### PR TITLE
Change Signature: Update all documents from the base solution

### LINKED ISSUE #784: Change Signature Removes wrong argument at Callsite
In [CSharpSyntaxContext](http://index/#Microsoft.CodeAnalysis.CSharp.Workspaces/Extensions/ContextQuery/CSharpSyntaxContext.cs, 12) of Roslyn Solution, try removing the argument `position` in any of the syntaxTree extension method call inside the `CsharpSyntaxContext` instantiation using ChangeSig(Invoked through Ctrl+.)

The call site removes `cancellationToken`, which is the second argument, instead of the `position` argument

--------

Couldn't get a simpler repo

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #784 and internal TFS issue 1102830

In change signature, when we needed to update 10 documents, we would
update the first document and replace it in the solution, then update
the second document and replace it in the solution, etc. However, if the
definition document is updated before a reference document, then trying
to bind the reference to the definition will not work correctly. Most of
the update process is syntactic so it usually doesn't matter, but we do
bind method references to see the invocation uses a reduced extension
method. This caused reduced extension method references to sometimes get
updated incorrectly.

We now produce all of the updated syntax trees from the same base
solution, and then apply them all at the end.

### CODE REVIEW

File: src/Features/Core/ChangeSignature/AbstractChangeSignatureService.cs [hunk 1]
```diff
@@ -279,7 +281,7 @@ private bool TryCreateUpdatedSolution(ChangeSignatureAnalyzedContext context, Ch
                     }
                 }
 
-                // TODO: Find references to containing type for Add methods & collection initializers (for example)
```
Comment (dpoeschl) [inline src/Features/Core/ChangeSignature/AbstractChangeSignatureService.cs]: TODO removed because we already have a bug tracking it

**Comment by dpoeschl** [comment]
Reviewers: @Pilchie @balajikris @basoundr @brettfo @rchande @jasonmalinowski

**Comment by balajikris** [comment]
Looks good to me. :+1:

**Comment by Pilchie** [comment]
:+1:
