### PR TITLE
Filter out missing import fixes that would add references

### LINKED ISSUE #34398: CSharpAddMissingImportsRefactoringProvider encountered an error
image

```
System.NotImplementedException : The method or operation is not implemented.
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedDocumentAsync(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddMissingImports.AbstractAddMissingImportsFeatureService.GetChangesForCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddMissingImports.AbstractAddMissingImportsFeatureService.ApplyFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddMissingImports.AbstractAddMissingImportsFeatureService.AddMissingImportsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.AddMissingImports.AbstractAddMissingImportsRefactoringProvider.AddMissingImports(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Hit this when i tired to copy the code from https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.formattedtext?view=netframework-4.7.2 to a class filein console application

### PR DESCRIPTION
**Pull request by JoeRobich**
Allow the user to choose when they want to add and which references they want to add to their project.

Resolves #34398, since the error is triggered by a foreground assertion when adding Framework assembly references.

### CODE REVIEW

File: src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs [hunk 1]
```diff
@@ -48,7 +48,14 @@ public async Task<Project> AddMissingImportsAsync(Document document, TextSpan te
             }
 
             // Find fixes for the diagnostic where there is only a single fix.
-            var usableFixes = await GetUnambiguousFixesAsync(document, diagnostics, cancellationToken).ConfigureAwait(false);
+            var unambiguousFixes = await GetUnambiguousFixesAsync(document, diagnostics, cancellationToken).ConfigureAwait(false);
+            if (unambiguousFixes.IsEmpty)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs]: this check seems superflous.

**Comment by JoeRobich** [comment]
@sharwell please take a look

**Comment by JoeRobich** [comment]
@vatsalyaagrawal for approval
