### PR TITLE
Remove redundant null check when using recursive patterns refactor

### LINKED ISSUE #64111: "Use recursive patterns" suggests redundant "this is { ... }" pattern
**Version Used**: 

Microsoft Visual Studio Enterprise 2022
Version 17.2.4
VisualStudio.17.Release/17.2.4+32602.215

C# Tools   4.2.0-4.22281.5+8d3180e5f00d42f0f0295165f756f368f0cbfa44

**Steps to Reproduce**:

```csharp
class Bar
{
    public Qux? Qux { get; }

    void Foo()
    {
        if (Qux != null && Qux.Color != ConsoleColor.Red)
        {
            Console.WriteLine("A");
        }
    }
}

class Qux
{
    public ConsoleColor Color { get; }
}
```

Generated code in `Foo` is equivalent to:

```csharp
	if (Qux != null && Qux.Color != ConsoleColor.Red) { ... }
```

**Expected Behavior**:

"Use recursive patterns" rewrites `Foo` to:

```csharp
    void Foo()
    {
        if (Qux is { Color: not ConsoleColor.Red })
        {
            Console.WriteLine("A");
        }
    }
```

Generated code in `Foo` is equivalent to:

```csharp
	Qux qux = Qux;
	if (qux != null && qux.Color != ConsoleColor.Red) { ... }
```

**Actual Behavior**:

"Use recursive patterns" rewrites `Foo` to:

```csharp
    void Foo()
    {
        if (this is { Qux: not null, Qux.Color: not ConsoleColor.Red })
        {
            Console.WriteLine("A");
        }
    }
```

where `this is { ... }` should always pass the `null` check, and simply using `Qux is { Color: not ConsoleColor.Red }` would already carry the `null` check for `Qux`.

Generated code has the redundant `null` check for `this`:

```csharp
	if (this != null)
	{
		Qux qux = Qux;
		if (qux != null && qux.Color != ConsoleColor.Red)
		{
			Console.WriteLine("A");
		}
	}
```

### PR DESCRIPTION
**Pull request by sdelarosbil**
Closes #64111 

The pr essentially tries to identify cases where we have a this.field != null condition where a pattern could be done with the field, but it has a null check that is redundant. When this happens, the null check side is thrown out leaving the pattern with the other side only.

### CODE REVIEW

File: src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs [hunk 1]
```diff
@@ -117,14 +117,29 @@ private static bool IsFixableNode(SyntaxNode node)
...
+                        var rightSubpattern = CreateSubpattern(rightNames, CreatePattern(rightReceiver, rightTarget, rightFlipped));
+                        var replacement = IsPatternExpression(commonReceiver, RecursivePattern(rightSubpattern));
+                        return root.ReplaceNode(logicalAnd, AdjustBinaryExpressionOperands(logicalAnd, replacement));
+                    }
+                    else if (rightNames.Length == 0)
+                    {
+                        var leftSubpattern = CreateSubpattern(leftNames, CreatePattern(leftReceiver, leftTarget, leftFlipped));
+                        var replacement = IsPatternExpression(commonReceiver, RecursivePattern(leftSubpattern));
+                        return root.ReplaceNode(logicalAnd, AdjustBinaryExpressionOperands(logicalAnd, replacement));
+                    }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs:135]: please doc these cases.  a good way to do this is to show the sort of code it would trigger for, and what it is replacing that code with.

File: src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs [hunk 2]
```diff
@@ -422,6 +439,29 @@ private static RecursivePatternSyntax RecursivePattern(SubpatternSyntax subpatte
                 commonReceiver = GetInnermostReceiver(left, lastName, static (identifierName, lastName) => identifierName != lastName);
             }
 
+            var iSymbol = model.GetSymbolInfo(leftNames[^1]).Symbol;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs:442]:
```suggestion
            var symbol = model.GetSymbolInfo(leftNames[^1]).Symbol;
```

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs:442]: this also needs doc'ing as well.  i have no idea why you're calling this on the leftmost name.

File: src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs [hunk 3]
```diff
@@ -422,6 +439,29 @@ private static RecursivePatternSyntax RecursivePattern(SubpatternSyntax subpatte
...
+            if (iSymbol != null && iSymbol.Equals(model.GetSymbolInfo(rightNames[^1]).Symbol))
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs:443]: no clue why this chekc is happening.  code needs docs.

File: src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs [hunk 4]
```diff
@@ -422,6 +439,29 @@ private static RecursivePatternSyntax RecursivePattern(SubpatternSyntax subpatte
...
+                    return (commonReceiver ?? ThisExpression(), ImmutableArray<IdentifierNameSyntax>.Empty, rightNames.ToImmutable());
+                }
+
+                if (rightIsNullCheck)
+                {
+                    lastName = leftNames[^1];
+                    commonReceiver = GetInnermostReceiver(left, lastName, static (identifierName, lastName) => identifierName != lastName);
+                    leftNames.Clip(leftNames.Count - 1);
+                    return (commonReceiver ?? ThisExpression(), leftNames.ToImmutable(), ImmutableArray<IdentifierNameSyntax>.Empty);
+                }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs:462]: all of this needs docs.

File: src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs [hunk 5]
```diff
@@ -450,6 +490,17 @@ static bool TryGetInnermostReceiver(ExpressionSyntax node, ArrayBuilder<Identifi
                 rightNames.Clip(rightIndex + 1);
                 return lastName;
             }
+
+            static bool IsNullCheck(SyntaxNode? exp)
+            {
+                if (exp is BinaryExpressionSyntax bin && bin.OperatorToken.Kind() == ExclamationEqualsToken
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs:496]: don't abbr.  can say `binaryExpression`.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs:496]: can check the kind directly.  like `is BinaryExpressionSyntax(SyntaxKind.NotEqualsExpression)`

**Comment by CyrusNajmabadi** [comment]
Can you add test with exactly the case from : https://github.com/dotnet/roslyn/issues/64111

File: src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs (hunk 1 above)
Comment (sdelarosbil) [reply src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs:135]: Added some comments explaining the logic

File: src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs (hunk 2 above)
Comment (sdelarosbil) [reply src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs]: I removed this. I didn't see there was a convenient method that did what I wanted and thought I needed to compare the symbols directly

File: src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs (hunk 4 above)
Comment (sdelarosbil) [reply src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs:467]: The comments hopefully explains it better, see if it's enough

File: src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs (hunk 5 above)
Comment (sdelarosbil) [reply src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs]: I tried this, it was breaking and I couldn't even get this to work in my IDE's evaluator during debugging, is this the correct why to do it?

**Comment by sdelarosbil** [comment]
> Can you add test with exactly the case from : #64111

Added.

Also curiously, the CI detected a test fail, but if I run the related tests, I couldn't get a fail so I am confused if it's my code or not...

File: src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs (hunk 3 above)
Comment (sdelarosbil) [reply src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs]: Same as before, I removed it since it wasn't necessary to do this.

File: src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs (hunk 5 above)
Comment (sdelarosbil) [reply src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs]: @CyrusNajmabadi hey, I am still waiting a response for this: are you sure this is the correct expression? I wasn't able to make it work.

**Comment by CyrusNajmabadi** [comment]
Looking.

File: src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs (hunk 5 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs]: Updated.

**Comment by CyrusNajmabadi** [comment]
LMK when this is ready for review.

**Comment by sdelarosbil** [comment]
> LMK when this is ready for review.

Actually, this was the only outstanding comment. The others I already addressed.

File: src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs [hunk 6]
```diff
@@ -117,14 +117,31 @@ private static bool IsFixableNode(SyntaxNode node)
...
+            if (TryGetCommonReceiver(leftReceiver, rightReceiver, leftTarget, rightTarget, model) is var (commonReceiver, leftNames, rightNames))
             {
                 return root =>
                 {
-                    var leftSubpattern = CreateSubpattern(leftNames, CreatePattern(leftReceiver, leftTarget, leftFlipped));
-                    var rightSubpattern = CreateSubpattern(rightNames, CreatePattern(rightReceiver, rightTarget, rightFlipped));
-                    var replacement = IsPatternExpression(commonReceiver, RecursivePattern(leftSubpattern, rightSubpattern));
-                    return root.ReplaceNode(logicalAnd, AdjustBinaryExpressionOperands(logicalAnd, replacement));
+                    // It's possible we decided to discard a pattern due to it being redundant (such as a null check
+                    // combined with a property check belonging to the same field we confirmed not being null)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs:125]: so i actually recommend giving examples in cases like this.  so show what sort of code the user would have started with, and what it would transform into.

File: src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs [hunk 7]
```diff
@@ -422,7 +441,36 @@ private static RecursivePatternSyntax RecursivePattern(SubpatternSyntax subpatte
...
             }
 
-            // If the common receiver is null, it's an implicit `this` reference in source.
+            // If the common receiver is null, there might still be one in cases like these:
+            // `MyClassField != null && MyClassField.prop != 0`. In this case, the left expression doesn't say
+            // anything new to the second one so it should be discarded, but MyClassField should still act as the
+            // receiver instead of the implicit this so we get
+            // `MyClassField is { prop: not 0 }` instead of `this is { MyClassField: not null, MyClassField.prop: not 0 }`
+            // We need to cover this case for either side of the expression by detecting a null check on either side
+            if (AreEquivalent(leftNames[^1], rightNames[^1]))
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs:450]: how do we know these are both non-empty? is it a guarantee of TryGetInnermostReceiver?

File: src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs [hunk 8]
```diff
@@ -117,14 +117,31 @@ private static bool IsFixableNode(SyntaxNode node)
...
+                        var rightSubpattern = CreateSubpattern(rightNames, CreatePattern(rightReceiver, rightTarget, rightFlipped));
+                        var replacement = IsPatternExpression(commonReceiver, RecursivePattern(rightSubpattern));
+                        return root.ReplaceNode(logicalAnd, AdjustBinaryExpressionOperands(logicalAnd, replacement));
+                    }
+                    else if (rightNames.Length == 0)
+                    {
+                        var leftSubpattern = CreateSubpattern(leftNames, CreatePattern(leftReceiver, leftTarget, leftFlipped));
+                        var replacement = IsPatternExpression(commonReceiver, RecursivePattern(leftSubpattern));
+                        return root.ReplaceNode(logicalAnd, AdjustBinaryExpressionOperands(logicalAnd, replacement));
+                    }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs:137]: i'm on the edge of wanting a local helper here, since tehse if/else blocks are nearly identical.  can you try taht out?  if it doesn't help, can keep like this.

File: src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs (hunk 4 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs:469]: this de feels like we should have a helper that both blocks share.

File: src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs (hunk 7 above)
Comment (sdelarosbil) [reply src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs:450]: Not the method itself, but yes in this context because both calls above this line needs to return true in order to not get an early return and for that to happen, they need to not be empty.

So we do have this guarantee here.

File: src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs (hunk 8 above)
Comment (sdelarosbil) [reply src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs:137]: I tried: it seemed to make it a bit messy (it involves a lot of parameters) and the case where both left and right are used makes it hard to extract so I will leave as is.

File: src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs (hunk 6 above)
Comment (sdelarosbil) [reply src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs]: Done.

**Comment by sdelarosbil** [comment]
@CyrusNajmabadi had to rebase + force push because the indentation of the file changed so I had to resolve the conflicts.

It is ready for another round of reviews.

File: src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs [hunk 9]
```diff
@@ -117,14 +117,33 @@ private static bool IsFixableNode(SyntaxNode node)
...
             return root =>
             {
-                var leftSubpattern = CreateSubpattern(leftNames, CreatePattern(leftReceiver, leftTarget, leftFlipped));
-                var rightSubpattern = CreateSubpattern(rightNames, CreatePattern(rightReceiver, rightTarget, rightFlipped));
-                var replacement = IsPatternExpression(commonReceiver, RecursivePattern(leftSubpattern, rightSubpattern));
-                return root.ReplaceNode(logicalAnd, AdjustBinaryExpressionOperands(logicalAnd, replacement));
+                // It's possible we decided to discard a pattern due to it being redundant (such as a null check
+                // combined with a property check belonging to the same field we confirmed not being null).
+                // For instance 'cf != null && cf.C != 0', the left null check doesn't add more information than the 
+                // right expression because the is pattern `cf is { C: not 0 }` already checks for null implicitly
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeRefactorings/UseRecursivePatterns/UseRecursivePatternsCodeRefactoringProvider.cs:127]: awesome.  this is great :)

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by sdelarosbil** [comment]
This CI test is odd: I tried it on my machine and it failed, but then I tried again later and now it passed.

I am not sure if it's my pr or not...

**Comment by sdelarosbil** [comment]
@CyrusNajmabadi ok I just rechecked to make sure and the test that's failing isn't my pr, but it is inconsistent: it may or may not fail.

Seems the test itself has an issue because I can make it fail on my machine, but very inconsistently

**Comment by CyrusNajmabadi** [comment]
> Seems the test itself has an issue because I can make it fail on my machine, but very inconsistently

It's a flakey test unfortunately.

**Comment by sdelarosbil** [comment]
@CyrusNajmabadi failed again :|

**Comment by CyrusNajmabadi** [comment]
@sdelarosbil we're investigating internally.  thanks :)
