### PR TITLE
Handle return statements with no expression in CSharpAsAndNullCheckDi…

### LINKED ISSUE #25237: NRE in Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpAsAndNullCheckDiagnosticAnalyzer
**Version Used**: 
VS 15.7

**Steps to Reproduce**:

1. Repo https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/Anycode
2. Branch Dev/rchiodo/add_logical_view_2
3. NuGet restore the main solution (src/Microsoft.VisualStudio.SLNX.sln) and then open in the IDE.

**Actual Behavior**:

Severity | Code | Description | Project | File | Line | Suppression State | Detail Description
-- | -- | -- | -- | -- | -- | -- | --
Error | AD0001 | Analyzer   'Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpAsAndNullCheckDiagnosticAnalyzer'   threw an exception of type 'System.NullReferenceException' with message   'Object reference not set to an instance of an object.'. | Microsoft.VisualStudio.Workspace.Implementation |   | 1 | Active | Analyzer   'Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpAsAndNullCheckDiagnosticAnalyzer'   threw the following exception:'Exception occurred with following   context:Compilation: Microsoft.VisualStudio.Workspace.ImplementationSyntaxTree:   F:\Anycode\Repo\src\Microsoft.VisualStudio.Workspace.Implementation\Workspace.csSyntaxNode:   return; [ReturnStatementSyntax]@[23344..23351)   (485,16)-(485,23)System.NullReferenceException: Object reference not set to   an instance of an object.   at   Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpAsAndNullCheckDiagnosticAnalyzer.GetLeftmostCondition(SyntaxNode   node)   at   Microsoft.CodeAnalysis.CSharp.UsePatternMatching.CSharpAsAndNullCheckDiagnosticAnalyzer.SyntaxNodeAction(SyntaxNodeAnalysisContext   syntaxContext)   at   Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__43`1.<ExecuteSyntaxNodeAction>b__43_0(ValueTuple`2   data)   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer   analyzer, Action`1 analyze, TArg argument, Nullable`1 info)-----'.

### PR DESCRIPTION
**Pull request by mavasani**
…agnosticAnalyzer.GetLeftmostCondition

Fixes #25237

<details><summary>Ask Mode template</summary>

### Customer scenario

Open a C# source file which has a void method with a `return;` statement.  The built-in IDE analyzer `CSharpAsAndNullCheckDiagnosticAnalyzer` throws a NullReferenceException producing an AD0001 diagnostic in the error list. Multiple instances of this diagnostic can easily show up in a normal C# solution.

### Bugs this fixes

https://github.com/dotnet/roslyn/issues/25237

### Workarounds, if any

Disable [IDE0019](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/Analyzers/IDEDiagnosticIds.cs,25) using a ruleset entry for every project that has return statements with no expression.

### Risk

Low risk. Fix involves just adding a null check.

### Performance impact

None

### Is this a regression from a previous update?

Yes, recent regression introduced in https://github.com/dotnet/roslyn/commit/10726d10d8a88af000c925fa5e3f5776dd7cbf4d#diff-64e1a867f5d1363da7ca518cdb658623.

### Root cause analysis

Missing unit tests. A regression test has been added with the PR. Verified the NRE on the added unit test before the fix.

### How was the bug found?

Dogfooding.

### Test documentation updated?

N/A
</details>

### CODE REVIEW

File: src/Features/CSharp/Portable/UsePatternMatching/CSharpAsAndNullCheckDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -423,6 +423,11 @@ private static SyntaxNode GetLeftmostCondition(SyntaxNode node)
                         continue;
                     case SyntaxKind.ReturnStatement:
                         node = ((ReturnStatementSyntax)node).Expression;
+                        if (node == null)
+                        {
+                            return null;
+                        }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/UsePatternMatching/CSharpAsAndNullCheckDiagnosticAnalyzer.cs]: consider adding the null check above the switch-statement.  then we can remove all the null checks inside the switch cases.

File: src/Features/CSharp/Portable/UsePatternMatching/CSharpAsAndNullCheckDiagnosticAnalyzer.cs [hunk 2]
```diff
@@ -413,6 +413,11 @@ private static SyntaxNode GetLeftmostCondition(SyntaxNode node)
         {
             while (true)
             {
+                if (node == null)
+                {
+                    return null;
```
Comment (Neme12) [inline src/Features/CSharp/Portable/UsePatternMatching/CSharpAsAndNullCheckDiagnosticAnalyzer.cs]: why not `while (node != null)`?

File: src/Features/CSharp/Portable/UsePatternMatching/CSharpAsAndNullCheckDiagnosticAnalyzer.cs [hunk 3]
```diff
@@ -428,13 +433,7 @@ private static SyntaxNode GetLeftmostCondition(SyntaxNode node)
...
                         // to simplify definitive assignment check and the code fix for now
-                        var value = declarators.Count == 1 ? declarators[0].Initializer?.Value : null;
-                        if (value == null)
-                        {
-                            return null;
-                        }
-
-                        node = value;
+                        node = declarators.Count == 1 ? declarators[0].Initializer?.Value : null;
                         continue;
```
Comment (Neme12) [inline src/Features/CSharp/Portable/UsePatternMatching/CSharpAsAndNullCheckDiagnosticAnalyzer.cs]: what about having `break;` in all cases and a `return` from the default case? might be easier to understand in my opinion than having `continue` from inside a switch statement

Comment (mavasani) [reply src/Features/CSharp/Portable/UsePatternMatching/CSharpAsAndNullCheckDiagnosticAnalyzer.cs]: I would prefer to keep an escrow regression fix minimal, without style changes. Personally, I also prefer code as per your suggestion, but the current style is also readable as we loop with explicit continue statements and exit when we reach null node or node of unhandled kind.

**Comment by CyrusNajmabadi** [comment]
+1 on making teh while loop simpler.  However, i would still keep the 'continue' form as that make a lot of sense to me.  Each block decomposes the node to get the 'left' side, then 'continues' the act of decomposition.  'break' makes me think that something will come 'next', when all that you really want to say is "keep going".

This is effectively a recursive algorithm that is non recursive (because of concerns about large expressions iirc).  So keeping the concepts similar between the two would be my preference.

**Comment by mavasani** [comment]
@jasonmalinowski @dotnet/roslyn-infrastructure - it seems ubuntu_16_mono_debug_prtest is failing for an unrelated reason, and it is failing in quite a few branches as well.

**Comment by jasonmalinowski** [comment]
@mavasani That's fine. This is a branch we just created for these bugfixes, and it doesn't have the fix to fix that. Go ahead and ignore it.

**Comment by jinujoseph** [comment]
QB approval pending

**Comment by jinujoseph** [comment]
Approved to merge via [link](https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_workitems/edit/577401)
