### PR TITLE
Fix a case where the stack spiller spills more than needed. (possibly resulting in false errors)

### LINKED ISSUE #17706: Compiler behaves unexpectedly when compiling specific combinations of ref and await expressions
**Version Used**: 
Master branch @ March 9
**Steps to Reproduce**:
Compile this code:
```csharp
using System.Threading.Tasks;
public class C {
    extern void N(int first, ref int second);
    extern ref int P {get;}
    
    public async void M(Task<int> t) {
        N(await t, ref P); // ok
        N(second: ref P, first: await t); // causes crash
    }
}
```

Or this code:
```csharp
using System.Threading.Tasks;
public class C {
    extern ref int M(int p);
    
    public async void M(Task<int> t) {
        M(await t)++;
    }
}
```

Not sure if they are related but effect is the same.

**Expected Behavior**:
First example: successful compilation.
Second example: error CS8178: 'await' cannot be used in an expression containing a call to 'C.M' because it returns by reference

**Actual Behavior**:
Crash.

And one more question. Why is the order of parameters (but not the evaluation order) is used to report error CS8178?

Example:
```csharp
using System.Threading.Tasks;
public class C {
    extern void M(ref int first, int second);
    
    extern ref int P {get;}
    public async void M(Task<int> t) {
        M(ref P, await t); // error
        M(second: await t, first: ref P); // error as well, but why?
    }
}
```

/cc @VSadov

### PR DESCRIPTION
**Pull request by VSadov**
Fixes:#17706

### Customer scenario

Customer uses code that involves a sequence of argument expressions that includes `await` - most commonly it is a method call with `await` among arguments, bit other more complex cases exist too.  

``` C#
Method(a(), b(), await c() + d(), e());  // must have empty stack when `await` happens
```

Since stack values cannot be preserved across `await` suspension, compiler turns the expressions that go before the `await` into statement forms that store evaluation results in temporaries, which are used to rebuild the argument values after resuming from the `await` suspension.

```C#
var t1 = a();
var t2 = b();
var t3 = await c();              // this `await` is ok since the stack is empty
Method(t1, t2, t3 + d(), e()) ;  // <-- should be rewritten like this
```

The problem is that compiler spills one more argument value than needed. 

```C#
var t1 = a();
var t2 = b();
var t3 = await c();
var t4 = d();                   // <-- this is redundant at best
Method(t1, t2, t3 + t4, e());    
```

In some cases it would make no difference (when spilling is a noop, like for constants), in some cases it will result in suboptimal, but correct code, and yet in some cases when argument happen to be unspillable (like a ref-returning member) it may result in a **false compile error**.

### Bugs this fixes

#17706

### Workarounds, if any

In some cases the differences are unobservable or an ignorable small degrade. No workaround is needed.

In other cases where it results in a compile error, user may refactor the code to "spill manually" and avoid using `await` in call arguments..

### Risk

Risk is low since it primarily affects cases where the difference is observable, which is a combination of method calls, `await` and ref-returning members.

### Performance impact

Low perf impact because no extra allocations/no complexity changes.

### Is this a regression from a previous update?

NO

### Root cause analysis

The bug involves a combination of features and in most cases leads to suboptimal, but correct code.

Tests are added for cases where the difference in spilling strategy leads to error/pass distinction.
There are existing tests where the change in code quality can be observed.

### How was the bug found?

Customer reported.

### Test documentation updated?

N/A

### CODE REVIEW

**Comment by VSadov** [comment]
@dotnet/roslyn-compiler - please review.

**Comment by VSadov** [comment]
Note - VB has a different implementation of stack spiller and it is not affected by this particular bug. A corresponding test has been added and it works as expected.

However VB seems to have other more general issues with spilling and ref-returning members. 
A bug logged to track: https://github.com/dotnet/roslyn/issues/17706

File: src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AwaitExpressionSpiller.cs [hunk 1]
```diff
@@ -455,13 +455,18 @@ private BoundStatement UpdateStatement(BoundSpillSequenceBuilder builder, BoundS
         {
             Debug.Assert(refKinds.IsDefault || refKinds.Length == args.Length);
 
+            if(args.Length == 0)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AwaitExpressionSpiller.cs]: Need a space here between `if` and `(`

File: src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AwaitExpressionSpiller.cs [hunk 2]
```diff
@@ -499,9 +506,17 @@ private BoundStatement UpdateStatement(BoundSpillSequenceBuilder builder, BoundS
                 }
             }
 
-            for (int i = lastSpill + 1; i < newList.Length; i++)
+            // the value of the last spill and everything that follows is not spilled
+            if (lastSpill < newList.Length)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AwaitExpressionSpiller.cs]: The use of `sideEffectsOnly` in this method seems inconsistent. Depending in the content of the `newList` when `sideEffectsOnly` is true we will return an empty list, a list which is part of `newList` or all of `newList`. That intuitively seems wrong. Am I missing something subtle here?

Comment (VSadov) [reply src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AwaitExpressionSpiller.cs]: `Spill` ensures that `replacement` is not sideeffecting (it is basically the "rehydrate" code). All sideeffects are moved into the spill builder. Therefore we can drop replacements when we know we only need sideeffects. - like if we are spilling a sequence. In fact some replacements are already `null` when coming from Spill - Spill knows when we do `sideeffectsOnly` and may just return `null` as the replacement as an easy-out when convenient. 

This is essentially an optimization, but it is an important one. 
If we keep unnecessary replacements, it will look like the values are spilled, survive across await and get restored - only to be unused later...

If we drop replacements right here, the spills become dead stores that do not need to be captured. Furthermore - IL Optimizer will kill dead stores and their locals, so only sideeffects will be emitted.

---
In reply to: [162102259](https://github.com/dotnet/roslyn/pull/24273#discussion_r162102259) [](ancestors = 162102259)

**Comment by VSadov** [comment]
@dotnet-bot test windows_release_vs-integration_prtest  please

**Comment by VSadov** [comment]
@dotnet/roslyn-compiler - PING. Can someone take a look?

File: src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AwaitExpressionSpiller.cs (hunk 2 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AwaitExpressionSpiller.cs]: At the same time though the method name is `VisitX` and it returns an array of varying length. Generally I would expect `VisitX` style methods to return an equivalent node. Maybe it's just the name throwing me off.

File: src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AwaitExpressionSpiller.cs [hunk 3]
```diff
@@ -487,21 +492,33 @@ private BoundStatement UpdateStatement(BoundSpillSequenceBuilder builder, BoundS
...
-            for (int i = 0; i <= lastSpill; i++)
+
+            // everything up until the last spill must be spilled entirely
+            for (int i = 0; i < lastSpill; i++)
             {
                 var refKind = refKinds.IsDefault ? RefKind.None : refKinds[i];
                 var replacement = Spill(builder, newList[i], refKind, sideEffectsOnly);
 
                 Debug.Assert(sideEffectsOnly || replacement != null);
+                Debug.Assert(!sideEffectsOnly || refKind == RefKind.None);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AwaitExpressionSpiller.cs]: >Debug.Assert(!sideEffectsOnly || refKind == RefKind.None); [](start = 16, length = 58)

Can we move this assert to the beginning of the function? Something like:
```
Debug.Assert(!sideEffectsOnly || refKinds.IsDefault);
```

File: src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AwaitExpressionSpiller.cs [hunk 4]
```diff
@@ -487,21 +492,33 @@ private BoundStatement UpdateStatement(BoundSpillSequenceBuilder builder, BoundS
             }
 
             var result = ArrayBuilder<BoundExpression>.GetInstance();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AwaitExpressionSpiller.cs]: >GetInstance [](start = 55, length = 11)

Can we guess the required size?

File: src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenRefReturnTests.vb [hunk 5]
```diff
@@ -2325,6 +2325,136 @@ BC31143: Method 'Public Overloads ByRef Function F() As Integer' does not have a
 </expected>)
         End Sub
 
+        <Fact>
+        <WorkItem(17706, "https://github.com/dotnet/roslyn/issues/17706")>
+        Public Sub SpillingByrefCall_NoSpilling()
```
Comment (cston) [inline src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenRefReturnTests.vb]: `ByRef`, here and in method below.

File: src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AwaitExpressionSpiller.cs (hunk 4 above)
Comment (VSadov) [reply src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AwaitExpressionSpiller.cs]: `newList.Length` would be a fair estimate. 

---
In reply to: [162473675](https://github.com/dotnet/roslyn/pull/24273#discussion_r162473675) [](ancestors = 162473675)

File: src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AwaitExpressionSpiller.cs (hunk 2 above)
Comment (VSadov) [reply src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AwaitExpressionSpiller.cs]: I think the confusing part is that this is a bit of unusual rewrite. It is not purely node-to-node. We are also filling up a builder. Parts of the input may move into the builder so it may appear that we have lost something. 
Most of the VisitX methods in this rewriter are like that. 

---
In reply to: [162472242](https://github.com/dotnet/roslyn/pull/24273#discussion_r162472242) [](ancestors = 162472242)

**Comment by VSadov** [comment]
CC @MeiChin-Tsai for ask mode approval

**Comment by MeiChin-Tsai** [comment]
approved.

**Comment by VSadov** [comment]
Thanks!!
