### PR TITLE
Fixed VS2017 crash with :: operator

### LINKED ISSUE #23940: VS2017 crash with :: operator
I'm attempting to to type in this program. VS 2017 crashes after I type the word `List` in `Col::List`

```csharp
using System;
using Col = System.Collections.Generic;

namespace AliasTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var list1 = new Col::List<int>
        }
    }
}
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/155278/vs2017-crash-with-operator.html
VSTS ticketId: 529066_
_These are the original issue comments:_

Michael Quinlan on ‎11‎/‎24‎/‎2017, 07:17 AM (32 days ago): <p>The code is C#. The problem only happens when I actually type in the code; VS 2017 doesn't crash if I copy-paste the program.</p><p>In Options under Text Editor--&gt;C#--&gt;IntelliSense, I tried disabling 'Show completion list after a character is typed', 'Highlight matching portions of completion list items', and 'Show completion item filters' but the problem still occurred.</p>

Michael Quinlan on ‎12‎/‎5‎/‎2017, 02:13 PM (20 days ago): <p>Problem still occurs is Visual Studio 15.5.0 (edit to add: Community Edition)</p>

_These are the original issue solutions:_
(no solutions)

### PR DESCRIPTION
**Pull request by zaytsev-victor**
### Customer scenario

A customer attempts to use the alias qualification operator `::` to refer to a namespace.

### Bugs this fixes

Fixes #23940

### Workarounds, if any

Avoid using this syntax.

### Risk

Low.

### Performance impact

Negligible. Adds a type check that is only needed in this case.

### Is this a regression from a previous update?

No.

### Root cause analysis

No one considered this syntax in testing. @sharwell wasn't even aware it was valid.

### How was the bug found?

Reported via developer community.

### Test documentation updated?

No.

### CODE REVIEW

File: src/Workspaces/CSharp/Portable/Extensions/ExpressionSyntaxExtensions.cs [hunk 1]
```diff
@@ -2578,6 +2578,11 @@ public static SimpleNameSyntax GetRightmostName(this ExpressionSyntax node)
                 return memberBinding.Name;
             }
 
+            if (node is AliasQualifiedNameSyntax aliasQualifiedName && aliasQualifiedName.Name != null)
+            {
+                return aliasQualifiedName.Name;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Extensions/ExpressionSyntaxExtensions.cs]: If this fixes a crash, then it seems like that would be because returning null below causes a problem.  Which means the caller of this method shoul dbe updated to be resilient to getting null back, as that's part of the contract of this method.

Comment (zaytsev-victor) [reply src/Workspaces/CSharp/Portable/Extensions/ExpressionSyntaxExtensions.cs]: Good point, thanks!

Comment (jasonmalinowski) [reply src/Workspaces/CSharp/Portable/Extensions/ExpressionSyntaxExtensions.cs]: @zaytsev-victor Should we undo this change then, since the change in NameSyntaxClassifier.cs is the right one?

Comment (zaytsev-victor) [reply src/Workspaces/CSharp/Portable/Extensions/ExpressionSyntaxExtensions.cs]: @jasonmalinowski No, we should not undo this change, because this the fix. Without this change
```Col::List``` would not be recognized that ```List``` is the type.

Comment (CyrusNajmabadi) [reply src/Workspaces/CSharp/Portable/Extensions/ExpressionSyntaxExtensions.cs]: Consider renamign this method to TryGetRightmostName.  That will allow us to audit all the callers.

**Comment by sharwell** [comment]
@Pilchie for ask mode

**Comment by Pilchie** [comment]
Needs passing tests.

**Comment by Pilchie** [comment]
Approved for 15.6 Preview 4 (pending passing tests)
