### PR TITLE
Report CS0675 warning for compound assignment operator.

### LINKED ISSUE #909: Warning CS0675 fired in Dev12 but not Dev14
The following code generates CS0675 when built with Dev12, but doesn't on Dev14 (I think I am using the Dev14 CPT 5 build.  The build number is 14.0.22512.0 DP).

```csharp

long bits = 0;
for (int i = 0; i < 32; i++)
{
    if (i % 2 == 0)
    {
        bits |= (1 << i);
    }
}
```

I'm not sure if this is a regression or by design change.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #909.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@VSadov, @gafter, @agocke, @jaredpar Please review.

**Comment by VSadov** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs [hunk 1]
```diff
@@ -388,7 +399,7 @@ private void CheckVacuousComparisons(BoundBinaryOperator tree, ConstantValue con
             }
         }
 
-        private void CheckOr(BoundBinaryOperator node)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs]: IMHO the name of this method is a bit misleading.  Can we rename it to `CheckIfOr` or add a comment specifying that it only performs checks in the case that it is an `Or` style operator?

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs]: @jaredpar How does "CheckForBitwiseOrSignExtend" sound?

Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs]: SGTM

Overall change LGTM as well.

JaredPar from a phone
http://blog.paranoidcoding.com/
________________________________
