### PR TITLE
Do not report IDE0059 for reference taken symbols

### LINKED ISSUE #40717: IDE0059 (Unnecessary assignment of a value) should not be reported for variables that are passed by reference
**Version Used**: 
VS2019 16.4.2
.NET Core 3.1

**Steps to Reproduce**:
```c#
static int Example()
{
    int value = 123;

    Span<int> valueSpan = MemoryMarshal.CreateSpan(ref value, 1);

    value = 456;

    return valueSpan[0];
}
```

**Expected Behavior**:
No suggestion to remove the assignment ``value = 456;``

**Actual Behavior**:
Suggestion to remove ``value = 456;``

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #40717

### CODE REVIEW

File: src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.AnalysisData.cs [hunk 1]
```diff
@@ -193,7 +199,7 @@ public void OnReadReferenceFound(ISymbol symbol)
                 SymbolsReadBuilder.Add(symbol);
             }
 
-            public void OnWriteReferenceFound(ISymbol symbol, IOperation operation, bool maybeWritten)
+            public void OnWriteReferenceFound(ISymbol symbol, IOperation operation, bool maybeWritten, bool isRef)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.AnalysisData.cs]: could you just take in a ValueUsageInfo  instead of thse two variables?

File: src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.AnalysisData.cs [hunk 2]
```diff
@@ -240,6 +257,7 @@ protected virtual void DisposeCoreData()
             {
                 SymbolsWriteBuilder.Free();
                 SymbolsReadBuilder.Free();
+                _referenceTakenSymbolsBuilder.Free();
```
Comment (genlu) [inline src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.AnalysisData.cs]: It seems base.DisposeCoreData() isn't always called in FlowGraphAnalysisData, are we leaking those pooled memory?

Comment (mavasani) [reply src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.AnalysisData.cs]: Good catch! Thanks, fixed now.

File: src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.AnalysisData.cs (hunk 1 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.AnalysisData.cs]: Possibly, but I wasn't sure how would this callsite be encoded: https://github.com/dotnet/roslyn/pull/40900/files#diff-6a1d90ea5d0ff913914c081c7a378a73R430

File: src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.AnalysisData.cs [hunk 3]
```diff
@@ -243,14 +260,15 @@ protected virtual void DisposeCoreData()
                 LambdaOrLocalFunctionsBeingAnalyzed.Free();
```
Comment (genlu) [inline src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.AnalysisData.cs]: Shouldn't these guys be moved to `DisposeAllocatedPrivateData` too? Then we can make `DisposeCoreData` abstract

Comment (mavasani) [reply src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.AnalysisData.cs]: No, because these are actually shared between instances of FlowGraphAnalysisData and allocated by sub-types. Let me clean this all up in a separate PR.

Comment (genlu) [reply src/Workspaces/Core/Portable/FlowAnalysis/SymbolUsageAnalysis/SymbolUsageAnalysis.AnalysisData.cs]: Sorry, I missed the other comment, please ignore.

**Comment by mavasani** [comment]
@genlu Any further feedback? I plan to work on refactoring the dispose code in a follow-up PR.

**Comment by mavasani** [comment]
Thanks, will send a follow-up PR for refactoring later today.
