### PR TITLE
 Not offering UseAutoProperty for volatile fields & when field used with ref

### LINKED ISSUE #25379: IDE0032 should not be reported for volatile fields
**Version Used**: Visual Studio Community 15.6.1

**Steps to Reproduce**:
Here is the example code.

```csharp
class Class1
{
    private volatile int _field1;

    public int Property1
    {
        get { return this._field1; }
        set { this._field1 = value; }
    }

    public int Property2 { get; set; }
}
```

`Property1` is a wrapper for `_field1`, which has `volatile` modifier. `Property2` is a normal auto property, which is written for comparison.

Visual Studio says `_field1` can be an auto property.

Screenshot of Code Action

**Expected Behavior**: This suggestion should not be shown because the field has `volatile` modifier.

The way to access to volatile fields is different from the way to access to normal fields. Access to volatile fields needs `volatile.` prefix in IL. So the field cannot be an auto property in the present case.

### LINKED ISSUE #25429: UseAutoProperty generates invalid code when using ref on the field
```c#
class Class
{
    int value;
    int Value
    {
        get { return value; }
    }

    void M()
    {
        ref int x = ref value;
    }
}
```

applying the code fix results in:
```c#
class Class
{
    int Value { get; set; }
    
    void M()
    {
        ref int x = ref Value;
    }
}
```
which doesn't compile because Value doesn't return by ref.

### PR DESCRIPTION
**Pull request by Neme12**
fixes #25379
fixes #25429

### CODE REVIEW

File: src/EditorFeatures/CSharp/UseAutoProperty/UseAutoPropertyAnalyzer.cs [hunk 1]
```diff
@@ -16,7 +16,8 @@ namespace Microsoft.CodeAnalysis.Editor.CSharp.UseAutoProperty
 {
     [Export]
     [DiagnosticAnalyzer(LanguageNames.CSharp)]
-    internal class CSharpUseAutoPropertyAnalyzer : AbstractUseAutoPropertyAnalyzer<PropertyDeclarationSyntax, FieldDeclarationSyntax, VariableDeclaratorSyntax, ExpressionSyntax>
+    internal class CSharpUseAutoPropertyAnalyzer : AbstractUseAutoPropertyAnalyzer<
```
Comment (Neme12) [inline src/EditorFeatures/CSharp/UseAutoProperty/UseAutoPropertyAnalyzer.cs]: I only wrapped what went past the GitHub limit (130 characters)

File: src/EditorFeatures/CSharp/UseAutoProperty/UseAutoPropertyAnalyzer.cs [hunk 2]
```diff
@@ -71,50 +72,53 @@ protected override bool CanExplicitInterfaceImplementationsBeFixed()
...
             {
-                AddIneligibleField(symbol, ineligibleFields);
+                AddSymbol(symbol);
             }
-        }
 
-        private static void AddIneligibleField(ISymbol symbol, HashSet<IFieldSymbol> ineligibleFields)
-        {
-            if (symbol is IFieldSymbol field)
+            void AddSymbol(ISymbol symbol)
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharp/UseAutoProperty/UseAutoPropertyAnalyzer.cs]: can you still call this "AddIneligibleField"

Comment (Neme12) [reply src/EditorFeatures/CSharp/UseAutoProperty/UseAutoPropertyAnalyzer.cs]: @CyrusNajmabadi I originally did but then realized it might be a little misleading because it could add more than 1 symbol

Comment (Neme12) [reply src/EditorFeatures/CSharp/UseAutoProperty/UseAutoPropertyAnalyzer.cs]: whereas the previous method called 'AddIneligibleField' only took the symbol (I changed that one into a local function)

Comment (Neme12) [reply src/EditorFeatures/CSharp/UseAutoProperty/UseAutoPropertyAnalyzer.cs]: but I'm not saying it's a good name as is...

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharp/UseAutoProperty/UseAutoPropertyAnalyzer.cs]: okey dokey

Comment (Neme12) [reply src/EditorFeatures/CSharp/UseAutoProperty/UseAutoPropertyAnalyzer.cs]: @CyrusNajmabadi wait, I didn't look properly that you pointed this at the local function itself... yes I could call this AddIneligibleField, but what about AddIneligibleFields then? did you notice both of them?

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharp/UseAutoProperty/UseAutoPropertyAnalyzer.cs]: > should they have names differing in 1 letter only?

That's fine.  It's fairly common in our code base.  A higher level functoin that operates on a collection of items, which calls a helper which works on a single element.

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharp/UseAutoProperty/UseAutoPropertyAnalyzer.cs]: > yes I could call this AddIneligibleField

great.

**Comment by Neme12** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

**Comment by Neme12** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please

**Comment by Neme12** [comment]
retest perf_correctness_prtest please

**Comment by DustinCampbell** [comment]
@dotnet-bot retest this please

**Comment by Neme12** [comment]
retest this please

**Comment by Neme12** [comment]
retest windows_debug_unit32_prtest please

**Comment by DustinCampbell** [comment]
Thanks again @Neme12
