### PR TITLE
Copy all diagnostic info from derived classes when changing severity of a diagnostic

### LINKED ISSUE #66037: Additional location on CS8618 is lost with warnAsError = true
Issue identified while investigating https://github.com/dotnet/efcore/issues/29582.

Below compiler unit test succeeds with `warnAsError = false` but fails on the last line when `warnAsError = true`. `AdditionalLocations` on the compiler diagnostic seem to get lost when it's effective severity is changed. https://github.com/dotnet/roslyn/pull/58096 added this additional location for CS8618

```csharp
        [Theory]
        [CombinatorialData]
        [WorkItem(66037, "https://github.com/dotnet/roslyn/issues/66037")]
        public void TestAdditionalLocationOnCompilerDiagnostic(bool warnAsError)
        {
            var options = WithNullableEnable();
            if (warnAsError)
            {
                options = options.WithGeneralDiagnosticOption(ReportDiagnostic.Error);
            }

            var comp = CreateCompilation(@"
public class B
{
    public B? f2;
}
public class C
{
    public B f;
    static void Main()
    {
        new C() { f = { f2 = null }};
    }
}", options: options);

            var diagnostics = comp.GetDiagnostics();
            diagnostics.Verify(
                // (8,14): warning CS8618: Non-nullable field 'f' must contain a non-null value when exiting constructor. Consider declaring the field as nullable.
                //     public B f;
                Diagnostic(ErrorCode.WRN_UninitializedNonNullableField, "f").WithArguments("field", "f").WithLocation(8, 14).WithWarningAsError(warnAsError));

            var diagnostic = Assert.Single(diagnostics);
            Assert.Single(diagnostic.AdditionalLocations);
        }
```

```
Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.NullableReferenceTypesTests.TestAdditionalLocationOnCompilerDiagnostic(warnAsError: True)
   Source: NullableReferenceTypesTests.cs line 545
   Duration: 9 ms

  Message: 
    The collection was expected to contain a single element, but it was empty.

  Stack Trace: 
    NullableReferenceTypesTests.TestAdditionalLocationOnCompilerDiagnostic(Boolean warnAsError) line 574
```

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #66037

The issue is specific to `CSDiagnostic` not copying AdditionalLocations over when `GetInstanceWithSeverity` is called. But I made sure all subtypes of `DiagnosticInfo` copy everything they contain. I think it might be painful to figure out tests for every override I added, but it just makes sense to keep all info when `GetInstanceWithSeverity` is called.

@mavasani Can you take a look?

### CODE REVIEW

**Comment by mavasani** [comment]
I think we should first settle on the preferred design from the compiler team on where the additional locations should be stored before working on this fix: https://github.com/dotnet/roslyn/issues/66037#issuecomment-1354605898.

**Comment by Youssef1313** [comment]
Converted to a draft until the compiler team confirms the design.

File: src/Compilers/CSharp/Portable/Errors/CSDiagnosticInfo.cs [hunk 1]
```diff
@@ -42,6 +42,16 @@ internal CSDiagnosticInfo(ErrorCode code, object[] args, ImmutableArray<Symbol>
             _additionalLocations = additionalLocations.IsDefaultOrEmpty ? SpecializedCollections.EmptyReadOnlyList<Location>() : additionalLocations;
         }
 
+        private CSDiagnosticInfo(CSDiagnosticInfo original, DiagnosticSeverity severity) : base(original, severity)
+        {
+            _additionalLocations = original._additionalLocations;
+        }
+
+        internal override DiagnosticInfo GetInstanceWithSeverity(DiagnosticSeverity severity)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Errors/CSDiagnosticInfo.cs:50]: FWIW, it seems to me that dropping information about the original instance, when creating a derived instance, is a cut-and-dry bug, and it seems perfectly fine to take this change as a starting point, even if we think more refactoring is desirable. cc @jcouv @dotnet/roslyn-compiler.

Comment (jcouv) [reply src/Compilers/CSharp/Portable/Errors/CSDiagnosticInfo.cs:50]: I'm okay with that as well. Fixing the deeper design issue seems orthogonal and outside the scope for this bug.

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Errors/CSDiagnosticInfo.cs:50]: @jcouv @RikkiGibson So is it possible to merge this as-is, and follow up on https://github.com/dotnet/roslyn/issues/66037#issuecomment-1354605898 later?

Unfortunately, I'm currently putting less time for open source due to exams (it ends 25 January).

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Errors/CSDiagnosticInfo.cs:50]: I'll review more carefully, and given the impact, I think it's reasonable for us to push to the PR branch to resolve any issues we identify, and merge without you needing to do anything more. Thanks, and good luck on exams 😄

**Comment by RikkiGibson** [comment]
Will try to address the broken test baseline and also introduce a guardrail so that we don't miss any future cases where changing severity results in us dropping info.

**Review by RikkiGibson — APPROVED** [review]

**Comment by RikkiGibson** [comment]
For expediency I'm delaying introducing the guardrail mentioned above and just getting the PR which fixes the issue into a ship-ready state.

File: src/Compilers/CSharp/Portable/Errors/CSDiagnosticInfo.cs [hunk 2]
```diff
@@ -42,6 +42,16 @@ internal CSDiagnosticInfo(ErrorCode code, object[] args, ImmutableArray<Symbol>
...
+        {
+            return new CSDiagnosticInfo(this, severity);
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Errors/CSDiagnosticInfo.cs:52]: Looks like CommonMessageProvider.FilterDiagnosticInfo doesn't check for equal severity, but it is only used to report analyzer load failures.

https://github.com/dotnet/roslyn/blob/8e0c2b0d227d6f0d9f5ca2213cde7e08d992e02c/src/Compilers/Core/Portable/Diagnostic/CommonMessageProvider.cs#L129-L151

DiagnosticWithInfo and CSDiagnostic does check for equal severity and looks to be the more common path.

https://github.com/dotnet/roslyn/blob/8e0c2b0d227d6f0d9f5ca2213cde7e08d992e02c/src/Compilers/Core/Portable/Diagnostic/DiagnosticWithInfo.cs#L210-L218

I wouldn't change DiagnosticInfo's responsibility to check for equal severity as part of this fix.

File: src/Compilers/CSharp/Portable/Errors/LazyDiagnosticInfo.cs [hunk 3]
```diff
@@ -25,6 +25,11 @@ internal sealed override DiagnosticInfo GetResolvedInfo()
             return _lazyInfo;
         }
 
+        protected LazyDiagnosticInfo(LazyDiagnosticInfo original, DiagnosticSeverity severity) : base(original, severity)
+        {
+            _lazyInfo = original._lazyInfo;
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Errors/LazyDiagnosticInfo.cs:31]: >} [](http://example.com/codeflow?start=8&length=1)

We should include:
```csharp
internal abstract override DiagnosticInfo GetInstanceWithSeverity(DiagnosticSeverity severity);
```

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Errors/LazyDiagnosticInfo.cs:31]:
```suggestion
        }

        internal abstract override DiagnosticInfo GetInstanceWithSeverity(DiagnosticSeverity severity);
```

**Comment by Youssef1313** [comment]
```
D:\a\_work\1\s\.dotnet\sdk\7.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1004: Assets file 'D:\a\_work\1\s\artifacts\obj\Microsoft.Net.Compilers.Toolset.Package\project.assets.json' not found. Run a NuGet package restore to generate this file. [D:\a\_work\1\s\src\NuGet\Microsoft.Net.Compilers.Toolset\AnyCpu\Microsoft.Net.Compilers.Toolset.Package.csproj::TargetFramework=net6.0]
```

Couple of jobs are failing with errors like this. I don't think this is related to the PR.

**Comment by RikkiGibson** [comment]
There was an Azure outage early this morning, we suspect today's CI failures are related. We'll try again later.

**Review by RikkiGibson — APPROVED** [review]

File: src/Compilers/Core/Portable/Diagnostic/DiagnosticInfo.cs [hunk 4]
```diff
@@ -165,7 +165,21 @@ internal DiagnosticInfo(CommonMessageProvider messageProvider, bool isWarningAsE
...
 
         // Create a copy of this instance with a explicit overridden severity
-        internal virtual DiagnosticInfo GetInstanceWithSeverity(DiagnosticSeverity severity)
+        internal DiagnosticInfo GetInstanceWithSeverity(DiagnosticSeverity severity)
+        {
+            if (Severity != severity)
+            {
+                var result = GetInstanceWithSeverityCore(severity);
+                // If this assert fails it means a subtype of DiagnosticInfo failed to override GetInstanceWithSeverityCore
+                Debug.Assert(this.GetType() == result.GetType());
```
Comment (Youssef1313) [inline src/Compilers/Core/Portable/Diagnostic/DiagnosticInfo.cs:174]: This doesn't solve the problem when the missing override is in `abstract` type in the middle of the inheritance hierarchy right?

Comment (RikkiGibson) [reply src/Compilers/Core/Portable/Diagnostic/DiagnosticInfo.cs:174]: I think we don't mind if an abstract type is missing the override. We just care if a type that was actually created is missing it--if some subtype went to the trouble of declaring it, I guess we just have to hope it didn't drop information from its base type :P

**Comment by RikkiGibson** [comment]
@cston @jcouv @dotnet/roslyn-compiler I believe I've addressed the remaining concerns on Youssef's behalf. Please take another look when you get the chance.

**Comment by cston** [comment]
Should we include a simple test? The following hits most of the clone methods.
```csharp
[Fact]
public void DiagnosticInfo_WithSeverity()
{
    var comp = CreateCompilation("");
    var args = new object[] { comp.GlobalNamespace };
    var symbol = (Symbol)comp.GlobalNamespace;
    var type = TypeWithAnnotations.Create(comp.GetSpecialType(SpecialType.System_Object));

    verifyWithSeverity(new CSDiagnosticInfo(ErrorCode.ERR_AbstractField));
    verifyWithSeverity(new DiagnosticInfoWithSymbols(ErrorCode.ERR_DuplicateTypeParameter, args,
        ImmutableArray.Create(symbol)));
    verifyWithSeverity(new LazyArrayElementCantBeRefAnyDiagnosticInfo(type));
    verifyWithSeverity(new LazyObsoleteDiagnosticInfo(symbol, symbol, BinderFlags.None));
    verifyWithSeverity(new LazyUseSiteDiagnosticsInfoForNullableType(LanguageVersion.CSharp11, type));
    verifyWithSeverity(new SyntaxDiagnosticInfo(1, 2, ErrorCode.ERR_DuplicateTypeParameter, args));
    verifyWithSeverity(new XmlSyntaxDiagnosticInfo(XmlParseErrorCode.XML_EndTagExpected, args));

    static void verifyWithSeverity(DiagnosticInfo diagnostic)
    {
        var other = diagnostic.GetInstanceWithSeverity(DiagnosticSeverity.Info);
        Assert.NotSame(diagnostic, other);
        Assert.Equal(DiagnosticSeverity.Info, other.Severity);
    }
}
```

File: src/Compilers/CSharp/Portable/Errors/CSDiagnosticInfo.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Errors/CSDiagnosticInfo.cs:52]: We ended up refactoring so that DiagnosticInfo.WithSeverity checks if the new severity is different.

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs [hunk 5]
```diff
@@ -102,6 +104,31 @@ public void TestCustomErrorInfo()
...
+                ImmutableArray.Create(symbol)));
+            verifyWithSeverity(new LazyArrayElementCantBeRefAnyDiagnosticInfo(type));
+            verifyWithSeverity(new LazyObsoleteDiagnosticInfo(symbol, symbol, BinderFlags.None));
+            verifyWithSeverity(new LazyUseSiteDiagnosticsInfoForNullableType(LanguageVersion.CSharp11, type));
+            verifyWithSeverity(new SyntaxDiagnosticInfo(1, 2, ErrorCode.ERR_DuplicateTypeParameter, args));
+            verifyWithSeverity(new XmlSyntaxDiagnosticInfo(XmlParseErrorCode.XML_EndTagExpected, args));
+
+            static void verifyWithSeverity(DiagnosticInfo diagnostic)
+            {
+                var other = diagnostic.GetInstanceWithSeverity(DiagnosticSeverity.Info);
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs:126]: nit: you could also verify that the instance remains identical when the severity isn't different

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 8) with a test suggestion to consider

**Comment by RikkiGibson** [comment]
Thanks @Youssef1313!

**Comment by Youssef1313** [comment]
@RikkiGibson Thanks for taking it over to completion too! ❤️
