### PR TITLE
Fix outlining banner with whitespace between hash and region.

### LINKED ISSUE #4105: Adding a space between # and region causes #region to show extra text when it is collapsed
If there is whitespace between `#` and `region`, the collapsed banner text is incorrect.

```C#
#  region Something
        Console.WriteLine();
#  endregion
```

image

### PR DESCRIPTION
**Pull request by Pilchie**
Fixes #4105.

### CODE REVIEW

**Comment by Pilchie** [comment]
@dotnet-bot retest this please

**Comment by Pilchie** [comment]
@DustinCampbell @jasonmalinowski @dpoeschl @brettfo @balajikris @basoundr @jmarolf @rchande @davkean Anyone want to take a look?

**Comment by dpoeschl** [comment]
:+1:

File: src/EditorFeatures/CSharpTest/Outlining/RegionDirectiveOutlinerTests.cs [hunk 1]
```diff
@@ -89,5 +89,21 @@ static void Main(string[] args)
 }
 ");
         }
+
+        [Fact, Trait(Traits.Feature, Traits.Features.Outlining)]
+        [WorkItem(4105, "https://github.com/dotnet/roslyn/issues/4105")]
+        public void SpacesBetweenPoundAndRegionShouldNotAffectBanner()
```
Comment (jasonmalinowski) [inline src/EditorFeatures/CSharpTest/Outlining/RegionDirectiveOutlinerTests.cs]: Can this happen in VB as well?

**Comment by jasonmalinowski** [comment]
:+1:

File: src/EditorFeatures/CSharpTest/Outlining/RegionDirectiveOutlinerTests.cs (hunk 1 above)
Comment (Pilchie) [inline src/EditorFeatures/CSharpTest/Outlining/RegionDirectiveOutlinerTests.cs]: It's not an issue in VB, because VB includes the whole `#Region` line in the collapsed section and the banner.
