### PR TITLE
Fix duplicate/inaccurate results in LSP GoToImpl

### LINKED ISSUE #44846: VS LSP: Go to implementation/declaration produces inaccurate/duplicate results
**Version Used**: 16.7.0 Preview 3.0 [30203.137.master]

**Steps to Reproduce**:

gotoimplementationbug

image

cc @dibarbet @NTaylorMullen

### PR DESCRIPTION
**Pull request by allisonchou**
Fixes #44846

### CODE REVIEW

File: src/Features/LanguageServer/Protocol/Handler/References/FindImplementationsHandler.cs [hunk 1]
```diff
@@ -47,7 +47,7 @@ public FindImplementationsHandler()
             foreach (var definition in context.GetDefinitions())
             {
                 var text = definition.GetClassifiedText();
-                foreach (var sourceSpan in context.GetDefinitions().SelectMany(definition => definition.SourceSpans))
```
Comment (dibarbet) [inline src/Features/LanguageServer/Protocol/Handler/References/FindImplementationsHandler.cs:50]: :O not sure what the original code was trying to do!

**Comment by allisonchou** [comment]
@dibarbet done! Thanks for the suggestion, forgot that LSP had some tests.
