### PR TITLE
Avoid reentrancy in ConditionalWeakTable

### LINKED ISSUE #28256: Reentrancy in SnapshotSourceText.From() causes exception on Mono
See Mono Runtime bug https://github.com/mono/mono/issues/8700

Roslyn has a situation where the delegate used to create the value when ConditionalWeakTable.GetValue returns false goes ahead and reentrantly adds the same value to the weak table, so by the time the delegate returns and the ConditionalWeakTable wants to add the result, it is already there, causing this line to throw:
https://github.com/mono/mono/blob/217a1424ee083283f53ccda4b8be8ff87d62463f/mcs/class/corlib/System.Runtime.CompilerServices/ConditionalWeakTable.cs#L201

While we work with the Mono runtime team to try to fix this bug, it would be nice to see if the Roslyn team can find a workaround that would avoid reentrancy here. Maybe a simple lock as a temporary workaround. Even if the runtime team fixes the bug, it will take time for the fixed version of Mono to propagate around, so ideally we'd need a fix in Roslyn.

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #28256 

### Customer scenario

Runs Visual Studio for Mac on Mono.

### Bugs this fixes

#28256

### Workarounds, if any

None

### Risk

Low. A call sequence is split to break recursion without changing the overall algorithm.

### Performance impact

Negligible.

### Is this a regression from a previous update?

No.

### Root cause analysis

The .NET Framework supports the case in question without causing problems. The bug only appears in certain cases when running on Mono.

### How was the bug found?

Reported by @KirillOsenkov from a review of Visual Studio for Mac customer reports.

### Test documentation updated?

N/A

</details>

### CODE REVIEW

File: src/EditorFeatures/Text/Extensions.SnapshotSourceText.cs [hunk 1]
```diff
@@ -80,9 +80,13 @@ public static SourceText From(ITextBufferCloneService textBufferCloneServiceOpt,
...
                 if (!s_textSnapshotMap.TryGetValue(editorSnapshot, out var snapshot))
                 {
+                    // Explicitly obtain the TextBufferContainer before calling GetValue to avoid reentrancy in
+                    // ConditionalWeakTable. https://github.com/dotnet/roslyn/issues/28256
+                    var container = TextBufferContainer.From(editorSnapshot.TextBuffer);
+
                     // Avoid capturing `textBufferCloneServiceOpt` on the fast path
                     var tempTextBufferCloneServiceOpt = textBufferCloneServiceOpt;
-                    snapshot = s_textSnapshotMap.GetValue(editorSnapshot, s => new SnapshotSourceText(tempTextBufferCloneServiceOpt, s));
+                    snapshot = s_textSnapshotMap.GetValue(editorSnapshot, s => new SnapshotSourceText(tempTextBufferCloneServiceOpt, s, container));
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Text/Extensions.SnapshotSourceText.cs]: do we still need the version of the constructor that doesn't take a container?

Comment (CyrusNajmabadi) [reply src/EditorFeatures/Text/Extensions.SnapshotSourceText.cs]: looking at current roslyn, it appears as if the answer is 'no'.  so i would remove that constructor if possible.

**Comment by sharwell** [comment]
Rebased/retargeted to **dev15.9.x** and removed the unused constructor.

**Comment by KirillOsenkov** [comment]
We hope that long term the Mono runtime will fix the bug https://github.com/mono/mono/issues/8700 so it won't be necessary to defend against reentrancy here.
