### PR TITLE
Fixed IDE0044 (Make Field Readonly) for DataMember fields in DataContract classes

### LINKED ISSUE #40644: IDE0044 (Make Field Readonly) Should not warn for DataMember fields in DataContract classes
**Version Used**: 

Microsoft Visual Studio Community 2019
Version 16.4.2
Microsoft .NET Framework
4.8.03752

**Steps to Reproduce**:

In a class marked `DataContract`, create a private field, NOT `readonly`, and marked `DataMember`.

	[DataContract]
	public class MyClass
	{
		[DataMember]
		private bool isReadOnly;
	}

**Expected Behavior**:

The field cannot be `readonly` because it is a `DataMember`.

**Actual Behavior**:

The IDE warns with "IDE0044 (Make Field Readonly)".

### PR DESCRIPTION
**Pull request by zaytsev-victor**
Fixes #40644

### CODE REVIEW

File: src/Analyzers/Core/Analyzers/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -102,19 +103,29 @@ void OnSymbolEnd(SymbolAnalysisContext symbolEndContext)
...
                         symbol.Locations.Length == 1 &&
                         symbol.Type.IsMutableValueType() == false &&
-                        !symbol.IsFixedSizeBuffer;
+                        !symbol.IsFixedSizeBuffer &&
+                        !IsDataContractSerializable(symbol, compilation);
+
+                static bool IsDataContractSerializable(IFieldSymbol symbol, Compilation compilation)
+                {
+                    var dataMemberAttribute = compilation.DataMemberAttribute();
+                    var dataContractAttribute = compilation.DataContractAttribute();
```
Comment (sharwell) [inline src/Analyzers/Core/Analyzers/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs:119]: ❗  Since this method is part of the analyzer fast path, these lookups should only occur once (within the Compilation Start callback)

File: src/Analyzers/Core/Analyzers/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 2]
```diff
@@ -102,19 +103,29 @@ void OnSymbolEnd(SymbolAnalysisContext symbolEndContext)
...
+
+                    return symbol.GetAttributes().Any(x => x.AttributeClass == dataMemberAttribute)
+                        && symbol.ContainingType.GetAttributes().Any(x => x.AttributeClass == dataContractAttribute);
```
Comment (sharwell) [inline src/Analyzers/Core/Analyzers/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs:122]:
```suggestion
                    return symbol.GetAttributes().Any(x => SymbolEqualityComparer.Default.Equals(x.AttributeClass, dataMemberAttribute))
                        && symbol.ContainingType.GetAttributes().Any(x => SymbolEqualityComparer.Default.Equals(x.AttributeClass, dataContractAttribute));
```

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ICompilationExtensions.cs [hunk 3]
```diff
@@ -206,5 +206,11 @@ public static ImmutableArray<IAssemblySymbol> GetReferencedAssemblySymbols(this
 
         public static INamedTypeSymbol? DisallowNullAttribute(this Compilation compilation)
             => compilation.GetTypeByMetadataName(typeof(DisallowNullAttribute).FullName!);
+
+        public static INamedTypeSymbol? DataMemberAttribute(this Compilation compilation)
```
Comment (sharwell) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ICompilationExtensions.cs:210]:
```suggestion
        public static INamedTypeSymbol? SystemRuntimeSerializationDataMemberAttribute(this Compilation compilation)
```

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ICompilationExtensions.cs [hunk 4]
```diff
@@ -206,5 +206,11 @@ public static ImmutableArray<IAssemblySymbol> GetReferencedAssemblySymbols(this
...
+            => compilation.GetTypeByMetadataName(typeof(DataMemberAttribute).FullName!);
+
+        public static INamedTypeSymbol? DataContractAttribute(this Compilation compilation)
```
Comment (sharwell) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ICompilationExtensions.cs:213]:
```suggestion
        public static INamedTypeSymbol? SystemRuntimeSerializationDataContractAttribute(this Compilation compilation)
```

File: src/Analyzers/CSharp/Tests/MakeFieldReadonly/MakeFieldReadonlyTests.cs [hunk 5]
```diff
@@ -1660,5 +1660,25 @@ public static void Run()
     }
 }");
         }
+
+        [WorkItem(40644, "https://github.com/dotnet/roslyn/issues/40644")]
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsMakeFieldReadonly)]
+        public async Task ShouldNotWarnForDataMemberFieldsInDataContractClasses()
```
Comment (sharwell) [inline src/Analyzers/CSharp/Tests/MakeFieldReadonly/MakeFieldReadonlyTests.cs:1666]: 💡 Should include tests for cases where only one of the attributes is provided

Comment (sharwell) [inline src/Analyzers/CSharp/Tests/MakeFieldReadonly/MakeFieldReadonlyTests.cs:1666]: 💡 Should include a test for a case where a class contains a field marked `[DataMember]` and a field which is not. The field without the attribute should still get marked `readonly`.

Comment (sharwell) [inline src/Analyzers/CSharp/Tests/MakeFieldReadonly/MakeFieldReadonlyTests.cs:1666]: 💡 Should include a test for a case where a _public_ field of a class marked `[DataContract]` does not include `[DataMember]`. For these cases, `[DataMember]` is optional and the member will be serialized except when it is marked `[IgnoreDataMember]`.

📝 Even though today the test will pass because public fields are excluded from this analysis, it will serve as a regression test for a future scenario where we allow analysis of exposed fields (somehow).

**Comment by Youssef1313** [comment]
@zaytsev-victor Would you like to address the review comments?

**Comment by sharwell** [comment]
If not, this PR is small enough that we can probably make the corrections to it and prepare it for merge.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ICompilationExtensions.cs (hunk 3 above)
Comment (sharwell) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ICompilationExtensions.cs:210]: ➡️ Did not change this since the other types in the file follow the current pattern

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ICompilationExtensions.cs (hunk 4 above)
Comment (sharwell) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ICompilationExtensions.cs:213]: ➡️ Did not change this since the other types in the file follow the current pattern

File: src/Analyzers/Core/Analyzers/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 1 above)
Comment (sharwell) [reply src/Analyzers/Core/Analyzers/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs:119]: ➡️ Now fixed

File: src/Analyzers/Core/Analyzers/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 2 above)
Comment (sharwell) [reply src/Analyzers/Core/Analyzers/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs:122]: ➡️ Now fixed

File: src/Analyzers/CSharp/Tests/MakeFieldReadonly/MakeFieldReadonlyTests.cs (hunk 5 above)
Comment (sharwell) [reply src/Analyzers/CSharp/Tests/MakeFieldReadonly/MakeFieldReadonlyTests.cs:1805]: ➡️ Now fixed

Comment (sharwell) [reply src/Analyzers/CSharp/Tests/MakeFieldReadonly/MakeFieldReadonlyTests.cs:1805]: ➡️ Now fixed

Comment (sharwell) [reply src/Analyzers/CSharp/Tests/MakeFieldReadonly/MakeFieldReadonlyTests.cs:1805]: ➡️ Now fixed

**Review by sharwell — APPROVED** [review]

**Review by RikkiGibson — APPROVED** [review]
Compiler changes LGTM. The changes are test-only so I think only one compiler review is needed.
