### PR TITLE
Dont disturb whitespace preceding comments

### LINKED ISSUE #1151: Format Document munges whitespace preceding // single line comments
Ported from TFS WorkItem: **1041787**

------------------------------

**Repro Steps:**

<OL>
<LI>Set C# formatting rules to use Tabs instead of spaces.</LI>
<LI>Extract the attached C# code file.</LI>
<LI>Enable Visible Whitespace (Edit -&gt; Advanced -&gt; View Whitespace).</LI>
<LI>Observe how the two lines in the Main method have trailing // comments, each exactly one space after the ;</LI>
<LI>Execute Format Document on it.</LI></OL>

**Expected**

Nothing happens to the spaces between the ; and //

&nbsp;

**Actual**

The first comment gets an extra space that precedes the //

The second comment gets its single space changed to a tab.

------------------------------

**Revisions:**

1) Created By Andrew Arnott (10/6/2014 11:00:34 AM)

This is a big deal because projects under SCC where some developers use Dev14 and some use Dev12 will continuely cause large noisy whitespace diff's and merge conflicts with each other.

------------------------------

2) Edited By Kevin Pilch-Bisson (10/7/2014 8:56:54 AM)

We're already tracking this.

------------------------------

3) Edited By Andrew Arnott (3/6/2015 7:53:50 AM)

Reactivating because it still repros in VSPro_Platform 22627.00, and the alleged dupe bug was resolved as fixed four months ago.

------------------------------

4) Edited By Kevin Pilch-Bisson (3/9/2015 9:52:27 AM)

Can you take&nbsp;another look at this?

------------------------------

### PR DESCRIPTION
**Pull request by basoundr**
Fix #1151 : Dont disturb the whitespaces preceding the comments which
are also not part of indentation to be converted to tabs if 'Keep Tabs'
option is set.

### CODE REVIEW

**Comment by dpoeschl** [comment]
test this please

File: src/Workspaces/Core/Portable/Formatting/TriviaEngine/AbstractTriviaFormatter.cs [hunk 1]
```diff
@@ -818,7 +818,7 @@ private string GetWhitespaceString(LineColumn lineColumn, LineColumnDelta delta)
             var useTabOnlyForIndentation = this.OptionSet.GetOption(FormattingOptions.UseTabOnlyForIndentation, this.Language);
```
Comment (Pilchie) [inline src/Workspaces/Core/Portable/Formatting/TriviaEngine/AbstractTriviaFormatter.cs]: With this change the (completely untested :frowning:) UseTabOnlyForIndentation option has no effect anymore.  The idea of that option is to use Tabs for the base indentation of the statement, and then spaces for alignment of consecutive lines after that initial set of tabs.

Perhaps we should either:

1. Remove the option, since it's untested and not exposed through the UI.
2. Add it back, put some tests in place, and use a different method to calculate alignment spaces and the spaces between tokens.

Comment (Pilchie) [inline src/Workspaces/Core/Portable/Formatting/TriviaEngine/AbstractTriviaFormatter.cs]: Let's just remove the option.

Comment (AArnott) [inline src/Workspaces/Core/Portable/Formatting/TriviaEngine/AbstractTriviaFormatter.cs]: Ooh, for what it's worth, that option sounds awesome. But if I had to choose, I'd rather have #1151 fixed than the option (for now).

Comment (basoundr) [inline src/Workspaces/Core/Portable/Formatting/TriviaEngine/AbstractTriviaFormatter.cs]: Yes, I have removed the option. Given that we dont have any test for this option and no more using this option in the code, it is ideal to have this option removed.

Issue #1176 has been opened to track the addition of the option with precise intent and testcases

**Comment by basoundr** [comment]
@Pilchie @heejaechang Please take a look at the final changes. This is a RC bug that needs to be fixed by tomorrow.

Other potential reviewers : @jasonmalinowski @dpoeschl @rchande @balajikris @brettfo

**Comment by Pilchie** [comment]
:+1:
