### PR TITLE
Copy nullable state from a limited set of BoundExpression types only

### LINKED ISSUE #33908: StackOverflow when compiling CoreFX
Trying to move to the current Arcade toolset results in a stackoverflow when compiling CoreFX: https://github.com/dotnet/corefx/pull/35826

Stack trace is 
[stacktrace2.txt](https://github.com/dotnet/corefx/files/2938556/stacktrace2.txt) -- Worth noting it exceeds the number of stack frames VS supports. I also have a dump locally, but it is 500mb.

Compiler version is `3.1.0-beta1-19127-06`, which corresponds to https://github.com/dotnet/roslyn/commits/3ef46d8367f4ae

### PR DESCRIPTION
**Pull request by cston**
Reverts fix for #31395 for now.

Fixes #33908.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 1]
```diff
@@ -834,7 +834,11 @@ private void ReportNullabilityMismatchInAssignment(SyntaxNode syntaxNode, object
                 // if InheritNullableStateOfMember asserts the member is valid for target and value?
                 if (areEquivalentTypes(targetType, valueType)) // https://github.com/dotnet/roslyn/issues/29968 Allow assignment to base type.
                 {
-                    if (targetType.IsReferenceType || targetType.IsNullableType())
+                    // https://github.com/dotnet/roslyn/issues/31395: We should copy all tracked state from `value` regardless of
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >https://github.com/dotnet/roslyn/issues/31395: [](start = 23, length = 46)

Should this issue be re-opened?

Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: I'll re-open the issue after merging.
