### PR TITLE
Revert usage of Word Diffing in Preview Changes

### LINKED ISSUE #3792: Preview Changes should not use StringDifferenceTypes.Word
The #2139 [PR - made preview dialog window to use a bit more expansive diff mode ](https://github.com/dotnet/roslyn/pull/2139) introduced the diff change to show [word changes](https://github.com/dotnet/roslyn/pull/2139#discussion_r33724774). This has resulted in a broken experience for Change Signature - Preview change.  Possibly more features.

image

You can see the drop down list of the word changes in the document Module1.vb. Instead we want to see each entry representing a single reference change or a definition change.

The repro code:

```VB
Public Class CLass2
    Sub Main()
        $$M3("", 3)
    End Sub

    Public Sub M3(v2 As String, v1 As Integer)
        Throw New NotImplementedException()
    End Sub
End Class
```
Press Ctrl + R + O(Don't use the light bulb feature. This bug will not repro because of the internal bug 977290). This openes up the change signature dialog box. Make some change, for eg, rearrange the parameters. Enable the Show Preview changes checkbox and press 'OK'

Linking #2098 on @heejaechang's request

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #3792

### CODE REVIEW

**Comment by dpoeschl** [comment]
(I'll remove the two initial no-op commits.)

**Comment by dpoeschl** [comment]
Tagging @dotnet/mlangide, @heejaechang for review.

**Comment by dpoeschl** [comment]
Fixed the commit list.

**Comment by dpoeschl** [comment]
Tagging @dotnet/roslyn-ide :smile:

**Comment by dpoeschl** [comment]
@dotnet/roslyn-ide / @basoundr -- Is anyone willing to stop by and play with the new (old) behavior for a few minutes to see if it feels better than the existing behavior?

**Comment by rchande** [comment]
Tried this out with @dpoeschl, the bug being unfixed isn't as bad as the regression from the fix.

:+1:

File: src/VisualStudio/Core/Def/Implementation/Preview/FileChange.cs [hunk 1]
```diff
@@ -80,18 +79,13 @@ private ChangeList ComputeChildren(TextDocument left, TextDocument right, Cancel
 
             diffService = diffService ?? diffSelector.DefaultTextDifferencingService;
 
-            var diff = ComputeDiffSpans(diffService, left, right, cancellationToken);
-            if (diff.Differences.Count == 0)
+            var diff = ComputeDiffSpans(oldText, newText, diffService, cancellationToken);
+            if (!diff.Differences.Any())
```
Comment (heejaechang) [inline src/VisualStudio/Core/Def/Implementation/Preview/FileChange.cs]: this will allocate enumerator. I don't think Any check whether given IEnumerable support a types that support Count

File: src/VisualStudio/Core/Def/Implementation/Preview/FileChange.cs [hunk 2]
```diff
@@ -80,18 +79,13 @@ private ChangeList ComputeChildren(TextDocument left, TextDocument right, Cancel
...
             {
-                // There are no changes.
-                return ChangeList.Empty;
+                // There are no changes. Just show the whole document.
+                return GetEntireDocumentAsSpanChange(left);
```
Comment (heejaechang) [inline src/VisualStudio/Core/Def/Implementation/Preview/FileChange.cs]: ?? why showing whole document? why moving this behavior back? does this has anything to do with changing diffing to Word?

**Comment by heejaechang** [comment]
@dpoeschl rather than reverting? why not just change diff option to Line?

**Comment by dpoeschl** [comment]
@heejaechang Okay, will update this.

**Comment by dpoeschl** [comment]
@heejaechang Fixed!

**Comment by heejaechang** [comment]
:+1:

**Comment by dpoeschl** [comment]
@tannergooding @jmarolf I only changed a method body, these errors seem spurious: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/115/console @dotnet/roslyn-infrastructure (I wish this alias existed)

**Comment by dpoeschl** [comment]
test unit please
