### PR TITLE
Fix issue when pressing ENTER in XML doc comments with a selection

### LINKED ISSUE #5486: XML doc comments: when code is selected and ENTER is pressed, the direction of the selection changes whether /// is inserted
```C#
/// <summary>
/// Hello World!
/// </summary>
class C
{
}
```

Select "World" from left-to-tight and press ENTER.

```C#
/// <summary>
/// Hello 
!
/// </summary>
class C
{
}
```

Select "World" from right-to-left and press ENTER.

```C#
/// <summary>
/// Hello 
/// !
/// </summary>
class C
{
}
```

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes #5486 

In order to insert XML doc comment exterior trivia (e.g. /// or '''), we grab the caret position prior to the new line being inserted into the editor and then perform a bit of analysis afterward using that position. However, if there's a selection in the editor and the caret is at the end of that selection, the position will be in an unexpected place in the syntax tree, causing that bit of analysis to fail. So, in this case (and all cases), we use the start of the selection as the position to perform analysis on since that position will be consistent after the new line is inserted.

### CODE REVIEW

**Comment by DustinCampbell** [comment]
Tagging @dotnet/mlangide.

**Comment by Pilchie** [comment]
:+1:

File: src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs [hunk 1]
```diff
@@ -480,14 +481,34 @@ public void ExecuteCommand(ReturnKeyCommandArgs args, Action nextHandler)
...
 
-            var caretPosition = args.TextView.GetCaretPoint(args.SubjectBuffer) ?? -1;
-            if (caretPosition < 0)
+            int originalPosition;
+
+            // The original position should be a position that is consistent with the syntax tree, even
+            // after Enter is pressed. Thus, we use the start of the first selection if there is one.
+            // Otherwise, getting the tokens to the right or the left might return unexpected results.
+
+            if (args.TextView.Selection.SelectedSpans.Count > 0)
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs]: The docs for SelectSpans states:
> This span collection is never empty, but the spans in this collection may be 0-length
So I don't believe you need this check at all. Not having a selection is just considered as having selected nothing at the start point.

File: src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs [hunk 2]
```diff
@@ -480,14 +481,34 @@ public void ExecuteCommand(ReturnKeyCommandArgs args, Action nextHandler)
...
+            {
+                var selectedSpan = args.TextView.Selection
+                    .GetSnapshotSpansOnBuffer(args.SubjectBuffer)
+                    .FirstOrNullable();
+
+                originalPosition = selectedSpan != null
+                    ? args.TextView.BufferGraph.MapUpOrDownToBuffer(selectedSpan.Value.Start, args.SubjectBuffer) ?? -1
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs]: `GetSnapshotSpansOnBuffer` already did the mapping. Why is the mapping happening again?

Comment (DustinCampbell) [inline src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs]: Because of old code I forgot to delete. Fixing...

File: src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs (hunk 1 above)
Comment (DustinCampbell) [inline src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs]: You're right. Fixing...
