### PR TITLE
Smarter resource management in MemoryMappedInfo

### LINKED ISSUE #19493: MemoryMappedInfo cleanup delays Visual Studio shutdown
**tl;dr:** We create instances of `MemoryMappedInfo` (and its nested types). These types are disposable and have finalizers, but in some cases we do not explicitly dispose of instances. The large number of instances created for some user scenarios combined with non-deterministic cleanup resulted in a measurable (~50ms) increase in the time it takes to close Visual Studio for some scenarios.

What follows is a long and detailed breakdown of an investigation that started early Friday morning (5/12) in response to a performance regression detected the day before.

:bulb: When we refer to "meeting internal performance goals" in places like the contributor guide for Roslyn, but don't explain how external contributors are supposed to actually accomplish that, part of what we're talking about is covered by the system explained in detail below. If you were ever interested in what exactly we meant by that, I hope you enjoy the following read. :smile:

### How it started (5/11)

As part of my current role ("grasshopper") on the @dotnet/roslyn-infrastructure team, one of my responsibilities is scheduling and monitoring the incorporation of Roslyn code into Visual Studio itself. The whole process is very new to me, but a reasonably accurate way for a non-Microsoft to view this system is a build farm dedicated to running end-to-end tests prior to taking changes from one large team and applying them to another team. The system as a whole serves as both an early warning system for potential problems and helps identify the team responsible for various types of failures.

One of the toughest types of problems to detect reliably is performance regressions, and anyone who's tried to implement such tests in the past knows what I'm talking about. And the bigger the system under test, the harder it is to produce meaningful results. Small sections of code might be easy to benchmark, but in this case we're talking about ~15+ minute end-to-end user scenario tests of Visual Studio. To keep things flowing smoothly, performance tests in the system allow for some amount of "noise" in the test results. Deviations outside the allowed noise signify major problems where we cannot proceed until they are resolved (I haven't had to deal with one of these so there could be exceptions/special cases that I just don't know about). Deviations "under the degrade bar" do not cause a red flag in the system, still show up on performance reports based on a scoring system. Test scenarios that ran slower than the baseline are given a score based on how close to the bar they are: (actual-baseline)/(bar-baseline), and the highest values show up on the top of the report for manual investigation.

I mentioned "tests" and "scenarios". The two concepts are vital to understanding how we review long and complicated test sequence to identify specific possible regressions. The "test" refers to a complete end-to-end test, which might include opening VS, creating one or more projects, writing some code, building, running, and finally closing the solution and closing Visual Studio itself. Each test is divided into several named scenarios corresponding to specific actions, and target metrics may be defined either for the test as a whole or for specific scenarios.

:bulb: For anyone wanting to set up a system like this someday, I recommend you implement the ability to automatically assign metrics based on what you measure in a shipping release. This "baselining" ability allows you to establish target goals relatively easily that help ensure future releases of your product perform *at least as well* as the previous release, which is a great place to start when discussing development strategies to gradually improve the experience your customers have on a daily basis.

Thursday's test run included one test which did not exceed the bar but seemed "worse than normal", thus starting a manual review. The specific scenario was "Close VS", which in this test occurs after the solution is already closed. The degrade bar is set at 100ms slower than the previous release, and the build was showing a value of 52ms slower. The investigation started with a review of the history of this test using a tool that shows the builds on our team and the builds for the "mainline" that all the teams interact with. This overlay of the two branches is important because it can show with relatively high confidence whether a problem originated on our team (shows up on ours before mainline), or another team (shows up in mainline before ours). Here's the graph going back several builds. The orange branch is our team, and the purple branch is one of the main Visual Studio branches.

image

This investigation centered around the apparent new trend where we are sitting roughly 40-50ms slower than our goal line, and which started on our team builds prior to showing up in the main branch.

### Tracking down the problem (5/12)

Tracking down the problem is not always easy, but the two things you can do to be successful on this front are preparation and practice.

#### Preparation

Our end-to-end tests which we use for performance monitoring have PerfView running in the background. I don't have details regarding the exact configuration, but the key items would be:

1. Configure your sampling rate such that you have a "manageable" output data file size over the duration of your test. Since our tests are 15+ minutes, this means a slower sampling rate than the default.
2. Make sure you are enabling items that relate to your user experience. The meaning of this will vary by industry/application, but for me the two items I found valuable were having Thread Time enabled and also having marks inserted into the trace by the end-to-end test driver identifying exactly when a scenario (e.g. Close VS) started and ended.
3. Store the outputs of the PerfView traces for a sufficient amount of time that they can be used for comparative analysis in the future.

#### Practice

I had an advantage in investigating this by knowing three things:

1. The scenario which failed was Close VS, so I could filter the PerfView reports to start and end at the markers placed at the start and end of this scenario. As you can see from the graph, this is a ~300ms window out of the ~15 minute report.
2. Since I was investigating an elapsed time performance failure, the view of most immediate interest was the Thread Time view. I needed to account for the additional 50ms of time, regardless of whether that time was BLOCKED TIME or CPU TIME.
3. Even though this was my first experience ever with this test or scenario, I knew I could most easily track down the time by opening two reports side by side: one from a recent "slow" run, and the other from a recent "fast" run.

### Findings

I started with the Call Tree view examining the main thread. By comparing with the previous run, I pretty quickly narrowed down the additional time on the main thread to the following trace. The highlighted value accounts for all of the new time:

image

As you can see, the main thread was blocked during this time, so to find the root cause we have to find out what it was waiting on. In this case, the answer was pretty easy to infer by looking at the thread activity histograms and asking "what would the CLR be waiting for during `clr!??EEShutdown`.

image

Focusing on the finalizer thread showed two items of particular interest:

image

The in the conveniently available CoreCLR sources, we can see that these are the two methods called to [finalize a single object](https://github.com/dotnet/coreclr/blob/76cbc581382ebbcf745dd2b79ac02c419970808c/src/vm/finalizerthread.cpp#L98-L99).

* **clr!WKS::CallFinalizer**: This is slow when you have many finalizers, or when finalizers themselves are slow
* **clr!WKS::LogFinalization**: This has no measurable overhead normally, but a small amount of overhead when ETW events are being recorded. While the call within it, **clr!??ETW::GCLog::SendFinalizeObjectEvent**, probably should have been pruned by our analysis as measurement overhead imposed by PerfView recording, it nevertheless provided valuable insight for me. *Time here means a large number of objects are getting finalized.*

A closer look at **clr!WKS::CallFinalizer** revealed the problem with `MemoryMappedInfo`:

image

In the next step of my investigation, I wanted to determine how many `MemoryMappedInfo` objects were getting finalized when the CLR was trying to shut down. This part was rather difficult, but hopefully in the future it can be improved (filed Microsoft/perfview#200 and Microsoft/perfview#201). I filtered the events view to the start/end time for the scenario, set MaxRet to 110000 (so all events would show), and set the process filter to **devenv**. I then opened the **Microsoft-Windows-DotNETRuntime/GC/FinalizeObject** events, showed the **TypeID** column, and exported the resulting view as a CSV file. After opening the CSV file in Excel, I used a pivot table on the TypeID column to get a histogram which I sorted by the number of times an object of that type ID was finalized. Working from the top, I then examined all available events in PerfView of type **Microsoft-Windows-DotNETRuntime/GC/AllocationTick** to associate type IDs with type names. I only made it through the first 5 items before the sampling rate of AllocationTick stopped showing results.

image

### Follow-up

The solution appears to be two-fold:

1. Reduce the number of memory-mapped file handles that need to be cleaned up. For example, rather than create a memory mapped file for every temporary storage request, we could set a minimum size on the file at 1 MiB, and use smaller views within the file for temporary storage. When a request is too large to fit in the available space at the end of the current file, stop creating storage in that file and move to a new one.
2. Reduce the "weight" of finalization by reducing the size of the object graph referenced by finalizable objects. In particular, avoid making `MemoryMappedInfo` and `SharedReadableStream` themselves finalizable, and instead create a minimal type (or types) derived from `CriticalHandle` which is responsible for releasing the unmanaged resources.

### LINKED ISSUE #19570: Use larger memory mapped files for temporary storage
**Version Used**: 15.2

We can reduce the number of `MemoryMappedFile` instances getting disposed (a time-consuming process) by creating larger instances and using each memory mapped file as the storage for multiple temporary files. This will improve upon the performance gains already realized in #19522.

Currently files are created to match the specific size needed for each file in the solution. For an initial experiment, it might be reasonable to:

* Create files that are 1MiB in size, and use bump pointer allocation to place files within it
* When a file doesn't fit in the remaining space at the end of the last memory mapped file, create a new memory mapped file where it goes at the beginning
* Any file larger than 256KiB is placed in its own memory mapped file

⚠️ Currently these buffers are shared with the OOP workers. The serialization assumes that each temporary file is placed at offset 0 within the target memory mapped file. This will need to be updated to account for multiple temporary storage buffers within a single memory mapped file.

### LINKED ISSUE #19604: OOM with memory mapped files
```
System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Not enough storage is available to process this command.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.MemoryMappedFiles.MemoryMappedView.CreateView(SafeMemoryMappedFileHandle memMappedFileHandle, MemoryMappedFileAccess access, Int64 offset, Int64 size)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewStream(Int64 offset, Int64 size, MemoryMappedFileAccess access)
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.MemoryMappedInfo.CreateWritableStream()
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.TemporaryStorageService.TemporaryTextStorage.WriteText(SourceText text, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.TemporaryStorageService.TemporaryTextStorage.<>c__DisplayClass13_0.<WriteTextAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.RecoverableTextAndVersion.RecoverableText.<SaveAsync>d__7.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.IOException: Not enough storage is available to process this command.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.MemoryMappedFiles.MemoryMappedView.CreateView(SafeMemoryMappedFileHandle memMappedFileHandle, MemoryMappedFileAccess access, Int64 offset, Int64 size)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateViewStream(Int64 offset, Int64 size, MemoryMappedFileAccess access)
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.MemoryMappedInfo.CreateWritableStream()
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.TemporaryStorageService.TemporaryTextStorage.WriteText(SourceText text, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.TemporaryStorageService.TemporaryTextStorage.<>c__DisplayClass13_0.<WriteTextAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.RecoverableTextAndVersion.RecoverableText.<SaveAsync>d__7.MoveNext()<---
```

### PR DESCRIPTION
**Pull request by sharwell**
* Unmap views of memory mapped files when they are not in use, allowing the process to use the address space for other purposes (#19604)
* Use fewer memory mapped files for small files (#19570)

## Ask Mode

**Customer scenario**

Customer works in a large solution; over time they tend to observe out of memory exceptions.

**Bugs this fixes:**

Fixes #19493
Fixes #19570
Fixes #19604 
[DevDiv 435299](https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=435299) (This is the bug that #19522 was supposed to fix, but it didn't address the problem enough for RPS to drop back to the expected values)

**Workarounds, if any**

None available.

**Risk**

Moderate. The code is complex but efficient and reliable.

**Performance impact**

This change substantially improves performance in several scenarios:

* Application responsiveness is improved by unmapping views of memory mapped files when they are no longer in use, which allows the garbage collector to operate more efficiently
* Application shutdown performance is improved by creating fewer `MemoryMappedFile` instances which need to be finalized

**Is this a regression from a previous update?**

Not really. It's possible that 15.3 Preview 1 or Preview 2 could contain a regression for users on small systems.

**Root cause analysis:**

Failed in #19522 to account for `MemoryMappedInfo` being a long-lived object, where the strong reference to `MemoryMappedInfo._accessor` help memory for much longer than was desirable.

**How was the bug found?**

Reported by dogfooding.

### CODE REVIEW

**Comment by sharwell** [comment]
@dotnet/roslyn-ide for review

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs [hunk 1]
```diff
@@ -50,13 +50,13 @@ internal sealed class MemoryMappedInfo : IDisposable
...
             /// <remarks>
-            /// <para>It is possible for this accessor to be disposed prior to the streams which use it. However, the
-            /// streams interact directly with the underlying memory buffer, and keep a
-            /// <see cref="CopiedMemoryMappedViewHandle"/> to prevent that buffer from being released while still in
-            /// use. The <see cref="SafeHandle"/> used by this accessor is reference counted, and is not finally
-            /// released until the reference count reaches zero.</para>
+            /// <para>This holds a weak reference to current <see cref="MemoryMappedViewAccessor"/>, which allows
+            /// additional accessors for the same address space to be obtained up until the point when no external code
+            /// is using it. When the memory is no longer being used by any <see cref="SharedReadableStream"/> objects,
+            /// it is unmapped automatically and a new accessor is created for the memory mapped file the next time it's
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: what does it mean to be "unmapped automatically"?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs [hunk 2]
```diff
@@ -99,13 +99,16 @@ public Stream CreateReadableStream()
...
                 lock (_memoryMappedFile)
                 {
-                    if (_accessor == null)
+                    var streamAccessor = _accessor.TryAddReference();
+                    if (streamAccessor == null)
                     {
-                        _accessor = RunWithCompactingGCFallback(info => info._memoryMappedFile.CreateViewAccessor(0, info._size, MemoryMappedFileAccess.Read), this);
+                        var rawAccessor = RunWithCompactingGCFallback(info => info._memoryMappedFile.CreateViewAccessor(0, info._size, MemoryMappedFileAccess.Read), this);
+                        streamAccessor = new ReferenceCountedDisposable<MemoryMappedViewAccessor>(rawAccessor);
+                        _accessor = new ReferenceCountedDisposable<MemoryMappedViewAccessor>.WeakReference(streamAccessor);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: does this give an automatic starting ref count?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs [hunk 3]
```diff
@@ -99,13 +99,16 @@ public Stream CreateReadableStream()
                 // CreateViewAccessor is not guaranteed to be thread-safe
                 lock (_memoryMappedFile)
                 {
-                    if (_accessor == null)
+                    var streamAccessor = _accessor.TryAddReference();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: Who is responsible for releasing this reference if it succeeds?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs [hunk 4]
```diff
@@ -162,16 +165,6 @@ private void Dispose(bool disposing)
             {
                 if (disposing)
                 {
-                    lock (_memoryMappedFile)
-                    {
-                        if (_accessor != null)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: shoudl we not consider still nulling out hte accessor?  And then in CreateReadableStream throwing if this was a disposed object?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 5]
```diff
@@ -0,0 +1,197 @@
...
+
+namespace Microsoft.CodeAnalysis.Host
+{
+    internal partial class TemporaryStorageServiceFactory
+    {
+        private sealed class ReferenceCountedDisposable<T> : IDisposable
+            where T : IDisposable
+        {
+            private T _instance;
+            private StrongBox<int> _referenceCount;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: why can't this just be an int?

Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: I'm surprised there is no lock to protect this guy.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 6]
```diff
@@ -0,0 +1,197 @@
...
+            /// <para>The reference count is initialized to 1.</para>
+            /// </remarks>
+            /// <param name="instance">The object owned by this wrapper.</param>
+            public ReferenceCountedDisposable(T instance)
+            {
+                _instance = instance;
+                _referenceCount = new StrongBox<int>(1);
+            }
+
+            private ReferenceCountedDisposable(T instance, StrongBox<int> referenceCount)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: when we do we need this.  Why can't we just give the person the existing ReferenceCountedDisposable instance we already ahve?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 7]
```diff
@@ -0,0 +1,197 @@
...
+                // This value can be set in Dispose. However, even if we have a race condition with Dispose where it's
+                // set to null in the middle of the call, the reference count will be incremented by this method if and
+                // only if a valid new reference was created. This is because the validity of this instance for creating
+                // new references is determined by _referenceCount.
+                var target = _instance;
+                Interlocked.MemoryBarrier();
+                var referenceCount = Volatile.Read(ref _referenceCount);
+
+                // Cannot use Interlocked.Increment because we need to latch the reference count when it reaches 0.
+                while (true)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: all this code seems very complex.  can we not just take a lock, check our state, and do whatever is necessary, while knowing things aren't going to change underneath us?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 8]
```diff
@@ -0,0 +1,197 @@
...
+            /// <summary>
+            /// Represents a weak reference to a <see cref="ReferenceCountedDisposable{T}"/> which is capable of
+            /// obtaining a new counted reference up until the point when the object is no longer accessible.
+            /// </summary>
+            public struct WeakReference
+            {
+                /// <summary>
+                /// DO NOT DISPOSE OF THE TARGET.
+                /// </summary>
+                private readonly WeakReference<ReferenceCountedDisposable<T>> _instance;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: This is very confusing.  You've defined a type wit hthe same name as a generic type that you're then using in yourself.

**Comment by CyrusNajmabadi** [comment]
What is the reason for all the interlocked code?  It makes all of this extremely complex and difficult to reason about.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 9]
```diff
@@ -0,0 +1,197 @@
...
+            /// <para>This call is not valid after <see cref="Dispose"/> is called.</para>
+            /// </remarks>
+            public T Target => _instance;
+
+            /// <summary>
+            /// Increments the reference count for the disposable object, and returns a new disposable reference to it.
+            /// </summary>
+            /// <remarks>
+            /// <para>The returned object is an independent reference to the same underlying object. Disposing of the
+            /// returned value multiple times will only cause the reference count to be decreased once.</para>
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: couldn't this be more easily accomplished with a bool that says if we've been disposed or not?  If we haven't been disposed, then we decrement the ref count.  If we have been, we ignore the second dispose.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 10]
```diff
@@ -0,0 +1,197 @@
...
+
+#if DEBUG
+using System.Diagnostics;
+#endif
+
+namespace Microsoft.CodeAnalysis.Host
+{
+    internal partial class TemporaryStorageServiceFactory
+    {
+        private sealed class ReferenceCountedDisposable<T> : IDisposable
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: If we are implementing a ref-counting scheme that depends on Dispose being called, then i would expect to have a finalizer (potentially debug only) telling us when someone has addref'ed, gotten a REferenceCountededDisposable, but then doesn't end up disposing it.  It seems very easy for someone to make one of these types, potentially forget to dispose it, and then leak a refcount, leading to never letting go of the underlying file.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 11]
```diff
@@ -0,0 +1,197 @@
...
+            /// has not yet been disposed; otherwise, <see langword="null"/> if this reference to the underlying object
+            /// has already been disposed.</returns>
+            public ReferenceCountedDisposable<T> TryAddReference()
+            {
+                // This value can be set in Dispose. However, even if we have a race condition with Dispose where it's
+                // set to null in the middle of the call, the reference count will be incremented by this method if and
+                // only if a valid new reference was created. This is because the validity of this instance for creating
+                // new references is determined by _referenceCount.
+                var target = _instance;
+                Interlocked.MemoryBarrier();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: Why is this needed?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 12]
```diff
@@ -0,0 +1,197 @@
...
+                var referenceCount = Volatile.Read(ref _referenceCount);
+
+                // Cannot use Interlocked.Increment because we need to latch the reference count when it reaches 0.
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: What do you mean "latch the reference"?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 13]
```diff
@@ -0,0 +1,197 @@
...
+                var instance = _instance;
+
+                // Set the instance back to its default value, so in case someone forgets to dispose of one of the
+                // counted references the finalizer of the underlying disposable object will have a chance to clean up
+                // the unmanaged resources as soon as possible.
+                Interlocked.MemoryBarrier();
+                _instance = default(T);
+
+#if !DEBUG
+                var decrementedValue = Interlocked.Decrement(ref referenceCount.Value);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: why do we not perform this code in debug?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 14]
```diff
@@ -0,0 +1,197 @@
...
+                if (decrementedValue == 0)
+                {
+                    instance.Dispose();
+                }
+#else
+                while (true)
+                {
+                    var currentValue = Volatile.Read(ref referenceCount.Value);
+                    Debug.Assert(currentValue > 0, "Dispose should have protected itself against races.");
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: Can this be a Contract so that we run this in Release?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 15]
```diff
@@ -0,0 +1,197 @@
...
+                _instance = default(T);
+
+#if !DEBUG
+                var decrementedValue = Interlocked.Decrement(ref referenceCount.Value);
+                if (decrementedValue == 0)
+                {
+                    instance.Dispose();
+                }
+#else
+                while (true)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: Why do we have such different codepaths for debug/release?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 16]
```diff
@@ -0,0 +1,197 @@
...
+                /// <summary>
+                /// DO NOT DISPOSE OF THE TARGET.
+                /// </summary>
+                private readonly WeakReference<ReferenceCountedDisposable<T>> _instance;
+
+                public WeakReference(ReferenceCountedDisposable<T> reference)
+                    : this()
+                {
+                    var instance = reference._instance;
+                    Interlocked.MemoryBarrier();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: why do you need this?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 17]
```diff
@@ -0,0 +1,197 @@
...
+                    var referenceCount = Volatile.Read(ref reference._referenceCount);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: having _referenceCount not be an int makes this all very strange.  Can you call it '_referenceCountStrongBox' or something to make it clearer?  Otherwise seeing comparisons to null is quite odd.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 18]
```diff
@@ -0,0 +1,197 @@
...
+                    }
+
+                    if (referenceCount.Value == 0)
+                    {
+                        // We were able to read the reference, but it's already disposed.
+                        return;
+                    }
+
+                    var innerReference = new ReferenceCountedDisposable<T>(instance, referenceCount);
+                    _instance = new WeakReference<ReferenceCountedDisposable<T>>(innerReference);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: i don't really understand how this can work.  You just made a new 'innerReference', and you are now holding onto it with a .Net WeakReference.  it doesn't look like anything is necessairly pointing at innerReference through a strong reference.  So i don't see how the first GC doesn't just clean this up immediately.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 19]
```diff
@@ -0,0 +1,197 @@
...
+                }
+
+                /// <summary>
+                /// Increments the reference count for the disposable object, and returns a new disposable reference to
+                /// it.
+                /// </summary>
+                /// <remarks>
+                /// <para>Unlike <see cref="ReferenceCountedDisposable{T}.TryAddReference"/>, this method is capable of
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: having these functions have the same name but differing behavior makes reading code in other locations much harder.

**Comment by CyrusNajmabadi** [comment]
Instead of focusing on this code, can you help by explaining what problem you saw?  I want to get an intuition for what the actual problem is.  From there we can then transition to a discussion of what the appropriate fix should be.  Right now this is a very complex solution.  It might be warranted.  But i don't know what the actual problem is, and i don't know if there may be simpler ways to address it.

Tagging @jasonmalinowski as well.

**Comment by CyrusNajmabadi** [comment]
Note: every comment i made int he PR implicitly is stating: "regardless of the reason, please update the code to make the reason clear so that future maintainers can understand it".

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 2 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: :arrow_right: Yes, the initial reference count is documented on the `ReferenceCountedDisposable<T>` constructor.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 5 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: I'll document this in the file

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 6 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: :arrow_right: This class supports multiple calls to `Dispose`, where everything after the first is a NOP.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 10 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: > If we are implementing a ref-counting scheme that depends on Dispose being called

It does not depend on `Dispose` being called. It's more efficient that way, but it will not fail to release resources if used sub-optimally. (This is the same set of conditions as the previous implementation.)

In addition, we know that some callers will fail to call `Dispose` in the current implementation. (Also the same as before.)

> It seems very easy for someone to make one of these types, potentially forget to dispose it, and then leak a refcount, leading to never letting go of the underlying file.

It will not leak. (the following explanation will be added in a comment)

The underlying object is _eligible_ for collection when all references to the same object reach _either_ of the following states:

1. The reference is eligible for collection (no path to root)
1. The reference is disposed

The underlying object will be _deterministically_ disposed when all references to the same object are explicitly disposed.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 11 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: ➡️ (Will document) Ensures the non-volatile read of `_instance` is consistent, even if `T` is a value type larger than the machine word size.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 12 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: :arrow_right: Latch means once a condition is true, it is never false.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 13 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: The two code paths are equivalent. The only difference is the `DEBUG` path has a `Debug.Assert`. Since the assert doesn't execute in release builds, we can use a wait-free path instead of just lock-free. If we drop the `Debug.Assert` line then this would become the only path.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 14 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: ➡️ This is a locally-provable condition, which cannot be affected by external code.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 15 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: :memo: Answered as part of a previous reply.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 16 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: Will document. Each use of `MemoryBarrier` ensures that we are consistent in our reads of `_instance`.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 17 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: Sure

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 18 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: :bug:

**Comment by sharwell** [comment]
> Instead of focusing on this code, can you help by explaining what problem you saw?

My previous pull request unintentionally added a new strong reference from `MemoryMappedInfo` to a mapped view of the file. As long as the view is mapped, it hold address space in the process. This change eliminates the strong reference, allowing the memory mapped file to exist but not take up address space in the process when it is not being used.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 1 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: Will clarify in the next update.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 3 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: :arrow_right: The stream owns this reference, and it's the only thing that's done with it. This seems to be covered by the existing documentation comment for the method.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 6 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: (documented in next update)

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 7 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: Documented the concurrent characteristics for all methods for the next update

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 9 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: :arrow_right: The more fields we add, the harder it is to adhere to the lock-free requirements which are now documented for the type.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 11 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: 📝 I had to add a `class` constraint on the generic type to provide correct behavior for the weak reference.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 13 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: :memo: I will fix this after we decide to either simplify to a single code path, or keep both.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 19 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: :memo: Originally I had `TryGetTarget`, but it wasn't clear that the result needed to be disposed by the caller. While the details of these two methods is slightly different (one can return null while the other is still able to add a reference), they do share an important characteristic in the meaning of the return value is the same for the caller.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 18 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: Fixed by making the weak reference point to the target disposable. This change did result in a requirement that `T` be a reference type.

**Comment by sharwell** [comment]
@stephentoub for additional review of the concurrent algorithm

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 9 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: > The more fields we add, the harder it is to adhere to the lock-free requirements

Why do we have a lock-free requirement?

>  which are now documented for the type.

I'm not certain what this means.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 20]
```diff
@@ -12,10 +12,50 @@ namespace Microsoft.CodeAnalysis.Host
...
+        /// <para>While each instance of <see cref="ReferenceCountedDisposable{T}"/> should be explicitly disposed when
+        /// the object is no longer needed by the code owning the reference, this implementation will not leak resources
+        /// in the event one or more callers fail to do so. The underlying object will be deterministically released
+        /// when the last reference to it is disposed. However, the underlying object is eligible for non-deterministic
+        /// release (should it have a finalizer) when each reference to it is <em>either</em> disposed <em>or</em>
+        /// eligible for garbage collection itself.</para>
+        ///
+        /// <para>All public methods on this type adhere to their pre- and post-conditions and will not invalidate state
+        /// even in concurrent execution. The implementation of <see cref="TryAddReference"/> is lock-free; all other
+        /// methods are wait-free, with the exception of the specific call to <see cref="Dispose"/> which results in the
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: why do we need lock-free or wait-free?  It seems to add a *lot* of compelxity to what seems to otherwise just be a case of trying to keep a refcount on a weak reference so that we can release early when the refcount reaches 0.

**Comment by CyrusNajmabadi** [comment]
Before we pull in stephen, can you provide information that explains why we need lock-free/wait-free here?

Are we using these memory mapped files in a way that simpler algorithms and simpler locking structures don't perform well for?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 12 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: Isn't this just a usecase for CountdownEvent then?  You create it with a count of 1, and then you use 'Signal' to reduce the count, and TryAddCount to increment.  TryAdd will fail if you're already at 0, and Signal will tell you if you were the thread that got the CountdownEvent to reach 0.  That seems to provide all the information you need here.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 14 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: I don't know what this means.

Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: You have an assert which is claiming something is true.  I don't see why that assert is currently debug only.  If we were to have gotten 0 back that woudl be bad and something we'd want to investigate even in release builds.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs [hunk 21]
```diff
@@ -44,43 +46,49 @@ internal sealed class MemoryMappedInfo : IDisposable
             /// However, the operating system does not actually close the views which are in use until the view handles
             /// are closed as well, even if the <see cref="MemoryMappedFile"/> is disposed first.</para>
             /// </remarks>
-            private readonly MemoryMappedFile _memoryMappedFile;
+            private readonly ReferenceCountedDisposable<MemoryMappedFile> _memoryMappedFile;
```
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: :memo: Will review/add documentation here

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs [hunk 22]
```diff
@@ -34,6 +34,8 @@ internal partial class TemporaryStorageServiceFactory
         internal sealed class MemoryMappedInfo : IDisposable
         {
             private readonly string _name;
+            private readonly long _fileSize;
```
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: :memo: Will review/add documentation here

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs [hunk 23]
```diff
@@ -30,7 +31,11 @@ public IWorkspaceService CreateService(HostWorkspaceServices workspaceServices)
         /// </summary>
         internal class TemporaryStorageService : ITemporaryStorageService2
         {
+            private const long SingleFileThreshold = 128 * 1024;
```
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: :memo: Will review/add documentation here

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs [hunk 24]
```diff
@@ -42,19 +47,88 @@ public ITemporaryTextStorage CreateTemporaryTextStorage(CancellationToken cancel
...
                 return new TemporaryStreamStorage(this);
             }
 
-            public ITemporaryStreamStorage AttachTemporaryStreamStorage(string storageName, long size, CancellationToken cancellationToken)
+            public ITemporaryStreamStorage AttachTemporaryStreamStorage(string storageName, long offset, long size, CancellationToken cancellationToken)
+            {
+                return new TemporaryStreamStorage(this, storageName, offset, size);
+            }
+
+            private MemoryMappedInfo CreateTemporaryStorage(long size)
```
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: :memo: Will review/add documentation here

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs [hunk 25]
```diff
@@ -42,19 +47,88 @@ public ITemporaryTextStorage CreateTemporaryTextStorage(CancellationToken cancel
...
+                    return new MemoryMappedInfo(reference, storage.Name, storage.Size, endOffset - size, size);
+                }
+            }
+
+            public static string CreateUniqueName(long size)
+            {
+                return "Roslyn Temp Storage " + size.ToString() + " " + Guid.NewGuid().ToString("N");
+            }
+
+            private sealed class MemoryMappedFileStorage
```
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: :memo: Will review/add documentation here

File: src/Workspaces/Core/Portable/Execution/Serializer_Asset.cs [hunk 26]
```diff
@@ -30,6 +30,7 @@ public void SerializeSourceText(ITemporaryStorageWithName storage, SourceText te
             {
                 writer.WriteInt32((int)SerializationKinds.MemoryMapFile);
                 writer.WriteString(storage.Name);
+                writer.WriteInt64(storage.Offset);
```
Comment (sharwell) [inline src/Workspaces/Core/Portable/Execution/Serializer_Asset.cs]: ❓ Is there a serialization version or something that needs to change, or do we just use this?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 9 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: > Why do we have a lock-free requirement?

Because it's not too challenging to get right at this scale.

> > which are now documented for the type.
>
> I'm not certain what this means.

Just means I added documentation in code explaining why it's implemented this way.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 12 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: No, `CountdownEvent` is not safe for use in concurrent code due to its implementation of `Dispose`. We would have to intentionally fail to call `Dispose` on it (not unlike Microsoft/vs-threading#105). It also adds a bunch of overhead for features we don't need here.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 14 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: I'm planning to just remove this block.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 9 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: > Because it's not too challenging to get right at this scale. 

That's not an acceptable reason.  Complexity has to justify itself over non complex solutions.  "because we can" isn't a reason.   We have countless examples of unnecessary complexity being something that has significantly impacted us in extremely poor ways over Roslyn's lifetime.  There are times when it is appropriate, and data shows the value we get out of that.  But in the absense of that, we should be going for the simplest, correct, solution we can provide.

In this case, it seems like a simple lock, with a couple of data fields (or one, if you want to just merge the boolean + the count into one field), would be sufficient.  It would then be far more trivial to review, comprehend, and maintain.  

There's nothing wrong with using a lock.  It's what we do almost entirely in the IDE code (that, or just using tasks ordering), and it works very well and is consistent with the rest of the code.  Since we don't use these lock-free/wait-free forms, this means this code is automatically much harder to reason about since it's different from our standard patterns and practices, and practically no one on the IDE routinely codes this way.

Please follow the patterns of the rest of the IDE unless we have data that indicates substantive problems with those approaches that warrant these types of solutions.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 13 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: Having different codepaths for release and debug in such a delicate codepath is concerning.  It is not at all clear to me that these codepaths are doing the same thing, and this may make things very hard to track down if we encounter issues that only occur in one flavor and not hte other.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 27]
```diff
@@ -0,0 +1,282 @@
...
+                {
+                    instance.Dispose();
+                }
+#else
+                while (true)
+                {
+                    var currentValue = Volatile.Read(ref referenceCount.Value);
+                    Debug.Assert(currentValue > 0, "Dispose should have protected itself against races.");
+
+                    if (Interlocked.CompareExchange(ref referenceCount.Value, currentValue - 1, currentValue) == currentValue)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: i don't get how this works in concurrent scenarios.  If someone has another instance that is holding onto this strongbox, and they Dispose, they may 'win' on decrementing the value.  If we come in, our compare-exchange may fail, and we won't enter this block.  So no one will actually dispose the instance.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 28]
```diff
@@ -0,0 +1,282 @@
...
+                }
+
+                // This is the thread which will write to _instance, so this will act as an atomic read
+                var instance = Interlocked.Exchange(ref _instance, null);
+
+                // Set the instance back to its default value, so in case someone forgets to dispose of one of the
+                // counted references the finalizer of the underlying disposable object will have a chance to clean up
+                // the unmanaged resources as soon as possible.
+                Interlocked.MemoryBarrier();
+                _instance = default(T);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: i don't understand why either of these lines are necessary.  if the Interlocked.Exchange already set _instance o null, then why we we need to set _isntance to default(T) here?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 14 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: My overall point is that this entire PR is extremely hard to review and verify correctness on.  There have been at least two locations that look wrong *from a local analysis*.  I haven't even been able to get to the point of understanding about how this all works together *non-locally* to validate correctness.  

Can we move to a simpler and safer approach that gives us the semantics we seem to want (deterministic release if all outstanding references are disposed), and then move to something more complex *if* data demonstrates that there is actually a concern of something like contention overhead.

These codepaths are only hit for creating streams/SourceTexts for syntax trees we've dumped and need to read back in, or for metadata references in VS.  It's unclear to me why this would be an area that necessitates things like Lock-Free.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 28 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: These lines were necessary prior to `T` having the generic constraint `class`, but are now a NOP. I have removed them now and updated the documentation for both this and the `Target` property.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 27 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: If the compare exchange fails, you go back to the beginning of the `while(true)` and retry the read. This block is equivalent to the `Interlocked.Decrement` which is used in the alternate code path (now the only code path), except that it will assert rather than decrement the value if the loop is reached more than once for a given reference counted instance.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 14 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: My anticipation is this type becomes *the* wrapper we use for scenarios like this. I do not have data saying that *this* case necessitates lock free code, but over the last month I have observed countless cases over the past few weeks where failure to account for the cost of locks is manifesting in user-observable performance deficiencies.

The cost of locks is similar to the cost of memory allocations. If we can localize the complexity such that it does not escape past the API boundary of the type, and it's reasonably easy to implement, then avoiding them will contribute to the ongoing success of the product. In this case, the complexity of a lock-free implementation of `ReferenceCountedDisposable<T>` is completely contained, placing no additional burdens on outside code. The only thing outside code needs to be concerned with is not calling `Dispose` on the wrapper while the `Target` is still in use. However, this limitation is already a requirement for using the target type `T` even without the wrapper.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 29]
```diff
@@ -0,0 +1,225 @@
...
+            {
+                _instance = instance;
+                _boxedReferenceCount = new StrongBox<int>(1);
+            }
+
+            private ReferenceCountedDisposable(T instance, StrongBox<int> referenceCount)
+            {
+                _instance = instance;
+
+                // The reference count has already been incremented for this instance
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: Could we assert the value is >0 here?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 30]
```diff
@@ -0,0 +1,225 @@
...
+                public WeakReference(ReferenceCountedDisposable<T> reference)
+                    : this()
+                {
+                    var instance = reference._instance;
+                    var referenceCount = reference._boxedReferenceCount;
+                    if (instance == null || referenceCount == null)
+                    {
+                        // The specified reference is already not valid.
+                        return;
+                    }
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: 1. It's not possible for referenceCount to ever be null is it?  
2. Even if you grab this weak reference and hte _instance is non-null whne you grab it, can't another thread come in and let go of the last reference, and then dispose the 'instance' leaving you with a disposed instance here?

Or will this code only get it once the ref count has already been incremented?  If so, can we assert anything about the refcount here?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 31]
```diff
@@ -0,0 +1,225 @@
...
+            /// <summary>
+            /// Represents a weak reference to a <see cref="ReferenceCountedDisposable{T}"/> which is capable of
+            /// obtaining a new counted reference up until the point when the object is no longer accessible.
+            /// </summary>
+            public struct WeakReference
+            {
+                /// <summary>
+                /// DO NOT DISPOSE OF THE TARGET.
+                /// </summary>
+                private readonly WeakReference<T> _instance;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: in this type can you call this _weakInstance (as well as the locals)?  it will help make it clear that it's not actaully pointing at hte underlying 'instance' directlyt when someone sees that name in code.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs [hunk 32]
```diff
@@ -42,19 +93,69 @@ public ITemporaryTextStorage CreateTemporaryTextStorage(CancellationToken cancel
...
+                    return new MemoryMappedInfo(new ReferenceCountedDisposable<MemoryMappedFile>(storage), mapName, 0, size);
+                }
+
+                lock (_gate)
+                {
+                    // Obtain a reference to the memory mapped file, creating one if necessary. If a reference counted
+                    // handle to a memory mapped file is obtained in this section, it must either be disposed before
+                    // returning or returned to the caller who will own it through the MemoryMappedInfo.
+                    var reference = _fileReference.TryAddReference();
+                    if (reference == null || _offset + size > _fileSize)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: this seems weird.  say the reference is non-null.  You've now incremented the refcount.  But hten you check the size stuff.  And if the second condition is true, you decide to overwrite reference and _fileReference.  But nothing seems to decrement the ref count for _fileReference that you just incremented here.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs [hunk 33]
```diff
@@ -44,43 +58,46 @@ internal sealed class MemoryMappedInfo : IDisposable
...
+                _memoryMappedFile = memoryMappedFile;
+                _name = name;
+                _offset = offset;
                 _size = size;
-
-                _memoryMappedFile = MemoryMappedFile.CreateNew(_name, size);
             }
 
-            public MemoryMappedInfo(string name, long size)
+            public MemoryMappedInfo(string name, long offset, long size)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: can this constructor not just delegate to the constructor above?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs [hunk 34]
```diff
@@ -33,7 +33,21 @@ internal partial class TemporaryStorageServiceFactory
         /// </remarks>
         internal sealed class MemoryMappedInfo : IDisposable
         {
+            /// <summary>
+            /// The name of the memory mapped file.
+            /// </summary>
             private readonly string _name;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: consider using autoprops here.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs [hunk 35]
```diff
@@ -96,27 +113,21 @@ private void ForceCompactingGC()
             /// </summary>
             public Stream CreateReadableStream()
             {
-                // CreateViewStream is not guaranteed to be thread-safe
+                // CreateViewAccessor is not guaranteed to be thread-safe
                 lock (_memoryMappedFile)
                 {
-                    if (_accessor == null)
+                    // Note: TryAddReference will not return a non-null but invalid reference, even if the current
+                    // object has been disposed (see comments on _memoryMappedFile and TryAddReference).
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: this comment is hard to parse.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs [hunk 36]
```diff
@@ -96,27 +113,21 @@ private void ForceCompactingGC()
...
-                        {
-                            // CreateViewAccessor will use a native memory map - which can't trigger a GC.
-                            // In this case, we'd otherwise crash with OOM, so we don't care about creating a UI delay with a full forced compacting GC.
-                            // If it crashes the second try, it means we're legitimately out of resources.
-                            this.ForceCompactingGC();
-                            _accessor = _memoryMappedFile.CreateViewAccessor(0, _size, MemoryMappedFileAccess.Read);
-                        }
+                        var rawAccessor = RunWithCompactingGCFallback(info => info._memoryMappedFile.Target.CreateViewAccessor(info._offset, info._size, MemoryMappedFileAccess.Read), this);
+                        streamAccessor = new ReferenceCountedDisposable<MemoryMappedViewAccessor>(rawAccessor);
+                        _accessor = new ReferenceCountedDisposable<MemoryMappedViewAccessor>.WeakReference(streamAccessor);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: the existing _accessor is not disposed before you overwrite it?

Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: :arrow_right: `_accessor` is not disposable

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 30 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: 1. No, it's not possible. I can remove this check.
2. It would be equivalent to `new System.WeakReference(null)`. Costs an allocation but in the end `TryAddReference` will return null the same way it would any other time the target is disposed.

> Or will this code only get it once the ref count has already been incremented? If so, can we assert anything about the refcount here?

This is a weak reference; it never owns a [strong] reference. All values of `referenceCount.Value` are valid at this point, so the assertion would be trivially true.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 29 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: We could assert that the value is not equal to 0 here, but there is no requirement that it be positive.

Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: :memo: I avoided this check here originally for the following reasons:

1. It's not externally visible code
2. It would complicate the documentation for `_boxedReferenceCount`, which current has the following note:

    > Accesses to `Value` should only occur when this object is locked.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 35 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: ➡️ Hopefully the next push improves this.

**Comment by sharwell** [comment]
@dotnet-bot retest this please

File: src/Workspaces/Core/Portable/Execution/Serializer_Asset.cs (hunk 26 above)
Comment (heejaechang) [inline src/Workspaces/Core/Portable/Execution/Serializer_Asset.cs]: you don't need version update since this never get persisted across VS session.

**Comment by heejaechang** [comment]
@sharwell overall I like the idea. but 

one question is it looks like temporary storage can be created and deleted at any given point and chunk of the block for the memory never reuse the deleted memory. 

this seems easily can lead to memory fragmentation. due to the way Roslyn uses Temporary Storage, it might not actually surface as an issue but still potentially it can lead to fragmentation since some thing like closed file text might sit on the temporary storage long time, and other one like skeleton assembly, metadata from dll, or forked text for code action might come and go putting hole in the map.

...

another one is that, this number of memory map files, but this doesnt reduce VM. since VM is affected by the accessor not by number of memory map files.

I believe existing one already shared VM for accessor for same memory map file, and let them (accessor and the file) go once there is no one holding onto it (accessor)

it looks like behavior of accessor remained as it used to be. so VM's behavior seems same as before. (sure previous implementation could have some bugs that made it to consume more VM but the expected behavior seems remain same)

the suggested improvement from devdiv perf team (Calvin) was doing what you are doing for mmf to view. it was due to the fact that windows allocates VM in 64KB chunk, meaning if one create 1 byte view over mmf, windows will actually create 64KB VM for it. so to have best improvement on VM, his suggestion was implementation something like what you did to view.

...

also, history. if you see history of the mmf, you will see you had something similar as what you are doing here. and I removed those after consulting with devdiv perf team that it won't affect VM much and number of mmf is not as critical as VM. so I remove those to make the code simpler.

but, I dont believe it will hurt anything and there will be some benefit so, fine with the mmf improvement, but to improve VM, I believe we need same memory manager for view.

**Comment by sharwell** [comment]
> one question is it looks like temporary storage can be created and deleted at any given point and chunk of the block for the memory is never reused after the deleted memory.

Yes, this is correct. However, the fragmentation, if it occurs, will be part of the system's virtual address space and not part of the process where Roslyn is running. Only the *views* of the memory mapped files are brought into the address space of the process, and these views are the same size as they were prior to this change.

It is conceivable that a pathological case exists where several small non-consecutive files are created in temporary storage such that each is placed in its own memory mapped file, and then not reclaimed. If this happened, the system could run out of available address space. If there is ever a threat of this occurring, we could expand on the implementation here to allow reuse of MMF storage after it is released.

> another one is that, this reduces number of memory map files, but this doesnt reduce VM. since VM is affected by the accessor not by number of memory map files.

The VM improvement is due to `MemoryMappedInfo._accessor` being a weak reference as opposed to the current strong reference. This means the GC can reclaim this handle and release the view if nothing is currently accessing it. The work to use larger memory mapped files for storage was required to avoid regressing on the RPS issue described in #19493.

> it was due to the fact that windows allocates VM in 64KB chunk, meaning if one create 1 byte view over mmf, windows will actually create 64KB VM for it. (ask Calvin for more detail if you are curious, and his leak detection tool can actually show this) so to have best improvement on VM, his suggestion was implementing something like what you did to view.

I did consider this. However, it seems that temporary storage is unmapped far more often than it is mapped, so it didn't seem like it made much difference.

**Comment by heejaechang** [comment]
@sharwell  awesome. 

"The VM improvement is due to MemoryMappedInfo._accessor being a weak reference as opposed to the current strong reference"

this one is surprise though, the accessor should have been nulled out if there is no stream shared out. if there is someone that holds onto the stream, but it means there is someone who is accessing the memory. 

most of consumer of the temporary storage has really short life time, except skeleton assembly and metadata. but these two, they do need the stream during life time of themselves.

**Comment by sharwell** [comment]
> this one is surprise though, the accessor should have been nulled out if there is no stream shared out. if there is someone that holds onto the stream, that means there is someone who is accessing the memory.

This used to be the case. I removed it in #19522 not realizing that it was a critical behavior change. Specifically it was the `MemoryMappedInfo.StreamDisposed()` method which handled this case.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs [hunk 37]
```diff
@@ -30,8 +31,58 @@ public IWorkspaceService CreateService(HostWorkspaceServices workspaceServices)
         /// </summary>
         internal class TemporaryStorageService : ITemporaryStorageService2
         {
+            /// <summary>
+            /// The maximum size of a single storage unit in a memory mapped file which is shared with other storage
```
Comment (Pilchie) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: In what unit? bytes I assume?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 38]
```diff
@@ -0,0 +1,242 @@
...
+            /// <para>This value is only cleared in order to support cases where one or more references is garbage
+            /// collected without having <see cref="Dispose"/> called.</para>
+            /// </remarks>
+            private T _instance;
+
+            /// <summary>
+            /// The boxed reference count, which is shared by all references with the same <see cref="Target"/> object.
+            /// </summary>
+            /// <remarks>
+            /// <para>Only use equality operators to compare this value with 0. The actual reference count is allowed to
```
Comment (Pilchie) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: I'm not convinced this is necessary to support.  Are we expecting more than 2^31 references?

**Comment by CyrusNajmabadi** [comment]
Starting another pass.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs [hunk 39]
```diff
@@ -96,27 +102,22 @@ private void ForceCompactingGC()
             /// </summary>
             public Stream CreateReadableStream()
             {
-                // CreateViewStream is not guaranteed to be thread-safe
+                // CreateViewAccessor is not guaranteed to be thread-safe
                 lock (_memoryMappedFile)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: You're locking  _memoryMappedFile which is a "ReferenceCountedDisposable".  But i thought everyone got a fresh ReferenceCountedDisposable.  So will this lock actually do anything?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs [hunk 40]
```diff
@@ -44,43 +41,52 @@ internal sealed class MemoryMappedInfo : IDisposable
...
-            /// released until the reference count reaches zero.</para>
+            /// <para>This holds a weak counted reference to current <see cref="MemoryMappedViewAccessor"/>, which
+            /// allows additional accessors for the same address space to be obtained up until the point when no
+            /// external code is using it. When the memory is no longer being used by any
+            /// <see cref="SharedReadableStream"/> objects, the view of the memory mapped file is automatically
+            /// unmapped, making the process address space it previously claimed available for other purposes. If/when
+            /// it is needed again, a new view is created.</para>
             /// </remarks>
-            private MemoryMappedViewAccessor _accessor;
+            private ReferenceCountedDisposable<MemoryMappedViewAccessor>.WeakReference _weakAccessor;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: Sorry, i've forgotten now.  Why do we need this?  Aren't all references to the memory mapped data passed out through streams?  All our clients should dispose those streams.  So why can't we deterministically release the data once all the streams are gone?

Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: What i mean is: why can't we *only* deterministically release the data once all the streams are gone?  Why do we need anything related to weak references and whatnot?  Why can't this just be a purely refcounted system?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 41]
```diff
@@ -0,0 +1,242 @@
...
+            /// be a negative integer in order to support a reference count full 32-bit number of reference. Ideally it
+            /// would be represented as a <see cref="uint"/>, but some <see cref="Interlocked"/> operations are not
+            /// implemented for this type.</para>
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: I'm with kevin, this seems really complex and unnecessary.  Do we even test that this works properly?  Can we even envision a real case where we'd have 2 billion open references to a memory mapped file?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 29 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: I'm ok with some debug only code that locks this and validates that the value is > 0.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 42]
```diff
@@ -0,0 +1,242 @@
...
+        {
+            /// <summary>
+            /// The target of this reference. This value is initialized to a non-<see langword="null"/> value in the
+            /// constructor, and set to <see langword="null"/> when the current reference is disposed.
+            /// </summary>
+            /// <remarks>
+            /// <para>This value is only cleared in order to support cases where one or more references is garbage
+            /// collected without having <see cref="Dispose"/> called.</para>
+            /// </remarks>
+            private T _instance;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: Looks like this can be an autoprop.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 43]
```diff
@@ -0,0 +1,242 @@
...
+                        // The current reference has been disposed, so even though it isn't disposed yet we don't have a
+                        // reference to the target
+                        return null;
+                    }
+
+                    referenceCount.Value++;
+
+                    // Must return a new instance, in order for the Dispose operation on each individual instance to
+                    // be idempotent.
+                    return new ReferenceCountedDisposable<T>(target, referenceCount);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: If you are returning new instances, it's unclear to me why the MemoryMappedInfo guy locks on this.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 38 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: :arrow_right: No, but since the current implementation allows it I figured I might as well document it.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 44]
```diff
@@ -0,0 +1,242 @@
...
+            public struct WeakReference
+            {
+                /// <summary>
+                /// DO NOT DISPOSE OF THE TARGET.
+                /// </summary>
+                private readonly WeakReference<T> _weakInstance;
+                private readonly StrongBox<int> _boxedReferenceCount;
+
+                public WeakReference(ReferenceCountedDisposable<T> reference)
+                    : this()
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: is this necessary?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 39 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: Good catch, need to lock on the target.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 45]
```diff
@@ -0,0 +1,242 @@
...
+                    var instance = reference._instance;
+                    var referenceCount = reference._boxedReferenceCount;
+                    if (instance == null)
+                    {
+                        // The specified reference is already not valid.
+                        return;
+                    }
+
+                    _weakInstance = new WeakReference<T>(instance);
+                    _boxedReferenceCount = referenceCount;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: should we check if refcount is 0 here as well?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 46]
```diff
@@ -0,0 +1,242 @@
...
+                public ReferenceCountedDisposable<T> TryAddReference()
+                {
+                    var weakInstance = _weakInstance;
+                    if (weakInstance == null || !_weakInstance.TryGetTarget(out var target))
+                    {
+                        return null;
+                    }
+
+                    var referenceCount = _boxedReferenceCount;
+                    if (referenceCount == null)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: how could referenceCount be null if you get to this line of code?  If it was null, then wouldn't _weakInstance be null as well?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs (hunk 37 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: Could a comment be provided explaining where these numbers came from?  Why 128k in this case for example?  Thanks!

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 40 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: ➡️ `MemoryMappedInfo` needs access to one of the view accessors currently in use in order to provide a new view of the same data.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs [hunk 47]
```diff
@@ -30,8 +31,58 @@ public IWorkspaceService CreateService(HostWorkspaceServices workspaceServices)
...
+            /// units.
+            /// </summary>
+            private const long SingleFileThreshold = 128 * 1024;
+
+            /// <summary>
+            /// The size of a memory mapped file created to store multiple temporary objects.
+            /// </summary>
+            private const long MultiFileBlockSize = SingleFileThreshold * 32;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: If a multifile block is around 4MB, then why would we not allow it to store files that were, say, 256k in it?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 41 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: No special accommodations for this were made in the code.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs [hunk 48]
```diff
@@ -42,19 +93,69 @@ public ITemporaryTextStorage CreateTemporaryTextStorage(CancellationToken cancel
...
+                    {
+                        var mapName = CreateUniqueName(MultiFileBlockSize);
+                        var file = MemoryMappedFile.CreateNew(mapName, MultiFileBlockSize);
+
+                        reference = new ReferenceCountedDisposable<MemoryMappedFile>(file);
+                        _weakFileReference = new ReferenceCountedDisposable<MemoryMappedFile>.WeakReference(reference);
+                        _name = mapName;
+                        _fileSize = MultiFileBlockSize;
+                        _offset = 0;
+                    }
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: i feel like falling through ehre makes things more difficult.  Can we just ahve two codepaths:  one for when you can reuse the existing file reference, and one for whne you need to make a fresh reference.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs [hunk 49]
```diff
@@ -42,19 +93,69 @@ public ITemporaryTextStorage CreateTemporaryTextStorage(CancellationToken cancel
...
+
+                    // Reserve additional space in this storage location
+                    _offset += size;
+                    var endOffset = _offset;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: is this local needed?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs [hunk 50]
```diff
@@ -68,14 +169,15 @@ public TemporaryTextStorage(TemporaryStorageService service)
...
                 {
                     _service = service;
                     _encoding = encoding;
-                    _memoryMappedInfo = new MemoryMappedInfo(storageName, size);
+                    _memoryMappedInfo = new MemoryMappedInfo(storageName, offset, size);
                 }
 
                 public string Name => _memoryMappedInfo?.Name;
+                public long Offset => _memoryMappedInfo.Offset;
                 public long Size => _memoryMappedInfo.Size;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: Name uses ?. but hte others use .   is that intentional?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 43 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: (Covered at previous mention)

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs [hunk 51]
```diff
@@ -141,7 +243,7 @@ public void WriteText(SourceText text, CancellationToken cancellationToken)
 
                         // the method we use to get text out of SourceText uses Unicode (2bytes per char). 
                         var size = Encoding.Unicode.GetMaxByteCount(text.Length);
-                        _memoryMappedInfo = new MemoryMappedInfo(size);
+                        _memoryMappedInfo = _service.CreateTemporaryStorage(size);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: the names here look really wonke.  We're asking to CreateTempStorage.. but that's returning a MemoryMappedInfo?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 45 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: :arrow_right: No, it's allowed to be 0.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 46 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: It couldn't be `null` here (will remove check)

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 40 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: But you have "_memoryMappedFile".  Can't you just use what it points to as long as it's ref count is not 0?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs (hunk 47 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: What's the comment for "I picked some values and they seemed to work so I left it"?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 41 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: We don't generally accomodate for this.  We have lots of counters that would likely rollover at 2^31.  But it's so out of hte realm of possible that we would hit this (we never have in all the time that roslyn has existed) that we just treated these as unsigned, and we consider the entire negative range to be offlimits.  It just makes things much easier to reason about.  And we don't have to somehow figure out a way to test that things work properly when these values roll over.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs (hunk 50 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: I'm not sure. I was just using the existing pattern (predated my initial work on this file).

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 45 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: When is that valuable.  If hte refcount is 0, why we would support keeping a weak reference around to the instance?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs (hunk 51 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: 💭 The `MemoryMappedInfo` describes the location of the temporary storage.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs (hunk 47 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: Say exactly that.  "These values were picked because they seemed reasonable and we didn't observe anything negative when we tested.  If necessary they can be changed based on data that indicates otherwise."

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 40 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: `_memoryMappedFile` is a reference to the `MemoryMappedFile`, not the view. (It also never has a reference count of 0 unless the `MemoryMappedInfo` has been disposed.)

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 45 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: Avoids the need to have locks in this method. The `TryAddReference` method does the validation of the reference count.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 42 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: I feel like this change would complicate the documentation of the implementation.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 41 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: Switched to using `checked` instead.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs (hunk 37 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: Updated the comments to clarify both items.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 38 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: :memo: switched to using `checked` instead.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs (hunk 49 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: Not really, removed.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 52]
```diff
@@ -0,0 +1,240 @@
...
+            }
+
+            /// <summary>
+            /// Gets the target object.
+            /// </summary>
+            /// <remarks>
+            /// <para>This call is not valid after <see cref="Dispose"/> is called. If this property or the target
+            /// object is used concurrently with a call to <see cref="Dispose"/>, it is possible for the code to be
+            /// using a disposed object. After the current instance is disposed, this property returns
+            /// <see langword="null"/>. However, the exact time when this property starts returning null after
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: Is there a reason this isn't throwing ObjectDisposedException instead?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 53]
```diff
@@ -0,0 +1,240 @@
...
+                    if (reference == null)
+                    {
+                        throw new ArgumentNullException(nameof(reference));
+                    }
+
+                    var instance = reference._instance;
+                    var referenceCount = reference._boxedReferenceCount;
+                    if (instance == null)
+                    {
+                        // The specified reference is already not valid.
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: Just to be clear: this is programmer error, effectively, since you're giving it an already disposed instance? Should it throw in this case?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 54]
```diff
@@ -0,0 +1,240 @@
...
+                /// <para>The returned object is an independent reference to the same underlying object. Disposing of
+                /// the returned value multiple times will only cause the reference count to be decreased once.</para>
+                /// </remarks>
+                /// <returns>A new <see cref="ReferenceCountedDisposable{T}"/> pointing to the same underlying object,
+                /// if it has not yet been disposed; otherwise, <see langword="null"/> if the underlying object has
+                /// already been disposed.</returns>
+                public ReferenceCountedDisposable<T> TryAddReference()
+                {
+                    var weakInstance = _weakInstance;
+                    if (weakInstance == null || !_weakInstance.TryGetTarget(out var target))
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: Is the weakInstance == null case for default-initialized stucts? Might be worth a comment (or an exception if that's considered programmer error?)

Comment (jasonmalinowski) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: The !TryGetTarget is also implied by the actual implementation of TryAddReferenceImpl, not sure if that's an interesting fact or not.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs [hunk 55]
```diff
@@ -30,8 +31,66 @@ public IWorkspaceService CreateService(HostWorkspaceServices workspaceServices)
...
+            /// <summary>
+            /// The most recent memory mapped file for creating multiple storage units. It will be used via bump-pointer
+            /// allocation until space is no longer available in it.
+            /// </summary>
+            /// <remarks>
+            /// <para>Access should be synchronized on <see cref="_gate"/>.</para>
+            /// </remarks>
+            private ReferenceCountedDisposable<MemoryMappedFile>.WeakReference _weakFileReference;
+
+            /// <summary>The name of the current memory mapped file for multiple storage units.</summary>
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: In all cases "the current memory mapped file" is the thing referenced by _weakFileReference? Might be good to cref it so the relationship is explicit.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs [hunk 56]
```diff
@@ -42,19 +101,70 @@ public ITemporaryTextStorage CreateTemporaryTextStorage(CancellationToken cancel
...
+            /// <param name="size">The size of the shared storage block to allocate.</param>
+            /// <returns>A <see cref="MemoryMappedInfo"/> describing the allocated block.</returns>
+            private MemoryMappedInfo CreateTemporaryStorage(long size)
+            {
+                if (size >= SingleFileThreshold)
+                {
+                    // Larger blocks are allocated separately
+                    var mapName = CreateUniqueName(size);
+                    var storage = MemoryMappedFile.CreateNew(mapName, size);
+                    return new MemoryMappedInfo(new ReferenceCountedDisposable<MemoryMappedFile>(storage), mapName, 0, size);
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: nit: named arguments for what I assume is offset and size at the end.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs [hunk 57]
```diff
@@ -42,19 +101,70 @@ public ITemporaryTextStorage CreateTemporaryTextStorage(CancellationToken cancel
...
+                    {
+                        var mapName = CreateUniqueName(MultiFileBlockSize);
+                        var file = MemoryMappedFile.CreateNew(mapName, MultiFileBlockSize);
+
+                        reference = new ReferenceCountedDisposable<MemoryMappedFile>(file);
+                        _weakFileReference = new ReferenceCountedDisposable<MemoryMappedFile>.WeakReference(reference);
+                        _name = mapName;
+                        _fileSize = MultiFileBlockSize;
+                        _offset = size;
+                        return new MemoryMappedInfo(reference, _name, _offset - size, size);
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: `_offset - size` is zero, right?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs (hunk 51 above)
Comment (jasonmalinowski) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: I think my thought for the name would be `MemoryMappedBlock` or `MemoryMappedAllocation` or something like that. I've been bugged by the name too.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs [hunk 58]
```diff
@@ -44,43 +41,52 @@ internal sealed class MemoryMappedInfo : IDisposable
...
-            /// <para>It is possible for this accessor to be disposed prior to the streams which use it. However, the
-            /// streams interact directly with the underlying memory buffer, and keep a
-            /// <see cref="CopiedMemoryMappedViewHandle"/> to prevent that buffer from being released while still in
-            /// use. The <see cref="SafeHandle"/> used by this accessor is reference counted, and is not finally
-            /// released until the reference count reaches zero.</para>
+            /// <para>This holds a weak counted reference to current <see cref="MemoryMappedViewAccessor"/>, which
+            /// allows additional accessors for the same address space to be obtained up until the point when no
+            /// external code is using it. When the memory is no longer being used by any
+            /// <see cref="SharedReadableStream"/> objects, the view of the memory mapped file is automatically
+            /// unmapped, making the process address space it previously claimed available for other purposes. If/when
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: "automatically unmapped" by the MemoryMappedViewAccessor's finalizer, right?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 40 above)
Comment (jasonmalinowski) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: It might be worth mentioning this is only used for reads, and writes always get their own accessor. Maybe rename to _weakReadAccessor.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs [hunk 59]
```diff
@@ -143,38 +174,25 @@ private void Dispose(bool disposing)
...
-                        {
-                            // (see remarks on accessor for relation between _accessor and the streams)
-                            _accessor.Dispose();
-                            _accessor = null;
-                        }
-                    }
-
-                    // (see remarks on accessor for relation between _memoryMappedFile and the views/streams)
+                    // See remarks on field for relation between _memoryMappedFile and the views/streams. There is no
+                    // need to write _weakAccessor here since the types involved adhere to their contracts even in
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: Might be worth replacing this sentence with "There is no need to write _weakAccessor, since it will return null for any further reads". Basically, state which contract you're relying on, so when somebody changes the contract and doesn't update this it's more clear what happened.

File: src/Workspaces/Core/Portable/Workspace/Host/TemporaryStorage/ITemporaryStorageService2.cs [hunk 60]
```diff
@@ -13,11 +13,11 @@ internal interface ITemporaryStorageService2 : ITemporaryStorageService
         /// <summary>
         /// Attach to existing <see cref="ITemporaryStreamStorage"/> with given name.
         /// </summary>
-        ITemporaryStreamStorage AttachTemporaryStreamStorage(string storageName, long size, CancellationToken cancellationToken = default(CancellationToken));
+        ITemporaryStreamStorage AttachTemporaryStreamStorage(string storageName, long offset, long size, CancellationToken cancellationToken = default(CancellationToken));
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Workspace/Host/TemporaryStorage/ITemporaryStorageService2.cs]: I admit I wish this API had a "temporary stream handle" struct that was name + offset + size, and that got passed around, rather than leaving it up to callers to not screw up offset/size ordering. ITemporaryStorageWithName then would become ITemporaryStorageWithHandle, or perhaps just a GetHandle call...

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 61]
```diff
@@ -0,0 +1,240 @@
...
+        /// in the event one or more callers fail to do so. The underlying object will be deterministically released
+        /// when the last reference to it is disposed. However, the underlying object is eligible for non-deterministic
+        /// release (should it have a finalizer) when each reference to it is <em>either</em> disposed <em>or</em>
+        /// eligible for garbage collection itself.</para>
+        ///
+        /// <para>All public methods on this type adhere to their pre- and post-conditions and will not invalidate state
+        /// even in concurrent execution.</para>
+        /// </remarks>
+        /// <typeparam name="T">The type of disposable object.</typeparam>
+        internal sealed class ReferenceCountedDisposable<T> : IDisposable
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: I wouldn't be against this type being moved outside the parent class and into untilities. I'm wondering if we have other places too that reimplement this pattern. Some of our reference handling in VS comes to mind...

Comment (jasonmalinowski) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: (it'd also be great because then we know that there isn't any accidental touching of private state somewhere else...)

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 52 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: ➡️ In the presence of concurrent code, it's impossible to make this guarantee to the caller. For example, it's possible to call this method without an exception, but then have `Dispose` called before the returned object is used. I opted to instead leave the fast path as fast as possible.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 53 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: No, this is intended to be the equivalent of `new WeakReference(null)`. It's allowed, but when you get the target it will return null. The special case is simply to avoid an unnecessary allocation when this happens.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 54 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: :arrow_right: `where T : class`

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs (hunk 57 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: Yes, the duplicate construction was a request of @CyrusNajmabadi but I opted to keep the coded semantics readily apparent (i.e. same code in both cases).

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 53 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: I'll expand on this comment

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 61 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: I'm very happy with the exposed semantics of this type, and believe it (and in particular the concurrent version) is approaching an ideal solution for the general use case. But that's for another time IMO.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 62]
```diff
@@ -0,0 +1,240 @@
...
+        /// <remarks>
+        /// <para>While each instance of <see cref="ReferenceCountedDisposable{T}"/> should be explicitly disposed when
+        /// the object is no longer needed by the code owning the reference, this implementation will not leak resources
+        /// in the event one or more callers fail to do so. The underlying object will be deterministically released
+        /// when the last reference to it is disposed. However, the underlying object is eligible for non-deterministic
+        /// release (should it have a finalizer) when each reference to it is <em>either</em> disposed <em>or</em>
+        /// eligible for garbage collection itself.</para>
+        ///
+        /// <para>All public methods on this type adhere to their pre- and post-conditions and will not invalidate state
+        /// even in concurrent execution.</para>
```
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: ➡️ Don't blame me. Y'all are the ones who assigned me to the same team as @jaredpar.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 63]
```diff
@@ -0,0 +1,240 @@
...
+        /// <summary>
+        /// A reference-counting wrapper which allows multiple uses of a single disposable object in code, which is
+        /// deterministically released (by calling <see cref="IDisposable.Dispose"/>) when the last reference is
+        /// disposed.
+        /// </summary>
+        /// <remarks>
+        /// <para>While each instance of <see cref="ReferenceCountedDisposable{T}"/> should be explicitly disposed when
+        /// the object is no longer needed by the code owning the reference, this implementation will not leak resources
+        /// in the event one or more callers fail to do so. The underlying object will be deterministically released
+        /// when the last reference to it is disposed. However, the underlying object is eligible for non-deterministic
```
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: :jasonmal:

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs (hunk 57 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: in this case, i seems clearer as 0.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 64]
```diff
@@ -0,0 +1,240 @@
...
+        /// release (should it have a finalizer) when each reference to it is <em>either</em> disposed <em>or</em>
```
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: :memo: Your "in other words" wording is not accurate... trying to rephrase in the comment.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 58 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: Addressed by removing the word "automatically"

**Comment by sharwell** [comment]
@jasonmalinowski Most of my work from your feedback is in commit 2fed1d36a338cf6daf414cf9f68e1288c08c5c95 so it applies to the concurrent code in history. I updated the final single commit which switches to using locks to address the small number of items which you mentioned which were only relevant to that.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 52 above)
Comment (jasonmalinowski) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: @sharwell Well, but that's the caller's mishandling of concurrency, not yours. The caller could also just write (in a single threaded way):

    var blah = reference.Target;
    reference.Dispose();
    // use blah

which from the perspective of your type is the same race you're worried about. Put another way, that's the *caller* being unsynchronized in their calls, which are invalid regardless of the guarantees you make for your type.

I suspect the check works out to be two x86 instructions that might add up to nearly no measurable time, especially given the uses of this type are doing things like creating memory mapped files and messing with virtual memory. The cost to us of finding a bug will be orders and orders of magnitude larger. I'd just add the check.

Comment (jasonmalinowski) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: Maybe another thought: you can't be safe when people misuse you, but it's probably better to let them not misuse you then. :smile:

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs [hunk 65]
```diff
@@ -96,27 +104,22 @@ private void ForceCompactingGC()
             /// </summary>
             public Stream CreateReadableStream()
             {
-                // CreateViewStream is not guaranteed to be thread-safe
-                lock (_memoryMappedFile)
+                // CreateViewAccessor is not guaranteed to be thread-safe
+                lock (_memoryMappedFile.Target)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: Just want to confirm: this is safe?  i.e. as long as we ahven't disposed _memoryMappedFile ourselves, then .Target will be non null.  And, if we had disposed, then this would throw... but tha'ts ok because it's not safe to use this after disposing.  Right?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 66]
```diff
@@ -0,0 +1,269 @@
...
+        /// target object is not disposed early.</para>
+        ///
+        /// <list type="number">
+        /// <para>Use <see cref="ReferenceCountedDisposable{T}"/> consistently. In other words, do not mix code using
+        /// reference-counted wrappers with code that references to the target directly.</para>
+        /// <para>Only use the <see cref="ReferenceCountedDisposable{T}(T)"/> constructor one time per target object.
+        /// Additional references to the same target object must only be obtained by calling
+        /// <see cref="TryAddReference"/>.</para>
+        /// <para>Do not call <see cref="IDisposable.Dispose"/> on the target object directly. It will be called
+        /// automatically at the appropriate time, as described above.</para>
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: great comment.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 67]
```diff
@@ -0,0 +1,269 @@
...
+            /// <summary>
+            /// Initializes a new reference counting wrapper around an <see cref="IDisposable"/> object.
+            /// </summary>
+            /// <remarks>
+            /// <para>The reference count is initialized to 1.</para>
+            /// </remarks>
+            /// <param name="instance">The object owned by this wrapper.</param>
+            public ReferenceCountedDisposable(T instance)
+            {
+                _instance = instance ?? throw new ArgumentNullException(nameof(instance));
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: good :)

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs [hunk 68]
```diff
@@ -0,0 +1,269 @@
...
+                _boxedReferenceCount = new StrongBox<int>(1);
+            }
+
+            private ReferenceCountedDisposable(T instance, StrongBox<int> referenceCount)
+            {
+                _instance = instance;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: Do we need the throw here as well?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 65 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: This is correct.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 68 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: No, and it would be impossible to cover the case if we tried. This private constructor is only used from a place where the target is known to not be null.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 66 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: I was happy with how this one turned out.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 68 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: if the target is known to "not be null"... why can't we add a null check here?  then we can also just merge the constructors, right?

Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: i.e. delegate

Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: Switched to constructor chaining

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs (hunk 9 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.ReferenceCountedDisposable.cs]: ➡️ The resolution to this discussion was preserving the concurrent implementation in source control history, should it be required in the future. I implemented the algorithm as a means to ensure this feature will perform admirably in concurrent scenarios, and while a bit abstract, this approach does address my underlying concern while also saving time on the review.

**Comment by sharwell** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please
@dotnet-bot retest windows_eta_open_prtest please

**Comment by sharwell** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

**Comment by sharwell** [comment]
@MattGertz for ask mode
