### PR TITLE
Do not use constrained call on a conditional access receiver known to be a reference type.

### LINKED ISSUE #23351: Invalid IL is emitted for a conditional access of off a constrained generic type parameter
Compile and run the following program:
```
Module Module1
    Sub Main()
        Dim obj1 As New MyObject1 With {.MyDate = CDate("2017-11-13T14:25:00Z")}
        Dim obj2 As New MyObject2(Of MyObject1)(obj1)

        System.Console.WriteLine(obj1.MyDate.Ticks)
        System.Console.WriteLine(obj2.CurrentDate.Value.Ticks)
    End Sub
End Module

Public MustInherit Class MyBaseObject1
    Property MyDate As Date
End Class

Public Class MyObject1
    Inherits MyBaseObject1
End Class

Public Class MyObject2(Of MyObjectType As {MyBaseObject1, New})
    Public Sub New(obj As MyObjectType)
        m_CurrentObject1 = obj
    End Sub

    Private m_CurrentObject1 As MyObjectType = Nothing
    Public ReadOnly Property CurrentObject1 As MyObjectType
        Get
            Return m_CurrentObject1
        End Get
    End Property
    Public ReadOnly Property CurrentDate As Date?
        Get
            Return CurrentObject1?.MyDate
        End Get
    End Property
End Class
```

**Observed:**
```
636461511000000000
2886802138464272
```

Also, PEVerify fails
```
[IL]: Error: MyObject2`1[MyObjectType]::get_CurrentDate][offset 0x00000021] The 'this' argument to a constrained call must have ByRef type.
``` 

**Expected:**
```
636461511000000000
636461511000000000
```
PEVerify succeeds.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #23351.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

File: src/Compilers/VisualBasic/Portable/CodeGen/EmitExpression.vb [hunk 1]
```diff
@@ -1034,7 +1034,9 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.CodeGen
                     ' if the receiver is actually a value type it would need to be boxed.
                     ' let .constrained sort this out. 
 
-                    callKind = If(receiverType.IsReferenceType AndAlso Not AllowedToTakeRef(receiver, AddressKind.ReadOnly),
+                    Debug.Assert(Not receiverType.IsReferenceType OrElse receiver.Kind <> BoundKind.ComplexConditionalAccessReceiver)
+                    callKind = If(receiverType.IsReferenceType AndAlso
+                                   (receiver.Kind = BoundKind.ConditionalAccessReceiverPlaceholder OrElse Not AllowedToTakeRef(receiver, AddressKind.ReadOnly)),
```
Comment (gafter) [inline src/Compilers/VisualBasic/Portable/CodeGen/EmitExpression.vb]: >AllowedToTakeRef [](start = 110, length = 16)

I am a bit surprised you didn't fix this by making `AllowedToTakeRef` return false for a `ConditionalAccessReceiverPlaceholder`

Comment (gafter) [reply src/Compilers/VisualBasic/Portable/CodeGen/EmitExpression.vb]: Unless one is really allowed to take a ref of the placeholder, I would think that is a more correct fix.

---
In reply to: [152643217](https://github.com/dotnet/roslyn/pull/23359#discussion_r152643217) [](ancestors = 152643217)

File: src/Compilers/VisualBasic/Test/Semantic/Semantics/ConditionalAccessTests.vb [hunk 2]
```diff
@@ -9553,5 +9553,117 @@ Test
...
+
+    Private m_CurrentObject1 As MyObjectType = Nothing
+    Public ReadOnly Property CurrentObject1 As MyObjectType
+        Get
+            Return m_CurrentObject1
+        End Get
+    End Property
+    Public ReadOnly Property CurrentDate As Date?
+        Get
+            Return CurrentObject1?.MyDate
```
Comment (jcouv) [inline src/Compilers/VisualBasic/Test/Semantic/Semantics/ConditionalAccessTests.vb]: Consider verifying IL on the conditional call

File: src/Compilers/VisualBasic/Portable/CodeGen/EmitExpression.vb (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Portable/CodeGen/EmitExpression.vb]: > I am a bit surprised you didn't fix this by making AllowedToTakeRef return false for a ConditionalAccessReceiverPlaceholder

> Unless one is really allowed to take a ref of the placeholder, I would think that is a more correct fix.

The placeholder node simply indicates that whatever we need is already on the stack in a suitable form. The logic I added ensures that we respect the form of the receiver that EmitConditionalAccess puts on the stack. Changing behavior of AllowedToTakeRef is going to break other scenarios, when a type parameter is not known to be a reference, or a value type. For example, when there are no constraints at all, or all constraints are interfaces, etc.

File: src/Compilers/VisualBasic/Test/Semantic/Semantics/ConditionalAccessTests.vb (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Test/Semantic/Semantics/ConditionalAccessTests.vb]: > Consider verifying IL on the conditional call

I intentionally didn't add IL comparison. Asserting runtime behavior and relying on PEVerify should be sufficient and they would fail before we have a chance to compare IL.

File: src/Compilers/VisualBasic/Portable/CodeGen/EmitExpression.vb (hunk 1 above)
Comment (VSadov) [reply src/Compilers/VisualBasic/Portable/CodeGen/EmitExpression.vb]: When receiver is known to be a reference type CallVirt is better than ConstrainedCallVirt because the result would be the same but the second requires a reference. I.E. if you have a value on the left, you would need to store it into a temp and push a ref to that temp.

C# is even more aggressive here with use of CallVirt - if receiver is not already a ref (only few cases are possible - like a result of a ref method invocation), then it forces CallVirt. 
In particular the receiver of a conditional call is never a ref when it has a reference type - since we need to null-check the value.

I think the fix is good enough. 
Porting `private bool IsRef(BoundExpression receiver)` from C# could have the same effect and improve code in related cases.

---
In reply to: [152643493](https://github.com/dotnet/roslyn/pull/23359#discussion_r152643493) [](ancestors = 152643493,152643217)

Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Portable/CodeGen/EmitExpression.vb]: > Porting private bool IsRef(BoundExpression receiver) from C# could have the same effect and improve code in related cases.

Opened https://github.com/dotnet/roslyn/issues/23362
