### PR TITLE
Auto-indentation on colon for switches with patterns

### LINKED ISSUE #9097: Indentation on colon not working for switches with patterns.
In a normal switch, when you type colon in a case clause, the case clause is properly dedented and aligned.  This does not work for case clauses with complex patterns in them.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #9097 

@CyrusNajmabadi @dotnet/roslyn-ide please review.

### CODE REVIEW

**Comment by DustinCampbell** [comment]
:+1:

**Comment by jaredpar** [comment]
:+1:

File: src/EditorFeatures/CSharp/Formatting/CSharpEditorFormattingService.cs [hunk 1]
```diff
@@ -151,7 +151,7 @@ private static bool TokenShouldNotFormatOnReturn(SyntaxToken token)
         private static bool TokenShouldNotFormatOnTypeChar(SyntaxToken token)
         {
             return (token.IsKind(SyntaxKind.CloseParenToken) && !token.Parent.IsKind(SyntaxKind.UsingStatement)) ||
-                (token.IsKind(SyntaxKind.ColonToken) && !(token.Parent.IsKind(SyntaxKind.LabeledStatement) || token.Parent.IsKind(SyntaxKind.CaseSwitchLabel) || token.Parent.IsKind(SyntaxKind.DefaultSwitchLabel)));
+                (token.IsKind(SyntaxKind.ColonToken) && !(token.Parent.IsKind(SyntaxKind.LabeledStatement) || token.Parent is SwitchLabelSyntax));
```
Comment (jaredpar) [inline src/EditorFeatures/CSharp/Formatting/CSharpEditorFormattingService.cs]: Doh, should have caught that when I fixed the other switch issues :frowning:
