### PR TITLE
Address a number of variance safety issues with code in interfaces.

### LINKED ISSUE #39731: C# compiler should issue CS1961 for variance violations for local functions within default interface methods
**Version Used**: 
Visual Studio 16.3.8
.Net Core 3.0
csc 3.3.1-beta3-19461-02

**Steps to Reproduce**:

Example repro (either interface will do)

```
public interface ICovariant<out T> {
    void DefaultMethod() {
        static void LocalFunction(T t) { }
    }
}

public interface IContravariant<in T>{
    void DefaultMethod() {
        static T LocalFunction() => default;
    }
}

class Program {
    static void Main(string[] args) {
        ICovariant<object> covariant;
        IContravariant<object> contravariant;
    }
}
```

**Expected Behavior**:
A local function which uses a variant generic type parameter incorrectly should cause a CS1961 'invalid variance' error if the local function is contained within a default interface method. 

**Actual Behavior**:

The program will compile successfully, but throw at runtime when loading the containing type:
```
System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'ICovariant`1' from assembly 'ScratchCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' because a covariant or contravariant type parameter was used illegally in the signature for an argument in method '<DefaultMethod>g__LocalFunction|0_0'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #39731.

- Declaration of classes, structures and enums within variant interfaces is disallowed.
- Nested classes synthesized by the compiler don't have variant emitted type parameters.
- Local functions and lambdas used within a variant interface always have display class.

### CODE REVIEW

File: src/Compilers/Core/Portable/PEWriter/InheritedTypeParameter.cs [hunk 1]
```diff
@@ -56,7 +56,7 @@ public bool MustHaveDefaultConstructor
 
         public TypeParameterVariance Variance
         {
-            get { return _parentParameter.Variance; }
+            get { return _inheritingType.IsInterface || _inheritingType.IsDelegate ? _parentParameter.Variance : TypeParameterVariance.NonVariant; }
```
Comment (agocke) [inline src/Compilers/Core/Portable/PEWriter/InheritedTypeParameter.cs]: Not sure I understand this change. In what situation is the inheriting type not an interface or a delegate, but the parentParameter variance is variant, and that is incorrect?

File: src/Compilers/CSharp/Portable/Symbols/VarianceSafety.cs [hunk 2]
```diff
@@ -52,10 +54,70 @@ internal static void CheckInterfaceVarianceSafety(this NamedTypeSymbol interface
...
+
+            if (container is object)
+            {
+                Debug.Assert(container.IsInterfaceType());
+                Debug.Assert(container.TypeParameters.Any(tp => tp.Variance != VarianceKind.None));
+                diagnostics.Add(ErrorCode.ERR_VarianceInterfaceNesting, member.Locations[0]);
+            }
+        }
+
+        internal static NamedTypeSymbol GetEnclosingVariantInterface(Symbol member)
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/VarianceSafety.cs]: Should this return `NamedTypeSymbol?` since null is an intended part of the return type?

File: src/Compilers/CSharp/Portable/Symbols/VarianceSafety.cs [hunk 3]
```diff
@@ -52,10 +54,70 @@ internal static void CheckInterfaceVarianceSafety(this NamedTypeSymbol interface
                     case SymbolKind.Event:
                         CheckEventVarianceSafety((EventSymbol)member, diagnostics);
                         break;
+                    case SymbolKind.NamedType:
+                        CheckNestedTypeVarianceSafety((NamedTypeSymbol)member, diagnostics);
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/VarianceSafety.cs]: The intent here is to make any nested type inside a variant interface an error, right?

File: src/Compilers/Core/Portable/PEWriter/InheritedTypeParameter.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/Core/Portable/PEWriter/InheritedTypeParameter.cs]: > Not sure I understand this change. In what situation is the inheriting type not an interface or a delegate, but the parentParameter variance is variant, and that is incorrect?

A class nested into an interface (for example, a display class) is inheriting type parameters of the containing interface. Those type parameters could be variant, but only interfaces and delegates are allowed to have variant type parameters.

---
In reply to: [347048798](https://github.com/dotnet/roslyn/pull/39839#discussion_r347048798) [](ancestors = 347048798)

File: src/Compilers/CSharp/Portable/Symbols/VarianceSafety.cs (hunk 3 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/VarianceSafety.cs]: > The intent here is to make any nested type inside a variant interface an error, right?

Not any nested type, delegates and interfaces are Ok.

---
In reply to: [347049921](https://github.com/dotnet/roslyn/pull/39839#discussion_r347049921) [](ancestors = 347049921)

File: src/Compilers/CSharp/Portable/Symbols/VarianceSafety.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/VarianceSafety.cs]: > Should this return NamedTypeSymbol? since null is an intended part of the return type?

Nullable Reference Types feature hasn't been enabled in this file yet.


---
In reply to: [347049241](https://github.com/dotnet/roslyn/pull/39839#discussion_r347049241) [](ancestors = 347049241)

File: src/Compilers/Core/Portable/PEWriter/InheritedTypeParameter.cs (hunk 1 above)
Comment (agocke) [reply src/Compilers/Core/Portable/PEWriter/InheritedTypeParameter.cs]: Got it, thanks.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need second sign-off.

**Comment by AlekseyTs** [comment]
@gafter, @dotnet/roslyn-compiler Please review, need second sign-off.

**Comment by gafter** [comment]
Reviewing...

File: src/Compilers/CSharp/Portable/Errors/ErrorCode.cs [hunk 4]
```diff
@@ -1735,6 +1735,7 @@ internal enum ErrorCode
         #endregion diagnostics introduced for C# 8.0
 
         ERR_InternalError = 8751,
+        ERR_VarianceInterfaceNesting = 8752,
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Errors/ErrorCode.cs]: >ERR_VarianceInterfaceNesting [](start = 8, length = 28)

I think this error code should be moved into the section of "diagnostics introduced for C# 8.0"

File: src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.Analysis.cs [hunk 5]
```diff
@@ -246,7 +246,12 @@ private void InlineThisOnlyEnvironments()
                         RemoveEnv();
                     }
                 }
-                else
+                // If we are in a variant interface, runtime might not consider the 
+                // method synthesized directly within the interface as viriant safe.
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.Analysis.cs]: >viriant [](start = 71, length = 7)

spelling

File: src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.Analysis.cs [hunk 6]
```diff
@@ -299,7 +304,13 @@ private void MakeAndAssignEnvironments()
                     // functions that capture those variables, so multiple passes may
                     // be needed. This will also decide if the environment is a struct
                     // or a class.
-                    bool isStruct = true;
+
+                    // If we are in a variant interface, runtime might not consider the 
+                    // method synthesized directly within the interface as viriant safe.
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.Analysis.cs]: >viriant [](start = 75, length = 7)

spelling

File: src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.cs [hunk 7]
```diff
@@ -424,9 +424,15 @@ private void SynthesizeLoweredFunctionMethods()
...
                     closureOrdinal = LambdaDebugInfo.ThisOnlyClosureOrdinal;
                 }
-                else if (closure.CapturedEnvironments.Count == 0 &&
-                         originalMethod.MethodKind == MethodKind.LambdaMethod &&
-                         _analysis.MethodsConvertedToDelegates.Contains(originalMethod))
+                else if ((closure.CapturedEnvironments.Count == 0 &&
+                          originalMethod.MethodKind == MethodKind.LambdaMethod &&
+                          _analysis.MethodsConvertedToDelegates.Contains(originalMethod)) ||
+                         // If we are in a variant interface, runtime might not consider the 
+                         // method synthesized directly within the interface as viriant safe.
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.cs]: >viriant [](start = 80, length = 7)

spelling

File: src/Compilers/CSharp/Portable/Symbols/VarianceSafety.cs [hunk 8]
```diff
@@ -52,10 +54,70 @@ internal static void CheckInterfaceVarianceSafety(this NamedTypeSymbol interface
...
+            {
+                Debug.Assert(container.IsInterfaceType());
+                Debug.Assert(container.TypeParameters.Any(tp => tp.Variance != VarianceKind.None));
+                diagnostics.Add(ErrorCode.ERR_VarianceInterfaceNesting, member.Locations[0]);
+            }
+        }
+
+        internal static NamedTypeSymbol GetEnclosingVariantInterface(Symbol member)
+        {
+            var container = member.ContainingType;
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Symbols/VarianceSafety.cs]: >var [](start = 12, length = 3)

Consider writing
`for (var container = member.ContainingType; container is object; container = container.ContainingType)`

File: src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs [hunk 9]
```diff
@@ -58605,5 +58605,640 @@ class C3 : C1
...
+                                                     parseOptions: TestOptions.Regular,
+                                                     targetFramework: TargetFramework.NetStandardLatest);
+
+                CompileAndVerify(compilation2, verify: VerifyOnMonoOrCoreClr, expectedOutput: !ExecutionConditionUtil.IsMonoOrCoreClr ? null :
+@"M1
+M2");
+            }
+        }
     }
 }
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs]: It might be helpful to add a test that demonstrates that variance safety is enforced on private methods in an interface.
