### PR TITLE
Do not export IDE0079 (remove unnecessary suppressions) analyzer in C…

### LINKED ISSUE #47942: IDE0079 (remove unnecessary suppressions) does not work when EnforceCodeStyleInBuild is enabled
**Version Used**: VS2019 16.8 P3

**Steps to Reproduce**:

1. Create a net5.0 class library project
```csharp
#pragma warning disable UnknownId1 // IDE0079

[System.Diagnostics.CodeAnalysis.SuppressMessage("Category", "UnknownId2")]  // IDE0079
public class C { }
```
2. Verify the pragma and suppress message attribute gets faded with IDE0079
3. Either install the CodeStyle NuGet package from [here](https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet-tools&view=overview&package=Microsoft.CodeAnalysis.CSharp.CodeStyle&version=3.8.0-3.20460.2&protocolType=NuGet) or set [EnforceCodeStyleInBuild](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#enforcecodestyleinbuild) to `true`

**Expected Behavior**:
IDE0079 is reported

**Actual Behavior**:
IDE0079 is not reported

This is a special IDE-only analyzer that should not be exported in the CodeStyle NuGet package. We still want to retain the code in the shared analyzer layer to allow different analyzer hosts to be able to explicitly instantiate it and enforce it on command line.

### PR DESCRIPTION
**Pull request by mavasani**
…odeStyle layer

Fixes #47942
This is a special IDE-only analyzer that should not be exported in the CodeStyle NuGet package. We still want to retain the code in the shared analyzer layer to allow different analyzer hosts to be able to explicitly instantiate it and enforce it on command line from the CodeStyle package.

### CODE REVIEW

**Comment by mavasani** [comment]
@jmarolf Will the CodeStyle assemblies from master eventually flow into .NET5 SDK? This is a fix to the CodeStyle package itself.

File: src/Analyzers/VisualBasic/Analyzers/RemoveUnnecessarySuppressions/VisualBasicRemoveUnnecessaryPragmaSuppressionsDiagnosticAnalyzer.vb [hunk 1]
```diff
@@ -10,7 +10,9 @@ Imports Microsoft.CodeAnalysis.VisualBasic.LanguageServices
 
 Namespace Microsoft.CodeAnalysis.VisualBasic.RemoveUnnecessarySuppressions
 
+#If Not CODE_STYLE Then ' Not exported in CodeStyle layer: https://github.com/dotnet/roslyn/issues/47942
     <DiagnosticAnalyzer(LanguageNames.VisualBasic)>
+#End If
```
Comment (Youssef1313) [inline src/Analyzers/VisualBasic/Analyzers/RemoveUnnecessarySuppressions/VisualBasicRemoveUnnecessaryPragmaSuppressionsDiagnosticAnalyzer.vb:15]: I don't see a reason why this generates a compile error. Does this need to file a compiler issue?

This might be a workaround that I hope to work.

```suggestion
#If Not CODE_STYLE Then ' Not exported in CodeStyle layer: https://github.com/dotnet/roslyn/issues/47942
    <DiagnosticAnalyzer(LanguageNames.VisualBasic)>
    Friend NotInheritable Class VisualBasicRemoveUnnecessaryInlineSuppressionsDiagnosticAnalyzer
#Else
    Friend NotInheritable Class VisualBasicRemoveUnnecessaryInlineSuppressionsDiagnosticAnalyzer
#End If
```

Comment (mavasani) [reply src/Analyzers/VisualBasic/Analyzers/RemoveUnnecessarySuppressions/VisualBasicRemoveUnnecessaryPragmaSuppressionsDiagnosticAnalyzer.vb]: Thanks. Not sure about if the VB compiler error is by design on not..

File: src/Analyzers/VisualBasic/Analyzers/RemoveUnnecessarySuppressions/VisualBasicRemoveUnnecessaryPragmaSuppressionsDiagnosticAnalyzer.vb [hunk 2]
```diff
@@ -10,7 +10,12 @@ Imports Microsoft.CodeAnalysis.VisualBasic.LanguageServices
 
 Namespace Microsoft.CodeAnalysis.VisualBasic.RemoveUnnecessarySuppressions
 
+#If Not CODE_STYLE Then ' Not exported in CodeStyle layer: https://github.com/dotnet/roslyn/issues/47942
     <DiagnosticAnalyzer(LanguageNames.VisualBasic)>
+    Friend NotInheritable Class VisualBasicRemoveUnnecessaryInlineSuppressionsDiagnosticAnalyzer
+#Else
+    Friend NotInheritable Class VisualBasicRemoveUnnecessaryInlineSuppressionsDiagnosticAnalyzer
+#End If
     Friend NotInheritable Class VisualBasicRemoveUnnecessaryInlineSuppressionsDiagnosticAnalyzer
```
Comment (Youssef1313) [inline src/Analyzers/VisualBasic/Analyzers/RemoveUnnecessarySuppressions/VisualBasicRemoveUnnecessaryPragmaSuppressionsDiagnosticAnalyzer.vb:19]: My previous suggestion should have removed this line as the declaration exists in both If and Else.

```suggestion
```

**Comment by jmarolf** [comment]
@mavasani I can update the sdk to include this change. Does this need to do into VS 16.8? If so I believe it will need to target a different branch

**Comment by mavasani** [comment]
@jmarolf I thought master is still targeting 16.8 P4. @vatsalyaagrawal @jinujoseph to confirm.

**Comment by jmarolf** [comment]
@mavasani see the mail @dibarbet sent. I believe this must target `release/dev16.8`

**Review by jmarolf — APPROVED** [review]

**Comment by mavasani** [comment]
Thanks @jmarolf!
