### PR TITLE
Ignore bit flag AssemblyFlags.PublicKey for assembly definitions

### LINKED ISSUE #399: Roslyn does not recognize a strongly named assembly
Repro steps:
* Open the attached solution [StrongNameTest.sln](http://tinyurl.com/qfu3zsu) in Visual Studio (with Roslyn installed)
* Try to build.

__ACTUAL:__
error CS8002: Referenced assembly 'Signed, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

__EXPECTED:__
No errors, build succeeds.

This solution builds successfully with native C# compiler.
The referenced assembly has a strong name as could be checked by sn.exe:
```
StrongNameTest>sn -vf Signed.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.33440
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'Signed.dll' is valid

StrongNameTest>sn -q -Tp Signed.dll
Public key (hash algorithm: sha1):
0024000004800000940000000602000000240000525341310004000001000100ddbb397625d47d
8a90acf6e8d5abd57ec93fe21b735960ff5cc57e8606cdc2669ca8b24aaf64e02c30b926d6660a
b877ab61a9b510998fc1d060524da1c8d0058369c1193f4ced751769e6a699a9ae7750d589d305
0563eb1458edee3a53dba06fa5b46e3e97793fac6b90a96155f86c03804a6835cc9cb82cd04941
45b318a4

Public key token is 306f32af5e021d46
```
Also, it could be successfully installed into GAC:
```
StrongNameTest>gacutil /nologo /i Signed.dll
Assembly successfully added to the cache

StrongNameTest>gacutil /nologo /l Signed
The Global Assembly Cache contains the following assemblies:
  Signed, Version=1.0.0.0, Culture=neutral, PublicKeyToken=306f32af5e021d46, processorArchitecture=MSIL
```

### PR DESCRIPTION
**Pull request by VladimirReshetnikov**
Fix #399

### CODE REVIEW

File: src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/PseudoVariableTests.cs [hunk 1]
```diff
@@ -1050,8 +1050,8 @@ static void M()
...
-                    Add("1", "A`1[[B`1[[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], 397300B0-B, Version=1.2.2.2, Culture=neutral, PublicKeyToken=null]], 397300B0-A, Version=2.1.2.1, Culture=neutral, PublicKeyToken=null").
-                    Add("2", "B`1[[A`1[[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]][], 397300B0-A, Version=2.1.2.1, Culture=neutral, PublicKeyToken=null]], 397300B0-B, Version=1.2.2.2, Culture=neutral, PublicKeyToken=null"),
+                    Add("1", "A`1[[B`1[[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], 397300B0-B, Version=1.2.2.2, Culture=neutral, PublicKeyToken=null]], 397300B0-A, Version=2.1.2.1, Culture=neutral, PublicKeyToken=1f8a32457d187bf3").
+                    Add("2", "B`1[[A`1[[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]][], 397300B0-A, Version=2.1.2.1, Culture=neutral, PublicKeyToken=1f8a32457d187bf3]], 397300B0-B, Version=1.2.2.2, Culture=neutral, PublicKeyToken=null"),
```
Comment (VladimirReshetnikov) [inline src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/PseudoVariableTests.cs]: I believe these tests in C# and VB (below) had to provide incorrect PublicKeyToken because of the bug #399 that is fixed by this pull request, so I updated them.

**Comment by VladimirReshetnikov** [comment]
@tmat @cston @amcasey @VSadov @AlekseyTs @gafter Please review.

File: src/Compilers/Core/Portable/MetadataReader/PEModule.cs [hunk 2]
```diff
@@ -474,33 +474,42 @@ internal AssemblyIdentity ReadAssemblyIdentityOrThrow()
...
+            string cultureName = culture.IsNil ? null : reader.GetString(culture);
             if (cultureName != null && !MetadataHelpers.IsValidMetadataIdentifier(cultureName))
             {
                 throw new BadImageFormatException(string.Format(CodeAnalysisResources.InvalidCultureName, cultureName));
             }
 
-            var hasPublicKey = (flags & AssemblyFlags.PublicKey) != 0;
-            var publicKeyOrToken = !publicKey.IsNil ? reader.GetBlobBytes(publicKey).AsImmutableOrNull() : default(ImmutableArray<byte>);
-            if (hasPublicKey)
+            ImmutableArray<byte> publicKeyOrToken = reader.GetBlobContent(publicKey);
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: Consider adding a comment why do we need to ignore the PublicKey flag here.

Comment (AlekseyTs) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: I see that you added comment that we ignore the flag below, but didn't provide any explanation as to why

File: src/Compilers/Core/Portable/MetadataReader/PEModule.cs [hunk 3]
```diff
@@ -474,33 +474,42 @@ internal AssemblyIdentity ReadAssemblyIdentityOrThrow()
...
             else
             {
-                // Assembly definitions do not contain public key tokens, but they may contain public key
-                // data without being marked as strong name signed (e.g. delay-signed assemblies).
-                publicKeyOrToken = default(ImmutableArray<byte>);
+                // Assembly definition, the flag AssemblyFlags.PublicKey is ignored 
+                hasPublicKey = !publicKeyOrToken.IsEmpty;
+                if (hasPublicKey && !MetadataHelpers.IsValidPublicKey(publicKeyOrToken))
+                {
+                    throw new BadImageFormatException(CodeAnalysisResources.InvalidPublicKey);
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: The validity check is duplicated now. Consider moving it out of the 'if (isReference)' statement. Perhaps the original 'if (hasPublicKey) ...' statement wouldn't need to change that much then.

File: src/Compilers/Core/Portable/MetadataReader/PEModule.cs [hunk 4]
```diff
@@ -474,33 +474,42 @@ internal AssemblyIdentity ReadAssemblyIdentityOrThrow()
...
+                    {
+                        throw new BadImageFormatException(CodeAnalysisResources.InvalidPublicKeyToken);
+                    }
                 }
             }
             else
             {
-                // Assembly definitions do not contain public key tokens, but they may contain public key
-                // data without being marked as strong name signed (e.g. delay-signed assemblies).
-                publicKeyOrToken = default(ImmutableArray<byte>);
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: Do we ever return publicKeyOrToken == default(ImmutableArray<byte>) now? Under what circumstances?

File: src/Compilers/Core/Portable/MetadataReader/PEModule.cs (hunk 2 above)
Comment (VladimirReshetnikov) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: @AlekseyTs OK, I will try to find a quote from Ecma.

File: src/Compilers/Core/Portable/MetadataReader/PEModule.cs (hunk 4 above)
Comment (VladimirReshetnikov) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: @AlekseyTs No, but we can return an empty array. `reader.GetBlobContent(publicKey)` returns an empty array if `publicKey.IsNil` is `true`. @tmat recommended to invoke `GetBlobContent` and let it handle the nil case.
An empty array can be returned for assembly reference without `AssemblyFlags.PublicKey` flag and a nil `publicKey`, and also for assembly definitions with a nil `publicKey` (`AssemblyFlags.PublicKey` is ignored for them because they cannot contain a public key token, and this corresponds to the native compiler behavior and other tools like `sn.exe`)

File: src/Compilers/Core/Portable/MetadataReader/PEModule.cs (hunk 3 above)
Comment (VladimirReshetnikov) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: @AlekseyTs The exception is thrown under different conditions for assembly references and assembly definitions.

File: src/Compilers/Core/Portable/MetadataReader/PEModule.cs (hunk 4 above)
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: Are there any consumers that specifically check for default(ImmutableArray) or !default(ImmutableArray) in the result?

Comment (VladimirReshetnikov) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: @AlekseyTs I'm not aware of any. Tests also did not identify anything. I can change the code to return the default array instead of an empty one if you insist.

Comment (AlekseyTs) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: RE: I'm not aware of any
Could you check in code?

**Comment by VSadov** [comment]
LGTM.

**Comment by VladimirReshetnikov** [comment]
@AlekseyTs Please review updated changes.

**Comment by AlekseyTs** [comment]
LGTM
