### PR TITLE
Use the binder that owns local function scope for name conflict errors

### LINKED ISSUE #13029: Unexpected errors are reported for local functions declared within a switch statement.
```
        [Fact]
        public void ScopeOfLocalFunction()
        {
            var source =
@"
public class X
{
    public static void Main()
    {
    }

    bool Dummy(params object[] x) { return true; }

    void Test14(int val)
    {
        switch (val)
        {
            case 1 when TakeOutParam(true, out var x14):
                void x14() {return;};
                break;
            case 2:
                x14();
                break;
        }

        switch (val)
        {
            case 1 when Dummy(1 is var x14):
                void x14() {return;};
                break;
            case 2:
                x14();
                break;
        }
    }

    static bool TakeOutParam<T>(T y, out T x) 
    {
        x = y;
        return true;
    }
}
";
            var compilation = CreateCompilationWithMscorlib45(source, options: TestOptions.DebugExe, parseOptions: TestOptions.Regular);

            compilation.VerifyDiagnostics(
                // (14,52): error CS0136: A local or parameter named 'x14' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
                //             case 1 when TakeOutParam(true, out var x14):
                Diagnostic(ErrorCode.ERR_LocalIllegallyOverrides, "x14").WithArguments("x14").WithLocation(14, 52),
                // (24,40): error CS0136: A local or parameter named 'x14' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
                //             case 1 when Dummy(1 is var x14):
                Diagnostic(ErrorCode.ERR_LocalIllegallyOverrides, "x14").WithArguments("x14").WithLocation(24, 40)
                );
        }
```

Unexpected errors reported:

```
                // (15,22): error CS0136: A local or parameter named 'x14' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
                //                 void x14() {return;};
                Diagnostic(ErrorCode.ERR_LocalIllegallyOverrides, "x14").WithArguments("x14").WithLocation(15, 22),
                // (25,22): error CS0136: A local or parameter named 'x14' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
                //                 void x14() {return;};
                Diagnostic(ErrorCode.ERR_LocalIllegallyOverrides, "x14").WithArguments("x14").WithLocation(25, 22),
                // (18,17): error CS0165: Use of unassigned local variable 'x14'
                //                 x14();
                Diagnostic(ErrorCode.ERR_UseDefViolation, "x14()").WithArguments("x14").WithLocation(18, 17),
                // (28,17): error CS0165: Use of unassigned local variable 'x14'
                //                 x14();
                Diagnostic(ErrorCode.ERR_UseDefViolation, "x14()").WithArguments("x14").WithLocation(28, 17)
```

### PR DESCRIPTION
**Pull request by agocke**
I believe the definite assignment errors were fixed by changing the design of local functions
to allow forward calls to local functions in scope.

This should fix the extra errors around name conflicts.

Fixes #13029

### CODE REVIEW

**Comment by agocke** [comment]
\+ @AlekseyTs @gafter @dotnet/roslyn-compiler 

Also, @AlekseyTs I assume your comment in the linked bug referred to the use-def errors being unexpected, not the names-conflicting-in-scope errors (which seem correct to me).

**Comment by agocke** [comment]
test windows_debug_unit32_prtest please

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests_Scope.cs [hunk 1]
```diff
@@ -16,6 +16,67 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+                // (15,22): error CS0136: A local or parameter named 'x14' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
+                //                 void x14() {return;};
+                Diagnostic(ErrorCode.ERR_LocalIllegallyOverrides, "x14").WithArguments("x14").WithLocation(15, 22),
+                // (24,40): error CS0136: A local or parameter named 'x14' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
+                //             case 1 when Dummy(1 is var x14):
+                Diagnostic(ErrorCode.ERR_LocalIllegallyOverrides, "x14").WithArguments("x14").WithLocation(24, 40),
+                // (25,22): error CS0136: A local or parameter named 'x14' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
+                //                 void x14() {return;};
+                Diagnostic(ErrorCode.ERR_LocalIllegallyOverrides, "x14").WithArguments("x14").WithLocation(25, 22));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests_Scope.cs]: >Diagnostic(ErrorCode.ERR_LocalIllegallyOverrides, "x14").WithArguments("x14").WithLocation(25, 22)); [](start = 16, length = 100)

I believe this error is unexpected.

**Comment by agocke** [comment]
@AlekseyTs Explained to me offline why the error is unexpected -- I agree. I'm going to close this PR and reopen when I have a proper fix.

**Comment by AlekseyTs** [comment]
@agocke Is this PR ready for review?

**Comment by agocke** [comment]
@AlekseyTs I was going to wait for test results before requesting review, but yes.

**Comment by agocke** [comment]
@dotnet/roslyn-compiler This should be ready for re-review. The changes for scoping are in the second commit.

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 2]
```diff
@@ -448,29 +448,11 @@ private BoundStatement BindGoto(GotoStatementSyntax node, DiagnosticBag diagnost
 
         private BoundStatement BindLocalFunctionStatement(LocalFunctionStatementSyntax node, DiagnosticBag diagnostics)
         {
-            var binder = GetBinder(node);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: >var binder = GetBinder(node); [](start = 12, length = 29)

If we no longer need to locate the binder, we should probably change LocalBinderFactory to no longer add one into the map.

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 3]
```diff
@@ -448,29 +448,11 @@ private BoundStatement BindGoto(GotoStatementSyntax node, DiagnosticBag diagnost
...
-            // This occurs through the semantic model.  In that case concoct a plausible result.
-            if (localSymbol == null)
-            {
-                localSymbol = new LocalFunctionSymbol(this, this.ContainingMemberOrLambda, node);
-            }
-            else
-            {
-                hasErrors |= this.ValidateDeclarationNameConflictsInScope(localSymbol, diagnostics);
-            }
+            var binder = localSymbol.ScopeBinder;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: >var binder = localSymbol.ScopeBinder [](start = 12, length = 36)

Consider renaming to scopeBinder or inlining the local so that no one would try to use this binder for binding something.

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 4]
```diff
@@ -30,6 +30,45 @@ internal void VerifyDiagnostics(string source, CSharpCompilationOptions options,
...
+    {
+        {
+            int T = 0; // Should not have error
+
+            int Local<T>() => 0; // Should conflict with above
+            Local<int>();
+            T++;
+        }
+        {
+            int T<T>() => 0;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: >int T<T>() => 0 [](start = 12, length = 15)

It would be good to have a test when type parameter ```T``` conflicts with is a type parameter of a containing method/local function.

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 5]
```diff
@@ -30,6 +30,45 @@ internal void VerifyDiagnostics(string source, CSharpCompilationOptions options,
...
+        {
+            var src = @"
+class C
+{
+    public void M()
+    {
+        {
+            int T = 0; // Should not have error
+
+            int Local<T>() => 0; // Should conflict with above
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: >Local [](start = 16, length = 5)

It would be good to have a test when the name of the local function conflict with the name of containing function/local function, or with its type parameter.

**Comment by AlekseyTs** [comment]
>                 Binder addToMap;

Consider renaming.

---
Refers to: src/Compilers/CSharp/Portable/Binder/LocalBinderFactory.cs:226 in bb98996. [](commit_id = bb98996c5cee1a03517e8b0f4c9092bc425fe2c9, deletion_comment = False)

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 6]
```diff
@@ -30,6 +30,84 @@ internal void VerifyDiagnostics(string source, CSharpCompilationOptions options,
...
+                // (9,23): error CS0136: A local or parameter named 'T' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
+                //             int Local<T>() => 0; // Should conflict with above
+                Diagnostic(ErrorCode.ERR_LocalIllegallyOverrides, "T").WithArguments("T").WithLocation(9, 23),
+                // (14,19): error CS0136: A local or parameter named 'T' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
+                //             int T<T>() => 0;
+                Diagnostic(ErrorCode.ERR_LocalIllegallyOverrides, "T").WithArguments("T").WithLocation(14, 19),
+                // (18,26): error CS0692: Duplicate type parameter 'T'
+                //             int Local<T, T>() => 0;
+                Diagnostic(ErrorCode.ERR_DuplicateTypeParameter, "T").WithArguments("T").WithLocation(18, 26),
+                // (25,23): warning CS0693: Type parameter 'T' has the same name as the type parameter from outer type 'C.M2<T>()'
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: >from outer type [](start = 103, length = 15)

This doesn't look accurate.

**Comment by AlekseyTs** [comment]
LGTM

**Comment by agocke** [comment]
ping @dotnet/roslyn-compiler For one more review

**Comment by rsikchi** [comment]
Hi Andy Gocke,

I had a question regarding the SourceGenerators - https://github.com/dotnet/roslyn/blob/12bd769ebcd3121b88f535e8559f5a42d9c0e873/docs/features/generators.md 

One of the instructions is - 
_"Like all pre-release features, code generators will need to be specially enabled, either by passing  /features:replace  directly to  csc  or by setting the  <Features>replace</Features>  flag in the project file."_

Can you tell me where to set the replace flag in project file?

Thanks in advance.

**Comment by agocke** [comment]
@rsikchi I believe there's a Features MSBuild property, so you would put the following in your csproj:

```
<Features>replace</Features>
```

But I haven't tested this since source generators got moved to their new branch.

**Comment by agocke** [comment]
@dotnet/roslyn-compiler Ping for review

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 7]
```diff
@@ -448,29 +448,11 @@ private BoundStatement BindGoto(GotoStatementSyntax node, DiagnosticBag diagnost
...
-            if (localSymbol == null)
-            {
-                localSymbol = new LocalFunctionSymbol(this, this.ContainingMemberOrLambda, node);
-            }
-            else
-            {
-                hasErrors |= this.ValidateDeclarationNameConflictsInScope(localSymbol, diagnostics);
-            }
+            var hasErrors = localSymbol.ScopeBinder
+                .ValidateDeclarationNameConflictsInScope(localSymbol, diagnostics);
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: Need to get you a bigger monitor.  Reading this code is like visiting our Team room.

Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: @gafter I can imagine my next budget request

> Please give my reports new monitors because I can't stand reviewing the code they right on tiny ones

😉

Comment (agocke) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: @gafter @jaredpar 

Actually, I write code using this: https://pbs.twimg.com/media/CvyuS5nWAAAqkgP.jpg

https://pbs.twimg.com/media/CvyuS5pWEAA79ml.jpg

**Comment by rsikchi** [comment]
@agocke  
_" I believe there's a Features MSBuild property, so you would put the following in your csproj:
<Features>replace</Features>


But I haven't tested this since source generators got moved to their new branch.
"_

Do you know anyone who might have tested this since sourcegenerator got moved to the new branch?

**Comment by agocke** [comment]
@rsikchi probably no one, since the feature is moved to C# 8 and not under active development.
