### PR TITLE
Make invalid call IInvalidExpression

### LINKED ISSUE #18722: Add `IInvalidInvocationExpression` interafce
Currently in C#, an invalid invocation is represented by an `IInvocationExpression` operation, but it might violate the contract of `IInvocationExpression`. For example, we can't provide a list of arguments in evaluation order correctly if we have extra arguments that don't match any parameter, or multiple arguments are matching to a single parameter, etc. On the other hand, making an invalid invocation an `IInvalidExpression` would solve the problem but it would be unnecessarily lossy since in many cases compiler does have more details that users might find useful to do further analysis.

The goal would be to expose as much information of a invalid invocation as possible at best effort, without violating the API contract of `IInvocationExpression`, hence the new `IInvalidInvocationExpression` interface.

Here's the notes from our discussion:
- Will be a sibling of `IInvocationExpression` (child of `IHasArgumentExpression`)
- Should contain candidate symbols and candidate reason.
- Has a list `ArgumentValues` of type `IOperation` that were passed to the invocation.
- And a receiver of type` IOperatoin`
- We would also like an api/extension `TryGetParameterForArgumentValue`, indicating it's best effort and may fail

@dotnet/analyzer-ioperation

### PR DESCRIPTION
**Pull request by genlu**
Fix #18722
vso : https://devdiv.visualstudio.com/DevDiv/_workitems/edit/510460

### CODE REVIEW

**Comment by genlu** [comment]
@AlekseyTs Could you take a look at this please?

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs [hunk 1]
```diff
@@ -445,12 +455,35 @@ private IPropertyReferenceExpression CreateBoundAnonymousPropertyDeclarationOper
...
+            {
+                return CreateInvalidExpressionForHasArgumentsExpression(null, boundObjectCreationExpression.Arguments, boundObjectCreationExpression.InitializerExpressionOpt, syntax, type, constantValue, isImplicit);
+            }
+
             Lazy<IObjectOrCollectionInitializerExpression> initializer = new Lazy<IObjectOrCollectionInitializerExpression>(() => (IObjectOrCollectionInitializerExpression)Create(boundObjectCreationExpression.InitializerExpressionOpt));
             Lazy<ImmutableArray<IArgument>> argumentsInEvaluationOrder = new Lazy<ImmutableArray<IArgument>>(() =>
             {
+                if (boundObjectCreationExpression.BinderOpt == null)
+                {
+                    // binder can only be null for a generated non-null default value of a nullable type parameter,
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: >binder can only be null for a generated non-null default value of a nullable type parameter [](start = 23, length = 91)

Where do we create this node? I think we should make sure it has the binder rather than making an assumption based on the fact that it is missing.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: I would like to get a better understanding of this scenario, let's talk offline you have time.

---
In reply to: [144118135](https://github.com/dotnet/roslyn/pull/22651#discussion_r144118135) [](ancestors = 144118135)

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs [hunk 2]
```diff
@@ -445,12 +455,35 @@ private IPropertyReferenceExpression CreateBoundAnonymousPropertyDeclarationOper
...
+        private IOperation CreateBoundObjectCreationExpressionOperation(BoundObjectCreationExpression boundObjectCreationExpression)
         {
-            IMethodSymbol constructor = boundObjectCreationExpression.Constructor;
+            MethodSymbol constructor = boundObjectCreationExpression.Constructor;
+            SyntaxNode syntax = boundObjectCreationExpression.Syntax;
+            ITypeSymbol type = boundObjectCreationExpression.Type;
+            Optional<object> constantValue = ConvertToOptional(boundObjectCreationExpression.ConstantValue);
+            bool isImplicit = boundObjectCreationExpression.WasCompilerGenerated;
+            
+            if (constructor == null)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: >constructor == null [](start = 16, length = 19)

Should we check LookupResultKind?

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs [hunk 3]
```diff
@@ -280,14 +280,25 @@ private IPlaceholderExpression CreateBoundDeconstructValuePlaceholderOperation(B
...
+        private IOperation CreateBoundCallOperation(BoundCall boundCall)
         {
-            IMethodSymbol targetMethod = boundCall.Method;
+            MethodSymbol targetMethod = boundCall.Method;
+            SyntaxNode syntax = boundCall.Syntax;
+            ITypeSymbol type = boundCall.Type;
+            Optional<object> constantValue = ConvertToOptional(boundCall.ConstantValue);
+            bool isImplicit = boundCall.WasCompilerGenerated;
+            
+            if (!boundCall.OriginalMethodsOpt.IsDefault || boundCall.ResultKind == LookupResultKind.OverloadResolutionFailure || targetMethod == null || targetMethod.OriginalDefinition is ErrorMethodSymbol)
```
Comment (genlu) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: @AlekseyTs I can't figure out how to hit the `targetMethod == null || targetMethod.OriginalDefinition is ErrorMethodSymbol` part of the condition.

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs [hunk 4]
```diff
@@ -348,35 +355,38 @@ private IPropertyReferenceExpression CreateBoundPropertyAccessOperation(BoundPro
...
+            SyntaxNode syntax = boundIndexerAccess.Syntax;
+            ITypeSymbol type = boundIndexerAccess.Type;
+            Optional<object> constantValue = ConvertToOptional(boundIndexerAccess.ConstantValue);
+            bool isImplicit = boundIndexerAccess.WasCompilerGenerated;
+
+            MethodSymbol accessor = boundIndexerAccess.UseSetterForDefaultArgumentGeneration
+                ? property.GetOwnOrInheritedSetMethod()
+                : property.GetOwnOrInheritedGetMethod();
+            
+            if (!boundIndexerAccess.OriginalIndexersOpt.IsDefault || boundIndexerAccess.ResultKind == LookupResultKind.OverloadResolutionFailure || accessor == null || accessor.OriginalDefinition is ErrorMethodSymbol)
```
Comment (genlu) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: @AlekseyTs Can't figure out if `accessor.OriginalDefinition is ErrorMethodSymbol` is necessary. Leave it there just to be safe.

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs [hunk 5]
```diff
@@ -573,14 +584,27 @@ private IMemberReferenceExpression CreateBoundObjectInitializerMemberOperation(B
                     }
                     else
                     {
+                        var accessor = property.GetOwnOrInheritedSetMethod();
+                        if (accessor == null || boundObjectInitializerMember.ResultKind == LookupResultKind.OverloadResolutionFailure || accessor.OriginalDefinition is ErrorMethodSymbol)
```
Comment (genlu) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: @AlekseyTs Same here.

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs [hunk 6]
```diff
@@ -573,14 +584,27 @@ private IMemberReferenceExpression CreateBoundObjectInitializerMemberOperation(B
...
+                        {
+                            Lazy<ImmutableArray<IOperation>> children = new Lazy<ImmutableArray<IOperation>>(
+                                 () =>
+                                 {
+                                     var builder = ArrayBuilder<IOperation>.GetInstance(boundObjectInitializerMember.Arguments.Length + 1);
+                                     builder.Add(CreateInstanceReferenceExpression());
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: >builder.Add(CreateInstanceReferenceExpression()); [](start = 37, length = 49)

I don't think this node adds any value, it doesn't reflect anything present in syntax.

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs [hunk 7]
```diff
@@ -595,6 +619,16 @@ private IMemberReferenceExpression CreateBoundObjectInitializerMemberOperation(B
...
             }
+
+            IOperation CreateInstanceReferenceExpression()
+            {
+                return new InstanceReferenceExpression(
+                    semanticModel: _semanticModel,
+                    syntax: boundObjectInitializerMember.Syntax,
+                    type: boundObjectInitializerMember.ReceiverType,
+                    constantValue: default(Optional<object>),
+                    isImplicit: boundObjectInitializerMember.WasCompilerGenerated);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: >boundObjectInitializerMember.WasCompilerGenerated [](start = 32, length = 49)

It feels like this node should be always implicit, it doesn't represent anything from source code.

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests.cs [hunk 8]
```diff
@@ -59,21 +59,14 @@ static void Test2(int y, params int[] x)
...
-            null
-        InConversion: CommonConversion (Exists: True, IsIdentity: True, IsNumeric: False, IsReference: False, IsUserDefined: False) (MethodSymbol: null)
-        OutConversion: CommonConversion (Exists: True, IsIdentity: True, IsNumeric: False, IsReference: False, IsUserDefined: False) (MethodSymbol: null)
-      IArgument (ArgumentKind.Explicit, Matching Parameter: null) (OperationKind.Argument) (Syntax: 'null')
-        ILiteralExpression (OperationKind.LiteralExpression, Type: null, Constant: null) (Syntax: 'null')
-        InConversion: CommonConversion (Exists: True, IsIdentity: True, IsNumeric: False, IsReference: False, IsUserDefined: False) (MethodSymbol: null)
-        OutConversion: CommonConversion (Exists: True, IsIdentity: True, IsNumeric: False, IsReference: False, IsUserDefined: False) (MethodSymbol: null)");
+@"IInvalidExpression (OperationKind.InvalidExpression, Type: System.Void, IsInvalid) (Syntax: 'Test2(new o ... ct(), null)')
+  Children(3):
+      IInstanceReferenceExpression (OperationKind.InstanceReferenceExpression, Type: Cls, IsImplicit) (Syntax: 'Test2')
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests.cs]: >IInstanceReferenceExpression (OperationKind.InstanceReferenceExpression, Type: Cls, IsImplicit) (Syntax: 'Test2') [](start = 6, length = 113)

It doesn't look like there is a value in including implicit IInstanceReferenceExpression nodes into the tree.

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IArgument.cs [hunk 9]
```diff
@@ -34,7 +35,7 @@ static void M1()
 ";
             var expectedDiagnostics = DiagnosticDescription.None;
 
-            VerifyOperationTreeAndDiagnosticsForTest<InvocationExpressionSyntax>(source, expectedOperationTree, expectedDiagnostics);
+            VerifyOperationTreeAndDiagnosticsForTest<InvocationExpressionSyntax>(source, expectedOperationTree, expectedDiagnostics, useLatestFrameworkReferences:true);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IArgument.cs]: >, useLatestFrameworkReferences:true [](start = 131, length = 35)

Why is this change needed?

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IArgument.cs [hunk 10]
```diff
@@ -2892,6 +3315,405 @@ void M1(int i, int i2)
             VerifyOperationTreeAndDiagnosticsForTest<ArgumentSyntax>(source, expectedOperationTree, expectedDiagnostics);
         }
 
+        [CompilerTrait(CompilerFeature.IOperation)]
+        [Fact]
+        public void NonNullDefaultValueForNullableTypeParameter()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IArgument.cs]: >TypeParameter [](start = 50, length = 13)

Not sure why name refers to "TypeParameter". Is it about **p**arameter **t**ype?

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IArgument.cs [hunk 11]
```diff
@@ -2892,6 +3315,405 @@ void M1(int i, int i2)
...
+IObjectCreationExpression (Constructor: P..ctor()) (OperationKind.ObjectCreationExpression, Type: P, IsInvalid) (Syntax: 'new P() { [0] = 1 }')
+  Arguments(0)
+  Initializer: 
+    IObjectOrCollectionInitializerExpression (OperationKind.ObjectOrCollectionInitializerExpression, Type: P, IsInvalid) (Syntax: '{ [0] = 1 }')
+      Initializers(1):
+          ISimpleAssignmentExpression (OperationKind.SimpleAssignmentExpression, Type: System.Int32, IsInvalid) (Syntax: '[0] = 1')
+            Left: 
+              IInvalidExpression (OperationKind.InvalidExpression, Type: System.Int32, IsInvalid) (Syntax: '[0]')
+                Children(2):
+                    IInstanceReferenceExpression (OperationKind.InstanceReferenceExpression, Type: P, IsInvalid) (Syntax: '[0]')
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IArgument.cs]: >IInstanceReferenceExpression (OperationKind.InstanceReferenceExpression, Type: P, IsInvalid) (Syntax: '[0]') [](start = 20, length = 108)

This node doesn't look useful.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 3).

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs (hunk 7 above)
Comment (genlu) [reply src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: I agree. Fixed.

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs (hunk 6 above)
Comment (genlu) [reply src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: I have excluded all compiler generated receiver when creating invalid expression.

**Comment by genlu** [comment]
@cston @dotnet/analyzer-ioperation Could you please take a look at this as well? Thanks!

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs [hunk 12]
```diff
@@ -596,14 +613,26 @@ private IMemberReferenceExpression CreateBoundObjectInitializerMemberOperation(B
...
+                        var accessor = property.GetOwnOrInheritedSetMethod();
+                        if (accessor == null || boundObjectInitializerMember.ResultKind == LookupResultKind.OverloadResolutionFailure || accessor.OriginalDefinition is ErrorMethodSymbol)
+                        {
+                            Lazy<ImmutableArray<IOperation>> children = new Lazy<ImmutableArray<IOperation>>(
+                                 () =>
+                                 {
+                                     var builder = ArrayBuilder<IOperation>.GetInstance(boundObjectInitializerMember.Arguments.Length);
+                                     builder.AddRange(boundObjectInitializerMember.Arguments.Select(a => Create(a)));
+                                     return builder.ToImmutableAndFree();
+                                 });
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: `() => boundObjectInitializerMember.Arguments.SelectAsArray(a => Create(a))`

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs [hunk 13]
```diff
@@ -162,6 +146,30 @@ private IEventReferenceExpression CreateBoundEventAccessOperation(BoundEventAssi
...
         }
 
+        private IInvalidExpression CreateInvalidExpressionForHasArgumentsExpression(BoundNode ReceiverOpt, ImmutableArray<BoundExpression> arguments, BoundExpression AdditionalNodeOpt, SyntaxNode syntax, ITypeSymbol type, Optional<object> constantValue, bool isImplicit)
+        {
+            Lazy<ImmutableArray<IOperation>> children = new Lazy<ImmutableArray<IOperation>>(
+                      () =>
+                      {
+                          ArrayBuilder<IOperation> builder = ArrayBuilder<IOperation>.GetInstance();
+
+                          if (ReceiverOpt != null && !ReceiverOpt.WasCompilerGenerated)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs]: What is the scenario where the receiver is compiler generated but should be dropped?

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs [hunk 14]
```diff
@@ -162,6 +146,30 @@ private IEventReferenceExpression CreateBoundEventAccessOperation(BoundEventAssi
                  invokedAsExtensionMethod: invokedAsExtensionMethod);
         }
 
+        private IInvalidExpression CreateInvalidExpressionForHasArgumentsExpression(BoundNode ReceiverOpt, ImmutableArray<BoundExpression> arguments, BoundExpression AdditionalNodeOpt, SyntaxNode syntax, ITypeSymbol type, Optional<object> constantValue, bool isImplicit)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs]: Parameter names should begin with lowercase letter: `receiverOpt`, `additionalNodeOpt`.

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests.cs [hunk 15]
```diff
@@ -59,21 +59,13 @@ static void Test2(int y, params int[] x)
...
-        ILiteralExpression (OperationKind.LiteralExpression, Type: null, Constant: null) (Syntax: 'null')
-        InConversion: CommonConversion (Exists: True, IsIdentity: True, IsNumeric: False, IsReference: False, IsUserDefined: False) (MethodSymbol: null)
-        OutConversion: CommonConversion (Exists: True, IsIdentity: True, IsNumeric: False, IsReference: False, IsUserDefined: False) (MethodSymbol: null)");
+@"IInvalidExpression (OperationKind.InvalidExpression, Type: System.Void, IsInvalid) (Syntax: 'Test2(new o ... ct(), null)')
+  Children(2):
+      IObjectCreationExpression (Constructor: System.Object..ctor()) (OperationKind.ObjectCreationExpression, Type: System.Object, IsInvalid) (Syntax: 'new object()')
+        Arguments(0)
+        Initializer: 
+          null
+      ILiteralExpression (OperationKind.LiteralExpression, Type: null, Constant: null) (Syntax: 'null')");
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests.cs]: It looks like the `IInvalidExpression` has dropped the receiver and method. It seems like this invocation should be represented by an `IInvocationExpression`.

Can we use `IInvocationExpression` for all invocations, even those with argument errors or extra arguments? If the concern is the evaluation order of arguments, consider using the syntax order for extra arguments.

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs [hunk 16]
```diff
@@ -53,37 +53,12 @@ internal IArgument CreateArgumentOperation(ArgumentKind kind, IParameterSymbol p
...
-
-                initializer = OperationFactory.CreateVariableInitializer(initializerSyntax, initializerValue, _semanticModel, isImplicit);
-            }
-
-            return OperationFactory.CreateVariableDeclaration(boundLocalDeclaration.LocalSymbol, initializer, _semanticModel, syntax);
+            return OperationFactory.CreateVariableDeclaration(boundLocalDeclaration.LocalSymbol, Create(boundLocalDeclaration.InitializerOpt), _semanticModel, syntax);
         }
 
         private IVariableDeclaration CreateVariableDeclaration(BoundLocal boundLocal)
         {
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs]: >!ReceiverOpt.WasCompilerGenerated [](start = 53, length = 33)

The fact that receiver is compiler generated doesn't mean that all its descendants are. I think we should also check for specific nodes here: BoundThis, and what else is getting translated into IInstanceReferenceExpression.

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests.cs (hunk 15 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests.cs]: > Can we use IInvocationExpression for all invocations, even those with argument errors or extra arguments? If the concern is the evaluation order of arguments, consider using the syntax order for extra arguments.

For now we explicitly decided to not try to be too clever about cases when overload resolution failed.

---
In reply to: [144702308](https://github.com/dotnet/roslyn/pull/22651#discussion_r144702308) [](ancestors = 144702308)

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 6)

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs (hunk 13 above)
Comment (genlu) [reply src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs]: For example, in the code below:
```cs
class P
{
    void M1()
    {
        M2(1, 2);
    }

    void M2(int x = 0)
    { }
}
```
There would a compiler generated `BoundThis` for the invalid call `M2(1, 2)`.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 7). It looks like there are some legitimate test failures.

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs (hunk 13 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs]: Why drop the implicit `BoundThis`? The `this` receiver seems correct in that case.

Comment (genlu) [reply src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs]: I think the reason is we are creating an InvalidExpression instead of an InvocationExpression for example, which basically just a list of operation in user's code. In this case, including a compiler generated `this` can be confusing and not much user can do with it.

**Comment by genlu** [comment]
Fixed the tests. It was caused by merging.

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs [hunk 17]
```diff
@@ -294,14 +294,25 @@ private IDeconstructionAssignmentExpression CreateBoundDeconstructionAssignmentO
...
+            Optional<object> constantValue = ConvertToOptional(boundCall.ConstantValue);
+            bool isImplicit = boundCall.WasCompilerGenerated;
+            
+            if (!boundCall.OriginalMethodsOpt.IsDefault || boundCall.ResultKind == LookupResultKind.OverloadResolutionFailure || targetMethod == null || targetMethod.OriginalDefinition is ErrorMethodSymbol)
+            {
+                return CreateInvalidExpressionForHasArgumentsExpression(boundCall.ReceiverOpt, boundCall.Arguments, null, syntax, type, constantValue, isImplicit);
+            }
+
             Lazy<IOperation> instance = new Lazy<IOperation>(() => CreateBoundCallInstanceOperation(boundCall));
             bool isVirtual = (object)boundCall.Method != null &&
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: Can use `targetMethod` rather than `boundCall.Method`, here and below.

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs [hunk 18]
```diff
@@ -374,33 +381,37 @@ private IPropertyReferenceExpression CreateBoundPropertyAccessOperation(BoundPro
...
-                    boundIndexerAccess.Indexer.Parameters,
+                    property.Parameters,
                     boundIndexerAccess.Expanded,
-                    boundIndexerAccess.Syntax);
-            });
-            SyntaxNode syntax = boundIndexerAccess.Syntax;
-            ITypeSymbol type = boundIndexerAccess.Type;
-            Optional<object> constantValue = ConvertToOptional(boundIndexerAccess.ConstantValue);
-            bool isImplicit = boundIndexerAccess.WasCompilerGenerated;
+                    boundIndexerAccess.Syntax));
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: `syntax`

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs [hunk 19]
```diff
@@ -487,10 +508,6 @@ private IObjectCreationExpression CreateBoundObjectCreationExpressionOperation(B
                     boundObjectCreationExpression.Expanded,
                     boundObjectCreationExpression.Syntax);
             });
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: Can use `constructor` rather than `boundObjectCreationExpression.Constructor`. Can use `syntax` rather than `boundObjectCreationExpression.Syntax`.

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IArgument.cs [hunk 20]
```diff
@@ -2144,7 +2116,215 @@ public void M2()
...
+                // (9,30): error CS0518: Predefined type 'System.Boolean' is not defined or imported
+                //     static void M2(bool? x = true)
+                Diagnostic(ErrorCode.ERR_PredefinedTypeNotFound, "true").WithArguments("System.Boolean").WithLocation(9, 30),
+                // (6,19): error CS0518: Predefined type 'System.Object' is not defined or imported
+                //         /*<bind>*/M2()/*</bind>*/;
+                Diagnostic(ErrorCode.ERR_PredefinedTypeNotFound, "M2").WithArguments("System.Object").WithLocation(6, 19),
+                // (2,7): error CS1729: 'object' does not contain a constructor that takes 0 arguments
+                // class P
+                Diagnostic(ErrorCode.ERR_BadCtorArgCount, "P").WithArguments("object", "0").WithLocation(2, 7)
+            };
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IArgument.cs]: Consider including definitions of special types in the source to reduce the number of unnecessary errors.
```
namespace System
{
    public class Object { }
    public struct Void { }
    public class ValueType { }
    public struct Boolean { }
}
```

**Comment by genlu** [comment]
FYI @jinujoseph

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IArgument.cs (hunk 20 above)
Comment (genlu) [reply src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IArgument.cs]: I think it'd be more accurate if we don't define those types, i.e. is it possible to have those type but missing only Nullable?

**Comment by natidea** [comment]
Approved to merge via [510460](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/510460)

**Comment by natidea** [comment]
@genlu please merge this by morning if you want it in Preview 2
