### PR TITLE
Run iterator validation for all block binding

### LINKED ISSUE #13937: Missing CS1623 for local function inside expression-bodied method
A method written like this:

```cs
    int M() => new Func<int>(() => {
        // Iterators cannot have ref or out parameters
        IEnumerable<int> f(ref int a) { yield break; }; //3
        return 3;
    })();
```

fails to report

```none
error CS1623: Iterators cannot have ref or out parameters
```

The test for this issue should look something like

```cs
        [Fact]
        public void CS1623ERR_BadIteratorArgType_02()
        {
            var text = @"
using System;
using System.Collections.Generic;

class Program
{
    static void Main(string[] args)
    {
        // iterators cannot have ref or out parameters
        IEnumerable<int> f(ref int a) { yield break; }; //1
    }

    ~Program()
    {
        // iterators cannot have ref or out parameters
        IEnumerable<int> f(ref int a) { yield break; }; //2
    }

    int M() => new Func<int>(() => {
        // Iterators cannot have ref or out parameters
        IEnumerable<int> f(ref int a) { yield break; }; //3
        return 3;
    })();
}
";
            var comp = CreateCompilationWithMscorlib(text);
            comp.VerifyDiagnostics(
                // (10,36): error CS1623: Iterators cannot have ref or out parameters
                //         IEnumerable<int> f(ref int a) { yield break; }; //1
                Diagnostic(ErrorCode.ERR_BadIteratorArgType, "a").WithLocation(10, 36),
                // (16,36): error CS1623: Iterators cannot have ref or out parameters
                //         IEnumerable<int> f(ref int a) { yield break; }; //2
                Diagnostic(ErrorCode.ERR_BadIteratorArgType, "a").WithLocation(16, 36),
                // (21,36): error CS1623: Iterators cannot have ref or out parameters
                //         IEnumerable<int> f(ref int a) { yield break; }; //3
                Diagnostic(ErrorCode.ERR_BadIteratorArgType, "a").WithLocation(21, 36)
                );
        }
```

### PR DESCRIPTION
**Pull request by agocke**
Previously iterator validation was only run in MethodCompiler
for blocks which pass through that code path, resulting in missed
local functions inside lambda blocks, which don't pass through
BindMethodBody.

Fixes #13937

### CODE REVIEW

**Comment by agocke** [comment]
cc @MattGertz For ask-mode

**Comment by Pilchie** [comment]
Scenario meets the bar - approved pending testing and code review signoff.

**Comment by agocke** [comment]
test this please

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 1]
```diff
@@ -2305,6 +2309,39 @@ private BoundBlock BindBlock(BlockSyntax node, DiagnosticBag diagnostics)
...
+                    }
+                }
+
+                if (iterator.IsVararg)
+                {
+                    // error CS1636: __arglist is not allowed in the parameter list of iterators
+                    diagnostics.Add(ErrorCode.ERR_VarargsIterator, iterator.Locations[0]);
+                }
+
+                if (((iterator as SourceMethodSymbol)?.IsUnsafe == true || (iterator as LocalFunctionSymbol)?.IsUnsafe == true)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: Perhaps add an `IsUnsafeIterator()` extension method.

**Comment by cston** [comment]
LGTM

**Comment by agocke** [comment]
also cc @gafter

**Comment by agocke** [comment]
Ping @dotnet/roslyn-compiler

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 2]
```diff
@@ -2292,8 +2292,12 @@ protected virtual LocalFunctionSymbol LookupLocalFunction(SyntaxToken nameToken)
             return Next.LookupLocalFunction(nameToken);
         }
 
+        protected virtual ImmutableArray<MethodSymbol> MethodSymbolsWithYield =>
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: >MethodSymbolsWithYield [](start = 55, length = 22)

It looks like this property deserves a good doc comment. Also, we usually define APIs like this in Binder.cs.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: >MethodSymbolsWithYield [](start = 55, length = 22)

Usually, BackstopBinder overrides such APIs and throws.

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 3]
```diff
@@ -2305,6 +2309,39 @@ private BoundBlock BindBlock(BlockSyntax node, DiagnosticBag diagnostics)
...
+                }
+
+                if (iterator.IsVararg)
+                {
+                    // error CS1636: __arglist is not allowed in the parameter list of iterators
+                    diagnostics.Add(ErrorCode.ERR_VarargsIterator, iterator.Locations[0]);
+                }
+
+                if (((iterator as SourceMethodSymbol)?.IsUnsafe == true || (iterator as LocalFunctionSymbol)?.IsUnsafe == true)
+                    && compilation.Options.AllowUnsafe) // Don't cascade
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: >&& compilation.Options.AllowUnsafe) // Don't cascade [](start = 20, length = 52)

Is there a test for this logic?

**Comment by AlekseyTs** [comment]
LGTM

**Comment by agocke** [comment]
+ @gafter . The last commit contains the change I needed to make for expression bodied properties -- super simple.

**Comment by agocke** [comment]
@cston I've modified the PR to be more constrained, given ask mode. Would you like to take another look?

**Comment by cston** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceCustomEventAccessorSymbol.cs [hunk 4]
```diff
@@ -29,7 +29,7 @@ internal sealed class SourceCustomEventAccessorSymbol : SourceEventAccessorSymbo
             DiagnosticBag diagnostics)
             : base(@event,
                    syntax.GetReference(),
-                   syntax.Body?.GetReference(),
+                   syntax.Body?.GetReference() ?? syntax.ExpressionBody?.GetReference(),
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceCustomEventAccessorSymbol.cs]: Yes, there are a number of tests that hit that case -- in fact, due to the change in binding to just consider whether or not `bodySyntax` is non-null, this hits *every* test case that binds an expression bodied event.
