### PR TITLE
Fix analyzer loading to prefer host

### LINKED ISSUE #60763: Reenable AssemblyLoading_MultipleVersions_ExactAndGreaterMatch
Disabled in .net7 upgrade https://github.com/dotnet/roslyn/pull/60523

### LINKED ISSUE #66104: SourceGenerators in shared compilation can cause MissingMethodException
**Version Used**: 
Visual Studio v17.5p1
Roslyn in .NET 7.0.101 and in .NETFramework 4.7.2 (the one that ships with VS)

**Steps to Reproduce**:

```
> mkdir CTRepro
> cd CTRepro
> dotnet new console
> dotnet add package CommunityToolkit.Mvvm -v 8.1.0-preview2
> dotnet add package Microsoft.Windows.CsWin32 -v 0.2.164-beta
```
then add a new `.cs` file so the CommunityToolkit SourceGenerators will run

```csharp
using CommunityToolkit.Mvvm.Input;

namespace CTRepro;

internal partial class Model
{
    [RelayCommand]
    private void Execute() { }
}
```

Then you can either build in VS or use `msbuild -restore /t:Rebuild` to trigger the warning

```
CSC : warning CS8785: Generator 'RelayCommandGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'MissingMethodException' with message 'Method not found: 'System.ReadOnlySpan`1<!0> System.Collections.Immutable.ImmutableArray`1.AsSpan()'.' [C:\Users\hank.mccord\source\repos\CTRepro\CTRepro.csproj]
```

**Expected Behavior**:

The generated code should include the `ICommand` that is generated

**Actual Behavior**:

Because the source generator encountered an error, the associated IL is missing entirely.
If you build with `dotnet build`, it works as expected.

**Investigation/Cause**

A couple things collide to cause this:
* Using `msbuild` or Visual Studio uses the full framework MSBuild (i.e. no ALCs) under a shared compilation context
* CsWin32 is shipping `System.Memory` in their analyzers directory
* VBCSCompiler eventually loads `System.Memory` in the `LoadFrom` context (even though System.Memory is in the probing path)

I hope this enough information. Someone who is very familiar with assembly loading process should get the gist of what's going on.  
The .NET version of roslyn has the names of simple assemblies that will be provided in by the compiler but the .NETFramework has a completely different loading process since there are no ALCs.

Is this a concern to the Roslyn team or should the fix be CsWin32 package not shipping Roslyn provided dlls in their analyzer folder?

[Update(jcouv):] This issue is referenced by some skipped tests.

### PR DESCRIPTION
**Pull request by jaredpar**
This changes the design of our analyzer loading policy to give hosts more control over dependencies. Whenever possible analyzer dependencies will be unified with the compiler host environment where previously we only tried to unify dependencies owned directly by the compiler. This will be achieved by using standard assembly loading practices that give the host first shot at determining an `Assembly` to load for a given `AssemblyName`.

For a concrete example of this problem consider some analyzers deploy copies of `System.Memory.dll` in their analyzer folder. That means there are two copies of `System.Memory.dll` in play: the one the compiler deploys and the analyzer copy. The compiler prefers its copy because so exchange types unify to a single place.

This won't change the designed behavior for the command line compilers. In those scenarios the compiler is the host and the intent compiler dependencies to be unified (this PR does fix a bug in this area). It will make the implementation more rigorous though.

This will potentially change our behavior when loaded in hosts such as Visual Studio. That environment has a much larger set of DLLs that can be loaded into the primary load context. This is important though to ensure propery type / dll unification happens where as today it can result in duplicate types and assemblies.

This change also substantially updates our tests. Most of our tests were focused on the default loading strategy (load in place, no shadow copies). That is actually the least common loading strategy. The most common is shadow copy loading. As such I revamped our test suite such that the same set of tests run for all four of our main configurations:

- default + .NET Core
- default + .NET Framework
- shadow + .NET Core
- shadow + .NET Framework

The results are illuminating. There are more differences between these scenarios than most people, likely, suspect. Later changes may try and unify a few scenarios but for now wanted to mostly document the behavior so it's not accidentally changed.

closes #66104
closes #60763
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1692992

### CODE REVIEW

**Comment by jaredpar** [comment]
@dotnet/roslyn-compiler PTAL, @RikkiGibson

File: src/Compilers/Core/CodeAnalysisTest/ShadowCopyAnalyzerAssemblyLoaderTests.cs [hunk 1]
```diff
@@ -1,146 +0,0 @@
-﻿// Licensed to the .NET Foundation under one or more agreements.
```
Comment (jaredpar) [inline src/Compilers/Core/CodeAnalysisTest/ShadowCopyAnalyzerAssemblyLoaderTests.cs:1]: These tests were merged into `DefaultAnalyzerAssemblyLoaderTestsBase`. That way they run on the four major configurations that we care about.

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs [hunk 2]
```diff
@@ -37,54 +37,95 @@ public class AssemblyLoadTestFixtureCollection : ICollectionFixture<AssemblyLoad
...
-        private readonly ITestOutputHelper _output;
+    public class DefaultAnalyzerAssemblyLoaderTests : DefaultAnalyzerAssemblyLoaderTestsBase<InvokeUtil>
+    {
+    }
 
-        public DefaultAnalyzerAssemblyLoaderTests(ITestOutputHelper output)
-        {
-            _output = output;
-        }
+    public class ShadowCopyDefaultAnalyzerAssemblyLoaderTests : DefaultAnalyzerAssemblyLoaderTestsBase<ShadowInvokeUtil>
```
Comment (RikkiGibson) [inline src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:107]: I'm concerned this will negatively impact the dev experience when using the "run tests in context" command. If I go to a single test method and "run tests in context", the test framework will no longer have enough information to run the test.

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs [hunk 3]
```diff
@@ -204,44 +253,91 @@ public void AssemblyLoading()
...
+        /// call has occurred. This is historical behavior that doesn't have a clear reason for existing. There
+        /// is strong suspicion it's to delay loading of analyzers until absolutely necessary. As such we're
+        /// enshrining the behavior here so it is not _accidentally_ changed.
+        /// </summary>
+        [Fact]
+        public void AssemblyLoading_OverwriteBeforeLoad()
+        {
+            Run(static (DefaultAnalyzerAssemblyLoader loader, AssemblyLoadTestFixture testFixture) =>
+            {
+                StringBuilder sb = new StringBuilder();
```
Comment (RikkiGibson) [inline src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:267]: sb looks unused.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 4]
```diff
@@ -23,18 +25,40 @@ internal abstract class AnalyzerAssemblyLoader : IAnalyzerAssemblyLoader
     {
         private readonly object _guard = new();
 
-        // lock _guard to read/write
-        private readonly Dictionary<string, Assembly> _loadedAssembliesByPath = new();
+        /// <summary>
+        /// Set of analyzer dependencies original full paths to the data calculated for that path
+        /// </summary>
+        /// <remarks>
+        /// Access must be guaraded by <see cref="_guard"/>
```
Comment (RikkiGibson) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:32]: guarded

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 5]
```diff
@@ -23,18 +25,40 @@ internal abstract class AnalyzerAssemblyLoader : IAnalyzerAssemblyLoader
...
+        /// </remarks>
+        private readonly Dictionary<string, (AssemblyName? AssemblyName, string RealAssemblyPath)?> _analyzerAssemblyInfoMap = new();
 
-        // maps file name to a full path (lock _guard to read/write):
+        /// <summary>
+        /// Maps analyzer dependency simple names to the set of original full paths it was loaded from. This _only_ 
+        /// tracks the paths provided to the analyzer as it's a place to look for indirect loads. 
+        /// </summary>
+        /// <remarks>
+        /// Access must be guaraded by <see cref="_guard"/>
```
Comment (RikkiGibson) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:41]: guarded

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 6]
```diff
@@ -23,18 +25,40 @@ internal abstract class AnalyzerAssemblyLoader : IAnalyzerAssemblyLoader
...
-        /// Implemented by derived types to actually perform the load for an assembly that doesn't have a cached result.
+        /// The implementation needs to load an <see cref="Assembly"/> with the specified <see cref="AssemblyName"/>. The
+        /// <paramref name="assemblyOriginalPath"/> parameter is the original path. It may be different than
+        /// <see cref="AssemblyName.CodeBase"/>
         /// </summary>
-        protected abstract Assembly LoadFromPathUncheckedImpl(string fullPath);
+        /// <remarks>
+        /// The implementation should return null on error, not throw an exception
+        /// </remarks>
+        protected abstract Assembly Load(AssemblyName assemblyName, string assemblyOriginalPath);
```
Comment (RikkiGibson) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:53]: I don't see any nullable directives in the file, isn't nullable enabled at this location?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/ShadowCopyAnalyzerAssemblyLoader.cs [hunk 7]
```diff
@@ -95,13 +116,24 @@ private void DeleteLeftoverDirectories()
...
+            string shadowCopyPath = CopyFileAndResources(originalFullPath, assemblyDirectory);
+            _pathMap[originalFullPath] = shadowCopyPath;
             return shadowCopyPath;
         }
 
+        internal override string GetRealLoadPath(string originalFullPath)
+        {
+            if (!_pathMap.TryGetValue(originalFullPath, out var loadPath))
+            {
+                throw new InvalidOperationException();
```
Comment (RikkiGibson) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/ShadowCopyAnalyzerAssemblyLoader.cs:131]: I take it there's reasons we don't want to just propagate the KeyNotFoundException that would occur when using the indexer?

Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/ShadowCopyAnalyzerAssemblyLoader.cs:131]: That is exposing an implementation detail, prefer to be a bit more resilient to change here.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs (hunk 6 above)
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:53]: I need to update that comment. This code originally indicated `null` was valid. After I dug into the API call tree though I figured out `null` wasn't a valid return. It either loads or throws.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs (hunk 5 above)
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:41]: i was close

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs (hunk 2 above)
Comment (jaredpar) [reply src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:107]: Correct. Once you move to an `abstract` type with derived types as the mechanism for providing behavior you lose the ability to right click and run test in the editor. You instead have to go through Test Explorer and run the test from there. 

I wish the tests had a better UI for this but alas they do not. There are several other examples of this pattern in our code base. It's workable. If there are suggestions for better way to plumb this through Im' interested in discussing.

I have thought about long term doing a runner extensibility point similar to `[WpfFact]` called `[AssemblyContextFact]` which effectively runs your test in a new assembly context. For .NET Core it's a new `AssemblyLoadContext` and for .NET framework it's `AppDomain`. That is a *lot* of work though and haven't gone that far yet.

Comment (RikkiGibson) [reply src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:107]: A few alternatives on my mind.

1. Make it so when individual tests call Run(), that we run the test code using both the regular and shadow copy loaders.
2. Make all the tests Theory, with the loader as a new test method parameter.

If it feels like there are other considerable benefits of the current pattern which outweigh the above alternatives, then I won't *die on that hill*, but it means I will be fighting my muscle memory whenever I come back here in the future 😉

Comment (jaredpar) [reply src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:107]: I _think_ that either is doable. Essentially what would happen is either:

1. The implementation of `Run` calls the delegate twice, once with default and the other with shadow copy loader 
2. Have a `bool isDefault` parameter to the test case which feeds into `Run` and the implementation then toggles if it's a shadow copy or not. 

I'm not sure which is the better approach.

Comment (jaredpar) [reply src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:107]: After some thought I'm going with 2. The rational is I feel like it's easier to debug. 

Consider how failures manifest in CI logs. Unless we are very careful with 1 it will be very difficult to tell if the failure was in the default load vs shadow load case. Nothing on the stack would give you a clue that was the case. Where as with 2 it's a part of the test name so it's a lot more obvious.

File: src/Compilers/Core/Portable/Collections/DictionaryExtensions.cs [hunk 8]
```diff
@@ -31,5 +31,24 @@ internal static class DictionaryExtensions
                 return value;
             }
         }
+
+#if !NETCOREAPP
```
Comment (sharwell) [inline src/Compilers/Core/Portable/Collections/DictionaryExtensions.cs:35]: 💡 Probably not necessary to make this conditional. The caller will bind different on .NET Core builds, but at runtime it would be fine to execute this if something did call it.

Comment (jaredpar) [reply src/Compilers/Core/Portable/Collections/DictionaryExtensions.cs:35]: This was an attempt to polyfill an API that wasn't available in .NET Framework. I'm not 100% sure it's needed anymore. The change has taken a couple of different shapes in the last few weeks.

Comment (jaredpar) [reply src/Compilers/Core/Portable/Collections/DictionaryExtensions.cs:35]: Yeah this isn't needed in the final change. Removing.

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs (hunk 2 above)
Comment (jaredpar) [reply src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs]: Okay I'm going with 2. It was relatively straight forward to implement it. I've had to track down several failures locally and CI and I'm satisfied the information is there to make it clear which context the failure occurred in.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 9]
```diff
@@ -52,67 +76,165 @@ public void AddDependencyLocation(string fullPath)
                 {
                     _knownAssemblyPathsBySimpleName[simpleName] = paths.Add(fullPath);
                 }
+
+                _ = _analyzerAssemblyInfoMap[fullPath] = null;
```
Comment (RikkiGibson) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:80]: A comment is probably warranted here. Also, the discard assignment seems unnecessary.

I am guessing that when we add a dependency location, we want to "reset" the process of calculating a shadow path for it. Is that right?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs [hunk 10]
```diff
@@ -17,95 +17,48 @@ namespace Microsoft.CodeAnalysis
...
-        private static readonly AssemblyLoadContext s_compilerLoadContext = AssemblyLoadContext.GetLoadContext(typeof(DefaultAnalyzerAssemblyLoader).GetTypeInfo().Assembly)!;
-
+        private readonly AssemblyLoadContext _compilerLoadContext;
         private readonly object _guard = new object();
         private readonly Dictionary<string, DirectoryLoadContext> _loadContextByDirectory = new Dictionary<string, DirectoryLoadContext>(StringComparer.Ordinal);
 
-        protected override Assembly LoadFromPathUncheckedImpl(string fullPath)
+        internal AssemblyLoadContext CompilerLoadContext => _compilerLoadContext;
+
+        internal DefaultAnalyzerAssemblyLoader()
```
Comment (RikkiGibson) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs:26]: It feels like it would be more hygienic to either remove the parameter default value in the subsequent constructor, or to delete this constructor.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs (hunk 9 above)
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:80]: Correct. 

The scenario is the following: 

1. Analyzer.csproj builds to `bin\debug\analyzer.dll` 
2. Consumer.csproj leverages `analyzer.dll`. 
3. The solution is built multiple times

Every time we essentially get a new call to `AddDependencyLocation`. The second call needs to supercede the first one else the second build will re-load the first version of `analyzer.dll`

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs [hunk 11]
```diff
@@ -121,71 +74,50 @@ public DirectoryLoadContext(string directory, DefaultAnalyzerAssemblyLoader load
...
+                    (_, var loadPath) = _loader.GetAssemblyInfoForPath(assemblyPath);
+                    return LoadFromAssemblyPath(loadPath);
                 }
 
-                AssemblyName? bestCandidateName = null;
-                string? bestCandidatePath = null;
-                // The assembly isn't expected to be found at 'assemblyPath',
-                // but some assembly with the same simple name is known to the loader.
-                foreach (var candidatePath in paths)
+                // Next prefer dependencies that other analyzers registered. Ideally this would not
```
Comment (RikkiGibson) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs:98]: I feel like it would be more clear if we just said *Next prefer registered dependencies from other directories*. In some scenarios it is the same analyzer that registered the dependency in msbuild, and in other scenarios it's a different analyzer that registered it.

It might also make sense to note that *this enables analyzer dependencies to be loaded in ProjectReference scenarios, but it also allows packaged analyzers to load which have not properly shipped their dependencies, and are inadvertently relying on dependencies which were shipped by other analyzer packages*.

Eventually I do hope we can eliminate the need for this code path. But it means msbuild needs to stop pointing us at the nuget cache for assemblies that were copied to the output directory.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs (hunk 10 above)
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs:26]: removed the empty ctor

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 12]
```diff
@@ -52,67 +76,165 @@ public void AddDependencyLocation(string fullPath)
...
+        public Assembly LoadFromPath(string originalAnalyzerPath)
         {
-            CompilerPathUtilities.RequireAbsolutePath(fullPath, nameof(fullPath));
-            return LoadFromPathUnchecked(fullPath);
-        }
+            CompilerPathUtilities.RequireAbsolutePath(originalAnalyzerPath, nameof(originalAnalyzerPath));
+
+            (AssemblyName? assemblyName, string _) = GetAssemblyInfoForPath(originalAnalyzerPath);
+
+            // Not a managed assembly, nothing else to do
```
Comment (RikkiGibson) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:90]: This is not a behavior change, right?

I am thinking of #54899 and I feel like we should permit the analyzer loader to load native dependencies. We know that people are working around this by doing IO in their extensions. It doesn't need to happen in this PR, but we do have it paged in now, and it might be a good time to just do it.

We know that when a native assembly is referenced in the build, that we will enter this path in an attempt to load any analyzers in it. Right? We could make Load take a nullable assemblyName, and require that a native assembly is found when assemblyName is null, and that a managed assembly is found when assemblyName is not null. If a native assembly is found, don't bother searching for analyzers in it, but do register it as a dependency location (which is already done at an earlier phase).

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs (hunk 11 above)
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs:98]: > Eventually I do hope we can eliminate the need for this code path. But it means msbuild needs to stop pointing us at the nuget cache for assemblies that were copied to the output directory.

Which is the bug that outlines this problem? Want to reference it here.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs (hunk 12 above)
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:90]: > This is not a behavior change, right?

Correct. This threw before as well. It's caught up in `AnalyzerFileReference.AddExtensions` where a diagnostic is registered for the exception. 

> I am thinking of https://github.com/dotnet/roslyn/issues/54899 and I feel like we should permit the analyzer loader to load native dependencies.

Lukewarm agree but it's more complicated than just removing the exception path here though. Have to consider this becomes the mechanism for passing any binary dependency threw to analyzers and that means we likely need to work with IDE to make sure these aren't inspected in ways that would cause issues if it suddenly became a large non-PE file

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 13]
```diff
@@ -52,67 +76,165 @@ public void AddDependencyLocation(string fullPath)
...
-
-            // Check if we have already loaded an assembly from the given path.
-            Assembly? loadedAssembly = null;
+            AssemblyName? assemblyName;
+            string realPath;
+            bool hasData;
             lock (_guard)
             {
-                if (_loadedAssembliesByPath.TryGetValue(fullPath, out var existingAssembly))
+                if (!_analyzerAssemblyInfoMap.TryGetValue(originalAnalyzerPath, out var tuple))
```
Comment (RikkiGibson) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:122]: Consider just locking to read the tuple.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 14]
```diff
@@ -52,67 +76,165 @@ public void AddDependencyLocation(string fullPath)
...
+                {
+                    throw new InvalidOperationException();
+                }
+
+                if (tuple is { } info)
+                {
+                    assemblyName = info.AssemblyName;
+                    realPath = info.RealAssemblyPath;
+                    hasData = true;
```
Comment (RikkiGibson) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:131]: Consider returning here instead of using a 'hasData' flag.

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs [hunk 15]
```diff
@@ -30,63 +30,131 @@
...
-        private AssemblyLoadTestFixtureCollection() { }
-    }
+#if NETCOREAPP
 
-    public sealed class DefaultAnalyzerAssemblyLoaderTests : TestBase
+    public sealed class InvokeUtil
     {
-#if NETCOREAPP
-        private sealed class InvokeUtil
+        public void Exec(Action<string> testOutputHelper, AssemblyLoadContext alc, bool shadowLoad, string typeName, string methodName)
```
Comment (RikkiGibson) [inline src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:37]: Consider naming this something like `compilerContext`

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs [hunk 16]
```diff
@@ -30,63 +30,131 @@
...
+            var loader = shadowLoad
+                ? new ShadowCopyAnalyzerAssemblyLoader(alc, tempRoot.CreateDirectory().Path)
+                : new DefaultAnalyzerAssemblyLoader(alc);
+            try
+            {
+                DefaultAnalyzerAssemblyLoaderTests.InvokeTestCode(loader, fixture, typeName, methodName);
+            }
+            finally
+            {
+                testOutputHelper($"Test fixture root: {fixture.TempDirectory.Path}");
```
Comment (RikkiGibson) [inline src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:56]: It wasn't clear to me why we use this action instead of passing the ITestOutputHelper itself and calling WriteLine.

Comment (jaredpar) [reply src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:56]: It's complicated ... 

The way the `AssemblyLoadContext` are setup today there are two copies of `ITestOutputHelper` because `XUnit.Abstractions.dll` is loaded twice: once in the default ALC and once in the custom ALC. That means if you try and pass `ITestOutputHelper` directly here you get a type mismatch at runtime because they are different types. 

To pass it around I need to move all of the xUnit loading into the default ALC. That is a bit challenging given how it's setup. I'm trying experiments to do that but may push that off into a follow up PR.

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs [hunk 17]
```diff
@@ -30,63 +30,131 @@
...
+                }
+
+                if (loader is ShadowCopyAnalyzerAssemblyLoader shadowLoader)
+                {
+                    testOutputHelper($"Shadow loader: {shadowLoader.BaseDirectory}");
+                }
+
+                testOutputHelper($"Loader path maps");
+                foreach (var pair in loader.GetPathMapSnapshot())
+                {
```
Comment (RikkiGibson) [inline src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:74]: It may aid readability to quote the values, e.g. `$"\t""{pair.Key}"" -> ""{pair.Value}"""`

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs [hunk 18]
```diff
@@ -363,10 +527,22 @@ public void AssemblyLoading_DependencyInDifferentDirectory2()
                 Assert.Equal(@"Delta: Gamma: Test G
 ", actual);
 
-                VerifyDependencyAssemblies(
-                    loader,
-                    deltaFile2.Path,
-                    gammaFile.Path);
+                if (ExecutionConditionUtil.IsDesktop && loader is ShadowCopyAnalyzerAssemblyLoader)
+                {
+                    // In desktop + shadow we lose the ability to related dlls in the same directory
```
Comment (RikkiGibson) [inline src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:532]: I didn't understand this comment.

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs [hunk 19]
```diff
@@ -30,63 +30,131 @@
...
+            }
+            catch (TargetInvocationException ex) when (ex.InnerException is XunitException)
+            {
+                var inner = ex.InnerException;
+                throw new Exception(inner.Message + inner.StackTrace);
+            }
+            finally
+            {
+                testOutputHelper.WriteLine($"Test fixture root: {fixture.TempDirectory.Path}");
+
```
Comment (RikkiGibson) [inline src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:107]: One thing I am wondering is, is this just a test baseline which should be recorded and turned into a failure when things change? Or is it much too brittle for that?

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs [hunk 20]
```diff
@@ -525,23 +745,44 @@ public void AssemblyLoading_MultipleVersions_MultipleEqualMatches()
...
                 e.GetType().GetMethod("Write")!.Invoke(e, new object[] { sb, "Test E" });
 
-                VerifyDependencyAssemblies(
-                    loader,
-                    testFixture.Delta2.Path,
-                    testFixture.Epsilon.Path);
+                if (ExecutionConditionUtil.IsDesktop && loader is ShadowCopyAnalyzerAssemblyLoader)
+                {
+                    // Delta2B and Delta2 have the same version, but we prefer Delta2B because it's added first and 
+                    // in shadow loader we can't fall back to same directory because the runtime doesn't provide
```
Comment (RikkiGibson) [inline src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:751]: Is this something that would be alleviated if the shadow loader grouped its outputs based on the directory structure of the "original" assemblies?

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs [hunk 21]
```diff
@@ -631,23 +886,45 @@ public void AssemblyLoading_MultipleVersions_WorseMatchInSameDirectory()
...
-                VerifyDependencyAssemblies(
-                    loader,
-                    delta1File.Path,
-                    epsilonFile.Path);
+                if (ExecutionConditionUtil.IsDesktop && loader is ShadowCopyAnalyzerAssemblyLoader)
+                {
+                    // In desktop + shadow load the dependencies are in different directories with 
+                    // no context available when the load for Delta comes in. So we pick the best 
+                    // option.
+                    // Epsilon wants Delta2, but since Delta1 is in the same directory, we prefer Delta1 over Delta2.
```
Comment (RikkiGibson) [inline src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:894]: Should this line be deleted?

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs [hunk 22]
```diff
@@ -874,31 +1160,48 @@ public void AssemblyLoading_NativeDependency()
...
                 StringBuilder sb = new StringBuilder();
 
                 var tempDir = temp.CreateDirectory();
                 var deltaCopy = tempDir.CreateFile("Delta.dll").CopyContentFrom(testFixture.Delta1.Path);
                 loader.AddDependencyLocation(deltaCopy.Path);
-                Assembly delta = loader.LoadFromPath(deltaCopy.Path);
+                Assembly? delta = loader.LoadFromPath(deltaCopy.Path);
 
-                try
+                if (loader is ShadowCopyAnalyzerAssemblyLoader)
```
Comment (RikkiGibson) [inline src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:1199]: ` || !ExecutionConditionUtil.IsWindows`?

Comment (RikkiGibson) [reply src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:1199]: BTW, is there any reason to use the shadow copy loader on non-Windows platforms? Is the usage of it conditioned accordingly?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/ShadowCopyAnalyzerAssemblyLoader.cs [hunk 23]
```diff
@@ -3,11 +3,17 @@
 // See the LICENSE file in the project root for more information.
 
 using System;
+using System.Collections.Concurrent;
 using System.Collections.Generic;
 using System.IO;
+using System.Linq;
```
Comment (RikkiGibson) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/ShadowCopyAnalyzerAssemblyLoader.cs:9]: Looks unused in current iteration.

**Comment by RikkiGibson** [comment]
A Linux test crashed when running the test `Microsoft.CodeAnalysis.UnitTests.DefaultAnalyzerAssemblyLoaderTests.AssemblyLoading_DependencyInDifferentDirectory`.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 24]
```diff
@@ -52,67 +76,165 @@ public void AddDependencyLocation(string fullPath)
...
+            foreach (var candidateOriginalPath in paths.OrderBy(StringComparer.Ordinal))
+            {
+                (AssemblyName? candidateName, string candidateRealPath) = GetAssemblyInfoForPath(candidateOriginalPath);
+                if (candidateName is null)
+                {
+                    continue;
+                }
+
+                bool isMatch;
+#if NETCOREAPP
```
[the remark this answers is not in the document]
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:189]: It's a sensible idea, I'm not sure I want to lump it into this PR though. It will cause fairly significant rename on top of all the churn already present here. May want to push that off to a follow up so I can get this bug fix in.

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs (hunk 19 above)
Comment (jaredpar) [reply src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:107]: It's too brittle for that. The shadow copy base directory changes on every run of the test. Also the set of test assemblies, particularly in the default contexts, change with some regularity. Consider that every change of a version, NuPkg update, etc ... change the output. 

For the most part I've found just the extra data here is enough to diagnose what is going wrong. Even in CI situations.

**Comment by jaredpar** [comment]
@RikkiGibson looks like this is a legite runtime crash. Filed a bug to track. Will disable this test on Linux 

https://github.com/dotnet/runtime/issues/81108

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs (hunk 24 above)
[the remark this answers is not in the document]
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:189]: I went ahead and spiked this out here 

https://github.com/jaredpar/roslyn/commit/c3fa753cc36766f1787506c42f8ed0b9d050482a

I agree we should do this but I'm leery to add it to the current PR. Feel like it's complicated enough. Think it's better to get this merged then follow up with that change quickly after. Open to suggestions.

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs (hunk 22 above)
Comment (jaredpar) [reply src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs]: I _think_ it can be but need to do more digging. Yes we can delete the files today but is that an accident of implementation or intentional design decision? Also are there other side effects we're not thinking of here? Have to discuss a bit with runtime team. 

Will add it to the list of follow ups in #66532.

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs [hunk 25]
```diff
@@ -127,6 +127,48 @@ public void Exec(ITestOutputHelper testOutputHelper, bool shadowLoad, string typ
...
+    /// same directory then the runtime will silently load it without a way for us to intervene.
+    ///
+    /// Note: this only applies when A.dll is in the Load or LoadFrom context which is always true for these tests
+    /// 
+    /// Limitation 2: Dependency is already loaded.
+    ///
+    /// Similar to Limitation 1 is when the dependency, B.dll, is already present in the Load or LoadFrom context 
+    /// then that will be used. The runtime will not attempt to load a better version (an exact match for example).
+    ///
+    /// Limitation 3: Shadow copy breaks up directories
```
Comment (RikkiGibson) [inline src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:158]: I expected limitation 3 to be referenced in some of the below tests, but it's not urgent to make the change to do so.

**Review by RikkiGibson — APPROVED** [review]
LGTM assuming CI is green.

File: src/Workspaces/Remote/ServiceHubTest/RemoteAnalyzerAssemblyLoaderTests.cs [hunk 26]
```diff
@@ -24,8 +26,8 @@ public void NonIdeAnalyzerAssemblyShouldBeLoadedInSeparateALC()
             // Try to load MS.CA.Remote.ServiceHub.dll as an analyzer assembly via RemoteAnalyzerAssemblyLoader
             // since it's not one of the special assemblies listed in RemoteAnalyzerAssemblyLoader,
             // RemoteAnalyzerAssemblyLoader should loaded in a spearate DirectoryLoadContext. 
-            loader.AddDependencyLocation(remoteAssemblyLocation);
-            var remoteAssemblyLoadedViaRemoteLoader = loader.LoadFromPath(remoteAssemblyLocation);
+            loader.AddDependencyLocation(testFixture.Delta1.Path);
+            var remoteAssemblyLoadedViaRemoteLoader = loader.LoadFromPath(testFixture.Delta1.Path);
```
Comment (jaredpar) [inline src/Workspaces/Remote/ServiceHubTest/RemoteAnalyzerAssemblyLoaderTests.cs:30]: @genlu wanted to make sure you signed off on this change. 

This change defers all assembly loading to the host. In short, if the host can resolve a name then we load the host copy of the DLL. Everything else is loaded from the analyzer dependency list. 

In this case your test was using a DLL that exists in the host directory as an analyzer dependency. In the new model that is resolvable by the host hence ends up in the host `AssemblyLoadContext`. I modified it to use a DLL which will never be resolvable by the host `AssemblyLoadContext`. I believe that maintains the intent of the test but want to verify.

Comment (genlu) [reply src/Workspaces/Remote/ServiceHubTest/RemoteAnalyzerAssemblyLoaderTests.cs:30]: I just started looking at this PR, will try to finish by tomorrow. I think the coreclr loader would be fine, since we only ship a small set of assemblies that's considered resolvable by our remote host on .NET 6. But on netfx remote host, my understanding is everything shipped in VS could be considered resolvable? I'd need to take a closer look at that part to understand the potential impact.

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs (hunk 25 above)
Comment (jaredpar) [reply src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:158]: It is referenced in `AssemblyLoading_DependencyInDifferentDirectory2`.

File: src/Workspaces/Remote/ServiceHubTest/RemoteAnalyzerAssemblyLoaderTests.cs (hunk 26 above)
Comment (genlu) [reply src/Workspaces/Remote/ServiceHubTest/RemoteAnalyzerAssemblyLoaderTests.cs:30]: The change to this test looks good. Could you please also fix the comment above to reflect this change?

**Review by genlu — APPROVED** [review]

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs [hunk 27]
```diff
@@ -30,63 +30,173 @@
...
+    ///
+    ///    // See limitation 1
+    ///
+    /// This allows us to provide central description of the limitations that can be easily referenced in the impacted
+    /// tests. For all the descriptions below assume that A.dll depends on B.dll. 
+    ///
+    /// Limitation 1: .NET Framework probing path.
+    ///
+    /// The .NET Framework assembly loader will only call AppDomain.AssemblyResolve when it cannot satifisfy a load
+    /// request. One of the places the assembly loader will always consider when looking for dependecies of A.dll
```
Comment (cston) [inline src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:147]: >dependecies [](http://example.com/codeflow?start=93&length=11)

Typo.

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs [hunk 28]
```diff
@@ -30,63 +30,173 @@
...
+    /// is the directory that A.dll was loading from (it's added to the probing path). Than means if B.dll is in the
+    /// same directory then the runtime will silently load it without a way for us to intervene.
```
Comment (cston) [inline src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:149]:
```suggestion
    /// request. One of the places the assembly loader will always consider when looking for dependencies of A.dll
    /// is the directory that A.dll was loading from (it's added to the probing path). That means if B.dll is in the
    /// same directory then the runtime will silently load it without a way for us to intervene.
```

**Review by jmarolf — APPROVED** [review]
I've been turning this over in my mind for the past two days and I think this is the best we can do. It still feels like there is a category of dependencies that we want to treat as special. If someone passes in an arbitrary version of a compiler assembly on .NET Framework I would hope that we've already loaded it and its ignored. But there are lots of other downside to that behavior. We can discuss this more in the resolution for https://github.com/dotnet/roslyn/issues/66532. Great work on the tests

**Comment by RikkiGibson** [comment]
Yeah, the situation where the compiler hasn't loaded one of its dependencies *yet*, and the analyzer asks for it, is a troubling one. I wonder if there's any test that would reproduce that.

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs [hunk 29]
```diff
@@ -204,44 +318,105 @@ public void AssemblyLoading()
...
         {
-            Run(static (DefaultAnalyzerAssemblyLoader loader, AssemblyLoadTestFixture testFixture) =>
+            Run(shadowLoad, static (DefaultAnalyzerAssemblyLoader loader, AssemblyLoadTestFixture testFixture) =>
+            {
+                loader.AddDependencyLocation(testFixture.Delta1.Path);
+                testFixture.Delta1.WriteAllBytes(testFixture.Delta2.ReadAllBytes());
+                var assembly = loader.LoadFromPath(testFixture.Delta1.Path);
+
+                var name = AssemblyName.GetAssemblyName(testFixture.Delta2.Path);
+                Assert.Equal(name.FullName, assembly.GetName().FullName);
```
Comment (cston) [inline src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:338]: Would it make sense to use `VerifyAssemblies()` here instead, to check that the assembly is in the shadow directory, and perhaps other details?
```
VerifyAssemblies(loader, new[] { assembly }, ("Delta", "2.0.0.0", testFixture.Delta2.Path));
```

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 30]
```diff
@@ -52,67 +76,176 @@ public void AddDependencyLocation(string fullPath)
...
             lock (_guard)
             {
-                if (_loadedAssembliesByPath.TryGetValue(fullPath, out var existingAssembly))
+                if (!_analyzerAssemblyInfoMap.TryGetValue(originalAnalyzerPath, out var tuple))
                 {
-                    loadedAssembly = existingAssembly;
+                    throw new InvalidOperationException();
+                }
+
+                if (tuple is { } info)
```
Comment (jcouv) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:128]: nit: we don't need a new local. Maybe `tuple` to `foundInfo` and then just do a `is not null` here.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 31]
```diff
@@ -52,67 +76,176 @@ public void AddDependencyLocation(string fullPath)
...
+                if (!_analyzerAssemblyInfoMap.TryGetValue(originalFullPath, out var tuple))
+                {
+                    throw new InvalidOperationException($"Invalid original path: {originalFullPath}");
+                }
+
+                return tuple is { } value ? value.RealAssemblyPath : originalFullPath;
+            }
+        }
+
+        internal (string OriginalAssemblyPath, string RealAssemblyPath)[] GetPathMapSnapshot()
```
Comment (jcouv) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:240]: This method appears unused. Is it for debugging? If so, consider using ` #if DEBUG` and/or switching to a `Dump()` that prints out strings.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 32]
```diff
@@ -52,67 +76,176 @@ public void AddDependencyLocation(string fullPath)
...
+#else
+                isMatch =
+                    candidateName.Name == assemblyName.Name &&
+                    candidateName.Version >= assemblyName.Version &&
+                    candidateName.GetPublicKeyToken().AsSpan().SequenceEqual(assemblyName.GetPublicKeyToken().AsSpan());
+#endif
+
+                if (isMatch)
+                {
+                    if (candidateName.Version == assemblyName.Version)
```
Comment (jcouv) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:200]: I didn't follow this case. Couldn't a later candidate be even better (ie. have a larger version)?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 33]
```diff
@@ -52,67 +76,176 @@ public void AddDependencyLocation(string fullPath)
...
         /// loaded from disk. This is used to substitute out the original path with the shadow-copied version.
         /// </summary>
-        protected virtual string GetPathToLoad(string fullPath)
+        protected virtual string PreparePathToLoad(string fullPath) => fullPath;
+
+        /// <summary>
+        /// When <see cref="PreparePathToLoad(string)"/> is overriden this returns the most recent
+        /// real path calculated for the <paramref name="originalFullPath"/>
+        /// </summary>
+        internal string GetRealLoadPath(string originalFullPath)
```
Comment (jcouv) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:227]: This method also appears to only be used in tests. Consider adding a comment to that effect.

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs [hunk 34]
```diff
@@ -585,33 +866,47 @@ public void AssemblyLoading_MultipleVersions_ExactAndGreaterMatch()
...
 ",
                         actual);
                 }
                 else
                 {
+                    // See limitation 2
+                    Assert.Throws<InvalidOperationException>(() => loader.GetRealLoadPath(testFixture.Delta2.Path));
+
+                    // Fake the dependency so we can verify the rest of the load
+                    loader.AddDependencyLocation(testFixture.Delta2.Path);
```
Comment (cston) [inline src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:891]: Why is this necessary? Shouldn't we use `textFixture.Delta2B.Path` below instead?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 35]
```diff
@@ -52,67 +76,176 @@ public void AddDependencyLocation(string fullPath)
...
+            return bestPath;
         }
 
         /// <summary>
         /// When overridden in a derived class, allows substituting an assembly path after we've
         /// identified the context to load an assembly in, but before the assembly is actually
         /// loaded from disk. This is used to substitute out the original path with the shadow-copied version.
         /// </summary>
-        protected virtual string GetPathToLoad(string fullPath)
+        protected virtual string PreparePathToLoad(string fullPath) => fullPath;
```
Comment (jcouv) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:221]: Consider using abstract instead.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs [hunk 36]
```diff
@@ -17,95 +17,43 @@ namespace Microsoft.CodeAnalysis
...
-               "System.Xml.ReaderWriter",
-               "System.Xml.XDocument",
-               "System.Xml.XPath.XDocument");
-
-        internal virtual ImmutableHashSet<string> AssemblySimpleNamesToBeLoadedInCompilerContext => CompilerAssemblySimpleNames;
-
-        // This is the context where compiler (and some of its dependencies) are being loaded into, which might be different from AssemblyLoadContext.Default.
-        private static readonly AssemblyLoadContext s_compilerLoadContext = AssemblyLoadContext.GetLoadContext(typeof(DefaultAnalyzerAssemblyLoader).GetTypeInfo().Assembly)!;
-
+        private readonly AssemblyLoadContext _compilerLoadContext;
```
Comment (jcouv) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Core.cs:20]: not related to this PR, consider sealing `DefaultAnalyzerAssemblyLoader` (both of them)

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 37]
```diff
@@ -52,67 +76,176 @@ public void AddDependencyLocation(string fullPath)
                 {
                     _knownAssemblyPathsBySimpleName[simpleName] = paths.Add(fullPath);
                 }
+
+                // Ensure that there is no cached Assembly information about this location. Long 
+                // lived processes like VS and VBCSCompiler will see the same location added as
+                // a dependency many times. Each time have to assume there is new content on disk
+                // that needs to be considered.
+                _analyzerAssemblyInfoMap[fullPath] = null;
```
Comment (cston) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:84]: >_analyzerAssemblyInfoMap[fullPath] = null; [](http://example.com/codeflow?start=16&length=42)

Is the `AnalyzerAssemblyLoader` instance shared across multiple builds? If so, what is the impact of clearing `_analyzerAssemblyInfoMap[fullPath]` on other concurrent builds that may use the same dependency path?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 38]
```diff
@@ -52,67 +76,176 @@ public void AddDependencyLocation(string fullPath)
...
+            AssemblyName? assemblyName;
+            try
             {
-                loadedAssembly = LoadFromPathUncheckedImpl(fullPath);
+                assemblyName = AssemblyName.GetAssemblyName(realPath);
+            }
+            catch
+            {
+                // The above can fail with the assembly doesn't exist because it's corrupted, 
+                // doesn't exist on disk or is a native DLL. Those failures are handled when
```
Comment (cston) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:143]:
```suggestion
                // The above can fail when the assembly doesn't exist because it's corrupted, 
                // doesn't exist on disk, or is a native DLL. Those failures are handled when 
```

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 39]
```diff
@@ -52,67 +76,176 @@ public void AddDependencyLocation(string fullPath)
...
-        }
+            CompilerPathUtilities.RequireAbsolutePath(originalAnalyzerPath, nameof(originalAnalyzerPath));
 
-        #endregion
+            (AssemblyName? assemblyName, string _) = GetAssemblyInfoForPath(originalAnalyzerPath);
+
+            // Not a managed assembly, nothing else to do
+            if (assemblyName is null)
+            {
+                throw new ArgumentException("Not a valid assembly");
```
Comment (cston) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:97]: >throw new ArgumentException("Not a valid assembly"); [](http://example.com/codeflow?start=16&length=52)

Consider including the path: `"Not a valid assembly: " + originalAnalyzerPath`

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs [hunk 40]
```diff
@@ -30,63 +30,173 @@
...
                 }
             }
         }
+    }
+
 #endif
 
-        private static readonly CSharpCompilationOptions s_dllWithMaxWarningLevel = new(OutputKind.DynamicallyLinkedLibrary, warningLevel: CodeAnalysis.Diagnostic.MaxWarningLevel);
-        private readonly ITestOutputHelper _output;
+    /// <summary>
```
Comment (jcouv) [inline src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:130]: This was super helpful. Thanks!

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs [hunk 41]
```diff
@@ -30,63 +30,173 @@
...
+            // Ensure that the test did not load any of the test fixture assemblies into 
+            // the default load context. That should never happen. Assemblies should either 
+            // load into the compiler or directory load context.
+            //
+            // Not only is this bad behavior it also pollutes future test results.
+            var count = AssemblyLoadContext.Default.Assemblies.Count();
+            using var fixture = new AssemblyLoadTestFixture();
+            using var tempRoot = new TempRoot();
+            var loader = shadowLoad
+                ? new ShadowCopyAnalyzerAssemblyLoader(alc, tempRoot.CreateDirectory().Path)
```
Comment (jcouv) [inline src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:48]: I'm missing a bit of context. When is the Core+ShadowCopy combination useful? I though shadow copying was mostly a workaround for the locking that Desktop does when loading assemblies.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 42]
```diff
@@ -52,67 +76,176 @@ public void AddDependencyLocation(string fullPath)
...
-                if (_loadedAssembliesByPath.TryGetValue(fullPath, out var existingAssembly))
+                if (!_analyzerAssemblyInfoMap.TryGetValue(originalAnalyzerPath, out var tuple))
                 {
-                    loadedAssembly = existingAssembly;
+                    throw new InvalidOperationException();
+                }
+
+                if (tuple is { } info)
+                {
+                    return (info.AssemblyName, info.RealAssemblyPath);
```
Comment (cston) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:130]: >return (info.AssemblyName, info.RealAssemblyPath); [](http://example.com/codeflow?start=20&length=50)

`return info;`

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 9). Mostly some clarifying questions. Thanks

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 43]
```diff
@@ -52,67 +76,176 @@ public void AddDependencyLocation(string fullPath)
...
+                }
+
+                bool isMatch;
+#if NETCOREAPP
+                isMatch = candidateName.Name == assemblyName.Name;
+#else
+                isMatch =
+                    candidateName.Name == assemblyName.Name &&
+                    candidateName.Version >= assemblyName.Version &&
+                    candidateName.GetPublicKeyToken().AsSpan().SequenceEqual(assemblyName.GetPublicKeyToken().AsSpan());
```
Comment (cston) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:195]: >candidateName.GetPublicKeyToken().AsSpan().SequenceEqual(assemblyName.GetPublicKeyToken().AsSpan() [](http://example.com/codeflow?start=20&length=98)

Is the public key check not needed with `NETCOREAPP`?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs [hunk 44]
```diff
@@ -102,106 +69,27 @@ internal bool EnsureResolvedUnhooked()
...
         }
 
-        private Assembly? CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs args)
+        private Assembly? AssemblyResolve(object sender, ResolveEventArgs args)
         {
-            // In the .NET Framework, if a handler to AssemblyResolve throws an exception, other handlers
-            // are not called. To avoid any bug in our handler breaking other handlers running in the same process
-            // we catch exceptions here. We do not expect exceptions to be thrown though.
             try
             {
```
Comment (cston) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs:75]: Consider wrapping `try { ... } catch { ... }` around `return Assembly.LoadFrom(bestPath);` only, assuming that is the only method expected to throw an exception.

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs (hunk 41 above)
Comment (jaredpar) [reply src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:48]: The primary purpose of shadow copy is to avoid locking files on disk. Analyzers are frequently loaded from locations that developers delete as a part of normal dev operations. Hence we shadow copy to allow normal dev operations to occur. 

That is true for both .NET Framework and .NET Core. Experimentally .NET Core + Linux allows delete without shadow copy but we're unsure if that is 100% viable for our scenarios. Part of #66532 is discussing that with the runtime team.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs (hunk 37 above)
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:84]: > Is the AnalyzerAssemblyLoader instance shared across multiple builds?

Yes.

> If so, what is the impact of clearing _analyzerAssemblyInfoMap[fullPath] on other concurrent builds that may use the same dependency path?

This is part of the second follow up item I have in #66532. The APIs are designed such that you can call `AddDependencyPath` followed by `LoadFromPath` in any order and combination. In truth though it only works 100% correct if you call them in a very specific pattern. Our uses of these APIs just so happen to use this pattern. 

The other invariant the loader has is that the on disk state cannot be modified in between calls to `AddDepedencyPath` and `LoadFromPath`. So even if two builds come along, call `AddDependencyPath` in parallel it's fine so long as this invariant is kept. One will clear the cached data, but the second will come along and put it back to the previous state. 

If you concurrent build, share analyzers, and change the on disk state of those locations it can result in quirky behavior. It has always been this way though. The previous code which attempted to cache assemblies was actually not doing what it thought it did. The underlying `AppDomain` and `AssemblyLoadContext` caches won out in all the load scenarios. 

I want to replace this with an APi which is *much* easier to follow. Compilations need to be registering their dependencies as a batch operation. That makes all of this clearer and afford us the ability to be more resilient in a few cases. But that's a follow up issue.

**Comment by jaredpar** [comment]
> Yeah, the situation where the compiler hasn't loaded one of its dependencies yet, and the analyzer asks for it, is a troubling one. I wonder if there's any test that would reproduce that.

That really shouldn't be an issue. On .NET Core we have complete control and do the right thing. On .NET Framework there are two cases to consider: 
1. Registered dependency will go through our code and load in host 
2. Non-registered dependency indirect load: that will go through normal assembly resolution in the `AppDomain` which will let the host choose. 
3. 2. Non-registered dependency direct load: Essentially a dependency doing `Assembly.LoadFrom("Microsoft.CodeAnalysis.dll") that can put MS.CA into the `LoadFrom` context. But honestly there is nothing we can do to protect against that and such dependencies are asking for problems.

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs (hunk 15 above)
Comment (jaredpar) [reply src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:37]: cleaned this up in the next PR where i fixed up names quite a bit.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 45]
```diff
@@ -52,67 +76,176 @@ public void AddDependencyLocation(string fullPath)
...
+
+            // Not a managed assembly, nothing else to do
+            if (assemblyName is null)
+            {
+                throw new ArgumentException("Not a valid assembly");
+            }
+
+            try
+            {
+                return Load(assemblyName, originalAnalyzerPath);
```
[the remark this answers is not in the document]
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:102]: The `originalAssemblyPath` is really only used to partition out the analyzer dependencies into `DirectoryLoadContext`. It really has no other usage. You can see that in the `.Desktop` case the variable is named `_` to be explicit about it not being used. 

One subtle detail here that is hard to doc / explain is that `AssemblyName.Location` has the real path in it for .NET Framework. That is really key to making the entire load scenario work on .NET Framework. For .NET Core though the strategy is a bit different because we have directory based isolation.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs (hunk 30 above)
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:128]: Correcth but then I have to do `tuple.Value.` in all the calls and I just prefer the local that doesn't have it.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs (hunk 43 above)
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:195]: On .NET Core the only thing that matters is simple name. The runtime never considers public key tokens or versions. Thus our dependency loading has to do the same.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs (hunk 32 above)
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:200]: The code has historically preferred identical versions over greater ones. That is a known quantity. While higher versions are generally compatible with lower versions that is not always true. Consider semantic versioning allows for breaks once major version changes happen. 

Overall though this is the existing behavior of the code, not new one I'm adding. There are tests that specifically assert we make this decision. Hence unless there is a compelling reason to change I'm inclined to keep the current behavior.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs (hunk 35 above)
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:221]: Agree but I've held tha off with the other refactoring around relationship between the hierarchy here. I have the change locally as my follow up PR.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs (hunk 33 above)
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:227]: Why though? It's designed to be used in product or test code. I'm not sure the value in commenting it's only used in tests at the moment. It's perfectly valid for product code to depend on in the future.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs (hunk 44 above)
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs:75]: `ApplyPolicy`, `new AssemblyName` and `LoadFrom` can all throw. The first two are significantly more edge case than the last one but they can indeed throw. Basically only `GetBestPath` is a non-throwing API.

**Review by cston — APPROVED** [review]

**Comment by jaredpar** [comment]
Sorry, I know we have a lot of active convos happening here but I need to rebase and force push. Until I do this change is going to be blocked by the Correctness build bug in our infra.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs (hunk 30 above)
Comment (jcouv) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:128]: Thanks. I'd missed this was a nullable tuple.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs (hunk 32 above)
Comment (jcouv) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:200]: Makes sense. Consider leaving a comment

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 11)
