### PR TITLE
Collection expressions: report specific error (if any) for explicit cast failure

### LINKED ISSUE #71490: Unexpected error message from collection expression cast
**Version Used**: 
https://github.com/dotnet/roslyn/commit/754f1b02295bdfcb8161665229a3530e6d3ba04b

**Steps to Reproduce**:
```C#
using System;

public class C 
{
    private DateTimeOffset _d;
    
    public void M() 
    {
        ReadOnlySpan<DateTime> x = [_d];
        var y = (ReadOnlySpan<DateTime>)[_d];
    }
}
```

**Expected Behavior**:
Both x and y produce the same error that's descriptive about not being able to convert a DateTimeOffset to a DateTime.

**Actual Behavior**:
x produces "error CS0029: Cannot implicitly convert type 'System.DateTimeOffset' to 'System.DateTime'"
y produces "error CS9174: Cannot initialize type 'ReadOnlySpan<DateTime>' with a collection expression because the type is not constructible."

### PR DESCRIPTION
**Pull request by cston**
Fixes #71490

### CODE REVIEW

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 2)

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 1]
```diff
@@ -2761,12 +2761,8 @@ private BoundExpression BindCastCore(ExpressionSyntax node, BoundExpression oper
                     }
                 case BoundKind.UnconvertedCollectionExpression:
                     {
-                        if (operand.Type is null)
-                        {
-                            Error(diagnostics, ErrorCode.ERR_CollectionExpressionTargetTypeNotConstructible, syntax, targetType);
-                            return;
-                        }
-                        break;
+                        GenerateImplicitConversionErrorForCollectionExpression((BoundUnconvertedCollectionExpression)operand, targetType, diagnostics);
```
Comment (jjonescz) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:2764]: Should the method be renamed since it is used to handle both implicit and explicit conversions now?

**Review by jjonescz — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 1 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:2764]: I'd considered renaming but decided to leave the name as is since we're using a similarly named method for the UnconvertedConditionalOperator and UnconvertedSwitchExpression cases above.

Perhaps we can consider renaming in a follow up PR if necessary.
