### PR TITLE
Avoid creating result temp for is-expressions (follow-up)

### LINKED ISSUE #55334: Pattern matching causing redundant jumps in generated IL (maybe a bug, maybe a good reason?)
**Version Used**: cli 5.0.302

**Steps to Reproduce**:
Compile the following method (LangVersion=9.0) in Release mode
```csharp
        public static string GetDescription(TestData data)
        {
            if (data is null or { A: null, B: null, C: null })
                return null;
            else
                return "Yay, stuff";
        }
```
**Actual Behavior**:
```cil
.method public hidebysig static string  GetDescription(class CoverletIssues.Program/TestData data) cil managed
{
  // Code size       44 (0x2c)
  .maxstack  1
  .locals init (bool V_0)
  IL_0000:  ldarg.0
  IL_0001:  brfalse.s  IL_001b
  IL_0003:  ldarg.0
  IL_0004:  callvirt   instance string CoverletIssues.Program/TestData::get_A()
  IL_0009:  brtrue.s   IL_001f
  IL_000b:  ldarg.0
  IL_000c:  callvirt   instance string CoverletIssues.Program/TestData::get_B()
  IL_0011:  brtrue.s   IL_001f
  IL_0013:  ldarg.0
  IL_0014:  callvirt   instance string CoverletIssues.Program/TestData::get_C()
  IL_0019:  brtrue.s   IL_001f
  IL_001b:  ldc.i4.1
  IL_001c:  stloc.0
  IL_001d:  br.s       IL_0021
  IL_001f:  ldc.i4.0
  IL_0020:  stloc.0
  IL_0021:  ldloc.0
  IL_0022:  brfalse.s  IL_0026
  IL_0024:  ldnull
  IL_0025:  ret
  IL_0026:  ldstr      "Yay, stuff"
  IL_002b:  ret
} // end of method Program::GetDescription
```

**Expected Behavior**:

I was wondering if there is a reason for the 'branch, set, branch' pattern being used here?
The initial section contains four null checks each of which go to either IL_001b or IL_001f. These two locations set a local variable to 1 and 0 respectively and then branch based on this variable.

It seems to me that this is producing an unneceessary additional branch as the branches to IL_001b and IL_001f could, instead jump directly to IL_0024 and IL_0026 and produce the same result with one less conditional jump.

The reason I bring this up is that I think (unconfirmed) that this is affecting condition coverage metrics in Coverlet.

### LINKED ISSUE #59615: Suboptimal code for non-linear is-pattern expressions compared to switch
```cs
class C {
    string Worst(object i) {
        // uses a boolean flag for the result and a conditional jump
        return i is 1 or C(2) ? "aaa" : "bbb";
    }
    string Switch(object i) {
        // falls back to switch arms when possible; this info isn't available for `is` expressions
        return i switch { 1 or C(2) => "aaa", _ => "bbb" };
    }
    string Best(object i) {
        // ideally it should be lowered as `||` - still "linear" without using a flag
        return i is 1 || i is C(2) ? "aaa" : "bbb";
    }
    void Deconstruct(out int i) => throw null;
}
```
Relates to https://github.com/dotnet/roslyn/issues/45679

([sharplab.io](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwAIDCKDeBYAUCglBARgAYUB1AJwHsBnAFwAobgArAUwGMGUoBKLHkIiUAejEoArnQ50UEFMBo0ANhwgwUAM1UQA5jppUUDABYcUVOVNW9NAEwUouNGA6gMobiKpRspMAAHYVECBAB2Pj55YhRjdCYkQQB+FAAiCCz0lBAM4AL0gG5QggBfUqIyFABlAHdPLjMWdm5eASF8MPFJbV9VeWAILgBrUxoUOgaGJoUqMHk6iy0g+jooYHUi0zMoeVhtCb2YAHJ7ADdoPU3LQ5MAAz37lA4ADyDrOnW3OkqRSOiU0aZiwKDiCTQSUEAF4AHwZLIQdIAGhQAH0UHD8oUUGUSl1ypUSOQAEJyZisTg8PiCHAE0QSPgODSqVQATz4vDoZhoticwEsqhodQ41icEHk9zgcGeAFpJl5WRlVLANFQctMeVJeAhyIpdAY/oQAVAYmCUNLontEskUGlMtlctjgMVKhV6QgACwoAAi3B+DCoUh4LG1fBg7Rh8PMtDqKBgtlU+LKQA=))

### PR DESCRIPTION
**Pull request by alrz**
Follow-up to https://github.com/dotnet/roslyn/pull/68694 including a possible fix for https://github.com/dotnet/roslyn/pull/69615 at https://github.com/dotnet/roslyn/commit/9ed6e9d060cd9c2c868250c0d6cb0b2f7ec8f626. 

In the repro, I traced the difference between iterating over `List<T>` and `ImmutableArray<T>` where the former works correctly and the enumerator is captured in a field. For `List<T>` the loop is wrapped in a try-finally where the state is modified afterwards. Looking back at the VisitLoweredIsPatternExpression I noticed this could be a possible missing piece.

Closes #59615
Closes #55334

### CODE REVIEW

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs [hunk 1]
```diff
@@ -3041,7 +3041,9 @@ public override BoundNode VisitConditionalReceiver(BoundConditionalReceiver node
 
         public override BoundNode VisitLoweredIsPatternExpression(BoundLoweredIsPatternExpression node)
         {
+            var savedState = this.State.Clone();
             VisitStatements(node.Statements);
+            this.State = savedState;
             return null;
         }
```
Comment (alrz) [inline src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:3048]: My reasoning for the change is that the lowered statements should not affect the state for anything that follows, therefore we start with initial state after visiting those statements. I have no way of verifying it though except for passing the repro. @RikkiGibson @AlekseyTs

File: src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs [hunk 2]
```diff
@@ -1447,6 +1466,14 @@ public override BoundNode VisitSwitchDispatch(BoundSwitchDispatch node)
             return node.Update(boundExpression, node.Cases, node.DefaultLabel, node.LengthBasedStringSwitchDataOpt);
         }
 
+        public override BoundNode VisitLoweredIsPatternExpression(BoundLoweredIsPatternExpression node)
+        {
+            var statements = VisitSideEffects(node.Statements);
+            RecordBranch(node.WhenTrueLabel);
+            RecordBranch(node.WhenFalseLabel);
```
Comment (alrz) [inline src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs:1473]: I'm not sure what is the difference between RecordBranch and RecordLabel here and whether or not this is correct.

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs (hunk 1 above)
Comment (alrz) [reply src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs]: It looks like capture walker is the only walker that operates on the lowered bound tree and therefore seeing this node? Is it possible to always run this post-rewrite and assert that the results "match"? Just a way to exercise this code path more than usual.

File: src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs (hunk 2 above)
Comment (alrz) [reply src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs:1473]: After a closer look I realized in switch dispatch we're jumping _to_ those labels, but these are simply emitted as labels not branches, so I think these should use RecordLabel which I think is semantically the exact opposite of RecordBranch (switch PR already does this for arm labels).  Pushed a commit to test that out.

**Comment by AlekseyTs** [comment]
@alrz How was the first commit in this PR created?

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs [hunk 3]
```diff
@@ -6053,5 +6053,36 @@ public async Task M(object o)
...
+                using System;
+                using System.Threading.Tasks;
+                using System.Collections.Immutable;
+
+                await M(ImmutableArray.Create("a"));
+                Console.Write(1);
+
+                public partial class Program
+                {
+                    public static void M1(bool b) { }
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs:6070]: >public static void M1(bool b) { } [](http://example.com/codeflow?start=20&length=33)

Let's observe the value of ```b```.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs [hunk 4]
```diff
@@ -6053,5 +6053,36 @@ public async Task M(object o)
...
+
+        [ConditionalFact(typeof(CoreClrOnly))]
+        public void Repro()
+        {
+            var source = """
+                using System;
+                using System.Threading.Tasks;
+                using System.Collections.Immutable;
+
+                await M(ImmutableArray.Create("a"));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs:6065]: >await M(ImmutableArray.Create("a")); [](http://example.com/codeflow?start=16&length=36)

Let's add calls with values for which the pattern is supposed to produce `true`

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs [hunk 5]
```diff
@@ -6053,5 +6053,36 @@ public async Task M(object o)
             var comp = CSharpTestBase.CreateCompilation(source);
             comp.VerifyEmitDiagnostics();
         }
+
+        [ConditionalFact(typeof(CoreClrOnly))]
+        public void Repro()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs:6058]: >Repro [](http://example.com/codeflow?start=20&length=5)

We probably need a more meaningful name for the test. Also, could you provide details about the nature of the failure for this scenario?

File: src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs [hunk 6]
```diff
@@ -1447,6 +1466,14 @@ public override BoundNode VisitSwitchDispatch(BoundSwitchDispatch node)
             return node.Update(boundExpression, node.Cases, node.DefaultLabel, node.LengthBasedStringSwitchDataOpt);
         }
 
+        public override BoundNode VisitLoweredIsPatternExpression(BoundLoweredIsPatternExpression node)
+        {
+            var statements = VisitSideEffects(node.Statements);
+            RecordLabel(node.WhenTrueLabel);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs:1472]: >RecordLabel [](http://example.com/codeflow?start=12&length=11)

Is this change made in an attempt to fix the "Repro" test?

Comment (alrz) [reply src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs:1472]: No, only the change referenced in PR description is related to that issue.
(I've added some context on this one a few comments earlier.)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs (hunk 5 above)
Comment (alrz) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs]: In the presence of pattern-matching, the capture walker did not consider the enumerator temp as a capture and it remained a local. Also related: https://github.com/dotnet/roslyn/pull/72273#discussion_r1514005305

**Comment by alrz** [comment]
> @alrz How was the first commit in this PR created?

That's the same squash I made to open https://github.com/dotnet/roslyn/pull/69194 before the original PR got merged, but no comments were added after that.

**Comment by AlekseyTs** [comment]
> > @alrz How was the first commit in this PR created?
> 
> That's the same squash I made to open #69194 before the original PR got merged, but no commits were added after that.

Could you please instead replace it with revert of revert of the original merged PR?

**Comment by alrz** [comment]
>Could you please instead replace it with revert of revert of the original merged PR? 

Done. Let me know if the rest should be squashed if you intend to keep the revert in the merge.

**Comment by alrz** [comment]
image
That's not helpful. I don't know since when git try to use "reapply" when reverting a revert.

**Comment by AlekseyTs** [comment]
> > Could you please instead replace it with revert of revert of the original merged PR?
 
> Done. 

Thanks!

> Let me know if the rest should be squashed if you intend to keep the revert in the merge.

No. We will squash while merging this PR

**Comment by alrz** [comment]
Sure, thought you wanted to do that separately. btw I made the rebase branch to rebase the rest of commits but ended up using `--onto HEAD` and resetting to the original for push. A little misleading.

**Comment by AlekseyTs** [comment]
>  thought you wanted to do that separately

I wanted to have a known/reviewed state of the first commit.

File: src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs (hunk 6 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs:1472]: This change makes sense to me. Effectively we have  implicit label statements for our labels and when we visit a ```BoundLabelStatement```, we call ```RecordLabel```

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs (hunk 5 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs]: >> Also, could you provide details about the nature of the failure for this scenario?

> In the presence of pattern-matching, the capture walker did not consider the enumerator temp as a capture and it remained a local. 

And how does this affect the test scenario? Does the test crash (where?), asserts (where?), exhibits unexpected behavior at runtime (what behavior), something else?

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs [hunk 7]
```diff
@@ -3039,6 +3039,14 @@ public override BoundNode VisitConditionalReceiver(BoundConditionalReceiver node
...
 
+        public override BoundNode VisitLoweredIsPatternExpression(BoundLoweredIsPatternExpression node)
+        {
+            var savedState = this.State.Clone();
+            VisitStatements(node.Statements);
+            SetState(savedState);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:3046]: >SetState(savedState); [](http://example.com/codeflow?start=12&length=21)

This doesn't look right. I think that here we also should act as though we have two implicit label statements and an implicit goto to the end. I am thinking about code doing something like:
```
VisitLabel(node.WhenTrueLabel);
var stateWhenTrue = this.State.Clone();
SetUnreachable();
VisitLabel(node.WhenFalseLabel);
Join(ref this.State, ref stateWhenTrue);
```

**Comment by AlekseyTs** [comment]
Done with review pass (commit 7)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs (hunk 5 above)
Comment (alrz) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs]: Since the enumerator is a local it's left unassigned when the continuation runs at runtime, leading to an NRE.

image

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs (hunk 7 above)
Comment (alrz) [reply src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:3046]: >we have two implicit label statements and an implicit goto to the end

That doesn't quite reflect the final flow,

https://github.com/dotnet/roslyn/blob/283061a27a5994d90190bb98e501f992399da4c0/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs#L370-L377

Also there's no such overload for `VisitLabel(node.WhenTrueLabel);` we do have `VisitLabel(LabelSymbol, BoundStatement)` but we're working with an expression and I don't think you meant to change that method?

Comment (alrz) [reply src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:3046]: Sorry I misread "to the end" as "at the end", but still I'm not sure what exactly should VisitLabel do.

Comment (alrz) [reply src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:3046]: Another question, since we're working with constants and known labels, what `SetUnreachable` signifies here? Handling of the labels should supposedly cover the unreachable state, in case, for example, there were no jumps to either labels.

Comment (alrz) [reply src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:3046]: Final note, I think this method should be an inlined version of the same impl for switch in the other PR.
```cs
return e is p;
// same as the following for this analysis
return e switch { p => true, _ => false };
```
Not saying that either of these are correct at this time, but they should definitely match. I believe this can help to verify the implementation in either PR.

https://github.com/dotnet/roslyn/blob/755afc6c7fb4217da5d2dc1b4f712280151bc3c1/src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass_Switch.cs#L185-L200

First off, notice we append binding statements to `LoweredIs.Statements`, but for switch the state is reset beforehand. 

For reference, at the moment `LoweredSwitchArm.Statements` contains:

1. lowered where clause including the exit jump if it evaluates to false, if any
2. binding statements, if any (this is the collection returned from BuilderForSection for both rewriters)
3. switch arm label statement
4. spilled value produced in spiller, if any

And finally the the value is emitted which is just a constant for is-expressions.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:3046]: > Also there's no such overload for `VisitLabel(node.WhenTrueLabel);` we do have `VisitLabel(LabelSymbol, BoundStatement)` but we're working with an expression and I don't think you meant to change that method?

This is how that local function should look like in my opinion:
```
        void visitLabel(LabelSymbol label)
        {
            ResolveBranches(label, null);
            var state = LabelState(label);
            Join(ref this.State, ref state);
            _labels[label] = this.State.Clone();
        }
```

> Another question, since we're working with constants and known labels, what `SetUnreachable`/`Join` signify here? 

`SetUnreachable` signifies that ```node.WhenFalseLabel``` is not reachable in case of a jump to ```node.WhenTrueLabel```.

`Join` signifies that control flow merges at the end, see what we do in ```EmitLoweredIsPatternExpression```. 

> Final note, I think this method should be an inlined version of the same impl for switch in the other PR which can be seen as a generalized `is` expression:

Let's focus on the simplified version of the problem that we have at hand, and get it right first. We will deal with problems in other PRs when we get to other PRs.

**Comment by AlekseyTs** [comment]
>             Debug.Assert(!this.IsConditionalState);

According to ```BoundLoweredIsPatternExpression.Validate```, there could be a ```BoundGotoStatement``` among ```BoundLoweredIsPatternExpression.Statements```. Is it possible to violate this assumption (```Debug.Assert(!this.IsConditionalState);```) for new usages of the node? Perhaps, when the pattern is involved in a more complex logical expression?

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:3244 in 283061a. [](commit_id = 283061a27a5994d90190bb98e501f992399da4c0, deletion_comment = False)

**Comment by alrz** [comment]
> > ```
> >         Debug.Assert(!this.IsConditionalState);
> > ```
> 
> According to `BoundLoweredIsPatternExpression.Validate`, there could be a `BoundGotoStatement` among `BoundLoweredIsPatternExpression.Statements`. Is it possible to violate this assumption (`Debug.Assert(!this.IsConditionalState);`) for new usages of the node? Perhaps, when the pattern is involved in a more complex logical expression?
> 
> Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:3244 in [283061a](https://github.com/dotnet/roslyn/commit/283061a27a5994d90190bb98e501f992399da4c0). [](commit_id = [283061a](https://github.com/dotnet/roslyn/commit/283061a27a5994d90190bb98e501f992399da4c0), deletion_comment = False)


`Statements` only branches out to leaf nodes and when the decision is complete,  it's also asserted that the stack stays the same when entering and exiting this block. I don't think there's any other way to reach there with a conditional state.

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs (hunk 7 above)
Comment (alrz) [reply src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:3046]: >This is how that local function should look

Thanks, didn't know the statement parameter is completely optional.

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs [hunk 8]
```diff
@@ -3039,6 +3039,12 @@ public override BoundNode VisitConditionalReceiver(BoundConditionalReceiver node
...
 
+        public override BoundNode VisitLoweredIsPatternExpression(BoundLoweredIsPatternExpression node)
+        {
+            VisitStatements(node.Statements);
+            return null;
+        }
+
         public override BoundNode VisitComplexConditionalReceiver(BoundComplexConditionalReceiver node)
         {
             var savedState = this.State.Clone();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:3062]: >VisitStatements [](http://example.com/codeflow?start=12&length=15)

We do need to visit statements though

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 9), assuming CI is passing

**Comment by AlekseyTs** [comment]
@jcouv, @dotnet/roslyn-compiler For the second review.

**Comment by AlekseyTs** [comment]
@jcouv, @dotnet/roslyn-compiler For the second review.

File: src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs [hunk 9]
```diff
@@ -844,7 +884,14 @@ private void EmitSequenceExpression(BoundSequence sequence, bool used)
             Debug.Assert(sequence.Value.Kind != BoundKind.TypeExpression || !used);
             if (sequence.Value.Kind != BoundKind.TypeExpression)
             {
-                EmitExpression(sequence.Value, used);
+                if (used && sequence.Type.SpecialType == SpecialType.System_Boolean)
+                {
+                    EmitCondExpr(sequence.Value, sense: sense);
+                }
+                else
+                {
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:892]: Can we assert that `sense == true` in this branch?

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 9). Only one minor question/suggestion

File: src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs (hunk 9 above)
Comment (alrz) [reply src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:894]: Added an assertion to the same effect.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 12)

File: src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs (hunk 9 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:894]: We can get into the alternative branch with `!used` and a boolean type. The added assertion doesn't cover `sense` in that scenario.

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 12). Still just a nit on assertion

**Comment by AlekseyTs** [comment]
@alrz Thanks for the contribution
