### PR TITLE
Fix intercepting a struct or enum base method

### LINKED ISSUE #70841: Invalid IL generated for intercepted callsite
**Version Used**: 

.NET SDK 8.0.100

**Steps to Reproduce**:

1.  `dotnet new console`
2.  Copy & paste attached `Program.cs` (adjust full path to match your system)
3. Add `<InterceptorsPreviewNamespaces>$(InterceptorsPreviewNamespaces);MyInterceptors</InterceptorsPreviewNamespaces` to the .csproj file
4. `dotnet run`

**Expected Behavior**:

Program runs to completion

**Actual Behavior**:

InvalidProgramException. 

The problem is that Roslyn generates invalid IL 
```
    .locals init (valuetype MyEnum V_0)
    IL_0000:  ldc.i4.1
    IL_0001:  stloc.0
    IL_0002:  ldloc.0 <- MyEnum is not assignable to Enum in IL!
    IL_0003:  call       string MyInterceptors.Interceptors::OtherToString(class [System.Runtime]System.Enum)
```

#### Program.cs
```csharp
using System.Runtime.CompilerServices;

var value = MyEnum.Second;
Console.WriteLine(value.ToString());

public enum MyEnum
{
    First,
    Second,
}

namespace MyInterceptors
{
    public static class Interceptors
    {
        [InterceptsLocation(@"C:\repro\Program.cs", line: 4, column: 25)]
        public static string OtherToString(this System.Enum value)
            => "Wrong Value" + value;
    }
}

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(string filePath, int line, int column)
        {
        }
    }
}
```

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #70841

When the original method is an instance method and interceptor is an extension, we have to adjust the receiver argument to pass it for the extension 'this' parameter. Receiver emit strategies such as 'ConstrainedCallVirt' are not available for an extension 'this' parameter, so we may need to insert an additional (generally boxing) conversion, to make the receiver argument actually match the parameter type.

See https://github.com/dotnet/roslyn/blob/main/docs/features/interceptors.md#signature-matching
> When an interceptable instance method is compared to a static interceptor method (including a classic extension method), we use the method as if it is an extension in reduced form for comparison.

In test `InterceptorEnumBaseMethod`, for example, we lower the call `value.ToString()` as if it were calling `OtherToString` in reduced form. In that case, `value` must be boxed.

### CODE REVIEW

**Comment by RikkiGibson** [comment]
@cston @jcouv Please take a look when you have the chance.

File: src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs [hunk 1]
```diff
@@ -3423,6 +3423,36 @@ static class D
...
+                [InterceptsLocation("Program.cs", 10, 23)]
+                public static void Interceptor(this in Program x) => Console.Write("Intercepted");
+            }
+            """;
+        var comp = CreateCompilation(new[] { (source, "Program.cs"), s_attributesSource }, parseOptions: RegularWithInterceptors);
+        comp.VerifyEmitDiagnostics(
+            // Program.cs(16,6): error CS9148: Interceptor must have a 'this' parameter matching parameter 'ref Program this' on 'Program.InterceptableMethod()'.
+            //     [InterceptsLocation("Program.cs", 10, 23)]
+            Diagnostic(ErrorCode.ERR_InterceptorMustHaveMatchingThisParameter, @"InterceptsLocation(""Program.cs"", 10, 23)").WithArguments("ref Program this", "Program.InterceptableMethod()").WithLocation(16, 6));
+    }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs:3454]: >} [](http://example.com/codeflow?start=4&length=1)

Consider testing `readonly void InterceptableMethod()` with `static void Interceptor(this in Program)`, `static void Interceptor(this ref readonly Program)`, and `static void Interceptor(this ref Program)`.

File: src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs [hunk 2]
```diff
@@ -4827,4 +4857,201 @@ static class D
...
+    public void InterceptorStructConstrainedInterfaceMethod()
+    {
+        var program = ("""
+            using System;
+
+            C.M(default(MyStruct));
+
+            class C
+            {
+                public static void M<T>(T t) where T : struct, I
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs:4997]: >struct, [](http://example.com/codeflow?start=55&length=7)

Consider testing without the `struct` constraint as well.

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs (hunk 2 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs:4997]: Or alternatively, perhaps remove all constraints and test a call to a virtual method on `object`.
```csharp
static void M<T>(T t)
{
    t.ToString();
}
```

**Comment by RikkiGibson** [comment]
@jcouv for second review

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 2)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs [hunk 3]
```diff
@@ -272,7 +272,11 @@ private void EmbedIfNeedTo(BoundExpression receiver, ImmutableArray<PropertySymb
             if (needToReduce)
             {
                 Debug.Assert(methodThisParameter is not null);
-                arguments = arguments.Insert(0, receiverOpt!);
+                Debug.Assert(receiverOpt?.Type is not null);
+                Debug.Assert(receiverOpt.Type.Equals(interceptor.Parameters[0].Type, TypeCompareKind.AllIgnoreOptions)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs:276]: I can try to add a clarifying comment here in a follow-up PR.
