### PR TITLE
Fix IBinaryOperatorExpression, IUnaryOperatorExpression and IIncrementExpression

### LINKED ISSUE #8114: IBinaryOperatorExpression.BinaryOperatorKind property getter can throw
I encountered this bug in IOperation while implementing CA2242, TestForNaNCorrectly.
 
My analyzer registers an action for `OperatorKind.BinaryOperatorExpression`. The action checks the operation’s `BinaryOperationKind` property to see if it’s one of the floating point comparison operators. If so, it checks to see whether either operand has a `ConstantValue` of `NaN`:
 
```C#
public override void Initialize(AnalysisContext analysisContext)
{
    analysisContext.RegisterOperationAction(
        operationAnalysisContext =>
        {
            var binaryOperatorExpression = (IBinaryOperatorExpression)operationAnalysisContext.Operation;
            if (!s_comparisonOperators.Contains(binaryOperatorExpression.BinaryOperationKind))
            {
                return;
            }
 
            if (IsNan(binaryOperatorExpression.Left) || IsNan(binaryOperatorExpression.Right))
            {
                operationAnalysisContext.ReportDiagnostic(
                   binaryOperatorExpression.Syntax.CreateDiagnostic(Rule));
            }
        },
        OperationKind.BinaryOperatorExpression);
}
 ```
 
The analyzer works correctly, except that the `BinaryOperatorKind` property getter throws an exception when given this test code:
 
```C#
[Fact]
public void CSharpNoDiagnosticForComparisonWithBadExpression()
{
    var code = @"
public class A
{
    public bool Compare(float f)
    {
        return f == float.Nan; // Misspelled; should be "NaN".
    }
}
";
    VerifyCSharp(code);
}
 ```

Property getters aren’t supposed to throw exceptions (with a few exceptions, see [CA1065](https://msdn.microsoft.com/en-us/library/bb386039.aspx)).
 
There’s really no workaround for this; my analyzer has to evaluate that property, and there’s no way to tell in advance if it will throw.

### PR DESCRIPTION
**Pull request by genlu**
1. Add `Invalid` to `SimpleUnaryOperationKind`, `UnaryOperandKind`, `UnaryOperationKind`,
   `SimpleBinaryOperationKind`, `BinaryOperandsKind` and `BinaryOperationKind`.
2. Make `BinaryOperationKind`/`UnaryOperationKind` properties return Invalid kind instead of throwing
   exception when handling code with errors.

This fixes #8114 .

FYI @JohnHamby @srivatsn @dotnet/roslyn-interactive @lgolding

### CODE REVIEW

File: src/Compilers/CSharp/Portable/BoundTree/Expression.cs [hunk 1]
```diff
@@ -2078,7 +2078,7 @@ internal static BinaryOperationKind DeriveBinaryOperationKind(UnaryOperationKind
                     return BinaryOperationKind.DynamicSubtract;
 
                 default:
-                    throw ExceptionUtilities.UnexpectedValue(incrementKind);
+                    return BinaryOperationKind.None;
```
Comment (JohnHamby) [inline src/Compilers/CSharp/Portable/BoundTree/Expression.cs]: Hmmm.... Since this value will actually occur, maybe it should be renamed "Invalid" or some such.

**Comment by JohnHamby** [comment]
I sign off.

At some point in the past, someone talked me into replacing returns of None with throws, because we believed that the default cases were unreachable. We didn't consider the implications of semantically-malformed input.

File: src/Compilers/CSharp/Portable/BoundTree/Expression.cs (hunk 1 above)
Comment (genlu) [inline src/Compilers/CSharp/Portable/BoundTree/Expression.cs]: Maybe I should add `invalid` at the end of each enum and leave `None` as is?

Comment (JohnHamby) [inline src/Compilers/CSharp/Portable/BoundTree/Expression.cs]: If we were to add Invalid, its value would need to be 0, for reasons that will become clear when you see my upcoming API review PR. Maybe leave it as None for today.

Comment (genlu) [inline src/Compilers/CSharp/Portable/BoundTree/Expression.cs]: @JohnHamby I just did a quick search for references to `BinaryOperationKind.None` in Roslyn, it turns out it has been used in several places. For example
```
BasicCodeAnalysis\BoundTree\Expression.vb - (95, 44) : Return BinaryOperationKind.None
```

It seems they all represent some kind of error state and probably should be replaced with the newly added `BinaryOperationKind.Invalid`, what do you think?

Comment (genlu) [inline src/Compilers/CSharp/Portable/BoundTree/Expression.cs]: I found an example of error value as the last entry in enum though. 
```
Microsoft.CodeAnalysis.VisualBasic.UnaryOperatorKind.Error
```

And FxCop suggests that the none value should indicate that no values have been set in the enum, which I think is not the case for Invalid. But yea, I can leave it as None today :)

**Comment by genlu** [comment]
@JohnHamby I rewrote this and added `Invalid` value to all the related enums. Could you please take a look? I hope the changes I made make sense :)

**Comment by JohnHamby** [comment]
I suggest giving all of the simple/operand Invalid constants a value of either 0xff00 or 0xff, so that the combined Invalid values are all 0xffff. This would make it almost inconceivable that we could run out of valid values.

Otherwise, I sign off again.

**Comment by genlu** [comment]
Fixed. Also, any thoughts RE: one of my previous question?

> I just did a quick search for references to BinaryOperationKind.None in Roslyn, it turns out it has been used in several places. For example
> `CodeAnalysis\Compilation\Expression.cs - (80, 50) : return Semantics.BinaryOperationKind.None;`
> It seems they all represent some kind of error state and probably should be replaced with the newly added BinaryOperationKind.Invalid, what do you think?

**Comment by JohnHamby** [comment]
Yes, now that Invalid exists, it's a better value to use for such cases than None. Thanks!

**Comment by genlu** [comment]
For the record, in the following 2 cases, `BinaryOperationKind.None` is still used as return value of `ISingleValueCaseClause.Equality` property, which I think is more accurate.
- `default` case clause in C#
- `Case Else` clause in VB
