### PR TITLE
Don't offer '??=' for pointer types

### LINKED ISSUE #62473: IDE0074 is offered for pointers
**Version Used**: 

**Steps to Reproduce**:
```C#
unsafe class Program
{
    private static void Main()
    {
        byte* ptr = null;
        if (ptr is null)
        {
            ptr = Get();
        }
    }

    static byte* Get() => null;
}
``` 

**Expected Behavior**:
IDE0074 isn't offered.

**Actual Behavior**:
IDE0074 is offered and the fixer generates invalid code:
```C#
unsafe class Program
{
    private static void Main()
    {
        byte* ptr = null;
        ptr ??= Get();
    }

    static byte* Get() => null;
}
```
because for whatever reason `??` and `??=` don't work with pointers:
```
Error CS0019 Operator '??=' cannot be applied to operands of type 'byte*' and 'byte*'
```

cc: @CyrusNajmabadi

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #62473

### CODE REVIEW

File: src/Analyzers/CSharp/Tests/UseCompoundAssignment/UseCompoundCoalesceAssignmentTests.cs [hunk 1]
```diff
@@ -694,5 +694,49 @@ static void Main(object o)
...
+
+        [WorkItem(62473, "https://github.com/dotnet/roslyn/issues/62473")]
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseCompoundAssignment)]
+        public async Task TestPointerCannotUseCoalesceAssignment()
+        {
+            // The purpose of this test is to keep track of whether the language
+            // allows ??= for pointers in future. It should be kept in 'Preview'.
+            // If the test failed because language added support and this is no longer
+            // an error. The behavior for test 'TestPointer' below should be updated as well to suggest ??=
+            // Note that, when ??= is supported for pointers, the analyzer should check the language version which supports it.
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/UseCompoundAssignment/UseCompoundCoalesceAssignmentTests.cs:706]: nifty idea!
