### PR TITLE
Do not offer to create p2p references if the project system will not allow those references.

### LINKED ISSUE #8771: [project reference add using] Reference desktop class library from UWP project crashes codefix
1. Create UWP app
2. Create Desktop class library `Class1`
3. Add code that will reference `var a = new Class1();`

image

**Expected**: Add Using is not offered because it is invalid to referece Desktop from UWP

**Actual**: Codefix crashes with following stack
```
User canceled out of save dialog (Exception from HRESULT: 0x8004000C (OLE_E_PROMPTSAVECANCELLED))
 at VSLangProj.References.AddProject(Project pProject)
 at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyProjectReferenceAdded(ProjectId projectId, ProjectReference projectReference)
 at Microsoft.CodeAnalysis.Workspace.ApplyProjectChanges(ProjectChanges projectChanges)
 at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution)
 at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution)
 at Microsoft.CodeAnalysis.CodeActions.ApplyChangesOperation.Apply(Workspace workspace, CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace, Document fromDocument, String title, Solution oldSolution, Solution updatedSolution, List`1 operationsList, CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.Apply(Workspace workspace, Document fromDocument, IEnumerable`1 operations, String title, CancellationToken cancellationToken)
 at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<InvokeWorkerAsync>d__18.MoveNext() --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
 at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass17_0.<<InvokeCoreAsync>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
 at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.<PerformActionAsync>d__2.MoveNext()
```

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes #8771, 	#8777, #8779, #8785

Note: this resurrects the work to make it so that code actoins can do a final applicability check on the UI thread. This is necessary because the APIs we need to call are COM STA affinitized. Once we move to CPS we should actually be able to safely call this stuff on the background thread and we can remove these internal APIs.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
tagging @srivatsn @heejaechang  and @dotnet/roslyn-ide 

Sri/Heejae,

This PR resurrects the concept of "Do one final viability on the UI thread for code actions" which we looked at in:
https://github.com/dotnet/roslyn/pull/7882

This was necessary because we can only check for p2p project reference viability on the UI thread (yaay STA project system).  Ideally we will get rid of this once we get onto CPS and can do these checks from any thread.

In the meantime, this is necessary for the RC because we're getting crashes when we attempt to add p2p references that the project system eventually considers invalid. We offer the fix to the user and then the fix causes a crash.  We don't even want to offer the fix in the first place.

Thanks!

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-ide  Please review asap.  I'd like to get this into stabilization/RC.

File: src/EditorFeatures/Core/Implementation/Suggestions/SuggestedActionsSourceProvider.cs [hunk 1]
```diff
@@ -245,16 +247,70 @@ private SuggestedActionSet InlineActions(SuggestedActionSet actionSet)
...
+                        ? collection
+                        : new CodeFixCollection(collection.Provider, collection.TextSpan, applicableFixes, collection.FixAllContext);
+            }
+
+            private bool IsApplicable(CodeAction action, Workspace workspace)
+            {
+                if (!action.PerformFinalApplicabilityCheck)
+                {
+                    // If we don't even need to perform the final applicability check,
+                    // then the code actoin is applicable.
```
Comment (Pilchie) [inline src/EditorFeatures/Core/Implementation/Suggestions/SuggestedActionsSourceProvider.cs]: Spelling - `action`

File: src/Workspaces/Core/Portable/Workspace/Workspace.cs [hunk 2]
```diff
@@ -879,6 +879,15 @@ public virtual bool CanApplyChange(ApplyChangesKind feature)
         }
 
         /// <summary>
+        /// Returns <code>true</code> if a reference to referencedProject can be added to 
+        /// referencingProject.  <code>false</code> otherwise.
+        /// </summary>
+        internal virtual bool CanAddProjectReference(ProjectId referencingProject, ProjectId referencedProject)
+        {
+            return false;
```
Comment (Pilchie) [inline src/Workspaces/Core/Portable/Workspace/Workspace.cs]: Is this the right default?

**Comment by Pilchie** [comment]
:+1:, though I'd appreciate @davkean looking at the compatibility check code closely.

**Comment by jmarolf** [comment]
Verified that this fixes the following bugs:

Name | Issue Number
--- | ---
[project reference add using] Reference desktop class library from UWP project crashes codefix | #8771
[project reference add using] Reference desktop class library from Website project crashes codefix | #8777
[project reference add using] Referencing ASP.NET Core 1.0 from ASP.NET 4.6 WebForms project crashes codefix | #8779
[project reference add using] Reference desktop class library from Phone 8 project crashes codefix | #8785

**Comment by jmarolf** [comment]
Test Signoff

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Comment by CyrusNajmabadi** [comment]
Thanks jon!

File: src/Workspaces/Core/Portable/Workspace/Workspace.cs (hunk 2 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Workspace/Workspace.cs]: Looking at the rest of the workspace, it looks like this is what we generally do in the root workspace.

File: src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs [hunk 3]
```diff
@@ -22,11 +22,12 @@
 
 namespace Microsoft.CodeAnalysis.CodeFixes
 {
+    using Editor.Shared.Utilities;
     using DiagnosticId = String;
     using LanguageKind = String;
 
     [Export(typeof(ICodeFixService)), Shared]
-    internal partial class CodeFixService : ICodeFixService
+    internal partial class CodeFixService : ForegroundThreadAffinitizedObject, ICodeFixService
```
Comment (dpoeschl) [inline src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs]: Do we care that this isn't portable anymore?

Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs]: No.  The only consumers of this API are not even in the portable layer.

**Comment by CyrusNajmabadi** [comment]
I am super confued about all these errors.  I don't think they were caused by my change.

**Comment by brettfo** [comment]
@CyrusNajmabadi: the 12 windows unit test failures are due to #8807 and unrelated to your change.

**Comment by davkean** [comment]
The unit test failures are known and have been disabled. For the other failures, tag @natidea please investgate.

**Comment by natidea** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please
@dotnet-bot retest prtest/win/dbg/unit64 please
// Retest reason: Failure tracked by #8807 Tests Disabled by #8844

**Comment by CyrusNajmabadi** [comment]
@natidea do you know anything about these failures: 
BasicVenus.Script Block
CSharpExpressionEvaluator.Validate Locals Window
    CSharpGoToImplementation.Go To Implementation opens in a provisional tab if document wasn't already open

These seem unrelated to anything i was doing.

**Comment by natidea** [comment]
@dotnet-bot retest prtest/win/vsi/p1 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p1/281/
@dotnet-bot retest prtest/win/vsi/p2 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/280/
// Retest reason: Some of the failures may be related to #8725

**Comment by davkean** [comment]
@natidea Please get bugs tracking the new failures, if they end up being the same cause we will dup them.

**Comment by CyrusNajmabadi** [comment]
@davkean Please take a look when you have a moment.  Thanks!

**Comment by CyrusNajmabadi** [comment]
Tagging @MattGertz .  For stabilization.

This fixes when trying to add a p2p reference between two incompatiable projects.  All four bugs are the same issue, but they exemplify that all the differnet ways a user could end up in this state.

**Comment by CyrusNajmabadi** [comment]
tagging @ManishJayaswal  and @Pilchie

**Comment by CyrusNajmabadi** [comment]
actually, sorry for jumping the gun.  I'd like Dav Kean to sign off first before going for ask mode approval.

**Comment by CyrusNajmabadi** [comment]
actually, sorry for jumping the gun. I'd like @davkean to sign off first before going for ask mode approval.

**Comment by ManishJayaswal** [comment]
ok. @davkean let me know when you sign off on this CR.

File: src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs [hunk 4]
```diff
@@ -407,12 +409,28 @@ public CodeFixProvider GetSuppressionFixer(string language, IEnumerable<string>
...
-                    continue;
-                }
+                    if (!fix.Action.PerformFinalApplicabilityCheck)
+                    {
+                        return true;
+                    }
 
-                return true;
+                    // Have to see if this fix is still applicable.  Jump to the foreground thread
+                    // to make that check.
```
Comment (davkean) [inline src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs]: Is this the typical way we jump to the foreground? I thought most of VS use JoinableTaskFactory to avoid deadlocks?

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs [hunk 5]
```diff
@@ -1047,6 +1047,66 @@ internal void OnAdditionalDocumentTextUpdatedOnDisk(DocumentId documentId)
...
+            if (!TryGetHierarchy(referencingProject, out referencingHierarchy) ||
+                !TryGetHierarchy(referencedProject, out referencedHierarchy))
+            {
+                return false;
+            }
+
+            var referencingProjectFlavor3 = referencingHierarchy as IVsProjectFlavorReferences3;
+            var referencedProjectFlavor3 = referencedHierarchy as IVsProjectFlavorReferences3;
+
+            if (referencingProjectFlavor3 != null && referencedProjectFlavor3 != null)
```
Comment (davkean) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs]: This doesn't look right. If the referencing project (say portable) implements IVsProjectFlavorReferences3, but the referenced (say C++) project doesn't - you're basically skipping all portable checks here and falling back to the default P2P matrix. And vice versa.

Comment (davkean) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs]: You should be verifying at least one side even if the other doesn't implement it.

File: src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs (hunk 4 above)
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs]: Discussed offline with @davkean  and @jasonmalinowski .  This is the pattern that Roslyn currently uses.  We never use JTF.  AFAICT, we try to make sure we never pump.  Instead, we have a strict rule that if UI thread is blocking on the results of a background call, that that background call cannot wait on the UI thread.

In this case, the codepath that runs through this never does any blocking on the UI thread.  As such, it's safe for the BG thread to make a BG-FG-BG switch.

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs (hunk 5 above)
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs]: Ok.  I can def do that.  Note though that we should never get C++ projects.  These are always Roslyn projects that we're dealing with.  But even so, i'll rework the code to properly handle this issue.

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Comment by CyrusNajmabadi** [comment]
@davkean I've pushed out an update with the logic i think you're asking for.

**Comment by davkean** [comment]
LGTM.

**Comment by CyrusNajmabadi** [comment]
Pinging @ManishJayaswal and @Pilchie  again.  DavKean has signed off, and we'd like to get this into Update2.

Note: if you sign off, he'll be handling the merge.

**Comment by CyrusNajmabadi** [comment]
@davkean  This is ready to go in.  Merge at your on convenience.
