### PR TITLE
Include file-local name prefix in names of explicit interface implementations

### LINKED ISSUE #68219: Partial class implementing identically named file interfaces with identically named members should not confuse them
**Version Used**:  .NET 7

(Before you think this is a crazy scenario, the use case is generated code.)

**Steps to Reproduce**:
(Unfortunately, this can't be demonstrated in a gist, because it requires multiple files.)
1. In one file:
```
file interface IFoo
{
    IReadOnlyDictionary<int, string> Bar { get; }
}

internal partial class Foo : IFoo
{
    private readonly Dictionary<int, string> _bar = new() { { 1, "one" }, { 2, "two" } };
    IReadOnlyDictionary<int, string> IFoo.Bar => _bar;
}
```
2. In a second file:
```
file interface IFoo
{
    IReadOnlyDictionary<int, string> Bar { get; }
}

internal partial class Foo : IFoo
{
    IReadOnlyDictionary<int, string> IFoo.Bar => _bar;
}
```
3. After getting no complaints in Visual Studio, compile.

**Diagnostic Id**: CS0102

4. Change second file:
```
file interface IFoo
{
    IReadOnlyDictionary<int, string> Bar { get; }
}

internal partial class Foo : IFoo
{
}
```
(`Foo` needs to implement `IFoo` because, elsewhere in the file, an instance of `Foo` will be passed to a method taking `IFoo`.)

5. Visual Studio complains that `Foo` doesn't implement `IFoo`.

6.  Compile.

**Diagnostic Id**: CS0535

**Expected Behavior**: The compiler recognizes that `IFoo.Bar` in the part of `Foo` in one file is different from `IFoo.Bar` in a different part because each `IFoo` is file scoped and is therefore a different type. Seeing these as different types, the compiler does not emit CS0102 and compiles the code.

**Actual Behavior**: The compiler confuses file scoped types with the same name and emits CS0102 and doesn't compile the code.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #68219

### CODE REVIEW

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler for review of a fairly small bug fix

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/FileModifierTests.cs [hunk 1]
```diff
@@ -4022,4 +4083,419 @@ public void SyntaxTreeAlreadyPresent()
...
+            }
+
+            internal partial class C : FI
+            {
+                int FI.Bar => 2;
+                public void Use2() => Console.Write(((FI)this).Bar);
+            }
+            """;
+
+        var verifier = CompileAndVerify(new[] { (source0, "F0.cs"), (source1, "F1.cs"), (source2, "F2.cs") }, verify: Verification.Skipped, expectedOutput: "12");
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/FileModifierTests.cs:4281]: >verify: Verification.Skipped [](http://example.com/codeflow?start=110&length=28)

Why is IL verification skipped in the newly added tests (but none of the previous file-type tests did)?

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 2) with a minor test question

**Comment by jcouv** [comment]
@dotnet/roslyn-compiler for second review. Thanks

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/FileModifierTests.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/Source/FileModifierTests.cs:4281]: ILVerify incorrectly believes duplicate members are present in the tests where the code is executed.

Comment (jcouv) [reply src/Compilers/CSharp/Test/Symbol/Symbols/Source/FileModifierTests.cs:4281]: Could you produce an IL/ildasm example for this? How is it possible given our current naming convention for file-types?
If we can confirm this is an ILVerify issue, then we should file an issue on the runtime repo.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/Source/FileModifierTests.cs:4281]: I think the issue is the name+parameter list of each member is exactly the same.

Perhaps somewhere along the way the member should be adjusted to prefix with the metadata name of the file type, instead of its source name.

**Comment by RikkiGibson** [comment]
I'll try and see if I can resolve the duplicate member issue the verifier is complaining about. If it's not too difficult, I will update this PR to just do it.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs [hunk 2]
```diff
@@ -1948,10 +1948,23 @@ private void CheckMemberNameConflicts(BindingDiagnosticBag diagnostics)
...
+                                var lastExplicitImplementations = lastSym.GetExplicitInterfaceImplementations();
+
+                                // Source symbols can only explicitly implement at most 1 member
+                                Debug.Assert(explicitImplementations.Length is 0 or 1 && explicitImplementations.Length == lastExplicitImplementations.Length);
+
+                                // Sometimes two non-overloadable members can have exactly the same source name, but be explicit implementations of different members.
+                                // For example, when explicitly implementing members of file-local interfaces.
+                                // We don't consider such members to be duplicates.
+                                if (explicitImplementations.Length == 0
+                                    || explicitImplementations[0].Equals(lastExplicitImplementations[0], TypeCompareKind.AllIgnoreOptions))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:1961]: This looks like a "voodoo magic" to me. It doesn't look appropriate to suppress the error based on the logic.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:1961]: Note that the similar situation (when names in source match) can be created with regular types. In this case, the names for explicit interface implementations are made by compiler unique:
```
    [Fact, WorkItem("[https://github.com/dotnet/roslyn/issues/68219](https://github.com/dotnet/roslyn/issues/68219)")]
    public void PartialExplicitImplementation_05_()
    {
        var source0 = """
            var c = new C();
            c.Use1();
            c.Use2();
            """;

        var source1 = """
            using System;
            using NS1;
            
            namespace NS1
            {
                interface FI
                {
                    int Bar { get; }
                }
            }

            internal partial class C : FI
            {
                int FI.Bar => 1;
                public void Use1() => Console.Write(((FI)this).Bar);
            }
            """;

        var source2 = """
            using System;
            using NS2;

            namespace NS2
            {
                interface FI
                {
                    int Bar { get; }
                }
            }
            
            internal partial class C : FI
            {
                int FI.Bar => 2;
                public void Use2() => Console.Write(((FI)this).Bar);
            }
            """;

        var verifier = CompileAndVerify(new[] { (source0, "F0.cs"), (source1, "F1.cs"), (source2, "F2.cs") }, expectedOutput: "12");
        verifier.VerifyDiagnostics();
        verifier.VerifyTypeIL("C",
@"
.class private auto ansi beforefieldinit C
 extends [mscorlib]System.Object
 implements NS1.FI,
            NS2.FI
{
 // Methods
 .method private final hidebysig specialname newslot virtual 
  instance int32 NS1.FI.get_Bar () cil managed 
 {
  .override method instance int32 NS1.FI::get_Bar()
  // Method begins at RVA 0x2081
  // Code size 2 (0x2)
  .maxstack 8
  IL_0000: ldc.i4.1
  IL_0001: ret
 } // end of method C::NS1.FI.get_Bar
 .method public hidebysig 
  instance void Use1 () cil managed 
 {
  // Method begins at RVA 0x2084
  // Code size 12 (0xc)
  .maxstack 8
  IL_0000: ldarg.0
  IL_0001: callvirt instance int32 NS1.FI::get_Bar()
  IL_0006: call void [mscorlib]System.Console::Write(int32)
  IL_000b: ret
 } // end of method C::Use1
 .method private final hidebysig specialname newslot virtual 
  instance int32 NS2.FI.get_Bar () cil managed 
 {
  .override method instance int32 NS2.FI::get_Bar()
  // Method begins at RVA 0x2091
  // Code size 2 (0x2)
  .maxstack 8
  IL_0000: ldc.i4.2
  IL_0001: ret
 } // end of method C::NS2.FI.get_Bar
 .method public hidebysig 
  instance void Use2 () cil managed 
 {
  // Method begins at RVA 0x2094
  // Code size 12 (0xc)
  .maxstack 8
  IL_0000: ldarg.0
  IL_0001: callvirt instance int32 NS2.FI::get_Bar()
  IL_0006: call void [mscorlib]System.Console::Write(int32)
  IL_000b: ret
 } // end of method C::Use2
 .method public hidebysig specialname rtspecialname 
  instance void .ctor () cil managed 
 {
  // Method begins at RVA 0x2079
  // Code size 7 (0x7)
  .maxstack 8
  IL_0000: ldarg.0
  IL_0001: call instance void [mscorlib]System.Object::.ctor()
  IL_0006: ret
 } // end of method C::.ctor
 // Properties
 .property instance int32 NS1.FI.Bar()
 {
  .get instance int32 C::NS1.FI.get_Bar()
 }
 .property instance int32 NS2.FI.Bar()
 {
  .get instance int32 C::NS2.FI.get_Bar()
 }
} // end of class C
");
    }
```

I think we simply should do the "same" thing for file-local types situation.

**Review by AlekseyTs — CHANGES_REQUESTED** [review]
See https://github.com/dotnet/roslyn/pull/68331#discussion_r1214525262

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:1961]: For an explicit interface implementation, should we adjust the member's name when the symbol is initially created to include the "file-local" prefix?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:1961]: > For an explicit interface implementation, should we adjust the member's name when the symbol is initially created to include the "file-local" prefix?

Probably. I would do that in the same place we "mangle" the names for the test scenario above.

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/FileModifierTests.cs [hunk 3]
```diff
@@ -4022,4 +4083,463 @@ public void SyntaxTreeAlreadyPresent()
...
+        comp.VerifyDiagnostics(
+            // F1.cs(6,24): error CS8646: 'IFoo.Bar' is explicitly implemented more than once.
+            // internal partial class Foo : IFoo
+            Diagnostic(ErrorCode.ERR_DuplicateExplicitImpl, "Foo").WithArguments("IFoo.Bar").WithLocation(6, 24),
+            // F1.cs(6,30): error CS0535: 'Foo' does not implement interface member 'IFoo.Bar'
+            // internal partial class Foo : IFoo
+            Diagnostic(ErrorCode.ERR_UnimplementedInterfaceMember, "IFoo").WithArguments("Foo", "IFoo.Bar").WithLocation(6, 30),
+            // F2.cs(9,14): error CS0102: The type 'Foo' already contains a definition for '<F2>F141A34209AF0D3C8CA844A7D9A360C895EB14E557F17D27626C519D9BE96AF4A__IFoo.Bar'
+            //     int IFoo.Bar => 2;
+            Diagnostic(ErrorCode.ERR_DuplicateNameInClass, "Bar").WithArguments("Foo", "<F2>F141A34209AF0D3C8CA844A7D9A360C895EB14E557F17D27626C519D9BE96AF4A__IFoo.Bar").WithLocation(9, 14));
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/FileModifierTests.cs:4239]: It's not ideal to expose the file type's metadata name in an error message, but it's also not a big problem.

If we decide on some way in the future to produce smaller/simpler mangled names for these types, it may be helpful in more places. For example, it's not easy to skim such type names when looking through an ETL trace.

**Comment by AlekseyTs** [comment]
@jcouv For the second review

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/FileModifierTests.cs [hunk 4]
```diff
@@ -4022,4 +4083,463 @@ public void SyntaxTreeAlreadyPresent()
...
+
+        var comp = CreateCompilation(new[] { (source1, "F1.cs"), (source2, "F2.cs") });
+        comp.VerifyDiagnostics();
+    }
+
+    [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/68219")]
+    public void PartialExplicitImplementation_04()
+    {
+        var source1 = """
+            file interface IFoo
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/FileModifierTests.cs:4206]: >IFoo [](http://example.com/codeflow?start=27&length=4)

I think we avoid "Foo" because of policheck

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 3). Only minor naming issue

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/FileModifierTests.cs (hunk 4 above)
Comment (jcouv) [reply src/Compilers/CSharp/Test/Symbol/Symbols/Source/FileModifierTests.cs:4206]: There's some "Foo" left here

**Review by jcouv — COMMENTED** [review]
Done with review (iteration 4)

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 5)
