### PR TITLE
Name suggestions don't contain suggestions starting with a digit.

### LINKED ISSUE #39519: Intellisense suggests numeric identifier name.
**Version Used**: 
Visual Studio Community 2019
**Steps to Reproduce**:

1. Create an identifier of a type whose name contains a number
2. Type [control] + [space] to produce a list of suggested names for the identifier

**Expected Behavior**:
Do not suggest an invalid identifier name (identifier names cannot start with a number)
**Actual Behavior**:
image

related: #22011

### PR DESCRIPTION
**Pull request by chris-schuetz**
Fixes #39519

### CODE REVIEW

File: src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.NameGenerator.cs [hunk 1]
```diff
@@ -57,6 +57,15 @@ private static ImmutableArray<Words> GetInterleavedPatterns(ArrayBuilder<TextSpa
                     result.Add(GetLongestBackwardSubsequence(length, breaks, baseName, pluralize));
                 }
 
+                for (var index = result.Count - 1; index >= 0; index--)
+                {
+                    if (char.IsDigit(result[index][0], 0))
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.NameGenerator.cs]:
```suggestion
                    if (char.IsDigit(result[index][0], index: 0))
```

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb [hunk 2]
```diff
@@ -5996,6 +5996,35 @@ namespace NS
...
+}
+]]></Document>)
+                Dim workspace = state.Workspace
+                workspace.TryApplyChanges(workspace.CurrentSolution.WithOptions(workspace.Options _
+                    .WithChangedOption(CompletionOptions.ShowNameSuggestions, LanguageNames.CSharp, True)))
+
+                state.SendInvokeCompletionList()
+                Await state.AssertCompletionItemsContainAll("foo123Bar", "foo123", "foo", "bar")
+                Await state.AssertCompletionItemsDoNotContainAny("123")
+            End Using
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: can we have a VB test as well?

File: src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.NameGenerator.cs (hunk 1 above)
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.NameGenerator.cs]: is this check correct?  a few thingsthat worry me:

1. how do we know that `result[index]` is non-empty?  Indexing into `[0]` might be unsafe.
2. we're only checking the first word in `Words`, why is that correct?  What about the other words in it?

Feels like we need to check *every* word to see if it starts with a digit.

Comment (chris-dd) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.NameGenerator.cs]: 1. The strings inside the Words struct were created by StringBreaker.GetWordParts(). StringBreaker will only add TextSpans that are not emtpy.
2. Every Words-struct is used by the DeclarationNameCompletionProvider to create exactly one name suggestion, based on current NamingStyle. Only the first word will be the start of the generated name.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.NameGenerator.cs]: 1. is the above true given that some of the strings added were also created by GetLongestBackwardSubsequence and so on?
2. if what you say is correct, *great*.  but that must be documented in the code.  please add a comment explaining as much.  thanks! :)

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb (hunk 2 above)
Comment (chris-dd) [reply src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: Changes were only made for the DeclarationNameCompletionProvider. This provider is only used for C#. I did a quick test run with VB and there seems to be no corresponding CompletionProvider for VB.

Comment (CyrusNajmabadi) [reply src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: ah ok.  #resolved

File: src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.NameGenerator.cs (hunk 1 above)
Comment (chris-dd) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.NameGenerator.cs]: 1. Yes, the GetLongestBackwardSubsequence and GetLongestForwardSubsequence will create subsequences containing a subset of the strings that were originally create by the StringBreaker. No new texts will be created from scratch.
2. Done. Please let me know if you think the new comment is helpful.

File: src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.NameGenerator.cs [hunk 3]
```diff
@@ -57,6 +57,17 @@ private static ImmutableArray<Words> GetInterleavedPatterns(ArrayBuilder<TextSpa
                     result.Add(GetLongestBackwardSubsequence(length, breaks, baseName, pluralize));
                 }
 
+                for (var index = result.Count - 1; index >= 0; index--)
+                {
+                    // Every words-struct in result corresponds to one name that will be generated.
+                    // The first string inside the words-struct is the start of the name.
+                    // Names shouldn't start with a digit, so results with a digit as the first character of the first word are removed.
+                    if (char.IsDigit(result[index][0], index: 0))
```
Comment (dpoeschl) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.NameGenerator.cs]: There are other types of identifier part characters that are not legal identifier start characters. Should we be using `IsValidIdentifier` instead?

https://github.com/dotnet/roslyn/blob/1b4b5ba7e615e8fdbde036806bac710977e0239c/src/Workspaces/CSharp/Portable/LanguageServices/CSharpSyntaxFactsService.cs#L443-L447

If doing the parse on each is too slow or something, then we could use `IsIdentifierStartCharacter` on the first character instead of checking exclusively for digits.

Comment (chris-schuetz) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.NameGenerator.cs]: You are right. I changed it to using `IsValidIdentifier`. This way there won't be a name suggestions that is invalid. I was unable to detect any significant slow down of the declaration name completion feature, using these changes.

File: src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.NameGenerator.cs [hunk 4]
```diff
@@ -57,6 +59,16 @@ private static ImmutableArray<Words> GetInterleavedPatterns(ArrayBuilder<TextSpa
                     result.Add(GetLongestBackwardSubsequence(length, breaks, baseName, pluralize));
                 }
 
+                for (var index = result.Count - 1; index >= 0; index--)
+                {
+                    // Every words-array in result corresponds to one name that will be generated.
+                    // The name should only be used if it represents a valid identifier.
+                    if (syntaxFacts.IsValidIdentifier(string.Join(string.Empty, result[index])) == false)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.NameGenerator.cs]:
```suggestion
                    if (!syntaxFacts.IsValidIdentifier(string.Join(string.Empty, result[index])))
```

Comment (dpoeschl) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.NameGenerator.cs]: I think I'd prefer using `CSharpSyntaxFactsService.Instance.IsValidIdentifier(...)` directly instead of passing the `Document` (or the `ISyntaxFactsService` retrieved from the `Document`) around. If another Roslyn language ever came around that wanted to also do declaration name completion, then this code would have to be shared and the `ISyntaxFactsService` used, but that doesn't seem necessary yet. Open to thoughts. :)

Comment (chris-schuetz) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.NameGenerator.cs]: That makes sense. :)

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb [hunk 5]
```diff
@@ -5996,6 +5996,35 @@ namespace NS
...
+    } 
+}
+]]></Document>)
+                Dim workspace = state.Workspace
+                workspace.TryApplyChanges(workspace.CurrentSolution.WithOptions(workspace.Options _
+                    .WithChangedOption(CompletionOptions.ShowNameSuggestions, LanguageNames.CSharp, True)))
+
+                state.SendInvokeCompletionList()
+                Await state.AssertCompletionItemsContainAll("foo123Bar", "foo123", "foo", "bar")
+                Await state.AssertCompletionItemsDoNotContainAny("123")
```
Comment (dpoeschl) [inline src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]:
```suggestion
                Await state.AssertCompletionItemsDoNotContainAny("123Bar")
```

Comment (dpoeschl) [reply src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: Take "FooCatBar" for example, we don't recommend "cat" in this case because it's not a left-most or right-most sub-array of words.

We should be checking for the absence of is "123Bar" since "123" wouldn't be offered even if it were a valid identifier. In the original issue, they checked against the number itself because the number was the rightmost "word" and therefore eligible. Try your test case out in VS before your change, and you'll see "123Bar" offered and not "123".

Comment (dpoeschl) [reply src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: Perhaps there should be a second test which is an exact copy of the original issue? That way we have this case where the number is in the middle (and part of a larger possible identifier), and one where the number itself becomes the possible identifier.

Comment (chris-schuetz) [reply src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: Done.

**Comment by chris-schuetz** [comment]
I had to move the `IsValidIdentifier` check to a different position in the `DeclarationNameCompletionProvider`.

The `DeclarationNameCompletionProvider` will try to escape keywords shortly before adding them to the suggestions. This allows an invalid identifier like `string` to become a valid identifier `@string`. I moved the check after the escape operation was performed, so name suggestions aren't removed if they can be made valid by escaping.
