### PR TITLE
/errorlog improvements, fixes, and marking as v1.0.0

### LINKED ISSUE #11383: Compiler emits duplicate rules metadata entries with ErrorLogger version 1.0.0-beta.5
**Version Used**: Latest Roslyn bits

**Steps to Reproduce**:

1. Unzip `Closed\Test\Solutions\Newtonsoft.json.zip` from the roslyn-internal repo

2. Clean your RoslynDev hive: "C:\Users\<%USER_NAME%>\AppData\Local\Microsoft\VisualStudio\14.0RoslynDev"

3. Build Roslyn.sln with 'OfficialBuild = true' using the below command. This will build and deploy latest Roslyn bits (and hence compiler ErrorLogger) into the RoslynDev hive.

     > msbuild /m Roslyn.sln /t:rebuild /p:OfficialBuild=true
4. devenv /rootSuffix RoslynDev

5. Open and build `\Closed\Test\Solutions\Newtonsoft.Json\Newtonsoft.Json\Newtonsoft.Json.Portable.sln` 

6. Open `\Closed\Test\Solutions\Newtonsoft.Json\Newtonsoft.Json\ErrorLog.json`

**Expected Behavior**:
No duplicate metadata entries for any rules (there are no rules with duplicate IDs)

**Actual Behavior**:
Duplicate entries SA1001 and SA1001.001
```
        "SA1003": {
          "id": "SA1003",
          "shortDescription": "Symbols must be spaced correctly",
          "fullDescription": "The spacing around an operator symbol is incorrect, within a C# code file.",
          "defaultLevel": "warning",
          "helpUri": "https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1003.md",
          "properties": {
            "category": "StyleCop.CSharp.SpacingRules",
            "isEnabledByDefault": true
          }
        },
        "SA1003.001": {
          "id": "SA1003",
          "shortDescription": "Symbols must be spaced correctly",
          "fullDescription": "The spacing around an operator symbol is incorrect, within a C# code file.",
          "defaultLevel": "warning",
          "helpUri": "https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1003.md",
          "properties": {
            "category": "StyleCop.CSharp.SpacingRules",
            "isEnabledByDefault": true
          }
        },```

### PR DESCRIPTION
**Pull request by nguerrera**
Five distinct changes in five commits

* 50f8500: Fix #11383 - prevent duplicate rule metadata   
* c664130: Fix URI escaping  
* f73fd4e: Log language 
* 82e584e: Change rule ID disambiguator from '.' to '-'  
* e090e14: Mark as v1.0.0 (schema update is pending and there will be no breaking changes to it)

@mavasani @agocke @lgolding @michaelcfanning

### CODE REVIEW

File: src/Compilers/Core/CodeAnalysisTest/Diagnostics/ErrorLoggerTests.cs [hunk 1]
```diff
@@ -93,10 +93,25 @@ public void AdditionalLocationsAsRelatedLocations()
         public void DescriptorIdCollision()
         {
             var descriptors = new[] {
+                // Toughest case: generation of TST001.001 collides with with actual TST001.001 and must be bumped to TST00.002
```
Comment (nguerrera) [inline src/Compilers/Core/CodeAnalysisTest/Diagnostics/ErrorLoggerTests.cs]: Typo: s/TST00.002/TST001.002/

**Comment by mavasani** [comment]
LGTM

**Comment by nguerrera** [comment]
test vsi please

**Comment by mavasani** [comment]
I'd this would break the VSI test as the error baseline now has duplicate entries mentioned in #11383. @nguerrera did you manually run the repro steps from the bug and verify fixed?

**Comment by nguerrera** [comment]
Didn't you put a workaround in the test? I saw a comment about filtering the ruleKey. I will run the repro locally to see.

**Comment by mavasani** [comment]
Yes, the workaround would have skipped the ruleKey entry in the diagnostic instance, but we still compare the entire "rules" blob with the baseline, which I thought would have failed with your fix.

**Comment by michaelcfanning** [comment]
+1

**Comment by nguerrera** [comment]
@mavasani @agocke @lgolding @michaelcfanning pushed 3 more fixes/improvements and generalized title so please take another look.

@michaelcfanning  c664130 shows how I handled and tested URI escaping issues.

**Comment by nguerrera** [comment]
@mavasani I've run the repro steps and I see no "ruleKey" or "*.NNN" duplicate entries in ErrorLog.json. I emailed you a copy.

File: src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs [hunk 2]
```diff
@@ -42,21 +42,17 @@ public ErrorLogger(Stream stream, string toolName, string toolFileVersion, Versi
             _writer.WriteArrayStart("runs");
             _writer.WriteObjectStart(); // run
 
-            WriteToolInfo(toolName, toolFileVersion, toolAssemblyVersion);
+            _writer.WriteObjectStart("tool");
+            _writer.Write("name", toolName);
+            _writer.Write("version", toolAssemblyVersion.ToString());
+            _writer.Write("fileVersion", toolFileVersion);
+            _writer.Write("semanticVersion", toolAssemblyVersion.ToString(fieldCount: 3));
+            _writer.Write("language", culture.Name);
```
Comment (lgolding) [inline src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs]: Will this give an RFC 3066 string (e.g., "en" or "en-US")? That's what the spec wants here.

File: src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs [hunk 3]
```diff
@@ -155,22 +151,34 @@ private static bool HasPath(Location location)
...
             Debug.Assert(!string.IsNullOrEmpty(path));
 
+            // Note that in general, these "paths" are opaque strings to be 
+            // interpreted by resolvers (see SyntaxTree.FilePath documentation).
+            
+            // Common case: absolute path -> absolute URI
             Uri uri;
+            if (Uri.TryCreate(path, UriKind.Absolute, out uri))
+            {
+                // Note that URI.ToString() does not, for example, escape spaces to %20.
```
Comment (lgolding) [inline src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs]: ... but AbsoluteUri does, I take it. Ok, with you so far...

File: src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs [hunk 4]
```diff
@@ -155,22 +151,34 @@ private static bool HasPath(Location location)
...
+            // (perhaps the resolver works that way).
+            if (Uri.TryCreate(path, UriKind.Relative, out uri))
             {
-                // The only constraint on paths are that they can be interpreted by
-                // various resolvers so there is no guarantee we can turn the arbitrary string
-                // in to a URI. If our attempt to do so fails, use the original string as the
-                // "URI".
-                return path;
+                // There is no AbsoluteUri equivalent for relative URI references and ToString() 
+                // won't escape without this relative -> absolute -> relative trick.
```
Comment (lgolding) [inline src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs]: Ah, now I see your problem.

File: src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs (hunk 2 above)
Comment (nguerrera) [inline src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs]: Yes. 

https://msdn.microsoft.com/en-us/library/system.globalization.cultureinfo.name(v=vs.110).aspx

> The culture name in the format languagecode2-country/regioncode2. languagecode2 is a lowercase two-letter code derived from ISO 639-1. country/regioncode2 is derived from ISO 3166 and usually consists of two uppercase letters, or a BCP-47 language tag.

**Comment by mavasani** [comment]
@nguerrera Thanks - probably something is broken in the test code comparing rules metadata. I'll look once your change is merged in.

File: src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs [hunk 5]
```diff
@@ -155,22 +151,34 @@ private static bool HasPath(Location location)
...
+                return _fileRoot.MakeRelativeUri(new Uri(_fileRoot, uri)).ToString();
             }
 
-            return uri.ToString();
+            // Last resort: UrlEncode the whole opaque string as a relative reference with one part.
+            return System.Net.WebUtility.UrlEncode(path);
```
Comment (lgolding) [inline src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs]: Eep. Won't that encode the slashes as well? Is that what you meant by "with one part"? Well, it's a legal URI, although RFC 3986 recommends against it:

... some URI producers percent-encode octets that do not require percent-encoding, resulting in URIs that    are equivalent to their non-encoded counterparts.  These URIs should be normalized by decoding any percent-encoded octet that corresponds to an unreserved character, as described in Section 2.3.

File: src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs [hunk 6]
```diff
@@ -381,6 +389,60 @@ public string Add(DiagnosticDescriptor descriptor)
...
+                    }
+
+                    if (ReferenceEquals(x, null) || ReferenceEquals(y, null))
+                    {
+                        return false;
+                    }
+
+                   return (x.Category == y.Category
+                        && x.DefaultSeverity == y.DefaultSeverity
+                        && x.Description.Equals(y.Description)
```
Comment (lgolding) [inline src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs]: Do we need to protect against Description or Title or CustomTags being null?

File: src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs [hunk 7]
```diff
@@ -381,6 +389,60 @@ public string Add(DiagnosticDescriptor descriptor)
                 list.Sort((x, y) => string.CompareOrdinal(x.Key, y.Key));
                 return list;
             }
+
+            /// <summary>
+            /// Compares descriptors by the values that we write to the log and nothing else.
+            /// 
+            /// We cannot use the IEquatable implementation because it includes message format 
+            /// and we don't write it out. It also ignores tags, which we do write.
+            /// </summary>
```
Comment (lgolding) [inline src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs]: Why do you say it ignores tags? Are "tags" different from the "CustomTags" which you do compare below?

File: src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs [hunk 8]
```diff
@@ -381,6 +389,60 @@ public string Add(DiagnosticDescriptor descriptor)
...
+                        return 0;
+                    }
+
+                    int hash = Hash.Combine(obj.Category.GetHashCode(),
+                        Hash.Combine(obj.DefaultSeverity.GetHashCode(),
+                        Hash.Combine(obj.Description.GetHashCode(),
+                        Hash.Combine(obj.HelpLinkUri.GetHashCode(),
+                        Hash.Combine(obj.Id.GetHashCode(),
+                        Hash.Combine(obj.IsEnabledByDefault.GetHashCode(),
+                        obj.Title.GetHashCode()))))));
```
Comment (lgolding) [inline src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs]: Do we need to worry about any of these being null? I'm particularly concerned about HelpLinkUri.

File: src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs (hunk 5 above)
Comment (nguerrera) [inline src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs]: It will. That is what I meant by "one part" though I see now that it's just another way to encode / and not recommended. This case would not be triggered in normal case. It's a last resort. We have what is legally an opaque string from the Roslyn OM's POV (but normally an absolute path in command line compiler + analyzers that don't make bizarre Locations). The middle case is for someone who is using the freedom of the opaque string merely to use relative paths. I'm not sure what to do in this final case. Previously, we just bailed and returned the string unchanged. I think UrlEncoding it is slightly better.

File: src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs (hunk 7 above)
Comment (nguerrera) [inline src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs]: They aren't different. What I mean here is that the IEquatable implementation of DiagnosticDescriptor itself does not include CustomTags in its comparison. So this comparer is different in two ways: it includes CustomTags, and excludes MessageFormat.

File: src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs (hunk 2 above)
Comment (lgolding) [inline src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs]: "Usually"? ;-) Oh well, it's not like there's anything better you can do here...

---
In reply to: [63798378](https://github.com/dotnet/roslyn/pull/11390#discussion_r63798378) [](ancestors = 63798378)

File: src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs (hunk 5 above)
Comment (lgolding) [inline src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs]: ok.

---
In reply to: [63799241](https://github.com/dotnet/roslyn/pull/11390#discussion_r63799241) [](ancestors = 63799241)

File: src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs (hunk 8 above)
Comment (nguerrera) [inline src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs]: This is a good question. It's copied from the IEquatable that we can't use so I assume not, but I'll double check. I suspect everything null is being rejected or coerced to empty at construction.

File: src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs (hunk 7 above)
Comment (lgolding) [inline src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs]: Oh, sorry, I can't read.

---
In reply to: [63799465](https://github.com/dotnet/roslyn/pull/11390#discussion_r63799465) [](ancestors = 63799465)

File: src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs (hunk 2 above)
Comment (nguerrera) [inline src/Compilers/Core/Portable/CommandLine/ErrorLogger.cs]: I believe technically, I can make custom CultureInfos with any name, but as you say, there's nothing else we can do. In practice, this will be from the built-in CultureInfos that do have the correct names.

**Comment by nguerrera** [comment]
test vsi please

**Comment by nguerrera** [comment]
Reviewers, this needs to go in today.

@mavasani Did you look at the commits after 50f8500? Do you still sign-off?

@lgolding I've clarified some comments and added some asserts in response to you feedback in 4f3f9ec 

@agocke Would you mind taking a look as well?

**Comment by lgolding** [comment]
:+1:

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs [hunk 9]
```diff
@@ -84,6 +84,11 @@ internal Version GetAssemblyVersion()
             return typeof(CommonCompiler).GetTypeInfo().Assembly.GetName().Version;
         }
 
+        internal string GetCultureName()
```
Comment (agocke) [inline src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: Expression-bodied property?

**Comment by agocke** [comment]
:shipit:

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs (hunk 9 above)
Comment (nguerrera) [inline src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: Probably would have been nicer, but not going to bother resetting CI over that. The function just above is a 1-liner too so I'll argue file self-consistency + minimal diff. ;)

**Comment by nguerrera** [comment]
retest windows_debug_unit64_prtest please
