### PR TITLE
Struct layout check – break an infinite generic expansion cycle that doesn’t include the target struct (a cycle at the end of the path)

### LINKED ISSUE #66844: Stack overflow due to struct layout cycle
This is a clone of existing ```StaticMemberExplosion``` test.

```
        [Fact]
        public void InstanceMemberExplosion()
        {
            string program = @"
struct A<T>
{
    A<A<T>> x;
}

struct B<T>
{
    A<B<T>> x;
}

struct C<T>
{
    D<T> x;
}
struct D<T>
{
    C<D<T>> x;
}
";
            CreateCompilation(program)
                .VerifyDiagnostics(
                );
        }
```

Observed:
```
Executing test method: Microsoft.CodeAnalysis.CSharp.UnitTests.FlowDiagnosticTests.InstanceMemberExplosion
[xUnit.net 00:00:00.25]   Starting:    Microsoft.CodeAnalysis.CSharp.Emit2.UnitTests
The active test run was aborted. Reason: Test host process crashed : Process is terminated due to StackOverflowException.

>	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.ConstructCore(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithAnnotations> typeArguments, bool unbound) Line 1232	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.Construct(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithAnnotations> typeArguments, bool unbound) Line 1227	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.SymbolExtensions.ConstructIfGeneric(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithAnnotations> typeArguments) Line 36	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.AbstractTypeMap.SubstituteNamedType(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol previous) Line 82	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.AbstractTypeMap.SubstituteType(Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol previous) Line 101	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithAnnotations.SubstituteTypeCore(Microsoft.CodeAnalysis.CSharp.Symbols.AbstractTypeMap typeMap) Line 435	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithAnnotations.NonLazyType.SubstituteType(Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithAnnotations type, Microsoft.CodeAnalysis.CSharp.Symbols.AbstractTypeMap typeMap) Line 909	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithAnnotations.SubstituteType(Microsoft.CodeAnalysis.CSharp.Symbols.AbstractTypeMap typeMap) Line 426	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.AbstractTypeMap.SubstituteNamedType(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol previous) Line 66	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.AbstractTypeMap.SubstituteType(Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol previous) Line 101	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithAnnotations.SubstituteTypeCore(Microsoft.CodeAnalysis.CSharp.Symbols.AbstractTypeMap typeMap) Line 435	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithAnnotations.NonLazyType.SubstituteType(Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithAnnotations type, Microsoft.CodeAnalysis.CSharp.Symbols.AbstractTypeMap typeMap) Line 909	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithAnnotations.SubstituteType(Microsoft.CodeAnalysis.CSharp.Symbols.AbstractTypeMap typeMap) Line 426	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.AbstractTypeMap.SubstituteType(Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithAnnotations previous) Line 129	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.SubstitutedFieldSymbol.GetFieldType(Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol> fieldsBeingBound) Line 31	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol.TypeWithAnnotations.get() Line 62	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol.Type.get() Line 75	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.NonPointerType(Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol field) Line 240	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 96	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.BaseTypeAnalysis.StructDependsClosure(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol type, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.CSharp.Symbol> partialClosure, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol on) Line 102	C#
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #66844

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

File: src/Compilers/CSharp/Test/Emit3/FlowAnalysis/StructTests.cs [hunk 1]
```diff
@@ -219,6 +219,196 @@ public void GenericStructWithPropertyUsingStruct()
                 Diagnostic(ErrorCode.ERR_StructLayoutCycle, "P").WithArguments("S<T>.P", "S<T[]>?").WithLocation(3, 13));
         }
 
+        [Fact]
+        [WorkItem("https://github.com/dotnet/roslyn/issues/66844")]
+        public void InstanceMemberExplosion_01()
```
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit3/FlowAnalysis/StructTests.cs:224]: > Consider testing ref structs with ref fields.

Wy do you think this will be interesting in context of this PR?

[the remark this answers is not in the document]
Comment (jjonescz) [reply src/Compilers/CSharp/Test/Emit3/FlowAnalysis/StructTests.cs:224]: Ref fields cannot cause cycles in the struct layout, but I think an error would be reported today. However, since ref to ref struct is an error anyway, it's probably fine, and unrelated to the PR.

**Review by jjonescz — APPROVED** [review]

File: src/Compilers/CSharp/Test/Emit3/FlowAnalysis/StructTests.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit3/FlowAnalysis/StructTests.cs:224]: In my opinion this scenario is not interesting for the purpose of this PR regardless whether ref fields are considered as a possible source of cycle. Because this PR doesn't change what fields are looked at. It simply ensures we do not infinitely expand types in the process.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

File: src/Compilers/CSharp/Test/Emit3/FlowAnalysis/StructTests.cs [hunk 2]
```diff
@@ -219,6 +219,196 @@ public void GenericStructWithPropertyUsingStruct()
...
+}
+
+struct C<T>
+{
+    static D<T> x;
+}
+struct D<T>
+{
+    static C<D<T>> x;
+}
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit3/FlowAnalysis/StructTests.cs:341]: Are we testing a mix of static and instance members? For instance:
```csharp
struct C<T>
{
    static D<T> x;
}
struct D<T>
{
    C<D<T>> x;
}
```

File: src/Compilers/CSharp/Test/Emit3/FlowAnalysis/StructTests.cs [hunk 3]
```diff
@@ -219,6 +219,196 @@ public void GenericStructWithPropertyUsingStruct()
...
+                //     X<Z> xz;
+                Diagnostic(ErrorCode.ERR_StructLayoutCycle, "xz").WithArguments("Y.xz", "X<Z>").WithLocation(12, 10),
+                // (18,10): error CS0523: Struct member 'Z.xy' of type 'X<Y>' causes a cycle in the struct layout
+                //     X<Y> xy;
+                Diagnostic(ErrorCode.ERR_StructLayoutCycle, "xy").WithArguments("Z.xy", "X<Y>").WithLocation(18, 10)
+                );
+        }
+
+        [Fact]
+        [WorkItem("https://github.com/dotnet/roslyn/issues/66844")]
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit3/FlowAnalysis/StructTests.cs:320]: >https://github.com/dotnet/roslyn/issues/66844 [](http://example.com/codeflow?start=19&length=45)

Are these static cases affected by this issue?

File: src/Compilers/CSharp/Test/Emit3/FlowAnalysis/StructTests.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit3/FlowAnalysis/StructTests.cs:341]: > Are we testing a mix of static and instance members? For instance:

These are not interesting in context of the problem we are facing because cycles across static and instance fields are detected separately and by different methods.

File: src/Compilers/CSharp/Test/Emit3/FlowAnalysis/StructTests.cs (hunk 3 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit3/FlowAnalysis/StructTests.cs:320]: > Are these static cases affected by this issue?

The scenario is not broken, if that is what you are asking. But I consider the test related to the issue.

File: src/Compilers/CSharp/Test/Emit3/FlowAnalysis/StructTests.cs (hunk 2 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Emit3/FlowAnalysis/StructTests.cs:341]: The example above currently compiles, but peverify fails, and the native compiler reports a cycle. Do we need to log an issue?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit3/FlowAnalysis/StructTests.cs:341]: > Do we need to log an issue?

Please do, we can investigate in more details later..

Comment (cston) [reply src/Compilers/CSharp/Test/Emit3/FlowAnalysis/StructTests.cs:341]: https://github.com/dotnet/roslyn/issues/75832

File: src/Compilers/CSharp/Portable/Symbols/BaseTypeAnalysis.cs [hunk 4]
```diff
@@ -65,30 +65,50 @@ internal static bool StructDependsOn(NamedTypeSymbol depends, NamedTypeSymbol on
...
+            }
+
+            if (on.ContainsReference(type.OriginalDefinition))
             {
                 // found a possibly expanding cycle, for example
                 //     struct X<T> { public T t; }
                 //     struct W<T> { X<W<W<T>>> x; }
                 // while not explicitly forbidden by the spec, it should be.
-                partialClosure.Add(on);
+                typesWithCycle.Add(type.OriginalDefinition);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/BaseTypeAnalysis.cs:94]: >typesWithCycle.Add [](http://example.com/codeflow?start=16&length=18)

Are there any examples where `typesWithCycle` willl have more than one item?

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Symbols/BaseTypeAnalysis.cs (hunk 4 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/BaseTypeAnalysis.cs:94]: > Are there any examples where typesWithCycle willl have more than one item?

I see nothing preventing that. If that is what you are asking?

Comment (cston) [reply src/Compilers/CSharp/Portable/Symbols/BaseTypeAnalysis.cs:94]: If it's possible, it would be useful to have a test that has multiple entries in `typesWithCycle`, to prevent us from changing this to a single value in the future.
