### PR TITLE
Localization test failures Return FormattableString for BoundTupleExpression.Display

### LINKED ISSUE #24603: Test localization failures on non english machines: BoundTupleExpression.Display returns a string instead a FormattableString
Extracted from the closed PR #24539 

**Steps to Reproduce**:

Run `Microsoft.CodeAnalysis.CSharp.UnitTests.OverloadResolutionTests.GenericInferenceOnInErrTuples` on a non-english machine.

**Expected Behavior**:

Test passes.

**Actual Behavior**:

Test fails for Diagnostics with a `BoundTupleExpression` because `BoundTupleExpression.Display` returns a localized string (e.g. German during the test run). BoundTupleExpression.Display should return a formattable string instead. There are some more tests that also fail. See the original PR for details.

**History**

The issue was discussed but not resolved in #24539. The relevant sections are:

@Mastr11
The diagnostic is created [here](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs#L991) and the argument is created via  `argument.Display` 
The problem here is that the [BoundTupleExpression.Display](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/BoundTree/Formatting.cs#L85) uses a stringbuilder. So the argument is a text as opposed to a `LocalizableErrorArgument`. I don't see any straight forward way on how to resolve this. @AlekseyTs I would propose to revert my changes here and let the test fail on non english machines for now. 

@AlekseyTs 
It would be great if you could fix it because you can easily verify the effect, but it is up to you.
I think there is a simple fix for BoundTupleExpression.Display. Instead of building complete string, we can build a format string with argument markers and collect arguments in an array. Then we call to System.Runtime.CompilerServices.FormattableStringFactory.Create and return its result.
There is also an issue with

```CS
    internal partial class BoundStackAllocArrayCreation
    {
        public override object Display
        {
            get { return string.Format(MessageID.IDS_StackAllocExpression.Localize().ToString(), ElementType, Count.Syntax); }
        }
    }
```

This one can be fixed by creating an object that is very similar to LocalizableErrorArgument, that calls Format after getting the string for requested culture.

### PR DESCRIPTION
**Pull request by MaStr11**
### Customer scenario

Running unit test `OverloadResolutionTests.GenericInferenceOnInErrTuples` on non English machines failed due to localization issues. The root cause was that `BoundTupleExpression.Display` returned a string instead of a localizable string. The PR implements the solution proposed by @AlekseyTs in #24603. 
As noted in #24603 `BoundStackAllocArrayCreation.Display` a few lines down needs also to be fixed. This will be done once the fix `BoundTupleExpression.Display` is reviewed as being valid.

### Bugs this fixes

Fixes #24603 

### Workarounds, if any

Ignore test failures.

### Risk

The proposed solution requires to allow `FormattableString` types in `DiagnosticInfo.Arguments`. This might lead to unwanted code patterns in respect to DiagnosticInfo and localizability in the future.

### Performance impact

Low.

### Root cause analysis

Localization wasn't tested before.

### How was the bug found?

Contributor reported.

### Test documentation updated?

No.

### CODE REVIEW

**Comment by MaStr11** [comment]
@AlekseyTs could you review please?

File: src/Compilers/Core/Portable/Diagnostic/DiagnosticInfo.cs [hunk 1]
```diff
@@ -102,6 +102,11 @@ internal static void AssertMessageSerializable(object[] args)
                     continue;
                 }
 
+                if (arg is FormattableString)
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Diagnostic/DiagnosticInfo.cs]: >FormattableString [](start = 27, length = 17)

Perhaps make it more general by checking against IFormattable?

File: src/Compilers/CSharp/Portable/BoundTree/Formatting.cs [hunk 2]
```diff
@@ -82,17 +84,18 @@ public override object Display
...
-                    builder.Append(", ");
-                    builder.Append(arguments[i].Display);
+                    builder.Append(", {" + i + "}");
                 }
 
                 builder.Append(')');
 
-                return pooledBuilder.ToStringAndFree();
+                var format = pooledBuilder.ToStringAndFree();
+                var argumentDisplays = arguments.Select(a => a.Display).ToArray();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/Formatting.cs]: >var argumentDisplays = arguments.Select(a => a.Display).ToArray(); [](start = 16, length = 66)

Instead of doing this, allocate an array of the right size for arguments and populate it along with the format string.
```
var argumentsDisplay = new object[arguments.Length];
...
argumentsDisplay[i] = arguments[i].Display;
...
FormattableStringFactory.Create(format, argumentsDisplay)
```

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/BoundTree/Formatting.cs]: Make sure to remove ```using System.Linq;``` if it is no longer needed.

---
In reply to: [172283897](https://github.com/dotnet/roslyn/pull/25209#discussion_r172283897) [](ancestors = 172283897)

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1)

**Comment by MaStr11** [comment]
@AlekseyTs 
I addressed your comments in cc0ea23. I also tried to fix `BoundStackAllocArrayCreation.Display` in bd62da1. The `Display` property is used in [StackAllocSpanExpressionsTests.ConditionalExpressionOnSpan_IncompatibleTypes](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Test/Semantic/Semantics/StackAllocSpanExpressionsTests.cs#L289) so the change I made is covered by a unit test.

**Comment by AlekseyTs** [comment]
> StackAllocSpanExpressionsTests.ConditionalExpressionOnSpan_IncompatibleTypes so the change I made is covered by a unit test.

Was the test failing before your change? If not, we need to come up with a test that fails without the change.

**Comment by MaStr11** [comment]
No it didn't. It `Display` produces `stackalloc int[10]`, which isn't changed by the current culture (The other test also contained only language keywords but for some mysterious reasons `<null>` was translated by the German translators to `<NULL>`.) Can you give me some advice, how to write the test (were should it go and how should I test it).

File: src/Compilers/CSharp/Portable/BoundTree/Formatting.cs [hunk 3]
```diff
@@ -148,9 +150,7 @@ public override object Display
     internal partial class BoundStackAllocArrayCreation
     {
         public override object Display
-        {
-            get { return string.Format(MessageID.IDS_StackAllocExpression.Localize().ToString(), ElementType, Count.Syntax); }
-        }
+            => ErrorFacts.GetMessageFormat(MessageID.IDS_StackAllocExpression, ElementType.ToDisplayString(), Count.Syntax.ToString());
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/Formatting.cs]: >ToDisplayString [](start = 91, length = 15)

That builds string too early. Nothing should be formatted until client asks for the string

**Comment by AlekseyTs** [comment]
> The other test also contained only language keywords but for some mysterious reasons <null> was translated by the German translators to <NULL>.

What other test? This could be an indication of a premature localization.

File: src/Compilers/CSharp/Portable/BoundTree/Formatting.cs (hunk 3 above)
Comment (MaStr11) [reply src/Compilers/CSharp/Portable/BoundTree/Formatting.cs]: So we need a mixture of FormattableStringFactory.Create (delays the arguments) and ErrorFacts.GetMessageFormat (Delays the formatstring). I haven't seen anything that is able to do this. Can you give me a hint were to look?

**Comment by MaStr11** [comment]
> What other test?

The test that was failing on a German machine and made me fix BoundTupleExpression.Display. It was `OverloadResolutionTests.GenericInferenceOnInErrTuples` and is fixed by the changes until the last commit. The last commit addressed your comment in the original issue #24603.

> There is also an issue with BoundStackAllocArrayCreation.Display

Actually bd62da1 is a different concern. Sorry for being confusing here. I would also be fine with reverting bd62da1 and open a new issue for that.

File: src/Compilers/CSharp/Portable/BoundTree/Formatting.cs [hunk 4]
```diff
@@ -148,9 +150,7 @@ public override object Display
     internal partial class BoundStackAllocArrayCreation
     {
         public override object Display
-        {
-            get { return string.Format(MessageID.IDS_StackAllocExpression.Localize().ToString(), ElementType, Count.Syntax); }
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/Formatting.cs]: >IDS_StackAllocExpression [](start = 49, length = 24)

It doesn't look like there is anything localizable in this resource - "stackalloc {0}[{1}]". I think we should remove it from resource file and hardcode the format string here. Then it becomes the same problem as for BoundTupleExpression. Note, it is fine to call ToString() on Count.Syntax and we should do this.

**Comment by AlekseyTs** [comment]
Since the only part that can involve localization in BoundStackAllocArrayCreation is the type symbol, it would be extremely hard to come up with broken case. I think it will be fine to fix it without failing test

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler, @jcouv, @VSadov Please review, need a second sign-off

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler, @jcouv, @VSadov Please review, need a second sign-off

**Comment by jcouv** [comment]
@jaredpar for ask-mode approval for 15.7. Thanks

**Comment by jaredpar** [comment]
Approved

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AlekseyTs** [comment]
@MaStr11 Thanks for the contribution!
