### PR TITLE
Suppress code for empty try-catch with /optimize (Release) mode

### LINKED ISSUE #2443: Compiler generates code for empty try..catch with /optimize flag
### Steps to reproduce:

1. Compile the below C# file with /optimize in VS2015 and VS2013
2. Observe the generated code for Main in ildasm.exe

```cs
using System;

namespace ConsoleApp
{
    class Program
    {
        public static void Main(string[] args)
        {
            try
            {
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
    }
}
```

### Expected Behavior (this is the VS2013 behavior)
```none
.method public hidebysig instance void  Main(string[] args) cil managed
{
  // Code size       1 (0x1)
  .maxstack  1
  .locals init (class [mscorlib]System.Exception V_0)
  IL_0000:  ret
} // end of method Program::Main
```

### Actual Behavior (this is the VS2015 behavior)
```none
.method public hidebysig static void  Main(string[] args) cil managed
{
  .entrypoint
  // Code size       10 (0xa)
  .maxstack  1
  .try
  {
    IL_0000:  leave.s    IL_0009
  }  // end .try
  catch [mscorlib]System.Exception 
  {
    IL_0002:  call       void [mscorlib]System.Console::WriteLine(object)
    IL_0007:  leave.s    IL_0009
  }  // end handler
  IL_0009:  ret
} // end of method Program::Main
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #2443 

@AlekseyTs @VSadov @jaredpar @agocke Please review.
@tmat This affects an expression evaluator test. Please review.

### CODE REVIEW

**Comment by tmat** [comment]
@cston for EE change

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TryStatement.cs [hunk 1]
```diff
@@ -16,13 +16,20 @@ public override BoundNode VisitTryStatement(BoundTryStatement node)
             var origSawAwait = _sawAwait;
             _sawAwait = false;
 
-            ImmutableArray<BoundCatchBlock> catchBlocks = (ImmutableArray<BoundCatchBlock>)this.VisitList(node.CatchBlocks);
+            // When optimizing and we have an empty try block, we can discard the catch blocks.
+            // In theory we could do better by detecting *effectively* empty catch blocks, but this is the most common case.
+            ImmutableArray<BoundCatchBlock> catchBlocks =
+                node.TryBlock.Statements.Length == 0 && this._compilation.Options.OptimizationLevel == OptimizationLevel.Release
+                    ? ImmutableArray<BoundCatchBlock>.Empty
+                    : (ImmutableArray<BoundCatchBlock>)this.VisitList(node.CatchBlocks);
```
Comment (VSadov) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TryStatement.cs]: Perhaps empty finallies can also be removed?

Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TryStatement.cs]: Cast to ImmutableArray&lt;BoundCatchBlock&gt; is not necessary.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTryFinally.cs [hunk 2]
```diff
@@ -2007,26 +2013,27 @@ public void ThrowInFinally()
...
-        try { }
+        try { nop(); }
         finally { throw new Exception(); }
     }
     static void ThrowInFinallyInTry()
     {
         try
         {
-            try { }
+            try { nop(); }
```
Comment (VSadov) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTryFinally.cs]: no need to put nops here since we do not have catches. We also need a test to verify that nonempty finallies do not disappear, so this could be one such test if nops are removed.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TryStatement.cs (hunk 1 above)
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TryStatement.cs]: Are we dropping errors by not visiting CatchBlocks? Instead, should the catch blocks be visited and then dropped?

**Comment by VSadov** [comment]
overall LGTM, but need a test to verify that nonempty finallies do not get optimized. 
Also it seems fairly easy to remove empty finallies as well. That might be interesting optimization too.

**Comment by VSadov** [comment]
Does VB need a similar change?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TryStatement.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TryStatement.cs]: Semantic errors are reported in earlier passes. The only errors we need to report here are problems that prevent us from generating code. If we can drop the code then there are no problems.

**Comment by gafter** [comment]
Yes, I will add the VB version to this PR.

**Comment by gafter** [comment]
I've responded to code reviews, including implementing the optimizations for VB and optimizing an empty finally. However I have not adjusted all tests as required.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TryStatement.cs [hunk 3]
```diff
@@ -16,13 +16,60 @@ public override BoundNode VisitTryStatement(BoundTryStatement node)
...
+            return (catchBlocks.IsDefaultOrEmpty && finallyBlockOpt == null)
+                ? (BoundNode)tryBlock
+                : (BoundNode)node.Update(tryBlock, catchBlocks, finallyBlockOpt, node.PreferFaultHandler);
+        }
+
+        /// <summary>
+        /// Is there no code to execute in the given statement that could have side-effects,
+        /// such as throwing an exception?
+        /// </summary>
+        private static bool IsMorallyEmpty(BoundStatement statement)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TryStatement.cs]: Is  "morally" the right term? Could we use name "HasNoSideEffects" instead?

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_Try.vb [hunk 4]
```diff
@@ -14,10 +14,35 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
             Debug.Assert(_unstructuredExceptionHandling.Context Is Nothing)
 
             Dim rewrittenTryBlock = RewriteTryBlock(node.TryBlock)
-            Dim rewrittenCatchBlocks = VisitList(node.CatchBlocks)
+            Dim optimizing = Not Me.OptimizationLevelIsDebug
+            ' When optimizing And we have a morally empty try block, we can discard the catch blocks.
+            Dim rewrittenCatchBlocks = If(optimizing AndAlso IsMorallyEmpty(rewrittenTryBlock), ImmutableArray(Of BoundCatchBlock).Empty, VisitList(node.CatchBlocks))
             Dim rewrittenFinally = RewriteFinallyBlock(node.FinallyBlockOpt)
+            If optimizing AndAlso IsMorallyEmpty(rewrittenFinally) Then rewrittenFinally = Nothing
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_Try.vb]: Consider using block-If

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_Try.vb [hunk 5]
```diff
@@ -14,10 +14,35 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
 
-            Return RewriteTryStatement(node.Syntax, rewrittenTryBlock, rewrittenCatchBlocks, rewrittenFinally, node.ExitLabelOpt)
+            Return If(rewrittenCatchBlocks.IsDefaultOrEmpty AndAlso rewrittenFinally Is Nothing, rewrittenTryBlock, RewriteTryStatement(node.Syntax, rewrittenTryBlock, rewrittenCatchBlocks, rewrittenFinally, node.ExitLabelOpt))
+        End Function
+
+        Private Shared Function IsMorallyEmpty(statement As BoundStatement) As Boolean
+            If statement Is Nothing Then Return True
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_Try.vb]: Consider using block-If.

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_Try.vb [hunk 6]
```diff
@@ -14,10 +14,35 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
+            Select Case statement.Kind
+                Case BoundKind.NoOpStatement
+                    Return True
+                Case BoundKind.Block
+                    Dim block = DirectCast(statement, BoundBlock)
+                    For Each s In block.Statements
+                        If Not IsMorallyEmpty(s) Then Return False
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_Try.vb]: Consider using block-If.

**Comment by AlekseyTs** [comment]
LGTM, modulo earlier comments.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TryStatement.cs [hunk 7]
```diff
@@ -16,13 +16,60 @@ public override BoundNode VisitTryStatement(BoundTryStatement node)
...
+        {
+            if (statement == null) return true;
+            switch (statement.Kind)
+            {
+                case BoundKind.NoOpStatement:
+                    return true;
+                case BoundKind.Block:
+                    {
+                        var block = (BoundBlock)statement;
+                        for (int i = 0; i < block.Statements.Length; i++)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TryStatement.cs]: Consider using foreach or return block.Statements.Any(HasNoSideEffects);

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TryStatement.cs [hunk 8]
```diff
@@ -16,13 +16,60 @@ public override BoundNode VisitTryStatement(BoundTryStatement node)
...
+                        {
+                            if (!IsMorallyEmpty(block.Statements[i])) return false;
+                        }
+                        return true;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TryStatement.cs]: Consider using foreach or return block.Statements.All(HasNoSideEffects);

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TryStatement.cs (hunk 3 above)
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TryStatement.cs]: Agreed. Consider a name such as HasNoSideEffects and update comments in callers.

**Comment by gafter** [comment]
I've moved the VB optimization into the `RewriteTryStatement` method so other callers will get its benefits.

**Comment by cston** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TryStatement.cs [hunk 9]
```diff
@@ -16,13 +16,61 @@ public override BoundNode VisitTryStatement(BoundTryStatement node)
...
+        /// such as throwing an exception? This implementation is conserviative, in the sense
+        /// that it may return true when the statement actually may have no side effects.
+        /// </summary>
+        private static bool HasSideEffects(BoundStatement statement)
+        {
+            if (statement == null) return false;
+            switch (statement.Kind)
+            {
+                case BoundKind.NoOpStatement:
+                    return true;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TryStatement.cs]: Should we return false here?
