### PR TITLE
Fixing a typo

### LINKED ISSUE #24805: Mispelling of VS code style option
image

"Prefere" instead of "Prefer".

### PR DESCRIPTION
**Pull request by Neme12**
fixes #24805

### CODE REVIEW

**Comment by sharwell** [comment]
@tmeschter @Pilchie Should we be pushing for this in 15.6 or 15.7?

File: src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs [hunk 1]
```diff
@@ -585,14 +585,14 @@ public Customer(string value)
         // {ServicesVSResources.Prefer_colon}
         int fibonacci(int n)
         {{
-            return n <= 1 ? 1 : fibonacci(n - 1) + fibonacci(n - 2);
+            return n <= 1 ? n : fibonacci(n - 1) + fibonacci(n - 2);
```
Comment (sharwell) [inline src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs]: 💭 As a best guess, this was mixed up with the base cases for a recursive definition of x! (factorial) in the original implementation

**Comment by Pilchie** [comment]
15.7 is fine at this point.  While embarrassing, typos are a fact of life...

**Comment by sharwell** [comment]
@Neme12 Would you like to rebase this onto the **dev15.7.x** branch or would you like me to? :smile:

**Comment by Neme12** [comment]
I would like you to if you don't mind :D I started working on #24807 in another branch

File: src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs (hunk 1 above)
Comment (gafter) [reply src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs]: It wasn't wrong before. See http://whatis.techtarget.com/definition/Fibonacci-sequence

Comment (gafter) [reply src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs]: Also https://en.wikipedia.org/wiki/Fibonacci_number

Comment (Neme12) [reply src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs]: but no matter whether you start from 1 or 0, fibonacci(2) is 1, not 2

Comment (Neme12) [reply src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs]: it would have returned 2

Comment (gafter) [reply src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs]: Also http://mathworld.wolfram.com/FibonacciNumber.html and https://www.mathsisfun.com/definitions/fibonacci-sequence.html

Comment (Neme12) [reply src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs]: but in all those links it literally says f(1) is 1 and f(2) is 1, so what do you mean? i don't get it

Comment (Neme12) [reply src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs]: it would have returned f(2)=2 which is wrong

Comment (gafter) [reply src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs]: f(0) is supposed to be 0. f(1) is supposed to be 1. f(2) will be 1 by addition of 0 and 1.

the PR's change makes f(0) 1 instead of 0, and makes f(2) 2 instead of 1, which disagrees with modern convention for the sequence.

Comment (Neme12) [reply src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs]: it also says f(0) may optionally be defined as 0, but f(2)=1 regardless

Comment (Neme12) [reply src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs]: no it doesn't? f(0) will be n<=1 therefore n therefore 0, previously it would have returned f(0)=1

Comment (Neme12) [reply src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs]: i think you are confusing the diff

Comment (gafter) [reply src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs]: Oh, yes, I'm reading the diff backwards!

Comment (Neme12) [reply src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs]: no before it was `n <= 1 ? 1` , not it is `n <= 1 ? n` so before it would have returned f(0) = 1, now it will return 0

**Comment by Neme12** [comment]
done

**Comment by sharwell** [comment]
@Pilchie for ask mode
