### PR TITLE
Make ScanType() and ParseType() agree not to accept pointer types in deconstruction

### LINKED ISSUE #15934: Using a pointer type in a deconstruction crashes the compiler
**Version Used**: https://github.com/dotnet/roslyn/commit/a2df65047264ed08fb3a985056085dbcee821253

**Steps to Reproduce**:
```cs
class C {
    unsafe void M() {
    	(int* x, int y) = M2();
    }
}
```
**Expected Behavior**: The compiler should not crash.

**Actual Behavior**: The compiler crashes with an invalid cast exception. See the [repro and call stack](http://tryroslyn.azurewebsites.net/#b:master/K4OwzghgZgpgBAYwDYTGOBhAUAby3AuANwHsBLAEzgFkAKASn0L0LgEhayQAXAKjgAeAGjhducAJ704AXhoAmBgG4mBAL6q4mzj14ix06osZs8bDWqA=).

### PR DESCRIPTION
**Pull request by gafter**
**Customer scenario**

Crash in deconstruction that attempts to use a pointer type.

**Bugs this fixes:** 

Fixes #15934

**Workarounds, if any**

Don't make that mistake.

**Risk**

Low. This changes an area of the compiler that recently underwent a complete overhaul. The changes here are relatively small and correct an error introduced at that time.

**Performance impact**

Low. The parser logic changes without any significant algorithmic changes.

**Is this a regression from a previous update?**

The previous update was not know to crash in this scenario, however, the scenario underwent a significant spec revision. The affected scenario is now an assignment expression, not a deconstruction declaration. So it is a bug in relatively recent code.

**Root cause analysis:**

We didn't have tests for this combination of features.

**How was the bug found?**

Customer reported.

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet/roslyn-compiler Please review.

**Comment by CyrusNajmabadi** [comment]
> Make ScanType() and ParseType() agree not to accept pointer types in deconstruction 

I'd much rather we accept any and all types, but that we give a good error message stating that pointer types are not legal here.  Generally i like the parser being permissive so that hte tree is good for higher layers and so that we get better error messages . If there's a place in the language where accept some subset of types, generally it's good if hte parser then accepts *all* types in that location.

**Comment by gafter** [comment]
@CyrusNajmabadi We want to treat `a*b` as a multiplication when appearing inside a tuple rather than a declaration of a variable `b` of type `a*`. We don't examine a much larger enclosing and following context to decide which it is. Since pointer types are not permitted here, we simply always treat it as a multiplication.

**Comment by alrz** [comment]
When it's legal to write `(x*y, z) = M();`? ref-returning operator*?

**Comment by gafter** [comment]
@alrz It is _syntactically_ legal to write today. It is just an assignment expression with a tuple on the left. The parser doesn't apply semantic rules to disambiguate.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 1]
```diff
@@ -4057,5 +4057,103 @@ public static void Main()
...
+            switch (a) { case int* b: break; }
+            switch (c) { case var* d: break; }
+            switch (e) { case Typ* f: break; }
+        }
+    }
+}
+";
+            var compilation = CreateCompilationWithMscorlibAndSystemCore(source, options: TestOptions.UnsafeDebugDll);
+            compilation.VerifyDiagnostics(
+                //             if (a is int* b) {}
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: You're likely missing a line of diagnostics/comment here.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 2]
```diff
@@ -4057,5 +4057,103 @@ public static void Main()
...
+            var source =
+@"
+public class Program
+{
+    public static void Main()
+    {
+        const int two = 2;
+        const int three = 3;
+        int six = two * three;
+        System.Console.WriteLine(six is two * three);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: >System.Console.WriteLine(six is two * three); [](start = 8, length = 45)

Consider also testing scenario when result should be false, i.e. 
```
System.Console.WriteLine(five is two * three);
```

**Comment by AlekseyTs** [comment]
LGTM

**Comment by gafter** [comment]
@MattGertz @kevinpi @ManishJayaswal @jaredpar May I please have approval? I crave approval.

**Comment by gafter** [comment]
@srivatsn May I please have approval? I crave approval.
