### PR TITLE
Match Roslyn EE to native EE behaviour with property accessibility

### LINKED ISSUE #18581: Roslyn EE regression with F# debug type proxies
**Version Used**: VS 2017

**Steps to Reproduce**:

Code to reproduce:

```f#
let someMap = ["Hi", 15; "There", 10] |> Map.ofList
```

1. Set a breakpoint after this line of code
2. Look at the "Locals" window to inspect `someMap`. Note how there are no members beneath this object, only "Raw View".

This regression is due to [TypeHelpers.cs@192](https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/ExpressionEvaluator/Core/Source/ResultProvider/Helpers/TypeHelpers.cs#L192-L194). An assumption was made by the author of this code that is invalid with F#. In F#, it is impossible to have public members on internal classes. Therefore any debug type proxy that is an internal type does not work with F# and the Roslyn EE. Note that this is a *regression* compared to the behaviour of the native EE (as noted in the comments of TypeHelpers.cs).

**Expected Behavior**:

This is the behaviour with VS 2015 or by enabling the "Legacy C#/VB.NET expression evaluator" in VS 2017:

image

**Actual Behavior**:

image

### PR DESCRIPTION
**Pull request by saul**
**Customer scenario**

The Roslyn EE breaks debug proxy types in FSharp.Core, meaning that maps, lists and sets are near impossible to debug as the Roslyn EE thinks all of the properties on the debug proxy types are not public. Roslyn EE is correct - the properties aren't public - but the Native EE accepted this. It's important to note that properties on internal types in F# are *impossible* to make public.

I believe that as the Roslyn EE causes a regression with F# compared to the Native EE, the old behaviour should be used instead.

See https://github.com/Microsoft/visualfsharp/issues/2184#issuecomment-292645097. 

**Before**:

image

**After**:

image

**Bugs this fixes:**

Fixes #18581, fixes https://github.com/Microsoft/visualfsharp/issues/2184

**Workarounds, if any**

**Risk**

**Performance impact**

 "Low"

**Is this a regression from a previous update?**

**Root cause analysis:**

**How did we miss it? What tests are we adding to guard against it in the future?**

**How was the bug found?**

customer reported

### CODE REVIEW

**Comment by tmat** [comment]
👎

This change skips the visibility check completely. With the change even entirely private property in C# will be shown. I'd be more willing to accept a change that displays the property if at least one of the acessors are visible. Even then it feels like a hack -- we should not compensate for bugs in F# compiler in C# EEs. 

I'd rather see F# having its own EE that implements the workaround. Roslyn provides the base class for Result Provider from which C# and VB providers inherit. Step one would be to inherit F# result provider -- it can copy the C# one for now and implement F# semantics later on.

**Comment by dsyme** [comment]
> This change skips the visibility check completely. 

Why is the visibility check even there?  Why would you want to stop a valid debug proxy working?    

Also, is there a public spec that says you must have the "public" on the method of an otherwise internal type?

**Comment by dsyme** [comment]
@tmat Also, would an F# EE actually be used when in a C# code file, looking at these values (in C#-calls-F# scenarios)?

**Comment by saul** [comment]
I'd just like to add that I think Roslyn EE is doing the right thing here. It's how I would write it - it makes sense.

However I think that as this PR means that private getter, public setter properties are shown on types in the debugger (how common are these?), restoring an old behaviour and removing no functionality, is significantly outweighed by the fact that F# users cannot view the contents of collections.

**Comment by tmat** [comment]
@dsyme @saul I gathered this is a bug in F# compiler from the discussion on https://github.com/Microsoft/visualfsharp/issues/2184#issuecomment-292645097:

> I think this is something we need to fix from the F# compiler side. I'm just awaiting @dsyme's comment, as I think we're setting the accessibility of property getter/setter methods incorrectly.

But you make good points about debugging older F# bits and looking at F# objects from C# method. As I said, I'd be willing to accept the change that displays the property if at least one of the accessors is visible. That seems to be what native EE actually does based on my observation:

```
    [DebuggerTypeProxy(typeof(X))]
    public class C { }

    internal class X
    {
        internal X(C c) { }
        private int Private { get; set; }
        internal int Internal { get; set; }
        public int Public { get; set; }
        internal int InternalPrivate { get; private set; }
        internal int PrivateInternal { private get; set; }
        public int PrivatePublic { private get; set; }
        public int PublicPrivate { get; private set; }
    }
```

Roslyn EE:
image

Legacy EE:
image

**Comment by saul** [comment]
@tmat I don't think your conclusion is entirely true re how the native EE handles this.

Looking at the IL for Microsoft.FSharp.Collections.MapDebugView`2<TKey, TValue>, it doesn't have any public getter/setters for the Items property, yet it appears fine in the native EE debugger view.

```
	.method assembly hidebysig specialname 
		instance valuetype [mscorlib]System.Collections.Generic.KeyValuePair`2<!TKey, !TValue>[] get_Items () cil managed

	.property instance valuetype [mscorlib]System.Collections.Generic.KeyValuePair`2<!TKey, !TValue>[] Items()
	{
		.custom instance void [mscorlib]System.Diagnostics.DebuggerBrowsableAttribute::.ctor(valuetype [mscorlib]System.Diagnostics.DebuggerBrowsableState) = (
			01 00 03 00 00 00 00 00
		)
		.get instance valuetype [mscorlib]System.Collections.Generic.KeyValuePair`2<!0, !1>[] Microsoft.FSharp.Collections.MapDebugView`2::get_Items()
	}

```

**Comment by saul** [comment]
It looks like having a `DebuggerBrowsable` attribute on the property makes the native EE ignore any accessibility constraints, try this out:

```c#
    struct Something
    {
        public int Foo;
    }

    [DebuggerTypeProxy(typeof(X))]
    public class C { }

    internal class X
    {
        internal X(C c) { }

        [DebuggerBrowsable(DebuggerBrowsableState.RootHidden)]
        internal Something Internal { get { return new Something(); } }
    }
```

**Comment by tmat** [comment]
@saul You are right. Presence of the attribute overrides the visibility check and the native EE shows the return value of the property getter for all properties that have a getter regardless of their visibility. That's not however what your change does. The change needs to be done in the caller of the IsPublic member where it should check for the attribute. If the attribute is not present the current IsPublic method should be used as is. Otherwise ```m => true``` should be passed in as a member filter.

**Comment by saul** [comment]
@tmat Agreed - I'll get working on that now.

**Comment by saul** [comment]
Ready for review - any pointers as to where I should place some tests for this?

**Comment by tmat** [comment]
test this please

**Comment by saul** [comment]
@tmat I've fixed the existing tests and added a new test to verify the behaviour is as we expect. Expecting this to go green.

It's worth noting that I found that all of the DebuggerBrowsableAttributeTests tests are skipped at the moment because the class is internal. Is this on purpose?

**Comment by tmat** [comment]
> It's worth noting that I found that all of the DebuggerBrowsableAttributeTests tests are skipped at the moment because the class is internal. 

@saul Good catch. Not intentional, could you please make them public?

**Comment by tmat** [comment]
/cc @cston 
👍

**Comment by tmat** [comment]
test windows_debug_vs-integration_prtest please
test windows_release_vs-integration_prtest please
https://github.com/dotnet/roslyn/issues/18714

File: src/ExpressionEvaluator/CSharp/Test/ResultProvider/DebuggerTypeProxyAttributeTests.cs [hunk 1]
```diff
@@ -1100,5 +1100,50 @@ public P(C c)
             Verify(children,
                 EvalResult("F", "3", "int", "(new C(3)).F"));
         }
+
+        [Fact]
```
Comment (cston) [inline src/ExpressionEvaluator/CSharp/Test/ResultProvider/DebuggerTypeProxyAttributeTests.cs]: Please add `[WorkItem(18581, "https://github.com/dotnet/roslyn/issues/18581")]`.

**Comment by cston** [comment]
LGTM. Thanks for fixing this @saul.

**Comment by saul** [comment]
@tmat I'll make the tests public again but one is failing - shall I change it so it passes?

Also I'm not sure why the VB symbol highlighting integration test is now failing - I've no idea where to even start with that. Any pointers would be appeciated as it doesn't look flaky.

**Comment by tmat** [comment]
Yes, please fix the failing test, unless the results don't seem correct.

You can ignore the failing integration test.

**Comment by saul** [comment]
@tmat I've done the review comments and fixed the one broken DebuggerBrowsableAttributeTest.

File: src/ExpressionEvaluator/Core/Source/ResultProvider/Expansion/MemberExpansion.cs [hunk 2]
```diff
@@ -26,7 +26,8 @@ internal sealed class MemberExpansion : Expansion
             DkmClrValue value,
             ExpansionFlags flags,
             Predicate<MemberInfo> predicate,
-            ResultProvider resultProvider)
+            ResultProvider resultProvider,
+            bool isProxyType)
```
Comment (cston) [inline src/ExpressionEvaluator/Core/Source/ResultProvider/Expansion/MemberExpansion.cs]: Did an existing test fail without `isProxyType`? If not, please add a test that demonstrates the difference.

Comment (saul) [inline src/ExpressionEvaluator/Core/Source/ResultProvider/Expansion/MemberExpansion.cs]: Committed a test to ensure that the behaviour on non-proxy types is not affected by this PR in 97164c9.

**Comment by cston** [comment]
LGTM

**Comment by jinujoseph** [comment]
test windows_debug_vs-integration_prtest please

**Comment by jinujoseph** [comment]
@MattGertz fyi

**Comment by tmat** [comment]
@MattGertz Clicked merge before realizing ask mode approval is needed.

**Comment by dsyme** [comment]
Thank you everyone for helping to resolve this issue, really great to see the cooperation and eventual precision in the fix
