### PR TITLE
Track whether or not a use of a range variable is a capture.

### LINKED ISSUE #1291: C# data flow analysis incorrectly reports range variable of the from clause as captured
Given the following method body:
```c#
    public static void Main()
    {
        int y = 1;
        {
            int x = 2;
            var f2 = from a in new[] { 1 } select a + y;
            var f3 = from a in new[] { 1 } where x > 0 select a;
        }
    }
```

```model.AnalyzeDataFlow(memberBody).Captured```

returns 4 variables:
```
[0]          Local System.Int32 y       Microsoft.CodeAnalysis.CSharp.Symbol {Microsoft.CodeAnalysis.CSharp.Symbols.SourceLocalSymbol.LocalWithInitializer}
[1]          Local System.Int32 x       Microsoft.CodeAnalysis.CSharp.Symbol {Microsoft.CodeAnalysis.CSharp.Symbols.SourceLocalSymbol.LocalWithInitializer}
[2]          RangeVariable ? a            Microsoft.CodeAnalysis.CSharp.Symbol {Microsoft.CodeAnalysis.CSharp.Symbols.RangeVariableSymbol}
[3]          RangeVariable ? a            Microsoft.CodeAnalysis.CSharp.Symbol {Microsoft.CodeAnalysis.CSharp.Symbols.RangeVariableSymbol}
```
However, the range variable a is not lifted to closure in this case. It’s translated to parameters of the selector lambdas.

Equivalent code in VB
```VB
    Sub F()
        Dim y As Integer = 1
        Do
            Dim x As Integer = 2
            Dim f2 = From a In {1} Select a + y
            Dim f3 = From a In {1} Where x > 0 Select a
        Loop
    End Sub
```
Only reports x and y as captured. 

Seems like C# got it wrong.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #1291

### CODE REVIEW

**Comment by gafter** [comment]
@jaredpar @VSadov @AlekseyTs @agocke @VladimirReshetnikov Could a couple of you review this please?

Note that the "related" VB issue #564 will be done next, separately.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 1]
```diff
@@ -334,20 +334,25 @@ protected void Analyze(ref bool badRegion, DiagnosticBag diagnostics)
             }
         }
 
-        private void CheckCaptured(Symbol variable)
+        private void CheckCaptured(Symbol variable, Symbol underlyingVariable = null)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: Consider adding a comment what is the underlyingVariable and when it should be passed in.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: Also, can we use more specific type for it?

File: src/Compilers/CSharp/Portable/FlowAnalysis/ReadWriteWalker.cs [hunk 2]
```diff
@@ -220,7 +220,28 @@ public override void VisitForEachIterationVariable(BoundForEachStatement node)
...
         public override BoundNode VisitRangeVariable(BoundRangeVariable node)
         {
-            NoteRead(node.RangeVariableSymbol);
+            // Compute the "underlying symbol" for a read of the range variable
+            Symbol underlyingSymbol = GetUnderlyingVariable(node.Value);
+            NoteRead(node.RangeVariableSymbol, underlyingSymbol);
+            return null;
+        }
+
+        private Symbol GetUnderlyingVariable(BoundNode underlying)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/ReadWriteWalker.cs]: It looks like this method can return only ParameterSymbol or null. Consider changing return type to ParameterSymbol. Also, consider adding a comment about the purpose of the method and possibly renaming it to GetRangeVariableUnderlyingParameter because it never returns a variable. Consider renaming new parameter in other APIs to rangeVariableUnderlyingParameter and using ParameterSymbol as its type.

File: src/Compilers/CSharp/Portable/FlowAnalysis/ReadWriteWalker.cs [hunk 3]
```diff
@@ -220,7 +220,28 @@ public override void VisitForEachIterationVariable(BoundForEachStatement node)
...
+            {
+                switch (underlying.Kind)
+                {
+                    case BoundKind.Parameter:
+                        return ((BoundParameter)underlying).ParameterSymbol;
+                    case BoundKind.PropertyAccess:
+                        underlying = ((BoundPropertyAccess)underlying).ReceiverOpt;
+                        continue;
+                    default:
+                        return null;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/ReadWriteWalker.cs]: Is this normal to not find a parameter? Should we Assert or throw?

File: src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs [hunk 4]
```diff
@@ -4563,6 +4563,32 @@ public static void Main()
...
+            var f2 = from a in data select a + y;
+            var f3 = from a in data where x > 0 select a;
+            var f4 = from a in data let b = 1 select /*<bind>*/a + b/*</bind>*/;
+            var f5 = from c in data where M(() => c) select c;
+        }
+    }
+    private static bool M(Func<int> f) => true;
+}");
+            var dataFlowAnalysisResults = analysisResults;
+            Assert.Equal("y, x, c", GetSymbolNamesJoined(dataFlowAnalysisResults.Captured));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs]: It feels like whether a range variable is captured should be determined in relation to the range being analyzed. For example, 'c' is captured in 'where' clause, but is not captured in 'select' clause. So, I would expect that 'c' is not captured given the range used by the test.

Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs]: @tmat Please chime in on this topic. How do you determine *which* instance of a range variable is captured for EnC. Or perhaps you don't need to?

Comment (tmat) [inline src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs]: The captured variable set is independent of the span for regular local variables in the current implementation. So the range variables should be the same. In my analysis I get the set for the method body and then for each lambda I determine variables read and written and intersect these sets.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs]: @tmat, let's talk offline, I would like to understand the scenario better.

Comment (tmat) [inline src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs]: Aleksey is right. Range variables are different and I can't use the same approach that I use for locals. We need DataFlowAnalysis to return a set of captures within given region.

Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs]: Filed #1545 to capture the required API change. For now I'll change this to only return captured range variables from inside the region, but ultimately we will want to rationalize range variables and other variables to be treated uniformly as described in #1545.

File: src/Compilers/CSharp/Portable/FlowAnalysis/ReadWriteWalker.cs (hunk 3 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/FlowAnalysis/ReadWriteWalker.cs]: I don't believe we have requirements for its behavior in error scenarios, so I don't think throwing is a good idea.

**Comment by gafter** [comment]
I've updated the PR as we had discussed. Please review.

**Comment by AlekseyTs** [comment]
LGTM
