### PR TITLE
Visit unreachable `when` clauses by `NullableWalker`

### LINKED ISSUE #65050: Assertion in nullable walker: "Did not find BoundBinaryOperator in the map."
Got this crash:

```
System.InvalidOperationException: Did not find Microsoft.CodeAnalysis.CSharp.BoundBinaryOperator `s.Length > 0` in the map.
      at Microsoft.CodeAnalysis.Remote.ThrowingTraceListener.Fail(String message, String detailMessage) in C:\github\roslyn\src\Workspaces\Remote\ServiceHub\Host\ThrowingTraceListener.cs:line 27
      at System.Diagnostics.TraceInternal.Fail(String message)
      at System.Diagnostics.Debug.Assert(Boolean condition, String message)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VerifyExpression(BoundExpression expression, Boolean 
```

Full stack:

<details>

```
StreamJsonRpc.RemoteInvocationException: Did not find Microsoft.CodeAnalysis.CSharp.BoundBinaryOperator `s.Length > 0` in the map.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__145`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__20`1.MoveNext() in C:\github\roslyn\src\Workspaces\Remote\Core\BrokeredServiceConnection.cs:line 239
RPC server exception:
System.InvalidOperationException: Did not find Microsoft.CodeAnalysis.CSharp.BoundBinaryOperator `s.Length > 0` in the map.
      at Microsoft.CodeAnalysis.Remote.ThrowingTraceListener.Fail(String message, String detailMessage) in C:\github\roslyn\src\Workspaces\Remote\ServiceHub\Host\ThrowingTraceListener.cs:line 27
      at System.Diagnostics.TraceInternal.Fail(String message)
      at System.Diagnostics.Debug.Assert(Boolean condition, String message)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VerifyExpression(BoundExpression expression, Boolean overrideSkippedExpression) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.DebugVerifier.cs:line 61
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitExpressionWithoutStackGuard(BoundExpression node) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.DebugVerifier.cs:line 68
      at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node) in C:\github\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 212
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(BoundNode node) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.DebugVerifier.cs:line 83
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitSwitchExpressionArm(BoundSwitchExpressionArm node) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.DebugVerifier.cs:line 249
      at Microsoft.CodeAnalysis.CSharp.BoundSwitchExpressionArm.Accept(BoundTreeVisitor visitor) in C:\github\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs:line 4662
      at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node) in C:\github\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 151
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(BoundNode node) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.DebugVerifier.cs:line 85
      at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList[T](ImmutableArray`1 list) in C:\github\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs:line 22
      at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitConvertedSwitchExpression(BoundConvertedSwitchExpression node) in C:\github\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs:line 9742
      at Microsoft.CodeAnalysis.CSharp.BoundConvertedSwitchExpression.Accept(BoundTreeVisitor visitor) in C:\github\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs:line 4724
      at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node) in C:\github\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 151
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitExpressionWithoutStackGuard(BoundExpression node) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.DebugVerifier.cs:line 69
      at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node) in C:\github\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 212
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(BoundNode node) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.DebugVerifier.cs:line 83
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitBadExpression(BoundBadExpression node) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.DebugVerifier.cs:line 102
      at Microsoft.CodeAnalysis.CSharp.BoundBadExpression.Accept(BoundTreeVisitor visitor) in C:\github\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs:line 992
      at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node) in C:\github\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 151
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitExpressionWithoutStackGuard(BoundExpression node) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.DebugVerifier.cs:line 69
      at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node) in C:\github\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 212
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(BoundNode node) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.DebugVerifier.cs:line 83
      at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitConversion(BoundConversion node) in C:\github\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs:line 9504
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitConversion(BoundConversion node) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.DebugVerifier.cs:line 277
      at Microsoft.CodeAnalysis.CSharp.BoundConversion.Accept(BoundTreeVisitor visitor) in C:\github\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs:line 2721
      at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node) in C:\github\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 151
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitExpressionWithoutStackGuard(BoundExpression node) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.DebugVerifier.cs:line 69
      at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node) in C:\github\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 212
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(BoundNode node) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.DebugVerifier.cs:line 83
      at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitLocalDeclaration(BoundLocalDeclaration node) in C:\github\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs:line 9554
      at Microsoft.CodeAnalysis.CSharp.BoundLocalDeclaration.Accept(BoundTreeVisitor visitor) in C:\github\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs:line 3158
      at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node) in C:\github\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 151
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(BoundNode node) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.DebugVerifier.cs:line 85
      at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList[T](ImmutableArray`1 list) in C:\github\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeWalker.cs:line 22
      at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitBlock(BoundBlock node) in C:\github\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs:line 9538
      at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor) in C:\github\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs:line 3062
      at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node) in C:\github\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 151
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(BoundNode node) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.DebugVerifier.cs:line 85
      at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitNonConstructorMethodBody(BoundNonConstructorMethodBody node) in C:\github\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs:line 10213
      at Microsoft.CodeAnalysis.CSharp.BoundNonConstructorMethodBody.Accept(BoundTreeVisitor visitor) in C:\github\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs:line 8241
      at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node) in C:\github\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 151
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(BoundNode node) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.DebugVerifier.cs:line 85
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Verify(ImmutableDictionary`2 analyzedNullabilityMap, SnapshotManager snapshotManagerOpt, BoundNode node) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.DebugVerifier.cs:line 39
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.AnalyzeWithSemanticInfo(CSharpCompilation compilation, Symbol symbol, BoundNode node, Binder binder, VariableState initialState, DiagnosticBag diagnostics, Boolean createSnapshots, Boolean requiresAnalysis) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs:line 1459
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.AnalyzeAndRewrite(CSharpCompilation compilation, Symbol symbol, BoundNode node, Binder binder, VariableState initialState, DiagnosticBag diagnostics, Boolean createSnapshots, SnapshotManager& snapshotManager, ImmutableDictionary`2& remappedSymbols) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.cs:line 1412
      at Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.RewriteNullableBoundNodesWithSnapshots(BoundNode boundRoot, Binder binder, DiagnosticBag diagnostics, Boolean createSnapshots, SnapshotManager& snapshotManager, ImmutableDictionary`2& remappedSymbols) in C:\github\roslyn\src\Compilers\CSharp\Portable\Compilation\MethodBodySemanticModel.cs:line 297
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.<EnsureNullabilityAnalysisPerformedIfNecessary>g__rewriteAndCache|130_1(<>c__DisplayClass130_0& ) in C:\github\roslyn\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1982
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.EnsureNullabilityAnalysisPerformedIfNecessary() in C:\github\roslyn\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1960
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node) in C:\github\roslyn\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 2052
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode(CSharpSyntaxNode node) in C:\github\roslyn\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 544
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node, CSharpSyntaxNode& bindableNode, BoundNode& lowestBoundNode, BoundNode& highestBoundNode, BoundNode& boundParent) in C:\github\roslyn\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1328
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken) in C:\github\roslyn\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1206
      at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken) in C:\github\roslyn\src\Compilers\CSharp\Portable\Compilation\SyntaxTreeSemanticModel.cs:line 215
      at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken) in C:\github\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 573
      at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoFromNode(SyntaxNode node, CancellationToken cancellationToken) in C:\github\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 4939
      at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoCore(SyntaxNode node, CancellationToken cancellationToken) in C:\github\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 5038
      at Microsoft.CodeAnalysis.SemanticModel.GetSymbolInfo(SyntaxNode node, CancellationToken cancellationToken) in C:\github\roslyn\src\Compilers\Core\Portable\Compilation\SemanticModel.cs:line 99
      at Microsoft.CodeAnalysis.ModelExtensions.GetSymbolInfo(SemanticModel semanticModel, SyntaxNode node, CancellationToken cancellationToken) in C:\github\roslyn\src\Compilers\Core\Portable\Compilation\Extensions.cs:line 21
      at Microsoft.CodeAnalysis.CSharp.Classification.OperatorOverloadSyntaxClassifier.AddClassifications(SyntaxNode syntax, SemanticModel semanticModel, ClassificationOptions options, ArrayBuilder`1 result, CancellationToken cancellationToken) in C:\github\roslyn\src\Workspaces\CSharp\Portable\Classification\SyntaxClassification\OperatorOverloadSyntaxClassifier.cs:line 31
      at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ClassifyNode(SyntaxNode syntax) in C:\github\roslyn\src\Workspaces\Core\Portable\Classification\SyntaxClassification\AbstractSyntaxClassificationService.Worker.cs:line 131
      at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ClassifyNodeOrToken(SyntaxNodeOrToken nodeOrToken) in C:\github\roslyn\src\Workspaces\Core\Portable\Classification\SyntaxClassification\AbstractSyntaxClassificationService.Worker.cs:line 114
      at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ProcessNodes() in C:\github\roslyn\src\Workspaces\Core\Portable\Classification\SyntaxClassification\AbstractSyntaxClassificationService.Worker.cs:line 99
      at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.Classify(SemanticModel semanticModel, TextSpan textSpan, ArrayBuilder`1 list, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, ClassificationOptions options, CancellationToken cancellationToken) in C:\github\roslyn\src\Workspaces\Core\Portable\Classification\SyntaxClassification\AbstractSyntaxClassificationService.Worker.cs:line 67
      at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.AddSemanticClassifications(SemanticModel semanticModel, TextSpan textSpan, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, ArrayBuilder`1 result, ClassificationOptions options, CancellationToken cancellationToken) in C:\github\roslyn\src\Workspaces\Core\Portable\Classification\SyntaxClassification\AbstractSyntaxClassificationService.cs:line 60
      at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.<AddSemanticClassificationsAsync>d__6.MoveNext() in C:\github\roslyn\src\Workspaces\Core\Portable\Classification\SyntaxClassification\AbstractSyntaxClassificationService.cs:line 43
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.<AddClassificationsInCurrentProcessAsync>d__7.MoveNext() in C:\github\roslyn\src\Workspaces\Core\Portable\Classification\AbstractClassificationService.cs:line 160
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.RemoteSemanticClassificationService.<>c__DisplayClass20_0.<<GetClassificationsAsync>b__0>d.MoveNext() in C:\github\roslyn\src\Workspaces\Remote\ServiceHub\Services\SemanticClassification\RemoteSemanticClassificationService.cs:line 44
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<<RunWithSolutionAsync>g__GetStreamImplementation|8_0>d`1.MoveNext() in C:\github\roslyn\src\Workspaces\Remote\ServiceHub\Host\RemoteWorkspace.cs:line 156
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<<RunWithSolutionAsync>g__GetStreamImplementation|8_0>d`1.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
      at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass9_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext() in C:\github\roslyn\src\Workspaces\Remote\ServiceHub\Host\RemoteWorkspace.cs:line 250
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass9_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext() in C:\github\roslyn\src\Workspaces\Remote\ServiceHub\Host\RemoteWorkspace.cs:line 250
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass9_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
      at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<RunWithSolutionAsync>d__9`1.MoveNext() in C:\github\roslyn\src\Workspaces\Remote\ServiceHub\Host\RemoteWorkspace.cs:line 178
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<RunWithSolutionAsync>d__9`1.MoveNext() in C:\github\roslyn\src\Workspaces\Remote\ServiceHub\Host\RemoteWorkspace.cs:line 178
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<RunWithSolutionAsync>d__9`1.MoveNext() in C:\github\roslyn\src\Workspaces\Remote\ServiceHub\Host\RemoteWorkspace.cs:line 186
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<RunWithSolutionAsync>d__9`1.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
      at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<RunWithSolutionAsync>d__8`1.MoveNext() in C:\github\roslyn\src\Workspaces\Remote\ServiceHub\Host\RemoteWorkspace.cs:line 134
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<RunWithSolutionAsync>d__8`1.MoveNext() in C:\github\roslyn\src\Workspaces\Remote\ServiceHub\Host\RemoteWorkspace.cs:line 134
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunWithSolutionAsync>d__11`1.MoveNext() in C:\github\roslyn\src\Workspaces\Remote\ServiceHub\Services\BrokeredServiceBase.cs:line 95
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__15`1.MoveNext() in C:\github\roslyn\src\Workspaces\Remote\ServiceHub\Services\BrokeredServiceBase.cs:line 136
```

</details>

I was in teh middle of writing:

```C#
using System.Linq.Expressions;

class Foo
{

}

public class Test
{
    int this[int index] { get { return 0; } set { } } // try to find references for this property declaration

    Test Create(Guid _fooId)
    {
        Expression<Func<Foo, bool>> filter = (_fooId, _fooOtherId) switch
        {
            (Guid fooId, _) => foo => foo.Id == _fooId.Value,
            (null, string s) when s.Length > 0 => foo => foo.OtherId == _fooOtherId,
            _ => null
        };
    }
}
```

Likely relates to https://github.com/dotnet/roslyn/issues/65053

### PR DESCRIPTION
**Pull request by jjonescz**
Fixes #65050.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs [hunk 1]
```diff
@@ -865,7 +872,14 @@ private void VisitSwitchExpressionCore(BoundSwitchExpression node, bool inferTyp
...
                 TakeIncrementalSnapshot(arm);
-                VisitPatternForRewriting(arm.Pattern);
+
+                if (!State.Reachable && arm.WhenClause != null)
+                {
+                    // Unreachable when clauses are not visited in `LearnFromDecisionDag`.
+                    VisitForRewriting(arm.WhenClause);
+                }
+
+                VisitForRewriting(arm.Pattern);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs:882]: It may not make an observable difference, but it makes the most sense to me to visit the WhenClause after the Pattern. I think of the when-clause as being evaluated only after the pattern is found to match.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 2]
```diff
@@ -156707,5 +156707,56 @@ public static void DoWork(List<Goo> list, string unrelatedObject)
...
+                        return b switch
+                        {
+                            _ when s.Length == 0 => s,
+                            _ => null,
+                            true when s.Length > 0 => s,
+                        };
+                    }
+                }
+                """;
+            CreateCompilation(source).VerifyDiagnostics(
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:156729]: It might be good to check the nullability info coming from public API as well, a la NullablePublicAPITests. Probably, everything will always show as non-null due to being visited in an unreachable state. But still may be useful for completeness.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs (hunk 1 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs]: That makes sense, thanks. Moved.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 3]
```diff
@@ -156715,21 +156715,36 @@ public void UnreachableWhenClause_SwitchExpression()
...
                 Diagnostic(ErrorCode.ERR_SwitchArmSubsumed, "true").WithLocation(10, 13));
+
+            var syntaxTree = comp.SyntaxTrees.Single();
+            var model = comp.GetSemanticModel(syntaxTree);
+
+            var arms = syntaxTree.GetRoot().DescendantNodes().OfType<SwitchExpressionArmSyntax>().ToImmutableArray();
+            Assert.Equal(3, arms.Length);
+            var unreachableArm = arms[^1];
+
+            var identifiers = unreachableArm.DescendantNodes().OfType<IdentifierNameSyntax>();
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:156741]: Should we assert anything like the value of `identifiers.Count()` or the string representation of each, to make it more clear what is being tested?

**Comment by RikkiGibson** [comment]
Minor procedural nit: could you please avoid hitting *Resolve conversation*, and instead indicate a PR comment is addressed by using the 👍 reaction, or by replying. Then I can more easily review the conversations and mark them resolved as appropriate.

**Review by RikkiGibson — APPROVED** [review]

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 2)
