### PR TITLE
Learn from comparisons to non-constant, non-null values

### LINKED ISSUE #34942: Unexpected nullable warning due to null-conditional access
**Version Used**:
3.1.0-beta1-19172-05+edd2de88fb3e84a097fb30b4070e0f219f624e40

**Steps to Reproduce**:
```C#
#nullable enable
using System;

public class Program
{
    static void Main()
    {
        string? value = "42";
        int count = 84;
        if (value?.Length == count)
        {
            Console.WriteLine(value.Length); // warning
        }
    }
}
```

Even though value was explicitly set to a non-null value, and even though the `if (value?.Length == count)` effectively expands to `if (value != null && value.Length == count)` and we could only end up inside the `if` block if `value` is non-null, this still warns with "Possible dereference of a null reference." on `value.Length`.

Interestingly, changing the `count` to be a const makes it no longer warn:
```C#
#nullable enable
using System;

public class Program
{
    static void Main()
    {
        string? value = "42";
        const int count = 84;
        if (value?.Length == count)
        {
            Console.WriteLine(value.Length); // no warning
        }
    }
}
```

cc: @dotnet/nullablefc

### PR DESCRIPTION
**Pull request by RikkiGibson**
Resolves #34942

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 1]
```diff
@@ -21867,18 +21867,15 @@ void M(Delegate d, string? s)
     {
         if (s != string.Empty) s.ToString(); // warn
         d.BeginInvoke(s, null, null);
-        s.ToString(); // warn 2
+        s.ToString();
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: I think removing this warning makes sense because in the case where a null `s` is passed to the method, we've already hit the first call to `s.ToString()`.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 2]
```diff
@@ -2043,11 +2043,11 @@ protected override void AfterLeftChildHasBeenVisited(BoundBinaryOperator binary)
 
             // learn from non-null constant
             BoundExpression operandComparedToNonNull = null;
-            if (isNonNullConstant(binary.Left))
+            if (leftType.IsNotNull && rightType.MayBeNull && binary.Right.ConstantValue?.IsNull != true)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: The point here is to avoid attempting to learn from a comparison between a null literal and a not-null expression so that we can continue on to the part where we learn from comparison to null.

**Comment by RikkiGibson** [comment]
>             // learn from null constant

The non-null case changed to work for any expression determined to be non-null, not just constants. Does this need to change too?

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:2076 in e8567ea. [](commit_id = e8567ea66ca78c544855eeee3619c1ba3275b245, deletion_comment = False)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 3]
```diff
@@ -2041,13 +2041,13 @@ protected override void AfterLeftChildHasBeenVisited(BoundBinaryOperator binary)
...
-            // learn from non-null constant
+            // learn from non-null expression
             BoundExpression operandComparedToNonNull = null;
-            if (isNonNullConstant(binary.Left))
+            if (leftType.IsNotNull && rightType.MayBeNull && binary.Right.ConstantValue?.IsNull != true)
             {
                 operandComparedToNonNull = binary.Right;
             }
-            else if (isNonNullConstant(binary.Right))
+            else if (leftType.MayBeNull && binary.Left.ConstantValue?.IsNull != true && rightType.IsNotNull)
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >binary.Left.ConstantValue?.IsNull [](start = 43, length = 33)

Why don't we have to skip through nullable conversions like we were doing previously? What happens if you were to do `left?.IntProp != (int?)null`?

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 4]
```diff
@@ -95651,6 +95648,29 @@ class Box<T>
                 Diagnostic(ErrorCode.ERR_BadBinaryOps, "x == null").WithArguments("==", "T", "<null>").WithLocation(53, 13));
         }
 
+        [Fact, WorkItem(34942, "https://github.com/dotnet/roslyn/issues/34942")]
+        public void ConditionalExpression_InferredNullability()
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Please add some more tests, especially around using these comparisons in more complicated expressions (where this is `&&`/`||` with something else) and in ternary operators.

**Comment by 333fred** [comment]
Done review pass (commit 4)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 2 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Please add some test where the expression is non-null due to a conversion.
```
class A
{
  // can implicitly convert A? to B
}
class B { }
...
if ( /*implicit conversion here*/ maybeNullA == nonNullB) maybeNullA.ToString(); // still expecting warning
```

---
In reply to: [287527897](https://github.com/dotnet/roslyn/pull/35953#discussion_r287527897) [](ancestors = 287527897)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 5]
```diff
@@ -2041,13 +2041,13 @@ protected override void AfterLeftChildHasBeenVisited(BoundBinaryOperator binary)
 
             BinaryOperatorKind op = binary.OperatorKind.Operator();
 
-            // learn from non-null constant
+            // learn from non-null expression
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >learn from non-null expression [](start = 15, length = 30)

I didn't understand the change in comment. It looks like we're still learning if there is a non-null constant (`binary.Right.ConstantValue?.IsNull != true`)

**Comment by jcouv** [comment]
>             // learn from null constant

I don't think so. I think this can stay as-is.

There are two categories: (1) null constant (most confidence of nullness), and (2) maybe-null expressions (this is the most conservative inference). I don't think we can learn from a maybe-null expression, because it offers less confidence than a null constant (the `null` should definitely keep a maybe-null state) or a not-null expression (that inference is stronger, more conservative, than a maybe-null inference).

---
In reply to: [495802426](https://github.com/dotnet/roslyn/pull/35953#issuecomment-495802426) [](ancestors = 495802426)

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:2076 in e8567ea. [](commit_id = e8567ea66ca78c544855eeee3619c1ba3275b245, deletion_comment = False)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 3 above)
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >rightType.IsNotNull [](start = 88, length = 19)

Please sort this condition so that it mirrors the one above.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: It appears that nullable conversions have a ConstantValue when the value being converted is `null`, but not when the value being converted is non-null. Tracked in #24380

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Basically, if the decision gets made one way (nullable conversions from constants should have ConstantValues) this code can stay as-is. If it gets made the other way (no nullable conversion should have a ConstantValue), this code may have to change.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: I simplified this code by checking for a null constant before looking for a NonNull to MaybeNull comparison.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: It looks like a comparison between values of type A and B will not cause a user-defined implicit conversion to occur--you have to cast. Will add as similar of a test to what you've described as possible.

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAmARgFgAoUnAZgAJ8qBBKgb1KtZupwIDYq0wAHDGgDGaGFQD2/RBBgSEVAEIAKBhACUVALwA+KgDs4AdyXL1AblIBfUuQ54lTa7ZKUaDgMJOSbdjQAsVACyZt6+vmraBgCuGBiWPuGsilTAUYYmKhYsSbwAZlTKENpaqZqMVDlJNolJVeFoBcrKiurFWqXA5fW+Nb3WQA===

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 6]
```diff
@@ -95651,6 +95648,126 @@ class Box<T>
...
+
+public class Program
+{
+    static void Main()
+    {
+        string? value = ""42"";
+        int? i = null;
+        if (value?.Length == i)
+        {
+            Console.WriteLine(value.Length);
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Please add some `// 1|2` comments to these so we can tell them apart easily.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 7]
```diff
@@ -95651,6 +95648,126 @@ class Box<T>
...
+        string? x = ""42"";
+        string? y = ""43"";
+        if (x?.Length == 2 && y?.Length == 2)
+        {
+            Console.WriteLine(x.Length);
+            Console.WriteLine(y.Length);
+        }
+        else
+        {
+            Console.WriteLine(x.Length);
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Also for these, as it's not immediately obvious that the warnings are on these lines as opposed to the lines above.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Haven't added a test using `||` (yet?) but we did learn some new things about ternary operators.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 6 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Done

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 8]
```diff
@@ -95651,6 +95648,241 @@ class Box<T>
...
+public class B { }
+
+
+public class Program
+{
+    static void Main()
+    {
+        A a = new A();
+        B b = new B();
+        if ((B)a.P == b)
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >if ((B)a.P == b) [](start = 8, length = 16)

Consider testing the same with an implicit conversion operator and without the explicit cast.
Also, I'm not sure why you need a property. It would be more direct to test `if (maybeNullA == b) ...` where `maybeNullA` is a parameter of type `A?`.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 9]
```diff
@@ -95651,6 +95648,241 @@ class Box<T>
...
+            var source =
+@"#nullable enable
+using System;
+
+public class Program
+{
+    static void Main()
+    {
+        string? value = ""42"";
+        if (value?.Length == (int?) null)
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >(int?) [](start = 29, length = 6)

consider removing this cast

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 10]
```diff
@@ -95651,6 +95648,241 @@ class Box<T>
...
+            Console.WriteLine(y.Length);
+        }
+        else
+        {
+            Console.WriteLine(x.Length); // 2
+            Console.WriteLine(y.Length); // 3
+        }
+    }
+}";
+            // The first warning produced for y.Length is unexpected.
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >The first warning produced for y.Length is unexpected. [](start = 15, length = 54)

Actually, I'm surprised by warning 3 too. Why do we get that?

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 11]
```diff
@@ -95651,6 +95648,241 @@ class Box<T>
...
+        {
+            var source =
+@"#nullable enable
+using System;
+
+public class Program
+{
+    static void Main()
+    {
+        string? x = ""42"";
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >""42""; [](start = 20, length = 7)

We should start those tests with a null-state of maybe-null. Otherwise the comparisons with non-null values are no-ops (they update the non-null state to non-null).

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 12]
```diff
@@ -95651,6 +95648,241 @@ class Box<T>
...
+        {
+            var source =
+@"#nullable enable
+using System;
+
+public class Program
+{
+    static void Main()
+    {
+        string? value = ""42"";
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >""42""; [](start = 24, length = 7)

should start with a maybe-null null-state.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 13]
```diff
@@ -2097,23 +2065,44 @@ protected override void AfterLeftChildHasBeenVisited(BoundBinaryOperator binary)
 
                     // `x == null` and `x != null` are pure null tests so update the null-state in the alternative branch too
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >// `x == null` and `x != null` are pure null tests so update the null-state in the alternative branch too [](start = 20, length = 105)

Reading this, I realized we probably have a bug: `x == nullConstant` is going to set the state of `x` to maybe-null, but it should not.
Could you add a test and either fix or file a bug? Only the `null` literal should count as a pure null test.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Done

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 10 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: In warning 3, we only know that one of `y?.Length != 2` or `y?.Length != 3` is true. So basically we haven't ruled out null.

I believe the issue is that our conditional expression analysis needs to be more complex to handle cases like these. More detail in the tracked issue #36096

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 8 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: I will simplify to just use a maybe-null parameter.

However I think I can't test aimplicit user-defined conversion the way you describe. Quoting my comment from earlier:

> It looks like a comparison between values of type A and B will not cause a user-defined implicit conversion to occur--you have to cast. Will add as similar of a test to what you've described as possible.

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAmARgFgAoUnAZgAJ8qBBKgb1KtZupwIDYq0wAHDGgDGaGFQD2/RBBgSEVAEIAKBhACUVALwA+KgDs4AdyXL1AblIBfUuQ54lTa7ZKUaDgMJOSbdjQAsVACyZt6+vmraBgCuGBiWPuGsilTAUYYmKhYsSbwAZlTKENpaqZqMVDlJNolJVeFoBcrKiurFWqXA5fW+Nb3WQA===

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 9 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Adding another test case that elides the cast

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 11 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Changing these to be parameters.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 12 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Done

Comment (jcouv) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: `value` should start in maybe-null state. Otherwise the test doesn't have an effect (no-op).

---
In reply to: [290009777](https://github.com/dotnet/roslyn/pull/35953#discussion_r290009777) [](ancestors = 290009777)

Comment (jcouv) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: you may have missed this comment. At least this place (maybe others) where initial null-state makes the test less useful.

---
In reply to: [290069589](https://github.com/dotnet/roslyn/pull/35953#discussion_r290069589) [](ancestors = 290069589,290009777)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 14]
```diff
@@ -95651,6 +95648,265 @@ class Box<T>
...
+    static void Main(C? value)
+    {
+        const object? i = null;
+        if (value?.s == i)
+        {
+            Console.WriteLine(value.s); // 1
+        }
+        else
+        {
+            Console.WriteLine(value.s); // 2
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: > // 2 [](start = 39, length = 5)

Nit: remove spurious warning marker.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 15]
```diff
@@ -95651,6 +95648,265 @@ class Box<T>
...
+using System;
+
+public class Program
+{
+    static void Main(string? x, string? y)
+    {
+        if (x?.Length == 2 ? y?.Length == 2 : y?.Length == 3)
+        {
+            Console.WriteLine(x.Length); // 1
+            Console.WriteLine(y.Length);
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: I would label this line with a warning marker. For now, this is intended behavior that matches definite assignment. I'm going to try and improve this scenario, but that's on the backlog and for now this is correct.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 14 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Done

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 15 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Done

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 12 above)
Comment (jcouv) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: ping

---
In reply to: [290078994](https://github.com/dotnet/roslyn/pull/35953#discussion_r290078994) [](ancestors = 290078994,290069589,290009777)

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: This test is the repro given in #34942 but I will change it to be a parameter for clarity/simplicity
