### PR TITLE
Integration fixes

### LINKED ISSUE #20371: [Test failure] BasicCodeActions.GenerateMethodInClosedFile
windows_release_vs-integration_prtest failed on #19490 Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicCodeActions.GenerateMethodInClosedFile ([details](https://ci.dot.net/job/dotnet_roslyn/job/dev15.6/job/windows_release_vs-integration_prtest/380/))
```
MESSAGE:
Assert.Equal() Failure
↓ (pos 13)\r\n
Expected:
Class Foo
 Friend Sub Bar()
 Throw New N···
Actual:
Class Foo
End Class
↑ (pos 13)
+++++++++++++++++++
STACK TRACE:
at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicCodeActions.GenerateMethodInClosedFile() in q:\roslyn\src\VisualStudio\IntegrationTest\IntegrationTests\VisualBasic\BasicCodeActions.cs:line 42
```

### LINKED ISSUE #25814: DumpLocalVariableValue tests show crashing VS
**Version Used**: Commit 3c001e34c3e638d7e880372218c3a8b6ecea8d41

The two `DumpLocalVariableValue` tests (previously named `DumpLocalVaribleValue`) fail when Visual Studio crashes with the following exception:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.InvalidOperationException: Queue empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Dequeue()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.DisconnectedBufferGraph.MapDownToSnapshot(Span span, IProjectionSnapshot start, ITextSnapshot target)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.DisconnectedBufferGraph.GetSubjectBufferTextSpanInViewBuffer(TextSpan textSpan)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.SetCaretPosition(Int32 desiredCaretPosition)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Commit(CompletionItem item, Model model, Nullable`1 commitChar, ITextSnapshot initialTextSnapshot, Action nextHandler)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.CommitOnNonTypeChar(CompletionItem item, Model model)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.CommitOnTab(Action nextHandler)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Microsoft.VisualStudio.Commanding.IChainedCommandHandler<Microsoft.VisualStudio.Text.Editor.Commanding.Commands.TabKeyCommandArgs>.ExecuteCommand(TabKeyCommandArgs args, Action nextHandler, CommandExecutionContext context)
   at Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.ExecuteCommand[T](ICommandHandler commandHandler, T args, Action nextCommandHandler, CommandExecutionContext executionContext)
   at Microsoft.CodeAnalysis.Editor.CommandHandlers.AbstractCompletionCommandHandler.ExecuteCommandWorker[TCommandArgs](TCommandArgs args, Action nextHandler, CommandExecutionContext context)
   at Microsoft.CodeAnalysis.Editor.CommandHandlers.AbstractCompletionCommandHandler.Microsoft.VisualStudio.Commanding.IChainedCommandHandler<Microsoft.VisualStudio.Text.Editor.Commanding.Commands.TabKeyCommandArgs>.ExecuteCommand(TabKeyCommandArgs args, Action nextHandler, CommandExecutionContext context)
   at Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.ExecuteCommand[T](ICommandHandler commandHandler, T args, Action nextCommandHandler, CommandExecutionContext executionContext)
   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.<>c__DisplayClass14_1`1.<Execute>b__1()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception)
   at Microsoft.VisualStudio.IntegrationTest.Setup.TestExtensionErrorHandler.HandleError(System.Object, System.Exception)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.HandleException(System.Object, System.Exception)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(System.Object, System.Action)
   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService+<>c__DisplayClass14_1`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<Execute>b__0()
   at Microsoft.CodeAnalysis.Editor.CSharp.EventHookup.EventHookupCommandHandler.ExecuteCommand(Microsoft.VisualStudio.Text.Editor.Commanding.Commands.TabKeyCommandArgs, System.Action, Microsoft.VisualStudio.Commanding.CommandExecutionContext)
   at Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.ExecuteCommand[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Microsoft.VisualStudio.Commanding.ICommandHandler, System.__Canon, System.Action, Microsoft.VisualStudio.Commanding.CommandExecutionContext)
   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService+<>c__DisplayClass14_1`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<Execute>b__1()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(System.Object, System.Action)
   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService+<>c__DisplayClass14_1`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<Execute>b__0()
   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.ExecuteCommandHandlerChain(Microsoft.VisualStudio.Commanding.CommandExecutionContext, System.Action, System.Action)
   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.Execute[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Func`3<Microsoft.VisualStudio.Text.Editor.ITextView,Microsoft.VisualStudio.Text.ITextBuffer,System.__Canon>, System.Action)
   at Microsoft.VisualStudio.Editor.Implementation.CommandHandlerServiceAdapter.ExecuteTabKeyCommand(System.Action)
   at Microsoft.VisualStudio.Editor.Implementation.CommandHandlerServiceAdapter.ExecuteVisualStudio2000(System.Guid ByRef, UInt32, IntPtr, IntPtr, System.Action)
   at Microsoft.VisualStudio.Editor.Implementation.CommandHandlerServiceAdapter.Exec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.LanguageServices.Implementation.DebuggerIntelliSense.DebuggerIntelliSenseFilter`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Exec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Exec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.Exec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.Exec(System.Guid ByRef, UInt32, UInt32, IntPtr, IntPtr)
```

### LINKED ISSUE #35965: Enable debugging/EnC integration tests
This PR disables integration tests: https://github.com/dotnet/roslyn/pull/34027, because it requires the <s>lab/16.2stg</s> 16.10 build with VS debugger insertion which won't be available on the CI machine.

Enable the tests again once the CI machine is upgraded.

Also uncomment `#if TODO` in `WaitForDesignMode`

### LINKED ISSUE #36763: BasicEditAndContinue Integration Tests Failing
A recent update to the preview version of Visual Studio that is used for integration tests has caused Basic EnC tests to consistently fail. 

To unblock contributors we made the Integration tests non-required for PRs. 

- [x] We should instead Skip these tests.
- [x] Return Integration tests to their required state.
- [ ] Unskip these tests when a fix is in place.

### LINKED ISSUE #37689: BasicEditAndContinue Integration Tests Failing
A recent update to the preview version of Visual Studio that is used for integration tests has caused Basic EnC tests to consistently fail.

- [x] Make integration tests not required for PRs
- [x] Add skips for these tests and flow through
- [x] Make integration tests required for PRs
- [ ] Unskip these tests when a fix is in place.

### LINKED ISSUE #38301: Investigate Integration Test Failures
5 integration tests are failing regularly in master and master-vs-deps PRs

```
CSharpUpgradeProject.CPSProject_GeneralPropertyGroupUpdated - System.InvalidOperationException : Expected a light bulb session to appear.
MSBuildWorkspaceTests.TestParseOptions_CSharp_LanguageVersion_Default - Assert.Equal() Failure\r\nExpected: CSharp8\r\nActual: CSharp7_3
```

The text "To browse the .NET Framework source code" is no longer part of the quick info text for System.String:
```
BasicQuickInfo.QuickInfo1 - Assert.Equal() Failure\r\n ↓ (pos 72)\r\nExpected: ···f UTF-16 code units.To browse the .NET Framework source code ···\r\nActual: ···f UTF-16 code units.\r\n ↑ (pos 72)
CSharpQuickInfo.QuickInfo_MetadataDocumentation - Assert.Equal() Failure\r\n ↓ (pos 72)\r\nExpected: ···f UTF-16 code units.To browse the .NET Framework source code ···\r\nActual: ···f UTF-16 code units.\r\n ↑ (pos 72)
```

For Async completion
```
BasicIntelliSense.IntelliSenseTriggersOnParenWithBraceCompletionAndCorrectUndoMerging - System.AggregateException : One or more errors occurred.\r\n---- System.InvalidOperationException : Expected exactly one session in the completion list, but found 0
```

- [ ] Skip the affected tests
- [ ] Update the tests to passing
- [ ] Unskip the tests

### LINKED ISSUE #40160: Failing C# REPL integration tests on 16.4 Preview 5
With the integration VM image updated to dev16.4 Preview 5 there are now 22 consistently failing C# REPL unit tests.

- [x] Skip REPL Tests (https://github.com/dotnet/roslyn/pull/40161)
- [ ] Fix underlying issues

### LINKED ISSUE #45234: BasicIntellisense.TypeAVariableDeclaration is flaky
The test `BasicIntellisense.TypeAVariableDeclaration` appears to be flaky.  It has failed repeatedly on https://github.com/dotnet/roslyn/pull/44702 despite that PR having no relevant changes.

### LINKED ISSUE #46027: Failing HighlightRefsMultipleSubmisionsVerifyRenameTags tests
The move of integration tests running on 16.7 Preview 2 to 16.7 Preview 3.1 has caused a few new test failures.

- HighlightRefsMultipleSubmisionsVerifyRenameTagsShowUpOnUnsubmittedText
- HighlightRefsMultipleSubmisionsVerifyRenameTagsShowUpWhenInvokedOnSubmittedText
- HighlightRefsMultipleSubmisionsVerifyRenameTagsShowUpOnTypesWhenInvokedOnUnsubmittedText
- HighlightRefsMultipleSubmisionsVerifyRenameTagsShowUpOnTypesWhenInvokedOnSubmittedText

- [ ] Skip tests (https://github.com/dotnet/roslyn/pull/46028)
- [ ] Fix and unskip tests ()

### LINKED ISSUE #57423: Failure in CSharpCodeActions.GFUFuzzyMatchAfterRenameTrackingAndAfterGenerateType
```
Error message
System.Exception : The following expected item(s) not found in sequence:
Rename 'P2' to 'Foober'
Generate type 'Foober'
Generate class 'Foober' in new file
Generate class 'Foober'
Generate nested class 'Foober'
Generate new type...
Goober - using N;
Suppress or Configure issues
Suppress CS0168
in Source
Configure CS0168 severity
None
Silent
Suggestion
Warning
Error

Actual items:


Stack trace
   at Microsoft.VisualStudio.IntegrationTest.Utilities.TestUtilities.ThrowIfExpectedItemNotFoundInOrder[TCollection](IEnumerable`1 actual, IEnumerable`1 expected) in /_/src/VisualStudio/IntegrationTest/TestUtilities/TestUtilities.cs:line 105
   at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.TextViewWindow_OutOfProc.Verifier`1.CodeActions(IEnumerable`1 expectedItems, String applyFix, Boolean verifyNotShowing, Boolean ensureExpectedItemsAreOrdered, Nullable`1 fixAllScope, Boolean blockUntilComplete) in /_/src/VisualStudio/IntegrationTest/TestUtilities/OutOfProcess/TextViewWindow_OutOfProc.Verifier.cs:line 81
   at Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpCodeActions.GFUFuzzyMatchAfterRenameTrackingAndAfterGenerateType() in /_/src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpCodeActions.cs:line 503
```

<!-- runfo report start -->
Runfo Tracking Issue: [GFUFuzzyMatchAfterRenameTrackingAndAfterGenerateType](https://runfo.azurewebsites.net/tracking/issue/215)
|Build|Definition|Kind|Run Name|
|---|---|---|---|



Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|0|0|

<!-- runfo report end -->

### LINKED ISSUE #70582: C# intellisense integration tests are flaky
Seeing increased failure rate in the following tests after recent VS update.

```
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpIntelliSense.CtrlAltSpace
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpIntelliSense.AtNamespaceLevel
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpIntelliSense.VerifyCompletionListMembersOnStaticTypesAndCompleteThem
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpIntelliSense.NavigatingWithDownKey
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpIntelliSense.EnsureTheCaretIsVisibleAfterALongEdit
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpSignatureHelp.ExplicitSignatureHelpDismissesCompletion
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpReplIntellisense.VerifyCommitCompletionOnTopLevel
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpIntelliSense.XmlDocCommentIntelliSense
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractiveCommands.VerifyReturnIndentCurrentLine
Roslyn.VisualStudio.NewIntegrationTests.CSharp.CSharpAutomaticBraceCompletion.Nested_AllKinds
```

### PR DESCRIPTION
**Pull request by sharwell**
Submitting to CI to catch cases I might have missed during the port. Will review and rebase with updates before marking reading for review.

Closes #20371 
Closes #25814 
Closes #35965 
Closes #36763 
Closes #37689 
Closes #38301 
Closes #40160
Closes #45234
Closes #46027 
Closes #57423
Closes #70582

### CODE REVIEW

**Review by CyrusNajmabadi — COMMENTED** [review]
Awesome!

File: src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/ITextViewWindowInProcessExtensions.cs [hunk 1]
```diff
@@ -0,0 +1,252 @@
...
+        }
+
+        public static async Task<ImmutableArray<Completion>> GetCompletionItemsAsync(this ITextViewWindowInProcess textViewWindow, CancellationToken cancellationToken)
+        {
+            await textViewWindow.TestServices.JoinableTaskFactory.SwitchToMainThreadAsync(cancellationToken);
+
+            await WaitForCompletionSetAsync(textViewWindow, cancellationToken);
+
+            // It's not known why WaitForCompletionSetAsync fails to stabilize calls to GetCompletionItemsAsync.
+            await Task.Delay(TimeSpan.FromSeconds(1));
```
Comment (sharwell) [inline src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/ITextViewWindowInProcessExtensions.cs:90]: 📝 Added a delay here as well. It looks like `ICompletionBroker` is introducing significant instability in the overall testing. We should work with the editor to stabilize these APIs.

Comment (genlu) [reply src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/ITextViewWindowInProcessExtensions.cs:90]: yea, we already switched to another API based on Kayle's suggestion, but it didn't help
https://github.com/dotnet/roslyn/pull/70578/files

**Comment by genlu** [comment]
>             options.SetOptionValue(DefaultOptions.ResponsiveCompletionOptionId, false);

There's also this option in editor, we should check with Kayle to see if we need to set it too
[https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS-Platform?path=/src/Editor/Text/Def/TextLogic/EditorOptions/DefaultOptions.cs&version=GBmain&line=304&lineEnd=305&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS-Platform?path=/src/Editor/Text/Def/TextLogic/EditorOptions/DefaultOptions.cs&version=GBmain&line=304&lineEnd=305&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents)

---
Refers to: src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/StateResetInProcess.cs:104 in 9075f85. [](commit_id = 9075f856666bf15f0db33a55d574f18a616c7b13, deletion_comment = False)

File: src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/ChangeSignatureDialogInProcess.cs [hunk 2]
```diff
@@ -0,0 +1,133 @@
...
+        }
+
+        public async Task VerifyOpenAsync(CancellationToken cancellationToken)
+        {
+            await JoinableTaskFactory.SwitchToMainThreadAsync(cancellationToken);
+
+            while (true)
+            {
+                cancellationToken.ThrowIfCancellationRequested();
+                if (await TryGetDialogAsync(cancellationToken) is null)
```
Comment (dibarbet) [inline src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/ChangeSignatureDialogInProcess.cs:47]: there's a `TryWaitForAsync` helper in one of the other services below - could be used here too.

File: src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/GenerateTypeDialogInProcess.cs [hunk 3]
```diff
@@ -0,0 +1,148 @@
...
+        }
+
+        public async Task VerifyOpenAsync(CancellationToken cancellationToken)
+        {
+            await JoinableTaskFactory.SwitchToMainThreadAsync(cancellationToken);
+
+            while (true)
+            {
+                cancellationToken.ThrowIfCancellationRequested();
+                if (await TryGetDialogAsync(cancellationToken) is null)
```
Comment (dibarbet) [inline src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/GenerateTypeDialogInProcess.cs:47]: Another place where we could use the helper (there's more further down as well, but I won't comment them all)

File: src/VisualStudio/IntegrationTest/IntegrationTests/AbstractEditorTest.cs [hunk 4]
```diff
@@ -1,95 +0,0 @@
-﻿// Licensed to the .NET Foundation under one or more agreements.
-// The .NET Foundation licenses this file to you under the MIT license.
-// See the LICENSE file in the project root for more information.
-
-#nullable disable
```
Comment (dibarbet) [inline src/VisualStudio/IntegrationTest/IntegrationTests/AbstractEditorTest.cs:5]: Can we remove the old integration test project entirely at this point?

**Review by dibarbet — APPROVED** [review]
A couple random nits, feel free to take or ignore.  I generally only skimmed the actual test files.  Nothing seemed egregiously off!

File: src/VisualStudio/IntegrationTest/New.IntegrationTests/AbstractIntegrationTest.cs [hunk 5]
```diff
@@ -23,8 +58,16 @@ public override async Task InitializeAsync()
...
             await base.InitializeAsync();
 
+            s_listenerProvider ??= await TestServices.Shell.GetComponentModelServiceAsync<AsynchronousOperationListenerProvider>(HangMitigatingCancellationToken);
+
             if (await TestServices.SolutionExplorer.IsSolutionOpenAsync(HangMitigatingCancellationToken))
             {
+                var dte = await TestServices.Shell.GetRequiredGlobalServiceAsync<SDTE, EnvDTE.DTE>(HangMitigatingCancellationToken);
+                if (dte.Debugger.CurrentMode != EnvDTE.dbgDebugMode.dbgDesignMode)
+                {
+                    dte.Debugger.TerminateAll();
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/VisualStudio/IntegrationTest/New.IntegrationTests/AbstractIntegrationTest.cs:68]: If a test fails during a debugging session, it will not stop the debugger before exiting the test method. This method cleans up from whatever state the test completed in so the failure is isolated to just the test with the assertion failure.

File: src/VisualStudio/IntegrationTest/IntegrationTests/AbstractEditorTest.cs (hunk 4 above)
Comment (sharwell) [reply src/VisualStudio/IntegrationTest/IntegrationTests/AbstractEditorTest.cs:5]: Yes I'll do that in the coming week. There is a bunch of support code in RunTests and the build scripts as well.

File: src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/ChangeSignatureDialogInProcess.cs (hunk 2 above)
Comment (sharwell) [reply src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/ChangeSignatureDialogInProcess.cs:47]: Maybe. I'm not thrilled with the current behavior but it matches the old code so left it for now.

File: src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/GenerateTypeDialogInProcess.cs (hunk 3 above)
Comment (sharwell) [reply src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/GenerateTypeDialogInProcess.cs:47]: Yeah, every dialog helper has the same code.
