### PR TITLE
Preserve CustomObsoleteDiagnosticInfo when changing severity

### LINKED ISSUE #47736: Incorrect error codes reported
**Version Used**: 

I'm updating Windows Forms SDK/toolset from P6 to RC1, and our builds fail with errors which we have already suppressed. E.g.:
image

It appears instead of `CS0618` we must now be suppressing `SYSLIB0011` but I had to spend time to figure it out on my own.
Likewise we have other failures, e.g.
image
...and only VS is telling me that I now need to suppress a different one:
image

Few builds:
* https://dev.azure.com/dnceng/public/_build/results?buildId=817132&view=results
* https://dev.azure.com/dnceng/public/_build/results?buildId=817156&view=results

**Steps to Reproduce**:

1. Clone this commit: https://github.com/dotnet/winforms/commit/2427ee0140db52050535e9459384e6527610720d
2. Run `.\build.cmd`
3. Observe multiple failures

**Expected Behavior**:

Errors must either correctly report codes or use the existing suppression rules.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #47736

Need to make a pass to add tests, but I think this fixes the problem.

### CODE REVIEW

File: src/Compilers/Core/Portable/Diagnostic/CustomObsoleteDiagnosticInfo.cs [hunk 1]
```diff
@@ -50,6 +56,11 @@ public override DiagnosticDescriptor Descriptor
             }
         }
 
+        internal override DiagnosticInfo GetInstanceWithSeverity(DiagnosticSeverity severity)
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/Diagnostic/CustomObsoleteDiagnosticInfo.cs:59]: Did you look at the other types that derive from `DiagnosticInfo` to see if they needed to also override this?

Comment (RikkiGibson) [reply src/Compilers/Core/Portable/Diagnostic/CustomObsoleteDiagnosticInfo.cs:59]: This is the only one because it's the only one that overrides Descriptor and MessageIdentifier.

**Comment by RikkiGibson** [comment]
I continue to get integration failures in release mode after 3 attempts:

`##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4652,5): error MSB3030: Could not copy the file "F:\workspace\_work\1\s\artifacts\obj\CompilersBoundTreeGenerator\x64\Release\netcoreapp3.1\BoundTreeGenerator.exe" because it was not found.`

I believe my change does not impact the build's ability to produce and copy this file to wherever it belongs, therefore I will force merge this PR for expediency.

**Comment by RikkiGibson** [comment]
@AlekseyTs could you please take a look at this PR?

**Comment by jaredpar** [comment]
Mail was just sent, integration tests are broken at the moment. I'm going to remove the required bit for the time being.

File: src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs [hunk 2]
```diff
@@ -8657,6 +8658,108 @@ void verify(MetadataReference reference)
...
+                );
+
+            verify(TestOptions.DebugDll.WithGeneralDiagnosticOption(ReportDiagnostic.Error),
+                // (6,9): error TEST1: 'C1.M1()' is obsolete
+                //         M1(); // 1
+                Diagnostic("TEST1", "M1()", isSuppressed: false).WithArguments("C1.M1()").WithLocation(6, 9).WithWarningAsError(true)
+                );
+
+            verify(TestOptions.DebugDll.WithGeneralDiagnosticOption(ReportDiagnostic.Hidden),
+                // (6,9): warning TEST1: 'C1.M1()' is obsolete
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs:8700]: >warning [](start = 26, length = 7)

"hidden"?

File: src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs [hunk 3]
```diff
@@ -8657,6 +8658,108 @@ void verify(MetadataReference reference)
...
+            verify(TestOptions.DebugDll.WithSpecificDiagnosticOptions(ImmutableDictionary<string, ReportDiagnostic>.Empty.Add("CS0618", ReportDiagnostic.Error)),
+                // (6,9): warning TEST1: 'C1.M1()' is obsolete
+                //         M1(); // 1
+                Diagnostic("TEST1", "M1()", isSuppressed: false).WithArguments("C1.M1()").WithLocation(6, 9)
+                );
+
+            verify(TestOptions.DebugDll.WithSpecificDiagnosticOptions(ImmutableDictionary<string, ReportDiagnostic>.Empty.Add("CS0618", ReportDiagnostic.Suppress)),
+                // (6,9): warning TEST1: 'C1.M1()' is obsolete
+                //         M1(); // 1
+                Diagnostic("TEST1", "M1()", isSuppressed: false).WithArguments("C1.M1()").WithLocation(6, 9)
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs:8739]: >Diagnostic("TEST1", "M1()", isSuppressed: false).WithArguments("C1.M1()").WithLocation(6, 9) [](start = 16, length = 92)

Why isn't this diagnostic suppressed?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs:8739]: Suppressions to CS0618 don't apply to this diagnostic. See #42119

File: src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs:8700]: Ahh, must have been a copy-paste issue. This severity is not actually verified, so I will just modify the comment.

**Review by cston — APPROVED** [review]

File: src/Compilers/Core/Portable/Diagnostic/DiagnosticInfo.cs [hunk 4]
```diff
@@ -137,7 +137,7 @@ internal DiagnosticInfo(CommonMessageProvider messageProvider, bool isWarningAsE
         }
 
         // Create a copy of this instance with a explicit overridden severity
-        internal DiagnosticInfo GetInstanceWithSeverity(DiagnosticSeverity severity)
+        internal virtual DiagnosticInfo GetInstanceWithSeverity(DiagnosticSeverity severity)
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/Diagnostic/DiagnosticInfo.cs:140]: Half of me wants to make this method `abstract` to force all derived types to acknowledge this potential issue. The other half of me thinks that's a bit overkill here.

**Review by jaredpar — APPROVED** [review]

File: src/Compilers/Core/Portable/Diagnostic/DiagnosticInfo.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/Core/Portable/Diagnostic/DiagnosticInfo.cs:140]: Yeah, it makes me wish for the ability to say "all of these members in the group must be overridden, or none of them".
