### PR TITLE
Restore original behavior of Shift+Enter during completion

### LINKED ISSUE #33823: Commit on shift+enter fails for async completion
**Version Used**: 2773f5e

Caught by integration test `CommitOnShiftEnter`.

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #33823 

This change is a workaround for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/809579, since we will not be able to fix _and validate_ that from the editor side prior to 16.0 RTM.

### CODE REVIEW

File: src/EditorFeatures/Core/Implementation/AutomaticCompletion/AbstractAutomaticLineEnderCommandHandler.cs [hunk 1]
```diff
@@ -58,6 +63,22 @@ public VSCommanding.CommandState GetCommandState(AutomaticLineEnderCommandArgs a
 
         public void ExecuteCommand(AutomaticLineEnderCommandArgs args, Action nextHandler, CommandExecutionContext context)
         {
+            // Completion will only be active here if this command wasn't handled by the completion controller itself.
+            if (_asyncCompletionBroker.IsCompletionActive(args.TextView))
```
Comment (ivanbasov) [inline src/EditorFeatures/Core/Implementation/AutomaticCompletion/AbstractAutomaticLineEnderCommandHandler.cs]: >_asyncCompletionBroker [](start = 16, length = 22)

Can it be null if the async completion is  turned off?

File: src/EditorFeatures/Core/Implementation/AutomaticCompletion/AbstractAutomaticLineEnderCommandHandler.cs [hunk 2]
```diff
@@ -58,6 +63,22 @@ public VSCommanding.CommandState GetCommandState(AutomaticLineEnderCommandArgs a
...
+            {
+                var session = _asyncCompletionBroker.GetSession(args.TextView);
+                var computedItems = session.GetComputedItems(context.OperationContext.UserCancellationToken);
+                var softSelection = computedItems.SuggestionItemSelected || computedItems.UsesSoftSelection;
+                var behavior = session.Commit('\n', context.OperationContext.UserCancellationToken);
+                session.Dismiss();
+
```
Comment (ivanbasov) [inline src/EditorFeatures/Core/Implementation/AutomaticCompletion/AbstractAutomaticLineEnderCommandHandler.cs]: This fix look weird. It seems that the old completion (Roslyn) supports IChainedCommandHandler<AutomaticLineEnderCommandArgs> but the new one (Editor) does not support it.

Maybe we should make a fi on the Editor side?

File: src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpIntelliSense.cs [hunk 3]
```diff
@@ -250,8 +250,7 @@ void Main(string[] args)
 assertCaretPosition: true);
         }
 
-        // 🐛 This should work with async completion, but currently does not.
-        [ConditionalWpfFact(typeof(LegacyCompletionCondition)), Trait(Traits.Feature, Traits.Features.Completion)]
+        [WpfFact, Trait(Traits.Feature, Traits.Features.Completion)]
```
Comment (ivanbasov) [inline src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpIntelliSense.cs]: >WpfFact [](start = 9, length = 7)

I tried this scenario in the recent VS (16.0 preview 4). It work without the fix.

Comment (ivanbasov) [reply src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpIntelliSense.cs]: Sorry! It seems that my VS worked with the old completion. I'm able to repro the scenario.

Still think we need to make it on the editor side.

---
In reply to: [262195984](https://github.com/dotnet/roslyn/pull/33828#discussion_r262195984) [](ancestors = 262195984)

File: src/EditorFeatures/Core/Implementation/AutomaticCompletion/AbstractAutomaticLineEnderCommandHandler.cs (hunk 2 above)
Comment (AmadeusW) [reply src/EditorFeatures/Core/Implementation/AutomaticCompletion/AbstractAutomaticLineEnderCommandHandler.cs]: the fix definitely belongs on the editor side

Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/AutomaticCompletion/AbstractAutomaticLineEnderCommandHandler.cs]: This fix can be reverted if the editor side fixes the issue, but it will not break the functionality to use it as a temporary workaround.

File: src/EditorFeatures/Core/Implementation/AutomaticCompletion/AbstractAutomaticLineEnderCommandHandler.cs [hunk 4]
```diff
@@ -58,6 +63,22 @@ public VSCommanding.CommandState GetCommandState(AutomaticLineEnderCommandArgs a
 
         public void ExecuteCommand(AutomaticLineEnderCommandArgs args, Action nextHandler, CommandExecutionContext context)
         {
+            // Completion will only be active here if this command wasn't handled by the completion controller itself.
+            if (_asyncCompletionBroker.IsCompletionActive(args.TextView))
+            {
+                var session = _asyncCompletionBroker.GetSession(args.TextView);
+                var computedItems = session.GetComputedItems(context.OperationContext.UserCancellationToken);
+                var softSelection = computedItems.SuggestionItemSelected || computedItems.UsesSoftSelection;
+                var behavior = session.Commit('\n', context.OperationContext.UserCancellationToken);
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/AutomaticCompletion/AbstractAutomaticLineEnderCommandHandler.cs]: If we do go with taking this workaround, I presume the code here should have a comment linking to the tracking bug to track the proper fix?
