### PR TITLE
Fixes symbol display incorrect for CS0118 with parameters

### LINKED ISSUE #7201: Symbol display incorrect for CS0118 with parameters
```
using System;
public class Program
{
    static void Main(params string[] args)
    {
        Action<args> a = null;
    }
}
```
Error:
```
error CS0118: 'params string[]' is a variable but is used like a type
```
Should be `args` and not `params string[]` (works without `params` too, just added to show the effect)

Note: works fine for locals, just seems to be issue with parameters.

### PR DESCRIPTION
**Pull request by leppie**
Fixes #7201

### CODE REVIEW

**Comment by davkean** [comment]
test eta please
tag @dotnet/roslyn-compiler

File: src/Compilers/CSharp/Portable/Errors/MessageProvider.cs [hunk 1]
```diff
@@ -103,7 +103,15 @@ public override string ConvertSymbolToString(int errorCode, ISymbol symbol)
                 return symbol.ToString();
             }
 
-            return SymbolDisplay.ToDisplayString(symbol, SymbolDisplayFormat.CSharpShortErrorMessageFormat);
+            var format = SymbolDisplayFormat.CSharpShortErrorMessageFormat;
+
+            // for CS0118 and symbol is a parameter, we dont want to display the type, but the name
+            if (errorCode == (int)ErrorCode.ERR_BadSKknown)
+            {
+                format = format.WithParameterOptions(SymbolDisplayParameterOptions.IncludeName);
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Errors/MessageProvider.cs]: How about instead adding an overload with the formatting options and then change the call site to pass the IncludeName option?

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Errors/MessageProvider.cs]: I agree, we should simply adjust the site where the diagnostics is created. I guess it is the body of 
```
internal static SingleLookupResult NotTypeOrNamespace(Symbol unwrappedSymbol, Symbol symbol, bool diagnose)
```
We have Microsoft.CodeAnalysis.FormattedSymbol class exactly for this purpose.

Comment (leppie) [inline src/Compilers/CSharp/Portable/Errors/MessageProvider.cs]: Thanks, will look into it. Still new to codebase :)

Comment (leppie) [inline src/Compilers/CSharp/Portable/Errors/MessageProvider.cs]: Guess the //todo comment should have made me consider a better option :)

**Comment by leppie** [comment]
@AlekseyTs I have now used FormattedSymbol and rolled up the commits into 1. Look OK?

File: src/Compilers/CSharp/Portable/Binder/LookupResult.cs [hunk 2]
```diff
@@ -191,7 +191,13 @@ internal static SingleLookupResult NotTypeOrNamespace(Symbol symbol, DiagnosticI
         internal static SingleLookupResult NotTypeOrNamespace(Symbol unwrappedSymbol, Symbol symbol, bool diagnose)
         {
             // TODO: determine correct diagnosis
```
Comment (leppie) [inline src/Compilers/CSharp/Portable/Binder/LookupResult.cs]: Is this comment still valid?

**Comment by davkean** [comment]
@dotnet-bot retest eta please

**Comment by leppie** [comment]
@davkean Looks like prtest/mac/dbg/unit32 crashed and is hanging now

**Comment by leppie** [comment]
retest prtest/mac/dbg/unit32 please

File: src/Compilers/CSharp/Portable/Binder/LookupResult.cs [hunk 3]
```diff
@@ -191,7 +191,13 @@ internal static SingleLookupResult NotTypeOrNamespace(Symbol symbol, DiagnosticI
         internal static SingleLookupResult NotTypeOrNamespace(Symbol unwrappedSymbol, Symbol symbol, bool diagnose)
         {
             // TODO: determine correct diagnosis 
-            var diagInfo = diagnose ? new CSDiagnosticInfo(ErrorCode.ERR_BadSKknown, unwrappedSymbol, unwrappedSymbol.GetKindText(), MessageID.IDS_SK_TYPE.Localize()) : null;
+            object sym = unwrappedSymbol;
+            // for CS0118 we dont want to display the type, but the name
+            if (unwrappedSymbol.Kind == SymbolKind.Parameter && diagnose)
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/LookupResult.cs]: This is a one-off patch for a symptom. Can we fix the root of the problem by overriding `ToString` in `ParameterSymbol.cs`?

Comment (leppie) [inline src/Compilers/CSharp/Portable/Binder/LookupResult.cs]: I can try, but I suspect it will break many things given that the default is different. Will report back.

Comment (davkean) [inline src/Compilers/CSharp/Portable/Binder/LookupResult.cs]: @DustinCampbell Was this is the thing you hit yesterday?

Comment (DustinCampbell) [inline src/Compilers/CSharp/Portable/Binder/LookupResult.cs]: Yup. See #7211 for discussion

Comment (leppie) [inline src/Compilers/CSharp/Portable/Binder/LookupResult.cs]: Except for the initial comment, the rest of #7211 is very unclear to me.

Comment (leppie) [inline src/Compilers/CSharp/Portable/Binder/LookupResult.cs]: @gafter `Symbol.ToString()` is sealed... And even when removing that limitation and overriding `ParameterSymbol.ToString()` with the `IncludeName` option, still outputs:
```
error CS0118: 'params string[]' is a variable but is used like a type
```
Currently, `FormattedSymbol` like @AlekseyTs advised seems the best option.

Comment (leppie) [inline src/Compilers/CSharp/Portable/Binder/LookupResult.cs]: @gafter And like that, there are 25 test failures for the C# compiler alone.

Comment (leppie) [inline src/Compilers/CSharp/Portable/Binder/LookupResult.cs]: Overriding `ToString` is bad:
```
// (14,22): error CS1503: Argument 1: cannot convert from 'method group' to 'int'
//     delegate T F2<[A(Invoke)]T> ();
Diagnostic(ErrorCode.ERR_BadArgType, "Invoke").WithArguments("1", "method group", "x").WithLocation(14, 22),
// (11,8): error CS1503: Argument 1: cannot convert from 'method group' to 'int'
//     [A(Invoke)]
Diagnostic(ErrorCode.ERR_BadArgType, "Invoke").WithArguments("1", "method group", "x").WithLocation(11, 8)
```
Again this is wrong due to #7204

Comment (DustinCampbell) [inline src/Compilers/CSharp/Portable/Binder/LookupResult.cs]: @leppie, most of the discussion in #7211 after the initial comment is essentially me trying to poke holes in the consistency of the various symbol display flags. I think it is *very* weird and unexpected that `IParameterSymbol.ToDisplayString()` would not return a parameter's name, but I'm assured that behavior is by design.

**Comment by AlekseyTs** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Binder/LookupResult.cs (hunk 3 above)
Comment (leppie) [inline src/Compilers/CSharp/Portable/Binder/LookupResult.cs]: @DustinCampbell I dont really have a problem on what is decided to be displayed. You guys sort that out. The really issue is #7204 in terms of getting consistent test expectations. This specific case just pointed out the issue. But for now, `FormattedSymbol` seems a good way to 'override' symbol display to work in the test suite's favor. (I am not saying the tests are broken, but they are constructed in an incorrect way, which will probably bite again later).

Comment (DustinCampbell) [inline src/Compilers/CSharp/Portable/Binder/LookupResult.cs]: I think it's already sorted out, no? I was simply providing an explanation since you wrote this:

> Except for the initial comment, the rest of #7211 is very unclear to me.

Comment (leppie) [inline src/Compilers/CSharp/Portable/Binder/LookupResult.cs]: @DustinCampbell Oh thanks :) But yes, you are right to poke holes into this, as any decent dev should do :D

**Comment by davkean** [comment]
Unsure of the conclusion of the correct approach here, @gafter?

File: src/Compilers/CSharp/Portable/Binder/LookupResult.cs [hunk 4]
```diff
@@ -191,7 +191,13 @@ internal static SingleLookupResult NotTypeOrNamespace(Symbol symbol, DiagnosticI
...
+            {
+                sym = new FormattedSymbol(unwrappedSymbol, SymbolDisplayFormat.CSharpShortErrorMessageFormat.WithParameterOptions(SymbolDisplayParameterOptions.IncludeName));
+            }
+            var diagInfo = diagnose ? new CSDiagnosticInfo(ErrorCode.ERR_BadSKknown, sym, unwrappedSymbol.GetKindText(), MessageID.IDS_SK_TYPE.Localize()) : null;
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/LookupResult.cs]: This approach is used elsewhere and appears to work here:

```cs
        internal static SingleLookupResult NotTypeOrNamespace(Symbol unwrappedSymbol, Symbol symbol, bool diagnose)
        {
            var diagInfo = diagnose ? new CSDiagnosticInfo(ErrorCode.ERR_BadSKknown, unwrappedSymbol.Name, unwrappedSymbol.GetKindText(), MessageID.IDS_SK_TYPE.Localize()) : null;
            return new SingleLookupResult(LookupResultKind.NotATypeOrNamespace, symbol, diagInfo);
        }
```

(I just added `.Name`)

Comment (leppie) [inline src/Compilers/CSharp/Portable/Binder/LookupResult.cs]: @gafter As per suggestion, done.

**Comment by gafter** [comment]
LGTM. I'm going to let the tests finish then merge.

**Comment by gafter** [comment]
@dotnet-bot test prtest/win/dbg/unit64

**Comment by heejaechang** [comment]
@leppie is this failure due to your change?

**Comment by davkean** [comment]
@heejaechang Doubtful:

```
Microsoft.CodeAnalysis.Test.Utilities.ExecutionException : \r\nExecution failed for assembly 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\Dumps'.\r\nException: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.\r\n at TestCase.<>c__DisplayClass1_0.<<Run>b__1>d.MoveNext()\r\n at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)\r\n at TestCase.<>c__DisplayClass1_0.<Run>b__1()\r\n at TestCase.<Run>d__1.MoveNext()\r\n at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)\r\n at TestCase.Run()\r\n at Driver.Main()\r\n---- System.AccessViolationException : Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
+++++++++++++++++++
```

**Comment by agocke** [comment]
:+1:

**Comment by agocke** [comment]
Assuming the test failures are unrelated.

**Comment by leppie** [comment]
retest prtest/mac/dbg/unit32 prtest/win/dbg/unit64   please

**Comment by leppie** [comment]
retest this please

**Comment by leppie** [comment]
@davkean In review can be removed for this and the logged issue
