### PR TITLE
Re-enable test that verifies ref return cannot be inlined

### LINKED ISSUE #12838: Test asserts temporary variable that can be inlined cannot be inlined
The following test appears to be incorrect

``` cs
        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsInlineTemporary)]
        public async Task WithRefInitializer1()
        {
            await TestMissingAsync(@"
class C
{
    ref int M()
    {
        int[] arr = new[] { 1, 2, 3 };
        ref int [||]x = ref arr[2];
        return ref x;
    }
}");
        }
```

If I understand it correctly, this asserts that the temporary variable x cannot be inlined. But it can be inlined. This was broken by a refactoring of the syntax model for ref locals.

### PR DESCRIPTION
**Pull request by OmarTawfik**
Fixes #12838
Test from commit https://github.com/dotnet/roslyn/commit/c7349324e98e5a9dbc38b9c8a89f09b41d3c2012
@dotnet/roslyn-ide 
@dotnet/roslyn-compiler

### CODE REVIEW

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-compiler can I get a second review?

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-ide @CyrusNajmabadi @jasonmalinowski any concerns about this change?

File: src/Features/CSharp/Portable/CodeRefactorings/InlineTemporary/InlineTemporaryCodeRefactoringProvider.cs [hunk 1]
```diff
@@ -69,7 +69,7 @@ internal partial class InlineTemporaryCodeRefactoringProvider : CodeRefactoringP
                 return;
             }
 
-            if (variableDeclarator.Initializer.Kind() == SyntaxKind.RefExpression)
+            if (variableDeclaration.Type.Kind() == SyntaxKind.RefType)
             {
                 // TODO: inlining byref temps is NYI
```
Comment (jasonmalinowski) [inline src/Features/CSharp/Portable/CodeRefactorings/InlineTemporary/InlineTemporaryCodeRefactoringProvider.cs]: What bug is tracking that this still doesn't work though? @gafter's original concern is that this should work, and that it was being blocked was incorrect. Can this TODO be updated with the tracking bug?

Comment (OmarTawfik) [inline src/Features/CSharp/Portable/CodeRefactorings/InlineTemporary/InlineTemporaryCodeRefactoringProvider.cs]: We're not enabling these IDE scenarios for ref returns for now per @VSadov comment on #12838.
Right now the tool tip is visible and IDE crashes when user tries that. My PR is disabling that scenario for the user. I don't think enabling quick fixes for ref returns is planned in the immediate future.

Comment (jasonmalinowski) [inline src/Features/CSharp/Portable/CodeRefactorings/InlineTemporary/InlineTemporaryCodeRefactoringProvider.cs]: I understand your PR properly disables it, but we should ensure we still have something to track. @Pilchie or @kuhlenh are we tracking this with a bug somewhere we can link to?

Comment (OmarTawfik) [inline src/Features/CSharp/Portable/CodeRefactorings/InlineTemporary/InlineTemporaryCodeRefactoringProvider.cs]: @Pilchie @kuhlenh @VSadov ?

**Comment by VSadov** [comment]
@OmarTawfik - I think @jasonmalinowski wants a tracking bug entered to make sure that this feature  (inline local with a ref) is implemented at some point.
I am not sure if there is an issue for this already. It is probably easier to just enter a new one.

**Comment by OmarTawfik** [comment]
@VSadov filed #17132 to track it.
@jasonmalinowski are there any other concerns?

**Comment by jasonmalinowski** [comment]
@OmarTawfik: please reference the bug URL in the TODO comment, otherwise that's it.

**Comment by OmarTawfik** [comment]
@jasonmalinowski done.
