### PR TITLE
Fix implementation of ISyntaxFacts.IsStatementContainer for top-level statements

### LINKED ISSUE #44188: Implementation of LanguageServices.ISyntaxFacts.IsStatementContainer returns false for a GlobalStatementSyntax.
An assert about that fires at:
```
>	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SplitOrMergeIfStatements.AbstractMergeNestedIfStatementsCodeRefactoringProvider.IsFirstStatementOfIfOrElseIf(Microsoft.CodeAnalysis.LanguageServices.ISyntaxFactsService syntaxFacts, Microsoft.CodeAnalysis.SplitOrMergeIfStatements.IIfLikeStatementGenerator ifGenerator, Microsoft.CodeAnalysis.SyntaxNode statement, out Microsoft.CodeAnalysis.SyntaxNode ifOrElseIf) Line 90	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SplitOrMergeIfStatements.AbstractMergeNestedIfStatementsCodeRefactoringProvider.CanBeMergedUpAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.SyntaxNode ifOrElseIf, System.Threading.CancellationToken cancellationToken, out Microsoft.CodeAnalysis.SyntaxNode outerIfOrElseIf) Line 42	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.SplitOrMergeIfStatements.AbstractMergeIfStatementsCodeRefactoringProvider.ComputeRefactoringsAsync(Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringContext context) Line 45	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan state, Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringProvider provider, Microsoft.CodeAnalysis.Extensions.IExtensionManager extensionManager, bool isBlocking, System.Threading.CancellationToken cancellationToken) Line 181	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.HasRefactoringsAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan state, System.Threading.CancellationToken cancellationToken) Line 93	C#
 	Microsoft.CodeAnalysis.EditorFeatures.Wpf.dll!Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.SuggestedActionsSource.TryGetRefactoringSuggestedActionCategoryAsync(Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider provider, Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan? selection, System.Threading.CancellationToken cancellationToken) Line 984	C#
 	Microsoft.CodeAnalysis.EditorFeatures.Wpf.dll!Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.SuggestedActionsSource.GetSuggestedActionCategoriesAsync.AnonymousMethod__1() Line 1150	C#
```

### PR DESCRIPTION
**Pull request by sharwell**
Closes #44188

### CODE REVIEW

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs [hunk 1]
```diff
@@ -333,14 +333,14 @@ internal partial interface ISyntaxFacts
...
-        SyntaxList<SyntaxNode> GetExecutableBlockStatements(SyntaxNode node);
+        IReadOnlyList<SyntaxNode> GetExecutableBlockStatements(SyntaxNode node);
         SyntaxNode FindInnermostCommonExecutableBlock(IEnumerable<SyntaxNode> nodes);
 
         /// <summary>
         /// A node that can host a list of statements or a single statement. In addition to
         /// every "executable block", this also includes C# embedded statement owners.
         /// </summary>
-        bool IsStatementContainer(SyntaxNode node);
+        bool IsStatementContainer([NotNullWhen(true)] SyntaxNode node);
```
Comment (mavasani) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs:343]: Seems confusing to have `NotNullWhen` attribute in files which are not nullable enabled yet.

Comment (sharwell) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs]: Enabled NRT for this method

File: src/Features/Core/Portable/SplitOrMergeIfStatements/AbstractMergeIfStatementsCodeRefactoringProvider.cs [hunk 2]
```diff
@@ -66,14 +66,22 @@ private async Task<Document> RefactorAsync(Document document, TextSpan upperIfOr
...
 
             var newRoot = GetChangedRoot(document, root, upperIfOrElseIf, lowerIfOrElseIf);
             return document.WithSyntaxRoot(newRoot);
+
+            static SyntaxNode FindIfOrElseIf(TextSpan span, IIfLikeStatementGenerator ifGenerator, SyntaxNode root)
+            {
+                var innerMatch = root.FindNode(span, getInnermostNodeForTie: true);
+                return innerMatch?.FirstAncestorOrSelf<SyntaxNode, (TextSpan span, IIfLikeStatementGenerator ifGenerator)>(
+                    (node, arg) => arg.ifGenerator.IsIfOrElseIf(node) && node.Span == arg.span,
+                    (span, ifGenerator));
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/SplitOrMergeIfStatements/AbstractMergeIfStatementsCodeRefactoringProvider.cs:83]: isn't this in the fix?  i think needing to avoid allocation in this fashion is unnecessary.  just capture the values in a closure.  it will be a *lot* easier to read/understand.

File: src/Features/Core/Portable/SplitOrMergeIfStatements/Consecutive/AbstractMergeConsecutiveIfStatementsCodeRefactoringProvider.cs [hunk 3]
```diff
@@ -13,6 +13,7 @@
 using Microsoft.CodeAnalysis.Formatting;
 using Microsoft.CodeAnalysis.LanguageServices;
 using Microsoft.CodeAnalysis.Shared.Extensions;
+using Microsoft.CodeAnalysis.Utilities;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/SplitOrMergeIfStatements/Consecutive/AbstractMergeConsecutiveIfStatementsCodeRefactoringProvider.cs:16]: necessary?

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs [hunk 4]
```diff
@@ -1676,28 +1676,31 @@ public bool IsScopeBlock(SyntaxNode node)
             => node.IsKind(SyntaxKind.Block);
 
         public bool IsExecutableBlock(SyntaxNode node)
-            => node.IsKind(SyntaxKind.Block, SyntaxKind.SwitchSection);
+            => node.IsKind(SyntaxKind.Block, SyntaxKind.SwitchSection, SyntaxKind.CompilationUnit);
 
-        public SyntaxList<SyntaxNode> GetExecutableBlockStatements(SyntaxNode node)
+        public IReadOnlyList<SyntaxNode> GetExecutableBlockStatements(SyntaxNode node)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs:1681]: this does worry me in that previously anyone calling this thought they were getting a contiguous sequence of statements.  the global-statement case is def different as clients really need to be able to understand the disctinction here between top-level statements and body-level statements.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/MoveDeclarationNearReference/AbstractMoveDeclarationNearReferenceService.cs [hunk 5]
```diff
@@ -11,6 +11,7 @@
 using Microsoft.CodeAnalysis.LanguageServices;
 using Microsoft.CodeAnalysis.Shared.Extensions;
 using Microsoft.CodeAnalysis.Simplification;
+using Microsoft.CodeAnalysis.Utilities;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/MoveDeclarationNearReference/AbstractMoveDeclarationNearReferenceService.cs:14]: needed?

File: src/Features/Core/Portable/SplitOrMergeIfStatements/Consecutive/AbstractMergeConsecutiveIfStatementsCodeRefactoringProvider.cs (hunk 3 above)
Comment (sharwell) [reply src/Features/Core/Portable/SplitOrMergeIfStatements/Consecutive/AbstractMergeConsecutiveIfStatementsCodeRefactoringProvider.cs:16]: Yes. It provides the `IndexOf` extension when the type changed from `SyntaxList<T>` to `IReadOnlyList<T>`.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs (hunk 4 above)
Comment (sharwell) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs:1681]: The sequence is contiguous in valid code.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/MoveDeclarationNearReference/AbstractMoveDeclarationNearReferenceService.cs (hunk 5 above)
Comment (sharwell) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/MoveDeclarationNearReference/AbstractMoveDeclarationNearReferenceService.cs:14]: Yes, same as https://github.com/dotnet/roslyn/pull/44622#discussion_r432044544

**Comment by sharwell** [comment]
> would appreciate an audit of the usages of GetExecutableStatements

I didn't see any uses in places that were red flags due to the new boxing allocation. I also didn't see any cases that would change behavior unexpectedly. Most are just getting the same object back with a different static type.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs (hunk 4 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs:1681]: oh?  do we not allow global statements to intermix with non-global-statements in legal code? i thoght that was fine.

**Comment by CyrusNajmabadi** [comment]
> I didn't see any uses in places that were red flags due to the new boxing allocation. I also didn't see any cases that would change behavior unexpectedly. Most are just getting the same object back with a different static type.

The audit was more around the expectation that this be contiguous.  If you're satisfied all callers will be ok, then i'm fine.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs (hunk 4 above)
Comment (sharwell) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs:1681]: It's allowed in script, but not top-level statements. Note that while the syntax nodes are contiguous, they are not siblings because each item is wrapped in a `GlobalStatementSyntax`.

File: src/Features/Core/Portable/SplitOrMergeIfStatements/AbstractMergeIfStatementsCodeRefactoringProvider.cs (hunk 2 above)
Comment (sharwell) [reply src/Features/Core/Portable/SplitOrMergeIfStatements/AbstractMergeIfStatementsCodeRefactoringProvider.cs]: Changed to a closure

**Comment by sharwell** [comment]
@CyrusNajmabadi This change doesn't appear to negatively impact other features using this. The other features do still need to be updated to work with top-level statements, but I'm already working on that in a follow-up branch.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs [hunk 6]
```diff
@@ -1676,28 +1676,31 @@ public bool IsScopeBlock(SyntaxNode node)
             => node.IsKind(SyntaxKind.Block);
 
         public bool IsExecutableBlock(SyntaxNode node)
-            => node.IsKind(SyntaxKind.Block, SyntaxKind.SwitchSection);
+            => node.IsKind(SyntaxKind.Block, SyntaxKind.SwitchSection, SyntaxKind.CompilationUnit);
```
Comment (miqm) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs:1679]: this change caused #45492
