### PR TITLE
Use correct type parameter binder for local functions

### LINKED ISSUE #17814: Roslyn crashes with 'KeyNotFoundException' when completion is invoked after a local fun declaration
**Version Used**: 
Microsoft Visual Studio Community 2017
Version 15.0.26228.4 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01586

**Steps to Reproduce**:

1. Create a C# project in Visual Studio 17
2. Paste the following code:
```
class C {
  static void foo()
  {
     void f<[X]T>(){}

  }
}
```
3. Put the caret at the empty line following the local function f declaration and press Ctrl+Space

**Expected Behavior**: No crash

**Actual Behavior**: Visual Studio crashes with System.Collections.Generic.KeyNotFoundException "The given key was not present in the dictionary."

```
	System.Collections.Immutable.dll!System.Collections.Immutable.ImmutableDictionary<Microsoft.CodeAnalysis.SyntaxTree, int>.this[Microsoft.CodeAnalysis.SyntaxTree].get(Microsoft.CodeAnalysis.SyntaxTree key)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSyntaxTreeOrdinal(Microsoft.CodeAnalysis.SyntaxTree tree)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetBinderFactory(Microsoft.CodeAnalysis.SyntaxTree syntaxTree = {Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParsedSyntaxTree})	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbol.GetAttributesToBind(Roslyn.Utilities.OneOrMany<Microsoft.CodeAnalysis.SyntaxList<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeListSyntax>> attributeDeclarationSyntaxLists, Microsoft.CodeAnalysis.CSharp.Symbols.AttributeLocation symbolPart = None, Microsoft.CodeAnalysis.DiagnosticBag diagnostics = Count = 0, Microsoft.CodeAnalysis.CSharp.CSharpCompilation compilation = {Microsoft.CodeAnalysis.CSharp.CSharpCompilation}, Microsoft.CodeAnalysis.CSharp.Binder rootBinderOpt = null, out System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Binder> binders = Uninitialized)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbol.LoadAndValidateAttributes(Roslyn.Utilities.OneOrMany<Microsoft.CodeAnalysis.SyntaxList<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeListSyntax>> attributesSyntaxLists, ref Microsoft.CodeAnalysis.CustomAttributesBag<Microsoft.CodeAnalysis.CSharp.Symbols.CSharpAttributeData> lazyCustomAttributesBag = null, Microsoft.CodeAnalysis.CSharp.Symbols.AttributeLocation symbolPart = None, bool earlyDecodingOnly = false, Microsoft.CodeAnalysis.DiagnosticBag addToDiagnostics = Count = 0, Microsoft.CodeAnalysis.CSharp.Binder binderOpt)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.SourceTypeParameterSymbolBase.GetAttributesBag(Microsoft.CodeAnalysis.DiagnosticBag diagnosticsOpt)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.LocalFunctionSymbol.GetDeclarationDiagnostics(Microsoft.CodeAnalysis.DiagnosticBag addTo = Count = 0)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindLocalFunctionStatement(Microsoft.CodeAnalysis.CSharp.Syntax.LocalFunctionStatementSyntax node = LocalFunctionStatementSyntax LocalFunctionStatement void f<[X]T>() { }, Microsoft.CodeAnalysis.DiagnosticBag diagnostics)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax node, Microsoft.CodeAnalysis.DiagnosticBag diagnostics)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.IncrementalBinder.BindStatement(Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax node, Microsoft.CodeAnalysis.DiagnosticBag diagnostics)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax node = BlockSyntax Block { void f<[X]T>() { } }, Microsoft.CodeAnalysis.DiagnosticBag diagnostics = Count = 0)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax node, Microsoft.CodeAnalysis.DiagnosticBag diagnostics)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.IncrementalBinder.BindStatement(Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax node, Microsoft.CodeAnalysis.DiagnosticBag diagnostics)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.Bind(Microsoft.CodeAnalysis.CSharp.Binder binder, Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node, Microsoft.CodeAnalysis.DiagnosticBag diagnostics)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.Bind(Microsoft.CodeAnalysis.CSharp.Binder binder, Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node, Microsoft.CodeAnalysis.DiagnosticBag diagnostics)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node = LocalFunctionStatementSyntax LocalFunctionStatement void f<[X]T>() { })	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node, out Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode bindableNode = IdentifierNameSyntax IdentifierName X, out Microsoft.CodeAnalysis.CSharp.BoundNode lowestBoundNode = null, out Microsoft.CodeAnalysis.CSharp.BoundNode highestBoundNode = null, out Microsoft.CodeAnalysis.CSharp.BoundNode boundParent = null)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node, Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.SymbolInfoOptions options = DefaultOptions, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax expression, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSymbolInfo(Microsoft.CodeAnalysis.SemanticModel semanticModel, Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax expression, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.Classification.Classifiers.NameSyntaxClassifier.ClassifyTypeSyntax(Microsoft.CodeAnalysis.CSharp.Syntax.NameSyntax name = IdentifierNameSyntax IdentifierName X, Microsoft.CodeAnalysis.SemanticModel semanticModel = {Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel}, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.Classification.Classifiers.NameSyntaxClassifier.ClassifyNode(Microsoft.CodeAnalysis.SyntaxNode syntax, Microsoft.CodeAnalysis.SemanticModel semanticModel, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Classification.AbstractClassificationService.Worker.ClassifyNode(Microsoft.CodeAnalysis.SyntaxNode syntax = IdentifierNameSyntax IdentifierName X)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Classification.AbstractClassificationService.Worker.ProcessNodes()	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Classification.AbstractClassificationService.Worker.Classify(Microsoft.CodeAnalysis.Workspace workspace, Microsoft.CodeAnalysis.SemanticModel semanticModel, Microsoft.CodeAnalysis.Text.TextSpan textSpan, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.ClassifiedSpan> list, System.Func<Microsoft.CodeAnalysis.SyntaxNode, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.Classifiers.ISyntaxClassifier>> getNodeClassifiers, System.Func<Microsoft.CodeAnalysis.SyntaxToken, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.Classifiers.ISyntaxClassifier>> getTokenClassifiers, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Classification.AbstractClassificationService.AddSemanticClassificationsAsync(Microsoft.CodeAnalysis.Document document = Program.cs, Microsoft.CodeAnalysis.Text.TextSpan textSpan = {Microsoft.CodeAnalysis.Text.TextSpan}, System.Func<Microsoft.CodeAnalysis.SyntaxNode, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.Classifiers.ISyntaxClassifier>> getNodeClassifiers = IsCancellationRequested = false, System.Func<Microsoft.CodeAnalysis.SyntaxToken, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.Classifiers.ISyntaxClassifier>> getTokenClassifiers = {Method = {System.Reflection.RuntimeMethodInfo}}, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.ClassifiedSpan> result = {Method = {System.Reflection.RuntimeMethodInfo}}, System.Threading.CancellationToken cancellationToken = Count = 0)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.CodeAnalysis.Classification.AbstractClassificationService.<AddSemanticClassificationsAsync>d__5>(ref Microsoft.CodeAnalysis.Classification.AbstractClassificationService.<AddSemanticClassificationsAsync>d__5 stateMachine)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Classification.AbstractClassificationService.AddSemanticClassificationsAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan textSpan, System.Func<Microsoft.CodeAnalysis.SyntaxNode, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.Classifiers.ISyntaxClassifier>> getNodeClassifiers, System.Func<Microsoft.CodeAnalysis.SyntaxToken, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.Classifiers.ISyntaxClassifier>> getTokenClassifiers, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.ClassifiedSpan> result, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.Classification.AbstractEditorClassificationService.AddSemanticClassificationsAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan textSpan, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.ClassifiedSpan> result, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities.ClassifySpansAsync(Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext<Microsoft.VisualStudio.Text.Tagging.IClassificationTag> context = {Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan}, Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan spanToTag = {Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>}, Microsoft.CodeAnalysis.Editor.IEditorClassificationService classificationService = {Microsoft.CodeAnalysis.Editor.CSharp.Classification.CSharpEditorClassificationService}, Microsoft.CodeAnalysis.Editor.Shared.Utilities.ClassificationTypeMap typeMap = {Microsoft.CodeAnalysis.Editor.Shared.Utilities.ClassificationTypeMap})	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities.<ClassifySpansAsync>d__2>(ref Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities.<ClassifySpansAsync>d__2 stateMachine)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities.ClassifySpansAsync(Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext<Microsoft.VisualStudio.Text.Tagging.IClassificationTag> context, Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan spanToTag, Microsoft.CodeAnalysis.Editor.IEditorClassificationService classificationService, Microsoft.CodeAnalysis.Editor.Shared.Utilities.ClassificationTypeMap typeMap)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities.TryClassifyContainingMemberSpan(Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext<Microsoft.VisualStudio.Text.Tagging.IClassificationTag> context = {Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>}, Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan spanToTag = {Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan}, Microsoft.CodeAnalysis.Editor.IEditorClassificationService classificationService = {Microsoft.CodeAnalysis.Editor.CSharp.Classification.CSharpEditorClassificationService}, Microsoft.CodeAnalysis.Editor.Shared.Utilities.ClassificationTypeMap typeMap = {Microsoft.CodeAnalysis.Editor.Shared.Utilities.ClassificationTypeMap})	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<bool>.Start<Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities.<TryClassifyContainingMemberSpan>d__1>(ref Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities.<TryClassifyContainingMemberSpan>d__1 stateMachine)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities.TryClassifyContainingMemberSpan(Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext<Microsoft.VisualStudio.Text.Tagging.IClassificationTag> context, Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan spanToTag, Microsoft.CodeAnalysis.Editor.IEditorClassificationService classificationService, Microsoft.CodeAnalysis.Editor.Shared.Utilities.ClassificationTypeMap typeMap)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities.ProduceTagsAsync(Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext<Microsoft.VisualStudio.Text.Tagging.IClassificationTag> context = {Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan}, Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan spanToTag = {Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>}, Microsoft.CodeAnalysis.Editor.IEditorClassificationService classificationService = {Microsoft.CodeAnalysis.Editor.CSharp.Classification.CSharpEditorClassificationService}, Microsoft.CodeAnalysis.Editor.Shared.Utilities.ClassificationTypeMap typeMap = {Microsoft.CodeAnalysis.Editor.Shared.Utilities.ClassificationTypeMap})	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities.<ProduceTagsAsync>d__0>(ref Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities.<ProduceTagsAsync>d__0 stateMachine)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationUtilities.ProduceTagsAsync(Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext<Microsoft.VisualStudio.Text.Tagging.IClassificationTag> context, Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan spanToTag, Microsoft.CodeAnalysis.Editor.IEditorClassificationService classificationService, Microsoft.CodeAnalysis.Editor.Shared.Utilities.ClassificationTypeMap typeMap)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationViewTaggerProvider.ProduceTagsAsync(Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext<Microsoft.VisualStudio.Text.Tagging.IClassificationTag> context)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>.TagSource.RecomputeTagsAsync(object oldState = IsCancellationRequested = false, Microsoft.VisualStudio.Text.SnapshotPoint? caretPosition = {Microsoft.CodeAnalysis.VersionStamp}, Microsoft.CodeAnalysis.Text.TextChangeRange? textChangeRange = Count = 1, System.Collections.Generic.List<Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan> spansToTag = {Microsoft.VisualStudio.Text.SnapshotPoint}, System.Collections.Immutable.ImmutableDictionary<Microsoft.VisualStudio.Text.ITextBuffer, Microsoft.CodeAnalysis.Editor.Shared.Tagging.TagSpanIntervalTree<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>> oldTagTrees = {Microsoft.CodeAnalysis.Text.TextChangeRange}, System.Threading.CancellationToken cancellationToken = Count = 1)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>.TagSource.<RecomputeTagsAsync>d__83>(ref Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>.TagSource.<RecomputeTagsAsync>d__83 stateMachine)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>.TagSource.RecomputeTagsAsync(object oldState, Microsoft.VisualStudio.Text.SnapshotPoint? caretPosition, Microsoft.CodeAnalysis.Text.TextChangeRange? textChangeRange, System.Collections.Generic.List<Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan> spansToTag, System.Collections.Immutable.ImmutableDictionary<Microsoft.VisualStudio.Text.ITextBuffer, Microsoft.CodeAnalysis.Editor.Shared.Tagging.TagSpanIntervalTree<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>> oldTagTrees, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider<System.__Canon>.TagSource.RecomputeTagsForeground.AnonymousMethod__0(System.Threading.CancellationToken ct)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Shared.Threading.AsynchronousSerialWorkQueue.EnqueueBackgroundTask.AnonymousMethod__0(System.Threading.Tasks.Task _)	Unknown
 	mscorlib.dll!System.Threading.Tasks.ContinuationResultTaskFromTask<System.Threading.Tasks.Task>.InnerInvoke()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.Execute()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot = Id = 24707, Status = Running, Method = "System.Threading.Tasks.Task <EnqueueBackgroundTask>b__0(System.Threading.Tasks.Task)", Result = "{Not yet computed}")	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()	Unknown
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
 	mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()	Unknown
```

### PR DESCRIPTION
**Pull request by agocke**
### Customer scenario

Write a local function with an (incorrect) attribute reference 
on a type parameter of the local function. Then, below the
local function, hit Ctrl+Space to bring up completion. VS crashes.

### Bugs this fixes

Fixes #17814

### Workarounds, if any

Don't place attributes on type parameters of local functions, even by mistake.

### Risk

Low. We're already doing this for regular parameters, we just missed type parameters.

### Performance impact

None. An additional field access.

### Is this a regression from a previous update?

No. Present since shipping local functions in 15.0.

### Root cause analysis

This looks like simple oversight. The binder being used for type
parameters was retrieved from the binder factory since we didn't
explicitly pass one. For members this is correct since the binder
factory can be queried for top-level binders. This is not correct for
local functions because they use method body binders, which are not
accessible from the binder factory.

Mostly, this doesn't matter. The exception is when you try to
speculatively bind an attribute on a type parameter. Here, you need an
in-method binder and VS will crash if it's the wrong binder. This was
uncommon since attributes on type parameters are not permitted in local
functions, but VS should not crash.

Tests have been added for this case.

### How was the bug found?

Customer reported.

### CODE REVIEW

**Comment by agocke** [comment]
cc @jaredpar @MeiChin-Tsai for ask-mode approval

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 1]
```diff
@@ -30,6 +30,71 @@ internal void VerifyDiagnostics(string source, CSharpCompilationOptions options,
...
+class C
+{
+    static void M()
+    {
+        void local<[A]T>() {}
+    }
+}");
+            var comp = CreateStandardCompilation(tree);
+            var model = comp.GetSemanticModel(tree);
+            var a = tree.GetRoot().DescendantNodes()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: >a [](start = 16, length = 1)

Consider asserting .ToString() of off this node or its parent so that reader can understand what node we are dealing with.

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 2]
```diff
@@ -30,6 +30,71 @@ internal void VerifyDiagnostics(string source, CSharpCompilationOptions options,
...
+            var newTree = SyntaxFactory.ParseSyntaxTree(text + " ");
+            var m = newTree.GetRoot()
+                .DescendantNodes().OfType<MethodDeclarationSyntax>().Single();
+
+            Assert.True(model.TryGetSpeculativeSemanticModelForMethodBody(m.Body.SpanStart, m, out model));
+
+            var x = newTree.GetRoot().DescendantNodes().OfType<IdentifierNameSyntax>().Single();
+            // If we aren't using the right binder here, the compiler crashes going through the binder factory
+            var info = model.GetSymbolInfo(x);
+            Assert.Null(info.Symbol);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: >Assert.Null(info.Symbol); [](start = 12, length = 25)

It would be good to test speculative semantic model with scenario where ```X``` actually binds to something.

**Comment by MeiChin-Tsai** [comment]
approved. Thanks!
