### PR TITLE
Pool background threads used for trampolines

### LINKED ISSUE #52751: Pressing Enter in .cs File Throttles CPU 25-30% for Over 30 Seconds
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Pressing-Enter-in-cs-File-Throttles-CPU/1400509)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:16.10.1]
Please see the attached recording.  Simply pressing the Enter button several times spikes the CPU to over 30% and then oscillates between 25-30% for 30-40 seconds.

---
#### DragonSpark on 4/16/2021, 09:32 AM: 

<p>Note that this may be related to <a target='_blank' href="https://developercommunity.visualstudio.com/t/razor-Development:-Basic-Development-Pe/1368587">https://developercommunity.visualstudio.com/t/razor-Development:-Basic-Development-Pe/1368587</a> but that has typically shown the grief in <code>.razor</code> files.  Here this issue is occurring within a <code>.cs</code> file which is new/different in my experience.</p>

#### Feedback Bot on 4/19/2021, 00:09 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by sharwell**
💡 A detailed scenario investigation and impact analysis is provided in https://github.com/dotnet/roslyn/issues/52751#issuecomment-822850144.

Fixes #52751

### CODE REVIEW

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs [hunk 1]
```diff
@@ -0,0 +1,170 @@
...
+                // Return the task.
+                return tcs.Task;
+
+                static void createThread()
+                {
+                    // Create a new background thread to run the work.
+                    var t = new Thread(() =>
+                    {
+                        // Repeatedly get the next item and invoke it, setting its TCS when we're done.
+                        // This will wait for up to the idle time before giving up and exiting.
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:76]: not quite seeing yet how it waits up the idle time limit.

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs [hunk 2]
```diff
@@ -0,0 +1,170 @@
...
+                        while (tryDequeue(out (Delegate action, object? state, TaskCompletionSource<object?> tcs) item))
+                        {
+                            try
+                            {
+                                if (item.action is Func<object?, object?> pts)
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:81]: pts?

**Comment by CyrusNajmabadi** [comment]
Overall i like this.  but i need my brain fresh to read the threading stuff.  Will review tomorrow.

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs (hunk 1 above)
Comment (stephentoub) [reply src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:76]: https://github.com/dotnet/roslyn/pull/52756/files#diff-7fd36fcbfc85d0e7e8ad471f962dcfc1e75649ab9b75a94d46a988a395a4d59cR146

**Comment by sharwell** [comment]
> but i need my brain fresh to read the threading stuff

It may help to know that @stephentoub authored the original 😄

File: src/Compilers/Core/Portable/Serialization/ObjectWriter.cs [hunk 3]
```diff
@@ -888,15 +890,17 @@ private void WriteObject(object instance, IObjectWritable? instanceAsWritable)
...
-                        TaskCreationOptions.LongRunning,
-                        TaskScheduler.Default);
+                    // don't blow the stack.
+                    var task = SerializationThreadPool.RunOnBackgroundThreadAsync(
+                        obj =>
+                        {
+                            WriteObjectWorker((IObjectWritable)obj!);
+                            return null;
+                        },
+                        writable);
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/Serialization/ObjectWriter.cs:903]: so we return the task, just to synchronously block on the result of it below.  Shoudl we jsut have the helper be a synchronous void method instead and move this blocking into it instead?

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs [hunk 4]
```diff
@@ -0,0 +1,170 @@
...
+                return tcs.Task;
+
+                static void createThread()
+                {
+                    // Create a new background thread to run the work.
+                    var t = new Thread(() =>
+                    {
+                        // Repeatedly get the next item and invoke it, setting its TCS when we're done.
+                        // This will wait for up to the idle time before giving up and exiting.
+                        while (tryDequeue(out (Delegate action, object? state, TaskCompletionSource<object?> tcs) item))
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:77]:
```suggestion
                        while (tryDequeue(out var item))
```

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs [hunk 5]
```diff
@@ -0,0 +1,170 @@
...
+            /// </summary>
+            public static Task<object?> QueueAsync(Func<object?, object?> threadStart, object? state) => QueueAsync((Delegate)threadStart, state);
+
+            private static Task<object?> QueueAsync(Delegate threadStart, object? state)
+            {
+                // Create the TaskCompletionSource used to represent this work.
+                // Call sites only care about completion, not about the distinction between
+                // success and failure and do not expect exceptions to be propagated in this manner,
+                // so only SetResult is used.
+                var tcs = new TaskCompletionSource<object?>(TaskCreationOptions.RunContinuationsAsynchronously);
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:62]: doc why we want RunContinuationsAsynchronously here.

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs [hunk 6]
```diff
@@ -0,0 +1,170 @@
...
+                static bool tryDequeue(out (Delegate action, object? state, TaskCompletionSource<object?> tcs) item)
+                {
+                    // Dequeues the next item if one is available. Before checking,
+                    // the available thread count is increased, so that enqueuers can
+                    // see how many threads are currently waiting, with the count
+                    // decreased after. Each time it waits, it'll wait for at most
+                    // the idle timeout before giving up.
+                    lock (s_queue)
+                    {
+                        s_availableThreads++;
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:141]: this part is still the part that i'm not understanding.  shouldn't the ++ And -- be done in the createThread part so that we know if we have a thread running that is available to process things?  having it be in tryDequeue is honestly confusing my brain.

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs [hunk 7]
```diff
@@ -0,0 +1,170 @@
...
+                        try
+                        {
+                            while (s_queue.Count == 0)
+                            {
+                                if (!Monitor.Wait(s_queue, s_idleTimeout))
+                                {
+                                    if (s_queue.Count > 0)
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:148]: this is just for optimism right?  we'd only get into the if if the idle timeout expired, if htere had been an item added prior to that, we'd have been pulsed.  so this is just for the *very* narrow case of we timeout and just then an item is added?

File: src/Compilers/Core/Portable/Serialization/ObjectWriter.cs (hunk 3 above)
Comment (sharwell) [reply src/Compilers/Core/Portable/Serialization/ObjectWriter.cs:903]: > Shoudl we jsut have the helper be a synchronous void method instead and move this blocking into it instead?

No. Blocking should always be pushed as far up the stack as possible. This method is the specific method that requires a blocking wait, and therefore this is the only method where the blocking wait is appropriate to appear.

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs (hunk 4 above)
Comment (sharwell) [reply src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:77]: The 'Use var' analyzer and Quick Info both think these are not the same type.

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs (hunk 2 above)
Comment (sharwell) [reply src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:81]: ⏱️ Renamed to `callbackWithState`

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs (hunk 6 above)
Comment (sharwell) [reply src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:141]: `s_availableThreads` is the number of threads waiting in `tryDequeue`.

Comment (CyrusNajmabadi) [reply src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:133]: Ah. Perhaps another name might help here. But it's not a big deal. If this babe works for you, that's fine with me.

File: src/Compilers/Core/Portable/Serialization/ObjectWriter.cs (hunk 3 above)
Comment (CyrusNajmabadi) [reply src/Compilers/Core/Portable/Serialization/ObjectWriter.cs:903]: I don't agree with that principle. This is a coupled set of functions. But it's not a hill I'd die on here. To me, it provides no value or clarity to have the async concept bleed out to the single location where it is known it will be blocked on (since that's the entire purpose of this component)

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs (hunk 4 above)
Comment (sharwell) [reply src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs]: Not sure. I replaced it manually and it seems to work, but when I hover over `var` it shows all the types as fully-qualified.

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs (hunk 5 above)
Comment (sharwell) [reply src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:58]: ➡️ Added this documentation, and removed the incorrect documentation about only using `SetResult`

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs (hunk 4 above)
Comment (CyrusNajmabadi) [reply src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs]: I wonder if we have an issue here with local functions... Strange

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs (hunk 7 above)
Comment (CyrusNajmabadi) [reply src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:140]: Right. That's my point. This is just for the very off chance that the timeout fired and it just do happens that right before that we had enqueued an item. But we were woken up for timeout, and not the pulse that occurred. 

It doesn't seem impossible. But it also seems very unlikely to ever happen.  So this feels like potential unnecessary complexity. I'm not saying to remove it. I'm just trying to gauge how important this is, and if my reading here is correct or not.

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs (hunk 6 above)
Comment (sharwell) [reply src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:133]: I left the name, but I did update the comment on the field to call out `tryDequeue` explicitly.

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs (hunk 7 above)
Comment (sharwell) [reply src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:140]: I believe if we omit this check, it's possible for this thread to be notified of a new element, ignore it, and then not have another thread wake up to handle it instead.

**Comment by sharwell** [comment]
@dotnet/roslyn-compiler for reviews

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs (hunk 7 above)
Comment (CyrusNajmabadi) [reply src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:140]: Hrmm... i'd like stephen to weigh in.  I would think teh Pulse woudl ensure that some waiting thread always wakes up and thus will see this value and process it.

Comment (CyrusNajmabadi) [reply src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:140]: (where i'm not good at analyzing this sort of code is when timeouts are part of thigns.  i don't have a clear mental model of the lifetimes and how we ensure that we either kick off a thread if necessary, or we defer to an existing thread in a way that we're sure will ensure the work will always be picked up.

**Comment by sharwell** [comment]
@dotnet/roslyn-compiler  for reviews

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs (hunk 7 above)
Comment (stephentoub) [reply src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:140]: Locks are not fair.  When thread 1 while holding the lock does a Pulse, it signals to the thread 2 at the front of the wait queue that it should become ready, but thread 2 still needs to reaquire the lock as part of successfully exiting from the Wait call, and thread 1 needs to exit the lock before that can happen.  When thread 2 does exit the lock, there's a race between thread 2 trying to acquire the lock and thread 3 coming along and trying to take the lock as well.  If thread 3 does acquire the lock before thread 2, it might dequeue an item, and there's then no guarantee that thread 2 would successfully dequeue an item when it sees Wait return true.  Hence the need for the second check; it's for correctness, not performance.

You can see this actually happening with a repro like:
```C#
using System;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    static readonly ManualResetEventSlim mres1 = new();
    static readonly ManualResetEventSlim mres3 = new();
    static readonly object syncObj = new();

    static volatile int value;
    static volatile int count1;
    static volatile int count3;

    static void Main()
    {
        while (true)
        {
            value = 0;
            mres1.Reset();
            mres3.Reset();

            Task.WaitAll(
                Task.Run(() => // Thread #2
                {
                    lock (syncObj)
                    {
                        mres1.Set();
                        Monitor.Wait(syncObj);
                        if (value == 1) count1++;
                        else if (value == 3) count3++;
                        else throw new Exception(value.ToString());
                        Console.SetCursorPosition(0, 0);
                        Console.WriteLine("1: " + count1);
                        Console.WriteLine("3: " + count3);
                    }
                }),
                Task.Run(() => // Thread #1
                {
                    mres1.Wait();
                    lock (syncObj)
                    {
                        mres3.Set();
                        Monitor.Pulse(syncObj);
                        value = 1;
                    }
                }),
                Task.Run(() => // Thread #3
                {
                    mres3.Wait();
                    lock (syncObj)
                    {
                        value = 3;
                    }
                }));
        }
    }
}
```

Here Thread 2 takes the lock on syncObj, and only then is Thread 1 allowed to try to acquire it.  Thread 2 proceeds to Wait on the lock, which will enable Thread 1 to successfully acquire it.  Thread 1 then unblocks Thread 3, which now also tries to acquire the lock, and Thread 1 proceeds to pulse the syncObj in order to unblock Thread 2.  Before exiting the lock, Thread 1 sets an int value to be 1.  Now, if there weren't a race condition, Thread 2 would always win, and when it woke up from its Wait it would see that value is always 1.  If Thread 3 wins the race, it will set the value to 3, and so Thread 1 would see the int value as 3.  And if you run the above, you'll see that Thread 3 actually ends up winning most of the time.

**Comment by sharwell** [comment]
@dotnet/roslyn-compiler for reviews. Do note that I have provided a detailed explanation for the underlying bug in https://github.com/dotnet/roslyn/issues/52751#issuecomment-822850144, which will help frame the change.

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs (hunk 7 above)
Comment (CyrusNajmabadi) [reply src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:140]: > Hence the need for the second check; it's for correctness, not performance.

That's great to know. Also, the above is exactly the sort of info that would be good to include in the pr. To me, it was not self evident and would be easy to screw up.

Can we add comments to this effect @sharwell ?

Comment (sharwell) [reply src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:140]: Yes, although I need to adjust the description. The comment was written in this context (emphasis mine):

```
... no guarantee that thread 2 would successfully dequeue an item when it sees Wait return **true** ...
```

Since this check is located under the condition where `Wait` returns _false_, a similar condition can occur but the sequence is different.

Comment (sharwell) [reply src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:140]: @CyrusNajmabadi details now added in a comment

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs [hunk 8]
```diff
@@ -0,0 +1,181 @@
...
+                                        //  3. Thread A times out and enters the ready thread queue
+                                        //  4. Thread B observes that s_queue.Count (1) <= s_availableThreads (1), so it
+                                        //     calls Pulse instead of creating a new thread
+                                        //  5. Thread B releases the lock
+                                        //  6. Thread A acquires the lock, and Monitor.Wait returns false
+                                        //
+                                        // Since no new thread was created in step 4, we must handle the enqueued
+                                        // element or the thread will exit and the item will sit in the queue
+                                        // indefinitely.
+                                        break;
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:161]: this is perfect, thanks very much.

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs [hunk 9]
```diff
@@ -0,0 +1,181 @@
...
+            private static readonly TimeSpan s_idleTimeout = TimeSpan.FromSeconds(1);
+
+            /// <summary>The queue of work items. Also used as a lock to protect all relevant state.</summary>
+            private static readonly Queue<(Delegate, object?, TaskCompletionSource<object?>)> s_queue = new();
+
+            /// <summary>The number of threads currently waiting in <c>tryDequeue</c> for work to arrive.</summary>
+            private static int s_availableThreads = 0;
+
+            /// <summary>
+            /// Queues an <see cref="Action"/> delegate to be executed immediately on another thread,
```
Comment (RikkiGibson) [inline src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:41]: I didn't see use of `Action` of the implementation. Should these references actually be to `Func<T>`/`Func<T1, T2>`?

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs [hunk 10]
```diff
@@ -0,0 +1,181 @@
...
+                            Monitor.Pulse(s_queue);
+                            return;
+                        }
+                    }
+
+                    // No thread was currently available.  Create one.
+                    createThread();
+                }
+
+                static bool tryDequeue(out (Delegate action, object? state, TaskCompletionSource<object?> tcs) item)
```
Comment (RikkiGibson) [inline src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:124]: Consider including these parameter names in similar tuples in this file.

File: src/Compilers/Core/Portable/Serialization/ObjectWriter.cs [hunk 11]
```diff
@@ -888,15 +890,17 @@ private void WriteObject(object instance, IObjectWritable? instanceAsWritable)
...
                     // If we're recursing too deep, move the work to another thread to do so we
-                    // don't blow the stack.  'LongRunning' ensures that we get a dedicated thread
-                    // to do this work.  That way we don't end up blocking the threadpool.
-                    var task = Task.Factory.StartNew(
-                        obj => WriteObjectWorker((IObjectWritable)obj!),
-                        writable,
-                        _cancellationToken,
-                        TaskCreationOptions.LongRunning,
-                        TaskScheduler.Default);
+                    // don't blow the stack.
```
Comment (RikkiGibson) [inline src/Compilers/Core/Portable/Serialization/ObjectWriter.cs:896]: The original comment mentions that we want to avoid blocking the threadpool. It feels like we are adding the 'SerializationThreadPool' type because we don't have a built-in alternative that allows us to pool threads while also not risking blocking other kinds of work in the "shared" threadpool. Is that correct?

**Review by RikkiGibson — APPROVED** [review]
I am fine with this change since it does seem to strictly improve things, but would like to know:

1. Do you have any measurements for this change under some workload similar to the linked issue #52751?

2. Would it be reasonable to, instead of using thread trampolining, use explicit stacks in ObjectReader/ObjectWriter. The implementation doesn't look extremely complicated to me so it feels like maybe not too much readability/maintainability would be lost.

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs [hunk 12]
```diff
@@ -0,0 +1,162 @@
...
+// See the LICENSE file in the project root for more information.
+
+using System;
+using System.Collections.Generic;
+using System.Threading;
+using System.Threading.Tasks;
+
+namespace Roslyn.Utilities
+{
+    internal static class SerializationThreadPool
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs:12]: I reviewed the code, and these are the only production code uses of `TaskCreationOptions.LongRunning` or `TaskContinuationOptions.LongRunning` that would be candidates for this. It seems safe to defer that work until such time as we have evidence of a need.

**Comment by sharwell** [comment]
> Do you have any measurements for this change under some workload similar to the linked issue #52751?

Not specifically, but the ETW clearly shows that the strategy would resolve a majority of thread creations.

> Would it be reasonable to, instead of using thread trampolining, use explicit stacks in ObjectReader/ObjectWriter.

This is tracked by #23331. In a similar case, I saw about 3-4x overall throughput improvement by rewriting a deeply-recursive serializer. But it's hard enough that it hasn't moved forward due to complexity even though the problem and benefits are well known.

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs [hunk 13]
```diff
@@ -0,0 +1,181 @@
...
+            /// <summary>The number of threads currently waiting in <c>tryDequeue</c> for work to arrive.</summary>
+            private static int s_availableThreads = 0;
+
+            /// <summary>
+            /// Queues an <see cref="Action"/> delegate to be executed immediately on another thread,
+            /// and returns a <see cref="Task"/> that represents its eventual completion. The task will
+            /// always end in the <see cref="TaskStatus.RanToCompletion"/> state; if the delegate throws
+            /// an exception, it'll be allowed to propagate on the thread, crashing the process.
+            /// </summary>
+            public static Task<object?> QueueAsync(Func<object?> threadStart) => QueueAsync((Delegate)threadStart, null);
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs]: ➡️ Now updated

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs (hunk 9 above)
Comment (sharwell) [reply src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs]: ➡️ Now updated

File: src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs (hunk 10 above)
Comment (sharwell) [reply src/Compilers/Core/Portable/Serialization/SerializationThreadPool.cs]: ➡️ Now updated

**Review by RikkiGibson — APPROVED** [review]

**Comment by sharwell** [comment]
@dotnet/roslyn-compiler I need to know what milestone this should target.

**Comment by sharwell** [comment]
This is now retargeted to release/dev16.11. @dotnet/roslyn-compiler for a second review.

**Comment by sharwell** [comment]
@dotnet/roslyn-compiler for second review

**Comment by sharwell** [comment]
@dotnet/roslyn-compiler for second review

**Review by jaredpar — APPROVED** [review]
