### PR TITLE
Add test to confirm that a bug is fixed.

### LINKED ISSUE #27104: Visual Studio 2017 will crash with this code.
**15.7.2**: 

**Steps to Reproduce**:

1. write this code:
```
      foreach(_ int "")
            {
            }
```
2. move mouse to _ ,wait about 2 seconds

**Expected Behavior**: nohting

**Actual Behavior**:Visual Studio 2017 will crash

### PR DESCRIPTION
**Pull request by gafter**
Fixes #27104

@dotnet/roslyn-compiler  May I please have one review of this test-only addition?

### CODE REVIEW

File: src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs [hunk 1]
```diff
@@ -6580,5 +6580,36 @@ public void UnmanagedConstraint_Delegate()
                 SymbolDisplayPartKind.Space,
                 SymbolDisplayPartKind.Keyword);
         }
+
+        [Fact, WorkItem(27104, "https://github.com/dotnet/roslyn/issues/27104")]
+        public void BadDiscardInForeachLoop_01()
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs]: Nit: consider removing the `_01` from the name
