### PR TITLE
Export additional code styles in .editorconfig generation

### LINKED ISSUE #30086: Add support for generating current naming rules/options in the editorconfig generator
See the discussion here: https://github.com/dotnet/roslyn/pull/30043#discussion_r219246165. Current editorconfig file generation only handles formatting and code style options, but we should extend it to generate entries for naming rules as well.

### LINKED ISSUE #33766: Settings for using directives not exported to .editorconfig
**Version Used**: VS2019 dogfood

**Steps to Reproduce**:

1. Open Tools -> Options
2. Configure settings on Text Editor -> C# -> Advanced for how to style using directives
    * Place 'System' directives first when sorting usings
    * Separate using directive groups
3. Switch to Code Style options and export .editorconfig settings

**Expected Behavior**:
These options for using directives should be exported (dotnet_sort_system_directives_first and dotnet_separate_import_directive_groups respectively)

**Actual Behavior**:
They are not exported to the .editorconfig file

### PR DESCRIPTION
**Pull request by sharwell**
~~Builds on #33946~~
Possibly supersedes #34122 

* Export using directives styles when generating .editorconfig (Fixes #33766)
* Export naming styles when generating .editorconfig (Fixes #30086)

### CODE REVIEW

File: src/Workspaces/Core/Portable/Editing/GenerationOptions.cs [hunk 1]
```diff
@@ -1,21 +1,28 @@
...
+using System.Collections.Immutable;
+using Microsoft.CodeAnalysis.CodeStyle;
 using Microsoft.CodeAnalysis.Options;
 
 namespace Microsoft.CodeAnalysis.Editing
 {
     internal class GenerationOptions
     {
         public static readonly PerLanguageOption<bool> PlaceSystemNamespaceFirst = new PerLanguageOption<bool>(nameof(GenerationOptions),
+            CodeStyleOptionGroups.Usings,
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Editing/GenerationOptions.cs]: note: we've generally called this 'imports' rather than 'usings' as 'imports' was found to at least make some amount of sense for both C# and VB, whereas 'usings' was completely non-sensical for the VB crowd.

File: src/Workspaces/Core/Portable/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_NamingStyle.cs [hunk 2]
```diff
@@ -102,5 +103,29 @@ private static bool TryParseCapitalizationScheme(string namingStyleCapitalizatio
...
+            switch (capitalization)
+            {
+                case Capitalization.PascalCase:
+                    return "pascal_case";
+
+                case Capitalization.CamelCase:
+                    return "camel_case";
+
+                case Capitalization.FirstUpper:
+                    return "first_word_upper";
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_NamingStyle.cs]: nit: it woudlbe nice if the enum value matched this text.

File: src/Workspaces/Core/Portable/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_SymbolSpec.cs [hunk 3]
```diff
@@ -281,5 +282,206 @@ private static ImmutableArray<ModifierKind> ParseModifiers(string symbolSpecRequ
...
+
+            return string.Join(", ", accessibilities.Select(accessibility => accessibility.ToEditorConfigString(languageName)));
+        }
+
+        private static string ToEditorConfigString(this Accessibility accessibility, string languageName)
+        {
+            switch (accessibility)
+            {
+                case Accessibility.NotApplicable:
+                    return "local";
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_SymbolSpec.cs]: this could use a comment :)

File: src/Workspaces/Core/Portable/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_SymbolSpec.cs [hunk 4]
```diff
@@ -281,5 +282,206 @@ private static ImmutableArray<ModifierKind> ParseModifiers(string symbolSpecRequ
...
+        }
+
+        private static string ToEditorConfigString(this ModifierKind modifier, string languageName)
+        {
+            switch (modifier.ModifierKindWrapper)
+            {
+                case ModifierKindEnum.IsAbstract:
+                    if (languageName == LanguageNames.VisualBasic)
+                    {
+                        return "must_inherit";
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_SymbolSpec.cs]: just to check, but thsi _ was intentional?  even though it's "MustInherit" in VB as the actual token?

File: src/Workspaces/Core/Portable/Editing/GenerationOptions.cs (hunk 1 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Editing/GenerationOptions.cs]: 📝 This was not changed by this pull request.

@dpoeschl should this be in scope for this pull request?

File: src/Workspaces/Core/Portable/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_NamingStyle.cs (hunk 2 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_NamingStyle.cs]: ➡️ These were already defined

File: src/Workspaces/Core/Portable/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_SymbolSpec.cs (hunk 4 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_SymbolSpec.cs]: ➡️ This was already defined

https://github.com/dotnet/roslyn/blob/7f809efa06ad3367dbac5971c9026433be6369b6/src/Workspaces/Core/Portable/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_SymbolSpec.cs#L261

File: src/Workspaces/Core/Portable/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_SymbolSpec.cs (hunk 3 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_SymbolSpec.cs]: ➡️ This is just a mirror of existing code a few lines up:

https://github.com/dotnet/roslyn/blob/7f809efa06ad3367dbac5971c9026433be6369b6/src/Workspaces/Core/Portable/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_SymbolSpec.cs#L213-L215

File: src/Workspaces/Core/Portable/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_NamingStyle.cs (hunk 2 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/NamingStyles/EditorConfig/EditorConfigNamingStyleParser_NamingStyle.cs]: Understood.  Would still like them to match :D  (i'm not pushing on it, hence hte 'nit'), just something i noticed :)
