### PR TITLE
don't escape method names in signature help tool tips

### LINKED ISSUE #3537: Argument-completion tooltip incorrectly escapes member name
Look at this picture:
next

In the argument-completion tooltip it shows the escaped form `Random.[Next]()` rather than `Random.Next()`. It shouldn't! There's no need to escape here!

I notice that when I finish typing the method and hover over it, to get the normal tooltip, then this tooltip is correct: it doesn't show the escape.
next2

### PR DESCRIPTION
**Pull request by brettfo**
This change brings the argument-completion tool tip in line with quick info in not escaping special identifier names.  E.g., for the following code, the tooltip for the invocation on the indicated line should display as `C.Next()` instead of `C.[Next]()`.

``` VB
Class C
    Sub [Next]()
        Dim x As New C
        x.Next() ' bug is on this line
    End Sub
End Class
```

Fixes #3537.

Tagging @Pilchie @dpoeschl @jasonmalinowski @rchande  @DustinCampbell @balajikris @basoundr @jmarolf @davkean for review.

### CODE REVIEW

File: src/EditorFeatures/VisualBasic/SignatureHelp/InvocationExpressionSignatureHelpProvider.MemberGroup.vb [hunk 1]
```diff
@@ -82,6 +82,7 @@ Namespace Microsoft.CodeAnalysis.Editor.VisualBasic.SignatureHelp
             Dim format = MinimallyQualifiedWithoutParametersFormat
             format = format.RemoveMemberOptions(SymbolDisplayMemberOptions.IncludeType Or SymbolDisplayMemberOptions.IncludeContainingType)
             format = format.RemoveKindOptions(SymbolDisplayKindOptions.IncludeMemberKeyword)
+            format = format.WithMiscellaneousOptions(format.MiscellaneousOptions And (Not SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers))
```
Comment (brettfo) [inline src/EditorFeatures/VisualBasic/SignatureHelp/InvocationExpressionSignatureHelpProvider.MemberGroup.vb]: This leads to the question: should `SymbolDisplayFormat` get a `RemoveMiscellaneousOptions()` method?  That would be a public API change.  See [here](http://source.roslyn.io/#Microsoft.CodeAnalysis/SymbolDisplay/SymbolDisplayFormat.cs,f1a74c53f582efcb,references).

**Comment by Pilchie** [comment]
:+1:

**Comment by brettfo** [comment]
retest this please
