### PR TITLE
Permit a parenthesized expression as the first operand of a switch expression

### LINKED ISSUE #26584: Parenthesized expression is parsed as a cast if it's followed by 'switch'
**Version Used**:  branch `features/recusrive-patterns`

**Steps to Reproduce**:

```cs
class C {
    void M(bool t)  {
        Console.Write((t) switch {var x => x});
    }
}
```

**Expected Behavior**:

No error.

**Actual Behavior**:

`error CS1525: Invalid expression term 'switch'`
`error CS0118: 't' is a variable but is used like a type`

### PR DESCRIPTION
**Pull request by gafter**
Fixes #26584

@cston @agocke @dotnet/roslyn-compiler May I please have a couple of reviews for this tiny bug fix?

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 1]
```diff
@@ -8716,7 +8716,6 @@ private static bool IsInvalidSubExpression(SyntaxKind kind)
                 case SyntaxKind.IfKeyword:
                 case SyntaxKind.LockKeyword:
                 case SyntaxKind.ReturnKeyword:
-                case SyntaxKind.SwitchKeyword:
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: I didn't understand this change. How is `switch` a sub-expression?

Comment (gafter) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: Didn't mean to change that. Will revert. I don't think it would change behavior, though.

File: src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs [hunk 2]
```diff
@@ -4090,5 +4090,73 @@ public void ArrayOfTupleType18()
             }
             EOF();
         }
+
+        [Fact]
+        public void ParenthseizedExpressionOfSwitchExpression()
```
Comment (agocke) [inline src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs]: Typo in name

**Comment by gafter** [comment]
@agocke Do you mean a cast followed by a switch? e.g. `(Type)e switch { _ => null }` ?

**Comment by agocke** [comment]
@gafter I did, yes, but now I realize that will probably just be handled like any other expression, since there will be a following identifier.
