### PR TITLE
always use the 'en-US' culture for `.ToUpper()` when creating the new property name

### LINKED ISSUE #5524: Encapsulate Field refactoring can result in incorrect case conversions depending on the user's locale
As shown in [this SO question](http://stackoverflow.com/questions/32825792/visual-studio-2015-encapsulate-field/32825978), applying the Encapsulate field on a field starting with `i`, eg `inside`, results in a property named `İnside` instead of `Inside` if the user's locale is set to Turkish. 

This is caused because [AbstractEncapsulateFieldService.GeneratePropertyName](https://github.com/dotnet/roslyn/blob/de252f4feb10428bdf4bcbeebc73a8deb19af3c5/src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs#L362) makes a call to `char.ToUpper()` without specifying the invariant culture. As a result, the case conversion is culture-specific, using the current user's locale. The case of the Turkish `i` is even described in the MSDN Article [Writing Culture-Safe Managed Code](https://msdn.microsoft.com/en-us/library/ms994325.aspx#cltsafcode_topic4). 

The fix should be to change line 362 to pass `CultureInfo.InvariantCulture` to `ToUpper()`, eg:

    return char.ToUpper(baseName[0],CultureInfo.InvariantCulture).ToString() + baseName.Substring(1);

instead of :

    return char.ToUpper(baseName[0]).ToString() + baseName.Substring(1);

### PR DESCRIPTION
**Pull request by brettfo**
As per an internal discussion, it was decided that it was best to use the "en-US" culture when calling `char.ToUpper()` to create the new property's name.  C# and VB share the same code path so only C# tests were added.

Fixes #5524.

### CODE REVIEW

File: src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs [hunk 1]
```diff
@@ -358,8 +360,9 @@ protected string GeneratePropertyName(string fieldName)
                 baseName = fieldName;
             }
 
-            // Make uppercase the first letter
-            return char.ToUpper(baseName[0]).ToString() + baseName.Substring(1);
+            // Make the first character upper case using the "en-US" culture
+            var firstCharacter = _englishUSCulture.TextInfo.ToUpper(baseName[0]);
```
Comment (brettfo) [inline src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs]: The portable APIs don't have `char.ToUpper(char, CultureInfo)` but according to the [reference source](http://referencesource.microsoft.com/#mscorlib/system/char.cs,8a74a9e898d17637) for that method, I can get the same result by using `TextInfo`.

**Comment by brettfo** [comment]
Tagging @dotnet/roslyn-ide for review.

File: src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs (hunk 1 above)
Comment (davkean) [inline src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs]: Can you add a comment and point to the issue on github around why this was done?

**Comment by CyrusNajmabadi** [comment]
Does this work properly if, say, I have accented characters?  Or characters in a language like farsi/Arabic?

**Comment by tmat** [comment]
Why en-US and not invariant?

**Comment by brettfo** [comment]
@CyrusNajmabadi: Good catch.  I've added tests with Arabic, Spanish (leading accented character), and Greek identifiers.
@tmat: According to an email conversation I had with @davkean, the en-US culture is kept up to date while the invariant one is not (but I'm not 100% sure what the definition of 'kept up to date' means in this case.)

**Comment by davkean** [comment]
This code doesn't handle surrogates/logical characters split into multiple actual chars, but the code ahs always had this bug and we should treat this as a separate bug which I'll file.

**Comment by davkean** [comment]
@tmat I'll reverse the question, why invariant?

**Comment by tmat** [comment]
Because that's what one is supposed to use when not caring about a specific culture.

**Comment by davkean** [comment]
We _do_ care about the culture here. If we had a way for the developer to say in VS "this is the culture/locale that I'm editing right now" then we would use that (it would never be invariant).

There aren't plans right now to add one, so this is a compromise. Based on that, we're choose the most _likely_ language that a user is editing in, in this case, en-US.

For IntelliSense, we did a slightly different approach; we first searching usign the current user's culture, and en-US, but here we have to choose one, so we went with en-US, as that was the least surprising.

**Comment by tmat** [comment]
I see. Sounds good then.

File: src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs [hunk 2]
```diff
@@ -340,6 +341,7 @@ protected IMethodSymbol CreateGet(string originalFieldName, IFieldSymbol field,
         }
 
         private static readonly char[] s_underscoreCharArray = new[] { '_' };
+        private static CultureInfo _englishUSCulture = new CultureInfo("en-US");
```
Comment (rchande) [inline src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs]: We're allocating one of these for Completion, too. Worth sharing?

File: src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs [hunk 3]
```diff
@@ -358,8 +360,10 @@ protected string GeneratePropertyName(string fieldName)
                 baseName = fieldName;
             }
 
-            // Make uppercase the first letter
-            return char.ToUpper(baseName[0]).ToString() + baseName.Substring(1);
+            // Make the first character upper case using the "en-US" culture.  See discusstion at
```
Comment (rchande) [inline src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs]: "discusstion"?
discussion?

**Comment by Pilchie** [comment]
:+1:

File: src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs (hunk 3 above)
Comment (brettfo) [inline src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs]: Not a regresstion, won't fix.

File: src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs (hunk 2 above)
Comment (brettfo) [inline src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs]: As soon as your PR with this gets merged I'll rebase and share.

Comment (rchande) [inline src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs]: My PR is merged. Thanks!

**Comment by rchande** [comment]
:+1:

**Comment by brettfo** [comment]
Rebased to take @rchande's changes and share the `CultureInfo` object.

File: src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs [hunk 4]
```diff
@@ -358,8 +358,10 @@ protected string GeneratePropertyName(string fieldName)
                 baseName = fieldName;
             }
 
-            // Make uppercase the first letter
-            return char.ToUpper(baseName[0]).ToString() + baseName.Substring(1);
+            // Make the first character upper case using the "en-US" culture.  See discussion at
+            // https://github.com/dotnet/roslyn/issues/5524.
+            var firstCharacter = CompletionRules.EnUSCultureInfo.TextInfo.ToUpper(baseName[0]);
```
Comment (rchande) [inline src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs]: Should we extract that static out to some utility class somewhere? I'm sure @jasonmalinowski and couplingchecker would be weeping right now.

Comment (brettfo) [inline src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs]: I considered adding `Features\Core\Portable\Common\CultureSomethingHelper.cs` but ultimately decided against it due to that class only containing one item, but I could be very easily convinced otherwise.

Comment (Pilchie) [inline src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs]: @davkean was suggesting that we have something like: `CultureFallbacks`, and also encapsulate the fallback comparison from @rchande's change there, so that all of that policy is in one place.

He also mentioned that we should use `CultureInfo.GetCulture()`, instead of `new CultureInfo()`.

**Comment by MattGertz** [comment]
Approved pending successful tests (if related to Dustin's change, then OK).

File: src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs (hunk 4 above)
Comment (brettfo) [inline src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs]: I spoke with @davkean offline and it was decided that to avoid churn in the `stabilization` branch this PR will be left as-is and I've filed issue #6442 to properly collect all usages of `new CultureInfo("en-US")`.

Comment (jasonmalinowski) [inline src/Features/Core/Portable/EncapsulateField/AbstractEncapsulateFieldService.cs]: @brettfo: thanks. I'll limit my weeping until that gets fixed.

**Comment by brettfo** [comment]
test prtest/win/dbg/eta please
