### PR TITLE
Fix TestOrdering test

### LINKED ISSUE #51817: FullyQualifyTests.TestOrdering does not pass
This test was missing a `Fact` attribute. When added, the test was failing.

https://github.com/dotnet/roslyn/blob/27913e0ff1564c82672aaff25a7621e882fa2386/src/EditorFeatures/VisualBasicTest/Diagnostics/FullyQualify/FullyQualifyTests.vb#L56-L83

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #51817 if CI passes.

### CODE REVIEW

File: src/EditorFeatures/VisualBasicTest/Diagnostics/FullyQualify/FullyQualifyTests.vb [hunk 1]
```diff
@@ -53,6 +53,7 @@ Namespace SomeNamespace
 End Namespace")
         End Function
 
+        <Fact, Trait(Traits.Feature, Traits.Features.CodeActionsFullyQualify)>
```
Comment (sharwell) [inline src/EditorFeatures/VisualBasicTest/Diagnostics/FullyQualify/FullyQualifyTests.vb:56]: Doh. I was hoping this would be applied after 6dd3258dafd16caa75a260aa5836032b1ec2382f.

Comment (Youssef1313) [reply src/EditorFeatures/VisualBasicTest/Diagnostics/FullyQualify/FullyQualifyTests.vb:56]: @sharwell So should we wait on this until #51812 is merged first?

Comment (sharwell) [reply src/EditorFeatures/VisualBasicTest/Diagnostics/FullyQualify/FullyQualifyTests.vb:56]: That or I merge this directly into my branch

Comment (Youssef1313) [reply src/EditorFeatures/VisualBasicTest/Diagnostics/FullyQualify/FullyQualifyTests.vb:56]: I'm okay either way. Feel free to close this and incorporate the fix into your branch.

**Review by sharwell — APPROVED** [review]
