### PR TITLE
MemberSemanticModel - special case binding CompilationUnit for a simple program.

### LINKED ISSUE #58521: System.InvalidCastException when SemanticModel attempts to bind simple program with a local function as the first statement
```
        [Fact]
        public void Test()
        {
            var source = @"
void F<T>(T t)
{
    var f = (ref T x) => 0;
}
";
            var compilation = CreateCompilation(source, options: TestOptions.DebugDll);
            var tree = compilation.SyntaxTrees[0];
            var identifier = tree.GetRoot().DescendantNodes().OfType<IdentifierNameSyntax>().First(id => id.Identifier.Text == "var");
            var model = compilation.GetSemanticModel(tree);
            var anonymousType = model.GetSymbolInfo(identifier).Symbol.GetSymbol<TypeSymbol>();

            model.GetOperation(identifier);
        }
```

Observed: System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.LocalFunctionSymbol' to type 'Microsoft.CodeAnalysis.CSharp.Symbols.SynthesizedSimpleProgramEntryPointSymbol'.

```
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindSimpleProgram(Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax compilationUnit, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 3436	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode syntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, bool includesFieldInitializers) Line 3427	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.IncrementalBinder.BindMethodBody(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, bool includeInitializersInBody) Line 2474	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.Bind(Microsoft.CodeAnalysis.CSharp.Binder binder, Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 106	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node) Line 2113	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetUpperBoundNode(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node, bool promoteToBindable) Line 519	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundRoot() Line 501	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetRootOperation() Line 1215	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetOperationWorker(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node, System.Threading.CancellationToken cancellationToken) Line 1153	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetOperationWorker(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node, System.Threading.CancellationToken cancellationToken) Line 194	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetOperationCore(Microsoft.CodeAnalysis.SyntaxNode node, System.Threading.CancellationToken cancellationToken) Line 478	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.SemanticModel.GetOperation(Microsoft.CodeAnalysis.SyntaxNode node, System.Threading.CancellationToken cancellationToken) Line 80	C#
>	Microsoft.CodeAnalysis.CSharp.Symbol.UnitTests.dll!Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.SymbolExtensionTests.Test() Line 113	C#
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #58521.

### CODE REVIEW

**Review by 333fred — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review for a small fix.

File: src/Compilers/CSharp/Test/Semantic/Semantics/TopLevelStatementsTests.cs [hunk 1]
```diff
@@ -9587,5 +9587,25 @@ namespace NS
...
+void F<T>(T t)
+{
+    var f = (ref T x) => 0;
+}
+";
+            var compilation = CreateCompilation(source, options: TestOptions.DebugDll);
+            var tree = compilation.SyntaxTrees[0];
+            var identifier = tree.GetRoot().DescendantNodes().OfType<IdentifierNameSyntax>().First(id => id.Identifier.Text == "var");
+            var model = compilation.GetSemanticModel(tree);
+            var anonymousType = model.GetSymbolInfo(identifier).Symbol.GetSymbol<TypeSymbol>();
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/TopLevelStatementsTests.cs:9605]: >anonymousType [](http://example.com/codeflow?start=16&length=13)

This value is unused.

File: src/Compilers/CSharp/Test/Semantic/Semantics/TopLevelStatementsTests.cs [hunk 2]
```diff
@@ -9587,5 +9587,25 @@ namespace NS
                 Diagnostic(ErrorCode.WRN_UnreferencedVarAssg, "x").WithArguments("x").WithLocation(6, 5)
                 );
         }
+
+        [Fact]
+        [WorkItem(58521, "https://github.com/dotnet/roslyn/issues/58521")]
+        public void Issue58521()
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/TopLevelStatementsTests.cs:9593]: >Issue58521 [](http://example.com/codeflow?start=20&length=10)

Consider giving a descriptive name.

**Review by cston — APPROVED** [review]
