### PR TITLE
VB: Make behavior of FindImplementationForInterfaceMember API on an interface consistent across source and metadata

### LINKED ISSUE #50713: inheritdoc failure for deep inheritance scenarios
**Version Used**: 16.8.4

**Steps to Reproduce**:

1. Define the following in C# project **ClassLibrary1**

```
public interface I1 { void Method(int arg); }
public interface I2 : I1 { new void Method(int arg); }
public interface I3 : I2 { new void Method(int arg); }
public interface I4 : I3 { new void Method(int arg); }
public interface I5 : I4 { new void Method(int arg); }
public interface I6 : I5 { new void Method(int arg); }
public interface I7 : I6 { new void Method(int arg); }
public interface I8 : I7 { new void Method(int arg); }
public interface I9 : I8 { new void Method(int arg); }
public interface I10 : I9 { new void Method(int arg); }
public interface I11 : I10 { new void Method(int arg); }
public interface I12 : I11 { new void Method(int arg); }
public interface I13 : I12 { new void Method(int arg); }
public interface I14 : I13 { new void Method(int arg); }
public interface I15 : I14 { new void Method(int arg); }
public interface I16 : I15 { new void Method(int arg); }
public interface I17 : I16 { new void Method(int arg); }
public interface I18 : I17 { new void Method(int arg); }
public interface I19 : I18 { new void Method(int arg); }
public interface I20 : I19 { new void Method(int arg); }
public interface I21 : I20 { new void Method(int arg); }
public interface I22 : I21 { new void Method(int arg); }
public interface I23 : I22 { new void Method(int arg); }
public interface I24 : I23 { new void Method(int arg); }
```

2. Create Visual Basic project **ClassLibrary2**
3. Add a reference from **ClassLibrary2** &rarr; **ClassLibrary1**
4. Add the following code to **ClassLibrary2**

```
Public Class C
    Sub M(arg As I24)
    End Sub
End Class
```

5. Type the following in `C.M`:

```
arg.Method(3)
```

**Expected Behavior**:

The IDE works. `arg.Method` is a reference to `I24.Method(int)`.

**Actual Behavior**:

The IDE hangs after typing `(`.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #50713.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

File: src/Compilers/CSharp/Test/Symbol/Symbols/InterfaceImplementationTests.cs [hunk 1]
```diff
@@ -2711,5 +2711,53 @@ static void Main()
...
+    new void M();
+}
+";
+
+            var comp1 = CreateCompilation(text1);
+            comp1.VerifyDiagnostics();
+
+            var i1M = comp1.GetMember("I1.M");
+            var i2 = comp1.GetMember<NamedTypeSymbol>("I2");
+            Assert.Null(i2.FindImplementationForInterfaceMember(i1M));
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Symbol/Symbols/InterfaceImplementationTests.cs:2736]: The doc comment for this member says:

> Returns the corresponding symbol in this type or a base type that implements interfaceMember

Given that I would expect that this returns a non-null value as the base type, or base interface, for `i2` does implement this member. Is the doc comment wrong here or am I misreading it somehow?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Symbol/Symbols/InterfaceImplementationTests.cs:2736]: > Given that I would expect that this returns a non-null value as the base type, or base interface, for i2 does implement this member. Is the doc comment wrong here or am I misreading it somehow? 

A declaration of a member in an interface is not an implementation. Also, even if a method was implemented by an interface (let's say written in C#), VB doesn't recognize those as implementations and would require a class to implement them anyway. 

---
In reply to: [563892891](https://github.com/dotnet/roslyn/pull/50722#discussion_r563892891) [](ancestors = 563892891)

**Review by jaredpar — APPROVED** [review]

**Review by 333fred — APPROVED** [review]
