### PR TITLE
Getting diagnostics and location of a token without a syntax tree should not crash

### LINKED ISSUE #17067: API crashes when getting diagnostics of parsed tokens
Here is a test that repros the crash. Tokens should not assume they've parse trees, or a parse tree should be created for independently parsed tokens:

```csharp
        public void APICrash()
        {
            var code = "token 1l";
            var tokens = SyntaxFactory.ParseTokens(code).ToList();
            Assert.Equal(3, tokens.Count); // "token", "1l", "EOF"

            var numeric = tokens[1];
            Assert.Equal("1l", numeric.Text);

            var diagnostics = numeric.GetDiagnostics();
            // Expecting to get a warning about using 'L' instead of 'l'.
            // NRE here because the token has no syntax tree attached to it.
        }
```

### PR DESCRIPTION
**Pull request by OmarTawfik**
Fixes #17067 
cc @AlekseyTs @gafter @dotnet/roslyn-compiler 

`this.SyntaxTree` is calculated from `Parent?.SyntaxTree`. So if `SyntaxTree` is null, this means that the parent (a `SyntaxNode`) is null, or doesn't belong to a tree. In that bug's case, the node is null.
Please let me know if there is another API surface area that the bug may have missed.

### CODE REVIEW

File: src/Compilers/Core/Portable/Syntax/SyntaxToken.cs [hunk 1]
```diff
@@ -634,9 +634,12 @@ internal SyntaxToken GetPreviousToken(Func<SyntaxToken, bool> predicate, Func<Sy
...
         {
-            return Node != null
-                ? this.SyntaxTree.GetLocation(this.Span)
-                : Location.None;
+            if (this.Node == null || this.SyntaxTree == null)
+            {
+                return Location.None;
+            }
+
+            return this.SyntaxTree.GetLocation(this.Span);
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Syntax/SyntaxToken.cs]: >this.SyntaxTree [](start = 19, length = 15)

Consider avoiding duplicate evaluation of this property by caching result of the first evaluation in a local.

File: src/Compilers/Core/Portable/Syntax/SyntaxToken.cs [hunk 2]
```diff
@@ -634,9 +634,12 @@ internal SyntaxToken GetPreviousToken(Func<SyntaxToken, bool> predicate, Func<Sy
         /// </summary>
         public Location GetLocation()
         {
-            return Node != null
-                ? this.SyntaxTree.GetLocation(this.Span)
-                : Location.None;
+            if (this.Node == null || this.SyntaxTree == null)
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Syntax/SyntaxToken.cs]: >this.Node == null [](start = 16, length = 17)

Would the check for SyntaxTree be sufficient on its own, or do we really need to check this condition as well?

File: src/Compilers/Core/Portable/Syntax/SyntaxToken.cs [hunk 3]
```diff
@@ -646,9 +649,18 @@ public Location GetLocation()
...
+                return SpecializedCollections.EmptyEnumerable<Diagnostic>();
+            }
+
+            if (this.SyntaxTree == null)
+            {
+                // If the parent or it's syntax tree are null, return diagnostics without a location.
+                return this.Node.GetDiagnostics().Select(Diagnostic.Create);
+            }
+
+            return this.SyntaxTree.GetDiagnostics(this);
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Syntax/SyntaxToken.cs]: >this.SyntaxTree [](start = 19, length = 15)

Consider avoiding double evaluation.

File: src/Compilers/Core/Portable/Syntax/SyntaxToken.cs [hunk 4]
```diff
@@ -646,9 +649,18 @@ public Location GetLocation()
...
-                : SpecializedCollections.EmptyEnumerable<Diagnostic>();
+            if (this.Node == null)
+            {
+                return SpecializedCollections.EmptyEnumerable<Diagnostic>();
+            }
+
+            if (this.SyntaxTree == null)
+            {
+                // If the parent or it's syntax tree are null, return diagnostics without a location.
+                return this.Node.GetDiagnostics().Select(Diagnostic.Create);
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Syntax/SyntaxToken.cs]: >this.Node.GetDiagnostics() [](start = 23, length = 26)

Would it make sense to optimize for the case when this returns an empty array?

Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Syntax/SyntaxToken.cs]: >Diagnostic.Create [](start = 57, length = 17)

Consider caching this delegate and reusing across function calls.

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxFactoryTests.cs [hunk 5]
```diff
@@ -377,5 +378,22 @@ private static string ToXmlEntities(string str)
 
             return builder.ToString();
         }
+
+        [Fact]
+        [WorkItem(17067, "https://github.com/dotnet/roslyn/issues/17067")]
+        public void GetTokenDiagnositcsWithoutSyntaxTree()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxFactoryTests.cs]: >GetTokenDiagnositcsWithoutSyntaxTree [](start = 20, length = 36)

Consider also adding a test when there is a tree.

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxFactoryTests.cs [hunk 6]
```diff
@@ -377,5 +378,22 @@ private static string ToXmlEntities(string str)
...
+            Assert.Equal(2, tokens.Count); // { "1l", "EOF" }
+
+            var literal = tokens.First();
+            Assert.Equal("1l", literal.Text);
+
+            Assert.Equal(Location.None, literal.GetLocation());
+
+            literal.GetDiagnostics().Verify(
+                // warning CS0078: The 'l' suffix is easily confused with the digit '1' -- use 'L' for clarity
+                Diagnostic(ErrorCode.WRN_LowercaseEllSuffix));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxFactoryTests.cs]: >Diagnostic(ErrorCode.WRN_LowercaseEllSuffix) [](start = 16, length = 44)

Consider also testing scenario with no diagnostics.

**Comment by AlekseyTs** [comment]
We should also try to test scenarios when Node is null, I am not sure when this happens.

**Comment by AlekseyTs** [comment]
Done with review pass.

File: src/Compilers/Core/Portable/Syntax/SyntaxToken.cs [hunk 7]
```diff
@@ -646,9 +649,18 @@ public Location GetLocation()
         /// </summary>
         public IEnumerable<Diagnostic> GetDiagnostics()
         {
-            return Node != null
-                ? this.SyntaxTree.GetDiagnostics(this)
-                : SpecializedCollections.EmptyEnumerable<Diagnostic>();
+            if (this.Node == null)
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/Syntax/SyntaxToken.cs]: Nit: coding guidelines ask to avoid `this.` prefix unless necessary.

File: src/Compilers/Core/Portable/Syntax/SyntaxToken.cs (hunk 2 above)
Comment (OmarTawfik) [inline src/Compilers/Core/Portable/Syntax/SyntaxToken.cs]: Checked the existing initializers. Node cannot exist without a SyntaxTree. Will edit.

---
In reply to: [106474900](https://github.com/dotnet/roslyn/pull/17899#discussion_r106474900) [](ancestors = 106474900)

**Comment by OmarTawfik** [comment]
@AlekseyTs @jaredpar responded to PR comments.

File: src/Compilers/Core/Portable/Syntax/SyntaxToken.cs [hunk 8]
```diff
@@ -22,6 +22,7 @@ public struct SyntaxToken : IEquatable<SyntaxToken>
     {
         internal static readonly Func<SyntaxToken, bool> NonZeroWidth = t => t.Width > 0;
         internal static readonly Func<SyntaxToken, bool> Any = t => true;
+        internal static readonly Func<DiagnosticInfo, Diagnostic> CreateDiagnosticWithoutLocation = Diagnostic.Create;
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Syntax/SyntaxToken.cs]: >internal [](start = 8, length = 8)

Should we use ```private``` accessibility? Do we expect other types to take advantage of this field?

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxFactoryTests.cs [hunk 9]
```diff
@@ -377,5 +378,83 @@ private static string ToXmlEntities(string str)
...
+            var literal = tokens.First();
+            Assert.Equal("1L", literal.Text);
+            Assert.Equal(Location.None, literal.GetLocation());
+
+            literal.GetDiagnostics().Verify();
+        }
+
+        [Fact]
+        [WorkItem(17067, "https://github.com/dotnet/roslyn/issues/17067")]
+        public void GetExpressionDiagnositcsWithoutSyntaxTree_WithDiagnositcs()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxFactoryTests.cs]: >Without [](start = 44, length = 7)

Did you mean to say "With" SyntaxTree?

**Comment by OmarTawfik** [comment]
@jaredpar @dotnet/roslyn-compiler can I get a second sign off?

**Comment by OmarTawfik** [comment]
ping @jaredpar since you already reviewed :)

File: src/Compilers/Core/Portable/Syntax/SyntaxToken.cs [hunk 10]
```diff
@@ -20,6 +20,8 @@ namespace Microsoft.CodeAnalysis
     [DebuggerDisplay("{GetDebuggerDisplay(), nq}")]
     public struct SyntaxToken : IEquatable<SyntaxToken>
     {
+        private static readonly Func<DiagnosticInfo, Diagnostic> CreateDiagnosticWithoutLocation = Diagnostic.Create;
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/Syntax/SyntaxToken.cs]: Private static field naming convention is `s_`

**Comment by OmarTawfik** [comment]
@jaredpar addressed.

**Comment by OmarTawfik** [comment]
@jaredpar can you please take a look?
