### PR TITLE
Throw MatchFailureException when match expression fails.

### LINKED ISSUE #31144: Throw MatchFailureException when match expression fails.
If `MatchFailureException` doesn't exist on the framework, throw its base class, `InvalidOperationException`.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #31144

### CODE REVIEW

File: src/Compilers/Core/Portable/WellKnownMember.cs [hunk 1]
```diff
@@ -482,6 +482,10 @@ internal enum WellKnownMember
         System_Runtime_CompilerServices_ITuple__get_Item,
         System_Runtime_CompilerServices_ITuple__get_Length,
 
+        System_InvalidOperationException__ctor,
+        System_MatchFailureException__ctor0,
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/WellKnownMember.cs]: >System_MatchFailureException__ctor0 [](start = 8, length = 35)

To follow established pattern, consider using name "System_MatchFailureException__ctor".

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_SwitchExpression.cs [hunk 2]
```diff
@@ -86,14 +87,29 @@ private BoundExpression LowerSwitchExpression(BoundSwitchExpression node)
...
-                    result.Add(_factory.ThrowNull());
+                    var objectType = _factory.SpecialType(SpecialType.System_Object);
+                    var thrownExpression =
+                        (optionalSavedInput != null &&
+                                implicitConversionExists(optionalSavedInput, objectType) &&
+                                _factory.WellKnownMember(WellKnownMember.System_MatchFailureException__ctor1, isOptional: true) is MethodSymbol newMatchFailureException1)
+                            ? _factory.New(newMatchFailureException1, _factory.Convert(objectType, optionalSavedInput)) :
+                        (_factory.WellKnownMember(WellKnownMember.System_MatchFailureException__ctor0, isOptional: true) is MethodSymbol newMatchFailureException0)
+                            ? _factory.New(newMatchFailureException0) :
+                        _factory.New(_factory.WellKnownMethod(WellKnownMember.System_InvalidOperationException__ctor));
```
Comment (svick) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_SwitchExpression.cs]: I realize that throwing `InvalidOperationException` is an edge case that's probably not going to happen very often, but shouldn't the thrown exception have a better message than the default "Operation is not valid due to the current state of the object."? The message could probably be the same as what `MatchFailureException.Message` is going to be.

File: src/Compilers/Core/Portable/WellKnownMember.cs [hunk 3]
```diff
@@ -482,6 +482,10 @@ internal enum WellKnownMember
...
+        System_MatchFailureException__ctor1,
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/WellKnownMember.cs]: >System_MatchFailureException__ctor1 [](start = 8, length = 35)

To follow established pattern, consider using name "System_MatchFailureException__ctorObject".

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs [hunk 4]
```diff
@@ -1489,6 +1489,211 @@ static int M1(bool? b1, bool? b2)
...
+    }
+}
+";
+            var compilation = CreatePatternCompilation(source);
+            compilation.VerifyDiagnostics(
+                // (8,24): warning CS8509: The switch expression does not handle all possible inputs (it is not exhaustive).
+                //             _ = (1, 2) switch { (3, 4) => 1 };
+                Diagnostic(ErrorCode.WRN_SwitchExpressionNotExhaustive, "switch").WithLocation(8, 24)
+                );
+            CompileAndVerify(compilation, expectedOutput: "MatchFailureException()");
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs]: >CompileAndVerify(compilation, expectedOutput: "MatchFailureException()"); [](start = 12, length = 73)

Based on the latest LDM decision, I would expect the value to be available for this scenario.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs [hunk 5]
```diff
@@ -1489,6 +1489,211 @@ static int M1(bool? b1, bool? b2)
...
+        }
+
+        [Fact]
+        public void UnmatchedInput_05()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs]: >UnmatchedInput_05 [](start = 20, length = 17)

Please add a test for a scenario when neither InvalidOperationException, nor MatchFailureException are available at compile time.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 2).

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_SwitchExpression.cs (hunk 2 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_SwitchExpression.cs]: I do not expect any message for `InvalidOperationException .Message`. The use of this exception is merely to allow using pattern-matching on platforms that precede the introduction of `MatchFailureException`. The message in `MatchFailureException.Message` will depend on your `corefx` implementation, none of which exist yet.

**Comment by gafter** [comment]
@AlekseyTs I believe I've responded to all comments. Do you have any others?

File: src/Compilers/Core/Portable/WellKnownMembers.cs [hunk 6]
```diff
@@ -3328,6 +3328,28 @@ static WellKnownMembers()
...
                     (byte)SignatureTypeCode.TypeHandle, (byte)SpecialType.System_Int32, // Return Type
+
+                 // System_InvalidOperationException__ctor
+                 (byte)MemberFlags.Constructor,                                                                                               // Flags
+                  (byte)WellKnownType.ExtSentinel, (byte)(WellKnownType.System_InvalidOperationException - WellKnownType.ExtSentinel),        // DeclaringTypeId
+                 0,                                                                                                                           // Arity
+                    0,                                                                                                                        // Method Signature
+                    (byte)SignatureTypeCode.TypeHandle, (byte)SpecialType.System_Void,
+
+                 // System_MatchFailureException__ctor0
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/WellKnownMembers.cs]: >System_MatchFailureException__ctor0 [](start = 20, length = 35)

Please propagate the rename here too.

File: src/Compilers/Core/Portable/WellKnownMembers.cs [hunk 7]
```diff
@@ -3328,6 +3328,28 @@ static WellKnownMembers()
...
+                 (byte)MemberFlags.Constructor,                                                                                               // Flags
+                 (byte)WellKnownType.ExtSentinel, (byte)(WellKnownType.System_MatchFailureException - WellKnownType.ExtSentinel),             // DeclaringTypeId
+                 0,                                                                                                                           // Arity
+                    0,                                                                                                                        // Method Signature
+                    (byte)SignatureTypeCode.TypeHandle, (byte)SpecialType.System_Void,
+
+                 // System_MatchFailureException__ctor1
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/WellKnownMembers.cs]: >System_MatchFailureException__ctor1 [](start = 20, length = 35)

Please propagate the rename here too.

File: src/Compilers/Core/Portable/WellKnownMembers.cs [hunk 8]
```diff
@@ -3746,6 +3768,9 @@ static WellKnownMembers()
                 ".ctor",                                    // System_Threading_Tasks_ValueTask_T__ctor
                 "get_Item",                                 // System_Runtime_CompilerServices_ITuple__get_Item
                 "get_Length",                               // System_Runtime_CompilerServices_ITuple__get_Length
+                ".ctor",                                    // System_InvalidOperationException__ctor
+                ".ctor",                                    // System_MatchFailureException__ctor0
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/WellKnownMembers.cs]: >System_MatchFailureException__ctor0 [](start = 63, length = 35)

Please propagate the rename here too.

File: src/Compilers/Core/Portable/WellKnownMembers.cs [hunk 9]
```diff
@@ -3746,6 +3768,9 @@ static WellKnownMembers()
...
+                ".ctor",                                    // System_MatchFailureException__ctor1
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/WellKnownMembers.cs]: >System_MatchFailureException__ctor1 [](start = 63, length = 35)

Please propagate the rename here too.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs (hunk 4 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs]: > The generated code does not construct a tuple object for the switch expression, so that tuple object cannot be trivially boxed into object

I got completely different impression specifically about tuples for the LDM discussion. It would be good to bring this specific scenario to LDM for confirmation. This issue doesn't block this PR though.

---
In reply to: [234384692](https://github.com/dotnet/roslyn/pull/31220#discussion_r234384692) [](ancestors = 234384692)
