### PR TITLE
Fix Local-Symbol Containing-Symbol in New-Extension-Method-Rewriter for Capture Analysis

### LINKED ISSUE #78042: Crash compiling extension static method
**Version Used**: 
5.0.0-1.25206.1

**Steps to Reproduce**:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>Preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="5.0.0-1.25207.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

```csharp
using System.Runtime.CompilerServices;

Console.WriteLine("Hello, World!");

namespace System.Linq
{
    public static partial class AsyncEnumerable
    {
        extension<TSource>(IAsyncEnumerable<TSource> source)
        {
            /// <summary>
            /// Casts the elements of an <see cref="IAsyncEnumerable{Object}"/> to the specified type.
            /// </summary>
            /// <typeparam name="TResult">The type to cast the elements of source to.</typeparam>
            /// <returns>An <see cref="IAsyncEnumerable{TResult}"/> that contains each element of the source sequence cast to the <typeparamref name="TResult"/> type.</returns>
            public IAsyncEnumerable<TResult> Cast<TResult>() // satisfies the C# query-expression pattern
            {
                return Impl(source, default);

                static async IAsyncEnumerable<TResult> Impl(
                    IAsyncEnumerable<TSource?> source,
                    [EnumeratorCancellation] CancellationToken cancellationToken)
                {
                    await foreach (object? item in source.WithCancellation(cancellationToken))
                    {
                        yield return (TResult)item!;
                    }
                }
            }
        }
    }
}
```

**Expected Behavior**:
Compiles

**Actual Behavior**:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Cci.MetadataWriter.CheckNameLength(String name, INamedEntity errorEntity)
   at Microsoft.Cci.MetadataWriter.PopulateFieldTableRows()
   at Microsoft.Cci.MetadataWriter.PopulateTypeSystemTables(Int32[] methodBodyOffsets, PooledBlobBuilder& mappedFieldDataWriter, PooledBlobBuilder& resourceWriter, BlobBuilder dynamicAnalysisData, Blob& mvidFixup)
   at Microsoft.Cci.MetadataWriter.BuildMetadataAndIL(PdbWriter nativePdbWriterOpt, BlobBuilder ilBuilder, PooledBlobBuilder& mappedFieldDataBuilder, PooledBlobBuilder& managedResourceDataBuilder, Blob& mvidFixup, Blob& mvidStringFixup)
   at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.SerializePeToStream(CommonPEModuleBuilder moduleBeingBuilt, DiagnosticBag metadataDiagnostics, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getMetadataPeStreamOpt, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, RebuildData rebuildData, Boolean metadataOnly, Boolean includePrivateMembers, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider metadataPEStreamProvider, EmitStreamProvider pdbStreamProvider, RebuildData rebuildData, Func`2 testSymWriterFactory, DiagnosticBag diagnostics, EmitOptions emitOptions, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 generators, ImmutableArray`1 additionalTextFiles, AnalyzerConfigSet analyzerConfigSet, ImmutableArray`1 sourceFileAnalyzerConfigOptions, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, ErrorLogger errorLogger, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, AnalyzerDriver& analyzerDriver, Nullable`1& generatorTimingInfo)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)
   at Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[T](Func`2 func)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter, String pipeName)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc, CompileOnServerFunc compileOnServerFunc, ICompilerServerLogger logger)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.MainCore(String[] args)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
```

### LINKED ISSUE #78135: C# 14 Preview 3 massive errors for nested functional extensions
C# 14 Preview 3 massive errors for nested functional extensions:
(Linux Mint 22.1, VS Code 1.99.2)

Playing around with extensions, I get tons of errors for: 

Program:
```c#
var sb =
        new StringBuilder("Info: ")
            .Snip    ( 1 )
            .Inspect ( c => Console.Write(c) );
``` 

Extension:
it compiles but will crash removing the foreach - comments below?!

```c#
namespace Extensions;

#nullable enable

public static class Test
{
    extension (StringBuilder sb)
    {
        //-------------------------------------------------------------------------

        public StringBuilder Snip (int n = 1)
        {
            var pos = sb.Length - int.Abs (n);

            if ( pos > 0 )
                sb.Remove (pos, n);

            return sb;
        }
        //-------------------------------------------------------------------------

        public StringBuilder Call (Action onCall)
        {
            onCall?.Invoke();
            return sb;
        }
        //-------------------------------------------------------------------------

        public StringBuilder Inspect (Action<char> onChar)
            =>
                sb.Call ( () =>
                {
                    // foreach (char c in sb.ToString())
                    //     onChar(c);
                });

        //-------------------------------------------------------------------------
    }
}
#nullable restore
``` 

```


    /home/user/.dotnet/sdk/10.0.100-preview.3.25201.16/Roslyn/Microsoft.CSharp.Core.targets(84,5): error : Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
    /home/user/.dotnet/sdk/10.0.100-preview.3.25201.16/Roslyn/Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataWriter.CheckNameLength(String name, INamedEntity errorEntity)
    /home/user/.dotnet/sdk/10.0.100-preview.3.25201.16/Roslyn/Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataWriter.PopulateFieldTableRows()
    /home/user/.dotnet/sdk/10.0.100-preview.3.25201.16/Roslyn/Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataWriter.PopulateTypeSystemTables(Int32[] methodBodyOffsets, PooledBlobBuilder& mappedFieldDataWriter, PooledBlobBuilder& resourceWriter, BlobBuilder dynamicAnalysisData, Blob& mvidFixup)
    /home/user/.dotnet/sdk/10.0.100-preview.3.25201.16/Roslyn/Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataWriter.BuildMetadataAndIL(PdbWriter nativePdbWriterOpt, BlobBuilder ilBuilder, PooledBlobBuilder& mappedFieldDataBuilder, PooledBlobBuilder& managedResourceDataBuilder, Blob& mvidFixup, Blob& mvidStringFixup)
    /home/user/.dotnet/sdk/10.0.100-preview.3.25201.16/Roslyn/Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
    /home/user/.dotnet/sdk/10.0.100-preview.3.25201.16/Roslyn/Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.Compilation.SerializePeToStream(CommonPEModuleBuilder moduleBeingBuilt, DiagnosticBag metadataDiagnostics, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getMetadataPeStreamOpt, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, RebuildData rebuildData, Boolean metadataOnly, Boolean includePrivateMembers, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
    /home/user/.dotnet/sdk/10.0.100-preview.3.25201.16/Roslyn/Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider metadataPEStreamProvider, EmitStreamProvider pdbStreamProvider, RebuildData rebuildData, Func`2 testSymWriterFactory, DiagnosticBag diagnostics, EmitOptions emitOptions, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
    /home/user/.dotnet/sdk/10.0.100-preview.3.25201.16/Roslyn/Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 generators, ImmutableArray`1 additionalTextFiles, AnalyzerConfigSet analyzerConfigSet, ImmutableArray`1 sourceFileAnalyzerConfigOptions, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, ErrorLogger errorLogger, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, AnalyzerDriver& analyzerDriver, Nullable`1& generatorTimingInfo)
    /home/user/.dotnet/sdk/10.0.100-preview.3.25201.16/Roslyn/Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
    /home/user/.dotnet/sdk/10.0.100-preview.3.25201.16/Roslyn/Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
    /home/user/.dotnet/sdk/10.0.100-preview.3.25201.16/Roslyn/Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
    /home/user/.dotnet/sdk/10.0.100-preview.3.25201.16/Roslyn/Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter, String pipeName)
    /home/user/.dotnet/sdk/10.0.100-preview.3.25201.16/Roslyn/Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc, CompileOnServerFunc compileOnServerFunc, ICompilerServerLogger logger)
    /home/user/.dotnet/sdk/10.0.100-preview.3.25201.16/Roslyn/Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.MainCore(String[] args)
    /home/user/.dotnet/sdk/10.0.100-preview.3.25201.16/Roslyn/Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)

Erstellen von fehlerhaft mit 16 Fehler(n) in 6,9s
```

### PR DESCRIPTION
**Pull request by bernd5**
fixes #78135
fixes #78042

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@bernd5 Please provide a more descriptive title for the PR, the title that reflects the nature of the changes

File: src/Compilers/CSharp/Portable/Lowering/BoundTreeToDifferentEnclosingContextRewriter.cs [hunk 1]
```diff
@@ -55,7 +57,7 @@ protected virtual bool TryRewriteLocal(LocalSymbol local, [NotNullWhen(true)] ou
             }
 
             var newType = VisitType(local.Type);
-            if (TypeSymbol.Equals(newType, local.Type, TypeCompareKind.ConsiderEverything2))
+            if (AllowReuseOfLocalsWithIncorrectContainingSymbol && TypeSymbol.Equals(newType, local.Type, TypeCompareKind.ConsiderEverything2))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/BoundTreeToDifferentEnclosingContextRewriter.cs:60]: >AllowReuseOfLocalsWithIncorrectContainingSymbol [](http://example.com/codeflow?start=16&length=47)

It feels like we should get into the `if` when type and container do not change

**Comment by AlekseyTs** [comment]
> Fix Local-Symbol Containing-Type in New-Extension-Method-Rewriter for Capture Analysis

"Containing-Type" or "Containing-Symbol"?

File: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs [hunk 2]
```diff
@@ -947,6 +947,49 @@ public static class Extensions
...
+            };
+            s();
+            return sb;
+        }
+    }
+}
+""";
+
+        var comp = CreateCompilation(src);
+        comp.VerifyEmitDiagnostics();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs:982]: >comp.VerifyEmitDiagnostics(); [](http://example.com/codeflow?start=8&length=29)

I think we would want to execute the code and observe that it works as expected.

File: src/Compilers/CSharp/Portable/Lowering/BoundTreeToDifferentEnclosingContextRewriter.cs [hunk 3]
```diff
@@ -30,6 +30,8 @@ internal abstract class BoundTreeToDifferentEnclosingContextRewriter : BoundTree
 
         protected abstract MethodSymbol CurrentMethod { get; }
 
+        protected virtual bool AllowReuseOfLocalsWithIncorrectContainingSymbol => true;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/BoundTreeToDifferentEnclosingContextRewriter.cs:33]: >AllowReuseOfLocalsWithIncorrectContainingSymbol [](http://example.com/codeflow?start=31&length=47)

"EnforceAccurateContainerForLocals"? This also inverts the meaning.

File: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs (hunk 2 above)
Comment (bernd5) [reply src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs:982]: Yeah that would be great - not sure how.
And we should may at a test where we can see that only captured locals are are hoisted to fields in display classes.

e.g. in code like:

```csharp
using System;
using System.Text;

int.Foo();

public static class Test
{
    extension(int)
    {
        public static void Foo()
        {
            var b = 123;
            Action a = () =>
            {
                int a = 123;
                Console.WriteLine(a);
                Console.WriteLine(b);
            };
        }
    }    
}
```

the compiler should generate only a field for `b` but not for `a`

**Comment by AlekseyTs** [comment]
Done with review pass (commit 5)

File: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs:982]: ```ComileAndVerify``` helper can be used to assert expected execution output.

> And we should may add a test where we can see that only captured locals are are hoisted to fields in display classes.

```VerifyTypeIL``` helper might help with that. However, when optimization level is DEBUG, all locals might be hoisted by design.

**Comment by bernd5** [comment]
I assume the faild tests have nothing todo with my change - some helix stuff 🤷

File: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs [hunk 4]
```diff
@@ -947,6 +947,1128 @@ public static class Extensions
...
+                        yield return (TResult)item!;
+                    }
+                }
+            }
+        }
+    }
+}
+""";
+
+        var comp = CreateCompilation(src, targetFramework: TargetFramework.Net90);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs:1316]: >targetFramework: TargetFramework.Net90 [](http://example.com/codeflow?start=42&length=38)

I think using explicit target framework is the source of the CI failure. You should be able to reproduce it locally if you run the test while targeting net472 environment. Consider removing this parameter. Otherwise, if this target framework is required, try specifying ```verify: Verification.FailsPEVerify``` as an argument for ```CompileAndVerify``` call below.

File: src/Compilers/CSharp/Portable/Lowering/BoundTreeToDifferentEnclosingContextRewriter.cs [hunk 5]
```diff
@@ -57,7 +59,22 @@ protected virtual bool TryRewriteLocal(LocalSymbol local, [NotNullWhen(true)] ou
             var newType = VisitType(local.Type);
             if (TypeSymbol.Equals(newType, local.Type, TypeCompareKind.ConsiderEverything2))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/BoundTreeToDifferentEnclosingContextRewriter.cs:60]: >if (TypeSymbol.Equals(newType, local.Type, TypeCompareKind.ConsiderEverything2)) [](http://example.com/codeflow?start=12&length=80)

It looks like the code could be simplified as follows:
```
            if (TypeSymbol.Equals(newType, local.Type, TypeCompareKind.ConsiderEverything2) &&
                (!EnforceAccurateContainerForLocals || local.ContainingSymbol == CurrentMethod))
            {
                newLocal = local;
            }
            else
            {
                newLocal = new TypeSubstitutedLocalSymbol(local, TypeWithAnnotations.Create(newType), CurrentMethod);
                localMap.Add(local, newLocal);
            }
```

File: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs [hunk 6]
```diff
@@ -947,6 +947,1128 @@ public static class Extensions
...
+using System;
+
+var a = int.Foo();
+a();
+
+public static class IntExt
+{
+    extension(int)
+    {
+        public static Action Foo()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs:1123]: >Foo [](http://example.com/codeflow?start=29&length=3)

This Identifier is flagged by a Policheck tool. Please use a "better" name.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs:1123]: The request is applicable to other places using this word

File: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs [hunk 7]
```diff
@@ -947,6 +947,1128 @@ public static class Extensions
...
+    public void ExtensionWithCapturing3()
+    {
+        var src = """
+using System.Runtime.CompilerServices;
+using System.Collections.Generic;
+using System;
+using System.Threading;
+using System.Threading.Tasks;
+
+Console.WriteLine("Hello, World!");
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs:1284]: What are we trying to verify by doing this?

File: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs [hunk 8]
```diff
@@ -947,6 +947,1128 @@ public static class Extensions
...
+
+namespace System.Linq
+{
+    public static partial class AsyncEnumerable
+    {
+        extension<TSource>(IAsyncEnumerable<TSource> source)
+        {
+            /// <summary>
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs:1292]: >/// <summary> [](http://example.com/codeflow?start=12&length=13)

Let's reduce the size of the string and remove all the comments that are not related to the issue we are testing.

File: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs [hunk 9]
```diff
@@ -947,6 +947,1128 @@ public static class Extensions
...
+}
+""";
+
+        var comp = CreateCompilation(src, targetFramework: TargetFramework.Net90);
+        var verifier = CompileAndVerify(comp, expectedOutput: """
+            Hello, World!
+
+            """, expectedReturnCode: 0, trimOutput: false);
+
+        VerifyTypeIL(verifier, "AsyncEnumerable",
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs:1322]: >VerifyTypeIL(verifier, "AsyncEnumerable", [](http://example.com/codeflow?start=8&length=41)

This base-line is quite long. Consider adding a comment describing the intent, i.e. what specific aspect we would like to verify. This is going to help to deal with situations when the IL is changed due to one reason or the other. 
Also, if we can focus on a nested type vs. the entire `AsyncEnumerable`, consider doing so.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 11)

**Comment by AlekseyTs** [comment]
@jcouv For the second review

File: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs (hunk 7 above)
Comment (bernd5) [reply src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs:1284]: This is the code from the other issue... (https://github.com/dotnet/roslyn/issues/78042)
We may just check local functions

File: src/Compilers/CSharp/Portable/Lowering/BoundTreeToDifferentEnclosingContextRewriter.cs (hunk 5 above)
Comment (bernd5) [reply src/Compilers/CSharp/Portable/Lowering/BoundTreeToDifferentEnclosingContextRewriter.cs:60]: Like jcouv said - I don't think `local.ContainingSymbol == CurrentMethod` is ever true. The whole class is about changing the enclosing context...

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/BoundTreeToDifferentEnclosingContextRewriter.cs:60]: > Like jcouv said - I don't think ```local.ContainingSymbol == CurrentMethod``` is ever true. The whole class is about changing the enclosing context...

Where did he say that? I only saw him asking you to explain the logic.

Second. This is a base class and you cannot really predict how it is going to be used in the future. Please explain why would we want to create new symbols when nothin about them is changing?

File: src/Compilers/CSharp/Portable/Lowering/BoundTreeToDifferentEnclosingContextRewriter.cs [hunk 10]
```diff
@@ -57,7 +59,22 @@ protected virtual bool TryRewriteLocal(LocalSymbol local, [NotNullWhen(true)] ou
...
             {
-                newLocal = local;
+                if (EnforceAccurateContainerForLocals)
+                {
+                    if (local.ContainingSymbol == CurrentMethod)
```
[the remark this answers is not in the document]
Comment (bernd5) [reply src/Compilers/CSharp/Portable/Lowering/BoundTreeToDifferentEnclosingContextRewriter.cs]: The Capture-Analysis compares the containing symbols to calculate which locals are captured. Without this check every local is analyzed as captured. The actual crash was caused by some synthesized locals which have no name...

[the remark this answers is not in the document]
Comment (jcouv) [reply src/Compilers/CSharp/Portable/Lowering/BoundTreeToDifferentEnclosingContextRewriter.cs]: Thanks. Aleksey walked me through:
1. the closure conversion is done on the tree rewritten by the extension body rewriter and it is sensitive to containing symbols (see link above)
2. the old behavior for all rewriters deriving from `BoundTreeToDifferentEnclosingContextRewriter` was to take a shortcut (re-use locals if the type didn't change)
3. for closure conversion to work well on a body rewritten by the extension body rewriter, the extension body rewriter should not take that shortcut

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 14)

File: src/Compilers/CSharp/Portable/Lowering/BoundTreeToDifferentEnclosingContextRewriter.cs (hunk 10 above)
[the remark this answers is not in the document]
Comment (bernd5) [reply src/Compilers/CSharp/Portable/Lowering/BoundTreeToDifferentEnclosingContextRewriter.cs]: Exactly!

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 15)

**Comment by AlekseyTs** [comment]
@bernd5 Thanks for the contribution!
