### PR TITLE
Adjust assert to account for error scenarios

### LINKED ISSUE #66046: Implicit field initialization analysis is firing an Assert
```
        [Fact]
        public void ImplicitlyInitializedField_()
        {
            var source = """
struct S1
{
    int F;

    S1(int x) {}

    public S1() : this(F) {}
}
""";
            var comp = CreateCompilation(source);
            comp.VerifyDiagnostics();
        }
```

Observed:
```
Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.StructConstructorTests.ImplicitlyInitializedField_ [FAIL]
  System.InvalidOperationException : Assertion failed
  Stack Trace:
    src\Compilers\Test\Core\ThrowingTraceListener.cs(26,0): at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
       at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage)
       at System.Diagnostics.Debug.Fail(String message, String detailMessage)
    src\Compilers\CSharp\Portable\FlowAnalysis\FlowAnalysisPass.cs(56,0): at Microsoft.CodeAnalysis.CSharp.FlowAnalysisPass.Rewrite(MethodSymbol method, BoundBlock block, TypeCompilationState compilationState, BindingDiagnosticBag diagnostics, Boolean hasTrailingExpression, Boolean originalBodyNested)
    src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs(1133,0): at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
    src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs(522,0): at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
    src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs(424,0): at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass25_0.<CompileNamedTypeAsync>b__0()
    src\Compilers\Core\Portable\InternalUtilities\UICultureUtilities.cs(139,0): at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0()
       at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location ---
       at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
    --- End of stack trace from previous location ---
    src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs(335,0): at Microsoft.CodeAnalysis.CSharp.MethodCompiler.WaitForWorkers()
    src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs(165,0): at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean emittingPdb, Boolean emitTestCoverageData, Boolean hasDeclarationErrors, Boolean emitMethodBodies, BindingDiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
    src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs(2775,0): at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForAllMethodBodies(BindingDiagnosticBag diagnostics, Boolean doLowering, CancellationToken cancellationToken)
    src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs(2746,0): at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsWithoutFiltering(CompilationStage stage, Boolean includeEarlierStages, BindingDiagnosticBag builder, CancellationToken cancellationToken)
    src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs(2657,0): at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, DiagnosticBag diagnostics, CancellationToken cancellationToken)
    src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs(2649,0): at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken)
    src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs(2643,0): at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CancellationToken cancellationToken)
    src\Compilers\Test\Core\Diagnostics\DiagnosticExtensions.cs(108,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyDiagnostics[TCompilation](TCompilation c, DiagnosticDescription[] expected)
    src\Compilers\CSharp\Test\Semantic\Semantics\StructConstructorTests.cs(4755,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.StructConstructorTests.ImplicitlyInitializedField_()
```

Shouldn't the analysis be even performed for a constructor with an initializer?

This issue is blocking some work in https://github.com/dotnet/roslyn/tree/features/PrimaryConstructors. I am going to disable the assert in that branch. Please keep the issue active until that assert is re-enabled.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Related to #66046

The effect of a constructor initializer is to prepend a statement to the effect of

```cs
S..ctor()
{
    S..otherCtor(out this, ...);
    // ... original constructor body statements
}
```

The point of this assert is that if a constructor initializer is present, it doesn't make sense for implicitly initialized fields to also be present, since you cannot access `this` until after the constructor initializer runs, which fully assigns `this`.

In error scenarios we can still end up referencing instance fields before the constructor initializer, so we relax the assert to allow the "unexpected" implicit initializations in this case.

Auto-default logic runs simply as a part of definite assignment analysis, so I think there is not a ton to be gained by skipping it when a constructor initializer is present. We could consider avoiding adding to the `implicitlyInitializedFields` when we notice a constructor initializer is present, but IMO this isn't necessary, and it's a little simpler to just adjust this assert to reflect our expectations. I'm open to discussion on this point, though.

In the future, if this assert fails, it means we are using an unassigned field before the constructor initializer has run in code without errors.

@AlekseyTs @dotnet/roslyn-compiler for review.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/StructConstructorTests.cs [hunk 1]
```diff
@@ -4091,6 +4091,48 @@ .maxstack  2
 ");
         }
 
+        [Fact]
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/StructConstructorTests.cs:4094]: nit: consider linking to issue

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 1)

**Review by cston — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@RikkiGibson As I mentioned in #66046: "Please keep the issue active until that assert is re-enabled."

**Comment by RikkiGibson** [comment]
@AlekseyTs Let me know if the adjusted assert seems reasonable to you. Thanks

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 3)
