### PR TITLE
Null coalescing assignment for nullable value type should set state of nullable type not underlying type

### LINKED ISSUE #67040: Assert compiling dotnet/runtime in NullableWalker
When compiling dotnet/runtime with the latest compiler in Debug we hit the following assert in the nullable walker (around line 7391). 

```
            Debug.Assert(false); // If this assert fails, add an appropriate test.
``` 

The line of code which is causing the assert is the following: 

https://github.com/dotnet/runtime/blob/f9ebd42d05ca88f086d472832487fbccfc7fe4ac/src/tools/illink/src/ILLink.Shared/TrimAnalysis/HandleCallAction.cs#L1166-L1168

Found while digging into https://github.com/dotnet/runtime/issues/82467

### PR DESCRIPTION
**Pull request by cston**
For a null coalescing assignment of a nullable value type, where the RHS is an instance of the underlying type, the nullable state of the LHS should be assigned a (non-null) nullable value type that wraps the state of the underlying value type from the RHS. Previously, the state of the LHS was set to the state from the RHS directly.

Fixes #67040

### CODE REVIEW

**Review by jjonescz — APPROVED** [review]

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 1]
```diff
@@ -5105,12 +5149,26 @@ private static BoundExpression SkipReferenceConversions(BoundExpression possibly
             var leftState = this.State.Clone();
             LearnFromNonNullTest(leftOperand, ref leftState);
             LearnFromNullTest(leftOperand, ref this.State);
+
+            // If we are assigning the underlying value type to a nullable value type variable,
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:5153]: I found this comment a little unclear. I think it should say that we do a special step to set the nullable variable's top level state within this block, then change the slot to later simulate an assignment from the RHS to the LHS's Value property, to update nullable states within the underlying value type.

**Review by RikkiGibson — APPROVED** [review]
