### PR TITLE
Fix analyzer action state tracking for partial analysis

### LINKED ISSUE #63205: Duplicate analyzer diagnostics from CompilationWithAnalyzers
Will be adding the following skipped test showing the failure:

```csharp
        [Fact]
        public async Task TestGetAnalysisResultWithFilterSpanAsync()
        {
            string source = @"
class B
{
    void M1()
    {
        int local1 = 1;
    }

    void M2()
    {
        int local2 = 1;
    }
}";

            var compilation = CreateCompilationWithMscorlib45(new[] { source });
            var tree = compilation.SyntaxTrees[0];
            var localDecl1 = tree.GetRoot().DescendantNodes().OfType<LocalDeclarationStatementSyntax>().First();
            var semanticModel = compilation.GetSemanticModel(tree);
            var analyzer1 = new VariableDeclarationAnalyzer("ID0001");
            var analyzer2 = new CSharpCompilerDiagnosticAnalyzer();
            var allAnalyzers = ImmutableArray.Create<DiagnosticAnalyzer>(analyzer1, analyzer2);
            var compilationWithAnalyzers = compilation.WithAnalyzers(allAnalyzers);

            // Invoke "GetAnalysisResultAsync" for a a sub-span and then
            // for the entire tree span and verify no duplicate diagnostics.

            var analysisResult = await compilationWithAnalyzers.GetAnalysisResultAsync(
                semanticModel,
                filterSpan: localDecl1.FullSpan,
                CancellationToken.None);

            var diagnostics1 = analysisResult.SemanticDiagnostics[tree][analyzer1];
            diagnostics1.Verify(
                Diagnostic("ID0001", "int local1 = 1").WithLocation(6, 9));

            var diagnostics2 = analysisResult.SemanticDiagnostics[tree][analyzer2];
            diagnostics2.Verify(
                // (6,13): warning CS0219: The variable 'local1' is assigned but its value is never used
                //         int local1 = 1;
                Diagnostic(ErrorCode.WRN_UnreferencedVarAssg, "local1").WithArguments("local1").WithLocation(6, 13));

            analysisResult = await compilationWithAnalyzers.GetAnalysisResultAsync(
                semanticModel,
                filterSpan: null,
                CancellationToken.None);

            diagnostics1 = analysisResult.SemanticDiagnostics[tree][analyzer1];
            diagnostics1.Verify(
                Diagnostic("ID0001", "int local1 = 1").WithLocation(6, 9),
                Diagnostic("ID0001", "int local2 = 1").WithLocation(11, 9));

            diagnostics2 = analysisResult.SemanticDiagnostics[tree][analyzer2];
            diagnostics2.Verify(
                // (6,13): warning CS0219: The variable 'local1' is assigned but its value is never used
                //         int local1 = 1;
                Diagnostic(ErrorCode.WRN_UnreferencedVarAssg, "local1").WithArguments("local1").WithLocation(6, 13),
                // (11,13): warning CS0219: The variable 'local2' is assigned but its value is never used
                //         int local2 = 1;
                Diagnostic(ErrorCode.WRN_UnreferencedVarAssg, "local2").WithArguments("local2").WithLocation(11, 13));
        }

        [DiagnosticAnalyzer(LanguageNames.CSharp)]
        public sealed class VariableDeclarationAnalyzer : DiagnosticAnalyzer
        {
            public VariableDeclarationAnalyzer(string diagnosticId)
            {
                Descriptor = new DiagnosticDescriptor(
                    diagnosticId,
                    "Title",
                    "Message",
                    "Category",
                    defaultSeverity: DiagnosticSeverity.Warning,
                    isEnabledByDefault: true);
            }

            public DiagnosticDescriptor Descriptor { get; }

            public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => ImmutableArray.Create(Descriptor);

            public override void Initialize(AnalysisContext context)
            {
                context.RegisterOperationAction(
                    context => context.ReportDiagnostic(Diagnostic.Create(Descriptor, context.Operation.Syntax.GetLocation())),
                    OperationKind.VariableDeclaration);
            }
        }
```

Failure on local execution:

```
Message: 

Expected:
    Diagnostic("ID0001", "int local1 = 1").WithLocation(6, 9),
    Diagnostic("ID0001", "int local2 = 1").WithLocation(11, 9)
Actual:
    Diagnostic("ID0001", "int local1 = 1").WithLocation(6, 9),
    Diagnostic("ID0001", "int local1 = 1").WithLocation(6, 9),
    Diagnostic("ID0001", "int local2 = 1").WithLocation(11, 9)
Diff:
++>     Diagnostic("ID0001", "int local1 = 1").WithLocation(6, 9)
Expected: True
Actual:   False
```

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #63205

While executing analyzers for a tree sub-span on CompilationWithAnalyzers, we were not adding to the set of processed nodes/operations after all the actions have been executed for it. This meant that all actions would be re-executed for this node/operation when analyzer diagnostics are subsequently queried on the same CompilationWithAnalyzers instance.

### CODE REVIEW

**Review by 333fred — APPROVED** [review]

**Comment by 333fred** [comment]
@dotnet/roslyn-compiler for a second review.

File: src/Compilers/CSharp/Test/Emit2/Diagnostics/DiagnosticAnalyzerTests.cs [hunk 1]
```diff
@@ -3570,6 +3570,70 @@ class C
...
+    {
+        int local2 = 1;
+    }
+}";
+
+            var compilation = CreateCompilationWithMscorlib45(new[] { source });
+            var tree = compilation.SyntaxTrees[0];
+            var localDecl1 = tree.GetRoot().DescendantNodes().OfType<LocalDeclarationStatementSyntax>().First();
+            var semanticModel = compilation.GetSemanticModel(tree);
+            var analyzer1 = new VariableDeclarationAnalyzer("ID0001");
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Emit2/Diagnostics/DiagnosticAnalyzerTests.cs:3594]: nit: consider also testing a case which uses a syntax analyzer.

**Review by RikkiGibson — APPROVED** [review]

File: src/Compilers/CSharp/Test/Emit2/Diagnostics/DiagnosticAnalyzerTests.cs (hunk 1 above)
Comment (mavasani) [reply src/Compilers/CSharp/Test/Emit2/Diagnostics/DiagnosticAnalyzerTests.cs]: Thanks, addressed with https://github.com/dotnet/roslyn/pull/63206/commits/764176e5e20b9fa020c112a0bd3d8a89693e8760
