### PR TITLE
Give errors on implicit conversions to 'void'

### LINKED ISSUE #40405: Roslyn doesn't detect error and generates a C7038 error: Failed to emit module
**Version Used**: 
SDK Version: 3.1.100
Windows 10 pro 1909

**Steps to Reproduce**:
1- Use the following code

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
```
```
using System;
namespace console1 {
    class ConcreteClass    {
        private ConcreteClass _next;
        public void Foo()   {
            return _next == null ? throw new NotImplementedException() : _next.Foo();
        }
    }
    class Program     {
        static void Main(string[] args)        {
        }
    }
}
```

2- dotnet build

**Expected Behavior**:
Error : CS0127	Since 'ConcreteClass.Foo()' returns void, a return keyword must not be followed by an object expression

**Actual Behavior**:
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 110,44 ms for ...\console1.csproj.
CSC : error CS7038: Failed to emit module 'console1'. [...\console1.csproj]
Program.cs(11,31): warning CS0649: Field 'ConcreteClass._next' is never assigned to, and will always have its default value null [...\console1.csproj]

Build FAILED.

Program.cs(11,31): warning CS0649: Field 'ConcreteClass._next' is never assigned to, and will always have its default value null [...\console1.csproj]
CSC : error CS7038: Failed to emit module 'console1'. [...\console1.csproj]
    1 Warning(s)
    1 Error(s)

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #40405

Any additional test case ideas would be appreciated--think unusual or new language features where we might accidentally let you convert something to 'void'.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs [hunk 1]
```diff
@@ -1486,6 +1486,106 @@ public static void Main()
...
+    {
+        object obj = true ? M2() : M2();
+    }
+
+    void M2() { }
+}
+";
+            CreateCompilation(text).VerifyDiagnostics(
+                // (6,22): error CS0029: Cannot implicitly convert type 'void' to 'object'
+                //         object obj = true ? M2() : M2();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs]: >true ? M2() : M2(); [](start = 40, length = 19)

Please add a test for ```_ = true ? M2() : M2();``` and for ```object x  = M2()```.
