### PR TITLE
Consider nullability in conversion to constraint type

### LINKED ISSUE #46150: No warning reported returning nullable version of unconstrained type parameter
A warning should be reported for the return value:
```C#
#nullable enable

class Program
{
    static T F<T, U>(U u) where U : T?
    {
        return u; // warning?
    }
}
```

### LINKED ISSUE #46410: Type argument nullability warning no longer reported for type parameter constrained to 'int?'
A warning should be reported for `M<T>(t)` since `T` is constrained to `int?` which does not satisfy the `notnull` constraint.
```C#
#nullable enable
abstract class A<T, U> where T : notnull
{
    internal static void M<V>(V v) where V : T { }
    internal abstract void F<V>(V v) where V : U;
}
class B : A<System.ValueType, int?>
{
    internal override void F<T>(T t)
    {
        M<T>(t);
    }
}
```
This may be a regression from https://github.com/dotnet/roslyn/pull/45993. Earlier builds reported:
```
(11,9): warning CS8631: The type 'T' cannot be used as type parameter 'V' in the generic type or method
    'A<ValueType, int?>.M<V>(V)'. Nullability of type argument 'T' doesn't match constraint type 'System.ValueType'.
```

### PR DESCRIPTION
**Pull request by cston**
Fixes #46150
Fixes #46410

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 1]
```diff
@@ -133388,26 +133867,36 @@ public void LambdaNullReturn_03()
...
+            await Task.Yield();
             if (t is null) return null;
             return t;
         });
     }
 }";
-            var comp = CreateCompilation(source);
+            var comp = CreateCompilation(source, parseOptions: TestOptions.RegularPreview);
             comp.VerifyEmitDiagnostics();
         }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:133897]: The only changes in `LambdaNullReturn_01` to `_06` is that each pair of tests have been combined. Two new tests `04` and `_05` were added at the end. (There were already too many similar tests and adding 4 news tests rather than combining pairs would have made the situation worse.)

**Comment by cston** [comment]
@dotnet/roslyn-compiler please review.

**Comment by cston** [comment]
@dotnet/roslyn-compiler please review.

**Comment by cston** [comment]
@dotnet/roslyn-compiler please review.

**Comment by 333fred** [comment]
Looking

File: src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs [hunk 2]
```diff
@@ -1015,7 +1015,7 @@ static NullableFlowState getTypeArgumentState(in TypeWithAnnotations typeWithAnn
                     }
                     else
                     {
-                        result = (NullableFlowState)Math.Min((int)result.Value, (int)constraintState);
+                        result = result.Value.Meet(constraintState);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs:1018]: Just to confirm: this is functionally equivalent, just a clean up, right?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 3]
```diff
@@ -6474,9 +6483,25 @@ static NullableFlowState getReferenceConversionResultState(TypeWithAnnotations t
             // Converting to a less-derived type (object, interface, type parameter).
             // If the operand is MaybeNull or MaybeDefault, the result should be
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:6484]: Is the comment still accurate? I'm having trouble mapping it to the logic below.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 4]
```diff
@@ -6497,13 +6522,38 @@ static NullableFlowState getConversionResultState(TypeWithState operandType)
...
                 {
-                    var type = operandType.Type;
-                    if (type is null || !type.IsTypeParameterDisallowingAnnotationInCSharp8())
+                    return NullableFlowState.MaybeDefault;
+                }
+                return state;
+            }
+
+            // If type parameter 1 depends on type parameter 2,
+            // returns the corresponding annotation.
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:6531]: what does "corresponding annotation" mean?

File: src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs (hunk 2 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs:1018]: Yes, this is equivalent. This was follow up from an earlier PR.

---
In reply to: [466656042](https://github.com/dotnet/roslyn/pull/46405#discussion_r466656042) [](ancestors = 466656042)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 5]
```diff
@@ -6474,9 +6483,25 @@ static NullableFlowState getReferenceConversionResultState(TypeWithAnnotations t
...
+                {
+                    var type = operandType.Type;
+                    if (type is null || !type.IsTypeParameterDisallowingAnnotationInCSharp8())
+                    {
+                        return NullableFlowState.MaybeDefault;
+                    }
+                    else if (targetType.NullableAnnotation.IsNotAnnotated() &&
+                        type is TypeParameterSymbol typeParameter1 &&
+                        targetType.Type is TypeParameterSymbol typeParameter2 &&
+                        dependsOnTypeParameter(typeParameter1, typeParameter2, NullableAnnotation.NotAnnotated, out var annotation))
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:6499]: Can `dependsOnTypeParameter` ever return false here (and above in `getReferenceConversionResultState`)?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 6]
```diff
@@ -6455,10 +6455,19 @@ static NullableFlowState getReferenceConversionResultState(TypeWithAnnotations t
                 switch (state)
                 {
                     case NullableFlowState.MaybeNull:
-                        if (operandType.Type?.IsTypeParameterDisallowingAnnotationInCSharp8() != true &&
-                            targetType.Type?.IsTypeParameterDisallowingAnnotationInCSharp8() == true)
+                        if (targetType.Type?.IsTypeParameterDisallowingAnnotationInCSharp8() == true)
                         {
-                            return NullableFlowState.MaybeDefault;
+                            var type = operandType.Type;
+                            if (type?.IsTypeParameterDisallowingAnnotationInCSharp8() != true)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:6461]: nit: consider aligning with next local function `if (type is null || !type.IsTypeParameterDisallowingAnnotationInCSharp8())`

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 7]
```diff
@@ -6455,10 +6455,19 @@ static NullableFlowState getReferenceConversionResultState(TypeWithAnnotations t
...
+                            {
+                                return NullableFlowState.MaybeDefault;
+                            }
+                            else if (targetType.NullableAnnotation.IsNotAnnotated() &&
+                                type is TypeParameterSymbol typeParameter1 &&
+                                dependsOnTypeParameter(typeParameter1, (TypeParameterSymbol)targetType.Type, NullableAnnotation.NotAnnotated, out var annotation))
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:6467]: can this cast fail? consider doing `targetType.Type is TypeParameterSymbol typeParameter2 &&` as in the following local function

Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:6467]: The cast cannot fail since we've checked `IsTypeParameterDisallowingAnnotationInCSharp8()` above.

---
In reply to: [466687268](https://github.com/dotnet/roslyn/pull/46405#discussion_r466687268) [](ancestors = 466687268)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 8]
```diff
@@ -132347,20 +132375,385 @@ class A<T> where T : class?
...
+            var source2 =
+@"#nullable enable
+class A
+{
+    static object F1<T>(T t) where T : class => t;
+    static object? F2<T>(T t) where T : class => t;
+    static object F3<T>(T? t) where T : class => t; // 1
+    static object? F4<T>(T? t) where T : class => t;
+}";
+            comp = CreateCompilation(source2, parseOptions: TestOptions.RegularPreview);
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:132544]: is the language version relevant? If not, consider using C# 8. 
Also applicable to other scenarios in this test.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 5 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:6499]: The `dependsOnTypeParameter()` check can fail in `getReferenceConversionResultState()`, with the following for instance (see `NullabilityOfTypeParameters_171()`):
```C#
#nullable enable
class C
{
    static U F<T, U>(T t)
        where T : C?
        where U : T
    {
        return (U)t;
    }
}
```
I suspect the check here in `getBoxingConversionResultState()` cannot fail, because both the target type and the operand type must be unconstrained type parameters, and we only create boxing conversions for those cases when there is an implicit conversion from operand to target type which requires checking the constraint types.

---
In reply to: [466677704](https://github.com/dotnet/roslyn/pull/46405#discussion_r466677704) [](ancestors = 466677704)
