### PR TITLE
Fix data flow analysis for using variables

### LINKED ISSUE #9581: A missing definite assignment error for a 'using' local.
```
class C
{
    static void Main()
    {
        using (System.IDisposable x = x)
        {
        }
    }
}
```

Observed:
No errors or warnings.

Expected (VS2013 behavior):
```
(5,35): warning CS1717: Assignment made to same variable; did you mean to assign something else?
(5,39): error CS0165: Use of unassigned local variable 'x'
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #9581

@dotnet/roslyn-compiler Please review.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 1]
```diff
@@ -1630,16 +1630,6 @@ public override BoundNode VisitUsingStatement(BoundUsingStatement node)
...
-                        if (slot >= 0)
-                        {
-                            SetSlotAssigned(slot);
-                            NoteWrite(local, value: null, read: true);
-                        }
-                        else
-                        {
-                            Debug.Assert(_emptyStructTypeCache.IsEmptyStructType(local.Type));
-                        }
                         break;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: Perhaps change from assert to:
```
case LocalDeclarationKind.UsingVariable:
    break;
default:
    throw ExceptionUtilities.UnexpectedValue(kind);
```

Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: Perhaps change from assert to:
```
case LocalDeclarationKind.UsingVariable:
    break;
default:
    throw ExceptionUtilities.UnexpectedValue(kind);
```

Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: Perhaps change from assert to:
```
case LocalDeclarationKind.UsingVariable:
    break;
default:
    throw ExceptionUtilities.UnexpectedValue(kind);
```

**Comment by cston** [comment]
LGTM

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 2]
```diff
@@ -1630,16 +1630,6 @@ public override BoundNode VisitUsingStatement(BoundUsingStatement node)
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: I can't comment on the actual line, but why not call `base.VisitUsingStatement` unconditionally? And shouldn't the treatment for BoundLocalDeclarations do the same thing for all declaration kinds? Is there some reason to special case this in the `using` visitor?

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 3]
```diff
@@ -1630,16 +1630,6 @@ public override BoundNode VisitUsingStatement(BoundUsingStatement node)
 
                     default:
                         Debug.Assert(local.DeclarationKind == LocalDeclarationKind.UsingVariable);
-                        int slot = GetOrCreateSlot(local);
-                        if (slot >= 0)
-                        {
-                            SetSlotAssigned(slot);
-                            NoteWrite(local, value: null, read: true);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: Where is this done now?

File: src/Compilers/CSharp/Test/Semantic/FlowAnalysis/FlowDiagnosticTests.cs [hunk 4]
```diff
@@ -2457,5 +2457,50 @@ public static void Main()
...
+{
+    static void Main()
+    {
+        using (System.IDisposable x = x)
+        {
+        }
+    }
+}";
+            CSharpCompilation comp = CreateCompilationWithMscorlib(source);
+            comp.VerifyDiagnostics(
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/FlowAnalysis/FlowDiagnosticTests.cs]: Are we no longer reporting CS1717 for cases like this?

File: src/Compilers/CSharp/Test/Semantic/FlowAnalysis/FlowDiagnosticTests.cs [hunk 5]
```diff
@@ -2457,5 +2457,50 @@ public static void Main()
...
+        [WorkItem(9581, "https://github.com/dotnet/roslyn/issues/9581")]
+        [Fact]
+        public void UsingSelfAssignment()
+        {
+            var source =
+@"class Program
+{
+    static void Main()
+    {
+        using (System.IDisposable x = x)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/FlowAnalysis/FlowDiagnosticTests.cs]: Consider adding a test with 'var' as the type.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: Reasonable, but I would prefer not to do it in only one place where this pattern occurs. So I'm not going to do it in this PR.

---
In reply to: [78840194](https://github.com/dotnet/roslyn/pull/13807#discussion_r78840194) [](ancestors = 78840194)

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: This has grown in complexity over time. It used to be a simple assertion that the locals were all using variables. But now out variables and pattern variables can occur here too, and out variables were designed in a way that makes them indistinguishable from other locals. Since they are declared here, we need to allocate slots for them. We don't actually need the switch except to support the assertion.

The "conditional" call to base.Visit... is just a shorthand way of skipping the following foreach loop... and the one after that. It could also be done as an if statement around them, but that seemed slightly more clumsy.

---
In reply to: [78859460](https://github.com/dotnet/roslyn/pull/13807#discussion_r78859460) [](ancestors = 78859460)

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs (hunk 3 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: It is done when we visit the variable declaration inside the using.

---
In reply to: [79029103](https://github.com/dotnet/roslyn/pull/13807#discussion_r79029103) [](ancestors = 79029103)

File: src/Compilers/CSharp/Test/Semantic/FlowAnalysis/FlowDiagnosticTests.cs (hunk 4 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/FlowAnalysis/FlowDiagnosticTests.cs]: CS1717 is used in Roslyn for the assignment operator and field declarations, but not for local declarations. For local declarations it would be a cascaded diagnostic, as there is always a definite assignment error.

---
In reply to: [79029925](https://github.com/dotnet/roslyn/pull/13807#discussion_r79029925) [](ancestors = 79029925)

File: src/Compilers/CSharp/Test/Semantic/FlowAnalysis/FlowDiagnosticTests.cs (hunk 5 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/FlowAnalysis/FlowDiagnosticTests.cs]: Sure, but that won't trigger any of the changed code. That would be a test of the local inference machinery.

---
In reply to: [79030042](https://github.com/dotnet/roslyn/pull/13807#discussion_r79030042) [](ancestors = 79030042)

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: I'd prefer to strengthen the assert to say that only pattern and out variables can appear here, but the current implementation of out variables does not provide any way to distinguish them from other locals.
