### PR TITLE
Permit array of pointer type to be parsed wherever an array type is permitted

### LINKED ISSUE #23100: The C# compiler failed to compile "obj is byte*[]" form
**Version Used**: 
Visual Studio 2017
C#7.1
.NET Framework 4.7

**Steps to Reproduce**:

1. Try to compile this code:
```C#
namespace Test
{
    static unsafe class Program
    {
        static void Main()
        {
            object obj = new byte*[10];
            bool b = obj is byte*[];
        }
    }
}
```

**Expected Behavior**:
Compile success.

**Actual Behavior**:
Program.cs(8,20,8,24): error CS1525: Invalid expression term 'byte'
Program.cs(8,25,8,26): error CS1525: Invalid expression term '['
Program.cs(8,26,8,27): error CS0443: Syntax error; value expected

### PR DESCRIPTION
**Pull request by gafter**
**Customer scenario**

Use the `is` operator to test an expression to see if it is an array of some pointer type. This used to work in earlier compilers, but now produces a syntax error.

**Bugs this fixes:**

Fixes #23100

**Workarounds, if any**

None.

**Risk**

Very low. The fix is focused on the problematic scenarios.

**Performance impact**

None expected, as the change does only a tiny bit more work in unusual circumstances.

**Is this a regression from a previous update?**

No, but it is a regression from C# 6.

**Root cause analysis:**

The introduction of pattern-matching changed the way types are parsed. As a consequence, certain type syntax forms that were previously permitted were unintentionally forbidden by the change.

Generally speaking, we do not permit pointer types to be parsed in certain contexts that require a managed type. These contexts include an is-expression type test, pattern-matching scenarios and tuples. The parser was modified to forbid pointer specifiers in these contexts. However, an array of a pointer type is a managed type and should have been permitted. This bug fix permits parsing arrays of pointer types in these contexts even though pointer types themselves are not permitted. 

**How was the bug found?**

Customer-reported.

**Test documentation updated?**

N/A

@jcouv This affects tuple parsing. Could you please review, particularly the deconstruction test changes?
@agocke Please review.
@pdelvo I would love your feedback, please.

### CODE REVIEW

**Comment by gafter** [comment]
@CyrusNajmabadi The restriction allows us to continue treating `A*B` as a multiplication inside a tuple instead of a declaration of `B`.

**Comment by gafter** [comment]
test windows_release_unit64_prtest please

**Comment by gafter** [comment]
test windows_release_unit64_prtest please

**Comment by gafter** [comment]
test windows_release_unit64_prtest please

**Comment by gafter** [comment]
test windows_release_vs-integration_prtest please

**Comment by gafter** [comment]
test windows_debug_vs-integration_prtest please

**Comment by gafter** [comment]
@jcouv Could you review this change please?
/cc @dotnet/roslyn-compiler

**Comment by gafter** [comment]
test windows_release_vs-integration_prtest please

**Comment by gafter** [comment]
test windows_release_vs-integration_prtest please

**Comment by gafter** [comment]
test windows_debug_vs-integration_prtest please

File: src/Compilers/CSharp/Test/Syntax/Parsing/ParsingTests.cs [hunk 1]
```diff
@@ -1,6 +1,6 @@
 ﻿// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
 
-// #define PARSING_TESTS_DUMP
+//#define PARSING_TESTS_DUMP
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Syntax/Parsing/ParsingTests.cs]: This is the only change in this file. Consider reverting it to the previous state

Comment (gafter) [reply src/Compilers/CSharp/Test/Syntax/Parsing/ParsingTests.cs]: This is actually intentional, so that the file corresponds to what VS produces when you uncomment-line and then comment-line it.
