### PR TITLE
Guard against null reference in AddImports

### LINKED ISSUE #794: NRE at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider.<GetNamespacesForMatchingExtensionMethodsAsync>
Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider.<GetNamespacesForMatchingExtensionMethodsAsync>d__20.MoveNext() in C:\Roslyn\Open\src\Features\Core\CodeFixes\AddImport\AbstractAddImportCodeFixProvider.cs:line 240
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.CodeFixes.AddImport.AbstractAddImportCodeFixProvider.<RegisterCodeFixesAsync>d__15.MoveNext() in C:\Roslyn\Open\src\Features\Core\CodeFixes\AddImport\AbstractAddImportCodeFixProvider.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.<PerformActionAsync>d__2.MoveNext()

### PR DESCRIPTION
**Pull request by jmarolf**
Previously we weren't properly guarding against null reference exceptions when the symbol we try to add Imports/usings for binds correctly.

Fixes #794

### CODE REVIEW

**Comment by jmarolf** [comment]
@srivatsn @tmeschter @shyamnamboodiripad @mavasani @heejaechang @JohnHamby Could you take a look, please?

**Comment by heejaechang** [comment]
:+1:

**Comment by shyamnamboodiripad** [comment]
:+1:

File: src/Features/Core/CodeFixes/AddImport/AbstractAddImportCodeFixProvider.cs [hunk 1]
```diff
@@ -237,9 +237,14 @@ private IEnumerable<INamespaceSymbol> GetNamespacesForMatchingTypesAsync(Semanti
 
             var expression = node.Parent;
 
-            var symbols = await GetSymbolsAsync(project, diagnostic, node, semanticModel, syntaxFacts, cancellationToken).ConfigureAwait(false);
+            var symbols = await GetSymbolsAsync(project, node, semanticModel, syntaxFacts, cancellationToken).ConfigureAwait(false);
 
-            return FilterForExtensionMethods(semanticModel, namespacesInScope, syntaxFacts, expression, symbols, cancellationToken);
+            if (symbols != null)
```
Comment (JohnHamby) [inline src/Features/Core/CodeFixes/AddImport/AbstractAddImportCodeFixProvider.cs]: The code could be more compact and arguably no less readable with a ?: operator.

**Comment by JohnHamby** [comment]
I sign off.
