### PR TITLE
Fix DeclaredInside for expression variables and deconstruction

### LINKED ISSUE #12940: Missing bound node for out variable declaration
We have a design invariant for the bound nodes that the initial bound tree is roughly isomorphic to the shape of the syntax. We create and retain bound nodes even when they do not represent runtime operations, e.g. local variable declarations.

The out variable declaration is not retained in the initial bound trees. It should be. This would slightly simplify the handling of the diagnostic reporting it being unsupported in expression trees, for example, and would simplify the handling of some error cases in flow analysis. It is necessary for region analysis to compute the "declared inside" property.

### LINKED ISSUE #14110: DataFlowAnalysis.VariablesDeclared does not handle deconstruction declarations
The following proposed unit test fails.

``` cs
        [Fact, WorkItem(14110, "https://github.com/dotnet/roslyn/issues/14110")]
        public void Test14110()
        {
            var dataFlowAnalysisResults = CompileAndAnalyzeDataFlowStatements(@"
using System;

class Program
{
    static void Main()
    {
/*<bind>*/
        var (x, y) = (1, 2);
        (var a, var b) = (3, 4);
/*</bind>*/
        Console.WriteLine(x + a);
    }
}
");
            Assert.Equal("a, b, x, y", GetSymbolNamesJoined(dataFlowAnalysisResults.VariablesDeclared));
        }
```

One symptom of this is #14108.

### LINKED ISSUE #15640: NullReferenceException in DeclaredInside for deconstruction foreach loop
The following test fails with a `NullReferenceException`.

```cs
        [Fact, WorkItem(15640, "https://github.com/dotnet/roslyn/issues/15640")]
        public void Test15640()
        {
            var dataFlowAnalysisResults = CompileAndAnalyzeDataFlowStatements(@"
using System;

class Program
{
    static void Main()
    {
/*<bind>*/
        foreach (var (a, b) in new[] { (1, 2) }) {}
/*</bind>*/
    }
}
");
            Assert.Equal("a, b", GetSymbolNamesJoined(dataFlowAnalysisResults.VariablesDeclared));
        }
```

### PR DESCRIPTION
**Pull request by gafter**
@dotnet/roslyn-compiler Please review.

**Customer scenario**

`DeclaredInside` is used for extract method, so the bugs fixed here result in incorrect behavior for that IDE feature. Also, it fixes a `NullReferenceException` that would result in an IDE crash when extract method is used in some circumstances.

**Bugs this fixes:** 

Fixes #12940
Fixes #14110
Fixes #15640

**Workarounds, if any**

Don't use extract method (or any other IDE features that use `DeclaredInside`).

**Risk**

Fairly low; the changes are localized to the affected scenarios, and significantly simplify the implementation.

**Performance impact**

Small. Slightly larger node for `BoundLocal`, which is transiently used during semantic analysis and in the `SemanticModel`

**Is this a regression from a previous update?**

No. The bugs have been present as long as the feature implementations have been in the code base.

**Root cause analysis:**

Implementing this API for expression variables has been a known laggard in the implementation of the new features. Because it wasn't implemented, it also wasn't tested. This PR adds tests for the affected scenarios.

**How was the bug found?**

Ad-hoc and unit testing while completing the feature.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/FlowAnalysis/VariablesDeclaredWalker.cs [hunk 1]
```diff
@@ -122,17 +122,26 @@ public override BoundNode VisitLocalFunctionStatement(BoundLocalFunctionStatemen
...
             {
-                _variablesDeclared.Add(node.IterationVariableOpt);
-            }
+                if (node.IterationVariableOpt != null)
+                {
+                    _variablesDeclared.Add(node.IterationVariableOpt);
+                }
 
-            return base.VisitForEachStatement(node);
+                var leftVariables = node.DeconstructionOpt?.DeconstructionAssignment?.LeftVariables;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/VariablesDeclaredWalker.cs]: Consider adding `.GetValueOrDefault()` here rather than twice below.

**Comment by cston** [comment]
LGTM

**Comment by gafter** [comment]
@dotnet/roslyn-compiler One more review, please.

**Comment by gafter** [comment]
@dotnet/roslyn-compiler There are no unaddressed comments. One more review, please.

**Comment by AlekseyTs** [comment]
LGTM

**Comment by gafter** [comment]
@MattGertz May I have an ask-mode approval please?
