### PR TITLE
Suggestion after comparison operators in is pattern matching

### LINKED ISSUE #58890: Nothing is suggested after entering comparison operators in `is` pattern matching
**Version Used**: 
Visual Studio 2022 Community
Version 17.1.0 Preview 1.1

**Steps to Reproduce**:

1. Begin an `is` pattern matching expression, using one of the 4 comparison operators (e.g. `is > `)
2. Pay attention to the suggestions

**Expected Behavior**:
Constant symbols, types and namespaces are suggested and available to autocomplete

**Actual Behavior**:
Nothing pops up for autocompletion or suggestion. Additionally, adding an extra whitespace and deleting it, bringing the cursor back to next to the comparison operator, the suggestions are `and` and `or`.

**Additional Information**:
- The same applies with having a `not`, `and` or `or` right before the comparison operator.
- Qualifying the member of a type will bring back suggestions normally. For instance, having entered `is > int.` will suggest members of the `int` type.

**Screenshots**:
Suggestions after deleting the extra whitespace next to the comparison operator:
image

### PR DESCRIPTION
**Pull request by maciek231**
Fix #58890

### CODE REVIEW

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs [hunk 1]
```diff
@@ -1389,6 +1389,16 @@ public static bool IsAtStartOfPattern(this SyntaxTree syntaxTree, SyntaxToken le
                 return true;
             }
 
+            // e is > $$
+            // e is >= $$
+            // e is < $$
+            // e is <= $$
+            if (leftToken.IsKind(SyntaxKind.GreaterThanToken, SyntaxKind.GreaterThanEqualsToken, SyntaxKind.LessThanToken, SyntaxKind.LessThanEqualsToken) &&
+                leftToken.Parent.IsKind(SyntaxKind.RelationalPattern))
```
Comment (DoctorKrolic) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs:1397]: I believe there is an existing `IsParentKind` method for `SyntaxToken`s. So you can just do `leftToken.IsParentKind(SyntaxKind.RelationalPattern)`

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs [hunk 2]
```diff
@@ -2328,6 +2329,16 @@ private IEnumerable<TypeInferenceInfo> InferTypeInWhileStatement(WhileStatementS
...
+
+            private IEnumerable<TypeInferenceInfo> InferTypeInRelationalPattern(RelationalPatternSyntax relationalPattern)
+            {
+                if (relationalPattern.Parent is IsPatternExpressionSyntax isPatternExpression)
+                {
+                    return InferTypeInIsPatternExpression(isPatternExpression, relationalPattern);
+                }
+
+                return SpecializedCollections.EmptyEnumerable<TypeInferenceInfo>();
+            }
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs:2341]:
```suggestion
            private IEnumerable<TypeInferenceInfo> InferTypeInRelationalPattern(RelationalPatternSyntax relationalPattern)
                => InferTypes(relationalPattern);
```

I think this will work just as well and fit the general idea of this type (Which is walking up to find the right inference point).

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs (hunk 1 above)
Comment (maciek231) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs:1397]: There is ```IsParentKind``` extension method, but only for ```SyntaxNode```

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs (hunk 2 above)
Comment (maciek231) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs]: Yes, you're right. It's working.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks!
