### PR TITLE
Make DiagnosticDescriptor completely exception safe (fixes #887)

### LINKED ISSUE #887: Handle exceptions from public abstract methods of LocalizableString
Following methods of LocalizableString: ToString(formatProvider), Equals and GetHashCode are abstract and can throw exceptions. DiagnosticDescriptor constructor takes localizable arguments for Title, MessageFormat and Description, but these are not converted to string until they are actually consumed by the host to report diagnostics. Hence these exceptions can escape the try/catch around analyzer callbacks.
We recently fixed the command line compiler to catch all exceptions from diagnostic formatter. We need to do the same for all places in IDE that can invoke any of these methods on a LocalizableString.

### PR DESCRIPTION
**Pull request by mavasani**
This is the final change in the series of changes I have been making to ensure that compiler and IDE are completely hardened against exceptions from analyzers.

This change makes the DiagnosticDescriptor completely exception safe. DiagnosticDescriptor has lazily evaluated LocalizableString fields for Title, MessageFormat and Description. These have public extension points at ToString, Equals and GetHashCode methods, all of which can throw. These callbacks have now been wrapped within a try-catch for our LocalizableResourceString implementation of LocalizableString. For custom user implementations of LocalizableString (which should hopefully be rare), we wrap these within an ExceptionSafeLocalizableString which calls into the inner localizable string wrapped within a try-catch. All this is done within the DiagnosticDescriptor constructor, so none of the clients have to explicitly handle the exception at use sites.

@srivatsn @tmeschter @JohnHamby @shyamnamboodiripad @heejaechang @jmarolf can you please review?

### CODE REVIEW

File: src/Compilers/Core/Portable/Diagnostic/LocalizableString.cs [hunk 1]
```diff
@@ -45,29 +43,61 @@ public override bool Equals(object other)
...
             {
-                var fixedStr = other as FixedLocalizableString;
-                return fixedStr != null && string.Equals(_fixedString, fixedStr.ToString());
+                onLocalizableStringException?.Invoke(ex);
+                return defaulValueOnException;
             }
+        }
 
-            public override int GetHashCode()
+        internal static T ExecuteAndCatchIfThrows<U, T>(Func<U, T> action, U argument, T defaulValueOnException, Action<Exception> onLocalizableStringException)
```
Comment (heejaechang) [inline src/Compilers/Core/Portable/Diagnostic/LocalizableString.cs]: don't you have this on some other thing as well? this should be just a generic helper thing.

File: src/Compilers/Core/Portable/Diagnostic/LocalizableString.cs [hunk 2]
```diff
@@ -45,29 +43,61 @@ public override bool Equals(object other)
             return Equals(other as LocalizableString);
         }
 
-        private sealed class FixedLocalizableString : LocalizableString
+        internal LocalizableString MakeExceptionSafe()
```
Comment (heejaechang) [inline src/Compilers/Core/Portable/Diagnostic/LocalizableString.cs]: can this get onException as an argument rather than using SetException .... to set field?

File: src/Compilers/Core/AnalyzerDriver/DiagnosticDescriptorExtensions.cs [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+using System.Collections.Generic;
+using System.Text;
+using Microsoft.CodeAnalysis;
+using Microsoft.CodeAnalysis.Diagnostics;
+
+namespace Microsoft.CodeAnalysis
+{
+    internal static class DiagnosticDescriptorExtensions
+    {
+        public static void SetOnLocalizableStringException(this DiagnosticDescriptor descriptor, DiagnosticAnalyzer owner, Action<Exception, DiagnosticAnalyzer, Diagnostic> onLocalizableStringException)
```
Comment (heejaechang) [inline src/Compilers/Core/AnalyzerDriver/DiagnosticDescriptorExtensions.cs]: it could be nice if we can do what you did for localizable string (exception safe localizable string) to diagnostic description as well.

var exceptionSafeDiagnosticDescriptor = userDiagnosticDescriptor.MakeExceptionSafe(onException);

File: src/Compilers/Core/Portable/Diagnostic/LocalizableString.cs (hunk 2 above)
Comment (mavasani) [inline src/Compilers/Core/Portable/Diagnostic/LocalizableString.cs]: I discussed this with Sri. We have 2 options, either to have a mutable field for OnException that can be hooked up later OR an immutable field for it. In the later case we are force to allocate a new LocalizableString for every LocalizableString passed into DiagnosticDescriptor constructor, where we are not mutating any state but just the OnException hander. In the former case, we can re-use existing instance of LocalizableString. First approach is better allocation wise, second one is better implementation and maintenance wise. I am not sure what is preferable, I hope people can give their opinions here and we can select the desired approach.

File: src/Compilers/Core/AnalyzerDriver/DiagnosticDescriptorExtensions.cs (hunk 3 above)
Comment (mavasani) [inline src/Compilers/Core/AnalyzerDriver/DiagnosticDescriptorExtensions.cs]: Yes, I prefer that too but is it ok to allocate a new descriptor for every descriptor returned by analyzers? Btw the userDiagnosticDescriptor above is already exception safe, we just need to hookup the optional exception handler to report exception diagnostic here.

Comment (heejaechang) [inline src/Compilers/Core/AnalyzerDriver/DiagnosticDescriptorExtensions.cs]: since descriptor is created once and cached for the life time of analyzer, I think we don't need to worry about allocation that much.

File: src/Compilers/Core/Portable/Diagnostic/LocalizableString.cs (hunk 2 above)
Comment (mavasani) [inline src/Compilers/Core/Portable/Diagnostic/LocalizableString.cs]: @heejaechang I have made your suggested change.

**Comment by tmeschter** [comment]
So it looks like we're basically adding events that fire when we're unable to get the localized text of a localizable string, except there's no way to unsubscribe from the events. Is this a memory leak? That is, is it a problem that the `LocalizableString` holds on to the OnException indefinitely?

**Comment by mavasani** [comment]
Good point.

Lifetime of localizable strings should be less than the owing descriptors. We currently cache descriptors onto a conditional weak table, keyed onto analyzer instance in the AnalyzerManager. Once a project is removed or its analyzer reference is removed, we dispose the analyzer reference and hence the analyzer instance, plus also clear off host diagnostics reported for analyzers from the analyzer reference. So nothing should hold onto the descriptor (and hence the localizable string) beyond the lifetime of the analyzer instance, that would be an even bigger concern for a leak.
Additionally, the OnException delegate in IDE just reports the diagnostic on the HostDiagnosticUpdateSource, which lives for lifetime of the workspace, so its not an immediate concern.

Having said that, I think an alternative to current approach would be to have OnException be an actual instance event on the LocalizableString so we don't need to re-allocate a localizable string just to register the exception handler.
Additionally, when we dispose off the analyzer reference we can explicitly walk through each contained analyzer's descriptors and their loc string fields and clear off the OnException event. Does that sound like a more preferred approach?

**Comment by heejaechang** [comment]
What was the reason we couldn’t seal the localizable string?

Can we have LocalizableString(.. something provider) and seal LocalizableString itself? And LocalizableString itself has an event that raised on exception?


-          heejae

**Comment by mavasani** [comment]
That is more of an API design question, but anyways I don't think extensibility of LocalizableString is an issue if we wanted to have an event for OnException on it. We can still have it. It is just that event args can just have the exception (LocalizableString has no knowledge of owning descriptor or analyzer), so the AnalyzerManager must wrap it's subscribed event handler with analyzer and exception diagnostic info and pass it to the host. It would also need to cache the registered handler per analyzer so that it can unsubscribe them later when analyzer reference is getting disposed.

**Comment by mavasani** [comment]
@tmeschter @heejaechang I have switched to using the event model for LocalizableString.OnException with subscribe/unsubscribe approach.

**Comment by srivatsn** [comment]
:+1:

**Comment by mavasani** [comment]
@dotnet-bot retest this please.

**Comment by heejaechang** [comment]
:+1:
