### PR TITLE
🐛 Fix Type/Constructor deduplication in Find All References

### LINKED ISSUE #35139: Find References results should distinguish direct and indirect references
See discussion in #34617.

Currently Find All References on a named type returns references to both the type itself and references to the constructor(s). In this and similar cases, the `FinderLocation` should indicate whether the location is a direct reference to the symbol passed to Find All References, or to a related symbol.

The Find All References presenter should be updated to not show references to a related symbol on the searched symbol whenever the related symbol will also be shown in the results. For example the following image shows a reference location that should not have been presented because it is a duplicate:

image

Related to #32738

### PR DESCRIPTION
**Pull request by sharwell**
~~The behavior once provided by this field will be generalized in #35139.~~

Closes #35139

### CODE REVIEW

File: src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamedTypeSymbolReferenceFinder.cs [hunk 1]
```diff
@@ -89,57 +89,7 @@ protected override bool CanFind(INamedTypeSymbol symbol)
...
-                constructorReferences.AddRange(references);
-            }
-
-            var result = ArrayBuilder<FinderLocation>.GetInstance();
-            foreach (var finderLocation in namedTypeReferences)
-            {
-                if (Contains(constructorReferences, finderLocation))
-                {
-                    var location = finderLocation.Location;
-                    location.IsDuplicateReferenceLocation = true;
```
Comment (sharwell) [inline src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamedTypeSymbolReferenceFinder.cs]: 📝 This is a dead store to a field of a value type in a temporary location. It is immediately discarded.

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamedTypeSymbolReferenceFinder.cs]: this looks like this regressed.  the code used to be:

```c#
                    var localReference = reference;
                    localReference.Location.IsDuplicateReferenceLocation = true;
                    result.Add(localReference);
```

This data would not have been lost.

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamedTypeSymbolReferenceFinder.cs]: Looks like i regressed this in: https://github.com/dotnet/roslyn/commit/3993e8dd5d72c898e2008add8afd7226500b8d57

However, i would prefer we maintain the original semantics rather than just remove this code.  The logic here was intentional and was supposed to be something observable in the UI.

Comment (sharwell) [reply src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamedTypeSymbolReferenceFinder.cs]: @CyrusNajmabadi I'm happy to restore the original behavior as long as someone can explain what the user-facing bug is 😄

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamedTypeSymbolReferenceFinder.cs]: @sharwell It may be reproable through the UI, or through the API (or both).  The original code came in through:

https://github.com/dotnet/roslyn/pull/14047

I think the issue is that if you search for a NamedType, you can get duplicated results for both it and its' constructors on an "new Foo()" expr.  

So, for example, if you have:

```c#
class Foo
{
    public Foo(int i)
    {

    }
}

class Bar
{
    void X()
    {
        new Foo(1);
    }
}
```

We show you:

image

But we decided we don't want that, and we intended for the "new" call to only show up in the constructors list.

--

yes, this is a fail on me to not adequately test.

Comment (sharwell) [reply src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/NamedTypeSymbolReferenceFinder.cs]: ➡️ On further review, I believe the original internal API for this feature is lacking. Rather than restore it to what I believe is a suboptimal representation, I filed #35139 to follow-up on this by creating a clearer Find All References API that more clearly supports grouping locations by the referenced symbol, even when it differs from the original symbol searched for.

File: src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_Hierarchy.cs [hunk 2]
```diff
@@ -416,11 +416,6 @@ public static async Task<IEnumerable<SymbolCallerInfo>> FindCallersAsync(ISymbol
                 }
             }
 
-            if (searchSymbol.Kind == SymbolKind.NamedType && symbolToMatch.IsConstructor())
```
Comment (sharwell) [inline src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_Hierarchy.cs]: 📝 I tracked this back to the start of the repository:

https://github.com/dotnet/roslyn/blob/fdcbb654875a4c61312a4d72da8fb59fc15fd5a9/src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs#L315-L318

However, it seems to duplicate the intent of `NamedTypeSymbolReferenceFinder.DetermineCascadedSymbolsAsync`. Cascaded symbols are correctly aggregated by the target of the reference, thus addressing the original bug without locating duplicate references.

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/FindSymbols/SymbolFinder_Hierarchy.cs]: That's great to know.  Mostly, i'm fine if we land in an area where:

1. the actual FAR **API** is sensible and clear.
2. the FAR feature/UI can handle these cases sensibly.  

in terms of the impl to get there, i'm very open to discussing options both in the FAR API model, as well as the code that runs at all teh different layers.  

I appreciate you looking at this, especially if we take a 'lean back and look at the whole picture' to decide what the best way forward is.

**Comment by sharwell** [comment]
@CyrusNajmabadi This should be ready for review again. The bug should be fixed as well.

**Comment by CyrusNajmabadi** [comment]
Can you give a brief rundown on how the FAR API now works post your change?  Thanks!

**Comment by sharwell** [comment]
> Can you give a brief rundown on how the FAR API now works post your change? Thanks!

Previously, FAR on a named type would cascade constructors into the search. Then it would search for references to the named type and combine those results with the results for searching for the constructor. During the search for named types, references to the constructors would be included. Therefore, each reference to a constructor was included twice in the results: once claiming to be a reference to the constructor, and the other claiming to be a reference to the type.

In the new API, constructors are still cascaded into the search for a named type. However, references to the constructors are only included in the results once, and they identify with the constructor definition.

**Comment by CyrusNajmabadi** [comment]
Well that's just much saner.  Glad you did this!

File: src/Workspaces/Core/Portable/Rename/RenameLocation.ReferenceProcessing.cs [hunk 3]
```diff
@@ -201,6 +212,14 @@ await IsPropertyAccessorOrAnOverride(originalSymbol, solution, cancellationToken
...
 
                 return false;
+
+                // Local functions
+                static bool IsConstructorForType(ISymbol possibleConstructor, ISymbol possibleType)
+                {
+                    return possibleConstructor.IsConstructor()
+                        && possibleType is INamedTypeSymbol namedType
+                        && Equals(possibleConstructor.ContainingType.ConstructedFrom, namedType.ConstructedFrom);
+                }
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Rename/RenameLocation.ReferenceProcessing.cs]: would like @jasonmalinowski 's eyes here as he knows rename-core better than i do. But i don't see anything that concerns me here.

**Comment by sharwell** [comment]
@jasonmalinowski gave me the idea for this approach so 👍 thanks for that!

File: src/Workspaces/Core/Portable/Rename/RenameLocation.ReferenceProcessing.cs (hunk 3 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/Rename/RenameLocation.ReferenceProcessing.cs]: Agreed, one of @jasonmalinowski, @dpoeschl or @ryzngard should validate the changes for rename processing.

**Comment by dpoeschl** [comment]
Should we have FAR tests here? I understand not having Rename tests exactly, since the goal here is to not change its behavior.

**Comment by sharwell** [comment]
I'll file a follow-up issue for the test gap. This is not the first time this has come up for this feature. 😄
