### PR TITLE
Make Finally keyword recommendation more precise

### LINKED ISSUE #2623: VS crash on editing nested VB Try/Catch blocks
Copy/paste VB code and follow the directions in the comment. Found while dogfooding.
```VB
Class C
    Sub M()
        Try
        Catch
            Try ' Type an 'E' on the next line

                Throw
            End Try
    End Sub
End Class
```
There are ArgumentOutOfRangeExceptions in the FinallyKeywordRecommender and eventually an ExecutionEngineException that brings down VS, but I haven't been able to figure out where that one comes from due to debugger issues.
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Microsoft.CodeAnalysis.SyntaxList`1.get_Item(Int32 index) in C:\Roslyn\Main\Open\src\Compilers\Core\Portable\Syntax\SyntaxList`1.cs:line 68
   at Microsoft.CodeAnalysis.SyntaxList`1.Last() in C:\Roslyn\Main\Open\src\Compilers\Core\Portable\Syntax\SyntaxList`1.cs:line 323
   at Microsoft.CodeAnalysis.VisualBasic.Completion.KeywordRecommenders.Statements.FinallyKeywordRecommender.RecommendKeywords(VisualBasicSyntaxContext context, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Features\VisualBasic\Completion\KeywordRecommenders\Statements\FinallyKeywordRecommender.vb:line 37
   at Microsoft.CodeAnalysis.VisualBasic.Completion.KeywordRecommenders.AbstractKeywordRecommender.RecommendKeywords(Int32 position, VisualBasicSyntaxContext context, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Features\VisualBasic\Completion\KeywordRecommenders\AbstractKeywordRecommender.vb:line 17
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractKeywordCompletionProvider`1.<RecommendKeywordsAsync>d__9.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractKeywordCompletionProvider.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractKeywordCompletionProvider`1.<>c__DisplayClass6_0.<<GetItemsWorkerAsync>b__0>d.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractKeywordCompletionProvider.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.<GetUnionResultsFromDocumentAndLinks>d__3`1.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Shared\Extensions\DocumentExtensions.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractKeywordCompletionProvider`1.<GetItemsWorkerAsync>d__6.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractKeywordCompletionProvider.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractCompletionProvider.<GetItemsAsync>d__7.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractCompletionProvider.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractCompletionProvider.<GetGroupAsync>d__4.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractCompletionProvider.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.AbstractCompletionService.<GetGroupsAsync>d__13.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Completion\AbstractCompletionService.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.AbstractCompletionService.<GetGroupsAsync>d__10.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Completion\AbstractCompletionService.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<GetGroupsAsync>d__16.MoveNext() in C:\Roslyn\Main\Open\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Controller.Session_ComputeModel.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<DoInBackgroundAsync>d__15.MoveNext() in C:\Roslyn\Main\Open\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Controller.Session_ComputeModel.cs:line 106
5/9/2015 7:42:39 PM
Source: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: Microsoft.CodeAnalysis
StackTrace:    at Microsoft.CodeAnalysis.SyntaxList`1.get_Item(Int32 index) in C:\Roslyn\Main\Open\src\Compilers\Core\Portable\Syntax\SyntaxList`1.cs:line 68
   at Microsoft.CodeAnalysis.SyntaxList`1.Last() in C:\Roslyn\Main\Open\src\Compilers\Core\Portable\Syntax\SyntaxList`1.cs:line 323
   at Microsoft.CodeAnalysis.VisualBasic.Completion.KeywordRecommenders.Statements.FinallyKeywordRecommender.RecommendKeywords(VisualBasicSyntaxContext context, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Features\VisualBasic\Completion\KeywordRecommenders\Statements\FinallyKeywordRecommender.vb:line 37
   at Microsoft.CodeAnalysis.VisualBasic.Completion.KeywordRecommenders.AbstractKeywordRecommender.RecommendKeywords(Int32 position, VisualBasicSyntaxContext context, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Features\VisualBasic\Completion\KeywordRecommenders\AbstractKeywordRecommender.vb:line 17
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractKeywordCompletionProvider`1.<RecommendKeywordsAsync>d__9.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractKeywordCompletionProvider.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractKeywordCompletionProvider`1.<>c__DisplayClass6_0.<<GetItemsWorkerAsync>b__0>d.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractKeywordCompletionProvider.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.<GetUnionResultsFromDocumentAndLinks>d__3`1.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Shared\Extensions\DocumentExtensions.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractKeywordCompletionProvider`1.<GetItemsWorkerAsync>d__6.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractKeywordCompletionProvider.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractCompletionProvider.<GetItemsAsync>d__7.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractCompletionProvider.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractCompletionProvider.<GetGroupAsync>d__4.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractCompletionProvider.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.AbstractCompletionService.<GetGroupsAsync>d__13.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Completion\AbstractCompletionService.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.AbstractCompletionService.<GetGroupsAsync>d__10.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Completion\AbstractCompletionService.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<GetGroupsAsync>d__16.MoveNext() in C:\Roslyn\Main\Open\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Controller.Session_ComputeModel.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<DoInBackgroundAsync>d__15.MoveNext() in C:\Roslyn\Main\Open\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Controller.Session_ComputeModel.cs:line 106
```

### PR DESCRIPTION
**Pull request by rchande**
Fixes #2623 
Reviewers: @dpoeschl @jasonmalinowski @Pilchie @balajikris @davkean @jmarolf

### CODE REVIEW

File: src/Features/VisualBasic/Completion/KeywordRecommenders/Statements/FinallyKeywordRecommender.vb [hunk 1]
```diff
@@ -41,5 +41,18 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Completion.KeywordRecommenders.Stat
 
             Return SpecializedCollections.EmptyEnumerable(Of RecommendedKeyword)()
         End Function
+
+        Private Function IsInCatchOfTry(targetToken As SyntaxToken, tryBlock As TryBlockSyntax) As Boolean
+            Dim parent = targetToken.Parent
+            While parent IsNot tryBlock
```
Comment (jasonmalinowski) [inline src/Features/VisualBasic/Completion/KeywordRecommenders/Statements/FinallyKeywordRecommender.vb]: What happens if parent becomes null?

File: src/Features/VisualBasic/Completion/KeywordRecommenders/Statements/FinallyKeywordRecommender.vb [hunk 2]
```diff
@@ -41,5 +41,18 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Completion.KeywordRecommenders.Stat
...
+                If parent.IsKind(SyntaxKind.CatchBlock) AndAlso tryBlock.CatchBlocks.Contains(DirectCast(parent, CatchBlockSyntax)) Then
```
Comment (jasonmalinowski) [inline src/Features/VisualBasic/Completion/KeywordRecommenders/Statements/FinallyKeywordRecommender.vb]: I wouldn't expect the cast is needed...

File: src/Features/VisualBasic/Completion/KeywordRecommenders/Statements/FinallyKeywordRecommender.vb [hunk 3]
```diff
@@ -41,5 +41,18 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Completion.KeywordRecommenders.Stat
 
             Return SpecializedCollections.EmptyEnumerable(Of RecommendedKeyword)()
         End Function
+
+        Private Function IsInCatchOfTry(targetToken As SyntaxToken, tryBlock As TryBlockSyntax) As Boolean
```
Comment (jasonmalinowski) [inline src/Features/VisualBasic/Completion/KeywordRecommenders/Statements/FinallyKeywordRecommender.vb]: If you're bored this can be come something like targetToken.GetAncestors(Of CatchBlockSyntax).TakeUntil(...).

**Comment by jasonmalinowski** [comment]
I hang my head in shame. :+1:

File: src/Features/VisualBasic/Completion/KeywordRecommenders/Statements/FinallyKeywordRecommender.vb (hunk 1 above)
Comment (rchande) [inline src/Features/VisualBasic/Completion/KeywordRecommenders/Statements/FinallyKeywordRecommender.vb]: You would hit the tryBlock first--we already know it's an ancestor of targetToken.

File: src/Features/VisualBasic/Completion/KeywordRecommenders/Statements/FinallyKeywordRecommender.vb (hunk 2 above)
Comment (rchande) [inline src/Features/VisualBasic/Completion/KeywordRecommenders/Statements/FinallyKeywordRecommender.vb]: It was :)

**Comment by Pilchie** [comment]
:+1:
