### PR TITLE
Fix metadata references not always having file watchers

### LINKED ISSUE #32554: IntelliSense errors for dependency references in newly created Service Fabric project
Regression in 16.0.

1. Launch the new project dialog
2. Create a Service Fabric Application project
3. Select the .NET Core Actor Service template from the New Service Fabric Service dialog
4. Wait for the solution to load and dependencies to restore
5. Check the Error List window and ensure the filter is set to show IntelliSense errors

Expected:
No IntelliSense errors should be reported (dependencies are restored and all references are resolvable).

Actual:
All references to dependencies (NuGet, SDK, or Project references) in the primary service project (Actor1 by default) are flagged as IntelliSense errors.

The errors are only reported for the newly created project and don't reappear after closing and re-opening the solution or unloading and reloading the specific project the errors are associated with. A full build succeeds without any errors or warnings, but doesn't clear the IntelliSense errors.

### PR DESCRIPTION
**Pull request by jasonmalinowski**
When we created metadata references inside of VisualStudioProject, we ensured we created them with a file watcher so we would know about changes. When we created a metadata reference after we converted a project reference back to a metadata reference that was originally a metadata reference, we didn't do so since that conversion happens in VisualStudioWorkspaceImpl itself and it couldn't access the file watcher.

This fixes this. The majority of the work here is just moving code around. Basically the watchers were per-project, which meant that it'd be forbidden to call into them the Workspace code because that would violate the lock hierarchy. To fix this, I move the file watching logic into it's own little type with a lock, and since no calls are made back into the workspace under that lock, it removes the deadlock concerns.

Fixes #32554.

<details><summary>Ask Mode template</summary>

### Customer scenario

Customer has a project with lots of P2P references and loads/unloads projects in various orders. In some cases, this will cause VS to crash or at least the project system to get in a missynced state.

### Bugs this fixes

dotnet/roslyn#32554 and https://devdiv.visualstudio.com/DevDiv/_workitems/edit/750094

### Workarounds, if any

None, really. If you don't unload projects you won't hit it, but creating some types of projects implicitly do the problematic operations in their template wizard.

### Risk

Moderate: it's a fair amount of code churn, but the churn is fairly straightforward.

### Performance impact

None.

### Is this a regression from a previous update?

Yes, this was broken by a late Preview 1 fix that missed an edge case.

### Root cause analysis

This edge case noticed in testing of a fix we made for Preview 1, but the full impact wasn't realized, and at the time a bug was filed to follow up on it. This is fixing the issue. Tests have been added to cover this scenario too.

### How was the bug found?

Noticed during testing of another fix, and also internal testing with certain templates that also trigger the bug.

</details>

### CODE REVIEW

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs [hunk 1]
```diff
@@ -1628,5 +1628,41 @@ public void RemoveProjectOutputPath(ProjectId projectId, string outputPath)
                 }
             }
         }
+
+        private void RefreshMetadataReferencesForFile(object sender, string fullFilePath)
+        {
+            lock (_gate)
+            {
+                var newSolution = CurrentSolution;
+                var changedProjectIds = new HashSet<ProjectId>();
```
Comment (tmat) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs]: >var changedProjectIds = new HashSet<ProjectId>(); [](start = 16, length = 49)

Pool the hash set?

**Comment by tmat** [comment]
>             var projectIdsChanged = new HashSet<ProjectId>();

Pool hashset?

---
Refers to: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs:1424 in 441d055. [](commit_id = 441d055dea484ebeed9135f8ac765e0c5fa4ea10, deletion_comment = False)

**Comment by tmat** [comment]
>             var projectIdsChanged = new HashSet<ProjectId>();

Pool hashset?

---
Refers to: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs:1492 in 441d055. [](commit_id = 441d055dea484ebeed9135f8ac765e0c5fa4ea10, deletion_comment = False)

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/MetadataReferences/FileWatchedPortableExecutableReferenceFactory.cs [hunk 2]
```diff
@@ -0,0 +1,134 @@
...
+    [Export]
+    internal sealed class FileWatchedPortableExecutableReferenceFactory
+    {
+        private readonly object _gate = new object();
+
+        /// <summary>
+        /// This right now acquires the entire VisualStudioWorkspace because right now the production
+        /// of metadata references depends on other workspace services. See the comments on
+        /// <see cref="VisualStudioMetadataReferenceManagerFactory"/> that this strictly shouldn't be necessary
+        /// but for now is quite the tangle to fix.
```
Comment (tmat) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/MetadataReferences/FileWatchedPortableExecutableReferenceFactory.cs]: >but for now is quite the tangle to fix. [](start = 12, length = 39)

Do we have an issue that tracks untangling it?

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/MetadataReferences/FileWatchedPortableExecutableReferenceFactory.cs [hunk 3]
```diff
@@ -0,0 +1,134 @@
...
+        {
+            _visualStudioWorkspace = visualStudioWorkspace;
+
+            // TODO: set this to watch the NuGet directory or the reference assemblies directory; since those change rarely and most references
+            // will come from them, we can avoid creating a bunch of explicit file watchers.
+            _fileReferenceChangeContext = fileChangeWatcherProvider.Watcher.CreateContext();
+            _fileReferenceChangeContext.FileChanged += FileReferenceChangeContext_FileChanged;
+        }
+
+        public event EventHandler<string> ReferenceChanged;
```
Comment (tmat) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/MetadataReferences/FileWatchedPortableExecutableReferenceFactory.cs]: >EventHandler [](start = 21, length = 12)

Curious, why are we using EventHandler instead of just `Action<string>`. We never seem to use `object sender` parameter.

Comment (jasonmalinowski) [reply src/VisualStudio/Core/Def/Implementation/ProjectSystem/MetadataReferences/FileWatchedPortableExecutableReferenceFactory.cs]: Just following framework convention. And we don't use it now, but if this ever goes public, better to do it than regret it.

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/MetadataReferences/FileWatchedPortableExecutableReferenceFactory.cs (hunk 2 above)
Comment (jasonmalinowski) [reply src/VisualStudio/Core/Def/Implementation/ProjectSystem/MetadataReferences/FileWatchedPortableExecutableReferenceFactory.cs]: Ah, thought we had one but didn't. https://devdiv.visualstudio.com/DevDiv/_workitems/edit/777154 filed.

**Comment by jasonmalinowski** [comment]
Tagging @jinujoseph for M2 approval. @tmat's suggestions of hash set pooling are wise and I'll fix that up before merging.
