### PR TITLE
Permit stackalloc to be used in an async method as long as it need not be spilled.

### LINKED ISSUE #37461: Incorrect spilling of stackalloc in async method
**Version Used**: 
image

**Steps to Reproduce**:

```C#
using System;
using System.Threading.Tasks;

public class P
{
    static object F1() => 1;
    static object F2() => 1;
    static int G(object obj, Span<int> span) => span.Length;

    static async Task Async1(Object obj, int i) { await Task.Delay(1); }

    static async Task Main()
    {
        await Async1(F1(), G(F2(), stackalloc int[] { 1, 2, 3 }));
    }
}
```

**Actual**

The program compiles and throws 

> System.TypeLoadException: 'A ByRef-like type cannot be used as the type for an instance field in a non-ByRef-like type.'

at runtime since the lowering of stackalloc in await expression spills `Span<T>` to a state machine field.

**Expected**

Compiler error.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #37461

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a couple of reviews of this nested stackalloc bug fix?

**Comment by 333fred** [comment]
@gafter https://github.com/dotnet/roslyn/issues/36443 is very related, do you want to take a look at that one while you're here?

**Comment by gafter** [comment]
I don't think #36443 is very related.  We have hooks for hoisting a ref local as long as it is compiler-generated and initialized with one of a small number of forms (which we just reevaluate when we would reuse the local).  #36443 is probably an issue with that.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StackAlloc.cs [hunk 1]
```diff
@@ -64,12 +64,20 @@ public override BoundNode VisitStackAllocArrayCreation(BoundStackAllocArrayCreat
                         type: ErrorTypeSymbol.UnknownResultType);
                 }
 
+                // The stackalloc instruction requires that the evaluation tack contains only its parameter when executed.
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StackAlloc.cs]: >tack [](start = 75, length = 4)

nit: spelling

File: src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs [hunk 2]
```diff
@@ -3236,39 +3233,37 @@ static bool M(object o)
...
-  IL_0025:  ldloc.3
-  IL_0026:  ret
-}");
+                    compVerifier.VerifyIL("Class1.M", @"
+{
+      // Code size       37 (0x25)
+      .maxstack  2
+      .locals init (bool V_0,
+                    int V_1,
+                    bool V_2)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs]: How did this IL end up changing? It doesn't seem related to the changes in the implementation.

Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs]: See the change in SpillSequenceSpiller.  We no longer make an extra copy through a local of the value of a spill sequence.

---
In reply to: [311192368](https://github.com/dotnet/roslyn/pull/37711#discussion_r311192368) [](ancestors = 311192368)

**Comment by gafter** [comment]
@RikkiGibson @333fred Do you have any further comments?
@dotnet/roslyn-compiler I still need a review from a Sr developer, please.

**Comment by gafter** [comment]
@agocke Could you review this please?

**Comment by gafter** [comment]
@jcouv Can you review this please?

**Comment by jcouv** [comment]
Looking

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StackAlloc.cs [hunk 3]
```diff
@@ -64,12 +64,20 @@ public override BoundNode VisitStackAllocArrayCreation(BoundStackAllocArrayCreat
                         type: ErrorTypeSymbol.UnknownResultType);
                 }
 
+                // The stackalloc instruction requires that the evaluation stack contains only its parameter when executed.
+                // We arrange to clear the stack by wrapping it in a SpillSequence, which will cause pending computations
+                // to be spilled, and also by storing the result in a temporary local, so that the result does not get
+                // hoisted/spilled into some state machine.  If that temp local needs to be spilled that will result in an
+                // error.
                 _needsSpilling = true;
+                var tempAccess = _factory.StoreToTemp(constructorCall, out BoundAssignmentOperator tempAssignment, syntaxOpt: stackAllocNode.Syntax);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StackAlloc.cs]: >StoreToTemp [](start = 42, length = 11)

Should we use `kind: SynthesizedLocalKind.Spill`?

File: src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs [hunk 4]
```diff
@@ -3165,48 +3165,45 @@ public static void Main()
...
-  IL_002e:  stloc.1
-  // sequence point: y.Chain2();
-  IL_002f:  ldloc.1
-  IL_0030:  callvirt   ""Program Program.Chain2()""
-  IL_0035:  pop
-  // sequence point: }
-  IL_0036:  ret
-}
+            v.VerifyIL(qualifiedMethodName: "Program.Main", @"
+    {
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs]: >{ [](start = 4, length = 1)

nit: indentation unnecessary changed. It's likely due to copy/paste from TestExplorer (adds four spaces... we've reported that bug)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StackAlloc.cs (hunk 3 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StackAlloc.cs]: No, that would cause things to break again.  Because in DEBUG it would be hoisted to a field, and this `var tmp = stackalloc...` would turn into this `frame.tmp = stackalloc...` which would leave frame on the stack when stackalloc appears in the IL.  That is a violation of the constraint that nothing but the argument to stackalloc may be on the stack where it appears in the IL.

---
In reply to: [315396717](https://github.com/dotnet/roslyn/pull/37711#discussion_r315396717) [](ancestors = 315396717)

File: src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs (hunk 4 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs]: I'm not willing to go through the painful hand-editing that would be required to fix this.

---
In reply to: [315403483](https://github.com/dotnet/roslyn/pull/37711#discussion_r315403483) [](ancestors = 315403483)
