### PR TITLE
Bad code for consecutive interface type tests with a when clause in a switch

### LINKED ISSUE #32774: Visual Studio 2019 Preview 2 breaks Switch Case with when Statements
**Version Used**: 
Visual Studio 2019 Preview 2

**Steps to Reproduce**:
Certain switch case statements including a when clause stopped working since updating to VS 2019 Preview 2.

The following statement will fail for every case that is not matched before the when clause:

        switch (someObject)
         {
            case string x:
               return true;
            case int x:
               return true;
            case IObject x when x.SubObject != null:
               return true;
            case IOtherObject x:
               return true;
            case double x:
               return true;
            default:
               return false;
         }

The following exception is thrown:  
_System.InvalidCastException: Unable to cast object of type 'System.Double' to type 'IOtherObject'._

However if you have an additional case just after the when where check without a condition it works fine:  

         switch (someObject)
         {
            case string x:
               return true;
            case int x:
               return true;
            case IObject x when x.SubObject != null:
               return true;
            case IObject x:
               return true;
            case IOtherObject x:
               return true;
            case double x:
               return true;
            default:
               return false;
         }

I uploaded a demo project to github that includes both cases and respective tests to showcase the problem:
https://github.com/huserben/VS19_SwitchCaseWhen

You can run the tests in VS 19 Preview 1 and one will fail, while both succeed if run from VS 2017

**Expected Behavior**:
Switch Case works in any of the cases

### PR DESCRIPTION
**Pull request by gafter**
Fixes #32774

@dotnet/roslyn-compiler May I please have a couple of reviews for this bad code fix targeting preview 3?

### CODE REVIEW

**Comment by gafter** [comment]
@cston @agocke May I please have a couple of reviews for this bad code fix targeting preview 3?

File: src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs [hunk 1]
```diff
@@ -2130,5 +2130,105 @@ static class C {
                 Diagnostic(ErrorCode.WRN_SwitchExpressionNotExhaustive, "switch").WithLocation(9, 38)
                 );
         }
+
+        [Fact, WorkItem(32774, "https://github.com/dotnet/roslyn/issues/32774")]
+        public void BadCode_32774()
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs]: >BadCode_32774 [](start = 20, length = 13)

Consider renaming the test since the test should not generate bad code. Perhaps `MatchAfterEliminatedEvaluationNode`.

**Comment by mjsabby** [comment]
Any chance this can make Preview 3?

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a second review?
