### PR TITLE
Fix for #22690 NRE in GetAttributeSyntaxNodeOfToken

### LINKED ISSUE #22690: VS crash: AbstractInternalsVisibleToCompletionProvider.GetAttributeSyntaxNodeOfToken throws NRE
```
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.Kind(SyntaxNode node) in E:\A\_work\24\s\src\Compilers\CSharp\Portable\CSharpExtensions.cs:line 161
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxFactsService.IsStringLiteralExpression(SyntaxNode node) in E:\A\_work\24\s\src\Workspaces\CSharp\Portable\LanguageServices\CSharpSyntaxFactsService.cs:line 1314
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractInternalsVisibleToCompletionProvider.GetAttributeSyntaxNodeOfToken(ISyntaxFactsService syntaxFactsService, SyntaxToken token) in E:\A\_work\24\s\src\Features\Core\Portable\Completion\Providers\AbstractInternalsVisibleToCompletionProvider.cs:line 78
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractInternalsVisibleToCompletionProvider.<ProvideCompletionsAsync>d__4.MoveNext() in E:\A\_work\24\s\src\Features\Core\Portable\Completion\Providers\AbstractInternalsVisibleToCompletionProvider.cs:line 55
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 157
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<GetContextAsync>d__31.MoveNext() in E:\A\_work\24\s\src\Features\Core\Portable\Completion\CompletionServiceWithProviders.cs:line 449
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 157
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<ComputeNonEmptyCompletionContextsAsync>d__24.MoveNext() in E:\A\_work\24\s\src\Features\Core\Portable\Completion\CompletionServiceWithProviders.cs:line 311
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 157
   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.<GetCompletionsAsync>d__22.MoveNext() in E:\A\_work\24\s\src\Features\Core\Portable\Completion\CompletionServiceWithProviders.cs:line 241
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 157
   at Microsoft.CodeAnalysis.Completion.CompletionService.<GetCompletionsAndSetItemDocumentAsync>d__11.MoveNext() in E:\A\_work\24\s\src\Features\Core\Portable\Completion\CompletionService.cs:line 183
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 184
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 157
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<DoInBackgroundAsync>d__13.MoveNext() in E:\A\_work\24\s\src\EditorFeatures\Core\Implementation\IntelliSense\Completion\Controller.Session_ComputeModel.cs:line 103
```

Crash dump: %internal_share%\public\tomat\Bugs\22690

VS build: 15.5.0 P1 (26927.1)

### PR DESCRIPTION
**Pull request by sharwell**
:memo: This is a back-port of #22961 to **dev15.5.x**. The template below is copied from that issue.

**Customer scenario**

An NRE in AbstractInternalsVisibleToCompletionProvider causes a crash of VS. The NRE was not reproducible and seemed only to occur in the C# intermediate window. No tests are provided (see #22690 why).

**Bugs this fixes:**

Fixes #22690 
[DevDiv 525354](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/525354)

**Workarounds, if any**

None.

**Risk**

Bug was not reproducible and therefore no tests are given. The fix is a best guess effort and is based on looking at possible NRE places in the stacktrace given by #22690:

* `IsStringLiteralExpression` is only called at on place in `AbstractInternalsVisibleToCompletionProvider.GetAttributeSyntaxNodeOfToken`
* `CSharpSyntaxFactsService.IsStringLiteralExpression`  is defined as `=> node.Kind() == SyntaxKind.StringLiteralExpression;`
* `node.Kind()` causes the NRE most likely here: `var rawKind = node.RawKind;` if node is null.

If this analysis is not correct there might still be a bug that causes VS to crash.

**Performance impact**

None.

**Is this a regression from a previous update?**

No. New feature. Bug found in VS 15.5 Preview 1

**Root cause analysis:**

`var node = token.Parent;` returns `null` in some rare circumstances. This was discovered in VS 15.5 Preview 1.

**How was the bug found?**

Reported by @tmat in #22690.

**Test documentation updated?**

No.

### CODE REVIEW

File: src/Features/Core/Portable/Completion/Providers/AbstractInternalsVisibleToCompletionProvider.cs [hunk 1]
```diff
@@ -75,7 +75,7 @@ private static SyntaxNode GetAttributeSyntaxNodeOfToken(ISyntaxFactsService synt
             //[Attribute(""|
             //[Attribute("Text"|)
             var node = token.Parent;
-            if (syntaxFactsService.IsStringLiteralExpression(node))
+            if (node != null && syntaxFactsService.IsStringLiteralExpression(node))
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/AbstractInternalsVisibleToCompletionProvider.cs]: this seems fine. but, in general, the syntax facts do the null checks.

**Comment by jinujoseph** [comment]
cc/ @tmat

**Comment by tmat** [comment]
test windows_release_vs-integration_prtest  please

**Comment by sharwell** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please

**Comment by natidea** [comment]
Approved to merge via https://devdiv.visualstudio.com/DevDiv/_workitems/edit/525354
