### PR TITLE
Fix UnmanagedCallingConventions test reliability

### LINKED ISSUE #48641: Roslyn UnmanagedCallingConventions failure
|Build|Definition|Kind|Run Name|
|---|---|---|---|
|[853806](https://dev.azure.com/dnceng/public/_build/results?buildId=853806)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Test Windows Desktop Debug 32|
|[844705](https://dev.azure.com/dnceng/public/_build/results?buildId=844705)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|[PR 48427](https://github.com/dotnet/roslyn/pull/48427)|Windows Desktop Release Test32|
|[844359](https://dev.azure.com/dnceng/public/_build/results?buildId=844359)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|[PR 48411](https://github.com/dotnet/roslyn/pull/48411)|Test Windows Desktop Release 64|
|[841244](https://dev.azure.com/dnceng/public/_build/results?buildId=841244)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Windows Desktop Release Test64|
|[838062](https://dev.azure.com/dnceng/public/_build/results?buildId=838062)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|[PR 48168](https://github.com/dotnet/roslyn/pull/48168)|Windows Desktop Debug Test64|
|[833358](https://dev.azure.com/dnceng/public/_build/results?buildId=833358)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|[PR 48101](https://github.com/dotnet/roslyn/pull/48101)|Windows Desktop Release Test64|
|[832818](https://dev.azure.com/dnceng/public/_build/results?buildId=832818)|[roslyn-CI](https://dnceng.visualstudio.com/public/_build?definitionId=15)|Rolling|Windows Desktop Release Test64|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|1|1|7|

### PR DESCRIPTION
**Pull request by jaredpar**
The test needs the `CombineStrings` instane to be alive through the
duration of the function pointer call. The `GC.KeepAlive` call though
was on the returned `IntPtr`. That is essentially a no-op cause it just
boxes to `object`. It doesn't actaully track the underlying `delegate`
instance.

Changed the code to track the `delegate` and push the `KeepAlive` after
the function pointer invocation.

closes #48641

### CODE REVIEW

**Comment by jaredpar** [comment]
@dotnet/roslyn-compiler PTAL

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs [hunk 1]
```diff
@@ -1199,25 +1199,26 @@ public void UnmanagedCallingConventions(string unmanagedConvention, string enumC
...
         return (delegate* unmanaged[{unmanagedConvention}]<string, string, string>)ptr;
     }}
 }}
 class Caller
 {{
     public unsafe static void Main()
     {{
-        Call(UnmanagedFunctionPointer.GetFuncPtr());
+        Call(UnmanagedFunctionPointer.GetFuncPtr(out var del));
+        GC.KeepAlive(del);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs:1221]: is this call actually needed if we are holding onto the `del` anyway?

**Review by RikkiGibson — APPROVED** [review]

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs (hunk 1 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs:1221]: Yes. Lacking this call the GC is free to collect it before the call to `Call`. 

For context: remember that the GC will collect `this` during an instance method call if it detects there are no more uses of `this` in the instance method. That is why you see so many `KeepAlive(this)` calls in .NET code.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenFunctionPointersTests.cs:1221]: TIL why `GC.KeepAlive` was supposed to be named `GC.OkYouCanHaveItNow`
