### PR TITLE
Remove CPS restriction for applying rename during code fix

### LINKED ISSUE #24560: Enable Rename file to match class name feature for .Net Core projects
context https://github.com/dotnet/roslyn/issues/16546 
cc @davkean , not sure if this belongs to project system or here.

### LINKED ISSUE #37469: Not getting Rename file to
In one sln:
image

In another sln it works:
image

Both are identical with:

```cs
namespace N
{
    public static partial class C1
    {
        public static class C2
        {
        }
    }
}
```

In a file named `WrongName.cs`

I could not narrow down a repro, tried restarting VS etc but no dice.

### PR DESCRIPTION
**Pull request by ryzngard**
Fixes #37469 
Fixes #24560

There's no reason I know of to restrict this

### CODE REVIEW

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs [hunk 1]
```diff
@@ -409,9 +409,6 @@ internal override bool CanChangeActiveContextDocument
             }
         }
 
-        internal override bool CanRenameFilesDuringCodeActions(CodeAnalysis.Project project)
-            => !IsCPSProject(project);
-
         internal bool IsCPSProject(CodeAnalysis.Project project)
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs]: The comment in IsCPSProject implies it's only being used for this rename case. Can it be deleted too?

Comment (ryzngard) [reply src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs]: It can't be deleted, but I can update the comment. It's used by [this code](http://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/DesignerAttribute/DesignerAttributeIncrementalAnalyzer.cs,09f9847477df4117) in DesignerAttribute

**Comment by ryzngard** [comment]
Hit a snag while enabling integration tests. Issue filed on [project system](https://github.com/dotnet/project-system/issues/5580). I left the integration test but expect it to fail.

File: src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.MoveTypeCodeAction.cs [hunk 2]
```diff
@@ -54,7 +54,6 @@ protected override async Task<IEnumerable<CodeActionOperation>> ComputeOperation
             internal override bool IsApplicable(Workspace workspace)
                 => _operationKind switch
                 {
-                    MoveTypeOperationKind.RenameFile => workspace.CanRenameFilesDuringCodeActions(_state.SemanticDocument.Document.Project),
                     MoveTypeOperationKind.MoveTypeNamespaceScope => _state.TypeNode.Parent is TNamespaceDeclarationSyntax,
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/CodeRefactorings/MoveType/AbstractMoveTypeService.MoveTypeCodeAction.cs]: this is bizarre.  THe purpose of IsApplicable is to do checks that can only be done on hte UI thread.  it's one final check to make sure we can proceed.

The check of `_state.TypeNode.Parent is TNamespaceDeclarationSyntax` can be done when the analyzer runs trivially.  We should do this in the analyzer and remove IsApplicable entirely.

File: src/Features/Core/Portable/CodeRefactorings/SyncNamespace/AbstractSyncNamespaceCodeRefactoringProvider.MoveFileCodeAction.cs [hunk 3]
```diff
@@ -38,12 +38,6 @@ public MoveFileCodeAction(State state, ImmutableArray<string> newFolders)
 
             internal override bool PerformFinalApplicabilityCheck => true;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/CodeRefactorings/SyncNamespace/AbstractSyncNamespaceCodeRefactoringProvider.MoveFileCodeAction.cs]: this should be false.  THere is no need to perform a final applicability check now :)

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.cs]: def update the comment thanks :)

File: src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpRenameFileToMatchTypeRefactoringNetFramework.cs [hunk 4]
```diff
@@ -0,0 +1,18 @@
+﻿using System;
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpRenameFileToMatchTypeRefactoringNetFramework.cs]: copyright.

**Comment by CyrusNajmabadi** [comment]
any way to proceed on this?

**Comment by penenkel** [comment]
Bump. 
Please do not forget to move this along. I have waited years for this feature to be available w/o Resharper.

**Comment by ryzngard** [comment]
Right now this PR is blocked on https://github.com/dotnet/project-system/issues/5580 

Enabling the experience would work, but would always pop up a misleading dialog which we feel is more of a regression.

**Comment by penenkel** [comment]
Hm, that's unfortunate.

I think I have encountered this dialog when performing the file-rename-quickfix via Resharper. I have to concur hat it is annoying and perhaps misleading. But on the other hand I don't remember it having any negative/unintended consequences, i.e. nothing changed no matter the choice.

On my personal scale of annoyingness, clicking away one unexpected dialog is far less annoying than opening the quick-fix menu, searching for the non-existing rename file option, remembering why it is not there, selecting the file in the solution explorer, pressing rename, and then typing the type name.

I propose to activate this here experience and either accept the appearance of the useless dialog or deactivate _that_ feature entirely. I don't think I have ever encountered the indented use case of said dialog. Such confirmation dialogs are kind of rare in VS as a whole, so it strikes me as somewhat unnatural anyway.

**Comment by dagood** [comment]
https://github.com/dotnet/project-system/issues/5139 was closed as fixed on May 26, is it possible to make progress on this now?

I'm in the same boat, being used to ReSharper.

**Comment by ryzngard** [comment]
@dagood  yup, seems to be resolved now. Updating this PR and preparing to get in for 16.8
