### PR TITLE
Handle analyzers which have enabled rules, but no registered actions.

### LINKED ISSUE #2980: Analyzer diagnostic messages printed to error list, but not in build output
This repros on VSPro_Platform 22919.00

1. Create a new C# console application
2. Run these commands in the Package Manager Console:

        install-package Microsoft.Net.ToolsetCompilers -version 1.0.0-rc2-20150415-05
        install-package StyleCop.Analyzers -version 1.0.0-alpha006

3. Rebuild

**EXPECTED**
3 analyzer warning messages added to the error list *and* printed in the build output window.

**ACTUAL**
3 analyzer warning messages added to the error list but the build output window shows no such warnings.
Command line builds similarly show no warnings.

**Error List** 

Severity Code | Description | Project | File
-------- | ----- | ----- | ---- 
Warning SA1600 | Elements must be documented | ConsoleApplication1   | C:\Users\andarno\git\Threading\ConsoleApplication1\ConsoleApplication1\Program.cs
Warning SA1400 | Element 'Main' must declare an access modifier | ConsoleApplication1 |  C:\Users\andarno\git\Threading\ConsoleApplication1\ConsoleApplication1\Program.cs
Warning SA1400 | Element 'Program' must declare an access modifier | ConsoleApplication1 | C:\Users\andarno\git\Threading\ConsoleApplication1\ConsoleApplication1\Program.cs
 
**Build output window**
> All packages are already installed and there is nothing to restore.
NuGet package restore finished.
1>------ Build started: Project: ConsoleApplication1, Configuration: Debug Any CPU ------
1>  ConsoleApplication1 -> C:\Users\andarno\git\Threading\ConsoleApplication1\ConsoleApplication1\bin\Debug\ConsoleApplication1.exe
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

### PR DESCRIPTION
**Pull request by mavasani**
Customer scenario: Analyzer author writes a bolier plate analyzer that defines the rule that it intends to implement in future, but registers no analyzer actions for analysis. Adding such an analyzer to your analyzer assembly brings down the entire analysis, and no analyzers execute during command line build. The issue was reported for StyleCopAnalyzers package which has many such to-be-implemented analyzers.

Fixes #2980

Fix description: Add a null check around the place we compute set of all registered actions for analyzers.

Testing: Added regression tests + existing tests.

/cc @ManishJayaswal @srivatsn This is for 1.0 milestone.

### CODE REVIEW

**Comment by mavasani** [comment]
@JohnHamby @tmeschter @heejaechang @jmarolf please review.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs [hunk 1]
```diff
@@ -634,7 +634,10 @@ private static Diagnostic GetFilteredDiagnostic(Diagnostic diagnostic, Compilati
                     if (!IsDiagnosticAnalyzerSuppressed(analyzer, analyzerExecutor.Compilation.Options, analyzerManager, analyzerExecutor))
                     {
                         var analyzerActions = await analyzerManager.GetAnalyzerActionsAsync(analyzer, analyzerExecutor).ConfigureAwait(false);
-                        allAnalyzerActions = allAnalyzerActions.Append(analyzerActions);
+                        if (analyzerActions != null)
```
Comment (mavasani) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: This is the fix, rest all changes in this file are triggered by the formatter.

**Comment by srivatsn** [comment]
:+1:

**Comment by MattGertz** [comment]
Approved 5/21 by ML Shiproom.

**Comment by JohnHamby** [comment]
I sign off.
