### PR TITLE
Fix for extract method crashes when extracting an invalid using statement

### LINKED ISSUE #40654: VS 16.5.0 Preview 1.0 - InvalidOperationException Unexpected false
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/865951/vs-1650-preview-10-invalidoperationexception-unexp.html)._

---
With the following code, selecting the line 'using System;' causes an InvalidOperationException. See attached screenshot and stacktrace.

```
namespace InvalidOperationException_Unexpected_false
{
    public static class C
    {
        public static void M()
        {
            using System;
        }
    }
}
```

```
System.InvalidOperationException : Unexpected false
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition,String message)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.LocalVariableSymbol`1.GetOriginalIdentifierToken(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.LocalVariableSymbol`1.AddIdentifierTokenAnnotationPair(List`1 annotations,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.<>c__DisplayClass18_0. <CreateDocumentWithAnnotationsAsync>b__0(VariableInfo v)
   at Roslyn.Utilities.EnumerableExtensions.Do[T](IEnumerable`1 source,Action`1 action)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.CreateDocumentWithAnnotationsAsync(SemanticDocument document,IList`1 variables,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.AnalyzeAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

---
#### Visual Studio Feedback System on 12/23/2019, 07:08 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by allisonchou**
Fixes #40654 and adds applicable tests.

### CODE REVIEW

File: src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs [hunk 1]
```diff
@@ -337,7 +337,7 @@ private OperationStatus CheckActiveStatements(IEnumerable<StatementSyntax> state
 
                 foreach (var statement in statements)
                 {
-                    if (!(statement is LocalDeclarationStatementSyntax declarationStatement))
+                    if (!(statement is LocalDeclarationStatementSyntax declarationStatement) || declarationStatement.Declaration.Variables.FullSpan.IsEmpty)
```
Comment (dibarbet) [inline src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs]: Don't know if it is ever the case in practice, but it looks like the Declaration's variables allows null - http://sourceroslyn.io/#Microsoft.CodeAnalysis.CSharp/Generated/Syntax.xml.Internal.Generated.cs,aef1ed83774e9d67

Comment (dibarbet) [reply src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs]: I take it back, the property is a struct, I didn't read closely enough :(
