### PR TITLE
Give member refactoring tools consistent field selection

### LINKED ISSUE #59470: Move static members to another type is suggested for top-level statements
**Version Used**:  
VS 17.1.0 Preview 6.0, '4.1.0-3.22075.3 (592501cb)'. Language version: 10.0.

**Steps to Reproduce**:

1. dotnet new console
2. Write a statement such as `_ = 42;`
3. Open the quick actions menu

image

image

````
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CodeRefactorings.PullMemberUp.PullMembersUpOptionsBuilder.<>c__DisplayClass0_0.<BuildPullMembersUpOptions>b__0(ValueTuple`2 memberAndMakeAbstract)
   at System.Collections.Immutable.ImmutableArray.CreateRange[TSource,TResult](ImmutableArray`1 items,Func`2 selector)
   at Microsoft.CodeAnalysis.CodeRefactorings.PullMemberUp.PullMembersUpOptionsBuilder.BuildPullMembersUpOptions(INamedTypeSymbol destination,ImmutableArray`1 members)
   at async Microsoft.CodeAnalysis.MoveStaticMembers.MoveStaticMembersWithDialogCodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeActionWithOptions.GetOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorkerAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
````

**Expected Behavior**:

Move static members to another type is not suggested

**Actual Behavior**:

Move static members to another type is suggested, but fails

### PR DESCRIPTION
**Pull request by Soreloser2**
This changes the logic used for refactoring providers "Extract Class", "Pull Members Up", and "Move Static Members" to accept multiple members to be selected. In most cases this simply changes which members are pre-selected in the dialog box. It also makes selection around field declarations (which can declare multiple members, since each variable is considered a member) more intuitive, and follows the selection logic for other members like properties and methods.

Previously, in order to activate the refactoring associated with the first two on a declared field, the cursor needed to be present on the field identifier/variable name itself. When the cursor was on one of the modifier keywords, after the semicolon, or selecting the entire declaration line, the refactoring wouldn't activate.

Here's a few examples of cursor selections that will now trigger refactorings for Extract Class and Pull Members Up (when other requirements are met), but did not used to trigger:
```
pu$$blic static int Foo;
public static int Foo;$$
$public static int Foo;$
```

Since field declarations can actually declare multiple variables, we have logic which selects multiple members when multiple members could be considered selected. For example:
```
[||]public static int Foo, Bar;

public static int Fo[|o, Bar;|]

public static int Bar, Foo;[||]

public static int F[|oo;
public static int Bar|];
```
Will all trigger the refactoring on both members. Something like `public static int F[||]oo, Bar;` will only select `Foo` (and not `Bar`)

There are also tests added to the refactorings that are affected. This fixes #59470

### CODE REVIEW

File: src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs [hunk 1]
```diff
@@ -18,8 +19,30 @@ internal static async Task<SyntaxNode> GetSelectedDeclarationOrVariableAsync(Cod
...
+            var memberDeclaration = await context.TryGetRelevantNodeAsync<MemberDeclarationSyntax>().ConfigureAwait(false) as SyntaxNode;
+            if (memberDeclaration == null)
+            {
+                return await context.TryGetRelevantNodeAsync<VariableDeclaratorSyntax>().ConfigureAwait(false);
+            }
+            // since a FieldDeclarationSyntax doesn't have an associated Symbol (it can have multiple), we just get its variable declaration instead
+            if (memberDeclaration is FieldDeclarationSyntax fieldDeclaration)
+            {
+                // find the variable declarator closest to the start of the span
+                var (_, span, _) = context;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs:31]:
```suggestion
                var span = context.Span;
```

File: src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs [hunk 2]
```diff
@@ -18,8 +19,30 @@ internal static async Task<SyntaxNode> GetSelectedDeclarationOrVariableAsync(Cod
...
-            return await context.TryGetRelevantNodeAsync<MemberDeclarationSyntax>().ConfigureAwait(false) as SyntaxNode ??
-                await context.TryGetRelevantNodeAsync<VariableDeclaratorSyntax>().ConfigureAwait(false);
+            var memberDeclaration = await context.TryGetRelevantNodeAsync<MemberDeclarationSyntax>().ConfigureAwait(false) as SyntaxNode;
+            if (memberDeclaration == null)
+            {
+                return await context.TryGetRelevantNodeAsync<VariableDeclaratorSyntax>().ConfigureAwait(false);
+            }
+            // since a FieldDeclarationSyntax doesn't have an associated Symbol (it can have multiple), we just get its variable declaration instead
+            if (memberDeclaration is FieldDeclarationSyntax fieldDeclaration)
+            {
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs:29]:
```suggestion
            if (memberDeclaration is not FieldDeclarationSyntax fieldDeclaration)
                return memberDeclaration;
```

nit.  makes it easier to see what the special logic is doing if the non-special case is simple and handled immediately.

File: src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs [hunk 3]
```diff
@@ -18,8 +19,30 @@ internal static async Task<SyntaxNode> GetSelectedDeclarationOrVariableAsync(Cod
...
+                    var dist = Math.Min(Math.Abs(candidate.SpanStart - span.Start), Math.Abs(candidate.Span.End - span.Start));
+                    if (dist < leastDistance)
+                    {
+                        closestDeclarator = candidate;
+                        leastDistance = dist;
+                    }
+                }
+                return closestDeclarator;
+            }
+            return memberDeclaration;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs:45]: nit:

```suggestion
    return fieldDeclaration.Declaration.Variables.Min(
        v => Math.Min(Math.Abs(v.SpanStart - span.Start), Math.Abs(v.Span.End - span.Start));
```

File: src/Features/VisualBasic/Portable/CodeRefactorings/NodeSelectionHelpers.vb [hunk 4]
```diff
@@ -15,7 +16,20 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.CodeRefactorings
...
+                Dim closestDeclarator As ModifiedIdentifierSyntax = Nothing
+                Dim leastDistance = Integer.MaxValue
+                For Each candidate In fieldDeclaration.Declarators.SelectMany(Function(vds) vds.Names)
+                    Dim dist = Math.Min(Math.Abs(candidate.SpanStart - span.Start), Math.Abs(candidate.Span.End - span.Start))
+                    If (dist < leastDistance) Then
+                        closestDeclarator = candidate
+                        leastDistance = dist
+                    End If
+                Next
+                Return closestDeclarator
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/CodeRefactorings/NodeSelectionHelpers.vb:32]: similar feedback here.

File: src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs [hunk 5]
```diff
@@ -18,8 +19,30 @@ internal static async Task<SyntaxNode> GetSelectedDeclarationOrVariableAsync(Cod
             // MemberDeclaration: member that can be declared in type (those are the ones we can pull up) 
             // VariableDeclaratorSyntax: for fields the MemberDeclaration can actually represent multiple declarations, e.g. `int a = 0, b = 1;`.
             // ..Since the user might want to select & pull up only one of them (e.g. `int a = 0, [|b = 1|];` we also look for closest VariableDeclaratorSyntax.
-            return await context.TryGetRelevantNodeAsync<MemberDeclarationSyntax>().ConfigureAwait(false) as SyntaxNode ??
-                await context.TryGetRelevantNodeAsync<VariableDeclaratorSyntax>().ConfigureAwait(false);
+            var memberDeclaration = await context.TryGetRelevantNodeAsync<MemberDeclarationSyntax>().ConfigureAwait(false) as SyntaxNode;
+            if (memberDeclaration == null)
+            {
+                return await context.TryGetRelevantNodeAsync<VariableDeclaratorSyntax>().ConfigureAwait(false);
```
[the remark this answers is not in the document]
Comment (Soreloser2) [reply src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs:25]: Based on the previous code, which used a null coalescing operator to first look for a `MemberDeclarationSyntax` and then a `VariableDeclaratorSyntax`, I think we can. I haven't run tests without it/to check if its hit, but based on previous behavior, selecting the variable name of a declared field wouldn't find a `FieldDeclarationSyntax`, but would find the corresponding `VariableDeclaratorSyntax`. Otherwise field member selection wouldn't have worked at all, since the refactoring providers just take the result of this helper and attempt to get the declared symbol.

[the remark this answers is not in the document]
Comment (Soreloser2) [reply src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs:26]: After running a debug test, this branch is indeed hit when something like `public static int F$$oo;` is selected. The `TryGetRelevantNodeAsync` does not find a `MemberDeclarationSyntax` there, but it does find a `VariableDeclaratorSyntax`

File: src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs [hunk 6]
```diff
@@ -18,8 +20,22 @@ internal static async Task<SyntaxNode> GetSelectedDeclarationOrVariableAsync(Cod
...
+            if (memberDeclaration is not FieldDeclarationSyntax fieldDeclaration)
+            {
+                return memberDeclaration;
+            }
+
+            // since a FieldDeclarationSyntax doesn't have an associated Symbol (which we will want later), we want the variable declaration they ask for
+            // find the variable declarator closest to the start of the span
+            var span = context.Span;
+            return fieldDeclaration.Declaration.Variables.OrderBy(
+                v => Math.Min(Math.Abs(v.SpanStart - span.Start), Math.Abs(v.Span.End - span.Start))).First();
```
Comment (jasonmalinowski) [inline src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs:38]: Not this?

```suggestion
                v => Math.Min(Math.Abs(v.SpanStart - span.Start), Math.Abs(v.Span.End - span.End))).First();
```

At least it seems odd that we're not being symmetrical here?

File: src/Features/VisualBasic/Portable/CodeRefactorings/NodeSelectionHelpers.vb [hunk 7]
```diff
@@ -14,12 +15,19 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.CodeRefactorings
...
             ' Gets field variable declarations (not including the keywords like Public/Shared, etc), which are not methods
             Dim fieldDeclaration = Await context.TryGetRelevantNodeAsync(Of FieldDeclarationSyntax).ConfigureAwait(False)
-            If fieldDeclaration IsNot Nothing Then
-                Return fieldDeclaration
+            If fieldDeclaration Is Nothing Then
+                ' Gets the identifier + type of the field itself (ex. TestField As Integer), since it is nested in the variable declaration
+                ' And so the token's parent is not a variable declaration
+                Return Await context.TryGetRelevantNodeAsync(Of ModifiedIdentifierSyntax).ConfigureAwait(False)
+            Else
+                ' Since field declarations can contain multiple variables (each of which are a "member"), we need to find one to choose
```
Comment (jasonmalinowski) [inline src/Features/VisualBasic/Portable/CodeRefactorings/NodeSelectionHelpers.vb:23]: Do we need some tests added for the VB behavior?

File: src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs (hunk 6 above)
Comment (Soreloser2) [reply src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs:38]: I agree, however currently NodeSelectionHelpers must return a single variable declarator, so we need to choose one of the fields to return and act on. Perhaps we could alter the refactoring features that depend on this to accept multiple member nodes, but it seems out of the scope of this PR.

Currently I think choosing the closest field to the start of the selection is a good way to choose since in the case of selections over multiple, the first/leftmost field in the selection scope would be chosen. 

@CyrusNajmabadi @jasonmalinowski I'd be happy to discuss other potential ways to decide in edge cases related to the example above as well.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs:38]: > I agree, however currently NodeSelectionHelpers must return a single variable declarator,

In this case, i would consider this a failure condition.  THere isn't a single correct variable declarator to return, so it shouldn't return anything.

Comment (Soreloser2) [reply src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs:38]: > THere isn't a single correct variable declarator to return, so it shouldn't return anything.

What about the following cases:
 `$$public static int Foo, Bar;`
 `public static int Foo, Bar;$$`
In both, the selection doesn't specifically point to a particular field out of the two. Would these also be ambiguous and return nothing since we can't tell? If that is the case then we could avoid sorting by only giving a valid variable declarator if the selection span overlaps exactly one variable declarator span.

File: src/Features/VisualBasic/Portable/CodeRefactorings/NodeSelectionHelpers.vb (hunk 7 above)
Comment (jasonmalinowski) [reply src/Features/VisualBasic/Portable/CodeRefactorings/NodeSelectionHelpers.vb:23]: Ah, too bad we don't have direct tests of just the selection code anywhere.

File: src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs (hunk 6 above)
Comment (jasonmalinowski) [reply src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs:38]: > If that is the case then we could avoid sorting by only giving a valid variable declarator if the selection span overlaps exactly one variable declarator span.

That seems reasonable to me.

File: src/Tools/ExternalAccess/OmniSharp/Internal/ExtractClass/OmniSharpExtractClassOptionsService.cs [hunk 8]
```diff
@@ -25,9 +27,9 @@ public OmniSharpExtractClassOptionsService(IOmniSharpExtractClassOptionsService
             _omniSharpExtractClassOptionsService = omniSharpExtractClassOptionsService;
         }
 
-        public async Task<ExtractClassOptions?> GetExtractClassOptionsAsync(Document document, INamedTypeSymbol originalType, ISymbol? selectedMember, CancellationToken cancellationToken)
+        public async Task<ExtractClassOptions?> GetExtractClassOptionsAsync(Document document, INamedTypeSymbol originalType, ImmutableArray<ISymbol> selectedMembers, CancellationToken cancellationToken)
```
Comment (333fred) [inline src/Tools/ExternalAccess/OmniSharp/Internal/ExtractClass/OmniSharpExtractClassOptionsService.cs:30]: I'm not sure why this is changed if it's not actually going to use anything more than the first item?

File: src/Features/VisualBasic/Portable/CodeRefactorings/NodeSelectionHelpers.vb [hunk 9]
```diff
@@ -2,24 +2,49 @@
...
+                    ' Field declarations can contain multiple variables (each of which are a "member")
+                    Return fieldDeclaration.Declarators.SelectMany(Function(vds) vds.Names).Cast(Of SyntaxNode).AsImmutable()
+                End If
+            Else
+                ' if the span is non-empty, then we get potentially multiple members
+                ' Note: even though this method handles the empty span case, we don't use it because it doesn't correctly
+                ' pick up on keywords before the declaration, such as "public static int".
+                ' We could potentially use it for every case if that behavior changes
+                Dim tree = Await doc.GetSyntaxTreeAsync(cancellationToken).ConfigureAwait(False)
+                Return Await VisualBasicSelectedMembers.Instance.GetSelectedMembersAsync(tree, span, True, cancellationToken).ConfigureAwait(False)
```
Comment (Soreloser2) [inline src/Features/VisualBasic/Portable/CodeRefactorings/NodeSelectionHelpers.vb:46]: The reason we do separate things for different spans is because for nonempty spans, `GetRelevantNodesAsync` will get the largest node that completely encompasses the span and will not get smaller ones. For example, if we selected multiple members in a class, `GetRelevantNodesAsync` gets the class declaration instead of the selected members. However, the `AbstractSelectedMembers` logic will only activate on an empty span if the span is on the identifier name (and not any of the keywords, which we want to include as well). It may be possible to change `AbstractSelectedMembers` to get nodes when the keyword is selected too, but this would end up probably being logic very similar to `GetRelevantNodesAsync`, and would also introduce a feature change in the encapsulate fields/properties and generate method refactorings as well.

File: src/Tools/ExternalAccess/OmniSharp/Internal/ExtractClass/OmniSharpExtractClassOptionsService.cs (hunk 8 above)
Comment (333fred) [reply src/Tools/ExternalAccess/OmniSharp/Internal/ExtractClass/OmniSharpExtractClassOptionsService.cs:30]: `IOmniSharpExtractClassOptionsService` is an internal API. The contract is that O# needs to react when we update it, and either Joey or myself signs off to indicate that we've seen the notification of the breaking change.

Comment (Soreloser2) [reply src/Tools/ExternalAccess/OmniSharp/Internal/ExtractClass/OmniSharpExtractClassOptionsService.cs:30]: Ok, I'll make the change to the interface as well then. Would there need to be anything done to notify/check with O# before that change is made?

Comment (333fred) [reply src/Tools/ExternalAccess/OmniSharp/Internal/ExtractClass/OmniSharpExtractClassOptionsService.cs:30]: > Would there need to be anything done to notify/check with O# before that change is made?

That's just notifying @JoeRobich and myself :).

File: src/Features/Core/Portable/ExtractClass/AbstractExtractClassRefactoringProvider.cs [hunk 10]
```diff
@@ -55,28 +58,38 @@ public override async Task ComputeRefactoringsAsync(CodeRefactoringContext conte
...
-            var selectedMember = semanticModel.GetDeclaredSymbol(selectedMemberNode, cancellationToken);
-            if (selectedMember is null || selectedMember.ContainingType is null)
+            var memberNodeSymbolPairs = selectedMemberNodes
+                .Select(m => (node: m, symbol: semanticModel.GetDeclaredSymbol(m, cancellationToken)))
+                // Use same logic as pull members up for determining if a selected member
+                // is valid to be moved into a base
+                .Where(pair => pair.symbol != null && MemberAndDestinationValidator.IsMemberValid(pair.symbol))
+                .AsImmutable();
+
+            var selectedMembers = memberNodeSymbolPairs.SelectAsArray(pair => pair.symbol!);
```
Comment (Soreloser2) [inline src/Features/Core/Portable/ExtractClass/AbstractExtractClassRefactoringProvider.cs:76]: We pair each node to its symbol because if we select multiple member nodes but only a subset of them are valid, we want to make sure we take all the valid ones (as opposed to failing to refactor, or keeping the incorrect nodes). This behavior and some other behavior such as getting the containing type is mostly similar across the other two other member refactoring services as well. It could possibly be refactored into common method(s) but I'm not sure where it would go.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SelectedMembers/AbstractSelectedMembers.cs [hunk 11]
```diff
@@ -28,13 +29,19 @@ internal abstract class AbstractSelectedMembers<
...
         protected abstract SyntaxList<TMemberDeclarationSyntax> GetMembers(TTypeDeclarationSyntax containingType);
-        protected abstract IEnumerable<TVariableSyntax> GetAllDeclarators(TFieldDeclarationSyntax field);
-
-        protected abstract SyntaxToken GetVariableIdentifier(TVariableSyntax declarator);
-        protected abstract SyntaxToken GetPropertyIdentifier(TPropertyDeclarationSyntax declarator);
+        protected abstract IEnumerable<(SyntaxToken identifier, SyntaxNode declaration)> GetDeclaratorsAndIdentifiers(TMemberDeclarationSyntax member);
 
         public async Task<ImmutableArray<SyntaxNode>> GetSelectedFieldsAndPropertiesAsync(
             SyntaxTree tree, TextSpan textSpan, bool allowPartialSelection, CancellationToken cancellationToken)
+                => await GetSelectedMembersAsync(tree, textSpan, allowPartialSelection, IsFieldOrProperty, cancellationToken).ConfigureAwait(false);
```
Comment (Soreloser2) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SelectedMembers/AbstractSelectedMembers.cs:36]: Refactor the current logic here to use a common method, which can take a filter if we only want certain members

File: src/Tools/ExternalAccess/OmniSharp/ExtractClass/IOmniSharpExtractClassOptionsService.cs [hunk 12]
```diff
@@ -9,7 +9,7 @@ namespace Microsoft.CodeAnalysis.ExternalAccess.OmniSharp.ExtractClass
 {
     internal interface IOmniSharpExtractClassOptionsService
     {
-        Task<OmniSharpExtractClassOptions?> GetExtractClassOptionsAsync(Document document, INamedTypeSymbol originalType, ISymbol? selectedMember);
+        Task<OmniSharpExtractClassOptions?> GetExtractClassOptionsAsync(Document document, INamedTypeSymbol originalType, ImmutableArray<ISymbol> selectedMember);
```
Comment (333fred) [inline src/Tools/ExternalAccess/OmniSharp/ExtractClass/IOmniSharpExtractClassOptionsService.cs:12]:
```suggestion
        Task<OmniSharpExtractClassOptions?> GetExtractClassOptionsAsync(Document document, INamedTypeSymbol originalType, ImmutableArray<ISymbol> selectedMembers);
```

**Review by 333fred — APPROVED** [review]
O# changes LGTM, aside from a small typo.

File: src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs [hunk 13]
```diff
@@ -4,22 +4,63 @@
...
+                    var varDeclarator = await context.TryGetRelevantNodeAsync<VariableDeclaratorSyntax>().ConfigureAwait(false);
+                    if (varDeclarator == null)
+                    {
+                        return ImmutableArray<SyntaxNode>.Empty;
+                    }
+                    else
+                    {
+
+                        return ImmutableArray.Create(varDeclarator as SyntaxNode);
+                    }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs:43]: nit:

```suggestion
                    var varDeclarator = await context.TryGetRelevantNodeAsync<VariableDeclaratorSyntax>().ConfigureAwait(false);
                    return varDeclarator == null
                        ? ImmutableArray<SyntaxNode>.Empty
                        : ImmutableArray.Create<SyntaxNode>(varDeclarator);
```

File: src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs [hunk 14]
```diff
@@ -4,22 +4,63 @@
...
+                }
+                else
+                {
+                    return memberDeclaration switch
+                    {
+                        FieldDeclarationSyntax fieldDeclaration => fieldDeclaration.Declaration.Variables.Cast<SyntaxNode>().AsImmutable(),
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs:49]:
```suggestion
                        FieldDeclarationSyntax fieldDeclaration => fieldDeclaration.Declaration.Variables.CastArray<SyntaxNode>(),
```

File: src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs [hunk 15]
```diff
@@ -4,22 +4,63 @@
...
+                        EventFieldDeclarationSyntax eventFieldDeclaration => eventFieldDeclaration.Declaration.Variables.Cast<SyntaxNode>().AsImmutable(),
+                        _ => ImmutableArray.Create(memberDeclaration as SyntaxNode),
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs:51]:
```suggestion
                        EventFieldDeclarationSyntax eventFieldDeclaration => eventFieldDeclaration.Declaration.Variables.CastArray<SyntaxNode>(),
                        _ => ImmutableArray.Create<SyntaxNode>(memberDeclaration),
```

Note: we never use `as` in our codebase, unless it is for a case where the type-cast coudl fail and we then *will* check it for null.

File: src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs [hunk 16]
```diff
@@ -4,22 +4,63 @@
...
+                }
+            }
+            else
+            {
+                // if the span is non-empty, then we get potentially multiple members
+                // Note: even though this method handles the empty span case, we don't use it because it doesn't correctly
+                // pick up on keywords before the declaration, such as "public static int".
+                // We could potentially use it for every case if that behavior changes
+                var tree = await doc.GetSyntaxTreeAsync(cancellationToken).ConfigureAwait(false);
+                return await CSharpSelectedMembers.Instance.GetSelectedMembersAsync(tree, span, true, cancellationToken).ConfigureAwait(false);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs:62]: named parameter for `true` please :)

File: src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs [hunk 17]
```diff
@@ -4,22 +4,63 @@
...
-        internal static async Task<SyntaxNode> GetSelectedDeclarationOrVariableAsync(CodeRefactoringContext context)
+        internal static async Task<ImmutableArray<SyntaxNode>> GetSelectedDeclarationsOrVariablesAsync(CodeRefactoringContext context)
         {
-            // Consider:
-            // MemberDeclaration: member that can be declared in type (those are the ones we can pull up) 
-            // VariableDeclaratorSyntax: for fields the MemberDeclaration can actually represent multiple declarations, e.g. `int a = 0, b = 1;`.
-            // ..Since the user might want to select & pull up only one of them (e.g. `int a = 0, [|b = 1|];` we also look for closest VariableDeclaratorSyntax.
-            return await context.TryGetRelevantNodeAsync<MemberDeclarationSyntax>().ConfigureAwait(false) as SyntaxNode ??
-                await context.TryGetRelevantNodeAsync<VariableDeclaratorSyntax>().ConfigureAwait(false);
+            var (doc, span, cancellationToken) = context;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeRefactorings/NodeSelectionHelpers.cs:22]:
```suggestion
            var (document, span, cancellationToken) = context;
```

In general we do not abbreviate unless it's a super common case (like Xml) or ht e name is just excessively long.  For a simpel name like `document` it keeps things nicely consistent to just use that name everywhere.

File: src/Features/Core/Portable/ExtractClass/AbstractExtractClassRefactoringProvider.cs [hunk 18]
```diff
@@ -55,28 +58,38 @@ public override async Task ComputeRefactoringsAsync(CodeRefactoringContext conte
...
             var (document, span, cancellationToken) = context;
             var semanticModel = await document.GetRequiredSemanticModelAsync(cancellationToken).ConfigureAwait(false);
-            var selectedMember = semanticModel.GetDeclaredSymbol(selectedMemberNode, cancellationToken);
-            if (selectedMember is null || selectedMember.ContainingType is null)
+            var memberNodeSymbolPairs = selectedMemberNodes
+                .Select(m => (node: m, symbol: semanticModel.GetDeclaredSymbol(m, cancellationToken)))
+                // Use same logic as pull members up for determining if a selected member
+                // is valid to be moved into a base
+                .Where(pair => pair.symbol != null && MemberAndDestinationValidator.IsMemberValid(pair.symbol))
+                .AsImmutable();
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ExtractClass/AbstractExtractClassRefactoringProvider.cs:74]:
```suggestion
                .Select(m => (node: m, symbol: semanticModel.GetRequiredDeclaredSymbol(m, cancellationToken)))
                // Use same logic as pull members up for determining if a selected member
                // is valid to be moved into a base
                .WhereAsArray(pair => MemberAndDestinationValidator.IsMemberValid(pair.symbol);
```

File: src/Features/Core/Portable/ExtractClass/AbstractExtractClassRefactoringProvider.cs [hunk 19]
```diff
@@ -55,28 +58,38 @@ public override async Task ComputeRefactoringsAsync(CodeRefactoringContext conte
...
+
+            var selectedMembers = memberNodeSymbolPairs.SelectAsArray(pair => pair.symbol!);
+
+            if (selectedMembers.IsEmpty)
             {
                 return null;
             }
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ExtractClass/AbstractExtractClassRefactoringProvider.cs:81]:
```suggestion
            if (memberNodeSymbolPairs.IsEmpty)
                return null;
            
            var selectedMembers = memberNodeSymbolPairs.SelectAsArray(pair => pair.symbol!);
```

File: src/Features/Core/Portable/ExtractClass/AbstractExtractClassRefactoringProvider.cs [hunk 20]
```diff
@@ -55,28 +58,38 @@ public override async Task ComputeRefactoringsAsync(CodeRefactoringContext conte
...
 
-            // Use same logic as pull members up for determining if a selected member
-            // is valid to be moved into a base
-            if (!MemberAndDestinationValidator.IsMemberValid(selectedMember))
+            var containingType = selectedMembers.First().ContainingType;
+            if (containingType == null || selectedMembers.Any(m => m.ContainingType != containingType))
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ExtractClass/AbstractExtractClassRefactoringProvider.cs:84]:
```suggestion
            var containingType = selectedMembers.First().ContainingType;
            Contract.ThrowIfNull(containingType);
            if (selectedMembers.Any(m => !containingType.Equals(m.ContainingType)))
```

Symbols cannot be tested for equality using reference-equality.  the compiler is free to create other instances that are .Equals but are not `==`.

File: src/Features/Core/Portable/ExtractClass/AbstractExtractClassRefactoringProvider.cs [hunk 21]
```diff
@@ -87,14 +100,15 @@ public override async Task ComputeRefactoringsAsync(CodeRefactoringContext conte
             }
 
             var syntaxFacts = document.GetRequiredLanguageService<ISyntaxFactsService>();
-            var containingTypeDeclarationNode = selectedMemberNode.FirstAncestorOrSelf<SyntaxNode>(syntaxFacts.IsTypeDeclaration);
+            var containingTypeDeclarationNode = selectedMemberNodes.First().FirstAncestorOrSelf<SyntaxNode>(syntaxFacts.IsTypeDeclaration);
             Contract.ThrowIfNull(containingTypeDeclarationNode);
+            if (selectedMemberNodes.Any(m => m.FirstAncestorOrSelf<SyntaxNode>(syntaxFacts.IsTypeDeclaration) != containingTypeDeclarationNode))
+            {
+                return null;
+            }
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ExtractClass/AbstractExtractClassRefactoringProvider.cs:108]: since you are already checking that htey're syntactically parented by the same type decl, you can skip the check above htat checks that they're semantically parented by the same INamedTYpeSymbol

File: src/Features/Core/Portable/MoveStaticMembers/AbstractMoveStaticMembersRefactoringProvider.cs [hunk 22]
```diff
@@ -26,8 +28,8 @@ public override async Task ComputeRefactoringsAsync(CodeRefactoringContext conte
                 return;
             }
 
-            var memberDeclaration = await GetSelectedNodeAsync(context).ConfigureAwait(false);
-            if (memberDeclaration == null)
+            var selectedMemberNodes = await GetSelectedNodesAsync(context).ConfigureAwait(false);
+            if (selectedMemberNodes == null)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MoveStaticMembers/AbstractMoveStaticMembersRefactoringProvider.cs:32]:
```suggestion
            if (selectedMemberNodes.IsDefaultOrEmpty)
```

(or .IsEmpty).  Just chekcing `== null` is only checking if it's a default ImmutableArrary.  I assume if it's empty you want to bail out here?

File: src/Features/Core/Portable/MoveStaticMembers/AbstractMoveStaticMembersRefactoringProvider.cs [hunk 23]
```diff
@@ -38,26 +40,32 @@ public override async Task ComputeRefactoringsAsync(CodeRefactoringContext conte
...
             }
 
-            var selectedType = semanticModel.GetEnclosingNamedType(span.Start, cancellationToken);
-            if (selectedType == null)
+            var memberNodeSymbolPairs = selectedMemberNodes
+                .Select(m => (node: m, symbol: semanticModel.GetDeclaredSymbol(m, cancellationToken)))
+                // Use same logic as pull members up for determining if a selected member
+                // is valid to be moved into a base
+                .Where(pair => pair.symbol != null && MemberAndDestinationValidator.IsMemberValid(pair.symbol) && pair.symbol.IsStatic)
+                .AsImmutable();
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MoveStaticMembers/AbstractMoveStaticMembersRefactoringProvider.cs:48]:
```suggestion
                .Select(m => (node: m, symbol: semanticModel.GetRequiredDeclaredSymbol(m, cancellationToken)))
                // Use same logic as pull members up for determining if a selected member
                // is valid to be moved into a base
                .WhereAsArray(pair => MemberAndDestinationValidator.IsMemberValid(pair.symbol) && pair.symbol.IsStatic);
```

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/MoveStaticMembers/AbstractMoveStaticMembersRefactoringProvider.cs:48]: Note: i believe thre's also a .SelectAsArray which takes a predicate, merging this into just one call that is cheaper and faster.

File: src/Features/Core/Portable/MoveStaticMembers/AbstractMoveStaticMembersRefactoringProvider.cs [hunk 24]
```diff
@@ -38,26 +40,32 @@ public override async Task ComputeRefactoringsAsync(CodeRefactoringContext conte
...
+
+            var selectedMembers = memberNodeSymbolPairs.SelectAsArray(pair => pair.symbol!);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MoveStaticMembers/AbstractMoveStaticMembersRefactoringProvider.cs:50]: same feedback as the prior class on how to tweak the rest of this method :)

File: src/Features/Core/Portable/PullMemberUp/AbstractPullMemberUpRefactoringProvider.cs [hunk 25]
```diff
@@ -39,50 +40,66 @@ public override async Task ComputeRefactoringsAsync(CodeRefactoringContext conte
...
 
-            var selectedMemberNode = await GetSelectedNodeAsync(context).ConfigureAwait(false);
-            if (selectedMemberNode == null)
+            var selectedMemberNodes = await GetSelectedNodesAsync(context).ConfigureAwait(false);
+            if (selectedMemberNodes.IsEmpty)
             {
                 return;
             }
 
             var semanticModel = await document.GetRequiredSemanticModelAsync(cancellationToken).ConfigureAwait(false);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/PullMemberUp/AbstractPullMemberUpRefactoringProvider.cs:49]: same tweaks to apply here.

File: src/Features/Core/Portable/PullMemberUp/AbstractPullMemberUpRefactoringProvider.cs [hunk 26]
```diff
@@ -39,50 +40,66 @@ public override async Task ComputeRefactoringsAsync(CodeRefactoringContext conte
...
 
-            var allActions = allDestinations.Select(destination => MembersPuller.TryComputeCodeAction(document, selectedMember, destination, context.Options))
-                .WhereNotNull().Concat(new PullMemberUpWithDialogCodeAction(document, selectedMember, _service, context.Options))
+            var allActions = allDestinations.Select(destination => MembersPuller.TryComputeCodeAction(document, selectedMembers, destination, context.Options))
+                .WhereNotNull().Concat(new PullMemberUpWithDialogCodeAction(document, selectedMembers, _service, context.Options))
                 .ToImmutableArray();
 
+            var title = selectedMembers.IsSingle() ?
+                string.Format(FeaturesResources.Pull_0_up, selectedMembers.Single().ToNameDisplayString()) :
+                FeaturesResources.Pull_selected_members_up;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/PullMemberUp/AbstractPullMemberUpRefactoringProvider.cs:87]:
```suggestion
            var title = selectedMembers.IsSingle()
                ? string.Format(FeaturesResources.Pull_0_up, selectedMembers.Single().ToNameDisplayString())
                : FeaturesResources.Pull_selected_members_up;
```

Allows the `?:` to align, and makes it very easy to immediately see that this is a conditional expr and what the cases will be.

File: src/Features/Core/Portable/PullMemberUp/MembersPuller.cs [hunk 27]
```diff
@@ -36,18 +36,24 @@ internal static class MembersPuller
...
             if (result.PullUpOperationNeedsToDoExtraChanges ||
-                IsSelectedMemberDeclarationAlreadyInDestination(selectedMember, destination))
+                selectedMembers.Any(
+                    static (m, destination) => IsSelectedMemberDeclarationAlreadyInDestination(m, destination), destination))
             {
                 return null;
             }
 
-            var title = string.Format(FeaturesResources.Pull_0_up_to_1, selectedMember.Name, result.Destination.Name);
+            var title = selectedMembers.IsSingle() ?
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/PullMemberUp/MembersPuller.cs:53]: same comment about formatting here.

File: src/Features/VisualBasic/Portable/CodeRefactorings/NodeSelectionHelpers.vb [hunk 28]
```diff
@@ -2,24 +2,49 @@
...
     Friend Module NodeSelectionHelpers
-        Friend Async Function GetSelectedMemberDeclarationAsync(context As CodeRefactoringContext) As Task(Of SyntaxNode)
-            Dim methodMember = Await context.TryGetRelevantNodeAsync(Of MethodBaseSyntax)().ConfigureAwait(False)
-            If methodMember IsNot Nothing Then
-                Return methodMember
+        Friend Async Function GetSelectedMemberDeclarationAsync(context As CodeRefactoringContext) As Task(Of ImmutableArray(Of SyntaxNode))
+            Dim doc As Document = Nothing
+            Dim span As TextSpan = Nothing
+            Dim cancellationToken As CancellationToken = Nothing
+            context.Deconstruct(doc, span, cancellationToken)
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/CodeRefactorings/NodeSelectionHelpers.vb:18]:
```suggestion
            Dim doc = context.Document;
            Dim span = context.Span;
            Dim cancellationToken = context.CancellationToken
```

VB basically doesn't benefit at all from deconstruction.  so better to just use the idiomatic assignment form above.

File: src/Features/VisualBasic/Portable/CodeRefactorings/NodeSelectionHelpers.vb [hunk 29]
```diff
@@ -2,24 +2,49 @@
...
+                ' Gets field variable declarations (not including the keywords like Public/Shared, etc), which are not methods
+                Dim fieldDeclaration = Await context.TryGetRelevantNodeAsync(Of FieldDeclarationSyntax).ConfigureAwait(False)
+                If fieldDeclaration Is Nothing Then
+                    ' Gets the identifier + type of the field itself (ex. TestField As Integer), since it is nested in the variable declaration
+                    ' And so the token's parent is not a variable declaration
+                    Dim modifiedIdentifier = Await context.TryGetRelevantNodeAsync(Of ModifiedIdentifierSyntax).ConfigureAwait(False)
+                    If modifiedIdentifier Is Nothing Then
+                        Return ImmutableArray(Of SyntaxNode).Empty
+                    Else
+                        Return ImmutableArray.Create(DirectCast(modifiedIdentifier, SyntaxNode))
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/CodeRefactorings/NodeSelectionHelpers.vb:34]:
```suggestion
                        Return ImmutableArray.Create(of SyntaxNode)(modifiedIdentifier)
```

File: src/Features/VisualBasic/Portable/CodeRefactorings/NodeSelectionHelpers.vb [hunk 30]
```diff
@@ -2,24 +2,49 @@
...
+                    ' Field declarations can contain multiple variables (each of which are a "member")
+                    Return fieldDeclaration.Declarators.SelectMany(Function(vds) vds.Names).Cast(Of SyntaxNode).AsImmutable()
+                End If
+            Else
+                ' if the span is non-empty, then we get potentially multiple members
+                ' Note: even though this method handles the empty span case, we don't use it because it doesn't correctly
+                ' pick up on keywords before the declaration, such as "public static int".
+                ' We could potentially use it for every case if that behavior changes
+                Dim tree = Await doc.GetSyntaxTreeAsync(cancellationToken).ConfigureAwait(False)
+                Return Await VisualBasicSelectedMembers.Instance.GetSelectedMembersAsync(tree, span, True, cancellationToken).ConfigureAwait(False)
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/CodeRefactorings/NodeSelectionHelpers.vb:46]: named parameter for 'true'.

File: src/VisualStudio/Core/Def/ExtractClass/VisualStudioExtractClassOptionsService.cs [hunk 31]
```diff
@@ -60,8 +60,8 @@ internal class VisualStudioExtractClassOptionsService : IExtractClassOptionsServ
                 .SelectAsArray(member =>
                     new PullMemberUpSymbolViewModel(member, _glyphService)
                     {
-                        // The member user selected will be checked at the beginning.
-                        IsChecked = SymbolEquivalenceComparer.Instance.Equals(selectedMember, member),
+                        // The member(s) user selected will be checked at the beginning.
+                        IsChecked = selectedMembers.Any(static (selectedMember, member) => SymbolEquivalenceComparer.Instance.Equals(selectedMember, member), member),
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Def/ExtractClass/VisualStudioExtractClassOptionsService.cs:64]:
```suggestion
                        IsChecked = selectedMembers.Any(SymbolEquivalenceComparer.Instance.Equals, member),
```

nit:

Comment (CyrusNajmabadi) [reply src/VisualStudio/Core/Def/ExtractClass/VisualStudioExtractClassOptionsService.cs:64]: (applies to the other places you wrote the same line below).

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SelectedMembers/CSharpSelectedMembers.cs [hunk 32]
```diff
@@ -23,16 +26,19 @@ private CSharpSelectedMembers()
         {
         }
 
-        protected override IEnumerable<VariableDeclaratorSyntax> GetAllDeclarators(FieldDeclarationSyntax field)
-            => field.Declaration.Variables;
+        protected override IEnumerable<(SyntaxToken identifier, SyntaxNode declaration)> GetDeclaratorsAndIdentifiers(MemberDeclarationSyntax member)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SelectedMembers/CSharpSelectedMembers.cs:29]: nit: woudl prefer this as an ImmutableArray, but i don't feel strongly.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SelectedMembers/AbstractSelectedMembers.cs [hunk 33]
```diff
@@ -28,13 +29,19 @@ internal abstract class AbstractSelectedMembers<
         where TVariableSyntax : SyntaxNode
     {
         protected abstract SyntaxList<TMemberDeclarationSyntax> GetMembers(TTypeDeclarationSyntax containingType);
-        protected abstract IEnumerable<TVariableSyntax> GetAllDeclarators(TFieldDeclarationSyntax field);
-
-        protected abstract SyntaxToken GetVariableIdentifier(TVariableSyntax declarator);
-        protected abstract SyntaxToken GetPropertyIdentifier(TPropertyDeclarationSyntax declarator);
+        protected abstract IEnumerable<(SyntaxToken identifier, SyntaxNode declaration)> GetDeclaratorsAndIdentifiers(TMemberDeclarationSyntax member);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SelectedMembers/AbstractSelectedMembers.cs:32]: nit: method name is 'get declarator and identifier' but returns a tuple in reverse order.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SelectedMembers/AbstractSelectedMembers.cs (hunk 11 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SelectedMembers/AbstractSelectedMembers.cs:36]:
```suggestion
        public Task<ImmutableArray<SyntaxNode>> GetSelectedFieldsAndPropertiesAsync(
            SyntaxTree tree, TextSpan textSpan, bool allowPartialSelection, CancellationToken cancellationToken)
                => GetSelectedMembersAsync(tree, textSpan, allowPartialSelection, IsFieldOrProperty, cancellationToken);
```

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SelectedMembers/AbstractSelectedMembers.cs [hunk 34]
```diff
@@ -81,29 +89,20 @@ internal abstract class AbstractSelectedMembers<
             for (var i = fieldIndex; i < members.Count; i++)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SelectedMembers/AbstractSelectedMembers.cs:89]: i can't select the line above this, but it should be:

```c#
using var _ = ArrayBuilder<SyntaxNode>.GetInstance(out var selectedMembers);

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SelectedMembers/AbstractSelectedMembers.cs [hunk 35]
```diff
@@ -81,29 +89,20 @@ internal abstract class AbstractSelectedMembers<
...
             {
                 var member = members[i];
-                AddSelectedFieldOrPropertyDeclarations(member);
+                AddSelectedMemberDeclarations(member, membersToKeep);
             }
 
             return selectedMembers.ToImmutableAndFree();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SelectedMembers/AbstractSelectedMembers.cs:95]:
```suggestion
            return selectedMembers.ToImmutable();
```

this ensures we return teh pooled arary even if we end up cancelling the work we do.

File: src/Features/Core/Portable/ExtractClass/AbstractExtractClassRefactoringProvider.cs [hunk 36]
```diff
@@ -55,28 +58,36 @@ public override async Task ComputeRefactoringsAsync(CodeRefactoringContext conte
...
-            var selectedMember = semanticModel.GetDeclaredSymbol(selectedMemberNode, cancellationToken);
-            if (selectedMember is null || selectedMember.ContainingType is null)
-            {
-                return null;
-            }
+            var memberNodeSymbolPairs = selectedMemberNodes
+                .SelectAsArray(m => (node: m, symbol: semanticModel.GetRequiredDeclaredSymbol(m, cancellationToken)))
+                // Use same logic as pull members up for determining if a selected member
+                // is valid to be moved into a base
+                .WhereAsArray(pair => MemberAndDestinationValidator.IsMemberValid(pair.symbol));
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ExtractClass/AbstractExtractClassRefactoringProvider.cs:73]: is it possible to use

```ImmutableArray<TResult> SelectAsArray<TItem, TResult>(this ImmutableArray<TItem> array, Func<TItem, bool> predicate, Func<TItem, TResult> selector)``` here?

that way we don't make an intermediate array?

File: src/Features/Core/Portable/MoveStaticMembers/AbstractMoveStaticMembersRefactoringProvider.cs [hunk 37]
```diff
@@ -38,26 +41,34 @@ public override async Task ComputeRefactoringsAsync(CodeRefactoringContext conte
                 return;
             }
 
-            var selectedType = semanticModel.GetEnclosingNamedType(span.Start, cancellationToken);
-            if (selectedType == null)
+            var memberNodeSymbolPairs = selectedMemberNodes
+                .SelectAsArray(m => (node: m, symbol: semanticModel.GetRequiredDeclaredSymbol(m, cancellationToken)))
+                // Use same logic as pull members up for determining if a selected member
+                // is valid to be moved into a base
+                .WhereAsArray(pair => MemberAndDestinationValidator.IsMemberValid(pair.symbol) && pair.symbol.IsStatic);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MoveStaticMembers/AbstractMoveStaticMembersRefactoringProvider.cs:48]: same comment.

File: src/Features/Core/Portable/ExtractClass/AbstractExtractClassRefactoringProvider.cs (hunk 36 above)
Comment (Soreloser2) [reply src/Features/Core/Portable/ExtractClass/AbstractExtractClassRefactoringProvider.cs:73]: This overload applies the filter first, then applies the map. Since our filter criteria depends on the symbol being created in the map, I don't think we could do it without essentially getting the symbol twice.

File: src/Features/Core/Portable/PullMemberUp/AbstractPullMemberUpRefactoringProvider.cs [hunk 38]
```diff
@@ -39,50 +40,69 @@ public override async Task ComputeRefactoringsAsync(CodeRefactoringContext conte
...
             {
                 return;
             }
 
             var semanticModel = await document.GetRequiredSemanticModelAsync(cancellationToken).ConfigureAwait(false);
-            var selectedMember = semanticModel.GetDeclaredSymbol(selectedMemberNode);
-            if (selectedMember == null || selectedMember.ContainingType == null)
+            var memberNodeSymbolPairs = selectedMemberNodes
+                .SelectAsArray(m => (node: m, symbol: semanticModel.GetRequiredDeclaredSymbol(m, cancellationToken)))
+                .WhereAsArray(pair => MemberAndDestinationValidator.IsMemberValid(pair.symbol));
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/PullMemberUp/AbstractPullMemberUpRefactoringProvider.cs:52]: same comment as before.

File: src/Tools/ExternalAccess/OmniSharp/ExtractClass/IOmniSharpExtractClassOptionsService.cs [hunk 39]
```diff
@@ -9,7 +9,7 @@ namespace Microsoft.CodeAnalysis.ExternalAccess.OmniSharp.ExtractClass
 {
     internal interface IOmniSharpExtractClassOptionsService
     {
-        Task<OmniSharpExtractClassOptions?> GetExtractClassOptionsAsync(Document document, INamedTypeSymbol originalType, ISymbol? selectedMember);
+        Task<OmniSharpExtractClassOptions?> GetExtractClassOptionsAsync(Document document, INamedTypeSymbol originalType, ImmutableArray<ISymbol> selectedMembers);
```
Comment (CyrusNajmabadi) [inline src/Tools/ExternalAccess/OmniSharp/ExtractClass/IOmniSharpExtractClassOptionsService.cs:12]: i don't think this is safe to do.  this will break omnisharp.  Right @333fred ?  

happy to explain more offline.

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/Tools/ExternalAccess/OmniSharp/ExtractClass/IOmniSharpExtractClassOptionsService.cs (hunk 39 above)
Comment (Soreloser2) [reply src/Tools/ExternalAccess/OmniSharp/ExtractClass/IOmniSharpExtractClassOptionsService.cs:12]: See Fred's comments earlier in this thread

Comment (CyrusNajmabadi) [reply src/Tools/ExternalAccess/OmniSharp/ExtractClass/IOmniSharpExtractClassOptionsService.cs:12]: n/m. @Soreloser2 mentioned you prefer this approach @333fred

Comment (333fred) [reply src/Tools/ExternalAccess/OmniSharp/ExtractClass/IOmniSharpExtractClassOptionsService.cs:12]: Yup. O# is already converting a list to a single member for this, it will simplify the code.

**Comment by Soreloser2** [comment]
just pinging @333fred @JoeRobich one last time to say that the changes are now in main.
