### PR TITLE
Remove incorrect assertion

### LINKED ISSUE #37783: Debug assert firing in SpillSequenceSpiller.cs
**Version Used**: 

Debug build of release/dev16.2 branch.

**Steps to Reproduce**:

Due to the issue reported [here](https://github.com/dotnet/roslyn/issues/37456) I had to build and run my first debug version of the Roslyn compiler. Now when building our .net core 2.2 web application project, an assert on row 1090 in [SpillSequenceSpiller.cs](https://github.com/dotnet/roslyn/blob/release/dev16.2/src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs#L1090) will fire repeatedly (>10-15 times).

**Expected Behavior**:

I would have expected either

1) That no debug assert would fire during a build
2) Or that some annotation (code comment or debug.assert message) would provide any hint on whether there is something wrong in my code or Roslyn code

**Actual Behavior**:

The assert fires. 

Trying blame on _SpillSequenceSpiller.cs_ does not seem to show any intent to why this assert was introduced. Build will complete successfully, and the application seems to work fine as well. 

Perhaps the assert is unnecessary? It was easy to just ignore it, but since it was the only assert firing during build I'm curious on why.

Ping @tmat seems to have touched the code five years ago, perhaps you know if this assert should fire, remove it or help annotate it?

### PR DESCRIPTION
**Pull request by gafter**
Fixes #37783

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a review from the compiler team for this tiny bug fix?

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a second review from the compiler team for this tiny bug fix?

**Comment by gafter** [comment]
@RikkiGibson @cston In light of another issue, I've simplified and generalized the fix for this bug.  Could you please have another look?

File: src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs [hunk 1]
```diff
@@ -839,6 +839,12 @@ public override BoundNode VisitConditionalOperator(BoundConditionalOperator node
 
         public override BoundNode VisitConversion(BoundConversion node)
         {
+            if (node.ConversionKind == ConversionKind.AnonymousFunction && node.Type.IsExpressionTree())
+            {
+                // Expression trees do not contain any code that requires spilling.
+                return node;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs]: >return node; [](start = 16, length = 12)

Is it really safe to not visit this node at all? Do we do something like that elsewhere?

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 2).

File: src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs]: Yes, it is safe because nothing legal in an expression tree can require spilling.  This code may have to be revised if that changes.  This pass doesn't perform any other kinds of rewrites that could be applicable.  I cannot think of a precedent for this in the compiler.
