### PR TITLE
Reduce memory consumption of LongestCommonSubsequence

### LINKED ISSUE #9497: EnC: OutOfMemoryException thrown by LongestCommonSubsequence.ComputeCostMatrix
When editing large methods (1000s of statements). 

The algorithm is currently allocating N^2 matrix. It can be optimized to N D or O(N).

Repro:

```C#
using System;

class Program
{
    static void Main(string[] args)
    {
        int i = 1;

        if (i == 0)
        {
             Console.WriteLine(0);
             Console.WriteLine(1);
             ...
             Console.WriteLine(10000);
        }
        else 
        {
             Console.WriteLine(0);
             Console.WriteLine(1);
             ...
             Console.WriteLine(10000);
        }
    }
}
```

### PR DESCRIPTION
**Pull request by HelenaKotas**
Changed implementation of LongestCommonSubsequence to use a less memory-intensive algorithm.
The old algorithm allocated O(oldSequence.Length * newSequence.Length) of memory.
The new algorithm is O((oldSequence.Length + newSequence.Length) * (# of inserts and deletes))
in both time and space.

Fixes #9497

**TODO:**
- [x] Verify OOM does not happen anymore
- [x] ~~Optimize allocations for ComputeDistance~~
- [x] ~~Is it worth to keep the previous algorithm for small inputs ?~~
- [x] Check on licence for https://www.codeproject.com/articles/42279/investigating-myers-diff-algorithm-part-of

### CODE REVIEW

**Comment by HelenaKotas** [comment]
@tmat Can you please take a look?

File: src/Workspaces/Core/Portable/Differencing/LongestCommonSubsequence.cs [hunk 1]
```diff
@@ -11,73 +11,150 @@ namespace Microsoft.CodeAnalysis.Differencing
...
     {
-        private const int DeleteCost = 1;
-        private const int InsertCost = 1;
-        private const int UpdateCost = 2;
-
-        protected abstract bool ItemsEqual(TSequence oldSequence, int oldIndex, TSequence newSequence, int newIndex);
-
-        protected IEnumerable<KeyValuePair<int, int>> GetMatchingPairs(TSequence oldSequence, int oldLength, TSequence newSequence, int newLength)
+        // VArray class enables array indexing in range [-d...d].
+        private class VArray
```
Comment (tmat) [inline src/Workspaces/Core/Portable/Differencing/LongestCommonSubsequence.cs]: Can we use struct instead to avoid allocations?

File: src/Workspaces/Core/Portable/Differencing/LongestCommonSubsequence.cs [hunk 2]
```diff
@@ -11,73 +11,150 @@ namespace Microsoft.CodeAnalysis.Differencing
...
         {
-            int[,] d = ComputeCostMatrix(oldSequence, oldLength, newSequence, newLength);
-            int i = oldLength;
-            int j = newLength;
+            private int[] array;
```
Comment (tmat) [inline src/Workspaces/Core/Portable/Differencing/LongestCommonSubsequence.cs]: Style: Use ```readonly``` for fields that don't change and ```_``` prefix for private fields.

File: src/Workspaces/Core/Portable/Differencing/LongestCommonSubsequence.cs [hunk 3]
```diff
@@ -11,73 +11,150 @@ namespace Microsoft.CodeAnalysis.Differencing
...
+            private int offset;
 
-            while (i != 0 && j != 0)
+            public VArray(int d, VArray previousVArray) : this(d)
             {
-                if (d[i, j] == d[i - 1, j] + DeleteCost)
+                if (previousVArray != null)
                 {
-                    i--;
+                    int copyDelta= offset - previousVArray.offset;
```
Comment (tmat) [inline src/Workspaces/Core/Portable/Differencing/LongestCommonSubsequence.cs]: Style: add space in front of ```=```

File: src/Workspaces/Core/Portable/Differencing/LongestCommonSubsequence.cs [hunk 4]
```diff
@@ -11,73 +11,150 @@ namespace Microsoft.CodeAnalysis.Differencing
...
+        private class VArray
         {
-            int[,] d = ComputeCostMatrix(oldSequence, oldLength, newSequence, newLength);
-            int i = oldLength;
-            int j = newLength;
+            private int[] array;
+            private int offset;
 
-            while (i != 0 && j != 0)
+            public VArray(int d, VArray previousVArray) : this(d)
```
Comment (tmat) [inline src/Workspaces/Core/Portable/Differencing/LongestCommonSubsequence.cs]: Since ```d``` is not used in the body it would be better to turn this constructor into an instance method (e.g. ```CopyFrom(VArray previous)```) and change the call-sites from ```new VArray(d, previous) to ```new VArray(d).CopyFrom(previous)```.

File: src/Workspaces/Core/Portable/Differencing/LongestCommonSubsequence.cs [hunk 5]
```diff
@@ -11,73 +11,150 @@ namespace Microsoft.CodeAnalysis.Differencing
...
-            int[,] d = ComputeCostMatrix(oldSequence, oldLength, newSequence, newLength);
-            int i = oldLength;
-            int j = newLength;
+            Stack<VArray> stackOfVs = ComputeEditPaths(oldSequence, oldLength, newSequence, newLength);
+
+            int x = oldLength;
+            int y = newLength;
 
-            while (i != 0 && j != 0)
+            for (int d = stackOfVs.Count - 1; x > 0 || y > 0; d--)
```
Comment (tmat) [inline src/Workspaces/Core/Portable/Differencing/LongestCommonSubsequence.cs]: I'd replace lines 66-68 with

```C#
while (x > 0 || y > 0)
{
   VArray currentV = stackOfVs.Pop();
   int d = stackOfVs.Count;

   ...
}
```

To avoid calculating stack depth in ```d``` as it's already counted by the stack itself.

File: src/Workspaces/Core/Portable/Differencing/LongestCommonSubsequence.cs [hunk 6]
```diff
@@ -11,73 +11,150 @@ namespace Microsoft.CodeAnalysis.Differencing
...
+        }
+
+        protected IEnumerable<SequenceEdit> GetEdits(TSequence oldSequence, int oldLength, TSequence newSequence, int newLength)
+        {
+            Stack<VArray> stackOfVs = ComputeEditPaths(oldSequence, oldLength, newSequence, newLength);
+
+            int x = oldLength;
+            int y = newLength;
+
+            for (int d = stackOfVs.Count - 1; x > 0 || y > 0; d--)
```
Comment (tmat) [inline src/Workspaces/Core/Portable/Differencing/LongestCommonSubsequence.cs]: The same here as above.

File: src/Workspaces/Core/Portable/Differencing/LongestCommonSubsequence.cs [hunk 7]
```diff
@@ -11,73 +11,150 @@ namespace Microsoft.CodeAnalysis.Differencing
...
+                y = yStart;
+            }
+
+        }
+
+        protected IEnumerable<SequenceEdit> GetEdits(TSequence oldSequence, int oldLength, TSequence newSequence, int newLength)
+        {
+            Stack<VArray> stackOfVs = ComputeEditPaths(oldSequence, oldLength, newSequence, newLength);
+
+            int x = oldLength;
```
Comment (tmat) [inline src/Workspaces/Core/Portable/Differencing/LongestCommonSubsequence.cs]: I wonder if we can somehow avoid duplicating the code between ```GetEdits``` and ```GetMatchingParts```. It seems that  a simple generalization to ```GetEdits``` could make it so that ```GetMatchingParts``` is a specialization of it. Adding a ```bool``` parameter that skips over lines 142-153. Would that work?

Comment (tmat) [inline src/Workspaces/Core/Portable/Differencing/LongestCommonSubsequence.cs]: We'd need to consolidate the return types between ```KeyValuePair<int, int>``` and ```SequenceEdit```. I guess we can do that as a refactoring later on, rather than mix it into these changes. Let's keep it duplicated for now.

**Comment by tmat** [comment]
@HelenaKotas Nice work! Did a first pass over the changes. So far looks good. Will dig a bit deeper on Mon.

File: src/Workspaces/Core/Portable/Differencing/LongestCommonSubsequence.cs (hunk 7 above)
Comment (HelenaKotas) [inline src/Workspaces/Core/Portable/Differencing/LongestCommonSubsequence.cs]: Agree.

**Comment by HelenaKotas** [comment]
Optimization: ComputeDistance only needs the number of matching pairs. For this the algorithm can be modified to use only a single resizable VArray without storing all of the previous VArrays in the Stack. Is this something worth doing? It would probably mean a clone of most of ComputeEditPaths code in ComputeDistance.

**Comment by tmat** [comment]
Re further optimizations - they would be certainly worth the effort, however I would leave that for later (another PR) to minimize this change in case we will be able to take it to VS 2017 RTM.

File: src/Workspaces/Core/Portable/Differencing/LongestCommonSubsequence.cs [hunk 8]
```diff
@@ -11,73 +11,154 @@ namespace Microsoft.CodeAnalysis.Differencing
...
-                    yield return new SequenceEdit(i, j);
+                    return _array.Length / 2;
                 }
             }
+        }
 
-            while (i > 0)
+        protected abstract bool ItemsEqual(TSequence oldSequence, int oldIndex, TSequence newSequence, int newIndex);
+
+        // TODO: Consolidate return types between GetMatchingPairs and GetEdit to avoid duplicated code
```
Comment (tmat) [inline src/Workspaces/Core/Portable/Differencing/LongestCommonSubsequence.cs]: >TODO: [](start = 11, length = 5)

I created an issue to follow up on this: [https://github.com/dotnet/roslyn/issues/16864](https://github.com/dotnet/roslyn/issues/16864). Please add the link to the comment.

File: src/Workspaces/CoreTest/Differencing/LongestCommonSubsequenceTests.cs [hunk 9]
```diff
@@ -0,0 +1,311 @@
...
+using Xunit;
+using System.Collections.Generic;
+
+namespace Microsoft.CodeAnalysis.Differencing.UnitTests
+{
+    public class LongestCommonSubsequenceTests
+    {
+        LongestCommonSubsequenceString lcs = new LongestCommonSubsequenceString();
+
+        private class LongestCommonSubsequenceString : LongestCommonSubsequence<string>
```
Comment (tmat) [inline src/Workspaces/CoreTest/Differencing/LongestCommonSubsequenceTests.cs]: >LongestCommonSubsequenceString [](start = 22, length = 30)

We already have LongestCommonSubstring class. 
Do we need this one?

[http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Differencing/LongestCommonSubstring.cs,55843be7ccb0c072,references](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Differencing/LongestCommonSubstring.cs,55843be7ccb0c072,references)

Comment (HelenaKotas) [inline src/Workspaces/CoreTest/Differencing/LongestCommonSubsequenceTests.cs]: Since the test is for the abstract LongestCommonSubsequence class it seems better to me to have a private class derived from it just for the testing rather then using the existing internal LongestCommonSubstring class. Just in case the internal class is changed in the future to not use the diff code from LongestCommonSubsequence.

**Comment by HelenaKotas** [comment]
Licensing update: The change was inspired by Myers' Diff Algorithm articles by @nicholasbutler (https://www.codeproject.com/articles/42279/investigating-myers-diff-algorithm-part-of).

The author has approved the use of his code from the article under the Apache 2.0 license.

[Nick Butler - Myers' Diff Alg - license.pdf](https://github.com/dotnet/roslyn/files/743862/Nick.Butler.-.Myers.Diff.Alg.-.license.pdf)

**Comment by tmat** [comment]
👍

**Comment by tmat** [comment]
test windows_eta_open_prtest  please

**Comment by tmat** [comment]
Re: "Is it worth to keep the previous algorithm for small inputs ?" I don't think so. We can optimize allocations more using pooled arrays in a next iteration on this code.

**Comment by tmat** [comment]
test windows_eta_open_prtest please

**Comment by tmat** [comment]
test windows_eta_open_prtest please
