### PR TITLE
Generalize dynamic static-only restriction to include field initializers

### LINKED ISSUE #10463: Invalid IL generated for field initializer with dynamic
**Version Used**: 1.2.0.60317

**Steps to Reproduce**:

1. Compile
```
using System;

public class B2
{
	public Action a = () => {
			dynamic d = 1;
			Test (d);
		};

	static decimal Test (dynamic arg)
	{
		return 3m;
	}
}

class M
{
	static void Main ()
	{
		new B2 ();
	}	
}
```
2. peverify output .exe 

**Expected Behavior**:

Valid IL produced by compiler.

**Actual Behavior**:

Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

[IL]: Error: [c.exe : B2::.ctor][offset 0x00000008][found <uninitialized> ref ('this' ptr) 'B2'][expected ref 'System.Object'] Unexpected type on the stack.

### PR DESCRIPTION
**Pull request by khyperia**
Fixes #10463

Native compiler handled all cases, Roslyn generated invalid IL when using dynamic in a field initializer. Roslyn *does* already handle dynamic in a constructor initializer, like the following case:

    public M() : base((object)Test((dynamic)2)) // as imagined inserted into test case in this PR

This PR simply hooks into that logic and extends it to field initializers as well (which also run before the base constructor call).

Ping @dotnet/roslyn-compiler for review.

### CODE REVIEW

**Comment by gafter** [comment]
:shipit:

**Comment by gafter** [comment]
:shipit:

**Comment by VSadov** [comment]
LGTM

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs [hunk 1]
```diff
@@ -14835,5 +14835,72 @@ .maxstack  4
...
+        public void FieldInitializerDynamic()
+        {
+            string source = @"
+using System;
+
+class M
+{
+    object a = Test((dynamic)2);
+
+    static object Test(object obj) => obj;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs]: Could you please add a test with an instance method?

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs]: It looks like there is a breaking change in this case.

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs [hunk 2]
```diff
@@ -270,11 +270,13 @@ private BoundExpression BindArgListOperator(InvocationExpressionSyntax node, Dia
                             break;
 
                         case BoundKind.ThisReference:
-                            if (InConstructorInitializer && receiver.WasCompilerGenerated)
+                            // Can't call the HasThis method due to EE doing odd things with containing member and its containing type.
+                            if ((InConstructorInitializer || InFieldInitializer) && receiver.WasCompilerGenerated)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: What happens if `this` is used in a static ctor / field initializer with dynamic?  Will this code path get hit?  If so do we have a test to make sure we don't crash?

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs [hunk 3]
```diff
@@ -14835,5 +14835,72 @@ .maxstack  4
...
+        [WorkItem(10463, "https://github.com/dotnet/roslyn/issues/10463")]
+        [Fact]
+        public void FieldInitializerDynamic()
+        {
+            string source = @"
+using System;
+
+class M
+{
+    object a = Test((dynamic)2);
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs]: Can we add a test for the case when the receiver has a dynamic parameter?

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs (hunk 2 above)
Comment (khyperia) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: No, it won't get hit. Added tests for that along with a group of other tests (including @AlekseyTs's comments above), will submit PR once I address this and your other comment below.

Reason: For static ctors, this diagnostic gets reported https://github.com/dotnet/roslyn/blob/fd32a7348150294a5f9d3a212da67d41977b2f12/src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs#L484 which then makes this if statement https://github.com/dotnet/roslyn/blob/fd32a7348150294a5f9d3a212da67d41977b2f12/src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs#L546 be false and not call BindDynamicInvocation, which is where the above diff is. The same happens for static fields, but the original diagnostic is reported in a slightly different location a couple lines away https://github.com/dotnet/roslyn/blob/fd32a7348150294a5f9d3a212da67d41977b2f12/src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs#L476
