### PR TITLE
Fix bug when caret is at the end of a numeric literal

### LINKED ISSUE #19369: Convert base / Insert digit separators refactorings are not available when the caret is at the end of a numeric literal
**Version Used**: Latest magma-hot bits

**Steps to Reproduce**:

```C#
class C
{
    int x = 42;
}
```

1. Place editor caret between `2` and `;`
2. Press <kbd>Ctrl</kbd>+<kbd>.</kbd>

**Expected Behavior**: 'Convert base' and 'Insert digit separators' refactorings should be available.

**Actual Behavior**: They're not.

### PR DESCRIPTION
**Pull request by alrz**
Fixes #19369

### CODE REVIEW

**Comment by sharwell** [comment]
@dotnet/roslyn-ide for review

File: src/Features/Core/Portable/ConvertNumericLiteral/AbstractConvertNumericLiteralCodeRefactoringProvider.cs [hunk 1]
```diff
@@ -19,26 +19,22 @@ internal abstract class AbstractConvertNumericLiteralCodeRefactoringProvider : C
...
+                token => syntaxFacts.IsNumericLiteralExpression(token.Parent), cancellationToken).ConfigureAwait(false);
 
-            var numericToken = root.FindToken(context.Span.Start);
-            if (numericToken.ContainsDiagnostics)
+            if (numericToken == default(SyntaxToken))
             {
                 return;
             }
 
-            if (!numericToken.Span.Contains(context.Span))
```
Comment (Pilchie) [inline src/Features/Core/Portable/ConvertNumericLiteral/AbstractConvertNumericLiteralCodeRefactoringProvider.cs]: This means the refactoring will now trigger if there is a selection that *starts* in the literal.  I think I'd prefer that it only work if there is either:

* No selection
* The selection matches Token.Span.

Thoughts?

Comment (sharwell) [inline src/Features/Core/Portable/ConvertNumericLiteral/AbstractConvertNumericLiteralCodeRefactoringProvider.cs]: I was leaning towards "no selection", but matching selection to token could be reasonable too.

**Comment by Pilchie** [comment]
Thanks @alrz.  @sharwell - can you get the ask mode template ready.

File: src/Features/Core/Portable/ConvertNumericLiteral/AbstractConvertNumericLiteralCodeRefactoringProvider.cs (hunk 1 above)
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ConvertNumericLiteral/AbstractConvertNumericLiteralCodeRefactoringProvider.cs]: I'd prefer no-selection.  That seems to be the approach we're taking witha  lot of refactorings.

Comment (alrz) [inline src/Features/Core/Portable/ConvertNumericLiteral/AbstractConvertNumericLiteralCodeRefactoringProvider.cs]: I think that'd be unexpected if we don't offer the fix when the selection matches the token because this refactoring operates on a single token. On the other hand, when we offer a refactoring based on parents of a node e.g. "add argument name", then the no-selection approach would be preferable imo.

**Comment by sharwell** [comment]
@alrz @Pilchie I've been swamped for a bit. I have it on my priority list to get the template in. Should be today.

**Comment by sharwell** [comment]
@dotnet-bot retest ubuntu_14_debug_prtest please

**Comment by sharwell** [comment]
**Customer scenario**

What does the customer do to get into this situation, and why do we think this
is common enough to address for this release.  (Granted, sometimes this will be
obvious "Open project, VS crashes" but in general, I need to understand how
common a scenario is)

**Bugs this fixes:**

(either VSO or GitHub links)

**Workarounds, if any**

Also, why we think they are insufficient for RC vs. RC2, RC3, or RTW

**Risk**

This is generally a measure our how central the affected code is to adjacent
scenarios and thus how likely your fix is to destabilize a broader area of code

**Performance impact**

(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")

**Is this a regression from a previous update?**

**Root cause analysis:**

How did we miss it?  What tests are we adding to guard against it in the future?

**How was the bug found?**

(E.g. customer reported it vs. ad hoc testing)

**Comment by sharwell** [comment]
@MattGertz  for ask mode
