### PR TITLE
Re-enable EvaluateInitializerExpression test

### LINKED ISSUE #1300: EE unit test EvaluateInitializerExpression fails due to nondeterministic module name
I have disabled EE test EvaluateInitializerExpression as the generated module contains the module name, which the test does not set. The test therefore fails today.

### PR DESCRIPTION
**Pull request by cston**
Fixes #1300

### CODE REVIEW

**Comment by cston** [comment]
@gafter, @amcasey, @KevinH-MS

File: src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/ExpressionCompilerTests.vb [hunk 1]
```diff
@@ -2082,6 +2082,43 @@ End Class"
...
+                compOptions:=TestOptions.DebugDll.WithModuleName("MODULE"),
+                assemblyName:=ExpressionCompilerUtilities.GenerateUniqueName())
+            Dim runtime = CreateRuntimeInstance(compilation0)
+            Dim context = CreateMethodContext(
+                runtime,
+                methodName:="C.M")
+            Dim resultProperties As ResultProperties = Nothing
+            Dim errorMessage As String = Nothing
+            Dim testData = New CompilationTestData()
+            context.CompileExpression("{ 1, 2, 3, 4, 5 }", resultProperties, errorMessage, testData)
```
Comment (amcasey) [inline src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/ExpressionCompilerTests.vb]: What's the type of this expression?  Would it be interesting to test the return type of the method?

File: src/Test/Utilities/SharedCompilationUtils.cs [hunk 2]
```diff
@@ -61,7 +61,14 @@ internal static CompilationTestData.MethodData GetMethodData(this CompilationTes
             [CallerLineNumber]int expectedValueSourceLine = 0,
             [CallerFilePath]string expectedValueSourcePath = null)
         {
+            const string moduleNamePlaceholder = "{#Module#}";
             string actualIL = GetMethodIL(method);
+            if (expectedIL.IndexOf(moduleNamePlaceholder) >= 0)
+            {
+                var module = method.Method.ContainingModule;
+                var moduleName = Path.GetFileNameWithoutExtension(module.Name);
```
Comment (amcasey) [inline src/Test/Utilities/SharedCompilationUtils.cs]: Why remove the extension and then add it back everywhere the placeholder is used?

**Comment by amcasey** [comment]
:+1:

File: src/Test/Utilities/SharedCompilationUtils.cs (hunk 2 above)
Comment (cston) [inline src/Test/Utilities/SharedCompilationUtils.cs]: I thought a pseudo-variable representing the module name without extension would be more useful than one that includes the extension.

Comment (amcasey) [inline src/Test/Utilities/SharedCompilationUtils.cs]: It seems like it would be more consistent to return the same thing that ModuleSymbol.Name would return.  Then, if people want to strip the file extension, they can.

File: src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/ExpressionCompilerTests.vb (hunk 1 above)
Comment (cston) [inline src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/ExpressionCompilerTests.vb]: Added check for Integer() ReturnType.

**Comment by KevinH-MS** [comment]
LGTM

**Comment by gafter** [comment]
:+1: :shipit:
