### PR TITLE
Run analyzer consistency checks on .NET Core

### LINKED ISSUE #70053: VBCSCompiler doesn't load changed dll referenced as analyzer reference
**Version Used**: 
8.0.100-preview.4.23260.5

**Steps to Reproduce**:
Create a solution with 2 projects: 

- Project A: a project with a source generator 
- Project B: has analyzer reference to Project A and uses generated code

1. Specify some usage of the generated file in Project B
2. Build using `dotnet build`
3. Make changes in Project A, e.g. change the generated class name
4. Build using `dotnet build` again

**Expected Behavior**:
The generated code in Project B is changed based on the changes in Project A source generators. The same behavior in Visual Studio

**Actual Behavior**:
The generated code in Project B has not changed

**Workaround**:
Shutdown VBCSComiler instance by specifying `dotnet build-server shutdown`

### Root Cause

The current Shadow Copy Assembly loader doesn't check the MVID of the built assembly, so once you build dll and it is loaded to VBCSComiler, it will be in the memory till the end of the process

But why does everything work fine in Visual Studio? There is an AnalyzerConsistencyChecker that checks the Mvid of compiled assemblies and returns an error if the Mvid is different. So once VBCSCompiler returns an error it closes and restarted by Visual Studio.

Unfortunately, this checker is disabled for NetCore: https://github.com/dotnet/roslyn/commit/158ba3aaff230b1b89284406323fcc79fa2d04e2

So at this moment, CLT tools don't allow us to work with local Source Generators properly, without shutting down VBCSComiler before every build.

### PR DESCRIPTION
**Pull request by jaredpar**
The job of `AnalyzerConsistencyChecker` is to determine when the compiler server has loaded analyzers in a bad state and force a restart. One of the bad states it detects is when the analyzers on disk change. That is not handled by `AnalyzerAssemblyLoader` because it has an invariant that the file system is unchanged. This was not running for .NET Core so this particular scenario was missed. This change updates `AnalyzerConsistencyChecker` to run on .NET Core too to catch these issues.

closes #70053

### CODE REVIEW

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 1]
```diff
@@ -13,6 +13,15 @@
 
 namespace Microsoft.CodeAnalysis
 {
+    internal interface IAnalyzerAssemblyLoaderInternal : IAnalyzerAssemblyLoader
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:16]: `IAnalyzerAssemblyLoader` is a `public` API and did not want to create new `public` API for this hence went with an `internal` API instead.

**Comment by jaredpar** [comment]
@dotnet/roslyn-compiler PTAL

**Comment by jaredpar** [comment]
@RikkiGibson, @jjonescz PTAL

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:16]: We don't expect external users (at least those who lack IVT) to implement IAnalyzerAssemblyLoader, right?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 2]
```diff
@@ -21,7 +30,7 @@ namespace Microsoft.CodeAnalysis
     /// This type generally assumes that files on disk aren't changing, since it ensure that two calls to <see cref="LoadFromPath(string)"/>
     /// will always return the same thing, per that interface's contract.
     /// </remarks>
-    internal abstract partial class AnalyzerAssemblyLoader : IAnalyzerAssemblyLoader
+    internal abstract partial class AnalyzerAssemblyLoader : IAnalyzerAssemblyLoaderInternal
```
Comment (RikkiGibson) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:33]: I was a little surprised I didn't see any changes which type-test or cast to `IAnalyzerAssemblyLoaderInternal`. I thought we had public API which permits users to pass in instances of `IAnalyzerAssemblyLoader` in order to use a common analyzer loader across compilations.

**Review by RikkiGibson — APPROVED** [review]
LGTM, just had minor comments/questions

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs (hunk 1 above)
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:16]: Correct. This is only used in the compiler server where external teams cannot provide implementations.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs (hunk 2 above)
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:33]: You're correct that we have end points that provide `IAnalyzerAssemblyLoader` parameters. This particular API is only used in the compiler server where we do not provide a public API end point. It's not a re-hostable component but one where we provide all the implementations. 

Pretty much the only reason that the compiler server takes `IAnalyzerAssemblyLoader` and not `AnalyzerAssemblyLoader` is that it limits the API surface area and it's easier to provide throwing implementations in unit tests so we can validate behavior better.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.Desktop.cs [hunk 3]
```diff
@@ -31,6 +31,28 @@ internal AnalyzerAssemblyLoader()
         {
         }
 
+        public bool IsHostAssembly(Assembly assembly)
+        {
+            // When an assembly is loaded from the GAC then the load result would be the same if 
+            // this ran on command line compiler. So there is no consistency issue here, this 
+            // is just runtime rules expressing themselves.
```
Comment (jjonescz) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.Desktop.cs:38]: It's a bit weird that the API is named `IsHostAssembly` but the comments are talking about "consistency" - they made sense when inside the consistency checker but here are bit out of context. But I guess it's fine since it's an internal API (and has just one caller - the consistency checker).

**Review by jjonescz — APPROVED** [review]
