### PR TITLE
Fix value usage info for VB 'For .. To'

### LINKED ISSUE #59720: Code CleanUp 'make field readonly, add 'readonly' when only written by for-loop
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Code-CleanUp-make-field-readonly-add-/1672970)._

---
[severity:It bothers me. A fix would be nice]
Hi,
When you have a Local field, that is written only by a for-loop
For excample this VB.Net Code

```
Module Program
    Dim i As Integer
    Sub Main(args As String())
        Console.WriteLine("Hello World!")
        For i = 1 To 10
            Console.WriteLine(i & " ...")
        Next
    End Sub
End Module
```

Gets changed to this Code by the Code CleanUp:

```
Friend Module Program
    Private ReadOnly i As Integer

Public Sub Main(args As String())
        Console.WriteLine("Hello World!")
        For i = 1 To 10
            Console.WriteLine(i & " ...")
        Next
    End Sub
End Module
```

---
#### Feedback Bot on 2/22/2022, 06:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #59720

### CODE REVIEW

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/OperationExtensions.cs [hunk 1]
```diff
@@ -132,7 +132,7 @@ INegatedPatternOperation or
             {
                 return ValueUsageInfo.ReadableWritableReference;
             }
-            else if (operation.Parent is IIncrementOrDecrementOperation)
```
Comment (Youssef1313) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/OperationExtensions.cs:135]: @mavasani This implementation has a copy in roslyn-analyzers:

https://github.com/dotnet/roslyn-analyzers/blob/main/src/Utilities/Compiler/Extensions/IOperationExtensions.cs

Can we investigate having an automation similar to dotnet/aspnetcore and dotnet/runtime (example: https://github.com/dotnet/runtime/pull/72588)

Comment (mavasani) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/OperationExtensions.cs:135]: Interesting, I think we have discussed about making some of this functionality available through public API. Not sure how acceptable that would be.

**Review by mavasani — APPROVED** [review]

**Comment by mavasani** [comment]
@Youssef1313 Do we need C# tests corresponding to this or is this Operation tree shape not possible in C#?

**Comment by Youssef1313** [comment]
> @Youssef1313 Do we need C# tests corresponding to this or is this Operation tree shape not possible in C#?

This shape is VB only. The equivalent C# code (`for (i = 0; i < 10; i++)`) has assignment operation as the parent of field reference in `i = 0`.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/OperationExtensions.cs (hunk 1 above)
Comment (Youssef1313) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/OperationExtensions.cs:135]: I'm not sure if the API is accurate/reliable enough to be public. But it would be nice to have public (after any needed improvements, if any)

**Comment by Youssef1313** [comment]
@mavasani There is an unrelated failure here.
