### PR TITLE
Ensure lvalue struct receivers are not copied by value due to interpolated string handler rewrite

### LINKED ISSUE #65470: Receiver of a call taking InterpolatedStringHandler is unexpectedly copied in a way that mutations performed by the method are not observable
```

        [Fact]
        public void StructReceiver_Lvalue_02()
        {
            var code = @"
using System;
using System.Runtime.CompilerServices;
using System.Text;

var i = 0;
var l = new StructLogger(true, 1);
Console.WriteLine(""logged = {0}"", l._logged);
l.Log($""log:{i++}"");
Console.WriteLine($""(1) i={i}"");
Console.WriteLine(""logged = {0}"", l._logged);

internal struct StructLogger
{
    private readonly bool _disabled;
    private readonly int _id;
    public int _logged;

    public bool Disabled => _disabled;
    public int Id => _id;

    public StructLogger(bool disabled, int id)
    {
        _disabled = disabled;
        _id = id;
    }

    public void Log([InterpolatedStringHandlerArgument("""")] DummyHandler handler)
    {
        _logged++;
        Console.WriteLine($""StructLogger#{_id}: "" + handler.GetContent());
    }
}

[InterpolatedStringHandler]
internal ref struct DummyHandler
{
    private readonly StringBuilder _builder;
    public DummyHandler(int literalLength, int formattedCount, StructLogger structLogger, out bool enabled)
    {
        Console.WriteLine($""Creating DummyHandler from StructLogger#{structLogger.Id}"");
        enabled = !structLogger.Disabled;
        _builder = structLogger.Disabled ? null : new StringBuilder();
    }
    public string GetContent() => _builder?.ToString();

    public void AppendLiteral(string s) => _builder?.Append(s);
    public void AppendFormatted<T>(T t) => _builder?.Append(t);
}
";


            var comp = CreateCompilation(new[] { code, InterpolatedStringHandlerAttribute, InterpolatedStringHandlerArgumentAttribute }, options: TestOptions.ReleaseExe);
            var verifier = CompileAndVerify(comp, expectedOutput: @"
logged = 0
Creating DummyHandler from StructLogger#1
StructLogger#1: 
(1) i=0
logged = 0
");

            verifier.VerifyDiagnostics();
        }
```

Observed:
```
logged = 0
Creating DummyHandler from StructLogger#1
StructLogger#1: 
(1) i=0
logged = 0
```

Expected:
```
logged = 0
Creating DummyHandler from StructLogger#1
StructLogger#1: 
(1) i=0
logged = 1
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #65470.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@333fred, @dotnet/roslyn-compiler Please review.

**Review by 333fred — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs [hunk 1]
```diff
@@ -306,31 +281,17 @@ private BoundIndexerAccess TransformIndexerAccess(BoundIndexerAccess indexerAcce
...
+                ref transformedReceiver,
+                captureReceiverForMultipleInvocations: CanChangeValueBetweenReads(receiverOpt),
                 indexerAccess.Arguments,
                 indexer,
                 argsToParamsOpt,
                 argumentRefKinds,
-                ref transformedReceiver!,
-                out ArrayBuilder<LocalSymbol>? argumentTemps);
+                stores,
+                ref temps!);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs:292]: >! [](http://example.com/codeflow?start=25&length=1)

Minor: Is `!` needed?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs:292]: > Minor: Is ! needed?

Otherwise it complains that method can assign null on the way out

File: src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs [hunk 2]
```diff
@@ -10769,6 +10775,504 @@ public CustomHandler(int literalLength, int formattedCount, ref S s1, ref S s2)
...
+
+            var comp = CreateCompilation(new[] { code, InterpolatedStringHandlerAttribute, InterpolatedStringHandlerArgumentAttribute }, options: TestOptions.ReleaseExe);
+            var verifier = CompileAndVerify(comp, expectedOutput: @"
+logged = 0
+Creating DummyHandler
+StructLogger: log:0
+logged = 1
+");
+
+            verifier.VerifyDiagnostics();
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs:10833]: >verifier [](http://example.com/codeflow?start=12&length=8)

Please consider including `verify.VerifyIL("test()", "...");` to verify the expected IL.

File: src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs [hunk 3]
```diff
@@ -10769,6 +10775,504 @@ public CustomHandler(int literalLength, int formattedCount, ref S s1, ref S s2)
...
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs:10889]: >verifier [](http://example.com/codeflow?start=12&length=8)

Consider including `verify.VerifyIL("test()", "...");`.

File: src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs:10833]: ```StructReceiver_Rvalue``` captures interesting IL changes. IL comparison is brittle. When possible, I prefer testing behavior instead. Which I think is sufficient for the change

File: src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs [hunk 4]
```diff
@@ -10769,6 +10775,504 @@ public CustomHandler(int literalLength, int formattedCount, ref S s1, ref S s2)
...
+    }
+    public string GetContent() => _builder.ToString();
+
+    public void AppendLiteral(string s) => _builder.Append(s);
+    public void AppendFormatted<T>(T t) => _builder.Append(t);
+}
+";
+
+            var comp = CreateCompilation(new[] { code, InterpolatedStringHandlerAttribute, InterpolatedStringHandlerArgumentAttribute }, options: TestOptions.ReleaseExe);
+            var verifier = CompileAndVerify(comp, expectedOutput: @"
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs:11066]: >verifier [](http://example.com/codeflow?start=16&length=8)

Consider including `verifier.VerifyIL("test3", "..."); verifier.VerifyIL("test4", "...");`.

**Review by cston — APPROVED** [review]
