### PR TITLE
Fix leak of projects in VisualStudioProjectTracker.WorkspaceHostState

### LINKED ISSUE #10358: deleted project hierarchy leaked through VisualStudioProjectTracker
**Version Used**: new version inserted into Dev 15 code

**Steps to Reproduce**:

1.  Add a CPS barebone project to a solution
2.  Delete the project
3. Ctrl-Alt-Shift-F12 couple times to force GC
4. Attach Windbg, check UnconfiguredProjectImpl instance in the memory, they should be released.

**Expected Behavior**:
no project object hold in the memory after it is deleted.

**Actual Behavior**:
 leak through this chain:

->  1c35480c Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.DocumentKey
            ->  1c24ffe8 Microsoft.VisualStudio.LanguageServices.CSharp.ProjectSystemShim.CSharpProjectShimWithServices
            ->  1c1a0714 Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker
            ->  1c1a0808 System.Collections.Generic.List`1[[Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker+WorkspaceHostState, Microsoft.VisualStudio.LanguageServices]]
            ->  23833ad0 Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker+WorkspaceHostState[]
            ->  1c1a0f78 Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker+WorkspaceHostState
            ->  1c1a0f90 System.Collections.Generic.HashSet`1[[Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject, Microsoft.VisualStudio.LanguageServices]]
            ->  1c262a80 System.Collections.Generic.HashSet`1+Slot[[Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject, Microsoft.VisualStudio.LanguageServices]][]
            ->  23c9829c Microsoft.VisualStudio.LanguageServices.CSharp.ProjectSystemShim.CSharpProjectShimWithServices
            ->  23acc8d0 Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode
            ->  23aadeb8 Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl

### PR DESCRIPTION
**Pull request by jasonmalinowski**
Fixes #10358.

### CODE REVIEW

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker.cs [hunk 1]
```diff
@@ -233,9 +233,12 @@ internal void RemoveProject(AbstractProject project)
 
             UpdateProjectBinPath(project, project.TryGetBinOutputPath(), null);
 
-            if (project.PushingChangesToWorkspaceHosts)
+            using (Dispatcher.CurrentDispatcher.DisableProcessing())
             {
-                NotifyWorkspaceHosts(host => host.OnProjectRemoved(project.Id));
+                foreach (var hostState in _workspaceHosts)
```
Comment (Pilchie) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker.cs]: What if `hostState` is not ready for events?

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker.cs [hunk 2]
```diff
@@ -233,9 +233,12 @@ internal void RemoveProject(AbstractProject project)
 
             UpdateProjectBinPath(project, project.TryGetBinOutputPath(), null);
 
-            if (project.PushingChangesToWorkspaceHosts)
```
Comment (Pilchie) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker.cs]: So, the bug was that this was false?

Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker.cs]: The bug is that once we had pushed a project to a host, if we removed it, we would never clear it from `WorkspaceHostState._pushedProjects`. Completely closing a solution was fine since we'd clear out everything, but that would leak the reference.

It's unclear to me how "big" this leak actually is; it might be only leaking the immediate AbstractProject and a few other cheap types, but better safe than sorry.

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker.cs (hunk 1 above)
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker.cs]: Then hostState.RemoveProject will no-op because there aren't any projects pushed. The list is empty, Remove will do nothing.

Comment (Pilchie) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker.cs]: Won't it call into http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Workspace.cs,414 and throw because the project isn't in the solution?  Also, what about the CodeLens `WorkspaceHost`.

Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker.cs]: No, because `_pushedProjects.Remove(project)` that I'm adding above will return false.

**Comment by Pilchie** [comment]
Got it - 👍

**Comment by jasonmalinowski** [comment]
Also an FYI to @dotnet/project-system since this may impact them too.

**Comment by jasonmalinowski** [comment]
And a note to reviewers: there are two commits. The first is me refactoring our test helpers for doing lifetime stuff, and the second is the actual fix. Also @dotnet/roslyn-compiler since I am touching their tests to respond to the refactoring.

**Comment by jasonmalinowski** [comment]
@dotnet-bot, retest windows_debug_unit32_prtest please. It's clear I've broken something; I'm just curious if what I've broken is consistent.

**Comment by jasonmalinowski** [comment]
@dotnet-bot, retest this please. PR got stale.

**Comment by jasonmalinowski** [comment]
@dotnet/roslyn-compiler, last call to take a look at this? I'm still fixing up the last services test, but no further changes should be happening on your side of things. I had to make a few tweaks to some tests; it appears that at least one of the weak list tests was getting slightly lucky that it was passing.

**Comment by jasonmalinowski** [comment]
@dotnet-bot test vsi please. And ping @dotnet/roslyn-ide for a second review.

**Comment by jasonmalinowski** [comment]
@dotnet-bot, retest windows_debug_unit64_prtest please due to #12222. Also test vsi please.

**Comment by jasonmalinowski** [comment]
@dotnet-bot, test vsi please. I made one tweak and had to repush.

File: src/Test/Utilities/Desktop/ObjectReference.cs [hunk 3]
```diff
@@ -0,0 +1,142 @@
...
+
+            _strongReference = null;
+
+            // We'll loop 100 times, or until the weak reference disappears. When we're trying to assert that the
+            // object is released, once the weak reference goes away, we know we're good. But if we're trying to assert
+            // that the object is held, our only real option is to know to do it "enough" times; but if it goes away then
+            // we are definitely done.
+            for (var i = 0; i < 100 && _weakReference.IsAlive; i++)
+            {
+                GC.Collect();
```
Comment (rchande) [inline src/Test/Utilities/Desktop/ObjectReference.cs]: The old tests used to do this over a time interval, is that worth replicating?

**Comment by rchande** [comment]
:+1:

File: src/Test/Utilities/Desktop/ObjectReference.cs (hunk 3 above)
Comment (jasonmalinowski) [inline src/Test/Utilities/Desktop/ObjectReference.cs]: It looks like some final tweak I made means perhaps we have to restore that. :-(
