### PR TITLE
Respect line directives in SARIF logger

### LINKED ISSUE #71449: Analysis results paths are pointing to generated code instead of the Razor files
For the diagnostics reported in `.razor` files, the locations are pointing to the generated files instead of the actual razor files.

E.g. when a diagnostic is reported on the `IncrementCount` identifier from the following code (`Counter.razor` file)
```
<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>
```
The Sarif report contains:
```
          "locations": [
            {
              "resultFile": {
                "uri": "Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/Components_Pages_Counter_razor.g.cs",
```
You can find [here](https://github.com/dotnet/razor/files/13615158/BlazorWebApp.zip) a reproducer. It contains already the generated Sarif report (`BlazorWebApp\BuildOutput.sarif`)

When working on custom code analyzers and development tools in general, it is very useful to have access to the original location of the syntax. For [sonar-dotnet](https://github.com/SonarSource/sonar-dotnet) analyzers, we need the correct locations to be able to import and display the issues on SonarQube and SonarCloud.

We tried to do the mapping ourselves (by using [GetMappedLineSpan](https://learn.microsoft.com/es-es/dotnet/api/microsoft.codeanalysis.syntaxtree.getmappedlinespan?view=roslyn-dotnet-4.6.0)) but the API offers limited functionality, and we often encounter issues like https://github.com/dotnet/roslyn/issues/69248. This has also unexpected behavior in the IDE like https://github.com/dotnet/razor/issues/9308 or https://github.com/dotnet/razor/issues/9108.

@davidwengier explained [here](https://github.com/dotnet/razor/issues/9308#issuecomment-1730846267) that:
> Also, I'm not surprised line mappings don't work, as they are not very sophisticated without the Razor compiler moving to enhanced line pragmas. I would expect that if a diagnostic is reported on the unmapped location, it probably has a better chance of working, as we will correctly map it to the .razor file, and we have more source mapping information than the Roslyn APIs can see. I don't think Roslyn's internal analyzers generally call GetMappedSpan() when creating diagnostics.

# tl;dr

Would it be possible to change paths for the diagnostics in razor files to point to the original files instead of the generated ones?

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #71449

PR title no longer accurate, will change before merge.

### CODE REVIEW

File: src/Compilers/Core/Portable/CommandLine/SarifV1ErrorLogger.cs [hunk 1]
```diff
@@ -133,7 +133,7 @@ public override void AddAnalyzerDescriptorsAndExecutionTime(ImmutableArray<(Diag
             // We log all analyzer descriptors only in SARIF v2+ format.
         }
 
-        protected override void WritePhysicalLocation(Location location)
+        protected override void WritePhysicalLocation(Location location, SourceReferenceResolver? resolver)
```
Comment (RikkiGibson) [inline src/Compilers/Core/Portable/CommandLine/SarifV1ErrorLogger.cs:136]: I opted not to change behavior in the "legacy"(?) v1 logger for now.

File: src/Compilers/Core/Portable/CommandLine/SarifV2ErrorLogger.cs [hunk 2]
```diff
@@ -167,16 +167,19 @@ private void WriteLocations(Location location, IReadOnlyList<Location> additiona
...
         }
 
-        protected override void WritePhysicalLocation(Location diagnosticLocation)
+        protected override void WritePhysicalLocation(Location diagnosticLocation, SourceReferenceResolver? resolver)
         {
             Debug.Assert(HasPath(diagnosticLocation));
 
             FileLinePositionSpan span = diagnosticLocation.GetLineSpan();
+            var path = diagnosticLocation.SourceTree is { } tree
+                ? tree.GetDisplayPath(diagnosticLocation.SourceSpan, resolver)
```
Comment (RikkiGibson) [inline src/Compilers/Core/Portable/CommandLine/SarifV2ErrorLogger.cs:176]: This also handles line directives. I didn't add a new test here, but I do have another PR in the works, which is maybe better to target main with, in order to make adding/maintaining the tests easier in this area.

File: src/Compilers/CSharp/Test/CommandLine/SarifV2ErrorLoggerTests.cs [hunk 3]
```diff
@@ -651,5 +651,628 @@ class C
...
+                    {
+                      "$schema": "http://json.schemastore.org/sarif-1.0.0",
+                      "version": "1.0.0",
+                      "runs": [
+                        {
+                          "tool": {
+                            "name": "Microsoft (R) Visual C# Compiler",
+                            "version": "42.42.42.42",
+                            "fileVersion": "4.9.0-dev (<developer build>)",
+                            "semanticVersion": "42.42.42",
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/CommandLine/SarifV2ErrorLoggerTests.cs:700]: Can't hard code these values cause they will change. Even the version will change between local and CI (-dev vs. -ci). Need to either filter these out or fill them with interpolation.

File: src/Compilers/CSharp/Test/CommandLine/SarifV2ErrorLoggerTests.cs [hunk 4]
```diff
@@ -651,5 +651,628 @@ class C
...
+        [ConditionalTheory(typeof(WindowsOnly), Reason = "https://github.com/dotnet/roslyn/issues/30289")]
+        [CombinatorialData]
+        public void LineDirective(SarifTestVersion version)
+        {
+            var errorLogDir = Temp.CreateDirectory();
+
+            var source = $$"""
+public class C
+{
+#line 123 "D:\otherfile.cs"
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/CommandLine/SarifV2ErrorLoggerTests.cs:873]: This makes me a bit nervous cause there are cases where `#line` can behave differently if it can / can't find a file. Hard coding a path like this means it's possible on some machines the file may exist while on others it won't. Prefer instead if we definitively do / don't put a file on disk at this location via `Temp.CreateDirectory().CreateFile` and then use interpolation to put the known file path.

**Review by jaredpar — CHANGES_REQUESTED** [review]

File: src/Compilers/Core/Portable/CommandLine/SarifV2ErrorLogger.cs [hunk 5]
```diff
@@ -167,16 +167,19 @@ private void WriteLocations(Location location, IReadOnlyList<Location> additiona
...
-        protected override void WritePhysicalLocation(Location diagnosticLocation)
+        protected override void WritePhysicalLocation(Location diagnosticLocation, SourceReferenceResolver? resolver)
         {
             Debug.Assert(HasPath(diagnosticLocation));
 
-            FileLinePositionSpan span = diagnosticLocation.GetLineSpan();
+            FileLinePositionSpan span = diagnosticLocation.GetMappedLineSpan();
+            var path = diagnosticLocation.SourceTree is { } tree
+                ? tree.GetDisplayPath(diagnosticLocation.SourceSpan, resolver)
+                : span.Path;
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/Core/Portable/CommandLine/SarifV2ErrorLogger.cs:177]: I was mistaken. I had an impression that `/pathmap` *was* used here, the ambiguity between "path mapping" for line directives and the command line doesn't help here.

**Review by jaredpar — APPROVED** [review]

**Review by 333fred — APPROVED** [review]
