### PR TITLE
Reduce memory required for document change processing queues

### LINKED ISSUE #45452: TouchDocumentAction sequences have unbounded size
**Version Used**: Visual Studio 2019 version 16.6.2

**Steps to Reproduce**:

1. Open a project with a large source file
1. Using an external tool/script, repeatedly "touch" the large source file on disk

**Expected Behavior**:

Visual Studio eventually processes the file changes.

**Actual Behavior**:

Visual Studio crashes.

**Details**:

The `TouchDocumentAction` object representing an external change to a document that still needs to be documented has unbounded size. The two state fields need to be updated to use temporary storage instead of holding the entire contents of the file (both the old text and the new text) in memory until processing is complete.

https://github.com/dotnet/roslyn/blob/5bfb295d2abef1e427a382793b63caf9158ed466/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationAndGeneratorDriverTranslationAction_Actions.cs#L22-L23

### PR DESCRIPTION
**Pull request by sharwell**
Substantially improves the "robustness" of the IDE in handling branch switches in large solutions (e.g. Roslyn.sln).

Fixes #45452

### CODE REVIEW

**Comment by tmat** [comment]
@CyrusNajmabadi PTAL

File: src/VisualStudio/Core/Def/Implementation/Library/ObjectBrowser/AbstractObjectBrowserLibraryManager.cs [hunk 1]
```diff
@@ -94,10 +94,7 @@ private void OnWorkspaceChanged(object sender, WorkspaceChangeEventArgs e)
                     var oldDocument = e.OldSolution.GetDocument(e.DocumentId);
                     var newDocument = e.NewSolution.GetDocument(e.DocumentId);
 
-                    // make sure we do this in background thread. we don't care about ordering of events
-                    // we just need to refresh OB at some point if it ever needs to be updated
-                    // link to the bug tracking root cause  - https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=169649&_a=edit
-                    Task.Run(() => DocumentChangedAsync(oldDocument, newDocument));
+                    UpdateDocument(oldDocument, newDocument);
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Def/Implementation/Library/ObjectBrowser/AbstractObjectBrowserLibraryManager.cs:97]: this does worry me, as it will do all this processing synchronously.

Comment (CyrusNajmabadi) [reply src/VisualStudio/Core/Def/Implementation/Library/ObjectBrowser/AbstractObjectBrowserLibraryManager.cs:97]: nevermind.  all this does is update version numbers, which then end up causing updates down the line.

File: src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentState.cs [hunk 2]
```diff
@@ -97,7 +97,14 @@ protected static ValueSource<TextAndVersion> CreateStrongText(TextLoader loader,
...
 
         protected static ValueSource<TextAndVersion> CreateRecoverableText(TextAndVersion text, SolutionServices services)
-            => new RecoverableTextAndVersion(CreateStrongText(text), services.TemporaryStorage);
+        {
+            var result = new RecoverableTextAndVersion(CreateStrongText(text), services.TemporaryStorage);
+
+            // Ensure the recoverable text is saved in temporary storage
+            result.GetValue();
+
+            return result;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentState.cs:106]: the implications of this are not clear to me.  @jasonmalinowski do you know this part any better?

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentState.cs:106]: so we use memory mapped files for this right?  is there a concern about what this does for using up address space?

File: src/VisualStudio/Core/Def/Implementation/Library/ObjectBrowser/AbstractObjectBrowserLibraryManager.cs (hunk 1 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/Library/ObjectBrowser/AbstractObjectBrowserLibraryManager.cs:97]: In the past, it ran separately because it had actual work to do. Now it doesn't do that work so it can run synchronously again.

File: src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentState.cs (hunk 2 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentState.cs:106]: The call to `GetValue` is just forcing this line to run:

https://github.com/dotnet/roslyn/blob/a37aeb14c5608c3c213a6bc9ce0f9bc0b4c9fa10/src/Workspaces/Core/Portable/Workspace/Solution/RecoverableTextAndVersion.cs#L83

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentState.cs:106]: sure.  but there are two things that aren't clear to me:

1. how expensive all those .GetValue calls will be...
2. how expensive this is:

```c#
            _initialSource = null;
            _version = textAndVersion.Version;
            _filePath = textAndVersion.FilePath;
            _loadDiagnostic = textAndVersion.LoadDiagnostic;
            _text = new RecoverableText(this, textAndVersion.Text);
            _text.GetValue(CancellationToken.None); // force access to trigger save
            return textAndVersion;
```

i don't have a good sense of what the tradeoff might be ehre.

File: src/VisualStudio/Core/Def/Implementation/Library/ObjectBrowser/AbstractObjectBrowserLibraryManager.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/VisualStudio/Core/Def/Implementation/Library/ObjectBrowser/AbstractObjectBrowserLibraryManager.cs:97]: agreed.  this part seems fine.  we may overl agressive bump the version numbers here.  but i'm ok with that on a branch switch as all it means is that VS will eventually refresh this stuff.

File: src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentState.cs (hunk 2 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentState.cs:106]: > how expensive all those .GetValue calls will be...

In this case, the call to `_initialSource.GetValue` is negligible because `_initialSource` is a `ConstantValueSource<TextAndVersion>`. The overall cost of the new code is essentially the cost of:

https://github.com/dotnet/roslyn/blob/bd545a6c2efc9dcca054b926589f0336b1be32bc/src/Workspaces/Core/Portable/Workspace/Solution/RecoverableTextAndVersion.cs#L156-L157

We already perform this operation as part of the `TouchDocumentAction` processing, so there are two fundamental differences with this approach:

1. Saving to temporary storage occurs _earlier_, though it still occurs exactly one time in total.
2. For the case where processing queue depth triggers a Gen 2 GC, it may cause the weak reference to go away which then needs to be loaded from temporary storage during subsequent event processing. This case is unlikely to be slower than the previous approach because this is the scenario that most often led to crashes prior to this pull request.

Comment (jasonmalinowski) [reply src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentState.cs:111]: > For the case where processing queue depth triggers a Gen 2 GC

Just to check, are we seeing cases where we have CompilationTrackers with multiple TouchDocumentActions queued to the same document?

Comment (sharwell) [reply src/Workspaces/Core/Portable/Workspace/Solution/TextDocumentState.cs:111]: One of the heaps I have suggests yes.
