### PR TITLE
Block the use of IForegroundNotificationService when there is no foreground thread

### LINKED ISSUE #25930: [xUnit] [ERROR] - The result file Roslyn.Services.Editor.UnitTests.dll.xml for the metric 'xUnit.Net' is empty.
The following error appeared in 2 runs. Will update this issue if the same test fails again.

[xUnit] [ERROR] - The result file 'D:\j\workspace\windows_relea---c796cf20\Binaries\Release\UnitTests\EditorServicesTest\xUnitResults\Roslyn.Services.Editor.UnitTests.dll.xml' for the metric 'xUnit.Net' is empty. The result file has been skipped.

https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.7.x/job/windows_release_unit32/229/

https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/dev15.7.x/job/windows_release_unit64/227/

### PR DESCRIPTION
**Pull request by sharwell**
### Customer scenario

A correctly-written test could incorrectly fail during a build.

### Bugs this fixes

Fixes #25930

### Workarounds, if any

None

### Risk

Low. The conditions under which behavior is changed do not occur in production environments.

### Performance impact

Low. A new assertion is added on a code path that is only called when work is being queued on a different thread.

### Is this a regression from a previous update?

Yes.

### Root cause analysis

This is a race condition where the following sequence occurs:

1. A test uses `[UseExportProvider]` but does not use `IForegroundNotificationService`
2. The test does not use `[WpfFact]`
3. During `UseExportProviderAttribute.After`, an instance of `ForegroundNotificationService` is constructed [here](https://github.com/dotnet/roslyn/blob/88801fa234db8f1bd16b30c04971311915a04cd7/src/Workspaces/CoreTestUtilities/UseExportProviderAttribute.cs#L103), which [queues a background task](https://github.com/dotnet/roslyn/blob/88801fa234db8f1bd16b30c04971311915a04cd7/src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs#L38)
4. `UseExportProviderAttribute.After` is executed on a background thread, and reaches [this join operation](https://github.com/dotnet/roslyn/blob/88801fa234db8f1bd16b30c04971311915a04cd7/src/Workspaces/CoreTestUtilities/UseExportProviderAttribute.cs#L112) before the task starts running
5. The task starts running on the current thread, which results in an assertion because the "foreground thread" is also a thread pool thread

This change prevents the `IForegroundNotificationService` from being used to schedule foreground operations when there is no foreground thread, and then resolves the source of the crash in this case by avoiding the creation of the background operation.

### How was the bug found?

Automated testing

### Test documentation updated?

N/A

### CODE REVIEW

File: src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs [hunk 1]
```diff
@@ -35,7 +36,11 @@ public ForegroundNotificationService()
             _workQueue = new PriorityQueue();
             _lastProcessedTimeInMS = Environment.TickCount;
 
-            Task.Factory.SafeStartNewFromAsync(ProcessAsync, CancellationToken.None, TaskScheduler.Default);
+            // Only start the background processing task if foreground work is allowed
+            if (ForegroundKind != ForegroundThreadDataKind.Unknown)
```
Comment (heejaechang) [inline src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs]: don't we have test foreground notification service?

http://source.roslyn.io/#Roslyn.Services.Test.Utilities/Workspaces/TestForegroundNotificationService.cs,12

File: src/EditorFeatures/Test/SolutionCrawler/WorkCoordinatorTests.cs [hunk 2]
```diff
@@ -876,9 +876,13 @@ End Property
 
                 await WaitAsync(service, workspace);
 
-                Assert.Equal(1, worker.DocumentIds.Take(5).Select(d => d.ProjectId).Distinct().Count());
-                Assert.Equal(1, worker.DocumentIds.Skip(5).Take(5).Select(d => d.ProjectId).Distinct().Count());
-                Assert.Equal(1, worker.DocumentIds.Skip(10).Take(5).Select(d => d.ProjectId).Distinct().Count());
+                // The worker could have duplicate document IDs due to a race condition between the analyzer and the
```
Comment (heejaechang) [inline src/EditorFeatures/Test/SolutionCrawler/WorkCoordinatorTests.cs]: I am changing this test to wait for semantic change processor. leave the fix to me.

File: src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs (hunk 1 above)
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs]: Yes we should remove that but it's still on the backlog.

Comment (heejaechang) [reply src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs]: so. we no longer use mock on tests? is that it?

Comment (Therzok) [reply src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs]: Is it safe to silently discard these? Maybe a non-fatal error could be logged.

Comment (Therzok) [reply src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs]: cc @KirillOsenkov we used to have no logging for these notifications and we had them silently discarded. We need to verify we're doing the right thing here if this patch goes in.

Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs]: @Therzok I'm not sure what the specific concern is here. With this change, it is impossible to queue work for the background thread, hence why I didn't start the task.

Comment (Therzok) [reply src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs]: From what I see, the fallback thread data will not queue work. The concern is needing to know which things need to be setup to properly function.

We had code throwing in this service, that was masked, because we didn't have FatalError handlers setup.

Maybe it's worth notifying the consumer that the setup is not properly done?

As another point, I was thinking about filing a bug about FatalError not saying no handler is registered. Maybe ForehroundNotificationService should report that no thread handler is set?

Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs]: > From what I see, the fallback thread data will not queue work.

Correct. It will throw a synchronous exception immediately upon attempting to schedule the work.

Comment (Therzok) [reply src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs]: Ohhhh, I just noticed the `Contract.ThrowIfTrue` calls below. No worries from my side anymore!

**Comment by heejaechang** [comment]
so I guess when testing features that require foreground thread in unit test, we need to mark the unit test WpfTest or something?

**Comment by heejaechang** [comment]
@sharwell I am fine with change. but if unit test that require certain attribute if it needs foreground thread for whatever reason, it would be nice if there is some doc or wifi people can learn about our unit test magics.

**Comment by sharwell** [comment]
> so I guess when testing features that require foreground thread in unit test, we need to mark the unit test WpfTest or something?

This was already the case, but breaking the rule in the past would typically just make for a flaky test.

**Comment by Pilchie** [comment]
I'm hesitant about treating this as a test only change considering the number of times changes like this have broken scenarios like `devenv /build`.

**Comment by sharwell** [comment]
> shouldn't it then explicitly crash or throw with message saying [WpfTest] should be marked on test that require UI?

Technically this isn't the requirement. The requirement is that a "main thread" of some form be available which is not also a thread pool thread. Generally code which violates this will hit a different problem much earlier by accessing a foreground thread affinitized object that asserts in the constructor. This service is a special case because it needs to support construction when no foreground thread is available, provided work is not queued in it.

**Comment by heejaechang** [comment]
wouldn't it be safer to just asking any tests that require main thread to just always marked as [WpfFact] rather than one to know all these details whether [WpfFact] is okay to omitted in certain case? 

 if (ForegroundKind != ForegroundThreadDataKind.Unknown)

not sure how many people in our team actually know all the implication of ThreaddataKind being different ones.

**Comment by sharwell** [comment]
@heejaechang The general approach is adding a call to [`WpfTestCase.RequireWpfFact`](https://github.com/dotnet/roslyn/blob/a5a3d5246111c58f1b3237b1af7adf5bd5c19a91/src/EditorFeatures/TestUtilities/Threading/WpfTestCase.cs#L118) whenever it's required. It's a bit more challenging in this case because the assertion lives in test code but the `ForegroundNotificationService` implementation lives in production code.

Improved messaging around this is something we can add in the future, perhaps as part of #25805. Also, keep in mind that it's quite possible other tests that use `IForegroundNotificationService` already call `RequireWpfFact` as part of their use of some other type.
