### PR TITLE
Overridden member for a member of constructed generic type should be calculated based on overridden member for its definition.

### LINKED ISSUE #6148: Compilation error when generic type matches overload method that takes that type
This was initally found [in this StackOverflow post](http://stackoverflow.com/questions/33177145/visual-studio-2015-does-not-compile-when-generic-type-matches-overloaded-method).

The code below will compile in VS2013. However, in VS2015 it will give the following error:

> CS0534  C# does not implement inherited abstract member Validator\<object\>.DoValidate(object)

```c#
public abstract class Validator
{
    public abstract void DoValidate(object objectToValidate);
}

public abstract class Validator<T> : Validator
{
    public override void DoValidate(object objectToValidate)
    {
    }

    protected abstract void DoValidate(T objectToValidate);
}

public abstract class ValidatorBase<T> : Validator<T>
{
    protected override void DoValidate(T objectToValidate)
    {
    }
}

public class Required : ValidatorBase<object>
{
}
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #6148.

@dotnet/roslyn-compiler Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@tannergooding For some reason tests are not triggered for this PR.

**Comment by AlekseyTs** [comment]
@dotnet-bot Test this please.

**Comment by AlekseyTs** [comment]
CC @amcasey

**Comment by MattGertz** [comment]
Approved pending CRs.

File: src/Compilers/CSharp/Portable/Symbols/EventSymbol.cs [hunk 1]
```diff
@@ -117,7 +117,12 @@ public EventSymbol OverriddenEvent
             {
                 if (this.IsOverride)
                 {
-                    return (EventSymbol)OverriddenOrHiddenMembers.GetOverriddenMember();
+                    if (IsDefinition)
```
Comment (amcasey) [inline src/Compilers/CSharp/Portable/Symbols/EventSymbol.cs]: It seems reasonable that the behavior would be different for substituted symbols, but I'm concerned about the fact that ```OverriddenEvent``` and ```OverriddenOrHiddenMembers``` are out of sync.  For instance, is there a corresponding issue for hidden members?

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs [hunk 2]
```diff
@@ -52,6 +53,37 @@ internal sealed class OverriddenOrHiddenMembersResult
             }
         }
 
+        internal static Symbol GetOverriddenMember(Symbol substitutedOverridingMember, Symbol overriddenByDefinitionMember)
+        {
+            Debug.Assert(!substitutedOverridingMember.IsDefinition);
+
+            if ((object)overriddenByDefinitionMember != null)
+            {
+                NamedTypeSymbol overridenByDefinitionContainingTypeDefinition = overriddenByDefinitionMember.ContainingType.OriginalDefinition;
```
Comment (amcasey) [inline src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs]: Typo: riden

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs [hunk 3]
```diff
@@ -52,6 +53,37 @@ internal sealed class OverriddenOrHiddenMembersResult
...
+                for (NamedTypeSymbol baseType = substitutedOverridingMember.ContainingType.BaseTypeNoUseSiteDiagnostics; 
+                    (object)baseType != null; 
+                    baseType = baseType.BaseTypeNoUseSiteDiagnostics)
+                {
+                    if (baseType.OriginalDefinition == overridenByDefinitionContainingTypeDefinition)
+                    {
+                        if (baseType.IsDefinition)
```
Comment (amcasey) [inline src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs]: Can this happen for generic types?  Maybe if the subclass is nested in the base class?

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs [hunk 4]
```diff
@@ -52,6 +53,37 @@ internal sealed class OverriddenOrHiddenMembersResult
...
+                        {
+                            return overriddenByDefinitionMember.OriginalDefinition;
+                        }
+
+                        if (baseType == overriddenByDefinitionMember.ContainingType)
```
Comment (amcasey) [inline src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs]: Consider extracting a local for ```overriddenByDefinitionMember.ContainingType```.

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs (hunk 3 above)
Comment (amcasey) [inline src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs]: As discussed offline, yes that is the case this handles.

Comment (amcasey) [inline src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs]: I think this code path can be removed since ```SymbolAsMember``` already short-circuits the case where nothing needs to be done.

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs (hunk 4 above)
Comment (amcasey) [inline src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs]: Also, consider adding a comment that this is just an optimization of the expression below (which would also be correct).

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs [hunk 5]
```diff
@@ -52,6 +53,37 @@ internal sealed class OverriddenOrHiddenMembersResult
...
+                        {
+                            return overriddenByDefinitionMember;
+                        }
+
+                        return overriddenByDefinitionMember.OriginalDefinition.SymbolAsMember(baseType);
+                    }
+                }
```
Comment (amcasey) [inline src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs]: Falling off the end of this loop is impossible, right?  Consider throwing ```ExceptionUtilities.Unreachable```.

File: src/Compilers/CSharp/Portable/Symbols/EventSymbol.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/EventSymbol.cs]: We haven't run into any issues with hidden members yet. And it is fine to have multiple hidden members, or for a hidden member to hide an overridden member due to generic substitution. For the purpose of this API, however, we need to figure out the only truly overridden member, even if it is considered hidden due to generic substitution. To the best of my understanding, hidden members and an overridden member serve different purpose within compiler and it is fine for them to disagree within constructed types.

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs (hunk 2 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs]: Thanks, will fix.

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs (hunk 3 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs]: Yes and yes.

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs (hunk 4 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs]: Sure.

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs [hunk 6]
```diff
@@ -52,6 +53,37 @@ internal sealed class OverriddenOrHiddenMembersResult
             }
         }
 
+        internal static Symbol GetOverriddenMember(Symbol substitutedOverridingMember, Symbol overriddenByDefinitionMember)
```
Comment (amcasey) [inline src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs]: It feels like what this method actually does is find the version of ```overriddenByDefinitionMember``` in the corresponding base class of ```substitutedOverridingMember```.  I think it might be clearer to express it that way: ```FindCorrespondingBaseTypeMember(Symbol member, NamedTypeSymbol type)```.

File: src/Compilers/VisualBasic/Portable/Symbols/Source/SourcePropertySymbol.vb [hunk 7]
```diff
@@ -734,6 +734,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols
                                                                             isOverrides:=True, isWithEvents:=Me.IsWithEvents))
                 End If
 
+                Debug.Assert(IsDefinition)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourcePropertySymbol.vb]: I am going to push this assert into OverriddenMember property. It will make it easier to avoid similar bugs in the future.

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourcePropertySymbol.vb]: Scratch this. We don't have required information for asserting there, but I covered all the call sites that we have right now and I will add a doc comment.

**Comment by amcasey** [comment]
After our offline discussion, I'm satisfied that this is the best way to address this issue for update 1.  :+1:

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs (hunk 6 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs]: I think there is a benefit in having both methods (this one and the one below it) to have the same name, discoverability, etc.

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs (hunk 5 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs]: Good idea.

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs (hunk 3 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersResult.cs]: Will remove this special case.

**Comment by AlekseyTs** [comment]
Ping. @dotnet/roslyn-compiler Please review.

**Comment by VSadov** [comment]
LGTM

**Comment by gafter** [comment]
LGTM
