### PR TITLE
Report use-site diagnostics if System.ValueTuple base type is an error type

### LINKED ISSUE #16879: RC 26127.3: Debugger broken when using tuples
**Version Used**: 26127.3

**Steps to Reproduce**:

1.  Place a breakpoint at the ending brace of the Main method bellow:
```
    class Program
    {
        static void Main(string[] args)
        {
            var a = 77;
            var b = (5, 6);
        }
    }
```
2. Run and wait for the breakpoint to hit. 
3. Hover over `a`. No info tooltip will appear.
4. Right-click `a` and select Quick Watch. The following error will be displayed:
```error CS8182: Predefined type 'ValueTuple`2' must be a struct```

The above behavior reproduces for any variable/field used in the method body, *except* for the tuple ones.
When removing the code that uses tuples, debugging works normally.

### PR DESCRIPTION
**Pull request by cston**
Report use-site diagnostics, if any, from `System.ValueTuple`  base type rather than `"'ValueTuple' must be a struct"`.

This may result in a clearer error message for the user when an assembly is missing. And it also allows the EE to recognize such cases at runtime so the EE can load the missing assembly explicitly.

Fixes #16879.

### CODE REVIEW

**Comment by cston** [comment]
@dotnet/roslyn-compiler please review.

File: src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs [hunk 1]
```diff
@@ -892,21 +892,39 @@ protected virtual Cci.IModuleReference TranslateModule(ModuleSymbol module, Diag
...
+            if (!_reportedErrorTypesMap.Add(namedTypeSymbol))
+            {
+                return;
+            }
+
+            var location = syntaxNodeOpt == null ? NoLocation.Singleton : syntaxNodeOpt.Location;
+            if ((object)declaredBase != null)
+            {
+                HashSet<DiagnosticInfo> useSiteDiagnostics = null;
+                declaredBase.AddUseSiteDiagnostics(ref useSiteDiagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs]: >declaredBase.AddUseSiteDiagnostics(ref useSiteDiagnostics); [](start = 16, length = 59)

This feels more complicated than it should be. We can call declaredBase.GetUseSiteDiagnostic() and add diagnostics if its result is non-null. There is also a helper in Binder ```internal static bool ReportUseSiteDiagnostics(Symbol symbol, DiagnosticBag diagnostics, Location location)``` that can be used instead, I think.

File: src/Compilers/VisualBasic/Portable/Emit/SymbolTranslator.vb [hunk 2]
```diff
@@ -203,21 +203,34 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Emit
...
+                Return
+            End If
+
+            Dim location = If(syntaxNodeOpt Is Nothing, NoLocation.Singleton, syntaxNodeOpt.GetLocation())
+            If declaredBase IsNot Nothing Then
+                Dim useSiteDiagnostics As HashSet(Of DiagnosticInfo) = Nothing
+                declaredBase.AddUseSiteDiagnostics(useSiteDiagnostics)
+                If diagnostics.Add(location, useSiteDiagnostics) Then
+                    Return
                 End If
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Emit/SymbolTranslator.vb]: Similar to C#, this code can be simplified to:
```
            Dim useSiteDiagnostic = declaredBase.GetUseSiteErrorInfo()
            If useSiteDiagnostic IsNot Nothing Then
                diagnostics.Add(useSiteDiagnostic, location)
                Return
            End If
``` 

There is also a helper in the binder ```Friend Shared Function ReportUseSiteError(diagBag As DiagnosticBag, syntax As SyntaxNodeOrToken, symbol As Symbol) As Boolean``` that can be cloned to work with location instead of SyntaxNodeOrToken.

**Comment by AlekseyTs** [comment]
Done with review pass.

File: src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs (hunk 1 above)
Comment (cston) [inline src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs]: Fixed.

File: src/Compilers/VisualBasic/Portable/Emit/SymbolTranslator.vb (hunk 2 above)
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Emit/SymbolTranslator.vb]: Fixed.

File: src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs [hunk 3]
```diff
@@ -892,21 +892,39 @@ protected virtual Cci.IModuleReference TranslateModule(ModuleSymbol module, Diag
...
+            if (!_reportedErrorTypesMap.Add(namedTypeSymbol))
+            {
+                return;
+            }
+
+            var location = syntaxNodeOpt == null ? NoLocation.Singleton : syntaxNodeOpt.Location;
+            if ((object)declaredBase != null)
+            {
+                var diagnosticInfo = declaredBase.GetUseSiteDiagnostic();
+                if (diagnosticInfo != null)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs]: >if (diagnosticInfo != null) [](start = 16, length = 27)

Use-site diagnostics in C# can be a warning, we probably want to report only errors.

File: src/Compilers/VisualBasic/Portable/Emit/SymbolTranslator.vb [hunk 4]
```diff
@@ -203,21 +203,34 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Emit
...
 
+            ' Try to decrease noise by not complaining about the same type over and over again.
+            If Not _reportedErrorTypesMap.Add(namedTypeSymbol) Then
+                Return
+            End If
+
+            Dim location = If(syntaxNodeOpt Is Nothing, NoLocation.Singleton, syntaxNodeOpt.GetLocation())
+            If declaredBase IsNot Nothing Then
+                Dim diagnosticInfo = declaredBase.GetUseSiteErrorInfo()
+                If diagnosticInfo IsNot Nothing Then
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Emit/SymbolTranslator.vb]: >If diagnosticInfo IsNot Nothing Then [](start = 16, length = 36)

VB is fine here, this is always an error or Nothing.

File: src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs (hunk 3 above)
Comment (cston) [inline src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs]: Added `ValueTupleBase_AssemblyUnification` tests.

**Comment by cston** [comment]
@dotnet/roslyn-compiler, @jcouv, please provide second review. Thanks.

**Comment by jcouv** [comment]
@cston You're good to go

**Comment by mirhagk** [comment]
Is there any workaround for now until this is fixed?

**Comment by jcouv** [comment]
There is no reliable workaround, but I saw some people having success by downgrading the reference to their ValueTuple package to the pre-release version of the package.
