### PR TITLE
Copy any CommentTrivia to simple using statements 

### LINKED ISSUE #37678: IDE0063 deletes code comments when simplifying using statement
**Version Used**: VS16.3.0 Preview 1.0

**Steps to Reproduce**:

0. .NET Core 3.0 Preview 7 console project
1. Have this C# code:
```c#
            using (var graphQLClient = new GraphQLClient(ServerUrl))
            {
                var allMoviesResponse = await graphQLClient.PostQueryAsync(@"{ movies { title } }");
                Console.WriteLine(allMoviesResponse.Data.movies[0].title);

                //            var response = await graphQLClient.PostAsync(new GraphQLRequest
                //            {
                //                Query = @"{
                //    movies
                //    {
                //        title
                //    }
                //}"
                //            });
            }
```
2. The `using` statement will get a triple-dot thingy, with a suggestion to simplify the `using` statement:
image
3. If you accept the suggestion, it deletes the code comments in the block:
```c#
            using var graphQLClient = new GraphQLClient(ServerUrl);
            var allMoviesResponse = await graphQLClient.PostQueryAsync(@"{ movies { title } }");
            Console.WriteLine(allMoviesResponse.Data.movies[0].title);
```

**Expected Behavior**:
The code fix shouldn't remove code comments because it has nothing to do with the fix at all.

**Actual Behavior**:
The code fix removes code comments.

### PR DESCRIPTION
**Pull request by 06needhamt**
Fixes #37678 

I am very new to the Roslyn codebase so please forgive me if this is not the correct way to approach this issue. I have updated the simple using code fix to copy all the CommentTrivia from inside the block to before the simplified using statement. I would like to make it copy the comments to the respective location in the block but can't seem to work out how.

Any feedback would be welcomed.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
> I am very new to the Roslyn codebase

Welcome!  and thanks for the contribution! :)

File: src/Features/CSharp/Portable/UseSimpleUsingStatement/UseSimpleUsingStatementCodeFixProvider.cs [hunk 1]
```diff
@@ -84,11 +84,25 @@ private static IEnumerable<StatementSyntax> Expand(UsingStatementSyntax usingSta
...
+
             for (int i = 0, n = result.Count; i < n; i++)
             {
                 result[i] = result[i].WithAdditionalAnnotations(Formatter.Annotation);
             }
 
+            result[0] = result[0].WithLeadingTrivia(comments);
+
             return result;
         }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/UseSimpleUsingStatement/UseSimpleUsingStatementCodeFixProvider.cs]: We'd definitely need tests for this change.  They can be added in https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/CSharpTest/UseSimpleUsingStatement/UseSimpleUsingStatementTests.cs

File: src/Features/CSharp/Portable/UseSimpleUsingStatement/UseSimpleUsingStatementCodeFixProvider.cs [hunk 2]
```diff
@@ -84,11 +84,25 @@ private static IEnumerable<StatementSyntax> Expand(UsingStatementSyntax usingSta
...
+            var comments = new List<SyntaxTrivia>();
+
+            decendentTrivia.ForEach(x =>
+            {
+                if (x.Kind() == SyntaxKind.SingleLineCommentTrivia || x.Kind() == SyntaxKind.MultiLineCommentTrivia)
+                {
+                    comments.Add(x);
+                    comments.Add(SyntaxFactory.EndOfLine(Environment.NewLine));
+                }
+            });
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/UseSimpleUsingStatement/UseSimpleUsingStatementCodeFixProvider.cs]: this seems like it would copy *alllllll* the comments inide the using statement (including trivia associated with internal statements).  this would cause duplications.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseSimpleUsingStatement/UseSimpleUsingStatementCodeFixProvider.cs]: So, given the bug that we're trying to fix, what we want to do instead is take the leading trivia of the *close curly* of the using statement, and we want to add it as leading trivia to the token that follows the using statement.  that way:

```c#
using (var x = y)
{
   // comment
}

return whatever;
```

Becomes:

```c#
using var x = y;

// comment

return whatever;
```

not:

```c#
// comment
using var x = y;

return whatever;
```

**Comment by CyrusNajmabadi** [comment]
I can provide more info if you want.  Or you can reach out at gitter.im/dotnet/roslyn, or in the #roslyn channel in discord.gg/csharp

**Comment by 06needhamt** [comment]
@CyrusNajmabadi Thanks for the feedback I have changed the behaviour and added a test

File: src/Features/CSharp/Portable/UseSimpleUsingStatement/UseSimpleUsingStatementCodeFixProvider.cs [hunk 3]
```diff
@@ -84,9 +84,23 @@ private static IEnumerable<StatementSyntax> Expand(UsingStatementSyntax usingSta
             var result = new List<StatementSyntax>();
             Expand(result, usingStatement);
 
+            var blockStatement = usingStatement.ChildNodes().Where(x => x.Kind() == SyntaxKind.Block);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/UseSimpleUsingStatement/UseSimpleUsingStatementCodeFixProvider.cs]: so this won't work for a lot of scenarios.  for example:

```c#
using (var x = y)
using (var a = b)
{
     // whatever
}
```

You'll probably need to update `private static void Expand(List<StatementSyntax> result, UsingStatementSyntax usingStatement)` instead.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseSimpleUsingStatement/UseSimpleUsingStatementCodeFixProvider.cs]: what you want to do in that function is collect the trivia to preserve when handling the block-syntax case.  it will need to return that trivia here.  that trivia will then need to be returned higher up the stack up to:

```c#
                if (statementToUpdate is UsingStatementSyntax usingStatement &&
                    usingStatement.Declaration != null)
                {
                    var updatedStatements = currentBlock.Statements.ReplaceRange(
                        statementToUpdate,
                        Expand(usingStatement));
                    return currentBlock.WithStatements(updatedStatements);
                }
```

At that point, it will need to take the trivia and assign it to the next statement in the block

**Comment by 06needhamt** [comment]
@CyrusNajmabadi I have updated the fix to work as you described. However the tests I added seem to fail although the expected output matches what I get when running the code fix. Is there something I am doing wrong/missing.

Thank you for you're patience.

**Comment by CyrusNajmabadi** [comment]
I'll try to look into this in the next 1-2 days. Ping me again if I don't!

**Comment by 06needhamt** [comment]
Thanks 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CyrusNajmabadi** [comment]
@06needhamt I've made the requisite fixes here: https://github.com/CyrusNajmabadi/roslyn/tree/patch-37678

You can merge them into your branch.  Cheers!

**Comment by 06needhamt** [comment]
I’ve merged them in. Thanks for your help. I hope to make more contributions in the future.

**Comment by CyrusNajmabadi** [comment]
> . I hope to make more contributions in the future.

That would be fantastic!

**Comment by CyrusNajmabadi** [comment]
@jinujoseph can a buddy be assigned for this new community contributer?  Thanks!

**Comment by CyrusNajmabadi** [comment]
Also, can you update the title?  It is no longer correct?

**Comment by 06needhamt** [comment]
@CyrusNajmabadi I have updated the title.

File: src/Features/CSharp/Portable/UseSimpleUsingStatement/UseSimpleUsingStatementCodeFixProvider.cs [hunk 4]
```diff
@@ -47,9 +48,11 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
             var topmostUsingStatements = diagnostics.Select(d => (UsingStatementSyntax)d.AdditionalLocations[0].FindNode(cancellationToken)).ToSet();
             var blocks = topmostUsingStatements.Select(u => (BlockSyntax)u.Parent);
 
+            // Process blocks in reverse order so we rewrite from inside-to-outside with nested
+            // usings.d
```
Comment (JoeRobich) [inline src/Features/CSharp/Portable/UseSimpleUsingStatement/UseSimpleUsingStatementCodeFixProvider.cs]: nit
```suggestion
            // usings.
```

**Comment by CyrusNajmabadi** [comment]
@JoeRobich can this be merged in now?  Thanks!

**Comment by CyrusNajmabadi** [comment]
Thanks @06needhamt !
