### PR TITLE
Consider variance when merging nullability of tuple elements

### LINKED ISSUE #31864: Tuple names shouldn't affect nullability of value types
**Version Used**: 
3.0.0-beta2-18616-01

**Steps to Reproduce**:

```C#
using System;

class C
{
    public C()
    {
        DateTime? earliest = DateTime.MaxValue;
        string? earliestPath = null;
        bool hasOutput = false;

        var x = hasOutput
            ? (earliest, earliestPath)
            : (null, null);
    }
}
```

**Expected Behavior**:
No warnings

**Actual Behavior**:
Program.cs(11,17,13,27): warning CS8626: No best nullability for operands of conditional expression '(DateTime? earliest, string? earliestPath)' and '(DateTime?, string?)'.

### PR DESCRIPTION
**Pull request by cston**
Fixes #31864.

### CODE REVIEW

**Comment by cston** [comment]
@jcouv, @gafter, @dotnet/roslyn-compiler, please review.

File: src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs [hunk 1]
```diff
@@ -1465,8 +1465,55 @@ internal override TypeSymbol MergeNullability(TypeSymbol other, VarianceKind var
...
+                {
+                    haveChanges = true;
+                }
+            }
+
+            if (haveChanges)
+            {
+                TypeMap substitution = new TypeMap(typeParameters, allTypeArguments.ToImmutable());
+                mergedType = substitution.SubstituteNamedType(typeDefinition);
+            }
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs]: >} [](start = 12, length = 1)

`else mergedType = typeA;` ?

**Comment by gafter** [comment]
Please take an action item to confirm this with Mads or the LDM.

File: src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs [hunk 2]
```diff
@@ -1465,8 +1465,55 @@ internal override TypeSymbol MergeNullability(TypeSymbol other, VarianceKind var
...
+
+            allTypeArguments.Free();
+            return haveChanges;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs]: Please update the speclet

File: src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs [hunk 3]
```diff
@@ -1465,8 +1465,55 @@ internal override TypeSymbol MergeNullability(TypeSymbol other, VarianceKind var
...
+            var typeArgumentsB = typeB.TypeArgumentsNoUseSiteDiagnostics;
+            bool haveChanges = false;
+            for (int i = 0; i < n; i++)
+            {
+                TypeSymbolWithAnnotations typeArgumentA = typeArgumentsA[i];
+                TypeSymbolWithAnnotations typeArgumentB = typeArgumentsB[i];
+                TypeSymbolWithAnnotations merged = typeArgumentA.MergeNullability(typeArgumentB, variance, out bool hadMismatch);
+                hadNullabilityMismatch |= hadMismatch;
+                allTypeArguments.Add(merged);
+                if (!typeArgumentA.IsSameAs(merged))
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs]: I didn't understand the use of `IsSameAs` here. That's doing reference equality, no? I expected `Equals` with some comparison options instead.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 4]
```diff
@@ -40032,38 +40023,108 @@ static void G(object? t1, object t2, string? u1, string u2)
...
+interface IIn<in T> { }
+interface IOut<out T> { }
+class C
+{
+    static T F<T>(T x, T y) => throw null;
+    static I<T> CreateI<T>(T t) => throw null;
+    static void G1(I<(object, string)> x1, I<(object?, string?)> y1)
+    {
+        var z1 = CreateI(A.F)/*T:I<(object, string)>!*/;
+        F(x1, x1)/*T:I<(object!, string!)>!*/;
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Consider numbering lines that have warnings

File: src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs (hunk 3 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs]: `IsSameAs` and `hasChanges` are only used as an optimization to avoid creating unnecessary `TypeSymbol` instances in the caller.

File: src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs (hunk 2 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs]: Updated.

**Comment by cston** [comment]
@gafter, #31864 has been marked for Language Design.
