### PR TITLE
Fix constraint cycle through nested type of base type

### LINKED ISSUE #68223: Recursive type triggers Roslyn stack overflow and crashes Visual Studio
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Recursive-type-triggers-Roslyn-stack-ove/10364034)._

---
1.  create a new console app on .NET 7.0, and
    
2.  paste in this (buggy) code below the standard “Hello, World!” lines:
    
    ```  
    interface ISetup<T> where T : new() { T Data { get; set; } }
    interface Base { public abstract class Nest { } }
    interface Base<N> : Base, ISetup<N> where N : Base<N>.Nest { }
    ```
    
3.  watch code analysis features breaking with exit code -1073741571 in a flood of yellow info bars,
    
4.  move the caret about in the code editor for `Program.cs`, and
    
5.  observe Visual Studio crashing.
    
(The attached screenshot was taken shortly before the info bars appeared.)

Also, `dotnet build` fails with 7000 and some errors.

Note that the last type constraint can be simplified and corrected to `Base.Nest, new()`, which makes both Visual Studio and `dotnet build` work.  
```

---
### Original Comments

#### Lars Hammer on 5/16/2023, 04:54 PM: 

(private comment, text removed)
#### Lars Hammer on 5/16/2023, 05:10 PM: 

(private comment, text removed)
#### Feedback Bot on 5/16/2023, 07:26 PM: 

(private comment, text removed)
#### Lars Hammer on 5/17/2023, 05:36 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #68223

The "unusual" logic we are trying to preserve is quite reasonable, although reading the original code might give one an incorrect impression that C# 8 compat was the motivation for the behavior.

Here's a relevant scenario ([SharpLab](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQGED2AbbEDGMAlpgHYAyRMECU2yANDCEdgwCYgDUAPgMSk4uKMDwACCKRF4AsACgA9ArEAhKMghiYATwAOm3VFoBbCNQRjsUfAGtkYqGIACAJjH4yyGLSKkYAOjEAUSoACxoxQWFRTUwLUjJUKKsYrT1NIwBzOFM/ew8hdjFgTTgNdn95JTEAFXCkMDjNZDhgLyo4YlJMh1IxTFEiADcSMrT9BwRs3JgxJBbsGHtfXv7BkcwxnX1KuScAZjFfczBrTQBJPxpT/AgARgAeGoA+eQBveTEv50OasQAFBCYXRiN5iTJmADcYg0MGhAF9Pt95AIhClxOwiMhpBAkV8Ds47gA2ZwAFjEAFkXAAKS4nM6PdDPMTsGjDCDsACUeNB8hRyRxEikMR53xZbKGHP8gOBYgAvJE0ZCeYi5Kr+WjBZIcVVlGoNOMDEYoKZzEd8p5vFBfBytJhIokBaltpoAOToV27ap1GgQRpIGGtdrwLo9KB9AbYYajewuybTSSzeZCJZHPqOBKkJKa53pL3KACCYDNdDYWnC/QQREyvjo4rAvioJD6WK0EFwvh6WwrcYA7mRXbMwHBSIRm2JdED9AhsNojmAHIrouI+76J0CRqyKvICcdrmcxHT97cXE9mb36po/iAxOh3jyCX8ZSCwRC4TCoWJVWKNcvNJjsRFOQxQJJxiTJSkaSPBAbggU8mXFKtJS5HkPjkX90U0bUgLFMVWSQqVn3lJdsGhapeyMUhO1vABlAAOIkXAAVhvdBwwSWYPFISUEFmZJLCoGg6xge1M2zP85j9X1R00F1djFVV1TkVEJOw2Q9kOVxb1BL95CAA)):
```cs
#nullable enable
// Base type parameter lacks a class constraint. Either nullable or non-nullable type arguments could be used.
// Therefore substituting an oblivious type argument results in an oblivious type.
public interface Interface1<T>
{
    public T Prop { get; set; }
    
#nullable disable
    public static void M2(Interface1<C> derived)
    {

#nullable enable
        derived.Prop = null;
    }
}

#nullable enable
// Base type parameter is constrained to non-nullable type 'C'.
// Therefore substituting an oblivious type argument results in a non-nullable type.
// After all, the original definition is telling us the type won't function properly if a nullable type were provided.
public interface Interface2<T> where T : C
{
    public T Prop { get; set; }
    
#nullable disable
    public static void M2(Interface2<C> derived)
    {

#nullable enable
        derived.Prop = null; // warning CS8625: Cannot convert null literal to non-nullable reference type.
    }
}

#nullable enable
public class C { }
```

The trouble is, that this means that the nullable annotation of a type argument depends on the type constraints of the type parameter. As shown in the linked issue, when the type parameter is used as a type argument in one of its own constraints, you can get a cycle.

We break the cycle by identifying when a type argument's nullable annotation can't be determined until after binding type constraints, and making the nullable annotation lazy in that case.

### CODE REVIEW

**Comment by RikkiGibson** [comment]
I think bootstrap build of BuildValidator is failing. Likely related to mishandling copying of custom modifiers on the type.

```
Stack Trace
   at Microsoft.CodeAnalysis.CommandLine.ExitingTraceListener.Exit(String originalMessage)
   at Microsoft.CodeAnalysis.CommandLine.ExitingTraceListener.WriteLine(String message)
   at System.Diagnostics.TraceInternal.Fail(String message)
   at System.Diagnostics.Debug.Assert(Boolean condition)
   at Microsoft.CodeAnalysis.CSharp.Symbols.CustomModifierUtils.CopyTypeCustomModifiers(TypeSymbol sourceType, TypeSymbol destinationType, AssemblySymbol containingAssembly)
   at Microsoft.CodeAnalysis.CSharp.Symbols.CustomModifierUtils.CopyMethodCustomModifiers(MethodSymbol sourceMethod, MethodSymbol destinationMethod, TypeWithAnnotations& returnType, ImmutableArray`1& customModifiers, ImmutableArray`1& parameters, Boolean alsoCopyParamsModifier)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceOrdinaryMethodOrUserDefinedOperatorSymbol.MethodChecks(TypeWithAnnotations returnType, ImmutableArray`1 parameters, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceOrdinaryMethodSymbol.MethodChecks(BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberMethodSymbol.LazyMethodChecks()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberMethodSymbol.get_OverriddenOrHiddenMembers()
   at Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol.get_OverriddenMethod()
   at Microsoft.CodeAnalysis.CSharp.Symbols.OverriddenMethodTypeParameterMap.GetOverriddenMethod(SourceOrdinaryMethodSymbol overridingMethod)
   at Microsoft.CodeAnalysis.CSharp.Symbols.OverriddenMethodTypeParameterMapBase.get_OverriddenMethod()
   at Microsoft.CodeAnalysis.CSharp.Symbols.OverriddenMethodTypeParameterMapBase.GetOverriddenTypeParameter(Int32 ordinal)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceOverridingMethodTypeParameterSymbol.get_OverriddenTypeParameter()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceOverridingMethodTypeParameterSymbol.get_HasReferenceTypeConstraint()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceTypeParameterSymbolBase.GetSynthesizedNullableAttributeValue()
   at Microsoft.CodeAnalysis.CSharp.Symbol.GetCommonNullableValues(CSharpCompilation compilation, MostCommonNullableValueBuilder& builder)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberMethodSymbol.ComputeNullableContextValue()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberMethodSymbol.GetLocalNullableContextValue()
   at Microsoft.CodeAnalysis.CSharp.Symbol.GetCommonNullableValues(CSharpCompilation compilation, MostCommonNullableValueBuilder& builder)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.ComputeNullableContextValue()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.GetLocalNullableContextValue()
   at Microsoft.CodeAnalysis.CSharp.Symbol.GetCommonNullableValues(CSharpCompilation compilation, MostCommonNullableValueBuilder& builder)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.ComputeNullableContextValue()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.GetLocalNullableContextValue()
   at Microsoft.CodeAnalysis.CSharp.Symbol.GetNullableContextValue()
   at Microsoft.CodeAnalysis.CSharp.Symbol.ShouldEmitNullableContextValue(Byte& value)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberMethodSymbol.AfterAddingTypeMembersChecks(ConversionsBase conversions, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceOrdinaryMethodOrUserDefinedOperatorSymbol.AfterAddingTypeMembersChecks(ConversionsBase conversions, BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.CheckSpecialMemberErrors(BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.AfterMembersChecks(BindingDiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Symbol.ForceCompleteMemberByLocation(SourceLocation locationOpt, Symbol member, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamespaceSymbol.<>c__DisplayClass68_1.<ForceComplete>b__0(Int32 i)
   at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass6_0`1.<WithCurrentUICulture>b__0(T param)
   at Roslyn.Utilities.RoslynParallel.<>c__DisplayClass1_0.<For>g__errorHandlingBody|0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

File: src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs [hunk 1]
```diff
@@ -919,6 +938,103 @@ internal override void TryForceResolve(bool asValueType)
...
+            }
+
+            internal override TypeWithAnnotations AsNullableReferenceType(TypeWithAnnotations type)
+            {
+                return CreateNonLazyType(type.DefaultType, NullableAnnotation.Annotated, _customModifiers);
+            }
+
+            internal override TypeWithAnnotations AsNotNullableReferenceType(TypeWithAnnotations type)
+            {
+                var defaultType = type.DefaultType;
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs:1013]: Some of these impls are copied straight from the NonLazyType. I guess we could extract them into "Core"-suffixed methods if we wanted.

File: src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs [hunk 2]
```diff
@@ -865,6 +883,7 @@ public NonLazyType(ImmutableArray<CustomModifier> customModifiers)
 
             internal override bool IsResolved => true;
             internal override TypeSymbol GetResolvedType(TypeSymbol defaultType) => defaultType;
+            internal override NullableAnnotation GetResolvedAnnotation(NullableAnnotation nullableAnnotation) => nullableAnnotation;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs:886]: >nullableAnnotation [](http://example.com/codeflow?start=90&length=18)

Perhaps `defaultAnnotation`.

File: src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs [hunk 3]
```diff
@@ -45,15 +45,18 @@ internal Boxed(TypeWithAnnotations value)
         /// </summary>
         private readonly Extensions _extensions;
 
-        public readonly NullableAnnotation NullableAnnotation;
+        /// <summary>
+        /// The nullable annotation, unless overridden by _extensions.
+        /// </summary>
+        public readonly NullableAnnotation DefaultNullableAnnotation;
 
         private TypeWithAnnotations(TypeSymbol defaultType, NullableAnnotation nullableAnnotation, Extensions extensions)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs:53]: >nullableAnnotation [](http://example.com/codeflow?start=79&length=18)

Consider renaming to `defaultAnnotation`.

File: src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs [hunk 4]
```diff
@@ -919,6 +938,103 @@ internal override void TryForceResolve(bool asValueType)
...
+            internal override SpecialType GetSpecialType(TypeSymbol typeSymbol) => typeSymbol.SpecialType;
+            internal override bool IsRestrictedType(TypeSymbol typeSymbol, bool ignoreSpanLikeTypes) => typeSymbol.IsRestrictedType(ignoreSpanLikeTypes);
+            internal override bool IsStatic(TypeSymbol typeSymbol) => typeSymbol.IsStatic;
+            internal override bool IsVoid(TypeSymbol typeSymbol) => typeSymbol.IsVoidType();
+            internal override bool IsSZArray(TypeSymbol typeSymbol) => typeSymbol.IsSZArray();
+            internal override bool IsRefLikeType(TypeSymbol typeSymbol) => typeSymbol.IsRefLikeType;
+
+            internal NullableAnnotation GetResolvedAnnotationCore()
+            {
+                if (_typeParameter.IsNotNullable == true)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs:968]: >IsNotNullable [](http://example.com/codeflow?start=35&length=13)

Can `IsNotNullable` return `false`? If not, consider asserting.

File: src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs [hunk 5]
```diff
@@ -919,6 +938,103 @@ internal override void TryForceResolve(bool asValueType)
...
+
+            internal override void ReportDiagnosticsIfObsolete(TypeWithAnnotations type, Binder binder, SyntaxNode syntax, BindingDiagnosticBag diagnostics)
+            {
+                type.ReportDiagnosticsIfObsoleteCore(binder, syntax, diagnostics);
+            }
+
+            internal override bool TypeSymbolEquals(TypeWithAnnotations type, TypeWithAnnotations other, TypeCompareKind comparison)
+            {
+                return type.TypeSymbolEqualsCore(other, comparison);
+            }
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs:1025]: >} [](http://example.com/codeflow?start=12&length=1)

Minor: Consider adding a blank line after the method.

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs:968]: this property needs a doc :)

File: src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs [hunk 6]
```diff
@@ -919,6 +938,103 @@ internal override void TryForceResolve(bool asValueType)
...
+            private readonly ImmutableArray<CustomModifier> _customModifiers;
+            private readonly TypeParameterSymbol _typeParameter;
+            private int _resolved;
+
+            public LazySubstitutedType(ImmutableArray<CustomModifier> customModifiers, TypeParameterSymbol typeParameter)
+            {
+                Debug.Assert(!customModifiers.IsDefault);
+                _customModifiers = customModifiers;
+                _typeParameter = typeParameter;
+                _resolved = (int)NullableAnnotation.Ignored;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs:956]: Does the initial value of `_resolved` matter in any way? Consider using `-1` instead of a seemingly meaningful (but in fact not) value

File: src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs (hunk 4 above)
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs:968]: nit: consider leaving a comment here, as this innocuous line is the computation we're trying to delay

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs:968]: I tried to write up a scenario where it would return false but I wasn't able to get it to hit the expected code path.

```cs
#nullable enable

class C { }

interface I<T> where T : C?,
#nullable disable
        I<T> { }
```

I expected that the usage of `I<T>` within the constraint clause would make us hit this code path with `_typeParameter.IsNotNullable == false`.

File: src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs (hunk 6 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs:956]: No, it's just a sentinel.

File: src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs [hunk 7]
```diff
@@ -244,6 +252,7 @@ internal TypeWithAnnotations MergeEquivalentTypes(TypeWithAnnotations other, Var
 
         public bool IsResolved => _extensions?.IsResolved != false;
         public TypeSymbol Type => _extensions?.GetResolvedType(DefaultType);
+        public NullableAnnotation NullableAnnotation => _extensions?.GetResolvedAnnotation(DefaultNullableAnnotation) ?? default;
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs:255]: This matches existing behavior of `NullableAnnotation` field. Basically, what happens when we access this property on `default(TypeWithAnnotations)`. (I think if we weren't defending against that, we wouldn't use a conditional access here.)

Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs:255]: If we used `-1` for the "uninitialized" value of `DefaultNullableAnnotation`, we could assert that that value is never returned here.
I'm not sure we can do that with `Ignored`.

File: src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs [hunk 8]
```diff
@@ -482,14 +491,27 @@ internal TypeWithAnnotations SubstituteTypeCore(AbstractTypeMap typeMap)
...
-                }
-                else
+                Debug.Assert(NullableAnnotation == NullableAnnotation.NotAnnotated);
+                Debug.Assert(newTypeWithModifiers.NullableAnnotation is NullableAnnotation.NotAnnotated or NullableAnnotation.Oblivious);
+                if (newTypeWithModifiers.NullableAnnotation == NullableAnnotation.Oblivious)
                 {
-                    newAnnotation = newTypeWithModifiers.NullableAnnotation;
+                    // When the type parameter disallows a nullable reference type as a type argument (i.e. IsNotNullable),
+                    // we want to drop any Oblivious annotation from the substituted type and use NotAnnotated instead,
+                    // to reflect the "stronger" claim being made by the type parameter.
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs:500]: Thanks much for the clarifying comment :-)

File: src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs [hunk 9]
```diff
@@ -919,6 +938,103 @@ internal override void TryForceResolve(bool asValueType)
...
+
+            internal NullableAnnotation GetResolvedAnnotationCore()
+            {
+                if (_typeParameter.IsNotNullable == true)
+                {
+                    return NullableAnnotation.NotAnnotated;
+                }
+                else
+                {
+                    return NullableAnnotation.Oblivious;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs]: nit: May deserve a comment (we only use this lazy extension for oblivious type parameter scenario). Alternatively, we could add "Oblivious" in the name of the type, but that might be less clear

**Review by jcouv — COMMENTED** [review]
Done with review (iteration 7)

File: src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs [hunk 10]
```diff
@@ -919,6 +942,110 @@ internal override void TryForceResolve(bool asValueType)
...
+                Debug.Assert(defaultAnnotation == NullableAnnotation.Ignored);
+                if (_resolved == Unresolved)
+                {
+                    Interlocked.CompareExchange(ref _resolved, value: (int)getResolvedAnnotationCore(), comparand: Unresolved);
+                }
+
+                Debug.Assert(_resolved != Unresolved);
+                return (NullableAnnotation)_resolved;
+
+                NullableAnnotation getResolvedAnnotationCore()
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs:983]: static?

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 9) modulo static question

File: src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs (hunk 10 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs:983]: I feel satisfied with the current factoring (capturing 'this'). Thanks

Comment (jcouv) [reply src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs:983]: Oh, I'd missed that. Thanks
