### PR TITLE
Prevent DeriveArgument methods from trying to access parameter symbols that don't exist.

### LINKED ISSUE #8901: IndexOutOfRangeException at Microsoft.CodeAnalysis.CSharp.BoundCall.DeriveArgument while running Operation analyzers
1. Clean your RoslynDev hive
2. Get latest sources of roslyn and roslyn-analyzers and build
3. devenv /rootsuffix RoslynDev
4. Open Roslyn.sln and source file `Compilation.cs` in project `CodeAnalysis` (I am unable to come up with a minimal repro that doesn't require opening Roslyn.sln)
5. Attach a debugger to this instance of VS.
6. Paste the below code at the beginning of class definition for `Compilation` and wait for a few seconds till the diagnostics are computed - you should hit the crash.

```C#
    private object F(Assembly assembly)
    {
        var type = (from t in assembly.GetTypes()
                    select t.Attributes).FirstOrDefault();
        return type;
    }
```

> >	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler) Line 151	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessCompilationEventsCoreAsync(Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, bool prePopulatedEventQueue, System.Threading.CancellationToken cancellationToken) Line 770	C#
 	[Resuming Async Method]	
 	[External Code]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundCall.DeriveArgument.AnonymousMethod__0(Microsoft.CodeAnalysis.CSharp.BoundExpression argument) Line 175	C#
 	[External Code]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundCall.DeriveArgument(int parameterIndex, int argumentIndex, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.BoundExpression> boundArguments, System.Collections.Immutable.ImmutableArray<string> argumentNames, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.RefKind> argumentRefKinds, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Symbols.ParameterSymbol> parameters, Microsoft.CodeAnalysis.SyntaxNode invocationSyntax) Line 148	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundCall.Microsoft.CodeAnalysis.Semantics.IInvocationExpression.ArgumentsInSourceOrder.get() Line 54	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitInvocationExpression(Microsoft.CodeAnalysis.Semantics.IInvocationExpression operation) Line 196	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(Microsoft.CodeAnalysis.Semantics.OperationVisitor visitor) Line 77	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(Microsoft.CodeAnalysis.IOperation operation) Line 34	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationExtensions.OperationCollector.Visit(Microsoft.CodeAnalysis.IOperation operation) Line 64	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitVariableDeclaration(Microsoft.CodeAnalysis.Semantics.IVariableDeclaration operation) Line 55	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.VariableDeclaration.Accept(Microsoft.CodeAnalysis.Semantics.OperationVisitor visitor) Line 35	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(Microsoft.CodeAnalysis.IOperation operation) Line 34	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationExtensions.OperationCollector.Visit(Microsoft.CodeAnalysis.IOperation operation) Line 64	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitArray<Microsoft.CodeAnalysis.Semantics.IVariableDeclaration>(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Semantics.IVariableDeclaration> list) Line 21	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitVariableDeclarationStatement(Microsoft.CodeAnalysis.Semantics.IVariableDeclarationStatement operation) Line 50	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundLocalDeclaration.Accept(Microsoft.CodeAnalysis.Semantics.OperationVisitor visitor) Line 614	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(Microsoft.CodeAnalysis.IOperation operation) Line 34	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationExtensions.OperationCollector.Visit(Microsoft.CodeAnalysis.IOperation operation) Line 64	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitArray<Microsoft.CodeAnalysis.IOperation>(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.IOperation> list) Line 21	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitBlockStatement(Microsoft.CodeAnalysis.Semantics.IBlockStatement operation) Line 45	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(Microsoft.CodeAnalysis.Semantics.OperationVisitor visitor) Line 52	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(Microsoft.CodeAnalysis.IOperation operation) Line 34	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationExtensions.OperationCollector.Visit(Microsoft.CodeAnalysis.IOperation operation) Line 64	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Semantics.OperationExtensions.DescendantsAndSelf(Microsoft.CodeAnalysis.IOperation operation) Line 32	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver<Microsoft.CodeAnalysis.CSharp.SyntaxKind>.GetOperationsToAnalyze(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.IOperation> operationBlocks) Line 1777	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver<Microsoft.CodeAnalysis.CSharp.SyntaxKind>.ExecuteDeclaringReferenceActions(Microsoft.CodeAnalysis.SyntaxReference decl, int declarationIndex, Microsoft.CodeAnalysis.Diagnostics.SymbolDeclaredCompilationEvent symbolEvent, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, bool shouldExecuteSyntaxNodeActions, bool shouldExecuteOperationActions, bool shouldExecuteCodeBlockActions, bool shouldExecuteOperationBlockActions, bool isInGeneratedCode, System.Threading.CancellationToken cancellationToken) Line 1542	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver<Microsoft.CodeAnalysis.CSharp.SyntaxKind>.ExecuteDeclaringReferenceActions(Microsoft.CodeAnalysis.Diagnostics.SymbolDeclaredCompilationEvent symbolEvent, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisStateOpt, bool isGeneratedCodeSymbol, System.Threading.CancellationToken cancellationToken) Line 1401	C#

### PR DESCRIPTION
**Pull request by JohnHamby**
This change set is expected to fix #8901 . There are no tests provided in the change set because attempts to produce a small repro have failed. The fix is to take defensive action against a situation the compilers are expected to screen out--semantically invalid invocations that include an argument that doesn't match a parameter.

@mavasani , does this change set actually fix #8901 ?

### CODE REVIEW

**Comment by mavasani** [comment]
@JohnHamby I found a minimal repro - which matches your description above. It's essentially just creating a **Portable** class library with the below code snippet. Property `Attributes` is not present in portable profile, hence the semantic error. Compiler generates a BoundCall with HasErrors=true and error symbol with name `C.FirstOrDefault`.

```C#
    private object F(Assembly assembly)
    {
        var type = (from t in assembly.GetTypes()
                    select t.Attributes).FirstOrDefault();
        return type;
    }
```

File: src/Compilers/CSharp/Portable/BoundTree/Expression.cs [hunk 1]
```diff
@@ -150,6 +150,7 @@ private static IArgument DeriveArgument(int parameterIndex, int argumentIndex, I
                 (argument) =>
                 {
                     string name = !argumentNames.IsDefaultOrEmpty ? argumentNames[argumentIndex] : null;
+                    Symbols.ParameterSymbol parameter = parameterIndex < parameters.Length ? parameters[parameterIndex] : null;
```
Comment (mavasani) [inline src/Compilers/CSharp/Portable/BoundTree/Expression.cs]: Should we bail out at the start of the method and return `boundArguments[argumentIndex]` if `HasErrors` is true? I presume we cannot guarantee a correct argument to parameter mapping in presence of errors.

**Comment by mavasani** [comment]
@JohnHamby this also repros for a regular non-portable console application, just replace the member access `.Attributes` with a non-existent member.

File: src/Compilers/CSharp/Portable/BoundTree/Expression.cs (hunk 1 above)
Comment (genlu) [inline src/Compilers/CSharp/Portable/BoundTree/Expression.cs]: I think we can't return `boundArguments[argumentIndex]` since it is not an `IArgument`. We sure can bail early by creating and returning an `Argument` if HasErrors is true. Either way is OK to me.

**Comment by genlu** [comment]
@dotnet-bot retest prtest/win/dbg/eta please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/4098/
// Retest reason: Known flaky test https://github.com/dotnet/roslyn/issues/8747

**Comment by genlu** [comment]
:+1: 
And I think this should be in stabilization as well.

File: src/Compilers/CSharp/Portable/BoundTree/Expression.cs (hunk 1 above)
Comment (JohnHamby) [inline src/Compilers/CSharp/Portable/BoundTree/Expression.cs]: Relying on HasErrors worries me. The more I think about this issue the more worried I get. My current belief:

Implementations of IOperation should treat the bound trees as unreliable in the sense that they are not guaranteed to obey a structural contract. Properties that one wouldn't expect to ever be null (e.g. the operands of a binary operator) should be tested for nullness. Arrays shouldn't be trusted to be of the expected size. Etc.

Further, an IOperation implementation should obey a structural contract, because otherwise analyzers will crash. This implies introducing Invalid objects where the bound trees do not supply valid values. For example, if an operand of a binary operator is missing in the bound trees, an IOperation implementation should supply an Invalid operand. If a symbol reference in the bound trees does not bind to a symbol, an IOperation implementation should supply an Invalid symbol of some kind.

If we don't do this either IOperation implementations or analyzers that use them will be subject to random crashes when a compiler produces a malformed bound tree.

There isn't time to do this hardening for Update 2.

**Comment by JohnHamby** [comment]
Elevating a concern that GitHub buried in an "outdated diff":

The more I think about this issue the more worried I get. My current belief:

Implementations of IOperation should treat the bound trees as unreliable in the sense that they are not guaranteed to obey a structural contract. Properties that one wouldn't expect to ever be null (e.g. the operands of a binary operator) should be tested for nullness. Arrays shouldn't be trusted to be of the expected size. Etc.

Further, an IOperation implementation should obey a structural contract, because otherwise analyzers will crash. This implies introducing Invalid objects where the bound trees do not supply valid values. For example, if an operand of a binary operator is missing in the bound trees, an IOperation implementation should supply an Invalid operand. If a symbol reference in the bound trees does not bind to a symbol, an IOperation implementation should supply an Invalid symbol of some kind.

If we don't do this either IOperation implementations or analyzers that use them will be subject to random crashes when a compiler produces a malformed bound tree.

There isn't time to do this hardening for Update 2.

**Comment by JohnHamby** [comment]
I just pushed a new commit that is a touch more robust.

I wasn't able to produce a standalone unit test for this issue, even with @mavasani 's suggestion. Someone who knows how to manage adding references to unit test compilations could do it.

Widening the review audience to @mavasani @genlu @srivatsn @ManishJayaswal @Pilchie because this is likely to end up as an Ask Mode ask.
