### PR TITLE
Fix nullable analysis of lambdas within conditional expressions

### LINKED ISSUE #40561: Incorrect CS8604 with captured variable in ternary operator
**Version Used**: 
VisualStudio.16.Release/16.4.2+29613.14
C# Tools 3.4.1-beta4-19610-02+c4e5d138903b899477649a17f197abd2bcb22f9e

**Steps to Reproduce**:
In the following program, `s` in never reassigned later in `M2` so the compiler should know that it's never `null` when `M1` is called, even though it's captured. Writing the equivalent code using `if/else` doesn't produce a warning.

```cs
#nullable enable

using System;

class C {
    void M1(string s) { }
    Action? M2(string? s) => s != null ? () => M1(s) : (Action?) null;
}
```

**Expected Behavior**:
No warning.

**Actual Behavior**:
Warning CS8604: Possible null reference argument for parameter 's' in 'void C.M1(string s)'.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Fixes #40561

For reasons I don't fully understand, analysis of conditional expressions is broken apart into phases, which can be seen in the implementation of `VisitConditionalOperatorCore`. It seems like the `convertResult` calls at the end can end up visiting the lambda over again, and when we do this without threading in the appropriate state, we can get spurious warnings.

Please review @333fred @dotnet/roslyn-compiler.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 1]
```diff
@@ -51575,6 +51575,62 @@ static void F()
...
+
+    static Action? M5(string? s)
+    {
+        return s != null
+            ? local(s = null, () => M0(s)) // 1
+            : (Action?)null;
+
+        Action local(string? s, Action a1)
+        {
+            return a1;
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:51623]: Can you add a variation where `s` is assigned null in the local function itself?

**Review by 333fred — APPROVED** [review]

**Review by jaredpar — APPROVED** [review]
