### PR TITLE
Ignore non-delegate types binding lambda arguments for error recovery

### LINKED ISSUE #17208: "Unassigned local" error for reference to "out var" in "group by"
The compiler incorrectly reports `CS0165` for `y == null`:
```
using System.Linq;
class C
{
    static void M()
    {
        var c = from x in new[] { 1, 2, 3 }
            group x > 1 && F(out var y) && y == null
            by x;
    }
    static bool F(out object o)
    {
        o = null;
        return true;
    }
}
```
```
(7,38): error CS8201: Out variable and pattern variable declarations are not allowed within a query clause.
(7,44): error CS0165: Use of unassigned local variable 'y'
```

### PR DESCRIPTION
**Pull request by cston**
Fixes #17208.

### CODE REVIEW

**Comment by cston** [comment]
@dotnet/roslyn-compiler please review.

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs [hunk 1]
```diff
@@ -1181,7 +1181,7 @@ private ImmutableArray<BoundExpression> BuildArgumentsForErrorRecovery(AnalyzedA
                             foreach (var parameterList in parameterListList)
                             {
                                 var parameterType = GetCorrespondingParameterType(analyzedArguments, i, parameterList);
-                                if (parameterType?.Kind == SymbolKind.NamedType)
+                                if (parameterType.IsDelegateType() || parameterType.IsExpressionTree())
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: >parameterType.IsDelegateType() || parameterType.IsExpressionTree() [](start = 36, length = 66)

Consider using GetDelegateType helper instead to be consistent in behavior with lambda binding.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: It looks like this change also broke some tests because it doesn't handle parameterType == null.
