### PR TITLE
Fixed handling of variable declarations inside of for loops in related code fixers

### LINKED ISSUE #40336: 'CSharpRemoveUnusedVariableCodeFixProvider' encountered an error and has been disabled
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/843951/csharpremoveunusedvariablecodefixprovider-encounte.html)._

---
Here is the stack trace:
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.ForStatementSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.LocalDeclarationStatementSyntax'.
   at Microsoft.CodeAnalysis.RemoveUnusedVariable.AbstractRemoveUnusedVariableCodeFixProvider`3.MergeNodesToRemove(HashSet`1 nodesToRemove)
   at async Microsoft.CodeAnalysis.RemoveUnusedVariable.AbstractRemoveUnusedVariableCodeFixProvider`3.FixAllAsync[TLocalDeclarationStatement,TVariableDeclarator,TVariableDeclaration](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0. <GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

---
#### Visual Studio Feedback System on 12/4/2019, 10:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by lameox**
fixes #40336.

This PR introduces two fixes for `AbstractRemoveUnusedValuesCodeFixProvider` and `AbstractRemoveUnusedVariableCodeFixProvider` respectively when dealing with variables declared inside a `ForStatementSyntax`. Both classes made the wrong assumption that a `LocalDeclarationStatementSyntax` was always present in the tree above a `VariableDeclaratorSyntax`.

Also added some tests that cover these cases.

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/RemoveUnusedParametersAndValues/RemoveUnusedValueAssignmentTests.cs [hunk 1]
```diff
@@ -6405,6 +6405,31 @@ void M(int j, int[] array)
...
+        [WorkItem(40336, "https://github.com/dotnet/roslyn/issues/40336")]
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsRemoveUnusedValues)]
+        public async Task RedundantAssignment_ForStatementVariableDeclaration()
+        {
+            await TestInRegularAndScriptAsync(
+@"class C
+{
+    void M()
+    {
+        for (int [|i|] = 0; ; )
```
Comment (mavasani) [inline src/EditorFeatures/CSharpTest/RemoveUnusedParametersAndValues/RemoveUnusedValueAssignmentTests.cs]: Can you please add a test for non-constant value, i.e.: `for (int [|i|] = GetValue(); ; )`

Comment (lameox) [reply src/EditorFeatures/CSharpTest/RemoveUnusedParametersAndValues/RemoveUnusedValueAssignmentTests.cs]: At the moment the suggested fix is replacing `i` with a discard pattern so `for (int [|i|] = GetValue(); ; )` would turn into `for (int _ = GetValue(); ; )`. 

Should we fix the expression to `for (GetValue(); ; )` since `GetValue()` might have side effects or completely get rid of the call (which might lead to unexpected removal of code when fixing all in locations the user might not immediately expect)?

Comment (lameox) [reply src/EditorFeatures/CSharpTest/RemoveUnusedParametersAndValues/RemoveUnusedValueAssignmentTests.cs]: Correction: After investigating a bit it seems the `for (int _ = GetValue(); ; )` [is intended](https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs#L461-L463). I therefore just added two tests for the current functionality.

Comment (mavasani) [reply src/EditorFeatures/CSharpTest/RemoveUnusedParametersAndValues/RemoveUnusedValueAssignmentTests.cs]: > I therefore just added two tests for the current functionality.

Thanks, yes I presume your change should not have any effect on these cases, but worth adding the unit tests validating the current behavior for completeness.

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs [hunk 2]
```diff
@@ -633,6 +640,7 @@ void InsertLocalDeclarationStatement(TLocalDeclarationStatementSyntax declaratio
             bool ShouldRemoveStatement(TLocalDeclarationStatementSyntax localDeclarationStatement, out SeparatedSyntaxList<SyntaxNode> variables)
             {
                 Debug.Assert(removeAssignments);
+                Debug.Assert(localDeclarationStatement != null, "We should never get a null here.");
```
Comment (mavasani) [inline src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs]:
```suggestion
                Debug.Assert(localDeclarationStatement != null);
```

IMO, the message is implicit from the condition.

Comment (lameox) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs]: I was trying to adhere to the section in the coding conventions [here](https://github.com/dotnet/roslyn/wiki/Contributing-Code#coding-conventions) statong that a message should always be provided. As I am a mew contributer: Is there some guide to follow on when specific rules apply other than common sense?

Comment (mavasani) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs]: Ah, thanks for following the guidelines so precisely. In general, we avoid the message for null checks, but recommend adding a message where it seems useful. We should likely update the contributor guidelines accordingly.

**Comment by lameox** [comment]
retest roslyn-CI please

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs [hunk 3]
```diff
@@ -422,7 +422,14 @@ protected sealed override async Task FixAllAsync(Document document, ImmutableArr
                             nodesToRemove.Add(variableDeclarator);
 
                             // Local declaration statement containing the declarator might be a candidate for removal if all its variables get marked for removal.
-                            candidateDeclarationStatementsForRemoval.Add(variableDeclarator.GetAncestor<TLocalDeclarationStatementSyntax>());
+                            // The check for null is necessary for cases where the ancestor tree doesn't contain any TLocalDeclarationStatementSyntax nodes.
+                            // This is the case for variables declared inside a ForStatementSyntax' VariableDeclaration.
+                            // The null would lead to a NPE inside syntaxFacts.GetVariablesOfLocalDeclarationStatement later on when ShouldRemoveStatement passes it along.
+                            var ancestor = variableDeclarator.GetAncestor<TLocalDeclarationStatementSyntax>();
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs]: this doesn't really work.  Consider:

```c#
Action a = () => {
    for (int i = ...
};
```

You can be in a variable declarator that will still be found inside a local declaration statement.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs]: Also... my prefernece would be that we just actually support the for-case.   Is there a reason we can't mark and remove the variable inside of a for if it isn't actually used?

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs]: Also, please add a test for the above case.

Comment (lameox) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs]: This should still work, unless i am overlooking somthing:
__________________
### Option 1
The containing lambda is used:
```cs 
    void M()
    {
        Action a = () =>
        {
            for (int [|i|] = 0; ; )
            {
            }
        };
        a();
    }
```
we only populate the candidates in this code. Later on, specifically [here](https://github.com/dotnet/roslyn/blob/dcf4d060f17dae42f3e6ac211a7f6c8436517b09/src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs#L645-L653), we filter out the false positive again because the lambdas body is not unused and therefore not contained in nodesToRemove.
image
__________________
### Option 2
The containing lambda itself is unused:
```cs
    void M()
    {
        Action a = () =>
        {
            for (int i = 0; ; )
            {
            }
        };
    }
```
In this case we don't actually report a IDE0059 diagnostic on the `i` but rather a CS0219 which would then be fixable by the `CSharpUnusedVariableCodeFixProvider` which has its base class fixed by this PR as well.
image

Now this might be a bug in and of itself, which i am not sure about.

For now i added two further tests for both cases above, however i am not sure if i am using the `TestDiagnosticMissingAsync` correctly or if i am supposed to use another helper.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs]: This is only working because of external effects we can't guarantee.  It could absolutely be hte case in the future that we report both an unused delegate and an unused for-variable.

We should strive ot make our code actually correct, not pseudo-correct by virtue of how some other external systems work.

Thanks! :)

Comment (lameox) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs]: Should this also happen in this PR?
I debugged through the code a bit to actually find why the IDE0059 isn't reported and it looks like the analyzer reports the lambda and then doesn't concern itself with the body any further, presumably because a fix all would actually remove the whole body since it is a non-used value itself.
For a proper fix we would therefore need to step into the lambda and analyze it further. My guess is that the fix should go somwhere around [here](https://github.com/dotnet/roslyn/blob/dcf4d060f17dae42f3e6ac211a7f6c8436517b09/src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs#L183)?

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs]: > Should this also happen in this PR?

I'm not sure what you mean by 'this'. 

All i'm saying is: the check that walks up arbitrary high in the ancestor clause to see if we're in a local var decl, is incorrect.  We should not do that.  Random cases (like the one i mentioned) would trigger as true, even though they shoudl be false.

The case you're asking is:  is this a variable decl in the foreach statement.  
that's what the code should check for.  it shouldn't infer that by looking to see if it's a local-var-decl or not, as that's not conclusive information.

Comment (lameox) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedValuesCodeFixProvider.cs]: Oh sorry I misunderstood your previous comment. I guess I never questioned the original implementation which I just wrapped in a null check for the fix.

File: src/Features/Core/Portable/RemoveUnusedVariable/AbstractRemoveUnusedVariableCodeFixProvider.cs [hunk 4]
```diff
@@ -154,8 +154,12 @@ private void MergeNodesToRemove(HashSet<SyntaxNode> nodesToRemove)
             var candidateLocalDeclarationsToRemove = new HashSet<TLocalDeclarationStatement>();
             foreach (var variableDeclarator in nodesToRemove.OfType<TVariableDeclarator>())
             {
-                var localDeclaration = (TLocalDeclarationStatement)variableDeclarator.Parent.Parent;
-                candidateLocalDeclarationsToRemove.Add(localDeclaration);
+                //NOTE: we can't cast directly here since in for loops the daclarator.Parent.Parent
+                //is the ForStatementSyntax instead of the TLocalDeclarationStatement
+                if (variableDeclarator.Parent.Parent is TLocalDeclarationStatement localDeclaration)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/RemoveUnusedVariable/AbstractRemoveUnusedVariableCodeFixProvider.cs]: wont' this not work for VB?

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/RemoveUnusedVariable/AbstractRemoveUnusedVariableCodeFixProvider.cs]: speaking of which, do we need VB tests for this scenario?

Comment (lameox) [reply src/Features/Core/Portable/RemoveUnusedVariable/AbstractRemoveUnusedVariableCodeFixProvider.cs]: I don't think it is a problem in VB since vb doesn't allow specifying a `for` with more than one declared variable and said variable is always "used" by the looping logic. Even if it werent (i.e. `For index = 0 To 0`) removing the variable/declaration would result in illegal VB syntax.

Comment (lameox) [reply src/Features/Core/Portable/RemoveUnusedVariable/AbstractRemoveUnusedVariableCodeFixProvider.cs]: Also, do you know why the `roslyn-CI` and `roslyn-integration-CI` pipelines are seemingly stuck on `Waiting for status to be reported`? Should i be worried?

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/RemoveUnusedVariable/AbstractRemoveUnusedVariableCodeFixProvider.cs]: > I don't think it is a problem in VB since it doesn't allow specifying a for with more than one declared variable and said variable is always "used" by the looping logic. 

So the latter is again requiring that we depend on external behavior that we cannot guarantee.  If things ever change such that the variable is *not* used by teh looping logic, then this will not work.  We shouldn't encode C#isms into shared code.

**Comment by CyrusNajmabadi** [comment]
> Also, do you know why the roslyn-CI and roslyn-integration-CI pipelines are seemingly stuck on Waiting for status to be reported? Should i be worried?

Nope.  PAging @jasonmalinowski @dotnet/roslyn-infrastructure

File: src/Features/Core/Portable/RemoveUnusedVariable/AbstractRemoveUnusedVariableCodeFixProvider.cs (hunk 4 above)
Comment (lameox) [reply src/Features/Core/Portable/RemoveUnusedVariable/AbstractRemoveUnusedVariableCodeFixProvider.cs]: I thought the readson i gave after addressed that. But you are right the syntax might change in the future to possibly allow a for statement without variable declaration.

Sorry if you have to repeat yourself. I think i am scared of breaking something and therefore try to change as little as possible.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/RemoveUnusedVariable/AbstractRemoveUnusedVariableCodeFixProvider.cs]: You have *zero* to be sorry about.  These are all great questions.  And your concerns are totally understandable. :)   Ths is why we have PRs.  So you can share your ideas and thoughts, but also hear the other side of the coin to give you confidence about things you might have been wary about.

Note: if it will help, you can also reach people in realtime at gitter.im/dotnet/roslyn or discord.gg/csharp (#roslyn)

Comment (lameox) [reply src/Features/Core/Portable/RemoveUnusedVariable/AbstractRemoveUnusedVariableCodeFixProvider.cs]: I will have to look into the gitter and discord sometime soon :)
I added the requested abstract method and am returning nothing from VB for now which can then be changed should the allowed syntax change.

**Comment by JoeRobich** [comment]
> Also, do you know why the roslyn-CI and roslyn-integration-CI pipelines are seemingly stuck on Waiting for status to be reported? Should i be worried?

@lameox This is affecting everyone today, not just you. The status of individual CI jobs should be getting reported appropriately.

**Comment by lameox** [comment]
@JoeRobich should i just retest this and if so how do i go about triggering a retest? just `Please retest this`?

**Comment by lameox** [comment]
close and reopen to trigger a retest

**Comment by lameox** [comment]
@mavasani do i need to do anything else on this PR or is it fine now?

File: src/Features/VisualBasic/Portable/RemoveUnusedVariable/VisualBasicRemoveUnusedVariableCodeFixProvider.vb [hunk 5]
```diff
@@ -41,5 +41,9 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.RemoveUnusedVariable
         Protected Overrides Function GetVariables(localDeclarationStatement As LocalDeclarationStatementSyntax) As SeparatedSyntaxList(Of SyntaxNode)
             Return localDeclarationStatement.Declarators
         End Function
+
+        Protected Overrides Function GetCandidateLocalDeclarationForRemoval(declarator As ModifiedIdentifierSyntax) As LocalDeclarationStatementSyntax
+            Return Nothing
```
Comment (mavasani) [inline src/Features/VisualBasic/Portable/RemoveUnusedVariable/VisualBasicRemoveUnusedVariableCodeFixProvider.vb]: Why is this returning Nothing?

File: src/Features/VisualBasic/Portable/RemoveUnusedParametersAndValues/VisualBasicRemoveUnusedValuesCodeFixProvider.vb [hunk 6]
```diff
@@ -52,5 +52,9 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.RemoveUnusedParametersAndValues
             ' VB does not support compound assignments.
             Throw New NotImplementedException()
         End Function
+
+        Protected Overrides Function GetCandidateLocalDeclarationForRemoval(declarator As VariableDeclaratorSyntax) As LocalDeclarationStatementSyntax
+            Return TryCast(declarator.Parent, LocalDeclarationStatementSyntax)
```
Comment (mavasani) [inline src/Features/VisualBasic/Portable/RemoveUnusedParametersAndValues/VisualBasicRemoveUnusedValuesCodeFixProvider.vb]: Can we add a unit test to validate this code path?

File: src/Features/VisualBasic/Portable/RemoveUnusedVariable/VisualBasicRemoveUnusedVariableCodeFixProvider.vb (hunk 5 above)
Comment (mavasani) [reply src/Features/VisualBasic/Portable/RemoveUnusedVariable/VisualBasicRemoveUnusedVariableCodeFixProvider.vb]: Can we add a unit test to validate this code path?

File: src/Features/VisualBasic/Portable/RemoveUnusedParametersAndValues/VisualBasicRemoveUnusedValuesCodeFixProvider.vb (hunk 6 above)
Comment (lameox) [reply src/Features/VisualBasic/Portable/RemoveUnusedParametersAndValues/VisualBasicRemoveUnusedValuesCodeFixProvider.vb]: This is already hit by the existing tests, for example [this one].(https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/VisualBasicTest/RemoveUnusedParametersAndValues/RemoveUnusedValueAssignmentTests.vb#L405)

File: src/Features/VisualBasic/Portable/RemoveUnusedVariable/VisualBasicRemoveUnusedVariableCodeFixProvider.vb (hunk 5 above)
Comment (lameox) [reply src/Features/VisualBasic/Portable/RemoveUnusedVariable/VisualBasicRemoveUnusedVariableCodeFixProvider.vb]: Originally i thought that the code in the base class only was necessary for C# since it was clearly beeing hit and causing the original issue that this PR is for.

However i just debugged a bit and it seems to me we can get rid of `MergeNodesToRemove` in the base class altogether, since the subsequent `RemoveNode` code seems to deal with unmerged nodes just fine (which might originally not have been the case). If i comment out the complete body for `MergeNodesToRemove` i still get all green unit tests for both vb and c#. 

Should i keep it and maybe add a comment here in the vb implementation to signal why it returns nothing, or should i just get rid of the unnecessary code?

Comment (mavasani) [reply src/Features/VisualBasic/Portable/RemoveUnusedVariable/VisualBasicRemoveUnusedVariableCodeFixProvider.vb]: I am not able to convince myself by looking at the code that `MergeNodesToRemove` is redundant. I also think the correct implementation for VB here should find the parenting local declaration statement, similar to the implementation in the previous file. What happens if you change the implementation to match that? Also can you confirm if existing tests are hitting this path?

File: src/Features/VisualBasic/Portable/RemoveUnusedParametersAndValues/VisualBasicRemoveUnusedValuesCodeFixProvider.vb (hunk 6 above)
Comment (mavasani) [reply src/Features/VisualBasic/Portable/RemoveUnusedParametersAndValues/VisualBasicRemoveUnusedValuesCodeFixProvider.vb]: Thanks, then it should be fine.

File: src/Features/VisualBasic/Portable/RemoveUnusedVariable/VisualBasicRemoveUnusedVariableCodeFixProvider.vb (hunk 5 above)
Comment (lameox) [reply src/Features/VisualBasic/Portable/RemoveUnusedVariable/VisualBasicRemoveUnusedVariableCodeFixProvider.vb]: I can confirm that this path is beeing hit by existing tests.

> I am not able to convince myself by looking at the code that MergeNodesToRemove is redundant. I also think the correct implementation for VB here should find the parenting local declaration statement, similar to the implementation in the previous file.

will do.

Comment (lameox) [reply src/Features/VisualBasic/Portable/RemoveUnusedVariable/VisualBasicRemoveUnusedVariableCodeFixProvider.vb]: @mavasani Since the implementations are now matching between C# and VB i pulled the code up into the base class and got rid of the function altogether. Tests are still passing.

**Comment by mavasani** [comment]
@lameox Thank you for the contribution!
