### PR TITLE
Fix nameof with restricted arguments.

### LINKED ISSUE #10467: unsafe fixed buffers. nameof doesn't work
6.0 (from vs 2015): 

```
unsafe struct Struct1
{
  public fixed char MessageType[50];

  public override string ToString()
  {
    return nameof(MessageType) + "=Struct1";// CS1666
  }
}
```

### PR DESCRIPTION
**Pull request by TyOverby**
Closes #10467

### CODE REVIEW

**Comment by TyOverby** [comment]
@dotnet/roslyn-compiler @agocke 

Review please!

File: src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs [hunk 1]
```diff
@@ -1168,5 +1168,66 @@ public void NameofTypeParameterInParameterInitializer()
...
+  }
+
+  public void DoSomething(out char[] x)
+  {
+    x = new char[] {};
+    Action a = () => { System.Console.WriteLine(nameof(x)); };
+  }
+}";
+            var compilation = CreateCompilationWithMscorlib45(source, null,
+                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary).WithAllowUnsafe(true)).VerifyDiagnostics();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs]: Should run it and observe what nameof produces.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs [hunk 2]
```diff
@@ -1168,5 +1168,66 @@ public void NameofTypeParameterInParameterInitializer()
...
+
+  public override string ToString()
+  {
+    return nameof(MessageType);
+  }
+
+  public void DoSomething(out char[] x)
+  {
+    x = new char[] {};
+    Action a = () => { System.Console.WriteLine(nameof(x)); };
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs]: This scenario is applicable to VB as well. Does it work? Consider adding a test.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs]: Make sure one doesn't exist before, though.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs [hunk 3]
```diff
@@ -1168,5 +1168,66 @@ public void NameofTypeParameterInParameterInitializer()
 }";
             var compilation = CreateCompilationWithMscorlib45(source).VerifyDiagnostics();
         }
+
+        [Fact, WorkItem(10467, "https://github.com/dotnet/roslyn/issues/10467")]
+        public void NameofFixedBuffer()
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs]: While you are in this file please add `[CompilerTrait(CompilerFeature.NameOf)]` to the class.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs [hunk 4]
```diff
@@ -1168,5 +1168,66 @@ public void NameofTypeParameterInParameterInitializer()
...
+        {
+            var source =
+@"
+using System;
+unsafe struct Struct1
+{
+  public fixed char MessageType[50];
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs]: What happens when I try and do `nameof` on `MessageType` from outside `Struct1` in a context that is safe?  Should that work?  We should check on that and add a test.

Comment (TyOverby) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs]: Since nameof is 100% compile-time, I think it should be safe.  I'll add tests for this.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs (hunk 1 above)
Comment (TyOverby) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs]: Done.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs (hunk 3 above)
Comment (TyOverby) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs]: Which assembly has `CompilerTrait` and `CompilerFeature`?

Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs]: It's in test utilities: both portable and desktop.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs (hunk 4 above)
Comment (TyOverby) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs]: Done.

**Comment by TyOverby** [comment]
New commit is up which added output verification and an extra case for accessing the member from outside of the struct.

Next up: VB tests.

**Comment by TyOverby** [comment]
@dotnet-bot retest prtest/win/dbg/eta please

reason: jenkins hit an IO error http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/6248/consoleFull#11416324786ee26338-6221-4f7c-8c8f-1d1d5cb4704a

**Comment by TyOverby** [comment]
@jaredpar @AlekseyTs: The VB fix is going to be much harder due to how the VB diagnostic is produced.

Because I'm on Mantis Role now, I'd like to merge this and fix the VB issue separately, tracking https://github.com/dotnet/roslyn/issues/10839

File: src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs [hunk 5]
```diff
@@ -1168,5 +1168,95 @@ public void NameofTypeParameterInParameterInitializer()
...
+class Other {
+    public static string GetFromExternal() {
+        Struct1 myStruct = default(Struct1);
+        return nameof(myStruct.MessageType);
+    }
+}
+";
+            var compilation = CreateCompilationWithMscorlib45(source, null,
+                new CSharpCompilationOptions(OutputKind.ConsoleApplication).WithAllowUnsafe(true)).VerifyDiagnostics();
+            CompileAndVerify(compilation, expectedOutput: "MessageType" + Environment.NewLine + "x" + Environment.NewLine + "MessageType");
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs]: We are usually using verbatim strings with line breaks inside.

**Comment by AlekseyTs** [comment]
LGTM

**Comment by jaredpar** [comment]
:+1:

File: src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs (hunk 3 above)
Comment (TyOverby) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs]: This is targeting master and CompilerTrait is in future.  I'll go back and annotate tests the next time that there's a Future -> Master merge.

**Comment by gafter** [comment]
@TyOverby Can/should I merge this?

**Comment by TyOverby** [comment]
I was waiting for the tests to finish.  Merging now.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs (hunk 3 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs]: Master is merged to the future on a daily basis. Rather than waiting for a merge from future to master, the test can be properly marked in the future, once it gets there.
