### PR TITLE
Propagate In/Out attributes on local functions

### LINKED ISSUE #57325: [In, Out] attributes removed from extern local function parameters
I notice that **[In, Out]** attributes are removed from a P/Invoke parameter when the method is declared as a local function. This causes problems when the changes need to be marshaled back to managed code. If I understand correctly from https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/local-functions, extern local static functions are supported. Moreover, beginning with C# 9, any attributes on local function parameters should also be preserved.

**Version Used**: 
```
Visual Studio: 16.11.5
C# Tools:      3.11.0-4.21403.6+ae1fff344d46976624e68ae17164e0607ab68b10
```

**Steps to Reproduce**:
1. Create a C or C++ DLL (_"SomeLibrary.dll"_) exporting a single method (_"SomeMethod"_).

  ```C++
typedef struct {
    bool enabled;
} State;

extern "C"
__declspec(dllexport) void SomeMethod(State* state_ptr)
{
    state_ptr->enabled = true;
}
  ```

2. Create a test project targetting .NET 5.

  ```C#
[TestClass]
public class SomeTests
{
    private const string TestLibraryName = "SomeLibrary";

    [StructLayout(LayoutKind.Sequential)]
    private class State
    {
        [MarshalAs(UnmanagedType.U1)]
        public bool Enabled;
    }

    [DllImport(TestLibraryName)]
    private static extern void SomeMethod([In, Out] State state);

    [TestMethod]
    public void TestOne()           // THIS TEST SUCCEEDS
    {
        State state = new();
        SomeMethod(state);
        Assert.IsTrue(state.Enabled);
    }

    [TestMethod]
    public void TestTwo()           // THIS TEST FAILS!!!
    {
        [DllImport(TestLibraryName)]
        static extern void SomeMethod([In, Out] State state);

        State state = new();
        SomeMethod(state);
        Assert.IsTrue(state.Enabled);
    }
}
  ```
3. Run the tests.

**Expected Behavior**:
Both tests should succeed.

**Actual Behavior**:
`TestTwo` method fails. Below is the generated code.  It seems that the compiler removes the **[In]** and **[Out]** attributes in the local function parameter of the `<TestTwo>g__SomeMethod|4_0` method, unlike the method declared at class scope with exactly the same signature where the attributes are preserved.
```C#
...
[DllImport("SomeLibrary")]
private static extern void SomeMethod([In][Out] State state);

public void TestOne()
{
    State state = new State();
    SomeMethod(state);
}

public void TestTwo()
{
    State state = new State();
    <TestTwo>g__SomeMethod|4_0(state);
}

[DllImport("SomeLibrary", EntryPoint = "SomeMethod")]
[CompilerGenerated]
internal static extern void <TestTwo>g__SomeMethod|4_0(State state);
...
```
Interestingly, other attributes seem to be preserved. For example, using a custom attribute:
```C#
public class XXXAttribute : Attribute
{
}
...
public void TestTwo() 
{
    [DllImport(TestLibraryName)]
    static extern void SomeMethod([In, Out, XXX] State state);
    ...
}
...
```
Generates the following code:
```C#
[DllImport("SomeLibrary", EntryPoint = "SomeMethod")]
[CompilerGenerated]
internal static extern void <TestTwo>g__SomeMethod|4_0([XXX] State state);
```

### PR DESCRIPTION
**Pull request by RikkiGibson**
Fixes #57325.

I found that we didn't override the appropriate methods to propagate these pseudo-custom attributes.

I reviewed *II.21.2.1 Pseudo custom attributes* in ECMA-335 for any attributes which could be applied to local functions or their parameters. I found that we had tests for every case except In/Out attributes.

### CODE REVIEW

**Review by 333fred — APPROVED** [review]

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs [hunk 1]
```diff
@@ -5968,6 +5968,309 @@ static void validate(ModuleSymbol module)
...
+    public bool B;
+}
+
+class Program
+{
+    static void M(in State state)
+    {
+        local(in state);
+
+        static void local(in State state)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs:6086]: Does `[In] in` present anything novel we should be testing?

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs [hunk 2]
```diff
@@ -5968,6 +5968,309 @@ static void validate(ModuleSymbol module)
...
+    public bool B;
+}
+
+class Program
+{
+    static void M(out State state)
+    {
+        local(out state);
+
+        static void local(out State state)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs:6191]: Does `[Out] out` or `[In] out` present anything novel we should be testing?

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs [hunk 3]
```diff
@@ -5968,6 +5968,309 @@ static void validate(ModuleSymbol module)
...
+                options: TestOptions.DebugDll.WithMetadataImportOptions(MetadataImportOptions.All));
+            var methodParam = ((CSharpCompilation)verifier.Compilation).GetMember<MethodSymbol>("Program.M").Parameters[0];
+            Assert.True(methodParam.IsMetadataIn);
+            Assert.True(methodParam.IsMetadataOut);
+
+            var localFunctionParam = verifier.FindLocalFunction("local").Parameters[0].GetSymbol<ParameterSymbol>();
+            Assert.True(localFunctionParam.IsMetadataIn);
+            Assert.True(localFunctionParam.IsMetadataOut);
+
+            verifier.VerifyTypeIL("Program", """
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs:6008]: >VerifyTypeIL [](http://example.com/codeflow?start=21&length=12)

What is the goal to use ```VerifyTypeIL```? Is asserting ```IsMetadataIn/IsMetadataOut``` insufficient? Otherwise, consider removing IL comparison.

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs [hunk 4]
```diff
@@ -315,6 +315,10 @@ public override ImmutableArray<CSharpAttributeData> GetAttributes()
 
         internal override bool IsMetadataOptional => _baseParameterForAttributes?.IsMetadataOptional == true;
 
+        internal override bool IsMetadataIn => base.IsMetadataIn || _baseParameterForAttributes?.IsMetadataIn == true;
+
+        internal override bool IsMetadataOut => base.IsMetadataOut || _baseParameterForAttributes?.IsMetadataOut == true;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs:320]: >base.IsMetadataOut || _baseParameterForAttributes?.IsMetadataOut == true [](http://example.com/codeflow?start=48&length=72)

Are we testing both branches here?

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs:320]: >base.IsMetadataOut [](http://example.com/codeflow?start=48&length=18)

It feels like declaration in base should be made abstract.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 1)

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs:320]: Adding a test which includes a custom attribute to ensure we test this branch (or its equivalent in the most recent revision).

**Comment by AlekseyTs** [comment]
Done with review pass (commit 2)

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs [hunk 5]
```diff
@@ -315,6 +315,10 @@ public override ImmutableArray<CSharpAttributeData> GetAttributes()
 
         internal override bool IsMetadataOptional => _baseParameterForAttributes?.IsMetadataOptional == true;
 
+        internal override bool IsMetadataIn => RefKind == RefKind.In || _baseParameterForAttributes?.GetDecodedWellKnownAttributeData()?.HasInAttribute == true;
+
+        internal override bool IsMetadataOut => RefKind == RefKind.Out || _baseParameterForAttributes?.GetDecodedWellKnownAttributeData()?.HasOutAttribute == true;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs:320]: >_baseParameterForAttributes?.GetDecodedWellKnownAttributeData()?.HasOutAttribute == true [](http://example.com/codeflow?start=74&length=88)

I'd expect this change to be backed by a test (suggested in the comment that motivated the change).

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 5)
