### PR TITLE
Ensure the operand of an is-pattern expression is evaluated.

### LINKED ISSUE #22619: "x is var _" results in the expression being true without x being evaluated
**Version Used**: 
C# 7.1, debug mode

**Steps to Reproduce**:
```cs
internal class Program
{
    private static void Main()
    {
        var test = new Program();
        var result = test.IsVarMethod();
        Console.WriteLine($"Result = {result}");
        Console.Read();
    }

    private int IsVarMethod() => ThrowingMethod() is var _ ? 1 : 0;
    private bool ThrowingMethod() => throw new Exception("Oh");
}
```

**Expected Behavior**:
I'd expect `ThrowingMethod()` to be invoked, resulting in an exception.

**Actual Behavior**:
The method, `IsVarMethod()`, returns `1` and no exception is thrown.

This only occurs if the `x is T y` expression uses the var pattern and a discard. Change `var` to `bool` or `_` to eg `y` and the method is invoked and the exception thrown.

### PR DESCRIPTION
**Pull request by gafter**
**Customer scenario**

Writing the expression `expr is var _` yields true without evaluating `expr` for its side-effects. It should evaluate `expr`.

**Bugs this fixes:**

Fixes #22619

**Workarounds, if any**

Change `_` to some otherwise unused identifier.

**Risk**

Very low. The fix is very focused on the particular scenario.

**Performance impact**

None. Does not change any algorithms of the compiler.

**Is this a regression from a previous update?**

No. This bug existed since pattern-matching was first introduced.

**Root cause analysis:**

The scenario is a little nonsensical, so we did not think to test it.

**How was the bug found?**

(Internal) customer reported.

**Test documentation updated?**

No.

-----------------
@dotnet/roslyn-compiler  Please review.

### CODE REVIEW

**Comment by gafter** [comment]
test windows_debug_vs-integration_prtest please

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 1]
```diff
@@ -6403,5 +6403,37 @@ static void Main()
...
+internal class Program
+{
+    private static void Main()
+    {
+        try
+        {
+            var test = new Program();
+            var result = test.IsVarMethod();
+            Console.WriteLine($""Result = {result}"");
+            Console.Read();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: >Console.Read(); [](start = 12, length = 15)

Consider removing this statement.

**Comment by gafter** [comment]
test windows_debug_unit32_prtest please
