### PR TITLE
Fixes overload resolution regression with ValueTuple

### LINKED ISSUE #20494: "More generic" tie-breaker not applied to ValueTuple in C# 7 compiler
**Version Used**: 15.2

**Steps to Reproduce**:

1. Compile the following code

**Expected Behavior**:

Code compiles without problem, just like it did using previous C# compilers.

**Actual Behavior**:

Compile fails at `M2(b)`, complaining that `error CS0121: The call is ambiguous between the following methods or properties: 'C.M2<T>((T, int))' and 'C.M2<T>(((T, int), int))'`

This is a regression from compilers previous to Visual Studio 2017.

``` c#
using System;
public class C
{
    public static void Main()
    {
        A<A<int>> a = null;
        M1(a); // ok, selects M1<T>(A<A<T>> a)

        var b = default(ValueTuple<ValueTuple<int, int>, int>);
        M2(b); // ok, should select M2<T>(ValueTuple<ValueTuple<T, int>, int> a)
    }
    public static void M1<T>(A<T> a) { }
    public static void M1<T>(A<A<T>> a) { }

    public static void M2<T>(ValueTuple<T, int> a) { }
    public static void M2<T>(ValueTuple<ValueTuple<T, int>, int> a) { }
}

public class A<T> { }
```

/cc @jaredpar @MadsTorgersen

### PR DESCRIPTION
**Pull request by gafter**
**Customer scenario**

The C# overload resolution tie-breaker involving a more specific type argument isn't respected for instances of ValueTuple. When such a scenario arises, the programmer get an ambiguity error on the invocation.

**Bugs this fixes:**

Fixes #20494
Adds a test for #20583

**Workarounds, if any**

The programmer can provide explicit type arguments to resolve the ambiguity.

**Risk**

Small. The fix is a very local workaround for the symptom. The underlying issue (ValueTuple instances are not recognized by the compiler as generic), may be addressed separately in a more extensive change.

**Performance impact**

Tiny or none.

**Is this a regression from a previous update?**

It is a regression in VS2017 versus VS2015.

**Root cause analysis:**

This is a symptom of our choice of internal representation for tuple types. I am separately looking at a more uniform change to address the underlying issue, which is that tuple types are not recognized by the compiler as generic.

**How was the bug found?**

Ad-hoc testing.

@dotnet/roslyn-compiler May I please have a couple of reviews of this tiny bug fix?

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs [hunk 1]
```diff
@@ -1782,8 +1782,8 @@ private static BetterResult MoreSpecificType(TypeSymbol t1, TypeSymbol t2, ref H
             //   argument is more specific and no type argument is less specific than the
             //   corresponding type argument in the other. 
 
-            var n1 = t1 as NamedTypeSymbol;
-            var n2 = t2 as NamedTypeSymbol;
+            var n1 = t1.TupleUnderlyingTypeOrSelf() as NamedTypeSymbol;
+            var n2 = t2.TupleUnderlyingTypeOrSelf() as NamedTypeSymbol;
```
Comment (VSadov) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs]: Do we need the same change for VB?

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs [hunk 2]
```diff
@@ -23412,5 +23412,58 @@ void M()
             Assert.Equal("(System.Int32, System.String, System.Int32)", model.GetTypeInfo(tuple).ConvertedType.ToTestDisplayString());
             Assert.Equal(ConversionKind.NoConversion, model.GetConversion(tuple).Kind);
         }
+
+        [Fact]
+        [WorkItem(20494, "https://github.com/dotnet/roslyn/issues/20494")]
+        public void MoreGenericTieBreaker_01()
```
Comment (VSadov) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: Can we have a "literal" form of these new tests as well? 
I am sure they will be have the same, - just for accidental regression purposes.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs [hunk 3]
```diff
@@ -23412,5 +23412,58 @@ void M()
...
+}
+
+public class A<T> {}";
+            var comp = CompileAndVerify(source, additionalRefs: s_valueTupleRefs, expectedOutput: "24");
+        }
+
+        [Fact(Skip = "https://github.com/dotnet/roslyn/issues/20583")]
+        [WorkItem(20494, "https://github.com/dotnet/roslyn/issues/20494")]
+        [WorkItem(20583, "https://github.com/dotnet/roslyn/issues/20583")]
+        public void MoreGenericTieBreaker_02()
```
Comment (VSadov) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: Can we also have a negative test when, for example, element type `#1` is more specific for one overload and element type `#20` is more specific for another. That should fail, but since we are not operating on the flat list of element types, we may accidentally give preference to the earlier or later types in the element type order.

Comment (gafter) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: It is more subtle than you would expect. If the first overload is more specific in the first and 10th parameter positions, but the second is more specific in the 11th parameter position, then the first overload is selected. I'll add that as a test too.

Comment (VSadov) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: There should not be any preference between position of tuple elements. How is N1 element is more important than N11? 
This behavior seems to be a bug leaking implementation details of tuple types.

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs]: Yes, we do.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs (hunk 3 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: No, it is intentional, and it is not a bug. Between the two overloads
``` c#
M<T, U, V>(((int, T), int, int, int, int, int, int, int, int, (int, U), V))
M<T, U, V>((T, int, int, int, int, int, int, int, int, U, (int, V)))
```
which could also be written
``` c#
M<T, U, V>(VT<VT<int, T>, int, int, int, int, int, int, VT<int, int, VT<int, U>, V>>)
M<T, U, V>(VT<T, int, int, int, int, int, int, VT<int, int, U, VT<int, V>>>)
```
when called on a value of type
``` c#
((int, int), int, int, int, int, int, int, int, int, (int, int), (int, int))
```
which could also be written
``` c#
VT<VT<int, int>, int, int, int, int, int, int, VT<int, int, VT<int, int>, VT<int, int>>
```
The former is more specific on the first type parameter of the argument, and they agree on type arguments 2-7, and in type argument position 8 we have a value of type
``` c#
VT<int, int, VT<int, int>, VT<int, int>
```
for which neither
``` c#
VT<int, int, VT<int, U>, V>
```
nor
``` c#
VT<int, int, U, VT<int, V>>
```
is more specific.

Since the former is more specific for type argument 1 of its first parameter, and the second is not more specific for any type argument of any parameter, the first overload is more specific.

Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: If I understood correctly, there is tension between the flat view of tuples and the nested view of ValueTuple. The trouble is that the nested view is what determines the behavior when compiling from C# 6. So it seems we have to adhere to that (although I prefer the flat view when possible) :-(

---
In reply to: [125343475](https://github.com/dotnet/roslyn/pull/20587#discussion_r125343475) [](ancestors = 125343475)

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs]: Done.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: Done.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs (hunk 3 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: The tests discussed in this thread have been added, for both C# and VB.

**Comment by gafter** [comment]
@VSadov Do these changes address your suggestions? Do you have any further suggestions?

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs (hunk 3 above)
Comment (VSadov) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: This looks not desirable. In all other places when N-ary nature of tuples is in conflict with the underlying implementation - the tuple semantica wins.
This behavior is an artefact of recursing via underlying type instead of recursing via TupleElementTypes. Initially it looked as if there was no difference. Now, since there is an observable difference the recursion should happen via TupleElementTypes.

Comment (VSadov) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: 100-element tuple is primarily a flat aggregate of 100 typed elements. The part where it is mapped to a 10+ times nested struct is an implementation detail and plays secondary part. The 'tuple' semantics takes precedence when there is a conflict. 
The primary goal of tuples is to provide tuple experience not the nested struct experience.

Comment (gafter) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: > In all other places when N-ary nature of tuples is in conflict with the underlying implementation - the tuple semantics wins.

@VSadov I can't think of any places where we changed the semantics from those already defined for C# 6 (for instances of `System.ValueTuple`). Though I sympathize with the desire to think of a 100-long tuple as being generic with arity 100, that would be an incompatibility with code compiled using the C# 6 compiler. The mapping to nested generics isn't merely an implementation detail, it is part of the language specification and it affects examples like these.

**Comment by gafter** [comment]
@VSadov 
> The recursion should happen via TupleElementTypes not via underlying type. In all other places where there is an observable difference we recurse via tuple elements.

We recurse over tuple elements for the new semantics that we added for tuples. I am not aware of any effort to change the behavior of overload resolution or type inference for tuples except as a side-effect of the addition of some new conversions.

In any case, doing as you suggest would be a breaking change. See `MoreGenericTieBreaker_03`, which compiles without error, even if converted to use the explicit `ValueTuple` syntax. With your suggestion, such code would no longer compile. As far as I know there is no specified or implemented change to type inference that was intended to make such code illegal.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs (hunk 3 above)
Comment (VSadov) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: We should bring this up to the LDM. I think in the past the guiding principle was that the tuple aspect takes precedent in conflicts like this.

Comment (gafter) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: > I think in the past the guiding principle was that the tuple aspect takes precedent in conflicts like this.

Can you give an example where there was a conflict resolved in this way (for code that was legal in C# 6)?
