### PR TITLE
Collection expressions: report specific conversion errors from overload resolution

### LINKED ISSUE #73297: Collection expression conversion failure should result in element-wise diagnostics
SharpLab is out of date so you'll have to paste into a console app or similar.

```cs
A[] arr = [
    new A(),
    new B() // CS0029: Cannot implicitly convert type 'B' to 'A' (squiggling only 'new B()')
];

M([
    new A(),
    new B()
]); // CS1503: Argument 1: cannot convert from 'collection expressions' to 'A[]' (squiggling the entire collection-expr)

void M(A[] arr) { }

class A { }
class B { }
```

**Expected behavior**: both cases report errors on the specific elements which are failing to convert.

**Actual behavior**: Argument to `M` gives an error on the entire collection-expr. One can imagine this being *unwieldy* for *large collection-exprs*. Only assignment to `A[] arr` reports element-wise errors in the sample.

It's possible that element-wise conversion errors are not always what we want. But, I am suggesting that we have consistency between conversion diagnostics for assignment and for argument conversions, as a baseline.

I think the reason for the current behavior with arguments has to do with the way overload resolution errors are reported. But it feels like even in overload cases, we should be able to report fine-grained diagnostics, when the candidate we choose for diagnostics doesn't have a conversion from collection-expr, and the parameter type is a collection type.

### PR DESCRIPTION
**Pull request by cston**
Fixes #73297

### CODE REVIEW

**Comment by cston** [comment]
@dotnet/roslyn-compiler, please review.

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs [hunk 1]
```diff
@@ -1231,6 +1231,10 @@ private static bool HadLambdaConversionError(BindingDiagnosticBag diagnostics, A
                 {
                     // a diagnostic has been reported by ReportDelegateOrFunctionPointerMethodGroupDiagnostics
                 }
+                else if (argument.Kind == BoundKind.UnconvertedCollectionExpression)
+                {
+                    binder.GenerateImplicitConversionErrorForCollectionExpression((BoundUnconvertedCollectionExpression)argument, parameterType, diagnostics);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs:1236]: Oh! That was easy. :)

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs [hunk 2]
```diff
@@ -26287,15 +26384,25 @@ public class XAttribute : System.Attribute
...
                 Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "ERROR").WithArguments("ERROR").WithLocation(8, 23)
                 );
         }
 
+        [Fact]
+        public void InAssignment_BadArrayType()
+        {
+            string source = """
+                ERROR[] values = [1];
+                values = [2];
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:26398]: That's interesting, and seems reasonable I guess, as an "avoid cascading" behavior? Is this similar to how `values = new[] { 2 }` would behave?

**Review by RikkiGibson — APPROVED** [review]

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs (hunk 2 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:26398]: Yes, the behavior is similalr for `values = new[] { 2 }` which doesn't report any error (since it is assumed we've already reported an error on the declaration of `ERROR[] values;`.

However, the error that is suppressed in `values = new[] { 2 }` is converting `int[]` to `ERROR[]`, where as with `values = [2]` the error that is suppressed is converting `int` to `ERROR`.

Also, the error reporting for assignment did not change in this PR - I added this test to show the similar diagnostics to the previous test `InAttribute_BadArrayType()` that was affected by this PR. In that test, a call to `[X(new[] { 2 })]` will result in a conversion error for the argument.

I'm on the fence about whether we should report an error at the for `[X([1])]` in that test.

Comment (cston) [reply src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:26398]: > However, the error that is suppressed in `values = new[] { 2 }` is converting `int[]` to `ERROR[]`, whereas with `values = [2]` the error that is suppressed is converting `int` to `ERROR`.

Another example is `values = default` which does not result in any additional error.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:26398]: that all sounds good, merge at will :)
