### PR TITLE
Fix missing constructor warnings for NotNull fields

### LINKED ISSUE #49903: Roslyn doesn't enforce initialization of [DisallowNull, NotNull] members
**Version Used**: 

```
Branch master (8 Dec 2020)
Latest commit 60d947d by AlekseyTs:
Ensure that each generic local function gets its own container to cache dynamic call-sites. (#49802)

Fixes #49599.
```

**Steps to Reproduce**:

Compile and run the following code
```
#nullable enable
using System.Diagnostics.CodeAnalysis;

public class C
{
    [DisallowNull, NotNull] public string? F;
    
    public static void Main() => new C().F.ToString();
}
```

**Expected Behavior**:
`warning CS8618: Non-nullable field 'F' must contain a non-null value when exiting constructor. Consider declaring the field as nullable.`

**Actual Behavior**:
No warnings. The program crashes at runtime with a `NullReferenceException`

**Notes**
I believe this is caused because Roslyn treats `[DisallowNull, NotNull]` members as not nullable yet it doesn't enforce their initialization. Looks like an oversight as it does handle `[AllowNull, MaybeNull]` and allow such members to be uninitialized i.e.

```
#nullable enable
using System.Diagnostics.CodeAnalysis;

public class C1
{
    // fine, [AllowNull, MaybeNull] make it possible to skip initialization
     public string F;
}

public class C2
{
    // no warnings ??? Apparently [DisallowNull, NotNull] are ignored
    [DisallowNull, NotNull] public string? F;
}
```

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #49903

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 1]
```diff
@@ -28928,6 +28928,159 @@ public void Init(T t)
...
+    }
+
+    public C3(int i)
+    {
+        this.F = i.ToString();
+    }
+}
+";
+            // Note that while lack of warnings on `C2(string?)` seems strange, it is expected
+            // 'C2.F' begins in a maybe-null state, but assigning maybe-null to it causes it to become not-null
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28987]: Please elaborate this sentence a bit. After I thought about it for a couple minutes I figured out what you meant, but the fact that it becomes non-null because it's a property and the getter and setter are not linked is not obvious.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 2]
```diff
@@ -28928,6 +28928,159 @@ public void Init(T t)
...
+        {
+            var source = @"
+#nullable enable
+using System.Diagnostics.CodeAnalysis;
+
+public class C1
+{
+    [DisallowNull, NotNull] public string? F { get; set; }
+
+    public C1() { } // 1
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28942]: Please add a test with a non-autoprop. For example, `[DisallowNull, NotNull] public string? F { get => ""; set {} }`.

**Comment by 333fred** [comment]
Done review pass (commit 1). I'm not certain that this is behavior we want: the status quo makes more sense to me.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28942]: Manually implemented properties are expected to never get initialization warnings.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 3]
```diff
@@ -626,15 +626,16 @@ void checkMemberStateOnConstructorExit(MethodSymbol constructor, Symbol member,
                 {
                     return;
                 }
-                if (!fieldType.NullableAnnotation.IsNotAnnotated())
+                var annotations = symbol.GetFlowAnalysisAnnotations();
+                if ((annotations & (FlowAnalysisAnnotations.AllowNull)) != 0)
```
Comment (TessenR) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:630]: Is there any particular reason for introducing inconsistency between `[AllowNull]` and `[DisallowNull]` there?

I.e. `[AllowNull] string field;` mean you can left the field uninitialized
Yet `[DisallowNull] string? field;` doesn't mean you have to initialize the field

I can see that you enforced this behavior in `public void DisallowNullField_Constructor`'s `C3.F`, but I can't see why it should behave this way.

Wouldn't C# benefit from consistent compiler behavior there?

I understand that `[NotNull/DisallowNull]` and `[MaybeNull/AllowNull]` attributes will likely be used together. However in some situation a person might omit the outward annotation attributes.

Consider a scenario where a type is only created and initialized to be serialized and used in another process. In this case you might not notice that it might be useful / logical to apply `[MaybeNull]` or `[NotNull] attributes especially if you aren't very familiar with `System.Diagnostic.CodeAnalysis` annotations.
You might create a type, write initialization for it, notice warnings for some optional fields, annotate them with `[AllowNull]`, see that it works, annotate required fields with `[DisallowNull]` to make this initialization safe to refactor later and finish there.
In this case you'll apply `[AllowNull]`, see that it works and you'll only notice that `[DisallowNull]` doesn't have a similar effect only when you end up with an unexpectedly uninitialized field some years later.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: This is a reasonable point. This is pre-existing behavior, which IIRC dotnet/runtime has depended on at least in the past, where they would put AllowNull on fields and expect to have the initialization warning suppressed.

However the only suspect usage of the attribute I see now in dotnet/runtime is [here](https://github.com/dotnet/runtime/blob/31062e4ec6b248b709095e13947400b49d507e53/src/libraries/System.Private.Xml/src/System/Xml/Xsl/Xslt/CompilerScopeManager.cs#L37).

I think it's worth examining this behavior to decide whether it's still something that people need, and whether we could adjust it as a "bug-fix" level change. But I won't make the change in this PR.

**Comment by RikkiGibson** [comment]
It feels like if we ever introduce warnings for "misuse" of nullability attributes, it would be good to include a warning on auto-properties whose inputs are less strict than the outputs due to nullability attributes.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 3 above)
Comment (TessenR) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: The behavior I had in mind here is enforcing initialization of fields marked with `[DisallowNull]`, not relaxing the rules around `[AllowNull]` members. This way the dotnet/runtime example you gave won't be broken and people won't have to think whether it's `[DisallowNull]` or `[NotNull]` to enforce initialization since both will work. Isn't it the reason why both `[AllowNull]` and `[MaybeNull]` were both supported originally?

**Comment by NN---** [comment]
Is there any option to declare a nullable variable and deny assigning null to it ?

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 4]
```diff
@@ -28928,6 +28928,244 @@ public void Init(T t)
...
+}
+
+public class C3
+{
+    [DisallowNull] public string? F { get; set; }
+
+    public C3() { }
+    public C3(string? F)
+    {
+        this.F = F; // 1
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28977]: Should this be `// 4`?

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 5]
```diff
@@ -28928,6 +28928,244 @@ public void Init(T t)
...
+    }
+
+    public C3(int i)
+    {
+        this.F = i.ToString();
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28982]: Why does this not warn given that `ToString` has a `string?` return type?

Given that `ToString` can return `string?` or `string~` given the reference assemblies we use I worry that it makes a poor method to use in testing. Developers reading the change will likely have the expectation that the return is `string?` but in our tests it can be either. Think we should use a method that has an non-contextual nullable return in our tests.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 6]
```diff
@@ -28928,6 +28928,244 @@ public void Init(T t)
...
+
+    public C1() { } // 1
+    public C1(string? F) // 2
+    {
+        this.F = F; // 3
+    }
+
+    public C1(int i)
+    {
+        this.F = i.ToString();
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28950]: Why does this not warn given `ToString` returns `string?`

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28950]: perhaps it is overridden on `int`?

Comment (jaredpar) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28950]: I'm not sure if it does or does not and that's another reason I think we should avoid `ToString` in our tests here. These tests should be concretely about the behavior of nullable flow. By using `ToString` from the framework we are introducing a bit of an ambiguity as to what we are actually testing. 

It also means when we upgrade to new reference assemblies it could potentially change the meaning of these tests. For most APIs that isn't really an issue because breaks, or changes at all, are rare. With nullability though they are actively annotating so expectation is there should be some change.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28950]: how about `GetType()`?

Comment (jaredpar) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28950]: Same. In general I'd avoid using any BCL method when we're trying to validate nullability. I think it makes the test harder to understand and less resilient to the type of change that we tend to make with reference assembly updates.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28950]: I feel like this is an argument to avoid using built-in members entirely in nullable tests and that is a fairly onerous ask.

Basically, yes, the risk exists that the annotation will change on the ref assemblies used by tests, and if it does change, then hundreds of tests in here are going to break. I'm a little resistant to the idea that we need to account for it here because it is going to need to be accounted for en masse.

A more reasonable ask would be perhaps to verify what are the annotations on ref assemblies that *are* used in our nullable tests in practice, and ensure that the annotations on ref assemblies for tests do not change accidentally, as well as gain a sense of how we *would* change them, if we wanted to adopt the .NET 5 nullability annotations for certain tests, for example.

Comment (jaredpar) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28950]: > I feel like this is an argument to avoid using built-in members entirely in nullable tests and that is a fairly onerous ask.

The majority of tests in this class use the `CreateNullableCompilation` helper to run analysis. That uses either the `netstandard2.0` or the `net451` reference assemblies hence all of the built-in members are oblivious. If the intent is to test oblivious then that works. My suspicion is though that in most cases the intent is not to test oblivious. Perhaps I'm wrong here though. 

> A more reasonable ask would be perhaps to verify what are the annotations on ref assemblies that are used in our nullable tests in practice

The answer to this depends on the test. If the test uses the `netstandard2.0` reference assemblies then there is one answer, if it uses `netcoreapp3.1` then there is a different answer. Basically it is subject to some degree of change. Generally that the API will get stronger though which is a "safe" change from this perspective. 

Consider this specific case though: the test here is using the `netstandard2.0` reference assemblies which means this is validating that `string~` can assign here. Was that the intent? Reading the test I thought the intent was to check what happened when either `string?` or `string!` was the source of the assignment. Am I just reading the intent of this test wrong (or reading the setup code wrong)?

> I'm a little resistant to the idea that we need to account for it here because it is going to need to be accounted for en masse.

I'm not suggesting we go back and rewrite all the tests. At the same time seems like something we could avoid going forward with new ones. 

> A more reasonable ask would be perhaps to verify what are the annotations on ref assemblies that are used in our nullable tests in practice, and ensure that the annotations on ref assemblies for tests do not change accidentally

The model we try to operate on is that we keep pushing the `.NET Core App` reference assemblies forward. Observe that while we have `netcoreapp3.1` assemblies we don't have `netcoreapp3.0` or `netcoreapp2.1`. That's because we're always effectively on latest. The API sets which are stable are `netstandard2.0`, `net451`, etc ...

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28950]: Looking a little more closely, the usages of ToString() in practice are usually either to:

1. demonstrate that "possible null reference receiver" warnings are given where appropriate
2. get a non-null string in order to update a variable's flow state to not-null.

I think there is no risk from continuing to do (1)--annotations on the member won't affect whether such warnings are given.

In these tests it's perhaps more straightforward to achieve (2) by assigning literal strings. So I think I will resolve this thread by changing the new tests to assign literal strings instead.

In practice, there is not going to be a difference between assigning an "oblivious" return value versus a "not annotated" return value--since both will just turn into the "not null" flow state. However, you've raised a good point that the annotations on ToString() in .NET Core make it harder to understand tests here which assign the return of ToString() to something, because the reader is not certain whether such annotations are present in the test or not. So we can try to refrain from doing that in the future.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Thanks, I think I understand the suggestion fully now. However, my view is that the warnings should just work by requiring the constructor to make it so the flow state of fields is compatible with the "output state" of the field. I think if we discover that we *can't* close the hole of "AllowNull removes initialization warnings", I'm open to the concept of "DisallowNull *introduces* initialization warnings", but my first preference is definitely to make things consistent by removing the "AllowNull" hole.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Also, because we have a specific code path here to check "are we skipping the diagnostic because of presence of AllowNull?" it should be pretty easy, if we decide it's necessary, to introduce a special diagnostic in this scenario to use in warning wave 6.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28977]: Yes, thanks

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 5 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28982]: Changing to use a literal string to improve clarity.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28987]: Have updated the comment, please let me know if you think it's sufficiently clear.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 7]
```diff
@@ -28928,6 +28928,244 @@ public void Init(T t)
...
+        Prop.ToString(); // 3
+    }
+
+    public void M1(T t) { }
+}
+";
+            var comp = CreateNullableCompilation(new[] { source, NotNullAttributeDefinition });
+            // It's not clear whether diagnostic 2 or 3 are appropriate.
+            // Going by the principle of "if you put a good value in, you will get a good value out",
+            // it seems like property state should be NotNull after assigning a MaybeNull to the property.
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:29156]: My mental model is that this sample is not meaningfully different than the following which does not warn:

```c#
#nullable enable

public class C {
    [return:NotNull]T M<T>(T t) => t;
}
```

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:29156]: This appears to warn on [SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+BiAdgVwBtCJhC4ACOXU8gWAChGABABguYEYA6AEQEsIAc1wB7WPwDGUbgGFRKOAEEahAJ5R+UANyMWAZg4AmCrIoBvRhWsUA2swDsIAHKiYzooQC6AFQoBZAB4fAD4ACj8YAEoKAF4QihhdBgBfIA==)

Comment (jaredpar) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:29156]: I copied that from SharpLab where it was not warning ... I must have been stuck on an old branch. Is it Friday yet? 

Still though I do believe my comment about this conceptually being the same problem here. Hence I would expect them to both or neither warn.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:29156]: Looking closer: this test reveals an issue that this PR is not intended to solve.

We have a pattern in nullable for properties where setters are allowed to accept a "wider" type than the getter will return, on the assumption that the setter will "sanitize" the input and ensure that the getter always returns a value of the correct type.

[SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+BYAUAYgDsBXAG1ImFLgAI5DLq8ABABhuYEYA6AEQEsIAc0IB7WPwDGUbgGFRKOAEEGpAJ5R+UANx48ANwgIaAdxoBeGoThmA6vxRC4MABQBKXbhPcAKnAAeMBZWZKSe3n6BvqIAyjAI/IRC7to0APRpVqKmRoSJQnT+AA5wkvAoerjMAMwcAEw09o7OeADeeDSdHJysAPw0APrwgZ5dNADaSuSiJgByoQC6HV013eyRMMud7bhjY05B5gB8g8NBvf0ARJeje51QzhYnQwGHNIakxHC3nQC+eL8gA===)
```cs
#nullable enable
using System.Diagnostics.CodeAnalysis;

var w = new Widget();
w.Text = null;
w.Text.ToString(); // no warning expected

public class Widget
{
    string? _text;
    [AllowNull]
    public string Text
    {
        get => _text ?? "";
        set => _text = value;
    }
}
```

These tests raise, but do not answer, the question of whether this behavior should be extended from just the "maybe null/not null" difference to the "maybe default/maybe null" or "maybe null/`[NotNull] T`" scenarios.

The WorkItem attribute on these tests indicates this, however for clarity I'm happy to add a link to the follow-up issue inline.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 3 above)
Comment (Joe4evr) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: > The behavior I had in mind here is enforcing initialization of fields marked with `[DisallowNull]`

The problem there is that can break cases where initialization cannot be done through the constructor, which is the only place that the compiler checks for it.

Comment (TessenR) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: @RikkiGibson FYI I've created an issue to track this since I want to get a notification when it's fixed and whether you'll change `[AllowNull]` to match `[DisallowNull]` or vice versa https://github.com/dotnet/roslyn/issues/50085

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler Please review :smile:

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 1 above)
Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28987]: I actually think it's less clear now, sorry. It's simply that the getter and setter are not linked: regardless of what we assign in the setter, the getter will return `NotNull` because that's how the property is annotated.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 8]
```diff
@@ -28928,6 +28928,246 @@ public void Init(T t)
...
+        [Fact, WorkItem(48996, "https://github.com/dotnet/roslyn/issues/48996")]
+        public void DisallowNullProperty_Constructor()
+        {
+            var source = @"
+#nullable enable
+using System.Diagnostics.CodeAnalysis;
+
+public class C1
+{
+    [DisallowNull, NotNull] public string? F { get; set; }
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28940]: Consider using F1, F2, F3 for these properties to make them differentiable.

**Comment by 333fred** [comment]
Done review pass (commit 5)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28987]: > It's simply that the getter and setter are not linked

I'm not sure I understand what linked means here. Are a property's accessors "linked" when the flow state of the property after assignment is the same as the flow state of the 'value' argument to the property setter?

I guess when I hear "not linked" I imagine a property setter which never changes the flow state from the getter. However, that is not the case here.

The language I used in this comment is how we summarized this behavior when it was designed. However, I can see that not all the context is given for it here, so I'm open to revising it again.

Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28987]: It's not linked in that the type of the thing put into the setter is not reflected in (ie, not linked to) the flow state of the getter.

**Review by 333fred — APPROVED** [review]

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler Please review

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler Please review

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 9]
```diff
@@ -28928,6 +28928,274 @@ public void Init(T t)
...
+    {
+        this.F = ""a"";
+    }
+}
+
+public class C2
+{
+    [NotNull] public string? F;
+
+    public C2() { } // 1
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:29030]: >// 1 [](start = 20, length = 4)

`// 4`, ...

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 10]
```diff
@@ -28928,6 +28928,274 @@ public void Init(T t)
...
+            // It's not clear whether diagnostic 2 or 3 are appropriate.
+            // Going by the principle of "if you put a good value in, you will get a good value out",
+            // it seems like property state should be NotNull after assigning a MaybeNull to the property.
+            // https://github.com/dotnet/roslyn/issues/49964
+            comp.VerifyDiagnostics(
+                // (8,12): warning CS8618: Non-nullable property 'Prop' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
+                //     public C() // 1
+                Diagnostic(ErrorCode.WRN_UninitializedNonNullableField, "C").WithArguments("property", "Prop").WithLocation(8, 12),
+                // (12,12): warning CS8618: Non-nullable property 'Prop' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
+                //     public C(T t) // 2
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:29163]: >public C(T t) // 2 [](start = 23, length = 18)

Is this a new warning? If so, we should consider investigating #49964 first, to make sure it is appropriate.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 11]
```diff
@@ -822,6 +831,8 @@ bool needsDefaultInitialStateForMembers()
                         return false;
                     }
 
+                    // we don't use a default initial state for value type instance constructors without `: this()` because
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:834]: >we [](start = 23, length = 2)

Minor: uppercase "W".

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 10 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:29163]: No, the same warnings are given before this change. [SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+BiAdgVwBtCJhC4ACOXU8gWACgABABgqYEYA6AEQEsIAc1wB7WHwDGULgGERKOAEEahAJ5Q+UANyNGTAMzsATBRkAeACoA+CgG9GFRxQDaAORExXRQgF0HTiwoABQQRAAc7CkE4GC0KKBi4gF9dBid2QxkACgBKCgB6fIoOf0d7NKcUhlKM0yzAmDzCiiMa8vT0kPCKAF4KWJqqmoN2ABYKAFl6/rz2jscuiL6BivnFrgsRAGUYBD5cQVy45v1B1PSRpnGJjmnGyKqkoA===)

**Review by cston — APPROVED** [review]

**Comment by dferretti** [comment]
We used to use a pattern similar to this in a lot of our tests:
```c#
[TestClass]
public class MyTest
{
    [NotNull] // using NotNull because from the caller's POV this will never be null
    public static string? TestDbConnStr { get; private set; }

    [AssemblyInitialize]
    public static void AssemblyInitialize(TestContext context)
        => TestDbConnStr = context.Properties["connStr"] ?? throw ...;
}
```

We have a value that we know will be populated by the test fixture (but not any constructor), so we mark it as NotNull to indicate that there will always be a value there. Is this an incorrect usage of NotNull? Is `string TestDbConnStr { get; private set; } = null!` the only way to go now?
Our build server uses the dotnet/sdk:5.0 docker image and we have `TreatWarningsAsErrors` enabled so our projects recently started not building unexpectedly.
