### PR TITLE
Resolve a number of issues in typeswitch

### LINKED ISSUE #9422: PreciseAbstractFlowPass doesn't override visit for BoundMatchCase and BoundConstantPattern nodes
If the visit methods can be called, they should be overridden and should visit constituent BoundExpressions as appropriate (either as a condition or as an RValue). Failing to properly visit constituent BoundExpressions can result in a NullReferenceExpression because we might run into conditional state when we don't expect to be in a conditional state.

If we don't expect the visit methods to be ever called, I suggest to still override them in this fashion:
```
        public sealed override BoundNode VisitMatchCase(BoundMatchCase node)
        {
            // Should be handled by VisitMatchExpression
            throw ExceptionUtilities.Unreachable;
        }

        public sealed override BoundNode VisitConstantPattern(BoundConstantPattern node)
        {
            // Should be handled by VisitPattern.
            // There is no reason to visit BoundConstantPattern.Value at the moment because it 
            // is supposed to be a constant.
            throw ExceptionUtilities.Unreachable;
        }
```

### PR DESCRIPTION
**Pull request by gafter**
- Reflect the most recent LDM decisions regarding reachability and subsumption
- Implement LDM-specified handling for constant switch expression in flow analysis and `default:`
- A type pattern cannot test a static type
- Augment `TestResource.AllInOneCSharpCode` to handle all supported pattern forms. 
- Pattern variables are mutable per latest LDM.
- Additional tests and some changes per review comments
Fixes #9422, #10487, #10932, #9277, #11379, #10633

(I believe there is a merge issue affecting some interactive window unit tests. I will resolve it before merging)

@AlekseyTs @agocke Please review
@dotnet/roslyn-compiler Any additional review will be appreciated

### CODE REVIEW

**Comment by khyperia** [comment]
> (I believe there is a merge issue affecting some interactive window unit tests. I will resolve it before merging)

I'm hitting those too - something to do with RTF color generation being different when copying out of the interactive window? (that was the issue I was hitting) - I believe those failures started when I upgraded to VS2015U3, and I traced the test to eventually call into a VS API to actually generate the RTF (if I understood the test correctly, I'm not entirely sure). My guess is that U3 changed that functionality.

I think many of us run tests through Jenkins (although I usually run locally) which I'm not sure which version of VS it's using, but I'm guessing it's not update 3 (which has the changes) - so everyone else's tests are passing when ran through Jenkins.

**Comment by jaredpar** [comment]
@jasonmalinowski i believe the RTF problem is specific to update 3.

**Comment by gafter** [comment]
@cston @agocke Please review these typeswitch changes.

File: src/Compilers/CSharp/Portable/Binder/SwitchBinder_BindPatternSwitch.cs [hunk 1]
```diff
@@ -166,21 +166,25 @@ private SourceLabelSymbol FindMatchingSwitchLabel(object key)
             return map;
         }
 
-        private ImmutableArray<BoundPatternSwitchSection> BindPatternSwitchSections(BoundExpression boundSwitchExpression, SyntaxList<SwitchSectionSyntax> sections, Binder originalBinder, ref DefaultSwitchLabelSyntax defaultLabel, DiagnosticBag diagnostics)
+        private ImmutableArray<BoundPatternSwitchSection> BindPatternSwitchSections(BoundExpression boundSwitchExpression, SyntaxList<SwitchSectionSyntax> sections, Binder originalBinder, ref BoundPatternSwitchLabel defaultLabel, DiagnosticBag diagnostics)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/SwitchBinder_BindPatternSwitch.cs]: It feels like `defaultLabel` should be an `out` parameter rather than `ref`.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs [hunk 2]
```diff
@@ -933,14 +921,22 @@ internal static class PatternConversionExtensions
...
         public abstract DecisionKind Kind { get; }
 
+#if DEBUG
+        internal string Dump()
+        {
+            var builder = new StringBuilder();
+            DumpInternal(builder, 0);
+            return builder.ToString();
+        }
+        internal abstract void DumpInternal(StringBuilder builder, int indent);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs]: Would it be simpler to pass in the indent string and have recursive calls use `indent.PadLeft(2)`?

File: src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass_Switch.cs [hunk 3]
```diff
@@ -182,11 +188,17 @@ private void VisitDecisionTree(DecisionTree decisionTree)
                 case DecisionTree.DecisionKind.ByValue:
                     {
                         var byValue = (DecisionTree.ByValue)decisionTree;
+                        var expressionIsConstant = byValue.Expression.ConstantValue != null;
+                        bool valueHandled = false;
                         foreach (var kvp in byValue.ValueAndDecision)
                         {
-                            VisitDecisionTree(kvp.Value);
+                            if (!expressionIsConstant || Equals(byValue.Expression.ConstantValue.Value, kvp.Key))
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass_Switch.cs]: Consider extracting a local for `byValue.Expression.ConstantValue`. And then this condition might be easier to read as: `if (constValue == null || Equals(constValue.Value, kvp.Key))`.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternSubsumptionTests.cs [hunk 4]
```diff
@@ -152,19 +149,19 @@ public static void Main()
...
             Assert.True(compilation.GetDiagnostics().HasAnyErrors());
             compilation.VerifyDiagnostics(
                 // (10,18): error CS0029: Cannot implicitly convert type 'string' to 'bool'
-                //             case "foo": // error: subsumed by previous case
+                //             case "foo": // wrong type
                 Diagnostic(ErrorCode.ERR_NoImplicitConv, @"""foo""").WithArguments("string", "bool").WithLocation(10, 18),
                 // (11,17): warning CS0162: Unreachable code detected
-                //                 break;
+                //                 break; // unreachable
                 Diagnostic(ErrorCode.WRN_UnreachableCode, "break").WithLocation(11, 17)
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternSubsumptionTests.cs]: Are we reporting unreachable because the `case` expression was invalid or because all possible cases were handled earlier? We don't seem to report unreachable for non-pattern switch: `switch (true) { case false: case true: break; case "false": break; }`.

File: src/Compilers/CSharp/Portable/Binder/SwitchBinder_BindPatternSwitch.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/SwitchBinder_BindPatternSwitch.cs]: I did this to be consistent with the way it is handled in `BindPatternSwitchSection`, but an `out` parameter (initialized to null here rather than in the caller) would work too. I'll change it.

---
In reply to: [69157587](https://github.com/dotnet/roslyn/pull/12250#discussion_r69157587) [](ancestors = 69157587)

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs]: Yes, that would be much simpler. I'll do that.

---
In reply to: [69160615](https://github.com/dotnet/roslyn/pull/12250#discussion_r69160615) [](ancestors = 69160615)

File: src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass_Switch.cs (hunk 3 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass_Switch.cs]: OK, sure.

---
In reply to: [69162180](https://github.com/dotnet/roslyn/pull/12250#discussion_r69162180) [](ancestors = 69162180)

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternSubsumptionTests.cs (hunk 4 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternSubsumptionTests.cs]: I'm not sure which it is, but in either case this is a cascaded diagnostic. It would probably be worth suppressing it, but it may be a bit awkward and it isn't my highest priority. I'll create an issue for this.

---
In reply to: [69164613](https://github.com/dotnet/roslyn/pull/12250#discussion_r69164613) [](ancestors = 69164613)

**Comment by cston** [comment]
LGTM

**Comment by gafter** [comment]
@agocke is added to the review. #Closed

**Comment by gafter** [comment]
@cston I've addressed your review comments and fixed one more bug in a newly pushed delta.

@agocke Please review these typeswitch changes.

**Comment by gafter** [comment]
@agocke Could you review this please?

**Comment by agocke** [comment]
@gafter Reviewing now.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs [hunk 5]
```diff
@@ -593,7 +589,8 @@ private DecisionTree AddByValue(DecisionTree.ByType byType, BoundExpression valu
             }
             if (value.ConstantValue == ConstantValue.Null)
             {
-                return AddByNull((DecisionTree)byType, makeDecision);
+                return byType.Expression.ConstantValue?.IsNull == false
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs]: Could you give an example of an expression where this expression is true?

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs [hunk 6]
```diff
@@ -933,14 +921,22 @@ internal static class PatternConversionExtensions
...
     {
-        public DecisionTree Parent;
         public readonly BoundExpression Expression;
         public readonly TypeSymbol Type;
         public bool MatchIsComplete;
 
         public enum DecisionKind { ByType, ByValue, Guarded }
         public abstract DecisionKind Kind { get; }
 
+#if DEBUG
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs]: Have you thought about using ConditionalAttribute("DEBUG") instead?

Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs]: That is not allowed on methods whose return type is not `void`.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs (hunk 5 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs]: The expression `3` or `"foo"`.

**Comment by gafter** [comment]
@agocke Any further comments on this PR?

**Comment by agocke** [comment]
@gafter Nope, LGTM
