### PR TITLE
Fix formatting of attributes at end of file

### LINKED ISSUE #59637: IDE0055 (Fix formatting) errors after upgrading to SDK 6.0.200 (VS 17.1.0)
### Analyzer

**Diagnostic ID**: [IDE0055](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/formatting-rules): `Fix formatting`

### Analyzer source

**SDK**: [SDK 6.0.200](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 6.0.200](https://dotnet.microsoft.com/download/dotnet/6.0)

### Describe the bug
After upgrading VS to the VS 17.1.0 version, when I build my solution I get an IDE0055 error on GlobalSuppression.cs files, the content of the files is something like this

```
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "My reason", Scope = "member", Target = "~M:Method")]
```

If I click on Fix formatting an space is added after "]", but then i got a "SA1028" error
If I add a new line after "]"  the error that appeas is "SA1518".

### Actual behavior
An error is generated with files that end with assembly level attributes.

### Expected behavior
No error

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #59637

### CODE REVIEW

**Review by JoeRobich — APPROVED** [review]

File: src/EditorFeatures/CSharpTest/Formatting/FormattingEngineTests.cs [hunk 1]
```diff
@@ -1633,6 +1634,23 @@ protected void Render()
...
+            var code = $@"using System.Diagnostics.CodeAnalysis;
+
+[assembly:SuppressMessage(""Globalization"", ""CA1308: Normalize strings to uppercase"", Justification = ""My reason"", Scope = ""member"", Target = ""~M:Method"") ] {endOfFile}";
+            var expected = $@"using System.Diagnostics.CodeAnalysis;
+
+[assembly: SuppressMessage(""Globalization"", ""CA1308: Normalize strings to uppercase"", Justification = ""My reason"", Scope = ""member"", Target = ""~M:Method"")]{endOfFile}";
+
+            await AssertFormatAsync(expected, code, spans: null);
+            await AssertFormatAsync(expected, expected, spans: null);
+        }
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Formatting/FormattingEngineTests.cs:1652]: do we need a test that "file must have final newline" is respected?

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/EditorFeatures/CSharpTest/Formatting/FormattingEngineTests.cs (hunk 1 above)
Comment (sharwell) [reply src/EditorFeatures/CSharpTest/Formatting/FormattingEngineTests.cs:1652]: > file must have final newline

This is not respected. dotnet-format and the editor implement support for this option separately from our formatter.
