### PR TITLE
Handly dynamic null checks against literal null

### LINKED ISSUE #30939: Unexpected WRN_ConvertingNullableToNonNullable/WRN_NullReferenceReceiver after explicit null check for "dynamic?" value.
```
        [Fact]
        public void Test()
        {
            var source = @"
class Outer
{
    void M1(dynamic? x1)
    {
        if (x1 == null) return;
        Outer y = x1;
        x1.ToString();
    }
}
";

            CreateCompilation(source, options: WithNonNullTypesTrue()).VerifyDiagnostics(
                // (7,19): warning CS8600: Converting null literal or possible null value to non-nullable type.
                //         Outer y = x1;
                Diagnostic(ErrorCode.WRN_ConvertingNullableToNonNullable, "x1").WithLocation(7, 19),
                // (8,9): warning CS8602: Possible dereference of a null reference.
                //         x1.ToString();
                Diagnostic(ErrorCode.WRN_NullReferenceReceiver, "x1").WithLocation(8, 9)
                );
        }
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #30939

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a couple of reviews of this nullable fix?

**Comment by AlekseyTs** [comment]
Is there a typo in the title?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 1]
```diff
@@ -5149,7 +5149,27 @@ public override BoundNode VisitUnaryOperator(BoundUnaryOperator node)
...
+                    break;
+                case UnaryOperatorKind.DynamicTrue:
+                    // We cannot use VisitCondition, because the operand is not of type bool.
+                    // Yet we want to keep the result split if it was split.  So we simply visit.
+                    Visit(node.Operand);
+                    break;
+                case UnaryOperatorKind.DynamicFalse:
+                    Visit(node.Operand);
+                    Split();
+                    SetConditionalState(StateWhenFalse, StateWhenTrue);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >SetConditionalState(StateWhenFalse, StateWhenTrue); [](start = 20, length = 51)

Instead of always splitting the state, can we do this conditionally, only when we are in a conditional state (```IsConditionalState```)?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 2]
```diff
@@ -5149,7 +5149,27 @@ public override BoundNode VisitUnaryOperator(BoundUnaryOperator node)
         {
             Debug.Assert(!IsConditionalState);
 
-            _ = base.VisitUnaryOperator(node);
+            switch (node.OperatorKind)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >switch (node.OperatorKind) [](start = 12, length = 26)

Should we move this more accurate analysis into the base class?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 3]
```diff
@@ -5149,7 +5149,27 @@ public override BoundNode VisitUnaryOperator(BoundUnaryOperator node)
...
+                case UnaryOperatorKind.BoolLogicalNegation:
+                    VisitCondition(node.Operand);
+                    SetConditionalState(StateWhenFalse, StateWhenTrue);
+                    break;
+                case UnaryOperatorKind.DynamicTrue:
+                    // We cannot use VisitCondition, because the operand is not of type bool.
+                    // Yet we want to keep the result split if it was split.  So we simply visit.
+                    Visit(node.Operand);
+                    break;
+                case UnaryOperatorKind.DynamicFalse:
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >UnaryOperatorKind.DynamicFalse [](start = 21, length = 30)

It feels like this case isn't covered by added tests.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1)

**Comment by gafter** [comment]
I am not going to fix the title because that would mess up threading of the conversation in the email notifications in outlook.

---
In reply to: [484211934](https://github.com/dotnet/roslyn/pull/34996#issuecomment-484211934) [](ancestors = 484211934)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 2 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: The base class has the invariant that conditional states are only for `bool` values.  That is relaxed here.

---
In reply to: [276386205](https://github.com/dotnet/roslyn/pull/34996#discussion_r276386205) [](ancestors = 276386205)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: As a rule we have avoided such micro-optimizations that complicate the code for little expected benefit.  The caller is likely to split the state in any case.

---
In reply to: [276385502](https://github.com/dotnet/roslyn/pull/34996#discussion_r276385502) [](ancestors = 276385502)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 3 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Agreed; it would not be particularly useful to do so, since it is only used for the implementation of a user-defined meaning for `||`, for which no reasonable inference can be produced by the caller.  Removing this case.

---
In reply to: [276389190](https://github.com/dotnet/roslyn/pull/34996#discussion_r276389190) [](ancestors = 276389190)

**Comment by gafter** [comment]
@AlekseyTs I think I have addressed your comments.  Do you have any others?

@dotnet/roslyn-compiler May I please have a second review for this small change?

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 4]
```diff
@@ -72989,28 +72989,249 @@ public void NullabilityOfTypeParameters_023()
             var source = @"
 class Outer
 {
-    void M<T>(dynamic? x)
+    void M1<T>(dynamic? x)
     {
         if (x == null) return;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >x == null [](start = 12, length = 9)

Consider adding tests for ```!(x != null)```

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 5]
```diff
@@ -72989,28 +72989,249 @@ public void NullabilityOfTypeParameters_023()
...
         T y;
         y = x;
         y = (T)x;
         y.ToString();
     }
+    void M2<T>(dynamic? x)
+    {
+        if (x != null) return;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >x != null [](start = 12, length = 9)

Consider adding tests for ```!(x == null)```

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 4 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Sure, but since we don't know the behavior, we don't infer anything.

---
In reply to: [278750198](https://github.com/dotnet/roslyn/pull/34996#discussion_r278750198) [](ancestors = 278750198)

**Comment by gafter** [comment]
@AlekseyTs You may want to have another look.  I added support for dynamic `!`.

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a second review?
