### PR TITLE
Generate inaccessible getters and setters

### LINKED ISSUE #2407: "Implement Abstract Class" Shouldn't be Offered as Refactoring for Classes with Internal Abstract Members
If I write this (VS2015 CTP6):

````
using System.Globalization;

public class x : EastAsianLunisolarCalendar
````

I get the "Implement Abstract Class" option, but since EastAsianLunisolarCalendar has internal members, the code that's generated is messed up:

````
using System;
using System.Globalization;

public class x : EastAsianLunisolarCalendar
{
	public override int[] Eras
	{
		get
		{
			throw new NotImplementedException();
		}
	}

	internal override EraInfo[] CalEraInfo internal override int MaxCalendarYear internal override DateTime MaxDate internal override int MinCalendarYear internal override DateTime MinDate public override int GetEra(DateTime time)
	{
		throw new NotImplementedException();
	}

	internal override int GetGregorianYear(int year, int era)
	{
		throw new NotImplementedException();
	}

	internal override int GetYear(int year, DateTime time)
	{
		throw new NotImplementedException();
	}

	internal override int GetYearInfo(int LunarYear, int Index)
	{
		throw new NotImplementedException();
	}
}
````

I shouldn't get that refactoring option if I really can't implement the members.

### PR DESCRIPTION
**Pull request by jmarolf**
The code generator no longer checks for accessibility when deciding if it
should generate a getter or a setter.  There are many cases where we
generate code that is inaccessible in the hope that the user can fix the
accessibility problem later.

Fixes #2407

### CODE REVIEW

**Comment by jmarolf** [comment]
@Pilchie @balajikris @dpoeschl @rchande @brettfo @DustinCampbell @basoundr @CyrusNajmabadi - please review

File: src/EditorFeatures/VisualBasicTest/Diagnostics/ImplementAbstractClass/ImplementAbstractClassTests.vb [hunk 1]
```diff
@@ -197,5 +197,13 @@ End Class
...
+        End Sub
```
Comment (balajikris) [inline src/EditorFeatures/VisualBasicTest/Diagnostics/ImplementAbstractClass/ImplementAbstractClassTests.vb]: can you use xml literals for this test? Its hard to understand what this is doing.

File: src/Features/Core/Portable/ImplementAbstractClass/AbstractImplementAbstractClassService.Editor.cs [hunk 2]
```diff
@@ -153,13 +153,7 @@ private partial class Editor
                     setMethod: setMethod);
             }
 
-            private bool ShouldGenerateAccessor(IMethodSymbol method)
-            {
-                return
-                    method != null &&
-                    method.IsAccessibleWithin(_state.ClassType) &&
-                    _state.ClassType.FindImplementationForAbstractMember(method) == null;
```
Comment (Pilchie) [inline src/Features/Core/Portable/ImplementAbstractClass/AbstractImplementAbstractClassService.Editor.cs]: Don't you want to keep this condition?  You don't want to re-implemenent already implemented members.  (Also, why didn't this fail a test?)

File: src/EditorFeatures/VisualBasicTest/Diagnostics/ImplementAbstractClass/ImplementAbstractClassTests.vb (hunk 1 above)
Comment (jmarolf) [inline src/EditorFeatures/VisualBasicTest/Diagnostics/ImplementAbstractClass/ImplementAbstractClassTests.vb]: I could... every other test in this file doesn't do this.  Do we want to say that all VB tests should use xml literals?

File: src/Features/Core/Portable/ImplementAbstractClass/AbstractImplementAbstractClassService.Editor.cs (hunk 2 above)
Comment (jmarolf) [inline src/Features/Core/Portable/ImplementAbstractClass/AbstractImplementAbstractClassService.Editor.cs]: Once we've created the state object, we've already identified which members need to be implemented, see [here](https://github.com/dotnet/roslyn/blob/7755b1632509f7fc9c6f494c99711dae8d700499/src/Features/Core/Portable/ImplementAbstractClass/AbstractImplementAbstractClassService.State.cs#L55)

Unless I am missing something, there should be no case where we want to generate a property, but the properties accessor are already implemented.

What the code used to say was:

"Don't generate an accessor if it is not required by the interface/class, is inaccessible, or it already exists somehow, **But Still Generate The Propery Anyway**"

Now we say:
"Since we've already decided to generate this property by getting to this location in the code, generate an accessor unless it is not required by the interface/class."

**Comment by jmarolf** [comment]
@dotnet-bot retest this please

File: src/EditorFeatures/VisualBasicTest/Diagnostics/ImplementAbstractClass/ImplementAbstractClassTests.vb (hunk 1 above)
Comment (DustinCampbell) [inline src/EditorFeatures/VisualBasicTest/Diagnostics/ImplementAbstractClass/ImplementAbstractClassTests.vb]: not anymore. Only use XML literals if you need to define a workspace. Use a VB multi-line string literal. :smile:

**Comment by tannergooding** [comment]
@dotnet-bot, test this please

**Comment by jmarolf** [comment]
@dotnet-bot retest this please

**Comment by tannergooding** [comment]
@jmarolf. Not sure why it is still reporting 'No test results found'. clicking on the 'Details' link clearly shows there is 1 failure in `Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics.ImplementAbstractClass.ImplementAbstractClassTests.TestOnlyGenerateUnimplementedAccessors`.

@mmitche, are you aware of why the information is reporting 'No test results found'?

**Comment by mmitche** [comment]
@tannergooding Does that actually work?  I've never seen anything but "No test results found".

**Comment by tannergooding** [comment]
@mmitche, I would expect it to do so.

**Comment by Pilchie** [comment]
:+1:
