### PR TITLE
Fix ParseVBErrorOrWarning

### LINKED ISSUE #47790: Building VB.NET project can report errors with invalid paths when the file path contains a number within parentheses
**Version Used**: 
VS 2019 v16.7.3
Recently repaired to see whether that fixed the issue.  It did not.

**Steps to Reproduce**:
1. Create a new VB.NET project in a path that contains a number within parentheses.  ie: E:\VBProject (x64)\BadErrorPath
2. Write a line of code that has an error in it.  ie: asdf
3. Verify that the Error List window shows the Line, Col, Path, and Source columns.
4. Close the code window.
5. Build the project.

**Expected Behavior**:
Expected the Error List to show the correct path, line, and column for the error.
Expected to be able to double-click the build error line to open the file with the error, positioned to the error line.

**Actual Behavior**:
I get two errors,  The one from the **Build** source says line 1, column 1 and has a bad path.  Double-clicking it does nothing.

The whole build output is below and in it I see:
**E:\VBProject (x64,9)\BadErrorPath\Module1.vb(4)**: error BC30451: 'asdf' is not declared. It may be inaccessible due to its protection level.

It looks like the (x64) from the path is tricking error reporting into placing the column number in those parentheses rather than after the line number in (4).

1>------ Build started: Project: BadErrorPath, Configuration: Debug Any CPU ------
1>Build started 9/17/2020 1:25:21 PM.
1>GenerateBindingRedirects:
1>  No suggested binding redirects from ResolveAssemblyReferences.
1>CoreResGen:
1>  No resources are out of date with respect to their source files. Skipping resource generation.
1>GenerateTargetFrameworkMonikerAttribute:
1>Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
1>CoreCompile:
1>  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\vbc.exe /noconfig {Snipped long line}
1>  Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn
1>E:\VBProject (x64,9)\BadErrorPath\Module1.vb(4): error BC30451: 'asdf' is not declared. It may be inaccessible due to its protection level.
1>
1>Build FAILED.
1>
1>"E:\VBProject (x64)\BadErrorPath\BadErrorPath.vbproj" (Build;BuiltProjectOutputGroup;BuiltProjectOutputGroupDependencies;DebugSymbolsProjectOutputGroup;DebugSymbolsProjectOutputGroupDependencies;DocumentationProjectOutputGroup;DocumentationProjectOutputGroupDependencies;SatelliteDllsProjectOutputGroup;SatelliteDllsProjectOutputGroupDependencies;SGenFilesOutputGroup;SGenFilesOutputGroupDependencies target) (1) ->
1>(CoreCompile target) -> 
1>  E:\VBProject (x64,9)\BadErrorPath\Module1.vb(4): error BC30451: 'asdf' is not declared. It may be inaccessible due to its protection level.
1>
1>    0 Warning(s)
1>    1 Error(s)
1>
1>Time Elapsed 00:00:00.04

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #47790

Not sure how/where to write tests for this. I was also unable to test this locally due to getting some unrelated exception (https://github.com/dotnet/roslyn/issues/47562#issuecomment-694899372).

### CODE REVIEW

File: src/Compilers/Core/MSBuildTask/Vbc.cs [hunk 1]
```diff
@@ -651,9 +651,6 @@ protected override void LogEventsFromTextOutput(string singleLine, MessageImport
         /// Given a string, parses it to find out whether it's an error or warning and, if so,
         /// make sure it's validated properly.  
         /// </summary>
-        /// <comments>
-        /// INTERNAL FOR UNITTESTING ONLY
-        /// </comments>
```
Comment (Youssef1313) [inline src/Compilers/Core/MSBuildTask/Vbc.cs:656]: I deleted this because I don't see this method is for unit testing only. Please can someone confirm?

**Comment by adambiser** [comment]
Mightn't the error description contain parentheses?  If so, using LastIndexOf would grab it instead.
I wonder whether it would be better to use IndexOf("):") since that combination isn't path of a valid path, so the first occurrence should be after the line number.

**Comment by Youssef1313** [comment]
@adambiser Yeah that's correct. Fixed.

File: src/Compilers/Core/MSBuildTask/Vbc.cs (hunk 1 above)
Comment (333fred) [reply src/Compilers/Core/MSBuildTask/Vbc.cs:656]: It does seem to be unused other than above. Consider making this `private` instead, given that.

---
In reply to: [491003584](https://github.com/dotnet/roslyn/pull/47833#discussion_r491003584) [](ancestors = 491003584)

**Review by 333fred — APPROVED** [review]
LGTM (commit 2). @jaredpar, can you take a second look?

**Comment by AlekseyTs** [comment]
I think we need to find a way to test the change.

**Comment by Youssef1313** [comment]
@AlekseyTs I agree, but I'm unfortunately unaware of how to test this.

File: src/Compilers/Core/MSBuildTask/Vbc.cs [hunk 2]
```diff
@@ -651,12 +651,9 @@ protected override void LogEventsFromTextOutput(string singleLine, MessageImport
...
         /// <param name="singleLine">The line to parse</param>
         /// <param name="messageImportance">The MessageImportance to use when reporting the error.</param>
-        internal void ParseVBErrorOrWarning(string singleLine, MessageImportance messageImportance)
+        private void ParseVBErrorOrWarning(string singleLine, MessageImportance messageImportance)
```
Comment (jaredpar) [inline src/Compilers/Core/MSBuildTask/Vbc.cs:656]: Agree in general that it's hard to test the various `Tasks` because it becomes more of an integration test with MSBuild. In this particular case though we're effectively altering how VB error messages are parsed in the task. I think we could factor this method a bit, by either adding a `static` method or by just newing up the `Task` in test and setting the properies, and use that to validate this change works (and stays correct going forward).

**Comment by adambiser** [comment]
There is a pull request on Youssef1313:patch-7 that has tests and fixes the issue.  The fix here does not parse what comes from vbc correctly (should be a space between the end parenthesis and the colon).  It has been waiting for a couple of weeks.  Should I close it and start a separate pull request for this issue?

**Comment by 333fred** [comment]
It's possible that @Youssef1313 didn't know the request was there?

**Comment by adambiser** [comment]
Possibly, but I thought that sending a pull request also sent a notification.

**Comment by 333fred** [comment]
> Possibly, but I thought that sending a pull request also sent a notification.

On forks, I believe notifications are actually off by default.

**Comment by adambiser** [comment]
OK.  I had forked from his fork so I thought he would get notification of the pull request to his repo.

File: src/Compilers/Core/MSBuildTaskTests/TestUtilities/ErrorLoggerEngine.cs [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+            _log.AppendLine();
+        }
+
+        public void LogCustomEvent(CustomBuildEventArgs eventArgs)
+        {
+        }
+
+        public void LogMessageEvent(BuildMessageEventArgs eventArgs)
+        {
+        }
```
Comment (Youssef1313) [inline src/Compilers/Core/MSBuildTaskTests/TestUtilities/ErrorLoggerEngine.cs:60]: Should throw `NotImplementedException` instead?

Comment (adambiser) [reply src/Compilers/Core/MSBuildTaskTests/TestUtilities/ErrorLoggerEngine.cs:60]: And thank you, too.  I had assumed you would get a notification since I had forked from you instead of the main project.  Figured other things were filling your time, as is easy to happen nowadays.  But now I know.

As for NotImplementedException, I don't think so.  I added the class solely to get to the warning and error output, though I guess given the class's limited usage, throwing NotImplementedException in both probably won't affect things.
I also was unaware of how to test this and ended up with two.  Not sure whether they will approve of the tests or not though.

File: src/Compilers/Core/MSBuildTaskTests/TestUtilities/ErrorLoggerEngine.cs [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+
+        public ErrorLoggingEngine()
+        {
+            // Use the formatting from Microsoft.Build.Shared.EventArgsFormatting.
+            var assembly = Assembly.LoadFrom("Microsoft.Build.dll");
+            var formattingClass = assembly.GetType("Microsoft.Build.Shared.EventArgsFormatting") ?? throw new Exception("Could not find EventArgsFormatting type");
+            _formatErrorMethod = formattingClass.GetMethod("FormatEventMessage", BindingFlags.Static | BindingFlags.NonPublic, null, CallingConventions.Any,
+                new Type[] { typeof(BuildErrorEventArgs) }, null) ?? throw new Exception("Could not find FormatEventMessage(BuildErrorEventArgs).");
+            _formatWarningMethod = formattingClass.GetMethod("FormatEventMessage", BindingFlags.Static | BindingFlags.NonPublic, null, CallingConventions.Any,
+                new Type[] { typeof(BuildWarningEventArgs) }, null) ?? throw new Exception("Could not find FormatEventMessage(BuildWarningEventArgs).");
```
Comment (333fred) [inline src/Compilers/Core/MSBuildTaskTests/TestUtilities/ErrorLoggerEngine.cs:33]: Using reflection here concerns me greatly. @rainersigwald, do you have suggestions for a better way to accomplish this?

Comment (333fred) [reply src/Compilers/Core/MSBuildTaskTests/TestUtilities/ErrorLoggerEngine.cs:33]: For context, we're trying to test our parsing of msbuild error message output in Vbc.exe

Comment (rainersigwald) [reply src/Compilers/Core/MSBuildTaskTests/TestUtilities/ErrorLoggerEngine.cs:33]: Sorry, missed this. I agree that this feels icky but I'm afraid I don't have a better idea at the moment.

**Comment by 333fred** [comment]
@jaredpar, if you have some time can you take a look at this PR?

**Review by jcouv — APPROVED** [review]
LGTM (iteration 6). Thanks for figuring out a way to unittest the change.

**Comment by jcouv** [comment]
@jaredpar @RikkiGibson Something strange is happening with CI. The Spanish legs fail after retry, but when I try to get details I get "Build not found" (and no details). Any clues?

**Comment by RikkiGibson** [comment]
The build might be too old to retry. I suggest merging master into the PR branch.

**Comment by adambiser** [comment]
The unit tests fail in Spanish because it's checking for the English error message text.

https://github.com/dotnet/roslyn/pull/47833/files#diff-10b671e15f3cd08b75ffd476f257613f8f99459752c107ba458ae68def5c02fc
```
Assert.Contains("\Test Path (123)\hellovb.vb(6) : warning BC40008: 'Public Property x As Integer' is obsolete.", output.ToString())
Assert.Contains("\Test Path (123)\hellovb.vb(6) : error BC30512: Option Strict On disallows implicit conversions from 'Double' to 'Integer'.", output.ToString())
Assert.Contains("\Test Path (123)\hellovb.vb(7) : error BC30451: 'asdf' is not declared. It may be inaccessible due to its protection level.", output.ToString())
```
But in Spanish it should check for
```
\Test Path (123)\hellovb.vb(6) : warning BC40008: 'Public Property x As Integer' está obsoleto.
\Test Path (123)\hellovb.vb(6) : error BC30512: Option Strict On no permite conversiones implícitas de 'Double' a 'Integer'.
\Test Path (123)\hellovb.vb(7) : error BC30451: 'asdf' no está declarado. Puede que sea inaccesible debido a su nivel de protección.
```

I guess it needs <ConditionalFact(GetType(IsEnglishLocal))> to be skipped for the Spanish checks?

**Comment by jcouv** [comment]
Thanks @adambiser!
@Youssef1313 I'll let you update. Thanks

File: src/Compilers/Core/MSBuildTask/Vbc.cs [hunk 5]
```diff
@@ -252,6 +252,8 @@ private protected override void LogCompilerOutput(string output, MessageImportan
             }
         }
 
+        internal void LogCompilerOutput_ForTestingOnly(string output, MessageImportance messageImportance) => LogCompilerOutput(output, messageImportance);
```
Comment (Youssef1313) [inline src/Compilers/Core/MSBuildTask/Vbc.cs:255]: That looks UGLY. Can we change `LogCompilerOutput` back to `internal` instead?

**Comment by Youssef1313** [comment]
Sorry for the delay here. The last commit should hopefully pass CI.

File: src/Compilers/VisualBasic/Test/CommandLine/CommandLineTests.vb [hunk 6]
```diff
@@ -337,6 +337,39 @@ End Module
             Assert.Equal("", output.ToString().Trim())
         End Sub
 
+        <Fact()>
```
Comment (333fred) [inline src/Compilers/VisualBasic/Test/CommandLine/CommandLineTests.vb:340]:
```suggestion
```

File: src/Compilers/Core/MSBuildTask/ManagedCompiler.cs [hunk 7]
```diff
@@ -686,12 +686,13 @@ private int HandleResponse(Guid requestId, BuildResponse? response, string pathT
             }
         }
 
+        // Internal for testing only.
```
Comment (jaredpar) [inline src/Compilers/Core/MSBuildTask/ManagedCompiler.cs:689]: Consider putting in a `<remarks>` section

File: src/Compilers/Core/MSBuildTask/Vbc.cs [hunk 8]
```diff
@@ -689,7 +686,7 @@ internal void ParseVBErrorOrWarning(string singleLine, MessageImportance message
                     string originalVBErrorString = originalVBError.Message;
 
                     int column = singleLine.IndexOf('~') + 1;
-                    int endParenthesisLocation = originalVBErrorString.IndexOf(')');
+                    int endParenthesisLocation = originalVBErrorString.IndexOf(") :");
```
Comment (jaredpar) [inline src/Compilers/Core/MSBuildTask/Vbc.cs:689]:
```suggestion
                    int endParenthesisLocation = originalVBErrorString.IndexOf(") :", StringComparison.Ordinal);
```

As long as we are changing the code lets make the comparison explicit to avoid the `net5` changes around string comparison.

**Review by jaredpar — APPROVED** [review]

**Review by jaredpar — APPROVED** [review]
