### PR TITLE
Disallow ref structs in expression trees

### LINKED ISSUE #30776: Using default() with ref struct in expression causes CS7038: Failed to emit module
**Version Used**: 
Tested with sdk 2.1.402 and 2.1.500-preview-009335
**Steps to Reproduce**:

1. Create a project
2. 
``` csharp
using System;
using System.Linq.Expressions;
public class Class1
{
    public void Method1()
    {
        Method((Class1 c) => c.Method2(default(Struct1)));
    }

    public void Method2(Struct1 s1) { }

    public static void Method<T>(Expression<Action<T>> expression) { }
}

public ref struct Struct1 { }
```
3. Build project

**Expected Behavior**:
Build succeeds
**Actual Behavior**:
error CS7038: Failed to emit module '_'.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Resolves #30776 

This adds the error code `ErrorCode.ERR_ExpressionTreeCantContainRefStruct`.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs [hunk 1]
```diff
@@ -514,7 +515,12 @@ private BoundLambda ReallyBind(NamedTypeSymbol delegateType)
             ((ExecutableCodeBinder)lambdaBodyBinder).ValidateIteratorMethods(diagnostics);
             ValidateUnsafeParameters(diagnostics, cacheKey.ParameterTypes);
 
-        haveLambdaBodyAndBinders:
+haveLambdaBodyAndBinders:
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: not sure how this got dedented

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs [hunk 2]
```diff
@@ -516,6 +517,11 @@ private BoundLambda ReallyBind(NamedTypeSymbol delegateType)
 
         haveLambdaBodyAndBinders:
 
+            if (delegateType.IsExpressionTree())
+            {
+                ExpressionTreeRefLikeWalker.Analyze(binder.Compilation, lambdaSymbol, block, diagnostics);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: This isn't sufficient to catch parameters of ref struct types. Will need to analyze a different BoundNode (maybe just use the BoundLambda?)

**Comment by RikkiGibson** [comment]
On the topic of parameters: `ref struct` is already prohibited for generic arguments, which means it can't be used in `Action<T>` but could be used in `delegate void MyDelegate(MyRefStruct s)`. Should it even be allowed in delegate parameter/return types?

File: src/Compilers/CSharp/Portable/FlowAnalysis/ExpressionTreeRefLikeWalker.cs [hunk 3]
```diff
@@ -0,0 +1,45 @@
+﻿using System;
+using System.Collections.Generic;
+using System.Text;
+
+namespace Microsoft.CodeAnalysis.CSharp.FlowAnalysis
+{
+    internal class ExpressionTreeRefLikeWalker : BoundTreeWalker
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/FlowAnalysis/ExpressionTreeRefLikeWalker.cs]: Why can't we add this validation to existing walkers of expression trees?

File: src/Compilers/CSharp/Portable/FlowAnalysis/ExpressionTreeRefLikeWalker.cs [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+    {
+        private readonly CSharpCompilation _compilation;
+        private readonly Symbol _member;
+        private readonly BoundBlock _block;
+        private readonly DiagnosticBag _diagnostics;
+        private bool _expressionTreeContainsRefLikeExpressions = false;
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/FlowAnalysis/ExpressionTreeRefLikeWalker.cs]: Explicit initialization not needed here.

File: src/Compilers/CSharp/Portable/FlowAnalysis/ExpressionTreeRefLikeWalker.cs (hunk 3 above)
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/FlowAnalysis/ExpressionTreeRefLikeWalker.cs]: sealed class

File: src/Compilers/CSharp/Portable/FlowAnalysis/ExpressionTreeRefLikeWalker.cs [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+        }
+
+        protected override BoundExpression VisitExpressionWithoutStackGuard(BoundExpression node)
+        {
+            return (BoundExpression)base.Visit(node);
+        }
+
+        public override BoundNode Visit(BoundNode node)
+        {
+            if (node is BoundExpression expr && expr.Type.IsByRefLikeType)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/FlowAnalysis/ExpressionTreeRefLikeWalker.cs]: Can Type be null here?

File: src/Compilers/CSharp/Portable/FlowAnalysis/ExpressionTreeRefLikeWalker.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/ExpressionTreeRefLikeWalker.cs]: I think it makes more sense to pull this into the existing walker--should I just make this check into some private helper and call it from the various places that expressions are visited in `DiagnosticsPass_ExpressionTrees`?

File: src/Compilers/CSharp/Portable/FlowAnalysis/ExpressionTreeRefLikeWalker.cs (hunk 5 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/ExpressionTreeRefLikeWalker.cs]: Probably.

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs [hunk 6]
```diff
@@ -211,6 +211,18 @@ public override BoundNode VisitCompoundAssignmentOperator(BoundCompoundAssignmen
             }
         }
 
+        public override BoundNode Visit(BoundNode node)
+        {
+            if (_inExpressionLambda &&
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs]: I'd like to be able to just do this instead of having to add Visit overrides and helper calls for every type of expression syntax that could have a ByRefLike type.

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs [hunk 7]
```diff
@@ -342,6 +354,21 @@ public override BoundNode VisitLambda(BoundLambda node)
...
+                var lambda = node.ExpressionSymbol as MethodSymbol;
+                if ((object)lambda != null)
+                {
+                    foreach (var p in lambda.Parameters)
+                    {
+                        if (p.RefKind != RefKind.None && p.Locations.Length != 0)
+                        {
+                            _diagnostics.Add(ErrorCode.ERR_ByRefParameterInExpressionTree, p.Locations[0]);
+                        }
+                        if (p.Type.TypeSymbol?.IsByRefLikeType == true)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs]: BoundLambda traversal doesn't traverse into the parameter syntax so we have to do additional checks here. Since the ByRefLike checks happen regardless of whether the lambda is "simple" or "parenthesized" I extracted the loop out to here.

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs (hunk 6 above)
Comment (agocke) [reply src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs]: I'd suggest something like

```C#
override BoundNode Visit(BoundExpression expr)
{
   if (expr.Type?.IsByRefLikeType == true)
   {
        Error(...)
   }
   return base.Visit(node);
}
```

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs [hunk 8]
```diff
@@ -211,6 +211,19 @@ public override BoundNode VisitCompoundAssignmentOperator(BoundCompoundAssignmen
             }
         }
 
+        public override BoundNode Visit(BoundNode node)
+        {
+            if (_inExpressionLambda &&
+                !(node is BoundConversion) &&
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs]: Why exclude `BoundConversion`?

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs [hunk 9]
```diff
@@ -211,6 +211,19 @@ public override BoundNode VisitCompoundAssignmentOperator(BoundCompoundAssignmen
...
+                node is BoundExpression expr &&
+                expr.Type is TypeSymbol type &&
+                type.IsByRefLikeType)
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs]: We should probably exclude all "restricted" types, not just ref structs.

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs [hunk 10]
```diff
@@ -211,6 +211,19 @@ public override BoundNode VisitCompoundAssignmentOperator(BoundCompoundAssignmen
...
+            {
+                Error(ErrorCode.ERR_FeatureNotValidInExpressionTree, node, "ref struct");
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs]: I think it would be fine to just put the type's name here.  We don't want unlocalized strings like this in diagnostics.  We do have a localized feature name if you really want this text.

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs [hunk 11]
```diff
@@ -342,6 +355,21 @@ public override BoundNode VisitLambda(BoundLambda node)
...
+                {
+                    foreach (var p in lambda.Parameters)
+                    {
+                        if (p.RefKind != RefKind.None && p.Locations.Length != 0)
+                        {
+                            _diagnostics.Add(ErrorCode.ERR_ByRefParameterInExpressionTree, p.Locations[0]);
+                        }
+                        if (p.Type.TypeSymbol?.IsByRefLikeType == true)
+                        {
+                            _diagnostics.Add(ErrorCode.ERR_FeatureNotValidInExpressionTree, p.Locations[0], "ref struct");
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs]: Use the localized feature name please

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs [hunk 12]
```diff
@@ -342,6 +355,21 @@ public override BoundNode VisitLambda(BoundLambda node)
         {
             if (_inExpressionLambda)
             {
+                var lambda = node.ExpressionSymbol as MethodSymbol;
+                if ((object)lambda != null)
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs]: I think you can just say `node.Symbol`, which is a LambdaSymbol, which inherits from MethodSymbol (i.e., I don't think this check can ever fail).

File: src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs [hunk 13]
```diff
@@ -1533,6 +1533,159 @@ static void Main()
...
+    public void Method2(Struct1 s1) { }
+
+    public static void Method<T>(Expression<Action<T>> expression) { }
+}
+
+public ref struct Struct1 { }
+";
+            var compilation = CreateCompilationWithMscorlib40AndSystemCore(text).VerifyDiagnostics(
+                // (8,40): error CS7053: An expression tree may not contain 'ref struct'
+                //         Method((Class1 c) => c.Method2(default(Struct1)));
```
Comment (agocke) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs]: Not a fan of this error message. I'd add a new one that says something like, "expression trees may not contain values of `ref struct` type." It's not too hard to add a resource and it would be much clearer.

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs (hunk 9 above)
Comment (agocke) [reply src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs]: That's a good point. We have an `IsRestrictedType` helper that should check everything.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs]: Sounds good

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs (hunk 12 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs]: Sounds good

File: src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs (hunk 13 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs]: Does this mean adding a new error code? Anything I should know about how creating new ErrorCode values works?

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs (hunk 8 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs]: This prevents redundant diagnostics in the [`RefStructDefaultExpressionTree`](https://github.com/dotnet/roslyn/pull/30871/commits/a080a34e149ee13c5b5188e0eb19982982ee8536#diff-609b3f09c132215b9994e189fd2a5861R1572) test case. In that case we'd have a `BoundConversion` containing a `BoundDefaultExpression`, where the type of both nodes `IsByRefLikeType`.

I'm wondering if there are other scenarios that would generate redundant diagnostics. Is there a better practice for handling this kind of problem?

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs (hunk 10 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs]: @agocke's suggestion in https://github.com/dotnet/roslyn/pull/30871#discussion_r230208523 seems reasonable

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs (hunk 8 above)
Comment (agocke) [reply src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs]: We really don't -- cascading diagnostics are handled on a case-by-case basis right now. In theory it sounds like what you really want is only one instance of this diagnostic to be reported per syntax node, but that sounds way too complicated for this bug. I think your solution is fine, but I would add a comment about why you're filtering conversions.

File: src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs (hunk 13 above)
Comment (agocke) [reply src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs]: Yup, it basically means you add a new error to the bottom of ErrorCode.cs and add a corresponding resource with the same name as the enum value to CSharpResources.resx (use an XML or simple text editor) at the bottom.

**Comment by RikkiGibson** [comment]
Resolved feedback. Please have another look.

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs [hunk 14]
```diff
@@ -211,6 +211,20 @@ public override BoundNode VisitCompoundAssignmentOperator(BoundCompoundAssignmen
             }
         }
 
+        public override BoundNode Visit(BoundNode node)
+        {
+            if (_inExpressionLambda &&
+                // Ignoring BoundConversion nodes prevents redundant diagnostics
+                !(node is BoundConversion) &&
+                node is BoundExpression expr &&
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs]: I think it's still easier to override `Visit(BoundExpression)` instead of `BoundNode`

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs]: I tried changing `Visit(BoundNode node)` to `VisitExpressionWithNullability(BoundExpressionWithNullability node)` and it never gets called :/

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler please have a look
