### PR TITLE
Avoid assert in emit layer when intercepted call implicitly captures receiver to temp

### LINKED ISSUE #71657: Intercepting a struct rvalue instance method call with an extension method trips a debug assertion in the compiler
We should resolve by either emitting an error at the interception (which feels unfortunate, but consistent with extension method calls), or by creating a temp during lowering.

Note that the shipped release-mode behavior here is to create a temp in the emit layer and do the call.
 
https://github.com/dotnet/roslyn/blob/1c88444212854f6b6be43d9901f6c3d541bdcafa/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs#L722

```cs
[Fact]
public void InterceptStructInstanceMethod_RvalueReceiver()
{
    // TODO2: this test crashes in debug mode due to assert in EmitExpression.cs:722.
    var source = ($$"""
        using System;

        struct Program
        {
            public void InterceptableMethod() => Console.Write("Original");

            public static void Main()
            {
                new Program().InterceptableMethod();
            }
        }
        """, "Program.cs");

    var interceptor = ("""
        using System.Runtime.CompilerServices;
        using System;

        static class D
        {
            [InterceptsLocation("Program.cs", 9, 23)]
            public static void Interceptor(this ref Program x) => Console.Write("Intercepted");
        }
        """, "Interceptor.cs");

    var verifier = CompileAndVerify(new[] { source, s_attributesSource }, parseOptions: RegularWithInterceptors);
    verifier.VerifyDiagnostics();
    verifier.VerifyIL("Program.Main", """
        {
            // Code size       15 (0xf)
            .maxstack  2
            .locals init (Program V_0)
            IL_0000:  ldloca.s   V_0
            IL_0002:  dup
            IL_0003:  initobj    "Program"
            IL_0009:  call       "void Program.InterceptableMethod()"
            IL_000e:  ret
        }
        """);

    verifier = CompileAndVerify(new[] { source, interceptor, s_attributesSource }, parseOptions: RegularWithInterceptors);
    verifier.VerifyDiagnostics();
    verifier.VerifyIL("Program.Main", """

        """);
}
```

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #71657

Extracted from #74363. This part of the change I feel confident is one we should be making. The other part I want to revisit and PR separately.

This PR is preserving an already-shipped behavior without changing it. It is just changing the exact way we get that behavior by adding the temp in lowering, when we know we are in the specific situation we want to permit, rather than in the more general code path in emit, which was tripping a debug assertion.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs [hunk 1]
```diff
@@ -7513,4 +7513,333 @@ static class Interceptors
...
+        var node = source.GetRoot().DescendantNodes().OfType<InvocationExpressionSyntax>().Last();
+        var locationSpecifier = model.GetInterceptableLocation(node)!;
+
+        var interceptors = CSharpTestSource.Parse($$"""
+            using System;
+
+            public static class C
+            {
+                {{locationSpecifier.GetInterceptsLocationAttributeSyntax()}}
+                public static void M1(this ref S s) => Console.WriteLine(1);
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs:7545]: Consider using `s` in a way that mutates, to show that we are actually capturing by ref and that the results are observable. The same for the rest of the test methods.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs:7545]: I am wondering how exactly should I demonstrate this? Do you want me to try and read the managed reference at the call site (e.g. by returning 'ref S s' by-reference)?

Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs:7545]: Yeah, that would work.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs:7545]: > read the field from the local

The lowering temp which is being passed by-ref to the call can't be directly used in user code. We would have to return a ref to that temp if we wanted the call site to be able to read it.

Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs:7545]: Am I misunderstanding the original bug? I expect something like this would be accessible, and would have triggered the emit assert:

```cs
var s = new S();
s.M(); // Intercepted, and `s` was mutated
```

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs:7545]: That case would not trigger the assert. The assert occurs when the compiler needs to create a temp for the receiver to use as an argument for a by-ref `this` parameter, such as `new S().M()`. It won't occur when the receiver argument is already something we can pass by-reference for the `this` parameter.

The emit layer is fine with creating a temp for an instance call receiver in the `new S().M()` case. However, when we intercept the call with a method like `static Extension(this ref S s)`, it basically sees the call as `Extension(new S())`, doesn't expect to create a temp for `new S()`, and will assert.

Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs:7545]: Could we observe this with a `ref`-returning method? IE, something like this?

```cs
var s = new S();
Identity(ref s).M();
s.ObserveMutated();

ref S Identity(ref S s) => ref s;
```

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs:7545]: I think in this case the compiler also doesn't need to capture the receiver 'Identity(ref s)' to temp. But we can go ahead and add the test to show that we use the reference properly here.

Comment (jaredpar) [reply src/Compilers/CSharp/Test/Semantic/Semantics/InterceptorsTests.cs:7545]: Think we could observe it this way 

```csharp
using System;
using System.Diagnostics.CodeAnalysis;

Span<int> Test() {
  // should error in both intercepted and non intercepted case
  return new S().M();
}

ref struct S {
    [UnscopedRef]
    public Span<int> M() => default;
}

static class D
{
    [InterceptsLocation(1, "...")]
    public static Span<int> Interceptor(this ref S s)
}
```

**Review by 333fred — APPROVED** [review]

**Review by jaredpar — APPROVED** [review]
