### PR TITLE
Ensure that `modreq(InAttribute)` is emitted for synthesized `ref readonly` returning methods

### LINKED ISSUE #76847: Unexpected metadata for function signature when defined as member vs local
The following definitions of the same signature result in surprising different metadata.

```csharp
static class Accessors
{
    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<obj>P")]
    public static extern ref readonly object MEMBER(ref readonly Foo value); 
    
    public static void A()
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<obj>P")]
        static extern ref readonly object LOCAL(ref readonly Foo value);
    }
}
```

[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwAICYCMBYAKAwAYACDHAOgCUBXGBKMAU0oGEB7MAB1WYCcAygIBuUAMbMAzgG5ChfswgATDjBQBPUlIT9a4hKQBiHDgAoOwAFbMDpS1bilYhiAEpCAb0Klf5ACykALJmbqQAvAB8pAD6EfbWcgR+AaQAcqER0XHhpBBJAL7yRDgAbORYpACC4pJSUhz8Ul4+fgDaAKowUhAAZsw1dQ38Zl09/YPSwwDSsMqURlDMKMpOaRAs8QBEADwOkQAKW24Auq2+GADM5GWkzAAeCAIwpIq9r0qq6loOtoZBAFEggAhAHUMxvD4qNSaYymUgiCAoWjMNwyUjnDHJPxXG7lDCBKqhTHebEpXydbp9Aa1KaNUZUia0+qNWYweaLZardIbZjbPbWQ7HM5k8kUcoPJ78F6QxTQ74JGx2AAyAHk2FVlRDmO85V9YSYOAikSi0ZiigQCkA===)

For `MEMBER`:
```
    .method public hidebysig static 
        object& modreq([System.Runtime]System.Runtime.InteropServices.InAttribute) MEMBER (
            [in] valuetype Foo& 'value'
        ) cil managed 
```

For `LOCAL`:
```
    .method assembly hidebysig static 
        object& '<A>g__LOCAL|1_0' (
            [in] valuetype Foo& 'value'
        ) cil managed 
```

The primary surprise is lack of the `modreq` on the `LOCAL` signature. This confusion led to the writing of a test that "validated" nothing, because there was no `modreq`. This difference is now understood and the runtime team will make sure tests are written to respect this fact, but it does seem odd the exact signature will yield different signatures when there are cases the runtime cares about custom modifiers.

See https://github.com/dotnet/runtime/issues/111647 for the issue.

/cc @jaredpar @AlekseyTs

### PR DESCRIPTION
**Pull request by AlekseyTs**
Closes #76847

### CODE REVIEW

**Review by 333fred — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review

File: src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs [hunk 1]
```diff
@@ -5857,6 +5857,9 @@ static void F(Delegate d) { }
 
             var comp = CreateCompilation(source);
             comp.VerifyDiagnostics(
+                // (5,20): warning CS0649: Field 'var.o' is never assigned to, and will always have its default value null
+                //     internal other o;
+                Diagnostic(ErrorCode.WRN_UnassignedInternalField, "o").WithArguments("var.o", "null").WithLocation(5, 20),
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs:5862]: It's not obvious how this change in diagnostic output results from the change. Is this change expected? #Closed

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs:5862]: > It's not obvious how this change in diagnostic output results from the change. Is this change expected?

It is cased by changes in `Binder_Statements.cs`, we no longer treat body of ```ref var () => throw null``` as returning a reference to an instance of "@var" type. Therefore, we don't treat it as a possible write to the field.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs:5862]: The behavior is consistent with explicit return statements

File: src/Compilers/CSharp/Portable/BoundTree/BoundExpressionExtensions.cs [hunk 2]
```diff
@@ -138,6 +138,13 @@ public static bool HasDynamicType(this BoundExpression node)
 
             var delegateType = expr.GetFunctionType()?.GetInternalDelegateType();
             delegateType?.AddUseSiteInfo(ref useSiteInfo);
+
+            if (expr is BoundMethodGroup { Methods: not [{ MethodKind: MethodKind.LocalFunction }] } &&
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/BoundTree/BoundExpressionExtensions.cs:145]: Is this check for `MethodKind` just to avoid cascading diagnostics (ie. checking the `InAttribute` both on the local function declaration and again on the usage)?
nit: If so, consider leaving a comment #Resolved

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/BoundTree/BoundExpressionExtensions.cs:145]: Added a comment
