### PR TITLE
Bail out for error types from IDE0058 analyzer (unused expression value)

### LINKED ISSUE #33073: IDE0058 reported if type does not resolve
**Version Used**: Visual Studio 2019 Preview 2

**Steps to Reproduce**:

Write the following _without_ including an import for `System.Threading`.

```
await Task.Delay(0, CancellationToken.None).ConfigureAwait(false);
```

**Expected Behavior**:

IDE0058 not reported.

**Actual Behavior**:

IDE0058 is reported, and the code fix adds `_ =` in front of the statement.

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #33073

### CODE REVIEW

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs [hunk 1]
```diff
@@ -137,8 +137,9 @@ private void AnalyzeExpressionStatement(OperationAnalysisContext context)
 
                     // Bail out cases for report unused expression value:
 
-                    //  1. Null type and void returning method invocations: no value being dropped here.
+                    //  1. Null type, error type and void returning method invocations: no value being dropped here.
                     if (value.Type == null ||
+                        value.Type.IsErrorType() ||
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs]: we have IsNullOrErrorType as a helper somewhere i think :)

Comment (mavasani) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs]: Ah thanks! Will keep in mind for now on.

**Comment by mavasani** [comment]
@jinujoseph @vatsalyaagrawal for approval
