### PR TITLE
Do not suggest using implicit type for stackalloc initialization

### LINKED ISSUE #22768: IDE0007 reported for stackalloc to Span<T>
**Version Used**: 15.5 Preview 1

**Steps to Reproduce**:

```csharp
Span<int> span = stackalloc int[3];
```

**Expected Behavior**:

IDE0007 is not reported, because a change to use `var` also changes the type of `span`.

**Actual Behavior**:

IDE0007 is reported, and the code fix causes the code to break.

### PR DESCRIPTION
**Pull request by OmarTawfik**
Fixes #22768

vso bug : https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_workitems/edit/517749

cc @sharwell @jcouv @dotnet/roslyn-ide

### CODE REVIEW

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -107,9 +107,18 @@ protected override bool TryAnalyzeVariableDeclaration(TypeSyntax typeName, Seman
                 }
 
                 var variable = variableDeclaration.Variables.Single();
-                if (AssignmentSupportsStylePreference(
-                        variable.Identifier, typeName, variable.Initializer.Value,
-                        semanticModel, optionSet, cancellationToken))
+                var initializer = variable.Initializer.Value;
+
+                // Discourage using "var pointer = stackalloc", after introducing C# 7.2, as it might be confusing to users expecting a Span<>
+                // Check descendant nodes as well, because Span-creating stackallocs can be nested in other nodes (like conditional operators and casts).
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs]: that seems odd... what if i had something like ```Type t = foo(... stackalloc ...);```

This would still be a location where converting to 'var' woudl be ok, right?

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs [hunk 2]
```diff
@@ -107,9 +107,18 @@ protected override bool TryAnalyzeVariableDeclaration(TypeSyntax typeName, Seman
...
+                // https://github.com/dotnet/roslyn/issues/22768
+                if (initializer.DescendantNodesAndSelf().Any(node => node.IsKind(SyntaxKind.StackAllocArrayCreationExpression)))
+                {
+                    issueSpan = default;
+                    return false;
+                }
+
+                if (AssignmentSupportsStylePreference(variable.Identifier, typeName, initializer, semanticModel, optionSet, cancellationToken))
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs]: i woudl keep the wrapping as it was before.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs]: what if the stackalloc is inside a lambda that is on the right hand side?  it seems weird that this would disable this feature at this level.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs [hunk 3]
```diff
@@ -107,9 +107,18 @@ protected override bool TryAnalyzeVariableDeclaration(TypeSyntax typeName, Seman
                 }
 
                 var variable = variableDeclaration.Variables.Single();
-                if (AssignmentSupportsStylePreference(
-                        variable.Identifier, typeName, variable.Initializer.Value,
-                        semanticModel, optionSet, cancellationToken))
+                var initializer = variable.Initializer.Value;
+
+                // Discourage using "var pointer = stackalloc", after introducing C# 7.2, as it might be confusing to users expecting a Span<>
```
Comment (sharwell) [inline src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs]: ❗️ This analyzer isn't the place to do this. The new C# 7.2 features do not affect the use of `var` from the perspective of this analyzer.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs [hunk 4]
```diff
@@ -107,9 +107,18 @@ protected override bool TryAnalyzeVariableDeclaration(TypeSyntax typeName, Seman
...
+                // Check descendant nodes as well, because Span-creating stackallocs can be nested in other nodes (like conditional operators and casts).
+                // https://github.com/dotnet/roslyn/issues/22768
+                if (initializer.DescendantNodesAndSelf().Any(node => node.IsKind(SyntaxKind.StackAllocArrayCreationExpression)))
```
Comment (sharwell) [inline src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs]: ❓ Why is this needed? We already have the following block which is intended to catch exactly this case. For example, no special casing is needed for `IFormattable f = $"";`.

https://github.com/dotnet/roslyn/blob/4b1c677e0161df22f12073a1493747532152b115/src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs#L180-L184

File: src/EditorFeatures/CSharpTest/Diagnostics/UseImplicitOrExplicitType/UseImplicitTypeTests.cs [hunk 5]
```diff
@@ -1749,5 +1749,86 @@ static void M()
...
+        [WorkItem(22768, "https://github.com/dotnet/roslyn/issues/22768")]
+        public async Task DoNotSuggestVarOnStackAllocExpressions_PointerType()
+        {
+            await TestMissingInRegularAndScriptAsync(
+@"using System;
+class C
+{
+    unsafe static void M()
+    {
+        [|int*|] x = stackalloc int [10];
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/Diagnostics/UseImplicitOrExplicitType/UseImplicitTypeTests.cs]: ❗️ For the `ImplicitTypeEverywhere()` options, this should report a diagnostic. `Span<T>` is not a special case, the same way string interpolation is not a special case.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs (hunk 1 above)
Comment (OmarTawfik) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs]: Such syntax is disabled. Please check #22046

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs]: You can't have a stackalloc inside lambda on the RHS?

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs (hunk 3 above)
Comment (OmarTawfik) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs]: @sharwell can you please explain? the IDE should never suggest that particular pattern in that case.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs (hunk 4 above)
Comment (OmarTawfik) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs]: Because in cases where compiler can bind the node successfully without errors, it will be replaced with a `BoundConvertedStackAllocExpression`. That's what the semantic model will return.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs (hunk 1 above)
Comment (OmarTawfik) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs]: I'll test that as well.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs [hunk 6]
```diff
@@ -109,16 +109,20 @@ protected override bool TryAnalyzeVariableDeclaration(TypeSyntax typeName, Seman
...
-                // Discourage using "var pointer = stackalloc", after introducing C# 7.2, as it might be confusing to users expecting a Span<>
-                // Check descendant nodes as well, because Span-creating stackallocs can be nested in other nodes (like conditional operators and casts).
-                // https://github.com/dotnet/roslyn/issues/22768
-                if (initializer.DescendantNodesAndSelf().Any(node => node.IsKind(SyntaxKind.StackAllocArrayCreationExpression)))
+                // Do not suggest var replacement for stackalloc span expressions.
+                // This will change the bound type from a span to a pointer.
+                if (!variableDeclaration.Type.IsKind(SyntaxKind.PointerType)
+                    && initializer
+                        .DescendantNodesAndSelf(descendIntoChildren: node => !node.IsAnyLambdaOrAnonymousMethod())
+                        .Any(node => node.IsKind(SyntaxKind.StackAllocArrayCreationExpression)))
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs]: FWIW, i would prefer really long expressions like this get broken out into either a helper method, or into statements.  i.e.:

```C#
var isPointerType = ...
var containsStackAlloc = ...

if (!isPointerType && containsStackAlloc) { ...
```

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs]: It's just much more readable to me that way (IMO).

**Comment by OmarTawfik** [comment]
@sharwell any other comments?

**Comment by OmarTawfik** [comment]
@sharwell can you please take a look?

**Comment by jinujoseph** [comment]
@OmarTawfik , submitting this for shiproom barcheck...can you fill in the ask mode template .
Once approved you are re-target this to master branch.
Thanks for taking care of this

**Comment by OmarTawfik** [comment]
@jinujoseph filled the questions in the VSO bug. Please let me know if I should do anything else.

**Comment by sharwell** [comment]
@OmarTawfik this will need to be rebased so we can target master.

**Comment by OmarTawfik** [comment]
@sharwell it is not going to be a pretty/straightforward rebase :(
I'll move these changes to another PR against `master` if it gets approved for `15.5`.

**Comment by sharwell** [comment]
@OmarTawfik I went ahead and did the rebase and changed the base branch of this PR to **master**. This will allow the tests to complete for the correct target so we're ready if approval comes through. 👍

**Comment by jinujoseph** [comment]
Pre-approved to merge via [link](https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_workitems/edit/517749)
