### PR TITLE
Code Model: GetTypeSymbolFromFullName should not return unpredictable results when the type name was in an unsupported format

### LINKED ISSUE #7179: Code Model: Stack overflow in CodeModel.MetadataNameHelpers.AppendNamedType
**Repro Steps**:

1. Create a WinForms application and Save All.
2. Add service reference to http://services.odata.org/OData/OData.svc.
3. Open data source window.
4. Drag table 'Advertisements' to designer.
5. Drag table 'Categories' to designer. (Note: You must drop the second table to repro)

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes #7179 

Tagging @dotnet/roslyn-ide

### CODE REVIEW

**Comment by DustinCampbell** [comment]
test vsi please

File: src/VisualStudio/Core/Test/CodeModel/CSharp/RootCodeModelTests.vb [hunk 1]
```diff
@@ -50,6 +50,23 @@ namespace N
...
+                    Dim dotNetName = rootCodeModel.DotNetNameFromLanguageSpecific("System.Collections.Generic.List<int>")
+                    Assert.Equal("System.Collections.Generic.List`1[System.Int32]", dotNetName)
+                End Sub)
+        End Function
+
+        <ConditionalWpfFact(GetType(x86)), Trait(Traits.Feature, Traits.Features.CodeModel)>
+        Public Async Function TestDotNetNameFromLanguageSpecificWithAssemblyQualifiedName() As Task
+            Await TestRootCodeModelWithCodeFile(<code></code>,
+                Sub(rootCodeModel)
+                    Assert.Throws(Of ArgumentException)(Sub() rootCodeModel.DotNetNameFromLanguageSpecific("System.Collections.Generic.List<int>, mscorlib"))
```
Comment (Pilchie) [inline src/VisualStudio/Core/Test/CodeModel/CSharp/RootCodeModelTests.vb]: Just for completeness, it might be worth using a name with a comma in the type parameter list, as well, since that might otherwise be valid.

Comment (DustinCampbell) [inline src/VisualStudio/Core/Test/CodeModel/CSharp/RootCodeModelTests.vb]: Great feedback -- will do!

**Comment by Pilchie** [comment]
:+1:

**Comment by DustinCampbell** [comment]
test vsi please

**Comment by DustinCampbell** [comment]
retest prtest/win/vsi/p1 please

File: src/VisualStudio/Core/Impl/CodeModel/MetadataNameHelpers.cs [hunk 2]
```diff
@@ -59,6 +60,11 @@ private static void AppendPointerType(IPointerTypeSymbol symbol, StringBuilder b
 
         public static string GetMetadataName(ITypeSymbol typeSymbol)
         {
+            if (typeSymbol.Kind == SymbolKind.TypeParameter)
+            {
+                throw new ArgumentException("Type parameters are not suppported", nameof(typeSymbol));
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Impl/CodeModel/MetadataNameHelpers.cs]: Does this need to be localized? I have no idea.

Comment (DustinCampbell) [inline src/VisualStudio/Core/Impl/CodeModel/MetadataNameHelpers.cs]: I don't think so. It's an internal API.
