### PR TITLE
Fix incorrect isInsideDelimiters assumption in MoveCaretToSemicolonPosition

### LINKED ISSUE #70224: Annoying completion when trying to insert a semi-colon in a switch expression
I'm trying to type `;` before the `switch` keyword, but VS won't let me:
annoying-cursor

### PR DESCRIPTION
**Pull request by sharwell**
Review commit-by-commit recommended. The fix for #70224 is the first commit, and the second commit is minor code cleanup.

Fixes #70224

### CODE REVIEW

File: src/EditorFeatures/CSharp/CompleteStatement/CompleteStatementCommandHandler.cs [hunk 1]
```diff
@@ -208,12 +195,16 @@ SyntaxKind.TupleExpression or
...
+                // We know the current node has delimiters due to the Kind() check above, so isInsideDelimiters is
+                // simply the inverse of being outside the delimiters.
+                isInsideDelimiters = !HasDelimitersButCaretIsOutside(currentNode, caret.Position);
+
                 var newCaret = args.SubjectBuffer.CurrentSnapshot.GetPoint(newCaretPosition);
                 if (!TryGetStartingNode(root, newCaret, out currentNode, cancellationToken))
                     return false;
 
                 return MoveCaretToSemicolonPosition(
-                    speculative, args, document, root, originalCaret, newCaret, syntaxFacts, currentNode, isInsideDelimiters: true, cancellationToken);
```
Comment (sharwell) [inline src/EditorFeatures/CSharp/CompleteStatement/CompleteStatementCommandHandler.cs:216]: 📝 The root cause of the bug is assuming `isInsideDelimiters` was true here. Normally it was true due to the way `TryGetStartingNode` skips nodes where we are outside delimiters, but `MoveCaretToSemicolonPosition` is called recursively which allowed us to violate this expectation.

File: src/EditorFeatures/CSharp/CompleteStatement/CompleteStatementCommandHandler.cs [hunk 2]
```diff
@@ -463,5 +454,25 @@ private static bool RequiredDelimiterIsMissing(SyntaxNode currentNode)
                 currentNode.GetParentheses().closeParen.IsMissing ||
                 currentNode.GetBraces().closeBrace.IsMissing;
         }
+
+        private static bool HasDelimitersButCaretIsOutside(SyntaxNode currentNode, int caretPosition)
+        {
+            if (currentNode.GetParentheses() is ((not SyntaxKind.None) openParenthesis, (not SyntaxKind.None) closeParenthesis))
```
Comment (sharwell) [inline src/EditorFeatures/CSharp/CompleteStatement/CompleteStatementCommandHandler.cs:460]: 📝 This syntax allows us to use the `Deconstruct` extension for `SyntaxToken` and check directly against `SyntaxKind`. However, I wasn't able to find a syntax which allowed us to _both_ deconstruct the tuple elements _and_ reuse the target variable. For example, I could not do this:

```cs
private static bool HasDelimitersButCaretIsOutside(SyntaxNode currentNode, int caretPosition)
{
    if (currentNode.GetParentheses() is ((not SyntaxKind.None) openDelimiter, (not SyntaxKind.None) closeDelimiter)
        || currentNode.GetBrackets() is ((not SyntaxKind.None) openDelimiter, (not SyntaxKind.None) closeDelimiter)
        || currentNode.GetBraces() is ((not SyntaxKind.None) openDelimiter, (not SyntaxKind.None) closeDelimiter))
    {
        return openDelimiter.SpanStart >= caretPosition || closeDelimiter.Span.End <= caretPosition;
    }
    else
    {
        return false;
    }
}
```

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharp/CompleteStatement/CompleteStatementCommandHandler.cs:460]: i don't love it, but i can't think of anything better :)

**Review by CyrusNajmabadi — APPROVED** [review]
