### PR TITLE
Disambiguate extension methods in "ambiguous call" error message when they have the same name but are from different assemblies

### LINKED ISSUE #80300: Include the assembly name when ambiguous methods are otherwise the same
**Version Used**: 
10.0.0-rc.1.25451.107

**Steps to Reproduce**:

With .NET 10, a lot of `IAsyncEnumerable` extension methods have been introduced in the BCL. These were taken from the `System.Linq.Async` package. There's also a `System.Linq.AsyncEnumerable` compatibility nuget.

All these assemblies contain extension methods
- with the same name
- contained in the same class name
- contained in the same namespace name

If you have a broken combination of any two (or three) of the above assemblies in your dependency, you get errors like
`error CS0121: The call is ambiguous between the following methods or properties: 'System.Linq.AsyncEnumerable.ToListAsync<TSource>(System.Collections.Generic.IAsyncEnumerable<TSource>, System.Threading.CancellationToken)' and 'System.Linq.AsyncEnumerable.ToListAsync<TSource>(System.Collections.Generic.IAsyncEnumerable<TSource>, System.Threading.CancellationToken)'`.

These make it pretty hard to identify which assemblies are actually involved.

**Expected Behavior**:

In cases where methods have fully identical string representations in the error message, it would be great to have the containing assembly as the final disambiguator as well.

### PR DESCRIPTION
**Pull request by jjonescz**
Fixes #80300.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs [hunk 1]
```diff
@@ -25162,11 +25162,10 @@ public static void M() { }
 interface I2 : I<int>, I<string> { }
 """;
         var comp = CreateCompilation(src, targetFramework: TargetFramework.Net70);
-        // Tracked by https://github.com/dotnet/roslyn/issues/78830 : diagnostic quality, consider improving the symbols in this error message
         comp.VerifyEmitDiagnostics(
-            // (1,4): error CS0121: The call is ambiguous between the following methods or properties: 'I<T>.M()' and 'I<T>.M()'
+            // (1,4): error CS0121: The call is ambiguous between the following methods or properties: 'I<int>.M()' and 'I<string>.M()'
```
Comment (jjonescz) [inline src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs:25166]: The second commit is to make this test work. Otherwise, an assert inside SymbolDistinguisher would fail because both symbols would be the same symbol. Furthermore, the change in the second commit also improves the diagnostic as suggested by the comment in this test ("consider improving the symbols in this error message").

**Comment by AlekseyTs** [comment]
@jjonescz Would it be possible to add more details into the title? #Closed

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs [hunk 2]
```diff
@@ -1414,8 +1414,8 @@ private bool HadAmbiguousWorseMethods(BindingDiagnosticBag diagnostics, Immutabl
                 // error CS0121: The call is ambiguous between the following methods or properties: 'P.W(A)' and 'P.W(B)'
                 diagnostics.Add(
                     CreateAmbiguousCallDiagnosticInfo(
-                        worseResult1.LeastOverriddenMember.OriginalDefinition,
-                        worseResult2.LeastOverriddenMember.OriginalDefinition,
+                        worseResult1.LeastOverriddenMember,
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs]: >worseResult1.LeastOverriddenMember, [](http://example.com/codeflow?start=24&length=35)

Could you point to test(s) demonstrating this change in behavior? #Closed

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs]: Also, it looks like there is another call site that wasn't adjusted.

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs [hunk 3]
```diff
@@ -1506,18 +1506,8 @@ private int TryGetFirstTwoValidResults(out MemberResolutionResult<TMember> first
...
-                            new FormattedSymbol(first, SymbolDisplayFormat.CSharpErrorMessageFormat),
-                            new FormattedSymbol(second, SymbolDisplayFormat.CSharpErrorMessageFormat)
-                    } :
-                new object[]
-                    {
-                            first,
-                            second
-                    };
-            return new DiagnosticInfoWithSymbols(ErrorCode.ERR_AmbigCall, arguments, symbols);
+            var distinguisher = new SymbolDistinguisher(compilation: null, first, second);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs]: >compilation: null [](http://example.com/codeflow?start=56&length=17)

If compilation going to improve the experience why don't we pass it? It feels like there should be a compilation around. #Closed

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs [hunk 4]
```diff
@@ -26193,9 +26193,9 @@ public static void M1<T, U>(((T, int), int, int, int, int, int, int, int, int, i
         { Console.Write(4); }
 }";
             CreateCompilation(source).VerifyDiagnostics(
-                // (7,9): error CS0121: The call is ambiguous between the following methods or properties: 'C.M1<T, U>((T, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, (U, int)))' and 'C.M1<T, U>(((T, int), int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, U))'
+                // (7,9): error CS0121: The call is ambiguous between the following methods or properties: 'C.M1<(int, int), int>(((int, int), int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, (int, int)))' and 'C.M1<int, (int, int)>(((int, int), int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, (int, int)))'
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: >(int, int), int> [](http://example.com/codeflow?start=113&length=16)

It feels like this change is outside of scope of this PR, and doesn't look like a big improvement to me.   #Closed

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs]: If this change is about improvement for scenario in ```AmbiguousCallOnInterface```, I suggest to address that issue in a separate PR, and use ```ConstructedFrom``` instead of ```OriginalDefinition```

File: src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs [hunk 5]
```diff
@@ -1177,30 +1177,27 @@ public static void Main(string[] args)
 }
 ";
             CreateCompilationWithILAndMscorlib40(csharp, il).VerifyDiagnostics(
-                // CONSIDER: Dev10 reports CS1957, even though the runtime has no trouble distinguishing the potentially
-                // overridden methods.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs:1181]: Why is this comment removed? #Closed

**Comment by AlekseyTs** [comment]
Done with review pass (commit 3) #Closed

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs (hunk 2 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs]: > If this change is about improvement for scenario in `AmbiguousCallOnInterface`, I suggest to address that issue in a separate PR, and use `ConstructedFrom` instead of `OriginalDefinition`

That's a good idea, thanks, I will do that.

File: src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs (hunk 5 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs:1181]: Good catch, thanks, that was a mistake.

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs (hunk 2 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs]: > Could you point to test(s) demonstrating this change in behavior?

Originally, tests changed in the second commit corresponded to the change. After changing to `ConstructedFrom` in commit 5, exactly the tests changed in that same commit (5) will correspond to the change.

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs [hunk 6]
```diff
@@ -1467,8 +1468,9 @@ private bool HadAmbiguousBestMethods(BindingDiagnosticBag diagnostics, Immutable
             // 'P.Ambiguous(object, string)' and 'P.Ambiguous(string, object)'
             diagnostics.Add(
                 CreateAmbiguousCallDiagnosticInfo(
-                    validResult1.LeastOverriddenMember.OriginalDefinition,
-                    validResult2.LeastOverriddenMember.OriginalDefinition,
+                    compilation,
+                    validResult1.LeastOverriddenMember.ConstructedFrom(),
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs:1474]: >.ConstructedFrom() [](http://example.com/codeflow?start=54&length=18)

Is this change observable in tests?

File: src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs [hunk 7]
```diff
@@ -1180,27 +1180,27 @@ public static void Main(string[] args)
...
                 // overridden methods.
 
-                // (6,26): error CS0462: The inherited members 'CG<T>.F(T)' and 'CG<T>.F(T)' have the same signature in type 'EG<T>', so they cannot be overridden
-                //     public override void F(T c)
-                Diagnostic(ErrorCode.ERR_AmbigOverride, "F").WithArguments("CG<T>.F(T)", "CG<T>.F(T)", "EG<T>"),
                 // (15,26): error CS0462: The inherited members 'CG<T>.F(T)' and 'CG<T>.F(T)' have the same signature in type 'EGI', so they cannot be overridden
                 //     public override void F(int c)
-                Diagnostic(ErrorCode.ERR_AmbigOverride, "F").WithArguments("CG<T>.F(T)", "CG<T>.F(T)", "EGI"),
+                Diagnostic(ErrorCode.ERR_AmbigOverride, "F").WithArguments("CG<T>.F(T)", "CG<T>.F(T)", "EGI").WithLocation(15, 26),
+                // (6,26): error CS0462: The inherited members 'CG<T>.F(T)' and 'CG<T>.F(T)' have the same signature in type 'EG<T>', so they cannot be overridden
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs:1183]: >// (6,26): error CS0462: The inherited members 'CG<T>.F(T)' and 'CG<T>.F(T)' have the same signature in type 'EG<T>', so they cannot be overridden [](http://example.com/codeflow?start=16&length=146)

Consider placing this error to its original position in the list to make the diff more informative. #Closed

File: src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs [hunk 8]
```diff
@@ -7913,18 +7913,18 @@ public static void Main()
 }";
 
             CreateCompilation(source).VerifyDiagnostics(
-// (20,27): warning CS0473: Explicit interface implementation 'Explicit.I1<int, int>.Method<V>(int, System.Func<int, int, V>, int)' matches more than one interface member. Which interface member is actually chosen is implementation-dependent. Consider using a non-explicit implementation instead.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs:7916]: >System [](http://example.com/codeflow?start=100&length=6)

This change looks unexpected, it looks like the warning argument did not change. #Closed

File: src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs [hunk 9]
```diff
@@ -8010,15 +8010,15 @@ public static void Main()
 }";
 
             CreateCompilation(source).VerifyDiagnostics(
-// (25,16): warning CS0108: 'ImplicitInBase.Method(int, System.Func<int, int>, params int[])' hides inherited member 'Base.Method(int, System.Func<int, int>, int[])'. Use the new keyword if hiding was intended.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs:8013]: Changes on this line look unexpected and do not match the actual warning arguments #Closed

**Comment by AlekseyTs** [comment]
Done with review pass (commit 6) #Closed

File: src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs (hunk 8 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs:7916]: That's what I'm getting from the test helper though. `WithArguments` and the message text is not consistent in general (I've seen those differ many times before). It seems that's because `diagnostic.ToString` (which is used for the comment) uses `CSharpShortErrorMessageFormat` for its symbol arguments. Whereas the test formatter of `WithArguments` just uses `ToString` on the arguments.

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs (hunk 6 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs:1474]: No, it seems this is not observable.

Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs:1474]: It seems this code path does not currently have any test coverage. I added `Debug.Fail()` there and no tests failed: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1160587&view=results

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs:1474]: > It seems this code path does not currently have any test coverage. 

Could you try adding a test?

File: src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs (hunk 8 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs:7916]: > That's what I'm getting from the test helper though

The comment is not a baseline, corresponding `Diagnostic` object is the baseline. I suggest revering the change in the comment since the only change in the `Diagnostic`  is location.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 7) #Closed

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs (hunk 6 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs:1474]: This would be reached if there were two `MemberResolutionResult`s which are both valid (applicable). But as far as I can see, if we ever have two `MemberResolutionResult`s which are valid, `OverloadResolution.RemoveWorseMembers` marks them as invalid (worse; not-applicable). So I think this might be unreachable, although I might be missing some overload resolution subtlety. Should I add an assert, assuming this is unreachable, so if we do reach this in the future, the assert will tell us to add tests?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs:1474]: > Should I add an assert, assuming this is unreachable, so if we do reach this in the future, the assert will tell us to add tests?


Let's do this and let's open an issue to close the test gap and reference it in a comment.

**Comment by AlekseyTs** [comment]
#80457 should fix the test that is currently broken in main

**Comment by jjonescz** [comment]
@dotnet/roslyn-compiler for a second review, thanks
