### PR TITLE
Key container signing fix

### LINKED ISSUE #25340: Strong Name signing with a key installed in a container
After upgrading to respectively installing Visual Studio 2017 Version 15.6 no assemblies will be signed with a strong name.

We are using the AssemblyKeyName Attribute in AssemblyInfo.cs.

Using a KeyFile instead (created from the projects properties) will work.

Am I missing something?

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/209811/strong-name-signing-with-a-key-installed-in-a-cont.html
VSTS ticketId: 578075_
_These are the original issue comments:_

Matthew Dodds on 3/7/2018, 10:24 AM (12 hours ago): <p>I am also having this problem with using AssemblyKeyName, which is showing up as two different issues. I am using C#, ASP.NET, .NET 4.7.1. Both of these issues were fixed once I reverted to Visual Studio 15.5.7. I also confirmed that using AssemblyKeyFile referencing a .snk instead of using AssemblyKeyName fixed both issues.</p><p>First: </p><p>Attempting to load the program in IIS results in the exception: "Could not load file or assembly '[redacted], Culture=neutral, PublicKeyToken=928c297f0d8e5e72' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference." </p><p>Fusion log contained: "Comparing the assembly name resulted in the mismatch: PUBLIC KEY TOKEN" </p><p><br></p><p>
Second:</p><p>
Building of a solution that references some of our C# libraries built outside of the solution will result in: "Error CS8002: Referenced assembly '[redacted], Version=6.3.0.144, Culture=neutral, PublicKeyToken=null' does not have a strong name." </p><p>Building this solution a second time will result it successfully building, but will always fail if telling Visual Studio to rebuild. </p><p><br></p>

_These are the original issue solutions:_
(no solutions)

### PR DESCRIPTION
**Pull request by agocke**
### Customer scenario(s)

There are two signing bugs. In the first, the compiler fails to sign an assembly if signing is specific using the AssemblyKeyContainer attribute and nothing else. Specifically, if key signing is requested using a key file or using a key container but provided through command line or MSBuild option, signing succeeds. In the second, the `-delaysign` option will fully sign an assembly if provided a key file that contains both a public and private key.

### Bugs this fixes

#25340
#25424 

Tracking bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/580955

### Workarounds, if any

There are three possible workarounds for the key container bug for 15.6:

1. You can switch to using a keyfile instead of a key container.
2. You can enable a fallback mode by putting the following in your MSBuild project files
```
<Features>$(Features);UseLegacyStrongNameProvider</Features>
```
3. You can move the name of the key container from the AssemblyAttributes C# file to your project file(s) by adding the following property: 
```
<KeyContainerName>the-name-of-your-key-here</KeyContainerName>
```

For the delaysign bug, you can use the UseLegacyStrongNameProvider flag on Windows, or you can create a key file that contains only the public key, with no private key.

### Risk

This change mostly moves us back to using the old signing behavior. The only change not related is the fix for delaysign on CoreCLR, which is a targeted fix to prevent us from full-signing when it was not requested. This change has been validated by unit tests.

### Performance impact

Almost none -- an additional null check in the working case and only a handful of allocations.

### Is this a regression from a previous update?

This is a regression, but not from another update. Key container signing using attributes previously worked.

### Root cause analysis

The tests only tried to test key containers with the desktop strong name provider, assuming that only a desktop strong name provider would be provided if we require key container signing. This is incorrect. This change moves us back to the old signing code, which has proper tests for these scenarios. For the delaysign fix, appropriate tests have been added for the CoreCLR code.

### How was the bug found?

Customer reported.

### CODE REVIEW

**Comment by jcouv** [comment]
>         private void DelaySignWithAssemblySignatureKeyHelper(StrongNameProvider provider)

Consider making this a local function, since used by a single test

---
Refers to: src/Compilers/CSharp/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.cs:1594 in e1a84e2. [](commit_id = e1a84e2cb4ad5b85f4d36c32a9c62f6ac44636b7, deletion_comment = False)

File: src/Compilers/CSharp/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.cs [hunk 1]
```diff
@@ -1630,18 +1622,14 @@ public class C
                 var header = metadata.Module.PEReaderOpt.PEHeaders.CorHeader;
                 //confirm header has expected SN signature size
                 Assert.Equal(256, header.StrongNameSignatureDirectory.Size);
+                Assert.Equal(CorFlags.ILOnly, header.Flags);
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.cs]: Consider adding a comment ("although a private key was provided, the assembly is still not signed" or something)
