### PR TITLE
Only use conditional expression conversion when no common type

### LINKED ISSUE #49598: There seems to be some errors in this target-typed conditional expression
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/There-seems-to-be-some-errors-in-this-ta/1260582?preview=true)._

---
[regression] [worked-in:16.8.1]
! [image.png] (https://aka.ms/dc/image?name=B0a4a46ea7d464f0096e4ecec621df50c637413446758633028_20201119-100435-image.png&tid=0a4a46ea7d464f0096e4ecec621df50c637413446758633028)

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            short? a = 1;

var b = true;

var c1 = a ?? (b ? 4: 1);

var c2 = a ?? (true ? 4 : 1);

var c3 = a ?? (false ? 4 : 1);
        }
    }
}
```

---
#### Feedback Bot on 11/18/2020, 10:17 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by cston**
Target-typed conditional expression conversion should only be used when there is no common type between the sub-expressions - see [conditional-expression-conversion](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-9.0/target-typed-conditional-expression.md#conditional-expression-conversion).

For example, in the following methods, `b ? 1 : 2` should be treated as an expression of type `int` rather than treated as target-typed because `1` and `2` have a common type. (The comments include the behavior in 16.8 compiling with `-langversion:8` and `-langversion:9` and the expected behavior for both matching 16.7.)

```C#
static short F1(bool b)
{
    // -langversion:8: CS8400: 'target-typed conditional expression' is not available
    // -langversion:9: ok
    //       expected: CS0266: cannot convert type 'int' to 'short'.
    return b ? 1 : 2;
}

static object F2(bool b, short? a)
{
    // -langversion:8: CS8400: 'target-typed conditional expression' is not available
    // -langversion:9: short
    //       expected: int
    return a ?? (b ? 1 : 2);
}
```

Fixes #49598

### CODE REVIEW

**Comment by AlekseyTs** [comment]
> expected: int

I am not sure what this exactly means. Could you please elaborate?

**Comment by cston** [comment]
> > expected: int
>
> I am not sure what this exactly means. Could you please elaborate?

The type of the expression `a ?? (b ? 1 : 2)` should be `System.Int32`, rather than `System.Int16`.

File: src/Compilers/CSharp/Test/Semantic/Semantics/TargetTypedConditionalOperatorTests.cs [hunk 1]
```diff
@@ -451,5 +453,200 @@ public static void Test(bool b, IDisposable d)
...
+                // (15,16): error CS0029: Cannot implicitly convert type 'A' to 'B'
+                //         return (b ? a : 0) + a;
+                Diagnostic(ErrorCode.ERR_NoImplicitConv, "(b ? a : 0) + a").WithArguments("A", "B").WithLocation(15, 16),
+                // (15,17): error CS8370: Feature 'target-typed conditional expression' is not available in C# 7.3. Please use language version 9.0 or greater.
+                //         return (b ? a : 0) + a;
+                Diagnostic(ErrorCode.ERR_FeatureNotAvailableInVersion7_3, "b ? a : 0").WithArguments("target-typed conditional expression", "9.0").WithLocation(15, 17));
+            CreateCompilation(source, parseOptions: TestOptions.Regular.WithLanguageVersion(MessageID.IDS_FeatureTargetTypedConditional.RequiredVersion())).VerifyDiagnostics(
+                // (15,16): error CS0029: Cannot implicitly convert type 'A' to 'B'
+                //         return (b ? a : 0) + a;
+                Diagnostic(ErrorCode.ERR_NoImplicitConv, "(b ? a : 0) + a").WithArguments("A", "B").WithLocation(15, 16));
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/TargetTypedConditionalOperatorTests.cs:649]: The behavior of this test is unchanged from 16.7 or 16.8.

**Comment by cston** [comment]
@dotnet/roslyn-compiler, please review.

File: src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs [hunk 2]
```diff
@@ -3917,23 +3917,53 @@ private BoundExpression BindConditionalOperator(ConditionalExpressionSyntax node
...
+            }
+
+            if (!hasErrors)
+            {
+                constantValue = FoldConditionalOperator(condition, trueExpr, falseExpr);
+                hasErrors = constantValue != null && constantValue.IsBad;
+            }
+
+            trueExpr = BindToNaturalType(trueExpr, diagnostics, reportNoTargetType: false);
+            falseExpr = BindToNaturalType(falseExpr, diagnostics, reportNoTargetType: false);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs:3963]: It feels like we need to do this only for the error type case above. Consider moving these two statements into the ```if```.

File: src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs [hunk 3]
```diff
@@ -3917,23 +3917,53 @@ private BoundExpression BindConditionalOperator(ConditionalExpressionSyntax node
...
+            return new BoundConditionalOperator(node, isRef: false, condition, trueExpr, falseExpr, constantValue, naturalTypeOpt: null, wasTargetTyped: false, type, hasErrors);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs:3964]: >null [](start = 131, length = 4)

Should we pass type here? What is this going to affect, SemanticModel?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs:3964]: I think we should add tests for GetTypeInfo.

---
In reply to: [567153678](https://github.com/dotnet/roslyn/pull/50755#discussion_r567153678) [](ancestors = 567153678)

**Comment by AlekseyTs** [comment]
Done with review pass (commit 2)

File: src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs (hunk 3 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs]: > Should we pass type here? What is this going to affect, SemanticModel?

I don't know of any callers that will be affected, but it seems reasonable to pass `type`.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 4)

File: src/Compilers/CSharp/Test/Semantic/Semantics/ConstantTests.cs [hunk 4]
```diff
@@ -2360,8 +2360,7 @@ void M()
             // Duplicate "(byte)2" is because there's an implicit conversion to uint.
             // Duplicate "b ? (uint)1 : (byte)2" is because there's an implicit conversion to int.
             var expected =
-@"true ? 1 + i : (int)4u --> BAD
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ConstantTests.cs:2363]: >"true ? 1 + i : (int)4u --> BAD [](start = 1, length = 31)

Why do we want this behavior change? All the parts are constants, so I'd expect the expression to still have a (bad) constant value.

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 4)

File: src/Compilers/CSharp/Test/Semantic/Semantics/ConstantTests.cs (hunk 4 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/ConstantTests.cs:2363]: > Why do we want this behavior change?

The previous behavior (copying the ConstantValue from one of the branches of the conditional operator when the condition is a constant and the branch is ConstantValue.Bad) was an artifact of an earlier optimization when the branches were identical types (see [Binder_Operators.cs](https://github.com/dotnet/roslyn/blob/27ede702ea49770fcb551e3d2e571dc51ff4b319/src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs#L3752)). If the branches were not identical, the constant value was not copied.

That meant the constant value was set on the first `?:` expression below but not the second. Since the behavior was inconsistent between the two cases, the optimization for identical types did not seem necessary.
```
const int i = i;
const int z = true ? 1 + i : (int)4u;
const int y = true ? 1 + i : 4u;
```

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 4)

**Comment by am11** [comment]
Could the values within target-type's limit be allowed?
```c#
// current behavior (which synthetically makes sense)

// no error
static byte B1(bool b) => b ? byte.MinValue : byte.MaxValue;
static short S1(bool b) => b ? short.MinValue : short.MaxValue;

// error CS0029
static byte B2(bool b) => b ? byte.MinValue - 1 : byte.MaxValue; // or both operands out of bounds
static short S2(bool b) => b ? short.MinValue - 1 : short.MaxValue;
```

**Comment by cston** [comment]
@am11

> Could the values within target-type's limit be allowed?

The cases `B1()` and `S1()` compile successfully with this change.

**Comment by MaxHayman** [comment]
As there was no way to express a ushort literal it was great when this was introduced. Meant a lot of code could look cleaner.

**Comment by binki** [comment]
Yeah, like @MaxHayman, I am being forced to add some `MyExtensions.StaticCast<ushort>(0)` into code which wasn’t needed in 16.8.
