### PR TITLE
Fix and re-enable portable signing

### LINKED ISSUE #23521: Full signing is broken using csc.exe in 15.6.x
Repro:

1. Use `sn.exe` to create a keyfile by calling `sn.exe -k test.snk`.
2. Compile hello world with signing using `csc.exe -keyfile:test.snk hello.cs`.
3. Run `sn.exe -vf hello.exe` to verify that the output is signed.

Expected:
```
Assembly 'hello.exe' is valid
```

Actual:
```
Failed to verify assembly -- Strong name validation failed.
````

### PR DESCRIPTION
**Pull request by agocke**
### Customer scenario

Re-enable portable signing, allowing binaries to be signed on Mac & Linux.

There were two separate bugs here:
    
1. Fixing up the MVID of the binary was being done *after* signing,
    when it should be done before.

2. System.Reflection.Metadata has a bug where calculating the
    checksum occurs before signing, when it should happen after.

Both of these isues have been fixed and the helper utility that checks
to see whether a binary was signed has been changed to verify that the
signature and checksums of the binaries are valid, not just that the
signed bit is set on the assembly.

### Bugs this fixes

Fixes #23521

### Workarounds, if any

None. Binaries cannot be strongname signed on Mac or Linux without this change.

### Risk

This change is isolated to signing.

### Performance impact

None. Portable signing is likely faster since it allows PE streams to be signed without
copying to a temporary file.

### Is this a regression from a previous update?

No.

### Root cause analysis

The primary helper used by the signing tests, IsStreamSigned, only checked to see
if the sign bit was set, not that the signature was valid. This helper has been modified
to use the verification used by System.Reflection.Metadata for its tests as well. That
helper includes a test that verifies a large number of core framework types (mscorlib, et al)
and thus is very likely to produce the same verification as the CLR itself.

### How was the bug found?

Toolset insertion into Visual Studio, which verified the strong name signatures after signing.

### CODE REVIEW

File: src/Compilers/Core/Portable/PEWriter/PeWriter.cs [hunk 1]
```diff
@@ -242,6 +250,30 @@ internal static class PeWriter
...
             return true;
+
+            Blob getChecksumBlob(PEBuilder builder)
+                => (Blob)typeof(PEBuilder).GetRuntimeFields()
+                    .Where(f => f.Name == "_lazyChecksum")
+                    .Single()
+                    .GetValue(builder);
+        }
+
+        private static MethodInfo _calculateChecksumMethod;
```
Comment (tmat) [inline src/Compilers/Core/Portable/PEWriter/PeWriter.cs]: I think we can correct the checksum without using reflection. Calculating the offset of the checksum in the PE file should be easy. Then we can copy the [checksum calculation implementation](http://source.dot.net/#System.Reflection.Metadata/System/Reflection/PortableExecutable/PEBuilder.cs,518) from SRM and:
1) build the full signed PE image as notmal
2) zero the checksum field
3) calculate the checksum 
4) write the checksum field

@agocke Wouldn't that work?

File: src/Compilers/CSharp/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.cs [hunk 2]
```diff
@@ -1137,10 +1142,131 @@ private static bool IsStreamSigned(Stream moduleContents)
...
+                    {
+                        return false;
+                    }
+                }
+
+                return true;
             }
         }
+
+        private static MethodInfo _peheaderSizeMethod;
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.cs]: The naming style for private static is `s_` not `_`

File: src/Compilers/Core/Portable/PEWriter/PeWriter.cs (hunk 1 above)
Comment (agocke) [reply src/Compilers/Core/Portable/PEWriter/PeWriter.cs]: Hashing 0-bytes is not a no-op. It's not good enough to zero the signature, you actually have to skip it.

Comment (tmat) [reply src/Compilers/Core/Portable/PEWriter/PeWriter.cs]: The signature is already calculated with the checksum zeroed (see the impl in SRM).

Comment (agocke) [reply src/Compilers/Core/Portable/PEWriter/PeWriter.cs]: Sorry, I wrote signature but I meant checksum. If I copied the code I would need to find the offset of the checksum field and exclude it from hashing. The APIs to do that are private, as far as I can tell. I could maybe get the raw byte array and then hard code the offset of the signature field, as well as copy over all the checksum code, but this doesn't seem better than using private reflection.

Comment (tmat) [reply src/Compilers/Core/Portable/PEWriter/PeWriter.cs]: The offset of the checksum field is a constant: http://source.dot.net/#System.Reflection.Metadata/System/Reflection/PortableExecutable/PEHeader.cs,252 for all PE files.

You can easily pass 2 blobs to the CalculateChecksum function: all content before that field and after that field.

Comment (agocke) [reply src/Compilers/Core/Portable/PEWriter/PeWriter.cs]: I don't think I can construct those blobs, because the constructor for a blob with an underlying buffer is internal.

Comment (tmat) [reply src/Compilers/Core/Portable/PEWriter/PeWriter.cs]: A blob is just an array segment.

**Comment by agocke** [comment]
ping @dotnet/roslyn-compiler for review

File: src/Compilers/Core/Portable/PEWriter/PeWriter.cs [hunk 3]
```diff
@@ -225,12 +226,19 @@ internal static class PeWriter
...
             if (privateKeyOpt != null)
             {
                 strongNameProvider.SignPeBuilder(peBuilder, peBlob, privateKeyOpt.Value);
-            }
 
-            PatchModuleVersionIds(mvidFixup, mvidSectionFixup, mvidStringFixup, peContentId.Guid);
+                // Checksum fixup, workaround for https://github.com/dotnet/corefx/issues/25829
+                // Since the checksum is calculated before signing in the PEBuilder,
+                // we need to redo the calculation and write in the correct checksum
+                var checksumBlob = getChecksumBlob(peBuilder);
```
Comment (jcouv) [inline src/Compilers/Core/Portable/PEWriter/PeWriter.cs]: Would be good to spell out types

File: src/Compilers/Core/Portable/PEWriter/SigningUtilities.cs [hunk 4]
```diff
@@ -27,11 +27,15 @@ internal static byte[] CalculateRsaSignature(IEnumerable<Blob> content, RSAParam
             }
         }
 
-        private static byte[] CalculateSha1(IEnumerable<Blob> content)
+        internal static byte[] CalculateSha1(IEnumerable<Blob> content)
         {
             using (var hash = IncrementalHash.CreateHash(HashAlgorithmName.SHA1))
             {
-                hash.AppendData(content);
```
Comment (jcouv) [inline src/Compilers/Core/Portable/PEWriter/SigningUtilities.cs]: I didn't understand this change. 
Was there an overload of `AppendData` that takes an `IEnumerable`? I can't find it on MSDN.
If yes, what was wrong with that method?

File: src/Compilers/CSharp/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.cs [hunk 5]
```diff
@@ -1129,18 +1129,10 @@ private static bool IsFileSigned(TempFile file)
             //TODO should check to see that the output was actually signed
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.cs]: Is this comment still applicable?

File: src/Test/Utilities/Portable/Metadata/ILValidation.cs [hunk 6]
```diff
@@ -3,16 +3,175 @@
...
+            using (var metadata = ModuleMetadata.CreateFromStream(moduleContents))
+            {
+                var metadataReader = metadata.MetadataReader;
+                var peReader = metadata.Module.PEReaderOpt;
+                var peHeaders = peReader.PEHeaders;
+                var flags = peHeaders.CorHeader.Flags;
+
+                bool is32bit = peHeaders.PEHeader.Magic == PEMagic.PE32;
+                const int SectionHeaderSize = 40;
+                int peHeadersSize = peHeaders.PEHeaderStartOffset
```
Comment (jcouv) [inline src/Test/Utilities/Portable/Metadata/ILValidation.cs]: Consider moving closer to usage.

File: src/Compilers/Core/Portable/Interop/IClrStrongName.cs [hunk 7]
```diff
@@ -132,10 +132,11 @@ internal interface IClrStrongName
             [In, MarshalAs(UnmanagedType.LPWStr)] string pwzFilePath,
             [In, MarshalAs(UnmanagedType.U4)] int dwInFlags);
 
-        [return: MarshalAs(UnmanagedType.I1)]
-        byte StrongNameSignatureVerificationEx(
+        [return: MarshalAs(UnmanagedType.Bool)]
+        bool StrongNameSignatureVerificationEx(
```
Comment (jcouv) [inline src/Compilers/Core/Portable/Interop/IClrStrongName.cs]: Would it be better to remove methods that we aren't using?

File: src/Test/Utilities/Portable/Metadata/ILValidation.cs [hunk 8]
```diff
@@ -3,16 +3,175 @@
...
+            int peHeadersSize,
+            int peHeaderAlignment,
+            Blob strongNameSignatureFixup)
+        {
+            if (s_getContentToSignMethod == null)
+            {
+                Interlocked.CompareExchange(
+                    ref s_getContentToSignMethod,
+                    typeof(PEBuilder).GetMethod(
+                        "GetContentToSign",
```
Comment (jcouv) [inline src/Test/Utilities/Portable/Metadata/ILValidation.cs]: Consider filing an issue to request this API be made public (or a PR to make it public ;-) ).

File: src/Test/Utilities/Portable/Metadata/ILValidation.cs [hunk 9]
```diff
@@ -3,16 +3,175 @@
...
+
+        private static FieldInfo s_bufferField;
+        private static byte[] GetBlobBuffer(Blob blob)
+        {
+            if (s_bufferField == null)
+            {
+                Interlocked.CompareExchange(
+                    ref s_bufferField,
+                    typeof(Blob).GetField(
+                        "Buffer",
```
Comment (jcouv) [inline src/Test/Utilities/Portable/Metadata/ILValidation.cs]: Ditto

File: src/Compilers/Core/Portable/CommandLine/CommonCommandLineArguments.cs [hunk 10]
```diff
@@ -284,10 +284,11 @@ public CompilationOptions CompilationOptions
...
         internal StrongNameProvider GetStrongNameProvider(StrongNameFileSystem fileSystem)
         {
-            // https://github.com/dotnet/roslyn/issues/23521
-            // Disable the portable strong name provider until we can find and fix the
-            // root cause of the bug
-            return new DesktopStrongNameProvider(KeyFileSearchPaths, null, fileSystem);
+            bool fallback = ParseOptionsCore.Features.ContainsKey("UseLegacyStrongNameProvider") ||
+                CompilationOptionsCore.CryptoKeyContainer != null;
+            return fallback ?
+                new DesktopStrongNameProvider(KeyFileSearchPaths, null, fileSystem) :
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/CommandLine/CommonCommandLineArguments.cs]: Can we pass null using a named argument? Not sure it's meaning here.

File: src/Compilers/Core/Portable/Interop/IClrStrongName.cs (hunk 7 above)
Comment (jaredpar) [reply src/Compilers/Core/Portable/Interop/IClrStrongName.cs]: Keeping unused methods is important when dealing with COM signatures. It sets up the vtable ordering.

File: src/Test/Utilities/Portable/Metadata/ILValidation.cs [hunk 11]
```diff
@@ -3,16 +3,175 @@
...
 using System.Xml;
+using Microsoft.Cci;
+using Microsoft.CodeAnalysis;
 using Microsoft.Metadata.Tools;
 
 namespace Roslyn.Test.Utilities
 {
     public static class ILValidation
     {
+        public static bool IsStreamSigned(Stream moduleContents)
```
Comment (jaredpar) [inline src/Test/Utilities/Portable/Metadata/ILValidation.cs]: What type of signing is this checking for: full, public, etc ... Please add a doc comment explaining.

File: src/Test/Utilities/Portable/Metadata/ILValidation.cs [hunk 12]
```diff
@@ -3,16 +3,175 @@
...
+                if (CorFlags.StrongNameSigned != (flags & CorFlags.StrongNameSigned))
+                {
+                    return false;
+                }
+
+                var snDirectory = peReader.PEHeaders.CorHeader.StrongNameSignatureDirectory;
+                int rva = snDirectory.RelativeVirtualAddress;
+                int size = snDirectory.Size;
+                var signature = peReader.GetSectionData(rva).GetContent(0, size);
+                if (!peHeaders.TryGetDirectoryOffset(snDirectory, out var snOffset))
```
Comment (jaredpar) [inline src/Test/Utilities/Portable/Metadata/ILValidation.cs]: Consider using type here instead of var. Type isn't obvious.

File: src/Test/Utilities/Portable/Metadata/ILValidation.cs [hunk 13]
```diff
@@ -3,16 +3,175 @@
...
+                {
+                    return false;
+                }
+
+                moduleContents.Position = 0;
+                int peSize = (int)moduleContents.Length;
```
Comment (jaredpar) [inline src/Test/Utilities/Portable/Metadata/ILValidation.cs]: Should we use `checked` here and return false if there is an overflow? Not sure about the semantics of this field hence not sure how to interpret overflow here as a reviewer.

File: src/Test/Utilities/Portable/Metadata/ILValidation.cs [hunk 14]
```diff
@@ -3,16 +3,175 @@
...
+                var hash = SigningUtilities.CalculateSha1(content);
+
+                var publicKey = CryptoBlobParser.ToRSAParameters(TestResources.General.snKey,
+                    includePrivateParameters: false);
+
+                using (var rsa = RSA.Create())
+                {
+                    rsa.ImportParameters(publicKey);
+                    var reversedSignature = signature.ToArray();
+                    Array.Reverse(reversedSignature);
```
Comment (jaredpar) [inline src/Test/Utilities/Portable/Metadata/ILValidation.cs]: Can you add a comment on why we do a Reverse here? Given how much of a surprise it was to us may help to comment for future readers.

File: src/Test/Utilities/Portable/Metadata/ILValidation.cs (hunk 8 above)
Comment (tmat) [reply src/Test/Utilities/Portable/Metadata/ILValidation.cs]: The PI is not gonna be made public. I'll fix the checksum calculation.

File: src/Test/Utilities/Portable/Metadata/ILValidation.cs (hunk 9 above)
Comment (tmat) [reply src/Test/Utilities/Portable/Metadata/ILValidation.cs]: Ditto :)

File: src/Test/Utilities/Portable/Metadata/ILValidation.cs (hunk 13 above)
Comment (agocke) [reply src/Test/Utilities/Portable/Metadata/ILValidation.cs]: I thought we had changed our defaults to checked everywhere?

File: src/Test/Utilities/Portable/Metadata/ILValidation.cs (hunk 14 above)
Comment (agocke) [reply src/Test/Utilities/Portable/Metadata/ILValidation.cs]: I still have no idea why we do it -- I just know that the signature in core framework binaries is reversed.

Comment (jaredpar) [reply src/Test/Utilities/Portable/Metadata/ILValidation.cs]: Understood. But even a comment to that effect will be helpful here. 

> The reason for reversing this signature is unknown. However because the original implementation had this reversal we must also as well. 

This gives a good accountability of "why" we made this change. Lacking the comment the next dev to read this will be wondering why in the same way we wonder why when we look at the CLR implementation 😄

File: src/Test/Utilities/Portable/Metadata/ILValidation.cs (hunk 13 above)
Comment (jaredpar) [reply src/Test/Utilities/Portable/Metadata/ILValidation.cs]: Our entire build is `unchecked`

https://github.com/dotnet/roslyn/blob/master/build/Targets/Settings.props#L316

File: src/Test/Utilities/Portable/Metadata/ILValidation.cs (hunk 8 above)
Comment (agocke) [reply src/Test/Utilities/Portable/Metadata/ILValidation.cs]: Instead I added a Debug assert to fire if the checksums are ever equal. If they are, it's likely the bug has been fixed. It may be possible for the assert to fire in a real case where both checksums are the same, but since this assert will be compiled out in release it seemed like an OK risk to take.

File: src/Compilers/Core/Portable/PEWriter/PeWriter.cs [hunk 15]
```diff
@@ -244,6 +246,47 @@ internal static class PeWriter
             return true;
         }
 
+        private static void FixupChecksum(ExtendedPEBuilder peBuilder, BlobBuilder peBlob)
+        {
+            // Checksum fixup, workaround for https://github.com/dotnet/corefx/issues/25829
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/PEWriter/PeWriter.cs]: Do we have a Roslyn issue tracking the CoreFX issue? If there is only a CoreFX issue worried we will lose track of undoing the work around.

File: src/Test/Utilities/Portable/Metadata/ILValidation.cs [hunk 16]
```diff
@@ -3,16 +3,182 @@
...
 {
     public static class ILValidation
     {
+        /// <summary>
+        /// Validates that the given stream is marked as signed, the signature matches
+        /// the public key, and the header checksum is correct.
+        /// </summary>
+        public static bool IsStreamFullSigned(Stream moduleContents)
+        {
+            moduleContents.Position = 0;
```
Comment (jaredpar) [inline src/Test/Utilities/Portable/Metadata/ILValidation.cs]: This is a visible mutation to the stream. Think this method should restore the original position upon exit.

File: src/Test/Utilities/Portable/Metadata/ILValidation.cs [hunk 17]
```diff
@@ -3,16 +3,182 @@
...
+                int rva = snDirectory.RelativeVirtualAddress;
+                int size = snDirectory.Size;
+                ImmutableArray<byte> signature = peReader.GetSectionData(rva).GetContent(0, size);
+                if (!peHeaders.TryGetDirectoryOffset(snDirectory, out int snOffset))
+                {
+                    return false;
+                }
+
+                moduleContents.Position = 0;
+                int peSize = checked((int)moduleContents.Length);
```
Comment (jaredpar) [inline src/Test/Utilities/Portable/Metadata/ILValidation.cs]: This should be wrapped in a `try / catch / return false`. If the stream signature isn't valid I would expect false to be returned here, not have an overflowexception thrown.

File: src/Compilers/Core/Portable/PEWriter/PeWriter.cs [hunk 18]
```diff
@@ -244,6 +246,48 @@ internal static class PeWriter
...
+            Blob checksumBlob = getChecksumBlob(peBuilder);
+
+            ArraySegment<byte> checksumSegment = checksumBlob.GetBytes();
+            uint oldChecksum = BitConverter.ToUInt32(checksumSegment.Array, checksumSegment.Offset);
+            uint newChecksum = CalculateChecksum(peBlob, checksumBlob);
+            new BlobWriter(checksumBlob).WriteUInt32(newChecksum);
+
+            // If this assert fires, the above bug has been fixed and this workaround should
+            // be removed
+            Debug.Assert(oldChecksum != newChecksum);
```
Comment (jcouv) [inline src/Compilers/Core/Portable/PEWriter/PeWriter.cs]: :+1:

File: src/Compilers/Core/Portable/CommandLine/CommonCommandLineArguments.cs [hunk 19]
```diff
@@ -282,12 +282,15 @@ public CompilationOptions CompilationOptions
...
+            string tempDirectory)
         {
-            // https://github.com/dotnet/roslyn/issues/23521
-            // Disable the portable strong name provider until we can find and fix the
-            // root cause of the bug
-            return new DesktopStrongNameProvider(KeyFileSearchPaths, null, fileSystem);
+            bool fallback = ParseOptionsCore.Features.ContainsKey("UseLegacyStrongNameProvider") ||
+                CompilationOptionsCore.CryptoKeyContainer != null;
+            return fallback ?
+                new DesktopStrongNameProvider(KeyFileSearchPaths, tempDirectory, fileSystem) :
```
Comment (jcouv) [inline src/Compilers/Core/Portable/CommandLine/CommonCommandLineArguments.cs]: Did you add a test to cover the new behavior (`tempDirectory` vs. previously `null`)?

File: src/Test/Utilities/Portable/Metadata/ILValidation.cs [hunk 20]
```diff
@@ -3,16 +3,200 @@
...
 {
     public static class ILValidation
     {
+        /// <summary>
+        /// Validates that the given stream is marked as signed, the signature matches
+        /// the public key, and the header checksum is correct.
+        /// </summary>
+        public static bool IsStreamFullSigned(Stream moduleContents)
+        {
+            var savedPosition = moduleContents.Position;
```
Comment (jcouv) [inline src/Test/Utilities/Portable/Metadata/ILValidation.cs]: What's the scenario where `savedPosition` matters and should be restored? Can it be tested?

File: src/Test/Utilities/Portable/Metadata/ILValidation.cs [hunk 21]
```diff
@@ -3,16 +3,200 @@
...
+                moduleContents.Position = 0;
+
+                using (var metadata = ModuleMetadata.CreateFromStream(moduleContents, leaveOpen: true))
+                {
+                    var metadataReader = metadata.MetadataReader;
+                    var peReader = metadata.Module.PEReaderOpt;
+                    var peHeaders = peReader.PEHeaders;
+                    var flags = peHeaders.CorHeader.Flags;
+
+                    bool is32bit = peHeaders.PEHeader.Magic == PEMagic.PE32;
```
Comment (jcouv) [inline src/Test/Utilities/Portable/Metadata/ILValidation.cs]: Consider moving `metadataReader`, `peHeaders`,   `is32bit`, `SectionHeaderSize`, `signature` (and its inputs), `signatureBlob` closer to usage too

**Comment by agocke** [comment]
cc @MeiChin-Tsai for ask-mode approval

File: src/Compilers/Core/Portable/CommandLine/CommonCommandLineArguments.cs (hunk 19 above)
Comment (agocke) [reply src/Compilers/Core/Portable/CommandLine/CommonCommandLineArguments.cs]: Done.

**Comment by jcouv** [comment]
@dotnet-bot test please

**Comment by jcouv** [comment]
test please

**Comment by jcouv** [comment]
@MeiChin-Tsai for ask-mode approval. Thanks

@agocke I tried to trigger a new CI run, since the current CI results were green but old. Let's make sure we get fresh results. Thanks

**Comment by agocke** [comment]
test this please

**Comment by agocke** [comment]
ping @MeiChin-Tsai for ask-mode approval

**Comment by MeiChin-Tsai** [comment]
approved.
