### PR TITLE
Give a specific message when analyzer references a more-recent compiler version

### LINKED ISSUE #61252: Compiler needs to declaratively fail when loading newer analyzers
The .NET SDK supports installation into older versions of Visual Studio. For example 17.0 installs the 6.0.100 SDK by default but loading 6.0.200, 6.0.300 is supported. While this is supported it means that there is a bit of a mismatch in which compiler is used: 

- When building from Visual Studio or `msbuild` the C# compiler installed with Visual Studio is used.
- When building from the CLI via `dotnet build` the compiler installed with the SDK is used. 

This means that analyzers and generators can experience two different compiler versions based on how the build is invoked. An analyzer / generator that depends on a new version of the Roslyn APIs can get into a situation where `dotnet build` succeeds but `msbuild` fails because the compiler with Visual Studio is too old. That ends up resulting in errors like the following: 

> `##[warning]CSC(0,0): Warning CS8032: An instance of analyzer Microsoft.CodeAnalysis.MakeFieldReadonly.MakeFieldReadonlyDiagnosticAnalyzer cannot be created from C:\hostedtoolcache\windows\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CodeStyle.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
CSC : warning CS8032: An instance of analyzer Microsoft.CodeAnalysis.MakeFieldReadonly.MakeFieldReadonlyDiagnosticAnalyzer cannot be created from C:\hostedtoolcache\windows\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CodeStyle.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.. [f:\a\1\s\src\XX\XX.csproj]

This situation has existed for a while but this error is becoming more common for a variety of reasons:

1. Source generator APIs are new and hence depend on much newer versions of the compiler 
2. Code style analyzers are effectively shipping in lock step with the language now and that requires them to use latest compiler APIs. 
3. There are more scenarios where customers are taking advantage of mismatched VS and .NET SDK versions

Given that we should address this scenario and I believe we should do so in two ways:

1. The compiler needs a declarative diagnostic here. I believe our analyzer loader should just scan the reference table of any analyzer we load and if it depends on a newer version of the compiler then we issue a proactive diagonstic and do not load the analyzer. 
2. The diagnostic should be a warning not an error. The reason is that when a customer gets into this situation there is often nothing they can do. Using an error means the build is fundamentally blocked until they can find the MSBuild logic to remove an analyzer, which then degrades the `dotnet build` scenario. Using a warning means the customer is alerted to the problem and the build can continue. 

Examples of customers hitting this: 

- https://github.com/dotnet/core/issues/7447#issuecomment-1123314610

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #61252

https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1569042

### CODE REVIEW

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs [hunk 1]
```diff
@@ -199,10 +199,7 @@ internal void AddGenerators(ImmutableArray<ISourceGenerator>.Builder builder, st
         private static AnalyzerLoadFailureEventArgs CreateAnalyzerFailedArgs(Exception e, string? typeName = null)
         {
             // unwrap:
-            if (e is { InnerException: FileLoadException inner })
-            {
-                e = inner;
-            }
+            e = (e as TargetInvocationException) ?? e;
```
Comment (Youssef1313) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs:202]: Does this line do anything?

Comment (RikkiGibson) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs]: I don't think it does. I'd like to remove it separately. Feel free to open a PR if you have a minute.

File: src/Compilers/CSharp/Portable/Errors/ErrorCode.cs [hunk 2]
```diff
@@ -2099,6 +2099,8 @@ internal enum ErrorCode
         ERR_FixedFieldMustNotBeRef = 9049,
         ERR_RefFieldCannotReferToRefStruct = 9050,
 
+        WRN_AnalyzerReferencesNewerCompiler = 9057,
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Errors/ErrorCode.cs:2102]: we're skipping error codes which we know are present in 17.4.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs (hunk 1 above)
Comment (Youssef1313) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs]: https://github.com/dotnet/roslyn/pull/62508

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerLoadFailureEventArgs.cs [hunk 3]
```diff
@@ -37,9 +38,11 @@ public enum FailureErrorCode
         /// </summary>
         public Exception? Exception { get; }
 
+        public Version? ReferencedCompilerVersion { get; init; }
```
Comment (RikkiGibson) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerLoadFailureEventArgs.cs:41]: The idea here was to prevent breaking the signature of the constructor, since it is public API. I guess we could use 'internal init' here as well.

Instead of adding this property, we could consider "smuggling through" a string representation of the referenced version through the 'message' property. But that is very hacky.

Ideally the public API would be much more limited here, i.e. the constructor would be internal and perhaps the entire type as well. It's not clear to me why external users would need to dig through why analyzers are failing to load instead of just surfacing the diagnostics.

File: src/Compilers/Core/CodeAnalysisTest/Analyzers/AnalyzerFileReferenceTests.cs [hunk 4]
```diff
@@ -244,6 +244,85 @@ public void TestFailedLoadDoesntCauseNoAnalyzersWarning()
...
+        private class AnalyzerLoaderMockCSharpCompiler : CSharpCompiler
+        {
+            public AnalyzerLoaderMockCSharpCompiler(CSharpCommandLineParser parser, string? responseFile, string[] args, BuildPaths buildPaths, string? additionalReferenceDirectories, IAnalyzerAssemblyLoader assemblyLoader, GeneratorDriverCache? driverCache = null, ICommonCompilerFileSystem? fileSystem = null)
+                : base(parser, responseFile, args, buildPaths, additionalReferenceDirectories, assemblyLoader, driverCache, fileSystem)
+            {
+            }
+        }
+
+        [ConditionalFact(typeof(IsEnglishLocal))]
+        public void AssemblyLoading_ReferencesLaterFakeCompiler_EndToEnd_CSharp()
```
Comment (RikkiGibson) [inline src/Compilers/Core/CodeAnalysisTest/Analyzers/AnalyzerFileReferenceTests.cs:298]: I also wanted to do an end-to-end test for VB, but I wasn't able to figure out how to provide a ref to Microsoft.VisualBasic.dll and System.dll in this context. Tried a few ways of making a mock compiler.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerLoadFailureEventArgs.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerLoadFailureEventArgs.cs:41]: @mavasani do you know whether/how the IDE is directly using `new AnalyzerLoadFailureEventArgs` and related APIs such as `AnalyzerLoadFailureEventArgs.FailureErrorCode`?

Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerLoadFailureEventArgs.cs:41]: The one point I would raise is whether the increase in complexity in the API is justified by how much clearer it makes the error. Basically is the error message without this good enough? Does knowing the exact version referenced by the analyzer help the customer enough to make this API worth it? Lacking this data the customer would still have the version of the compiler and the version of the analyzer (usually it's the full path to the NuPkg). 

Leaned both ways thinking about this in last 5 minutes.

File: src/Compilers/Test/Core/AssemblyLoadTestFixture.cs [hunk 5]
```diff
@@ -385,6 +389,64 @@ public int GetFileAttributes(string path)
...
 
 ");
+
+
+            var analyzerWithFakeCompilerDependencyDirectory = _directory.CreateDirectory("AnalyzerWithFakeCompilerDependency");
+            var fakeCompilerAssembly = GenerateDll("Microsoft.CodeAnalysis", analyzerWithFakeCompilerDependencyDirectory, @"
+using System;
+using System.Reflection;
+
+[assembly: AssemblyVersionAttribute(""42.42.42.42"")]
```
Comment (jaredpar) [inline src/Compilers/Test/Core/AssemblyLoadTestFixture.cs:399]: Why use 42.42.42.42 here? This will sometimes match the version in the MS.CA running in this process and sometimes not match it. Feels like that could lead to flakiness down the road (running unit tests on official binaries for example). My instinct says a different number should be here. Am I missing something about what this helps with?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerLoadFailureEventArgs.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerLoadFailureEventArgs.cs:41]: > Lacking this data the customer would still have the version of the compiler and the version of the analyzer

The user would have the *running* version of the compiler, to be clear. They could be referencing an analyzer version which just happens to require a later SDK than the one they're running, and the process of figuring out manually which compiler version the analyzer is referencing may not be something we expect users to know how to do.

I'm happy to look at any way to pass along this information in a way that's found to be more palatable. But I do think the information is worth passing along.

**Comment by RikkiGibson** [comment]
Looking at the failing netframework tests now.

**Comment by RikkiGibson** [comment]
@jaredpar @chsienki This is ready for another review pass.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerLoadFailureEventArgs.cs (hunk 3 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerLoadFailureEventArgs.cs:41]: > @mavasani do you know whether/how the IDE is directly using new AnalyzerLoadFailureEventArgs and related APIs such as AnalyzerLoadFailureEventArgs.FailureErrorCode?

@RikkiGibson `AnalyzerLoadFailureEventArgs` is required to be exposed for all analyzer hosts that might require loading the analyzer assembly in contexts outside analyzer execution. For example, in the IDE, we need to load the analyzer assembly to populate the `Analyzers` node in the solution explorer, and any failure to load the analyzer assembly needs to be reported as a diagnostic in the error list. We do so by hooking up to the event handler `AnalyzerFileReference.AnalyzerLoadFailed`: https://github.com/dotnet/roslyn/blob/ec6da663c592238cca8e145044e7410c4ca9213a/src/VisualStudio/Core/Def/ProjectSystem/VisualStudioAnalyzer.cs#L52-L53

In the hooked up event handler, we create the appropriate diagnostic using the failure code and report it in the error list: https://github.com/dotnet/roslyn/blob/ec6da663c592238cca8e145044e7410c4ca9213a/src/VisualStudio/Core/Def/ProjectSystem/VisualStudioAnalyzer.cs#L61-L70

**Review by chsienki — APPROVED** [review]
