### PR TITLE
Fix test issues

### LINKED ISSUE #4300: Fix flaky suite CodeGenAsyncTests.Return07_2
The Return07_2 test is periodically failing with the below stack trace.  Need to fix the flaky behavior and re-enable the suite:

```
Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenAsyncTests.Return07_2 : Microsoft.CodeAnalysis.Test.Utilities.ExecutionException : Execution failed for assembly 'C:\Users\acasey\AppData\Local\Temp\RoslynTestFailureDump\de5c3197-023b-4a93-af6d-6f556d27c828'. Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt. at TestCase.<>c__DisplayClass6.<<Run>b__9>d__0.MoveNext() at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine) at TestCase.<>c__DisplayClass6.<Run>b__9() at TestCase.<Run>d__1.MoveNext() at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine) at TestCase.Run() at Driver.Main() ---- System.AccessViolationException : Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.Execute(String moduleName, Int32 expectedOutputLength, String& processOutput) in F:\Enlistments\Roslyn1\Open\Test\Utilities\HostedRuntimeEnvironment.cs:line 257
   at Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.Execute(String moduleName, String expectedOutput) in F:\Enlistments\Roslyn1\Open\Test\Utilities\HostedRuntimeEnvironment.cs:line 264
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.Emit(String expectedOutput, IEnumerable`1 manifestResources, Boolean peVerify, SignatureDescription[] expectedSignatures) in F:\Enlistments\Roslyn1\Open\Test\Utilities\CommonTestBase.CompilationVerifier.cs:line 114
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(CommonTestBase test, Compilation compilation, IEnumerable`1 dependencies, TestEmitters emitOptions, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Action`2 assemblyValidator, Action`2 symbolValidator, Boolean collectEmittedAssembly, Boolean verify) in F:\Enlistments\Roslyn1\Open\Test\Utilities\CommonTestBase.cs:line 400
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, TestEmitters emitOptions, Action`2 sourceSymbolValidator, Action`2 assemblyValidator, Action`2 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean collectEmittedAssembly, Boolean verify) in F:\Enlistments\Roslyn1\Open\Test\Utilities\CommonTestBase.cs:line 202
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, TestEmitters emitOptions, Action`1 sourceSymbolValidator, Action`2 validator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean collectEmittedAssembly, Boolean verify) in F:\Enlistments\Roslyn1\Open\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:line 165
   at Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenAsyncTests.CompileAndVerify(String source, String expectedOutput, IEnumerable`1 references, TestEmitters emitOptions, CSharpCompilationOptions compOptions) in F:\Enlistments\Roslyn1\Open\Compilers\CSharp\Test\Emit\CodeGen\CodeGenAsyncTests.cs:line 35
   at Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenAsyncTests.Return07_2() in F:\Enlistments\Roslyn1\Open\Compilers\CSharp\Test\Emit\CodeGen\CodeGenAsyncTests.cs:line 1984
----- Inner Stack Trace -----
   at TestCase.<>c__DisplayClass6.<<Run>b__9>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at TestCase.<>c__DisplayClass6.<Run>b__9()
   at TestCase.<Run>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at TestCase.Run()
   at Driver.Main()
```

### LINKED ISSUE #5866: CultureAttributeMismatch failing intermittently
This suites is failing intermittently during runs.  Disabling until we can track down the issue.

```
at Microsoft.CodeAnalysis.Test.Utilities.RuntimeAssemblyManager.PeVerifyModules(String[] modulesToVerify, Boolean throwOnError) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Test\Utilities\Desktop\HostedRuntimeEnvironment.cs:line 812 
at Microsoft.CodeAnalysis.Test.Utilities.RuntimeAssemblyManager.PeVerifyModules(String[] modulesToVerify, Boolean throwOnError) 
at Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.PeVerify() in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Test\Utilities\Desktop\HostedRuntimeEnvironment.cs:line 365 
at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.Emit(String expectedOutput, IEnumerable`1 manifestResources, Boolean peVerify, SignatureDescription[] expectedSignatures) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Test\Utilities\Desktop\CommonTestBase.CompilationVerifier.cs:line 104 
at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(Compilation compilation, IEnumerable`1 dependencies, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Action`1 assemblyValidator, Action`1 symbolValidator, Boolean verify) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Test\Utilities\Desktop\CommonTestBase.cs:line 204 at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Test\Utilities\Desktop\CommonTestBase.cs:line 129 
at Microsoft.CodeAnalysis.VisualBasic.UnitTests.BasicTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 validator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Compilers\Test\Utilities\VisualBasic\BasicTestBase.vb:line 77 
at AssemblyAttributeTests.CultureAttributeMismatch() in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Compilers\VisualBasic\Test\Emit\Attributes\AssemblyAttributes.vb:line 455
```

### PR DESCRIPTION
**Pull request by jaredpar**
This fixes as couple of test issues:

- CultureAttributeMismatch: this was a flaky suite whose flakiness was
fixed via the PEVerify changes.  The hardened rules revealed the suite
was setup to consistently fail verification because it didn't fully load
it's dependencies into the Compilation object.  This behavior is
actually expected, we want to get the compiler errors that result from
such a compilation.  Hence we disable verification in those cases.
- Return07_2: This was directly fixed by the PEVerify hardenning.

closes #4300
closes #5866

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-compiler

File: src/Test/Utilities/Desktop/HostedRuntimeEnvironment.cs [hunk 1]
```diff
@@ -137,11 +137,13 @@ private static RuntimeData GetOrCreateRuntimeData(IEnumerable<ModuleData> module
                 return new RuntimeData(new RuntimeAssemblyManager(), null);
             }
 
+            /*
             var data = TryGetCachedRuntimeData(modules);
             if (data != null)
             {
                 return data;
             }
+            */
```
Comment (AlekseyTs) [inline src/Test/Utilities/Desktop/HostedRuntimeEnvironment.cs]: Should this code be removed instead?

**Comment by AlekseyTs** [comment]
LGTM

File: src/Test/Utilities/Desktop/HostedRuntimeEnvironment.cs (hunk 1 above)
Comment (jaredpar) [inline src/Test/Utilities/Desktop/HostedRuntimeEnvironment.cs]: @AlekseyTs that shouldn't be checked in, it was only for testing. Removing.

**Comment by TyOverby** [comment]
LGTM
