### PR TITLE
Don't store pooled object in cache

### LINKED ISSUE #39599: MisplacedUsingDirectivesDiagnosticAnalyzer ' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Index was out of range.
**Version Used**: 
Version 16.5.0 Preview 1.0 [29429.152.master]

**Steps to Reproduce**:

``` C#
namespace Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package
{
    using System;
    using System.Collections.Immutable;
    using System.ComponentModel.Composition;
    using System.Diagnostics.CodeAnalysis;
    using System.Diagnostics.Contracts;
    using System.Threading;
    using Microsoft.VisualStudio.Shell.Interop;
```

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.MisplacedUsingDirectives.MisplacedUsingDirectivesDiagnosticAnalyzer' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index'.	Microsoft.VisualStudio.ProjectSystem.VS.Implementation		1	Active	Analyzer 'Microsoft.CodeAnalysis.CSharp.MisplacedUsingDirectives.MisplacedUsingDirectivesDiagnosticAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.VisualStudio.ProjectSystem.VS.Implementation
SyntaxTree: C:\CPS\src\Microsoft.VisualStudio.ProjectSystem.VS.Implementation\VsProjectTypeValuesCacheService.cs
SyntaxNode: namespace Microsoft.VisualStudio ... [NamespaceDeclarationSyntax]@[314..24814) (6,0)-(495,1)

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Microsoft.CodeAnalysis.AnalyzerConfigSet.SequenceEqualComparer.Equals(List`1 x, List`1 y)
   at Microsoft.CodeAnalysis.ConcurrentCache`2.TryAdd(TKey key, TValue value)
   at Microsoft.CodeAnalysis.AnalyzerConfigSet.GetOptionsForSourcePath(String sourcePath)
   at Microsoft.CodeAnalysis.ProjectState.WorkspaceAnalyzerConfigOptionsProvider.GetOptions(SyntaxTree tree)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.GetFilteredDiagnostic(Diagnostic diagnostic, Compilation compilation, AnalyzerOptions analyzerOptions)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<>c__DisplayClass117_0.<GetDiagnosticSink>b__0(Diagnostic diagnostic, DiagnosticAnalyzer analyzer, Boolean isSyntaxDiagnostic)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.AnalyzerDiagnosticReporter.AddDiagnostic(Diagnostic diagnostic)
   at Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext.ReportDiagnostic(Diagnostic diagnostic)
   at Microsoft.CodeAnalysis.CSharp.MisplacedUsingDirectives.MisplacedUsingDirectivesDiagnosticAnalyzer.ReportDiagnostics(SyntaxNodeAnalysisContext context, DiagnosticDescriptor descriptor, IEnumerable`1 usingDirectives, CodeStyleOption`1 option)
   at Microsoft.CodeAnalysis.CSharp.MisplacedUsingDirectives.MisplacedUsingDirectivesDiagnosticAnalyzer.AnalyzeNamespaceNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__55`1.<ExecuteSyntaxNodeAction>b__55_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.

```

### PR DESCRIPTION
**Pull request by agocke**
The AnalyzerConfigSet had a race where we were storing the pooled object
in the cache. It turns out that this often works, due to hash codes mapping
different sets to different buckets, but is wildly unsafe and can produce
almost any result.

This change allocates a new list for the cache when adding.

Fixes #39599

### CODE REVIEW

**Comment by agocke** [comment]
Unfortunately, haven't figured out a good way to make a test that fails for this.

Obviously it's possible for it to fail if the hash of the object identities of different sections collide, but that's not really mockable.

**Comment by agocke** [comment]
@jaredpar I think we should take this for 16.4

**Comment by jaredpar** [comment]
I agree.

**Comment by jasonmalinowski** [comment]
@agocke Should this be targeting release/dev16.4 (non-vs-deps)?

**Comment by agocke** [comment]
@jasonmalinowski Yes, thank you.

File: src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs [hunk 1]
```diff
@@ -193,7 +193,7 @@ public AnalyzerConfigOptionsResult GetOptionsForSourcePath(string sourcePath)
                     treeOptionsBuilder.Count > 0 ? treeOptionsBuilder.ToImmutable() : SyntaxTree.EmptyDiagnosticOptions,
                     analyzerOptionsBuilder.Count > 0 ? analyzerOptionsBuilder.ToImmutable() : AnalyzerConfigOptions.EmptyDictionary,
                     diagnosticBuilder.ToImmutableAndFree());
-                _optionsCache.TryAdd(sectionKey, result);
+                _optionsCache.TryAdd(new List<Section>(sectionKey), result);
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs]: >new List<Section>(sectionKey) [](start = 37, length = 29)

So, the problem was that were clearing and freeing the ```sectionKey``` below? If we wouldn't do that for this code path things would work?

Comment (AlekseyTs) [reply src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs]: Would it make sense to ```ForgetTrackedObject``` on this code path instead?

---
In reply to: [343936912](https://github.com/dotnet/roslyn/pull/39729#discussion_r343936912) [](ancestors = 343936912)

Comment (agocke) [reply src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs]: That would also work, but I figured that it doesn't matter either way -- if we have a stable pooled object count then we would then immediately allocate a new object for the pool to satisfy parallel requests.

So we either allocate a new object here, or in the pooling manager. This seemed less error-prone.

Comment (AlekseyTs) [reply src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs]: > So we either allocate a new object here, or in the pooling manager. This seemed less error-prone.

It feels like delaying an allocation until it actually necessary is always good.

---
In reply to: [344299232](https://github.com/dotnet/roslyn/pull/39729#discussion_r344299232) [](ancestors = 344299232)

Comment (agocke) [reply src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs]: Sounds fine to me
