### PR TITLE
Split CloseFile into CloseCodeFile and CloseDesignerFile

### LINKED ISSUE #26442: Flaky integration test VisualBasic.BasicWinForms.AddControl
**VisualBasic.BasicWinForms.AddControl** [failed](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/915/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicWinForms/AddControl/) in debug on a non-code PR (https://github.com/dotnet/roslyn/pull/26416) with the following message:

**Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicWinForms.AddControl** (from Roslyn.VisualStudio.IntegrationTests)

Failing for the past 1 build (Since Failed#915 )
Took 2.6 sec.
Stacktrace
MESSAGE:
Assert.Contains() Failure
Not found: ``Me.SomeButton.Name = "SomeButton"``
In value: 
```VB
<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class Form1
 Inherits System.Windows.Forms.Form
 
 'Form overrides dispose to clean up the component list.
  <System.Diagnostics.DebuggerNonUserCode()> _
  Protected Overrides Sub Dispose(ByVal disposing As Boolean)
   Try
    If disposing AndAlso components IsNot Nothing Then
     components.Dispose()
    End If
   Finally
    MyBase.Dispose(disposing)
   End Try
  End Sub
  
  'Required by the Windows Form Designer
  Private components As System.ComponentModel.IContainer
  
  'NOTE: The following procedure is required by the Windows Form Designer
  'It can be modified using the Windows Form Designer. 
  'Do not modify it using the code editor.
  <System.Diagnostics.DebuggerStepThrough()> _
  Private Sub InitializeComponent()
   components = New System.ComponentModel.Container()
   Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
   Me.ClientSize = New System.Drawing.Size(800, 450)
   Me.Text = "Form1"
  End Sub
 
End Class

```
+++++++++++++++++++
STACK TRACE:
at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicWinForms.AddControl()

### LINKED ISSUE #26443: Flakey integration test VisualBasic.BasicWinForms.ChangeControlProperty
**VisualBasic.BasicWinForms.ChangeControlProperty** [failed](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/915/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicWinForms/ChangeControlProperty/) in debug on a non-code PR (https://github.com/dotnet/roslyn/pull/26416) with the following message:

**Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicWinForms.ChangeControlProperty** (from Roslyn.VisualStudio.IntegrationTests)

Failing for the past 1 build (Since Failed#915 )
Took 3.3 sec.
Stacktrace
MESSAGE:
Assert.Contains() Failure
Not found: `Me.SomeButton.Text = "NewButtonText"`
In value:
```VB 
<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class Form1
 Inherits System.Windows.Forms.Form

 'Form overrides dispose to clean up the component list.
 <System.Diagnostics.DebuggerNonUserCode()> _
 Protected Overrides Sub Dispose(ByVal disposing As Boolean)
  Try
   If disposing AndAlso components IsNot Nothing Then
    components.Dispose()
   End If
  Finally
   MyBase.Dispose(disposing)
  End Try
 End Sub

 'Required by the Windows Form Designer
 Private components As System.ComponentModel.IContainer

 'NOTE: The following procedure is required by the Windows Form Designer
 'It can be modified using the Windows Form Designer. 
 'Do not modify it using the code editor.
 <System.Diagnostics.DebuggerStepThrough()> _
 Private Sub InitializeComponent()
  components = New System.ComponentModel.Container()
  Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
  Me.ClientSize = New System.Drawing.Size(800, 450)
  Me.Text = "Form1"
 End Sub

End Class
```
+++++++++++++++++++
STACK TRACE:
at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicWinForms.ChangeControlProperty()

### LINKED ISSUE #26444: Flaky integration test VisualBasic.BasicWinForms.ChangeControlPropertyInCode
**VisualBasic.BasicWinForms.ChangeControlPropertyInCode** [failed](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/915/testReport/junit/Roslyn.VisualStudio.IntegrationTests.VisualBasic/BasicWinForms/ChangeControlPropertyInCode/) in debug on a non-code PR (https://github.com/dotnet/roslyn/pull/26416) with the following message:

**Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicWinForms.ChangeControlPropertyInCode** (from Roslyn.VisualStudio.IntegrationTests)

Failing for the past 1 build (Since Failed#915 )
Took 2.7 sec.
Stacktrace
MESSAGE:
Assert.Contains() Failure
Not found: `Me.SomeButton.Text = "ButtonTextGoesHere"`
In value:
```VB
<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class Form1
 Inherits System.Windows.Forms.Form

 'Form overrides dispose to clean up the component list.
 <System.Diagnostics.DebuggerNonUserCode()> _
 Protected Overrides Sub Dispose(ByVal disposing As Boolean)
  Try
   If disposing AndAlso components IsNot Nothing Then
    components.Dispose()
   End If
  Finally
   MyBase.Dispose(disposing)
  End Try
 End Sub

 'Required by the Windows Form Designer
 Private components As System.ComponentModel.IContainer

 'NOTE: The following procedure is required by the Windows Form Designer
 'It can be modified using the Windows Form Designer. 
 'Do not modify it using the code editor.
 <System.Diagnostics.DebuggerStepThrough()> _
 Private Sub InitializeComponent()
  components = New System.ComponentModel.Container()
  Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
  Me.ClientSize = New System.Drawing.Size(800, 450)
  Me.Text = "Form1"
 End Sub

End Class


```
+++++++++++++++++++
STACK TRACE:
at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicWinForms.ChangeControlPropertyInCode()

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #26442
Fixes #26443
Fixes #26444

### CODE REVIEW

File: src/VisualStudio/IntegrationTest/TestUtilities/InProcess/SolutionExplorer_InProc.cs [hunk 1]
```diff
@@ -888,25 +888,36 @@ public void OpenFile(string projectName, string relativeFilePath)
...
-                document.Close(EnvDTE.vsSaveChanges.vsSaveChangesYes);
-            }
-            else
+            CloseFile(projectName, relativeFilePath, VSConstants.LOGVIEWID.Designer_guid, saveFile);
+        }
+
+        public void CloseCodeFile(string projectName, string relativeFilePath, bool saveFile)
+        {
+            CloseFile(projectName, relativeFilePath, VSConstants.LOGVIEWID.Code_guid, saveFile);
+        }
```
Comment (ivanbasov) [inline src/VisualStudio/IntegrationTest/TestUtilities/InProcess/SolutionExplorer_InProc.cs]: nit: you can inline this and above

File: src/VisualStudio/IntegrationTest/TestUtilities/InProcess/SolutionExplorer_InProc.cs [hunk 2]
```diff
@@ -888,25 +888,36 @@ public void OpenFile(string projectName, string relativeFilePath)
...
+                ErrorHandler.ThrowOnFailure(windowFrame.CloseFrame((uint)frameClose));
+            });
         }
 
         private EnvDTE.Document GetOpenDocument(string projectName, string relativeFilePath)
         {
             var filePath = GetAbsolutePathForProjectRelativeFilePath(projectName, relativeFilePath);
             var documents = GetDTE().Documents.Cast<EnvDTE.Document>();
-            var document = documents.FirstOrDefault(d => d.FullName == filePath);
+            var document = documents.SingleOrDefault(d => d.FullName == filePath);
```
Comment (ivanbasov) [inline src/VisualStudio/IntegrationTest/TestUtilities/InProcess/SolutionExplorer_InProc.cs]: >SingleOrDefault [](start = 37, length = 15)

I like this!

File: src/VisualStudio/IntegrationTest/TestUtilities/InProcess/SolutionExplorer_InProc.cs (hunk 1 above)
Comment (sharwell) [reply src/VisualStudio/IntegrationTest/TestUtilities/InProcess/SolutionExplorer_InProc.cs]: I'm going to keep it like this since it's causing build failures and we already have a passing build in the current form.
