### PR TITLE
Object Creation Preselection special case

### LINKED ISSUE #2836: Declared type precedence in new operator (regression)
Mentioned but not addressed in comments at CodePlex [#138](https://roslyn.codeplex.com/workitem/138).

```csharp
bool b;
Program p = new |
b = false;
```

This results in Intellisense offering `bool` instead of `Program`. There is no scenario where `bool` would be acceptable at this place (or where the code after cursor would be relevant to what is following the `new` operator).

This worked in previous version of Visual Studio.

### PR DESCRIPTION
**Pull request by balajikris**
Fixes #2836.

There are cases in broken code scenarios where the new keyword in
objectcreationexpression appears to be a part of a subsequent
assignment.

This was originally addressed in #2537. This commit addresses #2836
which is a special case of the same class of problem.

E.g:
```C#
bool b;
Program p = new $$
b = false;
```

Per the parser, the new token here belongs to the second assignment and
hence type inferrer recommends `bool`.  However, that is not helpful.
The IDE detects this and correctly infers the type `Program` which is
what the user expects.

### CODE REVIEW

**Comment by balajikris** [comment]
staging against master for CR and bar checks etc. Will send a PR for stabilization if approved. 

tagging for CR: @rchande @dpoeschl @brettfo @basoundr @DustinCampbell @jmarolf @jasonmalinowski @Pilchie

**Comment by tmeschter** [comment]
@dotnet-bot Retest this, please.

**Comment by Pilchie** [comment]
Assigning to Matt for bar check.

**Comment by rchande** [comment]
:shipit: Thanks!

**Comment by rchande** [comment]
@balajikris Can we think of any other cases that will follow the same pattern?

**Comment by Pilchie** [comment]
:+1:

**Comment by tmeschter** [comment]
@dotnet-bot Retest this, please.

**Comment by MattGertz** [comment]
Rejected 6/11 by ML Shiproom.

**Comment by balajikris** [comment]
Merging to Master for 1.1

File: src/Workspaces/CSharp/Portable/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs [hunk 1]
```diff
@@ -283,12 +274,44 @@ private IEnumerable<ITypeSymbol> InferTypesWorker(int position)
...
+                        // but the user is really trying to assign to Location.
+                        // In this case, we need to detect that the 'new' token is on the left side of 
+                        // its parent assignment and on the right side of its grandparent assignment and
+                        // return the inferred type of the grandparent.
+                        if (parentAssignment.Parent is AssignmentExpressionSyntax)
                         {
-                            parent = grandparentAssignment;
-                            token = grandparentAssignment.OperatorToken;
+                            var grandparentAssignment = (AssignmentExpressionSyntax)parentAssignment.Parent;
+                            if (grandparentAssignment.IsKind(SyntaxKind.SimpleAssignmentExpression) &&
```
Comment (DustinCampbell) [inline src/Workspaces/CSharp/Portable/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs]: This won't work for compound assignment. With your change, I would expect this case to still be a problem:

```C#
int i;
Program p = new |
i += 1;
```

Comment (balajikris) [inline src/Workspaces/CSharp/Portable/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs]: Yes, good catch! :clap: I'd indeed forgotten about this. 

Haven't tested yet but some notes off the top of my mind:
The first check however is scoped for cases like below, which cannot have compound assignment :
```C#
Program p = new $$
bool b = false;
```

The second check for equals value clause though, should handle this. I'll test and address it :smile: 

Thanks again, good find.
