### PR TITLE
Better handle dismissed rename tracking sessions

### LINKED ISSUE #540: Stale rename entries in the lightbulb menu
Ported from TFS WorkItem: **1125186**

------------------------------

**Repro Steps:**

**Affected Branch:**&nbsp;vspro_1
 **Affected Build:**&nbsp;22611
 **Affected Product Language:** 
 
**Steps to reproduce:**

1. paste the following code<div>
  </div><div><div>&nbsp; &nbsp; &nbsp; &nbsp; int M3(int x) { return x; }</div></div><div>
  </div><div>

2. change "x" in "return x;" to "xrenamed", note that the rectangle around xrenamed indicating the rename tracking</div><div>

3. press [ESC], note that the rectangle is gone</div><div>

4. Ctrl+[DOT]</div><div>

5. Select either rename option.</div><div><div>
</div><div>**Expected**:</div><div>x renamed to y,</div><div>or rename options shouldn't appear if the tracking is gone.</div><div>
</div><div>**Actual**:</div></div><div>Nothing happened.</div>

------------------------------

**Revisions:**

1) Created By Jeremy Meng (2/13/2015 10:54:57 AM)

------------------------------

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #540 "Stale rename entries in the lightbulb menu"

Prior to this change, dismissed rename tracking sessions continued to
provide codefixes which would silently fail when invoked, without
completing the rename operation.

With this change, we now do the following when rename tracking is
manually dismissed:

- Trigger the diagnostic service to reanalyze the document, thus
removing the rename tracking diagnostic.
- Stop providing a codefix when requested
- Show a dialog if a cached codefix is invoked explaining that the
rename was not performed.

Here are the there user scenarios:

1. The user dismisses rename tracking

- The lightbulb will continue to show in the margin, regardless of
whether any codefix/refactoring is actually still available.

2. The user expands the lightbulb without it ever having been expanded
before.

- In this case, we are queried for fixes and will not return any, so
either the lightbulb will disappear or it will contain other relevant
codefixes/refactorings at that position, excluding rename.

3. The user expands the lightbulb after it was previously expanded.

- Our fix was already cached, so we can only give a reasonable message
when it is invoked.

Once #885 is fixed, we can instead implement IDiagnosticUpdateSource and
avoid forcing diagnostic reanalysis.

### CODE REVIEW

**Comment by dpoeschl** [comment]
New PR because I cannot reopen #770. We want to eventually the implementation from reanalyzing diagnostics to implementing IDiagnosticUpdateSource, but that depends on #885 being completed. For the current milestone, let's proceed with this interim solution as it fixes certain cases and the rest of the time it avoids the confusion of committing the lightbulb item and having nothing happen.

**Comment by dpoeschl** [comment]
Tagging reviewers: @balajikris was already looking at #770, and other potential reviewers include @Pilchie @basoundr @rchande @brettfo

File: src/EditorFeatures/Test/RenameTracking/RenameTrackingTaggerProviderTests.cs [hunk 1]
```diff
@@ -1,13 +1,13 @@
 // Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
 
-using System;
```
Comment (brettfo) [inline src/EditorFeatures/Test/RenameTracking/RenameTrackingTaggerProviderTests.cs]: Other files in this PR keep the System directives at the top.

**Comment by Pilchie** [comment]
:+1:

File: src/EditorFeatures/Test/RenameTracking/RenameTrackingTaggerProviderTests.cs (hunk 1 above)
Comment (dpoeschl) [inline src/EditorFeatures/Test/RenameTracking/RenameTrackingTaggerProviderTests.cs]: Fixed. Thanks Brett.

**Comment by dpoeschl** [comment]
@balajikris - can you take a look?

**Comment by balajikris** [comment]
:+1:
