### PR TITLE
Fix classification for comments after "#pragma warning" directives

### LINKED ISSUE #30783: Comments after "#pragma warning" directives sometimes don't have correct colouring
**Version Used**: VS 15.8.8 (Roslyn 2.9.0.63208)

**Steps to Reproduce**:

1. Paste the following code into a C# file.

```c#
#pragma warning disable // Test
#pragma warning disable CS1000 // Test
```

**Expected Behavior**: Both comments are highlighted as comments.

**Actual Behavior**: Only the second comment is highlighted as a comment.

pwd-hr

### PR DESCRIPTION
**Pull request by jhinder**
Fixes #30783.

Single-line comments after the `disable`/`restore` keyword are part of the trailing trivia of the keyword token. This PR adds support for classifying those comments.

Block comments are not supported in preprocessor directives, so they are not classified.

### CODE REVIEW

File: src/Workspaces/CSharp/Portable/Classification/Worker_Preprocesser.cs [hunk 1]
```diff
@@ -263,6 +263,17 @@ private void ClassifyPragmaWarningDirective(PragmaWarningDirectiveTriviaSyntax n
             AddClassification(node.WarningKeyword, ClassificationTypeNames.PreprocessorKeyword);
             AddClassification(node.DisableOrRestoreKeyword, ClassificationTypeNames.PreprocessorKeyword);
 
+            // Comments after a "#pragma warning" directive without any error codes are trailing trivia of the "disable"/"restore" token.
```
Comment (sharwell) [inline src/Workspaces/CSharp/Portable/Classification/Worker_Preprocesser.cs]: ❓ Why not just call `ClassifyDirectiveTrivia` at the end of this method, like that seen in other cases:

https://github.com/dotnet/roslyn/blob/8c0679915d947048efa5786fc7f1f9b1bf1efdcc/src/Workspaces/CSharp/Portable/Classification/Worker_Preprocesser.cs#L288

Comment (jhinder) [reply src/Workspaces/CSharp/Portable/Classification/Worker_Preprocesser.cs]: That makes two tests fail (namely `PP_PragmaWarning[Disable|Restore]OneWithComment`), because the actual output contains one additional `Comment("//Goo")`. Those two tests have error codes in the directive, so the classifier function calls `ClassifyNodeOrToken` on the error code node, from where it will eventually reach `ClassifyTriviaList` and `ClassifyTrivia`, adding a second classification for the comment. And we can't pass `allowComments: false` because that would defeat the entire purpose of that call.

Comment (sharwell) [reply src/Workspaces/CSharp/Portable/Classification/Worker_Preprocesser.cs]: 💭 Would it work to call `ClassifyDirectiveTrivia` only if `node.ErrorCodes` is empty?

Comment (jhinder) [reply src/Workspaces/CSharp/Portable/Classification/Worker_Preprocesser.cs]: Yes, that works. Thanks! I've updated the PR.

Comment (sharwell) [reply src/Workspaces/CSharp/Portable/Classification/Worker_Preprocesser.cs]: 🎉

**Comment by sharwell** [comment]
@jinujoseph for approval
