### PR TITLE
Disallow returning TypedReference in local functions

### LINKED ISSUE #27463: TypedReference shoud not be returned from C# 7.0 Local Function
**Version Used**: C# 7.0 ~ 7.3

**Steps to Reproduce**:

C# compiler can't compile next code.

        // Error CS1599 Method or delegate cannot return type 'TypedReference'
        TypedReference GetInstanceFromFunction()
        {
            int x = 100;
            TypedReference tr = __makeref(x);
            return tr;
        }

But, C# compiler can compile next code.

    private static void TestLocalFunction()
    {
        TypedReference inst = GetInstanceFromLocalFunction();
        int value = __refvalue(inst, int);
        Console.WriteLine(value);

        TypedReference GetInstanceFromLocalFunction()
        {
            int x = 100;
            TypedReference tr = __makeref(x);
            return tr;
        }
    }

As you know, it has side effect when the above code compile with Release. (or if some code exists between GetInstanceFromLocalFunction and __refvalue)

**Expected Behavior**:
In Local function, C# compiler must produce CS1599 error when returning TypedReference.

**Actual Behavior**:
In Local function, C# compiler compile normally.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Resolves #27463

The implementation is basically copied and simplified from the code linked below.
https://github.com/dotnet/roslyn/blob/06fce4022bf56edf7c89787c8b381ec8e3a5bfd5/src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs#L182

I didn't see tests about local functions with ref parameters of restricted types so I added one.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs [hunk 1]
```diff
@@ -241,6 +241,13 @@ internal void ComputeReturnType()
                 // Note: we don't need to warn on annotations used without NonNullTypes context for local functions, as this is handled in binding already
             }
 
+            // span-like types are returnable in general
+            if (returnType.IsRestrictedType(ignoreSpanLikeTypes: true))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: >ignoreSpanLikeTypes: true [](start = 44, length = 25)

It would be good to have a tests observing significance of ```ignoreSpanLikeTypes: true```.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 3)

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: Should it be a standalone test in LocalFunctionTests.cs instead of something in SymbolErrorTests.cs?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: Addressed in 640f73e

**Comment by RikkiGibson** [comment]
Seems like integration tests are hung up. Should I wait for them or just merge?

**Comment by jaredpar** [comment]
Took a look, it's just the VS integration tests and there is no real risk here for those. Merge away.
