### PR TITLE
Report AD0001 if an analyzer accidentally provides a null descriptor …

### LINKED ISSUE #30453: Handle null descriptor in DiagnosticAnalyzer.SupportedDiagnostics
Likely cause of intermittent FailFast in integration tests: https://ci.dot.net/job/dotnet_roslyn/job/dev16.0.x/job/windows_debug_vs-integration_prtest/189/artifact/Binaries/Debug/UnitTests/Microsoft.VisualStudio.LanguageServices.IntegrationTests/xUnitResults/Screenshots/Unknown-RemotingException-16.23.36.DotNet.log

```
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.NullReferenceException: Object reference not set to an instance of an object.

   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.AnalyzerExecutionContext.ComputeDescriptors(DiagnosticAnalyzer analyzer, AnalyzerExecutor analyzerExecutor)

   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.AnalyzerExecutionContext.GetOrComputeDescriptors(DiagnosticAnalyzer analyzer, AnalyzerExecutor analyzerExecutor)

   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.GetSupportedDiagnosticDescriptors(DiagnosticAnalyzer analyzer, AnalyzerExecutor analyzerExecutor)

   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.IsDiagnosticAnalyzerSuppressed(DiagnosticAnalyzer analyzer, CompilationOptions options, Func`2 isCompilerAnalyzer, AnalyzerExecutor analyzerExecutor)

   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.IsDiagnosticAnalyzerSuppressed(DiagnosticAnalyzer analyzer, CompilationOptions options, AnalyzerManager analyzerManager, AnalyzerExecutor analyzerExecutor)

   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<GetAnalyzerActionsAsync>d__105.MoveNext()
```

### PR DESCRIPTION
**Pull request by mavasani**
…in its SupportedDiagnostics

Fixes #30453

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs [hunk 1]
```diff
@@ -889,6 +889,22 @@ public void TestReportingDiagnosticWithInvalidId()
...
+        public void TestAnalyzerWithNullDescriptor()
+        {
+            string source = @"";
+            var analyzers = new DiagnosticAnalyzer[] { new AnalyzerWithNullDescriptor() };
+            var analyzerFullName = "Microsoft.CodeAnalysis.CommonDiagnosticAnalyzers+AnalyzerWithNullDescriptor";
+            string message = new ArgumentException(string.Format(CodeAnalysisResources.SupportedDiagnosticsHasNullDescriptor, analyzerFullName), "SupportedDiagnostics").Message;
+
+            CreateCompilationWithMscorlib45(source)
+                .VerifyDiagnostics()
+                .VerifyAnalyzerDiagnostics(analyzers, null, null, logAnalyzerExceptionAsDiagnostics: true,
```
Comment (sharwell) [inline src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs]: 📝 The alternative to `logAnalyzerExceptionAsDiagnostics: true` results in a `FailFast` during testing. I have a local branch where I'm working to remove this parameter instead since `FailFast` has been causing us so much trouble.

**Comment by sharwell** [comment]
@jaredpar This is, to our best combined guess, the underlying cause of the integration test failure your recent PR experienced.

**Comment by mavasani** [comment]
@jinujoseph for approval
