### PR TITLE
Reset the interactive window using IInteractiveWindowOperations

### LINKED ISSUE #52409: Flaky test - Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpInteractive.BclMathCall
someone needs to modify the test to force the interactive host process to crash when this test fails. We already have tools in place to capture that crash dump and attach it to the build

_Originally posted by @sharwell in https://github.com/dotnet/roslyn/issues/51856#issuecomment-810613400_

### PR DESCRIPTION
**Pull request by sharwell**
The previous implementation relies on using DTE to execute a named command. However, since it is not the purpose of these tests to cover invoking this command by name (a dedicated test could be created if desired), we modify the code to instead directly invoke the backing API for this command. This change reduces the likelihood that a failure in the commanding infrastructure leads to an obscure test failure.

Closes #52409

### CODE REVIEW

File: src/VisualStudio/IntegrationTest/TestUtilities/InProcess/InteractiveWindow_InProc.cs [hunk 1]
```diff
@@ -151,7 +152,15 @@ public string GetLastReplInput()
 
         public void Reset(bool waitForPrompt = true)
         {
-            ExecuteCommand(WellKnownCommandNames.InteractiveConsole_Reset);
```
Comment (jasonmalinowski) [inline src/VisualStudio/IntegrationTest/TestUtilities/InProcess/InteractiveWindow_InProc.cs:154]: Why isn't this way stable? Is this actually hiding a bug where the user command won't be reliable?

Comment (sharwell) [reply src/VisualStudio/IntegrationTest/TestUtilities/InProcess/InteractiveWindow_InProc.cs:154]: @tmat and I were not able to find a root cause looking through heap dumps all day. My best guess is we are somehow issuing the command at a point where `IsResetting` is true and it ends up getting dropped:

https://github.com/dotnet/interactive-window/blob/f45f6bef9e002b4b661ad7abf73f5dc996c0709d/src/Microsoft.VisualStudio.VsInteractiveWindow/VsInteractiveWindowCommandFilter.cs#L374

Comment (jasonmalinowski) [reply src/VisualStudio/IntegrationTest/TestUtilities/InProcess/InteractiveWindow_InProc.cs:154]: Hmm, ExecuteCommand doesn't return a failure if we try executing it when the command is unavailable?

**Review by jasonmalinowski — APPROVED** [review]

File: src/VisualStudio/IntegrationTest/TestUtilities/InProcess/InteractiveWindow_InProc.cs (hunk 1 above)
Comment (sharwell) [reply src/VisualStudio/IntegrationTest/TestUtilities/InProcess/InteractiveWindow_InProc.cs:154]: The [documentation](https://docs.microsoft.com/en-us/dotnet/api/envdte._dte.executecommand?view=visualstudiosdk-2019) just says:

> `ExecuteCommand` cannot execute commands that are currently disabled in the environment. The `Build` method, for example, will not execute while a build is currently in progress.

The method returns `void` and doesn't declare any exceptions.
