### PR TITLE
Add unit-tests for fixed issues.

### LINKED ISSUE #31676: Regression with Nullable<T> and a generic type constraint on base
With the attached solution, we (the EF team) are getting the following errors:

> error CS8320: Feature 'nullable reference types' is not available in C# 7.0. Please use language version 8.0 or greater.
> error CS8627: A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint.
> error CS0115: 'QueryAsserter<TContext>.AssertQueryScalar<TItem1, TResult>(Func<IQueryable<TItem1>, IQueryable<TResult?>>)': no suitable method found to override
> error CS0534: 'QueryAsserter<TContext>' does not implement inherited abstract member 'QueryAsserterBase.AssertQueryScalar<TItem1, TResult>(Func<IQueryable<TItem1>, IQueryable<TResult?>>)'

The base type looks like this. (Our actual codebase uses `TResult?` here too but it reproed more consistently with `Nullable<TResult>`)

``` csharp
public abstract class QueryAsserterBase
{
    public abstract void AssertQueryScalar<TItem1, TResult>(
        Func<IQueryable<TItem1>, IQueryable<Nullable<TResult>>> actualQuery)
        where TResult : struct;
}
```

The derived type looks like this.

``` csharp
public class QueryAsserter<TContext> : QueryAsserterBase
{
    public override void AssertQueryScalar<TItem1, TResult>(
        Func<IQueryable<TItem1>, IQueryable<TResult?>> actualQuery)
    {          
    }
}
```

Putting the classes in the same file makes the issue go away as do other seemingly unrelated changes. Possibly an ordering issue or a race condition. Only repros on later versions of Roslyn (VS 2019 and .NET Core SDK 3.0).

cc @maumar @ajcvickers @Eilon

[Repro.zip](https://github.com/dotnet/roslyn/files/2664844/Repro.zip)

### LINKED ISSUE #33276: Nullability check; Ignoring inherited type constraints from types in another assembly
**Version Used**:  VS 2019 Preview 2.2

**Steps to Reproduce**:
This issue was quite hard to isolate, here it is: 
1. in BaseAssembly.dll
```CS
    public class MyEntity
    {
    }

    public abstract class BaseController<T>
        where T : MyEntity
    {
        public abstract void SomeMethod<R>(R? lite)
            where R : MyEntity;
    }
```

in DerivedAssembly.dll

```CS
        class DerivedController<T> : BaseController<T>
            where T : MyEntity
        {
            Table<T> table = null!;
            public override void SomeMethod<R>(R? lite) /*where R : MyEntity produces CS460*/
            {
/*error CS8627: A nullable type parameter must be known to be a value type or non-nullable reference type. Consider adding a 'class', 'struct', or type constraint.*/
                   table.OtherMethod(lite);
            }
        }

        class Table<T>
            where T : MyEntity
        {
            public void OtherMethod<R>(R? lite) where R : MyEntity
            {
                lite?.ToString();
            }
        }
```
Both assemblies have   `<NullableContextOptions>enable</NullableContextOptions>`

**Expected Behavior**:
Compiles succesfully

**Actual Behavior**:
error CS8627

### PR DESCRIPTION
**Pull request by AlekseyTs**
Closes #33276.
Closes #31676.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 1]
```diff
@@ -13184,6 +13184,121 @@ class D : C
...
+}
+";
+
+            var source2 =
+@"
+class DerivedController<T> : BaseController<T>
+    where T : MyEntity
+{
+    Table<T> table = null!;
+    public override void SomeMethod<R>(R? lite) where R : class
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >where R : class [](start = 48, length = 15)

is it also worth testing without the constraint on the override (as originally reported in the bug)?

As a side note, was there a discussion to port the fix for compat break to 16.0 (the fix is currently made it in 16.1p3)?
