### PR TITLE
Fix switch-expression and pattern printing in SyntaxNormalizer

### LINKED ISSUE #52543: NormalizeWhitespace on switch expressions behave weirdly
**Version Used**: 
3.9.0

**Steps to Reproduce**:

1. Create a switch expression syntax
2. call .NormalizeWhitespace()
3. print the result, ie using .ToFullString()

**Expected Behavior**:
like all other components, switch expressions are formatted nicely

example:
```cs
entryPoint switch
{
    "MessageBoxA" => MessageBoxA,
    "CreateWindowExA" => CreateWindowExA
}
```

**Actual Behavior**:
switch expressions are formatted oddly

example:
```cs
entryPoint switch
{
"MessageBoxA" => MessageBoxA, "CreateWindowExA" => CreateWindowExA
}
```
note that at the end there is two newlines too much, as a trailing semicolon is weirdly placed like
```cs
...
}

;
```

### PR DESCRIPTION
**Pull request by bernd5**
Draft for fixed printing / normalize for `SwitchExpressionSyntax` and `RecursivePatternSyntax`.

fixes #52543

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Needs tests :)

**Comment by Youssef1313** [comment]
> See: #52680

This links to this PR

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs [hunk 1]
```diff
@@ -16,6 +16,68 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+  Bus b when ((double)b.Riders / (double)b.Capacity) < 0.50 => 5.00m + 2.00m,
+  Bus b when ((double)b.Riders / (double)b.Capacity) > 0.90 => 5.00m - 1.00m,
+  Bus b => 5.00m,
+  DeliveryTruck t when (t.GrossWeightClass > 5000) => 10.00m + 5.00m,
+  DeliveryTruck t when (t.GrossWeightClass < 3000) => 10.00m - 2.00m,
+  DeliveryTruck t => 10.00m,
+  {} => -1, //throw new ArgumentException(message: ""Not a known vehicle type"", paramName: nameof(vehicle)),
+  null => 0 //throw new ArgumentNullException(nameof(vehicle))
+};";
+            TestNormalizeStatement(a, b);
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs:78]: is thre a test that shows where the braces go if the parent is indented?

Comment (bernd5) [reply src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs:106]: Yes, always new line - like for if, while...

**Comment by bernd5** [comment]
Why do those "telemetry tests" fail?

**Comment by bernd5** [comment]
@CyrusNajmabadi could you have a look?

**Comment by Youssef1313** [comment]
@bernd5 Are you working on Linux? I think you'll need to replace Linux line endings (`\n`) with Windows line endings (`\r\n`)

**Comment by bernd5** [comment]
No, I use Windows and on my machine everything looks fine - all tests passed

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs [hunk 2]
```diff
@@ -16,6 +16,142 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+  }
+
+  if (x is System.ValueTuple<int, int> (_, _) { Item1: > 10 } t3)
+  {
+  }
+
+  if (x is System.ValueTuple<int, int> (_, _) { Item1: > 10, Item2: < 20 })
+  {
+  }
+}"
```
Comment (Youssef1313) [inline src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs:61]: Can you try calling [NormalizeLineEndings](https://github.com/dotnet/roslyn/blob/315c2e149ba7889b0937d872274c33fcbfe9af5f/src/Compilers/Test/Core/FX/StringExtensions.cs#L17-L25) on the expected output for failing tests?

```suggestion
}".NormalizeLineEndings()
```

Comment (bernd5) [reply src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs:61]: I added NormalizeLineEndings() but should work without it...

**Comment by bernd5** [comment]
@333fred or @CyrusNajmabadi could you review this PR, please?

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs [hunk 3]
```diff
@@ -91,17 +64,7 @@ public void TestNormalizeSwitchRecPattern()
...
-  int { } => ""two"",
-  { } t when t.GetHashCode() == 42 => ""42"",
-  System.ValueTuple<int, int> (1, _) { Item2: > 2 and < 20 } => ""tuple.Item2 < 20"",
-  System.ValueTuple<int, int> (1, _) { Item2: >= 100 } greater => greater.ToString(),
-  System.ValueType { } => ""not null value"",
-  object { } i when i is not 42 => ""not 42"",
-  { } => ""not null"",
-  null => ""null"",
-};"
+                "var x = (object)1 switch\r\n{\r\n  int { } => \"two\",\r\n  { } t when t.GetHashCode() == 42 => \"42\",\r\n  System.ValueTuple<int, int> (1, _) { Item2: > 2 and < 20 } => \"tuple.Item2 < 20\",\r\n  System.ValueTuple<int, int> (1, _) { Item2: >= 100 } greater => greater.ToString(),\r\n  System.ValueType { } => \"not null value\",\r\n  object { } i when i is not 42 => \"not 42\",\r\n  { } => \"not null\",\r\n  null => \"null\",\r\n};"
```
Comment (Youssef1313) [inline src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs:67]: I personally don't see this form readable. Keeping it as verbatim string with NormalizeLineEndings called improves its readability a lot. But let the team decide.

Comment (bernd5) [reply src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs:67]: Yes, I prefer verbatim strings, too. But on the Ubuntu machine it causes errors...

Comment (Youssef1313) [reply src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs:67]: @bernd5 It shouldn't cause any problems if you call `NormalizeLineEndings` on the "expected" argument. The failures you saw in [this run](https://github.com/dotnet/roslyn/runs/2370918006) are unrelated. They are known flakiness issues.

Comment (bernd5) [reply src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs:67]: But shouldn't it work without NormalizeLineEndings()?

Comment (Youssef1313) [reply src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs:67]: @bernd5 The verbatim string seems to have different line endings on Windows vs Linux builds. I don't know the reason unfortunately.

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs [hunk 4]
```diff
@@ -220,6 +220,10 @@ private int LineBreaksAfter(SyntaxToken currentToken, SyntaxToken nextToken)
                     return LineBreaksAfterCloseBrace(currentToken, nextToken);
 
                 case SyntaxKind.CloseParenToken:
+                    if (currentToken.Parent is PositionalPatternClauseSyntax)
+                    {
+                        return 0;
+                    }
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs:226]: i'd like a comment here explaining what's going on.

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs [hunk 5]
```diff
@@ -391,6 +397,118 @@ private static int LineBreaksAfterSemicolon(SyntaxToken currentToken, SyntaxToke
             }
         }
 
+        private static bool? TryNeedsSeparatorForPropertyPattern(SyntaxToken token, SyntaxToken next)
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs:400]: doc waht the tri-state means here.

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs [hunk 6]
```diff
@@ -391,6 +397,118 @@ private static int LineBreaksAfterSemicolon(SyntaxToken currentToken, SyntaxToke
...
+        {
+            PropertyPatternClauseSyntax? propPattern =
+                token.Parent as PropertyPatternClauseSyntax ??
+                next.Parent as PropertyPatternClauseSyntax;
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs:404]: can you do this as kind checks first.  type checks can be expensive, and based on how this function is shaped, it looks like you do this for all pairs of tokens?

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs [hunk 7]
```diff
@@ -16,6 +16,87 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+                {
+                }
+                if (x is System.ValueTuple<int, int>(_, _) { Item1: > 10 } t3)
+                {
+                }
+                if (x is System.ValueTuple<int, int>(_, _) { Item1: > 10, Item2: < 20 })
+                {
+                }
+}",
+                "{\r\n  object x = 1;\r\n  if (x is { })\r\n  {\r\n  }\r\n\r\n  if (x is { } t)\r\n  {\r\n  }\r\n\r\n  if (x is int { } t2)\r\n  {\r\n  }\r\n\r\n  if (x is System.ValueTuple<int, int> (_, _) { Item1: > 10 } t3)\r\n  {\r\n  }\r\n\r\n  if (x is System.ValueTuple<int, int> (_, _) { Item1: > 10, Item2: < 20 })\r\n  {\r\n  }\r\n}"
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs:40]: this is really hard to read.  can you please just put in normal newlines?

Comment (bernd5) [reply src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs]: An ubuntu build issued an error - that was the reason...
But I do not like it, too.

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs (hunk 4 above)
Comment (bernd5) [reply src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs:227]: comment added

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs (hunk 5 above)
Comment (bernd5) [reply src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs]: I removed that...

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs (hunk 6 above)
Comment (bernd5) [reply src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs]: I changed it to IsKind calls...

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs (hunk 7 above)
Comment (bernd5) [reply src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs]: Yes, on a (ubuntu) machine it failed because of "\r\n" vs. "\n"...

Comment (bernd5) [reply src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs]: But I reverted that

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs [hunk 8]
```diff
@@ -391,6 +398,132 @@ private static int LineBreaksAfterSemicolon(SyntaxToken currentToken, SyntaxToke
...
 
+        private static bool NeedsSeparatorForPropertyPattern(SyntaxToken token, SyntaxToken next)
+        {
+            PropertyPatternClauseSyntax? propPattern;
+            if (token.Parent.IsKind(SyntaxKind.PropertyPatternClause))
+            {
+                propPattern = (PropertyPatternClauseSyntax)token.Parent;
+            }
+            else
+            if (next.Parent.IsKind(SyntaxKind.PropertyPatternClause))
```
Comment (Youssef1313) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs:409]:
```suggestion
            else if (next.Parent.IsKind(SyntaxKind.PropertyPatternClause))
```

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs [hunk 9]
```diff
@@ -391,6 +398,132 @@ private static int LineBreaksAfterSemicolon(SyntaxToken currentToken, SyntaxToke
...
+
+        private static bool NeedsSeparatorForPositionalPattern(SyntaxToken token, SyntaxToken next)
+        {
+            PositionalPatternClauseSyntax? posPattern;
+            if (token.Parent.IsKind(SyntaxKind.PositionalPatternClause))
+            {
+                posPattern = (PositionalPatternClauseSyntax)token.Parent;
+            }
+            else
+            if (next.Parent.IsKind(SyntaxKind.PositionalPatternClause))
```
Comment (Youssef1313) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs:470]:
```suggestion
            else if (next.Parent.IsKind(SyntaxKind.PositionalPatternClause))
```

**Comment by bernd5** [comment]
Anything to add or change?

**Comment by bernd5** [comment]
Something to add or change?

**Comment by bernd5** [comment]
@jaredpar could you review this PR - or who is responsible?

**Comment by jaredpar** [comment]
@dotnet/roslyn-compiler PTAL at this community PR.

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs (hunk 6 above)
Comment (333fred) [reply src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs]: Neal and @agocke did benchmarks on this a year or two ago, and it actually was not super significant (half a nanosecond or so, which basically vanished when you actually do the cast afterwards).

Comment (333fred) [reply src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs]: I'd prefer, for this `if/else` chain, we just did a switch statement with type tests and return in default.

Comment (333fred) [reply src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs]: Actually, I suppose it would be cleaner to just do what you had originally, with the `as` expressions. Not super important if you want to leave it as is, but with only two `as` type tests it's not a perf concern.

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs [hunk 10]
```diff
@@ -391,6 +398,130 @@ private static int LineBreaksAfterSemicolon(SyntaxToken currentToken, SyntaxToke
...
+                    }
+                }
+            }
+            return false;
+        }
+
+        private static bool NeedsSeparatorForPositionalPattern(SyntaxToken token, SyntaxToken next)
+        {
+            PositionalPatternClauseSyntax? posPattern;
+            if (token.Parent.IsKind(SyntaxKind.PositionalPatternClause))
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs:464]: Same comment about `IsKind` followed by a cast on two nodes vs `as` not being a perf concern.

**Review by 333fred — APPROVED** [review]
LGTM (commit 25), other than the minor comments on `as` vs `IsKind` checks.

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs (hunk 10 above)
Comment (bernd5) [reply src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs:464]: `PositionalPatternClauseSyntax` is a `sealed` class - so I think the `is` check should just do a null check and a comparison of the VMT pointer. With IsKind we compare simply the stored integer and omit the null check. The performance difference should be not that big.
For non-sealed classes it pays maybe a perfomance penalty.
But for those we can't do a simple IsKind check (e.g. Statement Syntax).

Comment (bernd5) [reply src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs:464]: I have seen that there are still some issues. E.g. `Foo() swtich { ...}` is normalized to `Foo()swtich { ...}`.
Or property-initializers are not normalized well - all in a single line - which is fine for collection initializers.

But those changes I would put in another PR.

**Comment by 333fred** [comment]
@dotnet/roslyn-compiler for a second review.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 25)

**Comment by jcouv** [comment]
Merged/squashed. Thanks @bernd5!
