### PR TITLE
Fixed IDE0009 suggestion in nameof expression used to initialize static member

### LINKED ISSUE #21519: IDE0009 suggested incorrectly in nameof expression used to initialize static member in VS 15.3
**Version Used**: VS2017 15.3.0

**Steps to Reproduce**:
1. Open `Opetions`, show `Text Editor -> C# -> Code Style -> General` tab, set `Qualify property access with 'this'` option to `Prefer 'this.'`
2. Create Visual C# Console App Project
3. Copy and paste following code:
```cs
class Program
{
    public int Foo { get; set; }
    public static string Bar = nameof(Foo); // IDE0009 "Add 'this' or 'Me' qualification." suggested here

    static void Main(string[] args)
    {
    }
}
```

**Expected Behavior**:
IDE0009 is not suggested.

**Actual Behavior**:
IDE0009 is suggested.
If I add "this" qualification, I get CS0026 `Keyword 'this' is not valid in a static property, static method, or static field initializer`.

I encountered this issue in real project, which uses Dependency Property: 
```cs
using System.Windows;
class SomeClass : DependencyObject
{
    public bool IsExpanded
    {
        get => (bool)this.GetValue(IsExpandedProperty);
        set => this.SetValue(IsExpandedProperty, value);
    }

    public static readonly DependencyProperty IsExpandedProperty = DependencyProperty.Register(
        nameof(IsExpanded), // IDE0009 suggested here
        typeof(bool),
        typeof(SomeClass),
        new PropertyMetadata(false));
}
```

### PR DESCRIPTION
**Pull request by zaytsev-victor**
**Customer scenario**
IDE0009 suggested incorrectly in nameof expression used to initialize static member in VS 15.3

**Bugs this fixes:**
Fixes #21519

**Risk**
Low

**Performance impact**
Low

**How was the bug found?**
customer reported

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/QualifyMemberAccess/QualifyMemberAccessTests.cs [hunk 1]
```diff
@@ -1096,5 +1096,52 @@ class Derived : Base
...
+
+        [WorkItem(21519, "https://github.com/dotnet/roslyn/issues/21519")]
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsQualifyMemberAccess)]
+        public async Task DoNotReportToQualify_IfInStaticContext1()
+        {
+            await TestMissingAsyncWithOption(
+@"class Program
+{
+    public int Foo { get; set; }
+    public static string Bar = nameof([|Foo|]);
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/QualifyMemberAccess/QualifyMemberAccessTests.cs]: :bulb: Can we get another test with `Bar` not being static?

```csharp
public string Bar = nameof(Foo);
```

Comment (zaytsev-victor) [inline src/EditorFeatures/CSharpTest/QualifyMemberAccess/QualifyMemberAccessTests.cs]: Done.

File: src/EditorFeatures/CSharpTest/QualifyMemberAccess/QualifyMemberAccessTests.cs [hunk 2]
```diff
@@ -1096,5 +1096,70 @@ class Derived : Base
...
+            await TestMissingAsyncWithOption(
+@"class Program
+{
+    public int Foo { get; set; }
+    static void Main(string[] args)
+    {
+        System.Console.WriteLine(nameof([|Foo|]));
+    }
+}",
+CodeStyleOptions.QualifyEventAccess);
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/QualifyMemberAccess/QualifyMemberAccessTests.cs]: is this the right option?

File: src/EditorFeatures/CSharpTest/QualifyMemberAccess/QualifyMemberAccessTests.cs [hunk 3]
```diff
@@ -1096,5 +1096,70 @@ class Derived : Base
...
+{
+    public int Foo { get; set; }
+    static string Bar { get; set; }
+
+    static Program()
+    {
+        Bar = nameof([|Foo|]);
+    }
+}",
+CodeStyleOptions.QualifyEventAccess);
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/QualifyMemberAccess/QualifyMemberAccessTests.cs]: right option?

File: src/EditorFeatures/CSharpTest/QualifyMemberAccess/QualifyMemberAccessTests.cs [hunk 4]
```diff
@@ -1143,5 +1143,23 @@ static Program()
...
+            await TestAsyncWithOption(
+@"class Program
+{
+    public int Foo { get; set; }
+    public string Bar = nameof([|Foo|]);
+}",
+@"class Program
+{
+    public int Foo { get; set; }
+    public string Bar = nameof(this.Foo);
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/QualifyMemberAccess/QualifyMemberAccessTests.cs]: ❗️ This is an error (CS0027).

Comment (zaytsev-victor) [inline src/EditorFeatures/CSharpTest/QualifyMemberAccess/QualifyMemberAccessTests.cs]: @sharwell I've fixed it, but I found another issue.
I this case:
```csharp
public class C
    {
        public int Foo { get; set; }
        public string Bar { get => nameof(Foo); }
    }
```
```CSharpQualifyMemberAccessDiagnosticAnalyzer``` doesn't even analyze it (so there isn't IDE0009 suggestion here).
Should it be fixed in this PR or I should file a separate issue?

Comment (Pilchie) [inline src/EditorFeatures/CSharpTest/QualifyMemberAccess/QualifyMemberAccessTests.cs]: @sharwell is on vacation and may not get a chance to look at this. @CyrusNajmabadi can you?

Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/QualifyMemberAccess/QualifyMemberAccessTests.cs]: @zaytsev-victor Fix if easy.  If not, open new issue.  Thanks!

**Comment by zaytsev-victor** [comment]
In case:
```csharp
public class C
{
    public int Foo { get; set; }
    public string Bar { get => nameof(Foo); }
}
```
Get accessor doesn't have body and ```GetDeclarationInfo``` doesn't create declaration info for this node and analyzer doesn't even run in this case, so we should pass ```ExpressionBody``` if ```Body``` is ```null```.

File: src/Compilers/CSharp/CSharpAnalyzerDriver/CSharpDeclarationComputer.cs [hunk 5]
```diff
@@ -183,7 +183,7 @@ private static bool InvalidLevel(int? level)
                 case SyntaxKind.GetAccessorDeclaration:
                     {
                         var t = (AccessorDeclarationSyntax)node;
-                        builder.Add(GetDeclarationInfo(model, node, getSymbol, t.Body, cancellationToken));
+                        builder.Add(GetDeclarationInfo(model, node, getSymbol, t.Body ?? (SyntaxNode)t.ExpressionBody, cancellationToken));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/CSharpAnalyzerDriver/CSharpDeclarationComputer.cs]: >t.Body ?? (SyntaxNode)t.ExpressionBody [](start = 79, length = 38)

Is there a test that demonstrate significance of this change? Also, looking at the code below (for SyntaxKind.MethodDeclaration, etc.), we should probably concatenate Body and ExpressionBody when both are present.

**Comment by AlekseyTs** [comment]
Done with review pass for Compilers.

File: src/Compilers/CSharp/CSharpAnalyzerDriver/CSharpDeclarationComputer.cs (hunk 5 above)
Comment (zaytsev-victor) [reply src/Compilers/CSharp/CSharpAnalyzerDriver/CSharpDeclarationComputer.cs]: @AlekseyTs ```AccessorDeclarationSyntax``` can't have Body and ExpressionBody at the same time.
Regarding to SyntaxKind.MethodDeclaration case I assume that the only one reason of using concatenation is passing list of parameters with Body or ExpressionBody.

Comment (AlekseyTs) [reply src/Compilers/CSharp/CSharpAnalyzerDriver/CSharpDeclarationComputer.cs]: > AccessorDeclarationSyntax can't have Body and ExpressionBody at the same time.

I think it can. This doesn't mean the program is valid, but it looks like both can present at the same time. You can try to add a test for a method, see what happens and then test similar scenario for an accessor. I would expect to observe similar behavior.

File: src/Compilers/CSharp/CSharpAnalyzerDriver/CSharpDeclarationComputer.cs [hunk 6]
```diff
@@ -183,7 +183,15 @@ private static bool InvalidLevel(int? level)
                 case SyntaxKind.GetAccessorDeclaration:
                     {
                         var t = (AccessorDeclarationSyntax)node;
-                        builder.Add(GetDeclarationInfo(model, node, getSymbol, t.Body, cancellationToken));
+                        if (t.Body != null && t.ExpressionBody != null)
```
Comment (cston) [inline src/Compilers/CSharp/CSharpAnalyzerDriver/CSharpDeclarationComputer.cs]: Please add a test for this case if possible. Perhaps: `object P { get { return null; } => null; }`.

File: src/Compilers/CSharp/CSharpAnalyzerDriver/CSharpDeclarationComputer.cs [hunk 7]
```diff
@@ -183,7 +183,15 @@ private static bool InvalidLevel(int? level)
...
+                        {
+                            builder.Add(GetDeclarationInfo(model, node, getSymbol, new SyntaxNode[] { t.Body, t.ExpressionBody }, cancellationToken));
+                        }
+                        else
+                        {
+                            builder.Add(GetDeclarationInfo(model, node, getSymbol, t.Body ?? (SyntaxNode) t.ExpressionBody, cancellationToken));
+                        }
```
Comment (cston) [inline src/Compilers/CSharp/CSharpAnalyzerDriver/CSharpDeclarationComputer.cs]: Consider merging the two code paths.
```
var blocks = ArrayBuilder<SyntaxNode>.GetInstance();
if (t.Body != null)
{
    blocks.Add(t.Body);
}
if (t.ExpressionBody != null)
{
    blocks.Add(t.ExpressionBody);
}
builder.Add(GetDeclaration(model, node, getSymbol, blocks, cancellationToken);
blocks.Free();
```

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-ide, Is it Ok to merge this PR?

File: src/Features/CSharp/Portable/QualifyMemberAccess/CSharpQualifyMemberAccessDiagnosticAnalyzer.cs [hunk 8]
```diff
@@ -15,7 +17,21 @@ protected override bool IsAlreadyQualifiedMemberAccess(SyntaxNode node)
             => node.IsKind(SyntaxKind.ThisExpression);
 
         // If the member is already qualified with `base.`, it cannot be further qualified.
-        protected override bool CanMemberAccessBeQualified(SyntaxNode node)
-            => !node.IsKind(SyntaxKind.BaseExpression);
+        protected override bool CanMemberAccessBeQualified(ISymbol containingSymbol, SyntaxNode node)
+            => !(node.IsKind(SyntaxKind.BaseExpression) || IsInPropertyOrFieldInitialization(containingSymbol, node));
+
+        private bool IsInPropertyOrFieldInitialization(ISymbol containingSymbol, SyntaxNode node)
```
Comment (sharwell) [inline src/Features/CSharp/Portable/QualifyMemberAccess/CSharpQualifyMemberAccessDiagnosticAnalyzer.cs]: 💭 I'm a bit concerned about the performance implications of this. However, when I went to investigate how [`ThisKeywordRecommender`](https://github.com/dotnet/roslyn/blob/master/src/Features/CSharp/Portable/Completion/KeywordRecommenders/ThisKeywordRecommender.cs) implemented the same feature, I found a bug. I'll file a bug to find a better way to implement this check and unify this analyzer and `ThisKeywordRecommender` to use it.
