### PR TITLE
Fix with-element indentation in collection expressions on multiple lines

### LINKED ISSUE #83029: "with" element is not correctly indented when converting collection initializer
**Version Used**: VS 18.4.2

**Steps to Reproduce**:
Place the caret on the "new" token and invoke the codefix for IDE0028.
```csharp
HashSet<string> h = new(StringComparer.Ordinal)
{
    "a",
    "b"
};
```

**Diagnostic Id**: IDE0028: Collection initialization can be simplified

**Expected Behavior**:
The "with" element is correctly indented.
```csharp
HashSet<string> h =
[
    with(StringComparer.Ordinal),
    "a",
    "b"
];
```

**Actual Behavior**:
The "with" element has no leading whitespace on its line.

```csharp
HashSet<string> h =
[
with(StringComparer.Ordinal),
    "a",
    "b"
];
```

Image

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/83029

Should be read commit by commit.

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/roslyn/pull/83030)

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@JoeRobich ptal.

**Comment by CyrusNajmabadi** [comment]
@JoeRobich @dibarbet @akhera99 ptal.

File: src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests_CollectionExpression.cs [hunk 1]
```diff
@@ -6115,6 +6115,49 @@ void M()
             }
             """);
 
+    [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/83029")]
+    public Task TestWithOverMultipleLines()
```
Comment (akhera99) [inline src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests_CollectionExpression.cs]: Not a blocker, can you add a test where the HashSet constructor arguments are multi-line?

**Review by akhera99 — APPROVED** [review]

File: src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests_CollectionExpression.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests_CollectionExpression.cs]: done.
