### PR TITLE
Do not report IDE1005 on function pointer invocations

### LINKED ISSUE #50976: Function pointers shouldn't trigger IDE1005 (Delegate invocation can be simplified)
**Version Used**: 
VS 16.9 Preview 3

**Steps to Reproduce**:

Define a function pointer as a member:

```csharp
public delegate* managed<in Instance, void> FunctionPtr { get; init; }
```

Then use this:

```csharp
if (FunctionPtr != null)
{
    FunctionPtr(this);
}
```

**Expected Behavior**:

Because of function pointer, IDE1005 shouldn't report on this scenario.

**Actual Behavior**:
IDE1005 raised, and suggest us to change the code to `FunctionPtr?.Invoke(this)`.

### PR DESCRIPTION
**Pull request by jhinder**
Fixes #50976.

### CODE REVIEW

File: src/Analyzers/CSharp/Analyzers/InvokeDelegateWithConditionalAccess/InvokeDelegateWithConditionalAccessAnalyzer.cs [hunk 1]
```diff
@@ -87,6 +87,12 @@ private void SyntaxNodeAction(SyntaxNodeAnalysisContext syntaxContext)
                 return;
             }
 
+            // Function pointers can only be invoked directly via the "()" operator, not "?.Invoke()".
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/InvokeDelegateWithConditionalAccess/InvokeDelegateWithConditionalAccessAnalyzer.cs:90]: @333fred i'm curious why that is.  is there no `check for null and invoke` idiom for function pointers?

**Review by CyrusNajmabadi — APPROVED** [review]
