### PR TITLE
Fix RemoveUnusedMembers handling of default parameter reads

### LINKED ISSUE #63892: IDE Usage Analysis Does Not Account for Lambda Default Parameters
```csharp
class C
{
    const int N = 10;
    void M()
    {
        var lam = (int x = N) => x;
    }
}
```
In the following case, `N` is shown as unused in the IDE, when its usage as a default parameter value for the lambda should be tracked. We are already removing unused variable warnings when they occur for local constants used as default parameter values for lambdas and local functions in the compiler: #63850

### PR DESCRIPTION
**Pull request by molostovvs**
fixes #63892

- treat parameter default value expressions as symbol reads inside lambdas and local funcs
- add related test cases

### CODE REVIEW

File: src/Analyzers/CSharp/Tests/RemoveUnusedMembers/RemoveUnusedMembersTests.cs [hunk 1]
```diff
@@ -822,6 +822,100 @@ public void M()
...
+    [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/63892")]
+    public async Task FieldIsRead_LambdaDefaultParameter()
+    {
+        var code = """
+            class MyClass
+            {
+                private const int _goo = 42;
+                public void M()
+                {
+                    var lam = (int x = _goo) => x;
```
Comment (DoctorKrolic) [inline src/Analyzers/CSharp/Tests/RemoveUnusedMembers/RemoveUnusedMembersTests.cs:834]: Add test with `delegate (int x = _goo) { }`

Comment (molostovvs) [reply src/Analyzers/CSharp/Tests/RemoveUnusedMembers/RemoveUnusedMembersTests.cs]: This results in [error CS1065](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1065)

Comment (molostovvs) [reply src/Analyzers/CSharp/Tests/RemoveUnusedMembers/RemoveUnusedMembersTests.cs]: @DoctorKrolic 
Hi! Can you please come back with a review?

File: src/Analyzers/CSharp/Tests/RemoveUnusedMembers/RemoveUnusedMembersTests.cs [hunk 2]
```diff
@@ -822,6 +822,100 @@ public void M()
...
+            }
+            """;
+
+        await new VerifyCS.Test
+        {
+            TestCode = code,
+            FixedCode = code,
+            LanguageVersion = LanguageVersion.CSharp12,
+        }.RunAsync();
+    }
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/RemoveUnusedMembers/RemoveUnusedMembersTests.cs:917]: can you add a test like so:  `var lam = (int x = _goo + _bar) => x + y;`

also `var lam = (int x = MyClass._goo) => x;`

thanks!

**Comment by CyrusNajmabadi** [comment]
Thanks @molostovvs !
