### PR TITLE
Fix for introduce local variable bugs

### LINKED ISSUE #40374: Introduce local can introduce local in wrong place with local functions
Steps to reproduce:
1. Original code:
```C#
    class Bug
    {
        void M(int i)
        {
            Local();
            var x = Foo();

            void Local()
            {
                var y = Foo();
            }
        }

        private static object Foo()
        {
            throw new NotImplementedException();
        }
    }
```

2. Highlight 'Foo()' within local function and apply code action to introduce local for all occurrences of 'Foo()'

3. Expected:
```C#
    class Bug
    {
        void M(int i)
        {
            object v = Foo();
            Local();
            var x = v;

            void Local()
            {
                var y = v;
            }
        }

        private static object Foo()
        {
            throw new NotImplementedException();
        }
    }
```
Actual:
```C#
    class Bug
    {
        void M(int i)
        {
            Local();
            object v = Foo();
            var x = v;

            void Local()
            {
                var y = v;
            }
        }

        private static object Foo()
        {
            throw new NotImplementedException();
        }
    }
```
The actual output is invalid code.

Furthermore, the following code also fails:
```C# void M()
{
    // Must put it up here, above Local()
    void Local()
    {
        int x = Foo();
    }

    // Can't put it here, even though it's before all calls to Local()
    int y = Foo();
    Local();
}
```

In short, there should be two conditions on where to place the new local declaration:
1) Before all calls to local functions that use the variable.
2) Before the local function itself.

(Thanks to @dpoeschl for originally catching this and for outlining the two conditions!)

### LINKED ISSUE #40381: Introduce local tries to introduce across static local functions
Steps to reproduce:
1) With the following code, highlight ```Foo()``` of ``` var x = Foo();``` and apply code action to introduce local across all occurrences:

```C#
    class Bug
    {
        void M(int i)
        {
            Local();
            static void Local()
            {
                var y = Foo();
            }

            var x = Foo();
        }

        private static object Foo()
        {
            throw new NotImplementedException();
        }
    }
```
2) Expected:
```C#
    class Bug
    {
        void M(int i)
        {
            Local();
            static void Local()
            {
                var y = Foo();
            }

            var v = Foo();
            var x = v;
        }
```
3) Actual:
```C#
    class Bug
    {
        void M(int i)
        {
            Local();
            var v = Foo();

            static void Local()
            {
                var y = v;
            }

            var x = v;
        }
```

### PR DESCRIPTION
**Pull request by allisonchou**
Fixes #40374 and fixes #40381 and adds applicable tests.

### CODE REVIEW

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService.cs [hunk 1]
```diff
@@ -146,6 +146,12 @@ protected override bool CanReplace(ExpressionSyntax expression)
             return true;
         }
 
+        protected override bool IsExpressionInStaticLocalFunction(ExpressionSyntax expression)
+        {
+            var localFunction = expression.GetAncestor<LocalFunctionStatementSyntax>();
+            return localFunction != null && localFunction.Modifiers.Any(modifier => modifier.IsKind(SyntaxKind.StaticKeyword));
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService.cs]: `localFunction.Modifiers.Any(SyntaxKind.StaticKeyword)`

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs [hunk 2]
```diff
@@ -259,6 +259,49 @@ private static SyntaxNode WithBlockBody(SyntaxNode node, BlockSyntax body)
...
+            if (localFunctions.IsEmpty())
+            {
+                return firstStatementAffectedIndex;
+            }
+
+            var localFunctionIdentifiers = localFunctions.Select(node => ((LocalFunctionStatementSyntax)node).Identifier.ValueText);
+
+            // Find all calls to the applicable local functions within the scope.
+            var localFunctionCalls = innermostCommonBlock.DescendantNodes().Where(node => node is InvocationExpressionSyntax invocationExpression &&
+                                                                                  localFunctionIdentifiers.Contains(invocationExpression.Expression.GetRightmostName().Identifier.ValueText));
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: this is inaccurate.  For example, `this.localName()` will show up for you as a call to a local function `localName` using this logic.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: `GetRightmostName` can return null in lots of legal cases.  for example `(foo)(arg1, arg2)`  this will crash.

Comment (allisonchou) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: Got it, thank you for the catch! Updated. 👍

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs [hunk 3]
```diff
@@ -259,6 +259,51 @@ private static SyntaxNode WithBlockBody(SyntaxNode node, BlockSyntax body)
...
+                return firstStatementAffectedIndex;
+            }
+
+            // Find which call is the earliest.
+            var earliestLocalFunctionCall = localFunctionCalls.Min(node => node.SpanStart);
+
+            var statementsInBlock = GetStatements(innermostCommonBlock);
+
+            // Check if our earliest call is before all local function declarations and all matches, and if so, place our new declaration there.
+            var statement = statementsInBlock.Where(s => s.Span.Contains(earliestLocalFunctionCall)).Single();
```
Comment (JoeRobich) [inline src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: Instead of `.Where()` you could use `.IndexOf()` to find the index of the earliest call. Since the statement itself isn't being used here.
