### PR TITLE
Delay pointer managed type check on type members until after binding

### LINKED ISSUE #37051: Compiler crash when overriding method that returns a generic pointer
**Version Used**: 

3.100.19.26603 (9d80dea7)

**Steps to Reproduce**:

1. Create a base class with an abstract method that returns a `T*` (of course `where T : unmanaged`).
2. Create a derived class that overrides that method.

Or you can just compile a .cs file with this code:

```cs
using System;

public unsafe abstract class Base
{
    public abstract T* Alloc<T>()
        where T : unmanaged;
}

public unsafe class Derived : Base
{
    public override T* Alloc<T>()
    {
        throw new NotImplementedException();
    }
}
```

**Expected Behavior**:

The compiler should accept this program (if it is correct) or print a diagnostic (if it is incorrect).

**Actual Behavior**:

The compiler crashes. When used from Visual Studio, the IDE abruptly shuts down. When used from VS Code, the editor shows the text `!!MISSING: command!!` above the offending methods.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Fixes #37051 by delaying the CheckManagedAddr check on pointers in type members until after type members are bound. Here is the scenario fixed by this change:

```cs
public unsafe class A
{
    public virtual T* M<T>() where T : unmanaged => throw null!;
}

public unsafe class B : A
{
    // before this we would crash when checking the unmanaged constraint on `T*`
    public override T* M<T>() => throw null!;
}
```

Similar to other scenarios where we delay constraint checking, this change makes it impossible to detect the illegal usage of a pointer type a la the following:

```cs
class A { public class B { } }
class C<T> : A { }

class Test
{
    // today this gives ErrorCode.ERR_ManagedAddr,
    // but in post-binding checks the type is seen as `A.B` so there's nothing to error about
    C<object*>.B f;
}
```

The fact that `Test.f` resolves to type `A.B` can be verified in the IL produced by this compiler:
```cil
.class private auto ansi beforefieldinit Test
	extends [mscorlib]System.Object
{
	// Fields
	.field private class A/B f

        // constructor, etc...

} // end of class Test
```

### CODE REVIEW

**Comment by RikkiGibson** [comment]
not sure why CI is not kicking. Will try marking the PR as ready for review.

**Comment by RikkiGibson** [comment]
Could I please get a review? @dotnet/roslyn-compiler

File: src/Compilers/CSharp/Test/Semantic/Semantics/UnsafeTests.cs [hunk 1]
```diff
@@ -3077,13 +3077,13 @@ public struct C
             CreateCompilation(text, options: TestOptions.UnsafeReleaseDll).VerifyDiagnostics(
                 // (13,20): error CS0208: Cannot take the address of, get the size of, or declare a pointer to a managed type ('A')
                 //             public A*[,][] aa; //CS0208
-                Diagnostic(ErrorCode.ERR_ManagedAddr, "A*").WithArguments("A"),
+                Diagnostic(ErrorCode.ERR_ManagedAddr, "aa").WithArguments("A"),
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/UnsafeTests.cs]: >aa [](start = 55, length = 2)

Should the error be reported on the type rather than the field name?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/UnsafeTests.cs]: It would be nice if we could do this but it's tricky as we discussed offline.

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler Could I get a second review on a small bug fix please?

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 2]
```diff
@@ -1208,17 +1208,17 @@ private BoundExpression BindSizeOf(SizeOfExpressionSyntax node, DiagnosticBag di
...
             if (managedKind == ManagedKind.Managed)
             {
-                diagnostics.Add(ErrorCode.ERR_ManagedAddr, node.Location, type);
+                diagnostics.Add(ErrorCode.ERR_ManagedAddr, location, type);
                 return true;
             }
             else if (managedKind == ManagedKind.UnmanagedWithGenerics)
             {
-                var supported = CheckFeatureAvailability(node, MessageID.IDS_FeatureUnmanagedConstructedTypes, diagnostics);
+                var supported = CheckFeatureAvailability(MessageID.IDS_FeatureUnmanagedConstructedTypes, diagnostics, location);
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: This is gonna conflict with my PR where I remove the ability to check for feature availability using a location: https://github.com/dotnet/roslyn/pull/37513

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: Ok, how would you like to proceed? I can merge master into this after 37513 gets merged and handle it if you’d like.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: I merged master in, but since master hasn't flowed to 16.4-preview1 yet, the fix from 37513 will continue to show in here for a little while.

**Comment by RikkiGibson** [comment]
Ping @dotnet/roslyn-compiler

**Comment by RikkiGibson** [comment]
The diff in this PR was refusing to simplify Andy's work out so I just merged the base branch in, committed the head version of all the files directly off of the base branch and force pushed. Nothing has actually changed.

**Comment by gafter** [comment]
We should probably make an issue corresponding to the deleted tests (situations where we fail to check constraints) and then close it as will not fix with an explanation.  That will help leave breadcrumbs in the future in case that issue is reported.

**Comment by RikkiGibson** [comment]
Created #37773
