### PR TITLE
Use more accurate assert condition in BuildMembersAndInitializers.

### LINKED ISSUE #2349: Intermittent failure in DiagnosticAnalyzerTests.DiagnosticAnalyzerAllInOne
Assert below fails from time to time.
```
Private Function BuildMembersAndInitializers(diagBag As DiagnosticBag) As MembersAndInitializers
#If DEBUG Then
            Dim threadId = Environment.CurrentManagedThreadId
            Debug.Assert(m_computingMembersThreadId <> threadId)
            Interlocked.CompareExchange(m_computingMembersThreadId, threadId, 0)
#End If 
``` 
Here is the stack trace of the exception:

```
   at System.Diagnostics.TraceInternal.Fail(String message)
   at System.Diagnostics.Debug.Assert(Boolean condition)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.BuildMembersAndInitializers(DiagnosticBag diagBag) in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberContainerTypeSymbol.vb:line 1683
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.GetMembersAndInitializers() in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberContainerTypeSymbol.vb:line 1646
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.get_MemberAndInitializerLookup() in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberContainerTypeSymbol.vb:line 1639
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.GetMembers(String name) in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberContainerTypeSymbol.vb:line 3131
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbolExtensions.FindMember(NamedTypeSymbol container, String symbolName, SymbolKind kind, TextSpan nameSpan, SyntaxTree tree) in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Symbols\NamedTypeSymbolExtensions.vb:line 34
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMethodSymbol.FindSymbolFromSyntax(MethodBaseSyntax syntax, SyntaxTree tree, NamedTypeSymbol container) in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Symbols\Source\SourceMethodSymbol.vb:line 1100
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetDeclaredSymbol(MethodBaseSyntax declarationSyntax, CancellationToken cancellationToken) in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Compilation\SyntaxTreeSemanticModel.vb:line 1032
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetDeclaredSymbol(MethodBlockBaseSyntax declarationSyntax, CancellationToken cancellationToken) in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Compilation\SemanticModel.vb:line 2650
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetDeclaredSymbolCore(SyntaxNode declaration, CancellationToken cancellationToken) in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Compilation\SemanticModel.vb:line 3302
   at Microsoft.CodeAnalysis.SemanticModel.GetDeclarationInfo(SyntaxNode node, Boolean getSymbol, IEnumerable`1 executableCodeBlocks, CancellationToken cancellationToken) in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\Core\Portable\Compilation\SemanticModel.cs:line 839
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.ComputeDeclarationsCore(SyntaxNode node, Func`3 shouldSkip, Boolean getSymbol, ArrayBuilder`1 builder, Nullable`1 levelsToCompute, CancellationToken cancellationToken) in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Compilation\SemanticModel.vb:line 3596
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.ComputeDeclarationsCore(SyntaxNode node, Func`3 shouldSkip, Boolean getSymbol, ArrayBuilder`1 builder, Nullable`1 levelsToCompute, CancellationToken cancellationToken) in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Compilation\SemanticModel.vb:line 3551
   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetDeclarationsInNode(SyntaxNode node, Boolean getSymbol, CancellationToken cancellationToken, Nullable`1 levelsToCompute) in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\VisualBasic\Portable\Compilation\SemanticModel.vb:line 3447
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.<AnalyzeDeclaringReferenceAsync>d__1.MoveNext() in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerDriver.cs:line 1139
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<ProcessEventAsync>d__1.MoveNext() in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerDriver.cs:line 351
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<ProcessEventsAsync>d__1.MoveNext() in C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerDriver.cs:line 319").WithLocation(1, 1)s
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #2349.

@VSadov, @gafter, @agocke, @jaredpar Please review.

### CODE REVIEW

**Comment by gafter** [comment]
Is the idea of this change to catch cases where a problem occurs across multiple threads (where it previously only diagnosed the single-thread problem)?

I'm curious why you wanted to make this change now. Did it help you diagnose an issue recently?

LGTM

**Comment by gafter** [comment]
Oh, I see there is a bug associated with this... what was the problem and how does this fix it?

File: src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberContainerTypeSymbol.vb [hunk 1]
```diff
@@ -1699,44 +1699,53 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols
...
+                        membersAndInitializers.Members.Add(name, StaticCast(Of Symbol).From(typeSymbols))
+                    Else
+                        membersAndInitializers.Members(name) = nontypeSymbols.Concat(StaticCast(Of Symbol).From(typeSymbols))
+                    End If
+                Next
 
 #If DEBUG Then
-            Interlocked.CompareExchange(_computingMembersThreadId, 0, threadId)
+            Finally
+                If added Then
```
Comment (gafter) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberContainerTypeSymbol.vb]: Since we asserted `added` above, mustn't this be true always?

**Comment by AlekseyTs** [comment]
@gafter It is hard to tell what went wrong during the test. We don’t have a reliable repro and the captured call stack doesn’t show reentrancy into BuildMembersAndInitializers on the asserting thread. One theory I have is that an exception was thrown while the function was executing and then the thread was reused before the exception had a chance to bubble up though async layers. I added Try/Finally to eliminate this situation in the future. Another issue with the original assert is that it performs verification only for the first thread among those executing the method concurrently. After the change, verification will be done on all concurrent threads.

File: src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberContainerTypeSymbol.vb (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberContainerTypeSymbol.vb]: We would like it to be true, and the assert there is to verify this assumption, but there is no guarantee. The if statement is there to ensure consistency of the HashSet even when assert is violated and ignored.

**Comment by VSadov** [comment]
LGTM

**Comment by gafter** [comment]
LGTM.
