### PR TITLE
Do not crash when highlighting alias symbols defined via global imports.

### LINKED ISSUE #1904: NRE in GetLocationSpan() of ReferenceHighlightingViewTaggerProvider.TagProvider
Ported from TFS WorkItem: **806504**

------------------------------

**Repro Steps:**

1. Create a VB Project
2. Introduce an [Alias -ed User Imported Namespace](https://msdn.microsoft.com/en-us/library/t4ttw1f9.aspx) through the Project Property page
3. Open a file in the project and reference the Alias.

*Expected* : The identifier to be highlighted

*Actual* : No Highlights

------------------------------

**Revisions:**

1) Created By Balaji Soundrarajan (10/21/2013 3:33:59 PM)

GetLocationSpan in ReferenceHighlightingViewTaggerProvider.TagProvider calls solution.GetDocument(SourceTree) and starts using the document without checking the null references and cases where we would have nulls would be VB Project Property reference (Alias References)

------------------------------

2) Edited By Kevin Pilch-Bisson (2/15/2015 9:13:35 PM)

Move to GitHub in 1.0 milestone.

------------------------------

### PR DESCRIPTION
**Pull request by balajikris**
Fixes #1904 

The crash happens because we try to highlight the definition of this alias symbol, but it does not have a source location. It is defined in the project property pages. We shouldn't try to highlight such definitions. This change addresses that. However, we should still highlight references of that alias symbol and its targets. That is not addressed by this PR, that will be addressed by #2079

### CODE REVIEW

**Comment by balajikris** [comment]
potential reviewers: @basoundr @brettfo @davkean @dpoeschl @Pilchie

File: src/EditorFeatures/Test2/ReferenceHighlighting/VisualBasicReferenceHighlightingTests.vb [hunk 1]
```diff
@@ -272,5 +272,27 @@ End Class
 
             VerifyHighlights(input)
         End Sub
+
+        <WorkItem(1904, "https://github.com/dotnet/roslyn/issues/1904")>
+        <WorkItem(2079, "https://github.com/dotnet/roslyn/issues/2079")>
```
Comment (brettfo) [inline src/EditorFeatures/Test2/ReferenceHighlighting/VisualBasicReferenceHighlightingTests.vb]: If this test doesn't prevent 2079 from regressing then don't add that WorkItem attribute.  Similarly for the comment below.

File: src/EditorFeatures/Core/Implementation/ReferenceHighlighting/AbstractDocumentHighlightsService.cs [hunk 2]
```diff
@@ -130,8 +130,10 @@ private bool ShouldConsiderSymbol(ISymbol symbol)
             bool addAllDefinitions = true;
 
             // Add definitions
+            // Filter out definitions that cannot be highlighted. e.g: alias symbols defined via project property pages.
             if (symbol.Kind == SymbolKind.Alias &&
-                symbol.Locations.Length > 0)
+                symbol.Locations.Length > 0 &&
+                symbol.Locations.First().SourceTree != null)
```
Comment (dpoeschl) [inline src/EditorFeatures/Core/Implementation/ReferenceHighlighting/AbstractDocumentHighlightsService.cs]: If the alias is defined in the project property pages, do we still need to set addAllDefinitions to false below?

File: src/EditorFeatures/Test2/ReferenceHighlighting/VisualBasicReferenceHighlightingTests.vb (hunk 1 above)
Comment (balajikris) [inline src/EditorFeatures/Test2/ReferenceHighlighting/VisualBasicReferenceHighlightingTests.vb]: This test currently addresses the issue in 1904. Once 2079 is fixed, this will start failing. It should be fixed up by adding the {|Reference:symbol|} tags, where symbol denotes the alias symbol or its target. Then it will cover both 1904 and 2079. I cannot possibly make a test that touches 1904 but wont fail after 2079 is addressed. The only other way would be to add the workitem tags and keep this test disabled until 2079 is fixed. Which then opens up the possibility that this will remain disabled.

Comment (brettfo) [inline src/EditorFeatures/Test2/ReferenceHighlighting/VisualBasicReferenceHighlightingTests.vb]: @dpoeschl and I just had a conversation about this and it ultimately comes down to people being in one of two camps:

1.  The attribute should be added to note a relationship, sort of like a cref.
2.  The attribute should be added once the bug is fixed.

David's in camp 1, I'm in 2, but ultimately I don't care really strongly about this either way and I should have prefaced my comment with "nit".

Back on the real issue of your fix, :shipit:

File: src/EditorFeatures/Core/Implementation/ReferenceHighlighting/AbstractDocumentHighlightsService.cs (hunk 2 above)
Comment (balajikris) [inline src/EditorFeatures/Core/Implementation/ReferenceHighlighting/AbstractDocumentHighlightsService.cs]: Ah nice catch! I failed to notice that side-effect flowing through since I get 0 references for now (2079) :smiley: I guess the [`location.IsInSource`](https://github.com/dotnet/roslyn/pull/2085/files#diff-6eed65d33ebfd49a9af243b54de70500R150) check should be sufficient but let me double check and also set it correctly. Thanks.

**Comment by balajikris** [comment]
Looks like jenkins servers were updated with the lightbulb API change. Trying to build by merging latest from dotnet:master.

**Comment by Pilchie** [comment]
:+1:

**Comment by balajikris** [comment]
@dpoeschl addressed your previous comment by making the change suggested.

**Comment by dpoeschl** [comment]
Post-merge :+1:
