### PR TITLE
Fix additional newlines being added when adding all missing imports

### LINKED ISSUE #31768: Add missing usings has extra whitespace
**Version Used**: 
Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.0.0 Preview 1.1 [28407.52.d16.0]

**Steps to Reproduce**:

1. Copy and paste in code that needs usings
2. Apply new codefix that adds missing usings

image

**Expected Behavior**:
There should be only one new line between usings.
image

**Actual Behavior**:
There are two new lines between usings
image

@JoeRobich for reference.

### PR DESCRIPTION
**Pull request by JoeRobich**
Before applying the missing imports remove any additional newlines that are introduced by add import wanting to separate the import from the rest of the code. This only occurs when there are no pre-existing imports.

Fixes #31768

### CODE REVIEW

**Comment by JoeRobich** [comment]
@dotnet/roslyn-ide PTAL

File: src/EditorFeatures/CSharpTest/CodeRefactorings/AddMissingImports/CSharpAddMissingImportsRefactoringProviderTests.cs [hunk 1]
```diff
@@ -336,5 +336,51 @@ public class D { }
...
+}
+
+namespace B
+{
+    public class E { }
+}
+";
+
+            var expected = @"
+using A;
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/CodeRefactorings/AddMissingImports/CSharpAddMissingImportsRefactoringProviderTests.cs]: this newline seems undesirable.

File: src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs [hunk 2]
```diff
@@ -157,6 +158,27 @@ private async Task<Document> ApplyFixesAsync(Document document, ImmutableArray<A
             return newDocument;
         }
 
+        private IEnumerable<TextChange> PrepareTextChangesForInsertion(IGrouping<TextSpan, TextChange> changes)
+        {
+            var first = changes.First();
+            var newLine = first.NewText.EndsWith("\r\n") ? "\r\n" : "\n";
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs]: this feels very skeezy.

File: src/EditorFeatures/CSharpTest/CodeRefactorings/AddMissingImports/CSharpAddMissingImportsRefactoringProviderTests.cs (hunk 1 above)
Comment (JoeRobich) [reply src/EditorFeatures/CSharpTest/CodeRefactorings/AddMissingImports/CSharpAddMissingImportsRefactoringProviderTests.cs]: The logic of the AddImport code fix is to move any leading trivia to the new import statement.

File: src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs [hunk 3]
```diff
@@ -157,6 +158,27 @@ private async Task<Document> ApplyFixesAsync(Document document, ImmutableArray<A
...
+                return changes.OrderBy(change => change.NewText);
+            }
+
+            // This span location had no pre-existing import statements.
+            // We need to compensate for each fix trying to add an additional
+            // newline to separate the imports from the rest of the code.
+            return changes.Select(change =>
+                    new TextChange(changes.Key, change.NewText.TrimEnd('\r', '\n') + newLine)) // Rewrite each text change to only apply a single newline.
+                    .OrderBy(change => change.NewText)                                         // Order to try and give a more correct result.
+                    .Concat(new[] { new TextChange(changes.Key, newLine) });                   // Add the newline intended to separate imports from code.
```
[the remark this answers is not in the document]
Comment (JoeRobich) [reply src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs]: @CyrusNajmabadi Thanks for the suggestion! I've updated the PR using that technique.

File: src/EditorFeatures/CSharpTest/CodeRefactorings/AddMissingImports/CSharpAddMissingImportsRefactoringProviderTests.cs (hunk 1 above)
Comment (JoeRobich) [reply src/EditorFeatures/CSharpTest/CodeRefactorings/AddMissingImports/CSharpAddMissingImportsRefactoringProviderTests.cs]: What is the proposed fix? I think it would probably need to be addressed separate from this PR.

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/CodeRefactorings/AddMissingImports/CSharpAddMissingImportsRefactoringProviderTests.cs]: A using goes at the top of the file, unless there is a banner (i.e. copyright) above it. In which case, it goes after a separate blank line after that banner.

File: src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs [hunk 4]
```diff
@@ -150,13 +153,64 @@ private async Task<Document> ApplyFixesAsync(Document document, ImmutableArray<A
...
+            if (textChanges.Count == 0)
+            {
+                return document;
+            }
+
+            // If there are changes then, this was a case where there were no
+            // previous imports statements. We need to retain the final extra
+            // newline because that separates the imports section from the rest
+            // of the code.
+            textChanges.RemoveAt(textChanges.Count - 1);
```
Comment (mavasani) [inline src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs]: Can we add any assert here that matches your comment above regarding the removed textChange?

File: src/EditorFeatures/CSharpTest/CodeRefactorings/AddMissingImports/CSharpAddMissingImportsRefactoringProviderTests.cs (hunk 1 above)
Comment (sharwell) [reply src/EditorFeatures/CSharpTest/CodeRefactorings/AddMissingImports/CSharpAddMissingImportsRefactoringProviderTests.cs]: I'm fine with the behavior presented here (in this test). If the user didn't want the file to start with a blank line, then the input code would not start with a blank line. By starting with a blank line, the premise for this change request is invalidated.

File: src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs [hunk 5]
```diff
@@ -150,13 +153,64 @@ private async Task<Document> ApplyFixesAsync(Document document, ImmutableArray<A
...
+            // length of the text we are inserting so that we can format the span afterwards.
+            var insertSpans = allTextChanges
+                .GroupBy(change => change.Span)
+                .Select(changes => new TextSpan(changes.Key.Start, changes.Sum(change => change.NewText.Length)));
+
             var text = await document.GetTextAsync(cancellationToken).ConfigureAwait(false);
             var newText = text.WithChanges(orderedTextInserts);
             var newDocument = newProject.GetDocument(document.Id).WithText(newText);
 
+            // When imports are added to a code file that has no previous imports extra
```
Comment (sharwell) [inline src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs]: 💡 

```suggestion
            // When imports are added to a code file that has no previous imports, extra
```

File: src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs [hunk 6]
```diff
@@ -150,13 +153,64 @@ private async Task<Document> ApplyFixesAsync(Document document, ImmutableArray<A
...
+        private async Task<Document> CleanUpNewLinesAsync(Document document, IEnumerable<TextSpan> insertSpans, CancellationToken cancellationToken)
+        {
+            var languageFormatter = document.GetLanguageService<ISyntaxFormattingService>();
+            var options = await document.GetOptionsAsync(cancellationToken).ConfigureAwait(false);
+
+            var newDocument = document;
+
+            // Since imports can be added at both the CompilationUnit and the Namespace level,
+            // format each span individually so that we can retain each newline that was intended
+            // separate the import section from the other content.
```
Comment (sharwell) [inline src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs]: 💡 

```suggestion
            // to separate the import section from the other content.
```

File: src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs [hunk 7]
```diff
@@ -175,5 +229,31 @@ private async Task<Document> ApplyFixesAsync(Document document, ImmutableArray<A
 
             return (projectChanges, textChanges);
         }
+
+        class CleanUpNewLinesFormatter : AbstractFormattingRule
```
Comment (sharwell) [inline src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs]: 💡  

```suggestion
        private sealed class CleanUpNewLinesFormatter : AbstractFormattingRule
```

File: src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs [hunk 8]
```diff
@@ -175,5 +229,31 @@ private async Task<Document> ApplyFixesAsync(Document document, ImmutableArray<A
...
+        {
+            private SourceText _text;
```
Comment (sharwell) [inline src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs]: 💡 

```suggestion
            private readonly SourceText _text;
```

File: src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs [hunk 9]
```diff
@@ -150,13 +153,64 @@ private async Task<Document> ApplyFixesAsync(Document document, ImmutableArray<A
...
+
             return newDocument;
         }
 
+        private async Task<Document> CleanUpNewLinesAsync(Document document, TextSpan insertSpan, ISyntaxFormattingService languageFormatter, OptionSet options, CancellationToken cancellationToken)
+        {
+            var root = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
+            var text = await document.GetTextAsync(cancellationToken).ConfigureAwait(false);
+
+            var textChanges = languageFormatter.Format(root, new[] { insertSpan }, options, new[] { new CleanUpNewLinesFormatter(text) }, cancellationToken).GetTextChanges();
```
Comment (sharwell) [inline src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs]: 😎 clever

Comment (JoeRobich) [reply src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs]: all thanks to @CyrusNajmabadi for the suggestion

File: src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs (hunk 4 above)
Comment (JoeRobich) [reply src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs]: Something like `Debug.Assert(textChanges.Last().Span.End == insertSpan.End);`?

**Comment by JoeRobich** [comment]
@jinujoseph @vatsalyaagrawal  for approval
