### PR TITLE
Always use DiagnosticHelper.Create for diagnostics with options

### LINKED ISSUE #73261: IDE0130 is not reported correctly in 8.0.2xx
### Describe the bug
Even though the corresponding dotnet style is set to produce a warning, the build doesn't produce the warning when an incorrect namespace is present. 

### To Reproduce
- Install the sdk version 8.0.2xx (I have tested this with 8.0.200 and 8.0.203)
- Set the following:
`dotnet_style_namespace_match_folder = true`
`dotnet_diagnostic.IDE0130.severity = warning`
- Modify a namespace to not match the directory structure.
- IDE0130 should be reported as a warning, but it is not reported.

### Further technical details
- This can be reproduced both in Visual studio 2022 and in the CLI running `dotnet build`

### PR DESCRIPTION
**Pull request by js6pak**
Fixes https://github.com/dotnet/sdk/issues/39142, fixes #73261

`IDE0073` was also affected but got fixed by https://github.com/dotnet/roslyn/pull/73263

Repro repo on which I tested this PR: https://github.com/js6pak/BrokenCodeStyleAnalyzersRepro
8.0.1xx and this PR should report `IDE0036`, `IDE0073` and `IDE0130` while 8.0.2xx won't report anything.

Even though I think I found all the affected diagnostics, there might be more I missed and this silent breakage when you use `Diagnostic.Create` directly on `CustomSeverityConfigurable` diagnostics definitely feels wrong, maybe it should throw if you don't use `DiagnosticHelper`?

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@mavasani @sharwell can you review?

File: src/Analyzers/Core/Analyzers/OrderModifiers/AbstractOrderModifiersDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -71,8 +71,13 @@ private void AnalyzeSyntaxTree(SyntaxTreeAnalysisContext context, CompilationOpt
                 // If the severity is hidden, put the marker on all the modifiers so that the
                 // user can bring up the fix anywhere in the modifier list.
                 context.ReportDiagnostic(
-                    Diagnostic.Create(Descriptor, context.Tree.GetLocation(
-                        TextSpan.FromBounds(modifiers.First().SpanStart, modifiers.Last().Span.End))));
+                    DiagnosticHelper.Create(
```
Comment (sharwell) [inline src/Analyzers/Core/Analyzers/OrderModifiers/AbstractOrderModifiersDiagnosticAnalyzer.cs:74]: ❗ The severity check a few lines up need to be corrected to reflect the severity that will be included in the custom diagnostic.

**Review by sharwell — CHANGES_REQUESTED** [review]

File: src/Analyzers/Core/Analyzers/OrderModifiers/AbstractOrderModifiersDiagnosticAnalyzer.cs (hunk 1 above)
Comment (js6pak) [reply src/Analyzers/Core/Analyzers/OrderModifiers/AbstractOrderModifiersDiagnosticAnalyzer.cs:74]: What is the expected behavior for this check in the first place? From my testing 8.0.1xx and this PR behave in the same way.
If by correcting you mean it actually checking the final severity and not just the option custom severity then I'd say it's out of scope of this PR, and I'm not sure whether it's even possible here.

Comment (sharwell) [reply src/Analyzers/Core/Analyzers/OrderModifiers/AbstractOrderModifiersDiagnosticAnalyzer.cs:74]: Ah, makes sense, thanks.

**Review by sharwell — APPROVED** [review]

**Comment by cremor** [comment]
Are the CI failures related to the changes in the PR? If not, can we get this merged?
