### PR TITLE
Enhance explicit interface implementation completion provider

### LINKED ISSUE #70458: C# completion offered for explicit static interface method declaration generates code with several issues
**Version Used**: VS 17.7.4

**Steps to Reproduce**:

Declare this interface:

```cs
interface IFoo
{
	static abstract bool TryDecode([NotNullWhen(false)] out DecodeError? decodeError, [NotNullWhen(false)] out string? errorMessage);
}
```

Then in a class that declares to implement this interface (but does not yet declare a `TryDecode` method,
start typing the declaration:

```cs
bool IFoo.
```

At this point, the completion list appears and offers to complete `TryDecode`. Selecting this, the line immediately becomes:

```cs
bool IFoo.TryDecode(out Nerdbank.Cryptocurrencies.DecodeError?? decodeError, out string? errorMessage)
```

There are 3 problems with this:
1. Notice that the `decodeError` parameter has `??` as its nullable ref annotation instead of `?`.
2. The `static` modifier hasn't been added.
3. The `[NotNullWhen(false)]` attributes are dropped, producing C# warnings about mismatching nullable guarantees.

Both of these have to be manually fixed before the body of the method can then be written.

### LINKED ISSUE #72224: Explicit interface member completion doesn't work with params collections
```
        [Fact]
        public async Task TestWithParamsCollectionParameter()
        {
            var markup = """
                using System.Collections.Generic;

                interface I
                {
                    void M(params IEnumerable<string> args);
                }

                class C : I
                {
                    void I.$$
                }
                """;

            var expected = """
                using System.Collections.Generic;

                interface I
                {
                    void M(params IEnumerable<string> args);
                }

                class C : I
                {
                    void I.M(params IEnumerable<string> args)
                }
                """;

            await VerifyProviderCommitAsync(markup, "M(params IEnumerable<string> args)", expected, '\t');
        }
```

Observed:
```
Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Completion.CompletionProviders.ExplicitInterfaceMemberCompletionProviderTests.TestWithParamsCollectionParameter [FAIL]
  Assert.Contains() Failure
  Not found: (filter expression)
  In value:  SegmentedList<CompletionItem> [M(params System.Collections.Generic.IEnumerable<string> args)]
  Stack Trace:
    D:\GitHub\roslyn\src\EditorFeatures\TestUtilities\Completion\AbstractCompletionProviderTests.cs(588,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Completion.AbstractCompletionProviderTests`1.<VerifyProviderCommitCheckResultsAsync>d__59.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
    D:\GitHub\roslyn\src\EditorFeatures\TestUtilities\Completion\AbstractCompletionProviderTests.cs(573,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Completion.AbstractCompletionProviderTests`1.<VerifyProviderCommitWorkerAsync>d__58.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
    D:\GitHub\roslyn\src\EditorFeatures\TestUtilities\Completion\AbstractCompletionProviderTests.cs(320,0): at Microsoft.CodeAnalysis.Editor.UnitTests.Completion.AbstractCompletionProviderTests`1.<VerifyProviderCommitAsync>d__45.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
    D:\GitHub\roslyn\src\EditorFeatures\CSharpTest\Completion\CompletionProviders\ExplicitInterfaceMemberCompletionProviderTests.cs(821,0): at Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Completion.CompletionProviders.ExplicitInterfaceMemberCompletionProviderTests.<TestWithParamsCollectionParameter>d__29.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

### LINKED ISSUE #75435: [IntelliSense] Suggest names of remaining explicitly implementable members after dotting an implemented interface without typing the return type
Currently, after dotting an interface name without having specified the type of the explicitly implemented member, the name of the member is not suggested. Instead, the appearing suggestions would expect a nested type to suggest, considering the case of typing out a name of the type of the member that is being declared.

Example:
```csharp
public interface IThing
{
    public void Method(int a, int b);
}

public sealed class C : IThing
{
    IThing.$$
}
```

Placing the caret at `$$` will trigger suggestions for nested types that `IThing` contains, in which case is none. It will not suggest auto-completing and filling in the return type of the auto-implemented member after the dot. This behavior would be similar to overriding methods, where typing `override` is sufficient to begin suggesting overridable members and automatically filling in the return type and the parameters/accessors of the overridden member after selecting the suggestion.

The way to actually show the explicitly implementable members right now is by having already typed the member's type and then typing the interface name. This requires knowing the return type, and typing that first before implementing the member, which is prone to errors like typing the wrong return type. The suggestion still appears even with the wrong return type, but then the compiler will show an error about the explicit implementation's return type.

### PR DESCRIPTION
**Pull request by Rekkonnect**
Fixes #75435
Fixes #72224
Fixes #70458

## Implementation details

The `ExplicitInterfaceMemberCompletionProvider` is now up to par with the `OverrideCompletionProvider`, with some abstractions to share between the two like the `ItemGetter`. The characters `[` and `<` no longer commit the selected completion item since the completion provider now fills the implementation body and the signature completely.

The `AbstractMemberInsertingCompletionProvider` itself also became faster by doing less work when replacing the completed text in the original document via annotations. This behavioral adjustment was also necessary because of problems that arose while changing the `ExplicitInterfaceMemberCompletionProvider` to be an `AbstractMemberInsertingCompletionProvider`.

Another fixed bug is the explicit interface implementation generator for abstract conversion operators, which were not handled in the "Implement interface explicitly" code fixes. This was resolved for both the fixes and the completion provider.

When the user is typing out an explicit interface declaration member, the provider ignores the potential difference in the return type. This is justified as the user could easily mistake the return type, and so we do not want to filter out the actual candidates that can be offered. Besides, in most cases the recommended members are too few to need this filtering. If the user types out a return type and then we complete a member that has a different return type, the result includes the actual signature of the implemented member, discarding the old return type.

The spell fix suggestions for explicit interface implementation members were removed because of the complexity of handling the generated code. The justification is that it's easier for the user to manually type the member out because of the improvements to the completion provider.

The symbol generators still ignore the attributes on the parameters or the symbols themselves of explicit interface implementations, despite being legal to use in that context.

## Tests

- [x] Added a bunch of tests showing the new behavior of the completion provider
- [x] Changed existing tests to reflect the new behavior
- [x] Changed the spell fix suggestion tests for explicit interface implementation members to expect no fixes
- [x] Added a test for #70458
- [x] Added tests showing the behavior on nested interfaces (outer types being interfaces or other kinds)

### CODE REVIEW

**Comment by Rekkonnect** [comment]
@CyrusNajmabadi ptal

File: src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs [hunk 1]
```diff
@@ -4540,7 +4540,7 @@ interface IOptional
 
             class Opt : IOptional
             {
-                int IOptional.Goo(int g)
+                int IOptional.Goo(int g = 0)
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs:4543]: what happened here?  explicit interface members should not have default values.

Comment (CyrusNajmabadi) [reply src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs:4543]: (compiler will warn if you do this).

Comment (Rekkonnect) [reply src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs:4543]: SharpLab shows that only a warning is shown indicating that the default value will have no effect. Though it's better to never generate the default value. I'll change this.

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProviderTests.cs [hunk 2]
```diff
@@ -1044,13 +1044,12 @@ interface I
...
             class C : I
             {
-                void I.M(int x = 10)
+                void I.M(int x)
                 {
                     throw new System.NotImplementedException();
                 }
             }
             """;
-        // TODO: Consider adding the default value too.
```
Comment (Rekkonnect) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProviderTests.cs:945]: Since default values are meaningless in explicit interface implementations, showing them in the completion item is also unimportant. Removed this comment to reflect the sanity of the current case.

File: src/Analyzers/Core/CodeFixes/ImplementInterface/AbstractImplementInterfaceService.cs [hunk 3]
```diff
@@ -94,4 +98,58 @@ public async Task<Document> ImplementInterfaceAsync(
...
+            OnlyRemaining = false,
+            ImplementDisposePattern = false,
+            ThroughMember = null,
+        };
+        var generator = new ImplementInterfaceGenerator(
+            this, document, info, options, configuration);
+        var implementedMembers = await generator.GenerateExplicitlyImplementedMembersAsync(member, options.PropertyGenerationBehavior, cancellationToken).ConfigureAwait(false);
+        cancellationToken.ThrowIfCancellationRequested();
+
+        var singleImplemented = implementedMembers[0]!;
```
Comment (CyrusNajmabadi) [inline src/Analyzers/Core/CodeFixes/ImplementInterface/AbstractImplementInterfaceService.cs:122]: why the !

File: src/Analyzers/Core/CodeFixes/ImplementInterface/AbstractImplementInterfaceService.cs [hunk 4]
```diff
@@ -94,4 +98,58 @@ public async Task<Document> ImplementInterfaceAsync(
...
+        // we have to process the created symbols and reduce to the single property wherein the accessors are contained
+        if (member is IPropertySymbol { IsIndexer: false })
+        {
+            IPropertySymbol? commonContainer = null;
+            foreach (var implementedMember in implementedMembers)
+            {
+                if (implementedMember is IPropertySymbol implementedProperty)
+                {
+                    commonContainer ??= implementedProperty;
+                    Debug.Assert(commonContainer == implementedProperty, "We should have a common property implemented");
```
Comment (CyrusNajmabadi) [inline src/Analyzers/Core/CodeFixes/ImplementInterface/AbstractImplementInterfaceService.cs:134]: make these intro contract calls.

File: src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs [hunk 5]
```diff
@@ -4704,8 +4704,9 @@ public void Goo([DateTimeConstant(100), Optional] DateTime x)
     [Fact, WorkItem("http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/545476")]
     public async Task TestOptionalDateTime2()
     {
-        await TestWithAllCodeStyleOptionsOffAsync(
-            """
+        await new VerifyCS.Test
+        {
+            TestCode = """
             using System;
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs:4710]: i woudl indent these strings.

File: src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs [hunk 6]
```diff
@@ -4731,13 +4732,18 @@ interface IGoo
...
                 {
                     throw new NotImplementedException();
                 }
             }
             """,
-codeAction: ("True;False;False:global::IGoo;Microsoft.CodeAnalysis.ImplementInterface.AbstractImplementInterfaceService+ImplementInterfaceCodeAction;", 1));
+            Options = { AllOptionsOff },
+
+            CodeActionEquivalenceKey = "True;False;False:global::IGoo;Microsoft.CodeAnalysis.ImplementInterface.AbstractImplementInterfaceService+ImplementInterfaceCodeAction;",
+            // 🐛 one value is generated with 0L instead of 0
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs:4744]: not sure what this means.

File: src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs [hunk 7]
```diff
@@ -7622,6 +7629,29 @@ public List<UU> M<TT, UU>(Dictionary<TT, List<UU>> a, TT b, UU c) where UU : TT
     [Fact, WorkItem("http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/994328")]
     public async Task TestDisposePatternWhenAdditionalUsingsAreIntroduced2()
     {
+        const string equatableParameter =
+#if NET9_0_OR_GREATER
+            "[AllowNull] int other"
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs:7634]: this seems... undesirable.  why have `AllowNull` on something known to be a value type?

File: src/Analyzers/Core/CodeFixes/ImplementInterface/AbstractImplementInterfaceService.cs [hunk 8]
```diff
@@ -94,4 +98,58 @@ public async Task<Document> ImplementInterfaceAsync(
...
+                }
+                else
+                {
+                    Contract.ThrowIfNull(implementedMember);
+                    var containingProperty = implementedMember!.ContainingSymbol as IPropertySymbol;
```
Comment (CyrusNajmabadi) [inline src/Analyzers/Core/CodeFixes/ImplementInterface/AbstractImplementInterfaceService.cs:139]: why the !, you just threw if it was null.

File: src/Features/CSharp/Portable/Completion/CompletionProviders/CompletionUtilities.cs [hunk 9]
```diff
@@ -185,4 +187,35 @@ public static int GetTargetCaretPositionForMethod(MethodDeclarationSyntax method
...
         }
     }
+
+    public static int GetTargetCaretPositionForInsertedMember(SyntaxNode caretTarget)
+    {
+        // Inserted Event declarations are a single line, so move to the end of the line.
+        switch (caretTarget)
+        {
+            case EventFieldDeclarationSyntax:
+                return caretTarget.GetLocation().SourceSpan.End;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/CompletionUtilities.cs:197]: to avoid all this repetition, just have tehse helpers return the node you want to move to the end to.  The caller can do the .GetLocation().SourceSpan.End bit.

File: src/Features/CSharp/Portable/Completion/CompletionProviders/CompletionUtilities.cs [hunk 10]
```diff
@@ -185,4 +187,35 @@ public static int GetTargetCaretPositionForMethod(MethodDeclarationSyntax method
...
+            case BaseMethodDeclarationSyntax methodDeclaration:
+                return GetTargetCaretPositionForMethod(methodDeclaration);
+            case BasePropertyDeclarationSyntax propertyDeclaration:
+                {
+                    // property: no accessors; move to the end of the declaration
+                    if (propertyDeclaration.AccessorList != null && propertyDeclaration.AccessorList.Accessors.Any())
```
[the remark this answers is not in the document]
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/CompletionUtilities.cs:203]:
```suggestion
                    if (propertyDeclaration.AccessorList is { Accessors: [var firstAccessor, ..] })
```

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.ItemGetter.cs [hunk 11]
```diff
@@ -0,0 +1,280 @@
...
+using Microsoft.CodeAnalysis.Text;
+using Microsoft.CodeAnalysis.Completion;
+using System;
+using Microsoft.CodeAnalysis.LanguageService;
+using Microsoft.CodeAnalysis.CSharp.Syntax;
+using Microsoft.CodeAnalysis.Completion.Providers;
+using Microsoft.CodeAnalysis.ErrorReporting;
+using System.Linq;
+using Roslyn.Utilities;
+using Microsoft.CodeAnalysis.Editing;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.ItemGetter.cs:21]: sort.

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.ItemGetter.cs [hunk 12]
```diff
@@ -0,0 +1,280 @@
...
+
+                    if (member.IsAccessor() ||
+                        member.Kind == SymbolKind.NamedType ||
+                        !semanticModel.IsAccessible(node.SpanStart, member))
+                    {
+                        return false;
+                    }
+
+                    return true;
+                }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.ItemGetter.cs:140]: all off these need docs.  and docs on 'why' not 'what' :)

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.ItemGetter.cs [hunk 13]
```diff
@@ -0,0 +1,280 @@
...
+                    var (displayText, displayTextSuffix) = SplitMemberName(memberString);
+
+                    return MemberInsertionCompletionItem.Create(
+                        displayText, displayTextSuffix, DeclarationModifiers.None, line,
+                        member, targetToken, Position,
+                        rules: GetRules());
+                }
+            }
+            catch (Exception e)
+            when (FatalError.ReportAndCatchUnlessCanceled(e, ErrorSeverity.General))
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.ItemGetter.cs:157]:
```suggestion
            catch (Exception e) when (FatalError.ReportAndCatchUnlessCanceled(e, ErrorSeverity.General))
```

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.ItemGetter.cs [hunk 14]
```diff
@@ -0,0 +1,280 @@
...
+            }
+        }
+
+        private string ToDisplayString(ISymbol symbol, SemanticModel semanticModel)
+            => symbol switch
+            {
+                IEventSymbol eventSymbol => ToDisplayString(eventSymbol),
+                IPropertySymbol propertySymbol => ToDisplayString(propertySymbol, semanticModel),
+                IMethodSymbol methodSymbol => ToDisplayString(methodSymbol, semanticModel),
+                _ => "" // This shouldn't happen.
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.ItemGetter.cs:170]: then throw.

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs [hunk 15]
```diff
@@ -5,133 +5,204 @@
...
 
-    public override async Task ProvideCompletionsAsync(CompletionContext context)
+    protected override async Task<ISymbol> GenerateMemberAsync(ISymbol member, INamedTypeSymbol implementingType, Document newDocument, CompletionItem completionItem, CancellationToken cancellationToken)
     {
-        try
-        {
-            var document = context.Document;
-            var position = context.Position;
-            var cancellationToken = context.CancellationToken;
+        var implementInterfaceService = (AbstractImplementInterfaceService)newDocument.GetRequiredLanguageService<IImplementInterfaceService>();
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs:39]: why are you casting to the derived type?

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs [hunk 16]
```diff
@@ -5,133 +5,204 @@
...
+
+        var semanticModel = await newDocument.GetSemanticModelAsync(cancellationToken)
+            .ConfigureAwait(false);
+        cancellationToken.ThrowIfCancellationRequested();
+        Debug.Assert(semanticModel != null);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs:44]: use GetRequiredSmenaitcModol, remov ethis assert.

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs [hunk 17]
```diff
@@ -5,133 +5,204 @@
...
+
+        var baseMemberInterfaceType = member.ContainingType;
+        Debug.Assert(baseMemberInterfaceType.TypeKind is TypeKind.Interface);
 
-            var syntaxTree = await document.GetRequiredSyntaxTreeAsync(cancellationToken).ConfigureAwait(false);
+        var interfaceNode = await GetInterfaceNodeInCompletionAsync(newDocument, completionItem, baseMemberInterfaceType, cancellationToken).ConfigureAwait(false);
+        cancellationToken.ThrowIfCancellationRequested();
+        Debug.Assert(interfaceNode != null);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs:51]: remove these asserts.  either make contracts, or ensure that these paths always succeed, or bail out if you can't do that.

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs [hunk 18]
```diff
@@ -5,133 +5,204 @@
...
+    private static async Task<SyntaxNode?> GetInterfaceNodeInCompletionAsync(Document document, CompletionItem item, INamedTypeSymbol baseMemberInterfaceType, CancellationToken cancellationToken)
+    {
+        var syntaxTree = await document.GetRequiredSyntaxTreeAsync(cancellationToken).ConfigureAwait(false);
+        cancellationToken.ThrowIfCancellationRequested();
+        var documentSemanticModel = await document.GetSemanticModelAsync(cancellationToken).ConfigureAwait(false);
+        cancellationToken.ThrowIfCancellationRequested();
+        Debug.Assert(documentSemanticModel != null, "Expected a semantic model out of the document");
+
+        var compilation = documentSemanticModel.Compilation;
+        var node = syntaxTree.FindNode(item.Span, false, true, cancellationToken);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs:74]: named parameters for false/true.

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs [hunk 19]
```diff
@@ -5,133 +5,204 @@
...
+        var primaryTypeDeclaration = node.GetAncestor<BaseTypeDeclarationSyntax>();
+        Debug.Assert(primaryTypeDeclaration != null, "Expected a BaseTypeDeclarationSyntax to contain the implemented interface member");
+        var interfaceNode = NodeInDeclaration(primaryTypeDeclaration);
+        if (interfaceNode != null)
+        {
+            return interfaceNode;
+        }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs:81]: prior to this it would be good to doc the general idea of what's going on.  what you're looking for and what you expect the shape of the tree to be.

**Comment by CyrusNajmabadi** [comment]
Done with pass.  Also, you have a file with a conflict in it.  please bring this PR up to date with main.  Thanks :)

File: src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs (hunk 6 above)
Comment (Rekkonnect) [reply src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs:4744]: See also `TestIntegralAndFloatLiterals`; when specifying `DateTimeConstant(100)`, the semantic structure equivalence check does not forgive the mismatching literal types, despite the available conversion. Removing the CodeActionValidationMode causes the test to fail saying that `"100" does not equal "100"`, where the one is int and the other is long. Apparently the generated argument is perceived as being `int` when the attribute's argument expects a long. I have not dug up the real cause for this problem, so I just copied the note from the other test to indicate the problem.

File: src/Analyzers/Core/CodeFixes/ImplementInterface/AbstractImplementInterfaceService.cs (hunk 3 above)
Comment (Rekkonnect) [reply src/Analyzers/Core/CodeFixes/ImplementInterface/AbstractImplementInterfaceService.cs:122]: Removing the ! and asserting not null as a contract

File: src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs (hunk 7 above)
Comment (Rekkonnect) [reply src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs:7634]: I'll crosscheck with the explicit interface implementation refactoring to see whether this is the existing behavior

File: src/Analyzers/Core/CodeFixes/ImplementInterface/AbstractImplementInterfaceService.cs (hunk 8 above)
Comment (Rekkonnect) [reply src/Analyzers/Core/CodeFixes/ImplementInterface/AbstractImplementInterfaceService.cs:139]: Removing the !

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs (hunk 15 above)
Comment (Rekkonnect) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs:39]: `AbstractImplementInterfaceService.State.Generate` requires an `AbstractImplementInterfaceService`, hence the cast

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs:39]: why are you accessing that here. it's an internal implementation detail.  If you need information from it, it should be through the interface.

**Comment by Rekkonnect** [comment]
@CyrusNajmabadi ready for review again

File: src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs (hunk 7 above)
Comment (CyrusNajmabadi) [reply src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs:7634]: waiting on this.

Comment (Rekkonnect) [reply src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs:7634]: Check the test `GenericInterfaceNotNull1` in `ImplementInterfaceTests`. It generates `[AllowNull] int bar`, with the type of the parameter in the interface method being a generic type parameter, which is a similar case to this. I don't think it's that big of an issue.

File: src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs [hunk 20]
```diff
@@ -4813,12 +4819,12 @@ interface IGoo
 
             public class C : IGoo
             {
-                void IGoo.Goo1(object x)
+                void IGoo.Goo1([IUnknownConstant, Optional] object x)
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs:4822]: i'm not undertstanding why we want these attributes.  can you explain why?

File: src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs [hunk 21]
```diff
@@ -4663,81 +4663,87 @@ public async Task TestOptionalDateTime1()
...
+                    void Goo([Optional][DateTimeConstant(100)] DateTime x);
+                }
 
-            public class C : IGoo
-            {
-                void IGoo.Goo(DateTime x)
+                public class C : IGoo
                 {
-                    throw new NotImplementedException();
+                    void IGoo.Goo([DateTimeConstant(100), Optional] DateTime x)
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs:4735]: these attributes seem undesirable.

File: src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs [hunk 22]
```diff
@@ -11538,12 +11567,12 @@ class C3 : I1<C3>
                     throw new System.NotImplementedException();
                 }
 
-                public static explicit operator checked string(C3 x)
+                static explicit I1<C3>.operator checked string(C3 x)
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs:11570]: why did these change?

File: src/Analyzers/Core/CodeFixes/ImplementInterface/AbstractImplementInterfaceService.cs (hunk 8 above)
Comment (CyrusNajmabadi) [reply src/Analyzers/Core/CodeFixes/ImplementInterface/AbstractImplementInterfaceService.cs:140]: i still see the `!`.  Stopping the review as it looks like you haven't pusehd changes.

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.ItemGetter.cs [hunk 23]
```diff
@@ -0,0 +1,291 @@
...
+            {
+                builder.Append("checked ");
+            }
+        }
+
+        private void AddParameters(ImmutableArray<IParameterSymbol> parameters, StringBuilder builder, SemanticModel semanticModel)
+        {
+            builder.AppendJoinedValues(", ", parameters, (parameter, builder) =>
+            {
+                builder.Append(parameter.RefKind switch
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.ItemGetter.cs:246]: this is simpelr as `(parameter.RefKind, parameter.ScopedKind) switch => ...`

File: src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs (hunk 20 above)
Comment (Rekkonnect) [reply src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs:4822]: I changed it so that explicitly implementing an interface method also carries over the parameters' attributes. This is better imo, for cases like `NotNull` attributes on nullable parameters. The user is still always free to remove those to their will.

File: src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs (hunk 22 above)
Comment (Rekkonnect) [reply src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs:11570]: This is an improvement, where the explicit interface implementation feature now actually explicitly implements operators like this one. All other static and non-static members were being explicitly implemented, whereas operators were not, despite the language allowing it.

File: src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs (hunk 20 above)
Comment (CyrusNajmabadi) [reply src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs:4822]: If it's better for those attributes, we shoudl only carry over those attributes (with explanations why).  We should not carry over the attributes that aren't appropriate to carry over.

File: src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs (hunk 21 above)
Comment (CyrusNajmabadi) [reply src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs:4735]: that doesn't help here.  i don't see how DateTimeConstant *or* optional are valuable here.

File: src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs (hunk 1 above)
Comment (Rekkonnect) [reply src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs]: This has been reverted.

File: src/Analyzers/Core/CodeFixes/ImplementInterface/AbstractImplementInterfaceService.cs (hunk 3 above)
Comment (Rekkonnect) [reply src/Analyzers/Core/CodeFixes/ImplementInterface/AbstractImplementInterfaceService.cs]: Removed

File: src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs (hunk 5 above)
Comment (Rekkonnect) [reply src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs]: Changes applied

File: src/Features/CSharp/Portable/Completion/CompletionProviders/CompletionUtilities.cs (hunk 9 above)
Comment (Rekkonnect) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/CompletionUtilities.cs]: Changed

File: src/Features/CSharp/Portable/Completion/CompletionProviders/CompletionUtilities.cs (hunk 10 above)
[the remark this answers is not in the document]
Comment (Rekkonnect) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/CompletionUtilities.cs]: Changed

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.ItemGetter.cs (hunk 13 above)
Comment (Rekkonnect) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.ItemGetter.cs]: Changed

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.ItemGetter.cs (hunk 11 above)
Comment (Rekkonnect) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.ItemGetter.cs]: Done

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs (hunk 15 above)
Comment (Rekkonnect) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs]: Changed to only rely on the interface

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs [hunk 24]
```diff
@@ -5,133 +5,204 @@
...
+            newDocument, state, member, options, cancellationToken)
+                .ConfigureAwait(false);
+
+        return implementedSymbol;
+    }
+
+    private static async Task<SyntaxNode?> GetInterfaceNodeInCompletionAsync(Document document, CompletionItem item, INamedTypeSymbol baseMemberInterfaceType, CancellationToken cancellationToken)
+    {
+        var syntaxTree = await document.GetRequiredSyntaxTreeAsync(cancellationToken).ConfigureAwait(false);
+        cancellationToken.ThrowIfCancellationRequested();
```
[the remark this answers is not in the document]
Comment (Rekkonnect) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs:62]: Changed usage of CancellationTokens, please verify that their usage is desirable

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs [hunk 25]
```diff
@@ -5,133 +5,204 @@
...
+        var documentSemanticModel = await document.GetSemanticModelAsync(cancellationToken).ConfigureAwait(false);
+        cancellationToken.ThrowIfCancellationRequested();
+        Debug.Assert(documentSemanticModel != null, "Expected a semantic model out of the document");
```
[the remark this answers is not in the document]
Comment (Rekkonnect) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs]: Used GetRequiredSemanticModelAsync

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs (hunk 18 above)
Comment (Rekkonnect) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs]: Used named parameters

File: src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs (hunk 20 above)
Comment (Rekkonnect) [reply src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs:4822]: Will prefer not carrying over any attributes for the time being, as also mentioned in offline discussion. A future iteration involving carrying over important attributes on explicit interface implementations is welcome.

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.ItemGetter.cs (hunk 23 above)
Comment (Rekkonnect) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.ItemGetter.cs]: Changed switch

File: src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs (hunk 21 above)
Comment (Rekkonnect) [reply src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs]: Removed the attributes for the reason mentioned in the comment above

File: src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs (hunk 20 above)
Comment (Rekkonnect) [reply src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs]: Applied changes

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs (hunk 19 above)
Comment (Rekkonnect) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs:85]: Wrote docs, please check

File: src/Analyzers/Core/CodeFixes/ImplementInterface/AbstractImplementInterfaceService.cs (hunk 4 above)
Comment (Rekkonnect) [reply src/Analyzers/Core/CodeFixes/ImplementInterface/AbstractImplementInterfaceService.cs]: Changed all Debug.Asserts into contract calls

File: src/Analyzers/Core/CodeFixes/ImplementInterface/AbstractImplementInterfaceService.cs (hunk 8 above)
Comment (Rekkonnect) [reply src/Analyzers/Core/CodeFixes/ImplementInterface/AbstractImplementInterfaceService.cs]: Removed the unnecessary !

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs (hunk 17 above)
Comment (Rekkonnect) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs]: Changed to contract calls here too

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs (hunk 16 above)
Comment (Rekkonnect) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs]: The comment is now outdated

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.ItemGetter.cs [hunk 26]
```diff
@@ -0,0 +1,280 @@
...
+                {
+                    RefKind.Out => "out ",
+                    RefKind.Ref => "ref ",
+                    RefKind.In => "in ",
```
[the remark this answers is not in the document]
Comment (Rekkonnect) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.ItemGetter.cs]: Scoped is properly handled

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.ItemGetter.cs (hunk 14 above)
Comment (Rekkonnect) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.ItemGetter.cs]: Throwing instead of ignoring the unexpected case

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.ItemGetter.cs (hunk 12 above)
Comment (Rekkonnect) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.ItemGetter.cs:142]: Docs were placed, please check

**Comment by Rekkonnect** [comment]
@CyrusNajmabadi ready for another pass

File: src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs (hunk 6 above)
Comment (Rekkonnect) [reply src/Analyzers/CSharp/Tests/ImplementInterface/ImplementInterfaceTests.cs]: The provider no longer emits attributes, so this was removed.

**Comment by CyrusNajmabadi** [comment]
@Rekkonnect there are merge conflicts here.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks!
