### PR TITLE
Don't provide refactoring for VB Move Static Members when IncompleteMemberSyntax is found

### LINKED ISSUE #63287: InvalidOperationException thrown by AbstractMoveStaticMembersRefactoringProvider
Version 17.4.0 Preview 2.0 [32807.141.main]

In broken VB code like

```
using md0 = ModuleMetadata.CreateFromImage(v0.EmittedAssemblyData)
Dim reader0 = md0.MetadataReader;
Dim generation0 = EmitBaseline.CreateInitialBaseline(md0, v0.CreateSymReader().GetEncMethodDebugInfo)
```

```
System.InvalidOperationException : Operation is not valid due to the current state of the object.
   at Microsoft.CodeAnalysis.Shared.Extensions.SemanticModelExtensions.GetRequiredDeclaredSymbol(SemanticModel semanticModel,SyntaxNode declaration,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MoveStaticMembers.AbstractMoveStaticMembersRefactoringProvider.<>c__DisplayClass1_0.<ComputeRefactoringsAsync>b__0(SyntaxNode m)
   at System.Collections.Immutable.ImmutableArray.CreateRange[TSource,TResult](ImmutableArray`1 items,Func`2 selector)
   at async Microsoft.CodeAnalysis.MoveStaticMembers.AbstractMoveStaticMembersRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

### PR DESCRIPTION
**Pull request by Soreloser2**
Fixes #63287

The `VisualBasicSelectedMembers` uses `StatementSyntax` for its member declaration type parameter, which is the last common base ancestor of `MethodBaseSyntax` and `ModifiedIdentifierSyntax` but is a fairly broad definition for a member declaration. Luckily, only syntaxes defined as members of the containing type are considered for selection, which limits the syntaxes that can actually be provided to `MethodBaseSyntax`, `ModifiedIdentifierSyntax`, and `IncompleteMemberSyntax` AFAIK. We can just do a similar thing that C# does, which is to return no members if the `AbstractSelectedMembers` gives us an `IncompleteMemberSyntax` as a member of its return list.

### CODE REVIEW

File: src/Features/VisualBasic/Portable/CodeRefactorings/NodeSelectionHelpers.vb [hunk 1]
```diff
@@ -42,7 +42,15 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.CodeRefactorings
...
-                Return Await VisualBasicSelectedMembers.Instance.GetSelectedMembersAsync(tree, span, allowPartialSelection:=True, cancellationToken).ConfigureAwait(False)
+                Dim selectedMembers = Await VisualBasicSelectedMembers.Instance.
+                    GetSelectedMembersAsync(tree, span, allowPartialSelection:=True, cancellationToken).ConfigureAwait(False)
+                If selectedMembers.Any(Function(member)
+                                           Return TypeOf member Is IncompleteMemberSyntax
+                                       End Function) Then
+                    Return ImmutableArray(Of SyntaxNode).Empty
+                Else
+                    Return selectedMembers
+                End If
```
Comment (Soreloser2) [inline src/Features/VisualBasic/Portable/CodeRefactorings/NodeSelectionHelpers.vb:53]: Same logic as C# version but without the `GlobalStatementSyntax` as those don't exist in VB

**Review by JoeRobich — APPROVED** [review]

File: src/Features/VisualBasic/Portable/CodeRefactorings/NodeSelectionHelpers.vb [hunk 2]
```diff
@@ -42,7 +42,15 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.CodeRefactorings
                 ' pick up on keywords before the declaration, such as "public static int".
                 ' We could potentially use it for every case if that behavior changes
                 Dim tree = Await document.GetSyntaxTreeAsync(cancellationToken).ConfigureAwait(False)
-                Return Await VisualBasicSelectedMembers.Instance.GetSelectedMembersAsync(tree, span, allowPartialSelection:=True, cancellationToken).ConfigureAwait(False)
+                Dim selectedMembers = Await VisualBasicSelectedMembers.Instance.
+                    GetSelectedMembersAsync(tree, span, allowPartialSelection:=True, cancellationToken).ConfigureAwait(False)
+                If selectedMembers.Any(Function(member)
+                                           Return TypeOf member Is IncompleteMemberSyntax
+                                       End Function) Then
```
Comment (Youssef1313) [inline src/Features/VisualBasic/Portable/CodeRefactorings/NodeSelectionHelpers.vb:49]: Does this shorter form work?

```suggestion
                If selectedMembers.OfType(Of IncompleteMemberSyntax)().Any() Then
```

**Review by Youssef1313 — APPROVED** [review]
LGTM
