### PR TITLE
Fix unused param (IDE0060) false positive

### LINKED ISSUE #56317: IDE0060 (unused param) with NotImplementedException
This has been requested earlier as #41236.

I'm not sure but it looks like

* this should've been solved with PR #42408
* that PR should've been shipped with [16.6.P2](https://github.com/dotnet/roslyn/milestone/65)

I have 16.11.2, but still see this issue.

So either this is broken again, it never worked, or there's a side-case where the fix doesn't work.

My project has `net5.0-windows10.0.17763` as target framework.

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #56317

#42408 handled bailing out reporting unused params for methods that only have a throw operation in its body. It missed a case where the throw might be wrapped within a conversion wrapped within a return operation, which happens when the method returns a non-void type.

### CODE REVIEW

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/OperationExtensions.cs [hunk 1]
```diff
@@ -370,5 +370,20 @@ public static bool IsNumericLiteral(this IOperation operation)
...
             => operand is ILiteralOperation { ConstantValue: { HasValue: true, Value: null } };
+
+        /// <summary>
+        /// Walks down consecutive conversion operations until an operand is reached that isn't a conversion operation.
+        /// </summary>
+        /// <param name="operation">The starting operation.</param>
+        /// <returns>The inner non conversion operation or the starting operation if it wasn't a conversion operation.</returns>
+        public static IOperation? WalkDownConversion(this IOperation? operation)
+        {
+            while (operation is IConversionOperation conversionOperation)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/OperationExtensions.cs:381]: do you only need to do this if it's implicit?

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/OperationExtensions.cs (hunk 1 above)
Comment (mavasani) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/OperationExtensions.cs:381]: Likely for the case in this bug, but probably we want to do it for all conversions for this extension method.
