### PR TITLE
Handle null Display string in FxCopAnalyzersSuggestedActionCallback

### LINKED ISSUE #39092: VisualStudioUnresolvedAnalyzerReference not overriding Display property provokes VS 16.3 crash.
Regression from what shipped with VS 16.2.

https://github.com/dotnet/roslyn/blob/7f60b3849b6dd1c3ee64cd2d327cfc5ea6fa7b64/src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioAnalyzer.cs#L135

does not override the `Display`property, meaning whoever uses that property will get a null value back despite the comment in `AnalyzerReference` suggesting the opposite.

Enter VS 16.3's `FxCopAnalyzersSuggestedActionCallback.IsNuGetInstalled()`

https://github.com/dotnet/roslyn/blob/829fe7d4fe75b243fc535454cf5c24c173dfe1ec/src/VisualStudio/Core/Def/Implementation/Diagnostics/FxCopAnalyzersSuggestedActionCallback.cs#L142-L144

Crash. Unhandled .NET exception.

Sure, it's VS acting up (and perhaps especially bad it's not handling this exception), but it seems this code is not doing what it `Should` (to quote)
https://github.com/dotnet/roslyn/blob/7f60b3849b6dd1c3ee64cd2d327cfc5ea6fa7b64/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerReference.cs#L29-L31

A quick (and dirty?) "fix" could be to just add an override for that property, forwarding to `_underlying.Display`, since that seems to have a non-null string, but I also believe this code needs a bit more unit testing, the baseclass comment "should" could benefit from some clarification (is it supposed to be dependable non-null, or is it an optional suggestion), and

@mavasani  that FxCop code needs to be fixed to not blindly trust reference values.

Since this is currently a show-stopper for us (we're at an effective stand still, not able to trust VS to not crash while editing code), perhaps that could be incentive to fast track a fix?

Edit: Just in case it helps understanding the issue, `_underlying.Display` contains the string
`Unresolved: MyProjPath\\mscorlib.dll`, where MyProjPath is the local filesystem absolute (with doubled-up backslashes) path to the directory holding the .csproj, which seems obvious to me since there are no dll's at all in that directory.

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #39092
Also fix VisualStudioUnresolvedAnalyzerReference to correctly forward the Display value to the underlying analyzer reference.

### CODE REVIEW

**Comment by mavasani** [comment]
@jinujoseph @vatsalyaagrawal Given this change fixes a VS crash, should it target a specific Dev16.4 preview branch earlier then preview targeted by master?

File: src/VisualStudio/Core/Def/Implementation/Diagnostics/FxCopAnalyzersSuggestedActionCallback.cs [hunk 1]
```diff
@@ -139,16 +146,27 @@ private bool IsNuGetInstalled()
...
-                    if (ChildAnalyzerNuGetPackageIds.Contains(analyzerReference.Display))
+                    if (analyzerReference is UnresolvedAnalyzerReference)
+                    {
+                        hasUnresolvedAnalyzerReference = true;
+                        continue;
+                    }
+
+                    var display = analyzerReference.Display;
+                    if (display != null &&
+                        ChildAnalyzerNuGetPackageIds.Contains(display))
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/Diagnostics/FxCopAnalyzersSuggestedActionCallback.cs]: So the display string here is actually being used for checks? That seems....dangerous. What form is the display expected to keep here? Can we add some tests to ensure the form stays in the shape we want?

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioAnalyzer.cs [hunk 2]
```diff
@@ -149,6 +149,9 @@ public override string FullPath
             public override object Id
                 => _underlying.Id;
 
+            public override string Display
+                => _underlying.Display;
```
Comment (sharwell) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioAnalyzer.cs]: ❓ Why is this not using the same form as `UnresolvedAnalyzerReference.Display`?

https://github.com/dotnet/roslyn/blob/97ad88fd2e1a97e15ccd5e9c05b096888ded8a60/src/Compilers/Core/Portable/DiagnosticAnalyzer/UnresolvedAnalyzerReference.cs#L28-L34

File: src/VisualStudio/Core/Def/Implementation/Diagnostics/FxCopAnalyzersSuggestedActionCallback.cs (hunk 1 above)
Comment (mavasani) [reply src/VisualStudio/Core/Def/Implementation/Diagnostics/FxCopAnalyzersSuggestedActionCallback.cs]: If the display string changes, then we will start getting false positives from this component - it will suggest you to install the package even if you already have it. 

> Can we add some tests to ensure the form stays in the shape we want?
Sure, I will add some tests.

File: src/VisualStudio/Core/Def/Implementation/Diagnostics/FxCopAnalyzersSuggestedActionCallback.cs [hunk 3]
```diff
@@ -87,11 +88,16 @@ public void OnSuggestedActionExecuted(SuggestedAction action)
...
+            // 1. Info bar hasn't been shown this session
+            // 2. FxCopAnalyzers VSIX is not installed 
+            // 3. FxCopAnalyzers NuGet is not installed
+            // 4. There are no unresolved analyzer references for active project and
+            // 5. User is candidate based on light bulb usage.
             if (!_infoBarChecked &&
                 !IsVsixInstalled() &&
-                !IsNuGetInstalled() &&
+                !IsNuGetInstalled(out var hasUnresolvedAnalyzerReference) &&
+                !hasUnresolvedAnalyzerReference &&
```
Comment (sharwell) [inline src/VisualStudio/Core/Def/Implementation/Diagnostics/FxCopAnalyzersSuggestedActionCallback.cs]: ❔ What happens if this check is left out? It seems like this doesn't actually change anything.

Comment (mavasani) [reply src/VisualStudio/Core/Def/Implementation/Diagnostics/FxCopAnalyzersSuggestedActionCallback.cs]: The changes to this file are not necessary for fixing the underlying bug. This is just making this component more conservative in presence of unresolved references as it can likely lead to false positives.

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioAnalyzer.cs (hunk 2 above)
Comment (mavasani) [reply src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioAnalyzer.cs]: I think that is what this change will produce given `_underlying` is of type `UnresolvedAnalyzerReference`

File: src/VisualStudio/Core/Def/Implementation/Diagnostics/FxCopAnalyzersSuggestedActionCallback.cs (hunk 1 above)
Comment (tamlin-mike) [reply src/VisualStudio/Core/Def/Implementation/Diagnostics/FxCopAnalyzersSuggestedActionCallback.cs]: @jasonmalinowski  From the original issue #39092:
`_underlying.Display` contains _[ed: contained, at the point of the crash]_ the string
`Unresolved: MyProjPath\\mscorlib.dll`, where MyProjPath is the local filesystem absolute (with doubled-up backslashes) path to the directory holding the .csproj.

One could question the silliness of checking such a name in this context (not to mention I find it somewhat less likely to find analyzers in mscorlib.dll, even _if_ a copy was found alongside the .csproj), but considering it's Monty Python's 50th anniversary... :-)

**Comment by jinujoseph** [comment]
lets keep in master for 16.4.p3

File: src/VisualStudio/Core/Def/Implementation/Diagnostics/FxCopAnalyzersSuggestedActionCallback.cs (hunk 1 above)
Comment (mavasani) [reply src/VisualStudio/Core/Def/Implementation/Diagnostics/FxCopAnalyzersSuggestedActionCallback.cs]: @jasonmalinowski Added regression test with https://github.com/dotnet/roslyn/pull/39097/commits/baf4026a401342cec9e01ca1354d03ca741c6319

**Comment by mavasani** [comment]
@jasonmalinowski Any further feedback? Thanks!

**Comment by mavasani** [comment]
Merging this in.. will address any further feedback with a follow-up PR.
