### PR TITLE
Fix primary ctor param in static context

### LINKED ISSUE #74327: Avoid recommending synthesizing record parameters in static context within the record
## Version Used
VS 2022 Version 17.10.3
Roslyn 4.10.0 (04fb39164c99c)

Project info
C# 12.0
.NET 8.0

## Steps to Reproduce

In the following code:
```csharp
public record class Point(int X, int Y)
{
    public static Point Parse(string line)
    {
        // $$
    }
}
```

place the cursor at `$$`, and type `X`. Examine the suggested symbols.

## Expected Behavior

None of the record's primary constructor parameters appear in the suggestions.

## Actual Behavior

The suggestions include primary constructor parameters within a static context. Note that only parameters that are used to synthesize properties within that record type appear.

### PR DESCRIPTION
**Pull request by Rekkonnect**
Fixes #74327

Two cases are skipped because of another bug in the recommender, as noted in the skip reason.

CC @CyrusNajmabadi

### CODE REVIEW

**Comment by Rekkonnect** [comment]
I can't reproduce the failing tests, could I be missing something?

**Comment by CyrusNajmabadi** [comment]
```
Assert.All() Failure: 1 out of 2 items in the collection did not pass.
[0]: Item: x
Xunit.Sdk.ContainsException: Assert.Contains() Failure
Not found: x
In value:  WhereSelectListIterator<CompletionItem, String> ["async", "await", "base", "Base", "bool", ...]
at Xunit.Assert.Contains[T](T expected, IEnumerable1 collection, IEqualityComparer1 comparer) in C:Dev\xunit\xunitsrc\xunit.assertAssertsCollectionAsserts.cs:line 108
at Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.TestState._Closure$__45-0.Lambda$__0(String v) in //src/EditorFeatures/TestUtilities2/Intellisense/TestState.vb:line 396
at Xunit.Assert.All[T](IEnumerable1 collection, Action1 action) in C:Dev\xunit\xunitsrc\xunit.assertAssertsCollectionAsserts.cs:line 36

```

**Comment by Rekkonnect** [comment]
When I execute them locally they all pass

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ContextQuery/SyntaxTreeExtensions.vb [hunk 1]
```diff
@@ -658,6 +658,43 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Extensions.ContextQuery
...
+                    Exit While
+                End If
+            End While
+
+            If enclosingSymbol Is Nothing Then
+                Return True
+            End If
+
+            Return Not enclosingSymbol.IsStatic
+
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ContextQuery/SyntaxTreeExtensions.vb:695]:
```suggestion
```

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ContextQuery/VisualBasicSyntaxContext.vb [hunk 2]
```diff
@@ -181,6 +185,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Extensions.ContextQuery
                 isInImportsDirective:=leftToken.GetAncestor(Of ImportsStatementSyntax)() IsNot Nothing,
                 isInLambda:=leftToken.GetAncestor(Of LambdaExpressionSyntax)() IsNot Nothing,
                 isInQuery:=isInQuery,
+                isInstanceContext:=IsInstanceContext,
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ContextQuery/VisualBasicSyntaxContext.vb:188]: wrong casing.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ContextQuery/SyntaxTreeExtensions.vb [hunk 3]
```diff
@@ -658,6 +658,43 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Extensions.ContextQuery
                                                        s_multilineStatementBlockStartKinds)
         End Function
 
+        <Extension()>
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ContextQuery/SyntaxTreeExtensions.vb:661]:
```suggestion
        <Extension>
```

**Comment by Rekkonnect** [comment]
@CyrusNajmabadi suggestions in place ptal

File: src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationService.cs [hunk 4]
```diff
@@ -132,6 +140,15 @@ internal bool ShouldIncludeSymbol(ISymbol symbol)
                 }
             }
 
+            // Primary constructor parameters should not appear in static context
+            if (_context.IsStatementContext &&
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationService.cs:144]: i don't understaand the IsStatementContext check.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ContextQuery/SyntaxTreeExtensions.vb [hunk 5]
```diff
@@ -658,6 +658,42 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Extensions.ContextQuery
                                                        s_multilineStatementBlockStartKinds)
         End Function
 
+        <Extension>
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ContextQuery/SyntaxTreeExtensions.vb:661]: why did vb need this?

Comment (Rekkonnect) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ContextQuery/SyntaxTreeExtensions.vb:661]: I needed C#'s `IsInstanceContext` so I pulled it into the base context, and since VB had it exposed I wanted to implement this for correctness. Though there are no tests showing that it is correct. Do we want to keep that implementation as-is, since this does not affect anything else for now? The context is not a public API after all.

File: src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationService.cs (hunk 4 above)
Comment (Rekkonnect) [reply src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationService.cs]: It's indeed unnecessary, removed

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ContextQuery/SyntaxTreeExtensions.vb (hunk 5 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ContextQuery/SyntaxTreeExtensions.vb:661]: > I needed C#'s IsInstanceContext so I pulled it into the base context

You know you're in c#, so you can cast the context to the derived type.

Comment (CyrusNajmabadi) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ContextQuery/SyntaxTreeExtensions.vb:661]: > Though there are no tests showing that it is correct. 

Remove as vb has no need for this.

Comment (Rekkonnect) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/VisualBasic/Extensions/ContextQuery/SyntaxTreeExtensions.vb]: Removed the VB implementation and made the fix C#-focused

**Comment by Rekkonnect** [comment]
@CyrusNajmabadi ready for review with resolved comments

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs [hunk 6]
```diff
@@ -14788,6 +14788,210 @@ IEnumerable<string> M() => [string.Empty, .. ($$
...
+            """;
+        await VerifyExpectedItemsAsync(markup, [
+            ItemExpectation.Exists("X"),
+            ItemExpectation.Exists("Y"),
+        ]);
+    }
+
+    [Theory, WorkItem("https://github.com/dotnet/roslyn/issues/74327")]
+    [InlineData("record class")]
+    [InlineData("class", Skip = "Class primary constructor parameter used in base constructor not recommended even inside nameof")]
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs:14893]: Don't add skipped tests. Just have the tests demonstrate what the behavior is currently

File: src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs [hunk 7]
```diff
@@ -407,12 +407,34 @@ static bool IsUndesirable(
...
 
                 return false;
             }
 
+            static bool IsPrimaryConstructorParameter(
+                CSharpSyntaxContext context,
+                ISymbol symbol,
+                CancellationToken cancellationToken)
+            {
+                if (symbol is not IParameterSymbol parameterSymbol)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs:429]: Return symbol is iparameter && param.isprimaryconstructor

File: src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs [hunk 8]
```diff
@@ -422,11 +444,11 @@ static bool IsCapturedPrimaryConstructorParameter(
...
                     return false;
 
-                if (symbol is not IParameterSymbol parameterSymbol)
-                    return false;
+                Debug.Assert(symbol is IParameterSymbol);
+                var parameterSymbol = (IParameterSymbol)symbol;
 
-                if (!parameterSymbol.IsPrimaryConstructor(cancellationToken))
-                    return false;
+                // Do not allow cancelling the assertion
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs:450]: I don't know what this comment means

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs (hunk 6 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs:14893]: Also, this seems trivially fixable

Comment (Rekkonnect) [reply src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs:14893]: I'd prefer fixing this in another PR. My intention with adding the skipped test is to demonstrate an existing bug. Otherwise it would be seen as intended behavior.

File: src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs (hunk 8 above)
Comment (Rekkonnect) [reply src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs:450]: It refers to passing default as the cancellation token in the evaluation of whether the parameter symbol is a primary constructor parameter. Though the assertion should also handle the case of the cancellation token having been cancelled, so I'll adjust to `Debug.Assert(parameter.IsPrimaryConstructor(cancellationToken) || cancellationToken.IsCancellationRequested);`

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs (hunk 6 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs:14893]: Unskip and leave a comment. Skipped tests serve no value. We only want to skip for flakey issues we're unblocking ci for.

File: src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs (hunk 8 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs:450]: I still don't understand. Why not just pass the cancellation token

Comment (Rekkonnect) [reply src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs:450]: I thought that if the cancellation token was passed, and a cancellation was requested, the method would return false. Haven't got much knowledge about whether cancellations throw or early-exit and in which areas. If it throws, then simply passing the cancellation token will do.

Comment (CyrusNajmabadi) [reply src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs:450]: They throw

File: src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs [hunk 9]
```diff
@@ -407,12 +405,41 @@ static bool IsUndesirable(
                 if (filterOutOfScopeLocals && symbol.IsInaccessibleLocal(context.Position))
                     return true;
 
-                if (IsCapturedPrimaryConstructorParameter(context, enclosingNamedType, symbol, cancellationToken))
-                    return true;
+                // Outside of a nameof(...) we don't want to include a primary constructor parameter if it's not
+                // available.  Inside of a nameof(...) we do want to include it as it's always legal and causes no
+                // warnings.
+                if (!context.IsNameOfContext &&
+                    IsPrimaryConstructorParameter(context, symbol, cancellationToken))
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs:412]: i fixed the logic to not inappropriately filter out symbols.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
lgtm  thanks.
