### PR TITLE
Preventing crash when a local function with iterators is using an out/ref parameter

### LINKED ISSUE #18813: Trying to use out variable in local function generator crashes Visual Studio
**Version Used**: 
Visual Studio 2017 15.1 (26403.7)

**Steps to Reproduce**:

Paste following as local function and your Visual Studio crashes
```
IEnumerable<string> getFoo(int count, out bool foobar)
{
  foobar = false;
  for (int i = 0; i < count; i++)
  {
    foreach (var val in getFoo(3, out var bar))
      yield return "foo";
  }
  yield return "foo";
}
```

**Watson**
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=423864&_a=edit&triage=true
**Expected Behavior**:
Visual Studio wouldn't crash
**Actual Behavior**:
It crashes

I would have used Visual Studio's "Report a problem" but it doesn't work for me. Tried signing out, signing in multiple times and rebooted my computer. I just get "Sorry, we couldn't send your report. Please retry now or sign out, sign in, and try again" all the time. And only way to report error for Visual Studio is through Visual Studio and that doesn't work! (https://developercommunity.visualstudio.com/ doesn't have form to report a problem, they only show you how to do it inside Visual Studio).

### PR DESCRIPTION
**Pull request by BattleRush**
When the localfunction has IsIterator == true, then a PendingBranch is
being added with a branch as null. This later causes a
NullReferenceException in ReportUnassignedOutParameter

Fixes #18813

**Customer scenario**
When creating a local function(with Iterators) and it has out/ref parameters, Visual Studio just crashes.

**Bugs this fixes:**
https://github.com/dotnet/roslyn/issues/18813

**Workarounds, if any**
None.

**Risk**
Affects Local functions when they have ref/out parameters

**Performance impact**
Low

**Is this a regression from a previous update?**
No.

**Root cause analysis:**
~~No tests found in the area of DataFlowPass.LocalFunctions.cs and other methods involved in this issue~~
~~What tests are we adding to guard against it in the future?~~
~~Might need a new issue to track the missing tests for this area.~~

Since the changes did trigger a failed build, my previous assumption, that there aren't tests covering the affected methods is wrong.

**How was the bug found?**
https://github.com/dotnet/roslyn/issues/18813

### CODE REVIEW

**Comment by BattleRush** [comment]
With the fix, this is the current output
image

image

**Comment by BattleRush** [comment]
Now that its building again, its ready to be reviewed.

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-compiler for review.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.LocalFunctions.cs [hunk 1]
```diff
@@ -141,6 +141,8 @@ public override BoundNode VisitLocalFunctionStatement(BoundLocalFunctionStatemen
             // of the function where the enumerable is returned.
             if (localFuncSymbol.IsIterator)
             {
+                //This causes an exception later if one of the parameters is out or ref
+                //Added the check bellow if (branch != null) to not check for LeaveParameters
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.LocalFunctions.cs]: Nit: please add a space between `//` and the comment text.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.LocalFunctions.cs [hunk 2]
```diff
@@ -163,9 +165,14 @@ public override BoundNode VisitLocalFunctionStatement(BoundLocalFunctionStatemen
             {
                 this.State = pending.State;
                 BoundNode branch = pending.Branch;
-                LeaveParameters(localFuncSymbol.Parameters, branch?.Syntax,
-                                branch?.WasCompilerGenerated == true
-                                    ? location : null);
+
+                if (branch != null)//No need to check the parameters if we dont know the branch
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.LocalFunctions.cs]: Please place comments like this above the `if` block.  Our style doesn't put comments between the if conditional and the opening `{`

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 3]
```diff
@@ -271,14 +271,19 @@ protected override ImmutableArray<PendingBranch> RemoveReturns()
 
         protected virtual void ReportUnassignedOutParameter(ParameterSymbol parameter, SyntaxNode node, Location location)
         {
-            if (!_requireOutParamsAssigned && topLevelMethod == currentMethodOrLambda) return;
+            if (!_requireOutParamsAssigned && topLevelMethod == currentMethodOrLambda ||
+                node == null && location == null)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: Unclear why we need to guard against `null` in these two cases.  Can you elaborate?

Comment (BattleRush) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: If `location` is `null` it could be created from `node`, however if both are `null` then there is no point to try validate further. It will lead to a `NullReferenceException`(this causes VS to crash) and a `location` is needed to create diagnostics. I couldn't find another way that both could be `null` since I added a `null `check in DataFlowPass.LocalFunctions.cs that actually prevented the issue already from this bug (created by `PendingBranches.Add(new PendingBranch(null, this.State));`)

I wanted to make sure if on some way it would happen again, its better to catch it than let VS run into crash.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.LocalFunctions.cs [hunk 4]
```diff
@@ -163,9 +165,15 @@ public override BoundNode VisitLocalFunctionStatement(BoundLocalFunctionStatemen
             {
                 this.State = pending.State;
                 BoundNode branch = pending.Branch;
-                LeaveParameters(localFuncSymbol.Parameters, branch?.Syntax,
-                                branch?.WasCompilerGenerated == true
-                                    ? location : null);
+
+                // No need to check the parameters if we dont know the branch
+                if (branch != null)
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.LocalFunctions.cs]: It looks like the root cause isn't that the branch is null, it's that `LeaveParameters` doesn't expect the syntax to be null. I see two options:

1. We could harden LeaveParameters against null syntax.
2. We could find some syntax to pass to LeaveParameters in the case that the branch is null.

I think (2) may be our best option here. It seems like the syntax is just a place to report the diagnostic. Since this is a generated branch which implicitly occurs before the first statement in an iterator, it seems like the local function itself is as good as any to put the diagnostic (since there is no line of source code that actually corresponds to the implicit branch).

I would instead remove the initial null check and change `branch?.Syntax` below to `branch?.Syntax ?? localFunc.Syntax` and add a comment about why we're choosing the local function syntax in the case of null.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 5]
```diff
@@ -271,14 +271,19 @@ protected override ImmutableArray<PendingBranch> RemoveReturns()
 
         protected virtual void ReportUnassignedOutParameter(ParameterSymbol parameter, SyntaxNode node, Location location)
         {
-            if (!_requireOutParamsAssigned && topLevelMethod == currentMethodOrLambda) return;
+            if (!_requireOutParamsAssigned && topLevelMethod == currentMethodOrLambda ||
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: I don't think we should try to guard against `null` here. I would instead add

```csharp
Debug.Assert(node != null || location != null);
```

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.LocalFunctions.cs (hunk 4 above)
Comment (BattleRush) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.LocalFunctions.cs]: How likelly is it that the SyntaxNode for branch and localFunction could be null?

**Comment by BattleRush** [comment]
I added the changes from the reviews.

I won't come around to do the tests today. Ill add them tomorrow.

**Comment by BattleRush** [comment]
@agocke I added now the test to cover this case.
Both repros worked resulted in the same crash so I added only once case. Should the other still be added?

Regarding the current error messages (Copy pase from a review comment that is auto hidden due to changes):
How likelly is it that the SyntaxNode for branch and localFunction could be null? 

Edit: With the changes this is the current output
image

Few questions
- On hoovering the error CS0177 is shown (would be CS1623 better since it better describes the problem?)
- The entire method is underlined. Is that ok like this, or is an output like https://github.com/dotnet/roslyn/pull/18836#issuecomment-295455997 preferred?

**Comment by CyrusNajmabadi** [comment]
> The entire method is underlined. Is that ok like this

We'd definitely want an error that isn't hte entire span of hte local-function.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.LocalFunctions.cs [hunk 6]
```diff
@@ -141,6 +141,8 @@ public override BoundNode VisitLocalFunctionStatement(BoundLocalFunctionStatemen
             // of the function where the enumerable is returned.
             if (localFuncSymbol.IsIterator)
             {
+                // This causes an exception later if one of the parameters is out or ref
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.LocalFunctions.cs]: This comment looks obsolete.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 7]
```diff
@@ -271,14 +271,19 @@ protected override ImmutableArray<PendingBranch> RemoveReturns()
...
+            Debug.Assert(node != null || location != null);
+
             if (Diagnostics != null && this.State.Reachable)
             {
                 if (location == null)
                 {
                     location = new SourceLocation(node);
                 }
-
+
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: extra whitespace

**Comment by agocke** [comment]
Yeah, I think @CyrusNajmabadi  is right. Maybe we should use the identifier of the local function instead of the whole thing.

Regarding the question: I don't think the local function itself could ever be null. The branch can be, of course, because it's introduced explicitly in a few cases where there is no syntax for the branch itself.

**Comment by agocke** [comment]
Also, might as well include both unit tests. Just in case we regress one but not the other.

**Comment by BattleRush** [comment]
Added a 2. test (with the second repro step for the crash)

Regarding the error display I removed the check for `WasCompilerGenerated `since this was blocking the `location `and was forcing a `new location` to be created each time.
Reason being is that the `location `already had the identifier of the local function correcty set and didn't want to throw it away if I could reuse it. 
However it seems a bit sketchy, thats why I'll wait out all tests to pass to see if have to have a look at it again.

**Comment by agocke** [comment]
@BattleRush I thought about this a little more and I think I gave you the wrong advice -- I think my condition is actually backwards. Since the branch is compiler generated, we shouldn't fake up syntax for it, we should pass a location. So really we should let `syntax` pass through as `null`, but change the condition for `location` to be passed when the branch is compiler generated OR if it is null. Thus, I think the appropriate code is this:

```csharp
// Pass the local function identifier as a location if the branch
// is null or compiler generated.
LeaveParameters(localFuncSymbol.Parameters,
  branch?.Syntax,
  branch?.WasCompilerGenerated == false ? null : location);
```

**Comment by agocke** [comment]
@BattleRush If you want, I can push this to your branch to save you some effort.

**Comment by BattleRush** [comment]
@agocke Thanks for the hint. I have commited the changes. I tested with the reprosteps and the errors are correctly displayed.

**Comment by agocke** [comment]
Cc @gafter @dotnet/roslyn-compiler for another review

File: src/Compilers/CSharp/Test/Semantic/FlowAnalysis/LocalFunctions.cs [hunk 8]
```diff
@@ -1318,5 +1318,67 @@ void Local()
                 //         Local();
                 Diagnostic(ErrorCode.ERR_UseDefViolationField, "Local()").WithArguments("_x").WithLocation(14, 9));
         }
+
+
+        [Fact]
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/FlowAnalysis/LocalFunctions.cs]: Nit: double empty line above.

File: src/Compilers/CSharp/Test/Semantic/FlowAnalysis/LocalFunctions.cs [hunk 9]
```diff
@@ -1318,5 +1318,67 @@ void Local()
...
+        public void LocalIEnumerableFunctionWithOutParameter1()
+        {
+            var comp = CreateStandardCompilation(@"
+class c
+{
+    static void Main(string[] args)
+    {
+        System.Collections.Generic.IEnumerable<string> getFoo(int count, out bool foobar)
+        {
+            foobar = true;
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/FlowAnalysis/LocalFunctions.cs]: Nit: we actually try to avoid "foobar" in the codebase because it triggers some geo-political keyword checker. Call it `output` or something else.

**Comment by jcouv** [comment]
@gafter You may want to take a look. Small change related to data flow analysis, fixing a crash.

**Comment by BattleRush** [comment]
Commited the code review changes and also changed the title of the pull request, since the old title didn't represent what has changed (due to changes during the pull request).

**Comment by jcouv** [comment]
LGTM Thanks!
I'll let @gafter also take a look.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 10]
```diff
@@ -271,7 +271,12 @@ protected override ImmutableArray<PendingBranch> RemoveReturns()
 
         protected virtual void ReportUnassignedOutParameter(ParameterSymbol parameter, SyntaxNode node, Location location)
         {
-            if (!_requireOutParamsAssigned && topLevelMethod == currentMethodOrLambda) return;
+            if (!_requireOutParamsAssigned && topLevelMethod == currentMethodOrLambda)
+                return;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: >return; [](start = 16, length = 7)

Please add ```{}``` around the ```if``` body.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.LocalFunctions.cs [hunk 11]
```diff
@@ -163,9 +163,13 @@ public override BoundNode VisitLocalFunctionStatement(BoundLocalFunctionStatemen
...
                 BoundNode branch = pending.Branch;
-                LeaveParameters(localFuncSymbol.Parameters, branch?.Syntax,
-                                branch?.WasCompilerGenerated == true
-                                    ? location : null);
+
+                // Pass the local function identifier as a location if the branch
+                // is null or compiler generated.
+                LeaveParameters(localFuncSymbol.Parameters,
+                  branch?.Syntax,
+                  branch?.WasCompilerGenerated == false ? null : location);
```
Comment (alrz) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.LocalFunctions.cs]: I think  you meant `branch?.WasCompilerGenerated == true ? local : false`?

**Comment by agocke** [comment]
cc @MeiChin-Tsai for ask mode approval

**Comment by MeiChin-Tsai** [comment]
approved. thx.

**Comment by agocke** [comment]
@BattleRush Sorry for the delay, but this has been merged and completed! Thank you for your contribution!
