### PR TITLE
Fix Extract Base When Class Has Base

### LINKED ISSUE #55610: Extract Base Class will trigger on multiple members, even if the containing class already has a base class
**Steps to Reproduce**:
Create a base class and a separate inherited class with members:
```
class Base
{
}

class Derived : Base
{
    public int _testInt;

    public static void TestMethod()
    {
    }
}
```
Highlight multiple members, as shown using `[|this symbol|]` to indicate the range of selection:
```
class Derived : Base
{
    [|public int _testInt;

    public static void TestMethod()
    {
    }|]
}
```
Then invoke the quick actions menu using the lightbulb/screwdriver or Ctrl + .
**Expected Behavior**:
"Extract Base Class" should not show up as a possible refactoring, as there is already a base class. This is the behavior shown when only one member is selected
**Actual Behavior**:
"Extract Base Class" shows up as a possible refactoring. Actually invoking the refactoring will open a dialog, which will create a new base class for `Derived`. Now `Derived` will inherit from multiple classes, which produces a compiler error.

I think it is possible for "Extract Base Class" to be a valid refactoring here. If we created an intermediate (possibly abstract) class that would inherit from `Base` and from which `Derived` would be inherited, as follows:
```
class Base
{
}

class GeneratedExtractedClass : Base
{
    public int _testInt;

    public static void TestMethod()
    {
    }
}

class Derived : GeneratedExtractedClass
{
}
```
However, this would be a significant extension of the "Extract Base Class" feature, and would also require the same refactoring to appear when we selected one member, which it currently doesn't. Either way, the refactoring should appear or not appear regardless of whether one or multiple members are selected.

### PR DESCRIPTION
**Pull request by ryzngard**
When the class already has a base, make sure not to offer the refactoring. 

Also fix so that if members are highlighted, we prefer to have them selected by default instead of doing the class only offering. 

Fixes #55610

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/ExtractClass/ExtractClassTests.cs [hunk 1]
```diff
@@ -2521,6 +2521,70 @@ class C
             }.RunAsync();
         }
 
+        [Fact]
+        [WorkItem(55610, "https://github.com/dotnet/roslyn/issues/55610")]
+        public async Task TestMultipleMethodsSelected_WithTypeContainingBaseClass()
```
Comment (genlu) [inline src/EditorFeatures/CSharpTest/ExtractClass/ExtractClassTests.cs:2526]: Looks like the issue was with `TryGetClassActionAsync`, so maybe have another test that select `Derived` as well?

**Review by genlu — APPROVED** [review]
:shipit:
