### PR TITLE
Brace Completion honors the Block IndentStyle

### LINKED ISSUE #2330: Block indenting does not work as expected
Ported from TFS WorkItem: **1161144**

------------------------------

**Repro Steps:**

This item was filed by a customer. Please communicate and close the loop with your customer via the customer tab inside TFS.
  

  

-----------------------
  

Problem Description
  

-----------------------
  

Hi,
  

  

description of &quot;Block indenting&quot; is &quot;When selected and you press ENTER, the new line of text is automatically indented to the same tab stop as the line preceding it.&quot;
  

  

This is not true when using code which has non-standard tabulation preceding the said line. 
  

  

Steps to reproduce:
  

  

* Use Options-&gt;Text Editor -&gt; All languages -&gt; Tabs -&gt; Indenting=block, keep tabs, tabsize=4
  

* Setup a code that is like image1
  

* Put cursor caret where is set in image1
  

* Press enter. Cursor is set as image2 is shown. 
  

  

Expected result: Cursor should be in the same tab stop as preceding line, and should be set to the far left.
  

  

  

image1 : https://dl.dropboxusercontent.com/u/49509038/images/vs2015_ctp6/block_indent_bug/img1.png
  

image2: https://dl.dropboxusercontent.com/u/49509038/images/vs2015_ctp6/block_indent_bug/img2.png

------------------------------

**Revisions:**

1) Created By Microsoft Connect (4/22/2015 3:48:47 AM)

------------------------</br>
Customer Information</br>
------------------------</br>
User ID: 10125130</br>
Handle: KakCAT</br>
</br>
---------------------------</br>
Connect Site Information</br>
---------------------------</br>
Site Name: Visual Studio and .NET Framework</br>
Site ID: 210</br>
Feedback ID: 1269101</br>
Feedback Form: 6049</br>
</br>
----------------------</br>
Problem Description</br>
-----------------------</br>
Hi,

description of &quot;Block indenting&quot; is &quot;When selected and you press ENTER, the new line of text is automatically indented to the same tab stop as the line preceding it.&quot;

This is not true when using code which has non-standard tabulation preceding the said line. 

Steps to reproduce:

* Use Options-&gt;Text Editor -&gt; All languages -&gt; Tabs -&gt; Indenting=block, keep tabs, tabsize=4
* Setup a code that is like image1
* Put cursor caret where is set in image1
* Press enter. Cursor is set as image2 is shown. 

Expected result: Cursor should be in the same tab stop as preceding line, and should be set to the far left.

image1 : https://dl.dropboxusercontent.com/u/49509038/images/vs2015_ctp6/block_indent_bug/img1.png
image2: https://dl.dropboxusercontent.com/u/49509038/images/vs2015_ctp6/block_indent_bug/img2.png

------------------------------

2) Edited By Macy Qu (Shang Hai Wei Chuang Ruan Jian) (4/24/2015 12:00:40 AM)

repro on Win8.1 with VS2015 CTP6

------------------------------

3) Edited By Kevin Pilch-Bisson (4/24/2015 10:16:38 AM)

Is this the same issue as [https://github.com/dotnet/roslyn/issues/2218](https://github.com/dotnet/roslyn/issues/2218)&nbsp;where the indent style setting is not being persisted?

------------------------------

4) Edited By Balaji Soundrarajan (4/24/2015 1:25:34 PM)

We will have to confirm the customer.

&nbsp;

If the user set the option to 'block', closed VS, opened VS, continued to work and saw this behavior then it is the persistance issue. At this point the user believes that the option is set but it is not because we did not persist the option properly.

&nbsp;

Instead if the user sets the option, continues working on VS and sees this behavior then it is a separate bug. 

&nbsp;

I tried latter and there was no issue. VS works as expected. So this seems like the persistance issue. I will have to confirm with the customer.

------------------------------

### PR DESCRIPTION
**Pull request by basoundr**
Fix #2330 Brace Completion and Smart Token Formatter now honors
Formatting Indentation Style 'block'

### CODE REVIEW

File: src/EditorFeatures/CSharp/AutomaticCompletion/Sessions/CurlyBraceCompletionSession.cs [hunk 1]
```diff
@@ -224,6 +224,19 @@ public override AdjustNewLinesOperation GetAdjustNewLinesOperation(SyntaxToken p
                 return base.GetAdjustNewLinesOperation(previousToken, currentToken, optionSet, nextOperation);
             }
 
+            public override void AddAlignTokensOperations(List<AlignTokensOperation> list, SyntaxNode node, OptionSet optionSet, NextAction<AlignTokensOperation> nextOperation)
```
Comment (Pilchie) [inline src/EditorFeatures/CSharp/AutomaticCompletion/Sessions/CurlyBraceCompletionSession.cs]: Why do we have to add this explicitly?  Is it because the formatter normally doesn't do it in block indent?

**Comment by basoundr** [comment]
Reviewers: @jasonmalinowski @Pilchie @dpoeschl @rchande @balajikris @brettfo @jmarolf

File: src/EditorFeatures/CSharp/AutomaticCompletion/Sessions/CurlyBraceCompletionSession.cs (hunk 1 above)
Comment (basoundr) [inline src/EditorFeatures/CSharp/AutomaticCompletion/Sessions/CurlyBraceCompletionSession.cs]: @Pilchie If we dont do it then the closing brace will indent like 'Smart Indenting'(i.e. Normal nested indentation). Block Indentation will expect the 'closing brace' to be at the same indentation as the opening brace. That is why we need to align the braces at the same indentation.

Comment (Pilchie) [inline src/EditorFeatures/CSharp/AutomaticCompletion/Sessions/CurlyBraceCompletionSession.cs]: But the } already aligns with the { when doing smart indenting too, and why is this needed only here in CurlyBraceSession, not also in the base case?

Comment (basoundr) [inline src/EditorFeatures/CSharp/AutomaticCompletion/Sessions/CurlyBraceCompletionSession.cs]: In Smart indentation, we expect the code to be properly nested and indented
Before:
```C#
namespace ns
{
    public class C1
    { $$}
}
```
After Return:
```C#
namespace ns
{
    public class C1
    {
        $$
    }
}
```

In the case of the Block Indentation, we have code like
Before:
```C#
namespace ns
{
public class C1
{ $$}
}
```

Without this change the resultant code After Return will look like
```C#
namespace ns
{
public class C1
{
$$
    }
}
```

This is because the indentation finder thinks that the close brace has to be placed according to the nested indentation. This is not true

Instead we would like to see
```C#
namespace ns
{
public class C1
{
$$
}
}
```

Another Scenario is
Before:
```C#
namespace ns
{
        public class C1
        { $$}
}
```

After:
```C#
namespace ns
{
        public class C1
        {
        $$
        }
}
```

We dont want to see it in the base rules because the closing brace will align with the opening brace everytime the user types '}' individually.

**Comment by sharwell** [comment]
I don't agree with the desired behavior. I believe the desired behavior for the result of your "block" example should be the following:

```cs
namespace ns
{
public class C1
{
$$}
}
```

That said, block indent mode exists for two reasons:

1. A "not as bad as nothing" language-agnostic default for cases where smart indenting (an extraordinarily complicated feature) is not implemented.
2. For cases where smart indent was implemented, but is sufficiently buggy that the default behavior is preferred.

For cases where smart indenting is properly implemented, there is no need to implement block formatting mode aside from the limitation that you cannot disable this radio button in the Visual Studio options service. A better solution for Roslyn would be to allow Block indent to be disabled, and just always use Smart indent (or nothing).

**Comment by Pilchie** [comment]
The fact is that we still have customers who *prefer* block indenting, even though we've had smart indenting since VS2002, so not allowing it is probably not an option.

**Comment by Pilchie** [comment]
:+1:

**Comment by basoundr** [comment]
test this please

**Comment by basoundr** [comment]
test this please
