### PR TITLE
Include ref info for parameters > 16 in synthesized delegate type name

### LINKED ISSUE #55570: The 17th parameter of a synthesized delegate doesn't have ref information encoded
This also affects the 33rd parameter, and presumably 65th etc. but I stopped bothering to check at 33.

**Steps to Reproduce**:

1. Create multiple lambdas for which delegates will be synthesized, with 17 parameters.
2. Make them differ in the ref kinds of the 17th parameter.
3. See SharpLab, observe two delegates being synthesized that are duplicates of each other:
https://sharplab.io/#v2:EYLgtghglgdgPgNwgJwAQH0CMqC8qAUsALhpgDSrEYBMFV6AzHTCegCzOsCsnGAbL3QB2QQA5BATkGYADNPKUWpWotaYmq0h01YeOzANTIApgDN9QgJS4AfKgDeqAL4BuALAAoJGnTVcBegV6FXoNem16PXpDehEdcR0pfTl9IKUsEPT1aQisqKyYmAtrHDtHVyA

**Expected Behavior**:
The synthesized delegates should have different names

**Actual Behavior**:
They share the same name.

This issue is referenced in source.

/cc @cston 

Relates to test plan https://github.com/dotnet/roslyn/issues/52192

### PR DESCRIPTION
**Pull request by cston**
Fixes #55570.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/RefKindVector.cs [hunk 1]
```diff
@@ -85,14 +85,14 @@ public string ToRefKindString()
             builder.Append("{");
 
             int i = 0;
-            foreach (int byRefIndex in this.Words())
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/RefKindVector.cs:88]: >int [](http://example.com/codeflow?start=21&length=3)

`Words()` is `IEnumerable<ulong>`.

Comment (davidwengier) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/RefKindVector.cs:88]: 🤣 I probably should have noticed that when I moved the code

**Review by RikkiGibson — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/RefKindVector.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/RefKindVector.cs:88]: The language/tooling should have guard rails in place to make this harder to do by accident. Unfortunate that there isn't a reasonable place for people to insert an "explicit" cast.

**Review by 333fred — APPROVED** [review]
