### PR TITLE
🔼 Compute indices when OOP is disabled

### LINKED ISSUE #34631: SymbolTreeInfoIncrementalAnalyzerProvider does not run anymore for VSMac
**Version Used**: 
master

**Steps to Reproduce**:

1. Open a solution
2. Expect SymbolTreeInfoIncrementalAnalyzerProvider.IncrementalAnalyzer to run
3. It does not

**Expected Behavior**:
It should run and cache symbol tree infos in the database.

**Actual Behavior**:
It does not, thus making symboltreeinfo operations slower in the IDE.

Regression as of https://github.com/dotnet/roslyn/commit/6f5be2ef2849b22dc185081ed9e389f02b80e473#r32981653

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #34631

### Customer scenario

Solution crawler indexing is disabled in host environments that do not support OOP (e.g. Visual Studio for Mac), or where OOP has been manually disabled (e.g. some customer scenarios for Visual Studio).

### Bugs this fixes

#34631

### Workarounds, if any

None.

### Risk

Low. This does not change behavior for primary host environments where OOP is used.

### Performance impact

No significant impact.

### Is this a regression from a previous update?

Yes.

### Root cause analysis

#31644 (specifically commit 6f5be2ef2849b22dc185081ed9e389f02b80e473) assumed that OOP is supported by the host. This is not always the case, and Visual Studio for Mac scenarios failed as a result.

### How was the bug found?

Reported by developers on Visual Studio for Mac.

### Test documentation updated?

No.

### CODE REVIEW

File: src/Workspaces/Core/Portable/Remote/RemoteFeatureOptions.cs [hunk 1]
```diff
@@ -25,6 +23,16 @@ public static bool ShouldComputeIndex(Workspace workspace)
...
+
+                case WorkspaceKind.Host:
+                    // Compute indices in the host workspace when OOP is disabled.
+                    var remoteHostClientService = workspace.Services.GetService<IRemoteHostClientService>();
+                    if (remoteHostClientService is null)
+                    {
+                        return true;
+                    }
+
+                    return !remoteHostClientService.IsEnabled();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Remote/RemoteFeatureOptions.cs]: are we sure this is ok?  computing indices in the host is expensive (both CPU and memory).  From perf testing it def affects things like typing latency, and can lead to many more GCs, which impacts the rest of the stuff running in VS.

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Remote/RemoteFeatureOptions.cs]: Gotcha.  Though i meant "VS" in the abstract sense.  Namely whatever host we might be in.  But i suppose thems the breaks.  If the host doesn't have an OOP option... they have to live with the perf implication here.

Comment (sharwell) [reply src/Workspaces/Core/Portable/Remote/RemoteFeatureOptions.cs]: @CyrusNajmabadi Some users disabled Roslyn OOP to save system memory even on Windows. This change was a regression for those users which is now being corrected.

File: src/Workspaces/Core/Portable/Remote/RemoteFeatureOptions.cs [hunk 2]
```diff
@@ -25,6 +23,17 @@ public static bool ShouldComputeIndex(Workspace workspace)
                 case WorkspaceKind.RemoteWorkspace:
                     // Always compute indices in the remote workspace.
                     return true;
+
+                case WorkspaceKind.Host:
```
Comment (heejaechang) [inline src/Workspaces/Core/Portable/Remote/RemoteFeatureOptions.cs]: so, you are basically doing what my initial PR did that got closed.

if you are checking existence of remote host to do indexing, you dont need switch in ShouldComputIndex per workspace kind.

just always check remote host existence, if it doesn't return true otherwise, return false.

Comment (heejaechang) [reply src/Workspaces/Core/Portable/Remote/RemoteFeatureOptions.cs]: you can introduce new IsEnabled or you could just do Workspace.TryGetRemoteHostClientAsync and see whether it returns null.

File: src/Workspaces/Core/Portable/Remote/RemoteFeatureOptions.cs [hunk 3]
```diff
@@ -25,6 +23,17 @@ public static bool ShouldComputeIndex(Workspace workspace)
...
+                case WorkspaceKind.MSBuild:
+                    // Compute indices in the host workspace when OOP is disabled.
+                    var remoteHostClientService = workspace.Services.GetService<IRemoteHostClientService>();
```
Comment (heejaechang) [inline src/Workspaces/Core/Portable/Remote/RemoteFeatureOptions.cs]: why the way, this is only called inside of solution crawler and not every workspace register itself to solution crawler. is msbuild now register itself to solution crawler?

Comment (sharwell) [reply src/Workspaces/Core/Portable/Remote/RemoteFeatureOptions.cs]: > is msbuild now register itself to solution crawler?

No, it's covered by the commit message. AnalyzerRunner uses MSBuildWorkspace for targeted testing, and @Therzok and I are working on a new mode in it to run incremental analyzers.

File: src/Workspaces/Core/Portable/Remote/RemoteFeatureOptions.cs (hunk 2 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Remote/RemoteFeatureOptions.cs]: >just always check remote host existence, if it doesn't return true otherwise, return false.

It wasn't clear to me whether temporary and preview workspaces would/should create the index.

**Comment by Therzok** [comment]
Is there anything blocking this from getting merged?

**Comment by Therzok** [comment]
Also, this broke one of our SQLite tests in the dev16.1 release. Is it possible to have this patch applied to dev16.1? cc @slluis @avodovnik @abock

**Comment by KirillOsenkov** [comment]
@jinujoseph @sharwell VSMac is pretty blocked without this PR. Is anything blocking it? We'd need a set of Roslyn NuGet packages with this fix otherwise we can't bump Roslyn to 3.1.

**Comment by heejaechang** [comment]
I just read this - https://github.com/dotnet/roslyn/issues/34631

looks like same issue as this - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/718897

basically, solution crawler doesn't run until a file is opened in VS? 

I believe @jasonmalinowski is working on the fix?

File: src/Workspaces/Core/Portable/Remote/RemoteFeatureOptions.cs (hunk 3 above)
Comment (heejaechang) [reply src/Workspaces/Core/Portable/Remote/RemoteFeatureOptions.cs]: I think you can just do 

```csharp
public static bool ShouldComputeIndex(Workspace workspace)
{
      var remoteHostClientService = workspace.Services.GetService<IRemoteHostClientService>();
      if (remoteHostClientService is null)
                    {
                        return true;
                    }

                     return !remoteHostClientService.IsEnabled();
}
```

**Comment by jinujoseph** [comment]
@ManishJayaswal for approval

**Comment by Therzok** [comment]
Thanks!
