### PR TITLE
Fix for extract interface crash

### LINKED ISSUE #43952: 'ExtractInterfaceCodeRefactoringProvider' encountered an error and has been disabled.
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1014268/extractinterfacecoderefactoringprovider-encountere-1.html)._

---
Visual Studio 2019 16.4.2
Windows Forms VB.Net project.

When I attempt to extract interface on any windows forms class I get the following:
**'ExtractInterfaceCodeRefactoringProvider' encountered an error and has been disabled.**

Stack trace:

```
System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.CodeAnalysis.VisualBasic.ExtractInterface.VisualBasicExtractInterfaceService.CreateFinalSolution(Solution solutionWithInterfaceDocument,IEnumerable`1 documentIds,Dictionary`2 docToRootMap)
   at async Microsoft.CodeAnalysis.VisualBasic.ExtractInterface.VisualBasicExtractInterfaceService.VB$StateMachine_7_UpdateMembersWithExplicitImplementationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractInterface.AbstractExtractInterfaceService.GetSolutionWithOriginalTypeUpdatedAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractInterface.AbstractExtractInterfaceService.ExtractInterfaceToNewFileAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractInterface.AbstractExtractInterfaceService.ExtractInterfaceFromAnalyzedTypeAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractInterface.ExtractInterfaceCodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeActionWithOptions.GetOperationsAsync(<Unknown Parameters>)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass20_0. <InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
```

---
#### Visual Studio Feedback System on 5/3/2020, 01:47 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by allisonchou**
Fixes #43952.

(Thanks to Cyrus for his help with this!)

### CODE REVIEW

File: src/Features/VisualBasic/Portable/ExtractInterface/VisualBasicExtractInterfaceService.vb [hunk 1]
```diff
@@ -90,7 +90,9 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.ExtractInterface
             Dim finalSolution = solutionWithInterfaceDocument
 
             For Each docId In documentIds
-                finalSolution = finalSolution.WithDocumentSyntaxRoot(docId, docToRootMap(docId), PreservationMode.PreserveIdentity)
+                If docToRootMap.ContainsKey(docId) Then
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/ExtractInterface/VisualBasicExtractInterfaceService.vb:93]: add doc that this is just to be resilietn to cases we haven't considered.

**Comment by allisonchou** [comment]
Thank you! :)
