### PR TITLE
Force load projects that failed design time builds, not ones that opt out of LSL

### LINKED ISSUE #19407: DeferredProjectWorkspaceService needs update to do the filtering on IVsSolutionWorkspaceService.GetManagedCommandLineInfoAsync()
IVsSolutionWorkspaceService.GetManagedCommandLineInfoAsync() used to return a dictionary with only valid intellisense data (CommandLineArgs and TargetPath not null or emtpy); the key is the full project path.

For 15.3 Preview 2, we've made the change to return the ManagedCommandLineInfo for all projects in the solution, so that when Roslyn calls this API, it can filter and act upon the projects that don't have valid Intellisense data, e.g. trigger a full load of those projects. Please make sure do the valid check to avoid crash.

### PR DESCRIPTION
**Pull request by Pilchie**
**Customer scenario**

Open a solution with Lightweight solution load enabled, that has project whose design time builds fail.  Roslyn is supposed to trigger a full load of those projects so that either: the legacy design time build works, or it reports appropriate diagnostics.  Unfortunately, a typo mean that we did that only for projects that *also* opt out of LSL.

**Bugs this fixes:**

Fixes #19407 

**Workarounds, if any**

Disable LSL for the solution.

**Risk**

Low - this is new code, and very specific to LSL

**Performance impact**

None - just changing a condition.

**Is this a regression from a previous update?**

No - this was introduced very recently in the first attempt to fix this, just had a typo.

**Root cause analysis:**

How did we miss it?  What tests are we adding to guard against it in the future?

**How was the bug found?**

Validating further LSL scenarios.

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @dotnet/roslyn-ide  for this silly typo :-/

**Comment by Pilchie** [comment]
Hit https://github.com/dotnet/roslyn/issues/19816.

**Comment by Pilchie** [comment]
retest windows_release_vs-integration_prtest please

**Comment by Pilchie** [comment]
Tagging @MattGertz for this embarrassing typo in a recent fix :-/

**Comment by MattGertz** [comment]
Oh, wow -- it's the canonical "it's just a one character fix!" case.  :-)

**Comment by Pilchie** [comment]
@MattGertz Indeed :)

**Comment by Pilchie** [comment]
retest windows_release_vs-integration_prtest please

**Comment by Pilchie** [comment]
Jenkins remoting error.

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker.cs [hunk 1]
```diff
@@ -636,7 +636,7 @@ private void ForceLoadProjectsWhoseDesignTimeBuildFailed(IReadOnlyDictionary<str
             var start = DateTimeOffset.UtcNow;
             var solution4 = (IVsSolution4)_vsSolution;
             var solution7 = (IVsSolution7)_vsSolution;
-            var projectInfosOfProjectsThatFailed = projectInfos.Where(pi => DesignTimeBuildFailed(pi.Value) && !solution7.IsDeferredProjectLoadAllowed(pi.Key));
+            var projectInfosOfProjectsThatFailed = projectInfos.Where(pi => DesignTimeBuildFailed(pi.Value) && solution7.IsDeferredProjectLoadAllowed(pi.Key));
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker.cs]: Could you use !! instead to make the logic clearer?

Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker.cs]: Actually, since !! is clearer, we should do !!!! for twice the clarity.

**Comment by Pilchie** [comment]
Hit https://github.com/dotnet/roslyn/issues/15497.

**Comment by Pilchie** [comment]
retest windows_release_vs-integration_prtest please
