### PR TITLE
Fix static virtual interface members not included in type parameter completion

### LINKED ISSUE #61255: Static virtual members of interfaces are not included into completion list on a type parameter
```
interface I1<T1> where T1 : I1<T1>
{
    static abstract void M1();
    static virtual void M2() { }

    static abstract event System.Action E1;
    static virtual event System.Action E2;

    static abstract int P1 { get; set; }
    static virtual int P2 { get; set; }
}

class Program
{
    void Test<T>() where T : I1<T>
    {
        T.E1 += null;
        T.E2 += null;
        T.M1();
        T.M2();
        T.P1++;
        T.P2++;
        T.   // <= Dot complition offers M1, E1, P1,  but doesn't offer M2, E2, P2
    }
}
```

### LINKED ISSUE #64182: IntelliSense doesn't work for interface statics when dotting a type parameter
This is a bad code I introduced in https://github.com/dotnet/roslyn/pull/53942 :)

`abstractsOnly` local should be removed altogether and the take the "false" code path for any condition relies on it.

Repro from @Sergio0694:

image

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #61255
Fixes #64182

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@arkalyanms we should consider this for 17.4.  This is necessary for the min bar for language feature work. Not sure how it was missed for sign off.

**Comment by arkalyanms** [comment]
Sounds like we have some missing test coverage that we can sync with Richa's team to get overlap.

That aside, for now @CyrusNajmabadi can you please work with @RikkiGibson to get this into 17.4 branch when the change is merged? It looks tight for preview 4.

**Review by arkalyanms — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
> Sounds like we have some missing test coverage that we can sync with Richa's team to get overlap.

i don't think this is really on them to test.  For new language features like this, it's really on the compiler/IDE-buddy to validate and sign-off.

**Comment by CyrusNajmabadi** [comment]
>That aside, for now @CyrusNajmabadi can you please work with @RikkiGibson to get this into 17.4 branch when the change is merged? It looks tight for preview 4. 

WIll do.

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs [hunk 1]
```diff
@@ -11414,9 +11415,10 @@ class Test
     }
 }
 ";
-            await VerifyItemIsAbsentAsync(source, "M0");
+            await VerifyItemExistsAsync(source, "M0");
```
Comment (AlekseyTs) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs:11418]: > await VerifyItemExistsAsync(source, "M0"); [](http://example.com/codeflow?start=11&length=43)

@Youssef1313, @CyrusNajmabadi This change is not expected. Only abstract  or virtual static members can be accessed on a type parameter.

Also, it would be good to include some (virtual/abstract/sealed) instance members to the interfaces and observe that they are not offered.

Comment (Youssef1313) [reply src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs:11418]: → 64733
