### PR TITLE
Made use of extension Add methods in Expression lambdas a compiler error...

### LINKED ISSUE #310: Internal compiler error: collection initializer via extension .Add() method + expression trees
```c#
using System;
using System.Collections.Generic;
using System.Linq.Expressions;

static class StackExtensions {
    public static void Add<T>(this Stack<T> s, T x) => s.Push(x);
}

class Foo {
    Expression<Func<Stack<int>>> E = () => new Stack<int> { 1 };
}
```

> ```
> Object reference not set to an instance of an object.

> at Microsoft.CodeAnalysis.CSharp.BoundNodeExtensions.HasErrors[T](ImmutableArray`1 nodeArray)
> at Microsoft.CodeAnalysis.CSharp.BoundCollectionElementInitializer..ctor(CSharpSyntaxNode syntax, MethodSymbol addMethod, ImmutableArray`1 arguments, Boolean expanded, ImmutableArray`1 argsToParamsOpt, Boolean invokedAsExtensionMethod, LookupResultKind resultKind, TypeSymbol type, Boolean hasErrors)
> at Microsoft.CodeAnalysis.CSharp.BoundCollectionElementInitializer.Update(MethodSymbol addMethod, ImmutableArray`1 arguments, Boolean expanded, ImmutableArray`1 argsToParamsOpt, Boolean invokedAsExtensionMethod, LookupResultKind resultKind, TypeSymbol type)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.MakeCollectionInitializer(BoundExpression rewrittenReceiver, BoundCollectionElementInitializer initializer)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.AddCollectionInitializers(ArrayBuilder`1& dynamicSiteInitializers, ArrayBuilder`1 result, BoundExpression rewrittenReceiver, ImmutableArray`1 initializers)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.MakeObjectOrCollectionInitializersForExpressionTree(BoundExpression initializerExpression)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.MakeObjectCreationInitializerForExpressionTree(BoundExpression initializerExpressionOpt)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitObjectCreationExpression(BoundObjectCreationExpression node)
> at Microsoft.CodeAnalysis.CSharp.BoundObjectCreationExpression.Accept(BoundTreeVisitor visitor)
> at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitExpressionImpl(BoundExpression node)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Visit(BoundNode node)
> at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitReturnStatement(BoundReturnStatement node)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitReturnStatement(BoundReturnStatement node)
> at Microsoft.CodeAnalysis.CSharp.BoundReturnStatement.Accept(BoundTreeVisitor visitor)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Visit(BoundNode node)
> at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.DoVisitList[T](ImmutableArray`1 list)
> at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitList[T](ImmutableArray`1 list)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitBlock(BoundBlock node)
> at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Visit(BoundNode node)
> at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitLambda(BoundLambda node)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitLambda(BoundLambda node)
> at Microsoft.CodeAnalysis.CSharp.BoundLambda.Accept(BoundTreeVisitor visitor)
> at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitExpressionImpl(BoundExpression node)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitExpression(BoundExpression node)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitConversion(BoundConversion node)
> at Microsoft.CodeAnalysis.CSharp.BoundConversion.Accept(BoundTreeVisitor visitor)
> at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitExpressionImpl(BoundExpression node)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitExpression(BoundExpression node)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitAssignmentOperator(BoundAssignmentOperator node, Boolean used)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitUnusedExpression(BoundExpression expression)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitExpressionStatement(BoundExpressionStatement node)
> at Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement.Accept(BoundTreeVisitor visitor)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Visit(BoundNode node)
> at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitSequencePointWithSpan(BoundSequencePointWithSpan node)
> at Microsoft.CodeAnalysis.CSharp.BoundSequencePointWithSpan.Accept(BoundTreeVisitor visitor)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Visit(BoundNode node)
> at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.DoVisitList[T](ImmutableArray`1 list)
> at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitList[T](ImmutableArray`1 list)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitTypeOrInstanceInitializers(BoundTypeOrInstanceInitializers node)
> at Microsoft.CodeAnalysis.CSharp.BoundTypeOrInstanceInitializers.Accept(BoundTreeVisitor visitor)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Visit(BoundNode node)
> at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Rewrite(CSharpCompilation compilation, MethodSymbol method, Int32 methodOrdinal, NamedTypeSymbol containingType, BoundStatement statement, TypeCompilationState compilationState, SynthesizedSubmissionFields previousSubmissionFields, Boolean allowOmissionOfConditionalCalls, DiagnosticBag diagnostics, Boolean& sawLambdas, Boolean& sawAwaitInExceptionHandler)
> at Microsoft.CodeAnalysis.CSharp.MethodCompiler.LowerBodyOrInitializer(MethodSymbol method, Int32 methodOrdinal, BoundStatement body, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState, DiagnosticBag diagnostics, VariableSlotAllocator& lazyVariableSlotAllocator, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, StateMachineTypeSymbol& stateMachineTypeOpt)
> at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
> at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol symbol)
> at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass21_0.<CompileNamedTypeAsTask>b__0()
> at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0()
> at System.Threading.Tasks.Task.InnerInvoke()
> at System.Threading.Tasks.Task.Execute()
> ```

### PR DESCRIPTION
**Pull request by VSadov**
....

Expression Trees specifically require that element initializer methods are instance methods.
Fixes #310

### CODE REVIEW

**Comment by VSadov** [comment]
@AlekseyTs @gafter  , Could you take a look?

File: src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs [hunk 1]
```diff
@@ -22237,6 +22237,46 @@ public void DictionaryInitializerInExprLambda1()
...
+            CreateCompilationWithMscorlib45(text, new[] { SystemRef_v4_0_30319_17929, SystemCoreRef_v4_0_30319_17929, CSharpRef }).VerifyDiagnostics(
+    // (25,72): error CS8075: An expression tree lambda may not contain an extension collection element initializer.
+    //         public Expression<Func<Stack<int>>> E = () => new Stack<int> { 42 };
+    Diagnostic(ErrorCode.ERR_ExtensionCollectionElementInitializerInExpressionTree, "42").WithLocation(25, 72)
+               );
+        }
+
+        [WorkItem(310, "https://github.com/dotnet/roslyn/issues/310")]
+        [Fact]
+        public void ExtensionElementInitializerInExpressionLambda()
```
Comment (VladimirReshetnikov) [inline src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs]: Something wrong with this diff? This looks like the new test method declaration, but its intended body is shown above... GitHub does not want to show the full file.

File: src/Compilers/CSharp/Portable/CSharpResources.resx [hunk 2]
```diff
@@ -4544,6 +4544,9 @@ To remove the warning, you can use /reference instead (set the Embed Interop Typ
   <data name="ERR_DictionaryInitializerInExpressionTree" xml:space="preserve">
     <value>An expression tree lambda may not contain a dictionary initializer.</value>
   </data>
+  <data name="ERR_ExtensionCollectionElementInitializerInExpressionTree" xml:space="preserve">
+    <value>An expression tree lambda may not contain an extension collection element initializer.</value>
```
Comment (VladimirReshetnikov) [inline src/Compilers/CSharp/Portable/CSharpResources.resx]: The message is a little confusing. If I didn't know what it means, I would probably have troubles with figuring it out.

Comment (gafter) [inline src/Compilers/CSharp/Portable/CSharpResources.resx]: I agree. Perhaps "An extension Add method is not supported for an object initializer in an expression lambda"

File: src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs]: Looks right to me

**Comment by gafter** [comment]
Looks good assuming you reword the diagnostic text as suggested.

File: src/Compilers/CSharp/Portable/CSharpResources.resx (hunk 2 above)
Comment (VSadov) [inline src/Compilers/CSharp/Portable/CSharpResources.resx]: An extension Add method is not supported for a _collection_ initializer in an expression lambda

**Comment by VladimirReshetnikov** [comment]
:+1: assuming rewording of the message.

**Comment by VladimirReshetnikov** [comment]
:+1:

**Comment by AlekseyTs** [comment]
Does VB have the same issue?

**Comment by VSadov** [comment]
Yes, turns out VB has similar issue as well. I will be entering a separate bug to track that. We may need a different fix there since the equivalent VB code used to compile in previous versions (even though it could not run). Making it a compile error for VB could be considered a compat breaker, so there is more to think about.

**Comment by VSadov** [comment]
VB bug is #1190
