### PR TITLE
Avoid assembly name resolution when loading analyzer type

### LINKED ISSUE #3347: Roslyn changed how Analyzer assemblies are loaded.  TypeScript analyzers no longer loading.
PR https://github.com/dotnet/roslyn/pull/2882 switched the code for loading Analyzer assemblies from:

```c#
                    var type = analyzerAssembly.GetType(typeName);
                    if (DerivesFromDiagnosticAnalyzer(type))
                    {
                        analyzer = (DiagnosticAnalyzer)Activator.CreateInstance(type);
                    }
```

To:

```c#
                    type = Type.GetType(typeName + ", " + analyzerAssembly.FullName, throwOnError: true);
```

However, this now fails to load the TypeScript as we are not in any binding path.  This is high pri as all TypeScript diagnostic scenarios (squiggles/error-list) are broken.

### PR DESCRIPTION
**Pull request by tmat**
Fixes #3347.

**Scenario**
TypeScript got broken by my previous change in analyzer loading logic. I didn't realize that we load analyzers to "load-from" context which is not where Type.GetType(assembly-qualified-name) is looking for assemblies. 

**Fix**
The purpose of the previous change was to communicate the load exception to the user. Unfortunately, portable profile 7 doesn't have the overload of Assembly.GetType that throws (hence the change to Type.GetType, which does). Turns out that the method is actually available on CoreCLR, so we can use the PortableShim to invoke it thru reflection to retrieve a good error message.

**Testing**
Added unit tests and verified that TS analyzer works as expected.

@ManishJayaswal

### CODE REVIEW

**Comment by tmat** [comment]
@jaredpar Could you review the reflection shim?
@tmeschter @mavasani

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs [hunk 1]
```diff
@@ -277,10 +277,12 @@ private IEnumerable<DiagnosticAnalyzer> GetAnalyzersForTypeNames(Assembly analyz
                 Type type;
                 try
                 {
-                    type = Type.GetType(typeName + ", " + analyzerAssembly.FullName, throwOnError: true);
+                    type = analyzerAssembly.GetType(typeName) ??
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs]: Consider documenting why we do things this way.  i.e. "analyzer.GetType" is the most robust method (since it doesn't need binding paths and all that goop).  But if it fails, you get nothing but "null".  Then the rest of the code can try to get a decent error if possible.

Comment (tmat) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs]: Done.

**Comment by tmeschter** [comment]
LGTM

File: src/Compilers/Core/Portable/PortableShim.cs [hunk 2]
```diff
@@ -434,5 +435,18 @@ internal static void SetCurrentUICulture(CultureInfo cultureInfo)
...
+        {
+            private const string TypeName = "System.Reflection.Assembly";
+
+            internal static readonly Type Type = ReflectionUtil.GetTypeFromEither(
+                contractName: $"{TypeName}, {CoreNames.System_Reflection}",
+                desktopName: TypeName);
+
+            internal static readonly MethodInfo GetTypeThrowOnErrorIgnoreCase = Type
+                .GetTypeInfo()
+                .GetDeclaredMethod("GetType", typeof(string), typeof(bool), typeof(bool));
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/PortableShim.cs]: Can we use CreateDelegate here to make this a direct call to GetType?  That would avoid a TargetInvocattionException on error.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs [hunk 3]
```diff
@@ -277,10 +277,14 @@ private IEnumerable<DiagnosticAnalyzer> GetAnalyzersForTypeNames(Assembly analyz
...
                 {
-                    type = Type.GetType(typeName + ", " + analyzerAssembly.FullName, throwOnError: true);
+                    // TODO: Once we move to CoreCLR we should just call GetType(typeName, throwOnError: true, ignoreCase: false) directly.
+                    // For now we fall back to reflection shim in order to report good error message (type load exception).
+                    type = analyzerAssembly.GetType(typeName) ?? 
+                           (Type)PortableShim.Assembly.GetTypeThrowOnErrorIgnoreCase.Invoke(analyzerAssembly, new object[] { typeName, true, false });
                 }
                 catch (Exception e)
                 {
+                    e = (e as TargetInvocationException)?.InnerException ?? e;
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs]: I believe if we use CreateDelegate below we can avoid this check

File: src/Compilers/Core/Portable/PortableShim.cs [hunk 4]
```diff
@@ -434,5 +435,18 @@ internal static void SetCurrentUICulture(CultureInfo cultureInfo)
...
+
+        internal static class Assembly
+        {
+            private const string TypeName = "System.Reflection.Assembly";
+
+            internal static readonly Type Type = ReflectionUtil.GetTypeFromEither(
+                contractName: $"{TypeName}, {CoreNames.System_Reflection}",
+                desktopName: TypeName);
+
+            internal static readonly MethodInfo GetTypeThrowOnErrorIgnoreCase = Type
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/PortableShim.cs]: For methods with overloads we try and spell out the name here vs. using a different name.  For example; GetType_string_bool_bool

File: src/Compilers/Core/Portable/PortableShim.cs (hunk 2 above)
Comment (tmat) [inline src/Compilers/Core/Portable/PortableShim.cs]: Yes, good point.

File: src/Compilers/Core/Portable/PortableShim.cs (hunk 4 above)
Comment (tmat) [inline src/Compilers/Core/Portable/PortableShim.cs]: The problem is that it's not clear from the call site what the booleans mean. Can't use named parameters unless I define a custom delegate type, which feels like an overkill.

Comment (tmat) [inline src/Compilers/Core/Portable/PortableShim.cs]: @jaredpar I guess I can do
```
const bool throwOnError = true;
const bool ignoreCase = false;
type = analyzerAssembly.GetType(typeName) ?? 
                           PortableShim.Assembly.GetType_string_bool_bool(analyzerAssembly, typeName, throwOnError, ignoreCase);
```

Comment (jaredpar) [inline src/Compilers/Core/Portable/PortableShim.cs]: I agree it's not great as a call site annotation.  But this is only temporary.  Once we switch to 4.6 these will become named arguments.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs [hunk 5]
```diff
@@ -277,7 +277,13 @@ private IEnumerable<DiagnosticAnalyzer> GetAnalyzersForTypeNames(Assembly analyz
...
                 try
                 {
-                    type = Type.GetType(typeName + ", " + analyzerAssembly.FullName, throwOnError: true);
+                    // TODO: Once we move to CoreCLR we should just call GetType(typeName, throwOnError: true, ignoreCase: false) directly.
+                    // For now we fall back to reflection shim in order to report good error message (type load exception).
+                    const bool throwOnError = true;
+                    const bool ignoreCase = false;
+
+                    type = analyzerAssembly.GetType(typeName) ?? 
+                           PortableShim.Assembly.GetType_string_bool_bool(analyzerAssembly, typeName, throwOnError, ignoreCase);
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs]: Why not always go through `GetType(string, bool, bool)` method?

Comment (tmat) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs]: To avoid reflection, but I guess we can.

Comment (jaredpar) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerFileReference.cs]: @tmat i think the reflection cost would be low.  We pay the one time cost to get the method but after that the `CreateDelegate` call makes it essentially 0 cost.

**Comment by MattGertz** [comment]
Approved 6/8 by ML Shiproom.
