### PR TITLE
Handle OperatorDeclaration when adding a member

### LINKED ISSUE #67019: `SyntaxGenerator`: cannot add an operator member declaration to an interface declaration
**Version Used**: main

**Steps to Reproduce**:

1. Create interface declaration
2. Create operator declaration
3. Add member to an interface: `syntaxGenerator.AddMembers(interfaceDeclaration, operatorDeclaration);`

`CSharpSyntaxGenerator.AsInterfaceMember` [(link)](https://github.com/dotnet/roslyn/blob/main/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L801-L847) does not handle members with `SyntaxKind.OperatorDeclaration` as a result exception thrown:
> System.InvalidOperationException: Unexpected value 'OperatorDeclaration' of type 'Microsoft.CodeAnalysis.CSharp.SyntaxKind'

Example:

**Diagnostic Id**:

**Expected Behavior**:

```C#
switch (member.Kind())
{
    case SyntaxKind.OperatorDeclaration:
        return ((OperatorDeclarationSyntax)member)
                 .WithModifiers(default)
                 .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken))
                 .WithBody(null);
}
```

**Actual Behavior**:

### PR DESCRIPTION
**Pull request by sdelarosbil**
Closes #67019 

Added an assert in the appropriate test to make sure it no longer throws and actually handles this case.

### CODE REVIEW

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs [hunk 1]
```diff
@@ -802,6 +802,12 @@ internal override SyntaxNode AsInterfaceMember(SyntaxNode m)
                                  .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken))
                                  .WithBody(null);
 
+                    case SyntaxKind.OperatorDeclaration:
+                        return ((OperatorDeclarationSyntax)member)
+                                 .WithModifiers(default)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs:807]: doesn't is need to be declared static at least?

also, are conversion ops allowed?  not sure what the rules are there.

Comment (sdelarosbil) [reply src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs:807]: For the static modifier, yes and it seems it also requires the public one.

For the conversion, no they aren't allowed in interfaces (in general, you can't have an interface type to be to and from).

If these rules are important to be enforced for the generator, show should they be? I could put public + static on the modifier since it seems fine, but what about the conversion ones? Do we throw an exception because it can't be handled?

Comment (CyrusNajmabadi) [reply src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs:807]: well, you can filter out other modifiers, but keep the allowed ones.  or you can force adding those modifiers if they're literally always required.

Comment (sdelarosbil) [reply src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs]: Ended up doing a bit of both: static is always required so I add it no matter.

But public can be implicit if omitted so this one, I allow it if it was present.

For abstract and virtual, one of the 2 is required because of how this type of member works in an interface so I also allow them to stay.

Doe this suitable?

File: src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs [hunk 2]
```diff
@@ -2736,6 +2736,7 @@ public void TestAddMembers()
             AssertMemberNamesEqual("m", Generator.AddMembers(Generator.ClassDeclaration("d"), [Generator.MethodDeclaration("m")]));
             AssertMemberNamesEqual("m", Generator.AddMembers(Generator.StructDeclaration("s"), [Generator.MethodDeclaration("m")]));
             AssertMemberNamesEqual("m", Generator.AddMembers(Generator.InterfaceDeclaration("i"), [Generator.MethodDeclaration("m")]));
+            AssertMemberNamesEqual("", Generator.AddMembers(Generator.InterfaceDeclaration("i"), [Generator.OperatorDeclaration(OperatorKind.Addition)]));
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs:2739]: i'm not seeing any tests that actually show what was actually generated.

Comment (sdelarosbil) [reply src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs:2739]: There doesn't seem to be much in this file in general and in this test.

Is it fine that I call VerifySyntaxRaw just for this? I didn't added them originally because it seemed out of place. I thought the goal of this test excluded sources since I didn't see any.

Comment (CyrusNajmabadi) [reply src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs:2739]: There are test files for Syntax generator that do validate the source generated.  Can you add tests to those?

Comment (sdelarosbil) [reply src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs]: There I added one for the operator member in interface

**Comment by sdelarosbil** [comment]
Had to rebase + force push due to conflicts resolution

File: src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs [hunk 3]
```diff
@@ -2736,6 +2736,15 @@ public void TestAddMembers()
...
             AssertMemberNamesEqual("m", Generator.AddMembers(Generator.InterfaceDeclaration("i"), [Generator.MethodDeclaration("m")]));
+            var interfaceOperator = Generator.AddMembers(Generator.InterfaceDeclaration("i"),
+                [Generator.OperatorDeclaration(OperatorKind.Addition)]);
+            VerifySyntax<InterfaceDeclarationSyntax>(interfaceOperator,
+                """
+                interface i
+                {
+                    static void operator +();
+                }
+                """);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs:2747]: tests with absrtact/static/virtual please.  i'd just make thsi a new test method also btw.

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs [hunk 4]
```diff
@@ -802,6 +802,18 @@ internal override SyntaxNode AsInterfaceMember(SyntaxNode m)
...
                              .WithBody(null);
 
+                case SyntaxKind.OperatorDeclaration:
+                    var operatorDeclaration = (OperatorDeclarationSyntax)member;
+                    var abstractVirtualModifiers = operatorDeclaration.Modifiers.Where(x =>
+                        x.Kind() == SyntaxKind.AbstractKeyword
+                        || x.Kind() == SyntaxKind.VirtualKeyword
+                        || x.Kind() == SyntaxKind.PublicKeyword);
+                    return operatorDeclaration
+                        .WithModifiers(SyntaxTokenList.Create(abstractVirtualModifiers.ToArray()))
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs:812]: is this .ToArray necessary?  if so, can you do SyntaxFactory.TokenList(abstractVirtualModifiers)

Comment (sdelarosbil) [reply src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs]: done

File: src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs (hunk 3 above)
Comment (sdelarosbil) [reply src/Workspaces/CSharpTest/CodeGeneration/SyntaxGeneratorTests.cs]: done, had to ensure static came first.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by CyrusNajmabadi** [comment]
Thanks!
