### PR TITLE
Fix race in VBCSCompiler test

### LINKED ISSUE #41788: VBCSCompiler unit test crashed with NRE on MacOS
PR build: https://dev.azure.com/dnceng/public/_build/results?buildId=528214

Seems like `registeredHandle` here might not be assigned a value before it is read from the lambda:

https://github.com/dotnet/roslyn/blob/master/src/Compilers/Server/VBCSCompilerTests/Extensions.cs#L28

Stack:

```
xUnit.net Console Runner v2.4.1-pre.build.4059 (64-bit .NET Core 3.1.0)
[37m  Discovering: VBCSCompiler.UnitTests
[m[37m  Discovered:  VBCSCompiler.UnitTests
[m[37m  Starting:    VBCSCompiler.UnitTests
[mUnhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CompilerServer.UnitTests.Extensions.<>c__DisplayClass0_0.<ToTask>b__0(Object _, Boolean timedOut) in /_/src/Compilers/Server/VBCSCompilerTests/Extensions.cs:line 28
   at System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context(Object state, Boolean timedOut)
   at System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context_f(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(_ThreadPoolWaitOrTimerCallback helper, Boolean timedOut)
=== COMMAND LINE ===
"/Users/runner/runners/2.164.8/work/1/s/.dotnet/dotnet" exec --depsfile "/Users/runner/runners/2.164.8/work/1/s/artifacts/bin/VBCSCompiler.UnitTests/Debug/netcoreapp3.1/VBCSCompiler.UnitTests.deps.json" --runtimeconfig "/Users/runner/runners/2.164.8/work/1/s/artifacts/bin/VBCSCompiler.UnitTests/Debug/netcoreapp3.1/VBCSCompiler.UnitTests.runtimeconfig.json"  "/Users/runner/runners/2.164.8/work/1/s/.packages/xunit.runner.console/2.4.1-pre.build.4059/tools/netcoreapp2.0/xunit.console.dll" "/Users/runner/runners/2.164.8/work/1/s/artifacts/bin/VBCSCompiler.UnitTests/Debug/netcoreapp3.1/VBCSCompiler.UnitTests.dll" -noautoreporters -xml "/Users/runner/runners/2.164.8/work/1/s/artifacts/TestResults/Debug/VBCSCompiler.UnitTests_netcoreapp3.1_x64.xml" -html "/Users/runner/runners/2.164.8/work/1/s/artifacts/TestResults/Debug/VBCSCompiler.UnitTests_netcoreapp3.1_x64.html"  > "/Users/runner/runners/2.164.8/work/1/s/artifacts/log/Debug/VBCSCompiler.UnitTests_netcoreapp3.1_x64.log" 2>&1

```

### PR DESCRIPTION
**Pull request by jaredpar**
Need to account for the case that the callback executes before the handle is assigned. Or that the handle is visible in the call back.

closes #41788

### CODE REVIEW

**Comment by jaredpar** [comment]
@dotnet/roslyn-compiler  PTAL

File: src/Compilers/Server/VBCSCompilerTests/Extensions.cs [hunk 1]
```diff
@@ -14,16 +14,16 @@ namespace Microsoft.CodeAnalysis.CompilerServer.UnitTests
...
+            var tcs = new TaskCompletionSource<object>();
             registeredHandle = ThreadPool.RegisterWaitForSingleObject(
                 handle,
-                (_, timedOut) =>
+                (_, timeout) =>
                 {
-                    tcs.TrySetResult(!timedOut);
-                    if (!timedOut)
+                    tcs.TrySetResult(null);
+                    if (registeredHandle is object)
```
Comment (gafter) [inline src/Compilers/Server/VBCSCompilerTests/Extensions.cs]: >registeredHandle [](start = 24, length = 16)

This `if` statement could be written `registeredHandle?.Unregister(waitObject: null);`
