### PR TITLE
Remove an incorrect ContainsDiagnostics test in LanguageParser

### LINKED ISSUE #13667: Untested code in parsing tuples.
The following code appears in `LanguageParser.cs`:

```cs
                if (!result.ContainsDiagnostics && list.Count < 2)
                {
                    result = this.AddError(result, ErrorCode.ERR_TupleTooFewElements);
                }
```

but the condition `result.ContainsDiagnostics` doesn't make a difference in any compiler tests. It should probably be removed or tested.

(Note that `ContainsDiagnostics` does not test for errors in the node, or even errors anywhere beneath the node)

### PR DESCRIPTION
**Pull request by gafter**
by which the presence of a nested warning could suppress
what should be an error. Also adds a test for #13719, which is
related.
Fixes #13667 

@VSadov @jcouv @dotnet/roslyn-compiler Please review
@jaredpar You might want to look at this too, since you were ***sooooo*** interested in the issue ;)

### CODE REVIEW

**Comment by jcouv** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 1]
```diff
@@ -6572,7 +6572,7 @@ private TupleTypeSyntax ParseTupleType()
                 var close = this.EatToken(SyntaxKind.CloseParenToken);
                 var result = _syntaxFactory.TupleType(open, list, close);
 
-                if (!result.ContainsDiagnostics && list.Count < 2)
+                if (list.Count < 2)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: >if (list.Count < 2) [](start = 16, length = 19)

It looks like a change here isn't covered by the new unit-tests. Is it possible to add one?

File: src/Compilers/CSharp/Test/Syntax/Parsing/ParserRegressionTests.cs [hunk 2]
```diff
@@ -107,5 +108,35 @@ public void ThrowInInvocationCompletes()
 
             SyntaxFactory.ParseExpression(code);
         }
+
+        [Fact(Skip = "https://github.com/dotnet/roslyn/issues/13719")]
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Syntax/Parsing/ParserRegressionTests.cs]: >Fact [](start = 9, length = 4)

Please add a WorkItem attribute.

**Comment by AlekseyTs** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: The change here is covered by existing unit tests that were modified.

---
In reply to: [78417858](https://github.com/dotnet/roslyn/pull/13720#discussion_r78417858) [](ancestors = 78417858)

File: src/Compilers/CSharp/Test/Syntax/Parsing/ParserRegressionTests.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Syntax/Parsing/ParserRegressionTests.cs]: This is the long-standing convention for unit tests: `Skip` points to a bug report, and a `WorkItem` attribute is added when it is fixed (it might be this issue or it might be another). I'd rather continue with the current conventions.

---
In reply to: [78419151](https://github.com/dotnet/roslyn/pull/13720#discussion_r78419151) [](ancestors = 78419151)

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Syntax/Parsing/ParserRegressionTests.cs]: I don't believe this is the convention that we were using, WorkItem attribute is always required.
