### PR TITLE
Catch exceptions from user code

### LINKED ISSUE #898: All Analyzer entry points need to be audited to make sure that every one is wrapped in a catch-all exception handler
Analyzer exceptions (even from the analyzer engine) should never propagate exceptions into the compiler  (see #865 for an example) and every entry point into analyer code, including things like hooking assembly load, need to be audited for this.

### PR DESCRIPTION
**Pull request by tmeschter**
The Solution Explorer calls `DiagnosticAnalyzer.SupportedDiagnostics` to
determine the list of items to show. This property is implemented by a
3rd-party (the analyzer author) and could potentially throw.

Here we move to using the `DiagnosticAnalyzerService` to obtain this
data; it will catch any exceptions and handle reporting them to the user
as appropriate.

Fixes #898.

### CODE REVIEW

**Comment by tmeschter** [comment]
@srivatsn @shyamnamboodiripad @mavasani @jmarolf @heejaechang @JohnHamby Could you take a look at this, please?

**Comment by mavasani** [comment]
:+1:

File: src/VisualStudio/Core/SolutionExplorerShim/DiagnosticItem/DiagnosticItemProvider.cs [hunk 1]
```diff
@@ -15,11 +16,14 @@ internal sealed class DiagnosticItemProvider : AttachedCollectionSourceProvider<
...
 
+        [Import]
+        private IDiagnosticAnalyzerService _diagnosticAnalyzerService = null;
+
         protected override IAttachedCollectionSource CreateCollectionSource(AnalyzerItem item, string relationshipName)
         {
             if (relationshipName == KnownRelationships.Contains)
             {
-                return new DiagnosticItemSource(item, _commandHandler);
+                return new DiagnosticItemSource(item, _commandHandler, (DiagnosticAnalyzerService)_diagnosticAnalyzerService);
```
Comment (JohnHamby) [inline src/VisualStudio/Core/SolutionExplorerShim/DiagnosticItem/DiagnosticItemProvider.cs]: If this cast is safe, why isn't the type of the field DiagnosticAnalyzerService?

Comment (mavasani) [inline src/VisualStudio/Core/SolutionExplorerShim/DiagnosticItem/DiagnosticItemProvider.cs]: We should also consider just adding the GetDiagnosticDescriptors(Analyzer) method to IDiagnosticAnalyzerService interface.

File: src/VisualStudio/Core/SolutionExplorerShim/DiagnosticItem/DiagnosticItemProvider.cs [hunk 2]
```diff
@@ -15,11 +16,14 @@ internal sealed class DiagnosticItemProvider : AttachedCollectionSourceProvider<
         [Import(typeof(AnalyzersCommandHandler))]
         private IAnalyzersCommandHandler _commandHandler = null;
 
+        [Import]
+        private IDiagnosticAnalyzerService _diagnosticAnalyzerService = null;
```
Comment (JohnHamby) [inline src/VisualStudio/Core/SolutionExplorerShim/DiagnosticItem/DiagnosticItemProvider.cs]: How does this field ever get a value other than null?

**Comment by JohnHamby** [comment]
I sign off, because this is surely a good thing,

File: src/VisualStudio/Core/SolutionExplorerShim/DiagnosticItem/DiagnosticItemProvider.cs (hunk 2 above)
Comment (tmeschter) [inline src/VisualStudio/Core/SolutionExplorerShim/DiagnosticItem/DiagnosticItemProvider.cs]: Yes, this is MEF magic.

**Comment by jmarolf** [comment]
:+1:

File: src/VisualStudio/Core/SolutionExplorerShim/DiagnosticItem/DiagnosticItemProvider.cs (hunk 1 above)
Comment (heejaechang) [inline src/VisualStudio/Core/SolutionExplorerShim/DiagnosticItem/DiagnosticItemProvider.cs]: can we just do that as part of this change?

**Comment by heejaechang** [comment]
:+1: 

@tmeschter @mavasani Tom, can you just add the method as part of the interface?

**Comment by tmeschter** [comment]
@dotnet-bot Retest this, please.

**Comment by tmeschter** [comment]
@heejaechang @mavasani I'll add the method to the interface.
