### PR TITLE
Fix #26358: AbstractDocumentationCommentCommandHandler has hardcoded Windows line ending

### LINKED ISSUE #26358: AbstractDocumentationCommentCommandHandler has hardcoded Windows line ending
**Version Used**: 
Any, 2.8.0-beta2-62708-11. Commit Hash: 88b12d42989e880e935be246dba802678f4ea226

**Steps to Reproduce**:

1. Set TextBuffer option "NewLineCharacter" to "\n"
2. Type `///` above method/class
3. Observe that documentation is inserted with "\r\n"

**Expected Behavior**:
Documentation respects "NewLineCharacter" option
**Actual Behavior**:
Documentation doesn't respect "NewLineCharacter" option

Problem is at https://github.com/dotnet/roslyn/blob/aa892f0/src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs#L82

### PR DESCRIPTION
**Pull request by DavidKarlas**
I used `\n` and `\r\n` in string instead `@""` because as far as I understand on Windows/CI code is checked out with `git config core.autocrlf` which means it modifies line endings...

### Customer scenario

If customer uses `\n` for line endings and has appropriate formatting setting set, every time documentation after `///` is inserted it inserted `\r\n` wrongly.

### Bugs this fixes

#26358

### Workarounds, if any

None.

### Risk

Fix is pretty small, so I would say it's unlikely to cause regressions.

### Performance impact

I don't expect changes

### Is this a regression from a previous update?

No.

### Root cause analysis

There was commented code that would support thiis, so I would assume reason was just not caring about `\n` scenario. Unit test is added.

### How was the bug found?

While integrating this command with VSfM.

### Test documentation updated?

Unit tests should be sufficient.

### CODE REVIEW

**Comment by DavidKarlas** [comment]
Hmm, looks like unit tests infrastructure just replace `\n` with `\r\n`, not sure how to unit test this, should I disable my new unit test until infrastructure is updated to handle working with `\n`, problem is at https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/TestUtilities/Extensions/XElementExtensions.cs#L12 ...
```
>	Roslyn.Services.Test.Utilities.dll!Microsoft.CodeAnalysis.Editor.UnitTests.Extensions.XElementExtensions.NormalizedValue(System.Xml.Linq.XElement element) Line 12	C#
 	Roslyn.Services.Test.Utilities.dll!Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.CreateDocument(Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace workspace, System.Xml.Linq.XElement workspaceElement, System.Xml.Linq.XElement documentElement, string language, Microsoft.VisualStudio.Composition.ExportProvider exportProvider, Microsoft.CodeAnalysis.Host.HostLanguageServices languageServiceProvider, System.Collections.Generic.Dictionary<string, Microsoft.VisualStudio.Text.ITextBuffer> filePathToTextBufferMap, ref int documentId) Line 648	C#
 	Roslyn.Services.Test.Utilities.dll!Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.CreateProject(System.Xml.Linq.XElement workspaceElement, System.Xml.Linq.XElement projectElement, Microsoft.VisualStudio.Composition.ExportProvider exportProvider, Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace workspace, System.Collections.Generic.Dictionary<System.Xml.Linq.XElement, string> documentElementToFilePath, System.Collections.Generic.Dictionary<string, Microsoft.VisualStudio.Text.ITextBuffer> filePathToTextBufferMap, ref int projectId, ref int documentId) Line 298	C#
 	Roslyn.Services.Test.Utilities.dll!Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Create(System.Xml.Linq.XElement workspaceElement, bool completed, bool openDocuments, Microsoft.VisualStudio.Composition.ExportProvider exportProvider, string workspaceKind) Line 99	C#
 	Roslyn.Services.Test.Utilities.dll!Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.Create(string language, Microsoft.CodeAnalysis.CompilationOptions compilationOptions, Microsoft.CodeAnalysis.ParseOptions parseOptions, string[] files, Microsoft.VisualStudio.Composition.ExportProvider exportProvider, string[] metadataReferences, string workspaceKind, string extension, bool commonReferences, bool openDocuments) Line 166	C#
 	Roslyn.Services.Test.Utilities.dll!Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.CreateCSharp(string[] files, Microsoft.CodeAnalysis.ParseOptions parseOptions, Microsoft.CodeAnalysis.CompilationOptions compilationOptions, Microsoft.VisualStudio.Composition.ExportProvider exportProvider, string[] metadataReferences, bool openDocuments) Line 231	C#
 	Roslyn.Services.Test.Utilities.dll!Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace.CreateCSharp(string file, Microsoft.CodeAnalysis.ParseOptions parseOptions, Microsoft.CodeAnalysis.CompilationOptions compilationOptions, Microsoft.VisualStudio.Composition.ExportProvider exportProvider, string[] metadataReferences, bool openDocuments) Line 220	C#
 	Roslyn.Services.Editor.CSharp.UnitTests.dll!Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.DocumentationComments.DocumentationCommentTests.CreateTestWorkspace(string code) Line 1947	C#
 	Roslyn.Services.Test.Utilities.dll!Microsoft.CodeAnalysis.Editor.UnitTests.DocumentationComments.AbstractDocumentationCommentTests.Verify(string initialMarkup, string expectedMarkup, bool useTabs, bool autoGenerateXmlDocComments, System.Action<Microsoft.VisualStudio.Text.Editor.IWpfTextView, Microsoft.VisualStudio.Text.Operations.ITextUndoHistoryRegistry, Microsoft.VisualStudio.Text.Operations.IEditorOperationsFactoryService, Microsoft.CodeAnalysis.Editor.IAsyncCompletionService> execute, System.Action<Microsoft.CodeAnalysis.Editor.UnitTests.Workspaces.TestWorkspace> setOptionsOpt, string newLine) Line 125	C#
 	Roslyn.Services.Test.Utilities.dll!Microsoft.CodeAnalysis.Editor.UnitTests.DocumentationComments.AbstractDocumentationCommentTests.VerifyTypingCharacter(string initialMarkup, string expectedMarkup, bool useTabs, bool autoGenerateXmlDocComments, string newLine) Line 34	C#
 	Roslyn.Services.Editor.CSharp.UnitTests.dll!Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.DocumentationComments.DocumentationCommentTests.TypingCharacter_Class_NewLine() Line 45	C#
```

**Comment by DavidKarlas** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please
and don't fail, thank you

**Comment by DavidKarlas** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

File: src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs [hunk 1]
```diff
@@ -76,12 +76,6 @@ private char TriggerCharacter
 
         public string DisplayName => EditorFeaturesResources.Documentation_Comment;
 
-        private string GetNewLine(SourceText text)
-        {
-            // return editorOptionsFactoryService.GetEditorOptions(text).GetNewLineCharacter();
-            return "\r\n";
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs]: 🤦‍♂️

**Comment by jinujoseph** [comment]
Approved to merge for 15.8.Preview4

**Comment by jasonmalinowski** [comment]
Thanks @DavidKarlas for the fix! I worry there are plenty more of these hiding...

**Comment by DavidKarlas** [comment]
@jasonmalinowski first step in finding them would be removing hacks like https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/TestUtilities/Extensions/XElementExtensions.cs#L12 and not using `git config core.autocrlf` and work with source code as is, and not manipulate it differently on every machine o.O
