### PR TITLE
Fix ParameterSyntax.Update to account for '!!'

### LINKED ISSUE #58597: Possible bug for `ParameterSyntax.Update` API around `exclamationExclamationToken` behavior
**Version Used**: 

main

**Steps to Reproduce**:

https://github.com/dotnet/roslyn/blob/e60a474fd5fcf1102d214a9845cb9f96630d06f1/src/Compilers/CSharp/Portable/Syntax/ParameterSyntax.cs#L21-L24

**Expected Behavior**:

`exclamationExclamationToken` should be preserved.

cc @RikkiGibson

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #58597

cc @RikkiGibson

### CODE REVIEW

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNodeTests.cs [hunk 1]
```diff
@@ -3802,5 +3802,15 @@ public void TestStackAllocKeywordUpdate()
             var newExpression = expression.Update(replacedKeyword, expression.Type).ToString();
             Assert.Equal("stackalloc int[50]", newExpression);
         }
+
+        [Fact]
+        [WorkItem(58597, "https://github.com/dotnet/roslyn/issues/58597")]
+        public void TestExclamationExclamationUpdate()
+        {
+            var text = "(string s!!)";
+            var expression = SyntaxFactory.ParseParameterList(text).Parameters[0];
```
Comment (cston) [inline src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNodeTests.cs:3811]: >expression [](http://example.com/codeflow?start=16&length=10)

`parameter` (and `newParameter` below)?

File: src/Compilers/CSharp/Portable/Syntax/ParameterSyntax.cs [hunk 2]
```diff
@@ -20,7 +16,7 @@ internal bool IsArgList
 
         public ParameterSyntax Update(SyntaxList<AttributeListSyntax> attributeLists, SyntaxTokenList modifiers, TypeSyntax type, SyntaxToken identifier, EqualsValueClauseSyntax @default)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Syntax/ParameterSyntax.cs:17]: >@default [](http://example.com/codeflow?start=178&length=8)

Not part of this PR, but this parameter seems incorrectly named. Should this be `initializer` instead?

**Review by cston — APPROVED** [review]

**Review by RikkiGibson — APPROVED** [review]
