### PR TITLE
An input requires analysis using a different slot when suppressed

### LINKED ISSUE #38586: 'warning CS8655: The switch expression does not handle some null inputs' on suppressed nulls
**Version Used**: master 

**Steps to Reproduce**:

```cs
#nullable enable
public class C {
    public int M0(C a)  => a switch { C _ => 0 }; // ok
    public int M1(C? a) => a switch { C _ => 0 }; // warns
    public int M2(C? a) => a! switch { C _ => 0 }; // warns (none expected)
}
```

**Expected Behavior**: no warnings in M2

**Actual Behavior**: compiler warns about unhandled null in M2

### PR DESCRIPTION
**Pull request by gafter**
Fixes #38586

### CODE REVIEW

**Comment by gafter** [comment]
@agocke @RikkiGibson Can you please review this?

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 1]
```diff
@@ -119332,5 +119332,46 @@ class C<T>
...
+        if (a == null) return;
+        switch (a!)
+        {
+            case C _:
+                break;
+            case null: // does not affect knowledge of 'a'
+                break;
+        }
+
+        a.ToString();
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Maybe it would be good to add an `M7` where everything is the same as `M6` except we `switch (a)`, and we *do* get a warning here.

Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: No, `switch (a)` does not have exhaustiveness warnings.

---
In reply to: [354012561](https://github.com/dotnet/roslyn/pull/39697#discussion_r354012561) [](ancestors = 354012561)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs [hunk 2]
```diff
@@ -142,7 +142,7 @@ public override BoundNode VisitITuplePattern(BoundITuplePattern node)
         protected override LocalState VisitSwitchStatementDispatch(BoundSwitchStatement node)
         {
             // first, learn from any null tests in the patterns
-            int slot = MakeSlot(node.Expression);
+            int slot = node.Expression.IsSuppressed ? GetOrCreatePlaceholderSlot(node.Expression) : MakeSlot(node.Expression);
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs]: Is the idea here that if `node.Expression` is suppressed it will get a new slot, but all suppressed expressions of the same form (i.e. minus suppression) will share the same slot, so there will be at most two slots for a given slot, a suppressed one and an unsuppressed one?

Comment (agocke) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs]: I think what I'm asking is if this is the best place to fix this, as opposed to checking IsSuppressed in the helper for MakeSlot/GetOrCreateSlot.

Comment (gafter) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs]: The intent of this fix is to reflect the fact that the input expression is copied for the purposes of the switch.  Since the `!` operator changes the relationship between the inferred state and the state of the original expression, we need to treat that copied expression as a new slot when suppressed.  I think this is the best place to do that since it is specific to switch.

---
In reply to: [358474870](https://github.com/dotnet/roslyn/pull/39697#discussion_r358474870) [](ancestors = 358474870)

**Comment by gafter** [comment]
@agocke I think this responds to your comments.  Do you have any others?
