### PR TITLE
Fix Use Auto Property handling of VB's As New syntax

### LINKED ISSUE #26256: "Use auto property" code fix loses initialized value
**Version Used**: 

**Steps to Reproduce**:

``` VB
Public Class Class1
    Private Shared ReadOnly s_editorGuid As New Guid("{04b8ab82-a572-4fef-95ce-5222444b6b64}") <!-- Use auto property

    'Exposing the GUID for the rest of the assembly to see
    Public Shared ReadOnly Property EditorGuid() As Guid
        Get
            Return s_editorGuid
        End Get
    End Property
End Class

```
**Expected Behavior**:

I think this is the valid transformation but don't quote me on it:

``` VB
Public Class Class1

    'Exposing the GUID for the rest of the assembly to see
    Public ReadOnly Property EditorGuid() As Guid = New Guid("{04b8ab82-a572-4fef-95ce-5222444b6b64}")

End Class

```

**Actual Behavior**:

``` VB

Public Class Class1

    'Exposing the GUID for the rest of the assembly to see
    Public ReadOnly Property EditorGuid() As Guid
End Class

```

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #26256

<details><summary>Ask Mode template not completed</summary>

### Customer scenario

What does the customer do to get into this situation, and why do we think this
is common enough to address for this release.  (Granted, sometimes this will be
obvious "Open project, VS crashes" but in general, I need to understand how
common a scenario is)

### Bugs this fixes

(either VSO or GitHub links)

### Workarounds, if any

Also, why we think they are insufficient for RC vs. RC2, RC3, or RTW

### Risk

This is generally a measure our how central the affected code is to adjacent
scenarios and thus how likely your fix is to destabilize a broader area of code

### Performance impact

(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")

### Root cause analysis

How did we miss it?  What tests are we adding to guard against it in the future?

### How was the bug found?

(E.g. customer reported it vs. ad hoc testing)

### Test documentation updated?

If this is a new non-compiler feature or a significant improvement to an existing feature, update https://github.com/dotnet/roslyn/wiki/Manual-Testing once you know which release it is targeting.

</details>

### CODE REVIEW

File: src/EditorFeatures/VisualBasicTest/Diagnostics/UseAutoProperty/UseAutoPropertyTests.vb [hunk 1]
```diff
@@ -105,6 +105,24 @@ end class",
...
+    dim i as new Guid(""{00000000-0000-0000-0000-000000000000}"")
+    [|readonly property P as Guid
+        get
+            return i
+        end get
+    end property|]
+end class",
+"class Class1
+    readonly property P as Guid
+= new Guid(""{00000000-0000-0000-0000-000000000000}"")
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/EditorFeatures/VisualBasicTest/Diagnostics/UseAutoProperty/UseAutoPropertyTests.vb]: ➡️ The language-agnostic code generator cannot distinguish between these two cases.

[the remark this answers is not in the document]
Comment (Neme12) [reply src/EditorFeatures/VisualBasicTest/Diagnostics/UseAutoProperty/UseAutoPropertyTests.vb]: if the user prefers that, we shouldn't that unnecessarily

[the remark this answers is not in the document]
Comment (sharwell) [reply src/EditorFeatures/VisualBasicTest/Diagnostics/UseAutoProperty/UseAutoPropertyTests.vb]: This request cannot be implemented without a substantial modification to the code generation infrastructure. As a bug fix for a situation capable of unexpectedly deleting important code, I do not believe the limitation should block progress on this fix.

[the remark this answers is not in the document]
Comment (Neme12) [reply src/EditorFeatures/VisualBasicTest/Diagnostics/UseAutoProperty/UseAutoPropertyTests.vb]: looking at the code above, I see VB specific code above GetFieldInitializer, not any language agnostic generator

[the remark this answers is not in the document]
Comment (Neme12) [reply src/EditorFeatures/VisualBasicTest/Diagnostics/UseAutoProperty/UseAutoPropertyTests.vb]: specifically this line:
```c#
                statement = statement.WithInitializer(SyntaxFactory.EqualsValue(initializer))
```
there should be something like `WithAsClause`

[the remark this answers is not in the document]
Comment (sharwell) [reply src/EditorFeatures/VisualBasicTest/Diagnostics/UseAutoProperty/UseAutoPropertyTests.vb]: Looking at this another way: prior to this pull request the following code is generated:

```
readonly property P as Guid
```

The form used in this pull request is objectively better than the previous implementation in both behavior and style, even if it does not represent the ideal end goal.

File: src/EditorFeatures/VisualBasic/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb [hunk 2]
```diff
@@ -46,7 +46,12 @@ Namespace Microsoft.CodeAnalysis.Editor.VisualBasic.UseAutoProperty
         Private Async Function GetFieldInitializer(fieldSymbol As IFieldSymbol, cancellationToken As CancellationToken) As Task(Of ExpressionSyntax)
             Dim identifier = TryCast(Await fieldSymbol.DeclaringSyntaxReferences(0).GetSyntaxAsync(cancellationToken).ConfigureAwait(False), ModifiedIdentifierSyntax)
             Dim declarator = TryCast(identifier?.Parent, VariableDeclaratorSyntax)
-            Return declarator?.Initializer?.Value
+            Dim initializer = declarator?.Initializer?.Value
```
Comment (Neme12) [inline src/EditorFeatures/VisualBasic/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb]: this seems a little unnecessary too - we're getting the expression from the initialize only to then construct a new initializer above - we could just return the initializer itself, together with the as clause as a tuple maybe?

Comment (Neme12) [reply src/EditorFeatures/VisualBasic/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb]: then a few lines above the code would be changed to
```vb
statement = statement.WithInitializer(initializer).WithAsClause(asClause)
```

Comment (sharwell) [reply src/EditorFeatures/VisualBasic/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb]: ➡️ This change could be implemented as a follow-up improvement, but is outside the scope of the bug fix. The code changes for this pull request were intentionally kept to a minimum and to match d2dc228.

Comment (Neme12) [reply src/EditorFeatures/VisualBasic/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb]: well it's sort of a bug fix that introduces another small bug :-/ the proper fix should be really easy and probably add even less lines of code than this one

Comment (sharwell) [reply src/EditorFeatures/VisualBasic/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb]: :memo: If I don't make a change here, I'll file a new issue in dotnet/roslyn so this feedback is not lost. The request is certainly reasonable.

Comment (sharwell) [reply src/EditorFeatures/VisualBasic/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb]: ➡️ I went ahead and made this change since, unlike the commit referenced above, this code fix does not use the language-agnostic syntax generator for this part.

File: src/EditorFeatures/VisualBasicTest/Diagnostics/UseAutoProperty/UseAutoPropertyTests.vb (hunk 1 above)
[the remark this answers is not in the document]
Comment (sharwell) [reply src/EditorFeatures/VisualBasicTest/Diagnostics/UseAutoProperty/UseAutoPropertyTests.vb]: ➡️ This is now corrected per https://github.com/dotnet/roslyn/pull/26592#discussion_r185870238

File: src/EditorFeatures/VisualBasic/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb (hunk 2 above)
Comment (Neme12) [reply src/EditorFeatures/VisualBasic/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb]: thank you

File: src/EditorFeatures/VisualBasic/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb [hunk 3]
```diff
@@ -32,21 +32,27 @@ Namespace Microsoft.CodeAnalysis.Editor.VisualBasic.UseAutoProperty
...
             Return statement
         End Function
 
-        Private Async Function GetFieldInitializer(fieldSymbol As IFieldSymbol, cancellationToken As CancellationToken) As Task(Of ExpressionSyntax)
+        Private Async Function GetFieldInitializer(fieldSymbol As IFieldSymbol, cancellationToken As CancellationToken) As Task(Of (equalsValue As EqualsValueSyntax, asNewClause As AsNewClauseSyntax))
             Dim identifier = TryCast(Await fieldSymbol.DeclaringSyntaxReferences(0).GetSyntaxAsync(cancellationToken).ConfigureAwait(False), ModifiedIdentifierSyntax)
             Dim declarator = TryCast(identifier?.Parent, VariableDeclaratorSyntax)
-            Return declarator?.Initializer?.Value
+            Dim initializer = declarator?.Initializer
+            Dim asNewClause = TryCast(declarator.AsClause, AsNewClauseSyntax)
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/VisualBasic/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb]: why is the trycast necessary?

Comment (CyrusNajmabadi) [reply src/EditorFeatures/VisualBasic/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb]: ah, i see why.might be worth a comment.

**Comment by jinujoseph** [comment]
Approved to merge for 15.8.preview2
