### PR TITLE
Unblock type forwarding scenarios involving extensions

### LINKED ISSUE #79894: Roslyn hits "unreachable" exception when processing type forward to a class containing an extension group
**Version Used**: 5.0.0-2.25412.102

**Steps to Reproduce**:

1. Create a new class library, `ClassLibrary1`, containing the following contents:
```csharp
public static class Extensions
{
    extension(int)
    {
    }
}
```
2. Create another new class library, `ClassLibrary2`, which references the first and which contains the following contents:
```csharp
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Extensions))]
```

-- Note: The original repro had a proper extension group containing members, this is a minified repro.

**Expected Behavior**:

The compilation should succeed.

**Actual Behavior**:

The compilation of ClassLibrary2 fails with the following:
```
  ClassLibrary1 succeeded (1.4s) → ClassLibrary1\bin\Release\net10.0\ClassLibrary1.dll
  ClassLibrary2 failed with 21 error(s) (3.2s)
    D:\Users\tagoo\.nuget\packages\microsoft.net.compilers.toolset\5.0.0-2.25412.102\tasks\netcore\Microsoft.CSharp.Core.targets(84,5): error : Unhandled exception. System.InvalidOperationException: This program location is thought to be unreachable. File='/_/src/roslyn/src/Compilers/CSharp/Portable/Emitter/Model/NamedTypeSymbolAdapter.cs' Line=800
    D:\Users\tagoo\.nuget\packages\microsoft.net.compilers.toolset\5.0.0-2.25412.102\tasks\netcore\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.Microsoft.Cci.INamedEntity.get_Name()
    D:\Users\tagoo\.nuget\packages\microsoft.net.compilers.toolset\5.0.0-2.25412.102\tasks\netcore\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataWriter.GetMetadataName(INamedTypeReference namedType, Int32 generation)
    D:\Users\tagoo\.nuget\packages\microsoft.net.compilers.toolset\5.0.0-2.25412.102\tasks\netcore\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataWriter.PopulateExportedTypeTableRows()
    D:\Users\tagoo\.nuget\packages\microsoft.net.compilers.toolset\5.0.0-2.25412.102\tasks\netcore\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataWriter.PopulateTypeSystemTables(Int32[] methodBodyOffsets, Int32 mappedFieldDataStartOffset, PooledBlobBuilder& mappedFieldDataWriter, PooledBlobBuilder& resourceWriter, BlobBuilder dynamicAnalysisData, Blob& mvidFixup)
    D:\Users\tagoo\.nuget\packages\microsoft.net.compilers.toolset\5.0.0-2.25412.102\tasks\netcore\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataWriter.BuildMetadataAndIL(PdbWriter nativePdbWriterOpt, BlobBuilder ilBuilder, PooledBlobBuilder& mappedFieldDataBuilder, PooledBlobBuilder& managedResourceDataBuilder, Blob& mvidFixup, Blob& mvidStringFixup)
    D:\Users\tagoo\.nuget\packages\microsoft.net.compilers.toolset\5.0.0-2.25412.102\tasks\netcore\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
    D:\Users\tagoo\.nuget\packages\microsoft.net.compilers.toolset\5.0.0-2.25412.102\tasks\netcore\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.Compilation.SerializePeToStream(CommonPEModuleBuilder moduleBeingBuilt, DiagnosticBag metadataDiagnostics, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getMetadataPeStreamOpt, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, RebuildData rebuildData, Boolean metadataOnly, Boolean includePrivateMembers, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
    D:\Users\tagoo\.nuget\packages\microsoft.net.compilers.toolset\5.0.0-2.25412.102\tasks\netcore\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider metadataPEStreamProvider, EmitStreamProvider pdbStreamProvider, RebuildData rebuildData, Func`2 testSymWriterFactory, DiagnosticBag diagnostics, EmitOptions emitOptions, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
    D:\Users\tagoo\.nuget\packages\microsoft.net.compilers.toolset\5.0.0-2.25412.102\tasks\netcore\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 generators, ImmutableArray`1 additionalTextFiles, AnalyzerConfigSet analyzerConfigSet, ImmutableArray`1 sourceFileAnalyzerConfigOptions, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, ErrorLogger errorLogger, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, AnalyzerDriver& analyzerDriver, Nullable`1& generatorTimingInfo)
    D:\Users\tagoo\.nuget\packages\microsoft.net.compilers.toolset\5.0.0-2.25412.102\tasks\netcore\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
    D:\Users\tagoo\.nuget\packages\microsoft.net.compilers.toolset\5.0.0-2.25412.102\tasks\netcore\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
    D:\Users\tagoo\.nuget\packages\microsoft.net.compilers.toolset\5.0.0-2.25412.102\tasks\netcore\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)
    D:\Users\tagoo\.nuget\packages\microsoft.net.compilers.toolset\5.0.0-2.25412.102\tasks\netcore\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[T](Func`2 func)
    D:\Users\tagoo\.nuget\packages\microsoft.net.compilers.toolset\5.0.0-2.25412.102\tasks\netcore\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[T](Boolean utf8Output, TextWriter textWriter, Func`2 func)
    D:\Users\tagoo\.nuget\packages\microsoft.net.compilers.toolset\5.0.0-2.25412.102\tasks\netcore\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
    D:\Users\tagoo\.nuget\packages\microsoft.net.compilers.toolset\5.0.0-2.25412.102\tasks\netcore\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)
    D:\Users\tagoo\.nuget\packages\microsoft.net.compilers.toolset\5.0.0-2.25412.102\tasks\netcore\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter, String pipeName)
    D:\Users\tagoo\.nuget\packages\microsoft.net.compilers.toolset\5.0.0-2.25412.102\tasks\netcore\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc, CompileOnServerFunc compileOnServerFunc, ICompilerServerLogger logger)
    D:\Users\tagoo\.nuget\packages\microsoft.net.compilers.toolset\5.0.0-2.25412.102\tasks\netcore\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.MainCore(String[] args)
    D:\Users\tagoo\.nuget\packages\microsoft.net.compilers.toolset\5.0.0-2.25412.102\tasks\netcore\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #79894
This is a temporary fix to unblock the scenario. A proper fix will require significantly more implementation and validation work.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Symbol/Symbols/Metadata/PE/TypeForwarders.cs [hunk 1]
```diff
@@ -1353,6 +1353,29 @@ public class Inner
             CheckForwarderEmit(source1, source2, "NS.Forwarded", "NS.Forwarded+Inner");
         }
 
+        [ClrOnlyFact]
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Metadata/PE/TypeForwarders.cs:1356]: Nit: it doesn't seem like this needs to only be run on Clr hosts?

Comment (333fred) [reply src/Compilers/CSharp/Test/Symbol/Symbols/Metadata/PE/TypeForwarders.cs:1356]: Added a note to https://github.com/dotnet/roslyn/issues/79615#issuecomment-3187085744 to audit this class for conditional facts that don't need to be conditional.

File: src/Compilers/CSharp/Test/Symbol/Symbols/Metadata/PE/TypeForwarders.cs [hunk 2]
```diff
@@ -1353,6 +1353,29 @@ public class Inner
...
+}";
+
+            var source2 = @"
+[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(Extensions))]
+";
+
+            // https://github.com/dotnet/roslyn/issues/78963 - The grouping and marker types should be among the forwarded types since they are public.
+            //                                                 They also should be among exported types for library built from source1. Type symbols
+            //                                                 representing extensions from the language perspective should not be in either set.
+            CheckForwarderEmit(source1, source2, "Extensions");
```
Comment (jjonescz) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Metadata/PE/TypeForwarders.cs:1376]: So the extension members are not forwarded in this temporary fix? That sounds like that wouldn't actually "unblock" anyone since they would get a similar effect just by removing the TypeForwardedToAttribute

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Symbol/Symbols/Metadata/PE/TypeForwarders.cs:1376]: > So the extension members are not forwarded in this temporary fix?

Since no one references them in executable code, that should be fine because design time binds to the real declaration wherever it was moved

**Review by jjonescz — APPROVED** [review]

File: src/Compilers/CSharp/Test/Symbol/Symbols/Metadata/PE/TypeForwarders.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Symbol/Symbols/Metadata/PE/TypeForwarders.cs:1376]: > That sounds like that wouldn't actually "unblock" anyone since they would get a similar effect just by removing the TypeForwardedToAttribute

Note that we are not forwarding grouping and marker types, but the attribute is on the enclosing type and that type is forwarded
