### PR TITLE
Fix IDE0009 false positive on expressions qualified with 'base.'

### LINKED ISSUE #17711: IDE0009 wrongly generated when using the base keyword
**Version Used**: VS2017 15.0.0-RTW+26228.4

**Steps to Reproduce**: Consider this code

```csharp
class A
{
    public virtual int Value => 5;
}

class B : A
{
    public override int Value => base.Value + 6; // warning here
}
```

**Expected Behavior**: No warning generated for IDE0009 on the marked line

**Actual Behavior**: IDE0009 is generated here

The analysis is completely wrong. Applying 'this' would create an infinite loop. The property does not need to be an expression body for IDE0009 to be generated. `Value { get { base.Value + 6; } }` will cause the warning as well.

### PR DESCRIPTION
**Pull request by RobSiklos**
**Customer scenario**
See #17711 for details

**Bugs this fixes:**
Fixes #17711

**Workarounds, if any**
None

**Risk**
Low

**Performance impact**
Low perf impact because only a couple extra checks are done, with no loops.

**Is this a regression from a previous update?**
No

**Root cause analysis:**
Tests added. Missed because there were no tests initially for this.

**How was the bug found?**
Customer reported.

### CODE REVIEW

**Comment by Pilchie** [comment]
Thanks for the contribution!  Tagging @dotnet/roslyn-ide for review.

File: src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -66,6 +73,12 @@ private void AnalyzeOperation(OperationAnalysisContext context)
                 return;
             }
 
+            // If we can't be qualified (e.g., because we're already qualified with `base.`), we're done.
+            if (CanMemberAccessBeQualified(memberReference.Instance.Syntax) == false)
```
Comment (sharwell) [inline src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs]: ❓ Why do we need/want to differentiate this case from the `isQualificationPresent` variable later in this method? Can we combine the two to simplify the code?

File: src/EditorFeatures/CSharpTest/QualifyMemberAccess/QualifyMemberAccessTests.cs [hunk 2]
```diff
@@ -1028,5 +1028,57 @@ void Error()
 }",
 CodeStyleOptions.QualifyMethodAccess);
         }
+
+        [WorkItem(17711, "https://github.com/dotnet/roslyn/issues/17711")]
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/QualifyMemberAccess/QualifyMemberAccessTests.cs]: ❓ Can we add a test for fields here? It would be similar to the other tests except it wouldn't use the virtual/override combination.

File: src/Features/VisualBasic/Portable/Diagnostics/Analyzers/VisualBasicQualifyMemberAccessDiagnosticAnalyzer.vb [hunk 3]
```diff
@@ -15,5 +15,10 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.QualifyMemberAccess
         Protected Overrides Function IsAlreadyQualifiedMemberAccess(node As SyntaxNode) As Boolean
             Return node.IsKind(SyntaxKind.MeExpression)
         End Function
+
+        Protected Overrides Function CanMemberAccessBeQualified(node As SyntaxNode) As Boolean
+            ' If the member is already qualified with `MyBase.`, or `MyClass.`, it cannot be further qualified.
+            Return Not (node.IsKind(SyntaxKind.MyBaseExpression) OrElse node.IsKind(SyntaxKind.MyClassExpression))
```
Comment (sharwell) [inline src/Features/VisualBasic/Portable/Diagnostics/Analyzers/VisualBasicQualifyMemberAccessDiagnosticAnalyzer.vb]: 👍

File: src/Features/CSharp/Portable/QualifyMemberAccess/CSharpQualifyMemberAccessDiagnosticAnalyzer.cs [hunk 4]
```diff
@@ -13,5 +13,9 @@ protected override string GetLanguageName()
 
         protected override bool IsAlreadyQualifiedMemberAccess(SyntaxNode node)
             => node.IsKind(SyntaxKind.ThisExpression);
+
+        // If the member is already qualified with `base.`, it cannot be further qualified.
+        protected override bool CanMemberAccessBeQualified(SyntaxNode node)
+            => !node.IsKind(SyntaxKind.BaseExpression);
```
Comment (sharwell) [inline src/Features/CSharp/Portable/QualifyMemberAccess/CSharpQualifyMemberAccessDiagnosticAnalyzer.cs]: 👍

File: src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs (hunk 1 above)
Comment (RobSiklos) [inline src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs]: We need to differentiate because you may have the case where the user doesn't want to qualify, (e.g. `dotnet_style_qualification_for_property = false:error`), and we don't want to have `base.` show up as a false positive.

File: src/EditorFeatures/CSharpTest/QualifyMemberAccess/QualifyMemberAccessTests.cs (hunk 2 above)
Comment (RobSiklos) [inline src/EditorFeatures/CSharpTest/QualifyMemberAccess/QualifyMemberAccessTests.cs]: Addressed in commit 062c7f9.

I think all comments from your review are addressed now, but I'm not sure how to indicate this on github (other than through a comment like this one).

**Comment by sharwell** [comment]
@CyrusNajmabadi When you review this, can you make sure to look at `IsAlreadyQualifiedMemberAccess` and `CanMemberAccessBeQualified` and see if that's the way we want to go? The explanation for needing two methods is in the comments above.

File: src/Features/CSharp/Portable/QualifyMemberAccess/CSharpQualifyMemberAccessDiagnosticAnalyzer.cs (hunk 4 above)
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/QualifyMemberAccess/CSharpQualifyMemberAccessDiagnosticAnalyzer.cs]: why this, instead of say adding "BaseExpression" to "IsAlreadyQualifiedMemberAccess"?

File: src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs [hunk 5]
```diff
@@ -37,6 +37,13 @@ public override bool OpenFileOnly(Workspace workspace)
 
         protected abstract string GetLanguageName();
 
+        /// <summary>
+        /// Reports on whether the specified member is suitable for qualification. Some member access expressions cannot be qualififed;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs]: "qualififed"

try to wrap comments at 100 columns.

File: src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs (hunk 1 above)
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs]: ```if (!Can...)```

File: src/Features/CSharp/Portable/QualifyMemberAccess/CSharpQualifyMemberAccessDiagnosticAnalyzer.cs (hunk 4 above)
Comment (sharwell) [inline src/Features/CSharp/Portable/QualifyMemberAccess/CSharpQualifyMemberAccessDiagnosticAnalyzer.cs]: @CyrusNajmabadi This was answered in this comment: https://github.com/dotnet/roslyn/pull/19812#discussion_r118935090

**Comment by sharwell** [comment]
@MattGertz for ask mode

File: src/Features/CSharp/Portable/QualifyMemberAccess/CSharpQualifyMemberAccessDiagnosticAnalyzer.cs (hunk 4 above)
Comment (RobSiklos) [inline src/Features/CSharp/Portable/QualifyMemberAccess/CSharpQualifyMemberAccessDiagnosticAnalyzer.cs]: @sharwell @CyrusNajmabadi Since the reason isn't completely obvious, I can add a comment in the code explaining why it's done this way. Let me know if you'd like this and I'll update my branch

Comment (sharwell) [inline src/Features/CSharp/Portable/QualifyMemberAccess/CSharpQualifyMemberAccessDiagnosticAnalyzer.cs]: @RobSiklos Sounds like a good idea

**Comment by MattGertz** [comment]
Approved & thank you!

**Comment by sharwell** [comment]
@RobSiklos Feel free to create a new PR with the documentation change you were thinking of. I didn't want to risk this change not making it into the next release so I went ahead and merged it. :smile:
