### PR TITLE
Fix for incorrect IDE0007 implicit type diagnostic being reported in switch expressions

### LINKED ISSUE #44507: Incorrect IDE0007 (Use implicit type "var") for switch expressions
See https://github.com/dotnet/roslyn/pull/44491#discussion_r428850149. Applying the suggestion to var causes `error CS8506: No best type was found for the switch expression`

### PR DESCRIPTION
**Pull request by allisonchou**
Fixes #44507.

### CODE REVIEW

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Utilities/TypeStyle/CSharpUseImplicitTypeHelper.cs [hunk 1]
```diff
@@ -381,10 +384,43 @@ private static bool IsSwitchExpressionAndCannotUseVar(TypeSyntax typeName, Expre
...
+                            //     1 => new B(),
+                            //     _ => throw new ArgumentException(),
+                            // };
+                            if (expressionType.Equals(declarationType) || seenTypes.Contains(expressionType))
+                            {
+                                continue;
+                            }
+
+                            var invalidType = seenTypes.Any(
+                                t => !t.InheritsFromOrEquals(expressionType) && !expressionType.InheritsFromOrEquals(t));
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Utilities/TypeStyle/CSharpUseImplicitTypeHelper.cs:417]: so this fixes the bug, but i don't think it's accurate in terms of how the language sees things.  for example, if you have:

```c#
interface I { }
class C : I { }

i switch {
  0 => (C)...,
  1 => (I)...,
}
```

THen that would ok.  I'm not sure the exact rules (since i can't find the spec on it), but it's likely going to be more of 'is there a common type between these?'.

@jcouv @gafter can you point us at the spec for switch-expressions so we can implement the right check as per the language?

Comment (jcouv) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Utilities/TypeStyle/CSharpUseImplicitTypeHelper.cs:417]: Here's the spec for switch-expressions: https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/patterns.md#switch-expression

**Comment by CyrusNajmabadi** [comment]
@allisonchou how's your investigation going here?

**Comment by allisonchou** [comment]
@CyrusNajmabadi Still investigating - it was suggested that speculation might work to test out whether we can convert a switch expression to ```var```, but still confirming with the compiler team.

**Comment by gafter** [comment]
The simplest way to tell if a switch expression was target typed is to look at the switch expression’s Type and ConvertedType through the SemanticModel API. If the Type exists (not null) and an implicit conversion exists from the former to the latter then it was not target typed. Otherwise it was target typed.

**Comment by allisonchou** [comment]
The PR fix #45069 has rendered the existing [IsSwitchExpressionAndCannotUseVar](https://github.com/dotnet/roslyn/pull/44581/files#diff-d29955f5648bf5e2de0d6620e7321897L360) method unnecessary. The relevant check is now performed [here](http://sourceroslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/CSharpUseImplicitTypeHelper.cs,330) - after the PR fix, this check should properly handle switch expression cases.

**Comment by CyrusNajmabadi** [comment]
Can you add some tests with switch expressions where we would still want this to work?

**Comment by allisonchou** [comment]
> Can you add some tests with switch expressions where we would still want this to work?

@CyrusNajmabadi Thanks for the review! I added some tests for working cases in a previous switch expression PR (#39393), for example this test here: http://sourceroslyn.io/#Microsoft.CodeAnalysis.CSharp.CodeStyle.UnitTests/ConvertSwitchStatementToExpressionTests.cs,1430
If there are any additional cases you think would be good to include, please let me know and I can definitely add them.

Also, side question - will this PR have to be broken up into two PRs? It look like the DevOps build fails since I remove this suppression here: https://github.com/dotnet/roslyn/pull/44581/files#diff-f82d716a4b52569093434496de25eca3L575
I've confirmed via testing however that this case should no longer cause an error.

**Comment by CyrusNajmabadi** [comment]
> It look like the DevOps build fails since we removed this suppression here: https://github.com/dotnet/roslyn/pull/44581/files#diff-f82d716a4b52569093434496de25eca3L575
I've confirmed via testing however that this case should no longer cause an error with this PR fix.

It takes time for the new logic to make it into a package that we run in CI.  so you'll need to keep taht around for now.  We will still take this in a single pr.
