### PR TITLE
Don't offer to fix naming for record parameters 

### LINKED ISSUE #47508: IDE1006 thinks positional parameters on records are parameters and properties
When defining a record with positional parameters, IDE1006 will tell you to format names as properties, and then tell you to format them back to parameters.

```
record Foo(int MyInt);
```

**Actual Behavior**:
image
and then
image

**Expected Behavior**:
My proposal is that IDE1006 simply ignores parameters of record declarations as their usage matches property semantics.

### PR DESCRIPTION
**Pull request by davidwengier**
Fixes #47508 

Not sure if this is a controversial opinion that needs to go to a design meeting first, or not, but its a long weekend in the US. Worst case this gets closed ¯\\\_(ツ)_/¯

### CODE REVIEW

**Review by Youssef1313 — COMMENTED** [review]
Does this completely ignore positional parameters and never offers a diagnostic for?

I think it's useful to have a diagnostic for violating the naming convention, just don't offer "cyclic" diagnostics/codefixes.

**Comment by davidwengier** [comment]
It still offers a diagnostic, and therefore fixer, for when they violate property naming conventions, and there is a test for it too :)

**Comment by CyrusNajmabadi** [comment]
We should def discuss this. We need a general team agreement on how to treat the dual prop/param nature of records. Tagging @jcouv as well

File: src/Analyzers/CSharp/Analyzers/NamingStyle/CSharpNamingStyleDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -20,5 +25,14 @@ internal sealed class CSharpNamingStyleDiagnosticAnalyzer : NamingStyleDiagnosti
...
                 SyntaxKind.TypeParameter);
+
+        // Parameters of positional record declarations should be ignored because they also
+        // considered properties, and that naming style makes more sense
+        protected override bool ShouldIgnore(ISymbol symbol)
+            => symbol.IsKind(SymbolKind.Parameter)
+            && IsParameterOfRecordDeclaration(symbol.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax());
+
+        private static bool IsParameterOfRecordDeclaration(SyntaxNode? node)
+            => node != null && node.HasAncestor<RecordDeclarationSyntax>();
```
Comment (sharwell) [inline src/Analyzers/CSharp/Analyzers/NamingStyle/CSharpNamingStyleDiagnosticAnalyzer.cs:36]: ❗  This will end up excluding all parameters at any level of a record. The filter should be more specific.

File: src/Analyzers/CSharp/Tests/NamingStyles/NamingStylesTests.cs [hunk 2]
```diff
@@ -1293,5 +1293,24 @@ public async Task TestRefactorNotifyTypeParameterNamesStartWithT()
...
+
+        [Fact, Trait(Traits.Feature, Traits.Features.NamingStyle)]
+        [WorkItem(47508, "https://github.com/dotnet/roslyn/issues/47508")]
+        public async Task TestRecordParameter_ParameterFormattedAsProperties()
+        {
+            await TestInRegularAndScriptAsync(
+@"public record Foo(int [|myInt|]);",
+@"public record Foo(int [|MyInt|]);",
+                options: s_options.MergeStyles(s_options.PropertyNamesArePascalCase, s_options.ParameterNamesAreCamelCaseWithPUnderscorePrefix));
+        }
```
Comment (sharwell) [inline src/Analyzers/CSharp/Tests/NamingStyles/NamingStylesTests.cs:1314]: ❕ Need tests for cases where parameters are given using an explicit constructor inside a record.

File: src/Analyzers/Core/Analyzers/NamingStyle/NamingStyleDiagnosticAnalyzerBase.cs [hunk 3]
```diff
@@ -80,6 +84,8 @@ void SyntaxNodeAction(SyntaxNodeAnalysisContext syntaxContext)
                     return;
                 }
 
+                RoslynDebug.AssertNotNull(syntaxContext.Compilation);
```
Comment (sharwell) [inline src/Analyzers/Core/Analyzers/NamingStyle/NamingStyleDiagnosticAnalyzerBase.cs:87]: 📝 This appears to be a bug in the nullable annotations for the context type

**Comment by davidwengier** [comment]
I was looking in general at records issues (posted something in Teams too) and I feel pretty strongly that the parameters and properties should be considered in the same way for records, but happy to discuss. At the moment support is inconsistent and there are some sharp edges.

File: src/Analyzers/Core/Analyzers/NamingStyle/NamingStyleDiagnosticAnalyzerBase.cs (hunk 3 above)
Comment (sharwell) [reply src/Analyzers/Core/Analyzers/NamingStyle/NamingStyleDiagnosticAnalyzerBase.cs:87]: ➡️ Submitted #47537 to fix this

**Review by sharwell — CHANGES_REQUESTED** [review]

File: src/Analyzers/CSharp/Analyzers/NamingStyle/CSharpNamingStyleDiagnosticAnalyzer.cs (hunk 1 above)
Comment (davidwengier) [reply src/Analyzers/CSharp/Analyzers/NamingStyle/CSharpNamingStyleDiagnosticAnalyzer.cs:36]: Good point, I completely missed that.

File: src/Analyzers/Core/Analyzers/NamingStyle/NamingStyleDiagnosticAnalyzerBase.cs (hunk 3 above)
Comment (davidwengier) [reply src/Analyzers/Core/Analyzers/NamingStyle/NamingStyleDiagnosticAnalyzerBase.cs:87]: Thanks for looking at that. I wasn't sure about it because its a public API, so even though _semanticModel is non-nullable, you can't really trust it.

**Comment by davidwengier** [comment]
Thanks @sharwell, fixed that issue. Records are so nice to use as a single line declaration, I forget its legal for them to be any bigger :)

File: src/Analyzers/Core/Analyzers/NamingStyle/NamingStyleDiagnosticAnalyzerBase.cs (hunk 3 above)
Comment (sharwell) [reply src/Analyzers/Core/Analyzers/NamingStyle/NamingStyleDiagnosticAnalyzerBase.cs:87]: #47537 is now merged, so this assertion is no longer necessary

**Review by sharwell — APPROVED** [review]
