### PR TITLE
Permit a throw expression in an expression-bodied ref-returning method.

### LINKED ISSUE #16171: throw expression in ref returning methods produces an error
**Version Used**: https://github.com/dotnet/roslyn/commit/a2df65047264ed08fb3a985056085dbcee821253

**Steps to Reproduce**:

```cs
class C
{
    ref int M() => throw null;
}
```
**Expected Behavior**: No error

**Actual Behavior**: `By-value returns may only be used in methods that return by value`

### PR DESCRIPTION
**Pull request by gafter**
**Customer scenario**

Use a throw expression as the expression body of a ref-returning local function.

**Bugs this fixes:** 

Fixes #16171

**Workarounds, if any**

Don't use an expression bodied method for this confluence of features.

**Risk**

Very low. The additional code is a simple test and targeted to the problematic scenario.

**Performance impact**

Tiny, if any, for the same reason.

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

We did not test the confluence of three new features (expression-bodied methods, ref-returning functions, and throw expressions).

**How was the bug found?**

Customer reported.

@dotnet/roslyn-compiler May I please have a couple of reviews of this tiny bug fix?

### CODE REVIEW

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenRefReturnTests.cs [hunk 1]
```diff
@@ -2517,5 +2517,80 @@ public class A<T>
                 );
         }
 
+        [Fact]
+        public void ThrowRefReturn()
+        {
+            var text = @"using System;
+class Program
+{
+    static ref int P1 { get => throw new E(1); }
```
Comment (VSadov) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenRefReturnTests.cs]: If we are allowing this, the following should also be enabled:
```C#
    delegate ref int D();
    
    public void M() 
    {
        D x = () => throw null;
    }
```

Comment (VSadov) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenRefReturnTests.cs]: Ah, I see it is enabled.

**Comment by VSadov** [comment]
LGTM

**Comment by gafter** [comment]
Hey, @srivatsn, may I have an approval, please?

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenRefReturnTests.cs [hunk 2]
```diff
@@ -2517,5 +2517,80 @@ public class A<T>
...
+
+        [Fact]
+        public void NoRefThrow()
+        {
+            var text = @"using System;
+class Program
+{
+    static ref int P1 { get => ref throw new E(1); }
+    static ref int P2 => ref throw new E(2);
+    static ref int M() => ref throw new E(3);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenRefReturnTests.cs]: >static ref int M() => ref throw new E(3); [](start = 4, length = 41)

Consider also adding a test for scenarios like ```int M() => ref throw new E(3);```, i.e. without ```ref``` on the return type.
