### PR TITLE
Infer method group based on receiver nullability

### LINKED ISSUE #33637: Method groups not inferred based on receiver type (nullable walker)
In `NullableWalker.VisitMethodGroup`, we recompute the type of the group's receiver and then drop it on the floor.  When the method group is an argument to a generic, we will need the recomputed method (or group of methods) for proper type inference.

Here is a test that demonstrates the issue:

``` c#
        [Fact]
        public void MethodGroupReinferredAfterReceiver()
        {
            var source =
@"public class C
{
    G<T> CreateG<T>(T t) => new G<T>();
    void Main(string? s1, string? s2)
    {
        Run(CreateG(s1).M, s2)/*T:(string?, string?)!*/;
        if (s1 == null) return;
        Run(CreateG(s1).M, s2)/*T:(string!, string?)!*/;
        if (s2 == null) return;
        Run(CreateG(s1).M, s2)/*T:(string!, string!)!*/;
    }
    (T, U) Run<T, U>(MyDelegate<T, U> del, U u) => del(u);
}
public class G<T>
{
    public T t = default(T)!;
    public (T, U) M<U>(U u) => (t, u)!;
}
public delegate (T, U) MyDelegate<T, U>(U u);
";
            var comp = CreateCompilation(new[] { source }, options: WithNonNullTypesTrue());
            comp.VerifyDiagnostics();
            comp.VerifyTypes();
        }
```

The failure is

``` none
Message: void C.Main(System.String? s1, System.String? s2)

Expected:
(string?, string?)!,
(string!, string?)!,
(string!, string!)!
Actual:
(string, string?),
(string, string?),
(string, string!)
Differences:
++> (string, string?),
++> (string, string?),
++> (string, string!),
--> (string?, string?)!,
--> (string!, string?)!,
--> (string!, string!)!

Expected: True
Actual:   False
```

### LINKED ISSUE #35274: Roslyn does not warn about mismatching nullability in method group conversions unless qualifier type is specified explicitly
**Version Used**: 

Branch master (25 Apr 2019)
Latest commit 95f137 by Gen Lu:
Merge pull request #35245 from genlu/FixMockExpService

Fix mock experiment service

**Steps to Reproduce**:

Compile and run the following code:
```cs
#nullable enable
using System;

class C<T>
{
  public readonly T field;

  public C(T t) => field = t;
 
  public T M() => field;
}

class Program
{
  public static void Main()
  {
    string? s = null;
    Func<string> f = GetC(s).M;
    f().ToString();
  }
    
  public static C<T> GetC<T>(T t) => new C<T>(t);
}
```

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOyQExAagB8BiTdAG3ImHLgAI5NraBYAKAAEAGOjgRgDc7dhwBMdAMIAeACoA+dgG92dXgGY6COBBwB7TOQCedGXQBmASzjkcQtivWSAFKZgBKOgF455qza90MHZ0DhwapgCyTh7evta27AC+wpzi/ADsSqEa/ABsvAAsdBEQFpjRDspsqqr8XAD8dFABZJTBNRwArFJ1PmYBAOJwMBJOUG4AdBHtqmbREzK6AMowCGUA5tHtydU12bx8+dLydEMjsnIugTE+mHAA7pIXTu52iUA==

**Expected Behavior**:
Warning for converting the method group `GetC(s).M` to `Func<string>` since nullability of return values doesn't match.

**Actual Behavior**:
No warnings. The program crashes at runtime with a `NullReferenceException`.

**Notes**
`GetC(s)` returns `C<string?>`. Roslyn seems to be aware of that as you can verify by compiling the following expression `GetC(s).field.ToString()` which will have a warning for dereferencing a  possible null reference while accessing the field `field`. Consequently the method `M` have signature `string? M()` and its assignment to `Func<string>` should result in a warning.

Interestingly enough Roslyn will not report a warning even if you extract the result of `GetC(s)` in a separate variable i.e.
```cs
var c = GetC(s);
Func<string> f = c.M;
```
However it _*will*_ report a warning if you specify the type of `c` expliclitly i.e.
```cs
C<string?> c = GetC(s);
Func<string> f = c.M;
```

### PR DESCRIPTION
**Pull request by cston**
Partially addresses #33637
Fixes #35274

### CODE REVIEW

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 1]
```diff
@@ -4712,6 +4708,49 @@ private void SetMethodGroupReceiverNullability(BoundExpression receiver, TypeWit
...
+        {
+            var receiverOpt = group.ReceiverOpt;
+            if (TryGetMethodGroupReceiverNullability(receiverOpt, out TypeWithState receiverType))
+            {
+                var syntax = group.Syntax;
+                if (!invokedAsExtensionMethod)
+                {
+                    method = (MethodSymbol)AsMemberOfType(receiverType.Type, method);
+                }
+                if (method.Arity > 0 && HasImplicitTypeArguments(group.Syntax))
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >method.Arity > 0 [](start = 20, length = 16)

Perhaps `method.IsGenericMethod`?

**Comment by cston** [comment]
@dotnet/roslyn-compiler, please review.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 2]
```diff
@@ -4712,6 +4708,49 @@ private void SetMethodGroupReceiverNullability(BoundExpression receiver, TypeWit
...
+                {
+                    var binder = compilation.GetBinderFactory(syntax.SyntaxTree).GetBinder(syntax);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: nit: move closer to usage

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 3]
```diff
@@ -4712,6 +4708,49 @@ private void SetMethodGroupReceiverNullability(BoundExpression receiver, TypeWit
...
+                    }
+                    // Create placeholders for the arguments. See Conversions.GetDelegateArguments()
+                    // which is used for that purpose in initial binding.
+                    foreach (var parameter in delegateType.DelegateInvokeMethod.Parameters)
+                    {
+                        var parameterType = parameter.TypeWithAnnotations;
+                        arguments.Add(new BoundExpressionWithNullability(syntax, new BoundParameter(syntax, parameter), parameterType.NullableAnnotation, parameterType.Type));
+                    }
+                    method = InferMethodTypeArguments(binder, method, arguments.ToImmutableAndFree(), argumentRefKindsOpt: default, argsToParamsOpt: default, expanded: false);
+                }
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >} [](start = 16, length = 1)

I wonder if annotation attributes on method parameters should be checked in some way (not blocking this PR)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 4]
```diff
@@ -96219,12 +96221,603 @@ class Program
...
+                // (11,15): warning CS8600: Converting null literal or possible null value to non-nullable type.
+                //         T y = null; // 1
+                Diagnostic(ErrorCode.WRN_ConvertingNullableToNonNullable, "null").WithLocation(11, 15),
+                // (14,13): warning CS8634: The type 'T?' cannot be used as type parameter 'T' in the generic type or method 'E.F<T>(T)'. Nullability of type argument 'T?' doesn't match 'class' constraint.
+                //         d = y.F; // 2
+                Diagnostic(ErrorCode.WRN_NullabilityMismatchInTypeParameterReferenceTypeConstraint, "y.F").WithArguments("E.F<T>(T)", "T", "T?").WithLocation(14, 13),
+                // (16,23): warning CS8634: The type 'T?' cannot be used as type parameter 'T' in the generic type or method 'E.F<T>(T)'. Nullability of type argument 'T?' doesn't match 'class' constraint.
+                //         _ = new D<T?>(y.F); // 3
+                Diagnostic(ErrorCode.WRN_NullabilityMismatchInTypeParameterReferenceTypeConstraint, "y.F").WithArguments("E.F<T>(T)", "T", "T?").WithLocation(16, 23));
+        }
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >} [](start = 8, length = 1)

Btw, I found that you could test suppressions in this PR. But that may need to parenthesize twice...
`_ = new D(((F<T>))!);`

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 5]
```diff
@@ -3384,40 +3414,50 @@ private VariableState GetVariableState(Optional<LocalState> localState)
 
         private MethodSymbol InferMethodTypeArguments(BoundCall node, MethodSymbol method, ImmutableArray<BoundExpression> arguments)
         {
+            return InferMethodTypeArguments(node.BinderOpt, method, arguments, node.ArgumentRefKindsOpt, node.ArgsToParamsOpt, node.Expanded);
+        }
+
+        private MethodSymbol InferMethodTypeArguments(
+            Binder binder,
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >Binder binder, [](start = 12, length = 14)

do we still need to pass a binder here, given that the NullableWalker now has an instance field `_binder`?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 6]
```diff
@@ -475,6 +497,7 @@ protected override ImmutableArray<PendingBranch> Scan(ref bool badRegion)
             CSharpCompilation compilation,
             Symbol symbol,
             BoundNode node,
+            Binder binder,
             Conversions conversions,
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >Conversions conversions, [](start = 12, length = 24)

do we still need to pass conversions here, or can we just grab them from the new `binder` parameter?

**Comment by jcouv** [comment]
>                     var binder = compilation.GetBinderFactory(syntax.SyntaxTree).GetBinder(syntax);

I didn't understand what was wrong with that binder.

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:4723 in 3fd4798. [](commit_id = 3fd4798c8a0227f81ac3dffa4f3f5bae80f08be7, deletion_comment = True)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 7]
```diff
@@ -1906,6 +1930,7 @@ private ArrayTypeSymbol VisitArrayInitializer(BoundArrayCreation node)
                                             useMethodSignatureParameterTypes: false,
                                             methodSignatureOpt: null,
                                             node,
+                                            binder: null,
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >binder: null, [](start = 44, length = 13)

Consider naming the parameter `binderOpt`

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 4 above)
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >} [](start = 8, length = 1)

Consider testing some of the scenarios above inside a lambda.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 5 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Perhaps not, although the existing caller passes the binder from the `BoundCall` node which may be distinct.

---
In reply to: [282702127](https://github.com/dotnet/roslyn/pull/35601#discussion_r282702127) [](ancestors = 282702127)

**Comment by cston** [comment]
>                     var binder = compilation.GetBinderFactory(syntax.SyntaxTree).GetBinder(syntax);

From a `SpeculativeSemanticModel`, the `SyntaxTree` is not part of the `Compilation`.

---
In reply to: [491103137](https://github.com/dotnet/roslyn/pull/35601#issuecomment-491103137) [](ancestors = 491103137)

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:4723 in 66593a9. [](commit_id = 66593a917435ecbf7c2436d481962f861f298323, deletion_comment = True)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 7 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: I considered that but thought it might be misleading because `binder` is only `null` within `BestTypeForLambdaReturns`.

---
In reply to: [282703161](https://github.com/dotnet/roslyn/pull/35601#discussion_r282703161) [](ancestors = 282703161)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 6 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: I went back and forth on that and either approach seemed reasonable.

---
In reply to: [282702465](https://github.com/dotnet/roslyn/pull/35601#discussion_r282702465) [](ancestors = 282702465)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 3 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: The annotations would only be applied when the delegate is invoked, not when the delegate is created.

---
In reply to: [282700235](https://github.com/dotnet/roslyn/pull/35601#discussion_r282700235) [](ancestors = 282700235)

Comment (jcouv) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: That seems strange. Let's say we do have a [MaybeNull] attribute. Can I convert `[MaybeNull] T M()` to `Func<T>` safely?

---
In reply to: [282755353](https://github.com/dotnet/roslyn/pull/35601#discussion_r282755353) [](ancestors = 282755353,282700235)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 5 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: If it is distinct, it would be good to comment. When should we use `_binder` as opposed to other binders we could get?

---
In reply to: [282748578](https://github.com/dotnet/roslyn/pull/35601#discussion_r282748578) [](ancestors = 282748578,282702127)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 3 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: The `[MaybeNull]` attribute is distinct from the other annotation attributes in that it directly represents the nullability of the type that it is applied to, in the same way that `?` does for a reference type. `[MaybeNull]` would be included in the `TypeWithAnnotations` so it would affect the delegate return type or parameter types.

---
In reply to: [282976456](https://github.com/dotnet/roslyn/pull/35601#discussion_r282976456) [](ancestors = 282976456,282755353,282700235)
