### PR TITLE
Apply ComVisible attribute to embedded value types.

### LINKED ISSUE #16177: Roslyn should embed interop structs with [ComVisible(true)]
**Version**: VS 2015 Update 3

**Steps to Reproduce**:

1. Create a ATL COM library:

```
import "oaidl.idl";
import "ocidl.idl";

[
	uuid(E9832E6C-053B-4E7B-9F94-624964D2177B),
	version(1.0),
]
library FooLib
{
	importlib("stdole2.tlb");

	 [uuid(823F7C79-0238-4830-A7F2-8610ED1B3550),
	 version(1.0)]
	 typedef struct FooStruct {

		long operand1;
		long operand2;

	} FooStruct;
	[
		uuid(C58291E0-9474-438A-97E4-F7976B919C30)		
	]
	coclass Bar
	{
		[default] interface IBar;
	};

	[
		object,
		uuid(57D5CCE9-B3E2-4884-95F8-5B268DDF3DF2),
		oleautomation,
		dual,
		nonextensible,
		pointer_default(unique)
	]
	interface IBar : IDispatch {
		[id(1)]
		HRESULT CallFoos([in] SAFEARRAY(FooStruct)* ppFoos);
	};

};
```

2. Create a C# desktop/console project, reference ATL com library (Add reference), and set Embed Interop Types = true, and make sure [ComVisible(false)] in the assemblyInfo.cs.

3. Try to call CallFoos with following code:

```
new Bar().CallFoos(new FooStruct[] {  new FooStruct() })
```

**Expected Behavior**:
Succeed

**Actual Behavior**:
Fail. CLR throws ArgumentException with HRESULT=0x80070057 (E_INVALIDARG).

**Reason**:
The underlying problem is caused by interop type embeding. When marshaling SAFEARRAY of structs, CLR needs to locate the IRecordInfo from the typelib in order to be able to correctly represent them in VARIANTs. 
Due to interop embeding, CLR is not able to correctly locate the type lib GUID (the right GUID is on the interop assembly that is not inherited into the main app, and in the case of multiple embedding interop assemblies, it simply can't), so registering the TLB actually don't work. As a result, CLR has to resort back to dynamically export a tlb on the fly to solve the issue. 
This usually works well for embedded interop classes and interfaces since they are [ComImport], but not for structs since it can't have [ComImport]. Therefore, CLR uses [ComVisible()] setting on struct to determine whether the importing is needed. If [ComVisible(false)] is set on assembly level (which is the **default**), CLR would ignore the struct and the struct would fail to be found in the exported type lib. 
If you turn off embed interop types, or change the default [ComVisible(false)] to true, you wouldn't see this issue. 
To work well with CLR, it might be reasonable to make such structs [ComVisible(true)] when embedding them.

### PR DESCRIPTION
**Pull request by AlekseyTs**
**Customer scenario**
Marshaling of embedded value types is not working in some interop scenarios when ComVisible(false) is applied to the embedding assembly. See #16177 for more information.

**Bugs this fixes:** 
Fixes #16177.

**Workarounds, if any**
Remove ComVisible(false) from the assembly, but this is going to expose all types not explicitly marked with ComVisible(false) to COM, which is not always desirable.

**Risk**
Low

**Performance impact**
Low

**Is this a regression from a previous update?**
No.

**Root cause analysis:**
Added tests.

**How was the bug found?**
Customer reported.

@dotnet/roslyn-compiler Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

File: src/Compilers/VisualBasic/Portable/Symbols/WellKnownMembers.vb [hunk 1]
```diff
@@ -172,8 +177,8 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
             Return New SynthesizedAttributeData(constructorSymbol, arguments, namedStringArguments)
         End Function
 
-        Private Function ReturnNothingOrThrowIfAttributeNonOptional(constructor As WellKnownMember) As SynthesizedAttributeData
-            If WellKnownMembers.IsSynthesizedAttributeOptional(constructor) Then
+        Private Function ReturnNothingOrThrowIfAttributeNonOptional(constructor As WellKnownMember, Optional isOptionalUse As Boolean = False) As SynthesizedAttributeData
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Symbols/WellKnownMembers.vb]: `Shared`

**Comment by cston** [comment]
LGTM

File: src/Compilers/VisualBasic/Portable/Symbols/WellKnownMembers.vb (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/WellKnownMembers.vb]: Since this is not a function introduced in this PR, I'll make make it ```Shared``` separately.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off.

**Comment by AlekseyTs** [comment]
@srivatsn For Ask Mode sign-off.
