### PR TITLE
Move optimization around use of Nullable type in Boolean Expressions into LocalRewriter and eliminate invalid optimization.

### LINKED ISSUE #38305: Incorrect code is generated when nullable value is compared to a not nullable in context of a logical short-circuiting operator used as a Boolean expression
Compile and run the following code:
```
Option Strict On

Class C

    Public shared Sub Main()
	Test1(Nothing, new C())
	Test2(Nothing, new C())
	Test3(Nothing, new C())
	Test4(Nothing, new C())
	Test5(Nothing, new C())
    End Sub

    Public Shared Sub Test1(x as C, y As C)
        System.Console.WriteLine("->Test1")
	If GetBool3(x) = True AndAlso y.GetBool2()
            System.Console.WriteLine("In If")
	End If
        System.Console.WriteLine("<-Test1")
    End Sub

    Public Shared Sub Test2(x as C, y As C)
        System.Console.WriteLine("->Test2")
	If x?.GetBool1() = True AndAlso y.GetBool2()
            System.Console.WriteLine("In If")
	End If
        System.Console.WriteLine("<-Test2")
    End Sub

    Public Shared Sub Test3(x as C, y As C)
        System.Console.WriteLine("->Test3")
	Dim z = GetBool3(x) = True AndAlso y.GetBool2()
	If z
            System.Console.WriteLine("In If")
	End If
        System.Console.WriteLine("<-Test3")
    End Sub

    Public Shared Sub Test4(x as C, y As C)
        System.Console.WriteLine("->Test4")
	Dim z = x?.GetBool1() = True AndAlso y.GetBool2()
	If z
            System.Console.WriteLine("In If")
	End If
        System.Console.WriteLine("<-Test4")
    End Sub

    Public Shared Sub Test5(x as C, y As C)
        System.Console.WriteLine("->Test5")
	If GetBool3(x) AndAlso y.GetBool2()
            System.Console.WriteLine("In If")
	End If
        System.Console.WriteLine("<-Test5")
    End Sub

    Function GetBool1() As Boolean
        Return True
    End Function
    Function GetBool2() As Boolean
        System.Console.WriteLine("GetBool2")
        Return True
    End Function
    Shared Function GetBool3(x as C) As Boolean?
	if x Is Nothing
             Return Nothing
	End If

        Return True
    End Function
End Class
```

Observed:
```
->Test1
<-Test1
->Test2
<-Test2
->Test3
GetBool2
<-Test3
->Test4
GetBool2
<-Test4
->Test5
GetBool2
<-Test5
```

Expected: Proper handling of Null propagation for short circuiting operator. I.e. all test methods should execute GetBool2 method for the provided set of arguments. As it happens for Test3 and Test4, which calculate result of a Boolean expression into a local rather than inlining it into an If. And as it happens for Test5, which doesn't have comparison in the Boolean expression.
```
->Test1
GetBool2
<-Test1
->Test2
GetBool2
<-Test2
->Test3
GetBool2
<-Test3
->Test4
GetBool2
<-Test4
->Test5
GetBool2
<-Test5
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #38305.

The goal of optimization is to eliminate the need to deal with instances of Nullable(Of Boolean) type as early as possible, and, as a result, simplify evaluation of built-in OrElse/AndAlso operators by eliminating the need to use three-valued Boolean logic. The optimization is possible because when an entire Boolean Expression is evaluated to Null, that has the same effect as if result of evaluation was False. However, we do want to preserve the original order of evaluation, according to language rules.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
I suspect the CI jobs are failing because there are bugs elsewhere in the compiler that were masked by the addressed correctness issue, i.e. the code depends on AndAlso to short circuit when short-circuiting shouldn't happen. I will investigate and confirm whether this is the case.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler  Please review

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb [hunk 1]
```diff
@@ -1225,7 +1225,7 @@ Namespace Microsoft.CodeAnalysis.Operations
 
         Friend Function CreateBoundCatchBlockExceptionDeclarationOrExpression(boundCatchBlock As BoundCatchBlock) As IOperation
             If boundCatchBlock.LocalOpt IsNot Nothing AndAlso
-                        boundCatchBlock.ExceptionSourceOpt?.Kind = BoundKind.Local AndAlso
+                        (boundCatchBlock.ExceptionSourceOpt?.Kind = BoundKind.Local).GetValueOrDefault() AndAlso
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb]: >(boundCatchBlock.ExceptionSourceOpt?.Kind = BoundKind.Local).GetValueOrDefault() AndAlso [](start = 24, length = 88)

This is a fix, we are going to dereference ```boundCatchBlock.ExceptionSourceOpt``` below. Prior to this PR, compiler would incorrectly apply GetValueOrDefault call itself.

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_QueryLambdaRewriter.vb [hunk 2]
```diff
@@ -84,7 +84,7 @@ Namespace Microsoft.CodeAnalysis.Operations
             End Function
 
             Public Overrides Function VisitParameter(node As BoundParameter) As BoundNode
-                If node.ParameterSymbol?.ContainingSymbol.IsQueryLambdaMethod AndAlso Not _uniqueNodes.Add(node) Then
+                If (node.ParameterSymbol?.ContainingSymbol.IsQueryLambdaMethod).GetValueOrDefault() AndAlso Not _uniqueNodes.Add(node) Then
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_QueryLambdaRewriter.vb]: >(node.ParameterSymbol?.ContainingSymbol.IsQueryLambdaMethod).GetValueOrDefault() [](start = 19, length = 80)

This is just an optimization, we wouldn't get into the if even without it.

File: src/Compilers/VisualBasic/Portable/Symbols/NamedTypeSymbol.vb [hunk 3]
```diff
@@ -1272,8 +1272,8 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols
 
             ' Should this be optimized for perf (caching for VT<0> to VT<7>, etc.)?
             If Not IsUnboundGenericType AndAlso
-                ContainingSymbol?.Kind = SymbolKind.Namespace AndAlso
-                ContainingNamespace?.ContainingNamespace?.IsGlobalNamespace = True AndAlso
+                (ContainingSymbol?.Kind = SymbolKind.Namespace).GetValueOrDefault() AndAlso
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/NamedTypeSymbol.vb]: >(ContainingSymbol?.Kind = SymbolKind.Namespace).GetValueOrDefault() [](start = 16, length = 67)

This is a fix, we are going to dereference ```ContainingNamespace``` below as the last condition. Prior to this PR, compiler would incorrectly apply GetValueOrDefault call itself.

File: src/Compilers/VisualBasic/Portable/Symbols/NamedTypeSymbol.vb [hunk 4]
```diff
@@ -1272,8 +1272,8 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols
...
+                (ContainingNamespace.ContainingNamespace?.IsGlobalNamespace).GetValueOrDefault() AndAlso
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/NamedTypeSymbol.vb]: >(ContainingNamespace.ContainingNamespace?.IsGlobalNamespace).GetValueOrDefault() [](start = 16, length = 80)

This is a fix, we are going to dereference ContainingNamespace below as the last condition even when it was null. Prior to this PR, compiler would incorrectly apply GetValueOrDefault call itself.

File: src/Compilers/VisualBasic/Portable/Symbols/SymbolExtensions.vb [hunk 5]
```diff
@@ -436,7 +436,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols
 
         <Extension>
         Friend Function ContainingNonLambdaMember(member As Symbol) As Symbol
-            While member?.Kind = SymbolKind.Method AndAlso DirectCast(member, MethodSymbol).MethodKind = MethodKind.AnonymousFunction
+            While (member?.Kind = SymbolKind.Method).GetValueOrDefault() AndAlso DirectCast(member, MethodSymbol).MethodKind = MethodKind.AnonymousFunction
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/SymbolExtensions.vb]: >(member?.Kind = SymbolKind.Method).GetValueOrDefault() [](start = 18, length = 54)

This is a fix, we are going to dereference member after AndAlso. Prior to this PR, compiler would incorrectly apply GetValueOrDefault call itself.

File: src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.vb [hunk 6]
```diff
@@ -1280,7 +1280,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols.Metadata.PE
                    specialtype <> SpecialType.System_Enum AndAlso specialtype <> SpecialType.System_MulticastDelegate Then
                     Dim base As TypeSymbol = GetDeclaredBase(Nothing)
 
-                    If base?.SpecialType = SpecialType.None AndAlso base.ContainingAssembly?.IsMissing Then
+                    If base IsNot Nothing AndAlso base.SpecialType = SpecialType.None AndAlso base.ContainingAssembly?.IsMissing Then
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.vb]: >base IsNot Nothing AndAlso base.SpecialType = SpecialType.None [](start = 23, length = 62)

This is a fix, we are going to dereference ```base``` after AndAlso. Prior to this PR, compiler would incorrectly apply GetValueOrDefault call.

File: src/Compilers/VisualBasic/Portable/Symbols/Source/SourceParameterSymbol.vb [hunk 7]
```diff
@@ -105,7 +105,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols
             Get
                 If Me.ContainingSymbol.IsImplicitlyDeclared Then
 
-                    If TryCast(Me.ContainingSymbol, MethodSymbol)?.MethodKind = MethodKind.DelegateInvoke AndAlso
+                    If (TryCast(Me.ContainingSymbol, MethodSymbol)?.MethodKind = MethodKind.DelegateInvoke).GetValueOrDefault() AndAlso
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceParameterSymbol.vb]: >(TryCast(Me.ContainingSymbol, MethodSymbol)?.MethodKind = MethodKind.DelegateInvoke).GetValueOrDefault() [](start = 23, length = 104)

This is an optimization.

File: src/Compilers/VisualBasic/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.vb [hunk 8]
```diff
@@ -1242,8 +1242,8 @@ End Class
 
             ' Always report diagnostics in generated code, unless explicitly suppressed or we are not even analyzing generated code.
             Dim reportInGeneratedCode = generatedCodeAnalysisFlagsOpt Is Nothing OrElse
-                ((generatedCodeAnalysisFlagsOpt And GeneratedCodeAnalysisFlags.ReportDiagnostics) <> 0 AndAlso
-                 (generatedCodeAnalysisFlagsOpt And GeneratedCodeAnalysisFlags.Analyze) <> 0)
+                ((generatedCodeAnalysisFlagsOpt.GetValueOrDefault() And GeneratedCodeAnalysisFlags.ReportDiagnostics) <> 0 AndAlso
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.vb]: >(generatedCodeAnalysisFlagsOpt.GetValueOrDefault() [](start = 17, length = 50)

This is just an optimization

File: src/Compilers/VisualBasic/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.vb [hunk 9]
```diff
@@ -1242,8 +1242,8 @@ End Class
...
+                 (generatedCodeAnalysisFlagsOpt.GetValueOrDefault() And GeneratedCodeAnalysisFlags.Analyze) <> 0)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.vb]: >generatedCodeAnalysisFlagsOpt.GetValueOrDefault() [](start = 18, length = 49)

This is just an optimization

File: src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicSelectionResult.vb [hunk 10]
```diff
@@ -188,7 +188,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.ExtractMethod
             End If
 
             ' use FormattableString if conversion between String And FormattableString
-            If info.Type?.SpecialType = SpecialType.System_String AndAlso
+            If (info.Type?.SpecialType = SpecialType.System_String).GetValueOrDefault() AndAlso
```
Comment (AlekseyTs) [inline src/Features/VisualBasic/Portable/ExtractMethod/VisualBasicSelectionResult.vb]: >(info.Type?.SpecialType = SpecialType.System_String).GetValueOrDefault() [](start = 15, length = 72)

This is just an optimization

File: src/Workspaces/VisualBasic/Portable/Extensions/CastAnalyzer.vb [hunk 11]
```diff
@@ -217,7 +217,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Extensions
 
             ' A casts to object can always be removed from an expression inside of an interpolation, since it'll be converted to object
             ' in order to call string.Format(...) anyway.
-            If castType?.SpecialType = SpecialType.System_Object AndAlso
+            If (castType?.SpecialType = SpecialType.System_Object).GetValueOrDefault() AndAlso
```
Comment (AlekseyTs) [inline src/Workspaces/VisualBasic/Portable/Extensions/CastAnalyzer.vb]: >(castType?.SpecialType = SpecialType.System_Object).GetValueOrDefault() [](start = 15, length = 71)

This is an optimization

File: src/Workspaces/VisualBasic/Portable/Extensions/ExpressionSyntaxExtensions.vb [hunk 12]
```diff
@@ -1476,7 +1476,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Extensions
             If name.IsKind(SyntaxKind.GenericName) Then
                 If (name.IsParentKind(SyntaxKind.CrefReference)) OrElse ' cref="Nullable(Of T)"
                    (name.IsParentKind(SyntaxKind.QualifiedName) AndAlso name.Parent?.IsParentKind(SyntaxKind.CrefReference)) OrElse ' cref="System.Nullable(Of T)"
-                   (name.IsParentKind(SyntaxKind.QualifiedName) AndAlso name.Parent?.IsParentKind(SyntaxKind.QualifiedName) AndAlso name.Parent?.Parent?.IsParentKind(SyntaxKind.CrefReference)) Then  ' cref="System.Nullable(Of T).Value"
+                   (name.IsParentKind(SyntaxKind.QualifiedName) AndAlso (name.Parent?.IsParentKind(SyntaxKind.QualifiedName)).GetValueOrDefault() AndAlso name.Parent.Parent?.IsParentKind(SyntaxKind.CrefReference)) Then  ' cref="System.Nullable(Of T).Value"
```
Comment (AlekseyTs) [inline src/Workspaces/VisualBasic/Portable/Extensions/ExpressionSyntaxExtensions.vb]: > (name.Parent?.IsParentKind(SyntaxKind.QualifiedName)).GetValueOrDefault() [](start = 71, length = 74)

This is just an optimization.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

File: src/Workspaces/VisualBasic/Portable/Extensions/ExpressionSyntaxExtensions.vb (hunk 12 above)
Comment (jasonmalinowski) [reply src/Workspaces/VisualBasic/Portable/Extensions/ExpressionSyntaxExtensions.vb]: I'm confused: is this ensuring the same optimization happens once Roslyn is built with a newer version of itself after this PR is merged? We absolutely don't care about that in the IDE cases, so we should just keep the code simple.

File: src/Workspaces/VisualBasic/Portable/Extensions/CastAnalyzer.vb (hunk 11 above)
Comment (jasonmalinowski) [reply src/Workspaces/VisualBasic/Portable/Extensions/CastAnalyzer.vb]: I'm confused: is this ensuring the same optimization happens once Roslyn is built with a newer version of itself after this PR is merged? We absolutely don't care about that in the IDE cases, so we should just keep the code simple.

File: src/Workspaces/VisualBasic/Portable/Extensions/ExpressionSyntaxExtensions.vb (hunk 12 above)
Comment (AlekseyTs) [reply src/Workspaces/VisualBasic/Portable/Extensions/ExpressionSyntaxExtensions.vb]: > is this ensuring the same optimization happens once Roslyn is built with a newer version of itself after this PR is merged?

No. This code was not optimized by the compiler before and isn't optimized now. Addition of GetValueOrDefault() call eliminates the need for "Nullable" logic. If you insist I can revert this change. 

---
In reply to: [327884076](https://github.com/dotnet/roslyn/pull/38802#discussion_r327884076) [](ancestors = 327884076)

File: src/Workspaces/VisualBasic/Portable/Extensions/CastAnalyzer.vb (hunk 11 above)
Comment (AlekseyTs) [reply src/Workspaces/VisualBasic/Portable/Extensions/CastAnalyzer.vb]: >  is this ensuring the same optimization happens once Roslyn is built with a newer version of itself after this PR is merged?

Yes.

> We absolutely don't care about that in the IDE cases, so we should just keep the code simple.

The new code looks simple to me. If you insist, I can revert it.

---
In reply to: [327884085](https://github.com/dotnet/roslyn/pull/38802#discussion_r327884085) [](ancestors = 327884085)

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

File: src/Workspaces/VisualBasic/Portable/Extensions/ExpressionSyntaxExtensions.vb (hunk 12 above)
Comment (jasonmalinowski) [reply src/Workspaces/VisualBasic/Portable/Extensions/ExpressionSyntaxExtensions.vb]: Ah, I misunderstood -- didn't realize the null case would continue to evaluate.

File: src/Workspaces/VisualBasic/Portable/Extensions/CastAnalyzer.vb (hunk 11 above)
Comment (jasonmalinowski) [reply src/Workspaces/VisualBasic/Portable/Extensions/CastAnalyzer.vb]: Ah, I misunderstood -- didn't realize the null case continues to evaluate.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

File: docs/compilers/Visual Basic/Compiler Breaking Changes - post VS2019.md [hunk 13]
```diff
@@ -0,0 +1,27 @@
...
+    Function GetBool2() As Boolean
+        System.Console.WriteLine("GetBool2")
+        Return True
+    End Function
+    Shared Function GetBool3() As Boolean?
+         Return Nothing
+    End Function
+```
+
+it is expected that GetBool2 function going to be called. This is also the expected behavior outside of
```
Comment (cston) [inline docs/compilers/Visual Basic/Compiler Breaking Changes - post VS2019.md]: >it is expected that GetBool2 function going to be called [](start = 0, length = 56)

I'm confused why `GetBool2()` should be called. `GetBool3() = True` is a `Boolean` expression that evaluates to `False`.

Comment (AlekseyTs) [reply docs/compilers/Visual Basic/Compiler Breaking Changes - post VS2019.md]: In VB ```GetBool3() = True``` evaluates to Null. Result of comparing unknown (which is what the Null is) with anything (even with another unknown) is unknown, i.e. Null. This is three-valued logic that VB compiler is using, unlike C#.

---
In reply to: [328675106](https://github.com/dotnet/roslyn/pull/38802#discussion_r328675106) [](ancestors = 328675106)

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb [hunk 14]
```diff
@@ -84,20 +84,33 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
         Public Overrides Function VisitBinaryOperator(node As BoundBinaryOperator) As BoundNode
             ' Do not blow the stack due to a deep recursion on the left. 
 
-            Dim child As BoundExpression = node.Left
+            Dim optimizeForConditionalBranch As Boolean = (node.OperatorKind And BinaryOperatorKind.OptimizableForConditionalBranch) <> 0
+            Dim optimizeChildForConditionalBranch As Boolean = optimizeForConditionalBranch
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb]: >optimizeChildForConditionalBranch [](start = 16, length = 33)

Consider using `optimizeForConditionalBranch` directly.

Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb]: > Consider using optimizeForConditionalBranch directly.

It might have a different value, I would still need another local

---
In reply to: [328762339](https://github.com/dotnet/roslyn/pull/38802#discussion_r328762339) [](ancestors = 328762339)

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb [hunk 15]
```diff
@@ -126,9 +140,34 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
+                optimizeForConditionalBranch = False
+            End If
+
+            Dim child As BoundExpression = binary.Left
+
+            While child.Kind = BoundKind.Parenthesized
+                child = DirectCast(child, BoundParenthesized).Expression
+            End While
+
+            Return child
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb]: `Return binary.Left.GetMostEnclosedParenthesizedExpression()`

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb [hunk 16]
```diff
@@ -126,9 +140,34 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
+        End Function
+
+        Private Shared Function GetRightOperand(binary As BoundBinaryOperator, adjustIfOptimizableForConditionalBranch As Boolean) As BoundExpression
+            If adjustIfOptimizableForConditionalBranch Then
+                Return LocalRewriter.AdjustIfOptimizableForConditionalBranch(binary.Right, Nothing)
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb]: >LocalRewriter. [](start = 23, length = 14)

Is the type qualifier needed?

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb [hunk 17]
```diff
@@ -894,6 +946,121 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
+                        ' For [x AndAlso y] we can produce Boolean result as follows:
+                        '
+                        ' tempX = x
+                        ' (Not tempX.HasValue OrElse tempX.GetValueOrDefault()) AndAlso
+                        ' (y.GetValueOrDefault() AndAlso tempX.HasValue)
+                        '
+                        Dim leftTemp As SynthesizedLocal = Nothing
+                        Dim leftInit As BoundExpression = Nothing
+
+                        ' Right may be a method that takes Left byref - " local And TakesArgByref(local) "
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb]: >And [](start = 80, length = 3)

`AndAlso`?

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb (hunk 16 above)
Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb]: > Is the type qualifier needed?

If it is not, does its usage violate some policy?

---
In reply to: [328789857](https://github.com/dotnet/roslyn/pull/38802#discussion_r328789857) [](ancestors = 328789857)

File: src/Compilers/VisualBasic/Portable/Binding/Binder_Expressions.vb [hunk 18]
```diff
@@ -91,7 +91,10 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
                     ' parent expression.
 
                     ' Dev10 allows parenthesized type expressions, let's bind as a general expression first.
-                    Dim operand As BoundExpression = BindExpression(DirectCast(node, ParenthesizedExpressionSyntax).Expression, False, False, eventContext, diagnostics)
+                    Dim operand As BoundExpression = BindExpression(DirectCast(node, ParenthesizedExpressionSyntax).Expression,
+                                                                    isInvocationOrAddressOf:=False,
```
Comment (jcouv) [inline src/Compilers/VisualBasic/Portable/Binding/Binder_Expressions.vb]: >False [](start = 93, length = 5)

should we pass `isInvocationOrAddressOf` here?

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_NullableHelpers.vb [hunk 19]
```diff
@@ -322,11 +329,18 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
-            End If
+            Select Case expr.Kind
+                Case BoundKind.ObjectCreationExpression
+                    Dim objCreation = DirectCast(expr, BoundObjectCreationExpression)
+                    ' Nullable<T> has only one ctor with parameters and only that one sets hasValue = true
+                    Return objCreation.Arguments.Length <> 0
+                Case BoundKind.Conversion
+                    Dim conversion = DirectCast(expr, BoundConversion)
+                    If (conversion.ConversionKind And (ConversionKind.Widening Or ConversionKind.Nullable Or ConversionKind.UserDefined)) = (ConversionKind.Widening Or ConversionKind.Nullable) AndAlso
+                        expr.Type.GetNullableUnderlyingType().Equals(conversion.Operand.Type, TypeCompareKind.AllIgnoreOptionsForVB) Then
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_NullableHelpers.vb]: Consider extracting a helper for here and `NullableValueOrDefault`.

File: src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenNullable.vb [hunk 20]
```diff
@@ -4831,5 +4788,2021 @@ VerifyIL("Module1.Main",
...
+  IL_003e:  br.s       IL_0042
+  IL_0040:  ldc.i4.3
+  IL_0041:  stloc.0
+  IL_0042:  ldloc.0
+  IL_0043:  ret
+}
+                ]]>)
+        End Sub
+
+        <Fact(Skip:="Only manual execution due to time.")>
```
Comment (cston) [inline src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenNullable.vb]: >Skip [](start = 14, length = 4)

We won't notice any regressions if the test is skipped. Could the number of iterations be reduced so this test could be enabled?

File: src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenNullable.vb [hunk 21]
```diff
@@ -4831,5 +4788,2021 @@ VerifyIL("Module1.Main",
...
+        Private Class BooleanExpression_30_Helpers
+
+            Class TreeNode
+                Public Left As TreeNode
+                Public Right As TreeNode
+            End Class
+
+            Public Shared Iterator Function BuildConditions(fromOperators As Integer, toOperators As Integer) As IEnumerable(Of ExpressionSyntax)
+                For operatorCount = fromOperators To toOperators
+                    For Each shape In BooleanExpression_30_Helpers.Shapes(operatorCount)
```
Comment (cston) [inline src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenNullable.vb]: >BooleanExpression_30_Helpers [](start = 38, length = 28)

Consider removing type qualifiers for readability.

File: src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenNullable.vb (hunk 20 above)
Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenNullable.vb]: > We won't notice any regressions if the test is skipped. Could the number of iterations be reduced so this test could be enabled?

I think that IL tests that I added are sufficient to catch a regression. I used this test to prove that what we emit actually executes the way we expect.

---
In reply to: [328832948](https://github.com/dotnet/roslyn/pull/38802#discussion_r328832948) [](ancestors = 328832948)

File: src/Compilers/VisualBasic/Portable/Binding/Binder_Expressions.vb (hunk 18 above)
Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Portable/Binding/Binder_Expressions.vb]: > should we pass isInvocationOrAddressOf here?

I do not think so and that wouldn't have any affect of the scenarios this change is targeting.

---
In reply to: [328824413](https://github.com/dotnet/roslyn/pull/38802#discussion_r328824413) [](ancestors = 328824413)

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb [hunk 22]
```diff
@@ -126,9 +140,34 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
             Return left
         End Function
 
-        Private Function RewriteBinaryOperatorSimple(node As BoundBinaryOperator) As BoundNode
+        Private Shared Function GetLeftOperand(binary As BoundBinaryOperator, ByRef optimizeForConditionalBranch As Boolean) As BoundExpression
+            If optimizeForConditionalBranch AndAlso (binary.OperatorKind And BinaryOperatorKind.OpMask) <> BinaryOperatorKind.OrElse Then
```
Comment (jcouv) [inline src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb]: ><> BinaryOperatorKind.OrElse [](start = 104, length = 28)

nit: I didn't understand why we check for "not OrElse" rather than just checking for "AndAlso" (seems more direct)

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_UnaryOperators.vb [hunk 23]
```diff
@@ -39,6 +44,35 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
+            Do
+                Select Case current.Kind
+                    Case BoundKind.BinaryOperator
+                        Dim binary = DirectCast(current, BoundBinaryOperator)
+                        If (binary.OperatorKind And BinaryOperatorKind.IsOperandOfConditionalBranch) <> 0 Then
+                            Select Case (binary.OperatorKind And BinaryOperatorKind.OpMask)
+                                Case BinaryOperatorKind.AndAlso, BinaryOperatorKind.OrElse
+                                    Debug.Assert((binary.OperatorKind And BinaryOperatorKind.Lifted) <> 0)
+                                    optimizableForConditionalBranch = True
+                                    Return binary.Update(binary.OperatorKind Or BinaryOperatorKind.OptimizableForConditionalBranch,
```
Comment (jcouv) [inline src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_UnaryOperators.vb]: >OptimizableForConditionalBranch [](start = 99, length = 31)

If I followed correctly, this is the only place were we set `BinaryOperatorKind.OptimizableForConditionalBranch`. It seems that all the information to decide whether to set this flag is available during binding. Why do we need to wait until lowering to set it?
If we can compute this during binding, then we would only need one flag.

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb (hunk 16 above)
Comment (jcouv) [reply src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb]: nit: I was thrown off by this too. Consider removing.

---
In reply to: [328821636](https://github.com/dotnet/roslyn/pull/38802#discussion_r328821636) [](ancestors = 328821636,328789857)

Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb]: >  I was thrown off by this too.

Could you please explain what confused you?

---
In reply to: [328859772](https://github.com/dotnet/roslyn/pull/38802#discussion_r328859772) [](ancestors = 328859772,328821636,328789857)

Comment (jcouv) [reply src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb]: I thought I had seen that method in LocalRewriter and so went to check where it was. When we qualify, I assume that the method is somewhere else, even though I recognize it is not necessary ;-)

---
In reply to: [328863180](https://github.com/dotnet/roslyn/pull/38802#discussion_r328863180) [](ancestors = 328863180,328859772,328821636,328789857)

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_UnaryOperators.vb (hunk 23 above)
Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_UnaryOperators.vb]: > If we can compute this during binding, then we would only need one flag.

I prefer to have stronger guarantees and apply optimization only when we are absolutely sure that we will "snap" Null to false. And that is when we actually have the ```BoundNullableIsTrueOperator``` as the ancestor and no user defined operators in between. We simply don't know that information during binding because we haven't bound binary operators up the hierarchy yet. So the optimization is triggered by the fact of snapping Null to false (getting to the VisitNullableIsTrueOperator method) and then we are making sure we don't have anything unexpected in between.

---
In reply to: [328851498](https://github.com/dotnet/roslyn/pull/38802#discussion_r328851498) [](ancestors = 328851498)

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb (hunk 16 above)
Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb]: > I thought I had seen that method in LocalRewriter and so went to check where it was. When we qualify, I assume that the method is somewhere else, even though I recognize it is not necessary ;-)

So, there was an actual benefit for the purpose of code review. You saw the call and went to see what the method actually does. Seems like a huge plus to me.  :-) 

---
In reply to: [328863963](https://github.com/dotnet/roslyn/pull/38802#discussion_r328863963) [](ancestors = 328863963,328863180,328859772,328821636,328789857)

Comment (jcouv) [reply src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb]: I didn't explain clearly. I was wondering "how does this relate to the method I saw earlier?" (ie. is it the same one, or a different one). The qualifier is what made me doubt. It's a nit. When the code is loaded in VS that won't be a problem (go to def...).

---
In reply to: [328866218](https://github.com/dotnet/roslyn/pull/38802#discussion_r328866218) [](ancestors = 328866218,328863963,328863180,328859772,328821636,328789857)

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_UnaryOperators.vb (hunk 23 above)
Comment (jcouv) [reply src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_UnaryOperators.vb]: Makes sense.
That may be a useful comment to capture next to one of the two flags.

---
In reply to: [328865595](https://github.com/dotnet/roslyn/pull/38802#discussion_r328865595) [](ancestors = 328865595,328851498)

**Comment by RikkiGibson** [comment]
Is this ready to merge @AlekseyTs?

**Comment by AlekseyTs** [comment]
No, I still need to follow up on some things

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb (hunk 16 above)
Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperators.vb]: > Is the type qualifier needed?

> didn't explain clearly. I was wondering "how does this relate to the method I saw earlier?" (ie. is it the same one, or a different one). The qualifier is what made me doubt. It's a nit. When the code is loaded in VS that won't be a problem (go to def...).

The type qualifier is need here because VB is case-insensitive and parameter takes over otherwise.

---
In reply to: [328867784](https://github.com/dotnet/roslyn/pull/38802#discussion_r328867784) [](ancestors = 328867784,328866218,328863963,328863180,328859772,328821636,328789857)

**Comment by AlekseyTs** [comment]
@cston, @jcouv I think I addressed your feedback. Please let me know if you have additional comments.
