### PR TITLE
Do not return FunctionTypeSymbol from InferBestType helper.

### LINKED ISSUE #71002: C# code with lambda in an array causes severl errors in refactoring code provider + diag analysis
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1919598

_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-code-with-lambda-in-an-array-causes-s/10520221)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.7.7]
Added code...

var tests = new[]
            {
                () => 
            };

Encountered several errors, these 2 are the last.

Resulted in... (even after re-starting VS)

StreamJsonRpc.RemoteInvocationException: This program location is thought to be unreachable. File='/_/src/Compilers/CSharp/Portable/Symbols/FunctionTypeSymbol.cs' Line=144
   at StreamJsonRpc.JsonRpc. <InvokeCoreAsync>d__151`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1. <TryInvokeAsync>d__18`1.MoveNext()
RPC server exception:
System.InvalidOperationException: This program location is thought to be unreachable. File='/_/src/Compilers/CSharp/Portable/Symbols/FunctionTypeSymbol.cs' Line=144
      at Microsoft.CodeAnalysis.CSharp.Symbols.FunctionTypeSymbol.CreateISymbol()
      at Microsoft.CodeAnalysis.CSharp.Symbol.get_ISymbol()
      at Microsoft.CodeAnalysis.DiagnosticInfo.GetArgumentsToUse(IFormatProvider formatProvider)
      at Microsoft.CodeAnalysis.DiagnosticInfo.GetMessage(IFormatProvider formatProvider)
      at Microsoft.CodeAnalysis.Diagnostics.DiagnosticData.Create(Diagnostic diagnostic, ProjectId projectId, String language, DiagnosticDataLocation location, ImmutableArray`1 additionalLocations, ImmutableDictionary`2 additionalProperties)
      at Microsoft.CodeAnalysis.Diagnostics.DiagnosticData.Create(Diagnostic diagnostic, TextDocument document)
      at Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResultBuilder.AddDocumentDiagnostic(Dictionary`2& map, TextDocument document, Diagnostic diagnostic)
      at Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResultBuilder.AddDiagnostics(Dictionary`2& lazyLocals, SyntaxTree tree, IEnumerable`1 diagnostics)
      at Microsoft.CodeAnalysis.Diagnostics.Extensions. <ToResultBuilderMapAsync>g__AddDiagnosticsToResult|6_1(ImmutableArray`1 diagnostics, DiagnosticAnalysisResultBuilder& result, Compilation compilation, SyntaxTree tree, DocumentId additionalDocumentId, Nullable`1 span, AnalysisKind kind, ImmutableArray`1 diagnosticIdsToFilter, Boolean includeSuppressedDiagnostics)
      at Microsoft.CodeAnalysis.Diagnostics.Extensions.ToResultBuilderMapAsync(AnalysisResult analysisResult, ImmutableArray`1 additionalPragmaSuppressionDiagnostics, DocumentAnalysisScope documentAnalysisScope, Project project, VersionStamp version, Compilation compilation, IEnumerable`1 analyzers, SkippedHostAnalyzersInfo skippedAnalyzersInfo, Boolean includeSuppressedDiagnostics, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.AnalyzeAsync(CompilationWithAnalyzers compilationWithAnalyzers, BidirectionalMap`2 analyzerToIdMap, ImmutableArray`1 analyzers, SkippedHostAnalyzersInfo skippedAnalyzersInfo, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.GetDiagnosticsAsync(IEnumerable`1 analyzerIds, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.GetNormalPriorityDiagnosticsAsync(IEnumerable`1 analyzerIds, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.<>c__DisplayClass4_0. <<CalculateDiagnosticsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass9_0`1. <<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.CalculateDiagnosticsAsync(Checksum solutionChecksum, DiagnosticArguments arguments, CancellationToken cancellationToken)

====================================

System.InvalidOperationException : This program location is thought to be unreachable. File='/_/src/Compilers/CSharp/Portable/Symbols/FunctionTypeSymbol.cs' Line=146
   at Microsoft.CodeAnalysis.CSharp.Symbols.FunctionTypeSymbol.CreateITypeSymbol(NullableAnnotation nullableAnnotation)
   at Microsoft.CodeAnalysis.CSharp.BoundExpression.GetPublicTypeSymbol()
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundConversionOperation(BoundConversion boundConversion,Boolean forceOperandImplicitLiteral)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateFromArray[TBoundNode,TOperation](ImmutableArray`1 boundNodes)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundArrayInitializationOperation(BoundArrayInitialization boundArrayInitialization)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundArrayCreationOperation(BoundArrayCreation boundArrayCreation)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateVariableDeclaratorInitializer(BoundLocalDeclaration boundLocalDeclaration,SyntaxNode syntax)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateVariableDeclaratorInternal(BoundLocalDeclaration boundLocalDeclaration,SyntaxNode syntax)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateVariableDeclarator(BoundNode declaration,SyntaxNode declarationSyntax)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundLocalDeclarationOperation(BoundLocalDeclaration boundLocalDeclaration)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateFromArray[TBoundNode,TOperation](ImmutableArray`1 boundNodes)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundBlockOperation(BoundBlock boundBlock)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundTryStatementOperation(BoundTryStatement boundTryStatement)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateFromArray[TBoundNode,TOperation](ImmutableArray`1 boundNodes)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundBlockOperation(BoundBlock boundBlock)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateMethodBodyOperation(BoundNonConstructorMethodBody boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetRootOperation()
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetOperationWorker(CSharpSyntaxNode node,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetOperationWorker(CSharpSyntaxNode node,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetOperationCore(SyntaxNode node,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.IntroduceUsingStatement.AbstractIntroduceUsingStatementCodeRefactoringProvider`3.FindDisposableLocalDeclarationAsync[TStatementSyntax,TLocalDeclarationSyntax,TTryStatementSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.IntroduceUsingStatement.AbstractIntroduceUsingStatementCodeRefactoringProvider`3.ComputeRefactoringsAsync[TStatementSyntax,TLocalDeclarationSyntax,TTryStatementSyntax](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)

---
#### Feedback Bot on 11/20/2023, 00:01 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #71002.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Semantics/BestTypeInferrer.cs [hunk 1]
```diff
@@ -76,7 +76,7 @@ public static NullableFlowState GetNullableState(ArrayBuilder<TypeWithState> typ
                     if (type.ContainsErrorType())
                     {
                         inferredFromFunctionType = false;
-                        return type;
+                        return type is FunctionTypeSymbol function ? function.GetInternalDelegateType() : type;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Semantics/BestTypeInferrer.cs:79]: >function.GetInternalDelegateType() [](http://example.com/codeflow?start=69&length=34)

Should we set `inferredFromFunctionType = true` in this case?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Semantics/BestTypeInferrer.cs:79]: > Should we set `inferredFromFunctionType = true` in this case?

It looks to me that we didn't really infer anything, but grabbed the first type with errors, there could be other type candidates that aren't function types. Since this is already an error scenario, I do not think adjusting the value is going to have any positive effect. However, I am willing to rely on your expertise in this area and make adjustments based on your recommendations. Do you have any specific scenario, that can benefit from the change, in mind?

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 1)

File: src/Compilers/CSharp/Portable/Binder/Semantics/BestTypeInferrer.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Semantics/BestTypeInferrer.cs:79]: > No, I don't have a specific scenario in mind that would benefit from the change. But since the returned type was inferred from a function type, it may be surprising to a caller that does depend on that behavior in the future.

Could you please clarify, are you making a specific suggestion or not?

**Review by cston — APPROVED** [review]
