### PR TITLE
Fix nested nullability of collection expressions

### LINKED ISSUE #71522: IDE0300 fix-all skips first diagnostic in a cascading ternary
**Version Used**: 
Version 17.9.0 Preview 3.0 [34431.11.main]

**Steps to Reproduce**:
```C#
int value = 3;
M(value is 1 ? new[] { "1" } :
  value is 2 ? new[] { "2" } :
  value is 3 ? new[] { "3" } :
  new[] { "4" });

static void M(string[] args) { }
```

**Diagnostic Id**:
IDE0300

**Expected Behavior**:
Four IDE0300 diagnostics issued. Selecting the last one and choosing to fix-all fixes all of them:
```C#
int value = 3;
M(value is 1 ? ["1"] :
  value is 2 ? ["2"] :
  value is 3 ? ["3"] :
  ["4"]);

static void M(string[] args) { }
```

**Actual Behavior**:
Four IDE0300 diagnostics issued. Selecting the last one and choosing to fix-all fixes the last three but not the first:
```C#
int value = 3;
M(value is 1 ? new[] { "1" } :
  value is 2 ? ["2"] :
  value is 3 ? ["3"] :
  ["4"]);

static void M(string[] args) { }
```
cc: @CyrusNajmabadi

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #71522

Adjust NullableWalker to stop passing target-typed expressions to BestTypeInferrer. This was causing the converted collection-expr's type from initial binding to sneak into the nullable best type analysis, causing some NotAnnotated annotations to get replaced with Oblivious in the array element case.

Also adjust BestTypeInferrer to expect that target-typed expressions are not passed to it. It doesn't make sense for a target-typed expression to participate in best-type. Target-typed expressions should only be converted to the resulting best-type, not have their type used as input to best-type analysis.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 1]
```diff
@@ -9305,7 +9317,11 @@ private void TrackAnalyzedNullabilityThroughConversionGroup(TypeWithState result
             while (conversionOpt != null && conversionOpt != convertedNode)
             {
                 Debug.Assert(conversionOpt.ConversionGroupOpt == conversionGroup);
-                visitResult = withType(visitResult, conversionOpt.Type);
+                // TODO2: what does it mean for these types to differ? Why is it correct to copy over the top-level nullability when the types have differences beyond nullability?
+                if (!visitResult.LValueType.Type.Equals(conversionOpt.Type, TypeCompareKind.AllNullableIgnoreOptions))
+                {
+                    visitResult = withType(visitResult, conversionOpt.Type);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:9323]: I wasn't able to figure out exactly what to do here. I found that sometimes the visitResult had a nullable-enriched type prior to this call and that calling `withType` was stomping on that and using the type from initial binding.

But, other times, the type of `conversionOpt.Type` was different than `visitResult` beyond just nullability. In this case, I opted to just drop the type from the visitResult.

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler for review

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 2]
```diff
@@ -3702,7 +3702,7 @@ TypeWithState convertCollection(BoundCollectionExpression node, TypeWithAnnotati
 
                 // Record the final state
                 NullableFlowState resultState = getResultState(node, collectionKind);
-                var resultTypeWithState = TypeWithState.Create(node.Type, resultState);
+                var resultTypeWithState = TypeWithState.Create(strippedTargetCollectionType, resultState);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3705]: Which test change is relevant to this?
To observe this change, I expected to see a test where the target type is a `System.Nullable<SomeCollectionType>`, such as `b ? [1] : nullableCollection` or something like that.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 3]
```diff
@@ -4613,7 +4613,11 @@ private static bool IsTargetTypedExpression(BoundExpression node)
             {
                 var (returnExpr, resultType, _) = returns[i];
                 resultTypes.Add(resultType);
-                placeholdersBuilder.Add(CreatePlaceholderIfNecessary(returnExpr, resultType));
+
+                if (!IsTargetTypedExpression(returnExpr))
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:4617]: The tests seem to focus on collection expressions as the "target-typed expression". Consider adding tests for the other kinds of target-typed expressions (null, default, switches, conditionals, lambdas, tuples, ...).

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/NullablePublicAPITests.cs [hunk 4]
```diff
@@ -5235,5 +5236,214 @@ void test(SemanticModelOptions options)
                 Assert.Equal(PublicNullableAnnotation.None, typeInfo.Type.NullableAnnotation);
             }
         }
+
+        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/71522")]
+        public void CollectionExpression_NestedNullability_01()
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/NullablePublicAPITests.cs:5241]: >_NestedNullability [](http://example.com/codeflow?start=40&length=18)

nit: I didn't quite follow what is the "nested nullability" aspect of those tests.

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/NullablePublicAPITests.cs [hunk 5]
```diff
@@ -5235,5 +5236,214 @@ void test(SemanticModelOptions options)
...
+                var b = false;
+                var arr = b ? ["1"] : new[] { "2" };
+                """;
+
+            var comp = CreateCompilation(source);
+            var tree = comp.SyntaxTrees[0];
+            var model = comp.GetSemanticModel(tree);
+
+            var root = tree.GetRoot();
+            var collectionExpr = root.DescendantNodes().OfType<CollectionExpressionSyntax>().Single();
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/NullablePublicAPITests.cs:5255]: nit: just FYI in case you find it convenient, I added a test helper "GetSyntax" which allows `GetSyntax<CollectionExpressionSyntax>(tree, """["1"]""")` to do the trick in this case.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3705]: The original version was propagating the type from initial binding, instead of the nullable-reinferred type which analysis says we are actually converting to, e.g. `string~[]` in the original code and `string![]` in the updated code.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3705]: It's possible the "strippedTargetCollectionType" is wrong in nullable value type cases, I thought that it was reasonable because collection-expr values themselves are never null. But I will have to look into it.

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/NullablePublicAPITests.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/Source/NullablePublicAPITests.cs:5241]: ElementNullableAnnotation is essentially nested, it is not tracked directly in the TypeWithState for an array value, for example, rather it is the ElementNullableAnnotation on the ArrayTypeSymbol.

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 3). Only minor questions on tests

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:4617]: the scenario is about when:
1. a target-typed expression is subject to best-type analysis (e.g. `b ? ["1"] : new[] { "2" }`),
2. *and*, there is a nested nullability reinference occurring in the other best-type candidate expressions, which we want to "win" over any initial-bound type which the target-typed expression may have.

So, there might be an interesting scenario to test like in `b ? ("1", "2") : GenericMethod("1")`, or something like that.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 1 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:9322]: From offline discussion, `TrackAnalyzedNullabilityThroughConversionGroup` is incorrect if we think of the general nullability tracking through conversions. But that's not its job (`VisitConversion` does that full analysis). So only a subset of cases must come through here (error conversions? trivial conversions?). An assertion narrowing down the conversions we expect to see here would help.
Is it okay that it returns types with nullabilities from initial binding in some/many cases?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:4617]: Have added a test based on this suggestion.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: I've investigated this more.

I noticed that SetAnalyzedNullability is already dropping the visitResult's type if it differs from conversionOpt.Type (with all ignore options). So, I think that 'withType' never actually affects anything. It was essentially repeating a step that SetAnalyzedNullability was already doing.

I have removed the function, and added a comment about the "inaccuracy" of what we are doing here--which is just that we're using the conversion's type from initial binding, instead of using the operand's visit result to reinfer the conversion's type and store the reinferred type instead.

My change has made it so that when the conversion operand's nested nullability is meaningfully reinferred, that info is not dropped, and that none of the existing inaccuracies are made "worse".

There is more room to improve here, but would like to leave it at that for this PR.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 3 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:4617]: I didn't follow. The test you added doesn't have lambdas.

Comment (jcouv) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:4617]: There are three places where an `IsTargetTypedExpression` check was added: conditionals, lambdas and switches. The added test seems to cover conditionals. 
Consider adding a similar test showing the effects of the fix on other target-typed expressions besides collection expressions in lambdas and switches.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:4617]: Switches are covered in `TargetTypedExpressions_NestedNullability`.
Lambdas are covered in `CollectionExpression_NestedNullability_06`. Note that one of the cases involves collection-exprs, and the other case doesn't involve collection-exprs, but still shows an incorrect behavior, tracked in #74609

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 10)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 3 above)
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:4617]: >if (!IsTargetTypedExpression(returnExpr)) [](http://example.com/codeflow?start=16&length=41)

Is this change covered by a test? It didn't seem like the new tests were affected by this check.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 6]
```diff
@@ -5817,6 +5821,14 @@ void makeAndAdjustReceiverSlot(BoundExpression receiver)
...
                 resultType = null;
             }
+            else if (IsTargetTypedExpression(consequence))
+            {
+                resultType = alternativeRValue.Type;
+            }
+            else if (IsTargetTypedExpression(alternative))
+            {
+                resultType = consequenceRValue.Type;
+            }
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:5831]: Are we testing this case?

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/NullablePublicAPITests.cs [hunk 7]
```diff
@@ -5235,5 +5236,287 @@ void test(SemanticModelOptions options)
...
         }
+
+        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/71522")]
+        public void CollectionExpression_NestedNullability_01()
+        {
+            var source = """
+                #nullable enable
+
+                var b = false;
+                var arr = b ? ["1"] : new[] { "2" };
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/NullablePublicAPITests.cs:5247]: >var arr = b ? ["1"] : new[] { "2" }; [](http://example.com/codeflow?start=16&length=36)

Consider also testing:
```
arr = b ? new[] { "1" } : ["2"];
```

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:4617]: That's correct, but, I would prefer to leave this check in order to satisfy new assertions in BestTypeInferrer.

I didn't investigate closely but I am guessing something is causing the return type we wanted to infer here to be replaced unexpectedly with a type from initial binding.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:4617]: Actually since this is only used in initial binding we might be able to remove the check and just assert that a target typed expr is not being used here.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:4617]: urgh, this code probably would have behaved incorrectly if one of the exprs actually was target-typed, it expects that 'resultTypes ' and 'placeholdersBuilder' have the same count after the loop.

**Review by cston — APPROVED** [review]
