### PR TITLE
Each kind of compiler should take its /version info from its containing assembly's FileVersion

### LINKED ISSUE #14172: Tests failing on signed builds after merging #13955
https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=351941&_a=summary&tab=ms.vss-test-web.test-result-details

An example test is at Microsoft.CodeAnalysis.CSharp.CommandLine.UnitTests.CommandLineTests.Version:

```
Assert.Equal() Failure
 ↓ (pos 6)
Expected: 2.0.0.60929
Actual: 2.0.0.0
 ↑ (pos 6)
```

### PR DESCRIPTION
**Pull request by gafter**
It appears we were lucky things worked before (that is, before I broke things by making the
output use file version and the tests use assembly version), as the implementation and tests
for /help disagreed on which assembly to use to get the version info for the C# and VB
compilers. They were usually the same information by coincidence as a consequence of
how the product is built. We now consistently use the file version of the file containing
the assembly of the compiler main class for /help, /version, and the tests of those flags.
Fixes #14172

@dotnet/roslyn-compiler Please review
@jasonmalinowski FYI

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet/roslyn-compiler Please review soon, as this addresses a break in the signed build tests.

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs [hunk 1]
```diff
@@ -86,11 +86,17 @@ public CommonCompiler(CommandLineParser parser, string responseFile, string[] ar
...
+        /// We don't simply use this.GetType() because that would break mock subclasses.
+        /// </summary>
+        internal abstract Type Type { get; }
+
+        internal virtual string GetAssemblyFileVersion()
         {
             if (_clientDirectory != null)
             {
-                var name = $"{typeof(CommonCompiler).GetTypeInfo().Assembly.GetName().Name}.dll";
+                var name = $"{Type.GetTypeInfo().Assembly.GetName().Name}.dll";
```
Comment (jasonmalinowski) [inline src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: Strictly the name of the assembly and the file could differ. Is there no filename or location option you can use?

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs [hunk 2]
```diff
@@ -100,7 +106,7 @@ internal string GetAssemblyFileVersion()
 
         internal Version GetAssemblyVersion()
```
Comment (jasonmalinowski) [inline src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: Curious, what is this used for? Perhaps a comment for why this would be used vs. the other one might avoid future confusion.

File: src/Scripting/CSharp/Hosting/CommandLine/Csi.cs [hunk 3]
```diff
@@ -18,15 +18,21 @@ internal CSharpInteractiveCompiler(string responseFile, string baseDirectory, st
         {
         }
 
+        internal override Type Type => typeof(CSharpInteractiveCompiler);
+
+        internal override string GetAssemblyFileVersion()
+        {
+            return Type.GetTypeInfo().Assembly.GetCustomAttribute<AssemblyFileVersionAttribute>().Version;
```
Comment (jasonmalinowski) [inline src/Scripting/CSharp/Hosting/CommandLine/Csi.cs]: Why not do this everywhere rather than having this be overridden? It seems like this should work in all cases?

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: There is none as far as I know. This isn't a new problem.

Comment (gafter) [inline src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: For the interactive assemblies, I suspect this is why we don't go looking for the file.

Comment (AlekseyTs) [inline src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: I think it is worth exploring if we can use Assembly.Location to extract the name.

---
In reply to: [81196987](https://github.com/dotnet/roslyn/pull/14181#discussion_r81196987) [](ancestors = 81196987)

File: src/Scripting/CSharp/Hosting/CommandLine/Csi.cs (hunk 3 above)
Comment (gafter) [inline src/Scripting/CSharp/Hosting/CommandLine/Csi.cs]: I don't know, but I suspect that the difference is due to the compiler server (for the command-line compilers), where the compiler server loads the assembly itself from disk. The base implementation models that (i.e. tells you the version of the compiler that the compiler server will run).

File: src/Compilers/CSharp/Portable/CommandLine/CSharpCompiler.cs [hunk 4]
```diff
@@ -254,6 +254,8 @@ public override void PrintLogo(TextWriter consoleOutput)
             consoleOutput.WriteLine();
         }
 
+        internal override Type Type => typeof(CSharpCompiler);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CommandLine/CSharpCompiler.cs]: >typeof(CSharpCompiler); [](start = 39, length = 23)

Consider adding a comment why not this.GetType().

File: src/Compilers/VisualBasic/Portable/CommandLine/VisualBasicCompiler.vb [hunk 5]
```diff
@@ -191,6 +191,12 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
             Return ErrorFactory.IdToString(ERRID.IDS_ToolName, Culture)
         End Function
 
+        Friend Overrides ReadOnly Property Type As Type
+            Get
+                Return GetType(VisualBasicCompiler)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/CommandLine/VisualBasicCompiler.vb]: >GetType(VisualBasicCompiler) [](start = 23, length = 28)

Consider adding a comment why not Me.GetType().

**Comment by AlekseyTs** [comment]
>> Strictly the name of the assembly and the file could differ. Is there no filename or location option you can use?

> There is none as far as I know.

I think it is worth exploring if we can use Assembly.Location to extract the name.

**Comment by gafter** [comment]
> I think it is worth exploring if we can use Assembly.Location to extract the name.

I tried that and it didn't work. Further exploration is outside the scope of this PR.

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: It is used for error logging. I will add a comment.

File: src/Compilers/CSharp/Portable/CommandLine/CSharpCompiler.cs (hunk 4 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/CommandLine/CSharpCompiler.cs]: Sure, I'll copy that part of the doc comment from the implemented method.

**Comment by gafter** [comment]
OK, I've added comments as requested by reviewers.

File: src/Scripting/CSharp/Hosting/CommandLine/Csi.cs (hunk 3 above)
Comment (jasonmalinowski) [inline src/Scripting/CSharp/Hosting/CommandLine/Csi.cs]: Ah, I see. Might be worth a comment there too.

Comment (gafter) [inline src/Scripting/CSharp/Hosting/CommandLine/Csi.cs]: I don't have sufficient confidence that I fully understand why things are this way. I'd rather not document what is just a (possibly accurate) guess.

**Comment by gafter** [comment]
@dotnet-bot test windows_debug_unit32_prtest please

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs [hunk 6]
```diff
@@ -86,21 +84,38 @@ public CommonCompiler(CommandLineParser parser, string responseFile, string[] ar
 
         internal abstract bool SuppressDefaultResponseFile(IEnumerable<string> args);
 
-        internal string GetAssemblyFileVersion()
+        /// <summary>
+        /// The type of the compiler class for version information in /help and /version.
+        /// We don't simply use this.GetType() because that would break mock subclasses.
+        /// </summary>
+        internal abstract Type Type { get; }
```
Comment (VSadov) [inline src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: NIT: I'd call it CompilerVersionType  or something like that. "Type" is already pretty overloaded term when code is in a compiler and is also using reflection.

**Comment by VSadov** [comment]
Overall the idea of taking the compiler version from the storage artifact seems a bit strange. - I.E. if I, hypothetically, compile IL into native code or c++, how do I retain the same version. 

Anyways, since the purpose is to unify the way we obtain the version, it seems   LGTM.

File: src/Scripting/CSharp/Hosting/CommandLine/Csi.cs (hunk 3 above)
Comment (jasonmalinowski) [inline src/Scripting/CSharp/Hosting/CommandLine/Csi.cs]: "I don't know" is a perfectly valid comment. It cleanly instills fear in the next person. :smile:

**Comment by jasonmalinowski** [comment]
@gafter I'm going to merge this to get the tests unblocked. I think any open questions are appropriate for later follow-up.
