### PR TITLE
Remove dependency on csc2 / vbc2

### LINKED ISSUE #5550: Roslyn.Compilers.CompilerServer.UnitTests.dll has failures in Standalone runs
45 unit tests fail inside this library because they are not able to find 'C:\Program Files (x86)\Msbuild\14.0\bin\amd64\csc2.exe'

Csc2.exe does appear in the list of UnitTestFiles to be copied over in DevDivInsertionFiles, however it does not appear like it is being inserted anywhere.

I'll be disabling this suite until this is fixed.

### PR DESCRIPTION
**Pull request by jaredpar**
This change removes the compiler server test dependency on csc2 and
vbc2.  These binaries don't exist in all environments where we run these
unit tests as they are no longer a part of the shipping product.
Instead I replaced all uses with csc / vbc and explicitly passed the
shared flag to the compiler.

closes #5550

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @AlekseyTs, @VSadov, @gafter, @agocke, @TyOverby

**Comment by VSadov** [comment]
LGTM

File: src/Compilers/Core/VBCSCompilerTests/CompilerServerTests.cs [hunk 1]
```diff
@@ -335,7 +331,7 @@ public void FallbackToCsc()
         {
             // Delete VBCSCompiler.exe so csc2 is forced to fall back to csc.exe
```
Comment (TyOverby) [inline src/Compilers/Core/VBCSCompilerTests/CompilerServerTests.cs]: Since csc2 is going away, should this comment still be here?

File: src/Compilers/Core/VBCSCompilerTests/CompilerServerTests.cs [hunk 2]
```diff
@@ -346,7 +342,7 @@ public void CscFallBackOutputNoUtf8()
 
             // Delete VBCSCompiler.exe so csc2 is forced to fall back to csc.exe
```
Comment (TyOverby) [inline src/Compilers/Core/VBCSCompilerTests/CompilerServerTests.cs]: Same here.

File: src/Compilers/Core/VBCSCompilerTests/CompilerServerTests.cs (hunk 1 above)
Comment (jaredpar) [inline src/Compilers/Core/VBCSCompilerTests/CompilerServerTests.cs]: Good catch, will remove
