### PR TITLE
fixed issue caused by VBOperationFactory

### LINKED ISSUE #19344: Semantic break introduced by VBOperationFactory refactoring
See code in master: http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/BoundTree/Expression.vb,1467

The operation kind depends on the length of the arguments in master, but is not so in features/operation branch: https://github.com/dotnet/roslyn/blob/features/ioperation/src/Compilers/Core/Portable/Generated/Operations.xml.Generated.cs#L1917

### PR DESCRIPTION
**Pull request by heejaechang**
@mavasani found issue caused by my VBOperationFactory work.

this fixes #19344

### CODE REVIEW

**Comment by heejaechang** [comment]
@mavasani @AlekseyTs @dotnet/analyzer-ioperation @333fred @jinujoseph can you take a look?

File: src/Compilers/VisualBasic/Test/Semantic/Diagnostics/OperationAnalyzerTests.vb [hunk 1]
```diff
@@ -1254,7 +1254,8 @@ End Class
             comp.VerifyAnalyzerDiagnostics({New EqualsValueTestAnalyzer}, Nothing, Nothing, False,
                                            Diagnostic(EqualsValueTestAnalyzer.EqualsValueDescriptor.Id, "= 44").WithLocation(2, 26),
                                            Diagnostic(EqualsValueTestAnalyzer.EqualsValueDescriptor.Id, "= ""Hello""").WithLocation(3, 25),
-                                           Diagnostic(EqualsValueTestAnalyzer.EqualsValueDescriptor.Id, "= Foo()").WithLocation(4, 26))
+                                           Diagnostic(EqualsValueTestAnalyzer.EqualsValueDescriptor.Id, "= Foo()").WithLocation(4, 26),
+                                           Diagnostic(EqualsValueTestAnalyzer.EqualsValueDescriptor.Id, "= 20").WithLocation(10, 84))
```
Comment (heejaechang) [inline src/Compilers/VisualBasic/Test/Semantic/Diagnostics/OperationAnalyzerTests.vb]: looks like @mavasani removed the last line when he added Skip for below tests. I am putting it back since it is right result.

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb [hunk 2]
```diff
@@ -23,7 +23,7 @@ Namespace Microsoft.CodeAnalysis.Semantics
                         ' It is not permissible to access the Left property of a BoundUserDefinedBinaryOperator unconditionally,
                         ' because that property can throw an exception if the operator expression is semantically invalid.
                         ' Fetching the left operand through IBinaryOperatorExpression is safe.
-                        If rightOperatorBinary.LeftOperand Is value.LeftOnTheRightOpt Then
+                        If rightOperatorBinary.LeftOperand Is Create(value.LeftOnTheRightOpt) Then
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: >Create(value.LeftOnTheRightOpt) [](start = 62, length = 31)

I am not sure I understand the motivation behind this change. Could you please elaborate?

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb [hunk 3]
```diff
@@ -681,7 +681,7 @@ Namespace Microsoft.CodeAnalysis.Semantics
             Dim parameter As IParameterSymbol = boundParameterEqualsValue.Parameter
             Dim value As Lazy(Of IOperation) = New Lazy(Of IOperation)(Function() Create(boundParameterEqualsValue.Value))
             Dim kind As OperationKind = OperationKind.ParameterInitializerAtDeclaration
-            Dim isInvalid As Boolean = DirectCast(boundParameterEqualsValue.Value, IOperation).IsInvalid
+            Dim isInvalid As Boolean = value.Value.IsInvalid
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb]: >value.Value.IsInvalid [](start = 39, length = 21)

What is the point in creating Lazy(Of IOperation) if we get its value two lines later?

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb]: Could we simply check boundParameterEqualsValue.Value.HasErrors instead?

---
In reply to: [116079177](https://github.com/dotnet/roslyn/pull/19406#discussion_r116079177) [](ancestors = 116079177)

**Comment by AlekseyTs** [comment]
Done with review pass.

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb (hunk 2 above)
Comment (heejaechang) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: rightOperatorBinary is IOperation. rightOperatorBinary.LeftOperand is IOperation.
value is BoundNode and value.LeftOnTheRightOpt is BoundNode. 

it used to work because BoundNode directly implemented IOperation. 
so "rightOperatorBinary.LeftOperand Is value.LeftOnTheRightOpt" would return true if both point to same instance of BoundNode which implements IOperation.

now, BoundNode and IOperation are different object so the above always return false.

the Create() method is IOperation factory entry point, IOperation Create(BoundNode).

so, if two were pointing to same BoundNode, Create will return same IOperation node which make "IS" work as it used to.

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb (hunk 3 above)
Comment (heejaechang) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb]: sure, I can do that.

FYI. in a few days, I will remove all isInvalid as we discussed in the earlier meeting.

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb (hunk 2 above)
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: It feels like all these checks should be performed on BoundNodes rather than on IOperation nodes. See how it is done in the previous case. I do not understand how did we end-up with code like this. I was under impression that the code was simply moved, but it turned out this is not the case, a projection to IOperation was added in some cases. Please identify all places like this in for both languages and remove added projections. 

---
In reply to: [116078819](https://github.com/dotnet/roslyn/pull/19406#discussion_r116078819) [](ancestors = 116078819)

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: > rightOperatorBinary is IOperation

I see, rightOperatorBinary was IOperation in original code, it shouldn't be.

Comment (heejaechang) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: @AlekseyTs  projection was in the original code, that  is why the projection was still there. the Create is only code added compared to the original code. what you ask will need some work, so can we do that in another PR so that we can make all test passed?

the original code, converted rightOpeartorBinary to IOperation so that it can use LeftOperand property which contains some logic over its original BoundNode. finding all those places and change all those back to BoundNode will require some work since original code was written in that way in the first place. basically we need to reverse the original code to the other way.

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: It looks like the original code was simply taking advantage (reusing) of implementation of IBinaryOperatorExpression.LeftOperand for BoundUserDefinedBinaryOperator. Instead of going through IOperation, we should get the same result of off BoundUserDefinedBinaryOperator directly.

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb (hunk 3 above)
Comment (heejaechang) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb]: @AlekseyTs basically these 2 cases are the case I missed which assumed BoundNode directly implements IOperation. so the original code used 2 type of nodes interchangeably. the original code cast one to the other in random places and use reference equality to make decision.

all I did here is make sure it normalized to IOperation when it compares reference equality.

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb (hunk 2 above)
Comment (heejaechang) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: for this particular case might be, but this pattern is all over the places in the original code. they assume 2 types are same object and they don't care which object is what type when they check reference equality.

so changing all those place back to BoundNode will require some work.

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: > so changing all those place back to BoundNode will require some work.

Sure, let's apply correct fix for this place in this PR.

Comment (heejaechang) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: @AlekseyTs just curious. rather than duplicating same logic in IOperation and the code above, what would be an issue of calling Create() as we did above?

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: The code should be based of off bound nodes, content of bound nodes determines the result we are calculating. We should not be taking dependency on today's implementation of IOperation, which might or might not change in the future, especially around placeholder nodes (this is what LeftOnTheRightOpt is). As for the code reuse, we can add a helper to the BoundUserDefinedBinaryOperator and reuse it in two places.

**Comment by heejaechang** [comment]
@AlekseyTs updated the code.

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb [hunk 4]
```diff
@@ -19,11 +19,13 @@ Namespace Microsoft.CodeAnalysis.Semantics
...
                     Case BoundKind.UserDefinedBinaryOperator
-                        Dim rightOperatorBinary As IBinaryOperatorExpression = DirectCast(Create(value.Right), IBinaryOperatorExpression)
+                        Dim rightOperatorBinary As BoundUserDefinedBinaryOperator = DirectCast(value.Right, BoundUserDefinedBinaryOperator)
+
                         ' It is not permissible to access the Left property of a BoundUserDefinedBinaryOperator unconditionally,
                         ' because that property can throw an exception if the operator expression is semantically invalid.
-                        ' Fetching the left operand through IBinaryOperatorExpression is safe.
-                        If rightOperatorBinary.LeftOperand Is value.LeftOnTheRightOpt Then
+                        ' get it through helper method
+                        Dim leftOperand = GetUserDefinedBinaryOperatorChild(rightOperatorBinary, 0)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: >GetUserDefinedBinaryOperatorChild(rightOperatorBinary, 0) [](start = 42, length = 57)

It looks like this is still projecting to IOperation, we should stay in bound node universe.

Comment (heejaechang) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: you are looking old one. can you refresh?

**Comment by heejaechang** [comment]
trying to figure out what is making building failing.

**Comment by heejaechang** [comment]
build failure was due to FI which enables roslyn analyzers which used to not run on this branch. that FI caused another bug to show up. I added fix to this PR.

**Comment by heejaechang** [comment]
retest windows_debug_unit32_prtest please

**Comment by heejaechang** [comment]
retest windows_debug_unit32_prtest please

**Comment by heejaechang** [comment]
@AlekseyTs can you take a look at the additional changes?

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb [hunk 5]
```diff
@@ -457,8 +491,11 @@ Namespace Microsoft.CodeAnalysis.Semantics
             Return s_variablesDeclMappings.GetValue(
                     boundUsingStatement,
                     Function(boundUsing)
+                        Dim declaration = If(boundUsing.ResourceList.IsDefaultOrEmpty,
```
Comment (heejaechang) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: this is the additional change.

**Comment by heejaechang** [comment]
@AlekseyTs ping?
