### PR TITLE
Constructors (& similar) should not be renamed if they are keywords (in VB)

### LINKED ISSUE #8297: Crash - Renaming escaped [New] token should not rename the constructor
1) Trigger rename for "[New]" in below code:

```VB
Class [New]
    Sub New()
    End Sub
End Class
```

**Expected**: Only 1 reference is found, constructor New is not renamed.
**Actual**: 2 references found by rename, including the constructor New. Renaming to a different name throws InvalidCastExceptions as the constructor also gets renamed.

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #8297

### CODE REVIEW

File: src/Workspaces/Core/Portable/Rename/RenameLocation.ReferenceProcessing.cs [hunk 1]
```diff
@@ -276,25 +276,29 @@ private static string TrimNameToAfterLastDot(string name)
...
                 // If we're renaming a named type, we'll also have to find constructors and
-                // destructors declarations that match the name
+                // destructors declarations that match the name if we're in C#. In VB these
+                // methods are not named to match the class.
                 if (referencedSymbol.Kind == SymbolKind.NamedType)
                 {
                     var namedType = (INamedTypeSymbol)referencedSymbol;
-
-                    foreach (var method in namedType.GetMembers().OfType<IMethodSymbol>())
+                    if (namedType.Language == LanguageNames.CSharp)
```
Comment (dpoeschl) [inline src/Workspaces/Core/Portable/Rename/RenameLocation.ReferenceProcessing.cs]: This is the only actual change. This may be contentious. Other options include adding `StructorNamesMatchTypeName` (working name) to ISyntaxFactsService and passing that in. I can't check the Kind because it's language-neutral. Other suggestions welcome...

**Comment by dpoeschl** [comment]
Tagging for review @dotnet/roslyn-ide

**Comment by Pilchie** [comment]
I don't *love* the language check, but I'm not too against it either.

File: src/Workspaces/Core/Portable/Rename/RenameLocation.ReferenceProcessing.cs (hunk 1 above)
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Rename/RenameLocation.ReferenceProcessing.cs]: Given talk is beginning about how to refactor this service to support other languages, this might just be creating debt there.

There's already other code in Rename to block renaming from a VB constructor (which you can't do) but would be allowed for a C# constructor. How does that work?

Comment (dpoeschl) [inline src/Workspaces/Core/Portable/Rename/RenameLocation.ReferenceProcessing.cs]: SyntaxFactsService.IsKeyword. I'll switch to that.

**Comment by dpoeschl** [comment]
Updated to use SyntaxFacts instead of using a language check.

Tagging for re-review @dotnet/roslyn-ide @jasonmalinowski

**Comment by balajikris** [comment]
:+1:

**Comment by dpoeschl** [comment]
Tagging for re-review @dotnet/roslyn-ide @jasonmalinowski

File: src/EditorFeatures/Test2/Rename/RenameEngineTests.vb [hunk 2]
```diff
@@ -5926,6 +5926,24 @@ End Class
...
+                            <Document><![CDATA[
+Class [|[$$New]|]
+    Sub New()
+    End Sub
+End Class
+]]>
+                            </Document>
+                        </Project>
+                    </Workspace>, renameTo:="New2")
+            End Using
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Test2/Rename/RenameEngineTests.vb]: Where do you do any verification?

Comment (dpoeschl) [inline src/EditorFeatures/Test2/Rename/RenameEngineTests.vb]: It doesn't crash. That's the verification.

File: src/Workspaces/Core/Portable/Rename/RenameLocation.ReferenceProcessing.cs [hunk 3]
```diff
@@ -279,8 +279,9 @@ private static string TrimNameToAfterLastDot(string name)
                 // destructors declarations that match the name
                 if (referencedSymbol.Kind == SymbolKind.NamedType)
                 {
-                    var namedType = (INamedTypeSymbol)referencedSymbol;
+                    ISyntaxFactsService syntaxFacts = null;
```
Comment (dpoeschl) [inline src/Workspaces/Core/Portable/Rename/RenameLocation.ReferenceProcessing.cs]: Perhaps. Do you think it should actually be changed?

File: src/EditorFeatures/Test2/Rename/RenameEngineTests.vb (hunk 2 above)
Comment (dpoeschl) [inline src/EditorFeatures/Test2/Rename/RenameEngineTests.vb]: Also the [| |]s around the class name but not around the constructor confirm that the rename spans are appropriate.

Comment (CyrusNajmabadi) [inline src/EditorFeatures/Test2/Rename/RenameEngineTests.vb]: Oh duh.  Sorry, thought this was a case where we just disable rename.  I can see it renames, just not the constructor.  Can you have another reference to show that that other reference (i.e. not hte decl) does get renamed?

File: src/Workspaces/Core/Portable/Rename/RenameLocation.ReferenceProcessing.cs (hunk 3 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Rename/RenameLocation.ReferenceProcessing.cs]: yes.  it just looks ugly as sin.  You're going to get the locations in 99.999% of all cases.  So just get the value up front so you can use it :)

**Comment by dpoeschl** [comment]
@CyrusNajmabadi I removed the ugly-as-sin laziness. Review plz. :smile:

**Comment by CyrusNajmabadi** [comment]
I liked it better before.

**Comment by CyrusNajmabadi** [comment]
:+1:
