### PR TITLE
Check nullability for delegate creation arguments

### LINKED ISSUE #37984: Roslyn should warn about null arguments to delegates' constructors
**Version Used**: 

```
Branch master (10 Aug 2019)
Latest commit c21548 by dotnet-automerge-bot:
Merge pull request #37896 from dotnet/merges/release/dev16.3-preview2-to-master

Merge release/dev16.3-preview2 to master
```

**Steps to Reproduce**:

Compile and run the following code:
```cs
#nullable enable
using System;

class C
{
  static void Main()
  {
    M(null);
  }
  static void M(Action? a)
  {
    var d = new D(a);
  }
}

delegate void D();
```

**Expected Behavior**:
Warning reported for `new D(a)` as delegates' constructors do not accept nulls.

**Actual Behavior**:
No warnings. The program crashes at runtime with 
```
System.ArgumentException: Delegate to an instance method cannot have null 'this'.
   at System.MulticastDelegate.CtorClosed(Object target, IntPtr methodPtr)
   at C.M(Action a)
   at C.Main()
```

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #37984

Note that the nullability mismatch checks were already happening for method groups and lambdas, but not for delegate arguments.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 1]
```diff
@@ -44138,6 +44138,131 @@ static void Main()
...
+        _ = new Action(d2); // 2
+        _ = new Action(d2!);
+    }
+}
+";
+            var comp = CreateNullableCompilation(source);
+            comp.VerifyDiagnostics(
+                // (11,19): warning CS8601: Possible null reference assignment.
+                //         _ = new D(a2); // 1
+                Diagnostic(ErrorCode.WRN_NullReferenceAssignment, "a2").WithLocation(11, 19),
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >WRN_NullReferenceAssignment [](start = 37, length = 27)

Should this be `WRN_NullReferenceArgument`?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 2]
```diff
@@ -5250,6 +5250,17 @@ public override BoundNode VisitDelegateCreationExpression(BoundDelegateCreationE
...
+                        var argState = VisitRvalueWithState(arg);
+                        ReportNullableAssignmentIfNecessary(arg, argTypeWithAnnotations, argState, useLegacyWarnings: false);
+                        if (!arg.IsSuppressed)
+                        {
+                            ReportNullabilityMismatchWithTargetDelegate(arg.Syntax.Location, delegateType, arg.Type.DelegateInvokeMethod(), invokedAsExtensionMethod: false);
+                        }
+                    }
+                    break;
                 default:
                     VisitRvalue(node.Argument);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >VisitRvalue [](start = 20, length = 11)

It feels like the issue is we're not calling `VisitConversion` here. For instance, we're not reporting any warning for the following:
```C#
delegate void D<T>(T t);
class Program
{
    static void M(D<object> d)
    {
        _ = new D<object?>(d);
    }
}
```
Consider changing this to something like:
```C#
VisitOptionalImplicitConversion(
    node.Argument,
    TypeWithAnnotations.Create(delegateType, NullableAnnotation.NotAnnotated),
    useLegacyWarnings: false,
    trackMembers: false,
    assignmentKind: AssignmentKind.Assignment);
```

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 3]
```diff
@@ -44138,6 +44138,131 @@ static void Main()
...
+        _ = new D1(a2);
+        _ = new D2(a1); // 1
+        _ = new D2(a1!);
+        _ = new D2(a2);
+        _ = new Action<string>(d1);
+        _ = new Action<string>(d2);
+        _ = new Action<string?>(d1); // 2
+        _ = new Action<string?>(d1!);
+        _ = new Action<string?>(d2);
+    }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: > } [](start = 3, length = 2)

Consider testing:
```
_ = new D(d1);
_ = new D(d2);
_ = new D(default(D));
```

Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Please test nested nullability mismatch:
```C#
delegate void D<T>(T t);
class Program
{
    static void M(D<object> d)
    {
        _ = new D<object?>(d);
    }
}
```

---
In reply to: [315376466](https://github.com/dotnet/roslyn/pull/38063#discussion_r315376466) [](ancestors = 315376466)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 2 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Actually, calling `VisitConversion` probably won't work because that method does not handle implicit MethodGroup conversions.

---
In reply to: [315370081](https://github.com/dotnet/roslyn/pull/38063#discussion_r315370081) [](ancestors = 315370081)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 4]
```diff
@@ -5250,6 +5250,17 @@ public override BoundNode VisitDelegateCreationExpression(BoundDelegateCreationE
...
                     }
                     break;
+                case BoundExpression arg when arg.Type is { TypeKind: TypeKind.Delegate } argType:
+                    {
+                        var argTypeWithAnnotations = TypeWithAnnotations.Create(argType, NullableAnnotation.NotAnnotated);
+                        var argState = VisitRvalueWithState(arg);
+                        ReportNullableAssignmentIfNecessary(arg, argTypeWithAnnotations, argState, useLegacyWarnings: false);
+                        if (!arg.IsSuppressed)
+                        {
+                            ReportNullabilityMismatchWithTargetDelegate(arg.Syntax.Location, delegateType, arg.Type.DelegateInvokeMethod(), invokedAsExtensionMethod: false);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >arg.Type [](start = 107, length = 8)

`argType`
