### PR TITLE
Fixed incorrect IDE0044 (Make field readonly) when the field is accessed by refeference.

### LINKED ISSUE #38995: Incorrect IDE0044 (Make field readonly) when used with "ref"
**Version Used**: 16.3.1

**Steps to Reproduce**:
``` csharp
using System;

class Program
{
    private static Int32 Value;

    static void Main()
    {
        ref var value = ref Value;
        value += 1;
    }
}
```
**Expected Behavior**: No errors / warnings / messages.

**Actual Behavior**:  IDE0044	Make field readonly.

Here is a counter example where it works as expected:
``` csharp
using System;

class Program
{
    private static Int32 Value;

    static void Main()
    {
        Increment( ref Value );
    }

    static void Increment( ref Int32 value ) => value += 1;
}
```

### PR DESCRIPTION
**Pull request by zlatanov**
In OperationExtensions there is an extension method **GetValueUsageInfo** which should return whether a given operation performs any read, write, etc.

The **MakeFieldReadonlyDiagnosticAnalyzer** class uses this information to infer whether a field can be made readonly. GetValueUsageInfo doesn't perform any analysis when the operation's parent is variable initializer and in that case it always returns **ValueUsageInfo.Read** which causes the diagnostic analyzer to wrongly suggest to make a field readonly.

Here is example where it fails:

``` csharp
class Program
{
    int i;

    void M()
    {
        ref var value = ref i;
        value += 1;
    }
}
```
 I've added a case inside GetValueUsageInfo to correctly handle this situation and also introduced 2 new unit tests to verify it is working. I am unsure however if somewhere there isn't something that depends on the method returning incorrectly ValueUsageInfo.Read for such cases.

Fixes #38995.

### CODE REVIEW

File: src/Workspaces/Core/Portable/Extensions/OperationExtensions.cs [hunk 1]
```diff
@@ -144,6 +146,20 @@ public static ValueUsageInfo GetValueUsageInfo(this IOperation operation)
...
+                if (variableInitializerOperation.Parent is IVariableDeclaratorOperation variableDeclaratorOperation)
+                {
+                    switch (variableDeclaratorOperation.Symbol.RefKind)
+                    {
+                        case RefKind.Ref:
+                            return ValueUsageInfo.ReadableWritableReference;
+
+                        case RefKind.RefReadOnly:
+                            return ValueUsageInfo.ReadableReference;
+                    }
```
Comment (sharwell) [inline src/Workspaces/Core/Portable/Extensions/OperationExtensions.cs]: @mavasani Should we include the `default` case here rather than rely on fall-through?

Comment (mavasani) [reply src/Workspaces/Core/Portable/Extensions/OperationExtensions.cs]: Would the default be something other then Read?
