### PR TITLE
Fix "path cost" calculation when computing the shortest path to the exit of a decision dag...

### LINKED ISSUE #47164: `"csc.exe" exited with code -2146232797.` using Version 5.0.100-preview.8.20417.9
**Version Used**:
 - MS Build Engine 16.8.0-preview-20414-02+a55ce4fbb
 - .NET Core SDK 5.0.100-preview.8.20417.9

**Steps to Reproduce**:
This may be reproducable by cloning https://github.com/Unknown6656/Unknown6656.Core and trying to build the project `/Unknown6656.Core/Unknown6656.Core.csproj` using the .NET Core SDK version 5.0.100-preview.8.20417.9

**Expected Behavior**:
No crash of `csc.exe` (at least, it did not crash on version 5.0.100-preview.7.20366.6)

**Actual Behavior**:
(I'm so sorry for the wall of text)
```
Microsoft (R) Build Engine version 16.8.0-preview-20414-02+a55ce4fbb for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error : Process terminated. System.InvalidOperationException: This program location is thought to be unreachable. [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.ShortestPathToNode(ImmutableArray`1 nodes, BoundDecisionDagNode node, Boolean nullPaths, Boolean& requiresFalseWhenClause) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.SamplePatternForPathToDagNode(BoundDagTemp rootIdentifier, ImmutableArray`1 nodes, BoundDecisionDagNode targetNode, Boolean nullPaths, Boolean& requiresFalseWhenClause) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.CheckSwitchExpressionExhaustive(SwitchExpressionSyntax node, BoundExpression boundInputExpression, ImmutableArray`1 switchArms, BoundDecisionDag& decisionDag, LabelSymbol& defaultLabel, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.BindSwitchExpressionCore(SwitchExpressionSyntax node, Binder originalBinder, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindPossibleArrayInitializer(ExpressionSyntax node, TypeSymbol destinationType, BindValueKind valueKind, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindVariableDeclaration(SourceLocalSymbol localSymbol, LocalDeclarationKind kind, Boolean isVar, VariableDeclaratorSyntax declarator, TypeSyntax typeSyntax, TypeWithAnnotations declTypeOpt, AliasSymbol aliasOpt, DiagnosticBag diagnostics, Boolean includeBoundType, CSharpSyntaxNode associatedSyntaxNode) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindDeclarationStatementParts(LocalDeclarationStatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindLocalDeclarationStatement(LocalDeclarationStatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindPossibleEmbeddedStatement(StatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindIfStatement(IfStatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode declaration, BlockSyntax blockBody, ArrowExpressionClauseSyntax expressionBody, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode syntax, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, DiagnosticBag diagnostics, ImportChain& importChain, Boolean& originalBodyNested, InitialState& forSemanticModel) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass22_0.<CompileNamedTypeAsync>b__0() [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at System.Environment.FailFast(System.String, System.Exception) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.FatalError.Report(System.Exception, System.Action`1<System.Exception>) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.FatalError.ReportUnlessCanceled(System.Exception) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass22_0.<CompileNamedTypeAsync>b__0() [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.ShortestPathToNode(System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.BoundDecisionDagNode>, Microsoft.CodeAnalysis.CSharp.BoundDecisionDagNode, Boolean, Boolean ByRef) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.SamplePatternForPathToDagNode(Microsoft.CodeAnalysis.CSharp.BoundDagTemp, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.BoundDecisionDagNode>, Microsoft.CodeAnalysis.CSharp.BoundDecisionDagNode, Boolean, Boolean ByRef) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.CheckSwitchExpressionExhaustive(Microsoft.CodeAnalysis.CSharp.Syntax.SwitchExpressionSyntax, Microsoft.CodeAnalysis.CSharp.BoundExpression, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.BoundSwitchExpressionArm>, Microsoft.CodeAnalysis.CSharp.BoundDecisionDag ByRef, Microsoft.CodeAnalysis.CSharp.Symbols.LabelSymbol ByRef, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.BindSwitchExpressionCore(Microsoft.CodeAnalysis.CSharp.Syntax.SwitchExpressionSyntax, Microsoft.CodeAnalysis.CSharp.Binder, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.DiagnosticBag, Boolean, Boolean) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.DiagnosticBag, Boolean, Boolean) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindPossibleArrayInitializer(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, BindValueKind, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindVariableDeclaration(Microsoft.CodeAnalysis.CSharp.Symbols.SourceLocalSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.LocalDeclarationKind, Boolean, Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclaratorSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax, Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithAnnotations, Microsoft.CodeAnalysis.CSharp.Symbols.AliasSymbol, Microsoft.CodeAnalysis.DiagnosticBag, Boolean, Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindDeclarationStatementParts(Microsoft.CodeAnalysis.CSharp.Syntax.LocalDeclarationStatementSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindLocalDeclarationStatement(Microsoft.CodeAnalysis.CSharp.Syntax.LocalDeclarationStatementSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindPossibleEmbeddedStatement(Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindIfStatement(Microsoft.CodeAnalysis.CSharp.Syntax.IfStatementSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode, Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.ArrowExpressionClauseSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.TypeCompilationState, Microsoft.CodeAnalysis.DiagnosticBag, Microsoft.CodeAnalysis.CSharp.ImportChain ByRef, Boolean ByRef, InitialState ByRef) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Int32, ProcessedFieldInitializers ByRef, Microsoft.CodeAnalysis.CSharp.SynthesizedSubmissionFields, Microsoft.CodeAnalysis.CSharp.TypeCompilationState) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass22_0.<CompileNamedTypeAsync>b__0() [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Roslyn.Utilities.UICultureUtilities+<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at System.Threading.Tasks.Task.InnerInvoke() [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at System.Threading.Tasks.Task+<>c.<.cctor>b__277_0(System.Object) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at System.Threading.ThreadPoolWorkQueue.Dispatch() [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error : System.InvalidOperationException: This program location is thought to be unreachable. [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.ShortestPathToNode(ImmutableArray`1 nodes, BoundDecisionDagNode node, Boolean nullPaths, Boolean& requiresFalseWhenClause) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.SamplePatternForPathToDagNode(BoundDagTemp rootIdentifier, ImmutableArray`1 nodes, BoundDecisionDagNode targetNode, Boolean nullPaths, Boolean& requiresFalseWhenClause) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.CheckSwitchExpressionExhaustive(SwitchExpressionSyntax node, BoundExpression boundInputExpression, ImmutableArray`1 switchArms, BoundDecisionDag& decisionDag, LabelSymbol& defaultLabel, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.BindSwitchExpressionCore(SwitchExpressionSyntax node, Binder originalBinder, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindPossibleArrayInitializer(ExpressionSyntax node, TypeSymbol destinationType, BindValueKind valueKind, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindVariableDeclaration(SourceLocalSymbol localSymbol, LocalDeclarationKind kind, Boolean isVar, VariableDeclaratorSyntax declarator, TypeSyntax typeSyntax, TypeWithAnnotations declTypeOpt, AliasSymbol aliasOpt, DiagnosticBag diagnostics, Boolean includeBoundType, CSharpSyntaxNode associatedSyntaxNode) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindDeclarationStatementParts(LocalDeclarationStatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindLocalDeclarationStatement(LocalDeclarationStatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindPossibleEmbeddedStatement(StatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindIfStatement(IfStatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode declaration, BlockSyntax blockBody, ArrowExpressionClauseSyntax expressionBody, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode syntax, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, DiagnosticBag diagnostics, ImportChain& importChain, Boolean& originalBodyNested, InitialState& forSemanticModel) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass22_0.<CompileNamedTypeAsync>b__0() [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]

Build FAILED.

C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error : Process terminated. System.InvalidOperationException: This program location is thought to be unreachable. [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.ShortestPathToNode(ImmutableArray`1 nodes, BoundDecisionDagNode node, Boolean nullPaths, Boolean& requiresFalseWhenClause) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.SamplePatternForPathToDagNode(BoundDagTemp rootIdentifier, ImmutableArray`1 nodes, BoundDecisionDagNode targetNode, Boolean nullPaths, Boolean& requiresFalseWhenClause) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.CheckSwitchExpressionExhaustive(SwitchExpressionSyntax node, BoundExpression boundInputExpression, ImmutableArray`1 switchArms, BoundDecisionDag& decisionDag, LabelSymbol& defaultLabel, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.BindSwitchExpressionCore(SwitchExpressionSyntax node, Binder originalBinder, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindPossibleArrayInitializer(ExpressionSyntax node, TypeSymbol destinationType, BindValueKind valueKind, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindVariableDeclaration(SourceLocalSymbol localSymbol, LocalDeclarationKind kind, Boolean isVar, VariableDeclaratorSyntax declarator, TypeSyntax typeSyntax, TypeWithAnnotations declTypeOpt, AliasSymbol aliasOpt, DiagnosticBag diagnostics, Boolean includeBoundType, CSharpSyntaxNode associatedSyntaxNode) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindDeclarationStatementParts(LocalDeclarationStatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindLocalDeclarationStatement(LocalDeclarationStatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindPossibleEmbeddedStatement(StatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindIfStatement(IfStatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode declaration, BlockSyntax blockBody, ArrowExpressionClauseSyntax expressionBody, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode syntax, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, DiagnosticBag diagnostics, ImportChain& importChain, Boolean& originalBodyNested, InitialState& forSemanticModel) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass22_0.<CompileNamedTypeAsync>b__0() [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at System.Environment.FailFast(System.String, System.Exception) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.FatalError.Report(System.Exception, System.Action`1<System.Exception>) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.FatalError.ReportUnlessCanceled(System.Exception) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass22_0.<CompileNamedTypeAsync>b__0() [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.ShortestPathToNode(System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.BoundDecisionDagNode>, Microsoft.CodeAnalysis.CSharp.BoundDecisionDagNode, Boolean, Boolean ByRef) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.SamplePatternForPathToDagNode(Microsoft.CodeAnalysis.CSharp.BoundDagTemp, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.BoundDecisionDagNode>, Microsoft.CodeAnalysis.CSharp.BoundDecisionDagNode, Boolean, Boolean ByRef) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.CheckSwitchExpressionExhaustive(Microsoft.CodeAnalysis.CSharp.Syntax.SwitchExpressionSyntax, Microsoft.CodeAnalysis.CSharp.BoundExpression, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.BoundSwitchExpressionArm>, Microsoft.CodeAnalysis.CSharp.BoundDecisionDag ByRef, Microsoft.CodeAnalysis.CSharp.Symbols.LabelSymbol ByRef, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.BindSwitchExpressionCore(Microsoft.CodeAnalysis.CSharp.Syntax.SwitchExpressionSyntax, Microsoft.CodeAnalysis.CSharp.Binder, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.DiagnosticBag, Boolean, Boolean) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.DiagnosticBag, Boolean, Boolean) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindPossibleArrayInitializer(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, BindValueKind, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindVariableDeclaration(Microsoft.CodeAnalysis.CSharp.Symbols.SourceLocalSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.LocalDeclarationKind, Boolean, Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclaratorSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax, Microsoft.CodeAnalysis.CSharp.Symbols.TypeWithAnnotations, Microsoft.CodeAnalysis.CSharp.Symbols.AliasSymbol, Microsoft.CodeAnalysis.DiagnosticBag, Boolean, Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindDeclarationStatementParts(Microsoft.CodeAnalysis.CSharp.Syntax.LocalDeclarationStatementSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindLocalDeclarationStatement(Microsoft.CodeAnalysis.CSharp.Syntax.LocalDeclarationStatementSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindPossibleEmbeddedStatement(Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindIfStatement(Microsoft.CodeAnalysis.CSharp.Syntax.IfStatementSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode, Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.ArrowExpressionClauseSyntax, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode, Microsoft.CodeAnalysis.DiagnosticBag) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.TypeCompilationState, Microsoft.CodeAnalysis.DiagnosticBag, Microsoft.CodeAnalysis.CSharp.ImportChain ByRef, Boolean ByRef, InitialState ByRef) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Int32, ProcessedFieldInitializers ByRef, Microsoft.CodeAnalysis.CSharp.SynthesizedSubmissionFields, Microsoft.CodeAnalysis.CSharp.TypeCompilationState) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass22_0.<CompileNamedTypeAsync>b__0() [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Roslyn.Utilities.UICultureUtilities+<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at System.Threading.Tasks.Task.InnerInvoke() [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at System.Threading.Tasks.Task+<>c.<.cctor>b__277_0(System.Object) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at System.Threading.ThreadPoolWorkQueue.Dispatch() [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error : System.InvalidOperationException: This program location is thought to be unreachable. [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.ShortestPathToNode(ImmutableArray`1 nodes, BoundDecisionDagNode node, Boolean nullPaths, Boolean& requiresFalseWhenClause) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.PatternExplainer.SamplePatternForPathToDagNode(BoundDagTemp rootIdentifier, ImmutableArray`1 nodes, BoundDecisionDagNode targetNode, Boolean nullPaths, Boolean& requiresFalseWhenClause) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.CheckSwitchExpressionExhaustive(SwitchExpressionSyntax node, BoundExpression boundInputExpression, ImmutableArray`1 switchArms, BoundDecisionDag& decisionDag, LabelSymbol& defaultLabel, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.BindSwitchExpressionCore(SwitchExpressionSyntax node, Binder originalBinder, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindPossibleArrayInitializer(ExpressionSyntax node, TypeSymbol destinationType, BindValueKind valueKind, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindVariableDeclaration(SourceLocalSymbol localSymbol, LocalDeclarationKind kind, Boolean isVar, VariableDeclaratorSyntax declarator, TypeSyntax typeSyntax, TypeWithAnnotations declTypeOpt, AliasSymbol aliasOpt, DiagnosticBag diagnostics, Boolean includeBoundType, CSharpSyntaxNode associatedSyntaxNode) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindDeclarationStatementParts(LocalDeclarationStatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindLocalDeclarationStatement(LocalDeclarationStatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindPossibleEmbeddedStatement(StatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindIfStatement(IfStatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode declaration, BlockSyntax blockBody, ArrowExpressionClauseSyntax expressionBody, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode syntax, DiagnosticBag diagnostics) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, DiagnosticBag diagnostics, ImportChain& importChain, Boolean& originalBodyNested, InitialState& forSemanticModel) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\Roslyn\Microsoft.CSharp.Core.targets(70,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass22_0.<CompileNamedTypeAsync>b__0() [L:\Projects.VisualStudio\Unknown6656.Core\Unknown6656.Core\Unknown6656.Core.csproj]
```

### PR DESCRIPTION
**Pull request by gafter**
...in the face of multiple when clauses, for the purpose of constructing the "not exhaustive" diagnostic.
Fixes #47164

### CODE REVIEW

**Comment by gafter** [comment]
May I please have a review of this small fix to a compiler crash?

File: src/Compilers/CSharp/Portable/Binder/PatternExplainer.cs [hunk 1]
```diff
@@ -52,10 +52,11 @@ int distance(BoundDecisionDagNode x)
...
-                    BoundTestDecisionDagNode t when distance(t.WhenTrue) is var trueDist && distance(t.WhenFalse) is var falseDist =>
-                        (trueDist <= falseDist) ? (1 + trueDist, t.WhenTrue) : (1 + falseDist, t.WhenFalse),
-                    BoundWhenDecisionDagNode w when distance(w.WhenTrue) is var trueDist && distance(w.WhenFalse) is var falseDist =>
-                        (trueDist <= falseDist) ? (1 + trueDist, w.WhenTrue) : (1 + falseDist + nodeCount, w.WhenFalse),
+                    BoundTestDecisionDagNode t when distance(t.WhenTrue) is var trueDist1 && distance(t.WhenFalse) is var falseDist1 =>
+                        (trueDist1 <= falseDist1) ? (1 + trueDist1, t.WhenTrue) : (1 + falseDist1, t.WhenFalse),
+                    BoundWhenDecisionDagNode w when distance(w.WhenTrue) is var trueDist2 && distance(w.WhenFalse) is var falseDist2 =>
+                        // add nodeCount to the distance if we need to flag that the path requires failure of a when clause
+                        (trueDist2 <= falseDist2) ? (1 + trueDist2, w.WhenTrue) : (1 + (falseDist2 < nodeCount ? nodeCount : 0) + falseDist2, w.WhenFalse),
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/PatternExplainer.cs:59]: Just checking my understanding: would a bad behavior be introduced if we changed `1 + (falseDist2 < nodeCount ? nodeCount : 0) + falseDist2` to `1 + (falseDist2 < nodeCount ? nodeCount : 0)`?

**Review by RikkiGibson — APPROVED** [review]
