### PR TITLE
Fix generate field doesn't recognize accessibility modifier configuration

### LINKED ISSUE #27716: Generate field doesn't recognize accessibility modifier configuration
**Version Used**: 
VS 2017 15.8p2
**Steps to Reproduce**:

1.  Add the following to an .editorconfig: 
`dotnet_style_require_accessibility_modifiers = omit_if_default:suggestion`
2. Create a class and add a constructor with a parameter. Hit `Ctrl + .` to get the quickfix to add and initialize a field.

**Expected Behavior**:
Field gets created as `readonly int foo;`

**Actual Behavior**:

Field gets created as `private readonly int foo;`

### PR DESCRIPTION
**Pull request by allisonchou**
Fixes #27716 
--
This fix operates under the assumption that the option "omit_if_default" operates the same way as "never" whenever the generate field/property option is invoked.

Also added applicable tests.

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/InitializeParameter/InitializeMemberFromParameterTests.cs [hunk 1]
```diff
@@ -648,5 +650,164 @@ public C(string s, int i)
...
+{
+    readonly int test = 5;
+
+    public C(int test, int test2)
+    {
+        Test2 = test2;
+    }
+
+    int Test2 { get; }
+}", index: 0, parameters: new TestParameters(options: Option(CodeStyleOptions.RequireAccessibilityModifiers, AccessibilityModifiersRequired.OmitIfDefault, NotificationOption.Warning)));
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/InitializeParameter/InitializeMemberFromParameterTests.cs]: can you make some static members for these options?  it's easier to read the test if it says: `parameters: OmitIfDefault_Warning`

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/InitializeParameter/InitializeMemberFromParameterTests.cs]: This is wrong.  You should be making a public property.  but this will make a private property.

File: src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs [hunk 2]
```diff
@@ -157,23 +168,33 @@ private static string GenerateUniqueName(IParameterSymbol parameter, ImmutableAr
...
                 if (rule.SymbolSpecification.AppliesTo(SymbolKind.Property, Accessibility.Public))
                 {
                     var uniqueName = GenerateUniqueName(parameter, parameterNameParts, rule);
 
+                    // We do not add an accessibility level if the user turned the setting off
+                    var accessibilityLevel = Accessibility.Public;
+                    if (requireAccessibilityModifiers.Value == AccessibilityModifiersRequired.Never || requireAccessibilityModifiers.Value == AccessibilityModifiersRequired.OmitIfDefault)
+                    {
+                        accessibilityLevel = Accessibility.NotApplicable;
+                    }
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs]: This is wrong.  This is not what this option controls.  The option controls whether or modifiers are required in the case where they're redundant.  But 'public' is never redundant.  If you leave it off, the property will be private.  And that's not what is being generated.

Comment (allisonchou) [reply src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs]: Oh I see, thank you for the clarification! I'll fix that ASAP. The option should still apply for fields though, correct?

File: src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs [hunk 3]
```diff
@@ -122,18 +123,28 @@ internal abstract partial class AbstractInitializeMemberFromParameterCodeRefacto
...
                 if (rule.SymbolSpecification.AppliesTo(SymbolKind.Field, Accessibility.Private))
                 {
                     var uniqueName = GenerateUniqueName(parameter, parameterNameParts, rule);
 
+                    // We do not add an accessibility level if the user turned the setting off
+                    var accessibilityLevel = Accessibility.Private;
+                    if (requireAccessibilityModifiers.Value == AccessibilityModifiersRequired.Never || requireAccessibilityModifiers.Value == AccessibilityModifiersRequired.OmitIfDefault)
+                    {
+                        accessibilityLevel = Accessibility.NotApplicable;
+                    }
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs]: This is not correct for fields in a VB struct.  We want to generate private fields.  And if you do not add the accessibility modifier then the field will be public in that struct.

File: src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs (hunk 2 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs]: Most of the time.  But there is a case for VB where it does not apply.  Thanks!

**Comment by CyrusNajmabadi** [comment]
Done with first pass.

**Comment by allisonchou** [comment]
Thanks Cyrus! I didn't realize there were so many different cases. I'll fix them ASAP.

File: src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs (hunk 3 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs]: It's actually not just fields.  properties are public in VB as well afaict. Gotta look through all the rules :)

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs]: You can look at: C:\GitHub\roslyn\src\Features\VisualBasic\Portable\AddAccessibilityModifiers\VisualBasicAddAccessibilityModifiersDiagnosticAnalyzer.vb

from tehre, you can see that teh only time in VB where you get something private is:

```vb
            If member.IsParentKind(SyntaxKind.ClassBlock) OrElse 
               member.IsParentKind(SyntaxKind.ModuleBlock) Then                
                If member.IsKind(SyntaxKind.FieldDeclaration) Then
                    Return accessibility = Accessibility.Private
                End If
            End If
```

So, if the above doesn't hold, you need the accessibility modifier.  If it does hold, hten you can omit if teh user doesn't want redundant modifiers.

**Comment by allisonchou** [comment]
@CyrusNajmabadi I believe I fixed the code to account for the various C# and VB cases. Whenever you have time, would it be possible to request another review?

**Comment by CyrusNajmabadi** [comment]
Definitely!

File: src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs [hunk 4]
```diff
@@ -122,18 +125,49 @@ internal abstract partial class AbstractInitializeMemberFromParameterCodeRefacto
...
             {
                 if (rule.SymbolSpecification.AppliesTo(SymbolKind.Field, Accessibility.Private))
                 {
                     var uniqueName = GenerateUniqueName(parameter, parameterNameParts, rule);
 
+                    var accessibilityLevel = Accessibility.Private;
+                    if (requireAccessibilityModifiers.Value == AccessibilityModifiersRequired.Never || requireAccessibilityModifiers.Value == AccessibilityModifiersRequired.OmitIfDefault)
+                    {
+                        // C#: always remove modifier for fields if "omit if default" or "never" option is set
+                        if (functionDeclaration.Language == LanguageNames.CSharp)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs]: might be good to clarify why this is.  specifically, because we're generating a 'private' field, and since 'private' is the default, this will do the right thing.

File: src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs [hunk 5]
```diff
@@ -122,18 +125,49 @@ internal abstract partial class AbstractInitializeMemberFromParameterCodeRefacto
...
+                        {
+                            accessibilityLevel = Accessibility.NotApplicable;
+                        }
+                        // VB: only remove modifier for fields if "omit if default" or "never" option is set and code is within a class or module
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs]: needs explanation as well.

File: src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs [hunk 6]
```diff
@@ -122,18 +125,49 @@ internal abstract partial class AbstractInitializeMemberFromParameterCodeRefacto
...
+                        else if (functionDeclaration.Language == LanguageNames.VisualBasic)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs]: so, at core layers, we do not fork behavior based on language.  The correct way to do this is to introduce an abstract method to control this and then supply implementations in the C# and VB subclasses.  Thanks!

File: src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj [hunk 7]
```diff
@@ -16,6 +16,7 @@
   </PropertyGroup>
   <ItemGroup Label="Project References">
     <ProjectReference Include="..\..\..\Compilers\Core\Portable\Microsoft.CodeAnalysis.csproj" />
+    <ProjectReference Include="..\..\..\Compilers\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.csproj" />
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Microsoft.CodeAnalysis.Features.csproj]: Noooooooooooooooop :)

**Comment by CyrusNajmabadi** [comment]
Done with pass.

**Comment by allisonchou** [comment]
@CyrusNajmabadi Thank you for the feedback! I took your recommendation of adding an abstract method. If there is anything else that can be improved, please let me know. :)

File: src/Features/CSharp/Portable/InitializeParameter/CSharpInitializeMemberFromParameterCodeRefactoringProvider.cs [hunk 8]
```diff
@@ -35,5 +35,8 @@ protected override void InsertStatement(SyntaxEditor editor, SyntaxNode function
 
         protected override bool IsImplicitConversion(Compilation compilation, ITypeSymbol source, ITypeSymbol destination)
             => InitializeParameterHelpers.IsImplicitConversion(compilation, source, destination);
+
+        // We always generate private fields. Since "private" is the default accessibility for fields in C#, we do not need an accessibility modifier.
+        protected override Accessibility CreateFieldHelper(Document document, SyntaxNode functionDeclaration, SemanticModel model, CancellationToken cancellationToken) => Accessibility.NotApplicable;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InitializeParameter/CSharpInitializeMemberFromParameterCodeRefactoringProvider.cs]: nit: wrap => to the next line, like the method above.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/InitializeParameter/CSharpInitializeMemberFromParameterCodeRefactoringProvider.cs]: Someting aobut this name doesn't make sense to me.  I think it woul dbe better as DetermineDesiredFieldAccessibility.

File: src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs [hunk 9]
```diff
@@ -122,18 +121,28 @@ internal abstract partial class AbstractInitializeMemberFromParameterCodeRefacto
...
                 if (rule.SymbolSpecification.AppliesTo(SymbolKind.Field, Accessibility.Private))
                 {
                     var uniqueName = GenerateUniqueName(parameter, parameterNameParts, rule);
 
+                    var accessibilityLevel = Accessibility.Private;
+                    if (requireAccessibilityModifiers.Value == AccessibilityModifiersRequired.Never || requireAccessibilityModifiers.Value == AccessibilityModifiersRequired.OmitIfDefault)
+                    {
+                        var model = await document.GetSemanticModelAsync(cancellationToken).ConfigureAwait(false);
+                        accessibilityLevel = CreateFieldHelper(document, functionDeclaration, model, cancellationToken);
+                    }
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs]: Note: i don't think processing fields is enough.  This feature can generate properties right?  And, in VB, a property is public by default in a class..  So if the user had the option on that they don't want redundant modifiers, we'd want to strip the modifier on a property in the vb case, right?

File: src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicInitializeMemberFromParameterCodeRefactoringProvider.vb [hunk 10]
```diff
@@ -40,5 +41,22 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.InitializeParameter
...
+                Dim containingTypeSymbol = CType(model.GetDeclaredSymbol(containingTypeNode, cancellationToken), INamedTypeSymbol)
+
+                ' We always generate private fields. Fields are public by default, except in the case of classes and modules. In those two cases, we can safely remove the accessibility modifier.
+                Select Case containingTypeSymbol.TypeKind
+                    Case TypeKind.[Class], TypeKind.[Module]
+                        accessibilityLevel = Accessibility.NotApplicable
+                End Select
+            End If
+            Return accessibilityLevel
+        End Function
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicInitializeMemberFromParameterCodeRefactoringProvider.vb]: I think a better way to do things would be to ahve a helper that answers: "What would the accessibility of this member be if it did *not* have an accessibility modifier".  You could then take that and use that alone (along with teh value of the user option) to determine if ou need to supply the accessibility modifier, or if you can just pass NotApplicable.

**Comment by CyrusNajmabadi** [comment]
Done with pass.  There is a correctness issue with VB.  And i think things can be simplified further :)

**Comment by allisonchou** [comment]
@CyrusNajmabadi I fixed the VB property issue, and took your suggested approach for the abstract helper method. Please let me know if there are any other improvements!

File: src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs [hunk 11]
```diff
@@ -122,18 +124,35 @@ internal abstract partial class AbstractInitializeMemberFromParameterCodeRefacto
             }
         }
 
-        private IFieldSymbol CreateField(
-            IParameterSymbol parameter, ImmutableArray<NamingRule> rules, ImmutableArray<string> parameterNameParts)
+        private async Task<IFieldSymbol> CreateFieldAsync(
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs]: there doesn't appear to be anything async in this method AFAICT :)

File: src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs [hunk 12]
```diff
@@ -122,18 +124,35 @@ internal abstract partial class AbstractInitializeMemberFromParameterCodeRefacto
...
             foreach (var rule in rules)
             {
                 if (rule.SymbolSpecification.AppliesTo(SymbolKind.Field, Accessibility.Private))
                 {
                     var uniqueName = GenerateUniqueName(parameter, parameterNameParts, rule);
 
+                    var accessibilityLevel = Accessibility.Private;
+                    if (requireAccessibilityModifiers.Value == AccessibilityModifiersRequired.Never || requireAccessibilityModifiers.Value == AccessibilityModifiersRequired.OmitIfDefault)
+                    {
+                        var model = await document.GetSemanticModelAsync(cancellationToken).ConfigureAwait(false);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs]: note: i think you're getting the semantic model in order to determinet he containing type.  But you can get that straight from the "IParameterSymbol parameter" symbol.  Just call .ContainingType on that and pass it in.

File: src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs [hunk 13]
```diff
@@ -190,6 +225,8 @@ private static string GenerateUniqueName(IParameterSymbol parameter, ImmutableAr
             throw ExceptionUtilities.Unreachable;
         }
 
+        protected abstract Accessibility DetermineDefaultPropertyAccessibility();
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs]: small nit: can you put all the abstract members at the top of the file together?

File: src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicInitializeMemberFromParameterCodeRefactoringProvider.vb [hunk 14]
```diff
@@ -40,5 +41,27 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.InitializeParameter
...
+                Dim containingTypeSymbol = CType(model.GetDeclaredSymbol(containingTypeNode, cancellationToken), INamedTypeSymbol)
+
+                ' Fields are public by default in VB, except in the case of classes and modules.
+                Select Case containingTypeSymbol.TypeKind
+                    Case TypeKind.[Class], TypeKind.[Module]
+                        accessibilityLevel = Accessibility.[Private]
+                End Select
+            End If
+            Return accessibilityLevel
+        End Function
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicInitializeMemberFromParameterCodeRefactoringProvider.vb]: a simpler way would be to just pass in the INamedTypeSymbol for the containing type from the caller.  then you can just do:

```return If(containingType.TypeKind = ..., Accessibility.Private, Acessibilty.Public)```.

File: src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicInitializeMemberFromParameterCodeRefactoringProvider.vb [hunk 15]
```diff
@@ -40,5 +41,27 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.InitializeParameter
...
+
+        ' Properties are always public by default in VB.
+        Protected Overrides Function DetermineDefaultPropertyAccessibility() As Accessibility
+            Return Accessibility.[Public]
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicInitializeMemberFromParameterCodeRefactoringProvider.vb]: FYI, you don't need to escape keywords after a `<dot>` in VB :)

**Comment by CyrusNajmabadi** [comment]
Done with pass.  Very minor nits/cleanup suggestions.  Looking great!

**Comment by allisonchou** [comment]
@CyrusNajmabadi Thank you, cleaned things up! Let me know if there's anything else.

**Comment by CyrusNajmabadi** [comment]
Nope!  Looks great.  I hope all the feedback made sense and helped for future work!

**Comment by allisonchou** [comment]
Thank you!! I appreciate all your helpful feedback this summer a ton. :) I definitely learned a lot!

**Comment by mavasani** [comment]
retest this please
