### PR TITLE
Report diagnostic on correct node

### LINKED ISSUE #50493: IntelliSense suggestion for "Add explicit cast" puts cast in wrong place when applied to an array index
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/IntelliSense-suggestion-for-Add-explici/1293943)._

---
[severity:It bothers me. A fix would be nice]
I have an array of ints, here I will call it myArray.
I put in an array reference using an Enum value for the index without including a cast, like so: 
`if (myArray[myEnumValue] == 1) { _some code here_ }.`
Naturally, this generates an IntelliSense suggestion that an explicit cast is required for the array index. However, if I tell VS to apply the suggestion, it applies it to the full array reference, rather than just the Enum value in the index.
That is, I get
`if ((int)myArray[myEnumValue] == 1) { _some code here_ }.`
rather than
`if (myArray[(int)myEnumValue] == 1) { _some code here_ }.`
as expected. This leads to the issue still being present, with the same suggestion still there. I can apply the suggestion repeatedly, potentially ending up with
`if ((int)(int)(int)(int)myArray[myEnumValue] == 1) { _some code here_ }.`
or however far I want to carry it. Naturally, this is not a breaking issue, and not one that will come up a lot, but in my style, I find it slightly easier and less error-prone to go ahead and type the simpler code and then go back and let IntelliSense put everything where it goes, so a minor correction like this would still be useful.

---
#### Tom S on 12/22/2020, 07:22 AM: 

<p>On further investigation, it looks like sometimes rather than generating the incorrect cast, it will simply refuse to do anything. Selecting the suggestion will have no effect, and it will stay there. Selecting “Preview changes” will bring up the window with no changes listed. Either way, this still seems to be incorrect behavior.</p>

#### Feedback Bot on 12/22/2020, 05:20 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/5/2021, 09:41 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

### LINKED ISSUE #53536: CS0266 diagnostic has the wrong span for an element accessor
Found while investigating https://github.com/dotnet/roslyn/issues/50493

**Steps to reproduce:**

```cs
public class C {
    public void M(object o) {
        var array = new int[10];

        if (array[o] > 0)
        {
        }
    }
}
```

**Expected:**
CS0266 reported for line 5 for the span of the element access argument `o`.

**Actual:**
CS0266 reported for line 5 for the entire `array[o]` expression.

See the red squiggle in sharplab:
https://sharplab.io/#v2:CYLg1APgAgzABFATHAwnA3gWAFBzw+KAFjgFkAKAewCMArAUwGMAXOSgSgx3x7gDcAhgCc4woQICecALxwAdvQDucAJZzmAbQCMABgC6AbhzdeeFQDM45MZI2U9cAHxwd7E6ay5TcAL7vfOH7YQA

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #53536
Fixes #50493

explicitcast

### CODE REVIEW

**Review by davidwengier — APPROVED** [review]
Thanks @Youssef1313 😀

IDE test change LGTM

File: src/Compilers/CSharp/Test/Emit/CodeGen/IndexAndRangeTests.cs [hunk 1]
```diff
@@ -1634,10 +1634,10 @@ public static void M(int[,] s)
             comp.VerifyDiagnostics(
                 // (12,27): error CS0029: Cannot implicitly convert type 'System.Index' to 'int'
                 //         Console.WriteLine(s[new Index(1, false), ^1]);
-                Diagnostic(ErrorCode.ERR_NoImplicitConv, "s[new Index(1, false), ^1]").WithArguments("System.Index", "int").WithLocation(12, 27),
+                Diagnostic(ErrorCode.ERR_NoImplicitConv, "new Index(1, false)").WithArguments("System.Index", "int").WithLocation(12, 27),
                 // (12,27): error CS0029: Cannot implicitly convert type 'System.Index' to 'int'
                 //         Console.WriteLine(s[new Index(1, false), ^1]);
-                Diagnostic(ErrorCode.ERR_NoImplicitConv, "s[new Index(1, false), ^1]").WithArguments("System.Index", "int").WithLocation(12, 27));
+                Diagnostic(ErrorCode.ERR_NoImplicitConv, "^1").WithArguments("System.Index", "int").WithLocation(12, 27));
```
[the remark this answers is not in the document]
Comment (Youssef1313) [reply src/Compilers/CSharp/Test/Emit/CodeGen/IndexAndRangeTests.cs:1640]: Yep I forgot those. Will update them shortly.

File: src/Compilers/CSharp/Test/Semantic/Semantics/IndexAndRangeTests.cs [hunk 2]
```diff
@@ -695,7 +695,7 @@ public class C {
             comp.VerifyDiagnostics(
                 // (11,17): error CS0656: Missing compiler required member 'System.Runtime.CompilerServices.RuntimeHelpers.GetSubArray'
                 //         var x = arr[0..2];
-                Diagnostic(ErrorCode.ERR_MissingPredefinedMember, "arr[0..2]").WithArguments("System.Runtime.CompilerServices.RuntimeHelpers", "GetSubArray").WithLocation(11, 17));
+                Diagnostic(ErrorCode.ERR_MissingPredefinedMember, "0..2").WithArguments("System.Runtime.CompilerServices.RuntimeHelpers", "GetSubArray").WithLocation(11, 21));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/IndexAndRangeTests.cs:698]: >Diagnostic [](http://example.com/codeflow?start=16&length=10)

It looks like we are lacking test coverage for the following scenarios affected by the change:
- pointer indexing
- array creation
- variable declaration with dimensions on the type

**Comment by AlekseyTs** [comment]
@Youssef1313 It looks like there are legitimate test failures.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 4)

File: src/Compilers/CSharp/Test/Semantic/Semantics/IndexAndRangeTests.cs (hunk 2 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Test/Semantic/Semantics/IndexAndRangeTests.cs:698]: - Will add a test for pointer indexing.

- Array creation is covered in `CS0266ERR_NoImplicitConvCast13:

https://github.com/dotnet/roslyn/blob/67c6bed1581a0d5db35b7e68d6766560a089ea1a/src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs#L9235-L9244

- If you mean `int[o] arr;`, then this will produce `error CS0270: Array size cannot be specified in a variable declaration (try initializing with a 'new' expression)`.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/IndexAndRangeTests.cs:698]: > If you mean int[o] arr;, then this will produce error CS0270: Array size cannot be specified in a variable declaration (try initializing with a 'new' expression).

Do we have an existing test demonstrating this with type mismatch in the illegal sizes?

**Comment by AlekseyTs** [comment]
Done with review pass (commit 6)

File: src/Compilers/CSharp/Test/Semantic/Semantics/IndexAndRangeTests.cs (hunk 2 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Test/Semantic/Semantics/IndexAndRangeTests.cs:698]: @AlekseyTs If you mean something like:

```
    public void M(object o) {
        int[o] x;
    }
```

Then I think there is no test for it. I'll add it once you confirm this is the case you're requesting.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/IndexAndRangeTests.cs:698]: > If you mean something like ...

Yes, something like this. We want a test that hits your changes in BindArrayDimension for a variable declaration

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 8)

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

**Review by RikkiGibson — APPROVED** [review]

**Comment by RikkiGibson** [comment]
Thanks for the contribution @Youssef1313!
