### PR TITLE
Fix emit of param-nullchecking on async methods

### LINKED ISSUE #58796: Param nullchecking emit crash with async method
**Version Used**: f29f93714d222888c232f34fe05165eafafe8ff7

**Steps to Reproduce**:

1. Change ToolsetVersion in eng/Versions.props to `4.2.0-1.22061.4`
2. Change [this method](https://github.com/dotnet/roslyn/blob/7c60002b24f59f88b0dc2fdb350936733afd4ccf/src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs#L144-L158) to the following:
```cs
        /// <summary>
        /// Gets all the diagnostics in the given document filtered by <see cref="DiagnosticIds"/>.
        /// </summary>
        public async Task<ImmutableArray<Diagnostic>> GetDocumentDiagnosticsAsync(Document document!!)
        {
            if (this.Project.Language != document.Project.Language)
            {
                return ImmutableArray<Diagnostic>.Empty;
            }

            var getDiagnosticsTask = State.DiagnosticProvider.GetDocumentDiagnosticsAsync(document, this.CancellationToken);
            return await GetFilteredDiagnosticsAsync(getDiagnosticsTask, this.DiagnosticIds).ConfigureAwait(false);
        }
```
3. Run a build

**Expected Behavior**: Builds successfully.

**Actual Behavior**: Crash during emit:

`error MSB6006: "csc.exe" exited with code -2146232797. [C:\Users\rikki\src\roslyn2\src\Workspaces\Core\Portab
le\Microsoft.CodeAnalysis.Workspaces.csproj]`

I attached a debugger and have a stack trace:

```
Microsoft.CodeAnalysis.CodeGen.LocalSlotManager.DeclareLocal(Microsoft.Cci.ITypeReference type, Microsoft.CodeAnalysis.Symbols.ILocalSymbolInternal symbol, string name, Microsoft.CodeAnalysis.SynthesizedLocalKind kind, Microsoft.CodeAnalysis.CodeGen.LocalDebugId id, System.Reflection.Metadata.LocalVariableAttributes pdbAttributes, Microsoft.CodeAnalysis.LocalSlotConstraints constraints, System.Collections.Immutable.ImmutableArray<bool> dynamicTransformFlags, System.Collections.Immutable.ImmutableArray<string> tupleElementNames, bool isSlotReusable) Line 138	C#
Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.DefineLocal(Microsoft.CodeAnalysis.CSharp.Symbols.LocalSymbol local, Microsoft.CodeAnalysis.SyntaxNode syntaxNode) Line 1417	C#
Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(Microsoft.CodeAnalysis.CSharp.BoundBlock block) Line 638	C#
Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(Microsoft.CodeAnalysis.CSharp.BoundStatement statement) Line 31	C#
Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.BoundStatement> statements) Line 665	C#
Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(Microsoft.CodeAnalysis.CSharp.BoundBlock block) Line 642	C#
Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(Microsoft.CodeAnalysis.CSharp.BoundStatement statement) Line 31	C#
Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.BoundStatement> statements) Line 665	C#
Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(Microsoft.CodeAnalysis.CSharp.BoundBlock block) Line 642	C#
Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(Microsoft.CodeAnalysis.CSharp.BoundStatement statement) Line 31	C#
Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatementList(Microsoft.CodeAnalysis.CSharp.BoundStatementList list) Line 128	C#
Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(Microsoft.CodeAnalysis.CSharp.BoundStatement statement) Line 63	C#
Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.GenerateImpl() Line 280	C#
Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.Generate(out bool hasStackalloc) Line 209	C#
Microsoft.CodeAnalysis.CSharp.MethodCompiler.GenerateMethodBody(Microsoft.CodeAnalysis.CSharp.Emit.PEModuleBuilder moduleBuilder, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol method, int methodOrdinal, Microsoft.CodeAnalysis.CSharp.BoundStatement block, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CodeGen.LambdaDebugInfo> lambdaDebugInfo, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CodeGen.ClosureDebugInfo> closureDebugInfo, Microsoft.CodeAnalysis.CSharp.StateMachineTypeSymbol stateMachineTypeOpt, Microsoft.CodeAnalysis.CodeGen.VariableSlotAllocator variableSlotAllocatorOpt, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, Microsoft.CodeAnalysis.CodeGen.DebugDocumentProvider debugDocumentProvider, Microsoft.CodeAnalysis.CSharp.ImportChain importChainOpt, bool emittingPdb, bool emitTestCoverageData, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CodeGen.SourceSpan> dynamicAnalysisSpans, Microsoft.CodeAnalysis.CSharp.Symbols.SynthesizedEntryPointSymbol.AsyncForwardEntryPoint entryPointOpt) Line 1559	C#
Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol methodSymbol, int methodOrdinal, ref Microsoft.CodeAnalysis.CSharp.Binder.ProcessedFieldInitializers processedInitializers, Microsoft.CodeAnalysis.CSharp.SynthesizedSubmissionFields previousSubmissionFields, Microsoft.CodeAnalysis.CSharp.TypeCompilationState compilationState) Line 1318	C#
Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol containingType) Line 529	C#
Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedTypeAsync.AnonymousMethod__0() Line 419	C#
Roslyn.Utilities.UICultureUtilities.WithCurrentUICulture.AnonymousMethod__0() Line 139	C#
```

It looks like we are trying to add a local that was already added. Must be an issue with param-nullchecking lowering.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #58796
Related to #36024

Spec update: dotnet/csharplang#5642

It seems we neglected to test the feature in combination with regular async methods. We do have some existing coverage for async iterators.

I found it was simplest to insert null checks after the last rewriting pass for both regular and synthesized methods. I found that when I added the checks before running the iterator rewriter they would actually get dropped in some scenarios.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Lowering/StateMachineRewriter/StateMachineRewriter.cs [hunk 1]
```diff
@@ -320,8 +320,7 @@ protected BoundStatement GenerateParameterStorage(LocalSymbol stateMachineVariab
             }
 
             var builtBody = bodyBuilder.ToImmutableAndFree();
-            ImmutableArray<BoundStatement> newBody = LocalRewriter.TryConstructNullCheckedStatementList(method.Parameters, builtBody, F);
-            return newBody.IsDefault ? F.Block(builtBody) : F.Block(ImmutableArray.Create(stateMachineVariable), newBody);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Lowering/StateMachineRewriter/StateMachineRewriter.cs:324]: The ImmutableArray here specifically was the cause of the crash. newBody already contained a block with the stateMachineVariable in it, so adding it again here made us crash in code generation.

File: src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs [hunk 2]
```diff
@@ -1293,21 +1301,17 @@ public override object VisitField(FieldSymbol symbol, TypeCompilationState argum
...
-                                    hasErrors = boundStatementsWithNullCheck.HasErrors() || diagsForCurrentMethod.HasAnyErrors();
-                                    SetGlobalErrorIfTrue(hasErrors);
-                                    if (hasErrors)
-                                    {
-                                        _diagnostics.AddRange(diagsForCurrentMethod);
-                                        return;
-                                    }
+                                    _diagnostics.AddRange(diagsForCurrentMethod);
+                                    return;
                                 }
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:1315]: It seems surprising we're calling `SetGlobalErrorIfTrue()` here and returning early only if there were null checks. What if `diagsForCurrentMethod.HasAnyErrors()` was `true` even without null checks?

File: src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs [hunk 3]
```diff
@@ -1293,21 +1301,17 @@ public override object VisitField(FieldSymbol symbol, TypeCompilationState argum
 
                             var factory = new SyntheticBoundNodeFactory(methodSymbol, syntax, compilationState, diagsForCurrentMethod);
 
-                            // Iterators handled in IteratorRewriter.cs
-                            if (!methodSymbol.IsIterator)
-                            {
-                                var boundStatementsWithNullCheck = LocalRewriter.TryConstructNullCheckedStatementList(methodSymbol.Parameters, boundStatements, factory);
+                            var nullCheckStatements = LocalRewriter.TryConstructNullCheckedStatementList(methodSymbol.Parameters, factory);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:1304]: >TryConstructNullCheckedStatementList [](http://example.com/codeflow?start=68&length=36)

Consider having `TryConstructNullCheckedStatementList()` return `ImmutableArray<BoundStatement>.Empty` rather than `default` if there are no null checks, and execute the code below unconditionally.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs [hunk 4]
```diff
@@ -260,12 +260,7 @@ public override BoundNode VisitLambda(BoundLambda node)
                     _instrumenter = RemoveDynamicAnalysisInjectors(oldInstrumenter);
                 }
 
-                var visited = (BoundLambda)base.VisitLambda(node)!;
-                if (RewriteNullChecking(visited.Body) is BoundBlock newBody)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs:264]: >RewriteNullChecking [](http://example.com/codeflow?start=20&length=19)

Where does is null checking added for lambdas with this change? In `MethodCompiler.CompileSynthesizedMethods()`?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs:264]: Yes.

File: src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:1315]: I think the `if (hasErrors)` block is redundant here.

File: src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenNullCheckedParameterTests.cs [hunk 5]
```diff
@@ -2029,5 +2042,209 @@ .maxstack  2
   IL_0024:  ret
 }");
         }
+
+        [Fact]
+        public void AsyncMethod_1()
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenNullCheckedParameterTests.cs:2047]: consider adding tests for async local function and/or lambda too.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 2) with a test suggestion to consider

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs [hunk 6]
```diff
@@ -330,13 +325,7 @@ public override BoundNode VisitLocalFunctionStatement(BoundLocalFunctionStatemen
...
                 }
 
-                var visited = (BoundLocalFunctionStatement)base.VisitLocalFunctionStatement(node)!;
-
-                if (!localFunction.IsIterator && RewriteNullChecking(visited.Body) is BoundBlock newBody)
-                {
-                    visited = visited.Update(localFunction, newBody, null);
-                }
-                return visited;
+                return (BoundLocalFunctionStatement)base.VisitLocalFunctionStatement(node)!;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs:328]: >(BoundLocalFunctionStatement) [](http://example.com/codeflow?start=23&length=29)

The cast is unnecessary.

File: src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenNullCheckedParameterTests.cs [hunk 7]
```diff
@@ -1399,12 +1398,26 @@ .maxstack  3
...
+    public static void Use()
     {
         IEnumerator<char> e = GetChars(""hello"");
+        Console.Write(1);
+
+        try
+        {
+            GetChars(null!);
+        }
+        catch
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenNullCheckedParameterTests.cs:1417]: >catch [](http://example.com/codeflow?start=8&length=5)

Consider catching `ArgumentNullException` explicitly, here and in the other new tests that catch exceptions.

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenNullCheckedParameterTests.cs (hunk 5 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenNullCheckedParameterTests.cs:2086]: Now have tests for both async lambdas and local functions. (I think we did have the local function test before this comment, but good to have the lambda test.)

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 4)
