### PR TITLE
VB: Check for script context in '#R' directive recommender

### LINKED ISSUE #37911: VB: #R directive is recommended in non-scripting context
**Version Used**: 16.2.1

**Steps to Reproduce**:

1. Open a regular VB file.
2. Type `#`.

**Expected Behavior**: `#R` does not appear in the list, as it's not a scripting context.

**Actual Behavior**: `#R` does appear, leading to a compiler error if it is inserted.

### PR DESCRIPTION
**Pull request by jhinder**
Fixes #37911.

### CODE REVIEW

File: src/EditorFeatures/VisualBasicTest/Recommendations/PreprocessorDirectives/ReferenceDirectiveKeywordRecommenderTests.vb [hunk 1]
```diff
@@ -0,0 +1,11 @@
+﻿' Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
+
+Namespace Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Recommendations.PreprocessorDirectives
+    Public Class ReferenceDirectiveKeywordRecommenderTests
+        <Fact, Trait(Traits.Feature, Traits.Features.KeywordRecommending)>
+        <WorkItem(37911, "https://github.com/dotnet/roslyn/issues/37911")>
+        Public Async Function NotInFileTest() As Task
+            Await VerifyRecommendationsMissingAsync(<File>|</File>, "#R")
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/VisualBasicTest/Recommendations/PreprocessorDirectives/ReferenceDirectiveKeywordRecommenderTests.vb]: can you have a test validating that it does show up when expected?

**Comment by jhinder** [comment]
I've extended the recommendation test helpers to allow `Script="True"` in test source tags in recommendation tests, which causes the source code to parse as script.

@CyrusNajmabadi I've also added the positive test you asked for.

**Comment by ivanbasov** [comment]
Thank you for your help, @jhinder and @cyrusnajmabadi !
