### PR TITLE
Fix bug when caret is at the end of an argument

### LINKED ISSUE #19175: "Add argument name" requires you to be on exactly the argument
1. CTRL+. at $

``` C#
using System;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine(args$);        
    }
}
```

**Expected:** To be offered to "Add argument name"
**Actual:** Not offered to "Add argument name"

Note, for highlighting usage and goto definition purposes that character position is considered part of the argument.

### PR DESCRIPTION
**Pull request by alrz**
Fixes #19175

### CODE REVIEW

File: src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs [hunk 1]
```diff
@@ -34,7 +34,13 @@ protected abstract class Analyzer<TBaseArgumentSyntax, TArgumentSyntax, TArgumen
                     return;
                 }
 
-                var argument = root.FindNode(context.Span).FirstAncestorOrSelf<TBaseArgumentSyntax>() as TArgumentSyntax;
+                var token = root.FindToken(context.Span.Start);
+                if (token.ValueText == ")" || token.ValueText == ",")
```
Comment (sharwell) [inline src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs]: 💭 Personally I would prefer to use the token's kind instead of text (which may require an abstract method implemented by the derived types), but if @CyrusNajmabadi doesn't have a problem with the current approach then I won't block on this.

File: src/EditorFeatures/VisualBasicTest/CodeActions/UseNamedArguments/UseNamedArgumentsTests.vb [hunk 2]
```diff
@@ -260,5 +260,59 @@ Class C
...
+"Class C
+    Sub M(arg1 As Integer, optional arg2 As Integer=1, optional arg3 as Integer=1)
+        M(1,[||],3)
+    End Sub
+End Class")
+        End Function
+
+        <WorkItem(19175, "https://github.com/dotnet/roslyn/issues/19175")>
+        <Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseNamedArguments)>
+        Public Async Function TestCaretPositionAtTheEnd4() As Task
```
Comment (sharwell) [inline src/EditorFeatures/VisualBasicTest/CodeActions/UseNamedArguments/UseNamedArgumentsTests.vb]: 💡 Maybe file a issue for the future showing how this refactoring operation could support missing arguments by omitting them during the conversion to named arguments. The output for this example would be:

```
M(arg1:=1, arg3:=3)
```

Comment (alrz) [inline src/EditorFeatures/VisualBasicTest/CodeActions/UseNamedArguments/UseNamedArgumentsTests.vb]: That was in the initial implementation (#15687) but superseded by Cyrus changes, supposedly that's not the desirable behavior. IMO it makes sense because the refactoring says "add named arguments" and it merely would do that, otherwise we're changing the code more than it's expected.

Comment (alrz) [inline src/EditorFeatures/VisualBasicTest/CodeActions/UseNamedArguments/UseNamedArgumentsTests.vb]: See `TestOmittedArguments2` for an example of a use case that we do offer the fix in presence of omitted args.

Comment (sharwell) [inline src/EditorFeatures/VisualBasicTest/CodeActions/UseNamedArguments/UseNamedArgumentsTests.vb]: The changes by Cyrus appear to have been an oversight. I went through every comment and commit message of the issue and both PRs, and it appears that the change slipped through as opposed to being deliberate. I believe it would be helpful to include the refactoring operation for the following basic reason: if the user believes that the use of a named argument will improve readability for the argument `1`, then this is the minimal change required to provide that readability improvement. Also, it will not be clear to users why this feature works for some provided arguments, but not for others.

File: src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs (hunk 1 above)
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs]: this should definitely be checking if it is ```.Kind() == SyntaxKind.CloseParen``` and SyntaxKind.Comma.

Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs]: It should also only move back if the caret is literally at the .Span.Start of the token.

Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs]: Because this is in abstrcat code, you'll need to provide customized logic for VB/C#  through the derived types.

File: src/EditorFeatures/VisualBasicTest/CodeActions/UseNamedArguments/UseNamedArgumentsTests.vb (hunk 2 above)
Comment (CyrusNajmabadi) [inline src/EditorFeatures/VisualBasicTest/CodeActions/UseNamedArguments/UseNamedArgumentsTests.vb]: My concern with such an approach would be that it could subtly change overload resolution if you now removed an argument.  if there was a two-arg method, with matching names, you'd now be calling that, instead of the original member.

File: src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs [hunk 3]
```diff
@@ -34,7 +34,17 @@ protected abstract class Analyzer<TBaseArgumentSyntax, TArgumentSyntax, TArgumen
                     return;
                 }
 
-                var argument = root.FindNode(context.Span).FirstAncestorOrSelf<TBaseArgumentSyntax>() as TArgumentSyntax;
+                var token = root.FindToken(context.Span.Start);
+                if (IsCloseParenOrComma(token))
+                {
+                    if (token.Span.Start != context.Span.Start ||
+                        IsCloseParenOrComma(token = token.GetPreviousToken()))
```
Comment (alrz) [inline src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs]: This certainly smells.

Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs]: please don't write it this way :)

Comment (alrz) [inline src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs]: You mean the inline assignment or duplicated check for comma? I could inline the whole FirstAncestorOrSelf and bail when we reach an argument list instead. thoughts?

Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs]: the inline assignment.   I would simply start with:

```c#
if (token.Span.Start == context.Span.Start &&
    IsCloseParenOrComma(token) &&
    token.GetPreviousToken().Span.End == context.Span.Start)
{
     token = token.GetPreviousToken();
}

// rest of your logic.
```

Comment (alrz) [inline src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs]: An opportunity to use `is var` :D but I'll take your suggestion.

File: src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs [hunk 4]
```diff
@@ -35,10 +35,12 @@ protected abstract class Analyzer<TBaseArgumentSyntax, TArgumentSyntax, TArgumen
...
                 var token = root.FindToken(context.Span.Start);
-                if (IsCloseParenOrComma(token))
+                if (token.Span.Start == context.Span.Start &&
+                    IsCloseParenOrComma(token))
                 {
-                    if (token.Span.Start != context.Span.Start ||
-                        IsCloseParenOrComma(token = token.GetPreviousToken()))
+                    token = token.GetPreviousToken();
+                    if (token.Span.End != context.Span.Start || 
+                        IsCloseParenOrComma(token))
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs]: i don't think you need this second IsCloseParenOrComma

Comment (alrz) [inline src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs]: `TestCaretPositionAtTheEnd5` requires it. though it's VB only.

Comment (sharwell) [inline src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs]: @CyrusNajmabadi It's a sneaky edge case. The missing argument led to the previous token being `,`, which is not part of the argument *list* but not the argument itself. This caused the code fix to search upwards and find the outer invocation and try to add the named argument there. It would be a rare but really weird experience when it occurred.

Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs]: I think the walk up should stop immediately at the first parameterlist.  that would make more sense to me.

Comment (alrz) [inline src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs]: yeah I did suggest that earlier.. so I need to fork FirstAncestorOrSelf method somewhere else since there is no helper for that case, I guess.

Comment (sharwell) [inline src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs]: @alrz I think the following would work:

```
FirstAncestorOrSelf<SyntaxNode>(node => node.IsKind(SyntaxKind.A, SyntaxKind.B))
```

Comment (alrz) [inline src/Features/Core/Portable/CodeRefactorings/UseNamedArguments/AbstractUseNamedArgumentsCodeRefactoringProvider.cs]: @sharwell it "filters" the result, it doesn't cause the walk up to stop.

File: src/Workspaces/Core/Portable/Shared/Extensions/SyntaxNodeExtensions.cs [hunk 5]
```diff
@@ -772,5 +746,29 @@ private static SyntaxToken FindSkippedTokenBackward(SyntaxTriviaList triviaList,
         {
             return node.WithLeadingTrivia(leadingTrivia).WithTrailingTrivia(trailingTrivia);
         }
+
+        private static SyntaxNode GetParent(this SyntaxNode node)
+        {
+            return (node as IStructuredTriviaSyntax)?.ParentTrivia.Token.Parent ?? node.Parent;
```
Comment (alrz) [inline src/Workspaces/Core/Portable/Shared/Extensions/SyntaxNodeExtensions.cs]: I think this is a behavioral change. should use a pattern instead.

File: src/Workspaces/Core/Portable/Shared/Extensions/SyntaxNodeExtensions.cs [hunk 6]
```diff
@@ -751,5 +751,24 @@ private static SyntaxNode GetParent(this SyntaxNode node)
         {
             return (node as IStructuredTriviaSyntax)?.ParentTrivia.Token.Parent ?? node.Parent;
         }
+
+        public static TNode FirstAncestorOrSelfUntil<TNode>(this SyntaxNode node, Func<SyntaxNode, bool> predicate)
+            where TNode : SyntaxNode
+        {
+            for (var current = node; current != null; current = current.GetParent())
+            {
+                if (predicate(current))
```
Comment (sharwell) [inline src/Workspaces/Core/Portable/Shared/Extensions/SyntaxNodeExtensions.cs]: ❗️ This needs to come after the other check

**Comment by alrz** [comment]
>I would prefer e18581a be a separate pull request.

The method I added depends on `GetParent` method added in the clean up.

**Comment by CyrusNajmabadi** [comment]
Tagging @MattGertz

Customer scenario

Our 'add named argument' feature doesn't work if the user is at the end of an argument.  This can be annoying and confusing. 

Bugs this fixes:

Fixes #19175

Workarounds, if any

None.

Risk

Low.

Performance impact

Low.

Is this a regression from a previous update?

No.

Root cause analysis:

We didn't validate the feature at all possible positions of the caret.  

How was the bug found?

Bug report.

**Comment by MattGertz** [comment]
Approved pending sharwell signoff.  Thank you!

**Comment by sharwell** [comment]
Thanks @alrz for the PR, and @CyrusNajmabadi for getting the approval through!
