### PR TITLE
Don't optimize large tuple literal switch inputs

### LINKED ISSUE #47878: Roslyn produces wrong code for huge switch expression
**Version Used**: 
.NET Core SDK 3.1.302
.NET 5 RC1

**Steps to Reproduce**:

Use the following [source code](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMBGAsAKBQZgAJ1CBhQgb10JuKJQwDZCBLAOxkIFkAGACnacAHgEpqtKjlrTCANwgJCwDIQC8hAGYQANlDgBucTLkKlaNZp17DU4ycXAi6rboNGZ8hwBYLL6++lPJQBWXys3W2Mg4GZncJs7eyUAdgsYBABXCMTogA40zOy7ANoUVL4hABolDGrgNDr8Oq864LrGOuS63JFCKAB3FhgAYwALEppJROk+WstXar84RfCVhfm9Nc3CdKzq3bhe1QA+QlqJmQB9NVOAWnPImQBfBNon93d0cym7BgBOPi8WYiESvGjvHBPIA===):

```csharp
using System;
public class C {
    public static int M0(int x)
    {
        var b1 = false;
        var b2 = false;
        var b3 = false;
        var b4 = false;
        var b5 = false;
        var b6 = false;
        var b7 = true; // but, if you remove these two variables b7, b8
        var b8 = true; // then everything is ok
        
        return (x, b1, b2, b3, b4, b5, b6, b7, b8) switch
        {
            (1, false, false, false, false, false, false, true, true) => 1,
            _ => -1,
        };
    }
    
    public static void Main() {
        Console.WriteLine(M0(1));
    }
}
```

It will produce:

```csharp
using System;
public class C
{
    public static int M0(int x)
    {
        bool flag = false;
        bool flag2 = false;
        bool flag3 = false;
        bool flag4 = false;
        bool flag5 = false;
        bool flag6 = false;
        bool flag7 = true;
        bool flag8 = true;
        bool flag9 = default(bool);   // these vars are not present in source code
        bool flag10 = default(bool);  // they are used instead of the "real" ones
        if (x == 1 && !flag && !flag2 && !flag3 && !flag4 && !flag5 && !flag6 && flag9 && flag10)
        {
            return 1;
        }
        return -1;
    }

    public static void Main()
    {
        Console.WriteLine(M0(1));
    }
}

```

**Expected Behavior**:
Provided sample should print "1".

**Actual Behavior**:
Provided sample will print "-1" (wrong code is generated).

### PR DESCRIPTION
**Pull request by RikkiGibson**
Fixes #47878

This is a simpler, less optimal fix than #47893. We can try to figure out how to fix the optimization, but I wanted to submit this as a candidate fix for 16.8 in case the optimization is hard to get right for large tuples.

### CODE REVIEW

**Review by 333fred — APPROVED** [review]

File: src/Compilers/CSharp/Test/Semantic/Semantics/SwitchTests.cs [hunk 1]
```diff
@@ -2949,6 +2949,482 @@ public static void Main()
...
+        {
+            var text = @"
+using System;
+public class C
+{
+    public static void Main()
+    {
+        int x1 = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10) switch
+        {
+            (1, 2, 3, 4, 5, 6, 7, 8, 9, 10) => 1,
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/SwitchTests.cs:2963]: Can we add a negative case here, basically a literal that won't match. Just for completeness.

**Review by jaredpar — APPROVED** [review]

File: src/Compilers/CSharp/Test/Semantic/Semantics/SwitchTests.cs [hunk 2]
```diff
@@ -2949,6 +2949,482 @@ public static void Main()
...
+  IL_017c:  stloc.0
+  IL_017d:  ldloc.0
+  IL_017e:  call       ""void System.Console.WriteLine(int)""
+  IL_0183:  ret
+}
+");
+        }
+
+        [Fact, WorkItem(47878, "https://github.com/dotnet/roslyn/issues/47878")]
+        public void VerifyIL_8ElementsTuple_SideEffects_DefaultLabel()
```
Comment (chsienki) [inline src/Compilers/CSharp/Test/Semantic/Semantics/SwitchTests.cs:3342]: Nit: doesn't actually verify IL

File: src/Compilers/CSharp/Test/Semantic/Semantics/SwitchTests.cs [hunk 3]
```diff
@@ -2949,6 +2949,482 @@ public static void Main()
...
+        public SwitchExpressionException(object unmatchedValue) => UnmatchedValue = unmatchedValue;
+        public object UnmatchedValue { get; }
+    }
+}
+";
+            CompileAndVerify(text, expectedOutput: "12345678💥");
+        }
+
+        [Fact, WorkItem(47878, "https://github.com/dotnet/roslyn/issues/47878")]
+        public void VerifyIL_9ElementsTuple_SideEffects_DefaultLabel()
```
Comment (chsienki) [inline src/Compilers/CSharp/Test/Semantic/Semantics/SwitchTests.cs:3386]: Nit: VerifyIL

**Review by chsienki — APPROVED** [review]
LGTM minus a couple of test naming nits

**Comment by RikkiGibson** [comment]
It looks like the integration queue is not running. Will force merge.
