### PR TITLE
Track nullability of instance members in lambdas and local functions

### LINKED ISSUE #31620: Field nullability incorrect in lambda
The following should compile without warnings:
```C#
#nullable enable
class Program
{
    private object? _field;
    private static void Execute(System.Func<object> f)
    {
    }
    private void F()
    {
        Execute(() =>
        {
            _field = new object();
            return _field; // warning
        });
    }
}
```
```
(13,20): warning CS8603: Possible null reference return.
```
cc @pilchie

### PR DESCRIPTION
**Pull request by cston**
Fixes #31620.

### CODE REVIEW

**Comment by cston** [comment]
@dotnet/roslyn-compiler please review.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 1]
```diff
@@ -49738,22 +49738,128 @@ void M()
...
+    private object _g = null!;
+    private void F()
+    {
+        object f()
+        {
+            _f = new object();
+            return _f;
+            object g(bool b)
+            {
+                    if (b)
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >if (b) [](start = 20, length = 6)

nit: indent

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 2]
```diff
@@ -453,6 +464,18 @@ protected override int MakeSlot(BoundExpression node)
                     break;
             }
             return base.MakeSlot(node);
+
+            bool isTopLevelMethod(MethodSymbol method)
+            {
+                switch (method.MethodKind)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >switch (method.MethodKind) [](start = 16, length = 26)

Consider checking if container is a named type instead. This is how binder does that. Also, this approach will be more robust to future changes in the language. If new flavor of non-top level method will be added, etc.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 3]
```diff
@@ -411,6 +411,17 @@ protected override int MakeSlot(BoundExpression node)
         {
             switch (node.Kind)
             {
+                case BoundKind.ThisReference:
+                case BoundKind.BaseReference:
+                    {
+                        var method = _member as MethodSymbol;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >_member [](start = 37, length = 7)

The name of this field implies it is a member, i.e. a top level method when it is a method. Is this not the case?

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 2).

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 3 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: It is not necessarily a type member. Renamed.

---
In reply to: [241169548](https://github.com/dotnet/roslyn/pull/31703#discussion_r241169548) [](ancestors = 241169548)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 4]
```diff
@@ -49738,22 +49738,136 @@ void M()
...
+            n = base.F.Length;
+        }
+    }
+}";
+            var comp = CreateCompilation(source, options: WithNonNullTypesTrue());
+            comp.VerifyDiagnostics(
+                // (12,21): warning CS8602: Possible dereference of a null reference.
+                //             int n = this.F.Length; // 1
+                Diagnostic(ErrorCode.WRN_NullReferenceReceiver, "this.F").WithLocation(12, 21),
+                // (18,21): warning CS8602: Possible dereference of a null reference.
```
[the remark this answers is not in the document]
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Lambdas and local functions do not currently affect the flow state in the enclosing method. But in this case, the local functions are not invoked so I believe the null state should not change in the caller.

---
In reply to: [241173462](https://github.com/dotnet/roslyn/pull/31703#discussion_r241173462) [](ancestors = 241173462)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 5]
```diff
@@ -65178,5 +65292,97 @@ static void F3(int? z, int? w)
...
+
+        [Fact]
+        public void IsDeclarationPattern_01()
+        {
+            var source =
+@"class Program
+{
+    static void F1(object x1)
+    {
+        if (x1 is string y1) x1.ToString();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >y1 [](start = 25, length = 2)

Consider also observing nullability of ```y1```. Similarly in other added scenarios.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 6]
```diff
@@ -65178,5 +65292,97 @@ static void F3(int? z, int? w)
...
+        where U : class
+    {
+        if (t1 is U u1) t1.ToString();
+        t1.ToString();
+    }
+    static void F2<T, U>(T t2)
+        where T : class?
+        where U : class
+    {
+        if (t2 is string u2) t2.ToString();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >string [](start = 18, length = 6)

Was this supposed to be ```U``` (below as well)?

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 7]
```diff
@@ -65178,5 +65292,97 @@ static void F3(int? z, int? w)
...
+    static void F3<T, U>(T t3)
+        where T : class
+        where U : class
+    {
+        t3 = null; // 2
+        if (t3 is string u3) t3.ToString();
+        t3.ToString(); // 3
+    }
+    static void F4<T, U>(T t4)
+        where T : class?
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >class? [](start = 18, length = 6)

Consider also testing scenarios without any constraints

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 4)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 8]
```diff
@@ -65178,5 +65292,162 @@ static void F3(int? z, int? w)
...
+        {
+            var source =
+@"class Program
+{
+    static void F1(object x1)
+    {
+        if (x1 is string y1)
+        {
+            x1.ToString();
+            y1.ToString();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >y1 [](start = 12, length = 2)

```y1``` is also in scope in the ```else``` and outside the ```if```. Are we testing behavior there?

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 9]
```diff
@@ -65178,5 +65292,162 @@ static void F3(int? z, int? w)
...
+        }
+        x1.ToString();
+    }
+    static void F2(object? x2)
+    {
+        if (x2 is string y2)
+        {
+            x2.ToString();
+            y2.ToString();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >y2 [](start = 12, length = 2)

Is [https://github.com/dotnet/roslyn/issues/30952](https://github.com/dotnet/roslyn/issues/30952) got fixed, or are we not getting any warnings here because the flow state is oblivious? Consider adding  ```y2?.ToString();``` above this line (and other similar lines) to verify that we will get a diagnostics about an unnecessary null check. Also, all changes related to Declaration Pattern are not related to stated subject of this PR, consider separating them into another PR in order to avoid unnecessary friction with this PR.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 10]
```diff
@@ -3373,7 +3391,8 @@ private bool HasTopLevelNullabilityConversion(TypeSymbolWithAnnotations source,
                             checkConversion: false,
                             fromExplicitCast: false,
                             useLegacyWarnings,
-                            assignmentKind);
+                            assignmentKind,
+                            target);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >target [](start = 28, length = 6)

It is hard to tell what scenario motivated this change. Do we have a unit-test that makes this change observable?

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 7)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 10 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Reverted.

---
In reply to: [241487312](https://github.com/dotnet/roslyn/pull/31703#discussion_r241487312) [](ancestors = 241487312)

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs [hunk 11]
```diff
@@ -454,7 +454,7 @@ protected ParameterSymbol MethodThisParameter
         /// <returns>true if the out parameters of the method should be analyzed</returns>
         protected bool ShouldAnalyzeOutParameters(out Location location)
         {
-            var method = _member as MethodSymbol;
+            var method = _symbol as MethodSymbol;
```
[the remark this answers is not in the document]
Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs]: There are only three cases where we use `as MethodSymbol`, here and in the two properties above. (There are several cases in `NullableWalker` where we unconditionally cast to `MethodSymbol` but `NullableWalker` ensures the symbol is a method in the constructor.)

Given that the uses of `as` are limited to these few similar members, I'll leave as is.

---
In reply to: [241496393](https://github.com/dotnet/roslyn/pull/31703#discussion_r241496393) [](ancestors = 241496393)

File: src/Compilers/CSharp/Test/Semantic/FlowAnalysis/FlowDiagnosticTests.cs [hunk 12]
```diff
@@ -2550,5 +2550,57 @@ void M()
                 //         r = (y+1)..(y=0);
                 Diagnostic(ErrorCode.ERR_UseDefViolation, "y").WithArguments("y").WithLocation(9, 14));
         }
+
+        [Fact]
+        public void FieldAssignedInLambdaOnly()
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/FlowAnalysis/FlowDiagnosticTests.cs]: Was there any actual behavioral change here, or this just documenting existing behavior?

Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/FlowAnalysis/FlowDiagnosticTests.cs]: Just testing existing behavior to avoid regressions.

---
In reply to: [241560302](https://github.com/dotnet/roslyn/pull/31703#discussion_r241560302) [](ancestors = 241560302)
