### PR TITLE
Fix performance regression in FixAll code path

### LINKED ISSUE #49698: Solution-wide code fixes take around two minutes to collect no matter which fix it is
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Solution-wide-code-fixes-take-around-two/1272947)._

---
[severity:It bothers me. A fix would be nice]
Most solution-wide code fixes take a couple of minutes to gather when you click "Fix all occurrences in... Solution." It seems like it takes the same amount of time no matter what the code fix is. It's unpleasantly long.

Two or three *seconds* would fit my expectations better since all the occurrences have been collected already and are showing in the Error List window.

If I select "Fix all occurrences in... Document," my stopwatch says it takes 20 seconds to find the one occurrence in a 170-line file.

---
#### jnm2 on 11/30/2020, 03:02 PM: 

<p>My “two minutes” is actually 1m11s when I use a stopwatch. “Fix all in document” and “…project” both take 20 seconds on my stopwatch in a 170-line file.</p>

#### Feedback Bot on 11/30/2020, 06:58 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 12/1/2020, 00:04 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by mavasani**
Recent move of analyzer diagnostic computation to OOP leads to running all analyzers when computing diagnostics to fix as part of a FixAll operation. This change ensures that we only run the required analyzer when computing diagnostics.

Fixes #49698. Verified that added test fails before the product change.

### CODE REVIEW

**Comment by mavasani** [comment]
Retargeting to master after talking with Vatsalya.

**Review by genlu — APPROVED** [review]
:shipit:

File: src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/DiagnosticComputer.cs [hunk 1]
```diff
@@ -75,6 +75,12 @@ internal class DiagnosticComputer
                 return SerializableDiagnosticAnalysisResults.Empty;
             }
 
+            if (_document == null && analyzers.Length < compilationWithAnalyzers.Analyzers.Length)
+            {
+                // PERF: Generate a new CompilationWithAnalyzers with trimmed analyzers for non-document analysis case.
+                compilationWithAnalyzers = compilationWithAnalyzers.Compilation.WithAnalyzers(analyzers, compilationWithAnalyzers.AnalysisOptions);
+            }
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/DiagnosticComputer.cs:82]: couldn't we always just do this, and then have .WithAnalyzers smartly no-op if passing in the same analyzers it poitns at?

Comment (mavasani) [reply src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/DiagnosticComputer.cs:82]: That would need a compiler change and possibly a new compiler public API `WithAnalyzer(analyzers)` that does not take options. Also note that for open file analysis we explicitly want to avoid this fork as we want to share the same `CompilationWithAnalyzers` instance across diagnostic computation calls.
