### PR TITLE
Fix AD0001 for IDE0076

### LINKED ISSUE #45465: AD0001 in CSharpRemoveUnnecessarySuppressionsDiagnosticAnalyzer
> Starting with Visual Studio 2019 version 16.7 Preview 2, a new analyzer ([dotnet/roslyn#44287](https://github.com/dotnet/roslyn/pull/44287)) will report cases where the target of a global suppression cannot be found. The first thing I would try is opening the solution in this version and looking for reports of IDE0076 in GlobalSuppressions.cs.

That helps. I can see 13 warnings raised by `IDE0076` analyzer when I opened the solution in VS 2019 Int Preview (16.7 Preview 4). I found around 35 additional errors from `AD0001` analyzer. please see attachment for errors with stack trace. Looks like an issue in `IDE0076 and IDE0077` analyzers.
[AD0001 errors.txt](https://github.com/dotnet/roslyn-analyzers/files/4833849/AD0001.errors.txt)

_Originally posted by @kartheekp-ms in https://github.com/dotnet/roslyn-analyzers/issues/3587#issuecomment-649823987_

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #45465
Ensure we normalize the target scope passed to target symbol resolver. It doesn't handle the recently added 'namespaceanddescendants' scope in legacy target string format and expects it to be normalized to 'namespace' scope.

### CODE REVIEW

**Comment by mavasani** [comment]
@jinujoseph @vatsalyaagrawal Does this need approval?

File: src/Analyzers/CSharp/Tests/RemoveUnnecessarySuppressions/RemoveUnnecessarySuppressionsTests.cs [hunk 1]
```diff
@@ -182,5 +183,23 @@ class C
 }}";
             await VerifyCS.VerifyCodeFixAsync(input, input);
         }
+
+        [Fact, WorkItem(45465, "https://github.com/dotnet/roslyn/issues/45465")]
+        public async Task LegacyModeGlobalSuppressionWithNamespaceAndDescendantsScope()
+        {
+            var target = "N:N.InvalidChild";
+            var input = $@"
+[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage(""Category"", ""Id: Title"", Scope = ""namespaceanddescendants"", Target = {{|#0:""{target}""|}})]
```
Comment (sharwell) [inline src/Analyzers/CSharp/Tests/RemoveUnnecessarySuppressions/RemoveUnnecessarySuppressionsTests.cs:192]: ❔ Do we have any tests with invalid `Scope`?

Comment (mavasani) [reply src/Analyzers/CSharp/Tests/RemoveUnnecessarySuppressions/RemoveUnnecessarySuppressionsTests.cs:192]: Yep - https://github.com/dotnet/roslyn/blob/be56bf44b7bcd2462c123aca88282791b4e5bca0/src/Analyzers/CSharp/Tests/RemoveUnnecessarySuppressions/RemoveUnnecessaryAttributeSuppressionsTests.cs#L81

**Comment by mavasani** [comment]
>  Does this need M2/shiproom approval?

Confirmed with @jinujoseph offline that 16.7 is now in QB mode, so rebased and retargeted the PR to master.
