### PR TITLE
Reject ref as an invalid modifier for accessors

### LINKED ISSUE #23833: Property ref get crash
**Version Used**: 
Microsoft Visual Studio 2017, Version 15.5.2
C# 7.2
**Steps to Reproduce**:

1. Write `ref get;` in any property

**Expected Behavior**:
It was just mistake, I just wanted to know can I make property getter as ref return.
**Actual Behavior**:
Visual studio just get crashed.

### PR DESCRIPTION
**Pull request by OmarTawfik**
### Customer scenario

User typing `ref` before an accessor (like `add`, `remove`, `set`, and `get`), will cause the C# compiler to OOM. VS will hang until it eventually runs out of memory.

```csharp
public int Prop
{
    ref get {
```

### Bugs this fixes

Fixes #23833

### Workarounds, if any

None.

### Risk

Minimal. It is rejecting a certain keyword in the parser.

### Performance impact

Minimal.

### Is this a regression from a previous update?

Yes. This bug shipped with ref structs.

### Root cause analysis

With the introduction of `ref struct`s, `ref` was considered a valid modifier, but accessor modifiers were not adjusted as well.

### How was the bug found?

Customer report.

### Test documentation updated?

Yes.

### CODE REVIEW

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-compiler for review.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 1]
```diff
@@ -3185,6 +3185,12 @@ private bool IsPossibleAccessorModifier()
             // to the user that this is not allowed.
             if (IsPossibleModifier())
             {
+                if (this.CurrentToken.Kind == SyntaxKind.RefKeyword)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: >if (this.CurrentToken.Kind == SyntaxKind.RefKeyword) [](start = 16, length = 52)

Perhaps rather than checking the token we should call ```private static DeclarationModifiers GetModifier(SyntaxToken token)``` instead of ```IsPossibleModifier``` and compare its return against ```DeclarationModifiers.Ref```?

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 2]
```diff
@@ -3185,6 +3185,12 @@ private bool IsPossibleAccessorModifier()
...
+                {
+                    // Although a legal modifier, it is never parsed unless before a struct definition
+                    return false;
+                }
+
                 var peekIndex = 1;
                 while (IsPossibleModifier(this.PeekToken(peekIndex)))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: >IsPossibleModifier(this.PeekToken(peekIndex))) [](start = 23, length = 46)

Should we have a special handling for a ref modifier here?

File: src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs [hunk 3]
```diff
@@ -6333,5 +6333,129 @@ class C<T> : where T : X
...
+class Program
+{
+    public int P
+    {
+        ref get => throw null;
+    }
+}";
+
+            CreateStandardCompilation(code).VerifyDiagnostics(
+                // (5,6): error CS1513: } expected
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs]: >// (5,6): error CS1513: } expected [](start = 16, length = 34)

Perhaps the experience would be better if we parse ```ref``` as a modifier, but report an "invalid modifier" error for it and ignore it during semantic analysis.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 2)

File: src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs (hunk 3 above)
Comment (VSadov) [reply src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs]: I also wonder if error recovery would be better if we just accept `ref` in parser for this case and give an error in binding.

---
In reply to: [158535495](https://github.com/dotnet/roslyn/pull/23905#discussion_r158535495) [](ancestors = 158535495)

Comment (OmarTawfik) [reply src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs]: I tried that yesterday. The main problem with this approach is that if `ref` is parsed freely as a modifier (without specifically checking if there is a `struct` keyword after it), it will wrongly parse `ref type identifier` wrongly as a by-val variable/field declaration, with `ref` being a modifier of that declaration.
The parser can be modified to accept `ref` in certain situations that we know for sure, but I believe this is not a common enough position to do so. Please let me know if you see otherwise.

---
In reply to: [158571025](https://github.com/dotnet/roslyn/pull/23905#discussion_r158571025) [](ancestors = 158571025,158535495)

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs (hunk 2 above)
Comment (OmarTawfik) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: I don't think so. We will eat it here, and later produce error messages. I'll add some test cases for that.

---
In reply to: [158534670](https://github.com/dotnet/roslyn/pull/23905#discussion_r158534670) [](ancestors = 158534670)

**Comment by OmarTawfik** [comment]
@AlekseyTs @VSadov comments addressed.

File: src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs (hunk 3 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs]: I meant that we would still parse accessors as accessors even when a ```ref``` modifier is present. We would still report an error, probably a new, very specific error saying that a ```ref``` modifier or keyword cannot be used here.

---
In reply to: [158574706](https://github.com/dotnet/roslyn/pull/23905#discussion_r158574706) [](ancestors = 158574706,158571025,158535495)

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 3)

File: docs/contributing/Compiler Test Plan.md [hunk 4]
```diff
@@ -30,7 +30,8 @@ This document provides guidance for thinking about language interactions and tes
 - Performance and stress testing
  
 # Type and members
-- Access modifiers (public, protected, internal, protected internal, private protected, private), static modifier
+- Access modifiers (public, protected, internal, protected internal, private protected, private), static, ref
+    - If adding a new modifier, check modifiers for accessors as well.
```
Comment (jaredpar) [inline docs/contributing/Compiler Test Plan.md]: Unclear what this means at a casual reading.

Comment (OmarTawfik) [reply docs/contributing/Compiler Test Plan.md]: Will modify.

---
In reply to: [159701433](https://github.com/dotnet/roslyn/pull/23905#discussion_r159701433) [](ancestors = 159701433)

**Comment by OmarTawfik** [comment]
@AlekseyTs @jaredpar comments addressed.

**Comment by MeiChin-Tsai** [comment]
looked good to me.

**Comment by ashegoulding** [comment]
Can't believe this bug isn't treated critical. This literally means that I could kill my IDE by typing random things and all the unsaved lines are gone.

**Comment by ashegoulding** [comment]
Oh, look, some guy next to me left with his IDE opened.
It would be a shame if
someone
type
ref get
on
his
code

**Comment by CyrusNajmabadi** [comment]
@ashegoulding 

> Can't believe this bug isn't treated critical. This literally means that I could kill my IDE by typing random things and all the unsaved lines are gone. Yes, that's the exact thing I did, btw.

This was merged into 15.6 back in january :)

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 5]
```diff
@@ -1157,18 +1157,8 @@ internal static DeclarationModifiers GetModifier(SyntaxKind kind, SyntaxKind con
                     return DeclarationModifiers.None;
             }
         }
-
-        private bool IsPossibleModifier()
-        {
-            return IsPossibleModifier(this.CurrentToken);
-        }
-
-        private static bool IsPossibleModifier(SyntaxToken token)
```
Comment (alrz) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: @OmarTawfik Was there a particular reason to remove this helper? If not, may I add it in my PR and update usages?

Comment (OmarTawfik) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: @alrz not sure which PR you're working on, but if it improves code (you need the same logic in other places) and you can update usages, I don't see a reason why not :)

Comment (alrz) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: thanks. (updated the PR at https://github.com/dotnet/roslyn/pull/23533)
