### PR TITLE
IDE0054: Fix compound assignment increment in expression context

### LINKED ISSUE #53969: Intellisense compoud assignment suggestion incorrect
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Intellisense-compoud-assignment-suggesti/1444349)._

---
[severity:Other]
For this code Intellisense suggest to use compound assignment, but it changes the behavior of the code.
Original code:

```
            bool alwaysTrue = true;
            int pkOrder = 0;
            int? current = null;
            for (int i = 0; i < 10; i++)
            {
                current = alwaysTrue == true ? pkOrder = pkOrder + 1 : null;
                Console.WriteLine(current);
            }
```

Results the following output:
1
2
3
4
5
6
7
8
9
10

Intellisense suggestion for this:

```
            bool alwaysTrue = true;
            int pkOrder = 0;
            int? current = null;
            for (int i = 0; i < 10; i++)
            {
                current = alwaysTrue == true ? pkOrder++ : null;
                Console.WriteLine(current);
            }
```

Results:

0
1
2
3
4
5
6
7
8
9

---
#### Feedback Bot on 6/8/2021, 06:22 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by MaStr11**
Fix #53969

### CODE REVIEW

File: src/Analyzers/CSharp/Tests/UseCompoundAssignment/UseCompoundAssignmentTests.cs [hunk 1]
```diff
@@ -1091,6 +1091,27 @@ void M()
...
+    void M(int i)
+    {
+        M(i [||]= i + 1);
+    }
+}",
+@"public class C
+{
+    void M(int i)
+    {
+        M(++i);
```
Comment (MaStr11) [inline src/Analyzers/CSharp/Tests/UseCompoundAssignment/UseCompoundAssignmentTests.cs:1113]: Without a call to `WithoutTrailingTrivia()`, the fix produces `M(++i );`

File: src/Analyzers/Core/CodeFixes/UseCompoundAssignment/AbstractUseCompoundAssignmentCodeFixProvider.cs [hunk 2]
```diff
@@ -81,12 +81,12 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
                         if (diagnostic.Properties.ContainsKey(UseCompoundAssignmentUtilities.Increment))
                         {
-                            return Increment((TExpressionSyntax)leftOfAssign);
+                            return Increment((TExpressionSyntax)leftOfAssign.WithoutTrailingTrivia(), postfix: syntaxFacts.IsStatement(currentAssignment.Parent));
                         }
 
                         if (diagnostic.Properties.ContainsKey(UseCompoundAssignmentUtilities.Decrement))
                         {
-                            return Decrement((TExpressionSyntax)leftOfAssign);
+                            return Decrement((TExpressionSyntax)leftOfAssign.WithoutTrailingTrivia(), postfix: syntaxFacts.IsStatement(currentAssignment.Parent));
```
Comment (MaStr11) [inline src/Analyzers/Core/CodeFixes/UseCompoundAssignment/AbstractUseCompoundAssignmentCodeFixProvider.cs:89]: `syntaxFacts.IsStatement` seems legit to address https://github.com/dotnet/roslyn/issues/53969#issuecomment-857908596, but maybe there is a better way to detect

> if the result of the assignment is used

There is also a lot of repetition, but I don't see a simple way to avoid that.

Comment (Youssef1313) [reply src/Analyzers/Core/CodeFixes/UseCompoundAssignment/AbstractUseCompoundAssignmentCodeFixProvider.cs:89]: What about `switch (x = x + 1)`? The assignment parent is a statement, but it should be prefix. Am I missing something?

Comment (MaStr11) [reply src/Analyzers/Core/CodeFixes/UseCompoundAssignment/AbstractUseCompoundAssignmentCodeFixProvider.cs:89]: Yes, you are right. Maybe `IsSimpleAssignmentStatement` is better.

https://github.com/dotnet/roslyn/blob/d3e915d2dc49f4371f510add785ea011ca6c36be/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs#L1374-L1376

Comment (Youssef1313) [reply src/Analyzers/Core/CodeFixes/UseCompoundAssignment/AbstractUseCompoundAssignmentCodeFixProvider.cs:89]: I'm not sure. But things I'd make sure they are not broken:

- `switch(...)`
- `return ....`
- `yield return ....`
- `while (...)`
- `var x = ...`
- `var x = (...)`
- `bool_expr ? ... : ...`
- `MethodCall(...)`

Comment (Youssef1313) [reply src/Analyzers/Core/CodeFixes/UseCompoundAssignment/AbstractUseCompoundAssignmentCodeFixProvider.cs:89]: Instead of doing syntax analysis here, could we do that by data flow analysis?

File: src/Analyzers/CSharp/Tests/UseCompoundAssignment/UseCompoundAssignmentTests.cs [hunk 3]
```diff
@@ -1087,11 +1087,85 @@ void M()
 {
     void M()
     {
-        for (int i = 0; i < 10; i++)
+        for (int i = 0; i < 10; ++i)
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/UseCompoundAssignment/UseCompoundAssignmentTests.cs:1090]: would prefer this not change.

File: src/Analyzers/CSharp/Tests/UseCompoundAssignment/UseCompoundAssignmentTests.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Analyzers/CSharp/Tests/UseCompoundAssignment/UseCompoundAssignmentTests.cs:1113]: the whole new expression should probably hve teh the exact leading/trailing trivia as the original full expression.  WithTriviaFrom can help with that.

**Review by CyrusNajmabadi — CHANGES_REQUESTED** [review]
tentatively requesting changes.  

1. if we can make it so we don't change the for loop incrementor, that would be nice.
2. insteaf of .WithoutTrivia just do .WithTriviaFrom to preserve leading/trailing trivia.

File: src/Analyzers/CSharp/Tests/UseCompoundAssignment/UseCompoundAssignmentTests.cs (hunk 1 above)
Comment (MaStr11) [reply src/Analyzers/CSharp/Tests/UseCompoundAssignment/UseCompoundAssignmentTests.cs:1113]: Done in 9e428fe7

File: src/Analyzers/CSharp/Tests/UseCompoundAssignment/UseCompoundAssignmentTests.cs (hunk 3 above)
Comment (MaStr11) [reply src/Analyzers/CSharp/Tests/UseCompoundAssignment/UseCompoundAssignmentTests.cs]: Done in 8b0e6572

**Comment by CyrusNajmabadi** [comment]
Are you ok with me pushing a couple of changes here?  Tahnks!

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs [hunk 4]
```diff
@@ -143,6 +143,15 @@ internal interface ISyntaxFacts
...
         bool IsExpressionOfForeach([NotNullWhen(true)] SyntaxNode? node);
+        /// <summary>
+        /// Returns the parts of a for loop. C#: for(var i = 0; i &lt; 10; i++) VB: For i = 0 To 10 Step 1
+        /// </summary>
+        /// <param name="node">The for loop statement</param>
+        /// <param name="variableDeclaration">C#: var i = 0 | VB: i</param>
+        /// <param name="startValue">C#: null | VB: 0</param>
+        /// <param name="endCondition">C#: i &lt; 10 | VB: 10</param>
+        /// <param name="increments">C#: i++ | VB: Step 1</param>
+        void GetPartsOfForStatement(SyntaxNode? node, out SyntaxNode? variableDeclaration, out SyntaxNode? startValue, out SyntaxNode? endCondition, out ImmutableArray<SyntaxNode> increments);
```
Comment (MaStr11) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs:154]: I thought the for loops of VB and C# are close enough for a "GetPartsOf" attempt, but they turned out to be quite different. Maybe it's better to create something like `IsPartOfForLoopIncrementor` in `AbstractUseCompoundAssignmentCodeFixProvider` or `ISyntaxFacts`.

**Comment by MaStr11** [comment]
> Are you ok with me pushing a couple of changes here? Tahnks!

Sure.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
thanks!
