### PR TITLE
Check type parameter index bounds when parsing `DocumentationCommentId`

### LINKED ISSUE #65396: DocumentationCommentId parser throws IndexOutOfRangeException when parsing type parameter symbol in invalid ID
**Version Used**: 
Microsoft.CodeAnalysis.dll 4.4.0-3.22518.13+7856a68c109b22de70e07580018fec601e944f46

**Steps to Reproduce**:

1. ```DocumentationCommentId.GetFirstSymbolForDeclarationId("M:System.Array.Sort``1(`0[])", Compilation)```

(Note that the correct ID for this method is ```M:System.Array.Sort``1(``0[])```.)

**Expected Behavior**:
Returns `null`.

**Actual Behavior**:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.CodeAnalysis.DocumentationCommentId.Parser.GetNthTypeParameter(INamedTypeSymbol typeSymbol, Int32 n)
   at Microsoft.CodeAnalysis.DocumentationCommentId.Parser.ParseTypeParameterSymbol(String id, Int32& index, ISymbol typeParameterContext, List`1 results)
   at Microsoft.CodeAnalysis.DocumentationCommentId.Parser.ParseTypeSymbol(String id, Int32& index, Compilation compilation, ISymbol typeParameterContext, List`1 results)
   at Microsoft.CodeAnalysis.DocumentationCommentId.Parser.ParseTypeSymbol(String id, Int32& index, Compilation compilation, ISymbol typeParameterContext)
   at Microsoft.CodeAnalysis.DocumentationCommentId.Parser.ParseParameter(String id, Int32& index, Compilation compilation, ISymbol typeParameterContext)
   at Microsoft.CodeAnalysis.DocumentationCommentId.Parser.ParseParameterList(String id, Int32& index, Compilation compilation, ISymbol typeParameterContext, List`1 parameters)
   at Microsoft.CodeAnalysis.DocumentationCommentId.Parser.GetMatchingMethods(String id, Int32& index, List`1 containers, String memberName, Int32 arity, Compilation compilation, List`1 results)
   at Microsoft.CodeAnalysis.DocumentationCommentId.Parser.ParseDeclaredId(String id, Int32& index, Compilation compilation, List`1 results)
   at Microsoft.CodeAnalysis.DocumentationCommentId.Parser.ParseDeclaredSymbolId(String id, Compilation compilation, List`1 results)
   at Microsoft.CodeAnalysis.DocumentationCommentId.GetFirstSymbolForDeclarationId(String id, Compilation compilation)
```

### PR DESCRIPTION
**Pull request by jjonescz**
Fixes #65396.

### CODE REVIEW

**Review by sharwell — APPROVED** [review]

**Review by cston — APPROVED** [review]

File: src/Compilers/Core/Portable/DocumentationCommentId.cs [hunk 1]
```diff
@@ -1374,7 +1374,12 @@ private static ITypeParameterSymbol GetNthTypeParameter(INamedTypeSymbol typeSym
                 }
 
                 var index = n - containingTypeParameterCount;
-                return typeSymbol.TypeParameters[index];
+                if (index < typeSymbol.TypeParameters.Length)
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/DocumentationCommentId.cs:1377]: >typeSymbol.TypeParameters [](http://example.com/codeflow?start=28&length=25)

Consider if caching this array is appropriate. It is quite possible that the property returns different arrays with the same content every time. The code is safe, but could allocate two arrays instead of one.

File: src/Workspaces/CoreTest/UtilityTest/DocumentationCommentIdTests.cs [hunk 2]
```diff
@@ -351,5 +351,21 @@ class InnerType<B, C>
             CheckReferenceId("System.Int32[]", compilation.CreateArrayTypeSymbol(intType), compilation);
             CheckReferenceId("System.Int32*", compilation.CreatePointerTypeSymbol(intType), compilation);
         }
+
+        [Fact, WorkItem(65396, "https://github.com/dotnet/roslyn/issues/65396")]
+        public void TestInvalidTypeParameterId()
```
Comment (AlekseyTs) [inline src/Workspaces/CoreTest/UtilityTest/DocumentationCommentIdTests.cs:356]: >TestInvalidTypeParameterId [](http://example.com/codeflow?start=20&length=26)

I think we need to add similar test for VB

File: src/Compilers/Core/Portable/DocumentationCommentId.cs (hunk 1 above)
Comment (jjonescz) [reply src/Compilers/Core/Portable/DocumentationCommentId.cs:1377]: Thanks, cached: 0900d3c79a4cdb651c5093f1ed91bccca4019c22

File: src/Workspaces/CoreTest/UtilityTest/DocumentationCommentIdTests.cs (hunk 2 above)
Comment (jjonescz) [reply src/Workspaces/CoreTest/UtilityTest/DocumentationCommentIdTests.cs]: Thanks. I haven't found VB tests for `DocumentatoinCommentId`, so I added it in the same class: 64443c472934146349ab021c6b3199efeed7d4c1

File: src/Compilers/Core/Portable/DocumentationCommentId.cs [hunk 3]
```diff
@@ -1365,7 +1365,7 @@ private static bool ParameterMatches(IParameterSymbol symbol, ParameterInfo para
                 return parameterType != null && symbol.Type.Equals(parameterType, SymbolEqualityComparer.CLRSignature);
             }
 
-            private static ITypeParameterSymbol GetNthTypeParameter(INamedTypeSymbol typeSymbol, int n)
+            private static ITypeParameterSymbol? GetNthTypeParameter(INamedTypeSymbol typeSymbol, int n)
```
[the remark this answers is not in the document]
Comment (jjonescz) [reply src/Compilers/Core/Portable/DocumentationCommentId.cs:1368]: Good catch, thanks. Fixed there, too: e89cf96a2396db1c6c2f86afd7bfc4225863f32d

File: src/Workspaces/CoreTest/UtilityTest/DocumentationCommentIdTests.cs [hunk 4]
```diff
@@ -351,5 +358,40 @@ class InnerType<B, C>
             CheckReferenceId("System.Int32[]", compilation.CreateArrayTypeSymbol(intType), compilation);
             CheckReferenceId("System.Int32*", compilation.CreatePointerTypeSymbol(intType), compilation);
         }
+
+        [Fact, WorkItem(65396, "https://github.com/dotnet/roslyn/issues/65396")]
+        public void TestInvalidTypeParameterId_CSharp()
```
Comment (AlekseyTs) [inline src/Workspaces/CoreTest/UtilityTest/DocumentationCommentIdTests.cs:363]: >TestInvalidTypeParameterId_CSharp [](http://example.com/codeflow?start=20&length=33)

Do these tests have to be in Workspaces layer? Can we move them into src\Compilers\Core\CodeAnalysisTest\Symbols\DocumentationCommentIdTests.cs?

**Comment by AlekseyTs** [comment]
Done with review pass (commit 4)

File: src/Workspaces/CoreTest/UtilityTest/DocumentationCommentIdTests.cs (hunk 4 above)
Comment (jjonescz) [reply src/Workspaces/CoreTest/UtilityTest/DocumentationCommentIdTests.cs]: You are right, thanks. Moved: bc3da5e704b89c30eca26232352db8819a6d3647

**Review by cston — APPROVED** [review]
