### PR TITLE
Fix unconditional binding of pointer types

### LINKED ISSUE #34693: StackOverflow in the compiler
**Repro:**
Compile the following program using the latest compiler bits:
```csharp
using System;
using System.Runtime.InteropServices;

namespace Interop
{
    public unsafe struct PROPVARIANT
    {
        public CAPROPVARIANT ca;
    }

    public unsafe struct CAPROPVARIANT
    {
        public uint cElems;
        public PROPVARIANT* pElems;
    }
}
```

StackTrace: 
[StackTrace.txt](https://github.com/dotnet/roslyn/files/3036089/StackTrace.txt)

### PR DESCRIPTION
**Pull request by RikkiGibson**
Fixes #34693

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/UnsafeTests.cs [hunk 1]
```diff
@@ -9193,5 +9193,26 @@ void M(S s)
...
+    }
+
+    public unsafe struct CAPROPVARIANT
+    {
+        public uint cElems;
+        public PROPVARIANT* pElems;
+    }
+}";
+            var comp = CreateCompilation(csharp, options: TestOptions.UnsafeDebugDll);
+            comp.VerifyDiagnostics();
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/UnsafeTests.cs]: What about the other test case about accessing a field through a derived type? Is that an existing test or do we need to add it?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/UnsafeTests.cs]: I can add the coverage however it's basically going to just reveal a less-impactful bug that was introduced in `features/unmanaged-constructed-types` as a side effect of delaying constraint checks until after field binding.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/UnsafeTests.cs]: There's one that's specific to "error on pointer to managed type" for which coverage already exists. We didn't happen to test a similar scenario for fields of a constrained generic type.

B<string*[]>.T, where T is not declared in B, is a Heisentype.
