### PR TITLE
Fix SimpleDiagnostic GetHashCode is more specific than Equals

### LINKED ISSUE #57: SimpleDiagnostic GetHashCode is inconsistent
To make Microsoft.CodeAnalysis.Diagnostic work with Sets and other data structures that requires GetHashCode to be implemented correctly you have to have a GetHashCode method with this property:  
```x.Equals(y) \implies x.GetHashCode() == y.GetHashCode() \forall x,y```

Currently SimpleDiagnostic's GetHashCode combines the hash codes of its properties including a GetHashCode on the object[] messageArgs which is using the reference to that array, not its contents to generate the hash code. Equals however is comparing the objects in the array (using Enumerable.SequenceEqual) . So currently you can have two diagnostics that are Equal in terms of IEquatable<Diagnostic>.Equals but with GetHashCode returning different values.
http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis/Diagnostic/Diagnostic_SimpleDiagnostic.cs,134
http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis/Diagnostic/Diagnostic_SimpleDiagnostic.cs,120

### PR DESCRIPTION
**Pull request by pdelvo**
Fixes #57.

I hope it is okay that I just went ahead and fixed it.

### CODE REVIEW

**Comment by pdelvo** [comment]
Btw. Why are the additional locations not used to determine equality?

**Comment by theoy** [comment]
> I hope it is okay that I just went ahead and fixed it.
> -- @pdelvo 

It is absolutely okay, in fact, awesome. Thanks for offering a fix - we're almost ready to start blasting through pull requests. We're just in the process of replacing our source control internally with Git on both sides so that we can fast-track all the subsequent pull requests :smile: Assignining to @mavasani since he has the corresponding bug too.

**Comment by pdelvo** [comment]
@AdamSpeight2008 
I don't think that the foreach is expensive. foeach on Arrays are getting turned into a for loop by the compiler if Im not mistakten.

@mavasani Create is calling the constructor which is checking messageArgs for null. It is using an empty array instead if it is. Hash.Combine<T> is checking for null so this should not be a problem if items in messageArgs are null. If I ignore null items in the array `new[] {null, "foo"}` would have the same hash as `new[] { "foo"}`

@pharring I did not know about Hash.CombineValues. Is the jit compiling the foreach loop in there into a for loop too?

I came up with a solution which should be faster and more readable.

File: src/Compilers/Core/Portable/Diagnostic/Diagnostic_SimpleDiagnostic.cs [hunk 1]
```diff
@@ -130,11 +130,15 @@ public override bool Equals(object obj)
 
             public override int GetHashCode()
             {
-                return Hash.Combine(_descriptor,
-                        Hash.Combine(_messageArgs.GetHashCode(),
-                         Hash.Combine(_location.GetHashCode(),
-                          Hash.Combine(_severity.GetHashCode(), _warningLevel)
-                        )));
+                int hash = 0;
```
Comment (pharring) [inline src/Compilers/Core/Portable/Diagnostic/Diagnostic_SimpleDiagnostic.cs]: Nit: Assignment to zero is not necessary since it's going to be overwritten on the next line.

**Comment by pdelvo** [comment]
@pharring I fixed that and I fixed a possible NRE if the location is null

**Comment by AdamSpeight2008** [comment]
Doesn't `foreach` get converted into a `while` loop?
```
var en = foos.GetEnumerator();
while( en.MoveNext() )
{

}
```

**Comment by pdelvo** [comment]
I can't compile roslyn on my machine this is why this stupid mistake could happen >.<
@AdamSpeight2008 Roslyn does optimize that.

File: src/Compilers/Core/Portable/Diagnostic/Diagnostic_SimpleDiagnostic.cs [hunk 2]
```diff
@@ -130,11 +130,15 @@ public override bool Equals(object obj)
...
+
+                hash = Hash.Combine(_location.GetHashCode(), 0);
+                hash = Hash.Combine((int)_severity, hash);
+                hash = Hash.Combine(_warningLevel, hash);
+                hash = Hash.Combine(Hash.CombineValues(_messageArgs), hash);
+                hash = Hash.Combine(_descriptor, hash);
```
Comment (pharring) [inline src/Compilers/Core/Portable/Diagnostic/Diagnostic_SimpleDiagnostic.cs]: Just an observation: While using the local variable undoubtedly makes the code easier to read, it does introduce a slight performance overhead. The original form's IL is shorter and (obviously) eliminates a local variable slot. The Roslyn compiler (currently) doesn't try to eliminate the local. I don't know whether the various JIT compilers will do so either.

File: src/Compilers/Core/Portable/Diagnostic/Diagnostic_SimpleDiagnostic.cs [hunk 3]
```diff
@@ -130,11 +130,15 @@ public override bool Equals(object obj)
...
-                        Hash.Combine(_messageArgs.GetHashCode(),
-                         Hash.Combine(_location.GetHashCode(),
-                          Hash.Combine(_severity.GetHashCode(), _warningLevel)
-                        )));
+                int hash = 0;
+
+                hash = Hash.Combine(_location.GetHashCode(), 0);
+                hash = Hash.Combine((int)_severity, hash);
+                hash = Hash.Combine(_warningLevel, hash);
+                hash = Hash.Combine(Hash.CombineValues(_messageArgs), hash);
```
Comment (pharring) [inline src/Compilers/Core/Portable/Diagnostic/Diagnostic_SimpleDiagnostic.cs]: Could this line be simply: `hash = Hash.CombineValues(_messageArgs, hash);`

File: src/Compilers/Core/Portable/Diagnostic/Diagnostic_SimpleDiagnostic.cs [hunk 4]
```diff
@@ -130,11 +130,15 @@ public override bool Equals(object obj)
...
             {
-                return Hash.Combine(_descriptor,
-                        Hash.Combine(_messageArgs.GetHashCode(),
-                         Hash.Combine(_location.GetHashCode(),
-                          Hash.Combine(_severity.GetHashCode(), _warningLevel)
-                        )));
+                int hash = 0;
+
+                hash = Hash.Combine(_location.GetHashCode(), 0);
+                hash = Hash.Combine((int)_severity, hash);
```
Comment (pharring) [inline src/Compilers/Core/Portable/Diagnostic/Diagnostic_SimpleDiagnostic.cs]: Lines 135 and 136 could be combined: `hash = Hash.Combine((int)_severity, _location.GetHashCode());`

Comment (pdelvo) [inline src/Compilers/Core/Portable/Diagnostic/Diagnostic_SimpleDiagnostic.cs]:
```csharp
hash = Hash.Combine(_location, (int)_severity);
```
Would work. _location could be null

**Comment by pdelvo** [comment]
I hope this is what you are looking for. If it is Im going to squash these commits together.

File: src/Compilers/Core/Portable/Diagnostic/Diagnostic_SimpleDiagnostic.cs (hunk 4 above)
Comment (mavasani) [inline src/Compilers/Core/Portable/Diagnostic/Diagnostic_SimpleDiagnostic.cs]: _location cannot be null. All the call sites that create SimpleDiagnostic use "location ?? Location.None". Probably we should have the same assignment expression in the constructors of SimpleDiagnostic to ensure _location is never set to null.

Comment (pdelvo) [inline src/Compilers/Core/Portable/Diagnostic/Diagnostic_SimpleDiagnostic.cs]: I have not looked at that. But relying on the caller to know that location cannot be null does not seem like a good idea if the first time an exception is thrown is when GetHashCode is called

Comment (mavasani) [inline src/Compilers/Core/Portable/Diagnostic/Diagnostic_SimpleDiagnostic.cs]: Yes exactly, we should not rely on the callers, but instead change the assignment in constructors of SimpleDiagnostic from "_location = location;" to "_location = location ?? Location.None;"

Comment (pdelvo) [inline src/Compilers/Core/Portable/Diagnostic/Diagnostic_SimpleDiagnostic.cs]: Should I do this in this PR too?

Comment (mavasani) [inline src/Compilers/Core/Portable/Diagnostic/Diagnostic_SimpleDiagnostic.cs]: If possible yes, otherwise I can take care of in a separate change. For now, you can assume _location is non-null as all of it's call site currently ensure that.

Comment (pdelvo) [inline src/Compilers/Core/Portable/Diagnostic/Diagnostic_SimpleDiagnostic.cs]: What about the descriptor? It could be null too. A diagnostic with no descriptor does not really make sense so should an ArgumentNullException be thrown?

**Comment by pdelvo** [comment]
I squashed this into one commit.

File: src/Compilers/Core/Portable/Diagnostic/Diagnostic_SimpleDiagnostic.cs (hunk 4 above)
Comment (mavasani) [inline src/Compilers/Core/Portable/Diagnostic/Diagnostic_SimpleDiagnostic.cs]: Yes, both changes look good. Thanks for fixing this! :+1:

**Comment by pdelvo** [comment]
The failed test semms to be unrelated to this

**Comment by mavasani** [comment]
@pdelvo Agreed, failing test "HandleSolutionProjectTypeSolutionFolder" seems to be unrelated to this change. I'll merge your PR. Thanks again!

**Comment by jaredpar** [comment]
@pdelvo 

Could you take a minute and sign the .NET Foundation CLA for the contributed code?

https://cla2.dotnetfoundation.org/

This should have been done before we merged the PR but there was some confusion on the process.

**Comment by pdelvo** [comment]
Done

**Comment by jaredpar** [comment]
@pdelvo thank you!
