### PR TITLE
Suppress 'IDE0041 Null check can be simplified' for unconstraint generic parameters.

### LINKED ISSUE #23581: IDE0041 Null check can be simplified is shown for Reference Equals of all generic parameters
IDE0041 should only be shown if the type is nullable or the generic parameter is constrained to a nullable type.
Executing the codefix will create invalid code.

**Version Used**: 
Visual Studio Enterprise 2017 15.5 RTM
**Steps to Reproduce**:

1. Use repro snippet from below
2. Build
3. Look at messages

**Expected Behavior**:
Not shown
**Actual Behavior**:
Message: IDE0041	Null check can be simplified is shown for the Reference Equals

Repro:
```csharp
public static void NotNull<T>(T value, string parameterName)
{
    if (ReferenceEquals(value, null)) // IDE0041 not valid here
    {
        throw new ArgumentNullException(parameterName);
    }
}
```

### PR DESCRIPTION
**Pull request by MaStr11**
### Customer scenario

`IDE0041 Null check can be simplified` is shown for the `ReferenceEquals` method and a fix is offered. The fix generates code which might have the compiler error 'Can not convert null to type parameter T because it could be a non-nullable value type.'. This fix suppresses IDE0041 if the parameter passed to ReferenceEquals is ~an unconstraint generic type parameter~ Update 01/17/2018: a value type constraint generic type parameter.

### Bugs this fixes

#23581

### Workarounds, if any

Suppress IDE0041 with a pragma or change the generated code from `(value is null)`to `(value == null)`.

### Risk

Low. Small additional check.

### Performance impact

Low. Syntax and semantic analysis has already been done by other checks on the code path before. This adds some more checks.

### Is this a regression from a previous update?

/

### Root cause analysis

/

### How was the bug found?

Customer reported #23581

### Test documentation updated?

/

### CODE REVIEW

**Comment by MaStr11** [comment]
Another option might be to generate `(value == null)` instead of `(value is null)`. VBs `value Is Nothing` seems also be fine with unconstraint parameters.

**Comment by MaStr11** [comment]
@CyrusNajmabadi 

> Another option might be to generate `(value == null)` instead of `(value is null)`. VBs `value Is Nothing` seems also be fine with unconstraint parameters.

This seems to be the better option (I just discovered this option after I finished the PR). Are there any downsides?

**Comment by CyrusNajmabadi** [comment]
> This seems to be the better option (I just discovered this option after I finished the PR). Are there any downsides?

Not that i can tell.  Make it so!

**Comment by MaStr11** [comment]
Oh my gosh! I just read dotnet/csharplang#505 and discovered that `(v == null)` fails for value type constraints:

```C#
public void TheFunction<T>(T a) where T : struct {
  var c = (a != null); // CS0019: Operator '!=' cannot be applied to operand of type 'T' and '<null>'
}
```
I will update the PR to suppress on value types now.

File: src/EditorFeatures/CSharpTest/UseIsNullCheck/UseIsNullCheckTests.cs [hunk 1]
```diff
@@ -36,7 +36,7 @@ class C
 {
     void M(string s)
     {
-        if (s is null)
+        if (s == null)
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/UseIsNullCheck/UseIsNullCheckTests.cs]: this seems like a regression.

File: src/Features/CSharp/Portable/UseIsNullCheck/CSharpUseIsNullCheckCodeFixProvider.cs [hunk 2]
```diff
@@ -17,12 +17,16 @@ protected override string GetIsNullTitle()
         protected override string GetIsNotNullTitle()
             => GetIsNullTitle();
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/UseIsNullCheck/CSharpUseIsNullCheckCodeFixProvider.cs]: the feature is literall the "Use 'is null'" feature :)   You're now using "== null".

Comment (MaStr11) [reply src/Features/CSharp/Portable/UseIsNullCheck/CSharpUseIsNullCheckCodeFixProvider.cs]: Yes. But I thought we agreed on [that](https://github.com/dotnet/roslyn/pull/24173#issuecomment-357335703). Did I got you wrong?

**Comment by CyrusNajmabadi** [comment]
> Did I got you wrong?

Yes (my fault).  I meant specifically using '==' only for the cases where 'is' wouldn't work.

**Comment by CyrusNajmabadi** [comment]
basically:
1. use "is null" whenever possible.
2. fall back to "== null" when '1' isn't possible.  (or possibly just suppress).
3. if neither are possible, offer nothing.

**Comment by MaStr11** [comment]
That's fine to me (I'm on the road tomorrow so this will not be done until Wednesday. Sorry.)

**Comment by CyrusNajmabadi** [comment]
No worries :)

**Comment by MaStr11** [comment]
I changed the logic as requested by @CyrusNajmabadi. I was wondering if it is worth to document somewhere that this fixer can be simplified once [this is done:](https://github.com/dotnet/roslyn/issues/24237#issuecomment-357676282) 

@gafter 
> We should change the language to permit value is null for an unconstrained generic.

There seems to be no issue in the language repo yet to link to.

**Comment by CyrusNajmabadi** [comment]
> There seems to be no issue in the language repo yet to link to.

you could make one :)   Then link to that in the code with a note.

File: src/Features/CSharp/Portable/UseIsNullCheck/CSharpUseIsNullCheckCodeFixProvider.cs [hunk 3]
```diff
@@ -17,12 +17,28 @@ protected override string GetIsNullTitle()
...
+        private static SyntaxNode CreateIsNullCheck(SyntaxNode argument)
             => SyntaxFactory.IsPatternExpression(
                 (ExpressionSyntax)argument,
                 SyntaxFactory.ConstantPattern(SyntaxFactory.LiteralExpression(SyntaxKind.NullLiteralExpression))).Parenthesize();
 
-        protected override SyntaxNode CreateIsNotNullCheck(SyntaxNode notExpression, SyntaxNode argument)
+        private static SyntaxNode CreateIsNotNullCheck(SyntaxNode notExpression, SyntaxNode argument)
             => ((PrefixUnaryExpressionSyntax)notExpression).WithOperand((ExpressionSyntax)CreateIsNullCheck(argument));
+
+        protected override SyntaxNode CreateNullCheck(SyntaxNode argument, bool isUnconstraintGeneric)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/UseIsNullCheck/CSharpUseIsNullCheckCodeFixProvider.cs]: Unconstrained (though Unconstraint is cute :))

File: src/Features/Core/Portable/UseIsNullCheck/AbstractUseIsNullDiagnosticAnalyzer.cs [hunk 4]
```diff
@@ -108,9 +119,18 @@ private void AnalyzeSyntax(SyntaxNodeAnalysisContext context, IMethodSymbol refe
                 return;
             }
 
+            var properties = ImmutableDictionary<string, string>.Empty;
+
+            switch (GetGenericParameterConstraintType(syntaxFacts, semanticModel, arguments[0], arguments[1], cancellationToken))
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/UseIsNullCheck/AbstractUseIsNullDiagnosticAnalyzer.cs]: a simpler approach seems like it would be if you just had this method return the type parameter if there is one.

then you could do:

```c#
if (typeParameter?.HasValueConstraint == true)
{
  return;
}
else if (...?.HasReferenceConstraint == true)
{
    ...
}
```

Then there's no need for the enum to shuttle data across that's already in the ITypeParameter.

**Comment by sharwell** [comment]
@Pilchie Requesting approval for 15.7 before we do the work to rebase this 😄

**Comment by Pilchie** [comment]
I'm in favor of fixing false positive diagnostic results as early as possible, so I would be supportive of this for 15.7.

**Comment by sharwell** [comment]
@MaStr11 This pull request needs to be rebased onto the **dev15.7.x** branch so we can get it to users earlier. Let me know if you'd like to do this yourself, or if you'd like me to go ahead and do it for you. 👍

**Comment by MaStr11** [comment]
@sharwell I changed the base branch but it seems there are some unrelated commits are also part of the PR. I'm not able to fix (because I don't know how to do it and because I'm currently on vacation and don't have my laptop with me). If there is anything that needs to be done it would be great if you could do it.

**Comment by sharwell** [comment]
@MaStr11 Thanks I'm on it!

**Comment by sharwell** [comment]
@Pilchie for approval

**Comment by Zenexer** [comment]
> Another option might be to generate `(value == null)` instead of `(value is null)`. VBs `value Is Nothing` seems also be fine with unconstraint parameters.

I know I'm late to the game here, but this needs to be documented: do not do this!  It's is not the same thing.  A `ReferenceEquals` comparison to `null` often occurs in the `Equals` override of a type, and that is in turn often referenced from `operator ==` and `operator !=`.  `value == null` will create an infinite loop.
