### PR TITLE
Set TypeDeclarationFlags.AnyMemberHasAttributes for a type with parameter list and a method-targeted attribute.

### LINKED ISSUE #68349: C# 12 primary constructors + ObsoleteAttribute
**Version Used**: 

current `main` branch

**Steps to Reproduce**:

Compile the following code:
```
using System;

_ = new ObsoletePrimary(); // missing error

var customAttributes = typeof(ObsoletePrimary).GetConstructors()[0].GetCustomAttributes(false);
Console.WriteLine(((ObsoleteAttribute)customAttributes[0]).Message); // prints "Obsolete 1"
return;

[method: Obsolete("Obsolete 1", error: true)]
partial class ObsoletePrimary();
[method: Obsolete("Obsolete 2", error: true)]
partial class ObsoletePrimary;
```

**Expected Behavior**:

Compilation error because of the `[Obsolete]` constructor usage.

**Actual Behavior**:

The code compiles fine.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #68349.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Declarations/DeclarationTreeBuilder.cs [hunk 1]
```diff
@@ -693,6 +693,14 @@ private SingleTypeDeclaration VisitTypeDeclaration(TypeDeclarationSyntax node, D
             {
                 declFlags |= SingleTypeDeclaration.TypeDeclarationFlags.HasAnyNontypeMembers;
                 declFlags |= SingleTypeDeclaration.TypeDeclarationFlags.HasPrimaryConstructor;
+
+                foreach (var attributeListSyntax in node.AttributeLists)
+                {
+                    if (attributeListSyntax.Target?.Identifier.ToAttributeLocation() == AttributeLocation.Method)
+                    {
+                        declFlags |= SingleTypeDeclaration.TypeDeclarationFlags.AnyMemberHasAttributes;
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Declarations/DeclarationTreeBuilder.cs:701]:
```suggestion
                        declFlags |= SingleTypeDeclaration.TypeDeclarationFlags.AnyMemberHasAttributes;
                        break;
```

**Comment by AlekseyTs** [comment]
@cston, @jjonescz Please review

**Review by jjonescz — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@cston, @dotnet/roslyn-compiler For the second review.

**Review by cston — APPROVED** [review]
