### PR TITLE
Handle unsupported diagnostics reported by analyzers

### LINKED ISSUE #252: Filtering is broken for analyzers reporting diagnostics with ID not beloging to any descriptor returned by SupportedDiagnostics
Ported from TFS WorkItem: <b>1100829</b>

------------------------------

<p><b>Repro Steps:</b></p>
<BR>1. Write a diagnostic analyzer with single descriptor with ID say "Rule1" returned in DiagnosticAnalyzer.SupportedDiagnostics</P>
<P>2. Report a diagnostic with a different ID, say "Rule2",&nbsp;in the analyzer</P>
<P>3. Start VS experimental instance with the analyzer and create a test that fires "Rule2".</P>
<P>&nbsp;</P>
<P>Expected:&nbsp;"Rule2" diagnostic is filtered out as the SupportedDiagnostics didn't return a descriptor with Rule2</P>
<P>Actual: "Rule2" is reported. Additionally, you cannot configure "Rule2" in ruleset editor as it is not part of SupportedDiagnostics.</P>
<P>&nbsp;</P>
<P>We should probably also write a Roslyn meta-analyzer to detect this scenario and flag the incorrect ReportDiagnostic invocation.</P>

------------------------------

<p><b>Revisions:</b></p>

1) Created By Manish Vasani (12/29/2014 11:09:34 AM)

------------------------------

2) Edited By Srivatsn Narayanan (1/9/2015 9:56:28 AM)

You've already written the roslyn analyzer for this now right?

------------------------------

3) Edited By Manish Vasani (1/9/2015 10:05:01 AM)

<p>Yes, the analyzer is written, but we need to still implement the logic in the drivers to filter reported diagnostics with unsupported ID.</p>
<p>Without this change, the analyzer's claim that unsupported diagnostics will not be reported is invalid as we will report even unsupported&nbsp;diagnostic reported by analyzer.</p>

------------------------------

4) Edited By Srivatsn Narayanan (1/9/2015 1:01:10 PM)

Ah i&nbsp;misunderstood. Yes we should do that. The things stopping us from doing it before was the the compiler and the EnC analyzer were both producing diagnostics that werent reported through SupportedDiagnostics. I think we are fine on both counts now. Let's make this change.

------------------------------

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #252 : If an analyzer reports a diagnostic with an unsupported diagnostic ID, i.e. no descriptor returned by SupportedDiagnostics has that ID, then throw an ArgumentException in ReportDiagnostic method. This exception would be turned into an analyzer diagnostic by the driver and reported back to the analyzer host.

Also fix a few tests that were reporting diagnostics with unsupported ID!

@srivatsn @tmeschter @shyamnamboodiripad @JohnHamby @jmarolf @heejaechang can you please review?

### CODE REVIEW

**Comment by sharwell** [comment]
:exclamation: This will break some analyzers, and I'm not sure it's what you want to do in all cases.

For a specific example, our original implementation of StyleCop rule SA1119 only really reported SA1119, but we created an additional diagnostic for the purpose of marking the parentheses themselves as unnecessary code. You can see this in DotNetAnalyzers/StyleCopAnalyzers#363. This weekend we updated the implementation of this analyzer to report both diagnostics as supported (in DotNetAnalyzers/StyleCopAnalyzers@264eb6d19a98da8c17c72d4d9d0870caf8732bc6) in order to simplify our testing. I was a bit uncomfortable with this change because I don't want the supporting rule to cause this analyzer to run even if the user disables SA1119. To ensure the analyzer is only triggered when SA1119 itself is enabled, I marked the supporting diagnostic as disabled by default when I added it to the list of supported diagnostics (it already has the tag `WellKnownDiagnosticTags.NotConfigurable`). I am assuming that a diagnostic can be reported even when it is disabled, and the UI for it will appear properly (e.g. Visual Studio will gray out the code we are marking as unnecessary).

File: src/Compilers/Core/AnalyzerDriver/AnalyzerExecutor.cs [hunk 1]
```diff
@@ -36,15 +37,17 @@ internal class AnalyzerExecutor
         /// Optional delegate which is invoked when an analyzer throws an exception.
```
Comment (VladimirReshetnikov) [inline src/Compilers/Core/AnalyzerDriver/AnalyzerExecutor.cs]: Is the name `AnalyzerActionsExecutor` in the `<summary>` element above up-to-date? Consider using `cref` for it.

File: src/Compilers/Core/AnalyzerDriver/DiagnosticAnalysisContextHelpers.cs [hunk 2]
```diff
@@ -25,12 +25,17 @@ internal static void VerifyArguments<TContext>(Action<TContext> action, Immutabl
...
+        internal static void VerifyArguments(Diagnostic diagnostic, Func<Diagnostic, bool> isSupportedDiagnostic)
         {
             if (diagnostic == null)
             {
                 throw new ArgumentNullException(nameof(diagnostic));
             }
+
+            if (!isSupportedDiagnostic(diagnostic))
+            {
+                throw new ArgumentException(string.Format(AnalyzerDriverResources.UnsupportedDiagnosticReported, diagnostic.Id));
```
Comment (VladimirReshetnikov) [inline src/Compilers/Core/AnalyzerDriver/DiagnosticAnalysisContextHelpers.cs]: Consider passing `nameof(diagnostic)` as the second argument to the constructor.

File: src/Compilers/Core/AnalyzerDriver/AnalyzerExecutor.cs [hunk 3]
```diff
@@ -54,9 +57,11 @@ internal class AnalyzerExecutor
...
```
Comment (VladimirReshetnikov) [inline src/Compilers/Core/AnalyzerDriver/AnalyzerExecutor.cs]: The same question about `<summary>` here.

**Comment by tmeschter** [comment]
:+1:

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs [hunk 4]
```diff
@@ -303,7 +305,7 @@ public CompilationAnalysisContext(Compilation compilation, AnalyzerOptions optio
         /// <param name="diagnostic"><see cref="Diagnostic"/> to be reported.</param>
         public void ReportDiagnostic(Diagnostic diagnostic)
         {
-            DiagnosticAnalysisContextHelpers.VerifyArguments(diagnostic);
+            DiagnosticAnalysisContextHelpers.VerifyArguments(diagnostic, _isSupportedDiagnostic);
             lock (_reportDiagnostic)
```
Comment (VladimirReshetnikov) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs]: Why do we lock on a delegate object passed to the constructor from outside? It introduces an implicit dependency on the calling code (e.g. it might pass the same object to other unrelated methods that can also lock on it).

Comment (mavasani) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs]: The constructor is only invoked from the within the IDE and compiler analyzer drivers, and #1285 tracks internalizing these constructors.

We need to lock the reportDiagnostic callback as the analyzer might decide to kick off multiple threads and report diagnostics from different threads simultaneously. We can probably guarantee that all analyzer hosts use thread safe diagnostic bags and the Add delegate that they provide for reported diagnostics is thread safe. However, this code is not maintainable and likely to introduce future race conditions. The only foolproof approach here is to make ReportDiagnostic itself intrinsically thread-safe by using a lock.

**Comment by mavasani** [comment]
@sharwell Thanks for sharing this use case, I hadn't considered this and probably it was overlooked by our team as well.

However, I think your current strategy is relying on a bug on our side as being an unintentional way to support a feature. I think the analyzer driver is right in assuming that an analyzer only ever reports diagnostics that it was told are supported, and not guaranteeing this can lead to other unforeseen bugs.

Having said that I agree that we can't checkin this change unless we add first class support for representing _linked_ descriptors, we don't want to break analyzer authors without giving an alterative. I am going to propose we do the following:

1. Add a public well known custom tag, say LinkedDiagnostic, that essentially marks a descriptor as being as second-tier or linked diagnostic. IsDiagnosticAnalyzerSuppressed API (http://source.roslyn.io/Microsoft.CodeAnalysis/R/6f5eadfed0d9a0eb.html) that determines if an analyzer is suppressed should not consider linked diagnostics.
2. Another related functionality that I think would be helpful to offer is an API such GetEffectiveDescritpor(compilation, descriptor) on the same lines as GetEffectiveDiagnostics (http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/CompilationWithAnalyzers.cs,ec36ad7bb5c29261). The API will take a descriptor and apply the compilation options (which includes the ruleset settings) and return the effective descriptor. So, if an analyzer has multiple first-tier descriptors and a second-tier or linked diagnostic depending on a subset of first-tier descriptors, it can have a check up front to determine the effective severity of second-tier descriptor based on that of its parent descriptors.

@srivatsn @JohnHamby @tmeschter @heejaechang @jmarolf @shyamnamboodiripad whats your view for this scenario?

**Comment by sharwell** [comment]
I like the idea of a `WellKnownDiagnosticTags.Linked`, or similar. Even if equivalent behavior can be created by following a particular combination of existing options, it is not really clear how all the settings play together. It would only be valid for `Hidden` diagnostics, and would imply `WellKnownDiagnosticTags.NotConfigurable`. The handling in "IsDiagnosticAnalyzerSuppressed" would effectively treat `Linked` as disabled by default (a setting which I needed to explicitly set).

In the absence of a `Linked` tag like this, it seems one additional option would be not throwing the `ArgumentException` for reported diagnostics that are `Hidden`, since they will not appear in the errors list and are not (or should not be?) part of filtering.

**Comment by mavasani** [comment]
Another alternative would be add an additional optional parameter "linkedDescriptors" to the DiagnosticDescriptor constructor and let the analyzer engine handle all this internally.

We have decided to put this PR on hold and discuss the design at a team meeting. I'll give an update here once we finalize the design. This PR is not super critical for us anyways, so we are fine with taking our time to design this properly.

Thanks again @sharwell

**Comment by heejaechang** [comment]
@mavasani @sharwell linked diagnostic is interesting. and usage case seems interesting. but kind of feels like we are trying to use diagnostic to send extra information to the system. since the linked diagnostic is not actually a diagnostic but something we use for other purpose like having extra tagging on screen, having different code fix area than squiggles and etc.

we have 3 different system to deliver such information now, custom tag, diagnostic property, trigger diagnostic.

we might need to think a bit deeper about those mechanisms and sort things about more clearly.

@srivatsn @JohnHamby @tmeschter @jmarolf how do you think?

**Comment by srivatsn** [comment]
Yes I agree that we need to think more about this scenario. What @sharwell is really trying do is to have a custom presentation. He needs to squiggle the entire expression but also grey out the surrounding parentheses for that issue. Because diagnostic authors cannot provide their own presentation of the issue and are limited to the only ones that are implemented (squiggle or fading out for unnecessary), this "linked" diagnostic is being used as a way to hack that in.

#1224 is the feature request for giving diagnostic authors the ability to define custom presentations. I imagine it would look like this:
- Diagnostic for SA1119 will have a custom tag called (say) "SA119PresentationTag". 
- The diagnostic engine should provide a way of registering a callback when a diagnostic with this customtag needs to be presented in the editor and will be handed the instance of the Diagnostic.
- The callback would simply create the green squiggle for the expression and grey out the two surrounding parentheses.

**Comment by heejaechang** [comment]
@mavasani @sharwell @srivatsn  by the way, I think we need to check this in for RC. so that people can't to rely on this behavior (our bug). it is unfortunate that this will remove something people could do due to our bug but I think we should stop from more people doing this sooner and provide proper way to do this.

**Comment by JohnHamby** [comment]
I will need to think (and probably discuss in person) before having anything meaningful to say about custom presentations or linked diagnostics, but analyzers should not be able to report diagnostics that they don't advertise. The original intent of this pull request is fundamentally correct.

File: src/Compilers/Core/AnalyzerDriver/AnalyzerManager.cs [hunk 5]
```diff
@@ -223,6 +223,20 @@ internal void ClearAnalyzerExceptionHandlers(DiagnosticAnalyzer analyzer)
             }
         }
 
+        internal bool IsSupportedDiagnostic(DiagnosticAnalyzer analyzer, Diagnostic diagnostic, AnalyzerExecutor analyzerExecutor)
+        {
+            var supportedDescriptors = GetSupportedDiagnosticDescriptors(analyzer, analyzerExecutor);
+            foreach (var descriptor in supportedDescriptors)
```
Comment (heejaechang) [inline src/Compilers/Core/AnalyzerDriver/AnalyzerManager.cs]: this is iterating through supported descriptions, can we think about a bit more performant way to do this at right position?

File: src/Compilers/Core/AnalyzerDriver/AnalyzerExecutor.cs [hunk 6]
```diff
@@ -36,15 +37,17 @@ internal class AnalyzerExecutor
...
         /// Delegate can do custom tasks such as report the given analyzer exception diagnostic, report a non-fatal watson for the exception, etc.
         /// </param>
+        /// <param name="analyzerManager">Analyzer manager to fetch supported diagnostics.</param>
```
Comment (JohnHamby) [inline src/Compilers/Core/AnalyzerDriver/AnalyzerExecutor.cs]: Is the manager providing supported diagnostics or diagnostic identifiers?

**Comment by srivatsn** [comment]
There is already an analyzer (part of the Codeanalysis analyzers) that tells you to not do this. @sharwell  - i'm curious did you see that diagnostic and did you have to suppress it? (If you are building on CTP6, you would have that analyzer)

File: src/Compilers/Core/AnalyzerDriver/AnalyzerManager.cs (hunk 5 above)
Comment (JohnHamby) [inline src/Compilers/Core/AnalyzerDriver/AnalyzerManager.cs]: The linear scan is surely OK, given that this runs only if a diagnostic is being reported and a given analyzer is quite unlikely to have hundreds of thousands of supported diagnostics, but maybe a comment to this effect is appropriate.

**Comment by tmeschter** [comment]
@srivatsn It's possible that diagnostic isn't even running due to the incorrect layout of the dependencies in the NuGet associated with CTP6. :-(

**Comment by tmeschter** [comment]
Since we added a property bag to `Diagnostic`, could we use that to communicate presentation information back to the host?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs (hunk 4 above)
Comment (JohnHamby) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs]: Is this robust? If the passed-in delegate comes from a lambda expression, is there a guarantee that the lambda doesn't create a new instance at each evaluation and thereby defeat the locking?

File: src/Compilers/Core/AnalyzerDriver/AnalyzerManager.cs (hunk 5 above)
Comment (JohnHamby) [inline src/Compilers/Core/AnalyzerDriver/AnalyzerManager.cs]: I wrote my comment before reading HeeJae's, but mine read as a response to his. I was actually responding to asking myself the same question.

Comment (heejaechang) [inline src/Compilers/Core/AnalyzerDriver/AnalyzerManager.cs]: but we already have compiler analyzer that has many diagnostics for each compiler diagnostic reported we will linearly scan all those. and assumption seems a bit to risky. how about analyzer manager who cache the descriptor anyway, check the count of the descriptor when cache and if it is more than 10 or something, we cache them in hashset rather than array?

**Comment by JohnHamby** [comment]
I sign off. We do need to discuss the objection, and come up with a decent way of covering it.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs (hunk 4 above)
Comment (mavasani) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/DiagnosticAnalysisContext.cs]: You are right, Sri is going to open a new issue to fix this in a better way.

**Comment by sharwell** [comment]
@srivatsn We did not see that diagnostic. In addition to the issue mentioned by @tmeschter, it's possible the diagnostic does not support our pattern of declaring the `ImmutableArray` for descriptors [using a backing field](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/d4a2b4b6c05c1c298ec6a901c4f6d3c59dabe109/StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1600ElementsMustBeDocumented.cs#L41-L51).

**Comment by mavasani** [comment]
@sharwell @heejaechang @JohnHamby @srivatsn let me try to summarize:

1. Fixing #1224 is the correct way to support presentation related concepts for diagnostics, not using helper diagnostics or reporting unsupported hidden diagnostics.
2. We don't want to bake any concept of such trigger/presentation diagnostics into our diagnostics API, and in fact want to discourage that as it as abuse of the diagnostic system and can lead to other bugs.
3. Until the above is fixed, @sharwell or any other analyzer that needs such linked presentation diagnostics, can workaround by using the helper diagnostic descriptor, but needs to make sure it is returned as part of the supported diagnostic descriptors. If they want to guarantee that the entire analyzer is completely turned off, they need to make the helper descriptor configurable and ask their users to turn off both the rules as a group. If they don't care about performance and are ok with analyzer running even when the primary diagnostic is suppressed, they can invoke this API (http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/CompilationWithAnalyzers.cs,ec36ad7bb5c29261) prior to reporting their primary diagnostic and only report the linked diagnostic if the primary diagnostic is not suppressed. I think these are acceptable workarounds till we fix #1224 

Does this sound reasonable?

**Comment by heejaechang** [comment]
@mavasani  +1

**Comment by srivatsn** [comment]
That sounds reasonable to me too.

**Comment by JohnHamby** [comment]
I agree that Manish's summary and proposal represent a reasonable position.

File: src/Compilers/Core/AnalyzerDriver/AnalyzerManager.cs (hunk 5 above)
Comment (mavasani) [inline src/Compilers/Core/AnalyzerDriver/AnalyzerManager.cs]: I agree with both of your views.
For compiler analyzer we don't even want to invoke SupportedDiagnostics to determine whether or not to run the analyzer AND whether or not diagnostics it reports are supported. We already did the former, and I will modify the PR to do the later as well by special casing the compiler analyzer.
I also agree with John's comment that for rest of the analyzers, we should be fine doing a linear scan here, doesn't buy us much by adding any more complexity.

**Comment by mavasani** [comment]
@srivatsn @sharwell @tmeschter the code analysis analyzer diagnostic that recommends not to report diagnostics with unsupported descriptors only scans for identifiers that bind to DiagnosticDescriptor type within the body of SupportedDiagnostics property. We should expand it look for backing fields of type ImmutableArray of descriptor. Note that the analyzer still cannot be guaranteed to catch 100% of misuse cases until we have complete dataflow analysis support.

**Comment by suprak** [comment]
Just wanted to touch base and see if there are any new recommendations other than what was last mentioned by @mavasani.

If not, I wanted to ask for more clarification what "can workaround by using the helper diagnostic descriptor" refers to in @mavasani's recommendation (#3)?

**Comment by sharwell** [comment]
@suprak Take a look at DotNetAnalyzers/StyleCopAnalyzers#930. Originally we just reported a diagnostic without declaring support for it. This pull request updates the analyzer to properly declare the existence of both diagnostics, and avoids performing the actual analysis if the "main" diagnostic is suppressed (a test for this performance issue was later added in DotNetAnalyzers/StyleCopAnalyzers#951).

**Comment by suprak** [comment]
Thanks for the pointer @sharwell 

Is there any update of how/when #1224 will be officially supported?

**Comment by mavasani** [comment]
@sharwell @suprak A better way to check for suppression of primary diagnostic is to use the newly added public API: [`DiagnosticDescriptor.GetEffectiveSeverity`](http://source.roslyn.io/Microsoft.CodeAnalysis/R/298bc3617e8352cc.html)

**Comment by suprak** [comment]
@mavasani Any comment on the status of support for #1224?

**Comment by mavasani** [comment]
I don't think we have it in our plans for the next update.

/cc @Pilchie @srivatsn @ManishJayaswal might have more information about the timeline for #1224

**Comment by suprak** [comment]
@mavasani Is what you mentioned earlier in this thread (1) still currently the best way to add rich adornments to diagnostics?

(1) https://github.com/dotnet/roslyn/pull/1286#issuecomment-81938018

**Comment by mavasani** [comment]
@suprak Yes, you are correct.
