### PR TITLE
Move IDE0078 codefix to Analyzers

### LINKED ISSUE #45569: IDE0078 diagnostic shows up without the code fix in CSharp CodeStyle NuGet package
**Version Used**: Latest

**Steps to Reproduce**:

1. Create a simple C# project
2. Add a NuGet package reference to latest NuGet package from https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.CodeAnalysis.CSharp.CodeStyle
3. Add code that triggers IDE0078 (Use pattern matching). Refer to https://github.com/dotnet/roslyn/blob/8601701c373aa687fdf5ccbe4a24498f67433751/src/EditorFeatures/CSharpTest/UsePatternCombinators/CSharpUsePatternCombinatorsDiagnosticAnalyzerTests.cs.

**Expected Behavior**:
IDE0078 diagnostic + Code fix on Ctrl + Dot

**Actual Behavior**:
IDE0078 diagnostic, but no code fix is offered.

The reason is that the analyzer was correctly added to analyzers shared project that is included in both Features and CodeStyle NuGet package. However, both the code fix and tests were added to Features/EditorFeatures instead of being added to shared projects. Hence the fix is not part of CodeStyle NuGet package:

**Actual locations**
1. Analyzer location:
https://github.com/dotnet/roslyn/blob/8601701c373aa687fdf5ccbe4a24498f67433751/src/Analyzers/CSharp/Analyzers/UsePatternCombinators/CSharpUsePatternCombinatorsDiagnosticAnalyzer.cs
2. Fixer location: https://github.com/dotnet/roslyn/blob/8601701c373aa687fdf5ccbe4a24498f67433751/src/Features/CSharp/Portable/UsePatternCombinators/CSharpUsePatternCombinatorsCodeFixProvider.cs
3. Tests location: https://github.com/dotnet/roslyn/blob/8601701c373aa687fdf5ccbe4a24498f67433751/src/EditorFeatures/CSharpTest/UsePatternCombinators/CSharpUsePatternCombinatorsDiagnosticAnalyzerTests.cs

**Expected locations**
1. Analyzer location is fine
2. Fixer location: https://github.com/dotnet/roslyn/tree/master/src/Analyzers/CSharp/CodeFixes
3. Tests location: https://github.com/dotnet/roslyn/tree/master/src/Analyzers/CSharp/Tests

### PR DESCRIPTION
**Pull request by Youssef1313**
Closes #45569

### CODE REVIEW

File: src/Analyzers/CSharp/CodeFixes/CSharpCodeFixes.projitems [hunk 1]
```diff
@@ -19,6 +19,7 @@
     <Compile Include="$(MSBuildThisFileDirectory)ConvertTypeOfToNameOf\CSharpConvertTypeOfToNameOfCodeFixProvider.cs" />
     <Compile Include="$(MSBuildThisFileDirectory)ConvertSwitchStatementToExpression\ConvertSwitchStatementToExpressionCodeFixProvider.cs" />
     <Compile Include="$(MSBuildThisFileDirectory)ConvertSwitchStatementToExpression\ConvertSwitchStatementToExpressionCodeFixProvider.Rewriter.cs" />
+    <Compile Include="$(MSBuildThisFileDirectory)CSharpUsePatternCombinatorsCodeFixProvider.cs" />
```
Comment (mavasani) [inline src/Analyzers/CSharp/CodeFixes/CSharpCodeFixes.projitems:22]: I am wondering if we should add `ExportCodeFixProviderAttribute` and `DiagnosticAnalyzerAttribute` to Banned APIs in Features layer, with a recommendation to move the analyzer/fixer down to the shared layer, when possible. For cases where this is not possible due to analyzer/fixer using a public API not available in a shipped Roslyn version, one would be expected to add a source suppression, with a TODO tracking the move later when the public API does become available (similar to the issue closed by this PR).

What do you thing @Youssef1313?

Comment (mavasani) [reply src/Analyzers/CSharp/CodeFixes/CSharpCodeFixes.projitems:22]: Btw, I don't recall if BannedApiAnalyzer flags banned attribute constructors :-)

**Review by mavasani — APPROVED** [review]

File: src/Analyzers/CSharp/CodeFixes/CSharpCodeFixes.projitems (hunk 1 above)
Comment (Youssef1313) [reply src/Analyzers/CSharp/CodeFixes/CSharpCodeFixes.projitems:22]: @mavasani There are too many codefixes there anyway. Banning the attribute (if possible) and suppressing all of the warnings is going to be noisy. I may look into moving more codefixes later. Then fix BannedApiAnalyzer if needed and use it.

File: src/Analyzers/CSharp/CodeFixes/UsePatternCombinators/CSharpUsePatternCombinatorsCodeFixProvider.cs [hunk 2]
```diff
@@ -118,7 +118,7 @@ private static PatternSyntax AsPatternSyntax(AnalyzedPattern pattern)
         private static ExpressionSyntax AsExpressionSyntax(ExpressionSyntax expr, AnalyzedPattern p)
         {
             var semanticModel = p.Target.SemanticModel;
-            Debug.Assert(semanticModel != null);
+            RoslynDebug.Assert(semanticModel != null);
```
Comment (Youssef1313) [inline src/Analyzers/CSharp/CodeFixes/UsePatternCombinators/CSharpUsePatternCombinatorsCodeFixProvider.cs:121]: `Debug.Assert` isn't annotated for netstandard2.0. Used RoslynDebug instead of null-suppression with `!`.

File: src/Analyzers/CSharp/CodeFixes/UsePatternCombinators/CSharpUsePatternCombinatorsCodeFixProvider.cs [hunk 3]
```diff
@@ -148,7 +148,9 @@ public MyCodeAction(string title, Func<CancellationToken, Task<Document>> create
             {
             }
 
+#if !CODE_STYLE // 'CodeActionPriority' is not a public API, hence not supported in CodeStyle layer.
             internal override CodeActionPriority Priority => CodeActionPriority.Low;
+#endif
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/CodeFixes/UsePatternCombinators/CSharpUsePatternCombinatorsCodeFixProvider.cs:153]: how does this work in vs @mavasani ?  do we pick up the CodeStyle fixer? Or do we pick up the one from Features?

Comment (mavasani) [reply src/Analyzers/CSharp/CodeFixes/UsePatternCombinators/CSharpUsePatternCombinatorsCodeFixProvider.cs:153]: We prefer the fixer and analyzer from NuGet package over the one from VSIX

Comment (mavasani) [reply src/Analyzers/CSharp/CodeFixes/UsePatternCombinators/CSharpUsePatternCombinatorsCodeFixProvider.cs:153]: Btw is there a specific reason for marking this as low priority?

Comment (Youssef1313) [reply src/Analyzers/CSharp/CodeFixes/UsePatternCombinators/CSharpUsePatternCombinatorsCodeFixProvider.cs:153]: @mavasani From related discussion in https://github.com/dotnet/roslyn/pull/43596, it seems this was a copy from another feature

image

I think if overriding `Priority` is something important the API may be considered to be exposed publicly

Comment (Youssef1313) [reply src/Analyzers/CSharp/CodeFixes/UsePatternCombinators/CSharpUsePatternCombinatorsCodeFixProvider.cs:153]: cc @alrz
