### PR TITLE
Fix parsing regression of expressions involving parens when used as a case expression or a constant pattern.

### LINKED ISSUE #33054: [x64](3.0.100-preview-010184) Switch expression bug
Hi

Looks like the new pattern matching feature broke old style switch expression

https://github.com/rds1983/StbImageSharp/blob/master/src/StbImageSharp/PngDecoder.cs#L714

Doesn't compile anymore 

```
  PngDecoder.cs(714, 38): [CS1003] Syntax error, ':' expected
  PngDecoder.cs(714, 70): [CS1002] ; expected
  PngDecoder.cs(714, 70): [CS1513] } expected
  PngDecoder.cs(718, 39): [CS1003] Syntax error, ',' expected
  PngDecoder.cs(774, 39): [CS1003] Syntax error, ',' expected
  PngDecoder.cs(793, 39): [CS1003] Syntax error, ',' expected
  PngDecoder.cs(842, 39): [CS1003] Syntax error, ',' expected
  PngDecoder.cs(878, 39): [CS1003] Syntax error, ',' expected
```

### LINKED ISSUE #33208: Breaking: case no longer works with constant expressions
**Version Used**: VisualStudio.16.Preview/16.0.0-pre.2.1+28529.54

**Steps to Reproduce**:
Switching on an integer variable:
`case ((2) + (2)):` and `case ((2 + 2) - 2):`
```
(3,10): error CS8370: Feature 'recursive patterns' is not available in C# 7.3. Please use language version 8.0 or greater.
(3,15): error CS1003: Chyba syntaxe; očekávána hodnota: ,
```

`case (2) | (2):` or `case ((2 << 2) | 2):`
```
(3,20): error CS1026: Očekává se ).
(3,20): error CS1003: Chyba syntaxe; očekávána hodnota: :
(3,20): error CS1525: Neplatný výraz |
(3,23): error CS1002: Očekával se středník (;).
(3,23): error CS1513: Očekával se znak }.
```

All cases above work in VS 2017.

(Sorry for non-English exceptions which is probably unrelated regression in VS2019.)

### PR DESCRIPTION
**Pull request by gafter**
- Fix parsing regression of expressions involving parens when used as a case expression or a constant pattern.
Fixes #33054
Fixes #33208
- Incidentally also correct and test the precedence of the switch expression
See https://github.com/dotnet/csharplang/blob/master/proposals/patterns.md#switch-expression for the spec.
- Fix terminology to match the spec - "conditional expression" rather than "ternary expression".

See also https://devdiv.visualstudio.com/DevDiv/_workitems/edit/792975 for shiproom purposes.

@dotnet/roslyn-compiler May I please have a couple of reviews of this parsing regression?

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 1]
```diff
@@ -9075,7 +9073,7 @@ private ExpressionSyntax ParseSubExpressionCore(Precedence precedence)
             {
                 // Operator ".." here can either be a prefix unary operator or a stand alone empty range:
                 var opToken = this.EatToken();
-                opKind = SyntaxKind.RangeExpression;
+                var opKind = SyntaxKind.RangeExpression;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: >var opKind = SyntaxKind.RangeExpression; [](start = 16, length = 40)

const? Or perhaps inline the value?

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 2]
```diff
@@ -9092,7 +9090,7 @@ private ExpressionSyntax ParseSubExpressionCore(Precedence precedence)
             }
             else if (IsAwaitExpression())
             {
-                opKind = SyntaxKind.AwaitExpression;
+                var opKind = SyntaxKind.AwaitExpression;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: >var opKind = SyntaxKind.AwaitExpression; [](start = 16, length = 40)

const? Or perhaps inline the value?

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 3]
```diff
@@ -9129,12 +9127,18 @@ private ExpressionSyntax ParseSubExpressionCore(Precedence precedence)
...
+        private ExpressionSyntax ParseExpressionContinued(ExpressionSyntax leftOperand, Precedence precedence)
+        {
             while (true)
             {
                 // We either have a binary or assignment operator here, or we're finished.
-                tk = this.CurrentToken.ContextualKind;
+                var tk = this.CurrentToken.ContextualKind;
 
                 bool isAssignmentOperator = false;
+                SyntaxKind opKind = leftOperand.Kind;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: >SyntaxKind opKind = leftOperand.Kind; [](start = 16, length = 37)

It looks like the local is initialized, but the initial value is never used.

File: src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs [hunk 4]
```diff
@@ -6870,5 +6870,575 @@ public void ExtraCommaInPropertyPattern()
...
+                }
+                N(SyntaxKind.CloseBraceToken);
+            }
+            EOF();
+        }
+
+        [Fact]
+        public void SwitchExpressionPrecedence_02()
+        {
+            // The left-hand-side of a switch is a relational, so `b` ends up on the left and the `a ==` expression has a switch on the right.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs]: >The left-hand-side of a switch is a relational [](start = 15, length = 46)

The previous unit-test uses the same reason, but the syntax tree is structured very differently. Should the comment(s) be adjusted?

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1)

**Comment by gafter** [comment]
@AlekseyTs I have addressed your comments and rebased to dev16.0.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 5]
```diff
@@ -9210,46 +9216,45 @@ private ExpressionSyntax ParseSubExpressionCore(Precedence precedence)
                 {
                     leftOperand = ParseIsExpression(leftOperand, opToken);
                 }
-                else
+                else if (isAssignmentOperator)
                 {
-                    if (isAssignmentOperator)
+                    ExpressionSyntax rhs = opKind == SyntaxKind.SimpleAssignmentExpression && CurrentToken.Kind == SyntaxKind.RefKeyword
+                        ? rhs = CheckFeatureAvailability(ParsePossibleRefExpression(), MessageID.IDS_FeatureRefReassignment)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: >rhs =  [](start = 26, length = 6)

This was not changed in the PR, but why are we assigning to `rhs` in either branch?

File: src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs [hunk 6]
```diff
@@ -450,7 +450,9 @@ private PatternSyntax ParsePatternContinued(TypeSyntax type, bool whenIsKeyword)
                         // There is an ambiguity between a positional pattern `(` pattern `)`
                         // and a constant expression pattern that happens to be parenthesized.
                         // Per 2017-11-20 LDM we treat such syntax as a parenthesized expression always.
-                        return _syntaxFactory.ConstantPattern(_syntaxFactory.ParenthesizedExpression(openParenToken, cp.Expression, closeParenToken));
+                        ExpressionSyntax expression = _syntaxFactory.ParenthesizedExpression(openParenToken, cp.Expression, closeParenToken);
+                        expression = ParseExpressionContinued(expression, precedence);
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs]: This is the most important part of this bug fix.
