### PR TITLE
Optimize switch code generation with relational operators via balanced tree of tests

### LINKED ISSUE #12509: Produce efficient code for switching on float, double, or decimal
We should generate a decision tree for switching on values of real types (float, double, or decimal), using comparisons and binary search to narrow the input value to one of a select set of switched values.

### LINKED ISSUE #42054: Optimize switch code generation with relational operators via tree
**Version Used**: https://github.com/dotnet/roslyn/tree/features/patterns3

**Steps to Reproduce**:

Look at the decompilation for the following code in sharplab:

```csharp
static class C {
    
    static LifeStage LifeStageAtAge(int age) => age switch
    {
        < 0 =>  LifeStage.Prenatal,
        < 2 =>  LifeStage.Infant,
        < 4 =>  LifeStage.Toddler,
        < 6 =>  LifeStage.EarlyChild,
        < 12 => LifeStage.MiddleChild,
        < 20 => LifeStage.Adolescent,
        < 40 => LifeStage.EarlyAdult,
        < 65 => LifeStage.MiddleAdult,
        _ =>    LifeStage.LateAdult,
    };
}

enum LifeStage
{
    Prenatal,
    Infant,
    Toddler,
    EarlyChild,
    MiddleChild,
    Adolescent,
    EarlyAdult,
    MiddleAdult,
    LateAdult,
}
```

decompiles to:

```csharp
internal static class C
{
    private static LifeStage LifeStageAtAge(int age)
    {
        if (age >= 0)
        {
            if (age >= 2)
            {
                if (age >= 4)
                {
                    if (age >= 6)
                    {
                        if (age >= 12)
                        {
                            if (age >= 20)
                            {
                                if (age >= 40)
                                {
                                    if (age < 65)
                                    {
                                        return LifeStage.MiddleAdult;
                                    }
                                    return LifeStage.LateAdult;
                                }
                                return LifeStage.EarlyAdult;
                            }
                            return LifeStage.Adolescent;
                        }
                        return LifeStage.MiddleChild;
                    }
                    return LifeStage.EarlyChild;
                }
                return LifeStage.Toddler;
            }
            return LifeStage.Infant;
        }
        return LifeStage.Prenatal;
    }
}
internal enum LifeStage
{
    Prenatal,
    Infant,
    Toddler,
    EarlyChild,
    MiddleChild,
    Adolescent,
    EarlyAdult,
    MiddleAdult,
    LateAdult
}
```

It could be made more efficient by creating a binary search tree, similar to what is done for strings:

```csharp
internal static class C
{
    private static LifeStage LifeStageAtAge(int age)
    {
        if (age < 12)
        {
            if (age < 4)
            {
                if (age < 2)
                {
                    if (age < 0)
                    {
                        return LifeStage.Prenatal;
                    }
                    else
                    {
                        return LifeStage.Infant;
                    }
                }
                else
                {
                    return LifeStage.Toddler;
                }
            }
            else
            {
                if (age < 6)
                {
                    return LifeStage.EarlyChild;
                }
                else
                {
                    return LifeStage.MiddleChild;
                }
            }
        }
        else
        {
            if (age < 40)
            {
                if (age < 20)
                {
                    return LifeStage.Adolescent;
                }
                else
                {
                    return LifeStage.EarlyAdult;
                }
            }
            else
            {
                if (age < 65)
                {
                    return LifeStage.MiddleAdult;
                }
                else
                {
                    return LifeStage.LateAdult;
                }
            }
        }
    }
}
internal enum LifeStage
{
    Prenatal,
    Infant,
    Toddler,
    EarlyChild,
    MiddleChild,
    Adolescent,
    EarlyAdult,
    MiddleAdult,
    LateAdult
}
```

### PR DESCRIPTION
**Pull request by gafter**
Also use a balanced tree of tests for sequences of float, double, and decimal constant patterns
Fixes #12509
Fixes #42054

Relates to https://github.com/dotnet/roslyn/issues/40727 (patterns for C# 9)

### CODE REVIEW

**Comment by gafter** [comment]
@agocke @RikkiGibson Could you please review this?

File: src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs [hunk 1]
```diff
@@ -611,6 +611,20 @@ public BoundObjectCreationExpression New(WellKnownMember wm, ImmutableArray<Boun
             var ctor = WellKnownMethod(wm, isOptional: false);
             return new BoundObjectCreationExpression(Syntax, ctor, binderOpt: null, args) { WasCompilerGenerated = true };
         }
+        public BoundExpression MakeIsNanTest(BoundExpression input)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs]: >IsNan [](start = 35, length = 5)

Perhaps "IsNaN".

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs [hunk 2]
```diff
@@ -410,53 +412,510 @@ private void GenerateTest(BoundExpression test, BoundDecisionDagNode whenTrue, B
...
+                    case BoundTestDecisionDagNode { WhenTrue: BoundTestDecisionDagNode test2 } test1:
+                        return CanDispatch(test1, test2);
+                    default:
+                        // Other cases are just as well done with a single test.
+                        return false;
+                }
+
+                bool CanDispatch(BoundTestDecisionDagNode test1, BoundTestDecisionDagNode test2)
+                {
+                    if (loweredNodes.Contains(test2))
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: >if (loweredNodes.Contains(test2)) [](start = 20, length = 33)

Can we remove this `Contains()` call from the RELEASE build, by asserting after the later call? For instance:
```C#
if (this._dagNodeLabels.ContainsKey(test2))
   return false;
Debug.Assert(!loweredNodes.Contains(test2));
```

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs [hunk 3]
```diff
@@ -410,53 +412,510 @@ private void GenerateTest(BoundExpression test, BoundDecisionDagNode whenTrue, B
...
+                        return false;
+                    var t1 = test1.Test;
+                    var t2 = test2.Test;
+                    if (!(t1 is BoundDagValueTest || t1 is BoundDagRelationalTest))
+                        return false;
+                    if (!(t2 is BoundDagValueTest || t2 is BoundDagRelationalTest))
+                        return false;
+                    if (!t1.Input.Equals(t2.Input))
+                        return false;
+                    return true;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: Perhaps `return t1.Input.Equals(t2.Input);`

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs [hunk 4]
```diff
@@ -410,53 +412,510 @@ private void GenerateTest(BoundExpression test, BoundDecisionDagNode whenTrue, B
...
-                     !loweredNodes.Contains(whenFalse) &&
-                     !this._dagNodeLabels.ContainsKey(whenFalse) &&
-                     firstTest.Input.Equals(secondTest.Input) &&
-                     firstTest.Input.Type.IsValidV6SwitchGoverningType()))
-                {
-                    // https://github.com/dotnet/roslyn/issues/12509 Could optimize float, double, decimal value switches. For now use if-then-else
+                if (!CanGenerateSwitchDispatch(node, loweredNodes))
                     return false;
+
+                var input = ((BoundTestDecisionDagNode)node).Test.Input;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: >var input = ((BoundTestDecisionDagNode)node).Test.Input; [](start = 16, length = 56)

Should `CanGenerateSwitchDispatch()` return this value?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs [hunk 5]
```diff
@@ -410,53 +412,510 @@ private void GenerateTest(BoundExpression test, BoundDecisionDagNode whenTrue, B
...
+                        return false;
+                    if (!(t2 is BoundDagValueTest || t2 is BoundDagRelationalTest))
+                        return false;
+                    if (!t1.Input.Equals(t2.Input))
+                        return false;
+                    return true;
+                }
+            }
+
+            private ValueDispatchNode GatherValueDispatchNodes(
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: >GatherValueDispatchNodes [](start = 38, length = 24)

It looks like this is only used in one location. Consider inlining.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs [hunk 6]
```diff
@@ -410,53 +412,510 @@ private void GenerateTest(BoundExpression test, BoundDecisionDagNode whenTrue, B
...
+                BoundDecisionDagNode node,
+                HashSet<BoundDecisionDagNode> loweredNodes,
+                BoundDagTemp input,
+                IValueSetFactory fac)
+            {
+                if (loweredNodes.Contains(node))
+                {
+                    bool foundLabel = this._dagNodeLabels.TryGetValue(node, out LabelSymbol label);
+                    Debug.Assert(foundLabel);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: >Debug.Assert(foundLabel); [](start = 20, length = 25)

Is there a chance we'll get here with `!foundLabel` in recursive call when `WhenTrue` or `WhenFalse` is not a `BoundTestDecisionDagNode`?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs (hunk 5 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: `fac` is an implementation detail I'd prefer to hide from the caller.

---
In reply to: [390492359](https://github.com/dotnet/roslyn/pull/42313#discussion_r390492359) [](ancestors = 390492359)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs (hunk 6 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: No.  If there were more than one path to a node it would have been assigned a label. Moreover, the decision dag is acyclic.

---
In reply to: [390511023](https://github.com/dotnet/roslyn/pull/42313#discussion_r390511023) [](ancestors = 390511023)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs (hunk 4 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: I could thread it through the two levels of calls but the savings are tiny and I'd rather keep things as simple as possible at this stage.

---
In reply to: [390489766](https://github.com/dotnet/roslyn/pull/42313#discussion_r390489766) [](ancestors = 390489766)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs [hunk 7]
```diff
@@ -410,53 +412,510 @@ private void GenerateTest(BoundExpression test, BoundDecisionDagNode whenTrue, B
...
 
-                // Gather up the (value, label) pairs, starting with the first one
-                var cases = ArrayBuilder<(ConstantValue value, LabelSymbol label)>.GetInstance();
-                cases.Add((value: firstTest.Value, label: GetDagNodeLabel(firstTestNode.WhenTrue)));
+                switch (otherwise)
+                {
+                    case ValueDispatchNode.LeafDispatchNode leaf:
+                        return new ValueDispatchNode.SwitchDispatch(syntax, cases, leaf.Label);
+                    case ValueDispatchNode.SwitchDispatch sd:
+                        return new ValueDispatchNode.SwitchDispatch(sd.Syntax, sd.Cases.Concat(cases), sd.Otherwise);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: >sd.Syntax [](start = 68, length = 9)

`syntax`?

Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: No.  The idea is to preserve the error location, for example, if `bool operator==(string, string)` is found to be missing.  The choice to use `sd.Syntax` instead of `syntax` is based on the behavior of tests, some of which would otherwise report the missing member on the whole switch expression's syntax rather than on just the constant pattern.

---
In reply to: [391109113](https://github.com/dotnet/roslyn/pull/42313#discussion_r391109113) [](ancestors = 391109113)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs (hunk 3 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: I found this slightly easier to debug.

---
In reply to: [390488282](https://github.com/dotnet/roslyn/pull/42313#discussion_r390488282) [](ancestors = 390488282)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs (hunk 2 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: Yes; good idea.

---
In reply to: [390484650](https://github.com/dotnet/roslyn/pull/42313#discussion_r390484650) [](ancestors = 390484650)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs (hunk 7 above)
Comment (alrz) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: In my opinion no error should be reported on the entire switch syntax if we're doing that for some other diagnostics, that doesn't seem to be helpful when it's highlighted in IDE. perhaps just the `switch` token?

Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: I do not believe there are any scenarios where do report an error on the entire switch syntax.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs [hunk 8]
```diff
@@ -410,53 +412,510 @@ private void GenerateTest(BoundExpression test, BoundDecisionDagNode whenTrue, B
...
+                protected virtual int Height => 1;
+                public readonly SyntaxNode Syntax;
+
+                public ValueDispatchNode(SyntaxNode syntax) => Syntax = syntax;
+
+                /// <summary>
+                /// A node representing the dispatch by value (equality). This corresponds to a classical C switch
+                /// statement, except that it also handles values of type float, double, decimal, and string.
+                /// </summary>
+                internal class SwitchDispatch : ValueDispatchNode
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: >internal class [](start = 16, length = 14)

Consider marking all derived types a `sealed`.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs [hunk 9]
```diff
@@ -410,53 +412,510 @@ private void GenerateTest(BoundExpression test, BoundDecisionDagNode whenTrue, B
...
+                        ConstantValueTypeDiscriminator.Decimal => true,
+                        ConstantValueTypeDiscriminator.Single => true,
+                        ConstantValueTypeDiscriminator.Double => true,
+                        _ => false
+                    });
+                    Debug.Assert(y.Discriminator == x.Discriminator);
+                    // Sort NaN values into the "highest" position so they fall naturally into the last bucket
+                    // when partitioned using less-than.
+                    return
+                        x.Discriminator != ConstantValueTypeDiscriminator.Decimal && double.IsNaN(x.DoubleValue) ? 1 :
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: >x.Discriminator != ConstantValueTypeDiscriminator.Decimal && double.IsNaN(x.DoubleValue) [](start = 24, length = 88)

Consider extracting a helper method.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs [hunk 10]
```diff
@@ -410,53 +412,510 @@ private void GenerateTest(BoundExpression test, BoundDecisionDagNode whenTrue, B
...
+                    private ValueDispatchNode Right { get; set; }
+                    private RelationalDispatch(SyntaxNode syntax, ConstantValue value, BinaryOperatorKind op, ValueDispatchNode left, ValueDispatchNode right) : base(syntax)
+                    {
+                        this.Value = value;
+                        this.Operator = op;
+                        WithLeftAndRight(left, right);
+                    }
+                    public ValueDispatchNode WhenTrue => IsReversed(Operator) ? Right : Left;
+                    public ValueDispatchNode WhenFalse => IsReversed(Operator) ? Left : Right;
+                    public override string ToString() => $"RelationalDispatch.{Height}({Left} {Operator.Operator()} {Value} {Right})";
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: >Operator.Operator() [](start = 95, length = 19)

There are a number of calls to `.Operator()` in this type, sometimes redundantly (such as some callers of `IsReversed()` and within `IsReversed()`). Consider asserting the `BinaryOperatorKind` is just the `Operator()` part and removing all the calls.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs [hunk 11]
```diff
@@ -410,53 +412,510 @@ private void GenerateTest(BoundExpression test, BoundDecisionDagNode whenTrue, B
...
+                    LowerValueDispatchNodeCore(rel.WhenTrue, input);
+                    _loweredDecisionDag.Add(_factory.Label(falseLabel));
+                    LowerValueDispatchNodeCore(rel.WhenFalse, input);
+                }
+            }
+
+            /// <summary>
+            /// A comparer for sorting cases containing values of type float, double, or decimal.
+            /// </summary>
+            private sealed class CasesComparer : IComparer
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: >IComparer [](start = 49, length = 9)

Could this be `IComparer<(ConstantValue, LabelSymbol)>` to avoid the casting?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs [hunk 12]
```diff
@@ -410,53 +412,510 @@ private void GenerateTest(BoundExpression test, BoundDecisionDagNode whenTrue, B
...
+                    var lessThanOrEqualOperator = input.Type.SpecialType switch
+                    {
+                        SpecialType.System_Single => BinaryOperatorKind.FloatLessThanOrEqual,
+                        SpecialType.System_Double => BinaryOperatorKind.DoubleLessThanOrEqual,
+                        SpecialType.System_Decimal => BinaryOperatorKind.DecimalLessThanOrEqual,
+                        _ => throw ExceptionUtilities.UnexpectedValue(input.Type.SpecialType)
+                    };
+
+                    var cases = node.Cases.ToArray();
+                    Array.Sort(cases, new CasesComparer(input.Type.SpecialType, lessThanOrEqualOperator));
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: `var cases = node.Cases.Sort(new CasesComparer(...));`

File: src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.NumericValueSet.cs [hunk 13]
```diff
@@ -135,13 +135,13 @@ static bool allInterval(Interval interval, BinaryOperatorKind relation, T value,
                                     return false;
                                 case GreaterThan when tc.Related(GreaterThan, minValue, value):
                                     return true;
-                                case LessThanOrEqual when tc.Related(LessThanOrEqual, value, minValue):
+                                case LessThanOrEqual when tc.Related(LessThan, value, minValue):
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.NumericValueSet.cs]: >LessThan [](start = 69, length = 8)

Is `OrEqual` not needed?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs [hunk 14]
```diff
@@ -3052,60 +3053,493 @@ private static void Test(decimal percent)
...
+      IL_004b:  stloc.0
+      IL_004c:  br.s       IL_004e
+      IL_004e:  ldloc.0
+      IL_004f:  ret
+    }
+");
+        }
+
+        [Fact]
+        public void RelationalFuzz_2020202_2_F()
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs]: >Fuzz_2020202_2_F [](start = 30, length = 16)

Consider renaming since fuzzing is not involved.

**Comment by gafter** [comment]
I suspect that the test failures are due to the modified compiler not correctly compiling switch statements, resulting in a misbehaving bootstrap compiler. I need to diagnose and fix that, but I'm putting it on the back burner in order to work on things needed to complete the feature far enough for integration.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs (hunk 10 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: It isn't just the operator part. Almost everywhere in this class it is the operator plus the type code. I will add some assertions to clarify that.

---
In reply to: [391910738](https://github.com/dotnet/roslyn/pull/42313#discussion_r391910738) [](ancestors = 391910738)

File: src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.NumericValueSet.cs (hunk 13 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.NumericValueSet.cs]: It would not be correct.  Consider a mixed interval [1..10] and a value of 1.  We don't know if all of the values in the interval are LessThanOrEqual to value.  If the interval contains only the number 1, then they are all LessThanOrEqual to the value and we should return true.  Otherwise we should return false.  So `tc.Related(LessThan, value, minValue)` would not be the correct test here to know if we should return false.

Which only goes to prove that this method and the corresponding `anyInterval` above are extremely subtle.  I added a bunch of tests to expose any off-by-one errors in these conditions.

---
In reply to: [392361775](https://github.com/dotnet/roslyn/pull/42313#discussion_r392361775) [](ancestors = 392361775)

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs (hunk 14 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs]: This was generated by the fuzz test with the parameters shown in the name.

---
In reply to: [392365148](https://github.com/dotnet/roslyn/pull/42313#discussion_r392365148) [](ancestors = 392365148)

**Comment by gafter** [comment]
@agocke @RikkiGibson @jcouv May I please have a second review of this?

**Comment by RikkiGibson** [comment]
Taking a look

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs [hunk 15]
```diff
@@ -410,53 +412,511 @@ private void GenerateTest(BoundExpression test, BoundDecisionDagNode whenTrue, B
...
+                /// Nodes of this kind are required to be height-balanced when constructed, so that when the full
+                /// decision tree is produced it generates a balanced tree of comparisons.
+                /// </summary>
+                internal sealed class RelationalDispatch : ValueDispatchNode
+                {
+                    private int _height;
+                    protected override int Height => _height;
+                    public readonly ConstantValue Value;
+                    public readonly BinaryOperatorKind Operator;
+                    /// <summary>The side of the test handling lower values. The true side for &lt; and &lt;=, the false side for > and >=.</summary>
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: we don't have to escape `>` in this context?

Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: As far as I can tell, no.  If there wasn't a preceding `<` to match it against, it is just treated as text.

File: src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.EnumeratedValueSetFactory.cs [hunk 16]
```diff
@@ -37,6 +37,13 @@ public IValueSet<T> Related(BinaryOperatorKind relation, T value)
             IValueSet IValueSetFactory.Related(BinaryOperatorKind relation, ConstantValue value) =>
                 value.IsBad ? EnumeratedValueSet<T, TTC>.AllValues : this.Related(relation, default(TTC).FromConstantValue(value));
 
+            bool IValueSetFactory.Related(BinaryOperatorKind relation, ConstantValue left, ConstantValue right)
+            {
+                Debug.Assert(relation == BinaryOperatorKind.Equal);
+                TTC tc = default;
+                return tc.FromConstantValue(left)!.Equals(tc.FromConstantValue(right));
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.EnumeratedValueSetFactory.cs]: Can we add a constraint so that we can avoid the suppression here?

File: src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs [hunk 17]
```diff
@@ -9718,5 +9718,1207 @@ .locals init (int V_0)
...
+      IL_01eb:  ldc.i4.3
+      IL_01ec:  stloc.0
+      IL_01ed:  br.s       IL_01f1
+      IL_01ef:  ldc.i4.0
+      IL_01f0:  stloc.0
+      IL_01f1:  ldloc.0
+      IL_01f2:  ret
+    }
+"
+            );
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs]: Verifying the IL is hard. Is there a way we could verify execution of different tests in some other way?
For example, could we define our own decimal type with custom operators that print out? Alternatively, we could include a Log operation in the `when` clauses?

File: src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.NumericValueSet.cs [hunk 18]
```diff
@@ -137,11 +137,11 @@ static bool allInterval(Interval interval, BinaryOperatorKind relation, T value,
                                     return true;
                                 case LessThanOrEqual when tc.Related(LessThan, value, minValue):
                                     return false;
-                                case LessThanOrEqual when tc.Related(LessThanOrEqual, maxValue, value):
+                                case LessThanOrEqual when tc.Related(LessThan, maxValue, value):
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.NumericValueSet.cs]: I remember that you had some direct tests on value set and value set factory. Could you add tests at that level for the changes here (ie. to test more directly)?

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 19]
```diff
@@ -1258,6 +1258,8 @@ void addSubpatternsForTuple(ImmutableArray<TypeWithAnnotations> elementTypes)
                         hasErrors = true;
                     }
                     break;
+                case BinaryOperatorKind.String:
+                case BinaryOperatorKind.Bool:
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: What test covers this change? I was looking for a test that would produce `ERR_UnsupportedTypeForRelationalPattern`.

File: src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs [hunk 20]
```diff
@@ -9718,5 +9718,1207 @@ .locals init (int V_0)
...
+        Console.WriteLine(M(27.1D));
+        Console.WriteLine(M(28.1D));
+        Console.WriteLine(M(29.1D));
+
+    }
+    static int M(double d)
+    {
+        return d switch
+        {
+            >= 27.1D and < 29.1D => 19,
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs]: nit: I am pretty confused by the numbering scheme, which seems random to my eyes. Why not just say `>= 27.1D and < 29.1D => 27`  (using one of the bounds as the identifier for the interval)?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs (hunk 14 above)
Comment (jcouv) [reply src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs]: This may be worth a comment in case we need to maintain this test

File: src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs [hunk 21]
```diff
@@ -9718,5 +9718,1207 @@ .locals init (int V_0)
...
+      IL_0066:  ldc.i4.2
+      IL_0067:  bge.un.s   IL_00a1
+      IL_0069:  br         IL_00ef
+      IL_006e:  ldarg.0
+      IL_006f:  ldc.i4.7
+      IL_0070:  blt.un.s   IL_008d
+      IL_0072:  ldarg.0
+      IL_0073:  ldc.i4.s   9
+      IL_0075:  sub
+      IL_0076:  switch    (
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs]: I didn't understand why we're producing a `switch` here for 9U, 10U, 11U and 12U, but we're not for 18U, 19U, 20U. Is there a minimum cap at 4 values?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs [hunk 22]
```diff
@@ -410,53 +412,511 @@ private void GenerateTest(BoundExpression test, BoundDecisionDagNode whenTrue, B
...
+                        return CanDispatch(test1, test2);
+                    default:
+                        // Other cases are just as well done with a single test.
+                        return false;
                 }
 
-                // Gather up the (value, label) pairs, starting with the first one
-                var cases = ArrayBuilder<(ConstantValue value, LabelSymbol label)>.GetInstance();
-                cases.Add((value: firstTest.Value, label: GetDagNodeLabel(firstTestNode.WhenTrue)));
+                bool CanDispatch(BoundTestDecisionDagNode test1, BoundTestDecisionDagNode test2)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: nit: we're using camelCase for local function (same as local variables)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs [hunk 23]
```diff
@@ -410,53 +412,511 @@ private void GenerateTest(BoundExpression test, BoundDecisionDagNode whenTrue, B
...
-                _loweredDecisionDag.Add(dispatch);
-                return true;
+                (ImmutableArray<(ConstantValue value, LabelSymbol label)> whenTrueCases, ImmutableArray<(ConstantValue value, LabelSymbol label)> whenFalseCases)
+                    splitCases(ImmutableArray<(ConstantValue value, LabelSymbol label)> cases, BinaryOperatorKind op, ConstantValue value)
+                {
+                    var whenTrueBuilder = ArrayBuilder<(ConstantValue value, LabelSymbol label)>.GetInstance();
+                    var whenFalseBuilder = ArrayBuilder<(ConstantValue value, LabelSymbol label)>.GetInstance();
+                    foreach (var pair in cases)
+                    {
+                        (fac.Related(op.Operator(), pair.value, value) ? whenTrueBuilder : whenFalseBuilder).Add(pair);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: nit: Consider extracting `op.Operator()` to a local

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs [hunk 24]
```diff
@@ -410,53 +412,511 @@ private void GenerateTest(BoundExpression test, BoundDecisionDagNode whenTrue, B
...
+                        this.Value = value;
+                        this.Operator = op;
+                        WithLeftAndRight(left, right);
+                    }
+                    public ValueDispatchNode WhenTrue => IsReversed(Operator) ? Right : Left;
+                    public ValueDispatchNode WhenFalse => IsReversed(Operator) ? Left : Right;
+                    public override string ToString() => $"RelationalDispatch.{Height}({Left} {Operator.Operator()} {Value} {Right})";
+                    private static bool IsReversed(BinaryOperatorKind op) => op.Operator() switch { BinaryOperatorKind.GreaterThan => true, BinaryOperatorKind.GreaterThanOrEqual => true, _ => false };
+
+                    private RelationalDispatch WithLeftAndRight(ValueDispatchNode left, ValueDispatchNode right)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: nit: Why call this method `With...` or return an instance, since it is destructive? Consider `void Update(...)`

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs [hunk 25]
```diff
@@ -410,53 +412,511 @@ private void GenerateTest(BoundExpression test, BoundDecisionDagNode whenTrue, B
...
+                    {
+                        Debug.Assert(op.OperandTypes() != 0);
+                        this.Value = value;
+                        this.Operator = op;
+                        WithLeftAndRight(left, right);
+                    }
+                    public ValueDispatchNode WhenTrue => IsReversed(Operator) ? Right : Left;
+                    public ValueDispatchNode WhenFalse => IsReversed(Operator) ? Left : Right;
+                    public override string ToString() => $"RelationalDispatch.{Height}({Left} {Operator.Operator()} {Value} {Right})";
+                    private static bool IsReversed(BinaryOperatorKind op) => op.Operator() switch { BinaryOperatorKind.GreaterThan => true, BinaryOperatorKind.GreaterThanOrEqual => true, _ => false };
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: nit:It may be worth a comment to explain why there is a distinction between Left/Right and WhenTrue/WhenFalse, and why we need both.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs [hunk 26]
```diff
@@ -410,53 +412,511 @@ private void GenerateTest(BoundExpression test, BoundDecisionDagNode whenTrue, B
...
+                    }
+
+                    return (whenTrueBuilder.ToImmutableAndFree(), whenFalseBuilder.ToImmutableAndFree());
+                }
+            }
+
+            /// <summary>
+            /// A node in a tree representing the form of a generated decision tree for classifying an input value.
+            /// </summary>
+            private abstract class ValueDispatchNode
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: nit: consider moving `ValueDispatchNode` to its own file.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs [hunk 27]
```diff
@@ -410,53 +412,511 @@ private void GenerateTest(BoundExpression test, BoundDecisionDagNode whenTrue, B
...
+                        #endregion Rebalance the top of the tree if necessary
+
+                        // that should have been sufficient to balance the tree.
+                        Debug.Assert(Math.Abs(left.Height - right.Height) < 2);
+                        return new RelationalDispatch(syntax, value, op, left: left, right: right);
+                    }
+                }
+            }
+
+            private void LowerValueDispatchNode(
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: nit: consider inlining `LowerValueDispatchNode` since it's simple, and its single caller is also simple. Then we can remove `Core` suffix from next method

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs [hunk 28]
```diff
@@ -410,53 +412,511 @@ private void GenerateTest(BoundExpression test, BoundDecisionDagNode whenTrue, B
...
+                }
+                else if (rel.WhenFalse is ValueDispatchNode.LeafDispatchNode whenFalse)
+                {
+                    LabelSymbol falseLabel = whenFalse.Label;
+                    _loweredDecisionDag.Add(_factory.ConditionalGoto(test, falseLabel, jumpIfTrue: false));
+                    LowerValueDispatchNodeCore(rel.WhenTrue, input);
+                }
+                else
+                {
+                    LabelSymbol falseLabel = _factory.GenerateLabel("sw");
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: nit: We've used more explicit label names in other places. Consider doing it here too. Same for "gt" label below in this file.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs [hunk 29]
```diff
@@ -410,53 +412,511 @@ private void GenerateTest(BoundExpression test, BoundDecisionDagNode whenTrue, B
...
+                if (!CanGenerateSwitchDispatch(node, loweredNodes))
                     return false;
+
+                var input = ((BoundTestDecisionDagNode)node).Test.Input;
+                ValueDispatchNode n = GatherValueDispatchNodes(node, loweredNodes, input);
+                LowerValueDispatchNode(n, input);
+                return true;
+            }
+
+            private bool CanGenerateSwitchDispatch(BoundDecisionDagNode node, HashSet<BoundDecisionDagNode> loweredNodes)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: nit: consider making this a local function (only used once)

File: src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.EnumeratedValueSetFactory.cs (hunk 16 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.EnumeratedValueSetFactory.cs]: We cannot add a struct constraint, because this is used for `string`.  But I can make this an assertion.

---
In reply to: [400457145](https://github.com/dotnet/roslyn/pull/42313#discussion_r400457145) [](ancestors = 400457145)

Comment (jcouv) [reply src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.EnumeratedValueSetFactory.cs]: Could we use a `notnull` constraint?

File: src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs (hunk 20 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs]: This test was automatically generated by the fuzz test  `PatternMatchingTests3.RelationalFuzz_01`.  The result numbering is in the order of the numbers the cases can match.

---
In reply to: [400466779](https://github.com/dotnet/roslyn/pull/42313#discussion_r400466779) [](ancestors = 400466779)

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs (hunk 19 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: `PatternMatchingTests3.Relational_01` (an existing test)

---
In reply to: [400464669](https://github.com/dotnet/roslyn/pull/42313#discussion_r400464669) [](ancestors = 400464669)

File: src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.NumericValueSet.cs (hunk 18 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.NumericValueSet.cs]: There are such tests included here, however all of this code is thrown away in [https://github.com/dotnet/roslyn/pull/42886](https://github.com/dotnet/roslyn/pull/42886)

---
In reply to: [400463170](https://github.com/dotnet/roslyn/pull/42313#discussion_r400463170) [](ancestors = 400463170)

File: src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs (hunk 21 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs]: This test was generated automatically by `PatternMatchingTests3.RelationalFuzz_01` and is used as an example of the quality of code generated for mixed relational and constant patterns.

---
In reply to: [400475069](https://github.com/dotnet/roslyn/pull/42313#discussion_r400475069) [](ancestors = 400475069)

Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs]: Oh, I understand what you were asking.  Yes, the code to emit switches uses direct tests for 3 values (and has for years)

---
In reply to: [400567926](https://github.com/dotnet/roslyn/pull/42313#discussion_r400567926) [](ancestors = 400567926,400475069)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs (hunk 24 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DecisionDagRewriter.cs]: Our convention is that `Update` is nondestructive too.  This would work either destructively or nondestructively.  It was originally nondestructive but then I noticed that the old node was always garbage after this was called (and that property is local to this class), so I made it destructive.

---
In reply to: [400510417](https://github.com/dotnet/roslyn/pull/42313#discussion_r400510417) [](ancestors = 400510417)

File: src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs (hunk 17 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs]: A `when` clause would prevent this machinery from kicking in, and would force things to be executed sequentially.
I think we have adequate tests for correctness, especially given the fuzz test `PatternMatchingTests3.RelationalFuzz_01`.
What is harder is verifying that the generated code uses *O(log N)* tests rather than *O(n)* tests.
However, I will add assertions to ValueDispatchNode that its height is less than *2 log N*, which is equivalent.

---
In reply to: [400461457](https://github.com/dotnet/roslyn/pull/42313#discussion_r400461457) [](ancestors = 400461457)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.DecisionDagRewriter.ValueDispatchNode.cs [hunk 30]
```diff
@@ -0,0 +1,256 @@
...
+                /// </summary>
+                internal sealed class LeafDispatchNode : ValueDispatchNode
+                {
+                    public readonly LabelSymbol Label;
+                    public LeafDispatchNode(SyntaxNode syntax, LabelSymbol Label) : base(syntax) => this.Label = Label;
+                    public override string ToString() => "Leaf";
+                }
+
+                /// <summary>
+                /// A node representing a dispatch based on a relational test of the input value by some constant.
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.DecisionDagRewriter.ValueDispatchNode.cs]: >A [](start = 20, length = 1)

I think this responds to the request for a comment explaining Left/Right/WhenTrue/WhenFalse.

File: src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.EnumeratedValueSetFactory.cs (hunk 16 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.EnumeratedValueSetFactory.cs]: Yes.

---
In reply to: [400558934](https://github.com/dotnet/roslyn/pull/42313#discussion_r400558934) [](ancestors = 400558934)

File: src/Compilers/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.csproj [hunk 31]
```diff
@@ -66,4 +66,8 @@
     <InternalsVisibleTo Include="CompilerBenchmarks" />
   </ItemGroup>
   <Import Project="..\CSharpAnalyzerDriver\CSharpAnalyzerDriver.projitems" Label="Shared" />
+  <ItemGroup>
+    <ExpectedCompile Remove="Lowering\LocalRewriter\LocalRewriter.DecisionDagRewriter.ValueDispatchNode.cs" />
```
[the remark this answers is not in the document]
Comment (gafter) [reply src/Compilers/CSharp/Portable/Microsoft.CodeAnalysis.CSharp.csproj:70]: Ask Visual Studio.  All I did was invoke "Move class to new file".
