### PR TITLE
Handle exception during teardown

### LINKED ISSUE #46724: Flaky test `AnalyzerInconsistencyShouldShutdown`
Microsoft.CodeAnalysis.CompilerServer.UnitTests.VBCSCompilerServerTests+MiscTests.AnalyzerInconsistencyShouldShutdown
```
Microsoft.CodeAnalysis.CompilerServer.UnitTests.VBCSCompilerServerTests+MiscTests.AnalyzerInconsistencyShouldShutdown

System.AggregateException : One or more errors occurred.
---- System.AggregateException : One or more errors occurred.
-------- System.ObjectDisposedException : Safe handle has been closed

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.CodeAnalysis.CompilerServer.UnitTests.ServerData.Dispose() in C:\Users\rikki\src\roslyn\src\Compilers\Server\VBCSCompilerTests\ServerUtil.cs:line 88
   at Microsoft.CodeAnalysis.CompilerServer.UnitTests.VBCSCompilerServerTests.MiscTests.<AnalyzerInconsistencyShouldShutdown>d__1.MoveNext() in C:\Users\rikki\src\roslyn\src\Compilers\Server\VBCSCompilerTests\VBCSCompilerServerTests.cs:line 369
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.Cancel()
   at Microsoft.CodeAnalysis.CompilerServer.NamedPipeClientConnectionHost.EndListening() in C:\Users\rikki\src\roslyn\src\Compilers\Server\VBCSCompiler\NamedPipeClientConnectionHost.cs:line 97
   at Microsoft.CodeAnalysis.CompilerServer.ServerDispatcher.ListenAndDispatchConnections(Nullable`1 keepAlive, CancellationToken cancellationToken) in C:\Users\rikki\src\roslyn\src\Compilers\Server\VBCSCompiler\ServerDispatcher.cs:line 102
   at Microsoft.CodeAnalysis.CompilerServer.BuildServerController.RunServer(String pipeName, ICompilerServerHost compilerServerHost, IClientConnectionHost clientConnectionHost, IDiagnosticListener listener, Nullable`1 keepAlive, CancellationToken cancellationToken) in C:\Users\rikki\src\roslyn\src\Compilers\Server\VBCSCompiler\BuildServerController.cs:line 143
   at Microsoft.CodeAnalysis.CompilerServer.BuildServerController.CreateAndRunServer(String pipeName, ICompilerServerHost compilerServerHost, IClientConnectionHost clientConnectionHost, IDiagnosticListener listener, Nullable`1 keepAlive, NameValueCollection appSettings, CancellationToken cancellationToken) in C:\Users\rikki\src\roslyn\src\Compilers\Server\VBCSCompiler\BuildServerController.cs:line 159
   at Microsoft.CodeAnalysis.CompilerServer.UnitTests.ServerUtil.<>c__DisplayClass8_0.<CreateServer>b__0() in C:\Users\rikki\src\roslyn\src\Compilers\Server\VBCSCompilerTests\ServerUtil.cs:line 127
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.CompilerServer.UnitTests.VBCSCompilerServerTests.MiscTests.<AnalyzerInconsistencyShouldShutdown>d__1.MoveNext() in C:\Users\rikki\src\roslyn\src\Compilers\Server\VBCSCompilerTests\VBCSCompilerServerTests.cs:line 367
----- Inner Stack Trace -----
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.Win32.UnsafeNativeMethods.CancelIoEx(SafeHandle handle, NativeOverlapped* lpOverlapped)
   at System.IO.Pipes.IOCancellationHelper.Cancel()
   at System.Threading.CancellationToken.ActionToActionObjShunt(Object obj)
   at System.Threading.CancellationCallbackInfo.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationCallbackInfo.ExecuteCallback()
   at System.Threading.CancellationTokenSource.CancellationCallbackCoreWork(CancellationCallbackCoreWorkArguments args)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
```

FYI @jaredpar

### PR DESCRIPTION
**Pull request by jaredpar**
The `CancellationTokenSource.Cancel` method can throw and that needs to
be accounted for. This exception is not coming from our code but rather
it's coming from the framework code. It is attempting to access a
disposed handle when cancellation IO operations and that results in an
unhandled exception.

This can't really be prevented on our part. We just need to handle it.

closes #46724

### CODE REVIEW

**Comment by jaredpar** [comment]
@dotnet/roslyn-compiler for flaky test fix review. Pretty straight forward.

File: src/Compilers/Server/VBCSCompiler/NamedPipeClientConnectionHost.cs [hunk 1]
```diff
@@ -94,7 +94,26 @@ public void EndListening()
...
+                // will try to cancel IO on a disposed SafeHandle. That causes an ObjectDisposedException
+                // to propagate out from the Cancel method here.
+                //
+                // There is no good way to guard against this hence we just have to accept it as a
+                // possible outcome.
+                _cancellationTokenSource.Cancel();
+            }
+            catch (Exception ex)
+            {
+                CompilerServerLogger.LogException(ex, $"Cancellation servers threw an exception");
```
Comment (RikkiGibson) [inline src/Compilers/Server/VBCSCompiler/NamedPipeClientConnectionHost.cs:114]: I'm confused by the wording "Cancellation servers threw an exception".

Comment (jaredpar) [reply src/Compilers/Server/VBCSCompiler/NamedPipeClientConnectionHost.cs]: Fixed :smile:

File: src/Compilers/Server/VBCSCompiler/NamedPipeClientConnectionHost.cs [hunk 2]
```diff
@@ -94,7 +94,26 @@ public void EndListening()
             Debug.Assert(_queue is object);
             Debug.Assert(_listenTasks is object);
 
-            _cancellationTokenSource.Cancel();
+            try
+            {
+                // Even though the Tasks created to run the compilation servers can never throw, 
+                // the CancellationToken from this source ends up getting passeed throughout the
```
Comment (cston) [inline src/Compilers/Server/VBCSCompiler/NamedPipeClientConnectionHost.cs:100]: >passeed [](start = 74, length = 7)

Typo

File: src/Compilers/Server/VBCSCompiler/NamedPipeClientConnectionHost.cs [hunk 3]
```diff
@@ -94,7 +94,26 @@ public void EndListening()
...
+                // named pipe infrastructure. Parts of that infrastructure hook into 
+                // CancellationToken.Register and those will throw during a Cancel operation. 
+                //
+                // Most notably of these is IOCancellationHelper.Cancel. This has a race where it
+                // will try to cancel IO on a disposed SafeHandle. That causes an ObjectDisposedException
+                // to propagate out from the Cancel method here.
+                //
+                // There is no good way to guard against this hence we just have to accept it as a
+                // possible outcome.
+                _cancellationTokenSource.Cancel();
```
Comment (sharwell) [inline src/Compilers/Server/VBCSCompiler/NamedPipeClientConnectionHost.cs:110]: ❔ Why not use `CancelAfter(0)` to run the cancellation continuations asynchronously?

Comment (jaredpar) [reply src/Compilers/Server/VBCSCompiler/NamedPipeClientConnectionHost.cs:110]: I would rather distinguish between the two scenarios:

1. `Cancel` throwing is generally indicative of a runtime bug. 
1. `WaitAll` throwing should never happen. That represents a bug in our code that needs immediate attention.

File: src/Compilers/Server/VBCSCompiler/NamedPipeClientConnectionHost.cs (hunk 2 above)
Comment (jaredpar) [reply src/Compilers/Server/VBCSCompiler/NamedPipeClientConnectionHost.cs:100]: Thanks. Will pick that up in the next change here. Merging now so  I can get rid of the flaky test.
