### PR TITLE
Fix regression in code fix service

### LINKED ISSUE #41116: Crash invoking quick actions
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/890186/crash-invoking-quick-actions.html)._

---
<p>[regression] [worked-in:Previous IntPreview]<br>
Attempting to click on a light bulb for a analyser fix crashes the process.</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/114730-quick-action-crash.gif"> Image:114730-quick-action-crash.gif</a></p><p><p>To repro:</p>
<ul>
<li>clone <a href="https://github.com/dotnet/winforms.git">https://github.com/dotnet/winforms.git</a> @ 96beeb0dab7f1c2596761072a165ace9901eb8f6</li>
<li>open in VS in Release mode</li>
<li>navigate to \winforms\src\System.Windows.Forms.Primitives\src\System\Windows\Forms\Message.cs</li>
<li>click on the light bulb for the Message to fix public API warning</li>
</ul>

---
#### Visual Studio Feedback System on 1/19/2020, 10:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### igveliko [MSFT] on 1/20/2020, 00:01 AM: 

<p>Here's a stack trace from EventViewer</p><pre>Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
   at System.Collections.Generic.SortedList`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Add(System.__Canon, System.__Canon)
   at Microsoft.CodeAnalysis.CodeFixes.CodeFixService+&lt;GetFixesAsync&gt;d__15.MoveNext()
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[[System.Collections.Immutable.ImmutableArray`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](System.Threading.Tasks.Task`1&lt;System.Collections.Immutable.ImmutableArray`1&lt;System.__Canon&gt;&gt;, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider+SuggestedActionsSource.GetCodeFixes(Microsoft.CodeAnalysis.Editor.Shared.ITextBufferSupportsFeatureService, Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet, Microsoft.CodeAnalysis.Workspace, Microsoft.CodeAnalysis.Document, Microsoft.VisualStudio.Text.SnapshotSpan, System.Func`2&lt;System.String,System.IDisposable&gt;, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider+SuggestedActionsSource.GetSuggestedActions(Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet, Microsoft.VisualStudio.Text.SnapshotSpan, Microsoft.VisualStudio.Utilities.IUIThreadOperationContext, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider+SuggestedActionsSource.GetSuggestedActions(Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet, Microsoft.VisualStudio.Text.SnapshotSpan, Microsoft.VisualStudio.Utilities.IUIThreadOperationContext)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbSession+&lt;&gt;c__DisplayClass40_0.&lt;TryGetSuggestedActionSets&gt;b__0(Microsoft.VisualStudio.Utilities.IUIThreadOperationContext)
   at Microsoft.VisualStudio.Editor.Implementation.VSUIThreadOperationExecutor.Execute(Microsoft.VisualStudio.Utilities.UIThreadOperationExecutionOptions, System.Action`1&lt;Microsoft.VisualStudio.Utilities.IUIThreadOperationContext&gt;)
   at Microsoft.VisualStudio.Editor.Implementation.VSUIThreadOperationExecutor.Execute(System.String, System.String, Boolean, Boolean, System.Action`1&lt;Microsoft.VisualStudio.Utilities.IUIThreadOperationContext&gt;)
   at Microsoft.VisualStudio.Text.Utilities.UIThreadOperationExecutor.Execute(System.String, System.String, Boolean, Boolean, System.Action`1&lt;Microsoft.VisualStudio.Utilities.IUIThreadOperationContext&gt;)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbSession.TryGetSuggestedActionSets(System.Collections.Generic.IEnumerable`1&lt;Microsoft.VisualStudio.Language.Intellisense.SuggestedActionSet&gt; ByRef, Microsoft.VisualStudio.Language.Intellisense.ISuggestedActionCategorySet)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulb.TransitionToExpandedState()
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulb.ChangeState(Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbState)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulb.&lt;OnSessionStateChanged&gt;b__37_0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
<br></pre>

#### Visual Studio Feedback System on 1/20/2020, 00:17 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by mavasani**
My recent change #40814 causes a crash in code fix service when there are duplicate diagnostics with same location and ID. This change adds a unit test to verify the regression and fixes the crash by using a SortedSet with a comparer.

Fixes #41116

### CODE REVIEW

File: src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs [hunk 1]
```diff
@@ -171,8 +174,8 @@ public async Task<ImmutableArray<CodeFixCollection>> GetFixesAsync(Document docu
 
                 cancellationToken.ThrowIfCancellationRequested();
 
-                aggregatedDiagnostics ??= new SortedDictionary<TextSpan, SortedList<string, DiagnosticData>>();
-                aggregatedDiagnostics.GetOrAdd(diagnostic.GetTextSpan(), _ => new SortedList<DiagnosticId, DiagnosticData>()).Add(diagnostic.Id, diagnostic);
+                aggregatedDiagnostics ??= new SortedDictionary<TextSpan, SortedSet<DiagnosticData>>();
+                aggregatedDiagnostics.GetOrAdd(diagnostic.GetTextSpan(), _ => new SortedSet<DiagnosticData>(s_diagnosticDataComparerById)).Add(diagnostic);
```
Comment (sharwell) [inline src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs]: ❗️ This will silently discard diagnostics that occur and the same location with the same ID.

Comment (mavasani) [reply src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs]: I just found the same and wrote a unit test for it :-). Will push a commit soon.

Comment (mavasani) [reply src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs]: Expanded the added unit test, so that the newly added assert fails with the prior fix, and succeeds with the modified fix.

File: src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs [hunk 2]
```diff
@@ -174,15 +174,21 @@ public async Task<ImmutableArray<CodeFixCollection>> GetFixesAsync(Document docu
...
 
             if (aggregatedDiagnostics == null)
             {
                 return ImmutableArray<CodeFixCollection>.Empty;
             }
 
+            // Order diagnostics by DiagnosticId so the fixes are in a deterministic order.
+            foreach (var diagnosticsWithSpan in aggregatedDiagnostics.Values)
+            {
+                diagnosticsWithSpan.Sort(s_diagnosticDataComparisonById);
```
Comment (sharwell) [inline src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs]: `List<T>.Sort` is an unstable sort, so for cases of duplicate diagnostics at the same location, they could move around with each pass. It would be good to use LINQ's `OrderBy` for this operation, which is a stable sort.

Comment (sharwell) [inline src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs]: ❔ How often does this get called? Sorting with a `Comparison<T>` will cause an allocation with each pass (creating a `Comparer<T>` wrapping the `Comparison<T>`.

File: src/EditorFeatures/Test/CodeFixes/CodeFixServiceTests.cs [hunk 3]
```diff
@@ -8,6 +8,7 @@
 using System.Linq;
 using System.Threading;
 using System.Threading.Tasks;
+using ICSharpCode.Decompiler.IL;
```
Comment (sharwell) [inline src/EditorFeatures/Test/CodeFixes/CodeFixServiceTests.cs]: ❔ Was this intentional?

File: src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs (hunk 2 above)
Comment (mavasani) [reply src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs]: Hmm I am not sure what would be a desirable diagnostic/fix order for such duplicate diagnostics though. Do we even have code fixes that generate different code actions for such duplicate diagnostics? I doubt if we do. I am going to wait for a realistic use case for which a unit test can be written before making a change.

Comment (mavasani) [reply src/EditorFeatures/Core/Implementation/CodeFixes/CodeFixService.cs]: This will be invoked once for each `Ctrl + .` invocation, so I think we should be fine.

File: src/EditorFeatures/Test/CodeFixes/CodeFixServiceTests.cs (hunk 3 above)
Comment (mavasani) [reply src/EditorFeatures/Test/CodeFixes/CodeFixServiceTests.cs]: Nope
