### PR TITLE
Fix #9945: Check if dynamic property is set-only when dotting off it

### LINKED ISSUE #9945: CSC crashes (instead of emitting error CS0154) when dotting off a setter-only property of type dynamic
**Version Used**: 
VS2015 Update 2 RC

**Steps to Reproduce**:

Create a console app with the following code, and build it:

```cs
class Program
{
    static void Main()
    {
        I i = null;
        System.Type ts = i.s.GetType();  // compile-time error CS0154
        System.Type td = i.d.GetType();  // compile-time CRASH with error code -2146232797
    }

    public interface I
    {
        string s { set; }
        dynamic d { set; }
    }
}
```

**Expected Behavior**:

Both `GetType()` lines should emit CS0154 "property cannot be used in this context because it lacks a get accessor"

**Actual Behavior**:

The second `GetType()` line causes a compiler crash with

### PR DESCRIPTION
**Pull request by khyperia**
When a set-only property (whose type is dynamic) is accessed via another member access, CS0154 ("property cannot be used in this context because it lacks a get accessor") was not produced, and instead crashed during emit.

Ping @jaredpar @gafter for review.

### CODE REVIEW

**Comment by jaredpar** [comment]
@dotnet/roslyn-compiler

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 1]
```diff
@@ -1685,8 +1685,21 @@ internal bool CheckValueKind(BoundExpression expr, BindValueKind valueKind, Diag
                 case BoundKind.EventAccess:
                     return CheckEventValueKind((BoundEventAccess)expr, valueKind, diagnostics);
                 case BoundKind.DynamicMemberAccess:
+                    {
+                        // dynamic access needs to check if the source of the
+                        // dynamic object is from, for example, a set-only property
+                        var access = (BoundDynamicMemberAccess)expr;
+                        return CheckValueKind(access.Receiver, BindValueKind.RValue, diagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: It feels like this check is too late. I would expect it to be performed before BoundDynamicMemberAccess is created. Here we are supposed to check BoundDynamicMemberAccess itself

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 2]
```diff
@@ -1685,8 +1685,21 @@ internal bool CheckValueKind(BoundExpression expr, BindValueKind valueKind, Diag
...
+                    }
                 case BoundKind.DynamicIndexerAccess:
-                    return true;
+                    {
+                        var access = (BoundDynamicIndexerAccess)expr;
+                        if (access.ReceiverOpt != null)
+                        {
+                            return CheckValueKind(access.ReceiverOpt, BindValueKind.RValue, diagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: Same here

File: src/Compilers/CSharp/Test/Semantic/Semantics/DynamicTests.cs [hunk 3]
```diff
@@ -3434,6 +3434,33 @@ static void Main()
             CompileAndVerify(compilation2, expectedOutput: @"4");
         }
 
+        [Fact, WorkItem(9945, "https://github.com/dotnet/roslyn/issues/9945")]
+        public void DynamicGetOnlyProperty()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/DynamicTests.cs]: Two places in binding were modified, but it looks like this test covers only one of them.

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs (hunk 1 above)
Comment (VSadov) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: Yes. It seems the Value check on the receiver should happen in BindDynamicMemberAccess.
CheckValueKind for BoundDynamicMemberAccess should just return true - since we do not know until runtime.

**Comment by khyperia** [comment]
Updated from feedback. Aleksey's test comment is no longer relevant, only one line is now changed. Other comments addressed by moving the check to BindMemberAccessWithBoundLeft, which is where the same situation in the non-dynamic case is detected (very bottom of the method, only other place where CheckValue is called in that method).

Please re-review, thanks!

**Comment by jmarolf** [comment]
retest vsi please

**Comment by davkean** [comment]
retest roslyn_prtest_win_vsi0  please
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_vsi0/63/, looks like https://github.com/dotnet/roslyn/issues/10110.

**Comment by davkean** [comment]
retest vsi please

**Comment by gafter** [comment]
:+1:

**Comment by VSadov** [comment]
LGTM

File: src/Compilers/CSharp/Test/Semantic/Semantics/DynamicTests.cs [hunk 4]
```diff
@@ -3434,6 +3434,33 @@ static void Main()
...
+        {
+            string source = @"
+class Program
+{
+    static void Main()
+    {
+        I i = null;
+        System.Type t = i.d.GetType();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/DynamicTests.cs]: Please add a test for DynamicIndexerAccess
