### PR TITLE
Fix C# completion preselection for enums in expression-bodied members

### LINKED ISSUE #4310: No enum/new preselect in expression bodied property
nopreselect

:crying_cat_face:

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes #4310 

Reviewers: @CyrusNajmabadi, @Pilchie, @jasonmalinowski, @rchande, @dpoeschl, @balajikris, @jmarolf, @davkean, @brettfo

### CODE REVIEW

File: src/Workspaces/Core/Portable/Shared/Extensions/ObjectExtensions.TypeSwitch.cs [hunk 1]
```diff
@@ -7877,6 +7877,228 @@ internal static partial class ObjectExtensions
...
+           where TDerivedType33 : TBaseType
+           where TDerivedType34 : TBaseType
+           where TDerivedType35 : TBaseType
+           where TDerivedType36 : TBaseType
+           where TDerivedType37 : TBaseType
+           where TDerivedType38 : TBaseType
+           where TDerivedType39 : TBaseType
+           where TDerivedType40 : TBaseType
+           where TDerivedType41 : TBaseType
+           where TDerivedType42 : TBaseType
```
Comment (dpoeschl) [inline src/Workspaces/Core/Portable/Shared/Extensions/ObjectExtensions.TypeSwitch.cs]: :grin:

**Comment by dpoeschl** [comment]
:+1:

**Comment by Pilchie** [comment]
:+1:

**Comment by rchande** [comment]
:shipit:

File: src/Workspaces/Core/Portable/Shared/Extensions/ObjectExtensions.TypeSwitch.cs (hunk 1 above)
Comment (DustinCampbell) [inline src/Workspaces/Core/Portable/Shared/Extensions/ObjectExtensions.TypeSwitch.cs]: Good catch! I had even realized how this overload makes me one with the universe. :alien:

Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Shared/Extensions/ObjectExtensions.TypeSwitch.cs]: This code makes me feel bad about myself.  Can we get @MadsTorgersen to get a real TypeSwitch into the language asap! :)

**Comment by CyrusNajmabadi** [comment]
:+1:

File: src/Workspaces/Core/Portable/Shared/Extensions/ObjectExtensions.TypeSwitch.cs (hunk 1 above)
Comment (DustinCampbell) [inline src/Workspaces/Core/Portable/Shared/Extensions/ObjectExtensions.TypeSwitch.cs]: It makes me feel bad about you too. :smile:

**Comment by jasonmalinowski** [comment]
:+1:, other than that this checkin doesn't delete TypeSwitch. :smile:

File: src/Workspaces/Core/Portable/Shared/Extensions/ObjectExtensions.TypeSwitch.cs (hunk 1 above)
Comment (tmat) [inline src/Workspaces/Core/Portable/Shared/Extensions/ObjectExtensions.TypeSwitch.cs]: @CyrusNajmabadi Why don't we switch over SyntaxKind?

Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Shared/Extensions/ObjectExtensions.TypeSwitch.cs]: This code is clearer.  Callers don't need to switch on the kind and then cast the result.  They simply say what they want to handle. Perf hasn't been an issue with these yet.  So here they remain.  I'd love a real language type-switch though.  Maybe in C# 8.

Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Shared/Extensions/ObjectExtensions.TypeSwitch.cs]: SyntaxKind also has the other challenge that you have to know all the possible kinds for a type, which isn't always obvious at first. Our Syntax.xml specifies that, but it's hard to keep in sync.

Comment (DustinCampbell) [inline src/Workspaces/Core/Portable/Shared/Extensions/ObjectExtensions.TypeSwitch.cs]: Doesn't make this less of an abomination though. :imp:

Comment (tmat) [inline src/Workspaces/Core/Portable/Shared/Extensions/ObjectExtensions.TypeSwitch.cs]: Wouldn't it help to have another NodeKind enum that you can use in the switch and that corresponds 1:1 with the node types?

Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Shared/Extensions/ObjectExtensions.TypeSwitch.cs]: I'm not sure how that would be any better.  The code on the caller side would actually look worse.  You'd have to switch, and then cast all your variables.

Comment (tmat) [inline src/Workspaces/Core/Portable/Shared/Extensions/ObjectExtensions.TypeSwitch.cs]: It would look slightly worse but it wouldn't be that bad (just an extra cast), would not require these helpers and would be faster.

Comment (tmat) [inline src/Workspaces/Core/Portable/Shared/Extensions/ObjectExtensions.TypeSwitch.cs]: Something like:
```case NodeType.ArrowExpressionClause: return InferTypeInArrowExpressionClause((ArrowExpressionClauseSyntax)node);```

Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Shared/Extensions/ObjectExtensions.TypeSwitch.cs]: Yeah, ugly, and predicates on a NodeType that isn't there. Rather than implement that, you could just go implement type matching in the compiler. :smile:

Comment (tmat) [inline src/Workspaces/Core/Portable/Shared/Extensions/ObjectExtensions.TypeSwitch.cs]: It is what it is. Are we expecting customers to copy these type matching helpers?
