### PR TITLE
'this' keyword available in expression-bodied members

### LINKED ISSUE #725: 'this' keyword not available in expression-bodied members
Ported from TFS WorkItem: **1107414**

------------------------------

**Repro Steps:**

**Affected Branch:** <BR>**Affected Build:** <BR>**Affected Product Language:** <BR><BR>**Steps to reproduce:**<BR><BR>1. Create a new C# class library.

2. Add a new class like so:

&nbsp;

class C

{<BR>&nbsp;&nbsp;&nbsp; int p;<BR>}

&nbsp;

3. Try to add the following member to C:<BR><BR>&nbsp;&nbsp;&nbsp; int M() =&gt; this.p;

&nbsp;

**Expected**

'this' shows up in completion lists in the body of M.

&nbsp;

**Actual**

'this' does not show up in completion lists.

------------------------------

**Revisions:**

1) Created By Tom Meschter (1/13/2015 1:14:52 PM)

------------------------------

2) Edited By Kevin Pilch-Bisson (2/19/2015 3:31:45 PM)

Wow, let's port this to GitHub and try to fix it soon.

------------------------------

### PR DESCRIPTION
**Pull request by basoundr**
Fix #725 : 'this' keyword should be available in the completion list, in the
context of member expression body.

### CODE REVIEW

**Comment by basoundr** [comment]
@rchande Could you please take a look if things look ok here? Thanks :)

File: src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs [hunk 1]
```diff
@@ -1435,6 +1435,12 @@ public static bool IsInstanceContext(this SyntaxTree syntaxTree, int position, S
                 return IsInBlock(accessor.Body, position);
             }
 
+            var propertyDeclaration = containingMember as PropertyDeclarationSyntax;
```
Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs]: What about inside expression bodied methods?  Operators? etc?

File: src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs [hunk 2]
```diff
@@ -1435,6 +1435,12 @@ public static bool IsInstanceContext(this SyntaxTree syntaxTree, int position, S
...
+            if (propertyDeclaration != null)
+            {
+                return isAnyExpressionContext && propertyDeclaration.ExpressionBody.IsKind(SyntaxKind.ArrowExpressionClause);
```
Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs]: Do we have to check isExpressionContext here?  It isn't done above for regular methods and property accessors, which leads me to believe that it's the callers job to check if they are in an expression or not.

File: src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs (hunk 1 above)
Comment (balajikris) [inline src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs]: Correct. They could be methods, operators, conversions, indexers in addition to being properties. 
[see design notes on codeplex](https://roslyn.codeplex.com/discussions/540574)

File: src/EditorFeatures/CSharpTest/Recommendations/ThisKeywordRecommenderTests.cs [hunk 3]
```diff
@@ -526,5 +526,29 @@ void M()
...
+        [WorkItem(725)]
+        [WorkItem(1107414)]
+        [Fact, Trait(Traits.Feature, Traits.Features.KeywordRecommending)]
+        public void InExpressionBodiedMembers()
+        {
+            VerifyKeyword(@"
+class C
+{
+    int x;
+    int M => $$");
```
Comment (rchande) [inline src/EditorFeatures/CSharpTest/Recommendations/ThisKeywordRecommenderTests.cs]: Other types of members?

File: src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs [hunk 4]
```diff
@@ -1398,7 +1398,7 @@ public static bool IsGlobalStatementContext(this SyntaxTree syntaxTree, int posi
             return token.IsBeginningOfGlobalStatementContext();
         }
 
-        public static bool IsInstanceContext(this SyntaxTree syntaxTree, int position, SyntaxToken tokenOnLeftOfPosition, CancellationToken cancellationToken)
+        public static bool IsInstanceContext(this SyntaxTree syntaxTree, int position, SyntaxToken tokenOnLeftOfPosition, bool isAnyExpressionContext, CancellationToken cancellationToken)
```
Comment (rchande) [inline src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs]: Why does this have the "isAnyExpressionContext" parameter? If you detect that you're in a (not static) expression bodied member, it's automatically an expression, right?

File: src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs (hunk 2 above)
Comment (rchande) [inline src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs]: You can just check if you're inside the ExpressionBody of a Property/Method declaration.

File: src/EditorFeatures/CSharpTest/Recommendations/ThisKeywordRecommenderTests.cs (hunk 3 above)
Comment (basoundr) [inline src/EditorFeatures/CSharpTest/Recommendations/ThisKeywordRecommenderTests.cs]: I have added the missed out members in the new commit

File: src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs [hunk 5]
```diff
@@ -1438,6 +1443,33 @@ public static bool IsInstanceContext(this SyntaxTree syntaxTree, int position, S
...
+            {
+                switch (containingMember.Kind())
+                {
+                    case SyntaxKind.PropertyDeclaration:
+                        return ((PropertyDeclarationSyntax)containingMember).ExpressionBody;
+                    case SyntaxKind.MethodDeclaration:
+                        return ((MethodDeclarationSyntax)containingMember).ExpressionBody;
+                    case SyntaxKind.IndexerDeclaration:
+                        return ((IndexerDeclarationSyntax)containingMember).ExpressionBody;
+                    default:
```
Comment (VladimirReshetnikov) [inline src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs]: It also could be an OperatorDeclarationSyntax.

Comment (rchande) [inline src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs]: +1. Should probably make this work on all cases and make it a helper somewhere.

Comment (basoundr) [inline src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs]: Expression-Bodies are supported on both Operators and ConversionOperators as well but Operator and Conversion Operators are both static. 'this' keyword must not get listed here. 

If this is made a helper, this will need Constructor and Destructor Syntaxes as well for being MemberDeclarationSyntaxes. At that point we will have code which will never get run.

May be I can rename the method name from `GetExpressionBodyFromMember` to `GetExpressionBodyFromMemberForThisKeywordRecommendation`

File: src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs [hunk 6]
```diff
@@ -1438,6 +1443,33 @@ public static bool IsInstanceContext(this SyntaxTree syntaxTree, int position, S
...
+                        return null;
+                }
+            }
+
+            return null;
+        }
+
+        private static TextSpan ArrowExpressionClauseExpressionAdjustedSpan(ArrowExpressionClauseSyntax arrowExpressionClause)
```
Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs]: I don't like this name - adjusted for what?  This sounds like `InTrailingTrivia()` which we probably already have somewhere.

File: src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs (hunk 5 above)
Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs]: No, I think the proposal would be to move it to something like SyntaxNodeExtensions or SyntaxFacts and have it no care about the instance/static distinction.  It's generally useful to be able to get to the body of an expression bodied member regardless of member type.

File: src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs [hunk 7]
```diff
@@ -1422,6 +1421,12 @@ public static bool IsInstanceContext(this SyntaxTree syntaxTree, int position, S
                 return false;
             }
 
+            var expressionBody = GetExpressionBodyFromMember(containingMember);
+            if (expressionBody != null)
+            {
+                return ArrowExpressionClauseExpressionAdjustedSpan(expressionBody).IntersectsWith(position);
```
Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs]: This only handles at the very beginning of the expression bodied member.  Would a better check be to see if the token on the left is the =>?

Comment (rchande) [inline src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs]: I believe he's using the span to avoid having to walk up the tree.

Consider `int M => ((this.x + this.y) * $$)` -- you'd have to walk up the tree until you found an ExpressionSyntax that was the Expression child of the ArrowExpresionClause, no?

Comment (basoundr) [inline src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs]: @Pilchie Could you explain the scenario here? By adjusting the span I am making sure I cover all the legit span both in broken syntax and valid syntax

If I am using a check to look for the left token then we should some more logic to handle cases like `int M => 0 * $$`

File: src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs (hunk 6 above)
Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs]: Ah, missed that one of these was ArrowToken and the other was just arrowExpressionClause.

Maybe rename this to SpanOfExpressionBody or something?

File: src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs (hunk 7 above)
Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Extensions/ContextQuery/SyntaxTreeExtensions.cs]: I understand now, I misread the implementation of `ArrowExpressionClauseExpressionAdjustedSpan`.  With a different name I think this is fine.

**Comment by DustinCampbell** [comment]
Maybe add a negative unit test to assert that 'this' is *not* available after the semicolon of an expression-bodied member?

i.e. it shouldn't be available here:

int P => 42; $$

**Comment by basoundr** [comment]
@dotnet-bot retest this please

**Comment by basoundr** [comment]
@DustinCampbell @Pilchie @rchande @balajikris : I have addressed the comments. Please review the new commit. :)

File: src/EditorFeatures/CSharpTest/Recommendations/ThisKeywordRecommenderTests.cs [hunk 8]
```diff
@@ -526,5 +526,109 @@ void M()
     {
         var c = new C { x = 2, y = 3, $$");
         }
+
+        [WorkItem(725)]
```
Comment (rchande) [inline src/EditorFeatures/CSharpTest/Recommendations/ThisKeywordRecommenderTests.cs]: Can you use the overload that takes a string and include the GH URL?

**Comment by balajikris** [comment]
:+1:

File: src/EditorFeatures/CSharpTest/Recommendations/ThisKeywordRecommenderTests.cs [hunk 9]
```diff
@@ -526,5 +526,109 @@ void M()
...
+        [WorkItem(1107414)]
+        [Fact, Trait(Traits.Feature, Traits.Features.KeywordRecommending)]
+        public void InExpressionBodiedMembersProperty_1()
+        {
+            VerifyKeyword(@"
+class C
+{
+    int x;
+    int M => $$
```
Comment (rchande) [inline src/EditorFeatures/CSharpTest/Recommendations/ThisKeywordRecommenderTests.cs]: This test looks like it's the same as the previous one but with text after the caret. Can you check and see if the keyword recommender tests automatically try the test with the fill file and at the end of the file? If so, you can get rid of the above test.

File: src/EditorFeatures/CSharpTest/Recommendations/ThisKeywordRecommenderTests.cs [hunk 10]
```diff
@@ -526,5 +526,109 @@ void M()
...
+class C
+{
+    int x;
+    public static explicit operator F(C c1) => $$");
+        }
+
+        [WorkItem(725)]
+        [WorkItem(1107414)]
+        [Fact, Trait(Traits.Feature, Traits.Features.KeywordRecommending)]
+        public void NotInsideExpressionBodiedMember()
```
Comment (rchande) [inline src/EditorFeatures/CSharpTest/Recommendations/ThisKeywordRecommenderTests.cs]: Not *Outside* ExpresionBodiedMember?

**Comment by rchande** [comment]
:+1:

File: src/EditorFeatures/CSharpTest/Recommendations/ThisKeywordRecommenderTests.cs (hunk 9 above)
Comment (basoundr) [inline src/EditorFeatures/CSharpTest/Recommendations/ThisKeywordRecommenderTests.cs]: @rchande The `VerifyInFrontOfComment` seems to include a comment but I don't think the tests try to fill the file. In this particular case, the position could be inside a trivia belonging to the leading trivia of the `int` in the next line `int p;`

Comment (rchande) [inline src/EditorFeatures/CSharpTest/Recommendations/ThisKeywordRecommenderTests.cs]: Take look at [VerifyKeyword](http://source.roslyn.io/#Roslyn.Services.Editor.CSharp.UnitTests/Recommendations/RecommenderTests.cs,1e641d3761d586fb|VerifyKeyword). Given a file with the caret indicated, it will run the test 
a) with exactly the specified text and caret position
b) with the specified text, with a /* */ comment inserted before the caret position
c) with the specified text only up to the caret position
d) the above, with the keyword partially typed.

The test `InExpressionBodiedMembersProperty` duplicates the (c) part of `InExpressionBodiedMembersProperty_1`, so you can get rid of it.

Comment (basoundr) [inline src/EditorFeatures/CSharpTest/Recommendations/ThisKeywordRecommenderTests.cs]: I get it now. `VerifyAtEndOfFile` was not clear it meant (c)

**Comment by basoundr** [comment]
@dotnet-bot retest this please

**Comment by basoundr** [comment]
retest this please

**Comment by basoundr** [comment]
@dotnet-bot retest this please

**Comment by Pilchie** [comment]
:+1:
