### PR TITLE
Handle BoundSequence as an assignment target in CodeGenerator.EmitAssignmentExpression.

### LINKED ISSUE #2878: ExceptionUtilities.UnexpectedValue is thrown in Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitStore
```
Public Class Test
    Private _field As UInteger

    Shared Sub Main()
        Dim t as New Test()
        System.Console.WriteLine(t._field)
        t.EventHandler(-1).Wait()
        System.Console.WriteLine(t._field)
    End Sub

    Private Async Function EventHandler(args As Integer) As System.Threading.Tasks.Task
        Await RunAsync(Async Function()
                                   System.Console.WriteLine(args)
                                   _field += CUInt(1)
                       End Function)
    End Function

    Private Async Function RunAsync(x As System.Func(Of System.Threading.Tasks.Task)) As System.Threading.Tasks.Task
        Await x()
    End Function
End Class
```

Exception thrown: 'System.InvalidOperationException' in Microsoft.CodeAnalysis.VisualBasic.dll
```
>	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitStore(Microsoft.CodeAnalysis.VisualBasic.BoundExpression expression) Line 1879	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitAssignmentExpression(Microsoft.CodeAnalysis.VisualBasic.BoundAssignmentOperator assignmentOperator, Boolean used) Line 1619	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitExpression(Microsoft.CodeAnalysis.VisualBasic.BoundExpression expression, Boolean used) Line 37	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitSequenceExpression(Microsoft.CodeAnalysis.VisualBasic.BoundSequence sequence, Boolean used) Line 441	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitExpression(Microsoft.CodeAnalysis.VisualBasic.BoundExpression expression, Boolean used) Line 97	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitStatement(Microsoft.CodeAnalysis.VisualBasic.BoundStatement statement) Line 25	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitStatementAndCountInstructions(Microsoft.CodeAnalysis.VisualBasic.BoundStatement statement) Line 80	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitSequencePointStatement(Microsoft.CodeAnalysis.VisualBasic.BoundSequencePoint node) Line 242	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitStatement(Microsoft.CodeAnalysis.VisualBasic.BoundStatement statement) Line 19	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitBlock(Microsoft.CodeAnalysis.VisualBasic.BoundBlock scope) Line 1202	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitStatement(Microsoft.CodeAnalysis.VisualBasic.BoundStatement statement) Line 16	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitBlock(Microsoft.CodeAnalysis.VisualBasic.BoundBlock scope) Line 1202	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitTryStatement(Microsoft.CodeAnalysis.VisualBasic.BoundTryStatement statement, Boolean emitCatchesOnly) Line 129	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitStatement(Microsoft.CodeAnalysis.VisualBasic.BoundStatement statement) Line 53	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitBlock(Microsoft.CodeAnalysis.VisualBasic.BoundBlock scope) Line 1202	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.EmitStatement(Microsoft.CodeAnalysis.VisualBasic.BoundStatement statement) Line 16	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.GenerateImpl() Line 144	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.CodeGen.CodeGenerator.Generate(Integer asyncCatchHandlerOffset, System.Collections.Immutable.ImmutableArray(Of Integer) asyncYieldPoints, System.Collections.Immutable.ImmutableArray(Of Integer) asyncResumePoints) Line 94	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.GenerateMethodBody(Microsoft.CodeAnalysis.VisualBasic.Emit.PEModuleBuilder moduleBuilder, Microsoft.CodeAnalysis.VisualBasic.Symbols.MethodSymbol method, Integer methodOrdinal, Microsoft.CodeAnalysis.VisualBasic.BoundStatement block, System.Collections.Immutable.ImmutableArray(Of Microsoft.CodeAnalysis.CodeGen.LambdaDebugInfo) lambdaDebugInfo, System.Collections.Immutable.ImmutableArray(Of Microsoft.CodeAnalysis.CodeGen.ClosureDebugInfo) closureDebugInfo, Microsoft.CodeAnalysis.VisualBasic.StateMachineTypeSymbol stateMachineTypeOpt, Microsoft.CodeAnalysis.CodeGen.VariableSlotAllocator variableSlotAllocatorOpt, Microsoft.CodeAnalysis.CodeGen.DebugDocumentProvider debugDocumentProvider, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, Boolean generateDebugInfo) Line 1505	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileSynthesizedMethods(Microsoft.CodeAnalysis.VisualBasic.TypeCompilationState compilationState) Line 961	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileNamedType(Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbol symbol, System.Predicate(Of Microsoft.CodeAnalysis.VisualBasic.Symbol) filter) Line 746	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.<closure>.<lambda0>() Line 515	Basic
 	Microsoft.CodeAnalysis.dll!Roslyn.Utilities.UICultureUtilities.WithCurrentUICulture.AnonymousMethod__0() Line 136	C#
 	mscorlib.dll!System.Threading.Tasks.Task.Execute() Line 2498	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot) Line 2827	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution) Line 2756	C#
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 820	C#
```

Doesn't repro with /optimize+.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #2878.

@VSadov, @gafter, @agocke, @jaredpar Please review.

### CODE REVIEW

**Comment by agocke** [comment]
LGTM

File: src/Compilers/VisualBasic/Portable/CodeGen/EmitExpression.vb [hunk 1]
```diff
@@ -1793,6 +1788,23 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.CodeGen
...
+                        _builder.OpenLocalScope()
+
+                        For Each local In sequence.Locals
+                            Me.DefineLocal(local, sequence.Syntax)
+                        Next
+                    End If
+
+                    Me.EmitSideEffects(sequence.SideEffects)
+                    lhsUsesStack = EmitAssignmentPreamble(sequence.ValueOpt)
+
```
Comment (VSadov) [inline src/Compilers/VisualBasic/Portable/CodeGen/EmitExpression.vb]: Why is it not possible to release locals here?

Comment (VSadov) [inline src/Compilers/VisualBasic/Portable/CodeGen/EmitExpression.vb]: C# frees the locals here and it could be a bug in C#. If sequence returns a field of a struct temp declared on the sequence, we may reuse the temp by the time we do the actual store.
Looks like a possible bug in C#.

**Comment by VSadov** [comment]
LGTM
