### PR TITLE
Properly support indentation within text of XML doc comment on ENTER

### LINKED ISSUE #2108: Incorrect behavior of ENTER in XML documentation comment after indented text
**Repro Steps:**

* Enter the following code, and position the caret at the location indicated by `|`.
```C#
            /// <summary>
            ///     foo bar|
            /// </summary>
            public void Foo() { }
```

* Press Enter

**Expected Result:**
```C#
        /// <summary>
        ///     foo bar
        ///     |
        /// </summary>
        public void Foo() { }
```

**Actual Result:**
```C#
        /// <summary>
        ///     foo bar
        /// |
        /// </summary>
        public void Foo() { }
```

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes #2108

Reviewers: @CyrusNajmabadi, @Pilchie, @jasonmalinowski, @rchande, @dpoeschl, @balajikris, @jmarolf, @davkean, @brettfo

@sharwell may want to take a look too.

### CODE REVIEW

**Comment by sharwell** [comment]
I only reviewed the test cases. :+1: based on that.

File: src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs [hunk 1]
```diff
@@ -657,20 +658,39 @@ private void InsertExteriorTriviaIfNeeded(ITextView view, ITextBuffer subjectBuf
...
+            Debug.Assert(trimmedPreviousLine.StartsWith(ExteriorTriviaText), "Unexpected: previous line does not begin with doc comment exterior trivia.");
+
+            // skip exterior trivia.
+            trimmedPreviousLine = trimmedPreviousLine.Substring(3);
+
+            var firstNonWhitespaceOffsetInPreviousXmlText = trimmedPreviousLine.GetFirstNonWhitespaceOffset();
+
+            var extraIndent = firstNonWhitespaceOffsetInPreviousXmlText != null
+                ? trimmedPreviousLine.Substring(0, firstNonWhitespaceOffsetInPreviousXmlText.Value)
+                : " ";
```
Comment (Pilchie) [inline src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs]: It seems to me that instead of re-building this line from scratch, you could instead just copy the previous line up to the first comment character.

Up to you though.

**Comment by Pilchie** [comment]
:+1:

File: src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs (hunk 1 above)
Comment (DustinCampbell) [inline src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs]: Yeah, I thought about that would have slightly different behavior than Dev12. If I just copy the first bit of the previous line, we might not correctly use the current tab/spaces settings for the new line.

FWIW, now that I've spent time in this old code I'm consumed with the desire to rewrite the whole feature into something sensible.

File: src/EditorFeatures/CSharpTest/DocumentationComments/DocumentationCommentTests.cs [hunk 2]
```diff
@@ -1114,6 +1114,156 @@ void M()
...
+{
+    /// <summary>
+	///     hello world
+	///     $$
+    /// </summary>
+    void M()
+    {
+    }
+}";
+
```
Comment (davkean) [inline src/EditorFeatures/CSharpTest/DocumentationComments/DocumentationCommentTests.cs]: From a test standpoint (I can't talk from code stand point), I'd love to see tests like:

``` XML
/// $$ <summary>
```
``` XML
///     
/// $$
```

Also I see code that (appears to me) to handle tab and whitespace but no tests around that. How do we usually handle that?

Comment (DustinCampbell) [inline src/EditorFeatures/CSharpTest/DocumentationComments/DocumentationCommentTests.cs]: I'm not sure I understand precisely what you mean from your example. There are loads of tests in this file and I'm pretty sure those simple cases are already covered. Or am I missing something? (I usually am :smile:)

Note that this very test is checking tabs and spaces. useTabs is specified below to ensure that particular option is set and the test contains whitespace with tabs and spaces.
