### PR TITLE
Generate Documentation - Dismiss session on caret move before generated proposal

### LINKED ISSUE #83162: XML document comment generation dots aren't dismissing on cursor move
https://github.com/user-attachments/assets/0ccf4589-907c-4bbd-b41f-e73c1538d90d

**Steps to Reproduce**:

1. Create a new XML doc comment block.
2. While it's still thinking, move your cursor.

**Expected Behavior**: the dots dismiss, since I'm clearly not waiting at this point
**Actual Behavior**: the dots start following me around

### PR DESCRIPTION
**Pull request by akhera99**
Fixes: https://github.com/dotnet/roslyn/issues/83162

### CODE REVIEW

File: src/EditorFeatures/Core/DocumentationComments/DocumentationCommentSuggestion.cs [hunk 1]
```diff
@@ -62,6 +62,13 @@ public override async Task OnProposalUpdatedAsync(SuggestionSessionBase session,
             Logger.Log(FunctionId.Copilot_Generate_Documentation_Diverged, logLevel: LogLevel.Information);
             await session.DismissAsync(ReasonForDismiss.DismissedAfterBufferChange, cancel).ConfigureAwait(false);
         }
+        // If the caret has moved and no proposal has been generated yet (still showing thinking dots),
+        // dismiss the session so the dots don't follow the caret around.
+        else if (originalProposal is null && reason == ReasonForUpdate.DivergedAfterCaretMove)
+        {
```
Comment (JoeRobich) [inline src/EditorFeatures/Core/DocumentationComments/DocumentationCommentSuggestion.cs]: nit: Move comments into `else if` block to keep it very obvious this is part of an `if..else`
```suggestion
        else if (originalProposal is null && reason == ReasonForUpdate.DivergedAfterCaretMove)
        {
            // The caret has moved and no proposal has been generated yet (still showing thinking dots),
            // dismiss the session so the dots don't follow the caret around.
```

**Review by JoeRobich — APPROVED** [review]
