### PR TITLE
correct text navigation in VB and C# strings

### LINKED ISSUE #551: Word selection doesn't work in VB string interpolation literals
`Console.WriteLine($"stuff before {1 + 2} stuff after")`

If you double-click on "before", "before" should be selected.  Instead "stuff before " is selected.

Note: this works as expected in C#.

### PR DESCRIPTION
**Pull request by brettfo**
Correct text navigation in VB and C# strings to match that of the old language service (i.e., VS 2013.)  Now when navigating inside of strings with Ctrl+LeftArrow, RightArrow the cursor will move on word/token boundaries and Ctrl+Delete, Backspace behave appropriately as well as double-click word selection.

Fixes #551.

### CODE REVIEW

**Comment by brettfo** [comment]
test this please

**Comment by brettfo** [comment]
Tagging @Pilchie @DustinCampbell @rchande @dpoeschl @jasonmalinowski @balajikris @basoundr as potential reviewers.

Also, it looks like Jenkins messed itself trying to build.  I'll keep trying periodically.

File: src/EditorFeatures/VisualBasic/TextStructureNavigation/TextStructureNavigatorProvider.vb [hunk 1]
```diff
@@ -41,19 +38,31 @@ Namespace Microsoft.CodeAnalysis.Editor.VisualBasic.TextStructureNavigation
...
+
+        Protected Overrides Function GetExtentOfWordFromToken(token As SyntaxToken, position As SnapshotPoint) As TextExtent
+            If token.Kind() = SyntaxKind.StringLiteralToken AndAlso position.Position = token.Span.End - 1 Then
+                ' Special case to treat the closing quote of a string literal as a separate token.  This allows the
+                ' cursor to stop during word navigation (Ctrl+LeftArrow, etc.) immediately before AND after the
+                ' closing quote, just like it did in VS2013 and like it currently does for interpolated strings.
+                Dim Span = New Span(position.Position, 1)
+                Return New TextExtent(New SnapshotSpan(position.Snapshot, Span), isSignificant:=True)
+            Else
+                Return MyBase.GetExtentOfWordFromToken(token, position)
```
Comment (rchande) [inline src/EditorFeatures/VisualBasic/TextStructureNavigation/TextStructureNavigatorProvider.vb]: Since this (and the stringliteraltoken case of IsWithinNaturalLanguage) are essentially the same in C# and VB, is there a way we can just push this up into the base type?

**Comment by rchande** [comment]
:+1:

File: src/EditorFeatures/VisualBasic/TextStructureNavigation/TextStructureNavigatorProvider.vb (hunk 1 above)
Comment (brettfo) [inline src/EditorFeatures/VisualBasic/TextStructureNavigation/TextStructureNavigatorProvider.vb]: Since `(C#)SyntaxKind.StringLiteralToken != (VB)SyntaxKind.StringLiteralToken` I didn't see a clean way of doing this so I opted to keep them separate, but I could certainly be talked either way.

File: src/EditorFeatures/CSharp/TextStructureNavigation/TextStructureNavigatorProvider.cs [hunk 2]
```diff
@@ -34,9 +34,14 @@ protected override bool IsWithinNaturalLanguage(SyntaxToken token, int position)
             switch (token.Kind())
             {
                 case SyntaxKind.StringLiteralToken:
-                    // Before the " is considered outside the string
-                    // TODO: does this handle verbatim strings correctly?
-                    return position > token.SpanStart;
+                    // This, in combination with the override of GetExtentOfWordFromToken() below, treats the closing
+                    // quote as a separate token.  This maintains behavior with VS2013.
+                    if (position == token.Span.End - 1 && token.Text.EndsWith("\""))
```
Comment (jaredpar) [inline src/EditorFeatures/CSharp/TextStructureNavigation/TextStructureNavigatorProvider.cs]: Hmm, makes me want to have an overload of `EndsWith` that takes a `char`.

**Comment by jasonmalinowski** [comment]
Important test here: make sure you can Ctrl+Left arrow and Ctrl+Right arrow back and forth across the file. I'm sure you've already done that, but you really want to make sure you don't break that...

**Comment by brettfo** [comment]
@jasonmalinowski yep, that works. Truth be told I fiddled with it until I could navigate like I expected then I just made the tests pass to match.

File: src/EditorFeatures/CSharpTest/TextStructureNavigation/TextStructureNavigatorTests.cs [hunk 3]
```diff
@@ -254,7 +254,7 @@ public void String()
                 TestString,
                 pos: TestString.LastIndexOf('"'),
                 isSignificant: true,
-                start: startOfString + lengthOfStringIncludingQuotes - 1, length: 2);
+                start: startOfString + lengthOfStringIncludingQuotes - 1, length: 1);
 
             AssertExtent(
                 TestString,
```
Comment (Pilchie) [inline src/EditorFeatures/CSharpTest/TextStructureNavigation/TextStructureNavigatorTests.cs]: No new tests for C#?

**Comment by Pilchie** [comment]
:+1:

File: src/EditorFeatures/CSharpTest/TextStructureNavigation/TextStructureNavigatorTests.cs (hunk 3 above)
Comment (brettfo) [inline src/EditorFeatures/CSharpTest/TextStructureNavigation/TextStructureNavigatorTests.cs]: We already had tests for C# interpolated strings that were correct; only regular/raw strings needed to be updated to treat the closing quote as a single token.

File: src/EditorFeatures/CSharp/TextStructureNavigation/TextStructureNavigatorProvider.cs [hunk 4]
```diff
@@ -34,9 +35,14 @@ protected override bool IsWithinNaturalLanguage(SyntaxToken token, int position)
             switch (token.Kind())
             {
                 case SyntaxKind.StringLiteralToken:
-                    // Before the " is considered outside the string
-                    // TODO: does this handle verbatim strings correctly?
-                    return position > token.SpanStart;
+                    // This, in combination with the override of GetExtentOfWordFromToken() below, treats the closing
+                    // quote as a separate token.  This maintains behavior with VS2013.
+                    if (position == token.Span.End - 1 && token.Text.EndsWith("\"", StringComparison.Ordinal))
```
Comment (VladimirReshetnikov) [inline src/EditorFeatures/CSharp/TextStructureNavigation/TextStructureNavigatorProvider.cs]: Consider replacing with a single 'return'.

File: src/EditorFeatures/VisualBasic/TextStructureNavigation/TextStructureNavigatorProvider.vb [hunk 5]
```diff
@@ -28,12 +29,8 @@ Namespace Microsoft.CodeAnalysis.Editor.VisualBasic.TextStructureNavigation
...
                 Case SyntaxKind.StringLiteralToken
-
-                    ' Before the " is considered outside the string
-                    If position = token.SpanStart Then
-                        Return False
-                    End If
-
+                    ' This, in combination with the override of GetExtentOfWordFromToken() below, treats the closing
+                    ' quote as a separate token.  This maintains behavior with VS2013.
                     If position = token.Span.End AndAlso token.Text.EndsWith("""", StringComparison.Ordinal) Then
```
Comment (VladimirReshetnikov) [inline src/EditorFeatures/VisualBasic/TextStructureNavigation/TextStructureNavigatorProvider.vb]: Consider replacing with a single 'Return'.

File: src/EditorFeatures/CSharp/TextStructureNavigation/TextStructureNavigatorProvider.cs (hunk 4 above)
Comment (brettfo) [inline src/EditorFeatures/CSharp/TextStructureNavigation/TextStructureNavigatorProvider.cs]: I tried changing this to a single return statement but since the condition needed to be inverted it was difficult to read/understand, so for readability's sake I'm going to leave this.
