### PR TITLE
Remove naming styles before generating field/property/parameter in constructor related refactorings

### LINKED ISSUE #35775: Add parameters to constructor should respect naming style in new parameter name
**Steps to Reproduce**:

1. In tools | Options, add a naming rule to require `_` as a prefix for parameters
2. Enter this code in IDE:
```csharp
 class C
    {
        private int v;
        public C()
        {
        }
    }
```
3. Select the `v` in `private int v;` and Ctrl+.

**Expected Behavior**:
When selecting `Add Parameter to C()` it should offer to add 'int _v' as the parameter

**Actual Behavior**:
image

### LINKED ISSUE #35776: "Create and initialize field or property" from constructor parameter should remove naming styles from parameter before creating field/property name
**Steps to Reproduce**:

1.  In Tools|Options create a naming rule for parameters to begin with `param_` and another naming rule for fields to begin with `field_`
2. In IDE, enter this code
```csharp
class C
    {
        public C(int param_v)
        {
        }
    }
```
3. Place cursor on `param_v` and Ctrl+.

**Expected Behavior**:
Should offer to "Create and initialize field `field_v`"

**Actual Behavior**:
Offers to "Create and initialize field `field_param_v`
image

### LINKED ISSUE #36741: Parameters in "Generate Constructor" refactorings should adhere to naming styles
Parameters in "Generate Constructor" refactorings should adhere to naming styles

### PR DESCRIPTION
**Pull request by chborl**
Fixes #35776
Fixes #35775
Fixes #36741

### CODE REVIEW

**Comment by chborl** [comment]
Still need to add tests, but I think the code is complete.

File: src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs [hunk 1]
```diff
@@ -59,8 +60,12 @@ internal abstract partial class AbstractInitializeMemberFromParameterCodeRefacto
             // to an existing matching field/prop if we can find one, or add a new field/prop
             // if we can't.
 
+            var rules = await document.GetNamingRulesAsync(FallbackNamingRules.RefactoringMatchLookupRules, cancellationToken).ConfigureAwait(false);
+            var parameterNameMinusPrefixAndSuffix = NamingStyle.GetBaseName(parameter, rules);
+            var parameterWordParts = GetParameterWordParts(parameterNameMinusPrefixAndSuffix);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs]: i feel like it might be worthwhile to combine all of tihs into a helper struct.

File: src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs [hunk 2]
```diff
@@ -346,6 +346,34 @@ private string CreateCompliantNameReusingPartialPrefixesAndSuffixes(string name)
...
+
+            foreach (var rule in rules)
+            {
+                if (rule.SymbolSpecification.AppliesTo(symbol))
+                {
+                    // remove specified prefix
+                    var prefix = rule.NamingStyle.Prefix;
+                    baseName = baseName.StartsWith(prefix) ?
+                        baseName.Substring(prefix.Length) :
+                        baseName;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs]: IDE style is to have `?` and `:` at start of line if things are wrapped.

File: src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/InitializeParameter/AbstractInitializeMemberFromParameterCodeRefactoringProviderMemberCreation.cs]: that way this sort of common operation could be easily reapplied to other features taht might need it.

**Comment by chborl** [comment]
Added tests.

**Comment by chborl** [comment]
I added a new issue https://github.com/dotnet/roslyn/issues/36622 to address these comments:
> - feels like tehse these could all be extracted into a helper/extension somewhere.
> - i woudl expect to now have some instance methods tehn let you use this data (along with maybe stuff like rules/specifications) to build names you want.

**Comment by ryzngard** [comment]
> // Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project rot for license information.

woops

---
Refers to: src/EditorFeatures/TestUtilities/Diagnostics/NamingStyles/NamingStylesTestOptionSets.cs:1 in 9fcd4e8. [](commit_id = 9fcd4e8141caca75095016e64a66869885dbf870, deletion_comment = False)

File: src/Features/Core/Portable/Shared/Naming/IdentifierNameParts.cs [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+using Microsoft.CodeAnalysis.Text;
+
+namespace Microsoft.CodeAnalysis.Shared.Naming
+{
+    internal readonly struct IdentifierNameParts
+    {
+        public readonly string BaseName;
+        public readonly ImmutableArray<string> BaseNameParts;
+
+        public IdentifierNameParts(string baseName, ImmutableArray<string> baseNameParts)
```
Comment (ryzngard) [inline src/Features/Core/Portable/Shared/Naming/IdentifierNameParts.cs]: >IdentifierNameParts [](start = 15, length = 19)

This appears to only be used by the static functions, so make this private?

File: src/EditorFeatures/TestUtilities/Diagnostics/NamingStyles/NamingStylesTestOptionSets.cs [hunk 4]
```diff
@@ -39,6 +40,9 @@ public NamingStylesTestOptionSets(string languageName)
         public IDictionary<OptionKey, object> FieldNamesAreCamelCaseWithUnderscore =>
             Options(new OptionKey(SimplificationOptions.NamingPreferences, languageName), FieldNamesAreCamelCaseWithUnderscoreOption());
 
+        public IDictionary<OptionKey, object> FieldNamesAreCamelCaseBeginWithField_ =>
```
Comment (ryzngard) [inline src/EditorFeatures/TestUtilities/Diagnostics/NamingStyles/NamingStylesTestOptionSets.cs]: `_` at the end of the name is a little weird

**Comment by ryzngard** [comment]
@CyrusNajmabadi 	can you take another look at this? Would prefer your input before merging.

**Comment by chborl** [comment]
@sharwell @dpoeschl  for review.

File: src/Features/Core/Portable/Shared/Naming/IdentifierNameParts.cs [hunk 5]
```diff
@@ -0,0 +1,81 @@
...
+            newBaseName = NamingStyle.StripCommonPrefixes(newBaseName, out var _);
+
+            // If no changes were made to the basename passed in, we're done
+            if (newBaseName == baseName)
+            {
+                return baseName;
+            }
+
+            // otherwise, see if any other prefixes exist
+            return RemovePrefixesAndSuffixes(symbol, rules, newBaseName);
```
Comment (dpoeschl) [inline src/Features/Core/Portable/Shared/Naming/IdentifierNameParts.cs]: Are there tests that require this recursion? If I make a rule that has an `_` prefix and make a very long `_________________________________________________________________________________________` variable, will I blow up the stack? What if the final baseName is the empty string?

File: src/Features/Core/Portable/Shared/Naming/IdentifierNameParts.cs [hunk 6]
```diff
@@ -0,0 +1,81 @@
...
+            BaseName = baseName;
+            BaseNameParts = baseNameParts;
+        }
+
+        public static IdentifierNameParts GetIdentifierBaseName(ISymbol symbol, ImmutableArray<NamingRule> rules)
+        {
+            var baseName = RemovePrefixesAndSuffixes(symbol, rules, symbol.Name);
+
+            var parts = StringBreaker.GetWordParts(baseName);
+            var result = CreateWords(parts, baseName);
```
Comment (dpoeschl) [inline src/Features/Core/Portable/Shared/Naming/IdentifierNameParts.cs]: I was confused by the name `result` here... can you rename to `words` (or similar) or just inline the call?

File: src/Features/Core/Portable/Shared/Naming/IdentifierNameParts.cs [hunk 7]
```diff
@@ -0,0 +1,81 @@
...
+        {
+            BaseName = baseName;
+            BaseNameParts = baseNameParts;
+        }
+
+        public static IdentifierNameParts GetIdentifierBaseName(ISymbol symbol, ImmutableArray<NamingRule> rules)
+        {
+            var baseName = RemovePrefixesAndSuffixes(symbol, rules, symbol.Name);
+
+            var parts = StringBreaker.GetWordParts(baseName);
```
Comment (dpoeschl) [inline src/Features/Core/Portable/Shared/Naming/IdentifierNameParts.cs]: There's also technically the concept of a rule-specific word-separator character. But I think `StringBreaker` handles `_` correctly which is pretty much the only reasonable such character, so this is probably fine.

Comment (chborl) [reply src/Features/Core/Portable/Shared/Naming/IdentifierNameParts.cs]: I also considered that and came to the same conclusion.  If we get requests to handle other characters for string breakers we can do so, but it seems unlikely.

File: src/Features/Core/Portable/Shared/Naming/IdentifierNameParts.cs (hunk 5 above)
Comment (chborl) [reply src/Features/Core/Portable/Shared/Naming/IdentifierNameParts.cs]: I added a test for the recursion.

File: src/Features/Core/Portable/GenerateFromMembers/AbstractGenerateFromMembersCodeRefactoringProvider.cs [hunk 8]
```diff
@@ -116,12 +118,16 @@ private static bool IsViableProperty(IPropertySymbol property)
                     ? ((IFieldSymbol)symbol).Type
                     : ((IPropertySymbol)symbol).Type;
 
+                var identifierNameParts = IdentifierNameParts.GetIdentifierBaseName(symbol, rules);
+                var parameterNamingRule = rules.Where(rule => rule.SymbolSpecification.AppliesTo(SymbolKind.Parameter, Accessibility.NotApplicable)).First();
+                var parameterName = parameterNamingRule.NamingStyle.MakeCompliant(identifierNameParts.BaseName).First();
```
[the remark this answers is not in the document]
Comment (chborl) [reply src/Features/Core/Portable/GenerateFromMembers/AbstractGenerateFromMembersCodeRefactoringProvider.cs]: I updated the code to handle empty base names (not offer to create a field or parameter if the base is empty) and added tests.

File: src/Features/Core/Portable/Shared/Naming/IdentifierNameParts.cs (hunk 6 above)
Comment (chborl) [reply src/Features/Core/Portable/Shared/Naming/IdentifierNameParts.cs]: fixed

File: src/Features/Core/Portable/Shared/Naming/IdentifierNameParts.cs [hunk 9]
```diff
@@ -0,0 +1,81 @@
...
+        public readonly string BaseName;
+        public readonly ImmutableArray<string> BaseNameParts;
+
+        public IdentifierNameParts(string baseName, ImmutableArray<string> baseNameParts)
+        {
+            BaseName = baseName;
+            BaseNameParts = baseNameParts;
+        }
+
+        public static IdentifierNameParts GetIdentifierBaseName(ISymbol symbol, ImmutableArray<NamingRule> rules)
```
[the remark this answers is not in the document]
Comment (chborl) [reply src/Features/Core/Portable/Shared/Naming/IdentifierNameParts.cs]: fixed
