### PR TITLE
Avoid optimizing goto in SyntheticBoundNodeFactory.Switch()

### LINKED ISSUE #33542: One of our projects fails to build with: "csc.exe" exited with code -2146232797
I don't have any idea why this would happen, this used to build on everything except Visual Studio 2019 Preview 2, preview 1.1 worked.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/434543/one-of-our-projects-fails-to-build-with-cscexe-exi.html
VSTS ticketId: 776735_
_These are the original issue comments:_

tstedel on 1/31/2019, 05:49 PM (19 days ago): <p>Still does this in preview 2.1. It hangs for a very long time and then doesn't build.</p><p>1&gt;------ Build started: Project: POS_Connector.Core, Configuration: Debug Any CPU ------<br>1&gt;C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets(52,5): error MSB6006: "csc.exe" exited with code -2146232797.<br>========== Build: 0 succeeded, 1 failed, 3 up-to-date, 0 skipped ==========</p><p><strong></strong><u></u><sub></sub><sup></sup></p>

tstedel on 1/31/2019, 06:41 PM (19 days ago): <pre>using System.Threading.Tasks;
namespace ConsoleApp6
\{
    class Program
    \{
        static async Task Main(string[] args)
        \{
            try
            \{
                try
                \{
                    return;
                }
                finally
                \{
                    await Task.CompletedTask;
                }
            }
            catch \{ }
            finally
            \{
                await Task.CompletedTask;
            }
        }
    }
}</pre>

tstedel on 1/31/2019, 06:42 PM (19 days ago): <p>What I just posted is the minimum necessary to reproduce this issue</p>

_These are the original issue solutions:_
(no solutions)

### LINKED ISSUE #34720: Roslyn compiler fails on compiling for>using>try>finally>await
**Version Used**: 
Windows 10.0.17763 Pro
Visual Studio 2017 Pro
Docker version 18.09.2, build 6247962

**Steps to Reproduce**:

1. Create NET.Core console app project with following code 

```
using System.IO;
using System.Threading.Tasks;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            
        }
    }

    public class CompilerFail
    {
        private async Task AsyncMethod()
        {
            for (var i = 0; i < 5; i++)
            {
                using (var wc = new MemoryStream())
                {
                    try
                    {
                        continue;
                    }
                    finally
                    {
                        await Task.Delay(1);
                    }
                }
            }
        }
    }
}
```
2. Create build docker file:
```
FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build-env
WORKDIR /app

COPY ConsoleApp/ConsoleApp.csproj ./ConsoleApp/

RUN dotnet restore ConsoleApp/ConsoleApp.csproj

COPY ConsoleApp ./ConsoleApp 

RUN dotnet publish -c Release -o /app/out ./ConsoleApp/ConsoleApp.csproj
```
3. Run build in docker 
```
docker build .
```

**Expected Behavior**:
Project is built

**Actual Behavior**:
```
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error : FailFast: [/app/ConsoleApp/ConsoleApp.csproj]
p/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CodeGen.ILOpCodeExtensions.GetLeaveOpcode(ILOpCode opcode) [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.BasicBlock.RewriteBranchesAcrossExceptionHandlers() [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.RewriteBranchesAcrossExceptionHandlers() [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.RealizeBlocks() [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.Realize() [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.GenerateImpl() [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.Generate(Int32& asyncCatchHandlerOffset, ImmutableArray`1& asyncYieldPoints, ImmutableArray`1& asyncResumePoints) [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol method, Int32 methodOrdinal, BoundStatement block, ImmutableArray`1 lambdaDebugInfo, ImmutableArray`1 closureDebugInfo, StateMachineTypeSymbol stateMachineTypeOpt, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, DebugDocumentProvider debugDocumentProvider, ImportChain importChainOpt, Boolean emittingPdb, Boolean emitTestCoverageData, ImmutableArray`1 dynamicAnalysisSpans) [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileSynthesizedMethods(TypeCompilationState compilationState) [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass21_0.<CompileNamedTypeAsTask>b__0() [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :  [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at System.Environment.FailFast(System.String, System.Exception) [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at System.Environment.FailFast(System.String, System.Exception) [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception) [/app/ConsoleApp/ConsoleApp.csproj/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.FatalError.Report(System.Exception, System.Action`1<System.Exception>) [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.FatalError.ReportUnlessCanceled(System.Exception) [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass21_0.<CompileNamedTypeAsTask>b__0() [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CodeGen.ILOpCodeExtensions.GetLeaveOpcode(System.Reflection.Metadata.ILOpCode) [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CodeGen.ILBuilder+BasicBlock.RewriteBranchesAcrossExceptionHandlers() [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.RewriteBranchesAcrossExceptionHandlers() [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.RealizeBlocks() [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.Realize() [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.GenerateImpl() [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.Generate(Int32 ByRef, System.Collections.Immutable.ImmutableArray`1<Int32> ByRef, System.Collections.Immutable.ImmutableArray`1<Int32> ByRef) [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.GenerateMethodBody(Microsoft.CodeAnalysis.CSharp.Emit.PEModuleBuilder, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Int32, Microsoft.CodeAnalysis.CSharp.BoundStatement, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CodeGen.LambdaDebugInfo>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CodeGen.ClosureDebugInfo>, Microsoft.CodeAnalysis.CSharp.StateMachineTypeSymbol, Microsoft.CodeAnalysis.CodeGen.VariableSlotAllocator, Microsoft.CodeAnalysis.DiagnosticBag, Microsoft.CodeAnalysis.CodeGen.DebugDocumentProvider, Microsoft.CodeAnalysis.CSharp.ImportChain, Boolean, Boolean, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CodeGen.SourceSpan>) [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileSynthesizedMethods(Microsoft.CodeAnalysis.CSharp.TypeCompilationState) [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol) [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass21_0.<CompileNamedTypeAsTask>b__0() [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Roslyn.Utilities.UICultureUtilities+<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef) [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at System.Threading.ThreadPoolWorkQueue.Dispatch() [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :  [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error : Exception details: [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error : System.InvalidOperationException: Unexpected value 'Beq' of type 'System.Reflection.Metadata.ILOpCode' [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CodeGen.ILOpCodeExtensions.GetLeaveOpcode(ILOpCode opcode) [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.BasicBlock.RewriteBranchesAcrossExceptionHandlers() [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.RewriteBranchesAcrossExceptionHandlers() [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.RealizeBlocks() [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CodeGen.ILBuilder.Realize() [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.GenerateImpl() [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.Generate(Int32& asyncCatchHandlerOffset, ImmutableArray`1& asyncYieldPoints, ImmutableArray`1& asyncResumePoints) [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol method, Int32 methodOrdinal, BoundStatement block, ImmutableArray`1 lambdaDebugInfo, ImmutableArray`1 closureDebugInfo, StateMachineTypeSymbol stateMachineTypeOpt, VariableSlotAllocator variableSlotAllocatorOpt, DiagnosticBag diagnostics, DebugDocumentProvider debugDocumentProvider, ImportChain importChainOpt, Boolean emittingPdb, Boolean emitTestCoverageData, ImmutableArray`1 dynamicAnalysisSpans) [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileSynthesizedMethods(TypeCompilationState compilationState) [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) [/app/ConsoleApp/ConsoleApp.csproj]
/usr/share/dotnet/sdk/2.2.202/Roslyn/Microsoft.CSharp.Core.targets(58,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass21_0.<CompileNamedTypeAsTask>b__0() [/app/ConsoleApp/ConsoleApp.csproj]
The command '/bin/sh -c dotnet publish -c Release -o /app/out ./ConsoleApp/ConsoleApp.csproj' returned a non-zero code: 1
```

### PR DESCRIPTION
**Pull request by cston**
`SyntheticBoundNodeFactory.Switch()` is used to generate synthesized switch statements for async rewriters, and the `goto` maybe a branch outside of the current `try` block, so merging a `Beq` + `Br` might result in a conditional branch outside of the block which is not supported in the code generator.

Fixes #33542 
Fixes #34720

### CODE REVIEW

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncLocalsTests.cs [hunk 1]
```diff
@@ -1295,8 +1291,7 @@ static void Main()
 }";
             var verifier = CompileAndVerify(text, options: TestOptions.UnsafeReleaseExe, expectedOutput: @"1", verify: Verification.Fails);
             verifier.VerifyIL("C.<F>d__0.System.Runtime.CompilerServices.IAsyncStateMachine.MoveNext()",
-@"
-{
+@"{
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncLocalsTests.cs]: Consider preserving original formatting. Here and below in similar situations

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncMainTests.cs [hunk 2]
```diff
@@ -1479,5 +1479,439 @@ static class Program {
...
+        {
+        }
+        finally
+        {
+            await Task.CompletedTask;
+        }
+    }
+}";
+            var comp = CreateCompilation(source, options: TestOptions.ReleaseExe.WithOptimizationLevel(OptimizationLevel.Release));
+            var verifier = CompileAndVerify(comp, expectedOutput: "");
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncMainTests.cs]: >expectedOutput: "" [](start = 50, length = 18)

Consider having adjusting the test scenario so that by looking at the output we could confirm that the behavior at runtime is what we expect. It is really hard to confirm that from the IL and will be even harder to confirm if IL would change in the future in some insignificant way.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncMainTests.cs [hunk 3]
```diff
@@ -1479,5 +1479,439 @@ static class Program {
...
+                finally
+                {
+                    await Task.Delay(1);
+                }
+            }
+        }
+    }
+}";
+            var comp = CreateCompilation(source, options: TestOptions.ReleaseExe.WithOptimizationLevel(OptimizationLevel.Release));
+            var verifier = CompileAndVerify(comp, expectedOutput: "");
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncMainTests.cs]: >expectedOutput: "" [](start = 50, length = 18)

Same suggestion

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 2)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncMainTests.cs (hunk 2 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncMainTests.cs]: I'd rather keep the test simple to ensure we hit the failing scenario.

---
In reply to: [272674792](https://github.com/dotnet/roslyn/pull/34791#discussion_r272674792) [](ancestors = 272674792)

File: src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs [hunk 4]
```diff
@@ -884,18 +884,9 @@ public BoundStatement Switch(BoundExpression ex, ImmutableArray<SyntheticSwitchS
             statements.Add(null); // placeholder at statements[0] for the dispatch
             foreach (var section in sections)
             {
-                LabelSymbol sectionLabel;
-                // If the section only contains a goto statement, use that label.
```
Comment (VSadov) [inline src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs]: IL generator should be able to do this optimization as a part of branch folding pass and it will check whether this is safe to do.
I assume most of the IL diffs are in Debug tests.

**Comment by gingters** [comment]
If that works and passes your CI builds, can you please additionally verify if that also fixes the compilation of our project ( https://github.com/thinktecture/relayserver/tree/2.2.0 ) where we have a try -> try -> finally -> await constellation that leads to probably the same error? Thanks.
