### PR TITLE
Fix ChangeNamespaceService to handle member access references

### LINKED ISSUE #37891: ChangeNamespaceService doesn't fix references in the form of member access
For example, when using refactoring to change namespace `NS1` to `NS2` in the code sample below, the reference `NS1.MyEnum.A` will not be changed to `NS2.MyEnum.A`

```cs
namespace NS
{
    public MyEnum
    {
        A,
        B,
        C,
    }
}

...

var x = NS.MyEnum.A;
```

### PR DESCRIPTION
**Pull request by genlu**
fix #37891

### CODE REVIEW

File: src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs [hunk 1]
```diff
@@ -194,6 +201,23 @@ protected override SyntaxList<MemberDeclarationSyntax> GetMemberDeclarationsInCo
             // The name will be resolved by adding proper import.
             old = @new = nameRef;
             return false;
+
+#nullable enable
```
Comment (mavasani) [inline src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs]: Just curious... Is this the general recommended way to enable nullable in the IDE layer? As in, use if for newly added methods even if the whole file is not nullable enabled?

File: src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs [hunk 2]
```diff
@@ -369,27 +393,27 @@ static bool ContainsNamespaceDeclaration(SyntaxNode node)
...
+                    case AliasQualifiedNameSyntax aliasQualifiedNameNode:
+                        return aliasQualifiedNameNode.Alias.Identifier.ValueText;
                 }
 
                 return null;
             }
         }
 
-        private static NameSyntax CreateNameSyntax(ImmutableArray<string> namespaceParts, string aliasQualifier, int index)
+        private static NameSyntax CreateNamespaceAsQualifiedName(ImmutableArray<string> namespaceParts, string aliasQualifier, int index)
```
Comment (mavasani) [inline src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs]: Change return type to `QualifiedNameSyntax`?

File: src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs (hunk 1 above)
Comment (jasonmalinowski) [reply src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs]: I would say the recommendation is to "nullable enable as much as you can get away with", but sometimes that's too big of an undertaking at once. I've totally done this in the VisualStudioWorkspace type because there's just a lot of code there, but I don't want to not annotate new code going forward.

File: src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs [hunk 3]
```diff
@@ -133,23 +133,34 @@ protected override SyntaxList<MemberDeclarationSyntax> GetMemberDeclarationsInCo
...
+                    @new = SyntaxFactory.QualifiedName(qualifiedNamespaceName, nameRef.WithoutTrivia());
                 }
-                else
+
+                // We might lose some trivia associated with children of `outerMostNode`.  
+                @new = @new.WithTriviaFrom(old);
+                return true;
+            }
+
+            if (syntaxFacts.IsNameOfMemberAccessExpression(nameRef))
```
Comment (jasonmalinowski) [inline src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs]: Nit: else if, since it doesn't require you to visually scan that the previous if will always return.

File: src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs (hunk 1 above)
Comment (jasonmalinowski) [reply src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs]: That said, I'm not sure why we wouldn't do this for the entire method rather than just the local method inside of it....

File: src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs [hunk 4]
```diff
@@ -133,23 +133,34 @@ protected override SyntaxList<MemberDeclarationSyntax> GetMemberDeclarationsInCo
...
+            {
+                old = nameRef.Parent;
+                var aliasQualifier = GetAliasQualifierOpt(old);
+
+                if (!TryGetGlobalQualifiedName(newNamespaceParts, nameRef, aliasQualifier, out @new))
                 {
-                    var qualifiedNamespaceName = CreateNameSyntax(newNamespaceParts, aliasQualifier, newNamespaceParts.Length - 1);
-                    @new = SyntaxFactory.QualifiedName(qualifiedNamespaceName, nameRef.WithoutTrivia());
+                    var memberAccessNamespaceName = CreateNamespaceAsMemberAccess(newNamespaceParts, aliasQualifier, newNamespaceParts.Length - 1);
+                    @new = SyntaxFactory.MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression, memberAccessNamespaceName, nameRef.WithoutTrivia());
```
Comment (jasonmalinowski) [inline src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs]: Nit: I wish we called @new "newNode" so the type is a bit more obvious.

File: src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs [hunk 5]
```diff
@@ -194,6 +201,23 @@ protected override SyntaxList<MemberDeclarationSyntax> GetMemberDeclarationsInCo
             // The name will be resolved by adding proper import.
             old = @new = nameRef;
             return false;
+
+#nullable enable
+            static bool TryGetGlobalQualifiedName(ImmutableArray<string> newNamespaceParts, SimpleNameSyntax nameNode, string? aliasQualifier, out SyntaxNode? newNode)
```
Comment (jasonmalinowski) [inline src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs]: newNode should be marked as `[NotNullIf(returnValue: true)]`

File: src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs [hunk 6]
```diff
@@ -133,23 +133,34 @@ protected override SyntaxList<MemberDeclarationSyntax> GetMemberDeclarationsInCo
...
-                    // If new namespace is "", then name will be declared in global namespace.
-                    // We will replace qualified reference with simple name qualified with alias (global if it's not alias qualified)
-                    var aliasNode = aliasQualifier?.ToIdentifierName() ?? SyntaxFactory.IdentifierName(SyntaxFactory.Token(SyntaxKind.GlobalKeyword));
-                    @new = SyntaxFactory.AliasQualifiedName(aliasNode, nameRef.WithoutTrivia());
+                    var qualifiedNamespaceName = CreateNamespaceAsQualifiedName(newNamespaceParts, aliasQualifier, newNamespaceParts.Length - 1);
+                    @new = SyntaxFactory.QualifiedName(qualifiedNamespaceName, nameRef.WithoutTrivia());
                 }
-                else
+
+                // We might lose some trivia associated with children of `outerMostNode`.
```
Comment (jasonmalinowski) [inline src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs]: Is this a bug we should be fixing?

**Comment by genlu** [comment]
@jasonmalinowski Will address you comments in a follow up PR, possibly targeting 16.4

File: src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs (hunk 6 above)
Comment (genlu) [reply src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs]: It happens when there's trivia in between names of a qualified name or member access node, which doesn't feels like a scenario worth fixing to me.
