### PR TITLE
Fix #1663

### LINKED ISSUE #1663: IntelliSense doesn't work on member access in nameof()
Source:

```C#
class C {
	static string x = nameof(x.);
}
```

It is impossible to show IntelliSense for the members of `string` for `x.`.

### PR DESCRIPTION
**Pull request by rchande**
Nameof now allows member access from locals, etc. Completion shouldn't
restrict member access to only types and namespaces.

Potential reviewers: @balajikris @basoundr @brettfo @dpoeschl @jasonmalinowski @Pilchie

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
:skull:

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs [hunk 1]
```diff
@@ -7421,12 +7421,12 @@ public class U
     public int nope;
```
Comment (dpoeschl) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs]: s/nope/yep/ :wink:

Comment (Pilchie) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs]: :+1:

**Comment by Pilchie** [comment]
LGTM

**Comment by dpoeschl** [comment]
:hamster:
