### PR TITLE
Fix TypeChar handler in Interactive Window

### LINKED ISSUE #6397: Consecutive keystrokes in Interactive Window should be a single undo action
When typing in interactive window, each keystroke is a separate action called `Text Buffer Change` in undo/redo history. We expect consecutive keystroke as a single undo action called `Insert Text`.

type_history

### PR DESCRIPTION
**Pull request by genlu**
Previous change on `TypeChar` handling (#6914) incorrectly shortcut all subsequent handlers in pre-language service filter , the result is missing functionalities like auto-completion...  This fixes the issue by handling typed char in pre-language service filter, then let the execution flow to other language service handlers, and finally stop the execution in pre-editor filter.

Also add support for merging consecutive TypeChar operations in Interactive Window, which fixes #6397

@dotnet/roslyn-interactive

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @dotnet/roslyn-ide

File: src/InteractiveWindow/Editor/InteractiveWindow.UIThreadOnly.cs [hunk 1]
```diff
@@ -475,9 +475,15 @@ private void AppendLineNoPromptInjection(ITextBuffer buffer)
             }
 
             /// <summary>Implements <see cref="IInteractiveWindowOperations2.TypeChar"/>.</summary>
-            internal void TypeChar(char typedChar)
+            public void TypeChar(char typedChar)
             {
-                InsertText(typedChar.ToString());
+                using (var transaction = UndoHistory?.CreateTransaction(InteractiveWindowResources.TypeChar))
```
Comment (jasonmalinowski) [inline src/InteractiveWindow/Editor/InteractiveWindow.UIThreadOnly.cs]: Why are we implementing this at all? This will break merging of typed character undo operations, amongst other things. Looking at PR #6914, it's not clear to me why this approach is necessary. I would expect you'd still be deferring to the editor for the actual insertion handling, doing whatever setup you need before forwarding to the next handler.

Comment (genlu) [inline src/InteractiveWindow/Editor/InteractiveWindow.UIThreadOnly.cs]: @jasonmalinowski The merging did not work before the change. So I made the change on Delete() and added TypeChar handling in hope to make undo/redo works better (everything was `Text Buffer Change` before the change). I'd love to have this fixed if you can show me the way :)

Comment (jasonmalinowski) [inline src/InteractiveWindow/Editor/InteractiveWindow.UIThreadOnly.cs]: Ah, well I guess this is an improvement then. Looking at the editor implementation of ECMD_TYPECHAR I guess it does forward to InsertText which is surprising to me. If you look at `TextTransactionMergePolicy` in the editor codebase it appears the requirements are:

1. Both transactions were initiated through EditorOperations to get the merge policy.
2. The textual descriptions are the same.
3. Edits are consecutive.

In any case, I was wrong about how I thought the editor handled this, so I guess this is better than before. I'm still curious though why we're having to do so much work here rather than forwarding to nextHandler more.

**Comment by jasonmalinowski** [comment]
This is quite the regression. :smile: No tests?

File: src/InteractiveWindow/Editor/InteractiveWindow.UIThreadOnly.cs (hunk 1 above)
Comment (genlu) [inline src/InteractiveWindow/Editor/InteractiveWindow.UIThreadOnly.cs]: It seems that `Delete's` are not merged in editor though, but yeah, I think I will need to rely on `EditorOperations.InsertText` for TypeChar in order to get them mergable.

The main reason behind implement those operations myself is to have a consistent behavior and better undo/redo when dealing with intertwined input and readonly buffers in interactive window among all the delete related operations  (i.e. delete, cut, paste, insert text, etc.). Some of them could be passed on to `EditorOperations` but I prefer consistency here :)

**Comment by genlu** [comment]
None of the language services are hooked up in Interactive window test today :(
I will go figure out how

**Comment by jasonmalinowski** [comment]
In the spirit of modular testing, it's probably best to not. Just having a test that creates a stupid TypeChar handler and ensures it gets called would be a useful step.

File: src/InteractiveWindow/Editor/InteractiveWindow.UIThreadOnly.cs (hunk 1 above)
Comment (jasonmalinowski) [inline src/InteractiveWindow/Editor/InteractiveWindow.UIThreadOnly.cs]: The consistency makes sense for cut/paste, but for delete which you also want merged, it looks like you'll have to call EditorOperations instead. Looks like consistency loses here. :smile:

Comment (genlu) [inline src/InteractiveWindow/Editor/InteractiveWindow.UIThreadOnly.cs]: Actually, I just remember another (bigger) reason why I implemented those operations in Interactive Window: the undo history is associated with input text buffer instead of the entire TextView of the window (both editable and readonly buffers), which doesn't work well with `EditorOperations` and how it handles undo/redo's.

Comment (jasonmalinowski) [inline src/InteractiveWindow/Editor/InteractiveWindow.UIThreadOnly.cs]: `EditorOperations.Insert seems to handle it fine, is it `EditorOperations.Delete` that's broken?

Comment (genlu) [inline src/InteractiveWindow/Editor/InteractiveWindow.UIThreadOnly.cs]: I believe so.

**Comment by genlu** [comment]
I will try to add some tests for TypeChar handler after I figure out how :)
Meanwhile, the most recent commit add support for merging consecutive TypeChar operations in Interactive Window, by copying `TextTransactionMergePolicy` from editor (I hate copying code, but this seems to be the best if not the only way to handle this in interactive window)

File: src/InteractiveWindow/Editor/InteractiveWindow.UIThreadOnly.cs (hunk 1 above)
Comment (genlu) [inline src/InteractiveWindow/Editor/InteractiveWindow.UIThreadOnly.cs]: Wait, did I miss something? Consecutive delete in VS editor are not merged.

**Comment by jasonmalinowski** [comment]
I'd prefer we just drive whatever issues we need driven to use EditorOperations rather than copying/pasting the code.

**Comment by genlu** [comment]
Added commit with `TextTransactionMergePolicy` back since I just got the go-ahead on copying it from VS. @dotnet/roslyn-interactive

**Comment by jasonmalinowski** [comment]
Can we fix the editor instead?

**Comment by genlu** [comment]
@jasonmalinowski I can't use the old model (i.e. handle delete and then let it fall through to editor for insert character) since it would make TypeChar two separate actions (delete and insert char), which also cause unmergable consecutive TypeChars

**Comment by jasonmalinowski** [comment]
But why can't we just let typechar flow through entirely? I understand you have to preprocess in a few situations, but it seems like those can all be ultimately setting up state and then calling nextHandler().

**Comment by genlu** [comment]
@jasonmalinowski because deletion in interactive window can't be handled by editor due to the existence of prompts: they are readonly but also 'deletable' such that they can be removed if the corresponding line of input is deleted.

**Comment by jasonmalinowski** [comment]
But how does that relate to typechar? The problem if I typechar over a selection that contains the prompts?

**Comment by genlu** [comment]
@jasonmalinowski Yup.

**Comment by jasonmalinowski** [comment]
OK, at this point I'm convinced you understand this more than I do, so :+1:!

File: src/InteractiveWindow/EditorTest/InteractiveWindowTests.cs [hunk 2]
```diff
@@ -491,6 +491,8 @@ private void TestIndentation(int indentSize)
             AssertCaretVirtualPosition(2, promptWidth + 1);
         }
 
+
+
```
Comment (jasonmalinowski) [inline src/InteractiveWindow/EditorTest/InteractiveWindowTests.cs]: Blank lines.
