### PR TITLE
Throw NotImplementedException when a build errorId is not supported

### LINKED ISSUE #81109: Build fails - Error List doesn't show error
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Build-fails---Error-List-doesnt-show-er/10965111)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:18.0.0]
This has been an intermittent issue since about VS 2017, but I'm seeing it in 2026 preview. Build will fail, but Error List doesn't update. Loading the same solution in VS 2022 it fails and shows me the error in Error List.

---
#### Feedback Bot on 9/11/2025, 06:23 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### YI CHWEEN ONG (Centific Technologies Inc) [MSFT] on 9/16/2025, 06:48 PM: 

<p>Thank you for taking the time to log this issue!<br>
Do you still repro this issue now? In order to investigate your issue further, could you help to confirm several questions?</p>
<ol>
<li>Can I know what kind of project you’re using to repro this issue (e.g., C#/C++ Console App, Unit Test Project, etc…)? Would it be possible to provide us a sample demo which can reproduce this issue?</li>
<li>Can you try to create a new simple solution and check if this issue also reproduces?</li>
<li>Can you provide us a repro video using <a target='_blank' href="https://www.screentogif.com/">https://www.screentogif.com/</a> or a similar tool?</li>
</ol>
<p><em>(The reason we’re asking for additional information is that we’d like to fully understand the issue and try to reproduce it on our side.)</em><br>
We look forward to hearing from you!</p>

#### Richard Tregaskis on 9/17/2025, 08:27 AM: 

<ol>
<li>C#, .Net Framework aspx web app</li>
<li>Fresh install of Windows and VS working on an older solution/project. Happens on multiple projects/solutions. It IS intermittent. If I close Visual Studio and delete the .vs folder and bin and obj folders, then it will work for a while. Or if I change the Build + Intelligence option in the Error List window to Build Only, this usually fixes it as well.</li>
<li>Like I said, it’s intermittent, but has been happening for several generations of Visual Studio and I can see that many people have reported this issue. It needs to be escalated to a dev to look at instead of putting the burden on so many users to try and “prove” there is an intermittent issue. Probably some minor issue that wouldn’t be too hard to find if someone would take the time.</li>
</ol>
<p>Summary: Build Only appears to work without issue. Build + Intellisense seems to present intermittent issues unless .vs and bin and obj are deleted.</p>

#### Richard Tregaskis on 10/15/2025, 01:22 PM: 

<p>Doing the same thing in VS 2026. It might be related to older .sln or .csproj files, but it definitely happens most of the time for me.</p>

#### Andrea Williams on 10/28/2025, 02:06 PM: 

(private comment, text removed)
#### Andrea Williams on 10/30/2025, 00:19 PM: 

(private comment, text removed)
#### YI CHWEEN ONG (Centific Technologies Inc) [MSFT] on 9/26/2025, 00:44 AM: 

<p>Sorry for the problem you encountered, in order to better reproduce the problem, could you please use the Feedback tool to create a dump file so that we can conduct further research with the following steps?</p>
<ol>
<li>In Visual Studio, use Help-&gt;Send Feedback-&gt; ‘My Feedback’.</li>
<li>Click ‘Provide More Info’.</li>
<li>Select Attach System logs and click ‘Record your actions to reproduce an issue’</li>
<li>Perform that steps that cause the issue to occur. (If the issue is intermittent – just work normally until the issue occurs; only the latest data is collected). Note: Pause the Steps Recorder to increase performance</li>
<li>After the problem occurs, close Steps Recorder to stop the trace; log files will be collected and attached to the ticket.<br>
For more information see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022</a>.</li>
</ol>
<p>We look forward to hearing from you!</p>

#### Feedback Bot on 10/7/2025, 06:52 PM: 

<p>We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.</p>

#### Andrea Williams on 10/15/2025, 00:49 PM: 

<p>I’m having the same issue.  Workaround is to delete bin and object folders and rebuild, which takes extra time and my productivity is reduced.  This started happening after an update to Visual Studio 2022.  Now Version 17.14.13 (August 2025)</p>

#### YI CHWEEN ONG (Centific Technologies Inc) [MSFT] on 10/20/2025, 11:45 PM: 

<p><a target='_blank' href="https://developercommunity.visualstudio.com/user/1246702/profile">Andrea Williams</a> Can you please provide the dump/etl file so we can analyze the issue further?</p>

#### Andrea Williams on 10/30/2025, 00:24 PM: 

(private comment, text removed)
#### Feedback Bot on 10/30/2025, 03:50 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

### PR DESCRIPTION
**Pull request by JoeRobich**
In #79964 we [removed a check](https://github.com/dotnet/roslyn/pull/79964/changes#diff-07399f17a690c95d4e31689e1023676fa4b43d37e86775b6611bd8e1f170de6aL280-L281) for whether a non-compiler build error should be reported to the Error List. This PR restores that check. It also adds an in-process cache of diagnostic descriptors so that it can synchronously determine whether a diagnostic id is supported.

Fixes https://github.com/dotnet/roslyn/issues/81109
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2695780

### CODE REVIEW

File: src/VisualStudio/Core/Def/TaskList/ProjectExternalErrorReporter.cs [hunk 1]
```diff
@@ -210,58 +212,68 @@ public void ReportError2(
             return;
         }
 
-        if (!bstrErrorId.StartsWith(_errorCodePrefix))
-            return;
+        Task.Run(() => ReportErrorAsync()).Forget();
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/TaskList/ProjectExternalErrorReporter.cs]: I believe making this async breaks the removal of errors, because now if the project system calls Report and then calls Clear, you can end up with the diagnostics stuck.

File: src/VisualStudio/Core/Def/TaskList/ProjectExternalErrorReporter.cs [hunk 2]
```diff
@@ -210,58 +212,68 @@ public void ReportError2(
...
 
-        if ((iEndLine >= 0 && iEndColumn >= 0) &&
-           ((iEndLine < iStartLine) ||
-            (iEndLine == iStartLine && iEndColumn < iStartColumn)))
+        async Task ReportErrorAsync()
         {
-            throw new ArgumentException(ServicesVSResources.End_position_must_be_start_position);
-        }
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/TaskList/ProjectExternalErrorReporter.cs:220]: Blank line.

File: src/VisualStudio/Core/Def/TaskList/ProjectExternalErrorReporter.cs (hunk 1 above)
Comment (jasonmalinowski) [reply src/VisualStudio/Core/Def/TaskList/ProjectExternalErrorReporter.cs]: @CyrusNajmabadi and I went through a number of iterations of this trying to get the semantics right...

File: src/VisualStudio/Core/Def/TaskList/ProjectExternalErrorReporter.cs [hunk 3]
```diff
@@ -210,58 +212,68 @@ public void ReportError2(
...
-            documentId = null;
-            iStartLine = iStartColumn = iEndLine = iEndColumn = 0;
-        }
-        else
-        {
-            documentId = TryGetDocumentId(bstrFileName);
-        }
+            if (!bstrErrorId.StartsWith(_errorCodePrefix) &&
+                !await DiagnosticProvider.IsSupportedDiagnosticIdAsync(
+                    _projectId, bstrErrorId, CancellationToken.None).ConfigureAwait(false))
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/TaskList/ProjectExternalErrorReporter.cs]: I'm trying to figure out what the logic of this should be. Inverting the logic for a moment, we're saying that we should report all diagnostics that are the compiler diagnostics, or ones that come from analyzers. But at that point what are filtering out? I guess MSBuild diagnostics, but then why did the project system call us in the first place?

Comment (JoeRobich) [reply src/VisualStudio/Core/Def/TaskList/ProjectExternalErrorReporter.cs]: That is a very valid point and my first instinct was to simply remove the compiler diagnostic filter. Then I looked up the history of the change and thought maybe restoring it to its previous "working" form was a better approach.

File: src/Features/Core/Portable/Diagnostics/IDiagnosticAnalyzerService.cs [hunk 4]
```diff
@@ -97,6 +98,13 @@ Task<ImmutableArray<DiagnosticData>> GetDiagnosticsForSpanAsync(
     Task<ImmutableDictionary<string, ImmutableArray<DiagnosticDescriptor>>> GetDiagnosticDescriptorsPerReferenceAsync(
         Solution solution, ProjectId? projectId, CancellationToken cancellationToken);
 
+    /// <summary>
+    /// Gets a cached snapshot of diagnostic descriptors for the given <paramref name="projectId"/>.
+    /// This call never computes descriptors synchronously. If no cached data is available, returns <see langword="false"/>.
```
Comment (JoeRobich) [inline src/Features/Core/Portable/Diagnostics/IDiagnosticAnalyzerService.cs]:
```suggestion
    /// If no cached data is available, returns <see langword="false"/>.
```

File: src/VisualStudio/Core/Def/TaskList/ProjectExternalErrorReporter.cs (hunk 1 above)
Comment (JoeRobich) [reply src/VisualStudio/Core/Def/TaskList/ProjectExternalErrorReporter.cs]: Made it synchronous

**Comment by JoeRobich** [comment]
@jasonmalinowski This is ready for another look.

**Review by akhera99 — APPROVED** [review]

File: src/VisualStudio/Core/Def/TaskList/ProjectExternalErrorReporter.cs [hunk 5]
```diff
@@ -200,21 +199,25 @@ public void ReportError2(
         int iEndColumn,
         string bstrFileName)
     {
-
         // make sure we have error id, otherwise, we simple don't support
         // this error
-        if (bstrErrorId == null)
+        if (bstrErrorId?.Length is null or 0)
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/TaskList/ProjectExternalErrorReporter.cs]: Just use string.IsNullOrEmpty?

File: src/VisualStudio/Core/Def/TaskList/ProjectExternalErrorReporter.cs [hunk 6]
```diff
@@ -200,21 +199,25 @@ public void ReportError2(
...
         {
-            // record NFW to see who violates contract.
-            FatalError.ReportAndCatch(new Exception("errorId is null"));
-            return;
+            if (bstrErrorId is null)
+                // record NFW to see who violates contract.
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/TaskList/ProjectExternalErrorReporter.cs:208]: Braces if we're going to have a comment there.

File: src/Workspaces/CoreTestUtilities/Workspaces/TestWorkspace`1.cs [hunk 7]
```diff
@@ -337,6 +337,7 @@ public override bool CanApplyChange(ApplyChangesKind feature)
         {
             case ApplyChangesKind.AddDocument:
             case ApplyChangesKind.RemoveDocument:
+            case ApplyChangesKind.RemoveProject:
                 return KindSupportsAddRemoveDocument();
```
Comment (jasonmalinowski) [inline src/Workspaces/CoreTestUtilities/Workspaces/TestWorkspace`1.cs:340]: Seems like the method name implies this should be used for documents which this isn't -- want to just add this as "return true" in it's own group?

File: src/Features/Core/Portable/Diagnostics/Service/DiagnosticAnalyzerService.DiagnosticDescriptorCache.cs [hunk 8]
```diff
@@ -0,0 +1,96 @@
...
+using Microsoft.CodeAnalysis.Shared.TestHooks;
+using Microsoft.CodeAnalysis.Threading;
+
+namespace Microsoft.CodeAnalysis.Diagnostics;
+
+internal sealed partial class DiagnosticAnalyzerService
+{
+    internal class DiagnosticDescriptorCache
+    {
+        private readonly ConcurrentDictionary<ProjectId, ImmutableDictionary<string, ImmutableArray<DiagnosticDescriptor>>> _projectIdToDescriptorCache = [];
```
Comment (jasonmalinowski) [inline src/Features/Core/Portable/Diagnostics/Service/DiagnosticAnalyzerService.DiagnosticDescriptorCache.cs]: Add a comment explaning what the structure is here, especially with that 'string' in there.

File: src/Features/Core/Portable/Diagnostics/Service/DiagnosticAnalyzerService_RemoteOrLocalDispatcher.cs [hunk 9]
```diff
@@ -102,6 +102,11 @@ public async Task<ImmutableArray<string>> GetCompilationEndDiagnosticDescriptorI
         return builder.ToImmutableArray();
     }
 
+    public bool TryGetCachedDiagnosticDescriptorsPerReference(ProjectId projectId, [NotNullWhen(returnValue: true)] out ImmutableDictionary<string, ImmutableArray<DiagnosticDescriptor>>? descriptorsPerReference)
```
Comment (jasonmalinowski) [inline src/Features/Core/Portable/Diagnostics/Service/DiagnosticAnalyzerService_RemoteOrLocalDispatcher.cs]: Is this the only method that is doing in-process stuff here? Does it make sense to still have this on this interface, versus just having the implemention be somewhere else? If the only consumer of this is the VS side of things, then it might make sense to keep this specific to the VS side, and possibly only activate it for csproj/msvbprj-based projects versus CPS projects.

File: src/Features/Core/Portable/Diagnostics/Service/DiagnosticAnalyzerService.DiagnosticDescriptorCache.cs [hunk 10]
```diff
@@ -0,0 +1,96 @@
...
+            var workspaceChanges = e.NewSolution.GetChanges(e.OldSolution);
+
+            foreach (var newProject in workspaceChanges.GetAddedProjects())
+            {
+                _projectDescriptorRefreshQueue.AddWork(newProject.Id);
+            }
+
+            foreach (var removedProject in workspaceChanges.GetRemovedProjects())
+            {
+                _projectIdToDescriptorCache.TryRemove(removedProject.Id, out _);
```
Comment (jasonmalinowski) [inline src/Features/Core/Portable/Diagnostics/Service/DiagnosticAnalyzerService.DiagnosticDescriptorCache.cs]: This has an implicit race with work that might already be in the queue, in that we'll try to remove this but the queue might put the entry back.

File: src/Features/Core/Portable/Diagnostics/Service/DiagnosticAnalyzerService.DiagnosticDescriptorCache.cs [hunk 11]
```diff
@@ -0,0 +1,96 @@
...
+        }
+
+        private async ValueTask RefreshCachedDiagnosticDescriptorsAsync(
+            ImmutableSegmentedList<ProjectId> projectIds,
+            CancellationToken cancellationToken)
+        {
+            foreach (var projectId in projectIds)
+            {
+                var project = _workspace.CurrentSolution.GetProject(projectId);
+                if (project == null)
```
Comment (jasonmalinowski) [inline src/Features/Core/Portable/Diagnostics/Service/DiagnosticAnalyzerService.DiagnosticDescriptorCache.cs]: To my earlier comment about the race, I'd imagine in this case you'd just want to remove the entry in the map. Then you can deal with the delete case by having it queue the ProjectId, and it gets removed here.

File: src/Features/Core/Portable/Diagnostics/Service/DiagnosticAnalyzerService.DiagnosticDescriptorCache.cs [hunk 12]
```diff
@@ -0,0 +1,96 @@
...
+
+            foreach (var removedProject in workspaceChanges.GetRemovedProjects())
+            {
+                _projectIdToDescriptorCache.TryRemove(removedProject.Id, out _);
+            }
+
+            foreach (var projectChange in workspaceChanges.GetProjectChanges())
+            {
+                var analyzersChanged = projectChange.GetAddedAnalyzerReferences().Any()
+                    || projectChange.GetRemovedAnalyzerReferences().Any();
```
Comment (jasonmalinowski) [inline src/Features/Core/Portable/Diagnostics/Service/DiagnosticAnalyzerService.DiagnosticDescriptorCache.cs]: It might be worth looking at whether we can optimize this a bit by getting the old/new states, and then just check if the collections themselves have changed with object equality. Because that would be cheaper than continually computing these lists since we don't actually care about what the changes were.

File: src/VisualStudio/Core/Def/TaskList/ExternalErrorDiagnosticUpdateSource.cs [hunk 13]
```diff
@@ -327,39 +326,36 @@ private sealed class InProgressState(Solution solution)
         /// <summary>
         /// Map from project ID to all the possible analyzer diagnostic IDs that can be reported in the project.
         /// </summary>
-        private ImmutableDictionary<ProjectId, AsyncLazy<ImmutableHashSet<string>>> _allDiagnosticIdMap = ImmutableDictionary<ProjectId, AsyncLazy<ImmutableHashSet<string>>>.Empty;
+        private readonly ConcurrentDictionary<ProjectId, ImmutableHashSet<string>> _allDiagnosticIdMap = [];
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/TaskList/ExternalErrorDiagnosticUpdateSource.cs]: So is this already a cache that's doing roughly the same thing? Do we have two caches now?

File: src/Workspaces/CoreTestUtilities/Workspaces/TestWorkspace`1.cs (hunk 7 above)
Comment (JoeRobich) [reply src/Workspaces/CoreTestUtilities/Workspaces/TestWorkspace`1.cs:340]: Should RemoveProject work in the context of scripting, misc, semantic workspace kinds?

Comment (JoeRobich) [reply src/Workspaces/CoreTestUtilities/Workspaces/TestWorkspace`1.cs:340]: I'll introduce new method.

File: src/Features/Core/Portable/Diagnostics/Service/DiagnosticAnalyzerService.cs [hunk 14]
```diff
@@ -6,7 +6,6 @@
 using System.Collections.Generic;
 using System.Collections.Immutable;
 using System.Composition;
```
Comment (JoeRobich) [inline src/Features/Core/Portable/Diagnostics/Service/DiagnosticAnalyzerService.cs:8]:
```suggestion
using System.Composition;
using System.Linq;
```

File: src/Features/Core/Portable/Diagnostics/Service/DiagnosticAnalyzerService_RemoteOrLocalDispatcher.cs [hunk 15]
```diff
@@ -5,7 +5,7 @@
 using System;
 using System.Collections.Generic;
 using System.Collections.Immutable;
-using System.Linq;
+using System.Diagnostics.CodeAnalysis;
```
Comment (JoeRobich) [inline src/Features/Core/Portable/Diagnostics/Service/DiagnosticAnalyzerService_RemoteOrLocalDispatcher.cs]:
```suggestion
```

File: src/Features/Core/Portable/Diagnostics/IDiagnosticAnalyzerService.cs [hunk 16]
```diff
@@ -3,6 +3,7 @@
 // See the LICENSE file in the project root for more information.
 
 using System.Collections.Immutable;
+using System.Diagnostics.CodeAnalysis;
```
Comment (JoeRobich) [inline src/Features/Core/Portable/Diagnostics/IDiagnosticAnalyzerService.cs]:
```suggestion
```

File: src/Features/Core/Portable/Diagnostics/Service/DiagnosticAnalyzerService_RemoteOrLocalDispatcher.cs [hunk 17]
```diff
@@ -5,7 +5,6 @@
 using System;
 using System.Collections.Generic;
 using System.Collections.Immutable;
```
Comment (JoeRobich) [inline src/Features/Core/Portable/Diagnostics/Service/DiagnosticAnalyzerService_RemoteOrLocalDispatcher.cs:7]:
```suggestion
using System.Collections.Immutable;
using System.Linq;
```

**Comment by JoeRobich** [comment]
@jasonmalinowski Ready for another look

File: src/VisualStudio/Core/Def/TaskList/VisualStudioDiagnosticIdCache.cs [hunk 18]
```diff
@@ -0,0 +1,117 @@
...
+using Microsoft.CodeAnalysis.Shared.TestHooks;
+using Microsoft.CodeAnalysis.Threading;
+
+namespace Microsoft.VisualStudio.LanguageServices.TaskList;
+
+[ExportWorkspaceServiceFactory(typeof(VisualStudioDiagnosticIdCache)), Shared]
+[method: ImportingConstructor]
+[method: Obsolete(MefConstruction.ImportingConstructorMessage, error: true)]
+internal sealed class DiagnosticAnalyzerServiceFactory(
+    [Import(AllowDefault = true)] IAsynchronousOperationListenerProvider? listenerProvider) : IWorkspaceServiceFactory
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/TaskList/VisualStudioDiagnosticIdCache.cs]: Since this is in-process this AllowDefault shouldn't be required anymore.

File: src/VisualStudio/Core/Def/TaskList/VisualStudioDiagnosticIdCache.cs [hunk 19]
```diff
@@ -0,0 +1,117 @@
...
+    {
+        return new VisualStudioDiagnosticIdCache(
+            workspaceServices.Workspace,
+            listenerProvider);
+    }
+}
+
+internal class VisualStudioDiagnosticIdCache : IWorkspaceService
+{
+    // This dictionary maps ProjectIds to a descriptor map.
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/TaskList/VisualStudioDiagnosticIdCache.cs]:
```suggestion
    // This dictionary maps ProjectIds to a descriptor list.
```

File: src/VisualStudio/Core/Def/TaskList/VisualStudioDiagnosticIdCache.cs [hunk 20]
```diff
@@ -0,0 +1,117 @@
...
+        _workspace = workspace;
+        _analyzerService = workspace.Services.GetRequiredService<IDiagnosticAnalyzerService>();
+        _listener = listenerProvider?.GetListener(FeatureAttribute.DiagnosticService) ?? AsynchronousOperationListenerProvider.NullListener;
+
+        _projectDescriptorRefreshQueue = new AsyncBatchingWorkQueue<ProjectId>(
+            delay: DelayTimeSpan.Short,
+            processBatchAsync: RefreshCachedDiagnosticIdsAsync,
+            equalityComparer: EqualityComparer<ProjectId>.Default,
+            asyncListener: _listener,
+            cancellationToken: CancellationToken.None);
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/TaskList/VisualStudioDiagnosticIdCache.cs]: If you import IThreadingContext that has a DisposalToken you can use.

File: src/VisualStudio/Core/Def/TaskList/VisualStudioDiagnosticIdCache.cs [hunk 21]
```diff
@@ -0,0 +1,117 @@
...
+        {
+            _projectDescriptorRefreshQueue.AddWork(removedProject.Id);
+        }
+
+        foreach (var projectChange in workspaceChanges.GetProjectChanges())
+        {
+            var oldProject = projectChange.OldProject;
+            var newProject = projectChange.NewProject;
+
+            var analyzersChanged = oldProject.AnalyzerReferences != newProject.AnalyzerReferences;
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/TaskList/VisualStudioDiagnosticIdCache.cs]: Should we be doing .Equals() here? Which actual type is this?

File: src/VisualStudio/Core/Def/TaskList/VisualStudioDiagnosticIdCache.cs [hunk 22]
```diff
@@ -0,0 +1,117 @@
...
+
+    private async ValueTask RefreshCachedDiagnosticIdsAsync(
+        ImmutableSegmentedList<ProjectId> projectIds,
+        CancellationToken cancellationToken)
+    {
+        foreach (var projectId in projectIds)
+        {
+            var project = _workspace.CurrentSolution.GetProject(projectId);
+            if (project == null)
+                continue;
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/TaskList/VisualStudioDiagnosticIdCache.cs:115]: I think you meant to remove here now per our earlier discussion.

File: src/EditorFeatures/Test/Diagnostics/DiagnosticAnalyzerServiceTests.cs [hunk 23]
```diff
@@ -1,1042 +0,0 @@
...
-            {
-                Assert.Equal(root.SyntaxTree, analyzer.CallbackFilterTree);
-                Assert.Null(analyzer.CallbackFilterFile);
-            }
-        }
-    }
-
-    [Theory, CombinatorialData]
-    [WorkItem("https://github.com/dotnet/roslyn/issues/67084")]
-    internal async Task TestCancellationDuringDiagnosticComputation_OutOfProc(AnalyzerRegisterActionKind actionKind)
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Test/Diagnostics/DiagnosticAnalyzerServiceTests.cs:857]: Don't we need all of these other tests?

Comment (JoeRobich) [reply src/EditorFeatures/Test/Diagnostics/DiagnosticAnalyzerServiceTests.cs:857]: yes, sigh

File: src/VisualStudio/Core/Def/TaskList/VisualStudioDiagnosticIdCache.cs (hunk 21 above)
Comment (JoeRobich) [reply src/VisualStudio/Core/Def/TaskList/VisualStudioDiagnosticIdCache.cs]: A boxed ImmutableArray but of course that is an implementation detail.

File: src/VisualStudio/Core/Def/TaskList/VisualStudioDiagnosticIdCache.cs [hunk 24]
```diff
@@ -0,0 +1,126 @@
...
+        return new VisualStudioDiagnosticIdCache(
+            workspaceServices.Workspace,
+            threadingContext,
+            listenerProvider);
+    }
+}
+
+internal class VisualStudioDiagnosticIdCache : IWorkspaceService
+{
+    // This dictionary maps ProjectIds to a descriptor list.
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/TaskList/VisualStudioDiagnosticIdCache.cs:43]: Use doc comments.

File: src/Workspaces/CoreTestUtilities/Workspaces/TestWorkspace`1.cs (hunk 7 above)
Comment (jasonmalinowski) [reply src/Workspaces/CoreTestUtilities/Workspaces/TestWorkspace`1.cs:340]: This seems reasonable.

File: src/VisualStudio/Core/Def/TaskList/ExternalErrorDiagnosticUpdateSource.cs [hunk 25]
```diff
@@ -324,42 +323,26 @@ private InProgressState GetOrCreateInProgressState()
 
     private sealed class InProgressState(Solution solution)
     {
-        /// <summary>
-        /// Map from project ID to all the possible analyzer diagnostic IDs that can be reported in the project.
-        /// </summary>
-        private ImmutableDictionary<ProjectId, AsyncLazy<ImmutableHashSet<string>>> _allDiagnosticIdMap = ImmutableDictionary<ProjectId, AsyncLazy<ImmutableHashSet<string>>>.Empty;
+        private readonly VisualStudioDiagnosticIdCache _diagnosticIdCache = solution.Workspace.Services.GetRequiredService<VisualStudioDiagnosticIdCache>();
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/TaskList/ExternalErrorDiagnosticUpdateSource.cs:326]: It may be a practical question of whether this line is doing much -- I assume we create new InProgressStates, and this will force the cache to be initialized earlier; in a CPS-project only solution we'll fetch this and then never use it.

Comment (jasonmalinowski) [reply src/VisualStudio/Core/Def/TaskList/ExternalErrorDiagnosticUpdateSource.cs:326]: And if we delete that then this InProgressState type might have no reason to exist either, but that's a follow-up.

**Review by jasonmalinowski — APPROVED** [review]
Comments are not blocking, :shipit:.
