### PR TITLE
Add FixAll in containing type/member support for code fixes

### LINKED ISSUE #60029: Make FixAll APIs for ContainingType/Member scope public
@jmarolf Yes, these APIs are intentionally public. Otherwise, public clients such as MS.CA.Testing library, would be unable to create a FixAll provider that supports these new FixAll scopes. We can certainly keep them internal in this PR and have a separate PR to just make these APIs public.

_Originally posted by @mavasani in https://github.com/dotnet/roslyn/pull/59989#discussion_r821311317_

### PR DESCRIPTION
**Pull request by mavasani**
Currently, one can apply FixAll operations to Document, Project and Solution scopes. Now, we also support fixing all diagnostics in containing member and type scopes, wherever applicable.

Closes #60029 

## Screenshot

FixAllInContainingMemberAndType

## Note

1. Fix all in `ContainingType` scope fixes all diagnostics in _all the partial definitions across files_, not just the type declaration in current file from which the fix is triggered.
2. If the trigger diagnostic span does not have a method level member declaration as it's containing symbol, we do not offer `ContainingMember` fix all option  (for example `make class static` code fix for [CA1822](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1822)).
3. Similarly, if the trigger diagnostic span does not have a type declaration as it's containing symbol, we do not offer `ContainingType` fix all option (for example `remove unnecessary usings` code fix for [IDE0005](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0005)).

## Added Tests

1. Unit tests: C# and VB unit tests tests for both `FixAllScope.ContainingMember` and `FixAllScope.ContainingType` in following buckets:
   1. Method body level code fix, so that both these fix all scopes are applicable for the code fix.
   4. Type declaration level code fix, so that only ContainingType fix all scope is applicable. We verify that ContainingMember fix all scope is not offered for such a code fix.
   5. File level code fix (remove unnecessary usings), so that neither of these fix all scopes are applicable. We verify that both these fix all scopes are not offered for such a code fix.
   6. FixAll tests for suppressions for both these scopes.
2. Integration tests for both `FixAllScope.ContainingMember` and `FixAllScope.ContainingType`.

### CODE REVIEW

File: src/Features/Core/Portable/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs [hunk 1]
```diff
@@ -210,6 +215,14 @@ static CodeFixGroupKey GetGroupKey(CodeFix fix)
             using var fixAllSuggestedActionsDisposer = ArrayBuilder<IUnifiedSuggestedAction>.GetInstance(out var fixAllSuggestedActions);
             foreach (var scope in supportedScopes)
             {
+                if (scope is FixAllScope.ContainingMember or FixAllScope.ContainingType)
```
Comment (mavasani) [inline src/Features/Core/Portable/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs:218]: This is the only real change in this file, rest all is making the entire call chain async. We bail out from showing ContainingMember or ContainingType fix all option if we cannot find a containing member or type respectively.

File: src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt [hunk 2]
```diff
@@ -1,5 +1,14 @@
+abstract Microsoft.CodeAnalysis.CodeFixes.FixAllContext.SpanBasedDiagnosticProvider.GetDocumentSpanDiagnosticsAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan fixAllSpan, System.Threading.CancellationToken cancellationToken) -> System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Diagnostic>>
+Microsoft.CodeAnalysis.CodeFixes.DocumentBasedFixAllProvider.DocumentBasedFixAllProvider(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CodeFixes.FixAllScope> supportedFixAllScopes) -> void
```
Comment (jmarolf) [inline src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt:2]: Are these public API additions intentional?

File: src/EditorFeatures/Core/Shared/Extensions/TelemetryExtensions.cs [hunk 3]
```diff
@@ -40,7 +40,9 @@ public static short GetScopeIdForTelemetry(this FixAllScope scope)
                 FixAllScope.Document => 1,
                 FixAllScope.Project => 2,
                 FixAllScope.Solution => 3,
-                _ => 4,
+                FixAllScope.ContainingMember => 4,
```
Comment (jmarolf) [inline src/EditorFeatures/Core/Shared/Extensions/TelemetryExtensions.cs:43]: We previously reported "Custom" scopes as `4` but will now report them as `6` with this change right? I assume we want to keep the telemetry reporting the same for custom scopes

File: src/Features/Core/Portable/CodeFixes/CodeFixService.cs [hunk 4]
```diff
@@ -758,6 +760,17 @@ private async Task<IEnumerable<Diagnostic>> GetDocumentDiagnosticsAsync(Document
             return await diagnostics.ToDiagnosticsAsync(document.Project, cancellationToken).ConfigureAwait(false);
         }
 
+        private async Task<IEnumerable<Diagnostic>> GetDocumentSpanDiagnosticsAsync(Document document, TextSpan span, ImmutableHashSet<string>? diagnosticIds, bool includeSuppressedDiagnostics, CancellationToken cancellationToken)
```
Comment (jmarolf) [inline src/Features/Core/Portable/CodeFixes/CodeFixService.cs:763]: Shouldn't this method be called by the one above and just pass in the span of the document?

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs [hunk 5]
```diff
@@ -106,9 +115,26 @@ private static async Task<ImmutableArray<Diagnostic>> DetermineDiagnosticsAsync(
...
-                : await fixAllContext.GetAllDiagnosticsAsync(fixAllContext.Project).ConfigureAwait(false);
+            if (fixAllContext.Document != null)
+            {
+                if (fixAllContext.State.FixAllSpans.IsEmpty)
+                {
+                    return await fixAllContext.GetDocumentDiagnosticsAsync(fixAllContext.Document).ConfigureAwait(false);
+                }
+                else
+                {
+                    var diagnostics = ImmutableArray<Diagnostic>.Empty;
```
Comment (jmarolf) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs:126]: Use a builder?

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.SpanBasedDiagnosticProvider.cs [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+using Microsoft.CodeAnalysis.Internal.Log;
+using Microsoft.CodeAnalysis.Text;
+using Roslyn.Utilities;
+
+namespace Microsoft.CodeAnalysis.CodeFixes
+{
+    /// <summary>
+    /// Context for "Fix all occurrences" code fixes provided by a <see cref="FixAllProvider"/>.
+    /// </summary>
+    public partial class FixAllContext
```
Comment (jmarolf) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.SpanBasedDiagnosticProvider.cs:19]: Make Internal?

File: src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt (hunk 2 above)
Comment (jmarolf) [reply src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt:2]: I think we can duplicate some types here and make them internal.

Comment (333fred) [reply src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt:2]: Yes, there's an issue template for it. Manish, you're one of the area owners so go ahead and file the issue and apply the `api-ready-for-review` tag.

File: src/Features/Core/Portable/FeaturesResources.resx [hunk 7]
```diff
@@ -737,6 +737,15 @@ Do you want to continue?</value>
   <data name="Solution" xml:space="preserve">
     <value>Solution</value>
   </data>
+  <data name="Selection" xml:space="preserve">
+    <value>Selection</value>
+  </data>
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/FeaturesResources.resx:742]: remove this one?

File: src/Features/Core/Portable/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs:218]: open question.  how does TS/F# play into this?  is finding the containing type/member part of some API they can imeplement?

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAll/FixAllState.cs [hunk 8]
```diff
@@ -28,24 +29,42 @@ internal sealed partial class FixAllState
         public FixAllScope Scope { get; }
         public CodeActionOptionsProvider CodeActionOptionsProvider { get; }
 
+        // Note: TriggerSpan can be null from the back-compat public constructor of FixAllContext.
+        public TextSpan? TriggerSpan { get; }
+
+        /// <summary>
+        /// Optional fix all spans to be fixed within the document. Can be empty
+        /// if fixing the entire document, project or solution.
+        /// If non-empty, <see cref="Document"/> must be non-null.
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAll/FixAllState.cs:38]: 'non-null' doesn't fit here.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs [hunk 9]
```diff
@@ -50,6 +54,48 @@ internal static class FixAllContextHelper
...
+                    if (document != null && !await document.IsGeneratedCodeAsync(cancellationToken).ConfigureAwait(false))
+                    {
+                        if (!fixAllSpans.IsEmpty)
+                        {
+                            // We are processing a span-based FixAllContext created for a partial declaration.
+                            var documentDiagnostics = ImmutableArray<Diagnostic>.Empty;
+                            foreach (var fixAllSpan in fixAllSpans)
+                            {
+                                documentDiagnostics = documentDiagnostics.AddRange(await fixAllContext.GetDocumentSpanDiagnosticsAsync(
+                                    document, fixAllSpan).ConfigureAwait(false));
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs:67]: can this helper just take in many spans?  woudl that be more efficient down below instead of calling multiple times into it?

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs [hunk 10]
```diff
@@ -50,6 +54,48 @@ internal static class FixAllContextHelper
 
                     break;
 
+                case FixAllScope.ContainingMember or FixAllScope.ContainingType:
+                    if (document != null && !await document.IsGeneratedCodeAsync(cancellationToken).ConfigureAwait(false))
+                    {
+                        if (!fixAllSpans.IsEmpty)
+                        {
+                            // We are processing a span-based FixAllContext created for a partial declaration.
+                            var documentDiagnostics = ImmutableArray<Diagnostic>.Empty;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs:63]:
```suggestion
                            using var _ = ArrayBuilde<Diagnostic>.GetInstance(out var documentDiagnostics);
```

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs [hunk 11]
```diff
@@ -50,6 +54,48 @@ internal static class FixAllContextHelper
...
+
+                            return ImmutableDictionary<Document, ImmutableArray<Diagnostic>>.Empty.SetItem(document, documentDiagnostics);
+                        }
+                        else if (triggerSpan.HasValue)
+                        {
+                            // We need to compute diagnostics for each of the containing member/type and its partial declarations
+                            // using the trigger span.
+                            var documentsAndSpans = await GetDocumentsAndSpansForContainingMemberOrTypeAsync(document,
+                                fixAllContext.Scope, triggerSpan.Value, fixAllContext.CancellationToken).ConfigureAwait(false);
+                            var unused = PooledDictionary<Document, ImmutableArray<Diagnostic>>.GetInstance(out var builder);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs:78]: we have helpers already that go from an mutable dict builder with ArrayBuilder values, which can then be converted to an immutable/immutable collection.  The extension is called MultiAdd, and you can see the pattern in CodeFixService.cs i believe.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs [hunk 12]
```diff
@@ -137,8 +183,90 @@ public static string GetDefaultFixAllTitle(FixAllContext fixAllContext)
...
             };
         }
+
+        public static async Task<ImmutableDictionary<Document, ImmutableArray<TextSpan>>> GetDocumentsAndSpansForContainingMemberOrTypeAsync(
+            Document document, FixAllScope fixAllScope, TextSpan triggerSpan, CancellationToken cancellationToken)
+        {
+            Contract.ThrowIfFalse(fixAllScope is FixAllScope.ContainingMember or FixAllScope.ContainingType);
+
+            var decl = await GetContainingMemberOrTypeDeclarationAsync(document, fixAllScope, triggerSpan, cancellationToken).ConfigureAwait(false);
+            if (decl == null)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs:198]: when does this happen?  do we offer such a fixallscope if the user is not in sucha  scope?

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs [hunk 13]
```diff
@@ -137,8 +183,90 @@ public static string GetDefaultFixAllTitle(FixAllContext fixAllContext)
...
+                return ImmutableDictionary<Document, ImmutableArray<TextSpan>>.Empty;
+
+            if (fixAllScope == FixAllScope.ContainingMember)
+            {
+                return ImmutableDictionary<Document, ImmutableArray<TextSpan>>.Empty
+                    .SetItem(document, ImmutableArray.Create(decl.FullSpan));
+            }
+            else
+            {
+                var semanticModel = await document.GetRequiredSemanticModelAsync(cancellationToken).ConfigureAwait(false);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs:208]: this seems to be C#/VB specific, whcih concerns me.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/SyntaxEditorBasedCodeFixProvider.cs [hunk 14]
```diff
@@ -13,10 +13,18 @@ namespace Microsoft.CodeAnalysis.CodeFixes
...
+        private static readonly ImmutableArray<FixAllScope> s_defaultSupportedFixAllScopes =
+            ImmutableArray.Create(FixAllScope.Document, FixAllScope.Project, FixAllScope.Solution,
+                FixAllScope.ContainingMember, FixAllScope.ContainingType);
+
         private readonly bool _supportsFixAll;
+        private readonly ImmutableArray<FixAllScope> _supportedFixAllScopes;
 
-        protected SyntaxEditorBasedCodeFixProvider(bool supportsFixAll = true)
-            => _supportsFixAll = supportsFixAll;
+        protected SyntaxEditorBasedCodeFixProvider(bool supportsFixAll = true, ImmutableArray<FixAllScope> supportedFixAllScopes = default)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/SyntaxEditorBasedCodeFixProvider.cs:23]: what are the features that pass something other than default here?

File: src/Features/Core/Portable/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs (hunk 1 above)
Comment (mavasani) [reply src/Features/Core/Portable/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs:218]: That is outside the scope of this PR. If we want to add support for these scopes in TS/F#, we would need some way to be able to query them to get the containing member span for trigger position.

File: src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt (hunk 2 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt:2]: @jmarolf Yes, these APIs are intentionally public. Otherwise, public clients such as MS.CA.Testing library, would be unable to create a FixAll provider that supports these new FixAll scopes. We can certainly keep them internal in this PR and have a separate PR to just make these APIs public.

File: src/EditorFeatures/Core/Shared/Extensions/TelemetryExtensions.cs (hunk 3 above)
Comment (mavasani) [reply src/EditorFeatures/Core/Shared/Extensions/TelemetryExtensions.cs:43]: Ah, thanks good catch. I'll make the change.

File: src/Features/Core/Portable/CodeFixes/CodeFixService.cs (hunk 4 above)
Comment (mavasani) [reply src/Features/Core/Portable/CodeFixes/CodeFixService.cs:763]: No, the IDE DiagnosticAnalyzerService uses different diagnostic getters for span based diagnostic queries and full document diagnostic queries, each of which is optimized for span vs full-span scenarios. [LatestDiagnosticsForSpanGetter](https://sourceroslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnosticsForSpan.cs,55) for span based queries and [IdeLatestDiagnosticGetter](https://sourceroslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs,35) for full document/project/solution queries.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs (hunk 5 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs:126]: So, for 99% cases we expect a single FixAll span entry here. We get multiple FixAll spans within a document only for the case where a single named type has multiple partial definitions defined in the same file, which is almost never the case in real code bases. I don't think we need to optimize for this corner case.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.SpanBasedDiagnosticProvider.cs (hunk 6 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.SpanBasedDiagnosticProvider.cs:19]: @jmarolf This type is already public. Note that this PR is not for FixAll support for code refactorings that we discussed last week. This PR is extending the existing FixAll feature and public APIs for diagnostics/code fixes to add new fix all scopes.

File: src/Features/Core/Portable/FeaturesResources.resx (hunk 7 above)
Comment (mavasani) [reply src/Features/Core/Portable/FeaturesResources.resx:742]: Ah, yes. Copy-paste is bad.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs (hunk 9 above)
Comment (mavasani) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs:67]: As explained in https://github.com/dotnet/roslyn/pull/59989#discussion_r821315635, multiple fix all spans is going to be an extreme corner case here that we do not need to optimize for. For all practical purposes and performance measurements, we should just assume a single FixAll span within a document.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs (hunk 10 above)
Comment (mavasani) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs:63]: Same comment as above https://github.com/dotnet/roslyn/pull/59989#discussion_r821317353. We don't need to optimize for multiple fix all spans within a document case here.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs (hunk 12 above)
Comment (mavasani) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs:198]: This will happen for file level diagnostics, say unnecessary usings. We will not show such a fix scope to users for a code fix to such diagnostics. That filtering is done here: https://github.com/dotnet/roslyn/pull/59989#discussion_r820627128

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs (hunk 13 above)
Comment (mavasani) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs:208]: Yes, that is intentionally so for this PR to keep it simple and limit the newly added scopes to just C#/VB for now. As mentioned in https://github.com/dotnet/roslyn/pull/59989#discussion_r821310498, we can absolutely enhance this in future to enable TS/F# to support these scopes, for which we would need to extract out all the code to map a trigger span to containing member/type span to some language service. I didn't want to add it here to avoid making this PR unnecessary bulkier.

File: src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt (hunk 2 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt:2]: https://github.com/dotnet/roslyn/issues/60029 tracks making APIs public. I'll switch the APIs to internal for this PR

File: src/Features/Core/Portable/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs (hunk 1 above)
Comment (mavasani) [reply src/Features/Core/Portable/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs]: I actually went ahead and did this refactoring in this PR itself with https://github.com/dotnet/roslyn/pull/59989/commits/64baa64648a00220629e760d343a8b237728a9be. Other languages can now implement the `IFixAllSpanMappingService` language service to enable fix all for these new scopes.

File: src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt (hunk 2 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt]: I have internalized most of these APIs with https://github.com/dotnet/roslyn/pull/59989/commits/2df4e07f971dc80771b249de77e04c453eea0d9f. I still had to retain one public API. I will open an issue with the public API proposals.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs (hunk 11 above)
Comment (mavasani) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs:79]: None of the existing overloads work for this case as we need to append array of diagnostics in each loop iteration. Also given we don't expect multiple fix all spans for each document in majority of cases, we should be fine here.

**Comment by mavasani** [comment]
> Thinking in it more. Maybe change the name to something simple then doc which Scopes this is NOT called for. Then doc that this is a way for a language to customize any other scopes that are supported. ?

Thanks. Done with https://github.com/dotnet/roslyn/pull/59989/commits/de6c22d33b281ef333c941fa0c87fef589bc2f36

File: src/EditorFeatures/Core/Shared/Extensions/TelemetryExtensions.cs [hunk 15]
```diff
@@ -40,7 +40,10 @@ public static short GetScopeIdForTelemetry(this FixAllScope scope)
                 FixAllScope.Document => 1,
                 FixAllScope.Project => 2,
                 FixAllScope.Solution => 3,
-                _ => 4,
+                FixAllScope.Custom => 4,
+                FixAllScope.ContainingMember => 5,
+                FixAllScope.ContainingType => 6,
+                _ => 7,
```
Comment (jmarolf) [inline src/EditorFeatures/Core/Shared/Extensions/TelemetryExtensions.cs:46]: hate to nit on this but before we reported `Custom` or `Unknown` as `4`. now we report `Custom` as 4 and `Unknown` as 7. I am fine taking this change but I just need to review out telemetry scripts and make sure I account for this new split. I'll reply back with a :+1: when I am sure we can handle this across past and future telemetry.

**Comment by mavasani** [comment]
@jmarolf @CyrusNajmabadi any other feedback here? I have filed a separate issue for public API review, and will take care of any API changes as part of that work. Can you please review if this PR looks fine functionality wise to merge in?

File: src/Features/LanguageServer/Protocol/Features/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs [hunk 16]
```diff
@@ -207,9 +213,19 @@ static CodeFixGroupKey GetGroupKey(CodeFix fix)
                 return null;
             }
 
+            var document = fixAllState.Document!;
             using var fixAllSuggestedActionsDisposer = ArrayBuilder<IUnifiedSuggestedAction>.GetInstance(out var fixAllSuggestedActions);
             foreach (var scope in supportedScopes)
             {
+                if (scope is FixAllScope.ContainingMember or FixAllScope.ContainingType &&
+                    document.GetLanguageService<IFixAllSpanMappingService>() is IFixAllSpanMappingService spanMappingService)
```
Comment (CyrusNajmabadi) [inline src/Features/LanguageServer/Protocol/Features/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs:221]: interesting.  so if we have a scope of ContainingMember/Type and the language does *not* export sucha  service, then we proceed?  should we filter those out instead?

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DefaultFixAllProviderHelpers.cs [hunk 17]
```diff
@@ -74,5 +75,28 @@ internal static class DefaultFixAllProviderHelpers
...
+                return null;
+
+            var documentsAndSpansToFix = await spanMappingService.GetFixAllSpansAsync(
+                fixAllContext.Document, fixAllContext.State.TriggerSpan.Value,
+                fixAllContext.Scope, fixAllContext.CancellationToken).ConfigureAwait(false);
+            if (documentsAndSpansToFix.IsEmpty)
+                return null;
+
+            var fixAllContexts = documentsAndSpansToFix.SelectAsArray(
+                (documentAndSpans) => fixAllContext.WithDocumentAndProject(documentAndSpans.Key, documentAndSpans.Key.Project)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DefaultFixAllProviderHelpers.cs:97]: asides: WithDoucmentAndProject feels somewhat weird given that a project is inferrable from a DOcument.  
also, i'm nto a fan of all the separate With'ers.  Could just have one and do `With(document: docAndSpan.Key, fixAllSpans: docAndSpan.Value)`

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs (hunk 5 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs:127]: my general concern is simply that the builder approach is just as easy to write, and works well for the 1 to many case.  I agree it's unlikely, but really rthe ImmutableArray.AddRange approach really stands out like a sort thumb as "this is just waiting for an unfortunate case.  Note: sam's TemporaryArray is great here.  just do:

```c#
using var diagnostics = TemporaryArray<Diagnostic>Empty;
```

As fast for the normal case (<4 items), and no pathlogical dropoff.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.SpanBasedDiagnosticProvider.cs [hunk 18]
```diff
@@ -0,0 +1,41 @@
...
+        /// method to compute diagnostics for a given span within a document.
+        /// We need to compute diagnostics for a span when applying a fix all operation in <see cref="FixAllScope.ContainingMember"/>
+        /// and <see cref="FixAllScope.ContainingType"/> scopes.
+        /// A regular <see cref="DiagnosticProvider"/> will compute diagnostics for the entire document and filter out
+        /// diagnostics outside the span as a post-filtering step.
+        /// A <see cref="SpanBasedDiagnosticProvider"/> can do this more efficiently by implementing the
+        /// <see cref="GetDocumentSpanDiagnosticsAsync(Document, TextSpan, CancellationToken)"/> method to compute
+        /// the diagnostics only for the given 'fixAllSpan' upfront.
+        /// </summary>
+        internal abstract class SpanBasedDiagnosticProvider : DiagnosticProvider
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.SpanBasedDiagnosticProvider.cs:33]: what is slightly unclear to me is who is intended to subclass this.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs [hunk 19]
```diff
@@ -88,12 +96,50 @@ public partial class FixAllContext
             IEnumerable<string> diagnosticIds,
             DiagnosticProvider fixAllDiagnosticProvider,
             CancellationToken cancellationToken)
+            : this(document, triggerSpan: null, codeFixProvider, scope,
+                  codeActionEquivalenceKey, diagnosticIds, fixAllDiagnosticProvider, cancellationToken)
+        {
+            if (scope is FixAllScope.ContainingMember or FixAllScope.ContainingType)
+            {
+                throw new ArgumentException(WorkspacesResources.Fixallscope_containingtype_and_fixallscope_containingmember_are_not_supported_with_this_constructor,
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs:104]:
```suggestion
                throw new ArgumentException(WorkspacesResources.FixAllScope_ContainingType_and_FixAllScope_ContainingMember_are_not_supported_with_this_constructor,
```

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs [hunk 20]
```diff
@@ -163,23 +216,55 @@ public async Task<ImmutableArray<Diagnostic>> GetDocumentDiagnosticsAsync(Docume
...
+            ImmutableHashSet<string> diagnosticIds,
+            TextSpan? filterSpan)
         {
             if (getDiagnosticsTask != null)
             {
                 var diagnostics = await getDiagnosticsTask.ConfigureAwait(false);
                 if (diagnostics != null)
                 {
-                    return diagnostics.Where(d => d != null && diagnosticIds.Contains(d.Id)).ToImmutableArray();
+                    return diagnostics.Where(d => d != null && diagnosticIds.Contains(d.Id)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs:232]:
```suggestion
                    return diagnostics.WhereAsArray(d => d != null && diagnosticIds.Contains(d.Id)
```

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs [hunk 21]
```diff
@@ -163,23 +216,55 @@ public async Task<ImmutableArray<Diagnostic>> GetDocumentDiagnosticsAsync(Docume
...
+            }
+
+            Task<IEnumerable<Diagnostic>>? getDiagnosticsTask;
+            if (State.DiagnosticProvider is FixAllContext.SpanBasedDiagnosticProvider spanBasedDiagnosticProvider)
+            {
+                getDiagnosticsTask = spanBasedDiagnosticProvider.GetDocumentSpanDiagnosticsAsync(document, filterSpan, this.CancellationToken);
+            }
+            else
+            {
+                getDiagnosticsTask = State.DiagnosticProvider.GetDocumentDiagnosticsAsync(document, this.CancellationToken);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs:262]: is there somethign that post-filters the diagnostics from this to the passed in filterspan?  i'm not seeing it.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs [hunk 22]
```diff
@@ -163,23 +216,55 @@ public async Task<ImmutableArray<Diagnostic>> GetDocumentDiagnosticsAsync(Docume
...
             var getDiagnosticsTask = State.DiagnosticProvider.GetDocumentDiagnosticsAsync(document, this.CancellationToken);
-            return await GetFilteredDiagnosticsAsync(getDiagnosticsTask, this.DiagnosticIds).ConfigureAwait(false);
+            return await GetFilteredDiagnosticsAsync(getDiagnosticsTask, this.DiagnosticIds, filterSpan: null).ConfigureAwait(false);
         }
 
-        private static async Task<ImmutableArray<Diagnostic>> GetFilteredDiagnosticsAsync(Task<IEnumerable<Diagnostic>> getDiagnosticsTask, ImmutableHashSet<string> diagnosticIds)
+        private static async Task<ImmutableArray<Diagnostic>> GetFilteredDiagnosticsAsync(
+            Task<IEnumerable<Diagnostic>> getDiagnosticsTask,
+            ImmutableHashSet<string> diagnosticIds,
+            TextSpan? filterSpan)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs:225]: is this only called from one place?  consider making nested helper method.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs [hunk 23]
```diff
@@ -163,23 +216,55 @@ public async Task<ImmutableArray<Diagnostic>> GetDocumentDiagnosticsAsync(Docume
...
         {
             if (getDiagnosticsTask != null)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs:227]: can' this actually ever be null?  i'm not seeing how.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllProvider.cs [hunk 24]
```diff
@@ -59,6 +59,38 @@ public static FixAllProvider Create(Func<FixAllContext, Document, ImmutableArray
             return new CallbackDocumentBasedFixAllProvider(fixAllAsync);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllProvider.cs:59]: consider having this method defer to the one below it.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllProvider.cs [hunk 25]
```diff
@@ -68,6 +100,14 @@ public CallbackDocumentBasedFixAllProvider(Func<FixAllContext, Document, Immutab
                 _fixAllAsync = fixAllAsync;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllProvider.cs:100]: my *string* preference is that constructors chain horizontally in a type (e.g. use `this`), then a single constructor uses `base` to walk up the inheritance hierarchy.  That way any special logic (like assigning fields) is always only in one constructor.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllScope.cs [hunk 26]
```diff
@@ -12,6 +12,8 @@ public enum FixAllScope
         Document,
         Project,
         Solution,
-        Custom
+        Custom,
+        ContainingMember,
+        ContainingType,
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllScope.cs:17]: public API.  please consider doc'ing.

File: src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt [hunk 27]
```diff
@@ -1,5 +1,9 @@
...
+Microsoft.CodeAnalysis.CodeFixes.FixAllScope.ContainingMember = 4 -> Microsoft.CodeAnalysis.CodeFixes.FixAllScope
+Microsoft.CodeAnalysis.CodeFixes.FixAllScope.ContainingType = 5 -> Microsoft.CodeAnalysis.CodeFixes.FixAllScope
 Microsoft.CodeAnalysis.Editing.SyntaxEditor.SyntaxEditor(Microsoft.CodeAnalysis.SyntaxNode root, Microsoft.CodeAnalysis.Host.HostWorkspaceServices services) -> void
 *REMOVED*static Microsoft.CodeAnalysis.Editing.SyntaxGenerator.DefaultRemoveOptions -> Microsoft.CodeAnalysis.SyntaxRemoveOptions
+static Microsoft.CodeAnalysis.CodeFixes.FixAllProvider.Create(System.Func<Microsoft.CodeAnalysis.CodeFixes.FixAllContext, Microsoft.CodeAnalysis.Document, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostic>, System.Threading.Tasks.Task<Microsoft.CodeAnalysis.Document>> fixAllAsync, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CodeFixes.FixAllScope> supportedFixAllScopes) -> Microsoft.CodeAnalysis.CodeFixes.FixAllProvider
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt:6]: we could consider not making this public for now, right? (i'm fine either way).

File: src/Workspaces/Core/Portable/WorkspacesResources.resx [hunk 28]
```diff
@@ -576,4 +576,10 @@
   <data name="Predefined_conversion_from_0_to_1" xml:space="preserve">
     <value>Predefined conversion from {0} to {1}.</value>
   </data>
+  <data name="Fixallscope_containingtype_and_fixallscope_containingmember_are_not_supported_with_this_constructor" xml:space="preserve">
+    <value>'FixAllScope.ContainingType' and 'FixAllScope.ContainingMember' are not supported with this constructor</value>
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/WorkspacesResources.resx:580]: so the loc strings should match the actual english content as much as possible.  so that means matching cases as well.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAll/FixAllState.cs [hunk 29]
```diff
@@ -28,24 +29,42 @@ internal sealed partial class FixAllState
         public FixAllScope Scope { get; }
         public CodeActionOptionsProvider CodeActionOptionsProvider { get; }
 
+        // Note: TriggerSpan can be null from the back-compat public constructor of FixAllContext.
+        public TextSpan? TriggerSpan { get; }
+
+        /// <summary>
+        /// Optional fix all spans to be fixed within the document. Can be empty
+        /// if fixing the entire document, project or solution.
+        /// If non-empty, <see cref="Document"/> is guaranteed to be not null.
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAll/FixAllState.cs:38]:
```suggestion
        /// If non-empty, <see cref="Document"/> is guaranteed to be not <see langword="default"/>.
```

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAll/FixAllState.cs [hunk 30]
```diff
@@ -64,29 +83,37 @@ public FixAllState WithCodeActionEquivalenceKey(string? codeActionEquivalenceKey
...
 
+        public FixAllState WithFixAllSpans(ImmutableArray<TextSpan> fixAllSpans)
+            => With(fixAllSpans: fixAllSpans);
+
         public FixAllState With(
             Optional<(Document? document, Project project)> documentAndProject = default,
             Optional<FixAllScope> scope = default,
-            Optional<string?> codeActionEquivalenceKey = default)
+            Optional<string?> codeActionEquivalenceKey = default,
+            Optional<ImmutableArray<TextSpan>> fixAllSpans = default)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAll/FixAllState.cs:93]: happy there is a 'With' here :)  i wish that other type was written the same way.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs [hunk 31]
```diff
@@ -50,6 +54,49 @@ internal static class FixAllContextHelper
 
                     break;
 
+                case FixAllScope.ContainingMember or FixAllScope.ContainingType:
+                    if (document != null && !await document.IsGeneratedCodeAsync(cancellationToken).ConfigureAwait(false))
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs:58]: doc why the IsGeneratedCode check.  i'm not getting why that is here.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs [hunk 32]
```diff
@@ -50,6 +54,49 @@ internal static class FixAllContextHelper
...
+                                triggerSpan.Value, fixAllContext.Scope, fixAllContext.CancellationToken).ConfigureAwait(false);
+                            var unused = PooledDictionary<Document, ImmutableArray<Diagnostic>>.GetInstance(out var builder);
+                            foreach (var (documentToFix, spans) in documentsAndSpans)
+                            {
+                                foreach (var span in spans)
+                                {
+                                    var documentDiagnostics = await fixAllContext.GetDocumentSpanDiagnosticsAsync(documentToFix, span).ConfigureAwait(false);
+                                    if (builder.TryGetValue(documentToFix, out var existingDiagnostics))
+                                    {
+                                        documentDiagnostics = existingDiagnostics.AddRange(documentDiagnostics);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs:87]: i don't get what's happening here.  if we just computed the doc span diagnostics 3 lines above... why are we adding other diagnostics to it?

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/SyntaxEditorBasedCodeFixProvider.cs [hunk 33]
```diff
@@ -13,10 +13,16 @@ namespace Microsoft.CodeAnalysis.CodeFixes
...
+            ImmutableArray.Create(FixAllScope.Document, FixAllScope.Project, FixAllScope.Solution,
+                FixAllScope.ContainingMember, FixAllScope.ContainingType);
+
         private readonly bool _supportsFixAll;
 
         protected SyntaxEditorBasedCodeFixProvider(bool supportsFixAll = true)
-            => _supportsFixAll = supportsFixAll;
+        {
+            _supportsFixAll = supportsFixAll;
+        }
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/SyntaxEditorBasedCodeFixProvider.cs:25]: unnecessary change.  but fine if you prefer the block form.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs [hunk 34]
```diff
@@ -0,0 +1,91 @@
...
+using Microsoft.CodeAnalysis.Shared.Extensions;
+using Microsoft.CodeAnalysis.Text;
+using Roslyn.Utilities;
+
+namespace Microsoft.CodeAnalysis.CodeFixes
+{
+    internal abstract class AbstractFixAllSpanMappingService : IFixAllSpanMappingService
+    {
+        public async Task<ImmutableDictionary<Document, ImmutableArray<TextSpan>>> GetFixAllSpansAsync(
+           Document document, TextSpan triggerSpan, FixAllScope fixAllScope, CancellationToken cancellationToken)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs:19]: incorrect indentation.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs [hunk 35]
```diff
@@ -0,0 +1,91 @@
...
+            Contract.ThrowIfFalse(fixAllScope is FixAllScope.ContainingMember or FixAllScope.ContainingType);
+
+            var decl = await GetContainingMemberOrTypeDeclarationAsync(document, fixAllScope, triggerSpan, cancellationToken).ConfigureAwait(false);
+            if (decl == null)
+                return ImmutableDictionary<Document, ImmutableArray<TextSpan>>.Empty;
+
+            if (fixAllScope == FixAllScope.ContainingMember)
+            {
+                return ImmutableDictionary<Document, ImmutableArray<TextSpan>>.Empty
+                    .SetItem(document, ImmutableArray.Create(decl.FullSpan));
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs:30]: nit:

```suggestion
                    .Add(document, ImmutableArray.Create(decl.FullSpan));
```

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs [hunk 36]
```diff
@@ -0,0 +1,91 @@
...
+                    var syntaxFacts = document.GetRequiredLanguageService<ISyntaxFactsService>();
+                    _ = PooledDictionary<Document, ImmutableArray<TextSpan>>.GetInstance(out var builder);
+                    foreach (var syntaxRef in symbol.DeclaringSyntaxReferences)
+                    {
+                        var documentForLocation = document.Project.GetDocument(syntaxRef.SyntaxTree);
+                        if (documentForLocation == null)
+                            continue;
+                        var root = await syntaxRef.SyntaxTree.GetRootAsync(cancellationToken).ConfigureAwait(false);
+                        var partialDeclSpan = syntaxFacts.GetContainingTypeDeclaration(root, syntaxRef.Span.Start)!.FullSpan;
+                        builder.MultiAdd(documentForLocation, partialDeclSpan);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs:47]: multi-add works with immutable-array?

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs [hunk 37]
```diff
@@ -0,0 +1,91 @@
...
+                    }
+
+                    return builder.ToImmutableDictionary();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs:50]:
```suggestion
                    return builder.ToImmutableDictionary(kvp => kcp.Key, kvp => kvp.Value.ToImmutable());
```

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs [hunk 38]
```diff
@@ -0,0 +1,91 @@
...
+            var syntaxFacts = document.GetRequiredLanguageService<ISyntaxFactsService>();
+
+            var startContainer = fixAllScope == FixAllScope.ContainingMember
+                ? syntaxFacts.GetContainingMemberDeclaration(root, triggerSpan.Start)
+                : syntaxFacts.GetContainingTypeDeclaration(root, triggerSpan.Start);
+
+            if (fixAllScope == FixAllScope.ContainingMember && !syntaxFacts.IsMethodLevelMember(startContainer))
+                return null;
+
+            if (triggerSpan.IsEmpty || startContainer == null)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs:78]: 1. can you split this heck, it's pretty confusing.  especially "if start is null, return start".

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensionsResources.resx [hunk 39]
```diff
@@ -129,6 +129,12 @@
   <data name="Fix_all_0_in_Solution" xml:space="preserve">
     <value>Fix all '{0}' in Solution</value>
   </data>
+  <data name="Fix_all_0_in_Containing_Member" xml:space="preserve">
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/WorkspaceExtensionsResources.resx:132]: string doesn't match text (casing).

**Review by CyrusNajmabadi — CHANGES_REQUESTED** [review]
overall strongly like this.  but a few things i def would like to see a little attention on (And clarity).  thanks!

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DefaultFixAllProviderHelpers.cs (hunk 17 above)
[the remark this answers is not in the document]
Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DefaultFixAllProviderHelpers.cs:97]: A code style analyzer or refactoring to suggest this change would be good :-)

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs (hunk 20 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs:232]: `WhereAsArray` is an extension method on `ImmutableArray<T>`, but not available on `IEnumerable<T>`

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs [hunk 40]
```diff
@@ -163,23 +216,55 @@ public async Task<ImmutableArray<Diagnostic>> GetDocumentDiagnosticsAsync(Docume
...
+        /// Gets all the diagnostics in the given <paramref name="filterSpan"/> for the given <paramref name="document"/> filtered by <see cref="DiagnosticIds"/>.
+        /// </summary>
+        public async Task<ImmutableArray<Diagnostic>> GetDocumentSpanDiagnosticsAsync(Document document, TextSpan filterSpan)
+        {
+            if (document == null)
+            {
+                throw new ArgumentNullException(nameof(document));
+            }
+
+            if (this.Project.Language != document.Project.Language)
```
[the remark this answers is not in the document]
Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs:250]: Few things to note:
1. This is a check for a public API input, that mimics the existing checks for other similar public APIs in this type: https://github.com/dotnet/roslyn/blob/7bb079e5ceb700d1772b88f7f1b798807fe31805/src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs#L150-L163
2. This public API is used by custom FixAllProviders to compute diagnostics to fix in any given document that is part of the FixAllScope that the provider has been asked to fix. For a multi-language solution, a FixAll in solution will span all documents in the solution, but current FixAll implementation and design only supports fixing the projects whose language match the FixAll trigger document language - FixAll in C# document will not fix similar VB documents. It is possible that custom FixAllProviders call this API for all documents in the solution, and the API appropriately returns empty set of diagnostics to fix in documents of different language that the trigger document language.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DefaultFixAllProviderHelpers.cs (hunk 17 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DefaultFixAllProviderHelpers.cs:97]: There are existing callsites for this API that pass a null document and non-null project: https://github.com/dotnet/roslyn/blob/7e835c8c324e294b467ba69648a2049e3acbcc6f/src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DefaultFixAllProviderHelpers.cs#L51 and https://github.com/dotnet/roslyn/blob/7e835c8c324e294b467ba69648a2049e3acbcc6f/src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DefaultFixAllProviderHelpers.cs#L75

> i'm nto a fan of all the separate With'ers

I agree, but going to leave this as is to avoid unrelated stylistic API changes in this PR.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs [hunk 41]
```diff
@@ -163,23 +216,55 @@ public async Task<ImmutableArray<Diagnostic>> GetDocumentDiagnosticsAsync(Docume
             }
 
             var getDiagnosticsTask = State.DiagnosticProvider.GetDocumentDiagnosticsAsync(document, this.CancellationToken);
-            return await GetFilteredDiagnosticsAsync(getDiagnosticsTask, this.DiagnosticIds).ConfigureAwait(false);
+            return await GetFilteredDiagnosticsAsync(getDiagnosticsTask, this.DiagnosticIds, filterSpan: null).ConfigureAwait(false);
         }
 
-        private static async Task<ImmutableArray<Diagnostic>> GetFilteredDiagnosticsAsync(Task<IEnumerable<Diagnostic>> getDiagnosticsTask, ImmutableHashSet<string> diagnosticIds)
+        private static async Task<ImmutableArray<Diagnostic>> GetFilteredDiagnosticsAsync(
+            Task<IEnumerable<Diagnostic>> getDiagnosticsTask,
```
[the remark this answers is not in the document]
Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs:223]: > really don't love seeing tasks of streaming work.

Existing public API :-( https://github.com/dotnet/roslyn/blob/7bb079e5ceb700d1772b88f7f1b798807fe31805/src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.DiagnosticProvider.cs#L23-L28

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllProvider.cs (hunk 24 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllProvider.cs:59]: That method requires supported fix all scopes, and GetDefaultSupportedFixAllScopes is an instance method on FixAllProvider. `CallbackDocumentBasedFixAllProvider` has two ctors, which call into different base type ctors, so these are different code paths.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllProvider.cs (hunk 25 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllProvider.cs:100]: Ideally, yes. But we don't have access to `GetDefaultSupportedFixAllScopes` API here, so we need this ctor to call into the parameterless public ctor of `DocumentBasedFixAllProvider`

File: src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt (hunk 27 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/PublicAPI.Unshipped.txt:6]: `FixAllProvider.Create` is used by the CodeStyle layer to create custom `DocumentBasedFixAllProvider`, and it only has access to public APIs in the Workspace layer. So we need this API to be public if we want CodeStyle NuGet based code fixes to show the new ContainingMember and ContainingType FixAll scopes.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs (hunk 31 above)
Comment (mavasani) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs:58]: This check already existed for `FixAllScope.Document` above, so I just retained it to match behavior for partial type declarations in generated code: https://github.com/dotnet/roslyn/blob/7bb079e5ceb700d1772b88f7f1b798807fe31805/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs#L44-L45

I believe @sharwell added this check to ensure that FixAll operations don't end up changing generated code.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs [hunk 42]
```diff
@@ -50,6 +54,49 @@ internal static class FixAllContextHelper
...
+                            foreach (var fixAllSpan in fixAllSpans)
+                            {
+                                documentDiagnostics = documentDiagnostics.AddRange(await fixAllContext.GetDocumentSpanDiagnosticsAsync(
+                                    document, fixAllSpan).ConfigureAwait(false));
+                            }
+
+                            return ImmutableDictionary<Document, ImmutableArray<Diagnostic>>.Empty.SetItem(document, documentDiagnostics);
+                        }
+                        else if (triggerSpan.HasValue &&
+                            document.GetLanguageService<IFixAllSpanMappingService>() is IFixAllSpanMappingService spanMappingService)
```
[the remark this answers is not in the document]
Comment (mavasani) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs:73]: So this source file is in the shared layer used by CodeStyle and Workspaces layer, so we cannot access the internal APIs to get to `FixAllContext.State.FixAllSpans` or `FixAllContext.TriggerSpan`, we have to pass the `triggerSpan` and `fixAllSpans` as parameters to this method. The reason we need both these parameters is the way `FixAllContext.State` is built up by the `DocumentBasedFixAllProvider` - we start with an instance of `FixAllContext` that just has the original input `triggerSpan` and not yet computed `FixAllSpans`, and later on the `DocumentBasedFixAllProvider` mutates the `FixAllContext.State` to populate it with computed `FixAllSpans` from the original trigger span.
The `BatchFixAllProvider` invokes this shared helper method with the original `FixAllContext` (i.e. with a trigger span, but not yet computed FixAllSpans), while the `DocumentBasedFixAllProvider` invokes this shared helper with the mutated `FixAllContext`, which already has the computed `FixAllSpans`. The if condition in this else if and the prior if check for both these code paths and has appropriate code to compute the final diagnostics to fix. Let me refactor/share/doc this code a bit more to help clarify.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs (hunk 32 above)
Comment (mavasani) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/FixAllContextHelper.cs:87]: Should hopefully be much easier to follow after the refactoring.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/SyntaxEditorBasedCodeFixProvider.cs (hunk 33 above)
Comment (mavasani) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/CodeFixes/SyntaxEditorBasedCodeFixProvider.cs:25]: I had edited the ctor to add another statement and then reverted, but forgot to switch the code back to expression body form.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs [hunk 43]
```diff
@@ -0,0 +1,91 @@
...
+                {
+                    var syntaxFacts = document.GetRequiredLanguageService<ISyntaxFactsService>();
+                    _ = PooledDictionary<Document, ImmutableArray<TextSpan>>.GetInstance(out var builder);
+                    foreach (var syntaxRef in symbol.DeclaringSyntaxReferences)
+                    {
+                        var documentForLocation = document.Project.GetDocument(syntaxRef.SyntaxTree);
+                        if (documentForLocation == null)
+                            continue;
+                        var root = await syntaxRef.SyntaxTree.GetRootAsync(cancellationToken).ConfigureAwait(false);
+                        var partialDeclSpan = syntaxFacts.GetContainingTypeDeclaration(root, syntaxRef.Span.Start)!.FullSpan;
```
[the remark this answers is not in the document]
Comment (mavasani) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs:46]: I had the code as per your suggestion earlier, but VB has the weird syntax nodes where the SourceSpan of the syntax ref is only the ClassStatementSyntax, not the containing ClassBlockSyntax. This code pattern handles both C# and VB correctly. We also have a unit test that verifies the C# and VB partial decl case which guards a regression here.

**Comment by mavasani** [comment]
@CyrusNajmabadi Thank you for the review! I believe I have addressed all your concerns, PTAL.

**Comment by mavasani** [comment]
@CyrusNajmabadi @jmarolf Any further feedback?

**Comment by mavasani** [comment]
@CyrusNajmabadi @jmarolf @333fred I have addressed all the API review feedback from https://github.com/dotnet/roslyn/issues/60029#issuecomment-1071458718

1. Added tests and support for top level statements with https://github.com/dotnet/roslyn/pull/59989/commits/9f346b516da46699fe2a523f0a42e892195632ce. This was a good catch, before this commit the new fix all scopes wouldn't have shown up within top level statements.
2. Renamed `triggerSpan` to `diagnosticSpan` with https://github.com/dotnet/roslyn/pull/59989/commits/85f433755a1f1c3298167032dd7ce0c194c8c7df
3. Switched `GetDocumentSpanDiagnosticsAsync` to internal with https://github.com/dotnet/roslyn/pull/59989/commits/f7ac5cd434c92ba97b9300aabf0d81f01ae6cb25
4. Made rest of the APIs approved in API review public with https://github.com/dotnet/roslyn/pull/59989/commits/516a15b5a51cc8484802a2a1400bb1f412e541bb

**Comment by mavasani** [comment]
Ping @CyrusNajmabadi @jmarolf - hopefully should be a quick review pass

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs [hunk 44]
```diff
@@ -0,0 +1,167 @@
...
+                    if (document != null && !await document.IsGeneratedCodeAsync(cancellationToken).ConfigureAwait(false))
+                    {
+                        // For the 'ContainingMember' and 'ContainingType' scopes, we might be invoked in a couple of different ways:
+                        //  1. Using the fully populated 'FixAllContext', which has already computed, non-empty 'fixAllSpans' for
+                        //     the member or type declaration to fix in the given 'document'. For this scenario, we return the
+                        //     diagnostics for the given fixAllSpans in the document for this scenario.
+                        //  2. Using the original 'FixAllContext' which has the 'triggerSpan' and 'document' for the original code fix, but
+                        //     the 'fixAllSpans' have not yet been computed. For this scenario, we use the 'IFixAllSpanMappingService' to
+                        //     map the triggerSpan and fixAllScope to documents and spans to fix for the containing member or
+                        //     type declaration (and its partials), and then return the diagnostics for each of the documents and fixAllSpans.
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs:54]: this is interesting and thanks for the info.  but could you clarify why some paths have a `fully populated 'FixAllContext', which has already computed, non-empty 'fixAllSpans"`, while some don't?  It's genuinely not clear to me how that would happen.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs [hunk 45]
```diff
@@ -0,0 +1,167 @@
...
+                    foreach (var span in spans)
+                    {
+                        var documentDiagnostics = await fixAllContext.GetDocumentSpanDiagnosticsAsync(document, span).ConfigureAwait(false);
+                        if (!builder.TryGetValue(document, out var arrayBuilder))
+                        {
+                            arrayBuilder = ArrayBuilder<Diagnostic>.GetInstance();
+                            builder.Add(document, arrayBuilder);
+                        }
+
+                        arrayBuilder.AddRange(documentDiagnostics);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs:138]: i believe there's already a multi-add helper for this so you don't need to do the ArrayBuilder stuff above.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs [hunk 46]
```diff
@@ -0,0 +1,167 @@
...
+                {
+                    progressTracker.ItemCompleted();
+                }
+            }
+
+            static async Task<ImmutableDictionary<Document, ImmutableArray<Diagnostic>>> GetSpanDiagnosticsAsync(
+                FixAllContext fixAllContext,
+                IEnumerable<KeyValuePair<Document, ImmutableArray<TextSpan>>> documentsAndSpans)
+            {
+                var builder = PooledDictionary<Document, ArrayBuilder<Diagnostic>>.GetInstance();
```
[the remark this answers is not in the document]
Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs:126]: oh.  this was a move.  n/m. you don't have to change anything thnat was a direct move if you don't want to.

File: src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/CSharpCodeFixVerifier`2+Test.cs [hunk 47]
```diff
@@ -122,7 +122,7 @@ protected override CodeFixContext CreateCodeFixContext(Document document, TextSp
                 CancellationToken cancellationToken)
                 => new(new FixAllState(
                     fixAllProvider: null,
-                    triggerSpan: null,
+                    diagnosticSpan: null,
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/DiagnosticsTestUtilities/CodeActions/CSharpCodeFixVerifier`2+Test.cs:125]: much clearer.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs [hunk 48]
```diff
@@ -107,13 +107,14 @@ public partial class FixAllContext
...
+        /// Creates a new <see cref="FixAllContext"/> with an associated <paramref name="diagnosticSpan"/>.
         /// Use this overload when applying fix all to a diagnostic with a source location and
         /// using <see cref="FixAllScope.ContainingMember"/> or <see cref="FixAllScope.ContainingType"/>
-        /// for the <paramref name="scope"/>.  When using other fix all scopes, <paramref name="triggerSpan"/>
-        /// is not required and other constructor which does not take a triggerSpan can be used instead.
+        /// for the <paramref name="scope"/>.  When using other fix all scopes, <paramref name="diagnosticSpan"/>
+        /// is not required and other constructor which does not take a diagnostic span can be used instead.
         /// </summary>
         /// <param name="document">Document within which fix all occurrences was triggered.</param>
+        /// <param name="diagnosticSpan">Span for the diagnostic for which fix all occurrences was triggered.</param>
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs:117]: Dumb question.  Should we just include the original diagnostic itself?  That seems 'reasonable' to me in that you started with a diagnostic, and you're asking to "fix all" of the diagnostics like it in some scope.

I basically worry that we might need some of the other data on it in the future (like teh properties/etc.) so we might just include it now for completeness.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs [hunk 49]
```diff
@@ -123,14 +123,14 @@ private static async Task<ImmutableArray<Diagnostic>> DetermineDiagnosticsAsync(
...
                     foreach (var fixAllSpan in fixAllContext.State.FixAllSpans)
                     {
-                        diagnostics = diagnostics.AddRange(await fixAllContext.GetDocumentSpanDiagnosticsAsync(
-                            fixAllContext.Document, fixAllSpan).ConfigureAwait(false));
+                        var spanDiagnostics = await fixAllContext.GetDocumentSpanDiagnosticsAsync(fixAllContext.Document, fixAllSpan).ConfigureAwait(false);
+                        diagnostics.AddRange(spanDiagnostics);
                     }
 
-                    return diagnostics;
+                    return diagnostics.ToImmutable();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs:133]: does this code run oop?  if so, consider getting doc diagnostics in parallel.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpFixAllSpanMappingService.cs [hunk 50]
```diff
@@ -19,5 +27,33 @@ internal sealed class CSharpFixAllSpanMappingService : AbstractFixAllSpanMapping
...
+                return ImmutableDictionary<Document, ImmutableArray<TextSpan>>.Empty;
+
+            // Compute the fix all span for the global statements to be fixed.
+            // If the file has non-global statements towards the end, they need to be excluded
+            // from the fix all span.
+            var fixAllSpan = root.FullSpan;
+            var firstNonGlobalStatement = root.ChildNodes().FirstOrDefault(n => n is not GlobalStatementSyntax);
+            if (firstNonGlobalStatement is not null)
+            {
+                // Bail out for error case where a non-global statement precedes global statements.
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpFixAllSpanMappingService.cs:48]: mention that this could would be in error, so it's ok to have this strategy.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpFixAllSpanMappingService.cs [hunk 51]
```diff
@@ -19,5 +27,33 @@ internal sealed class CSharpFixAllSpanMappingService : AbstractFixAllSpanMapping
...
+                if (root.FullSpan.Start == firstNonGlobalStatement.FullSpan.Start)
+                    return ImmutableDictionary<Document, ImmutableArray<TextSpan>>.Empty;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpFixAllSpanMappingService.cs:50]: i don't think this check is right.  for example, you could have 

```
using X;

class C { }

if (x) { ... }
```

What i think you simply want to check is if there is a non-global statement that precedes a global statement.

**Comment by CyrusNajmabadi** [comment]
Done with pass.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs (hunk 44 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs]: Thanks! So, there seemed to be couple of different code paths in to reach this helper and at some place the FixAllSpans were lazily computed and at some they were precomputed and passed around. I have cleaned this up by completely removing `FixAllState.FixAllSpans` property and instead we now always lazily compute these spans right when they are required to compute diagnostics to fix.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DefaultFixAllProviderHelpers.cs [hunk 52]
```diff
@@ -75,28 +73,5 @@ internal static class DefaultFixAllProviderHelpers
                 fixAllContext,
                 sortedProjects.SelectAsArray(p => fixAllContext.WithScope(FixAllScope.Project).WithDocumentAndProject(document: null, p)));
         }
-
-        private static async Task<Solution?> GetContainingMemberOrTypeFixesAsync(FixAllContext fixAllContext, FixAllContexts fixAllContextsAsync)
```
Comment (mavasani) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DefaultFixAllProviderHelpers.cs]: This code path was precomputing and eagerly populating FixAllSpans.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs (hunk 46 above)
[the remark this answers is not in the document]
Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs:110]: Yes, just a code move so will retain this as-is.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs (hunk 45 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs]: `MultiAdd` extension only works if the value being added is a single diagnostic. I have added a new extension `MultiAddRange` and used it.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs (hunk 48 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs:117]: I had started with attempting to use diagnostic as the input, but the CodeFixContext exposes a single span and multiple possible diagnostics of the same ID for the span: https://github.com/dotnet/roslyn/blob/53468b541401e6d1fe358cc4997fcabc37ea987c/src/Workspaces/Core/Portable/CodeFixes/CodeFixContext.cs#L32-L41

Additionally, the `RegisterCodeFix` method has overloads to register a single code action fixing multiple of these diagnostics: https://github.com/dotnet/roslyn/blob/53468b541401e6d1fe358cc4997fcabc37ea987c/src/Workspaces/Core/Portable/CodeFixes/CodeFixContext.cs#L146-L166

So it seemed more logical to stick to the diagnostic span as the input (which is actually `CodeFixContext.Span` to be honest).

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs [hunk 53]
```diff
@@ -123,8 +123,7 @@ public partial class FixAllContext
         /// <see cref="DiagnosticProvider"/> to fetch document/project diagnostics to fix in a <see cref="FixAllContext"/>.
         /// </param>
         /// <param name="cancellationToken">Cancellation token for fix all computation.</param>
-        /// <remarks>TODO: Make API public (tracked by https://github.com/dotnet/roslyn/issues/60029)</remarks>
-        internal FixAllContext(
+        public FixAllContext(
```
[the remark this answers is not in the document]
Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs:126]: I don't think we should - hosts which don't want to support the newly added FixAllScopes don't need to switch over to the new constructor.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs (hunk 49 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs]: This doesn't run in OOP

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpFixAllSpanMappingService.cs (hunk 51 above)
Comment (mavasani) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpFixAllSpanMappingService.cs:52]: Done. thanks

**Comment by mavasani** [comment]
Thanks @CyrusNajmabadi - I believe I have addressed all the comments and cleaned up the code quite a bit more.

File: src/Features/LanguageServer/Protocol/Features/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs [hunk 54]
```diff
@@ -207,9 +213,26 @@ static CodeFixGroupKey GetGroupKey(CodeFix fix)
...
 
+            var document = fixAllState.Document!;
             using var fixAllSuggestedActionsDisposer = ArrayBuilder<IUnifiedSuggestedAction>.GetInstance(out var fixAllSuggestedActions);
             foreach (var scope in supportedScopes)
             {
+                if (scope is FixAllScope.ContainingMember or FixAllScope.ContainingType)
+                {
+                    // Skip showing ContainingMember and ContainingType FixAll scopes if the language
+                    // does not implement 'IFixAllSpanMappingService' langauge service or
+                    // we have no mapped FixAll spans to fix.
```
Comment (CyrusNajmabadi) [inline src/Features/LanguageServer/Protocol/Features/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs:224]: this is a bit odd right?  other languages aren't going to add those FixAllScopes... so how would we get here?  we'd only get these scopes for C#/VB fixers taht update to use this, which means tehre is a mapping service...

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs [hunk 55]
```diff
@@ -27,6 +27,10 @@ private BatchFixAllProvider()
         {
         }
 
+        public override IEnumerable<FixAllScope> GetSupportedFixAllScopes()
+            => ImmutableArray.Create(FixAllScope.Document, FixAllScope.Project,
+                FixAllScope.Solution, FixAllScope.ContainingMember, FixAllScope.ContainingType);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs:32]: oh... i see.  you're making it so that anyone that uses BatchFixAllProvider.Instance now is opted into this... hrmmmm

that's potentialy more concerning.  though i guess we can do this and then filter this out later when we process the diagnostics.  i'm not a huge fan though as i think it might be better to keep old behavior and have people opt in... 

but i do get that this is beneficial for all the C#/VB fixers out there that won't update hat could use this :-/

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs [hunk 56]
```diff
@@ -106,9 +115,21 @@ private static async Task<ImmutableArray<Diagnostic>> DetermineDiagnosticsAsync(
...
+            {
+                if (fixAllContext.Scope is FixAllScope.ContainingMember or FixAllScope.ContainingType)
+                {
+                    var diagnosticsMap = await FixAllContextHelper.GetDocumentDiagnosticsToFixAsync(fixAllContext).ConfigureAwait(false);
+                    return diagnosticsMap.SelectMany(kvp => kvp.Value).AsImmutableOrEmpty();
+                }
+                else
+                {
+                    return await fixAllContext.GetDocumentDiagnosticsAsync(document).ConfigureAwait(false);
+                }
```
[the remark this answers is not in the document]
Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs:129]: basically, the original code looks correct to me :)   it feels like this shoudl move inwards into the helper hte context already exposes.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.SpanBasedDiagnosticProvider.cs [hunk 57]
```diff
@@ -0,0 +1,41 @@
...
+        {
+            /// <summary>
+            /// Gets all the diagnostics to fix for the given <paramref name="fixAllSpan"/> in the given <paramref name="document"/> in a <see cref="FixAllContext"/>.
+            /// </summary>
+            public abstract Task<IEnumerable<Diagnostic>> GetDocumentSpanDiagnosticsAsync(Document document, TextSpan fixAllSpan, CancellationToken cancellationToken);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.SpanBasedDiagnosticProvider.cs:38]: nit: consider returning ImmutableArray.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs [hunk 58]
```diff
@@ -88,8 +96,45 @@ public partial class FixAllContext
             IEnumerable<string> diagnosticIds,
             DiagnosticProvider fixAllDiagnosticProvider,
             CancellationToken cancellationToken)
+            : this(document, diagnosticSpan: null, codeFixProvider, scope,
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs:99]: can we add this to teh *roslyn* banned API list?  taht way we make sure that all our code calls teh new constructor?  i get the benefit of having this still in teh public API.  but we want to be careful we're not accidentally using this.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs (hunk 23 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs:225]: bleagh.  i hate thsi.  but i'm ok with preserving it....

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs [hunk 59]
```diff
@@ -0,0 +1,145 @@
...
+using Microsoft.CodeAnalysis.Text;
+using Roslyn.Utilities;
+
+namespace Microsoft.CodeAnalysis.CodeFixes
+{
+    internal static partial class FixAllContextHelper
+    {
+        public static async Task<ImmutableDictionary<Document, ImmutableArray<Diagnostic>>> GetDocumentDiagnosticsToFixAsync(
+            FixAllContext fixAllContext)
+        {
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs:22]: so why is this not just an internal helper on FixAllContext?

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpFixAllSpanMappingService.cs [hunk 60]
```diff
@@ -0,0 +1,61 @@
...
+            // from the fix all span.
+            var fixAllSpan = root.FullSpan;
+            var firstNonGlobalStatement = root.ChildNodes().FirstOrDefault(n => n is not GlobalStatementSyntax);
+            if (firstNonGlobalStatement is not null)
+            {
+                // Bail out for compiler error case where a non-global statement precedes a global statement.
+                // C# compiler requires all global statements to preceed non-global statements.
+                var globalStatements = root.ChildNodes().OfType<GlobalStatementSyntax>();
+                if (globalStatements.Any(g => firstNonGlobalStatement.SpanStart < g.SpanStart))
+                    return ImmutableDictionary<Document, ImmutableArray<TextSpan>>.Empty;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpFixAllSpanMappingService.cs:52]: this doesn't sppear fixed.  your `root.ChildNodes().FirstOrDefault(n => n is not GlobalStatementSyntax)` will return things like a `using directive`.  That using directive is allowed to come before a normal `global statement`.  but this will return empty here.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs [hunk 61]
```diff
@@ -30,8 +30,16 @@ namespace Microsoft.CodeAnalysis.CodeFixes
     /// </remarks>
     public abstract class DocumentBasedFixAllProvider : FixAllProvider
     {
+        private readonly ImmutableArray<FixAllScope> _supportedFixAllScopes;
+
         protected DocumentBasedFixAllProvider()
         {
+            _supportedFixAllScopes = base.GetSupportedFixAllScopes().ToImmutableArray();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs:37]: fwiw, this feels pretty wonky.  can we not hav FixAllProvider just make a protected internal static with the default `ImmutableArray.Create(FixAllScope.Document, FixAllScope.Project, FixAllScope.Solution)`?  the base woudl just return that.  here, we'd just defer to our other constructor, passing that along.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs [hunk 62]
```diff
@@ -0,0 +1,96 @@
...
+                    .Add(document, ImmutableArray.Create(decl.FullSpan));
+            }
+            else
+            {
+                var semanticModel = await document.GetRequiredSemanticModelAsync(cancellationToken).ConfigureAwait(false);
+                var symbol = semanticModel.GetDeclaredSymbol(decl, cancellationToken);
+                if (symbol?.DeclaringSyntaxReferences.Length > 1)
+                {
+                    var syntaxFacts = document.GetRequiredLanguageService<ISyntaxFactsService>();
+                    var builder = PooledDictionary<Document, ArrayBuilder<TextSpan>>.GetInstance();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs:42]:
```suggestion
                    using var = PooledDictionary<Document, ArrayBuilder<TextSpan>>.GetInstance(out var builder);
```

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs [hunk 63]
```diff
@@ -0,0 +1,96 @@
...
+                        var partialDeclSpan = syntaxFacts.GetContainingTypeDeclaration(root, syntaxRef.Span.Start)!.FullSpan;
+                        builder.MultiAdd(documentForLocation, partialDeclSpan);
+                    }
+
+                    return builder.ToImmutableMultiDictionaryAndFree();
+                }
+                else
+                {
+                    return ImmutableDictionary<Document, ImmutableArray<TextSpan>>.Empty
+                        .SetItem(document, ImmutableArray.Create(decl.FullSpan));
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs:57]:
```suggestion
                    return ImmutableDictionary.create(document, ImmutableArray.Create(decl.FullSpan));
```

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs [hunk 64]
```diff
@@ -0,0 +1,96 @@
...
+            Contract.ThrowIfFalse(fixAllScope is FixAllScope.ContainingMember or FixAllScope.ContainingType);
+
+            var decl = await GetContainingMemberOrTypeDeclarationAsync(document, fixAllScope, diagnosticSpan, cancellationToken).ConfigureAwait(false);
+            if (decl == null)
+                return await GetFixAllSpansIfWithinGlobalStatementAsync(document, diagnosticSpan, fixAllScope, cancellationToken).ConfigureAwait(false);
+
+            if (fixAllScope == FixAllScope.ContainingMember)
+            {
+                return ImmutableDictionary<Document, ImmutableArray<TextSpan>>.Empty
+                    .Add(document, ImmutableArray.Create(decl.FullSpan));
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs:33]:
```suggestion
                return ImmutableDictionary.Create(document, ImmutableArray.Create(decl.FullSpan));
```

probably applies to other code in this PR :)

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs [hunk 65]
```diff
@@ -0,0 +1,96 @@
...
+                ? syntaxFacts.GetContainingMemberDeclaration(root, span.Start)
+                : syntaxFacts.GetContainingTypeDeclaration(root, span.Start);
+
+            if (startContainer == null)
+                return null;
+
+            if (fixAllScope == FixAllScope.ContainingMember && !syntaxFacts.IsMethodLevelMember(startContainer))
+                return null;
+
+            if (span.IsEmpty)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs:83]: when is span empty?

**Review by CyrusNajmabadi — CHANGES_REQUESTED** [review]
done iwth pass.  almost all nits.  did see a concern with global statements.

File: src/Features/LanguageServer/Protocol/Features/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs (hunk 54 above)
Comment (mavasani) [reply src/Features/LanguageServer/Protocol/Features/UnifiedSuggestions/UnifiedSuggestedActionsSource.cs:224]: This is a defensive check in case a third-party code fix provider for a different language returns the new FixAllScopes for `FixAllProvider.GetSupportedFixAllScopes`, but the language itself does not support/implement these scopes.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs (hunk 55 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs:32]: > i see. you're making it so that anyone that uses BatchFixAllProvider.Instance now is opted into this

Yes, this is something Sam and I discussed and decided to change.

> that's potentialy more concerning

I don't think so. Batch fixer works by merging code actions for diagnostics to fixed, and if it works fine for all diagnostics in a document, it should work fine for subset of those in a document as well.

> i'm not a huge fan though as i think it might be better to keep old behavior and have people opt in...

There is no way to opt-in. The BatchFixer is a complete FixAllProvider implementation. We can potentially have a new BatchFixer instance that supports additional modes, but in reality that would mean none of the existing code fixers will ever get updated to support new scopes. I would agree with your concern if this was done for FixAll for code refactorings, as we do not have a good way to guarantee that if it works on a document, it will work on a span. But I think making this assumption for code fixers is fine.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.SpanBasedDiagnosticProvider.cs (hunk 57 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.SpanBasedDiagnosticProvider.cs:38]: I have tried to be consistent with the existing public APIs in the base type: https://github.com/dotnet/roslyn/blob/ac603f8bdde93a35e2e4b9ef95a4674b561ab433/src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.DiagnosticProvider.cs#L23-L39

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs (hunk 58 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs:99]: Sure, I'll do that.

Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContext.cs:99]: Turns out both the existing public constructors for FixAllContext are already part of the banned API list, recommendation is to use the internal constructor overload:
https://github.com/dotnet/roslyn/blob/ac603f8bdde93a35e2e4b9ef95a4674b561ab433/eng/config/BannedSymbols.txt#L9-L10

I'll add even the new public API to this file.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs (hunk 61 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs:37]: Done.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs (hunk 62 above)
Comment (mavasani) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs:42]: PooledDictionary only supports `ToImmutableMultiDictionaryAndFree`, so I ended up using this pattern.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs (hunk 65 above)
Comment (mavasani) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs:83]: Diagnostic with zero span size and non-zero start?

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs (hunk 56 above)
[the remark this answers is not in the document]
Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/DocumentBasedFixAllProvider.cs:129]: Alright, so seems there was lot of wonkiness in the DocumentBasedFixAllProvider code. I have cleaned this all up to directly use the FixAllContextHelper to fetch the per-document diagnostics, and pass the map down to `GetFixedDocumentsAsync` helper. Hopefully, this makes everything much more clear.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs (hunk 59 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs:22]: It's used at couple of places - in `DocumentBasedFixAllProvider` and `FixAllContext.DiagnosticProvider`

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpFixAllSpanMappingService.cs (hunk 60 above)
Comment (mavasani) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpFixAllSpanMappingService.cs:52]: Thanks - I updated the check to now use [SyntaxFacts.IsNamespaceMemberDeclaration](https://sourceroslyn.io/Microsoft.CodeAnalysis.CSharp/R/9217de0879160b70.html), which matches the logic used by the language parser to report this error: https://github.com/dotnet/roslyn/blob/main/src/Compilers/CSharp/Portable/Parser/LanguageParser.cs#L604-L628

**Comment by mavasani** [comment]
Thanks @CyrusNajmabadi - feedback addressed

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs [hunk 66]
```diff
@@ -0,0 +1,145 @@
...
+                foreach (var (document, spans) in documentsAndSpans)
+                {
+                    foreach (var span in spans)
+                    {
+                        var documentDiagnostics = await fixAllContext.GetDocumentSpanDiagnosticsAsync(document, span).ConfigureAwait(false);
+                        builder.MultiAddRange(document, documentDiagnostics);
+                    }
+                }
+
+                return builder.ToImmutableMultiDictionaryAndFree();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs:120]: does this free the inner ArrayBuilder?

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpFixAllSpanMappingService.cs [hunk 67]
```diff
@@ -0,0 +1,61 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+// See the LICENSE file in the project root for more information.
+
+#nullable disable
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpFixAllSpanMappingService.cs:5]: remove.

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpFixAllSpanMappingService.cs [hunk 68]
```diff
@@ -0,0 +1,61 @@
...
+        public CSharpFixAllSpanMappingService()
+        {
+        }
+
+        protected override async Task<ImmutableDictionary<Document, ImmutableArray<TextSpan>>> GetFixAllSpansIfWithinGlobalStatementAsync(
+            Document document, TextSpan diagnosticSpan, FixAllScope fixAllScope, CancellationToken cancellationToken)
+        {
+            Contract.ThrowIfFalse(fixAllScope is FixAllScope.ContainingMember or FixAllScope.ContainingType);
+
+            var root = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/LanguageServices/CSharpFixAllSpanMappingService.cs:36]:
```suggestion
            var root = await document.GetRequiredSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
```

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs [hunk 69]
```diff
@@ -0,0 +1,96 @@
...
+        {
+            Contract.ThrowIfFalse(fixAllScope is FixAllScope.ContainingMember or FixAllScope.ContainingType);
+
+            var decl = await GetContainingMemberOrTypeDeclarationAsync(document, fixAllScope, diagnosticSpan, cancellationToken).ConfigureAwait(false);
+            if (decl == null)
+                return await GetFixAllSpansIfWithinGlobalStatementAsync(document, diagnosticSpan, fixAllScope, cancellationToken).ConfigureAwait(false);
+
+            if (fixAllScope == FixAllScope.ContainingMember)
+            {
+                return ImmutableDictionary<Document, ImmutableArray<TextSpan>>.Empty
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs:32]:
```suggestion
                return ImmutableDictionary.Create(
```

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs [hunk 70]
```diff
@@ -0,0 +1,96 @@
...
+                        var partialDeclSpan = syntaxFacts.GetContainingTypeDeclaration(root, syntaxRef.Span.Start)!.FullSpan;
+                        builder.MultiAdd(documentForLocation, partialDeclSpan);
+                    }
+
+                    return builder.ToImmutableMultiDictionaryAndFree();
+                }
+                else
+                {
+                    return ImmutableDictionary<Document, ImmutableArray<TextSpan>>.Empty
+                        .Add(document, ImmutableArray.Create(decl.FullSpan));
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/LanguageServices/FixAllSpanMappingService/AbstractFixAllSpanMappingService.cs:57]:
```suggestion
                    return ImmutableDictionary.Create(document, ImmutableArray.Create(decl.FullSpan));
```

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs (hunk 66 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/FixAllContextHelper.cs:120]: Yes, it does.
