### PR TITLE
Make var patterns bindable

### LINKED ISSUE #51615: GoToDefinition on `var` in var pattern doesn't navigate to type
It is possible to use GoToDefinition on `var` in local declarations, out variables and deconstructions.
But it doesn't work on a var pattern:
```
string M() { }

void M2()
{
  if (M() is var$$ x && x.Length > 0) // GoToDefinition on `var` should go to definition of `string` type
  {
  }
}
```

Looking at compiler test `SwitchExpression_10`, I think that `GetDeclaredSymbol` and `GetTypeInfo` work on var patterns, so I suspect this is an IDE problem.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #51615

I'm not very comfortable with special casing Var patterns. Will wait for feedback.
cc: @CyrusNajmabadi Since you worked on this in https://github.com/dotnet/roslyn/pull/43395

### CODE REVIEW

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs [hunk 1]
```diff
@@ -1093,6 +1093,11 @@ private static TextSpan GetBlockBodySpan(BlockSyntax body)
                 node = parent;
             }
 
+            if (node is VarPatternSyntax)
```
Comment (Youssef1313) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs:1096]: I could check for `token` to be `VarKeyword` instead of `VarPatternSyntax`. Not sure if it matters, or if there is a better third option.

Comment (CyrusNajmabadi) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs:1096]: This is fine

File: src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs [hunk 2]
```diff
@@ -7087,5 +7087,24 @@ public class Person { public Person(int id) { } }
...
+
+    void M2()
+    {
+      if (M() is va$$r x && x.Length > 0)
+      {
+      }
+    }
+}",
+                MainDescription("class System.String"));
+        }
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs:7108]: Can you add test showing what you get if you're on 'x' instead of 'var'?

**Comment by Youssef1313** [comment]
@CyrusNajmabadi I addressed your feedback. Is this ready to merge?

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks!
