### PR TITLE
Code fix for CS0109 (The new keyword is not required)

### LINKED ISSUE #43661: Code fix for CS0109 (The new keyword is not required)
**Version Used**: 16.6 Preview 3

**Steps to Reproduce**:

1. Create a method that hides a base method with the `new` keyword
2. Rename the method to no longer hide a base method

CS0109 is reported:

> The member 'name' does not hide an accessible member. The new keyword is not required.

**Expected Behavior**:

A code fix is offered which removes the `new` modifier.

**Actual Behavior**:

No code fix is provided. The modifier must be removed manually.

### PR DESCRIPTION
**Pull request by vanashimko**
Closes #43661.

What bothers me in this implementation is hacking through trivia manually. Not sure if it should be done this way, but did not find anything built-in for `SyntaxToken` removing with trivia handling (only for `SyntaxNode`). Would be great if somebody shows me the right way (if it is not).

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs [hunk 1]
```diff
@@ -178,5 +178,123 @@ class App : Application
...
     /* start */ public /* middle */ new readonly /* end */ int Test;
 }");
+
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsRemoveNew)]
+        public async Task TestRemoveNewFromProperty()
+        {
+            await TestInRegularAndScriptAsync(
+@"class App
+{
+    [|public static new App Current|] { get; set; }
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs:188]: span seems weird.  would expect it to only be on `new` keyword.

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+using System.Threading;
+using System.Threading.Tasks;
+using Microsoft.CodeAnalysis.CSharp.Extensions;
+using Microsoft.CodeAnalysis.CSharp.LanguageServices;
+
+namespace Microsoft.CodeAnalysis.CSharp.CodeFixes.HideBase
+{
+    internal partial class HideBaseCodeFixProvider
+    {
+        private class RemoveNewKeywordAction : CodeActions.CodeAction
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs:16]: instead of this, it can just be a DocumetnChangeAction, and just provide an appropriate lambda to do the fixup.  This is what the majority of other fixers do.

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+// See the LICENSE file in the project root for more information.
+
+using System.Diagnostics;
+using System.Linq;
+using System.Threading;
+using System.Threading.Tasks;
+using Microsoft.CodeAnalysis.CSharp.Extensions;
+using Microsoft.CodeAnalysis.CSharp.LanguageServices;
+
+namespace Microsoft.CodeAnalysis.CSharp.CodeFixes.HideBase
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs:12]: odd namespace for this feature.

File: src/Features/CSharp/Portable/CSharpFeaturesResources.resx [hunk 4]
```diff
@@ -445,6 +445,9 @@
   <data name="Hide_base_member" xml:space="preserve">
     <value>Hide base member</value>
   </data>
+  <data name="Remove_new_keyword" xml:space="preserve">
+    <value>Remove 'new' keyword</value>
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CSharpFeaturesResources.resx:449]: i think `Remove 'new' modifier` likely reads better.

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs [hunk 5]
```diff
@@ -17,14 +17,15 @@ namespace Microsoft.CodeAnalysis.CSharp.CodeFixes.HideBase
     internal partial class HideBaseCodeFixProvider : CodeFixProvider
     {
         internal const string CS0108 = nameof(CS0108); // 'SomeClass.SomeMember' hides inherited member 'SomeClass.SomeMember'. Use the new keyword if hiding was intended.
+        internal const string CS0109 = nameof(CS0109); // The member 'SomeClass.SomeMember' does not hide an accessible member. The new keyword is not required.
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs:20]: ah, i see you reused this type.   i would't just make a new type.

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs [hunk 6]
```diff
@@ -54,7 +55,10 @@ public sealed override async Task RegisterCodeFixesAsync(CodeFixContext context)
                 return;
             }
 
-            context.RegisterCodeFix(new AddNewKeywordAction(context.Document, originalNode), context.Diagnostics);
+            if (diagnostic.Id == CS0108)
+                context.RegisterCodeFix(new AddNewKeywordAction(context.Document, originalNode), context.Diagnostics);
+            else if (diagnostic.Id == CS0109)
+                context.RegisterCodeFix(new RemoveNewKeywordAction(context.Document, originalNode), context.Diagnostics);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs:61]: we shuld check to make sure we can *find* teh `new` modifier first before registering the action.  that way there is no way to fail when teh action runs.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxTriviaListExtensions.cs [hunk 7]
```diff
@@ -90,5 +90,24 @@ public static IEnumerable<SyntaxTrivia> TakeRange(this SyntaxTriviaList triviaLi
                 yield return triviaList[start++];
             }
         }
+
+        /// <summary>
+        /// Returns modified <paramref name="triviaList"/> with removed multiple <see cref="SyntaxToken"/>
+        /// with kind <see cref="SyntaxKind.WhitespaceTrivia"/> arranged in a sequence 
+        /// preserving only the first one: [space1][space2][space3] -> [space1]. 
+        /// </summary>
+        public static SyntaxTriviaList CollapseSequentialWhitespaceTrivia(this SyntaxTriviaList triviaList)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxTriviaListExtensions.cs:99]: i don't think we really need this helper.

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs [hunk 8]
```diff
@@ -0,0 +1,79 @@
...
+            protected override async Task<Document> GetChangedDocumentAsync(CancellationToken cancellationToken)
+            {
+                var syntaxFacts = CSharpSyntaxFacts.Instance;
+
+                var newModifier = GetNewModifier(_node);
+                Debug.Assert(newModifier != default, $"'new' keyword was not found, but diagnostic was triggered");
+
+                var newNode = _node;
+
+                if (newModifier.HasTrailingTrivia || newModifier.HasLeadingTrivia)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs:38]: one of these will always be true afaict.

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs [hunk 9]
```diff
@@ -0,0 +1,79 @@
...
+                {
+                    var newModifierTrivia = newModifier.GetAllTrivia().ToSyntaxTriviaList();
+                    var previousToken = newModifier.GetPreviousToken();
+                    var nextToken = newModifier.GetNextToken();
+
+                    var sourceText = _document.GetTextSynchronously(cancellationToken);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs:44]: thi should be `GetTextAsync`

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs [hunk 10]
```diff
@@ -0,0 +1,79 @@
...
+                    {
+                        var nextTokenWithMovedTrivia = nextToken.WithLeadingTrivia(newTrivia);
+                        newNode = newNode.ReplaceToken(nextToken, nextTokenWithMovedTrivia);
+                    }
+                    else
+                    {
+                        var previousTokenWithMovedTrivia = previousToken.WithTrailingTrivia(newTrivia);
+                        newNode = newNode.ReplaceToken(previousToken, previousTokenWithMovedTrivia);
+                    }
+                }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs:65]: a much simpler approach would be:

1. grab all the trivia on the `new` modifier`
2. attach it to the previous token as trailing trivia
3. add an ElasticTrivia to the previous token's trailing trivia as well.

This should ensure the formatter cleans up things like multiple-whitespaces between the previous and next token.

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs [hunk 11]
```diff
@@ -54,7 +55,10 @@ public sealed override async Task RegisterCodeFixesAsync(CodeFixContext context)
                 return;
             }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs:56]: what aobut events?  can they not be 'new'?

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs:56]: what about indexers?

**Comment by CyrusNajmabadi** [comment]
Thanks for the contribution!  Do we need this for VB as well?

**Comment by CyrusNajmabadi** [comment]
Done with pass.

File: src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs (hunk 1 above)
Comment (vanashimko) [reply src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs:188]: Could you please point me to the place where I can read about this syntax `[|. . .|]`? I just copied tests in this file for adding 'new' modifier.

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs (hunk 5 above)
Comment (jnm2) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs:20]: @CyrusNajmabadi is that "would" or "wouldn't"?

**Comment by jnm2** [comment]
> Thanks for the contribution! Do we need this for VB as well?

To clarify, the policy is still that if a feature can apply to VB, it must be implemented for VB too?

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs (hunk 8 above)
Comment (jnm2) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs:38]: Here's an example of a `new` modifier with neither true:

```cs
class C
{
new(int a, int b) x;
}
```

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzhgHwAEAmAAgGEBYAKAG9aA7GAdwAoBLRjM7NMrj2ABKMggDctAL60gA

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs (hunk 6 above)
Comment (jnm2) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs:61]: @CyrusNajmabadi should a SyntaxReference be passed to the fixer or should the logic be called both before registering the fix and while applying the fix?

File: src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs (hunk 1 above)
Comment (jnm2) [reply src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs:188]: I think it represents what the text selection is in the text editor when Ctrl+. is pressed.

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs (hunk 10 above)
Comment (vanashimko) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs:65]: I tried this approach and faced two issues:
1. If `new` is the first token on the line, attaching trivia to previous token seems to be not working at all, it got removed completely. Failed test:
```
 class App
 {
-    /* start */ /* end */ int Test;
+int Test;
 }
```
2. Formatter starts inserting line breaks after multiline comments in elastic trivia. Failed test:
```
 class App
 {
-    /* start */ public /* middle */ /* end */ int Test;
+    /* start */
+    public /* middle */     /* end */ int Test;
 }
```

I thought that I should preserve original code structure as much as possible and reduce any side effects. If I'm on the wrong way, I'd be happy to revisit my hacky approach.

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs (hunk 11 above)
Comment (jnm2) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs:56]: Nested types can also be `new`.

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/classes#the-new-modifier

Comment (jnm2) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs:56]: I think `new` can be used on every kind of member except constructors, finalizers, and operators.
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEA3GUCWAZgJ4A+AAgEwCMAsAFANUAEAwgwN4PM/PkDMzAHYwA7nxTMAsgAoAlMw7MAvt14DhY5viEZmAMQDcanhpHiYuXX2qVmAUWP1efQee3WACouYBzGBiGKiaumuI6ehgAFvgAzgDaEcwADgC6zAC8AHwpTi7uLKx2SqrOvO6xGFAArmB6AMrFwWU87hF4hACGYDDMAJJNpflaACYwADYwvp0YveSSACKU8nnlWjBC1QC2DoMMykA

File: src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs (hunk 1 above)
Comment (vanashimko) [reply src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs:188]: Thanks @jnm2 , in this case I'd put it on the actual member name. @CyrusNajmabadi does it make sense for you?

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs (hunk 11 above)
Comment (vanashimko) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs:56]: I think I can use `token.GetAncestor<MemberDeclarationSyntax>();` instead of these multiple checks. However it will also affect CS0108 fix. That's not an issue if I need to move the entire fixer to a separate class/folder, as it was mentioned in another comment.

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs (hunk 8 above)
Comment (vanashimko) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs:38]: Thanks, interesting example, will add as a test case (together with others like inner class, indexer, etc from another comment after agreeing on updating `HideBaseCodeFixProvider` to support more members in addition to property/method/field).

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs (hunk 5 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs:20]: fixed :)

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs (hunk 6 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs]: easiest is just call the logic both times.  it's simple and cheap enough to do.

**Comment by CyrusNajmabadi** [comment]
> To clarify, the policy is still that if a feature can apply to VB, it must be implemented for VB too?

Our policy has always been: Do VB as well unless:

1. the feature makes zero sense for VB.  i.e. there's no VB analog to "use patterns"
2. the feature is extremely expensive for VB.  However, even then, an explicit decision to not support VB needs to be made.  Note that this is quite rare.

File: src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs]: i would put it on the 'new' modifier since that's what' sbeing removed :)

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs (hunk 10 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs:65]: > If new is the first token on the line, attaching trivia to previous token seems to be not working at all, it got removed completely. Failed test:

something is strange there.  i'd need to see what your code was doing.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs:65]: note: given that 'new' might be first, it's prob best to just attach to next token.  but still add elastic so that multiple whitespace is cleaned up.

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs (hunk 11 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs:56]: > However it will also affect CS0108 fix. That's not an issue if I need to move the entire fixer to a separate class/folder, as it was mentioned in another comment.

i would just do this.

**Comment by jnm2** [comment]
This should be in https://github.com/dotnet/roslyn/blob/master/docs/wiki/Contributing-Code.md

**Comment by CyrusNajmabadi** [comment]
I'll update.

**Comment by vanashimko** [comment]
@CyrusNajmabadi @jnm2 thanks for your review! I will work on fixes for C# implementation.

Also regarding VB fix: in the issue there was only CS0109 mentioned, so I did not think about VB at all. From your comments I'm coming up to conclusion that analog code fix for VB should be done in this PR. Is it correct?

File: src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs (hunk 1 above)
Comment (vanashimko) [reply src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs]: That's strange but in this case all tests are failing with `System.Exception: No action was offered when one was expected. Diagnostics from the compilation:` ("diagnostics from the compilation" looks empty). I've pushed it to a temp branch to not to trigger CI for known failed tests: https://github.com/vanashimko/roslyn/commit/976734b4308aa8c7fbc3f81a766b2e7710c7ae46. In case of putting this on member name, all tests pass. Can this be related not to the code fix itself, but to the way how this diagnostic applied?

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs (hunk 6 above)
Comment (vanashimko) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs]: Thanks, got it. One question: is it safe to pass `SyntaxNode` (`MemberDeclarationSyntax`) reference to `DocumentChangeAction` delegate or I should retrieve it one more time from `Document` inside the actual code fix?

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs (hunk 10 above)
Comment (vanashimko) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs:65]: Thanks, moving to the next token worked better, however, there are still some failing tests due to extra line breaks/spaces inserted. I pushed the code to temp branch: https://github.com/vanashimko/roslyn/commit/4c32b00bcbca08dca21aebb89460357867293391.

Failed tests:
1) 
```
 class App
 {
-    public const int test = 1;
+    public const  int test = 1;
 }
```
2) 
```
 class App
 {
-    /* start */ /* end */ int Test;
+    /* start */
+    /* end */
+    int Test;
 }
```
3) 
```
 class App
 {
-    /* start */ public /* middle */ /* end */ int Test;
+    /* start */ public /* middle */     /* end */ int Test;
 }
```
4) 
 ```
 class App
 {
-    /* start */ public /* middle */ /* end */ int Test;
+    /* start */ public /* middle */  /* end */ int Test;
 }
```
5) 
```
 class App
 {
-    /* end */ int Test;
+    /* end */
+    int Test;
 }
```

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs (hunk 3 above)
Comment (vanashimko) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs]: Moved to a separate class in `Microsoft.CodeAnalysis.CSharp.CodeFixes.RemoveNewModifier`.

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs (hunk 5 above)
Comment (vanashimko) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs]: Moved to `Microsoft.CodeAnalysis.CSharp.CodeFixes.RemoveNewModifier.RemoveNewModifierCodeFixProvider`.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxTriviaListExtensions.cs (hunk 7 above)
Comment (vanashimko) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxTriviaListExtensions.cs]: Moved to a private method for now. Will remove once/if more beautiful solution will be found in separate "trivia handling" thread.

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs (hunk 11 above)
Comment (vanashimko) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs]: Moved to a separate class and used `.GetAncestor<MemberDeclarationSyntax>()` there. Also tests are added for all cases from SharpLab example.

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs (hunk 6 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs]: technically it is discouraged.  but about 80% of our own fixers violate that recommendation, so there's no harm in one more doing it :)

File: src/EditorFeatures/CSharpTest/Diagnostics/RemoveNewModifier/RemoveNewModifierCodeFixProviderTests.cs [hunk 12]
```diff
@@ -0,0 +1,101 @@
...
+            "/* start */ public /* middle */ /* end */ int Test;")]
+        [InlineData(
+            "/* start */ public /* middle */new /* end */ int [|Test|];",
+            "/* start */ public /* middle */ /* end */ int Test;")]
+        [InlineData(
+            "/* start */ public /* middle */ new/* end */ int [|Test|];",
+            "/* start */ public /* middle */ /* end */ int Test;")]
+        [InlineData(
+            "/* start */ public /* middle */new/* end */ int [|Test|];",
+            "/* start */ public /* middle *//* end */ int Test;")]
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Diagnostics/RemoveNewModifier/RemoveNewModifierCodeFixProviderTests.cs:75]: fwiw, most of these tests are not realistic IMO.  i.e. even if they did appear, it would be a 0.001% case.  so exerting a ton of effort to make them work ok just isn't necessary.

File: src/Features/CSharp/Portable/CodeFixes/RemoveNewModifier/RemoveNewModifierCodeFixProvider.cs [hunk 13]
```diff
@@ -0,0 +1,131 @@
...
+using Microsoft.CodeAnalysis.CSharp.LanguageServices;
+using Microsoft.CodeAnalysis.CSharp.Syntax;
+using Microsoft.CodeAnalysis.Shared.Extensions;
+
+namespace Microsoft.CodeAnalysis.CSharp.CodeFixes.RemoveNewModifier
+{
+    [ExportCodeFixProvider(LanguageNames.CSharp, Name = PredefinedCodeFixProviderNames.RemoveNew), Shared]
+    internal class RemoveNewModifierCodeFixProvider : CodeFixProvider
+    {
+        internal const string CS0109 = nameof(CS0109); // The member 'SomeClass.SomeMember' does not hide an accessible member. The new keyword is not required.
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeFixes/RemoveNewModifier/RemoveNewModifierCodeFixProvider.cs:24]: does this need to be internal?

File: src/Features/CSharp/Portable/CodeFixes/RemoveNewModifier/RemoveNewModifierCodeFixProvider.cs [hunk 14]
```diff
@@ -0,0 +1,131 @@
...
+
+        [ImportingConstructor]
+        [SuppressMessage("RoslynDiagnosticsReliability", "RS0033:Importing constructor should be [Obsolete]", Justification = "Used in test code: https://github.com/dotnet/roslyn/issues/42814")]
+        public RemoveNewModifierCodeFixProvider()
+        {
+        }
+
+        public override FixAllProvider GetFixAllProvider()
+            => WellKnownFixAllProviders.BatchFixer;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeFixes/RemoveNewModifier/RemoveNewModifierCodeFixProvider.cs:33]: since you support fix-all, have at least one test that demonstrates it working.

File: src/Features/CSharp/Portable/CodeFixes/RemoveNewModifier/RemoveNewModifierCodeFixProvider.cs [hunk 15]
```diff
@@ -0,0 +1,131 @@
...
+                    newNode = newNode.ReplaceToken(nextToken, nextTokenWithMovedTrivia);
+                }
+                else
+                {
+                    var previousTokenWithMovedTrivia = previousToken.WithTrailingTrivia(newTrivia);
+                    newNode = newNode.ReplaceToken(previousToken, previousTokenWithMovedTrivia);
+                }
+            }
+
+            newNode = newNode.ReplaceToken(GetNewModifier(newNode, syntaxFacts), SyntaxFactory.Token(SyntaxKind.None));
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeFixes/RemoveNewModifier/RemoveNewModifierCodeFixProvider.cs:96]: instead of all the replace-tokens, consider just making a SyntaxEditor.  Then perform two edits on it similar to this:

```c#
editor.ReplaceNode(
  nextToken.Parent,
  nextToken.Parent.ReplaceToken(nextToken, nextTokenWithMovedTrivia));
editor.ReplaceNode(
  memberDecl,
  (current, _) =>
  {
    var currentMemberDecl = (MemberDeclarationSyntax)current;
    return currentMemberDecl.WithModifiers(RemoveNew(currentMemberDecl.Modifiers));
  });
```

File: src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs (hunk 1 above)
Comment (jnm2) [reply src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs]: Yes, I think you have no choice but to make the span include the member name token unless you make changes in the compiler layer which I believe @CyrusNajmabadi would not recommend for this PR.

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs]: > In case of putting this on member name


That's fine then :)

> Yes, I think you have no choice but to make the span include the member name token unless you make changes in the compiler layer which I believe @CyrusNajmabadi would not recommend for this PR.

Correct :)

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs (hunk 6 above)
Comment (vanashimko) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs]: Sorry @CyrusNajmabadi didn't get it :) By "one more doing it" you mean retrieving `SyntaxNode` two times (before registering codefix and inside a codefix) or do it one time and pass the reference into a codefix?

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs (hunk 2 above)
Comment (vanashimko) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs]: Followed this approach with `MyCodeAction` (looked through other fixers and found it there) in new separate `RemoveNewModifierCodeFixProvider`.

File: src/Features/CSharp/Portable/CodeFixes/RemoveNewModifier/RemoveNewModifierCodeFixProvider.cs (hunk 15 above)
Comment (vanashimko) [reply src/Features/CSharp/Portable/CodeFixes/RemoveNewModifier/RemoveNewModifierCodeFixProvider.cs:96]: I'm receiving `current` as `null` when calling `ReplaceNode` with callback: https://github.com/vanashimko/roslyn/commit/067050ef86fd34ab150b22b420163d20dbcd49ff. Seems to be I'm doing something wrong again :(

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs (hunk 10 above)
Comment (vanashimko) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.RemoveNewKeywordAction.cs]: JFYI if somebody is interested, discussion is in progress in the actual commit in another branch: https://github.com/vanashimko/roslyn/commit/4c32b00bcbca08dca21aebb89460357867293391#r38914037

File: src/EditorFeatures/CSharpTest/Diagnostics/RemoveNewModifier/RemoveNewModifierCodeFixProviderTests.cs (hunk 12 above)
Comment (vanashimko) [reply src/EditorFeatures/CSharpTest/Diagnostics/RemoveNewModifier/RemoveNewModifierCodeFixProviderTests.cs:75]: Ok, makes sense, can we move to this thread https://github.com/dotnet/roslyn/pull/43913#discussion_r419067063 for the discussion on what is not necessary to handle? (there is one strange failure there with `const`, for other cases there are just few extra spaces/line breaks)

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs (hunk 6 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.cs]: Either :)

**Comment by CyrusNajmabadi** [comment]
You can see my approach here: https://github.com/CyrusNajmabadi/roslyn/pull/new/issue-43661-elastic-marker

I used the basic approach of:

```c#
        private async Task<Document> FixAsync(
            Document document,
            MemberDeclarationSyntax memberDeclaration,
            CancellationToken cancellationToken)
        {
            var root = await document.GetRequiredSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
            var generator = document.GetRequiredLanguageService<SyntaxGenerator>();

            return document.WithSyntaxRoot(root.ReplaceNode(
                memberDeclaration,
                generator.WithModifiers(
                    memberDeclaration, generator.GetModifiers(memberDeclaration) - DeclarationModifiers.New)));
        }
```

I don't see why it needs to be more complicated than that :)

**Comment by vanashimko** [comment]
> I don't see why it needs to be more complicated than that :)

Thanks for your time @CyrusNajmabadi! I've started hacking this around under impression that I should preserve all the formatting and comments "at any cost". I will follow the approach you suggest.

**Comment by vanashimko** [comment]
@CyrusNajmabadi I accidentally reverted "FixAll" test, will fix.

**Comment by CyrusNajmabadi** [comment]
Not a problem :)

**Comment by vanashimko** [comment]
@CyrusNajmabadi @jnm2 just double-checking: is anything else required from my side?

**Comment by CyrusNajmabadi** [comment]
Nope!  Thanks for the contribution!
