### PR TITLE
Partial methods implementation should match declaration parameter ref kinds

### LINKED ISSUE #25399: partial methods shouldn't be allowed to have different ref-kinds
**Version Used**: master

**Steps to Reproduce**:
```cs
partial class C {
    partial void M(in int i);
    partial void M(ref int i) {}  
}
```
**Expected Behavior**: Error: ref-kind doesn't match

` CS0759: No defining declaration found for implementing declaration of partial method `

**Actual Behavior**: No error

/cc @OmarTawfik

### PR DESCRIPTION
**Pull request by OmarTawfik**
### Customer scenario

Customers should not be able to implement partial methods having parameters with a different ref kind than the definition. The compiler should produce diagnostics and prevent that. Currently, the following invalid code passes without errors:

```csharp
partial class C {
    partial void M(in int i);
    partial void M(ref int i) {}  
}
```

Since this is a breaking change, @dotnet/roslyn-compat-council will be notified and will get approval before merging.

### Bugs this fixes

Fixes #25399

### Workarounds, if any

None.

### Risk

Low risk. This is producing an error in a corner case scenario where code shouldn't have been allowed in first place.

### Performance impact

Negligible.

### Is this a regression from a previous update?

It is a breaking change.

### How was the bug found?

Reported on GitHub by a contributor.

cc @dotnet/roslyn-compiler for review.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs [hunk 1]
```diff
@@ -20096,5 +20096,83 @@ public void MethodA(ClassC obj)
...
+    partial void M(in int i);
+    partial void M(int i) {}  
+}").VerifyDiagnostics(
+                // (4,18): error CS0759: No defining declaration found for implementing declaration of partial method 'C.M(int)'
+                //     partial void M(int i) {}  
+                Diagnostic(ErrorCode.ERR_PartialMethodMustHaveLatent, "M").WithArguments("C.M(int)").WithLocation(4, 18));
+        }
+
+        [Fact]
+        public void PartialMethodsConsiderRefKindDifferences_InWithRef()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs]: >PartialMethodsConsiderRefKindDifferences_InWithRef [](start = 20, length = 50)

Should probably fold ```out``` into the test matrix.

Comment (OmarTawfik) [reply src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs]: Partial methods cannot have `out` parameters, and there exists already a test for that.
What is the scenario you're proposing?

---
In reply to: [178658268](https://github.com/dotnet/roslyn/pull/25893#discussion_r178658268) [](ancestors = 178658268)

Comment (OmarTawfik) [reply src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs]: Discussed offline. Either confirming CS759 is reported, or lookup the symbol table and confirm they're not merged.

---
In reply to: [178992135](https://github.com/dotnet/roslyn/pull/25893#discussion_r178992135) [](ancestors = 178992135,178658268)

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-compiler can I get another review?

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-compiler can I get another review?

File: docs/compilers/CSharp/Compiler Breaking Changes - post VS2017.md [hunk 2]
```diff
@@ -98,3 +98,4 @@ Example: `Func<int> f = default(TypedReference).GetHashCode; // new error CS0123
 
 - Visual Studio 2017 version 15.7: https://github.com/dotnet/roslyn/issues/19792 C# compiler will now reject [IsReadOnly] symbols that should have an [InAttribute] modreq, but don't.
 - Visual Studio 2017 version 15.7: https://github.com/dotnet/roslyn/pull/25131 C# compiler will now check `stackalloc T [count]` expressions to see if T matches constraints of `Span<T>`.
+- Visual Studio 2017 version 15.7: https://github.com/dotnet/roslyn/issues/25399 C# compiler will now produce errors if partial methods parameters have different ref-kinds in implementation vs definition.
```
Comment (jcouv) [inline docs/compilers/CSharp/Compiler Breaking Changes - post VS2017.md]: I assume this was blessed by the Compat Council. 
If not, please do (before merging).

**Comment by OmarTawfik** [comment]
@jcouv yes. They already approved.
@jaredpar can you please approve for sign off?

**Comment by jaredpar** [comment]
approved
