### PR TITLE
Perform lookup in base interfaces even in a type-only context.

### LINKED ISSUE #38469: Nested type is not found in a base interface when it is referenced in a type-or-namespace-only position.
```
interface I100
{
    public class C100
    {
        public static void Test() { }
    }
}

interface I101 : I100
{
    private C100 Test1() => null; // error CS0246: The type or namespace name 'C100' could not be found (are you missing a using directive or an assembly reference?)

    static void Test2()
    {
        C100.Test();
    }
}
```

Observed:
```
private C100 Test1() => null; // error CS0246: The type or namespace name 'C100' could not be found (are you missing a using directive or an assembly reference?)
```

No error (the type is found in base interface) for: 
```
        C100.Test();
```

Expected: No errors, the type should be found.

This is not a regression in C# 8. This code wasn't changed in the compiler for a long time. Note the ```(options & (LookupOptions.NamespaceAliasesOnly | LookupOptions.NamespacesOrTypesOnly)) == 0``` condition.
```
        // Lookup member in interface, and any base interfaces.
        private static void LookupMembersInInterfaceOnly(
            LookupResult current,
            NamedTypeSymbol type,
            string name,
            int arity,
            ConsList<TypeSymbol> basesBeingResolved,
            LookupOptions options,
            Binder originalBinder,
            TypeSymbol accessThroughType,
            bool diagnose,
            ref HashSet<DiagnosticInfo> useSiteDiagnostics)
        {
            Debug.Assert((object)type != null);
            Debug.Assert(type.IsInterface);

            LookupMembersWithoutInheritance(current, type, name, arity, options, originalBinder, accessThroughType, diagnose, ref useSiteDiagnostics, basesBeingResolved);
            if ((options & (LookupOptions.NamespaceAliasesOnly | LookupOptions.NamespacesOrTypesOnly)) == 0 && !originalBinder.InCrefButNotParameterOrReturnType)
            {
                LookupMembersInInterfacesWithoutInheritance(current, type.AllInterfacesWithDefinitionUseSiteDiagnostics(ref useSiteDiagnostics), name, arity, basesBeingResolved, options, originalBinder, accessThroughType, diagnose, ref useSiteDiagnostics);
            }
        }
```

I think the check violates language specification, however, removing it might introduce a breaking change for existing code because types nested into interfaces were always supported by runtime, and could be produced by other languages like VB, etc. Removing the condition could resolve the identifier to a different type. For example, if there was a type named C100 in the global namespace for the example above, the C100 identifier in ```private C100 Test1() => null;``` would bind to that type. If we change lookup behavior to follow the spec, it would silently find I100.C100 type instead.
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #38469.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

File: src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs [hunk 1]
```diff
@@ -55584,5 +55584,236 @@ public interface I1
...
+        x.Test1().Test1();
+    }
+}
+";
+
+            var compilation1 = CreateCompilation(source1, options: TestOptions.DebugExe,
+                                                 parseOptions: TestOptions.Regular);
+
+            CompileAndVerify(compilation1, expectedOutput: "I100.C100.Test1");
+        }
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs]: >} [](start = 8, length = 1)

What happens if two nested types are implemented in two implemented interfaces and have the same name? I assume it's an error (ambiguous).
```
interface I1 { class C { } }
interface I2 { class C { } }
class Test : I1, I2 { ... try to use C ... }
```

File: src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs [hunk 2]
```diff
@@ -924,9 +924,52 @@ private static Symbol GetNearestOtherSymbol(ConsList<TypeSymbol> list, TypeSymbo
...
-                LookupMembersInInterfacesWithoutInheritance(current, type.AllInterfacesWithDefinitionUseSiteDiagnostics(ref useSiteDiagnostics), name, arity, basesBeingResolved, options, originalBinder, accessThroughType, diagnose, ref useSiteDiagnostics);
+                ImmutableArray<NamedTypeSymbol> baseInterfaces;
+
+                if (basesBeingResolved?.Any() != true)
+                {
+                    baseInterfaces = type.AllInterfacesWithDefinitionUseSiteDiagnostics(ref useSiteDiagnostics);
+                }
+                else
+                {
+                    var interfacesLookedAt = PooledHashSet<NamedTypeSymbol>.GetInstance();
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs]: >PooledHashSet<NamedTypeSymbol>.GetInstance(); [](start = 45, length = 45)

We're using object equality for comparison, but should we compare ignoring nullability instead?
It'll be worth testing with duplicate implementation differing by nullability. I think we don't want to produce an ambiguity in that case, right?

File: src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs [hunk 3]
```diff
@@ -924,9 +924,52 @@ private static Symbol GetNearestOtherSymbol(ConsList<TypeSymbol> list, TypeSymbo
...
+                    {
+                        getBaseInterfaces(baseInterfacesBuilder[i], baseInterfacesBuilder, interfacesLookedAt, basesBeingResolved);
+                    }
+
+                    interfacesLookedAt.Free();
+                    baseInterfaces = baseInterfacesBuilder.ToImmutableAndFree();
+
+                    foreach (var candidate in baseInterfaces)
+                    {
+                        candidate.OriginalDefinition.AddUseSiteDiagnostics(ref useSiteDiagnostics);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs]: >candidate.OriginalDefinition.AddUseSiteDiagnostics(ref useSiteDiagnostics); [](start = 24, length = 75)

I didn't understand this. Why are we collecting use site diagnostics from a base interface which may not end up being used/useful?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs]: > I didn't understand this. Why are we collecting use site diagnostics from a base interface which may not end up being used/useful?

1. This code is a replacement for AllInterfacesWithDefinitionUseSiteDiagnostics call.
2. In lookup we depend on all base interfaces, all of them are used.


---
In reply to: [322412154](https://github.com/dotnet/roslyn/pull/38564#discussion_r322412154) [](ancestors = 322412154)

File: src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs]: >  I think we don't want to produce an ambiguity in that case, right?

This question is outside of scope of this PR. The PR has nothing to do with handling nullable and has no intent to change any behavior around nullable. The hashset is used to build the same set of interfaces that AllInterfacesWithDefinitionUseSiteDiagnostics API does. Feel free to open an issue to follow up on interaction between lookup in base interfaces and nullable. 

---
In reply to: [322410943](https://github.com/dotnet/roslyn/pull/38564#discussion_r322410943) [](ancestors = 322410943)

File: src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs]: > What happens if two nested types are implemented in two implemented interfaces and have the same name? I assume it's an error (ambiguous).

Lookup in class doesn't look in base interfaces, so the type C is not found (no change in behavior). This PR doesn't change anything about lookup in base interfaces, it simply enables it for scenarios where it wasn't enabled, but should have been. You can observe behavior today by referring to a type in a not type-only context. For example, like for ```C100.Test2();``` in ```NestedTypes_24```, there is no behavior change for that line.



---
In reply to: [322408711](https://github.com/dotnet/roslyn/pull/38564#discussion_r322408711) [](ancestors = 322408711)

**Comment by AlekseyTs** [comment]
@jcouv I think I responded to all your questions.

**Comment by AlekseyTs** [comment]
> Was there a thread to let compat council know about this new breaking change?

There is a discussion in progress.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off.

**Comment by gafter** [comment]
Looking.

File: src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs [hunk 4]
```diff
@@ -924,9 +924,57 @@ private static Symbol GetNearestOtherSymbol(ConsList<TypeSymbol> list, TypeSymbo
...
+
+                foreach (var candidate in baseInterfaces)
+                {
+                    candidate.OriginalDefinition.AddUseSiteDiagnostics(ref useSiteDiagnostics);
+                }
+            }
+
+            return baseInterfaces;
+
+            static void getBaseInterfaces(NamedTypeSymbol derived, ArrayBuilder<NamedTypeSymbol> baseInterfaces, HashSet<NamedTypeSymbol> interfacesLookedAt, ConsList<TypeSymbol> basesBeingResolved)
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs]: >baseInterfaces [](start = 97, length = 14)

Please rename this parameter from `baseInterfaces` to `baseInterfacesBuilder`.

File: src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs [hunk 5]
```diff
@@ -924,9 +924,57 @@ private static Symbol GetNearestOtherSymbol(ConsList<TypeSymbol> list, TypeSymbo
...
+            {
+                baseInterfaces = type.AllInterfacesWithDefinitionUseSiteDiagnostics(ref useSiteDiagnostics);
+            }
+            else
+            {
+                var interfacesLookedAt = new HashSet<NamedTypeSymbol>(TypeSymbol.EqualsConsiderEverything);
+                var baseInterfacesBuilder = ArrayBuilder<NamedTypeSymbol>.GetInstance();
+
+                getBaseInterfaces(type, baseInterfacesBuilder, interfacesLookedAt, basesBeingResolved);
+
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs]: I believe that `LookupMembersInInterfacesWithoutInheritance` depends for its correctness on its second parameter being topologically sorted. Please use Tarjan's algorithm to enumerate the base interfaces in topological order.

**Comment by gafter** [comment]
Done reviewing (Iteration 2)

**Comment by AlekseyTs** [comment]
@gafter I think I've addressed the feedback.

**Comment by AlekseyTs** [comment]
@gafter Please review.

File: src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs [hunk 6]
```diff
@@ -924,9 +924,65 @@ private static Symbol GetNearestOtherSymbol(ConsList<TypeSymbol> list, TypeSymbo
...
+            foreach (var candidate in result)
+            {
+                candidate.OriginalDefinition.AddUseSiteDiagnostics(ref useSiteDiagnostics);
+            }
+
+            return result.ToImmutableAndFree();
+
+            static void addAllInterfaces(NamedTypeSymbol @interface, HashSet<NamedTypeSymbol> visited, ArrayBuilder<NamedTypeSymbol> result, ConsList<TypeSymbol> basesBeingResolved)
+            {
+                if (@interface.IsInterface && visited.Add(@interface) && !basesBeingResolved.ContainsReference(@interface.OriginalDefinition))
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Binder_Lookup.cs]: >visited.Add(@interface) [](start = 46, length = 23)

I think the contract here is that if you add to `visited`, you have committed to adding to `result`.  Otherwise the parts that are produced (taking trimming due to `basesBeingResolved` into account) may be incomplete, leading to an incorrect final result.

One way to fix this would be to swap the last two operands of `&&`.

**Comment by gafter** [comment]
Done reviewing (Iteration 5)
