### PR TITLE
Expand RemoveAllComments to have more in depth logic 

### LINKED ISSUE #31377: Move type to file copies unrelated comment
**Version Used**: VisualStudio.15.Preview/15.9.0-pre.6.0+28307.53

**Steps to Reproduce**:

```C#
namespace ConsoleApp1
{
    partial class Program
    {
        class Nested { }

        static void Main(string[] args) { }

        int ToInt(string s) => int.Parse(s);
        // long ToLong(string s) => long.Parse(s);
    }
}
```
1. Invoke or preview 'Move type to Nested.cs' quick action on the `Nested` class.

**Expected Behavior**: comment is not part of the new file

**Actual Behavior**: comment is copied to the new file

### PR DESCRIPTION
**Pull request by ryzngard**
Make RemoveAllComments special case TypeDeclarations to remove 
leading and trailing comments on the open/close tokens as well in csharp.

Separate out the logic for RemoveAllComments and RemoveLeadingAndTrailingComments since the behavior could be different based on the syntax passed in. RemoveLeadingAndTrailingComments only works on leading and trailing syntax. 

Fixes #31377

### CODE REVIEW

**Comment by ryzngard** [comment]
Ping @heejaechang

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs [hunk 1]
```diff
@@ -4255,6 +4255,75 @@ internal override SyntaxNode RefExpression(SyntaxNode expression)
...
+        }
+
+        internal override SyntaxTriviaList RemoveCommentLines(SyntaxTriviaList syntaxTriviaList)
+        {
+            IEnumerable<SyntaxTrivia> removeComments()
+            {
+                var start = 0;
+                var inComment = false;
+                var sameLine = true;
+                for (var i = start; i < syntaxTriviaList.Count; i++)
```
Comment (JoeRobich) [inline src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs]: This loop is a little involved. Maybe it would be more readable to split the trivia into lines and filter based on whether they contain a comment.
