### PR TITLE
Don't crash on nullable value types

### LINKED ISSUE #48236: CSharpRemoveRedundantEqualityDiagnosticAnalyzer analyzer is failing with null-reference
**Version Used**: 
Version 16.9.0 Preview 1.0 [30601.208.main]

We're seeing 10s of these across multiple code bases after updating to a recent build.

**Steps to Reproduce**:

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.RemoveRedundantEquality.CSharpRemoveRedundantEqualityDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Exception occurred with following context:
Compilation: Microsoft.VisualStudio.ProjectSystem.VS.Implementation
IOperation: BinaryOperator
SyntaxTree: C:\CPS\src\Microsoft.VisualStudio.ProjectSystem.VS.Implementation\Package\Nodes\Nesting\INestingProfilesSnapshotExtensions.cs
SyntaxNode: type == null [BinaryExpressionSyntax]@[721..733) (20,16)-(20,28)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.RemoveRedundantEquality.AbstractRemoveRedundantEqualityDiagnosticAnalyzer.AnalyzeBinaryOperator(OperationAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__63_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: IDE0100	Microsoft.VisualStudio.ProjectSystem.VS.Implementation		1	Active	Analyzer 'Microsoft.CodeAnalysis.CSharp.RemoveRedundantEquality.CSharpRemoveRedundantEqualityDiagnosticAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.VisualStudio.ProjectSystem.VS.Implementation
IOperation: BinaryOperator
SyntaxTree: C:\CPS\src\Microsoft.VisualStudio.ProjectSystem.VS.Implementation\Package\Nodes\Nesting\INestingProfilesSnapshotExtensions.cs
SyntaxNode: type == null [BinaryExpressionSyntax]@[721..733) (20,16)-(20,28)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.RemoveRedundantEquality.AbstractRemoveRedundantEqualityDiagnosticAnalyzer.AnalyzeBinaryOperator(OperationAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__63_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

**Expected Behavior**:

**Actual Behavior**:

### PR DESCRIPTION
**Pull request by davidwengier**
Fixes #48236

FYI @Youssef1313

### CODE REVIEW

File: src/Analyzers/Core/Analyzers/RemoveRedundantEquality/AbstractRemoveRedundantEqualityDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -60,7 +64,7 @@ private void AnalyzeBinaryOperator(OperationAnalysisContext context)
 
             var isOperatorEquals = operation.OperatorKind == BinaryOperatorKind.Equals;
             _syntaxFacts.GetPartsOfBinaryExpression(operation.Syntax, out _, out var operatorToken, out _);
-            var properties = ImmutableDictionary.CreateBuilder<string, string>();
+            var properties = ImmutableDictionary.CreateBuilder<string, string?>();
```
Comment (Youssef1313) [inline src/Analyzers/Core/Analyzers/RemoveRedundantEquality/AbstractRemoveRedundantEqualityDiagnosticAnalyzer.cs:67]: The dictionary doesn't hold any nulls. Both the keys and values are string constants defined in `RedundantEqualityConstants`. Am I missing something?

Comment (davidwengier) [reply src/Analyzers/Core/Analyzers/RemoveRedundantEquality/AbstractRemoveRedundantEqualityDiagnosticAnalyzer.cs:67]: I nullable enabled the file (which didn't help because IOperation isn't annotated), so this had to change to match the nullable annotations of `ReportDiagnostic` that it's passed to.

File: src/Analyzers/Core/Analyzers/RemoveRedundantEquality/AbstractRemoveRedundantEqualityDiagnosticAnalyzer.cs [hunk 2]
```diff
@@ -52,6 +50,12 @@ private void AnalyzeBinaryOperator(OperationAnalysisContext context)
...
             var rightOperand = operation.RightOperand;
             var leftOperand = operation.LeftOperand;
+
+            if (rightOperand.Type is null || leftOperand.Type is null)
+            {
+                return;
+            }
+
             if (rightOperand.Type.SpecialType != SpecialType.System_Boolean ||
                 leftOperand.Type.SpecialType != SpecialType.System_Boolean)
```
Comment (Youssef1313) [inline src/Analyzers/Core/Analyzers/RemoveRedundantEquality/AbstractRemoveRedundantEqualityDiagnosticAnalyzer.cs:60]: nit

```suggestion
            if (rightOperand.Type?.SpecialType != SpecialType.System_Boolean ||
                leftOperand.Type?.SpecialType != SpecialType.System_Boolean)
```

Comment (Youssef1313) [inline src/Analyzers/Core/Analyzers/RemoveRedundantEquality/AbstractRemoveRedundantEqualityDiagnosticAnalyzer.cs:60]:
```suggestion
            if (rightOperand.Type?.SpecialType != SpecialType.System_Boolean ||
                leftOperand.Type?.SpecialType != SpecialType.System_Boolean)
```

**Review by CyrusNajmabadi — APPROVED** [review]
I'm fine either withthis, or hte suggestions @Youssef1313 mentioned.

**Comment by davidwengier** [comment]
Thanks, I prefer the clarity of the explicit null checks :P
