### PR TITLE
[Ask Mode] Add InvalidExpression concrete type

### LINKED ISSUE #9114: NRE in `BoundCall.ArgumentBase.IsInvalid`
This is caused by Value property returns `null`. Can be repro'd by 
```
Microsoft.CodeAnalysis.CSharp.UnitTests.CompilationErrorTests.CS0225ERR_ParamsMustBeArray01
```
Stack trace:
```

Test 'Microsoft.CodeAnalysis.CSharp.UnitTests.CompilationErrorTests.CS0225ERR_ParamsMustBeArray01' failed: System.NullReferenceException : Object reference not set to an instance of an object.
	BoundTree\Expression.cs(247,0): at Microsoft.CodeAnalysis.CSharp.BoundCall.ArgumentBase.Microsoft.CodeAnalysis.IOperation.get_IsInvalid()
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(39,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.Visit(IOperation operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(210,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.VisitInvocationExpression(IInvocationExpression operation)
	BoundTree\Expression.cs(77,0): at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(41,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.Visit(IOperation operation)
	Compilation\OperationWalker.cs(181,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitExpressionStatement(IExpressionStatement operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(185,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.VisitExpressionStatement(IExpressionStatement operation)
	BoundTree\Statement.cs(699,0): at Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(41,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.Visit(IOperation operation)
	Compilation\OperationWalker.cs(21,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitArray[T](ImmutableArray`1 list)
	Compilation\OperationWalker.cs(45,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitBlockStatement(IBlockStatement operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(51,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.VisitBlockStatement(IBlockStatement operation)
	BoundTree\Statement.cs(52,0): at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(41,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.Visit(IOperation operation)
	CSharpTestBase.cs(582,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBaseBase.WalkOperationTree(CSharpCompilation compilation)
	CSharpTestBase.cs(529,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBaseBase.CreateCompilation(IEnumerable`1 trees, IEnumerable`1 references, CSharpCompilationOptions options, String assemblyName)
	CSharpTestBase.cs(443,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBaseBase.CreateCompilationWithMscorlib(IEnumerable`1 trees, IEnumerable`1 references, CSharpCompilationOptions options, String assemblyName)
	CSharpTestBase.cs(425,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBaseBase.CreateCompilationWithMscorlib(IEnumerable`1 sources, IEnumerable`1 references, CSharpCompilationOptions options, CSharpParseOptions parseOptions, String assemblyName)
	DiagnosticTestUtilities.cs(77,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.DiagnosticsUtils.VerifyErrorsAndGetCompilationWithMscorlib(String[] srcs, ErrorDescription[] expectedErrorDesp)
	DiagnosticTestUtilities.cs(69,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.DiagnosticsUtils.VerifyErrorsAndGetCompilationWithMscorlib(String text, ErrorDescription[] expectedErrorDesp)
	Symbols\SymbolErrorTests.cs(2846,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.CompilationErrorTests.CS0225ERR_ParamsMustBeArray01()
```

### PR DESCRIPTION
**Pull request by genlu**
Also fixes crash in `ArgumentBase.IsInvalid` property when code has error. This fixes #9114 

@JohnHamby @dotnet/roslyn-interactive

### CODE REVIEW

File: src/Compilers/Core/CodeAnalysisTest/Diagnostics/OperationTestAnalyzer.cs [hunk 1]
```diff
@@ -493,6 +493,14 @@ public class InvocationTestAnalyzer : DiagnosticAnalyzer
             DiagnosticSeverity.Warning,
             isEnabledByDefault: true);
 
+        public static readonly DiagnosticDescriptor InvalidArgumentDescriptor = new DiagnosticDescriptor(
+            "InvalidArgument",
+            "Invalid argument",
+            "Invocation has invalid argumen",
```
Comment (JohnHamby) [inline src/Compilers/Core/CodeAnalysisTest/Diagnostics/OperationTestAnalyzer.cs]: Missing a trailing 't'.

File: src/Compilers/CSharp/Portable/BoundTree/Expression.cs [hunk 2]
```diff
@@ -141,7 +142,7 @@ private static IArgument DeriveArgument(int parameterIndex, int argumentIndex, I
                 }
 
                 // There is no supplied argument and there is no params parameter. Any action is suspect at this point.
-                return new SimpleArgument(null, null);
+                return new SimpleArgument(null, new InvalidExpression(invocationSyntax));
```
Comment (JohnHamby) [inline src/Compilers/CSharp/Portable/BoundTree/Expression.cs]: I had a sinking feeling when I wrote the line above that something like this might turn out to be necessary. Sorry for not taking care of it then.

**Comment by JohnHamby** [comment]
I sign off.
