### PR TITLE
Fix stack overflow where overload resolution gets parameter type attributes

### LINKED ISSUE #33388: Incorrect usage of StructLayout attribute cause VS crash
Create C# project and use this code:

    using System.Runtime.InteropServices;

    [StructLayout(LayoutKind.Sequential, Size = Marshal.SizeOf(Test))]
    public struct Test
    {
    }

or:

    using System.Runtime.InteropServices;

    [StructLayout(LayoutKind.Sequential, Pack = Marshal.SizeOf(Test))]
    public struct Test
    {
    }

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/450661/incorrect-usage-of-structlayout-attribute-cause-vs.html
VSTS ticketId: 790164_
_These are the original issue comments:_

Visual Studio Feedback System on 2/12/2019, 01:29 AM (2 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

### PR DESCRIPTION
**Pull request by RikkiGibson**
Fixes #33388 by refraining from normalizing task-like types when binding an attribute argument.

I'd like to make sure I completely understand the implications of this change. If we stop normalizing task-like parameters to attribute constructors, what user-facing consequences could possibly occur?

### CODE REVIEW

File: src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests.cs [hunk 1]
```diff
@@ -8980,6 +8980,40 @@ public static async Task UserInfo()
...
+public class C2
+{
+}
+";
+            var comp = CreateCompilation(source);
+            comp.VerifyDiagnostics(
+                // (20,6): error CS0182: An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type
+                // [Rec(C.M(null))]
+                Diagnostic(ErrorCode.ERR_BadAttributeArgument, "C.M(null)").WithLocation(20, 6));
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests.cs]: Please add a test where `NormalizeTaskTypes` would be meaningful today. For instance:
```c#
class A : Attribute
{
    public A(Func<MyTask<int>> f) { }
    public A(Func<Task<int>> f) { }
}
[A(async () => 1)]
class C
{
}
```

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs [hunk 2]
```diff
@@ -1559,8 +1559,13 @@ private static ParameterSymbol GetParameter(int argIndex, MemberAnalysisResult r
                                                    ref useSiteDiagnostics,
                                                    out okToDowngradeToNeither);
 
-                var type1Normalized = type1.NormalizeTaskTypes(Compilation);
-                var type2Normalized = type2.NormalizeTaskTypes(Compilation);
+                var type1Normalized = type1;
+                var type2Normalized = type2;
+                if ((_binder.Flags & BinderFlags.AttributeArgument) == BinderFlags.None)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs]: >(_binder.Flags & BinderFlags.AttributeArgument) == BinderFlags.None [](start = 20, length = 67)

Consider using ```InAttributeArgument``` property instead

**Comment by RikkiGibson** [comment]
@cston I was pleasantly surprised to see that the test I added in 517ffc9 chose the `MyTask<int>` overload. Looks like we bind the attribute arguments with `BinderFlags.AttributeArgument` set. Then we resolve the constructor overload with the flag *unset*.

**Comment by RikkiGibson** [comment]
Commenting out the calls to `NormalizeTaskTypes` in `BetterFunctionMember<TMember>` doesn't seem to affect the outcome of the test. I'm probably not understanding something here.

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs [hunk 3]
```diff
@@ -1559,8 +1559,13 @@ private static ParameterSymbol GetParameter(int argIndex, MemberAnalysisResult r
                                                    ref useSiteDiagnostics,
                                                    out okToDowngradeToNeither);
 
-                var type1Normalized = type1.NormalizeTaskTypes(Compilation);
-                var type2Normalized = type2.NormalizeTaskTypes(Compilation);
+                var type1Normalized = type1;
+                var type2Normalized = type2;
+                if (!_binder.InAttributeArgument)
+                {
+                    type1Normalized = type1.NormalizeTaskTypes(Compilation);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs]: >NormalizeTaskTypes [](start = 44, length = 18)

It looks like there are two more call sites for this method in this file. Should they be protected as well?

File: src/Compilers/CSharp/Test/Semantic/Semantics/BindingAsyncTasklikeMoreTests.cs [hunk 4]
```diff
@@ -1320,5 +1320,79 @@ static void Main()
...
+{
+    public static MyTaskMethodBuilder Create() => null;
+    public void SetStateMachine(IAsyncStateMachine stateMachine) { }
+    public void Start<TStateMachine>(ref TStateMachine stateMachine) where TStateMachine : IAsyncStateMachine { }
+    public void SetException(Exception e) { }
+    public void SetResult() { }
+    public void AwaitOnCompleted<TAwaiter, TStateMachine>(ref TAwaiter awaiter, ref TStateMachine stateMachine) where TAwaiter : INotifyCompletion where TStateMachine : IAsyncStateMachine { }
+    public void AwaitUnsafeOnCompleted<TAwaiter, TStateMachine>(ref TAwaiter awaiter, ref TStateMachine stateMachine) where TAwaiter : ICriticalNotifyCompletion where TStateMachine : IAsyncStateMachine { }
+    public MyTask Task => default(MyTask);
+}
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/BindingAsyncTasklikeMoreTests.cs]: `MyTask` and `MyTaskMethodBuilder` are not needed, just `MyTask<T>` and `MyTaskMethodBuilder<T>`.

**Comment by cston** [comment]
@RikkiGibson, the original example I suggested may not be sufficient to hit the changed code path. It might be necessary to have a cycle. Perhaps:
```C#
class A : Attribute
{
    public A(int i) { }
}
class B
{
    public static int F(Func<MyTask<object>> t) => 1;
    public static int F(Func<Task<C>> t) => 2;
}
[A(B.F(async () => null))]
class C
{
}
```

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs]: Possibly. However I can't figure out what conditions cause us to reach [the call sites you mentioned](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Binder/Semantics/OverloadResolution/OverloadResolution.cs,1674). I've tried adding `throw new Exception()` and running all the tests and they all continue to pass.

**Comment by RikkiGibson** [comment]
It seems like it's possible to violate the `!allSame` assert and actually enter the "apparently unused" branch by using the same parameter types but different ref kinds, e.g.

```cs
    public void M(long x, ref int y, MyTask<int> t) {}
    public void M(ref long x, int y, MyTask<long> t) {}
```

Working on adding a test case which exercises this.

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs [hunk 5]
```diff
@@ -1656,6 +1661,8 @@ private static ParameterSymbol GetParameter(int argIndex, MemberAnalysisResult r
 
             // We might have got out of the loop above early and allSame isn't completely calculated.
             // We need to ensure that we are not going to skip over the next 'if' because of that.
+            // This condition requires the methods being compared have parameters of identical types but different ref kinds.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs]: >This condition requires [](start = 15, length = 23)

The condition doesn't require that and we don't really know if there are other scenarios when condition could be true, consider changing the comment to say: "For example, we can get in this situation when ..."

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs]: Done.

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs [hunk 6]
```diff
@@ -1559,8 +1559,13 @@ private static ParameterSymbol GetParameter(int argIndex, MemberAnalysisResult r
                                                    ref useSiteDiagnostics,
                                                    out okToDowngradeToNeither);
 
-                var type1Normalized = type1.NormalizeTaskTypes(Compilation);
-                var type2Normalized = type2.NormalizeTaskTypes(Compilation);
+                var type1Normalized = type1;
+                var type2Normalized = type2;
+                if (!_binder.InAttributeArgument)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs]: We should include a comment on why this check is needed and valid. Perhaps something like:
Avoid normalizing task types in attribute arguments to avoid cycles binding attributes on task-like types. Normalizing is only necessary to differentiate async lambdas which are not supported in attribute arguments.
