### PR TITLE
Potentially fixed a bug regarding static items not bolding

### LINKED ISSUE #38781: Static method isn't rendered in bold in nameof operator
**Version Used**: Visual Studio 2019 Version 16.3

**Steps to Reproduce**:

```cs
public static class Type
{
    public static int Field;

    public static int Property { get; set; }

    public static void Method()
    {
        _ = nameof(Type);
        _ = nameof(Field);
        _ = nameof(Property);
        _ = nameof(Method); // Regular
        System.Action action = Method; // Bold
    }
}
```

**Expected Behavior**:

`Method` in `nameof` operator is rendered in bold.

**Actual Behavior**:

`Method` in `nameof` operator is rendered regularly.

### PR DESCRIPTION
**Pull request by akhera99**
Fixes #38781 

Issue: 
The issue here was that certain static defined items were not being bolded properly. This was due to the fact that we classified static methods only if there was a single symbol match. Since, in the example provided, nameof is ambiguous then we also need to classify static methods in that case. 

Fix:
To fix this, I needed to modify the ```TryClassifyAmbiguousSymbol``` method. I added a boolean flag to indicate if at least one of the references were static. Then, if they all resolved at the set remained at a size of 1, I checked to see if any of those references were static. If they were, I also added a static classification to the result. In the case of multiple overloaded methods with the same name, some being static and some not, we decided to resolve it to just be bolded.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Hi @akhera99 I'll take a look at thsi :) Thanks for the contribution.

File: src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs [hunk 1]
```diff
@@ -3903,5 +3903,65 @@ public async Task NotNativeUnsignedInteger()
...
+{
+    public static void Method()
+    {
+        System.Action action = Method;
+    }
+}",
+            Namespace("System"),
+            Delegate("Action"),
+            Method("Method"),
+            Static("Method"));
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs:3921]: i'm not really understanding why this wouldn't have worked before.  there was only one 'Method', and it's static, so why do we need to care about multiple symbols?

File: src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs [hunk 2]
```diff
@@ -3903,5 +3903,65 @@ public async Task NotNativeUnsignedInteger()
...
+
+    }
+
+    public void Test() {
+        _ = nameof(Method);
+    }
+}",
+            Keyword("_"),
+            Keyword("nameof"),
+            Static("Method"),
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs:3963]: i don't know or believe that static would be correct here.  It seems like it should be bolded only if *Everything* is a static method in teh method group.

File: src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.cs [hunk 3]
```diff
@@ -105,15 +105,33 @@ protected override bool IsParentAnAttribute(SyntaxNode node)
         {
             // If everything classifies the same way, then just pick that classification.
             using var _ = PooledHashSet<ClassifiedSpan>.GetInstance(out var set);
+            using var _s = PooledHashSet<ClassifiedSpan>.GetInstance(out var sset);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.cs:108]: 1. we woudl name these `_1` and _2`.  
2. the comment `// If everything classifies the same way, then just pick that classification.` is not correct anymore.
3. `sset` isn't a good name.

File: src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.cs [hunk 4]
```diff
@@ -105,15 +105,33 @@ protected override bool IsParentAnAttribute(SyntaxNode node)
...
-            if (set.Count == 1)
+            if (sset.Count == 1)
+            {
+                result.Add(sset.First());
+                return true;
+            }
+            else if (set.Count == 1)
             {
                 result.Add(set.First());
                 return true;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.cs:137]: so the existing logic seems correct to me.  we only consider it static if *all* the overloads are static.  I think we shoudl preserve that.

File: src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.cs [hunk 5]
```diff
@@ -105,15 +105,33 @@ protected override bool IsParentAnAttribute(SyntaxNode node)
...
+            using var _s = PooledHashSet<ClassifiedSpan>.GetInstance(out var sset);
+            var count = result.Count;
             foreach (var symbol in symbolInfo.CandidateSymbols)
             {
                 if (TryClassifySymbol(name, symbol, semanticModel, cancellationToken, out var classifiedSpan))
                 {
-                    set.Add(classifiedSpan);
+                    if (classifiedSpan.ClassificationType != ClassificationTypeNames.Keyword)
+                    {
+                        TryClassifyStaticSymbol(symbol, classifiedSpan.TextSpan, result);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.cs:116]: this would need comments explaining why this is being done.  it's not something that can be trivially understood just by examining the code.

File: src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.cs [hunk 6]
```diff
@@ -105,20 +106,32 @@ protected override bool IsParentAnAttribute(SyntaxNode node)
         {
             // If everything classifies the same way, then just pick that classification.
             using var _ = PooledHashSet<ClassifiedSpan>.GetInstance(out var set);
+            var isStatic = false;
+            var staticSpan = new TextSpan();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Classification/SyntaxClassification/NameSyntaxClassifier.cs:110]: you shouldn't need to store this span.  it's redundant with the one stored in `set`.

File: src/Workspaces/Core/Portable/Classification/SyntaxClassification/AbstractNameSyntaxClassifier.cs [hunk 7]
```diff
@@ -116,5 +117,37 @@ internal abstract class AbstractNameSyntaxClassifier : AbstractSyntaxClassifier
 
             result.Add(new ClassifiedSpan(span, ClassificationTypeNames.StaticSymbol));
         }
+
+        protected static bool IsStaticSymbol(ISymbol? symbol)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Classification/SyntaxClassification/AbstractNameSyntaxClassifier.cs:121]: this ends up duplicating all the logic (Which would make maintenance much harder).  We would want teh function above to now call this helper so we only have it in one place, supporting mutiple clients.

File: src/Workspaces/Core/Portable/Classification/SyntaxClassification/AbstractNameSyntaxClassifier.cs [hunk 8]
```diff
@@ -116,5 +117,37 @@ internal abstract class AbstractNameSyntaxClassifier : AbstractSyntaxClassifier
...
+                return false;
+            }
+
+            if (symbol.IsLocalFunction())
+            {
+                // Local function names are not classified as static since the
+                // the symbol returning true for IsStatic is an implementation detail.
+                return false;
+            }
+            return true;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Classification/SyntaxClassification/AbstractNameSyntaxClassifier.cs:150]:
```suggestion

            return true;
```

nit: our codestyle is that there should generally be a blank line after a `}` and hte next statement.

**Comment by CyrusNajmabadi** [comment]
Done with pass.

File: src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs [hunk 9]
```diff
@@ -3903,5 +3903,65 @@ public async Task NotNativeUnsignedInteger()
...
+    }
+}",
+            Namespace("System"),
+            Delegate("Action"),
+            Method("Method"),
+            Static("Method"));
+        }
+
+        [Fact, Trait(Traits.Feature, Traits.Features.Classification)]
+        public async Task StaticBoldingMethodNameNested()
```
Comment (jasonmalinowski) [inline src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs:3925]:
```suggestion
        public async Task StaticBoldingMethodNameNestedInNameof()
```

File: src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs (hunk 1 above)
Comment (jasonmalinowski) [reply src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs:3921]: This case came up as a "does it work?" so I believe @akhera99 added the test both to confirm we don't break it and also just to make sure it's working too.
