### PR TITLE
"Generate Equals" should ignore indexers and setter-only properties

### LINKED ISSUE #25690: "Generate Equals" refactorings produce non-compiling code when using indexers
**Version Used**: VS 15.7 Preview 2 (Roslyn 2.8.0.62716, `e205ae18`)

**Steps to Reproduce**:

1. Copy the class below into a C# source file.
2. Invoke the Quick Fix menu at the marked location and select either "Generate Equals(object)…" or "Generate Equals and GetHashCode…".
3. Make sure the indexer "this[int]" is selected in the list. Press OK.

```c#
class Repro
{
	public int this[int index]
	{
		get => index;
	}
	$$
}
```

**Expected Behavior**: The generated methods are syntactically valid. (Although I don't know how one could use an indexer to implement Equals or GetHashCode.)

**Actual Behavior**: The generated code looks something like this, which is syntactically invalid:

```c#
public override bool Equals(object obj)
{
	var repro = obj as Repro;
	return repro != null &&
		this[] == repro.this[]; // Emits four compiler errors and one warning
}

public override int GetHashCode()
{
	return -529683855 + this[].GetHashCode(); // Emits one compiler error
}
```

### LINKED ISSUE #25707: "Generate Equals" refactorings should not include set-only properties
**Version Used**: VS 15.7 Preview 2 (Roslyn 2.8.0.62716)

**Steps to Reproduce**:

1. Copy the class below into a C# source file.
2. Invoke the Quick Fix menu at the marked location and select either "Generate Equals" or "Generate Equals and GetHashCode".
3. Make sure SetOnly is marked in the list and press "OK".

```c#
class Repro
{
	int SetOnly { set { } }
	$$
}
```

**Expected Behavior**: The property is not included in the list, and thus doesn't appear in the generated code.

**Actual Behavior**: The generated code looks something like this:

```c#
public override bool Equals(object obj)
{
	var repro = obj as Repro;
	return repro != null &&
		   this.SetOnly == repro.SetOnly; // Emits two CS0154 errors
}

public override int GetHashCode()
{
	return 257811045 + this.SetOnly.GetHashCode(); // Emits one CS0154 error
}
```

### PR DESCRIPTION
**Pull request by Neme12**
fixes #25690 
fixes #25707

### CODE REVIEW

**Comment by Neme12** [comment]
@CyrusNajmabadi Would you take a look at this? Thanks

File: src/EditorFeatures/VisualBasicTest/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersTests.vb [hunk 1]
```diff
@@ -106,6 +106,68 @@ Partial Class c1(Of V As {New}, U)
...
+        Return program IsNot Nothing AndAlso
+               F = program.F
+    End Function
+End Class",
+chosenSymbols:=Nothing)
+        End Function
+
+        <WorkItem(25690, "https://github.com/dotnet/roslyn/issues/25690")>
+        <Fact, Trait(Traits.Feature, Traits.Features.CodeActionsGenerateEqualsAndGetHashCode)>
+        Public Async Function TestWithDialogNoIndexer() As Task
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/VisualBasicTest/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersTests.vb]: note: this is not an indexer for VB, it's a parameterized property.  To make an indexer, you need to use "default property".  I would consider adding a test for both cases.

Comment (Neme12) [reply src/EditorFeatures/VisualBasicTest/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersTests.vb]: ok

Comment (Neme12) [reply src/EditorFeatures/VisualBasicTest/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersTests.vb]: I think i've seen this referred to as an "indexer property" in the docs

**Comment by Neme12** [comment]
@CyrusNajmabadi I made other changes to fix another issue, you might want to review again.

File: src/Features/Core/Portable/GenerateFromMembers/AbstractGenerateFromMembersService.cs [hunk 2]
```diff
@@ -74,27 +74,20 @@ protected AbstractGenerateFromMembersCodeRefactoringProvider()
 
         // Can use non const fields and properties with setters in them.
         protected static bool IsWritableInstanceFieldOrProperty(ISymbol symbol)
-            => IsViableInstanceFieldOrProperty(symbol) &&
-               IsWritableFieldOrProperty(symbol);
+            => !symbol.IsStatic &&
+               (symbol is IFieldSymbol field && IsViableField(field) && !field.IsConst ||
+                symbol is IPropertySymbol property && IsViableProperty(property) && property.IsWritableInConstructor());
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/GenerateFromMembers/AbstractGenerateFromMembersService.cs]: this mix of &&'s and ||'s is confusing.  Please extract into helper and parenthesize to keep precedence clear.  In general, we prefer expressions that are uniform with &&'s or ||'s.

Comment (Neme12) [reply src/Features/Core/Portable/GenerateFromMembers/AbstractGenerateFromMembersService.cs]: I thought about this for a while and found it hard to extract common code between `IsWritableInstanceFieldOrProperty` and `IsReadableInstanceFieldOrProperty`. They use the same logic for whether the field/property is "viable" but they also need to do more checks that are still specific to each type. Basically one method would check the type and some condition, and the other one would check the type again for another condition. So I don't know what to do there.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/GenerateFromMembers/AbstractGenerateFromMembersService.cs]: > IsWritableInstanceFieldOrProperty 

> IsReadableInstanceFieldOrProperty

Based on the name, it sounds like they can reuse whatever computes if this is an InstanceFieldOrProperty

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/GenerateFromMembers/AbstractGenerateFromMembersService.cs]: > I thought about this for a while and found it hard to extract common code

Right now the mixing of precedence operators is confusing here.  Please at least parenthesize for clarity.  Also, to prevent mixing and matching of operators, just make this a full body method.  THis is complex enough that collapsing into an expression is harder to understand.

Comment (Neme12) [reply src/Features/Core/Portable/GenerateFromMembers/AbstractGenerateFromMembersService.cs]: > Also, to prevent mixing and matching of operators, just make this a full body method. THis is complex enough that collapsing into an expression is harder to understand

Yes. But then you'd still have another method for IsWritableInstanceFieldOrProperty which would have the same structure - it needs to check writability based on whether the symbol is a field or a property. So the code reuse would actually reuse some things but duplicate other things, and introduce unnecessary type checks after we already did the same check before.

**Comment by Neme12** [comment]
> to give precedence to clarity.

interesting way to phrase things :smiley:

File: src/Features/Core/Portable/GenerateFromMembers/AbstractGenerateFromMembersService.cs [hunk 3]
```diff
@@ -72,23 +72,39 @@ protected AbstractGenerateFromMembersCodeRefactoringProvider()
...
 
-        protected static bool IsReadableInstanceFieldOrProperty(ISymbol symbol)
-            => !symbol.IsStatic &&
-               (symbol is IFieldSymbol field && IsViableField(field) ||
-                symbol is IPropertySymbol property && IsViableProperty(property) && !property.IsWriteOnly);
+        private static bool IsReadableFieldOrProperty(ISymbol symbol)
+        {
+            switch (symbol)
+            {
+                case IFieldSymbol field when IsViableField(field): return true;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/GenerateFromMembers/AbstractGenerateFromMembersService.cs]: can you not just do:  ```case IFieldSymbol field: return IsViableField(field);```?  It seems much simpler than having 'when' *and* a boolean.

File: src/Features/Core/Portable/GenerateFromMembers/AbstractGenerateFromMembersService.cs [hunk 4]
```diff
@@ -72,23 +72,39 @@ protected AbstractGenerateFromMembersCodeRefactoringProvider()
...
+                case IPropertySymbol property when IsViableProperty(property): return !property.IsWriteOnly;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/GenerateFromMembers/AbstractGenerateFromMembersService.cs]: same issue here.  no need for 'when'.  just merge its condition into the actual return statement.

File: src/Features/Core/Portable/GenerateFromMembers/AbstractGenerateFromMembersService.cs [hunk 5]
```diff
@@ -72,23 +72,39 @@ protected AbstractGenerateFromMembersCodeRefactoringProvider()
...
 
-        // Can use non const fields and properties with setters in them.
+        protected static bool IsReadableInstanceFieldOrProperty(ISymbol symbol)
+            => !symbol.IsStatic && IsReadableFieldOrProperty(symbol);
+
         protected static bool IsWritableInstanceFieldOrProperty(ISymbol symbol)
-            => !symbol.IsStatic &&
-               (symbol is IFieldSymbol field && IsViableField(field) && !field.IsConst ||
-                symbol is IPropertySymbol property && IsViableProperty(property) && property.IsWritableInConstructor());
+            => !symbol.IsStatic && IsWritableFieldOrProperty(symbol);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/GenerateFromMembers/AbstractGenerateFromMembersService.cs]: these two methods are very readable.  thank you :)

File: src/Features/Core/Portable/GenerateFromMembers/AbstractGenerateFromMembersService.cs (hunk 4 above)
Comment (Neme12) [reply src/Features/Core/Portable/GenerateFromMembers/AbstractGenerateFromMembersService.cs]: I found this a little nice than having && inside each case but ok

**Comment by Neme12** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by Neme12** [comment]
retest windows_release_vs-integration_prtest please

**Comment by Neme12** [comment]
retest windows_release_unit32_prtest please

**Comment by Neme12** [comment]
retest windows_release_unit32_prtest please

**Comment by DustinCampbell** [comment]
@dotnet-bot retest windows_release_unit64_prtest please

**Comment by DustinCampbell** [comment]
@dotnet-bot retest this please

File: src/EditorFeatures/VisualBasicTest/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersTests.vb (hunk 1 above)
Comment (DustinCampbell) [reply src/EditorFeatures/VisualBasicTest/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersTests.vb]: Internally, we've always called them "parameterized properties". Indexers use the "Default" keyword.

**Comment by Neme12** [comment]
I think some of those tests are stuck. I have this on another PR as well and retesting doesn't help.

**Comment by Neme12** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by Neme12** [comment]
retest windows_release_vs-integration_prtest please

**Comment by Neme12** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by Neme12** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by DustinCampbell** [comment]
@jaredpar: Is the windows_debug_spanish_unit32_prtest flaky at the moment? We've run it a few times, but we keep getting back, "xunit produced no error output but had exit code 1"

**Comment by jaredpar** [comment]
@DustinCampbell looks like the EE tests are just faky in general. Seen this in a few logs

 ``` Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.UnitTests.DebuggerTypeProxyAttributeTests.GenericTypeWithGenericTypeArgument
System.Reflection.TargetInvocationException: Se produjo una excepciÃ³n en el destino de la invocaciÃ³n.
System.AccessViolationException: Intento de leer o escribir en la memoria protegida. A menudo, esto indica que hay otra memoria daÃ±ada.
```

**Comment by DustinCampbell** [comment]
OK to merge?

**Comment by jaredpar** [comment]
It's fine by me.

**Comment by DustinCampbell** [comment]
Great! @Neme12: Thanks very much for your contributions!

**Comment by Neme12** [comment]
Thanks, I still have 12 other PRs if you're interested :smile:
