### PR TITLE
Handle unchanged value in SerializableOptionSet.WithChangedOption

### LINKED ISSUE #48564: Differences detected in solution checksum
**Version Used**: 16db183

🔗 https://dev.azure.com/dnceng/public/_build/results?buildId=850293

**Steps to Reproduce**:

Integration tests

**Actual Behavior**:

```
10/13/2020 15:36:10 Coordinated Universal Time: Error : 1 :[devenv:11412] Unexpected exception: StreamJsonRpc.RemoteInvocationException: Differences detected in solution checksum: assets only in the incremental solution but not in the request
EfrvvFm3ZUG52+613BSqYI1ADvw=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
CYda0ruFSG9ks8sYc+spWfnndxQ=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in new solution but not in incremental solution
ZzGaCUmyuTQ3C88JmctKnJn0SGY=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
anaWAORO0kIjpiqXme+7iDsW4n8=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in incremental solution but not in new solution
EfrvvFm3ZUG52+613BSqYI1ADvw=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
CYda0ruFSG9ks8sYc+spWfnndxQ=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in the request but not in incremental solution
ZzGaCUmyuTQ3C88JmctKnJn0SGY=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
anaWAORO0kIjpiqXme+7iDsW4n8=, Microsoft.CodeAnalysis.Options.SerializableOptionSet



   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__133`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__10`1.MoveNext() in /_/src/Workspaces/Remote/Core/BrokeredServiceConnection.cs:line 114
RPC server exception:
System.InvalidOperationException: Differences detected in solution checksum: assets only in the incremental solution but not in the request
EfrvvFm3ZUG52+613BSqYI1ADvw=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
CYda0ruFSG9ks8sYc+spWfnndxQ=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in new solution but not in incremental solution
ZzGaCUmyuTQ3C88JmctKnJn0SGY=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
anaWAORO0kIjpiqXme+7iDsW4n8=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in incremental solution but not in new solution
EfrvvFm3ZUG52+613BSqYI1ADvw=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
CYda0ruFSG9ks8sYc+spWfnndxQ=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in the request but not in incremental solution
ZzGaCUmyuTQ3C88JmctKnJn0SGY=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
anaWAORO0kIjpiqXme+7iDsW4n8=, Microsoft.CodeAnalysis.Options.SerializableOptionSet



      at Microsoft.CodeAnalysis.Remote.ThrowingTraceListener.Fail(String message, String detailMessage) in /_/src/Workspaces/Remote/ServiceHub/Services/Host/ThrowingTraceListener.cs:line 14
      at System.Diagnostics.TraceInternal.Fail(String message)
      at Microsoft.CodeAnalysis.Remote.TestUtils.<AssertChecksumsAsync>d__2.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/TestUtils.cs:line 79
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<ValidateChecksumAsync>d__19.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs:line 525
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<CreateSolutionAsync>d__6.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs:line 89
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<CreateSolution_NoLockAsync>d__10.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs:line 135
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<GetSolutionAsync>d__12.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs:line 213
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.RemoteSemanticClassificationService.<>c__DisplayClass2_0.<<GetSemanticClassificationsAsync>b__0>d.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Services/SemanticClassification/RemoteSemanticClassificationService.cs:line 38
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceAsync>d__11`1.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs:line 69
```

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #48564

### CODE REVIEW

File: src/Workspaces/Core/Portable/Options/SerializableOptionSet.cs [hunk 1]
```diff
@@ -133,8 +133,16 @@ private bool ShouldSerialize(OptionKey optionKey)
...
         {
-            // make sure we first load this in current optionset
-            this.GetOption(optionKey);
+            // Make sure we first load this in current optionset
+            var currentValue = this.GetOption(optionKey);
+
+            // Check if the new value is the same as the current value.
+            if (value == currentValue)
+            {
+                // Return a cloned option set as the public API 'WithChangedOption' guarantees a new option set is returned.
```
Comment (sharwell) [inline src/Workspaces/Core/Portable/Options/SerializableOptionSet.cs:142]: 😕 I can see how the documentation reads this way, but does anyone actually depend on it? `SerializableOptionSet` is an immutable snapshot so I don't see how returning `this` would ever be a problem.

File: src/Workspaces/Core/Portable/Options/SerializableOptionSet.cs [hunk 2]
```diff
@@ -133,8 +133,16 @@ private bool ShouldSerialize(OptionKey optionKey)
...
+                return new SerializableOptionSet(_languages, _workspaceOptionSet, _serializableOptions,
+                    _serializableOptionValues, _changedOptionKeysSerializable, _changedOptionKeysNonSerializable);
```
Comment (sharwell) [inline src/Workspaces/Core/Portable/Options/SerializableOptionSet.cs:144]: > _changedOptionKeysSerializable

💭 It would be much easier to understand states if we made this field always relative to the _default_ values, instead of making them relevant to the current globals.

File: src/Workspaces/Core/Portable/Options/SerializableOptionSet.cs (hunk 1 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/Options/SerializableOptionSet.cs:142]: I am not sure, I tried to keep the change as targeted as possible.

File: src/Workspaces/Core/Portable/Options/SerializableOptionSet.cs (hunk 2 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/Options/SerializableOptionSet.cs:144]: Yep, that can be a separate refactoring if required.

**Comment by mavasani** [comment]
@sharwell any further feedback?

File: src/Workspaces/Core/Portable/Options/SerializableOptionSet.cs [hunk 3]
```diff
@@ -133,8 +133,16 @@ private bool ShouldSerialize(OptionKey optionKey)
 
         public override OptionSet WithChangedOption(OptionKey optionKey, object? value)
         {
-            // make sure we first load this in current optionset
-            this.GetOption(optionKey);
+            // Make sure we first load this in current optionset
+            var currentValue = this.GetOption(optionKey);
+
+            // Check if the new value is the same as the current value.
+            if (value == currentValue)
```
Comment (sharwell) [inline src/Workspaces/Core/Portable/Options/SerializableOptionSet.cs:140]: 💭 Should this use the same equality logic that `WithLanguages` uses?

https://github.com/dotnet/roslyn/blob/3d333c226822a88df0e1a585f56f498299797c7f/src/Workspaces/Core/Portable/Options/SerializableOptionSet.cs#L110

Comment (mavasani) [inline src/Workspaces/Core/Portable/Options/SerializableOptionSet.cs:140]:
```suggestion
            if (Equals(value, currentValue))
```

Comment (mavasani) [reply src/Workspaces/Core/Portable/Options/SerializableOptionSet.cs]: Yep, done.

**Review by sharwell — APPROVED** [review]
