### PR TITLE
Fix Locals in async lambdas...

### LINKED ISSUE #2240: No Locals when debugging async method...
In e-mail, Mark M. reports:

...I've got lots of locals and such, but none of them show data in the autos or local windows during a breakpoint...

```
public IHttpActionResult GetCatalogUtilization(DateTime? from = null, DateTime? to = null)
{
        if (from == null) from = DateTime.Now - TimeSpan.FromDays(30);
        if (to == null) to = DateTime.Now + TimeSpan.FromMinutes(30);

        var fromKey = $"{(DateTime.MaxValue.Ticks - from.Value.ToUniversalTime().Ticks):x16}-ffff-z";
        var toKey = $"{(DateTime.MaxValue.Ticks - to.Value.ToUniversalTime().Ticks):x16}-0000";

        return new LambdaResult(async cancelToken =>
        {
            var utilization = new Dictionary<string, Dictionary<string, ItemUtilizationData>>();

            var exchanges = await (from exch in GetSummariesTable().CreateQuery<ExchangeSummary>()
                                   where exch.PartitionKey == "EXCHANGE"
                                   where exch.RowKey.CompareTo(fromKey) <= 0 && exch.RowKey.CompareTo(toKey) >= 0
                                   select exch).AsTableQuery().ExecuteAsync();
            //pull all exchanges and build the utilization view per catalog item
            foreach (var exInfo in exchanges.OrderBy(e=>e.LogTimestamp))
            {
                if (exInfo.ExchangeKind.StartsWith("CONSUME")) continue; //we don't care about consume
                if (exInfo.ExchangeKind.Contains("CANCELLED")) continue; //cancels didn't happen
                Dictionary<string, ItemUtilizationData> catalogItemData;
                if (exInfo.CatalogItemId == null)
                {
                    //TODO: we'll need to deal with this problem
                    continue;
                }
                if (!utilization.TryGetValue(exInfo.CatalogItemId, out catalogItemData))
                {
                    catalogItemData = new Dictionary<string, ItemUtilizationData>();
                    utilization.Add(exInfo.CatalogItemId, catalogItemData);
                }
                ItemUtilizationData itemData;
                if (!catalogItemData.TryGetValue(exInfo.Item, out itemData))
                {
                    itemData = new ItemUtilizationData();
                    catalogItemData.Add(exInfo.Item, itemData);
                }
                itemData.ProcessExchange(exInfo, from.Value);
            }

            foreach (var catalogInfo in utilization)
            {
                foreach (var itemInfo in catalogInfo.Value)
                {
                    itemInfo.Value.FinalizeWindow(to.Value);
                }
            }
            var catalog = await CatalogStorage.GetCatalogAsync();

            Func<string, IEnumerable<ItemUtilizationData>> getUtilization = catId =>
            {
                Dictionary<string, ItemUtilizationData> catalogItemData;
               if (!utilization.TryGetValue(catId, out catalogItemData))
                {
                    return Enumerable.Empty<ItemUtilizationData>();
                }
                return catalogItemData.Values;
            };

            return Ok(from catalogItem in catalog
                     let utilizationInfo = getUtilization(catalogItem.Id.ToString())
                     select new CatalogItemUtilizationDto
                     {
                          Id = catalogItem.Id,
                          DisplayName = catalogItem.DisplayName,
                          Description = catalogItem.Description,
                          Category = catalogItem.Category,
                          ImagePath = Url.Link(nameof(MachineController.GetCatalogImage), new { catalogItemId = catalogItem.Id }),
                          HoursBorrowed = utilizationInfo.Sum(d => d.BorrowedTime.TotalHours),
                          Borrows = utilizationInfo.Sum(d => d.BorrowCount),
                     });
        });
}
```

### PR DESCRIPTION
**Pull request by KevinH-MS**
We shouldn't ignore custom debug info for a method just because it doesn't contain import records.  It may still contain info about local variable scopes, dynamic info, etc...

Note:  VB did not have a problem with this scenario, but I added a unit test for good measure.

(fixes #2240)

### CODE REVIEW

**Comment by KevinH-MS** [comment]
FYI @amcasey @ManishJayaswal

File: src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs [hunk 1]
```diff
@@ -619,7 +619,7 @@ private static BoundStatement BindAssignment(Binder binder, ExpressionSyntax syn
                 BinderFlags.UncheckedRegion |
                 BinderFlags.AllowManagedAddressOf |
                 BinderFlags.AllowAwaitInUnsafeContext);
-            var hasImports = !importRecordGroups.IsDefault;
+            var hasImports = !importRecordGroups.IsDefaultOrEmpty;
```
Comment (amcasey) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs]: I don't believe default and empty are meaningfully different, so we should probably pick one.  Normally, Empty is more convenient for the caller.

File: src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/SymUnmanagedReaderExtensions.cs [hunk 2]
```diff
@@ -21,56 +21,59 @@ internal static class SymUnmanagedReaderExtensions
             var importStringGroups = reader.GetCSharpGroupedImportStrings(methodToken, methodVersion, out externAliasStrings);
             Debug.Assert(importStringGroups.IsDefault == externAliasStrings.IsDefault);
 
-            if (importStringGroups.IsDefault)
+            ArrayBuilder<ImmutableArray<ImportRecord>> importRecordGroupBuilder = null;
```
Comment (amcasey) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/SymUnmanagedReaderExtensions.cs]: Alternatively, make this ```ImmutableArray<ImmutableArray<ImportRecord>>.Empty``` and replace it if there are ```importStringGroups```.

File: src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/SymUnmanagedReaderExtensions.cs [hunk 3]
```diff
@@ -21,56 +21,59 @@ internal static class SymUnmanagedReaderExtensions
...
                     }
+                    importRecordGroupBuilder.Add(groupBuilder.ToImmutableAndFree());
                 }
-                importRecordGroupBuilder.Add(groupBuilder.ToImmutableAndFree());
             }
 
-            var externAliasRecordBuilder = ArrayBuilder<ExternAliasRecord>.GetInstance(externAliasStrings.Length);
-            foreach (string externAliasString in externAliasStrings)
+            ArrayBuilder<ExternAliasRecord> externAliasRecordBuilder = null;
+            if (!externAliasStrings.IsDefault)
```
Comment (amcasey) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/SymUnmanagedReaderExtensions.cs]: I'm not sure what would happen if we had extern aliases without import strings.  I suspect that's what the original if was guarding against.  Perhaps this if should be inside the first one?  You'd have to check the consumers of ```MethodDebugInfo```.

File: src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs (hunk 1 above)
Comment (amcasey) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs]: Oh, we probably get default for ```default(MethodDebugInfo)```.  So it's default if we got no ```MethodDebugInfo``` and empty if there was some, just none about imports?

**Comment by amcasey** [comment]
LGTM, but please check the extern aliases case.

File: src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs (hunk 1 above)
Comment (KevinH-MS) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs]: Yes, that's correct, and we still expect to get a ```default(MethodDebugInfo)``` when we're called from CreateTypeContext.

File: src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/SymUnmanagedReaderExtensions.cs (hunk 2 above)
Comment (KevinH-MS) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/SymUnmanagedReaderExtensions.cs]: I figured I'd avoid the extra local variable (since we'd still need a local variable for the builder).  The builder could be scoped to the if in that case, but still an extra local.

File: src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/SymUnmanagedReaderExtensions.cs (hunk 3 above)
Comment (KevinH-MS) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/SymUnmanagedReaderExtensions.cs]: I attempted to write a test for this (externs with no imports), and I found that ```GetCSharpGroupedImportStrings``` will not populate ```externAliasStrings``` if there are no import strings.  To be on the safe side, I'll nest the ifs so that we don't populate the ```externAliasRecordBuilder``` if there are no import strings.  I'm not going to add a test, because I'd have to remove the Assert above to exercise this scenario.

Comment (amcasey) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/SymUnmanagedReaderExtensions.cs]: Sounds good.  Thanks for checking.
