### PR TITLE
Bug fix for issue #8111 - Don't mark cast as redundant if removing it will change the shape of a new anonymous object

### LINKED ISSUE #8111: IDE0004 "C# Cast is redundant" suggestion when removing cast would change anonymous member type (and program behavior)
Here's a simple console app to demonstrate the issue:

```C#
using System;
namespace ConsoleApplication1
{
    public class Program
    {
        private static void Main(string[] args)
        {
            object thing = new { shouldBeAnInt = (int)Directions.South };
            Console.WriteLine(thing);//should output "{ shouldBeAnInt = 2 }" not "{ shouldBeAnInt = South }"
        }
    }

    public enum Directions { North, East, South, West }
}
```

The anonymous type only knows what data type the `shouldBeAnInt` member is by looking at the right hand side of the assignment. Visual Studio 2015 suggests removing the cast to int, but doing so changes the member's type and the output of the program.

Note that the suggestion goes away if you use `var thing = ...` instead of `object thing = ...`

### PR DESCRIPTION
**Pull request by steveniles**
Fixes #8111

This fixes a corner case in which the IDE0004 diagnostic ("C# Cast is redundant") claims a cast is safe to remove, when removing it could in fact change program behavior, by changing the type of an anonymous object's member

### CODE REVIEW

**Comment by davkean** [comment]
@dotnet-bot test eta please

tag @dotnet/roslyn-ide @DustinCampbell

**Comment by davkean** [comment]
@dotnet-bot retest prtest/mac/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/3066/
// Retest reason: Mono deadlock

File: src/EditorFeatures/CSharpTest/Diagnostics/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.cs [hunk 1]
```diff
@@ -3790,5 +3790,22 @@ private static void RequiresCondition<TException>(bool condition, string message
...
+class Program
+{
+    static void Main(string[] args)
+    {
+        object thing = new { shouldBeAnInt = [|(int)Directions.South|] };
+    }
+    public enum Directions { North, East, South, West }
+}
+");
+        }
```
Comment (DustinCampbell) [inline src/EditorFeatures/CSharpTest/Diagnostics/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.cs]: It's be good to add a test to ensure that it still reports redundant identity casts in this scenario.

Comment (DustinCampbell) [inline src/EditorFeatures/CSharpTest/Diagnostics/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.cs]: Also, tests for casts when the property name is omitted. E.g.

```C#
object thing = new { (int)Directions.South };
```

Comment (steveniles) [inline src/EditorFeatures/CSharpTest/Diagnostics/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.cs]: Both good ideas, I'll try to get those in soon

File: src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs [hunk 2]
```diff
@@ -396,6 +396,12 @@ public static bool IsUnnecessaryCast(this CastExpressionSyntax cast, SemanticMod
                 return expressionType != null && expressionType.Equals(outerType);
             }
 
+            //Don't remove cast if it would change the shape of a new anonymous object
+            if (cast.IsParentKind(SyntaxKind.AnonymousObjectMemberDeclarator))
+            {
+                return false;
+            }
+
```
Comment (DustinCampbell) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: FWIW, I don't think this is the correct fix. It will generally work OK for casts, but it isn't comprehensive enough of a change to address other semantics-preserving rewrites. This would be more appropriately fixed in `SpeculationAnalyzer.ReplacementChangesSemantics()`.

**Comment by DustinCampbell** [comment]
Ignore my comment about `object thing = new { (int)Directions.South };`. My good friend @CyrusNajmabadi just pointed out to me that's not legal syntactically. :smile:

**Comment by davkean** [comment]
tag @dotnet/roslyn-ide for another look.

**Comment by DustinCampbell** [comment]
LGTM :+1:

File: src/Workspaces/CSharp/Portable/Utilities/SpeculationAnalyzer.cs [hunk 3]
```diff
@@ -430,10 +430,23 @@ protected override bool ReplacementChangesSemanticsForNodeLanguageSpecific(Synta
             {
                 return !TypesAreCompatible((ImplicitArrayCreationExpressionSyntax)currentOriginalNode, (ImplicitArrayCreationExpressionSyntax)currentReplacedNode);
             }
+            else if (currentOriginalNode is AnonymousObjectMemberDeclaratorSyntax)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Utilities/SpeculationAnalyzer.cs]: why 'is' instead of the Kind checks like above?

**Comment by CyrusNajmabadi** [comment]
:+1: just had a nit.

File: src/Workspaces/CSharp/Portable/Utilities/SpeculationAnalyzer.cs (hunk 3 above)
Comment (steveniles) [inline src/Workspaces/CSharp/Portable/Utilities/SpeculationAnalyzer.cs]: Saw others with "is", especially at the top of the method, copied that style.

**Comment by davkean** [comment]
Sorry for the late reply on this, we'll try and get this merged in today.

@dotnet-bot test eta please
@dotnet-bot test vsi please

**Comment by natidea** [comment]
@dotnet-bot test eta please
@dotnet-bot test vsi please

**Comment by davkean** [comment]
@dotnet-bot test eta please
@dotnet-bot test vsi please

**Comment by DustinCampbell** [comment]
test vsi please

**Comment by DustinCampbell** [comment]
retest this please

**Comment by DustinCampbell** [comment]
@steveniles -- sorry it took so long to get this one in. Running tests one more time. :smile:

**Comment by steveniles** [comment]
@DustinCampbell No problem, figured it would get done once the issues with the test server(s) were resolved :)
