### PR TITLE
Code Model: Implement IParameterKind legacy interface

### LINKED ISSUE #10525: Code Model: Implement internal IParameterKind interface on CodeParameter
There is an internal interface that we failed to implement on CodeParameter that looks like so:

``` C#
internal enum PARAMETER_PASSING_MODE
{
    cmParameterTypeIn = 1,
    cmParameterTypeOut = 2,
    cmParameterTypeInOut = 3
}

[ComImport()]
[Guid("A55CCBCC-7031-432d-B30A-A68DE7BDAD75")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
[ComVisible(true)]
internal interface IParameterKind
{
    void SetParameterPassingMode(PARAMETER_PASSING_MODE ParamPassingMode);
    void SetParameterArrayDimensions(int ulDimensions);
    int GetParameterArrayCount();
    int GetParameterArrayDimensions(int uIndex);
    PARAMETER_PASSING_MODE GetParameterPassingMode();
}
```

It turns out that this interface is used by the Windows Workflow v1 designer and breaks some particular scenarios.

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes #10525 

We did not implement the internal legacy interface `IParameterKind` on `EnvDTE.CodeParameter` because there were no known consumers. Unfortunately, it appears that there is some old code in the first (i.e. pre-.NET 4.0) version of the Workflow Designer that depends on this interface being present. Without the interface, at least one Workflow activity can not be properly configured within the designer. 

Unfortunately, because the Workflow Designer ships in the .NET Framework, it's far easier to fix this problem in Code Model rather than update Workflow to use a different API. So, this change implements the `IParameterKind` interface. I've verified that the Workflow Designer doesn't work without this change and *does* work properly with it. Plenty 'o unit tests.

cc @dotnet/roslyn-ide for review

### CODE REVIEW

**Comment by DustinCampbell** [comment]
test vsi please

**Comment by DustinCampbell** [comment]
retest prtest/win/vsi/p0

**Comment by DustinCampbell** [comment]
@dotnet-bot retest prtest/win/vsi/p0 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p0/606/
// Retest reason:

**Comment by DustinCampbell** [comment]
Anyone from @dotnet/roslyn-ide want to take a look?

File: src/VisualStudio/CSharp/Impl/CodeModel/CSharpCodeModelService.cs [hunk 1]
```diff
@@ -1967,6 +1968,34 @@ public override SyntaxNode SetParameterKind(SyntaxNode node, EnvDTE80.vsCMParame
...
         }
 
+        public override EnvDTE80.vsCMParameterKind UpdateParameterKind(EnvDTE80.vsCMParameterKind parameterKind, PARAMETER_PASSING_MODE passingMode)
+        {
+            var updatedParameterKind = parameterKind;
+
+            switch (passingMode)
+            {
+                case PARAMETER_PASSING_MODE.cmParameterTypeIn:
+                    updatedParameterKind |= EnvDTE80.vsCMParameterKind.vsCMParameterKindNone;
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/CSharp/Impl/CodeModel/CSharpCodeModelService.cs]: why the ors and ands.  Why not just say if it's cmParameterTypeIn then parameter kind is vsCMParameterKindNone?

File: src/VisualStudio/Core/Impl/CodeModel/InternalElements/CodeParameter.cs [hunk 2]
```diff
@@ -187,5 +188,86 @@ public EnvDTE.CodeAttribute AddAttribute(string name, string value, object posit
...
+            var type = this.ParameterSymbol.Type;
+            var compilation = this.FileCodeModel.GetCompilation();
+
+            var elementType = type is IArrayTypeSymbol
+                ? ((IArrayTypeSymbol)type).ElementType
+                : type;
+
+            // The original C# implementation had a weird behavior where it wold allow setting array dimensions
+            // to 0 to create an array with a single rank.
+            var rank = dimensions > 0
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Impl/CodeModel/InternalElements/CodeParameter.cs]: rank = Max(dimensions, 1)?

File: src/VisualStudio/VisualBasic/Impl/CodeModel/VisualBasicCodeModelService.vb [hunk 3]
```diff
@@ -2027,6 +2032,27 @@ Namespace Microsoft.VisualStudio.LanguageServices.VisualBasic.CodeModel
...
+                    updatedParameterKind = updatedParameterKind And Not EnvDTE80.vsCMParameterKind.vsCMParameterKindRef
+                    updatedParameterKind = updatedParameterKind And Not EnvDTE80.vsCMParameterKind.vsCMParameterKindOut
+
+                Case PARAMETER_PASSING_MODE.cmParameterTypeInOut
+                    updatedParameterKind = updatedParameterKind And Not EnvDTE80.vsCMParameterKind.vsCMParameterKindIn
+                    updatedParameterKind = updatedParameterKind Or EnvDTE80.vsCMParameterKind.vsCMParameterKindRef
+                    updatedParameterKind = updatedParameterKind And Not EnvDTE80.vsCMParameterKind.vsCMParameterKindOut
+
+                Case PARAMETER_PASSING_MODE.cmParameterTypeOut
+                    Throw Exceptions.ThrowEInvalidArg()
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/VisualBasic/Impl/CodeModel/VisualBasicCodeModelService.vb]: Maybe makes more sense to be vsCMParameterKindRef here?

**Comment by CyrusNajmabadi** [comment]
:+1:

File: src/VisualStudio/VisualBasic/Impl/CodeModel/VisualBasicCodeModelService.vb (hunk 3 above)
Comment (DustinCampbell) [inline src/VisualStudio/VisualBasic/Impl/CodeModel/VisualBasicCodeModelService.vb]: T'would be a code model breaking change.

File: src/VisualStudio/CSharp/Impl/CodeModel/CSharpCodeModelService.cs (hunk 1 above)
Comment (DustinCampbell) [inline src/VisualStudio/CSharp/Impl/CodeModel/CSharpCodeModelService.cs]: Because there are also flags for Params and Optional that I don't want to blow out.

File: src/VisualStudio/Core/Impl/CodeModel/InternalElements/CodeParameter.cs (hunk 2 above)
Comment (DustinCampbell) [inline src/VisualStudio/Core/Impl/CodeModel/InternalElements/CodeParameter.cs]: Nice! Will do.

File: src/VisualStudio/CSharp/Impl/CodeModel/CSharpCodeModelService.cs (hunk 1 above)
Comment (CyrusNajmabadi) [inline src/VisualStudio/CSharp/Impl/CodeModel/CSharpCodeModelService.cs]: Ah, that makes sense.

File: src/VisualStudio/VisualBasic/Impl/CodeModel/VisualBasicCodeModelService.vb (hunk 3 above)
Comment (CyrusNajmabadi) [inline src/VisualStudio/VisualBasic/Impl/CodeModel/VisualBasicCodeModelService.vb]: Really?  Do we think people depend on getting an exception fi they do this? :)   Is it really a breaking change to *stop* throwing an exception and to have somewhat of a better fallback?  

That said, this is all legacy, so do what you want :)

Comment (DustinCampbell) [inline src/VisualStudio/VisualBasic/Impl/CodeModel/VisualBasicCodeModelService.vb]: Yeah, I don't like it either. However, striving to throw the same exceptions is something we've done in Code Model to date.

I hate Code Model. :smile:

**Comment by DustinCampbell** [comment]
@Pilchie, do you want to take a look?

**Comment by Pilchie** [comment]
:+1:
