### PR TITLE
Fixing 'else' keyword completion

### LINKED ISSUE #25336: Missing completion for 'else' after nested if with else
```c#
if (true)
    if (true)
        Console.WriteLine();
    else
        Console.WriteLine();
$$ // 'else' is not in the completion list
```

### PR DESCRIPTION
**Pull request by Neme12**
fixes #25336

I tried rewriting the tests using theory at the end to make them less overwhelming and significantly reduce the repetition, but I'm not sure if it's the right thing to do considering that this sort of approach isn't used in any other tests.
@CyrusNajmabadi I think I remember you saying that tests should contain the literal code so that it's easy to understand each one separately and we should generally avoid using any sort of helpers. Do you think what I did here is acceptable?

### CODE REVIEW

File: src/EditorFeatures/CSharpTest2/Recommendations/ElseKeywordRecommenderTests.cs [hunk 1]
```diff
@@ -86,43 +90,218 @@ public class ElseKeywordRecommenderTests : KeywordRecommenderTests
...
+        [Statements]
+        public async Task TestAfterIfStatement(string statement)
         {
             await VerifyKeywordAsync(AddInsideMethod(
-@"if (true)
-{
-    Console.WriteLine();
-}
+$@"if (true)
+    {statement}
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest2/Recommendations/ElseKeywordRecommenderTests.cs]: i personally dislike this.  I cannot see what's happening.  My tests are now non-local.  

The only sort of 'theory' approach i've ever been ok with is targetted, simple application of theories, where the theory is on hte test method itself.  if i have to look up more than 2-3 lines, or i have to go look at another *class*/*method* etc. then i've completely lost the plot on what the test is testing.  Previously i could see this exactly.  Now i can't.  this is a net negative for me here.

File: src/EditorFeatures/CSharpTest2/Recommendations/ElseKeywordRecommenderTests.cs [hunk 2]
```diff
@@ -86,43 +90,218 @@ public class ElseKeywordRecommenderTests : KeywordRecommenderTests
...
-            await VerifyKeywordAsync(AddInsideMethod(
+            await VerifyAbsenceAsync(AddInsideMethod(
 @"if (true)
-    Console.WriteLine();
 $$"));
         }
 
-        [Fact, Trait(Traits.Feature, Traits.Features.KeywordRecommending)]
-        public async Task TestAfterIfBlock()
+        class Statements : DataAttribute
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest2/Recommendations/ElseKeywordRecommenderTests.cs]: private

File: src/EditorFeatures/CSharpTest2/Recommendations/ElseKeywordRecommenderTests.cs (hunk 1 above)
Comment (Neme12) [reply src/EditorFeatures/CSharpTest2/Recommendations/ElseKeywordRecommenderTests.cs]: ok I can revert it back... it just seemed to me like this way it's much easier to read, review and spot bugs in the tests, whereas with a lot of duplication it's really easy to miss something

**Comment by CyrusNajmabadi** [comment]
> I tried rewriting the tests using theory at the end to make them less overwhelming

To me this i a non-problem.  I don't think of test quantity as being "overwhelming".  It's just a lot of tests.  There are still the same number of tests when you use theories, you just have used a generation technique to produce the tests, which i think decreases clarity.

At the end of hte day you generally have 100% test coverage until you break something and either a single test breaks, or a set of tests break.  You go and look at those tests, figure it out and rinse/repeat.  The number of total tests isn't really relevant here.

File: src/EditorFeatures/CSharpTest2/Recommendations/ElseKeywordRecommenderTests.cs (hunk 1 above)
Comment (Neme12) [reply src/EditorFeatures/CSharpTest2/Recommendations/ElseKeywordRecommenderTests.cs]: and also more importantly, when writing more tests people will usually avoid writing all the cases and just do some of them to not bother with writing so much duplication, which can sometimes miss bugs due to missing test cases

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest2/Recommendations/ElseKeywordRecommenderTests.cs]: IMO, tests for this sort of thing should be written based on the expected interesting cases based on the code change.  So, your change adds an arbitrary walk upwards looking for if-statements.  And it also checks that if-statement for the last token of the true-statement within it.

It seems like we could test this out with some very judicious tests that would demonstrate that both of those pieces of logic are working properly.  For example, we sholud not see 'else' here:

```c#
if (true) 
     Console.WriteLine()
$$
```

Because the last token of hte true-statement would be the missing-token ```;``` and htat's not what we're on.  Similarly, we should see if after ```Console.WriteLine();```.  And we should see if htis if it deeply nested.   Testing one level deep, two levels deep, and something larger should be sufficient.

This does not seem like a lot of tests needed.  It tests positive and negative cases.  And feels appropriate given the code change.

**Comment by Neme12** [comment]
@CyrusNajmabadi What if I put InlineData on each test instead but still kept it as a theory? How would you feel about that?

File: src/EditorFeatures/CSharpTest2/Recommendations/ElseKeywordRecommenderTests.cs (hunk 1 above)
Comment (Neme12) [reply src/EditorFeatures/CSharpTest2/Recommendations/ElseKeywordRecommenderTests.cs]: Thanks, I'll add tests for that too.

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest2/Recommendations/ElseKeywordRecommenderTests.cs]: > it just seemed to me like this way it's much easier to read, review and spot bugs in the tests

It's harder for me, because i ca'nt just look at a test and know what it means.  I have to go analyze other parts of the test file to know.  We try to avoid that.  I've accepted some Theories in hte past where the theory *travels* with the test method.  and the theory itself is very tiny.  i.e. i've seen theories that try to do major replacements in the code, and def make it less clear. 

I'm on the fence here about this one.  But, give my previous post, i don't think it adds substantial value given just writing the 6ish test cases manually.

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/ElseKeywordRecommender.cs [hunk 3]
```diff
@@ -23,35 +23,21 @@ protected override bool IsValidContext(int position, CSharpSyntaxContext context
...
-            // if (goo) {
-            //     Console.WriteLine();
-            //   } |
-            //   if (goo) {
-            //     Console.WriteLine();
-            //   } e|
-            if (token.IsKind(SyntaxKind.CloseBraceToken) && ifStatement.Statement is BlockSyntax && token == ((BlockSyntax)ifStatement.Statement).CloseBraceToken)
-            {
-                return true;
+                if (ifStatement.Statement.GetLastToken(includeSkipped: true, includeZeroWidth: true) == token)
```
Comment (Neme12) [inline src/Features/CSharp/Portable/Completion/KeywordRecommenders/ElseKeywordRecommender.cs]: I actually have no idea why `includeSkipped: true` is needed here.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi What if I put InlineData on each test instead but still kept it as a theory? How would you feel about that?

I would probably be ok with that.  though i like the InlineData to be small to be clear as to what's going on.  In your case, it's likely ok.  But it's not a blanket rule that that's ok for all tests.

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/ElseKeywordRecommender.cs (hunk 3 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/Completion/KeywordRecommenders/ElseKeywordRecommender.cs]: IncludeSkipped is likely appropriate, though harder to test for.  It basically means, "if the parser  ran into stuff it totally didn't understand, but it attached it to that staement, then treat hte *last* token of that skipped run of tokens as the last token of the statement.

Comment (Neme12) [reply src/Features/CSharp/Portable/Completion/KeywordRecommenders/ElseKeywordRecommender.cs]: What this actually does is in cases like this:
```c#
if (true)
    hello();,
```
it *prevents* `else` from being offered because context.TargetToken does not include skipped tokens.
Is that the intended behavior here?

Comment (Neme12) [reply src/Features/CSharp/Portable/Completion/KeywordRecommenders/ElseKeywordRecommender.cs]: It seems really unlikely that there would be a skipped semicolon at the end. That usually parsers as a separate empty statement.

Comment (Neme12) [reply src/Features/CSharp/Portable/Completion/KeywordRecommenders/ElseKeywordRecommender.cs]: In the original implementation, `else` is *not* offered in code like this (because the last token is not a semicolon or a close brace):
```c#
if (true)
    hello();,
```
But with this PR, `else` *is* offered. Which is the expected behavior here?

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/Completion/KeywordRecommenders/ElseKeywordRecommender.cs]: > Which is the expected behavior here? 

The expected behavior is whatever is easiest to provide :)

You could literally have this work, and that would be ok.  Or it could not work, and that would be ok.

Comment (Neme12) [reply src/Features/CSharp/Portable/Completion/KeywordRecommenders/ElseKeywordRecommender.cs]: > whatever is easiest to provide

The difference is just in setting `includeSkipped` to either true or false. Then I guess easiest to provide would be to not specify the argument?

Comment (Neme12) [reply src/Features/CSharp/Portable/Completion/KeywordRecommenders/ElseKeywordRecommender.cs]: Given that there is absolutely no completion for anything after such skipped tokens and the fact that if you type `else` at that point it doesn't actually end up being an else clause (it also becomes a skipped token), I'm removing this.

File: src/EditorFeatures/CSharpTest2/Recommendations/ElseKeywordRecommenderTests.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest2/Recommendations/ElseKeywordRecommenderTests.cs]: Yes.  this form seems ok to me.  i can live with inline data at individual test sites.

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/ElseKeywordRecommender.cs [hunk 4]
```diff
@@ -23,35 +23,21 @@ protected override bool IsValidContext(int position, CSharpSyntaxContext context
...
-            // if (goo) {
-            //     Console.WriteLine();
-            //   } |
-            //   if (goo) {
-            //     Console.WriteLine();
-            //   } e|
-            if (token.IsKind(SyntaxKind.CloseBraceToken) && ifStatement.Statement is BlockSyntax && token == ((BlockSyntax)ifStatement.Statement).CloseBraceToken)
-            {
-                return true;
+                if (ifStatement.Statement.GetLastToken(includeZeroWidth: true) == token)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/KeywordRecommenders/ElseKeywordRecommender.cs]: warrants a comment.   but not a big deal.

**Comment by Neme12** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by Neme12** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by Neme12** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by Neme12** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by jcouv** [comment]
@dotnet/roslyn-ide Can this community PR get a final review?

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/ElseKeywordRecommender.cs (hunk 4 above)
Comment (Neme12) [reply src/Features/CSharp/Portable/Completion/KeywordRecommenders/ElseKeywordRecommender.cs]: fixed in 0c495ca42df1962d6406ee762f351ed6c9824186
