### PR TITLE
Show object creation completion before braces

### LINKED ISSUE #13402: No intellisense after new in object creation expression [braces case]
**Version Used**: 25618.00/2.0.0.60808

**Steps to Reproduce**:

``` C#
class Program
{
    static void Main(string[] args)
    {
        Program p = new |
        { }
    }
}
```

**Expected Behavior**:
`Program` preselected in autocomplete list.

**Actual Behavior**:
List not offered and nothing preselected if invoked. More evident if different type is used last, e.g.

``` C#
Dictionary<float, float> f = new |
{ }
```

This is another, like fourth or fifth case of the "no intellisense after new keyword" problem. Rather than hitting the individual things that can possible appear after `new` and exempting them, couldn't this be perhaps done from the other end?

cf. #2836 #12755
/cc @balajikris @rchande

### PR DESCRIPTION
**Pull request by rchande**
Fixes #13402
Tag @dotnet/roslyn-ide for review

### CODE REVIEW

File: src/Workspaces/CSharp/Portable/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs [hunk 1]
```diff
@@ -240,6 +241,8 @@ protected override IEnumerable<TypeInferenceInfo> InferTypesWorker_DoNotCallDire
                 }
             }
 
+            private IEnumerable<TypeInferenceInfo> InferTypeInAnonymousObjectCreation(AnonymousObjectCreationExpressionSyntax expression) => InferTypes(expression.SpanStart);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs]: 1. you need to pass the token in and validate that it's the 'new' token.  For examlpe, we should not infer a type in "new {$$" or "new { }$$".

2. If you use=> then wrap, so that it is visible on github.

**Comment by Pilchie** [comment]
This should be targeting `post-dev15`, right?

**Comment by CyrusNajmabadi** [comment]
👍
