### PR TITLE
Fix a few param-nullchecking parsing bugs

### LINKED ISSUE #58585: Invalid null-checked parameter syntax doesn't cause errors.
From offline convo with @RikkiGibson :   `public C(string x!) { }` shoudl not parse.  Also, it's likely that we're parsing `string x!!= = 0` improperly (creating an invalid tree that violates roslyn invariants).

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #58585

Thanks to Cyrus for the greater part of the work here.

Relates to test plan https://github.com/dotnet/roslyn/issues/36024

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 1]
```diff
@@ -4423,12 +4431,12 @@ private ParameterSyntax ParseParameter()
...
+                    }
                 }
 
-                if (this.CurrentToken.Kind == SyntaxKind.EqualsToken)
-                {
-                    equals = this.EatToken(SyntaxKind.EqualsToken);
-                }
                 if (exclamationExclamation != null)
                 {
                     exclamationExclamation = (exclamationExclamation.Kind != SyntaxKind.ExclamationExclamationToken)
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:4442]: i don't see hwo this case ever happens.  eerything that sets exclamationExclamation has already made an ExclamationExclamationToken.  Indeed, i think we can have a contract call for exactly that.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 2]
```diff
@@ -4406,6 +4406,10 @@ private ParameterSyntax ParseParameter()
                         else
                         {
                             exclamationExclamation = MergeTokens(exclamationExclamation, this.EatToken(SyntaxKind.ExclamationToken), SyntaxKind.ExclamationExclamationToken);
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:4408]: are you still intending to fix the missing diagnostic lifting for this case?

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 3]
```diff
@@ -13619,7 +13627,7 @@ private new struct ResetPoint
 
         private SyntaxToken MergeTokens(SyntaxToken s1, SyntaxToken s2, SyntaxKind kind)
         {
-            if (s1.GetTrailingTriviaWidth() == 0 && s2.GetLeadingTriviaWidth() == 0)
+            if (!s1.ContainsDiagnostics && !s2.ContainsDiagnostics && s1.GetTrailingTriviaWidth() == 0 && s2.GetLeadingTriviaWidth() == 0)
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:13630]: oh interesting.  i don't love this approach.  i think we should instead always just merge, and say the caller only calls into thsi when they have both of  these tokens.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs (hunk 2 above)
Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:4408]: ok.  so my recommendation is to get current token for being exclamation.  If so, grab and merge (if valid to do so).  

otherwise, have a dedicate branch for just single `!` and give the one messaget htere and convert it to !!.  then lower down you don't need to do any further checking that your !! was actually a !!.,

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 4]
```diff
@@ -11539,12 +11603,12 @@ bool isParenVarCommaSyntax()
...
                         }
+
+                        var token3 = this.PeekToken(3);
                         // ( x!! , [...]
                         // https://github.com/dotnet/roslyn/issues/58335: https://github.com/dotnet/roslyn/pull/46520#discussion_r466650228
                         if (after.Kind == SyntaxKind.ExclamationToken
-                            && this.PeekToken(3).Kind == SyntaxKind.ExclamationToken
-                            && after.GetTrailingTriviaWidth() == 0
-                            && this.PeekToken(3).GetLeadingTriviaWidth() == 0
+                            && token3.Kind == SyntaxKind.ExclamationToken
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:11617]: intentionally removed this restriction.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 5]
```diff
@@ -11614,9 +11678,7 @@ private bool ScanExplicitlyTypedLambda(Precedence precedence)
                         this.EatToken();
                     }
                     if (this.CurrentToken.Kind == SyntaxKind.ExclamationToken
-                        && this.PeekToken(1).Kind == SyntaxKind.ExclamationToken
-                        && this.CurrentToken.GetTrailingTriviaWidth() == 0
-                        && this.PeekToken(1).GetLeadingTriviaWidth() == 0)
+                        && this.PeekToken(1).Kind == SyntaxKind.ExclamationToken)
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:11687]: intentionally removed this restriction.

File: src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs [hunk 6]
```diff
@@ -7383,8 +7422,44 @@ public void TestNullCheckedArgList()
                     N(SyntaxKind.CloseBraceToken);
                 }
             }
+            EOF();
         }
 
+        [Fact]
+        public void TestArgListWithDefaultValue()
+        {
+            UsingStatement(@"void M(__arglist = null) { }", options: TestOptions.RegularPreview); N(SyntaxKind.LocalFunctionStatement);
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs:7431]: still need to open an issue on this.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 7]
```diff
@@ -4385,71 +4386,132 @@ private ParameterSyntax ParseParameter()
...
+        /// </summary>
+        private SyntaxToken? MergeAdjacent(SyntaxToken t1, SyntaxToken t2, SyntaxKind kind)
+        {
+            if (t1.GetTrailingTriviaWidth() == 0 && t2.GetLeadingTriviaWidth() == 0)
+                return SyntaxFactory.Token(t1.GetLeadingTrivia(), kind, t2.GetTrailingTrivia());
+
+            var sb = PooledStringBuilder.GetInstance();
+            var writer = new System.IO.StringWriter(sb.Builder, System.Globalization.CultureInfo.InvariantCulture);
+            t1.WriteTo(writer, leading: false, trailing: true);
+            t2.WriteTo(writer, leading: true, trailing: false);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:4502]: It might be good to move this and the below 'NoTriviaBetween' helper down to the original location at the bottom of the file, so that auditing the changes made over time is a little easier.

File: src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs [hunk 8]
```diff
@@ -7574,7 +7706,7 @@ public void TestNullCheckedArgWithSpaceInbetween()
                             N(SyntaxKind.StringKeyword);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs:7706]: much better!

File: src/Compilers/CSharp/Test/Syntax/Parsing/LambdaParameterParsingTests.cs [hunk 9]
```diff
@@ -1805,7 +1744,170 @@ public void TestNullCheckedSyntaxCorrection9()
...
+            EOF();
+        }
+
+        [Fact]
+        public void TestBracesAfterParenthesizedLambdaName()
+        {
+            UsingDeclaration("Func<string[], string> func0 = (x[]) => x;", options: TestOptions.RegularPreview,
+                    // (1,36): error CS1001: Identifier expected
+                    // Func<string[], string> func0 = (x[]) => x;
+                    Diagnostic(ErrorCode.ERR_IdentifierExpected, ")").WithLocation(1, 36)); N(SyntaxKind.FieldDeclaration);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Syntax/Parsing/LambdaParameterParsingTests.cs:1845]: I don't mind this parse, but I was confused that it expected an identifier instead of `)`.

File: src/Compilers/CSharp/Test/Syntax/Parsing/LambdaParameterParsingTests.cs [hunk 10]
```diff
@@ -1818,6 +1920,1047 @@ public void TestNullCheckedSyntaxCorrection9()
...
+            EOF();
+        }
+
+        [Fact]
+        public void TestDefaultValueParenthesizedLamda2()
+        {
+            UsingDeclaration("Func<string, string> func0 = (y, x = null) => x;", options: TestOptions.RegularPreview,
+                    // (1,44): error CS1003: Syntax error, ',' expected
+                    // Func<string, string> func0 = (y, x = null) => x;
+                    Diagnostic(ErrorCode.ERR_SyntaxError, "=>").WithArguments(",", "=>").WithLocation(1, 44)); N(SyntaxKind.FieldDeclaration);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Syntax/Parsing/LambdaParameterParsingTests.cs:2114]: does make me wonder if there is more room to unify on parameter lists in parenthesized lambdas and non-lambdas, and if we could simplify the parser and move some errors like these to binding in the process.

File: src/Compilers/CSharp/Test/Syntax/Parsing/LambdaParameterParsingTests.cs [hunk 11]
```diff
@@ -1818,6 +1920,1047 @@ public void TestNullCheckedSyntaxCorrection9()
...
+            UsingDeclaration("Func<string, string> func0 = (string y, string x!! = null) => x;", options: TestOptions.RegularPreview,
+                // (1,41): error CS1525: Invalid expression term 'string'
+                // Func<string, string> func0 = (string y, string x!! = null) => x;
+                Diagnostic(ErrorCode.ERR_InvalidExprTerm, "string").WithArguments("string").WithLocation(1, 41),
+                // (1,48): error CS1026: ) expected
+                // Func<string, string> func0 = (string y, string x!! = null) => x;
+                Diagnostic(ErrorCode.ERR_CloseParenExpected, "x").WithLocation(1, 48),
+                // (1,48): error CS1003: Syntax error, ',' expected
+                // Func<string, string> func0 = (string y, string x!! = null) => x;
+                Diagnostic(ErrorCode.ERR_SyntaxError, "x").WithArguments(",", "").WithLocation(1, 48)); N(SyntaxKind.FieldDeclaration);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Syntax/Parsing/LambdaParameterParsingTests.cs:2586]: looks like formatting is wrong here and in many of the other new tests.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs (hunk 4 above)
Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:11609]: correct!  it also means there's uniform 'token handling' that goes in before calling the helper.  none of these scanners (or hte helper) care about having this requirement.  it means they're all resilient to accidental spaces happening as you edit.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 12]
```diff
@@ -11539,12 +11609,12 @@ bool isParenVarCommaSyntax()
                         {
                             return true;
                         }
+
+                        var token3 = this.PeekToken(3);
```
[the remark this answers is not in the document]
Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:11605]: agreed

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 13]
```diff
@@ -11855,28 +11923,40 @@ private bool IsPossibleLambdaExpression(Precedence precedence)
...
                 return true;
             }
 
             // Broken case but error will be added in lambda function (!!=>).
-            if (token1 == SyntaxKind.ExclamationToken
-                && this.PeekToken(2).Kind == SyntaxKind.ExclamationEqualsToken
-                && this.PeekToken(3).Kind == SyntaxKind.GreaterThanToken)
+            if (token1.Kind == SyntaxKind.ExclamationToken
+                && token2.Kind == SyntaxKind.ExclamationEqualsToken
+                && token3.Kind == SyntaxKind.GreaterThanToken)
```
[the remark this answers is not in the document]
Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:11951]: yup.  i def like that!

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 14]
```diff
@@ -12888,52 +12968,31 @@ LambdaExpressionSyntax parseLambdaExpressionWorker()
                 }
                 else
                 {
-                    var name = this.ParseIdentifierToken();
-                    SyntaxToken arrow, exclamationExclamation;
-                    // Case x!! =>
-                    if (this.CurrentToken.Kind == SyntaxKind.ExclamationToken)
+                    var identifier = this.ParseIdentifierToken();
```
[the remark this answers is not in the document]
Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:12963]: makes esnse

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 15]
```diff
@@ -13056,19 +13115,15 @@ private ParameterSyntax ParseLambdaParameter()
...
-            {
-                exclamationExclamation = (exclamationExclamation.Kind != SyntaxKind.ExclamationExclamationToken)
-                    ? ConvertToMissingWithTrailingTrivia(exclamationExclamation, SyntaxKind.ExclamationExclamationToken)
-                    : CheckFeatureAvailability(exclamationExclamation, MessageID.IDS_ParameterNullChecking);
-            }
-            var parameter = _syntaxFactory.Parameter(attributes, modifiers.ToList(), paramType, paramName, exclamationExclamation, null);
+            var identifier = this.ParseIdentifierToken();
+            ParseParameterNullCheck(out var exclamationExclamationToken, out var equalsToken);
+
+            // This should never be non-null.  That indicates while we were scanning for potential lambdas, we saw an
```
[the remark this answers is not in the document]
Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:13113]: right!

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 16]
```diff
@@ -4386,70 +4387,139 @@ private ParameterSyntax ParseParameter()
...
+
+        /// <summary>
+        /// Merges two successive tokens into a single token with the given <paramref name="kind"/>.  If the two tokens
+        /// have no trivia between them, then the final token will be trivially generated, properly passing on the right
+        /// leading/trailing trivia.  However, if there is trivia between the tokens, then appropriate errors will be
+        /// reported that the tokens cannot merge successfully.
+        /// </summary>
+        private SyntaxToken? MergeAdjacent(SyntaxToken t1, SyntaxToken t2, SyntaxKind kind)
+        {
+            if (t1.GetTrailingTriviaWidth() == 0 && t2.GetLeadingTriviaWidth() == 0)
```
[the remark this answers is not in the document]
Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:4496]: yup!

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 17]
```diff
@@ -4386,70 +4387,139 @@ private ParameterSyntax ParseParameter()
...
+                return SyntaxFactory.Token(t1.GetLeadingTrivia(), kind, t2.GetTrailingTrivia());
+
+            var sb = PooledStringBuilder.GetInstance();
+            var writer = new System.IO.StringWriter(sb.Builder, System.Globalization.CultureInfo.InvariantCulture);
```
[the remark this answers is not in the document]
Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:4500]: oh yeah :-/  wonky!

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 18]
```diff
@@ -4385,71 +4386,132 @@ private ParameterSyntax ParseParameter()
...
+                SyntaxFactory.Token(t1.GetLeadingTrivia(), kind, text, text, t2.GetTrailingTrivia()),
+                GetExpectedTokenError(kind, t1.Kind));
+        }
+
+        private static bool NoTriviaBetween(SyntaxToken token1, SyntaxToken token2)
+            => token1.GetTrailingTriviaWidth() == 0 && token2.GetLeadingTriviaWidth() == 0;
+
+#nullable disable
+
         private static bool IsParameterModifier(SyntaxKind kind, bool isFunctionPointerParameter = false)
```
[the remark this answers is not in the document]
Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:4515]: hrmm.. this comment seems to be in the wrong place.  what is this referring to?

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs (hunk 7 above)
Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:4502]: sure!

File: src/Compilers/CSharp/Test/Syntax/Parsing/LambdaParameterParsingTests.cs (hunk 9 above)
Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Test/Syntax/Parsing/LambdaParameterParsingTests.cs:1845]: good point.  let me look into that!

File: src/Compilers/CSharp/Test/Syntax/Parsing/LambdaParameterParsingTests.cs (hunk 10 above)
Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Test/Syntax/Parsing/LambdaParameterParsingTests.cs:2114]: this is definitely possible.  the IsPossibleLambda will have to do much more speculative parsing to handle the `= null` places whatnot.  I put these tests in though so we could see the improvement if we do that.  

i'm open to doing more in this PR if you've like!

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs (hunk 18 above)
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:4515]: It was referring to the `GetExpectedTokenError()` call in the `MergeAdjacent()` method.

[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:4515]: Have clarified offline. The call is doing the right thing here. Replacing a token with a bad kind with an "error" token with the expected kind.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs (hunk 7 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:4503]: I found this too cumbersome, better to just have it here than introduce a new nullable region etc.

File: src/Compilers/CSharp/Test/Syntax/Parsing/LambdaParameterParsingTests.cs (hunk 10 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Syntax/Parsing/LambdaParameterParsingTests.cs]: I think we should consider it a "design debt" issue to address in the future.

File: src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs (hunk 6 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs]: Opened #58672

**Comment by RikkiGibson** [comment]
The test failure in Unix is due to a whitespace/line ending difference. Haven't quite figured out how to hammer it down.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 19]
```diff
@@ -4385,71 +4387,132 @@ private ParameterSyntax ParseParameter()
...
             finally
             {
                 _pool.Free(modifiers);
             }
         }
 
+#nullable enable
+
+        /// <summary>
+        /// Parses out the <c>!!</c> following once the type and identifier has been parsed out already.  If the token
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:4429]: The comment wording seems a little complicated. Perhaps:

```suggestion
        /// Parses the <c>!!</c> following a parameter type and identifier.  If the token
```

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 20]
```diff
@@ -4385,71 +4387,132 @@ private ParameterSyntax ParseParameter()
...
+        /// is followed by <c>!!=</c> or <c>! !=</c>, then the final equals will be returned out through <paramref
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:4430]: The comment wording seems a little complicated. Perhaps:

```suggestion
        /// Parses the <c>!!</c> following a parameter type and identifier.  If the token
        /// is followed by <c>!!=</c> or <c>! !=</c>, then the final equals will be returned through <paramref
```

File: src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs [hunk 21]
```diff
@@ -7677,15 +7810,16 @@ public void TestNullCheckedArgWithSpaceAfterBangs()
...
             }
+            EOF();
         }
 
         [Fact]
         public void TestNullCheckedArgWithSpaceBeforeBangs()
         {
             UsingStatement(@"void M(string name ! !=null) { }", options: TestOptions.RegularPreview,
-                    // (1,22): error CS1525: Invalid expression term '!'
+                    // (1,20): error CS1003: Syntax error, '!!' expected
```
Comment (cston) [inline src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs:7820]: >'!!' expected [](http://example.com/codeflow?start=59&length=13)

Are we testing this case with trailing and leading trivia on the two tokens? Perhaps something like:

```csharp
void M(string name ! /*comment1*/
/*comment2*/!);
```

File: src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs [hunk 22]
```diff
@@ -7272,6 +7272,44 @@ public void TestMethodDeclarationNullValidation()
             }
         }
 
+        [Fact]
+        public void TestMethodDeclarationNullValidation_SingleExclamation()
+        {
+            UsingStatement(@"void M(string name!) { }", options: TestOptions.RegularPreview,
+                    // (1,19): error CS1003: Syntax error, '!!' expected
```
Comment (cston) [inline src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs:7279]: >'!!' expected [](http://example.com/codeflow?start=59&length=13)

Are we testing this case with trailing and leading trivia on the `!` token? Perhaps:

```csharp
void M(string name
/*comment1*/!/*comment2*/);
```

**Comment by cston** [comment]
>                 if (opToken.GetTrailingTriviaWidth() == 0 && tk.GetLeadingTriviaWidth() == 0)

`NoTriviaBetween(opToken, tk)`

---
Refers to: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:3516 in 1d233bf. [](commit_id = 1d233bf2d217759c0d70eecbbdaa764af3669c42, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 23]
```diff
@@ -12888,52 +12952,34 @@ LambdaExpressionSyntax parseLambdaExpressionWorker()
...
-
-                    if (exclamationExclamation != null)
-                    {
-                        exclamationExclamation = (exclamationExclamation.Kind != SyntaxKind.ExclamationExclamationToken)
-                            ? ConvertToMissingWithTrailingTrivia(exclamationExclamation, SyntaxKind.ExclamationExclamationToken)
-                            : CheckFeatureAvailability(exclamationExclamation, MessageID.IDS_ParameterNullChecking);
                     }
 
                     if (arrow != null)
-                    {
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:12928]: >{ [](http://example.com/codeflow?start=20&length=1)

Consider adding back the `{` and `}`.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 24]
```diff
@@ -13056,19 +13102,15 @@ private ParameterSyntax ParseLambdaParameter()
...
-                    ? ConvertToMissingWithTrailingTrivia(exclamationExclamation, SyntaxKind.ExclamationExclamationToken)
-                    : CheckFeatureAvailability(exclamationExclamation, MessageID.IDS_ParameterNullChecking);
-            }
-            var parameter = _syntaxFactory.Parameter(attributes, modifiers.ToList(), paramType, paramName, exclamationExclamation, null);
+            var identifier = this.ParseIdentifierToken();
+            ParseParameterNullCheck(out var exclamationExclamationToken, out var equalsToken);
+
+            // 'equalsToken' should always be null here. Otherwise, it means while we were scanning
+            // for potential lambdas, we saw an `!!=` or `!=` sign in the parameter list and allowed
+            // it. However, that should never happen as ScanParenthesizedLambda only allows !! only.
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:13110]:
```suggestion
            // for potential lambdas, we saw an `!!=` or `!=` in the parameter list and allowed
            // it. However, that should never happen as ScanParenthesizedLambda allows `!!` only.
```

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullCheckedParameterTests.cs [hunk 25]
```diff
@@ -129,59 +129,49 @@ public void NullCheckedBadSyntax()
 #pragma warning disable CS8893
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullCheckedParameterTests.cs:129]: >warning disable CS8893 [](http://example.com/codeflow?start=8&length=22)

Was this `#pragma` disabling the warning previously? Does it now? (Was there a reason to change the parameter default value from `null` in each of the methods?)

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullCheckedParameterTests.cs:129]: *sigh* yes, some renumbering must have broken it. I feel it's simpler to use a literal string here, so if you don't object I'd like to keep it as it is in this PR. But I will delete the pragma.

File: src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs (hunk 22 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Syntax/Parsing/DeclarationParsingTests.cs:7279]: Added the test in ae0c6bf

File: src/Compilers/CSharp/Test/Syntax/Parsing/LambdaParameterParsingTests.cs [hunk 26]
```diff
@@ -1818,6 +1928,1063 @@ public void TestNullCheckedSyntaxCorrection9()
...
+                        }
+                    }
+                }
+                N(SyntaxKind.SemicolonToken);
+            }
+            EOF();
+        }
+
+        [Fact]
+        public void TestDefaultValueParenthesizedLamda1()
```
Comment (cston) [inline src/Compilers/CSharp/Test/Syntax/Parsing/LambdaParameterParsingTests.cs:2060]: >Lamda [](http://example.com/codeflow?start=49&length=5)

Typo. It looks like there several instances of this.

**Review by cston — APPROVED** [review]

**Review by chsienki — APPROVED** [review]
LGTM
