### PR TITLE
Handle names in long tuples in EE

### LINKED ISSUE #13625: Incorrect names in the EE in long tuple
Names in the last nested tuple of `C.F` are incorrect in the EE.
```
class C
{
    static ((int A, (int B, int C) D, int E, int F, int G, int H, int I, int J) K, (int L, int M, int N) O) F =
        ((1, (2, 3), 4, 5, 6, 7, 8, 9), (10, 11, 12));
}
```
Result:
```
((int A, (int B, int C) D, int E, int F, int G, int H, int I, int J) K, (int, int L, int M) O)
```

### PR DESCRIPTION
**Pull request by cston**
Handle names in long tuples in EE

Fixes #13625

### CODE REVIEW

**Comment by cston** [comment]
@agocke, @vsadov, @jcouv, @kevinh-ms, @dotnet/roslyn-compiler please review.

File: src/ExpressionEvaluator/Core/Source/ResultProvider/Helpers/TypeHelpers.cs [hunk 1]
```diff
@@ -389,6 +389,14 @@ internal static bool IsTupleCompatible(this Type type, out int cardinality)
             return false;
         }
 
+        // Returns cardinality if tuple type, otherwise 0.
+        internal static int GetTupleCardinalityIfAny(this Type type)
```
Comment (agocke) [inline src/ExpressionEvaluator/Core/Source/ResultProvider/Helpers/TypeHelpers.cs]: Have we removed 0-cardinality tuples? Otherwise this could be a problem :)

File: src/ExpressionEvaluator/Core/Source/ResultProvider/Helpers/DynamicFlagsMap.cs [hunk 2]
```diff
@@ -190,7 +190,7 @@ private static int[] GetTupleElementNameStartIndices(Type type)
             var typeArgs = type.GetGenericArguments();
             Debug.Assert(typeArgs.Length > 0);
 
-            int pos = GetTupleCardinalityIfAny(type);
+            int pos = type.GetTupleCardinalityIfAny();
             var startsBuilder = ArrayBuilder<int>.GetInstance();
             var tupleElementNameStartIndices = ArrayBuilder<int>.GetInstance();
```
Comment (agocke) [inline src/ExpressionEvaluator/Core/Source/ResultProvider/Helpers/DynamicFlagsMap.cs]: >var tupleElementNameStartIndices = ArrayBuilder<int>.GetInstance(); [](start = 12, length = 67)

This variable doesn't seem to be used and the builder doesn't look to be freed.

**Comment by agocke** [comment]
>     internal sealed class CustomTypeInfoTypeArgumentMap

It looks like the type name here was changed but the file is still named DynamicFlagsMap

---
Refers to: src/ExpressionEvaluator/Core/Source/ResultProvider/Helpers/DynamicFlagsMap.cs:11 in ec87758. [](commit_id = ec8775838340bb9998941eb74fcef5ac6945d729, deletion_comment = False)

File: src/ExpressionEvaluator/Core/Source/ResultProvider/Helpers/TypeHelpers.cs (hunk 1 above)
Comment (jcouv) [inline src/ExpressionEvaluator/Core/Source/ResultProvider/Helpers/TypeHelpers.cs]: There is currently no way to create a 0-tuple. It cannot be specified in source, it is not created internally, and public APIs block it too.

**Comment by jcouv** [comment]
LGTM Thanks

File: src/ExpressionEvaluator/Core/Source/ResultProvider/Helpers/DynamicFlagsMap.cs (hunk 2 above)
Comment (cston) [inline src/ExpressionEvaluator/Core/Source/ResultProvider/Helpers/DynamicFlagsMap.cs]: Good catch. Removed.

**Comment by cston** [comment]
@agocke Renamed files to match class names.

**Comment by agocke** [comment]
LGTM
