### PR TITLE
Fixed error messages around fixed fields

### LINKED ISSUE #26688: C# 7.3 fixed field still requires pinning with implicit `this` reference
**Version Used**:  C# 7.3 / VS 15.7

**Steps to Reproduce**:

In reading through the proposal for relaxing the pinning requirement for fixed fields, I believe the following code should now be valid

```C#
unsafe struct Foo
{
    private fixed int Bar[4];

    public int FirstBar => Bar[0];
}
```

But I still get the "You cannot use fixed size buffers contained in unfixed expressions".  However, if I use an explicit `this` reference I don't get the error

```C#
unsafe struct Foo2
{
    private fixed int Bar[4];

    public int FirstBar => this.Bar[0];
}
```

Is there a reason these would be interpreted differently by the compiler?

### LINKED ISSUE #26743: C# 7.3 allows unmanaged pointer to fixed field without pinning
**Version Used**: C# 7.3 / VS 15.7.1

**Steps to Reproduce**:

Using an explicit `this` pointer to work around #26688, I am able to take the address of a fixed field, giving me an unmanaged pointer without pinning.  If I'm understanding the relaxed restrictions correctly, this should not be possible, as the pointer should only be useable as an indexer.

```C#
unsafe struct Foo
{
	private fixed byte buff1[256];
	private fixed byte buff2[256];

	public void DoUnsafeThing()
	{
		Buffer.MemoryCopy(&this.buff1[0], &this.buff2[0], 256, 256);
	}
}

```

### PR DESCRIPTION
**Pull request by OmarTawfik**
Fixes #26688 
Fixes #26743

### CODE REVIEW

**Comment by OmarTawfik** [comment]
@dotnet-bot test this please

**Comment by OmarTawfik** [comment]
@dotnet-bot test this please

**Comment by OmarTawfik** [comment]
@dotnet-bot test windows_debug_spanish_unit32_prtest please
@dotnet-bot test windows_debug_vs-integration_prtest please
@dotnet-bot test windows_release_vs-integration_prtest please

**Comment by OmarTawfik** [comment]
@dotnet-bot test windows_debug_spanish_unit32_prtest please

**Comment by OmarTawfik** [comment]
@dotnet-bot test windows_debug_vs-integration_prtest please

**Comment by OmarTawfik** [comment]
@dotnet-bot test windows_release_vs-integration_prtest please

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-compiler this is ready for review.

File: docs/compilers/CSharp/Compiler Breaking Changes - post VS2017.md [hunk 1]
```diff
@@ -130,4 +130,7 @@ Example:
...
 - Visual Studio 2017 version 15.8: https://github.com/dotnet/roslyn/issues/26418 C# compiler will now produce errors on out variable declarations that have "ref" or "ref readonly" ref kinds. Example: M(out ref int x);
-- Visual Studio 2017 version 15.8: https://github.com/dotnet/roslyn/issues/27047 The C# compiler will now produce diagnostics for operators marked as obsolete when they are used as part of a tuple comparison.
\ No newline at end of file
+- Visual Studio 2017 version 15.8: https://github.com/dotnet/roslyn/issues/27047 The C# compiler will now produce diagnostics for operators marked as obsolete when they are used as part of a tuple comparison.
+
+- Visual Studio 2017 version 15.8: https://github.com/dotnet/roslyn/issues/26743 C# will now reject expressions such as `public int* M => &this.Bar[0];` if `Bar` is a fixed field of the containing type.
+- Visual Studio 2017 version 15.8: https://github.com/dotnet/roslyn/issues/26688 C# will now accept expressions such as `public int M => Bar[0];` if `Bar` is a fixed field of the containing type.
```
Comment (AlekseyTs) [inline docs/compilers/CSharp/Compiler Breaking Changes - post VS2017.md]: Is this really a breaking change?

File: src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs [hunk 2]
```diff
@@ -2138,6 +2138,7 @@ private BoundExpression BindAddressOfExpression(PrefixUnaryExpressionSyntax node
         // Basically a port of ExpressionBinder::isFixedExpression, which basically implements spec section 18.3.
         // Renamed because there are already too many things called "fixed".
         // NOTE: internal purely for testing purposes.
+        // CONSIDER: why is it used in product code? also, accessedLocalOrParameterOpt is not used anywhere!
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs]: >// CONSIDER: why is it used in product code? also, accessedLocalOrParameterOpt is not used anywhere! [](start = 8, length = 100)

I think the comment above says that it is not private because we want to be able to use it in unit-tests. Form that perspective, it is fine to use use this function in production code.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs]: >also, accessedLocalOrParameterOpt is not used anywhere! [](start = 53, length = 55)

It looks like the NonMoveableVariables_Dereference unit-test demonstrates that the symbol is actually used.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 4)

File: docs/compilers/CSharp/Compiler Breaking Changes - post VS2017.md (hunk 1 above)
Comment (OmarTawfik) [reply docs/compilers/CSharp/Compiler Breaking Changes - post VS2017.md]: Technically no. I'll remove it.

---
In reply to: [194576467](https://github.com/dotnet/roslyn/pull/27424#discussion_r194576467) [](ancestors = 194576467)

File: src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs (hunk 2 above)
Comment (OmarTawfik) [reply src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs]: Thanks for clarifying. Will remove that.

---
In reply to: [194577195](https://github.com/dotnet/roslyn/pull/27424#discussion_r194577195) [](ancestors = 194577195)

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-compiler can I get another review?

**Comment by OmarTawfik** [comment]
@dotnet-bot test this please

**Comment by OmarTawfik** [comment]
@jcouv for merge approval

**Comment by jcouv** [comment]
Approved for merge.

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-infrastructure another infra [failure](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/2008/testReport/junit/Roslyn.VisualStudio.IntegrationTests.CSharp/CSharpReplIdeFeatures/HighlightRefsMultipleSubmisionsVerifyRenameTagsGoAwayWhenInvokedOnUnsubmittedText/):
`System.Runtime.Remoting.RemotingException : Failed to read from an IPC Port: The pipe has been ended.`
