### PR TITLE
Fix suggestions for dotted constant patterns in Color Color case

### LINKED ISSUE #75350: No suggestions in switch expression arm when dotting on an enum type in a `Color Color` case
## Version Used
VS 2022 Version 17.11.4
Roslyn 4.11.0 (5649376e0e5f5db3743a94a62b073f2cce4be5d9)

Project info
C# 12.0
.NET 8.0

## Steps to Reproduce

Paste the following snippet and place the cursor at the position of `$$`:

```csharp
public sealed record OrderModel(int Id, Status Status)
{
    public string StatusDisplay
    {
        get
        {
            return Status switch
            {
                Status.$$
            }
        }
    }
}

public enum Status
{
    Undisclosed,
    Open,
    Closed,
}
```

In [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEDMACAZwFMIAbIgEz2SIGMB7ZKgeSaOQFl6KjSAKWAjwBJCnDwBlBBASoCk6bIIBKALAAoAN4a8uvLn0BGAAwKZcgCJQCAB1IQAnjr3b1e93gDmRBM495Xf38sAHYzJUIAdygEWgALPyDdQKSgqXMCADoAEmzEpIBffL0itxKNUo0DIhhUMHC5DRTdAFUYCmtaUnpiMUTmGxq4RIBhbt7h9QKgA)

In the above example, the auto complete will not show any suggestions. Note that this also works in a regular class, not binding to the primary constructor parameter, and also when the current context is a static method.

## Expected Behavior

I get all the suggestions for the enum field values of `Status` that I can use.

## Actual Behavior

No suggestions appear.

### PR DESCRIPTION
**Pull request by Rekkonnect**
Fixes #75350

After an offline conversation with @CyrusNajmabadi, this PR only addresses the IDE suggestions, without changing the behavior of binding the symbol, or the parsed syntax. We simply reinterpret the non-const symbol as a type and suggest off of the type symbol.

### CODE REVIEW

File: src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs [hunk 1]
```diff
@@ -526,23 +530,46 @@ private RecommendedSymbols GetSymbolsOffOfExpressionInConstantPattern(Expression
...
+                    var reinterpretedBinding = semanticModel.GetSpeculativeSymbolInfo(identifier.SpanStart, identifier, SpeculativeBindingOption.BindAsTypeOrNamespace);
+                    var reinterpretedSymbol = reinterpretedBinding.GetAnySymbol();
+
+                    // The reinterpretation must be a type
+                    if (reinterpretedSymbol is not INamedTypeSymbol reinterprettedNamedType)
+                        return default;
+
+                    var expression = originalExpression.WalkDownParentheses();
+
+                    return GetSymbolsOffOfBoundExpressionWorker(reinterpretedBinding, originalExpression, expression, reinterprettedNamedType, false, false);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs:550]: named parameters for 'false'.
wrap args.

File: src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs [hunk 2]
```diff
@@ -526,23 +530,46 @@ private RecommendedSymbols GetSymbolsOffOfExpressionInConstantPattern(Expression
...
+
+            if (boundSymbol.Symbol is not INamespaceOrTypeSymbol namespaceOrType)
+            {
+                // Likely a Color Color case, so we reinterpret the bound symbol into a type
+                if (originalExpression is IdentifierNameSyntax identifier)
+                {
+                    var reinterpretedBinding = semanticModel.GetSpeculativeSymbolInfo(identifier.SpanStart, identifier, SpeculativeBindingOption.BindAsTypeOrNamespace);
+                    var reinterpretedSymbol = reinterpretedBinding.GetAnySymbol();
+
+                    // The reinterpretation must be a type
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs:544]: because...?

(this comment explains what the code does, but not why).

File: src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs [hunk 3]
```diff
@@ -526,23 +530,46 @@ private RecommendedSymbols GetSymbolsOffOfExpressionInConstantPattern(Expression
...
+            // A constant pattern may only include qualifications to
             // - namespaces (from other namespaces or aliases),
             // - types (from aliases, namespaces or other types),
             // - constant fields (from types)
-            // Methods, properties, events, non-constant fields etc. are excluded since they may not be present in the RHS of an `is` pattern
-            var symbols = namespaceOrType.GetMembers()
-                .WhereAsArray(s => s is INamespaceOrTypeSymbol or IFieldSymbol { IsConst: true } && s.IsAccessibleWithin(containingType));
-            return new RecommendedSymbols(symbols);
+            // Methods, properties, events, non-constant fields etc. are excluded since they are not constant expressions
+            bool FilterMember(ISymbol symbol)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs:568]: used in one location? just inline?

File: src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs [hunk 4]
```diff
@@ -526,23 +530,46 @@ private RecommendedSymbols GetSymbolsOffOfExpressionInConstantPattern(Expression
...
+            {
+                return symbol is INamespaceOrTypeSymbol or IFieldSymbol { IsConst: true }
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs:570]: what about a constant local?  can you add  a test for that?

**Comment by CyrusNajmabadi** [comment]
Done with pass.  looking good.

File: src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs (hunk 2 above)
Comment (Rekkonnect) [reply src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs:544]: This was an oversight. We also want to allow other kinds of symbols like aliases, namespaces and types. Will update, including a reason.

File: src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs (hunk 4 above)
Comment (Rekkonnect) [reply src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs:570]: Local symbols are not contained within a type or namespace, so we will never encounter those through the filtering. However, we should have tests to make sure they are not overlooked at.

Comment (Rekkonnect) [reply src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs]: Added tests showing the behavior in locals

File: src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs (hunk 3 above)
Comment (Rekkonnect) [reply src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs]: Done

File: src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs (hunk 2 above)
Comment (Rekkonnect) [reply src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs]: Done, ptal

File: src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs (hunk 1 above)
Comment (Rekkonnect) [reply src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationServiceRunner.cs]: Done

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks!
