### PR TITLE
Fix parsing regression on switch case expression that is parenthesized unary expression

### LINKED ISSUE #32161: Parenthesized switch case expressions rejected in master with langver 7
The following C# code is reportedly rejected in `master` with language version 7. This is a breaking change.

``` c#
switch (notesColumn)
{
    case (-1):
        {
            // not found, do nothing;
            break;
        }
    case (0):
        {
            // root column, add to Items
            item.Text = justification.Text;
            break;
        }
    default:
        {
            // add to sub items
            item.SubItems[notesColumn].Text = justification.Text;
            break;
        }
}
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #32161

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs [hunk 1]
```diff
@@ -625,7 +625,7 @@ private bool IsPossibleSubpatternElement()
             bool isExpression = this.IsPossibleExpression() &&
                     // IsPossibleExpression returns true when the next token is a binary operator.
                     // That is useful for error recovery elsewhere, but not here.
-                    !(SyntaxFacts.IsBinaryExpression(tk) || SyntaxFacts.IsAssignmentExpressionOperatorToken(tk));
+                    !(SyntaxFacts.IsBinaryExpression(tk) && !SyntaxFacts.IsPrefixUnaryExpression(tk) || SyntaxFacts.IsAssignmentExpressionOperatorToken(tk));
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs]: fwiw, this expression has now reached the point of not being comprehensible to me in this compact form.

Comment (jcouv) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs]: Same for me

File: src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs [hunk 2]
```diff
@@ -6122,5 +6122,136 @@ public void NestedShortTuplePatterns()
...
+{
+    case (0): break;
+    case (-1): break;
+    case (+2): break;
+    case (~3): break;
+}
+";
+            foreach (var langVersion in new[] { LanguageVersion.CSharp6, LanguageVersion.CSharp7, LanguageVersion.CSharp8 })
+            {
+                UsingStatement(text, options: CSharpParseOptions.Default.WithLanguageVersion(langVersion));
```
[the remark this answers is not in the document]
Comment (gafter) [reply src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs]: Yes, it does.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs]: Turns out this whole expression can be replaced by a call to a recently introduced helper (actually, the same `IsPossibleExpression` helper with new parameters).

File: src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs [hunk 3]
```diff
@@ -6122,5 +6122,136 @@ public void NestedShortTuplePatterns()
...
+        {
+            var text = @"
+switch (e)
+{
+    case (0): break;
+    case (-1): break;
+    case (+2): break;
+    case (~3): break;
+}
+";
```
Comment (cston) [inline src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs]: Are there other interesting cases? Perhaps:
```
    case (^1): break;
    case ((-1)): break;
```

Comment (gafter) [reply src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs]: I don't think those cases are different in any way that is relevant to the bug or its fix.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs [hunk 4]
```diff
@@ -621,12 +621,8 @@ private SubpatternSyntax ParseSubpatternElement()
...
         private bool IsPossibleSubpatternElement()
         {
-            var tk = this.CurrentToken.Kind;
-            bool isExpression = this.IsPossibleExpression() &&
-                    // IsPossibleExpression returns true when the next token is a binary operator.
-                    // That is useful for error recovery elsewhere, but not here.
-                    !(SyntaxFacts.IsBinaryExpression(tk) || SyntaxFacts.IsAssignmentExpressionOperatorToken(tk));
-            return isExpression || this.CurrentToken.Kind == SyntaxKind.OpenBraceToken;
+            return this.IsPossibleExpression(allowBinaryExpressions: false, allowAssignmentExpressions: false) ||
+                this.CurrentToken.Kind == SyntaxKind.OpenBraceToken;
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs]: Thanks!  Note: i would personally find it valuable if there was an explanation here (even if brief) as to why neither of these expression forms are allowed.  i.e. what hte intuition here is for why this is correct.

Comment (gafter) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs]: These parameters are about whether binary operator tokens should be accepted.  We don't want a token such as `==` to be considered to be permitted in this context.
