### PR TITLE
Fix F1 keywords clashing for !_CSharpKeyword

### LINKED ISSUE #46988: Issue with `!_CSharpKeyword`
Both the not operator and null-forgiving operator have the same F1 help keyword. That causes the dotnet/docs repository to have the exact same f1 keyword in two articles. And unfortunately, pressing F1 in any `!` always redirects to the null-forgiving article. I think Roslyn should provide different f1 keywords so dotnet/docs can be updated to have different f1 keywords too.

cc: @BillWagner @gewarren

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #46988

@davidwengier Can you review? Also, we should get the docs PR (dotnet/docs#20341) merged first right?

### CODE REVIEW

File: src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs [hunk 1]
```diff
@@ -206,6 +206,13 @@ private bool TryGetTextForSymbol(SyntaxToken token, SemanticModel semanticModel,
 
         private static bool TryGetTextForOperator(SyntaxToken token, Document document, out string text)
         {
+            if (token.IsKind(SyntaxKind.ExclamationToken) && token.Parent is not null)
+            {
+                text = token.Parent.IsKind(SyntaxKind.LogicalNotExpression)
+                    ? Keyword("!")
+                    : Keyword("nullForgiving");
```
Comment (davidwengier) [inline src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:213]: This feels a little like redoing some of the logic the parser is doing for us already, and will fall down if exclamation points are used for something else in future. For example there is a proposal for argument validation that would use it.

To me it makes more sense to simply check if the parent is `SuppressNullableWarningExpression` and return `Keyword("nullForgiving")` for that, and let the rest of the code flow as it did before.

Comment (Youssef1313) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs]: @davidwengier I did that in the latest commit but just realized a problem with that approach.
For null forgiving operator, SuppressNullableWarningExpression won't always be the parent.
The parent could be MemberAccessExpression whose parent is SuppressNullableWarningExpression.
So, that will need traversing the tree up to make sure it'll work correctly.

Does it worth doing so?

Comment (Youssef1313) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs]: By the way, I believe there are many other cases that aren't handled correctly. For example, the colon in inheritance vs ternary operator.

Do you see a way to refactor the whole thing instead of keeping special-casing more things? probably make it based on semantics instead of syntax?

Comment (davidwengier) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs]: > The parent could be MemberAccessExpression whose parent is SuppressNullableWarningExpression.

What scenario would have this?

**Review by davidwengier — APPROVED** [review]

File: src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs (hunk 1 above)
Comment (Youssef1313) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs]: I looked again in SharpLab and it was just my eyes *incorrectly* seeing sibling nodes as parent/children :smile: . So this approach should just work.

**Review by allisonchou — APPROVED** [review]

File: src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs [hunk 2]
```diff
@@ -206,6 +206,12 @@ private bool TryGetTextForSymbol(SyntaxToken token, SemanticModel semanticModel,
 
         private static bool TryGetTextForOperator(SyntaxToken token, Document document, out string text)
         {
+            if (token.IsKind(SyntaxKind.ExclamationToken) && token.Parent is not null &&
+                token.Parent.IsKind(SyntaxKind.SuppressNullableWarningExpression))
+            {
+                text = Keyword("nullForgiving");
+                return true;
+            }
```
Comment (allisonchou) [inline src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:214]: nit:
```suggestion
            }
            
```

File: src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs [hunk 3]
```diff
@@ -206,6 +206,13 @@ private bool TryGetTextForSymbol(SyntaxToken token, SemanticModel semanticModel,
 
         private static bool TryGetTextForOperator(SyntaxToken token, Document document, out string text)
         {
+            if (token.IsKind(SyntaxKind.ExclamationToken) && token.Parent is not null &&
```
Comment (sharwell) [inline src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:209]: The null check is not necessary because `IsKind` already checks for null.

```suggestion
            if (token.IsKind(SyntaxKind.ExclamationToken) &&
```

**Review by sharwell — APPROVED** [review]

**Review by CyrusNajmabadi — APPROVED** [review]
lgtm with the suggestion sam made.

**Review by sharwell — APPROVED** [review]

**Comment by Youssef1313** [comment]
@sharwell @davidwengier Can you re-run the integration tests please?

**Comment by davidwengier** [comment]
I've restarted the leg than hung, and will monitor if it passes (and then if GitHub can be convinced that it has)
