### PR TITLE
Fixed IntelliSense completion for initializing a generic class member when a class member has the same name as generic type argument

### LINKED ISSUE #2644: IntelliSense incorrectly attempts to disambiguate generic arguments when they clash with a member
Given the following:

``` C#
using System.Collections.ObjectModel;

namespace ConsoleApplication34
{
    class Program
    {
        public static ReadOnlyCollection<Bar> Bar
        {
            get;
        }

        static void Main(string[] args)
        {
            Bar = new 
        }
    }

    class Bar
    {
    }
}
```

IntelliSense incorrectly attempts to disambiguate the `Bar` type in the `ReadOnlyCollection<ConsoleApplication34.Bar>` suggestion. It appears to do this because it thinks there is a clash with the `Bar` property.

image

After this, you are immediately asked to simplify the expression:

image

### LINKED ISSUE #21674: Intellisense suggests fully-qualified type name when property has same name as other type
Intellisense should suggest `A` at `$$` below rather than `ConsoleApplication1.A`.
```
namespace ConsoleApplication1
{
    class Program
    {
        static A B { get; set; }
        static B A { get; set; }

        static void Main()
        {
            B = new $$
        }
    }
    class A { }
    class B { }
}
```

### PR DESCRIPTION
**Pull request by zaytsev-victor**
**Customer scenario**
IntelliSense incorrectly attempts to disambiguate generic arguments when they clash with a member

**Bugs this fixes:**
Fixes #2644
Fixes #21674

**Workarounds, if any**
None

**Risk**
Low

**Is this a regression from a previous update?**
No

**How was the bug found?**
customer reported

### CODE REVIEW

File: src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs [hunk 1]
```diff
@@ -47,11 +48,21 @@ protected bool NameBoundSuccessfullyToSameSymbol(INamedTypeSymbol symbol)
             var type1 = GetSymbolType(normalSymbol);
             var type2 = GetSymbolType(typeOnlySymbol);
 
-            return
+            return (
                 type1 != null &&
                 type2 != null &&
                 type1.Equals(type2) &&
-                typeOnlySymbol.Equals(symbol.OriginalDefinition);
+                typeOnlySymbol.Equals(symbol.OriginalDefinition)) || IsGenericTypeArgument(type1, symbol);
```
Comment (cston) [inline src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs]: It's not clear why we compare `typeOnlySymbol` with the type of the symbol from `LookupSymbols` or against it's type arguments. That wouldn't handle cases where the type returned from `LookupNamespacesAndTypes` is not part of the type of the symbol from `LookupSymbols`. For instance:
```
namespace ConsoleApplication1
{
    class Program
    {
        static C<A> B { get; set; }
        static C<B> A { get; set; }

        static void Main(string[] args)
        {
            B = new $$
        }
    }
    class A { }
    class B { }
    class C<T> { }
}
```
Would we get the expected result with `return typeOnlySymbol.Equals(symbol.OriginalDefinition);`?

File: src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor_Minimal.cs [hunk 2]
```diff
@@ -159,6 +159,20 @@ private void MinimallyQualify(INamedTypeSymbol symbol)
             AddNameAndTypeArgumentsOrParameters(symbol);
         }
 
+        protected bool InObjectInitializatioContext(INamedTypeSymbol symbol)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor_Minimal.cs]: Is the check for `SyntaxKind.NewKeyword` necessary? If not, then could the issue be fixed by simplifying `NameBoundSuccessfullyToSameSymbol`, rather than introducing a new method here, since `NameBoundSuccessfullyToSameSymbol` is already calling `LookupNamespacesAndTypes`:
```
        protected bool NameBoundSuccessfullyToSameSymbol(INamedTypeSymbol symbol)
        {
            if (!ShouldRestrictMinimallyQualifyLookupToNamespacesAndTypes())
            {
                ImmutableArray<ISymbol> normalSymbols = semanticModelOpt.LookupSymbols(positionOpt, name: symbol.Name);
                ISymbol normalSymbol = SingleSymbolWithArity(normalSymbols, symbol.Arity);

                if (normalSymbol == null)
                {
                    return false;
                }

                // Binding normally ended up with the right symbol.  We can definitely use the
                // simplified name.
                if (normalSymbol.Equals(symbol.OriginalDefinition))
                {
                    return true;
                }
            }

            // Binding normally failed.  We may be in a "Color Color" situation where 'Color'
            // will bind to the field, but we could still allow simplification here.
            ImmutableArray<ISymbol> typeOnlySymbols = semanticModelOpt.LookupNamespacesAndTypes(positionOpt, name: symbol.Name);
            ISymbol typeOnlySymbol = SingleSymbolWithArity(typeOnlySymbols, symbol.Arity);

            if (typeOnlySymbol == null)
            {
                return false;
            }

            return typeOnlySymbol.Equals(symbol.OriginalDefinition);
        }
```

Comment (zaytsev-victor) [inline src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor_Minimal.cs]: @cston, sorry for late response, we can't simplify ```NameBoundSuccessfullyToSameSymbol```, because the test ```SemanticQuickInfoSourceTests.ColorColorRangeVariable``` will fail.

Comment (cston) [inline src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor_Minimal.cs]: @CyrusNajmabadi, by simplifying `NameBoundSuccessfullyToSameSymbol`, the test `SemanticQuickInfoSourceTests.ColorColorRangeVariable` fails since the QuickInfo for the range variable is `yield yield` rather than `N1.yield yield`. The former looks correct to me and is consistent with the QuickInfo for the range variable in other parts of the query. Do we need the namespace qualifier in this case?

File: src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor_Minimal.cs [hunk 3]
```diff
@@ -120,7 +120,7 @@ private void MinimallyQualify(INamedTypeSymbol symbol)
 
             if (!(symbol.IsAnonymousType || symbol.IsTupleType))
             {
-                if (!NameBoundSuccessfullyToSameSymbol(symbol))
+                if (!(NameBoundSuccessfullyToSameSymbol(symbol) || InObjectInitializatioContext(symbol)))
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor_Minimal.cs]: Name is missing an 'n'.

File: src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor_Minimal.cs (hunk 2 above)
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor_Minimal.cs]: I'm absolutely fine with this behavior changing.  "yield yield" is totally ok.  This scenario is completely irrelevant :)

File: src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs [hunk 4]
```diff
@@ -3268,31 +3268,6 @@ static void M(string[] args)
...
-            foreach (yield yield in from yield in new yield[0]
-                                    select y$$ield)
-            {
-                yield return yield;
-            }
-        }
-    }
-}",
-                MainDescription($"({FeaturesResources.range_variable}) N1.yield yield"));
-        }
```
Comment (cston) [inline src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs]: Please keep this test, updating the expected result to `yield yield`.

File: src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs [hunk 5]
```diff
@@ -39,19 +37,7 @@ protected bool NameBoundSuccessfullyToSameSymbol(INamedTypeSymbol symbol)
             ImmutableArray<ISymbol> typeOnlySymbols = semanticModelOpt.LookupNamespacesAndTypes(positionOpt, name: symbol.Name);
             ISymbol typeOnlySymbol = SingleSymbolWithArity(typeOnlySymbols, symbol.Arity);
 
-            if (typeOnlySymbol == null)
-            {
-                return false;
-            }
-
-            var type1 = GetSymbolType(normalSymbol);
-            var type2 = GetSymbolType(typeOnlySymbol);
```
Comment (cston) [inline src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs]: Please remove the `GetSymbolType` method as well.

**Comment by cston** [comment]
@dotnet/roslyn-compiler please review the compiler changes.

File: src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs [hunk 6]
```diff
@@ -39,19 +37,7 @@ protected bool NameBoundSuccessfullyToSameSymbol(INamedTypeSymbol symbol)
...
-
-            return
-                type1 != null &&
-                type2 != null &&
-                type1.Equals(type2) &&
-                typeOnlySymbol.Equals(symbol.OriginalDefinition);
+            return typeOnlySymbol == null ? false : typeOnlySymbol.Equals(symbol.OriginalDefinition);
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs]: >return typeOnlySymbol == null ? false : typeOnlySymbol.Equals(symbol.OriginalDefinition); [](start = 12, length = 89)

Given this change, we are no longer targeting the "Color Color" case as the comment above implies. At the very least the comment should be adjusted to explain why this logic is sound. To me, it looks like this new logic is valid only if we know that we are in a type-only context, which we cannot be sure of, given the limited information this function has. It feels like we should do more testing and verify that we are not breaking behavior in a non-type-only context.

**Comment by AlekseyTs** [comment]
It looks like the change affects VB too, please add similar tests for VB.

File: src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs (hunk 6 above)
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs]: return typeOnlySymbol != null && typeOnlySymbol.Equals...

**Comment by AlekseyTs** [comment]
Done with review pass.

File: src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs (hunk 6 above)
Comment (cston) [inline src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs]: @AlekseyTs and I debugged through a couple of cases. He is correct that this change, that I suggested, breaks existing cases, although we don't have any tests that fail currently. We should add a test, perhaps adding the following to SemanticInfoQuickInfoSourceTests.cs.
```
        [Fact, Trait(Traits.Feature, Traits.Features.QuickInfo)]
        public async Task PropertyWithSameNameAsOtherType()
        {
            await TestAsync(
@"namespace ConsoleApplication1
{
    class Program
    {
        static A B { get; set; }
        static B A { get; set; }

        static void Main(string[] args)
        {
            B = ConsoleApplication1.B$$.F();
        }
    }
    class A { }
    class B
    {
        public static A F() => null;
    }
}",
                MainDescription($"ConsoleApplication1.A ConsoleApplication1.B.F()"));
        }
```
We suspect that to fix the original issue, #2644, this method should be changed to always lookup symbols in a type-only context when looking up symbols for type arguments. If `AbstractSymbolDisplayVisitor` tracks when it visits type arguments, perhaps as a field on the visitor, then the first line in this method becomes `var normalSymbols = _inTypeArguments || ShouldRestrictMinimallyQualifyLookupToNamespacesAndTypes() ? ... : ...;` and the rest of the method could be reverted. (Thanks @AlekseyTs.)

Comment (cston) [inline src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs]: We discovered a similar issue with object creation but with simple types rather than type arguments: #21674.

Comment (cston) [inline src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs]: #21674 is a distinct issue that can be fixed separately.

File: src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs [hunk 7]
```diff
@@ -123,5 +86,40 @@ protected static ITypeSymbol GetSymbolType(ISymbol symbol)
...
+                    else
+                    {
+                        singleSymbol = null;
+                        break;
+                    }
+                }
+            }
+            return singleSymbol;
+        }
     }
```
Comment (cston) [inline src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs]: Can this file be reverted and removed from the PR at this point?

File: src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs [hunk 8]
```diff
@@ -4992,5 +4992,31 @@ static void Main(string[] args)
 }",
                 MainDescription($"({FeaturesResources.local_variable}) ref int i"));
         }
+
+        [WorkItem(2644, "https://github.com/dotnet/roslyn/issues/2644")]
+        [Fact, Trait(Traits.Feature, Traits.Features.QuickInfo)]
+        public async Task PropertyWithSameNameAsOtherType()
```
Comment (AlekseyTs) [inline src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs]: >PropertyWithSameNameAsOtherType [](start = 26, length = 31)

Please add similar test for VB.

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ObjectCreationCompletionProviderTests.cs [hunk 9]
```diff
@@ -501,5 +501,95 @@ static void Main(string[] args)
 ";
             await VerifyItemExistsAsync(markup, "TimeSpan");
         }
+
+        [WorkItem(2644, "https://github.com/dotnet/roslyn/issues/2644")]
+        [Fact, Trait(Traits.Feature, Traits.Features.Completion)]
+        public async Task InPropertyWithSameNameAsGenericTypeArgument1()
```
Comment (AlekseyTs) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ObjectCreationCompletionProviderTests.cs]: >InPropertyWithSameNameAsGenericTypeArgument1 [](start = 26, length = 44)

Please add similar test for VB.

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ObjectCreationCompletionProviderTests.cs [hunk 10]
```diff
@@ -501,5 +501,95 @@ static void Main(string[] args)
...
+    {
+    }
+}
+";
+            await VerifyItemExistsAsync(markup, "List<Bar>");
+        }
+
+        [WorkItem(2644, "https://github.com/dotnet/roslyn/issues/2644")]
+        [Fact, Trait(Traits.Feature, Traits.Features.Completion)]
+        public async Task InPropertyWithSameNameAsGenericTypeArgument4()
```
Comment (AlekseyTs) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ObjectCreationCompletionProviderTests.cs]: >InPropertyWithSameNameAsGenericTypeArgument4 [](start = 26, length = 44)

Please add similar test for VB.

File: src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs [hunk 11]
```diff
@@ -54,41 +52,6 @@ protected bool NameBoundSuccessfullyToSameSymbol(INamedTypeSymbol symbol)
...
-                    {
-                        singleSymbol = null;
-                        break;
-                    }
-                }
-            }
-            return singleSymbol;
-        }
-
         protected static ITypeSymbol GetSymbolType(ISymbol symbol)
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs]: >protected static ITypeSymbol GetSymbolType(ISymbol symbol) [](start = 8, length = 58)

Please revert this file to its original state.

File: src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor_Minimal.cs [hunk 12]
```diff
@@ -47,7 +47,7 @@ protected override bool ShouldRestrictMinimallyQualifyLookupToNamespacesAndTypes
             var token = semanticModelOpt.SyntaxTree.GetRoot().FindToken(positionOpt);
             var startNode = token.Parent;
 
-            return SyntaxFacts.IsInNamespaceOrTypeContext(startNode as ExpressionSyntax);
+            return SyntaxFacts.IsInNamespaceOrTypeContext(startNode as ExpressionSyntax) || token.IsKind(SyntaxKind.NewKeyword);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor_Minimal.cs]: >|| token.IsKind(SyntaxKind.NewKeyword [](start = 89, length = 37)

I do not think this fix covers other scenarios where type arguments are involved. For example here is a clone of scenario from PropertyWithSameNameAsOtherType QuickInfo test :
```
namespace ConsoleApplication1
{
    class Program
    {
        public static List<Bar> Bar { get; set; }

        static void Main(string[] args)
        {
            Test<Bar>();
        }

        static void Test<T>() { }
    }

    class Bar
    {
    }
}
```

Hover over ```Test``` in ```Test<Bar>();```, it shows ```void Program.Test<ConsoleApplication1.Bar>()```. I would expect it to show ```void Program.Test<Bar>()```.

**Comment by AlekseyTs** [comment]
Done with review pass.

File: src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs (hunk 6 above)
Comment (zaytsev-victor) [reply src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs]: @cston Why do we need namespace for return value here? It looks like a bug, isn't it?
It make sense in this case:
```csharp
using C1;
using C2;

namespace ConsoleApplication1
{
    class Program
    {
        static C2.A B { get; set; }
        static B A { get; set; }
        static C C { get; set; }

        static void Main(string[] args)
        {
            var a = new C1.A();
            B = C2.B$$.F();
        }
    }   
}

namespace C1
{
    public class A { }

    public class C { }
}

namespace C2
{
    public class A { }

    class B
    {
        public static A F() => null;
    }
}
```

Comment (cston) [reply src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs]: @zaytsev-victor, yes, it looks like the namespace qualifier is unnecessary for the return type in the `PropertyWithSameNameAsOtherType` test above.

Comment (zaytsev-victor) [reply src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs]: @cston Could you please explain what is "Color Color" case?) Because I'm starting to think that simplifying of ```NameBoundSuccessfullyToSameSymbol``` function was the correct fix.

Comment (cston) [reply src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs]: The "Color Color" case is the where the member name and the member type name are identical: see [C# spec](https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#identical-simple-names-and-type-names). Unfortunately simplifying `NameBoundSuccessfullyToSameSymbol` will also simplify cases where the member name matches the type name of a different member which is not correct: see `PropertyWithSameNameAsOtherType` test above.

Comment (zaytsev-victor) [reply src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs]: @cston but you are agree that the namespace qualifier is unnecessary for the return type in the ```PropertyWithSameNameAsOtherType``` test. If we really want (for some reason) the namespace qualifier in quick info in these cases it is better to create new format option for quick info, isn't it? Because the namespace qualifier isn't required in code.

Comment (cston) [reply src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor_Minimal.cs]: I think it's reasonable to have the namespace qualifier on both the return type and member if the namespace is required for one of the two.

**Comment by zaytsev-victor** [comment]
@rchande, it is not good actually ;) I don't understand in which cases we should add namespace (as I understand only in quick info). But I think that parameter should be added (may be to format options) that would indicate that we need display string for quick info, since it requires additional logic. All other variants look pretty 'buggy'

**Comment by AlekseyTs** [comment]
@zaytsev-victor I think the problem with type arguments can be fixed by visiting them in a special mode. When we are visiting them, we are always in namespace or type context, regardless of what position is given in source. Therefore, it would be appropriate for  ShouldRestrictMinimallyQualifyLookupToNamespacesAndTypes to return true for type arguments. One possible way to achieve that would be to use a special flavor of NotFirstVisitor, let's call it NotFirstVisitorNamespaceOrType when we are visiting type arguments.

File: src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor.cs [hunk 13]
```diff
@@ -12,18 +12,21 @@ internal abstract partial class AbstractSymbolDisplayVisitor : SymbolVisitor
         protected readonly ArrayBuilder<SymbolDisplayPart> builder;
         protected readonly SymbolDisplayFormat format;
         protected readonly bool isFirstSymbolVisited;
+        protected readonly bool inTypeArguments;
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor.cs]: >inTypeArguments [](start = 32, length = 15)

"inNamespaceOrType" ?

Comment (AlekseyTs) [reply src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor.cs]: Please rename the field and parameters

**Comment by AlekseyTs** [comment]
The PR claims to fix https://github.com/dotnet/roslyn/issues/21674, but I didn't see a unit-test that backs this claim. Please add a unit-test for both languages.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 7).

File: src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor.cs (hunk 13 above)
Comment (zaytsev-victor) [reply src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor.cs]: @AlekseyTs the field indicates if it is in type argument context. I think it is more relevant name.

Comment (AlekseyTs) [reply src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor.cs]: It doesn't have to be that specific, I can imagine using this kind of visitor in other contexts in the future. For example, when we are formatting parameter types withing method signature, etc.

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ObjectCreationCompletionProviderTests.cs [hunk 14]
```diff
@@ -501,5 +501,119 @@ static void Main(string[] args)
...
+    }
+    class A { }
+    class B { }
+    class C<T> { }
+}
+";
+            await VerifyItemExistsAsync(markup, "C<A>");
+        }
+
+        [WorkItem(2644, "https://github.com/dotnet/roslyn/issues/2644")]
```
Comment (AlekseyTs) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ObjectCreationCompletionProviderTests.cs]: >2644 [](start = 18, length = 4)

Should this refer to 21674 instead?

File: src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/ObjectCreationCompletionProviderTests.vb [hunk 15]
```diff
@@ -99,5 +99,98 @@ End Namespace
...
+    Class C(Of T)
+    End Class
+End Namespace
+]]></Text>.Value
+
+            Await VerifyItemExistsAsync(markup, "C(Of B)")
+        End Function
+
+        <Fact, Trait(Traits.Feature, Traits.Features.Completion)>
+        <WorkItem(2644, "https://github.com/dotnet/roslyn/issues/2644")>
```
Comment (AlekseyTs) [inline src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/ObjectCreationCompletionProviderTests.vb]: >2644 [](start = 18, length = 4)

Should this refer to 21674 instead?

**Comment by AlekseyTs** [comment]
@cston Please review latest revision of the fix.

File: src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor.cs [hunk 16]
```diff
@@ -54,7 +58,21 @@ protected AbstractSymbolDisplayVisitor NotFirstVisitor
...
+                {
+                    _lazyNotFirstVisitorNamespaceOrType = MakeNotFirstVisitorNamespaceOrType();
+                }
+
+                return _lazyNotFirstVisitorNamespaceOrType;
+            }
+        }
+
         protected abstract AbstractSymbolDisplayVisitor MakeNotFirstVisitor();
+        protected abstract AbstractSymbolDisplayVisitor MakeNotFirstVisitorNamespaceOrType();
```
Comment (cston) [inline src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor.cs]: Let's just add a `bool inNamespaceOrType` parameter to `MakeNotFirstVisitor`.

File: src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/ObjectCreationCompletionProviderTests.vb [hunk 17]
```diff
@@ -99,5 +99,98 @@ End Namespace
 
             Await VerifyItemExistsAsync(markup, "N.S")
         End Function
+
+        <Fact, Trait(Traits.Feature, Traits.Features.Completion)>
+        <WorkItem(2644, "https://github.com/dotnet/roslyn/issues/2644")>
+        Public Async Function InPropertyWithSameNameAsGenericTypeArgument1() As Task
+            Dim markup = <Text><![CDATA[
+Imports System.Collections.Generic
+Namespace Foo
```
Comment (cston) [inline src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/ObjectCreationCompletionProviderTests.vb]: Please rename namespace. Perhaps `Namespace1`.

File: src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.cs [hunk 18]
```diff
@@ -47,20 +47,7 @@ protected override AbstractSymbolDisplayVisitor MakeNotFirstVisitor()
...
-            return new SymbolDisplayVisitor(
-                this.builder,
-                this.format,
-                this.semanticModelOpt,
-                this.positionOpt,
-                _escapeKeywordIdentifiers,
-                _lazyAliasMap,
-                isFirstSymbolVisited: false,
-                inNamespaceOrType: true);
+                isFirstSymbolVisited: inNamespaceOrType);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.cs]:
```
isFirstSymbolVisited: false,
inNamespaceOrType: inNamespaceOrType);
```

**Comment by cston** [comment]
@dotnet-bot test windows_debug_unit32_prtest please

**Comment by cston** [comment]
@AlekseyTs, are the integration test failures known issues?

**Comment by AlekseyTs** [comment]
@rchande Were all your comments addressed?

**Comment by AlekseyTs** [comment]
CC @jaredpar For approval

**Comment by jaredpar** [comment]
Approved

**Comment by AlekseyTs** [comment]
@rchande Ping. Are all your comments addressed?

File: src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs [hunk 19]
```diff
@@ -3268,8 +3268,8 @@ static void M(string[] args)
                 MainDescription("string[]"));
         }
 
-        [WorkItem(529139, "http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/529139")]
-        [Fact, Trait(Traits.Feature, Traits.Features.QuickInfo)]
+        [WorkItem(529139, "http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/529139")]
```
Comment (rchande) [inline src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs]: Extra spaces?

File: src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs [hunk 20]
```diff
@@ -3289,8 +3289,8 @@ public static IEnumerable<yield> Bar()
             }
         }
     }
-}",
-                MainDescription($"({FeaturesResources.range_variable}) N1.yield yield"));
+ }",
```
Comment (rchande) [inline src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs]: What happened here?

**Comment by sharwell** [comment]
@zaytsev-victor This is ready once the merge conflict is fixed and tests pass. Please let me know if you would like me to fix the conflict for you so it can be merged. :smile:

**Comment by sharwell** [comment]
@rchande I believe your requests have now been addressed, aside from the conflict which I'm looking into.
