### PR TITLE
IBinaryOperatorExpression, IUnaryOperatorExpression and IIncrementExp…

### LINKED ISSUE #8848: IOperation: VB - BoundUserDefinedBinaryOperator implementation of IBinaryOperatorExpression.BinaryOperationKind doesn't handle some operators
It looks like BinaryOperatorKind.Power is not handled and will cause UnexpectedValue exception.
I didn't confirm that all other operators are handled properly.

### PR DESCRIPTION
**Pull request by mavasani**
…ression API changes

This implements a bunch of changes to the IOperation representation for binary operator, unary operator and increment expressions.

1. #8834: Simplify `UnaryOperatorKind` to only contain the operator kind values instead of a matrix of operator and operand kinds.
2. #8835: Simplify `BinaryOperatorKind` in similar manner as above.
3. #8825: Add `IUnaryOperatorExpression.IsChecked` flag. Cyrus has already added the `IUnaryOperatorExpression.IsLifted` flag.
4. #8846: Add `IBinaryOperatorExpression.IsChecked` and `IBinaryOperatorExpression.IsCompareText` flags Cyrus has already added the `IBinaryOperatorExpression.IsLifted` flag.
5. #21283: Add `IIncrementExpression.IsDecrement` and `IIncrementExpression.IsPostfix` flags and remove PostFix/Prefix Increment/Decrement from `UnaryOperatorKind` enum.

This change also fixes #8848 and #8843 as the matrix operation kind enums no longer exist.

### CODE REVIEW

File: src/Test/Utilities/Portable/Compilation/OperationTreeVerifier.cs [hunk 1]
```diff
@@ -792,15 +795,23 @@ public override void VisitBinaryOperatorExpression(IBinaryOperatorExpression ope
         {
             LogString(nameof(IBinaryOperatorExpression));
 
-            var kindStr = $"{nameof(BinaryOperationKind)}.{operation.BinaryOperationKind}";
+            var kindStr = $"{nameof(BinaryOperatorKind)}.{operation.OperatorKind}";
             if (operation.IsLifted)
             {
-                LogString($" ({kindStr}-IsLifted)");
+                kindStr += "-IsLifted";
```
Comment (333fred) [inline src/Test/Utilities/Portable/Compilation/OperationTreeVerifier.cs]: To be more consistent with other IOperation tests, we should probably have these as separate fields, with true/false explicitly listed.

**Review by 333fred — COMMENTED** [review]
API changes look to to me.

File: src/Compilers/Core/Portable/Operations/IBinaryOperatorExpression.cs [hunk 2]
```diff
@@ -32,5 +32,13 @@ public interface IBinaryOperatorExpression : IHasOperatorMethodExpression
         /// value types.
         /// </summary>
         bool IsLifted { get; }
+        /// <summary>
+        /// <code>true</code> if this is a 'checked' binary operator.
+        /// </summary>
+        bool IsChecked { get; }
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/Operations/IBinaryOperatorExpression.cs]: I feel like IsChecked should be something that may just be pulled up to IOperation.

File: src/Compilers/Core/Portable/Operations/IBinaryOperatorExpression.cs [hunk 3]
```diff
@@ -32,5 +32,13 @@ public interface IBinaryOperatorExpression : IHasOperatorMethodExpression
...
+        /// <summary>
+        /// <code>true</code> if the comparison is text based for string or object comparison in VB.
+        /// </summary>
+        bool IsCompareText { get; }
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/Operations/IBinaryOperatorExpression.cs]: Do we need this?

**Review by CyrusNajmabadi — APPROVED** [review]
That was way simpler than i expected.

File: src/Compilers/Core/Portable/Operations/IBinaryOperatorExpression.cs (hunk 2 above)
Comment (333fred) [inline src/Compilers/Core/Portable/Operations/IBinaryOperatorExpression.cs]: What about things where IsChecked doesn't make sense, like all statements? The Type property at least has a way to show that Type isn't relevant for the operation, by returning null. Seems like we wouldn't be able to distinguish between "This isn't a checked expression" and "IsChecked has no meaning here" easily.

File: src/Compilers/Core/Portable/Operations/IBinaryOperatorExpression.cs (hunk 3 above)
Comment (mavasani) [inline src/Compilers/Core/Portable/Operations/IBinaryOperatorExpression.cs]: Yes, @AlekseyTs explicitly requested this in https://github.com/dotnet/roslyn/issues/8846

File: src/Compilers/Core/Portable/Operations/IBinaryOperatorExpression.cs (hunk 2 above)
Comment (mavasani) [inline src/Compilers/Core/Portable/Operations/IBinaryOperatorExpression.cs]: I agree with Fred, this seems specific to expressions, and if we had an IExpression, it would logically move there, but it doesn't make sense for rest of operations (statements, query clauses, patterns, etc.)

File: src/Test/Utilities/Portable/Compilation/OperationTreeVerifier.cs (hunk 1 above)
Comment (mavasani) [inline src/Test/Utilities/Portable/Compilation/OperationTreeVerifier.cs]: Sure, I will change the format to match other bool fields on IOperation

**Comment by nguerrera** [comment]
Also fixes #8395 (I hit this in IL to operation).

File: src/Compilers/Core/Portable/Operations/IBinaryOperatorExpression.cs [hunk 4]
```diff
@@ -32,5 +32,13 @@ public interface IBinaryOperatorExpression : IHasOperatorMethodExpression
         /// value types.
         /// </summary>
         bool IsLifted { get; }
+        /// <summary>
+        /// <code>true</code> if this is a 'checked' binary operator.
```
Comment (nguerrera) [inline src/Compilers/Core/Portable/Operations/IBinaryOperatorExpression.cs]: I think it would be useful to describe more about what 'checked' means semantically in the doc comment than to just repeat the API name. i.e. that it is checked for arithmetic overflow.

File: src/Compilers/Core/Portable/Operations/IBinaryOperatorExpression.cs (hunk 2 above)
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/Operations/IBinaryOperatorExpression.cs]: i mean, 'Checked' makes sense for statements to me.  After all, we have:

```c#
checked
{
// statements
}
```

That said, i don't feel strongly about it.  Given that checked or not really only affects how an expression will be evaluated at runtime, i think it's fine to only have the bit on the specific expressions.  

(the reason though i did like it on IOPeration was that someone could then simply ask "am i in a checked context or not?" and perhaps make changes as appropriate).

**Comment by mavasani** [comment]
Few retest failed as the new analyzer NuGet package was still not available. Its fixed now, so re-running them.

**Comment by mavasani** [comment]
@dotnet-bot retest ubuntu_16_debug_prtest please

**Comment by mavasani** [comment]
@dotnet-bot retest windows_build_correctness_prtest please

**Comment by mavasani** [comment]
@dotnet-bot retest windows_release_unit32_prtest please

**Comment by mavasani** [comment]
@dotnet-bot retest windows_release_unit64_prtest please

**Comment by mavasani** [comment]
@dotnet-bot retest windows_coreclr_test_prtest please

**Comment by AlekseyTs** [comment]
It looks like #8846 also mentions that Option Compare Text for String or Object comparison cannot be represented. Are we going to keep the issue active after this PR?

**Comment by mavasani** [comment]
> It looks like #8846 also mentions that Option Compare Text for String or Object comparison cannot be represented. Are we going to keep the issue active after this PR?

@AlekseyTs, do you think the new flag IsCompareText is not sufficient for this? I can drop by to get more info.

**Comment by AlekseyTs** [comment]
> do you think the new flag IsCompareText is not sufficient for this?

It should be sufficient, some how I missed that part the summary for this PR.

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs [hunk 5]
```diff
@@ -203,749 +203,114 @@ private ImmutableArray<ISwitchCase> GetPatternSwitchStatementCases(BoundPatternS
             });
         }
 
-        private static BinaryOperationKind GetLabelEqualityKind(BoundSwitchLabel label)
+        internal class Helper
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs]: >Helper [](start = 23, length = 6)

Perhaps we should give this class a more meaningful name and move it to its own file, or should get rid of it and place methods into the containing type directly.

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb [hunk 6]
```diff
@@ -413,34 +414,39 @@ Namespace Microsoft.CodeAnalysis.Semantics
             Dim syntax As SyntaxNode = boundUserDefinedUnaryOperator.Syntax
             Dim type As ITypeSymbol = boundUserDefinedUnaryOperator.Type
             Dim constantValue As [Optional](Of Object) = ConvertToOptional(boundUserDefinedUnaryOperator.ConstantValueOpt)
-            Dim isLifted = (boundUserDefinedUnaryOperator.OperatorKind And UnaryOperatorKind.Lifted) <> 0
-            Return New LazyUnaryOperatorExpression(unaryOperationKind, operand, isLifted, usesOperatorMethod, operatorMethod, _semanticModel, syntax, type, constantValue)
+            Dim isLifted = (boundUserDefinedUnaryOperator.OperatorKind And VisualBasic.UnaryOperatorKind.Lifted) <> 0
+            Dim isChecked = False
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb]: >Dim isChecked = False [](start = 12, length = 21)

This implementation doesn't look consistent with C#.

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb [hunk 7]
```diff
@@ -413,34 +414,39 @@ Namespace Microsoft.CodeAnalysis.Semantics
...
             Dim rightOperand As Lazy(Of IOperation) = New Lazy(Of IOperation)(Function() GetUserDefinedBinaryOperatorChild(boundUserDefinedBinaryOperator, 1))
             Dim operatorMethod As IMethodSymbol = If(boundUserDefinedBinaryOperator.UnderlyingExpression.Kind = BoundKind.Call, boundUserDefinedBinaryOperator.Call.Method, Nothing)
             Dim usesOperatorMethod As Boolean = operatorMethod IsNot Nothing
             Dim syntax As SyntaxNode = boundUserDefinedBinaryOperator.Syntax
             Dim type As ITypeSymbol = boundUserDefinedBinaryOperator.Type
             Dim constantValue As [Optional](Of Object) = ConvertToOptional(boundUserDefinedBinaryOperator.ConstantValueOpt)
-            Dim isLifted = (boundUserDefinedBinaryOperator.OperatorKind And BinaryOperatorKind.Lifted) <> 0
-            Return New LazyBinaryOperatorExpression(binaryOperationKind, leftOperand, rightOperand, isLifted, usesOperatorMethod, operatorMethod, _semanticModel, syntax, type, constantValue)
+            Dim isLifted = (boundUserDefinedBinaryOperator.OperatorKind And VisualBasic.BinaryOperatorKind.Lifted) <> 0
+            Dim isChecked = boundUserDefinedBinaryOperator.Checked
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb]: >Dim isChecked = boundUserDefinedBinaryOperator.Checked [](start = 12, length = 54)

This implementation doesn't look consistent with CreateBoundUserDefinedUnaryOperatorOperation

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb [hunk 8]
```diff
@@ -413,34 +414,39 @@ Namespace Microsoft.CodeAnalysis.Semantics
...
+            Dim isCompareText = (boundUserDefinedBinaryOperator.OperatorKind And VisualBasic.BinaryOperatorKind.CompareText) <> 0
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb]: >Dim isCompareText = (boundUserDefinedBinaryOperator.OperatorKind And VisualBasic.BinaryOperatorKind.CompareText) <> 0 [](start = 12, length = 117)

I do not believe CompareText is meaningful for user-defined operators.

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb [hunk 9]
```diff
@@ -453,16 +459,18 @@ Namespace Microsoft.CodeAnalysis.Semantics
...
             Dim rightOperand As Lazy(Of IOperation) = New Lazy(Of IOperation)(Function() Create(boundUserDefinedShortCircuitingOperator.BitwiseOperator.Right))
             Dim usesOperatorMethod As Boolean = True
             Dim operatorMethod As IMethodSymbol = boundUserDefinedShortCircuitingOperator.BitwiseOperator.Call.Method
             Dim syntax As SyntaxNode = boundUserDefinedShortCircuitingOperator.Syntax
             Dim type As ITypeSymbol = boundUserDefinedShortCircuitingOperator.Type
             Dim constantValue As [Optional](Of Object) = ConvertToOptional(boundUserDefinedShortCircuitingOperator.ConstantValueOpt)
-            Dim isLifted = (boundUserDefinedShortCircuitingOperator.BitwiseOperator.OperatorKind And BinaryOperatorKind.Lifted) <> 0
-            Return New LazyBinaryOperatorExpression(binaryOperationKind, leftOperand, rightOperand, isLifted, usesOperatorMethod, operatorMethod, _semanticModel, syntax, type, constantValue)
+            Dim isLifted = (boundUserDefinedShortCircuitingOperator.BitwiseOperator.OperatorKind And VisualBasic.BinaryOperatorKind.Lifted) <> 0
+            Dim isChecked = False
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb]: >Dim isChecked = False [](start = 12, length = 21)

Is this consistent with C# implementation?

**Comment by AlekseyTs** [comment]
>         Concatenate = 0xf,

Is this kind used?

---
Refers to: src/Compilers/Core/Portable/Operations/BinaryOperatorKind.cs:26 in c7a75ef. [](commit_id = c7a75ef16a2b1959416a6b32dbb3d269b36df74b, deletion_comment = False)

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb [hunk 10]
```diff
@@ -466,349 +446,67 @@ Namespace Microsoft.CodeAnalysis.Semantics
...
-                                Return BinaryOperationKind.ObjectLessThanOrEqual
-                            Case BinaryOperatorKind.Equals
-                                Return BinaryOperationKind.ObjectVBEquals
-                            Case BinaryOperatorKind.Is
-                                Return BinaryOperationKind.ObjectEquals
-                            Case BinaryOperatorKind.IsNot
-                                Return BinaryOperationKind.ObjectNotEquals
-                            Case BinaryOperatorKind.NotEquals
-                                Return BinaryOperationKind.ObjectVBNotEquals
-                            Case BinaryOperatorKind.Like
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: >Case BinaryOperatorKind.Like [](start = 28, length = 28)

It looks like this kind is no longer handled.

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb [hunk 11]
```diff
@@ -466,349 +446,67 @@ Namespace Microsoft.CodeAnalysis.Semantics
...
-                            Case BinaryOperatorKind.OrElse
-                                Return BinaryOperationKind.BooleanConditionalOr
-                            Case BinaryOperatorKind.Equals
-                                Return BinaryOperationKind.BooleanEquals
-                            Case BinaryOperatorKind.NotEquals
-                                Return BinaryOperationKind.BooleanNotEquals
-                        End Select
-                    Case SpecialType.System_String
-                        Select Case operatorKind And BinaryOperatorKind.OpMask
-                            Case BinaryOperatorKind.Concatenate
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: >BinaryOperatorKind.Concatenate [](start = 33, length = 30)

It looks like this kind is no longer handled

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb [hunk 12]
```diff
@@ -466,349 +446,67 @@ Namespace Microsoft.CodeAnalysis.Semantics
...
-                                Return BinaryOperationKind.ObjectLeftShift
-                            Case BinaryOperatorKind.RightShift
-                                Return BinaryOperationKind.ObjectRightShift
-                            Case BinaryOperatorKind.LessThan
-                                Return BinaryOperationKind.ObjectLessThan
-                            Case BinaryOperatorKind.LessThanOrEqual
-                                Return BinaryOperationKind.ObjectLessThanOrEqual
-                            Case BinaryOperatorKind.Equals
-                                Return BinaryOperationKind.ObjectVBEquals
-                            Case BinaryOperatorKind.Is
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: >BinaryOperatorKind.Is [](start = 33, length = 21)

It looks like this kind is no longer handled.

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb [hunk 13]
```diff
@@ -466,349 +446,67 @@ Namespace Microsoft.CodeAnalysis.Semantics
...
-                                Return BinaryOperationKind.ObjectEquals
-                            Case BinaryOperatorKind.IsNot
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: >BinaryOperatorKind.IsNot [](start = 33, length = 24)

It looks like this kind is no longer handled.

File: src/Compilers/VisualBasic/Test/Semantic/Diagnostics/OperationAnalyzerTests.vb [hunk 14]
```diff
@@ -1695,24 +1695,26 @@ End Module
...
+                Diagnostic(BinaryOperatorVBTestAnalyzer.BinaryUserDefinedOperatorDescriptor.Id, "x = y").WithArguments("Equals").WithLocation(116, 13),
+                Diagnostic(BinaryOperatorVBTestAnalyzer.BinaryUserDefinedOperatorDescriptor.Id, "x <> y").WithArguments("NotEquals").WithLocation(117, 13),
+                Diagnostic(BinaryOperatorVBTestAnalyzer.BinaryUserDefinedOperatorDescriptor.Id, "x < y").WithArguments("LessThan").WithLocation(118, 13),
+                Diagnostic(BinaryOperatorVBTestAnalyzer.BinaryUserDefinedOperatorDescriptor.Id, "x > y").WithArguments("GreaterThan").WithLocation(119, 13),
+                Diagnostic(BinaryOperatorVBTestAnalyzer.BinaryUserDefinedOperatorDescriptor.Id, "x <= y").WithArguments("LessThanOrEqual").WithLocation(120, 13),
+                Diagnostic(BinaryOperatorVBTestAnalyzer.BinaryUserDefinedOperatorDescriptor.Id, "x >= y").WithArguments("GreaterThanOrEqual").WithLocation(121, 13),
+                Diagnostic(BinaryOperatorVBTestAnalyzer.BinaryUserDefinedOperatorDescriptor.Id, "x Like y").WithArguments("Invalid").WithLocation(122, 13),
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/Diagnostics/OperationAnalyzerTests.vb]: >"x Like y").WithArguments("Invalid") [](start = 96, length = 36)

This looks broken.

File: src/Compilers/VisualBasic/Test/Semantic/Diagnostics/OperationAnalyzerTests.vb [hunk 15]
```diff
@@ -1695,24 +1695,26 @@ End Module
...
+                Diagnostic(BinaryOperatorVBTestAnalyzer.BinaryUserDefinedOperatorDescriptor.Id, "x & y").WithArguments("Invalid").WithLocation(123, 13),
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/Diagnostics/OperationAnalyzerTests.vb]: >"x & y").WithArguments("Invalid") [](start = 96, length = 33)

Is this broken?

File: src/Compilers/VisualBasic/Test/Semantic/IOperation/IOperationTests_IForEachLoopStatement.vb [hunk 16]
```diff
@@ -433,8 +433,8 @@ IForEachLoopStatement (Iteration variable: null) (LoopKind.ForEach) (OperationKi
             Instance Receiver: null
             Arguments(1):
                 IArgument (ArgumentKind.Explicit, Matching Parameter: message) (OperationKind.Argument) (Syntax: 'country.Cou ... untry.Count')
-                  IBinaryOperatorExpression (BinaryOperationKind.StringConcatenate) (OperationKind.BinaryOperatorExpression, Type: System.String) (Syntax: 'country.Cou ... untry.Count')
-                    Left: IBinaryOperatorExpression (BinaryOperationKind.StringConcatenate) (OperationKind.BinaryOperatorExpression, Type: System.String) (Syntax: 'country.Cou ... & " count="')
+                  IBinaryOperatorExpression (BinaryOperatorKind.Invalid, IsChecked) (OperationKind.BinaryOperatorExpression, Type: System.String) (Syntax: 'country.Cou ... untry.Count')
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/IOperation/IOperationTests_IForEachLoopStatement.vb]: >(BinaryOperatorKind.Invalid, IsChecked)  [](start = 44, length = 40)

This looks broken

File: src/Compilers/VisualBasic/Test/Semantic/IOperation/IOperationTests_IForEachLoopStatement.vb [hunk 17]
```diff
@@ -784,14 +784,14 @@ Class C
...
+Dim expectedOperationTree = <![CDATA[
 IForEachLoopStatement (Iteration variable: null) (LoopKind.ForEach) (OperationKind.LoopStatement) (Syntax: 'For Each o  ... Next')
   Collection: IConversionExpression (Implicit, TryCast: False, Unchecked) (OperationKind.ConversionExpression, Type: System.Collections.IEnumerable) (Syntax: 'c')
       Conversion: CommonConversion (Exists: False, IsIdentity: False, IsNumeric: False, IsReference: False, IsUserDefined: False) (MethodSymbol: null)
       Operand: IParameterReferenceExpression: c (OperationKind.ParameterReferenceExpression, Type: System.Object()) (Syntax: 'c')
   Body: IBlockStatement (1 statements) (OperationKind.BlockStatement) (Syntax: 'For Each o  ... Next')
       IIfStatement (OperationKind.IfStatement) (Syntax: 'If o IsNot  ... Return True')
-        Condition: IBinaryOperatorExpression (BinaryOperationKind.ObjectNotEquals) (OperationKind.BinaryOperatorExpression, Type: System.Boolean) (Syntax: 'o IsNot Nothing')
+        Condition: IBinaryOperatorExpression (BinaryOperatorKind.Invalid) (OperationKind.BinaryOperatorExpression, Type: System.Boolean) (Syntax: 'o IsNot Nothing')
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/IOperation/IOperationTests_IForEachLoopStatement.vb]: >(BinaryOperatorKind.Invalid) [](start = 45, length = 28)

This looks broken

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb (hunk 12 above)
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: It would be good to have  a test for this operator and string operands

---
In reply to: [133323581](https://github.com/dotnet/roslyn/pull/21407#discussion_r133323581) [](ancestors = 133323581)

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs [hunk 18]
```diff
@@ -775,27 +775,29 @@ private IMemberInitializerExpression CreateBoundMemberInitializerOperation(Bound
...
-            bool usesOperatorMethod = (boundCompoundAssignmentOperator.Operator.Kind & BinaryOperatorKind.TypeMask) == BinaryOperatorKind.UserDefined;
+            bool usesOperatorMethod = (boundCompoundAssignmentOperator.Operator.Kind & CSharp.BinaryOperatorKind.TypeMask) == CSharp.BinaryOperatorKind.UserDefined;
             IMethodSymbol operatorMethod = boundCompoundAssignmentOperator.Operator.Method;
             SyntaxNode syntax = boundCompoundAssignmentOperator.Syntax;
             ITypeSymbol type = boundCompoundAssignmentOperator.Type;
             Optional<object> constantValue = ConvertToOptional(boundCompoundAssignmentOperator.ConstantValue);
-            return new LazyCompoundAssignmentExpression(binaryOperationKind, boundCompoundAssignmentOperator.Type.IsNullableType(), target, value, usesOperatorMethod, operatorMethod, _semanticModel, syntax, type, constantValue);
+            return new LazyCompoundAssignmentExpression(operatorKind, boundCompoundAssignmentOperator.Type.IsNullableType(), target, value, usesOperatorMethod, operatorMethod, _semanticModel, syntax, type, constantValue);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: >new LazyCompoundAssignmentExpression(operatorKind, boundCompoundAssignmentOperator.Type.IsNullableType( [](start = 19, length = 103)

What about ```checked``` flag?

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs [hunk 19]
```diff
@@ -775,27 +775,29 @@ private IMemberInitializerExpression CreateBoundMemberInitializerOperation(Bound
...
+            bool isLifted = boundIncrementOperator.OperatorKind.IsLifted();
             Lazy<IOperation> target = new Lazy<IOperation>(() => Create(boundIncrementOperator.Operand));
-            bool usesOperatorMethod = (boundIncrementOperator.OperatorKind & UnaryOperatorKind.TypeMask) == UnaryOperatorKind.UserDefined;
+            bool usesOperatorMethod = (boundIncrementOperator.OperatorKind & CSharp.UnaryOperatorKind.TypeMask) == CSharp.UnaryOperatorKind.UserDefined;
             IMethodSymbol operatorMethod = boundIncrementOperator.MethodOpt;
             SyntaxNode syntax = boundIncrementOperator.Syntax;
             ITypeSymbol type = boundIncrementOperator.Type;
             Optional<object> constantValue = ConvertToOptional(boundIncrementOperator.ConstantValue);
-            return new LazyIncrementExpression(incrementOperationKind, target, usesOperatorMethod, operatorMethod, _semanticModel, syntax, type, constantValue);
+            return new LazyIncrementExpression(isDecrement, isPostfix, isLifted, target, usesOperatorMethod, operatorMethod, _semanticModel, syntax, type, constantValue);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: >return new LazyIncrementExpression(isDecrement, isPostfix, isLifted, [](start = 12, length = 68)

What about ```checked``` flag?

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb [hunk 20]
```diff
@@ -272,7 +272,7 @@ Namespace Microsoft.CodeAnalysis.Semantics
                 Dim syntax As SyntaxNode = boundAssignmentOperator.Syntax
                 Dim type As ITypeSymbol = boundAssignmentOperator.Type
                 Dim constantValue As [Optional](Of Object) = ConvertToOptional(boundAssignmentOperator.ConstantValueOpt)
-                Return New LazyCompoundAssignmentExpression(binaryOperationKind, boundAssignmentOperator.Type.IsNullableType(), target, value, usesOperatorMethod, operatorMethod, _semanticModel, syntax, type, constantValue)
+                Return New LazyCompoundAssignmentExpression(operatorKind, boundAssignmentOperator.Type.IsNullableType(), target, value, usesOperatorMethod, operatorMethod, _semanticModel, syntax, type, constantValue)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb]: >Return New LazyCompoundAssignmentExpression(operatorKind [](start = 16, length = 56)

What about ```checked``` flag?

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb]: >boundAssignmentOperator.Type.IsNullableType() [](start = 74, length = 45)

I am curious what this check is used for?

**Comment by AlekseyTs** [comment]
Do we expose ```checked``` flag for ```for``` loop increment in VB?

**Comment by AlekseyTs** [comment]
Please add targeted tests for each new flag added. Given the number of affected existing tests, it is hard to figure out what coverage they provide, what permutations are covered etc.

**Comment by AlekseyTs** [comment]
Done with review pass.

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs (hunk 5 above)
Comment (mavasani) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs]: Sure, added the comment to the list of items tracked here: https://github.com/dotnet/roslyn/issues/20204

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb (hunk 6 above)
Comment (mavasani) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb]: @AlekseyTs Seems like certain bound nodes for operators in VB don't have the Checked flag. I am not sure how this value should be exposed for such operators. Do you think this is a compiler bug that the check overflow value is not respected for these operators or the default value of False that is being used here is incorrect? I can drop by to chat whenever you are in office.

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb]: If nodes for user-defined operators don't have Checked flag, that is fine because it is meaningless for them. The implementation is good then.

**Comment by mavasani** [comment]
I will open a separate issue for this.

---
In reply to: [322617592](https://github.com/dotnet/roslyn/pull/21407#issuecomment-322617592) [](ancestors = 322617592)

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb (hunk 20 above)
Comment (mavasani) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb]: Refactored into a separate local

---
In reply to: [133329408](https://github.com/dotnet/roslyn/pull/21407#discussion_r133329408) [](ancestors = 133329408)

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb (hunk 6 above)
Comment (mavasani) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb]: As we discussed, VB bound node for this operator doesn't have this flag.

---
In reply to: [133312257](https://github.com/dotnet/roslyn/pull/21407#discussion_r133312257) [](ancestors = 133312257)

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs (hunk 18 above)
Comment (mavasani) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: Added.

---
In reply to: [133328954](https://github.com/dotnet/roslyn/pull/21407#discussion_r133328954) [](ancestors = 133328954)

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs (hunk 19 above)
Comment (mavasani) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: Added

---
In reply to: [133329027](https://github.com/dotnet/roslyn/pull/21407#discussion_r133329027) [](ancestors = 133329027)

**Comment by mavasani** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

**Comment by mavasani** [comment]
@jcouv @cston can you please take a look?

**Comment by mavasani** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

**Comment by mavasani** [comment]
@dotnet retest windows_debug_vs-integration_prtest please

**Comment by mavasani** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by mavasani** [comment]
> Do we expose checked flag for for loop increment in VB?

Filed https://github.com/dotnet/roslyn/issues/21648

File: src/Compilers/Core/Portable/Generated/Operations.xml.Generated.cs [hunk 21]
```diff
@@ -669,9 +671,21 @@ internal abstract partial class BaseBinaryOperatorExpression : Operation, IHasOp
...
+        /// <code>true</code> if this is a 'lifted' binary operator.  When there is an 
+        /// operator that is defined to work on a value type, 'lifted' operators are 
+        /// created to work on the <see cref="System.Nullable{T}"/> versions of those
+        /// value types.
+        /// </summary>
         public bool IsLifted { get; }
-
+        /// <summary>
+        /// <code>true</code> if this is overflow checking is performed for the arithmetic operation.
+        /// </summary>
```
Comment (bkoelman) [inline src/Compilers/Core/Portable/Generated/Operations.xml.Generated.cs]: *is* (sentence)

Comment (bkoelman) [inline src/Compilers/Core/Portable/Generated/Operations.xml.Generated.cs]: (occurs 7 times)

File: src/Compilers/Core/Portable/Generated/Operations.xml.Generated.cs [hunk 22]
```diff
@@ -2005,17 +2024,37 @@ public LazyIfStatement(Lazy<IOperation> condition, Lazy<IOperation> ifTrueStatem
...
         /// </summary>
-        public UnaryOperationKind IncrementOperationKind { get; }
+        public bool IsDecrement { get; }
+        /// <summary>
+        /// <code>true</code> if this is a postfix expression.
+        /// <code>false</code> if this is a prefix expression.
+        /// </summary>
+        public bool IsPostfix { get; }
+        /// <summary>
+        /// <code>true</code> if this is a 'lifted' incremen operator.  When there is an
```
Comment (bkoelman) [inline src/Compilers/Core/Portable/Generated/Operations.xml.Generated.cs]: incremen*t*

File: src/Compilers/Core/Portable/Operations/IIncrementExpression.cs [hunk 23]
```diff
@@ -19,9 +17,29 @@ public interface IIncrementExpression : IOperation, IHasOperatorMethodExpression
...
+        bool IsDecrement { get; }
+
+        /// <summary>
+        /// <code>true</code> if this is a postfix expression.
+        /// <code>false</code> if this is a prefix expression.
+        /// </summary>
+        bool IsPostfix { get; }
+
+        /// <summary>
+        /// <code>true</code> if this is a 'lifted' incremen operator.  When there is an
```
Comment (bkoelman) [inline src/Compilers/Core/Portable/Operations/IIncrementExpression.cs]: incremen**t**

File: src/Compilers/Core/Portable/Operations/UnaryOperatorKind.cs [hunk 24]
```diff
@@ -1,24 +1,21 @@
...
-        Plus = 0x7,
-        Minus = 0x8,
-        True = 0x9,
-        False = 0xa,
-        BitwiseOrLogicalNot = 0xb,
+        Plus = 0x3,
+        Minus = 0x4,
+        True = 0x5,
+        False = 0x6,
+        BitwiseOrLogicalNot = 0x7,
```
Comment (cston) [inline src/Compilers/Core/Portable/Operations/UnaryOperatorKind.cs]: Is `BitwiseOrLogicalNot` still used?

**Review by cston — APPROVED** [review]

File: src/Compilers/Core/Portable/Operations/UnaryOperatorKind.cs (hunk 24 above)
Comment (mavasani) [inline src/Compilers/Core/Portable/Operations/UnaryOperatorKind.cs]: Thanks, you are correct. It seems C# has separate operator kinds for BitwiseNegation and LogicalNot. VB has single Not operator to represent LogicalNot (bool operand), BitwiseNegation (integral operand) and BitwiseOrLogicalNot (object operand)

---
In reply to: [134530885](https://github.com/dotnet/roslyn/pull/21407#discussion_r134530885) [](ancestors = 134530885)

Comment (mavasani) [inline src/Compilers/Core/Portable/Operations/UnaryOperatorKind.cs]: Actually, I looked at the other logical operators in VB 'And', 'Or' and 'Xor', and they have also similar differing semantics based on the type of the operands, but we use a single BinaryOperatorKind to represent them. I recall that the design team has decided that we will not have different OperatorKind for the same operator just due to different semantics based on operand types. So, I am going to delete BitwiseOrLogicalNot and we will use 'LogicalNot' to represent VB 'Not' operator and C# '!' operator. 'BitwiseNegation' will be used only for the C# '~' operator.

---
In reply to: [134536171](https://github.com/dotnet/roslyn/pull/21407#discussion_r134536171) [](ancestors = 134536171,134530885)

**Comment by mavasani** [comment]
@AlekseyTs can you please take another look?

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs [hunk 25]
```diff
@@ -256,9 +255,7 @@ private IOperation CreateInternal(BoundNode boundNode)
                     return CreateBoundIsPatternExpressionOperation((BoundIsPatternExpression)boundNode);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: >boundCompoundAssignmentOperator.Type.IsNullableType(); [](start = 28, length = 54)

I do not think this is correct way to figure out whether the operator is lifted. Isn't this information part of the operator kind? Please check for other similar places.

Comment (mavasani) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: Tagging @CyrusNajmabadi - I will file a separate issue to track this as this is not part of this PR.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: Please add tests that expose problems with the current code.

---
In reply to: [135119021](https://github.com/dotnet/roslyn/pull/21407#discussion_r135119021) [](ancestors = 135119021)

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb [hunk 26]
```diff
@@ -256,12 +255,11 @@ Namespace Microsoft.CodeAnalysis.Semantics
 
         Private Function CreateBoundAssignmentOperatorOperation(boundAssignmentOperator As BoundAssignmentOperator) As IOperation
             Dim kind = GetAssignmentKind(boundAssignmentOperator)
-            Dim isImplicit As Boolean = boundAssignmentOperator.WasCompilerGenerated
             If kind = OperationKind.CompoundAssignmentExpression Then
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb]: >Dim isChecked As Boolean = False [](start = 16, length = 32)

This code for ```isChecked``` and ```isLifted``` doesn't look right. Shouldn't we pull this information from the binary operator? Please add tests that expose incorrect behavior.

Comment (mavasani) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb]: [BoundAssignmentOperatior](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Generated/BoundNodes.xml.Generated.vb,b1659918c50dce2c,references) in VB doesn't contain a Checked flag, so I have defaulted it to false. I will file an issue to track the correct way for calculated IsLifted.

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs (hunk 25 above)
Comment (mavasani) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: Filed https://github.com/dotnet/roslyn/issues/21723 to track issues with IsLifted.

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb [hunk 27]
```diff
@@ -396,25 +386,24 @@ Namespace Microsoft.CodeAnalysis.Semantics
...
             Dim type As ITypeSymbol = boundArrayAccess.Type
             Dim constantValue As [Optional](Of Object) = ConvertToOptional(boundArrayAccess.ConstantValueOpt)
-            Dim isImplicit As Boolean = boundArrayAccess.WasCompilerGenerated
-            Return New LazyArrayElementReferenceExpression(arrayReference, indices, _semanticModel, syntax, type, constantValue, isImplicit)
+            Return New LazyArrayElementReferenceExpression(arrayReference, indices, _semanticModel, syntax, type, constantValue)
         End Function
 
         Private Function CreateBoundUnaryOperatorOperation(boundUnaryOperator As BoundUnaryOperator) As IUnaryOperatorExpression
-            Dim unaryOperationKind As UnaryOperationKind = Helper.DeriveUnaryOperationKind(boundUnaryOperator.OperatorKind, boundUnaryOperator.Operand)
+            Dim operatorKind As UnaryOperatorKind = Helper.DeriveUnaryOperatorKind(boundUnaryOperator.OperatorKind)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb]: >Dim isChecked As Boolean = False [](start = 12, length = 32)

This doesn't look right, conversions can be checked too.

Comment (mavasani) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb]: Tagging @333fred

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb [hunk 28]
```diff
@@ -434,16 +402,25 @@ Namespace Microsoft.CodeAnalysis.Semantics
                             _semanticModel,
                             syntax,
                             type:=Nothing,
-                            constantValue:=Nothing,
-                            isImplicit:=False) ' Declaration is always explicit
+                            constantValue:=Nothing)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: >leftOpt?.Type [](start = 34, length = 13)

Let's handle the case of null Type, just in case this can happen with erroneous code.

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs [hunk 29]
```diff
@@ -204,749 +204,114 @@ private ImmutableArray<ISwitchCase> GetPatternSwitchStatementCases(BoundPatternS
...
-                                return BinaryOperationKind.PointerGreaterThan;
-                            case BinaryOperatorKind.Enum:
-                                return BinaryOperationKind.EnumGreaterThan;
-                            case BinaryOperatorKind.UserDefined:
-                                return BinaryOperationKind.OperatorMethodGreaterThan;
-                        }
-
-                        break;
+                    case CSharp.BinaryOperatorKind.Addition:
+                        return BinaryOperatorKind.Add;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs]: >return BinaryOperatorKind.Add; [](start = 24, length = 30)

How do we represent string concatenation? Should we ever return Concatenate kind.

Comment (mavasani) [reply src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs]: We return Concatenate kind only for the VB Concatenate operator. I can open a separate issue to track whether or not we should represent C# + operation with string operators as Concatenate.

File: src/Compilers/Core/Portable/Operations/UnaryOperatorKind.cs [hunk 30]
```diff
@@ -0,0 +1,48 @@
...
+
+        /// <summary>
+        /// Represents the C# '~' operator.
+        /// </summary>
+        BitwiseNegation = 0x1,
+
+        /// <summary>
+        /// Represents the C# '!' operator and VB 'Not' operator.
+        /// </summary>
+        LogicalNot = 0x2,
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Operations/UnaryOperatorKind.cs]: >LogicalNot = 0x2, [](start = 8, length = 17)

Can we simply call it ```Not```?

File: src/Compilers/Core/Portable/Operations/ICompoundAssignmentExpression.cs [hunk 31]
```diff
@@ -16,10 +14,16 @@ public interface ICompoundAssignmentExpression : IAssignmentExpression, IHasOper
...
+
         /// <summary>
         /// <code>true</code> if this assignment contains a 'lifted' binary operation.
         /// </summary>
         bool IsLifted { get; }
+
+        /// <summary>
+        /// <code>true</code> if overflow checking is performed for the arithmetic operation.
+        /// </summary>
+        bool IsChecked { get; }
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Operations/ICompoundAssignmentExpression.cs]: >bool IsChecked { get; } [](start = 8, length = 23)

Do we have positive and negative tests for this property?

File: src/Compilers/Core/Portable/Operations/IIncrementExpression.cs [hunk 32]
```diff
@@ -19,9 +17,29 @@ public interface IIncrementExpression : IOperation, IHasOperatorMethodExpression
...
+        /// created to work on the <see cref="System.Nullable{T}"/> versions of those
+        /// value types.
+        /// </summary>
+        bool IsLifted { get; }
+
+        /// <summary>
+        /// <code>true</code> if overflow checking is performed for the arithmetic operation.
         /// </summary>
-        UnaryOperationKind IncrementOperationKind { get; }
+        bool IsChecked { get; }
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Operations/IIncrementExpression.cs]: >ool IsChecked { get; } [](start = 9, length = 22)

Do we have positive and negative tests for this property?

**Comment by AlekseyTs** [comment]
Done with review pass.

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb (hunk 26 above)
Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb]: BoundAssignmentOperatior doesn't need to have the flag, that information is available on the binary operator associated with the compound assignment, see the code  

```Dim temporaryRight = DirectCast(Create(boundAssignmentOperator.Right), IBinaryOperatorExpression)```

**Comment by AlekseyTs** [comment]
>                 Select Case value.Right.Kind

I believe this switch should handle case of conversion on top of the binary operator. Do we have an issue tracking that? Basically, if ```value.LeftOnTheRightOpt IsNot Nothing``` then this is a compound assignment. We should also confirm whether binary operators are always there, even in erroneous case.  

---
Refers to: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb:17 in 30167a6. [](commit_id = 30167a69209ef75bea9d90279c14cc3c73663381, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs (hunk 29 above)
Comment (mavasani) [reply src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs]: Filed https://github.com/dotnet/roslyn/issues/21737

File: src/Compilers/Core/Portable/Operations/UnaryOperatorKind.cs (hunk 30 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/Operations/UnaryOperatorKind.cs]: Sure, done.

**Comment by mavasani** [comment]
>I believe this switch should handle case of conversion on top of the binary operator. Do we have an issue tracking that? Basically, if value.LeftOnTheRightOpt IsNot Nothing then this is a compound assignment. We should also confirm whether binary operators are always there, even in erroneous case.

Filed https://github.com/dotnet/roslyn/issues/21738

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb (hunk 28 above)
Comment (mavasani) [reply src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: Sure, done

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb (hunk 27 above)
Comment (mavasani) [reply src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory.vb]: Filed https://github.com/dotnet/roslyn/issues/21740

File: src/Compilers/Core/Portable/Operations/ICompoundAssignmentExpression.cs (hunk 31 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/Operations/ICompoundAssignmentExpression.cs]: Done.

File: src/Compilers/Core/Portable/Operations/IIncrementExpression.cs (hunk 32 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/Operations/IIncrementExpression.cs]: Done.

**Comment by mavasani** [comment]
@AlekseyTs addressed your feedback, thanks.

File: src/Compilers/Core/Portable/Operations/IIncrementExpression.cs [hunk 33]
```diff
@@ -19,9 +17,29 @@ public interface IIncrementExpression : IOperation, IHasOperatorMethodExpression
         IOperation Target { get; }
 
         /// <summary>
-        /// Kind of increment.
+        /// <code>true</code> if this is a decrement expression.
+        /// <code>false</code> if this is an increment expression.
+        /// </summary>
+        bool IsDecrement { get; }
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Operations/IIncrementExpression.cs]: >bool IsDecrement { get; } [](start = 8, length = 25)

I think we should consider to simply use distinct kind for decrement rather than having a special property. IIncrementExpression could have two different kinds. Something to discuss at the next design meeting.

**Review by AlekseyTs — APPROVED** [review]
LGTM

File: src/Compilers/Core/Portable/Operations/IIncrementExpression.cs (hunk 33 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/Operations/IIncrementExpression.cs]: It was originally a separate kind, but we decided to remove it when you were OOF. Lets discuss it one more time next meeting - I will file a tracking issue.

Comment (mavasani) [reply src/Compilers/Core/Portable/Operations/IIncrementExpression.cs]: Filed https://github.com/dotnet/roslyn/issues/21748

**Comment by mavasani** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest  please
