### PR TITLE
Check generic containing attribute types

### LINKED ISSUE #58837: Missing CS8970 when applying attribute class having unsupported type arguments from containing type
**Version Used**: 
sharplab.io main 6 Jan 2022

**Steps to Reproduce**:
Compile the following code:

```csharp
using System;

[A<(int A, int B)>.B]
class C
{
}

class A<T>
{  
  public class B : Attribute
  {
  }
}
```

**Expected Behavior**:
Error CS8970 on attribute application.

**Actual Behavior**:
No errors.

### PR DESCRIPTION
**Pull request by jjonescz**
Fixes #58837.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs [hunk 1]
```diff
@@ -10799,6 +10799,74 @@ void verify(ModuleSymbol module)
...
+class C
+{
+}
+
+class A<T>
+{  
+    public class B : Attribute
+    {
+    }
+}
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs:10853]: Consider splitting this into a separate test if it is independent of the cases above.

File: src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs [hunk 2]
```diff
@@ -10799,6 +10799,74 @@ void verify(ModuleSymbol module)
...
+
+[A<(int A, int B)>.B]
+class C
+{
+}
+
+class A<T>
+{  
+    public class B : Attribute
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs:10850]: >B [](http://example.com/codeflow?start=17&length=1)

Please add a test for `[A<int A, int B)>.B]` where the inner type is named `BAttribute`.

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs [hunk 3]
```diff
@@ -1190,6 +1190,25 @@ private Symbol UnwrapAlias(Symbol symbol, out AliasSymbol alias, BindingDiagnost
             }
 
             return TypeWithAnnotations.Create(AreNullableAnnotationsEnabled(node.TypeArgumentList.GreaterThanToken), resultType);
+
+            // Determines whether node represents containing type of an attribute.
+            // For example, returns true for "A<T>" node in "[A<T>.B]".
+            static bool ContainsAttributeType(NameSyntax node)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs:1196]: >C [](http://example.com/codeflow?start=24&length=1)

We typically use lowercase for the first letter of local function names.

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs [hunk 4]
```diff
@@ -1190,6 +1190,25 @@ private Symbol UnwrapAlias(Symbol symbol, out AliasSymbol alias, BindingDiagnost
...
+            {
+                var parent = node.Parent;
+                if (parent is null)
+                {
+                    return false;
+                }
+
+                if (parent.Kind() == SyntaxKind.QualifiedName)
+                {
+                    var qn = (QualifiedNameSyntax)parent;
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs:1206]:
```suggestion
                if (node.Parent is QualifiedNameSyntax qn)
                {
```

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs [hunk 5]
```diff
@@ -1190,6 +1190,25 @@ private Symbol UnwrapAlias(Symbol symbol, out AliasSymbol alias, BindingDiagnost
...
+                    return SyntaxFacts.IsAttributeName(qn.Right) || ContainsAttributeType(qn);
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs:1207]: Let's use an iterative approach here, rather than a recursive approach.

**Review by 333fred — COMMENTED** [review]
Done review pass (commit 1)

File: src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs (hunk 1 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs:10873]: f161a6d488f331211b543861d0f85de9098d083e

File: src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs (hunk 2 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs:10870]: 2c71c355975227a42c17e03acbcd856acccf626e

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs (hunk 3 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs]: 5e7ac70c223fd907058bc07ef8773819e58d5da3

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs (hunk 4 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs]: 1a6366a7e888361f9f3284bb3a71da4bc98c8091

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs (hunk 5 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs]: 1a6366a7e888361f9f3284bb3a71da4bc98c8091

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs [hunk 6]
```diff
@@ -1161,7 +1161,7 @@ private Symbol UnwrapAlias(Symbol symbol, out AliasSymbol alias, BindingDiagnost
             {
                 var boundTypeArguments = BindTypeArguments(typeArguments, diagnostics, basesBeingResolved);
                 if (unconstructedType.IsGenericType
-                    && options.IsAttributeTypeLookup())
+                    && (options.IsAttributeTypeLookup() || containsAttributeType(node)))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs:1164]: > && (options.IsAttributeTypeLookup() || containsAttributeType(node))) [](http://example.com/codeflow?start=19&length=69)

I think this is not the right place to perform this check. Not all constituent parts of the attribute type are going to be looked up at the attribute name location. For example,
```
using AB = A<(int A, int B)>.B;

[AB]
class C
{
}

class A<T>
{  
  public class B : System.Attribute
  {
  }
}
```

"AB" in ```[AB]``` is not even a generic name (so we will not get here), yet the attribute type still has the same problem. I think the check should be moved to where we bind attribute application. Once we get the attribute type back, we should simply run the validation across all of its parts, containing types, type arguments, etc. (VisitType does that, I think).

It looks like Binder.BindAttributeTypes method is the right place to do the check. Right after ```binder.BindType``` call.

**Comment by AlekseyTs** [comment]
Do we have the same issue in VB? If VB reports similar error, at least we need to add similar tests, I think.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 5)

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs [hunk 7]
```diff
@@ -1190,6 +1190,19 @@ private Symbol UnwrapAlias(Symbol symbol, out AliasSymbol alias, BindingDiagnost
...
 
             return TypeWithAnnotations.Create(AreNullableAnnotationsEnabled(node.TypeArgumentList.GreaterThanToken), resultType);
+
+            // Determines whether node represents containing type of an attribute.
+            // For example, returns true for "A<T>" node in "[A<T>.B]".
+            static bool containsAttributeType(NameSyntax node)
+            {
+                while (node.Parent is QualifiedNameSyntax qn)
+                {
+                    if (SyntaxFacts.IsAttributeName(qn.Right)) return true;
```
[the remark this answers is not in the document]
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs]: Good catch, fixed: 8a5dc429855c56f1927e4c211953149d4e4b6bcb

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs (hunk 6 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs]: Sounds like a much better place, you are right. Moved the check there: cd02bbaf4f4ac4c2e8ff970cccea1897070bd9e4

**Comment by jjonescz** [comment]
> Do we have the same issue in VB? If VB reports similar error, at least we need to add similar tests, I think.

It should be impossible to have generic attributes in VB: [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAGxAN2HALiCBndAfASTAAcB7AJ3WwAIBlAT1wFMwBYAKA4GEEcavSMdNBhNyACgDyAM2oAVAJQdqK6gB4AgunQSZ8hQD5lqnn2pcAjMZUBRGABNzvbNg7X1WnQKEixU2YoAdJ7kRuyqTmZcAEzudo6mLm7hqpra5N7CsH56QQBCwelhEYn8AMxxDpFJ7PHVrpzspdQh/vruBDAAFmJQVC3pUMAAruhMHHWlyc0hmb66AUopKgAKw8AIUADG9QM67hGdPeR9NCFDo+ONERFrG9vUK+SkxGLo9NQAahAIw0wtNDklQSzga7jumx2zTyB1UEIeM3SsJu1COvX65xGY2R1EmoOB9QmVSm7CAA==)

File: src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs [hunk 8]
```diff
@@ -10799,6 +10799,176 @@ void verify(ModuleSymbol module)
...
 
+        [Fact, WorkItem(58837, "https://github.com/dotnet/roslyn/issues/58837")]
+        public void GenericAttribute_NestedType01()
+        {
+            var source = @"
+using System;
+
+class Container<T>
+{
+    [Attr<T>]
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs:10810]: >[Attr<T>] [](http://example.com/codeflow?start=4&length=9)

Consider testing `[Attr<T[]>]` as well.

File: src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs [hunk 9]
```diff
@@ -10799,6 +10799,176 @@ void verify(ModuleSymbol module)
...
+                Diagnostic(ErrorCode.ERR_AttrTypeArgCannotBeTypeVar, "AttrContainer<T>.B.Attr").WithArguments("T").WithLocation(16, 6));
+        }
+
+        [Fact, WorkItem(58837, "https://github.com/dotnet/roslyn/issues/58837")]
+        public void GenericAttribute_NestedType02()
+        {
+            var source = @"
+using System;
+
+[A<(int A, int B)>.B]
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs:10863]: Consider testing `[A<(int A, int B)[]>.B]` as well.

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs [hunk 10]
```diff
@@ -51,7 +51,30 @@ internal partial class Binder
...
                     // When looking up a name in attribute type context, we generate a diagnostic + error type if it is not an attribute type, i.e. named type deriving from System.Attribute.
                     // Hence we can assume here that BindType returns a NamedTypeSymbol.
-                    boundAttributeTypes[i] = (NamedTypeSymbol)binder.BindType(attributeToBind.Name, diagnostics).Type;
+                    var boundType = binder.BindType(attributeToBind.Name, diagnostics);
+                    var boundTypeSymbol = (NamedTypeSymbol)boundType.Type;
+
+                    // Check type arguments inside the attribute type (unless the attribute type is already an error).
+                    if (boundTypeSymbol.TypeKind != TypeKind.Error)
+                    {
+                        var location = attributeToBind.GetLocation();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs:60]: >attributeToBind [](http://example.com/codeflow?start=39&length=15)

Location probably should be just the type rather than the entire attribute syntax

File: src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs [hunk 11]
```diff
@@ -51,7 +51,30 @@ internal partial class Binder
...
+                        for (var type = boundTypeSymbol; type is not null; type = type.ContainingType)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs:61]: >for (var type = boundTypeSymbol; type is not null; type = type.ContainingType) [](http://example.com/codeflow?start=24&length=78)

I think all this logic should be moved into ```CheckDisallowedAttributeDependentType``` and it should be called with ```boundType```. ```CheckDisallowedAttributeDependentType``` already traverses containing types, we just need to add checks for unbound generic type and type parameters.

**Comment by AlekseyTs** [comment]
>It is impossible to have generic attributes in VB at all, so this shouldn't be needed: [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAGxAN2AHwJJgA4HsBOALgM4AEAygJ7GECmYAsAFDMDCCExZruMh0MWvgAUAeQBmpACoBKZqQWkAPAEFChEROkyAfPMXtO3AIz6FAURgATUoa7MzytRp58BQsZNkA6Z/j1MirYcXLYATI6WNnbEDoGKqur4rvywHlo+AEK+SQFBMbYAzJHWwUbMUWX2LEwFfp7ajhgwABZCUCSkflDAAK50FaUxcXVJKe6aXnLxCgAKvcAIUADGVWR+jkHNbfgd60k9/bRxQUHziyuks/i42EKElKQAahAIvbRdZFIl0SGxNWcFktVgVMptFOdgWsuklwadSNt2p1un0BjNTpVhujMX9Br9ykwgA)

The attribute type doesn't have to be declared in VB. Therefore, the fact that a generic attribute cannot be declared in VB is not important. It is true that VB also doesn't support application of generic attributes, but we cannot judge whether the check is robust based on a single code example. C# compiler also reported errors for some scenarios, but failed to do that for others. In general, a code example can prove that a problem exists, but it is not often possible to prove the opposite, unless we are certain that the example covers all possible scenarios of interest. That said, I looked at the source code responsible for reporting ```ERR_AttrCannotBeGenerics``` in VB and the implementation looked good to me.

File: src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs (hunk 11 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs]: Alright, but `CheckDisallowedAttributeDependentType` traverses the whole type, not just nested types, so after moving the checks there, I changed them to work directly on the type arguments and hence the reported argument slightly changed: 1480493cbd30fee714e29a50fbd6102d0c201a43

File: src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs (hunk 10 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Binder/Binder_Attributes.cs]: Right, that looks better. Fixed: 7a4b202cad2947b3be6e0b2ebdad561dc80e455d

File: src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs (hunk 8 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs:10810]: Good idea, added: 80caaf81e2032d861eec014c76bed3e85517ff8a

File: src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs (hunk 9 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests.cs:10871]: Good idea, added: 80caaf81e2032d861eec014c76bed3e85517ff8a

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 12]
```diff
@@ -1355,19 +1355,24 @@ private void CheckDisallowedAttributeDependentType(TypeWithAnnotations typeArgum
...
-                var (topLevelType, errorLocation, diagnostics) = arg;
+                var (errorLocation, diagnostics) = arg;
                 var type = typeWithAnnotations.Type;
                 if (type.IsDynamic()
                     || (typeWithAnnotations.NullableAnnotation.IsAnnotated() && !type.IsValueType)
                     || type.IsNativeIntegerWrapperType
                     || (type.IsTupleType && !type.TupleElementNames.IsDefault))
                 {
-                    diagnostics.Add(ErrorCode.ERR_AttrDependentTypeNotAllowed, errorLocation, topLevelType.ToDisplayString(SymbolDisplayFormat.CSharpShortErrorMessageFormat));
+                    diagnostics.Add(ErrorCode.ERR_AttrDependentTypeNotAllowed, errorLocation, type.ToDisplayString(SymbolDisplayFormat.CSharpShortErrorMessageFormat));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:1365]: >type.ToDisplayString(SymbolDisplayFormat.CSharpShortErrorMessageFormat) [](http://example.com/codeflow?start=94&length=71)

This is a "preexisting condition", but since we are changing this function and since you are "copying" this below, let's fix it. We are not supposed to convert symbols to strings for the purpose of creating diagnostics. We either should use "raw" symbols as arguments, or, if default formatting isn't what we want, we should use ```FormattedSymbol```s.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 13]
```diff
@@ -1355,19 +1355,24 @@ private void CheckDisallowedAttributeDependentType(TypeWithAnnotations typeArgum
...
+                    return true;
+                }
+                if (type.Kind == SymbolKind.TypeParameter)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:1368]: >if (type.Kind == SymbolKind.TypeParameter) [](http://example.com/codeflow?start=16&length=42)

Consider adding an empty line between two multi-line statements. This is going to improve readability of the code and probably will make the diff for the change easier to follow.

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs [hunk 14]
```diff
@@ -1160,22 +1160,6 @@ private Symbol UnwrapAlias(Symbol symbol, out AliasSymbol alias, BindingDiagnost
             else
             {
                 var boundTypeArguments = BindTypeArguments(typeArguments, diagnostics, basesBeingResolved);
-                if (unconstructedType.IsGenericType
-                    && options.IsAttributeTypeLookup())
-                {
-                    foreach (var typeArgument in boundTypeArguments)
-                    {
-                        var type = typeArgument.Type;
-                        if (type.IsUnboundGenericType() || type.ContainsTypeParameter())
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs:1169]: >type.IsUnboundGenericType() [](http://example.com/codeflow?start=28&length=27)

It looks like this check is dropped, not moved to ```CheckDisallowedAttributeDependentType````. It doesn't look like anything is obviously broken, but I would keep it anyway.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 11)

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 12 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: Makes sense. Fixed: 2fd652d9257dfcb245a738983bdf8364e769c0c2

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 13 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:1369]: Good idea. Fixed: b451f3daccb48971a89b4eb8cdcdeb2632167482

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs (hunk 14 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs:1169]: The check is replaced by `type.Kind == SymbolKind.TypeParameter`. That's because previously, only the top-level types were traversed (e.g., `A<T>` and `B` in `A<T>.B`), but the `CheckDisallowedAttributeDependentType` method traverses the whole type (e.g., `T` also in `A<T>.B`). So after moving the checks there (https://github.com/dotnet/roslyn/pull/64006#discussion_r975027168), I changed them to fire on the type argument itself instead of on the `A<T>`.

https://github.com/dotnet/roslyn/blob/2fd652d9257dfcb245a738983bdf8364e769c0c2/src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs#L1369

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs:1169]: > The check is replaced by ```type.Kind == SymbolKind.TypeParameter```.

I am specifically referring to the ```type.IsUnboundGenericType()``` check. It is not the same as a type parameter check.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 13)

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs (hunk 14 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs:1169]: Oh, right. I'm not sure how to hit that code path, but added nevertheless: d70a2ee8f113f9687651aa4d56bd37f0e6de58b5

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 15]
```diff
@@ -1355,19 +1355,25 @@ private void CheckDisallowedAttributeDependentType(TypeWithAnnotations typeArgum
...
                     || (typeWithAnnotations.NullableAnnotation.IsAnnotated() && !type.IsValueType)
                     || type.IsNativeIntegerWrapperType
                     || (type.IsTupleType && !type.TupleElementNames.IsDefault))
                 {
-                    diagnostics.Add(ErrorCode.ERR_AttrDependentTypeNotAllowed, errorLocation, topLevelType.ToDisplayString(SymbolDisplayFormat.CSharpShortErrorMessageFormat));
+                    diagnostics.Add(ErrorCode.ERR_AttrDependentTypeNotAllowed, errorLocation, type);
+                    return true;
+                }
+
+                if (type.IsUnboundGenericType() && type.Kind == SymbolKind.TypeParameter)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:1369]: >&& [](http://example.com/codeflow?start=48&length=2)

The use of ```&&``` here looks incorrect

**Comment by AlekseyTs** [comment]
Done with review pass (commit 14)

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 15)
