### PR TITLE
Fix Extract Method operations within an event accessor

### LINKED ISSUE #17474: InvalidCastException at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpSelectionResult.StatementResult.GetContainingScopeType
**Version Used**: 
D15Rel 26226.0

**Steps to Reproduce**:
1. Restore, build and open Roslyn.sln
2. Open source file: `\src\EditorFeatures\Core\Implementation\Classification\SemanticClassificationBufferTaggerProvider.Tagger.cs` and enter the following code at end of the file:
  ```
namespace NewTaggerNamespace
{
    internal partial class NewTagger : IAccurateTagger<IClassificationTag>
    {
        public event EventHandler<SnapshotSpanEventArgs> TagsChanged;

        event EventHandler<SnapshotSpanEventArgs> ITagger<IClassificationTag>.TagsChanged
        {
            add
            {
                throw new NotImplementedException();
            }

            remove
            {
                throw new NotImplementedException();
            }
        }

        public IEnumerable<ITagSpan<IClassificationTag>> GetAllTags(NormalizedSnapshotSpanCollection spans, CancellationToken cancel)
        {
            throw new NotImplementedException();
        }

        IEnumerable<ITagSpan<IClassificationTag>> ITagger<IClassificationTag>.GetTags(NormalizedSnapshotSpanCollection spans)
        {
            throw new NotImplementedException();
        }
    }
}
  ```
3. Select text `throw new NotImplementedException();` in the add or remove handler.

Got the following exception in the info bar:

```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.SourceCustomEventSymbol' to type 'Microsoft.CodeAnalysis.IPropertySymbol'.
   at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpSelectionResult.StatementResult.GetContainingScopeType()
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.CodeGenerator`3.AddReturnIfUnreachable(IEnumerable`1 statements,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.CreateStatementsOrInitializerToInsertAtCallSiteAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpCodeGenerator.GenerateBodyForCallSiteContainerAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.CodeGenerator`3.GenerateAsync[TStatement,TExpression,TNodeUnderContainer](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

### LINKED ISSUE #19136: ExtractMethodCodeRefactoringProvider crashed with InvalidOperationException
VS Build: 26426.1 VSUWPT

Note same code that crashed: https://github.com/dotnet/roslyn/issues/19135.

``` C#
// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

using System;
using Microsoft.VisualStudio.ProjectSystem.VS;

namespace Microsoft.VisualStudio.Shell.Interop
{
    internal static class IVsOutputWindowExtensions
    {
        public static void ActivatePane(this IVsOutputWindow outputWindow, Guid pane)
        {
            Requires.NotNull(outputWindow, nameof(outputWindow));
            Requires.NotEmpty(pane, nameof(pane));

            HResult hr = outputWindow.GetPane(ref $pane$, out IVsOutputWindowPane pane);
            if (!hr.IsOK) // Pane not found
                return;

            hr = pane.Activate();
            if (hr.Failed)
                throw hr.Exception;
        }
    }
}
```

```
System.InvalidOperationException : Unexpected false
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition,String message)
   at Microsoft.CodeAnalysis.ExtractMethod.ExtractMethodMatrix.GetVariableStyle(Boolean captured,Boolean dataFlowIn,Boolean dataFlowOut,Boolean alwaysAssigned,Boolean variableDeclared,Boolean readInside,Boolean writtenInside,Boolean readOutside,Boolean writtenOutside,Boolean unsafeAddressTaken)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GetVariableStyle(Dictionary`2 symbolMap,ISymbol symbol,SemanticModel model,ITypeSymbol type,Boolean captured,Boolean dataFlowIn,Boolean dataFlowOut,Boolean alwaysAssigned,Boolean variableDeclared,Boolean readInside,Boolean writtenInside,Boolean readOutside,Boolean writtenOutside,Boolean unsafeAddressTaken)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GenerateVariableInfoMap(SemanticModel model,DataFlowAnalysis dataFlowAnalysisData,Dictionary`2 symbolMap)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.AnalyzeAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #17474
Closes #19136

## Ask Mode

**Customer scenario**

Uses the light bulb while a selection is present in certain code. A non-fatal exception occurs in the Extract Method refactoring and the gold bar appears.

**Bugs this fixes:**

Fixes #17474
Closes #19136 (the behavior is sub-optimal, but a proper solution can wait for #19958) 

**Workarounds, if any**

None

**Risk**

Low. The changed code paths only affect the failing scenario.

**Performance impact**

This change should not have any impact on performance.

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

* Failure to test all code constructs
* Failure to account for erroneous code in testing

**How was the bug found?**

Internal customer report

### CODE REVIEW

**Comment by sharwell** [comment]
@dotnet/roslyn-ide for review

File: src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs [hunk 1]
```diff
@@ -10079,6 +10079,157 @@ public class Class1
...
+        {{
+            throw new NotImplementedException();
+        }}
+    }}
+}}";
+
+            await TestExtractMethodAsync(code, expected);
+        }
+
+        [Fact]
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs]: we usually keep Fact+Trait together.

File: src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.StatementResult.cs [hunk 2]
```diff
@@ -71,13 +71,23 @@ public override ITypeSymbol GetContainingScopeType()
...
+                        switch (semanticModel.GetDeclaredSymbol(access.Parent.Parent))
+                        {
+                            case IPropertySymbol propertySymbol:
+                                return propertySymbol.Type;
+
+                            case IEventSymbol eventSymbol:
+                                return eventSymbol.Type;
+
+                            default:
+                                return null;
```
Comment (Pilchie) [inline src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.StatementResult.cs]: Should there be an assert or a throw Unreachable?

Comment (sharwell) [inline src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.StatementResult.cs]: I was taking the approach of the lines above.

File: src/Features/Core/Portable/ExtractMethod/ExtractMethodMatrix.cs [hunk 3]
```diff
@@ -73,6 +73,13 @@ static ExtractMethodMatrix()
                 {
                     key = new Key(dataFlowIn, /*dataFlowOut*/ true, alwaysAssigned, variableDeclared, readInside, writtenInside, readOutside, writtenOutside);
                 }
+
+                // interesting case in invalid code (bug #19136)
```
Comment (dpoeschl) [inline src/Features/Core/Portable/ExtractMethod/ExtractMethodMatrix.cs]: Should we link to the actual bug since bug numbers are ambiguous in isolation?

Comment (sharwell) [inline src/Features/Core/Portable/ExtractMethod/ExtractMethodMatrix.cs]: Here I was taking the approach of a few lines above as well. Since the issue is also linked in the commit message (git blame), I could see this going either way.

File: src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs (hunk 1 above)
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs]: Fixed

**Comment by sharwell** [comment]
@MattGertz for ask mode
