### PR TITLE
Disallow UseConditionalExpression with unsafe or checked/unchecked blocks

### LINKED ISSUE #70750: When automatically converting an "if" statement into a conditional expression using the C# editor, unintended conversion may occur.
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/When-automatically-converting-an-if-st/10510564)._

---
[severity:It bothers me. A fix would be nice]
### [Overview]
When you automatically convert an `if` statement to a conditional expression in VisualStudio's C# editor, code that behaves differently from the code that is converted may be generated.

### [Execution environment]

- OS: Windows 10 64bit
- Visual Studio: Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.7.6
- .NET Runtime: 6.0.24 and 7.0.13

### [Sample code]

```csharp
using System;
using System.Diagnostics.CodeAnalysis;

namespace Experiment01
{
    internal class Program
    {
        [SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>")]
        private static int Main(string[] args)
        {
            Console.WriteLine(Subtract(int.MaxValue, int.MinValue));
            return 0;
        }

        private static int Subtract(int x, int y)
        {
            if (x < 0) // If you select "Quick actions and refactoring..." and then "Convert to conditional expression" in this "if" statement, an unintended conversion will occur.
                throw new ArgumentOutOfRangeException(nameof(x));
            checked // A similar problem occurs with "unchecked" or "unsafe" blocks.
            {
                return x - y;
            }
        }
    }
}
```

### [Method of operation]
1. Select "Quick actions and refactoring..." in the `if` part of `if (x < 0)` on line 17.
2. Also select “Convert to conditional expression”.

### [Expected results]
The corresponding "if" statement cannot be converted to a conditional expression.

### [Actual results]
The `Subtract` method has been converted as follows.

```csharp
        private static int Subtract(int x, int y)
        {
            return x < 0 ? throw new ArgumentOutOfRangeException(nameof(x)) : x - y;
            checked // A similar problem occurs with "unchecked" or "unsafe" blocks.
            {
            }
        }
```

### Reproducibility
This problem will definitely reappear.

### [Problem]
The code (`x - y`) that should originally be executed inside the `checked` block is now executed outside the `checked` block.
Note that similar problems seem to occur not only with `checked` blocks, but also with `unchecked` or `unsafe` blocks.

#### `.editorconfig` file of the sample program solution

```ini
root = true

[*.cs]

indent_size = 4
indent_style = space
tab_width = 4

end_of_line = crlf
insert_final_newline = false

dotnet_separate_import_directive_groups = false
dotnet_sort_system_directives_first = true
file_header_template = unset

dotnet_style_qualification_for_event = false:suggestion
dotnet_style_qualification_for_field = false
dotnet_style_qualification_for_method = false:suggestion
dotnet_style_qualification_for_property = false:suggestion

dotnet_style_predefined_type_for_locals_parameters_members = true:suggestion
dotnet_style_predefined_type_for_member_access = true:suggestion

dotnet_style_parentheses_in_arithmetic_binary_operators = never_if_unnecessary:suggestion
dotnet_style_parentheses_in_other_binary_operators = never_if_unnecessary:suggestion
dotnet_style_parentheses_in_other_operators = never_if_unnecessary:suggestion
dotnet_style_parentheses_in_relational_binary_operators = always_for_clarity:warning

dotnet_style_require_accessibility_modifiers = for_non_interface_members

dotnet_style_coalesce_expression = true
dotnet_style_collection_initializer = true:warning
dotnet_style_explicit_tuple_names = true:warning
dotnet_style_namespace_match_folder = true
dotnet_style_null_propagation = true
dotnet_style_object_initializer = true:warning
dotnet_style_operator_placement_when_wrapping = beginning_of_line
dotnet_style_prefer_auto_properties = true:suggestion
dotnet_style_prefer_compound_assignment = true
dotnet_style_prefer_conditional_expression_over_assignment = true:suggestion
dotnet_style_prefer_conditional_expression_over_return = true:suggestion
dotnet_style_prefer_foreach_explicit_cast_in_source = when_strongly_typed
dotnet_style_prefer_inferred_anonymous_type_member_names = true
dotnet_style_prefer_inferred_tuple_names = true
dotnet_style_prefer_is_null_check_over_reference_equality_method = true:warning
dotnet_style_prefer_simplified_boolean_expressions = false:warning
dotnet_style_prefer_simplified_interpolation = true:suggestion

dotnet_style_readonly_field = true:warning

dotnet_code_quality_unused_parameters = all

dotnet_remove_unnecessary_suppression_exclusions = none

dotnet_style_allow_multiple_blank_lines_experimental = false:warning
dotnet_style_allow_statement_immediately_after_block_experimental = false:suggestion

csharp_style_var_elsewhere = true
csharp_style_var_for_built_in_types = true
csharp_style_var_when_type_is_apparent = true

csharp_style_expression_bodied_accessors = true:suggestion
csharp_style_expression_bodied_constructors = false:suggestion
csharp_style_expression_bodied_indexers = true:suggestion
csharp_style_expression_bodied_lambdas = true:suggestion
csharp_style_expression_bodied_local_functions = true:suggestion
csharp_style_expression_bodied_methods = true:suggestion
csharp_style_expression_bodied_operators = true:suggestion
csharp_style_expression_bodied_properties = true:suggestion

csharp_style_pattern_matching_over_as_with_null_check = true
csharp_style_pattern_matching_over_is_with_cast_check = true
csharp_style_prefer_extended_property_pattern = true
csharp_style_prefer_not_pattern = true
csharp_style_prefer_pattern_matching = true:suggestion
csharp_style_prefer_switch_expression = true:warning

csharp_style_conditional_delegate_call = true

csharp_prefer_static_local_function = true
csharp_preferred_modifier_order = public,private,protected,internal,file,static,extern,new,virtual,abstract,sealed,override,readonly,unsafe,required,volatile,async
csharp_style_prefer_readonly_struct = true
csharp_style_prefer_readonly_struct_member = true

csharp_prefer_braces = when_multiline:warning
csharp_prefer_simple_using_statement = true
csharp_style_namespace_declarations = block_scoped:warning
csharp_style_prefer_method_group_conversion = false:warning
csharp_style_prefer_primary_constructors = true
csharp_style_prefer_top_level_statements = false:warning

csharp_prefer_simple_default_expression = true
csharp_style_deconstructed_variable_declaration = true
csharp_style_implicit_object_creation_when_type_is_apparent = true
csharp_style_inlined_variable_declaration = true
csharp_style_prefer_index_operator = true
csharp_style_prefer_local_over_anonymous_function = true
csharp_style_prefer_null_check_over_type_check = true:warning
csharp_style_prefer_range_operator = true
csharp_style_prefer_tuple_swap = true:warning
csharp_style_prefer_utf8_string_literals = true
csharp_style_throw_expression = true
csharp_style_unused_value_assignment_preference = discard_variable
csharp_style_unused_value_expression_statement_preference = discard_variable:suggestion

csharp_using_directive_placement = outside_namespace:warning

csharp_style_allow_blank_line_after_colon_in_constructor_initializer_experimental = false:warning
csharp_style_allow_blank_line_after_token_in_arrow_expression_clause_experimental = false:warning
csharp_style_allow_blank_line_after_token_in_conditional_expression_experimental = false:warning
csharp_style_allow_blank_lines_between_consecutive_braces_experimental = false:warning
csharp_style_allow_embedded_statements_on_same_line_experimental = false:warning

csharp_new_line_before_catch = true
csharp_new_line_before_else = true
csharp_new_line_before_finally = true
csharp_new_line_before_members_in_anonymous_types = true
csharp_new_line_before_members_in_object_initializers = true
csharp_new_line_before_open_brace = all
csharp_new_line_between_query_expression_clauses = true

csharp_indent_block_contents = true
csharp_indent_braces = false
csharp_indent_case_contents = true
csharp_indent_case_contents_when_block = false
csharp_indent_labels = one_less_than_current
csharp_indent_switch_labels = true

csharp_space_after_cast = false
csharp_space_after_colon_in_inheritance_clause = true
csharp_space_after_comma = true
csharp_space_after_dot = false
csharp_space_after_keywords_in_control_flow_statements = true
csharp_space_after_semicolon_in_for_statement = true
csharp_space_around_binary_operators = before_and_after
csharp_space_around_declaration_statements = false
csharp_space_before_colon_in_inheritance_clause = true
csharp_space_before_comma = false
csharp_space_before_dot = false
csharp_space_before_open_square_brackets = false
csharp_space_before_semicolon_in_for_statement = false
csharp_space_between_empty_square_brackets = false
csharp_space_between_method_call_empty_parameter_list_parentheses = false
csharp_space_between_method_call_name_and_opening_parenthesis = false
csharp_space_between_method_call_parameter_list_parentheses = false
csharp_space_between_method_declaration_empty_parameter_list_parentheses = false
csharp_space_between_method_declaration_name_and_open_parenthesis = false
csharp_space_between_method_declaration_parameter_list_parentheses = false
csharp_space_between_parentheses = false
csharp_space_between_square_brackets = false

csharp_preserve_single_line_blocks = true
csharp_preserve_single_line_statements = false

dotnet_naming_rule.interface_should_be_begins_with_i.severity = suggestion
dotnet_naming_rule.interface_should_be_begins_with_i.symbols = interface
dotnet_naming_rule.interface_should_be_begins_with_i.style = begins_with_i

dotnet_naming_rule.types_should_be_pascal_case.severity = suggestion
dotnet_naming_rule.types_should_be_pascal_case.symbols = types
dotnet_naming_rule.types_should_be_pascal_case.style = pascal_case

dotnet_naming_rule.non_field_members_should_be_pascal_case.severity = suggestion
dotnet_naming_rule.non_field_members_should_be_pascal_case.symbols = non_field_members
dotnet_naming_rule.non_field_members_should_be_pascal_case.style = pascal_case

dotnet_naming_symbols.interface.applicable_kinds = interface
dotnet_naming_symbols.interface.applicable_accessibilities = public, internal, private, protected, protected_internal, private_protected
dotnet_naming_symbols.interface.required_modifiers = 

dotnet_naming_symbols.types.applicable_kinds = class, struct, interface, enum
dotnet_naming_symbols.types.applicable_accessibilities = public, internal, private, protected, protected_internal, private_protected
dotnet_naming_symbols.types.required_modifiers = 

dotnet_naming_symbols.non_field_members.applicable_kinds = property, event, method
dotnet_naming_symbols.non_field_members.applicable_accessibilities = public, internal, private, protected, protected_internal, private_protected
dotnet_naming_symbols.non_field_members.required_modifiers = 

dotnet_naming_style.pascal_case.required_prefix = 
dotnet_naming_style.pascal_case.required_suffix = 
dotnet_naming_style.pascal_case.word_separator = 
dotnet_naming_style.pascal_case.capitalization = pascal_case

dotnet_naming_style.begins_with_i.required_prefix = I
dotnet_naming_style.begins_with_i.required_suffix = 
dotnet_naming_style.begins_with_i.word_separator = 
dotnet_naming_style.begins_with_i.capitalization = pascal_case
```

---
#### Feedback Bot on 11/8/2023, 08:50 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by sdelarosbil**
Closes #70750 

As it says on the thin. To note, I did checked to see how hard it would be to wrap the statement to an expression in the case of checked/unchecked and I found it would require some refactor I am not sure on how to do so I opted to disallow them for now.

### CODE REVIEW

File: src/Analyzers/CSharp/Analyzers/UseConditionalExpression/CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -21,5 +22,41 @@ public CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer()
...
+
+        protected override (bool matched, bool canSimplify) TryMatchPattern(IConditionalOperation ifOperation, ISymbol containingSymbol)
+        {
+            if (!UseConditionalExpressionForReturnHelpers.TryMatchPattern(
+                    GetSyntaxFacts(), ifOperation, containingSymbol, out var isRef, out var trueStatement, out var falseStatement, out var trueReturn, out var falseReturn))
+            {
+                return default;
+            }
+
+            if (IsWrappedByCheckedOrUnsafe(trueStatement) ||
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/UseConditionalExpression/CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer.cs:34]: doc.

File: src/Analyzers/CSharp/Analyzers/UseConditionalExpression/CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer.cs [hunk 2]
```diff
@@ -21,5 +22,41 @@ public CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer()
...
+            return (matched: true, canSimplify);
+        }
+
+        private static bool IsWrappedByCheckedOrUnsafe(IOperation trueStatement)
+        {
+            if (trueStatement is not IReturnOperation { Parent: IBlockOperation block })
+                return false;
+
+            if (block.Syntax.Parent is UnsafeStatementSyntax)
+                return true;
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/UseConditionalExpression/CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer.cs:55]:
```suggestion
                return true;
                
```

Comment (sdelarosbil) [reply src/Analyzers/CSharp/Analyzers/UseConditionalExpression/CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer.cs:56]: Dome

File: src/Analyzers/CSharp/Analyzers/UseConditionalExpression/CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer.cs (hunk 1 above)
Comment (sdelarosbil) [reply src/Analyzers/CSharp/Analyzers/UseConditionalExpression/CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer.cs:35]: Done.

File: src/Analyzers/CSharp/Analyzers/UseConditionalExpression/CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer.cs [hunk 3]
```diff
@@ -21,5 +22,43 @@ public CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer()
...
+                return default;
+            }
+
+            var canSimplify = UseConditionalExpressionHelpers.CanSimplify(
+                trueReturn?.ReturnedValue ?? trueStatement,
+                falseReturn?.ReturnedValue ?? falseStatement,
+                isRef,
+                out _);
+
+            return (matched: true, canSimplify);
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/UseConditionalExpression/CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer.cs:47]: this looks to be repeating what's in teh base.  Can you instead just call into the base, and *if* it matches, you then do the additional checks?

alternatively, have the base method be selaed, but which calls into a new virtual method (that is passed the true/false statements) that you can then check?

Comment (sdelarosbil) [reply src/Analyzers/CSharp/Analyzers/UseConditionalExpression/CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer.cs]: Done, did the latter.

File: src/Analyzers/Core/Analyzers/UseConditionalExpression/ForReturn/AbstractUseConditionalExpressionForReturnDiagnosticAnalyzer.cs [hunk 4]
```diff
@@ -41,5 +44,10 @@ protected override (bool matched, bool canSimplify) TryMatchPattern(IConditional
 
             return (matched: true, canSimplify);
         }
+
+        protected virtual bool AreStatementsSupported(IOperation trueStatement, IOperation falseStatement)
+        {
+            return true;
+        }
```
Comment (CyrusNajmabadi) [inline src/Analyzers/Core/Analyzers/UseConditionalExpression/ForReturn/AbstractUseConditionalExpressionForReturnDiagnosticAnalyzer.cs:51]:
```suggestion
        protected virtual bool AreStatementsSupported(IOperation trueStatement, IOperation falseStatement)
            => true;
```

File: src/Analyzers/CSharp/Analyzers/UseConditionalExpression/CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer.cs [hunk 5]
```diff
@@ -21,5 +22,25 @@ public CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer()
...
         protected override ISyntaxFacts GetSyntaxFacts()
             => CSharpSyntaxFacts.Instance;
+
+        protected override bool AreStatementsSupported(IOperation trueStatement, IOperation falseStatement)
+        {
+            // Return statements wrapped in an unsafe, checked or unchecked block are not supported
+            return !IsWrappedByCheckedOrUnsafe(trueStatement) && !IsWrappedByCheckedOrUnsafe(falseStatement);
+        }
+
+        private static bool IsWrappedByCheckedOrUnsafe(IOperation trueStatement)
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/UseConditionalExpression/CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer.cs:32]:
```suggestion
        private static bool IsWrappedByCheckedOrUnsafe(IOperation statement)
```

File: src/Analyzers/CSharp/Analyzers/UseConditionalExpression/CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer.cs [hunk 6]
```diff
@@ -21,5 +22,25 @@ public CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer()
...
+        {
+            if (trueStatement is not IReturnOperation { Parent: IBlockOperation block })
+                return false;
+
+            if (block.Syntax.Parent is UnsafeStatementSyntax)
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/UseConditionalExpression/CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer.cs:37]:
```suggestion
            if (block.Syntax.Parent is UnsafeStatementSyntax or CheckedStatementSyntax)
```

File: src/Analyzers/CSharp/Analyzers/UseConditionalExpression/CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer.cs [hunk 7]
```diff
@@ -21,5 +22,25 @@ public CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer()
 
         protected override ISyntaxFacts GetSyntaxFacts()
             => CSharpSyntaxFacts.Instance;
+
+        protected override bool AreStatementsSupported(IOperation trueStatement, IOperation falseStatement)
+        {
+            // Return statements wrapped in an unsafe, checked or unchecked block are not supported
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/UseConditionalExpression/CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer.cs:28]: so, this is just a statement of what the code is doing.  Consider instead saying why.

File: src/Analyzers/Core/Analyzers/UseConditionalExpression/ForReturn/AbstractUseConditionalExpressionForReturnDiagnosticAnalyzer.cs [hunk 8]
```diff
@@ -25,14 +25,17 @@ internal abstract class AbstractUseConditionalExpressionForReturnDiagnosticAnaly
...
+        protected sealed override (bool matched, bool canSimplify) TryMatchPattern(IConditionalOperation ifOperation, ISymbol containingSymbol)
         {
             if (!UseConditionalExpressionForReturnHelpers.TryMatchPattern(
                     GetSyntaxFacts(), ifOperation, containingSymbol, out var isRef, out var trueStatement, out var falseStatement, out var trueReturn, out var falseReturn))
             {
                 return default;
             }
 
+            if (!AreStatementsSupported(trueStatement, falseStatement))
+                return default;
```
Comment (CyrusNajmabadi) [inline src/Analyzers/Core/Analyzers/UseConditionalExpression/ForReturn/AbstractUseConditionalExpressionForReturnDiagnosticAnalyzer.cs:37]: nit:

```suggestion
            if (!IsStatementSupported(trueStatement) ||
                !IsStatementSupported(falseStatement))
            {
                return default;
            }
```

**Comment by sdelarosbil** [comment]
@CyrusNajmabadi all done.

**Comment by CyrusNajmabadi** [comment]
Small favor.  Please don't force-push once a review has started.  It makes it much harder.  Just request that when your PR is merged, it is set to "squash" so it only ends up as a single commit.  Thanks!

File: src/Analyzers/CSharp/Analyzers/UseConditionalExpression/CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer.cs [hunk 9]
```diff
@@ -21,5 +22,24 @@ public CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer()
...
+
+        protected override bool IsStatementSupported(IOperation statement)
+        {
+            // Return statements wrapped in an unsafe, checked or unchecked block are not supported
+            // because having these enclosing blocks makes it difficult or impossible to convert
+            // the blocks to expressions
+            return !IsWrappedByCheckedOrUnsafe(statement);
+        }
+
+        private static bool IsWrappedByCheckedOrUnsafe(IOperation statement)
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/UseConditionalExpression/CSharpUseConditionalExpressionForReturnDiagnosticAnalyzer.cs:34]: nit: it would be fine to inline this.
