### PR TITLE
Fix for #8625: allow SyntaxNode.Contains to return quicker in simplest case

### LINKED ISSUE #8625: Possible typo in SyntaxNode.cs found by PVS-Studio static analyzer.
A possible typo\error found by PVS-Studio static analyzer:

From the  roslyn/src/Compilers/Core/Portable/Syntax/SyntaxNode.cs file:

```
        /// <summary>
        /// Determines if the specified node is a descendant of this node.
        /// </summary>
        public bool Contains(SyntaxNode node)
        {
            if (node == null || !node.FullSpan.IntersectsWith(node.FullSpan))
            {
                return false;
            }

            while (node != null)
            {
                if (node == this)
                {
                    return true;
                }

                if (node.Parent != null)
                {
                    node = node.Parent;
                }
                else if (node.IsStructuredTrivia)
                {
                    node = ((IStructuredTriviaSyntax)node).ParentTrivia.Token.Parent;
                }
                else
                {
                    node = null;
                }
            }

            return false;
        }
```
The condition `node.FullSpan.IntersectsWith(node.FullSpan)` should possibly be as follows: `this.FullSpan.IntersectsWith(node.FullSpan)`, otherwise the check is senseless.

### PR DESCRIPTION
**Pull request by jcouv**
There was indeed a typo. 
The behavior change is not observable, except that the method returns quicker.

I validated by stepping through this [test](https://gist.github.com/jcouv/d20e55eb4804b791c7d4).

Fixes #8625.
CC @dotnet/roslyn-compiler for code review.

### CODE REVIEW

File: src/Compilers/Core/Portable/Syntax/SyntaxNode.cs [hunk 1]
```diff
@@ -421,7 +421,7 @@ public bool ContainsDiagnostics
         /// </summary>
         public bool Contains(SyntaxNode node)
         {
-            if (node == null || !node.FullSpan.IntersectsWith(node.FullSpan))
+            if (node == null || !this.FullSpan.IntersectsWith(node.FullSpan))
```
Comment (cston) [inline src/Compilers/Core/Portable/Syntax/SyntaxNode.cs]: `IntersectsWith` returns true if the end point of one span matches the start of the other. Consider using ```this.FullSpan.Contains(node.FullSpan)``` instead.

Comment (cston) [inline src/Compilers/Core/Portable/Syntax/SyntaxNode.cs]: Can the method body be replaced with the following?
```
return this.FullSpan.Contains(node.FullSpan) && this.SyntaxTree == node.SyntaxTree;
```

Comment (jcouv) [inline src/Compilers/Core/Portable/Syntax/SyntaxNode.cs]: I think so. 
I was wondering about this too, and the only case where Span comparison wouldn't work is if the nodes aren't in the same tree. I didn't realize there is an easy way to check that.
I'll make the change.

Comment (jcouv) [inline src/Compilers/Core/Portable/Syntax/SyntaxNode.cs]: From our discussion, I will leave as-is, as the current implementation may be more performant. 
It only partially walks up one tree, while calling `SyntaxTree` walks all the way up the tree (when that property wasn't cached) and we do it twice.

Comment (VSadov) [inline src/Compilers/Core/Portable/Syntax/SyntaxNode.cs]: Also it seems that Contains implies that node "is or a child of" this. If you compare trees, it would seem either could be a parent of another.

Comment (VSadov) [inline src/Compilers/Core/Portable/Syntax/SyntaxNode.cs]: I think we might need a test to guard the above assumption.

Comment (cston) [inline src/Compilers/Core/Portable/Syntax/SyntaxNode.cs]: I agree `Contains` implies parent/child, I'd missed that aspect. Given that and the potential performance difference @jcouv mentioned, it makes sense to leave the `while` loop as is.

**Comment by AlekseyTs** [comment]
LGTM

**Comment by gafter** [comment]
LGTM
