### PR TITLE
Insert documentation comments only on supported declarations

### LINKED ISSUE #59081: Typing `///` in top-level statements inserts a documentation comment template
**Version Used**: `Compiler version: '4.1.0-3.22062.11 (cc0d213b)'. Language version: 10.0.` (Visual Studio 17.1.0 preview 4.0)

**Steps to Reproduce**:

1. Create a new console project and populate `Program.cs` as follows:

```csharp

Console.WriteLine("Hello, World!");

Console.WriteLine("Hello, World!");
```

2. Type `///` in the at the end of any line

**Expected Behavior**:

`///` is inserted with no special behavior. (Same as in normal method bodies.)

**Actual Behavior**:

A documentation comment template is erroneously generated:

image

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #59081

### CODE REVIEW

**Review by CyrusNajmabadi — APPROVED** [review]
interesting.  i'm curious if this breaks anything.

File: src/EditorFeatures/CSharpTest/DocumentationComments/DocumentationCommentTests.cs [hunk 1]
```diff
@@ -706,6 +706,26 @@ public void TypingCharacter_NotInsideCtor()
...
+
+            var expected = @"
+using System;
+
+///$$
+Console.WriteLine();
+";
+
+            VerifyTypingCharacter(code, expected);
+        }
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/DocumentationComments/DocumentationCommentTests.cs:727]: consider adding a test for namespaces too.

**Review by RikkiGibson — APPROVED** [review]

**Review by sharwell — APPROVED** [review]

File: src/EditorFeatures/CSharpTest/DocumentationComments/DocumentationCommentTests.cs (hunk 1 above)
Comment (sharwell) [reply src/EditorFeatures/CSharpTest/DocumentationComments/DocumentationCommentTests.cs:728]: ➡️ This test is now added
