### PR TITLE
Handle ForEach statement in control flow graph

### LINKED ISSUE #26112: 'For Each' over multi-dimensional array doesn't apply proper conversion for an element of the array
Try to compile this code:
```
Namespace ForEach
    NotInheritable Class C

        Shared Sub Main()
            For Each z As C In New Integer(,) {{0}}
            Next
        End Sub

'        Public Shared Widening Operator CType(x As Integer) As C
'            System.Console.WriteLine("CType")
'            Return Nothing
'        End Operator
    End Class
End Namespace
```

Observed and Expected:
```
error BC30311: Value of type 'Integer' cannot be converted to 'C'.

            For Each z As C In New Integer(,) {{0}}
                               ~~~~~~~~~~~~~~~~~~~~
```

Now uncomment user-defined conversion and try again
Observed:
1. Compilation succeeds
2. An exception is thrown at runtime:
```
Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'ForEach.C'.
   at ForEach.C.Main()
```

Expected:
Execution should succeed, the user-defined conversion operator should be called.

Here is IL that we produce:
```
.method public static void  Main() cil managed
{
  .entrypoint
  .custom instance void [mscorlib]System.STAThreadAttribute::.ctor() = ( 01 00 00 00 ) 
  // Code size       40 (0x28)
  .maxstack  2
  .locals init (class [mscorlib]System.Collections.IEnumerator V_0,
           class ForEach.C V_1,
           bool V_2)
  IL_0000:  nop
  IL_0001:  ldc.i4.1
  IL_0002:  ldc.i4.1
  IL_0003:  newobj     instance void int32[0...,0...]::.ctor(int32,
                                                             int32)
  IL_0008:  call       instance class [mscorlib]System.Collections.IEnumerator [mscorlib]System.Array::GetEnumerator()
  IL_000d:  stloc.0
  IL_000e:  br.s       IL_001d
  IL_0010:  ldloc.0
  IL_0011:  callvirt   instance object [mscorlib]System.Collections.IEnumerator::get_Current()
  IL_0016:  castclass  ForEach.C
  IL_001b:  stloc.1
  IL_001c:  nop
  IL_001d:  ldloc.0
  IL_001e:  callvirt   instance bool [mscorlib]System.Collections.IEnumerator::MoveNext()
  IL_0023:  stloc.2
  IL_0024:  ldloc.2
  IL_0025:  brtrue.s   IL_0010
  IL_0027:  ret
} // end of method C::Main
``` 

Note that result of System.Collections.IEnumerator::get_Current() is converted directly to ```C``` (castclass  ForEach.C). Instead it should be converted to int and then converted to ```C``` by using user-defined conversion operator. 

The same broken behavior is in native compiler.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Also, fixed #26112 - a bug in VB compiler around For Each over multi-dimensional arrays

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@333fred, @mavasani, @cston, @dotnet/roslyn-compiler, @dotnet/analyzer-ioperation Please review.

**Comment by AlekseyTs** [comment]
@333fred, @mavasani, @cston, @dotnet/roslyn-compiler, @dotnet/analyzer-ioperation Please review.

File: src/Compilers/Core/Portable/Operations/ForEachLoopOperationInfo.cs [hunk 1]
```diff
@@ -0,0 +1,62 @@
+﻿// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
+
+using System;
+using System.Collections.Immutable;
+
+namespace Microsoft.CodeAnalysis.Operations
+{
+    internal struct ForEachLoopOperationInfo
```
Comment (333fred) [inline src/Compilers/Core/Portable/Operations/ForEachLoopOperationInfo.cs]: Is this something we want to consider exposing publicly? At least some of this info might be useful, like the enumerator info.

Comment (AlekseyTs) [reply src/Compilers/Core/Portable/Operations/ForEachLoopOperationInfo.cs]: > Is this something we want to consider exposing publicly? At least some of this info might be useful, like the enumerator info.

That is for IOIperation team to decide. I am not planning to expose any of this information publicly under umbrella of CFG work

---
In reply to: [181822345](https://github.com/dotnet/roslyn/pull/26158#discussion_r181822345) [](ancestors = 181822345)

Comment (333fred) [reply src/Compilers/Core/Portable/Operations/ForEachLoopOperationInfo.cs]: Can you open an issue to track that?

---
In reply to: [181826224](https://github.com/dotnet/roslyn/pull/26158#discussion_r181826224) [](ancestors = 181826224,181822345)

Comment (AlekseyTs) [reply src/Compilers/Core/Portable/Operations/ForEachLoopOperationInfo.cs]: > Can you open an issue to track that?

[https://github.com/dotnet/roslyn/issues/26176](https://github.com/dotnet/roslyn/issues/26176)

---
In reply to: [181826481](https://github.com/dotnet/roslyn/pull/26158#discussion_r181826481) [](ancestors = 181826481,181826224,181822345)

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IForEachLoopStatement.cs [hunk 2]
```diff
@@ -1417,5 +1418,2063 @@ void M(object o)
...
+        [Fact]
+        public void ForEachFlow_12()
+        {
+            string source = @"
+public class MyClass
+{
+    void M(MyClass e, int result)
+    /*<bind>*/{
+        foreach (var x in e)
+        {
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IForEachLoopStatement.cs]: >  [](start = 9, length = 1)

Nit: A lot of these tests appear to have some extra whitespace.

File: src/Compilers/VisualBasic/Portable/Symbols/Source/LocalSymbol.vb [hunk 3]
```diff
@@ -664,31 +664,21 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols
...
-                                                       elementType,
-                                                       isEnumerable,
-                                                       boundGetEnumeratorCall,
-                                                       boundEnumeratorPlaceholder,
-                                                       boundMoveNextCall,
-                                                       boundCurrentCall,
-                                                       collectionPlaceholder,
-                                                       needToDispose,
-                                                       isOrInheritsFromOrImplementsIDisposable,
+                                                       collectionExpression:=Nothing,
```
Comment (333fred) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/LocalSymbol.vb]: I don't see any functional changes in this file? Consider reverting changes.

Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Portable/Symbols/Source/LocalSymbol.vb]: > I don't see any functional changes in this file? Consider reverting changes.

There are functional changes here.

---
In reply to: [181876878](https://github.com/dotnet/roslyn/pull/26158#discussion_r181876878) [](ancestors = 181876878)

File: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs [hunk 4]
```diff
@@ -2364,44 +2363,56 @@ void processResource(IOperation resource, ArrayBuilder<(IVariableDeclarationOper
...
-                AppendNewBlock(endOfFinally);
+            EnterRegion(new RegionBuilder(ControlFlowGraph.RegionKind.Finally));
+            AppendNewBlock(new BasicBlock(BasicBlockKind.Block));
 
-                LeaveRegion();
-                Debug.Assert(_currentRegion.Kind == ControlFlowGraph.RegionKind.TryAndFinally);
-                LeaveRegion();
+            if (!knownToImplementIDisposable)
+            {
+                Debug.Assert(!(resource.Type?.IsValueType == true && !ITypeSymbolHelpers.IsNullableType(resource.Type)));
```
Comment (333fred) [inline src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: All the inversions in this assert make it very complicated to read and reason about simply. Please simplify it.

Comment (333fred) [reply src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: Or consider making a helper, as this condition is used multiple times.

---
In reply to: [181883394](https://github.com/dotnet/roslyn/pull/26158#discussion_r181883394) [](ancestors = 181883394)

Comment (AlekseyTs) [reply src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: > All the inversions in this assert make it very complicated to read and reason about simply. Please simplify it.

Inversion is not trivial when dealing with nullable values. 

---
In reply to: [181883394](https://github.com/dotnet/roslyn/pull/26158#discussion_r181883394) [](ancestors = 181883394)

File: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs [hunk 5]
```diff
@@ -2593,6 +2607,208 @@ public override IOperation VisitLock(ILockOperation operation, int? captureIdFor
...
+
+            ForEachLoopOperationInfo info = ((BaseForEachLoopStatement)operation).Info;
+
+            bool haveLocals = !operation.Locals.IsEmpty;
+            bool createdRegionForCollection = false;
+
+            if (haveLocals && operation.LoopControlVariable.Kind == OperationKind.VariableDeclarator)
+            {
+                // VB has rather interesting scoping rules for control variable.
+                // It is in scope in collection expression. However, it is considered to be
```
Comment (333fred) [inline src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: >  [](start = 36, length = 1)

Typo: missing `the`

Comment (333fred) [reply src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: And again 2 lines down

---
In reply to: [181888492](https://github.com/dotnet/roslyn/pull/26158#discussion_r181888492) [](ancestors = 181888492)

**Comment by 333fred** [comment]
Done with review pass (Iteration 1)

**Review by 333fred — APPROVED** [review]
LGTM (suggestions can be in a follow up)

**Comment by AlekseyTs** [comment]
@mavasani, @dotnet/analyzer-ioperation Please review.

**Comment by AlekseyTs** [comment]
@cston, @dotnet/roslyn-compiler Please review, need a second review.

**Comment by AlekseyTs** [comment]
@cston, @dotnet/roslyn-compiler Please review, need a second review.

File: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs [hunk 6]
```diff
@@ -2593,6 +2607,208 @@ public override IOperation VisitLock(ILockOperation operation, int? captureIdFor
...
+                // there are two distinct locals, one is used in collection expression and the 
+                // other is used as a loop control variable. This is done to have proper hoisting 
+                // and lifetime in presence of lambdas.
+                // Rather than introducing a separate local symbol, we will simply add another 
+                // lifetime region for that local around the collection expression. 
+
+                var declarator = (IVariableDeclaratorOperation)operation.LoopControlVariable;
+                ILocalSymbol local = declarator.Symbol;
+
+                if (operation.Collection.DescendantsAndSelf().OfType<ILocalReferenceOperation>().Where(l => l.Local.Equals(local)).Any())
```
Comment (cston) [inline src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: >OfType<ILocalReferenceOperation>().Where(l => l.Local.Equals(local)).Any() [](start = 62, length = 74)

Consider merging some of these. Perhaps: `Any(d => d is ILocalReferenceOperation l && l.Local.Equals(local))`

File: src/Compilers/Core/Portable/Operations/ForEachLoopOperationInfo.cs (hunk 1 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/Operations/ForEachLoopOperationInfo.cs]: Adding @heejaechang @ivanbasov @CyrusNajmabadi - I believe this is very useful semantic information, which can be very valuable for foreach loop refactorings written by these folks.

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IForEachLoopStatement.cs [hunk 7]
```diff
@@ -1417,5 +1418,2063 @@ void M(object o)
...
+          Value: 
+            IParameterReferenceOperation: b (OperationKind.ParameterReference, Type: MyClass[]) (Syntax: 'b')
+
+    Next (Regular) Block[B4]
+Block[B4] - Block
+    Predecessors: [B2] [B3]
+    Statements (1)
+        IFlowCaptureOperation: 2 (OperationKind.FlowCapture, Type: null, IsImplicit) (Syntax: 'a ?? b')
+          Value: 
+            IInvocationOperation (virtual System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()) (OperationKind.Invocation, Type: System.Collections.IEnumerator, IsImplicit) (Syntax: 'a ?? b')
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IForEachLoopStatement.cs]: The compiler does not generate a call to `GetEnumerator()` for arrays.

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IForEachLoopStatement.cs [hunk 8]
```diff
@@ -1417,5 +1418,2063 @@ void M(object o)
...
+    }
+}
+.finally {R4}
+{
+    Block[B8] - Block
+        Predecessors (0)
+        Statements (1)
+            IFlowCaptureOperation: 4 (OperationKind.FlowCapture, Type: null, IsImplicit) (Syntax: 'a ?? b')
+              Value: 
+                IConversionOperation (TryCast: True, Unchecked) (OperationKind.Conversion, Type: System.IDisposable, IsImplicit) (Syntax: 'a ?? b')
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IForEachLoopStatement.cs]: `IDisposable` is not used for arrays.

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IForEachLoopStatement.cs (hunk 7 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IForEachLoopStatement.cs]: > The compiler does not generate a call to GetEnumerator() for arrays.

This is an optimization performed by compiler, this rewrite follows language specification.

---
In reply to: [182158151](https://github.com/dotnet/roslyn/pull/26158#discussion_r182158151) [](ancestors = 182158151)

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IForEachLoopStatement.cs [hunk 9]
```diff
@@ -1417,5 +1418,2063 @@ void M(object o)
...
+            string expectedFlowGraph = @"
+Block[B0] - Entry
+    Statements (0)
+    Next (Regular) Block[B1]
+Block[B1] - Block
+    Predecessors: [B0]
+    Statements (1)
+        IFlowCaptureOperation: 0 (OperationKind.FlowCapture, Type: null, IsImplicit) (Syntax: 'a')
+          Value: 
+            IInvocationOperation ( System.CharEnumerator System.String.GetEnumerator()) (OperationKind.Invocation, Type: System.CharEnumerator, IsImplicit) (Syntax: 'a')
```
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IForEachLoopStatement.cs]: > Compiler uses String.Chars property.

This is an optimization performed by compiler, this rewrite follows language specification.

---
In reply to: [182160674](https://github.com/dotnet/roslyn/pull/26158#discussion_r182160674) [](ancestors = 182160674)

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IForEachLoopStatement.cs (hunk 8 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IForEachLoopStatement.cs]: > IDisposable is not used for arrays.

This is an optimization performed by compiler, this rewrite follows language specification.

---
In reply to: [182158402](https://github.com/dotnet/roslyn/pull/26158#discussion_r182158402) [](ancestors = 182158402)

File: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs [hunk 10]
```diff
@@ -2593,6 +2607,208 @@ public override IOperation VisitLock(ILockOperation operation, int? captureIdFor
...
+                    return MakeInvalidOperation(((Operation)operation).SemanticModel.Compilation.GetSpecialType(SpecialType.System_Boolean), enumeratorRef);
+                }
+            }
+
+            IOperation getCurrent(IOperation enumeratorRef)
+            {
+                if (info.CurrentProperty != null)
+                {
+                    return new PropertyReferenceExpression(info.CurrentProperty,
+                                                           info.CurrentProperty.IsStatic ? null : enumeratorRef,
```
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: > Is there a test for this case?

ForEachFlow_22 for VB

---
In reply to: [182162222](https://github.com/dotnet/roslyn/pull/26158#discussion_r182162222) [](ancestors = 182162222)

File: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs [hunk 11]
```diff
@@ -2593,6 +2607,208 @@ public override IOperation VisitLock(ILockOperation operation, int? captureIdFor
...
+                ILocalSymbol local = declarator.Symbol;
+
+                if (operation.Collection.DescendantsAndSelf().OfType<ILocalReferenceOperation>().Where(l => l.Local.Equals(local)).Any())
+                {
+                    EnterRegion(new RegionBuilder(ControlFlowGraph.RegionKind.Locals, locals: ImmutableArray.Create(local)));
+                    createdRegionForCollection = true;
+                }
+            }
+
+            IOperation collection = Visit(operation.Collection);
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: >Visit(operation.Collection); [](start = 36, length = 28)

I think this might preserve some side-effects that should not be preserved for the Shared GetEnumertor scenario, I'll follow up on this.

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IForEachLoopStatement.cs (hunk 8 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IForEachLoopStatement.cs]: It seems incorrect to include a try/finally in the flow graph when there is no try/finally in the generated code.

---
In reply to: [182166241](https://github.com/dotnet/roslyn/pull/26158#discussion_r182166241) [](ancestors = 182166241,182158402)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IForEachLoopStatement.cs]: > It seems incorrect to include a try/finally in the flow graph when there is no try/finally in the generated code.

We will discuss this at the design meeting, but I personally don't see any harm in that for the purpose of flow analysis.  

---
In reply to: [182170874](https://github.com/dotnet/roslyn/pull/26158#discussion_r182170874) [](ancestors = 182170874,182166241,182158402)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IForEachLoopStatement.cs]: This is also consistent with behavior of SemanticModel

---
In reply to: [182172038](https://github.com/dotnet/roslyn/pull/26158#discussion_r182172038) [](ancestors = 182172038,182170874,182166241,182158402)

File: src/Compilers/VisualBasic/Test/Semantic/Semantics/MultiDimensionalTest.vb [hunk 12]
```diff
@@ -1165,25 +1165,38 @@ Test1
...
+              IL_0010:  br.s       IL_0022
+              IL_0012:  ldloc.0
+              IL_0013:  callvirt   "Function System.Collections.IEnumerator.get_Current() As Object"
+              IL_0018:  call       "Function Microsoft.VisualBasic.CompilerServices.Conversions.ToDouble(Object) As Double"
+              IL_001d:  call       "Sub System.Console.WriteLine(Double)"
+              IL_0022:  ldloc.0
+              IL_0023:  callvirt   "Function System.Collections.IEnumerator.MoveNext() As Boolean"
+              IL_0028:  brtrue.s   IL_0012
+              IL_002a:  ret
+            }
```
Comment (cston) [inline src/Compilers/VisualBasic/Test/Semantic/Semantics/MultiDimensionalTest.vb]: Please revert indenting if not needed.

**Review by cston — APPROVED** [review]

**Comment by AlekseyTs** [comment]
Addressed feedback
