### PR TITLE
Name anonymous delegate parameters

### LINKED ISSUE #64436: Empty parameter name reported in error "missing required parameter"
**Version Used**: main (28 Sep 2022)

**Steps to Reproduce**:

```cs
var lam = (int x, ref int y) => { };
lam(1);
```

[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4DcICcAEAbCMHAXhwApYAXHADzhywFMAzHKnATwEoSA+HAN44AvgG4AsACgCYMgEYuooA===)

**Expected Behavior**: Reports something like:

```
error CS7036: There is no argument given that corresponds to the required parameter 2 of '<anonymous delegate>'
```

**Actual Behavior**: Reports error with empty parameter name:

```
error CS7036: There is no argument given that corresponds to the required parameter '' of '<anonymous delegate>'
```

### PR DESCRIPTION
**Pull request by jjonescz**
Fixes #64436.

I have added names to parameters of anonymous delegates, matching parameter names of `System.Func`/`System.Action`.

Alternative (if changing generated code is too much) would be to change the reported diagnostic message only:

https://github.com/dotnet/roslyn/blob/8664540f18958ed79e89adf39ce44a4701082a62/src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolutionResult.cs#L890-L897

This approach is used for CS8347:

https://github.com/dotnet/roslyn/blob/e4667d4dc586d6bbf91ad32d7dd86f1a3971223b/src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs#L13932-L13934

Relates to test plan https://github.com/dotnet/roslyn/issues/52192 (lambda improvements in C# 10)

### CODE REVIEW

**Comment by jcouv** [comment]
I was going to suggest sorting out the language/spec question before discussion implementation strategy. 
It turns out the desired behavior is already described (very close to what you're proposing) but our synthesized delegates are wrong.
The [spec](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-10.0/lambda-improvements.md#delegate-types) says:

> ### Delegate types
> The delegate type for the anonymous function or method group with parameter types `P1, ..., Pn` and return type `R` is:
> - if any parameter or return value is not by value, or there are more than 16 parameters, or any of the parameter types or return are not valid type arguments (say, `(int* p) => { }`), then the delegate is a synthesized `internal` anonymous delegate type with signature that matches the anonymous function or method group, and with parameter names `arg1, ..., argn` or `arg` if a single parameter;
> - if `R` is `void`, then the delegate type is `System.Action<P1, ..., Pn>`;
> - otherwise the delegate type is `System.Func<P1, ..., Pn, R>`.

Note that the case with a single parameter should be `arg`, not `arg1`.

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNames.cs [hunk 1]
```diff
@@ -496,6 +496,12 @@ internal static string LambdaCopyParameterName(int ordinal)
             return "<p" + StringExtensions.GetNumeral(ordinal) + ">";
         }
 
+        internal static string AnonymousDelegateParameterName(int index)
+        {
+            // Consistent with `System.Action` and `System.Func` types.
+            return "arg" + StringExtensions.GetNumeral(index + 1);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNames.cs:502]: We'll want `arg` instead of `arg1` for single parameter case.

File: src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs [hunk 2]
```diff
@@ -10234,6 +10234,17 @@ static void Main()
 ");
         }
 
+        [Fact, WorkItem(64436, "https://github.com/dotnet/roslyn/issues/64436")]
+        public void SynthesizedDelegateTypes_NamedParameters()
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs:10238]: It'd be good to expand this test to cover a bit more of the cases described in "if any parameter or return value is not by value, or there are more than 16 parameters, or any of the parameter types or return are not valid type arguments (say, `(int* p) => { }`)".

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 5)

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNames.cs (hunk 1 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNames.cs:506]: Thanks, I should have checked the spec first. Updated: 51326d4c86f4e2db1d69ac903466840687976189

File: src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs (hunk 2 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs]: Right, thanks. I have consolidated and expanded the tests: d1a846d8bd48ce79f41edd91fe91a739c5553a0e

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNames.cs [hunk 3]
```diff
@@ -496,6 +496,16 @@ internal static string LambdaCopyParameterName(int ordinal)
             return "<p" + StringExtensions.GetNumeral(ordinal) + ">";
         }
 
+        internal static string AnonymousDelegateParameterName(int index, int parameterCount)
+        {
+            // SPEC: parameter names arg1, ..., argn or arg if a single parameter
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/GeneratedNames.cs:501]: A bit of irony, it looks like `System.Func'2` uses `arg`, but `System.Action'1` uses `obj`...
[https://learn.microsoft.com/en-us/dotnet/api/system.action-1?view=net-6.0](https://learn.microsoft.com/en-us/dotnet/api/system.action-1?view=net-6.0)

We should stick with `arg` as planned ;-)

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 9)

**Review by 333fred — APPROVED** [review]

**Review by genlu — APPROVED** [review]
IDE change LGTM
