### PR TITLE
Only move the caret if the enter was hit within the snippet fields.

### LINKED ISSUE #5366: Pressing Enter after generating a snippet goes to the wrong location
Ported from internal bug 145284

1. Type if followed by <tab><tab> to generate an if block 
2. Don't type anything, but click somewhere else in the source code 
3. Press Enter 

**Expected**: The snippet session is complete and the Enter inserts a newline where the caret was positioned.
**Actual**: The cursor is moved back inside the generated if block, to the snippet's ```$end$``` position.

We should only honor the ```$end$``` location if the caret position is within a snippet field (or maybe within the larger snippet span, we should check the exact Visual Studio 2013 behavior).

### PR DESCRIPTION
**Pull request by diryboy**
Fixes #5366 

Turns out that we don't need to parse xml ourselves. Not sure how to add test for this.

### CODE REVIEW

**Comment by davkean** [comment]
@dotnet-bot test eta please
@dotnet-bot test vsi please

**Comment by davkean** [comment]
tag @dotnet/roslyn-ide @dpoeschl

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetExpansionClient.cs [hunk 1]
```diff
@@ -352,13 +352,14 @@ public virtual bool TryHandleEscape()
 
         public virtual bool TryHandleReturn()
         {
-            // TODO(davip): Only move the caret if the enter was hit within the editable spans
-
             if (ExpansionSession != null)
             {
-                ExpansionSession.EndCurrentExpansion(fLeaveCaret: 0);
+                // Only move the caret if the enter was hit within the snippet fields.
+                var hitWithinField = VSConstants.S_OK == ExpansionSession.GoToNextExpansionField(fCommitIfLast: 0);
```
Comment (Pilchie) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetExpansionClient.cs]: What is the return if you aren't in a field?  `S_FALSE` or an error value?

**Comment by DustinCampbell** [comment]
test?

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetExpansionClient.cs (hunk 1 above)
Comment (diryboy) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetExpansionClient.cs]: I did not examine the value myself, code was copied and modified from `TryHandleTab` if you expand the diff upwards a few times. The [document](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.textmanager.interop.ivsexpansionsession.gotonextexpansionfield.aspx) says it would be an error value.

**Comment by CyrusNajmabadi** [comment]
I imagine this would have to be an integration test.  Unfortunately, it looks like we haven't totally open sourced these yet (but i think we're working on it). @dpoeschl Can you update our snippet integration test to handle this case?

**Comment by davkean** [comment]
@CyrusNajmabadi @dpoeschl It doesn't look like @diryboy can do anything to resolve the test issue? Is this good to merge in and we'll file a bug to add a test?

**Comment by dpoeschl** [comment]
:+1: & Test Signoff

Awesome! Thank you @diryboy!

@davkean - Yes, a tracking issue for the tests will be great. Will add that issue just before merging this.

**Comment by Pilchie** [comment]
:+1: from me too.
