### PR TITLE
Fix nullable suppression in conditional access

### LINKED ISSUE #43659: Counterintuitive interaction of null-conditional and null-forgiving operators
According to the [documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving), the null-forgiving operator has no effect at run time. However, it has a surprising side effect of breaking a [`null_conditional_operations`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#null-conditional-operator) chain at compile time, which may change evaluation of the expression.  Consider this example:
```C#
int[] a = null;

// s1 is null: ToString() is not called at all
string s1 = a?.First().ToString();

// s2 is the empty string: ToString() is called on default(int?)
string s2 = a?.First()!.ToString();
```
Adding the `!` operator effectively changes parsing of the expression to `(a?.First())!.ToString()`.  Since this behavior is surprising for many developers (e.g., dotnet/docs#17988), I am wondering whether not allowing `!` in `null_conditional_operations` was due to omission rather than intentional design.  In the former case we might consider fixing this, in the latter — I would like to learn arguments that led to this decision.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Fixes #43659

### CODE REVIEW

File: src/Compilers/CSharp/Test/Syntax/Parsing/SuppressNullableWarningExpressionParsingTests.cs [hunk 1]
```diff
@@ -252,5 +252,363 @@ public void ConditionalAccess()
...
+                    }
+                }
+            }
+            EOF();
+        }
+
+        [Fact]
+        public void ConditionalAccess_Repeated_03()
+        {
+            UsingNode("x?.y.z!!");
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Test/Syntax/Parsing/SuppressNullableWarningExpressionParsingTests.cs:578]: aside... allowing `!` at the end of `... ?. ...` is *SUPER* weird right?  like no good codebase should ever have that.  the point of using `?.` is to say "i need to handle null in this expr, and i want to shortcircuit to `null` in that case".  But then you're explicitly overriding that at the end with a `!` to say *"i will never get null"* ??

if you can't ever get null, then why use `?.` in teh first place.  and, if you're using `?.`, then you are saying "i can get null and will have to deal with it"

Note: this is not about your PR, but it feels like a def place for an analyzer to ask what hte heck you're doing :)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 2]
```diff
@@ -7893,15 +7893,27 @@ public void SuppressionOnNullableReferenceType_AppliedOnField2()
 public class C
 {
     public string? field;
-    void M(C? c)
+    void M1(C? c)
     {
         c?.field!.ToString();
-        c.ToString(); // We learned from suppressed dereference that `c` isn't null
+        c.ToString(); // 1
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:7899]: @jcouv I wasn't sure whether we actually want 'c' to become not-null due to the suppression on `field!` any more.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 3]
```diff
@@ -10603,6 +10615,20 @@ internal ExpressionSyntax ParseConsequenceSyntax()
                         return expr;
                 }
             }
+
+            bool isExclamationSequenceFollowedByConditionalConsequencePart()
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:10619]: This method name is `isExclamationSequenceFollowedBy` but this method does not guarantee there is an exclamation token. It will return true if the current token is an open paren for example with no exclamation.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:10619]: 0 or more exclamations 😉

**Comment by RikkiGibson** [comment]
Please review @dotnet/roslyn-compiler

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs (hunk 3 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:10619]: Perhaps "isOptionalExclamationSequence..."

---
In reply to: [489068851](https://github.com/dotnet/roslyn/pull/47712#discussion_r489068851) [](ancestors = 489068851)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 4]
```diff
@@ -7893,15 +7893,42 @@ public void SuppressionOnNullableReferenceType_AppliedOnField2()
...
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:7899]: >// 1 [](start = 22, length = 4)

Consider similar tests for other cases:
```C#
#nullable enable
class C
{
    string[]? F1;
    System.Func<object> F2;
    static void M1(C? c)
    {
        c?.F1![0].ToString();
        c.ToString(); // 1        
    }
    static void M2(C? c)
    {
        c?.F2!().ToString();
        c.ToString(); // 1
        
    }
}
```

File: src/Compilers/CSharp/Test/Syntax/Parsing/SuppressNullableWarningExpressionParsingTests.cs [hunk 5]
```diff
@@ -252,5 +252,493 @@ public void ConditionalAccess()
...
+                                N(SyntaxKind.IdentifierToken, "z");
+                            }
+                        }
+                    }
+                    N(SyntaxKind.ExclamationToken);
+                }
+                N(SyntaxKind.ExclamationToken);
+            }
+            EOF();
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Syntax/Parsing/SuppressNullableWarningExpressionParsingTests.cs:742]: >} [](start = 8, length = 1)

Consider testing:
"x?.y?![0].ToString()"
"x?.y?!().ToString()"
"x?.y!?!.ToString()"

**Review by jaredpar — APPROVED** [review]
Modulo tests requested by @cston

**Review by cston — APPROVED** [review]

**Comment by RikkiGibson** [comment]
I'm validating the change in VS just in case this breaks them (e.g. the `x?.y!.z` pattern was used and nullability of the expression has changed)
