### PR TITLE
Fix document rename when case is same

### LINKED ISSUE #39617: Changing class name casing renames file in C #
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/774315/changing-class-name-casing-renames-file-in-c.html)._

---
1. Create new .NET Framework console app project using C# language;
1. You should end up with a project with a single `Program` class;
27. Move cursor to the `Program` word on the `class Program` line;
42. Press the F2 key to start renaming;
256. Change the lowercase `g` to the uppercase `G`;
1024. Confirm rename by pressing Enter;
33284. Notice that the file was renamed to `ProGram1.cs`.

Expexted result: no rename happens, or renamed file name case matches the class name case without any extra characters.

---
#### Visual Studio Feedback System on 10/11/2019, 07:52 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/18/2019, 09:12 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by ryzngard**
When renaming a document, we ensure that the name is unique
but include the old document name in the check. Since that's
the document that's name is changing, we can ignore it
when comparing names for uniqueness.

Fixes #39617

### CODE REVIEW

File: src/EditorFeatures/Test2/Rename/InlineRenameTests.vb [hunk 1]
```diff
@@ -1838,5 +1838,33 @@ End Class
                 Assert.Equal(InlineRenameFileRenameInfo.NotAllowed, session.FileRenameInfo)
             End Using
         End Sub
+
+        <WpfFact>
+        <Trait(Traits.Feature, Traits.Features.Rename)>
+        Public Sub VerifyFileRenamesCorrectlyWhenCaseChanges()
```
Comment (ryzngard) [inline src/EditorFeatures/Test2/Rename/InlineRenameTests.vb]: Note that this doesn't actually validate the fix needed in this change, but I believe is a worthwhile test so I kept it.

File: src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpRename.cs [hunk 2]
```diff
@@ -577,6 +578,37 @@ void Goo()
...
+}");
+
+            VisualStudio.SolutionExplorer.OpenFile(project, "Program.cs");
+            VisualStudio.Editor.PlaceCaret("Program");
+
+            InlineRenameDialog.Invoke();
+
+            VisualStudio.Editor.SendKeys(VirtualKey.Home, VirtualKey.Delete, VirtualKey.P, VirtualKey.Enter);
+
+            VisualStudio.SolutionExplorer.Verify.FileContents(project, "program.cs",
```
Comment (jasonmalinowski) [inline src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpRename.cs]: Does the Verify.FileContents _fail_ if the program.cs wasn't renamed at all and the file on disk is still called Program.cs?

Comment (ryzngard) [reply src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpRename.cs]: Hmmm.... I was really hoping it would check the file name matches case but it doesn't... It does verify that it's not called "Program1.cs" though =/
