### PR TITLE
Fix a null reference in BaseFormattingRule...

### LINKED ISSUE #11642: Crash formatting parenthesized lambda expression
**Version Used**: 
1.2.2

**Steps to Reproduce**:
```
    var syntaxNode =
        ParenthesizedExpression(
            ParenthesizedLambdaExpression(ParameterList(), Block()));
    var result = Formatter.Format(syntaxNode, new AdhocWorkspace());
```
**Expected Behavior**:
Formatter.Format succeeds returning formatted node

**Actual Behavior**:
Microsoft.CodeAnalysis.CSharp.Formatting.BaseFormattingRule.SomeParentHasMissingCloseBrace fails with NullReferenceException

### PR DESCRIPTION
**Pull request by balajikris**
... that was introduced with PR #4644

Method `SomeParentHasMissingCloseBrace` expects a fully formed node that
has a compilation unit, which a roslyn document would have, but this
code is also in a formatter public api path, that can possibly `an
arbitrary` syntax node that may not be associated with a syntaxtree or a
compilation unit.

The fix is simple, it adds a missing null check to this method.

Fixes #11642

### CODE REVIEW

**Comment by balajikris** [comment]
@dotnet/roslyn-ide, please review.

File: src/EditorFeatures/CSharpTest/Formatting/FormattingEngineTests.cs [hunk 1]
```diff
@@ -1405,6 +1404,18 @@ public void M()
             await AssertFormatAfterTypeCharAsync(code, expected);
         }
 
+        [WorkItem(11642, "https://github.com/dotnet/roslyn/issues/11642")]
+        [WpfFact, Trait(Traits.Feature, Traits.Features.Formatting)]
+        public async Task FormatArbitraryNodeParenthesizedLambdaExpression()
+        {
+            // code equivalent to an expression synthesized like so:
```
Comment (jasonmalinowski) [inline src/EditorFeatures/CSharpTest/Formatting/FormattingEngineTests.cs]: Not sure why the comment is here. The test seems to stand by itself quite nicely.

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
:+1:
