### PR TITLE
Change 'None' in code style options to 'Refactoring Only'

### LINKED ISSUE #15760: The Error List shows different results based on whether you've ever opened a source file
1. Clone this repo to this commit: https://github.com/dotnet/roslyn-project-system/commit/e8f444a1ebe3d78b6b494d5dc355e95b7da19086
2. From a VS command prompt, run build.cmd from the root
3. Open src\ProjectSystem.sln (build 26005.0 D15PreRel)
4. Change your VB code style settings to:
image
6. Make sure Background Analysis is turned on for VB
7. Wait till Error List no longer has "..." after name
-- Error List should look something like --
image

7. Open src\Microsoft.VisualStudio.AppDesigner\ApplicationDesigner\ApplicationDesignerView.vb
8. Close that file

-- Error List should look something like (Notice that there's 22 more messages that have appeared) -- 

image

Very confused how or why messages show up the Error List? What exactly do I need to do to show *all* possible messages?

### LINKED ISSUE #16026: "Open Files" analysis doesn't occur on files that were opened from a previous solution session
1. Create a project
2. Create two files containing a violation on something that only occurs in open files (for example, interfaces must start with I
3. Open both files

-- Note that you see both errors in the error list --

4. File -> Close Solution
5. Open the solution you just closed

Expected: For both errors to appear in the error list
Actual: Only error from the file that current the selected tab is in the error list

Very confusing - especially when I was using the "Open Documents" filter.

### LINKED ISSUE #16700: Bumping diagnostic severity for some IDE analyzers to error/warning doesn't cause it to run for closed files.
**Version Used**: 
D15PreRel 26120.4

**Steps to Reproduce**:

1. Enable full solution analysis for C#
2. Create a C# console app with the following source code:
```
namespace ConsoleApp1
{
    class Program
    {
        void F(object o)
        {
            var x = o as Program;
        }

        static void Main(string[] args)
        {
        }
    }
}
```
3. Verify IDE0008 is shown in the error list.
3. In solution explorer, right click on Analyzers node under `Project -> References -> Analyzers` and click "Open active ruleset".
4. Search "IDE0008" in the ruleset editor, and change the severity of both the listed diagnostics to "Error".
5. Verify IDE0008 is now shown as "Error" in the error list
6. Close the source file

**Expected Behavior**:
Error IDE0008 is still shown in the error list. Any diagnostics marked as error in the project's ruleset should always be executed for closed files.

**Actual Behavior**:
IDE0008 will disappear, and only show for open files. Even closing and re-opening solution/VS doesn't seem to help.
The problem seems to be that many IDE analyzers compute OpenFileOnly value using just the Workspace level NotificationOption, see [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs,25). They should instead be using the effective severity of the diagnostic ID for the current compilation to decide this value.

### PR DESCRIPTION
**Pull request by sharwell**
* Rename 'None' in code style options to 'Refactoring Only'
* Add "refactoring" as an alias for "silent" in .editorconfig
* Remove special case handling of `ReportDiagnostic.Hidden`

image

### Customer scenario

The 15.8 release contains several changes to improve the overall experience for users with .editorconfig files. While the experience for users working exclusively with .editorconfig is consistent, and the experience for users working exclusively without .editorconfig is consistent, during the documentation effort for the new features several discrepancies were identified that would lead to inconsistent messaging:

1. The term 'none' means one thing in rule set files and .editorconfig, but has a very different meaning in Tools &rarr; Options
2. The behavior of code style rules configured as 'Hidden' (rule set) / 'silent' (.editorconfig) / 'None' (Tools &rarr; Options) is not consistent for all rules with respect to Fix All operations and Code Cleanup

To resolve these issues, we have tweaked the design of none and silent to have the a consistent description for all users.

### Bugs this fixes

N/A

### Workarounds, if any

Not include documentation, or write documentation knowing the current implementation does not adhere to the described behavior.

### Risk

This pull request is *mostly* a low-risk change to terminology. However, for a few built-in diagnostics that support Fix All operations, the Fix All will now fix certain items which were previously excluded. This change should only impact cases where *all* of the following are true:

1. The solution contains scoped code style configurations (e.g. per-project or per-document), and one or more scopes uses the same code style preference from the others but differs in the reported diagnostic severity.
2. One of the diagnostic severities from the previous item is 'Hidden' (rule set) / 'silent' (.editorconfig) / 'None' (Tools &rarr; Options)
3. A Fix All operation is performed on a scope which includes diagnostics reported in multiple scopes, and the scopes containing diagnostics for the Fix All operation meet the conditions described for both (1) and (2).

### Performance impact

Performance is not changed aside from the increased scope of work described under **Risk**.

### Is this a regression from a previous update?

No.

### Root cause analysis

Our design provided self-consistent experiences for several different user stories, but we failed to provide clear messaging between these groups. While the groups are generally distinct (users each tend to prefer one approach over the others), clear and consistent messaging helps users adopt our features and communicate in public about successful use of our product to solve problems.

### How was the bug found?

Writing documentation.

### Test documentation updated?

No, but user documentation is being updated.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
can you post a picture of what this look like?

**Comment by sharwell** [comment]
@CyrusNajmabadi yes, tomorrow. I meant to earlier but ran out of time.

**Comment by sharwell** [comment]
Here's another view if you make the dialog narrower:

image

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs [hunk 1]
```diff
@@ -26,16 +21,7 @@ internal abstract partial class CSharpTypeStyleDiagnosticAnalyzerBase :
 
         public override DiagnosticAnalyzerCategory GetAnalyzerCategory() => DiagnosticAnalyzerCategory.SemanticSpanAnalysis;
 
-        public override bool OpenFileOnly(Workspace workspace)
-        {
-            var forIntrinsicTypesOption = workspace.Options.GetOption(CSharpCodeStyleOptions.UseImplicitTypeForIntrinsicTypes).Notification;
```
[the remark this answers is not in the document]
Comment (heejaechang) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: open files only has nothing to do with fix all by the way.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs [hunk 2]
```diff
@@ -62,9 +48,7 @@ private void HandleVariableDeclaration(SyntaxNodeAnalysisContext context)
 
             var typeStyle = Helper.AnalyzeTypeName(
                 declaredType, semanticModel, optionSet, cancellationToken);
-            if (!typeStyle.IsStylePreferred ||
-                typeStyle.Severity.WithDefaultSeverity(DiagnosticSeverity.Hidden) >= ReportDiagnostic.Hidden ||
```
Comment (heejaechang) [inline src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: what is this hidden diagnostic check? is IDE used to have different behavior based on severity?

File: src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs [hunk 3]
```diff
@@ -31,7 +31,7 @@ public UseExpressionBodyCodeFixProvider()
         }
 
         protected override bool IncludeDiagnosticDuringFixAll(Diagnostic diagnostic)
-            => diagnostic.Severity != DiagnosticSeverity.Hidden ||
```
Comment (heejaechang) [inline src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs]: interesting? why explicitly filtering out hidden diagnostic for fix all? anyway, I am not sure how you get suppressed diagnostic for fix all. assuming there is no hidden IDE only hack, the engine should never give suppressed diagnostics to fix all.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: Could you help clarify what the purpose of OpenFileOnly is?  thanks!

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs [hunk 4]
```diff
@@ -30,7 +30,7 @@ public override ImmutableArray<string> FixableDiagnosticIds
             => ImmutableArray.Create(IDEDiagnosticIds.UseLocalFunctionDiagnosticId);
 
         protected override bool IncludeDiagnosticDuringFixAll(Diagnostic diagnostic)
-            => diagnostic.Severity != DiagnosticSeverity.Hidden && !diagnostic.IsSuppressed;
```
Comment (heejaechang) [inline src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: hmmm.. same here. engine only call analyzer service to return suppressed diagnostics for suppression fix service.

File: src/Features/Core/Portable/Diagnostics/Analyzers/NamingStyleDiagnosticAnalyzerBase.cs [hunk 5]
```diff
@@ -40,7 +39,7 @@ protected NamingStyleDiagnosticAnalyzerBase()
         // see https://github.com/dotnet/roslyn/issues/14061
         protected abstract ImmutableArray<TLanguageKindEnum> SupportedSyntaxKinds { get; }
 
-        public override bool OpenFileOnly(Workspace workspace) => true;
```
Comment (heejaechang) [inline src/Features/Core/Portable/Diagnostics/Analyzers/NamingStyleDiagnosticAnalyzerBase.cs]: do we know why it was open file only before? there used to be 2 reasons as long as I know.

first is perf. some analyzer was just so slow, so making it to run all files just make full solution analysis useless. so it was set to open file only until perf is improved.

second was it required a workspace/vs service which doesn't exist in OOP including some options.

File: src/Features/Core/Portable/Diagnostics/Analyzers/NamingStyleDiagnosticAnalyzerBase.cs [hunk 6]
```diff
@@ -118,7 +117,7 @@ void SyntaxNodeAction(SyntaxNodeAnalysisContext syntaxContext)
             var namingStyleRules = namingPreferences.Rules;
 
             if (!namingStyleRules.TryGetApplicableRule(symbol, out var applicableRule) ||
-                applicableRule.EnforcementLevel.WithDefaultSeverity(DiagnosticSeverity.Hidden) >= ReportDiagnostic.Hidden)
```
Comment (heejaechang) [inline src/Features/Core/Portable/Diagnostics/Analyzers/NamingStyleDiagnosticAnalyzerBase.cs]: what does this mean?

File: src/Features/Core/Portable/Diagnostics/Analyzers/PreferFrameworkTypeDiagnosticAnalyzerBase.cs [hunk 7]
```diff
@@ -31,16 +31,7 @@ private static PerLanguageOption<CodeStyleOption<bool>> GetOptionForDeclarationC
         private static PerLanguageOption<CodeStyleOption<bool>> GetOptionForMemberAccessContext 
             => CodeStyleOptions.PreferIntrinsicPredefinedTypeKeywordInMemberAccess;
 
-        public override bool OpenFileOnly(Workspace workspace)
-        {
-            var preferTypeKeywordInDeclarationOption = workspace.Options.GetOption(
```
Comment (heejaechang) [inline src/Features/Core/Portable/Diagnostics/Analyzers/PreferFrameworkTypeDiagnosticAnalyzerBase.cs]: same question. do we know why it was open file only before?

File: src/Features/Core/Portable/Diagnostics/Analyzers/PreferFrameworkTypeDiagnosticAnalyzerBase.cs [hunk 8]
```diff
@@ -132,6 +123,6 @@ private bool IsFrameworkTypePreferred(OptionSet optionSet, PerLanguageOption<Cod
         /// </summary>
         /// <remarks>if predefined type is not preferred, it implies the preference is framework type.</remarks>
         private static bool OptionSettingPrefersFrameworkType(CodeStyleOption<bool> optionValue, ReportDiagnostic severity)
-            => !optionValue.Value && severity.WithDefaultSeverity(DiagnosticSeverity.Hidden) < ReportDiagnostic.Hidden;
```
Comment (heejaechang) [inline src/Features/Core/Portable/Diagnostics/Analyzers/PreferFrameworkTypeDiagnosticAnalyzerBase.cs]: is it using supress as its own special meaning now?

File: src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs [hunk 9]
```diff
@@ -24,18 +24,7 @@ protected AbstractQualifyMemberAccessDiagnosticAnalyzer()
         {
         }
 
-        public override bool OpenFileOnly(Workspace workspace)
-        {
-            var qualifyFieldAccessOption = workspace.Options.GetOption(CodeStyleOptions.QualifyFieldAccess, GetLanguageName()).Notification;
```
Comment (heejaechang) [inline src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs]: interesting there were so many open file only analyzers in IDE.. is it due to some hack IDE did like returning nothing for supported diagnsotics and then report some random diagnostics when they want causing engine's optimization of not running hidden diagnostics for closed files?

is that now changed?

File: src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs [hunk 10]
```diff
@@ -121,19 +110,20 @@ private void AnalyzeOperation(OperationAnalysisContext context, IOperation opera
             var optionValue = optionSet.GetOption(applicableOption, context.Operation.Syntax.Language);
 
             var shouldOptionBePresent = optionValue.Value;
-            var isQualificationPresent = IsAlreadyQualifiedMemberAccess(simpleName);
-            if (shouldOptionBePresent && !isQualificationPresent)
+            var severity = optionValue.Notification.Severity;
+            if (!shouldOptionBePresent || severity == ReportDiagnostic.Suppress)
```
Comment (heejaechang) [inline src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs]: ah. so it is not checking diagnostic's supression but option's supression to see whether analyzer is turned off? is this option work with ruleset as well? I think ruleset's diagnostic severity comes from compilation option.

File: src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs (hunk 3 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs]: > why explicitly filtering out hidden diagnostic for fix all? 

In some projects you may have this things set to a higher level (and would get things like suggestions ellipses in the code).  In other projects, the feature level may be 'true:none' (since you want to generate expression-bodies, but you don't want to see anything in the UI.  We use this so that you can still actually generate the expression body in that project if you're on the item.

However, if you fix all, we don't want to update the nodes we marked with the hidden diagnostic.  Only teh ones the user can visibly see marked and want updated.

File: src/Features/Core/Portable/Diagnostics/Analyzers/PreferFrameworkTypeDiagnosticAnalyzerBase.cs (hunk 7 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/Diagnostics/Analyzers/PreferFrameworkTypeDiagnosticAnalyzerBase.cs]: I think OpenFileOnly is that special IBuiltInAnalyzer stuff.  Do we know who added that, so we can find out?

File: src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs (hunk 9 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs]: Sorry, can you explain why that's a hack?  How else would you get fix-all to work across documents otherwise?

Can you explain what the right way is to do things so the IDE can remove 'hacks'?    Thanks!

**Comment by heejaechang** [comment]
code wise looks fine. but can't remember all reasons why they were marked as open files only. @Pilchie @jinujoseph @mavasani do you remember?

I think these 3 reasons, but might be more

1. perf - some were too slow to run for all files. othrewise, full solution analysis become unusable.
2. services - some require IDE service that doesn't exist in OOP, so it couldn't run OOP.
3. hack - some analyzers didn't follow compiler's diagnostic analyzer contract but IDE own thing so one of optimization to run hidden diagnostics only for open files didn't work for those analyzers. so they had to do thier own logic in OpenFiles so that they don't run on closed files.

anyway, probably need to confirm that now all those concerns are gone.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (heejaechang) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: it tells engine to run the analyzer only for open files.

File: src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs (hunk 9 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs]: > Can you explain what the right way is to do things so the IDE can remove 'hacks'? Thanks!

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs]: Basically, what is the "right" way for the IDE to use the analyzer subsystem for things like fixes/style/etc?

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (sharwell) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: > Could you help clarify what the purpose of OpenFileOnly is? thanks!

It's a flag that forces the analysis to always run inside Visual Studio (as opposed to OOP). It has a nasty side effect that causes Fix All operations to be scoped to the intersection of the requested scope and the set of files currently open in the editor. This limitation has been removed for analyzers that do not depend on Visual Studio services, so if you ask for Fix All you will now get Fix All.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs (hunk 2 above)
Comment (sharwell) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: The original intent is avoiding a case where a user tries to apply a Fix All to a warning or error, and the Fix All operation tries to fix a bunch of hidden diagnostics that the user intended to ignore. Multiple mitigations for this scenario are already in place, but if desired we could implement additional protection by filtering the diagnostics selected for Fix All to only include diagnostics at the severity chosen for Fix All or more severe (e.g. Fix All on an Error diagnostic would fix all Error severity; Fix All on a Warning diagnostic would fix all Error and Warning severity; etc.). The easiest approach would be the one seen here, where Fix All simply means to fix all diagnostics.

Comment (heejaechang) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: so, are we saying whether fix all for diagnostics that have different severities due to editorconfig between a different portion of directories/files in a solution, each "fix all provider" have its own behavior?

is it something we want to generalize in the engine?

sounds like a design question?

...

should fix all engine fix only diagnostics with same (severity, id, equivalent key) rather than (id, equivalent) or is it something each fix all provider decide?

File: src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs (hunk 3 above)
Comment (heejaechang) [reply src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs]: so should be pushed to engine? @mavasani @jinujoseph @kuhlenh

File: src/Features/Core/Portable/Diagnostics/Analyzers/PreferFrameworkTypeDiagnosticAnalyzerBase.cs (hunk 7 above)
Comment (heejaechang) [reply src/Features/Core/Portable/Diagnostics/Analyzers/PreferFrameworkTypeDiagnosticAnalyzerBase.cs]: I added it due to IDE analyzer special behavior I listed above and below. but that doesn't mean I know why these analyzers are chosen to be open file only.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs (hunk 2 above)
Comment (heejaechang) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: also about Full Solution Analysis. I think I sent telemetry data a few days ago on IDE options. FSA is 3rd most popular options user changes among all Roslyn options.

Comment (heejaechang) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: in case people are curious. 
First most popular option is naming preferences (http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Simplification/SimplificationOptions.cs,103)

Second most popular option is placing system first option
(http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Editing/GenerationOptions.cs,9)

File: src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs (hunk 9 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs]: > it might have been better if IDE didn't jam these into compiler DIagnosticAnalyzer but built its own DiagnosticAnalyzer system for IDE only that can use whatever system they want for whatever experience they want rather than jam these conflicting desire into one that defined in compiler layer.

I'm confused.  The original design of the Diagnostic Analysis subsystem was to make something that would work for IDE purposes**.  IDE *already* had it's own system prior to that (after all, we shipped analyzers/fixers long before we build the Diagnostic-Analyzer stuff).  If DiagnosticAnalyzer isn't the appropriate system for the IDE then why was so much effort put into building it *and* moving all the existing IDE code onto it?  

--

** I remember this distinctly in the original meetings on the topic.  When we were deciding core deliverables, one of them was that this has to suffice for IDE needs since a primary goal was to get us out of hte "let's analyze files twice" state we were in.  So we went with: we'll analyze stuff once as hte compiler is doing it, and it will call out into plugins so that we can do things like IDE analysis at the same time.  This was a core goal, and i'm def confused by the messaging that the IDE was actually supposed to *not* use the actual DiagnosticAnalyzer...

Comment (heejaechang) [reply src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs]: we can bring in @mavasani and @Pilchie since I wasn't in the design meeting that decide DiagnosticAnalyzer compiler feature. 

anyway, DiagnosticAnalyzer was built as compiler feature and from the point of view of compiler. that's why it doesn't have concept of file by file analysis concept which is very important for IDE.

and I dont believe it was built for all the possible things IDE could do in mind rather it was built with what all the thing compiler can do in mind. and IDE simply wants more than that. 

that's why DiagnosticAnalyzer can only access compilation data and nothing else when IDE can do much more with other data (ex, Nuget, web config, options and more)

as I remember, at the time, once it moved to compiler layer, it was simply errors that compiler produce for IDE that we shouldn't care whether it is csc generated or third party analyzers. and that's it.

I don't know why IDE decide to hop on that system. if they wanted some part of it like squiggle, LB, error list, you guys could use incremental analyzer, diagnostic source, and expand LB to support IDE one as well. since IDE DiagnosticAnalyzer can't run on VBCSCompiler anyway.

Comment (heejaechang) [reply src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs]: or you guys could change compiler DiagnosticAnalyzer itself to support all things you guys wanted and then IDE side naturally get all those new thing working. rather than workaround these thing in IDE and now we have 2 different systems that share some and not share some.

Comment (heejaechang) [reply src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs]: >  This was a core goal, and i'm def confused by the messaging that the IDE was actually supposed to not use the actual DiagnosticAnalyzer

if you guys were using DiagnosticAnalyzer as it is defined/supported by compiler then it was right decision. but you guys don't. and that is the problem.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs]: > I don't know why IDE decide to hop on that system. 

Literally a core design goal of DiagnosticAnalyzers was to be able to support the IDE scenarios around lightbulbs.  That was a design goal from the very earliest meetings.  It's one of the reasons that so many IDE features immediately moved onto DiagnosticAnalyzers.  Which i *though* was actually done by the analyzer team.  i.e. i don't think IDE people moved things like 'simplify name', 'remove-cast', 'generate method' and so on and so forth to DiagnosticAnalyzers.  That was done by the analyzer group to help prove out the DiagnosticAnalyzer infrastructure and to show that it could suffice for IDE needs.

If this wasn't the purpose of DiagnosticAnalyzer, then there was some *dramatic* miscommunication.  Because literally tons of man-hours were sunk to create this system and then have pretty much eveyr IDE diagnostic feature now sit on it.  If that wasn't the purpose of this work, then i have no idea why that wasn't noticed or addressed until now...

> or when IDE needed more, if IDE improved DiagnsoticAnalyzer in compiler then, it would have been good again since we could just call compiler.GetDiagnostics without any IDE only hacks and special behavior. but IDE doesn't. and that is the problem.

You're saying the IDE hacked things.  But it's unclear to me what those hacks actually are.  As far as i can tell, we're using the API that is actually exposed by the analysis subsystem.  And, from previous posts you said things like "IBuiltInAnalyzer interface is basically a hack to make 2 system merged together."  But IDE didn't create that API.  That API is what came from people working on the DiagnosticAnalyzer and it was added to the analyzer that the IDE had built.

--

Basically, if there was an issue, i wish it had been brought up 5+ years ago as we started using these facilities.  I'm happy to move to a 'non-hack' solution.  But it's unclear to me what that is. 

However, i don't think ti's a solution for the IDE to just make a new analysis subsystem for itself.  That would be enormous duplication.  And would go against the intended goal of the real diagnostic analysis work (which was to create something suitable for all these needs).  So any real solution would be updating the real DiagnosticAnalyzer to do things non-hackily.  However, that works seems like it would be sensible to do by the people who know the DiagnosticAnalyzer subsystem the best.

**Comment by heejaechang** [comment]
@sharwell I am not against on this PR. I think changing non to refactoring only is good. if you believe all those open file analyzers are now okay to run for all closed files with FSA on, then I am fine checking this in as well!

File: src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs (hunk 3 above)
Comment (mavasani) [reply src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs]: I think we are now seeing suppressed diagnostic instances in the IDE now for rules which are completely disabled (turned off in ruleset or tools option) after https://github.com/dotnet/roslyn/pull/27220. I mentioned this in https://github.com/dotnet/roslyn/pull/27220#pullrequestreview-125710982, and I believe we should revert that approach/workaround for a better design as soon as possible, as that violates lot of basic assumptions in the IDE diagnostic engine.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs (hunk 2 above)
Comment (mavasani) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: > The original intent is avoiding a case where a user tries to apply a Fix All to a warning or error, and the Fix All operation tries to fix a bunch of hidden diagnostics that the user intended to ignore.

I think the underlying issue is naming style analyzers have different dynamic diagnostic descriptors for different symbol kind with possibly different severities, and all of them use the same diagnostic ID. Ideally:

1. All diagnostic instances in a compilation with a specific diagnostic ID *must* have same _effective severity_.
2. Performing FixAll on a specific diagnostic, with an explicitly chosen scope (document, project, solution) *must* fix all diagnostic instances with that ID in the requested scope. Effective severity should never play a part in determining fix all behavior.

File: src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs (hunk 3 above)
Comment (heejaechang) [reply src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs]: just looked. so another case where IDE does its own then. so now IDE analyzer can bypass all engine and set severity whatever they want.. these analyzer will not be able to run in other host but only in IDE.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs (hunk 2 above)
Comment (heejaechang) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: @mavasani with editorconfig, isn't user now possible to set different severity for same diagnostic id in different part of directory? so effective severity can different per directory or file I guess now?

for 2, I think right fix might be making fix all works with error list so that user can select bunch of errors in error list and invoke fix all rather than we having bunch of heuristic that might make sense in one situation and doesn't in other context. and what end result user wants is different on every occasion based on why user is invoking it.

with code clean up framework we have now ("fix all" custom set of diagnostics + multiple fixer), we might be able to extend it a bit more to support error list.


complication on error list over code clean up was that, code clean up only care about diagnostic/fixer kind rather than each specific instance of diagnostic, so it was easy to track between each fixer, but error list is about specific instance of diagnostic, so a bit harder to track on each fixes.

File: src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs (hunk 3 above)
Comment (mavasani) [reply src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs]: Yes, in order for us to move these analyzers to NuGet, we will need to remove all performance/functional workarounds in the analyzers and/or the IDE diagnostic engine. Sam already has an idea on how to tackle dynamic diagnostic IDs for naming style analyzers, but we will need to explicitly identify and fix remaining issues like this before that work can be done.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs]: @mavasani 

> Sam already has an idea on how to tackle dynamic diagnostic IDs for naming style analyzers, but we will need to explicitly identify and fix remaining issues like this before that work can be done.

I would def like to be involved/aware of those issues, and how we would like ot design support for that into the analysis subsystem.  It would def be helpful.  Thanks!

Comment (heejaechang) [reply src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs]: wondering how all these work with suppression service.. have we tested that area? or are we treat diagnostics from IDE analyzer special in suppression service as well? suppression service is supposed to be able to unsupress suppressed diagnostics, isn't it? does that work with IDE analyzer?
…

File: src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs (hunk 9 above)
Comment (mavasani) [reply src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs]: DiagnosticAnalyzer API was always designed to support analyzers in both compiler and IDE hosts. However, due to various functional and/or performance requirements of executing these analyzers in the IDE and configuring them via workspace options, over time lot of workarounds have been added in the analyzers and the IDE diagnostic engine that strongly couple them to the IDE host. @sharwell's planned work on moving these analyzers to NuGet would thread apart all such tight couplings, will need removing all such workarounds and internals knowledge, and possibly identify missing public APIs or engine functionality that are required to continue executing these analyzers correctly and efficiently in IDE.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs (hunk 2 above)
Comment (mavasani) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: > with editorconfig, isn't user now possible to set different severity for same diagnostic id in different part of directory? so effective severity can different per directory or file I guess now?

Yes, I always forget the side effects of editorconfig's directory based configurations. I wonder if we need a change in FixAll experience to allow users to choose between fixing all diagnostics with (a) same effective severity or (b) same or more severe effective severity or (c) regardless of effective severity.

File: src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs (hunk 3 above)
Comment (mavasani) [reply src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs]: > wondering how all these work with suppression service.. have we tested that area? or are we treat diagnostics from IDE analyzer special in suppression service as well? suppression service is supposed to be able to unsupress suppressed diagnostics, isn't it? does that work with IDE analyzer?

I did bring up these points on the PR from @sharwell. Sam were you able to test if suppressing diagnostic from error list, then unsuppressing source-suppressed diagnostics work fine? We might have just broken that error list feature.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (sharwell) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: :memo: Related to #26758

File: src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs (hunk 3 above)
Comment (sharwell) [reply src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs]: > Sam were you able to test if suppressing diagnostic from error list, then unsuppressing source-suppressed diagnostics work fine? We might have just broken that error list feature.

Not yet. I'm trying to round out the more obvious items and looking at ones like this for preview 5 polish.

Comment (sharwell) [reply src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs]: > In other projects, the feature level may be 'true:none'

`true:none` in .editorconfig now acts as a suppression (or disabled), so these would not appear in the Fix All experience. `silent` severity *would* now show in the Fix All experience.

Comment (sharwell) [reply src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs]: > suppression service is supposed to be able to unsupress suppressed diagnostics, isn't it?

👍 This is the part I was missing. I knew about the ability to filter the error list, but that alone seemed like a really small issue.

File: src/Features/Core/Portable/Diagnostics/Analyzers/NamingStyleDiagnosticAnalyzerBase.cs (hunk 6 above)
Comment (sharwell) [reply src/Features/Core/Portable/Diagnostics/Analyzers/NamingStyleDiagnosticAnalyzerBase.cs]: If the `ReportDiagnostic` has a value of `Default`, `Hidden`, or `Suppress`, the expression on this line is true.

* `Default` maps to `Hidden` per the call to `WithDefaultSeverity`
* `Hidden` and `Suppress` are the only two values greater than or equal to `Hidden` (this enumeration is defined in the opposite order from `DiagnosticSeverity`)

File: src/Features/Core/Portable/Diagnostics/Analyzers/PreferFrameworkTypeDiagnosticAnalyzerBase.cs (hunk 8 above)
Comment (sharwell) [reply src/Features/Core/Portable/Diagnostics/Analyzers/PreferFrameworkTypeDiagnosticAnalyzerBase.cs]: `Suppress` is the internal representation of severity `none` from .editorconfig. Unlike rule set files, we cannot blanket disable an analyzer or diagnostic with severity `none` so we need a way to represent it in the options passed to the analyzers.

File: src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs (hunk 9 above)
Comment (sharwell) [reply src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs]: > @sharwell's planned work on moving these analyzers to NuGet would thread apart all such tight couplings, will need removing all such workarounds and internals knowledge, and possibly identify missing public APIs or engine functionality that are required to continue executing these analyzers correctly and efficiently in IDE.

💯 The NuGet distribution of what is currently the IDE analyzers will not have `InternalsVisibleTo` access to the compiler or workspace, so whatever we need implemented to make the experience work well for those will necessarily be available for all analyzer authors.

File: src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs (hunk 10 above)
Comment (sharwell) [reply src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs]: > is this option work with ruleset as well? I think ruleset's diagnostic severity comes from compilation option.

It is my understanding that the presence of a value in a rule set file will force the severity of diagnostics to be overridden, so whatever we do here would no longer have an impact. With that said, our IDE analyzers do not work particularly well with rule set files; they were implemented with .editorconfig as the recommended configuration mechanism.

> by the way, is this work with command line case? is this another IDE only thing?

None of these analyzers are currently supported on the command line.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (sharwell) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: > Confirmed. I'm guessing my mistaken impression was the result of observing the behavior of IncludeDiagnosticDuringFixAll and assuming it was the open file status that led to it.

Based on this, I'm going to revert the changes to `OpenFileOnly`, but leave the changes for Fix All filtering.

[the remark this answers is not in the document]
Comment (sharwell) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: ➡️ The changes to `OpenFileOnly` methods were reverted (no other changes so I amended the previous commit)

File: src/Features/Core/Portable/Diagnostics/Analyzers/NamingStyleDiagnosticAnalyzerBase.cs (hunk 5 above)
Comment (sharwell) [reply src/Features/Core/Portable/Diagnostics/Analyzers/NamingStyleDiagnosticAnalyzerBase.cs]: ➡️ The changes to `OpenFileOnly` methods were reverted (no other changes so I amended the previous commit)

File: src/Features/Core/Portable/Diagnostics/Analyzers/PreferFrameworkTypeDiagnosticAnalyzerBase.cs (hunk 7 above)
Comment (sharwell) [reply src/Features/Core/Portable/Diagnostics/Analyzers/PreferFrameworkTypeDiagnosticAnalyzerBase.cs]: ➡️ The changes to `OpenFileOnly` methods were reverted (no other changes so I amended the previous commit)

File: src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs (hunk 9 above)
Comment (sharwell) [reply src/Features/Core/Portable/QualifyMemberAccess/AbstractQualifyMemberAccessDiagnosticAnalyzer.cs]: ➡️ The changes to `OpenFileOnly` methods were reverted (no other changes so I amended the previous commit)

File: src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs (hunk 3 above)
Comment (sharwell) [reply src/Features/CSharp/Portable/UseExpressionBody/UseExpressionBodyCodeFixProvider.cs]: > Sam were you able to test if suppressing diagnostic from error list, then unsuppressing source-suppressed diagnostics work fine? We might have just broken that error list feature.

I tested this today, and it appears the use of `none` in .editorconfig prevents the items from showing up in Error List even if the list isn't filtered to Active.

File: src/EditorFeatures/CSharpTest/Formatting/CodeCleanupTests.cs [hunk 11]
```diff
@@ -87,6 +87,7 @@ static void Main(string[] args)
             return AssertCodeCleanupResult(expected, code,
                 (CodeCleanupOptions.AreCodeCleanupRulesConfigured, enabled: true),
                 (CodeCleanupOptions.SortImports, enabled: true),
+                (CodeCleanupOptions.ApplyImplicitExplicitTypePreferences, enabled: false),
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Formatting/CodeCleanupTests.cs]: was this needef for some purpose?

File: src/Workspaces/CSharp/Portable/Utilities/CSharpTypeStyleHelper.cs [hunk 12]
```diff
@@ -18,16 +18,17 @@ internal struct TypeStyleResult
...
+        /// <c>var</c> for everything, and you have <c>int i = 0</c> then <see cref="IsStylePreferred"/> will be
+        /// <see langword="true"/>. However, if the user likes <c>var</c> for everything and you have <c>var i = 0</c>,
+        /// then it's still possible to convert that, it would just be <see langword="false"/> for
+        /// <see cref="IsStylePreferred"/> because it goes against the user's preferences.
         /// </summary>
+        /// <remarks>
+        /// <para>In general, most features should only convert the type if <see cref="IsStylePreferred"/> is
+        /// <see langword="true"/>. The one exception is the refactoring, which is explicitly there to still let people
+        /// convert things quickly, even if it's going against their stated style.</para>
+        /// </remarks>
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Utilities/CSharpTypeStyleHelper.cs]: thanks!

File: src/Workspaces/Core/Portable/CodeStyle/CodeStyleHelpers.cs [hunk 13]
```diff
@@ -98,6 +98,7 @@ public static bool TryParseNotification(string value, out NotificationOption not
                     notification = NotificationOption.None;
                     return true;
 
+                case EditorConfigSeverityStrings.Refactoring:
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeStyle/CodeStyleHelpers.cs]: ok.  so this means in editor-config, people can do true:refactoring, yes?

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs [hunk 14]
```diff
@@ -62,9 +58,7 @@ private void HandleVariableDeclaration(SyntaxNodeAnalysisContext context)
 
             var typeStyle = Helper.AnalyzeTypeName(
                 declaredType, semanticModel, optionSet, cancellationToken);
-            if (!typeStyle.IsStylePreferred ||
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: @sharwell what process did you use to figure out waht would need updating?  did you basically just look for usages of .Hidden?

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: Basically, i'm trying to figure out if we got everything, or if any analyzers might have slipped through.

File: src/EditorFeatures/CSharpTest/Formatting/CodeCleanupTests.cs (hunk 11 above)
Comment (sharwell) [reply src/EditorFeatures/CSharpTest/Formatting/CodeCleanupTests.cs]: These are enabled by default at 'None' severity in Tools &rarr; Options. This became 'Refactoring Only' and behaves like all other Hidden-severity diagnostics, which means the fixes will be applied if checked in Code Cleanup.

File: src/Workspaces/Core/Portable/CodeStyle/CodeStyleHelpers.cs (hunk 13 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/CodeStyle/CodeStyleHelpers.cs]: ➡️ Yes, this is correct. It's the same as `true:silent` and is added simply to reduce confusion about terminology differences between Tools&rarr;Options and .editorconfig.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs (hunk 14 above)
Comment (sharwell) [reply src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: I looked for uses of `Hidden` and also accounted for the diff of #27220. The type change there did a good job of highlighting relevant cases.

**Comment by sharwell** [comment]
retest this please

**Comment by jinujoseph** [comment]
Approved to merge for 15.8.Preview4 (once green)

File: src/Workspaces/Core/Portable/CodeStyle/CodeStyleHelpers.cs (hunk 13 above)
Comment (Neme12) [reply src/Workspaces/Core/Portable/CodeStyle/CodeStyleHelpers.cs]: I'm a little confused by this terminology. Refactorings are often available even if they go *against* the user preference (for example implicit/explicit type). Therefore I would expect "refactoring" to be equivalent to "none" as opposed to "silent".

Comment (heejaechang) [reply src/Workspaces/Core/Portable/CodeStyle/CodeStyleHelpers.cs]: we find some customers want none as none. no squiggle, no suggestion, no error or no refactoring. they want to completely turn off these offering for whatever reasons they have. (some said having tool icon distract them too much for things they never use or care)

they can turn completely off by opening rule set editor and set it as none. they now got confused since they have 3 different things (ruleset, editorconfig, tools->options) for the same cause (issues) that have slightly different behavior.

this will make these 3 to have same behavior and give those cusomters a way to completely off these features they never want.

Comment (Neme12) [reply src/Workspaces/Core/Portable/CodeStyle/CodeStyleHelpers.cs]: I can understand that a refactoring icon may distract some people but isn't that an argument for adding an option to hide it as opposed to going through every single refactoring and setting it to none?

Comment (Neme12) [reply src/Workspaces/Core/Portable/CodeStyle/CodeStyleHelpers.cs]: My point is:
1. We get the refactoring even without setting this to "refactoring only". For example even if my preference is var, I always get a refactoring to use explicit type. Or am I mistaken? Does "none" actually disable the refactoring?
2. As I understand it, "silent" is more than a refactoring, for example it will participate in "fix all", is that true? Having "refactoring" as a synonym for "silent" is a little confusing then, because it's much more than that.

Comment (Neme12) [reply src/Workspaces/Core/Portable/CodeStyle/CodeStyleHelpers.cs]: What's the reason for adding "refactoring only"? I would just expect it to be changed to "Silent" in tools->options to match editorconfig. I find "refactoring" or "refactoring only" a little confusing (but maybe I don't understand the change).

Comment (sharwell) [reply src/Workspaces/Core/Portable/CodeStyle/CodeStyleHelpers.cs]: @Neme12 The behavior of "Silent" was not obvious to users. The behavior was more closely related to what users first thought when they heard "Refactoring". There are still some nuances and inconsistencies (e.g. there are cases where refactorings are still offered when `none` is used), but in general more users have a better understanding of the behavior with fewer words when the terms in this pull request are used.

Comment (sharwell) [reply src/Workspaces/Core/Portable/CodeStyle/CodeStyleHelpers.cs]: @kuhlenh Has a table showing the behavior of `none` and `silent`/`refactoring` which makes it quite clear where everything is expected to work. 😄

Comment (heejaechang) [reply src/Workspaces/Core/Portable/CodeStyle/CodeStyleHelpers.cs]: > Does "none" actually disable the refactoring?

yes, it disables that particular one.

>, for example, it will participate in "fix all"

I believe you are making this distinction since you actually know how code fix/refactoring provider works. from feedbacks you get, most of the users don't/can't distinguish those except icon. they don't seem to even know/care what code fix provider/refactoring provider is.

hidden diagnostic's code fix shows up with refactoring icon even though it is not provided by refactoring provider. so they are the same thing for most users. so we are reflecting it to names.

two are slightly different in behavior and capability they provide. but so far, it looks like users don't care on those much. if we get more feedback/telemetry on those, we will improve on those in future.
