### PR TITLE
Don't trigger naming style violation for prefixed numbers.

### LINKED ISSUE #47569: IDE1006 fires on discard parameters
**Version Used**: 
Microsoft Visual Studio Professional 2019
Version 16.6.3

**Steps to Reproduce**:

1.  Create a function with an unused parameter (I used _ and _1 to handle multiple discarded parameters)
`public object DiscardParameter(string _1)`
2. Define .editorconfig rule
dotnet_naming_rule.parameter_should_be_camelcase.severity = suggestion
dotnet_naming_rule.parameter_should_be_camelcase.symbols = parameter
dotnet_naming_rule.parameter_should_be_camelcase.style = camelcase

**Expected Behavior**:
No warning

**Actual Behavior**:

Severity | Code | Description | Project | File | Line | Suppression   State | Priority
-- | -- | -- | -- | -- | -- | -- | --
Message | IDE1006 | Naming   rule violation: Prefix '_' is not expected | *** | *** | 903 | Active | Normal

Reference:
https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1801?view=vs-2019
>This rule does not flag parameters that are named with the discard symbol, for example, _, _1, and _2

Incompatible rules are confusing

### PR DESCRIPTION
**Pull request by huoyaoyuan**
Fixes #47569 
The rule is quite naive and I'm not sure if it's appropriate.

### CODE REVIEW

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingStyle.cs [hunk 1]
```diff
@@ -179,7 +179,7 @@ public bool IsNameCompliant(string name, out string failureReason)
             // remove specified Prefix, then look for any other common prefixes
             name = StripCommonPrefixes(name.Substring(Prefix.Length), out var prefix);
 
-            if (prefix != string.Empty)
+            if (prefix != string.Empty && !char.IsDigit(name[0]))
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingStyle.cs:182]: not sure if this is ok.  i.e. if would thinkg `_0foo` was ok.  i think it should check all the remainder of hte string and only ignore if it's all a number.

Comment (CyrusNajmabadi) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingStyle.cs:182]: would also need a comment explaining this.

File: src/Analyzers/CSharp/Tests/NamingStyles/NamingStylesTests.cs [hunk 2]
```diff
@@ -1334,5 +1334,36 @@ public async Task TestRecordParameter_ParameterFormattedAsProperties()
 @"public record Foo(int [|MyInt|]);",
                 options: s_options.MergeStyles(s_options.PropertyNamesArePascalCase, s_options.ParameterNamesAreCamelCaseWithPUnderscorePrefix));
         }
+
+        [Theory]
+        [InlineData("_")]
+        [InlineData("_1")]
+        [InlineData("m_1")]
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/NamingStyles/NamingStylesTests.cs:1341]: i don't really ge the `m_1` case.  whyis this treated the same as `_` and `_1`?

Comment (huoyaoyuan) [reply src/Analyzers/CSharp/Tests/NamingStyles/NamingStylesTests.cs:1341]: https://github.com/huoyaoyuan/roslyn/blob/4239a7ae9231e4df5c96efbae7413d3807eb6aeb/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingStyle.cs#L376
The logic strips `m_` like `_`.

Comment (CyrusNajmabadi) [reply src/Analyzers/CSharp/Tests/NamingStyles/NamingStylesTests.cs:1341]: hrmm... there's a strong difference though between these.  i think we're classifying `_` and `_0` (_1, _2, _3, etc.) as discards.  we wouldn't do the same with `m_1`.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingStyle.cs (hunk 1 above)
Comment (davidwengier) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingStyle.cs:182]: Perhaps this helper method from Remove Unused Parameter could be moved so it can be re-used?
https://github.com/dotnet/roslyn/blob/master/src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs#L327-L334

This allows for only one digit after an underscore, but at least we'd have consistency.

File: src/Analyzers/CSharp/Tests/NamingStyles/NamingStylesTests.cs (hunk 2 above)
Comment (huoyaoyuan) [reply src/Analyzers/CSharp/Tests/NamingStyles/NamingStylesTests.cs:1341]: I think it would need more design about how to determine naming style when there are mixed type characters.
It falls into a similar situation I've met in dotnet/runtime#42009

Comment (CyrusNajmabadi) [reply src/Analyzers/CSharp/Tests/NamingStyles/NamingStylesTests.cs:1341]: i think the design is pretty simple here.  Treat underscore-followed-by-number as a discard :)  I would limit it to just that.

Comment (mavasani) [reply src/Analyzers/CSharp/Tests/NamingStyles/NamingStylesTests.cs:1341]: +1 to what @CyrusNajmabadi said.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingStyle.cs (hunk 1 above)
Comment (Forge36) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingStyle.cs:182]: Thanks @davidwengier resolving the conflicting nature of the two rules was my goal with #47569

File: src/Analyzers/CSharp/Tests/NamingStyles/NamingStylesTests.cs (hunk 2 above)
Comment (huoyaoyuan) [reply src/Analyzers/CSharp/Tests/NamingStyles/NamingStylesTests.cs:1341]: Current code fix renames `m_1` to `1`. Is there any consideration to change the logic?

Comment (CyrusNajmabadi) [reply src/Analyzers/CSharp/Tests/NamingStyles/NamingStylesTests.cs:1341]: > Current code fix renames m_1 to 1. Is there any consideration to change the logic?

Yes.  That is clearly wrong.  But it woudl also be out of scope of this PR IMO :)

**Comment by sharwell** [comment]
We'll take this one too design review tomorrow and make sure it's the direction we want.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingStyleRules.cs [hunk 3]
```diff
@@ -109,5 +109,14 @@ private static bool IsInterfaceImplementation(ISymbol symbol)
 
             return false;
         }
+
+        /// <summary>
+        /// Returns true for symbols whose name starts with an underscore and
+        /// are optionally followed by an integer, such as '_', '_1', '_2', etc.
+        /// These are treated as special discard symbol names.
+        /// </summary>
+        internal static bool IsSymbolWithSpecialDiscardName(ISymbol symbol)
```
Comment (mavasani) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingStyleRules.cs:118]: Can we instead make this as extension method on `ISymbol` and move it to https://github.com/dotnet/roslyn/blob/master/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ISymbolExtensions.cs?

**Review by mavasani — APPROVED** [review]
LGTM. Once the helper method is made an extension method, I can merge the PR.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingStyleRules.cs (hunk 3 above)
Comment (huoyaoyuan) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingStyleRules.cs:118]: After I moved, IntelliSense says that the extension is available for `Features`, but not `CodeStyle` project.

Comment (mavasani) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingStyleRules.cs:118]: Which project/file did you move the extension to? Please ensure the file is moved to the shared project at the location mentioned above, which is imported into both CodeStyle and Features layer.

Comment (huoyaoyuan) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingStyleRules.cs:118]: I moved to wrong file, with the same namespace `Microsoft.CodeAnalysis.Shared.Extensions`. It really confuses me that there are so many files named `ISymbolExtension`.

Comment (mavasani) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/NamingStyles/NamingStyleRules.cs]: Yeah, but Roslyn has multiple layers, each requiring its own set of extensions, so it is unavoidable.

**Review by mavasani — APPROVED** [review]
