### PR TITLE
Adjust various places outside of compiler to account for the fact that ArgumentSyntax.Expression can be null.

### LINKED ISSUE #12147: Generate member crashes when Out Variable Declaration is among the arguments
Hover over ```Undefined``` identifier.
```
Undefined(out var c);
```

VS crashes with the following call stack:
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckSyntaxNode(CSharpSyntaxNode syntax)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetTypeInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetTypeInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Extensions.ArgumentSyntaxExtensions.DetermineParameterType(ArgumentSyntax argument, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.GenerateMember.GenerateMethod.CSharpGenerateParameterizedMemberService`1.InvocationExpressionInfo.DetermineParameterType(ArgumentSyntax argument, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.GenerateMember.GenerateMethod.CSharpGenerateParameterizedMemberService`1.InvocationExpressionInfo.<>c__DisplayClass9_0.<DetermineParameterTypes>b__0(ArgumentSyntax a)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.CSharp.GenerateMember.GenerateMethod.CSharpGenerateParameterizedMemberService`1.InvocationExpressionInfo.DetermineParameterTypes(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateParameterizedMemberService`4.SignatureInfo.DetermineParameters(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateParameterizedMemberService`4.SignatureInfo.GenerateMethod(SyntaxGenerator factory, Boolean isAbstract, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateParameterizedMemberService`4.State.<TryFinishInitializingState>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateMethodService`4.State.<GenerateMethodStateAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.GenerateMember.GenerateParameterizedMember.AbstractGenerateMethodService`4.<GenerateMethodAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.CodeFixes.GenerateMember.AbstractGenerateMemberCodeFixProvider.<RegisterCodeFixesAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.<PerformActionAsync>d__2.MoveNext()

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #12147.

@dotnet/roslyn-ide Please review.

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/Diagnostics/GenerateConstructor/GenerateConstructorTests.cs [hunk 1]
```diff
@@ -872,5 +872,45 @@ public bool M(string s, int i, bool b)
...
         }
+
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsGenerateConstructor)]
+        [WorkItem(12147, "https://github.com/dotnet/roslyn/issues/12147")]
+        public async Task TestOutVariableDeclaration_ImplicitlyTyped()
+        {
+            await TestAsync(
+@"class C { void M() { new [|C|](out var a); } }",
+@"class C { public C(out object a) { a = null; } void M() { new C(out var a); } }",
+                                parseOptions: TestOptions.Regular.WithOutVarFeature());
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Diagnostics/GenerateConstructor/GenerateConstructorTests.cs]: indentation is wonky.  this should be at the same indentation of the previous line.

File: src/EditorFeatures/CSharpTest/Diagnostics/GenerateConstructor/GenerateConstructorTests.cs [hunk 2]
```diff
@@ -872,5 +872,45 @@ public bool M(string s, int i, bool b)
...
+        }
+
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsGenerateConstructor)]
+        [WorkItem(12147, "https://github.com/dotnet/roslyn/issues/12147")]
+        public async Task TestOutVariableDeclaration_ImplicitlyTyped_NamedArgument()
+        {
+            await TestAsync(
+@"class C { void M() { new C([|b|]: out var a); } }",
+@"class C { public C(out object b) { b = null; } void M() { new C(b: out var a); } }",
+                                parseOptions: TestOptions.Regular.WithOutVarFeature());
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Diagnostics/GenerateConstructor/GenerateConstructorTests.cs]: What is the reason for these "WithXXXFeature".  IDE features should work the same regardless of parse options.  In our last meeting on this topic, we decided that the presence or absence of the parse option would only cause a compiler error to be issued if you used hte feature, nothing more.  All other behavior would otherwise be the same.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUnboundIdentifiersDiagnosticAnalyzer.cs [hunk 3]
```diff
@@ -55,7 +55,7 @@ protected override bool ConstructorDoesNotExist(SyntaxNode node, SymbolInfo info
             {
                 for (int i = 0; i < constructor.Parameters.Length; i++)
                 {
-                    var typeInfo = model.GetTypeInfo(args[i].Expression);
+                    var typeInfo = model.GetTypeInfo(args[i].Expression != null ? args[i].Expression : args[i].Declaration.Type);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUnboundIdentifiersDiagnosticAnalyzer.cs]: args[i].Expression ?? args[i].Declaration.Type

File: src/Features/CSharp/Portable/GenerateType/CSharpGenerateTypeService.cs [hunk 4]
```diff
@@ -945,7 +946,26 @@ internal override bool IsSimpleName(ExpressionSyntax expression)
                 newObjectCreation = (ObjectCreationExpressionSyntax)newNode.GetAnnotatedNodes(s_annotation).Single();
                 var symbolInfo = speculativeModel.GetSymbolInfo(newObjectCreation, cancellationToken);
                 var parameterTypes = newObjectCreation.ArgumentList.Arguments.Select(
-                    a => speculativeModel.GetTypeInfo(a.Expression, cancellationToken).ConvertedType).ToList();
+                    a =>
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/GenerateType/CSharpGenerateTypeService.cs]: Why the large change here?

File: src/Workspaces/CSharp/Portable/Extensions/ArgumentSyntaxExtensions.cs [hunk 5]
```diff
@@ -105,9 +105,17 @@ public static RefKind GetRefKind(this ArgumentSyntax argument)
             SemanticModel semanticModel,
             CancellationToken cancellationToken)
         {
+            TypeInfo typeInfo;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Extensions/ArgumentSyntaxExtensions.cs]: This code looks nearly identical to the same added code a few files earlier.  Can this code not be shared?

File: src/Workspaces/CSharp/Portable/Simplification/CSharpSimplificationService.Expander.cs [hunk 6]
```diff
@@ -764,9 +767,9 @@ private bool IsInvocationWithDynamicArguments(SimpleNameSyntax originalSimpleNam
                     {
                         foreach (var argument in invocationExpression.ArgumentList.Arguments)
                         {
-                            if (argument != null && argument.Expression != null)
+                            if (argument != null)
                             {
-                                var typeinfo = semanticModel.GetTypeInfo(argument.Expression);
+                                var typeinfo = semanticModel.GetTypeInfo(argument.Expression != null ? argument.Expression : argument.Declaration.Type);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Simplification/CSharpSimplificationService.Expander.cs]: argument.Expression ?? argument.Declaration.Type

**Comment by CyrusNajmabadi** [comment]
Small nits, a few important questions.

File: src/EditorFeatures/CSharpTest/Diagnostics/GenerateConstructor/GenerateConstructorTests.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/EditorFeatures/CSharpTest/Diagnostics/GenerateConstructor/GenerateConstructorTests.cs]: Will fix

---
In reply to: [68112090](https://github.com/dotnet/roslyn/pull/12159#discussion_r68112090) [](ancestors = 68112090)

File: src/EditorFeatures/CSharpTest/Diagnostics/GenerateConstructor/GenerateConstructorTests.cs (hunk 2 above)
Comment (AlekseyTs) [inline src/EditorFeatures/CSharpTest/Diagnostics/GenerateConstructor/GenerateConstructorTests.cs]: Will remove.

---
In reply to: [68112365](https://github.com/dotnet/roslyn/pull/12159#discussion_r68112365) [](ancestors = 68112365)

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUnboundIdentifiersDiagnosticAnalyzer.cs (hunk 3 above)
Comment (AlekseyTs) [inline src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUnboundIdentifiersDiagnosticAnalyzer.cs]: sure

---
In reply to: [68112502](https://github.com/dotnet/roslyn/pull/12159#discussion_r68112502) [](ancestors = 68112502)

File: src/Features/CSharp/Portable/GenerateType/CSharpGenerateTypeService.cs (hunk 4 above)
Comment (AlekseyTs) [inline src/Features/CSharp/Portable/GenerateType/CSharpGenerateTypeService.cs]: I am not sure how to answer this question. Do you see any unnecessary parts?

---
In reply to: [68112768](https://github.com/dotnet/roslyn/pull/12159#discussion_r68112768) [](ancestors = 68112768)

File: src/Workspaces/CSharp/Portable/Extensions/ArgumentSyntaxExtensions.cs (hunk 5 above)
Comment (AlekseyTs) [inline src/Workspaces/CSharp/Portable/Extensions/ArgumentSyntaxExtensions.cs]: I assume you are talking about the change in GetDelegatingConstructor. It is nearly identical, but not quite the same. I tried to keep the code as close as possible to the original behavior. If you are fine with changing GetDelegatingConstructor to use DetermineParameterType, I will make the change.

---
In reply to: [68112952](https://github.com/dotnet/roslyn/pull/12159#discussion_r68112952) [](ancestors = 68112952)

File: src/Workspaces/CSharp/Portable/Simplification/CSharpSimplificationService.Expander.cs (hunk 6 above)
Comment (AlekseyTs) [inline src/Workspaces/CSharp/Portable/Simplification/CSharpSimplificationService.Expander.cs]: sure

---
In reply to: [68113256](https://github.com/dotnet/roslyn/pull/12159#discussion_r68113256) [](ancestors = 68113256)

File: src/Workspaces/CSharp/Portable/Extensions/ArgumentSyntaxExtensions.cs (hunk 5 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Extensions/ArgumentSyntaxExtensions.cs]: Yeah.  Can we try that out.  I feel like these shoudl be the same.

File: src/EditorFeatures/CSharpTest/Diagnostics/GenerateConstructor/GenerateConstructorTests.cs (hunk 2 above)
Comment (AlekseyTs) [inline src/EditorFeatures/CSharpTest/Diagnostics/GenerateConstructor/GenerateConstructorTests.cs]: Actually, a couple of scenarios are affected by the parse options because some semantic errors are suppressed due to the presence of parse errors. I will open an issue track this separately.   

---
In reply to: [68117890](https://github.com/dotnet/roslyn/pull/12159#discussion_r68117890) [](ancestors = 68117890,68112365)

**Comment by AlekseyTs** [comment]
Addressed feedback provided so far.

File: src/EditorFeatures/CSharpTest/Diagnostics/GenerateConstructor/GenerateConstructorTests.cs (hunk 2 above)
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Diagnostics/GenerateConstructor/GenerateConstructorTests.cs]: What parse errors happen?  From our discussion on parse options previously, we should always be parsing code the same way, regardless of feature flags or language versions.  All those flags do is add an error if you are using a feature that is not allowed.  But no other changes should be observable.

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by CyrusNajmabadi** [comment]
:+1: with VSI passing.

**Comment by AlekseyTs** [comment]
test vsi please

**Comment by jaredpar** [comment]
retest vsi please

**Comment by CyrusNajmabadi** [comment]
vsi doesn't seem to be testing.

File: src/EditorFeatures/CSharpTest/Diagnostics/GenerateConstructor/GenerateConstructorTests.cs (hunk 2 above)
Comment (AlekseyTs) [inline src/EditorFeatures/CSharpTest/Diagnostics/GenerateConstructor/GenerateConstructorTests.cs]: Opened https://github.com/dotnet/roslyn/issues/12182 to track this issue.
