### PR TITLE
Ensure proper validation of operator signatures when tuple types are involved.

### LINKED ISSUE #11530: Tuple implementation rejects implicit operators
The following code is improperly rejected by the tuple implementation
```cs
namespace System
{
    public struct ValueTuple<T1, T2>
    {
        public T1 Item1;
        public T2 Item2;

        // error: conversion must convert to or from enclosing type
        public static implicit operator Collections.Generic.KeyValuePair<T1, T2>(ValueTuple<T1, T2> tuple)
        {
            T1 k;
            T2 v;
            (k, v) = tuple;
            return new KeyValuePair<T1, T2>(k, v);
        }

        // error: conversion must convert to or from enclosing type
        public static implicit operator ValueTuple<T1, T2>(Collections.Generic.KeyValuePair<T1, T2> kvp)
        {
            return (kvp.Key, kvp.Value);
        }
    }
}
```

This was tested against https://github.com/jcouv/roslyn/tree/tuple-deconstruction (from https://github.com/dotnet/roslyn/pull/11457) at commit https://github.com/jcouv/roslyn/commit/c7b60a478ce0f5993d1e7a85af17545b96611a9e

### LINKED ISSUE #11986: Tuple implementation rejects implicit operators
Related to #11530, the following code is improperly rejected by the tuple implementation in `master`.

```cs
namespace System
{
    public struct ValueTuple<T1, T2>
    {
        public T1 Item1;
        public T2 Item2;
        public ValueTuple(T1 item1, T2 item2)
        {
            this.Item1 = item1;
            this.Item2 = item2;
        }

        // error: conversion must convert to or from enclosing type
        public static explicit operator int((T1, T2)? source)
        {
            return 1;
        }
        // error: conversion must convert to or from enclosing type
        public static explicit operator long(Nullable<(T1, T2)> source)
        {
            return 1;
        }
        // error: conversion must convert to or from enclosing type
        public static explicit operator string(Nullable<ValueTuple<T1, T2>> source)
        {
            return "";
        }
        // error: conversion must convert to or from enclosing type
        public static explicit operator double(ValueTuple<T1, T2>? source)
        {
            return 1;
        }
    }
}
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #11986.
Fixes #11530.

@dotnet/roslyn-compiler, @VSadov, @jcouv Please review.

### CODE REVIEW

File: src/Compilers/VisualBasic/Portable/Semantics/Operators.vb [hunk 1]
```diff
@@ -453,7 +453,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
             If containingType.SpecialType = SpecialType.System_Nullable_T Then
                 Return typeFromSignature Is containingType
             Else
-                Return typeFromSignature.GetNullableUnderlyingTypeOrSelf() Is containingType
+                Return typeFromSignature.GetNullableUnderlyingTypeOrSelf().GetTupleUnderlyingTypeOrSelf() = containingType.GetTupleUnderlyingTypeOrSelf()
```
Comment (gafter) [inline src/Compilers/VisualBasic/Portable/Semantics/Operators.vb]: >containingType.GetTupleUnderlyingTypeOrSelf() [](start = 108, length = 45)

Can containingType be a tuple type symbol?

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Semantics/Operators.vb]: Yes, it can. This function is called at the use site to verify that a method syntactically declared as an operator has a valid signature.

**Comment by AlekseyTs** [comment]
Ping. @dotnet/roslyn-compiler, @VSadov, @jcouv Please review.

**Comment by gafter** [comment]
:shipit:

**Comment by VSadov** [comment]
LGTM
