### PR TITLE
Fix formatting for tuple pointers

### LINKED ISSUE #50723: Auto-format inserts space between tuple type and pointer star
**Version Used**:

Compiler version: '3.8.0-5.20604.10 (9ed4b774)'. Language version: 9.0.

Visual Studio 16.8.4

Also reproduced with Compiler version: '3.9.0-3.21056.4 (e5eb71d6)'. Language version: 9.0. 

Visual Studio 16.9.0 Preview 32.

**Steps to Reproduce**:

1. Given the following:

```csharp
public unsafe static class Program
{
    public static void Main(string[] args)
    {
        int* intPointer = null;
        (int, int)* intIntPointer = null;
    }
}
```

2. Invoke automatic code formatting (IE: Using Code Cleanup, Edit -> Advanced -> Format Document, retyping the semicolon, etc.)

**Expected Behavior**:

Nothing changes as the code is well-formed. 

**Actual Behavior**:

A space is inserted between the tuple type and the pointer `*`:

```csharp
public unsafe static class Program
{
    public static void Main(string[] args)
    {
        int* intPointer = null;
        (int, int) * intIntPointer = null;
        //        ^_______________This space was added
    }
}
```

------------

I've reproduced this with a completely vanilla Visual Studio environment (Default settings, no extensions, no EditorConfig), so I don't think it's a weird setting I accidentally configured somewhere. [Here's my .editorconfig though](https://github.com/InfectedLibraries/Biohazrd/blob/c55d7c5748be0152d4d91cd17d9b62640c5d4058/.editorconfig) if it's needed.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #50723

This PR just changes the order of the pointer check.

Confirmed the test fails before making the fix:

image

### CODE REVIEW

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/TokenBasedFormattingRule.cs [hunk 1]
```diff
@@ -472,6 +472,13 @@ private static SyntaxList<UsingDirectiveSyntax> GetUsings(SyntaxNode node)
                 return CreateAdjustSpacesOperation(0, AdjustSpacesOption.ForceSpacesIfOnSingleLine);
             }
 
+            // pointer case for regular pointers
+            if ((currentToken.Kind() == SyntaxKind.AsteriskToken && currentToken.Parent is PointerTypeSyntax) ||
+                (previousToken.Kind() == SyntaxKind.AsteriskToken && previousToken.Parent is PrefixUnaryExpressionSyntax))
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/TokenBasedFormattingRule.cs:477]: It's prefer two separate conditions here. With a doc for each stating what case each is for.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/TokenBasedFormattingRule.cs [hunk 2]
```diff
@@ -483,6 +490,8 @@ private static SyntaxList<UsingDirectiveSyntax> GetUsings(SyntaxNode node)
 
                 case SyntaxKind.CloseParenToken:
                 case SyntaxKind.CloseBracketToken:
+                    // This isn't correct for a tuple pointer `(int, int)* p` where there shouldn't be a space after
+                    // the closing parenthesis. This case is already handled above. So we're okay here.
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/TokenBasedFormattingRule.cs:494]: This comment seems odd.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Thanks for review. I applied your requested changes.

**Review by CyrusNajmabadi — APPROVED** [review]
