### PR TITLE
Fixed variable name for Extract Local refactoring

### LINKED ISSUE #21665: Extract Local refactoring: variable name should be equal to value tuple field name
**Version Used**: 
current master branch
**Steps to Reproduce**:

```csharp
var tuple = (key: "key", value: DateTime.Now.ToString());
```

**Expected Behavior**:
```csharp
var value = DateTime.Now.ToString();
var tuple = (key: "key", value: value);
```
**Actual Behavior**:
```csharp
var value1 = DateTime.Now.ToString();
var tuple = (key: "key", value: value1);
```

### PR DESCRIPTION
**Pull request by zaytsev-victor**
**Customer scenario**

Extract Local refactoring: variable name should be equal to value tuple field name

**Bugs this fixes:**

Fixes #21665

**Risk**
Low

**Performance impact**
Low

**Is this a regression from a previous update?**
No

**Root cause analysis:**

```GetExistingSymbols``` doesn't exclude tuple field names.

**How was the bug found?**

customer reported

### CODE REVIEW

**Comment by DustinCampbell** [comment]
LGTM

File: src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.cs [hunk 1]
```diff
@@ -240,10 +240,10 @@ private CodeAction CreateAction(State state, bool allOccurrences, bool isConstan
         private static IEnumerable<ISymbol> GetExistingSymbols(
             SemanticModel semanticModel, SyntaxNode container, CancellationToken cancellationToken)
         {
-            // Ignore an annonymous type property.  It's ok if they have a name that 
+            // Ignore an annonymous type property and value tuple type field. It's ok if they have a name that 
             // matches the name of the local we're introducing.
             return semanticModel.GetAllDeclaredSymbols(container, cancellationToken)
-                                .Where(s => !s.IsAnonymousTypeProperty());
+                                .Where(s => !(s.IsAnonymousTypeProperty() || s.IsTupleField()));
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.cs]: FYI, this code exists in several features.  We should probably update it in all others as well.  Ideally, they would share a single implementation for all of them to use.
