### PR TITLE
Target-typed switch expression

### LINKED ISSUE #14965: Throwing expressions which can be converted to Exception
The current specification has this in 8.9.5:

> A throw statement with an expression throws the value produced by evaluating the expression. The expression must denote a value of the class type System.Exception, of a class type that derives from System.Exception or of a type parameter type that has System.Exception (or a subclass thereof) as its effective base class. If evaluation of the expression produces null, a System.NullReferenceException is thrown instead.

As part of the ECMA standardization process, we noted that this is a bit unfriendly for `dynamic`, and is unusual in terms of not taking implicit conversions to `Exception` into account. `mcs` does both of these, and the ECMA group has decided to permit this, including the following wording in the upcoming standard:

> A throw statement with an expression throws an exception produced by evaluating the expression. The expression shall be implicitly convertible to `System.Exception`, and the result of evaluating the expression is converted to `System.Exception` before being thrown. If the result of the conversion is null, a `System.NullReferenceException` is thrown instead.

We would like Roslyn to implement our retroactive change to the Standard, with appropriate levels of grovelling apology (from us). Note that this potentially affects an error message as well:

> error CS0155: The type caught or thrown must be derived from System.Exception

### LINKED ISSUE #35958: Compiler crash when tuple equality used with a conversion-from-expression
The [following code causes the C# compiler to crash](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDZICYgNQA+AAgAwAERAjANwCwAUA0QMwUBMZAwmQN4NkCKrKgDYKAFjIBZCGgB2ACgCU/QX3qDNFShwhkAvGQXKDAPl4BfJXQ1aBVAJzGISaUoOGFU1xCXXVAhYBZMGiEtImPEH00UA===):

``` c#
using System;

public class C {
    public static void Main()
    {
        Action a = (() => {});
        Console.WriteLine((a, M) == (M, a));
    }
    
    static void M() {}
}
```

the failure is

``` none
System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.BoundLocal' to type 'Microsoft.CodeAnalysis.CSharp.BoundMethodGroup'.
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.MakeConversionNode(BoundConversion oldNode, SyntaxNode syntax, BoundExpression rewrittenOperand, Conversion conversion, Boolean checked, Boolean explicitCastInCode, ConstantValue constantValueOpt, TypeSymbol rewrittenType)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.MakeConversionNode(SyntaxNode syntax, BoundExpression rewrittenOperand, Conversion conversion, TypeSymbol rewrittenType, Boolean checked, Boolean explicitCastInCode, ConstantValue constantValueOpt)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.RewriteTupleSingleOperator(Single single, BoundExpression left, BoundExpression right, TypeSymbol boolType, BinaryOperatorKind operatorKind)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.RewriteTupleOperator(TupleBinaryOperatorInfo operator, BoundExpression left, BoundExpression right, TypeSymbol boolType, ArrayBuilder`1 temps, BinaryOperatorKind operatorKind)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.RewriteNonNullableNestedTupleOperators(Multiple operators, BoundExpression left, BoundExpression right, TypeSymbol type, ArrayBuilder`1 temps, ArrayBuilder`1 effects, BinaryOperatorKind operatorKind)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.RewriteTupleNestedOperators(Multiple operators, BoundExpression left, BoundExpression right, TypeSymbol boolType, ArrayBuilder`1 temps, BinaryOperatorKind operatorKind)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitTupleBinaryOperator(BoundTupleBinaryOperator node)
   at Microsoft.CodeAnalysis.CSharp.BoundTupleBinaryOperator.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitExpressionImpl(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.DoVisitList[T](ImmutableArray`1 list)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitCall(BoundCall node)
   at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitExpressionImpl(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitUnusedExpression(BoundExpression expression)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.RewriteExpressionStatement(BoundExpressionStatement node, Boolean suppressInstrumentation)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitExpressionStatement(BoundExpressionStatement node)
   at Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitPossibleUsingDeclaration(BoundStatement node, ImmutableArray`1 statements, Int32 statementIndex, Boolean& replacedLocalDeclarations)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitStatementSubList(ArrayBuilder`1 builder, ImmutableArray`1 statements, Int32 startIndex)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitBlock(BoundBlock node)
   at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Rewrite(CSharpCompilation compilation, MethodSymbol method, Int32 methodOrdinal, NamedTypeSymbol containingType, BoundStatement statement, TypeCompilationState compilationState, SynthesizedSubmissionFields previousSubmissionFields, Boolean allowOmissionOfConditionalCalls, Boolean instrumentForDynamicAnalysis, ImmutableArray`1& dynamicAnalysisSpans, DebugDocumentProvider debugDocumentProvider, DiagnosticBag diagnostics, Boolean& sawLambdas, Boolean& sawLocalFunctions, Boolean& sawAwaitInExceptionHandler)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.LowerBodyOrInitializer(MethodSymbol method, Int32 methodOrdinal, BoundStatement body, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState, Boolean instrumentForDynamicAnalysis, DebugDocumentProvider debugDocumentProvider, ImmutableArray`1& dynamicAnalysisSpans, DiagnosticBag diagnostics, VariableSlotAllocator& lazyVariableSlotAllocator, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, StateMachineTypeSymbol& stateMachineTypeOpt)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
```

I believe the root cause is that the design of the tuple equality operator requires deferring the tuple element conversions.  But conversions that are *conversion-from-expression*s should not be deferred.

/cc @jcouv

### PR DESCRIPTION
**Pull request by gafter**
This PR adds support for a target-typed switch expression.

This is the first time where we have an expression form that must be converted when it is used with its natural type.  That is because an expression such as `e switch { 1 => a, 2 => b }` must not convert `a` to `b` if the target type is some common supertype (e.g. `object`), but must do the conversion if it is needed to use the expression in its natural type.  Moreover, there might be errors using the expression in its natural type (e.g. an obsolete user-defined conversion).  These errors must only be reported when the expression is used without being converted to some type.

In order to do this we add a new bottleneck for converting an expression to its natural type.  Every rvalue expression must either be converted, or be passed through `BindToNaturalType(e, diagnostics)`.  To ensure that we've handled all contexts, we instrument every reference to a local or parameter, and add a flag to it when it has "been converted" (in debug mode only).  Then, in definite assignment analysis we assert that every rvalue expression that needs to have been converted (including switch expressions, tuple literals, parameters and locals) has indeed been converted.  Since we have excellent test coverage of language forms that have subexpressions using parameters and locals, this flushed out scores of places where binding required changes.  This will also help ensure that new language constructs are handled properly.

A new invariant is that after binding, there are no unconverted tuple literals or unconverted switch expressions remaining.  Every one of them has been replaced by (converted to) its "converted" form.  The assertion mentioned above also checks this.

The PR also includes an overhaul to the handling of tuple equality.  Now, in initial binding, we simply produce converted tuples or converted tuple literals for operands.  In lowering, we reorder the operations so that conversions that should be deferred are done later.

Fixes #14965 
Fixes #35958
Specified by https://github.com/dotnet/csharplang/issues/2389

### CODE REVIEW

**Comment by 333fred** [comment]
>         public void SwitchExpression_NoCommonType()

Consider adding a new test to replicate the scenario this was intended to cover, where there truly is not common type between the branches.

---
Refers to: src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_ISwitchExpression.cs:173 in 27d287e. [](commit_id = 27d287e8478fef87e6c79c4325c25b0c0da6b69b, deletion_comment = False)

File: src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IConstructorBodyOperation.cs [hunk 1]
```diff
@@ -122,18 +122,21 @@ public C() : base()
...
-          Arguments(0)
-  BlockBody: 
+            Arguments(0)
+    BlockBody: 
     IBlockOperation (1 statements) (OperationKind.Block, Type: null) (Syntax: '{ throw null; }')
-      IThrowOperation (OperationKind.Throw, Type: null) (Syntax: 'throw null;')
-        ILiteralOperation (OperationKind.Literal, Type: null, Constant: null) (Syntax: 'null')
-  ExpressionBody: 
+        IThrowOperation (OperationKind.Throw, Type: null) (Syntax: 'throw null;')
+        IConversionOperation (TryCast: False, Unchecked) (OperationKind.Conversion, Type: System.Exception, Constant: null, IsImplicit) (Syntax: 'null')
```
Comment (333fred) [inline src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IConstructorBodyOperation.cs]: Formatting seems very weird here, operands should be indented from parents.. In general there are a bunch of formatting changes to the IOperation unit tests that don't seem relevant, please revert them.

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs [hunk 2]
```diff
@@ -126,14 +139,34 @@ internal partial class Binder
...
-            { WasCompilerGenerated = wasCompilerGenerated };
+                type: destination) { WasCompilerGenerated = wasCompilerGenerated };
+        }
+
+        /// <summary>
+        /// Rewrite the expressions in the switch expression arms to add a conversion to the destination type.
+        /// </summary>
+        private BoundExpression ConvertSwitchExpression(BoundUnconvertedSwitchExpression source, TypeSymbol destination, DiagnosticBag diagnostics, bool hasErrors = false)
+        {
+            var builder = ArrayBuilder<BoundSwitchExpressionArm>.GetInstance();
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: Specify length.

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs [hunk 3]
```diff
@@ -126,14 +139,34 @@ internal partial class Binder
...
+            foreach (var oldCase in source.SwitchArms)
+            {
+                var oldValue = oldCase.Value;
+                var newValue = GenerateConversionForAssignment(destination, oldValue, diagnostics);
+                var newCase = (oldValue == newValue) ? oldCase :
+                    new BoundSwitchExpressionArm(oldCase.Syntax, oldCase.Locals, oldCase.Pattern, oldCase.WhenClause, newValue, oldCase.Label, oldCase.HasErrors);
+                builder.Add(newCase);
+            }
+
+            var newSwitchArms = builder.ToImmutableAndFree();
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: Could consider an optimization where if all cases are the same, we don't need to create a new array.

File: src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs [hunk 4]
```diff
@@ -218,6 +220,7 @@ private BoundExpression FixTupleLiteral(ArrayBuilder<DeconstructionVariable> che
                     boundRHS = GenerateConversionForAssignment(mergedTupleType, boundRHS, diagnostics);
                 }
             }
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs]: Unnecessary blank line

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 5]
```diff
@@ -225,10 +225,16 @@ internal TypeSymbol CreateErrorType(string name = "")
         /// </summary>
         internal BoundExpression BindValue(ExpressionSyntax node, DiagnosticBag diagnostics, BindValueKind valueKind)
         {
+            // PROTOTYPE(ngafter): Should we have a version of this that does the BindToNaturalType treatment?
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: Prototype comment, please address or file a bug.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 6]
```diff
@@ -2729,19 +2735,20 @@ private BoundExpression BindArgumentExpression(DiagnosticBag diagnostics, Expres
                 var kind = result.ConversionForArg(arg);
                 BoundExpression argument = arguments[arg];
 
-                if (!kind.IsIdentity || argument.Kind == BoundKind.TupleLiteral)
+                // CONSIDER: should we create an (Identity) conversion when the kind is Identity but the types differ?
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: Please address or file a follow up bug

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 7]
```diff
@@ -2759,6 +2766,17 @@ private BoundExpression BindArgumentExpression(DiagnosticBag diagnostics, Expres
                     Debug.Assert(parameterTypeWithAnnotations.HasType);
                     arguments[arg] = ((BoundDiscardExpression)argument).SetInferredTypeWithAnnotations(parameterTypeWithAnnotations);
                 }
+                else if (argument.NeedsToBeConverted())
+                {
+                    Debug.Assert(kind.IsIdentity);
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: Is this assert necessary? It's part of the if/else structure.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 8]
```diff
@@ -2885,8 +2903,8 @@ private BoundExpression BindArrayCreationExpression(ArrayCreationExpressionSynta
                 {
                     if (arg.Kind() != SyntaxKind.OmittedArraySizeExpression)
                     {
-                        var size = BindValue(arg, diagnostics, BindValueKind.RValue);
-                        Error(diagnostics, ErrorCode.ERR_InvalidArray, dimension[0]);
+                        var size = BindRValueWithoutTargetType(arg, diagnostics);
+                        Error(diagnostics, ErrorCode.ERR_InvalidArray, arg);
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: >arg [](start = 71, length = 3)

Why change the error location?

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs [hunk 9]
```diff
@@ -174,6 +175,8 @@ private static ImmutableArray<MethodSymbol> GetOriginalMethods(OverloadResolutio
 
         private BoundExpression BindArgListOperator(InvocationExpressionSyntax node, DiagnosticBag diagnostics, AnalyzedArguments analyzedArguments)
         {
+            bool wasError = analyzedArguments.HasErrors;
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: nit: consider naming `hasErrors` instead.

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs [hunk 10]
```diff
@@ -198,6 +201,11 @@ private BoundExpression BindArgListOperator(InvocationExpressionSyntax node, Dia
                 else if (argument.Type.IsVoidType())
                 {
                     Error(diagnostics, ErrorCode.ERR_CantUseVoidInArglist, argument.Syntax);
+                    wasError = true;
+                }
+                else if (analyzedArguments.RefKind(i) == RefKind.None)
+                {
+                    analyzedArguments.Arguments[i] = BindToNaturalType(analyzedArguments.Arguments[i], diagnostics);
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: Do we want to set HasErrors if this produces errors as well?

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs [hunk 11]
```diff
@@ -389,38 +402,19 @@ private void CheckNamedArgumentsForDynamicInvocation(AnalyzedArguments arguments
 
         private ImmutableArray<BoundExpression> BuildArgumentsForDynamicInvocation(AnalyzedArguments arguments, DiagnosticBag diagnostics)
         {
-            for (int i = 0; i < arguments.Arguments.Count; i++)
+            var builder = ArrayBuilder<BoundExpression>.GetInstance(arguments.Arguments.Count);
+            builder.AddRange(arguments.Arguments);
+            for (int i = 0, n = builder.Count; i < n; i++)
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: Aside: Man is this so much easier to understand.

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs [hunk 12]
```diff
@@ -957,15 +951,23 @@ private void CheckRestrictedTypeReceiver(BoundExpression expression, Compilation
...
-                        if (unboundLambda != null)
+                        switch (argument)
                         {
-                            var boundWithErrors = unboundLambda.BindForErrorRecovery();
-                            diagnostics.AddRange(boundWithErrors.Diagnostics);
+                            case UnboundLambda unboundLambda:
+                                var boundWithErrors = unboundLambda.BindForErrorRecovery();
+                                diagnostics.AddRange(boundWithErrors.Diagnostics);
+                                break;
+                            case BoundTupleLiteral _:
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: >_ [](start = 51, length = 1)

nit: you could just not put anything here at all

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 13]
```diff
@@ -844,6 +856,45 @@ protected BoundExpression BindInferredVariableInitializer(DiagnosticBag diagnost
             return expression;
         }
 
+        internal BoundExpression BindToNaturalType(BoundExpression expression, DiagnosticBag diagnostics)
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: Why is this in `Binder_Statements.cs`? Seems like it should be in `Binder_Expressions.cs`

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 14]
```diff
@@ -844,6 +856,45 @@ protected BoundExpression BindInferredVariableInitializer(DiagnosticBag diagnost
...
+        {
+            BoundExpression result;
+            switch (expression)
+            {
+                case BoundConvertedSwitchExpression _:
+                case BoundConvertedTupleLiteral _:
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: Could combine these labels with `default`

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 15]
```diff
@@ -2117,6 +2173,30 @@ internal BoundExpression GenerateConversionForAssignment(TypeSymbol targetType,
                     {
                         var stackAllocExpression = (BoundStackAllocArrayCreation)operand;
                         Error(diagnostics, ErrorCode.ERR_StackAllocConversionNotPossible, syntax, stackAllocExpression.ElementType, targetType);
+                        return;
+                    }
+                case BoundKind.UnconvertedSwitchExpression:
+                    {
+                        var switchExpression = (BoundUnconvertedSwitchExpression)operand;
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: Nit: add variable to case declaration.

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 16]
```diff
@@ -2117,6 +2173,30 @@ internal BoundExpression GenerateConversionForAssignment(TypeSymbol targetType,
...
+                        {
+                            var armConversion = this.Conversions.ClassifyImplicitConversionFromExpression(arm.Value, targetType, ref useSiteDiagnostics);
+                            if (!armConversion.IsImplicit)
+                            {
+                                GenerateImplicitConversionError(diagnostics, arm.Value.Syntax, conversion, arm.Value, targetType);
+                                reportedError = true;
+                            }
+                        }
+
+                        Debug.Assert(reportedError);
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: Why assert this then immediately check the opposite of the error? We definitely don't have any tests that will the if

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 17]
```diff
@@ -2255,21 +2335,17 @@ internal BoundExpression BindBooleanExpression(ExpressionSyntax node, Diagnostic
                             Error(diagnostics, ErrorCode.WRN_IncorrectBooleanAssg, assignment.Syntax);
                         }
                     }
-
-                    return expr;
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: Why do we need to create a conversion in the identity case?

File: src/Compilers/CSharp/Portable/Binder/Binder_TupleOperators.cs [hunk 18]
```diff
@@ -93,29 +90,21 @@ private BoundExpression ApplyConvertedTypes(BoundExpression expr, TupleBinaryOpe
...
             }
 
-            if (left.IsLiteralNull() && right.IsLiteralNull())
+            int ignored = 0;
+            BoundExpression comparison = BindSimpleBinaryOperator(node, diagnostics, left, right, ref ignored);
+            switch (comparison)
             {
-                return new TupleBinaryOperatorInfo.NullNull(kind);
-            }
+                case BoundLiteral literal:
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_TupleOperators.cs]: >literal [](start = 34, length = 7)

unused declaration?

File: src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs [hunk 19]
```diff
@@ -318,7 +318,7 @@ private BoundForEachStatement BindForEachPartsWorker(DiagnosticBag diagnostics,
                         var variables = node.Variable;
                         if (variables.IsDeconstructionLeft())
                         {
-                            var valuePlaceholder = new BoundDeconstructValuePlaceholder(_syntax.Expression, collectionEscape, iterationVariableType.Type).MakeCompilerGenerated();
+                            var valuePlaceholder = new BoundDeconstructValuePlaceholder(_syntax.Expression, collectionEscape, iterationVariableType.Type) { WasCompilerGenerated = true };
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs]: Is this a necessary change?

File: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml [hunk 20]
```diff
@@ -1199,6 +1193,23 @@
...
+  </Node>
+
+  <!-- 
+  Switch expressions can convert to the target type.
+  Once converted to a target type, they cannot be target-typed again. 
+  The Converted switch expression is one which has been already converted to a target type.
+  Converted switch expressions always has a type.
+  -->
+  <Node Name="BoundConvertedSwitchExpression" Base="BoundSwitchExpression">
+    <!-- Converted switch expression must have a type, even if that's `void` for a statement. -->
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml]: >even if that's `void` for a statement. [](start = 55, length = 38)

Switch expressions can't be statements?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 21]
```diff
@@ -3792,6 +3792,11 @@ UnboundLambda getUnboundLambda(BoundLambda expr, VariableState variableState)
 
         private void CheckMethodConstraints(SyntaxNode syntax, MethodSymbol method)
         {
+            if (_disableDiagnostics)
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: This change seems unrelated to this PR?

File: src/Tools/Source/CompilerGeneratorTools/Source/BoundTreeGenerator/BoundNodeClassWriter.cs [hunk 22]
```diff
@@ -894,48 +894,11 @@ private void WriteType(TreeType node)
             {
                 WriteAccept(node.Name);
                 WriteUpdateMethod(node as Node);
-                WriteShallowCloneMethodIfNeeded(node as Node);
             }
 
             WriteClassFooter(node);
         }
 
-        private void WriteShallowCloneMethodIfNeeded(Node node)
```
Comment (333fred) [inline src/Tools/Source/CompilerGeneratorTools/Source/BoundTreeGenerator/BoundNodeClassWriter.cs]: Did this change need to be made as part of this?

File: src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs [hunk 23]
```diff
@@ -836,9 +836,11 @@ public BoundSequence Sequence(BoundExpression[] sideEffects, BoundExpression res
             return new BoundSequence(Syntax, ImmutableArray<LocalSymbol>.Empty, sideEffects.AsImmutableOrNull(), result, type ?? result.Type) { WasCompilerGenerated = true };
         }
 
-        public BoundSequence Sequence(ImmutableArray<LocalSymbol> locals, ImmutableArray<BoundExpression> sideEffects, BoundExpression result)
+        public BoundExpression Sequence(ImmutableArray<LocalSymbol> locals, ImmutableArray<BoundExpression> sideEffects, BoundExpression result)
         {
-            return new BoundSequence(Syntax, locals, sideEffects, result, result.Type) { WasCompilerGenerated = true };
+            return
+                locals.IsDefaultOrEmpty && sideEffects.IsDefaultOrEmpty ? result :
+                new BoundSequence(Syntax, locals, sideEffects, result, result.Type) { WasCompilerGenerated = true };
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs]: Consider indenting this line so it's clear it's part of a ternary, and not just being && or || with the previous line.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperator.cs [hunk 24]
```diff
@@ -813,7 +813,6 @@ private BoundExpression MakeOptimizedGetValueOrDefault(SyntaxNode syntax, BoundE
         {
             // If the expression is of nullable type then call GetValueOrDefault. If not,
             // then just use its value.
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BinaryOperator.cs]: Only change in this file? Consider reverting.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs [hunk 25]
```diff
@@ -730,6 +730,11 @@ private BoundExpression BoxReceiver(BoundExpression rewrittenReceiver, NamedType
                 case BoundKind.Local:
                     return localsMayBeAssignedOrCaptured || ((BoundLocal)expression).LocalSymbol.RefKind != RefKind.None;
 
+                case BoundKind.TypeExpression:
+                    return false;
+
+                // CONSIDER: Could add support for a (converted) method group.  It cannot change if the receiver cannot change.
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs]: Please handle or file a bug.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs [hunk 26]
```diff
@@ -32,23 +32,6 @@ public override BoundNode VisitConversion(BoundConversion node)
             var toType = node.Type;
             Debug.Assert(result.Type.Equals(toType, TypeCompareKind.IgnoreDynamicAndTupleNames | TypeCompareKind.IgnoreNullableModifiersForReferenceTypes));
 
-            // 4.1.6 C# spec: To force a value of a floating point type to the exact precision of its type, an explicit cast can be used.
-            // It means that explicit casts to (double) or (float) should be preserved on the node.
-            // If original conversion has become something else with unknown precision, add an explicit identity cast.
-            if (!_inExpressionLambda &&
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs]: Why is this removed?

Comment (333fred) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs]: Ah, I see that it was moved. 

---
In reply to: [301354883](https://github.com/dotnet/roslyn/pull/37052#discussion_r301354883) [](ancestors = 301354883)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs [hunk 27]
```diff
@@ -663,58 +694,83 @@ private BoundExpression MakeImplicitConversion(BoundExpression rewrittenOperand,
...
-                    return objectCreation.Arguments[0];
-                }
+                // Detect the lowered nullable conversion from value type K to type Nullable<K>
+                case BoundObjectCreationExpression { Arguments: { Length: 1 } args }:
+                    return args[0];
+
+                // Detect the unlowered nullable conversion from value type K to type Nullable<K>
+                // This arises in lowering tuple equality operators
+                case BoundConversion
+                { Conversion: { Kind: ConversionKind.ImplicitNullable }, Operand: var convertedArgument }
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs]: I'm really not a fan of this formatting, as this is where the opening brace would go if there was a `:` on the previous line. Can we indent this, or reformat on onto the previous line? Same for the next case.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TupleBinaryOperator.cs [hunk 28]
```diff
@@ -32,33 +35,116 @@ public override BoundNode VisitTupleBinaryOperator(BoundTupleBinaryOperator node
...
             }
+        }
 
-            return _factory.Sequence(locals, effects, returnValue);
+        private BoundExpression PushDownImplicitTupleConversion(
+            BoundExpression expr,
+            ArrayBuilder<BoundExpression> initEffects,
+            ArrayBuilder<LocalSymbol> temps)
+        {
+            if (expr is BoundConversion { ConversionKind: ConversionKind.ImplicitTuple, Conversion: var conversion } conv)
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TupleBinaryOperator.cs]: >conv [](start = 117, length = 4)

Consider renaming to `BoundConversion` for clarity

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TupleBinaryOperator.cs [hunk 29]
```diff
@@ -256,20 +414,50 @@ private BoundLocal MakeTemp(BoundExpression loweredExpression, ArrayBuilder<Loca
...
+                        var operand = MakeValueOrDefaultTemp(o, temps, effects);
+                        var types = expr.Type.GetNullableUnderlyingType().GetElementTypesOfTupleOrCompatible();
+                        int tupleCardinality = operand.Type.TupleElementTypesWithAnnotations.Length;
+                        var underlyingConversions = tupleConversion.UnderlyingConversions;
+                        Debug.Assert(underlyingConversions.Length == tupleCardinality);
+                        return new BoundConvertedTupleLiteral(
+                            syntax: operand.Syntax,
+                            sourceTuple: null,
+                            arguments: Enumerable.Range(0, tupleCardinality)
+                                .Select(i => MakeBoundConversion(GetTuplePart(operand, i), underlyingConversions[i], types[i], conv)).AsImmutable(),
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TupleBinaryOperator.cs]: This is going to create lots of garbage as this lambda cannot be cached.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenThrowTests.cs [hunk 30]
```diff
@@ -314,5 +314,92 @@ static void Main()
 }";
             CompileAndVerify(source, expectedOutput: "A");
         }
+
+        [Fact]
+        public void TestThrowConvertedValue()
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenThrowTests.cs]: This is a deviation from the current C# spec. Clearly you're intending it, but have we taken the change through LDM?

File: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml (hunk 20 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml]: I think switch expressions cannot be used in expression statements at the moment.

---
In reply to: [301350455](https://github.com/dotnet/roslyn/pull/37052#discussion_r301350455) [](ancestors = 301350455)

File: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml [hunk 31]
```diff
@@ -1199,6 +1193,23 @@
...
+    <Field Name="Type" Type="TypeSymbol" Override="true" Null="disallow"/>
+    <!-- Natural type is preserved for the purpose of semantic model. Can be `null`. -->
+    <Field Name="NaturalTypeOpt" Type="TypeSymbol" Null="allow"/>
+  </Node>
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml]: >Node [](start = 4, length = 4)

nit: extra empty line below

File: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml [hunk 32]
```diff
@@ -1511,26 +1527,20 @@
...
   Tuple literals can convert to the target type.
-  Once converted to a target type, they cannot be target-typed again. 
-  The Converted tuple literal is one which has been already converted to a target type.
+  Once converted to a target type, they cannot be target-typed again.
+  The Converted tuple literal is one which has already been converted to a target type.
   Converted tuple literal always has a type.
   -->
   <Node Name="BoundConvertedTupleLiteral" Base="BoundTupleExpression">
-    <!-- Converted tuple must have a type -->
-    <Field Name="Type" Type="TypeSymbol" Override="true" Null="disallow"/>
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml]: Why remove this? Seems good to enforce that converted tuple literal must have a type.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleEqualityTests.cs [hunk 33]
```diff
@@ -1878,12 +1932,18 @@ void M(S s1, S s2)
 }";
             var comp = CreateCompilation(source);
             comp.VerifyDiagnostics(
-                // (6,35): error CS0306: The type 'S' may not be used as a type argument
-                //         System.Console.Write(("", s1) == (null, s2));
-                Diagnostic(ErrorCode.ERR_BadTypeArgument, "s1").WithArguments("S").WithLocation(6, 35),
-                // (6,30): error CS0019: Operator '==' cannot be applied to operands of type 'S' and 'S'
-                //         System.Console.Write(("", s1) == (null, s2));
-                Diagnostic(ErrorCode.ERR_BadBinaryOps, @"("""", s1) == (null, s2)").WithArguments("==", "S", "S").WithLocation(6, 30)
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleEqualityTests.cs]: Consider keep existing indentation.=

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleEqualityTests.cs [hunk 34]
```diff
@@ -1878,12 +1932,18 @@ void M(S s1, S s2)
...
+                    // (6,35): error CS0306: The type 'S' may not be used as a type argument
+                    //         System.Console.Write(("", s1) == (null, s2));
+                    Diagnostic(ErrorCode.ERR_BadTypeArgument, "s1").WithArguments("S").WithLocation(6, 35),
+                    // (6,30): error CS0019: Operator '==' cannot be applied to operands of type 'S' and 'S'
+                    //         System.Console.Write(("", s1) == (null, s2));
+                    Diagnostic(ErrorCode.ERR_BadBinaryOps, @"("""", s1) == (null, s2)").WithArguments("==", "S", "S").WithLocation(6, 30),
+                    // (6,35): error CS0306: The type 'S' may not be used as a type argument
+                    //         System.Console.Write(("", s1) == (null, s2));
+                    Diagnostic(ErrorCode.ERR_BadTypeArgument, "s1").WithArguments("S").WithLocation(6, 35),
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleEqualityTests.cs]: This appears to be a duplicate warning.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleEqualityTests.cs [hunk 35]
```diff
@@ -2835,12 +2895,9 @@ int M(out int x)
 ";
             var comp = CreateCompilation(source);
             comp.VerifyDiagnostics(
-                // (7,14): error CS0841: Cannot use local variable 'z' before it is declared
-                //         _ = (z, M(out int z)) == (1, 2); // error
-                Diagnostic(ErrorCode.ERR_VariableUsedBeforeDeclaration, "z").WithArguments("z").WithLocation(7, 14),
-                // (7,13): error CS0019: Operator '==' cannot be applied to operands of type 'var' and 'int'
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleEqualityTests.cs]: Why did this warning get removed?

File: src/Compilers/CSharp/Portable/BoundTree/BoundNode.cs [hunk 36]
```diff
@@ -99,6 +107,18 @@ public bool HasErrors
             {
                 return (_attributes & BoundNodeAttributes.HasErrors) != 0;
             }
+            protected set
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/BoundTree/BoundNode.cs]: >protected [](start = 12, length = 9)

could this be private?

File: src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IConstructorBodyOperation.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IConstructorBodyOperation.cs]: Unfortunately, there is no easy way to do that.  The new VS test explorer places an extra four spaces before the output of a test, so my choices are to either copy and paste that, adding the four spaces, or do the same followed by an "unindent" operation in VS, which unfortunately messes up the indentation as here.  If there was a way to see the raw output of the test I could use that, but I don't see that option.

---
In reply to: [301332549](https://github.com/dotnet/roslyn/pull/37052#discussion_r301332549) [](ancestors = 301332549)

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 5 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: It is addressed (see next method below).  Will delete the comment.

---
In reply to: [301335706](https://github.com/dotnet/roslyn/pull/37052#discussion_r301335706) [](ancestors = 301335706)

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 7 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: Yes, since it is so distant from the condition, it protects the code here from adjustments above.

---
In reply to: [301336387](https://github.com/dotnet/roslyn/pull/37052#discussion_r301336387) [](ancestors = 301336387)

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 8 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: Because the problem is with this arg, not `dimensions[0]`.  It was simply wrong before.  Moreover, `dimensions[0]` might be an omitted size expression, which has no width.

---
In reply to: [301336868](https://github.com/dotnet/roslyn/pull/37052#discussion_r301336868) [](ancestors = 301336868)

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs (hunk 10 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: Since the error flag is aggregated up the bound nodes, that will happen automatically.

---
In reply to: [301337777](https://github.com/dotnet/roslyn/pull/37052#discussion_r301337777) [](ancestors = 301337777)

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs (hunk 3 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: Someone once said "Aside: Man is this so much easier to understand" when I reverted such a micro-optimization.  I agree with that person.

---
In reply to: [301335232](https://github.com/dotnet/roslyn/pull/37052#discussion_r301335232) [](ancestors = 301335232)

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs (hunk 12 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: That's not the way pattern-matching works.  A type is not a pattern.

---
In reply to: [301339843](https://github.com/dotnet/roslyn/pull/37052#discussion_r301339843) [](ancestors = 301339843)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenThrowTests.cs (hunk 30 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenThrowTests.cs]: Yes.  Actually, it was approved long ago (C# 5 era I think, and already documented this way in the ECMA specification by our agreement) but pending implementation, but given target-typed switch expression it would be a breaking change to do it any later than now.

---
In reply to: [301711198](https://github.com/dotnet/roslyn/pull/37052#discussion_r301711198) [](ancestors = 301711198)

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 37]
```diff
@@ -2266,12 +2266,9 @@ internal static uint GetValEscape(BoundExpression expr, uint scopeOfTheContainin
                     return Binder.ExternalScope;
 
                 case BoundKind.TupleLiteral:
-                    var tupleLiteral = (BoundTupleLiteral)expr;
-                    return GetTupleValEscape(tupleLiteral.Arguments, scopeOfTheContainingExpression);
-
                 case BoundKind.ConvertedTupleLiteral:
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: >case [](start = 16, length = 4)

Not related to this line of code: consider extending `LocalRewritingValidator` to assert that no unconverted tuple literals remain after lowering. I don't think we have such a validator for initial binding.

File: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml [hunk 38]
```diff
@@ -1498,11 +1509,16 @@
...
+    <!-- Which argument names were inferred (as opposed to explicitly provided)? -->
+    <Field Name="InferredNamesOpt" Type="ImmutableArray&lt;bool&gt;" Null="allow"/>
   </AbstractNode>
 
   <!-- 
   Tuple literals can convert to the target type.
-  Once converted to a target type, they cannot be target-typed again. 
+  Once converted to a target type, they cannot be target-typed again.
   The tuple literal is one which has not been converted to a target type.
   -->
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml]: Comment should mention that this node does not survive past initial binding. Same thing for unconverted switch expression.
Maybe we could even enforce that.

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs (hunk 13 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: +1
Also, consider adding xml doc

---
In reply to: [301341152](https://github.com/dotnet/roslyn/pull/37052#discussion_r301341152) [](ancestors = 301341152)

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs [hunk 39]
```diff
@@ -63,20 +61,12 @@ internal partial class Binder
 
             if (conversion.IsIdentity)
             {
-                // identity tuple conversions result in a converted tuple
-                // to indicate that tuple conversions are no longer applicable.
-                // nothing else changes
-                if (source.Kind == BoundKind.TupleLiteral)
-                {
-                    var sourceTuple = (BoundTupleLiteral)source;
+                if (source is BoundTupleLiteral sourceTuple)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: >) [](start = 59, length = 1)

nit: missing braces

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs [hunk 40]
```diff
@@ -126,14 +139,34 @@ internal partial class Binder
...
+        /// </summary>
+        private BoundExpression ConvertSwitchExpression(BoundUnconvertedSwitchExpression source, TypeSymbol destination, DiagnosticBag diagnostics, bool hasErrors = false)
+        {
+            var builder = ArrayBuilder<BoundSwitchExpressionArm>.GetInstance();
+            foreach (var oldCase in source.SwitchArms)
+            {
+                var oldValue = oldCase.Value;
+                var newValue = GenerateConversionForAssignment(destination, oldValue, diagnostics);
+                var newCase = (oldValue == newValue) ? oldCase :
+                    new BoundSwitchExpressionArm(oldCase.Syntax, oldCase.Locals, oldCase.Pattern, oldCase.WhenClause, newValue, oldCase.Label, oldCase.HasErrors);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: >new BoundSwitchExpressionArm [](start = 20, length = 28)

nit: consider using an `WithValue` method (which can handle the laziness as well)

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs [hunk 41]
```diff
@@ -198,6 +201,11 @@ private BoundExpression BindArgListOperator(InvocationExpressionSyntax node, Dia
                 else if (argument.Type.IsVoidType())
                 {
                     Error(diagnostics, ErrorCode.ERR_CantUseVoidInArglist, argument.Syntax);
+                    wasError = true;
+                }
+                else if (analyzedArguments.RefKind(i) == RefKind.None)
+                {
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: why only RefKind.None, and not also RefKind.Ref?

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs [hunk 42]
```diff
@@ -389,38 +402,19 @@ private void CheckNamedArgumentsForDynamicInvocation(AnalyzedArguments arguments
...
-                            builder[i] = ((BoundDiscardExpression)argument).FailInference(this, diagnostics);
-                        }
-
-                        i++;
-                    }
-                    while (i < builder.Count);
-
-                    return builder.ToImmutableAndFree();
-                }
+                    OutVariablePendingInference ovpi => ovpi.FailInference(this, diagnostics),
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: >ovpi [](start = 48, length = 4)

nit: consider `outVar`, `discard` for locals, instead of acronyms

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs [hunk 43]
```diff
@@ -957,15 +951,23 @@ private void CheckRestrictedTypeReceiver(BoundExpression expression, Compilation
...
-                            diagnostics.AddRange(boundWithErrors.Diagnostics);
+                            case UnboundLambda unboundLambda:
+                                var boundWithErrors = unboundLambda.BindForErrorRecovery();
+                                diagnostics.AddRange(boundWithErrors.Diagnostics);
+                                break;
+                            case BoundTupleLiteral _:
+                                // Tuple literals can contain unbound lambdas or switch expressions.
+                                _ = BindToNaturalType(argument, diagnostics);
+                                break;
+                            case BoundUnconvertedSwitchExpression { Type: { } naturalType } switchExpr:
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: >{ } [](start = 74, length = 3)

`object`?

File: src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs [hunk 44]
```diff
@@ -926,6 +933,28 @@ private Conversion ClassifyImplicitBuiltInConversionFromExpression(BoundExpressi
             return Conversion.NoConversion;
         }
 
+        private Conversion GetSwitchExpressionConversion(BoundExpression source, TypeSymbol destination, ref HashSet<DiagnosticInfo> useSiteDiagnostics)
+        {
+            switch (source)
+            {
+                case BoundConvertedSwitchExpression _:
+                    // It has already been subjected to a switch expression conversion.
+                    return Conversion.NoConversion;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs]: >NoConversion [](start = 38, length = 12)

can we reach this?

File: src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs [hunk 45]
```diff
@@ -926,6 +933,28 @@ private Conversion ClassifyImplicitBuiltInConversionFromExpression(BoundExpressi
...
+                    {
+                        if (!this.ClassifyConversionFromExpression(arm.Value, destination, ref useSiteDiagnostics).IsImplicit)
+                        {
+                            return Conversion.NoConversion;
+                        }
+                    }
+
+                    return Conversion.SwitchExpression;
+                default:
+                    return Conversion.NoConversion;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs]: >NoConversion [](start = 38, length = 12)

can we reach this?

**Comment by jcouv** [comment]
>             return new BoundBinaryOperator(node, kind, left, right, ConstantValue.NotAvailable, null, lookupResult, originalUserDefinedOperators, CreateErrorType(), true);

It seems possible for `left` and `right` to not have been pushed through the bottleneck here, in error scenarios. Is that okay?

---
Refers to: src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs:858 in 9a9a0c7. [](commit_id = 9a9a0c72c629e6b4d2c5fd00a49ab338bc8176fd, deletion_comment = False)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs [hunk 46]
```diff
@@ -7123,8 +7126,11 @@ static void Main()
 
             CreateCompilation(source).VerifyDiagnostics(
                 // (23,9): error CS0121: The call is ambiguous between the following methods or properties: 'C.Test(Func<(Func<short>, int)>)' and 'C.Test(Func<(Func<byte>, int)>)'
+                //         Test(()=>(()=>(byte)1, 1));
+                Diagnostic(ErrorCode.ERR_AmbigCall, "Test").WithArguments("C.Test(System.Func<(System.Func<short>, int)>)", "C.Test(System.Func<(System.Func<byte>, int)>)").WithLocation(23, 9),
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: How is this not a breaking change?

File: src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IConstructorBodyOperation.cs (hunk 1 above)
Comment (333fred) [reply src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IConstructorBodyOperation.cs]: At the very least, the formatting needs to be consistent. The `IConversionOperation` here is a child of the `IThrowOperation` and needs to be formatted as such. (if you were using vsvim, fixing the spaces is as easy as selecting the lines and then `s/^    //g`).

---
In reply to: [301738225](https://github.com/dotnet/roslyn/pull/37052#discussion_r301738225) [](ancestors = 301738225,301332549)

Comment (333fred) [reply src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IConstructorBodyOperation.cs]: @jfleisher, I've filed feedback on this that was assigned to you: [https://developercommunity.visualstudio.com/content/problem/612756/test-explorer-adds-4-spaces-to-the-beginning-of-ev.html](https://developercommunity.visualstudio.com/content/problem/612756/test-explorer-adds-4-spaces-to-the-beginning-of-ev.html). This is the kind of scenario where the extra lines introduced by the test explorer hurts the compiler team.

---
In reply to: [301780343](https://github.com/dotnet/roslyn/pull/37052#discussion_r301780343) [](ancestors = 301780343,301738225,301332549)

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 47]
```diff
@@ -844,6 +856,45 @@ protected BoundExpression BindInferredVariableInitializer(DiagnosticBag diagnost
...
 
+        internal BoundExpression BindToNaturalType(BoundExpression expression, DiagnosticBag diagnostics)
+        {
+            BoundExpression result;
+            switch (expression)
+            {
+                case BoundConvertedSwitchExpression _:
+                case BoundConvertedTupleLiteral _:
+                    result = expression;
+                    break;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: >break [](start = 20, length = 5)

can we reach this? (seems like we should try to lock in the natural type only once)

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 48]
```diff
@@ -2554,7 +2630,6 @@ private BoundStatement BindReturn(ReturnStatementSyntax syntax, DiagnosticBag di
             {
                 BindValueKind requiredValueKind = GetRequiredReturnValueKind(refKind);
                 arg = BindValue(expressionSyntax, diagnostics, requiredValueKind);
-                arg = ValidateEscape(arg, Binder.ExternalScope, refKind != RefKind.None, diagnostics);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: >ValidateEscape [](start = 22, length = 14)

nit: what was the motivation to move this somewhere below?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs [hunk 49]
```diff
@@ -606,5 +606,355 @@ class Program
...
+}
+class Target
+{
+    private readonly string Value;
+    public Target(string value) => Value = value;
+    public override string ToString() => Value;
+}
+class Source1
+{
+    public static implicit operator Target(Source1 self) => new Target(""Source1 "");
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs]: Consider adding tests where these conversions are defined on the target type, not on the source type.

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 50]
```diff
@@ -2720,6 +2796,7 @@ private BoundStatement BindReturn(ReturnStatementSyntax syntax, DiagnosticBag di
                     if (conversion.Kind != ConversionKind.Identity)
                     {
                         Error(diagnostics, ErrorCode.ERR_RefReturnMustHaveIdentityConversion, argument.Syntax, returnType);
+                        argument = argument.WithHasErrors();
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: >argument = argument.WithHasErrors(); [](start = 24, length = 36)

why do we do this only in this case, but not other branches of this code that call `Error(...)`?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs [hunk 51]
```diff
@@ -606,5 +606,355 @@ class Program
...
+}
+";
+            var compilation = CreateCompilation(source, options: TestOptions.DebugExe.WithNullableContextOptions(NullableContextOptions.Disable));
+            compilation.VerifyDiagnostics(
+                // (6,18): error CS8506: No best type was found for the switch expression.
+                //         _ = true switch { true => 1, false => string.Empty };
+                Diagnostic(ErrorCode.ERR_SwitchExpressionNoBestType, "switch").WithLocation(6, 18));
+        }
     }
 }
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs]: Suggested to add test

`Target t = c switch { 1 => TargetSubtype, 2 => source };`

where U.D. conversion from source to Target

**Comment by jcouv** [comment]
>         private static bool IsEncompassingImplicitConversionKind(ConversionKind kind)

nit: I've seen this method before, but still don't understand what "encompassing" means. Consider adding xml doc if the purpose of this method is clear to you.

---
Refers to: src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/UserDefinedImplicitConversions.cs:551 in 9a9a0c7. [](commit_id = 9a9a0c72c629e6b4d2c5fd00a49ab338bc8176fd, deletion_comment = False)

File: src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs [hunk 52]
```diff
@@ -26,11 +20,48 @@ internal BoundExpression WithSuppression(bool suppress = true)
...
             result.IsSuppressed = suppress;
             return result;
         }
 
+        internal BoundExpression WithWasConverted()
+        {
+#if DEBUG
+            // We track the WasConverted flag for locals and parameters only, as many other
+            // kinds of bound nodes have special behavior that prevents this from working for them.
+            if (Kind != BoundKind.Local && Kind != BoundKind.Parameter || this.WasConverted)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs]: >Kind != BoundKind.Local && Kind != BoundKind.Parameter [](start = 16, length = 54)

nit: consider parens

File: src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs [hunk 53]
```diff
@@ -26,11 +20,48 @@ internal BoundExpression WithSuppression(bool suppress = true)
...
-            var result = ShallowClone();
+            var result = (BoundExpression)MemberwiseClone();
             result.IsSuppressed = suppress;
             return result;
         }
 
+        internal BoundExpression WithWasConverted()
+        {
+#if DEBUG
+            // We track the WasConverted flag for locals and parameters only, as many other
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs]: > We track the WasConverted flag for locals and parameters only [](start = 14, length = 62)

I didn't understand this. Could you elaborate? What is an example of special behavior that prevents such tracking from working?
Also, in `BindToNaturalType`, we're using `WithWasConverted` on converted switch and tuple expressions. That seems useful even though they are not locals or parameters.

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs (hunk 3 above)
Comment (333fred) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: I don't think a bool flag for whether the builder should be used is quite so egregious

---
In reply to: [301743214](https://github.com/dotnet/roslyn/pull/37052#discussion_r301743214) [](ancestors = 301743214,301335232)

**Comment by 333fred** [comment]
Done review pass (iteration 16). I still need to re-review the tuple conversions more in depth, but will wait for current feedback to be addressed.

File: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml [hunk 54]
```diff
@@ -1511,26 +1527,20 @@
...
+  Once converted to a target type, they cannot be target-typed again.
+  The Converted tuple literal is one which has already been converted to a target type.
   Converted tuple literal always has a type.
   -->
   <Node Name="BoundConvertedTupleLiteral" Base="BoundTupleExpression">
-    <!-- Converted tuple must have a type -->
-    <Field Name="Type" Type="TypeSymbol" Override="true" Null="disallow"/>
     <!-- Original tuple is preserved for the purpose of semantic model -->
-    <Field Name="SourceTuple" Type="BoundTupleLiteral" SkipInVisitor="ExceptNullabilityRewriter" />
+    <Field Name="SourceTuple" Type="BoundTupleLiteral" Null="allow" SkipInVisitor="ExceptNullabilityRewriter" />
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml]: >allow [](start = 61, length = 5)

It may be good to comment when the source tuple could be null

File: src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs [hunk 55]
```diff
@@ -1962,12 +1962,12 @@ private static bool IsUserDefinedTrueOrFalse(BoundUnaryOperator @operator)
                                 }
                                 break;
                             }
-                        case BoundConvertedTupleLiteral tupleLiteral:
+                        case BoundConvertedTupleLiteral { SourceTuple: BoundTupleLiteral original } tupleLiteral:
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs]: >tupleLiteral [](start = 100, length = 12)

consider using discard

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs [hunk 56]
```diff
@@ -545,6 +544,7 @@ protected void VisitLvalue(BoundExpression node)
                     }
 
                 case BoundKind.TupleLiteral:
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs]: >TupleLiteral [](start = 31, length = 12)

can we still get an unconverted tuple literal here?

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs [hunk 57]
```diff
@@ -600,7 +600,7 @@ private void AdjustConditionalState(BoundExpression node)
         /// AssignedWhenFalse.
         /// </summary>
         /// <param name="node"></param>
-        protected virtual void VisitRvalue(BoundExpression node)
+        protected virtual void VisitRvalue(BoundExpression node, bool isKnownToBeAnLvalue = false)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs]: >isKnownToBeAnLvalue [](start = 70, length = 19)

nit: please update xml doc for this new parameter

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs [hunk 58]
```diff
@@ -1227,7 +1228,7 @@ protected virtual void VisitArguments(ImmutableArray<BoundExpression> arguments,
                 RefKind refKind = GetRefKind(refKindsOpt, i);
                 if (refKind != RefKind.Out)
                 {
-                    VisitRvalue(arguments[i]);
+                    VisitRvalue(arguments[i], isKnownToBeAnLvalue: refKind != RefKind.None);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs]: >RefKind.None); [](start = 78, length = 14)

how about RefKind.In?

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass_Switch.cs [hunk 59]
```diff
@@ -138,7 +138,17 @@ public override BoundNode VisitSwitchDispatch(BoundSwitchDispatch node)
             return null;
         }
 
-        public override BoundNode VisitSwitchExpression(BoundSwitchExpression node)
+        public override BoundNode VisitConvertedSwitchExpression(BoundConvertedSwitchExpression node)
+        {
+            return this.VisitSwitchExpression(node);
+        }
+
+        public override BoundNode VisitUnconvertedSwitchExpression(BoundUnconvertedSwitchExpression node)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass_Switch.cs]: >VisitUnconvertedSwitchExpression [](start = 34, length = 32)

If no unconverted switch expressions survive past initial binding, can we hit this code?

File: src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs [hunk 60]
```diff
@@ -1160,7 +1182,7 @@ protected virtual void AssignImpl(BoundNode node, BoundExpression value, bool is
                         {
                             // Writing through the (reference) value of a reference local
                             // requires us to read the reference itself.
-                            if (written) VisitRvalue(local);
+                            if (written) VisitRvalue(local, true);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs]: >true [](start = 60, length = 4)

nit: consider naming argument

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs [hunk 61]
```diff
@@ -471,7 +471,20 @@ int makeDagTempSlot(TypeWithAnnotations type, BoundDagTemp temp)
...
 
-        public override BoundNode VisitSwitchExpression(BoundSwitchExpression node)
+        public override BoundNode VisitConvertedSwitchExpression(BoundConvertedSwitchExpression node)
+        {
+            bool inferType = node.NaturalTypeOpt is object && node.NaturalTypeOpt.Equals(node.Type, TypeCompareKind.ConsiderEverything);
+            VisitSwitchExpressionCore(node, inferType);
+            return null;
+        }
+
+        public override BoundNode VisitUnconvertedSwitchExpression(BoundUnconvertedSwitchExpression node)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs]: >VisitUnconvertedSwitchExpression [](start = 34, length = 32)

can we get an unconverted switch expression all the way to NullableWalker?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs [hunk 62]
```diff
@@ -730,6 +730,11 @@ private BoundExpression BoxReceiver(BoundExpression rewrittenReceiver, NamedType
                 case BoundKind.Local:
                     return localsMayBeAssignedOrCaptured || ((BoundLocal)expression).LocalSymbol.RefKind != RefKind.None;
 
+                case BoundKind.TypeExpression:
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs]: >case BoundKind.TypeExpression: [](start = 16, length = 30)

was this a pre-existing bug?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs [hunk 63]
```diff
@@ -626,6 +643,20 @@ private BoundExpression MakeImplicitConversion(BoundExpression rewrittenOperand,
...
             NamedTypeSymbol rewrittenType)
+        {
+            (LocalSymbol temp, BoundAssignmentOperator assignmentToTemp, ImmutableArray<BoundExpression> fieldAccesses) =
+                RewriteTupleConversionCore(syntax, rewrittenOperand, conversion, @checked, explicitCastInCode, rewrittenType);
+            var result = MakeTupleCreationExpression(syntax, rewrittenType, fieldAccesses);
+            return _factory.MakeSequence(temp, assignmentToTemp, result);
+        }
+
+        private (LocalSymbol temp, BoundAssignmentOperator assignmentToTemp, ImmutableArray<BoundExpression> fieldAccesses)
+        RewriteTupleConversionCore(SyntaxNode syntax,
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs]: >RewriteTupleConversionCore [](start = 8, length = 26)

Feels like we could inline this method back into `RewriteTupleConversion`, because it only is used there and there is only one return statement.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs [hunk 64]
```diff
@@ -663,58 +694,83 @@ private BoundExpression MakeImplicitConversion(BoundExpression rewrittenOperand,
...
-            // default(int?) never has a value.
-            if (expression.Kind == BoundKind.DefaultExpression)
-            {
-                return true;
-            }
+            return nullableNeverHasValue(expression);
 
-            // new int?() never has a value if there is no argument.
-            if (expression.Kind == BoundKind.ObjectCreationExpression)
+            bool nullableNeverHasValue(BoundExpression expression)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs]: static?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DeconstructionAssignmentOperator.cs [hunk 65]
```diff
@@ -331,13 +345,11 @@ private ArrayBuilder<Binder.DeconstructionVariable> GetAssignmentTargetsAndSideE
                         break;
 
                     case BoundKind.TupleLiteral:
+                    case BoundKind.ConvertedTupleLiteral:
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DeconstructionAssignmentOperator.cs]: >ConvertedTupleLiteral [](start = 35, length = 21)

can we get either a converted or an unconverted tuple literal here?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_SwitchExpression.cs [hunk 66]
```diff
@@ -5,14 +5,16 @@
 using System.Collections.Immutable;
 using System.Diagnostics;
 using System.Linq;
+using System.Net.Sockets;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_SwitchExpression.cs]: does not compute ;-)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TupleCreationExpression.cs [hunk 67]
```diff
@@ -11,7 +12,7 @@ internal partial class LocalRewriter
     {
         public override BoundNode VisitTupleLiteral(BoundTupleLiteral node)
         {
-            return VisitTupleExpression(node);
+            throw ExceptionUtilities.UnexpectedValue(node.Kind);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TupleCreationExpression.cs]: >UnexpectedValue(node.Kind); [](start = 37, length = 27)

nit: unreachable?

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs [hunk 68]
```diff
@@ -278,7 +278,8 @@ internal IOperation CreateInternal(BoundNode boundNode)
                     return CreateRangeExpressionOperation((BoundRangeExpression)boundNode);
                 case BoundKind.SwitchSection:
                     return CreateBoundSwitchSectionOperation((BoundSwitchSection)boundNode);
-                case BoundKind.SwitchExpression:
+                case BoundKind.UnconvertedSwitchExpression:
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: >UnconvertedSwitchExpression [](start = 31, length = 27)

can we get an unconverted switch here?

File: src/Compilers/CSharp/Test/Syntax/Parsing/ParserErrorMessageTests.cs [hunk 69]
```diff
@@ -263,9 +263,6 @@ public static int Main()
 ";
 
             CreateCompilation(test).VerifyDiagnostics(
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Syntax/Parsing/ParserErrorMessageTests.cs]: >VerifyDiagnostics [](start = 36, length = 17)

What happened here? The diagnostics changed slightly (line number)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenThrowTests.cs (hunk 30 above)
Comment (jcouv) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenThrowTests.cs]: Just to confirm, `throw default` is still (properly) disallowed, even though it converts to `Exception`, correct?

---
In reply to: [301744754](https://github.com/dotnet/roslyn/pull/37052#discussion_r301744754) [](ancestors = 301744754,301711198)

Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenThrowTests.cs]: >TestThrowConvertedValue [](start = 20, length = 23)

Can you add a link to a github roslyn or csharplang issue, if we have one?

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs [hunk 70]
```diff
@@ -15968,6 +15974,44 @@ static void Main()
...
+            Assert.Equal("(System.Int16, System.String)", model.GetTypeInfo(n1).ConvertedType.ToTestDisplayString());
+            Assert.Equal(ConversionKind.ImplicitTupleLiteral, model.GetConversion(n1).Kind);
+
+            var n2 = nodes.OfType<TupleExpressionSyntax>().ElementAt(1);
+
+            Assert.Equal(@"(2, null)", n2.ToString());
+            Assert.Null(model.GetTypeInfo(n2).Type);
+            Assert.Equal("(System.Int16, System.String)", model.GetTypeInfo(n2).ConvertedType.ToTestDisplayString());
+            Assert.Equal(ConversionKind.ImplicitTupleLiteral, model.GetConversion(n2).Kind);
+        }
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: >} [](start = 8, length = 1)

Maybe I missed those tests, but it would be good to have a test with a target-typed tuple whose elements are target-typed switch expressions.
Also, vice-versa: a target-typed switch expression whose elements are target-typed tuples.

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs [hunk 71]
```diff
@@ -109,6 +99,29 @@ internal partial class Binder
...
+                bool hasErrors = false;
+                if (type is null)
+                {
+                    Debug.Assert(!conversion.Exists);
+                    type = CreateErrorType();
+                    hasErrors = true;
+                }
+
+                source = ConvertSwitchExpression((BoundUnconvertedSwitchExpression)source, type, diagnostics, hasErrors);
+                if (destination.Equals(type, TypeCompareKind.ConsiderEverything) && wasCompilerGenerated)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: >ConsiderEverything [](start = 61, length = 18)

Not sure about the ConsiderEverything. For example, do differences of `dynamic` vs. `object`, or tuple names matter?

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 72]
```diff
@@ -2759,6 +2766,17 @@ private BoundExpression BindArgumentExpression(DiagnosticBag diagnostics, Expres
                     Debug.Assert(parameterTypeWithAnnotations.HasType);
                     arguments[arg] = ((BoundDiscardExpression)argument).SetInferredTypeWithAnnotations(parameterTypeWithAnnotations);
                 }
+                else if (argument.NeedsToBeConverted())
+                {
+                    Debug.Assert(kind.IsIdentity);
+                    if (argument is BoundTupleLiteral sourceTuple)
+                    {
+                        TypeWithAnnotations parameterTypeWithAnnotations = GetCorrespondingParameterTypeWithAnnotations(ref result, parameters, arg);
+                        TupleTypeSymbol.ReportNamesMismatchesIfAny(parameterTypeWithAnnotations.Type, sourceTuple, diagnostics);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: >ReportNamesMismatchesIfAny [](start = 40, length = 26)

It seems strange to have a case for `!kind.IsIdentity` then a case for `argument.NeedsToBeConverted()`.
Could we run both cases through `CreateConversion` instead, to factor the code and not add a special case to call `ReportNamesMismatchesIfAny` here?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs (hunk 51 above)
Comment (alrz) [reply src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs]: can both conversations get stacked? e.g.: UD from source to the othet arm's type and from that type to Target with no direct conversation from source to Target

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs (hunk 40 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: I would if I had another use for it.

---
In reply to: [301761902](https://github.com/dotnet/roslyn/pull/37052#discussion_r301761902) [](ancestors = 301761902)

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs (hunk 47 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: Yes, we can currently reach this.  It is harmless to lock in the natural type more than once.  It is a no-op if the expression has had its natural type locked in.

If you think there would be value in trying to ensure it happens only once, please file an issue.  We can use the WasConverted flag to detect duplicate application of binding to the natural type.

---
In reply to: [301783223](https://github.com/dotnet/roslyn/pull/37052#discussion_r301783223) [](ancestors = 301783223)

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs (hunk 15 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: The switch is on the bound kind, not the node.

---
In reply to: [301341912](https://github.com/dotnet/roslyn/pull/37052#discussion_r301341912) [](ancestors = 301341912)

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs (hunk 17 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: Because it could be a switch expression, in which case we need to push the conversion to `bool` down into each branch.

---
In reply to: [301342606](https://github.com/dotnet/roslyn/pull/37052#discussion_r301342606) [](ancestors = 301342606)

File: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml (hunk 20 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml]: Correct.

---
In reply to: [301716937](https://github.com/dotnet/roslyn/pull/37052#discussion_r301716937) [](ancestors = 301716937,301350455)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 21 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: The changes indirectly triggered duplicate diagnostics in the nullable walker.  This fixed that.

---
In reply to: [301352605](https://github.com/dotnet/roslyn/pull/37052#discussion_r301352605) [](ancestors = 301352605)

File: src/Tools/Source/CompilerGeneratorTools/Source/BoundTreeGenerator/BoundNodeClassWriter.cs (hunk 22 above)
Comment (gafter) [reply src/Tools/Source/CompilerGeneratorTools/Source/BoundTreeGenerator/BoundNodeClassWriter.cs]: No, but it sure simplified things, since I was changing the attributes.

---
In reply to: [301353131](https://github.com/dotnet/roslyn/pull/37052#discussion_r301353131) [](ancestors = 301353131)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs (hunk 62 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs]: No, it is needed due to changes added here, where we use this on a receiver which can be either a type or an expression.

---
In reply to: [301817913](https://github.com/dotnet/roslyn/pull/37052#discussion_r301817913) [](ancestors = 301817913)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs (hunk 25 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs]: [https://github.com/dotnet/roslyn/issues/37120](https://github.com/dotnet/roslyn/issues/37120)

---
In reply to: [301354753](https://github.com/dotnet/roslyn/pull/37052#discussion_r301354753) [](ancestors = 301354753)

File: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml (hunk 32 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml]: A converted tuple literal is not required to have a type in some scenarios in which they are used to represent tuple equality, for example when there is a `null` on both sides like `(1, null) == (1, null)`.  Why we allow that I do not know, but we do allow it.

---
In reply to: [301718699](https://github.com/dotnet/roslyn/pull/37052#discussion_r301718699) [](ancestors = 301718699)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleEqualityTests.cs (hunk 34 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleEqualityTests.cs]: [https://github.com/dotnet/roslyn/issues/37121](https://github.com/dotnet/roslyn/issues/37121)

---
In reply to: [301725757](https://github.com/dotnet/roslyn/pull/37052#discussion_r301725757) [](ancestors = 301725757)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleEqualityTests.cs (hunk 35 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleEqualityTests.cs]: Because it is a cascaded diagnostic and a bad one at that.  `var` refers to an error type.  There is no `var` in the source at all!

---
In reply to: [301726282](https://github.com/dotnet/roslyn/pull/37052#discussion_r301726282) [](ancestors = 301726282)

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 37 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: Emit has no support for tuple literals of any kind, so that is already checked in emit.

---
In reply to: [301753517](https://github.com/dotnet/roslyn/pull/37052#discussion_r301753517) [](ancestors = 301753517)

File: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml (hunk 38 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml]: It does survive initial binding, as a converted literal points to the unconverted literal.  That makes a bit of a mess in our bound trees (or should i say bound dag), but that is what it is today.

---
In reply to: [301753825](https://github.com/dotnet/roslyn/pull/37052#discussion_r301753825) [](ancestors = 301753825)

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs (hunk 39 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: Not required by coding style guide, in fact it explicitly advocates this style for short ifs like this.  I would shorted the other ifs in this function, but I don't have a reason to touch them.

---
In reply to: [301759611](https://github.com/dotnet/roslyn/pull/37052#discussion_r301759611) [](ancestors = 301759611)

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs (hunk 41 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: Binding to its natural type only makes sense for an rvalue.

---
In reply to: [301765261](https://github.com/dotnet/roslyn/pull/37052#discussion_r301765261) [](ancestors = 301765261)

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs (hunk 43 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: The former would give the wrong type to the variable, and the latter would incorrectly let through null.

---
In reply to: [301773105](https://github.com/dotnet/roslyn/pull/37052#discussion_r301773105) [](ancestors = 301773105)

File: src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs (hunk 44 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs]: Almost certainly, especially during error recovery and error reporting.

---
In reply to: [301774871](https://github.com/dotnet/roslyn/pull/37052#discussion_r301774871) [](ancestors = 301774871)

Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/ConversionsBase.cs]: Though I have not found any tests that fail with a throw statement here.

---
In reply to: [302304419](https://github.com/dotnet/roslyn/pull/37052#discussion_r302304419) [](ancestors = 302304419,301774871)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs (hunk 46 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: Technically, it is a breaking change caused by a bug that I fixed in type inference involving lambdas. It was deeply broken before, in a way that could cause bad code generation in the presence of a switch expression. I don't have an easy way to keeping it working without breaking things. It is pretty hard to hit the issue.

---
In reply to: [301778341](https://github.com/dotnet/roslyn/pull/37052#discussion_r301778341) [](ancestors = 301778341)

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs (hunk 48 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: We may have a switch expression here that has not been converted, so we do not have the correct expressions for its arms and cannot compute its escape scope yet.

---
In reply to: [301785766](https://github.com/dotnet/roslyn/pull/37052#discussion_r301785766) [](ancestors = 301785766)

File: src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs (hunk 53 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs]: We have special nodes for out parameters, deconstruction variables, and a bunch of others.  Also, the code for doing this causes an extra duplication of every node that is tracked that way, and it would double the space allocated for bound nodes if we did it for everything (in DEBUG).

`WithWasConverted` is a no-op on anything except locals and parameters.

---
In reply to: [301793834](https://github.com/dotnet/roslyn/pull/37052#discussion_r301793834) [](ancestors = 301793834)

Comment (gafter) [reply src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs]: Also lambdas, method groups.  Also `null` does not require conversion to a target type in some circumstances, such as `null==null`.

---
In reply to: [302313036](https://github.com/dotnet/roslyn/pull/37052#discussion_r302313036) [](ancestors = 302313036,301793834)

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs (hunk 50 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: To suppress the second diagnostic in `RefLocalsAndReturnsTests.BadRefReturnWrongType` which would otherwise report
``` none
                    // (6,20): error CS8151: The return expression must be of type 'int' because this method returns by reference
                    //         return ref i;
                    Diagnostic(ErrorCode.ERR_RefReturnMustHaveIdentityConversion, "i").WithArguments("int").WithLocation(6, 20),
                    // (6,20): error CS8156: An expression cannot be used in this context because it may not be passed or returned by reference
                    //         return ref i;
                    Diagnostic(ErrorCode.ERR_RefReturnLvalueExpected, "i").WithLocation(6, 20)
```
Ad for the other branches, we don't need a reason not to do something.  If cascaded diagnostic scenarios arise that prove that it useful, then we can add it.

---
In reply to: [301788345](https://github.com/dotnet/roslyn/pull/37052#discussion_r301788345) [](ancestors = 301788345)

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs (hunk 51 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs]: That is exactly what the "Suggested to add test" is asking to show (that yes, it would work).

---
In reply to: [301891848](https://github.com/dotnet/roslyn/pull/37052#discussion_r301891848) [](ancestors = 301891848)

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs (hunk 56 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs]: Yes, in error scenarios.

---
In reply to: [301813107](https://github.com/dotnet/roslyn/pull/37052#discussion_r301813107) [](ancestors = 301813107)

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs (hunk 58 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs]: Those are not known to be an lvalue.

---
In reply to: [301813498](https://github.com/dotnet/roslyn/pull/37052#discussion_r301813498) [](ancestors = 301813498)

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass_Switch.cs (hunk 59 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass_Switch.cs]: No.  And if some do survive, for example in error scenarios, yes.

---
In reply to: [301816043](https://github.com/dotnet/roslyn/pull/37052#discussion_r301816043) [](ancestors = 301816043)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs (hunk 61 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs]: Yes, in error scenarios.

---
In reply to: [301816928](https://github.com/dotnet/roslyn/pull/37052#discussion_r301816928) [](ancestors = 301816928)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DeconstructionAssignmentOperator.cs (hunk 65 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_DeconstructionAssignmentOperator.cs]: We don't convert the left-hand-side of an assignment, so I think the answer is yes.

---
In reply to: [301822054](https://github.com/dotnet/roslyn/pull/37052#discussion_r301822054) [](ancestors = 301822054)

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs (hunk 68 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: Yes, in error scenarios.

---
In reply to: [301822553](https://github.com/dotnet/roslyn/pull/37052#discussion_r301822553) [](ancestors = 301822553)

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs (hunk 71 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: This method never produced identity conversion before.  See line 74.  I have already opened an issue about that.

---
In reply to: [301826665](https://github.com/dotnet/roslyn/pull/37052#discussion_r301826665) [](ancestors = 301826665)

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 72 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: There is an open issue around that.  Perhaps CreateConversion should create an identity conversion node when the types differ for example in tuple element names, but that would be a change of behavior so I don't want to do that here.

---
In reply to: [301827169](https://github.com/dotnet/roslyn/pull/37052#discussion_r301827169) [](ancestors = 301827169)

**Comment by gafter** [comment]
>             return new BoundBinaryOperator(node, kind, left, right, ConstantValue.NotAvailable, null, lookupResult, originalUserDefinedOperators, CreateErrorType(), true);

Yes, that is intentional.  Even if we did it here, there are other places where erroneous bound nodes don't make it through the bottleneck.  Also unbound lambdas.

---
In reply to: [509792695](https://github.com/dotnet/roslyn/pull/37052#issuecomment-509792695) [](ancestors = 509792695)

---
Refers to: src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs:858 in 9a9a0c7. [](commit_id = 9a9a0c72c629e6b4d2c5fd00a49ab338bc8176fd, deletion_comment = False)

**Comment by gafter** [comment]
>         private static bool IsEncompassingImplicitConversionKind(ConversionKind kind)

That is a term defined in the language specification.  I'll add a quote.

---
In reply to: [509805592](https://github.com/dotnet/roslyn/pull/37052#issuecomment-509805592) [](ancestors = 509805592)

---
Refers to: src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/UserDefinedImplicitConversions.cs:551 in 9a9a0c7. [](commit_id = 9a9a0c72c629e6b4d2c5fd00a49ab338bc8176fd, deletion_comment = False)

**Comment by gafter** [comment]
>         private static bool IsEncompassingImplicitConversionKind(ConversionKind kind)

OK, this is a mess.  First, ECMA and our spec disagree (I think ECMA is correct).  However, we don't implement either.  See [https://github.com/dotnet/roslyn/issues/37134](https://github.com/dotnet/roslyn/issues/37134)

---
In reply to: [510279665](https://github.com/dotnet/roslyn/pull/37052#issuecomment-510279665) [](ancestors = 510279665,509805592)

---
Refers to: src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/UserDefinedImplicitConversions.cs:551 in 9a9a0c7. [](commit_id = 9a9a0c72c629e6b4d2c5fd00a49ab338bc8176fd, deletion_comment = False)

**Comment by gafter** [comment]
@jcouv @333fred I think I have addressed all of your comments.  Do you have any others?

**Comment by gafter** [comment]
@jcouv Is this good to go?

**Comment by jcouv** [comment]
>                             if ((object)methodGroup.Methods[i].ReduceExtensionMethod(left.Type) == null) methodGroup.Methods.RemoveAt(i);

what happened with this removed block?

---
Refers to: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:6312 in 9a9a0c7. [](commit_id = 9a9a0c72c629e6b4d2c5fd00a49ab338bc8176fd, deletion_comment = True)

**Comment by gafter** [comment]
>                             if ((object)methodGroup.Methods[i].ReduceExtensionMethod(left.Type) == null) methodGroup.Methods.RemoveAt(i);

It does not exist in master

---
In reply to: [511558949](https://github.com/dotnet/roslyn/pull/37052#issuecomment-511558949) [](ancestors = 511558949)

---
Refers to: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:6312 in 9a9a0c7. [](commit_id = 9a9a0c72c629e6b4d2c5fd00a49ab338bc8176fd, deletion_comment = True)
