### PR TITLE
Fix converted nullability on extract method

### LINKED ISSUE #39075: Extract method drops nullable annotation on explicit cast
Copy into a C# 8.0 app:

```
#nullable enable

namespace ConsoleApp65
{
    class C
    {
        void M()
        {
            object? o = null;
            var s = (string?)o;
            Console.WriteLine(s);
        }
    }
}
```

Invoke extract method on the "o" in the "var s..." line. Do *not* select the cast, just the o.

**Expected:** the generated method returns string? because that's the explicit cast before it.
**Actual:** it returns just string which breaks code.

### PR DESCRIPTION
**Pull request by ryzngard**
Fixes #39075 

* Remove the IsObjectType check since it caused incorrect behavior when selecting an identifier of type Object. See TestExtractNullableObjectWithExplicitCast 
* Fix extension methods to correctly use converted nullability 
* Add some tests to show expected behavior with nullable reference types
* Work around #39122 by calling GetTypeInfo on the CastExpressionSyntax  directly

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractMethodTests.cs [hunk 1]
```diff
@@ -2815,5 +2815,244 @@ private void NewMethod()
...
+@"#nullable enable
+
+using System;
+
+class C
+{
+    void M()
+    {
+        object? o = null;
+        var s = [|(string?)o|];
```
Comment (jasonmalinowski) [inline src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractMethodTests.cs]: Did we also want a test for the explicit case where this cast is just `(string)`? It's invalid code but the compiler supposedly maintains the flow state and will consider s to still be `string?`.

File: src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.ExpressionResult.cs [hunk 2]
```diff
@@ -74,14 +74,14 @@ public override ITypeSymbol GetContainingScopeType()
...
-                    if (regularType != null && !regularType.IsObjectType())
+                    if (regularType != null)
                     {
                         return regularType;
                     }
 
                     if (node.Parent is CastExpressionSyntax castExpression)
                     {
-                        return model.GetTypeInfo(castExpression.Type).GetTypeWithAnnotatedNullability();
+                        return model.GetTypeInfo(castExpression).GetTypeWithAnnotatedNullability();
```
Comment (jasonmalinowski) [inline src/Features/CSharp/Portable/ExtractMethod/CSharpSelectionResult.ExpressionResult.cs]: Now should this be GetTypeWithFlowNullability? One of the original questions we had here was whether or not we really needed both or whether GetTypeInfo can only work with flow nullability.

File: src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractMethodTests.cs (hunk 1 above)
Comment (ryzngard) [reply src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractMethodTests.cs]: Added more tests. Please confirm they are the behavior we want :)
