### PR TITLE
Fix PathMapping to a root directory

### LINKED ISSUE #22815: PathMap incorrectly handles unix-style root path
On Windows running this command:

```
D:\temp>csc a.cs /debug:portable /pathmap:D:\temp=/
```

produces document name ```\a.cs``` in the PDB while I expect it to be ```/a.cs```. 

The problem is the combination of trimming separators here:

http://source.roslyn.io/#Microsoft.CodeAnalysis/CommandLine/CommonCommandLineParser.cs,209

and then then not having the separator available in this check:

http://source.roslyn.io/#Microsoft.CodeAnalysis/FileSystem/PathUtilities.cs,643 

As a result we flip the separator from ```/``` to ```\```.

### PR DESCRIPTION
**Pull request by khyperia**
Fixes #22815

Fixes https://github.com/dotnet/roslyn/issues/21639

The convention is now to store PathMap entries ending with a path separator, instead of without.

Also, this properly unquotes PathMap command line parsing.

### CODE REVIEW

File: src/Compilers/Core/Portable/FileSystem/PathUtilities.cs [hunk 1]
```diff
@@ -53,6 +57,34 @@ public static string TrimTrailingSeparators(string s)
             return s;
         }
 
+        /// <summary>
+        /// Ensures a trailing directory separator character
+        /// </summary>
+        public static string AddTrailingSeparator(string s)
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/FileSystem/PathUtilities.cs]: I would rename this method "EnsureTrailingSeparator". The "Add" prefix implies it will always do work (aka allocate).

File: src/Compilers/CSharp/Portable/CommandLine/CSharpCommandLineParser.cs [hunk 2]
```diff
@@ -1037,11 +1037,12 @@ public new CSharpCommandLineArguments Parse(IEnumerable<string> args, string bas
 
                         case "pathmap":
                             // "/pathmap:K1=V1,K2=V2..."
+                            unquoted = RemoveQuotesAndSlashes(value);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/CommandLine/CSharpCommandLineParser.cs]: Consider moving `unquoted = Remove...` into the block to match. Otherwise, block is confusing.

File: src/Compilers/Core/Portable/FileSystem/PathUtilities.cs [hunk 3]
```diff
@@ -53,6 +57,34 @@ public static string TrimTrailingSeparators(string s)
...
+            {
+                return s + '/';
+            }
+            else if (!hasSlash && hasBackslash)
+            {
+                return s + '\\';
+            }
+            else
+            {
+                // If the slashes are not consistent, use the current platform's slash.
```
Comment (jcouv) [inline src/Compilers/Core/Portable/FileSystem/PathUtilities.cs]: Consider "If there are no slashes or they are inconsistent, ..."

File: src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs [hunk 4]
```diff
@@ -9135,6 +9139,20 @@ public void PathMapParser()
...
+            parsedArgs = DefaultParse(new[] { "/pathmap:\"K 1=V 1\",\"K 2=V 2\"", "a.cs" }, _baseDirectory);
+            parsedArgs.Errors.Verify();
+            Assert.Equal(KeyValuePair.Create("K 1\\", "V 1\\"), parsedArgs.PathMap[0]);
+            Assert.Equal(KeyValuePair.Create("K 2\\", "V 2\\"), parsedArgs.PathMap[1]);
+
+            parsedArgs = DefaultParse(new[] { "/pathmap:\"K 1\"=\"V 1\",\"K 2\"=\"V 2\"", "a.cs" }, _baseDirectory);
+            parsedArgs.Errors.Verify();
+            Assert.Equal(KeyValuePair.Create("K 1\\", "V 1\\"), parsedArgs.PathMap[0]);
+            Assert.Equal(KeyValuePair.Create("K 2\\", "V 2\\"), parsedArgs.PathMap[1]);
         }
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs]: Do we cover the mixed slashes scenario?

File: src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs [hunk 5]
```diff
@@ -2517,5 +2520,33 @@ public void Bug9288_keycontainer()
...
 
         #endregion
+
+        #region PathMap Linux Tests
+        // Like the above (CoreCLR Signing Tests), these aren't actually syntax tests, but this is in one of only two assemblies tested on linux
+
+        [Fact]
+        public void PathMapKeepsCrossPlatformRoot()
+        {
+            CSharpCommandLineArguments Parse(params string[] args)
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs]: Nit: I think we camelCase local functions (like locals).

File: src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs [hunk 6]
```diff
@@ -2517,5 +2520,33 @@ public void Bug9288_keycontainer()
         // get to the third case (but there's still error handling if that changes)
 
         #endregion
+
+        #region PathMap Linux Tests
+        // Like the above (CoreCLR Signing Tests), these aren't actually syntax tests, but this is in one of only two assemblies tested on linux
+
+        [Fact]
+        public void PathMapKeepsCrossPlatformRoot()
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs]: What happens if the pathMap maps both `/temp` and `/temp/`?

Comment (jcouv) [inline src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs]: Should we have corresponding VB test as well?

Comment (jcouv) [inline src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs]: I'm not sure how to do that, but can we also test the platform-specific case (when no slashes can be detected)?

File: src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs [hunk 7]
```diff
@@ -2517,5 +2520,52 @@ public void Bug9288_keycontainer()
         // get to the third case (but there's still error handling if that changes)
 
         #endregion
+
+        #region PathMap Linux Tests
+        // Like the above (CoreCLR Signing Tests), these aren't actually syntax tests, but this is in one of only two assemblies tested on linux
+
+        [Fact]
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs]: Did you consider using an xunit theory here vs. a fact? Seems like this is a fairly data driven test and would be ripe for a theory. 

Note: we don't have a policy here and I'm fine as is. But Theory seems ot be a feature other repos are more apt to use than Roslyn is.

Comment (khyperia) [reply src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs]: No, I didn't consider it (forgot that it existed). I was about to say "nah, there's some wacky behavior here, so 4 parameters would be needed `(expected key, expected value, input key, input value)`", but then I tried it and it's not too bad to have 4 params.

File: src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs (hunk 6 above)
Comment (khyperia) [reply src/Compilers/CSharp/Test/Syntax/Diagnostics/DiagnosticTest.cs]: Added it, but unfortunately we can't test the cross-platform behavior (the equivalent VB test is only on windows). Thankfully the behavior here is in shared code, so it should be decent test coverage.

**Comment by khyperia** [comment]
retest windows_debug_unit64_prtest please
