### PR TITLE
Produce error when static local function captures a local with extension method method group conversion

### LINKED ISSUE #65938: Capturing wrong variable in a local static function by using an extension method
**Version Used**: C#11; main (30 Nov 2022) on sharplab;

**Steps to Reproduce**:

Run the following code using `<LangVersion>latest</LangVersion>` or `<LangVersion>11.0</LangVersion>`: https://sharplab.io/#gist:b2eb10fdce4d06159c10ca727b7f5ccb

**Diagnostic Id**: -

**Expected Behavior**: The output should be:
```
Anna: Anna
Billy: Billy
```

**Actual Behavior**:
```
Anna: Anna
Billy: Anna
```

This problem happens for `LangVersion` 11.0 (or latest at the time of writing). Switching to an older version will behave as expected.

This problem doesn't happen if we make any of the following changes:

- Remove `static` from `Foo(int)`'s declaration
- Change `Select(Foo)` to `Select(x => Foo(x))`

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #65938

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs [hunk 1]
```diff
@@ -822,7 +822,7 @@ private void CheckMethodGroup(BoundMethodGroup node, MethodSymbol method, bool p
             CheckReceiverIfField(node.ReceiverOpt);
             CheckReferenceToMethodIfLocalFunction(node, method);
 
-            if (method is null || method.RequiresInstanceReceiver)
+            if (method is null || method.RequiresInstanceReceiver || node.ReceiverOpt is not (BoundThisReference or BoundBaseReference))
```
[the remark this answers is not in the document]
Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs:825]: I couldn't find a broken case with the case I currently have. But I'm going to change it to something that feels more meaningful.

File: src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs [hunk 2]
```diff
@@ -189,5 +189,89 @@ public void M()
                 // }
                 Diagnostic(ErrorCode.ERR_EOFExpected, "}").WithLocation(7, 1));
         }
+
+        [Fact]
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs:193]: >[Fact] [](http://example.com/codeflow?start=8&length=6)

Please include a `[WorkItem]` attribute for this test.

File: src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs [hunk 3]
```diff
@@ -189,5 +189,89 @@ public void M()
...
+                        => string.Empty;
+                }
+                """).VerifyDiagnostics(
+                    // (5,13): error CS0026: Keyword 'this' is not valid in a static property, static method, or static field initializer
+                    //     var x = this.MyExtension;
+                    Diagnostic(ErrorCode.ERR_ThisInStaticMeth, "this").WithLocation(5, 13),
+                    // (5,13): error CS8422: A static local function cannot contain a reference to 'this' or 'base'.
+                    //     var x = this.MyExtension;
+                    Diagnostic(ErrorCode.ERR_StaticLocalFunctionCannotCaptureThis, "this").WithLocation(5, 13));
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs:275]: >} [](http://example.com/codeflow?start=8&length=1)

Please add a test where there should be no receiver.
```csharp
static class Extensions
{
    static void F()
    {
        LocalFunc();
        static void LocalFunc()
        {
            var x = MyExtension;
            x(null);
        }
    }
    static string MyExtension(this object o)
        => string.Empty;
}
```

File: src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs [hunk 4]
```diff
@@ -189,5 +189,89 @@ public void M()
...
+                LocalFunc();
+
+                static void LocalFunc()
+                {
+                    var x = c.MyExtension;
+                    x();
+                }
+
+
+                public class C
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs:207]: Consider removing the extra blank line in this test and the following.

File: src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs [hunk 5]
```diff
@@ -189,5 +189,89 @@ public void M()
...
+        {
+            CreateCompilation("""
+                LocalFunc();
+
+                static void LocalFunc()
+                {
+                    var x = this.MyExtension;
+                    x();
+                }
+
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs:262]: Consider testing `base.MyExtension` as well.

**Review by cston — APPROVED** [review]

**Comment by jaredpar** [comment]
Do `static` lambda methods have the same bug? Do we have tests for that case?

File: src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs [hunk 6]
```diff
@@ -189,5 +189,116 @@ public void M()
...
+        [Fact, WorkItem(65938, "https://github.com/dotnet/roslyn/issues/65938")]
+        public void StaticLocalFunction_CapturingMethodGroup()
+        {
+            CreateCompilation("""
+                var c = new C();
+                LocalFunc();
+
+                static void LocalFunc()
+                {
+                    var x = c.MyExtension;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs:202]: >c.MyExtension [](http://example.com/codeflow?start=28&length=13)

Consider also testing creating delegate with `new`.

File: src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs [hunk 7]
```diff
@@ -189,5 +189,116 @@ public void M()
...
+                        static void LocalFunc()
+                        {
+                            var x = MyExtension;
+                            x(null);
+                        }
+                    }
+                    static string MyExtension(this object o)
+                        => string.Empty;
+                }
+                """).VerifyDiagnostics();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs:301]: VerifyEmitDiagnostics? This is a success scenario, let's verify that to the end.

File: src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs [hunk 8]
```diff
@@ -189,5 +189,116 @@ public void M()
...
+
+        [Fact]
+        public void StaticLocalFunction_CapturingMethodGroup3()
+        {
+            CreateCompilation("""
+                LocalFunc();
+
+                static void LocalFunc()
+                {
+                    var x = this.MyExtension;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs:257]: >this [](http://example.com/codeflow?start=28&length=4)

`this` and `base` are not allowed in top level code. Please adjust the scenario so that the only reason for the error is the static nature of the local function.

File: src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs [hunk 9]
```diff
@@ -189,5 +189,116 @@ public void M()
...
+                }
+
+                public static class Extensions
+                {
+                    public static string MyExtension(this C c)
+                        => string.Empty;
+                }
+                """).VerifyDiagnostics(
+                    // (7,7): error CS8421: A static local function cannot contain a reference to 'c'.
+                    //     x(c);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs:245]: >//     x(c); [](http://example.com/codeflow?start=20&length=12)

Let's remove this code, which is not about method group conversions, change this scenario into success case, and verify that we can compile it successfully.

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs [hunk 10]
```diff
@@ -822,7 +822,8 @@ private void CheckMethodGroup(BoundMethodGroup node, MethodSymbol method, bool p
             CheckReceiverIfField(node.ReceiverOpt);
             CheckReferenceToMethodIfLocalFunction(node, method);
 
-            if (method is null || method.RequiresInstanceReceiver)
+            if (method is null || method.RequiresInstanceReceiver ||
+                (method.IsExtensionMethod && node.SearchExtensionMethods))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs:826]: >method.IsExtensionMethod && node.SearchExtensionMethods [](http://example.com/codeflow?start=17&length=55)

This feels fragile, the method is not part of the BoundMethodGroup and the group doesn't control how the method is used. Rather than inventing new ways to infer the answer, let's use information explicitly stored in ```BoundConversion``` and ```BoundDelegateCreationExpression``` nodes, specifically the ```IsExtensionMethod``` property. This will also be consistent with how ```LocalRewriter``` does that. Alternatively, we could always visit the receiver. Could any harm come from visiting a bound type, for example?

**Comment by AlekseyTs** [comment]
Done with review pass (commit 4)

File: src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs (hunk 8 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs:257]: > Please adjust the scenario so that the only reason for the error is the static nature of the local function.

The other scenario I can think of is the one tested with `StaticLocalFunction_CapturingMethodGroup`

Could you clarify the scenario you're looking for please? Thanks!

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs:257]: >>`this` and `base` are not allowed **in top level code**. Please adjust the scenario so that the only reason for the error is the static nature of the local function.

>Could you clarify the scenario you're looking for please? 

Do not use top level code.

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs (hunk 10 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs:826]: Visiting unconditionally fails the following:

```csharp
using System;
class Program
{
    static void Main()
    {
        static void F1<T>()
        {
            Console.WriteLine(typeof(T));
        }
        static void F2()
        {
            F1<int>();
            Action a = F1<string>;
            a();
        }
        F2();
    }
}
```

The receiver here is `this`, but it's not really captured. I'm not sure though why the receiver is non-null value.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs:826]: > The receiver here is this, but it's not really captured. I'm not sure though why the receiver is non-null value.

It looks like unconditional visit wouldn't work. I forgot that binder synthesizes `this` receiver in cases like that too.

File: src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs [hunk 11]
```diff
@@ -189,5 +189,181 @@ public void M()
...
+
+                internal static class Extensions
+                {
+                    public static string MyExtension(this Base c)
+                        => string.Empty;
+                }
+                """).VerifyDiagnostics(
+                    // (13,22): error CS8422: A static local function cannot contain a reference to 'this' or 'base'.
+                    //             var x1 = this.MyExtension;
+                    Diagnostic(ErrorCode.ERR_StaticLocalFunctionCannotCaptureThis, "this").WithLocation(13, 22),
```
Comment (Youssef1313) [inline src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs:322]: Are we missing more `ERR_StaticLocalFunctionCannotCaptureThis` diagnostics? I'm not sure.

File: src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs [hunk 12]
```diff
@@ -189,5 +189,181 @@ public void M()
...
+                        static void LocalFunc()
+                        {
+                            var x = MyExtension;
+                            var y = new Func<object, string>(MyExtension);
+                        }
+                    }
+                    static string MyExtension(this object o)
+                        => string.Empty;
+                }
+                """).VerifyDiagnostics().VerifyEmitDiagnostics();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs:366]: >VerifyDiagnostics().VerifyEmitDiagnostics [](http://example.com/codeflow?start=21&length=41)

Doing both is redundant. Consider removing ```VerifyDiagnostics``` call.

File: src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs (hunk 11 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs:322]: > Are we missing more ERR_StaticLocalFunctionCannotCaptureThis diagnostics? I'm not sure.

Is there a specific concern here?

**Comment by AlekseyTs** [comment]
Done with review pass (commit 5).

File: src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs (hunk 11 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs:322]: No, I asked just to make sure that nothing is wrong

File: src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs [hunk 13]
```diff
@@ -189,5 +189,181 @@ public void M()
...
+                            var y1 = base.MyExtension;
+                            var y2 = new Func<string>(base.MyExtension);
+                        }
+                
+                        void NonStatic()
+                        {
+                            Action f = static () =>
+                            {
+                                var x1 = this.MyExtension;
+                                var x2 = new Func<string>(this.MyExtension);
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs:306]: Are we reporting errors for these cases? (Consider renaming the locals in this lambda to `x3`, `x4`, `y3`, `y4` so it's easier to match up diagnostics.)

File: src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs [hunk 14]
```diff
@@ -189,5 +189,181 @@ public void M()
...
+            CreateCompilation("""
+                using System;
+
+                var c = new C();
+                LocalFunc();
+                NonStatic();
+
+                static void LocalFunc()
+                {
+                    var x = c.MyExtension;
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs:205]: >x [](http://example.com/codeflow?start=24&length=1)

Consider naming the locals distinctly across the static local function and static lambda expression below, so it's easier to match up diagnostics.

File: src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs [hunk 15]
```diff
@@ -189,5 +189,181 @@ public void M()
...
+                            var x2 = new Func<string>(this.MyExtension);
+                            var y1 = base.MyExtension;
+                            var y2 = new Func<string>(base.MyExtension);
+                        }
+                
+                        void NonStatic()
+                        {
+                            Action f = static () =>
+                            {
+                                var x3 = this.MyExtension;
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs:305]: >this.MyExtension [](http://example.com/codeflow?start=41&length=16)

Should this case and the next be reported as errors?

Comment (Youssef1313) [reply src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs:305]: @cston I'm not sure, was already asking in https://github.com/dotnet/roslyn/pull/65965#discussion_r1053728427

Note that when I comment portion of the test and make the test input as follows:

```csharp
                using System;
                public class Base { }

                public class C : Base
                {
                    public void M()
                    {
                        //LocalFunc();
                        NonStatic();

                        //static void LocalFunc()
                        //{
                        //    var x1 = this.MyExtension;
                        //    var x2 = new Func<string>(this.MyExtension);
                        //    var y1 = base.MyExtension;
                        //    var y2 = new Func<string>(base.MyExtension);
                        //}
                
                        void NonStatic()
                        {
                            Action f = static () =>
                            {
                                var x3 = this.MyExtension;
                                var x4 = new Func<string>(this.MyExtension);
                                //var y3 = base.MyExtension;
                                //var y4 = new Func<string>(base.MyExtension);
                            };
                        }
                    }
                }

                internal static class Extensions
                {
                    public static string MyExtension(this Base c)
                        => string.Empty;
                }
```

errors are reported on x3 and x4 properly.

See also a simplified example that is unrelated to extension methods [here](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKAPQGYACLUgYQIG8DSHyz0AWUgWQAoBKexu/IyGkAcgHsYAZQAuEaVADGPANwE+w8m3FTZ8pb0EbSAo8PTZMpAGakAvOWwA2UjzsA+daeOevjAPR+pDBipACmAE7hYuHW0aQABtIAFlAAzvEAdKQAQgCu0qRQNvEAnvGFqaQKYmBgoTDSoQhwpBAwYZFxaaQADlEIuQpNPr6kAG4QMQAedqTJaRkA4qHSABIQqUmUYgihqoajjBMxJbPAG6EZ7PuHAL43RreeT/gvQA===)

Comment (cston) [reply src/Compilers/CSharp/Test/Symbol/Symbols/LocalFunctionTests.cs:305]: > Note that when I comment portion of the test and make the test input as follows:
> ...
> errors are reported on x3 and x4 properly.

In that case, let's add a test without the commented out parts, to verify those errors are reported when there are no other errors.

**Review by cston — APPROVED** [review]

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit7)

**Comment by AlekseyTs** [comment]
@Youssef1313 Thanks for the contribution
