### PR TITLE
Fix incorrect async capture analysis in loops inside try.

### LINKED ISSUE #7669: IDisposable.Dispose() not called in Release mode for async method in VB
[This issue is created after consulting the folks at StackOverflow, who also thought of this as a bug.](http://stackoverflow.com/questions/34421966/idisposable-dispose-not-called-in-release-mode-for-async-method)

I wrote the following WPF sample app in VB.NET 14 using .NET 4.6.1 on VS2015.1:

    Class MainWindow
    
        Public Sub New()
            InitializeComponent()
        End Sub
    
        Private Async Sub Button_Click(sender As Object, e As RoutedEventArgs)
            MessageBox.Show("Pre")
    
            Using window = New DisposableWindow()
                window.Show()
    
                For index = 1 To 1
                    Await Task.Delay(100)
                Next
            End Using
    
            MessageBox.Show("Post")
        End Sub
    
        Class DisposableWindow
            Inherits Window
            Implements IDisposable
    
            Public Sub Dispose() Implements IDisposable.Dispose
                Me.Close()
                MessageBox.Show("Disposed")
            End Sub
        End Class
    
    End Class

The sample below produces the following output:

- Debug mode: Pre, Disposed, Post
- Release mode: Pre, Post

This is strange. Why would Debug mode execute this code differently than Release mode...?

When I change the using block to a manual try/finally block, the call to window.Dispose() even throws a NullReferenceException:

    Dim window = New DisposableWindow()
    Try
        window.Show()
    
        For index = 1 To 1
            Await Task.Delay(100)
        Next
    Finally
        window.Dispose()
    End Try

And even more strange stuff: When the for-loop is excluded, the sample works perfectly. I've only let the For-loop run once, to specify the minimum amount of loops the produce the issue. Also feel free to replace the For-loop with a While-loop. It produces the same behavior as the For-loop.

Works: 

    Using window = New DisposableWindow()
        window.Show()
    
        Await Task.Delay(100)
    End Using

I've also made the exact same sample in C# (6), where it works perfectly. So in C# both Debug and Release mode result in 'Pre, Disposed, Post' as output.

The samples can be downloaded here: 

http://www.filedropper.com/vbsample 

http://www.filedropper.com/cssample

**Edit:**

Did some more test:

- Disabling compiler optimizations in VB.NET for Release mode, makes it behave like Debug mode (as expected, but wanted to test it, just in case).
- The issue also happens when I target .NET 4.5 (the earliest version where async/await became available).

### PR DESCRIPTION
**Pull request by VSadov**
When variable slot is marked unassigned, it should also be unassigned in containing try state, regardless if the current state has the slot already unassigned or not.
Existing code seems to assume that situation with variable being unasigned in the current state but assigned in the try state is impossible, but it is possible when try contains a loop and the loop contains await.

Fixes #7669

### CODE REVIEW

**Comment by VSadov** [comment]
C# did not have this bug, but did not have any unit tests either (introducing the bug would pass all tests). 
So I have added C# tests as well.

**Comment by VSadov** [comment]
@dotnet/roslyn-compiler - please review

**Comment by VSadov** [comment]
@dotnet-bot test prtest/lin/dbg/unit32 please

File: src/Compilers/VisualBasic/Portable/Analysis/FlowAnalysis/DataFlowPass.vb [hunk 1]
```diff
@@ -615,13 +615,14 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
 
             ' If the state of the slot is 'assigned' we need to clear it 
             '    and possibly propagate it to all the parents
+            If Me._tryState IsNot Nothing Then
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Analysis/FlowAnalysis/DataFlowPass.vb]: Do we need to specially handle nested Try-s? Why not?

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Analysis/FlowAnalysis/DataFlowPass.vb]: Consider adding unit-test with nesting.

Comment (VSadov) [inline src/Compilers/VisualBasic/Portable/Analysis/FlowAnalysis/DataFlowPass.vb]: Nested try has a nested try state that is merged with the outer try state. Nothing had to be fixed there.
HoistUsing004 is a nested Using test.

**Comment by AlekseyTs** [comment]
LGTM

File: src/Compilers/VisualBasic/Portable/Analysis/FlowAnalysis/DataFlowPass.vb [hunk 2]
```diff
@@ -615,13 +615,14 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
 
             ' If the state of the slot is 'assigned' we need to clear it
```
Comment (gafter) [inline src/Compilers/VisualBasic/Portable/Analysis/FlowAnalysis/DataFlowPass.vb]: This comment no longer corresponds to the code.

File: src/Compilers/VisualBasic/Portable/Analysis/FlowAnalysis/DataFlowPass.vb (hunk 1 above)
Comment (gafter) [inline src/Compilers/VisualBasic/Portable/Analysis/FlowAnalysis/DataFlowPass.vb]: Why doesn't this change need to occur in the similar code below?

Comment (VSadov) [inline src/Compilers/VisualBasic/Portable/Analysis/FlowAnalysis/DataFlowPass.vb]: I think it should, i just did not notice that. This assign/unassign back and forth stuff is very convoluted.

Comment (VSadov) [inline src/Compilers/VisualBasic/Portable/Analysis/FlowAnalysis/DataFlowPass.vb]: Turns out the similar code below does not need fixing because it is never used. The whole tryState deal is used to track conservative unassignemts in async capture analysis. However awaits unassign variables and do not unassign fields, so having parent variables and having tryState are mutually exclusivesituations.
I am going to remove the confusing code that tries to unassign parent variables in the tryState.
C# does not seem to have such code either.

Comment (gafter) [inline src/Compilers/VisualBasic/Portable/Analysis/FlowAnalysis/DataFlowPass.vb]: That comment (just above) is very useful to know! Can you excerpt part of it into a comment in the code?

Comment (VSadov) [inline src/Compilers/VisualBasic/Portable/Analysis/FlowAnalysis/DataFlowPass.vb]: Will add a comment to both VB and C#

Comment (VSadov) [inline src/Compilers/VisualBasic/Portable/Analysis/FlowAnalysis/DataFlowPass.vb]: It seems somewhat unfortunate that base analysis implementation in many places has become so coupled with quirks and requirements (sometimes conflicting) of the actual kinds of analysis performed.

Comment (VSadov) [inline src/Compilers/VisualBasic/Portable/Analysis/FlowAnalysis/DataFlowPass.vb]: Actually that was not entirely correct. unassignments are also used for region analysis and that can have partially assigned/unassigned structs. So for completeness we do need to propagate unassignments of parent variables to the tryState too. I cant figure right away what kind of testcase would hit this.

Comment (VSadov) [inline src/Compilers/VisualBasic/Portable/Analysis/FlowAnalysis/DataFlowPass.vb]: I have refactored VB code roughly equivalent to C# here: https://github.com/dotnet/roslyn/pull/7728
That is more than enough for fixing the async analysis and tidying up.   
However it does not seem to work as intended in a case of more general "DataFlowsOut" analysis when struct partial assignments are involved (at least as I understand it should work). I will continue investigating that. If it is indeed broken, the reasons would not be in this code and the fix would be outside of the scope of this bug.
