### PR TITLE
Handle unmatched conditionals in brace matching

### LINKED ISSUE #7534: ArgumentNullException in brace matching with partially typed directive
Put the caret at the $$.

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

class Program
{
    static void Main(string[] args)
    {#if$$

    }
}
```

```C#
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.Editor.CSharp.BraceMatching.CSharpDirectiveTriviaBraceMatcher.GetMatchingConditionalDirectives(DirectiveTriviaSyntax directive, CancellationToken cancellationToken) in C:\roslyn-internal\Open\src\EditorFeatures\CSharp\BraceMatching\CSharpDirectiveTriviaBraceMatcher.cs:line 19
   at Microsoft.CodeAnalysis.Editor.AbstractDirectiveTriviaBraceMatcher`7.<FindBracesAsync>d__3.MoveNext() in C:\roslyn-internal\Open\src\EditorFeatures\Core\Extensibility\BraceMatching\AbstractDirectiveTriviaBraceMatcher.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.BraceMatching.BraceMatchingService.<GetMatchingBracesAsync>d__2.MoveNext() in C:\roslyn-internal\Open\src\EditorFeatures\Core\Implementation\BraceMatching\BraceMatchingService.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.BraceMatching.BraceHighlightingViewTaggerProvider.<ProduceTagsForBracesAsync>d__7.MoveNext() in C:\roslyn-internal\Open\src\EditorFeatures\Core\Implementation\BraceMatching\BraceHighlightingViewTaggerProvider.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.BraceMatching.BraceHighlightingViewTaggerProvider.<ProduceTagsAsync>d__6.MoveNext() in C:\roslyn-internal\Open\src\EditorFeatures\Core\Implementation\BraceMatching\BraceHighlightingViewTaggerProvider.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.<ProduceTagsAsync>d__29.MoveNext() in C:\roslyn-internal\Open\src\EditorFeatures\Core\Tagging\AbstractAsynchronousTaggerProvider.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.<RecomputeTagsAsync>d__81.MoveNext() in C:\roslyn-internal\Open\src\EditorFeatures\Core\Tagging\AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs:line 554
12/16/2015 12:42:38 PM
Source: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: First chance exception: System.Core
StackTrace:    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.Editor.CSharp.BraceMatching.CSharpDirectiveTriviaBraceMatcher.GetMatchingConditionalDirectives(DirectiveTriviaSyntax directive, CancellationToken cancellationToken) in C:\roslyn-internal\Open\src\EditorFeatures\CSharp\BraceMatching\CSharpDirectiveTriviaBraceMatcher.cs:line 19
   at Microsoft.CodeAnalysis.Editor.AbstractDirectiveTriviaBraceMatcher`7.<FindBracesAsync>d__3.MoveNext() in C:\roslyn-internal\Open\src\EditorFeatures\Core\Extensibility\BraceMatching\AbstractDirectiveTriviaBraceMatcher.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.BraceMatching.BraceMatchingService.<GetMatchingBracesAsync>d__2.MoveNext() in C:\roslyn-internal\Open\src\EditorFeatures\Core\Implementation\BraceMatching\BraceMatchingService.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.BraceMatching.BraceHighlightingViewTaggerProvider.<ProduceTagsForBracesAsync>d__7.MoveNext() in C:\roslyn-internal\Open\src\EditorFeatures\Core\Implementation\BraceMatching\BraceHighlightingViewTaggerProvider.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.BraceMatching.BraceHighlightingViewTaggerProvider.<ProduceTagsAsync>d__6.MoveNext() in C:\roslyn-internal\Open\src\EditorFeatures\Core\Implementation\BraceMatching\BraceHighlightingViewTaggerProvider.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.<ProduceTagsAsync>d__29.MoveNext() in C:\roslyn-internal\Open\src\EditorFeatures\Core\Tagging\AbstractAsynchronousTaggerProvider.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider`1.TagSource.<RecomputeTagsAsync>d__81.MoveNext() in C:\roslyn-internal\Open\src\EditorFeatures\Core\Tagging\AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs:line 554
```

### PR DESCRIPTION
**Pull request by balajikris**
Fixes #7534 

For unmatched conditionals, C# returns null when asked for a matching
conditional directive, whereas VB returns a list with the single
unmatched directive in it. Incorporate checks for those into the
AbstractDirectiveTriviaBraceMatcher and add tests.

### CODE REVIEW

**Comment by balajikris** [comment]
@dotnet/roslyn-ide, @rchande

**Comment by rchande** [comment]
:+1:

File: src/EditorFeatures/Core/Extensibility/BraceMatching/AbstractDirectiveTriviaBraceMatcher.cs [hunk 1]
```diff
@@ -36,12 +36,15 @@ internal abstract class AbstractDirectiveTriviaBraceMatcher<TDirectiveTriviaSynt
...
             }
 
-            TDirectiveTriviaSyntax matchingDirective;
+            TDirectiveTriviaSyntax matchingDirective = null;
             if (IsConditionalDirective(directive))
             {
                 // #if/#elif/#else/#endif directive cases.
                 var matchingDirectives = GetMatchingConditionalDirectives(directive, cancellationToken);
-                matchingDirective = matchingDirectives[(matchingDirectives.IndexOf(directive) + 1) % matchingDirectives.Count];
+                if (matchingDirectives != null && matchingDirectives.Count > 0)
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Extensibility/BraceMatching/AbstractDirectiveTriviaBraceMatcher.cs]: matchingDirectivs?.Count > 0    ?

**Comment by CyrusNajmabadi** [comment]
:+1:

File: src/EditorFeatures/CSharp/BraceMatching/CSharpDirectiveTriviaBraceMatcher.cs [hunk 2]
```diff
@@ -16,7 +17,7 @@ internal class CSharpDirectiveTriviaBraceMatcher : AbstractDirectiveTriviaBraceM
         RegionDirectiveTriviaSyntax, EndRegionDirectiveTriviaSyntax>
     {
         internal override List<DirectiveTriviaSyntax> GetMatchingConditionalDirectives(DirectiveTriviaSyntax directive, CancellationToken cancellationToken)
-                 => directive.GetMatchingConditionalDirectives(cancellationToken).ToList();
+                => directive.GetMatchingConditionalDirectives(cancellationToken)?.ToList();
```
Comment (davkean) [inline src/EditorFeatures/CSharp/BraceMatching/CSharpDirectiveTriviaBraceMatcher.cs]: This override is allowed to return null?

Comment (davkean) [inline src/EditorFeatures/CSharp/BraceMatching/CSharpDirectiveTriviaBraceMatcher.cs]: Ignore me - Cyrus corrected me.
