### PR TITLE
Do not use SyntaxWalker to visit an arbitrary syntax tree in order to avoid a stack overflow.

### LINKED ISSUE #59190: Visual Studio 2022 crashes for certain solution after setting net6.0 instead of net5.0
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022-crashes-for-certain-s/1622689)._

---
[severity:I'm unable to use this version]
I have existing solution for .NET 5 (ASP.NET Core), I worked with it in VS 2019, all works good.
Now I want upgrade all projects from this solution to .NET 6 and work in VS 2022.
I replaced net5.0 to net6.0 in all .csproj files in this solution.
And after that VS 2022 crashed.
If I launch VS 2022 again and open this solution then VS 2022 hangs and then crashes.

Problem is only for this solution.
For other similar solutions all works good - I replaced net5.0 to net6.0 and VS didn't crash.

---
#### Feedback Bot on 12/26/2021, 05:17 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Peng Ge [MSFT] on 12/27/2021, 00:16 AM: 

<p>Dear customer, thank you for your feedback and I am sorry to hear that you are running into this issue.<br>
You can try to repair Visual Studio, disable third-party extensions, delete the .vs and bin folders of the project and reload the project.</p>

#### Pavel Mokshin on 12/27/2021, 09:22 AM: 

<p>Hi. I tried all these ways, they didn’t help.</p>

#### Peng Ge [MSFT] on 12/29/2021, 00:18 AM: 

<p>Open the project in Visual Studio 2022, then modify the target framework in the project properties-&gt;application-&gt;General, will you encounter this issue?</p>

#### Pavel on 12/29/2021, 00:37 PM: 

<p>Yes.<br>
I did it now for all projects in solution.<br>
Problem is only for one project - when I switch it to .NET 6 then Visual Studio 2022 hangs and crashes.</p>
<p>Don’t know is it important or not but in this project I use Roslyn SDK.<br>
I attached this proj file which I use in .NET 5.<br>
If change net5.0 to net6.0 in it then I encounter this issue.<br>
At moment of switch I have old versions of Nuget packages which I used in .NET 5.<br>
I also tried manually change versions of Nuget packages to latest (4.0.1 for Roslyn and 6.0.1 for .NET) but it didn’t help.</p>
<p>Also attached screenshot with some error messages from VS.<br>
But I couldn’t click “Show stack trace” because VS hangs.</p>

#### Pavel on 12/29/2021, 04:05 PM: 

<p>Created and attached small solution with one project, it has this problem too - VS 2022 hangs and crashes.<br>
Here is used Antlr4.<br>
Some files with code are very big.<br>
Maybe this is the reason of problem.</p>

#### Feedback Bot on 12/30/2021, 01:06 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Pavel on 12/30/2021, 04:33 AM: 

<p>Also found similar ticket: <a target='_blank' href="https://developercommunity.visualstudio.com/t/visual-studio-2022-preview-crashes-opening-solutio/1519923">https://developercommunity.visualstudio.com/t/visual-studio-2022-preview-crashes-opening-solutio/1519923</a><br>
Here user (randyL2004) found workaround but it doesn’t work for me.</p>
<p>In this ticket MS Team said that it’s bug of Antlr and suggested write to them.<br>
User created issue on Antlr github: <a target='_blank' href="https://github.com/antlr/antlr4/issues/3274">https://github.com/antlr/antlr4/issues/3274</a><br>
Please look this discussion, maybe it will help.</p>

#### Peng Ge [MSFT] on 1/18/2022, 01:53 AM: 

<p>Thank you for your feedback.<br>
Will you encounter this issue without using Antlr?<br>
We look forward to hearing from you!</p>

#### Pavel Mokshin on 1/20/2022, 00:37 AM: 

<p>No, it’s only with Antlr. But Antlr is required for this project.<br>
For now I’m forced to use Rider IDE from Jetbrains, it works good for this project.</p>

#### Drew Noakes [MSFT] on 1/22/2022, 02:42 AM: 

<p>Hi @<a target='_blank' href="https://developercommunity.visualstudio.com/users/356099/PavelMokshin.html">Pavel Mokshin</a>, thanks very much for the bug report, especially for the attached project. I can reproduce the problem and have assigned this ticket to the relevant team, who will look into it for you.</p>

#### Feedback Bot on 1/23/2022, 08:57 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #59190.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs [hunk 1]
```diff
@@ -2806,5 +2806,44 @@ class C { }
...
+        [Fact]
+        [WorkItem(59190, "https://github.com/dotnet/roslyn/issues/59190")]
+        public void LongBinaryExpression()
+        {
+            var source = @"
+class C {
+public static readonly string F = ""a""
+";
+
+            for (int i = 0; i < 3500 + 3500; i++)
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs:2819]:
```suggestion
            for (int i = 0; i < 7000; i++)
```

**Review by cston — APPROVED** [review]

**Review by RikkiGibson — APPROVED** [review]

**Comment by 333fred** [comment]
@AlekseyTs probably need to skip the new test in the IOperation leg.

**Comment by AlekseyTs** [comment]
@chsienki Please review.

**Review by 333fred — APPROVED** [review]

File: src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs [hunk 2]
```diff
@@ -2806,5 +2806,43 @@ class C { }
...
+}
+";
+            var parseOptions = TestOptions.RegularPreview;
+            Compilation compilation = CreateCompilation(source, options: TestOptions.DebugDll, parseOptions: parseOptions);
+            compilation.VerifyDiagnostics();
+            Assert.Single(compilation.SyntaxTrees);
+
+            var generator = new PipelineCallbackGenerator(ctx =>
+            {
+                ctx.RegisterSourceOutput(ctx.SyntaxProvider.CreateSyntaxProvider((node, ct) => node is ClassDeclarationSyntax c, (context, ct) => context.Node).WithTrackingName("Syntax"), (context, ct) => { });
```
Comment (sharwell) [inline src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs:2835]: 💡 It may help to also have a test that registers for `LiteralExpressionSyntax`
