### PR TITLE
Fix regression using alias qualified name in an is-type expression

### LINKED ISSUE #44019: More `global::` scenarios
The fix for https://github.com/dotnet/roslyn/issues/43960 didn't cover all scenarios this can occur, and the VS build is still failing. An example:

```cs
namespace N
{
    class C
    {
        void M(object o)
        {
            if (o is global::N.C) { }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #44019

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a couple of reviews of this tiny but urgent fix for a regression blocking 16.7P1?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs [hunk 1]
```diff
@@ -3361,6 +3361,72 @@ void M(E e)
...
+@"namespace E
+{
+    public class A { }
+}
+
+class Class1
+{
+    void M(object e)
+    {
+        if (e is global::E.A) { }
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs:3428]: >E.A [](start = 25, length = 3)

It feels like it would be good to have a test where either part of the name is generic instantiation.

**Comment by AlekseyTs** [comment]
>                 case MemberAccessExpressionSyntax { Expression: var expr, OperatorToken: { Kind: SyntaxKind.DotToken } dotToken, Name: var simpleName }

Is this always a simple name?

---
Refers to: src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs:57 in a83e3c3. [](commit_id = a83e3c3fd8a37decb834fd9e30baa30a890d8c30, deletion_comment = False)

**Comment by JoeRobich** [comment]
@gafter Is this good to merge?

**Comment by 333fred** [comment]
@gafter I went ahead and added the tests that Aleksey asked for.

**Comment by gafter** [comment]
@JoeRobich We need to wait for the tests.
