### PR TITLE
Update Solution.GetProject(IAssemblySymbol) [Fixes unit test flakiness]

### LINKED ISSUE #10132: Microsoft.CodeAnalysis.Editor.UnitTests.GoToDefinition.GoToDefinitionTests.TestCrossLanguageParameterizedPropertyOverride failure
http://dotnet-ci.cloudapp.net/job/roslyn_master_win_dbg_unit64/1018/testReport/junit/Microsoft.CodeAnalysis.Editor.UnitTests.GoToDefinition/GoToDefinitionTests/TestCrossLanguageParameterizedPropertyOverride/

Microsoft.CodeAnalysis.Editor.UnitTests.GoToDefinition.GoToDefinitionTests.TestCrossLanguageParameterizedPropertyOverride (from Roslyn.Services.Editor.UnitTests2)

Failing for the past 1 build (Since Failed#1018 )
Took 0.77 sec.
add description
Stacktrace

MESSAGE:
Assert.Equal() Failure\r\nExpected: True\r\nActual: False
+++++++++++++++++++
STACK TRACE:
at Microsoft.CodeAnalysis.Editor.UnitTests.Utilities.GoToHelpers.GoToTestHelpers.VB$StateMachine_3_TestAsync.MoveNext() in q:\roslyn\src\EditorFeatures\Test2\Utilities\GoToHelpers\GoToTestHelpers.vb:line 47 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at Microsoft.CodeAnalysis.Editor.UnitTests.GoToDefinition.GoToDefinitionTests.VB$StateMachine_69_TestCrossLanguageParameterizedPropertyOverride.MoveNext() in q:\roslyn\src\EditorFeatures\Test2\GoToDefinition\GoToDefinitionTests.vb:line 1626 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #10132

Adds a map from ISymbol (assembly or module symbols) to ProjectId so we can find projects for skeleton assemblies even after its compilation could have been GC'd.

### CODE REVIEW

**Comment by dpoeschl** [comment]
FYI @jasonmalinowski @CyrusNajmabadi @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
:+1:

File: src/Workspaces/Core/Portable/Workspace/Solution/Solution.CompilationTracker.cs [hunk 1]
```diff
@@ -648,6 +652,29 @@ public CompilationInfo(Compilation compilation, bool hasSuccessfullyLoadedTransi
...
 
+            private Compilation UpdateCompilationWithNewReferencesAndRecordAssemblySymbols(Compilation compilation, List<MetadataReference> newReferences, Dictionary<MetadataReference, ProjectId> metadataReferenceToProjectId)
+            {
+                if (!Enumerable.SequenceEqual(compilation.ExternalReferences, newReferences))
+                {
+                    compilation = compilation.WithReferences(newReferences);
+                }
+
+                // TODO: Record source assembly to project mapping
+                // RecordSourceOfAssemblySymbol(compilation.Assembly, this.ProjectState.Id);
```
Comment (Pilchie) [inline src/Workspaces/Core/Portable/Workspace/Solution/Solution.CompilationTracker.cs]: Why is this commented out?

**Comment by jasonmalinowski** [comment]
@dotnet-bot, test vsi please.

File: src/Workspaces/Core/Portable/Workspace/Solution/Solution.CompilationTracker.cs (hunk 1 above)
Comment (dpoeschl) [inline src/Workspaces/Core/Portable/Workspace/Solution/Solution.CompilationTracker.cs]: There will be another PR that will uncomment this. It relies on some other changes involving a new public ISourceAsseblySymbol type, and we didn't want to block fixing this bug on API ratification.

Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Workspace/Solution/Solution.CompilationTracker.cs]: Since that might be later or might never happen, can we just delete this?

File: src/Workspaces/Core/Portable/Workspace/Solution/Solution.CompilationTracker.cs [hunk 2]
```diff
@@ -729,8 +756,8 @@ private bool HasMissingReferences(Compilation compilation, IReadOnlyList<Metadat
 
             /// <summary>
             /// Attempts to get (without waiting) a metadata reference to a possibly in progress
-            /// compilation. Actual compilation references are preferred over skeletal assembly
-            /// references.  Could potentially return null if nothing can be provided.
+            /// compilation. Only actual compilation references are returned. Could potentially
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Workspace/Solution/Solution.CompilationTracker.cs]: This should probably just return `ComplationReference` then?

File: src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs [hunk 3]
```diff
@@ -2056,18 +2050,28 @@ internal Task<bool> HasSuccessfullyLoadedAsync(Project project, CancellationToke
                 : project.Solution.GetProjectState(project.Id).HasAllInformation ? SpecializedTasks.True : SpecializedTasks.False;
         }
 
-        private static readonly ConditionalWeakTable<MetadataReference, ProjectId> s_metadataReferenceToProjectMap =
-            new ConditionalWeakTable<MetadataReference, ProjectId>();
+        /// <summary>
+        /// Symbols need to be either <see cref="IAssemblySymbol"/> or <see cref="IModuleSymbol"/>.
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs]: It might be good to document what this map actually represents. This is more of a remark than a summary.

**Comment by jasonmalinowski** [comment]
:+1:. Nitpicks can be addressed later if we get a green test run from this.

**Comment by dpoeschl** [comment]
All tests passed, so I'm merging this in. Will address nitpicks in a follow-up PR.
