### PR TITLE
[Ask Mode] Fix crash in `BoundObjectCreationExpression.ArgumentsInParameterOrder` in VB

### LINKED ISSUE #9014: NRE in `BoundObjectCreationExpression.ArgumentsInParameterOrder`
Crash with a NRE at `BoundObjectCreationExpression.ArgumentsInParameterOrder` with following code, due the null value of `Me.ConstructorOpt`:
```vb
        Class C
            Protected Structure S
            End Structure
            Private F As Integer
            Private Property P As Integer
            Protected Shared ReadOnly Property Q(o)
                Get
                    Return Nothing
                End Get
            End Property
        End Class
        Class D
            Shared Sub M(o)
                Dim x As C = Nothing
                M(New C.S())
                M(x.F)
                M(x.P)
                M(C.Q(Nothing))
            End Sub
        End Class
```

Here's stack trace:
```
Test 'Microsoft.CodeAnalysis.VisualBasic.UnitTests.BindingErrorTests.BC30389ERR_InaccessibleSymbol2_1' failed: System.NullReferenceException : Object reference not set to an instance of an object.
	BoundTree\Expression.vb(1170,0): at Microsoft.CodeAnalysis.VisualBasic.BoundObjectCreationExpression.get_IHasArgumentsExpression_ArgumentsInParameterOrder()
	Compilation\OperationWalker.cs(338,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitObjectCreationExpression(IObjectCreationExpression operation)
	BoundTree\Expression.vb(1207,0): at Microsoft.CodeAnalysis.VisualBasic.BoundObjectCreationExpression.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	Compilation\OperationWalker.cs(291,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitConversionExpression(IConversionExpression operation)
	BoundTree\Expression.vb(1037,0): at Microsoft.CodeAnalysis.VisualBasic.BoundConversion.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	Compilation\OperationWalker.cs(201,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitArgument(IArgument operation)
	BoundTree\Expression.vb(427,0): at Microsoft.CodeAnalysis.VisualBasic.BoundCall.ArgumentBase.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	Compilation\OperationWalker.cs(21,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitArray[T](ImmutableArray`1 list)
	Compilation\OperationWalker.cs(196,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitInvocationExpression(IInvocationExpression operation)
	BoundTree\Expression.vb(340,0): at Microsoft.CodeAnalysis.VisualBasic.BoundCall.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	Compilation\OperationWalker.cs(178,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitExpressionStatement(IExpressionStatement operation)
	BoundTree\Statement.vb(1477,0): at Microsoft.CodeAnalysis.VisualBasic.BoundExpressionStatement.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	CompilationTestUtils.vb(247,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.WalkOperationTrees(VisualBasicCompilation compilation)
	CompilationTestUtils.vb(228,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithReferences(IEnumerable`1 sourceTrees, IEnumerable`1 references, VisualBasicCompilationOptions options, String assemblyName)
	CompilationTestUtils.vb(199,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithReferences(XElement sources, IEnumerable`1 references, VisualBasicCompilationOptions options, IEnumerable`1& spans, VisualBasicParseOptions parseOptions)
	CompilationTestUtils.vb(74,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithMscorlib(XElement sources, VisualBasicCompilationOptions options, IEnumerable`1 references, IEnumerable`1& spans, VisualBasicParseOptions parseOptions)
	Binding\BindingErrorTests.vb(5647,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.BindingErrorTests.BC30389ERR_InaccessibleSymbol2_1()
```

### PR DESCRIPTION
**Pull request by genlu**
This fixes #9014

### CODE REVIEW

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb [hunk 1]
```diff
@@ -1167,7 +1167,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
 
         Private ReadOnly Property IHasArgumentsExpression_ArgumentsInParameterOrder As ImmutableArray(Of IArgument) Implements IHasArgumentsExpression.ArgumentsInParameterOrder
             Get
-                Return BoundCall.DeriveArguments(Me.Arguments, Me.ConstructorOpt.Parameters)
+                Return If(Me.ConstructorOpt Is Nothing, ImmutableArray(Of IArgument).Empty, BoundCall.DeriveArguments(Me.Arguments, Me.ConstructorOpt.Parameters))
```
Comment (genlu) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: @AlekseyTs @JohnHamby In what scenario `ConstructorOpt` property can be null? (other than error as in the testcase)

Comment (JohnHamby) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: I don't know of a case where a valid program could produce a null constructor, but @AlekseyTs will have more of the language subtleties to mind.

Someone (meaning myself or @genlu ) needs to make a systematic pass through the IOperation implementations and protect against null properties or, more generally, malformed bound trees due to invalid source.

**Comment by JohnHamby** [comment]
I sign off.

File: src/Compilers/VisualBasic/Test/Semantic/Diagnostics/OperationAnalyzerTests.vb [hunk 2]
```diff
@@ -1591,6 +1591,32 @@ End Class
...
+    Shared Sub M(o)
+        M(New C.S())
+    End Sub
+End Class
+]]>
+                             </file>
+                         </compilation>
+
+            Dim comp = CompilationUtils.CreateCompilationWithMscorlibAndVBRuntime(source)
+            comp.VerifyDiagnostics(Diagnostic(ERRID.ERR_InaccessibleSymbol2, "C.S").WithArguments("C.S", "Protected").WithLocation(7, 15))
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/Diagnostics/OperationAnalyzerTests.vb]: Please use AssertTheseDiagnostics helper in VB tests.

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: I think this can happen when a structure type is accessible, but its parameter-less constructor is not.

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: See Binder.BindObjectCreationExpression

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: Also, we don't want to drop arguments in this case, lets add an assert that ConstructorOpt is never Nothing if there are arguments attached to BoundObjectCreationExpression.

Comment (genlu) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: Based on `Binder.BindObjectCreationExpression`, it seems one of requirements of having `ConstructorOpt == Nothing` is 'Argument.Count == 0', is that right? If so, why do we need to assert here?

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: Asserts are needed to verify assumptions and to make sure assumptions are not invalidated by future changes.

File: src/Compilers/VisualBasic/Test/Semantic/Diagnostics/OperationAnalyzerTests.vb (hunk 2 above)
Comment (genlu) [inline src/Compilers/VisualBasic/Test/Semantic/Diagnostics/OperationAnalyzerTests.vb]: Is there a counterpart for analyzer diagnostics I should use as well?

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb (hunk 1 above)
Comment (genlu) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: Gotcha.

File: src/Compilers/VisualBasic/Test/Semantic/Diagnostics/OperationAnalyzerTests.vb (hunk 2 above)
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/Diagnostics/OperationAnalyzerTests.vb]: I cannot point you to any specific helper (haven't been involved into analyzers testing), but, if there is one that uses base-line in the format similar to AssertTheseDiagnostics, it would be preferred.

Comment (genlu) [inline src/Compilers/VisualBasic/Test/Semantic/Diagnostics/OperationAnalyzerTests.vb]: OK, I have created an issue for replacing them all in this file. #9077

File: src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb [hunk 3]
```diff
@@ -1167,7 +1167,8 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
 
         Private ReadOnly Property IHasArgumentsExpression_ArgumentsInParameterOrder As ImmutableArray(Of IArgument) Implements IHasArgumentsExpression.ArgumentsInParameterOrder
             Get
-                Return BoundCall.DeriveArguments(Me.Arguments, Me.ConstructorOpt.Parameters)
+                Debug.Assert(If(Me.Arguments.IsEmpty(), True, Me.ConstructorOpt IsNot Nothing))
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: Debug.Assert(Me.ConstructorOpt IsNot Nothing OrElse Me.Arguments.IsEmpty()) ?

Comment (genlu) [inline src/Compilers/VisualBasic/Portable/BoundTree/Expression.vb]: OK.

**Comment by AlekseyTs** [comment]
LGTM

**Comment by genlu** [comment]
Retest this please.

**Comment by genlu** [comment]
retest vsi please

**Comment by genlu** [comment]
@dotnet-bot retest prtest/win/vsi/p0 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p0/333/
// Retest reason: #9172
