### PR TITLE
Include HasValue check in BoundSwitchStatement

### LINKED ISSUE #9131: Incorrect NullReferenceException
The following code throws a NullReferenceException in a line where it cannot happen:

```
using System;
using System.Collections.Generic;

class Program
{
    private static Dictionary<int, Model> _dictionary = new Dictionary<int, Model> { { 3, new Model { A = 5 } } };

    private static void Main(string[] args)
    {
        Model model1 = null;
        switch (model1?.A)
        {
            case null:
                var model2 = _dictionary[3]; // NullReferenceException here
                Func<Model> f = () => model2;
                break;
        }
    }
}

class Model 
{
    public int A { get; set; }
}
```

I'm using Windows 7 Professional N SP1
.Net Framework 4.5.2 Console application
System.dll runtime version is v4.0.30319

### PR DESCRIPTION
**Pull request by cston**
If the switch expression is a ```Nullable<T>``` a conditional branch is added for the `HasValue` check.
That check was added as a separate `BoundStatement` outside of the `BoundSwitchStatement`.
If the lambda rewriter subsequently generated any display class instances, the allocations are added
as a prologue to the rewritten switch statement but since the conditional branch is outside the switch
statement, the branch skips the prologue, skipping the allocations. The change is to include the
conditional branch in the `BoundSwitchStatement` so the branch occurs after the prologue.

Fixes #9131

### CODE REVIEW

**Comment by cston** [comment]
@dotnet/roslyn-compiler please review
@mattgertz ask mode approval

**Comment by MattGertz** [comment]
Approved pending code reviews.

**Comment by gafter** [comment]
LGTM

**Comment by leppie** [comment]
Should this not go to master?

**Comment by jaredpar** [comment]
@leppie stabliization auto merges to master.  Checking in here puts the fix in our next release.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenClosureLambdaTests.cs [hunk 1]
```diff
@@ -5224,5 +5224,75 @@ public object Foo<T>()
...
+            Func<object> f = () => o;
+            break;
+        case 0:
+            o = 1;
+            break;
+        }
+    }
+}";
+            var options = TestOptions.DebugExe.WithConcurrentBuild(false);
+            var compilation = CompileAndVerify(source, options: options, expectedOutput: @"");
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenClosureLambdaTests.cs]: Consider printing something to verify that the default section is executed? Also, it wold be good to invoke the lambda and be able to observe the fact of lifting for the local.

**Comment by AlekseyTs** [comment]
LGTM

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenClosureLambdaTests.cs (hunk 1 above)
Comment (leppie) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenClosureLambdaTests.cs]: Could optimization not possibly remove null assignment?

**Comment by VSadov** [comment]
LGTM

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenClosureLambdaTests.cs (hunk 1 above)
Comment (cston) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenClosureLambdaTests.cs]: Added ```Console.Write()``` to `default` section and changed to release build options.
