### PR TITLE
Handle local promotion to long lived in stack spiller when local is type substituted

### LINKED ISSUE #4697: Using await in an object initializer within an async lambda crashes the compiler.
Description: We're experiencing a compiler crash, "error MSB6006: "csc.exe" exited with code -2146232797." when we await a task inside of an object initializer within an async lambda. 

The minimal code for reproducing is below:

 ```cs
using System;
using System.Threading.Tasks;

namespace CompilerCrashRepro2
{
    public class Item<T>
    {
        public T Value { get; set; }
    }

    public class Crasher
    {

public static Func<Task<Item<T>>> Build<T>()
{
    return async () => new Item<T>()
    {
        Value = await GetValue<T>()
    };
}

        public static Task<T> GetValue<T>()
        {
            throw new NotImplementedException();
        }
    }
}
```

Migrated from TFS/DevDiv 1210325

### PR DESCRIPTION
**Pull request by VSadov**
Handle local promotion to long lived in stack spiller when local is type substituted

Fixes #4697

### CODE REVIEW

**Comment by VSadov** [comment]
@gafter @AlekseyTs @jaredpar @agocke @TyOverby - please review

File: src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AwaitExpressionSpiller.cs [hunk 1]
```diff
@@ -1108,9 +1108,19 @@ private void PromoteAndAddLocals(BoundSpillSequenceBuilder builder, ImmutableArr
...
-                    SynthesizedLocal longLived = shortLived.WithSynthesizedLocalKindAndSyntax(SynthesizedLocalKind.AwaitSpill, _F.Syntax);
-                    _tempSubstitution.Add(shortLived, longLived);
+                    LocalSymbol longLived;
+
+                    var substituted = local as TypeSubstitutedLocalSymbol;
+                    if ((object)substituted != null)
+                    {
+                        longLived = substituted.WithSynthesizedLocalKindAndSyntax(SynthesizedLocalKind.AwaitSpill, _F.Syntax);
+                    }
+                    else {
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AwaitExpressionSpiller.cs]: Curly on next line

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/TypeSubstitutedLocalSymbol.cs [hunk 2]
```diff
@@ -97,5 +97,15 @@ internal override ImmutableArray<Diagnostic> GetConstantValueDiagnostics(BoundEx
         {
             return _originalVariable.GetConstantValueDiagnostics(boundInitValue);
         }
+
+        internal TypeSubstitutedLocalSymbol WithSynthesizedLocalKindAndSyntax(SynthesizedLocalKind kind, SyntaxNode syntax)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/TypeSubstitutedLocalSymbol.cs]: Did you consider making `WithSynthesizedLocalKindAndSyntax` an abstract method on LocalSymbol?  That would simplify the rewriter code.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs [hunk 3]
```diff
@@ -3400,6 +3400,48 @@ class Program
...
+        {
+            return async () => new Item<T>()
+            {
+                Value = await GetValue<T>()
+            };
+        }
+
+        public static Task<T> GetValue<T>()
+        {
+            return Task.FromResult(default(T));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs]: Consider adding a test that awaits for a small delay in order to test behavior for a non short-circuiting scenario. LGTM otherwise.

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/TypeSubstitutedLocalSymbol.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/TypeSubstitutedLocalSymbol.cs]: I agree, I think that would be an improvement.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs (hunk 3 above)
Comment (VSadov) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs]: I think these tests are adequate since the problem was not in the async machinery, but in the way we mark locals (short vs. long lived) and we simply could not compile this code at all.

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/TypeSubstitutedLocalSymbol.cs (hunk 2 above)
Comment (VSadov) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/TypeSubstitutedLocalSymbol.cs]: I considered that, but thought it would be a bit of an overkill. It is certainly possible.
