### PR TITLE
Bug Fix 5607: VB Parenthesis overtyping

### LINKED ISSUE #5607: VB "match closing parenthesis" fails for some constructs (works for others)
matchclosingparenthesis

Here's a minimal video repro. In all three lines I'm typing the closing parenthesis `)` rather than cursoring-right over it. Observe that "match closing parenthesis" feature works fine when I write the generic type, and when I write console.writeline, but it fails on list.RemoveAt.

I've noticed this failure a lot in my day-to-day coding. I haven't figured out which things work and which don't.

### PR DESCRIPTION
**Pull request by balajikris**
Fixes #5607

The bug was that automatic brace completion will not overtype close
parenthesis if the close parenthesis token was preceded by a numeric
literal. The bug was in `IsEntirelyWithinStringOrCharOrNumericLiteral`,
where we were imposing checks meant for chars and strings on numeric
literals, which was likely introduced in PR #1763. This change addresses
it by not enforcing checks meant for chars/strings on numeric literals.

### CODE REVIEW

**Comment by balajikris** [comment]
@dotnet/roslyn-ide : Please review.

File: src/Workspaces/VisualBasic/Portable/Extensions/SyntaxTreeExtensions.vb [hunk 1]
```diff
@@ -114,6 +114,12 @@ recurse:
                 Return True
             End If
 
+            ' If it is not a char or string literal, we're okay
+            If Not token.IsKind(SyntaxKind.CharacterLiteralToken, SyntaxKind.StringLiteralToken) Then
```
Comment (CyrusNajmabadi) [inline src/Workspaces/VisualBasic/Portable/Extensions/SyntaxTreeExtensions.vb]: I'd much rather you do the reverse check.  i.e. "if isKind(integer, decimal, date, floating) return"

**Comment by brettfo** [comment]
A big thank you for fixing this!  :shipit:

File: src/Workspaces/VisualBasic/Portable/Extensions/SyntaxTreeExtensions.vb (hunk 1 above)
Comment (balajikris) [inline src/Workspaces/VisualBasic/Portable/Extensions/SyntaxTreeExtensions.vb]: sure.

**Comment by Pilchie** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
:+1:
