### PR TITLE
Avoid optimizing away temporary for 'is not' pattern

### LINKED ISSUE #49262: `!(x is T)` and `x is not T` unequal semantics when x is of T type
**Version Used**: 

master branch 10.11.2020

**Steps to Reproduce**:

Compile and run the following code:
```
using static System.Console;

var c = new C();
M1(c);
M2(c);

void M1(C c) {
  if (!(c is C c1)) return;

  WriteLine(c1.Foo); // prints 42
}
    
void M2(C c) {
  if (c is not C c1) return;

  WriteLine(c1.Foo); // throws NRE
}

public class C 
{
    public int Foo => 42;
}
```

**Expected Behavior**:

Two `42` values being printed.

**Actual Behavior**:

One `42` is printed followed by `NullReferenceException`.

https://twitter.com/gafter/status/1326187196856954881

### PR DESCRIPTION
**Pull request by cston**
Pattern matching was optimizing away the temporary for the pattern input `c` in `c is not C c1`. That temporary would be reused by the pattern variable `c1`, but if optimized away, the temporary for the pattern variable is only assigned in the success case (when `c is not C`, where the variable is not needed) rather than the failure case (when `c is C`).

Fixes #49262

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PatternLocalRewriter.cs [hunk 1]
```diff
@@ -472,7 +471,13 @@ protected BoundExpression MakeRelationalTest(SyntaxNode syntax, BoundExpression
                 Debug.Assert(savedInputExpression != null);
                 return decisionDag;
 
-                bool usesOriginalInput(BoundDecisionDagNode node)
+                static bool isWhenClause(BoundDecisionDagNode node) =>
+                    node is BoundWhenDecisionDagNode { WhenExpression: { ConstantValue: null } };
+
+                static bool isNotClause(BoundDecisionDagNode node) =>
```
[the remark this answers is not in the document]
Comment (alrz) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PatternLocalRewriter.cs:477]: Looks like with this check other unrelated tests are affected. Is there any way to avoid that?(e.g.using Syntax)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PatternLocalRewriter.cs [hunk 2]
```diff
@@ -408,14 +408,13 @@ protected BoundExpression MakeRelationalTest(SyntaxNode syntax, BoundExpression
...
-                    decisionDag.TopologicallySortedNodes
-                    .Any(node => node is BoundWhenDecisionDagNode { WhenExpression: { ConstantValue: null } });
+                bool anyWhenClause = decisionDag.TopologicallySortedNodes.Any(node => isWhenClause(node));
 
                 var inputDagTemp = BoundDagTemp.ForOriginalInput(loweredInput);
                 if ((loweredInput.Kind == BoundKind.Local || loweredInput.Kind == BoundKind.Parameter)
                     && loweredInput.GetRefKind() == RefKind.None &&
-                    !anyWhenClause)
+                    !anyWhenClause &&
+                    !decisionDag.TopologicallySortedNodes.Any(node => isNotClause(node)))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PatternLocalRewriter.cs:417]: >!decisionDag.TopologicallySortedNodes.Any(node => isNotClause(node)) [](start = 20, length = 68)

It is quite possible I am missing something here, but, given the comment inside the ```if```, it feels like addition of this condition goes against the intent of the modified ```if``` condition. Specifically, the presence of the "is not" clause doesn't indicate a possibility for the input variable to change, therefore, the optimization should still be valid. It feels like there problem is elsewhere and we simply failing to "and we just reuse the local variable when we need the input expression" (i.e. failing to take optimization into account) when we generate code for the pattern failure branch.

File: src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs [hunk 3]
```diff
@@ -1158,35 +1158,38 @@ public class C {
             var compVerifier = CompileAndVerify(compilation);
             compVerifier.VerifyIL("C.M",
 @"{
-  // Code size       82 (0x52)
+  // Code size       84 (0x54)
   .maxstack  3
-  .locals init (string V_0) //name
+  .locals init (string V_0, //name
+                Person V_1)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs:1164]: >Person V_1 [](start = 16, length = 10)

It feels like this change is unexpected.

File: src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs [hunk 4]
```diff
@@ -1217,32 +1220,35 @@ public class C {
             var compVerifier = CompileAndVerify(compilation);
             compVerifier.VerifyIL("C.M",
 @"{
-  // Code size       64 (0x40)
+  // Code size       66 (0x42)
   .maxstack  3
   .locals init (string V_0, //name
-                string V_1) //name
+                string V_1, //name
+                Person V_2)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs:1227]: >Person V_2 [](start = 16, length = 10)

It feels like this change is unexpected.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PatternLocalRewriter.cs (hunk 2 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PatternLocalRewriter.cs:417]: > failing to take optimization into account) when we generate code for the pattern failure branch

I believe we do not generate code at the end of failure branches, only success branches.

---
In reply to: [524447959](https://github.com/dotnet/roslyn/pull/49369#discussion_r524447959) [](ancestors = 524447959)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PatternLocalRewriter.cs:417]: > I believe we do not generate code at the end of failure branches, only success branches.

Obviously somewhere we refer to the local and not taking optimization into account

---
In reply to: [525428080](https://github.com/dotnet/roslyn/pull/49369#discussion_r525428080) [](ancestors = 525428080,524447959)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PatternLocalRewriter.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PatternLocalRewriter.cs:477]: This method doesn't test for the presence of a `not` clause. It just tests for a place where the failure branch goes to a when clause or a final decision with a variable declared. That can happen in a switch statement like this:
```c#
    case X { Y: null }: ...
    case X x: ...
```
If the null test for `Y` fails, the `WhenFalse` is the `BoundWhenDecisionDagNod` for the second case. There is no `not` in this code. I don't think any code adjustment is needed for this case, so I don't think the test is right.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs [hunk 5]
```diff
@@ -6149,6 +6149,332 @@ static void Main()
...
+{
+    static void Main()
+    {
+        var c = new C();
+        M1(c);
+        M2(c);
+    }
+    static void M1(C c)
+    {
+        if (!(c is { F: 42 } c1)) return;
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs:6343]: I would expect identical code for these two methods.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PatternLocalRewriter.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (cston) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PatternLocalRewriter.cs]: Changed approach to handle 'not' outside the decision DAG based on your feedback.

---
In reply to: [525590499](https://github.com/dotnet/roslyn/pull/49369#discussion_r525590499) [](ancestors = 525590499)

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs [hunk 6]
```diff
@@ -6149,6 +6149,332 @@ static void Main()
...
+  IL_000c:  br.s       IL_000f
+  IL_000e:  ret
+  IL_000f:  ldloc.1
+  IL_0010:  call       ""void System.Console.WriteLine(object)""
+  IL_0015:  ldloc.0
+  IL_0016:  ldfld      ""object C.F""
+  IL_001b:  call       ""void System.Console.WriteLine(object)""
+  IL_0020:  ret
+}");
+        }
```
[the remark this answers is not in the document]
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs:6622]: Added, thanks.

---
In reply to: [523378828](https://github.com/dotnet/roslyn/pull/49369#discussion_r523378828) [](ancestors = 523378828)

File: src/Compilers/CSharp/Portable/BoundTree/BoundPattern.cs [hunk 7]
```diff
@@ -0,0 +1,21 @@
...
+    internal partial class BoundPattern
+    {
+        internal bool IsNegated(out BoundPattern innerPattern)
+        {
+            innerPattern = this;
+            bool negated = false;
+            while (innerPattern is BoundNegatedPattern negatedPattern)
+            {
+                negated = !negated;
+                innerPattern = negatedPattern.Negated;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/BoundPattern.cs:16]: >innerPattern [](start = 16, length = 12)

I would expect us to set ```innerPattern``` to null at the end if we return false.

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 8]
```diff
@@ -113,6 +119,19 @@ private BoundExpression BindIsPatternExpression(IsPatternExpressionSyntax node,
 
             return new BoundIsPatternExpression(
                 node, expression, pattern, decisionDag, whenTrueLabel: whenTrueLabel, whenFalseLabel: whenFalseLabel, boolType, hasErrors);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs:121]: > whenTrueLabel: whenTrueLabel, whenFalseLabel: whenFalseLabel [](start = 55, length = 61)

Are labels now "flipped around" for a negated pattern? This is very subtle and can be a source of confusion down the road. Consider capturing ```negated``` in the node and documenting its effect, or, perhaps, "flipping" the labels here explicitly.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs [hunk 9]
```diff
@@ -685,9 +685,10 @@ public override BoundNode VisitIsPatternExpression(BoundIsPatternExpression node
             LearnFromAnyNullPatterns(node.Expression, node.Pattern);
             VisitPatternForRewriting(node.Pattern);
             var expressionState = VisitRvalueWithState(node.Expression);
+            bool negated = node.Pattern.IsNegated(out _);
             var labelStateMap = LearnFromDecisionDag(node.Syntax, node.DecisionDag, node.Expression, expressionState, ref this.State);
-            var trueState = labelStateMap.TryGetValue(node.WhenTrueLabel, out var s1) ? s1.state : UnreachableState();
-            var falseState = labelStateMap.TryGetValue(node.WhenFalseLabel, out var s2) ? s2.state : UnreachableState();
+            var trueState = labelStateMap.TryGetValue(negated ? node.WhenFalseLabel : node.WhenTrueLabel, out var s1) ? s1.state : UnreachableState();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs:690]: >negated ? node.WhenFalseLabel : node.WhenTrueLabel [](start = 54, length = 50)

A need to do a fixup like that and the need to analyze a child for that feels very fragile. Easy to miss while working with the tree.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PatternLocalRewriter.cs [hunk 10]
```diff
@@ -472,7 +470,10 @@ protected BoundExpression MakeRelationalTest(SyntaxNode syntax, BoundExpression
                 Debug.Assert(savedInputExpression != null);
                 return decisionDag;
 
-                bool usesOriginalInput(BoundDecisionDagNode node)
+                static bool isWhenClause(BoundDecisionDagNode node) =>
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.PatternLocalRewriter.cs:473]: >isWhenClause [](start = 28, length = 12)

Consider reverting changes in this file, or renaming this function to reflect significance of the ConstantValue.

File: src/Compilers/CSharp/Portable/BoundTree/BoundPattern.cs (hunk 7 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/BoundTree/BoundPattern.cs:16]: I'd prefer to set a usable value in all cases. And with `is not not C`, we should set inner pattern, even though the return value is `false`.

---
In reply to: [530509675](https://github.com/dotnet/roslyn/pull/49369#discussion_r530509675) [](ancestors = 530509675)

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs (hunk 8 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs:121]: I considered adding a `bool IsNegated` property but that state is easily available from the `DecisionDag`. And switching the labels seem as fragile as leaving them as is.

---
In reply to: [530521673](https://github.com/dotnet/roslyn/pull/49369#discussion_r530521673) [](ancestors = 530521673)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs (hunk 9 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs:690]: Yes, it is fragile.

---
In reply to: [530525286](https://github.com/dotnet/roslyn/pull/49369#discussion_r530525286) [](ancestors = 530525286)

File: src/Compilers/CSharp/Portable/BoundTree/BoundPattern.cs (hunk 7 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/BoundTree/BoundPattern.cs:16]: > I'd prefer to set a usable value in all cases. 

Consider clearly documenting this behavior in a doc comment.

---
In reply to: [530597572](https://github.com/dotnet/roslyn/pull/49369#discussion_r530597572) [](ancestors = 530597572,530509675)

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs (hunk 8 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs:121]: > I considered adding a bool IsNegated property but that state is easily available from the DecisionDag. 

I am not sure I am following. It doesn't look like the state is inferred from a DecisionDag in the lowering and in the nullable walker. In any case, I think we need to have that clearly documented. Consider adding a comment with a note above this construction and also adding comments in BoundNodes.xml for the properties involved.  

---
In reply to: [530599832](https://github.com/dotnet/roslyn/pull/49369#discussion_r530599832) [](ancestors = 530599832,530521673)

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 11]
```diff
@@ -111,8 +117,23 @@ private BoundExpression BindIsPatternExpression(IsPatternExpressionSyntax node,
                 }
             }
 
+            // decisionDag, whenTrueLabel, and whenFalseLabel represent the decision DAG and
+            // branch labels for the original pattern rather than the inner pattern.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs:121]: >branch labels for the original pattern rather than the inner pattern. [](start = 15, length = 69)

Is this accurate? If this is for the original pattern then why any flipping is necessary?

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 7)

**Comment by cston** [comment]
@dotnet/roslyn-compiler, please review, thanks.

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 12]
```diff
@@ -111,8 +117,23 @@ private BoundExpression BindIsPatternExpression(IsPatternExpressionSyntax node,
                 }
             }
 
+            // decisionDag, whenTrueLabel, and whenFalseLabel represent the decision DAG for the inner pattern,
+            // after removing any outer 'not's, so consumers will need to compensate for negated patterns.
```
[the remark this answers is not in the document]
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs:121]: Added `BoundIsPatternExpression.IsNegated` property.

---
In reply to: [533842037](https://github.com/dotnet/roslyn/pull/49369#discussion_r533842037) [](ancestors = 533842037)

**Comment by cston** [comment]
@dotnet/roslyn-compiler, please review, thanks.

File: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml [hunk 13]
```diff
@@ -2022,9 +2022,13 @@
     <Field Name="Format" Type="BoundLiteral?"/>
   </Node>
   
+    <!-- An 'is pattern'. The fields DecisionDag, WhenTrueLabel, and WhenFalseLabel represent the inner pattern
+         after removing any outer 'not's, so consumers (such as lowering and definite assignment of the local in
+         'is not Type t') will need to compensate for negated patterns. -->
   <Node Name="BoundIsPatternExpression" Base="BoundExpression">
     <Field Name="Expression" Type="BoundExpression" Null="disallow"/>
     <Field Name="Pattern" Type="BoundPattern" Null="disallow"/>
+    <Field Name="IsNegated" Type="bool"/>
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml:2031]: >IsNegated [](start = 17, length = 9)

I think this property needs a comment, or, alternatively, should be mentioned in the comment above.

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs [hunk 14]
```diff
@@ -962,13 +962,8 @@ public override BoundNode VisitIsPatternExpression(BoundIsPatternExpression node
...
             VisitRvalue(node.Expression);
 
-            var pattern = node.Pattern;
-            bool negated = false;
-            while (pattern is BoundNegatedPattern n)
-            {
-                negated = !negated;
-                pattern = n.Negated;
-            }
+            bool negated = node.Pattern.IsNegated(out var pattern);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:965]: >bool negated = node.Pattern.IsNegated(out var pattern); [](start = 12, length = 55)

I think we should use property here, this is what it is there for.

**Review by gafter — APPROVED** [review]
😷

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs [hunk 15]
```diff
@@ -6149,6 +6149,524 @@ static void Main()
...
+
+        [Theory]
+        [InlineData("!(c is C c1)")]
+        [InlineData("!(c is (C c1))")]
+        [InlineData("!(c is { } c1)")]
+        [InlineData("c is not C c1")]
+        [InlineData("c is not (C c1)")]
+        [InlineData("c is not (not not C c1)")]
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs:6236]: nit: missed opportunity to name the class "opposite day"

**Review by RikkiGibson — APPROVED** [review]

**Comment by alrz** [comment]
@cston @gafter 

I'm wondering why we actually flipped the branches rather than fixing up the optimizer?

I couldn't find where this "temp optimization" happens. We might need to change this logic to enable variables under `or` as well.

**Comment by cston** [comment]
@alrz 

> I'm wondering why we flipped the branches rather than actually fixing up dag construction?
> 
> I couldn't find where this "temp optimization" happens. We might need to change this logic to enable variables under `or` as well.

Flipping branches was a simple solution for https://github.com/dotnet/roslyn/issues/49262 (see https://github.com/dotnet/roslyn/pull/49369), although as you suggest, that approach may not be sufficient to handle variables under `or`.

The "temp optimization" occurs `PatternLocalRewriter.ShareTempsAndEvaluateInput()`. See the first commit https://github.com/dotnet/roslyn/pull/49369/commits/f4368606633d2f14557679808c13f89d8f2fc6a7 in that PR which skipped the optimization rather than flipping branches.

**Comment by alrz** [comment]
Yeah, turns out ShareTempsAndEvaluateInput is innocent here. 

For `or` patterns we actually require a state per each side with its own bindings, while currently there's only one state per each pattern of any form. And even when we do this, we need to modify lowering to expect intermediate bindings.

For `not` patterns, as I mentioned above, bindings should happen in the opposite branch and possibly lowered as intermediate bindings. That last part is not required for top-level `not` patterns, because at that point we have reached the end of dag lowering.

**Comment by RikkiGibson** [comment]
Is there a language feature in development that involves adding the ability to declare variables under 'or' patterns?

**Comment by 333fred** [comment]
> Is there a language feature in development that involves adding the ability to declare variables under 'or' patterns?

https://github.com/dotnet/csharplang/pull/4592
