### PR TITLE
Fix project based CompletionProvider

### LINKED ISSUE #61950: CompletionProvider descriptions not working
I have a custom `CompletionProvider` that overrides `GetDescriptionAsync` to add text to the completion item tooltip. The completion provider works, but `GetDescriptionAsync` is never called and the tooltip is empty.

image

It also doesn't work in unit tests. `CompletionService.GetDescriptionAsync` doesn't return a description.

I did some debugging and _I think_ it is because the code that displays the items includes project providers:
https://github.com/dotnet/roslyn/blob/5f01883263cc2f1da722ccc54d03a60e6fe31bfc/src/Features/Core/Portable/Completion/CompletionServiceWithProviders.ProviderManager.cs#L102-L120

But when displaying the description, and getting the provider for an item:
https://github.com/dotnet/roslyn/blob/f2ef02aa06aa8d15863fad5438aa6817c79d7cde/src/Features/Core/Portable/Completion/CompletionServiceWithProviders.cs#L411-L423

The providers are loaded from a different place, which doesn't include the custom provider:
https://github.com/dotnet/roslyn/blob/f2ef02aa06aa8d15863fad5438aa6817c79d7cde/src/Features/Core/Portable/Completion/CompletionServiceWithProviders.ProviderManager.cs#L44-L75

cc @sharwell @CyrusNajmabadi

### PR DESCRIPTION
**Pull request by genlu**
Fix #61950 and #46803. 

~~Majority of the change in this PR are from https://github.com/dotnet/roslyn/pull/61943, I based this PR on that branch in order to minimize future merge conflicts. To review this PR, you can ignore everything except the last commit https://github.com/dotnet/roslyn/pull/61976/commits/58639aff8fb765dd9acf334c805bc7f7bd50c240~~

### CODE REVIEW

File: src/Features/Core/Portable/Completion/CompletionService.ProviderManager.cs [hunk 1]
```diff
@@ -57,41 +54,74 @@ public ProviderManager(CompletionService service)
...
                     {
-                        provider = _nameToProvider.GetOrAdd(item.ProviderName, _getProviderByName);
+                        if (!_nameToProvider.TryGetValue(item.ProviderName, out provider))
+                        {
+                            provider = GetImportedAndBuiltInProviders(roles: ImmutableHashSet<string>.Empty).FirstOrDefault(p => p.Name == item.ProviderName);
+                            _nameToProvider.Add(item.ProviderName, provider);
+                        }
                     }
+
+                    provider ??= GetProjectCompletionProviders(project).FirstOrDefault(p => p.Name == item.ProviderName);
```
Comment (genlu) [inline src/Features/Core/Portable/Completion/CompletionService.ProviderManager.cs:124]: This is the core to the fix, we didn't consult project references for operations tied to completion item befire (get description, text change, etc.)

Comment (JoeRobich) [reply src/Features/Core/Portable/Completion/CompletionService.ProviderManager.cs:124]: Should we check if project is null to avoid any unnecessary work?

Comment (genlu) [reply src/Features/Core/Portable/Completion/CompletionService.ProviderManager.cs:124]: There's a null check two calls in, but I think it'd be good to do it here too. Will fix

**Comment by JamesNK** [comment]
Will this make it into 17.3?

File: src/Features/Core/Portable/Completion/CompletionService.ProviderManager.cs [hunk 2]
```diff
@@ -57,41 +54,74 @@ public ProviderManager(CompletionService service)
...
                 CompletionProvider? provider = null;
 
                 if (item.ProviderName != null)
                 {
                     lock (_gate)
                     {
-                        provider = _nameToProvider.GetOrAdd(item.ProviderName, _getProviderByName);
+                        if (!_nameToProvider.TryGetValue(item.ProviderName, out provider))
+                        {
+                            provider = GetImportedAndBuiltInProviders(roles: ImmutableHashSet<string>.Empty).FirstOrDefault(p => p.Name == item.ProviderName);
```
Comment (sharwell) [inline src/Features/Core/Portable/Completion/CompletionService.ProviderManager.cs:119]: ⚠️ This is going to capture `item` even on the fast path (results in an allocation even when `_nameToProvider` already has this name in the map)

File: src/Features/Core/Portable/Completion/CompletionService.ProviderManager.cs [hunk 3]
```diff
@@ -57,41 +54,74 @@ public ProviderManager(CompletionService service)
...
                 }
             }
 
-            public CompletionProvider? GetProvider(CompletionItem item)
+            public ImmutableArray<CompletionProvider> GetProviders(ImmutableHashSet<string> roles, Project? project)
+            {
+                using var _ = ArrayBuilder<CompletionProvider>.GetInstance(out var providers);
+                providers.AddRange(GetImportedAndBuiltInProviders(roles));
+                providers.AddRange(GetProjectCompletionProviders(project));
+                return providers.ToImmutable();
```
Comment (sharwell) [inline src/Features/Core/Portable/Completion/CompletionService.ProviderManager.cs:106]: ❔ How hot is this path? I worry about the allocation costs it may have for using `ArrayBuilder` instead of `ConcatFast` like the filtered providers below.

**Review by sharwell — CHANGES_REQUESTED** [review]
Need to fix the capturing delegate and determine if a change is needed for `GetAllProviders`

File: src/Features/Core/Portable/Completion/CompletionService.cs [hunk 4]
```diff
@@ -392,17 +392,17 @@ public virtual TextSpan GetDefaultCompletionListSpan(SourceText text, int caretP
...
 
         /// <summary>
         /// Don't call. Used for pre-populating NuGet providers only.
         /// </summary>
         internal static ImmutableArray<CompletionProvider> GetProjectCompletionProviders(Project? project)
             => ProviderManager.GetProjectCompletionProviders(project);
 
-        internal CompletionProvider? GetProvider(CompletionItem item)
-            => _providerManager.GetProvider(item);
+        internal CompletionProvider? GetProvider(CompletionItem item, Project? project = null)
```
[the remark this answers is not in the document]
Comment (genlu) [reply src/Features/Core/Portable/Completion/CompletionService.cs:404]: There's one codepath in VB [CompltionService](https://sourceroslyn.io/#Microsoft.CodeAnalysis.VisualBasic.Features/Completion/VisualBasicCompletionService.vb,108) that doesn't have document/project available.

File: src/Features/Core/Portable/Completion/CompletionService.ProviderManager.cs (hunk 3 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/CompletionService.ProviderManager.cs:106]: This is only called under a lock when we have a cache miss in `_rolesToProviders`, so once per roles

Comment (genlu) [reply src/Features/Core/Portable/Completion/CompletionService.ProviderManager.cs:106]: This is only used in CompletionService.TestAccessor

File: src/EditorFeatures/TestUtilities/Completion/AbstractCompletionProviderTests.cs [hunk 5]
```diff
@@ -106,7 +106,7 @@ protected static async Task<bool> CanUseSpeculativeSemanticModelAsync(Document d
         internal virtual CompletionService GetCompletionService(Project project)
         {
             var completionService = project.LanguageServices.GetRequiredService<CompletionService>();
-            var completionProviders = completionService.GetImportedProviders();
+            var completionProviders = completionService.GetLazyImportedProviders();
```
[the remark this answers is not in the document]
Comment (genlu) [reply src/EditorFeatures/TestUtilities/Completion/AbstractCompletionProviderTests.cs]: good catch. Switched to using TestAccessor

File: src/Features/Core/Portable/Completion/CompletionService.ProviderManager.cs (hunk 2 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/CompletionService.ProviderManager.cs]: fixed with pooled predicate

File: src/Features/Core/Portable/Completion/CompletionService.ProviderManager.cs [hunk 6]
```diff
@@ -98,6 +96,9 @@ ImmutableArray<CompletionProvider> GetImportedAndBuiltInProvidersWorker(Immutabl
                 }
             }
 
+            /// <summary>
+            /// Don't call. For test only.
+            /// </summary>
```
Comment (sharwell) [inline src/Features/Core/Portable/Completion/CompletionService.ProviderManager.cs:101]: 💡 This can move to a test accessor with two benefits:

1. The test method is constrained to a test method location
2. We have an analyzer to enforce that test accessors are only used by test code

**Review by sharwell — APPROVED** [review]

File: src/Features/Core/Portable/Completion/CompletionService.ProviderManager.cs (hunk 6 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/CompletionService.ProviderManager.cs]: fixed
