### PR TITLE
Condense quick info

### LINKED ISSUE #32838: Object browser does not render <br/>
**Version Used**: Visual Studio 2019 Preview 2

🔗 Originally filed as https://devdiv.visualstudio.com/DevDiv/_workitems/edit/176321

**Steps to Reproduce**:

1. Attempt to write a documentation comment with a line break that is _not_ a paragraph break using `<br/>`
2. View the documentation comment in Object Browser

**Expected Behavior**:

The `<br/>` is rendered as a line break that is not a paragraph break.

**Actual Behavior**:

The `<br/>` is ignored. Attempting to use `<para>` as an alternative creates a paragraph break.

### LINKED ISSUE #33001: In documentation, mark <para> will generate empty line in tooltip
When using &lt;para&gt; to insert a new line in the documentation, &lt;para&gt; will generates additional empty lines in the Tooltip displayed by IntelliSense or mouseover on keywords.
this problem is start at VS 2013, please fix it

image

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/441448/in-documentation-mark-will-generate-empty-line-in.html
VSTS ticketId: 782031_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #32838
Fixes #33001

## Before

image

## After

image

### CODE REVIEW

**Comment by sharwell** [comment]
Build failure was caused by #33785; re-running

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs [hunk 1]
```diff
@@ -79,16 +107,67 @@ internal static class IntellisenseQuickInfoBuilder
...
             var content = new ContainerElement(
-                                ContainerElementStyle.Stacked,
+                                ContainerElementStyle.Stacked | ContainerElementStyle.VerticalPadding,
                                 elements);
 
             return new IntellisenseQuickInfoItem(trackingSpan, content);
         }
 
-        private static ClassifiedTextElement BuildClassifiedTextElement(QuickInfoSection section)
+        private static IEnumerable<object> BuildClassifiedTextElements(QuickInfoSection section)
```
Comment (heejaechang) [inline src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: so, this actually doesnt consume any section info except taggedParts. which is good. can this be changed to extension method so that other can reuse? like ToClassifiedTexts(this IEnumerable<TaggedText>) ?

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs [hunk 2]
```diff
@@ -79,16 +107,67 @@ internal static class IntellisenseQuickInfoBuilder
...
+                    }
+                    else
+                    {
+                        currentParagraph.Add(new ClassifiedTextElement(currentRuns));
+                        currentRuns.Clear();
+                    }
+                }
+                else
+                {
+                    currentRuns.Add(new ClassifiedTextRun(part.Tag.ToClassificationTypeName(), part.Text));
```
Comment (heejaechang) [inline src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: it seems could become generic helper extension method if we don't already have one. TaggedText.ToClassifiedText()

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs [hunk 3]
```diff
@@ -79,16 +107,67 @@ internal static class IntellisenseQuickInfoBuilder
...
 
-        private static ClassifiedTextElement BuildClassifiedTextElement(QuickInfoSection section)
+        private static IEnumerable<object> BuildClassifiedTextElements(QuickInfoSection section)
         {
-            return new ClassifiedTextElement(section.TaggedParts.Select(
-                    part => new ClassifiedTextRun(part.Tag.ToClassificationTypeName(), part.Text)));
+            var paragraphs = new List<object>();
+            var currentParagraph = new List<object>();
+            var currentRuns = new List<ClassifiedTextRun>();
+            foreach (var part in section.TaggedParts)
```
Comment (heejaechang) [inline src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: it would be nice if you can explain what this is actually trying to do.

Comment (heejaechang) [reply src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: and this code seems require some testing on various different input cases.

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs [hunk 4]
```diff
@@ -79,16 +107,67 @@ internal static class IntellisenseQuickInfoBuilder
...
+                    {
+                        currentParagraph.Add(new ClassifiedTextElement(currentRuns));
+                        currentRuns.Clear();
+                    }
+                }
+                else
+                {
+                    currentRuns.Add(new ClassifiedTextRun(part.Tag.ToClassificationTypeName(), part.Text));
+                }
+            }
```
Comment (heejaechang) [inline src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: so basically if there is multiple linebreaks then it got ignored.

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs (hunk 2 above)
Comment (heejaechang) [reply src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: any taggedtext before line breaks and accumulated in current run

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs [hunk 5]
```diff
@@ -79,16 +107,67 @@ internal static class IntellisenseQuickInfoBuilder
...
+                            {
+                                paragraphs.Add(new ContainerElement(ContainerElementStyle.Stacked, currentParagraph));
+                            }
+
+                            currentParagraph.Clear();
+                        }
+                    }
+                    else
+                    {
+                        currentParagraph.Add(new ClassifiedTextElement(currentRuns));
```
Comment (heejaechang) [inline src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: first line break after tagged texts.

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs [hunk 6]
```diff
@@ -79,16 +107,67 @@ internal static class IntellisenseQuickInfoBuilder
...
+            var currentParagraph = new List<object>();
+            var currentRuns = new List<ClassifiedTextRun>();
+            foreach (var part in section.TaggedParts)
+            {
+                if (part.Tag == TextTags.LineBreak)
+                {
+                    if (currentRuns.Count == 0)
+                    {
+                        if (currentParagraph.Count > 0)
+                        {
```
Comment (heejaechang) [inline src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: second line break but there was tagged text before first line break.

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs [hunk 7]
```diff
@@ -79,16 +107,67 @@ internal static class IntellisenseQuickInfoBuilder
...
+                            if (currentParagraph.Count == 1)
+                            {
+                                paragraphs.Add(currentParagraph[0]);
```
Comment (heejaechang) [inline src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: if it is first time, then put paragraph as it is.

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs [hunk 8]
```diff
@@ -79,16 +107,67 @@ internal static class IntellisenseQuickInfoBuilder
...
+                            }
+                            else
+                            {
+                                paragraphs.Add(new ContainerElement(ContainerElementStyle.Stacked, currentParagraph));
```
Comment (heejaechang) [inline src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: if there was multiple tagged text with single line break, and then second continuous line breaks then, but them in stacked form.

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs [hunk 9]
```diff
@@ -41,21 +42,48 @@ internal static class IntellisenseQuickInfoBuilder
...
+                    }
+                    else
+                    {
+                        elements.Add(element);
+                    }
+                }
             }
 
-            var elements = new List<object>
+            elements.Insert(0, new ContainerElement(ContainerElementStyle.Wrapped, firstLineElements));
```
Comment (heejaechang) [inline src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: this container element still needed if description is null? or desSection is empty?

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs [hunk 10]
```diff
@@ -41,21 +42,48 @@ internal static class IntellisenseQuickInfoBuilder
                 firstLineElements.Add(new ImageElement(warningGlyph.GetImageId()));
             }
 
+            var elements = new List<object>();
             var descSection = quickInfoItem.Sections.FirstOrDefault(s => s.Kind == QuickInfoSectionKinds.Description);
             if (descSection != null)
             {
-                firstLineElements.Add(BuildClassifiedTextElement(descSection));
+                var isFirstElement = true;
+                foreach (var element in BuildClassifiedTextElements(descSection))
```
Comment (heejaechang) [inline src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: this code could use same pattern as the one before? the documentationCommentSection?

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs (hunk 1 above)
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: The return type contains both `ClassifiedTextElement` and `ContainerElement`, which do not share a base type other than `object`. This make the return value of `BuildClassifiedTextElements` particularly unpleasant to use. The current form allows me to encapsulate the ugliness so the untyped enumeration is not visible outside the containing `IntellisenseQuickInfoBuilder` type. I'm not opposed to refactoring this code, but I don't want to expose it with a weakly-typed signatures. Thoughts on how to resolve it?

File: src/EditorFeatures/Test2/IntelliSense/IntellisenseQuickInfoBuilderTests.vb [hunk 11]
```diff
@@ -12,88 +17,476 @@ Imports QuickInfoItem = Microsoft.CodeAnalysis.QuickInfo.QuickInfoItem
...
+            Assert.Equal(expected.AutomationName, actual.AutomationName)
+        End Sub
+
+        Private Shared Sub AssertEqualClassifiedTextElement(expected As ClassifiedTextElement, actual As ClassifiedTextElement)
+            Assert.Equal(expected.Runs.Count, actual.Runs.Count)
+            For Each pair In expected.Runs.Zip(actual.Runs, Function(expectedRun, actualRun) (expectedRun, actualRun))
+                AssertEqualClassifiedTextRun(pair.expectedRun, pair.actualRun)
+            Next
+        End Sub
+
```
Comment (heejaechang) [inline src/EditorFeatures/Test2/IntelliSense/IntellisenseQuickInfoBuilderTests.vb]: the test seems missing some cases for state machine for GetClassifiedText method. like line breaks at the start or 2+ line breaks and etc.

File: src/Features/Core/Portable/DocumentationComments/AbstractDocumentationCommentFormattingService.cs [hunk 12]
```diff
@@ -72,6 +73,20 @@ public void MarkBeginOrEndPara()
                 _anyNonWhitespaceSinceLastPara = false;
             }
 
+            public void MarkLineBreak()
+            {
+                // If this is a <br> with nothing before it, then skip it.
+                if (_anyNonWhitespaceSinceLastPara == false)
```
Comment (heejaechang) [inline src/Features/Core/Portable/DocumentationComments/AbstractDocumentationCommentFormattingService.cs]: do we have test for this change?

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs (hunk 4 above)
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: Currently yes. I can add tests verifying that each of the following produces the same result (the first being the preferred source form for this output):

1. `<para>text</para><para>text</para>`
2. `text<br/><br/>text`
3. `text<br/><br/><br/>text`
4. `<para>text</para><br/><para>text</para>`

Any objection to the behavior in 2-4 as described? If so, can you clarify how it should be presented?

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs (hunk 1 above)
Comment (heejaechang) [reply src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: is ClassifiedTextElement thing only for quick info? or this behavior (format) we only want to use in quick info? otherwise, sharing implementation seems good to me.

File: src/Features/Core/Portable/DocumentationComments/AbstractDocumentationCommentFormattingService.cs (hunk 12 above)
Comment (sharwell) [reply src/Features/Core/Portable/DocumentationComments/AbstractDocumentationCommentFormattingService.cs]: The entire feature area is a test hole. If you don't see the test in this PR, there are no tests for it.

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs (hunk 1 above)
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: These are only for Quick Info.

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs (hunk 4 above)
Comment (heejaechang) [reply src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: I don't have objection on what we decide on UX. confident that people who care on those were discussed and decided what the good experience is. I was more asking whether there is a test covering it so that people know the experience is intentional.

File: src/Features/Core/Portable/DocumentationComments/AbstractDocumentationCommentFormattingService.cs (hunk 12 above)
Comment (heejaechang) [reply src/Features/Core/Portable/DocumentationComments/AbstractDocumentationCommentFormattingService.cs]: sure, but you could add more tests if you see that's beneficial to make this area more reliable. having test in this area will tell devs what was done intentionally and what is just result of implementation happen to be written in a way.

Comment (heejaechang) [reply src/Features/Core/Portable/DocumentationComments/AbstractDocumentationCommentFormattingService.cs]: in my experience, whenever there is complex state machine, unless there is tests covering all states, it is hard to know for those missing cases, whether it just happen to be that way or it is done intentionally that way.

for example, it looks like this code and the other code, it looks like multiple line breaks are ignored when used as first elements in quickinfo or when used in the middle of sections. is that intentional for both cases? or it is just the way things were implemented? without test, I dont know.

Comment (heejaechang) [reply src/Features/Core/Portable/DocumentationComments/AbstractDocumentationCommentFormattingService.cs]: I am not asking you to write tests covering all different states. I was just asking so you think and you decide if you haven't thought about it. if you already did, then move on.

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs (hunk 4 above)
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: I will add tests for each of the above.

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs (hunk 2 above)
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: > it seems could become generic helper extension method if we don't already have one

We didn't already have one, but this code is only used by this IntelliSense builder so it didn't seem to improve clarity to move this to another file. I did end up refactoring the pattern used for moving content from `currentParagraph`&rarr;`paragraphs`.

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs (hunk 3 above)
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: Lots of comments coming in the next push.

File: src/Features/Core/Portable/DocumentationComments/AbstractDocumentationCommentFormattingService.cs (hunk 12 above)
Comment (sharwell) [reply src/Features/Core/Portable/DocumentationComments/AbstractDocumentationCommentFormattingService.cs]: I'm happy to add any tests you think of, and am planning to add at least the ones mentioned in comments previously.

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs (hunk 7 above)
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: Now documented in the `CreateParagraphFromLines` method.

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs (hunk 8 above)
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: Now documented in the `CreateParagraphFromLines` method.

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs (hunk 6 above)
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: Now documented.

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs (hunk 5 above)
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: Now documented.

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs (hunk 4 above)
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: I have now _documented_ the ignored empty paragraphs, but not marking this resolved since I'm still working on the tests.

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs (hunk 3 above)
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: Now documented. Marking this comment resolved; we have a couple other open comments tracking my work to add more tests.

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs (hunk 2 above)
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: I pushed the refactoring and documentation update for `BuildClassifiedTextElements`, so it should be much more clear within that method.

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs (hunk 1 above)
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: I looked into refactoring this, specifically by wrapping raw `ClassifiedTextElement` paragraphs into a single-element `ContainerElement`. While these would look the same in Quick Info, they would end up adding new elements to the WPF rendering tree. Since the code is not used outside this type and the documentation should keep the current approach clear, it doesn't seem like extracting an extension method for this would help clarity at this time.

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs (hunk 4 above)
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: ➡️ Added documentation in 05ab07fee61a82a457e7c7952d15c5a08f4eb0b2, and added a bunch of tests in d8d897ee380395d72057d1bf4a9e3b91998e67d8. This suggestion caught a bug in the implementation. 👍

File: src/EditorFeatures/Test2/IntelliSense/IntellisenseQuickInfoBuilderTests.vb (hunk 11 above)
Comment (sharwell) [reply src/EditorFeatures/Test2/IntelliSense/IntellisenseQuickInfoBuilderTests.vb]: Tests have been added 👍

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs (hunk 9 above)
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: I have no idea how to produce such an element.

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs (hunk 10 above)
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/IntellisenseQuickInfoBuilder.cs]: The sections now use similar code patterns. It's not perfect, but the test coverage should be much better and combined with the new documentation it lower our chances of a regression.

File: src/EditorFeatures/Test2/IntelliSense/IntellisenseQuickInfoBuilderTests.vb [hunk 13]
```diff
@@ -12,88 +17,537 @@ Imports QuickInfoItem = Microsoft.CodeAnalysis.QuickInfo.QuickInfoItem
...
+        <InlineData("text1<br/><br/>text2")>
+        <InlineData("text1<br/><br/><br/>text2")>
+        <InlineData("<br/>text1<br/><br/>text2<br/>")>
+        <InlineData("<br/><br/>text1<br/><br/>text2<br/><br/>")>
+        <InlineData("<para>text1<br/><br/>text2</para>")>
+        <InlineData("<para/>text1<br/><br/>text2<para/>")>
+        <InlineData("<para/><para/>text1<br/><br/>text2<para/><para/>")>
+        <InlineData("<para>text1</para><br/><para>text2</para>")>
+        <WorkItem(33001, "https://github.com/dotnet/roslyn/issues/33001")>
+        Public Async Sub EquivalentParagraphForms(summary As String)
```
Comment (sharwell) [inline src/EditorFeatures/Test2/IntelliSense/IntellisenseQuickInfoBuilderTests.vb]: @mavasani This parameter is incorrectly reported as unused.

Comment (sharwell) [reply src/EditorFeatures/Test2/IntelliSense/IntellisenseQuickInfoBuilderTests.vb]: :arrow_right: Moved to #33898
