### PR TITLE
Use a distinct diagnostic ID when an exhaustiveness report uses an unnamed enum value.

### LINKED ISSUE #47066: Split CS8509 into unhandled named and unnamed enum values
**Brief description:**

CS8509 is a warning you get when a switch expression doesn't have a pattern for certain enum values. You get the same warning when the enum value is named as when the value is unnamed (via a cast like `(EnumType)9`). 

This means that even when every named enum value has been handled you still get a warning. This encourages programmers to add a pattern that handles every case (often times this case simply throws an exception i.e. `_ => throw new ..`).

But that means that when you add a new named value to your enum you won't get a warning since it has already been handled (incorrectly) by the catch-all pattern.

My suggestion:

If instead you get a different warning depending on whether or not the unhandled enum value is named or unnamed, people could decide for themselves how they would like to approach this issue by enabling/disabling the appropriate warning.

**Languages applicable:**

C#, I'm not sure if VB has switch expressions.

**Code example that the analyzer should report:**

With this enum:

```cs
public enum Operation
{
    Plus,
    Minus,
    Multiply,
}
```

this code:

```cs
public static string OperationToString(Operation op)
{
    return op switch
    {
        Operation.Plus => "+",
        Operation.Minus => "-",
        // Note!: Operation.Multiply has not been handled by accident
    };
}
```

and this code:

```cs
public static string OperationToString(Operation op)
{
    return op switch
    {
        Operation.Plus => "+",
        Operation.Minus => "-",
        Operation.Multiply => "*",
        // Note!: Every named enum value has been handled
    };
}
```

should be reported with different warnings.

**Additional information:**

I expect neither warning to trigger when you add a catch-all pattern. This means that when you intend for your switch expression to handle every named value you would generally not add a catch-all pattern so that you get an alert on those switch expressions when you add a new named enum value.

I think the [Flags] attribute should cause *unnamed* enum values that can be created by using `bitwise or` on *named* enum values should also be considered named for the purposes of these warning.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #47066

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/SwitchExpressionBinder.cs [hunk 1]
```diff
@@ -98,9 +98,13 @@ internal override BoundExpression BindSwitchExpressionCore(SwitchExpressionSynta
             {
                 if (n is BoundLeafDecisionDagNode leaf && leaf.Label == defaultLabel)
                 {
+                    bool unnamedEnumValue = false;
                     var samplePattern = PatternExplainer.SamplePatternForPathToDagNode(
-                        BoundDagTemp.ForOriginalInput(boundInputExpression), nodes, n, nullPaths: false, out bool requiresFalseWhenClause);
-                    ErrorCode warningCode = requiresFalseWhenClause ? ErrorCode.WRN_SwitchExpressionNotExhaustiveWithWhen : ErrorCode.WRN_SwitchExpressionNotExhaustive;
+                        BoundDagTemp.ForOriginalInput(boundInputExpression), nodes, n, nullPaths: false, out bool requiresFalseWhenClause, ref unnamedEnumValue);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/SwitchExpressionBinder.cs:103]: >ref [](start = 139, length = 3)

nit: why use `ref` rather than `out`?

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 1) with nitpick (`ref` vs. `out`)

**Review by RikkiGibson — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Binder/SwitchExpressionBinder.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/SwitchExpressionBinder.cs:103]: It does feel like this specific parameter could be made 'out' while the rest of the stuff inside remains as 'ref'--just have to assign a 'false' default value before passing the out parameter on to 'SamplePatternForTemp'.

**Review by RikkiGibson — APPROVED** [review]
