### PR TITLE
Do not allow rename on the well known ValueTuple types

### LINKED ISSUE #14159: Rename tracking codefix crashes when renaming tuple
**Steps to Reproduce**:

Change `ValueTuple` to `Tuple` as shown below and invoke the lighbulb

Before
```C#
using System;

class C {
    void M() {
        var x = new ValueTuple<int, int>();
    }
}
```
After
```C#
using System;

class C {
    void M() {
        var x = new Tuple<int, int>();
    }
}
```

**Expected Behavior**:
No Crash

**Actual Behavior**:
CodeFix crashes with the following stack
```
System.AggregateException : One or more errors occurred. ---> Index was outside the bounds of the array.
   at async Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.RenameSymbolAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass15_0.<GetPreviewOperationsAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass26_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
---> (Inner Exception #0) System.IndexOutOfRangeException : Index was outside the bounds of the array.
   at async Microsoft.CodeAnalysis.Rename.RenameLocations.ReferenceProcessing.GetRenamableDefinitionLocationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Rename.RenameLocations.AddLocationsReferenceSymbolsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Rename.RenameLocations.FindAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Rename.Renamer.RenameSymbolAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.RenameSymbolWorkerAsync(<Unknown Parameters>)<---

```

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #14159

The well-known ValueTuple types are very special in that you can ask for
the SymbolInfo on the ValueTuple token and not get back the ValueTuple
type. This means that the token we invoke rename on has no locations,
which Rename Tracking mistakenly interpreted as being okay to rename.
This has been fixed, and also the RenameUtilities.GetTokenRenameInfo
method has been updated to return NoSymbolsTokenInfo when it finds an
ITypeSymbol with IsTupleType.

### CODE REVIEW

**Comment by dpoeschl** [comment]
Tagging for review: @dotnet/roslyn-ide @CyrusNajmabadi @jmarolf

File: src/EditorFeatures/Core/Implementation/RenameTracking/RenameTrackingTaggerProvider.TrackingSession.cs [hunk 1]
```diff
@@ -194,7 +194,7 @@ public void Cancel()
                     // Get the source symbol if possible
                     var sourceSymbol = await SymbolFinder.FindSourceDefinitionAsync(symbol, document.Project.Solution, _cancellationToken).ConfigureAwait(false) ?? symbol;
 
-                    if (!sourceSymbol.Locations.All(loc => loc.IsInSource))
+                    if (!sourceSymbol.Locations.Any() || !sourceSymbol.Locations.All(loc => loc.IsInSource))
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/RenameTracking/RenameTrackingTaggerProvider.TrackingSession.cs]: i find ".IsEmpty" far easier to read than "!.Any()"

File: src/EditorFeatures/Core/Implementation/RenameTracking/RenameTrackingTaggerProvider.TrackingSession.cs [hunk 2]
```diff
@@ -217,7 +217,7 @@ public void Cancel()
                     return TriggerIdentifierKind.NotRenamable;
                 }
 
-                if (!sourceSymbol.Locations.All(loc => loc.IsInSource))
+                if (!sourceSymbol.Locations.Any() || !sourceSymbol.Locations.All(loc => loc.IsInSource))
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/RenameTracking/RenameTrackingTaggerProvider.TrackingSession.cs]: Same.

**Comment by CyrusNajmabadi** [comment]
👍

File: src/EditorFeatures/Core/Implementation/RenameTracking/RenameTrackingTaggerProvider.TrackingSession.cs (hunk 1 above)
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/RenameTracking/RenameTrackingTaggerProvider.TrackingSession.cs]: The symbol is neither from source nor metadata? @CyrusNajmabadi has convinced me this isn't insane, but I'm wondering if this needs to be doc'ed somewhere.

File: src/EditorFeatures/Core/Implementation/RenameTracking/RenameTrackingTaggerProvider.TrackingSession.cs (hunk 2 above)
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/RenameTracking/RenameTrackingTaggerProvider.TrackingSession.cs]: Should we also jus refactor a proper "IsFromSource" helper because I think we have this pattern in other places too.

File: src/EditorFeatures/Test/RenameTracking/RenameTrackingTaggerProviderTests.cs [hunk 3]
```diff
@@ -1478,5 +1478,72 @@ End Sub
...
+        public T1 Item1;
+    }
+}
+        </Document>
+    </Project>
+</Workspace>";
+            using (var state = await RenameTrackingTestState.CreateFromWorkspaceXmlAsync(workspaceXml, LanguageNames.CSharp))
+            {
+                state.EditorOperations.InsertText("2");
+                await state.AssertNoTag();
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Test/RenameTracking/RenameTrackingTaggerProviderTests.cs]: Shouldn't this have blocked? I'm not understanding what the intended behavior is here.

File: src/EditorFeatures/Core/Implementation/RenameTracking/RenameTrackingTaggerProvider.TrackingSession.cs (hunk 1 above)
Comment (dpoeschl) [inline src/EditorFeatures/Core/Implementation/RenameTracking/RenameTrackingTaggerProvider.TrackingSession.cs]: @jasonmalinowski See https://github.com/dotnet/roslyn/issues/14524

File: src/EditorFeatures/Core/Implementation/RenameTracking/RenameTrackingTaggerProvider.TrackingSession.cs (hunk 2 above)
Comment (dpoeschl) [inline src/EditorFeatures/Core/Implementation/RenameTracking/RenameTrackingTaggerProvider.TrackingSession.cs]: Will do.

**Comment by dpoeschl** [comment]
@jasonmalinowski @CyrusNajmabadi I've added helpers to ISymbolExtensions, and I believe the tests are behaving as expected.

**Comment by dpoeschl** [comment]
Tagging @ManishJayaswal for RC ask mode approval (or is @MattGertz doing them again now?)

File: src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs [hunk 4]
```diff
@@ -168,6 +168,11 @@ public static bool IsArrayType(this ISymbol symbol)
             return symbol?.Kind == SymbolKind.ArrayType;
         }
 
+        public static bool IsTupleType(this ISymbol symbol)
+        {
+            return (symbol as ITypeSymbol)?.IsTupleType ?? false;
```
Comment (Pilchie) [inline src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs]: Nit: I think we've decided that `== true` is more idiomatic than `?? false`

**Comment by Pilchie** [comment]
:+1:

**Comment by dpoeschl** [comment]
Lots of "Error processing xUnit results failures...

**Comment by dpoeschl** [comment]
retest windows_debug_unit32_prtest please
retest windows_debug_unit64_prtest please
retest windows_release_unit32_prtest please
retest windows_release_unit64_prtest please

**Comment by dpoeschl** [comment]
retest windows_debug_unit32_prtest please

**Comment by dpoeschl** [comment]
retest windows_debug_unit64_prtest please

**Comment by dpoeschl** [comment]
retest windows_release_unit32_prtest please

**Comment by dpoeschl** [comment]
retest windows_release_unit64_prtest please

**Comment by ManishJayaswal** [comment]
Approved pending completion of tests

**Comment by dpoeschl** [comment]
retest windows_debug_unit32_prtest please

**Comment by dpoeschl** [comment]
retest windows_debug_unit64_prtest please

**Comment by dpoeschl** [comment]
retest windows_release_unit32_prtest please

**Comment by dpoeschl** [comment]
retest windows_release_unit64_prtest please

File: src/EditorFeatures/Test/RenameTracking/RenameTrackingTaggerProviderTests.cs (hunk 3 above)
Comment (jasonmalinowski) [inline src/EditorFeatures/Test/RenameTracking/RenameTrackingTaggerProviderTests.cs]: Sorry, I meant "should the user have been blocked from renaming this". I didn't realize this was rename _tracking_ instead of core rename. My bad.
