### PR TITLE
Bug Fix #7117: Move Options/Imports/Attributes To Top Of File but after banner text

### LINKED ISSUE #7117: Investigate why we have "option strict on" above the copyright banner in some VB files.
For example: ExtractMethod/ExtractMethodTests.vb
It seems possible that our code action to add "option strict" might be placing the item above the copyright header.

### PR DESCRIPTION
**Pull request by balajikris**
Fixes #7117

This change makes MoveToTopOfFile recognize banner text on top of file
and moves options/attributes/imports to be after banner text, if any.

### CODE REVIEW

**Comment by davkean** [comment]
@balajikris Ignore the prtest/lin/tst/unit32 failure, we're testing our new dynamic pooling images.

@tannergooding Notice that linux test job failed.

**Comment by balajikris** [comment]
tagging @dotnet/roslyn-ide for CR.

File: src/Features/VisualBasic/Portable/CodeFixes/MoveToTopOfFile/MoveToTopOfFileCodeFixProvider.vb [hunk 1]
```diff
@@ -144,9 +144,14 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.CodeFixes.MoveToTopOfFile
             }
         End Function
 
-        Private Function FindLastContiguousStatement(nodes As IEnumerable(Of SyntaxNode)) As Integer
+        Private Function FindLastContiguousStatement(nodes As IEnumerable(Of SyntaxNode), trivia As IEnumerable(Of SyntaxTrivia)) As Integer
             If Not nodes.Any() Then
-                Return 0
+                If Not trivia.Any(Function(t) t.IsKind(SyntaxKind.CommentTrivia)) Then
```
Comment (brettfo) [inline src/Features/VisualBasic/Portable/CodeFixes/MoveToTopOfFile/MoveToTopOfFileCodeFixProvider.vb]: To avoid enumerating the sequence twice (once for `Any()` and once for `Last()`) what about something like:

``` VB
Dim lastTrivia = trivia.LastOrDefault(Function(t) ...)
If lastTrivia Is Nothing Then
    Return 0
Else
    Return lastTrivia.GetLocation()...
End If
```

**Comment by brettfo** [comment]
:shipit:

File: src/Features/VisualBasic/Portable/CodeFixes/MoveToTopOfFile/MoveToTopOfFileCodeFixProvider.vb (hunk 1 above)
Comment (balajikris) [inline src/Features/VisualBasic/Portable/CodeFixes/MoveToTopOfFile/MoveToTopOfFileCodeFixProvider.vb]: right, i wanted to avoid that and duly forgot. good catch.

**Comment by balajikris** [comment]
ping, @dotnet/roslyn-ide : can one more person please take a look?

**Comment by davkean** [comment]
@dotnet/roslyn-ide @DustinCampbell @CyrusNajmabadi @Pilchie @jasonmalinowski Can one of you sign of off on this?

**Comment by DustinCampbell** [comment]
:+1:
