### PR TITLE
Only restore based on assets file changes if the actual content changed

### LINKED ISSUE #80242: Restore loop in file-based programs
Repro: 

```cs
#:package Newtonsoft.Json:13.0.3
```

Expected: A diagnostic is reported for the bad `:` separator (`@` is expected) and restore fails
Actual: No diagnostic is shown in IDE, restore keeps happening in a loop

Found by @davidfowl

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #80242 

What was happening was, a restore would modify the assets file and cause our watcher to get notified, even though the actual content didn't change. The design time build would notice that assets were still missing and kick off another restore, which would fail again, but generate the file watcher event, in a cycle.

The change is to hash the assets file content when we get a change notification for it, and compare it with the hash from the previous notification, to make sure a meaningful content change has occurred, before kicking off a design time build based on it.

With this change we no longer get a restore loop for a package directive like `#:package Newtonsoft.Json:13.0.4`.

### CODE REVIEW

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs [hunk 1]
```diff
@@ -95,6 +101,22 @@ private void ProjectFileChangeContext_FileChanged(object? sender, string filePat
         NeedsReload?.Invoke(this, EventArgs.Empty);
     }
 
+    private void AssetsFileChangeContext_FileChanged(object? sender, string filePath)
+    {
+        // We only want to trigger design time build if the assets file content actually changed from the last time this handler was called.
+        // Sometimes we can get a change event where no content changed (e.g. for a failed restore).
+        // In such cases, proceeding with design-time build can put us in a restore loop (since the design-time build notices that assets are missing).
+        using var assetsFileStream = File.OpenRead(filePath);
+        var sourceText = SourceText.From(assetsFileStream);
```
Comment (RikkiGibson) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs]: Is this the right way to do read the assets file in this context? Is there some other pattern that should be used instead?

**Comment by RikkiGibson** [comment]
@dibarbet @jasonmalinowski for review

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectLoader.cs [hunk 2]
```diff
@@ -362,7 +362,8 @@ private async Task<bool> ReloadProjectAsync(ProjectToLoad projectToLoad, ToastEr
                 _projectSystemHostInfo);
 
             var loadedProject = new LoadedProject(projectSystemProject, projectFactory, _fileChangeWatcher, _targetFrameworkManager);
-            loadedProject.NeedsReload += (_, _) => _projectsToReload.AddWork(projectToLoad with { ReportTelemetry = false });
+            loadedProject.NeedsReload += (_, _) =>
+                _projectsToReload.AddWork(projectToLoad with { ReportTelemetry = false });
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectLoader.cs:366]: Was this accidentally left from some editing you were doing? It's not bad, but given the line before is longer it's a bit strange...

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs (hunk 1 above)
Comment (jasonmalinowski) [reply src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs]: It should be wrapped in an IOUtilities.PerformIO() to deal with the case of this throwing some sort of I/O exception.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs [hunk 3]
```diff
@@ -95,6 +101,22 @@ private void ProjectFileChangeContext_FileChanged(object? sender, string filePat
         NeedsReload?.Invoke(this, EventArgs.Empty);
     }
 
+    private void AssetsFileChangeContext_FileChanged(object? sender, string filePath)
+    {
+        // We only want to trigger design time build if the assets file content actually changed from the last time this handler was called.
+        // Sometimes we can get a change event where no content changed (e.g. for a failed restore).
+        // In such cases, proceeding with design-time build can put us in a restore loop (since the design-time build notices that assets are missing).
+        using var assetsFileStream = File.OpenRead(filePath);
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs]: Consider making this async.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs [hunk 4]
```diff
@@ -95,6 +101,22 @@ private void ProjectFileChangeContext_FileChanged(object? sender, string filePat
...
+        var sourceText = SourceText.From(assetsFileStream);
+        var contentHash = sourceText.GetContentHash();
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs]: You could just use https://github.com/dotnet/roslyn/blob/6a3a568f4849590011f6717f813e93eb2b43e976/src/Workspaces/Core/Portable/Workspace/Solution/Checksum_Factory.cs?plain=1#L71C5-L71C49 and directly pass the stream so we avoid having to realize the full thing. That also returns our existing Checksum object directly which will simplify your code a bit.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectLoader.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectLoader.cs:366]: Without this change it is a pain to put a breakpoint inside the lambda. I meant to mention that, sorry.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs [hunk 5]
```diff
@@ -95,6 +101,22 @@ private void ProjectFileChangeContext_FileChanged(object? sender, string filePat
         NeedsReload?.Invoke(this, EventArgs.Empty);
     }
 
+    private void AssetsFileChangeContext_FileChanged(object? sender, string filePath)
```
Comment (jasonmalinowski) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs:104]: There's a _theoretical_ race here where the file path being passed might be to an assets file that isn't actually being watched anymore. Not sure that matters in any useful way; just deal with the IO exceptions in case it's gone.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs]: Which operation should be made async? I did not see a `File.OpenAsync` or similar method. I did find discussion https://github.com/dotnet/runtime/discussions/63153 though.

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs]: I am going to make an assumption that we don't need to handle a scenario where we are notified the assets file changed, and, the file was actually deleted from disk.

I guess I am also making an assumption that if we got an IOException when reading the file for some other reason, that there isn't a need to start a design time build.

When I use this helper, is there any need to log or anything in the case an IO exception is thrown?

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs (hunk 3 above)
Comment (jasonmalinowski) [reply src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs]: Oh I didn't realize that wasn't a thing. Never mind then.

**Review by jasonmalinowski — APPROVED** [review]
