### PR TITLE
Fix crash where we try previewing a generated document; general cleanup

### LINKED ISSUE #49755: Crash opening Quick Info
**Version Used**: e9fd4dc7

**Steps to Reproduce**:

Not sure

**Expected Behavior**:

No crash

**Actual Behavior**:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at Microsoft.CodeAnalysis.Solution.CheckContainsDocument(Microsoft.CodeAnalysis.DocumentId)
   at Microsoft.CodeAnalysis.Solution.WithDocumentText(Microsoft.CodeAnalysis.DocumentId, Microsoft.CodeAnalysis.Text.SourceText, Microsoft.CodeAnalysis.PreservationMode)
   at Microsoft.CodeAnalysis.Document.WithText(Microsoft.CodeAnalysis.Text.SourceText)
   at Microsoft.CodeAnalysis.Editor.QuickInfo.ContentControlService.CreateDisposableToolTip(Microsoft.CodeAnalysis.Document, Microsoft.VisualStudio.Text.ITextBuffer, Microsoft.VisualStudio.Text.Span, System.Object)
   at Microsoft.VisualStudio.LanguageServices.FindUsages.StreamingFindUsagesPresenter+DocumentSpanEntry.CreateDisposableToolTip(Microsoft.CodeAnalysis.Document, Microsoft.CodeAnalysis.Text.TextSpan)
   at Microsoft.VisualStudio.LanguageServices.FindUsages.StreamingFindUsagesPresenter+DocumentSpanEntry.<TryCreateColumnContent>b__6_0()
   at Microsoft.CodeAnalysis.Editor.QuickInfo.ContentControlService+LazyToolTip.OnToolTipOpening(System.Object, System.Windows.Controls.ToolTipEventArgs)
   at System.Windows.Controls.ToolTipEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Controls.PopupControlService.RaiseToolTipOpeningEvent(Boolean)
   at System.Windows.Controls.PopupControlService+<>c__DisplayClass8_0.<InspectElementForToolTip>b__0(System.Object, System.EventArgs)
   at System.Windows.Threading.DispatcherTimer.FireTick(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

### PR DESCRIPTION
**Pull request by jasonmalinowski**
**COMMIT-AT-A-TIME HIGHLY RECOMMENDED**

The core problem here was when we were trying to create a preview, we were trying to fork the contents of the document with a SourceText that came from the buffer; if the document is a source generated document trying to fork it won't work, and we'd crash.

Upon further inspection this pattern of using PreviewWorkspace this way was widespread; we'd fork a document with new content, and then call PreviewWorkspace.OpenDocument() which would fetch the text back and then open it up. This doesn't really make sense: OpenDocument updates the text as a part of it's action, so the extra document forking is entirely unnecessary if we just pass the container in directly when opening the document. Furthermore some code in AbstractPreviewFactoryService was also removing and adding documents for other reasons I can't explain, but we can delete all of this to clean things up.

After that refactoring, the fix is to simply not open the source generated document, which we do by checking in PreviewWorkspace.OpenDocument for now. We don't support opening source generated documents at this time, but once we do in the core Workspace layer we'll enable that so we get classification support in previews.

Fixes #49755

### CODE REVIEW

File: src/EditorFeatures/Core/Preview/AbstractPreviewFactoryService.cs [hunk 1]
```diff
@@ -69,17 +67,17 @@ internal abstract class AbstractPreviewFactoryService<TDifferenceViewer> : Foreg
             _previewRoleSet = previewRoleSet;
         }
 
-        public SolutionPreviewResult GetSolutionPreviews(Solution oldSolution, Solution newSolution, CancellationToken cancellationToken)
+        public SolutionPreviewResult GetSolutionPreviews(Solution oldSolution, Solution? newSolution, CancellationToken cancellationToken)
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Preview/AbstractPreviewFactoryService.cs:70]: what does it mean to have a solution diff preview when the new solution is null?

Comment (jasonmalinowski) [reply src/EditorFeatures/Core/Preview/AbstractPreviewFactoryService.cs:70]: I have no idea either. It was null checked, so clearly it's allowed.

Comment (jasonmalinowski) [reply src/EditorFeatures/Core/Preview/AbstractPreviewFactoryService.cs:70]: (this was me very much annotating the implied state of the code, but not asking why)

File: src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs [hunk 2]
```diff
@@ -41,24 +40,26 @@ public void CloseWorkspace()
...
-                UpdateBuffer(document, spanSource);
-            }
+            UpdateBuffer(document);
 
             // Picking a different span: no text change; update span anyway.
-            SpanToShow = spanSource.GetSpan();
-            var spanInBuffer = new SnapshotSpan(TextView.TextBuffer.CurrentSnapshot, new Span(SpanToShow.Start, 0));
-            TextView.ViewScroller.EnsureSpanVisible(spanInBuffer, EnsureSpanVisibleOptions.None);
-            Tagger.OnTextBufferChanged();
+            _tagger.Span = spanSource.GetSpan();
```
Comment (davidwengier) [inline src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs:46]: What happens when the TagsChanged event is fired? Does it matter that this now happens before the scroll?

**Review by davidwengier — APPROVED** [review]

File: src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs (hunk 2 above)
Comment (jasonmalinowski) [reply src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs:46]: When we fire tags changed, it means the editor will query back for us where they should be doing the current highlighting. I guess the ordering doesn't actually matter here, since the editor all will query if scrolling happens or something else that requires a relayout of text. I guess this probably still slightly better as otherwise we might be triggering an extra layout when we raise tags changed when we haven't scrolled to where the user wants to see, so it'd just be wasting time.

**Comment by KirillOsenkov** [comment]
FYI @jasonmalinowski @davidwengier @sharwell after some bisecting I'm starting to suspect that this PR has regressed LightBulb Diff Previews in VSMac. The lightbulb menus work, but the preview never shows up.

I'm thinking the problem really is we don't have an equivalent of this for Cocoa:
https://github.com/dotnet/roslyn/pull/41655

There's really a race condition/deadlock in this code:
https://github.com/dotnet/roslyn/blob/724452a2462e7b67ab1a6b538106004f1fa4edae/src/EditorFeatures/Core.Cocoa/Preview/ICocoaDifferenceViewerExtensions.cs#L95

If the buffer diff isn't ready by the time `CalculateSize()` runs, we exit the method, but never set the `_taskCompletion` result, so the continuation awaiting the CalculateSize result never runs, and the preview never shows. I see Sam has fixed this by waiting for the `SnapshotDifferenceChanged` event, which I think will prevent the deadlock.

I haven't confirmed that this PR is the root cause, but the bisect has narrowed it down to VSMac PR 2984 on Dec 21, which essentially bumps Roslyn from `3.9.0-3.20608.12` to `3.9.0-3.20619.14`, and the list of Roslyn changes includes this PR.

FYI @sevoku

**Comment by KirillOsenkov** [comment]
See the internal VSMac issue here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1275431

**Comment by jasonmalinowski** [comment]
Hmm, the refactoring as much as possible tried to keep behavior the same but I can imagine timing might have changed by accident.

**Comment by KirillOsenkov** [comment]
I guess the bug was always there because we’re missing Sam’s fix. Still not sure what made it reproduce. Should we file an issue to try and unify the CalculateSize() logic between Wpf and Cocoa?
