### PR TITLE
Avoid analyzer cancellation after state changes

### LINKED ISSUE #46786: VB test CustomizableTagsForUnnecessaryCode intermittently failing in CI
https://dev.azure.com/dnceng/public/_build/results?buildId=768040&view=results

```
Assert.Equal() Failure\r\nExpected: 2\r\nActual:   1
```

Stack trace
```
   at Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.Squiggles.ErrorSquiggleProducerTests.VB$StateMachine_6_CustomizableTagsForUnnecessaryCode.MoveNext() in /_/src/EditorFeatures/VisualBasicTest/Squiggles/ErrorSquiggleProducerTests.vb:line 127
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #46786

### CODE REVIEW

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilerDiagnosticAnalyzer.CompilationAnalyzer.cs [hunk 1]
```diff
@@ -41,9 +41,9 @@ public void AnalyzeSyntaxTree(SyntaxTreeAnalysisContext context)
             public static void AnalyzeSemanticModel(SemanticModelAnalysisContext context)
             {
                 var declDiagnostics = context.SemanticModel.GetDeclarationDiagnostics(cancellationToken: context.CancellationToken);
-                ReportDiagnostics(declDiagnostics, context.ReportDiagnostic, IsSourceLocation, s_declaration);
-
                 var bodyDiagnostics = context.SemanticModel.GetMethodBodyDiagnostics(cancellationToken: context.CancellationToken);
+
+                ReportDiagnostics(declDiagnostics, context.ReportDiagnostic, IsSourceLocation, s_declaration);
```
Comment (mavasani) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilerDiagnosticAnalyzer.CompilationAnalyzer.cs:46]: This change might address duplicate diagnostics in presence of cancellation, how does it handle missing diagnostics, which seem to be the reason for all failures?

Comment (tmat) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilerDiagnosticAnalyzer.CompilationAnalyzer.cs:46]: This change seems desirable regardless of whether it addresses a test failure or not. We should not report half of diagnostics when cancelled. All or nothing.

---
In reply to: [473253945](https://github.com/dotnet/roslyn/pull/46974#discussion_r473253945) [](ancestors = 473253945)

Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilerDiagnosticAnalyzer.CompilationAnalyzer.cs:46]: Yep, no argument about this being a desirable change.
