### PR TITLE
Extract Base Record Pass 1 

### LINKED ISSUE #62415: 'Extract base class' doesn't work well for records
```csharp
record CC
{
    public void M()
    {
    }
}
```

Invoke lightbulb on `M`:

image

1. Code action should be "extract base type"

2. Unspeakable `<Clone>$` shouldn't be shown
  image

3. Same as 1, but for the window title.
4. Generated type should be record, it's currently class, which produces CS8864 Records may only inherit from object or another record

### PR DESCRIPTION
**Pull request by ryzngard**
Fixes #62415 

This gets the "extract base class" to not fall over for records entirely. It no longer allows the user to select compiler generated methods, and generates the right type. 

Still to do: 

1. Make so invocation on record works `record $$R(string $$S)`. Both `$$` locations don't currently work
2. Support properties declared with syntax `record R(string S)`

### CODE REVIEW

File: src/Features/Core/Portable/ExtractClass/ExtractClassWithDialogCodeAction.cs [hunk 1]
```diff
@@ -68,81 +70,80 @@ internal class ExtractClassWithDialogCodeAction : CodeActionWithOptions
 
         protected override async Task<IEnumerable<CodeActionOperation>> ComputeOperationsAsync(object options, CancellationToken cancellationToken)
         {
-            if (options is ExtractClassOptions extractClassOptions)
+            if (options is not ExtractClassOptions extractClassOptions)
```
Comment (ryzngard) [inline src/Features/Core/Portable/ExtractClass/ExtractClassWithDialogCodeAction.cs:73]: suggest whitespace off here. I moved exit to early, and then dedented the rest

File: src/Features/Core/Portable/ExtractClass/ExtractClassWithDialogCodeAction.cs [hunk 2]
```diff
@@ -68,81 +70,80 @@ internal class ExtractClassWithDialogCodeAction : CodeActionWithOptions
...
-                        cancellationToken).ConfigureAwait(false);
-
-                // Update the original type to have the new base
-                var solutionWithUpdatedOriginalType = await GetSolutionWithBaseAddedAsync(
-                    updatedDocument.Project.Solution,
-                    symbolMapping,
+            // Map the symbols we're removing to annotations
+            // so we can find them easily
+            var codeGenerator = _document.GetRequiredLanguageService<ICodeGenerationService>();
+            var symbolMapping = await AnnotatedSymbolMapping.CreateAsync(
```
Comment (ryzngard) [inline src/Features/Core/Portable/ExtractClass/ExtractClassWithDialogCodeAction.cs:82]: At some point I think we should move off of passing symbols to the UI layer, but that's a larger change and involves breaking external access. Can do as a follow up

File: src/Features/Core/Portable/PullMemberUp/MemberAndDestinationValidator.cs [hunk 3]
```diff
@@ -29,15 +29,19 @@ public static bool IsDestinationValid(Solution solution, INamedTypeSymbol destin
...
+
             // Static, abstract and accessiblity are not checked here but in PullMembersUpOptionsBuilder.cs since there are
             // two refactoring options provided for pull members up,
             // 1. Quick Action (Only allow members that don't cause error)
             // 2. Dialog box (Allow modifers may cause error and will provide fixing)
             return member switch
             {
                 IMethodSymbol methodSymbol => methodSymbol.MethodKind == MethodKind.Ordinary,
-                IFieldSymbol fieldSymbol => !fieldSymbol.IsImplicitlyDeclared,
-                _ => member.IsKind(SymbolKind.Property) || member.IsKind(SymbolKind.Event),
```
Comment (davidwengier) [inline src/Features/Core/Portable/PullMemberUp/MemberAndDestinationValidator.cs:40]: Are there tests for implicitly declared fields? If not, I think it might be best to revert this change, as you'll have to remove the check on line 32 in future, to do record parameters, and it would be easy to forget to put this back.

File: src/EditorFeatures/CSharpTest/ExtractClass/ExtractClassTests.cs [hunk 4]
```diff
@@ -197,6 +197,69 @@ int Method2()
...
+
+            await new Test
+            {
+                TestCode = input,
+                FixedCode = input,
+                LanguageVersion = LanguageVersion.CSharp9,
+                ReferenceAssemblies = ReferenceAssemblies.Net.Net50,
+            }.RunAsync();
+        }
+
```
Comment (davidwengier) [inline src/EditorFeatures/CSharpTest/ExtractClass/ExtractClassTests.cs:262]: Test that we don't offer for `record struct`?

Would also be good to test

```
record R
{
	public string S {get;set;}
}
```
and also
```
record R(string S)
{
	public string S {get;set;} = S;
}
```

**Review by davidwengier — APPROVED** [review]

File: src/Features/Core/Portable/FeaturesResources.resx [hunk 5]
```diff
@@ -3157,4 +3157,8 @@ Zero-width positive lookbehind assertions are typically used at the beginning of
   <data name="Deleting_0_requires_restarting_the_application_because_is_not_supported_by_the_runtime" xml:space="preserve">
     <value>Deleting {0} requires restarting the application because is not supported by the runtime.</value>
   </data>
+  <data name="Extract_base_record" xml:space="preserve">
+    <value>Extract base record...</value>
+    <comment>"record" is a language construct and should be left the same</comment>
```
Comment (Youssef1313) [inline src/Features/Core/Portable/FeaturesResources.resx:3162]: Consider using `{Locked="record"}` similar to this:

https://github.com/dotnet/roslyn/blob/2552d53c0a044cc5301c195cde161739e89dfc28/src/Features/CSharp/Portable/CSharpFeaturesResources.resx#L131

File: src/EditorFeatures/CSharpTest/ExtractClass/ExtractClassTests.cs (hunk 4 above)
Comment (ryzngard) [reply src/EditorFeatures/CSharpTest/ExtractClass/ExtractClassTests.cs:342]: Added tests. The second example will definitely still produce bad code, I'll enable that in my second pass
