### PR TITLE
Avoid deep recursion for nested bound patterns

### LINKED ISSUE #80840: Stack overflow in `ErrorFacts.IsBuildOnlyDiagnostic`
I believe this is a recurrence of #80569. This repros both with the built-in language server in the C# extension and with a locally-built language server (see steps below).

The crash seems to occur when computing semantic classifications for [`ErrorFacts.IsBuildOnlyDiagnostic`](https://github.com/dotnet/roslyn/blob/7f4062e4154c945c3f30950cdee993061b5aab85/src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs#L587). Generally opening this file in the context of a code review (using [vscode-pull-request-github](https://github.com/microsoft/vscode-pull-request-github)) has been how I encounter the issue.

### Local build steps

I used a locally built Release mode version of the language server from commit 4c279b20a0e580cb42c29e440ce596d2cd57171a.

I used the following command to build the language server:  
`dotnet build src\LanguageServer\Microsoft.CodeAnalysis.LanguageServer\ -r win-x64 -c Release`

Then I used the following VS Code setting to use the resulting language server (note that an absolute path is required):  
`"dotnet.server.path": "F:\\src\\roslyn\\artifacts\\bin\\Microsoft.CodeAnalysis.LanguageServer\\Release\\net9.0\\win-x64\\Microsoft.CodeAnalysis.LanguageServer.dll"`

> [!NOTE]
> 
> I **don't repro the problem** when building in **debug mode**. It appears that with the debug language server, semantic classification of `IsBuildOnlyDiagnostic` is proceeding successfully, just slowly. I am unsure what is causing the behavioral difference.

Also note that I am using both the C# v2.94.71 and C# Dev Kit v1.70.3 extensions, in VS Code v1.105.1.

<details>
    <summary>Stack trace</summary>

```
2025-10-21 11:14:25.456 [error] [stderr] Stack overflow.

2025-10-21 11:14:25.457 [error] [stderr] Repeated 2460 times:
--------------------------------

2025-10-21 11:14:25.458 [error] [stderr]    at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder+Tests+SequenceTests.Filter(Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder, Microsoft.CodeAnalysis.CSharp.BoundDagTest, DagState, Microsoft.CodeAnalysis.CSharp.IValueSet, Microsoft.CodeAnalysis.CSharp.IValueSet, Tests ByRef, Tests ByRef, Boolean ByRef)
--------------------------------
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.SplitCases(DagState, Microsoft.CodeAnalysis.CSharp.BoundDagTest, FrozenArrayBuilder`1<StateForCase> ByRef, System.Collections.Immutable.ImmutableDictionary`2<Microsoft.CodeAnalysis.CSharp.BoundDagTemp,Microsoft.CodeAnalysis.CSharp.IValueSet> ByRef, FrozenArrayBuilder`1<StateForCase> ByRef, System.Collections.Immutable.ImmutableDictionary`2<Microsoft.CodeAnalysis.CSharp.BoundDagTemp,Microsoft.CodeAnalysis.CSharp.IValueSet> ByRef, Boolean ByRef)
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.MakeDecisionDag(Microsoft.CodeAnalysis.Collections.TemporaryArray`1<StateForCase> ByRef, System.Collections.Generic.Dictionary`2<DagState,DagState>)
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.MakeBoundDecisionDag(Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.Collections.TemporaryArray`1<StateForCase> ByRef)
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.CreateDecisionDagForSwitchExpression(Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.CSharp.BoundExpression, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.BoundSwitchExpressionArm>)

2025-10-21 11:14:25.458 [error] [stderr]    at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.CheckSwitchExpressionExhaustive(Microsoft.CodeAnalysis.CSharp.Syntax.SwitchExpressionSyntax, Microsoft.CodeAnalysis.CSharp.BoundExpression, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.BoundSwitchExpressionArm>, Microsoft.CodeAnalysis.CSharp.BoundDecisionDag ByRef, Microsoft.CodeAnalysis.CSharp.Symbols.LabelSymbol ByRef, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag)
   at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.BindSwitchExpressionCore(Microsoft.CodeAnalysis.CSharp.Syntax.SwitchExpressionSyntax, Microsoft.CodeAnalysis.CSharp.Binder, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindSwitchExpression(Microsoft.CodeAnalysis.CSharp.Syntax.SwitchExpressionSyntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag, Boolean, Boolean)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindReturn(Microsoft.CodeAnalysis.CSharp.Syntax.ReturnStatementSyntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.Bind(Microsoft.CodeAnalysis.CSharp.Binder, Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode, SymbolInfoOptions, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService+Worker.ClassifyNode(Microsoft.CodeAnalysis.SyntaxNode)
   at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService+Worker.Classify(Microsoft.CodeAnalysis.SemanticModel, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Text.TextSpan>, Microsoft.CodeAnalysis.Collections.SegmentedList`1<Microsoft.CodeAnalysis.Classification.ClassifiedSpan>, System.Func`2<Microsoft.CodeAnalysis.SyntaxNode,System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Classification.Classifiers.ISyntaxClassifier>>, System.Func`2<Microsoft.CodeAnalysis.SyntaxToken,System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Classification.Classifiers.ISyntaxClassifier>>, Microsoft.CodeAnalysis.Classification.ClassificationOptions, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService+<AddSemanticClassificationsAsync>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService+<AddSemanticClassificationsAsync>d__5, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService+<AddSemanticClassificationsAsync>d__5, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService+<AddSemanticClassificationsAsync>d__5, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)

2025-10-21 11:14:25.458 [error] [stderr]    at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at Microsoft.CodeAnalysis.Document+<GetRequiredNullableDisabledSemanticModelAsync>d__26.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Document+<GetRequiredNullableDisabledSemanticModelAsync>d__26, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Document+<GetRequiredNullableDisabledSemanticModelAsync>d__26, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Document+<GetRequiredNullableDisabledSemanticModelAsync>d__26, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at Microsoft.CodeAnalysis.Document+<GetSemanticModelAsync>d__25.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Document+<GetSemanticModelAsync>d__25, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Document+<GetSemanticModelAsync>d__25, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Document+<GetSemanticModelAsync>d__25, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at Microsoft.CodeAnalysis.Document+<GetSemanticModelHelperAsync>d__28.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Document+<GetSemanticModelHelperAsync>d__28, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Document+<GetSemanticModelHelperAsync>d__28, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Document+<GetSemanticModelHelperAsync>d__28, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
2025-10-21 11:14:25.458 [error] [stderr] 
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at Microsoft.CodeAnalysis.Document+<>c__DisplayClass28_0+<<GetSemanticModelHelperAsync>g__GetSemanticModelWorkerAsync|0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Document+<>c__DisplayClass28_0+<<GetSemanticModelHelperAsync>g__GetSemanticModelWorkerAsync|0>d, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Document+<>c__DisplayClass28_0+<<GetSemanticModelHelperAsync>g__GetSemanticModelWorkerAsync|0>d, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Document+<>c__DisplayClass28_0+<<GetSemanticModelHelperAsync>g__GetSemanticModelWorkerAsync|0>d, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at Microsoft.CodeAnalysis.Shared.Extensions.ProjectExtensions+<GetRequiredCompilationAsync>d__18.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Shared.Extensions.ProjectExtensions+<GetRequiredCompilationAsync>d__18, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Shared.Extensions.ProjectExtensions+<GetRequiredCompilationAsync>d__18, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Shared.Extensions.ProjectExtensions+<GetRequiredCompilationAsync>d__18, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at Microsoft.CodeAnalysis.SolutionCompilationState+RegularCompilationTracker+<GetCompilationSlowAsync>d__24.MoveNext()

2025-10-21 11:14:25.459 [error] [stderr]    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.SolutionCompilationState+RegularCompilationTracker+<GetCompilationSlowAsync>d__24, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext(System.Threading.Thread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at Microsoft.CodeAnalysis.SolutionCompilationState+RegularCompilationTracker+<GetOrBuildFinalStateAsync>d__25.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.SolutionCompilationState+RegularCompilationTracker+<GetOrBuildFinalStateAsync>d__25, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext(System.Threading.Thread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at Microsoft.CodeAnalysis.SolutionCompilationState+RegularCompilationTracker+<>c__DisplayClass25_0+<<GetOrBuildFinalStateAsync>g__BuildFinalStateAsync|0>d.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.SolutionCompilationState+RegularCompilationTracker+<>c__DisplayClass25_0+<<GetOrBuildFinalStateAsync>g__BuildFinalStateAsync|0>d, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext(System.Threading.Thread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetExistingTaskResult(System.Threading.Tasks.Task`1<System.__Canon>, System.__Canon)
   at Microsoft.CodeAnalysis.SolutionCompilationState+RegularCompilationTracker+<>c__DisplayClass25_0+<<GetOrBuildFinalStateAsync>g__CollapseInProgressStateAsync|2>d.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.SolutionCompilationState+RegularCompilationTracker+<>c__DisplayClass25_0+<<GetOrBuildFinalStateAsync>g__CollapseInProgressStateAsync|2>d, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext(System.Threading.Thread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at Microsoft.CodeAnalysis.SolutionCompilationState+RegularCompilationTracker+<>c__DisplayClass25_0+<<GetOrBuildFinalStateAsync>g__ApplyFirstTransformationAsync|6>d.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)

2025-10-21 11:14:25.459 [error] [stderr]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.ValueTuple`3[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.SolutionCompilationState+RegularCompilationTracker+CompilationTrackerGeneratorInfo, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.SolutionCompilationState+RegularCompilationTracker+<>c__DisplayClass25_0+<<GetOrBuildFinalStateAsync>g__ApplyFirstTransformationAsync|6>d, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext(System.Threading.Thread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at Microsoft.CodeAnalysis.SolutionCompilationState+TranslationAction+AddDocumentsAction+<TransformCompilationAsync>d__3.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.SolutionCompilationState+TranslationAction+AddDocumentsAction+<TransformCompilationAsync>d__3, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext(System.Threading.Thread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at Microsoft.CodeAnalysis.Threading.ProducerConsumer`1+<RunParallelAsync>d__10`2[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Threading.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Collections.Immutable.ImmutableArray`1[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Collections.Immutable, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[Microsoft.CodeAnalysis.Threading.ProducerConsumer`1+<RunParallelAsync>d__10`2[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Threading.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext(System.Threading.Thread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)

2025-10-21 11:14:25.459 [error] [stderr]    at Microsoft.CodeAnalysis.Threading.ProducerConsumer`1+<RunChannelAsync>d__14`2[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.ValueTuple`4[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.ValueTuple`3[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Threading.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Immutable.ImmutableArray`1[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Collections.Immutable, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Collections.Immutable.ImmutableArray`1[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Collections.Immutable, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[Microsoft.CodeAnalysis.Threading.ProducerConsumer`1+<RunChannelAsync>d__14`2[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.ValueTuple`4[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.ValueTuple`3[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Threading.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Immutable.ImmutableArray`1[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Collections.Immutable, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]], Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext(System.Threading.Thread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task+WhenAllPromise.Invoke(System.Threading.Tasks.Task)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)

2025-10-21 11:14:25.459 [error] [stderr]    at Microsoft.CodeAnalysis.Threading.ProducerConsumer`1+<>c__DisplayClass14_0`2+<<RunChannelAsync>g__ReadFromChannelAndConsumeItemsAsync|1>d[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.ValueTuple`4[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.ValueTuple`3[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Threading.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Immutable.ImmutableArray`1[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Collections.Immutable, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Collections.Immutable.ImmutableArray`1[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Collections.Immutable, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[Microsoft.CodeAnalysis.Threading.ProducerConsumer`1+<>c__DisplayClass14_0`2+<<RunChannelAsync>g__ReadFromChannelAndConsumeItemsAsync|1>d[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.ValueTuple`4[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.ValueTuple`3[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Threading.VoidResult, Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Immutable.ImmutableArray`1[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Collections.Immutable, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]], Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext(System.Threading.Thread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Collections.Immutable.ImmutableArray`1[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Collections.Immutable, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].SetExistingTaskResult(System.Threading.Tasks.Task`1<System.Collections.Immutable.ImmutableArray`1<System.ValueTuple`2<System.__Canon,System.__Canon>>>, System.Collections.Immutable.ImmutableArray`1<System.ValueTuple`2<System.__Canon,System.__Canon>>)
   at Microsoft.CodeAnalysis.IAsyncEnumerableExtensions+<ToImmutableArrayAsync>d__0`1[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)

2025-10-21 11:14:25.460 [error] [stderr]    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Collections.Immutable.ImmutableArray`1[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Collections.Immutable, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[Microsoft.CodeAnalysis.IAsyncEnumerableExtensions+<ToImmutableArrayAsync>d__0`1[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.CodeAnalysis.Workspaces, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext(System.Threading.Thread)
   at System.Threading.Channels.ChannelReader`1+<ReadAllAsync>d__12[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
```
</details>

### PR DESCRIPTION
**Pull request by AlekseyTs**
Closes #80840.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

**Comment by RikkiGibson** [comment]
I will try to repro the stack overflow again with this PR and will review it soon. Thanks #Resolved

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

File: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs [hunk 1]
```diff
@@ -2335,43 +2380,334 @@ public sealed override void Filter(
...
+                            {
+                                if (easyOut.GetValueOrDefault())
+                                {
+                                    continue;
+                                }
+
+                                return false;
+                            }
+
+                            Debug.Assert(t2 is SequenceTests);
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs]: Nit: it's not obvious at first read that `equalsEasyOut` will validate that `RemainingTests` are equal in length. Think we can strengthen this assert and make it easier to understand by asserting that the remaining tests lengths are equal here. #Resolved

File: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs [hunk 2]
```diff
@@ -2335,43 +2380,334 @@ public sealed override void Filter(
...
+                        }
+
+                        if (obj is not SequenceTests other || sequence.GetType() != other.GetType() || sequence.RemainingTests.Length != other.RemainingTests.Length)
+                        {
+                            return false;
+                        }
+
+                        if (!sequence.RemainingTests.Any(t => t is SequenceTests))
+                        {
+                            return sequence.RemainingTests.SequenceEqual(other.RemainingTests);
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs:2625]: Is there any chance that there will be nested sequences in an individual remaining test? And if so, is that something we want to handle? If the answer to either question is no, consider leaving a comment to explain. #Resolved

File: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs [hunk 3]
```diff
@@ -2335,43 +2380,334 @@ public sealed override void Filter(
...
+                        }
+                    }
+                    while (tests.Count != 0);
+
+                    tests.Free();
                     return value;
+
+                    static int? getHashCodeEasyOut(SequenceTests sequence)
+                    {
+                        if (sequence.RemainingTests.Any(t => t is SequenceTests))
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs:2674]: Same question about nested sequences. #Resolved

File: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs [hunk 4]
```diff
@@ -221,48 +221,93 @@ private static Tests SimplifyTestsAndBindings(
...
+            if (!testsSimplified.IsEmpty || !testsToAssemble.IsEmpty)
+            {
+                throw ExceptionUtilities.Unreachable();
+            }
+
+            testsToSimplify.Free();
+            testsToAssemble.Free();
+            testsSimplified.Free();
+
+            return result;
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs:311]: Do we still need to free `usedValues` here? #Resolved

File: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs [hunk 5]
```diff
@@ -221,48 +221,93 @@ private static Tests SimplifyTestsAndBindings(
...
+                                var newSequence = ArrayBuilder<Tests>.GetInstance(length);
+                                for (int i = 0; i < length; i++)
+                                {
+                                    newSequence.Add(testsSimplified.Pop());
+                                }
+
+                                testsSimplified.Push(seq.Update(newSequence));
+                                break;
+
+                            case Tests.Not n:
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs]: nit: `n` could be deleted here. #Resolved

File: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs:2625]: I am not sure what is there to explain. This operation is equivalent to what the "non-easy" comparison would do.

File: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs (hunk 3 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs:2674]: Same answer. I am not making any assumptions about nested sequences.

File: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs (hunk 2 above)
Comment (333fred) [reply src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs:2625]: If the recursion was sequence->nonsequence->sequence..., then we'd still have deep recursion here. That's what I'm concerned about.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs:2625]: This PR doesn't attempt to avoid that form of recursion, even if one is possible.

File: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs [hunk 6]
```diff
@@ -2335,43 +2380,334 @@ public sealed override void Filter(
...
+                    testsToFilter.Free();
+                    testsToAssemble.Free();
+                    trueTests.Free();
+                    falseTests.Free();
+
+                    static void assemble(SequenceTests toAssemble, ArrayBuilder<Tests> tests)
+                    {
+                        var length = toAssemble.RemainingTests.Length;
+                        var newSequence = ArrayBuilder<Tests>.GetInstance(length, null!);
+                        for (int i = 1; i <= length; i++)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs]: nit: I would find this a little easier to follow, if a similar loop header as earlier in the containing method were used. i.e. `for (int i = toAssembly.RemainingTests.Length - 1; i >= 0; i--) newSequence[i] = ...`. This would help make it clear at a glance that similar traversal order is being used in both places. Unless there is actually a difference between the two that I missed. #Resolved

**Review by RikkiGibson — APPROVED** [review]
LGTM modulo the pending comments. It looks like the stack overflow from #80840 does not repro with this change.
