### PR TITLE
Harden DiagnosticResultSerializer diagnostic reader part

### LINKED ISSUE #46544: System.Exception: Unexpected value 'Float8' of type 'Roslyn.Utilities.ObjectWriter+EncodingKind' crashed Visual Studio
https://dev.azure.com/dnceng/public/_build/results?buildId=753622&view=artifacts&type=publishedArtifacts

```
Message: System.Exception: Unexpected value 'Float8' of type 'Roslyn.Utilities.ObjectWriter+EncodingKind'
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.WatsonReporter.ReportFatal(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.WatsonTraceListener.Exit(System.String)
   at Microsoft.CodeAnalysis.ErrorReporting.WatsonTraceListener.Fail(System.String, System.String)
   at System.Diagnostics.TraceListener.Fail(System.String)
   at System.Diagnostics.TraceInternal.Fail(System.String)
   at System.Diagnostics.Debug.Assert(Boolean, System.String)
   at Roslyn.Utilities.ExceptionUtilities.UnexpectedValue(System.Object)
   at Roslyn.Utilities.ObjectReader.ReadStringValue(EncodingKind)
   at Roslyn.Utilities.ObjectReader.ReadStringValue()
   at Roslyn.Utilities.ObjectReader.ReadString()
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticResultSerializer.ReadDiagnosticAnalysisResults(Roslyn.Utilities.ObjectReader, System.Collections.Generic.IDictionary`2<System.String,Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer>, Microsoft.CodeAnalysis.Diagnostics.DocumentAnalysisScope, Microsoft.CodeAnalysis.Project, Microsoft.CodeAnalysis.VersionStamp, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.InProcOrRemoteHostAnalyzerRunner+<ReadCompilerAnalysisResultAsync>d__12.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResultMap`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResult, Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].Start[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon ByRef)
   at Microsoft.CodeAnalysis.Diagnostics.InProcOrRemoteHostAnalyzerRunner.ReadCompilerAnalysisResultAsync(System.IO.Stream, System.Collections.Generic.Dictionary`2<System.String,Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer>, Microsoft.CodeAnalysis.Diagnostics.DocumentAnalysisScope, Microsoft.CodeAnalysis.Project, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.InProcOrRemoteHostAnalyzerRunner+<>c__DisplayClass11_0.<AnalyzeOutOfProcAsync>b__1(System.IO.Stream, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Remote.RemoteEndPoint+<InvokeAsync>d__22`1[[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResultMap`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResult, Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]], Microsoft.CodeAnalysis.Workspaces, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Threading.Tasks.TaskFactory`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].FromAsyncCoreLogic(System.IAsyncResult, System.Func`2<System.IAsyncResult,System.Threading.Tasks.VoidTaskResult>, System.Action`1<System.IAsyncResult>, System.Threading.Tasks.Task`1<System.Threading.Tasks.VoidTaskResult>, Boolean)
   at System.Threading.Tasks.TaskFactory`1+<>c__DisplayClass35_0[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<FromAsyncImpl>b__0(System.IAsyncResult)
   at System.IO.Pipes.NamedPipeServerStream.AsyncWaitForConnectionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)
```

### PR DESCRIPTION
**Pull request by mavasani**
**Strongly recommended to review with whitespace diffs disabled: https://github.com/dotnet/roslyn/pull/46597/files?diff=unified&w=1**

Closes #46544

Current implementation of read logic in DiagnosticResultSerializer was partially graceful - handled version mismatches + exceptions from deserializing individual document diagnostics. However, it attempted to continue deserializing data after any such mismatch/exception, and none of this code was guarded against further exceptions. This PR does the following changes:

1. Completely harden the deserializing logic against any exceptions or version mismatches. We now log NFW for exceptions and prevent VS crash.
2. Do not attempt to continue deserializing data when there is a failure to read any specific part of the serialized data. We immediately bail out from deserializing and return empty diagnostic result. This prevents cascaded exceptions/NFWs.

### CODE REVIEW

File: src/Features/Core/Portable/Diagnostics/DiagnosticResultSerializer.cs [hunk 1]
```diff
@@ -14,6 +14,8 @@
 using Microsoft.CodeAnalysis.Shared.Extensions;
 using Microsoft.CodeAnalysis.Workspaces.Diagnostics;
 using Roslyn.Utilities;
+using System.Diagnostics.CodeAnalysis;
+using Microsoft.CodeAnalysis.ErrorReporting;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Diagnostics/DiagnosticResultSerializer.cs:18]: sorting

File: src/Features/Core/Portable/Diagnostics/DiagnosticResultSerializer.cs [hunk 2]
```diff
@@ -68,82 +70,103 @@ internal static class DiagnosticResultSerializer
...
                     {
-                        Debug.Assert(documentAnalysisScope.Kind == AnalysisKind.Semantic);
-                        semanticLocalMap = ReadDiagnosticDataMap(reader, diagnosticDataSerializer, project, cancellationToken);
-                        syntaxLocalMap = ImmutableDictionary<DocumentId, ImmutableArray<DiagnosticData>>.Empty;
+                        if (!TryReadDiagnosticDataMap(reader, diagnosticDataSerializer, project, cancellationToken, out var syntaxLocalMap) ||
+                            !TryReadDiagnosticDataMap(reader, diagnosticDataSerializer, project, cancellationToken, out var semanticLocalMap) ||
+                            !TryReadDiagnosticDataMap(reader, diagnosticDataSerializer, project, cancellationToken, out var nonLocalMap) ||
+                            !diagnosticDataSerializer.TryReadDiagnosticData(reader, project, document: null, cancellationToken, out var others))
+                        {
+                            return false;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Diagnostics/DiagnosticResultSerializer.cs:136]: when does this happen.  seems bad.

File: src/Workspaces/Core/Portable/Diagnostics/DiagnosticDataSerializer.cs [hunk 3]
```diff
@@ -183,34 +185,42 @@ private static void WriteLocation(ObjectWriter writer, DiagnosticDataLocation? i
...
 
-                return ReadDiagnosticDataArray(reader, project, document, cancellationToken);
+                data = ReadDiagnosticDataArray(reader, project, document, cancellationToken);
+                return true;
             }
-            catch (Exception)
+            catch (Exception ex) when (FatalError.ReportWithoutCrashUnlessCanceled(ex))
             {
-                return default;
+                return false;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Diagnostics/DiagnosticDataSerializer.cs:223]: this worries me in that it seems like we're testing a scenario where we write/read data, and are currently corrupting/crashing.  this feels like it papers over things.

File: src/Features/Core/Portable/Diagnostics/DiagnosticResultSerializer.cs (hunk 2 above)
Comment (mavasani) [reply src/Features/Core/Portable/Diagnostics/DiagnosticResultSerializer.cs:136]: Down the stack there are checks for version mismatches, and also there was an existing try/catch for reading diagnostic data. Those code paths now return false instead of silently skipping reading of expected data.

File: src/Workspaces/Core/Portable/Diagnostics/DiagnosticDataSerializer.cs (hunk 3 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/Diagnostics/DiagnosticDataSerializer.cs:223]: I agree, hence the reason to now log an NFW instead of silently swallowing the exception.

**Comment by mavasani** [comment]
Had an offline discussion with @CyrusNajmabadi.
Just to clarify - this PR likely does not address the underlying corruption of serialized/deserialized diagnostic result. It takes us to a better place from current where we do not crash VS in case of such a corruption, do not attempt to keep deserializing in case we encounter any exception or version mismatch and log an NFW as opposed to silently walking past exceptions during deserializing.

**Comment by mavasani** [comment]
@CyrusNajmabadi any further feedback on this?

**Comment by mavasani** [comment]
Ping @CyrusNajmabadi @dotnet/roslyn-ide

File: src/Features/Core/Portable/Diagnostics/DiagnosticResultSerializer.cs (hunk 2 above)
Comment (tmat) [reply src/Features/Core/Portable/Diagnostics/DiagnosticResultSerializer.cs:136]: What is the try/catch catching? Should that rather keep the exception propagating?

---
In reply to: [466700707](https://github.com/dotnet/roslyn/pull/46597#discussion_r466700707) [](ancestors = 466700707)

Comment (tmat) [reply src/Features/Core/Portable/Diagnostics/DiagnosticResultSerializer.cs:136]: The version mismatch should probably also throw (ExceptionUtilities.UnexpectedValue).

---
In reply to: [468051167](https://github.com/dotnet/roslyn/pull/46597#discussion_r468051167) [](ancestors = 468051167,466700707)

File: src/Workspaces/Core/Portable/Diagnostics/DiagnosticDataSerializer.cs (hunk 3 above)
Comment (tmat) [reply src/Workspaces/Core/Portable/Diagnostics/DiagnosticDataSerializer.cs:223]: I think we should rather let the exception propagate. I don't know why we even check versions here. Seems pointless.

---
In reply to: [466701364](https://github.com/dotnet/roslyn/pull/46597#discussion_r466701364) [](ancestors = 466701364)

File: src/Features/Core/Portable/Diagnostics/DiagnosticResultSerializer.cs (hunk 2 above)
Comment (mavasani) [reply src/Features/Core/Portable/Diagnostics/DiagnosticResultSerializer.cs:136]: So you feel it is better to let the exception go unhandled and crash VS rather then log an NFW? It is not clear to me why the original code was bailing out on bunch of version checks and had a try catch for deserialization, but I still feel the diagnostic deserialization part should not bring down VS, similar to the way any exception inside CompilationWithAnalyzers for exception in analyzer execution does not bring down VS.

Comment (tmat) [reply src/Features/Core/Portable/Diagnostics/DiagnosticResultSerializer.cs:136]: It should not bring down VS. There should be try-catch somewhere higher on the stack. In OOP, this would be already handled on the remoting boundary. In devenv, the diagnostic analyzer runner should have try-catch somewhere.

Comment (mavasani) [reply src/Features/Core/Portable/Diagnostics/DiagnosticResultSerializer.cs:136]: Ah, that makes sense to me. Let me find a better place to add the handler and update the PR.

File: src/Workspaces/Core/Portable/Diagnostics/DiagnosticDataSerializer.cs (hunk 3 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/Diagnostics/DiagnosticDataSerializer.cs:223]: > I don't know why we even check versions here. Seems pointless. I'd change the above code to Contract.ThrowIfFalse and remove try-catch

@tmat `DiagnosticDataSerializer` is used in couple of code paths:
1. Serializing/deserializing diagnostics to/from devenv and OOP processes
2. Serializing/deserializing diagnostics within devenv to/from persistent storage. See the references in file `DiagnosticIncrementalAnalyzer.ProjectState.cs` here: http://sourceroslyn.io/#Microsoft.CodeAnalysis.Workspaces/Diagnostics/DiagnosticDataSerializer.cs,00debdf1025dbd8d,references.

For the second use case, it is very much possible/expected that the serialized versions do not match deserialized versions from persistent storage. So, the checks are valid. However, the current approach of continuing to attempt reading from the stream in presence of these version mismatches seem error-prone. Additionally, given there are multiple clients of DiagnosticDataSerializer, I don't feel comfortable letting the exceptions from core read part to propagate and have each client handle exceptions. My current approach stance is as follows:

1. Deserializing diagnostics from any serialized source is a safe operation with `TryDeserialize` semantics.
2. Each client that wants deserialized diagnostics is explicitly made aware about potential failures from the signature itself `bool TryXXX`, and we don't rely on each of them wrapping the deserialization attempts inside a try/catch

File: src/Features/Core/Portable/Diagnostics/DiagnosticResultSerializer.cs (hunk 2 above)
Comment (mavasani) [reply src/Features/Core/Portable/Diagnostics/DiagnosticResultSerializer.cs:136]: See https://github.com/dotnet/roslyn/pull/46597#discussion_r490296477, I feel much more comfortable making the deserialize API safer with `bool TryDeserializeXXX` approach here.

**Comment by mavasani** [comment]
@tmat @CyrusNajmabadi it seems that some recent changes in Roslyn are now making cancellation during the core read part much more likely at http://sourceroslyn.io/#Microsoft.CodeAnalysis.Workspaces/Diagnostics/DiagnosticDataSerializer.cs,229. We have had https://github.com/dotnet/roslyn/issues/46544 and https://github.com/dotnet/roslyn/issues/47726 filed as dupes of this, and I can repro this very easily when trying out bits from Roslyn master. End user experience is they will stop seeing diagnostics while typing. I am going to merge this PR to unblock this bad regression, and if either of you feel strongly against https://github.com/dotnet/roslyn/pull/46597#discussion_r490296477 and feel exception boundaries need further adjustment, lets file a follow up issue to discuss this.

File: src/Workspaces/Core/Portable/Diagnostics/DiagnosticDataSerializer.cs (hunk 3 above)
Comment (tmat) [reply src/Workspaces/Core/Portable/Diagnostics/DiagnosticDataSerializer.cs:223]: For the scenario [2], where we need to check the version, shouldn't this check be only at the top-level though? That is have just one version for the whole diagnostic blob and then its parts are not versioned. Or is it valuable to be able to read partial data from the storage? 

I'm also wondering if versioning using a number is the best thing to do. If we make sure the next version is always additive and the extra data is ignored by previous reader then we would achieve more resiliency. Then we would only use the version number for truly breaking changes, which should be rare.

Comment (mavasani) [reply src/Workspaces/Core/Portable/Diagnostics/DiagnosticDataSerializer.cs:223]: Thanks @tmat - I filed https://github.com/dotnet/roslyn/issues/47801 for further refactoring work.
