### PR TITLE
Fix SyntaxGenerator for checked operators

### LINKED ISSUE #63410: SyntaxGenerator crashes with 'checked' operators
on `main` branch, adding a test to `SyntaxGeneratorTests.cs`:

```csharp
        [Fact]
        public void Test()
        {
            var comp = CSharpCompilation.Create(null, new[] { SyntaxFactory.ParseSyntaxTree("""
                public class C
                {
                    public static C operator checked ++(C x) => x;
                }
                """) });
            var operatorSymbol = (IMethodSymbol)comp.GetTypeByMetadataName("C").GetMembers(WellKnownMemberNames.CheckedIncrementOperatorName).Single();
            VerifySyntax<OperatorDeclarationSyntax>(Generator.OperatorDeclaration(operatorSymbol), "");
        }
```

crashes with

```
System.ArgumentException : Unknown operator kind.

  Stack Trace: 
    SyntaxGenerator.GetOperatorKind(IMethodSymbol method) line 256
    SyntaxGenerator.OperatorDeclaration(IMethodSymbol method, IEnumerable`1 statements) line 215
    SyntaxGeneratorTests.Test() line 3791
```

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #63410

@CyrusNajmabadi What do you think of the fix?

### CODE REVIEW

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs [hunk 1]
```diff
@@ -251,23 +256,40 @@ public override SyntaxNode OperatorDeclaration(OperatorKind kind, IEnumerable<Sy
...
+        {
+            var operatorKind = CSharp.SyntaxFacts.GetOperatorKind(method.Name);
+            if (operatorKind == SyntaxKind.None)
+            {
+                throw new ArgumentException("Unknown operator kind.");
             }
+
+            isChecked = method.Name.StartsWith("op_Checked");
+            return (int)operatorKind;
         }
```
Comment (Youssef1313) [inline src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs:291]:
```suggestion
```

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs [hunk 2]
```diff
@@ -242,6 +242,11 @@ internal static SyntaxToken GetArgumentModifiers(RefKind refKind)
...
 
         public override SyntaxNode OperatorDeclaration(OperatorKind kind, IEnumerable<SyntaxNode>? parameters = null, SyntaxNode? returnType = null, Accessibility accessibility = Accessibility.NotApplicable, DeclarationModifiers modifiers = default, IEnumerable<SyntaxNode>? statements = null)
+        {
+            return OperatorDeclaration((int)GetTokenKind(kind), isChecked: false, parameters, returnType, accessibility, modifiers, statements);
+        }
+
+        private protected override SyntaxNode OperatorDeclaration(int syntaxKind, bool isChecked, IEnumerable<SyntaxNode>? parameters = null, SyntaxNode? returnType = null, Accessibility accessibility = Accessibility.NotApplicable, DeclarationModifiers modifiers = default, IEnumerable<SyntaxNode>? statements = null)
```
Comment (Youssef1313) [inline src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs:249]: This signature doesn't play nicely with VB.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi This is ready for review.

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs [hunk 3]
```diff
@@ -251,23 +256,39 @@ public override SyntaxNode OperatorDeclaration(OperatorKind kind, IEnumerable<Sy
...
 
+        private protected override int GetOperatorSyntaxKind(IMethodSymbol method, out bool isChecked)
+        {
+            var operatorKind = CSharp.SyntaxFacts.GetOperatorKind(method.Name);
+            if (operatorKind == SyntaxKind.None)
+            {
+                throw new ArgumentException("Unknown operator kind.");
+            }
+
+            isChecked = method.Name.StartsWith("op_Checked");
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs:288]:
```suggestion
            isChecked = CSharp.SyntaxFacts.IsCheckedOperator(method.Name);
```

File: src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs [hunk 4]
```diff
@@ -202,18 +202,39 @@ internal SyntaxNode MethodDeclaration(IMethodSymbol method, string name, IEnumer
...
+            bool isChecked,
+            bool isImplicitConversion,
+            IEnumerable<SyntaxNode>? parameters = null,
+            SyntaxNode? returnType = null,
+            Accessibility accessibility = Accessibility.NotApplicable,
+            DeclarationModifiers modifiers = default,
+            IEnumerable<SyntaxNode>? statements = null)
+        {
+            throw new NotImplementedException();
+        }
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs:216]: what's this guy?

Comment (Youssef1313) [reply src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs:216]: @CyrusNajmabadi A new method that allows me to pass `isChecked`.

File: src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs [hunk 5]
```diff
@@ -223,38 +244,10 @@ public SyntaxNode OperatorDeclaration(IMethodSymbol method, IEnumerable<SyntaxNo
...
-                WellKnownMemberNames.OnesComplementOperatorName => OperatorKind.OnesComplement,
-                WellKnownMemberNames.RightShiftOperatorName => OperatorKind.RightShift,
-                WellKnownMemberNames.UnsignedRightShiftOperatorName => OperatorKind.UnsignedRightShift,
-                WellKnownMemberNames.SubtractionOperatorName => OperatorKind.Subtraction,
-                WellKnownMemberNames.TrueOperatorName => OperatorKind.True,
-                WellKnownMemberNames.UnaryNegationOperatorName => OperatorKind.UnaryNegation,
-                WellKnownMemberNames.UnaryPlusOperatorName => OperatorKind.UnaryPlus,
-                _ => throw new ArgumentException("Unknown operator kind."),
-            };
+        private protected virtual int GetOperatorSyntaxKind(IMethodSymbol method, out bool isChecked)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs:247]: why virtual and not abstract (applies to all methods like this).

Comment (Youssef1313) [reply src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs:247]: @CyrusNajmabadi SyntaxGenerator is public. Adding new abstract members is breaking.

File: src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs (hunk 4 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs:216]: that makes sense. w hy is this virtual though and not abstract?

File: src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs (hunk 5 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs:247]: SyntaxGenerator has internal-abstracts.  It cannot be publicly subclassed :)  you're fine adding a new abstract to it.

File: src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs (hunk 4 above)
Comment (Youssef1313) [reply src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs]: I incorrectly assumed the type is subclass-able when I saw this:

https://github.com/dotnet/roslyn/blob/8f96b1b0c608df74aae94823f21f5878bf0bec23/src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs#L194-L203

Given there are already non-public abstract methods, it's indeed okay to make the new methods abstract.

This is fixed in the last commit now.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi This is ready for another look.

File: src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs [hunk 6]
```diff
@@ -202,18 +202,36 @@ internal SyntaxNode MethodDeclaration(IMethodSymbol method, string name, IEnumer
             throw new NotImplementedException();
         }
 
+        private protected abstract SyntaxNode OperatorDeclaration(
+            int syntaxKind,
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs:206]: i think i'd prefer just passing hte operator name along.  thsi also includes 'checked' so it can subsume the first two parameters.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by jcouv** [comment]
@CyrusNajmabadi Can this be merged?

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Can you take a look please? Thanks!

**Comment by CyrusNajmabadi** [comment]
Thanks @Youssef1313  :)
