### PR TITLE
Suppress analyzer for properties with explicit interface implementation

### LINKED ISSUE #23735: "Use auto properties" code fix produces invalid code for explicitly implemented interface properties
**Version Used**: 
Microsoft Visual Studio Enterprise 2017 Preview
Version 15.6.0 Preview 1.0

**Steps to Reproduce**:

1. Load the following code in the editor:

```cs
namespace RoslynSandbox
{
	public interface IFoo
	{
		object Bar { get; }
	}

	class Foo : IFoo
	{
		public Foo(object bar)
		{
			this.bar = bar;
		}

		readonly object bar;

		object IFoo.Bar
		{
			get { return bar; }
		}
	}
}
```

2. Note that line 15 (`readonly object bar;`) is greyed out.
3. Click on line 15
4. Select the lightbulb
5. Select "Use auto properties"

**Expected Behavior**:

The code fix should either produce workable code, or not be offered.

**Actual Behavior**:

The resulting code is invalid and does not compile:

```cs
namespace RoslynSandbox
{
	public interface IFoo
	{
		object Bar { get; }
	}

	class Foo : IFoo
	{
		public Foo(object bar)
		{
			this.RoslynSandbox.IFoo.Bar = bar;
		}

		object IFoo.Bar { get; }
	}
}
```

### PR DESCRIPTION
**Pull request by MaStr11**
### Customer scenario

"Use auto property" code fix is provided for properties explicit interface implementations. The code fix generated invalid code. This fix suppress the code fixer for those properties.

### Bugs this fixes

Fixes #23735 

### Workarounds, if any

Don't use the code fix.

### Risk

Low.

### Performance impact

The change causes an allocation of an immutable array on each "AnalyzeProperty" run.

### Is this a regression from a previous update?

No.

### Root cause analysis

Case wasn't covered by unit tests.

### How was the bug found?

Customer reported

### Test documentation updated?

No.

### Remark

As discussed in https://github.com/dotnet/roslyn/issues/23735#issuecomment-351719968 there are cases where the analyzer actually could fix explicit implemented properties too, but this would probably do more harm than good. It would only work for read/write properties and every access to the backing field needs to be replaced by a cast to the interface:

```C#
namespace RoslynSandbox
{
    public interface IFoo
    {
        object Bar
        {
            get;
            set;
        }
    }
    internal class Foo : IFoo
    {
        private object bar;

        object IFoo.Bar
        {
            get
            {
                return this.bar;
            }
            set
            {
                this.bar = value;
            }
        }

        private void M()
        {
            this.bar = null;
        }
    }
}
```

```C#
namespace RoslynSandbox
{
    public interface IFoo
    {
        object Bar
        {
            get;
            set;
        }
    }
    internal class Foo : IFoo
    {
        object IFoo.Bar
        {
            get;
            set;
        }

        private void M()
        {
            ((IFoo)this).Bar = null;
        }
    }
}
```

### CODE REVIEW

File: src/Features/Core/Portable/UseAutoProperty/AbstractUseAutoPropertyAnalyzer.cs [hunk 1]
```diff
@@ -113,6 +113,11 @@ protected void AnalyzeProperty(SemanticModelAnalysisContext context, TPropertyDe
                 return;
             }
 
+            if (property.ExplicitInterfaceImplementations.Length != 0)
```
Comment (MaStr11) [inline src/Features/Core/Portable/UseAutoProperty/AbstractUseAutoPropertyAnalyzer.cs]: Should this also test the accessibility as [here](https://github.com/dotnet/roslyn/pull/23395/files#diff-92c94c254879f0d3a29d14a4615442ceR178)?

**Comment by sharwell** [comment]
> The change causes an allocation of an immutable array on each "AnalyzeProperty" run.

This is correct in the worst case, but in reality it's not quite this bad:

* Properties that do not explicitly implement an interface property (the most important case) simply return `ImmutableArray<T>.Empty` without an allocation
* At least in C#, most implementations of `ExplicitInterfaceImplementations` cache the underlying array, allowing it to be returned without an allocation

File: src/EditorFeatures/CSharpTest/Diagnostics/UseAutoProperty/UseAutoPropertyTests.cs [hunk 2]
```diff
@@ -1000,5 +1000,34 @@ int Q
     int Q { get; }
 }", fixAllActionEquivalenceKey: FeaturesResources.Use_auto_property);
         }
+
+        [WorkItem(23735, "https://github.com/dotnet/roslyn/issues/23735")]
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseAutoProperty)]
+        public async Task ExplicitInterfaceImplementation()
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/Diagnostics/UseAutoProperty/UseAutoPropertyTests.cs]: :bulb: It would be good to add a second test demonstrating the behavior for explicit interface properties that have both `get` and `set`.

File: src/EditorFeatures/VisualBasicTest/Diagnostics/UseAutoProperty/UseAutoPropertyTests.vb [hunk 3]
```diff
@@ -553,5 +553,33 @@ end class")
     Public Property [|P|] As Integer
 End Class")
         End Function
+
+        <WorkItem(23735, "https://github.com/dotnet/roslyn/issues/23735")>
+        <Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseAutoProperty)>
+        Public Async Function ExplicitInterfaceImplementation() As Task
+            Await TestMissingInRegularAndScriptAsync("
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/VisualBasicTest/Diagnostics/UseAutoProperty/UseAutoPropertyTests.vb]: Why are we disabling things for VB?  This is only a problem for C# right?

File: src/Features/Core/Portable/UseAutoProperty/AbstractUseAutoPropertyAnalyzer.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/UseAutoProperty/AbstractUseAutoPropertyAnalyzer.cs]: Won't this disable the feature for VB as well as C#?

File: src/EditorFeatures/VisualBasicTest/Diagnostics/UseAutoProperty/UseAutoPropertyTests.vb (hunk 3 above)
Comment (MaStr11) [reply src/EditorFeatures/VisualBasicTest/Diagnostics/UseAutoProperty/UseAutoPropertyTests.vb]: You are right. I changed the PR to suppress the fixer for C# only.

File: src/EditorFeatures/CSharpTest/Diagnostics/UseAutoProperty/UseAutoPropertyTests.cs [hunk 4]
```diff
@@ -1000,5 +1000,64 @@ int Q
     int Q { get; }
 }", fixAllActionEquivalenceKey: FeaturesResources.Use_auto_property);
         }
+
+        [WorkItem(23735, "https://github.com/dotnet/roslyn/issues/23735")]
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseAutoProperty)]
+        public async Task ExplicitInterfaceImplementationGetterOnly()
+        {
+            await TestMissingInRegularAndScriptAsync(@"
+namespace RoslynSandbox
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Diagnostics/UseAutoProperty/UseAutoPropertyTests.cs]: Small nit.  When making test cases, try to make them as small as possible (i'll admit we don't always follow that).  So, remove things like unnecessary namespaces as they're not relevant to the fix.

Note: you don't have to change this.  just something to keep in mind for the future.

**Comment by sharwell** [comment]
@dotnet-bot retest this please

**Comment by sharwell** [comment]
@Pilchie for ask mode

**Comment by Pilchie** [comment]
Approved for 15.6 Preview 4.
