### PR TITLE
Show 'else' within Ifs within Elses

### LINKED ISSUE #719: Else keyword not recommended
Ported from TFS WorkItem: **1097332**

------------------------------

**Repro Steps:**

Reduced repro:

&nbsp;
<FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">

Class</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> </FONT></FONT><FONT color=#2b91af size=1 face="Courier New"><FONT color=#2b91af size=1 face="Courier New"><FONT color=#2b91af size=1 face="Courier New">Module1
</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New">

</FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Shared</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Sub</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> Main(args </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">As</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">String</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New">())

</FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">If</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> args </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Is</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Nothing</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Then
</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New">

</FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Else
</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New">

</FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">If</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> args </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Is</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Nothing</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Then
</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New">

</FONT></FONT><FONT color=#008000 size=1 face="Courier New"><FONT color=#008000 size=1 face="Courier New"><FONT color=#008000 size=1 face="Courier New">' Expect "Else" to be in completion list here
</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New">

</FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">End</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">If
</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New">

</FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">End</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">If
</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New">

</FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">End</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Sub

End</FONT></FONT></FONT><FONT size=1 face="Courier New"><FONT size=1 face="Courier New"> </FONT></FONT><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New"><FONT color=#0000ff size=1 face="Courier New">Class
</FONT></FONT></FONT>

&nbsp;

Original repro:

<OL>
<LI>Sync to changeset 1387311</LI>
<LI>Unshelve acasey;Repro1097332</LI>
<LI>Go to line 133 (after "ilOffset = 0) in ExpressionCompilerTestBase.vb</LI></OL>

Expected: "Else" recommended

Actual: "Else" not in completion list

------------------------------

**Revisions:**

1) Created By Andrew Casey (ROSLYN) (12/16/2014 4:13:56 PM)

------------------------------

2) Edited By Kevin Pilch-Bisson (12/17/2014 9:46:47 AM)

Since keyword recommendation is (almost) entirely syntactic, can you see if this repros with just the body of the method?&nbsp; If so, can you include that in the bug?

------------------------------

3) Edited By Kevin Pilch-Bisson (2/19/2015 2:42:13 PM)

Port to GitHub.

------------------------------

### PR DESCRIPTION
**Pull request by rchande**
When recommending "Else" we walk all the way up the tree to determine
if the position is nested inside an Else block. This means we don't
recommend "Else" inside an If block nested within an Else block. When
walking up the tree, we should stop at the If/ElseIf block.

Fixes #719.

### CODE REVIEW

**Comment by rchande** [comment]
Potential reviewers: @brettfo  @balajikris  @dpoeschl  @basoundr  @jasonmalinowski @DustinCampbell @Pilchie

File: src/EditorFeatures/VisualBasicTest/Recommendations/Statements/ElseKeywordRecommenderTests.vb [hunk 1]
```diff
@@ -235,5 +235,36 @@ Select Case x
     Case 1
 </MethodBody>, "Else")
         End Sub
+
+        <Fact>
+        <Trait(Traits.Feature, Traits.Features.KeywordRecommending)>
```
Comment (dpoeschl) [inline src/EditorFeatures/VisualBasicTest/Recommendations/Statements/ElseKeywordRecommenderTests.vb]: <WorkItem(...)>

File: src/Features/VisualBasic/Completion/KeywordRecommenders/Statements/ElseKeywordRecommender.vb [hunk 2]
```diff
@@ -45,5 +45,23 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Completion.KeywordRecommenders.Stat
...
+            Do While parent IsNot Nothing
+                If parent.IsKind(SyntaxKind.MultiLineIfBlock, SyntaxKind.ElseIfBlock) Then
+                    Return True
+                End If
+
+                If parent.IsKind(SyntaxKind.ElseBlock) Then
+                    Return False
+                End If
+
+                parent = parent.Parent
```
Comment (Pilchie) [inline src/Features/VisualBasic/Completion/KeywordRecommenders/Statements/ElseKeywordRecommender.vb]: Is there a case where we actually have to go up multiple levels, or should this just look at `parent` and then stop?

Comment (dpoeschl) [inline src/Features/VisualBasic/Completion/KeywordRecommenders/Statements/ElseKeywordRecommender.vb]: Will we offer "Else" inside a more nested scope (say, a Do While loop) just because the Do While loop itself is in an If?

File: src/Features/VisualBasic/Completion/KeywordRecommenders/Statements/ElseKeywordRecommender.vb [hunk 3]
```diff
@@ -45,5 +45,23 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Completion.KeywordRecommenders.Stat
 
             Return SpecializedCollections.EmptyEnumerable(Of RecommendedKeyword)()
         End Function
+
+        Private Function IsNotDirectlyInElseBlock(context As VisualBasicSyntaxContext) As Boolean
```
Comment (dpoeschl) [inline src/Features/VisualBasic/Completion/KeywordRecommenders/Statements/ElseKeywordRecommender.vb]: Based on the current implementation, this method name seems wrong ("directness" isn't required)

File: src/Features/VisualBasic/Completion/KeywordRecommenders/Statements/ElseKeywordRecommender.vb (hunk 2 above)
Comment (rchande) [inline src/Features/VisualBasic/Completion/KeywordRecommenders/Statements/ElseKeywordRecommender.vb]: Yeah, we can just look at the parents of the TargetToken.

File: src/Features/VisualBasic/Completion/KeywordRecommenders/Statements/ElseKeywordRecommender.vb [hunk 4]
```diff
@@ -45,5 +44,16 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Completion.KeywordRecommenders.Stat
 
             Return SpecializedCollections.EmptyEnumerable(Of RecommendedKeyword)()
         End Function
+
+        Private Function IsDirectlyInIfOrElseIf(context As VisualBasicSyntaxContext) As Boolean
+            ' Maybe we're after the Then keyword
+            If context.TargetToken.IsKind(SyntaxKind.ThenKeyword) AndAlso
+                context.TargetToken.Parent?.Parent.IsKind(SyntaxKind.MultiLineIfBlock, SyntaxKind.ElseIfBlock) Then
+                Return True
```
Comment (dpoeschl) [inline src/Features/VisualBasic/Completion/KeywordRecommenders/Statements/ElseKeywordRecommender.vb]: If the TargetToken is the ThenKeyword, then can bad things happen if you fall through to the code below? Doesn't look like the code below is set up to deal with the ThenKeyword.

File: src/EditorFeatures/VisualBasicTest/Recommendations/Statements/ElseKeywordRecommenderTests.vb [hunk 5]
```diff
@@ -235,5 +235,50 @@ Select Case x
...
+</MethodBody>, "Else")
+        End Sub
+
+        <Fact>
+<Trait(Traits.Feature, Traits.Features.KeywordRecommending)>
+        Public Sub ElseNotWithinDo()
+            VerifyRecommendationsMissing(
+<MethodBody>
+If True Then
+Do While True
```
Comment (dpoeschl) [inline src/EditorFeatures/VisualBasicTest/Recommendations/Statements/ElseKeywordRecommenderTests.vb]: Doesn't actually matter, but can you indent the Do While loop so it's clear nothing weird is going on?
