### PR TITLE
Use a simple temp instead of InlineArray1

### LINKED ISSUE #72566: Collection expression IL could be simplified for single span element
**Version Used**: 
https://github.com/dotnet/roslyn/commit/d8d7886808a68c720a246b09028f870bc62c30fe

**Steps to Reproduce**:
```C#
using System;
using System.Runtime.CompilerServices;
public class C
{
    public void M1(int i) => Use([i]);
    public void M2(int i) => Use(new ReadOnlySpan<int>(in i));
    
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static void Use<T>(ReadOnlySpan<T> span){}
}
```
[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoBAGABAlAOgCUBXGAFyjAFNCBhAezAAcoAbGgJwGVuA3KAGMaAZwDcmBAGZ8SXPUwBvTLjX5ZCACy4AsigAUsCrigBKXAF4AfLgCqomgYDaUALpnJGdRvw7dSEaUphY29o4GMDQA7rjENBAAJgDyMOwAnjwsEDAAPMbWQSGequqlas66NBQAFoyJAJKs7AZVtfVNLOzJLFSMMKKEAHKMDWmwsADmZm7luCxcUPwQFDT4KABsfuE0uQAqhfFJqRlZOfu2otkwZkoAvph3QA===)

**Expected Behavior**:
M1 and M2 could produce identical IL.

**Actual Behavior**:
The IL generated is more akin to:
```C#
    public void M1(int i)
    {
        <>y__InlineArray1<int> buffer = default(<>y__InlineArray1<int>);
        <PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray1<int>, int>(ref buffer, 0) = i;
        Use(<PrivateImplementationDetails>.InlineArrayAsReadOnlySpan<<>y__InlineArray1<int>, int>(ref buffer, 1));
    }

    public void M2(int i)
    {
        Use(new ReadOnlySpan<int>(ref i));
    }
```
The JIT is able to produce exactly the same thing for both, but the IL for the former is more complicated and requires the compiler synthesize the `<>y__InlineArray1<T>` type if it wouldn't otherwise be necessary.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Fixes #72566

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 1]
```diff
@@ -439,6 +439,23 @@ private static bool ShouldUseInlineArray(BoundCollectionExpressionBase node, CSh
...
+                    ? WellKnownMember.System_ReadOnlySpan_T__ctor_ref_readonly_T
+                    : WellKnownMember.System_Span_T__ctor_ref_T, isOptional: true) is MethodSymbol spanRefConstructor)
+            {
+                // Special case: no need to create an InlineArray1 type. Just use a temp of the element type.
+                var spanType = _factory
+                    .WellKnownType(asReadOnlySpan ? WellKnownType.System_ReadOnlySpan_T : WellKnownType.System_Span_T)
+                    .Construct([elementType]);
+                var constructor = spanRefConstructor.AsMember(spanType);
+                var element = VisitExpression((BoundExpression)elements[0]);
+                var temp = _factory.StoreToTemp(element, out var assignment);
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:453]: What is the re-use policies on these temps? Basically is there any chance that the temp slot allocated here will be re-used or is it considered a temp that lives for the lifetime of the current method?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:453]: I think the local slot can be reused outside the containing block, but that's fine, since the span value that references the temp can't escape outside the containing block.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 2]
```diff
@@ -439,6 +439,23 @@ private static bool ShouldUseInlineArray(BoundCollectionExpressionBase node, CSh
...
+                    ? WellKnownMember.System_ReadOnlySpan_T__ctor_ref_readonly_T
+                    : WellKnownMember.System_Span_T__ctor_ref_T, isOptional: true) is MethodSymbol spanRefConstructor)
+            {
+                // Special case: no need to create an InlineArray1 type. Just use a temp of the element type.
+                var spanType = _factory
+                    .WellKnownType(asReadOnlySpan ? WellKnownType.System_ReadOnlySpan_T : WellKnownType.System_Span_T)
+                    .Construct([elementType]);
+                var constructor = spanRefConstructor.AsMember(spanType);
+                var element = VisitExpression((BoundExpression)elements[0]);
+                var temp = _factory.StoreToTemp(element, out var assignment, isKnownToReferToTempIfReferenceType: true);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:453]: It's unclear to me if `isKnownToReferToTempIfReferenceType: true` matters here, I tried removing it from the `InlineArray` temp case below and neither CollectionExpressionTests nor ParamsCollectionsTests had any failures.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs]: I added a test. It doesn't look like the temp is reused.

**Comment by cston** [comment]
>                         }

Consider assigning to `y[0]`.

---
Refers to: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:20936 in e9e7d2a. [](commit_id = e9e7d2a87c0948a06fff229b96b288946d306dfa, deletion_comment = False)

**Comment by cston** [comment]
>         public void Span_SingleElement_TempReuse()

Perhaps rename to `MultipleTemps` or something similar so it's clear we're not expecting reuse.

---
Refers to: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:20922 in e9e7d2a. [](commit_id = e9e7d2a87c0948a06fff229b96b288946d306dfa, deletion_comment = False)

**Review by cston — APPROVED** [review]

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler for a second review

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs [hunk 3]
```diff
@@ -20832,6 +20837,267 @@ static void Report<T>(MyCollection<T> c)
...
+                    static void Main() => M(1);
+
+                    static void M(int x)
+                    {
+                        {
+                            Span<int> y = [x];
+                            Console.Write(y[0]);
+                        }
+                        {
+                            Span<int> y = [x];
```
Comment (jjonescz) [inline src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:20938]: Do we have a test where we create single-element collection twice in the same block (not different blocks like in this test)?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs (hunk 1 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs]: Not sure the test is sufficient here. Looking at the code it seems that it's a re-usable temp. The default kind of the temp is `SynthesizedLocalKind.LoweringTemp` and that is not a long lived temp. The doc mentions these cannot live across a statement boundary

```csharp
    /// 1) Short-lived (temporary)
    ///    The lifespan of a temporary variable shall not cross a statement boundary (a PDB sequence point).
    ///    These variables are not tracked by EnC and don't have names. Only values less than 0 are considered
    ///    short-lived: new short-lived kinds should have a negative value.
```

**Comment by cston** [comment]
>             var verifier = CompileAndVerify(source, targetFramework: TargetFramework.Net80, verify: Verification.Skipped, expectedOutput: IncludeExpectedOutput("11"));

Consider compiling with `TestOptions.ReleaseExe` explicitly, so it's more obvious that the code gen (and temporaries) will be optimized.

---
Refers to: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:20945 in e9e7d2a. [](commit_id = e9e7d2a87c0948a06fff229b96b288946d306dfa, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs (hunk 2 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:453]: >isKnownToReferToTempIfReferenceType [](http://example.com/codeflow?start=77&length=35)

1. In general, when not sure, the safest value for this parameter is `false`. It enables some optimizations and you don't want to apply those when they are not appropriate because that can lead to an incorrect result, i.e. bugs.
2. This value is meaningful only for ref locals. I would avoid setting it to true for non-ref locals.
3. The meaning of this flag - this local refers to something (it is a ref), and if the type of that something is a reference type, there is a guarantee that that something is a temporary (not a user local, not a parameter, not a field, etc.) So, it is about what we are referring to with this local. Obviously this temp is a temp, but this value is not about that.

So, I recommend, cleaning up this code and any other "expression collections" code with respect to values used for this parameter. In order to avoid spreading questionable code through copy/paste and eventually hitting a scenario that can actually break because we haven't given much thought about the value.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs]: > What is the re-use policies on these temps?

Slots can be reused for locals that go out of scope. The scope is defined by blocks and sequences that list locals they own. If I remember correctly, sometimes scope of locals is extended by codegen, when, for example, a sequence returns a ref to a local that it owns. One might say the bound tree violates scoping rules in such cases, but for whatever reason a decision was made to handle the case instead of enforcing correctness of the tree.

That said, symbols for temps are never reused by default. One might, of course, intentionally create a bound tree that shares the same temp for different purposes.

I hope that helps with concerns that prompted the original question.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs]: Regarding the short-lived/long-lived story. According to my understanding, these are mostly about PDB/ENC, and the statement boundary the comment is talking about is in terms of syntax (perhaps talking in terms of sequence point boundaries would be more accurate), not about bound statement nodes. Reuse of slots in IL is not based on that. It is based on what I said in the previous message on this thread. So as long as the local is added to the right BoundBlock/BoundSequence, it will not be reused while code for that node is emitted.

There is, however, something interesting going on with where we put inline array locals. The line ```locals.Add(inlineArrayLocal.LocalSymbol);``` below. According to comments on ```_additionalLocals``` field, the local is going to end up on the enclosing method outermost block. Hopefully that is not going to mess with EnC too much because effectively the local crosses a sequence point boundary. "Collection expressions"  devs might want to take a close look at this.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 4]
```diff
@@ -439,6 +439,23 @@ private static bool ShouldUseInlineArray(BoundCollectionExpressionBase node, CSh
...
+                locals.Add(temp.LocalSymbol);
+                var call = _factory.New(constructor, arguments: [temp], argumentRefKinds: [asReadOnlySpan ? RefKind.In : RefKind.Ref]);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:455]: >RefKind.In [](http://example.com/codeflow?start=108&length=10)

```RefKindExtensions.StrictIn```?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs (hunk 1 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs]: Great. Thansk for the explanation!

**Comment by AlekseyTs** [comment]
>             ArrayBuilder<LocalSymbol> locals)

It looks like there is a single call site for this function and that one passe `_additionalLocals` for this parameter. Consider removing the parameter and using  `_additionalLocals` explicitly. That will make it clearer where the locals are going to end up at, in my opinion.

---
Refers to: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:433 in e9e7d2a. [](commit_id = e9e7d2a87c0948a06fff229b96b288946d306dfa, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs (hunk 1 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs]: > There is, however, something interesting going on with where we put inline array locals. ...

Logged https://github.com/dotnet/roslyn/issues/73246 based on this comment and offline discussion.

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs (hunk 3 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:20938]: Indeed this is the type of test that I was most worried about. Re-using the temp between two different blocks is just fine. Re-using it within the same block would be a significant codegen error. Want to make sure that we're not doing that.

File: src/Compilers/CSharp/Test/Emit2/Semantics/ParamsCollectionTests.cs [hunk 5]
```diff
@@ -4558,9 +4558,7 @@ static void Test(params System.Span<int> a)
 
             CompileAndVerify(
                 comp,
-                verify: ExecutionConditionUtil.IsMonoOrCoreClr ?
-                            Verification.FailsILVerify with { ILVerifyMessage = "[InlineArrayAsSpan]: Return type is ByRef, TypedReference, ArgHandle, or ArgIterator. { Offset = 0xc }" }
-                            : Verification.Skipped,
+                verify: Verification.Skipped,
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Emit2/Semantics/ParamsCollectionTests.cs:4561]: Curious now. Lets say I have the following code: 

```csharp
M(1);
M(2);
void M(params Span<int> i) { } 
```

After this change the compiler will optimize the calling code to roughly be: 

```
int tmp = 1;
M(new Span<int>(ref temp));
```

But do we create 1 or 2 temps here? Guessing we only create one today but want to check. This could be a significant optimization opportunity for us in the future.

File: src/Compilers/Core/Portable/WellKnownMembers.cs [hunk 6]
```diff
@@ -3388,6 +3396,14 @@ static WellKnownMembers()
                      (byte)SignatureTypeCode.TypeHandle, (byte)SpecialType.System_Int32,
                      (byte)SignatureTypeCode.TypeHandle, (byte)SpecialType.System_Int32,
 
+                 // System_ReadOnlySpan_T__ctor_ref_readonly_T
+                 (byte)(MemberFlags.Constructor),                                                                                                               // Flags
+                 (byte)WellKnownType.ExtSentinel, (byte)(WellKnownType.System_ReadOnlySpan_T - WellKnownType.ExtSentinel),                                      // DeclaringTypeId
+                 0,                                                                                                                                             // Arity
+                     1,                                                                                                                                         // Method Signature
+                     (byte)SignatureTypeCode.TypeHandle, (byte)SpecialType.System_Void, // Return Type
+                     (byte)SignatureTypeCode.ByReference, (byte)SignatureTypeCode.GenericTypeParameter, 0,
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/WellKnownMembers.cs:3405]: The signature of the ReadOnlySpan<T> consructor changed between net7.0 and net8.0 from in to ref readonly. Will this match both versions?

Comment (RikkiGibson) [reply src/Compilers/Core/Portable/WellKnownMembers.cs:3405]: In practice I expect it will. This is because the comparison here is just checking that it is a managed reference according to the runtime. It doesn't check anything about the readability or writability of the reference (C#-level concepts).

However for the particular way this optimization is implemented, I think won't even enter the path for using the 'Span referencing a temp' optimization, because the containing code path is gated on InlineArray runtime feature availability, IIRC. This is shown in the codegen for the tests which use target framework net7.

Comment (jaredpar) [reply src/Compilers/Core/Portable/WellKnownMembers.cs:3405]: Yep. I'm less interested in the optimization being applied and more interested in making sure that this well known member can see both variations of the signature. Otherwise it could create confusion for later changes.

**Review by cston — APPROVED** [review]

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Test/Emit2/Semantics/ParamsCollectionTests.cs [hunk 7]
```diff
@@ -359,6 +359,77 @@ void assertAttributeData(string name)
             }
         }
 
+        [Fact]
+        public void Span_SingleElement_TempsAreNotReused()
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Emit2/Semantics/ParamsCollectionTests.cs:363]: Did we file a bug to follow up on this? This is a place where future optimizations could very much benefit. 

In this particular case the win is pretty minor. It's just an extra `int` or two on the stack. Consider though when we're passing instead 3 parameters and storing lots of redundant inline array temporaries. That can start to make the stack frame size increase be noticable and may deserve an optimization pass to do proper reuse.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Emit2/Semantics/ParamsCollectionTests.cs:363]: #73269

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler for second review

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 8]
```diff
@@ -429,16 +428,33 @@ private static bool ShouldUseInlineArray(BoundCollectionExpressionBase node, CSh
...
+                    : WellKnownMember.System_Span_T__ctor_ref_T, isOptional: true) is MethodSymbol spanRefConstructor)
+            {
+                // Special case: no need to create an InlineArray1 type. Just use a temp of the element type.
+                var spanType = _factory
+                    .WellKnownType(asReadOnlySpan ? WellKnownType.System_ReadOnlySpan_T : WellKnownType.System_Span_T)
+                    .Construct([elementType]);
+                var constructor = spanRefConstructor.AsMember(spanType);
+                var element = VisitExpression((BoundExpression)elements[0]);
+                var temp = _factory.StoreToTemp(element, out var assignment);
+                _additionalLocals.Add(temp.LocalSymbol);
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:453]: This feels likely to me to have some potentially bad interactions with the work @jjonescz is doing for allowing ref locals in async methods; seems possible that we'll end up trying to lift these locals into closure state. Jan and Rikki, is there any coordination between this and the feature branch that we need to do to avoid issues?

**Review by 333fred — COMMENTED** [review]
I'm concerned by the "method-level" scope of the local change here, particularly when this change meets the feature branch for allowing ref structs in async and iterators.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs (hunk 8 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:453]: > This feels likely to me to have some potentially bad interactions with the work @jjonescz is doing for allowing ref locals in async methods; seems possible that we'll end up trying to lift these locals into closure state.

The local that is added to the method here is not a ref local and is not a ref struct. Therefore, I do not think there will be any issues specifically with lifting that local.

Comment (333fred) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:453]: Thanks for the clarification Aleksey.

**Review by 333fred — APPROVED** [review]
