### PR TITLE
Fix #help output in InteractiveWindow

### LINKED ISSUE #8121: #help in VS interactive is incorrect
A couple of issues - there is a duplicate line:

```
Ctrl-Enter        Within the current submission, evaluate the current submission.
                       Within the current submission, evaluate the current submission.
```

These shouldn't be displayed since they don't work (there might be an option that switches the behavior on and off, so #help needs to use that option):
```
  UpArrow              At the end of the current submission, replace the current submission with a previous submission.
                       Elsewhere, move the cursor up one line.
  DownArrow            At the end of the current submission, replace the current submission with a subsequent submission (after having previously navigated backwards).
                       Elsewhere, move the cursor down one line.
```

### PR DESCRIPTION
**Pull request by genlu**
So the help text generated is based on the value of SmartUpDown option. This fixes #8121.

@dotnet/roslyn-interactive

### CODE REVIEW

File: src/InteractiveWindow/Editor/Commands/InteractiveWindowCommands.cs [hunk 1]
```diff
@@ -263,10 +246,35 @@ public Task<ExecutionResult> TryExecuteCommand()
...
+            list.Add("Alt-DownArrow        " + InteractiveWindowResources.AltDownArrowHelp);
+            list.Add("Ctrl-Alt-UpArrow     " + InteractiveWindowResources.CtrlAltUpArrowHelp);
+            list.Add("Ctrl-Alt-DownArrow   " + InteractiveWindowResources.CtrlAltDownArrowHelp);
+            if (UseSmartUpDown)
+            {
+                list.Add("UpArrow              " + InteractiveWindowResources.UpArrowHelp1);
+                list.Add("                     " + InteractiveWindowResources.UpArrowHelp2);
+                list.Add("DownArrow            " + InteractiveWindowResources.DownArrowHelp1);
+                list.Add("                     " + InteractiveWindowResources.DownArrowHelp2);
+            }
```
Comment (KevinH-MS) [inline src/InteractiveWindow/Editor/Commands/InteractiveWindowCommands.cs]: In the ```!UseSmartUpDown``` case, should we say that these keys "navigate" (or something to that effect)?

File: src/InteractiveWindow/Editor/Commands/InteractiveWindowCommands.cs [hunk 2]
```diff
@@ -349,5 +357,7 @@ public void DisplayCommandHelp(IInteractiveWindowCommand command)
         {
             DisplayCommandUsage(command, _window.OutputWriter, displayDetails: true);
         }
+
+        private bool UseSmartUpDown =>_window.TextView.Options.GetOptionValue(InteractiveWindowOptions.SmartUpDown);
```
Comment (KevinH-MS) [inline src/InteractiveWindow/Editor/Commands/InteractiveWindowCommands.cs]: nitpick:  missing space after ```=>```

File: src/InteractiveWindow/Editor/Commands/InteractiveWindowCommands.cs (hunk 1 above)
Comment (genlu) [inline src/InteractiveWindow/Editor/Commands/InteractiveWindowCommands.cs]: Hmm, I'm not sure. To me, the interactive window is just like any other VS text window, so I simply expect up and down arrows to behave like that unless help text says otherwise.

File: src/InteractiveWindow/Editor/Commands/InteractiveWindowCommands.cs (hunk 2 above)
Comment (genlu) [inline src/InteractiveWindow/Editor/Commands/InteractiveWindowCommands.cs]: Ah, thx :)

File: src/InteractiveWindow/Editor/Commands/InteractiveWindowCommands.cs (hunk 1 above)
Comment (KevinH-MS) [inline src/InteractiveWindow/Editor/Commands/InteractiveWindowCommands.cs]: Yeah, I guess that's fair.

**Comment by KevinH-MS** [comment]
:+1:

File: src/InteractiveWindow/Editor/Commands/InteractiveWindowCommands.cs [hunk 3]
```diff
@@ -166,7 +167,9 @@ public IEnumerable<IInteractiveWindowCommand> GetCommands()
 
         internal IEnumerable<string> Help()
         {
-            string format = "{0,-" + _maxCommandNameLength + "}  {1}";
+            // The magic number `19` here is calculated based on how the description is dispayed for other help entries to keep the texts aligned
+            // (As of now other help entries include REPL commands and script derectives, both have manually formatted help description strings.
+            string format = "{0,-" + Math.Max(19, _maxCommandNameLength) + "}  {1}";
```
Comment (genlu) [inline src/InteractiveWindow/Editor/Commands/InteractiveWindowCommands.cs]: I also fixed the text alignment for REPL commands description, which really bothers me. Please let me know if you think using magic# is evil.

snip_20160203160906

File: src/InteractiveWindow/Editor/Commands/InteractiveWindowCommands.cs [hunk 4]
```diff
@@ -237,40 +239,44 @@ public Task<ExecutionResult> TryExecuteCommand()
...
+                          HelpIndent + "UpArrow              " + InteractiveWindowResources.UpArrowHelp1   + "\r\n" +
+                          HelpIndent + "                     " + InteractiveWindowResources.UpArrowHelp2   + "\r\n" +
+                          HelpIndent + "DownArrow            " + InteractiveWindowResources.DownArrowHelp1 + "\r\n" +
+                          HelpIndent + "                     " + InteractiveWindowResources.DownArrowHelp2 + "\r\n");
+
+        private static readonly string s_shortcutDescriptionsNoSmartUpDown =
+            string.Format(s_shortcutDescriptionsFormat, string.Empty);
+
+
+        internal string ShortcutDescriptions => UseSmartUpDown ? s_shortcutDescriptionsSmartUpDown : s_shortcutDescriptionsNoSmartUpDown;
```
Comment (genlu) [inline src/InteractiveWindow/Editor/Commands/InteractiveWindowCommands.cs]: I just realized the option of UseSmartUpDown can be set/reset at anytime by interactive window, so we have to check everytime `DisplayHelp` is executed.

**Comment by genlu** [comment]
@dotnet-bot retest prtest/mac/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/3295/
// Retest reason: Mono Crashed

**Comment by genlu** [comment]
@dotnet-bot retest prtest/mac/dbg/unit32 please
