### PR TITLE
Small analyzer performance fix for disabled by default rules 

### LINKED ISSUE #64771: Analyzer performance for disabled by default rules
While doing some private testing, I identified that enabling a disabled by default rule for a single file/folder via an editorconfig entry executes the analyzer for the entire project, only for all reported diagnostics outside that file/folder to be dropped immediately. We should only execute the analyzer for the enabled file(s)/folder(s) instead.

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #64771

Disabled by default descriptor with default configured severity should be treated equivalent to suppressed

Verified that the added unit test fails prior to the fix with the analyzer driver making unnecessary callbacks for all files in the compilation.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Emit2/Diagnostics/DiagnosticAnalyzerTests.cs [hunk 1]
```diff
@@ -4009,5 +4009,30 @@ public record A(int X, int Y);";
...
+                new TestSyntaxTreeOptionsProvider(tree1, (AnalyzerWithDisabledRules.Rule.Id, ReportDiagnostic.Warn)));
+            compilation = compilation.WithOptions(options);
+
+            // Verify single analyzer diagnostic reported in the compilation.
+            compilation.VerifyDiagnostics()
+                .VerifyAnalyzerDiagnostics(new DiagnosticAnalyzer[] { analyzer }, null, null,
+                    Diagnostic("ID1", "C1").WithLocation(1, 7));
+
+            // PERF: Verify no analyzer callbacks are made for source files where the analyzer was not enabled.
+            var symbol = Assert.Single(analyzer.CallbackSymbols);
```
Comment (mavasani) [inline src/Compilers/CSharp/Test/Emit2/Diagnostics/DiagnosticAnalyzerTests.cs:4034]: This assert fails without the product change.

**Comment by mavasani** [comment]
@dotnet/roslyn-compiler for second review.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 2)
