### PR TITLE
Fix a crash when a nullable reference type is used in a pattern.

### LINKED ISSUE #45103: Binder crash with nullable reference types
**Version Used**: 

master branch, june 12

**Steps to Reproduce**:

Compile the following code
```c#
public class C {
    public void M(object o) {
        var t = o is string? { };
    }
}
```

**Actual Behavior**:

> System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbolExtensions.GetNullableUnderlyingTypeWithAnnotations(TypeSymbol type) in /_/src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs:line 142
>    at Microsoft.CodeAnalysis.CSharp.Binder.CheckValidPatternType(SyntaxNode typeSyntax, TypeSymbol inputType, TypeSymbol patternType, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs:line 442
>    at Microsoft.CodeAnalysis.CSharp.Binder.BindTypeForPattern(TypeSyntax typeSyntax, TypeSymbol inputType, DiagnosticBag diagnostics, Boolean& hasErrors) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs:line 508
>    at Microsoft.CodeAnalysis.CSharp.Binder.BindRecursivePatternType(TypeSyntax typeSyntax, TypeSymbol inputType, DiagnosticBag diagnostics, Boolean& hasErrors, BoundTypeExpression& boundDeclType) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs:line 603
>    at Microsoft.CodeAnalysis.CSharp.Binder.BindRecursivePattern(RecursivePatternSyntax node, TypeSymbol inputType, UInt32 inputValEscape, Boolean permitDesignations, Boolean hasErrors, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs:line 702
>    at Microsoft.CodeAnalysis.CSharp.Binder.BindPattern(PatternSyntax node, TypeSymbol inputType, UInt32 inputValEscape, Boolean permitDesignations, Boolean hasErrors, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs:line 157
>    at Microsoft.CodeAnalysis.CSharp.Binder.BindIsPatternExpression(IsPatternExpressionSyntax node, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs:line 41
>    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:line 725
>    at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:line 460
>    at Microsoft.CodeAnalysis.CSharp.Binder.BindInferredVariableInitializer(DiagnosticBag diagnostics, ExpressionSyntax initializer, BindValueKind valueKind, RefKind refKind, CSharpSyntaxNode errorSyntax) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 878
>    at Microsoft.CodeAnalysis.CSharp.Binder.BindVariableDeclaration(SourceLocalSymbol localSymbol, LocalDeclarationKind kind, Boolean isVar, VariableDeclaratorSyntax declarator, TypeSyntax typeSyntax, TypeWithAnnotations declTypeOpt, AliasSymbol aliasOpt, DiagnosticBag diagnostics, Boolean includeBoundType, CSharpSyntaxNode associatedSyntaxNode) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 991
>    at Microsoft.CodeAnalysis.CSharp.Binder.BindDeclarationStatementParts(LocalDeclarationStatementSyntax node, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 692
>    at Microsoft.CodeAnalysis.CSharp.Binder.BindLocalDeclarationStatement(LocalDeclarationStatementSyntax node, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 679
>    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 160
>    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 1731
>    at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 1713
>    at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 160
>    at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode declaration, BlockSyntax blockBody, ArrowExpressionClauseSyntax expressionBody, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 3392
>    at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode syntax, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 3289
>    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, DiagnosticBag diagnostics, ImportChain& importChain, Boolean& originalBodyNested, InitialState& forSemanticModel) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 1773
>    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 890
>    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 506
>    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass22_0.<CompileNamedTypeAsync>b__0() in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 402
>    at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in /_/src/Compilers/Core/Portable/InternalUtilities/UICultureUtilities.cs:line 143
>    at System.Threading.Tasks.Task.InnerInvoke()
>    at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.WaitForWorkers() in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 311
>    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean emittingPdb, Boolean emitTestCoverageData, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 203
>    at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForAllMethodBodies(DiagnosticBag diagnostics, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:line 2511
>    at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, DiagnosticBag diagnostics, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:line 2468
>    at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:line 2370
>    at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.GetAllDiagnosticsWithoutStateTrackingAsync(ImmutableArray`1 analyzers, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs:line 448

### PR DESCRIPTION
**Pull request by gafter**
Fixes #45103

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 1]
```diff
@@ -399,12 +399,17 @@ private BoundPattern BindDiscardPattern(DiscardPatternSyntax node, TypeSymbol in
...
-            else if (patternType.IsNullableType() || typeSyntax is NullableTypeSyntax)
+            else if (patternType.IsNullableType())
             {
                 // It is an error to use pattern-matching with a nullable type, because you'll never get null. Use the underlying type.
                 Error(diagnostics, ErrorCode.ERR_PatternNullableType, typeSyntax, patternType, patternType.GetNullableUnderlyingType());
                 return true;
             }
+            else if (typeSyntax is NullableTypeSyntax)
+            {
+                Error(diagnostics, ErrorCode.ERR_PatternNullableType, typeSyntax, patternType.ToDisplayString(CodeAnalysis.NullableFlowState.MaybeNull), patternType);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs:410]: Ideally we should delay converting the `patternType` argument to a string until the diagnostic message is needed. Could we use `typeSyntax` as the diagnostic argument instead of `patternType.ToDisplayString(...)`?

Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs:410]: No, because we are using `ToDisplayString` to tack on a `?`. I suppose I could put the `?` into the diagnostic template?

---
In reply to: [440484936](https://github.com/dotnet/roslyn/pull/45206#discussion_r440484936) [](ancestors = 440484936)

**Comment by gafter** [comment]
@cston I've responded to your comments. I don't know if you still think I should do something about realizing the type as a string in the diagnostic early. I suppose I could put the `?` into the diagnostic template and make sure to use the nullable underlying type the other place that error code is used a few lines earlier. Please advise what you would suggest.

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs (hunk 1 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs:410]: `typeSyntax` is a `NullableTypeSyntax`. Doesn't it include `?`?

**Comment by gafter** [comment]
@cston I added a commit that keeps the diagnostic arguments lazy. Would you please have a look?

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: `typeSyntax` is for the squiggles.

---
In reply to: [440552553](https://github.com/dotnet/roslyn/pull/45206#discussion_r440552553) [](ancestors = 440552553)
