### PR TITLE
Fixes a crash when analysing "omitted ref on COM" errors

### LINKED ISSUE #5728: Crash when attempting to write a lambda that consumes a native COM interface
Dump: \\davkean-i7\Shared\ComCrash\devenv.dmp (note the dump was taken with a slightly different repro, below repro is when I simplified it)

Repro:

1. Press SPACE at $$
``` C#
        
       public static IVsProject ImplementOpenItemWithSpecific(VsHierarchyPropID propId, int hr)
        {
            object result;
            var mock = new Mock<IVsProject4>();
            mock.Setup(h => h.OpenItemWithSpecific(It.IsAny<uint>(),$$)
        }

```

IVsProject4.OpenItemWithSpecific is defined here: https://msdn.microsoft.com/en-us/library/ee197729.aspx.

```
Stack:
IndexOutOfRangeException
   at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.IsComCallWithRefOmitted(MethodSymbol method, ImmutableArray`1 arguments, ImmutableArray`1 argumentRefKindsOpt)
   at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.VisitCall(MethodSymbol method, PropertySymbol propertyAccess, ImmutableArray`1 arguments, ImmutableArray`1 argumentRefKindsOpt, ImmutableArray`1 argumentNamesOpt, Boolean expanded, BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.VisitCall(BoundCall node)
   at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList[T](ImmutableArray`1 list)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitCall(BoundCall node)
   at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.VisitCall(BoundCall node)
   at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitReturnStatement(BoundReturnStatement node)
   at Microsoft.CodeAnalysis.CSharp.BoundReturnStatement.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList[T](ImmutableArray`1 list)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitBlock(BoundBlock node)
   at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.VisitLambda(BoundLambda node)
   at Microsoft.CodeAnalysis.CSharp.BoundLambda.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.VisitConversion(BoundConversion node)
   at Microsoft.CodeAnalysis.CSharp.BoundConversion.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList[T](ImmutableArray`1 list)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitCall(BoundCall node)
   at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.VisitCall(BoundCall node)
   at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitExpressionStatement(BoundExpressionStatement node)
   at Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList[T](ImmutableArray`1 list)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitBlock(BoundBlock node)
   at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.DiagnosticsPass.IssueDiagnostics(CSharpCompilation compilation, BoundNode node, DiagnosticBag diagnostics, MethodSymbol containingSymbol)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.VisitNamedType(NamedTypeSymbol symbol, TypeCompilationState arg)
   at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.Accept[TArgument,TResult](CSharpSymbolVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamespace(NamespaceSymbol symbol)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.VisitNamespace(NamespaceSymbol symbol, TypeCompilationState arg)
   at Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceSymbol.Accept[TArgument,TResult](CSharpSymbolVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamespace(NamespaceSymbol symbol)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.VisitNamespace(NamespaceSymbol symbol, TypeCompilationState arg)
   at Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceSymbol.Accept[TArgument,TResult](CSharpSymbolVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamespace(NamespaceSymbol symbol)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.VisitNamespace(NamespaceSymbol symbol, TypeCompilationState arg)
   at Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceSymbol.Accept[TArgument,TResult](CSharpSymbolVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamespace(NamespaceSymbol symbol)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.VisitNamespace(NamespaceSymbol symbol, TypeCompilationState arg)
   at Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceSymbol.Accept[TArgument,TResult](CSharpSymbolVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamespace(NamespaceSymbol symbol)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean generateDebugInfo, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForMethodBodiesInTree(SyntaxTree tree, Nullable`1 span, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForSyntaxTree(CompilationStage stage, SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Boolean includeEarlierStages, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetMethodBodyDiagnostics(Nullable`1 span, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<<TryGetSyntaxAndSemanticCompilerDiagnostics>b__16_3>d.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<TryGetDocumentDiagnosticsAsync>d__21.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<TryGetSyntaxAndSemanticCompilerDiagnostics>d__16.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<TryGetSyntaxAndSemanticDiagnosticsAsync>d__15.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<TryGetAsync>d__14.MoveNext()
```

### PR DESCRIPTION
**Pull request by VSadov**
In error conditions (common while typing), there is a possibility that are dealing with a broken case and method parameter count does not match argument length and result  in IndexOutOfRange exception.
We should not check for "omitted ref on COM" in such cases.

Fixes #5728

### CODE REVIEW

**Comment by VSadov** [comment]
@dotnet/roslyn-compiler - please review

**Comment by VSadov** [comment]
test this please

**Comment by VSadov** [comment]
test this please

**Comment by VSadov** [comment]
test windows please

**Comment by VSadov** [comment]
test win please

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs [hunk 1]
```diff
@@ -212,7 +212,10 @@ private static bool IsSameLocalOrField(BoundExpression expr1, BoundExpression ex
 
         private static bool IsComCallWithRefOmitted(MethodSymbol method, ImmutableArray<BoundExpression> arguments, ImmutableArray<RefKind> argumentRefKindsOpt)
         {
-            if ((object)method.ContainingType == null || !method.ContainingType.IsComImport) return false;
+            if (method.ParameterCount != arguments.Length ||
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs]: Should we simply check for HasErrors in VisitCall instead? That should take care of all kinds of error conditions we might run into now or in the future.

**Comment by VSadov** [comment]
test this please

**Comment by AlekseyTs** [comment]
LGTM, modulo considering if we could add a more general guard up the stack instead.

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs (hunk 1 above)
Comment (VSadov) [inline src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs]: I thought about that and it seems that in general we want to report all the errors of this sort, so we want to visit the node. We stop early only in cases when node is broken in a way that prevents further analysis (like this case)

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs [hunk 2]
```diff
@@ -212,7 +212,10 @@ private static bool IsSameLocalOrField(BoundExpression expr1, BoundExpression ex
...
+                (object)method.ContainingType == null ||
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs]: Did we actually see ContainingType as null here or is this just an extra precaution?

Comment (VSadov) [inline src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs]: The check existed before the change. Since we get here with error method symbols, I would not be surprised if they do not have containing types.

**Comment by VSadov** [comment]
test this please

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs (hunk 2 above)
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs]: @VSadov is there any where else in the lowering phase where we assume ContainingType is non-null that could be hit by a similar error?

Comment (VSadov) [inline src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs]: This pass happens prior to lowering and can get malformed trees. Lowering will not happen if there are errors, so it would be ok for lowering to make stronger assumptions like every method has containing type.
We, basically, could check if the tree contains errors here and bail, but it is pretty clear from this walker that it intentionally wants to be able to at least try do some work even if we already have errors.

**Comment by VSadov** [comment]
test this please

**Comment by VSadov** [comment]
test this please

**Comment by VSadov** [comment]
test this please

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_Warnings.cs]: I am curious, are any unit-tests going to fail if we go HasErrors check?

**Comment by VSadov** [comment]
test this please

**Comment by VSadov** [comment]
prtest/win/vsi/p1 is ignorable for this PR. It should not even run for this change, possibly picked up by accident when I did "test this please"

**Comment by VSadov** [comment]
test prtest/win/dbg/eta please

**Comment by VSadov** [comment]
test this please

**Comment by VSadov** [comment]
test mac please

**Comment by VSadov** [comment]
test this please
