### PR TITLE
Ensure binder with `BinderFlags.AttributeArgument` is in the local binder chain

### LINKED ISSUE #81576: Fatal VS crash when invoking completion session
**Version Used**:
VS 2026 [11222.16]

**Steps to Reproduce**:
```cs
using System.Collections;
using System.Runtime.CompilerServices;

[CollectionBuilder(typeof(MyFancyCollection), nameof(MyFancyCollection$$))]
public class MyFancyCollection : IEnumerable<int>
{
    public MyFancyCollection Create(ReadOnlySpan<int> ints)
    {
    }

    public IEnumerator<int> GetEnumerator()
    {
        throw new NotImplementedException();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }
}
```
Type `.` at `$$`

**Expected Behavior**:
I see completion list

**Actual Behavior**:
VS hard-crashes in a few secs probably due to stack overflow

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #81576.

A binder with the flag was injected manually as the current binder while binding attributes. Because of that `BinderFlags.AttributeArgument` was not preserved by `GetBinder` API. For example the API is used during binding of `nameof`. Various checks responsible for breaking infinite binding cycles are relying on presence of the flag.

Since after the change the flag is preserved when we are binding `nameof`, I had to add a fixup in several places to properly support `IDS_FeatureInstanceMemberInNameof` feature in context of an attribute. See #67461 that initially added support for the feature.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 1]
```diff
@@ -35,6 +35,12 @@ internal partial class Binder
         /// <returns>True if a reference to "this" is available.</returns>
         internal bool HasThis(bool isExplicit, out bool inStaticContext)
         {
+            if (!isExplicit && IsInsideNameof && Compilation.IsFeatureEnabled(MessageID.IDS_FeatureInstanceMemberInNameof))
```
Comment (jjonescz) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:38]: I didn't follow why `!isExplicit` is needed in this check.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:38]: > I didn't follow why `!isExplicit` is needed in this check.

There are no tests indicating that it must not be present. If you have a scenario in mind, please suggest an example.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:38]: My goal was to use most conservative conditions to fix failing tests.

**Comment by AlekseyTs** [comment]
@jcouv, @dotnet/roslyn-compiler For a second review.

**Review by 333fred — APPROVED** [review]
