### PR TITLE
Do not allow ReadValue to return while a stream is still being read

### LINKED ISSUE #19761: Access violation in RoslynCodeAnalysisService32 reading from memory mapped file
**Version Used**: 15.3 preview 1

**Stack trace**

```
Application: ServiceHub.RoslynCodeAnalysisService32.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory+MemoryMappedInfo+SharedReadableStream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.<ReadValue>b__25_0()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.LongRunningThreadWork(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)
```

### LINKED ISSUE #20170: Dogfooding crash in memory mapped files
**Version Used**: 
VS 2017 Preview 15.3 P 2, + latest Roslyn signed VSIX: 2.3.06181101

**Steps to Reproduce**:

1. Had Roslyn.sln open, rebased my branch to get the latest changes from master (but there weren't any).

**Actual Behavior**:
VS Crash.  

**Dump:**
`"\\mlangfs1\public\kevinpi\TemporaryStorageAccessDenied.dmp"`

**Callstack:**
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory+MemoryMappedInfo+SharedReadableStream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at Roslyn.Utilities.ObjectReader.ReadValueWorker()
   at Roslyn.Utilities.ObjectReader.<ReadValue>b__25_0()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.LongRunningThreadWork(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)
```

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #19761

## Ask Mode

**Customer scenario**

The specific steps to encounter this issue are not completely clear. It appears to involve working in a file which has a deeply nested structure. When the bug arises, Visual Studio may read from a pointer which has been freed, resulting in corruption of internal data structures or an access violation.

**Bugs this fixes:**

Fixes #19761
Fixes #20170

**Workarounds, if any**

None.

**Risk**

The change made here is theoretically capable of producing either a deadlock or a performance regression. Neither of these seems likely from the particular change, and the situations we are avoiding are certainly worse (stack overflow or heap corruption). @CyrusNajmabadi Can you provide an evaluation of the risk for this change?

**Performance impact**

This change disables a cancellation point in the code, which could in some cases cause a regression related to serialization performance. However, this cancellation point was implemented as a recursion guard, not a proper cancellation point, so it's likely we were not relying on its behavior as the latter for performance.

**Is this a regression from a previous update?**

Yes, this bug was introduced in #16798 (specifically 6427a2b5e66913a752889860ca28ddb284be4973) for release 15.1.

**Root cause analysis:**

The code accessing unmanaged memory is extremely performance sensitive, so most checks capable of detecting this concurrency bug early have too much overhead for deployment.

**How was the bug found?**

Internal customer report.

### CODE REVIEW

File: src/Compilers/Core/Portable/Serialization/ObjectReader.cs [hunk 1]
```diff
@@ -138,8 +138,11 @@ public object ReadValue()
                     _cancellationToken,
                     TaskCreationOptions.LongRunning,
                     TaskScheduler.Default);
-                task.Wait(_cancellationToken);
-                value = task.Result;
+
+                // We must not proceed until the additional task completes. After returning from a read, the underlying
+                // stream providing access to raw memory will be closed; if this occurs before the separate thread
+                // completes its read then an access violation can occur attempting to read from unmapped memory.
+                value = task.GetAwaiter().GetResult();
```
Comment (Pilchie) [inline src/Compilers/Core/Portable/Serialization/ObjectReader.cs]: Can we explicitly mention that waiting with cancellation would be a problem if the underlying task doesn't support the cancellation?

Comment (sharwell) [inline src/Compilers/Core/Portable/Serialization/ObjectReader.cs]: :arrow_right: Updated the comment

**Comment by Pilchie** [comment]
Thanks for the comment.

File: src/Compilers/Core/Portable/Serialization/ObjectReader.cs [hunk 2]
```diff
@@ -138,8 +138,15 @@ public object ReadValue()
...
-                value = task.Result;
+
+                // We must not proceed until the additional task completes. After returning from a read, the underlying
+                // stream providing access to raw memory will be closed; if this occurs before the separate thread
+                // completes its read then an access violation can occur attempting to read from unmapped memory.
+                //
+                // CANCELLATION: If cancellation is required, DO NOT attempt to cancel the operation by cancelling this
+                // wait. Cancellation must only be implemented by modifying 'task' to cancel itself in a timely manner
+                // so the wait can complete.
+                value = task.GetAwaiter().GetResult();
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/Serialization/ObjectReader.cs]: This looks ok to me.  Though i would like @stephentoub to weigh in.

Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/Serialization/ObjectReader.cs]: @stephentoub is this the appropriately idiomatic way to say "i would like to wait on this task, and cancel early if it hasn't started running, but block on it until it's IsCompleted becomes true"?

**Comment by CyrusNajmabadi** [comment]
Hrmm... the failure of all tests is concerning though.  What's up with that?

File: src/Compilers/Core/Portable/Serialization/ObjectReader.cs (hunk 2 above)
Comment (stephentoub) [inline src/Compilers/Core/Portable/Serialization/ObjectReader.cs]: This looks right to me, in that it's effectively the same as the else clause below (well, slightly closer would be if the _cancellationToken passed to StartNew were instead changed to be CancellationToken.None, but what you have looks fine).  As it's now written, either the operation will be canceled before it's ever started (due to the token having cancellation requested prior to the StartNew delegate getting invoked, although because it's LongRunning, a new thread is going to be spawned and ReadValueWorker will likely be invoked very quickly as it won't be waiting in any thread pool queues), or any cancellation will be up to the ReadValueWorker implementation itself, which is what you want.  The previous version would have allowed code to continue running even as ReadValueWorker is still executing (since the wait was being canceled rather than ReadValueWorker itself), and thus if what comes after this might attempt to access the same state as ReadValueWorker potentially touches, you end up with race conditions.  Even if ReadValueWorker itself pays attention to / polls for cancellation, there are still potentially races, depending on the implementation.

**Comment by CyrusNajmabadi** [comment]
Also, we have this thread spawning in two other places (in ObjectWriter).  We probably want to have this fix applied there as well, right?

File: src/Compilers/Core/Portable/Serialization/ObjectReader.cs (hunk 2 above)
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/Serialization/ObjectReader.cs]: Thanks stephen.  Sam's code  looks to be exaclty what we want then (i.e. throw exception directly, not an aggregate exception).  Preemptively cancel, but only have it respected on the next potential thread launch.  Thanks!

**Comment by sharwell** [comment]
@dotnet-bot retest this please

**Comment by sharwell** [comment]
@MattGertz this issue fixes a possible access violation (memory corruption) when editing files with deeply nested structures (but not so deep such that they don't exist; both @Pilchie and I have hit this in practice).

**Comment by MattGertz** [comment]
@sharwell Is there any telemetry we can add to help pin down the repro steps, which will help us evaluate if there might be other effects lurking behind this one?

**Comment by Pilchie** [comment]
Just hit this again in my service hub process :-/

**Comment by sharwell** [comment]
@MattGertz We talked about this and we're not quite sure how to reproduce it specifically. We could probably trigger a deterministic failure by wrapping the stream passed to the ObjectReader and forcing it to trigger a cancellation when it starts getting read requests from a different thread than it started on, but it could still be quite a bit of effort. My hope is the "obnoxious comment" provides sufficient deterrent for regressions in the future.

Between @Pilchie and I, we've seen the specific crash a total of 3 times now over the past several weeks.

**Comment by dpoeschl** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by dpoeschl** [comment]
retest windows_release_vs-integration_prtest please
