### PR TITLE
Fixed incorrect codegen when rethrow is used in a regular catch next to ...

### LINKED ISSUE #1334: C#: await in one catch causes following catches cannot re-throw exceptions
I'm using Visual Studio 2015 Preview, I have some code like the following one:

```C#
public async void TestAsync()
{
    try
    {
        throw new ArgumentOutOfRangeException();
        // The type of exception here is not important, just not be an `ArgumentNullException`.
    }
    catch (ArgumentNullException) // Catches some other type here.
    {
        await Task.Delay(500); // Do something async here, it's essential.
    }
    catch (Exception)
    {
        // Maybe do some additional processes here, doesn't affect the result.
        throw; // Just re-throw the exception.
        // throw another exception here works fine.
    }
}
```

Obviously, this method should throw an `ArgumentOutOfRangeException`, **BUT** it will throw a `NullReferenceException` instead, no matter what exception is passed into `catch (Exception)`.

### PR DESCRIPTION
**Pull request by VSadov**
...catches with awaits.

Catches without awaits should not be rewritten in a context of an await catch frame since rethrow in such catch is just a regular rethrow.
Fixes #1334

### CODE REVIEW

**Comment by VSadov** [comment]
@gafter @AlekseyTs , please review this.

**Comment by gafter** [comment]
:+1:

**Comment by AlekseyTs** [comment]
Does VB have the same issue?

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs [hunk 1]
```diff
@@ -1229,6 +1229,75 @@ public static void Main()
...
+
+        try
+        {
+            try
+            {
+                x = x / x;
+            }
+            catch (ArgumentNullException)
+            {
+                x = await F();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs]: Would it be interesting to test what re-throw would do after this statement? Test two or more catch blocs with await and re-throw?

**Comment by VSadov** [comment]
@AlekseyTs - no, VB does not allow awaits in catch blocks.

**Comment by AlekseyTs** [comment]
LGTM, but consider my comment about the unit-test.
