### PR TITLE
Fixes #16984: Accessors not correctly indented

### LINKED ISSUE #16984: Accessors not correctly indented by the formatter
Splitting from #16927

**Version Used**: 2.0.0.61401

**Steps to Reproduce**:

```C#
    public static bool Test
    {
get
        {
            return true;
        }
    }
```
Retype the bracket after `return`.

**Expected Behavior**: The `get` to be correctly indented as is the case for other blocks (e.g. `if`).

**Actual Behavior**: `get` not touched unless the second closing bracket is retyped.

### PR DESCRIPTION
**Pull request by martinzimmermann**
Fixes #16984

Now `get` and `set` behave like `if`.
Unfortunately I had to change the test `AccessorList5` to match the new behavior.
Seeing that `if` also has the same behavior if there are no matching closing brackets, I think this is another issue.

### CODE REVIEW

**Comment by Pilchie** [comment]
Thanks for the PR.  Pinging @dotnet/roslyn-ide for reviewers.

File: src/Workspaces/CSharp/Portable/Utilities/FormattingRangeHelper.cs [hunk 1]
```diff
@@ -360,7 +360,9 @@ private static bool IsSpecialContainingNode(SyntaxNode node)
                 node.Kind() == SyntaxKind.FinallyClause ||
                 node.Kind() == SyntaxKind.LabeledStatement ||
                 node.Kind() == SyntaxKind.LockStatement ||
-                node.Kind() == SyntaxKind.FixedStatement;
+                node.Kind() == SyntaxKind.FixedStatement ||
+                node.Kind() == SyntaxKind.GetAccessorDeclaration ||
+                node.Kind() == SyntaxKind.SetAccessorDeclaration;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Utilities/FormattingRangeHelper.cs]: what about Add/RemoveAccessorDeclaration?

Comment (martinzimmermann) [inline src/Workspaces/CSharp/Portable/Utilities/FormattingRangeHelper.cs]: It would make sense to also include them. I will add them and write some test cases.

**Comment by heejaechang** [comment]
retest windows_release_vs-integration_prtest please

**Comment by heejaechang** [comment]
retset windows_debug_vs-integration_prtest please

**Comment by heejaechang** [comment]
👍

**Comment by heejaechang** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by martinzimmermann** [comment]
retest windows_release_vs-integration_prtest please

**Comment by sharwell** [comment]
@dotnet-bot retest this please

File: src/EditorFeatures/CSharpTest/Formatting/Indentation/SmartTokenFormatterFormatRangeTests.cs [hunk 2]
```diff
@@ -446,12 +446,10 @@ class Class
...
 {
     int Prop {
-        get
-        {
-            return 1;
+        get { return 1;
         }";
 
-            await AutoFormatOnCloseBraceAsync(code, expected, SyntaxKind.GetKeyword);
+            await AutoFormatOnCloseBraceAsync(code, expected, SyntaxKind.OpenBraceToken);
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/Formatting/Indentation/SmartTokenFormatterFormatRangeTests.cs]: ❗️ Do we know why this change occurred? I actually use this sequence of operations relatively frequently to convert a single-line getter into a multi-line getter.

Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Formatting/Indentation/SmartTokenFormatterFormatRangeTests.cs]: I'm with sam.  I don't think this change in behavior is ok.

**Comment by jinujoseph** [comment]
pinging @martinzimmermann  again here

File: src/EditorFeatures/CSharpTest/Formatting/Indentation/SmartTokenFormatterFormatRangeTests.cs (hunk 2 above)
Comment (sharwell) [reply src/EditorFeatures/CSharpTest/Formatting/Indentation/SmartTokenFormatterFormatRangeTests.cs]: ➡️ It turns out that this behavior change is due to the fact that the property declaration does not have a closing brace. In the use case I was primarily worried about, this does not occur. I added a new test showing that the scenario I was worried about has not been altered by this change.

File: src/EditorFeatures/CSharpTest/Formatting/Indentation/SmartTokenFormatterFormatRangeTests.cs [hunk 3]
```diff
@@ -444,14 +444,40 @@ class Class
...
         get
         {
             return 1;
-        }";
+        }
+}
+}";
 
-            await AutoFormatOnCloseBraceAsync(code, expected, SyntaxKind.GetKeyword);
+            await AutoFormatOnCloseBraceAsync(code, expected, SyntaxKind.OpenBraceToken);
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Formatting/Indentation/SmartTokenFormatterFormatRangeTests.cs]: @heejaechang What is this argument for?

File: src/Workspaces/CSharp/Portable/Utilities/FormattingRangeHelper.cs [hunk 4]
```diff
@@ -360,7 +360,11 @@ private static bool IsSpecialContainingNode(SyntaxNode node)
                 node.Kind() == SyntaxKind.FinallyClause ||
                 node.Kind() == SyntaxKind.LabeledStatement ||
                 node.Kind() == SyntaxKind.LockStatement ||
-                node.Kind() == SyntaxKind.FixedStatement;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Utilities/FormattingRangeHelper.cs]: not a problem witht his PR, but i have no idea what "special-containing-node" means.   What does it mean to be "special"?  Why are these nodes "special"? How do i judge if the added nodes are correct to have here, and that we're not missing other nodes that should go here?

@heejaechang can you clarify the intent of this method?

Comment (heejaechang) [reply src/Workspaces/CSharp/Portable/Utilities/FormattingRangeHelper.cs]: it is basically list of nodes that require different behavior than normal one. special cases basically. usually means one larger scope than other cases. but not sure it is still that since it has been years since I last touched this.

looks like IsSpecialContainingNode should only be used in GetTopContainingNode and nothing else.

File: src/EditorFeatures/CSharpTest/Formatting/Indentation/SmartTokenFormatterFormatRangeTests.cs (hunk 3 above)
Comment (heejaechang) [reply src/EditorFeatures/CSharpTest/Formatting/Indentation/SmartTokenFormatterFormatRangeTests.cs]: token tells you what token range start with. this could be use the marker stuff to mark what start token it is looking for rather than give in token kind.

**Comment by sharwell** [comment]
@jinujoseph for approval 😄

**Comment by jinujoseph** [comment]
Approved to merge for 15.8.Preview3

**Comment by sharwell** [comment]
Thank you @martinzimmermann for getting this fixed! 😄  Sorry it took so long to get it merged.

**Comment by martinzimmermann** [comment]
Sorry for not responding, I didn’t get how the notification system on Github worked and just randomly looked into the issue again.
I’m glad it helped 😄
