### PR TITLE
Reuse nullable override checks for delegate conversions

### LINKED ISSUE #44129: Roslyn doesn't check nullability violations in delegate conversions caused by flow annotations
**Version Used**: 
```
commit 27654b066e600a350706a13ebd67d1da542c1a7b
Merge: 436d17816f6 0c9f90368a5
Author: msftbot[bot] <48340428+msftbot[bot]@users.noreply.github.com>
Date:   Thu May 7 05:33:48 2020 +0000

    Merge pull request #44029 from dotnet/merges/release/dev16.7-preview1-to-master

    Merge release/dev16.7-preview1 to master
```

**Steps to Reproduce**:

Compile and run the following code
```cs
using System;
using System.Collections.Generic;
using System.Linq;

#nullable enable
public class D
{
  public static void Main()
  {
    IEnumerable<string> e = new string[0];
    Func<string> f = e.FirstOrDefault;
    f().ToString();
  }
}
```

**Expected Behavior**:
Warning for conversion `Func<string> f = e.FirstOrDefault` because `FirstOrDefault` uses `[return: MaybeNull]` annotation

**Actual Behavior**:
No warnings. The code crashes at runtime with a `NullReferenceException`

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #44129

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 1]
```diff
@@ -54235,6 +54248,197 @@ void M(Action? a)
                 Diagnostic(ErrorCode.WRN_NullReferenceAssignment, "a").WithLocation(10, 20));
         }
 
+        [Fact]
+        [WorkItem(44129, "https://github.com/dotnet/roslyn/issues/44129")]
+        public void DelegateCreation_FromMethodGroup_NullabilityAttributes()
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:54253]: Consider adding some variations of this test taking into account variance. Delegate types with `out` parameters and these attributes, for example. For the same type of scenario, also consider testing usage of `MaybeNullWhen`.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 2]
```diff
@@ -4286,24 +4286,32 @@ public void Verify31958()
             var source = @"
 class C
 {
-    string? M(string s)
+    string? M1(string s)
     {
-        var d = (D)M;
+        var d = (D)M1; // 1
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:4291]: To clarify why these tests changed: the nullable override analysis will refrain from warning about parameters if we have already warned about the return type. Thus to exercise all the same code paths in this test we need to have a method with an incompatible return type and another method with a compatible one.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 3]
```diff
@@ -53375,38 +53383,43 @@ static void Main()
     }
 
     CL0<string?> M1(CL0<string> x) { throw new System.Exception(); }
+    CL0<string> M2(CL0<string> x) { throw new System.Exception(); }
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:53386]: This test changed for the same reason as https://github.com/dotnet/roslyn/pull/46953#discussion_r474304674.

**Comment by RikkiGibson** [comment]
Please review @dotnet/roslyn-compiler

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:54253]: I did not test with 'out' parameters because it turns out they are not covariant in the language, but I added a test for by-value parameters and returns.

I do feel like the variance checks themselves are fairly well exercised by the overload resolution tests--delegates are just an analogous reuse of those checks, so it feels like it might be OK to not cover every last scenario

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler Please review

**Comment by jcouv** [comment]
Wouldn't have thought to re-use the override check logic, but it makes sense. Neat!
