### PR TITLE
Better handle surrounding directives when inlining a local variable.

### LINKED ISSUE #21455: Inline temporary leaves preprocessor directives inconsistent
**Version Used**: 15.3 Preview 7

:link: Originally revealed by `InlineTemporaryTests.Preprocessor2` in #21439.

### Steps to Reproduce

1. Use the following code:

    ```csharp
    namespace ConsoleApp5
    {
        class Program
        {
            static void Main(string[] args)
            {
                int y,
    #if true
                    x = 1,
    #endif
                    z;

                int a = x;
            }
        }
    }
    ```

2. Place the caret before `x` (in `x = 1`)
3. Apply the **Inline temporary variable** refactoring

#### Option 1:

Do not show the **Inline temporary variable** refactoring for this case.

#### Option 2:

```csharp
namespace ConsoleApp5
{
    class Program
    {
        static void Main(string[] args)
        {
            int y,
#if true
#endif
                z;

            int a = 1;
        }
    }
}
```

#### Option 3:

```csharp
namespace ConsoleApp5
{
    class Program
    {
        static void Main(string[] args)
        {
            int y,
                z;

            int a = 1;
        }
    }
}
```

### Actual Behavior

```csharp
namespace ConsoleApp5
{
    class Program
    {
        static void Main(string[] args)
        {
            int y,
#endif
                z;

            int a = 1;
        }
    }
}
```

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
### Customer scenario

The Inline Temporary Variable code fix is applied to code containing preprocessor directives. The operation fails to consider the syntax requirements of the preprocessor directives, and the resulting file is no longer valid code.

### Bugs this fixes

Fixes #21455

### Workarounds, if any

None.

### Risk

Low. Existing test behavior was not altered except where the previous code was obviously incorrect, and new tests were implemented to cover the new behavior.

### Performance impact

Low. There are no key algorithm changes and the approach is consistent with other cases needing similar patterns.

### Is this a regression from a previous update?

No.

### Root cause analysis

Tests were configured to ignore trivia by default (including preprocessor directives), so the validation described in previous unit tests did not match the actual validation occurring. The test suite was corrected in #21439, leaving this bug as a follow-up work item.

### How was the bug found?

Unit tests.

### Test documentation updated?

No.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @dotnet/roslyn-compiler @mattwar 

As part of this change, i've tweaked out SyntaxNode.RemoveNode works when removing a node from a separated list.  Specifically, i've tweaked the heuristic that is used to decide which comma to remove from teh seprated list when removing the node.  Previously, we would always remove the preceding comma if there was one.  If there wasn't one, we'd remove hte following comma.  This was suboptimal for some coding patterns.  For example, if the user has:

```c#
SomeMethod(a, // comment about a
           b, // some comment about b
           c // come comment about c
);
```

Then previously removing 'b' would leave you with:

```c#
SomeMethod(a, // some comment about b
           c // come comment about c
);
```

Now it gives you the expected

```c#
SomeMethod(a, // comment about a
           c // come comment about c
);
```

**Comment by sharwell** [comment]
@CyrusNajmabadi I don't see any difference between your before/after examples in the previous comment.

File: src/EditorFeatures/CSharpTest/CodeActions/InlineTemporary/InlineTemporaryTests.cs [hunk 1]
```diff
@@ -1380,12 +1379,13 @@ static void Main(string[] args)
 @"
 {
         int y,
+#if true
+
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/CodeActions/InlineTemporary/InlineTemporaryTests.cs]: :bulb: This blank line should be removed

**Comment by CyrusNajmabadi** [comment]
@sharwell

> I don't see any difference between your before/after examples in the previous comment.

I've highlighted the relevant part with asterisk here:

```c#
SomeMethod(a, // comment about **b**
           c // come comment about c
);
```

Now it gives you the expected

```c#
SomeMethod(a, // comment about **a**
           c // come comment about c
);
```

File: src/EditorFeatures/CSharpTest/CodeActions/InlineTemporary/InlineTemporaryTests.cs (hunk 1 above)
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/CodeActions/InlineTemporary/InlineTemporaryTests.cs]: I can live with this behavior.  Critical part is not leaving dangling preprocessor directives.

**Comment by sharwell** [comment]
@CyrusNajmabadi Can you verify that the comment preservation works with leading comments too:

```csharp
SomeMethod(/*arg1:*/ a,
    /*arg2:*/ b,
    /*arg3:*/ c);
```

I'd rather leave the extraneous comment on a blank line than have cases where a comment is incorrectly removed. In other works, the following outcome in your original example would be either acceptable or preferred:

```csharp
SomeMethod(a, // comment about a
           // some comment about b
           c // come comment about c
);
```

**Comment by sharwell** [comment]
Also test the following:

```csharp
SomeMethod(// comment about a
           a,
           // some comment about b
           b,
           // come comment about c
           c);
```

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNodeRemover.cs [hunk 2]
```diff
@@ -260,6 +288,19 @@ public override SeparatedSyntaxList<TNode> VisitList<TNode>(SeparatedSyntaxList<
                 return list;
             }
 
+            private bool ContainsEndOfLine(SyntaxTriviaList triviaList)
```
Comment (sharwell) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxNodeRemover.cs]: :bulb: Several other kinds of trivia have a newline built-in. StyleCop Analyzers uses a [`HasBuiltinEndLine`](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/6d80369e41d01fc31732ba1d4dbdf0884f7f4b3d/StyleCop.Analyzers/StyleCop.Analyzers/Helpers/TriviaHelper.cs#L388-L393) helper method for this function.

Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxNodeRemover.cs]: I considered the cases here, but felt they were not suitably interesting or important enough to handle right now.

**Comment by CyrusNajmabadi** [comment]
Sure, will add additional tests.

**Comment by CyrusNajmabadi** [comment]
Added tests.

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-compiler @mattwar  Please review the changes (and tests) to 'RemoveNode'.  Thanks!

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNodeRemover.cs (hunk 2 above)
Comment (cston) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxNodeRemover.cs]: Method can be `static` or perhaps an instance method on `SyntaxTriviaList`. Or alternatively, replace with `triviaList.IndexOf(SyntaxKind.EndOfLineTrivia) >= 0`.

File: src/Compilers/VisualBasic/Portable/Syntax/SyntaxNodeRemover.vb [hunk 3]
```diff
@@ -199,6 +227,16 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Syntax
                 Return list
             End Function
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Syntax/SyntaxNodeRemover.vb]: Can `VisitList` be shared between C# and VB?

Comment (CyrusNajmabadi) [inline src/Compilers/VisualBasic/Portable/Syntax/SyntaxNodeRemover.vb]: Yup.  I think i can move to a shared helper.

Comment (CyrusNajmabadi) [inline src/Compilers/VisualBasic/Portable/Syntax/SyntaxNodeRemover.vb]: Ok.  I looked into this, and we definitely can't share the entire method.  First, it accesses a lot of instance state.  And we can't make the REmover classes shared either (because htey need to respectively subclass either CSharpSyntaxRewriter and VisualBasicSyntaxRewriter).  

However, i can try to share some smaller pieces of logic.

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNodeRemover.cs (hunk 2 above)
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxNodeRemover.cs]: Fixed.

**Comment by CyrusNajmabadi** [comment]
@cston Another look plz?

File: src/Compilers/Core/Portable/Syntax/CommonSyntaxNodeRemover.cs [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+            //      Goo(a, // a stuff
+            //          b, // b stuff
+            //          c);
+            //
+            // If we're removing 'b', we should remove the comma after it.
+            //
+            // If there is no next comma, or the next comma is not on the 
+            // same line, then just remove the preceding comma if there is 
+            // one.  If there is no next or previous comma there's nothing
+            // in the list that needs to be fixed up.
```
Comment (cston) [inline src/Compilers/Core/Portable/Syntax/CommonSyntaxNodeRemover.cs]: The comment and the name of this class are a little confusing because the methods are only classifying separators not removing any nodes.

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-compiler @mattwar i need a second pair of eyes when you get a chance.  thanks!

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
Need another @dotnet/roslyn-compiler review.  Thanks!

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-compiler @mattwar i need a second pair of eyes when you get a chance. thanks!

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-compiler @mattwar i need a second pair of eyes when you get a chance. thanks!

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-compiler @mattwar i need a second pair of eyes when you get a chance. thanks!

**Comment by mattwar** [comment]
What about:

```cs
SomeMethod( /* A */ a, /* B */ b, /* C */ c);
```

Removing b and trailing comma gives me:

```cs
SomeMethod( /* A */ a, /* B */ c);
```
Because the comments are trailing the tokens.

Though this pattern is probably less likely to be used than the end-of-line comments.

**Comment by CyrusNajmabadi** [comment]
@mattwar That case works properly (and has tests).  Specifically, in your example of ```SomeMethod( /* A */ a, /* B */ b, /* C */ c);``` the comma following 'b' is not considered to the be the one "belonging" to 'b'.  We only consider the comma to belong to it if it is followed by a newline.

So, in this case, we'll do the right thing and will make ```SomeMethod( /* A */ a, /* C */ c);```

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-compiler Are you ok with just Chuck and Matt's reviews?

**Comment by CyrusNajmabadi** [comment]
@agocke Can you take a look?  Thanks!

**Comment by CyrusNajmabadi** [comment]
@sharwell can you, or someone on @dotnet/roslyn-ide help get this in?  Thanks!

**Comment by jinujoseph** [comment]
@jcouv can you get a second review for this from compiler side

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNodeRemover.cs [hunk 5]
```diff
@@ -213,16 +213,20 @@ public override SeparatedSyntaxList<TNode> VisitList<TNode>(SeparatedSyntaxList<
                                 alternate.Add(withSeps, 0, i);
                             }
 
-                            if (alternate.Count > 0 && alternate[alternate.Count - 1].IsToken)
+                            CommonSyntaxNodeRemover.GetSeparatorInfo(
+                                withSeps, i, (int)SyntaxKind.EndOfLineTrivia,
+                                out var nextTokenIsSeparator, out var nextSeparatorBelongsToNode);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxNodeRemover.cs]: Please spell out bool types

File: src/Compilers/CSharp/Portable/Syntax/CSharpSyntaxVisitor.cs [hunk 6]
```diff
@@ -2,6 +2,7 @@
 
 using Microsoft.CodeAnalysis.CSharp.Symbols;
 using Microsoft.CodeAnalysis.CSharp.Syntax;
+using Microsoft.CodeAnalysis.Syntax;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Syntax/CSharpSyntaxVisitor.cs]: Can be removed?

**Comment by sharwell** [comment]
@jcouv Updated for your two changes

**Comment by jcouv** [comment]
@sharwell FYI The PR is all green, if you're ready for ask-mode approval (probably needs template).

**Comment by sharwell** [comment]
@Pilchie for ask mode

**Comment by Pilchie** [comment]
To comment - this change missed the cutoff for 15.6 Escrow.  Given the narrowness of the scenario, we're going to just take it for 15.7 instead.

**Comment by Pilchie** [comment]
Approved - sorry for the delay
