### PR TITLE
Verify that bound node has ConstantValue even when underlying symbol has one.

### LINKED ISSUE #8475: NullReferenceException when local Const is used before its declaration
Ported from DevDiv 187850

```
Public Class TestClass
    Shared Sub Main()
        Dim x as Integer = STR_DEF
        Const STR_DEF As String = vbNullString
    End Sub
End Class
```

Observed: NullReferenceException
>	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Conversions.ClassifyNumericConstantConversion(Microsoft.CodeAnalysis.VisualBasic.BoundExpression constantExpression, Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol destination, Microsoft.CodeAnalysis.VisualBasic.Binder binder) Line 1482	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Conversions.ClassifyPredefinedConversion(Microsoft.CodeAnalysis.VisualBasic.BoundExpression source, Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol destination, Microsoft.CodeAnalysis.VisualBasic.Binder binder, Boolean userDefinedConversionsMightStillBeApplicable, System.Collections.Generic.HashSet(Of Microsoft.CodeAnalysis.DiagnosticInfo) useSiteDiagnostics) Line 944	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Conversions.ClassifyConversion(Microsoft.CodeAnalysis.VisualBasic.BoundExpression source, Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol destination, Microsoft.CodeAnalysis.VisualBasic.Binder binder, System.Collections.Generic.HashSet(Of Microsoft.CodeAnalysis.DiagnosticInfo) useSiteDiagnostics) Line 996	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Binder.ApplyConversion(Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode node, Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol targetType, Microsoft.CodeAnalysis.VisualBasic.BoundExpression argument, Boolean isExplicit, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, Boolean isOperandOfConditionalBranch, Boolean explicitSemanticForConcatArgument) Line 393	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Binder.ApplyImplicitConversion(Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode node, Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol targetType, Microsoft.CodeAnalysis.VisualBasic.BoundExpression expression, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, Boolean isOperandOfConditionalBranch) Line 304	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Binder.BindVariableDeclaration(Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode tree, Microsoft.CodeAnalysis.VisualBasic.Syntax.ModifiedIdentifierSyntax name, Microsoft.CodeAnalysis.VisualBasic.Syntax.AsClauseSyntax asClauseOpt, Microsoft.CodeAnalysis.VisualBasic.Syntax.EqualsValueSyntax equalsValueOpt, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, Boolean skipAsNewInitializer) Line 1124	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Binder.BindVariableDeclarators(Microsoft.CodeAnalysis.SeparatedSyntaxList(Of Microsoft.CodeAnalysis.VisualBasic.Syntax.VariableDeclaratorSyntax) declarators, Microsoft.CodeAnalysis.DiagnosticBag diagnostics) Line 978	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Binder.BindLocalDeclaration(Microsoft.CodeAnalysis.VisualBasic.Syntax.LocalDeclarationStatementSyntax node, Microsoft.CodeAnalysis.DiagnosticBag diagnostics) Line 946	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Binder.BindStatement(Microsoft.CodeAnalysis.VisualBasic.Syntax.StatementSyntax node, Microsoft.CodeAnalysis.DiagnosticBag diagnostics) Line 77	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Binder.BindBlock(Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode syntax, Microsoft.CodeAnalysis.SyntaxList(Of Microsoft.CodeAnalysis.VisualBasic.Syntax.StatementSyntax) stmtList, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, Microsoft.CodeAnalysis.VisualBasic.Binder stmtListBinder) Line 2006	Basic

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixed #8475.

@dotnet/roslyn-compiler Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
Test prtest/win/dbg/unit64 please

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

**Comment by jaredpar** [comment]
:+1:

File: src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb [hunk 1]
```diff
@@ -916,13 +916,16 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
-            ' Using <symbol>.IsConstant() for field accesses can result in an infinite loop.
+            ' Using source.IsConstant for field accesses can result in an infinite loop.
             ' To detect such a loop pass the already visited constants from the binder.
+            ' The check for source.IsConstant is still necessary because the node might still 
+            ' be considered as a non-constant in some error conditions (a reference before declaration,
+            ' for example).
             Dim sourceIsConstant As Boolean = False
             If source.Kind = BoundKind.FieldAccess Then
-                sourceIsConstant = DirectCast(source, BoundFieldAccess).FieldSymbol.GetConstantValue(binder.ConstantFieldsInProgress) IsNot Nothing
+                sourceIsConstant = DirectCast(source, BoundFieldAccess).FieldSymbol.GetConstantValue(binder.ConstantFieldsInProgress) IsNot Nothing AndAlso source.IsConstant
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb]: Please add a test for this case.

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb]: I don't believe we can have the same situation for fields right now and making defensive change because it can only make things better, not worse.

File: src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb [hunk 2]
```diff
@@ -916,13 +916,16 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
             userDefinedConversionsMightStillBeApplicable = False
             Dim conv As ConversionKind
 
-            ' Using <symbol>.IsConstant() for field accesses can result in an infinite loop.
+            ' Using source.IsConstant for field accesses can result in an infinite loop.
             ' To detect such a loop pass the already visited constants from the binder.
+            ' The check for source.IsConstant is still necessary because the node might still 
+            ' be considered as a non-constant in some error conditions (a reference before declaration,
+            ' for example).
```
Comment (agocke) [inline src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb]: This comment now reads as saying that source.IsConstant can cause an infinite loop, but we're going to do it anyway.

I presume checking the `ConstantFieldsInProgress` first allows us to break the cycle. If so, can you please consolidate this comment to explain the best practices around calling `source.IsConstant` in this method?

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb]: All source.IsConstant does is checking if source.ConstantValueOpt is not Nothoing. If sourceIsConstant is true, the code below (ClassifyNothingLiteralConversion, ClassifyNumericConstantConversion) is going to request ConstantValueOpt anyway, so adding source.IsConstant condition at the end with AndAlso doesn't add any new chances for an infinite loop.
Regarding the comment. I think the comment is quite clear. However, if you provide a complete wording that you believe is better, I will happily replace the comment with it.

Comment (agocke) [inline src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb]: We agree offline that the code as written is good, so my suggestion would be that the comment read as follows:

```
' Using source.IsConstant for field accesses can result in an infinite loop.
' To resolve the cycle, first call GetConstantValue with the already visited constants from the binder.		             
' The check for source.IsConstant is still necessary because the node might still 
' be considered as a non-constant in some error conditions (a reference before declaration,
' for example).
```

**Comment by agocke** [comment]
:+1:

File: src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb (hunk 2 above)
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Semantics/Conversions.vb]: The comment has been updated.

**Comment by cston** [comment]
LGTM

**Comment by AlekseyTs** [comment]
Re-syncing Jenkins

**Comment by AlekseyTs** [comment]
Test prtest/lin/dbg/unit32 please.

**Comment by AlekseyTs** [comment]
Test prtest/win/dbg/unit64 please
