### PR TITLE
Detect indirect cyclic constructor chaining

### LINKED ISSUE #366: Cyclical constructor chaining in C# should result in an error
In C# it is a compile-time error to write a constructor that recursively chains directly to itself

```cs
class C
{
    public C(int x) : this(x+1) {}
}
```

A quick survey revealed that most people (including Mads and Anders) thought that (like Java) we also forbid indirect recursion

```cs
class C
{
    public C(int x) : this() {}
    public C() : this(0) {}
}
```

In fact the C# compiler accepts this without complaint. However, these constructors can never complete normally – they always cause a stack overflow.
 
This code is broken. The basic principle of a strongly-typed language is to tell the programmer about incorrect code at compile-time rather than leaving it to be diagnosed during some later run of the code. A programmer who writes this code benefits from learning about the broken code immediately.
 
The C# team proposes to specify that it is a compile-time error for a constructor to chain to itself directly or indirectly. (It is already an error in VB)

[Ported from TFS bug DevDiv 1092076]

### PR DESCRIPTION
**Pull request by gafter**
Detect and report cyclic constructor initializers that are indirect.
    Fixes #366
Also Rename CSharpCompilation.SemanticDiagnostics to DeclarationDiagnostics.
    See #846.

### CODE REVIEW

**Comment by gafter** [comment]
I apologize for mixing the two issues in one PR, but one issue popped up while I was addressing the other (I tried reporting the initializer cycles in `compilation.SemanticDiagnostics` but they disappeared into a black hole)

**Comment by gafter** [comment]
@jaredpar @VSadov @AlekseyTs @agocke @VladimirReshetnikov Could a couple of you review this please?

File: src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs [hunk 1]
```diff
@@ -164,6 +172,59 @@ public void Free()
...
             _wrappers = null;
+            _constructorInitializers = null;
+        }
+
+        // Add an edge to the ctor-initializer graph
+        internal void NoteConstructorInitializer(MethodSymbol method1, MethodSymbol method2, CSharpSyntaxNode syntax)
+        {
+            if (_constructorInitializers == null)
+            {
+                _constructorInitializers = new Dictionary<MethodSymbol, Tuple<MethodSymbol, CSharpSyntaxNode>>();
```
Comment (sharwell) [inline src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs]: I would prefer to use another dictionary implementation whose enumeration is dependent on something like the location within a source file, or even the order in which items get added. The order of enumerating `Keys` determines which constructor in the chain is the target of the new error.

File: src/Compilers/CSharp/Portable/Errors/ErrorCode.cs [hunk 2]
```diff
@@ -540,7 +540,9 @@ internal enum ErrorCode
         ERR_PartialMethodInExpressionTree = 765,
         ERR_PartialMethodMustReturnVoid = 766,
         ERR_ExplicitImplCollisionOnRefOut = 767,
-        // unused 768-799
+        ERR_RecursiveConstructorCall2 = 768,
```
Comment (sharwell) [inline src/Compilers/CSharp/Portable/Errors/ErrorCode.cs]: :question: Can this be `ERR_IndirectRecursiveConstructorCall`?

File: src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs [hunk 3]
```diff
@@ -164,6 +172,59 @@ public void Free()
...
+                var errorLocation = _constructorInitializers[ctor].Item2.Location;
+                diagnostics.Add(ErrorCode.ERR_RecursiveConstructorCall2, errorLocation, ctor);
+                _constructorInitializers.Remove(ctor);
+            }
+
+            visiting.Free();
+            todo.Free();
+        }
+
+        private bool HasCycleAt(MethodSymbol ctor, HashSet<MethodSymbol> visiting, HashSet<MethodSymbol> todo)
```
Comment (sharwell) [inline src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs]: I believe it's possible for the current implementation to return true for a constructor which is not actually part of a recursive loop. For example, consider the following constructors used in the test:

```csharp
public A() : this(1) {}
public A(int x) : this(string.Empty) {}
public A(string s) : this(1) {}
```

Do we want to make sure this warning is only reported on `A.A(int)` or `A.A(string)`, or is it also acceptable for it to be reported on `A.A()`. Note that if we report it on `A.A()`, the use of `_constructorInitializers.Remove(ctor)` above to "break the loop" will not behave as expected, and you could see two errors for a single loop.

File: src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs [hunk 4]
```diff
@@ -164,6 +172,59 @@ public void Free()
...
+        {
+            // Consider rewriting this code to use an explicit stack instead of recursion.
+            try
+            {
+                if (!visiting.Add(ctor))
+                    return true;
+                if (!todo.Remove(ctor))
+                    return false;
+                var next = _constructorInitializers[ctor];
```
Comment (sharwell) [inline src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs]: :question: What is the purpose of `todo`? In the current code, it seems to be duplicating the job of `visiting`. If that is the case, you can remove `todo` and get the next item using this:

```csharp
MethodSymbol next;
if (!_constructorInitializers.TryGetValue(ctor, out next))
  return false;
```

File: src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs (hunk 3 above)
Comment (sharwell) [inline src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs]: :question: If `todo` is removed, would it make sense to get rid of `visiting` as well in favor of a constant space cycle detection algorithm (e.g. the [tortoise and hare algorithm](http://en.wikipedia.org/wiki/Cycle_detection#Tortoise_and_hare))?

File: src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs]: The implementation reports the one error on the (lexically) last constructor in each distinct ctor-initializer cycle. It does not depend on the order of enumeration of the keys anywhere.

File: src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs (hunk 3 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs]: As you can see by the test, that does not occur. We process the constructors in lexical order, adding them to the graph one by one. As soon as the graph contains a cycle, we report it on the last constructor and remove that ctor from the graph. So the order is both deterministic and the reporting is correct.

File: src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs (hunk 4 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs]: It was intended to reduce the complexity of the cycle detection algorithm by preventing the analysis of a ctor that has already been analyzed. `todo` is monotonically growing, while `visited` only contains the ctors in the current chain.

File: src/Compilers/CSharp/Portable/Errors/ErrorCode.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Errors/ErrorCode.cs]: I'd prefer the more explicit message and a separate error number.

Comment (sharwell) [inline src/Compilers/CSharp/Portable/Errors/ErrorCode.cs]: Sorry I wasn't more clear here. `ERR_IndirectRecursiveConstructorCall` does not currently exist; I was suggesting it as a more clearly-named constant for this particular diagnostic.

Comment (gafter) [inline src/Compilers/CSharp/Portable/Errors/ErrorCode.cs]: Yes, that would be more clear.

File: src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs (hunk 3 above)
Comment (sharwell) [inline src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs]: @gafter Thanks for following up. I edited my comment above to describe the incorrect assumption I made which led to that conclusion. I would still consider comparing an implementation using a constant space cycle-detection algorithm with the one used here to see which one performs better in the wild.

File: src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs [hunk 5]
```diff
@@ -68,6 +70,12 @@ internal MethodWithBody(MethodSymbol method, BoundStatement body, ImportChain im
 
         public LambdaFrame staticLambdaFrame;
 
+        /// <summary>
+        /// A graph of method->method references for this(...) constructor initializers.
+        /// Used to detect and report initializer cycles.
+        /// </summary>
+        Dictionary<MethodSymbol, Tuple<MethodSymbol, CSharpSyntaxNode>> _constructorInitializers;
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs]: A full `Dictionary<TKey, TValue>` seems wasteful here because the majority case won't have more than a few entries. Do we have a frugal dictionary we could use here instead?

File: src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs (hunk 3 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs]: I think the idea of using a constant space cycle-detection algorithm is awesome. Given that we maintain the invariant that the set of edges stored so far is acyclic, we can use an even simpler one than the tortoise-and-hare algorithm. I will prepare a revision.

File: src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs (hunk 5 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs]: @jaredpar http://source.roslyn.io/#Microsoft.CodeAnalysis/Collections/SmallDictionary.cs,53fe71a956c56abd

**Comment by gafter** [comment]
@jaredpar @VSadov @AlekseyTs @agocke @VladimirReshetnikov Could a couple of you review this please? Teaser: we now use a constant-space loop detection algorithm.

**Comment by jaredpar** [comment]
:+1:

File: src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs [hunk 6]
```diff
@@ -1872,21 +1872,34 @@ internal override CommonMessageProvider MessageProvider
...
-        internal DiagnosticBag SemanticDiagnostics
+        internal DiagnosticBag DeclarationDiagnostics
         {
             get
             {
-                if (_lazySemanticDiagnostics == null)
+                // We should only be placing diagnostics in this bag until
+                // we are done gathering declaration diagnostics. Assert that is
+                // the case. But since we have bugs (see https://github.com/dotnet/roslyn/issues/846)
+                // we disable the assertion until they are fixed.
```
Comment (VladimirReshetnikov) [inline src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs]: TODO comment?

File: src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs [hunk 7]
```diff
@@ -1872,21 +1872,34 @@ internal override CommonMessageProvider MessageProvider
...
+                return _lazyDeclarationDiagnostics;
             }
         }
 
-        private DiagnosticBag _lazySemanticDiagnostics;
+        private IEnumerable<Diagnostic> FreezeDeclarationDiagnostics()
+        {
+            _declarationDiagnosticsFrozen = true;
+            var result = _lazyDeclarationDiagnostics?.AsEnumerable() ?? Enumerable.Empty<Diagnostic>();
+            return result;
```
Comment (VladimirReshetnikov) [inline src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs]: Consider inlining the 'result' variable.

File: src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs [hunk 8]
```diff
@@ -164,6 +172,58 @@ public void Free()
             }
 
             _wrappers = null;
+            _constructorInitializers = null;
+        }
+
+        /// <summary>
+        /// Report an error if adding the edge (method1, method2) to the ctor-initializer
+        /// graph would add a new cycle to that graph.
```
Comment (VladimirReshetnikov) [inline src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs]: Why "a _new_ cycle"?

File: src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs [hunk 9]
```diff
@@ -164,6 +172,58 @@ public void Free()
...
+            if (method1 == method2)
+            {
+                // direct recursion is diagnosed elsewhere
+                throw ExceptionUtilities.Unreachable;
+            }
+
+            if (_constructorInitializers == null)
+            {
+                _constructorInitializers = new SmallDictionary<MethodSymbol, MethodSymbol>();
+                _constructorInitializers.Add(method1, method2);
```
Comment (VladimirReshetnikov) [inline src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs]: Consider using collection initializer instead of Add method.

File: src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs [hunk 10]
```diff
@@ -164,6 +172,58 @@ public void Free()
...
+                return;
+            }
+
+            MethodSymbol next = method2;
+            while (true)
+            {
+                if (_constructorInitializers.TryGetValue(next, out next))
+                {
+                    Debug.Assert((object)next != null);
```
Comment (VladimirReshetnikov) [inline src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs]: Consider adding Debug.Assert(next != method2)  -  that would cause an infinite loop.

File: src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs [hunk 11]
```diff
@@ -10055,6 +10055,32 @@ public class A : A<int>
                 Diagnostic(ErrorCode.ERR_RecursiveConstructorCall, "base").WithArguments("A.A()"));
         }
 
+        [WorkItem(366, "https://github.com/dotnet/roslyn/issues/366")]
+        [Fact]
+        public void IndirectConstructorCycle()
+        {
+            var text = @"
+public class A
```
Comment (VladimirReshetnikov) [inline src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs]: Consider adding a test for structs.

File: src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs (hunk 6 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs]: No TODO comment. In fact, we will soon embark on the task of cleaning out the TODOs and adding github issues to replace them.

File: src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs (hunk 8 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Compiler/TypeCompilationState.cs]: A new cycle is one that wasn't previously there. I use this word for clarity, since the call graph may have had cycles among previously considered edges, even though such cycles are not recorded in the graph that we store as we avoid adding cycle-inducing edges.

**Comment by VladimirReshetnikov** [comment]
:+1:

**Comment by agocke** [comment]
LGTM
