### PR TITLE
Fix build task on CoreClr 3.0

### LINKED ISSUE #31737: Roslyn failing on latest coreclr
This is blocking insertion of runtime into core-sdk in https://github.com/dotnet/core-sdk/pull/204

```
error MSB4061: The "Csc" task could not be instantiated from "D:\Src\core-sdk\bin\2\win-x64\dotnet\sdk\3.0.100-preview-009827\Roslyn\Microsoft.Build.Tasks.CodeAnalysis.dll". 

System.TypeInitializationException: The type initializer for 'Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler' threw an exception. 
---> System.TypeInitializationException: The type initializer for 'Microsoft.CodeAnalysis.BuildTasks.AssemblyResolution' threw an exception. 
---> System.TypeInitializationException: The type initializer for '_AppDomain' threw an exception. 
---> System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type)
   at Roslyn.Utilities.CorLightup.Desktop._AppDomain..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.CodeAnalysis.BuildTasks.AssemblyResolution..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler..ctor()
   at Microsoft.CodeAnalysis.BuildTasks.Csc..ctor() 
```

Why is code in CorLightup.*Desktop* running on CoreCLR? It is failing against implementation changes in .NET Core 3.0.

cc @jaredpar @jkotas

### PR DESCRIPTION
**Pull request by jaredpar**
The compiler build tasks were broken on CoreClr due to some private reflection code that got invalidated by runtime changes. As I dug into this though most of this usage stemmed from our days when the compiler build task was single targeted and targeting netstandard1.3. Now that we multi-target all of our end points and reference netstandard2.0 lots of this light up code can simply be deleted. 

closes #31737

### CODE REVIEW

**Comment by jaredpar** [comment]
@dotnet/roslyn-compiler, @nguerrera, @tmat for review

**Comment by jaredpar** [comment]
@dotnet/roslyn-ide for review of some small changes. Just moved reflection based code to use APIs directly.

**Comment by jasonmalinowski** [comment]
I think @tmat is the only real expert on the "IDE" bits of this.

File: src/Compilers/Shared/DesktopShim.cs [hunk 1]
```diff
@@ -14,12 +14,11 @@ internal static class DesktopShim
     {
         internal static class FileNotFoundException
         {
-            internal static readonly Type Type = ReflectionUtilities.TryGetType(
-               "System.IO.FileNotFoundException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a");
+            internal static readonly Type Type = typeof(FileNotFoundException);
```
Comment (nguerrera) [inline src/Compilers/Shared/DesktopShim.cs]: Isn't this typeof this static class?

Comment (jaredpar) [reply src/Compilers/Shared/DesktopShim.cs]: good catch ...

**Comment by jaredpar** [comment]
@dotnet/roslyn-compiler  PTAL. Need to get this in so we can unblock .NET core 3.0 work.

File: eng/Versions.props [hunk 2]
```diff
@@ -200,11 +200,6 @@
     <MicrosoftCodeAnalysisVisualBasicWorkspacesFixedVersion>$(CodeStyleLayerCodeAnalysisVersion)</MicrosoftCodeAnalysisVisualBasicWorkspacesFixedVersion>
   </PropertyGroup>
 
-  <!-- TODO: remove https://github.com/dotnet/roslyn/issues/31479 -->
```
[the remark this answers is not in the document]
Comment (jaredpar) [reply eng/Versions.props]: Yes. This PR removes all uses of this element that I could find. Did you see one I missed?

File: src/Compilers/Core/MSBuildTask/Microsoft.Build.Tasks.CodeAnalysis.csproj [hunk 3]
```diff
@@ -75,12 +72,12 @@
     </EmbeddedResource>
   </ItemGroup>
   <ItemGroup>
-    <PackageReference Include="Microsoft.Build" Version="$(MicrosoftBuildFixedVersion)" />
-    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="$(MicrosoftBuildTasksCoreFixedVersion)" />
+    <PackageReference Include="Microsoft.Build.Framework" Version="$(MicrosoftBuildFrameworkVersion)" ExcludeAssets="Runtime" />
```
Comment (jcouv) [inline src/Compilers/Core/MSBuildTask/Microsoft.Build.Tasks.CodeAnalysis.csproj]: I didn't understand what `ExcludeAssets` is for. What purpose does it serve here?

Comment (jaredpar) [reply src/Compilers/Core/MSBuildTask/Microsoft.Build.Tasks.CodeAnalysis.csproj]: A NuGet package can come with a variety of assets inside it. For this line there are two types that are important: runtime and compile time. The compile time assets are the libraries that we compile against (ref dlls for example). The runtime assets are items the NuPkg believes are necessary at runtime.

For MSBuild we are hosted inside their process. We never start up MSBuild on our own and create say a workspace. This bulid task is always loaded in their runtime. Hence their runtime assets aren't useful to us (and can possibly confuse our analysis). Hence we exclude them. 

Note: this is how we handle MSBuild assets in other parts of the Roslyn repository. The build task was always "wrong-ish" here.

File: src/Scripting/Core/Hosting/AssemblyLoader/DesktopAssemblyLoaderImpl.cs [hunk 4]
```diff
@@ -15,14 +15,14 @@ public DesktopAssemblyLoaderImpl(InteractiveAssemblyLoader loader)
             : base(loader)
         {
             _assemblyResolveHandlerOpt = loader.ResolveAssembly;
-            CorLightup.Desktop.AddAssemblyResolveHandler(_assemblyResolveHandlerOpt);
+            CoreLightup.Desktop.AddAssemblyResolveHandler(_assemblyResolveHandlerOpt);
```
Comment (jcouv) [inline src/Scripting/Core/Hosting/AssemblyLoader/DesktopAssemblyLoaderImpl.cs]: I didn't understand why we can't eliminate the light up class for scripting too.

File: src/Compilers/Core/MSBuildTask/Microsoft.Build.Tasks.CodeAnalysis.csproj (hunk 3 above)
Comment (jcouv) [reply src/Compilers/Core/MSBuildTask/Microsoft.Build.Tasks.CodeAnalysis.csproj]: Should we also use `ExcludeAssets` below (in `Microsoft.Build.Tasks.CodeAnalysis.UnitTests.csproj`)?

File: eng/Versions.props (hunk 2 above)
[the remark this answers is not in the document]
Comment (jcouv) [reply eng/Versions.props]: Consider adding "Fixes #..." to the description. That will automatically link and close it when you merge.

File: src/Compilers/Core/MSBuildTask/Microsoft.Build.Tasks.CodeAnalysis.csproj (hunk 3 above)
Comment (nguerrera) [reply src/Compilers/Core/MSBuildTask/Microsoft.Build.Tasks.CodeAnalysis.csproj]: No. The unit tests need the msbuild dll runtime assets because they load the task outside of an msbuild process.

File: src/Scripting/Core/Hosting/AssemblyLoader/DesktopAssemblyLoaderImpl.cs (hunk 4 above)
Comment (jaredpar) [reply src/Scripting/Core/Hosting/AssemblyLoader/DesktopAssemblyLoaderImpl.cs]: The scripting code still depends on the assembly resolving process but is not multi-targeted (it's a netstandard 2.0 project). Scripting doesn't run on CoreClr at the moment hence this isn't actually a problem. But I was unsure how to unwind this code correctly. I filed the following bug to followup and it's linked to the commits that updated scripting

https://github.com/dotnet/roslyn/issues/31762

File: eng/Versions.props (hunk 2 above)
[the remark this answers is not in the document]
Comment (jaredpar) [reply eng/Versions.props]: I added that as the commit message on https://github.com/dotnet/roslyn/pull/31763/commits/2a8ea55f99c5b7dc45e9b9699976faf5175794fb. That will have the same effect. Given the number of commits here I wanted to link it the specific change vs. the  PR.
