### PR TITLE
Include project diagnostic suppressors in host analyzer execution

### LINKED ISSUE #75399: NuGet-installed diagnostic suppressors should be able to suppress VSIX-installed analyzer diagnostics
This regression was introduced by #75317.

Tracks a comment in test code.

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #75399

### CODE REVIEW

File: src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/DiagnosticComputer.cs [hunk 1]
```diff
@@ -528,7 +528,15 @@ private static (ImmutableArray<DiagnosticAnalyzer> projectAnalyzers, ImmutableAr
             }
         }
 
-        return (projectBuilder.ToImmutableAndClear(), hostBuilder.ToImmutableAndClear());
+        var projectAnalyzers = projectBuilder.ToImmutableAndClear();
+
+        if (hostAnalyzerIds.Any())
+        {
+            // If any host analyzers are active, make sure to also include any project diagnostic suppressors
+            hostBuilder.AddRange(projectAnalyzers.WhereAsArray(static a => a is DiagnosticSuppressor));
```
Comment (tmat) [inline src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/DiagnosticComputer.cs:536]: Nit: Don't need "WhereAsArray" here, "Where" should do.

File: src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/DiagnosticComputer.cs [hunk 2]
```diff
@@ -396,31 +396,23 @@ private async Task<SerializableDiagnosticAnalysisResults> AnalyzeAsync(
...
-        {
-            builderMap = builderMap.AddRange(await hostAnalysisResult.ToResultBuilderMapAsync(
-                additionalPragmaSuppressionDiagnostics, documentAnalysisScope,
-                _project, VersionStamp.Default, compilationWithAnalyzers.HostCompilation!,
-                hostAnalyzers, skippedAnalyzersInfo, reportSuppressedDiagnostics, cancellationToken).ConfigureAwait(false));
+                _project, VersionStamp.Default, compilationWithAnalyzers.ProjectCompilation, compilationWithAnalyzers.HostCompilation,
+                projectAnalyzers, hostAnalyzers, skippedAnalyzersInfo, reportSuppressedDiagnostics, cancellationToken).ConfigureAwait(false));
         }
 
+        // TODO Does this need adjustment?
```
Comment (sharwell) [inline src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/DiagnosticComputer.cs:413]: 📝 Need to trace this data back and see if the `telemetry` list is ever converted back to a dictionary

File: src/Workspaces/Core/Portable/Diagnostics/Extensions.cs [hunk 3]
```diff
@@ -270,7 +274,9 @@ static void AddDiagnosticsToResult(
             }
 
             diagnostics = diagnostics.Filter(diagnosticIdsToFilter, includeSuppressedDiagnostics, span);
-            Debug.Assert(diagnostics.Length == CompilationWithAnalyzers.GetEffectiveDiagnostics(diagnostics, compilation).Count());
+
+            // ⚠️ No obvious way to keep this assertion
+            //Debug.Assert(diagnostics.Length == CompilationWithAnalyzers.GetEffectiveDiagnostics(diagnostics, compilation).Count());
```
Comment (sharwell) [inline src/Workspaces/Core/Portable/Diagnostics/Extensions.cs:279]: 📝 Need to understand how important this assertion is. If it is not important, there are multiple parameters that can be removed to simplify this code.

File: src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/DiagnosticComputer.cs (hunk 2 above)
Comment (sharwell) [reply src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/DiagnosticComputer.cs:413]: This is converted back to a dictionary, so I need to modify the code to avoid having the key present twice.

Comment (sharwell) [reply src/Workspaces/Remote/ServiceHub/Services/DiagnosticAnalyzer/DiagnosticComputer.cs]: ➡️ Problems are now avoided by using the merged telemetry dictionary

**Review by arunchndr — APPROVED** [review]

File: src/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.InProcOrRemoteHostAnalyzerRunner.cs [hunk 4]
```diff
@@ -167,7 +167,9 @@ private async Task<DiagnosticAnalysisResultMap<DiagnosticAnalyzer, DiagnosticAna
 
                 if (hostAnalysisResult is not null)
                 {
-                    telemetry = telemetry.AddRange(hostAnalysisResult.AnalyzerTelemetryInfo);
+                    // Use SetItems instead of AddRange so exceptions will not occur if diagnostic suppressors are
+                    // counted in both project and host analysis results.
+                    telemetry = telemetry.SetItems(hostAnalysisResult.AnalyzerTelemetryInfo);
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.InProcOrRemoteHostAnalyzerRunner.cs]: ➡️ We now use whichever value is the largest

**Review by arunchndr — APPROVED** [review]

File: src/Workspaces/Core/Portable/Diagnostics/Extensions.cs (hunk 3 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Diagnostics/Extensions.cs]: ➡️ I removed this assertion and the parameters supporting it.

**Review by tmat — APPROVED** [review]
