### PR TITLE
Make ValueText return empty instead of null

### LINKED ISSUE #41304: default(SyntaxToken).ValueText could return an empty string
**Version Used**: 1b4b5ba7e615e8fdbde036806bac710977e0239c

**Steps to Reproduce**:

```
default(SyntaxToken).ValueText
```

**Expected Behavior**:

Returns `""`.

**Actual Behavior**:

Returns `null`.

This is the only situation where `SyntaxToken.ValueText` returns `null`, and it forces the property itself to have type `string?` instead of `string`. If we update the return value for this case, the property no longer needs to be nullable.

### PR DESCRIPTION
**Pull request by sharwell**
Closes #41304

### CODE REVIEW

File: src/Features/CSharp/Portable/SignatureHelp/TupleConstructionSignatureHelpProvider.cs [hunk 1]
```diff
@@ -24,7 +24,7 @@ internal class TupleConstructionSignatureHelpProvider : AbstractCSharpSignatureH
         private static readonly Func<TupleExpressionSyntax, SyntaxToken> s_getOpenToken = e => e.OpenParenToken;
         private static readonly Func<TupleExpressionSyntax, SyntaxToken> s_getCloseToken = e => e.CloseParenToken;
         private static readonly Func<TupleExpressionSyntax, IEnumerable<SyntaxNodeOrToken>> s_getArgumentsWithSeparators = e => e.Arguments.GetWithSeparators();
-        private static readonly Func<TupleExpressionSyntax, IEnumerable<string>> s_getArgumentNames = e => e.Arguments.Select(a => a.NameColon?.Name.Identifier.ValueText ?? string.Empty);
+        private static readonly Func<TupleExpressionSyntax, IEnumerable<string>> s_getArgumentNames = e => e.Arguments.Select(a => a.NameColon?.Name.Identifier.ValueText);
```
Comment (RikkiGibson) [inline src/Features/CSharp/Portable/SignatureHelp/TupleConstructionSignatureHelpProvider.cs]: I don't understand why we can delete the `?? string.Empty` here, since we still do a conditional access for `a.NameColon?.Name`

Comment (sharwell) [reply src/Features/CSharp/Portable/SignatureHelp/TupleConstructionSignatureHelpProvider.cs]: great catch!
