### PR TITLE
Activate language client during workspace load.

### LINKED ISSUE #39280: Roslyn C#/VB language server fails to start
**Version Used**: 
Visual Studio 2019 16.3 and later

**Steps to Reproduce**:

This is an intermittent repro that appears to be the result of the Roslyn language server returning a null connection when its ILanguageClient is called.

1. Open a C# or VB solution
2. Attempt to search for code in Ctrl+Q search box

**Expected Behavior**:
Symbols appear in the box.

**Actual Behavior**:
Occasionally, the language client fails to start due to a null connection being returned by Roslyn's language client.

### PR DESCRIPTION
**Pull request by dibarbet**
~~pending RPS validation + RPS exception for new DLLs being loaded~~
exception granted

resolved #39280

### CODE REVIEW

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs [hunk 1]
```diff
@@ -13,19 +19,57 @@ namespace Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService
...
+                this._languageClientBroker.Value.LoadAsync(new LanguageClientMetadata(new string[] { ContentTypeNames.CSharpContentType, ContentTypeNames.VisualBasicContentType }), this._languageServerClient).Forget();
+            }, TaskScheduler.Default);
+        }
+
+        /// <summary>
+        /// The <see cref="ILanguageClientBroker.LoadAsync(ILanguageClientMetadata, ILanguageClient)"/> 
+        /// requires that we pass the <see cref="ILanguageClientMetadata"/> along with the language client instance.
+        /// The implementation of <see cref="ILanguageClientMetadata"/> is not public, so have to re-implement.
+        /// </summary>
+        private class LanguageClientMetadata : ILanguageClientMetadata
```
Comment (gundermanc) [inline src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs]: This is unfortunate, we should probably file a bug to have an implementation of this in the LSP client definitions.

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClient.cs [hunk 2]
```diff
@@ -103,38 +97,31 @@ public async Task<Connection> ActivateAsync(CancellationToken cancellationToken)
...
 
-            // set up event stream so that we start LSP server once Roslyn is loaded
-            _eventListener.WorkspaceStarted.ContinueWith(async _ =>
+            // this might get called before solution is fully loaded and before file is opened. 
+            // we delay our OOP start until then, but user might do vsstart before that. so we make sure we start OOP if 
+            // it is not running yet. multiple start is no-op
+            ((RemoteHostClientServiceFactory.RemoteHostClientService)_workspace.Services.GetService<IRemoteHostClientService>()).Enable();
+
+            // wait until remote host is available before let platform know that they can activate our LSP
+            var client = await _workspace.TryGetRemoteHostClientAsync(CancellationToken.None).ConfigureAwait(false);
```
Comment (gundermanc) [inline src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClient.cs]: Is this used anywhere?

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs [hunk 3]
```diff
@@ -13,19 +19,57 @@ namespace Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService
...
     {
+        private readonly LanguageServerClient _languageServerClient;
+        private readonly Lazy<ILanguageClientBroker> _languageClientBroker;
         private readonly TaskCompletionSource<object> _taskCompletionSource;
 
         public Task WorkspaceStarted => _taskCompletionSource.Task;
 
-        public LanguageServerClientEventListener()
+        [ImportingConstructor]
+        [Obsolete(MefConstruction.ImportingConstructorMessage, error: true)]
```
[the remark this answers is not in the document]
Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs]: I believe this is the pattern we use elsewhere, so going to leave as-is

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClient.cs [hunk 4]
```diff
@@ -103,38 +97,31 @@ public async Task<Connection> ActivateAsync(CancellationToken cancellationToken)
...
-                    // don't ask platform to start LSP
-                    return;
-                }
-
-                // let platform know that they can start us
-                await StartAsync.InvokeAsync(this, EventArgs.Empty).ConfigureAwait(false);
-            }, TaskScheduler.Default).CompletesAsyncOperation(token);
+                // there is no OOP. either user turned it off, or process got killed.
+                // don't ask platform to start LSP
+                return;
```
[the remark this answers is not in the document]
Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClient.cs]: Would this be worth throwing up a gold bar here?  Because clearly we're in a bad state here.  Can definitely also add a watson for that.
@heejaechang will we already throw up a gold bar if this happens?

[the remark this answers is not in the document]
Comment (gundermanc) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClient.cs]: IMO, this should be up to the LSP client and/or API to handle.

That said, I'd hope we wouldn't find ourselves in this scenario anymore.

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs (hunk 1 above)
Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs]: @tinaschrepfer to comment here - it also seems like we shouldn't need to pass along the metadata if we have the actual client instance?  Because as a result we're keeping this metadata in two places that must be kept in sync

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClient.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClient.cs]: We can definitely still end up here if the user kills the OOP / OOP crashes as the original comment.

also adding @tinaschrepfer also to comment - is throwing here the appropriate solution, or do we need to take care of displaying the exception properly on our end

**Comment by gundermanc** [comment]
> I'd like to validate before check-in but it looks fine.

Seems like it's working fine.

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClient.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (heejaechang) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClient.cs]: it depends on what we want. if client is null, it means something is broken. and we should have reacted to it when it happened (info bar/NFW and etc) but whether we can connect that to this particular code is different story since the issue could happen 10 mins before and user kept using VS even if info bar told users to close and re-open VS.

so, one could use session explorer to see whether we have got into broken state before this code took place, or one could get dump to see whether OOP of roslyn is turned off, or we lost connection to OOP, or add telemetry to this code path to indicate that we took this code path.

all depends on what you are trying to do.

**Comment by heejaechang** [comment]
for me, interaction seems too complicated then what we conceptually want.

I guess assumption of the API initially was platform can ask LSP client provider to start LSP server and that can always happen when asked. and it was probably true before when assumption was there is already editor opened in VS. since, most of existing language server should have already initialized at that point in practice.

and now, things are complicated since the assumption (LSP client can start LSP server anytime asked) is no longer 100% true. now, a feature (vs search) can call us even when we are not even loaded in VS. meaning no Roslyn is initialized. and we can't just randomly initialize Roslyn for LSP client.

and to make thing more complicated, unlike navigate to, where we simply return nothing when Roslyn is not initialized yet, due to the way LSP client works, we can't simply return nothing since doing so will make platform never try to create our LSP client again even after Roslyn is loaded later.

so, for now, I am not sure nip picking on this initialization matter much since the root cause seems to supporting this new scenario in LSP client where it should not assume the LSP client provider can always provide the client when asked. 

we probably want to provide first party support for such case since I dont think it is only matter of Roslyn. a lot of language service won't be able to do so as well.

**Comment by gundermanc** [comment]
I've published new preview packages for the LSP client with streaming support for 'workspace/symbol'. Consider switching over and removing the 'workspace/beginSymbol' temporary message. Here's a sample of the upgrade: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/217789

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClient.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClient.cs]: I see, thanks!  I think the only solution is to restart VS, so since we already display a gold bar indicating that they should restart VS there's no need to show another one here specifically.  Probably best to just log telemetry here that we hit this then.

[the remark this answers is not in the document]
Comment (tinaschrepfer) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClient.cs]: Throwing exceptions here can have ramifications further down the line.  We don't expect this method to throw exceptions, so it cause a cascading effect when you do throw and potentially deliver a poor user experience.  Our assumption is that in this method, you control if you actually want to activate the language server.

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs (hunk 1 above)
Comment (tinaschrepfer) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs]: This does seem like a deficiency.  We should either have the class available, or allow you to pass an instance of ILanguageClient and we learn the parse the metadata ourselves.  Please file a bug.

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClient.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (gundermanc) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClient.cs]: >We don't expect this method to throw exceptions, so it cause a cascading effect when you do throw and potentially deliver a poor user experience.

The problem I can see with requiring the language service to do their own alerting the user of the failure condition here is the behavior is going to be inconsistent and fragmented across languages. Some will give dialogs, some gold bars, some will do nothing.

Editor has guarded operations as a generic catch-all and reporting mechanism for exceptions. I was advocating for such a model because it keeps things consistent. If the LS is dying anyways, at least the experience is consistent.

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs (hunk 1 above)
Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs]: Done
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1043922

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClient.cs (hunk 2 above)
Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClient.cs]: Yes, this triggers and waits for the oop to actually load.

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs [hunk 5]
```diff
@@ -13,19 +19,58 @@ namespace Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService
...
+        /// We know we can provide <see cref="LanguageServerClient"/> as soon as the workspace is started, so tell the
+        /// <see cref="ILanguageClientBroker"/> to start loading it.
+        /// </summary>
         public void StartListening(Workspace workspace, object serviceOpt)
         {
             // mark that roslyn solution is added
-            _taskCompletionSource.SetResult(null);
+            this._taskCompletionSource.SetResult(null);
+
+            this.WorkspaceStarted.ContinueWith(_ =>
```
Comment (sharwell) [inline src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs]: 😕 Why is this not just using `Task.Run`? It completes `WorkspaceStarted` before calling this line.

Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs]: I wasn't completely sure that workspace started would be completed here, but if it is then I can do that.

Should I be using jtf run, or task run?

Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs]: Task.Run is fine since you are calling `Forget` on the result.

Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs]: Ahh right yeah I'm not waiting for it so it won't deadlock.  Will update.

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs [hunk 6]
```diff
@@ -13,19 +19,58 @@ namespace Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService
...
+        /// We know we can provide <see cref="LanguageServerClient"/> as soon as the workspace is started, so tell the
+        /// <see cref="ILanguageClientBroker"/> to start loading it.
+        /// </summary>
         public void StartListening(Workspace workspace, object serviceOpt)
         {
             // mark that roslyn solution is added
-            _taskCompletionSource.SetResult(null);
+            this._taskCompletionSource.SetResult(null);
+
+            Task.Run(() =>
```
Comment (gundermanc) [inline src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs]: I think this potentially introduces a race condition. The assumption of

```
this._languageClientBroker.Value.LoadAsync(new LanguageClientMetadata(new string[] { ContentTypeNames.CSharpContentType, ContentTypeNames.VisualBasicContentType }), this._languageServerClient).Forget();
```

is that the registration of the initializing client is happening before the thread yields, ensuring that we have record of your initializing client on focus of the Ctrl+Q box when it's focused so we can await your initialization.

Doing this in a task, there's a small chance that registration won't happen by the time the user focuses the box.

Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs]: So I see that since we're running the task, it won't synchronously complete up to the point where the task gets added to the lsp client collection.

But couldn't that be an issue with continue with?  If the original task has the continuation option to run asynchronously - https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcontinuationoptions?view=netframework-4.8 ( RunContinuationsAsynchronously ).

Comment (gundermanc) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs]: >But couldn't that be an issue with continue with? 

It looks like you removed the ContinueWith?

Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs]: I removed it, what I was saying is that I think it could have been an issue before - since continuewith idt necessarily runs the continuation synchronously.  

This would be fixed if I do Task.RunSynchronously right?  It would run the task synchronously, but wouldn't block since we're calling .Forget() on it.

Comment (gundermanc) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs]: > since continuewith idt necessarily runs the continuation synchronously.

The important thing is that the registration happens before the task tracking solution load completes.

My understanding of .NET async code is that calling an async method without awaiting the task via `Forget()` should cause the method to execute up to the first yield/await.

This should have the desired effect, even in an async code path, so long as the solution load task awaits completion of the calling async code path.

The overarching goal is to make sure your ILanguageClient is registered as loading with the LSP client before the threaded wait dialog disappears.

Comment (gundermanc) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs]: Even though it'd be equivalent, I think it'd be clearer to the code reviewer if we updated the LSP client with a 
```csharp
void BeginLoad()
```
method that does the equivalent through a synchronous signature.

Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs]: per this https://devblogs.microsoft.com/pfxteam/when-executesynchronously-doesnt-execute-synchronously/ I was under the impression that it will just queue the continuation task, which means it would be the same as task.run right?

Comment (gundermanc) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs]: >per this https://devblogs.microsoft.com/pfxteam/when-executesynchronously-doesnt-execute-synchronously/ I was under the impression that it will just queue the continuation task, which means it would be the same as task.run right?

I think that's correct for `ContinueWith`. For `LoadAsync().Forget()`, I would expect up to the first await/yield to happen on the calling thread.

Ultimately, it probably doesn't matter too much since in its current state, Roslyn doesn't wait for projects to load before marking the search complete, so there are scenarios in which the user won't get results early in the session.

Ideally, we'd 1) send what's available 2) when a project finishes loading, send an update with that new batch, but that's a larger change.

Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs]: Discussed offline with @sharwell (thanks!!) - since the workspace started task has already been completed, we can just call LoadAsync.Forget without any continuewith / task.run.  Which should then execute synchronously until the task gets loaded into the collection inside the LSP client.

Comment (gundermanc) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs]: Not sure what you're asking, should we chat in person?

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs [hunk 7]
```diff
@@ -13,19 +20,59 @@ namespace Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService
     [ExportEventListener(WellKnownEventListeners.Workspace, WorkspaceKind.Host), Shared]
     internal class LanguageServerClientEventListener : IEventListener<object>
     {
+        private readonly LanguageServerClient _languageServerClient;
+        private readonly Lazy<ILanguageClientBroker> _languageClientBroker;
         private readonly TaskCompletionSource<object> _taskCompletionSource;
```
Comment (gundermanc) [inline src/VisualStudio/Core/Def/Implementation/LanguageClient/LanguageServerClientEventListener.cs]: Looks like _taskCompletionSource is unused

**Comment by dibarbet** [comment]
@dotnet/roslyn-ide could use a review on this - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1053002
