### PR TITLE
[AskMode] Fix issue with #load of files that can't be read as text...

### LINKED ISSUE #6589: Running incorrect #load command crashes Visual Studio
Running
```
>#load "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Xml.dll"
```

In the C# interactive window causes Visual Studio to crash with the following stack trace:

```
   "The given key was not present in the dictionary."
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key) in f:\dd\ndp\fxcore\Open\src\System.Collections.Immutable\src\System\Collections\Immutable\ImmutableDictionary`2.cs:line 258
   at Microsoft.CodeAnalysis.CSharp.SyntaxAndDeclarationManager.GetRemoveSetForLoadedTrees(ImmutableArray`1 loadDirectives, ImmutableDictionary`2 loadDirectiveMap, ImmutableDictionary`2 loadedSyntaxTreeMap, HashSet`1 removeSet) in F:\Builds\5433\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Compilation\SyntaxAndDeclarationManager.cs:line 405
   at Microsoft.CodeAnalysis.CSharp.SyntaxAndDeclarationManager.GetRemoveSet(SyntaxTree oldTree, Boolean includeLoadedTrees, ImmutableArray`1 syntaxTrees, ImmutableDictionary`2 syntaxTreeOrdinalMap, ImmutableDictionary`2 loadDirectiveMap, ImmutableDictionary`2 loadedSyntaxTreeMap, HashSet`1 removeSet, Int32& totalReferencedTreeCount, ImmutableArray`1& oldLoadDirectives) in F:\Builds\5433\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Compilation\SyntaxAndDeclarationManager.cs:line 365
   at Microsoft.CodeAnalysis.CSharp.SyntaxAndDeclarationManager.ReplaceSyntaxTree(SyntaxTree oldTree, SyntaxTree newTree) in F:\Builds\5433\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Compilation\SyntaxAndDeclarationManager.cs:line 448
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.ReplaceSyntaxTree(SyntaxTree oldTree, SyntaxTree newTree) in F:\Builds\5433\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 804
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonReplaceSyntaxTree(SyntaxTree oldTree, SyntaxTree newTree) in F:\Builds\5433\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs:line 2737
   at Microsoft.CodeAnalysis.Solution.<UpdateDocumentInCompilationAsync>d__115.MoveNext() in F:\Builds\5433\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Workspaces\Core\Portable\Workspace\Solution\Solution.cs:line 1621
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 166
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\TaskAwaiter.cs:line 156
   at Microsoft.CodeAnalysis.Solution.CompilationTracker.<BuildDeclarationCompilationFromInProgressAsync>d__27.MoveNext() in F:\Builds\5433\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Workspaces\Core\Portable\Workspace\Solution\Solution.CompilationTracker.cs:line 551"	string
```

Dump available at (ML File Share)\public\jmarolf\Dumps\LoadCrash.dmp

### PR DESCRIPTION
**Pull request by KevinH-MS**
If a #load'ed file can be resolved, but cannot be read (or cannot be read as text), it doesn't get added to the map of resolved file paths -> SyntaxTrees (because there is no SyntaxTree to add).  This wasn't handled in the remove and replace helpers that rebuild the various syntax maps.  In addition, we were attempting to add #load'ed trees to the ordinal map twice in the case that their ordinal position needed to be shifted after a remove or replace.

(fixes #6589)

### CODE REVIEW

**Comment by KevinH-MS** [comment]
@dotnet/roslyn-interactive please review this escrow bug fix.

**Comment by amcasey** [comment]
:+1:

File: src/Compilers/CSharp/Portable/Compilation/SyntaxAndDeclarationManager.cs [hunk 1]
```diff
@@ -383,10 +383,18 @@ public SyntaxAndDeclarationManager RemoveSyntaxTrees(HashSet<SyntaxTree> trees)
...
-                            var loadedTree = loadedSyntaxTreeMap[directive.ResolvedPath];
-                            if (removeSet.Contains(loadedTree))
+                            SyntaxTree loadedTree;
+                            if (loadedSyntaxTreeMap.TryGetValue(directive.ResolvedPath, out loadedTree))
                             {
-                                removeSet.Remove(loadedTree);
+                                if (removeSet.Contains(loadedTree))
+                                {
+                                    removeSet.Remove(loadedTree);
+                                }
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxAndDeclarationManager.cs]: Can call ```removeSet.Remove()``` always, without the ```if``` check.

File: src/Compilers/CSharp/Portable/Compilation/SyntaxAndDeclarationManager.cs [hunk 2]
```diff
@@ -596,10 +617,11 @@ internal static bool IsLoadedSyntaxTree(SyntaxTree tree, ImmutableDictionary<str
...
                         }
-
-                        treesBuilder.Add(tree);
-
-                        ordinalMapBuilder.Add(tree, ordinalMapBuilder.Count);
+                        else
+                        {
+                            // If we don't have a tree for this directive, there should be errors.
+                            Debug.Assert(directive.Diagnostics.HasAnyErrors());
+                        }
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxAndDeclarationManager.cs]: The same ```if (loadedSyntaxTreeMap.TryGetValue(...)) ... else Debug.Assert(...);``` appears multiple times. Consider extracting to a method.

**Comment by cston** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Compilation/SyntaxAndDeclarationManager.cs (hunk 1 above)
Comment (KevinH-MS) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxAndDeclarationManager.cs]: I always forget that--changed.

**Comment by genlu** [comment]
:+1:

File: src/Compilers/CSharp/Portable/Compilation/SyntaxAndDeclarationManager.cs (hunk 2 above)
Comment (KevinH-MS) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxAndDeclarationManager.cs]: Not sure why I overcomplicated that one...done...

**Comment by brettfo** [comment]
If this change is accepted then PR 354 from the internal repo should also be merged into stabilization to enable VSI test coverage.

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-compiler 

Please CC compiler team when making ask mode changes to the compiler.

**Comment by KevinH-MS** [comment]
Sorry—my bad.
