### PR TITLE
Elide an emit optimization that produces bad code near a stackalloc.

### LINKED ISSUE #35764: Invalid IL generated for stackalloc assigned to Span
3.2.0-beta1-19253-08

**Steps to Reproduce**:

1. Compile System.Private.CoreLib

**Expected Behavior**:

Valid IL generated for `Environment.GetEnvironmentVariableCore` method

**Actual Behavior**:

Invalid IL generated for `Environment.GetEnvironmentVariableCore` method

The ECMA spec requires that IL stack is empty, apart from the size item, for localloc instruction.

Details in https://github.com/dotnet/coreclr/pull/24369#issuecomment-493130547

### PR DESCRIPTION
**Pull request by gafter**
Fixes #35764
Also fix the type of a bound node (argument to a ctor) so it agrees with the corresponding parameter.

@jcouv @jaredpar Should this be patched on some other branch?

### CODE REVIEW

**Comment by RikkiGibson** [comment]
When was the bug introduced?

**Comment by jcouv** [comment]
From discussion with Neal this bug was introduced by the nested stackalloc feature (merged in 16.2p1). That feature causes stackallocs to be spilled into a temp: `temp = new Span(stackalloc ...);`.
The problem is in debug mode we don't optimize this temp away so another optimization kicks in that rewrite the initialization as `Span..ctor(&temp, stackalloc ...)`. 
But this breaks a restriction on stackalloc. I don't remember exactly the restriction; I'll let Neal restate it.

**Comment by gafter** [comment]
The restriction is that you can't have anything on the stack when you do a `stackalloc` (other than its argument).  This optimization puts `&temp` on the stack, breaking the constraint.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StackAlloc.cs [hunk 1]
```diff
@@ -46,7 +46,8 @@ public override BoundNode VisitStackAllocArrayCreation(BoundStackAllocArrayCreat
                 var locals = ArrayBuilder<LocalSymbol>.GetInstance();
                 var countTemp = CaptureExpressionInTempIfNeeded(rewrittenCount, sideEffects, locals, SynthesizedLocalKind.Spill);
                 var stackSize = RewriteStackAllocCountToSize(countTemp, elementType);
-                stackAllocNode = new BoundConvertedStackAllocExpression(stackAllocNode.Syntax, elementType, stackSize, initializerOpt, spanType);
+                stackAllocNode = new BoundConvertedStackAllocExpression(
+                    stackAllocNode.Syntax, elementType, stackSize, initializerOpt, _compilation.CreatePointerTypeSymbol(elementType));
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StackAlloc.cs]: >_compilation.CreatePointerTypeSymbol(elementType) [](start = 83, length = 49)

I didn't understand why this part of the change is necessary or good.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs [hunk 2]
```diff
@@ -16203,6 +16205,34 @@ .maxstack  2
   IL_0026:  call       ""int System.Span<int>.Length.get""
   IL_002b:  call       ""void System.Console.Write(int)""
   IL_0030:  ret
+}");
+            comp = CreateCompilationWithMscorlibAndSpan(source, TestOptions.DebugExe);
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs]: >TestOptions.DebugExe [](start = 64, length = 20)

Consider adding some Debug verification or flipping some options in other existing tests.

**Comment by jcouv** [comment]
For the release vehicle question, let's discuss in person.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StackAlloc.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StackAlloc.cs]: This expression is being passed as an argument to the constructor of `Span<T>`.  The argument is a use of the `stackalloc` instruction, which produces a pointer.  But the compiler was recording the type of the argument expression as `Span<T>` instead of a pointer type.  This change corrects that bug.  There were no symptoms of the bug, but it makes the compiler fragile to have nodes lying about their types.

---
In reply to: [285221496](https://github.com/dotnet/roslyn/pull/35780#discussion_r285221496) [](ancestors = 285221496)

**Comment by gafter** [comment]
@julien @cston Could one of you please review this?

**Comment by gafter** [comment]
Note that this fixes https://github.com/dotnet/roslyn/issues/35764.  I had the wrong issue number originally in the OP, but that is fixed now.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs [hunk 3]
```diff
@@ -16261,13 +16294,302 @@ .maxstack  2
...
+  IL_0039:  stloc.3
+  IL_003a:  ldloc.1
+  IL_003b:  ldloca.s   V_3
+  IL_003d:  call       ""int System.Span<int>.Length.get""
+  IL_0042:  mul
+  IL_0043:  call       ""void System.Console.WriteLine(int)""
+  IL_0048:  nop
+  IL_0049:  ret
 }");
         }
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs]: >} [](start = 8, length = 1)

Might it be worth testing passing a stackalloc to a params parameter (`params Span<T>[] p`)?

Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs]: It would be an error to use `Span<T>` as the element type of an array.  Similarly, `stackalloc` is not a constant.

**Comment by tannergooding** [comment]
@gafter, can this be merged now or is it still blocked by something.

Also. CC. @safern, @ViktorHofer
