### PR TITLE
Brace Completion in conditional access expressions.

### LINKED ISSUE #1628: Generic parameter brace completion doesn't work in a conditional access expression
(This repro is dependent on PR #1626 being fixed first)

``` C#
using System.Linq;

class C
{
    void M(object[] args)
    {
        args?.OfType$$
    }
}
```

After typing '<' at the caret location indicated by '$$', automatic brace completion doesn't add '>' and this ultimately leads to the classifier marking "OfType" as a type (e.g., light-blue in VS).

### PR DESCRIPTION
**Pull request by balajikris**
Fixes #1628 

Handle auto brace completion inside conditional access expressions.

### CODE REVIEW

**Comment by balajikris** [comment]
code reviewers: @brettfo @basoundr @dpoeschl @jmarolf @Pilchie @jasonmalinowski

**Comment by brettfo** [comment]
:shipit:

File: src/EditorFeatures/CSharpTest/AutomaticCompletion/AutomaticLessAndGreaterThanCompletionTests.cs [hunk 1]
```diff
@@ -135,23 +135,6 @@ public void Multiple_Nested()
...
-}";
-            using (var session = CreateSession(code))
-            {
-                Assert.NotNull(session);
-                CheckStart(session.Session, expectValidSession: false);
-            }
-        }
-
-        [Fact, Trait(Traits.Feature, Traits.Features.AutomaticCompletion)]
         public void TypeArgument_Invalid2()
```
Comment (dpoeschl) [inline src/EditorFeatures/CSharpTest/AutomaticCompletion/AutomaticLessAndGreaterThanCompletionTests.cs]: Just TypeArgument_Invalid now? The TypeArgument# tests below start on 2 as well. Weird.

File: src/EditorFeatures/CSharp/AutomaticCompletion/Sessions/LessAndGreaterThanCompletionSession.cs [hunk 2]
```diff
@@ -58,8 +59,19 @@ private bool PossibleTypeArgument(ITextSnapshot snapshot, SyntaxToken token, Can
...
 
+            // Analyze node on the left of < operator to verify if it is a generic type or method.
+            var leftNode = node.Left;
+            if (leftNode is ConditionalAccessExpressionSyntax)
+            {
+                // If node on the left is a conditional access expression, get the member binding expression 
+                // from the innermost conditional acccess expression, which is the left of < operator. 
+                // e.g: In a?.b?.c< we need to get the conditional access expression .b?.c and analyze its
+                // member binding expression (the .c) to see if it is a generic type/method.
+                leftNode = leftNode.GetInnerMostConditionalAccessExpression().WhenNotNull;
```
Comment (dpoeschl) [inline src/EditorFeatures/CSharp/AutomaticCompletion/Sessions/LessAndGreaterThanCompletionSession.cs]: Wouldn't this miss the ```a?.b?.c.d<``` case?

Comment (balajikris) [inline src/EditorFeatures/CSharp/AutomaticCompletion/Sessions/LessAndGreaterThanCompletionSession.cs]: No. that works. In that example, `GetInnerMostConditionalAccessExpression` returns `.b?.c.d` and its `WhenNotNull` member is a `SimpleMemberAccessExpression` - `.c.d` .

So long as I do not give a `ConditionalAccessExpression` (instead of the expression to right of ?.) to `GetSymbolInfo` we'll be fine.

Comment (dpoeschl) [inline src/EditorFeatures/CSharp/AutomaticCompletion/Sessions/LessAndGreaterThanCompletionSession.cs]: Ahh, yep. Thanks! :smile:

**Comment by dpoeschl** [comment]
:+1:

File: src/EditorFeatures/CSharp/AutomaticCompletion/Sessions/LessAndGreaterThanCompletionSession.cs (hunk 2 above)
Comment (balajikris) [inline src/EditorFeatures/CSharp/AutomaticCompletion/Sessions/LessAndGreaterThanCompletionSession.cs]: Added a test :satisfied:

File: src/EditorFeatures/CSharpTest/AutomaticCompletion/AutomaticLessAndGreaterThanCompletionTests.cs (hunk 1 above)
Comment (balajikris) [inline src/EditorFeatures/CSharpTest/AutomaticCompletion/AutomaticLessAndGreaterThanCompletionTests.cs]: Thanks, fixed that in the next commit.

**Comment by balajikris** [comment]
@Pilchie or @jasonmalinowski , interested in taking a look?

File: src/Workspaces/CSharp/Portable/Extensions/SyntaxNodeExtensions.cs [hunk 3]
```diff
@@ -1201,5 +1201,15 @@ public static ConditionalAccessExpressionSyntax GetParentConditionalAccessExpres
...
         }
+
+        public static ConditionalAccessExpressionSyntax GetInnerMostConditionalAccessExpression(this SyntaxNode node)
+        {
+            if (!(node is ConditionalAccessExpressionSyntax))
+            {
+                return null;
+            }
+
+            return node.DescendantNodesAndSelf().OfType<ConditionalAccessExpressionSyntax>().Last();
```
Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Extensions/SyntaxNodeExtensions.cs]: Probably not what you intended.  Consider lambdas.

```
a?.M(x => x?.P);
```

Calling this on the `ConditionalAccessExpression` for `a?.M` will return `x?.P`.

Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Extensions/SyntaxNodeExtensions.cs]: In general, be careful of using Ancestors or Descendants in expression contexts, as you might accidentally cross into a lambda.

Comment (balajikris) [inline src/Workspaces/CSharp/Portable/Extensions/SyntaxNodeExtensions.cs]: Thanks for the note @Pilchie. I'll look out for this in the future. To think that I hand wrote what i needed and then swapped it for a 1 line linq statement that isn't the same just before i sent the PR :anguished:

**Comment by Pilchie** [comment]
:+1: pending fixing `GetInnermostConditionalExpression`.
