### PR TITLE
Disallow converting a lambda with attributes to an expression tree.

### LINKED ISSUE #53910: Lambda attributes + expression trees = missing metadata
**Version Used**: 

main branch, 07.06.2021

**Steps to Reproduce**:

Compile the following code:
```
using System;
using System.Linq.Expressions;

Expression<Func<int, int>> e = [A] ([A] x) => x;

class A : Attribute { }
```

**Expected Behavior**:

Compiler error "Expression tree lambdas can't have attributes"

**Actual Behavior**:

Successful compilation, attributes are missing in metadata (since there is no method compiled from expression tree lambda).

### PR DESCRIPTION
**Pull request by AlekseyTs**
Closes #53910.

Relates to test plan https://github.com/dotnet/roslyn/issues/52192

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs [hunk 1]
```diff
@@ -5190,5 +5190,218 @@ private static LambdaSymbol GetLambdaSymbol(SemanticModel model, LambdaExpressio
         {
             return model.GetSymbolInfo(syntax).Symbol.GetSymbol<LambdaSymbol>();
         }
+
+        [Fact]
+        [WorkItem(53910, "https://github.com/dotnet/roslyn/issues/53910")]
+        public void Issue53910_01()
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs:5196]: >Issue53910 [](http://example.com/codeflow?start=20&length=10)

Perhaps name these "WithAttributesToExpressionTree" or something similar.

**Review by cston — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 2)
