### PR TITLE
Fix IDE0047: discard pattern parentheses

### LINKED ISSUE #52589: Incorrect IDE0047 Parentheses can be removed diagnostic
**Version Used**: 4e4c823

[SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMBGAsAKBQZgAJ1CBhQgb10JuKJQBZCBZACgHtgArOAYxkIAPAJSVqtCQEsAZoVaDCkqHID6w4eIk0qOLbQC+mwoZz6gA===)

```cs
using System;
public class C {
    public void M(object x) {
        if (x is (_)) // info IDE0047: Parentheses can be removed
        {
        }
    }
}
```

**Expected Behavior**: No IDE0047 diagnostic

**Actual Behavior**: IDE0047 is given, but when the user applies the fix, it introduces a compile error `error CS0246: The type or namespace name '_' could not be found` because the expression is now considered to be an "is type" expression instead of "is pattern" and old binding rules apply.

I think this scenario may be changed if @jmarolf's suggested feature to remove non-lexical contextual keywords is implemented.

### PR DESCRIPTION
**Pull request by vorotynsky**
Fixes #52589

I fixed a false positive and added some test cases.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/roslyn?pullRequest=53441) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/roslyn?pullRequest=53441) before we can accept your contribution.<br/><br/>:x: vorotynsky [sign now](https://cla.dotnetfoundation.org/dotnet/roslyn?pullRequest=53441)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/roslyn?pullRequest=53441) it.</sub>

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs [hunk 1]
```diff
@@ -689,6 +689,11 @@ public static bool CanRemoveParentheses(this ParenthesizedPatternSyntax node)
             if (pattern is ParenthesizedPatternSyntax)
                 return true;
 
+            // We're parenthesized discard pattern. We cannot remove parens.
+            // x is (_)
+            if (pattern is DiscardPatternSyntax {Parent: ParenthesizedPatternSyntax {Parent: IsPatternExpressionSyntax}})
```
Comment (Youssef1313) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs:694]:
```suggestion
            if (pattern is DiscardPatternSyntax { Parent: ParenthesizedPatternSyntax { Parent: IsPatternExpressionSyntax } })
```

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs [hunk 2]
```diff
@@ -689,6 +689,11 @@ public static bool CanRemoveParentheses(this ParenthesizedPatternSyntax node)
             if (pattern is ParenthesizedPatternSyntax)
                 return true;
 
+            // We're parenthesized discard pattern. We cannot remove parens.
+            // x is (_)
+            if (pattern is DiscardPatternSyntax { Parent: ParenthesizedPatternSyntax { Parent: IsPatternExpressionSyntax } })
```
Comment (Youssef1313) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs:694]: Isn't the `Parent` always ParenthesizedPatternSyntax since the `pattern` is coming from a `ParenthesizedPatternSyntax.Node`? This could potentially be simplified to:

```suggestion
            if (pattern is DiscardPatternSyntax { Parent: { Parent: IsPatternExpressionSyntax } })
```

**Comment by CyrusNajmabadi** [comment]
I'm fine with teh PR as is.  Will be ok merging it once you sign the CLA.  If you do want to make the changes @Youssef1313 suggests, feel free to.  once you're happy, ping me and i can merge in.

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs (hunk 2 above)
Comment (vorotynsky) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs:694]: It can't be after this because `GetOperatorPrecedence` for discard pattern returns `OperatorPrecedence.Primary`

```cs
var patternPrecedence = pattern.GetOperatorPrecedence();
if (patternPrecedence == OperatorPrecedence.Primary || patternPrecedence == OperatorPrecedence.Unary)
    return true;
```

**Comment by CyrusNajmabadi** [comment]
Thanks!
