### PR TITLE
Fixed IntelliSense suggestion for read-only class properties in object initializers 

### LINKED ISSUE #15205: IntelliSense doesn't show read-only class properties in object initializers
**Version Used**: 2015, 15

```C#
class C {
	int x;
	C P { get; } = new C {  };
}
```

Inside the last pair of braces, IntelliSense should show `P`, to allow `new C { P = { x = 2 } }` (which is completely legal).

It currently only shows writable properties and concrete collection properties.

### PR DESCRIPTION
**Pull request by zaytsev-victor**
**Customer scenario**
IntelliSense doesn't show read-only class properties in object initializers

**Bugs this fixes:**
Fixes #15205

**Risk**
Low

**Performance impact**
Low

**Is this a regression from a previous update?**
No

**How was the bug found?**
customer reported

### CODE REVIEW

**Comment by zaytsev-victor** [comment]
Please note that the fix cause a test failure (```Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Completion.CompletionProviders.ObjectInitializerCompletionProviderTests.CollectionInitializerPatternFromBaseTypeInaccessible```)

```csharp
using System;
using System.Collections;

public class SupportsAdd : IEnumerable
{
    protected void Add(int x) { }

    public IEnumerator GetEnumerator()
    {
        throw new NotImplementedException();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        throw new NotImplementedException();
    }
}

class Container
{
    public SupportsAdd S { get; }
}

class Program
{
    static void Main(string[] args)
    {
        var y = new Container { $$ };
    }
}
```
```S``` is avaliable in ```$$``` because ```var y = new Container { S = { } };``` is a legal syntax.
I'll appreciate for any suggestions how it should be handled

**Comment by rchande** [comment]
@zaytsev-victor Can you change this to only suggest properties whose type has settable properties? (Right now you're just checking to see if the property has a getter and isn't a struct, which is why that test is failing). I argue that that test should stay the same because the `SupportsAdd` type has no settable properties.

**Comment by zaytsev-victor** [comment]
@rchande
> Can you change this to only suggest properties whose type has settable properties? (Right now you're just checking to see if the property has a getter and isn't a struct, which is why that test is failing). 

But it isn't correct behavior. In this case:
```csharp
class A
{
    public B PropB { get; }
}

class B
{
    public C PropC { get; }
}

class C
{
    public int P { get; set; }
}

class Test
{
    void M()
    {
        var a = new A { PropB = { PropC = { P = 1 } } };
    }
}
```

Class ```B``` hasn't settable properties, but ```C``` has, so we should show ```PropB```. The question is how deep we should analyze it?

**Comment by rchande** [comment]
@zaytsev-victor I think we (you :) ) should search the types of properties until you find something with a writable property as described in https://github.com/dotnet/roslyn/issues/15205#issuecomment-317021438. If this causes performance problems, we can always switch back to something less precise like you have implemented now. Does that seem reasonable?

**Comment by zaytsev-victor** [comment]
@rchande yes, sure. I just hope I didn't remove this part from stash :)

**Comment by sharwell** [comment]
I lean in favor of showing all accessible fields and properties, except where the declaration would prevent the use of this syntax. Specifically:

* If the member returns a reference type (including array types), then always show it
* If the member returns a pointer to a value type, then show it unless the member is a `readonly` field
* If the member returns a reference to a value type, then do not show it
* If the member is any other value type, then only show it if the member is a field which is *not* marked `readonly`

Since we're not providing consistent feedback right now, I'll talk with @rchande and @Pilchie today or very soon to find a resolution.

**Comment by zaytsev-victor** [comment]
@sharwell do you have any update on this?

**Comment by sharwell** [comment]
@SLaks If you could code review this as well, it would be greatly appreciated 👍

**Comment by SLaks** [comment]
> If the member returns a reference type (including array types), then always show it
Why show a readonly array-typed property?

File: src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs [hunk 1]
```diff
@@ -96,5 +88,42 @@ protected virtual bool IsInitializable(ISymbol member, INamedTypeSymbol containi
                 member.MatchesKind(SymbolKind.Field, SymbolKind.Property) &&
                 member.IsAccessibleWithin(containingType);
         }
+
+        private static bool CanSupportObjectInitializer(ISymbol symbol, ISymbol within)
+        {
+            if (symbol is IPropertySymbol propertySymbol)
```
Comment (SLaks) [inline src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs]: This same logic should apply to fields too.

File: src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs [hunk 2]
```diff
@@ -96,5 +88,42 @@ protected virtual bool IsInitializable(ISymbol member, INamedTypeSymbol containi
...
+            {
+                return propertySymbol.GetMethod != null && !propertySymbol.Type.IsStructType() && HasAccesseblePropertiesOrFields(propertySymbol.Type, within);
+            }
+
+            return false;
+        }
+
+        private static bool HasAccesseblePropertiesOrFields(ITypeSymbol type, ISymbol within)
```
Comment (SLaks) [inline src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs]: Typo: Accessible

File: src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs [hunk 3]
```diff
@@ -96,5 +88,42 @@ protected virtual bool IsInitializable(ISymbol member, INamedTypeSymbol containi
...
+                    .Any(member => member.IsWriteableFieldOrProperty() || 
+                            CanSupportCollectionInitializer(member, within) || 
+                            HasAccesseblePropertiesOrFields(member.GetMemberType(), alreadyCheckedTypes));
+            }
+        }
+
+        private static bool CanSupportCollectionInitializer(ISymbol symbol, ISymbol within)
+        {
+            var type = symbol.GetMemberType();
+            return type != null && type.CanSupportCollectionInitializer(within);
```
Comment (SLaks) [inline src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs]: Optional:

=> symbol.GetMemberType()?.CanSupportCollectionInitializer(within) ?? false;

File: src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs (hunk 2 above)
Comment (SLaks) [inline src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs]: Since it also checks for CanSupportCollectionInitializer, this should be named HasObjectInitializableMembers() or similar.

File: src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs [hunk 4]
```diff
@@ -77,15 +77,7 @@ protected override Task<CompletionDescription> GetDescriptionWorkerAsync(Documen
...
-        {
-            var type = symbol.GetMemberType();
-            if (type != null && type.CanSupportCollectionInitializer(within))
-            {
-                return true;
-            }
-
-            return symbol.IsWriteableFieldOrProperty();
-        }
+            => CanSupportCollectionInitializer(symbol, within) || symbol.IsWriteableFieldOrProperty() || CanSupportObjectInitializer(symbol, within);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs]: symbol.IsWriteableFieldOrProperty() should probably go first.

File: src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs [hunk 5]
```diff
@@ -96,5 +88,42 @@ protected virtual bool IsInitializable(ISymbol member, INamedTypeSymbol containi
                 member.MatchesKind(SymbolKind.Field, SymbolKind.Property) &&
                 member.IsAccessibleWithin(containingType);
         }
+
+        private static bool CanSupportObjectInitializer(ISymbol symbol, ISymbol within)
+        {
+            if (symbol is IPropertySymbol propertySymbol)
+            {
+                return propertySymbol.GetMethod != null && !propertySymbol.Type.IsStructType() && HasAccesseblePropertiesOrFields(propertySymbol.Type, within);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs]: "Accesseble"

File: src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs [hunk 6]
```diff
@@ -96,5 +88,42 @@ protected virtual bool IsInitializable(ISymbol member, INamedTypeSymbol containi
...
+        }
+
+        private static bool HasAccesseblePropertiesOrFields(ITypeSymbol type, ISymbol within)
+        {
+            var types = new HashSet<ITypeSymbol>();
+            return HasAccesseblePropertiesOrFields(type, types);
+
+            bool HasAccesseblePropertiesOrFields(ITypeSymbol typeToCheck, HashSet<ITypeSymbol> alreadyCheckedTypes)
+            {
+                if (alreadyCheckedTypes.Contains(typeToCheck))
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs]: simpler:

```c#
if (!alreadyCheckedTypes.Add(typeToCheck)) {
    return;
}
```

File: src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs [hunk 7]
```diff
@@ -96,5 +88,42 @@ protected virtual bool IsInitializable(ISymbol member, INamedTypeSymbol containi
...
+
+            return false;
+        }
+
+        private static bool HasAccesseblePropertiesOrFields(ITypeSymbol type, ISymbol within)
+        {
+            var types = new HashSet<ITypeSymbol>();
+            return HasAccesseblePropertiesOrFields(type, types);
+
+            bool HasAccesseblePropertiesOrFields(ITypeSymbol typeToCheck, HashSet<ITypeSymbol> alreadyCheckedTypes)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs]: consider renaming alreadyCheckedTypes to "visited"

**Comment by sharwell** [comment]
> Why show a readonly array-typed property?

@SLaks Because this:

```
using System;
using System.Linq;

class C {
	int x;
	public C P { get => new C { Data = { [0] = 5 } }; }
  public int[] Data { get; } = { 3, 4 };
}

public class Program
{
  public static void Main()
  {
    Console.WriteLine(new C().Data[0]);
    Console.WriteLine(new C().P.Data[0]);
  }
}
```

**Comment by sharwell** [comment]
I'm going to take this through our new design review process and based on that we'll have a clear direction to proceed.

**Comment by sharwell** [comment]
@zaytsev-victor The team agreed that code completion should offer items that are potentially valid, even if the syntax for use is not widely known. I need to go back through this pull request and see if there are any cases we left out.

File: src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs (hunk 2 above)
Comment (sharwell) [reply src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs]: 📝 This test can be removed altogether. Empty braces are allowed for the initializer even if no members are accessible.

File: src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs (hunk 3 above)
Comment (sharwell) [reply src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs]: 📝 The collection initializer check is unnecessary. All objects supporting collection initialization also support object initializer syntax using empty braces.

File: src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs (hunk 2 above)
Comment (sharwell) [reply src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs]: 📝 Accessibility does not need to be checked to determine whether the syntax is allowed.

**Comment by sharwell** [comment]
@jinujoseph Requesting this goes into 16.0 Preview 1. It's extremely obvious when working with the Microsoft.CodeAnalysis.Testing library following dotnet/roslyn-sdk#198.

**Comment by jinujoseph** [comment]
Can you retarget this to dotnet:dev16.0.x pls

File: src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs (hunk 2 above)
Comment (zaytsev-victor) [reply src/Features/Core/Portable/Completion/Providers/AbstractObjectInitializerCompletionProvider.cs]: @sharwell so we'll show the suggestion for all valid syntax (even if no settable properties/fields)?

**Comment by jinujoseph** [comment]
test ubuntu_16_debug_prtest

**Comment by dpoeschl** [comment]
retest ubuntu_16_debug_prtest please
