### PR TITLE
Fixing a compat issue with invoking properties on generic type parameters in expression trees.

### LINKED ISSUE #4471: Implicit conversions to interfaces are not present in expression trees.
The following expressions should result in a same shape of expression tree:

```C#
interface IDeletedID
{
    int DeletedID { get; }
}

class C1 : IDeletedID
{
    int IDeletedID.DeletedID
    {
        get
        {
            return 1;
        }
    }
}

    static void M<T>(T x) where T : IDeletedID
    {
        Expression<Func<bool>> expr1 = () => ((IDeletedID)x).DeletedID == 1;
        Expression<Func<bool>> expr2 = () => (x).DeletedID == 1;
    }
```

Cast to (IDeletedID) subtly changes the meaning of the expression. If, for example, x happens to be a struct, the cast will result in boxing and "DeletedID" will be called on a copy.

Old compiler inserts casts like this in the expression tree. Roslyn does not. 
From execution semantics, the cast should not be there, however the change is observable when traversing the tree and there are known breaks because of this.

Should we try inserting these casts for compat reasons?

### PR DESCRIPTION
**Pull request by VSadov**
Fixing a compat issue with invoking properties on generic type parameters in expression trees.

While the casts inserted by the old compiler are not strictly correct, the conditions under which they are observable are extremely narrow:
We would have to deal with a generic T receiver which is actually a struct that implements a property form an interface and the implementation of the getter must make observable mutations to the instance.

At this point it seems more appropriate to continue adding these casts.

Fixes #4471

### CODE REVIEW

**Comment by VSadov** [comment]
@gafter @AlekseyTs @agocke @jaredpar - please review

**Comment by VSadov** [comment]
@dotnet-bot test this please

File: src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/ExpressionLambdaRewriter.cs [hunk 1]
```diff
@@ -923,6 +923,23 @@ private BoundExpression VisitPropertyAccess(BoundPropertyAccess node)
...
+            //         there are known dependencies on this kind of tree shape.
+            //
+            //         While the casts are semantically incorrect, the conditions
+            //         under which they are observable are extremely narrow:
+            //         We would have to deal with a generic T receiver which is actually a struct
+            //         that implements a property form an interface and 
+            //         the implementation of the getter must make observable mutations to the instance.
+            //
+            //         At this point it seems more appropriate to continue adding these casts.
+            if (node.ReceiverOpt?.Type.IsTypeParameter() == true)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/ExpressionLambdaRewriter.cs]: Is ```== true``` redundant here?

**Comment by AlekseyTs** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/ExpressionLambdaRewriter.cs (hunk 1 above)
Comment (VSadov) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/ExpressionLambdaRewriter.cs]: because of  ?.  we have bool? here, so we need == true

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/ExpressionLambdaRewriter.cs]: I see, it is not needed in VB :-)

Comment (VSadov) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/ExpressionLambdaRewriter.cs]: It is a bit awkward, but as I understand it would be ambiguous otherwise. 
The codegen should optimize this into a null check on ReceiverOpt and regular branch on the result (no nullables will be really involved).

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/ExpressionLambdaRewriter.cs]: VB has a special rule about converting Boolean? to Boolean in context of a conditional expression, if I remember correctly, it gets translated into GetValueOrDefault. I don't think there is a big difference in codegen here, just thought C# had similar rule too.
