### PR TITLE
Fix IEventAssignmentExpression

### LINKED ISSUE #8346: `IEventAssignmentExpression` should contains an `IEventReferenceExpression`
Right now, it is defined to directly contain event symbol and event instance. @JohnHamby mentioned this is intentional since the bound tree makes it difficult to provide operation this way. We need to spend a little more time to decide if this is possible to fix.

Update with proposed interface:

```cs

    /// <summary>
    /// Represents a binding of an event.
    /// </summary>
    /// <remarks>
    /// This interface is reserved for implementation by its associated APIs. We reserve the right to
    /// change it in the future.
    /// </remarks>
    public interface IEventAssignmentExpression : IOperation
    {
        /// <summary>
        /// Event being bound.
        /// </summary>
        IEventReferenceExpression Event { get; }
 
        /// <summary>
        /// Handler supplied for the event.
        /// </summary>
        IOperation HandlerValue { get; }
 
        /// <summary>
        /// True for adding a binding, false for removing one.
        /// </summary>
        bool Adds { get; }
    }
```

### PR DESCRIPTION
**Pull request by genlu**
Fix #8346

Replaced the event symbol in `IEventAssignmentExpression` with `IEventReferenceExpression`
```cs

    /// <summary>
    /// Represents a binding of an event.
    /// </summary>
    /// <remarks>
    /// This interface is reserved for implementation by its associated APIs. We reserve the right to
    /// change it in the future.
    /// </remarks>
    public interface IEventAssignmentExpression : IOperation
    {
        /// <summary>
        /// Reference to the event being bound.
        /// </summary>
        IEventReferenceExpression EventReference { get; }
 
        /// <summary>
        /// Handler supplied for the event.
        /// </summary>
        IOperation HandlerValue { get; }
 
        /// <summary>
        /// True for adding a binding, false for removing one.
        /// </summary>
        bool Adds { get; }
    }
```

Note that for C#, the bound node doesn't contain the syntax for the event reference, even though it was provided during binding. Because of this, the syntax of entire event assignment expression is used for the syntax event reference operation, just so I can get the interface change done first. To address this issue, we probably need to at least change `BoundEventAssignmentOperator`.

@dotnet/analyzer-ioperation @cston @jcouv

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs [hunk 1]
```diff
@@ -351,14 +351,26 @@ private IEventReferenceExpression CreateBoundEventAccessOperation(BoundEventAcce
...
         private IEventAssignmentExpression CreateBoundEventAssignmentOperatorOperation(BoundEventAssignmentOperator boundEventAssignmentOperator)
         {
-            IEventSymbol @event = boundEventAssignmentOperator.Event;
-            Lazy<IOperation> eventInstance = new Lazy<IOperation>(() => Create(boundEventAssignmentOperator.Event.IsStatic ? null : boundEventAssignmentOperator.ReceiverOpt));
+            SyntaxNode syntax = boundEventAssignmentOperator.Syntax;
+            Lazy<IEventReferenceExpression> eventReference = new Lazy<IEventReferenceExpression>(() =>
+            {
+                IEventSymbol @event = boundEventAssignmentOperator.Event;
+                Lazy<IOperation> instance = new Lazy<IOperation>(() => Create(boundEventAssignmentOperator.Event.IsStatic ? null : boundEventAssignmentOperator.ReceiverOpt));
+                ISymbol member = boundEventAssignmentOperator.Event;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: `member` is not used.

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs [hunk 2]
```diff
@@ -351,14 +351,26 @@ private IEventReferenceExpression CreateBoundEventAccessOperation(BoundEventAcce
...
+                // BoundEventAssignmentOperator doesn't hold on to all the data from the provided BoundEventAccess during binding.
+                // Based on the implementation of those two bound node types, the following data can be retieved w/o changing BoundEventAssignmentOperator:
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: `retrieved`?

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb [hunk 3]
```diff
@@ -408,20 +408,16 @@ Namespace Microsoft.CodeAnalysis.Semantics
...
         Private Function GetRemoveStatementExpression(statement As BoundRemoveHandlerStatement) As IOperation
             Dim eventAccess As BoundEventAccess = TryCast(statement.EventAccess, BoundEventAccess)
-            Dim [event] As IEventSymbol = eventAccess?.EventSymbol
-            Dim instance = If([event] Is Nothing OrElse [event].IsStatic, Nothing, If(eventAccess IsNot Nothing, Create(eventAccess.ReceiverOpt), Nothing))
-
+            Dim eventReference = If(eventAccess Is Nothing, Nothing, CreateBoundEventAccessOperation(eventAccess))
             Return New EventAssignmentExpression(
-                [event], instance, Create(statement.Handler), adds:=False, syntax:=statement.Syntax, type:=Nothing, constantValue:=Nothing)
+                eventReference, Create(statement.Handler), adds:=False, syntax:=statement.Syntax, type:=Nothing, constantValue:=Nothing)
         End Function
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: These two methods look identical. Can they be replaced by a single `GetAddOrRemoveHandlerStatementExpression`?

File: src/Compilers/VisualBasic/Test/Semantic/IOperation/IOperationTests_IEventAssignmentExpression.vb [hunk 4]
```diff
@@ -0,0 +1,173 @@
...
+            Dim source = <![CDATA[
+Imports System
+
+Class TestClass
+    
+    Event TestEvent As Action
+
+    Sub Add(receiver As TestClass)
+        AddHandler TestEvent, AddressOf M'BIND:"AddHandler TestEvent, AddressOf M"
+    End Sub
```
Comment (cston) [inline src/Compilers/VisualBasic/Test/Semantic/IOperation/IOperationTests_IEventAssignmentExpression.vb]: `receiver` is not used in these tests.

**Comment by mavasani** [comment]
> Because of this, the syntax of entire event assignment expression is used for the syntax event reference operation, just so I can get the interface change done first. To address this issue, we probably need to at least change BoundEventAssignmentOperator

I think we should do this change in this PR. Is it non-trivial to change the bound node?

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs [hunk 5]
```diff
@@ -351,14 +351,26 @@ private IEventReferenceExpression CreateBoundEventAccessOperation(BoundEventAcce
...
+                //  1. The type of BoundEventAccess is the type of the event symbol.
+                //  2. the constant value of BoundEventAccess is always null.
+                // However, we can't reliably get the syntax node for the BoundEventAccess w/o changing BoundEventAssignmentOperator, so the syntax of entire
+                // BoundEventAssignmentOperator is used instead.
```
Comment (mavasani) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: Can we cast the syntax to AssignmentOperatorSyntax and use the Left/Target field of this syntax node? This way the correct syntax will be used, and we can optimize the implementation as per your comments later. Also, please file a bug for this TODO.

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs [hunk 6]
```diff
@@ -351,14 +351,26 @@ private IEventReferenceExpression CreateBoundEventAccessOperation(BoundEventAcce
 
         private IEventAssignmentExpression CreateBoundEventAssignmentOperatorOperation(BoundEventAssignmentOperator boundEventAssignmentOperator)
         {
-            IEventSymbol @event = boundEventAssignmentOperator.Event;
-            Lazy<IOperation> eventInstance = new Lazy<IOperation>(() => Create(boundEventAssignmentOperator.Event.IsStatic ? null : boundEventAssignmentOperator.ReceiverOpt));
+            SyntaxNode syntax = boundEventAssignmentOperator.Syntax;
+            Lazy<IEventReferenceExpression> eventReference = new Lazy<IEventReferenceExpression>(() =>
+            {
+                IEventSymbol @event = boundEventAssignmentOperator.Event;
+                Lazy<IOperation> instance = new Lazy<IOperation>(() => Create(boundEventAssignmentOperator.Event.IsStatic ? null : boundEventAssignmentOperator.ReceiverOpt));
```
Comment (mavasani) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: Do we need the conditional expression here, i.e. is there a case where event is static but ReceiverOpt is non-null?

**Comment by genlu** [comment]
@mavasani I think there's a few options:
1. The simplest way to fix the syntax of newly added `EventReference` is to add a field in `BoundEventAssignmentOperator` just for the syntax of `BoundEventAccess`.
2. similar to the one above, we can capture the entire `BoundEventAccess`, but keep binding/lowering process unchanged.
3. This is the approach I prefer, we can "un-lower" the `BoundEventAssignmentOperator` so it contains `BoundEventAccess` when exposed to us, and modify rewriter to do the lowering logic currently resides in binder. But I'm not sure if this would affect other things, like perf, etc.

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs (hunk 6 above)
Comment (genlu) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: Good point, will fix.

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs (hunk 5 above)
Comment (genlu) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: If the syntax from left can be guaranteed to be correct, then I guess we can do w/o changing bound node after all.

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs (hunk 6 above)
Comment (genlu) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: Actually, it seems the conditional is necessary, since the receiver will not be null for static event reference:
http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Binder/Binder_Expressions.cs,5809

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs (hunk 5 above)
Comment (genlu) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: A closer look suggests that the syntax can only be `AssignmentOperatorSyntax` for a `BoundEventAssignmentOperator`. There's no need to change bound node then.

**Comment by genlu** [comment]
ping... @mavasani @cston @jcouv

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb [hunk 7]
```diff
@@ -406,22 +406,12 @@ Namespace Microsoft.CodeAnalysis.Semantics
...
-                        [event], instance, Create(statement.Handler), adds:=True, syntax:=statement.Syntax, type:=Nothing, constantValue:=Nothing)
-        End Function
-
-        Private Function GetRemoveStatementExpression(statement As BoundRemoveHandlerStatement) As IOperation
-            Dim eventAccess As BoundEventAccess = TryCast(statement.EventAccess, BoundEventAccess)
-            Dim [event] As IEventSymbol = eventAccess?.EventSymbol
-            Dim instance = If([event] Is Nothing OrElse [event].IsStatic, Nothing, If(eventAccess IsNot Nothing, Create(eventAccess.ReceiverOpt), Nothing))
-
+            Dim eventReference = If(eventAccess Is Nothing, Nothing, CreateBoundEventAccessOperation(eventAccess))
+            Dim adds = TypeOf statement Is BoundAddHandlerStatement
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: `Dim adds = statement.Kind = BoundKind.AddHandlerStatement`

File: src/Test/Utilities/Portable/Diagnostics/OperationTestAnalyzer.cs [hunk 8]
```diff
@@ -1060,9 +1060,9 @@ public sealed override void Initialize(AnalysisContext context)
                      IEventAssignmentExpression eventAssignment = (IEventAssignmentExpression)operationContext.Operation;
                      operationContext.ReportDiagnostic(Diagnostic.Create(eventAssignment.Adds ? HandlerAddedDescriptor : HandlerRemovedDescriptor, operationContext.Operation.Syntax.GetLocation()));
 
-                     if (eventAssignment.Event == null)
+                     if (eventAssignment.EventReference?.Event == null)
                      {
-                         if (eventAssignment.EventInstance == null && eventAssignment.HasErrors(operationContext.Compilation, operationContext.CancellationToken))
+                         if (eventAssignment.EventReference?.Instance == null && eventAssignment.HasErrors(operationContext.Compilation, operationContext.CancellationToken))
                          {
                              // report inside after checking for null to make sure it does't crash.
```
Comment (cston) [inline src/Test/Utilities/Portable/Diagnostics/OperationTestAnalyzer.cs]: Typo: `doesn't`

File: src/Test/Utilities/Portable/Diagnostics/OperationTestAnalyzer.cs [hunk 9]
```diff
@@ -1060,9 +1060,9 @@ public sealed override void Initialize(AnalysisContext context)
                      IEventAssignmentExpression eventAssignment = (IEventAssignmentExpression)operationContext.Operation;
                      operationContext.ReportDiagnostic(Diagnostic.Create(eventAssignment.Adds ? HandlerAddedDescriptor : HandlerRemovedDescriptor, operationContext.Operation.Syntax.GetLocation()));
 
-                     if (eventAssignment.Event == null)
+                     if (eventAssignment.EventReference?.Event == null)
                      {
-                         if (eventAssignment.EventInstance == null && eventAssignment.HasErrors(operationContext.Compilation, operationContext.CancellationToken))
+                         if (eventAssignment.EventReference?.Instance == null && eventAssignment.HasErrors(operationContext.Compilation, operationContext.CancellationToken))
```
Comment (cston) [inline src/Test/Utilities/Portable/Diagnostics/OperationTestAnalyzer.cs]: When are both `EventReference?.Event == null` and `EventReference?.Instance == null`? Is that only when `EventReference == null`? If so, consider checking that instead.

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IForLoopStatement.cs [hunk 10]
```diff
@@ -1247,24 +1247,24 @@ public void Next()
 string expectedOperationTree = @"
 IForLoopStatement (LoopKind.For) (OperationKind.LoopStatement) (Syntax: 'for (d.Init ... }')
   Condition: IUnaryOperatorExpression (UnaryOperationKind.DynamicTrue) (OperationKind.UnaryOperatorExpression, Type: System.Boolean) (Syntax: 'd.Done')
-      Operand: IOperation:  (OperationKind.None) (Syntax: 'd.Done')
```
Comment (genlu) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IForLoopStatement.cs]: @jinujoseph This seems to be caused by two PRs merged around the same time w/o running tests on up-to-date code?

**Comment by genlu** [comment]
Ping @mavasani @dotnet/roslyn-compiler

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs [hunk 11]
```diff
@@ -355,14 +356,26 @@ private IEventReferenceExpression CreateBoundEventAccessOperation(BoundEventAcce
...
+            SyntaxNode syntax = boundEventAssignmentOperator.Syntax;
+            Lazy<IEventReferenceExpression> eventReference = new Lazy<IEventReferenceExpression>(() =>
+            {
+                // BoundEventAssignmentOperator doesn't hold on to BoundEventAccess provided during binding.
+                // Based on the implementation of those two bound node types, the following data can be retrieved w/o changing BoundEventAssignmentOperator:
+                //  1. the type of BoundEventAccess is the type of the event symbol.
+                //  2. the constant value of BoundEventAccess is always null.
+                //  3. the syntax of the boundEventAssignmentOperator is always AssignmentExpressionSyntax, so the syntax for the event reference would be the LHS of the assignment.
+                IEventSymbol @event = boundEventAssignmentOperator.Event;
+                Lazy<IOperation> instance = new Lazy<IOperation>(() => Create(boundEventAssignmentOperator.Event.IsStatic ? null : boundEventAssignmentOperator.ReceiverOpt));
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: We should include the receiver in the `static` case as well, so the consumer can walk the entire expression even in an error scenario.

Comment (genlu) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: Good point. I have made the change for both C# and VB (and I noticed in test that adding handler to static event through an instance is not an error in VB.

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IEventAssignmentExpression.cs [hunk 12]
```diff
@@ -0,0 +1,250 @@
...
+                // file.cs(6,31): warning CS0067: The event 'Test.MyEvent' is never used
+                //     public event EventHandler MyEvent;
+                Diagnostic(ErrorCode.WRN_UnreferencedEvent, "MyEvent").WithArguments("Test.MyEvent").WithLocation(6, 31)
+            };
+
+            VerifyOperationTreeAndDiagnosticsForTest<AssignmentExpressionSyntax>(source, expectedOperationTree, expectedDiagnostics);
+        }
+
+        [Fact]
+        public void AddEventHandler_AssignToStaticEventOnInstance()
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IEventAssignmentExpression.cs]: For completeness, please test a reference to a instance event without a receiver, and test the same two cases in VB.

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs (hunk 11 above)
Comment (genlu) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: As I just mentioned offline, making this change causes us to return a `None` operation as the instance derived from a `BoundTypeExpression` as `BoundEventAssignmentOperator.ReceiverOpt`. If we want to expose as much information as possible in erroneous case, we will need to accurately check for error when creating the `EventReferenceOperation` plus modify the interface definition to make it clear that instance could be non null in this case. We probably discuss this during our design meeting.

Meanwhile, I 'm gonna revert this change (but keep those tests) to make the behavior consistent with other related operations, e.g.:
https://github.com/dotnet/roslyn/blob/features/ioperation/src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs#L306

Is this OK?

Comment (cston) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: Yes, we should have consistent behavior for related operations. It sounds reasonable to revert the change for now while we discuss overall approach.

Comment (genlu) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: By the way, there's alsoready an issue tracking the `BoundTypeExpression` issue:
https://github.com/dotnet/roslyn/issues/8909

**Comment by cston** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs [hunk 13]
```diff
@@ -355,14 +356,26 @@ private IEventReferenceExpression CreateBoundEventAccessOperation(BoundEventAcce
 
         private IEventAssignmentExpression CreateBoundEventAssignmentOperatorOperation(BoundEventAssignmentOperator boundEventAssignmentOperator)
         {
-            IEventSymbol @event = boundEventAssignmentOperator.Event;
-            Lazy<IOperation> eventInstance = new Lazy<IOperation>(() => Create(boundEventAssignmentOperator.Event.IsStatic ? null : boundEventAssignmentOperator.ReceiverOpt));
+            SyntaxNode syntax = boundEventAssignmentOperator.Syntax;
+            Lazy<IEventReferenceExpression> eventReference = new Lazy<IEventReferenceExpression>(() =>
```
Comment (mavasani) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory.cs]: Can you refactor this into a separate method `CreateBoundEventReferenceExpressionOperation`?

**Comment by genlu** [comment]
Can I get another review from @dotnet/roslyn-compiler?

**Comment by jcouv** [comment]
Looking now.

File: src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IEventAssignmentExpression.cs [hunk 14]
```diff
@@ -0,0 +1,328 @@
+﻿// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
+
+using Microsoft.CodeAnalysis.CSharp.Syntax;
+using Roslyn.Test.Utilities;
+using Xunit;
+
+namespace Microsoft.CodeAnalysis.CSharp.UnitTests
+{
+    public partial class IOperationTests : SemanticModelTestBase
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IEventAssignmentExpression.cs]: There should be a trait to tag IOperation tests, if there isn't one already.
Something like `[CompilerTrait(CompilerFeature.Tuples)]`

Comment (genlu) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IEventAssignmentExpression.cs]: @dotnet/analyzer-ioperation Do we have this already? I don't see it in existing tests. I can create one in a separate PR if not.

Comment (jinujoseph) [inline src/Compilers/CSharp/Test/Semantic/IOperation/IOperationTests_IEventAssignmentExpression.cs]: No we don't ...there is a issue tracking this https://github.com/dotnet/roslyn/issues/20652

**Comment by genlu** [comment]
@dotnet/roslyn-infrastructure Linux builds are failing with following error, any ideas?
https://ci.dot.net/job/dotnet_roslyn/job/features_ioperation/job/ubuntu_14_debug_prtest/385/

```
9:25:16 + ./cibuild.sh --nocache --debug
09:25:16 Runs our integration suite on Linux
09:25:16 usage: cibuild.sh [options]
09:25:16 
09:25:16 Options
09:25:16   --debug               Build Debug (default)
09:25:16   --release             Build Release
09:25:16   --cleanrun            Clean the project before building
09:25:16   --skiptest            Do not run tests
09:25:16   --skipcommitprinting  Do not print commit information
09:25:17 Build step 'Execute shell' marked build as failure
```

**Comment by jasonmalinowski** [comment]
@brettfo Is this something we just need to take another merge for?
