### PR TITLE
Reduce allocations in DeclarationTable.RootNamespaceLocationComparer.Compare

### LINKED ISSUE #23464: Investigate allocation reduction in RootNamespaceLocationComparer
**Version Used**: 2b39919ba6eebb6b22524db11a537fe247ee8a79

**Steps to Reproduce**:

Use AnalyzerRunner to run CSharpFeatures analyzers on Orchard.sln.

**Result**:

329MB (1.7% overall) allocations occur in `DeclarationTable.RootNamespaceLocationComparer.Compare`, due to allocations of `SourceLocation`. Allocations of this object were substantially reduced in the work to resolve #23427, and this is the remaining hot path case.

### PR DESCRIPTION
**Pull request by sharwell**
### Customer scenario

Running analyzer during a build is slower than it should be, with the analyzer driver contributing substantial overhead even when the analyzers themselves are lightweight.

### Bugs this fixes

Fixes #23464

### Workarounds, if any

None needed

### Risk

This poses a small maintainability risk by duplicating an existing algorithm into a new form for the sole benefit of reducing allocations. The risk is mitigated by a comment explaining the new constraint, and justified by AnalyzerRunner indicating the code lies on a particularly hot path.

### Performance impact

2% reduction in allocations for running IDE analyzers.

### Is this a regression from a previous update?

No.

### Root cause analysis

AnalyzerRunner is a new tool for helping us test analyzer performance in isolation.

### How was the bug found?

AnalyzerRunner.

### Test documentation updated?

No.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Declarations/DeclarationTable.cs [hunk 1]
```diff
@@ -150,7 +150,7 @@ internal RootNamespaceLocationComparer(CSharpCompilation compilation)
 
             public int Compare(SingleNamespaceDeclaration x, SingleNamespaceDeclaration y)
             {
-                return _compilation.CompareSourceLocations(x.Location, y.Location);
+                return _compilation.CompareSourceLocations(x.SyntaxReference, y.SyntaxReference);
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Declarations/DeclarationTable.cs]: sorry, how does thsi cahnge anything for C#?  It looks like CompareSourceLocations does the exact same thing with Locations.

**Comment by CyrusNajmabadi** [comment]
Could you explain what the bad path was before, and how it is avoided now?  thanks!

File: src/Compilers/CSharp/Portable/Declarations/DeclarationTable.cs (hunk 1 above)
Comment (sharwell) [reply src/Compilers/CSharp/Portable/Declarations/DeclarationTable.cs]: :arrow_right: The `Location` property allocates a `SourceLocation` object each time it is accessed.

Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Portable/Declarations/DeclarationTable.cs]: Oh ick.  Ok, your change should def be better.  However, given how often locations are accessed (including from declarations by symbols), might we not want to also just cache this Location object?  Seems like that would also suitably help, and also benefit all the other callers that use .Location.

Comment (sharwell) [reply src/Compilers/CSharp/Portable/Declarations/DeclarationTable.cs]: I'm concerned the memory overhead by widespread caching of these objects could be problematic in other ways. This seems like the safe option for now.

Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Portable/Declarations/DeclarationTable.cs]: It shouldn't be.  We've added information to declarations very cheaply in the past.  It's worth noting that they only correspond to the namespaces+sourcetypes in your system.  So there are very few of them, compared to many other types of instances in our system.  On top of that, they're *heavily* shared in the most important typing paths.  All but the declarations for your file will be reused on each edit, making the allocations only usually a handful per edit per file.

**Comment by sharwell** [comment]
@dotnet/roslyn-compiler for review

@Pilchie for ask mode

File: src/Compilers/CSharp/Portable/Declarations/DeclarationTable.cs [hunk 2]
```diff
@@ -148,9 +148,12 @@ internal RootNamespaceLocationComparer(CSharpCompilation compilation)
                 _compilation = compilation;
             }
 
+            [PerformanceSensitive(
+                "https://github.com/dotnet/roslyn/issues/23582",
+                Constraint = "Avoid " + nameof(SingleNamespaceOrTypeDeclaration.Location) + " since it has a costly allocation on this fast path.")]
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Declarations/DeclarationTable.cs]: Why an attribute rather than a comment?

Comment (sharwell) [reply src/Compilers/CSharp/Portable/Declarations/DeclarationTable.cs]: ➡️ The attribute is capable of driving analyzers to prevent regressions. Aside from the initial benefit of enforcing that the first parameter is a valid URI, one example that I figured out already is dotnet/roslyn-analyzers#1439. I haven't figured out a general form for "prevent access to [some specific item]", so I used the general purpose `Constraint` property here for now.

**Comment by Pilchie** [comment]
Please tag again with appropriate code review signoffs completed.

**Comment by sharwell** [comment]
@Pilchie again 😄
