### PR TITLE
Fixed #18763 Compiler crash on bad code in the IDE

### LINKED ISSUE #18763: Compiler crash on bad code in the IDE
**Version Used**: VS 2017 (also reproducible with VS 2015)

**Steps to Reproduce**:

1. Open a new Console Application
2. Paste the following code into the main class
``` c#
[X(() => this._Y)]
public void Z()
{
}
```
3. Move the mouse over `this`

**Expected Behavior**:

Some error message.

**Actual Behavior**:

Visual Studio crashes.

-----------------------------------

Possible stack trace:
``` none
System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.AddUnwrappingErrorTypes(ArrayBuilder`1 builder, Symbol s)
at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoForNode(SymbolInfoOptions options, BoundNode lowestBoundNode, BoundNode highestBoundNode, BoundNode boundNodeForSyntacticParent, Binder binderOpt)
at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoFromNode(SyntaxNode node, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoCore(SyntaxNode node, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.Shared.Extensions.SemanticModelExtensions.GetSemanticInfo(SemanticModel semanticModel, ISemanticFactsService semanticFacts, ISyntaxFactsService syntaxFacts, SyntaxToken token, CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.Shared.Extensions.SemanticModelExtensions.GetSemanticInfo(SemanticModel semanticModel, SyntaxToken token, Workspace workspace, CancellationToken cancellationToken)
```

-----------------------------------
Also recorded internally at
- https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?_a=edit&id=406701
- https://vsfeedback/comment/844007

### PR DESCRIPTION
**Pull request by brianhartung**
(First time contributor)

Fixes #18763

Customer scenario
Visual Studio crashes when hovering over invalid code in IDE.

Bugs this fixes:
#18763

Workarounds, if any
None

Risk
Low

Performance impact
Low (additional null check, no new allocations)

Is this a regression from a previous update?
No

Root cause analysis:
In CSharpSemanticModel method AddUnwrappingErrorTypes an existing null check failed to consider a null value on a child member access inside the body of the protected block.

How was the bug found?
Customer Reported

@jaredpar

### CODE REVIEW

**Comment by brianhartung** [comment]
All tests pass if I run them locally but the first PR test above fails with the "xunit produced no error output but had exit code 1" error that's been referenced on and off for the last couple of years.

I've tried twice and get the same result. It was such a simple fix for this issue that I tend to suspect this is not related to the change itself. Not sure what to do at this point...any chance someone can help take a look at this? Thanks in advance!

**Comment by agocke** [comment]
I'd expect a compiler unit test to be added to verify this change.

**Comment by agocke** [comment]
Specifically, I'd expect an additional test in src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetSemanticInfoTests.cs

File: src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs [hunk 1]
```diff
@@ -1852,7 +1852,7 @@ private bool IsInTypeofExpression(int position)
         private static void AddUnwrappingErrorTypes(ArrayBuilder<Symbol> builder, Symbol s)
         {
             var originalErrorSymbol = s.OriginalDefinition as ErrorTypeSymbol;
-            if ((object)originalErrorSymbol != null)
+            if ((object)originalErrorSymbol != null && originalErrorSymbol.CandidateSymbols != null)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs]: `ErrorTypeSymbol.CandidateSymbols` should return `ImmutableArray<Symbol>.Empty` rather than `default(ImmutableArray<Symbol>)`.

Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs]: @cston are you making a comment about what this PR should do or that possibly `ErrorTypeSymbol` is the source of the bug? Can't tell from the comment.

Comment (cston) [inline src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs]: If `ErrorTypeSymbol.CandidateSymbols` is returning `default(IImmutableArray<Symbol>)`, it seems like the bug is in `ErrorTypeSymbol`.

Comment (brianhartung) [inline src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs]: Suddenly I am unable to reproduce the crashing behavior with or without my changes. I did have to install 15.3 preview which may explain this (previously when I could repro the behavior I was on 15.2 Enterprise but I apparently got myself into PDB hell and could not longer get symbols to load and step through code so I installed 15.3 and now it won't crash anymore in either VS install).

**Comment by brianhartung** [comment]
Ok, I think we might have narrowed in on the issue here. I haven't added any unit tests yet (not 100% sure what those would look like) but I wanted to have someone eyeball this fix.  I can get VS (15.3 Preview) to reliably crash without it.

**Comment by cston** [comment]
A test would probably look something like the following. Please ensure the test fails without your fix.
```
        [Fact]
        public void AttributeArgumentLambdaThis()
        {
            string source =
@"class C
{
    [X(() => this._Y)]
    public void Z()
    {
    }
}";
            var compilation = CreateStandardCompilation(source);
            var tree = compilation.SyntaxTrees[0];
            var model = compilation.GetSemanticModel(tree);
            var syntax = tree.GetCompilationUnitRoot().DescendantNodes().Single(n => n.Kind() == SyntaxKind.ThisExpression);
            var info = model.GetSemanticInfoSummary(syntax);
            Assert.Equal("...", info.Type.ToTestDisplayString());
        }
```

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetSemanticInfoTests.cs [hunk 2]
```diff
@@ -15213,5 +15213,24 @@ class K
 
             Assert.False(semanticInfo.IsCompileTimeConstant);
         }
+
+        [Fact]
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetSemanticInfoTests.cs]: Please add `[WorkItem(18763, "https://github.com/dotnet/roslyn/issues/18763")]`. (I should have included that originally.)

Comment (brianhartung) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetSemanticInfoTests.cs]: No problem...I'll do that now.  Btw, as requested I did verify that with my change all tests pass locally (including my new one) but if I revert the fix, I get the original NRE in this new test case (in the same spot that caused the crash).  Being new to this, I'm not sure what the best way is to provide evidence, but attached is a screenshot of the expected failure case
attributeargumentlambdathistest_failed
.

**Comment by cston** [comment]
LGTM

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetSemanticInfoTests.cs (hunk 2 above)
Comment (agocke) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetSemanticInfoTests.cs]: @brianhartung No problem. For future reference, if you say the test failed without your change we usually take your word on it :)

**Comment by dpoeschl** [comment]
retest windows_debug_vs-integration_prtest please
