### PR TITLE
Adjust calculation of invocation escape when return type is ref to ref struct

### LINKED ISSUE #65648: Writes through `UnscopedRef` allows bypassing lifetime rules
**Version Used**: 
57cfbe6f5ba818c42485bf15f03146f15546e12e

**Steps to Reproduce**:

The following example compiles:

```csharp
using System;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

public class Repro
{
    private static void Bad(ref RefStruct2 s2)
    {
        int value = 100;
        RefStruct1 s1 = new RefStruct1();
        s1.Ref.RefField = ref value;
        s2.RefField = ref s1.RefField;
    }

    private ref struct RefStruct1
    {
        public ref int RefField;
        [UnscopedRef] public ref RefStruct1 Ref => ref this;
    }

    private ref struct RefStruct2
    {
        public ref int RefField;
    }
}
```

[Sharplab Example](https://sharplab.io/#v2:EYLgtghglgdgNAFxFANnAJiA1AHwAIBMAjALABQeADAAR5EB0AIlBAOYwD2AzglAMZd6AYQ7oApgEEYEFAE8uULgG5yVWgwBKAVxi8wY4RzAAHVGIBOAZQsA3fmOXlVAZloFqGscfMdyAb3JqIOpvKBsIBDF1ADZaABZqACEIdAAKczEAMw8sywRzLT4Edy4CAEpA4ICyYNrqWARqcJQtKIBeaiJKShUauqDPTLyCoqJqLjGOmDEAdxyh/MKEIlSy3v6gifpB7ayAMSgxFHRqDozs5tb1jdLdzIOjk7Os8c19w+ProIBfJz6g0LhSLUc7jRZFebDJakf7UaobWiuUENeYPT6VfoAbQAqjAuHwOMYxOhBgBdREgl6DKGjeanAB8lOyCAAFoovtRfmQMSFzGEIlFQTwRo1qeDijz4Rs8EiXijBmj0Byud8gA==)

A byref to `value` escapes from `Bad`.

**Expected Behavior**:
Compiler error.

**Actual Behavior**:
No compiler error.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Implementation of https://github.com/dotnet/csharplang/pull/6781

Closes #65648

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 1]
```diff
@@ -1729,18 +1729,35 @@ bool isRefEscape
...
+                // We are only getting the method in order to handle a special condition where the method returns by-ref.
+                // It is an error for a property to have a setter and return by-ref, so we only bother looking for a getter here.
+                PropertySymbol p => p.GetMethod,
+                _ => null
+            };
+            var returnsWritableRefToRefStruct = method is { ReturnsByRef: true, ReturnType.IsRefLikeType: true };
+            foreach (var (param, argument, _, isArgumentRefEscape) in argsAndParamsAll)
+            {
+                // SPEC:
+                // If `M()` does return ref-to-ref-struct, the *safe-to-escape* is the same as the *safe-to-escape* of all arguments which are ref-to-ref-struct.
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1745]:
```suggestion
                // If `M()` does return ref-to-ref-struct, the *safe-to-escape* is the same as the *safe-to-escape* of all arguments which are ref-to-ref-struct. It is an error if there are multiple arguments with different *safe-to-escape* because of *method arguments must match*.
```

Perhaps better to include more of the spec excerpt here

**Comment by cston** [comment]
>             foreach (var argAndParam in argsAndParamsAll)

Do we need to consider only ref-to-ref-struct parameters here when the method returns a ref-to-ref-struct?

---
Refers to: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1889 in a8ea1ae. [](commit_id = a8ea1aee37bafd2b1cbb90af48236f02dadc0795, deletion_comment = False)

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 2]
```diff
@@ -27082,5 +27082,96 @@ static void M()
...
+                    }
+
+                    private ref struct RefStruct
+                    {
+                        public ref int RefField;
+                        [UnscopedRef] public ref RefStruct RefProperty => ref this;
+                        [UnscopedRef] public ref RefStruct RefMethod() => ref this;
+                    }
+                }
+                """;
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:27119]: >"""; [](http://example.com/codeflow?start=16&length=4)

It looks like we're only testing ref-to-ref-struct arguments used as the receiver of an instance method. Consider testing a static method with ref-to-ref-struct argument.
```csharp
F(ref s1).RefField = ref value;

static ref RefStruct F(ref RefStruct r) => ref r;
```

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 3]
```diff
@@ -1729,18 +1729,35 @@ bool isRefEscape
...
+                // If `M()` does return ref-to-ref-struct, the *ref-safe-to-escape* is the narrowest *ref-safe-to-escape* contributed by all arguments which are ref-to-ref-struct.
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1746]: We can take a reference to a variable from any scope, so one case where they might be different is e.g.

```cs
RS rs1 = M();
{
    RS rs2 = M();
    M(ref rs1, ref rs2);
}
```

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 4]
```diff
@@ -1869,24 +1891,34 @@ bool isRefEscape
...
-                    CheckRefEscape(argument.Syntax, argument, escapeFrom, escapeTo, false, diagnostics) :
-                    CheckValEscape(argument.Syntax, argument, escapeFrom, escapeTo, false, diagnostics);
-
-                if (!valid)
+                // SPEC:
+                // If `M()` does return ref-to-ref-struct, the *safe-to-escape* is the same as the *safe-to-escape* of all arguments which are ref-to-ref-struct.
+                // If `M()` does return ref-to-ref-struct, the *ref-safe-to-escape* is the narrowest *ref-safe-to-escape* contributed by all arguments which are ref-to-ref-struct.
+                //
+                if (!returnsWritableRefToRefStruct
+                    || (argAndParam.Parameter?.RefKind.IsWritableReference() == true && argAndParam.Parameter.Type.IsRefLikeType && argAndParam.IsRefEscape == isRefEscape))
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1903]: >argAndParam.Parameter [](http://example.com/codeflow?start=24&length=21)

Consider extracting a `param` local, or using `foreach` deconstruction above to match `GetInvocationEscapeWithUpdatedRules()`: `foreach (var (param, argument, _, isArgumentRefEscape) in argsAndParamsAll)`

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 5]
```diff
@@ -1869,24 +1891,34 @@ bool isRefEscape
...
             foreach (var argAndParam in argsAndParamsAll)
             {
-                var argument = argAndParam.Argument;
-                bool valid = argAndParam.IsRefEscape ?
-                    CheckRefEscape(argument.Syntax, argument, escapeFrom, escapeTo, false, diagnostics) :
-                    CheckValEscape(argument.Syntax, argument, escapeFrom, escapeTo, false, diagnostics);
-
-                if (!valid)
+                // SPEC:
+                // If `M()` does return ref-to-ref-struct, the *safe-to-escape* is the same as the *safe-to-escape* of all arguments which are ref-to-ref-struct.
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1899]: >. [](http://example.com/codeflow?start=160&length=1)

Consider adding "It is an error if there are multiple arguments with different *safe-to-escape* because of *method arguments must match*."

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 6]
```diff
@@ -27082,5 +27079,228 @@ static void M()
...
+
+                    private static void Bad2(scoped ref RefStruct s1, int value)
+                    {
+                        s1.RefProperty = new RefStruct(ref value); // 2
+                    }
+
+                    private static void Bad3(scoped ref RefStruct s1, int value)
+                    {
+                        s1.RefMethod() = new RefStruct(ref value); // 3
+                    }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:27195]: >} [](http://example.com/codeflow?start=20&length=1)

Consider testing a static method with a ref-to-ref-struct argument if you haven't already.
```csharp
static void Bad4(scoped ref RefStruct s4, int value)
{
    GetRef(ref s4) = new RefStruct(ref value); // 4
}

static ref RefStruct GetRef(ref RefStruct s) => ref s;
```

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 7]
```diff
@@ -27082,5 +27079,228 @@ static void M()
...
+                """;
+            var comp = CreateCompilation(source, targetFramework: TargetFramework.Net70);
+            comp.VerifyDiagnostics(
+                // (10,14): error CS8352: Cannot use variable 's2' in this context because it may expose referenced variables outside of their declaration scope
+                //         s1 = s2.RefMethod(); // 1
+                Diagnostic(ErrorCode.ERR_EscapeVariable, "s2").WithArguments("s2").WithLocation(10, 14));
+        }
+
+        [Fact, WorkItem(65648, "https://github.com/dotnet/roslyn/issues/65648")]
+        public void ReturnRefToRefStruct_RefEscape_01()
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:27268]: >ReturnRefToRefStruct_RefEscape_01 [](http://example.com/codeflow?start=20&length=33)

Is this test affected by the changes in the PR? It doesn't look like it, but I wanted to confirm I wasn't overlooking something.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 8]
```diff
@@ -27082,5 +27079,228 @@ static void M()
...
+
+        [Fact, WorkItem(65648, "https://github.com/dotnet/roslyn/issues/65648")]
+        public void ReturnRefToRefStruct_ValEscape_02()
+        {
+            var source = """
+                using System.Diagnostics.CodeAnalysis;
+
+                public class Repro
+                {
+                    private static void Bad1(ref RefStruct s1, int value)
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:27138]: >ref [](http://example.com/codeflow?start=45&length=3)

Should this be `scoped ref`?

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs (hunk 7 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:27268]: This test verifies the following line of the specification

> If `M()` does return ref-to-ref-struct, the *ref-safe-to-escape* is the narrowest *ref-safe-to-escape* contributed by all arguments which are ref-to-ref-struct.

The behavior in practice is not new, though. I couldn't think of a scenario which tests the behavior more deeply, e.g. something where we pick the narrowest of multiple input ref escapes, and ignore an even narrower STE. since the narrowest STE is necessarily wider or equal to the narrowest RSTE.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs (hunk 8 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:27138]: Yeah, I think so.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 9]
```diff
@@ -1729,25 +1729,47 @@ bool isRefEscape
...
+        {
+            var method = symbol switch
+            {
+                MethodSymbol m => m,
+                // We are only getting the method in order to handle a special condition where the method returns by-ref.
+                // It is an error for a property to have a setter and return by-ref, so we only bother looking for a getter here.
+                PropertySymbol p => p.GetMethod,
+                _ => null
+            };
+            return method is ({ ReturnsByRef: true } or { ReturnsByRefReadonly: true }) and { ReturnType.IsRefLikeType: true };
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1770]: >({ ReturnsByRef: true } or { ReturnsByRefReadonly: true }) and { ReturnType.IsRefLikeType: true } [](http://example.com/codeflow?start=29&length=97)

Minor: Consider changing to `{ RefKind: not RefKind.None, ReturnType.IsRefLikeType: true }` to simplify (slightly) and to align with the similar checks for `param`.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 10]
```diff
@@ -27082,5 +27079,334 @@ static void M()
...
+                    private static void Bad1(int value)
+                    {
+                        RefStruct s1 = new RefStruct();
+                        GetReference1(ref s1).RefField = ref value; // 1
+                        GetReference2(in s1).RefField = ref value; // 2
+                        GetReference3(out s1).RefField = ref value; // 3
+
+                        GetReadonlyReference1(ref s1).RefField = ref value; // 4
+                        GetReadonlyReference2(in s1).RefField = ref value; // 5
+                        GetReadonlyReference3(out s1).RefField = ref value; // 6
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:27373]: Are these cases affected by the changes in this PR? It looks like we already report these errors.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 11]
```diff
@@ -27082,5 +27079,334 @@ static void M()
...
+                        s1.RefMethod().RefField = ref value; // 3
+                    }
+
+                    private ref struct RefStruct
+                    {
+                        public ref int RefField;
+                        [UnscopedRef] public ref RefStruct RefProperty => ref this;
+                        [UnscopedRef] public ref RefStruct RefMethod() => ref this;
+                    }
+                }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:27159]: >} [](http://example.com/codeflow?start=16&length=1)

Should we have similar tests for `ref readonly` parameters? Presumably, these assignments should be allowed because we create a copy of the parameter.
```csharp
    private static void Bad2(in RefStruct s1, int value)
    {
        s1.RefProperty.RefField = ref value; // ok
    }

    private static void Bad3(in RefStruct s1, int value)
    {
        s1.RefMethod().RefField = ref value; // ok
    }
```

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:27159]: I think strictly we should allow it, but also, you're storing to a field of an temp struct variable, so if it fell out as being an error I'd be OK with it.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs (hunk 6 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:27195]: Added this in to `ReturnRefToRefStruct_ValEscape_03`.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs (hunk 10 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:27373]: I think the behavior is not changed, but it still feels relevant to test this case, because we can still end up in a path in escape analysis where the method returns *readonly ref to ref struct* with various kinds of parameters. Basically, I just don't want anything to fall over in that combination, or to unexpectedly permit any of these assignments (as unlikely as that may be).

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1738]: This is tested in `ReturnRefToRefStruct_RefEscape_01`

**Review by cston — APPROVED** [review]

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler for a second review

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 12]
```diff
@@ -1729,25 +1729,47 @@ bool isRefEscape
...
-            foreach (var argAndParam in argsAndParamsAll)
-            {
-                var argument = argAndParam.Argument;
-                uint argEscape = argAndParam.IsRefEscape ?
-                    GetRefEscape(argument, scopeOfTheContainingExpression) :
-                    GetValEscape(argument, scopeOfTheContainingExpression);
 
-                escapeScope = Math.Max(escapeScope, argEscape);
-                if (escapeScope >= scopeOfTheContainingExpression)
+            var returnsWritableRefToRefStruct = ReturnsRefToRefStruct(symbol);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1733]: should be `var returnsRefToRefStruct`

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 13]
```diff
@@ -1729,25 +1729,47 @@ bool isRefEscape
...
+            foreach (var (param, argument, _, isArgumentRefEscape) in argsAndParamsAll)
+            {
+                // SPEC:
+                // If `M()` does return ref-to-ref-struct, the *safe-to-escape* is the same as the *safe-to-escape* of all arguments which are ref-to-ref-struct. It is an error if there are multiple arguments with different *safe-to-escape* because of *method arguments must match*.
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1737]: >It is an error if there are multiple arguments with different *safe-to-escape* because of *method arguments must match*. [](http://example.com/codeflow?start=162&length=120)

nit: skip second sentence?

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 14]
```diff
@@ -27082,5 +27079,385 @@ static void M()
...
+                //         GetReadonlyReference1(ref s1).RefField = ref value; // 4
+                Diagnostic(ErrorCode.ERR_AssignReadonlyNotField2, "GetReadonlyReference1(ref s1).RefField").WithArguments("method", "GetReadonlyReference1").WithLocation(12, 9),
+                // (13,9): error CS8332: Cannot assign to a member of method 'GetReadonlyReference2' or use it as the right hand side of a ref assignment because it is a readonly variable
+                //         GetReadonlyReference2(in s1).RefField = ref value; // 5
+                Diagnostic(ErrorCode.ERR_AssignReadonlyNotField2, "GetReadonlyReference2(in s1).RefField").WithArguments("method", "GetReadonlyReference2").WithLocation(13, 9),
+                // (14,9): error CS8332: Cannot assign to a member of method 'GetReadonlyReference3' or use it as the right hand side of a ref assignment because it is a readonly variable
+                //         GetReadonlyReference3(out s1).RefField = ref value; // 6
+                Diagnostic(ErrorCode.ERR_AssignReadonlyNotField2, "GetReadonlyReference3(out s1).RefField").WithArguments("method", "GetReadonlyReference3").WithLocation(14, 9));
+        }
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:27461]: nit: consider test invocation of a `ref R ReturnRef(scoped ref R r, ref R r)` method

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 5) with a couple nits to consider

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 13 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1737]: We felt this was more clear to include. It's meant to explain why we are still calculating the narrowest scope here (`Math.Max`) instead of requiring equal scopes--you shouldn't worry about the case where the scopes actually differ, since an error will be reported elsewhere.

**Review by jcouv — APPROVED** [review]
