### PR TITLE
Fix HasFileLocalTypes check for constructed types

### LINKED ISSUE #67208: Compiler fails to detect a constructed `file` type.
```
file class C1 {}

class C2 : C1 {}

file class C3<T> {}

class C4 : C3<int> {}
```

Observed:
```
error CS9053: File-local type 'C1' cannot be used as a base type of non-file-local type 'C2'.
```

Expected an additional error for base type of C4.

The ```type is SourceMemberContainerTypeSymbol``` check is the likely source of the problem:
```
        public static bool HasFileLocalTypes(this TypeSymbol type)
        {
            var foundType = type.VisitType(predicate: (type, _, _) => type is SourceMemberContainerTypeSymbol { IsFileLocal: true }, arg: (object?)null);
            return foundType is not null;
        }
```
There are several more places in the code base that might have similar issues.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #67208

Reviewed usages of HasFileLocalTypes and tried to add tests exercising each one.

Relates to file-types: https://github.com/dotnet/roslyn/issues/60819

### CODE REVIEW

**Comment by RikkiGibson** [comment]
> I would recommend each test to have a type check

Are you suggesting the test obtains the relevant type symbols and checks their types?

**Comment by jcouv** [comment]
> Are you suggesting the test obtains the relevant type symbols and checks their types?

That's what I was suggesting, but looking at the test file it looks like it's mostly doing that already (type check and check for `IsFileLocal`). So I guess that wouldn't have prevented the issue...

File: src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs [hunk 1]
```diff
@@ -1366,7 +1366,7 @@ public static bool IsPartial(this TypeSymbol type)
 
         public static bool HasFileLocalTypes(this TypeSymbol type)
         {
-            var foundType = type.VisitType(predicate: (type, _, _) => type is SourceMemberContainerTypeSymbol { IsFileLocal: true }, arg: (object?)null);
+            var foundType = type.VisitType(predicate: (type, _, _) => type.OriginalDefinition is SourceMemberContainerTypeSymbol { IsFileLocal: true }, arg: (object?)null);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs:1369]: What kind of symbol was causing a problem, was it `SubstitutedNamedTypeSymbol`? If so, shouldn't `SubstitutedNamedTypeSymbol.IsFileLocal` already defer to the original definition?

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 1)

File: src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs:1369]: Per offline discussion we'd like to try introducing `internal abstract bool NamedTypeSymbol.IsFileLocal { get; }` and using it where applicable.

File: src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs [hunk 2]
```diff
@@ -3392,7 +3392,7 @@ public override void VisitNamespace(NamespaceSymbol symbol)
             public override void VisitNamedType(NamedTypeSymbol symbol)
             {
                 Debug.Assert(symbol.ContainingSymbol.Kind == SymbolKind.Namespace); // avoid unnecessary traversal of nested types
-                if (symbol.AssociatedFileIdentifier is not null)
+                if (symbol.IsFileLocal)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:3395]: Nice. I think this reads better/clearer :-)

File: src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs (hunk 1 above)
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs:1369]: Could we just do `=> type.IsFileLocal` now?

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 4)

File: src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs:1369]: Oops, the whole point was to start using the new API here.

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs [hunk 3]
```diff
@@ -394,7 +394,8 @@ internal override ModuleSymbol ContainingModule
             get;
         }
 
-        internal override FileIdentifier? AssociatedFileIdentifier
+        internal sealed override bool IsFileLocal => AssociatedFileIdentifier is not null;
```
[the remark this answers is not in the document]
Comment (jcouv) [reply src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs]: Consider updating the `AssociatedFileIdentifier` property below to use `IsFileLocal`, to avoid duplication. `return IsFileLocal ? new FileIdentifier { ... } : null;`

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 5) with a minor suggestion in PENamedTypeSymbol

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs]: I considered some strategies for avoiding duplication in the below `AssociatedFileIdentifier` implementation, but in the end felt that the current solution was adequate.

[the remark this answers is not in the document]
Comment (jcouv) [reply src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs]: I didn't follow, what's the downside of the refactoring I proposed?

[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs]: Having to separately read the fields again in AssociatedFileIdentifier, and either add MemberNotNullAttribute to IsFileLocal or add ! when we know some are non-null.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 5)

**Comment by AlekseyTs** [comment]
Looking

File: src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs [hunk 4]
```diff
@@ -1366,7 +1366,7 @@ public static bool IsPartial(this TypeSymbol type)
 
         public static bool HasFileLocalTypes(this TypeSymbol type)
         {
-            var foundType = type.VisitType(predicate: (type, _, _) => type is SourceMemberContainerTypeSymbol { IsFileLocal: true }, arg: (object?)null);
+            var foundType = type.VisitType(predicate: (type, _, _) => type is NamedTypeSymbol { IsFileLocal: true }, arg: (object?)null);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs:1369]: >IsFileLocal [](http://example.com/codeflow?start=96&length=11)

I see several more places where access to ```IsFileLocal``` property is "surrounded" with a type check. For example:
```
        private static BestSymbolLocation GetLocation(CSharpCompilation compilation, Symbol symbol)
        {
            if (symbol is SourceMemberContainerTypeSymbol { IsFileLocal: true })
```

Consider getting rid of the type checks, unless they are significant. Or adding a comment (about the significance) otherwise.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 5).

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 6)
