### PR TITLE
Fix that completion list doesn't include param entries for indexers

### LINKED ISSUE #1661: Intellisense doesnt suggest <param> tags for indexers
```csharp
public class Foo
{
    /// <summary>
    /// A indexer.
    /// </summary>
    /// <#
    /// <returns> foo. </returns>
    public string this [string foo]
    {
        get { return foo; }
    }
}
```

If the cursor is at # and intellisense is up "param name="foo"" doesnt show up. It should work for indexers the same way it works for methods. I can create a PR for that.

### PR DESCRIPTION
**Pull request by pdelvo**
This commit changes the completion list for indexers. The completion list now includes <param> entries for each parameter.
In C# completion for paramref's name tags in indexer documentation will now provide a parameter list.
Also some unnecessary code for typeref tags inside property declarations are removed, because properties and indexers can't have type arguments.

I can't test any of this so I don't know if this will work and if there are any tests that are failing now. So this might be completly wrong.

Fixes #1661.

### CODE REVIEW

File: src/EditorFeatures/CSharp/Completion/CompletionProviders/XmlDocCommentCompletion/XmlDocCommentCompletionProvider.cs [hunk 1]
```diff
@@ -220,15 +220,39 @@ private string AttributeSelector(XmlElementSyntax element, string attribute)
...
 
-            var typeParameters = symbol.GetTypeArguments().Select(p => p.Name).ToSet();
+            if (symbol.IsIndexer)
+            {
+                var parameters = symbol.GetParameters().Select(p => p.Name).ToSet();
 
-            RemoveExistingTags(trivia, typeParameters, x => AttributeSelector(x, "typeparam"));
+                // User is trying to write a name, try to suggest only names.
+                if (token.Parent.IsKind(SyntaxKind.XmlNameAttribute) ||
+                    (token.Parent.IsKind(SyntaxKind.IdentifierName) && token.Parent.IsParentKind(SyntaxKind.XmlNameAttribute)))
```
Comment (rchande) [inline src/EditorFeatures/CSharp/Completion/CompletionProviders/XmlDocCommentCompletion/XmlDocCommentCompletionProvider.cs]: Since this is basically the same as the code that adds paramref/typeparamref for methods, could you extract out a helper that takes "token", "items", an IEnumerable<IParameterSymbol>, and an IEnumerable<ITypeParameterSymbol> and call that from both GetTagsForMethod and GetTagsForProperty?

Comment (rchande) [inline src/EditorFeatures/CSharp/Completion/CompletionProviders/XmlDocCommentCompletion/XmlDocCommentCompletionProvider.cs]: Should we also go ahead and add in the ContainingType's type parameters?

**Comment by rchande** [comment]
Are you able to run the tests in "Roslyn.Services.Editor.CSharp.UnitTests.dll" and "Roslyn.Services.Editor.VisualBasic.UnitTests.dll"?

If so, would you mind adding corresponding tests to XmlDocumentationCommentCompletionProviderTests.cs and  XmlDocCommentCompletionProviderTests.vb, respectively? If those test assemblies don't work on your machine, I can do it for you.

**Comment by rchande** [comment]
FWIW, this change does work on my machine :smile:. Thanks!

File: src/EditorFeatures/CSharp/Completion/CompletionProviders/XmlDocCommentCompletion/XmlDocCommentCompletionProvider.cs (hunk 1 above)
Comment (Pilchie) [inline src/EditorFeatures/CSharp/Completion/CompletionProviders/XmlDocCommentCompletion/XmlDocCommentCompletionProvider.cs]: You can't refer to them with &lt:typeparam&gt; can you?  You need to use &lt;typeparamref&gt; for that.

Comment (rchande) [inline src/EditorFeatures/CSharp/Completion/CompletionProviders/XmlDocCommentCompletion/XmlDocCommentCompletionProvider.cs]: Yes, he should call the extracted helper I mention with the property's parameters for the enumerable of parameters and the property's ContainingType's type parameters as the type parameters...parameter.

Comment (pdelvo) [inline src/EditorFeatures/CSharp/Completion/CompletionProviders/XmlDocCommentCompletion/XmlDocCommentCompletionProvider.cs]: Thats a lot of parameters. To sum that up: 
- Add a 
```csharp
 private IEnumerable<CompletionItem> GetParameterNameTags(TextSpan filterSpan, SyntaxToken token, List<CompletionItem> items, ISet<string> parameters, ISet<string> typeParameters)
```
- Call that method both in `GetTagsForProperty` and `GetTagsForMethod`.
- Use ContainingType.Typeparameters for the type parameters in the GetTagsForProperty and ContainingType.Typeparameters + the method type parameters for the type parameters in GetTagsForMethod

Im asking because typeparamref doesnt have completion for containing type type parameters yet.

**Comment by sharwell** [comment]
@pdelvo I'm a bit confused by the commit message and title. Does this affect `<param>` elements, `<paramref>` elements, or both?

**Comment by pdelvo** [comment]
It affects both. it looks like that it was fergotten that there are properties (indexers) that could have parameters. So both <param and <paramref didnt have working autocompletion. And with the changes suggested by @rchande it also affects <typeparamref on indexers and methods if I understood that correctly.

File: src/EditorFeatures/CSharp/Completion/CompletionProviders/XmlDocCommentCompletion/XmlDocCommentCompletionProvider.cs (hunk 1 above)
Comment (rchande) [inline src/EditorFeatures/CSharp/Completion/CompletionProviders/XmlDocCommentCompletion/XmlDocCommentCompletionProvider.cs]: Yep, that's right. It is rather a lot of parameters--you're welcome to factor it in a different way. It just seemed silly to duplicate the logic of looking at the tree to determine what to suggest. Thanks!

**Comment by rchande** [comment]
@pdelvo I apologize for losing track of this. Are you still interested in getting this change merged?

**Comment by pdelvo** [comment]
I had problems running the tests. It works now. I rebased everything and added two tests.

**Comment by rchande** [comment]
@pdelvo Thanks! This looks good to me.

@brettfo @balajikris @dpoeschl @jasonmalinowski Would one of you mind reviewing this for a second sign off?

**Comment by DustinCampbell** [comment]
This looks good to me. :+1:
