### PR TITLE
Fix for introduce local does not introduce across local functions

### LINKED ISSUE #40209: ExtractLocal: does not extract across local functions
In the following code, extracting a local for all instances of `i.ToString()` behaves correctly on the declaration of `x`, but not on the declaration of `y`. Only the instance on the declaration of `y` would be extracted, instead of both (see screenshot).

``` chsarp
        void M(int i)
        {
            var x = i.ToString();
            local();

            void local()
            {
                var y = i.ToString();
            }
        }
```

image

### PR DESCRIPTION
**Pull request by allisonchou**
Fixes #40209 and adds applicable tests.

### CODE REVIEW

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs [hunk 1]
```diff
@@ -197,8 +197,10 @@ private static SyntaxNode WithBlockBody(SyntaxNode node, BlockSyntax body)
         {
             declarationStatement = declarationStatement.WithAdditionalAnnotations(Formatter.Annotation);
 
-            var oldOutermostBlock = block;
-            var matches = FindMatches(document, expression, document, oldOutermostBlock, allOccurrences, cancellationToken);
+            // If we're within a local function, our scope for the new local declaration is expanded to include the enclosing member.
+            var scope = block.GetAncestor<LocalFunctionStatementSyntax>() == null ? block : (SyntaxNode)block.GetAncestor<MemberDeclarationSyntax>();
```
Comment (JoeRobich) [inline src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: If it isn't especially expensive, would it be simpler to just always look for the `MemberDeclarationSyntax`?

```
var scope = (SyntaxNode)block.GetAncestorOrSelf<MemberDeclarationSyntax>();
```

Comment (dibarbet) [inline src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: I'm not familiar with the rest of the service, but it seems like from here this will expand the scope for static local functions as well?  But I think it shouldn't for static local since the var inside the static local function isn't visible.

If it's already covered somewhere else, might be good to add a test.

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs [hunk 2]
```diff
@@ -197,8 +197,10 @@ private static SyntaxNode WithBlockBody(SyntaxNode node, BlockSyntax body)
...
+
+            var matches = FindMatches(document, expression, document, scope, allOccurrences, cancellationToken);
```
Comment (dpoeschl) [inline src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: What determines where the eventual local gets generated? Will it always be in the member declaration now? Should we be finding the nearest common ancestor member/local function of all discovered matches and putting it there?

Comment (dpoeschl) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: (Maybe it all works great and I'm just asking for more tests on these cases.)

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs (hunk 1 above)
Comment (allisonchou) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: I think you're correct. Unfortunately I didn't realize that we had to ensure the local function was non-static, so I think the check is unavoidable now.

Comment (allisonchou) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: I think you're correct, thanks for the catch! I updated the code with additional tests.

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs (hunk 2 above)
Comment (allisonchou) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: Added more tests for these cases. Thank you!

File: src/EditorFeatures/CSharpTest/CodeActions/IntroduceVariable/IntroduceVariableTests.cs [hunk 3]
```diff
@@ -6228,5 +6228,281 @@ void Test()
...
+        {
+            await TestInRegularAndScriptAsync(
+@"class Program
+{
+    void M(int i)
+    {
+        var x = i.ToString();
+        Local();
+
+        void Local()
```
Comment (jcouv) [inline src/EditorFeatures/CSharpTest/CodeActions/IntroduceVariable/IntroduceVariableTests.cs]: It's less common, but you probably want to test with a nested local function (local function inside another local function).

Comment (allisonchou) [reply src/EditorFeatures/CSharpTest/CodeActions/IntroduceVariable/IntroduceVariableTests.cs]: Thank you for the suggestion! Per your comments, I added some nested local function tests in the PR here: #40441
