### PR TITLE
Ensure proper receiver value is used for a constrained call invocation

### LINKED ISSUE #63221: CompoundAssignment.Bug1021941 fail in .net7p6
Found in https://github.com/dotnet/roslyn/pull/63062 - disabling per infraswat to unblock upgrade to .net7p6, integration tests, and merge of -vs-deps back to main

These tests consistently fail (in all legs on multiple retries) on .net7p6 with an error similar to

```
Roslyn.Test.Utilities.ExecutionException :
Execution failed for assembly '01aff525-fc82-4b43-ac86-50de849ffa07, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
Expected:
Position get for item 'Goo'
Position set for item 'Goo'

Actual: Position get for item 'Goo'
Position set for item 'Bar'
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1921926&view=ms.vss-test-web.build-test-results-tab&runId=49765824&resultId=145381&paneView=debug

### PR DESCRIPTION
**Pull request by AlekseyTs**
Closes #63221.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

File: src/Compilers/VisualBasic/Portable/CodeGen/EmitExpression.vb [hunk 1]
```diff
@@ -1177,6 +1172,116 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.CodeGen
             End If
         End Sub
 
+        <MethodImpl(MethodImplOptions.NoInlining)>
```
Comment (jjonescz) [inline src/Compilers/VisualBasic/Portable/CodeGen/EmitExpression.vb:1175]: Why is this attribute needed?

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

File: src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenCallTests.cs
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenCallTests.cs:1]: > I expected to find a test which was skipped or produced different expected outputs without this fix. Is there such test?

I didn't add any skipped tests for this issue prior to this PR. There are plenty of tests that changed the output in CodeGenCallTests.vb, just look for "Wrong output" in the diff (within removed lines). Apart from IL, no behavior differences expected for C#.

File: src/Compilers/VisualBasic/Portable/CodeGen/EmitExpression.vb (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Portable/CodeGen/EmitExpression.vb:1175]: > Why is this attribute needed?

It is need to prevent JIT from inlining this method into the caller, otherwise recursive calls of the caller can cause a stack overflow for much smaller depth than before.

File: src/Compilers/VisualBasic/Portable/Lowering/UseTwiceRewriter.vb [hunk 2]
```diff
@@ -321,6 +322,42 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
                                       boundTemp)
+            ElseIf receiverOpt.IsLValue AndAlso
+                   CodeGenerator.IsPossibleReferenceTypeReceiverOfConstrainedCall(receiverOpt) AndAlso
+                   Not CodeGenerator.ReceiverIsKnownToReferToTempIfReferenceType(receiverOpt) AndAlso
+                   Not (isForRegularCompoundAssignment AndAlso CodeGenerator.IsSafeToDereferenceReceiverRefAfterEvaluatingArguments(node.Arguments)) Then
+
+                Debug.Assert(Not receiverOpt.Type.IsReferenceType)
+
+                ' A case where T Is actually a class must be handled specially.
+                ' Taking a reference to a class instance Is fragile because the value behind the
```
Comment (jjonescz) [inline src/Compilers/VisualBasic/Portable/Lowering/UseTwiceRewriter.vb:333]:
```suggestion
                ' A case where T is actually a class must be handled specially.
                ' Taking a reference to a class instance is fragile because the value behind the 
```

File: src/Compilers/VisualBasic/Portable/Lowering/AsyncRewriter/AsyncRewriter.AsyncMethodToClassRewriter.Expressions.vb [hunk 3]
```diff
@@ -95,19 +96,89 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
+                                Dim referenceReceiverBuilder As New SpillBuilder()
+                                Dim spilledReferenceReceiver As BoundExpression = SpillRValue(receiverOpt.MakeRValue(), referenceReceiverBuilder)
+                                spilledReferenceReceiver = referenceReceiverBuilder.BuildSequenceAndFree(Me.F, spilledReferenceReceiver)
+                                Dim referenceReceiverSpillSequence = TryCast(spilledReferenceReceiver, BoundSpillSequence)
+
+                                If referenceReceiverSpillSequence IsNot Nothing Then
+                                    ' If condition `(object)default(T) != null` is true at execution time,
+                                    ' the T Is a value type. And it is a reference type otherwise.
+                                    Dim isValueTypeCheck = Me.F.ReferenceIsNotNothing(Me.F.DirectCast(Me.F.DirectCast(Me.F.Null(), receiverType),
+                                                                                      Me.F.SpecialType(SpecialType.System_Object)))
```
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Portable/Lowering/AsyncRewriter/AsyncRewriter.AsyncMethodToClassRewriter.Expressions.vb:157]: > Looks like this condition will be false for nullable value types.

Yes, but we can leave with that and make a copy of a nullable value type because today there is no other more accurate check that is going to be reliably recognized and removed along with the branch known to be false by JIT during specialization. Throughout both compilers we do not go into these details in comments to not "muddle the water".

**Review by jjonescz — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

**Review by RikkiGibson — COMMENTED** [review]
C# changes LGTM, but I need more time to get through the VB changes.

**Review by RikkiGibson — APPROVED** [review]
