### PR TITLE
Repair an InvalidCastException caused by unnecessarily tight coupling.

### LINKED ISSUE #18811: InvalidCastException if System.Nullable`1 is missing
**Version Used**: current master branch

**Steps to Reproduce**:

```C#
using System.IO;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace ConsoleApp1234 {
	class Program {
		static void Main(string[] args) {
			var source = @"
namespace System {
	public class Object { }
	public abstract class ValueType { }
	public struct Void { }
	public struct Boolean { }
	public struct Int32 { }
}
static class C {
	public static bool M() => ((object)123) is int i;
}
";
			var syntaxTree = CSharpSyntaxTree.ParseText(source);
			var compilation = CSharpCompilation.Create("test", new[] { syntaxTree }, options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
			var output = new MemoryStream();
			var result = compilation.Emit(output);
		}
	}
}
```

`System.InvalidCastException: 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.ConstructedErrorTypeSymbol' to type 'Microsoft.CodeAnalysis.CSharp.Symbols.SubstitutedNamedTypeSymbol'.'`

```
>	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol.AsMember(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol newOwner) Line 821	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.LocalRewriter.UnsafeGetNullableMethod(Microsoft.CodeAnalysis.SyntaxNode syntax, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol nullableType, Microsoft.CodeAnalysis.SpecialMember member) Line 1725	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.LocalRewriter.MakeIsDeclarationPattern(Microsoft.CodeAnalysis.SyntaxNode syntax, Microsoft.CodeAnalysis.CSharp.BoundExpression loweredInput, Microsoft.CodeAnalysis.CSharp.BoundExpression loweredTarget, bool requiresNullTest) Line 198	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.LocalRewriter.MakeIsDeclarationPattern(Microsoft.CodeAnalysis.CSharp.BoundDeclarationPattern loweredPattern, Microsoft.CodeAnalysis.CSharp.BoundExpression loweredInput) Line 99	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.LocalRewriter.MakeIsPattern(Microsoft.CodeAnalysis.CSharp.BoundPattern loweredPattern, Microsoft.CodeAnalysis.CSharp.BoundExpression loweredInput) Line 28	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitIsPatternExpression(Microsoft.CodeAnalysis.CSharp.BoundIsPatternExpression node) Line 16	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundIsPatternExpression.Accept(Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor visitor) Line 5786	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression node) Line 96	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression node) Line 225	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(ref int recursionDepth, Microsoft.CodeAnalysis.CSharp.BoundExpression node) Line 206	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression node) Line 91	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitExpressionImpl(Microsoft.CodeAnalysis.CSharp.BoundExpression node) Line 177	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.LocalRewriter.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 137	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitReturnStatement(Microsoft.CodeAnalysis.CSharp.BoundReturnStatement node) Line 8689	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitReturnStatement(Microsoft.CodeAnalysis.CSharp.BoundReturnStatement node) Line 13	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundReturnStatement.Accept(Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor visitor) Line 2473	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.LocalRewriter.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 140	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitBlock(Microsoft.CodeAnalysis.CSharp.BoundBlock node) Line 24	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor visitor) Line 2195	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.LocalRewriter.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 140	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.LocalRewriter.Rewrite(Microsoft.CodeAnalysis.CSharp.CSharpCompilation compilation, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol method, int methodOrdinal, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol containingType, Microsoft.CodeAnalysis.CSharp.BoundStatement statement, Microsoft.CodeAnalysis.CSharp.TypeCompilationState compilationState, Microsoft.CodeAnalysis.CSharp.SynthesizedSubmissionFields previousSubmissionFields, bool allowOmissionOfConditionalCalls, bool instrumentForDynamicAnalysis, ref System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CodeGen.SourceSpan> dynamicAnalysisSpans, Microsoft.CodeAnalysis.CodeGen.DebugDocumentProvider debugDocumentProvider, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, out bool sawLambdas, out bool sawLocalFunctions, out bool sawAwaitInExceptionHandler) Line 94	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MethodCompiler.LowerBodyOrInitializer(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol method, int methodOrdinal, Microsoft.CodeAnalysis.CSharp.BoundStatement body, Microsoft.CodeAnalysis.CSharp.SynthesizedSubmissionFields previousSubmissionFields, Microsoft.CodeAnalysis.CSharp.TypeCompilationState compilationState, bool instrumentForDynamicAnalysis, Microsoft.CodeAnalysis.CodeGen.DebugDocumentProvider debugDocumentProvider, ref System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CodeGen.SourceSpan> dynamicAnalysisSpans, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, ref Microsoft.CodeAnalysis.CodeGen.VariableSlotAllocator lazyVariableSlotAllocator, Microsoft.CodeAnalysis.ArrayBuilder<Microsoft.CodeAnalysis.CodeGen.LambdaDebugInfo> lambdaDebugInfoBuilder, Microsoft.CodeAnalysis.ArrayBuilder<Microsoft.CodeAnalysis.CodeGen.ClosureDebugInfo> closureDebugInfoBuilder, out Microsoft.CodeAnalysis.CSharp.StateMachineTypeSymbol stateMachineTypeOpt) Line 1171	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol methodSymbol, int methodOrdinal, ref Microsoft.CodeAnalysis.CSharp.Binder.ProcessedFieldInitializers processedInitializers, Microsoft.CodeAnalysis.CSharp.SynthesizedSubmissionFields previousSubmissionFields, Microsoft.CodeAnalysis.CSharp.TypeCompilationState compilationState) Line 1001	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol containingType) Line 434	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedTypeAsTask.AnonymousMethod__0() Line 324	C#
 	Microsoft.CodeAnalysis.dll!Roslyn.Utilities.UICultureUtilities.WithCurrentUICulture.AnonymousMethod__0() Line 136	C#
```

### PR DESCRIPTION
**Pull request by gafter**
**Customer scenario**

Use pattern-matching when compiling (or compiling against) a core library that lacks Nullable`1. Compiler crashes.

**Bugs this fixes:**

Fixes #18811

**Workarounds, if any**

Don't do that.

**Risk**

Tiny. The bug was in error recovery code.

**Performance impact**

None expected.

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

The improper tight coupling (depending on particular implementation types) bug has been latent, undetected, for years. We just found a symptom.

**How was the bug found?**

Customer reported.

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a review of this tiny fix to a compiler crash?

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a review of this tiny fix to a compiler crash?

**Comment by cston** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Symbols/SubstitutedMethodSymbol.cs [hunk 1]
```diff
@@ -38,9 +38,10 @@ internal class SubstitutedMethodSymbol : WrappedMethodSymbol
 
         private int _hashCode; // computed on demand
 
-        internal SubstitutedMethodSymbol(SubstitutedNamedTypeSymbol containingSymbol, MethodSymbol originalDefinition)
+        internal SubstitutedMethodSymbol(NamedTypeSymbol containingSymbol, MethodSymbol originalDefinition)
             : this(containingSymbol, containingSymbol.TypeSubstitution, originalDefinition, constructedFrom: null)
         {
+            Debug.Assert(containingSymbol is SubstitutedNamedTypeSymbol || containingSymbol is SubstitutedErrorTypeSymbol);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/SubstitutedMethodSymbol.cs]: >containingSymbol is SubstitutedErrorTypeSymbol [](start = 75, length = 46)

Error types do not have members, is this yet another case where we are fed an error method symbol and try use it as if it is good? If that is the case, I would prefer us to fix the root cause of the problem, i.e. the problem of failing to recognize the error situation in the local rewriter, rather than fixing a symptom.

**Comment by AlekseyTs** [comment]
Done with review pass.

File: src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs [hunk 2]
```diff
@@ -818,7 +818,7 @@ internal MethodSymbol AsMember(NamedTypeSymbol newOwner)
         {
             Debug.Assert(this.IsDefinition);
             Debug.Assert(ReferenceEquals(newOwner.OriginalDefinition, this.ContainingSymbol.OriginalDefinition));
-            return (newOwner == this.ContainingSymbol) ? this : new SubstitutedMethodSymbol((SubstitutedNamedTypeSymbol)newOwner, this);
+            return (newOwner == this.ContainingSymbol) ? this : new SubstitutedMethodSymbol(newOwner, this);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs]: >return (newOwner == this.ContainingSymbol) ? this : new SubstitutedMethodSymbol(newOwner, this); [](start = 12, length = 96)

Could you please point to the location of the affected consumer.

File: src/Compilers/CSharp/Portable/Symbols/SubstitutedMethodSymbol.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Symbols/SubstitutedMethodSymbol.cs]: Error symbols are designed specifically to be "used as if they are good" to avoid having to special-case error recovery code. As such, I believe this is precisely the correct fix (as opposed to adding special-case error recovery code in each caller).

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/SubstitutedMethodSymbol.cs]: > Error symbols are designed specifically to be "used as if they are good" to avoid having to special-case error recovery code.

It is very possible that that was the intent behind introducing non-type error symbols. However, the implementation never delivered on that promise. Until that is done, I think we should move away from the pattern of using "Unsafe..." helpers in the local rewriter to using "TryGet..." helpers. PR https://github.com/dotnet/roslyn/pull/17549 made local rewriter more robust in situations like this and I believe we should follow the same approach in addressing this particular issue. Judging by the call stack, the crash that we are trying to fix happens in UnsafeGetNullableMethod. It is already marked as an unsafe API to use.

File: src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs]: It is the `AsMember` call here in `LocalRewriter_BinaryOperator.cs`:

``` c#
        private MethodSymbol UnsafeGetNullableMethod(SyntaxNode syntax, TypeSymbol nullableType, SpecialMember member)
        {
            var nullableType2 = nullableType as NamedTypeSymbol;
            Debug.Assert((object)nullableType2 != null);
            return UnsafeGetSpecialTypeMethod(syntax, member).AsMember(nullableType2);
        }
```

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs]: I would say that this method should never be called with an error type symbol as the target container.

Comment (gafter) [inline src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs]: Why would you say that? With the unnecessarily tight coupling fixed, the behavior appears to be precisely as needed in the callers. I suspect you're imagining some value in pushing some additional error recovery code into the callers (which would be duplicate code in each caller), but you have not identified that value.

The questions are
1. Is the bug fixed? (If not, please demonstrate)
2. Is the fix tested?

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a couple of reviews of this small bug fix?

File: src/Compilers/CSharp/Portable/Symbols/SubstitutedMethodSymbol.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Symbols/SubstitutedMethodSymbol.cs]: The only reason it is "Unsafe" for this kind of use is because of the inappropriate tight coupling fixed by this PR. It should always be safe to call `method.AsMember` with a type that is a construction of the method's containing type. It wasn't before this PR. It is after this PR. That was clearly a bug. With that bug fixed, the crash is fixed.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/SubstitutedMethodSymbol.cs]: >Debug.Assert(containingSymbol is SubstitutedNamedTypeSymbol || containingSymbol is SubstitutedErrorTypeSymbol); [](start = 12, length = 111)

Please add an assert for containership relationship between originalDefinition and containingSymbol.OriginalDefinition.

Comment (gafter) [inline src/Compilers/CSharp/Portable/Symbols/SubstitutedMethodSymbol.cs]: Done.

File: src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+using Microsoft.CodeAnalysis.CodeGen;
+using Microsoft.CodeAnalysis.CSharp.Symbols;
+using Microsoft.CodeAnalysis.CSharp.Test.Utilities;
+using Microsoft.CodeAnalysis.Test.Utilities;
+using Roslyn.Test.Utilities;
+using Xunit;
+
+namespace Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen
+{
+    public class PatternTests : EmitMetadataTestBase
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs]: I would put these tests next to the other pattern-matching tests. It is very convenient when all tests for a feature are next to each other, rather than spread across different test binaries.

**Comment by gafter** [comment]
@jaredpar May I have permission to merge please?

**Comment by jaredpar** [comment]
Approved
