### PR TITLE
Fix comparer for sorting enums in SymbolDisplay

### LINKED ISSUE #22507: Mousing over enums can crash the IDE due to exception in the compiler
> I work on large solution and we have the following:
>
>using System;
>
>namespace NamespaceName
>{
[Flags]
public enum SomeTypes : long
{
Default = 0,
TypeA = 2,
TypeB = 4,
TypeC = 1024,
TypeD = 1048576,
TypeE = 2097152,
TypeF = 33554432,
TypeG = 67108864,
TypeH = 134217728,
TypeI = 1073741824,
TypeJ = 2147483648,
TypeK = 4294967296,
TypeL = 1099511627776,
TypeM = 2199023255552,
TypeN = 4398046511104,
TypeO = 1125899906842624,
TypeP = 2251799813685248,
TypeQ = 4503599627370496,
TypeR = 9007199254740992,
TypeS = 18014398509481984,
TypeT = 2305843009213693952
}
}
>
>"SomeTypes" is defined in an assembly, which is loaded from NuGet repo and used in the Actual Solution.
>
>SomeTypes is used in the Actual Solution:
>
>if (instance.HasAnySubtype(SomeTypes.TypeF | SomeTypes.TypeG))
>
>So in VS2017 when you'd move mouse over "TypeF" OR "TypeG" of the aforementioned snippet, VS would crash.
>
>In Windows "EventViewer -> Windows Logs -> Application" a stack trace of the exception can be found. (see an attachment)
>
>Please, fix the bug. It's really annoying and is causing troubles for at least half a year.

Stack trace:
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.ArgumentException: Unable to sort because the IComparer.Compare() method returns inconsistent results. Either a value does not compare equal to itself, or one value repeatedly compared to another value yields different results. IComparer: 'Roslyn.Utilities.EnumField+EnumFieldComparer'.
   at System.Collections.Generic.IntrospectiveSortUtilities.ThrowOrIgnoreBadComparer(Object comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at Microsoft.CodeAnalysis.SymbolDisplay.AbstractSymbolDisplayVisitor.GetSortedEnumFields(INamedTypeSymbol enumType, ArrayBuilder`1 enumFields)
   at Microsoft.CodeAnalysis.SymbolDisplay.AbstractSymbolDisplayVisitor.AddFlagsEnumConstantValue(INamedTypeSymbol enumType, Object constantValue, Boolean preferNumericValueOrExpandedFlags)
   at Microsoft.CodeAnalysis.SymbolDisplay.AbstractSymbolDisplayVisitor.AddEnumConstantValue(INamedTypeSymbol enumType, Object constantValue, Boolean preferNumericValueOrExpandedFlags)
   at Microsoft.CodeAnalysis.SymbolDisplay.AbstractSymbolDisplayVisitor.AddNonNullConstantValue(ITypeSymbol type, Object constantValue, Boolean preferNumericValueOrExpandedFlagsForEnum)
   at Microsoft.CodeAnalysis.CSharp.SymbolDisplayVisitor.AddConstantValue(ITypeSymbol type, Object constantValue, Boolean preferNumericValueOrExpandedFlagsForEnum)
   at Microsoft.CodeAnalysis.CSharp.SymbolDisplayVisitor.VisitField(IFieldSymbol symbol)
   at Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol.Accept(SymbolVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.SymbolDisplay.ToDisplayParts(ISymbol symbol, SemanticModel semanticModelOpt, Int32 positionOpt, SymbolDisplayFormat format, Boolean minimal)
   at Microsoft.CodeAnalysis.CSharp.SymbolDisplay.ToMinimalDisplayParts(ISymbol symbol, SemanticModel semanticModel, Int32 position, SymbolDisplayFormat format)
   at Microsoft.CodeAnalysis.CSharp.Symbol.Microsoft.CodeAnalysis.ISymbol.ToMinimalDisplayParts(SemanticModel semanticModel, Int32 position, SymbolDisplayFormat format)
   at Microsoft.CodeAnalysis.Editor.CSharp.LanguageServices.CSharpSymbolDisplayService.ToMinimalDisplayParts(SemanticModel semanticModel, Int32 position, ISymbol symbol, SymbolDisplayFormat format)
   at Microsoft.CodeAnalysis.LanguageServices.AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.ToMinimalDisplayParts(ISymbol symbol, SymbolDisplayFormat format)
   at Microsoft.CodeAnalysis.LanguageServices.AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.<GetFieldPartsAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.LanguageServices.AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.<AddDescriptionForFieldAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.LanguageServices.AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.<AddDescriptionPartAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.LanguageServices.AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.<AddPartsAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.LanguageServices.AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.<BuildDescriptionSectionsAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.LanguageServices.AbstractSymbolDisplayService.<ToDescriptionGroupsAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.AbstractSemanticQuickInfoProvider.<CreateContentAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.AbstractSemanticQuickInfoProvider.<BuildContentAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.AbstractQuickInfoProvider.<GetQuickInfoItemAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.AbstractQuickInfoProvider.<GetItemAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.Controller.<ComputeModelInBackgroundAsync>d__9.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(System.Exception)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.Controller+<ComputeModelInBackgroundAsync>d__9.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.Controller+<ComputeModelInBackgroundAsync>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.Controller+<ComputeModelInBackgroundAsync>d__9, Microsoft.CodeAnalysis.EditorFeatures, Version=2.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ComputeModelInBackgroundAsync>d__9 ByRef)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.Controller.ComputeModelInBackgroundAsync(Int32, Microsoft.VisualStudio.Text.ITextSnapshot, System.Collections.Generic.IList`1<Microsoft.CodeAnalysis.Editor.IQuickInfoProvider>, Boolean, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.Controller+<>c__DisplayClass7_0.<StartSession>b__0(Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.QuickInfo.Model, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.ModelComputation`1+<>c__DisplayClass17_0[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<ChainTaskAndNotifyControllerWhenFinished>b__0(System.Threading.Tasks.Task`1<System.__Canon>)
   at Roslyn.Utilities.TaskExtensions+<>c__DisplayClass16_0`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<SafeContinueWithFromAsync>b__0(System.Threading.Tasks.Task)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

### PR DESCRIPTION
**Pull request by agocke**
**Customer scenario**

When mousing over enums fields with values in the highest end of the unsigned long range,
SymbolDisplay can throw an exception while sorting the enum and crash Visual Studio.

**Bugs this fixes:**

Fixes #22507

**Workarounds, if any**

Do not hover over any enum field that is a member of an enum with one of these
enum fields.

**Risk**

This is, I believe, the minimal fix for this scenario. It's probable that any possible
fix in this area is a breaking change, but the change would be that a `Flags` enum
field shown in symbol display could result in a different order of enum members, i.e.
if the enum display for flags components was `E.A | E.B`, it could instead be `E.B | E.A`
or, in some cases, it may cause some other enum member, `E.C` that exactly matches to
be chosen instead.

To my knowledge, this is purely aesthetic. It does not affect the compiled code in any way.

**Performance impact**

Minimal, just an extra call to `long.CompareTo`.

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

This is a somewhat esoteric edge case and it looks like this code was
translated fairly literally from C++ in the native compiler or the EE, so
it's possible that this code worked in C++ and no longer works in C#
due to correct sorting or different conversion routines.

By using standard C# idioms and library calls, this should be much more
resilient code.

**How was the bug found?**

Customer reported through VS feedback.

**Test documentation updated?**

N/A

### CODE REVIEW

**Comment by agocke** [comment]
@jaredpar To bar check for 15.5

File: src/Compilers/Core/Portable/InternalUtilities/EnumField.cs [hunk 1]
```diff
@@ -71,10 +71,10 @@ private class EnumFieldComparer : IComparer<EnumField>
             int IComparer<EnumField>.Compare(EnumField field1, EnumField field2)
             {
                 // Sort order is descending value, then ascending name.
-                var diff = unchecked((long)field2.Value - (long)field1.Value);
+                int diff = unchecked(((long)field2.Value).CompareTo((long)field1.Value));
```
Comment (jcouv) [inline src/Compilers/Core/Portable/InternalUtilities/EnumField.cs]: Do we still need the `unchecked`?

File: src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs [hunk 2]
```diff
@@ -11,13 +11,62 @@
...
+using Roslyn.Utilities;
 using Xunit;
 
 namespace Microsoft.CodeAnalysis.CSharp.UnitTests
 {
     public class SymbolDisplayTests : CSharpTestBase
     {
         [Fact]
+        [WorkItem(22507, "https://github.com/dotnet/roslyn/issues/22507")]
+        public void Repro22507()
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs]: Consider moving test to the end of the file rather than the start, so simple cases are earlier.

File: src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs [hunk 3]
```diff
@@ -11,13 +11,62 @@
...
+    TypeL = 1099511627776,
+    TypeM = 2199023255552,
+    TypeN = 4398046511104,
+    TypeO = 1125899906842624,
+    TypeP = 2251799813685248,
+    TypeQ = 4503599627370496,
+    TypeR = 9007199254740992,
+    TypeS = 18014398509481984,
+    TypeT = 2305843009213693952
+}
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs]: Is there a simpler repro, with just two values perhaps?

File: src/Compilers/Core/Portable/InternalUtilities/EnumField.cs (hunk 1 above)
Comment (agocke) [reply src/Compilers/Core/Portable/InternalUtilities/EnumField.cs]: I believe the conversion from `ulong` to `long` requires it, per Section 6.2.1, "Explicit numeric conversions":

> In a checked context, the conversion succeeds if the value of the source operand is within the range of the destination type, but throws a System.OverflowException if the value of the source operand is outside the range of the destination type.

File: src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs (hunk 3 above)
Comment (agocke) [reply src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs]: I'm certain there is, but isn't it better to use the full repro as a regression test?

File: src/Compilers/Core/Portable/InternalUtilities/EnumField.cs (hunk 1 above)
Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/InternalUtilities/EnumField.cs]: I'm terrified that the compiler devs aren't sure.

Comment (jaredpar) [reply src/Compilers/Core/Portable/InternalUtilities/EnumField.cs]: We compile all our code in unchecked though ...

File: src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs (hunk 3 above)
Comment (agocke) [reply src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs]: I've added a unit test to directly demonstrate the enum comparer problem since the customer repro is very close to a minimal repro to actually produce an exception.

File: src/Compilers/Core/Portable/InternalUtilities/EnumField.cs (hunk 1 above)
Comment (agocke) [reply src/Compilers/Core/Portable/InternalUtilities/EnumField.cs]: I have confirmed that it is required if we ever compile in a checked context. (which I thought we did for Debug?) Anyway, I dislike ever relying on ambient checked/unchecked context since it has no way to demonstrate the intent of the developer.

**Comment by MeiChin-Tsai** [comment]
approved.

**Comment by agocke** [comment]
@cston Does my additional test match your expectations?
