### PR TITLE
Pattern-matching fixes for ITuple, short tuple patterns, and nulls

### LINKED ISSUE #30906: Matching nullables with var pattern
**Version Used**: features/recursive-patterns

**Steps to Reproduce**:

```cs
using System;
class C {
    extern static (int, int)? Get();   

    static void Test() {
        if (Get() is var (x, y)) {
            Console.Write(x);   
            Console.Write(y);   
        }
    }
}
```

**Expected Behavior**: Should check for HasValue and deconstruct.

**Actual Behavior**: Error.

Note: should work for any deconstructible, not just tuples.
Note: in effect, this should be equivalent to the `(var x, var y)` pattern.

### LINKED ISSUE #30962: Pattern-matching changes for short tuples
Adjust the implementation of pattern-matching to reflect LDM [resolutions from 2018-11-05](https://github.com/dotnet/csharplang/issues/1054#issuecomment-436025050).  The last point will be included in the changes for https://github.com/dotnet/roslyn/issues/20648.

### **Proposed:**

1. If the type is a tuple type (any arity >=0; see below), then use the tuple semantics
2. if the type has no accessible instance `Deconstruct`, and satisfies the `ITuple` deconstruct constraints, use `ITuple` semantics
3. Otherwise attempt `Deconstruct` semantics (instance or extension)

Alternative
1. If the type is a tuple type (any arity >= 0; see below), then use the tuple semantics
2. If "binding" a Deconstruct invocation would finds one or more applicable methods, use Deconstruct.
3. if the satisfies the `ITuple` deconstruct constraints, use `ITuple` semantics

In both cases, 4. Error

***Decision***: Alternative

### Proposed:

1. Permit pattern-matching tuple patterns with 0 and 1 elements (appropriately disambiguated as previously decided)

``` c#
if (e is ()) ...

if (e is (1) _) ...
if (e is (x: 1)) ...

if (e is (1, 2)) ...
```

***Conclusion***: Approved

### Proposed:

As part of this, I propose that we consider `System.ValueTuple<T>` instantitations to be considered tuple types.  I do not propose any syntax changes related to this.

As part of this, I propose that we consider `System.ValueTuple` to be considered a tuple type.  I do not propose any syntax changes related to this.

***Conclusion***: Approved

### LINKED ISSUE #31031: "No suitable Deconstruct instance or extension method was found" is incorrect
Compiling the following reports (among other things) that `CS8129 No suitable Deconstruct instance or extension method was found for type 'IA', with 2 out parameters and a void return type.`

``` c#
using System;

class Program
{
    static void Main()
    {
        IA a = new A();
        (var x, var y) = a;
    }
}
interface I1
{
    void Deconstruct(out int X, out int Y);
}
interface I2
{
    void Deconstruct(out int X, out int Y);
}
interface IA : I1, I2 { }
class A : IA, I1, I2
{
    void I1.Deconstruct(out int X, out int Y) => (X, Y) = (3, 4);
    void I2.Deconstruct(out int X, out int Y) => (X, Y) = (7, 8);
}
```

However, there are indeed suitable `Deconstruct` instance methods for type `IA`. In fact there are too many of them. This diagnostic is simply incorrect.

### PR DESCRIPTION
**Pull request by gafter**
* Implement LDM disambiguation rules for Deconstruct vs ITuple
* Permit 0-element and 1-element tuple patterns
Fixes #30962
Replaces #31027

* Handle null and nullable input for a var pattern with a tuple designation
Fixes #30906
Replaces #30935

* Don't report missing Deconstruct when there is more than one applicable Deconstruct
Fixes #31031

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 1]
```diff
@@ -476,22 +475,68 @@ TypeSymbol BindRecursivePatternType(TypeSyntax typeSyntax, TypeSymbol inputType,
...
         }
 
+        // Work around https://github.com/dotnet/roslyn/issues/20648: The compiler's internal APIs such as `declType.IsTupleType`
+        // do not correctly treat the non-generic struct `System.ValueTuple` as a tuple type.  We explicitly perform the tests
+        // required to identify it.  When that bug is fixed we should be able to remove this code and its callers.
+        internal static bool IsZeroElementTupleType(TypeSymbol type)
+        {
+            return type.IsStructType() && type.Name == "ValueTuple" && type.GetArity() == 0 && type.ContainingSymbol is var declContainer &&
+                declContainer.Kind == SymbolKind.Namespace && declContainer.Name == "System" && declContainer.ContainingSymbol?.Kind == SymbolKind.Namespace &&
+                declContainer.ContainingSymbol.ContainingSymbol?.Kind == SymbolKind.NetModule;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: Checking for `NetModule` seems unnecessary. Could we simply check `(declContainer.ContainingSymbol as NamespaceSymbol)?.IsGlobalNamespace == true`?

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 2]
```diff
@@ -476,22 +475,68 @@ TypeSymbol BindRecursivePatternType(TypeSyntax typeSyntax, TypeSymbol inputType,
...
+                        deconstructClause.Subpatterns.Count, inputPlaceholder, deconstructClause, deconstructDiagnostics, outPlaceholders: out ImmutableArray<BoundDeconstructValuePlaceholder> outPlaceholders,
+                        out bool anyDeconstructCandidates);
+                    if (!anyDeconstructCandidates && ShouldUseITupleForRecursivePattern(node, declType, diagnostics, out var iTupleType, out var iTupleGetLength, out var iTupleGetItem))
+                    {
+                        // There was no Deconstruct, but the constraints for the use of ITuple are satisfied.
+                        // Use that and forget any errors from trying to bind Deconstruct.
+                        deconstructDiagnostics.Free();
+                        BindITupleSubpatterns(deconstructClause, patterns, diagnostics);
+                        deconstructionSubpatterns = patterns.ToImmutableAndFree();
+                        return new BoundITuplePattern(node, iTupleGetLength, iTupleGetItem, deconstructionSubpatterns, inputType, hasErrors);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: >return new BoundITuplePattern [](start = 24, length = 29)

Should `BindDeconstructSubpatterns()` be called? Might there be errors in the sub-patterns that are not related to the missing `Deconstruct`?

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 3]
```diff
@@ -770,66 +846,107 @@ private BoundPattern BindVarPattern(VarPatternSyntax node, TypeSymbol inputType,
...
                 case SyntaxKind.ParenthesizedVariableDesignation:
                     {
-                        var tupleDesignation = (ParenthesizedVariableDesignationSyntax)designation;
+                        var tupleDesignation = (ParenthesizedVariableDesignationSyntax)node;
                         var subPatterns = ArrayBuilder<BoundSubpattern>.GetInstance(tupleDesignation.Variables.Count);
                         MethodSymbol deconstructMethod = null;
-                        if (inputType.IsTupleType)
+                        var strippedInputType = inputType.StrippedType();
+
+                        if (IsZeroElementTupleType(strippedInputType))
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: >IsZeroElementTupleType(strippedInputType) [](start = 28, length = 41)

It looks like the only difference between this case and the `IsTupleType` case below is `elementTypes`. If so, would it make sense to extract a local function to share code where the caller passes in `elementTypes`?

**Comment by cston** [comment]
>                 if (symbol is FieldSymbol field && field.IsTupleElement())

`IsTupleElement()` is an extension method on `IFieldSymbol`. Perhaps use `IsTupleField` instead.

---
Refers to: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs:823 in 102de2f. [](commit_id = 102de2f3576805b604c22d8014f7fd7b5d173cf1, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 4]
```diff
@@ -500,137 +545,181 @@ private BoundPattern BindRecursivePattern(RecursivePatternSyntax node, TypeSymbo
...
-            out MethodSymbol deconstructMethod,
-            ref bool hasErrors)
+            ref bool hasErrors,
+            ArrayBuilder<BoundSubpattern> patterns,
+            DiagnosticBag diagnostics)
         {
-            deconstructMethod = null;
-            var patterns = ArrayBuilder<BoundSubpattern>.GetInstance(node.Subpatterns.Count);
-            if (declType.IsTupleType)
+            ImmutableArray<TypeSymbolWithAnnotations> elementTypes = declType.TupleElementTypes;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: >elementTypes [](start = 54, length = 12)

If `elementTypes` is passed in as a parameter, could `BoundValueTupleSubpatterns` be used for 0-element tuples as well?

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 5]
```diff
@@ -8370,30 +8370,50 @@ private StatementSyntax ParseLocalDeclarationStatement()
             }
         }
 
-        private VariableDesignationSyntax ParseDesignation()
+        private VariableDesignationSyntax ParseDesignation(bool forPattern)
         {
             // the two forms of designation are
             // (1) identifier
             // (2) ( designation ... )
+            // for pattern-matching, we permite the designation list to be empty
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: >permite [](start = 40, length = 7)

Typo?

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 6]
```diff
@@ -8370,30 +8370,50 @@ private StatementSyntax ParseLocalDeclarationStatement()
...
+                        }
                     }
-                    else
+                }
+                else
+                {
+                    listOfDesignations.Add(ParseDesignation(forPattern));
+                    listOfDesignations.AddSeparator(this.EatToken(SyntaxKind.CommaToken));
+
+                    while (true)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: >while (true) [](start = 20, length = 12)

Would it make sense to share the `while` loop between the two cases? Perhaps something like:
```c#
bool done = false;
if (forPattern)
{
    done = (this.CurrentToken.Kind == SyntaxKind.CloseParenToken);
}
else
{
    listOfDesignations.Add(ParseDesignation(forPattern));
    listOfDesignations.AddSeparator(EatToken(SyntaxKind.CommaToken));
}
if (!done)
{
    while (true)
    {
        // ...
    }
}
```

**Comment by cston** [comment]
>         }

Consider testing `static void Deconstruct(this ITuple tuple, ...) { }`.

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs:649 in 102de2f. [](commit_id = 102de2f3576805b604c22d8014f7fd7b5d173cf1, deletion_comment = False)

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs [hunk 7]
```diff
@@ -923,131 +838,423 @@ class C1
...
+    {
+        public T1 Item1;
+        public T2 Item2;
+        public ValueTuple(T1 item1, T2 item2) => (Item1, Item2) = (item1, item2);
+    }
+}
+";
+            var compilation = CreatePatternCompilation(source);
+            compilation.VerifyDiagnostics();
+            var expectedOutput = @"";
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs]: >@""; [](start = 33, length = 4)

Why doesn't `is var (x, y)` match `ValueTuple<T1, T2>`?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs [hunk 8]
```diff
@@ -923,131 +838,423 @@ class C1
...
+    {
+        for (int i = 0; i < 6; i++)
+        {
+            if (Get(i) is var (x, y))
+                Console.WriteLine($""{i} {x} {y}"");
+        }
+    }
+}
+
+// Provide a ValueTuple that DOES NOT implements ITuple
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs]: >that DOES NOT implements ITuple [](start = 24, length = 31)

`... with no Deconstruct method and ...`

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs [hunk 9]
```diff
@@ -1384,5 +1591,484 @@ class _
                 );
             CompileAndVerify(compilation, expectedOutput: "8");
         }
+
+        [Fact]
+        public void DeconstructVsITuple_01()
+        {
+            // From LDM 2018-11-05:
+            // 1. If the type is a tuple type (any arity >= 0; see below), then use the tuple semantics
+            // 2. If "binding" a Deconstruct invocation would finds one or more applicable methods, use Deconstruct.
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs]: >would finds [](start = 56, length = 11)

Typo?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs [hunk 10]
```diff
@@ -1384,5 +1591,484 @@ class _
...
+            // 3. If the satisfies the ITuple deconstruct constraints, use ITuple semantics
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs]: >the satisfies [](start = 21, length = 13)

`If the type satisfies ...`?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs [hunk 11]
```diff
@@ -1384,5 +1591,484 @@ class _
...
+}
+";
+            var compilation = CreatePatternCompilation(source);
+            compilation.VerifyDiagnostics(
+                );
+            CompileAndVerify(compilation, expectedOutput: "3 4");
+        }
+
+        [Fact]
+        public void DeconstructVsITuple_01b()
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs]: >DeconstructVsITuple_01b [](start = 20, length = 23)

Consider adding a comment on how this differs from previous test.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs [hunk 12]
```diff
@@ -1384,5 +1591,484 @@ class _
...
+            var compilation = CreatePatternCompilation(source);
+            compilation.VerifyDiagnostics(
+                // (8,22): error CS0121: The call is ambiguous between the following methods or properties: 'I1.Deconstruct(out int, out int)' and 'I2.Deconstruct(out int, out int)'
+                //         if (a is var (x, y)) Console.Write($"{x} {y}");
+                Diagnostic(ErrorCode.ERR_AmbigCall, "(x, y)").WithArguments("I1.Deconstruct(out int, out int)", "I2.Deconstruct(out int, out int)").WithLocation(8, 22)
+                );
+        }
+
+        [Fact]
+        public void DeconstructVsITuple_02b()
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs]: >DeconstructVsITuple_02b [](start = 20, length = 23)

Consider adding a comment on how this differs from previous test.

**Comment by gafter** [comment]
>                 if (symbol is FieldSymbol field && field.IsTupleElement())

Added [https://github.com/dotnet/roslyn/issues/20648#issuecomment-438093884](https://github.com/dotnet/roslyn/issues/20648#issuecomment-438093884) to track this

---
In reply to: [438087900](https://github.com/dotnet/roslyn/pull/31056#issuecomment-438087900) [](ancestors = 438087900,437406528)

---
Refers to: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs:823 in 102de2f. [](commit_id = 102de2f3576805b604c22d8014f7fd7b5d173cf1, deletion_comment = False)

**Comment by gafter** [comment]
@cston I think this iteration responds to all of your comments. Do you have any others?

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 13]
```diff
@@ -476,22 +475,68 @@ TypeSymbol BindRecursivePatternType(TypeSyntax typeSyntax, TypeSymbol inputType,
             }
         }
 
+        // Work around https://github.com/dotnet/roslyn/issues/20648: The compiler's internal APIs such as `declType.IsTupleType`
+        // do not correctly treat the non-generic struct `System.ValueTuple` as a tuple type.  We explicitly perform the tests
+        // required to identify it.  When that bug is fixed we should be able to remove this code and its callers.
+        internal static bool IsZeroElementTupleType(TypeSymbol type)
+        {
+            return type.IsStructType() && type.Name == "ValueTuple" && type.GetArity() == 0 && type.ContainingSymbol is var declContainer &&
+                declContainer.Kind == SymbolKind.Namespace && declContainer.Name == "System" && declContainer.ContainingSymbol?.Kind == SymbolKind.Namespace &&
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: >declContainer.ContainingSymbol?.Kind == SymbolKind.Namespace && [](start = 96, length = 63)

This clause is no longer necessary.

**Comment by jcouv** [comment]
Do you have a speclet for the feature? It would make sense to update along with the PR.

**Comment by gafter** [comment]
A speclet for recursive patterns is still in the works.  Tracked as https://github.com/dotnet/roslyn/issues/28975

**Comment by gafter** [comment]
@agocke @jcouv Could either of you please review this?

File: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs [hunk 14]
```diff
@@ -459,6 +459,14 @@ private static void Assert(bool condition, string message = null)
                         MakeTestsAndBindings(output, pattern, tests, bindings);
                     }
                 }
+                else if (Binder.IsZeroElementTupleType(inputType))
+                {
+                    // Work around https://github.com/dotnet/roslyn/issues/20648: The compiler's internal APIs such as `declType.IsTupleType`
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs]: >// Work around https://github.com/dotnet/roslyn/issues/20648: [](start = 20, length = 61)

nit: Consider removing this comment since it is already captured in `Binder.IsZeroElementTupleType`

File: src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs [hunk 15]
```diff
@@ -1915,16 +1912,13 @@ public void ParenthesizedExpression_04()
             UsingStatement(@"switch (e) { case (((x: 3))): ; }", TestOptions.RegularWithoutRecursivePatterns,
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs]: >case (((x: 3))): [](start = 42, length = 16)

Could you add a test with pattern `((3))` too?

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 16]
```diff
@@ -485,22 +484,68 @@ TypeSymbol BindRecursivePatternType(TypeSyntax typeSyntax, TypeSymbol inputType,
             }
         }
 
+        // Work around https://github.com/dotnet/roslyn/issues/20648: The compiler's internal APIs such as `declType.IsTupleType`
+        // do not correctly treat the non-generic struct `System.ValueTuple` as a tuple type.  We explicitly perform the tests
+        // required to identify it.  When that bug is fixed we should be able to remove this code and its callers.
+        internal static bool IsZeroElementTupleType(TypeSymbol type)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: >IsZeroElementTupleType [](start = 29, length = 22)

Would it be simpler go get the well-known type `ValueTuple` and compare them?

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 17]
```diff
@@ -485,22 +484,68 @@ TypeSymbol BindRecursivePatternType(TypeSyntax typeSyntax, TypeSymbol inputType,
...
-                return BindITuplePattern(node, inputType, iTupleType, iTupleGetLength, iTupleGetItem, hasErrors, diagnostics);
-            }
-
             MethodSymbol deconstructMethod = null;
             ImmutableArray<BoundSubpattern> deconstructionSubpatterns = default;
             if (node.DeconstructionPatternClause != null)
             {
-                deconstructionSubpatterns = BindDeconstructionPatternClause(node.DeconstructionPatternClause, declType, inputValEscape, diagnostics, out deconstructMethod, ref hasErrors);
+                DeconstructionPatternClauseSyntax deconstructClause = node.DeconstructionPatternClause;
+                Debug.Assert(deconstructClause != null);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: >Debug.Assert(deconstructClause != null); [](start = 16, length = 40)

nit: assertion doesn't add much, since checked two lines above

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 18]
```diff
@@ -485,22 +484,68 @@ TypeSymbol BindRecursivePatternType(TypeSyntax typeSyntax, TypeSymbol inputType,
...
+                deconstructMethod = null;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: >deconstructMethod = null; [](start = 16, length = 25)

assignment seem unnecessary since initialized with `null` already

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 19]
```diff
@@ -485,22 +484,68 @@ TypeSymbol BindRecursivePatternType(TypeSyntax typeSyntax, TypeSymbol inputType,
...
+                var patterns = ArrayBuilder<BoundSubpattern>.GetInstance(deconstructClause.Subpatterns.Count);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: >patterns [](start = 20, length = 8)

Rename to `patternsBuilder`?

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 20]
```diff
@@ -485,22 +484,68 @@ TypeSymbol BindRecursivePatternType(TypeSyntax typeSyntax, TypeSymbol inputType,
...
+                    }
+                    else
+                    {
+                        diagnostics.AddRangeAndFree(deconstructDiagnostics);
+                    }
+
+                    deconstructMethod = BindDeconstructSubpatterns(deconstructClause, inputValEscape, deconstruct, outPlaceholders, patterns, ref hasErrors, diagnostics);
+                }
+
+                deconstructionSubpatterns = patterns.ToImmutableAndFree();
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: >deconstructionSubpatterns = patterns.ToImmutableAndFree(); [](start = 16, length = 58)

The flow of this method would be easier to follow if `BindValueTupleSubpatterns` and `BindDeconstructSubpatterns` returned patterns (which we would store into `deconstructionSubpatterns`).
`BindDeconstructSubpatterns` would set `deconstructMethod` via a secondary output (an `out` parameter).

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 21]
```diff
@@ -509,137 +554,144 @@ private BoundPattern BindRecursivePattern(RecursivePatternSyntax node, TypeSymbo
...
                     diagnostics.Add(ErrorCode.ERR_ArgumentNameInITuplePattern, subpatternSyntax.NameColon.Location);
                 }
 
-                // Since the input has been cast to ITuple, it must be escapable.
-                const uint valEscape = Binder.ExternalScope;
                 var boundSubpattern = new BoundSubpattern(
                     subpatternSyntax,
                     null,
-                    BindPattern(subpatternSyntax.Pattern, elementType, valEscape, false, diagnostics));
+                    BindPattern(subpatternSyntax.Pattern, objectType, valEscape, false, diagnostics));
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: >false [](start = 81, length = 5)

nit: consider naming `hasErrors: false` (here and below)

**Comment by jcouv** [comment]
>         if (c2 is C2(1, 2) {}) {}  // [7]

Just to confirm, the type in a pattern cannot be a tuple type. That would be a parsing error, correct?
`c2 is (int, int) (1, 2) ...`
Do we have a test already?

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs:844 in bbcf265. [](commit_id = bbcf2655c0eaab4385000afc7c2aea9905959260, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 22]
```diff
@@ -779,66 +818,99 @@ private BoundPattern BindVarPattern(VarPatternSyntax node, TypeSymbol inputType,
...
                 case SyntaxKind.ParenthesizedVariableDesignation:
                     {
-                        var tupleDesignation = (ParenthesizedVariableDesignationSyntax)designation;
+                        var tupleDesignation = (ParenthesizedVariableDesignationSyntax)node;
                         var subPatterns = ArrayBuilder<BoundSubpattern>.GetInstance(tupleDesignation.Variables.Count);
                         MethodSymbol deconstructMethod = null;
-                        if (inputType.IsTupleType)
+                        var strippedInputType = inputType.StrippedType();
+
+                        void addSubpatternsForTuple(ImmutableArray<TypeSymbolWithAnnotations> elementTypes)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: >addSubpatternsForTuple [](start = 29, length = 22)

Please move local function to the end of the method to keep the code flow clear. Thanks

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 23]
```diff
@@ -779,66 +818,99 @@ private BoundPattern BindVarPattern(VarPatternSyntax node, TypeSymbol inputType,
...
+                                BindITupleSubpatterns(tupleDesignation, subPatterns, diagnostics);
+                                return new BoundITuplePattern(node, iTupleGetLength, iTupleGetItem, subPatterns.ToImmutableAndFree(), strippedInputType, hasErrors);
+                            }
+                            else
+                            {
+                                diagnostics.AddRangeAndFree(deconstructDiagnostics);
+                            }
+
                             deconstructMethod = deconstruct.ExpressionSymbol as MethodSymbol;
+                            if (!hasErrors)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: >) [](start = 42, length = 1)

braces?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs [hunk 24]
```diff
@@ -246,32 +246,13 @@ public static void Main()
...
-                //         Console.WriteLine(t is (3, 4, 5, 6)); // false
-                Diagnostic(ErrorCode.ERR_MissingDeconstruct, "(3, 4, 5, 6)").WithArguments("C", "4").WithLocation(13, 32)
-                );
+            compilation.VerifyDiagnostics();
+            var expectedOutput =
+@"False
+True
+False
+False";
+            var compVerifier = CompileAndVerify(compilation, expectedOutput: expectedOutput);
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs]: >var compVerifier =  [](start = 12, length = 19)

unused local

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs [hunk 25]
```diff
@@ -713,27 +627,63 @@ public class C : ITuple
...
+        [Fact]
+        public void ITuple_09b()
+        {
+            // - An extension Deconstruct hides ITuple
+            var source =
+@"using System;
+using System.Runtime.CompilerServices;
+public class C : ITuple
+{
+    int ITuple.Length => 4;
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs]: >4; [](start = 25, length = 2)

Consider splitting this test. One test would have the ITuple implementation throw.
Also, three of the comments say the same thing but in different ways...

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs [hunk 26]
```diff
@@ -1489,6 +1731,557 @@ static int M1(bool? b1, bool? b2)
...
+    }
+}
+interface IA : ITuple
+{
+    void Deconstruct(out int X, out int Y);
+}
+class A: IA, ITuple
+{
+    void IA.Deconstruct(out int X, out int Y) => (X, Y) = (3, 4);
+    int ITuple.Length => 2;
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs]: >2; [](start = 25, length = 2)

Consider throwing for members that don't participate in execution. (also applies in other tests below)

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs [hunk 27]
```diff
@@ -1489,6 +1731,557 @@ static int M1(bool? b1, bool? b2)
...
+        public void DeconstructVsITuple_02b()
+        {
+            // From LDM 2018-11-05:
+            // 1. If the type is a tuple type (any arity >= 0; see below), then use the tuple semantics
+            // 2. If "binding" a Deconstruct invocation would find one or more applicable methods, use Deconstruct.
+            // 3. If the type satisfies the ITuple deconstruct constraints, use ITuple semantics
+            // Here we test the relative priority of steps 2 and 3.
+            // - Found more than one applicable Deconstruct method (even though the type implements ITuple): error
+
+            // case 1: tuple pattern with var subpatterns
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs]: >case 1 [](start = 15, length = 6)

I didn't understand what "case 1" refers to

File: src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs (hunk 15 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs]: See existing test `ParenthesizedExpression_01`.

---
In reply to: [234822088](https://github.com/dotnet/roslyn/pull/31056#discussion_r234822088) [](ancestors = 234822088)

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs (hunk 16 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: No; there can be more than one tuple type imported from different assemblies.

---
In reply to: [234822985](https://github.com/dotnet/roslyn/pull/31056#discussion_r234822985) [](ancestors = 234822985)

Comment (jcouv) [reply src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: Sorry, one more question on this: would `IsTupleCompatible` do the job?

---
In reply to: [237273866](https://github.com/dotnet/roslyn/pull/31056#discussion_r237273866) [](ancestors = 237273866,234822985)

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs (hunk 20 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: They produce multiple subpatterns, not a single pattern, which is why they go into a builder.

---
In reply to: [234825978](https://github.com/dotnet/roslyn/pull/31056#discussion_r234825978) [](ancestors = 234825978)

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs (hunk 22 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: Cannot do so as it uses variables declared in this scope.

---
In reply to: [234839194](https://github.com/dotnet/roslyn/pull/31056#discussion_r234839194) [](ancestors = 234839194)

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs (hunk 23 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: I'd rather remove unnecessary braces.

---
In reply to: [234839920](https://github.com/dotnet/roslyn/pull/31056#discussion_r234839920) [](ancestors = 234839920)

**Comment by gafter** [comment]
>         if (c2 is C2(1, 2) {}) {}  // [7]

We do have parsing tests that show this is a syntax error.

---
In reply to: [440095022](https://github.com/dotnet/roslyn/pull/31056#issuecomment-440095022) [](ancestors = 440095022)

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests4.cs:844 in bbcf265. [](commit_id = bbcf2655c0eaab4385000afc7c2aea9905959260, deletion_comment = False)
