### PR TITLE
Remove dependency on Microsoft.CodeAnalysis.Workspaces

### LINKED ISSUE #3706: FixerWithFixAllAnalyzer does not run in the compiler
The [FixerWithFixAllAnalyzer](https://github.com/dotnet/roslyn/blob/master/src/Diagnostics/CodeAnalysis/Core/FixAnalyzers/FixerWithFixAllAnalyzer.cs) takes a dependency on the `CodeFixProvider` and `CodeAction` types in Microsoft.CodeAnalysis.Workspaces.dll. For example:
``` C#
private static string CodeFixProviderMetadataName = typeof(CodeFixProvider).FullName;
```

This works fine in VS but causes a `TypeInitializationException` in the compilers because Microsoft.CodeAnalysis.Workspaces.dll is not available.

This should be relatively easy to fix: just replace `typeof(CodeFixProvider).FullName` with `"Microsoft.CodeAnalysis.CodeFixes.CodeFixProvider"`, and make the related change for `CodeAction`.

### PR DESCRIPTION
**Pull request by tmeschter**
FixerWithFixAllAnalyzer references types in the Workspaces assembly in a
couple of places:
``` C#
private static string CodeFixProviderMetadataName = typeof(CodeFixProvider).FullName;
```

This creates a runtime dependency on Microsoft.CodeAnalysis.Workspaces.dll
which is part of VS but not part of the compilers (csc/vbc/vbcscompiler).
The analyzers that derive from this type thus work in VS but fail during
build with a `TypeInitializationException`.

The fix is to use hard-coded strings for the names of these types. As
they are part of the public API, their names won't be changing anytime
soon.

This does not remove the project-to-project reference to Workspaces.
Doing so would have required fixing up a bunch of `<see cref="..." />`
elements in the doc comments to use the full name of these types as well,
generally making them much uglier. This isn't necessary to fix the
runtime issue.

Fixes #3706.

### CODE REVIEW

**Comment by tmeschter** [comment]
@mavasani @shyamnamboodiripad @heejaechang @jmarolf @srivatsn @ManishJayaswal Please take a look, if you would.

**Comment by shyamnamboodiripad** [comment]
:+1:

**Comment by tmeschter** [comment]
@dotnet-bot Retest this, please.

**Comment by tmeschter** [comment]
@dotnet-bot Retest this, please.

**Comment by AdamSpeight2008** [comment]
Can we get that name at compile-time? via `namof`?

File: src/Diagnostics/CodeAnalysis/Core/FixAnalyzers/FixerWithFixAllAnalyzer.cs [hunk 1]
```diff
@@ -18,9 +18,9 @@ namespace Microsoft.CodeAnalysis.Analyzers.FixAnalyzers
     /// </summary>
     public abstract class FixerWithFixAllAnalyzer<TLanguageKindEnum> : DiagnosticAnalyzer
         where TLanguageKindEnum: struct
-    {
-        private static string CodeFixProviderMetadataName = typeof(CodeFixProvider).FullName;
-        private static string CodeActionMetadataName = typeof(CodeAction).FullName;
+    { 
+        private static string CodeFixProviderMetadataName = "Microsoft.CodeAnalysis.CodeFixes.CodeFixProvider";
```
Comment (pharring) [inline src/Diagnostics/CodeAnalysis/Core/FixAnalyzers/FixerWithFixAllAnalyzer.cs]: Could be 'const' instead of 'static' now.

**Comment by tmeschter** [comment]
@AdamSpeight2008 Not the full name, no.

**Comment by AdamSpeight2008** [comment]
@tmeschter  Why?
This part seems reasonable.
```c#
static const string CodeFixProviderMetadateName =
 nameof(  Microsoft.CodeAnalysis.CodeFixes.CodeFixProvider );
```

**Comment by tmeschter** [comment]
@AdamSpeight2008 Because `nameof(...)` gives you the *name*, not the *full name*. That is:
``` C#
nameof(Microsoft.CodeAnalysis.CodeFixes.CodeFixProvider) != "Microsoft.CodeAnalysis.CodeFixes.CodeFixProvider"
nameof(Microsoft.CodeAnalysis.CodeFixes.CodeFixProvider) == "CodeFixProvider"
```

**Comment by AdamSpeight2008** [comment]
@tmeschter  Then maybe it should with some optional parameters. 

`nameof( ... , nameofoptions:= option.FullName )`

**Comment by tmeschter** [comment]
@dotnet-bot Retest this, please.

**Comment by tmeschter** [comment]
@dotnet-bot Retest this, please.

**Comment by heejaechang** [comment]
@AdamSpeight2008 where do you get this symbol (Microsoft.CodeAnalysis.CodeFixes.CodeFixProvider) for nameof if you don't have reference to workspace?

**Comment by AdamSpeight2008** [comment]
@heejaechang It was used as an example, of a fully qualified name.

**Comment by heejaechang** [comment]
@AdamSpeight2008 that you probably need to open a suggestion (new issue) and label language-design + feature request.
