### PR TITLE
Address issues with nullable flow analysis slot container types and changing types during inference

### LINKED ISSUE #33428: Ensure NullableWalker.InheritNullableStateOfMember is not copying state for invalid members
`NullableWalker.InheritNullableStateOfMember` should assert the member is valid for value and target.

### LINKED ISSUE #39220: Roslyn doesn't handle inferred nullability in the presence of `goto`.
**Version Used**: 
```
Branch master (23 Sep 2019)
Latest commit 89b4f60 by Charles Stoner:
Allow conversion of collection initializer Add extension method this arg (#38732)
```

**Steps to Reproduce**:

Compile and run the following code:
```cs
#nullable enable
class C<T>
{
  public C(T t) => Property = t;
  public T Property { get; }
}

class Program
{
  static void Main()
  {
    Test("");
  }
  
  static void Test(string? s)
  {
    if (s == null) return;
    
    hell:
    var c = GetC(s);
    switch (c)
    {
      case { Property: var prop }:
        prop.ToString();
        break;
    }
    
    s = null;
    goto hell;
  }
  
  public static C<T> GetC<T>(T t) => new C<T>(t);
}
```

**Expected Behavior**:
`warning CS8602: Dereference of a possibly null reference.` reported for `prop.ToString()`

**Actual Behavior**:
No warnings are reported for the program above. The program crashes at runtime with a `NullReferenceException`

**Notes**
If you specify the type of `c` explicitly i.e. `C<string?> c = GetC(s);` you'll get the correct warning.

### LINKED ISSUE #39297: NullableWalker violates invariants of slot and slot parents
I tried adding the following assertion

``` c#
                HashSet<DiagnosticInfo> discardedUseSiteDiagnostics = null;
                Debug.Assert(
                    symbol.Kind != SymbolKind.Field || // we only check fields, but the NullableWalker also works with properties
                    containingSlot == 0 && !symbol.RequiresInstanceReceiver() ||
                    symbol.ContainingType.Equals(variableBySlot[containingSlot].Symbol.GetTypeOrReturnType().Type, TypeCompareKind.AllIgnoreOptions) ||
                    compilation.Conversions.IsBaseClass(variableBySlot[containingSlot].Symbol.GetTypeOrReturnType().Type, symbol.ContainingType, ref discardedUseSiteDiagnostics));
```

before the following line in `LocalDataFlowPass.cs`

``` c#
                variableBySlot[slot] = identifier;
```

but there are a number of failures (of this assertion) in `NullableWalker`.  It is possible that some of these are symptoms of https://github.com/dotnet/roslyn/issues/20648 but I believe at least the failure in `NullableReferenceTypesTests.Conversions_TupleConversions_03` and two other tests is a deeper problem.  I am skipping those tests to make progress on https://github.com/dotnet/roslyn/issues/39220, and I removing the assertion for now.  The assertion should be readded after https://github.com/dotnet/roslyn/issues/20648 has been fixed and any issues causing the assertion to fail should be reevaluated.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #39220
Fixes #39297
Fixes #33428

### CODE REVIEW

**Comment by gafter** [comment]
@cston Can you please have a look at this?  We discussed this earlier today.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 1]
```diff
@@ -681,6 +681,73 @@ private static BoundNode Rewrite(ImmutableDictionary<BoundExpression, (Nullabili
...
+                return;
+
+            var containingSlotType = variableBySlot[containingSlot].Symbol.GetTypeOrReturnType().Type;
+            Debug.Assert(IsMember(variable, containingSlotType));
+        }
+
+        static bool IsMember(Symbol member, TypeSymbol possibleContainer)
+        {
+            TypeSymbol memberContainer = member.ContainingType;
+            if (memberContainer.Equals(possibleContainer, TypeCompareKind.AllIgnoreOptions))
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >memberContainer.Equals(possibleContainer, TypeCompareKind.AllIgnoreOptions) [](start = 16, length = 75)

Consider extracting a local function since the same check is made several times.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 2]
```diff
@@ -681,6 +681,73 @@ private static BoundNode Rewrite(ImmutableDictionary<BoundExpression, (Nullabili
...
+            var variable = variableBySlot[i].Symbol;
+            var containingSlot = variableBySlot[i].ContainingSlot;
+            if (containingSlot < 1)
+                return;
+
+            var containingSlotType = variableBySlot[containingSlot].Symbol.GetTypeOrReturnType().Type;
+            Debug.Assert(IsMember(variable, containingSlotType));
+        }
+
+        static bool IsMember(Symbol member, TypeSymbol possibleContainer)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >static [](start = 8, length = 6)

`private`

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 3]
```diff
@@ -1254,7 +1321,11 @@ private void InheritNullableStateOfMember(int targetContainerSlot, int valueCont
         {
             Debug.Assert(targetContainerSlot > 0);
             Debug.Assert(skipSlot > 0);
-            // https://github.com/dotnet/roslyn/issues/33428: Ensure member is valid for target and value.
+
+            // Ensure member is valid for target and value.
+            if (!IsMember(member, variableBySlot[targetContainerSlot].Symbol.GetTypeOrReturnType().Type))
+                return;
+            // PROTOTYPE(ngafter): The above line is a good place to set a breakpoint to diagnose this set of changes.
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >PROTOTYPE [](start = 15, length = 9)

Please remove or address PROTOTYPE comments.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 4]
```diff
@@ -681,6 +681,73 @@ private static BoundNode Rewrite(ImmutableDictionary<BoundExpression, (Nullabili
...
+            int i = nextVariableSlot - 1;
+            if (i <= 1)
+                return;
+
+            var variable = variableBySlot[i].Symbol;
+            var containingSlot = variableBySlot[i].ContainingSlot;
+            if (containingSlot < 1)
+                return;
+
+            var containingSlotType = variableBySlot[containingSlot].Symbol.GetTypeOrReturnType().Type;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >variableBySlot[containingSlot].Symbol.GetTypeOrReturnType() [](start = 37, length = 59)

We have this pattern repeated several times in the class. Consider extracting a `GetVariableType()` method.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 5]
```diff
@@ -1607,7 +1680,7 @@ private void DeclareLocal(LocalSymbol local)
                 if (slot > 0)
                 {
                     PopulateOneSlot(ref this.State, slot);
-                    InheritDefaultState(slot);
+                    InheritDefaultState(_variableTypes.TryGetValue(local, out var typeWithAnootations) ? typeWithAnootations.Type : local.Type, slot);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >Anootations [](start = 90, length = 11)

Typo

Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >_variableTypes.TryGetValue(local, out var typeWithAnootations) ? typeWithAnootations.Type : local.Type [](start = 40, length = 102)

`GetDeclaredLocalResult(local).Type`

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 6]
```diff
@@ -1953,7 +2026,12 @@ private void VisitObjectElementInitializer(int containingSlot, BoundAssignmentOp
 
                         if ((object)symbol != null)
                         {
-                            int slot = (containingSlot < 0) ? -1 : GetOrCreateSlot(symbol, containingSlot);
+                            if (containingSlot > 0 && !IsMember(symbol, base.variableBySlot[containingSlot].Symbol.GetTypeOrReturnType().Type))
+                            {
+                                // PROTOTYPE(ngafter): This block is here to help0 debug things.
+                            }
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Please add `#if DEBUG` if this block is needed.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 7]
```diff
@@ -4868,10 +4959,12 @@ void trackConvertedValue(FieldSymbol targetField, Conversion conversion, FieldSy
                         if (AreNullableAndUnderlyingTypes(targetField.Type, valueField.Type, out _))
                         {
                             int targetFieldSlot = GetOrCreateSlot(targetField, slot);
+                            ValidateLastSlot();
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >ValidateLastSlot [](start = 28, length = 16)

Consider adding a `new int GetOrCreateSlot()` method in `NullableWalker` that simply delegates to `base.GetOrCreateSlot()` and calls `ValidateLastSlot()`.

**Comment by gafter** [comment]
@cston You last reviewed iteration 2.  I've made a number of changes since then.  Can you please have another look?

@dotnet/roslyn-compiler May I please have a second review of this nullable change?  It adds assertions to check invariants around the way slots are used.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.VariableIdentifier.cs [hunk 8]
```diff
@@ -80,7 +80,7 @@ public bool Equals(VariableIdentifier other)
                     return true;
                 }
 
-                return Symbol.OriginalDefinition.Equals(other.Symbol.OriginalDefinition, SymbolEqualityComparer.ConsiderEverything.CompareKind);
+                return Symbol.Equals(other.Symbol, SymbolEqualityComparer.IgnoreEverything.CompareKind);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.VariableIdentifier.cs]: >SymbolEqualityComparer.IgnoreEverything.CompareKind [](start = 51, length = 51)

It looks like this is the only use of `SymbolEqualityComparer.IgnoreEverything`. That member can be removed and replaced here with `TypeCompareKind.AllIgnoreOptions`.

**Comment by cston** [comment]
> #nullable disable

`restore`

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:170 in 5217bea. [](commit_id = 5217bea7a3cd834dcec959ec543440a1e7b69d93, deletion_comment = False)

File: src/Compilers/Core/Portable/Symbols/SymbolEqualityComparer.cs [hunk 9]
```diff
@@ -26,6 +26,9 @@ public sealed class SymbolEqualityComparer : IEqualityComparer<ISymbol?>
         // Internal only comparisons:
         internal readonly static SymbolEqualityComparer ConsiderEverything = new SymbolEqualityComparer(TypeCompareKind.ConsiderEverything);
 
+        // Internal only comparisons:
+        internal readonly static SymbolEqualityComparer IgnoreEverything = new SymbolEqualityComparer(TypeCompareKind.AllIgnoreOptions);
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Symbols/SymbolEqualityComparer.cs]: >SymbolEqualityComparer [](start = 33, length = 22)

This comparer is not meant for usage by compilers. I think the change to this file should be reverted.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 10]
```diff
@@ -1253,12 +1278,26 @@ private void InheritNullableStateOfTrackableStruct(TypeSymbol targetType, int ta
             }
         }
 
+        private bool IsSlotMember(int slot, Symbol possibleMember)
+        {
+            TypeSymbol possibleBase = possibleMember.ContainingType;
+            TypeSymbol possibleDerived = NominalSlotType(slot);
+            HashSet<DiagnosticInfo> discardedUseSiteDiagnostics = null;
+            var conversionsWithoutNullability = this.compilation.Conversions;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >this.compilation.Conversions [](start = 48, length = 28)

For reference, this is also available (for essentially zero cost) from `_conversions.WithNullability(false)`.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 11]
```diff
@@ -859,78 +859,94 @@ protected override bool TryGetReceiverAndMember(BoundExpression expr, out BoundE
...
-                        var method = getTopLevelMethod(_symbol as MethodSymbol);
-                        var thisParameter = method?.ThisParameter;
-                        return (object)thisParameter != null ? GetOrCreateSlot(thisParameter) : -1;
-                    }
-                case BoundKind.Conversion:
-                    {
-                        int slot = getPlaceholderSlot(node);
-                        if (slot > 0)
+                // Check that the slot represents a value of an equivalent type to the node
+                TypeSymbol slotType = variableBySlot[result].Symbol.GetTypeOrReturnType().Type;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >variableBySlot[result].Symbol.GetTypeOrReturnType().Type [](start = 38, length = 56)

`NominalSlotType(result)`

**Comment by cston** [comment]
>             if (!(CurrentSymbol is MethodSymbol methodSymbol))

Is this change needed?

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:1429 in 5217bea. [](commit_id = 5217bea7a3cd834dcec959ec543440a1e7b69d93, deletion_comment = False)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 12]
```diff
@@ -6916,11 +6964,12 @@ private Symbol VisitMemberAccess(BoundExpression node, BoundExpression receiverO
         private int GetNullableOfTValueSlot(TypeSymbol containingType, int containingSlot, out Symbol valueProperty, bool forceSlotEvenIfEmpty = false)
         {
             Debug.Assert(containingType.IsNullableType());
-            Debug.Assert(TypeSymbol.Equals(variableBySlot[containingSlot].Symbol.GetTypeOrReturnType().Type, containingType, TypeCompareKind.ConsiderEverything2));
+            Debug.Assert(TypeSymbol.Equals(NominalSlotType(containingSlot), containingType, TypeCompareKind.ConsiderEverything2));
 
             var getValue = (MethodSymbol)compilation.GetSpecialTypeMember(SpecialMember.System_Nullable_T_get_Value);
             valueProperty = getValue?.AsMember((NamedTypeSymbol)containingType)?.AssociatedSymbol;
-            return (valueProperty is null) ? -1 : GetOrCreateSlot(valueProperty, containingSlot, forceSlotEvenIfEmpty: forceSlotEvenIfEmpty);
+            var result = (valueProperty is null) ? -1 : GetOrCreateSlot(valueProperty, containingSlot, forceSlotEvenIfEmpty: forceSlotEvenIfEmpty);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >var result = [](start = 12, length = 12)

Consider reverting.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs [hunk 13]
```diff
@@ -462,14 +461,28 @@ void addToTempMap(BoundDagTemp output, int slot, TypeSymbol type)
                 {
                     // The dag temp has already been allocated on another branch of the dag
                     Debug.Assert(outputSlotAndType.slot == slot);
-                    Debug.Assert(outputSlotAndType.type.Equals(type, TypeCompareKind.AllIgnoreOptions));
+                    Debug.Assert(isDerivedType(outputSlotAndType.type, type));
                 }
                 else
                 {
+                    var slotType = NominalSlotType(slot);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs]: >var slotType [](start = 20, length = 12)

Please wrap in `#if DEBUG`.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 14]
```diff
@@ -120598,5 +120619,115 @@ public static void Main()
...
+class Program
+{
+    static void Test(string? s)
+    {
+        if (s == null) return;
+
+        heck:
+        var c = GetC(s);
+        var prop = c.Property;
+        prop.ToString(); // BOOM (after goto)
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >BOOM (after goto) [](start = 28, length = 17)

Consider removing comment since presumably it does not apply.

Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: It describes the fact that a null reference exception will occur at runtime.  I'll reword the comment.

---
In reply to: [366648998](https://github.com/dotnet/roslyn/pull/39301#discussion_r366648998) [](ancestors = 366648998)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 10 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Sure, I'll switch to that and fix the concurrency bug in the implementation of `WithNullability` so that it doesn't fail an assertion.

---
In reply to: [366642586](https://github.com/dotnet/roslyn/pull/39301#discussion_r366642586) [](ancestors = 366642586)

**Comment by gafter** [comment]
>             if (!(CurrentSymbol is MethodSymbol methodSymbol))

No sure which change you're referring to, but yes, at least the one inside `VisitYieldReturn` is needed.  I'll revert the rest.

---
In reply to: [574439406](https://github.com/dotnet/roslyn/pull/39301#issuecomment-574439406) [](ancestors = 574439406)

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:1429 in 15a06b8. [](commit_id = 15a06b875b7ebe576d8a60012cd946df86adbf99, deletion_comment = False)

**Comment by gafter** [comment]
@AlekseyTs I think I've addressed your comments.  Do you have any others?

**Comment by AlekseyTs** [comment]
> I think I've addressed your comments. Do you have any others?

I do not have any other comments at the moment, but that was the only file I looked at.

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a second review of this nullability bug fix that strengthens its internal assertions?

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a second review of this nullability bug fix that strengthens its internal assertions?
