### PR TITLE
Use a recent Unicode version for case mapping by relying on a neutral culture

### LINKED ISSUE #2116: Change VB's case-mapping rules to use a more recent Unicode version
VB's current case-mapping rules for identifier equivalence uses a pretty old version of the Unicode spec, and has bugs. Specifically we use the "invariant" locale, which because it is invariant will never change to be updated as the Unicode spec evolves.

We should instead use a "neutral" culture for the case-mapping, such as the "en" locale, which follows the Unicode case-mapping rules and has no locale-specific exceptions.

### PR DESCRIPTION
**Pull request by gafter**
instead of the not-so-neutral invarant culture.
Fixes #2116, #620
See also #1070

@ellismg @jaredpar @AlekseyTs : Please review
/cc @VladimirReshetnikov

### CODE REVIEW

File: src/Compilers/Core/Portable/CaseInsensitiveComparison.cs [hunk 1]
```diff
@@ -14,69 +14,105 @@ namespace Microsoft.CodeAnalysis
...
+                // Apparently we are running on a platform without the "en" culture.
+                // Let us try a couple of fall-backs...
+            }
 
-                if (c < 0xC0) // Covers ASCII (U+0000 - U+007F) and up to the next upper-case codepoint (Latin Capital Letter A with Grave)
-                {
-                    return c;
-                }
+            culture = CultureInfo.CurrentCulture;
+            if (culture.IsNeutralCulture)
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/CaseInsensitiveComparison.cs]: Even though IsNeutralCulture is true, the culture might be associated with a non-English language. Is this going to be a problem? And why not?

**Comment by AlekseyTs** [comment]
Other than the question about neutral culture, LGTM.

File: src/Compilers/Core/Portable/CaseInsensitiveComparison.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/Core/Portable/CaseInsensitiveComparison.cs]: If the culture is neutral, then it has no culture-specific rules for character mapping. In that case is doesn't matter if the underlying locale it is French, Japanese, or Russian, as they will all have the same character mapping for the purposes used herein.

Comment (ellismg) [inline src/Compilers/Core/Portable/CaseInsensitiveComparison.cs]: > If the culture is neutral, then it has no culture-specific rules for character mapping.

I don't believe that's true.  Consider the following sample:

```csharp
CultureInfo c = new CultureInfo("tr");
Console.WriteLine(c.IsNeutralCulture);
Console.WriteLine(c.TextInfo.ToLower('I') == 'i');
```

The output of this program is "true, false".  If I change the culture to "en" then it is true, true.

Now, for this specific case, I think you are still fine because you handle ASCII letters in a special way.  I am not sure if there are cases where there are non ASCII characters which have culture specific casing rules.  You might ask the NLS folks internally.

**Comment by ellismg** [comment]
Given that you are relying on the OS behavior (per #1070), I guess this change is fine.  For what it's worth, I find it very hard to reason about.  If it was me, I would do something like say we use Default Caseless Matching (from Section 3.13) of the Unicode spec with data locked at some specific Unicode revision (and mention that we do simple case mapping, not full, when case-folding).

The downside of this approach is you'd have to carry along some fixed data-tables (e.g encode the data in CaseFolding.txt somehow), since I don't believe the framework provides a way to get at this information.  The upside is your algorithm would not be platform dependent and IMHO, much easier to reason about.

I think in the common case there wouldn't be a performance difference, since the special case you have for ASCII makes it easy enough to not have to actually go do a lookup in the data tables to actually find casing data.

**Comment by gafter** [comment]
The intent of the VB language spec is to *not* lock to a particular Unicode version, but rather have the behavior be updated when the platform updates to a later version.

File: src/Compilers/Core/Portable/CaseInsensitiveComparison.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/Core/Portable/CaseInsensitiveComparison.cs]: What is the meaning of `IsNeutralCulture`?

**Comment by gafter** [comment]
It would be valuable to have a note in the compiler spec about what we do here (since it is a Unicode version upgrade).
