### PR TITLE
For tuple types, NamedTypeSymbol.GetFieldsToEmit API should return symbols for tuple underlying fields.

### LINKED ISSUE #43524: Roslyn throws exception when compiling project
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/983261/roslyn-throws-exception-when-compiling-project.html)._

---
When I build a project with Visual Studio 2019, Roslyn throws an exception. The exception changes each time I try to build the project. Here's one of them:

```
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error : 
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error : Excepci├│n no controlada: System.EntryPointNotFoundException: No se encontr├│ el punto de entrada.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error :    en Microsoft.Cci.IParameterTypeInformation.GetType(EmitContext context)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error :    en Microsoft.Cci.MetadataWriter.SerializeParameterInformation(ParameterTypeEncoder encoder, IParameterTypeInformation parameterTypeInformation)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error :    en Microsoft.Cci.MetadataWriter.SerializeReturnValueAndParameters(MethodSignatureEncoder encoder, ISignature signature, ImmutableArray`1 varargParameters)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error :    en Microsoft.Cci.MetadataWriter.GetMethodSignatureHandleAndBlob(IMethodReference methodReference, ImmutableArray`1& signatureBlob)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error :    en Microsoft.Cci.MetadataWriter.PopulateMethodTableRows(Int32[] methodBodyOffsets)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error :    en Microsoft.Cci.MetadataWriter.PopulateTypeSystemTables(Int32[] methodBodyOffsets, BlobBuilder mappedFieldDataWriter, BlobBuilder resourceWriter, BlobBuilder dynamicAnalysisDataOpt, Blob& mvidFixup)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error :    en Microsoft.Cci.MetadataWriter.BuildMetadataAndIL(PdbWriter nativePdbWriterOpt, BlobBuilder ilBuilder, BlobBuilder mappedFieldDataBuilder, BlobBuilder managedResourceDataBuilder, Blob& mvidFixup, Blob& mvidStringFixup)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error :    en Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error :    en Microsoft.CodeAnalysis.Compilation.SerializePeToStream(CommonPEModuleBuilder moduleBeingBuilt, DiagnosticBag metadataDiagnostics, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getMetadataPeStreamOpt, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean includePrivateMembers, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error :    en Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider metadataPEStreamProvider, EmitStreamProvider pdbStreamProvider, Func`2 testSymWriterFactory, DiagnosticBag diagnostics, Boolean metadataOnly, Boolean includePrivateMembers, Boolean emitTestCoverageData, String pePdbFilePath, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error :    en Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 additionalTextFiles, AnalyzerConfigSet analyzerConfigSet, ImmutableArray`1 sourceFileAnalyzerConfigOptions, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, Boolean& reportAnalyzer, AnalyzerDriver& analyzerDriver)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error :    en Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error :    en Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error :    en Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error :    en Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[T](Func`2 func)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error :    en Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error :    en Microsoft.CodeAnalysis.CommandLine.BuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error :    en Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter, String pipeName)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error :    en Microsoft.CodeAnalysis.CommandLine.BuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5): error :    en Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
========== Compilar: 0 correctos, 1 incorrectos, 2 actualizados, 0 omitidos ==========
```

---
#### Visual Studio Feedback System on 4/8/2020, 09:04 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Jared Parsons [MSFT] on 4/14/2020, 08:00 PM: 

<p>Thanks for taking the time to file this feedback issue. Unfortunately there is not enough information here for us to reproduce the problem. Can you provide a code sample that demonstrates the problem?</p>

#### Dzianis Kosy on 4/19/2020, 11:07 AM: 

(private comment, text removed)
#### Visual Studio Feedback System on 4/20/2020, 01:41 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
#### Dzianis Kosy solved on 4/19/2020, 11:10 AM, 0 votes: 

<p>Try to compile CodeJam.sln: <a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/129695-codejam.zip">codejam.zip</a></p>

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #43524.
Related to #43549.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@jcouv, @dotnet/roslyn-compiler Please review

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs [hunk 1]
```diff
@@ -889,6 +889,9 @@ internal override IEnumerable<FieldSymbol> GetFieldsToEmit()
                     if ((object)associatedField != null)
                     {
                         Debug.Assert((object)associatedField.AssociatedSymbol != null);
+
+                        associatedField = associatedField.TupleUnderlyingField ?? associatedField;
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs:893]: This pattern pops up a bit. Is it worth adding a new member like `TulpeUnderlyingFieldOrSelf` to encourage this as a best practice going forward?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs:893]: > This pattern pops up a bit. Is it worth adding a new member like TulpeUnderlyingFieldOrSelf to encourage this as a best practice going forward?

Are you suggesting to add one? I didn't get an urge to add one.

Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs:893]: Reading the PR I was wondering to myself:

> How will future developers know this is an important problem? If we had `TupleUnderlyingFieldOrSelf` maybe it would be a clue that this is important. 

I don't feel strongly about this. It's just a thought I had reading through this PR.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs:893]: > How will future developers know this is an important problem?

I guess I am not sure what is the problem to be aware of. There is an API TupleUnderlyingField, it is docummented to return null in some scenarios. What is there to miss or be confused about?

Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.cs:893]: Mostly that in the case the return is `null` then using `this` is the generally the correct fallback. That can also be inferred by looking through these cases. 

As I said though, this isn't a big concern. Mostly just thinking out loud as I'm reading the PR.

**Comment by AlekseyTs** [comment]
@jcouv Please review

**Comment by AlekseyTs** [comment]
@jcouv Please review, need a second sign-off
