### PR TITLE
Diagnose parsing precedence inversions with left operand that do not end in an expression

### LINKED ISSUE #10492: Precedence errors in parsing the relational "is" expression
The following short program illustrates two errors in the Roslyn expression parser. These issues interfere with the extension of the parser to support pattern-matching.

``` cs
using System;

class Program
{
    const bool B = true;

    public static void Main(string[] args)
    {
        object a = null;
        B c = null;
        Console.WriteLine(a is B & c); // prints 5 (correct)
        Console.WriteLine(a is B > c); // prints 6 (correct)
        Console.WriteLine(a is B < c); // syntax error but should print 7
        Console.WriteLine(a is B + c); // should be syntax error but prints 8
    }
}

class B
{
    public static int operator &(bool left, B right) => 5;
    public static int operator >(bool left, B right) => 6;
    public static int operator <(bool left, B right) => 7;
    public static int operator +(bool left, B right) => 8;
}
```

The last of these cases is most problematic for pattern-matching. While `a is B + c` should have been a syntax error in C# 6, in C# 7 it should mean `a is (B + c)`, which works if `B + c` is a constant value. However, we parse it incorrectly as `(a is B) + b`, which is an inversion of the precedence required by the language specification.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #10492

### CODE REVIEW

File: docs/compilers/CSharp/Compiler Breaking Changes - post VS2019.md [hunk 1]
```diff
@@ -78,3 +78,11 @@ could be different than the one that compiler used to find.
...
 
 11. Previously, the language version was not checked for `this ref` and `this in` orderings of parameter modifiers. In *Visual Studio 2019 version 16.4* these orderings produce an error with langversion below 7.2. See https://github.com/dotnet/roslyn/issues/38486
+
+12. https://github.com/dotnet/roslyn/issues/10492 Under some circumstances, the compiler would accept an expression that does not obey the rules of the language grammar.  Examples include
+    - `()=>{} + c`
+    - `e is {} + c`
+    - `e is T t + c`
+    - `delegate {} + c`
+
+    These all have in common that the left operand is of looser precedence than the `+` operator, but the left operand does not end in an expression so it cannot "consume" the addition.  Such expressions will no longer be permitted in Visual Studio 2019 version 16.5 (Update 5) and later.
```
Comment (cston) [inline docs/compilers/CSharp/Compiler Breaking Changes - post VS2019.md]: >(Update 5) [](start = 267, length = 10)

We should reference full versions rather than particular updates (and it looks like the update # is incorrect anyway).

File: docs/compilers/CSharp/Compiler Breaking Changes - post VS2019.md [hunk 2]
```diff
@@ -78,3 +78,11 @@ could be different than the one that compiler used to find.
     ```
 
 11. Previously, the language version was not checked for `this ref` and `this in` orderings of parameter modifiers. In *Visual Studio 2019 version 16.4* these orderings produce an error with langversion below 7.2. See https://github.com/dotnet/roslyn/issues/38486
+
+12. https://github.com/dotnet/roslyn/issues/10492 Under some circumstances, the compiler would accept an expression that does not obey the rules of the language grammar.  Examples include
+    - `()=>{} + c`
```
Comment (cston) [inline docs/compilers/CSharp/Compiler Breaking Changes - post VS2019.md]: >()=>{} [](start = 7, length = 6)

Minor: consider adding spaces: `() => {} ...`

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 3]
```diff
@@ -8763,6 +8769,41 @@ private static Precedence GetPrecedence(SyntaxKind op)
...
+                case SyntaxKind.SimpleMemberAccessExpression:
+                case SyntaxKind.StackAllocArrayCreationExpression:
+                case SyntaxKind.StringLiteralExpression:
+                case SyntaxKind.SuppressNullableWarningExpression:
+                case SyntaxKind.ThisExpression:
+                case SyntaxKind.TrueLiteralExpression:
+                case SyntaxKind.TupleExpression:
+                    return Precedence.Primary;
                 default:
                     throw ExceptionUtilities.UnexpectedValue(op);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: >throw ExceptionUtilities.UnexpectedValue(op); [](start = 20, length = 45)

Are we calling `GetPrecedence()` for more (all?) expression types now? If so, are we likely to hit this for new expression types?

File: docs/compilers/CSharp/Compiler Breaking Changes - post VS2019.md (hunk 1 above)
Comment (gafter) [reply docs/compilers/CSharp/Compiler Breaking Changes - post VS2019.md]: What full version do you suggest here?

---
In reply to: [352902202](https://github.com/dotnet/roslyn/pull/40089#discussion_r352902202) [](ancestors = 352902202)

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs (hunk 3 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: Yes, we do.  On line 9048.

---
In reply to: [352907086](https://github.com/dotnet/roslyn/pull/40089#discussion_r352907086) [](ancestors = 352907086)

File: docs/compilers/CSharp/Compiler Breaking Changes - post VS2019.md (hunk 1 above)
Comment (cston) [reply docs/compilers/CSharp/Compiler Breaking Changes - post VS2019.md]: My suggestion is "Visual Studio 2019 version 16.5" without the "update ..." qualifier.

---
In reply to: [353406094](https://github.com/dotnet/roslyn/pull/40089#discussion_r353406094) [](ancestors = 353406094,352902202)

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs (hunk 3 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: In that case, how do we test all future expression types to ensure the associated `SyntaxKind` is added above?

---
In reply to: [353406709](https://github.com/dotnet/roslyn/pull/40089#discussion_r353406709) [](ancestors = 353406709,352907086)

Comment (gafter) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: By placing it on the left-hand-side of a binary operator in a test source.

---
In reply to: [353416906](https://github.com/dotnet/roslyn/pull/40089#discussion_r353416906) [](ancestors = 353416906,353406709,352907086)

**Comment by gafter** [comment]
This change is being reviewed by the "Compatibility Council".

**Comment by gafter** [comment]
In response to a compat council suggestion, I'm narrowing the fix to strict mode, or when the left operand is an is-pattern expression.

---
In reply to: [561391816](https://github.com/dotnet/roslyn/pull/40089#issuecomment-561391816) [](ancestors = 561391816)

**Comment by gafter** [comment]
@RikkiGibson Could you review this please?

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 4]
```diff
@@ -8682,13 +8682,18 @@ enum Precedence : uint
...
 
         private static Precedence GetPrecedence(SyntaxKind op)
         {
             switch (op)
             {
+                case SyntaxKind.QueryExpression:
+                case SyntaxKind.ParenthesizedLambdaExpression:
+                case SyntaxKind.SimpleLambdaExpression:
+                case SyntaxKind.AnonymousMethodExpression:
+                    return Precedence.Expression;
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: I feel like I'm missing something, are these not meant to be Lambda precedence?

**Comment by RikkiGibson** [comment]
LGTM except for one question

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs (hunk 4 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: Yes.  However, since `Expression` is not used anywhere else, it won't have an observable or testable effect on the behavior.

---
In reply to: [357866628](https://github.com/dotnet/roslyn/pull/40089#discussion_r357866628) [](ancestors = 357866628)

Comment (gafter) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: Moreover, they are technically at the same precedence.  See [https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#expression](https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#expression)

---
In reply to: [357875828](https://github.com/dotnet/roslyn/pull/40089#discussion_r357875828) [](ancestors = 357875828,357866628)

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: Makes sense, thank you!

Comment (gafter) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: I'm going to merge the three precedence levels in the next iteration unless that runs into problems!

---
In reply to: [357879626](https://github.com/dotnet/roslyn/pull/40089#discussion_r357879626) [](ancestors = 357879626)
