### PR TITLE
Visit query lambda by `NullableWalker` even without conversion

### LINKED ISSUE #65053: Assertion in nullable walker: "Did not find BoundCall in the map."
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Did not find Microsoft.CodeAnalysis.CSharp.BoundCall `itemBGroup.DefaultIfEmpty()` in the map.



   at Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VerifyExpression(BoundExpression expression, Boolean overrideSkippedExpression) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.DebugVerifier.cs:line 61

   at Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitExpressionWithoutStackGuard(BoundExpression node) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.DebugVerifier.cs:line 68

   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node) in C:\github\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs:line 212

   at Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(BoundNode node) in C:\github\roslyn\src\Compilers\CSharp\Portable\FlowAnalysis\NullableWalker.DebugVerifier.cs:line 83

   at Microsoft.CodeAnalysis.CSharp.Boun......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

The code i have is:

```c#
using System.Diagnostics;

class C
{
    void M()
    {
        _ = from itemA in new[] { new { X = (int?)1 } }.AsQueryable()
            join itemB in new[] { new { X = (int?)2 } }.AsQueryable() on itemA.X equals itemB.X into itemBGroup
            from itemB in itemBGroup.DefaultIfEmpty()
                //     ↓ IDE0031 Use null propagation
            select itemB == null ? null : itemB.X;
    }
}
```

Full stack trace:
<details>

```
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VerifyExpression(Microsoft.CodeAnalysis.CSharp.BoundExpression expression, bool overrideSkippedExpression) Line 61	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression node) Line 68	C#
 	[External Code]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 83	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitReturnStatement(Microsoft.CodeAnalysis.CSharp.BoundReturnStatement node) Line 9578	C#
 	[External Code]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 85	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList<Microsoft.CodeAnalysis.CSharp.BoundStatement>(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.BoundStatement> list) Line 22	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitBlock(Microsoft.CodeAnalysis.CSharp.BoundBlock node) Line 9538	C#
 	[External Code]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 85	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitLambda(Microsoft.CodeAnalysis.CSharp.BoundLambda node) Line 10077	C#
 	[External Code]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression node) Line 69	C#
 	[External Code]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 83	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitQueryClause(Microsoft.CodeAnalysis.CSharp.BoundQueryClause node) Line 115	C#
 	[External Code]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression node) Line 69	C#
 	[External Code]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 83	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList<Microsoft.CodeAnalysis.CSharp.BoundExpression>(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.BoundExpression> list) Line 22	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitCall(Microsoft.CodeAnalysis.CSharp.BoundCall node) Line 9923	C#
 	[External Code]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression node) Line 69	C#
 	[External Code]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 83	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitQueryClause(Microsoft.CodeAnalysis.CSharp.BoundQueryClause node) Line 115	C#
 	[External Code]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression node) Line 69	C#
 	[External Code]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 83	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitQueryClause(Microsoft.CodeAnalysis.CSharp.BoundQueryClause node) Line 115	C#
 	[External Code]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression node) Line 69	C#
 	[External Code]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 83	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitQueryClause(Microsoft.CodeAnalysis.CSharp.BoundQueryClause node) Line 115	C#
 	[External Code]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression node) Line 69	C#
 	[External Code]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 83	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitAssignmentOperator(Microsoft.CodeAnalysis.CSharp.BoundAssignmentOperator node) Line 9412	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitAssignmentOperator(Microsoft.CodeAnalysis.CSharp.BoundAssignmentOperator node) Line 178	C#
 	[External Code]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression node) Line 69	C#
 	[External Code]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 83	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitExpressionStatement(Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement node) Line 9594	C#
 	[External Code]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 85	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.DebugVerifier.Verify(System.Collections.Immutable.ImmutableDictionary<Microsoft.CodeAnalysis.CSharp.BoundExpression, (Microsoft.CodeAnalysis.NullabilityInfo Info, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol Type)> analyzedNullabilityMap, Microsoft.CodeAnalysis.CSharp.NullableWalker.SnapshotManager snapshotManagerOpt, Microsoft.CodeAnalysis.CSharp.BoundNode node) Line 39	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.NullableWalker.AnalyzeAndRewriteSpeculation(int position, Microsoft.CodeAnalysis.CSharp.BoundNode node, Microsoft.CodeAnalysis.CSharp.Binder binder, Microsoft.CodeAnalysis.CSharp.NullableWalker.SnapshotManager originalSnapshots, out Microsoft.CodeAnalysis.CSharp.NullableWalker.SnapshotManager newSnapshots, ref System.Collections.Immutable.ImmutableDictionary<Microsoft.CodeAnalysis.CSharp.Symbol, Microsoft.CodeAnalysis.CSharp.Symbol> remappedSymbols) Line 1516	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.EnsureNullabilityAnalysisPerformedIfNecessary() Line 1955	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node) Line 2052	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node) Line 544	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node, out Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode bindableNode, out Microsoft.CodeAnalysis.CSharp.BoundNode lowestBoundNode, out Microsoft.CodeAnalysis.CSharp.BoundNode highestBoundNode, out Microsoft.CodeAnalysis.CSharp.BoundNode boundParent) Line 1328	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node, Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.SymbolInfoOptions options, System.Threading.CancellationToken cancellationToken) Line 1206	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.SpeculativeSemanticModelWithMemberModel.GetSymbolInfoWorker(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node, Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.SymbolInfoOptions options, System.Threading.CancellationToken cancellationToken) Line 448	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax expression, System.Threading.CancellationToken cancellationToken) Line 573	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoFromNode(Microsoft.CodeAnalysis.SyntaxNode node, System.Threading.CancellationToken cancellationToken) Line 4939	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfoCore(Microsoft.CodeAnalysis.SyntaxNode node, System.Threading.CancellationToken cancellationToken) Line 5038	C#
>	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.SemanticModel.GetSymbolInfo(Microsoft.CodeAnalysis.SyntaxNode node, System.Threading.CancellationToken cancellationToken) Line 99	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.ModelExtensions.GetSymbolInfo(Microsoft.CodeAnalysis.SemanticModel semanticModel, Microsoft.CodeAnalysis.SyntaxNode node, System.Threading.CancellationToken cancellationToken) Line 21	C#
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.Simplification.Simplifiers.CastSimplifier.IntroducedAmbiguity(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax castNode, Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax rewrittenExpression, Microsoft.CodeAnalysis.SemanticModel originalSemanticModel, Microsoft.CodeAnalysis.SemanticModel rewrittenSemanticModel, System.Threading.CancellationToken cancellationToken) Line 926	C#
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.Simplification.Simplifiers.CastSimplifier.GetSemanticModelWithCastRemoved(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax castNode, Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax castedExpressionNode, Microsoft.CodeAnalysis.SemanticModel originalSemanticModel, System.Threading.CancellationToken cancellationToken) Line 1289	C#
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.Simplification.Simplifiers.CastSimplifier.IsConversionCastSafeToRemove(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax castNode, Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax castedExpressionNode, Microsoft.CodeAnalysis.SemanticModel originalSemanticModel, Microsoft.CodeAnalysis.Operations.IConversionOperation originalConversionOperation, System.Threading.CancellationToken cancellationToken) Line 320	C#
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.Simplification.Simplifiers.CastSimplifier.IsCastSafeToRemove(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax castNode, Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax castedExpressionNode, Microsoft.CodeAnalysis.SemanticModel originalSemanticModel, System.Threading.CancellationToken cancellationToken) Line 198	C#
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.Simplification.Simplifiers.CastSimplifier.IsUnnecessaryCast(Microsoft.CodeAnalysis.CSharp.Syntax.CastExpressionSyntax cast, Microsoft.CodeAnalysis.SemanticModel semanticModel, System.Threading.CancellationToken cancellationToken) Line 108	C#
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.Simplification.Simplifiers.CastSimplifier.IsUnnecessaryCast(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax cast, Microsoft.CodeAnalysis.SemanticModel semanticModel, System.Threading.CancellationToken cancellationToken) Line 47	C#
 	Microsoft.CodeAnalysis.CSharp.Features.dll!Microsoft.CodeAnalysis.CSharp.RemoveUnnecessaryCast.CSharpRemoveUnnecessaryCastDiagnosticAnalyzer.IsUnnecessaryCast(Microsoft.CodeAnalysis.SemanticModel model, Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax cast, System.Threading.CancellationToken cancellationToken) Line 27	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.RemoveUnnecessaryCast.AbstractRemoveUnnecessaryCastDiagnosticAnalyzer<Microsoft.CodeAnalysis.CSharp.SyntaxKind, Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax>.TryRemoveCastExpression(Microsoft.CodeAnalysis.SemanticModel model, Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax node, System.Threading.CancellationToken cancellationToken) Line 57	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.RemoveUnnecessaryCast.AbstractRemoveUnnecessaryCastDiagnosticAnalyzer<Microsoft.CodeAnalysis.CSharp.SyntaxKind, Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax>.AnalyzeSyntax(Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext context) Line 42	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteSyntaxNodeAction.AnonymousMethod__62_0((System.Action<Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext> action, Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext context) data) Line 937	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock<(System.Action<Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext>, Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext)>(Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer analyzer, System.Action<(System.Action<Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext>, Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext)> analyze, (System.Action<Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext>, Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext) argument, Microsoft.CodeAnalysis.Diagnostics.AnalysisContextInfo? info) Line 1620	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows<(System.Action<Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext>, Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext)>(Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer analyzer, System.Action<(System.Action<Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext>, Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext)> analyze, (System.Action<Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext>, Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext) argument, Microsoft.CodeAnalysis.Diagnostics.AnalysisContextInfo? info) Line 1601	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteSyntaxNodeAction<Microsoft.CodeAnalysis.CSharp.SyntaxKind>(Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalyzerAction<Microsoft.CodeAnalysis.CSharp.SyntaxKind> syntaxNodeAction, Microsoft.CodeAnalysis.SyntaxNode node, Microsoft.CodeAnalysis.ISymbol containingSymbol, Microsoft.CodeAnalysis.SemanticModel semanticModel, System.Action<Microsoft.CodeAnalysis.Diagnostic> addDiagnostic, System.Func<Microsoft.CodeAnalysis.Diagnostic, bool> isSupportedDiagnostic, bool isGeneratedCode, Microsoft.CodeAnalysis.Diagnostics.AnalysisState.SyntaxNodeAnalyzerStateData analyzerState) Line 935	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteSyntaxNodeActions<Microsoft.CodeAnalysis.CSharp.SyntaxKind>(Microsoft.CodeAnalysis.SyntaxNode node, Microsoft.CodeAnalysis.Collections.ImmutableSegmentedDictionary<Microsoft.CodeAnalysis.CSharp.SyntaxKind, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalyzerAction<Microsoft.CodeAnalysis.CSharp.SyntaxKind>>> nodeActionsByKind, Microsoft.CodeAnalysis.ISymbol containingSymbol, Microsoft.CodeAnalysis.SemanticModel model, System.Func<Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.CSharp.SyntaxKind> getKind, System.Action<Microsoft.CodeAnalysis.Diagnostic> addDiagnostic, System.Func<Microsoft.CodeAnalysis.Diagnostic, bool> isSupportedDiagnostic, bool isGeneratedCode, Microsoft.CodeAnalysis.Diagnostics.AnalysisState.SyntaxNodeAnalyzerStateData analyzerState) Line 1418	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteSyntaxNodeActions<Microsoft.CodeAnalysis.CSharp.SyntaxKind>(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.SyntaxNode> nodesToAnalyze, Microsoft.CodeAnalysis.Collections.ImmutableSegmentedDictionary<Microsoft.CodeAnalysis.CSharp.SyntaxKind, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalyzerAction<Microsoft.CodeAnalysis.CSharp.SyntaxKind>>> nodeActionsByKind, Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer analyzer, Microsoft.CodeAnalysis.ISymbol containingSymbol, Microsoft.CodeAnalysis.SemanticModel model, System.Func<Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.CSharp.SyntaxKind> getKind, System.Action<Microsoft.CodeAnalysis.Diagnostic> addDiagnostic, System.Func<Microsoft.CodeAnalysis.Diagnostic, bool> isSupportedDiagnostic, bool isGeneratedCode, Microsoft.CodeAnalysis.Diagnostics.AnalysisState.SyntaxNodeAnalyzerStateData analyzerState) Line 1397	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteSyntaxNodeActionsCore<Microsoft.CodeAnalysis.CSharp.SyntaxKind>(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.SyntaxNode> nodesToAnalyze, Microsoft.CodeAnalysis.Collections.ImmutableSegmentedDictionary<Microsoft.CodeAnalysis.CSharp.SyntaxKind, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalyzerAction<Microsoft.CodeAnalysis.CSharp.SyntaxKind>>> nodeActionsByKind, Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer analyzer, Microsoft.CodeAnalysis.ISymbol containingSymbol, Microsoft.CodeAnalysis.SemanticModel model, System.Func<Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.CSharp.SyntaxKind> getKind, Microsoft.CodeAnalysis.Text.TextSpan filterSpan, Microsoft.CodeAnalysis.Diagnostics.AnalysisState.SyntaxNodeAnalyzerStateData analyzerState, bool isGeneratedCode) Line 1364	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.TryExecuteSyntaxNodeActions<Microsoft.CodeAnalysis.CSharp.SyntaxKind>(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.SyntaxNode> nodesToAnalyze, Microsoft.CodeAnalysis.Collections.ImmutableSegmentedDictionary<Microsoft.CodeAnalysis.CSharp.SyntaxKind, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalyzerAction<Microsoft.CodeAnalysis.CSharp.SyntaxKind>>> nodeActionsByKind, Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer analyzer, Microsoft.CodeAnalysis.SemanticModel model, System.Func<Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.CSharp.SyntaxKind> getKind, Microsoft.CodeAnalysis.Text.TextSpan filterSpan, int declarationIndex, Microsoft.CodeAnalysis.ISymbol declaredSymbol, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisState, bool isGeneratedCode) Line 1331	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver<Microsoft.CodeAnalysis.CSharp.SyntaxKind>.TryExecuteDeclaringReferenceActions.__executeNodeActionsByKind|2(Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.SyntaxNode> nodesToAnalyze, Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver<Microsoft.CodeAnalysis.CSharp.SyntaxKind>.GroupedAnalyzerActions groupedActions) Line 2647	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver<Microsoft.CodeAnalysis.CSharp.SyntaxKind>.TryExecuteDeclaringReferenceActions.__executeNodeActions|1() Line 2632	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver<Microsoft.CodeAnalysis.CSharp.SyntaxKind>.TryExecuteDeclaringReferenceActions(Microsoft.CodeAnalysis.SyntaxReference decl, int declarationIndex, Microsoft.CodeAnalysis.Diagnostics.SymbolDeclaredCompilationEvent symbolEvent, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisState, Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver<Microsoft.CodeAnalysis.CSharp.SyntaxKind>.GroupedAnalyzerActions coreActions, Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver<Microsoft.CodeAnalysis.CSharp.SyntaxKind>.GroupedAnalyzerActions additionalPerSymbolActions, bool shouldExecuteSyntaxNodeActions, bool shouldExecuteOperationActions, bool shouldExecuteCodeBlockActions, bool shouldExecuteOperationBlockActions, bool isInGeneratedCode, System.Threading.CancellationToken cancellationToken) Line 2601	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver<Microsoft.CodeAnalysis.CSharp.SyntaxKind>.TryExecuteDeclaringReferenceActions(Microsoft.CodeAnalysis.Diagnostics.SymbolDeclaredCompilationEvent symbolEvent, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisState, bool isGeneratedCodeSymbol, Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.IGroupedAnalyzerActions additionalPerSymbolActions, System.Threading.CancellationToken cancellationToken) Line 2492	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.TryProcessSymbolDeclaredAsync(Microsoft.CodeAnalysis.Diagnostics.SymbolDeclaredCompilationEvent symbolEvent, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisState, System.Threading.CancellationToken cancellationToken) Line 1642	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.TryProcessEventCoreAsync(Microsoft.CodeAnalysis.Diagnostics.CompilationEvent compilationEvent, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisState, System.Threading.CancellationToken cancellationToken) Line 1594	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessEventAsync(Microsoft.CodeAnalysis.Diagnostics.CompilationEvent e, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisState, System.Threading.CancellationToken cancellationToken) Line 1505	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessCompilationEventsCoreAsync(Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisState, bool prePopulatedEventQueue, System.Threading.CancellationToken cancellationToken) Line 1492	C#
 	[Resuming Async Method]	
 	[External Code]	
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.GetPerSymbolAnalyzerActionsAsync.__getSymbolActionsCoreAsync|149_2(Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver driver, Microsoft.CodeAnalysis.ISymbol symbol, Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer analyzer) Line 2181	C#
 	[Resuming Async Method]	
 	[External Code]	
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.GetPerSymbolAnalyzerActionsAsync(Microsoft.CodeAnalysis.ISymbol symbol, bool isGeneratedCodeSymbol, Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer analyzer, Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor analyzerExecutor) Line 215	C#
 	[Async Call Stack]	
 	[Async] Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessCompilationEventsAsync(Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisState, bool prePopulatedEventQueue, System.Threading.CancellationToken cancellationToken) Line 1426	C#
 	[Async] Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ExecutePrimaryAnalysisTaskAsync(Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisState, bool usingPrePopulatedEventQueue, System.Threading.CancellationToken cancellationToken) Line 682	C#
 	[Async] Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.AttachQueueAndProcessAllEventsAsync(Microsoft.CodeAnalysis.Diagnostics.AsyncQueue<Microsoft.CodeAnalysis.Diagnostics.CompilationEvent> eventQueue, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState analysisState, System.Threading.CancellationToken cancellationToken) Line 616	C#
 	[Async] Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.ComputeAnalyzerDiagnosticsCoreAsync(Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver driver, Microsoft.CodeAnalysis.Diagnostics.AsyncQueue<Microsoft.CodeAnalysis.Diagnostics.CompilationEvent> eventQueue, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, System.Threading.CancellationToken cancellationToken) Line 1032	C#
 	[Async] Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.ComputeAnalyzerDiagnosticsAsync.AnonymousMethod__1() Line 828	C#
 	[External Code]	
 	[Async] Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.ComputeAnalyzerDiagnosticsAsync(Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, System.Func<System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostics.CompilationEvent>> getPendingEventsOpt, int newTaskToken, System.Threading.CancellationToken cancellationToken) Line 847	C#
 	[Async] Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.ComputeAnalyzerSemanticDiagnosticsAsync(Microsoft.CodeAnalysis.SemanticModel model, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope analysisScope, System.Threading.CancellationToken cancellationToken, bool forceCompletePartialTrees) Line 695	C#
 	[Async] Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.GetAnalysisResultCoreAsync(Microsoft.CodeAnalysis.SemanticModel model, Microsoft.CodeAnalysis.Text.TextSpan? filterSpan, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer> analyzers, System.Threading.CancellationToken cancellationToken) Line 668	C#
 	[Async] Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Diagnostics.Extensions.GetAnalysisResultAsync(Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers compilationWithAnalyzers, Microsoft.CodeAnalysis.Diagnostics.DocumentAnalysisScope documentAnalysisScope, System.Threading.CancellationToken cancellationToken) Line 348	C#
 	[Async] Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Diagnostics.Extensions.GetAnalysisResultAsync(Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers compilationWithAnalyzers, Microsoft.CodeAnalysis.Diagnostics.DocumentAnalysisScope documentAnalysisScope, Microsoft.CodeAnalysis.Project project, Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerInfoCache analyzerInfoCache, System.Threading.CancellationToken cancellationToken) Line 315	C#
 	[Async] Microsoft.CodeAnalysis.LanguageServer.Protocol.dll!Microsoft.CodeAnalysis.Diagnostics.InProcOrRemoteHostAnalyzerRunner.AnalyzeInProcAsync(Microsoft.CodeAnalysis.Diagnostics.DocumentAnalysisScope documentAnalysisScope, Microsoft.CodeAnalysis.Project project, Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers compilationWithAnalyzers, Microsoft.CodeAnalysis.Remote.RemoteHostClient client, bool logPerformanceInfo, bool getTelemetryInfo, System.Threading.CancellationToken cancellationToken) Line 98	C#
 	[Async] Microsoft.CodeAnalysis.LanguageServer.Protocol.dll!Microsoft.CodeAnalysis.Diagnostics.InProcOrRemoteHostAnalyzerRunner.AnalyzeAsync.__AnalyzeCoreAsync|0() Line 82	C#
 	[Async] Microsoft.CodeAnalysis.LanguageServer.Protocol.dll!Microsoft.CodeAnalysis.Diagnostics.InProcOrRemoteHostAnalyzerRunner.AnalyzeAsync(Microsoft.CodeAnalysis.Diagnostics.DocumentAnalysisScope documentAnalysisScope, Microsoft.CodeAnalysis.Project project, Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers compilationWithAnalyzers, bool forceExecuteAllAnalyzers, bool logPerformanceInfo, bool getTelemetryInfo, System.Threading.CancellationToken cancellationToken) Line 67	C#

```
</details>

Likely relates to https://github.com/dotnet/roslyn/issues/65050

### PR DESCRIPTION
**Pull request by jjonescz**
Fixes #65053.

The added test reproduces the error from https://github.com/dotnet/roslyn/issues/65053#issuecomment-1294237444. I wasn't able to write a test for the original error from the issue, but was able to verify manually that it goes away with this fix.

### CODE REVIEW

**Comment by jaredpar** [comment]
@dotnet/roslyn-compiler PTAL

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 1]
```diff
@@ -10933,6 +10933,15 @@ private static bool IsNullabilityMismatch(TypeSymbol type1, TypeSymbol type2)
         public override BoundNode? VisitQueryClause(BoundQueryClause node)
         {
             var result = base.VisitQueryClause(node);
+
+            if (node.Value is BoundLambda lambda)
+            {
+                // 'VisitConversion' only visits a lambda when the lambda has an AnonymousFunction conversion.
+                // This lambda doesn't have a conversion, so we need to visit it here.
+                Debug.Assert(node.HasAnyErrors);
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:10941]: Why do we need the `Debug.Assert` call here? Is that because this is there is no conversion only when there are errors?

Comment (jjonescz) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:10941]: > there is no conversion only when there are errors?

Yes. I got inspired here:

https://github.com/dotnet/roslyn/blob/ef5680468c491a5e7274ce68c944fb1c601b20eb/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs#L6215-L6223

**Comment by jcouv** [comment]
I'm a bit concerned that we're patching one scenario where a lambda was left unconverted, but there might be more places where a lambda could be left unconverted in error scenarios, and they would have the same problem.

Chatted with @jjonescz about possibly relying on the `VisitLambda(BoundLambda)` overload to visit unconverted lambdas and the `VisitLambda(BoundLambda, NamedTypeSymbol?, Optional<LocalState>)` overload for converted lambdas. 
But it is hard to make that separation, as we have multiple paths where conversions are removed, then the operand is visited. That will hit the `VisitLambda(BoundLambda)` overload first, then the conversion will be re-inferred with nullability and the second `VisitLambda` is called.
Making a localized fix seems best for now.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 3)

**Comment by jcouv** [comment]
@dotnet/roslyn-compiler for second review. Thanks

**Review by RikkiGibson — APPROVED** [review]
