### PR TITLE
Fix 'sync namespace' with file scoped namespaces

### LINKED ISSUE #54749: Handle file-scoped namespaces in IDE0130 (match folder with namespace)
The analyzer doesn't handle the new file-scoped namespaces:

https://github.com/dotnet/roslyn/blob/93e7cc3d8e24624ec8f507c6f7b0f60aa6265cba/src/Analyzers/CSharp/Analyzers/MatchFolderAndNamespace/CSharpMatchFolderAndNamespaceDiagnosticAnalyzer.cs#L14

@ryzngard

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes #54749

### CODE REVIEW

File: src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs [hunk 1]
```diff
@@ -470,16 +443,25 @@ private static ExpressionSyntax CreateNamespaceAsMemberAccess(ImmutableArray<str
...
+            {
+                openingBuilder.AddRange(namespaceDeclaration.OpenBraceToken.LeadingTrivia);
+                openingBuilder.AddRange(namespaceDeclaration.OpenBraceToken.TrailingTrivia);
+
+                closingBuilder.AddRange(namespaceDeclaration.CloseBraceToken.LeadingTrivia);
+                closingBuilder.AddRange(namespaceDeclaration.CloseBraceToken.TrailingTrivia);
+            }
+            else if (baseNamespace is FileScopedNamespaceDeclarationSyntax fileScopedNamespace)
+            {
+                openingBuilder.AddRange(fileScopedNamespace.SemicolonToken.TrailingTrivia);
```
Comment (Youssef1313) [inline src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs:463]: Can the semicolon have leading trivia here?

File: src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs [hunk 2]
```diff
@@ -470,16 +443,25 @@ private static ExpressionSyntax CreateNamespaceAsMemberAccess(ImmutableArray<str
...
         private static (ImmutableArray<SyntaxTrivia> openingTrivia, ImmutableArray<SyntaxTrivia> closingTrivia)
-            GetOpeningAndClosingTriviaOfNamespaceDeclaration(NamespaceDeclarationSyntax namespaceDeclaration)
+            GetOpeningAndClosingTriviaOfNamespaceDeclaration(BaseNamespaceDeclarationSyntax baseNamespace)
         {
             var openingBuilder = ArrayBuilder<SyntaxTrivia>.GetInstance();
-            openingBuilder.AddRange(namespaceDeclaration.GetLeadingTrivia());
-            openingBuilder.AddRange(namespaceDeclaration.OpenBraceToken.LeadingTrivia);
-            openingBuilder.AddRange(namespaceDeclaration.OpenBraceToken.TrailingTrivia);
-
             var closingBuilder = ArrayBuilder<SyntaxTrivia>.GetInstance();
```
Comment (Youssef1313) [inline src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs:449]: nit: This is unused for the FileScopedNamespace code path. Consider constructing a builder only for the file-scoped case.

**Review by Youssef1313 — COMMENTED** [review]
I had already made most of these changes in #54755 😄 
But since you're doing a bit more than I did (more tests and fixing move type service), I'll close my PR.

**Comment by Youssef1313** [comment]
Can you mark the PR as "Fixes #54749"

**Comment by CyrusNajmabadi** [comment]
Will do!

File: src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs:463]: yes, though that's a 1:10000 case :)  i'm writing for the 99.9% cases :)

Comment (Youssef1313) [reply src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs:463]: @CyrusNajmabadi To me personally, I agree this case is very very rare. But since it's a simple change, I'd handle it. Users put comments in weird places 😄
I'd expect someone later reporting the following trivia being lost:

```
namespace    R
    /*trivia*/;
```

**Comment by CyrusNajmabadi** [comment]
ping @ryzngard

**Comment by ryzngard** [comment]
I was waiting on #55020 to give this a final pass, since some of the changes overlapped. Will take a look later today

File: src/EditorFeatures/CSharpTest/Debugging/LocationInfoGetterTests.cs [hunk 3]
```diff
@@ -83,7 +83,7 @@ void Method()
     {
     }$$
 }
-", "Class.Method()", 2);
+", "Namespace.Class.Method()", 2);
```
Comment (ryzngard) [inline src/EditorFeatures/CSharpTest/Debugging/LocationInfoGetterTests.cs:86]: Why this change?

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/Debugging/LocationInfoGetterTests.cs:86]: This is correct.  The namepace name shoudl be appended. but it wasn't because the walker wasn't seeing the file-scoped-namespace and was only checking for normal namespaces.

File: src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/CodeRefactorings/SyncNamespace/CSharpChangeNamespaceService.cs:463]: to me it's that i can map where i expect teh trailing trivia to go.  Leading trivia is something else entirely.

**Review by ryzngard — APPROVED** [review]
