### PR TITLE
Fix control flow analysis for local functions

### LINKED ISSUE #39946: Extract method incorrectly inserts return statement when local function call is present
**Version Used**: Latest Roslyn build (commit f3388dcccd1da69d6b7143a5f9b287396357d592)

**Steps to Reproduce**:

1. Highlight statements to extract under a local function call
2. Select "Extract method"

From testing, this bug is not present in 16.4 P5 or P6.

**Expected Behavior**: "return" statement not inserted

**Actual Behavior**: "return" statement is inserted

The screenshots below are from a branch (hence the "extract local function" code action), but the same behavior persists in master.
bug1
bug2

### PR DESCRIPTION
**Pull request by agocke**
Control flow analysis should now use the analysis walker from the base
class instead of defining its own.

Fixes #39946

### CODE REVIEW

File: src/Compilers/CSharp/Portable/FlowAnalysis/ControlFlowPass.cs [hunk 1]
```diff
@@ -199,6 +199,11 @@ protected override ImmutableArray<PendingBranch> RemoveReturns()
             var result = base.RemoveReturns();
             foreach (var pending in result)
             {
+                if (pending.Branch is null)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/FlowAnalysis/ControlFlowPass.cs]: When does this happen?

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractRegionControlFlowPass.cs [hunk 2]
```diff
@@ -27,22 +27,12 @@ public override BoundNode Visit(BoundNode node)
...
-            return VisitLocalFunctionOrLambda(node.Body);
-        }
-
-        private BoundNode VisitLocalFunctionOrLambda(BoundBlock body)
         {
             var oldPending = SavePending(); // We do not support branches *into* a lambda.
             LocalState finalState = this.State;
             this.State = TopState();
             var oldPending2 = SavePending();
-            VisitAlways(body);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/FlowAnalysis/AbstractRegionControlFlowPass.cs]: The comment on line 8 mentions that any fix to this class should also be applied to AbstractRegionDataFlowPass. Does that apply for this change?

File: src/Compilers/CSharp/Portable/FlowAnalysis/ControlFlowPass.cs (hunk 1 above)
Comment (agocke) [reply src/Compilers/CSharp/Portable/FlowAnalysis/ControlFlowPass.cs]: In a local function that is also an iterator, there is a silent generated branch out of the method before the first statement to return the enumerator.

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractRegionControlFlowPass.cs (hunk 2 above)
Comment (agocke) [reply src/Compilers/CSharp/Portable/FlowAnalysis/AbstractRegionControlFlowPass.cs]: These are actually completely different files now. I don't know when they were similar, but it hasn't been for a while. I'll delete both comments.

File: src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs [hunk 3]
```diff
@@ -4129,6 +4129,209 @@ static void Main(string[] args)
...
+}");
+
+            Assert.True(controlFlow.Succeeded);
+            Assert.False(controlFlow.StartPointIsReachable);
+            Assert.False(controlFlow.EndPointIsReachable);
+        }
+
+        [Fact]
+        [WorkItem(39946, "https://github.com/dotnet/roslyn/issues/39946")]
+        public void ControlFlowAnalysisLocalFunctions02()
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs]: Is there anything interesting to testing nested local functions that eventually throw an exception?

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 4]
```diff
@@ -575,7 +575,10 @@ BoundBlock runAnalysis(BoundBlock block, DiagnosticBag blockDiagnostics)
                     // rather we go directly to LowerBodyOrInitializer, which skips over flow analysis (which is in CompileMethod)
                     // (the same thing - calling ControlFlowPass.Analyze in the lowering - is done for lambdas)
                     // It's a bit of code duplication, but refactoring would make things worse.
-                    var endIsReachable = ControlFlowPass.Analyze(localSymbol.DeclaringCompilation, localSymbol, block, blockDiagnostics);
+                    // However, we don't need to report diagnostics here. They will be reported when analyzing the parent method.
+                    var ignored = DiagnosticBag.GetInstance();
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: This is just getting rid of that `Label is not referenced` warning, right?

File: src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs (hunk 3 above)
Comment (agocke) [reply src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs]: Not sure I understand. Is the goal to test nested local functions?

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs (hunk 4 above)
Comment (agocke) [reply src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: This is actually just preventing duplicates from showing up. The reason we are getting rid of those warnings is because we're analyzing the whole method for control flow now, instead of just a scoped segment, so we actually do see that the label is being referenced, just in a way that's illegal (so we provide an error elsewhere)

**Comment by agocke** [comment]
@allisonchou Could you take a look at the IDE extract method test accurately reproduces/fixes the problem you're seeing?

File: src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs [hunk 5]
```diff
@@ -4129,6 +4129,209 @@ static void Main(string[] args)
...
+            /*<bind>*/
+            throw null;
+            /*</bind>*/
+        }
+    }
+}");
+
+            Assert.True(controlFlow.Succeeded);
+            Assert.True(controlFlow.StartPointIsReachable);
+            Assert.False(controlFlow.EndPointIsReachable);
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs]: >controlFlow.EndPointIsReachable [](start = 25, length = 31)

This result is unexpected.

**Comment by allisonchou** [comment]
> @allisonchou Could you take a look at the IDE extract method test accurately reproduces/fixes the problem you're seeing?

@agocke Just tested and it seemed to have fixed the problem. Thanks so much!
