### PR TITLE
Fix FAR for less than operator and add tests for all operators

### LINKED ISSUE #39177: C# reference count shown as 0 for operators <, >
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/742322/c-reference-count-shown-as-0-for-operators.html)._

---
Shows:
        0 references
        static public bool operator &lt;(OrderingMeasure a, OrderingMeasure b)
Although it's used

---
#### Visual Studio Feedback System on 9/23/2019, 01:34 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### LINKED ISSUE #52654: Codelens doesn't count references for `operator <`
**Version Used**: 
VS 16.10 Preview 2

**Steps to Reproduce**:

```csharp
using System;

C a = new(), b = new();
_ = a == b;
_ = a != b;
_ = a > b;
_ = a >= b;
_ = a < b;
_ = a <= b;

public sealed class C
{
    public static bool operator ==(C left, C right) => throw new NotImplementedException();
    public static bool operator !=(C left, C right) => throw new NotImplementedException();
    public static bool operator >(C left, C right) => throw new NotImplementedException();
    public static bool operator >=(C left, C right) => throw new NotImplementedException();
    public static bool operator <(C left, C right) => throw new NotImplementedException();
    public static bool operator <=(C left, C right) => throw new NotImplementedException();
}
```

Then you will found that only `operator <` shows "0 references", while others all "1 reference".

**Expected Behavior**:

`operator <` will also count the references.

**Actual Behavior**:

`operator <` doesn't count.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #52654
Closes #39177 (this was already *partially* working (the `>` part) - and this PR fixed the `<`)

### CODE REVIEW

File: src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs [hunk 1]
```diff
@@ -216,7 +216,7 @@ private static bool TryGetTextForOperator(SyntaxToken token, Document document,
             }
 
             var syntaxFacts = document.GetLanguageService<ISyntaxFactsService>();
-            if (syntaxFacts.IsOperator(token) || syntaxFacts.IsPredefinedOperator(token) || SyntaxFacts.IsAssignmentExpressionOperatorToken(token.Kind()))
+            if (syntaxFacts.IsOperator(token) || SyntaxFacts.IsAssignmentExpressionOperatorToken(token.Kind()))
```
Comment (Youssef1313) [inline src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:219]: "IsPredefinedOperator" only checks the token kind regardless its context. This caused `<` of type argument list (e.g, in `List<int>`) to be classified as less than.

The check of "IsOperator" should handle everything with respect to the token context. I also think `IsAssignmentExpressionOperatorToken` should be removed, but will leave that for now because a test will fail, and F1 isn't the main change intended with this PR.

Comment (CyrusNajmabadi) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:219]: I wouldn't touch this function at all in this pr. It seems to be fixing two unrelated issues.

Comment (Youssef1313) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:219]: @CyrusNajmabadi I had to touch it to fix test failure.

Comment (CyrusNajmabadi) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:219]: the change feels dangerous.  i'm ont sure what unintended consequences tehre would be by removing this case here.  Instead of removing htis, could we instead have the C# f1 helper check if this a < in a generic name and not in a regular expression?

Comment (Youssef1313) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:219]: That way I'll have to special case multiple things:

- TypeArgumentListSyntax
- TypeParameterListSyntax
- FunctionPointerParameterListSyntax
- XmlElementStartTagSyntax
- OperatorMemberCref
- XmlEmptyElementSyntax

This doesn't look neat IMO.

Either way, F1 help service isn't accurate and has bugs.

Does adding more tests to cover all operators that are in the deleted checks make the change more comfortable?

Comment (CyrusNajmabadi) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:219]: or just say that `<` is only an operator here if it's parent is a binaryexpression

File: src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs [hunk 2]
```diff
@@ -215,8 +215,15 @@ private static bool TryGetTextForOperator(SyntaxToken token, Document document,
                 return true;
             }
 
+            // Workaround IsPredefinedOperator returning true for '<' in generics.
+            if (token.IsKind(SyntaxKind.LessThanToken) && token.Parent is not BinaryExpressionSyntax)
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:219]:
```suggestion
            if (token is { Kind: (int)SyntaxKind.LessThanToken, Parent: not BinaryExpressionSyntax })
```

up to you.

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs [hunk 3]
```diff
@@ -215,6 +215,13 @@ private static bool TryGetTextForOperator(SyntaxToken token, Document document,
                 return true;
             }
 
+            // Workaround IsPredefinedOperator returning true for '<' in generics.
+            if (token is { Kind: (int)SyntaxKind.LessThanToken, Parent: not BinaryExpressionSyntax })
```
Comment (Youssef1313) [inline src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:219]:
```suggestion
            if (token is { RawKind: (int)SyntaxKind.LessThanToken, Parent: not BinaryExpressionSyntax })
```

**Comment by Youssef1313** [comment]
@CyrusNajmabadi This should be ready to merge.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks!
