### PR TITLE
Change Windows command line argument parsing

### LINKED ISSUE #4021: Cannot compile a project that contains an embedded resource with a comma in its filename
Steps to reproduce:

- Create a Classic Desktop class library
- Add a file called `a,b.txt`
- Set the `Build Action` on the file to `Embedded Resource`
- Compile the project

Build error:

```
1>------ Rebuild All started: Project: ClassLibrary1, Configuration: Debug Any CPU ------
1>CSC : error CS1906: Invalid option 'ClassLibrary1.a'; Resource visibility must be either 'public' or 'private'
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

### PR DESCRIPTION
**Pull request by jaredpar**
A process in Windows is provided arguments as a flat string yet main methods in applications receive arguments as an arary of string values.  The transition between the flat string and array is done automatically by the runtime in two phases:

- Break into arguments based on spaces and grouping quotes.
- Remove extraneous quotes and backslashes.

Doing both operations at the same time serves to remove separators that are significant to the compilers.  For example:

1. /r:"a.dll,b.dll"
2. /r:a.dll,b.dll

In the main method both of these argument strings will show up as the latter value (the quotes are considered extraneous by the runtime).  Yet these represent very different values to the compiler:

1. Reference a single file named "a.dll,b.dll"
2. Reference two files named a.dll and b.dll respectively

This change restores the native compiler behavior by manually parsing out the flat argument string.  All of the parsing methods were taken directly from the old compiler.

There are a few small changes of note here:

1. VB now considers semicolon to be a list separator as it does comma (unifies behavior between languages and other tools).
2. VB and C# now have unified behavior for collapsing backslash characters.
3. Fixed several unit tests which were validating incorrect behavior.

closes #4021

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @AlekseyTs, @VSadov, @gafter, @TyOverby, @agocke

**Comment by jaredpar** [comment]
Ping CC @AlekseyTs, @VSadov, @gafter, @TyOverby, @agocke

File: src/Compilers/Core/MSBuildTask/BuildClient.cs [hunk 1]
```diff
@@ -32,13 +32,15 @@ internal static class BuildClient
         // Spend up to 20s connecting to a new process, to allow time for it to start.
         private const int TimeOutMsNewProcess = 20000;
 
+        private static bool IsRunningOnWindows => Path.DirectorySeparatorChar == '\\';
```
Comment (AlekseyTs) [inline src/Compilers/Core/MSBuildTask/BuildClient.cs]: Does this guarantee that we are running on Windows? Perhaps better name?

File: src/Compilers/CSharp/Portable/CommandLine/CommandLineParser.cs [hunk 2]
```diff
@@ -1147,7 +1156,7 @@ public new CSharpCommandLineArguments Parse(IEnumerable<string> args, string bas
             };
         }
 
-        private static void ParseAndResolveReferencePaths(string switchName, string switchValue, string baseDirectory, List<string> builder, MessageID origin, List<Diagnostic> diagnostics)
+        private void ParseAndResolveReferencePaths(string switchName, string switchValue, string baseDirectory, List<string> builder, MessageID origin, List<Diagnostic> diagnostics)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CommandLine/CommandLineParser.cs]: Does it have to be instance method?

File: src/Compilers/CSharp/Portable/CommandLine/CommandLineParser.cs [hunk 3]
```diff
@@ -1174,7 +1183,7 @@ private static void ParseAndResolveReferencePaths(string switchName, string swit
             }
         }
 
-        private static string GetWin32Setting(string arg, string value, List<Diagnostic> diagnostics)
+        private string GetWin32Setting(string arg, string value, List<Diagnostic> diagnostics)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CommandLine/CommandLineParser.cs]: Does it have to be instance method?

File: src/Compilers/VisualBasic/Portable/CommandLine/CommandLineParser.vb [hunk 4]
```diff
@@ -1301,11 +1318,11 @@ lVbRuntimePlus:
             Return Nothing
         End Function
 
-        Private Shared Function GetWin32Setting(arg As String, value As String, diagnostics As List(Of Diagnostic)) As String
+        Private Function GetWin32Setting(arg As String, value As String, diagnostics As List(Of Diagnostic)) As String
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/CommandLine/CommandLineParser.vb]: Does it have to be instance method?

**Comment by AlekseyTs** [comment]
LGTM

File: src/Compilers/Core/MSBuildTask/BuildClient.cs (hunk 1 above)
Comment (jaredpar) [inline src/Compilers/Core/MSBuildTask/BuildClient.cs]: Yes.  What name would you suggest?

File: src/Compilers/CSharp/Portable/CommandLine/CommandLineParser.cs (hunk 3 above)
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/CommandLine/CommandLineParser.cs]: No.  I think that is a hold over from an earlier change where it did.  I will move it back.

File: src/Compilers/CSharp/Portable/CommandLine/CommandLineParser.cs (hunk 2 above)
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/CommandLine/CommandLineParser.cs]: Same.

File: src/Compilers/VisualBasic/Portable/CommandLine/CommandLineParser.vb (hunk 4 above)
Comment (jaredpar) [inline src/Compilers/VisualBasic/Portable/CommandLine/CommandLineParser.vb]: Same.

File: src/Compilers/Core/MSBuildTask/BuildClient.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/Core/MSBuildTask/BuildClient.cs]: Just feels like a strange way to detect the platform.

Comment (VSadov) [inline src/Compilers/Core/MSBuildTask/BuildClient.cs]: Do we actually care if it is windows or if it is anything where backslash is a primary separator?

IsRunningOnWindows still seems the shortest way to call this

File: src/Compilers/Core/Portable/CommandLine/CommonCommandLineParser.cs [hunk 5]
```diff
@@ -562,88 +563,197 @@ internal static string RemoveAllQuotes(string arg)
...
 
-                    afterSingleBackslash = !afterSingleBackslash & c == '\\';
-                    return false;
-                }).ToArray();
+            return pool.ToStringAndFree();
+        }
+
+        /// <summary>
+        /// Mimic behavior of the native function by the same name.
+        /// </summary>
```
Comment (VSadov) [inline src/Compilers/Core/Portable/CommandLine/CommonCommandLineParser.cs]: Best description ever!

**Comment by VSadov** [comment]
LGTM

**Comment by jaredpar** [comment]
test win 64 please
