### PR TITLE
SymbolDisplayVisitor.CreateAliasMap – pop out of speculative semantic model to lookup for declared aliases.

### LINKED ISSUE #5002: C# autocomplete uses full namespace rather than alias from using statement
__Steps to Reproduce__
1. Copy the code below.
2. Complete the line `v = new ` with autocomplete.
```csharp
using MSG = Microsoft.Structures.Geometry3d;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            MSG.Vector v = new
        }
    }
}

namespace Microsoft.Structures.Geometry3d
{
    class Vector
    {
    }
}
```
__Expected__
`MSG.Vector v = new MSG.Vector();`
__Actual__
`MSG.Vector v = new Microsoft.Structures.Geometry3d.Vector();`

EDIT: The "Actual" used to say "MSG.Structures.Geometry3d.Vector", but the actual displayed/inserted text is "Microsoft.Structures.Geometry3d.Vector"

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #5002.

@dotnet/roslyn-compiler Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

**Comment by cston** [comment]
LGTM

File: src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor_Minimal.cs [hunk 1]
```diff
@@ -166,7 +166,22 @@ private void MinimallyQualify(INamedTypeSymbol symbol)
                 return SpecializedCollections.EmptyDictionary<INamespaceOrTypeSymbol, IAliasSymbol>();
             }
 
-            var token = semanticModelOpt.SyntaxTree.GetRoot().FindToken(positionOpt);
+            // Walk up the ancestors from the current position. If this is a speculative
+            // model, walk up the corresponding ancestors in the parent model.
+            SemanticModel semanticModel;
+            int position;
+            if (semanticModelOpt.IsSpeculativeSemanticModel)
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor_Minimal.cs]: This should probably be a while loop. Although nesting/chaining speculative semantic models doesn't always work well, it is in part because we keep doing this.

Comment (VSadov) [inline src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor_Minimal.cs]: Do we actually allow to speculate on top of a speculative model?

**Comment by VSadov** [comment]
LGTM
