### PR TITLE
Ensure that warnaserror works identically for warnings configured in …

### LINKED ISSUE #43051: TreatWarningsAsErrors ignored when severity set in EditorConfig
## Workaround
Use `dotnet build -warnaserror` instead of `dotnet build -p:TreatWarningsAsErrors=true` in step 5 of the below repros.

#### Repro steps

1. dotnet new console
2. Edit the source code to:
```csharp
class Program
{
    static void Main(string[] args)
    {
        // warning CS0219: The variable 'unused' is assigned but its value is never used
        int unused = 0;
    }
}
```
3. dotnet build -p:TreatWarningsAsErrors=true
4. Add .editorconfig with:
```editorconfig
root = true

[*.cs]
dotnet_diagnostic.CS0219.severity = warning
```
5. dotnet build -p:TreatWarningsAsErrors=true

#### Expected behavior

I expect the build output in steps 3 and 5 to be the same, i.e. the build in both cases should fail due to CS0219 being promoted to an error.

#### Actual behavior
Build fails in step 3, but not in step 5. `dotnet_diagnostic.CS0219.severity = warning` takes precedence over `/warnaserror+` passed to csc.exe from `-p:TreatWarningsAsErrors=true`

#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.8 (Latest)

#### Diagnostic ID

N/A

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.200/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.200 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

#### Repro steps

1. dotnet new console
2. dotnet add package Microsoft.CodeAnalysis.FxCopAnalyzers -v 2.9.8
3. dotnet build -p:TreatWarningsAsErrors=true
4. Add .editorconfig with:
```editorconfig
root = true

[*.cs]
dotnet_diagnostic.CA1303.severity = default
dotnet_diagnostic.CA1801.severity = warning
```
5. dotnet build -p:TreatWarningsAsErrors=true

#### Expected behavior

I expect the build output in steps 3 and 5 to be the same, i.e. the build in both cases should fail due to two build errors: CA1303, CA1801.

#### Actual behavior

The output from step 3 shows build failure due to two errors: CA1303, CA1801. This is correct and expected:
```
$ dotnet build -p:TreatWarningsAsErrors=true
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 35.32 ms for /home/a-x-d/dev/fx1/fx1.csproj.
Program.cs(9,31): error CA1303: Method 'void Program.Main(string[] args)' passes a literal string as parameter 'value' of a call to 'void Console.WriteLine(string value)'. Retrieve the following string(s) from a resource table instead: "Hello World!". [/home/a-x-d/dev/fx1/fx1.csproj]
Program.cs(7,35): error CA1801: Parameter args of method Main is never used. Remove the parameter or use it in the method body. [/home/a-x-d/dev/fx1/fx1.csproj]

Build FAILED.

Program.cs(9,31): error CA1303: Method 'void Program.Main(string[] args)' passes a literal string as parameter 'value' of a call to 'void Console.WriteLine(string value)'. Retrieve the following string(s) from a resource table instead: "Hello World!". [/home/a-x-d/dev/fx1/fx1.csproj]
Program.cs(7,35): error CA1801: Parameter args of method Main is never used. Remove the parameter or use it in the method body. [/home/a-x-d/dev/fx1/fx1.csproj]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:00.98
```

The build output from step 5 shows build passing with two warnings for CA1303, CA1801. Somehow editor config configuration overrides TreatWarningsAsErrors property. This is not expected and seems incorrect:
```
$ dotnet build -p:TreatWarningsAsErrors=true
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 216.45 ms for /home/a-x-d/dev/fx1/fx1.csproj.
Program.cs(9,31): warning CA1303: Method 'void Program.Main(string[] args)' passes a literal string as parameter 'value' of a call to 'void Co
nsole.WriteLine(string value)'. Retrieve the following string(s) from a resource table instead: "Hello World!". [/home/a-x-d/dev/fx1/fx1.cspro
j]
Program.cs(7,35): warning CA1801: Parameter args of method Main is never used. Remove the parameter or use it in the method body. [/home/a-x-d
/dev/fx1/fx1.csproj]
  fx1 -> /home/a-x-d/dev/fx1/bin/Debug/netcoreapp3.1/fx1.dll

Build succeeded.

Program.cs(9,31): warning CA1303: Method 'void Program.Main(string[] args)' passes a literal string as parameter 'value' of a call to 'void Co
nsole.WriteLine(string value)'. Retrieve the following string(s) from a resource table instead: "Hello World!". [/home/a-x-d/dev/fx1/fx1.cspro
j]
Program.cs(7,35): warning CA1801: Parameter args of method Main is never used. Remove the parameter or use it in the method body. [/home/a-x-d/dev/fx1/fx1.csproj]
    2 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.35
```

### PR DESCRIPTION
**Pull request by mavasani**
…ruleset and global config

1. Fixes #43051
2. Ensures consistent behavior between ruleset and global config. Before the product change in this PR, the added unit tests pass for ruleset scenario, but fails for global config, confirming the inconsistency.

This change enables users to migrate away from rulesets when they desire to have rules configured as warnings by default and bump it to errors in CI with warnaserror. They cannot do this via editorconfig as diagnostic severity settings in editorconfig always override command line options (nowarn and warnaserror).

### CODE REVIEW

**Review by chsienki — APPROVED** [review]

**Comment by mavasani** [comment]
Thanks @chsienki!

@dotnet/roslyn-compiler for an additional review.

File: src/Compilers/CSharp/Portable/Compilation/CSharpDiagnosticFilter.cs [hunk 1]
```diff
@@ -196,6 +196,12 @@ internal static class CSharpDiagnosticFilter
             {
                 // 4. Global analyzer config level
                 isSpecified = true;
+
+                // '/warnaserror' should promote warnings configured in global analyzer config to error.
+                if (report == ReportDiagnostic.Warn && generalDiagnosticOption == ReportDiagnostic.Error)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Compilation/CSharpDiagnosticFilter.cs:201]: Why do we only consider `generalDiagnosticOption` in this particular `if` block? Why not the others essentially?

Comment (mavasani) [reply src/Compilers/CSharp/Portable/Compilation/CSharpDiagnosticFilter.cs:201]: This is due to the fact that global configs are lazily parsed, while rulesets are parsed upfront by the command line parser.

1. Rulesets are parsed before parsing `/warnaserror` command line arguments: http://sourceroslyn.io/#Microsoft.CodeAnalysis.CSharp/CommandLine/CSharpCommandLineParser.cs,158
2. When parsing `/warnaserror` on command line, options from rulesets are directly bumped to errors in place: http://sourceroslyn.io/#Microsoft.CodeAnalysis.CSharp/CommandLine/CSharpCommandLineParser.cs,828

Comment (mavasani) [reply src/Compilers/CSharp/Portable/Compilation/CSharpDiagnosticFilter.cs:201]: By the way, we can consider implementing a similar fix for settings in editorconfig files, i.e. if you specify `dotnet_diagnostic.RuleId.severity = warning` in an editorconfig and execute with `/warnaserror`, then the diagnostic gets promoted to error - that does seem more sensible behavior as `/warnaserror` should ideally imply one does not see any warnings, but only errors (unless of course users have a `/warnaserror-:RuleId` for specific rules). Customers are also requesting the fix to editorconfig behavior in https://github.com/dotnet/roslyn/issues/43051, but there is potential of that being a more visible breaking change for existing users as editorconfig support in compiler has been shipped for a while. We have 2 options:

1. Avoid breaking change for editorconfig settings, and ask users to instead switch to global config if they desire `/warnaserror` to bump user configured warnings to errors. The approach taken currently in this PR.
2. Make the more correct fix of doing this change for both editorconfig and global config settings, at the risk of breaking some customers who have configured warnings in editorconfig files and run with `/warnaserror`. This would be a simple change to make in this PR if we are comfortable with it.

Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Compilation/CSharpDiagnosticFilter.cs:201]: Where do we document what the precedence level is between all of the various options here? I was a bit surprised at first glance to see that the test verifies that the command line essentially overrides the config files. Likely my intuition is just off here. But wanted to find a full list of "A wins over B" so I could consider what other tests we may need here.

Comment (mavasani) [reply src/Compilers/CSharp/Portable/Compilation/CSharpDiagnosticFilter.cs:201]: We have https://github.com/dotnet/roslyn/issues/47154 tracking adding this documentation.

Comment (mavasani) [reply src/Compilers/CSharp/Portable/Compilation/CSharpDiagnosticFilter.cs:201]: @jaredpar @chsienki I plan to add the precedence level documentation tracked in https://github.com/dotnet/roslyn/issues/47154 to docs.microsoft.com later today.

However, the open question in my above comment https://github.com/dotnet/roslyn/pull/47710#discussion_r490676970 still needs to be answered to define this order wrt to command line options: do we believe that command line options (/nowarn and /warnaserror) should always override diagnostic settings from any of the other sources (editorconfig, global config and rulesets)? I think that should be the case, as shown by the scenarios in https://github.com/dotnet/roslyn/issues/43051.

This PR ensures these semantics for global configs. I can create a follow-up PR for ensuring the same semantics for editorconfigs, if we feel it is a reasonable behavior change.

Comment (mavasani) [reply src/Compilers/CSharp/Portable/Compilation/CSharpDiagnosticFilter.cs:201]: @jaredpar Do you feel scheduling a meeting for discussing this would be preferrable? Also, should this PR be retargeted to 16.8 release branch?

Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Compilation/CSharpDiagnosticFilter.cs:201]: Sorry I just lost track of this.

**Review by jaredpar — APPROVED** [review]
