### PR TITLE
Check escape after converting

### LINKED ISSUE #64045: Incorrect ref escape analysis
Note: the erroneous scenario is outlined in https://github.com/dotnet/roslyn/issues/64045#issuecomment-1271568313 and explained in the following comments.

**Version Used**: 

Version 17.4.0 Preview 2.0
C# Tools   4.4.0-2.22430.14+2f760738cb92f32f50c981b68ba04ac3c8b7ee48

**Steps to Reproduce**:

https://gist.github.com/ufcpp/19d090babe824ab3fc064203b50de684

**Expected Behavior**:

Error at

https://gist.github.com/ufcpp/19d090babe824ab3fc064203b50de684#file-shoulderror-cs-L7

No error at

https://gist.github.com/ufcpp/19d090babe824ab3fc064203b50de684#file-shouldnoterror1-cs-L5
https://gist.github.com/ufcpp/19d090babe824ab3fc064203b50de684#file-shouldnoterror1-cs-L6
https://gist.github.com/ufcpp/19d090babe824ab3fc064203b50de684#file-shouldnoterror2-cs-L9
https://gist.github.com/ufcpp/19d090babe824ab3fc064203b50de684#file-shouldnoterror2-cs-L11
https://gist.github.com/ufcpp/19d090babe824ab3fc064203b50de684#file-shouldnoterror2-cs-L14
https://gist.github.com/ufcpp/19d090babe824ab3fc064203b50de684#file-shouldnoterror2-cs-L16
https://gist.github.com/ufcpp/19d090babe824ab3fc064203b50de684#file-shouldnoterror2-cs-L19
https://gist.github.com/ufcpp/19d090babe824ab3fc064203b50de684#file-shouldnoterror2-cs-L21

**Actual Behavior**:

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #64045.

### CODE REVIEW

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 2)

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler for second review

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 1]
```diff
@@ -25763,5 +25763,115 @@ .maxstack  2
...
+                // (12,27): error CS9075: Cannot return a parameter by reference 'i4' because it is scoped to the current method
+                //         return new RS(ref i4);
+                Diagnostic(ErrorCode.ERR_RefReturnScopedParameter, "i4").WithArguments("i4").WithLocation(12, 27));
+        }
+
+        [Fact, WorkItem(64045, "https://github.com/dotnet/roslyn/issues/64045")]
+        public void ConstructorInvocationValEscape_02()
+        {
+            var source = """
+
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:25823]:
```suggestion
```

Nit

**Review by jaredpar — APPROVED** [review]

**Review by cston — APPROVED** [review]
