### PR TITLE
Handle additional diagnostic scenarios for captured primary constructor parameters

### LINKED ISSUE #67162: Consider warning for [StructLayout] usage with primary constructor
I noticed that we produce a warning if you use StructLayout on a partial (undefined ordering).
Should we do something similar for primary constructors (and record structs)?
Alternatively, we can define/specify/verify the ordering.

```
// (5,15): warning CS0282: There is no defined ordering between fields in multiple declarations of partial struct 'C'. To specify an ordering, all instance fields must be in the same declaration.                
Diagnostic(ErrorCode.WRN_SequentialOnPartialClass, "C").WithArguments("C")); 
```

This was also reported [here](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1748065) with an example showing an unexpected execution output.

Relates to test plan https://github.com/dotnet/roslyn/issues/65697

### PR DESCRIPTION
**Pull request by AlekseyTs**
Closes #67162.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 1]
```diff
@@ -1931,18 +1939,43 @@ private BoundExpression BindNonMethod(SimpleNameSyntax node, Symbol symbol, Bind
                             if (IsBadLocalOrParameterCapture(parameter, parameter.Type, parameter.RefKind))
                             {
                                 isError = true;
-                                Error(diagnostics, parameter.Type.IsRefLikeType ? ErrorCode.ERR_AnonDelegateCantUseRefLike : ErrorCode.ERR_AnonDelegateCantUse, node, parameter.Name);
+
+                                if (parameter.RefKind != RefKind.None)
+                                {
+                                    Error(diagnostics, ErrorCode.ERR_AnonDelegateCantUse, node, parameter.Name);
+                                }
+                                else if (parameter.Type.IsRestrictedType(ignoreSpanLikeTypes: true))
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:1947]: Would it be simpler to remove this case and just updating `ERR_AnonDelegateCantUseRefLike` (used in case below) to say "restricted" instead of "ref-like"?

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 2]
```diff
@@ -1931,18 +1939,43 @@ private BoundExpression BindNonMethod(SimpleNameSyntax node, Symbol symbol, Bind
...
-                                    (parameter.RefKind != RefKind.None || parameter.Type.IsRefLikeType) &&
+                                    (parameter.RefKind != RefKind.None || parameter.Type.IsRestrictedType()) &&
                                     !IsInsideNameof)
                                 {
-                                    Error(diagnostics, parameter.Type.IsRefLikeType ? ErrorCode.ERR_UnsupportedPrimaryConstructorParameterCapturingRefLike : ErrorCode.ERR_UnsupportedPrimaryConstructorParameterCapturingRef, node, parameter.Name);
+                                    if (parameter.RefKind != RefKind.None)
+                                    {
+                                        Error(diagnostics, ErrorCode.ERR_UnsupportedPrimaryConstructorParameterCapturingRef, node, parameter.Name);
+                                    }
+                                    else if (parameter.Type.IsRestrictedType(ignoreSpanLikeTypes: true))
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:1970]: Same comment here (consider using two error codes, one for `ref` and one for bad type, instead of three)

File: src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs [hunk 3]
```diff
@@ -15430,5 +15430,279 @@ public S3(object o) : this()
...
+" + declaration + @" C4(System.ArgIterator z)
+{
+}
+";
+            var comp = CreateCompilation(src1, targetFramework: TargetFramework.DesktopLatestExtended);
+            comp.VerifyDiagnostics(
+                // (7,13): error CS9136: Cannot use primary constructor parameter of type 'ArgIterator' inside an instance member
+                //         _ = a;
+                Diagnostic(ErrorCode.ERR_UnsupportedPrimaryConstructorParameterCapturingRefAny, "a").WithArguments("System.ArgIterator").WithLocation(7, 13),
+                // (16,37): error CS4013: Instance of type 'ArgIterator' cannot be used inside a nested function, query expression, iterator block or async method
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs:15681]: Should this be documented as a compat break?

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 1)

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:1947]: > Would it be simpler to remove this case and just updating ERR_AnonDelegateCantUseRefLike (used in case below) to say "restricted" instead of "ref-like"?

The logic doesn't look particularly complicated to me and we have an existing error for the situation, which was reported for regular parameters during lambda rewrite. In a sense, I am preserving an existing behavior for regular parameters by using ```ErrorCode.ERR_SpecialByRefInLambda``` here.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 4]
```diff
@@ -1899,7 +1899,15 @@ private BoundExpression BindNonMethod(SimpleNameSyntax node, Symbol symbol, Bind
                             if (IsBadLocalOrParameterCapture(localSymbol, type, localSymbol.RefKind))
                             {
                                 isError = true;
-                                Error(diagnostics, ErrorCode.ERR_AnonDelegateCantUseLocal, node, localSymbol);
+
+                                if (localSymbol.RefKind == RefKind.None && type.IsRestrictedType(ignoreSpanLikeTypes: true))
```
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:1903]: > the new error code seems better for by-value ref-like types. Would this be better without the 

I am preserving original behavior for this scenario. The ErrorCode.ERR_SpecialByRefInLambda error used to be reported during lambda rewrite.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 1)

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs [hunk 5]
```diff
@@ -2651,6 +2651,14 @@ private void CheckSequentialOnPartialType(BindingDiagnosticBag diagnostics)
                     }
                 }
             }
+
+            if (whereFoundField != null &&
+                PrimaryConstructor is { } primaryConstructor && primaryConstructor.GetCapturedParameters().Any() &&
+                (primaryConstructor.SyntaxRef.SyntaxTree != whereFoundField.SyntaxTree || primaryConstructor.SyntaxRef.Span != whereFoundField.Span))
+            {
+                diagnostics.Add(ErrorCode.WRN_SequentialOnPartialClass, Locations[0], this);
```
Comment (jjonescz) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:2659]:
```suggestion
                diagnostics.Add(ErrorCode.WRN_SequentialOnPartialClass, GetFirstLocation(), this);
```

to be consistent with https://github.com/dotnet/roslyn/pull/67678

**Review by jjonescz — APPROVED** [review]
