### PR TITLE
Collection expressions: IOperation and Add method with params array

### LINKED ISSUE #72461: Custom `IEnumarable<T>.Add(IEnumerable<T>)` + Collection Initalizer causes `csc.exe` to crash
**Version Used**: 
Visual Studio: Version 17.9.2
dotnet: 6.0.419

**Steps to Reproduce**:

1. 
```cs
public static class MyExtensions2
{
  public static void Add<T, TEnumElement>(this ICollection<T> collection,
    IEnumerable<TEnumElement>? elements)
    where TEnumElement : T
  {
    if (elements is null)
      return;
    ArgumentNullException.ThrowIfNull(collection);
    if (collection is List<T> list)
      list.AddRange((IEnumerable<T>)elements);
    else
      foreach (T element in elements)
        collection.Add(element);
  }

  public static void Add<T>(this ICollection<T> collection, params T[] elements)
  {
    if (elements?.Length is (null or 0))
      return;
    Add(collection, (IEnumerable<T>)elements);
  }

}

public class Class2
{
  public Dictionary<string, string?> Issue(ICollection<string?> fullNames)
  {
    Dictionary<string, string?> result = new()
    {
      fullNames
      .Where(n => !string.IsNullOrEmpty(n))
      .Cast<string>()
      .Select(GetParts)
    };
    return result;
  }

  private static KeyValuePair<string, string?> GetParts(string fullName)
  {
    var parts = fullName.Split(" ", 2);
    return new(parts[0], parts.ElementAtOrDefault(1));
  }
}
```
2. invoke CodeFix
image
3. get invalid code
image
4. "fix" it 
image
5. compile
6.  `Error	MSB6006	"csc.exe" exited with code -2146232797.	ClassLibrary2	C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets	84`

**Diagnostic Id**:

IDE0028 Collection initialization can be simplified

**Expected Behavior**:
- can initialze Dict with `[..]` with Enumerable/List of KVP's
- or let CodeFix produce Code using the `new(IEnumerable<KeyValuePair<TKey, TValue>> collection)` constructor
**Actual Behavior**:
- csc.exe crashes with unusefull exit code

**Notes**:
Due to varying Versions of VS between our collogues, and slow updates on the build server, we suspect this Issue arose between VS 17.8 (suspected last known working) and 17.9.2 (current tested).

Windows Event Viewer has the following:
image
```txt
Faulting application name: csc.exe, version: 4.900.24.12101, time stamp: 0xdf363ce0
Faulting module name: Microsoft.CodeAnalysis.ni.dll, version: 4.900.24.12101, time stamp: 0xf92539f3
Exception code: 0x80131623
Fault offset: 0x0000000001b78a97
Faulting process id: 0xea00
Faulting application start time: 0x01da715d3033203d
Faulting application path: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe
Faulting module path: C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\Microsoft.Cbf18da00#\6838802e15d8dcce8bf54d191c41ad64\Microsoft.CodeAnalysis.ni.dll
Report Id: 155582bc-5d44-423a-a3a2-d47c8b3c14fa
Faulting package full name: 
Faulting package-relative application ID: 
```
image

```txt
Application: csc.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.InvalidOperationException: Unexpected value 'Microsoft.CodeAnalysis.CSharp.BoundArrayCreation' of type 'Microsoft.CodeAnalysis.CSharp.BoundArrayCreation'
   at Microsoft.CodeAnalysis.CSharp.BoundNode.GetConversion(BoundExpression conversion, BoundValuePlaceholder placeholder)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundCollectionExpressionSpreadElement(BoundCollectionExpression expr, BoundCollectionExpressionSpreadElement element)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundCollectionExpressionElement(BoundCollectionExpression expr, BoundNode element)
   at System.Collections.Immutable.ImmutableArray.CreateRange[TSource,TArg,TResult](ImmutableArray`1 items, Func`3 selector, TArg arg)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundCollectionExpression(BoundCollectionExpression expr)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundConversionOperation(BoundConversion boundConversion, Boolean forceOperandImplicitLiteral)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateVariableDeclaratorInitializer(BoundLocalDeclaration boundLocalDeclaration, SyntaxNode syntax)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateVariableDeclaratorInternal(BoundLocalDeclaration boundLocalDeclaration, SyntaxNode syntax)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateVariableDeclarator(BoundNode declaration, SyntaxNode declarationSyntax)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundLocalDeclarationOperation(BoundLocalDeclaration boundLocalDeclaration)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateFromArray[TBoundNode,TOperation](ImmutableArray`1 boundNodes)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundBlockOperation(BoundBlock boundBlock)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateMethodBodyOperation(BoundNonConstructorMethodBody boundNode)
   at Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(BoundNode boundNode)
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetRootOperation()
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetOperationWorker(CSharpSyntaxNode node, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetOperationWorker(CSharpSyntaxNode node, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetOperationCore(SyntaxNode node, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.GetOperationBlocksToAnalyze(ImmutableArray`1 executableBlocks, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.<>c__DisplayClass11_0.<ExecuteDeclaringReferenceActions>g__executeExecutableCodeActions|2()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.ExecuteDeclaringReferenceActions(SyntaxReference decl, SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, GroupedAnalyzerActions coreActions, GroupedAnalyzerActions additionalPerSymbolActions, Boolean shouldExecuteSyntaxNodeActions, Boolean shouldExecuteOperationActions, Boolean shouldExecuteCodeBlockActions, Boolean shouldExecuteOperationBlockActions, Boolean isInGeneratedCode, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.ExecuteDeclaringReferenceActions(SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, Boolean isGeneratedCodeSymbol, IGroupedAnalyzerActions additionalPerSymbolActions, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<TryProcessSymbolDeclaredAsync>d__137.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<TryProcessEventCoreAsync>d__136.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<ProcessEventAsync>d__134.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<ProcessCompilationEventsCoreAsync>d__133.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, Microsoft.CodeAnalysis.ErrorReporting.ErrorSeverity, Boolean)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportAndPropagateUnlessCanceled(System.Exception, System.Threading.CancellationToken, Microsoft.CodeAnalysis.ErrorReporting.ErrorSeverity)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<ProcessCompilationEventsCoreAsync>d__133.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<ProcessCompilationEventsCoreAsync>d__133.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetException(System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetException(System.Exception)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<ProcessEventAsync>d__134.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetException(System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetException(System.Exception)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<TryProcessEventCoreAsync>d__136.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetException(System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetException(System.Exception)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<TryProcessSymbolDeclaredAsync>d__137.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<GetPerSymbolAnalyzerActionsAsync>d__152.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<GetPerSymbolAnalyzerActionsAsync>d__153.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<<GetPerSymbolAnalyzerActionsAsync>g__getAllActionsAsync|153_0>d.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<<GetPerSymbolAnalyzerActionsAsync>g__getInheritedActionsAsync|153_1>d.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<GetPerSymbolAnalyzerActionsAsync>d__153.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<<GetPerSymbolAnalyzerActionsAsync>g__getAllActionsAsync|153_0>d.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[Microsoft.CodeAnalysis.Diagnostics.AnalyzerActions, Microsoft.CodeAnalysis, Version=4.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].TrySetResult(Microsoft.CodeAnalysis.Diagnostics.AnalyzerActions)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Microsoft.CodeAnalysis.Diagnostics.AnalyzerActions, Microsoft.CodeAnalysis, Version=4.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].SetResult(Microsoft.CodeAnalysis.Diagnostics.AnalyzerActions)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<<GetPerSymbolAnalyzerActionsAsync>g__getSymbolActionsCoreAsync|153_2>d.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[Microsoft.CodeAnalysis.Diagnostics.AnalyzerActions, Microsoft.CodeAnalysis, Version=4.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].TrySetResult(Microsoft.CodeAnalysis.Diagnostics.AnalyzerActions)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[Microsoft.CodeAnalysis.Diagnostics.AnalyzerActions, Microsoft.CodeAnalysis, Version=4.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].SetResult(Microsoft.CodeAnalysis.Diagnostics.AnalyzerActions)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager+<GetPerSymbolAnalyzerActionsAsync>d__13.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager+<GetSymbolAnalysisScopeAsync>d__8.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager+<GetSymbolAnalysisScopeCoreAsync>d__9.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

### PR DESCRIPTION
**Pull request by cston**
For a collection with an `Add(params T[])` method, `Binder.GetUnderlyingCollectionExpressionElement` was returning the array rather than the element in the array.

Fixes #72461

### CODE REVIEW

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs [hunk 1]
```diff
@@ -33158,6 +33158,466 @@ class MyCollection : IEnumerable
...
+                    public IEnumerator<T> GetEnumerator() => _list.GetEnumerator();
+                    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
+                }
+                class Program
+                {
+                    static void Main()
+                    {
+                        int x = 1;
+                        MyCollection<int> y = [2, 3];
+                        MyCollection<object> z = /*<bind>*/[x, ..y]/*</bind>*/;
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:33228]: I do not think we should change it in this PR, or perhaps do anything about it ever, but the codegen for this sure is something. We alloc an array of length 1 for each element of `y` in order to call `Add(params object[])`.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:33228]: It might be worth demonstrating the current behavior, though, by adding a Console.Write call to `MyCollection<T>.Add`. Up to you.

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs [hunk 2]
```diff
@@ -33158,6 +33158,466 @@ class MyCollection : IEnumerable
...
+                    {
+                        MyCollection x = /*<bind>*/[[]]/*</bind>*/;
+                        x.Report();
+                    }
+                }
+                """;
+
+            comp = CreateCompilation([sourceB2, sourceA, s_collectionExtensions], options: TestOptions.ReleaseExe);
+            comp.VerifyEmitDiagnostics();
+            CompileAndVerify(comp, expectedOutput: "[], ");
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:33456]: I expected the output here to be similar to the output for `sourceB1`. Am I missing something about the semantics of the respective expressions?

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs [hunk 3]
```diff
@@ -33158,6 +33158,466 @@ class MyCollection : IEnumerable
...
+                """);
+
+            string sourceB2 = """
+                class Program
+                {
+                    static void Main()
+                    {
+                        object[] x = [1];
+                        object[][] y = [[2, 3]];
+                        MyCollection z = /*<bind>*/[x, ..y]/*</bind>*/;
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:33598]: I think this is another case where behavior would be made more clear by also writing to console when Add is called (which could show how many times Add is called and with what values).

**Review by RikkiGibson — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs [hunk 4]
```diff
@@ -818,12 +818,27 @@ internal bool HasCollectionExpressionApplicableAddMethod(SyntaxNode syntax, Type
...
                     _ => null,
                 };
             }
             return element;
+
+            static BoundExpression getCollectionInitializerElement(BoundCollectionElementInitializer collectionInitializer)
+            {
+                int argIndex = collectionInitializer.InvokedAsExtensionMethod ? 1 : 0;
+                var arg = collectionInitializer.Arguments[argIndex];
+                if (collectionInitializer.Expanded && collectionInitializer.AddMethod.Parameters[argIndex].IsParams)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:832]: >&& collectionInitializer.AddMethod.Parameters[argIndex].IsParams [](http://example.com/codeflow?start=51&length=64)

I think we should remove this check. At best it is redundant. because overload resolution already checked for that. At worse, it will lead to the same bug when the ```collectionInitializer.AddMethod``` is an override that doesn't have `ParamArray` attribute (overload resolution checks for it on the least derived declaration). The ```collectionInitializer.Expanded``` condition is sufficient in my opinion.

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs [hunk 5]
```diff
@@ -818,12 +818,27 @@ internal bool HasCollectionExpressionApplicableAddMethod(SyntaxNode syntax, Type
...
+                    BoundCollectionElementInitializer collectionInitializer => getCollectionInitializerElement(collectionInitializer),
                     BoundDynamicCollectionElementInitializer dynamicInitializer => dynamicInitializer.Arguments[0],
                     _ => null,
                 };
             }
             return element;
+
+            static BoundExpression getCollectionInitializerElement(BoundCollectionElementInitializer collectionInitializer)
+            {
+                int argIndex = collectionInitializer.InvokedAsExtensionMethod ? 1 : 0;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:830]: >argIndex [](http://example.com/codeflow?start=20&length=8)

Consider asserting that this argument is not a default value.

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs [hunk 6]
```diff
@@ -33158,6 +33158,466 @@ class MyCollection : IEnumerable
...
+        {
+            string source = """
+                using System;
+                using System.Collections.Generic;
+                static class Extensions
+                {
+                    public static void Add<T>(this ICollection<T> collection, params T[] elements)
+                    {
+                        foreach (T element in elements)
+                            collection.Add(element);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:33173]: >Add [](http://example.com/codeflow?start=39&length=3)

Just curious, what method is called here?

**Comment by AlekseyTs** [comment]
Done with review pass (commit 2)

**Comment by AlekseyTs** [comment]
@cston Consider leaving the bug active and assigning it to me when this PR is merged. I will make sure similar scenarios with param collections are working properly.

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs (hunk 4 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:832]: It's necessary to check that the `argIndex` refers to the `params` parameter even if the `collectionInitializer.Expanded` to allow for the case where there is a parameter before the `params` parameter (see `Add_ParamsArray_04`):
```
public void Add(T x, params T[] y) { ... }
```

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs (hunk 6 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:33173]: The implementation of `ICollection<T>.Add(T)` is called on the `collection` instance.

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs (hunk 4 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: It looks like the `ParamArray` attribute is added to overrides, at least for overrides declared in C#. But I've changed the check here to avoid using `IsParams`.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: > It looks like the `ParamArray` attribute is added to overrides, at least for overrides declared in C#. 

What is important is the fact that the presence of the attribute on overrides is not required for the method to be used in expanded form. And metadata like that can easily be created.

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs (hunk 6 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:33173]: > The implementation of `ICollection<T>.Add(T)` is called on the `collection` instance.

I that method is available and it is preferred over `params` version here, how do we end up using `params` method for collection expression?

Comment (cston) [reply src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:33173]: The `ICollection<KeyValuePair<K, V>>.Add()` method on `Dictionary<K, V>` is ignored in the collection expression because it is an explicit implementation.

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs [hunk 7]
```diff
@@ -33158,6 +33158,548 @@ class MyCollection : IEnumerable
...
+                using System.Collections;
+                using System.Collections.Generic;
+                abstract class MyCollectionBase 
+                {
+                    public abstract void Add(params object[] x);
+                }
+                class MyCollection : MyCollectionBase, IEnumerable<object>
+                {
+                    private List<object> _list = new();
+                    public override void Add(object[] x) => _list.AddRange(x);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:33667]: >public override void Add(object[] x) => _list.AddRange(x); [](http://example.com/codeflow?start=20&length=58)

It doesn't look like this test targets an interesting scenario when the override doesn't have `ParamArray` attribute. Consider adding a test for this scenario as well. The situation can be achieved by placing `abstract` and `override` methods in different assemblies and adding `params` modifier to the `abstract` method after the `override` method is compiled.

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs [hunk 8]
```diff
@@ -818,12 +818,28 @@ internal bool HasCollectionExpressionApplicableAddMethod(SyntaxNode syntax, Type
...
+                var arg = collectionInitializer.Arguments[argIndex];
+                Debug.Assert(!collectionInitializer.DefaultArguments[argIndex]);
+                if (collectionInitializer.Expanded && argIndex == collectionInitializer.AddMethod.ParameterCount - 1)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:833]: >argIndex == collectionInitializer.AddMethod.ParameterCount - 1 [](http://example.com/codeflow?start=54&length=62)

Are we testing scenario when ```collectionInitializer.Expanded``` is true, but this condition is is false?

**Comment by AlekseyTs** [comment]
Done with review pass (commit 4)

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs (hunk 8 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:833]: Yes, `Add_ParamsArray_04`.

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs [hunk 9]
```diff
@@ -33158,6 +33158,581 @@
...
+        public void Add_ParamsArray_09()
+        {
+            string sourceA1 = """
+                public abstract class MyCollectionBase 
+                {
+                    public abstract void Add(object[] x);
+                }
+                """;
+            string assemblyName = GetUniqueName();
+            var comp = CreateCompilation(new AssemblyIdentity(assemblyName, new Version(1, 0, 0, 0)),  sourceA1, references: TargetFrameworkUtil.StandardReferences);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:33681]: >var comp = CreateCompilation(new AssemblyIdentity(assemblyName, new Version(1, 0, 0, 0)),  sourceA1, references: TargetFrameworkUtil.StandardReferences); [](http://example.com/codeflow?start=12&length=153)

It looks like correctness leg complains about formatting issue around this line.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 6)

**Review by 333fred — APPROVED** [review]

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs (hunk 2 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:33456]: In `sourceB1`, the `Add(params MyCollection[])` call for `x` in `[x, ..y]` is bound in expanded form, that is we call the method with `Add(new MyCollection[] { x })`. In `sourceB2`, the call for `[]` in `[[]]` is bound in normal form, that is we call `Add(new MyCollection[0])`. Add `Console.WriteLine()` calls to hopefully indicate this.
