### PR TITLE
View call hierarchy fix (#57856)

### LINKED ISSUE #57856: Editor Context Menu allows to view Call Hierarchy on Property Setters, but Search finds no results
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Editor-Context-Menu-allows-to-view-Call-/1586919)._

---
In C# text editor Right-clicked on a Property's setter (the "set" keyword) and select `View Call Hierarchy`
The Call Hierarchy tool window is shown. With a tree of `Calls to set_<property>`, `Calls to Overrides` and `Calls to Base member <fully-qualified-property-name>.set` but when I expand it says Search found no results.
This is the bug.

Note: If I do the same on the Property name, then it finds calls to both getter and setter, but doesn't allow me to filter just the setters.

---
#### Feedback Bot on 11/17/2021, 02:13 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by maciek231**
Fix #57856

Fix view call hierarchy tests. Assertions in methods 'VerifyResult' and 'VerifyResultName' weren't reached, if the specified root had no callers.

### CODE REVIEW

File: src/VisualStudio/CSharp/Test/CallHierarchy/CSharpCallHierarchyTests.cs [hunk 1]
```diff
@@ -474,6 +474,11 @@ class C
         void G$$oo()
         {
         }
+
+        void Foo()
```
Comment (ryzngard) [inline src/VisualStudio/CSharp/Test/CallHierarchy/CSharpCallHierarchyTests.cs:478]: nit: We avoid Foo these days. Suggest using single letter names such as "M" instead

File: src/VisualStudio/TestUtilities2/CallHierarchy/CallHierarchyTestState.vb [hunk 2]
```diff
@@ -172,19 +172,30 @@ Namespace Microsoft.CodeAnalysis.Editor.UnitTests.CallHierarchy
...
         Friend Sub VerifyResultName(root As CallHierarchyItem, searchCategory As String, expectedCallers As String(), Optional scope As CallHierarchySearchScope = CallHierarchySearchScope.EntireSolution, Optional documents As IImmutableSet(Of Document) = Nothing)
+            Dim callers = New List(Of String)
             SearchRoot(root, searchCategory, Sub(c As ICallHierarchyNameItem)
-                                                 Assert.Contains(ConvertToName(c), expectedCallers)
+                                                 callers.Add(ConvertToName(c))
                                              End Sub,
                 scope,
                 documents)
+
+            For Each expected In expectedCallers
```
Comment (ryzngard) [inline src/VisualStudio/TestUtilities2/CallHierarchy/CallHierarchyTestState.vb:182]: worth adding a check that the size of the two collections is the same as well to make sure nothing is added that wasn't expected

File: src/VisualStudio/TestUtilities2/CallHierarchy/CallHierarchyTestState.vb [hunk 3]
```diff
@@ -172,19 +172,30 @@ Namespace Microsoft.CodeAnalysis.Editor.UnitTests.CallHierarchy
...
         Friend Sub VerifyResult(root As CallHierarchyItem, searchCategory As String, expectedCallers As String(), Optional scope As CallHierarchySearchScope = CallHierarchySearchScope.EntireSolution, Optional documents As IImmutableSet(Of Document) = Nothing)
+            Dim callers = New List(Of String)
             SearchRoot(root, searchCategory, Sub(c As CallHierarchyItem)
-                                                 Assert.Contains(ConvertToName(c), expectedCallers)
+                                                 callers.Add(ConvertToName(c))
                                              End Sub,
                 scope,
                 documents)
+
+            For Each expected In expectedCallers
```
Comment (ryzngard) [inline src/VisualStudio/TestUtilities2/CallHierarchy/CallHierarchyTestState.vb:195]: worth adding a check that the size of the two collections is the same as well to make sure nothing is added that wasn't expected

**Review by ryzngard — CHANGES_REQUESTED** [review]
These changes look good overall but I don't see a test verifying the fixed scenario for setters. Thanks for contributing! Once these tests are in and small naming changes we can get these in.

**Review by ryzngard — APPROVED** [review]
:shipit:
