### PR TITLE
Fix ArgumentNullException under a race condition in analyzer driver

### LINKED ISSUE #59988: ArgumentNullException in Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteBlockActionsCore
Saw the below exception during analyzer execution in the IDE in gold bar:

```
StreamJsonRpc.RemoteInvocationException: Value cannot be null.
Parameter name: source
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__16`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
RPC server exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: source
      at System.Linq.Enumerable.Cast[TResult](IEnumerable source)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteBlockActionsCore[TBlockStartAction,TBlockAction,TNodeAction,TNodeStateData,TNode,TLanguageKindEnum](IEnumerable`1 startActions, IEnumerable`1 actions, IEnumerable`1 endActions, DiagnosticAnalyzer analyzer, SyntaxNode declaredNode, ISymbol declaredSymbol, ImmutableArray`1 executableBlocks, Func`2 getNodesToAnalyze, SemanticModel semanticModel, Func`2 getKind, BlockAnalyzerStateData`2 analyzerState, Boolean isGeneratedCode)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.TryExecuteOperationBlockActions(IEnumerable`1 operationBlockStartActions, IEnumerable`1 operationBlockActions, IEnumerable`1 operationBlockEndActions, DiagnosticAnalyzer analyzer, SyntaxNode declaredNode, ISymbol declaredSymbol, ImmutableArray`1 operationBlocks, ImmutableArray`1 operations, SemanticModel semanticModel, Int32 declarationIndex, AnalysisScope analysisScope, AnalysisState analysisState, Boolean isGeneratedCode)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.<>c__DisplayClass12_0.<TryExecuteDeclaringReferenceActions>g__executeOperationsBlockActions|7(ImmutableArray`1 operationBlocksToAnalyze, ImmutableArray`1 operationsToAnalyze, IEnumerable`1 codeBlockActions)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.<>c__DisplayClass12_0.<TryExecuteDeclaringReferenceActions>g__executeExecutableCodeActions|3()
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.TryExecuteDeclaringReferenceActions(SyntaxReference decl, Int32 declarationIndex, SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, AnalysisState analysisState, GroupedAnalyzerActions coreActions, GroupedAnalyzerActions additionalPerSymbolActions, Boolean shouldExecuteSyntaxNodeActions, Boolean shouldExecuteOperationActions, Boolean shouldExecuteCodeBlockActions, Boolean shouldExecuteOperationBlockActions, Boolean isInGeneratedCode, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.TryExecuteDeclaringReferenceActions(SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, AnalysisState analysisState, Boolean isGeneratedCodeSymbol, IGroupedAnalyzerActions additionalPerSymbolActions, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<TryProcessSymbolDeclaredAsync>d__132.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<TryProcessEventCoreAsync>d__131.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<ProcessEventAsync>d__129.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<ProcessCompilationEventsCoreAsync>d__128.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<>c__DisplayClass127_0.<<ProcessCompilationEventsAsync>b__2>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<ProcessCompilationEventsAsync>d__127.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<ExecutePrimaryAnalysisTaskAsync>d__96.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<AttachQueueAndProcessAllEventsAsync>d__94.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<ComputeAnalyzerDiagnosticsCoreAsync>d__72.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<>c__DisplayClass67_1.<<ComputeAnalyzerDiagnosticsAsync>b__1>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<ComputeAnalyzerDiagnosticsAsync>d__67.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<ComputeAnalyzerSemanticDiagnosticsAsync>d__66.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<>c__DisplayClass66_0.<<ComputeAnalyzerSemanticDiagnosticsAsync>g__processPartialSymbolLocationsAsync|0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<ComputeAnalyzerSemanticDiagnosticsAsync>d__66.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<GetAnalysisResultCoreAsync>d__64.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Diagnostics.Extensions.<GetAnalysisResultAsync>d__9.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Diagnostics.Extensions.<GetAnalysisResultAsync>d__8.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.<AnalyzeAsync>d__9.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.<GetDiagnosticsAsync>d__8.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.<>c__DisplayClass3_0.<<CalculateDiagnosticsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__13`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

```

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #59988
Fixes [AB#1654606](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1654606)

Do not mark declaration/symbol/event as fully processed when the state is still being processed by another thread. This can happen in rare cases when multiple threads are trying to analyze the same symbol/syntax/operation, such that one thread has finished all the analyzer callbacks, but before this thread attempts to mark the state as complete, second thread starts processing the same symbol/syntax/operation and sets the StateKind to 'InProcess' for the same state object. With this PR, we do not mark the state as complete for such cases and instead let subsequent thread attempt to mark completion.

### CODE REVIEW

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs [hunk 1]
```diff
@@ -319,6 +319,24 @@ private static void FreeState_NoLock<TAnalyzerStateData>(TAnalyzerStateData? sta
...
+                    // 'InProcess' for the same state object. If we free the state here in the first thread,
+                    // then this can lead to data corruption/exceptions in the second thread.
+                    // For example, see https://github.com/dotnet/roslyn/issues/59988.
+                    //
+                    // CONSIDER: Note that our current approach of not freeing the state for StateKind.InProcess
+                    // leads to a leak, as we will never return this state object to the pool. However, this should
+                    // happen in extremely rare cases as described above, so it should be fine. In future, if we do
+                    // see negative performance impact from this leak, we can do a more complex state tracking and
+                    // ensure that we free this state object and return it to the pool once the StateKind is reset
+                    // to StateKind.ReadyToProcess state.
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs:336]: personally, this seems bad to me.  i don't like that such a core part of our system is fundamentally 'racey', with teh choices being: "corruption" or "leaking".  

Can we not just take locks and transition these states cleanly through whatever state machine edges they need to travel?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs [hunk 2]
```diff
@@ -319,6 +319,24 @@ private static void FreeState_NoLock<TAnalyzerStateData>(TAnalyzerStateData? sta
...
+                    if (state.StateKind == StateKind.InProcess)
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs:337]: fundamentally, i'm not even sure how i can view this code as safe.  if we do have multi-threaded manipulation then we could read .StateKind, see htat it's not .InProcess, and then an instant later have another thread change that value right?  leading to the same problem as before.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs (hunk 1 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs:336]: We have all the locking/synchronization in place to ensure that only one thread will ever have access to this state object during analysis to mutate the state and perform analyzer callbacks. Specifically, `StateKind.InProcess` indicates this. However, the `Free` operation on the state object was not thread safe and also mutates the state. I thought a more simpler, defensive approach with a small leak will suffice in this case as it should be rare. But I have now switched over to more hardened approach without a leak, where we mark the object for a pending free operation in this scenario, to be executed later.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs (hunk 2 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs:337]: Reverted now.

**Comment by mavasani** [comment]
@dotnet/roslyn-compiler for reviews

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.AnalyzerStateData.cs [hunk 3]
```diff
@@ -52,13 +64,49 @@ public virtual void SetStateKind(StateKind stateKind)
...
+                    // but before this thread marks the state as complete and invokes this Free call,
+                    // second thread starts processing the same symbol/syntax/operation and sets the StateKind to
+                    // 'InProcess' for the same state object. If we free the state here in the first thread,
+                    // then this can lead to data corruption/exceptions in the second thread.
+                    // For example, see https://github.com/dotnet/roslyn/issues/59988.
+                    _callbackForDeferredFreeOperation = () => FreeAndReturnToPoolCore(state, pool);
+                }
+                else
+                {
+                    FreeAndReturnToPoolCore(state, pool);
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.AnalyzerStateData.cs:101]: >FreeAndReturnToPoolCore(state, pool); [](http://example.com/codeflow?start=20&length=37)

Is there a guarantee that the other thread doesn't start processing the same symbol/syntax/operation once we get here?

In general, it feels like there is something wrong with the whole idea of sharing the same object between two different threads and the state moving "backwards" by one of them. Using an object pool for concurrently accessed objects also feels very suspicious.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 2)

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.AnalyzerStateData.cs (hunk 3 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.AnalyzerStateData.cs:101]: > Is there a guarantee that the other thread doesn't start processing the same symbol/syntax/operation once we get here

Yes. State object is guaranteed to have `StateKind.InProcess` when it is attempting to run analysis or access any properties off it.

> In general, it feels like there is something wrong with the whole idea of sharing the same object between two different threads and the state moving "backwards" by one of them

The state object can be fetched/read/written by only one thread at a time when attempting to execute analysis. The only exception is the bug being fixed here, i.e. when one of the threads has completed all analysis corresponding to the symbol/syntax/operation for the state and it needs to update the corresponding state map and subsequently free the state: https://github.com/dotnet/roslyn/blob/86e06cace23209576e17cb362b2501593c76cbd3/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs#L272-L287

Above code removes the state from the declaration data map, so the state would no longer be retrievable by future attempts. Attempt to free the state and return to pool should only happen when no other thread has hold of the state, which is what the above `StateKind.InProcess` check is ensuring.

for the code being added here which sets the callback for deferred free operation when the analysis corresponding to the state object has completed on the current thread and it invokes Free, but some other thread

Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.AnalyzerStateData.cs]: We discussed offline and decided that for such cases where we attempt to mark completion of state on one thread, such that another thread is still processing the state, we not bail out upfront and neither free the state nor mark it complete. This ensures that another thread will eventually re-attempt to mark completion of the state, at which time we will free the state and successfully mark completion. I have pushed a commit for this approach.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs [hunk 4]
```diff
@@ -375,9 +397,9 @@ public bool TryStartProcessingEvent(CompilationEvent compilationEvent, [NotNullW
                 return TryStartProcessingEntity(compilationEvent, _pendingEvents, _analyzerStateDataPool, out state);
             }
 
-            public void MarkEventComplete(CompilationEvent compilationEvent)
+            public bool TryMarkEventComplete(CompilationEvent compilationEvent)
```
Comment (mavasani) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs:400]: I converted all the methods that mark completion of events/symbols/declaration/syntax from `void MarkXXXComplete(...)` to `bool TryMarkXXXComplete(...)`

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs [hunk 5]
```diff
@@ -397,23 +397,21 @@ public void ExecuteSuppressionAction(DiagnosticSuppressor suppressor, ImmutableA
         {
             Debug.Assert(compilationEvent is CompilationStartedEvent || compilationEvent is CompilationCompletedEvent);
 
-            AnalyzerStateData? analyzerState = null;
-
-            try
+            if (TryStartProcessingEvent(compilationEvent, analyzer, analysisScope, analysisState, out var analyzerState))
```
Comment (mavasani) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs:400]: @AlekseyTs State machine transitions should now be very clear:
1. We attempt to `TryStartProcessingEvent` to get hold of analyzer state, with `StateKind.InProcess`.
2. If we succeed, then we attempt to execute relevant analyzer callbacks for the compilation event
3. After executing callbacks, we transition the state to `StateKind.ReadyToProcess` state
4. Finally, we attempt to mark completion of the event for the analyzer and try to transition to `StateKind.FullyProcessed` and return true only if we succeed.
5. If we fail at Step 1, which happens when either another thread is executing steps 2-4 OR analyzer state has already completed and transitioned to `FullyProcessed`, we don't attempt to execute analysis but instead return `IsEventComplete` to handle the latter case.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.AnalyzerStateData.cs [hunk 6]
```diff
@@ -56,6 +57,7 @@ public void ResetToReadyState()
 
             public virtual void Free()
             {
+                Debug.Assert(StateKind != StateKind.InProcess);
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.AnalyzerStateData.cs:60]: >StateKind != StateKind.InProcess [](http://example.com/codeflow?start=29&length=32)

Does it make sense to make this assert stronger and check that we are in ```FullyProcessed``` state?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs [hunk 7]
```diff
@@ -157,12 +157,17 @@ public bool HasPendingSymbolAnalysis(ISymbol symbol)
             {
                 if (pendingEntities.TryGetValue(analysisEntity, out var state))
                 {
+                    if (state != null && state.StateKind == StateKind.InProcess)
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs:160]: >if (state != null && state.StateKind == StateKind.InProcess) [](http://example.com/codeflow?start=20&length=60)

Are we always under lock here? Can other thread change state to ```InProcess``` before we complete operations below?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.cs [hunk 8]
```diff
@@ -771,52 +783,60 @@ public void MarkDeclarationsComplete(ISymbol symbol, IEnumerable<DiagnosticAnaly
...
             {
-                return;
+                return true;
             }
 
+            var success = true;
             foreach (var analyzer in analysisScope.Analyzers)
             {
-                if (!processedAnalyzers.Contains(analyzer))
+                if (!processedAnalyzers.Contains(analyzer) &&
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.cs:832]: >processedAnalyzers [](http://example.com/codeflow?start=21&length=18)

Here and in several other places we are using information on the side that tracks whether all things are marked as complete and is used to make various shortcuts. When we adjust that side information, do we take into account the fact that some of the states were not complete?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs [hunk 9]
```diff
@@ -397,23 +397,21 @@ public void ExecuteSuppressionAction(DiagnosticSuppressor suppressor, ImmutableA
...
-                if (TryStartProcessingEvent(compilationEvent, analyzer, analysisScope, analysisState, out analyzerState))
+                try
                 {
                     ExecuteCompilationActionsCore(compilationActions, analyzer, analyzerState);
-                    analysisState?.MarkEventComplete(compilationEvent, analyzer);
-                    return true;
+                }
+                finally
+                {
+                    analyzerState?.ResetToReadyState();
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs:408]: >analyzerState?.ResetToReadyState(); [](http://example.com/codeflow?start=20&length=35)

Is the following going to decrease/eliminate the chances of us failing to complete the event because another thread "hijacked" the state after this line?

We could introduce another state, called "AttemptingToComplete". Before executing ```TryMarkEventComplete```, we don't reset the state to "ReadyToProcess", instead we change it to ```AttemptingToComplete```. And only, if ```TryMarkEventComplete``` failed, we reset to "ReadyToProcess".

I am not sure if this is going to introduce too much complexity, or, perhaps, a race for completion between different threads.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs [hunk 10]
```diff
@@ -397,23 +397,21 @@ public void ExecuteSuppressionAction(DiagnosticSuppressor suppressor, ImmutableA
...
                 }
 
-                return IsEventComplete(compilationEvent, analyzer, analysisState);
-            }
-            finally
-            {
-                analyzerState?.ResetToReadyState();
+                return TryMarkEventComplete(compilationEvent, analyzer, analysisState);
```
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs:411]: It looks like we were protected against that before because we were not resetting to ```ReadyToProcess``` before attempting to complete.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 7).

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.AnalyzerStateData.cs (hunk 6 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.AnalyzerStateData.cs:60]: Actually the `StateKind` would be `ReadyToBeProcessed` here, I'll change the assert here accordingly. `StateKind.FullyProcessed` is only used for singletons : https://sourceroslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalysisState.StateKind.cs,2777a03ff8c49043,references to reduce allocations. When transitioning analysis to complete state, we use the below code pattern: https://github.com/dotnet/roslyn/blob/440b6fc370f0ddcea68b445e183f1383c0d1bc6e/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs#L281-L286

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs (hunk 7 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs:160]: Yes, we are always under lock here. Changing the state to `InProcess` can only happen under lock, so it cannot happen simultaneously here.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.cs (hunk 8 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.cs:832]: Yes, this code path is only meant to handle analyzers that were completely unprocessed or skipped - for example `analysisScope` requested might only contain subset of analyzers, and rest can be skipped: https://sourceroslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerDriver.cs,747

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs (hunk 9 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs:408]: > Is the following going to decrease/eliminate the chances of us failing to complete the event because another thread "hijacked" the state after this line?

Yes, this definitely can happen.

> I am not sure if this is going to introduce too much complexity, or, perhaps, a race for completion between different threads.

That is my primary concern. Let me open a separate tracking issue to try the new `StateKind` approch as a follow-up.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs (hunk 10 above)
[the remark this answers is not in the document]
Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs:411]: > Is there a guarantee that there is no race between two different threads reaching this point at the same time and trying to complete the same thing at the same time. Could we, perhaps, "free" the same thing twice?

Attempt to mark completion + freeing always happens under the lock, so we are protected.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs (hunk 7 above)
[the remark this answers is not in the document]
Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs:160]: > we should consider using Volatile.Read for all reads of the StateKind

`StateKind` is an enum, so `Volatile.Read(ref _stateKind)` doesn't compile.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs (hunk 9 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs:408]: Filed https://github.com/dotnet/roslyn/issues/65330

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs (hunk 7 above)
[the remark this answers is not in the document]
Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs:160]: Would you be fine if we do any such change as part of the follow-up work tracked by https://github.com/dotnet/roslyn/issues/65330?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.AnalyzerStateData.cs [hunk 11]
```diff
@@ -56,7 +57,7 @@ public void ResetToReadyState()
 
             public virtual void Free()
             {
-                this.StateKind = StateKind.ReadyToProcess;
+                Debug.Assert(StateKind == StateKind.ReadyToProcess);
```
Comment (mavasani) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.AnalyzerStateData.cs:60]: Note that this will change to `Debug.Assert(StateKind == StateKind.AttemptingToComplete);` after we implement https://github.com/dotnet/roslyn/issues/65330

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs (hunk 7 above)
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs:160]: As we discussed offline, let's use ```int``` as type of the field.

**Comment by mavasani** [comment]
> > ```
> >                 ClearCachedAnalysisDataIfAnalyzed(symbol, declarationIndex, analysisState);
> > ```
> 
> Should we be taking this code path if we "failed" in the loop above?
> 
> In reply to: [1309059500](https://github.com/dotnet/roslyn/pull/65083#issuecomment-1309059500)
> 
> Refers to: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs:2665 in [0f841ca](https://github.com/dotnet/roslyn/commit/0f841ca1626472cf4975ad1e19474a9a069a9d27). [](commit_id = [0f841ca](https://github.com/dotnet/roslyn/commit/0f841ca1626472cf4975ad1e19474a9a069a9d27), deletion_comment = False)

Thanks, I missed this comment. Updated to also check `success` now.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs (hunk 9 above)
Comment (AlekseyTs) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs:408]: > Let me open a separate tracking issue to try the new ```StateKind``` approch as a follow-up.

Sounds good

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 9)

**Comment by mavasani** [comment]
Thanks @AlekseyTs

@dotnet/roslyn-compiler for second review.

**Comment by mavasani** [comment]
@dotnet/roslyn-compiler Can I please get a second review?
This change is a candidate for 17.4 servicing, and we want to give it enough bake time in 17.5 preview dogfood builds before taking it for 17.4 servicing. Thanks!

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs (hunk 10 above)
Comment (cston) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs:411]: >return TryMarkEventComplete(compilationEvent, analyzer, analysisState); [](http://example.com/codeflow?start=16&length=71)

Is the change to have `MarkEventComplete()` return a `bool` and return that here, just an optimization over calling `return IsEventComplete();` in all cases? (I think that is a reasonable change, but just confirming that I understand this.)

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs (hunk 7 above)
Comment (cston) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs:160]: >state.StateKind == StateKind.InProcess [](http://example.com/codeflow?start=41&length=38)

When will this be true? Doesn't the change to `AnalyzerExecutor.TryExecuteCompilationActions()` ensure that only the current thread is processing `analysisEntity`?

**Comment by cston** [comment]
> Do mark declaration/symbol/event as fully processed when the state is still being processed by another thread.

Should that be "Do _not_ mark ... "?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs (hunk 10 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs:411]: Yes, that is correct. We could split this into two calls, but that is unnecessary.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs (hunk 7 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalysisState.PerAnalyzerState.cs:160]: There is still a small window between when we reset the analyzer state to ready after executing the actions AND before attempt to marking completion when another thread might invoke `TryExecuteCompilationActions` and get hold of the analyzer state and start processing it. The second thread will not make any callbacks as prior thread made all callbacks, but with this change we now ensure that the second thread marks completion instead of the first one doing it while second thread is executing and has hold of the state object.

**Comment by mavasani** [comment]
> > Do mark declaration/symbol/event as fully processed when the state is still being processed by another thread.
> 
> Should that be "Do _not_ mark ... "?

Yes, updated the PR description. Thanks.

**Review by cston — APPROVED** [review]
