### PR TITLE
Isolate tests

### LINKED ISSUE #25119: xUnit crash with -1073740791
EditorServices2 crashed with `-1073740791` in a test run. My searching indicates that this code is actually C0000409, which is a stack buffer overflow code. Output:

```
00:11:19 Errors Roslyn.Services.Editor2.UnitTests.dll: 
00:11:19 
00:11:19 Command: C:\Users\dotnet-bot\.nuget\packages\xunit.runner.console\2.3.1\tools\net452\xunit.console.x86.exe "D:\j\workspace\windows_relea---fcb95091\Binaries\Release\UnitTests\EditorServicesTest2\Roslyn.Services.Editor2.UnitTests.dll"  -xml "D:\j\workspace\windows_relea---fcb95091\Binaries\Release\UnitTests\EditorServicesTest2\xUnitResults\Roslyn.Services.Editor2.UnitTests.dll.xml" -noshadow -verbose
00:11:19 xUnit output log: D:\j\workspace\windows_relea---fcb95091\Binaries\Release\UnitTests\EditorServicesTest2\xUnitResults\Roslyn.Services.Editor2.UnitTests.dll.out.log
00:11:19 
xunit produced no error output but had exit code -1073740791
```
Log File: [Roslyn.Services.Editor2.UnitTests.dll.out.log.txt](https://github.com/dotnet/roslyn/files/1768403/Roslyn.Services.Editor2.UnitTests.dll.out.log.txt)

### LINKED ISSUE #25315: InteractivePasteCommandhandlerTests.PasteCommandWithInteractiveFormat failure
`InteractivePasteCommandhandlerTests.PasteCommandWithInteractiveFormat` failed in the signed build, https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1450639&_a=summary&tab=details. Unfortunately test results for this test seem to be missing (though the failure is in the console output and failed the build), so I don't have a stack trace. Possibly related to https://github.com/dotnet/roslyn/issues/20840.

### LINKED ISSUE #25560: Block ExportProvider pollution in tests
Currently many tests share instances of `ExportProvider` for efficiency purposes. This mutable type ends up containing mutable objects, and sharing across tests can cause unexpected cross-test behavior changes.

The caching strategy can be improved by caching the `IExportProviderFactory` used to create the `ExportProvider`. This immutable object caches the expensive operations required to compose the MEF container, so the lightweight `ExportProvider` instances only need to invoke the constructors for contained types.

The overall approach in testing should achieve the following:

1. Rules for `ExportProvider` in testing
    * During the execution of any given test, at most one `ExportProvider` will be created
    * An `ExportProvider` created during a test must be disposed either within the test or as part of the teardown for the test
2. Rules for exported values in testing
    * An object normally obtained from the `ExportProvider` must only be obtained through the export provider. If a substitution object is required (e.g. a mock with specific behavior), the mock must be placed in the `ExportProvider` and then obtained from it. Constructors for MEF-exported types should have the following attribute on their constructor as a compile-time guarantee:

        ```csharp
        [Obsolete(
            "This exported object must be obtained through the MEF export provider.",
            error: true)]
        ```

3. Additional constraints

    * Asynchronous (background) operations should be completed during the lifetime of each test, and joined to the test so failures are propagated to the test status. Each test should cancel unnecessary operations to avoid prolonging test runs.

### PR DESCRIPTION
**Pull request by sharwell**
This change implements MEF container isolation during tests.

Closes #25560 
Fixes #25119
Fixes #25315

It is further expected to close a number of open flaky test issues where xunit was crashing in a `FailFast`.

This is _almost_ strictly a test change. The only change that could impact a user is if code with IVTs to Roslyn uses `new AsynchronousOperationListenerProvider()`, as opposed to going to the MEF container.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
1. is this ready for review?
2. is there any writup that explains the new system and how new test fixtures should be created?  
3. Does this affect how people write features?

**Comment by sharwell** [comment]
> is this ready for review?

Yes, ready and working aside from #25691 

> is there any writup that explains the new system and how new test fixtures should be created?

It's not much different from the last one, and if you break one of the new rules it will typically tell you what the specific problem was. Most of the changes to how tests are created are listed in #25560.

> Does this affect how people write features?

It shouldn't.

File: src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs [hunk 1]
```diff
@@ -2182,7 +2182,7 @@ void goo()
                 WpfTestCase.RequireWpfFact("Creates an IWpfTextView explicitly with an unrelated buffer");
                 using (var disposableView = workspace.ExportProvider.GetExportedValue<ITextEditorFactoryService>().CreateDisposableTextView(extraBuffer))
                 {
-                    var listenerProvider = new AsynchronousOperationListenerProvider();
+                    var listenerProvider = workspace.ExportProvider.GetExportedValue<IAsynchronousOperationListenerProvider>();
```
Comment (heejaechang) [inline src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs]: tagging @dotnet/roslyn-ide @jinujoseph @DustinCampbell @Pilchie @jasonmalinowski 

I think if we go this route, we should change our code to use [Import] property/fields rather than doing [ImportingConstructor]

we choose ImportingConstructor at the time with completely opposite mindset. we wanted to give in Mock to dependencies. and make test more API level unit tests.

we start to move to more behavior test kind of unit tests. start to use MEF to provide dependencies (since our dependency was too complex, almost impossible to provide all those mocks at right layer).

now with this change, where we use MEF provider itself as isolation point, I think ImportingConstructor actually work against what we want. since user can provide one at the constructor, and deep down other service getting same dependency from MEF export and messing up everything.

we should ban using ImportingConstructor from our code, and use [Import] rather to force, all dependencies are coming from MEF export.

Comment (sharwell) [reply src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs]: > rather than doing [ImportingConstructor]

We need to keep `[ImportingConstructor]` so we can block direct construction of the object (otherwise the default constructor would be public and accessible). The placement of dependencies as parameters vs. properties at that point makes little difference.

Comment (heejaechang) [reply src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs]: hmm.. I dont understand what you mean by blocking direct construction? you can give in null to all dependencies. or mock to it. isn't one of point of what you are doing here is to make sure all dependencies get same services rather than different one?

why use code review to make sure it gets same dependency when you can make sure in does by the system?

having [Import] as same as I create object giving null to all dependencies?

Comment (sharwell) [reply src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs]: The goal of the change is for the following to be a *compilation error*:

```csharp
new AsynchronousOperationListenerProvider(...)
```

Alternatives to what I have implemented here are fine as long as that characteristic is preserved.

File: src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionCommandHandlerTests.vb [hunk 2]
```diff
@@ -88,7 +88,7 @@ class C
     </Project>
 </Workspace>
 
-            Using workspace = TestWorkspace.Create(definition, exportProvider:=GoToTestHelpers.ExportProvider)
+            Using workspace = TestWorkspace.Create(definition, exportProvider:=GoToTestHelpers.ExportProviderFactory.CreateExportProvider())
                 Dim cursorDocument = workspace.Documents.First(Function(d) d.CursorPosition.HasValue)
                 Dim cursorPosition = cursorDocument.CursorPosition.Value
```
Comment (heejaechang) [inline src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionCommandHandlerTests.vb]: this will be the example. here it uses mock IDocumentNavigationService and IStreamFindUsagespresenter mock. 

but one of them is given as dependency and the other uses MEF. one is probably given as MEF since it is not exposed through constructor of CSharpGotoDefinitionService but want to easily inject that dependency under several layers.

and the other is happen to be exposed through CSharpGoToDefinitionService. unless I know exactly how these dependencies are used, I can't be sure whether IStreamingFindUsagesPresernter I gave in here is the one used internally.

removing all possibility to provide dependency except through MEF removes your concern that some tests uses 2 different instances of same service (one from constructor and one from MEF) and making test flaky.

especially, when one can add dependency through MEF to new service without realizing one had to change test like this as well since one just introduced possiblity of tests having 2 different instance of same service.

Comment (heejaechang) [reply src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionCommandHandlerTests.vb]: by the way, I just searched Mock in roslyn solution. there are quite more mocks you used in our tests. I didn't even search for Testxxx. since I believe we used Mockxxx or Testxxx for our mock dependencies for unit tests.

File: src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs (hunk 1 above)
Comment (heejaechang) [reply src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs]: that's interesting. so planning to mark all importing constructor as obsolete? that should work as well. 

so, when someone wants to test service itself like 
http://source.roslyn.io/#Roslyn.Services.Editor2.UnitTests/GoToDefinition/GoToDefinitionCommandHandlerTests.vb,103

they should get CSharpGotoDefinitionService from MEF from the beginning? ya. that should work as well rather than changing all code to [Import] from [ImportingConstructor]

so I guess that work is not done yet? I see only Async Listener Provider is marked obsolete. that can fix the problem where 2 different instance of IAsynchornounsListenerProvider is used. one directly given and one from MEF. but what about all other services?

Comment (sharwell) [reply src/EditorFeatures/CSharpTest/Classification/SemanticClassifierTests.cs]: Correct, I have only made the change for two services to date (one in #25558, and one here).

File: src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionCommandHandlerTests.vb (hunk 2 above)
Comment (sharwell) [reply src/EditorFeatures/Test2/GoToDefinition/GoToDefinitionCommandHandlerTests.vb]: Correct, fixing the mocks is left as a follow-up item. :smile:

File: src/Workspaces/CoreTestUtilities/ExportProviderCache.cs [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+using System;
+using System.Collections.Generic;
+using System.Reflection;
+using System.Threading.Tasks;
+using Microsoft.VisualStudio.Composition;
+using Roslyn.Utilities;
+
+namespace Microsoft.CodeAnalysis.Test.Utilities
+{
+    public static class ExportProviderCache
```
Comment (jasonmalinowski) [inline src/Workspaces/CoreTestUtilities/ExportProviderCache.cs]: Can we move the non-cache methods to some other type? It's very confusing as these methods don't have anything to do with caching, which makes consumption confusing later.

File: src/Workspaces/CoreTestUtilities/UseExportProviderAttribute.cs [hunk 4]
```diff
@@ -94,6 +99,26 @@ private static MefHostServices CreateMefHostServices(IEnumerable<Assembly> assem
...
         }
 
+        private HostServices GetOrCreateRemoteHostServices()
+        {
+            if (_remoteHostServices != null)
+            {
+                return _remoteHostServices;
+            }
+
+            lock (_remoteHostServicesCreationLock)
```
Comment (jasonmalinowski) [inline src/Workspaces/CoreTestUtilities/UseExportProviderAttribute.cs]: Should we just be using Lazy here?

File: src/Workspaces/Core/Portable/Shared/TestHooks/IAsynchronousOperationListenerProvider.cs [hunk 5]
```diff
@@ -68,6 +68,7 @@ public static void Enable(bool enable)
             s_enabled = enable;
         }
 
+        [Obsolete("This exported object must be obtained through the MEF export provider.", error: true)]
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Shared/TestHooks/IAsynchronousOperationListenerProvider.cs]: Love this trick.

File: src/Workspaces/CoreTestUtilities/WorkspacesTestUtilities.csproj [hunk 6]
```diff
@@ -18,6 +18,7 @@
     <ProjectReference Include="..\..\Compilers\CSharp\Portable\CSharpCodeAnalysis.csproj" />
     <ProjectReference Include="..\..\Compilers\Test\Resources\Core\CompilerTestResources.csproj" />
     <ProjectReference Include="..\..\Compilers\VisualBasic\Portable\BasicCodeAnalysis.vbproj" />
+    <ProjectReference Include="..\..\EditorFeatures\Core\EditorFeatures.csproj" />
```
Comment (jasonmalinowski) [inline src/Workspaces/CoreTestUtilities/WorkspacesTestUtilities.csproj]: This feels like a layering violation here: can we have the IForegroundNotificationService somehow add itself to a list of "things that need cleanup" for the UseExportProviderAttribute?

File: src/EditorFeatures/CSharpTest/EncapsulateField/EncapsulateFieldTestState.cs [hunk 7]
```diff
@@ -27,11 +27,12 @@ internal class EncapsulateFieldTestState : IDisposable
...
         public string NotificationMessage { get; private set; }
 
-        private static readonly ComposableCatalog s_composableCatalog =
-            TestExportProvider.MinimumCatalogWithCSharpAndVisualBasic.WithParts(
-            typeof(CSharpEncapsulateFieldService),
-            typeof(EditorNotificationServiceFactory),
-            typeof(DefaultDocumentSupportsFeatureService));
+        private static readonly IExportProviderFactory s_exportProviderFactory =
+            ExportProviderCache.CreateExportProviderFactory(
+                TestExportProvider.MinimumCatalogWithCSharpAndVisualBasic.WithParts(
```
Comment (jasonmalinowski) [inline src/EditorFeatures/CSharpTest/EncapsulateField/EncapsulateFieldTestState.cs]: Naming here is again throwing me for a loop: it's odd that the creation of a _factory_ uses things from a _provider_. Should this really be TestCatalogs.MinmumCatalogWithCSharpAndVisualBasic?

I get the naming isn't new here, but since we're trying to make this correct, this would help ensure the concepts are clear for the future. Is that a big change?

File: src/EditorFeatures/TestUtilities/TestExportProvider.cs [hunk 8]
```diff
@@ -111,9 +118,9 @@ private static Type[] GetNeutralAndCSharpAndVisualBasicTypes()
         /// Create fresh ExportProvider that doesn't share anything with others. Tests can use this
```
Comment (jasonmalinowski) [inline src/EditorFeatures/TestUtilities/TestExportProvider.cs]: Comment now stale.

File: src/Workspaces/CoreTestUtilities/ExportProviderCache.cs [hunk 9]
```diff
@@ -52,6 +72,22 @@ public static ComposableCatalog CreateAssemblyCatalog(Assembly assembly)
 
         public static ComposableCatalog CreateAssemblyCatalog(IEnumerable<Assembly> assemblies, Resolver resolver = null)
         {
+            if (assemblies is ImmutableArray<Assembly> assembliesArray)
+            {
+                if (s_defaultHostCatalog != null && assembliesArray == MefHostServices.DefaultAssemblies)
+                {
+                    return s_defaultHostCatalog;
+                }
+                else if (s_desktopHostCatalog != null && assembliesArray == DesktopMefHostServices.DefaultAssemblies)
```
Comment (jasonmalinowski) [inline src/Workspaces/CoreTestUtilities/ExportProviderCache.cs]: Oof this is magic: so the static initializer calls the method that then uses the field inside of it? That seems like it's ripe for breaking.

File: src/Workspaces/CoreTestUtilities/ExportProviderCache.cs [hunk 10]
```diff
@@ -103,45 +139,67 @@ public static ComposableCatalog WithPart(this ComposableCatalog catalog, Type t)
...
                 }
 
-                expected = exportProviderFactory.CreateExportProvider();
-                expected = Interlocked.CompareExchange(ref _expectedProviderForCatalog, expected, null) ?? expected;
-                Interlocked.CompareExchange(ref _currentExportProvider, expected, null);
-            }
+                var expectedCatalog = Interlocked.CompareExchange(ref _expectedCatalog, _catalog, null) ?? _catalog;
+                if (expectedCatalog != _catalog)
+                {
+                    throw new InvalidOperationException($"Only one {nameof(ExportProvider)} can be created for a single test.");
```
Comment (jasonmalinowski) [inline src/Workspaces/CoreTestUtilities/ExportProviderCache.cs]: I admit I'm still not getting the one-export-provider restriction. If it's for cleanup, why can't we just clean all of the ones that were made up? It seems like it'd simplify the code.

I can imagine you had cases through this work where we were creating one that was previously a static and by re-creating multiple instances you caused a bug because state that was a singleton in a test now isn't. But it seems that was a point-in-time offense, where now just allowing multiple to be created and cleaning up all of them would  be easier code to maintain going forward.

Put another way: this rule might have been great for your work to do this, but seems like it needs justification (and commenting) if it's going to stay.

File: src/Workspaces/CoreTestUtilities/ExportProviderCache.cs [hunk 11]
```diff
@@ -103,45 +139,67 @@ public static ComposableCatalog WithPart(this ComposableCatalog catalog, Type t)
...
-            var exportProvider = _currentExportProvider;
-            if (exportProvider != expected)
-            {
-                throw new InvalidOperationException($"Only one {nameof(ExportProvider)} can be created in the context of a single test.");
-            }
+                var expected = _expectedProviderForCatalog;
+                if (expected == null)
+                {
+                    expected = _exportProviderFactory.CreateExportProvider();
+                    expected = Interlocked.CompareExchange(ref _expectedProviderForCatalog, expected, null) ?? expected;
```
Comment (jasonmalinowski) [inline src/Workspaces/CoreTestUtilities/ExportProviderCache.cs]: Why the Interlocked* here? Is this trying to support a single test consuming multiple threads? It's clearly not multiple tests running in parallel (since this mechanism of using statics wouldn't work)...

File: src/Workspaces/CSharpTest/CSharpServicesTest.csproj [hunk 12]
```diff
@@ -18,6 +18,8 @@
     <ProjectReference Include="..\..\Compilers\Core\Portable\CodeAnalysis.csproj" />
     <ProjectReference Include="..\..\Compilers\CSharp\Portable\CSharpCodeAnalysis.csproj" />
     <ProjectReference Include="..\..\Compilers\Test\Resources\Core\CompilerTestResources.csproj" />
+    <ProjectReference Include="..\..\EditorFeatures\Core\EditorFeatures.csproj" />
```
Comment (jasonmalinowski) [inline src/Workspaces/CSharpTest/CSharpServicesTest.csproj]: This is a layering violation I believe.

**Comment by jasonmalinowski** [comment]
And I should clarify: the ProjectReference concerns I wouldn't consider blocking for this PR, but if they get cleaned up while trying to simplify the attribute and ExportProviderCache, I won't complain...

File: src/EditorFeatures/TestUtilities/Workspaces/TestWorkspaceFixture.cs [hunk 13]
```diff
@@ -62,7 +61,20 @@ private static void UpdateText(ITextBuffer textBuffer, string text)
             }
         }
 
-        public void CloseTextView()
+        public void DisposeAfterTest()
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/EditorFeatures/TestUtilities/Workspaces/TestWorkspaceFixture.cs]: :arrow_right: No purpose. Filed #25804 to address this in a follow-up PR.

File: src/VisualStudio/CSharp/Test/CodeModel/AbstractFileCodeElementTests.cs [hunk 14]
```diff
@@ -14,16 +14,30 @@ namespace Microsoft.VisualStudio.LanguageServices.CSharp.UnitTests.CodeModel
...
+        public AbstractFileCodeElementTests(string contents)
+        {
+            _contents = contents;
+        }
+
+        public Tuple<TestWorkspace, FileCodeModel> WorkspaceAndCodeModel
+        {
+            get
+            {
+                return _workspaceAndCodeModel ?? (_workspaceAndCodeModel = CreateWorkspaceAndFileCodeModelAsync(_contents));
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/VisualStudio/CSharp/Test/CodeModel/AbstractFileCodeElementTests.cs]: Constructors are called before `UseExportProviderAttribute`, so eager initialization of these properties will throw an exception on the following line (the entire gap from the end of a test to the initialization of the export provider for the next test is attributed to the former test in the exception message):

https://github.com/dotnet/roslyn/blob/7eb0b2dd998713278e9f34110492901b3ac45eeb/src/Workspaces/CoreTestUtilities/UseExportProviderAttribute.cs#L74

File: src/EditorFeatures/TestUtilities/UseExportProviderAttribute.cs [hunk 15]
```diff
@@ -0,0 +1,123 @@
...
+using Microsoft.VisualStudio.Composition;
+using Roslyn.Test.Utilities;
+using Xunit.Sdk;
+
+namespace Microsoft.CodeAnalysis.Test.Utilities
+{
+    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
+    public sealed class UseExportProviderAttribute : BeforeAfterTestAttribute
+    {
+        private static readonly TimeSpan CleanupTimeout = TimeSpan.FromSeconds(15);
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/EditorFeatures/TestUtilities/UseExportProviderAttribute.cs]: ➡️ In the total absence of enforcement to date, we did a terrible job making sure tests clean up after themselves. I fixed enough cases in #25558 to make sure this change is viable, but I expect to see this condition hit in practice. Earlier portions of the cleanup code guarantee that all synchronous and immediately-queued cancellation requests are processed before reaching this condition. **All cases where this is hit are a bug.** However, the condition relaxes the overall acceptance criteria for this large change and allows us to pay off the debt over time.

File: src/Workspaces/CoreTestUtilities/ExportProviderCache.cs (hunk 9 above)
Comment (sharwell) [reply src/Workspaces/CoreTestUtilities/ExportProviderCache.cs]: ➡️ Refactoring to avoid magic

File: src/Workspaces/CoreTestUtilities/ExportProviderCache.cs (hunk 10 above)
Comment (sharwell) [reply src/Workspaces/CoreTestUtilities/ExportProviderCache.cs]: ➡️ Documenting code at the site where the exception is thrown

File: src/EditorFeatures/CSharpTest/EncapsulateField/EncapsulateFieldTestState.cs (hunk 7 above)
Comment (sharwell) [reply src/EditorFeatures/CSharpTest/EncapsulateField/EncapsulateFieldTestState.cs]: ➡️ We have a few inconsistencies in naming, but not enough to be a major concern for me at this time. We can file a follow-up issue if you want.

File: src/Workspaces/CoreTestUtilities/WorkspacesTestUtilities.csproj (hunk 6 above)
Comment (sharwell) [reply src/Workspaces/CoreTestUtilities/WorkspacesTestUtilities.csproj]: ➡️ Filed #25805. I have ideas for how to handle this but don't want to block on it due to scale of the work.

File: src/Workspaces/CoreTestUtilities/ExportProviderCache.cs (hunk 3 above)
Comment (sharwell) [reply src/Workspaces/CoreTestUtilities/ExportProviderCache.cs]: ➡️ This type acts as a cache which facilitates the efficient creation of `ExportProvider` instances, and caches various immutable data objects required for this construction. The name seems reasonable in this context. Normally this response would be 💭 , but given the size of this PR and the marginal benefit of refactoring here I would prefer to leave it.

File: src/EditorFeatures/Test/Utilities/EditorServicesUtil.cs [hunk 16]
```diff
@@ -10,17 +10,16 @@ namespace Microsoft.CodeAnalysis.Editor.UnitTests.Utilities
 {
     public static class EditorServicesUtil
     {
-        private static Lazy<ExportProvider> s_lazyExportProvider = new Lazy<ExportProvider>(CreateExportProvider);
+        private static Lazy<ComposableCatalog> s_composableCatalog = new Lazy<ComposableCatalog>(CreateComposableCatalog);
 
-        public static ExportProvider ExportProvider => s_lazyExportProvider.Value;
+        public static ExportProvider ExportProvider => ExportProviderCache.CreateExportProvider(s_composableCatalog.Value);
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/EditorFeatures/Test/Utilities/EditorServicesUtil.cs]: ➡️ Replied to this on another comment.

File: src/EditorFeatures/TestUtilities/DispatcherExtensions.cs [hunk 17]
```diff
@@ -30,5 +32,50 @@ public static void DoEvents(this Dispatcher dispatcher)
                 operation.Abort();
             }
         }
+
+        public static void DoEvents(this Dispatcher dispatcher, Func<CancellationToken, Task<bool>> continueUntilAsync = null, CancellationToken cancellationToken = default)
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/EditorFeatures/TestUtilities/DispatcherExtensions.cs]: ➡️ I believe this is unnecessarily complex, and have filed #25806 to correct this

File: src/EditorFeatures/TestUtilities/UseExportProviderAttribute.cs [hunk 18]
```diff
@@ -0,0 +1,123 @@
...
+
+        public override void After(MethodInfo methodUnderTest)
+        {
+            var exportProvider = ExportProviderCache.ExportProviderForCleanup;
+            try
+            {
+                var listenerProvider = exportProvider?.GetExportedValues<IAsynchronousOperationListenerProvider>().SingleOrDefault();
+                if (listenerProvider != null)
+                {
+                    var stopwatch = Stopwatch.StartNew();
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/EditorFeatures/TestUtilities/UseExportProviderAttribute.cs]: ➡️ I believe this is unnecessarily complex, and have filed #25806 to correct this

File: src/Workspaces/CSharpTest/CSharpServicesTest.csproj (hunk 12 above)
Comment (sharwell) [reply src/Workspaces/CSharpTest/CSharpServicesTest.csproj]: ➡️ This should be covered by #25805

**Comment by sharwell** [comment]
@jasonmalinowski I filed follow-up issues (with links to/from comments) and pushed a new commit with documentation and minor refactoring.

File: src/VisualStudio/CSharp/Test/CodeModel/AbstractFileCodeElementTests.cs (hunk 14 above)
[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/VisualStudio/CSharp/Test/CodeModel/AbstractFileCodeElementTests.cs]: > Constructors are called before UseExportProviderAttribute

Interesting. That feels like an xunit bug/gotcha -- is that something we can fix or at least make more diagnosable? Otherwise the obvious sequence of events of:

1. Write a new test from scratch, get error that you don't have attribute.
2. Apply attribute.
3. Run test.
4. Still broken.

seems quite undebuggable.

File: src/Workspaces/CoreTestUtilities/ExportProviderCache.cs (hunk 3 above)
Comment (jasonmalinowski) [reply src/Workspaces/CoreTestUtilities/ExportProviderCache.cs]: Some methods act as a cache: some methods aren't. I guess it was very confusing from my perspective because some methods are OK to call and some are evil to call in various places.

File: src/Workspaces/CoreTestUtilities/WorkspacesTestUtilities.csproj (hunk 6 above)
Comment (jasonmalinowski) [reply src/Workspaces/CoreTestUtilities/WorkspacesTestUtilities.csproj]: I guess I want to make sure that isn't viewed as optional, as this is opening a barn door and the animals are ready to escape.

File: src/Workspaces/CoreTestUtilities/ExportProviderCache.cs [hunk 19]
```diff
@@ -19,24 +19,24 @@ public static class ExportProviderCache
...
         // Cache the catalog and export provider factory for RoslynServices.RemoteHostAssemblies
         private static readonly ComposableCatalog s_remoteHostCatalog =
-            CreateAssemblyCatalog(RoslynServices.RemoteHostAssemblies);
+            CreateAssemblyCatalogNoCache(RoslynServices.RemoteHostAssemblies);
 
         private static readonly IExportProviderFactory s_remoteHostExportProviderFactory =
-            CreateExportProviderFactory(s_remoteHostCatalog);
+            CreateExportProviderFactoryNoCache(s_remoteHostCatalog);
 
         private static bool _enabled;
```
Comment (jasonmalinowski) [inline src/Workspaces/CoreTestUtilities/ExportProviderCache.cs]: Can't stick a comment on line 47 so doing it here: can we rename the setting property to something more like "Enabled_OnlyCallFromUseExportProvider"? I read the property as "enabled via the attribute" which implies there are *other* ways you can enable that are also valid. I didn't read it as "only use from there".

File: src/Workspaces/CoreTestUtilities/ExportProviderCache.cs [hunk 20]
```diff
@@ -88,6 +88,11 @@ public static ComposableCatalog CreateAssemblyCatalog(IEnumerable<Assembly> asse
                 }
             }
 
+            return CreateAssemblyCatalogNoCache(assemblies, resolver);
```
Comment (jasonmalinowski) [inline src/Workspaces/CoreTestUtilities/ExportProviderCache.cs]: You can remove the null checks now in CreateAssemblyCatalog, since they're always non-null since this method is always running after the static field initialization ran.

(I do like the cleanup though, thanks.)

Comment (jasonmalinowski) [reply src/Workspaces/CoreTestUtilities/ExportProviderCache.cs]: Also random thought/naming nit: should CreateAssemblyCatalogNoCache just be called "CreateAssemblyCatalog" and the caching one called GetOrCreate? I think that pattern is seen elsewhere and clarifies that "Create" doesn't always create something new.

File: src/Workspaces/CoreTestUtilities/ExportProviderCache.cs [hunk 21]
```diff
@@ -193,12 +202,37 @@ public ExportProvider CreateExportProvider()
...
+                    //
+                    // When this exception is thrown by a test, it typically means one of the following occurred:
+                    //
+                    // * A test failed to pass an ExportProvider via an optional argument to a method, resulting in the
+                    //   method attempting to create a default ExportProvider which did not match the one assigned to
+                    //   the test.
+                    // * A test attempted to perform multiple test sequences in the context of a single test method,
+                    //   rather than break up the test into distict tests for each case.
+                    // * A test referenced different predefined ExportProvider instances within the context of a test.
+                    //   Each test is expected to use the same ExportProvider throughout the test.
```
Comment (jasonmalinowski) [inline src/Workspaces/CoreTestUtilities/ExportProviderCache.cs]: This comment is great, and motivates the reasoning well. Thanks.

**Comment by sharwell** [comment]
@Pilchie Can I get ask mode approval for the production code changes in this PR? They are:

1. A few IVTs from production to local test assemblies (should not need special approval?)
2. A change to **IAsynchronousOperationListenerProvider.cs** here, which prevents outside code from using the constructor of `AsynchronousOperationListenerProvider`. We already verified it is not used in this manner downstream.

    https://github.com/sharwell/roslyn/commit/33a1a3bb928d4d56c3c7aec97ddfff00d5676094#diff-ce3a65ac7e5f22f0b2333d00b6c89556

3. The addition of one test hook method:

    https://github.com/dotnet/roslyn/blob/7e8391f8aff293303e8ce56a403892e2f1189de1/src/Workspaces/Core/Desktop/Workspace/Host/Mef/DesktopMefHostServices.cs#L25-L28

**Comment by Pilchie** [comment]
Yes, I approve those changes.

File: src/VisualStudio/CSharp/Test/CodeModel/AbstractFileCodeElementTests.cs (hunk 14 above)
[the remark this answers is not in the document]
Comment (sharwell) [reply src/VisualStudio/CSharp/Test/CodeModel/AbstractFileCodeElementTests.cs]: ➡️ Extracted a method which throws the `InvalidOperationException`, and added a comment to help users who hit it.

File: src/Workspaces/CoreTestUtilities/ExportProviderCache.cs (hunk 19 above)
Comment (sharwell) [reply src/Workspaces/CoreTestUtilities/ExportProviderCache.cs]: ➡️ Name is improved now

File: src/Workspaces/CoreTestUtilities/ExportProviderCache.cs (hunk 20 above)
Comment (sharwell) [reply src/Workspaces/CoreTestUtilities/ExportProviderCache.cs]: ➡️ Modified to use `Create` and `GetOrCreate` consistently aside from the remaining issue in #25863

**Comment by sharwell** [comment]
Fun, so error code COR_E_EXECUTIONENGINE is a new one for me. 😆

**Comment by sharwell** [comment]
@Pilchie There is one more change to approve in commit a4eb40996b456c30977e6b7291e7e1fc52a750b6. I kept hitting cases where a test didn't cancel it's work, resulting in a failed test. After quite a bit of debugging locally, I found that in some cases, the `CancellationTokenSource` was getting reset to non-cancelled after `TagSource.Dispose` was called, and then a work item queued with that token.
