### PR TITLE
Speculative semantic model - create child member models for attributes and parameter default values.

### LINKED ISSUE #24135: Speculative semantic model produces different behavior for local functions
See the behavior in this test:

```csharp
        [Fact]
        public void LocalFunctionAttribute()
        {
            const string text = @"
using System;
class A : Attribute {}

class C
{
    static void M()
    {
        void local<[A]T>() {}
    }
}";
            var tree = SyntaxFactory.ParseSyntaxTree(text);
            var comp = CreateStandardCompilation(tree);
            var model = comp.GetSemanticModel(tree);
            var a = tree.GetRoot().DescendantNodes()
                .OfType<IdentifierNameSyntax>().ElementAt(2);
            Assert.Equal("A", a.Identifier.Text);
            var attrInfo = model.GetSymbolInfo(a);
            var attrType = comp.GlobalNamespace.GetTypeMember("A");
            var attrCtor = attrType.GetMember(".ctor");
            Assert.Equal(attrCtor, attrInfo.Symbol);

            // Assert that this is also true for the speculative semantic model
            var newTree = SyntaxFactory.ParseSyntaxTree(text + " ");
            var m = newTree.GetRoot()
                .DescendantNodes().OfType<MethodDeclarationSyntax>().Single();

            Assert.True(model.TryGetSpeculativeSemanticModelForMethodBody(m.Body.SpanStart, m, out model));

            a = newTree.GetRoot().DescendantNodes().OfType<IdentifierNameSyntax>().ElementAt(2);
            Assert.Equal("A", a.Identifier.Text);

            // If we aren't using the right binder here, the compiler crashes going through the binder factory
            var info = model.GetSymbolInfo(a);
            Assert.Equal(attrType, info.Symbol);
        }
```

When using the regular semantic model, the symbol returned by GetSymbolInfo is the attribute constructor. When using the speculative semantic model, the type is returned instead.

The root cause of this seems to be that `TryGetSpeculativeSemanticModelForMethodBody` directly returns a MethodBody semantic model, which bypasses the `GetMemberModel` call which may be needed to retrieve a more specific model (like an Attribute or InitializerSemanticModel) that may be needed to bind pieces of local functions.

### LINKED ISSUE #60801: Speculation within attributes on local functions is broken
The binder from `GetBinder` all in `TryBindNameofOperator` should never be null.
But currently, it could be during speculation using a `MethodBodySemanticModel` (see test below, which would crash without this mitigation). 
This also happens in completion scenarios in the IDE (see tests that use `skipSpeculation` and are marked with the current issue).

In short, the model returned by `TryGetSpeculativeSemanticModelForMethodBody` should not directly try to bind the expression, it should first create an `AttributeSemanticModel` first in some cases.

This affects new `nameof` scenarios ([test plan](https://github.com/dotnet/roslyn/issues/40524)), but likely other existing scenarios too.

```
        private bool TryBindNameofOperator(InvocationExpressionSyntax node, BindingDiagnosticBag diagnostics, out BoundExpression result)
        {
            if (node.MayBeNameofOperator())
            {
                var binder = this.GetBinder(node);
                if (binder is null)
                {
                    // This could happen during speculation due to a bug, but should be removed
                    // Tracked by https://github.com/dotnet/roslyn/issues/60801
                    result = null;
                    return false;
                }
                if (binder.EnclosingNameofArgument == node.ArgumentList.Arguments[0].Expression)
                {
                    result = binder.BindNameofOperatorInternal(node, diagnostics);
                    return true;
                }
            }

            result = null;
            return false;
        }
```
```
        [Fact]
        public void ParameterScope_InMethodAttributeNameOf_GetSymbolInfoOnSpeculativeMethodBodySemanticModel()
        {
            var source = @"
class C
{
    void M()
    {
        [My(nameof(parameter))]
        void local(int parameter) { }
    }
}

public class MyAttribute : System.Attribute
{
    public MyAttribute(string name1) { }
}
";

            var comp = CreateCompilation(source, parseOptions: TestOptions.RegularNext);
            comp.VerifyDiagnostics(
                // (7,14): warning CS8321: The local function 'local' is declared but never used
                //         void local(int parameter) { }
                Diagnostic(ErrorCode.WRN_UnreferencedLocalFunction, "local").WithArguments("local").WithLocation(7, 14)
                );

            var tree = comp.SyntaxTrees.Single();
            var model = comp.GetSemanticModel(tree);

            var tree2 = CSharpSyntaxTree.ParseText(source);
            var method = tree2.GetRoot().DescendantNodes().OfType<MethodDeclarationSyntax>().First();
            Assert.True(model.TryGetSpeculativeSemanticModelForMethodBody(method.Body.SpanStart, method, out var speculativeModel));

            var invocation = tree2.GetRoot().DescendantNodes().OfType<InvocationExpressionSyntax>().Single();
            Assert.Equal("nameof(parameter)", invocation.ToString());
            var symbolInfo = speculativeModel.GetSymbolInfo(invocation);
            Assert.Null(symbolInfo.Symbol);
        }
```

Note to self: I have some [notes](https://github.com/jcouv/roslyn/commit/1597e6cb4c981ca2fe99110711c8f91e482e9607) from brainstorming with Aleksey on how to fix this.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #60801.
Fixes #24135.

### CODE REVIEW

**Review by 333fred — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski anything in particular you wanted me to hone in on?  Overall this looks fine to me :)

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi No; this needed some IDE reviewer and you seemed like a good choice.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Gotcha.  LGTM.

File: src/Compilers/Core/Portable/Operations/Operation.cs [hunk 1]
```diff
@@ -31,7 +31,7 @@ protected Operation(SemanticModel? semanticModel, SyntaxNode syntax, bool isImpl
             if (semanticModel != null)
             {
                 Debug.Assert(semanticModel.ContainingModelOrSelf != null);
-                if (semanticModel.IsSpeculativeSemanticModel)
+                if (semanticModel.Language != LanguageNames.CSharp && semanticModel.IsSpeculativeSemanticModel)
```
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/Core/Portable/Operations/Operation.cs:34]: > could you doc what's going on here? 

Once I merge this PR, I will open a follow-up issue for VB to align behavior. Once that is done, the code will go away.

[the remark this answers is not in the document]
Comment (CyrusNajmabadi) [reply src/Compilers/Core/Portable/Operations/Operation.cs:34]: gotcha.  thanks!  #resolved

**Comment by AlekseyTs** [comment]
@jcouv, @dotnet/roslyn-compiler For the second review.

**Comment by AlekseyTs** [comment]
@jcouv, @dotnet/roslyn-compiler For the second review.

File: src/Compilers/CSharp/Portable/Compilation/SpeculativeSemanticModelWithMemberModel.cs [hunk 2]
```diff
@@ -0,0 +1,565 @@
...
+using System.Collections.Immutable;
+using System.Diagnostics;
+using System.Threading;
+using Microsoft.CodeAnalysis.CSharp.Symbols;
+using Microsoft.CodeAnalysis.CSharp.Syntax;
+using Microsoft.CodeAnalysis.Text;
+using Roslyn.Utilities;
+
+namespace Microsoft.CodeAnalysis.CSharp
+{
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Compilation/SpeculativeSemanticModelWithMemberModel.cs:14]: Consider adding xml doc.
nit: extra blank line below

File: src/Compilers/CSharp/Portable/Compilation/PublicSemanticModel.cs [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+// The .NET Foundation licenses this file to you under the MIT license.
+// See the LICENSE file in the project root for more information.
+
+using Microsoft.CodeAnalysis.CSharp.Symbols;
+using Microsoft.CodeAnalysis.CSharp.Syntax;
+
+namespace Microsoft.CodeAnalysis.CSharp
+{
+    /// <summary>
+    /// Instances of this <see cref="SemanticModel"/> can be exposed to external consumers.
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Compilation/PublicSemanticModel.cs:11]: Do we have a comment somewhere explaining why some instances should not be exposed to external customers?

File: src/Compilers/CSharp/Portable/Compilation/SpeculativeSemanticModelWithMemberModel.cs [hunk 4]
```diff
@@ -0,0 +1,565 @@
...
+        }
+
+        private MemberSemanticModel GetOrAddModelForAttribute(MemberSemanticModel containing, AttributeSyntax attribute)
+        {
+            return ImmutableInterlocked.GetOrAdd(ref _childMemberModels, attribute,
+                                                 (node, binderAndModel) => CreateModelForAttribute(binderAndModel.binder, (AttributeSyntax)node, binderAndModel.model),
+                                                 (binder: containing.GetEnclosingBinder(attribute.SpanStart), model: containing));
+        }
+
+        private MemberSemanticModel GetOrAddModelForParameter(SyntaxNode node, MemberSemanticModel containing, ParameterSyntax paramDecl)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Compilation/SpeculativeSemanticModelWithMemberModel.cs:180]: This seem very close or duplicated from `SyntaxTreeSemanticModel.GetOrAddModelForParameter`. Could we factorize?

File: src/Compilers/CSharp/Portable/Compilation/SpeculativeSemanticModelWithMemberModel.cs [hunk 5]
```diff
@@ -0,0 +1,565 @@
...
+            SyntaxTreeSemanticModel parentSemanticModel,
+            int position,
+            NullableWalker.SnapshotManager? snapshotManagerOpt)
+        {
+            Debug.Assert(parentSemanticModel is not null);
+
+            _parentSemanticModel = parentSemanticModel;
+            _position = position;
+            _parentSnapshotManagerOpt = snapshotManagerOpt;
+            _memberModel = null!;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Compilation/SpeculativeSemanticModelWithMemberModel.cs:34]: How is this safe?

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 4) with some minor comments/questions

File: src/Compilers/CSharp/Portable/Compilation/SpeculativeSemanticModelWithMemberModel.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Compilation/SpeculativeSemanticModelWithMemberModel.cs:14]: > Consider adding xml doc.

I think the name is descriptive enough and captures everything that the doc comment would say.

File: src/Compilers/CSharp/Portable/Compilation/PublicSemanticModel.cs (hunk 3 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Compilation/PublicSemanticModel.cs:11]: > Do we have a comment somewhere explaining why some instances should not be exposed to external customers?

This would violate the design.

File: src/Compilers/CSharp/Portable/Compilation/SpeculativeSemanticModelWithMemberModel.cs (hunk 4 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Compilation/SpeculativeSemanticModelWithMemberModel.cs:180]: > Could we factorize?

I considered that, but didn't think the refactoring worth the trouble.

File: src/Compilers/CSharp/Portable/Compilation/PublicSemanticModel.cs (hunk 3 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/Compilation/PublicSemanticModel.cs:11]: I didn't follow how having a comment (I'm not talking about xml doc) would violate the design.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Compilation/PublicSemanticModel.cs:11]: > I didn't follow how having a comment (I'm not talking about xml doc) would violate the design.

Sorry for the confusion. I was not referring to having a comment, but to exposing other instances to external consumers. Doing that would violate the design.
