### PR TITLE
Ensure NullableWalker.SnapshotManager.ExitWalker() is invoked

### LINKED ISSUE #51739: Analyzer feature failures
**Version Used**: 
* VS 16.9.0, 
* `<TargetFramework>net5.0</TargetFramework>`
* MS NuGet packages: `Version="5.0.*"` (literally. I'm using * to deal with some inconsistencies)

**Steps to Reproduce**:
* Open a CS file
* Change to different CS file
* Use auto-completion/auto-suggestions/intellisense.

Note: Restart of VS didn't help; nor did a restart of my PC. 

**Expected Behavior**:
No errors are thrown by VS.

**Actual Behavior**:
image

Examples of stack traces:

**Example 1:**
```
StreamJsonRpc.RemoteInvocationException: Index was outside the bounds of the array.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
RPC server exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.SnapshotManager.GetUpdatedTypeForLocalSymbol(SourceLocalSymbol symbol)
      at Microsoft.CodeAnalysis.CSharp.NullabilityRewriter.<GetUpdatedSymbol>g__remapLocal|4_1[T](SourceLocalSymbol local)
      at Microsoft.CodeAnalysis.CSharp.NullabilityRewriter.GetUpdatedSymbol[T](BoundNode expr, T sym)
      at Microsoft.CodeAnalysis.CSharp.NullabilityRewriter.GetUpdatedArray[T](BoundNode expr, ImmutableArray`1 symbols)
      at Microsoft.CodeAnalysis.CSharp.NullabilityRewriter.VisitBlock(BoundBlock node)
      at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitNonConstructorMethodBody(BoundNonConstructorMethodBody node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.Rewrite(ImmutableDictionary`2 updatedNullabilities, SnapshotManager snapshotManager, BoundNode node, ImmutableDictionary`2& remappedSymbols)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.AnalyzeAndRewrite(CSharpCompilation compilation, Symbol symbol, BoundNode node, Binder binder, VariableState initialState, DiagnosticBag diagnostics, Boolean createSnapshots, SnapshotManager& snapshotManager, ImmutableDictionary`2& remappedSymbols)
      at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, DiagnosticBag diagnostics, VariableState nullableInitialState, ImportChain& importChain, Boolean& originalBodyNested, InitialState& forSemanticModel)
      at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
      at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
      at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass22_0.<CompileNamedTypeAsync>b__0()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
      at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0()
      at System.Threading.Tasks.Task.Execute()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.CSharp.MethodCompiler.WaitForWorkers()
      at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean emittingPdb, Boolean emitTestCoverageData, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForMethodBodiesInTree(SyntaxTree tree, Nullable`1 span, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForSyntaxTree(CompilationStage stage, SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Boolean includeEarlierStages, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDiagnostics(Nullable`1 span, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.GenerateCompilationEvents(AnalysisScope analysisScope, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<ComputeAnalyzerDiagnosticsAsync>d__67.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<ComputeAnalyzerSemanticDiagnosticsAsync>d__66.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<GetAnalysisResultCoreAsync>d__64.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Diagnostics.Extensions.<GetAnalysisResultAsync>d__12.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Diagnostics.Extensions.<GetAnalysisResultAsync>d__11.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.<AnalyzeAsync>d__9.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.<GetDiagnosticsAsync>d__8.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.<>c__DisplayClass3_0.<<CalculateDiagnosticsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__12`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Example 2:**
Feature 'Semantic classification' is currently unavailable due to an internal error.

```
StreamJsonRpc.RemoteInvocationException: Index was outside the bounds of the array.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
RPC server exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.SnapshotManager.GetUpdatedTypeForLocalSymbol(SourceLocalSymbol symbol)
      at Microsoft.CodeAnalysis.CSharp.NullabilityRewriter.<GetUpdatedSymbol>g__remapLocal|4_1[T](SourceLocalSymbol local)
      at Microsoft.CodeAnalysis.CSharp.NullabilityRewriter.GetUpdatedSymbol[T](BoundNode expr, T sym)
      at Microsoft.CodeAnalysis.CSharp.NullabilityRewriter.GetUpdatedArray[T](BoundNode expr, ImmutableArray`1 symbols)
      at Microsoft.CodeAnalysis.CSharp.NullabilityRewriter.VisitBlock(BoundBlock node)
      at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitNonConstructorMethodBody(BoundNonConstructorMethodBody node)
      at Microsoft.CodeAnalysis.CSharp.NullableWalker.Rewrite(ImmutableDictionary`2 updatedNullabilities, SnapshotManager snapshotManager, BoundNode node, ImmutableDictionary`2& remappedSymbols)
      at Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.RewriteNullableBoundNodesWithSnapshots(BoundNode boundRoot, Binder binder, DiagnosticBag diagnostics, Boolean createSnapshots, SnapshotManager& snapshotManager, ImmutableDictionary`2& remappedSymbols)
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.<EnsureNullabilityAnalysisPerformedIfNecessary>g__rewriteAndCache|132_1(DiagnosticBag diagnosticBag, <>c__DisplayClass132_0& )
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.EnsureNullabilityAnalysisPerformedIfNecessary()
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node)
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node, CSharpSyntaxNode& bindableNode, BoundNode& lowestBoundNode, BoundNode& highestBoundNode, BoundNode& boundParent)
      at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSymbolInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.Classification.Classifiers.NameSyntaxClassifier.ClassifyTypeSyntax(NameSyntax name, SemanticModel semanticModel, ArrayBuilder`1 result, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.Classification.Classifiers.NameSyntaxClassifier.AddClassifications(Workspace workspace, SyntaxNode syntax, SemanticModel semanticModel, ArrayBuilder`1 result, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ClassifyNode(SyntaxNode syntax)
      at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.ProcessNodes()
      at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.Worker.Classify(Workspace workspace, SemanticModel semanticModel, TextSpan textSpan, ArrayBuilder`1 list, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.<AddSemanticClassificationsAsync>d__5.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.<AddSemanticClassificationsInCurrentProcessAsync>d__3.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteSemanticClassificationService.<>c__DisplayClass2_0.<<GetSemanticClassificationsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__12`1.MoveNext()
```

### PR DESCRIPTION
**Pull request by cston**
Invoke `NullableWalker.SnapshotManager.ExitWalker()` even if an exception is thrown during nullable analysis (for instance, if an expression is too long to be analyzed) to ensure the `SnapshotManager` has a complete set of snapshots.

Fixes #51739

### CODE REVIEW

File: src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs [hunk 1]
```diff
@@ -316,5 +316,70 @@ static void runTest(int n)
...
+        }
+
+        [WorkItem(51739, "https://github.com/dotnet/roslyn/issues/51739")]
+        [ConditionalFact(typeof(WindowsOrLinuxOnly))]
+        public void NullableAnalysisNestedExpressionsInLocalFunction()
+        {
+            NullableAnalysisNestedExpressions(insideLocalFunction: true);
+        }
+
+        private static void NullableAnalysisNestedExpressions(bool insideLocalFunction)
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs:334]: This test doesn't directly hit the failure case. (A version of this test that did hit the failure case was too specific to be usable as a general test for different platforms etc.) I'll see if there are other alternatives.

**Comment by RikkiGibson** [comment]
So what exactly is happening here? Is it that user code has an expression too complex to be analyzed, then the set of snapshots gets into a bad state, then we crash?

It feels like the new behavior is to still throw from the walker, but because our snapshots are still in a good state, we are able to recover and allow the language tooling to continue functioning. Do I have that right?

**Comment by cston** [comment]
> So what exactly is happening here? Is it that user code has an expression too complex to be analyzed, then the set of snapshots gets into a bad state, then we crash?

Yes, if the expression is too complex to be analyzed, `NullableWalker.VisitExpression()` throws an exception that is caught in the `NullableWalker.Analyze()` entry point, but the snapshots were not completed so subsequent lookup in the snapshots can cause a crash.

This PR does not change where exceptions are thrown or caught. It simply adds `finally` blocks to complete the snapshots.

File: src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs:334]: Have you been able to verify the fix via ad-hoc testing?

**Review by RikkiGibson — APPROVED** [review]

File: src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs (hunk 1 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs:334]: > Have you been able to verify the fix via ad-hoc testing?

Yes. I verified the failure and the fix with a version of this test locally. But the test was not sufficiently general to hit the failure on all platforms, etc.

---
In reply to: [593512691](https://github.com/dotnet/roslyn/pull/51851#discussion_r593512691) [](ancestors = 593512691)

Comment (cston) [reply src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs]: The latest tests test the issue directly.

---
In reply to: [593513744](https://github.com/dotnet/roslyn/pull/51851#discussion_r593513744) [](ancestors = 593513744,593512691)

File: src/Compilers/CSharp/Test/Semantic/Semantics/OverloadResolutionPerfTests.cs [hunk 2]
```diff
@@ -551,5 +550,72 @@ public void NullableStateManyNestedFunctions()
                 //         return value;
                 Diagnostic(ErrorCode.WRN_NullReferenceReturn, "value").WithLocation(16395, 16));
         }
+
+        [WorkItem(51739, "https://github.com/dotnet/roslyn/issues/51739")]
+        [ConditionalFact(typeof(WindowsOnly), typeof(IsRelease))]
+        public void NullableAnalysisNestedExpressionsInMethod()
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/OverloadResolutionPerfTests.cs:556]: Are these tests enough to induce the crash when we break the placement of Enter/ExitWalker?

File: src/Compilers/CSharp/Test/Semantic/Semantics/OverloadResolutionPerfTests.cs [hunk 3]
```diff
@@ -551,5 +550,72 @@ public void NullableStateManyNestedFunctions()
                 //         return value;
                 Diagnostic(ErrorCode.WRN_NullReferenceReturn, "value").WithLocation(16395, 16));
         }
+
+        [WorkItem(51739, "https://github.com/dotnet/roslyn/issues/51739")]
+        [ConditionalFact(typeof(WindowsOnly), typeof(IsRelease))]
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/OverloadResolutionPerfTests.cs:555]: I feel like these tests could perform their function portably if the nesting level and max depth were, say, 20 and 10 respectively. I would feel a little better about this as it seems like someone inadvertently breaking the Enter/ExitWalker calls will cause this test to start failing.

File: src/Compilers/CSharp/Test/Semantic/Semantics/OverloadResolutionPerfTests.cs (hunk 2 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/OverloadResolutionPerfTests.cs:556]: > Are these tests enough to induce the crash when we break the placement of Enter/ExitWalker?

Yes, they should be sufficient. The tests hit the crash without the change to `NullableWalker`.

---
In reply to: [594513255](https://github.com/dotnet/roslyn/pull/51851#discussion_r594513255) [](ancestors = 594513255)

**Review by RikkiGibson — APPROVED** [review]
I would support making the new tests unconditional `Fact` instead of release-only if we have confidence that as written they don't risk exceeding stack limits.

**Comment by cston** [comment]
> I would support making the new tests unconditional Fact instead of release-only 

Asserts fail in `DebugVerifier` because not all of the expressions have been recorded in the snapshot when an expression is too complex.

---
In reply to: [612458302](https://github.com/dotnet/roslyn/pull/51851#issuecomment-612458302) [](ancestors = 612458302)

**Review by 333fred — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs [hunk 4]
```diff
@@ -137,7 +137,19 @@ internal Conversions Conversions
         /// The key is a symbol for methods or parameters, and syntax for attributes.
         /// The data is collected during testing only.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:138]: >The data is collected during testing only. [](start = 12, length = 42)

Is this still accurate? Otherwise holding all this information indefinitely is likely to cause perf issues.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 5]
```diff
@@ -406,6 +406,19 @@ public string GetDebuggerDisplay()
         // For purpose of nullability analysis, awaits create pending branches, so async usings and foreachs do too
         public sealed override bool AwaitUsingAndForeachAddsPendingBranch => true;
 
+        protected override void EnsureSufficientExecutionStack(int recursionDepth)
+        {
+            if (recursionDepth > StackGuard.MaxUncheckedRecursionDepth &&
+                compilation.NullableAnalysisData is { MaxRecursionDepth: var depth } &&
+                depth > 0 &&
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:413]: >depth > 0 && [](start = 16, length = 12)

Is this check necessary?

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableContextTests.cs [hunk 6]
```diff
@@ -195,7 +194,7 @@ class Program
             void verify(CSharpParseOptions parseOptions, params string[] expectedAnalyzedKeys)
             {
                 var comp = CreateCompilation(source, parseOptions: parseOptions);
-                comp.NullableAnalysisData = new ConcurrentDictionary<object, NullableWalker.Data>();
+                comp.NullableAnalysisData = new();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableContextTests.cs:197]: >new(); [](start = 44, length = 6)

Usage of target typed `new` negatively affects readability and I believe we tentatively agreed to not use it in Compilers on an e-mail thread.

File: src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs (hunk 4 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:138]: > Is this still accurate?

Yes, `NullableAnalysisData` is only in tests.

---
In reply to: [595299058](https://github.com/dotnet/roslyn/pull/51851#discussion_r595299058) [](ancestors = 595299058)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 5 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:413]: Yes, the default value is `-1` which is intended to mean no limit.

---
In reply to: [595301185](https://github.com/dotnet/roslyn/pull/51851#discussion_r595301185) [](ancestors = 595301185)

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 4)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableContextTests.cs (hunk 6 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableContextTests.cs:197]: `NullableAnalysisData` is just a field used by tests, primarily these tests. The actual type of the field seems unimportant.

---
In reply to: [595306179](https://github.com/dotnet/roslyn/pull/51851#discussion_r595306179) [](ancestors = 595306179)
