### PR TITLE
Ensure to get the name of nameof argument

### LINKED ISSUE #52013: nameof in attribute produces empty string
**Version Used**: 
```
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  3.1.113 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
```
**Steps to Reproduce**:

1.  Create source generator that adds property
2.  Create test that will have attribute referencing generated property via `nameof`
3. Inspect `AttributeData.ConstructorArguments`

**Expected Behavior**:

Arguments have property name in form `MemberNotNullAttribute("GeneratedProp")`

**Actual Behavior**:

Argument is an empty string `MemberNotNullAttribute("")`

**Sample**

Repo with complete example https://github.com/jl0pd/RoslynSourceGeneratorNameof

Sample class
```csharp
using System.Diagnostics.CodeAnalysis;
public partial class MyClass
{
    [MemberNotNull(nameof(GeneratedProp))]
    void Foo()
    {}

    public static void Main() {}
}
```

Source generator code, [link](https://github.com/jl0pd/RoslynSourceGeneratorNameof/blob/9837fc58b76a561023170342c01d846aa58035fa/RoslynSourceGeneratorNameof/MyBuggyGenerator.cs#L41)
```csharp
if (method.GetAttributes().FirstOrDefault(ad => SymbolEqualityComparer.Default.Equals(ad.AttributeClass, notNull)) is AttributeData ad)
{
    ImmutableArray<TypedConstant> args =  ad.ConstructorArguments; // actual {System.Diagnostics.CodeAnalysis.MemberNotNullAttribute("")}
    if (args[0].Value is "")                                       // should be {System.Diagnostics.CodeAnalysis.MemberNotNullAttribute("GeneratedProp")}
    {
        throw new Exception("here's bug!");
    }
}
```

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #52013.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs [hunk 1]
```diff
@@ -1874,7 +1874,7 @@ private void EnsureNameofExpressionSymbols(BoundMethodGroup methodGroup, Binding
         /// <summary>
         /// Returns true if syntax form is OK (so no errors were reported)
         /// </summary>
-        private bool CheckSyntaxForNameofArgument(ExpressionSyntax argument, out string name, BindingDiagnosticBag diagnostics, bool top = true)
+        private bool CheckSyntaxForNameofArgument(ExpressionSyntax argument, out string name, BindingDiagnosticBag diagnostics, bool boundArgumentHasAnyErrors, bool top = true)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs:1877]: >bool boundArgumentHasAnyErrors [](start = 128, length = 30)

Instead of adding this parameter we should consider passing BindingDiagnosticBag.Discarded when we are trying to suppress cascading diagnostics.

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs [hunk 2]
```diff
@@ -1831,11 +1831,11 @@ private BoundExpression BindNameofOperatorInternal(InvocationExpressionSyntax no
         {
             CheckFeatureAvailability(node, MessageID.IDS_FeatureNameof, diagnostics);
             var argument = node.ArgumentList.Arguments[0].Expression;
-            string name = "";
             // We relax the instance-vs-static requirement for top-level member access expressions by creating a NameofBinder binder.
             var nameofBinder = new NameofBinder(argument, this);
             var boundArgument = nameofBinder.BindExpression(argument, diagnostics);
-            if (!boundArgument.HasAnyErrors && CheckSyntaxForNameofArgument(argument, out name, diagnostics) && boundArgument.Kind == BoundKind.MethodGroup)
+            var syntaxIsOk = CheckSyntaxForNameofArgument(argument, out string name, diagnostics, boundArgument.HasAnyErrors);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs:1837]: >var syntaxIsOk = CheckSyntaxForNameofArgument(argument, out string name, diagnostics, boundArgument.HasAnyErrors); [](start = 12, length = 114)

We should add tests that observe this behavior change via SemanticModel/IOperation and possibly other APIs.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 3)

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs (hunk 1 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs:1877]: @AlekseyTs That simplifies it **alot**! 🎉

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs [hunk 3]
```diff
@@ -1831,11 +1831,12 @@ private BoundExpression BindNameofOperatorInternal(InvocationExpressionSyntax no
         {
             CheckFeatureAvailability(node, MessageID.IDS_FeatureNameof, diagnostics);
             var argument = node.ArgumentList.Arguments[0].Expression;
-            string name = "";
             // We relax the instance-vs-static requirement for top-level member access expressions by creating a NameofBinder binder.
             var nameofBinder = new NameofBinder(argument, this);
             var boundArgument = nameofBinder.BindExpression(argument, diagnostics);
-            if (!boundArgument.HasAnyErrors && CheckSyntaxForNameofArgument(argument, out name, diagnostics) && boundArgument.Kind == BoundKind.MethodGroup)
+
+            bool syntaxIsOk = CheckSyntaxForNameofArgument(argument, out string name, boundArgument.HasAnyErrors ? BindingDiagnosticBag.Discarded : diagnostics);
```
Comment (Youssef1313) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs:1838]: I didn't want to introduce a local for this conditional expression to prevent it from being used accidentally. (See few lines later which uses `diagnostics` regardless `syntaxIsOk`)

File: src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_INameOfOperation.cs [hunk 4]
```diff
@@ -176,6 +176,51 @@ void M(bool b, int i1, int i2)
...
+                  Right: 
+                    ILiteralOperation (OperationKind.Literal, Type: System.String, Constant: ""test2"", IsInvalid) (Syntax: 'nameof(test2)')
+            Next (Regular) Block[B2]
+                Leaving: {R1}
+    }
+    Block[B2] - Exit
+        Predecessors: [B1]
+        Statements (0)
 ";
             VerifyFlowGraphAndDiagnosticsForTest<BlockSyntax>(source, expectedFlowGraph, expectedDiagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_INameOfOperation.cs:225]: >VerifyFlowGraphAndDiagnosticsForTest [](start = 12, length = 36)

Did you really mean to validate a flow graph or just copied "wrong" test?

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 4), modulo a question around IOperation test.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review. Need a second sign-off for a small community PR.

File: src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_INameOfOperation.cs (hunk 4 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_INameOfOperation.cs:225]: @AlekseyTs, Ah I think I wanted to validate the operation tree instead. But probably okay to keep it since the ILiteralOperation's constant value should be affected by this change.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review. Need a second sign-off for a small community PR.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review. Need a second sign-off for a small community PR.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review. Need a second sign-off for a small community PR.

**Review by 333fred — APPROVED** [review]

**Comment by 333fred** [comment]
Thanks @Youssef1313!
