### PR TITLE
Remove conflicting key binding for integration tests

### LINKED ISSUE #65840: Quick Info tests fail when using new editor package versions
Found and disabled in https://github.com/dotnet/roslyn/pull/65795

```
at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/Contract.cs:line 154
   at Roslyn.Utilities.Contract.ThrowIfNull[T](T value, Int32 lineNumber) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/Contract.cs:line 29
   at Microsoft.VisualStudio.Extensibility.Testing.EditorInProcess.<InvokeQuickInfoAsync>d__13.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/EditorInProcess.cs:line 272
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicQuickInfo.<International>d__4.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicQuickInfo.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Note - these work fine in main.  Only in -vs-deps with new editor package versions do these fail.  Most likely related to the fact that the VS install on integration test machines is extremely old.  Hopefully can re-enable with https://github.com/dotnet/roslyn/pull/65839

### LINKED ISSUE #70511: VerifyOverloadsUpdated integration tests are failing
- Roslyn.VisualStudio.NewIntegrationTests.VisualBasic.BasicRename.VerifyOverloadsUpdated (VS2022)
- Roslyn.VisualStudio.NewIntegrationTests.CSharp.CSharpRename.VerifyOverloadsUpdated (VS2022)

Failing currently in all integration pipelines.

```
Expected:
[27..37)
[56..66)
[124..134)
[178..188)
Actual:
[27..37)
[124..134)
Differences:
[27..37)
--> [56..66)
[124..134)
--> [178..188)

Expected: True
Actual:   False

Stack trace
   at Roslyn.Test.Utilities.AssertEx.SetEqual[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer, String message, String itemSeparator, Func`2 itemInspector) in /_/src/Compilers/Test/Core/Assert/AssertEx.cs:line 478
   at Roslyn.VisualStudio.NewIntegrationTests.CSharp.CSharpRename.<VerifyOverloadsUpdated>d__11.MoveNext() in /_/src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpRename.cs:line 393
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

### PR DESCRIPTION
**Pull request by sharwell**
Closes #65840
Closes #70511

### CODE REVIEW

File: src/VisualStudio/IntegrationTest/New.IntegrationTests/AbstractIntegrationTest.cs [hunk 1]
```diff
@@ -28,6 +28,7 @@ public override async Task InitializeAsync()
                 await TestServices.SolutionExplorer.CloseSolutionAsync(HangMitigatingCancellationToken);
             }
 
+            await TestServices.Workarounds.RemoveConflictingKeyBindingsAsync(HangMitigatingCancellationToken);
```
Comment (sharwell) [inline src/VisualStudio/IntegrationTest/New.IntegrationTests/AbstractIntegrationTest.cs:31]: 📝 Would be good to restrict this with a version check

File: src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/WorkaroundsInProcess.cs [hunk 2]
```diff
@@ -6,12 +6,32 @@
...
     {
+        public async Task RemoveConflictingKeyBindingsAsync(CancellationToken cancellationToken)
+        {
+            await JoinableTaskFactory.SwitchToMainThreadAsync(cancellationToken);
+
+            var dte = await GetRequiredGlobalServiceAsync<SDTE, EnvDTE80.DTE2>(cancellationToken);
+            EnvDTE.Command command;
+            try
+            {
+                command = dte.Commands.Item("Edit.IntelliCode.APIUsageExamples");
```
Comment (sharwell) [inline src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/WorkaroundsInProcess.cs:24]: 📝 Need to link to tracking bug

**Review by dibarbet — APPROVED** [review]

**Review by CyrusNajmabadi — APPROVED** [review]

**Review by arkalyanms — APPROVED** [review]

**Review by jasonmalinowski — APPROVED** [review]

**Review by jasonmalinowski — APPROVED** [review]
