### PR TITLE
Report Obsolete diagnostics on Using Static Statements

### LINKED ISSUE #10639: Using static ignores Obsolete attribute
**Version Used**: 1.2.0.60317

**Steps to Reproduce**:
1. Compile following program

```
using System;
using static D;

[Obsolete ("Broken class", true)]
static class D
{
    public static void Foo ()
    {

    }
}

class Test
{
    public static void Main ()
    {
        Foo ();
    }
}
```

**Expected Behavior**:

Compilation error

**Actual Behavior**:

No error

### PR DESCRIPTION
**Pull request by OmarTawfik**
Fixes #10639

### CODE REVIEW

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-compiler ready for review.

File: src/Compilers/CSharp/Portable/Binder/Imports.cs [hunk 1]
```diff
@@ -217,6 +217,8 @@ internal string GetDebuggerDisplay()
                                 }
                                 else
                                 {
+                                    Binder.ReportDiagnosticsIfObsoleteInternal(diagnostics, importedType, usingDirective.Name, importedType.ContainingSymbol, BinderFlags.None);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Imports.cs]: Should the error be report on the `using static` statement or only on the use of that static type? For aliases such as `using A = N.C;`, we only report errors on the use of `A` whe `C` is marked `[Obsolete]`.

File: src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs [hunk 2]
```diff
@@ -8406,5 +8406,49 @@ class MyAttribute : System.Attribute
...
+}";
+
+            CreateCompilationWithMscorlib(source).VerifyDiagnostics(
+                // (3,14): error CS0619: 'TestError' is obsolete: 'Broken Error Class'
+                // using static TestError;
+                Diagnostic(ErrorCode.ERR_DeprecatedSymbolStr, "TestError").WithArguments("TestError", "Broken Error Class").WithLocation(3, 14),
+                // (4,14): warning CS0618: 'TestWarning' is obsolete: 'Broken Warning Class'
+                // using static TestWarning;
+                Diagnostic(ErrorCode.WRN_DeprecatedSymbolStr, "TestWarning").WithArguments("TestWarning", "Broken Warning Class").WithLocation(4, 14));
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs]: Do we need to test nested classes? `using static A.B;` where `A` is `[Obsolete]` for instance.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs]: Yes, I think it would be interesting to test scenarios like that. Both, when only A is obsolete and only B is obsolete.

---
In reply to: [95923514](https://github.com/dotnet/roslyn/pull/16472#discussion_r95923514) [](ancestors = 95923514)

File: src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs [hunk 3]
```diff
@@ -8406,5 +8406,49 @@ class MyAttribute : System.Attribute
 
             CompileAndVerify(source, symbolValidator: attributeValidator);
         }
+
+        [Fact, WorkItem(10639, "https://github.com/dotnet/roslyn/issues/10639")]
+        public void UsingStaticDirectiveDoesNotIgnoreObsoleteAttribute()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs]: >UsingStaticDirectiveDoesNotIgnoreObsoleteAttribute [](start = 20, length = 50)

It feels like this test doesn't belong in this file. Perhaps it should be in src\Compilers\CSharp\Test\Semantic\Semantics\ImportsTests.cs

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs]: Never mind, I see that we have similar tests for other contexts in this file.

---
In reply to: [96045994](https://github.com/dotnet/roslyn/pull/16472#discussion_r96045994) [](ancestors = 96045994)

File: src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.vb [hunk 4]
```diff
@@ -5208,5 +5208,43 @@ End Class
...
+    End Sub
+End Module
+]]>
+                             </file>
+                         </compilation>
+
+            Dim options = New VisualBasicCompilationOptions(OutputKind.ConsoleApplication, rootNamespace:="TestAssembly")
+            Dim compilation = CreateCompilationWithMscorlibAndVBRuntime(source, options)
+
+            compilation.VerifyDiagnostics(
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.vb]: >compilation.VerifyDiagnostics( [](start = 12, length = 30)

Please always use AssertTheseDiagnostics helper for VB tests, unless we verify the fact that diagnostics is empty.

File: src/Compilers/CSharp/Portable/Binder/Imports.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Imports.cs]: I think the difference is that there is an explicit reference to the alias when it is use, this is not the case here. Also, looks consistent with how VB behaves.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Imports.cs]: >Binder.ReportDiagnosticsIfObsoleteInternal [](start = 36, length = 42)

It doesn't look like we are supposed to use this method directly. I would use ```internal void ReportDiagnosticsIfObsolete(DiagnosticBag diagnostics, Symbol symbol, SyntaxNodeOrToken node, bool hasBaseReceiver)``` and call it off of ``declarationBinder``` or ```usingsBinder```. Might be useful to check how VB does this.

**Comment by AlekseyTs** [comment]
Done with review pass.

File: src/Compilers/CSharp/Portable/Binder/Imports.cs (hunk 1 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/Binder/Imports.cs]: The proposed behavior is consistent with VB. I think if we want to change it, we might want to change how VB behaves too (this has been around for a while AFAIK).

Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Imports.cs]: We should leave the behavior as you have it, consistent with VB.

**Comment by cston** [comment]
LGTM

**Comment by OmarTawfik** [comment]
@AlekseyTs comments addressed.
@gafter should this be recorded as a breaking change?

**Comment by gafter** [comment]
I've forwarded this question to the @dotnet/roslyn-compat-council for review.

**Comment by gafter** [comment]
Please target this to milestone 2.1.

**Comment by OmarTawfik** [comment]
@AlekseyTs do I've a sign off?

**Comment by OmarTawfik** [comment]
@dotnet-bot test this please

**Comment by OmarTawfik** [comment]
@jcouv do we need ASK MODE approval for `post-dev15` branch?

**Comment by jcouv** [comment]
No. Just code reviews and green CI as normal.
