### PR TITLE
Enforce proper shadowing for locals and parameters in EE

### LINKED ISSUE #18426: EE: Should not bind to display class parameters
At the breakpoint, evaluate `value`.
```
class C
{
    void F(int x)
    {
        int G()
        {
            return x + 1; // break here
        };
        G();
    }
}
```
Expected: `error CS0103: The name 'value' does not exist in the current context`
Actual: Binds to synthesized display class parameter

### LINKED ISSUE #67177: Display class locals "shadow" regular locals and parameters in EE
See comments for ```testData.GetMethodData``` calls in tests:
```
        [Fact]
        public void CapturingAndShadowing_01()
        {
            var source =
@"class C
{
    void Test()
    {
        int x = 0;
        int z = 1;

        var d1 = () =>
        {
            x += z;
        };

        d1();

        var d2 = () =>
        {
            sbyte x = 0;
            int y = x;

            var d3 = () =>
            {
                y += z;
            };

            x = -100;
#line 100
            z += x;
#line 200
            return d3;
        };

        d2()();
    }
}
";

            var testData = Evaluate(
                source,
                OutputKind.DynamicallyLinkedLibrary,
                methodName: "C.<>c__DisplayClass0_0.<Test>b__1",
                atLineNumber: 100,
                expr: "x");

            // Should load sbyte V_1 instead
            testData.GetMethodData("<>x.<>m0").VerifyIL(
@"
{
  // Code size        7 (0x7)
  .maxstack  1
  .locals init (C.<>c__DisplayClass0_1 V_0, //CS$<>8__locals0
                sbyte V_1, //x
                System.Action V_2, //d3
                System.Action V_3)
  IL_0000:  ldarg.0
  IL_0001:  ldfld      ""int C.<>c__DisplayClass0_0.x""
  IL_0006:  ret
}");
        }

        [Fact]
        public void CapturingAndShadowing_03()
        {
            var source =
@"class C
{
    void Test()
    {
        int x = 0;
        int z = 1;

        var d1 = () =>
        {
            x += z;
        };

        d1();

        var d2 = (sbyte x) =>
        {
            int y = x;

            var d3 = (short x) =>
            {
                y += z;
            };

            x = -100;
#line 100
            z += x;
#line 200
            return d3;
        };

        d2(-100)(-200);
    }
}
";

            var testData = Evaluate(
                source,
                OutputKind.DynamicallyLinkedLibrary,
                methodName: "C.<>c__DisplayClass0_0.<Test>b__1",
                atLineNumber: 100,
                expr: "x");

            // Should load parameter instead
            testData.GetMethodData("<>x.<>m0").VerifyIL(
@"
{
  // Code size        7 (0x7)
  .maxstack  1
  .locals init (C.<>c__DisplayClass0_1 V_0, //CS$<>8__locals0
                System.Action<short> V_1, //d3
                System.Action<short> V_2)
  IL_0000:  ldarg.0
  IL_0001:  ldfld      ""int C.<>c__DisplayClass0_0.x""
  IL_0006:  ret
}");
        }

        [Fact]
        public void CapturingAndShadowing_04()
        {
            var source =
@"class C
{
    void Test()
    {
        int x = 0;
        int z = 1;

        var d1 = () =>
        {
            x += z;
        };

        d1();

        var d2 = (sbyte x) =>
        {
            int y = x;

            var d3 = (short x) =>
            {
#line 100
                y += z;
#line 200
            };

            x = -100;
            z += x;

            return d3;
        };

        d2(-100)(-200);
    }
}
";

            var testData = Evaluate(
                source,
                OutputKind.DynamicallyLinkedLibrary,
                methodName: "C.<>c__DisplayClass0_1.<Test>b__2",
                atLineNumber: 100,
                expr: "x");

            // Should load parameter instead
            testData.GetMethodData("<>x.<>m0").VerifyIL(
@"
{
  // Code size       12 (0xc)
  .maxstack  1
  IL_0000:  ldarg.0
  IL_0001:  ldfld      ""C.<>c__DisplayClass0_0 C.<>c__DisplayClass0_1.CS$<>8__locals1""
  IL_0006:  ldfld      ""int C.<>c__DisplayClass0_0.x""
  IL_000b:  ret
}");
        }
```

### LINKED ISSUE #67188: Unexpected name conflict error in EE
```
        [Fact]
        public void CapturingAndShadowing_18()
        {
            var source =
@"class C
{
    void Test(byte x)
    {
        byte l1 = 1;

        void d1()
        {
            x += l1;
        };

        d1();
#line 100
        var d2 = (int x) => x;
#line 200
    }
}
";

            var testData = Evaluate(
                source,
                OutputKind.DynamicallyLinkedLibrary,
                methodName: "C.Test",
                atLineNumber: 100,
                expr: "(int x) => x");

            testData.GetMethodData("<>x.<>m0").VerifyIL(
@"
{
}");
        }
```

Observed:
```
    Assert.Null() Failure
Expected: (null)
Actual:   error CS0136: A local or parameter named 'x' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
```

Expected: No error.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #67177.
Fixes #18426.
Fixes #67188.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@cston, @dotnet/roslyn-compiler Please review.

File: src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs [hunk 1]
```diff
@@ -384,6 +402,43 @@ private static string GetNextMethodName(ArrayBuilder<MethodSymbol> builder)
                             !IsDisplayClassParameter(parameter))
                         {
                             itemsAdded.Add(parameterName);
+
+                            // Display class variables created for method parameters shadow the parameters.
```
Comment (cston) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs:406]: >Display class variables created for method parameters shadow the parameters. [](http://example.com/codeflow?start=31&length=76)

Is there a similar issue in VB?

Comment (AlekseyTs) [reply src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs:406]: > Is there a similar issue in VB?

I do not know. That would be doubtful because VB doesn't allow shadowing parameters by name and the rewrite that used to be done in ```CapturedVariableRewriter``` would work for VB. This code is a compensation for  removal of ```CapturedVariableRewriter.VisitParameter```, which didn't handle shadowing.

File: src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs [hunk 2]
```diff
@@ -384,6 +402,43 @@ private static string GetNextMethodName(ArrayBuilder<MethodSymbol> builder)
...
+                            if (_displayClassVariables.TryGetValue(parameterName, out var variable) && variable.Kind == DisplayClassVariableKind.Parameter)
+                            {
+                                int saveCount = methodBuilder.Count;
+                                int localIndex = 0;
+                                foreach (var local in _localsForBindingOutside)
```
Comment (cston) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs:411]: >_localsForBindingOutside [](http://example.com/codeflow?start=54&length=24)

Consider using `_localsForBindingOutside.Concat(_localsForBindingInside)` to simplify.

File: src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs [hunk 3]
```diff
@@ -82,17 +95,22 @@ internal sealed class CompilationContext
                     _locals,
                     inScopeHoistedLocalSlots,
                     _sourceMethodParametersInOrder,
-                    out var displayClassVariableNamesInOrder,
+                    parametersAreOutside: currentFrame.ParameterCount == 0,
```
Comment (cston) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs:98]: >currentFrame.ParameterCount == 0 [](http://example.com/codeflow?start=42&length=32)

Why does `ParameterCount == 0` determine whether parameters are considered outside of inside?

Comment (cston) [reply src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs:98]: > This is a special situation for async MoveNext method.

Consider adding a comment here to indicate that.

**Review by cston — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review

File: src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs [hunk 4]
```diff
@@ -420,7 +463,18 @@ private static string GetNextMethodName(ArrayBuilder<MethodSymbol> builder)
                     {
                         // Locals which were not added as parameters or parameters of the source method.
                         int localIndex = 0;
-                        foreach (var local in _localsForBinding)
+                        foreach (var local in _localsForBindingOutside)
+                        {
+                            if (!itemsAdded.Contains(local.Name) &&
+                                !_locals.Any((l, name) => l.Name == name, local.Name)) // Not captured locals inside the method shadow outside locals
```
Comment (333fred) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs:469]: Nit: consider marking the lambda static.

**Review by 333fred — APPROVED** [review]

File: src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs (hunk 4 above)
Comment (AlekseyTs) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs:469]:
```suggestion
                                !_locals.Any(static (l, name) => l.Name == name, local.Name)) // Not captured locals inside the method shadow outside locals
```
