### PR TITLE
[Stabilization, Crash] Rename: Don't restrict rename project search set for explicit interface implementations

### LINKED ISSUE #8139: Visual Studio crash when renaming explicit interface method implementation
Ported from internal bug 170064 (description modified)

Create a Console Application project that references a Class Library project, with the following code:

```C#
// In the Console Application
class Program
{
    static void Main(string[] args)
    {
        Test(new Class1());
    }

    static void Test(IInterface i)
    {
        i.M();
    }
}
```

```C#
// In the Class Library
public class Class1 : IInterface
{
    void IInterface.M() { }  // Rename 'M' from here
}

public interface IInterface
{
    void M();
}
```

Renaming `M` from `Class1` causes a VS crash.

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #8139
    
We were previously asserting that renaming a private member meant that the rename operation would occur entirely in that member's declaring project, but rename affect other projects if the private member is an explicit implementation of a public interface member.

Triage - **Fixes a crash** - We were crashing when you'd rename an explicit interface implementation of interface from a different project.

### CODE REVIEW

**Comment by dpoeschl** [comment]
Tagging for review @dotnet/roslyn-ide

File: src/Workspaces/Core/Portable/Rename/RenameUtilities.cs [hunk 1]
```diff
@@ -79,9 +79,8 @@ internal static IEnumerable<Document> GetDocumentsAffectedByRename(ISymbol symbo
                     .Concat(documentsOfRenameSymbolDeclaration.First().Id)
                     .Select(d => d.ProjectId).Distinct();
 
-                if (symbol.DeclaredAccessibility == Accessibility.Private)
+                if (ShouldRenameOnlyAffectDeclaringProject(symbol))
```
Comment (dpoeschl) [inline src/Workspaces/Core/Portable/Rename/RenameUtilities.cs]: I think I might want to additionally check "isSubset" and then include the extra projects if it is false rather than assert/throw, since it's much more likely that the rename cascaded from private to public than for us to have errantly found unrelated projects (I hope). But I'm not sure whether we'd rather keep it this way to keep the perf scenarios tightly monitored. @rchande - any thoughts?

**Comment by jasonmalinowski** [comment]
Curious: why is this change necessary like this? Why is `symbol` looking at the explicit method implementation instead of the interface method symbol which would see this as "public"?

**Comment by dpoeschl** [comment]
@jasonmalinowski This always runs off the "original" symbol, because for some kinds of cascading (overloads) the set of symbols can change during the rename, but the original symbol is always involved.

**Comment by jasonmalinowski** [comment]
That's your real bug, then, right? Renaming this should have cascaded to the other projects affected? Or that this function should be looking at all cascaded symbols and not just the original?

**Comment by dpoeschl** [comment]
@jasonmalinowski Updated the approach to match your (extremely correct) suggestion. Thoughts?

cc @dotnet/roslyn-ide for more reviews.

**Comment by dpoeschl** [comment]
@davkean FYI, another thing I might want to get in today (pending reviews, etc.)

**Comment by dpoeschl** [comment]
retest vsi please

File: src/EditorFeatures/Test2/Rename/RenameEngineTests.vb [hunk 2]
```diff
@@ -3153,11 +3153,52 @@ namespace X
...
+    void [|M|]();
+}
+                        </Document>
+                    </Project>
+
+                </Workspace>, renameTo:="Foo")
             End Using
         End Sub
 
+
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Test2/Rename/RenameEngineTests.vb]: Nit: extra blank line.

**Comment by jasonmalinowski** [comment]
:+1:. Nit should not be considered blocking.

**Comment by dpoeschl** [comment]
retest vsi please

**Comment by dpoeschl** [comment]
Updated review that should fix the previous test failures. @jasonmalinowski @dotnet/roslyn-ide @davkean

**Comment by dpoeschl** [comment]
@MattGertz @Pilchie Can we consider this for 1.2?

**Comment by MattGertz** [comment]
Approved pending testing.

**Comment by Pilchie** [comment]
:+1:, though concerned about the test failures.

**Comment by dpoeschl** [comment]
@jasonmalinowski @Pilchie Back to the original implementation. Not perfection, but it makes the world a better place.

**Comment by davkean** [comment]
@dotnet-bot test vsi please

**Comment by Pilchie** [comment]
Still :+1: on the targeted solution.

**Comment by jasonmalinowski** [comment]
And pretend I used a time machine to give you a :+1: on the targeted solution as well.
