### PR TITLE
Add parameter CodefixProvider: Fix argument list handling of local functions 

### LINKED ISSUE #29752: Action to add a new parameter to a local function actually replaces existing one
**Version Used**: 

Microsoft Visual Studio Professional 2017 
Version 15.8.2
VisualStudio.15.Release/15.8.2+28010.2016
Microsoft .NET Framework
Version 4.7.03056

**Steps to Reproduce**:

Paste the following code into VS:
```cs
class Rsrp
{
  public void M()
  {
    Local("ignore this", mynewparameter: true);
    void Local(string whatever)
    {
      
    }
  }
}
```

Execute 'Add parameter to Local(string)' action from the 'mynewparameter' identifier.

**Expected Behavior**:

New parameter is created in the local function.

**Actual Behavior**:

Existing parameter is replaced.

image

### LINKED ISSUE #29753: ArgumentOutOfRangeException from 'add parameter' code fix
**Version Used**: 

Microsoft Visual Studio Professional 2017
Version 15.8.2
VisualStudio.15.Release/15.8.2+28010.2016
Microsoft .NET Framework
Version 4.7.03056

**Steps to Reproduce**:

Paste the following code into VS:
```cs
class Rsrp
{
  public void M()
  {
    Local("ignore this", true);
    void Local(string whatever)
    {
      
    }
  }
}
```

Place the caret on the `Local` function invocation and open bulb items menu.

**Expected Behavior**:

No exceptions.

**Actual Behavior**:

```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: index
   at Roslyn.Utilities.SpecializedCollections.Empty.List`1.get_Item(Int32 index)
   at async Microsoft.CodeAnalysis.AddParameter.AbstractAddParameterCodeFixProvider`6.FixAsync[TArgumentSyntax,TAttributeArgumentSyntax,TArgumentListSyntax,TAttributeArgumentListSyntax,TInvocationExpressionSyntax,TObjectCreationExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

### PR DESCRIPTION
**Pull request by MaStr11**
Fixes #29752
Fixes #29753

Note to reviewers:
The diff shows a lot of changes for CSharpSyntaxGenerator.cs which are actually only whitespace related. 
You should turn on *[Hide whitespace changes](https://github.com/dotnet/roslyn/pull/29794/files?utf8=%E2%9C%93&diff=unified&w=1)* in the diff settings.

### CODE REVIEW

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs [hunk 1]
```diff
@@ -2680,6 +2680,8 @@ internal static BaseParameterListSyntax GetParameterList(SyntaxNode declaration)
                     return ((ParenthesizedLambdaExpressionSyntax)declaration).ParameterList;
                 case SyntaxKind.SimpleLambdaExpression:
                     return SyntaxFactory.ParameterList(SyntaxFactory.SingletonSeparatedList(((SimpleLambdaExpressionSyntax)declaration).Parameter));
+                case SyntaxKind.LocalFunctionStatement:
+                    return ((LocalFunctionStatementSyntax)declaration).ParameterList;
```
Comment (MaStr11) [inline src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs]: I don't know why all the other diffs show up on github, but I actually only added these two lines to CSharpSyntaxGenerator.cs
2018-09-12 11_07_28-roslyn - microsoft visual studio

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs [hunk 2]
```diff
@@ -2139,41 +2139,41 @@ public override DeclarationKind GetDeclarationKind(SyntaxNode declaration)
...
-                    // this node is considered the declaration if it is one among many, or it has no parent
-                    if (vd == null || vd.Variables.Count > 1)
                     {
-                        if (ParentIsFieldDeclaration(vd))
+                        var vd = (VariableDeclarationSyntax)declaration;
+                        if (vd.Variables.Count == 1 && vd.Parent == null)
                         {
-                            return DeclarationKind.Field;
+                            // this node is the declaration if it contains only one variable and has no parent.
+                            return DeclarationKind.Variable;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs]: when do we have no parent...?

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs [hunk 3]
```diff
@@ -2139,41 +2139,41 @@ public override DeclarationKind GetDeclarationKind(SyntaxNode declaration)
...
-                    }
-                }
-
-                case SyntaxKind.VariableDeclarator:
-                {
-                    var vd = declaration.Parent as VariableDeclarationSyntax;
-
-                    // this node is considered the declaration if it is one among many, or it has no parent
-                    if (vd == null || vd.Variables.Count > 1)
                     {
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs]: i think indentation changed, which made github very unhappy.  can we fix that?

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs (hunk 2 above)
Comment (MaStr11) [reply src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs]: That's only a whitespace diff. I haven't touched this. You should turn of whitespace in the diff settings.

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs (hunk 3 above)
Comment (MaStr11) [reply src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs]: Yep. We can either ignore it or I need to revert and commit again. Your call.

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs (hunk 2 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs]: >That's only a whitespace diff. I haven't touched this. You should turn of whitespace in the diff settings.

Well... why did you change the whitespace ;-)  

You're right though.  Adding `?w=1` showed things better.  So i'm def ok with this change :)

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs (hunk 1 above)
Comment (Neme12) [inline src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs]: Can you fix `WithParameterList` below as well for symmetry?

Comment (MaStr11) [reply src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs]: `SyntaxKind.LocalFunctionStatement` is already supported in `WithParameterList`: https://github.com/dotnet/roslyn/blob/b966e6700749381dcc9a8b73450214aa376e74eb/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L2690-L2709

Comment (Neme12) [reply src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs]: Ok thanks

**Comment by MaStr11** [comment]
@heejaechang Have you had a chance to look into this?

**Comment by heejaechang** [comment]
retest windows_release_vs-integration_prtest please

**Comment by heejaechang** [comment]
retest windows_release_vs-integration_prtest please
