### PR TITLE
Fix resx source generator for less common resx metadata and locations

### LINKED ISSUE #81973: resx source generator doesn't apply ClassName metadata consistently
**Version Used**: Microsoft.CodeAnalysis.ResxSourceGenerator 5.0.0-1.25277.114

**Steps to Reproduce**:

See [resxrepro.zip](https://github.com/user-attachments/files/24573095/resxrepro.zip) for a minimal repro.

Or, just do this:

1. Set `ClassName` metadata on an `EmbeddedResource` item for a Strings.resx file to some other namespace.classname value.
   ```xml
   <ItemGroup>
     <EmbeddedResource Update="Strings.resx" ClassName="AdjustedNS.AdjustedName" />
   </ItemGroup>
   ```
3. Look at the generated Strings.Designer.cs file.

**Expected Behavior**:

I expect to see only `AdjustedNS` as the namespace and only `AdjustedName` as the type name in the emitted coce.

**Actual Behavior**:

I see *both* the default *and* the adjusted namespace and name for the class:

```cs
// <auto-generated/>

#nullable enable
using System.Reflection;

namespace resxrepro
{
    internal static class Strings { }
}
namespace AdjustedNS
{
    internal static partial class AdjustedName
    {
        private static global::System.Resources.ResourceManager? s_resourceManager;
        public static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(resxrepro.Strings)));
        public static global::System.Globalization.CultureInfo? Culture { get; set; }
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        [return: global::System.Diagnostics.CodeAnalysis.NotNullIfNotNull("defaultValue")]
        internal static string? GetResourceString(string resourceKey, string? defaultValue = null) =>  ResourceManager.GetString(resourceKey, Culture) ?? defaultValue;
        /// <summary>The index for the account. Must be a non-negative number.</summary>
        public static string @AccountIndexOptionDescription => GetResourceString("AccountIndexOptionDescription")!;

    }
}
```

This breaks our builds, because `resxrepro` should never be a namespace, since it already appears as a type in the same context, causing C# to deal with compile errors when we reference the *type* that also now appears as a namespace.

This namespace/type changing works fine in the old resx design-time generated, designer.cs file approach. 
As such, this is an adoption blocker of the new resx source generator.

### LINKED ISSUE #81991: resx source generator emits invalid C# for namespace when .resx file is an absolute path
**Version Used**: Microsoft.CodeAnalysis.ResxSourceGenerator 5.0.0-1.25277.114

**Steps to Reproduce**:

Add an `EmbeddedResource` item like this:

```xml
<EmbeddedResource Include="$(PlatformPath)\Utilities\Impl\DpiAwarenessResources.resx" />
```

Where `$(PlatformPath)` is set to an absolute path.

**Expected Behavior**:

A valid code-behind is source generated.

**Actual Behavior**:

The emitted file has an invalid namespace:

```cs
namespace Microsoft.VisualStudio.Utilities.E:.VS.src.Platform.Utilities.Impl
```

Notice how this has `E:` as one of the segments of the namespace.

And due to #81973 I cannot workaround this bug by simply setting the `ClassName` metadata.

### PR DESCRIPTION
**Pull request by AArnott**
- Stop resx source generator from declaring type with original name when overridden
- Avoid emitting illegal namespace identifiers when resx file is not under the project directory by using `Link` metadata or removing the non-relative path.

This change deletes a block of code that is commented as being necessary to support NativeAOT. I have tested a NativeAOT app with these changes and it works. The source generator is also producing code more similar to the old resx SFG, so we should be quite confident it will run correctly.

Fixes #81973
Fixes #81991

### CODE REVIEW

File: src/RoslynAnalyzers/Microsoft.CodeAnalysis.ResxSourceGenerator/Microsoft.CodeAnalysis.ResxSourceGenerator/AbstractResxGenerator.cs [hunk 1]
```diff
@@ -693,7 +680,7 @@ End Namespace
                             {{memberIndent}}/// <summary>
                             {{memberIndent}}///   Returns the cached ResourceManager instance used by this class.
                             {{memberIndent}}/// </summary>
-                            {{memberIndent}}public static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof({{resourceTypeName}})));
+                            {{memberIndent}}public static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager({{(ResourceInformation.ResourceName == ResourceInformation.ResourceClassName ? $"typeof({className})" : $"\"{ResourceInformation.ResourceName}\", typeof({className}).Assembly")}}));
```
Comment (JoeRobich) [inline src/RoslynAnalyzers/Microsoft.CodeAnalysis.ResxSourceGenerator/Microsoft.CodeAnalysis.ResxSourceGenerator/AbstractResxGenerator.cs]: Please extract these ternaries since they are a bit much to read in-line.
