### PR TITLE
re-filter signature help providers if the file's content type has changed

### LINKED ISSUE #1940: Crash after changing content type.
We need to better handle content types changing.  I was looking at this and saw at least one crash:

1. Create a C# project
2. Rename Program.cs to Program.vb
3. Close and open the file
4. Convert the syntax to be VB syntax (by hand)
5. Rename the file back to Program.cs
6. Start converting the syntax back to C#

Result:
Crash: 
```
"Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax' to type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax'."
   at Microsoft.CodeAnalysis.VisualBasic.Extensions.IDocumentExtensions.VB$StateMachine_5_GetVisualBasicSyntaxRootAsync.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Editor.VisualBasic.SignatureHelp.GenericNameSignatureHelpProvider.VB$StateMachine_13_GetItemsWorkerAsync.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.AbstractSignatureHelpProvider.<GetItemsAsync>d__15.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller.Session.<ComputeItemsAsync>d__10.MoveNext()
```

### PR DESCRIPTION
**Pull request by brettfo**
When a file is opened and the user types a character, the list of all signature help providers is filtered based on the buffer's content type and cached.  If the content type is then changed without closing the file (e.g., renaming File1.cs to File1.vb) then another character is typed, the cached list of signature help providers is stale and any of those providers could be invoked based on `ISignatureHelpProvider.IsTriggerCharacter()` and `IsRetriggerCharacter()` which could ultimately lead to a crash when/if a syntax node is explicitly cast to a language-specific syntax node that doesn't match.

The fix is to also track the content type used to initially filter the list and invalidate the cache if the content type has changed.  There is also the added benefit with this change that after renaming a file extension, signature help continues to work as expected.

Writing a unit test for this ended up being very code-intensive and contrived, but I could be convinced to add an internal integration test for this scenario if people think it's important enough.

This also fixes another crashing bug I found while working on this where the mis-matched content type could cause the navigation bars to try to navigate with a negative index.  I audited all other instances of calling `GetCurrentSelection(int, out int)` and we either explicitly check for a negative index before navigation or we're appropriately guarded otherwise.

Fixes #1940.

### CODE REVIEW

**Comment by brettfo** [comment]
Tagging @Pilchie @dpoeschl @jasonmalinowski @balajikris @basoundr @rchande @davkean for review.

**Comment by Pilchie** [comment]
:+1:

**Comment by rchande** [comment]
I assume you found that Completion didn't have this problem when you tested the fix?

:+1:

**Comment by brettfo** [comment]
Correct, completion works as expected.

File: src/VisualStudio/Core/Def/Implementation/NavigationBar/NavigationBarClient.cs [hunk 1]
```diff
@@ -152,7 +152,7 @@ int IVsDropdownBarClient.GetComboTipText(int iCombo, out string pbstrText)
             int selectionIndex;
             var selectedItemPreviewText = string.Empty;
 
-            if (_dropdownBar.GetCurrentSelection(iCombo, out selectionIndex) == VSConstants.S_OK)
+            if (_dropdownBar.GetCurrentSelection(iCombo, out selectionIndex) == VSConstants.S_OK && selectionIndex >= 0)
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/NavigationBar/NavigationBarClient.cs]: Unrelated fix?

File: src/EditorFeatures/Core/Implementation/IntelliSense/SignatureHelp/Controller.cs [hunk 2]
```diff
@@ -108,13 +110,17 @@ private IList<ISignatureHelpProvider> GetProviders()
         {
             this.AssertIsForeground();
 
-            if (_providers == null)
+            var snapshot = this.SubjectBuffer.CurrentSnapshot;
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/IntelliSense/SignatureHelp/Controller.cs]: Why grab the snapshot? You can just do this.SubjectBuffer.ContentType directly and then skip the locals.

Comment (brettfo) [inline src/EditorFeatures/Core/Implementation/IntelliSense/SignatureHelp/Controller.cs]: Good call.  I'll inline the references to ContentType.

File: src/VisualStudio/Core/Def/Implementation/NavigationBar/NavigationBarClient.cs (hunk 1 above)
Comment (brettfo) [inline src/VisualStudio/Core/Def/Implementation/NavigationBar/NavigationBarClient.cs]: Partially related.  While debugging the original issue, there was a case where the mis-matched content type could cause GetCurrentSelection() to return true but set selectionIndex to -1 which would then crash VS for a different reason due to the invalid index.  I figured since it was such a small fix I'd rather take care of it here than create another PR for it.

Comment (davkean) [inline src/VisualStudio/Core/Def/Implementation/NavigationBar/NavigationBarClient.cs]: Doesn't that sound like a bug in GetCurrentSelection? Won't everyone whom calls this method need to handle this now?

Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/NavigationBar/NavigationBarClient.cs]: The [documentation for the API](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.textmanager.interop.ivsdropdownbar.getcurrentselection.aspx) isn't clear if -1 is an allowed return or not.

@brettfo: sounds like that's a separate bug. Even if it's not a separate PR, please have a separate git commit and an explanation in that commit why it's there.
