### PR TITLE
Handles clause with missing MyBase

### LINKED ISSUE #9400: IDE crash binding Handles clause with erroneous WithEvents declaration
**Version Used**:
VS2015 Update 2 CTP

**Steps to Reproduce**:

1. Create a VB project
2. Select all text and paste the code below

```VB
Public Class Form1
    Interface WithEvents a As Boolean

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load

    End Sub
End Class
```

**Actual Behavior**:
Crash.  Callstack:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.VisualBasic.Binder.ReportUseSiteError(DiagnosticBag diagBag, SyntaxNodeOrToken syntax, Symbol symbol) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Binding\Binder_Symbols.vb:line 264
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberMethodSymbol.BindSingleHandlesClause(HandlesClauseItemSyntax singleHandleClause, Binder typeBinder, DiagnosticBag diagBag, ArrayBuilder`1 candidateEventSymbols, ArrayBuilder`1 candidateWithEventsSymbols, ArrayBuilder`1 candidateWithEventsPropertySymbols, LookupResultKind& resultKind) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberMethodSymbol.vb:line 700
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberMethodSymbol.GetHandles(SourceModuleSymbol sourceModule, DiagnosticBag diagBag) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberMethodSymbol.vb:line 588
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberMethodSymbol.get_HandledEvents() in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberMethodSymbol.vb:line 562
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMethodSymbol.GenerateDeclarationErrors(CancellationToken cancellationToken) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMethodSymbol.vb:line 560
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberMethodSymbol.GenerateDeclarationErrors(CancellationToken cancellationToken) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberMethodSymbol.vb:line 211
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.GenerateAllDeclarationErrorsImpl(CancellationToken cancellationToken) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberContainerTypeSymbol.vb:line 294
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.GenerateAllDeclarationErrorsImpl(CancellationToken cancellationToken) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceNamedTypeSymbol.vb:line 102
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.GenerateDeclarationErrors(CancellationToken cancellationToken) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberContainerTypeSymbol.vb:line 281
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol._Closure$__77-0._Lambda$__0(NamespaceOrTypeSymbol typeOrNamespace) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceModuleSymbol.vb:line 568
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol._Closure$__80-1._Lambda$__0() in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceModuleSymbol.vb:line 690
   at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in D:\Code\Roslyn\Open\src\Compilers\Core\Portable\InternalUtilities\UICultureUtilities.cs:line 136
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol.GetDeclarationErrorsInTree(SyntaxTree tree, Nullable`1 filterSpanWithinTree, Func`4 locationFilter, CancellationToken cancellationToken) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceModuleSymbol.vb:line 576
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.GetDiagnosticsForSyntaxTree(CompilationStage stage, SyntaxTree tree, Nullable`1 filterSpanWithinTree, Boolean includeEarlierStages, CancellationToken cancellationToken) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Compilation\VisualBasicCompilation.vb:line 1999
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetDiagnostics(Nullable`1 span, CancellationToken cancellationToken) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Compilation\SyntaxTreeSemanticModel.vb:line 91
   at Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.<HasAnyErrorsAsync>d__5.MoveNext() in D:\Code\Roslyn\Open\src\Workspaces\Core\Portable\Shared\Extensions\DocumentExtensions.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.CodeCleanup.AbstractCodeCleanerService.<IterateAllCodeCleanupProvidersAsync>d__15.MoveNext() in D:\Code\Roslyn\Open\src\Workspaces\Core\Portable\CodeCleanup\AbstractCodeCleanerService.cs:line 461
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.CodeCleanup.AbstractCodeCleanerService.<CleanupAsync>d__1.MoveNext() in D:\Code\Roslyn\Open\src\Workspaces\Core\Portable\CodeCleanup\AbstractCodeCleanerService.cs:line 43
3/2/2016 7:47:39 AM
Source: First chance exception: First chance exception: First chance exception: First chance exception: Microsoft.CodeAnalysis.VisualBasic
StackTrace:    at Microsoft.CodeAnalysis.VisualBasic.Binder.ReportUseSiteError(DiagnosticBag diagBag, SyntaxNodeOrToken syntax, Symbol symbol) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Binding\Binder_Symbols.vb:line 264
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberMethodSymbol.BindSingleHandlesClause(HandlesClauseItemSyntax singleHandleClause, Binder typeBinder, DiagnosticBag diagBag, ArrayBuilder`1 candidateEventSymbols, ArrayBuilder`1 candidateWithEventsSymbols, ArrayBuilder`1 candidateWithEventsPropertySymbols, LookupResultKind& resultKind) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberMethodSymbol.vb:line 700
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberMethodSymbol.GetHandles(SourceModuleSymbol sourceModule, DiagnosticBag diagBag) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberMethodSymbol.vb:line 588
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberMethodSymbol.get_HandledEvents() in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberMethodSymbol.vb:line 562
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMethodSymbol.GenerateDeclarationErrors(CancellationToken cancellationToken) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMethodSymbol.vb:line 560
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberMethodSymbol.GenerateDeclarationErrors(CancellationToken cancellationToken) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberMethodSymbol.vb:line 211
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.GenerateAllDeclarationErrorsImpl(CancellationToken cancellationToken) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberContainerTypeSymbol.vb:line 294
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.GenerateAllDeclarationErrorsImpl(CancellationToken cancellationToken) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceNamedTypeSymbol.vb:line 102
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.GenerateDeclarationErrors(CancellationToken cancellationToken) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceMemberContainerTypeSymbol.vb:line 281
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol._Closure$__77-0._Lambda$__0(NamespaceOrTypeSymbol typeOrNamespace) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceModuleSymbol.vb:line 568
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol._Closure$__80-1._Lambda$__0() in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceModuleSymbol.vb:line 690
   at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in D:\Code\Roslyn\Open\src\Compilers\Core\Portable\InternalUtilities\UICultureUtilities.cs:line 136
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceModuleSymbol.GetDeclarationErrorsInTree(SyntaxTree tree, Nullable`1 filterSpanWithinTree, Func`4 locationFilter, CancellationToken cancellationToken) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceModuleSymbol.vb:line 576
   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.GetDiagnosticsForSyntaxTree(CompilationStage stage, SyntaxTree tree, Nullable`1 filterSpanWithinTree, Boolean includeEarlierStages, CancellationToken cancellationToken) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Compilation\VisualBasicCompilation.vb:line 1999
   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetDiagnostics(Nullable`1 span, CancellationToken cancellationToken) in D:\Code\Roslyn\Open\src\Compilers\VisualBasic\Portable\Compilation\SyntaxTreeSemanticModel.vb:line 91
   at Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.<HasAnyErrorsAsync>d__5.MoveNext() in D:\Code\Roslyn\Open\src\Workspaces\Core\Portable\Shared\Extensions\DocumentExtensions.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.CodeCleanup.AbstractCodeCleanerService.<IterateAllCodeCleanupProvidersAsync>d__15.MoveNext() in D:\Code\Roslyn\Open\src\Workspaces\Core\Portable\CodeCleanup\AbstractCodeCleanerService.cs:line 461
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.CodeCleanup.AbstractCodeCleanerService.<CleanupAsync>d__1.MoveNext() in D:\Code\Roslyn\Open\src\Workspaces\Core\Portable\CodeCleanup\AbstractCodeCleanerService.cs:line 43
```

### PR DESCRIPTION
**Pull request by cston**
Fixes #9400

### CODE REVIEW

**Comment by cston** [comment]
@dotnet/roslyn-compiler please review

File: src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberMethodSymbol.vb [hunk 1]
```diff
@@ -697,17 +697,21 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols
                 Return Nothing
             End If
 
-            typeBinder.ReportUseSiteError(diagBag, singleHandleClause.EventMember, eventContainingType)
```
Comment (jaredpar) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberMethodSymbol.vb]: Was the original NRE a result of `eventContainingType` being `Nothing`?

Comment (cston) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberMethodSymbol.vb]: Yes.

Comment (jaredpar) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberMethodSymbol.vb]: Can't we run into the same problem here? 

http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Binding/Binder_Conversions.vb,1074

**Comment by cston** [comment]
@mattgertz ask mode approval

**Comment by MattGertz** [comment]
Approved pending code reviews.

File: src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberMethodSymbol.vb (hunk 1 above)
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberMethodSymbol.vb]: `CreateUserDefinedConversion` asserts `convKind.Value IsNot Nothing` and dereferences `convKind.Value` in several places before calling `ReportUseSiteError`.

File: src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Source/EventTests.vb [hunk 2]
```diff
@@ -2209,5 +2209,26 @@ End Enum
             Assert.Equal(0, symbolInfo.CandidateSymbols.Length)
         End Sub
 
+        <WorkItem(9400, "https://github.com/dotnet/roslyn/issues/9400")>
+        <Fact()>
+        Public Sub HandlesNoMyBase()
+            Dim compilation = CompilationUtils.CreateCompilationWithMscorlib(
+<compilation>
+    <file name="a.vb"><![CDATA[
+Interface I
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Source/EventTests.vb]: I think the repro in the issue uses a class. Is it a mistake in the issue? Let's correct it, otherwise consider adding a test with a class.

**Comment by AlekseyTs** [comment]
LGTM, modulo the class/interface inconsistency between the repro in the issue and the unit-test.

**Comment by Pilchie** [comment]
The repro was a case with parse errors `Interface WithEvents a`.  My assumption is that @cston constructed this based on the shape of the tree the parser generated when recovering.

File: src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Source/EventTests.vb (hunk 2 above)
Comment (cston) [inline src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Source/EventTests.vb]: In #9400 the member with the `Handles` clause is `Interface WithEvents`.

Comment (cston) [inline src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Source/EventTests.vb]: In #9400 the `Handles` clause is on a member of `Interface WithEvents`.

**Comment by AlekseyTs** [comment]
@Pilchie, @cston Thanks, I got it now the indentation confused me.

**Comment by AlekseyTs** [comment]
LGTM

**Comment by jaredpar** [comment]
:+1:
