### PR TITLE
Fix compiler crash in broken code in pattern matching

### LINKED ISSUE #10529: Compiler crash when operand of pattern match is error
**Version Used**:  Future branch, commit a5a17a2fb3d46c84ef05cb92ebd3a04c1d025612

**Reproduce**:

a.

````
if (obj.Property is var o) { } // `obj` doesn't exist.
```
b.

````
var obj = new object();
if (obj| is var o) { } // Now type `.`(dot) at `|`.
````

AND

The IntelliSense thinks the type of `o` is `var` in snippet b, maybe relates to #10174.

**Exception**:

````
System.NullReferenceException: Object reference not set to an instance of an object.

   at Microsoft.CodeAnalysis.CSharp.Binder.IsOperatorErrors(CSharpSyntaxNode node, TypeSymbol operandType, BoundTypeExpression typeExpression, DiagnosticBag diagnostics) in D:\Github\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Operators.cs:line 2566
   at Microsoft.CodeAnalysis.CSharp.Binder.BindDeclarationPattern(DeclarationPatternSyntax node, BoundExpression operand, TypeSymbol operandType, Boolean hasErrors, DiagnosticBag diagnostics) in D:\Github\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Patterns.cs:line 358
   at Microsoft.CodeAnalysis.CSharp.Binder.BindPattern(PatternSyntax node, BoundExpression operand, TypeSymbol operandType, Boolean hasErrors, DiagnosticBag diagnostics) in D:\Github\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Patterns.cs:line 28
   at Microsoft.CodeAnalysis.CSharp.Binder.BindIsPatternExpression(IsPatternExpressionSyntax node, DiagnosticBag diagnostics) in D:\Github\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Patterns.cs:line 17
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in D:\Github\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 606
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in D:\Github\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 380
   at Microsoft.CodeAnalysis.CSharp.Binder.BindBooleanExpression(ExpressionSyntax node, DiagnosticBag diagnostics) in D:\Github\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 2832
   at Microsoft.CodeAnalysis.CSharp.Binder.BindIfStatement(IfStatementSyntax node, DiagnosticBag diagnostics) in D:\Github\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 2782
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatementCore(StatementSyntax node, DiagnosticBag diagnostics) in D:\Github\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 61
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.IncrementalBinder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in D:\Github\roslyn\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1704
   at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics) in D:\Github\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 2350
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatementCore(StatementSyntax node, DiagnosticBag diagnostics) in D:\Github\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 48
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.IncrementalBinder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in D:\Github\roslyn\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1704
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.Bind(Binder binder, CSharpSyntaxNode node, DiagnosticBag diagnostics) in D:\Github\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 2036
   at Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.Bind(Binder binder, CSharpSyntaxNode node, DiagnosticBag diagnostics) in D:\Github\roslyn\src\Compilers\CSharp\Portable\Compilation\MethodBodySemanticModel.cs:line 36
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node) in D:\Github\roslyn\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1461
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode(CSharpSyntaxNode node) in D:\Github\roslyn\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 410
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node, CSharpSyntaxNode& bindableNode, BoundNode& lowestBoundNode, BoundNode& highestBoundNode, BoundNode& boundParent) in D:\Github\roslyn\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1019
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetOperationWorker(CSharpSyntaxNode node, GetOperationOptions options, CancellationToken cancellationToken) in D:\Github\roslyn\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 854
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetOperationWorker(CSharpSyntaxNode node, GetOperationOptions options, CancellationToken cancellationToken) in D:\Github\roslyn\src\Compilers\CSharp\Portable\Compilation\SyntaxTreeSemanticModel.cs:line 165
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetOperationCore(SyntaxNode node, CancellationToken cancellationToken) in D:\Github\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 471
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.GetOperationBlocksToAnalyze(ImmutableArray`1 executableBlocks, SemanticModel semanticModel, CancellationToken cancellationToken) in D:\Github\roslyn\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerDriver.cs:line 1820
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.ExecuteDeclaringReferenceActions(SyntaxReference decl, Int32 declarationIndex, SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, AnalysisState analysisStateOpt, Boolean shouldExecuteSyntaxNodeActions, Boolean shouldExecuteOperationActions, Boolean shouldExecuteCodeBlockActions, Boolean shouldExecuteOperationBlockActions, Boolean isInGeneratedCode, CancellationToken cancellationToken) in D:\Github\roslyn\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerDriver.cs:line 1586
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.ExecuteDeclaringReferenceActions(SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, AnalysisState analysisStateOpt, Boolean isGeneratedCodeSymbol, CancellationToken cancellationToken) in D:\Github\roslyn\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerDriver.cs:line 1448
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessSymbolDeclared(SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, AnalysisState analysisStateOpt, CancellationToken cancellationToken) in D:\Github\roslyn\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerDriver.cs:line 875
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessEventCore(CompilationEvent e, AnalysisScope analysisScope, AnalysisState analysisStateOpt, CancellationToken cancellationToken) in D:\Github\roslyn\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerDriver.cs:line 833
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<ProcessCompilationEventsCoreAsync>d__67.MoveNext() in D:\Github\roslyn\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerDriver.cs:line 809
````

### PR DESCRIPTION
**Pull request by gafter**
Fix binder factory for local function improperly placed as an embedded statement.
Also changes per code review on previous PR in pattern-matching branch.
Fixes #10529

@AlekseyTs @agocke Please review
/cc @dotnet/roslyn-compiler

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 1]
```diff
@@ -625,14 +625,20 @@ private bool ApplicableOperatorIs(MethodSymbol candidate, CSharpSyntaxNode node,
             AliasSymbol aliasOpt;
             TypeSymbol declType = BindType(typeSyntax, diagnostics, out isVar, out aliasOpt);
             if (isVar && operandType != null) declType = operandType;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: (object)?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 2]
```diff
@@ -7684,65 +7684,65 @@ void Test16(int val)
...
+    Diagnostic(ErrorCode.ERR_NameNotInContext, "y10").WithArguments("y10").WithLocation(85, 17),
+    // (87,25): error CS0841: Cannot use local variable 'y10' before it is declared
+    //             case 0 when y10:
+    Diagnostic(ErrorCode.ERR_VariableUsedBeforeDeclaration, "y10").WithArguments("y10").WithLocation(87, 25),
+    // (89,18): error CS0841: Cannot use local variable 'y10' before it is declared
+    //             case y10:
+    Diagnostic(ErrorCode.ERR_VariableUsedBeforeDeclaration, "y10").WithArguments("y10").WithLocation(89, 18),
                 // (89,18): error CS0150: A constant value is expected
                 //             case y10:
                 Diagnostic(ErrorCode.ERR_ConstantExpected, "y10").WithLocation(89, 18),
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: It is not clear why alignment is left inconsistent.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 3]
```diff
@@ -15362,5 +15362,38 @@ static void Main()
...
+";
+            var compilation = CreateCompilationWithMscorlib45(source, options: TestOptions.DebugExe, parseOptions: patternParseOptions);
+            compilation.VerifyDiagnostics(
+                // (11,22): error CS1001: Identifier expected
+                //             if (obj. is var o) { }
+                Diagnostic(ErrorCode.ERR_IdentifierExpected, "is").WithLocation(11, 22),
+                // (7,17): error CS0103: The name 'obj' does not exist in the current context
+                //             if (obj.Property is var o) { } // `obj` doesn't exist.
+                Diagnostic(ErrorCode.ERR_NameNotInContext, "obj").WithArguments("obj").WithLocation(7, 17),
+                // (7,17): error CS0837: The first operand of an 'is' or 'as' operator may not be a lambda expression, anonymous method, or method group.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: This error feels unexpected.

**Comment by AlekseyTs** [comment]
I do not believe this change fixes #10521.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 4]
```diff
@@ -15362,5 +15362,38 @@ static void Main()
...
+                //             if (obj.Property is var o) { } // `obj` doesn't exist.
+                Diagnostic(ErrorCode.ERR_LambdaInIsAs, "obj.Property is var o").WithLocation(7, 17)
+                );
+        }
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Consider adding verification for relevant semantic model APIs.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: It is a merge artifact. I'll make them consistent.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs (hunk 3 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: It is because we have an empty method group. However, it is a cascaded diagnostic and I will suppress it.

**Comment by gafter** [comment]
All review comments addressed.

File: src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs [hunk 5]
```diff
@@ -2552,8 +2552,12 @@ private bool IsOperandErrors(CSharpSyntaxNode node, BoundExpression operand, Dia
                 case BoundKind.UnboundLambda:
                 case BoundKind.Lambda:
                 case BoundKind.MethodGroup:  // New in Roslyn - see DevDiv #864740.
-                    // operand for an is or as expression cannot be a lambda expression or method group
-                    Error(diagnostics, ErrorCode.ERR_LambdaInIsAs, node);
+                                             // operand for an is or as expression cannot be a lambda expression or method group
+                    if (!operand.HasAnyErrors)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs]: Alignment of the comment is off

File: src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs [hunk 6]
```diff
@@ -2963,8 +2967,11 @@ private BoundExpression BindAsOperator(BinaryExpressionSyntax node, DiagnosticBa
...
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs]: Alignment of the comment is off

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 7]
```diff
@@ -7725,7 +7725,7 @@ void Test16(int val)
                 Diagnostic(ErrorCode.ERR_VariableUsedBeforeDeclaration, "y11").WithArguments("y11").WithLocation(102, 18),
                 // (102,18): error CS0150: A constant value is expected
                 //             case y11:
-                Diagnostic(ErrorCode.ERR_ConstantExpected, "y11").WithLocation(102, 18),
+                            Diagnostic(ErrorCode.ERR_ConstantExpected, "y11").WithLocation(102, 18),
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Alignment is off

File: src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs (hunk 6 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs]: Alignment of the comment is off

**Comment by AlekseyTs** [comment]
LGTM, modulo alignment issues.

**Comment by gafter** [comment]
@agocke Please review

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 8]
```diff
@@ -617,30 +617,36 @@ private bool ApplicableOperatorIs(MethodSymbol candidate, CSharpSyntaxNode node,
...
-                hasErrors = CheckValidPatternType(typeSyntax, operand, operandType, declType,
+                hasErrors |= CheckValidPatternType(typeSyntax, operand, operandType, declType,
                                                   isVar: isVar, patternTypeWasInSource: true, diagnostics: diagnostics);
             }
 
             SourceLocalSymbol localSymbol = this.LookupLocal(identifier);
 
             // In error scenarios with misplaced code, it is possible we can't bind the local declaration.
             // This occurs through the semantic model.  In that case concoct a plausible result.
-            if ((object)localSymbol == null)
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: Why the swap?

**Comment by agocke** [comment]
LGTM

**Comment by AlekseyTs** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs (hunk 8 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: Consistency.
