### PR TITLE
Adjust implement interface service to work with static abstract operators

### LINKED ISSUE #53925: Implement interface fixer doesn't spit out `static` modifier implementations of static members
Start with:
```
interface I3
{
    static abstract void M1();
}

class Test31 : I3
{
}

class Test32 : I3
{
}
```

Use "Implement interface implicitly" for Test31 and "Implement interface explicitly" for Test32.

Observed:
```
class Test31 : I3
{
    public void M1()
    {
        throw new NotImplementedException();
    }
}

class Test32 : I3
{
    void I3.M1()
    {
        throw new NotImplementedException();
    }
}
```

Expected:
```
class Test31 : I3
{
    public static void M1()
    {
        throw new NotImplementedException();
    }
}

class Test32 : I3
{
    static void I3.M1()
    {
        throw new NotImplementedException();
    }
}
```

### LINKED ISSUE #53927: Implement interface fixer is not offered for an operator declared in an interface
Start with.
```
interface I3
{
    static abstract int operator -(I3 x);
}

class Test31 : I3
{
}
```

Observed:
"Implement interface" fixer is not offered for Test31.

If there are non-operator members to implement, the fixer is offered, but it doesn't spit out implementation (implicit or explicit) for operators. 

Same experience with conversion operators.

### LINKED ISSUE #54327: Implement interface fails to emit static modifier for explicit interface implementation
This test reveals a bug in Implement Interface Explicitly:

https://github.com/dotnet/roslyn/blob/51c367a5c3b2e51026bd0dc459bbb9cba6e09d3b/src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs#L9470-L9522

The `static` modifier was omitted, resulting in multiple errors in the generated code.

### LINKED ISSUE #54328: Implement interface abstractly should not apply to static members
Implementations of static abstract members in an interface cannot be abstract themselves. Implement Interface Abstractly should perform one of the following actions instead:

1. Omit `static abstract` members declared in the interface (they can be implemented by a subsequent "Implement remaining members" action).
2. Include implementations for `static abstract` members, but give them an implementation instead of marking them abstract.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #53927
Fixes #53925
Fixes #54328
Fixes #54327

### CODE REVIEW

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction_Method.cs [hunk 1]
```diff
@@ -14,6 +15,63 @@ namespace Microsoft.CodeAnalysis.ImplementInterface
 {
     internal abstract partial class AbstractImplementInterfaceService
     {
+        private sealed class InterfaceReplacerWithContainingTypeVisistor : SymbolVisitor<ISymbol>
+        {
+            private readonly INamedTypeSymbol _intrerfaceSymbol;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction_Method.cs:20]: "intrerface"

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction_Method.cs [hunk 2]
```diff
@@ -14,6 +15,63 @@ namespace Microsoft.CodeAnalysis.ImplementInterface
...
+            public override ISymbol VisitNamedType(INamedTypeSymbol symbol)
+            {
+                if (symbol.Equals(_intrerfaceSymbol, SymbolEqualityComparer.Default))
+                {
+                    return _containingTypeSymbol;
+                }
+
+                return symbol;
+            }
+        }
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction_Method.cs:73]: 1.this is all interesting.  is this the lgoic the compiler uses here?
2. can we have tests with generic classes/interfaces?

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction_Method.cs [hunk 3]
```diff
@@ -25,14 +83,20 @@ internal partial class ImplementInterfaceCodeAction
...
                 var updatedMethod = method.EnsureNonConflictingNames(State.ClassOrStructType, syntaxFacts);
 
                 updatedMethod = updatedMethod.RemoveInaccessibleAttributesAndAttributesOfTypes(
                     State.ClassOrStructType,
                     AttributesToRemove(compilation));
 
+                // Operators parameter should match containing type. For example, implementing:
+                // interface I { static abstract int operator -(I x); }
+                // in a class called C should result in:
+                // class C : I { public static int operator -(C x) {}
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction_Method.cs:97]:
```suggestion
                // class C : I { public static int operator -(C x) { } }
```

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction_Method.cs (hunk 2 above)
Comment (Youssef1313) [reply src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction_Method.cs:73]: 1. Probably not :smile: I believe things are more complicated than what I've here, specifically for generics (I'm actually not able to implement the non-generic version :smile: see https://github.com/dotnet/roslyn/issues/53927#issuecomment-856699046).
2. Sure.

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction_Method.cs (hunk 3 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction_Method.cs:97]: also, this is a bit interesting from a covariant parameter type perspective.   It honestly seems a bit odd.  Given this, i could have a binary operator like `public static I operator +(I i1, I i2)`.  However, we'll instantiate that as `public static C operator +(C i1, C i2)`.  

Would i then be able to call this with two potentially different I's that were not both C's at runtmie?

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction_Method.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction_Method.cs]: place in different file please.

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction_Method.cs (hunk 2 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction_Method.cs:73]: the symbolvisitor seems overkill since we're not recurisng past return-type/parameter.  seems like we could just have a simple method that accomplishes the same.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi This is ready for another look :)

File: src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs [hunk 4]
```diff
@@ -8984,5 +8984,122 @@ public int Foo
 }
 ", parseOptions: CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.CSharp5));
         }
+
+        [WorkItem(53927, "https://github.com/dotnet/roslyn/issues/53927")]
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsImplementInterface)]
+        public async Task TestStaticAbstractInterfaceOperator_OnlyExplicitlyImplementable()
+        {
+            await TestInRegularAndScriptAsync(@"
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs:8992]: in the future, if your'e interested, it would be good to update these to be sdk style tests.  that way we can validate if our fix produces errors :)

File: src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs [hunk 5]
```diff
@@ -8984,5 +8984,122 @@ public int Foo
...
+",
+@"
+interface ITest<T> where T : ITest<T>
+{
+    static abstract int operator -(T x);
+}
+
+abstract class C : ITest<C>
+{
+    public abstract static int operator -(C x);
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs:9100]: i'm curious.  is this legal?

File: src/Workspaces/CSharp/Portable/CodeGeneration/OperatorGenerator.cs [hunk 6]
```diff
@@ -86,23 +87,36 @@ internal static class OperatorGenerator
...
+            {
+                tokens.Add(SyntaxFactory.Token(SyntaxKind.PublicKeyword));
+            }
+
+            if (method.IsAbstract)
+            {
+                tokens.Add(SyntaxFactory.Token(SyntaxKind.AbstractKeyword));
+            }
+
+            tokens.Add(SyntaxFactory.Token(SyntaxKind.StaticKeyword));
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/CodeGeneration/OperatorGenerator.cs:118]: i would expect static to come before abstract.  But i guess we have no precedence.  How are these ordered in our default modifiers list?

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/INamedTypeSymbolExtensions.cs [hunk 7]
```diff
@@ -226,6 +227,20 @@ static bool IsNonPublicImplementableAccessor(IMethodSymbol? accessor)
             {
                 return accessor != null && IsImplementable(accessor) && accessor.DeclaredAccessibility != Accessibility.Public;
             }
+
+            static bool IsImplicitlyImplementable(ISymbol member, ISymbol within)
+            {
+                if (member is IMethodSymbol { IsStatic: true, IsAbstract: true } method)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/INamedTypeSymbolExtensions.cs:233]: do we only need to do this test for operators?  i suppose by filtering down to statics though, that's enough.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/INamedTypeSymbolExtensions.cs [hunk 8]
```diff
@@ -226,6 +227,20 @@ static bool IsNonPublicImplementableAccessor(IMethodSymbol? accessor)
...
+                {
+                    // For example, the following is not implementable implicitly.
+                    // interface I { static abstract int operator -(I x); }
+                    // But the following is implementable:
+                    // interface I<T> where T : I<T> { static abstract int operator -(T x); }
+                    return method.Parameters.Any(p => p.Type.Equals(within, SymbolEqualityComparer.Default));
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/INamedTypeSymbolExtensions.cs:239]: since this is .Any, can you add tests for binary operators where only one side is the right type, and the other is some other type?  You might want to also link to the section of the spec that requires that.

**Review by CyrusNajmabadi — COMMENTED** [review]
Overall this looks good.  Just some tiny questions/cleanup/requests.

File: src/Workspaces/CSharp/Portable/CodeGeneration/OperatorGenerator.cs (hunk 6 above)
Comment (sharwell) [reply src/Workspaces/CSharp/Portable/CodeGeneration/OperatorGenerator.cs:118]: `static` comes before `abstract`

File: src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs (hunk 5 above)
Comment (AlekseyTs) [reply src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs:9100]: Abstract statics are allowed only in interfaces

File: src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs (hunk 4 above)
Comment (sharwell) [reply src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs:8992]: 📝 I'm working on this change for ImplementInterfaceTests in a separate branch.

File: src/Workspaces/CSharp/Portable/CodeGeneration/OperatorGenerator.cs (hunk 6 above)
Comment (Youssef1313) [reply src/Workspaces/CSharp/Portable/CodeGeneration/OperatorGenerator.cs:118]: Note to self: MethodGenerator may need to adjust the order too:

https://github.com/dotnet/roslyn/blob/781dab82c6cc8a6e0d04e66bcbacf04ab16e2e91/src/Workspaces/CSharp/Portable/CodeGeneration/MethodGenerator.cs#L240-L253

File: src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs (hunk 5 above)
Comment (Youssef1313) [reply src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs:9100]: Thanks for noting @CyrusNajmabadi @AlekseyTs 
I'm curious whether the "Implement interface abstractly" should do nothing for the operator, or generate it without the "abstract" keyword?

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/INamedTypeSymbolExtensions.cs (hunk 7 above)
Comment (Youssef1313) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/INamedTypeSymbolExtensions.cs]: Fixed.

File: src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs (hunk 5 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs]: implement abstractly needs to take the code from uncompilable state to compilable, attempting for each member it *needs to* generate to make that abstract.  If the member doesn't need to be generated, we should not generate it.

**Comment by AlekseyTs** [comment]
Note that https://github.com/dotnet/roslyn/tree/features/StaticAbstractMembersInInterfaces has been merged to main, all related PRs should target main at this point.

File: src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs (hunk 5 above)
Comment (Youssef1313) [reply src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs]: @CyrusNajmabadi The member needs to be generated to be in a compilable state, but it cannot be generated abstractly.

Comment (AlekseyTs) [reply src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs]: I do not believe there is away to implement a static member abstractly. So, if there are static abstract members in the interface, the option probably shouldn't be offered.

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs [hunk 9]
```diff
@@ -309,7 +309,7 @@ private string DetermineMemberName(ISymbol member, ArrayBuilder<ISymbol> impleme
                 var generateInvisibleMember = GenerateInvisibleMember(member, memberName);
                 memberName = generateInvisibleMember ? member.Name : memberName;
 
-                var generateAbstractly = !generateInvisibleMember && Abstractly;
+                var generateAbstractly = !member.IsStatic && !generateInvisibleMember && Abstractly;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs:312]: possibly explicitly comment that the language doesn't allow static abstract impls of interface methods.

File: src/Workspaces/CSharp/Portable/CodeGeneration/OperatorGenerator.cs [hunk 10]
```diff
@@ -86,23 +87,37 @@ internal static class OperatorGenerator
...
             return operatorDecl;
         }
 
-        private static SyntaxTokenList GenerateModifiers()
+        private static SyntaxTokenList GenerateModifiers(IMethodSymbol method)
         {
-            return SyntaxFactory.TokenList(
-                SyntaxFactory.Token(SyntaxKind.PublicKeyword),
-                SyntaxFactory.Token(SyntaxKind.StaticKeyword));
+            var tokens = ArrayBuilder<SyntaxToken>.GetInstance();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/CodeGeneration/OperatorGenerator.cs:106]:
```suggestion
            using var tokens = TemporaryArray<SyntaxToken>.Empty;
```

Comment (CyrusNajmabadi) [reply src/Workspaces/CSharp/Portable/CodeGeneration/OperatorGenerator.cs:106]: TemporaryArray is nice when we expect 4 or less items commonly :)

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/Workspaces/CSharp/Portable/CodeGeneration/OperatorGenerator.cs (hunk 10 above)
Comment (Youssef1313) [reply src/Workspaces/CSharp/Portable/CodeGeneration/OperatorGenerator.cs]: Nice to know about TemporaryArray! Thanks. I applied the change.

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs (hunk 9 above)
Comment (Youssef1313) [reply src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs:314]: Added comment.

**Comment by Youssef1313** [comment]
CI failure is unrelated and was fixed in `main`. Closing and reopening for new build.

**Comment by CyrusNajmabadi** [comment]
Thanks!
