### PR TITLE
Suggest interfaces after generic type name

### LINKED ISSUE #70382: Interfaces not in autocompletion list after generic type
**Version Used**: VS 17.8 Preview 3

**Steps to Reproduce**:
Invoke autocomplete at the marked locations:

```csharp
interface I
{
    I M();
}

interface I<T>
{
    I<T> M();
}

class C<T> : I, I<T>
{
    I $$;
    I<T> $$;
}
```

**Expected Behavior**: The interfaces are in the completion list in both cases.

**Actual Behavior**: In the first case, both interfaces are in the completion list. In the second case, neither interface is in the completion list.

### PR DESCRIPTION
**Pull request by jhinder**
Fixes #70382.

### CODE REVIEW

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceTypeCompletionProvider.cs [hunk 1]
```diff
@@ -75,7 +75,13 @@ public override async Task ProvideCompletionsAsync(CompletionContext context)
             if (SyntaxFacts.GetContextualKeywordKind(targetToken.ValueText) == SyntaxKind.AsyncKeyword)
                 return SpecializedTasks.EmptyImmutableArray<SymbolAndSelectionInfo>();
 
-            var typeNode = targetToken.Parent as TypeSyntax;
+            var potentialTypeNode = targetToken.Parent;
+            while (potentialTypeNode is TypeArgumentListSyntax typeArgumentList)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceTypeCompletionProvider.cs:79]: why do you need the while look?

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceTypeCompletionProvider.cs:79]: can you ensure that  this only happens when the target token is the `>` token.

Comment (jhinder) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceTypeCompletionProvider.cs:79]: It could also be an `if` because the target token is always the right-most closing angled bracket, so the immediate parent will always be the GenericNameSyntax, right?

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceTypeCompletionProvider.cs:79]: that seems sensible to me :)

Comment (jhinder) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceTypeCompletionProvider.cs]: Converted to `if` and added a check for the `>` token.

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceTypeCompletionProvider.cs [hunk 2]
```diff
@@ -75,7 +75,13 @@ public override async Task ProvideCompletionsAsync(CompletionContext context)
             if (SyntaxFacts.GetContextualKeywordKind(targetToken.ValueText) == SyntaxKind.AsyncKeyword)
                 return SpecializedTasks.EmptyImmutableArray<SymbolAndSelectionInfo>();
 
-            var typeNode = targetToken.Parent as TypeSyntax;
+            var potentialTypeNode = targetToken.Parent;
+            if (targetToken.IsKind(SyntaxKind.GreaterThanToken) && potentialTypeNode is TypeArgumentListSyntax typeArgumentList)
+            {
+                potentialTypeNode = typeArgumentList.Parent;
+            }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceTypeCompletionProvider.cs:82]:
```suggestion
                potentialTypeNode = typeArgumentList.Parent;
```

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Review by genlu — APPROVED** [review]
