### PR TITLE
Fix FAR counting for target-typed new

### LINKED ISSUE #47987: Target typed new - bug with constructor reference counting
**Version Used**: 
VS 16.8 latest

**Steps to Reproduce**:
Bug can be reproduced in a minimal console project. Just add code like this:

Bug triggers if some class "Foo" has any field initializer with target typed new syntax, like "Bar bar1 = new();" in the example. 

This field initializer somehow messes up reference counting in the "Foo" constructor body, so all of the constructor references are counted twice (one for new, one for identifier name, check highlights in the screenshot).  

Double counting ceases immediately after field initializer "Bar bar1 = new();" is replaced with the old syntax "Bar bar = new Bar();"

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #47987

Counting implicit object creations was depending on whether the whole document **contains** any implicit object creations or not.
That caused normal object creations to count as implicit when the document contains implicit creations. So, the normal object creations were counted twice.

### CODE REVIEW

File: src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs [hunk 1]
```diff
@@ -637,6 +637,11 @@ static bool IsRelevantDocument(SyntaxTreeIndex syntaxTreeInfo)
             void CollectMatchingReferences(ISymbol originalUnreducedSymbolDefinition, SyntaxNode node,
                 ISyntaxFactsService syntaxFacts, ISemanticFactsService semanticFacts, ArrayBuilder<FinderLocation> locations)
             {
+                if (syntaxFacts.IsImplicitObjectCreation(node))
```
Comment (Youssef1313) [inline src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/AbstractReferenceFinder.cs:640]: @jcouv In 

https://github.com/dotnet/roslyn/pull/43645/files#diff-aeace626a93e2448b1aec4bc466c9931R336-R337

I see you introduced an extension method called "IsImplicitObjectCreationExpression". So I'm not sure whether I should use `IsImplicitObjectCreation` instance method, or `IsImplicitObjectCreationExpression`, and why we need the two?

**Review by Youssef1313 — COMMENTED** [review]
The method `FindReferencesInImplicitObjectCreationExpressionAsync` is currently in `AbstractReferenceFinder.cs`. I think it makes more sense to move it as a private method to `ConstructorSymbolReferenceFinder.cs`.

I can't see a reason why to make it in `AbstractReferenceFinder` while its friend is in `ConstructorSymbolReferenceFinder`:

https://github.com/dotnet/roslyn/blob/bc85a40ac042f9cf799f5e43deb0fee2d595247b/src/Workspaces/Core/Portable/FindSymbols/FindReferences/Finders/ConstructorSymbolReferenceFinder.cs#L107

If you agree, I'll fix that.

**Review by Youssef1313 — COMMENTED** [review]
Note 2:

`FindReferencesInImplicitObjectCreationExpressionAsync` currently returns a `Task`, while `FindOrdinaryReferencesAsync` returns a `ValueTask`.

I'm not sure if there is a performance benefit if both are returning a `ValueTask`. It worth having a look.

**Comment by sharwell** [comment]
Blocked on #48401 that we are taking for 16.8

**Comment by sharwell** [comment]
@Youssef1313 No we can keep the test in the master branch. I was fixing a performance issue for 16.8 and it just happens to have the same root cause as this.

**Comment by Youssef1313** [comment]
> No we can keep the test in the master branch.

@sharwell Thanks. I'm keeping it in master.

There does seem to be test failures here related to the FAR feature. Can you please re-run the failed job to see whether it's a consistent failure or just flaky?

I can't currently debug this because of some weird errors I'm getting in Visual Studio:

image

I tried to restart Visual Studio a couple of times, but every time I just get a different weird error.

**Comment by CyrusNajmabadi** [comment]
Already has PR to fix in: https://github.com/dotnet/roslyn/pull/48402 :)

**Review by CyrusNajmabadi — CHANGES_REQUESTED** [review]
Thanks for the PR, however this is something Sam and I already have fixes for.  https://github.com/dotnet/roslyn/pull/48402

Sorry for any time wasted.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi No problem at all! Closing as duplicate.

**Comment by Youssef1313** [comment]
The bug is already fixed, but I re-opened to add the test to prevent regressions while refactoring in the future.

**Comment by Youssef1313** [comment]
> Blocked on #48401 that we are taking for 16.8. Keeping this PR open since the test is still helpful.

@sharwell This is no longer blocked as your PR is now merged..

**Review by sharwell — APPROVED** [review]

**Comment by Youssef1313** [comment]
@CyrusNajmabadi This is a test only change. Can you please review?

**Review by sharwell — APPROVED** [review]
