### PR TITLE
Avoid several breaking changes in overload resolution from inferred types of lambda expressions and method groups

### LINKED ISSUE #55691: Overload resolution fails in complex scenario with Delegate overloads and extension methods
**Version Used**: 
Version 17.0.0 Preview 4.0 [31616.459.main]

**Steps to Reproduce**:

```C#
var app = new WebApp();

app.Map("/sub", builder =>
{
    builder.UseAuth();
});


class WebApp : IAppBuilder, IRouteBuilder
{
    public void UseAuth()
    {
        
    }
}

public interface IAppBuilder
{
    void UseAuth();
}

public interface IRouteBuilder
{

}

static class AppBuilderExtensions
{
    public static IAppBuilder Map(this IAppBuilder app, PathSring path, Action<IAppBuilder> callback) => app;
}

public static class RouteBuilderExtensions
{
    public static IRouteBuilder Map(this IRouteBuilder routes, string path, Delegate callback) => routes;
}

struct PathSring
{
    public PathSring(string? path)
    {
        Path = path;
    }

    public string? Path { get; }

    public static implicit operator PathSring(string? s) => new PathSring(s);

    public static implicit operator string?(PathSring path) => path.Path;
}
```

**Expected Behavior**:

AppBuilderExtensions.Map would be chosen by the overload resolution algorithm.

**Actual Behavior**:

The call is ambiguous between the following methods or properties: 'AppBuilderExtensions.Map(IAppBuilder, PathSring, Action<IAppBuilder>)' and 'RouteBuilderExtensions.Map(IRouteBuilder, string, Delegate)'	C:\Users\david\source\repos\ConsoleApp133\WebApplication1\Program.cs

It seems like the implicit conversion on `PathString` throws off the overload resolution completely. If `PathString` is replaced with string, it works as expected.

cc @cston

### LINKED ISSUE #56167: .NET 6 RC 1: changes to overload resolution? Breaks NUnit?
**Version Used**: 

```
> dotnet --version
6.0.100-rc.1.21452.4
```

**Steps to Reproduce**:

1. Unzip this somewhere: [repro.zip](https://github.com/dotnet/roslyn/files/7106561/repro.zip)
2. `dotnet build` fails with:

```
Program.cs(3,8): error CS0121: The call is ambiguous between the following methods or properties: 'Assert.That(TestDelegate, IResolveConstraint)' and 'Assert.That<TActual>(TActual, IResolveConstraint)'
```

3. If you uncomment `<LangVersion>9.0</LangVersion>` it works.

The problematic method is NUnit:

```csharp
Assert.That(() => { }, Throws.Nothing);
```

We hit this in .NET MAUI here:

https://github.com/dotnet/maui/pull/2369

The breaking change might be expected. The part that is concerning, is we had some unit tests fail at runtime due to a similar issue, where changing `LangVersion=9.0` fixed the test failure:

https://github.com/dotnet/maui/blob/f22a61ac027bb115a115a0f493c97ba0c98fa3e8/src/Core/tests/UnitTests/LifecycleEvents/LifecycleEventsTests.cs#L119-L136

I thought it might be worth checking into, thanks!

**Expected Behavior**:

NUnit `Assert.That(() => { }, Throws.Nothing);` compiles in C# 10?

**Actual Behavior**:

NUnit `Assert.That(() => { }, Throws.Nothing);` doesn't compile under C# 10.

### LINKED ISSUE #56319: Ambigious call in PLinq Aggregate method due to C#10 lambda type inference
**Version Used**:  4.0.0-5.21453.15 (2bbf85ba)

**Steps to Reproduce**:

1. Compile https://github.com/dotnet/runtime/blob/91f43669bbd6bdf1ba760a6eaa4e42c2794c5f08/src/libraries/System.Linq.Parallel/tests/QueryOperators/AggregateTests.cs 

**Expected Behavior**: No errors.

**Actual Behavior**:

```
AggregateTests.cs(320,59): error CS0121: The call is ambiguous between the following methods or properties: 'ParallelEnumerable.Aggregate<TSource, TAccumulate, TResult>(ParallelQuery<TSource>, Func<TAccumulate>, Func<TAccumulate, TSource, TAccumulate>, Func<TAccumulate, TAccumulate, TAccumulate>, Func<TAccumulate, TResult>)' and 'ParallelEnumerable.Aggregate<TSource, TAccumulate, TResult>(ParallelQuery<TSource>, TAccumulate, Func<TAccumulate, TSource, TAccumulate>, Func<TAccumulate, TAccumulate, TAccumulate>, Func<TAccumulate, TResult>)' [/Users/alexander/dev/runtime/src/libraries/System.Linq.Parallel/tests/System.Linq.Parallel.Tests.csproj]
AggregateTests.cs(333,93): error CS0121: The call is ambiguous between the following methods or properties: 'ParallelEnumerable.Aggregate<TSource, TAccumulate, TResult>(ParallelQuery<TSource>, Func<TAccumulate>, Func<TAccumulate, TSource, TAccumulate>, Func<TAccumulate, TAccumulate, TAccumulate>, Func<TAccumulate, TResult>)' and 'ParallelEnumerable.Aggregate<TSource, TAccumulate, TResult>(ParallelQuery<TSource>, TAccumulate, Func<TAccumulate, TSource, TAccumulate>, Func<TAccumulate, TAccumulate, TAccumulate>, Func<TAccumulate, TResult>)' [/Users/alexander/dev/runtime/src/libraries/System.Linq.Parallel/tests/System.Linq.Parallel.Tests.csproj]
AggregateTests.cs(338,97): error CS0121: The call is ambiguous between the following methods or properties: 'ParallelEnumerable.Aggregate<TSource, TAccumulate, TResult>(ParallelQuery<TSource>, Func<TAccumulate>, Func<TAccumulate, TSource, TAccumulate>, Func<TAccumulate, TAccumulate, TAccumulate>, Func<TAccumulate, TResult>)' and 'ParallelEnumerable.Aggregate<TSource, TAccumulate, TResult>(ParallelQuery<TSource>, TAccumulate, Func<TAccumulate, TSource, TAccumulate>, Func<TAccumulate, TAccumulate, TAccumulate>, Func<TAccumulate, TResult>)' [/Users/alexander/dev/runtime/src/libraries/System.Linq.Parallel/tests/System.Linq.Parallel.Tests.csproj]
AggregateTests.cs(360,103): error CS0121: The call is ambiguous between the following methods or properties: 'ParallelEnumerable.Aggregate<TSource, TAccumulate, TResult>(ParallelQuery<TSource>, Func<TAccumulate>, Func<TAccumulate, TSource, TAccumulate>, Func<TAccumulate, TAccumulate, TAccumulate>, Func<TAccumulate, TResult>)' and 'ParallelEnumerable.Aggregate<TSource, TAccumulate, TResult>(ParallelQuery<TSource>, TAccumulate, Func<TAccumulate, TSource, TAccumulate>, Func<TAccumulate, TAccumulate, TAccumulate>, Func<TAccumulate, TResult>)' [/Users/alexander/dev/runtime/src/libraries/System.Linq.Parallel/tests/System.Linq.Parallel.Tests.csproj]
AggregateTests.cs(362,119): error CS0121: The call is ambiguous between the following methods or properties: 'ParallelEnumerable.Aggregate<TSource, TAccumulate, TResult>(ParallelQuery<TSource>, Func<TAccumulate>, Func<TAccumulate, TSource, TAccumulate>, Func<TAccumulate, TAccumulate, TAccumulate>, Func<TAccumulate, TResult>)' and 'ParallelEnumerable.Aggregate<TSource, TAccumulate, TResult>(ParallelQuery<TSource>, TAccumulate, Func<TAccumulate, TSource, TAccumulate>, Func<TAccumulate, TAccumulate, TAccumulate>, Func<TAccumulate, TResult>)' [/Users/alexander/dev/runtime/src/libraries/System.Linq.Parallel/tests/System.Linq.Parallel.Tests.csproj]
AggregateTests.cs(363,121): error CS0121: The call is ambiguous between the following methods or properties: 'ParallelEnumerable.Aggregate<TSource, TAccumulate, TResult>(ParallelQuery<TSource>, Func<TAccumulate>, Func<TAccumulate, TSource, TAccumulate>, Func<TAccumulate, TAccumulate, TAccumulate>, Func<TAccumulate, TResult>)' and 'ParallelEnumerable.Aggregate<TSource, TAccumulate, TResult>(ParallelQuery<TSource>, TAccumulate, Func<TAccumulate, TSource, TAccumulate>, Func<TAccumulate, TAccumulate, TAccumulate>, Func<TAccumulate, TResult>)' [/Users/alexander/dev/runtime/src/libraries/System.Linq.Parallel/tests/System.Linq.Parallel.Tests.csproj]
```

@CyrusNajmabadi asked me to open an issue for discussion.

/cc @333fred  @cston

### PR DESCRIPTION
**Pull request by cston**
Update "[better function member](https://github.com/dotnet/csharplang/blob/main/spec/expressions.md#better-function-member)" to prefer members where none of the conversions and none of the type arguments involved inferred types from lambda expressions or method groups.

> #### Better function member
> ...
> Given an argument list `A` with a set of argument expressions `{E1, E2, ..., En}` and two applicable function members `Mp` and `Mq` with parameter types `{P1, P2, ..., Pn}` and `{Q1, Q2, ..., Qn}`, `Mp` is defined to be a ***better function member*** than `Mq` if
>
> 1. **for each argument, the implicit conversion from `Ex` to `Px` is not a _function_type_conversion_, and**
>    *  **`Mp` is a non-generic method or `Mp` is a generic method with type parameters `{X1, X2, ..., Xp}` and for each type parameter `Xi` the type argument is inferred from an expression or from a type other than a _function_type_, and**
>    *  **for at least one argument, the implicit conversion from `Ex` to `Qx` is a _function_type_conversion_, or `Mq` is a generic method with type parameters `{Y1, Y2, ..., Yq}` and for at least one type parameter `Yi` the type argument is inferred from a _function_type_, or**
> 2. for each argument, the implicit conversion from `Ex` to `Qx` is not better than the implicit conversion from `Ex` to `Px`, and for at least one argument, the conversion from `Ex` to `Px` is better than the conversion from `Ex` to `Qx`.

Update "[better conversion from expression](https://github.com/dotnet/csharplang/blob/main/spec/expressions.md#better-conversion-from-expression)" to prefer conversions that did not involve inferred types from lambda expressions or method groups.

> #### Better conversion from expression
> 
> Given an implicit conversion `C1` that converts from an expression `E` to a type `T1`, and an implicit conversion `C2` that converts from an expression `E` to a type `T2`, `C1` is a ***better conversion*** than `C2` if:
> 1. **`C1` is not a _function_type_conversion_ and `C2` is a _function_type_conversion_, or**
> 2. `E` is a non-constant _interpolated\_string\_expression_, `C1` is an _implicit\_string\_handler\_conversion_, `T1` is an _applicable\_interpolated\_string\_handler\_type_, and `C2` is not an _implicit\_string\_handler\_conversion_, or
> 3. `E` does not exactly match `T2` and at least one of the following holds:
>     * `E` exactly matches `T1` ([Exactly matching Expression](../../spec/expressions.md#exactly-matching-expression))
>     * `T1` is a better conversion target than `T2` ([Better conversion target](../../spec/expressions.md#better-conversion-target))

The changes resolve several breaking changes between C#9 and C#10.

Fixes #55691
Fixes #56167
Fixes #56319

Relates to test plan #52192

### CODE REVIEW

**Comment by jcouv** [comment]
Regarding the proposed spec change:

> a conversion from the inferred type of an anonymous method or a method group

Can this be simplified to "a function type conversion"?

Similarly, we can use the "function type" label as a shorthand in the third group. 
Merging the bullets to reflect top-level OR with 3 groups.

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs [hunk 1]
```diff
@@ -67,17 +67,20 @@ internal static class PooledDictionaryIgnoringNullableModifiersForReferenceTypes
     }
 
     // Method type inference can fail, but we still might have some best guesses. 
-    internal struct MethodTypeInferenceResult
+    internal readonly struct MethodTypeInferenceResult
     {
         public readonly ImmutableArray<TypeWithAnnotations> InferredTypeArguments;
+        public readonly bool InferredFromFunctionType;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs:73]: nit: Consider adding a comment here and in `MemberResolutionResult`
nit: Consider aligning names between those two structures (`TypeArgumentsFromFunctionType` here?)

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs [hunk 2]
```diff
@@ -276,7 +279,7 @@ private enum Dependency
             // Early out: if the method has no formal parameters then we know that inference will fail.
             if (formalParameterTypes.Length == 0)
             {
-                return new MethodTypeInferenceResult(false, default(ImmutableArray<TypeWithAnnotations>));
+                return new MethodTypeInferenceResult(false, default, false);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MethodTypeInference.cs:282]: nit: consider naming arguments

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs [hunk 3]
```diff
@@ -2449,6 +2464,16 @@ private BetterResult BetterConversionFromExpression(BoundExpression node, TypeSy
                 }
             }
 
+            switch ((conv1.Kind, conv2.Kind))
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:2467]: The proposed spec changes covers "better function member" and is implemented by `BetterFunctionMember` above. But I don't a spec change for better conversion from expression. I think this change is sensible, but let's spec it too.

File: src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs [hunk 4]
```diff
@@ -2333,10 +2333,175 @@ static void Main()
...
-            CompileAndVerify(source, parseOptions: TestOptions.Regular9, expectedOutput: "M(Action<string> a)");
+            var expectedOutput = "M(Action<string> a)";
+            CompileAndVerify(source, parseOptions: TestOptions.Regular9, expectedOutput: expectedOutput);
+            CompileAndVerify(source, parseOptions: TestOptions.Regular10, expectedOutput: expectedOutput);
+            CompileAndVerify(source, expectedOutput: expectedOutput);
+        }
+
+        [WorkItem(4674, "https://github.com/dotnet/csharplang/issues/4674")]
+        [Fact]
+        public void OverloadResolution_01A()
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs:2344]: consider adding one more variation on this: `void M<T>(T, Func<object>)` vs. `void M<T>(Func<object>, T)` (remains error)

File: src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs [hunk 5]
```diff
@@ -2333,10 +2333,175 @@ static void Main()
...
+M<T>(T x, T y)
+";
+            CompileAndVerify(source, parseOptions: TestOptions.Regular9, expectedOutput: expectedOutput);
+            CompileAndVerify(source, parseOptions: TestOptions.Regular10, expectedOutput: expectedOutput);
+            CompileAndVerify(source, expectedOutput: expectedOutput);
+        }
+
+        [WorkItem(4674, "https://github.com/dotnet/csharplang/issues/4674")]
+        [Fact]
+        public void OverloadResolution_01D()
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs:2432]: Could we add a variant of this scenario with `M<T, U>(Func<T>, U)` versus `M<T, U>(T, U)`? I think it will be ambiguous, but may be worth discussing (should we keep a per-argument rule like before rather than adding an aggregate rule where any function type conversion means "worse"?)

File: src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs [hunk 6]
```diff
@@ -2762,20 +2927,8 @@ public PathSring(string? path)
...
-                Diagnostic(ErrorCode.ERR_AmbigCall, "Map").WithArguments("AppBuilderExtensions.Map(IAppBuilder, PathSring, System.Action<IAppBuilder>)", "RouteBuilderExtensions.Map(IRouteBuilder, string, System.Delegate)").WithLocation(8, 5)
-            };
-
-            var comp = CreateCompilation(source, parseOptions: TestOptions.Regular10);
-            comp.VerifyDiagnostics(expectedDiagnostics10AndLater);
-
-            comp = CreateCompilation(source);
-            comp.VerifyDiagnostics(expectedDiagnostics10AndLater);
+            CompileAndVerify(source, parseOptions: TestOptions.Regular10);
+            CompileAndVerify(source);
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs:2931]: Let's verify which overload got picked

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 9)

**Comment by jcouv** [comment]
This PR fixes a few recently opened issues. I think https://github.com/dotnet/roslyn/issues/56167 is one of them

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 3 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:2467]: I haven't found a case where this change is still needed so I've removed it.

File: src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs [hunk 7]
```diff
@@ -3007,126 +3223,401 @@ static void Main()
...
+                Diagnostic(ErrorCode.ERR_BadArgType, "F").WithArguments("1", "method group", "System.Linq.Expressions.Expression").WithLocation(10, 11),
+                // (11,11): error CS1660: Cannot convert lambda expression to type 'Expression' because it is not a delegate type
+                //         M(() => 1);
+                Diagnostic(ErrorCode.ERR_AnonMethToNonDel, "() => 1").WithArguments("lambda expression", "System.Linq.Expressions.Expression").WithLocation(11, 11));
+
+            var expectedDiagnostics = new[]
+            {
+                // (10,11): error CS0428: Cannot convert method group 'F' to non-delegate type 'Expression'. Did you intend to invoke the method?
+                //         M(F);
+                Diagnostic(ErrorCode.ERR_MethGrpToNonDel, "F").WithArguments("F", "System.Linq.Expressions.Expression").WithLocation(10, 11)
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs:3573]: Ideally, overload resolution should choose `M(object)` rather than `M(Expression)`.

File: src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs [hunk 8]
```diff
@@ -4997,7 +5488,256 @@ static void Main()
...
+        _ = b + (() => 2);
+    }
+}";
+
+            CompileAndVerify(source, parseOptions: TestOptions.Regular9, expectedOutput:
+@"operator+(A a, Func<int> f)
+operator+(A a, Func<int> f)
+");
+
+            // Breaking change from C#9.
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs:5734]: Let's update the breaking change doc along with this and review that we've documented other breaks we've accepted. Could be done in a separate PR, but feels like it would fit well along with this.

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 12)

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs [hunk 9]
```diff
@@ -1701,10 +1684,18 @@ private static ParameterSymbol GetParameter(int argIndex, MemberAnalysisResult r
             {
                 return hasAnyRefOmittedArgument1 ? BetterResult.Right : BetterResult.Left;
             }
-            else
+
+            // Prefer overloads that did not use the inferred type of lambdas or method groups
+            // to infer generic method type arguments or to convert arguments.
+            switch (RequiredFunctionType(m1), RequiredFunctionType(m2))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:1690]: >switch (RequiredFunctionType(m1), RequiredFunctionType(m2)) [](http://example.com/codeflow?start=12&length=59)

It feels like this should be the first thing this function does.

File: src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs [hunk 10]
```diff
@@ -3007,126 +3223,401 @@ static void Main()
...
-    static void F(Delegate d) => Console.WriteLine(""F(Delegate d)"");
-    static void F(Func<object> f) => Console.WriteLine(""F(Func<int> f)"");
+    static void M(Expression e) { Console.WriteLine(""M(Expression e)""); }
+    static void M(object o) { Console.WriteLine(""M(object o)""); }
+    static int F() => 0;
     static void Main()
     {
-        F(() => 1);
+        M(F);
+        M(() => 1);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs:3556]: >M(() => 1); [](http://example.com/codeflow?start=8&length=11)

Do we have a test verifying which overload is called here in C# 10?

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 12).

File: src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs [hunk 11]
```diff
@@ -2441,6 +2678,41 @@ static class E
...
+    public void M(Expression e) { Console.WriteLine(""C.M""); }
+}
+static class E
+{
+    public static void M(this object o, Func<int> a) { Console.WriteLine(""E.M""); }
+}";
+
+            CompileAndVerify(source, parseOptions: TestOptions.Regular9, expectedOutput: @"E.M");
+
+            // Breaking change from C#9 which binds to E.M.
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs:2708]: >Breaking change from C#9 which binds to E.M. [](http://example.com/codeflow?start=15&length=44)

This break needs to be considered.

Comment (jcouv) [reply src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs:2708]: I didn't understand the comment. This seems the break we've already accepted (ie. bullet 2 in doc above, scenario where extension ends up losing)

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 15)

File: src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs (hunk 11 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs:2708]: The argument in this case is a method group so ideally the `Expression` overload should be ignored.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs:2708]: > The argument in this case is a method group so ideally the Expression overload should be ignored.

Quite possibly this is an unrelated issue, but this feels like a bug. Why the Expression candidate is considered applicable?

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 16) with a possible follow up on the breaking change thread.

File: src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs (hunk 11 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/DelegateTypeTests.cs]: Discussed in [https://github.com/dotnet/csharplang/blob/main/meetings/2021/LDM-2021-09-20.md#method-groups-converting-to-expression](https://github.com/dotnet/csharplang/blob/main/meetings/2021/LDM-2021-09-20.md#method-groups-converting-to-expression)

File: docs/compilers/CSharp/Compiler Breaking Changes - DotNet 6.md [hunk 12]
```diff
@@ -6,4 +6,104 @@
     {
         if (o is null!) {} // error
     }
-    ```
\ No newline at end of file
+    ```
+
+2. In C# 10, lambda expressions and method groups with inferred type are implicitly convertible to `System.MulticastDelegate`, and bases classes and interfaces of `System.MulticastDelegate` including `object`,
+and lambda expressions are implicitly convertible to `System.Linq.Expressions.Expression` and `System.Linq.Expressions.LambdaExpression`.
```
Comment (jcouv) [inline docs/compilers/CSharp/Compiler Breaking Changes - DotNet 6.md:12]: >lambda expressions [](http://example.com/codeflow?start=4&length=18)

I'd suggest saying "lambda expressions and method groups" here, and convert bullet 3 to be bullet 2c.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 21) with a suggestion to consolidate breaking change bullet 3 into breaking change bullet 2.

File: docs/compilers/CSharp/Compiler Breaking Changes - DotNet 6.md [hunk 13]
```diff
@@ -6,4 +6,104 @@
...
+    using System;
+
+    class Program
+    {
+        static void F(Func<Func<object>> f, int i) { }
+        static void F(Func<Func<int>> f, object o) { }
+
+        static void Main()
+        {
+            F(() => () => 1, 2); // C#9: ok; C#10: ambiguous
```
Comment (AlekseyTs) [inline docs/compilers/CSharp/Compiler Breaking Changes - DotNet 6.md:106]: >ok [](http://example.com/codeflow?start=41&length=2)

"Ok" doesn't really explain the previous behavior. What overload is chosen?

File: docs/compilers/CSharp/Compiler Breaking Changes - DotNet 6.md [hunk 14]
```diff
@@ -6,4 +6,104 @@
...
+    using System;
+
+    class Program
+    {
+        static void F(Func<Func<object>> f, int i) { }
+        static void F(Func<Func<int>> f, object o) { }
+
+        static void Main()
+        {
+            F(() => () => 1, 2); // C#9: F(Func<Func<object>>, int); C#10: ambiguous
```
Comment (AlekseyTs) [inline docs/compilers/CSharp/Compiler Breaking Changes - DotNet 6.md:106]: > // C#9: F(Func<Func<object>>, int); C#10: ambiguous [](http://example.com/codeflow?start=32&length=52)

This behavior change feels unexpected to me, perhaps we should follow up on it.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 23)

File: docs/compilers/CSharp/Compiler Breaking Changes - DotNet 6.md (hunk 14 above)
Comment (cston) [reply docs/compilers/CSharp/Compiler Breaking Changes - DotNet 6.md:106]: [https://github.com/dotnet/roslyn/issues/56623](https://github.com/dotnet/roslyn/issues/56623)

**Comment by cston** [comment]
> I wonder if this change is worth a mention in dotnet/core#6570.

Thanks @jnm2, I've added an entry there.
