### PR TITLE
Fix LSP semantic tokens algorithm

### LINKED ISSUE #54671: Semantic tokens edits handler returns incorrect deltas
**Version Used**: 
Visual Studio 16.10 Int Preview
Visual Studio 17.0 Int Preview

**Steps to Reproduce**:

- Create a simple C# app like this:

image

- Enable the 'experimental C#/VB editor' Preview Feature
image

- Repeated type SPACE, then BACKSPACE, quickly at ---> fo|r (...

**Expected Behavior**:

Colors are updated asynchronously and catch up with any edits the user makes.

**Actual Behavior**:

- Various tokens can end up off by one.
- Large edits can end up with significant color corruption, such as off-by-entire-word in several places.
- Cases that don't have _visible_ impact, the LSP client is recovering by detecting tokens past the end of the line and doing an expensive re-request/re-draw of the entire view.

image

**Net Impact**

- Local: shouldn't really be impacted, because this feature flag is not enabled locally.
- LiveShare guest: isn't _currently_ impacted because of [a hack I put in place](https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient?path=%2Fsrc%2Fproduct%2FRemoteLanguage%2FImpl%2FFeatures%2FSemanticTokens%2FTagger%2FSemanticTokensDocumentClassificationTagger.cs&version=GBdevelop&line=251&lineEnd=261&lineStartColumn=1&lineEndColumn=14&lineStyle=plain&_a=contents) to work around a similar versioning issue in LiveShare. A prototype of the fix exists but was never funded to be fixed.
- ASP.NET Razor: making edits to lines containing C# can corrupt Razor document token positions. There's at least one feedback ticket about this: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1349853
- Looks like this is a missed case of #45427

### PR DESCRIPTION
**Pull request by allisonchou**
This PR primarily accomplishes two tasks:

1) Overhauls the existing LSP semantic tokens edits processing algorithm to align with [Razor's](https://github.com/dotnet/aspnetcore-tooling/blob/main/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/SemanticTokensEditsDiffer.cs) (shoutout to Ryan and the rest of the Razor team for writing the original 😄). The main change here is going from calculating edits per token (i.e. five ints) to per int. The updated algorithm is much more efficient than our previous algorithm, and returns less edits back to the LSP client.

2) The interpretation of Roslyn's LongestCommonSubstring algorithm, which we use to calculate raw edits, was missing a critical piece. Namely, for insertions, we need to keep track of _where_ we should be inserting into the original token set. We don't keep track of this in the existing implementation, resulting in bugs such as #54671.

Resolves #54671

### CODE REVIEW

File: src/Workspaces/Core/Portable/Differencing/SequenceEdit.cs [hunk 1]
```diff
@@ -18,40 +18,26 @@ internal struct SequenceEdit : IEquatable<SequenceEdit>
...
-                return EditKind.Update;
-            }
-        }
+        public EditKind Kind => _kind;
 
         /// <summary>
-        /// Index in the old sequence, or -1 if the edit is insert.
+        /// Index in the old sequence.
         /// </summary>
         public int OldIndex => _oldIndex;
```
Comment (tmat) [inline src/Workspaces/Core/Portable/Differencing/SequenceEdit.cs:42]: >OldIndex [](http://example.com/codeflow?start=19&length=8)

What is the exact semantics of OldIndex value for Insert?

Say I have sequences: (a, b, b, c) and (a, c, x). 
Is the OldIndex of insert of x expected to be 4?

**Review by tmat — CHANGES_REQUESTED** [review]
:clock1:

File: src/Workspaces/Core/Portable/Differencing/SequenceEdit.cs (hunk 1 above)
Comment (tmat) [reply src/Workspaces/Core/Portable/Differencing/SequenceEdit.cs:42]: Setting OldIndex on Insert edit seems unnecessary as it can be easily inferred from the Update operation that precedes it. 

For the above example the edits will be:

U[0,0], D[1], D[2], U[3,1], D[4], I[2], U[5,3].

The last Update before I[2] is U[3,1]. Depending on whether you want to count deletes or not the desired "old index" for I is either 5 or 4 (4 + 1, 3 + 1)

File: src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs [hunk 2]
```diff
@@ -100,239 +100,99 @@ public SemanticTokensEditsHandler(SemanticTokensCache tokensCache)
...
-
-                var deleteCount = 5 * (1 + (endEditNumber - startEditIndex));
-                semanticTokensEdits.Add(
-                    GenerateEdit(start: editStartPosition, deleteCount: deleteCount, data: Array.Empty<int>()));
-                return endEditNumber;
-            }
+                        break;
+                    case EditKind.Insert:
+                        if (editInProgress != null &&
+                            editInProgress.Data != null &&
```
[the remark this answers is not in the document]
Comment (allisonchou) [reply src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs:144]: While I agree verifying all the fields isn't ideal, I'm a little worried about clarity if we switch over to using names like `RoslynSemanticTokensInsertEdit` and `RoslynSemanticTokensDeleteEdit`. With the way the edits are currently processed, technically a `RoslynSemanticTokensInsertEdit` could (but not always) contain both insertions and deletions. But a `RoslynSemanticTokenDeleteEdit` would only be able to contain deletions. So the naming seems a bit weird, but I can't think of better alternatives unless you have any ideas?

File: src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/SemanticTokensEditsTests.cs [hunk 3]
```diff
@@ -114,14 +114,17 @@ public async Task TestGetSemanticTokensEdits_ReturnMinimalEdits()
...
-            var expectedEdit = SemanticTokensEditsHandler.GenerateEdit(
-                start: 0, deleteCount: 5,
+            var expectedEdit = GenerateEdit(
+                start: 2, deleteCount: 0,
                 data: new int[]
                 {
-                    0, 0, 5, SemanticTokensCache.TokenTypeToIndex[LSP.SemanticTokenTypes.Keyword], 0,
-                    1, 0, 10, SemanticTokensCache.TokenTypeToIndex[LSP.SemanticTokenTypes.Comment], 0
+                    // 'class'
+                    /* 0, 0, */ 5, SemanticTokensCache.TokenTypeToIndex[LSP.SemanticTokenTypes.Keyword], 0,
```
[the remark this answers is not in the document]
Comment (allisonchou) [reply src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/SemanticTokensEditsTests.cs:125]: Ah, so this was actually intentional. Since we're switching over to computing edits by int now instead of by token, I thought it might be helpful to show where the inserted individual ints are located in relation to other ints. So for example, in the test above we can see that the new four new inserted ints make up the end of the `class` token and the beginning of the `// Comment` token. If you think this makes things more confusing, I don't mind removing it

File: src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/SemanticTokensEditsTests.cs [hunk 4]
```diff
@@ -42,7 +42,7 @@ static class C { }";
 
             var results = await RunGetSemanticTokensEditsAsync(testLspServer, caretLocation, previousResultId: "1");
 
-            var expectedEdit = SemanticTokensEditsHandler.GenerateEdit(start: 5, deleteCount: 1, data: new int[] { 2 });
+            var expectedEdit = GenerateEdit(start: 5, deleteCount: 1, data: new int[] { 2 });
```
[the remark this answers is not in the document]
Comment (allisonchou) [reply src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/SemanticTokensEditsTests.cs:46]: Good idea, added!

File: src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/SemanticTokensEditsTests.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (dibarbet) [reply src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/SemanticTokensEditsTests.cs:125]: Ah I see, I think as-is is fine!

File: src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (dibarbet) [reply src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs:144]: Ah I see, since deletion can modify the inprogress insertion.  thats fair!

**Review by dibarbet — APPROVED** [review]

File: src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs [hunk 5]
```diff
@@ -100,239 +100,102 @@ public SemanticTokensEditsHandler(SemanticTokensCache tokensCache)
...
-                int startEditIndex,
-                int editStartPosition)
-            {
-                var _ = ArrayBuilder<int>.GetInstance(out var tokensToInsert);
-
-                // For simplicitly, we only allow an "update" (i.e. a dual insertion/deletion) to be
-                // combined with other updates.
-                var endEditIndex = GetCombinedEditEndIndex(
-                    SemanticTokenEditKind.Update, indexToEditKinds, editIndices, startEditIndex);
+                        if (editInProgress != null &&
```
Comment (CyrusNajmabadi) [inline src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs:127]: i would def apprecaite some commetns on this.

File: src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs [hunk 6]
```diff
@@ -100,239 +100,102 @@ public SemanticTokensEditsHandler(SemanticTokensCache tokensCache)
...
+                            editInProgress.Start + editInProgress.DeleteCount == edit.OldIndex)
+                        {
+                            editInProgress.DeleteCount += 1;
```
Comment (CyrusNajmabadi) [inline src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs:130]:
```suggestion
                            editInProgress.DeleteCount++;
```

?

File: src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs [hunk 7]
```diff
@@ -100,239 +100,102 @@ public SemanticTokensEditsHandler(SemanticTokensCache tokensCache)
...
+                                Start = insertIndex,
+                                Data = new List<int>
+                                {
+                                    newSemanticTokens[edit.NewIndex],
+                                },
+                                DeleteCount = 0,
+                            };
+
+                            results.Add(semanticTokensEdit);
+                        }
```
Comment (CyrusNajmabadi) [inline src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs:163]: same.  comments would be good :)

File: src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs [hunk 8]
```diff
@@ -343,53 +206,23 @@ public static IEnumerable<SequenceEdit> GetEdits(SemanticToken[] oldSemanticToke
...
-            {
-                tokensToInsert.Add(_deltaLine);
-                tokensToInsert.Add(_deltaStartCharacter);
-                tokensToInsert.Add(_length);
-                tokensToInsert.Add(_tokenType);
-                tokensToInsert.Add(_tokenModifiers);
-            }
+            public int Start { get; set; }
+            public int DeleteCount { get; set; }
+            public IList<int>? Data { get; set; }
```
Comment (CyrusNajmabadi) [inline src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs:215]: def doc these fields.

Comment (CyrusNajmabadi) [reply src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs:215]: can this be a struct instead of a calss?

File: src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/AbstractSemanticTokensTests.cs [hunk 9]
```diff
@@ -104,5 +104,13 @@ protected static async Task VerifyNoMultiLineTokens(TestLspServer testLspServer,
                     $"The token ends at index {currentChar + tokenLength}, which exceeds the line length of {lineLength}.");
             }
         }
+
+        protected static LSP.SemanticTokensEdit GenerateEdit(int start, int deleteCount, int[] data)
```
Comment (CyrusNajmabadi) [inline src/Features/LanguageServer/ProtocolUnitTests/SemanticTokens/AbstractSemanticTokensTests.cs:108]: this method seems unnecessary.  seems equivalent to just `new SemanticTOkensEdit { ... }`

**Review by tmat — APPROVED** [review]
:shipit:

File: src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs (hunk 8 above)
Comment (allisonchou) [reply src/Features/LanguageServer/Protocol/Handler/SemanticTokens/SemanticTokensEditsHandler.cs:242]: I _think_ unless this makes more sense as a class, since I believe in a struct we can't modify the value of `DeleteCount` without creating an entirely new struct. (If I'm wrong, please let me know. 🙂)

**Comment by allisonchou** [comment]
Thanks everyone for the reviews!

@CyrusNajmabadi I'm going to merge this to get it in early for P4 dogfooding. If you have any additional feedback, I can address them in a follow-up PR.
