### PR TITLE
Fix unit test deadlocks

### LINKED ISSUE #7825: Roslyn.Services.Editor.CSharp.UnitTests periodically asserts and hangs the unit tests
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/2555/console

`[xUnit] [ERROR] - The result file 'd:\j\workspace\roslyn_prtest_win_dbg_unit64\Binaries\Debug\xUnitResults\Roslyn.Services.Editor.CSharp.UnitTests.dll.xml' for the metric 'xUnit.Net' is empty. The result file has been skipped.`

I remember seeing one yesterday as well.  I'll add a link if I can find it.

Bounty

### PR DESCRIPTION
**Pull request by jaredpar**
There are runs on Jenkins where the IDE is failing the assertions of running on the foreground / background thread.  This causes an exception to be emitted and generally fails the resulting test.  In the case of this bug though the exception was causing the test to deadlock due to this particular call.

http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/Classification/SyntacticClassificationTaggerProvider.TagComputer.cs,203

``` csharp
_notificationService.RegisterNotification(() =>
    {
        _workQueue.AssertIsForeground();
        ReportChangedSpan(snapshot.GetFullSpan());
    },
    ReportChangeDelayInMilliseconds,
    _listener.BeginAsyncOperation("ReportEntireFileChanged"),
    _reportChangeCancellationSource.Token);
```

Here the callback throws due to the failed foreground check.  The implementation of RegisterNotification wasn't properly hardened to ensure `IAsyncToken` was disposed in the face of an exception.  This caused that particular token to never complete and deadlocked the unit tests.

closes #7825

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-ide

**Comment by jaredpar** [comment]
Filed #10121 to fix the root cause bug.

**Comment by jaredpar** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/5619/
// Retest reason:

File: src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs [hunk 1]
```diff
@@ -139,6 +147,15 @@ private void NotifyOnForegroundWorker()
...
                             // eat up cancellation
                         }
+                        catch (Exception ex) when (FatalError.ReportWithoutCrash(ex))
+                        {
+                            // The PendingWork callbacks should never throw.  In the case they do we
+                            // must ensure the IAsyncToken implementation is completed.  If it is not
+                            // then the unit test code will end up in a deadlock doing an 'await' 
+                            // on the token instance.
+                            Debug.Assert(false, ex.Message);
+                            done = true;
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs]: This line seems unnecessary.  done is set to true at hte top.  It is only set to false if DoWorkFunc returns true.  But in that case, we didn't throw, and we wouldn't get here.

**Comment by CyrusNajmabadi** [comment]
```
_notificationService.RegisterNotification(() =>
    {
        _workQueue.AssertIsForeground();
        ReportChangedSpan(snapshot.GetFullSpan());
    },
```
This is terrifying.  If we registered to get called back on the foreground, and we don't get called back on the foreground, then we have a *serious* issue.

**Comment by Pilchie** [comment]
:+1:

File: src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs (hunk 1 above)
Comment (jaredpar) [inline src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs]: @CyrusNajmabadi agree it's unlikely for it to be `false` here.  Pedantically `Enqueue` or `UpdateToLocalTime` could throw in which case we'd end up here with a `done == false`.  Given the trouble it took to find this deadlock I err'd on the side of over cautious here + future proofing.  Can remove if desired.

**Comment by jaredpar** [comment]
@CyrusNajmabadi agree it's disturbing this is happening.  Once we get this change in this error should start showing up directly and we can get better data on why.

**Comment by jaredpar** [comment]
@roslyn-ide can I get one more sign off?

File: src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs [hunk 2]
```diff
@@ -139,6 +147,15 @@ private void NotifyOnForegroundWorker()
                         {
                             // eat up cancellation
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs]: Wouldn't we also need the token to be completed here too?

Comment (jaredpar) [inline src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs]: @jasonmalinowski which token?

File: src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs [hunk 3]
```diff
@@ -139,6 +147,15 @@ private void NotifyOnForegroundWorker()
...
                         }
+                        catch (Exception ex) when (FatalError.ReportWithoutCrash(ex))
+                        {
+                            // The PendingWork callbacks should never throw.  In the case they do we
+                            // must ensure the IAsyncToken implementation is completed.  If it is not
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs]: Two issues with this:

1. The code now can't decide if it's trying to ensure we cleanly recover from this state or not. The comment says "callbacks should never throw", but we're now trying to clean up which means we're sure expecting it. Should we just ReportWithCrash() this? It seems easier and safer than us trying to march along in a state we clearly never considered.
2. The comment seems off to me: it's not just unit tests that will get screwed up by this. You're calling out a very specific symptom here of a very large problem. This feels like saying "we need to make sure there's gas in the car, because it's important to keep the low fuel light off." Sure, yeah, that's one thing it fixes, but not the only one...

File: src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs (hunk 2 above)
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs]: Oh sorry, misread. I was thinking there was an async token around here somewhere in this method.

File: src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs (hunk 3 above)
Comment (jaredpar) [inline src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs]: @jasonmalinowski if the IDE would prefer to crash here I'm very okay with that.  My change is an attempt to keep the existing semantics in place where throw is dealt with an an non-fatal case

Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs]: If this should never throw, then adding the crash shouldn't hurt the product. Since clearly this statement is vacuously true (:smile:) let's go with an easier change I think. If we continue to choose to not crash, then I'd expect you to add tests that this system properly recovers from exceptions being thrown.

**Comment by jasonmalinowski** [comment]
:+1: as is, but I suspect just crashing would be an easier change since clearly we have no tests that actually ensure that anything works after cancellation. Also @heejaechang might want to look at this PR.

I also don't get the parallel error handling happening in the foreground handling function and the background task. It seems like only one of those should be necessary...

File: src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs (hunk 3 above)
Comment (jaredpar) [inline src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs]: @jasonmalinowski this is the IDE code. My change is a representation of how I believe it should function given the comments and current structure.  If you're asking on how I think it should work then look to this change for guidance.  If you'd prefer it be done another way then please be more definitive.

File: src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs (hunk 2 above)
Comment (heejaechang) [inline src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs]: hmmm I am not sure why it is matter whether this runs from BG or not. InvokeBelowInputPriority should make sure given action run on UI thread.

File: src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs (hunk 3 above)
Comment (heejaechang) [inline src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs]: I am not sure when this is added. 
catch (Exception ex) when (FatalError.ReportWithoutCrash(ex))

it used to crash if there was any exception thrown.
Task.Factory.SafeStartNewFromAsync(ProcessAsync, CancellationToken.None, TaskScheduler.Default);

that catch now eat up the exception?

**Comment by heejaechang** [comment]
is this deadlock issue for unit test or integration test? if it is dead lock case, two question.

1. what FG/BG mean in unit test?
2. unit test used to use its own one so that it doesnt care FG/BG mess. which seems no longer being used. any reason we not using it?
http://source.roslyn.io/#Roslyn.Services.Editor.UnitTests/Workspaces/TestForegroundNotificationService.cs,12

File: src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs (hunk 1 above)
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/ForegroundNotification/ForegroundNotificationService.cs]: Nope.  That seems reasonable.  But i'd appreciate a comment in the code to that effect.  Thanks!
