### PR TITLE
Account for Mutex ctor throwing

### LINKED ISSUE #24124: Error building on Linux
_From @sebastienros on January 8, 2018 17:33_

On Linux only, when building a specific project on Linux with the latest SDK, I get an exception that originates from msbuild.

When using an older SDK the error goes away.

Current installed SDK: `2.2.0-preview1-007866`
SDK that doesn't repro the error: `2.2.0-preview1-007522`

Project to reproduce the issue: https://github.com/aspnet/benchmarks/tree/dev/src/Benchmarks

Logged error
```
Errors
    /tmp/tmpYHoYVk.tmp/l5visbph.cxt/sdk/2.2.0-preview1-007866/Roslyn/Microsoft.CSharp.Core.targets(84,5): error MSB3883: Unexpected exception:  [/tmp/tmpYHoYVk.tmp/nshuithb.5nm/benchmarks/src/Benchmarks/Benchmarks.csproj]
    /tmp/tmpYHoYVk.tmp/l5visbph.cxt/sdk/2.2.0-preview1-007866/Roslyn/Microsoft.CSharp.Core.targets(84,5): System.AggregateException: One or more errors occurred. (The system cannot open the device or file specified) ---> System.IO.IOException: The system cannot open the device or file specified
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at Microsoft.CodeAnalysis.CommandLine.BuildServerConnection.<RunServerCompilationCore>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
---> (Inner Exception #0) System.IO.IOException: The system cannot open the device or file specified
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at Microsoft.CodeAnalysis.CommandLine.BuildServerConnection.<RunServerCompilationCore>d__7.MoveNext()<--- [/tmp/tmpYHoYVk.tmp/nshuithb.5nm/benchmarks/src/Benchmarks/Benchmarks.csproj]

```

I also join the full `msbuild.log`

_Copied from original issue: dotnet/cli#8344_

### PR DESCRIPTION
**Pull request by jaredpar**
This changes the compiler server to be resilient in the face of the
Mutex constructor throwing an exception. It's documented as being able
to throw various exceptions but we never accounted for it. Had a real
world case pop up when using certain Docker containers on Linux.

In the case the Mutex ctor throws an exception just fall back to normal
csc / vbc execution. The build will complete just fine here, it just
won't have the performance boost of the compiler server.

closes #24124

<details><summary>Ask Mode template not completed</summary>

### Customer scenario

What does the customer do to get into this situation, and why do we think this
is common enough to address for this release.  (Granted, sometimes this will be
obvious "Open project, VS crashes" but in general, I need to understand how
common a scenario is)

### Bugs this fixes

(either VSO or GitHub links)

### Workarounds, if any

Also, why we think they are insufficient for RC vs. RC2, RC3, or RTW

### Risk

This is generally a measure our how central the affected code is to adjacent
scenarios and thus how likely your fix is to destabilize a broader area of code

### Performance impact

(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")

### Root cause analysis

How did we miss it?  What tests are we adding to guard against it in the future?

### How was the bug found?

(E.g. customer reported it vs. ad hoc testing)

### Test documentation updated?

If this is a new non-compiler feature or a significant improvement to an existing feature, update https://github.com/dotnet/roslyn/wiki/Manual-Testing once you know which release it is targeting.

</details>

### CODE REVIEW

File: src/Compilers/Shared/BuildServerConnection.cs [hunk 1]
```diff
@@ -118,47 +118,62 @@ internal sealed class BuildServerConnection
...
-                                               createdNew: out var holdsMutex))
+            Mutex clientMutex = null;
+            var holdsMutex = false;
+            try
             {
                 try
                 {
-                    if (!holdsMutex)
+                    var clientMutexName = GetClientMutexName(pipeName);
+                    clientMutex = new Mutex(initiallyOwned: true, name: clientMutexName, out holdsMutex);
```
Comment (jaredpar) [inline src/Compilers/Shared/BuildServerConnection.cs]: Unfortunately I don't have any good ideas on how to test this. No way I can think of to force Mutex ctor to throw an exception here.

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-compiler for review

File: src/Compilers/Shared/BuildServerConnection.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Compilers/Shared/BuildServerConnection.cs]: Why not pass in a mutex indirection?  In standard builds, pass in a simple version that just instantiates and returns "new Mutexes".  In a test, pass in a version that throws.  That's one way we simulate exceptions in IDE tests.

Comment (sharwell) [reply src/Compilers/Shared/BuildServerConnection.cs]: :bulb: I prefer to force the real error to occur by pre-creating a mutex with the same name and using ACLs that will prevent this constructor from accessing it.

Comment (jaredpar) [reply src/Compilers/Shared/BuildServerConnection.cs]: @sharwell like that idea. Have an example I can look at. Been a while since I've done ACLs.

Comment (sharwell) [reply src/Compilers/Shared/BuildServerConnection.cs]: This passes for me on Windows.

```csharp
[Fact]
public void TestMutexACL()
{
    var user = Environment.UserDomainName + "\\" + Environment.UserName;

    using (var outer = new Mutex(true, "SomeName", out bool createdNew))
    {
        Assert.True(createdNew);
        var mutexSecurity = outer.GetAccessControl();
        mutexSecurity.AddAccessRule(new MutexAccessRule(user, MutexRights.FullControl, AccessControlType.Deny));
        outer.SetAccessControl(mutexSecurity);

        Assert.Throws<UnauthorizedAccessException>(() => new Mutex(true, "SomeName", out createdNew));
    }
}
```

File: src/Compilers/Shared/BuildServerConnection.cs [hunk 2]
```diff
@@ -118,47 +118,62 @@ internal sealed class BuildServerConnection
             var clientDir = buildPaths.ClientDirectory;
             var timeoutNewProcess = timeoutOverride ?? TimeOutMsNewProcess;
             var timeoutExistingProcess = timeoutOverride ?? TimeOutMsExistingProcess;
-            var clientMutexName = GetClientMutexName(pipeName);
             Task<NamedPipeClientStream> pipeTask = null;
-            using (var clientMutex = new Mutex(initiallyOwned: true,
```
Comment (333fred) [inline src/Compilers/Shared/BuildServerConnection.cs]: Why not keep the using statement and wrap it in a Try/Finally?

Comment (jaredpar) [reply src/Compilers/Shared/BuildServerConnection.cs]: Assume you meant "try / catch" there. 

I wanted to be very specific about what error I was catching here: the Mutex throwing. Only way to do that was to remove the `using` and use a `try / catch` in this manner.

File: src/Compilers/Shared/BuildServerConnection.cs [hunk 3]
```diff
@@ -118,47 +118,62 @@ internal sealed class BuildServerConnection
...
-                                               name: clientMutexName,
-                                               createdNew: out var holdsMutex))
+            Mutex clientMutex = null;
+            var holdsMutex = false;
+            try
             {
                 try
                 {
-                    if (!holdsMutex)
+                    var clientMutexName = GetClientMutexName(pipeName);
```
Comment (agocke) [inline src/Compilers/Shared/BuildServerConnection.cs]: I think this should go outside of the try-catch. This shouldn't throw, and if it does I think we should get a Watson for it.

File: src/Compilers/Shared/BuildServerConnection.cs [hunk 4]
```diff
@@ -555,12 +570,21 @@ internal static string GetBasePipeName(string compilerExeDirectory)
...
         {
-            Mutex mutex;
-            var open = Mutex.TryOpenExisting(mutexName, out mutex);
-            if (open)
+            try
             {
-                mutex.Dispose();
-                return true;
+                Mutex mutex;
+                var open = Mutex.TryOpenExisting(mutexName, out mutex);
```
Comment (agocke) [inline src/Compilers/Shared/BuildServerConnection.cs]:
```C#
if (Mutex.TryOpenExisting(mutexName, out Mutex mutex))
{
  mutex.Dispose();
  return true;
}
```

File: src/Compilers/Shared/BuildServerConnection.cs (hunk 3 above)
Comment (jaredpar) [reply src/Compilers/Shared/BuildServerConnection.cs]: I put it in here because it limits the scope of the variable name better. But I agree it's not part of the catch.

Dislike having to make trade offs like this. Wish we had more granular exception catch support.

**Comment by jaredpar** [comment]
Responded to feedback.

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-compiler for review

**Comment by sharwell** [comment]
@jaredpar Did you have any luck with the test?

**Comment by jaredpar** [comment]
Yes test worked great. Somehow it didn’t get added to git. Will fix.

**Comment by jaredpar** [comment]
@sharwell figured out my git mistake.

File: src/Compilers/Shared/BuildServerConnection.cs [hunk 5]
```diff
@@ -118,47 +118,62 @@ internal sealed class BuildServerConnection
...
             {
                 try
                 {
-                    if (!holdsMutex)
+                    var clientMutexName = GetClientMutexName(pipeName);
+                    clientMutex = new Mutex(initiallyOwned: true, name: clientMutexName, out holdsMutex);
+                }
+                catch
+                {
+                    // The Mutex constructor can throw in certain cases. One specific example is docker containers
```
[the remark this answers is not in the document]
Comment (jaredpar) [reply src/Compilers/Shared/BuildServerConnection.cs]: @ajaybhargavb it's less important there. 

In the MSBuild task the exception is causing us to completely abandon running csc. That breaks the build. In the server the exception causes the server to crash. That's an expected scenario and the MSBuild task will recover from that and run csc manually. 

I probably should handle it just to exit a bit more gracefully. The result is still the same though: server exits with a non-zero exit code.

File: src/Compilers/Shared/BuildServerConnection.cs (hunk 1 above)
Comment (ajaybhargavb) [reply src/Compilers/Shared/BuildServerConnection.cs]: Looks like the easiest way to make the Mutex constructor throw is to just pass in a name longer that 260 characters.

File: src/Compilers/Server/VBCSCompilerTests/DesktopBuildClientTests.cs [hunk 6]
```diff
@@ -145,6 +146,32 @@ public void ConnectToServerFails()
                 }
             }
 
+#if NET461
```
Comment (jcouv) [inline src/Compilers/Server/VBCSCompilerTests/DesktopBuildClientTests.cs]: Consider adding a comment for the pragma

File: src/Compilers/Shared/BuildServerConnection.cs [hunk 7]
```diff
@@ -118,47 +118,62 @@ internal sealed class BuildServerConnection
...
+                    pipeTask = TryConnectToServerAsync(pipeName, timeout, cancellationToken);
+                }
+            }
+            finally
+            {
+                if (clientMutex != null)
                 {
                     if (holdsMutex)
                     {
                         clientMutex.ReleaseMutex();
```
Comment (AlekseyTs) [inline src/Compilers/Shared/BuildServerConnection.cs]: >clientMutex.ReleaseMutex(); [](start = 24, length = 27)

Can this throw? Should we try/catch around it?

Comment (jaredpar) [reply src/Compilers/Shared/BuildServerConnection.cs]: It can throw but only in cases where there is a programming error: called from wrong thread for example. Want those cases to throw vs. swallowing an error here.
