### PR TITLE
Fix generate event handler with invalid name (#59935)

### LINKED ISSUE #59935: The name of the generated event handler is invalid for generics classes.
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/The-name-of-the-generated-event-handler-/1681517)._

---
I have a class whch is called "MyClass<T>", which has an event "MyEvent"

When I write the following:
MyClass<MyType>. MyEvent +=
and press tab-tab to generate the event handler, it generated the follolwing method:
`MyClass<MyType>_MyEvent` 

Which is invalid and causing a lot of errors in the code.

Visual studio should generate a valid name in this case, too.

---
#### Feedback Bot on 3/3/2022, 00:58 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by maciek231**
Fix #59935

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/EventHookup/EventHookupCommandHandlerTests.cs [hunk 1]
```diff
@@ -1080,6 +1080,31 @@ void CurrentDomain_UnhandledException(object sender, System.UnhandledExceptionEv
...
+        public async Task HandlerName_EventInGenericClass()
+        {
+            var markup = @"
+using System;
+
+class C
+{
+    void M()
+    {
+        Generic&lt;int&gt;.MyEvent +$$
```
Comment (Youssef1313) [inline src/EditorFeatures/CSharpTest/EventHookup/EventHookupCommandHandlerTests.cs:1094]: Can you add a test for `global::Generic<int>.MyEvent`? I'm expecting it to fail.

**Review by Youssef1313 — CHANGES_REQUESTED** [review]

File: src/EditorFeatures/CSharpTest/EventHookup/EventHookupCommandHandlerTests.cs (hunk 1 above)
Comment (Youssef1313) [reply src/EditorFeatures/CSharpTest/EventHookup/EventHookupCommandHandlerTests.cs:1094]: For that, I suggest using this extension method

https://github.com/dotnet/roslyn/blob/31d7f1f7da00ffc8a6aeaf6de97159ee2caa0bae/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ExpressionSyntaxExtensions.cs#L679

Comment (maciek231) [reply src/EditorFeatures/CSharpTest/EventHookup/EventHookupCommandHandlerTests.cs:1094]: Yes, it failed both for generic and non-generic. I added more tests and fix that

**Review by Youssef1313 — APPROVED** [review]

File: src/EditorFeatures/CSharp/EventHookup/EventHookupSessionManager_EventHookupSession.cs [hunk 2]
```diff
@@ -257,19 +257,15 @@ private string GetNameObjectPart(IEventSymbol eventSymbol, SyntaxToken plusEqual
...
+                        // For generic we must exclude type variables
+                        return lhsGenericNameSyntax.Identifier.Text;
                     }
 
-                    if (lhs is NameSyntax lhsNameSyntax)
-                    {
-                        // Even easier -- the LHS of the dot is the name itself
-                        return lhsNameSyntax.ToString();
-                    }
+                    return lhs.ToString();
```
Comment (jasonmalinowski) [inline src/EditorFeatures/CSharp/EventHookup/EventHookupSessionManager_EventHookupSession.cs:268]: GetRightmostName could return null (at least it's annotated as such), does this need a null check? My gut is it seems like you'd need to have something malformed to the left of the period but still somehow have succeeded in binding the event, so that seems like it'd be a difficult thing to achieve.

Comment (Youssef1313) [reply src/EditorFeatures/CSharp/EventHookup/EventHookupSessionManager_EventHookupSession.cs:268]: @jasonmalinowski Nice catch!

But will it really be something malformed? I think it can be null in a completely valid scenario like this?

```
using System;

class C
{
    public event EventHandler MyEvent;
    
    public static C CreateC()
    {
        return new C();
    }
    
    public void M2()
    {
        CreateC().MyEvent +=
    }
}
```

Here `memberAccessExpression.Expression` is InvocationExpressionSyntax where GetRightmostName returns null. We need to fall into `syntaxFactsService` below when it's null, I think.

Comment (jasonmalinowski) [reply src/EditorFeatures/CSharp/EventHookup/EventHookupSessionManager_EventHookupSession.cs:268]: @Youssef1313 Ah right, of course. I was mentally reading through the GetRightmostName() then forgetting that we're passing in the LHS of the original dot, so yeah. If we don't have a test for that case, we should add one regardless,

File: src/EditorFeatures/CSharp/EventHookup/EventHookupSessionManager_EventHookupSession.cs [hunk 3]
```diff
@@ -257,18 +257,17 @@ private string GetNameObjectPart(IEventSymbol eventSymbol, SyntaxToken plusEqual
...
+                    if (lhs is GenericNameSyntax lhsGenericNameSyntax)
                     {
-                        // Okay, cool.  The name we're after is in the RHS of this dot.
-                        return lhsMemberAccessExpression.Name.ToString();
+                        // For generic we must exclude type variables
+                        return lhsGenericNameSyntax.Identifier.Text;
                     }
 
-                    if (lhs is NameSyntax lhsNameSyntax)
+                    if (lhs != null)
```
Comment (DoctorKrolic) [inline src/EditorFeatures/CSharp/EventHookup/EventHookupSessionManager_EventHookupSession.cs:268]: `lhs is not null` maybe

**Review by jasonmalinowski — APPROVED** [review]
Looks great!

**Comment by jasonmalinowski** [comment]
Thanks @maciek231 for the fix!
