### PR TITLE
Remove RemoveUnneededReferences from LamdaRewriter

### LINKED ISSUE #19033: Compiler crash
**Any version below apr 17**: 

```csharp
using System;

namespace ConsoleApp3
{
    class BC { }
    class DC1 : BC { }
    class DC2 : BC { }
    class Program
    {
        static void Main(string[] args)
        {
        }

        private string Q(BC bclass, int n = 0)
        {
            switch (bclass)
            {
                case DC1 mc:

                    string A(BC map)
                    {
                        return "";
                    }

                    string B(BC map) 
                    {
                        switch (map)
                        {
                            case DC1 ne:
                                Action<int> a = _ => B(new DC2());
                                return "";
                            case DC2 b: 
                                return C(b);
                            default:
                                return A(map);
                        }
                    }

                    string C(BC map)
                    {
                        switch (map)
                        {
                            case DC1 me:
                                return n.ToString();
                            default:
                                return "";
                        }
                    }
                    break;

                default:
                    break;
            }

            return "";
        }
    }
}
```

"csc.exe" exited with code -2146232797

### LINKED ISSUE #20577: Compiler (csc) crashes with code of a nested recursive function and different scope access
**Version Used**: 
2.2.0.61624
**Steps to Reproduce**:

1. Paste this code:
```
using System.Linq;

public class Program {
	public static void Main(string[] args) {
		object v;

		void AAA() {
			object BBB(object v2) {
				var a = v;
				((object[])v2).Select(i => BBB(i));
				return null;
			}
		}
	}
}
```
2. Compile

**Expected Behavior**:
Code compiles or fails to compile.
**Actual Behavior**:
Compiler crashes.

### PR DESCRIPTION
**Pull request by agocke**
Currently, the lambda rewriter has an early optimization pass in
analysis that tries to find all local functions that only capture 'this'
and remove references to local functions that do the same. There are two
problems with this approach:

    1) Generally, removing information from the tree is a bad idea
    because it hurts further analysis passes that may have needed that
    information.

    2) The optimization strategy itself is very tricky and has a number
    of complex corner cases. This has lead to bugs, for example #19033.

This PR deletes the current method and adds a new optimization routine
at the end of the analysis, operating on assigned scopes and
environments rather than removing captured variable analysis. The new
optimization is as follows: if we end up with an environment containing
only 'this', the environment can be removed, all containing methods can
be moved to the top-level type, and all environments which capture the
'this' environment can instead directly capture the 'this' parameter.
This produces almost the same results as the previous optimization, but
is easier to validate as an algebraic equivalence.

Fixes #19033
Fixes #20577

### CODE REVIEW

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs [hunk 1]
```diff
@@ -90,24 +182,24 @@ .maxstack  2
   IL_0010:  ldarg.0
   IL_0011:  ldfld      ""int C._x""
   IL_0016:  call       ""void System.Console.WriteLine(int)""
-  IL_001b:  ldloca.s   V_0
-  IL_001d:  call       ""void C.<M>g__L12_0(ref C.<>c__DisplayClass2_0)""
-  IL_0022:  ldarg.0
-  IL_0023:  ldfld      ""int C._x""
-  IL_0028:  call       ""void System.Console.WriteLine(int)""
-  IL_002d:  ret
+  IL_001b:  ldarg.0
```
Comment (khyperia) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs]: It looks like we're storing `this` in both `C.<>c__DisplayClass2_0.<>4__this` as well as the receiver on `C.<M>g__L12_0(ref C.<>c__DisplayClass2_0)`. Is that intended?

(It looks like `C.<M>g__L12_0(ref C.<>c__DisplayClass2_0)` never touches the captured `C C.<>c__DisplayClass2_1.<>4__this`)

File: src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/LocalFunctionTests.cs [hunk 2]
```diff
@@ -123,7 +123,7 @@ int G()
   // Code size        7 (0x7)
   .maxstack  1
   .locals init (int V_0)
-  IL_0000:  ldarg.0
+  IL_0000:  ldarg.1
```
Comment (khyperia) [inline src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/LocalFunctionTests.cs]: I'm guessing the same thing happened here - capturing `this` on both the receiver and a field.

File: src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.Analysis.Tree.cs [hunk 3]
```diff
@@ -119,6 +119,13 @@ public sealed class Closure
 
                 public ClosureEnvironment ContainingEnvironmentOpt;
 
+                /// <summary>
+                /// True if this closure directly or transitively captures 'this' (captures
+                /// a local function which directly or indirectly captures 'this').
+                /// Calculated in <see cref="MakeAndAssignEnvironments"/>.
+                /// </summary>
+                public bool CapturesThis;
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.Analysis.Tree.cs]: Why fields instead of properties? 

Is there ever a case where this can move from `true` to `false`? If not would it make sense to validate this in a prooperty setter?

File: src/Compilers/Core/Portable/InternalUtilities/SetWithInsertionOrder.cs [hunk 4]
```diff
@@ -37,6 +37,27 @@ public bool Add(T value)
...
+                }
+                Add(value);
+            }
+            else
+            {
+                if (!_set.Add(value))
+                {
+                    return false;
+                }
+                _elements.Insert(index, value);
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/InternalUtilities/SetWithInsertionOrder.cs]: Consider the case the `Insert` operation throws because it's invalid. That means `SetWithInsertionOrder` is now in an inconsistent state: `_set` has the value but it's not present in `_elements`. Think we need to guard against this and ensure the data type is consistent in the face of bad `index` values.

File: src/Compilers/Core/Portable/InternalUtilities/SetWithInsertionOrder.cs [hunk 5]
```diff
@@ -57,5 +78,7 @@ public IEnumerator<T> GetEnumerator()
         IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
 
         public ImmutableArray<T> AsImmutable() => _elements.ToImmutableArrayOrEmpty();
+
+        public T this[int i] => _elements[i];
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/InternalUtilities/SetWithInsertionOrder.cs]: Should this be a `ref` return?  I'd think so if `T` is ever a `struct`

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs (hunk 1 above)
Comment (agocke) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs]: Yup, this is a result of a less aggressive optimization. What's going on here is we only eliminate the `this` closure if it captures *only* `this`. But both `x` and `this` are captured in the same scope, so the environment contains both `x` and `this`, thus the optimization doesn't apply. I haven't found a really simple optimization strategy that works for this case, so I didn't do anything extra here.

If you have any suggestions I could incorporate them, though.

File: src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.Analysis.Tree.cs (hunk 3 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.Analysis.Tree.cs]: Sounds good. I can do that.

Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.Analysis.Tree.cs]: In general though why are you preferring fields here over auto-properties? That seems to go against the style of the compiler.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs (hunk 1 above)
Comment (khyperia) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs]: Wait... but it's *also* lowered onto the containing class. I'm not sure why that is - it seems like if we don't optimize the `this` out of the environment, the generated method shouldn't go on the containing class. (And grab the field, instead of the `this` parameter of the generated method, if it needs the original `this`)

Comment (khyperia) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs]: Oh, I think I get it - it *is* by design. We use the generated `this` parameter **when we can**, but the environment may be passed somewhere that we can't use the `this` parameter (such as a lambda placed on the environment class).

File: src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.Analysis.Tree.cs (hunk 3 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.Analysis.Tree.cs]: The original LambdaRewriter was all fields. I was just sticking with the surrounding code style.

Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.Analysis.Tree.cs]: Gotcha.

File: src/Compilers/Core/Portable/InternalUtilities/SetWithInsertionOrder.cs (hunk 5 above)
Comment (agocke) [inline src/Compilers/Core/Portable/InternalUtilities/SetWithInsertionOrder.cs]: ArrayBuilder doesn't (and can't) have a `ref` returning indexer, so this can't be.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs (hunk 1 above)
Comment (agocke) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs]: Right, and finding and ruling out all those corner cases is the tricky bit, so I haven't built up a full technique.

File: src/Compilers/Core/Portable/InternalUtilities/SetWithInsertionOrder.cs [hunk 6]
```diff
@@ -37,6 +37,35 @@ public bool Add(T value)
...
+                    throw new IndexOutOfRangeException();
+                }
+                Add(value);
+            }
+            else
+            {
+                if (!_set.Add(value))
+                {
+                    return false;
+                }
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/InternalUtilities/SetWithInsertionOrder.cs]: Blank line.

File: src/Compilers/Core/Portable/InternalUtilities/SetWithInsertionOrder.cs [hunk 7]
```diff
@@ -37,6 +37,35 @@ public bool Add(T value)
...
+                try
+                {
+                    _elements.Insert(index, value);
+                }
+                catch
+                {
+                    _set.Remove(value);
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/InternalUtilities/SetWithInsertionOrder.cs]: Wanted to give feedback here about writing tests but it seems like we don't have any tests for `SetWithInsertionOrder`.

File: src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.Analysis.Tree.cs [hunk 8]
```diff
@@ -119,6 +119,22 @@ public sealed class Closure
 
                 public ClosureEnvironment ContainingEnvironmentOpt;
 
+                private bool _capturesThis;
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.Analysis.Tree.cs]: Blank line

File: src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.Analysis.Tree.cs [hunk 9]
```diff
@@ -227,6 +191,31 @@ public static void VisitClosures(Scope scope, Action<Scope, Closure> action)
             }
 
             /// <summary>
+            /// Visit all the closures and return true when the <paramref name="func"/> returns
+            /// true. Otherwise, returns false.
+            /// </summary>
+            public static bool CheckClosures(Scope scope, Func<Scope, Closure, bool> func)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.Analysis.Tree.cs]: Is this method used? Can't find a reference in this PR.

File: src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.Analysis.Tree.cs [hunk 10]
```diff
@@ -132,81 +148,29 @@ public void Free()
...
-                        }
-                    }
-                }
+                /// <summary>
+                /// Represents a <see cref="SynthesizedEnvironment"/> that had its environment
+                /// pointer (a local pointing to the environment) captured like a captured
+                /// variable. Assigned in
+                /// <see cref="ComputeLambdaScopesAndFrameCaptures(ParameterSymbol)"/>
+                /// </summary>
+                public bool CapturesParent;
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.Analysis.Tree.cs]: Can this value go to `false` after going to `true`? If so does it make sense to assert?

File: src/Compilers/Core/Portable/InternalUtilities/SetWithInsertionOrder.cs (hunk 7 above)
Comment (agocke) [inline src/Compilers/Core/Portable/InternalUtilities/SetWithInsertionOrder.cs]: 🎉

File: src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.Analysis.Tree.cs (hunk 9 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.Analysis.Tree.cs]: In `InlineThisOnlyEnvironment` when we see if any `ContainingEnvironmentOpt` is non-null.

**Comment by agocke** [comment]
As @khyperia pointed out, there are some situations with this optimization scheme where an instance method may receive a struct environment that also contains a pointer to `this`. For example, the generated code may look like

```csharp
class C
{
    void CallMe() {}

    struct S
    {
        C _c;
        int _x;
    }

    int Lowered(ref S s)
    {
        CallMe();
    }
}
```

You'll notice that in the `Lowered` method, there are two paths to `CallMe` -- one through `S` (`s._c.CallMe()`) and one through the parent class (`this.CallMe()`). In these situations, the lowering always prefers the implicit receiver, if possible.

I've done a quick benchmark of the two options, and here are the results:

```
// * Summary *

BenchmarkDotNet=v0.10.9, OS=Windows 10 Redstone 2 (10.0.15063)
Processor=Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), ProcessorCount=8
Frequency=3515628 Hz, Resolution=284.4442 ns, Timer=TSC
.NET Core SDK=1.1.0
  [Host]     : .NET Core 1.1.2 (Framework 4.6.25211.01), 64bit RyuJIT DEBUG
  DefaultJob : .NET Core 1.1.2 (Framework 4.6.25211.01), 64bit RyuJIT


       Method |      Mean |     Error |    StdDev |
------------- |----------:|----------:|----------:|
 ReceiverCall | 0.0010 ns | 0.0023 ns | 0.0021 ns |
    FieldCall | 0.0215 ns | 0.0242 ns | 0.0215 ns |
```

As you can see, this approach appears to be about 10x faster than going through the field.
