### PR TITLE
Simplify lazy initialization in RazorDocumentServiceProviderWrapper

### LINKED ISSUE #58004: Broken double-checked locking (data race) in RazorDocumentServiceProviderWrapper
**Version Used**: 
dac98b9 (latest commit on the main branch as of this writing), the most recent commit to the document is 0e94007

**Steps to Reproduce**:
The code of [RazorDocumentServiceProviderWrapper](https://github.com/dotnet/roslyn/blob/0e940070b483a1631cb2dd8f86716a8de573c454/src/Tools/ExternalAccess/Razor/RazorDocumentServiceProviderWrapper.cs) is formally incorrect in terms of parallelism. It applies the double-checked locking pattern without marking the respective fields as `volatile`.

**Expected Behavior**:
One possible solution is marking the fields `_spanMappingService`, `_excerptService`, and `_documentPropertiesService` as `volatile` to conform to C#'s memory-model.

**Actual Behavior**:
Formally incorrect, see [Exploring the Singleton Design Pattern (docs.microsoft.com)](https://docs.microsoft.com/en-us/previous-versions/msp-n-p/ee817670(v=pandp.10))

### PR DESCRIPTION
**Pull request by sharwell**
Closes #58004

### CODE REVIEW

File: src/Tools/ExternalAccess/Razor/RazorDocumentServiceProviderWrapper.cs [hunk 1]
```diff
@@ -1,27 +1,25 @@
...
 {
     internal sealed class RazorDocumentServiceProviderWrapper : IDocumentServiceProvider, IDocumentOperationService
     {
         private readonly IRazorDocumentServiceProvider _innerDocumentServiceProvider;
-        private readonly object _lock;
 
-        private RazorSpanMappingServiceWrapper? _spanMappingService;
-        private RazorDocumentExcerptServiceWrapper? _excerptService;
-        private RazorDocumentPropertiesServiceWrapper? _documentPropertiesService;
+        private StrongBox<ISpanMappingService?>? _spanMappingService;
```
Comment (sharwell) [inline src/Tools/ExternalAccess/Razor/RazorDocumentServiceProviderWrapper.cs:16]: 📝 `StrongBox<T>` is used because `LazyInitialization.EnsureInitialized` doesn't allow the callback to return `null`. This pattern allows us to cache both the non-null and null results.

**Comment by stephentoub** [comment]
This is now optimistic concurrency, and it's possible two threads could end up concurrently running the delegate, even though only one's result will ever be published and consumed.  If that's ok, LGTM (though I'm not clear on why the StrongBox is needed).

File: src/Tools/ExternalAccess/Razor/RazorDocumentServiceProviderWrapper.cs (hunk 1 above)
Comment (stephentoub) [reply src/Tools/ExternalAccess/Razor/RazorDocumentServiceProviderWrapper.cs:16]: Ah, ok.  Null is considered an initialized result.

Comment (ryzngard) [reply src/Tools/ExternalAccess/Razor/RazorDocumentServiceProviderWrapper.cs:16]: Putting this comment in code would be helpful for future readers :)

**Review by ryzngard — APPROVED** [review]

**Review by NTaylorMullen — APPROVED** [review]
Thank you @sharwell!

File: src/Tools/ExternalAccess/Razor/RazorDocumentServiceProviderWrapper.cs (hunk 1 above)
Comment (sharwell) [reply src/Tools/ExternalAccess/Razor/RazorDocumentServiceProviderWrapper.cs]: ➡️ Now in a comment
