### PR TITLE
Fix further issues with Code Model lifetime management

### LINKED ISSUE #5837: System.InvalidOperationException at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.OnCodeElementCreated
I saw the following exception in my Jenkins [run](http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/308/testReport/junit/Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp/CodeAttributeTests/AddAttributeArgument3/), the failure is unrelated to my change:

```
Failed

Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeAttributeTests.AddAttributeArgument3 (from (empty)) 

MESSAGE:
System.InvalidOperationException : Key already exists in table.

STACK TRACE:
at Microsoft.VisualStudio.LanguageServices.Implementation.Interop.CleanableWeakComHandleTable`2.Add(TKey key, TValue value) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Def\Implementation\Interop\CleanableWeakComHandleTable.cs:line 174
at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.OnCodeElementCreated(SyntaxNodeKey nodeKey, CodeElement element) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Impl\CodeModel\FileCodeModel.cs:line 193
at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeClass.Create(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNodeKey nodeKey, Nullable`1 nodeKind) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Impl\CodeModel\InternalElements\CodeClass.cs:line 31 
at Microsoft.VisualStudio.LanguageServices.CSharp.CodeModel.CSharpCodeModelService.CreateInternalCodeElement(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\CSharp\Impl\CodeModel\CSharpCodeModelService.cs:line 521 
at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.GetOrCreateCodeElement[T](SyntaxNode node) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Impl\CodeModel\FileCodeModel.cs:line 226 
at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.AbstractCodeModelService.CreateInternalCodeAttribute(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Impl\CodeModel\AbstractCodeModelService.cs:line 400 
at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.AbstractCodeModelService.CreateInternalCodeAttributeArgument(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Impl\CodeModel\AbstractCodeModelService.cs:line 506 at Microsoft.VisualStudio.LanguageServices.CSharp.CodeModel.CSharpCodeModelService.CreateInternalCodeElement(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\CSharp\Impl\CodeModel\CSharpCodeModelService.cs:line 502 
at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.AddAttributeArgument(SyntaxNode containerNode, String name, String value, Object position) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Impl\CodeModel\FileCodeModel_CodeGen.cs:line 155 
at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeAttribute.<>c__DisplayClass23_0.<AddArgument>b__0() in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Impl\CodeModel\InternalElements\CodeAttribute.cs:line 150 
at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.EnsureEditor[T](Func`1 action) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Impl\CodeModel\FileCodeModel.cs:line 275 at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeAttribute.AddArgument(String value, Object nameObj, Object position) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Impl\CodeModel\InternalElements\CodeAttribute.cs:line 148 
at EnvDTE80.CodeAttribute2.AddArgument(String Value, Object Name, Object Position) 
at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.AbstractCodeAttributeTests.AddAttributeArgument(CodeAttribute2 codeElement, AttributeArgumentData data) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Test\CodeModel\AbstractCodeAttributeTests.vb:line 55 
at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.AbstractCodeAttributeTests.TestAddAttributeArgument(XElement code, XElement expectedCode, AttributeArgumentData data) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Test\CodeModel\AbstractCodeAttributeTests.vb:line 123 
at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeAttributeTests.AddAttributeArgument3() in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Test\CodeModel\CSharp\CodeAttributeTests.vb:line 639\CodeAttribute.cs:line 150 at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.EnsureEditor[T](Func`1 action) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Impl\CodeModel\FileCodeModel.cs:line 275 
at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeAttribute.AddArgument(String value, Object nameObj, Object position) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Impl\CodeModel\InternalElements\CodeAttribute.cs:line 148 at EnvDTE80.CodeAttribute2.AddArgument(String Value, Object Name, Object Position) at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.AbstractCodeAttributeTests.AddAttributeArgument(CodeAttribute2 codeElement, AttributeArgumentData data) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Test\CodeModel\AbstractCodeAttributeTests.vb:line 55 
at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.AbstractCodeAttributeTests.TestAddAttributeArgument(XElement code, XElement expectedCode, AttributeArgumentData data) in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Test\CodeModel\AbstractCodeAttributeTests.vb:line 123 
at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeAttributeTests.AddAttributeArgument3() in d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\VisualStudio\Core\Test\CodeModel\CSharp\CodeAttributeTests.vb:line 639

```

### LINKED ISSUE #5841: Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeAttributeTests.AddAttributeArgument1 is flaky
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/295/console

Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeAttributeTests.AddAttributeArgument1 [FAIL]
10:13:36         System.InvalidOperationException : Key already exists in table.
10:13:36         Stack Trace:
10:13:36            src\VisualStudio\Core\Def\Implementation\Interop\CleanableWeakComHandleTable.cs(174,0): at Microsoft.VisualStudio.LanguageServices.Implementation.Interop.CleanableWeakComHandleTable`2.Add(TKey key, TValue value)
10:13:36            src\VisualStudio\Core\Impl\CodeModel\FileCodeModel.cs(193,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.OnCodeElementCreated(SyntaxNodeKey nodeKey, CodeElement element)
10:13:36            src\VisualStudio\Core\Impl\CodeModel\InternalElements\CodeClass.cs(31,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeClass.Create(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNodeKey nodeKey, Nullable`1 nodeKind)
10:13:36            src\VisualStudio\VisualBasic\Impl\CodeModel\VisualBasicCodeModelService.vb(563,0): at Microsoft.VisualStudio.LanguageServices.VisualBasic.CodeModel.VisualBasicCodeModelService.CreateInternalCodeElement(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node)
10:13:36            src\VisualStudio\Core\Impl\CodeModel\FileCodeModel.cs(226,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.GetOrCreateCodeElement[T](SyntaxNode node)
10:13:36            src\VisualStudio\Core\Impl\CodeModel\AbstractCodeModelService.cs(400,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.AbstractCodeModelService.CreateInternalCodeAttribute(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node)
10:13:36            src\VisualStudio\Core\Impl\CodeModel\AbstractCodeModelService.cs(506,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.AbstractCodeModelService.CreateInternalCodeAttributeArgument(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node)
10:13:36            src\VisualStudio\VisualBasic\Impl\CodeModel\VisualBasicCodeModelService.vb(538,0): at Microsoft.VisualStudio.LanguageServices.VisualBasic.CodeModel.VisualBasicCodeModelService.CreateInternalCodeElement(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node)
10:13:36            src\VisualStudio\Core\Impl\CodeModel\FileCodeModel_CodeGen.cs(155,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.AddAttributeArgument(SyntaxNode containerNode, String name, String value, Object position)
10:13:36            src\VisualStudio\Core\Impl\CodeModel\InternalElements\CodeAttribute.cs(150,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeAttribute.<>c__DisplayClass23_0.<AddArgument>b__0()
10:13:36            src\VisualStudio\Core\Impl\CodeModel\FileCodeModel.cs(275,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.EnsureEditor[T](Func`1 action)
10:13:36            src\VisualStudio\Core\Impl\CodeModel\InternalElements\CodeAttribute.cs(148,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeAttribute.AddArgument(String value, Object nameObj, Object position)
10:13:36               at EnvDTE80.CodeAttribute2.AddArgument(String Value, Object Name, Object Position)
10:13:36            src\VisualStudio\Core\Test\CodeModel\AbstractCodeAttributeTests.vb(55,0): at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.AbstractCodeAttributeTests.AddAttributeArgument(CodeAttribute2 codeElement, AttributeArgumentData data)
10:13:36            src\VisualStudio\Core\Test\CodeModel\AbstractCodeAttributeTests.vb(123,0): at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.AbstractCodeAttributeTests.TestAddAttributeArgument(XElement code, XElement expectedCode, AttributeArgumentData data)
10:13:36            src\VisualStudio\Core\Test\CodeModel\VisualBasic\CodeAttributeTests.vb(797,0): at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeAttributeTests.AddAttributeArgument1()

### LINKED ISSUE #5868: Disabling test CodeModel\CSharp\FileCodeModelTests.vb due to failures
See e.g.:
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_unit32/64/testReport/junit/Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp/CSharpFileCodeModelTests/AddClass10/

or 

http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/339/console

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes #5868
Fixes #5837
Fixes #5841

* Added another "stress" test that performs 100 operations to catch failures in the element table.
* Addressed problem where CleanableWeakComHandleTable.TryGetValue() might incorrectly return true.
* Fixed issue in FileCodeModel.GetOrCreateCodeElement() where a node key might not be removed from the element table.
* Unskip tests

tagging @dotnet/roslyn-ide, @jaredpar

### CODE REVIEW

File: src/VisualStudio/Core/Def/Implementation/Interop/CleanableWeakComHandleTable.cs [hunk 1]
```diff
@@ -215,7 +215,7 @@ public bool TryGetValue(TKey key, out TValue value)
             if (_table.TryGetValue(key, out handle))
             {
                 value = handle.ComAggregateObject;
-                return true;
+                return value != null;
```
Comment (jaredpar) [inline src/VisualStudio/Core/Def/Implementation/Interop/CleanableWeakComHandleTable.cs]: Should we correspondingly assert `value != null` in the `Add` method?

**Comment by Pilchie** [comment]
:+1:

File: src/VisualStudio/Core/Def/Implementation/Interop/CleanableWeakComHandleTable.cs (hunk 1 above)
Comment (DustinCampbell) [inline src/VisualStudio/Core/Def/Implementation/Interop/CleanableWeakComHandleTable.cs]: Yes, we should throw in that case. I'll add a check.

File: src/VisualStudio/Core/Impl/CodeModel/FileCodeModel.cs [hunk 2]
```diff
@@ -177,7 +177,13 @@ internal DocumentId GetDocumentId()
...
         internal void UpdateCodeElementNodeKey(AbstractKeyedCodeElement keyedElement, SyntaxNodeKey oldNodeKey, SyntaxNodeKey newNodeKey)
         {
-            var codeElement = _codeElementTable.Remove(oldNodeKey);
+            EnvDTE.CodeElement codeElement;
+            if (!_codeElementTable.TryGetValue(oldNodeKey, out codeElement))
+            {
+                throw new InvalidOperationException($"Could not find {oldNodeKey} in Code Model element table.");
+            }
+
+            _codeElementTable.Remove(oldNodeKey);
```
Comment (jaredpar) [inline src/VisualStudio/Core/Impl/CodeModel/FileCodeModel.cs]: I think it's too early and I'm missing the key difference here.  But I can't on the surface see a difference between the old code (which checked for a `null` return from `_codeElementTable.Remove`) and the new code which uses `TryGetValue`.

Comment (DustinCampbell) [inline src/VisualStudio/Core/Impl/CodeModel/FileCodeModel.cs]: The old code didn't check for null. It simply called ```ComAggregate.GetManagedObject(...)``` with the null value it received from ```_codeElement.Remove(...)```, which threw. The change is a bit more significant because I decided to call ```TryGetValue``` and bail out a bit early (with a good message) if ```oldNodeKey``` isn't in the table or doesn't have a code element.

**Comment by jaredpar** [comment]
:+1:

**Comment by DustinCampbell** [comment]
retest this please

**Comment by DustinCampbell** [comment]
test vsi please
