### PR TITLE
Avoid using the main thread within CodeAction.GetOperationsAsync

### LINKED ISSUE #48679: Infinite suggested action never ends.
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1223055/infinite-suggested-action-never-ends.html)._

---
[severity:I'm unable to use this version of Visual Studio] [regression] [worked-in:Visual Studio Community 16.7.6]
Hello,

This happens on visual studio preview 16.8.4 preview 4. I'm using Windows 10 professional 64 bits.
After creating a unit testing and attempting to use the "suggested action" to add a reference to one of my projects, the action never finishes.
This is a .NET Core console application for  .NET 5.0 RC1

---
#### Feedback Bot on 10/15/2020, 08:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by sharwell**
Preview operations are not allowed to use the main thread, but final code fix applications are allowed to as part of the `CodeActionOperation`.

Fixes #48679

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
This is a major design decision we need to discuss.  Up until now, this was explicitly not allowed.  We have to make an explicit decision it we're going to enable features doing this. Note: if we do, it def has positive/negative implications. 

Positives: Features that need to do this now can.  Features that have worked around this (like add-nuget package) can become greatly simplified.  i.e. today, add-nuget-package has two components.  One which does the work of talking ot the UI and populating a backing index.  And the actual analyzer, which can access that index in a free threaded fashion.

Negatives: Features can be written much more haphhazardly, potentially saturating or otherwise impacting the UI thread.  My main concern here is that this can be very hard to track down.  Especially if you end up with N analyzers all smearing the UI thread with tiny bits of work that end up causing hiccoughs. 

Tagging @jasonmalinowski

**Comment by sharwell** [comment]
This fixes a regression introduced by #46725. It was always the case that code actions were allowed to use the main thread, but code action _previews_ were not. This pull request fixes a case where consolidation of the code action application path pushed some main thread work into a section where it was blocked.

Note that "normal" code actions still would be blocked from using the main thread. Using this feature requires a custom `CodeAction` implementation that provides separate behavior for preview and application code paths.

**Comment by jasonmalinowski** [comment]
> It was always the case that code actions were allowed to use the main thread

This is news to me. If somebody was being called _during_ a preview because they don't have separate preview operations, would we have allowed that?

More practically, what is the offending code fix here? Why can't we fix that?

**Comment by jasonmalinowski** [comment]
Why isn't that check just running in the CodeActionOperation, which unambiguously is allowed to be on the UI thread (since that's kinda the point of it.)

**Comment by jasonmalinowski** [comment]
Alright so digging through the sequence of events that got us here for my own edification.

1. It seems when we originally added the CanAddProjectReference code, it was not done through the GetOperations() path but instead we added the back-door mechanism for it: https://github.com/dotnet/roslyn/commit/1dd8ba21d003161b4c9f5199895d05cea69b0a86
2. @dibarbet observed that switching to the UI thread is potentially risky for LSP [here](https://github.com/dotnet/roslyn/pull/46082#discussion_r460325805) so #46431 got filed.
3. https://github.com/dotnet/roslyn/pull/46725 fixed #46431 by removing the backdoor.

@dibarbet what was your original goal in your comment in step 2 above? It seems like we may not be doing filtering via an explicit UI thread thing here, but we're still doing it implicitly and this change is allowing it. So how is this any better? What did #46725 achieve?

**Comment by jasonmalinowski** [comment]
Or perhaps to summarize: it seems like #46725 is what is "forcing" this change to happen and might have violated @CyrusNajmabadi's and my original understanding of this path. I can't speak to why that change was necessary in the first place, but I'm now just as wondering why we aren't reverting that or doing something else entirely.

(My question of why we can't use a custom CodeActionOperation still stands, because this seems pretty heavily bound to VS as it is.)

**Comment by sharwell** [comment]
@jasonmalinowski I'll investigate using a custom CodeActionOperation here

**Comment by jasonmalinowski** [comment]
And one caveat of the Operation of course is it means that the application just silently does nothing late, as opposed to being skipped earlier. So that might be bad in it's own right. At this point the only thing I know is I don't know what experience we're trying to create or what UI thread requirements LSP needs to enforce on this code to really know what the right fix is. I'd say @dibarbet and @CyrusNajmabadi probably should chime in to clarify what we all think the goal is here.

File: src/Features/Core/Portable/AddImport/CodeActions/AssemblyReferenceCodeAction.cs [hunk 1]
```diff
@@ -45,21 +35,82 @@ private async Task<IEnumerable<CodeActionOperation>> ComputeOperationsAsync(bool
...
                 {
-                    var resolvedPath = await ResolvePathAsync(cancellationToken).ConfigureAwait(false);
-                    if (!string.IsNullOrWhiteSpace(resolvedPath))
-                    {
-                        var service = OriginalDocument.Project.Solution.Workspace.Services.GetRequiredService<IMetadataService>();
-                        var reference = service.GetReference(resolvedPath, MetadataReferenceProperties.Assembly);
-                        newProject = newProject.WithMetadataReferences(
-                            newProject.MetadataReferences.Concat(reference));
-                    }
+                    // If this is a preview, just return an ApplyChangesOperation for the updated document
```
[the remark this answers is not in the document]
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/AddImport/CodeActions/AssemblyReferenceCodeAction.cs:40]: i don't love this.  but it does unblock the cirtical hang.  it does mean we might have a situation where we offer afix that doesn't end up working.  but that's far less of a problem than just breaking the IDE.

[the remark this answers is not in the document]
Comment (sharwell) [reply src/Features/Core/Portable/AddImport/CodeActions/AssemblyReferenceCodeAction.cs:40]: I could make the preview show the reference being added with the simple name instead of the resolved path. Would that be preferable?

File: src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs [hunk 2]
```diff
@@ -237,8 +237,22 @@ private static async Task<Document> CleanUpNewLinesAsync(Document document, Text
...
-                progressTracker, cancellationToken: cancellationToken).ConfigureAwait(false);
+            var operations = await codeAction.GetOperationsAsync(cancellationToken).ConfigureAwait(false);
+            Solution newSolution;
+            if (operations.Length == 0)
+            {
+                newSolution = document.Project.Solution;
+            }
+            else if (operations.Length == 1 && operations[0] is ApplyChangesOperation applyChangesOperation)
+            {
+                newSolution = applyChangesOperation.ChangedSolution;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs:248]: why do we need these two branches unrolled here?  wouldn't GetChangedSolutionAsync just do this?

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs:248]: (and, if it doesn't, then please doc why we're special casing tehse two cases here).

**Review by CyrusNajmabadi — APPROVED** [review]
lgtm with some minor docs/explanation.

File: src/Features/Core/Portable/AddImport/CodeActions/AssemblyReferenceCodeAction.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/AddImport/CodeActions/AssemblyReferenceCodeAction.cs:40]: yes.  that would be awesome! :)

File: src/Features/Core/Portable/AddImport/CodeActions/SymbolReference.SymbolReferenceCodeAction.cs [hunk 3]
```diff
@@ -54,8 +54,11 @@ protected override async Task<IEnumerable<CodeActionOperation>> ComputeOperation
             {
                 var updatedDocument = await GetUpdatedDocumentAsync(cancellationToken).ConfigureAwait(false);
 
-                // Defer to subtype to add any p2p or metadata refs as appropriate.
-                return await UpdateProjectAsync(updatedDocument.Project, isPreview, cancellationToken).ConfigureAwait(false);
+                // Defer to subtype to add any p2p or metadata refs as appropriate. If no changes to project references
+                // are necessary, the call to 'UpdateProjectAsync' will return null, in which case we fall back to just
+                // returning the updated document with its text changes.
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/AddImport/CodeActions/SymbolReference.SymbolReferenceCodeAction.cs:59]: thanks.

File: src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs [hunk 4]
```diff
@@ -237,8 +237,35 @@ private static async Task<Document> CleanUpNewLinesAsync(Document document, Text
...
+            // expected to apply the changes by executing the operations in GetOperationsAsync (which may have other
+            // side effects). This code cannot assume the input CodeAction supports GetChangedSolutionAsync, so it first
+            // attempts to apply text changes obtained from GetOperationsAsync. Two forms are supported:
+            //
+            // 1. GetOperationsAsync returns an empty list of operations (i.e. no changes are required)
+            // 2. GetOperationsAsync returns a list of operations, where the first change is an ApplyChangesOperation to
+            //    change the text in the solution, and any remaining changes are deferred computation changes.
+            //
+            // If GetOperationsAsync does not adhere to one of these patterns, the code falls back to calling
+            // GetChangedSolutionAsync since there is no clear way to apply the changes otherwise.
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs:252]: ahh... that sucks. but this makes sense then :)

File: src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs (hunk 2 above)
Comment (sharwell) [reply src/Features/Core/Portable/CodeRefactorings/AddMissingImports/AbstractAddMissingImportsFeatureService.cs:261]: ➡️ Documented both changes in this commit

File: src/Features/Core/Portable/AddImport/CodeActions/AssemblyReferenceCodeAction.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (sharwell) [reply src/Features/Core/Portable/AddImport/CodeActions/AssemblyReferenceCodeAction.cs:40]: I'm going to submit this as a separate follow-up so we can discuss test strategy.
