### PR TITLE
Show hyperlinked diagnostic IDs in Quick Info

### LINKED ISSUE #43728: Show hyperlinked diagnostic ID in Quick Info
**Version Used**: 16.6 Preview 3

**Steps to Reproduce**:

Hover over a diagnostic warning or error in the editor.

**Expected Behavior**:

1. The diagnostic ID should appear with the diagnostic message in Quick Info
2. Clicking the diagnostic ID should navigate to the help link URI for the diagnostic

**Actual Behavior**:

The diagnostic ID is not shown, and it is not possible to navigate to the help link from Quick Info.

### PR DESCRIPTION
**Pull request by sharwell**
Closes #43728

Diagnostics with a help link are hyperlinked:

image

Diagnostics with no help link just show the ID:

image

### CODE REVIEW

**Comment by terrajobst** [comment]
That's interesting! I love that it shows up. I wonder how many people understand that they can interact with the tooltip, but it's a paradigm that VS Code is using and it feels quite natural there.

**Comment by sandyarmstrong** [comment]
@terrajobst I think "Show potential fixes" sets the precedent for VS users.

File: src/EditorFeatures/Core/Implementation/Diagnostics/DiagnosticsSuggestionTaggerProvider.cs [hunk 1]
```diff
@@ -37,16 +39,20 @@ internal partial class DiagnosticsSuggestionTaggerProvider :
...
 
         protected internal override bool IncludeDiagnostic(DiagnosticData diagnostic)
             => diagnostic.Severity == DiagnosticSeverity.Info;
 
-        protected override IErrorTag CreateTag(DiagnosticData diagnostic) =>
-            new ErrorTag(PredefinedErrorTypeNames.HintedSuggestion, diagnostic.Message);
+        protected override IErrorTag CreateTag(DiagnosticData diagnostic)
+            => new ErrorTag(
+                PredefinedErrorTypeNames.HintedSuggestion,
+                CreateToolTipContent(_primaryWorkspace.Workspace, diagnostic));
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/Diagnostics/DiagnosticsSuggestionTaggerProvider.cs:55]: Ditto: why not pass the workspace through?

File: src/EditorFeatures/TestUtilities/QuickInfo/ToolTipAssert.cs [hunk 2]
```diff
@@ -0,0 +1,241 @@
...
+        }
+
+        private static string ContainerToString(object element)
+        {
+            var result = new StringBuilder();
+            ContainerToString(element, "", result);
+            return result.ToString();
+        }
+
+        //Private Shared Function ContainerToString(element As Object) As String
```
Comment (jasonmalinowski) [inline src/EditorFeatures/TestUtilities/QuickInfo/ToolTipAssert.cs:104]: Dead code?

File: src/EditorFeatures/TestUtilities/QuickInfo/ToolTipAssert.cs [hunk 3]
```diff
@@ -0,0 +1,241 @@
...
+
+        private static string GetKnownImageGuid(Guid guid)
+        {
+            foreach (var field in typeof(KnownImageIds).GetFields())
+            {
+                if (!field.IsStatic)
+                    continue;
+
+                var rawValue = field.GetValue(null);
+                var value = rawValue as Guid?;
```
Comment (jasonmalinowski) [inline src/EditorFeatures/TestUtilities/QuickInfo/ToolTipAssert.cs:217]: `Guid?`? Why the nullable? It seems like this changed slightly from the original VB.

File: src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsAdornmentTaggerProvider.cs [hunk 4]
```diff
@@ -46,6 +49,36 @@ internal abstract class AbstractDiagnosticsAdornmentTaggerProvider<TTag> :
             return new TagSpan<TTag>(adjustedSpan, errorTag);
         }
 
+        protected object CreateToolTipContent(Workspace workspace, DiagnosticData diagnostic)
+        {
+            Action navigationAction = null;
+            string tooltip = null;
+            if (workspace is object
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsAdornmentTaggerProvider.cs:56]: #nullable enable?

File: src/EditorFeatures/CSharpTest/Squiggles/ErrorSquiggleProducerTests.cs [hunk 5]
```diff
@@ -122,27 +124,54 @@ void Test()
...
             Assert.Equal(PredefinedErrorTypeNames.Suggestion, second.Tag.ErrorType);
-            Assert.Equal(CSharpAnalyzersResources.Using_directive_is_unnecessary, second.Tag.ToolTipContent);
+            ToolTipAssert.EqualContent(expectedToolTip, second.Tag.ToolTipContent);
             Assert.Equal(82, second.Span.Start);
             Assert.Equal(60, second.Span.Length);
 
+            expectedToolTip = new ContainerElement(
+                ContainerElementStyle.Wrapped,
+                new ClassifiedTextElement(
+                    new ClassifiedTextRun(ClassificationTypeNames.Text, "IDE0049"),
```
Comment (jasonmalinowski) [inline src/EditorFeatures/CSharpTest/Squiggles/ErrorSquiggleProducerTests.cs:168]: Are we able to assert that one of these has a link somewhere?

File: src/EditorFeatures/TestUtilities/QuickInfo/ToolTipAssert.cs (hunk 2 above)
Comment (sharwell) [reply src/EditorFeatures/TestUtilities/QuickInfo/ToolTipAssert.cs:104]: 🤦‍♂️

File: src/EditorFeatures/TestUtilities/QuickInfo/ToolTipAssert.cs (hunk 3 above)
Comment (sharwell) [reply src/EditorFeatures/TestUtilities/QuickInfo/ToolTipAssert.cs:217]: The `as` operator doesn't work with value types. You can either use a nullable value type, or you can use `is` followed by a cast. The original VB code used the latter, but `as` is cleaner in C#.

File: src/EditorFeatures/CSharpTest/Squiggles/ErrorSquiggleProducerTests.cs (hunk 5 above)
Comment (sharwell) [reply src/EditorFeatures/CSharpTest/Squiggles/ErrorSquiggleProducerTests.cs:168]: It is possible to implement this such that the link can be tested.

File: src/EditorFeatures/Core/Implementation/Diagnostics/DiagnosticsSquiggleTaggerProvider.cs [hunk 6]
```diff
@@ -67,7 +71,7 @@ protected override IErrorTag CreateTag(DiagnosticData diagnostic)
                 return null;
             }
 
-            return new ErrorTag(errorType, diagnostic.Message);
+            return new ErrorTag(errorType, CreateToolTipContent(_primaryWorkspace.Workspace, diagnostic));
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/Diagnostics/DiagnosticsSquiggleTaggerProvider.cs:74]: I'll try it out. Hopefully it works because `PrimaryWorkspace` was the worst part of this.

File: src/EditorFeatures/CSharpTest/Squiggles/ErrorSquiggleProducerTests.cs [hunk 7]
```diff
@@ -122,27 +124,54 @@ void Test()
...
                 };
 
+            var diagnosticsAndSpans = await _producer.GetDiagnosticsAndErrorSpans(workspace, analyzerMap);
+
             var spans =
-                (await _producer.GetDiagnosticsAndErrorSpans(workspace, analyzerMap)).Item2
-                    .OrderBy(s => s.Span.Span.Start).ToImmutableArray();
+                diagnosticsAndSpans.Item1
+                    .Zip(diagnosticsAndSpans.Item2, (diagnostic, span) => (diagnostic, span))
+                    .OrderBy(s => s.span.Span.Span.Start).ToImmutableArray();
```
Comment (jasonmalinowski) [inline src/EditorFeatures/CSharpTest/Squiggles/ErrorSquiggleProducerTests.cs:132]: image

File: src/EditorFeatures/Core/Implementation/Diagnostics/DiagnosticsSuggestionTaggerProvider.cs (hunk 1 above)
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/Diagnostics/DiagnosticsSuggestionTaggerProvider.cs:55]: ➡️ Tracking as https://github.com/dotnet/roslyn/pull/43732#discussion_r416973354

File: src/EditorFeatures/CSharpTest/Squiggles/ErrorSquiggleProducerTests.cs (hunk 7 above)
Comment (sharwell) [reply src/EditorFeatures/CSharpTest/Squiggles/ErrorSquiggleProducerTests.cs:132]: I'll see if I can add a fourth one for balance.

File: src/EditorFeatures/CSharpTest/Squiggles/ErrorSquiggleProducerTests.cs (hunk 5 above)
Comment (sharwell) [reply src/EditorFeatures/CSharpTest/Squiggles/ErrorSquiggleProducerTests.cs:170]: Links are now tested

File: src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsAdornmentTaggerProvider.cs (hunk 4 above)
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsAdornmentTaggerProvider.cs:59]: Done

File: src/EditorFeatures/TestUtilities/QuickInfo/ToolTipAssert.cs (hunk 3 above)
Comment (sharwell) [reply src/EditorFeatures/TestUtilities/QuickInfo/ToolTipAssert.cs]: Now simplified a bit (retained this concept though)

File: src/EditorFeatures/TestUtilities/QuickInfo/ToolTipAssert.cs (hunk 2 above)
Comment (sharwell) [reply src/EditorFeatures/TestUtilities/QuickInfo/ToolTipAssert.cs]: Fixed

File: src/EditorFeatures/Core/Implementation/Diagnostics/DiagnosticsSquiggleTaggerProvider.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/Diagnostics/DiagnosticsSquiggleTaggerProvider.cs]: Good suggestion. New way is much cleaner.

**Comment by sharwell** [comment]
@jasonmalinowski Feedback addressed

File: src/EditorFeatures/CSharpTest/Squiggles/ErrorSquiggleProducerTests.cs (hunk 7 above)
Comment (jasonmalinowski) [reply src/EditorFeatures/CSharpTest/Squiggles/ErrorSquiggleProducerTests.cs:134]: @sharwell Good, I was bugged by it not being in proper rhythm.

File: src/EditorFeatures/TestUtilities/QuickInfo/ToolTipAssert.cs [hunk 8]
```diff
@@ -92,6 +95,24 @@ private static void EqualClassifiedTextRun(ClassifiedTextRun expected, Classifie
...
+                Assert.Same(expected.NavigationAction, hyperLink.NavigationAction);
+                var actualTarget = Assert.IsType<QuickInfoHyperLink>(actual.NavigationAction.Target);
+                Assert.Same(actual.NavigationAction, actualTarget.NavigationAction);
+                Assert.Equal(hyperLink, actualTarget);
+            }
+            else
+            {
+                // Cannot validate this navigation action
+                Assert.NotNull(actual.NavigationAction);
+                Assert.IsNotType<QuickInfoHyperLink>(actual.NavigationAction.Target);
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/EditorFeatures/TestUtilities/QuickInfo/ToolTipAssert.cs:114]: We have other actions (`cref` targets) that do not get validated, aside from simply asserting that they are not the same as `href` targets.

File: src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/QuickInfoHyperLink.cs [hunk 9]
```diff
@@ -0,0 +1,59 @@
...
+        }
+
+        internal readonly struct TestAccessor
+        {
+            public static Action CreateNavigationAction(Uri uri)
+            {
+                // The workspace is not validated by tests
+                return new QuickInfoHyperLink(null!, uri).NavigationAction;
+            }
+        }
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/IntelliSense/QuickInfo/QuickInfoHyperLink.cs:57]: I will submit a follow-up pull request to clean this up.

**Comment by sharwell** [comment]
@dotnet/roslyn-compiler I had to fix a nullable annotation in the analyzer driver as part of this pull request. Can you review that?

**Comment by sharwell** [comment]
@dotnet/roslyn-compiler Can I get a second review for the two changed lines?

**Comment by sharwell** [comment]
@dotnet/roslyn-compiler can I get a second review for the two changed lines?
