### PR TITLE
Fix crash, and offer "declare as nullable" for tuple fields

### LINKED ISSUE #46354: 'CSharpDeclareAsNullableCodeFixProvider' encountered an error and has been disabled
**Version Used**: 

```
Microsoft Visual Studio Professional 2019 Preview
Version 16.7.0 Preview 5.0
VisualStudio.16.Preview/16.7.0-pre.5.0+30317.65
Microsoft .NET Framework
Version 4.8.03752
```

**Steps to Reproduce**:

Paste the following code in VS, expand the bulb while caret is on `null` in `t.Item1 = null;`
```
#nullable enable
class Program
{
  static void F1<T>((T, T?) t) where T : class
  {
    if (t.Item2 == null) return;
    t.Item1 = null;
    
    var (a, b) = t;
  }
}
```

**Expected Behavior**:
No exceptions I guess

**Actual Behavior**:
```
System.IndexOutOfRangeException : Index was outside the bounds of the array.
   at Microsoft.CodeAnalysis.CSharp.CodeFixes.DeclareAsNullable.CSharpDeclareAsNullableCodeFixProvider.TryGetDeclarationTypeToFix(SemanticModel model,SyntaxNode node)
   at async Microsoft.CodeAnalysis.CSharp.CodeFixes.DeclareAsNullable.CSharpDeclareAsNullableCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

### PR DESCRIPTION
**Pull request by davidwengier**
Fixes #46354 

This fixes the crash, but also adds support to the fixer for tuple fields.

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/Diagnostics/Nullable/CSharpDeclareAsNullableCodeFixTests.cs [hunk 1]
```diff
@@ -1046,6 +1046,85 @@ public async Task MultipleDeclarator_NoDiagnostic()
 class Program
 {
     string [|s|], s2 = ""hello"";
+}", parameters: s_nullableFeature);
+        }
+
+        [Fact]
+        [WorkItem(46354, "https://github.com/dotnet/roslyn/issues/46354")]
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Diagnostics/Nullable/CSharpDeclareAsNullableCodeFixTests.cs:1053]:
```suggestion
        [Fact, WorkItem(46354, "https://github.com/dotnet/roslyn/issues/46354")]
```

File: src/Features/CSharp/Portable/CodeFixes/Nullable/CSharpDeclareAsNullableCodeFixProvider.cs [hunk 2]
```diff
@@ -219,7 +219,8 @@ private static void MakeDeclarationNullable(SyntaxEditor editor, SemanticModel m
                 {
                     return TryGetParameterTypeSyntax(parameter);
                 }
-                else if (symbol is IFieldSymbol field)
+                // implicitly declared fields don't have DeclaringSyntaxReferences so filter them out
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeFixes/Nullable/CSharpDeclareAsNullableCodeFixProvider.cs:222]: 1.  def don't like comment put above an `else` like this.

File: src/Features/CSharp/Portable/CodeFixes/Nullable/CSharpDeclareAsNullableCodeFixProvider.cs [hunk 3]
```diff
@@ -228,6 +229,24 @@ private static void MakeDeclarationNullable(SyntaxEditor editor, SemanticModel m
                     {
                         return declaration.Type;
                     }
+                    else if (syntax is TupleElementSyntax tupleElement)
+                    {
+                        return tupleElement.Type;
+                    }
+                }
+                // Assigning a tuple field, eg. foo.Item1 = null
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeFixes/Nullable/CSharpDeclareAsNullableCodeFixProvider.cs:237]: same.
