### PR TITLE
Fix symbol info in identifier name in object initializer

### LINKED ISSUE #74348: Gracefully handle incomplete property setter in object initializer
## Version Used
VS 2022 Version 17.10.3
Roslyn 4.10.0 (04fb39164c99c)

Project info
C# 12.0
.NET 8.0

## Steps to Reproduce

```csharp
public class Thing
{
    public int Key { get; set; }
    public string? Value { get; set; }
}

public class Using
{
    public static Thing CreateThing(int key, string? value)
    {
        return new()
        {
            Key = key,
            // $$
        };
    }
}
```

In the code above, place the cursor at `$$`, and type `Value`. Notice that `Value` is not bound to the property of `Thing` and is instead treated as an expression.

Example image:
image

## Expected Behavior

Despite lacking the setter, the member is properly bound.

## Actual Behavior

The part of the object initializer is not handled as a member setter, and so the member appears unbound.

### PR DESCRIPTION
**Pull request by Rekkonnect**
Closes #74348

We now bind simple identifier name expressions as `BoundObjectInitializerMember` when inside an object initializer. Additionally, we also handle `BoundObjectInitializerMember` instances in the nullable walker and consider them as non null.

This approach follows the suggestion by @CyrusNajmabadi to handle this fix in the binder instead of the parser to avoid breaking too many parsing tests in the process.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 1]
```diff
@@ -5767,7 +5806,7 @@ private BoundExpression MakeBadExpressionForObjectCreation(SyntaxNode node, Type
                             if (!hasErrors)
                             {
                                 // TODO: distinct error code for collection initializers?  (Dev11 doesn't have one.)
-                                Error(diagnostics, ErrorCode.ERR_ReadonlyValueTypeInObjectInitializer, leftSyntax, fieldSymbol, fieldSymbol.Type);
+                                Error(diagnostics, ErrorCode.ERR_ReadonlyValueTypeInObjectInitializer, (CSharpSyntaxNode)leftSyntax, fieldSymbol, fieldSymbol.Type);
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:5809]: What is this cast for?

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 2]
```diff
@@ -5954,10 +5993,12 @@ private static void ReportDuplicateObjectMemberInitializers(BoundExpression boun
 
                 var memberInitializerSyntax = boundMemberInitializer.Syntax;
 
-                Debug.Assert(memberInitializerSyntax.Kind() == SyntaxKind.SimpleAssignmentExpression);
-                var namedAssignment = (AssignmentExpressionSyntax)memberInitializerSyntax;
+                var memberNameSyntax = memberInitializerSyntax as IdentifierNameSyntax;
+                if (memberInitializerSyntax is AssignmentExpressionSyntax assignment)
+                {
+                    memberNameSyntax = assignment.Left as IdentifierNameSyntax;
+                }
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:6000]: Feels like we should still be maintaining the original invariants here, just adjusted. For example:
```suggestion
                IdentifierNameSyntax memberNameSyntax;
                if (memberInitializerSyntax is AssignmentExpressionSyntax namedAssignment)
                {
                    Debug.Assert(memberInitializerSyntax.Kind() == SyntaxKind.SimpleAssignmentExpression);
                    memberNameSyntax = namedAssignment.Left as IdentifierNameSyntax;
                }
                else
                {
                    memberNameSyntax = (IdentifierNameSyntax)memberInitializerSyntax;
                }
```

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 3]
```diff
@@ -10953,8 +10953,14 @@ public override void VisitForEachIterationVariables(BoundForEachStatement node)
 
         public override BoundNode? VisitObjectInitializerMember(BoundObjectInitializerMember node)
         {
-            // Should be handled by VisitObjectCreationExpression.
-            throw ExceptionUtilities.Unreachable();
+            // We reach this point when we have just an identifier name in the initializer without an actual
+            // assignment, like "Value"
+            Debug.Assert(node.Syntax.Parent!.Kind() is SyntaxKind.ObjectInitializerExpression,
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:10958]:
```suggestion
            Debug.Assert(node.Syntax.Parent!.IsKind(SyntaxKind.ObjectInitializerExpression),
```

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 4]
```diff
@@ -10953,8 +10953,14 @@ public override void VisitForEachIterationVariables(BoundForEachStatement node)
...
+                "Expected to visit this only in a member initializer with a missing assignment");
+
+            // We cannot perform any analysis here, as we have no real expression assignment or access
+            SetNotNullResult(node);
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:10962]: Arguably that means we should set a `null` result, but I don't think I care that much.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs [hunk 5]
```diff
@@ -7163,49 +7166,51 @@ public B M(int i, int j)
...
+                    CaptureIds: [0]
+                    Block[B1] - Block
+                        Predecessors: [B0]
+                        Statements (5)
+                            IFlowCaptureOperation: 0 (OperationKind.FlowCapture, Type: null, IsImplicit) (Syntax: 'this')
+                              Value:
+                                IInstanceReferenceOperation (ReferenceKind: ContainingTypeInstance) (OperationKind.InstanceReference, Type: B) (Syntax: 'this')
+                            IInvalidOperation (OperationKind.Invalid, Type: ?, IsInvalid, IsImplicit) (Syntax: 'i')
+                              Children(1):
+                                  IOperation:  (OperationKind.None, Type: null, IsInvalid) (Syntax: 'i')
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs:7185]: What is this `NoneOperation` representing?

File: src/Compilers/CSharp/Test/Semantic/Semantics/ObjectAndCollectionInitializerTests.cs [hunk 6]
```diff
@@ -2832,27 +2832,30 @@ static void Main(string[] args)
...
-";
+                      IObjectOrCollectionInitializerOperation (OperationKind.ObjectOrCollectionInitializer, Type: Dictionary<System.Object, System.Object>, IsInvalid) (Syntax: '{ ... }')
+                        Initializers(3):
+                            IInvalidOperation (OperationKind.Invalid, Type: ?, IsInvalid) (Syntax: '{"s", 1 }')
+                              Children(2):
+                                  ILiteralOperation (OperationKind.Literal, Type: System.String, Constant: "s", IsInvalid) (Syntax: '"s"')
+                                  ILiteralOperation (OperationKind.Literal, Type: System.Int32, Constant: 1, IsInvalid) (Syntax: '1')
+                            IInvalidOperation (OperationKind.Invalid, Type: ?, IsInvalid, IsImplicit) (Syntax: 'var')
+                              Children(1):
+                                  IOperation:  (OperationKind.None, Type: null, IsInvalid) (Syntax: 'var')
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ObjectAndCollectionInitializerTests.cs:2846]: What is this `NoneOperation` representing?

**Review by 333fred — COMMENTED** [review]
The general approach looks fine to me, but I have a few comments. I don't like the new `NoneOperation` in the tree here; it doesn't seem like it should be there.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 4 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:10962]: Most likely the user intends to assign a non-null value, so my choice was to assume the more likely scenario of assigning a non-null value after actually typing the `= expr` the user intends, thus avoiding the extra arising warnings in the code below, reducing friction while handling this erroneous case.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs (hunk 5 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs:7185]: To be honest I kinda just left it do its job after the fix in the binder. Perhaps we should consider how to treat this situation without defaulting to a none operation

Comment (Rekkonnect) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs:7185]: In this case, `i` is bound as a `BoundMethodGroup`, as an aftermath of the changes to the binder. In such a weird case though I don't think we should care much about the operation that is returned.

Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs:7185]: That seems pretty wrong. I do not want to see that returned, and it doesn't feel right that this would be bound as a method group either.

Comment (Rekkonnect) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs:7185]: So the direction is to discard the bound result from the identifier name case if it's not a valid member and fallback to the previous behavior (binding to `i`, the local).

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 7]
```diff
@@ -5616,43 +5616,72 @@ private BoundExpression MakeBadExpressionForObjectCreation(SyntaxNode node, Type
...
+                            return BindAssignment(initializer, boundLeft, boundRight, isRef, diagnostics);
+                        }
+                        break;
+                    }
 
-                    var rhsExpr = initializer.Right.CheckAndUnwrapRefExpression(diagnostics, out RefKind refKind);
-                    bool isRef = refKind == RefKind.Ref;
-                    var rhsKind = isRef ? GetRequiredRHSValueKindForRefAssignment(boundLeft) : BindValueKind.RValue;
+                // We fall back on simply binding the name as an expression for proper recovery
+                // and also report a diagnostic about this being an invalid value
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:5660]: might want to explain why this is beneficial.

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs [hunk 8]
```diff
@@ -5267,6 +5267,388 @@ static void Main()
             Assert.Same(symbol1.ContainingSymbol, symbol2.ContainingSymbol);
         }
 
+        [Fact]
+        [WorkItem("https://github.com/dotnet/roslyn/issues/74348")]
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs:5271]:
```suggestion
        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/74348")]
```

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs [hunk 9]
```diff
@@ -5267,6 +5267,388 @@ static void Main()
...
+                .ChildNodes()
+                .ToArray();
+            var initializedSymbol = model.GetSymbolInfo(initializers[1]).Symbol;
+
+            Assert.NotNull(initializedSymbol);
+            Assert.True(initializedSymbol.Equals(valueProperty, SymbolEqualityComparer.Default));
+        }
+
+        [Fact]
+        [WorkItem("https://github.com/dotnet/roslyn/issues/74348")]
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs:5319]:
```suggestion
        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/74348")]
```

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs [hunk 10]
```diff
@@ -5267,6 +5267,388 @@ static void Main()
...
+                as InitializerExpressionSyntax;
+            var valueInitializer = thingInitializer.Expressions[1];
+            var initializedSymbol = model.GetSymbolInfo(valueInitializer).Symbol;
+
+            Assert.NotNull(initializedSymbol);
+            Assert.True(initializedSymbol.Equals(valueProperty, SymbolEqualityComparer.Default));
+        }
+
+        [Fact]
+        [WorkItem("https://github.com/dotnet/roslyn/issues/74348")]
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs:5376]:
```suggestion
        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/74348")]
```

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs [hunk 11]
```diff
@@ -5267,6 +5267,388 @@ static void Main()
...
+                .ChildNodes()
+                .ToArray();
+            var initializedSymbol = model.GetSymbolInfo(initializers[1]).Symbol;
+
+            Assert.NotNull(initializedSymbol);
+            Assert.True(initializedSymbol.Equals(valueField, SymbolEqualityComparer.Default));
+        }
+
+        [Fact]
+        [WorkItem("https://github.com/dotnet/roslyn/issues/74348")]
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs:5424]:
```suggestion
        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/74348")]
```

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs [hunk 12]
```diff
@@ -5267,6 +5267,388 @@ static void Main()
...
+                .First()
+                .ChildNodes()
+                .ToArray();
+            var initializedSymbol = model.GetSymbolInfo(initializers[1]).Symbol;
+
+            Assert.Null(initializedSymbol);
+        }
+
+        [Fact]
+        [WorkItem("https://github.com/dotnet/roslyn/issues/74348")]
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs:5462]:
```suggestion
        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/74348")]
```

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs [hunk 13]
```diff
@@ -5267,6 +5267,388 @@ static void Main()
...
+                as InitializerExpressionSyntax;
+            var valueInitializer = thingInitializer.Expressions[0];
+            var initializedSymbol = model.GetSymbolInfo(valueInitializer).Symbol;
+
+            Assert.NotNull(initializedSymbol);
+            Assert.True(initializedSymbol.Equals(valueProperty, SymbolEqualityComparer.Default));
+        }
+
+        [Fact]
+        [WorkItem("https://github.com/dotnet/roslyn/issues/74348")]
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs:5567]:
```suggestion
        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/74348")]
```

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs [hunk 14]
```diff
@@ -5267,6 +5267,388 @@ static void Main()
...
+                .ChildNodes()
+                .ToArray();
+            var initializedSymbol = model.GetSymbolInfo(initializers[0]).Symbol;
+
+            Assert.NotNull(initializedSymbol);
+            Assert.True(initializedSymbol.Equals(valueField, SymbolEqualityComparer.Default));
+        }
+
+        [Fact]
+        [WorkItem("https://github.com/dotnet/roslyn/issues/74348")]
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs:5615]:
```suggestion
        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/74348")]
```

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 7 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: Added an explanation, lmk if it's okay

**Review by 333fred — APPROVED** [review]

**Comment by 333fred** [comment]
@dotnet/roslyn-compiler for a second review.

**Comment by 333fred** [comment]
@dotnet/roslyn-compiler for a second review

**Comment by AlekseyTs** [comment]
@Rekkonnect Could you resolve merge conflicts?

**Comment by Rekkonnect** [comment]
@AlekseyTs done could you ptal

File: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs [hunk 15]
```diff
@@ -6056,7 +6056,8 @@ void handleInitializer(IOperation innerInitializer)
 #if DEBUG
                         var validKinds = ImmutableArray.Create(OperationKind.Invocation, OperationKind.DynamicInvocation, OperationKind.Increment, OperationKind.Literal,
                                                                OperationKind.LocalReference, OperationKind.Binary, OperationKind.FieldReference, OperationKind.Invalid,
-                                                               OperationKind.InterpolatedString);
+                                                               OperationKind.InterpolatedString, OperationKind.PropertyReference, OperationKind.FieldReference,
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:6059]: >OperationKind.FieldReference [](http://example.com/codeflow?start=130&length=28)

It looks like this value is already added above.

File: src/Compilers/CSharp/Test/Semantic/Semantics/ObjectAndCollectionInitializerTests.cs [hunk 16]
```diff
@@ -2832,27 +2832,28 @@ static void Main(string[] args)
...
-            IInvalidOperation (OperationKind.Invalid, Type: ?, IsInvalid) (Syntax: '{""s"", 1 }')
-              Children(2):
-                  ILiteralOperation (OperationKind.Literal, Type: System.String, Constant: ""s"", IsInvalid) (Syntax: '""s""')
-                  ILiteralOperation (OperationKind.Literal, Type: System.Int32, Constant: 1, IsInvalid) (Syntax: '1')
-            IInvalidOperation (OperationKind.Invalid, Type: ?, IsInvalid) (Syntax: 'var')
-              Children(0)
-            ISimpleAssignmentOperation (OperationKind.SimpleAssignment, Type: ?, IsInvalid) (Syntax: 'x = 1')
-              Left:
-                IInvalidOperation (OperationKind.Invalid, Type: ?, IsInvalid, IsImplicit) (Syntax: 'x')
+            string expectedOperationTree = """
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ObjectAndCollectionInitializerTests.cs:2835]: >""" [](http://example.com/codeflow?start=43&length=3)

Please revert to the original style.

File: src/Compilers/CSharp/Test/Semantic/Semantics/ObjectAndCollectionInitializerTests.cs [hunk 17]
```diff
@@ -2872,12 +2873,12 @@ static void Main(string[] args)
                 // (8,13): error CS0747: Invalid initializer member declarator
                 //             {"s", 1 },
                 Diagnostic(ErrorCode.ERR_InvalidInitializerElementInitializer, @"{""s"", 1 }").WithLocation(8, 13),
-                // (9,9): error CS0103: The name 'var' does not exist in the current context
-                //         var x = 1;
-                Diagnostic(ErrorCode.ERR_NameNotInContext, "var").WithArguments("var").WithLocation(9, 9),
                 // (9,9): error CS0747: Invalid initializer member declarator
                 //         var x = 1;
-                Diagnostic(ErrorCode.ERR_InvalidInitializerElementInitializer, "var").WithLocation(9, 9)
+                Diagnostic(ErrorCode.ERR_InvalidInitializerElementInitializer, "var").WithLocation(9, 9),
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ObjectAndCollectionInitializerTests.cs:2878]: >Diagnostic(ErrorCode.ERR_InvalidInitializerElementInitializer, "var").WithLocation(9, 9) [](http://example.com/codeflow?start=16&length=88)

Please place this item back to its original position.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/ObjectAndCollectionInitializerTests.cs:2878]: Either I am missing something, or none of the changes in this file are necessary. If so, please revert it to its original state.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs [hunk 18]
```diff
@@ -7163,49 +7166,49 @@ public B M(int i, int j)
...
-                ILiteralOperation (OperationKind.Literal, Type: System.Int32, Constant: 2) (Syntax: '2')
-        Next (Return) Block[B2]
-            IFlowCaptureReferenceOperation: 0 (OperationKind.FlowCaptureReference, Type: B, IsImplicit) (Syntax: 'this')
-            Leaving: {R1}
-}
-Block[B2] - Exit
-    Predecessors: [B1]
-    Statements (0)
-";
+            var expectedFlowGraph = """
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs:7169]: >""" [](http://example.com/codeflow?start=36&length=3)

Please revert to the original style and alignment

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs [hunk 19]
```diff
@@ -9921,85 +9927,86 @@ public static void M(int i, int j)
...
-                              IFlowCaptureReferenceOperation: 1 (OperationKind.FlowCaptureReference, Type: <anonymous type: System.Int32 A>, IsImplicit) (Syntax: 'a')
-            Next (Regular) Block[B3]
-                Leaving: {R3} {R1}
-    }
-}
-Block[B3] - Exit
-    Predecessors: [B2]
-    Statements (0)
-";
+            var expectedFlowGraph = """
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs:9930]: >""" [](http://example.com/codeflow?start=36&length=3)

Please revert to the original style and alignment

File: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs [hunk 20]
```diff
@@ -6585,8 +6586,13 @@ public override IOperation VisitInstanceReference(IInstanceReferenceOperation op
                     }
                     else
                     {
-                        Debug.Assert(operation.Parent is InvocationOperation { Parent: CollectionExpressionOperation ce } && ce.HasErrors(_compilation),
-                            "Expected to reach this only in collection expression infinite chain cases.");
+                        Debug.Assert(
+                            // We have a collection expression infinite chain case
+                            (operation.Parent is InvocationOperation { Parent: CollectionExpressionOperation ce } && ce.HasErrors(_compilation)) ||
+                            // We have an object initializer with an invalid assignment
+                            (operation.Parent is { Kind: OperationKind.None }),
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:6593]: >(operation.Parent is { Kind: OperationKind.None }) [](http://example.com/codeflow?start=28&length=50)

Similar comment about lack of illustration in tests.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 21]
```diff
@@ -5616,43 +5616,73 @@ private BoundExpression BindInitializerMemberAssignment(
...
-                        rhsKind,
-                        typeSyntax: boundLeft.Syntax,
-                        diagnostics: diagnostics);
+                        var identifierName = (IdentifierNameSyntax)memberInitializer;
+                        Debug.Assert(objectInitializerMemberBinder != null);
 
-                    // Bind member initializer assignment expression
-                    return BindAssignment(initializer, boundLeft, boundRight, isRef, diagnostics);
-                }
+                        var boundNode = objectInitializerMemberBinder.BindObjectInitializerMemberMissingAssignment(identifierName, implicitReceiver, diagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:5669]: >diagnostics [](http://example.com/codeflow?start=149&length=11)

It doesn't feel appropriate to collect diagnostics from this trial binding, then drop the node, bind the same syntax again, but keep the diagnostics from the trial. At the very least the diagnostics and the node should be kept or dropped together.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 22]
```diff
@@ -5616,43 +5616,73 @@ private BoundExpression BindInitializerMemberAssignment(
...
+                        // Do not bind to a non-member, like a BoundBadExpression
+                        if (boundNode.Kind is BoundKind.ObjectInitializerMember)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:5671]: >if (boundNode.Kind is BoundKind.ObjectInitializerMember) [](http://example.com/codeflow?start=24&length=56)

The logic here with all the rebinding and ```includeError``` flag feels unnecessary complicated. Also, it appears we are now creating a new tree shape whare an implicit receiver appears in a place where we didn't expect it to appear before (not under an assignment). Likely this is the reason for some of the adjustments made in `ControlFlowGraphBuilder.cs`. 

For the purpose of error recovery, I think it is reasonable to assume that a standalone identifier at this position is just an unfinished assignment and bind it as such. Meaning:
- use the ```boundNode``` regardless of what it is at this point
- create "WasCompilerGenerated" ```BoundAssignmentOperator```  with it as the target, "WasCompilerGenerated" ```BoundBadExpression``` with ```UnknownResultType```  as value
- return that assignment node

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 23]
```diff
@@ -5954,10 +6007,18 @@ private static void ReportDuplicateObjectMemberInitializers(BoundExpression boun
 
                 var memberInitializerSyntax = boundMemberInitializer.Syntax;
 
-                Debug.Assert(memberInitializerSyntax.Kind() == SyntaxKind.SimpleAssignmentExpression);
-                var namedAssignment = (AssignmentExpressionSyntax)memberInitializerSyntax;
+                IdentifierNameSyntax memberNameSyntax;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:6010]: >IdentifierNameSyntax memberNameSyntax; [](http://example.com/codeflow?start=16&length=38)

Adjustments to this function likely won't be necessary if we create ```BoundAssignmentOperator``` as suggested because it will not pass the ```!boundMemberInitializer.HasAnyErrors``` test.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 24]
```diff
@@ -10981,8 +10981,14 @@ public override void VisitForEachIterationVariables(BoundForEachStatement node)
 
         public override BoundNode? VisitObjectInitializerMember(BoundObjectInitializerMember node)
         {
-            // Should be handled by VisitObjectCreationExpression.
-            throw ExceptionUtilities.Unreachable();
+            // We reach this point when we have just an identifier name in the initializer without an actual
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:10984]: >// We reach this point when we have just an identifier name in the initializer without an actual [](http://example.com/codeflow?start=12&length=96)

Adjustments to this function likely won't be necessary if we create ```BoundAssignmentOperator``` as suggested.

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs [hunk 25]
```diff
@@ -5267,6 +5267,380 @@ void F(int x = 2, = 3) { }
...
+                    {
+                        return new()
+                        {
+                            Key = key,
+                            Value,
+                        };
+                    }
+                }
+                """;
+            var comp = CreateCompilation(source);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs:5292]: >comp [](http://example.com/codeflow?start=16&length=4)

Please assert diagnostics for the compilation. This suggestion applies to all added tests

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs [hunk 26]
```diff
@@ -5267,6 +5267,380 @@ void F(int x = 2, = 3) { }
...
+            var model = comp.GetSemanticModel(tree);
+            var root = tree.GetCompilationUnitRoot();
+            var propertyDecls = root.DescendantNodes()
+                .OfType<ClassDeclarationSyntax>()
+                .First()
+                .ChildNodes()
+                .OfType<PropertyDeclarationSyntax>()
+                .ToArray();
+            var valuePropertyDecl = propertyDecls[1];
+            var valueProperty = model.GetDeclaredSymbol(valuePropertyDecl);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs:5303]: >model.GetDeclaredSymbol(valuePropertyDecl) [](http://example.com/codeflow?start=32&length=42)

This is an extremely convoluted and inefficient way of getting a property symbol. It is much simpler to get it from symbol model. I think we have helpers that do that based on qualified name. "GetMemberSymbol" or something. That said, given the goal of this test, I don't think we even need to locate the symbol. See the next comment

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs [hunk 27]
```diff
@@ -5267,6 +5267,380 @@ void F(int x = 2, = 3) { }
...
+            Assert.NotNull(valueProperty);
+
+            var initializers = root.DescendantNodes()
+                .OfType<InitializerExpressionSyntax>()
+                .First()
+                .ChildNodes()
+                .ToArray();
+            var initializedSymbol = model.GetSymbolInfo(initializers[1]).Symbol;
+
+            Assert.NotNull(initializedSymbol);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs:5313]: >Assert.NotNull(initializedSymbol); [](http://example.com/codeflow?start=12&length=34)

I think this assert together with the one below can be replaced with 
```
Assert.Equal("...", initializedSymbol.ToTestDisplayString());
```

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs:5313]: This suggestion is applicable to other added tests too

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs [hunk 28]
```diff
@@ -5267,6 +5267,380 @@ void F(int x = 2, = 3) { }
             Assert.Same(symbol1.ContainingSymbol, symbol2.ContainingSymbol);
         }
 
+        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/74348")]
+        public void ObjectInitializerIncompletePropertyValueDeclaration01()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs:5271]: >Declaration [](http://example.com/codeflow?start=60&length=11)

Regarding the "Declaration" word in the name of the test. What is it supposed to convey?

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs [hunk 29]
```diff
@@ -5267,6 +5267,380 @@ void F(int x = 2, = 3) { }
...
+                as InitializerExpressionSyntax;
+            var valueInitializer = thingInitializer.Expressions[1];
+            var initializedSymbol = model.GetSymbolInfo(valueInitializer).Symbol;
+
+            Assert.NotNull(initializedSymbol);
+            Assert.True(initializedSymbol.Equals(valueProperty, SymbolEqualityComparer.Default));
+        }
+
+        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/74348")]
+        public void ObjectInitializerIncompletePropertyValueDeclaration03()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs:5374]: >Property [](http://example.com/codeflow?start=47&length=8)

Is there a property in the test scenario?

**Comment by AlekseyTs** [comment]
Done with review pass (commit 9)

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs (hunk 28 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs:5271]: It should be "Assignment" I think, I'll change that in the next commits

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs (hunk 29 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs:5374]: All those tests reflect member assignments, not property assignments specifically. I'll rename accordingly, also addressing the previous comment

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs (hunk 28 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs:5271]: >public [](http://example.com/codeflow?start=8&length=6)

Consider adding similar tests for VB

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 22 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:5671]: I tried this approach and I can't figure out what syntax node to provide into the bound bad expression; either I use the identifier name twice, throwing when running the tests because the same syntax is used in multiple bound expressions, or I have to generate a syntax node that contains nothing and doesn't actually exist in the parsed tree.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:5671]: > I tried this approach and I can't figure out what syntax node to provide into the bound bad expression; either I use the identifier name twice, throwing when running the tests because the same syntax is used in multiple bound expressions, or ...

Did you accurately follow the suggestion? Did you mark the synthesized nodes as "WasCompilerGenerated"?

File: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs (hunk 15 above)
Comment (Rekkonnect) [reply src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: Removed those added values

File: src/Compilers/CSharp/Test/Semantic/Semantics/ObjectAndCollectionInitializerTests.cs (hunk 16 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Test/Semantic/Semantics/ObjectAndCollectionInitializerTests.cs]: Reverted

File: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs (hunk 15 above)
[the remark this answers is not in the document]
Comment (Rekkonnect) [reply src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: Removed those added values

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 22 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:5669]: I confused `hasError` with `WasCompilerGenerated`, it works fine now and I've applied this approach. Thanks for the guidance.

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs (hunk 28 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs]: This PR only improves handling incorrect object initializers in C#, leaving VB unaffected. Do we want to add tests showing the current state of similar cases in VB?

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs (hunk 25 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs:5292]: Done

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs (hunk 27 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs]: Done

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs (hunk 26 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs]: Done

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs (hunk 29 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs]: Renamed

File: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs (hunk 20 above)
[the remark this answers is not in the document]
Comment (Rekkonnect) [reply src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: Reverted

Comment (Rekkonnect) [reply src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: Reverted

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs (hunk 19 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs]: Reverted

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs (hunk 18 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs]: Reverted

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 21 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:5667]: Adjusted approach as described below

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 24 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Reverted

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 23 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: Reverted

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs (hunk 28 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs]: Renamed those methods

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 4 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Reverted this change as described in comments below

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 22 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:5669]: This `if` is still present after commit 15. To clarify, the suggestion was to get rid of it and always return ```BoundAssignmentOperator```.

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs (hunk 28 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs]: > Do we want to add tests showing the current state of similar cases in VB?

I think we do.

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs [hunk 30]
```diff
@@ -5267,6 +5267,434 @@ void F(int x = 2, = 3) { }
...
+                            Key = key,
+                            Value,
+                        };
+                    }
+                }
+                """;
+            var comp = CreateCompilation(source);
+
+            comp.VerifyDiagnostics(
+                // (4,18): warning CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs:5295]: >warning CS8632 [](http://example.com/codeflow?start=27&length=14)

Please get rid of these warnings by removing the nullable annotations. I assume they are not required to observe effect of the changes.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 22 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:5669]: I tried that and binding to the symbols failed, so this specific binding technique is necessary it seems

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs [hunk 31]
```diff
@@ -5267,6 +5267,434 @@ void F(int x = 2, = 3) { }
...
+                            Key = key,
+                            Handler,
+                        };
+                    }
+                }
+                """;
+            var comp = CreateCompilation(source);
+
+            comp.VerifyDiagnostics(
+                // (4,18): error CS0246: The type or namespace name 'Action' could not be found (are you missing a using directive or an assembly reference?)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs:5451]: >// (4,18): error CS0246: The type or namespace name 'Action' could not be found (are you missing a using directive or an assembly reference?) [](http://example.com/codeflow?start=16&length=141)

Please fix this error

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs [hunk 32]
```diff
@@ -5267,6 +5267,434 @@ void F(int x = 2, = 3) { }
...
+                //     public event Action? Handler;
+                Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "Action").WithArguments("Action").WithLocation(4, 18),
+                // (4,26): error CS0066: 'Thing.Handler': event must be of a delegate type
+                //     public event Action? Handler;
+                Diagnostic(ErrorCode.ERR_EventNotDelegate, "Handler").WithArguments("Thing.Handler").WithLocation(4, 26),
+                // (4,26): warning CS0067: The event 'Thing.Handler' is never used
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs:5457]: >// (4,26): warning CS0067: The event 'Thing.Handler' is never used [](http://example.com/codeflow?start=16&length=66)

Please suppress this warning with pragma

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 22 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:5669]: > I tried that and binding to the symbols failed, so this specific binding technique is necessary it seems

Where did it fail, why did it fail? I assume it would work if the assignment was present in the syntax. In general, if a suggestion doesn't quite work, it would be good to explicitly communicate the fact.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 15)

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 22 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: I tried again and removed the `if`, tests pass fine. This is done.

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs (hunk 30 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs]: Done

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs (hunk 32 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs]: Done

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs (hunk 31 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs]: Done

**Comment by AlekseyTs** [comment]
Done with review pass (commit 17)

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs (hunk 28 above)
Comment (Rekkonnect) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetDeclaredSymbolAPITests.cs]: Added the tests, lmk

**Comment by AlekseyTs** [comment]
@333fred For the second review

**Review by 333fred — APPROVED** [review]
