### PR TITLE
ChangeSignature - don't crash on unparenthesized lambdas

### LINKED ISSUE #43664: Change signature disabled due to ArgumentException
Version: 16.7.0 Preview 1.0 [30024.6.master]

Repro:
1. Right-click ```BlockOverlapsHiddenPosition``` in line 152 in [AbstractIntroduceVariableService.cs](http://sourceroslyn.io/#Microsoft.CodeAnalysis.Features/IntroduceVariable/AbstractIntroduceVariableService.cs,152):
``` C#
if (blocks.All(b => !BlockOverlapsHiddenPosition(b, cancellationToken)))
```
2. Change signature encounters argument exception and is disabled.

Stack trace:
```C#
System.ArgumentException : Unexpected SyntaxNode
Parameter name: matchingNode
   at Microsoft.CodeAnalysis.CSharp.ChangeSignature.CSharpChangeSignatureService.GetPositionBeforeParameterListClosingBrace(SyntaxNode matchingNode)
   at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.GetContextAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.GetChangeSignatureCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ChangeSignature.ChangeSignatureCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #43664

### CODE REVIEW

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs [hunk 1]
```diff
@@ -171,7 +171,7 @@ protected override int GetPositionBeforeParameterListClosingBrace(SyntaxNode mat
             {
                 ParameterListSyntax parameterListSyntax => parameterListSyntax.CloseParenToken.SpanStart,
                 BracketedParameterListSyntax bracketedParameterListSyntax => bracketedParameterListSyntax.CloseBracketToken.SpanStart,
-                _ => throw new ArgumentException("Unexpected SyntaxNode", nameof(matchingNode))
+                _ => matchingNode.SpanStart // e.g. unparenthesized lambda parameters
```
Comment (dpoeschl) [inline src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:174]: This whole method can probably be gotten rid of, since it was more necessary for the completion list aspect which we pulled out. But this is a minimal fix for the crash.
