### PR TITLE
Reinfer containing type argument for GetResult when analyzing 'await'

### LINKED ISSUE #40452: await Task<T?> returns T instead of T?
**Version Used**: 
VS2019 Version 16.4.2
.NET Core 3.1 Project

**Steps to Reproduce**:
```C#
static async Task Main()
{
    object? thisIsNull = await Task.Run(GetNull);
    Console.WriteLine(thisIsNull);
}

static object? GetNull() => null;
```

**Actual Behavior**:
VS popup tip on `Console.WriteLine(thisIsNull)` says that "`thisIsNull` is not null here".
Change `Task.Run(GetNull)` to `Task.Run<object?>(GetNull)` and tip says "may be null here" but `<object?>` becomes grayed out and VS suggests to remove it.

**Expected Behavior**:
I'm not sure what is wrong here, but either `<object?>` should not be grayed out or `await Task<T?>` should return `T?` without explicit generic method type specification.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #40452

Thanks @cston for your help with this.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 1]
```diff
@@ -7420,8 +7420,11 @@ public override BoundNode VisitAwaitExpression(BoundAwaitExpression node)
             }
             else
             {
-                // Update method based on inferred receiver type: see https://github.com/dotnet/roslyn/issues/29605.
-                SetResultType(node, awaitableInfo.GetResult.ReturnTypeWithAnnotations.ToTypeWithState());
+                var reinferredGetResult = _visitResult.RValueType.Type is NamedTypeSymbol taskAwaiterType
+                    ? awaitableInfo.GetResult.OriginalDefinition.AsMember(taskAwaiterType)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >awaitableInfo.GetResult.OriginalDefinition.AsMember(taskAwaiterType) [](start = 22, length = 68)

Just curious: Why use `NamedTypeSymbol.AsMember()` rather than `AsMemberOfType(TypeSymbol, Symbol)` as used in other cases in `NullableWalker`?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Hmm, I must have missed it when I went looking for it, but it seems like `NullableWalker.AsMemberOfType` is a more complex/general purpose method, and it eventually calls down into `MethodSymbol.AsMember(NamedTypeSymbol)` which I use directly here.

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler Could I please get a second review on a small fix?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 2]
```diff
@@ -7420,8 +7420,11 @@ public override BoundNode VisitAwaitExpression(BoundAwaitExpression node)
...
+                    : awaitableInfo.GetResult;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: > : awaitableInfo.GetResult; [](start = 19, length = 27)

can we hit this case? Do we have a test?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: We can hit this case with some unusual scenarios such as a task-like type where the return value from GetAwaiter is a type parameter. We decided it's not worth the work to address these scenarios. I added a comment.

---
In reply to: [369191832](https://github.com/dotnet/roslyn/pull/41064#discussion_r369191832) [](ancestors = 369191832)

**Comment by RikkiGibson** [comment]
Actually I will go to the extra effort to squash merge it

**Comment by RikkiGibson** [comment]
This PR is blocked on infra issues. Every attempt of the failing legs has failed on git checkout.
