### PR TITLE
TrimTrailingSeparators on GetRelativePath

### LINKED ISSUE #51602: CSharpMatchFolderAndNamespaceDiagnosticAnalyzer throws exception
installed .NET 6 preview SDK

Opened default console app in VS 2019.10 Preview 1

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MatchFolderAndNamespace.CSharpMatchFolderAndNamespaceDiagnosticAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.
Exception occurred with following context:
Compilation: net6-analyzers-bug
SyntaxTree: C:\source\jmarolf\scratch\net6-analyzers-bug\Program.cs
SyntaxNode: namespace ConsoleCore { class Program ... [NamespaceDeclarationSyntax]@[15..173) (1,0)-(9,1)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Roslyn.Utilities.PathUtilities.GetRelativePath(String directory, String fullPath)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.IsFileAndNamespaceMismatch(TNamespaceSyntax namespaceDeclaration, String rootNamespace, String projectDir, String currentNamespace, String& targetNamespace)
   at Microsoft.CodeAnalysis.Analyzers.MatchFolderAndNamespace.AbstractMatchFolderAndNamespaceDiagnosticAnalyzer`1.AnalyzeNamespaceNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

### PR DESCRIPTION
**Pull request by jmarolf**
fixes #51602

### CODE REVIEW

**Review by cston — APPROVED** [review]

File: src/Compilers/Core/CodeAnalysisTest/FileSystem/PathUtilitiesTests.cs [hunk 1]
```diff
@@ -383,5 +383,13 @@ public void CombinePaths_DifferentFromPathCombine(string expected, string path1,
         {
             Assert.Equal(expected, PathUtilities.CombinePaths(path1, path2));
         }
+
+        [ConditionalFact(typeof(WindowsOnly)), WorkItem(51602, @"https://github.com/dotnet/roslyn/issues/51602")]
```
Comment (RikkiGibson) [inline src/Compilers/Core/CodeAnalysisTest/FileSystem/PathUtilitiesTests.cs:387]: Why WindowsOnly?

Comment (jmarolf) [reply src/Compilers/Core/CodeAnalysisTest/FileSystem/PathUtilitiesTests.cs:387]: `PathUtilities.GetRelativePath(@"C:\A\B\", @"C:\A\B")` is handled completely different by the underlying framework on *nix machines

Comment (RikkiGibson) [reply src/Compilers/Core/CodeAnalysisTest/FileSystem/PathUtilitiesTests.cs:387]: Is there any analogous bug that we should verify is fixed on non-Windows platforms?

**Review by RikkiGibson — APPROVED** [review]

File: src/Compilers/Core/Portable/FileSystem/PathUtilities.cs [hunk 2]
```diff
@@ -534,6 +534,9 @@ public static string GetRelativePath(string directory, string fullPath)
         {
             string relativePath = string.Empty;
 
+            directory = TrimTrailingSeparators(directory);
+            fullPath = TrimTrailingSeparators(fullPath);
+
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/FileSystem/PathUtilities.cs:539]: this is always terrifying to me.  Is there a reason we have our own GetRelativePath?  I thought this was something the platform provided.  If we write our own, won't we always have the risk of just deviating and needing to continually patch like this?

Comment (CyrusNajmabadi) [reply src/Compilers/Core/Portable/FileSystem/PathUtilities.cs:539]: Can you remove this entirely and switch to https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getrelativepath?view=net-5.0 ?

**Review by CyrusNajmabadi — DISMISSED** [review]
can we either use the platform method?  or can we just dupe their code?  I'm really wary about us seeming to have a home  grown version with semantics i have no clue about.

File: src/Compilers/Core/CodeAnalysisTest/FileSystem/PathUtilitiesTests.cs [hunk 3]
```diff
@@ -383,5 +383,13 @@ public void CombinePaths_DifferentFromPathCombine(string expected, string path1,
...
+        public void GetRelativePath_IndexOutOfRangeException()
+        {
+            var expected = "";
+            var result = PathUtilities.GetRelativePath(@"C:\A\B\", @"C:\A\B");
+            Assert.Equal(expected, result);
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/CodeAnalysisTest/FileSystem/PathUtilitiesTests.cs:392]: instead of making this windows only, can we instead just build the string using the platform sepaarator?  or, barring that, have some tests for non-windows?

File: src/Compilers/Core/Portable/FileSystem/PathUtilities.cs (hunk 2 above)
Comment (jmarolf) [reply src/Compilers/Core/Portable/FileSystem/PathUtilities.cs:539]: because Path.GetRelativePath doesn't exist in .NET Framework of .NET Standard  I assume? @dotnet/roslyn-compiler

**Review by tmat — CHANGES_REQUESTED** [review]
:clock1:

**Review by tmat — APPROVED** [review]
:shipit:

File: src/Compilers/Core/CodeAnalysisTest/FileSystem/PathUtilitiesTests.cs (hunk 1 above)
Comment (jmarolf) [reply src/Compilers/Core/CodeAnalysisTest/FileSystem/PathUtilitiesTests.cs:387]: I'll add a test

File: src/Compilers/Core/Portable/FileSystem/PathUtilities.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/Compilers/Core/Portable/FileSystem/PathUtilities.cs:539]: That's correct. I don't know if it would be better to use the platform implementation on TFMs where it's available, and fall back to our own implementation otherwise, since if there are bugs with this it may make it harder to reproduce them.

As far as copying the platform implementation, that may help, if the implementation doesn't depend on too much stuff within dotnet/runtime. If it's practical to copy the tests for this method from dotnet/runtime repo that might be helpful too. I consider both to be up to the author's discretion here.

**Review by cston — APPROVED** [review]

File: src/Compilers/Core/Portable/FileSystem/PathUtilities.cs (hunk 2 above)
Comment (jmarolf) [reply src/Compilers/Core/Portable/FileSystem/PathUtilities.cs:539]: I agree that its would be _much_ better if we called the underlying platform apis on .NET Core and newer. The question is whether we want https://github.com/dotnet/roslyn/issues/51602 to make 16.10. we basically have today and tomorrow to get this in if we do.

**Comment by jmarolf** [comment]
Filed https://github.com/dotnet/roslyn/issues/52936 to resolve what the correct thing to do with our poor duplicate implementation of GetRelativePath

**Comment by benaadams** [comment]
Thank you 💜

**Comment by lohithgn** [comment]
@jmarolf hi. I am facing this issue now in a project of mine. I see you have a fix checked in. But how do we get it ? is there any workaround to this? I am kind of blocked in what i am doing. thoughts? 
thanks.
