### PR TITLE
Provide context information for analyzer exceptions

### LINKED ISSUE #30660: Include enough information in AD0001 (when an analyzer throws) to be able to disable & file a bug
I've got the following error in my error list:

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerApiUsageAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	Microsoft.VisualStudio.ProjectSystem.Managed.TestServices		1	Active	Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.MetaAnalyzers.CSharpDiagnosticAnalyzerApiUsageAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.VisualStudio.ProjectSystem.Managed.TestServices
ISymbol: FuncWithOut (NamedType)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.DiagnosticAnalyzerApiUsageAnalyzer`1.GetUsedNamedTypes(INamedTypeSymbol namedType, Compilation compilation, CancellationToken cancellationToken, Boolean& hasAccessToTypeFromWorkspaceAssemblies)
   at Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.DiagnosticAnalyzerApiUsageAnalyzer`1.<>c__DisplayClass11_0.<Initialize>b__1(SymbolAnalysisContext symbolContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteSymbolActionsCore>b__39_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.

```

This is blocking my build, but there's not enough information in the error to be able to file a bug & disable the analyzer. Please include the analyzer ID & the full identity of the assembly it comes from.

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #30660

### CODE REVIEW

File: src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs [hunk 1]
```diff
@@ -10727,8 +10727,14 @@ public void LoadingAnalyzerNetStandard13()
             var srcFile = analyzerDir.CreateFile(srcFileName).WriteAllText("public class C { }");
 
             var result = ProcessUtilities.Run(s_CSharpCompilerExecutable, arguments: $"/nologo /t:library /analyzer:{analyzerFileName} {srcFileName}", workingDirectory: analyzerDir.Path);
+            var outputWithoutPaths = Regex.Replace(result.Output, " in .*", "");
             AssertEx.AssertEqualToleratingWhitespaceDifferences(
-                $"warning AD0001: Analyzer 'TestAnalyzer' threw an exception of type 'System.NotImplementedException' with message '28'.", result.Output);
+                $@"warning AD0001: Analyzer 'TestAnalyzer' threw an exception of type 'System.NotImplementedException' with message '28'.
+System.NotImplementedException: 28
+   at TestAnalyzer.get_SupportedDiagnostics()
+   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.AnalyzerExecutionContext.<>c__DisplayClass20_0.<ComputeDiagnosticDescriptors>b__0(Object _)
```
Comment (mavasani) [inline src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs]: > at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.AnalyzerExecutionContext.c__DisplayClass20_0.<ComputeDiagnosticDescriptors>b__0(Object _)

This looks very brittle. Can we instead just verifying containment of specific parts of the text?

File: src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs [hunk 2]
```diff
@@ -841,14 +842,24 @@ public override void Initialize(AnalysisContext context)
...
+            var analyzers = new DiagnosticAnalyzer[] { analyzer };
             string message = new ArgumentException(string.Format(CodeAnalysisResources.UnsupportedDiagnosticReported, AnalyzerReportingUnsupportedDiagnostic.UnsupportedDescriptor.Id), "diagnostic").Message;
+            IFormattable context = $@"Exception occurred with following context:
+Compilation: {compilation.AssemblyName}
 
-            CreateCompilationWithMscorlib45(source)
+{new LazyToString(() => analyzer.ThrownException)}
+-----
+
+Suppress the following diagnostics to disable this analyzer: ID_1";
```
Comment (mavasani) [inline src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs]: This is nice. Do we want to force the unit test to run only on English locale with a conditional fact attribute?

Comment (sharwell) [reply src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs]: Updated to support other languages

File: src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs (hunk 1 above)
Comment (sharwell) [reply src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs]: Not easily, but it's rare for this portion of the tests to need changes so I'm not especially concerned at this point. (Most tests only care that AD0001 is _not_ reported.)

**Comment by sharwell** [comment]
@dotnet/roslyn-compiler this is ready for review. Please let me know if you have any questions.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs [hunk 3]
```diff
@@ -1486,6 +1487,29 @@ private static string CreateDiagnosticDescription(AnalysisContextInfo? info, Exc
                 string.Format(CodeAnalysisResources.ExceptionContext, info?.GetContext()), e.CreateDiagnosticDescription());
         }
 
+        private static string CreateDisablingMessage(DiagnosticAnalyzer analyzer)
+        {
+            var diagnosticIds = ImmutableSortedSet<string>.Empty.WithComparer(StringComparer.OrdinalIgnoreCase);
+            try
+            {
+                foreach (var diagnostic in analyzer.SupportedDiagnostics)
```
Comment (mavasani) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs]: Switch to invoking [AnalyzerManager.GetSupportedDiagnosticDescriptors](http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerManager.cs,233) - this handles exceptions from callbacks + also caches the descriptors per analyzer so you don't need any try catch here.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs [hunk 4]
```diff
@@ -1469,7 +1469,8 @@ internal static Diagnostic CreateAnalyzerExceptionDiagnostic(DiagnosticAnalyzer
             var analyzerName = analyzer.ToString();
             var title = CodeAnalysisResources.CompilerAnalyzerFailure;
             var messageFormat = CodeAnalysisResources.CompilerAnalyzerThrows;
-            var messageArguments = new[] { analyzerName, e.GetType().ToString(), e.Message };
+            var contextInformation = string.Join(Environment.NewLine, CreateDiagnosticDescription(info, e), CreateDisablingMessage(analyzer)).Trim();
+            var messageArguments = new[] { analyzerName, e.GetType().ToString(), e.Message, contextInformation };
             var description = string.Format(CodeAnalysisResources.CompilerAnalyzerThrowsDescription, analyzerName, CreateDiagnosticDescription(info, e));
```
Comment (mavasani) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs]: > CreateDiagnosticDescription(info, e)

We are now duplicating this data in the diagnostic message and the description, the latter shows up in the IDE when you expand the diagnostic in error list.

Comment (sharwell) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs]: I'll file a follow-up issue for this.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs (hunk 3 above)
Comment (sharwell) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs]: Done!

Comment (sharwell) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs]: Well that didn't work. Reverting this part of the change.

Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs]: What part did not work?

Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs]: Is it because this method (to report exception diagnostics) may itself be invoked while computing SupportedDiagnostics?

Comment (sharwell) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs]: It crashed the test runner. It didn't give any indication of _which_ tests failed so I reverted to a state that I know worked and we can leave this as a follow-up if you'd like to see it changed.

Comment (sharwell) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs]: > Is it because this method (to report exception diagnostics) may itself be invoked while computing SupportedDiagnostics?

I'm not sure, but a stack overflow would explain the lack of details in the test failures.

**Comment by agocke** [comment]
How does this solve the issue that was reported, namely that there's not enough info to disable the analyzer?

File: src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs [hunk 5]
```diff
@@ -872,23 +884,59 @@ public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics
...
+                    }
+                });
             }
         }
 
         [Fact, WorkItem(4376, "https://github.com/dotnet/roslyn/issues/4376")]
         public void TestReportingDiagnosticWithInvalidId()
         {
             string source = @"";
+            CSharpCompilation compilation = CreateCompilationWithMscorlib45(source);
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs]: Please use `CreateCompilation` unless you have a specific reason for targeting net45. The goal is to eliminate these legacy helpers.

File: src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs [hunk 6]
```diff
@@ -872,23 +884,59 @@ public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics
...
+-----
+
+{string.Format(CodeAnalysisResources.DisableAnalyzerDiagnosticsMessage, "Invalid ID")}";
+
+            EventHandler<FirstChanceExceptionEventArgs> firstChanceException = (sender, e) =>
+            {
+                if (e.Exception is ArgumentException)
+                {
+                    analyzerException = e.Exception;
+                }
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs]: Are other exceptions expected here?

File: src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs [hunk 7]
```diff
@@ -872,23 +884,59 @@ public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics
...
+            };
+
+            try
+            {
+                AppDomain.CurrentDomain.FirstChanceException += firstChanceException;
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs]: > AppDomain.CurrentDomain.FirstChanceException += firstChanceException; [](start = 15, length = 70)

This is really brittle to do in our unit test environment where there may be stray `Task` running from a previous test run. If we need to actually catch first chance exceptions we should just do this in a separate `AppDomain`

File: src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs (hunk 6 above)
Comment (sharwell) [reply src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs]: No, a specific exception is thrown inside the analyzer engine and we a reference to it for the message details.

File: src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs (hunk 7 above)
Comment (sharwell) [reply src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs]: I believe we lose the ability to run the tests on other platforms in that case. Note that we would only get interference if an `ArgumentException` was thrown from another test, and if the test did fail it would include a stack trace for the code running from a previous test.

**Comment by sharwell** [comment]
> How does this solve the issue that was reported, namely that there's not enough info to disable the analyzer?

Two ways:

1. It provides context so the underlying problem can be fixed
2. It includes a list of diagnostic IDs in the error message, and if the user disables those diagnostic IDs then the analyzer will not run (and thus will not fail)

File: src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs (hunk 5 above)
Comment (sharwell) [reply src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs]: This is preserved unchanged from the original code (leaving conversion for a separate work item). New tests added by this pull request already use `CreateCompilation`.

File: src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs (hunk 7 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs]: Okay then we need another approach to validating this change. As written the validation is flaky and can't be safely merged.

Comment (sharwell) [reply src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs]: What about `e.Exception is ArgumentException { Message: message }`?

Comment (sharwell) [reply src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs]: @jaredpar would the proposed change address your concerns?

Comment (sharwell) [reply src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs]: @jaredpar If your review is blocking, can you mark this as Request Changes? Also, I would like to get this merged for 16.5 Preview 2 but I need to know if the above proposed test strategy is acceptable.

**Comment by sharwell** [comment]
@jaredpar I updated all the tests using FirstChanceException handling to only consider exceptions with a matching identity (where possible) or unique message (remaining). Please take a look at 3d20f88.

**Comment by jaredpar** [comment]
> Do you have an example for how to do this?

**Comment by jaredpar** [comment]
> Do you have an example for how to do this?

What I had envisioned was a helper method on this class that was essentially: 

```cs
List<Exception> RunOnNewDomain(Action action)
``` 

That would use a simple `AppDomain` wrapper to reload the current assembly and then execute the `action` while recording the first chance exceptions.

**Comment by sharwell** [comment]
Summary of offline discussion: while the current tests could collide in theory with other tests running in parallel, that is not currently possible today for the following reasons:

1. With the exception of one _specific_ test pair, each of these tests uses an exception message which is unique to that test within the entire test suite (i.e. no collision possible unless a new test is written to produce the same message)
2. For the specific test pair mentioned previously, the pair of tests appear in the same test class. xUnit does not parallelize test methods within one class, so it is not possible for these tests to overlap with each other in a way that can trigger a false positive - failure of one test to throw the exception during the life of that test (and instead throw it during a different test) necessarily means the poorly behaved test also failed because it failed to throw an expected exception.

**Comment by sharwell** [comment]
@dotnet/roslyn-compiler  for a second review

**Comment by sharwell** [comment]
@dotnet/roslyn-compiler for a second review

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs [hunk 8]
```diff
@@ -1521,6 +1522,29 @@ private static string CreateDiagnosticDescription(AnalysisContextInfo? info, Exc
...
+            {
+                // Intentionally empty
+            }
+
+            if (diagnosticIds.IsEmpty)
+            {
+                return "";
+            }
+
+            return string.Format(CodeAnalysisResources.DisableAnalyzerDiagnosticsMessage, string.Join(", ", diagnosticIds));
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs]: >DisableAnalyzerDiagnosticsMessage [](start = 55, length = 33)

This is going to use default localization for the thread. Is this acceptable?

File: src/Compilers/CSharp/Test/Semantic/Microsoft.CodeAnalysis.CSharp.Semantic.UnitTests.csproj [hunk 9]
```diff
@@ -17,6 +17,7 @@
   </ItemGroup>
   <ItemGroup>
     <PackageReference Include="Microsoft.CSharp" Version="$(MicrosoftCSharpVersion)" />
+    <PackageReference Include="Xunit.Combinatorial" Version="$(XunitCombinatorialVersion)" />
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Microsoft.CodeAnalysis.CSharp.Semantic.UnitTests.csproj]: ><PackageReference Include="Xunit.Combinatorial" Version="$(XunitCombinatorialVersion)" /> [](start = 4, length = 89)

What prompted this change, it doesn't look like there are any source changes in this project?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs (hunk 8 above)
Comment (sharwell) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs]: Yes, this is the same behavior that was in place before my change.

File: src/Compilers/CSharp/Test/Semantic/Microsoft.CodeAnalysis.CSharp.Semantic.UnitTests.csproj (hunk 9 above)
Comment (sharwell) [reply src/Compilers/CSharp/Test/Semantic/Microsoft.CodeAnalysis.CSharp.Semantic.UnitTests.csproj]: I can't find a specific reason for this change. I think this PR is going to need to be retargeted (contains a localization change), so I'll remove it if possible before the new build is kicked off.

File: src/Compilers/Core/Portable/CodeAnalysisResources.resx [hunk 10]
```diff
@@ -394,7 +394,8 @@
     <value>Analyzer Failure</value>
   </data>
   <data name="CompilerAnalyzerThrows" xml:space="preserve">
-    <value>Analyzer '{0}' threw an exception of type '{1}' with message '{2}'.</value>
+    <value>Analyzer '{0}' threw an exception of type '{1}' with message '{2}'.
+{3}</value>
```
Comment (tmeschter) [inline src/Compilers/Core/Portable/CodeAnalysisResources.resx]: Best practice is to document the placeholders in the notes field of each item; this helps during the translation process.

Comment (sharwell) [reply src/Compilers/Core/Portable/CodeAnalysisResources.resx]: Is there a reference document regarding standard documentation for common types of placeholders?

File: src/Compilers/CSharp/Test/Semantic/Microsoft.CodeAnalysis.CSharp.Semantic.UnitTests.csproj (hunk 9 above)
Comment (sharwell) [reply src/Compilers/CSharp/Test/Semantic/Microsoft.CodeAnalysis.CSharp.Semantic.UnitTests.csproj]: ➡️ The test TestReportingDiagnosticWithInvalidLocation uses this.
