### PR TITLE
Re-enable BuildWithCommandLine test

### LINKED ISSUE #18204: [Flaky Test] Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpBuild.BuildWithCommandLine Test Failure
Failed in https://ci.dot.net/job/dotnet_roslyn/job/dev16/job/windows_release_vs-integration/24/. The logs only contain that the build failed with exit code 0, due to assert ordering. Submitted https://github.com/dotnet/roslyn/pull/18203 to address that issue.

### PR DESCRIPTION
**Pull request by allisonchou**
This test was previously disabled for being flaky. This flakiness has been resolved with [this PR](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/341836), which allows us to re-enable the test.

Fixes #18204

### CODE REVIEW

**Review by JoeRobich — APPROVED** [review]

**Review by ryzngard — APPROVED** [review]

**Review by jasonmalinowski — APPROVED** [review]

File: src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpBuild.cs [hunk 1]
```diff
@@ -50,7 +50,7 @@ static void Main(string[] args)
             // TODO: Validate build works as expected
         }
 
-        [WpfFact(Skip = "https://github.com/dotnet/roslyn/issues/18204"), Trait(Traits.Feature, Traits.Features.Build)]
+        [WpfFact, Trait(Traits.Feature, Traits.Features.Build)]
```
Comment (Youssef1313) [inline src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpBuild.cs:53]: Should mark the PR as "Fixes #18204"?
