### PR TITLE
Relaxed escape rules for spans

### LINKED ISSUE #22197: ref ternary must match val-escapes on its branches (not ref escapes)
The spec and implementation need to be updated. The following should fail

```CS
public class C
{
    bool flag1 = true;
    bool flag2 = false;

    public void M(ref Span<int> global)
    {
        Span<int> local = stackalloc int[10];

        ref var r1 = ref (flag1 ? ref global : ref local);
        ref var r2 = ref (flag2 ? ref global : ref local);

	// same as         global = local;   which would be an error.
       // but we can’t fail here, since r1 and r2 are basically the same, 
       // so should fail when making r1 and r2 above.
        r1 = r2;   

        // it would require val-escape scopes for r1 and r2 be different.
        // easier to say that val-escape must match
    }
}
```

### PR DESCRIPTION
**Pull request by VSadov**
Also fixes #22197   (mixing rules for ternary ref)

NOTE: many tests that were tracking scope-escapes would be meaningless now since. We cannot observe the difference since spans cannot become attached to a particular scope by capturing a local ref.

I tried to salvage tests by using global/stackalloc  scopes instead - to make sure we are not losing coverage by accident.  
However, since that has only 2 levels of escape (not N) as before, there can be some overlap in tests now. I do not think extra testing that might result from this is a concern though.

### CODE REVIEW

**Comment by VSadov** [comment]
@dotnet/roslyn-compiler - please review.

**Comment by VSadov** [comment]
Please ignore the "Making default stackalloc ...." commit. That goes in as a separate PR (already approved, waiting for Jenkins). I will rebase that away once it is in.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 1]
```diff
@@ -2067,8 +2075,16 @@ internal static bool CheckValEscape(SyntaxNode node, BoundExpression expr, uint
                 case BoundKind.ConditionalOperator:
                     var conditional = (BoundConditionalOperator)expr;
 
-                    return CheckValEscape(conditional.Consequence.Syntax, conditional.Consequence, escapeFrom, escapeTo, checkingReceiver: false, diagnostics: diagnostics) &&
-                           CheckValEscape(conditional.Alternative.Syntax, conditional.Alternative, escapeFrom, escapeTo, checkingReceiver: false, diagnostics: diagnostics);
+                    var consValid = CheckValEscape(conditional.Consequence.Syntax, conditional.Consequence, escapeFrom, escapeTo, checkingReceiver: false, diagnostics: diagnostics);
+
+                    if (consValid || conditional.IsByRef)
+                    {
```
Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: Not sure I get that. Why don't we check the alternative if the consequence is valid?

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenRefConditionalOperatorTests.cs [hunk 2]
```diff
@@ -662,10 +662,7 @@ static void Main()
             comp.VerifyEmitDiagnostics(
                 // (15,27): error CS8168: Cannot return local 'local1' by reference because it is not a ref local
```
Comment (OmarTawfik) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenRefConditionalOperatorTests.cs]: >because it is not a ref local [](start = 84, length = 29)

because it is?

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 1 above)
Comment (VSadov) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: Should be !consValid. And I need test, I guess.

---
In reply to: [139840188](https://github.com/dotnet/roslyn/pull/22203#discussion_r139840188) [](ancestors = 139840188)

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs [hunk 3]
```diff
@@ -45,23 +47,25 @@ static S1 MayWrap(ref int arg)
         }
     }
 ";
-            CreateStandardCompilation(text).VerifyDiagnostics(
-                // (21,42): error CS8168: Cannot return local 'local' by reference because it is not a ref local
+            CreateCompilationWithMscorlibAndSpan(text).VerifyDiagnostics(
```
Comment (OmarTawfik) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs]: >CreateCompilationWithMscorlibAndSpan [](start = 12, length = 36)

That reminds me, how are we tracking the addition of Span to the libraries we reference in testing? so that we can remove this helper function

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenRefConditionalOperatorTests.cs (hunk 2 above)
Comment (VSadov) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenRefConditionalOperatorTests.cs]: local1 is not a ref local so we cannot return it by reference.   The quality of cascaded error may be improved, but this is how it work right now.

---
In reply to: [139840517](https://github.com/dotnet/roslyn/pull/22203#discussion_r139840517) [](ancestors = 139840517)

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs (hunk 3 above)
Comment (VSadov) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs]: I am not even sure we have to change this. Span implementations are platform-specific and we only care about the APIs that exposed. As long as we call right methods, we are producing right code.
I will enter a bug to add some tests with actual span (I think we can use slow-span, since that should be able to run on any platform), but that is not a priority. 

---
In reply to: [139844972](https://github.com/dotnet/roslyn/pull/22203#discussion_r139844972) [](ancestors = 139844972)

Comment (VSadov) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs]: [https://github.com/dotnet/roslyn/issues/22213](https://github.com/dotnet/roslyn/issues/22213)

---
In reply to: [139847810](https://github.com/dotnet/roslyn/pull/22203#discussion_r139847810) [](ancestors = 139847810,139844972)

**Comment by VSadov** [comment]
test windows_release_unit64_prtest please

**Comment by VSadov** [comment]
@dotnet/roslyn-compiler - any more comments on this?

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 4]
```diff
@@ -949,21 +949,21 @@ private bool CheckPropertyValueKind(SyntaxNode node, BoundExpression expr, BindV
...
             ImmutableArray<RefKind> argRefKinds,
             ImmutableArray<int> argsToParamsOpt,
-            uint scopeOfTheContainingExpression)
+            uint scopeOfTheContainingExpression,
+            bool isRefEscape
+        )
         {
             // SPEC: (also applies to the CheckInvocationEscape counterpart)
             //
             //            An lvalue resulting from a ref-returning method invocation e1.M(e2, ...) is ref-safe - to - escape the smallest of the following scopes:
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: >smallest [](start = 129, length = 8)

Nit: "smallest" is ambiguous. Consider using "narrowest" here and a couple of lines below.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 5]
```diff
@@ -1577,10 +1566,11 @@ internal static uint GetRefEscape(BoundExpression expr, uint scopeOfTheContainin
                 case BoundKind.ConditionalOperator:
                     var conditional = (BoundConditionalOperator)expr;
 
-                    // byref conditional defers to one operand. Since are here without errors, both operands must match.
                     if (conditional.IsByRef)
                     {
-                        return GetRefEscape(conditional.Consequence, scopeOfTheContainingExpression);
+                        // ref conditional defers to its operands
+                        return Math.Max(GetRefEscape(conditional.Consequence, scopeOfTheContainingExpression),
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: Are we sure we want to relax the ref-safe-to-escape for ternary? Might that cause problems once we allow ref re-assignment (ie. the ternary could be used on the left)?

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 6]
```diff
@@ -2105,7 +2123,8 @@ internal static bool CheckValEscape(SyntaxNode node, BoundExpression expr, uint
                         checkingReceiver,
                         escapeFrom,
                         escapeTo,
-                        diagnostics);
+                        diagnostics,
+                        isRefEscape: false);
 
                 case BoundKind.ObjectCreationExpression:
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: It just occurred to me, are we covering tuples?

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 5 above)
Comment (VSadov) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: It cannot be on the left of ref assignment.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 6 above)
Comment (VSadov) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: Tuples cannot contain ref-structs since they are themselves not ref structs

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 5 above)
Comment (VSadov) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: It would ned to be a ref to a ref.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 4 above)
Comment (VSadov) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: That is the terminology from the spec proposal. I think we should fix it there. 
Here it is less important, since it is just a comment. Will fix when the spec is updated. (hopefully there will be no changes to rules too :-)
