### PR TITLE
Use synthesized methods for compiler-generated switch exceptions

### LINKED ISSUE #59601: Use synthesized wrapper methods for compiler-generated 'throw's
Perhaps we should do similar to what we did for !! and do the throw via a synthesized wrapper method. Would it be necessary to change the language of the [patterns proposal](https://github.com/dotnet/csharplang/blob/3c8559f186d4c5df5d1299b0eaa4e139ae130ab6/proposals/csharp-8.0/patterns.md#switch-expression) before changing the implementation to use such a helper? Intuitively it seems like no.

> ...
> If there is no such *switch_expression_arm*, the *switch_expression* throws an instance of the exception `System.Runtime.CompilerServices.SwitchExpressionException`.

_Originally posted by @RikkiGibson in https://github.com/dotnet/roslyn/issues/59449#issuecomment-1034551206_

---

The benefit of this change is that compiled switch expressions are easier to inline when they use a helper method instead of directly using the 'throw' instruction.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #59601

@RikkiGibson Tagging you since you self-assigned the issue.

### CODE REVIEW

**Comment by Youssef1313** [comment]
Using the existing `PrivateImplementationClass` will require some (unneeded) types to exist:

https://github.com/dotnet/roslyn/blob/e6ce86ce5dd83f68d51cf9ea64d2ce5f0b86e349/src/Compilers/Core/Portable/Emit/CommonPEModuleBuilder.cs#L1026-L1036

I expect this to be a problem for parameter null checking as well. @RikkiGibson Do you think it should be okay to require those types (and change the expected diagnostics of `MissingExceptions_01` test), or do some refactoring to not require them?

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedThrowSwitchExpressionExceptionMethod.cs [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+        internal override void GenerateMethodBody(TypeCompilationState compilationState, BindingDiagnosticBag diagnostics)
+        {
+            SyntheticBoundNodeFactory F = new SyntheticBoundNodeFactory(this, this.GetNonNullSyntaxNode(), compilationState, diagnostics);
+            F.CurrentFunction = this;
+
+            try
+            {
+                ParameterSymbol unmatchedValue = this.Parameters[0];
+
+                //throw new SwitchExpressionException((object)unmatchedValue);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedThrowSwitchExpressionExceptionMethod.cs:30]: I wasn't sure why the pseudocode includes a cast to object here. It looks like we assume that this method parameter type is the same as the constructor parameter type and don't do a conversion. I'm fine with that, just checking.

**Comment by RikkiGibson** [comment]
> Using the existing `PrivateImplementationClass` will require some (unneeded) types to exist:
> 
> https://github.com/dotnet/roslyn/blob/e6ce86ce5dd83f68d51cf9ea64d2ce5f0b86e349/src/Compilers/Core/Portable/Emit/CommonPEModuleBuilder.cs#L1026-L1036
> 
> I expect this to be a problem for parameter null checking as well. @RikkiGibson Do you think it should be okay to require those types (and change the expected diagnostics of `MissingExceptions_01` test), or do some refactoring to not require them?
> 
> #Resolved in [db3b4c5](https://github.com/dotnet/roslyn/commit/db3b4c5d20fd1129af1e47788931663f32fcddb1)

Special types are generally required to exist, so we shouldn't do work to try and continue working even in absence of them. That's one key difference between "special types" and "well known types"--compiler generally does try to keep working in the absence of "well known types".

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedThrowSwitchExpressionExceptionMethod.cs (hunk 1 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedThrowSwitchExpressionExceptionMethod.cs:30]: This is [an existing behavior](https://github.com/dotnet/roslyn/blob/b8bd69824fa1f4190cc0a24121828524ec5488ef/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_SwitchExpression.cs#L130), which if I understand correctly makes sure we call into the correct `SwitchExpressionException` constructor overload.

File: src/Compilers/Core/Portable/CodeGen/PrivateImplementationDetails.cs [hunk 2]
```diff
@@ -31,14 +31,37 @@ internal sealed class PrivateImplementationDetails : DefaultTypeDef, Cci.INamesp
...
+        internal const string SynthesizedThrowSwitchExpressionExceptionFunctionName = "ThrowSwitchExpressionException";
+        internal const string SynthesizedThrowSwitchExpressionExceptionParameterlessFunctionName = "ThrowSwitchExpressionExceptionParameterless";
+        internal const string SynthesizedThrowInvalidOperationExceptionFunctionName = "ThrowInvalidOperationException";
+
         private readonly CommonPEModuleBuilder _moduleBuilder;       //the module builder
-        private readonly Cci.ITypeReference _systemObject;           //base type
-        private readonly Cci.ITypeReference _systemValueType;        //base for nested structs
+        private readonly SyntaxNode _syntaxNodeOpt;
+        private readonly DiagnosticBag _diagnostics;
+        private Cci.ITypeReference SystemObject //base type
```
Comment (RikkiGibson) [inline src/Compilers/Core/Portable/CodeGen/PrivateImplementationDetails.cs:41]: Let's simplify by reverting this to the original implementation as much as possible (fetching the needed special types eagerly in the constructor, etc.), as well as related changes in `src/Compilers/Core/Portable/Emit/CommonPEModuleBuilder.cs`.

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedThrowSwitchExpressionExceptionMethod.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedThrowSwitchExpressionExceptionMethod.cs:30]:
```cs
// we cast to object here
ThrowSwitchExpressionException((object)arg);

void ThrowSwitchExpressionException(object param)
{
    // comment implies another cast to 'object' is included here, but there isn't such a cast
    throw new SwitchExpressionException(param);
}
```

It's perhaps more clear to remove the cast from this comment here, but I also don't have a strong opinion.
```suggestion
                //throw new SwitchExpressionException(unmatchedValue);
```

**Comment by RikkiGibson** [comment]
Great progress here. My only concern currently is I don't see tests where:

1. the parameterless ThrowSwitchExpressionException is used. For example, when switch input is a pointer type or ref struct.
2. InvalidOperationException is used. For example, if we use MakeMemberMissing on both SwitchExpressionException constructors.

**Comment by Youssef1313** [comment]
@RikkiGibson I updated some existing tests.

**Review by RikkiGibson — APPROVED** [review]

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler for second review.

File: src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs [hunk 3]
```diff
@@ -1810,6 +1810,77 @@ internal MethodSymbol EnsureThrowIfNullFunctionExists(SyntaxNode syntaxNode, Syn
...
+            TypeSymbol unmatchedValueType = factory.SpecialType(SpecialType.System_Object);
+            var sourceModule = SourceModule;
+
+            // use add-then-get pattern to ensure the symbol exists, and then ensure we use the single "canonical" instance added by whichever thread won the race.
+            privateImplClass.TryAddSynthesizedMethod(new SynthesizedThrowSwitchExpressionExceptionMethod(sourceModule, privateImplClass, returnType, unmatchedValueType).GetCciAdapter());
+            return (MethodSymbol)privateImplClass.GetMethod(PrivateImplementationDetails.SynthesizedThrowSwitchExpressionExceptionFunctionName)!.GetInternalSymbol()!;
+        }
+
+        /// <summary>
+        /// Creates the ThrowSwitchExpressionException helper if needed.
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs:1836]: >ThrowSwitchExpressionException [](http://example.com/codeflow?start=24&length=30)

ThrowSwitchExpressionExceptionParameterless

File: src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs [hunk 4]
```diff
@@ -1810,6 +1810,77 @@ internal MethodSymbol EnsureThrowIfNullFunctionExists(SyntaxNode syntaxNode, Syn
             Debug.Assert((object?)privateImplClass.GetMethod(PrivateImplementationDetails.SynthesizedThrowFunctionName)!.GetInternalSymbol() == internalSymbol.ThrowMethod);
             return internalSymbol;
         }
+
+        /// <summary>
+        /// Creates the ThrowSwitchExpressionException helper if needed.
+        /// </summary>
+        internal MethodSymbol EnsureThrowSwitchExpressionExceptionExists(SyntaxNode syntaxNode, SyntheticBoundNodeFactory factory, DiagnosticBag? diagnostics)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs:1817]: Can diagnostics ever be null? Same question for other helpers below

File: src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs [hunk 5]
```diff
@@ -1810,6 +1810,77 @@ internal MethodSymbol EnsureThrowIfNullFunctionExists(SyntaxNode syntaxNode, Syn
...
+            TypeSymbol returnType = factory.SpecialType(SpecialType.System_Void);
+            var sourceModule = SourceModule;
+
+            // use add-then-get pattern to ensure the symbol exists, and then ensure we use the single "canonical" instance added by whichever thread won the race.
+            privateImplClass.TryAddSynthesizedMethod(new SynthesizedParameterlessThrowMethod(
+                sourceModule,
+                privateImplClass,
+                returnType,
+                PrivateImplementationDetails.SynthesizedThrowInvalidOperationExceptionFunctionName,
+                factory.WellKnownMethod(WellKnownMember.System_InvalidOperationException__ctor)).GetCciAdapter());
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs:1881]: >factory.WellKnownMethod(WellKnownMember.System_InvalidOperationException__ctor) [](http://example.com/codeflow?start=16&length=79)

Do we have tests where either the exception type is missing or the constructor we need is missing?
You can look for tests that reference those well-known types/members.
This can be tested with MakeTypeMissing/MakeMemberMissing test helpers.
Same question applies for the other two exceptions affected by PR.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_SwitchExpression.cs [hunk 6]
```diff
@@ -151,6 +152,46 @@ bool implicitConversionExists(BoundExpression expression, TypeSymbol type)
                     return c.IsImplicit;
                 }
             }
+
+            private static BoundStatement ConstructThrowSwitchExpressionExceptionHelperCall(SyntheticBoundNodeFactory factory, BoundExpression unmatchedValue)
+            {
+                var module = factory.ModuleBuilderOpt!;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_SwitchExpression.cs:158]: We should use an assertion rather than suppression here. Also applies to added methods below
We try to use suppressions sparingly: 1. inside assertions, 2. if the non-nullness is implied by preceding logic/check in method but compiler is just unable to see it

File: src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs (hunk 4 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs:1817]: @jcouv I had copied the existing signature for `ThrowIfNull`

https://github.com/dotnet/roslyn/blob/534c0e8d04e58044c66ef4f66eeafd255a18749d/src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs#L1790

But I agree we should change it to non-nullable.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_SwitchExpression.cs (hunk 6 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_SwitchExpression.cs:158]: @jcouv This was a copy from:

https://github.com/dotnet/roslyn/blob/534c0e8d04e58044c66ef4f66eeafd255a18749d/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_NullChecking.cs#L41

But I agree.

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterlessThrowMethod.cs [hunk 7]
```diff
@@ -0,0 +1,47 @@
...
+        internal override void GenerateMethodBody(TypeCompilationState compilationState, BindingDiagnosticBag diagnostics)
+        {
+            SyntheticBoundNodeFactory F = new SyntheticBoundNodeFactory(this, this.GetNonNullSyntaxNode(), compilationState, diagnostics);
+            F.CurrentFunction = this;
+
+            try
+            {
+                //throw new GivenException();
+
+                var body = F.Block(
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterlessThrowMethod.cs:33]: Do we need the block?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_SwitchExpression.cs [hunk 8]
```diff
@@ -151,6 +152,46 @@ bool implicitConversionExists(BoundExpression expression, TypeSymbol type)
...
+                var diagnosticSyntax = factory.CurrentFunction.GetNonNullSyntaxNode();
+                var diagnostics = factory.Diagnostics.DiagnosticBag;
+                Debug.Assert(diagnostics is not null);
+                var throwSwitchExpressionExceptionMethod = module.EnsureThrowSwitchExpressionExceptionExists(diagnosticSyntax, factory, diagnostics);
+                var call = factory.Call(
+                    receiver: null,
+                    throwSwitchExpressionExceptionMethod,
+                    arg0: unmatchedValue);
+                return factory.HiddenSequencePoint(factory.ExpressionStatement(call));
```
[the remark this answers is not in the document]
Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_SwitchExpression.cs:167]: @jcouv I was following the same that was done for `!!`:

https://github.com/dotnet/roslyn/blob/534c0e8d04e58044c66ef4f66eeafd255a18749d/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_NullChecking.cs#L53

I don't know what hidden sequence points mean to be honest :(

File: src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs (hunk 4 above)
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs:1817]: nit: I couldn't find a test for `VerifyIL` on `ThrowSwitchExpressionException`. Consider adding.
Also, it would be good to ensure we have tests executing those three private implementation methods (`CompileAndVerify` with `expectedOutput:`).

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 6). Overall looks good, only minor feedback and coverage recommendations

File: src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs (hunk 5 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs:1881]: @jcouv 

- `UnmatchedInput_04` tests `SwitchExpressionException(object)` constructor.
- `UnmatchedInput_02` makes `SwitchExpressionException(object)` missing (or actually it's already missing, the test just didn't declare it explicitly). So this tests the parameterless overload of the constructor.
- `UnmatchedInput_01` doesn't provide `SwitchExpressionException` at all. So this tests `InvalidOperationException`.

There doesn't seem to be any tests that makes `InvalidOperationException` missing though.

None of the tests use `VerifyEmitDiagnostics`, so I'll add it to the existing tests.

I'll:

- Update the existing tests to verify specific ctors are missing.
- Use VerifyEmitDiagnostics in those tests.
- Add new test where InvalidOperationException is also missing.

File: src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs (hunk 4 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Emitter/Model/PEModuleBuilder.cs:1817]: Will update `UnmatchedInput_04` to verify IL.

`UnmatchedInput_04`, `UnmatchedInput_02`, and `UnmatchedInput_01` all execute the synthesized methods using `CompileAndVerify`.

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterlessThrowMethod.cs (hunk 7 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterlessThrowMethod.cs:33]: Seems unnecessary. Will remove.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 7)

**Review by RikkiGibson — APPROVED** [review]
