### PR TITLE
Improve speculation for AsNewClauseSyntax [fixes crash]

### LINKED ISSUE #14554: Crash during Inline Rename conflict detection in VB
_Reported via Visual Studio Feedback_

**Steps to Reproduce**:
1. Start with the following code.

``` VB
Public MustInherit Class Base
    Public MustOverride Function Close() As Boolean
    Public MustOverride Function Save() As Boolean
End Class

Public Class Crasher
    Sub New(a As Action)
    End Sub
End Class

Public Class Other
    Inherits Base

    Public Sub New(vm As Base)
        Me.Vm = vm
    End Sub

    Public ReadOnly Property Vm As Base

    Public ReadOnly Property Crash As New Crasher(Sub()
                                                      Vm.Close()
                                                  End Sub)
    Public Overrides Function Close() As Boolean
        Return False
    End Function

    Public Overrides Function Save() As Boolean
        Return False
    End Function
End Class

Public Class Tester
    Inherits Base

    Public Overrides Function Close() As Boolean
        Return False
    End Function

    Public Overrides Function Save() As Boolean
        Return False
    End Function
End Class
```
1. Invoke Inline Rename (<kbd>F2</kbd> or <kbd>Ctrl+R, R</kbd>) on `Tester.Close()`
2. Rename `Close` to `Save`

**Expected Behavior**: An unresolvable conflict is reported

**Actual Behavior**: VS crashes

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #14554

**Customer scenario**

A crash occurs any time rename does conflict detection in an AsNewClause in VB. This means that the AsNewClause would have to have some code in it with identifiers that could possibly conflict with the name of an identifier being renamed. The easiest way to get into this situation is to have executable code in your AsNewClause (being passed to an Action or Func parameter on the constructor). I would guess that this is a fairly infrequent problem, but it was reported by a customer.

**Bugs this fixes:** 

https://github.com/dotnet/roslyn/issues/14554

**Workarounds, if any**

If the conflicting name isn't the final new name in the rename session and just happens to be on the path from old name to new name, then the user can avoid passing through the conflicting name on the way to the new name, but that's a pretty convoluted workaround. In the case where the final new name of the rename session actually matches the identifier in the AsNewClause, the workaround is to do the rename manually.

**Risk**

Moderate. The change to the VisualBasicRenameRewriterLanguageService should have no effect on cases that don't involve AsNewClauses (so probably no regressions there). The change to SpeculationAnalyzer ensures we return a non-null speculative model instead of a null one when we encounter an AsNewClause. This could possibly impact other consumers.

**Performance impact**

Low perf impact, it's doing the same sort of speculative semantic model work that other parts of the rename process already do.

**Is this a regression from a previous update?**

At one point, we had an overload of GetSpeculativeSemanticModel for AsNewClauses, but it was reverted in http://vstfdevdiv:8080/DevDiv2/Roslyn/_versionControl/changeset/995416?_a=summary due to http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems?id=680657&_a=edit

**Root cause analysis:**

The compiler doesn't offer an API to speculate on AsNewClauses, so a workaround was implemented to rewrite AsNewClauses to EqualsValueClauses during features that need to speculate on AsNewClauses. This workaround was not implemented in all of the required locations. I added a Rename test to ensure the crash no longer happens. A better fix could be implemented by fixing https://github.com/dotnet/roslyn/issues/15593, but that isn't currently on the schedule.

**How was the bug found?**

Customer reported.

### CODE REVIEW

**Comment by dpoeschl** [comment]
@mavasani Does this match what you expected to see?

File: src/Workspaces/VisualBasic/Portable/Utilities/SpeculationAnalyzer.vb [hunk 1]
```diff
@@ -140,6 +140,16 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Utilities
                 Case SyntaxKind.RangeArgument
                     semanticModel.TryGetSpeculativeSemanticModel(position, DirectCast(nodeToSpeculate, RangeArgumentSyntax), speculativeModel)
                     Return speculativeModel
+
+                Case SyntaxKind.AsNewClause
+                    ' Speculation is not supported for AsNewClauseSyntax nodes.
```
Comment (mavasani) [inline src/Workspaces/VisualBasic/Portable/Utilities/SpeculationAnalyzer.vb]: I filed https://github.com/dotnet/roslyn/issues/15593 for this missing API.

**Comment by dpoeschl** [comment]
Tagging @dotnet/roslyn-ide for additional reviews.

File: src/Workspaces/VisualBasic/Portable/Rename/VisualBasicRenameRewriterLanguageService.vb [hunk 2]
```diff
@@ -174,6 +174,11 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Rename
                 Me._speculativeModel = GetSemanticModelForNode(newNode, Me._semanticModel)
                 Debug.Assert(_speculativeModel IsNot Nothing, "expanding a syntax node which cannot be speculated?")
 
+                ' There are cases when we change the type of node to make speculation work (e.g.,
+                ' for AsNewClauseSyntax), so getting the newNode from the _speculativeModel 
+                ' ensures the final node replacing the original node is found.
+                newNode = Me._speculativeModel.SyntaxTree.GetRoot(_cancellationToken).GetAnnotatedNodes(Of SyntaxNode)(annotation).First()
```
Comment (jmarolf) [inline src/Workspaces/VisualBasic/Portable/Rename/VisualBasicRenameRewriterLanguageService.vb]: We should check everywhere that the speculative semantic model is used since if you speculate on an `As New` node you will get a different node back

File: src/Workspaces/VisualBasic/Portable/Utilities/SpeculationAnalyzer.vb [hunk 3]
```diff
@@ -140,6 +140,16 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Utilities
                 Case SyntaxKind.RangeArgument
                     semanticModel.TryGetSpeculativeSemanticModel(position, DirectCast(nodeToSpeculate, RangeArgumentSyntax), speculativeModel)
                     Return speculativeModel
+
+                Case SyntaxKind.AsNewClause
```
Comment (jmarolf) [inline src/Workspaces/VisualBasic/Portable/Utilities/SpeculationAnalyzer.vb]: Is there a way the check for what is supported can be integrated with this method so they don't get out of sync?

**Comment by DustinCampbell** [comment]
Tagging @MattGertz for approval. Note that the original bug is marked for 2.0 (RC.2) so I marked this PR as the same. Note that the original bug was created from a report received through VS feedback.

**Comment by MattGertz** [comment]
@dpoeschl @DustinCampbell Rejected for RC.2; please move to RC.3.  Although this is customer-reported and this is low-risk, I want to play it safe through the (understaffed) holidays.  The hit count is apparently low and RC.3 will be fine for this; that will still allow us feedback from the customer before RTW.

**Comment by DustinCampbell** [comment]
No problem. It's already on "master", so it's ready for RC.3 approval.

**Comment by MattGertz** [comment]
Approved for RC.3.

File: src/EditorFeatures/Test2/Rename/InlineRenameTests.vb [hunk 4]
```diff
@@ -1451,5 +1451,46 @@ End Class
...
+                                    </Project>
+                                </Workspace>)
+
+                Dim session = StartSession(workspace)
+
+                Dim caretPosition = workspace.Documents.Single(Function(d) d.CursorPosition.HasValue).CursorPosition.Value
+                Dim textBuffer = workspace.Documents.Single().TextBuffer
+
+                ' Ensure the rename doesn't crash
+                textBuffer.Insert(caretPosition, "e")
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Test2/Rename/InlineRenameTests.vb]: Why is this being tested through inline rename vs. the tests that test rename directly?

File: src/Workspaces/VisualBasic/Portable/Utilities/SpeculationAnalyzer.vb (hunk 1 above)
Comment (jasonmalinowski) [inline src/Workspaces/VisualBasic/Portable/Utilities/SpeculationAnalyzer.vb]: Perhaps we should update the code too to reference the bug.

File: src/Workspaces/VisualBasic/Portable/Rename/VisualBasicRenameRewriterLanguageService.vb (hunk 2 above)
Comment (jasonmalinowski) [inline src/Workspaces/VisualBasic/Portable/Rename/VisualBasicRenameRewriterLanguageService.vb]: Indeed -- doesn't @jmarolf's concern raise the risk of this change?
