### PR TITLE
Fixes a subtle bug in branch optimizer.

### LINKED ISSUE #4838: Incorrect compiler output for code involving async, loop, switch.
I've spotted an issue with compilation output from VS 2015 Enterprise (RTM version).

The following code involving async, loop and switch constructs causes  ```ArgumentOutOfRangeException``` from ```default:``` branch when run, whereas a return from ```case 0:``` is expected. Apparently the compiler generates code without ```case 0:``` branch.

**Code**
```
using System;
using System.Threading.Tasks;

namespace ConsoleApplication11
{
    class Program
    {
        static void Main()
        {
            M(0).Wait();
        }

        static async Task M(int input)
        {
            for (;;)
            {
                var value = await Task.FromResult(input);
                switch (value)
                {
                    case 0:
                        return;
                    case 3:
                        return;
                    case 4:
                        continue;
                    case 100:
                        return;
                    default:
                        throw new ArgumentOutOfRangeException("Unknown value: " + value);
                }
            }
        }
    }
}
```

**Compile with optimizations**
```
D:\dev\bugs>"c:\Program Files (x86)\MSBuild\14.0\Bin\csc.exe" Program1.cs /o+
Microsoft (R) Visual C# Compiler version 1.0.0.50618
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Output**
```

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Unknown value: 0
   at ConsoleApplication11.Program.<M>d__1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ConsoleApplication11.Program.Main()
```

### LINKED ISSUE #4839: Invalid compilation output for code involving async and switch
I've spotted an issue with compilation output from VS 2015 Enterprise (RTM version).

The compiler generates invalid IL for the following code involving async and switch constructs.

**Code**
```
using System;
using System.Threading.Tasks;

namespace ConsoleApplication11
{
    class Program
    {
        static void Main()
        {
            M(0).Wait();
        }
 
        static async Task M(int input)
        {
            var value = await Task.FromResult(input);
            switch (value)
            {
                case 0:
                    return;
                case 1:
                    return;
            }
        }
    }
}
```

**Compile with optimizations**
```
D:\dev\bugs>"c:\Program Files (x86)\MSBuild\14.0\Bin\csc.exe" Program2.cs /o+
Microsoft (R) Visual C# Compiler version 1.0.0.50618
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Output**
```
Unhandled Exception: System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at ConsoleApplication11.Program.<M>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at ConsoleApplication11.Program.M(Int32 input)
   at ConsoleApplication11.Program.Main()
```

### PR DESCRIPTION
**Pull request by VSadov**
"branch over branch" optimization eliminates chains of trivial basic blocks from the graph, which is correct as long as trivial blocks are not reachable individually from outside via branches.
The "same as next" optimization can make a block trivial and if it was targeted by a branch, break the assumption, leading to a rare situation of some branches having stale offsets.

The fix makes sure if a block becomes trivial, its labels are moved to the next nontrivial block.

Fixes #4838
Fixes #4839

### CODE REVIEW

**Comment by VSadov** [comment]
@AlekseyTs @gafter @agocke @jaredpar - please review

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs [hunk 1]
```diff
@@ -3463,5 +3463,175 @@ public void AwaitInStaticInitializer()
...
+                return;
+            case 1:
+                return;
+        }
+    }
+}
+";
+            var comp = CreateCompilation(source, options: TestOptions.DebugExe);
+            CompileAndVerify(comp);
+            CompileAndVerify(comp.WithOptions(TestOptions.ReleaseExe));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs]: Does it make sense to check IL since the program doesn't output anything?

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs [hunk 2]
```diff
@@ -3463,5 +3463,175 @@ public void AwaitInStaticInitializer()
...
+                    return;
+                case ""b"":
+                    return;
+            }
+        }
+    }
+";
+            var comp = CreateCompilation(source, options: TestOptions.DebugExe);
+            CompileAndVerify(comp);
+            CompileAndVerify(comp.WithOptions(TestOptions.ReleaseExe));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs]: Does it make sense to check IL since the program doesn't output anything?

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs [hunk 3]
```diff
@@ -3463,5 +3463,175 @@ public void AwaitInStaticInitializer()
...
+                default:
+                    throw new ArgumentOutOfRangeException(""Unknown value: "" + value);
+            }
+        }
+    }
+}
+";
+            var comp = CreateCompilation(source, options: TestOptions.DebugExe);
+            CompileAndVerify(comp);
+            CompileAndVerify(comp.WithOptions(TestOptions.ReleaseExe));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs]: Does it make sense to check IL since the program doesn't output anything?

Comment (VSadov) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs]: I have one test (the simplest) that checks actual IL. Others are basically repro scenarios from the bugs. 
For the purpose of this fix, async, strings, loops are  only adding more clutter to essentially same scenario, but I added them to make sure that the bugs mentioned are indeed fixed. 
I think as long as the repros pass PEVerify they are good enough as tests.

**Comment by AlekseyTs** [comment]
LGTM
