### PR TITLE
Bugfix: GetAwaitExpressionInfo ignores BoundConversion

### LINKED ISSUE #54298: Missing handling for `BoundConversion` in GetAwaitExpressionInfo
**Version Used**: 80b8a9b

**Steps to Reproduce**:

compile and run:

```csharp
using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;


var text = @"
using System;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

MyAwaitable Get()
{
    return new MyAwaitable();
}

var x = Get();
x.SetValue(42);

Console.WriteLine(await x + ""!"");

struct MyAwaitable
{
    private ValueTask<int> task;
    private TaskCompletionSource<int> source;

    private TaskCompletionSource<int> Source
    {
        get
        {
            if (source == null)
            {
                source = new TaskCompletionSource<int>();
                task = new ValueTask<int>(source.Task);
            }
            return source;
        }
    }
    internal ValueTask<int> Task
    {
        get
        {
            _ = Source;
            return task;
        }
    }

    public void SetValue(int i)
    {
        Source.SetResult(i);
    }
}

static class MyAwaitableExtension
{
    public static System.Runtime.CompilerServices.ValueTaskAwaiter<int> GetAwaiter(this MyAwaitable a)
    {
        return a.Task.GetAwaiter();
    }
}
";

var tree = SyntaxTree(ParseCompilationUnit(text));

var refApis = AppDomain.CurrentDomain.GetAssemblies().Select(a => MetadataReference.CreateFromFile(a.Location));
var com = CSharpCompilation.Create("something", new []{ tree }, refApis );

var diag =com.GetDiagnostics().Where(e => e.Severity == DiagnosticSeverity.Error).ToList();

foreach(var d in diag)
{
  Console.WriteLine(d);    
}

var model = com.GetSemanticModel(tree);
var awaitExpression = tree.GetRoot().DescendantNodes().OfType<AwaitExpressionSyntax>().First();
var awaitInfo = model.GetAwaitExpressionInfo(awaitExpression);

Console.WriteLine(awaitInfo.GetAwaiterMethod == null);
```

**Expected Behavior**:
Roslyn should find / return the `GetAwaiterMethod` - it should print `False`.

**Actual Behavior**:
`GetAwaiterMethod` is null - it prints `True`

### PR DESCRIPTION
**Pull request by bernd5**
fixes #54298
Bugfix to handle "BoundConversion"

### CODE REVIEW

**Comment by bernd5** [comment]
fixes #54298

File: src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs [hunk 1]
```diff
@@ -898,9 +898,9 @@ public override AwaitExpressionInfo GetAwaitExpressionInfo(AwaitExpressionSyntax
             {
                 throw new ArgumentException("node.Kind==" + node.Kind());
             }
-
-            var bound = GetUpperBoundNode(node);
-            BoundAwaitableInfo awaitableInfo = (((bound as BoundExpressionStatement)?.Expression ?? bound) as BoundAwaitExpression)?.AwaitableInfo;
+            var boundAwait = FindBoundAwait(GetLowerBoundNode(node), node)
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:901]: We have a helper method for getting all the bound nodes of an expression: `GetBoundNodes`.

Comment (333fred) [reply src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:901]: I'm also not sure that we need to search both upper and lower bound nodes. I would think the upper bound node should be sufficient.

File: src/Compilers/CSharp/Test/Semantic/Semantics/AwaitExpressionTests.cs [hunk 2]
```diff
@@ -20,6 +20,97 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+}";
+            var refApis = System.AppDomain.CurrentDomain.GetAssemblies().Where(a => !a.IsDynamic).Select(
+                a => MetadataReference.CreateFromFile(a.Location)
+            );
+            var tree = SyntaxFactory.SyntaxTree(SyntaxFactory.ParseCompilationUnit(text));
+            var csCompilation = CSharpCompilation.Create("something",
+                   new[] { tree },
+                   refApis,
+                   new CSharpCompilationOptions(OutputKind.ConsoleApplication)
+            );
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/AwaitExpressionTests.cs:92]: There are helper methods to construct compilations.
```
var comp = CreateCompilationWithMscorlib45(text);
var tree = comp.SyntaxTrees.Single();
```

File: src/Compilers/CSharp/Test/Semantic/Semantics/AwaitExpressionTests.cs [hunk 3]
```diff
@@ -20,6 +20,97 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+
+            var model = csCompilation.GetSemanticModel(tree);
+            var awaitExpression = tree.GetRoot().DescendantNodes().OfType<AwaitExpressionSyntax>().First();
+
+            var op = model.GetOperation(awaitExpression);
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/AwaitExpressionTests.cs:97]: >var op [](http://example.com/codeflow?start=12&length=6)

This local does not appear to be used. If the call to `GetOperation()` is part of the test, consider asserting the returned value is as expected.

File: src/Compilers/CSharp/Test/Semantic/Semantics/AwaitExpressionTests.cs [hunk 4]
```diff
@@ -20,6 +20,97 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+using System.Threading.Tasks;
+
+static class App{
+    public static async Task Main(){
+        MyAwaitable Get()
+        {
+            return new MyAwaitable();
+        }
+
+        var x = Get();
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/AwaitExpressionTests.cs:38]: Is the local function required for the test? If not, perhaps `var x = new MyAwaitable();` instead.

File: src/Compilers/CSharp/Test/Semantic/Semantics/AwaitExpressionTests.cs [hunk 5]
```diff
@@ -70,15 +161,17 @@ public void DefaultAwaitExpressionInfo()
             Assert.Equal(0, info.GetHashCode());
         }
 
-        private AwaitExpressionInfo GetAwaitExpressionInfo(string text, out CSharpCompilation compilation, params DiagnosticDescription[] diagnostics)
+        private AwaitExpressionInfo GetAwaitExpressionInfo(string text,
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/AwaitExpressionTests.cs:164]: >GetAwaitExpressionInfo [](http://example.com/codeflow?start=36&length=22)

Consider reverting the changes to this method if not needed.

File: src/Compilers/CSharp/Test/Semantic/Semantics/AwaitExpressionTests.cs (hunk 2 above)
Comment (bernd5) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AwaitExpressionTests.cs]: good to know, thanks

File: src/Compilers/CSharp/Test/Semantic/Semantics/AwaitExpressionTests.cs (hunk 3 above)
Comment (bernd5) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AwaitExpressionTests.cs]: Oh, I used it just while debugging...

File: src/Compilers/CSharp/Test/Semantic/Semantics/AwaitExpressionTests.cs (hunk 4 above)
Comment (bernd5) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AwaitExpressionTests.cs]: it is not required - I remove it

File: src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs (hunk 1 above)
Comment (bernd5) [reply src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:901]: Before it was just the upper node - but it was wrapped in a `BoundConversion` which was not handled.
Isn't the lower node just the node we look for?

Comment (bernd5) [reply src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:901]: `GetBoundNodes` would be a good fallback if we didn't find it directly? But are there other cases we miss here?

File: src/Compilers/CSharp/Test/Semantic/Semantics/AwaitExpressionTests.cs (hunk 5 above)
Comment (bernd5) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AwaitExpressionTests.cs]: I do

File: src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs (hunk 1 above)
Comment (333fred) [reply src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs]: Generally, here's how the upper/lower set works: for every syntax node, there is a BoundNode that is highest in the tree, and a bound node that is lowest in the tree. It's very possible that just `GetLowerBoundNode` here will give us the bound node we're interested in with no need to go to the highest node, but that needs to be tested. If not, what I was suggesting is using the `GetBoundNodes` overload that has multiple out parameters for the highest and lowest nodes.

File: src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs [hunk 6]
```diff
@@ -899,8 +899,19 @@ public override AwaitExpressionInfo GetAwaitExpressionInfo(AwaitExpressionSyntax
                 throw new ArgumentException("node.Kind==" + node.Kind());
             }
 
-            var bound = GetUpperBoundNode(node);
-            BoundAwaitableInfo awaitableInfo = (((bound as BoundExpressionStatement)?.Expression ?? bound) as BoundAwaitExpression)?.AwaitableInfo;
+            //usually the GetUpperBoundNode is sufficient, but we need to handle
+            //for example BoundExpressionStatement or BoundConversion here, too.
+            BoundAwaitExpression boundAwait = null;
+            foreach (var boundNode in GetBoundNodes(node))
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:905]: Did you look into just using `GetLowerBoundNode` here and assuming it's a BoundAwaitExpression in all cases?

Comment (bernd5) [reply src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:905]: Yes, I actually can't imagine which node code be there beside the `BoundAwaitExpression` but to be 100% sure I would like to avoid making here any assumptions.
Usually `GetBoundNodes(node)` returns just a single node which is the one we are looking for - but as we have seen there are cases with more nodes like an additional `BoundConversion`.

**Comment by bernd5** [comment]
Why is the test failing?

File: src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs (hunk 6 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:905]: > foreach (var boundNode in GetBoundNodes(node)) [](http://example.com/codeflow?start=11&length=47)

We should not be inventing new ways to locate nodes. If ```GetLowerBoundNode``` isn't working, I would like to understand why. Otherwise, we should simply use it because it appears that the bug was caused by the usage of the wrong API.

File: src/Compilers/CSharp/Test/Semantic/Semantics/AwaitExpressionTests.cs [hunk 7]
```diff
@@ -20,6 +20,85 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+    {
+        return a.Task.GetAwaiter();
+    }
+}";
+
+            var csCompilation = CreateCompilation(text, targetFramework: TargetFramework.NetCoreAppAndCSharp);
+            var tree = csCompilation.SyntaxTrees.Single();
+
+            var model = csCompilation.GetSemanticModel(tree);
+            var awaitExpression = tree.GetRoot().DescendantNodes().OfType<AwaitExpressionSyntax>().First();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/AwaitExpressionTests.cs:84]: >awaitExpression [](http://example.com/codeflow?start=16&length=15)

Please assert string representation of the located node. This will make the test more readable and will ensure we are testing what is intended.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 6)

File: src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs (hunk 6 above)
Comment (bernd5) [reply src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs]: Okay, I use simply `GetLowerBoundNode`

File: src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs [hunk 8]
```diff
@@ -899,8 +899,10 @@ public override AwaitExpressionInfo GetAwaitExpressionInfo(AwaitExpressionSyntax
                 throw new ArgumentException("node.Kind==" + node.Kind());
             }
 
-            var bound = GetUpperBoundNode(node);
-            BoundAwaitableInfo awaitableInfo = (((bound as BoundExpressionStatement)?.Expression ?? bound) as BoundAwaitExpression)?.AwaitableInfo;
+            BoundAwaitExpression boundAwait = (BoundAwaitExpression)GetLowerBoundNode(node);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:902]: >GetLowerBoundNode [](http://example.com/codeflow?start=68&length=17)

I do not expect any changes in this function except a change from using GetUpperBoundNode to using GetLowerBoundNode. Our assumptions of what might happen do not change

Comment (bernd5) [reply src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:902]: Could you explain what you mean?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:902]: I mean ```(((bound as BoundExpressionStatement)?.Expression ?? bound) as BoundAwaitExpression)?.AwaitableInf``` shouldn't change. Conditional access shouldn't be eliminated, asserts should not be added. Only this line ```var bound = GetUpperBoundNode(node);``` should change in this function. Othe lines should not be touched, even to change formatting (we don't welcome style-only changes, BTW).

Comment (bernd5) [reply src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs]: In my eyes this is wrong because we should never get a `BoundExpressionStatement` here - but it is your code.

File: src/Compilers/CSharp/Test/Semantic/Semantics/AwaitExpressionTests.cs [hunk 9]
```diff
@@ -20,6 +20,85 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+            Assert.Equal("[234..241)", awaitExpression.Location.SourceSpan.ToString());
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/AwaitExpressionTests.cs:85]: >[234..241) [](http://example.com/codeflow?start=26&length=10)

This is not a "string representation of the located node". For example, I cannot tell from this what node we are using.

Comment (bernd5) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AwaitExpressionTests.cs:85]: Sorry I misread your comment - I don't like such asserts, too. I change it.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 9)

**Review by 333fred — APPROVED** [review]
LGTM (commit 10)

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 10)

**Comment by AlekseyTs** [comment]
@bernd5 Thanks for the contribution.
