### PR TITLE
Fix tests in PatternMatchingTests that fails in cultures with differe…

### LINKED ISSUE #12094: [Test Failure] PatternMatchingTests fails in non-English locale
8 tests in PatternMatchingTests fails when running in a locale having decimal separator different from '.' Output of test when running in Norwegian locale (with decimal separator ','):
```
------ Test started: Assembly: Roslyn.Compilers.CSharp.Semantic.UnitTests.dll ------

Test 'Microsoft.CodeAnalysis.CSharp.UnitTests.PatternMatchingTests.PatternInFieldInitializer' failed: Microsoft.CodeAnalysis.Test.Utilities.ExecutionException : 
Execution failed for assembly 'C:\Users\borge\AppData\Local\Temp\'.
Expected: False for 1
True for 10
False for 1.2
Actual:   False for 1
True for 10
False for 1,2


	HostedRuntimeEnvironment.cs(263,0): at Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.Execute(String moduleName, String expectedOutput)
	CommonTestBase.CompilationVerifier.cs(109,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.Emit(String expectedOutput, IEnumerable`1 manifestResources, Boolean peVerify, SignatureDescription[] expectedSignatures)
	f:\git\roslyn\src\Test\Utilities\Desktop\CommonTestBase.cs(204,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(Compilation compilation, IEnumerable`1 dependencies, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Action`1 assemblyValidator, Action`1 symbolValidator, Boolean verify)
	f:\git\roslyn\src\Test\Utilities\Desktop\CommonTestBase.cs(129,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify)
	f:\git\roslyn\src\Compilers\Test\Utilities\CSharp.Desktop\CSharpTestBase.cs(195,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 validator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify)
	Semantics\PatternMatchingTests.cs(324,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.PatternMatchingTests.PatternInFieldInitializer()

Test 'Microsoft.CodeAnalysis.CSharp.UnitTests.PatternMatchingTests.PatternInExpressionBodiedLambda' failed: Microsoft.CodeAnalysis.Test.Utilities.ExecutionException : 
Execution failed for assembly 'C:\Users\borge\AppData\Local\Temp\'.
Expected: False for 1
True for 10
False for 1.2
Actual:   False for 1
True for 10
False for 1,2


	HostedRuntimeEnvironment.cs(263,0): at Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.Execute(String moduleName, String expectedOutput)
	CommonTestBase.CompilationVerifier.cs(109,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.Emit(String expectedOutput, IEnumerable`1 manifestResources, Boolean peVerify, SignatureDescription[] expectedSignatures)
	f:\git\roslyn\src\Test\Utilities\Desktop\CommonTestBase.cs(204,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(Compilation compilation, IEnumerable`1 dependencies, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Action`1 assemblyValidator, Action`1 symbolValidator, Boolean verify)
	f:\git\roslyn\src\Test\Utilities\Desktop\CommonTestBase.cs(129,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify)
	f:\git\roslyn\src\Compilers\Test\Utilities\CSharp.Desktop\CSharpTestBase.cs(195,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 validator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify)
	Semantics\PatternMatchingTests.cs(425,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.PatternMatchingTests.PatternInExpressionBodiedLambda()

Test 'Microsoft.CodeAnalysis.CSharp.UnitTests.PatternMatchingTests.PatternInExpressionBodiedLocalFunction' failed: Microsoft.CodeAnalysis.Test.Utilities.ExecutionException : 
Execution failed for assembly 'C:\Users\borge\AppData\Local\Temp\'.
Expected: False for 1
True for 10
False for 1.2
Actual:   False for 1
True for 10
False for 1,2


	HostedRuntimeEnvironment.cs(263,0): at Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.Execute(String moduleName, String expectedOutput)
	CommonTestBase.CompilationVerifier.cs(109,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.Emit(String expectedOutput, IEnumerable`1 manifestResources, Boolean peVerify, SignatureDescription[] expectedSignatures)
	f:\git\roslyn\src\Test\Utilities\Desktop\CommonTestBase.cs(204,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(Compilation compilation, IEnumerable`1 dependencies, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Action`1 assemblyValidator, Action`1 symbolValidator, Boolean verify)
	f:\git\roslyn\src\Test\Utilities\Desktop\CommonTestBase.cs(129,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify)
	f:\git\roslyn\src\Compilers\Test\Utilities\CSharp.Desktop\CSharpTestBase.cs(195,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 validator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify)
	Semantics\PatternMatchingTests.cs(390,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.PatternMatchingTests.PatternInExpressionBodiedLocalFunction()

Test 'Microsoft.CodeAnalysis.CSharp.UnitTests.PatternMatchingTests.UnconstrainedPatternTest' failed: Microsoft.CodeAnalysis.Test.Utilities.ExecutionException : 
Execution failed for assembly ''.
Expected: expression 1 is not String
expression foo is not Int32
expression 1 is Int32 1
expression 1.2 is not Int32
expression 1.2 is Double 1.2
expression 1 is Nullable`1 1
expression  is not Nullable`1
expression  is not String
Actual:   expression 1 is not String
expression foo is not Int32
expression 1 is Int32 1
expression 1,2 is not Int32
expression 1,2 is Double 1,2
expression 1 is Nullable`1 1
expression  is not Nullable`1
expression  is not String


	HostedRuntimeEnvironment.cs(263,0): at Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.Execute(String moduleName, String expectedOutput)
	CommonTestBase.CompilationVerifier.cs(109,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.Emit(String expectedOutput, IEnumerable`1 manifestResources, Boolean peVerify, SignatureDescription[] expectedSignatures)
	f:\git\roslyn\src\Test\Utilities\Desktop\CommonTestBase.cs(204,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(Compilation compilation, IEnumerable`1 dependencies, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Action`1 assemblyValidator, Action`1 symbolValidator, Boolean verify)
	f:\git\roslyn\src\Test\Utilities\Desktop\CommonTestBase.cs(129,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify)
	f:\git\roslyn\src\Compilers\Test\Utilities\CSharp.Desktop\CSharpTestBase.cs(195,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 validator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify)
	Semantics\PatternMatchingTests.cs(189,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.PatternMatchingTests.UnconstrainedPatternTest()

Test 'Microsoft.CodeAnalysis.CSharp.UnitTests.PatternMatchingTests.GeneralizedSwitchStatement' failed: Microsoft.CodeAnalysis.Test.Utilities.ExecutionException : 
Execution failed for assembly ''.
Expected: one
int 10
long 20
double 1.2
class String foo
struct Boolean True
null
struct X X
class Exception System.Exception: boo

Actual:   one
int 10
long 20
double 1,2
class String foo
struct Boolean True
null
struct X X
class Exception System.Exception: boo


	HostedRuntimeEnvironment.cs(263,0): at Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.Execute(String moduleName, String expectedOutput)
	CommonTestBase.CompilationVerifier.cs(109,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.Emit(String expectedOutput, IEnumerable`1 manifestResources, Boolean peVerify, SignatureDescription[] expectedSignatures)
	f:\git\roslyn\src\Test\Utilities\Desktop\CommonTestBase.cs(204,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(Compilation compilation, IEnumerable`1 dependencies, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Action`1 assemblyValidator, Action`1 symbolValidator, Boolean verify)
	f:\git\roslyn\src\Test\Utilities\Desktop\CommonTestBase.cs(129,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify)
	f:\git\roslyn\src\Compilers\Test\Utilities\CSharp.Desktop\CSharpTestBase.cs(195,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 validator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify)
	Semantics\PatternMatchingTests.cs(553,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.PatternMatchingTests.GeneralizedSwitchStatement()

Test 'Microsoft.CodeAnalysis.CSharp.UnitTests.PatternMatchingTests.PatternInCatchFilter' failed: Microsoft.CodeAnalysis.Test.Utilities.ExecutionException : 
Execution failed for assembly ''.
Expected: No for 1
Yes for 10
No for 1.2
Actual:   No for 1
Yes for 10
No for 1,2


	HostedRuntimeEnvironment.cs(263,0): at Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.Execute(String moduleName, String expectedOutput)
	CommonTestBase.CompilationVerifier.cs(109,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.Emit(String expectedOutput, IEnumerable`1 manifestResources, Boolean peVerify, SignatureDescription[] expectedSignatures)
	f:\git\roslyn\src\Test\Utilities\Desktop\CommonTestBase.cs(204,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(Compilation compilation, IEnumerable`1 dependencies, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Action`1 assemblyValidator, Action`1 symbolValidator, Boolean verify)
	f:\git\roslyn\src\Test\Utilities\Desktop\CommonTestBase.cs(129,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify)
	f:\git\roslyn\src\Compilers\Test\Utilities\CSharp.Desktop\CSharpTestBase.cs(195,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 validator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify)
	Semantics\PatternMatchingTests.cs(292,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.PatternMatchingTests.PatternInCatchFilter()

Test 'Microsoft.CodeAnalysis.CSharp.UnitTests.PatternMatchingTests.PatternInExpressionBodiedMethod' failed: Microsoft.CodeAnalysis.Test.Utilities.ExecutionException : 
Execution failed for assembly ''.
Expected: False for 1
True for 10
False for 1.2
Actual:   False for 1
True for 10
False for 1,2


	HostedRuntimeEnvironment.cs(263,0): at Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.Execute(String moduleName, String expectedOutput)
	CommonTestBase.CompilationVerifier.cs(109,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.Emit(String expectedOutput, IEnumerable`1 manifestResources, Boolean peVerify, SignatureDescription[] expectedSignatures)
	f:\git\roslyn\src\Test\Utilities\Desktop\CommonTestBase.cs(204,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(Compilation compilation, IEnumerable`1 dependencies, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Action`1 assemblyValidator, Action`1 symbolValidator, Boolean verify)
	f:\git\roslyn\src\Test\Utilities\Desktop\CommonTestBase.cs(129,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify)
	f:\git\roslyn\src\Compilers\Test\Utilities\CSharp.Desktop\CSharpTestBase.cs(195,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 validator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify)
	Semantics\PatternMatchingTests.cs(357,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.PatternMatchingTests.PatternInExpressionBodiedMethod()
 
Test 'Microsoft.CodeAnalysis.CSharp.UnitTests.PatternMatchingTests.PatternInSwitchAndForeach' failed: Microsoft.CodeAnalysis.Test.Utilities.ExecutionException : 
Execution failed for assembly ''.
Expected: False for 1
True for 10
False for 1.2
Actual:   False for 1
True for 10
False for 1,2


	HostedRuntimeEnvironment.cs(263,0): at Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.Execute(String moduleName, String expectedOutput)
	CommonTestBase.CompilationVerifier.cs(109,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.Emit(String expectedOutput, IEnumerable`1 manifestResources, Boolean peVerify, SignatureDescription[] expectedSignatures)
	f:\git\roslyn\src\Test\Utilities\Desktop\CommonTestBase.cs(204,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(Compilation compilation, IEnumerable`1 dependencies, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Action`1 assemblyValidator, Action`1 symbolValidator, Boolean verify)
	f:\git\roslyn\src\Test\Utilities\Desktop\CommonTestBase.cs(129,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify)
	f:\git\roslyn\src\Compilers\Test\Utilities\CSharp.Desktop\CSharpTestBase.cs(195,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 validator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean verify)
	Semantics\PatternMatchingTests.cs(496,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.PatternMatchingTests.PatternInSwitchAndForeach()

85 passed, 8 failed, 1 skipped (see 'Error List / Messages'), took 8,66 seconds (xUnit.net 2.1.0 build 3179).
```

### PR DESCRIPTION
**Pull request by bnordli**
…nt decimal separator than '.'. Fixes #12094 

Output of tests in Norwegian locale after this change:
```
------ Test started: Assembly: Roslyn.Compilers.CSharp.Semantic.UnitTests.dll ------
 
93 passed, 0 failed, 1 skipped (see 'Error List / Messages'), took 8,43 seconds (xUnit.net 2.1.0 build 3179).
```

### CODE REVIEW

File: src/Test/Utilities/Shared/FX/EnsureEnglishCulture.cs [hunk 1]
```diff
@@ -0,0 +1,63 @@
+﻿// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
```
Comment (bnordli) [inline src/Test/Utilities/Shared/FX/EnsureEnglishCulture.cs]: This file is just an adapted copy of EnsureEnglishUICulture.cs

**Comment by Pilchie** [comment]
@dotnet-bot retest perf_correctness_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/perf_correctness_prtest/66/
// Retest reason: `error VSSDK1031: Extension '49e24138-9ee3-49e0-8ede-6b39f49303bf' could not be found. Please make sure the extension has been installed`

**Comment by Pilchie** [comment]
Thanks for the contribution!

Tagging @roslyn-ide for review.

File: src/Test/Utilities/Shared/FX/EnsureEnglishCulture.cs (hunk 1 above)
Comment (gafter) [inline src/Test/Utilities/Shared/FX/EnsureEnglishCulture.cs]: Which comes from where? Is it already part of Roslyn?

Comment (gafter) [inline src/Test/Utilities/Shared/FX/EnsureEnglishCulture.cs]: Oh, I see. It is in the same directory.

**Comment by gafter** [comment]
@dotnet/roslyn-compiler Can I have another (other than me) person review this, please?

**Comment by gafter** [comment]
LGTM. @agocke how does this look to you?

**Comment by jaredpar** [comment]
:+1:

**Comment by gafter** [comment]
@bnordli thank you so much for this contribution!

**Comment by bnordli** [comment]
Thanks to you, too, for accepting it!
