### PR TITLE
Fix wrong reporting for removing parenthesis for stackalloc

### LINKED ISSUE #44629: Visual studio suggests removing redundant parenthesis for spans that aren't redundant.
**Version Used**: VS 2019 preview 16.7

**Steps to Reproduce**:
Add the following method to a class.
```cs
private static void BadSuggestion()
{
    var span = (stackalloc byte[8]);
    for(int i = 0; i < span.Length; i++)
    {
         span[i] = (byte)0xFF;
    }
}
```
Visual studio recommends removing the redundant parenthesis in the line `var span = (stackalloc byte[8]);`. However doing so leads to the following errors

> error CS0214: Pointers and fixed size buffers may only be used in an unsafe context
> error CS1061: 'byte*' does not contain a definition for 'Length' and no accessible extension method 'Length' accepting a first argument of type 'byte*' could be found (are you missing a using directive or an assembly reference?)
> error CS0214: Pointers and fixed size buffers may only be used in an unsafe context

**Expected Behavior**:
VS would not suggest to remove the parenthesis.

As an aside, perhaps the issue is that 
```cs
static unsafe void Foo()
{
     var thisIsABytePointer = stackalloc byte[8];
     var thisIsASpanOfBytes = (stackalloc byte[8]);
}
```

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #44629

@CyrusNajmabadi, Opening `Compilers.sln` in Visual Studio makes my laptop hangs and unusable (perhaps because low specs and the solution is very big). So, I really cannot confirm if this fixes it.
I'll add relevant unit tests soon.

### CODE REVIEW

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs [hunk 1]
```diff
@@ -26,6 +26,12 @@ public static bool CanRemoveParentheses(this ParenthesizedExpressionSyntax node,
             }
 
             var expression = node.Expression;
+            if (expression is StackAllocArrayCreationExpressionSyntax)
+            {
+                // var span = (stackalloc byte[8]);
+                // https://github.com/dotnet/roslyn/issues/44629
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs:32]: it woudl be a worth a dedicated comment for this.  also, this check should likely go lower.  i.e. if we have `((stackalloc byte[8]))` we'd want to remove the outer parens.

Comment (Youssef1313) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs:32]: @CyrusNajmabadi, 
> it woudl be a worth a dedicated comment for this.
Do you mean a comment linking the PR?

> i.e. if we have ((stackalloc byte[8])) we'd want to remove the outer parens.
Right, I'll move it down.

Comment (Youssef1313) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs:32]: The current build fails without enough information available to me.

```
Compilers.sln:
/Users/runner/runners/2.169.1/work/1/s/.dotnet/sdk/3.1.200/MSBuild.dll /nologo -maxcpucount /m -verbosity:m /v:minimal /bl:/Users/runner/runners/2.169.1/work/1/s/artifacts/log/Debug/ToolsetRestore.binlog /clp:Summary /clp:ErrorsOnly;NoSummary /nr:false /p:TreatWarningsAsErrors=false /p:ContinuousIntegrationBuild=true /p:__ToolsetLocationOutputFile=/Users/runner/runners/2.169.1/work/1/s/artifacts/toolset/1.0.0-beta.20278.5.txt /t:__WriteToolsetLocation /Users/runner/runners/2.169.1/work/1/s/artifacts/toolset/restore.proj
/Users/runner/runners/2.169.1/work/1/s/artifacts/toolset/restore.proj : error : System.AggregateException: One or more errors occurred. (Could not find a part of the path '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/NuGetScratch/0709bfa4352c4b61a70bc6fb18e24971/a9376905db214e218fcd506fe4571a66.proj.nuget.dgspec.json'.)
/Users/runner/runners/2.169.1/work/1/s/artifacts/toolset/restore.proj : error :  ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/NuGetScratch/0709bfa4352c4b61a70bc6fb18e24971/a9376905db214e218fcd506fe4571a66.proj.nuget.dgspec.json'.
/Users/runner/runners/2.169.1/work/1/s/artifacts/toolset/restore.proj : error :    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
/Users/runner/runners/2.169.1/work/1/s/artifacts/toolset/restore.proj : error :    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
/Users/runner/runners/2.169.1/work/1/s/artifacts/toolset/restore.proj : error :    at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
/Users/runner/runners/2.169.1/work/1/s/artifacts/toolset/restore.proj : error :    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
/Users/runner/runners/2.169.1/work/1/s/artifacts/toolset/restore.proj : error :    at System.IO.FileStream..ctor(String path, FileMode mode)
/Users/runner/runners/2.169.1/work/1/s/artifacts/toolset/restore.proj : error :    at NuGet.ProjectModel.DependencyGraphSpec.Save(String path)
/Users/runner/runners/2.169.1/work/1/s/artifacts/toolset/restore.proj : error :    at NuGet.Commands.NoOpRestoreUtilities.PersistDGSpecFile(DependencyGraphSpec spec, String dgPath, ILogger log)
/Users/runner/runners/2.169.1/work/1/s/artifacts/toolset/restore.proj : error :    at NuGet.Commands.RestoreCommand.EvaluateCacheFile()
/Users/runner/runners/2.169.1/work/1/s/artifacts/toolset/restore.proj : error :    at NuGet.Commands.RestoreCommand.ExecuteAsync(CancellationToken token)
/Users/runner/runners/2.169.1/work/1/s/artifacts/toolset/restore.proj : error :    at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
/Users/runner/runners/2.169.1/work/1/s/artifacts/toolset/restore.proj : error :    at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List`1 restoreTasks)
/Users/runner/runners/2.169.1/work/1/s/artifacts/toolset/restore.proj : error :    at NuGet.Commands.RestoreRunner.RunWithoutCommit(IEnumerable`1 restoreRequests, RestoreArgs restoreContext)
/Users/runner/runners/2.169.1/work/1/s/artifacts/toolset/restore.proj : error :    --- End of inner exception stack trace ---
/Users/runner/runners/2.169.1/work/1/s/artifacts/toolset/restore.proj : error :    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
/Users/runner/runners/2.169.1/work/1/s/artifacts/toolset/restore.proj : error :    at System.Threading.Tasks.Task`1.get_Result()
/Users/runner/runners/2.169.1/work/1/s/artifacts/toolset/restore.proj : error :    at Microsoft.Build.NuGetSdkResolver.NuGetSdkResolver.NuGetAbstraction.GetSdkResult(SdkReference sdk, Object nuGetVersion, SdkResolverContext context, SdkResultFactory factory)
/Users/runner/runners/2.169.1/work/1/s/artifacts/toolset/restore.proj : error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found.
##[error]Build failed (exit code '1').
Killing running build processes...
```

Is that related to my changes or something else?

Comment (CyrusNajmabadi) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs]: ignore that.  ci machine issue.

**Comment by CyrusNajmabadi** [comment]
> Do you mean a comment linking the PR?

no.  i mean a comment explaining why we don't want to remove parens here.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs [hunk 2]
```diff
@@ -57,6 +57,16 @@ public static bool CanRemoveParentheses(this ParenthesizedExpressionSyntax node,
                 return true;
             }
 
+            if (expression is StackAllocArrayCreationExpressionSyntax)
```
Comment (alrz) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs:60]: Also check for ImplicitStackAllocArrayCreation. they both have the same behviour here.

Comment (Youssef1313) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs:60]: Thanks for review, I'll update that.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi There are test failures now after I moved the test down, can you check where is the problem? things are a bit hard for me to figure, especially that I can't open the sln in Visual Studio.

**Comment by CyrusNajmabadi** [comment]
Yup, this test is failing:

> Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.RemoveUnnecessaryParentheses.RemoveUnnecessaryExpressionParenthesesTests.TestStackAlloc [FAIL]

i can try to debug through later to see why.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs [hunk 3]
```diff
@@ -51,12 +51,22 @@ public static bool CanRemoveParentheses(this ParenthesizedExpressionSyntax node,
 
             // Simplest cases:
             //   ((x)) -> (x)
-            if (expression.IsKind(SyntaxKind.ParenthesizedExpression) ||
+            if (expression.IsKind(SyntaxKind.ParenthesizedExpression) &&
```
Comment (Youssef1313) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs:54]: Not very sure, but I think the check should be && because the comment above indicates that this searches double parentheses. Is that correct or wrong?

Comment (CyrusNajmabadi) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/ParenthesizedExpressionSyntaxExtensions.cs:54]: i believe the || is intentional.  i.e if you call on the outer, or you call on the inner, you will be told that the parens are unnecessary.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi, The unit test was just missing the `$$` that indicates the cursor position. The CI build hasn't finished yet, but expected to complete successfully. So, this is ready for review now.

**Comment by CyrusNajmabadi** [comment]
Great, thanks!
