### PR TITLE
Fixed incorrect suggestion for collection initialization simplification

### LINKED ISSUE #23672: invalid IDE0028 (explicit interface implementation)
**Version Used**: 

VS 15.5.0

**Steps to Reproduce**:

1. 

```cs
using System.Collections.Generic;
using System.Dynamic;

class Program
{
    static void Main()
    {
        // ExpandoObject doesn't have public Add method. Its Add is explicit implementation of IDictionary.
        IDictionary<string, object> obj = new ExpandoObject();
        obj.Add("string", "v");
        obj.Add("int", 1);
        obj.Add("object", new { X=1, Y=2 });
    }
}
```

2. IDE0028 Quick Action

```cs
IDictionary<string, object> obj = new ExpandoObject
{
    // Error CS1061 'ExpandoObject' does not contain a definition for 'Add'
    { "string", "v" },
    { "int", 1 },
    { "object", new { X = 1, Y = 2 } }
};
```

**Expected Behavior**:

No IDE0028 suggestion.

**Actual Behavior**:

image

### PR DESCRIPTION
**Pull request by zaytsev-victor**
Fixes #23672 
<details><summary>Ask Mode template not completed</summary>

### Customer scenario

What does the customer do to get into this situation, and why do we think this
is common enough to address for this release.  (Granted, sometimes this will be
obvious "Open project, VS crashes" but in general, I need to understand how
common a scenario is)

### Bugs this fixes

(either VSO or GitHub links)

### Workarounds, if any

Also, why we think they are insufficient for RC vs. RC2, RC3, or RTW

### Risk

This is generally a measure our how central the affected code is to adjacent
scenarios and thus how likely your fix is to destabilize a broader area of code

### Performance impact

(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")

### Root cause analysis

How did we miss it?  What tests are we adding to guard against it in the future?

### How was the bug found?

(E.g. customer reported it vs. ad hoc testing)

### Test documentation updated?

If this is a new non-compiler feature or a significant improvement to an existing feature, update https://github.com/dotnet/roslyn/wiki/Manual-Testing once you know which release it is targeting.

</details>

### CODE REVIEW

File: src/Features/Core/Portable/UseCollectionInitializer/ObjectCreationExpressionAnalyzer.cs [hunk 1]
```diff
@@ -200,13 +200,30 @@ protected override void AddMatches(ArrayBuilder<TExpressionStatementSyntax> matc
             _syntaxFacts.GetPartsOfMemberAccessExpression(memberAccess, out var localInstance, out var memberName);
             _syntaxFacts.GetNameAndArityOfSimpleName(memberName, out var name, out var arity);
 
-            if (arity != 0 || !name.Equals(nameof(IList.Add)))
+            if (arity != 0 || !name.Equals(nameof(IList.Add)) || IsExplicitlyImplemented(memberName))
```
Comment (sharwell) [inline src/Features/Core/Portable/UseCollectionInitializer/ObjectCreationExpressionAnalyzer.cs]: ❓ Will this run for cases where the local variable has the same type as the constructed object, e.g. when using `var`? If so, can we special case the behavior for this to avoid expensive calls to `GetSymbolInfo`?

Comment (zaytsev-victor) [reply src/Features/Core/Portable/UseCollectionInitializer/ObjectCreationExpressionAnalyzer.cs]: Good point, I'll check it.

Comment (zaytsev-victor) [reply src/Features/Core/Portable/UseCollectionInitializer/ObjectCreationExpressionAnalyzer.cs]: @sharwell Should we provide suggestion in this case:

```csharp
var obj = new ExpandoObject();
obj.Add("string", "v");
obj.Add("int", 1);
obj.Add("object", new { X=1, Y=2 });
```

This code won't compile but we have suggestion to use collection initialization

Comment (sharwell) [reply src/Features/Core/Portable/UseCollectionInitializer/ObjectCreationExpressionAnalyzer.cs]: I'm OK with either way in that scenario, so whatever's more efficient.

File: src/Features/Core/Portable/UseCollectionInitializer/ObjectCreationExpressionAnalyzer.cs [hunk 2]
```diff
@@ -120,6 +118,11 @@ protected override void AddMatches(ArrayBuilder<TExpressionStatementSyntax> matc
             }
         }
 
+        protected override bool ShouldAnalize()
+            => _semanticModel.GetTypeInfo(_objectCreationExpression, default).Type
+                    .GetMembers(WellKnownMemberNames.CollectionInitializerAddMethodName)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/UseCollectionInitializer/ObjectCreationExpressionAnalyzer.cs]: 1. ```.Type``` may return null, so this would crash on GetMembers.
2. Do not pass default for the cancellation token.  We should have an actual cancellation token that can be passsed.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/UseCollectionInitializer/ObjectCreationExpressionAnalyzer.cs]: 3. This won't pick up inherited .Add methods, or extension .Add methods.

File: src/Features/Core/Portable/UseCollectionInitializer/AbstractObjectCreationExpressionAnalyzer.cs [hunk 3]
```diff
@@ -66,6 +66,11 @@ protected void Clear()
                 return null;
             }
 
+            if (!ShouldAnalize())
```
Comment (jcouv) [inline src/Features/Core/Portable/UseCollectionInitializer/AbstractObjectCreationExpressionAnalyzer.cs]: Typo: ShouldAnalyze

**Comment by jinujoseph** [comment]
test windows_debug_spanish_unit32_prtest

File: src/Features/Core/Portable/UseCollectionInitializer/ObjectCreationExpressionAnalyzer.cs [hunk 4]
```diff
@@ -118,10 +118,22 @@ protected override void AddMatches(ArrayBuilder<TExpressionStatementSyntax> matc
             }
         }
 
-        protected override bool ShouldAnalize()
-            => _semanticModel.GetTypeInfo(_objectCreationExpression, default).Type
-                    .GetMembers(WellKnownMemberNames.CollectionInitializerAddMethodName)
-                    .Any(x => x is IMethodSymbol m && m.DeclaredAccessibility == Accessibility.Public);
+        protected override bool ShouldAnalyze()
+        {
+            var type = _semanticModel.GetTypeInfo(_objectCreationExpression, _cancellationToken).Type;
```
Comment (sharwell) [inline src/Features/Core/Portable/UseCollectionInitializer/ObjectCreationExpressionAnalyzer.cs]: :memo: This should not cause a performance problem because this expression was already being used on this this code path:

https://github.com/dotnet/roslyn/blob/84e1af7365956a04027014ce48c228f874a93d3c/src/Features/Core/Portable/UseCollectionInitializer/AbstractUseCollectionInitializerDiagnosticAnalyzer.cs#L88-L89

**Comment by sharwell** [comment]
@jinujoseph for approval to merge

**Comment by jinujoseph** [comment]
Approved to merge for 15.8.Preview2
