### PR TITLE
Bail on null type information in GenerateDeconstructMethodCodeFixProvider

### LINKED ISSUE #32510: Null Reference in GenerateDeconstructMethodCodeFixProvider
VS 28515.53

Stack:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at async Microsoft.CodeAnalysis.CSharp.CodeFixes.GenerateDeconstructMethod.GenerateDeconstructMethodCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

I've been update to create a small repro here, as my initial tests in a simple consoleapp haven't shown the same issue. The code I typed was this:
```C#
                var topLevelNullabilityMap = PooledDictionary<BoundExpression, TypeSymbolWithAnnotations>.GetInstance();
                foreach ((key, value) in topLevelNullabilityMap) // Yes, invalid variable declarator syntax.
                {

                }
```

I've put a dump here: "\\mlangfs1\public\frsilb\dumps\32510\devenv.dmp"
Probably related to https://github.com/dotnet/roslyn/issues/29718, or at least a similar underlying issue, as I hit both these at the same time.

### PR DESCRIPTION
**Pull request by ryzngard**
It's possible that a valid foreach statement has an invalid variable declaration syntax, which can result in no type information on calling `GetForEachStatementInfo`

Fixes #32510

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/Diagnostics/GenerateMethod/GenerateDeconstructMethodTests.cs [hunk 1]
```diff
@@ -294,6 +294,25 @@ internal void Deconstruct(out int x, out int y)
     {
         throw new NotImplementedException();
     }
+}");
+        }
+
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsGenerateMethod)]
```
Comment (genlu) [inline src/EditorFeatures/CSharpTest/Diagnostics/GenerateMethod/GenerateDeconstructMethodTests.cs]: nit: Missing `WorkItemAttribute`.

File: src/Features/CSharp/Portable/CodeFixes/GenerateMethod/GenerateDeconstructMethodCodeFixProvider.cs [hunk 2]
```diff
@@ -68,7 +68,7 @@ public sealed override async Task RegisterCodeFixesAsync(CodeFixContext context)
                     throw ExceptionUtilities.Unreachable;
             }
 
-            if (type.Kind != SymbolKind.NamedType)
+            if (type == null || type.Kind != SymbolKind.NamedType)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeFixes/GenerateMethod/GenerateDeconstructMethodCodeFixProvider.cs]: could just be `type?.Kind != SymbolKind.NamedType`.

**Comment by ryzngard** [comment]
@jinujoseph @vatsalyaagrawal ready for M2 approval targeting P4
