### PR TITLE
Fix DateAndTimePatternDetector for ?. expressions

### LINKED ISSUE #47553: IntelliSense completion in DateTime doesn;t work for nullable DateTime.
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1174811/intellisense-completion-in-datetime-doesnt-work-fo.html)._

---
[severity:I'm somewhat annoyed. A fix would be nice]
In [Visual Studio 2019 version 16.7.0](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#--visual-studio-2019-version-1670) there was added IntelliSense completion for DateTime.
It doesn't work when the DateTime is nullable and I use "?." operator. For example for

obj. StartDate.Value.ToString("d") // I get IntelliSence with format suggestions

obj. StartDate?. ToString("d") //I don't get this nice intellisense like above

---
#### Feedback Bot on 9/7/2020, 04:07 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #47553

### CODE REVIEW

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests_DateAndTime.vb [hunk 1]
```diff
@@ -204,6 +204,36 @@ class c
...
+        Public Async Function TestNullableDateTimeCompletion(showCompletionInArgumentLists As Boolean) As Task
+            Using state = TestStateFactory.CreateCSharpTestState(
+<Document><![CDATA[
+using System;
+class c
+{
+    void goo(DateTime? d)
+    {
+        d?.ToString("hh:mm:$$");
+    }
```
Comment (Youssef1313) [inline src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests_DateAndTime.vb:217]: This test is an exact copy/paste of the above test except changing DateTime to be nullable.

Comment (Youssef1313) [reply src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests_DateAndTime.vb:217]: #47873 is opened to make sure the test fails without the fix.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs [hunk 2]
```diff
@@ -572,6 +572,9 @@ public bool LooksGeneric(SyntaxNode simpleName)
         public SyntaxNode GetTargetOfMemberBinding(SyntaxNode node)
             => (node as MemberBindingExpressionSyntax).GetParentConditionalAccessExpression()?.Expression;
 
+        public SyntaxNode GetNameOfMemberBindingExpression(SyntaxNode node)
+            => (node as MemberBindingExpressionSyntax).Name;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs:576]:
```suggestion
        public SyntaxNode GetNameOfMemberBindingExpression(SyntaxNode node)
            => ((MemberBindingExpressionSyntax)node).Name;
```

no point doing an `as` only to immediately dot off of it.  if it's the wrong type it will crash, just with a less helpful exception.

Comment (Youssef1313) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs:576]: This is the pattern used in most of SyntaxFacts methods.

Comment (Youssef1313) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs:576]: I'll apply your suggestion, but if you want to fix this everywhere in SyntaxFacts, we may open an issue and fix that in a separate PR.

Comment (CyrusNajmabadi) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs]: Broken windows sound not be copied :-)

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Is this ready to merge?

**Review by CyrusNajmabadi — APPROVED** [review]
lgtm.  thanks!
