### PR TITLE
Bail in GetDependenceChain if typesymbol isn't found

### LINKED ISSUE #10211: "Index was outside the bounds of the array" during VB emit
This crashed during random dogfooding:
```
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberContainerTypeSymbol.DetectTypeCircularity_ShouldStepIntoType(NamedTypeSymbol typeToTest)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceChain(HashSet`1 visited, SourceNamedTypeSymbol root, TypeSymbol current)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceChain(HashSet`1 visited, SourceNamedTypeSymbol root, TypeSymbol current)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.BaseTypeAnalysis.GetDependenceDiagnosticForBase(SourceNamedTypeSymbol this, TypeSymbol base)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.MakeAcyclicBaseType(DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbol.get_BaseTypeNoUseSiteDiagnostics()
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.GetDirectBaseTypeNoUseSiteDiagnostics(ConsList`1 basesBeingResolved)
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.TypeSymbol.GetDirectBaseTypeWithDefinitionUseSiteDiagnostics(ConsList`1 basesBeingResolved, HashSet`1& useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.MemberLookup.LookupInClass(LookupResult result, TypeSymbol container, String name, Int32 arity, LookupOptions options, TypeSymbol accessThroughType, Binder binder, HashSet`1& useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.MemberLookup.Lookup(LookupResult lookupResult, TypeSymbol type, String name, Int32 arity, LookupOptions options, Binder binder, HashSet`1& useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.Binder.LookupMember(LookupResult lookupResult, TypeSymbol container, String name, Int32 arity, LookupOptions options, HashSet`1& useSiteDiagnostics)
   at Microsoft.CodeAnalysis.VisualBasic.NamedTypeBinder.LookupInSingleBinder(LookupResult lookupResult, String name, Int32 arity, LookupOptions options, Binder originalBinder, HashSet`1& useSiteDiagnostics)
```

A dump is available internally at \\<internal-server>\public\jasonmal\Dumps\Roslyn\10211

### PR DESCRIPTION
**Pull request by TyOverby**
closes #10211

Very simple change, please review @dotnet/roslyn-compiler.

Also I'd like advice on how to add unit tests that cover this.

### CODE REVIEW

File: src/Compilers/VisualBasic/Portable/Symbols/BaseTypeAnalysis.vb [hunk 1]
```diff
@@ -190,7 +190,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols
 
             Debug.Assert(root.OriginalDefinition = root, "root must not be a substitution")
 
-            If current Is Nothing Then
+            If current Is Nothing Or TypeOf current Is MissingMetadataTypeSymbol Then
```
Comment (agocke) [inline src/Compilers/VisualBasic/Portable/Symbols/BaseTypeAnalysis.vb]: It feels like we shouldn't be getting this far with a `MissingMetadataTypeSymbol`

Comment (jaredpar) [inline src/Compilers/VisualBasic/Portable/Symbols/BaseTypeAnalysis.vb]: @agocke would this be considered a declaration level error?  If so then I agree we should not get here.  If not then indeed the code can get this far.

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/BaseTypeAnalysis.vb]: Perhaps we should not single out MissingMetadataTypeSymbol, but cover all error type symbols (SymbolKind.ErrorType)

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/BaseTypeAnalysis.vb]: We should also see if it is possible to harden the code where the crash happens, where we assume to have at least one location. If that is covered, we might not need this change.

**Comment by AlekseyTs** [comment]
I agree, we should have a test for this scenario.

File: src/Compilers/VisualBasic/Portable/Symbols/BaseTypeAnalysis.vb (hunk 1 above)
Comment (TyOverby) [inline src/Compilers/VisualBasic/Portable/Symbols/BaseTypeAnalysis.vb]: @AlekseyTs The error location is [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Symbols/Source/SourceMemberContainerTypeSymbol.vb,2226).  When building in debug mode, I hit the first assert.

Comment (TyOverby) [inline src/Compilers/VisualBasic/Portable/Symbols/BaseTypeAnalysis.vb]: @AlekseyTs I like the idea of covering all error type symbols.  My most recent push has switched to using this.

**Comment by agocke** [comment]
@AlekseyTs What do you think about short circuiting `GetDependencyDiagnosticForBase` entirely when we have an error symbol in hand. Is there any useful cycle information we can give for error symbols?

**Comment by AlekseyTs** [comment]
@agocke To answer your question we need to understand the logic better.

**Comment by TyOverby** [comment]
@dotnet/roslyn-compiler I'd like to get this kicked back off again.  To start, does anyone know how I'd be able to reproduce this in a unit test?  We have a lot of helpers for setting up compilations with specific references, but how easy would it be to get one such that Object can't be found?

**Comment by AlekseyTs** [comment]
@TyOverby It is easy to get one without System.Object, don't give mscorlib reference. It might be tricky to set-up a compilation so that the code of interest would be reachable though. Perhaps we should start with understanding what references are given to compilation in the real word scenario and why we consider object missing. Then we can think what would be the best way to set-up similar situation for a unit-test.

**Comment by TyOverby** [comment]
@jaredpar Are you still able to repro this on your machine?  I'll try following your steps on mine, but I haven't had an issue in a long time.

**Comment by jaredpar** [comment]
I can't repro this anymore :(

**Comment by TyOverby** [comment]
I'm currently wading through the dump that Cyrus took and it looks like the compilation has *no* references.  I'm just looking at the References field on Compilation though.

```
-		References	{Microsoft.CodeAnalysis.Compilation.<get_References>d__84}	System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.MetadataReference> {Microsoft.CodeAnalysis.Compilation.<get_References>d__84}
		System.Collections.Generic.IEnumerator<Microsoft.CodeAnalysis.MetadataReference>.Current	null	Microsoft.CodeAnalysis.MetadataReference
		System.Collections.IEnumerator.Current	null	object
    -		Results View	Expanding the Results View will enumerate the IEnumerable	
    		Empty	"Enumeration yielded no results"	string

```

**Comment by AlekseyTs** [comment]
That (zero references) should be easy to recreate. Now, try to figure out what source is casing the compiler to take the code path.

**Comment by KirillOsenkov** [comment]
It was one of the .vb files in the Roslyn solution. I imagine one could write a tool that iterates over all .vb files in Roslyn, creates a compilation with each file and no references, and binds everything. Let it run for a few minutes and you'll get your repro :)

**Comment by KirillOsenkov** [comment]
Or, open all .vbproj projects from Roslyn, remove all references from each project and rebind everything (in case the problematic code spans multiple files)...

**Comment by TyOverby** [comment]
Repro:

```vb
Public Class B 
    Inherits A
End Class

Public Class A
End Class
```

Interesting, the lexical order of the classes influences the test.

**Comment by TyOverby** [comment]
When ordered in `class B inherits A, class A` we get the dependence chain pattern:

```
root B
current A

root B
current 
visiting: A

root B
current Object
visiting: A

root B
current 
visiting: A
visiting: Object
```

But the `class A, class B inherits A` pattern yields

```
root B
current A

root B
current 
visited: A
```

**Comment by jaredpar** [comment]
@TyOverby is current followed by no text mean `current` is `Nothing`?

File: src/Compilers/VisualBasic/Portable/Symbols/BaseTypeAnalysis.vb [hunk 2]
```diff
@@ -190,7 +190,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols
 
             Debug.Assert(root.OriginalDefinition = root, "root must not be a substitution")
 
-            If current Is Nothing Then
+            If current Is Nothing Then ' Or current.Kind = SymbolKind.ErrorType Then
```
Comment (gafter) [inline src/Compilers/VisualBasic/Portable/Symbols/BaseTypeAnalysis.vb]: The addition of this comment confuses me.

**Comment by TyOverby** [comment]
@jaredpar: Yep.  

@gafter: That content of that comment is my "fix" for the compiler crash.  We weren't sure that this is the correct fix, so I commented it out while investigating.

**Comment by TyOverby** [comment]
@jaredpar @AlekseyTs @agocke This PR is ready, re-review please!

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs [hunk 3]
```diff
@@ -2101,6 +2101,18 @@ void M(int x)
...
+        [Fact()]
+        [WorkItem(10211, "https://github.com/dotnet/roslyn/issues/10211")]
+        public void GetDependenceChainRegression_10211()
+        {
+            var compilation = CreateCompilation(@"
+class Child : Parent {}
+class Parent {}
+");
+            var semanticModel = compilation.GetSemanticModel(compilation.SyntaxTrees[0]);
+            semanticModel.GetMethodBodyDiagnostics();
```
Comment (agocke) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs]: Don't you want to assert the presence of some diagnostics here?

File: src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberContainerTypeSymbol.vb [hunk 4]
```diff
@@ -2230,8 +2230,12 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols
                 Return True
             End If
 
+            ' We can not get the relative order of a declaration without a source location
```
Comment (agocke) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberContainerTypeSymbol.vb]: I'm not sure I understand why the lack of declaration order means we should step into the type.

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberContainerTypeSymbol.vb]: By analogy with the previous 'If'

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs [hunk 5]
```diff
@@ -2101,6 +2101,18 @@ void M(int x)
...
         }
 
+        [Fact()]
+        [WorkItem(10211, "https://github.com/dotnet/roslyn/issues/10211")]
+        public void GetDependenceChainRegression_10211()
+        {
+            var compilation = CreateCompilation(@"
+class Child : Parent {}
+class Parent {}
+");
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs]: Consider adding a test with an opposite declaration order. Same for VB.

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs (hunk 3 above)
Comment (TyOverby) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs]: There are no diagnostics that should be reported.  `GetMethodBodyDiagnostics` simply shouldn't throw an exception.

I've added a comment: `// Ensure that we don't crash here.`

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs (hunk 5 above)
Comment (TyOverby) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs]: Done.

File: src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberContainerTypeSymbol.vb (hunk 4 above)
Comment (agocke) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberContainerTypeSymbol.vb]: Ah, I see

**Comment by AlekseyTs** [comment]
LGTM

File: src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberContainerTypeSymbol.vb [hunk 6]
```diff
@@ -2230,8 +2230,12 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols
...
+            If typeToTest.Locations.IsEmpty Then
+                Return True
```
Comment (jaredpar) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberContainerTypeSymbol.vb]: What type of symbol would make it to this statement?  A symbol from metadata?

**Comment by agocke** [comment]
:+1:

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs (hunk 3 above)
Comment (agocke) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs]: You could also assert no diagnostics -- I presume this case isn't covered in some other test because we would be throwing an exception, correct?

File: src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberContainerTypeSymbol.vb (hunk 6 above)
Comment (TyOverby) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberContainerTypeSymbol.vb]: @AlekseyTs?

The only other one that I can think of would be a error symbol, but I already covered that.

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberContainerTypeSymbol.vb]: The one without locations :-) I don't know if there are named type symbols like that today, besides the error type symbols. In any case, it is not worth crashing because of them, I think.

Comment (TyOverby) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberContainerTypeSymbol.vb]: Sounds good to me.
