### PR TITLE
Prevent infinite lookup cycle through bases of a containing type of an enum or a delegate type.

### LINKED ISSUE #70027: I've founded a C# code that crashes Visual Studio (and VS Code C# extension)
[AB#1883913](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1883913)

_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Ive-founded-a-C-code-that-crashes-Visu/10462968)._

---

```
using static MyNamespace.AnyClass.AnyEnum.Val;

namespace MyNamespace;

internal class AnyClass : AnyBaseClass
{
    internal enum AnyEnum
    {
        Val
    }
}
```

---
#### Feedback Bot on 9/11/2023, 07:59 PM: 

(private comment, text removed)
#### Feedback Bot on 9/19/2023, 10:33 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #70027.

### CODE REVIEW

**Review by 333fred — APPROVED** [review]

**Review by jjonescz — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Utilities/TypeSymbolExtensions.cs [hunk 1]
```diff
@@ -189,11 +189,18 @@ internal static TypeSymbol GetNextBaseTypeNoUseSiteDiagnostics(this TypeSymbol t
                 case TypeKind.Interface:
                     return GetNextDeclaredBase((NamedTypeSymbol)type, basesBeingResolved, compilation, ref visited);
 
-                default:
-                    // Enums and delegates know their own base types
+                case TypeKind.Dynamic:
+                case TypeKind.Enum:
+                case TypeKind.Delegate:
+                case TypeKind.Array:
+                case TypeKind.Submission:
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Utilities/TypeSymbolExtensions.cs:196]:
```suggestion
                case TypeKind.Submission:
                case TypeKind.Pointer:
                case TypeKind.FunctionPointer:
```
