### PR TITLE
Ensure only non-nullable valuetypes are wrapped in Nullable with a lifted conversion

### LINKED ISSUE #8190: Roslyn emits invalid Nullable, Nullable<string>.
Using the following test case:

```
using System;

namespace RoslynNullableStringRepro
{
    public class Program
    {
        public static void Main(string[] args)
        {
            NonNullableString? irony = "abc";
            irony += "def";

            Console.WriteLine(irony);
        }
    }

    struct NonNullableString
    {
        NonNullableString(string value)
        {
            if (value == null)
            {
                throw new ArgumentNullException(nameof(value));
            }

            this.value = value;
        }

        readonly string value;

        public override string ToString() => value;

        public static implicit operator string(NonNullableString self) => self.value;

        public static implicit operator NonNullableString(string value) => new NonNullableString(value);

        public static string operator +(NonNullableString lhs, NonNullableString rhs) => lhs.value + rhs.value;
    }
}
```

Expected results:
* Program writes "abcdef" to standard output
* Program exits with code 0.

Actual results:
* `TypeLoadException` at runtime: 
```
An unhandled exception of type 'System.TypeLoadException' occurred in mscorlib.dll

Additional information: GenericArguments[0], 'System.String', on 'System.Nullable`1[T]' violates the constraint of type parameter 'T'.
```

IL of `Program.Main`, as generated by Visual Studio 2015 (Roslyn 1.1):

```
.class public auto ansi beforefieldinit RoslynNullableStringRepro.Program
	extends [mscorlib]System.Object
{
	// Methods
	.method public hidebysig static 
		void Main (
			string[] args
		) cil managed 
	{
		// Method begins at RVA 0x2050
		// Code size 115 (0x73)
		.maxstack 3
		.entrypoint
		.locals init (
			[0] valuetype [mscorlib]System.Nullable`1<valuetype RoslynNullableStringRepro.NonNullableString>,
			[1] valuetype [mscorlib]System.Nullable`1<valuetype RoslynNullableStringRepro.NonNullableString>,
			[2] valuetype [mscorlib]System.Nullable`1<string>
		)

		IL_0000: nop
		IL_0001: ldloca.s 0
		IL_0003: ldstr "abc"
		IL_0008: call valuetype RoslynNullableStringRepro.NonNullableString RoslynNullableStringRepro.NonNullableString::op_Implicit(string)
		IL_000d: call instance void valuetype [mscorlib]System.Nullable`1<valuetype RoslynNullableStringRepro.NonNullableString>::.ctor(!0)
		IL_0012: ldloca.s 0
		IL_0014: ldloc.0
		IL_0015: stloc.1
		IL_0016: ldloca.s 1
		IL_0018: call instance bool valuetype [mscorlib]System.Nullable`1<valuetype RoslynNullableStringRepro.NonNullableString>::get_HasValue()
		IL_001d: brtrue.s IL_002a

		IL_001f: ldloca.s 2
		IL_0021: initobj valuetype [mscorlib]System.Nullable`1<string>
		IL_0027: ldloc.2
		IL_0028: br.s IL_0036

		IL_002a: ldloca.s 1
		IL_002c: call instance !0 valuetype [mscorlib]System.Nullable`1<valuetype RoslynNullableStringRepro.NonNullableString>::GetValueOrDefault()
		IL_0031: call string RoslynNullableStringRepro.NonNullableString::op_Implicit(valuetype RoslynNullableStringRepro.NonNullableString)

		IL_0036: stloc.2
		IL_0037: ldloca.s 2
		IL_0039: call instance !0 valuetype [mscorlib]System.Nullable`1<string>::get_Value()
		IL_003e: ldstr "def"
		IL_0043: call string [mscorlib]System.String::Concat(string, string)
		IL_0048: call valuetype RoslynNullableStringRepro.NonNullableString RoslynNullableStringRepro.NonNullableString::op_Implicit(string)
		IL_004d: call instance void valuetype [mscorlib]System.Nullable`1<valuetype RoslynNullableStringRepro.NonNullableString>::.ctor(!0)
		IL_0052: ldloc.0
		IL_0053: stloc.1
		IL_0054: ldloca.s 1
		IL_0056: call instance bool valuetype [mscorlib]System.Nullable`1<valuetype RoslynNullableStringRepro.NonNullableString>::get_HasValue()
		IL_005b: brtrue.s IL_0060

		IL_005d: ldnull
		IL_005e: br.s IL_006c

		IL_0060: ldloca.s 1
		IL_0062: call instance !0 valuetype [mscorlib]System.Nullable`1<valuetype RoslynNullableStringRepro.NonNullableString>::GetValueOrDefault()
		IL_0067: call string RoslynNullableStringRepro.NonNullableString::op_Implicit(valuetype RoslynNullableStringRepro.NonNullableString)

		IL_006c: call void [mscorlib]System.Console::WriteLine(string)
		IL_0071: nop
		IL_0072: ret
	} // end of method Program::Main

	.method public hidebysig specialname rtspecialname 
		instance void .ctor () cil managed 
	{
		// Method begins at RVA 0x20cf
		// Code size 8 (0x8)
		.maxstack 8

		IL_0000: ldarg.0
		IL_0001: call instance void [mscorlib]System.Object::.ctor()
		IL_0006: nop
		IL_0007: ret
	} // end of method Program::.ctor

} // end of class RoslynNullableStringRepro.Program
```

### PR DESCRIPTION
**Pull request by leppie**
Fixes #8190

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs [hunk 1]
```diff
@@ -556,13 +556,15 @@ private BoundExpression MakeImplicitConversion(BoundExpression rewrittenOperand,
 
                 TypeSymbol userDefinedConversionRewrittenType = conversion.Method.ReturnType;
 
-                if (rewrittenOperand.Type != conversion.Method.ParameterTypes[0])
+                // the conversion only needs to happen for non-nullable valuetypes
+                if (rewrittenOperand.Type != conversion.Method.ParameterTypes[0] && userDefinedConversionRewrittenType.IsValueType && !userDefinedConversionRewrittenType.IsNullableType())
```
Comment (leppie) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs]: Should I rather use `!CanBeAssignedNull()` for the last 2 conditions?

Comment (leppie) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs]: Looks good. Changed

**Comment by davkean** [comment]
tag @dotnet/roslyn-compiler 

@dotnet-bot test eta please

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs [hunk 2]
```diff
@@ -556,13 +556,14 @@ private BoundExpression MakeImplicitConversion(BoundExpression rewrittenOperand,
 
                 TypeSymbol userDefinedConversionRewrittenType = conversion.Method.ReturnType;
 
-                if (rewrittenOperand.Type != conversion.Method.ParameterTypes[0])
+                // the conversion only needs to happen for non-nullable valuetypes
+                if (rewrittenOperand.Type != conversion.Method.ParameterTypes[0] && !userDefinedConversionRewrittenType.CanBeAssignedNull())
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs]: It isn't clear to me that this type cannot be a type parameter. If it can, what is the right behavior for that case? This test doesn't seem apropos for that.

Comment (leppie) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs]: The lifting conversion here attempts to make the result nullable (either nullable valuetype or reference). `rewrittenOperand.Type` is always `Nullable<T>` here. But for surity, I will write test cases for the reverse case.

Comment (leppie) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs]: @gafter I updated the tests

**Comment by AlekseyTs** [comment]
What conversion are we dealing with here? is it a conversion from ```NonNullableString?``` to ```string``` ?

It looks like Language Specification doesn't define a lifted conversion like this:
```
6.4.2 Lifted conversion operators
Given a user-defined conversion operator that converts from a non-nullable value type S to a non-nullable value type T, a lifted conversion operator exists that converts from S? to T?. This lifted conversion operator performs an unwrapping from S? to S followed by the user-defined conversion from S to T followed by a wrapping from T to T?, except that a null valued S? converts directly to a null valued T?.
```

This behavior looks like a spec violation. Are we implementing it because old compiler did?

**Comment by leppie** [comment]
@AlekseyTs The check prevents this conversion from happening. All the tests work fine on the legacy compiler.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs [hunk 3]
```diff
@@ -556,13 +556,14 @@ private BoundExpression MakeImplicitConversion(BoundExpression rewrittenOperand,
...
                 {
                     Debug.Assert(rewrittenOperand.Type.IsNullableType());
                     Debug.Assert(rewrittenOperand.Type.GetNullableUnderlyingType() == conversion.Method.ParameterTypes[0]);
-                    Debug.Assert(!userDefinedConversionRewrittenType.IsNullableType());
 
                     // Lifted conversion, wrap return type in Nullable
+                    // BUG: Construct(...) should check the conversion is correct, as it is now, it will not check generic type parameter constraints
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs]: Rather than adding this comment, I think we should use more specific and precise condition for the ```if```. If I interpret the intent of this code correctly its purpose is to set ```userDefinedConversionRewrittenType``` to result type of a lifted conversion operator, if we are dealing with a lifted operator. So, let's use condition that checks for that explicitly.
```
rewrittenOperand.Type.IsNullableType() && 
conversion.Method.ParameterTypes[0] == rewrittenOperand.Type.GetNullableUnderlyingType() &&
!userDefinedConversionRewrittenType.IsNullableType() && 
userDefinedConversionRewrittenType.IsValueType
```

**Comment by AlekseyTs** [comment]
@leppie I don't see the check preventing conversion from ```NonNullableString?``` to ```string```. And my question is whether this is a spec violation. And if so, whether this violation is intentional.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs (hunk 3 above)
Comment (leppie) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs]: That sounds fair. Should the bug allowing `Construct` to create `Nullable<string>` also be logged?

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs]: No, Construct is not supposed to check constraints.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.cs]: When there is ```Nullable<string>``` in code, we should be able to construct the symbol so that constraints could be checked later.

**Comment by leppie** [comment]
test  prtest/win/tst/unit32  please

**Comment by davkean** [comment]
@leppie should mentioned for the future, you can ignore the runs with _tst_ in them. We're testing our dynamic pooling along side our static pool of machines, and they are still a little flaky.

File: src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs [hunk 4]
```diff
@@ -8745,6 +8745,101 @@ operator IntHolder(int i)
...
+{
+  public class Program
+  {
+    public static void Main(string[] args)
+    {
+      NonNullableString? irony = ""abc"";
+      irony += ""def"";
+      string ynori = ""abc"";
+      ynori += (NonNullableString?)""def"";
+
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs]: It feels like we are missing scenarios where ```NonNullableString?``` instances have null value.

File: src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs [hunk 5]
```diff
@@ -8745,6 +8745,101 @@ operator IntHolder(int i)
...
+namespace RoslynNullableIntRepro
+{
+  public class Program
+  {
+    public static void Main(string[] args)
+    {
+      NonNullableInt? irony = 1;
+      irony += 2;
+      int? ynori = 1;
+      ynori += (NonNullableInt?) 2;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs]: It feels like we are missing scenarios where ```NonNullableInt?``` instances have null value.

**Comment by AlekseyTs** [comment]
LGTM, modulo the missing test scenarios.

**Comment by leppie** [comment]
@AlekseyTs: Are the test scenarios sufficient now? If so, I will squash the commits. 

Any clarification about a possible spec violation, or is this just an 'underspecced' area?

**Comment by AlekseyTs** [comment]
The behavior looks like a spec violation to me, but I guess it is intentional in Roslyn since VS2013 compiler supports this scenario.

**Comment by AlekseyTs** [comment]
LGTM

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off.

**Comment by leppie** [comment]
@AlekseyTs @gafter: Should the violation maybe be controlled by checking for strict mode?

**Comment by AlekseyTs** [comment]
> Should the violation maybe be controlled by checking for strict mode?
There is no such requirement at the moment.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, we need a second sign-off on this change before we can merge it.

**Comment by VSadov** [comment]
LGTM
