### PR TITLE
Fix symbol resolution by applying groups at a time

### LINKED ISSUE #29935: EditorConfig: rules concerning var break code
**Version Used**: VS Community editon 15.8.4

**Steps to Reproduce**:

When using the following .editorconfig file

```
# top-most EditorConfig file
root = true

[*.cs]
# Implicit and explicit types
csharp_style_var_for_built_in_types = true:none
csharp_style_var_when_type_is_apparent = true:silent
csharp_style_var_elsewhere = true:none
```

to format the code:
```
using System;
using System.Collections.Generic;
using System.Text;

namespace OutVarSimplification
{
  public class Example<TKey, TValue, TToken> where TKey : IComparable<TKey>
  {
    public bool TryPeek(out TKey key, out TValue value)
    {
      throw new NotImplementedException("Implementation irrelevant");
    }

    public bool TryPeek(out KeyValuePair<TKey, TValue> result, out TToken token)
    {
      throw new NotImplementedException("Implementation irrelevant");
    }
 
    public KeyValuePair<TKey, TValue> Peek()
    {
      KeyValuePair<TKey, TValue> result;
      TToken token;
      TryPeek(out result, out token);
      return result; // details irrelevant
    }
  }
}
```

the resulting code is no longer compilable due to an ambiguity between the two TryPeek methods:

```
using System;
using System.Collections.Generic;
using System.Text;

namespace OutVarSimplification
{
  public class Example<TKey, TValue, TToken> where TKey : IComparable<TKey>
  {
    public bool TryPeek(out TKey key, out TValue value)
    {
      throw new NotImplementedException("Implementation irrelevant");
    }

    public bool TryPeek(out KeyValuePair<TKey, TValue> result, out TToken token)
    {
      throw new NotImplementedException("Implementation irrelevant");
    }

    public KeyValuePair<TKey, TValue> Peek()
    {
      TryPeek(out var result, out var token);
      return result; // details irrelevant
    }
  }
}
```

**Expected Behavior**:

Don't execute formatting rules that lead to code that no longer compiles.

**Actual Behavior**:

Code does no longer compile due to an ambiguity between two methods (TryPeek).

### PR DESCRIPTION
**Pull request by ryzngard**
When applying all for inline declaration fixes, checks for a new semantic target relied on only one variable in that target being changed. 

To fix, group by semantic targets and apply the speculative changes all at once. If the target changes, just leave explicit types instead of using var. Fixes #29935

### CODE REVIEW

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 1]
```diff
@@ -49,133 +49,151 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
+                // Recover the nodes we care about.
+                var declaratorLocation = diagnostic.AdditionalLocations[0];
+                var identifierLocation = diagnostic.AdditionalLocations[1];
+                var root = declaratorLocation.SourceTree.GetRoot(cancellationToken);
+
+                var declarator = (VariableDeclaratorSyntax)declaratorLocation.FindNode(cancellationToken);
+                var identifier = (IdentifierNameSyntax)identifierLocation.FindNode(cancellationToken);
+                
+                
+
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: one blank line.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 2]
```diff
@@ -307,7 +329,7 @@ private static IEnumerable<SyntaxTrivia> MassageTrivia(IEnumerable<SyntaxTrivia>
             return false;
         }
 
-        private SyntaxNode GetTopmostContainer(ExpressionSyntax expression)
+        private SyntaxNode GetTopmostContainer(CSharpSyntaxNode expression)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: please don't refernce CSharpSyntaxNode directly.  just use SyntaxNode.

**Comment by CyrusNajmabadi** [comment]
> When applying all for inline declaration fixes, checks for a new semantic target relied on only one variable in that target being changed.

> To fix, group by semantic targets and apply the speculative changes all at once. If the target changes, just leave explicit types instead of using var

Sorry, i can't really understand what this is trying to explain.

**Comment by CyrusNajmabadi** [comment]
Note: we have a helper here that i woudl have expect to see used.  Namely, either:

ApplyExpressionLevelSemanticEditsAsync or ApplyMethodBodySemanticEditsAsync.  These both work by fixing diagnostics in parallel across certain boundaries, but only fixing the diagnostics serially within a boundary.  So, for example, you could say: if i need to make multiple edits in a method, do them one at a time.  However, we can still process methods in parallel using the same original semantic model.

This is valuable as forking semantic models is expensive, and if we can avoid it (i.e. because there was only one change in a method) we don't want to do it for the other methods.

File: src/EditorFeatures/CSharpTest/InlineDeclaration/CSharpInlineDeclarationTests_FixAllTests.cs [hunk 3]
```diff
@@ -78,6 +79,7 @@ void M1()
         public async Task FixAllInDocument3()
         {
 
+
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/InlineDeclaration/CSharpInlineDeclarationTests_FixAllTests.cs]: remove both these blank lines.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 4]
```diff
@@ -49,133 +49,151 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
             // of the local.  This is necessary in some cases (for example, when the
             // type of the out-var-decl affects overload resolution or generic instantiation).
 
-            foreach (var diagnostic in diagnostics)
+            // Group by the ExpressionSyntax that the modified expression targets
+            var diagnosticGroups = diagnostics.GroupBy(d => d.AdditionalLocations[2]);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: the is a 'what' comment (i.e. it says what it is doing), but it's not a 'why' comment.  It doesn't tell me why this is appropriate or why it's better than not doing this.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 5]
```diff
@@ -49,133 +49,151 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
             {
                 // Switching to 'var' changed semantics.  Just use the original type of the local.
 
-                // If the user originally wrote it something other than 'var', then use what they
-                // wrote.  Otherwise, synthesize the actual type of the local.
-                var explicitType = declaration.Type.IsVar ? local.Type?.GenerateTypeSyntax() : declaration.Type;
-                declarationExpression = GetDeclarationExpression(
-                    sourceText, identifier, explicitType, singleDeclarator ? null : declarator);
-            }
+                foreach ((var local, var declaration, var identifier) in declarationsToAdd)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: why not: `foreach (var (localSymbol, declaration, identifier) in ...)`?

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 6]
```diff
@@ -253,15 +271,14 @@ private static IEnumerable<SyntaxTrivia> MassageTrivia(IEnumerable<SyntaxTrivia>
...
-            TypeSyntax newType,
-            IdentifierNameSyntax identifier,
-            DeclarationExpressionSyntax declarationExpression,
+            Document document, 
+            List<(ILocalSymbol, DeclarationExpressionSyntax, IdentifierNameSyntax)> declarationsToAdd, 
+            ExpressionSyntax invocationOrCreation, 
             CancellationToken cancellationToken)
         {
-            if (newType.IsVar)
+            var anyVar = declarationsToAdd.Any(t => t.Item2.Type.IsVar);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: needs explanation.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 7]
```diff
@@ -282,10 +299,15 @@ private static IEnumerable<SyntaxTrivia> MassageTrivia(IEnumerable<SyntaxTrivia>
...
                 var annotation = new SyntaxAnnotation();
-                var updatedTopmostContainer = topmostContainer.ReplaceNode(
-                    invocationOrCreation, invocationOrCreation.ReplaceNode(identifier, declarationExpression)
+
+                foreach ((var _, var declaration, var identifier) in declarationsToAdd)
+                {
+                    updatedTopmostContainer = updatedTopmostContainer.ReplaceNode(
+                        invocationOrCreation, invocationOrCreation.ReplaceNode(identifier, declaration)
                                                               .WithAdditionalAnnotations(annotation));
+                }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: something is super wonky with indentation here.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 8]
```diff
@@ -253,15 +271,14 @@ private static IEnumerable<SyntaxTrivia> MassageTrivia(IEnumerable<SyntaxTrivia>
...
-            Document document,
-            VariableDeclarationSyntax declaration,
-            ExpressionSyntax invocationOrCreation,
-            TypeSyntax newType,
-            IdentifierNameSyntax identifier,
-            DeclarationExpressionSyntax declarationExpression,
+            Document document, 
+            List<(ILocalSymbol, DeclarationExpressionSyntax, IdentifierNameSyntax)> declarationsToAdd, 
+            ExpressionSyntax invocationOrCreation, 
             CancellationToken cancellationToken)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: note: overall, i think much of this logic is pretty overwrought.  It seems to be trying to reimplement what we already have with ApplySemanticEditsAsync.  I'd prefer to use that helper as it's more tried and true.

Effectively, all you have to do is get the nodes marked by the original diagnostics.  You then say you want to ApplyMethodBodySemanticEdit.  Then that helper will do the grouping for you, where diagnostics in different methods can all apply independently.  But diagnostics within a method apply one at a time.  Then, all you need to do is validate each applied diagnostic to make sure it's not changing semantics if it uses 'var'.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: Let me know if you need more info.  I'm also available on gitter.im to discuss things more!

Comment (mavasani) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: It seems to me that `ApplyMethodBodySemanticEdit` is more expensive then the current approach. That method seems to be [forking a new semantic model](([http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Shared/Extensions/SyntaxEditorExtensions.cs,109](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Shared/Extensions/SyntaxEditorExtensions.cs,109))) after every edit within the method body, while current approach creates a very lightweight speculative semantic model off the original semantic model to validate semantic changes (unless I read the code incorrectly).

---
In reply to: [230210774](https://github.com/dotnet/roslyn/pull/30917#discussion_r230210774) [](ancestors = 230210774)

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: > That method seems to be forking a new semantic model after every edit within the method body

Yes.  it would be more expensive in the case of multiple edits in the same *statement* boundary (i.e. precisely this case).  But this is the outlier case. The majority of cases would be those that don't involve many edits within the same statement boundary.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: The SemanticEdit helper straddles a line of allowing code to be very simple (so that all the features that use it don't have to write complex logic for handling potential semantic collisions), while also being fast for the common case of no collisions.

Cost is only paid per collision (which in general is rare), with the benefit of having much simpler individual features that can share this sort of approach instead of having to individually do it themselves.  

Does that make sense?

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 9]
```diff
@@ -282,10 +299,15 @@ private static IEnumerable<SyntaxTrivia> MassageTrivia(IEnumerable<SyntaxTrivia>
...
                 }
 
+                var updatedTopmostContainer = topmostContainer;
                 var annotation = new SyntaxAnnotation();
-                var updatedTopmostContainer = topmostContainer.ReplaceNode(
-                    invocationOrCreation, invocationOrCreation.ReplaceNode(identifier, declarationExpression)
+
+                foreach ((var _, var declaration, var identifier) in declarationsToAdd)
+                {
+                    updatedTopmostContainer = updatedTopmostContainer.ReplaceNode(
```
Comment (mavasani) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: >ReplaceNode [](start = 70, length = 11)

You can use [ReplaceNodes](http://source.roslyn.io/#Microsoft.CodeAnalysis/Syntax/SyntaxNodeExtensions.cs,54) to replace multiple nodes.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs (hunk 8 above)
Comment (mavasani) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: Yes, that sounds reasonable. I am wondering if the helper can have an overload that supports the specific scenario that Andrew encountered here and avoid forking semantic model and provide him a speculative model for every statement edit. Regardless, I agree that taking a simplest approach is suitable here.

---
In reply to: [230226018](https://github.com/dotnet/roslyn/pull/30917#discussion_r230226018) [](ancestors = 230226018)

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: > the specific scenario that Andrew encountered here and avoid forking semantic model and provide him a speculative model for every statement edit. 

I think that would definitely be possible.  IIRC, there was some reason i couldn't use that before. Unfortunately i don't remember what that issue was now :( (sorry!).

We could start by just making it *always* give out a speculative model.  Then see what breaks.  If nothing breaks, then we'll just change to that.   If something breaks, then we make this a knob on the API.  So everyone who can use speculative models can use them for the perf boost.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: Ok.  IIRC, the issue with speculative models was specifically about when you were making a change that was introducing a new variable in scope (like a declaration-expression).  You would end up with a collision (because the original semantic model had a variable with that name) that your speculated code now interfered with.  And even if the variables had the same name+type, you'd often get error symbols, which would make it seem as if the edit was bad. 

It would be interesting to see if that is still an issue.  And, again, i'm totally supportive of this API using speculative models for perf if the caller knows that's safe for their scenario! :)

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: @ryzngard is there enough info here for you to go off of?

Comment (ryzngard) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: Yea, I'm working on something more elegant that I think can drive meaningful conversation. Hopefully get an update today based on some of this feedback

**Comment by ryzngard** [comment]
@CyrusNajmabadi @mavasani

File: src/EditorFeatures/CSharpTest/InlineDeclaration/CSharpInlineDeclarationTests_FixAllTests.cs (hunk 3 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/InlineDeclaration/CSharpInlineDeclarationTests_FixAllTests.cs]: this does not actually seem to have been resolved.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 10]
```diff
@@ -49,17 +50,26 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
-                    options, cancellationToken).ConfigureAwait(false);
+                originalNodes[i] = await GetDeclarationAsync(document, editor, diagnostics[i], options, cancellationToken).ConfigureAwait(false);
             }
+
+            await editor.ApplyExpressionLevelSemanticEditsAsync(
+                document,
+                originalNodes.AsImmutable(),
+                (_1, _2, _3) => true,
+                (semanticModel, currentRoot, t, currentNode) => ReplaceNode(semanticModel, currentRoot, t, currentNode),
+                (t) => t.Item3, // Use the InvocationOrCreation node to track
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: item3 is a pretty terrible name.  it also seems incorrect given that Item3 looks to be a DeclarationExpressionSyntax.  Name tuple properties are a good thing :)

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 11]
```diff
@@ -49,17 +50,26 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
-                    document, editor, diagnostic, 
-                    options, cancellationToken).ConfigureAwait(false);
+                originalNodes[i] = await GetDeclarationAsync(document, editor, diagnostics[i], options, cancellationToken).ConfigureAwait(false);
             }
+
+            await editor.ApplyExpressionLevelSemanticEditsAsync(
+                document,
+                originalNodes.AsImmutable(),
+                (_1, _2, _3) => true,
+                (semanticModel, currentRoot, t, currentNode) => ReplaceNode(semanticModel, currentRoot, t, currentNode),
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: 't' is very vague.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 12]
```diff
@@ -49,17 +50,26 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
-                cancellationToken.ThrowIfCancellationRequested();
-                await AddEditsAsync(
-                    document, editor, diagnostic, 
-                    options, cancellationToken).ConfigureAwait(false);
+                originalNodes[i] = await GetDeclarationAsync(document, editor, diagnostics[i], options, cancellationToken).ConfigureAwait(false);
             }
+
+            await editor.ApplyExpressionLevelSemanticEditsAsync(
+                document,
+                originalNodes.AsImmutable(),
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: instead of an array, and AsImmutable, use `ArrayBuilder.GetInstance(length)`, then do `ToImmutableAndFree` here.  It's idiomatic for the LS.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 13]
```diff
@@ -160,22 +170,30 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
             var declarationExpression = GetDeclarationExpression(
                 sourceText, identifier, newType, singleDeclarator ? null : declarator);
 
+            return (local, identifier, declarationExpression, invocationOrCreation);
+        }
+
+        private SyntaxNode ReplaceNode(SemanticModel semanticModel, SyntaxNode currentRoot, (ILocalSymbol, IdentifierNameSyntax, DeclarationExpressionSyntax, SyntaxNode) t, SyntaxNode currentNode)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: 't' is not a good name here :)

Also, instead of passing the whole tuple *consider* (i.e. up to you) just passing the data you need.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 14]
```diff
@@ -252,29 +270,26 @@ private static IEnumerable<SyntaxTrivia> MassageTrivia(IEnumerable<SyntaxTrivia>
...
-            TypeSyntax newType,
+        private bool SemanticsChanged(
+            SemanticModel semanticModel,
+            SyntaxNode root,
+            SyntaxNode nodeToReplace,
             IdentifierNameSyntax identifier,
-            DeclarationExpressionSyntax declarationExpression,
-            CancellationToken cancellationToken)
+            DeclarationExpressionSyntax declarationExpression
+            )
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: paren never goes here.  please place on previous line.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs (hunk 10 above)
Comment (ryzngard) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: Aye. I added another item and messed this up :) I'll switch to named tuple properties.

File: src/Workspaces/Core/Portable/Shared/Extensions/SyntaxEditorExtensions.cs [hunk 15]
```diff
@@ -13,6 +13,29 @@ namespace Microsoft.CodeAnalysis.Shared.Extensions
...
+        {
+            return ApplySemanticEditsAsync(
+                editor, document,
+                originalNodes,
+                (syntaxFacts, node) => GetExpressionSemanticBoundary(syntaxFacts, node),
+                canReplace,
+                updateRoot,
+                selector,
+                cancellationToken);
+        }
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Shared/Extensions/SyntaxEditorExtensions.cs]: i woudl expect the existing ApplyExpressionLevelSemanticEditsAsync to call into this more general helper, passing along `node => node` as the selector function.

File: src/Workspaces/Core/Portable/Shared/Extensions/SyntaxEditorExtensions.cs [hunk 16]
```diff
@@ -29,8 +52,32 @@ internal static class SyntaxEditorExtensions
                 editor, document,
                 originalNodes,
                 (syntaxFacts, node) => GetExpressionSemanticBoundary(syntaxFacts, node),
+                (semanticModel, _, node) => canReplace(semanticModel, (TNode)node),
+                (semanticModel, currentRoot, _, node) => updateRoot(semanticModel, currentRoot, (TNode)node),
+                (t) => t,
+                cancellationToken);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Shared/Extensions/SyntaxEditorExtensions.cs]: the direction here seems reversed.  i would expect this to call into the new, more general, ApplyExpressionLevelSemanticEditsAsync.  And that new function is the one that will call into ApplySemanticEditsAsync.

Basically, more specific functions keep calling the more general ones.  so it would go OldApplyExpressionLevelSemanticEditsAsync -> NewApplyExpressionLevelSemanticEditsAsync -> ApplySemanticEditsAsync

File: src/Workspaces/Core/Portable/Shared/Extensions/SyntaxEditorExtensions.cs [hunk 17]
```diff
@@ -50,8 +97,9 @@ internal static class SyntaxEditorExtensions
                 editor, document,
                 originalNodes,
                 (syntaxFacts, node) => GetMethodBodySemanticBoundary(syntaxFacts, node),
-                canReplace,
-                updateRoot,
+                (semanticModel, _, node) => canReplace(semanticModel, (TNode)node),
+                (semanticModel, currentRoot, _, node) => updateRoot(semanticModel, currentRoot, (TNode)node),
+                (t) => t,
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Shared/Extensions/SyntaxEditorExtensions.cs]: same comments apply.  also, nit: we don't parenthesize single-element lambdas.

File: src/Workspaces/Core/Portable/Shared/Extensions/SyntaxEditorExtensions.cs [hunk 18]
```diff
@@ -73,36 +121,40 @@ internal static class SyntaxEditorExtensions
...
             Func<ISyntaxFactsService, SyntaxNode, SyntaxNode> getSemanticBoundary,
-            Func<SemanticModel, TNode, bool> canReplace,
-            Func<SemanticModel, SyntaxNode, TNode, SyntaxNode> updateRoot,
-            CancellationToken cancellationToken) where TNode : SyntaxNode
+            Func<SemanticModel, TType, SyntaxNode, bool> canReplace,
+            Func<SemanticModel, SyntaxNode, TType, SyntaxNode, SyntaxNode> updateRoot,
+            Func<TType, SyntaxNode> selector,
+            CancellationToken cancellationToken)
         {
+            var originalNodePairs = originalNodes.Select(n => (n, selector(n)));
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Shared/Extensions/SyntaxEditorExtensions.cs]: can we name our tuple elements, seeing Item1 and Item2 is just confusing below.  Also, consider not using 'nodes' for things that are no longer SyntaxNodes.

File: src/Workspaces/Core/Portable/Shared/Extensions/SyntaxEditorExtensions.cs [hunk 19]
```diff
@@ -50,8 +97,9 @@ internal static class SyntaxEditorExtensions
                 editor, document,
                 originalNodes,
                 (syntaxFacts, node) => GetMethodBodySemanticBoundary(syntaxFacts, node),
-                canReplace,
-                updateRoot,
+                (semanticModel, _, node) => canReplace(semanticModel, (TNode)node),
+                (semanticModel, currentRoot, _, node) => updateRoot(semanticModel, currentRoot, (TNode)node),
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Shared/Extensions/SyntaxEditorExtensions.cs]: the casts here don't make sense to me.  They indicate that the TNode information from this function is being lost in the call to ApplySemanticEditsAsync.  ApplySemanticEditsAsync should be generic on both the 'input type' and the 'type being selected to'.

File: src/Workspaces/Core/Portable/Shared/Extensions/SyntaxEditorExtensions.cs (hunk 18 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Shared/Extensions/SyntaxEditorExtensions.cs]: This should be generic on two types.  We both want it to be strongly typed on a TInput type (i.e. your TType), and the TNode type that 'selector' function (and things like canReplace and updateRoot) operate with.  That will prevent unnecessary casts in the callers.

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Shared/Extensions/SyntaxEditorExtensions.cs]: i'm on the fence if you even need to do this.  just calling selector on-demand doesn't seem like a problem.  But it's up to you if you want to make sucha  change.  i'm ok with this as is.

File: src/Workspaces/Core/Portable/Shared/Extensions/SyntaxEditorExtensions.cs (hunk 16 above)
Comment (ryzngard) [reply src/Workspaces/Core/Portable/Shared/Extensions/SyntaxEditorExtensions.cs]: Like

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs (hunk 11 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: your selector is always returning Item3 right?  That shoudl always be a DeclarationExpression.  So wouldn't currentNode be typed as DeclarationExpression?  If so, it seems unfortunate to me that we've weakend the type to just be SyntaxNode in that declaration.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi @mavasani let me know what you think with the latest approach. I'm currently working on fixing the tests, as not all are passing, but I wanted feedback.

The approach is good overall :)   My concerns are mostly about making this more typesafe (which seems like it should be possible), and also getting hte abstraction direction going the right way.

File: src/Workspaces/Core/Portable/Shared/Extensions/SyntaxEditorExtensions.cs (hunk 19 above)
Comment (ryzngard) [reply src/Workspaces/Core/Portable/Shared/Extensions/SyntaxEditorExtensions.cs]: That's because they're wrong :) I mixed up the ordering, and the cast will never make sense. Fixed and removed the cast

File: src/Workspaces/Core/Portable/Shared/Extensions/SyntaxEditorExtensions.cs [hunk 20]
```diff
@@ -13,6 +13,29 @@ namespace Microsoft.CodeAnalysis.Shared.Extensions
...
+        /// Performs several edits to a document.  If multiple edits are made within the same
+        /// expression context, then the document/semantic-model will be forked after each edit 
+        /// so that further edits can see if they're still safe to apply.
+        /// </summary>
+        public static Task ApplyExpressionLevelSemanticEditsAsync<TType>(
+            this SyntaxEditor editor, Document document,
+            ImmutableArray<TType> originalNodes,
+            Func<SemanticModel, TType, SyntaxNode, bool> canReplace,
+            Func<SemanticModel, SyntaxNode, TType, SyntaxNode, SyntaxNode> updateRoot,
+            Func<TType, SyntaxNode> selector,
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Shared/Extensions/SyntaxEditorExtensions.cs]: IMO, hte selector should go right after the 'originalNodes' parameter.  It's effectively one of the most important parts about this.  It is *the* thing that associated with originalNodes and maps accordingly.  Also, if it follows right afterwards, it can likely be generic on a TNode type which will then work properly with type inference (i think).

Finally, consider the following (but you don't have to do this if you don't want to): If i have a list of things and mapping from those things to another value, then that's just another way of saying "i have a mapping".  i.e. this may be more accurately expressed as a `ImmutableDictionary<TType, TNode>`.  Then, the simple case of just having array of nodes, is just a mapping from node to itself.  

That may simplify things by removing the need for multiple arguments by consolidating this into a single clearer argument.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 21]
```diff
@@ -49,17 +50,26 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
+
+            var originalNodes = new (ILocalSymbol, IdentifierNameSyntax, DeclarationExpressionSyntax, SyntaxNode)[diagnostics.Length];
+
+            for (var i = 0; i < originalNodes.Length; i++)
             {
-                cancellationToken.ThrowIfCancellationRequested();
-                await AddEditsAsync(
-                    document, editor, diagnostic, 
-                    options, cancellationToken).ConfigureAwait(false);
+                originalNodes[i] = await GetDeclarationAsync(document, editor, diagnostics[i], options, cancellationToken).ConfigureAwait(false);
```
Comment (genlu) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: I was going to suggest using `Task.WhenAll` to avoid the long declaration of `originalNodes` then I realized `GetDeclarationAsync` has side-effects. Maybe just call it something like `AddInlineWithVarEditsAsync` to make it more clear what it actually does? Sorry, I'm terrible at naming things, but I'm sure you know I'm saying :)

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: SyntaxEditor likely should *not* be passed into GetDeclarationAsync.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs (hunk 13 above)
Comment (genlu) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: This is a very general name for a method :) Consider adding some doc comments or change the method to something like `ReplaceIdentifierWithInlineDeclaration`

Comment (ryzngard) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: Missed this comment, but still applicable to current code. Will update to new name

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 22]
```diff
@@ -48,36 +50,55 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
+            OptionSet options, SemanticModel semanticModel,
+            SyntaxNode currentRoot, VariableDeclaratorSyntax declarator,
+            IdentifierNameSyntax identifier, SyntaxNode invocationOrCreation,
+            SyntaxNode currentNode)
+        {
+            declarator = currentRoot.GetCurrentNode(declarator);
+            identifier = currentRoot.GetCurrentNode(identifier);
+
+            var editor = new SyntaxEditor(currentRoot, CSharpSyntaxGenerator.Instance);
+            var sourceText = currentRoot.GetText();
```
Comment (mavasani) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: >GetText [](start = 41, length = 7)

Can we thread in the `cancellationToken`?
