### PR TITLE
Disallow ref returning Main method

### LINKED ISSUE #17923: The entry point Main method should not be allowed to return int by-ref because it is not supported by CLR
**Version Used**: 

Microsoft Visual Studio Enterprise 2017
Version 15.0.26228.9 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01586

**Steps to Reproduce**:

Compile as a console application and run:
```
using System;

class C
{
    static ref int Main()
    {
        throw new Exception();
    }
}
```

**Expected Behavior**: A compile-time error: error CS5001: Program does not contain a static 'Main' method suitable for an entry point.

**Actual Behavior**: No compile-time errors. Unhandled exception at runtime: System.MethodAccessException: Entry point must have a return type of void, integer, or unsigned integer.

### PR DESCRIPTION
**Pull request by jaredpar**
The Main method cannot have a ref return.

closes #17923

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-compiler for review

File: src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs [hunk 1]
```diff
@@ -613,6 +613,11 @@ internal bool HasEntryPointSignature()
                 return false;
             }
 
+            if (RefKind != RefKind.None)
```
Comment (VSadov) [inline src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs]: nice. This will handle "ref readonly" as well.

File: src/Compilers/CSharp/Test/Emit/Emit/EntryPointTests.cs [hunk 2]
```diff
@@ -1444,5 +1444,45 @@ class Program
...
+                //     public static ref int Main() {}
+                Diagnostic(ErrorCode.WRN_InvalidMainSig, "Main").WithArguments("Program.Main()").WithLocation(4, 27),
+                // error CS5001: Program does not contain a static 'Main' method suitable for an entry point
+                Diagnostic(ErrorCode.ERR_NoEntryPoint).WithLocation(1, 1));
+        }
+
+        [WorkItem(17923, "https://github.com/dotnet/roslyn/issues/17923")]
+        [Fact]
+        [CompilerTrait(CompilerFeature.RefLocalsReturns)]
+        public void RefIntReturnMainWithParams()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/Emit/EntryPointTests.cs]: >RefIntReturnMainWithParams [](start = 20, length = 26)

Consider adding a test for success case when there is also a method with acceptable return type.
