### PR TITLE
Semantic snippets - Adds tooltip descriptions to snippets

### LINKED ISSUE #64925: Semantic snippets: new snippets don't have tooltips
**Version Used**:
Latest main

**Steps to Reproduce**:
Invoke completions on any position valid for any semantic snippet and observe its tooltip

(A [sharplab](https://sharplab.io/) repro is ideal for compiler/language issues whenever possible)

**Expected Behavior**:
New semantic snippets have some tooltips

**Actual Behavior**:
They don't have any

**Demo:**
- Old snippet:
devenv_kfeUnIq6Qk
- New snippet:
devenv_mMjjaKtzvW

### PR DESCRIPTION
**Pull request by akhera99**
Fixes #64925 
image

### CODE REVIEW

File: src/Features/Core/Portable/Completion/Providers/Snippets/AbstractSnippetCompletionProvider.cs [hunk 1]
```diff
@@ -91,17 +92,23 @@ public override async Task ProvideCompletionsAsync(CompletionContext context)
...
                 var completionItem = SnippetCompletionItem.Create(
-                    displayText: snippetData.SnippetIdentifier,
+                    displayText: snippetData.Shortcut,
                     displayTextSuffix: "",
                     position: position,
-                    snippetIdentifier: snippetData.SnippetIdentifier,
+                    snippetIdentifier: snippetData.Shortcut,
                     glyph: Glyph.Snippet,
-                    inlineDescription: snippetData.Description,
+                    description: (snippetData.Title + Environment.NewLine + snippetData.Description).ToSymbolDisplayParts(),
```
Comment (akhera99) [inline src/Features/Core/Portable/Completion/Providers/Snippets/AbstractSnippetCompletionProvider.cs:100]: do we want a different format?

File: src/Features/Core/Portable/Snippets/SnippetProviders/AbstractSnippetProvider.cs [hunk 2]
```diff
@@ -22,8 +22,9 @@ namespace Microsoft.CodeAnalysis.Snippets
 {
     internal abstract class AbstractSnippetProvider : ISnippetProvider
     {
-        public abstract string SnippetIdentifier { get; }
-        public abstract string SnippetDescription { get; }
+        public abstract string Shortcut { get; }
+        public abstract string Title { get; }
+        public string Description => string.Format(FeaturesResources.Code_snippet_for_0, Title);
```
Comment (akhera99) [inline src/Features/Core/Portable/Snippets/SnippetProviders/AbstractSnippetProvider.cs:27]: Do we want a different description?

File: src/Features/Core/Portable/Snippets/SnippetData.cs [hunk 3]
```diff
@@ -16,14 +16,16 @@ namespace Microsoft.CodeAnalysis.Snippets
     /// </summary>
     internal readonly struct SnippetData
     {
+        public readonly string Title;
+        public readonly string Shortcut;
```
Comment (genlu) [inline src/Features/Core/Portable/Snippets/SnippetData.cs:20]: Could you please add comments to explain how those strings are used?

File: src/Features/Core/Portable/Completion/Providers/Snippets/AbstractSnippetCompletionProvider.cs (hunk 1 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/Snippets/AbstractSnippetCompletionProvider.cs:100]: This seems fine to me

File: src/Features/Core/Portable/Snippets/SnippetProviders/AbstractSnippetProvider.cs (hunk 2 above)
Comment (genlu) [reply src/Features/Core/Portable/Snippets/SnippetProviders/AbstractSnippetProvider.cs:27]: This seems to be consistent with old snippet, should be fine

File: src/Features/Core/Portable/Snippets/SnippetProviders/ISnippetProvider.cs [hunk 4]
```diff
@@ -12,12 +12,17 @@ internal interface ISnippetProvider
...
-        /// What is being displayed for the description of the snippet
+        /// What is being displayed for the inline-description of the snippet as well as the title on the tool-tip.
         /// </summary>
-        string SnippetDescription { get; }
+        string Title { get; }
+
+        /// <summary>
+        /// What is being displayed for the description of the snippet on the tool-tip.
+        /// </summary>
+        string Description { get; }
```
Comment (genlu) [inline src/Features/Core/Portable/Snippets/SnippetProviders/ISnippetProvider.cs:25]: If this is always in the same format of "Code snippet for [Title]", then it can be constructed by the snippet completion provider.

File: src/Features/Core/Portable/Snippets/SnippetProviders/ISnippetProvider.cs [hunk 5]
```diff
@@ -12,12 +12,17 @@ internal interface ISnippetProvider
         /// <summary>
         /// What we use to identify each SnippetProvider on the completion list
         /// </summary>
-        string SnippetIdentifier { get; }
+        string Shortcut { get; }
```
Comment (genlu) [inline src/Features/Core/Portable/Snippets/SnippetProviders/ISnippetProvider.cs:15]: maybe DisplayText? Not sure what Shortcut means,

**Comment by genlu** [comment]
@akhera99 Let's add a test for snippet description

File: src/Features/Core/Portable/Snippets/SnippetProviders/ISnippetProvider.cs (hunk 5 above)
Comment (akhera99) [reply src/Features/Core/Portable/Snippets/SnippetProviders/ISnippetProvider.cs:15]: I was matching what the old snippets used to identify as. It's a shortcut bc it's the shorthand word that brings up the snippet. I can change to display text though

File: src/Features/CSharp/Portable/Snippets/CSharpClassSnippetProvider.cs [hunk 6]
```diff
@@ -24,9 +24,9 @@ internal class CSharpClassSnippetProvider : CSharpTypeSnippetProvider
         public CSharpClassSnippetProvider()
         {
         }
-        public override string SnippetIdentifier => "class";
+        public override string Shortcut => "class";
 
-        public override string SnippetDescription => FeaturesResources.class_;
```
Comment (DoctorKrolic) [inline src/Features/CSharp/Portable/Snippets/CSharpClassSnippetProvider.cs:29]: TBO I preffer `Description` over new `Title`. `Title` is something eye-catching, while this text is displayed on a side of a completion item, so I would probably call it a "small description" rather than a title. If you need to differentiate it from what is displayed outside the completion list, well, it is a _tooltip_

File: src/Features/Core/Portable/Completion/Providers/Snippets/AbstractSnippetCompletionProvider.cs [hunk 7]
```diff
@@ -91,17 +92,23 @@ public override async Task ProvideCompletionsAsync(CompletionContext context)
             foreach (var snippetData in snippets)
             {
                 var completionItem = SnippetCompletionItem.Create(
-                    displayText: snippetData.SnippetIdentifier,
+                    displayText: snippetData.Shortcut,
                     displayTextSuffix: "",
                     position: position,
-                    snippetIdentifier: snippetData.SnippetIdentifier,
+                    snippetIdentifier: snippetData.Shortcut,
```
Comment (genlu) [inline src/Features/Core/Portable/Completion/Providers/Snippets/AbstractSnippetCompletionProvider.cs:98]: `Identifier`?

File: src/Features/Core/Portable/Completion/Providers/Snippets/AbstractSnippetCompletionProvider.cs [hunk 8]
```diff
@@ -11,6 +11,7 @@
 using Microsoft.CodeAnalysis.ConvertToInterpolatedString;
 using Microsoft.CodeAnalysis.Host;
 using Microsoft.CodeAnalysis.Internal.Log;
+using Microsoft.CodeAnalysis.LanguageService;
```
Comment (genlu) [inline src/Features/Core/Portable/Completion/Providers/Snippets/AbstractSnippetCompletionProvider.cs:14]: Is this necessary?

**Review by genlu — APPROVED** [review]

**Review by genlu — APPROVED** [review]

File: src/Features/Core/Portable/Completion/Providers/Snippets/AbstractSnippetCompletionProvider.cs (hunk 8 above)
Comment (akhera99) [reply src/Features/Core/Portable/Completion/Providers/Snippets/AbstractSnippetCompletionProvider.cs:14]: for the SymbolDescriptionOptions - yes
