### PR TITLE
Revise pattern parsing to fix compatibility break

### LINKED ISSUE #14785: C# 'is' expression with template + array no longer compiles
**Version Used**: Dev 15 RC build 15.0.25826.0

**Steps to Reproduce**:
1. Create C# console app, .NET Framework 4.6.1
2. Add the following method to Program class:

```
        private static string GetTypeName3(object item) {
            if (item == null) {
                return "null";
            } else if (item is Dictionary<string, object>[]) { // THIS CONDITION DOESN'T COMPILE
                return "tuple(dict(str -> object))";
            } else if (item is object[]) { // THIS CONDITION IS FINE
                return "tuple(object)";
            } else {
                return item.GetType().Name;
            }
        }
```
1. Compile

**Expected Behavior**:
Compiles with no error, like in VS 2015 Update 3.

**Actual Behavior**:
Compile error, red squiggles in editor.

```
1>c:\users\huvalo\documents\visual studio 2017\Projects\ConsoleApp2\ConsoleApp2\Program.cs(21,43,21,49): error CS1525: Invalid expression term 'string'
1>c:\users\huvalo\documents\visual studio 2017\Projects\ConsoleApp2\ConsoleApp2\Program.cs(21,49,21,50): error CS1026: ) expected
1>c:\users\huvalo\documents\visual studio 2017\Projects\ConsoleApp2\ConsoleApp2\Program.cs(21,49,21,50): error CS1525: Invalid expression term ','
1>c:\users\huvalo\documents\visual studio 2017\Projects\ConsoleApp2\ConsoleApp2\Program.cs(21,49,21,50): error CS1002: ; expected
1>c:\users\huvalo\documents\visual studio 2017\Projects\ConsoleApp2\ConsoleApp2\Program.cs(21,49,21,50): error CS1513: } expected
1>c:\users\huvalo\documents\visual studio 2017\Projects\ConsoleApp2\ConsoleApp2\Program.cs(21,57,21,58): error CS1001: Identifier expected
1>c:\users\huvalo\documents\visual studio 2017\Projects\ConsoleApp2\ConsoleApp2\Program.cs(21,57,21,58): error CS1002: ; expected
1>c:\users\huvalo\documents\visual studio 2017\Projects\ConsoleApp2\ConsoleApp2\Program.cs(21,57,21,58): error CS1525: Invalid expression term '>'
1>c:\users\huvalo\documents\visual studio 2017\Projects\ConsoleApp2\ConsoleApp2\Program.cs(21,58,21,59): error CS1525: Invalid expression term '['
1>c:\users\huvalo\documents\visual studio 2017\Projects\ConsoleApp2\ConsoleApp2\Program.cs(21,59,21,60): error CS0443: Syntax error; value expected
1>c:\users\huvalo\documents\visual studio 2017\Projects\ConsoleApp2\ConsoleApp2\Program.cs(21,60,21,61): error CS1002: ; expected
1>c:\users\huvalo\documents\visual studio 2017\Projects\ConsoleApp2\ConsoleApp2\Program.cs(21,60,21,61): error CS1513: } expected
1>c:\users\huvalo\documents\visual studio 2017\Projects\ConsoleApp2\ConsoleApp2\Program.cs(23,15,23,19): error CS1513: } expected
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #14785 

@AlekseyTs @agocke Please review
@dotnet/roslyn-compiler Additional reviews welcome

### CODE REVIEW

File: src/Compilers/CSharp/Test/Syntax/Parsing/ParsingTests.cs [hunk 1]
```diff
@@ -45,13 +45,20 @@ protected SyntaxTree UsingTree(string text, CSharpParseOptions options = null)
...
         {
             var root = ParseNode(text, options);
+            UsingNode(root);
+            return root;
+        }
+
+        /// <summary>
+        /// Initializes a depth-first preorder enumerator for the given node.
+        /// </summary>
+        protected void UsingNode(CSharpSyntaxNode root, CSharpParseOptions options = null)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Syntax/Parsing/ParsingTests.cs]: >, CSharpParseOptions options = null [](start = 54, length = 35)

It looks like this parameter is never used, please remove.

**Comment by AlekseyTs** [comment]
LGTM, modulo the not-meaningful parameter for UsingNode.

**Comment by gafter** [comment]
@agocke Please review.

File: src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs [hunk 2]
```diff
@@ -200,5 +201,96 @@ class C
...
+                                N(SyntaxKind.IdentifierToken, "C");
+                            }
+                            N(SyntaxKind.CommaToken);
+                            N(SyntaxKind.IdentifierName);
+                            {
+                                N(SyntaxKind.IdentifierToken, "D");
+                            }
+                            N(SyntaxKind.GreaterThanToken);
+                        }
+                        N(SyntaxKind.ArrayRankSpecifier);
```
Comment (agocke) [inline src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs]: Shouldn't this be indented one block less? `ArrayRank` isn't a part of `GenericName`, right?

**Comment by AlekseyTs** [comment]
LGTM

File: src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs]: Right.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 3]
```diff
@@ -5588,12 +5588,14 @@ private ScanTypeArgumentListKind ScanTypeArgumentList(NameOptions options)
...
-                            case SyntaxKind.BarToken:
-                            case SyntaxKind.CloseBraceToken:
-                            case SyntaxKind.EndOfFileToken:
+                            case SyntaxKind.AmpersandAmpersandToken: // e.g. `e is A<B> && e`
+                            case SyntaxKind.BarBarToken:             // e.g. `e is A<B> || e`
+                            case SyntaxKind.CaretToken:              // e.g. `e is A<B> ^ e`
+                            case SyntaxKind.BarToken:                // e.g. `e is A<B> | e`
+                            case SyntaxKind.AmpersandToken:          // e.g. `e is A<B> & e`
+                            case SyntaxKind.OpenBracketToken:        // e.g. `e is A<B>[]`
+                            case SyntaxKind.CloseBraceToken:         // e.g. `new { X = e is A<B> }`
```
Comment (VSadov) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: Do we care about pointers - ```e is A<B>*``` . 
Pointers do not box, so this will never be correct semantically, but should it parse similarly to  ```e is A<B>?```?

**Comment by VSadov** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs (hunk 3 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: No, because `*` binds more tightly than a comparison, it cannot be a type test on the left of a multiplication.
