### PR TITLE
Report errors from (unbound) lambdas when the enclosing invocation fails

### LINKED ISSUE #1867: Have compiler return semantic errors in lambdas even in the presence of syntax errors
Today, the compiler does not return semantic errors inside lambdas in the IDE if there are syntax errors.   This causes several quick fix scenarios to fail inside lambdas (for example #1239, #1241, and #1744 are all caused by this problem).  

Consider the code sample below from issue #1239:
```C#
using System.Threading.Tasks;

class C {
    C() {
        Task.Run(() => {
            new C(0)
        });
    }
}
```

_new C(0)_ will never be squiggled by the IDE because of the lack of a semicolon.  This makes quick-fixes that could generate a constructor unable to run because there is no error to trigger them.  

By having the compiler return semantic errors in lambdas even in the presence of syntax errors, many more IDE scenarios will "Just Work"

### PR DESCRIPTION
**Pull request by gafter**
Also reduce cascaded diagnostics in lambdas inside queries.
Fixes #1867

@CyrusNajmabadi @dotnet/roslyn-compiler Please review.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder.WithQueryLambdaParametersBinder.cs [hunk 1]
```diff
@@ -72,10 +72,12 @@ private BoundExpression SelectField(SimpleNameSyntax node, BoundExpression recei
                 {
                     // We only construct transparent query variables using anonymous types, so if we're trying to navigate through
                     // some other type, we must have some query API where the types don't match up as expected.
-                    // We should report this as an error of some sort.
-                    // TODO: DevDiv #737822 - reword error message and add test.
                     var info = new CSDiagnosticInfo(ErrorCode.ERR_UnsupportedTransparentIdentifierAccess, name, receiver.ExpressionSymbol ?? receiverType);
-                    Error(diagnostics, info, node);
+                    if (receiver.Type?.IsErrorType() != true)
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Binder/Binder.WithQueryLambdaParametersBinder.cs]: Can you explain this bit?

File: src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs [hunk 2]
```diff
@@ -1465,5 +1465,94 @@ static void Main(string[] args)
 
             CompileAndVerify(compilation);
         }
+
+        [Fact]
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs]: I'm surprised this new behavior didn't cause any breaks in existing tests.

File: src/Compilers/CSharp/Portable/Binder/Binder.WithQueryLambdaParametersBinder.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Binder.WithQueryLambdaParametersBinder.cs]: According to the language specification when we translate a Linq query such as `from x in e1 let y = e2 select M(x, y)` we create an anonymous type with a *transparent identifier* to represent both `x` and `y` in the final `select` clause. This can fall apart in (at least) two ways.

First, the `Select` method it translates into might not follow the *linq pattern`; it could, for example, be written to accept a `Func<int, int>` as its argument instead of a `Func<T, U>`. That would cause the compiler's normal translation "not to work" because the translation of `x` and `y` in the final `select clause` would just not work. This error message `ErrorCode.ERR_UnsupportedTransparentIdentifierAccess` is for that case, and tells the user that their Linq API may be malformed.

The second way it could fall apart is if there is some error earlier in the query expression. In that case the compiler would not be able to successfully do overload resolution, and would assign an `ErrorType` to the lambda argument. In this case there is no point telling the user that their API might be malformed; that would be an example of a *cascaded error message*. We always try to eliminate cascaded error messages, but we went too far before, simply dropping all diagnostics from lambdas we could not bind. Now we do better, but this particular diagnostic would be a cascaded error under the new scheme, so we suppress it when we have an error type.

File: src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LambdaTests.cs]: Me too. If did until I added the `if` statement you asked about.

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs [hunk 3]
```diff
@@ -713,11 +713,23 @@ private static void CheckRestrictedTypeReceiver(BoundExpression expression, Comp
 
             if (!result.Succeeded)
             {
-                // If the arguments had an error reported about them then suppress further error
-                // reporting for overload resolution. 
-
-                if (!analyzedArguments.HasErrors)
+                if (analyzedArguments.HasErrors)
+                {
+                    // Errors for arguments have already been reported, except for unbound lambdas.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: Would it make sense to report errors for unbound lambdas where it is done for other arguments? Also since we are binding the lambdas for error recovery, would it make sense to capture BoundLambda nodes as the arguments in the tree so that SemanticModel wouldn't have to deal with UnboundLambdas again?

File: src/Compilers/CSharp/Test/Syntax/Parsing/ParserRegressionTests.cs [hunk 4]
```diff
@@ -80,7 +80,7 @@ public void c024928()
         }
 
         [WorkItem(2771, "https://github.com/dotnet/roslyn/issues/2771")]
-        [Fact]
+        [Fact(Skip = "This test is flaky under low memory conditions; it fails in StringBuilder.ToString in the parser")]
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Syntax/Parsing/ParserRegressionTests.cs]: Please move this change into a separate commit, this is a second PR that contains this change.

**Comment by AlekseyTs** [comment]
Please add WorkItem attribute to all new tests.

**Comment by AlekseyTs** [comment]
All new tests are targeting scenarios of using lambdas as arguments within method invocations. What about an assignment case, i.e. a lambda is assigned to a variable typed as a delegate? Delegate creation scenarios (new DelegateType (lambda))? Any other lambda usage scenarios missing?

**Comment by gafter** [comment]
This is one of a series of PRs addressing the user story. This PR addresses the specific use cases reported, which appear in the tests. This is an iterative process; as more use cases are discovered, additional PRs will be submitted.

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs (hunk 3 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: To your first question: We cannot report errors for unbound lambdas where we report errors for other arguments, as we need the unbound lambdas in order to do overload resolution.

To your second question: Yes, it *would* be a good idea to preserve these for the `SemanticModel`. I'll revise.

Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: Actually, there is nothing to revise. The `UnboundLambda` already saves (caches) the `BoundLambda` that is the result of `BindForErrorRecovery`, and it is already used in `SemanticModel`. Saving replacing them explicitly in the bound argument list wouldn't make things different in any observable way.

**Comment by gafter** [comment]
All comments addressed. Please re-review.

**Comment by AlekseyTs** [comment]
LGTM

**Comment by TyOverby** [comment]
test prtest/mac/dbg/unit32 please

**Comment by gafter** [comment]
@dotnet/roslyn-compiler Can I please have a second sign-off on this PR?

**Comment by VSadov** [comment]
LGTM
