### PR TITLE
Adjust solution crawler logic to choose next best project to reduce expensive allocations

### LINKED ISSUE #22609: StateSet.ContainsAnyDocumentOrProjectDiagnostics heavy allocator
**Version Used**: 15.4 Preview 4

**Steps to Reproduce**:

1. Open Roslyn.sln
2. Work for a bit

**Result**:

`StateSet.ContainsAnyDocumentOrProjectDiagnostics` allocates ~5% of the total allocation load in devenv.exe. Roughly 75% of this is in `GetActiveFileStates`, while 25% of this is in the concurrent dictionary `GetEnumerator()` call.

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #22609

Background analysis in solution crawler currently chooses the documents/projects to analyze using the following priority order:
1. Active document
2. Open documents in a project processed based on the project dependency graph that had one or more diagnostics in prior snapshot
3. Open documents on the remaining dependent projects of the active document project based on the project dependency graph
4. Rest of the open documents
5. Projects processed based on the project dependency graph of the active document project that had one or more diagnostics (If FSA is enabled)
6. Remaining dependent projects of the active document project based on the project dependency graph (If FSA is enabled)
7. Rest of the projects (If FSA is enabled)

The logic to compute if a project had any diagnostics in the prior snapshot has been known to be pretty expensive causing lot of allocations. Additionally, we are not sure if that is really providing any additional user experience improvement for error list refresh. This change removes the checks in 2. and 6. above.

### CODE REVIEW

**Review by ToddGrun — APPROVED** [review]
:shipit:

File: src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.AsyncWorkItemQueue.cs [hunk 1]
```diff
@@ -259,26 +258,17 @@ protected CancellationToken GetNewCancellationToken_NoLock(object key)
...
                         {
-                            if (workQueue.ContainsKey(dependingProjectId) && analyzerService?.ContainsDiagnostics(Workspace, dependingProjectId) == true)
+                            if (workQueue.ContainsKey(dependingProjectId))
                             {
                                 return dependingProjectId;
                             }
                         }
                     }
 
-                    // prefer a project that has diagnostics as next project to process.
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.AsyncWorkItemQueue.cs:273]: could you file an issue saying that we should consider walkign in this order in workspace pull diags.  We have the information about the previous result, so we should be able to add this back in.  Personally, i do think it's a sensible heuristic.  But i am totally ok with it not being deep in the engine, but a policy decision of the system that 'pulls'.

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.AsyncWorkItemQueue.cs (hunk 1 above)
Comment (mavasani) [reply src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.AsyncWorkItemQueue.cs:273]: #67687

**Comment by mavasani** [comment]
> > ```
> >             if (_activeFileStates.Count == 1 && _projectStates.IsEmpty)
> > ```
> 
> I'd like to understand this method better:
> 
> 1. I assume this method never get intermingled with writes to _activeFileStates or _projectStates? If so, a comment would help.
> 2. It's my understanding the the Count property is pretty inefficient wrt taking locks. This code runs on the VS side, right, and doesn't get .net core benefits, right?
> 
> Refers to: src/Features/LanguageServer/Protocol/Features/Diagnostics/EngineV2/DiagnosticIncrementalAnalyzer.StateSet.cs:48 in [3f1406c](https://github.com/dotnet/roslyn/commit/3f1406c5baae5c379da6c0a457e18f25246b24ff). [](commit_id = [3f1406c](https://github.com/dotnet/roslyn/commit/3f1406c5baae5c379da6c0a457e18f25246b24ff), deletion_comment = False)

1. Yes, correct. I can add a comment in a subsequent PR
2. Thanks, that is good to know, and yes this code runs on VS side. However, this method is not on a hot path - it is called only on VS shutdown.
