### PR TITLE
Fix extra space in editorconfig

### LINKED ISSUE #50577: Multiple file patterns in editorconfig don't work as expected
See https://github.com/dotnet/roslyn/pull/50569/commits/e1e9fa4a6bc5accab2bdd90fbc79bf90d9ae9736

Warnings from CA1822 weren't reported from the build of this commit.

It was only reported for https://github.com/dotnet/roslyn/pull/50569/commits/96b0f6dfbe6bb03d90827ef57f4cd153ffb508f3

However, the added line is already existing for src/VisualStudio in:

https://github.com/dotnet/roslyn/blob/96b0f6dfbe6bb03d90827ef57f4cd153ffb508f3/.editorconfig#L264

### PR DESCRIPTION
**Pull request by Youssef1313**
Closes #50577

### CODE REVIEW

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/AlwaysActivateInProcLanguageClient.cs [hunk 1]
```diff
@@ -39,7 +37,7 @@ internal class AlwaysActivateInProcLanguageClient : AbstractInProcLanguageClient
             ILspWorkspaceRegistrationService lspWorkspaceRegistrationService)
             : base(languageServerProtocol, workspace, diagnosticService: null, listenerProvider, lspWorkspaceRegistrationService, diagnosticsClientName: null)
         {
-            _globalOptionService = globalOptionService;
+            _ = globalOptionService;
```
Comment (Youssef1313) [inline src/VisualStudio/Core/Def/Implementation/LanguageClient/AlwaysActivateInProcLanguageClient.cs:40]: I don't know whether the removal of the parameter from the ctor can affect code relying on IVT. So I kept it with a discard to silence the warning. If it's known that this ctor can safely be modified, let me know.

File: src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs [hunk 2]
```diff
@@ -104,11 +102,6 @@ public GeneratedFileDirectoryInfo(DocumentId documentId, Type generatorType)
             // The IVsRunningDocumentTable is a free-threaded VS service that allows fetching of the service and advising events
             // to be done without implicitly marshalling to the UI thread.
             _runningDocumentTable = _serviceProvider.GetService<SVsRunningDocumentTable, IVsRunningDocumentTable>();
-            _runningDocumentTableEventTracker = new RunningDocumentTableEventTracker(
```
Comment (Youssef1313) [inline src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs:107]: Can the constructor call for some reason do something useful?

File: src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/OnAutoInsert/OnAutoInsertHandler.cs [hunk 3]
```diff
@@ -31,8 +31,6 @@ public OnAutoInsertHandler()
 
         public async Task<DocumentOnAutoInsertResponseItem?> HandleRequestAsync(DocumentOnAutoInsertParams request, RequestContext context, CancellationToken cancellationToken)
         {
-            using var _ = ArrayBuilder<DocumentOnAutoInsertResponseItem>.GetInstance(out var response);
```
Comment (Youssef1313) [inline src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/OnAutoInsert/OnAutoInsertHandler.cs:34]: The method was refactored in #49711 and this line was forgotten to be removed in that PR.

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/AlwaysActivateInProcLanguageClient.cs (hunk 1 above)
Comment (mavasani) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/AlwaysActivateInProcLanguageClient.cs:40]: Yes, you can safely remove the parameter of a MEF importing ctor.

File: src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs (hunk 2 above)
Comment (mavasani) [reply src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs:107]: @jasonmalinowski?

Comment (jasonmalinowski) [reply src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs:107]: Yes, this constructor call, as a side effect, subscribes to events.

Comment (jasonmalinowski) [reply src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs:107]: And the integration test failures are the source generator tests, so that's probably because of this.

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/AlwaysActivateInProcLanguageClient.cs (hunk 1 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/AlwaysActivateInProcLanguageClient.cs:40]: 📝 Our use of `[Obsolete]` on these constructors ensures they can be altered.

File: src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs [hunk 4]
```diff
@@ -104,11 +102,6 @@ public GeneratedFileDirectoryInfo(DocumentId documentId, Type generatorType)
             // The IVsRunningDocumentTable is a free-threaded VS service that allows fetching of the service and advising events
             // to be done without implicitly marshalling to the UI thread.
             _runningDocumentTable = _serviceProvider.GetService<SVsRunningDocumentTable, IVsRunningDocumentTable>();
```
Comment (sharwell) [inline src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs:104]: ❗ This call is not allowed within a MEF constructor

File: src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs (hunk 2 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs:107]: @jasonmalinowski These event listeners are not allowed to be subscribed within the constructor of a MEF component.

Comment (jasonmalinowski) [reply src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs:107]: The shell has a specific implementation that specifically allows this use, for precisely this reason.

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs [hunk 5]
```diff
@@ -50,7 +49,6 @@ internal partial class VisualStudioSymbolNavigationService : ForegroundThreadAff
             var componentModel = IServiceProviderExtensions.GetService<SComponentModel, IComponentModel>(_serviceProvider);
             _editorAdaptersFactory = componentModel.GetService<IVsEditorAdaptersFactoryService>();
             _metadataAsSourceFileService = componentModel.GetService<IMetadataAsSourceFileService>();
-            _sourceGeneratedFileManager = componentModel.GetService<SourceGeneratedFileManager>();
```
Comment (sharwell) [inline src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs:53]: 📝 All of these should be promoted to constructor parameters so MEF can create the objects prior to started to construct this object.

Comment (Youssef1313) [reply src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs:53]: @sharwell This constructor isn't marked as `ImportingConstructor`.

File: src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs (hunk 4 above)
Comment (Youssef1313) [reply src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs:104]: @sharwell Do you want to file a tracking issue for removing this call?

File: src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Formatting/AbstractFormatDocumentHandlerBase.cs [hunk 6]
```diff
@@ -19,7 +19,9 @@ internal abstract class AbstractFormatDocumentHandlerBase<RequestType, ResponseT
         public override bool MutatesSolutionState => false;
         public override bool RequiresLSPSolution => true;
 
+#pragma warning disable IDE0060 // Remove unused parameter 'documentIdentifier' - Unsure whether it can break any code relying on IVTs.
```
Comment (Youssef1313) [inline src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Formatting/AbstractFormatDocumentHandlerBase.cs:22]: @jasonmalinowski Do you know if this suppression should remain or otherwise I need a better certain comment.

Comment (jasonmalinowski) [reply src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Formatting/AbstractFormatDocumentHandlerBase.cs:22]: @davidwengier? I wouldn't imagine we have IVTs in our LSP handlers (would seem to defeat the point architecturally), but I never cease to be surprised about our codebase sometimes.

Comment (mgoertz-msft) [reply src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Formatting/AbstractFormatDocumentHandlerBase.cs:22]: This method isn't used by IVT. The pattern for our LSP handlers is to get a language service, in this case the IXamlFormattingService a few lines below, and those cannot be changed (at least not without some careful coordination).

Comment (davidwengier) [reply src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Formatting/AbstractFormatDocumentHandlerBase.cs:22]: Fine by me. Nothing on the VSMac side is using LSP, and I agree with Jason this would be an odd way to do it :)

**Comment by Youssef1313** [comment]
@davidwengier @jasonmalinowski The current failure is to remove redundant assignment at:

```
            // At this point we've mutated the workspace.  So we're no longer cancellable.
            cancellationToken = CancellationToken.None;
```

While cancellationToken isn't used after this assignment, the line may have been written to be future-proof not to accidentally use the original token later on. Not sure if I should suppress the warning or delete this assignment.

**Comment by Youssef1313** [comment]
Closing and reopening to make sure build is still green (i.e, no changes violating rules have made it into `main` after my last commit).

@jasonmalinowski @davidwengier Is this ready to merge?

File: src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs [hunk 7]
```diff
@@ -104,7 +102,7 @@ public GeneratedFileDirectoryInfo(DocumentId documentId, Type generatorType)
...
-            _runningDocumentTableEventTracker = new RunningDocumentTableEventTracker(
+            _ = new RunningDocumentTableEventTracker(
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/Workspace/SourceGeneratedFileManager.cs:105]: I can't say I'm a particular fan here that we're creating a type with a side effect and then hiding it. This might be tricky to debug later -- can we just keep the field in this case?

File: src/VisualStudio/Core/Def/Implementation/UnusedReferences/RemoveUnusedReferencesCommandHandler.cs [hunk 8]
```diff
@@ -47,7 +46,6 @@ internal sealed class RemoveUnusedReferencesCommandHandler
             VisualStudioWorkspace workspace)
         {
             _unusedReferenceDialogProvider = unusedReferenceDialogProvider;
-            _vsHierarchyItemManager = vsHierarchyItemManager;
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/UnusedReferences/RemoveUnusedReferencesCommandHandler.cs:50]: Should also be removed from the constructor parameter list as well.

**Comment by jasonmalinowski** [comment]
@Youssef1313 Looks like something else did sneak in. 😢 Also reviewed the rest of this finally, so good to take it once that issue is fixed and comments addressed.

**Comment by Youssef1313** [comment]
> eng\targets\Bootstrap.targets(4,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Too many compiler server connection failures detected

:/

**Comment by Youssef1313** [comment]
@jasonmalinowski Build is green 🎉

**Review by jasonmalinowski — APPROVED** [review]
