### PR TITLE
Do not copy nullable value type receiver of a constrained call.

### LINKED ISSUE #66162: Nullable value type receiver of a constrained call is unexpectedly copied
```
        [Fact]
        public void GenericTypeParameterAsReceiver_Call_Nullable()
        {
            var source = @"
using System;

#pragma warning disable CS0659 // 'Item' overrides Object.Equals(object o) but does not override Object.GetHashCode()
    
struct Item
{
    public int Count;

    public override bool Equals(object obj)
    {
        Console.WriteLine(""Position Equals for item '{0}'"", Count);
        return base.Equals(obj);
    }
}

class Program
{
    static void Main()
    {
        Item? item1 = new Item {Count = 1};
        Call1(item1);
        Item? item2 = new Item {Count = 2};
        Call2(ref item2);
    }

    static void Call1<T>(T item)
    {
        item.Equals(GetOffset(ref item));
    }

    static void Call2<T>(ref T item)
    {
        item.Equals(GetOffset(ref item));
    }
    
    static int value = 0;
    static int GetOffset<T>(ref T item)
    {
        item = (T)(object)new Item {Count = --value};
        return 0;
    }
}
";
            var verifier = CompileAndVerify(source, options: TestOptions.ReleaseExe, expectedOutput: @"
Position Equals for item '-1'
Position Equals for item '-2'
").VerifyDiagnostics();
        }
```

Observed:
```
Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenCallTests.GenericTypeParameterAsReceiver_Call_Nullable [FAIL]
  Roslyn.Test.Utilities.ExecutionException : 
  Execution failed for assembly 'd9d40dcd-4b54-4258-8425-bf38af6ab1e7, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
  Expected: 
  Position Equals for item '-1'
  Position Equals for item '-2'
  
  Actual: Position Equals for item '1'
  Position Equals for item '2'
```

This is a regression from https://github.com/dotnet/roslyn/pull/65642

### PR DESCRIPTION
**Pull request by AlekseyTs**
The check that we used to detect value types at runtime didn’t quite work for nullable value types due to special boxing behavior for them. Switching to `typeof(T).IsValueType` check instead.

Fixes #66162.
Related to #63221.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@333fred Please review, you should know the context since you reviewed #65642

**Comment by jcouv** [comment]
FWIW, I took a look (trying to understand the problem in the bug and how it was resolved), but couldn't figure it out after 20 minutes so I'm leaving it for someone else or if some more context could be provided (what's wrong with the IL from `Call1` or `Call2` in example, how does the fix address the problem?)

**Comment by AlekseyTs** [comment]
@jcouv 
> I took a look (trying to understand the problem in the bug and how it was resolved), but couldn't figure it out after 20 minutes so I'm leaving it for someone else or if some more context could be provided (what's wrong with the IL from `Call1` or `Call2` in example, how does the fix address the problem?)

If you look at the IL diff for affected tests, you'll notice that the change replaces sequences like 
```
  IL_0002:  ldloca.s   V_0
  IL_0004:  initobj    ""T""
  IL_000a:  ldloc.0
  IL_000b:  box        ""T""
  IL_0010:  brtrue.s   IL_001a
```

with sequences like:
```
  IL_0002:  ldtoken    ""T""
  IL_0007:  call       ""System.Type System.Type.GetTypeFromHandle(System.RuntimeTypeHandle)""
  IL_000c:  call       ""bool System.Type.IsValueType.get""
  IL_0011:  brtrue.s   IL_001b
```

These IL sequences produce the same result for all types, but for nullable value types. There is a special boxing behavior for nullable value types, boxing of a default value of a nullable value type yields null. Therefore, the old IL is not going to jump for a nullable value type, but instead going to fall through to the code that is supposed to be executed only for a class. That is wrong because a nullable value type is a value type.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 1]
```diff
@@ -4579,6 +4579,21 @@ internal enum AddressKind
                         stackLocalsOpt));
                     goto case BoundKind.ConditionalReceiver;
 
+                case BoundKind.ComplexReceiver:
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:4582]: Can we reach this? I thought this node would only be introduced in a later phase (but not during initial binding).

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:4582]: > Can we reach this? I thought this node would only be introduced in a later phase (but not during initial binding).

The same goes for ```BoundKind.ComplexConditionalReceiver```. Just follow the pattern.

File: src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs [hunk 2]
```diff
@@ -1780,16 +1839,91 @@ LocalDefinition emitGenericReceiver(BoundCall call, out CallKind callKind)
...
+
+                return whenValueTypeLabel;
+            }
+
+            return null;
+        }
+
+        private void EmitComplexReceiver(BoundComplexReceiver expression, bool used)
+        {
+            Debug.Assert(!used);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:1874]: nit: What's the benefit of only asserting? Throwing seems better.
We can still keep the conditional `AdjustStack` below for the day we could reach with here with used==true.

**Comment by jcouv** [comment]
>                 );

We have a note in the compiler test plan: "If you add a new expression form that requires spilling, test it in the catch filter". Consider adding a test for this.

---
Refers to: src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenCallTests.cs:30721 in 208dc2a. [](commit_id = 208dc2aea142a74e078074d3a174defa2930c562, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 1 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:4582]: Why not throw unreachable exception since this is unreachable? I'd do that for `ComplexConditionalReceiver` too

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 1) with test suggestion to consider

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs [hunk 3]
```diff
@@ -2940,6 +2940,20 @@ public override BoundNode VisitComplexConditionalReceiver(BoundComplexConditiona
             return null;
         }
 
+        public override BoundNode VisitComplexReceiver(BoundComplexReceiver node)
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:2943]: Are any flow passes actually going to see one of these? It looks like they're only created during local lowering, so I wouldn't expected them to be seen.

**Review by 333fred — COMMENTED** [review]
Done review pass (commit 1)

File: src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:1874]: > What's the benefit of only asserting? Throwing seems better.

The implementation is doing the right thing. I do not see any point in throwing. The assert will help us identify the test scenario.

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs (hunk 3 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:2943]: > Are any flow passes actually going to see one of these? It looks like they're only created during local lowering, so I wouldn't expected them to be seen.

This code path is reachable. Flow analysis is done during async rewrite, etc.

**Comment by AlekseyTs** [comment]
>                 );

> We have a note in the compiler test plan: "If you add a new expression form that requires spilling, test it in the catch filter". Consider adding a test for this.

I think that refers to language constructs that themselves trigger spilling, like async or patterns, and is not talking about new bound nodes. I am not adding anything like that. 

---
In reply to: [1376544884](https://github.com/dotnet/roslyn/pull/66311#issuecomment-1376544884) [](http://example.com/codeflow?ancestors=1376544884,1376544884)

---
Refers to: src/Compilers/CSharp/Test/Emit2/CodeGen/CodeGenCallTests.cs:30721 in 208dc2a. [](commit_id = 208dc2aea142a74e078074d3a174defa2930c562, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:4582]: > Why not throw unreachable exception since this is unreachable? I'd do that for ```ComplexConditionalReceiver``` too

I am comfortable going as is

**Review by 333fred — APPROVED** [review]
