### PR TITLE
use predefined type keywords if the real types would only be bracketed

### LINKED ISSUE #7955: Generate method creates unnecessary escaping
_Created from internal bug 175760_

**Repro:**
1. Turn off the VB option "Prefer intrinsic predefined type keyword when declaring locals, parameters and members".
2. `Dim x = SomeMethod("asdf")`
3. Invoke Generate Method.

**Expected:**
``` VB
Private Function SomeMethod(v as String) as Object
    Throw New NotImplementedException()
End Function
```

**Actual:**
``` VB
Private Function SomeMethod(v as [String]) as [Object]
    Throw New NotImplementedException()
End Function
```

### PR DESCRIPTION
**Pull request by brettfo**
e.g., always prefer `String` to `[String]` in VB even if real types are preferred.

Fixes #7955.

### CODE REVIEW

**Comment by brettfo** [comment]
@dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
:+1:

File: src/EditorFeatures/Test2/Simplification/TypeNameSimplifierTest.vb [hunk 1]
```diff
@@ -4390,6 +4390,80 @@ End Class
...
+End Class
+]]></text>
+
+            Await TestAsync(input, expected, DontPreferIntrinsicPredefinedTypeKeywordInDeclaration())
+        End Function
+#End Region
+
+#Region "Helpers"
+
+        Protected Function DontPreferIntrinsicPredefinedTypeKeywordInDeclaration() As Dictionary(Of OptionKey, Object)
```
Comment (Pilchie) [inline src/EditorFeatures/Test2/Simplification/TypeNameSimplifierTest.vb]: This could probably be a `Shared` field, instead of a `Protected Function`.

**Comment by Pilchie** [comment]
:+1:

File: src/EditorFeatures/Test2/Simplification/TypeNameSimplifierTest.vb (hunk 1 above)
Comment (brettfo) [inline src/EditorFeatures/Test2/Simplification/TypeNameSimplifierTest.vb]: Fixed.
