### PR TITLE
Dont generate Getter/Setter when Writeonly/Readonly for VB Properties

### LINKED ISSUE #2096: VB incorrect codespit when hit Enter on readonly indexed property (regression)
REPRO: within a VB class, write this line and hit ENTER
```vb
Public readonly property key(i As integer) As string
```
WHAT I EXPECT: it should spit out only the getter

WHAT I GET: it spits out both getter and setter. The "Set" keyword of course has a red underline.

I repro'd this in Dev14RC-Signed-Release\20150411.1

### PR DESCRIPTION
**Pull request by basoundr**
fix #2096 Dont generate  a getter for a Writeonly property and dont
generate a setter for a Readonly properly in VB during End Construct
generation

### CODE REVIEW

**Comment by basoundr** [comment]
Reviewers: @Pilchie @jasonmalinowski @dpoeschl @rchande @brettfo @balajikris @jmarolf

File: src/EditorFeatures/VisualBasic/EndConstructGeneration/EndConstructStatementVisitor_Properties.vb [hunk 1]
```diff
@@ -122,6 +122,10 @@ Namespace Microsoft.CodeAnalysis.Editor.VisualBasic.EndConstructGeneration
         ''' might be in the middle of typing one that would be a false positive. </param>
         Private Function NeedsGetAccessor(propertyDeclaration As PropertyStatementSyntax, Optional accessorToIgnore As AccessorBlockSyntax = Nothing) As Boolean
             Dim propertyBlock = propertyDeclaration.GetAncestor(Of PropertyBlockSyntax)()
+            If propertyDeclaration.Modifiers.Any(Function(m) m.IsKind(SyntaxKind.WriteOnlyKeyword)) Then
```
Comment (jasonmalinowski) [inline src/EditorFeatures/VisualBasic/EndConstructGeneration/EndConstructStatementVisitor_Properties.vb]: This code already seems to exist on line 139 post-edit. Is that code dead?

Comment (Pilchie) [inline src/EditorFeatures/VisualBasic/EndConstructGeneration/EndConstructStatementVisitor_Properties.vb]: Looks like it's dead, because we will return true if there is no block on line 130.

Comment (Pilchie) [inline src/EditorFeatures/VisualBasic/EndConstructGeneration/EndConstructStatementVisitor_Properties.vb]: I would remove the code on line 139, and move this check before the declaration of `propertyBlock`

File: src/EditorFeatures/VisualBasicTest/EndConstructGeneration/PropertyBlockTests.vb [hunk 2]
```diff
@@ -275,5 +275,41 @@ Namespace Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.EndConstructGenera
                        "End Interface"},
                 caret:={1, -1})
         End Sub
+
+        <Fact, Trait(Traits.Feature, Traits.Features.EndConstructGeneration)>
+        <WorkItem(2096, "https://github.com/dotnet/roslyn/issues/2096")>
+        Public Sub DontGenerateGetForReadonlyProperty()
```
Comment (Pilchie) [inline src/EditorFeatures/VisualBasicTest/EndConstructGeneration/PropertyBlockTests.vb]: Names are reversed - you *are* generating a get in the readonly property :)

File: src/EditorFeatures/VisualBasic/EndConstructGeneration/EndConstructStatementVisitor_Properties.vb (hunk 1 above)
Comment (basoundr) [inline src/EditorFeatures/VisualBasic/EndConstructGeneration/EndConstructStatementVisitor_Properties.vb]: This is what happens when I try to create a PR at the end of the day

**Comment by basoundr** [comment]
Reviewers: @Pilchie @jasonmalinowski @dpoeschl @rchande @brettfo @balajikris @jmarolf

**Comment by Pilchie** [comment]
:shipit:

**Comment by jasonmalinowski** [comment]
:sparkles:
