### PR TITLE
Fix crash in classification service

### LINKED ISSUE #33167: VS crashes when renaming a wpf xaml file to a .cs file
Repro steps:
1. create a WPF app
2. open xaml in designer
3. rename .xaml file to .cs

stack-trace:
```
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object. 
at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.<AddSyntacticClassificationsAsync>d__3.MoveNext() --- 
End of stack trace from previous location where exception was thrown 
--- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject) 
--- End of inner exception stack trace --- 
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) 
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) 
at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SyntacticClassificationTaggerProvider.TagComputer.AddClassifiedSpansForCurrentTree[TClassificationService](IClassificationDelegationService`1 delegationService, TClassificationService classificationService, SnapshotSpan span, Document document, List`1 classifiedSpans) at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SyntacticClassificationTaggerProvider.TagComputer.AddClassifiedSpans[TClassificationService](IClassificationDelegationService`1 delegationService, TClassificationService classificationService, SnapshotSpan span, List`1 classifiedSpans) 
at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SyntacticClassificationTaggerProvider.TagComputer.GetTags[TClassificationService](NormalizedSnapshotSpanCollection spans, HostLanguageServices languageServices, IClassificationDelegationService`1 delegationService) 
at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SyntacticClassificationTaggerProvider.TagComputer.GetTags(NormalizedSnapshotSpanCollection spans) 
at Microsoft.CodeAnalysis.Editor.Implementation.Classification.SyntacticClassificationTaggerProvider.Tagger.GetTags(NormalizedSnapshotSpanCollection spans) 
at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__46.MoveNext() 
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object. 
at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.<AddSyntacticClassificationsAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown --- 
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)<--- 
```

The cause seems to be when rename happened, VS creates a snapshot of content type "CSharp" for the xaml file, which however is still in the special "-xaml" project in the workspace.

### PR DESCRIPTION
**Pull request by genlu**
https://github.com/dotnet/roslyn/pull/33168/commits/d94f2129de2a511e8cba353b404e847d1f479b8a Fix #33167 

https://github.com/dotnet/roslyn/pull/33168/commits/8d4e28ea25fb92d807aa2017bf4f62fa71a32e74 is an attempt to (at least partially) fix internal bug [763988](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/763988). Since we still don't know the root cause, and we don't wanna crash VS for highlighting failure, change crash to NFW instead.

### CODE REVIEW

File: src/EditorFeatures/Core/Implementation/Classification/SyntacticClassificationTaggerProvider.TagComputer.cs [hunk 1]
```diff
@@ -178,7 +178,7 @@ public void DisconnectFromWorkspace()
 
             private void EnqueueParseSnapshotTask(Document newDocument)
             {
-                if (newDocument != null)
+                if (newDocument != null && newDocument.SupportsSyntaxTree)
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/Classification/SyntacticClassificationTaggerProvider.TagComputer.cs]: 1. why not just export this classifier provider for C#/VB?  Then this wouldn't ever even run for languages that don't support syntax trees?
2. i need to understand the issue more deeply.  We've have this type a *long* time.  It hasn't been a problem yet for F# or TS/JS.  So why now is there suddenly an issue with a crash here?

Comment (genlu) [reply src/EditorFeatures/Core/Implementation/Classification/SyntacticClassificationTaggerProvider.TagComputer.cs]: I'm still trying to figure out what's the root cause is, but I think the crash is directly caused by VS providing us a buffer of content type "CSharp" for a xaml document.

Here's the stacktrace after the renaming of xaml file that eventually leads to the crash.
```
Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.Classification.SyntacticClassificationTaggerProvider.TagComputer.EnqueueParseSnapshotTask(Microsoft.CodeAnalysis.Document newDocument) Line 181
	at C:\github\roslyn\src\EditorFeatures\Core\Implementation\Classification\SyntacticClassificationTaggerProvider.TagComputer.cs(181)
Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.Classification.SyntacticClassificationTaggerProvider.TagComputer.ConnectToWorkspace(Microsoft.CodeAnalysis.Workspace workspace) Line 158
	at C:\github\roslyn\src\EditorFeatures\Core\Implementation\Classification\SyntacticClassificationTaggerProvider.TagComputer.cs(158)
Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.Classification.SyntacticClassificationTaggerProvider.TagComputer.TagComputer(Microsoft.VisualStudio.Text.ITextBuffer subjectBuffer, Microsoft.CodeAnalysis.Editor.IForegroundNotificationService notificationService, Microsoft.CodeAnalysis.Shared.TestHooks.IAsynchronousOperationListener asyncListener, Microsoft.CodeAnalysis.Editor.Shared.Utilities.ClassificationTypeMap typeMap, Microsoft.CodeAnalysis.Editor.Implementation.Classification.SyntacticClassificationTaggerProvider taggerProvider) Line 92
	at C:\github\roslyn\src\EditorFeatures\Core\Implementation\Classification\SyntacticClassificationTaggerProvider.TagComputer.cs(92)
Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.Classification.SyntacticClassificationTaggerProvider.CreateTagger<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>(Microsoft.VisualStudio.Text.ITextBuffer buffer) Line 51
	at C:\github\roslyn\src\EditorFeatures\Core\Implementation\Classification\SyntacticClassificationTaggerProvider.cs(51)
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>.InstantiateBuferTagger(System.Lazy<Microsoft.VisualStudio.Text.Tagging.ITaggerProvider, Microsoft.VisualStudio.Text.Tagging.INamedTaggerMetadata> factory, Microsoft.VisualStudio.Text.ITextBuffer textBuffer, System.Collections.Generic.IList<Microsoft.VisualStudio.Text.Tagging.ITagger<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>> newTaggers)
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>.AddTaggers(Microsoft.VisualStudio.Text.ITextBuffer textBuffer, System.Collections.Generic.IList<Microsoft.VisualStudio.Text.Tagging.ITagger<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>> newTaggers)
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>.OnContentTypeChanged(object sender, Microsoft.VisualStudio.Text.ContentTypeChangedEventArgs e)
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent<Microsoft.VisualStudio.Text.ContentTypeChangedEventArgs>(object sender, System.EventHandler<Microsoft.VisualStudio.Text.ContentTypeChangedEventArgs> eventHandlers, Microsoft.VisualStudio.Text.ContentTypeChangedEventArgs args)
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Implementation.BaseBuffer.ContentTypeChangedEventRaiser.RaiseEvent(Microsoft.VisualStudio.Text.Implementation.BaseBuffer baseBuffer, bool immediate)
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Implementation.BufferGroup.RaiseEvents()
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Implementation.BufferGroup.FinishEdit()
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Implementation.BaseBuffer.TextBufferEdit.Apply()
Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Implementation.BaseBuffer.ChangeContentType(Microsoft.VisualStudio.Utilities.IContentType newContentType, object editTag)
Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.TextDocData.SetLanguageServiceID(ref System.Guid guidLangService, bool changeContentType, bool sendChangedEvent)
Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.TextDocData.ChooseLanguageServicePerBufferMoniker(bool shouldSendEvent)
Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.TextDocData.SetData_Moniker(string newMoniker, bool shouldSendEvent)
Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.TextDocData.SetData(ref System.Guid riidKey, object vtData)
Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.TextDocData.RenameDocData(uint grfAttribs, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy pHierNew, uint itemidNew, string pszMkDocumentNew)
[Native to Managed Transition]
[Managed to Native Transition]
Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.VisualStudio.Shell.Flavor.FlavoredProjectBase.SetProperty(uint itemId, int propId, object property)
Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.VisualStudio.Shell.Flavor.FlavoredProjectBase.Microsoft.VisualStudio.Shell.Interop.IVsHierarchy.SetProperty(uint itemId, int propId, object property)
[Native to Managed Transition]
[Managed to Native Transition]
Microsoft.VisualStudio.Shell.TreeNavigation.HierarchyProvider.dll!Microsoft.VisualStudio.PlatformUI.HierarchyItem.RenameLabel.set(string value)
Microsoft.VisualStudio.Shell.TreeNavigation.HierarchyProvider.dll!Microsoft.VisualStudio.PlatformUI.HierarchyRenameItemTransaction.Commit(Microsoft.Internal.VisualStudio.PlatformUI.RenameItemCompletionFocusBehavior completionFocusBehavior)
Microsoft.VisualStudio.Shell.15.0.dll!Microsoft.Internal.VisualStudio.PlatformUI.EditableItemTextBox.OnKeyDown(System.Windows.Input.KeyEventArgs e)
PresentationCore.dll!System.Windows.UIElement.OnKeyDownThunk(object sender, System.Windows.Input.KeyEventArgs e)
PresentationCore.dll!System.Windows.Input.KeyEventArgs.InvokeEventHandler(System.Delegate genericHandler, object genericTarget)
PresentationCore.dll!System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate handler, object target)
PresentationCore.dll!System.Windows.RoutedEventHandlerInfo.InvokeHandler(object target, System.Windows.RoutedEventArgs routedEventArgs)
PresentationCore.dll!System.Windows.EventRoute.InvokeHandlersImpl(object source, System.Windows.RoutedEventArgs args, bool reRaised)
PresentationCore.dll!System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject sender, System.Windows.RoutedEventArgs args)
PresentationCore.dll!System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs args)
PresentationCore.dll!System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs args, bool trusted)
PresentationCore.dll!System.Windows.Input.InputManager.ProcessStagingArea()
PresentationCore.dll!System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs input)
PresentationCore.dll!System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport inputReport)
PresentationCore.dll!System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(System.IntPtr hwnd, System.Windows.Input.InputMode mode, int timestamp, System.Windows.Input.RawKeyboardActions actions, int scanCode, bool isExtendedKey, bool isSystemKey, int virtualKey)
PresentationCore.dll!System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(ref System.Windows.Interop.MSG msg, ref bool handled)
PresentationCore.dll!System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(ref System.Windows.Interop.MSG msg, System.Windows.Input.ModifierKeys modifiers)
PresentationCore.dll!System.Windows.Interop.HwndSource.OnPreprocessMessage(object param)
WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)
WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)
WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs)
WindowsBase.dll!System.Windows.Threading.Dispatcher.Invoke(System.Windows.Threading.DispatcherPriority priority, System.Delegate method, object arg)
PresentationCore.dll!System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(ref System.Windows.Interop.MSG msg, ref bool handled)
PresentationCore.dll!System.Windows.Interop.HwndSource.WeakEventPreprocessMessage.OnPreprocessMessage(ref System.Windows.Interop.MSG msg, ref bool handled)
WindowsBase.dll!System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(ref System.Windows.Interop.MSG msg)
Microsoft.VisualStudio.Platform.WindowManagement.dll!Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.PreTranslateInput(ref Microsoft.VisualStudio.OLE.Interop.MSG oleMsg, bool handled)

```

Comment (genlu) [reply src/EditorFeatures/Core/Implementation/Classification/SyntacticClassificationTaggerProvider.TagComputer.cs]: Also I just tried renaming a f# file to .cs in solution explorer, it indeed triggers the same crash. I suspect the same for documents in TypeScript project

**Comment by genlu** [comment]
@jasonmalinowski @heejaechang Could you please take a look at this? Thanks!

File: src/EditorFeatures/Core/Implementation/Classification/SyntacticClassificationTaggerProvider.TagComputer.cs (hunk 1 above)
Comment (genlu) [reply src/EditorFeatures/Core/Implementation/Classification/SyntacticClassificationTaggerProvider.TagComputer.cs]: @CyrusNajmabadi I have added some comments

File: src/VisualStudio/Xaml/Impl/Implementation/XamlTextViewCreationListener.cs [hunk 2]
```diff
@@ -161,7 +162,13 @@ private void OnDocumentMonikerChanged(IVsHierarchy hierarchy, string oldMoniker,
                 project.RemoveSourceFile(oldMoniker);
             }
 
-            project.AddSourceFile(newMoniker);
+            var info = _rdt.Value.GetDocumentInfo(docCookie);
+            var buffer = TryGetTextBufferFromDocData(info.DocData);
+
+            if (buffer != null && buffer.ContentType.IsOfType(ContentTypeNames.XamlContentType))
```
[the remark this answers is not in the document]
Comment (genlu) [reply src/VisualStudio/Xaml/Impl/Implementation/XamlTextViewCreationListener.cs]: I will take this as sign-off for Xaml related change :)

File: src/EditorFeatures/Core/Implementation/Classification/SyntacticClassificationTaggerProvider.TagComputer.cs (hunk 1 above)
Comment (heejaechang) [reply src/EditorFeatures/Core/Implementation/Classification/SyntacticClassificationTaggerProvider.TagComputer.cs]: problem is content type is editor concept and document is our concept. so, not sure how we coordinate these two when content type get changed.

Comment (heejaechang) [reply src/EditorFeatures/Core/Implementation/Classification/SyntacticClassificationTaggerProvider.TagComputer.cs]: one thing we could try would be
changing this "GetDocumentIdInCurrentContext".

most of time, this is the API we convert buffer to document. right now, it gets our buffer to document where we get our buffer from editor buffer through AsTextContainer().

we could add new API "GetDocumentIdInCurrentContext" that accepts editor buffer directly and in the API, it checks content type of the buffer to be same as language of the document we get out. if they are different, return null.

File: src/EditorFeatures/Core/Implementation/KeywordHighlighting/HighlightingService.cs [hunk 3]
```diff
@@ -27,11 +28,21 @@ internal class HighlightingService : IHighlightingService
...
              SyntaxNode root, int position, CancellationToken cancellationToken)
         {
-            return _highlighters.Where(h => h.Metadata.Language == root.Language)
-                               .Select(h => h.Value.GetHighlights(root, position, cancellationToken))
-                               .WhereNotNull()
-                               .Flatten()
-                               .Distinct();
+            try
+            {
+                return _highlighters.Where(h => h.Metadata.Language == root.Language)
```
Comment (heejaechang) [inline src/EditorFeatures/Core/Implementation/KeywordHighlighting/HighlightingService.cs]: this one was crashing because root was null. root is null since csharp document was under xaml document which has no syntaxtree so, we got null root here. and throw

File: src/VisualStudio/Xaml/Impl/Implementation/XamlTextViewCreationListener.cs [hunk 4]
```diff
@@ -161,7 +162,15 @@ private void OnDocumentMonikerChanged(IVsHierarchy hierarchy, string oldMoniker,
                 project.RemoveSourceFile(oldMoniker);
             }
 
-            project.AddSourceFile(newMoniker);
+            var info = _rdt.Value.GetDocumentInfo(docCookie);
```
Comment (heejaechang) [inline src/VisualStudio/Xaml/Impl/Implementation/XamlTextViewCreationListener.cs]: this I guess always called from Ui thread?

**Comment by genlu** [comment]
@heejaechang and I discussed this offline, I think his proposal makes perfect sense. Basically, we will:

1. Add a new workspace API (the original one is public, so can't change it), which check the content type of the buffer and throw NFW when mismatch.
```cs
public virtual DocumentId GetDocumentIdInCurrentContext(ITextBuffer buffer)
```

2. Convert all usage of the original API from code we own to this new one. So at least we would know where we screwed up. This won't help if there's some external components interacting with workspace through this API though.

3. Maybe eventually deprecate the original API?

@jasonmalinowski @CyrusNajmabadi thoughts?

**Comment by genlu** [comment]
Here's a comment from @jasonmalinowski offline:
> Looking at your "check the RDT and see if the content type is right", I'm worried that during rename scenarios you might still get the old content type. The editor will refresh, but with what ordering?

I will debug through editor code to see if this is something I can figure out.

File: src/VisualStudio/Xaml/Impl/Implementation/XamlTextViewCreationListener.cs (hunk 4 above)
Comment (genlu) [reply src/VisualStudio/Xaml/Impl/Implementation/XamlTextViewCreationListener.cs]: Since this is called through a RDT event, I'd think that's the case.

File: src/EditorFeatures/Core/Implementation/KeywordHighlighting/HighlightingService.cs [hunk 5]
```diff
@@ -27,11 +28,21 @@ internal class HighlightingService : IHighlightingService
...
+                                   .Select(h => h.Value.GetHighlights(root, position, cancellationToken))
+                                   .WhereNotNull()
+                                   .Flatten()
+                                   .Distinct();
+            }
+            catch (Exception e) when (FatalError.ReportWithoutCrashUnlessCanceled(e))
+            {
+                // https://devdiv.visualstudio.com/DevDiv/_workitems/edit/763988
+                // We still couldn't identify the root cause for the linked bug above.
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/KeywordHighlighting/HighlightingService.cs]: So why wouldn't we make a SupportSyntaxTree change like we did for the syntactic classifier earlier?

File: src/VisualStudio/Xaml/Impl/Implementation/XamlTextViewCreationListener.cs (hunk 4 above)
Comment (jasonmalinowski) [reply src/VisualStudio/Xaml/Impl/Implementation/XamlTextViewCreationListener.cs]: It is, yes.

File: src/EditorFeatures/Core/Implementation/KeywordHighlighting/HighlightingService.cs (hunk 5 above)
Comment (genlu) [reply src/EditorFeatures/Core/Implementation/KeywordHighlighting/HighlightingService.cs]: We can do that, but I 'd like to see if the fix I made in xaml project actually address the issue for xaml.

Comment (jasonmalinowski) [reply src/EditorFeatures/Core/Implementation/KeywordHighlighting/HighlightingService.cs]: Ah, so the intent is you want to see if this can be hit, and if so, we'd remove this because we've figured out the root cause?

Comment (genlu) [reply src/EditorFeatures/Core/Implementation/KeywordHighlighting/HighlightingService.cs]: Yup. Or if not, we can remove this after we have done what heejae proposed above.

Comment (jasonmalinowski) [reply src/EditorFeatures/Core/Implementation/KeywordHighlighting/HighlightingService.cs]: If that's the intent, the comment doesn't say that. It says we couldn't identify a root cause. :smile:

Comment (jasonmalinowski) [reply src/EditorFeatures/Core/Implementation/KeywordHighlighting/HighlightingService.cs]: I guess I don't see why we wouldn't apply the same SupportSyntaxTree check to the highlighting stuff as well, for consistency...

Comment (genlu) [reply src/EditorFeatures/Core/Implementation/KeywordHighlighting/HighlightingService.cs]: Well, you are probably right. If we are confident that enforcing content-type and document language in workspace would eliminate the root cause of the crash and will remove the NFW once it's done, then it doesn't really matter if we know the particular code path we fixed in XAML can be hit or not.

Comment (jasonmalinowski) [reply src/EditorFeatures/Core/Implementation/KeywordHighlighting/HighlightingService.cs]: Just to be clear all I'd say is we do two things:

1. Do the same SupportsSyntax check in the caller of this code like we did in the other place; until we do the larger API change that @heejaechang was thinking of, let's guard it in both places.
2. Change the comment in this NFW to say that we think the other fix does fix it, and if we don't see any further hits after a certain date we can just delete the NFW. Or leave the NFW in because we're saying as a general policy this feature isn't worth crashing the product over. But in that case, let's revise the comment to make it independent of the bug.

My biggest worry here is as the PR stands somebody looking at this code a few years from now won't be clear why the NFW is there, or why they can't delete if it the bug was indeed fixed.

Comment (mavasani) [reply src/EditorFeatures/Core/Implementation/KeywordHighlighting/HighlightingService.cs]: +1 - Agree with @jasonmalinowski.

Comment (genlu) [reply src/EditorFeatures/Core/Implementation/KeywordHighlighting/HighlightingService.cs]: If we added the SupportSyntax check in the caller, then the NFW wouldn't be needed at all.  I will do (1) you asked and add some comment there, then remove NFW

**Comment by genlu** [comment]
FYI I have filed #33439 based on @heejaechang's comment
