### PR TITLE
Fix #251: Preview Changes dialog always shows additional files as empty

### LINKED ISSUE #251: Preview Changes dialog always shows additional files as empty
Ported from TFS WorkItem: <b>1114841</b>

------------------------------

<p><b>Repro Steps:</b></p>
<B>Steps to reproduce:</B><BR><BR>1. Use InstallDogfood to install a recent build of Roslyn.</P>
<P>2. Open Roslyn.sln.</P>
<P>3. Open PublicAPI.txt in Workspaces.Desktop.</P>
<P>4. Delete the four lines at the top related to FileTextLoader.</P>
<P>5. Open FileTextLoader.cs. Note that squiggles appear under the four public types/members in this file.</P>
<P>6. Open the light bulb, and under "Add FileTextLoader to API" click "Preview Changes"</P>
<P>&nbsp;</P>
<P><STRONG>Expected</STRONG></P>
<P>The Preview Changes dialog opens, and when PublicAPI.txt is selected in the top pane, the bottom pane shows the file contents with the FileTextLoader APIs added back in.</P>
<P>&nbsp;</P>
<P><STRONG>Actual</STRONG></P>
<P>The bottom pane shows PublicAPI.txt as an empty file.</P>

------------------------------

<p><b>Revisions:</b></p>

1) Created By Tom Meschter (1/26/2015 11:01:13 AM)

If the errors or the fixer don't appear, make sure the build you've installed with InstallDogfood is compatible with the current toolset compilers/diagnostics.

------------------------------

### PR DESCRIPTION
**Pull request by mavasani**
Handle additional documents in Preview engine.
This exposed a bunch of NREs in some editor features and text extension methods that didn't account for additional documents being opened in the preview workspace, these have been fixed with appropriate null checks.

@tmeschter @shyamnamboodiripad @heejaechang can you please take a look?

### CODE REVIEW

File: src/EditorFeatures/Core/Shared/Tagging/TagProducers/AbstractSingleDocumentTagProducer.cs [hunk 1]
```diff
@@ -36,6 +37,10 @@ public Task<IEnumerable<ITagSpan<TTag>>> ProduceTagsAsync(IEnumerable<DocumentSn
 
             var snapshotSpan = snapshotSpans.Single().SnapshotSpan;
             var document = snapshotSpans.Single().Document;
+            if (document == null)
+            {
+                return Task.FromResult(SpecializedCollections.EmptyEnumerable<ITagSpan<TTag>>());
```
Comment (heejaechang) [inline src/EditorFeatures/Core/Shared/Tagging/TagProducers/AbstractSingleDocumentTagProducer.cs]: SpecializedTasks.EmptyEnumerable?

File: src/VisualStudio/Core/Def/Implementation/Preview/FileChange.cs [hunk 2]
```diff
@@ -30,6 +30,7 @@ internal class FileChange : AbstractChange
         private readonly ITextBuffer _buffer;
         private readonly Encoding _encoding;
         private readonly IVsImageService2 _imageService;
+        private readonly bool _isAddionalDocument;
```
Comment (heejaechang) [inline src/VisualStudio/Core/Def/Implementation/Preview/FileChange.cs]: this seem good one to use new readonly (getter only) property.

File: src/VisualStudio/Core/Def/Implementation/Preview/PreviewEngine.cs [hunk 3]
```diff
@@ -194,10 +194,10 @@ public int GetWarning(out string pbstrWarning, out int ppcwlWarningLevel)
         public void UpdatePreview(DocumentId documentId, SpanChange spanSource)
         {
             var updatedSolution = _topLevelChange.GetUpdatedSolution(applyingChanges: false);
-            var document = updatedSolution.GetDocument(documentId);
+            var document = updatedSolution.GetDocument(documentId) ?? updatedSolution.GetAdditionalDocument(documentId);
             if (document != null)
             {
-                _updater.UpdateView(document, spanSource);
+                _updater.UpdateView(document, spanSource, isAdditionalDocument: !(document is Document));
```
Comment (heejaechang) [inline src/VisualStudio/Core/Def/Implementation/Preview/PreviewEngine.cs]: is this flag needed? UpdateView should be able to check it itself since document is given.

also can we have extension method that is
 GetTextDocument(this solution, documentid) { 
return solution.GetDocument(documentId) ?? solution.GetAdditionalDocument(documentId) 
}

looks like useful one to have.

File: src/VisualStudio/Core/Def/Implementation/Preview/FileChange.cs [hunk 4]
```diff
@@ -44,6 +45,7 @@ internal class FileChange : AbstractChange
             _left = left;
             _right = right;
             _imageService = imageService;
+            _isAddionalDocument = !((left ?? right) is Document);
```
Comment (heejaechang) [inline src/VisualStudio/Core/Def/Implementation/Preview/FileChange.cs]: FileChange actually accepts TextDocument, is there a reason it can't handle additional document which should be text document?

also, assuming a document as an additional document just because it is not Document seems too fragile.

File: src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs [hunk 5]
```diff
@@ -35,14 +33,14 @@ public void CloseWorkspace()
             }
         }
 
-        public void UpdateView(Document document, SpanChange spanSource)
+        public void UpdateView(TextDocument document, SpanChange spanSource, bool isAdditionalDocument)
```
Comment (heejaechang) [inline src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs]: is isAdditionalDocument need to be passed down? whoever needs that flag should be able to get that info from document passed down I think.

File: src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs [hunk 6]
```diff
@@ -52,34 +50,65 @@ public void UpdateView(Document document, SpanChange spanSource)
...
             {
-                _previewWorkspace.CloseDocument(_currentDocument, _previewWorkspace.CurrentSolution.GetDocument(_currentDocument).GetTextAsync().Result);
-
-                // Put the new document into the current preview solution
-                var updatedSolution = _previewWorkspace.CurrentSolution.WithDocumentText(document.Id, document.GetTextAsync().Result);
-                var updatedDocument = updatedSolution.GetDocument(document.Id);
-
-                ApplyDocumentToBuffer(updatedDocument, spanSource, out container, out documentBackedByTextBuffer);
+                // Close the current document in preview solution.
+                if (_isCurrentAdditionalDocument)
```
Comment (heejaechang) [inline src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs]: both flags _isCurrentAdditionalDocument and isAdditionalDocument look like can be figured out by _currentDocument and document. 

since retrieving that information from the documents is not expensive. having less flag probably better I think.

also, it would be nice if there is a extension method that 
GetDocumentKind(TextDocument document)
{
if (document is Document)
{
return "SomeKindOfEnum?".Document;
}

// not sure whether there is a better way?
if (document.Solution.GetAdditionalDocument(document.Id) == document)
{
return "Additional..."
}

return "Text..."
}

File: src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs [hunk 7]
```diff
@@ -52,34 +50,65 @@ public void UpdateView(Document document, SpanChange spanSource)
...
+                else
+                {
+                    _previewWorkspace.CloseDocument(_currentDocument, _previewWorkspace.CurrentSolution.GetDocument(_currentDocument).GetTextAsync().Result);
+                }
+
+                // Put the new document into the current preview solution.
+                TextDocument updatedDocument;
+                if (isAdditionalDocument)
+                {
+                    var updatedSolution = _previewWorkspace.CurrentSolution.WithAdditionalDocumentText(document.Id, document.GetTextAsync().Result);
```
Comment (heejaechang) [inline src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs]: hmmm.. so assumption is this code only run on UI thread? but.. it not having cancellationtoken from wait dialog seems... weird.

File: src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs [hunk 8]
```diff
@@ -52,34 +50,65 @@ public void UpdateView(Document document, SpanChange spanSource)
...
+                {
+                    var updatedSolution = _previewWorkspace.CurrentSolution.WithDocumentText(document.Id, document.GetTextAsync().Result);
+                    updatedDocument = updatedSolution.GetDocument(document.Id);
+                }
+
+                ApplyDocumentToBuffer(updatedDocument, spanSource, isAdditionalDocument, out container, out documentBackedByTextBuffer);
 
                 _previewWorkspace.TryApplyChanges(documentBackedByTextBuffer.Project.Solution);
-                _previewWorkspace.OpenDocument(document.Id);
+                OpenDocument(document.Id, isAdditionalDocument);
```
Comment (heejaechang) [inline src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs]: can't workspace figture out whether given doucmentId is for additional document without the flag?

File: src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs [hunk 9]
```diff
@@ -52,34 +50,65 @@ public void UpdateView(Document document, SpanChange spanSource)
...
                 _currentDocument = document.Id;
             }
             else
             {
                 _currentDocument = document.Id;
 
-                ApplyDocumentToBuffer(document, spanSource, out container, out documentBackedByTextBuffer);
+                ApplyDocumentToBuffer(document, spanSource, isAdditionalDocument, out container, out documentBackedByTextBuffer);
```
Comment (heejaechang) [inline src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs]: same here. it would be nice if we can get rid of the flag.

File: src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs [hunk 10]
```diff
@@ -52,34 +50,65 @@ public void UpdateView(Document document, SpanChange spanSource)
...
 
                 _previewWorkspace = new PreviewDialogWorkspace(documentBackedByTextBuffer.Project.Solution);
-                _previewWorkspace.OpenDocument(document.Id);
+                OpenDocument(document.Id, isAdditionalDocument);
+            }
+
+            _isCurrentAdditionalDocument = isAdditionalDocument;
```
Comment (heejaechang) [inline src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs]: then, we don't need to do this kind of state management.

File: src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs [hunk 11]
```diff
@@ -52,34 +50,65 @@ public void UpdateView(Document document, SpanChange spanSource)
...
+        }
+
+        private void OpenDocument(DocumentId documentId, bool isAdditionalDocument)
+        {
+            if (isAdditionalDocument)
+            {
+                _previewWorkspace.OpenAdditionalDocument(documentId);
```
Comment (heejaechang) [inline src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs]: workspace should have enough information to see whether given documentId is additional document or not.

Comment (heejaechang) [inline src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs]: also... not sure why two has to be different API.. OpenAdditionalDocument and OpenDocument...

File: src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs [hunk 12]
```diff
@@ -96,7 +125,9 @@ private void ApplyDocumentToBuffer(Document document, SpanChange spanSource, out
             }
 
             container = TextView.TextBuffer.AsTextContainer();
-            documentBackedByTextBuffer = document.WithText(container.CurrentText);
+            documentBackedByTextBuffer = isAdditionalDocument ?
+                document.WithAdditionalDocumentText(container.CurrentText) :
+                document.WithText(container.CurrentText);
```
Comment (heejaechang) [inline src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs]: this seem can be avoided as well. what is hierarchy between additional and document/textdocument look like?

File: src/VisualStudio/Core/Def/Implementation/Preview/TopLevelChange.cs [hunk 13]
```diff
@@ -95,13 +98,17 @@ private Solution ApplyFileChanges(Solution solution, IEnumerable<FileChange> fil
                     if (applyingChanges && fileChange.CheckState == __PREVIEWCHANGESITEMCHECKSTATE.PCCS_Unchecked)
                     {
                         var oldText = oldDocument.GetTextAsync().Result.ToString();
-                        solution = solution.AddDocument(oldDocument.Id, oldDocument.Name, oldText, oldDocument.Folders, oldDocument.FilePath);
+                        solution = isAdditionalDoc ?
+                            solution.AddAdditionalDocument(oldDocument.Id, oldDocument.Name, oldText, oldDocument.Folders, oldDocument.FilePath) :
```
Comment (heejaechang) [inline src/VisualStudio/Core/Def/Implementation/Preview/TopLevelChange.cs]: this is unfortunate that we had to pass in string rather than sourcetext

**Comment by heejaechang** [comment]
I think it would be nice if we can get rid of those constant checking of two type of documents. is it something not solvable by type hierarchy and overrides?

File: src/EditorFeatures/Core/Implementation/ReferenceHighlighting/ReferenceHighlightingViewTaggerProvider.TagProducer.cs [hunk 14]
```diff
@@ -56,6 +56,10 @@ public void Dispose()
                 }
 
                 var document = snapshotSpans.First(vt => vt.SnapshotSpan.Snapshot == position.Snapshot).Document;
+                if (document == null)
+                {
+                    return SpecializedTasks.EmptyEnumerable<ITagSpan<AbstractNavigatableReferenceHighlightingTag>>();
+                }
```
Comment (tmeschter) [inline src/EditorFeatures/Core/Implementation/ReferenceHighlighting/ReferenceHighlightingViewTaggerProvider.TagProducer.cs]: I'm not clear on why this `NullReferenceException` happens in the first place. Can you provide some context?

**Comment by tmeschter** [comment]
The changes themselves look fine to me, though I agree with HeeJae that there's a larger issue here as well. It look like lots of our services operate on `Document` when they should really just operate on `TextDocument`, and we shouldn't really need to pass around a flag to distinguish between a code file and an additional file. I'm not sure what we can do about that without changing our APIs, however.

File: src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs (hunk 8 above)
Comment (mavasani) [inline src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs]: I'll open a new issue to ensure that workspace APIs based on DocumentId handle all text documents, not just source 'Document'.

File: src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs (hunk 11 above)
Comment (mavasani) [inline src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs]: I don't think we are going to change the API now, but at least OpenDocument should handle additional documents as user just passed DocumentId. I'll add this to a new issue I am about to file.

File: src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs (hunk 12 above)
Comment (mavasani) [inline src/VisualStudio/Core/Def/Implementation/Preview/PreviewUpdater.cs]: TextDocument is base type for all (source and non-source documents).
Document derives from TextDocument and represents all source documents.
AdditionalDocument: There is no strong type for additional document. It is basically a TextDocument that is not of type Document. Ideally, I would have preferred it to have a new type and TextDocument be abstract.

File: src/EditorFeatures/Core/Implementation/ReferenceHighlighting/ReferenceHighlightingViewTaggerProvider.TagProducer.cs (hunk 14 above)
Comment (mavasani) [inline src/EditorFeatures/Core/Implementation/ReferenceHighlighting/ReferenceHighlightingViewTaggerProvider.TagProducer.cs]: I saw an NRE here for null document, can't recall it was for additional document OR document removed from workspace. In fact, the constructor of DocumentSnapshotSpan says the Document could be null and we have a null check at all but 2 places, so making this consistent seems right.

**Comment by mavasani** [comment]
Filed #492 to track Workspace API issues.

**Comment by mavasani** [comment]
Merging the PR, I'll address any subsequent API related feedback after #492 has been addressed.

**Comment by heejaechang** [comment]
Hmmm.. once this in, it might hard to clean up….

I would rather create API first. Even if it is extension method ..


-          Heejae

**Comment by mavasani** [comment]
I did add extension methods wherever possible. The only places where I have retained the checks for source or additional document is in the preview workspace overrides.

**Comment by heejaechang** [comment]
yep, I saw that. goods good to me!
