### PR TITLE
Track local constant usage in attributes applied to local methods or lambdas

### LINKED ISSUE #47619: Constant used in attribute on local function warns that it is unused
**Version Used**: Compiler version: '3.8.0-4.20460.4 (64f2392e)'. Language version: 9.0.

**Steps to Reproduce**:

Compile the following code: ([SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEAMACFBGAdAJQFcA7GASzDlwElTEB7ABwGVEA3MgYzigG4BYAFBCUAZiwAmDABUeMIQG8hGFVnEoALDLkBZODAAW9ACYAKAJTLVSwarsZO9YrCzZMxgDYeAchEoYAXgwAIllYXE8PYIFbexUrOIBtABEvajBGegQYU0jfSnMAXQT7HAA2DDgAD3gEYiwtX3I2OBQAVnInCxi4+Ni4prIW9s7ibpKAXyEJoA==))

```csharp
using System.Runtime.InteropServices;

public class Test
{
    public void TestMethod()
    {
        const string dllName = "Test.dll";
        
        [DllImport(dllName)]
        static extern void NativeFunction();
        
        NativeFunction();
    }
}
```

**Expected Behavior**: No warnings or errors.

**Actual Behavior**:

The compiler warns that `dllName` is not used:

```
warning CS0219: The variable 'dllName' is assigned but its value is never used
```

### LINKED ISSUE #60645: Incorrect 'The variable 'X' is assigned but its value is never used' when constant is used in attribute of local function
I don't think the warning makes sense here:

```csharp
public class C
{
    public int P
    {
        get
        {
            // warning CS0219: The variable 'X' is assigned but its value is never used
            const int X = 5;
            return local1();

            [My(X)]
            int local1() => 0;
        }
    }
}

public class MyAttribute : System.Attribute
{
    public MyAttribute(int i) { }
}
```

Lambda attributes have the same bug too:

```csharp
public class C
{
    public int P
    {
        get
        {
            // warning CS0219: The variable 'X' is assigned but its value is never used
            const int X = 5;
            var f = [My(X)] () => 0;
            return f();
        }
    }
}

public class MyAttribute : System.Attribute
{
    public MyAttribute(int i) { }
}
```

### PR DESCRIPTION
**Pull request by jjonescz**
Follow up on #64660 which fixed similar issue for attributes applied to method/lamba parameters only, i.e.,
```cs
void lam = ([Attr(constant)] int x) => { };
```
whereas this PR fixes the same for attributes applied to whole methods/lambdas, i.e.,
```cs
void lam = [Attr(constant)] (int x) => { };
```

Fixes [AB#1614551](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1614551)
Fixes #60645
Fixes #47619
Closes #62158

### CODE REVIEW

**Review by Youssef1313 — COMMENTED** [review]
Consider making sure that all tests I had in https://github.com/dotnet/roslyn/pull/62158 are passing (and if any test contains a currently untested scenario, you can port it)

After that, we can close https://github.com/dotnet/roslyn/pull/62158

**Comment by Youssef1313** [comment]
You could also mark the issues linked in https://github.com/dotnet/roslyn/pull/62158 as fixed in this PR (after confirming the exact test cases are indeed fixed)

**Comment by jjonescz** [comment]
Thanks @Youssef1313. I wasn't aware of your PR and those issues, will look into it.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs [hunk 1]
```diff
@@ -2126,6 +2140,12 @@ public override BoundNode VisitLambda(BoundLambda node)
             var oldSymbol = this.CurrentSymbol;
             this.CurrentSymbol = node.Symbol;
 
+            // Mark attribute arguments as used.
+            if (node.Symbol.BindMethodAttributes() is { IsDefaultOrEmpty: false } boundAttributes)
```
Comment (Youssef1313) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs:2144]: This does binding during flow analysis, which is something @RikkiGibson was concerned about. See https://github.com/dotnet/roslyn/pull/62158#discussion_r917129834

**Review by Youssef1313 — COMMENTED** [review]
I'm not sure whether @adamperlin has fixed something in this area or not. So it's also worth looking into what behavior we have in the `lambda-default-parameters` branch

File: src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs (hunk 1 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs:2144]: I see, although this was accepted for [default lambda parameters](https://github.com/dotnet/roslyn/pull/63850/files#diff-c1fe10ac125bdb06ceee8d34353277788c8751b28a729cd3d5ce55e8deb8c91bR1690) and [parameter attributes](https://github.com/dotnet/roslyn/pull/64660/files#diff-c1fe10ac125bdb06ceee8d34353277788c8751b28a729cd3d5ce55e8deb8c91bR1690).

**Comment by jjonescz** [comment]
> it's also worth looking into what behavior we have in the `lambda-default-parameters` branch

There it's implemented only for lambda default parameters. See #63850.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs:2150]: Yeah, I think at this point we agree that as long as it doesn't present a performance issue, it is not a serious problem to re-bind something which may already be bound somewhere else. Thanks!

**Review by 333fred — APPROVED** [review]
@dotnet/roslyn-compiler for a second review.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs [hunk 2]
```diff
@@ -1690,16 +1690,30 @@ protected override void EnterParameter(ParameterSymbol parameter)
...
+                VisitAttributes(boundAttributes);
+            }
+        }
+
+        /// <summary>
+        /// Marks attribute arguments as used.
+        /// </summary>
+        private void VisitAttributes(ImmutableArray<(CSharpAttributeData, BoundAttribute)> boundAttributes)
+        {
+            foreach (var (attributeData, boundAttribute) in boundAttributes)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs:1702]: nit: might it make sense to move the check for `IsDefault` here, so that the `{ IsDefaultOrEmpty: false }` checks below could be factored away?

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs [hunk 3]
```diff
@@ -362,6 +362,15 @@ internal override (CSharpAttributeData?, BoundAttribute?) EarlyDecodeWellKnownAt
...
             return base.EarlyDecodeWellKnownAttribute(ref arguments);
         }
+
+        /// <summary>
+        /// Binds attributes applied to this method.
+        /// </summary>
+        public ImmutableArray<(CSharpAttributeData, BoundAttribute)> BindMethodAttributes()
+        {
+            Debug.Assert(OuterBinder is not null);
+            return BindAttributes(GetAttributeDeclarations(), OuterBinder);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs:372]: >OuterBinder [](http://example.com/codeflow?start=62&length=11)

Why are we using `OuterBinder` rather than `WithTypeParametersBinder` here?

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs [hunk 4]
```diff
@@ -575,25 +575,9 @@ internal sealed override CustomAttributesBag<CSharpAttributeData> GetAttributesB
...
-                        var boundType = binder.BindType(attributeSyntax.Name, BindingDiagnosticBag.Discarded);
-                        var boundTypeSymbol = (NamedTypeSymbol)boundType.Type;
-                        var boundAttribute = new ExecutableCodeBinder(attributeSyntax, binder.ContainingMemberOrLambda, binder)
-                            .BindAttribute(attributeSyntax, boundTypeSymbol, this, BindingDiagnosticBag.Discarded);
-                        boundAttributeArrayBuilder.Add(boundAttribute);
-                    }
-                }
-            }
-            return boundAttributeArrayBuilder.ToImmutableAndFree();
+            return BindAttributes(GetAttributeDeclarations(), WithTypeParametersBinderOpt);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs:580]: >WithTypeParametersBinderOpt [](http://example.com/codeflow?start=62&length=27)

I'm wondering about old code. What's a scenario where `WithTypeParametersBinderOpt` would be null?
If this is reachable, then the parameter should be marked as nullable in `BindAttributes`.

File: src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs [hunk 5]
```diff
@@ -517,6 +517,30 @@ static bool isObsoleteDiagnostic(DiagnosticWithInfo d)
...
+            var boundAttributeArrayBuilder = ArrayBuilder<(CSharpAttributeData, BoundAttribute)>.GetInstance();
+            foreach (var attributeListSyntaxList in attributeDeclarations)
+            {
+                foreach (var attributeListSyntax in attributeListSyntaxList)
+                {
+                    foreach (var attributeSyntax in attributeListSyntax.Attributes)
+                    {
+                        var boundType = binder.BindType(attributeSyntax.Name, BindingDiagnosticBag.Discarded);
+                        var boundTypeSymbol = (NamedTypeSymbol)boundType.Type;
+                        var boundAttribute = binder.GetAttribute(attributeSyntax, boundTypeSymbol,
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs:536]: >binder [](http://example.com/codeflow?start=45&length=6)

The previous logic (from `SourceComplexParameterSymbol.BindParameterAttributes`) had 
```
var boundAttribute = new ExecutableCodeBinder(attributeSyntax, binder.ContainingMemberOrLambda, binder)
                            .BindAttribute(attributeSyntax, boundTypeSymbol, this, BindingDiagnosticBag.Discarded);
```

What's the impact/intent of this change?

File: src/Compilers/CSharp/Test/Emit2/FlowAnalysis/FlowTests.cs [hunk 6]
```diff
@@ -5635,12 +5647,138 @@ class Program
...
+                {
+                    static void Main()
+                    {
+                        const int N1 = 10;
+                        const int N2 = 20;
+                        const int N3 = 30;
+                        const int N4 = 40;
+                        const int N5 = 50;
+                        const int N6 = 60;
+                        [A(N1, Prop = N2)][return: A(N3, Prop = N4)] int F() => N5;
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit2/FlowAnalysis/FlowTests.cs:5682]: Although this PR is focusing on attributes on the lambda/local function, consider adding similar tests for parameters of lambdas/local functions.

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 5)

File: src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs (hunk 5 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs:536]: Good catch, I forgot to explain. `binder.GetAttribute(...)` internally calls `new ExecutableCodeBinder(attributeSyntax, binder.ContainingMemberOrLambda, binder).BindAttribute(...)` which I noticed here and simplified the code.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs (hunk 3 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs:372]: That's what's used in `GetAttributesBag`, I'm just trying to be consistent.

https://github.com/dotnet/roslyn/blob/a7f80599c74692d58c41eaf9998488387dcac63a/src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs#L286

File: src/Compilers/CSharp/Test/Emit2/FlowAnalysis/FlowTests.cs (hunk 6 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Test/Emit2/FlowAnalysis/FlowTests.cs:5682]: Such tests were already added in the previous PR:

https://github.com/dotnet/roslyn/pull/64660/files#diff-fc05250f65f4e4fed831dc87cf19115cf1a315d3bfc07d47fa1300a4864fc769

File: src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs (hunk 2 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs:1706]: Good catch, thanks. 199920676bedcc3ac63467eda2c7974cfe74585d

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs (hunk 4 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs:580]: Not sure when it can be `null`, but I can do the same thing as `GetAttributesBag` does when binding attributes: 7c19b43548cec1368c4eb803e92b0fd94e56fa78

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs (hunk 3 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs:371]: Is there a test that will fail if someone (in future) changed `OuterBinder` to `WithTypeParametersBinder` in this code path?

What if the generic parameter is used inside `nameof(..)` which is allowed?

I think constants usage in attributes should be consistent with the following existing behavior

```csharp
using System;
public class C
{
    public void M()
    {
        // no compiler warning
        const int X = 5;
        Console.WriteLine(nameof(X));
        
        // warning CS0219: The variable 'Y' is assigned but its value is never used
        const int Y = 6;
    }
}
```

ie, `[MyAttr(nameof(UnusedConstant))]` shouldn't give a warning

Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs:371]: > Is there a test that will fail if someone (in future) changed `OuterBinder` to `WithTypeParametersBinder` in this code path?

No, but I can add one: dba8ea61d7a2d521225f107712c41aa3d932ddc1. It fails whenever `OuterBinder` is changed to `WithTypeParametersBinder` in either (or both) of the code paths.

> What if the generic parameter is used inside `nameof(..)` which is allowed?

That actually works even with the `OuterBinder` (not sure why, but it binds properly; although I think it's not possible to test it with the usage analysis).

Comment (jcouv) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbolWithAttributes.cs:371]: Thanks. Adding such a test would be good.
Yes, the special behavior inside nameof is expected (this was a C# 11 feature). Thanks for clarifying.

File: src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs (hunk 5 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs:536]: Thanks for the clarification.

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 9)

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs (hunk 4 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs:580]: OK, seems that `SourceComplexParameterSymbolBase.WithTypeParameterOpt == null` happens for parameters of `SourcePropertySymbol`. But `SourceMethodSymbolWithAttributes.OuterBinder == null` never happens as all current implementations provide non-`null` binder (although the abstract property type is nullable).

For the former case, I added an explicit test of the `BindParameterAttributes()` method to verify it behaves correctly when `WithTypeParameterOpt == null`: 1892e8cca890f5f4d8299578cb1518619758a3a6. This is not a normal integration test as I don't think this can be hit directly though definite assignment analysis. Also not sure this is the correct place for the test.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 10)

**Comment by jjonescz** [comment]
@333fred @dotnet/roslyn-compiler for a second review.

**Review by 333fred — APPROVED** [review]
