### PR TITLE
Remove at most 1 end of line preceding redundant nullable directives

### LINKED ISSUE #63163: `IDE0240` codefix leaves redundunt blank line
**Version Used**:
VS 2022 v17.3 Preview 6

**Steps to Reproduce**:
1) Create new console app, it will contain `<Nullable>enable</Nullable>` in a `.csproj` file by default
2) Add this code to `Program.cs`:
```cs
using System;

#nullable enable

namespace MyNamespace;

class MyClass
{

}
```
3) Invoke codefix of `IDE0240` on `#nullable enable`

**Expected Behavior**:
```cs
using System;

namespace MyNamespace;

class MyClass
{

}
```

**Actual Behavior**:
```cs
using System;


namespace MyNamespace;

class MyClass
{

}
```
_Note that there are 2 blank lines between `using System;` and `
namespace MyNamespace;`_

### PR DESCRIPTION
**Pull request by sdelarosbil**
Closes #63163

This pr changes the way the redudant directive is removed by checking the trivias preceding them. All of the whitespaces ones are removed until an end of line trivia is found. This means at most, this will delete a blank like preceding the directive which removes a potential blank line.

I added a test, but I needed to change 2 tests to fit the changes. The new algorithm first groups the nodes by their directive nodes which allows to go through each of their parent's childs and perform their removal. This is done on a per node basis so cases where there's multiple directives in a row are batched together.

I am not too sure about the complexity of this and it might be because there's some node apis I wasn't aware of that would have made this simpler, but I at least wanted to present a working solution in case it could be simplified.

### CODE REVIEW

**Comment by sdelarosbil** [comment]
Hey, this is still ready for review, I am not sure why the vs integration tests are failing, seems to be a timeout?

File: src/Analyzers/CSharp/CodeFixes/RemoveUnnecessaryNullableDirective/CSharpRemoveUnnecessaryNullableDirectiveCodeFixProvider.cs [hunk 1]
```diff
@@ -53,10 +57,46 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
             CodeActionOptionsProvider fallbackOptions,
             CancellationToken cancellationToken)
         {
-            foreach (var diagnostic in diagnostics)
+            var nullableDirectivesByNodes = diagnostics.GroupBy(x =>
+                x.Location.FindNode(findInsideTrivia: false, getInnermostNodeForTie: false, cancellationToken), x =>
+                x.Location.FindNode(findInsideTrivia: true, getInnermostNodeForTie: true, cancellationToken))
+                .ToDictionary(x => x.Key, x => x.ToList());
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/CodeFixes/RemoveUnnecessaryNullableDirective/CSharpRemoveUnnecessaryNullableDirectiveCodeFixProvider.cs:63]: what is thsi code for.  this needs docs.

File: src/Analyzers/CSharp/CodeFixes/RemoveUnnecessaryNullableDirective/CSharpRemoveUnnecessaryNullableDirectiveCodeFixProvider.cs [hunk 2]
```diff
@@ -53,10 +57,46 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
+                {
+                    foreach (var nullableDirective in nullableDirectives)
+                        editor.RemoveNode(nullableDirective, SyntaxRemoveOptions.KeepNoTrivia);
+                    continue;
+                }
+
+                var leadingTrivia = node.GetLeadingTrivia();
+                var indexes = nullableDirectives.Select(x => leadingTrivia.IndexOf(x.ParentTrivia))
+                                                .OrderByDescending(x => x).ToArray();
+                foreach (var index in indexes)
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/CodeFixes/RemoveUnnecessaryNullableDirective/CSharpRemoveUnnecessaryNullableDirectiveCodeFixProvider.cs:77]: i really don't understand the logic here.  including what the above indices are representing, or waht the loop below is doing.  this all needs examples.

File: src/Analyzers/CSharp/CodeFixes/RemoveUnnecessaryNullableDirective/CSharpRemoveUnnecessaryNullableDirectiveCodeFixProvider.cs [hunk 3]
```diff
@@ -53,10 +57,46 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
+                            leadingTrivia = leadingTrivia.RemoveAt(i);
+                            break;
+                        }
+                        if (leadingTrivia[i].IsWhitespace())
+                        {
+                            leadingTrivia = leadingTrivia.RemoveAt(i);
+                        }
+                        i--;
+                    }
+                }
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/CodeFixes/RemoveUnnecessaryNullableDirective/CSharpRemoveUnnecessaryNullableDirectiveCodeFixProvider.cs:95]: it's unclear why it's not sufficient to just remove all the trivia that precedes the nullable directive that is whitespace or endofline.

File: src/Analyzers/CSharp/Tests/RemoveUnnecessaryNullableDirective/CSharpRemoveRedundantNullableDirectiveTests.cs [hunk 4]
```diff
@@ -182,13 +182,41 @@ class Program
...
+        public async Task TestRedundantDirectiveBetweenUsingAndNamespace()
+        {
+            await VerifyCodeFixAsync(
+                NullableContextOptions.Enable,
+                """
+                using System;
+                
+                [|#nullable enable|]
+
+                namespace MyNamespace
```
Comment (sharwell) [inline src/Analyzers/CSharp/Tests/RemoveUnnecessaryNullableDirective/CSharpRemoveRedundantNullableDirectiveTests.cs:201]: 💡 Also would be good to have tests with the following. Each of these two cases should result in a single blank line appearing after the refactoring.

```
using System;
#nullable enable

namespace MyNamespace
{
}
```

```
using System;

#nullable enable
namespace MyNamespace
{
}
```

Comment (sdelarosbil) [reply src/Analyzers/CSharp/Tests/RemoveUnnecessaryNullableDirective/CSharpRemoveRedundantNullableDirectiveTests.cs:201]: Done, had to handle the second one as I wasn't doing that

File: src/Analyzers/CSharp/CodeFixes/RemoveUnnecessaryNullableDirective/CSharpRemoveUnnecessaryNullableDirectiveCodeFixProvider.cs (hunk 3 above)
Comment (sdelarosbil) [reply src/Analyzers/CSharp/CodeFixes/RemoveUnnecessaryNullableDirective/CSharpRemoveUnnecessaryNullableDirectiveCodeFixProvider.cs:123]: It would remove more lines than desired if you removed all of them like if we had 2 blank lines before. This is why I remove at most one preceding line

File: src/Analyzers/CSharp/CodeFixes/RemoveUnnecessaryNullableDirective/CSharpRemoveUnnecessaryNullableDirectiveCodeFixProvider.cs (hunk 2 above)
Comment (sdelarosbil) [reply src/Analyzers/CSharp/CodeFixes/RemoveUnnecessaryNullableDirective/CSharpRemoveUnnecessaryNullableDirectiveCodeFixProvider.cs:93]: Added comments, does it help?

File: src/Analyzers/CSharp/CodeFixes/RemoveUnnecessaryNullableDirective/CSharpRemoveUnnecessaryNullableDirectiveCodeFixProvider.cs (hunk 1 above)
Comment (sdelarosbil) [reply src/Analyzers/CSharp/CodeFixes/RemoveUnnecessaryNullableDirective/CSharpRemoveUnnecessaryNullableDirectiveCodeFixProvider.cs:65]: Added comments.

File: src/Analyzers/CSharp/CodeFixes/RemoveUnnecessaryNullableDirective/CSharpRemoveUnnecessaryNullableDirectiveCodeFixProvider.cs [hunk 5]
```diff
@@ -53,10 +57,76 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
             CodeActionOptionsProvider fallbackOptions,
             CancellationToken cancellationToken)
         {
-            foreach (var diagnostic in diagnostics)
+            // We first group the nullable directives by the syntax node they are attached
+            // This allows to replace each node separately even if they have multiple nullable directives
+            var nullableDirectivesByNodes = diagnostics.GroupBy(x =>
+                x.Location.FindNode(findInsideTrivia: false, getInnermostNodeForTie: false, cancellationToken), x =>
+                x.Location.FindNode(findInsideTrivia: true, getInnermostNodeForTie: true, cancellationToken))
+                .ToDictionary(x => x.Key, x => x.ToList());
```
Comment (sharwell) [inline src/Analyzers/CSharp/CodeFixes/RemoveUnnecessaryNullableDirective/CSharpRemoveUnnecessaryNullableDirectiveCodeFixProvider.cs:65]:
```suggestion
            var nullableDirectivesByNodes = diagnostics
                .GroupBy(
                    x => x.Location.FindNode(findInsideTrivia: false, getInnermostNodeForTie: false, cancellationToken),
                    x => x.Location.FindNode(findInsideTrivia: true, getInnermostNodeForTie: true, cancellationToken))
                .ToDictionary(x => x.Key, x => x.ToList());
```

**Review by sharwell — APPROVED** [review]

File: src/Analyzers/CSharp/CodeFixes/RemoveUnnecessaryNullableDirective/CSharpRemoveUnnecessaryNullableDirectiveCodeFixProvider.cs (hunk 3 above)
Comment (CyrusNajmabadi) [reply src/Analyzers/CSharp/CodeFixes/RemoveUnnecessaryNullableDirective/CSharpRemoveUnnecessaryNullableDirectiveCodeFixProvider.cs:124]: so, basically, i see this as having a much simpler solution.

check the directive.  we're looking to see if there's a blank line above it, and a blank line below it.

if there is both, then we want to simply remove one of those blank lines.  that seems to be it afaict.  if there are no blank lines we don't need to do anything.  and if htere is just a blank line above *or* a blank line below (but not both) we don't need to do anything either.

the code seems very overwrought to accomplish this.

Comment (sdelarosbil) [reply src/Analyzers/CSharp/CodeFixes/RemoveUnnecessaryNullableDirective/CSharpRemoveUnnecessaryNullableDirectiveCodeFixProvider.cs:124]: I agree it seemed weird to me, but I couldn't find an easier to get the preceding trivia or the following one.

Maybe there was an api or method of traversal I wasn't aware of?

**Comment by sdelarosbil** [comment]
> @sdelarosbil do you mind if i push to your repo? if not, i can push to another branch where i show what i mean :)

you can push to this branch, sure

I understand the idea, it's more I think I might miss how to easilly get the trivias relative to the directives that I have a bit of an issue.

**Comment by CyrusNajmabadi** [comment]
Ok.  Pushed :)

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by sdelarosbil** [comment]
Oh, I see, yeah now I understand more how you do this now.

Thanks!
