### PR TITLE
Fixed Inline Temporary Variable refactoring

### LINKED ISSUE #16819: Inline Temporary Variable adds duplicate cast
**Version Used**: 15.0.0-RC.3+26127.0

```C#
var o = (Exception)null;
Console.Write(o == new Exception());
```

The Inline Temporary Variable refactoring produces

```C#
Console.Write((Exception)(Exception)null == new Exception());
```

### PR DESCRIPTION
**Pull request by zaytsev-victor**
**Customer scenario**
Inline Temporary Variable adds duplicate cast

**Bugs this fixes:**
Fixes #16819

**Risk**
Low

**Performance impact**
Low

**Is this a regression from a previous update?**
No

**How was the bug found?**
customer reported

### CODE REVIEW

**Comment by dpoeschl** [comment]
retest windows_release_vs-integration_prtest please

**Comment by dpoeschl** [comment]
retest windows_debug_unit64_prtest please

**Comment by Pilchie** [comment]
Ping @dotnet/roslyn-ide for reviews on this community PR.

**Comment by CyrusNajmabadi** [comment]
I'm not certain if this is the best way to handle things.  I think it's fine for the cast to be inserted even for an already casted expression.  For example, the helper may be used in a way that ends up with something like ```(T)(object)something```.  So i would instead expect the simplification code to remove one of the two casts.  (And, in this code example, remove both casts).

**Comment by DustinCampbell** [comment]
Yes, @CyrusNajmabadi is right. This is definitely the wrong fix and will introduce other bugs. At the very least, the check to determine whether a cast should be added should check that the target type and the type of the casted expression are the same.

In reality, the bug should be fixed in the simplification engine. The fact that an identity cast is not removed is definitely fishy.

File: src/EditorFeatures/CSharpTest/CodeActions/InlineTemporary/InlineTemporaryTests.cs [hunk 1]
```diff
@@ -4564,6 +4564,32 @@ bool M<T>(ref T x)
...
+
+class C
+{
+    void M()
+    {
+        Console.Write((Exception)null == new Exception());
+    }
+}");
+        }
+
```
Comment (DustinCampbell) [inline src/EditorFeatures/CSharpTest/CodeActions/InlineTemporary/InlineTemporaryTests.cs]: This should probably go at the end of the file rather than between two tests that are related to one another (`InlineTemporary_RefParams` and `InlineTemporary_OutParams`).

File: src/Workspaces/CSharp/Portable/Extensions/ExpressionSyntaxExtensions.cs [hunk 2]
```diff
@@ -84,7 +84,7 @@ public static ExpressionSyntax Parenthesize(this ExpressionSyntax expression, bo
             int position,
             SemanticModel semanticModel)
         {
-            if (targetType.ContainsAnonymousType())
+            if (targetType.ContainsAnonymousType() || expression.Kind() == SyntaxKind.CastExpression)
```
Comment (DustinCampbell) [inline src/Workspaces/CSharp/Portable/Extensions/ExpressionSyntaxExtensions.cs]: This syntactic check is wrong. Note that this means that this method would stop adding casts to *any* type. For example, it would no longer be able to cast `(B)c` to `(A)(B)c`.

**Comment by DustinCampbell** [comment]
FWIW, the problem is here: http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Extensions/CastExpressionSyntaxExtensions.cs,380

```C#
// Simple case: If the conversion from the inner expression to the cast type is identity,
// the cast can be removed.
if (expressionToCastType.IsIdentity)
{
    // Required explicit cast for reference comparison.
    // Cast removal causes warning CS0252 (Possible unintended reference comparison).
    //      object x = string.Intern("Hi!");
    //      (object)x == "Hi!"
    if (IsRequiredCastForReferenceEqualityComparison(outerType, cast, semanticModel, out var other))
    {
        var otherToOuterType = semanticModel.ClassifyConversion(other, outerType);
        if (otherToOuterType.IsImplicit && otherToOuterType.IsReference)
        {
            return false;
        }
    }

    return true;
}
```

The problem is that this is on the left side of an equality comparison and there's a special case that's been added there which is incorrect.

**Comment by DustinCampbell** [comment]
Yeah, `IsRequiredCastForReferenceEqualityComparison` is super-wrong. The warning scenario that it's testing for is specific to equality comparison (CS0252 and CS0253). Here's where those warnings are added in the compiler for reference: http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Lowering/DiagnosticsPass_Warnings.cs,304.

**Comment by DustinCampbell** [comment]
OK. While I'd like to see `IsRequiredCastForReferenceEqualityComparison` rewritten, there's a simpler fix that address this particular problem:. Just update [CastExpressionSyntaxExtensions.IsUnnecessaryCast(...)](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Extensions/CastExpressionSyntaxExtensions.cs,ceefcfb31aea482e) to introduce a new clause at line 376 like so:

```C#
// Simple case: If the conversion from the inner expression to the cast type is identity,
// the cast can be removed.
if (expressionToCastType.IsIdentity)
{
    // Simple case: Is this an identity cast to another cast? If so, we're safe to remove it.
    if (cast.Expression.WalkDownParentheses().IsKind(SyntaxKind.CastExpression))
    {
        return true;
    }

    // Required explicit cast for reference comparison.
    // Cast removal causes warning CS0252 (Possible unintended reference comparison).
    //      object x = string.Intern("Hi!");
    //      (object)x == "Hi!"
    if (IsRequiredCastForReferenceEqualityComparison(outerType, cast, semanticModel, out var other))
    {
        var otherToOuterType = semanticModel.ClassifyConversion(other, outerType);
        if (otherToOuterType.IsImplicit && otherToOuterType.IsReference)
        {
            return false;
        }
    }

    return true;
}
```

That should do the trick.

**Comment by sharwell** [comment]
@dotnet-bot retest this please

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by sharwell** [comment]
@zaytsev-victor I'll go ahead and move the test so we can merge this!

**Comment by sharwell** [comment]
@MattGertz for belated ask mode (forgot the switchover)

**Comment by Pilchie** [comment]
I've approved - and can do ask mode approvals for IDE/project/analyzers.
