### PR TITLE
Dont fail format on MAS with Tabs on

### LINKED ISSUE #4019: Metadata as Source completely breaks with tab indentation
Running the RTM build:

MAS completely fails on [`Microsoft.VisualStudio.Settings.SettingsStore`](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.settings.settingsstore).

F12 shows an AggregateException message in a dialog.  Peek just hangs.  Attaching a debugger shows an ArgumentOutRange complaining the `start` is less than `end` from the following stack:

```
>	Microsoft.CodeAnalysis.Text.TextSpan.FromBounds(int start, int end)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Formatting.TriviaDataFactory.ComplexTrivia.ShouldFormat(Microsoft.CodeAnalysis.Formatting.FormattingContext context)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Formatting.TriviaDataFactory.ComplexTrivia.Format(Microsoft.CodeAnalysis.Formatting.FormattingContext context, Microsoft.CodeAnalysis.Formatting.ChainedFormattingRules formattingRules, System.Action<int, Microsoft.CodeAnalysis.Formatting.TriviaData> formattingResultApplier, System.Threading.CancellationToken cancellationToken, int tokenPairIndex)	Unknown
 	Microsoft.CodeAnalysis.Formatting.AbstractFormatEngine.ApplyEndOfTreeTriviaOperation(Microsoft.CodeAnalysis.Formatting.FormattingContext context, Microsoft.CodeAnalysis.Formatting.TokenStream tokenStream, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Formatting.AbstractFormatEngine.Format(System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Formatting.CSharpStructuredTriviaFormatEngine.Format(Microsoft.CodeAnalysis.SyntaxTrivia trivia, int initialColumn, Microsoft.CodeAnalysis.Options.OptionSet optionSet, Microsoft.CodeAnalysis.Formatting.ChainedFormattingRules formattingRules, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Formatting.CSharpTriviaFormatter.FormatStructuredTrivia(Microsoft.CodeAnalysis.Formatting.LineColumn lineColumn, Microsoft.CodeAnalysis.SyntaxTrivia trivia, System.Collections.Generic.List<Microsoft.CodeAnalysis.Text.TextChange> changes, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Formatting.CSharpTriviaFormatter.Format(Microsoft.CodeAnalysis.Formatting.LineColumn lineColumn, Microsoft.CodeAnalysis.SyntaxTrivia commonTrivia, System.Collections.Generic.List<Microsoft.CodeAnalysis.Text.TextChange> changes, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Formatting.AbstractTriviaFormatter<Microsoft.CodeAnalysis.SyntaxTrivia>.FormatFirstTriviaAndWhitespaceAfter<Microsoft.CodeAnalysis.Text.TextChange>(Microsoft.CodeAnalysis.Formatting.LineColumn lineColumnBeforeTrivia1, Microsoft.CodeAnalysis.SyntaxTrivia trivia1, Microsoft.CodeAnalysis.Formatting.LineColumnDelta existingWhitespaceBetween, Microsoft.CodeAnalysis.SyntaxTrivia trivia2, Microsoft.CodeAnalysis.Formatting.AbstractTriviaFormatter<Microsoft.CodeAnalysis.SyntaxTrivia>.Formatter<Microsoft.CodeAnalysis.Text.TextChange> format, Microsoft.CodeAnalysis.Formatting.AbstractTriviaFormatter<Microsoft.CodeAnalysis.SyntaxTrivia>.WhitespaceAppender<Microsoft.CodeAnalysis.Text.TextChange> addWhitespaceTrivia, System.Collections.Generic.List<Microsoft.CodeAnalysis.Text.TextChange> changes, bool implicitLineBreak, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Formatting.AbstractTriviaFormatter<Microsoft.CodeAnalysis.SyntaxTrivia>.FormatTrivia<Microsoft.CodeAnalysis.Text.TextChange>(Microsoft.CodeAnalysis.Formatting.AbstractTriviaFormatter<Microsoft.CodeAnalysis.SyntaxTrivia>.Formatter<Microsoft.CodeAnalysis.Text.TextChange> formatter, Microsoft.CodeAnalysis.Formatting.AbstractTriviaFormatter<Microsoft.CodeAnalysis.SyntaxTrivia>.WhitespaceAppender<Microsoft.CodeAnalysis.Text.TextChange> whitespaceAdder, System.Collections.Generic.List<Microsoft.CodeAnalysis.Text.TextChange> changes, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Formatting.AbstractTriviaFormatter<Microsoft.CodeAnalysis.SyntaxTrivia>.FormatToTextChanges(System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Formatting.TriviaDataFactory.FormattedComplexTrivia.FormattedComplexTrivia(Microsoft.CodeAnalysis.Formatting.FormattingContext context, Microsoft.CodeAnalysis.Formatting.ChainedFormattingRules formattingRules, Microsoft.CodeAnalysis.SyntaxToken token1, Microsoft.CodeAnalysis.SyntaxToken token2, int lineBreaks, int spaces, string originalString, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Formatting.TriviaDataFactory.ComplexTrivia.Format(Microsoft.CodeAnalysis.Formatting.FormattingContext context, Microsoft.CodeAnalysis.Formatting.ChainedFormattingRules formattingRules, int lines, int spaces, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Formatting.TriviaDataFactory.ComplexTrivia.Format(Microsoft.CodeAnalysis.Formatting.FormattingContext context, Microsoft.CodeAnalysis.Formatting.ChainedFormattingRules formattingRules, System.Action<int, Microsoft.CodeAnalysis.Formatting.TriviaData> formattingResultApplier, System.Threading.CancellationToken cancellationToken, int tokenPairIndex)	Unknown
 	Microsoft.CodeAnalysis.Formatting.AbstractFormatEngine.ApplyBeginningOfTreeTriviaOperation(Microsoft.CodeAnalysis.Formatting.FormattingContext context, Microsoft.CodeAnalysis.Formatting.TokenStream tokenStream, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Formatting.AbstractFormatEngine.Format(System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.CSharp.Formatting.CSharpSyntaxFormattingService.Format(Microsoft.CodeAnalysis.SyntaxNode node, Microsoft.CodeAnalysis.Options.OptionSet optionSet, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Formatting.Rules.IFormattingRule> formattingRules, Microsoft.CodeAnalysis.SyntaxToken token1, Microsoft.CodeAnalysis.SyntaxToken token2, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Formatting.AbstractSyntaxFormattingService.FormatIndividually(Microsoft.CodeAnalysis.SyntaxNode node, Microsoft.CodeAnalysis.Options.OptionSet options, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Formatting.Rules.IFormattingRule> rules, System.Collections.Generic.IList<Microsoft.CodeAnalysis.Text.TextSpan> spansToFormat, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Formatting.AbstractSyntaxFormattingService.Format(Microsoft.CodeAnalysis.SyntaxNode node, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Text.TextSpan> spans, Microsoft.CodeAnalysis.Options.OptionSet options, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Formatting.Rules.IFormattingRule> rules, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Formatting.Formatter.Format(Microsoft.CodeAnalysis.SyntaxNode node, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Text.TextSpan> spans, Microsoft.CodeAnalysis.Workspace workspace, Microsoft.CodeAnalysis.Options.OptionSet options, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Formatting.Rules.IFormattingRule> rules, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.Formatting.Formatter.FormatAsync(Microsoft.CodeAnalysis.Document document, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Text.TextSpan> spans, Microsoft.CodeAnalysis.Options.OptionSet options, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Formatting.Rules.IFormattingRule> rules, System.Threading.CancellationToken cancellationToken)	Unknown
```

The debugger reveals that the tokens being formatted are

```
#region Assembly Microsoft.VisualStudio.Shell.11.0, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// C:\Users\SSL\Development\Open Source\Mine\C#\VSEmbed\References\v11.0\Microsoft.VisualStudio.Shell.11.0.dll
#endregion

usingSystem;usingSystem.Collections.Generic;usingSystem.IO;namespaceMicrosoft.VisualStudio.Settings{publicabstractclassSettingsStore{protectedSettingsStore();publicabstractSystem.BooleanCollectionExists(System.StringcollectionPath);publicabstractSystem.BooleanGetBoolean(System.StringcollectionPath,System.StringpropertyName);publicabstractSystem.BooleanGetBoolean(System.StringcollectionPath,System.StringpropertyName,System.BooleandefaultValue);publicabstractSystem.Int32GetInt32(System.StringcollectionPath,System.StringpropertyName);publicabstractSystem.Int32GetInt32(System.StringcollectionPath,System.StringpropertyName,System.Int32defaultValue);publicabstractSystem.Int64GetInt64(System.StringcollectionPath,System.StringpropertyName);publicabstractSystem.Int64GetInt64(System.StringcollectionPath,System.StringpropertyName,System.Int64defaultValue);publicabstractglobal::System.DateTimeGetLastWriteTime(System.StringcollectionPath);publicabstractglobal::System.IO.MemoryStreamGetMemoryStream(System.StringcollectionPath,System.StringpropertyName);publicabstractSystem.Int32GetPropertyCount(System.StringcollectionPath);publicabstractglobal::System.Collections.Generic.IEnumerable<System.String>GetPropertyNames(System.StringcollectionPath);publicabstractglobal::Microsoft.VisualStudio.Settings.SettingsTypeGetPropertyType(System.StringcollectionPath,System.StringpropertyName);publicabstractSystem.StringGetString(System.StringcollectionPath,System.StringpropertyName);publicabstractSystem.StringGetString(System.StringcollectionPath,System.StringpropertyName,System.StringdefaultValue);publicabstractSystem.Int32GetSubCollectionCount(System.StringcollectionPath);publicabstractglobal::System.Collections.Generic.IEnumerable<System.String>GetSubCollectionNames(System.StringcollectionPath);publicabstractSystem.UInt32GetUInt32(System.StringcollectionPath,System.StringpropertyName);publicabstractSystem.UInt32GetUInt32(System.StringcollectionPath,System.StringpropertyName,System.UInt32defaultValue);publicabstractSystem.UInt64GetUInt64(System.StringcollectionPath,System.StringpropertyName);publicabstractSystem.UInt64GetUInt64(System.StringcollectionPath,System.StringpropertyName,System.UInt64defaultValue);publicabstractSystem.BooleanPropertyExists(System.StringcollectionPath,System.StringpropertyName);}}
```

It looks like the error comes when trying to format the `#endregion`

### PR DESCRIPTION
**Pull request by basoundr**
Fixes #4019 While formatting a complextrivia that falls as a end_of_tree
trivia of a tree that is being formatted, adjust the span of the
ComplexTrivia for formatting purposes

### CODE REVIEW

File: src/EditorFeatures/Core/Implementation/MetadataAsSource/MetadataAsSourceFileService.cs [hunk 1]
```diff
@@ -253,12 +253,17 @@ private void RemoveDocumentFromWorkspace_NoLock(MetadataAsSourceGeneratedFileInf
             }
         }
 
-        private void InitializeWorkspace(Project project)
+        private void InitializeWorkspace(Project project, OptionSet option)
```
Comment (rchande) [inline src/EditorFeatures/Core/Implementation/MetadataAsSource/MetadataAsSourceFileService.cs]: It doesn't look like you've updated the caller of MAS to pass in an OptionSet. How does MAS normally get the VS options? Can you reuse that in the tests instead of adding this parameter?

**Comment by basoundr** [comment]
retest this please

**Comment by basoundr** [comment]
@dotnet-bot retest this please

File: src/EditorFeatures/Core/Implementation/MetadataAsSource/MetadataAsSourceFileService.cs (hunk 1 above)
Comment (basoundr) [inline src/EditorFeatures/Core/Implementation/MetadataAsSource/MetadataAsSourceFileService.cs]: This looked more cleaner but your question makes sense. Let me see if how that turns out

Comment (basoundr) [inline src/EditorFeatures/Core/Implementation/MetadataAsSource/MetadataAsSourceFileService.cs]: @rchande I looked into making this change and found it not possible because the MAS spins up the new workspace, which in turn spins up a new optionService. The OptionService then populates the values for the options from the deserializer.

**Comment by basoundr** [comment]
@dotnet-bot retest this please

File: src/EditorFeatures/Core/Implementation/MetadataAsSource/MetadataAsSourceFileService.cs [hunk 2]
```diff
@@ -67,7 +67,7 @@ private string GetRootPathWithGuid_NoLock()
             return _rootTemporaryPathWithGuid;
         }
 
-        public async Task<MetadataAsSourceFile> GetGeneratedFileAsync(Project project, ISymbol symbol, CancellationToken cancellationToken = default(CancellationToken))
+        public async Task<MetadataAsSourceFile> GetGeneratedFileAsync(Project project, ISymbol symbol, OptionSet optionSet = null, CancellationToken cancellationToken = default(CancellationToken))
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/MetadataAsSource/MetadataAsSourceFileService.cs]: Do we need it to be explicit, or can you just pick up the options from the Project that's already being passed in?

File: src/EditorFeatures/Core/Implementation/MetadataAsSource/MetadataAsSourceFileService.cs (hunk 1 above)
Comment (rchande) [inline src/EditorFeatures/Core/Implementation/MetadataAsSource/MetadataAsSourceFileService.cs]: @basoundr We have a "TestOptionServiceFactory" that you should be able to add to the composition used by the MAS tests.

Comment (rchande) [inline src/EditorFeatures/Core/Implementation/MetadataAsSource/MetadataAsSourceFileService.cs]: Basically, you'll provide an implementation of IOptionProvider that doesn't use the serializers.

File: src/EditorFeatures/Test/MetadataAsSource/MetadataAsSourceTests.cs [hunk 3]
```diff
@@ -37,6 +40,26 @@ public class [|C|]
 End Class");
         }
 
+        [WorkItem(4019, "https://github.com/dotnet/roslyn/issues/4019")]
+        [Fact, Trait(Traits.Feature, Traits.Features.MetadataAsSource)]
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Test/MetadataAsSource/MetadataAsSourceTests.cs]: Given this isn't a bug in MetadataAsSource per se, can't we just test this with formatting tests? I recognize no user-inputted text will replicate it, but we really should have tests for this scenario directly.

(I'd prefer there actually aren't any tests for MAS here.)

File: src/EditorFeatures/Core/Implementation/MetadataAsSource/MetadataAsSourceFileService.cs (hunk 1 above)
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/MetadataAsSource/MetadataAsSourceFileService.cs]: There's also more subtleties here I failed to consider when writing this code, consider bug #4206 that I just filed. That's more an edge case, but it's indicative of "MAS isn't passing options around right as it is".

File: src/EditorFeatures/Core/Implementation/Peek/DefinitionPeekableItem.cs [hunk 4]
```diff
@@ -72,7 +72,7 @@ public void FindResults(string relationshipName, IPeekResultCollection resultCol
                 if (!sourceLocations.Any())
                 {
                     // It's a symbol from metadata, so we want to go produce it from metadata
-                    var declarationFile = _peekableItem._metadataAsSourceFileService.GetGeneratedFileAsync(project, symbol, cancellationToken).WaitAndGetResult(cancellationToken);
+                    var declarationFile = _peekableItem._metadataAsSourceFileService.GetGeneratedFileAsync(project, symbol, null, cancellationToken).WaitAndGetResult(cancellationToken);
```
Comment (balajikris) [inline src/EditorFeatures/Core/Implementation/Peek/DefinitionPeekableItem.cs]: suggestion: use named arguments ?

**Comment by basoundr** [comment]
Replaced the MAS test with a formatting test, which addresses the issue to be tested directly.

**Comment by rchande** [comment]
@basoundr Does your newly added test fail if you undo the change to the formatter? I thought we only hit this but on generated (and not parsed by the compiler) code.

**Comment by basoundr** [comment]
@rchande The crash happens only in the generated code and not in the compiler parsed code. Thats why I had to modify the parsed code(which I think you did not see properly) to resemble a structure that would look like a generated code. 

And ofcourse, the testcase fails without the fix. Wouldn't it defeat the purpose of writing the testcase? :D

**Comment by rchande** [comment]
@basoundr My bad, was reading a little too quickly. Mostly, I was thrown off by the local called "text" that you assign an Option to :smile:

**Comment by rchande** [comment]
:+1:

**Comment by basoundr** [comment]
Reviewers: @Pilchie @jasonmalinowski @DustinCampbell @rchande @dpoeschl @balajikris @brettfo @jmarolf @davkean

File: src/Workspaces/CSharp/Portable/Formatting/Engine/Trivia/TriviaDataFactory.ComplexTrivia.cs [hunk 5]
```diff
@@ -74,7 +74,7 @@ private bool ShouldFormat(FormattingContext context)
                 var commonToken1 = this.Token1;
                 var commonToken2 = this.Token2;
 
-                var span = TextSpan.FromBounds(commonToken1.Span.End, commonToken2.Span.Start);
+                var span = TextSpan.FromBounds(commonToken1.Span.End, commonToken2.Kind() == SyntaxKind.None ? commonToken1.Span.End : commonToken2.Span.Start);
```
Comment (DustinCampbell) [inline src/Workspaces/CSharp/Portable/Formatting/Engine/Trivia/TriviaDataFactory.ComplexTrivia.cs]: Might be worth extracting the conditional expression into a new local.

**Comment by DustinCampbell** [comment]
:+1:

File: src/Workspaces/CSharp/Portable/Formatting/Engine/Trivia/TriviaDataFactory.ComplexTrivia.cs (hunk 5 above)
Comment (dpoeschl) [inline src/Workspaces/CSharp/Portable/Formatting/Engine/Trivia/TriviaDataFactory.ComplexTrivia.cs]: Seconded.

File: src/Workspaces/CSharpTest/Formatting/FormattingTriviaTests.cs [hunk 6]
```diff
@@ -1723,5 +1720,46 @@ public void NewLineOptions_LineFeedOnly()
...
+{
+	string s;
+}";
+            var tree = SyntaxFactory.ParseCompilationUnit(code);
+
+            var text = DefaultWorkspace.Options.GetOption(FormattingOptions.NewLine, LanguageNames.CSharp);
+            var newLine = SyntaxFactory.ElasticEndOfLine(text);
+
+            tree = tree.ReplaceTokens(tree.DescendantTokens(descendIntoTrivia: true)
+                .Where(tr => tr.IsKind(SyntaxKind.EndOfDirectiveToken)), (o, r) => o.WithTrailingTrivia(o.LeadingTrivia.Add(newLine))
```
Comment (dpoeschl) [inline src/Workspaces/CSharpTest/Formatting/FormattingTriviaTests.cs]: Can you consider reformatting this statement?
- This line ends the first argument and begins the second argument, which makes it hard for me to visually parse. 
- It looks like the ```.Where``` might be a continuation of the ```tree.ReplaceTokens``` because of its indentation.

File: src/Workspaces/CSharpTest/Formatting/FormattingTriviaTests.cs [hunk 7]
```diff
@@ -1723,5 +1720,46 @@ public void NewLineOptions_LineFeedOnly()
...
+
+using System.Collections;
+
+class F
+{
+	string s;
+}";
+            var tree = SyntaxFactory.ParseCompilationUnit(code);
+
+            var text = DefaultWorkspace.Options.GetOption(FormattingOptions.NewLine, LanguageNames.CSharp);
```
Comment (dpoeschl) [inline src/Workspaces/CSharpTest/Formatting/FormattingTriviaTests.cs]: Consider rename to ```newLineText```? ```text``` makes me think it's the text of the tree.

**Comment by dpoeschl** [comment]
I know you ran into some trouble making MetadataAsSource unit tests because of the way that service is written (and so instead made a direct formatting test, which is fine). Can you file a bug for us to clean the MetadataAsSource service up?

**Comment by dpoeschl** [comment]
:+1:

**Comment by Pilchie** [comment]
The next VS Update is the current plan.

**Comment by SLaks** [comment]
Any word on when that will happen?
Is it possible for Roslyn to use a faster release cycle?

**Comment by Pilchie** [comment]
There is no word on dates for it yet.  Unfortunately, it's not technically possible to ship just Roslyn faster than that right now, though we are exploring the possibility of being able to ship VSIXs with updated Roslyn support on a faster cadence.

**Comment by DustinCampbell** [comment]
@slaks, unfortunately that's not possible at the moment. There are too many things in VS that might break even with Roslyn internal changes (e.g. TypeScript).

**Comment by Pilchie** [comment]
FYI that this fix is included in the VS2015 Update 1 CTP that was released today at http://blogs.msdn.com/b/visualstudio/archive/2015/10/08/visual-studio-2015-update-1-ctp.aspx.
