### PR TITLE
Make sure errors are consistent when providing null vs empty key files during signing

### LINKED ISSUE #11497: Inconsistent compiler behaviour between OS X and Windows if keyFile is the empty string
**Version Used**: 

_OS X_:

``` sh
computer:api user$ dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

_Windows_:

``` cmd
PS C:\Coding\api> dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64
```

**Steps to Reproduce**:
1. Clone [https://github.com/martincostello/api.git](https://github.com/martincostello/api.git) from commit [c7d2e8a448470c07d98160bc19cbc2786cb28fc6](https://github.com/martincostello/api/commit/c7d2e8a448470c07d98160bc19cbc2786cb28fc6).
2. Run `dotnet build src/API` from the root of the repository.

**Expected Behaviour**:

OS X and Windows build attempts exhibit the same behaviour, which is either to:
1. Treat `""` as `null` on both platforms and compile successfully with no strong name, or;
2. Treat `""` as an invalid key file and error with `error CS7088: Invalid 'CryptoKeyFile' value: ''.` on both platforms. I'm tending towards this being the preferrable behaviour as in my case I didn't have a key file at all, so I resolved the error by using `null` explicitly in [this commit](https://github.com/martincostello/api/commit/0dc2557083103f2ac500ae871a9a901cb0c8a293).

**Actual Behaviour**:

_OS X_:

``` sh
computer:api user$ dotnet build src/API
Project API (.NETCoreApp,Version=v1.0) will be compiled because expected inputs are missing
Compiling API for .NETCoreApp,Version=v1.0
/usr/local/share/dotnet/dotnet compile-csc @/Users/user/Coding/api/src/API/obj/Debug/netcoreapp1.0/dotnet-compile.rsp returned Exit Code 1
/Users/user/Coding/api/src/API/error CS7088: Invalid 'CryptoKeyFile' value: ''.

Compilation failed.
    0 Warning(s)
    1 Error(s)

Time elapsed 00:00:01.5841885
```

_Windows_:

``` cmd
PS C:\Coding\api> dotnet build .\src\API\
Project API (.NETCoreApp,Version=v1.0) will be compiled because expected inputs are missing
Compiling API for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:02.5016735
```

### PR DESCRIPTION
**Pull request by OmarTawfik**
@dotnet/roslyn-compiler 
Fixes #11497

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Diagnostics/GetDiagnosticsTests.cs [hunk 1]
```diff
@@ -394,5 +394,43 @@ public void CompilingCodeWithSameParseOptionsInMultipleSyntaxTreesShouldReportOn
             Assert.True(diagnostics[0].Location.SourceTree.Equals(syntaxTree1));
             Assert.True(diagnostics[1].Location.SourceTree.Equals(syntaxTree2));
         }
+
+        [Fact]
+        [WorkItem(11497, "https://github.com/dotnet/roslyn/issues/11497")]
+        public void ConsistentErrorMessageWhenProvidingNullKeyFile()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Diagnostics/GetDiagnosticsTests.cs]: >ConsistentErrorMessageWhenProvidingNullKeyFile [](start = 20, length = 46)

These test probably should be placed next to other signing tests. Also, when we expect compilation to succeed, we should probably emit, verify the output and check expected signed state.

File: src/Compilers/CSharp/Test/Semantic/Diagnostics/GetDiagnosticsTests.cs [hunk 2]
```diff
@@ -394,5 +394,43 @@ public void CompilingCodeWithSameParseOptionsInMultipleSyntaxTreesShouldReportOn
...
+                Diagnostic(ErrorCode.ERR_PublicSignButNoKey).WithLocation(1, 1));
+        }
+
+        [Fact]
+        [WorkItem(11497, "https://github.com/dotnet/roslyn/issues/11497")]
+        public void ConsistentErrorMessageWhenProvidingEmptyKeyFile_PublicSigne()
+        {
+            var options = new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, cryptoKeyFile: string.Empty, publicSign: true);
+            CreateCompilation(string.Empty, options: options).VerifyDiagnostics(
+                // error CS8106: Option 'CryptoKeyFile' must be an absolute path.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Diagnostics/GetDiagnosticsTests.cs]: >// error CS8106: Option 'CryptoKeyFile' must be an absolute path. [](start = 16, length = 65)

This error feels unexpected if we want an empty string and null to be treated the same way.

File: src/Compilers/VisualBasic/Test/Semantic/Diagnostics/GetDiagnosticsTests.vb [hunk 3]
```diff
@@ -448,5 +448,45 @@ BC31030: Conditional compilation constant '2' is not valid: Identifier expected.
...
+            CreateCompilation(String.Empty, options:=options).VerifyDiagnostics()
+        End Sub
+
+        <Fact>
+        <WorkItem(11497, "https://github.com/dotnet/roslyn/issues/11497")>
+        Public Sub ConsistentErrorMessageWhenProvidingNullKeyFile_PublicSign()
+            Dim options = New VisualBasicCompilationOptions(OutputKind.DynamicallyLinkedLibrary, cryptoKeyFile:=Nothing, publicSign:=True)
+            Dim compilation = CreateCompilation(String.Empty, options:=options)
+
+            CompilationUtils.AssertTheseDiagnostics(compilation.GetDiagnostics(),
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/Diagnostics/GetDiagnosticsTests.vb]: >.GetDiagnostics() [](start = 63, length = 17)

It looks like the GetDiagnostics call is not necessary.

File: src/Compilers/VisualBasic/Test/Semantic/Diagnostics/GetDiagnosticsTests.vb [hunk 4]
```diff
@@ -448,5 +448,45 @@ BC31030: Conditional compilation constant '2' is not valid: Identifier expected.
...
+        <Fact>
+        <WorkItem(11497, "https://github.com/dotnet/roslyn/issues/11497")>
+        Public Sub ConsistentErrorMessageWhenProvidingEmptyKeyFile_PublicSign()
+            Dim options = New VisualBasicCompilationOptions(OutputKind.DynamicallyLinkedLibrary, cryptoKeyFile:=String.Empty, publicSign:=True)
+            Dim compilation = CreateCompilation(String.Empty, options:=options)
+
+            CompilationUtils.AssertTheseDiagnostics(compilation.GetDiagnostics(),
+<errors>
+BC37254: Public sign was specified and requires a public key, but no public key was specified
+BC37257: Option 'CryptoKeyFile' must be an absolute path.
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/Diagnostics/GetDiagnosticsTests.vb]: Same comment as for C#.

**Comment by AlekseyTs** [comment]
Done with review pass.

File: src/Compilers/CSharp/Test/Semantic/Diagnostics/GetDiagnosticsTests.cs (hunk 1 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Test/Semantic/Diagnostics/GetDiagnosticsTests.cs]: The issue/PR has nothing to do with signing. It is just about input validation, and whether we're consistent when reporting error strings or not.
I'll edit these tests to just verify CompilationOptions.Errors in that case.
Please let me know if you disagree.

---
In reply to: [109721642](https://github.com/dotnet/roslyn/pull/18407#discussion_r109721642) [](ancestors = 109721642)

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Diagnostics/GetDiagnosticsTests.cs]: I think this fix is related to signing. We are making changes around options that affect signing exclusively. Both success and error cases should be tested.

File: src/Compilers/CSharp/Test/Semantic/Diagnostics/GetDiagnosticsTests.cs (hunk 2 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Test/Semantic/Diagnostics/GetDiagnosticsTests.cs]: Null here means uninitialized/not set. An empty string means that the user specifically set it to something, and we will validate it. Since an empty string is not a valid path, we will error out.
What do you propose to do instead?

---
In reply to: [109722102](https://github.com/dotnet/roslyn/pull/18407#discussion_r109722102) [](ancestors = 109722102)

File: src/Compilers/VisualBasic/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.vb [hunk 5]
```diff
@@ -31,15 +31,12 @@ Partial Public Class InternalsVisibleToAndStrongNameTests
         Return New SigningTestHelpers.VirtualizedStrongNameProvider(ImmutableArray.Create(keyFilePath))
     End Function
 
-    Private Shared Sub VerifySigned(comp As Compilation)
+    Private Shared Sub VerifySigned(comp As Compilation, Optional expectedToBeSigned As Boolean = True)
```
Comment (OmarTawfik) [inline src/Compilers/VisualBasic/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.vb]: Note to self: investigate moving these helper classes to a base type.

File: src/Compilers/CSharp/Test/Semantic/Diagnostics/GetDiagnosticsTests.cs (hunk 2 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Diagnostics/GetDiagnosticsTests.cs]: If we are saying that null and empty string are equivalent, then we should treat them this way. For both we report an error that key wasn't specified, but for empty string we also report some other confusing error. I am proposing to treat an empty string the same way as null as PR's title implies.

---
In reply to: [109781874](https://github.com/dotnet/roslyn/pull/18407#discussion_r109781874) [](ancestors = 109781874,109722102)

**Comment by OmarTawfik** [comment]
@AlekseyTs comments addressed.

File: src/Compilers/CSharp/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.cs [hunk 6]
```diff
@@ -2277,6 +2273,48 @@ public void Bug1095618()
...
+                Diagnostic(ErrorCode.ERR_PublicSignButNoKey).WithLocation(1, 1));
+        }
+
+        [Fact]
+        [WorkItem(11497, "https://github.com/dotnet/roslyn/issues/11497")]
+        public void ConsistentErrorMessageWhenProvidingEmptyKeyFile_PublicSigne()
+        {
+            var options = new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, cryptoKeyFile: string.Empty, publicSign: true);
+            CreateCompilationWithMscorlib(string.Empty, options: options).VerifyDiagnostics(
+                // error CS8106: Option 'CryptoKeyFile' must be an absolute path.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.cs]: >// error CS8106: Option 'CryptoKeyFile' must be an absolute path. [](start = 16, length = 65)

I believe that we should not be reporting this error for an empty string as we don't report it for null and the other error clearly states that the key was not specified. If it was not specified, it shouldn't be validated.

File: src/Compilers/VisualBasic/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.vb [hunk 7]
```diff
@@ -2080,4 +2077,47 @@ End Class]]>
...
+
+    <Fact>
+    <WorkItem(11497, "https://github.com/dotnet/roslyn/issues/11497")>
+    Public Sub ConsistentErrorMessageWhenProvidingEmptyKeyFile_PublicSign()
+        Dim options = New VisualBasicCompilationOptions(OutputKind.DynamicallyLinkedLibrary, cryptoKeyFile:=String.Empty, publicSign:=True)
+        Dim compilation = CreateCompilationWithMscorlib(String.Empty, options:=options)
+
+        CompilationUtils.AssertTheseDiagnostics(compilation,
+<errors>
+BC37254: Public sign was specified and requires a public key, but no public key was specified
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.vb]: Similar to C#, I don't think this error should be reported.

File: src/Compilers/CSharp/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.cs [hunk 8]
```diff
@@ -2277,6 +2273,46 @@ public void Bug1095618()
...
+        }
+
+        [Fact]
+        [WorkItem(11497, "https://github.com/dotnet/roslyn/issues/11497")]
+        public void ConsistentErrorMessageWhenProvidingEmptyKeyFile_PublicSign()
+        {
+            var options = new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, cryptoKeyFile: string.Empty, publicSign: true);
+            CreateCompilationWithMscorlib(string.Empty, options: options).VerifyDiagnostics(
+                // error CS8102: Public signing was specified and requires a public key, but no public key was specified.
+                Diagnostic(ErrorCode.ERR_PublicSignButNoKey));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.cs]: >Diagnostic(ErrorCode.ERR_PublicSignButNoKey) [](start = 16, length = 44)

Please keep the location.

File: src/Compilers/CSharp/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.cs [hunk 9]
```diff
@@ -2277,6 +2273,46 @@ public void Bug1095618()
...
+        }
+
+        [Fact]
+        [WorkItem(11497, "https://github.com/dotnet/roslyn/issues/11497")]
+        public void ConsistentErrorMessageWhenProvidingNullKeyFile_PublicSign()
+        {
+            var options = new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, cryptoKeyFile: null, publicSign: true);
+            CreateCompilationWithMscorlib(string.Empty, options: options).VerifyDiagnostics(
+                // error CS8102: Public signing was specified and requires a public key, but no public key was specified.
+                Diagnostic(ErrorCode.ERR_PublicSignButNoKey));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.cs]: >Diagnostic(ErrorCode.ERR_PublicSignButNoKey)); [](start = 16, length = 46)

Please keep the location.
