### PR TITLE
Fix for flaky test TestAnalyzerLoading

### LINKED ISSUE #6665: AnalyzerFileReferenceTests.TestAnalyzerLoading is periodically failing in future
See http://dotnet-ci.cloudapp.net/job/roslyn-internal_future_win_dbg_unit64/49/testReport/Microsoft.CodeAnalysis.UnitTests/AnalyzerFileReferenceTests/TestAnalyzerLoading/ for an example

### PR DESCRIPTION
**Pull request by mavasani**
This test is failing intermittently with an `InvalidCastException` _'Unable to cast transparent proxy to type 'Microsoft.CodeAnalysis.UnitTests.RemoteAnalyzerFileReferenceTest'_ over [here](http://source.roslyn.io/#Roslyn.Compilers.UnitTests/AnalyzerFileReferenceTests.cs,197). This test creates a separate appdomain, invokes `CreateInstanceAndUnwrap` on it and then casts the created object to type `RemoteAnalyzerFileReferenceTest` defined in the same assembly. This indicates that the CLR ended up loading a separate instance of the assembly from a different path in the appdomain, causing the cast failure.

Fix is to use the [AppDomainUtils.Create](http://source.roslyn.io/Roslyn.Test.Utilities.Desktop/R/32b4516c21702320.html) method for creating the appdomain. This helper method has a special assembly resolve handler hooked up to the created appdomain that first attempts to resolve the assembly from current xunit directory. This helper is already being used by a similar remote analyzer loading test [TestAnalyzerLoading_Error](http://source.roslyn.io/#Roslyn.Compilers.UnitTests/AnalyzerFileReferenceTests.cs,b04fd584904390af).

Fixes #6665

### CODE REVIEW

**Comment by mavasani** [comment]
@srivatsn @heejaechang @tmeschter @brettfo can you please review?

**Comment by brettfo** [comment]
Re-run the windows tests a few times to try to shake it out, but otherwise :shipit:

File: src/Compilers/Core/CodeAnalysisTest/AnalyzerFileReferenceTests.cs [hunk 1]
```diff
@@ -187,17 +187,23 @@ public void TestLoadErrors3()
             Assert.Equal(0, errors.Count);
         }
 
-        [Fact(Skip = "https://github.com/dotnet/roslyn/issues/6665")]
+        [Fact]
         public void TestAnalyzerLoading()
         {
             var dir = Temp.CreateDirectory();
             var test = dir.CopyFile(typeof(FromFileLoader).Assembly.Location);
             var analyzerFile = TestHelpers.CreateCSharpAnalyzerAssemblyWithTestAnalyzer(dir, "MyAnalyzer");
```
Comment (srivatsn) [inline src/Compilers/Core/CodeAnalysisTest/AnalyzerFileReferenceTests.cs]: Do you also want to wrap analyzerFile in a using to make sure it's disposed?

**Comment by srivatsn** [comment]
:+1:

File: src/Compilers/Core/CodeAnalysisTest/AnalyzerFileReferenceTests.cs (hunk 1 above)
Comment (mavasani) [inline src/Compilers/Core/CodeAnalysisTest/AnalyzerFileReferenceTests.cs]: That's actually not required as [Temp](http://source.roslyn.io/Roslyn.Test.Utilities.Desktop/R/b2f9b4034b00b7f5.html) will get disposed after each test class finishes executing, which deletes the temp directory created in the tests.

**Comment by natidea** [comment]
:+1: Thanks Manish. Are we also going to need to merge this into master to prevent flakiness in Update 2 work?

**Comment by mavasani** [comment]
Yes will do so.

Sent from Outlook<http://aka.ms/Ox5hz3>

_____________________________

**Comment by mavasani** [comment]
@dotnet-bot retest prtest/win/dbg/unit64 please.

FYI: retesting just to verify flaky test fixed here doesn't fail again.
