### PR TITLE
Few fixes for DeclarationKind enum

### LINKED ISSUE #48136: public enum DeclarationKind must have an InitAccessor member
https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.editing.declarationkind?view=roslyn-dotnet

The current enum members include GetAccessor, SetAccessor, but not InitAccessor.

### PR DESCRIPTION
**Pull request by Youssef1313**
Closes #48136

Edit: @sharwell I'm removing #52799 from being fixed as this PR doesn't delete RecordStruct from the enum. This issue will need to be fixed separately (RecordStruct isn't in main)

### CODE REVIEW

File: src/Workspaces/Core/Portable/Editing/DeclarationKind.cs [hunk 1]
```diff
@@ -37,10 +46,18 @@ public enum DeclarationKind
...
+        /// </summary>
         SetAccessor,
+
         AddAccessor,
         RemoveAccessor,
         RaiseAccessor,
+
+        [Obsolete($"This value is not used. Use {nameof(Class)} instead.")]
+        [EditorBrowsable(EditorBrowsableState.Never)]
         RecordClass,
```
Comment (Youssef1313) [inline src/Workspaces/Core/Portable/Editing/DeclarationKind.cs:61]: :warning: This enum member was shipped, but it's still in Unshipped text file. I suspect this is unintentional?

Comment (sharwell) [reply src/Workspaces/Core/Portable/Editing/DeclarationKind.cs:61]: @333fred

**Review by sharwell — APPROVED** [review]

**Comment by sharwell** [comment]
LGTM pending API change review

File: src/Workspaces/Core/Portable/Editing/DeclarationKind.cs (hunk 1 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Editing/DeclarationKind.cs:61]: This case was missed during the 3.9.0 API review, so we have two options:

1. Fix it for 3.10.0
2. Leave it like it was, and have this be the only special case for this enum

Comment (333fred) [reply src/Workspaces/Core/Portable/Editing/DeclarationKind.cs:61]: I don't understand. The doc comment appears to be wrong, we were using this enum. Why are we obsoleteing it?

Comment (Youssef1313) [reply src/Workspaces/Core/Portable/Editing/DeclarationKind.cs:61]: @333fred The intent of DeclarationKind enum is to represent language-agnostic declarations. For example, it doesn't have the VB modules. The addition of RecordClass didn't follow the intent of the enum. The available options are:

- Keep the inconsistency, and start adding language-specific declarations, e.g, VB modules, C# init accessors, record classes, and record structs.
- Delete RecordStructs since it's not shipped, and obsolete (and don't use) RecordClasses.

@sharwell and @CyrusNajmabadi preferred the second option.

**Review by mavasani — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by 333fred** [comment]
@CyrusNajmabadi @mavasani did you send an email to the roslyn compat council?
