### PR TITLE
Parse `[` after nullable type as part of the type

### LINKED ISSUE #55013: Error parsing nullable arrays in switch patterns
Consider the following code 

```cs
#nullable enable
using System;
public class C {
    public object field;
    public void M() {
    }
    
    string Prop => field switch
    {
        string?[] arr => "a"
    };
}
```

This parses in 3.10 but fails in 4.0. Likely this is a regression introduced when we changed lambda parsing. 

DevDiv tracking issue: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1359655/

### PR DESCRIPTION
**Pull request by cston**
Parse `? [` as a nullable array type always in `switch` and `is` expression pattern types: `x switch { string ? [] y => y }`

As a result, parentheses are required when the `[` starts a lambda expression with attributes: `x is string ? ([A] y => y) : z`

Fixes #55013.

### CODE REVIEW

**Comment by cston** [comment]
>                             return !CanStartExpression();

Before this change, `CanStartExpression()` returned `true` for `[` so `x is string?[] y ...` was treated as a conditional expression `x is string ? ([] y ...) ...` rather than a test of an array.

---
Refers to: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:6861 in 813334a. [](commit_id = 813334a7f3b8abefc2f60b6bbc2854665b731f5a, deletion_comment = False)

**Comment by cston** [comment]
@dotnet/roslyn-compiler, please review this fix for parsing nullable array types in `switch` and `is` patterns. The actual parsing change is small, but there are a number of parsing tests included. Thanks.

**Review by 333fred — APPROVED** [review]

File: src/Compilers/CSharp/Test/Syntax/Parsing/LambdaAttributeParsingTests.cs [hunk 1]
```diff
@@ -1964,37 +1961,1494 @@ public void Range_02()
...
+                }
+                N(SyntaxKind.CloseBraceToken);
+            }
+            EOF();
+        }
+
+        [Fact]
+        public void NullableType_Switch_03()
+        {
+            string source = "x switch { string? [A] y => y }";
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Syntax/Parsing/LambdaAttributeParsingTests.cs:2125]: Makes me glad that we decided to separate list-pattern from the more general recursive pattern ;-)

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 2)

**Comment by jcouv** [comment]
Approved by BU and Division triage in email. Can be merged to 16.11
FYI @allisonchou
