### PR TITLE
Integration test stability improvements

### LINKED ISSUE #26039: Lack of UI automation retry leads to integration test failure
This case is similar to the ones addressed by commits 36886991c8b770eb2b05f3fd17c70d4ddb203c9f and b13e9744e281e24c7dc7e44d624e54ee3fc9c800, and should be corrected in a similar fashion.

Example:

https://ci.dot.net/job/dotnet_roslyn/job/dev15.7.x/job/windows_release_vs-integration_prtest/354/

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Could not find item with name 'CSProj' under 'ProjectList'.
   at Microsoft.VisualStudio.IntegrationTest.Utilities.AutomationElementExtensions.FindDescendantByName(IUIAutomationElement parent, String name)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.DialogHelpers.SelectComboBoxItem(IntPtr visualStudioHWnd, String dialogAutomationName, String comboBoxAutomationName, String itemText)
   at Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.GenerateTypeDialog_OutOfProc.SetTargetProject(String projectName)
   at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicGenerateTypeDialog.BasicToCSharp()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance)
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task).GetType().Name
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance)
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
```

As shown in the screenshot, the element of interest is available:

image

### PR DESCRIPTION
**Pull request by sharwell**
Various improvements for integration testing

* Invoke UI thread operations at **Background** priority, allowing other initialization/input/render operations to complete before them
* Close the **Object Browser** window as part of the between-test cleanup
* Avoid hiding true failures caused by a second exception thrown in a `finally` block
* Add more UI Automation retry operations
* Avoid polluting completion for `System.Object` by moving extension methods to a nested namespace

Fixes #26039

<details><summary>Ask Mode template not completed</summary>

### Customer scenario

What does the customer do to get into this situation, and why do we think this
is common enough to address for this release.  (Granted, sometimes this will be
obvious "Open project, VS crashes" but in general, I need to understand how
common a scenario is)

### Bugs this fixes

(either VSO or GitHub links)

### Workarounds, if any

Also, why we think they are insufficient for RC vs. RC2, RC3, or RTW

### Risk

This is generally a measure our how central the affected code is to adjacent
scenarios and thus how likely your fix is to destabilize a broader area of code

### Performance impact

(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")

### Root cause analysis

How did we miss it?  What tests are we adding to guard against it in the future?

### How was the bug found?

(E.g. customer reported it vs. ad hoc testing)

### Test documentation updated?

If this is a new non-compiler feature or a significant improvement to an existing feature, update https://github.com/dotnet/roslyn/wiki/Manual-Testing once you know which release it is targeting.

</details>

### CODE REVIEW

File: src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs [hunk 1]
```diff
@@ -647,7 +647,7 @@ private void ProduceTagsSynchronously(TaggerContext<TTag> context)
                 {
                     foreach (var (latestBuffer, latestSpans) in newTagTrees)
                     {
-                        var snapshot = spansToTag.First(s => s.SnapshotSpan.Snapshot.TextBuffer == latestBuffer).SnapshotSpan.Snapshot;
+                        var snapshot = spansToTag.FirstOrDefault(s => s.SnapshotSpan.Snapshot.TextBuffer == latestBuffer).SnapshotSpan.Snapshot ?? latestBuffer.CurrentSnapshot;
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs]: this is scary to me.  esp. without a comment.  When are we asking for spans to tag... but then none of those spans to tag match the buffer we care about...

**Comment by CyrusNajmabadi** [comment]
sorry, missed the "personal" label.

File: src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs (hunk 1 above)
Comment (sharwell) [reply src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs]: ➡️ This is just building on #27933.

**Comment by sharwell** [comment]
@dotnet-bot retest this please

File: src/VisualStudio/IntegrationTest/TestUtilities/AutomationElementExtensions.cs [hunk 2]
```diff
@@ -39,7 +39,10 @@ public static IUIAutomationElement FindDescendantByAutomationId(this IUIAutomati
             }
 
             var condition = Helper.Automation.CreatePropertyCondition(AutomationElementIdentifiers.AutomationIdProperty.Id, automationId);
-            var child = parent.FindFirst(TreeScope.TreeScope_Descendants, condition);
+            var child = Helper.Retry(
+                () => parent.FindFirst(TreeScope.TreeScope_Descendants, condition),
+                AutomationRetryDelay,
```
Comment (tannergooding) [inline src/VisualStudio/IntegrationTest/TestUtilities/AutomationElementExtensions.cs]: It seems like these would be good candidates for default values (or an overload which just takes the lambda).

File: src/VisualStudio/IntegrationTest/TestUtilities/InProcess/InProcComponent.cs [hunk 3]
```diff
@@ -29,13 +29,13 @@ private static Dispatcher CurrentApplicationDispatcher
             => Application.Current.Dispatcher;
 
         protected static void BeginInvokeOnUIThread(Action action)
-            => CurrentApplicationDispatcher.BeginInvoke(action);
+            => CurrentApplicationDispatcher.BeginInvoke(action, DispatcherPriority.Background);
```
Comment (tannergooding) [inline src/VisualStudio/IntegrationTest/TestUtilities/InProcess/InProcComponent.cs]: A helper for this seems useful, so that new code will also be Background by default.

Comment (sharwell) [reply src/VisualStudio/IntegrationTest/TestUtilities/InProcess/InProcComponent.cs]: ➡️ This _is_ the helper 😄

File: src/VisualStudio/IntegrationTest/TestUtilities/AutomationElementExtensions.cs (hunk 2 above)
Comment (sharwell) [reply src/VisualStudio/IntegrationTest/TestUtilities/AutomationElementExtensions.cs]: I don't have enough confidence in these specific values to make them the default for all operations. Could be considered in the future if we ever get to a state of high reliability though.

**Comment by tmat** [comment]
Bunch of tests are failing with `System.Runtime.Remoting.RemotingException : Failed to read from an IPC Port: The pipe has been ended.` error:
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/2112/

**Comment by sharwell** [comment]
@tmat Yes, that's the existing issue from #27933

**Comment by tmat** [comment]
ok
