### PR TITLE
recursive-patterns(12): Improve switch code by using pattern variables as match automaton temps

### LINKED ISSUE #20641: Pattern matching IL much larger than non-pattern matching equivalent
**Version Used**:
2.3.0.61814 (b7f611db)

**Steps to Reproduce**:
Compile the following program:
```C#
using System.Collections;
using System.Collections.Generic;

class Program
{
    static void Main() { }

    internal static bool TryGetCount1<T>(IEnumerable<T> source, out int count)
    {
        ICollection nonGeneric = source as ICollection;
        if (nonGeneric != null)
        {
            count = nonGeneric.Count;
            return true;
        }

        ICollection<T> generic = source as ICollection<T>;
        if (generic != null)
        {
            count = generic.Count;
            return true;
        }

        count = -1;
        return false;
    }

    internal static bool TryGetCount2<T>(IEnumerable<T> source, out int count)
    {
        switch (source)
        {
            case ICollection nonGeneric:
                count = nonGeneric.Count;
                return true;

            case ICollection<T> generic:
                count = generic.Count;
                return true;

            default:
                count = -1;
                return false;
        }
    }
}
```

**Expected Behavior**:
The IL for TryGetCount1 and TryGetCount2 would be close to identical.

**Actual Behavior**:
The IL for TryGetCount2 is ~28% larger than that for TryGetCount1.
```
.method assembly hidebysig static bool  TryGetCount1<T>(class [mscorlib]System.Collections.Generic.IEnumerable`1<!!T> source,
                                                        [out] int32& count) cil managed
{
  // Code size       45 (0x2d)
  .maxstack  2
  .locals init ([0] class [mscorlib]System.Collections.ICollection nonGeneric,
           [1] class [mscorlib]System.Collections.Generic.ICollection`1<!!T> generic)
  IL_0000:  ldarg.0
  IL_0001:  isinst     [mscorlib]System.Collections.ICollection
  IL_0006:  stloc.0
  IL_0007:  ldloc.0
  IL_0008:  brfalse.s  IL_0014
  IL_000a:  ldarg.1
  IL_000b:  ldloc.0
  IL_000c:  callvirt   instance int32 [mscorlib]System.Collections.ICollection::get_Count()
  IL_0011:  stind.i4
  IL_0012:  ldc.i4.1
  IL_0013:  ret
  IL_0014:  ldarg.0
  IL_0015:  isinst     class [mscorlib]System.Collections.Generic.ICollection`1<!!T>
  IL_001a:  stloc.1
  IL_001b:  ldloc.1
  IL_001c:  brfalse.s  IL_0028
  IL_001e:  ldarg.1
  IL_001f:  ldloc.1
  IL_0020:  callvirt   instance int32 class [mscorlib]System.Collections.Generic.ICollection`1<!!T>::get_Count()
  IL_0025:  stind.i4
  IL_0026:  ldc.i4.1
  IL_0027:  ret
  IL_0028:  ldarg.1
  IL_0029:  ldc.i4.m1
  IL_002a:  stind.i4
  IL_002b:  ldc.i4.0
  IL_002c:  ret
} // end of method Program::TryGetCount1
```
and
```
.method assembly hidebysig static bool  TryGetCount2<T>(class [mscorlib]System.Collections.Generic.IEnumerable`1<!!T> source,
                                                        [out] int32& count) cil managed
{
  // Code size       58 (0x3a)
  .maxstack  2
  .locals init ([0] class [mscorlib]System.Collections.Generic.IEnumerable`1<!!T> V_0,
           [1] class [mscorlib]System.Collections.ICollection V_1,
           [2] class [mscorlib]System.Collections.Generic.ICollection`1<!!T> V_2,
           [3] class [mscorlib]System.Collections.ICollection nonGeneric,
           [4] class [mscorlib]System.Collections.Generic.ICollection`1<!!T> generic)
  IL_0000:  ldarg.0
  IL_0001:  stloc.0
  IL_0002:  ldloc.0
  IL_0003:  brfalse.s  IL_0035
  IL_0005:  ldloc.0
  IL_0006:  isinst     [mscorlib]System.Collections.ICollection
  IL_000b:  dup
  IL_000c:  stloc.1
  IL_000d:  brtrue.s   IL_001b
  IL_000f:  ldloc.0
  IL_0010:  isinst     class [mscorlib]System.Collections.Generic.ICollection`1<!!T>
  IL_0015:  dup
  IL_0016:  stloc.2
  IL_0017:  brfalse.s  IL_0035
  IL_0019:  br.s       IL_0027
  IL_001b:  ldloc.1
  IL_001c:  stloc.3
  IL_001d:  ldarg.1
  IL_001e:  ldloc.3
  IL_001f:  callvirt   instance int32 [mscorlib]System.Collections.ICollection::get_Count()
  IL_0024:  stind.i4
  IL_0025:  ldc.i4.1
  IL_0026:  ret
  IL_0027:  ldloc.2
  IL_0028:  stloc.s    generic
  IL_002a:  ldarg.1
  IL_002b:  ldloc.s    generic
  IL_002d:  callvirt   instance int32 class [mscorlib]System.Collections.Generic.ICollection`1<!!T>::get_Count()
  IL_0032:  stind.i4
  IL_0033:  ldc.i4.1
  IL_0034:  ret
  IL_0035:  ldarg.1
  IL_0036:  ldc.i4.m1
  IL_0037:  stind.i4
  IL_0038:  ldc.i4.0
  IL_0039:  ret
} // end of method Program::TryGetCount2
```

### LINKED ISSUE #25566: Possible decision dag optimization: use pattern variables in place of temps
One possible optimization would be to use pattern variables directly rather than using the pattern-matching temps to avoid a copy when the pattern matches.

This would probably help address https://github.com/dotnet/roslyn/issues/20641

It would require expanding the scope of those variables, but they are already expanded (not from the debugger's point of view) so capturing across sections works right (e.g. when a local function in one section captures some pattern variable but is called from another section).

This would have to be done carefully so the scopes work correctly in the new *switch expression*.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #20641
Fixes #25566

@cston @agocke Please review. **There is only a single delta in this PR**, though you may see deltas from previous PRs. The optimization is not very complex but it makes a big difference in some cases (I'll point out the principal use case).

/cc @dotnet/roslyn-compiler

### CODE REVIEW

File: src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs [hunk 1]
```diff
@@ -486,61 +469,662 @@ .maxstack  2
...
+  IL_0027:  ret
+  IL_0028:  ldarg.1
+  IL_0029:  ldc.i4.m1
+  IL_002a:  stind.i4
+  IL_002b:  ldc.i4.0
+  IL_002c:  ret
+}");
+            compVerifier.VerifyIL("Program.TryGetCount2<T>",
+@"{
+  // Code size       47 (0x2f)
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs]: This is the driving use case for this optimization. See #20641. Now the code is nearly the same as the hand-written alternative, with the exception of a different ordering of the basic blocks which causes a couple of extra IL bytes.

File: src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs [hunk 2]
```diff
@@ -3525,47 +3513,38 @@ .maxstack  1
 
             verifier.VerifyIL("Program.M1<T>",
 @"{
-  // Code size       46 (0x2e)
+  // Code size       29 (0x1d)
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs]: An example of how much better things can get.

File: src/Compilers/CSharp/Portable/BoundTree/BoundDecisionDag.cs [hunk 3]
```diff
@@ -10,24 +10,27 @@
...
                     yield return p.WhenTrue;
                     yield break;
-                case BoundDecision d:
+                case BoundLeafDecisionDagNode d:
                     yield break;
-                case BoundWhenClause w:
+                case BoundWhenDecisionDagNode w:
                     Debug.Assert(w.WhenTrue != null);
                     yield return w.WhenTrue;
                     if (w.WhenFalse != null)
```
Comment (alrz) [inline src/Compilers/CSharp/Portable/BoundTree/BoundDecisionDag.cs]: Could as well return ImmutableArray?
```cs
return w.WhenFalse != null
  ? ImmurableArray.Create(w.WhenTrue, w.WhenFalse)
  : ImmutableArray.Create(w.WhenTrue);
```

Comment (gafter) [reply src/Compilers/CSharp/Portable/BoundTree/BoundDecisionDag.cs]: This is an iterator method. I think you're suggesting changing it to an ordinary method. I don't think it would reduce allocation (there is an array inside the `ImmutableArray`, and that immutable array would be boxed for the return value's `IEnumerable<...>`. In fact, I think that's *more* allocation.

---
In reply to: [177485292](https://github.com/dotnet/roslyn/pull/25739#discussion_r177485292) [](ancestors = 177485292)

Comment (alrz) [reply src/Compilers/CSharp/Portable/BoundTree/BoundDecisionDag.cs]: Thought that `if` is the only reason that this had to become an iterator *and* in turn, return IEnumerable. if the sort algorithm only works on an IEnumerable, yeah it won't make much of a difference, but we could possibly make all that ImmurableArray to avoid boxing all the way and simplify generated code.

Comment (gafter) [reply src/Compilers/CSharp/Portable/BoundTree/BoundDecisionDag.cs]: The generic topological sort is used in a few places, but yes it could probably be made to use an immutable array instead of an `IEnumerable`. I've recorded your suggestion as [https://github.com/dotnet/roslyn/issues/25754](https://github.com/dotnet/roslyn/issues/25754)

---
In reply to: [177498107](https://github.com/dotnet/roslyn/pull/25739#discussion_r177498107) [](ancestors = 177498107)

**Comment by gafter** [comment]
Previous test failure: https://ci.dot.net/job/dotnet_roslyn/job/features_recursive-patterns/job/windows_release_unit64_prtest/130/

test windows_release_unit64_prtest please

**Comment by gafter** [comment]
test windows_release_unit64_prtest please

File: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml [hunk 4]
```diff
@@ -841,31 +858,35 @@
...
-    <Field Name="WhenFalse" Type="BoundDecisionDag" Null="disallow"/>
+  <Node Name="BoundTestDecisionDagNode" Base="BoundDecisionDagNode ">
+    <Field Name="Test" Type="BoundDagTest" Null="disallow"/>
+    <Field Name="WhenTrue" Type="BoundDecisionDagNode " Null="disallow"/>
+    <Field Name="WhenFalse" Type="BoundDecisionDagNode " Null="disallow"/>
   </Node>
-  <Node Name="BoundWhenClause" Base="BoundDecisionDag">
-    <Field Name="Bindings" Type="ImmutableArray&lt;(BoundExpression,BoundDagTemp)&gt;" Null="disallow"/>
+  <Node Name="BoundWhenDecisionDagNode" Base="BoundDecisionDagNode ">
+    <Field Name="Bindings" Type="ImmutableArray&lt;(BoundExpression left,BoundDagTemp dagTemp)&gt;" Null="disallow"/>
```
Comment (cston) [inline src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml]: >(BoundExpression left,BoundDagTemp dagTemp) [](start = 51, length = 43)

Please consider using uppercase for first character of tuple fields.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs [hunk 5]
```diff
@@ -126,95 +125,171 @@ protected virtual LabelSymbol GetDagNodeLabel(BoundDecisionDag dag)
...
-                // However, some nodes can be emitted more efficiently as a switch dispatch (possibly out
-                // of order).
-                var loweredNodes = PooledHashSet<BoundDecisionDag>.GetInstance();
-                BoundDecisionDag previous = null;
-                foreach (BoundDecisionDag node in sortedNodes)
+                // Note that a when-clause can contain an assignment to a
+                // pattern variable declared in a different when-clause, so we only apply the optimization
+                // of using user-declared pattern variables as pattern-matching automaton temps
+                // when there are no nontrivial when-clauses at all.
+                if (!sortedNodes.OfType<BoundWhenDecisionDagNode>().Where(w => w.WhenExpression != null && w.WhenExpression.ConstantValue != ConstantValue.True).Any())
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs]: >sortedNodes [](start = 21, length = 11)

Consider using `Any` only, to avoid allocations: `sortedNodes.Any(n => { var w = n as BoundWhenDecisionDagNode; return w.WhenExpression != null && ...; })`

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs [hunk 6]
```diff
@@ -252,7 +265,79 @@ protected BoundExpression LowerDecision(BoundDagDecision decision)
...
+            protected void ShareTemps(ImmutableArray<BoundDecisionDagNode> sortedNodes)
+            {
+                if (_loweredInput.Kind == BoundKind.Local || _loweredInput.Kind == BoundKind.Parameter)
+                {
+                    // If we're switching on a local variable and there is no when clause (checked by the caller),
+                    // we assume the value of the local variable does not change during the execution of the
+                    // decision automaton and we just reuse the local variable when we need the input expression.
+                    // It is possible for this assumption to be violated by a side-effecting Deconstruct that
+                    // modifies the local variable which has been captured in a lambda. Since the language assumes
+                    // that the pattern-matching machinery performs no such tomfoolery (functions called by
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: >performs no such tomfoolery [](start = 59, length = 27)

`has no side-effects`?

**Comment by cston** [comment]
>                 if (whenClause.WhenExpression != null && whenClause.WhenExpression.ConstantValue != ConstantValue.True)

When is `BoundWhenDecisionDagNode.WhenExpression == null`?

---
Refers to: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs:424 in 1bb6bc2. [](commit_id = 1bb6bc2beed1bf9c4a8557209f6a43cb1fa6466d, deletion_comment = False)

File: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml (hunk 4 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml]: I prefer to always use lowercase for tuple field names.

**Comment by gafter** [comment]
>                 if (whenClause.WhenExpression != null && whenClause.WhenExpression.ConstantValue != ConstantValue.True)

When there is no when clause but there are pattern variables that have to be assigned.

---
In reply to: [376949965](https://github.com/dotnet/roslyn/pull/25739#issuecomment-376949965) [](ancestors = 376949965)

---
Refers to: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs:424 in 1bb6bc2. [](commit_id = 1bb6bc2beed1bf9c4a8557209f6a43cb1fa6466d, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs [hunk 7]
```diff
@@ -142,7 +141,16 @@ private void LowerDecisionDag(ImmutableArray<BoundDecisionDagNode> sortedNodes)
                         break;
                 }
 
-                // Code for the when clause goes in a separate code section for the switch section.
+                // Note that a when-clause can contain an assignment to a
+                // pattern variable declared in a different when-clause, so we only apply the optimization
+                // of using user-declared pattern variables as pattern-matching automaton temps
+                // when there are no nontrivial when-clauses at all.
+                if (!sortedNodes.OfType<BoundWhenDecisionDagNode>().Where(w => w.WhenExpression != null && w.WhenExpression.ConstantValue != ConstantValue.True).Any())
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs]: I think we could do slightly better here by tracking inside the when clauses to see if a variable is modified or calls something that could modify that variable (local function, etc). This would be rare, but when clauses are probably not so rare.

**Comment by gafter** [comment]
Responses to all comments in this PR have been added to https://github.com/dotnet/roslyn/pull/25767
