### PR TITLE
Bail out on delegate creation wrapped a in tuple operation

### LINKED ISSUE #32903: A variable from tuple deconstruction offers "Use discard" refactoring even when captured in a local function
**Version Used**: 
16.0.0 Preview 2.0

**Steps to Reproduce**:
https://github.com/Tragetaschen/DbusCore/blob/a4c1292b3df5fb8885c94a153e7c82f32019e477/src/Dbus/Decoder.cs#L225
image

**Expected Behavior**:
The "Use discard" should not be offered

**Actual Behavior**:
The "Use discard" code fix creates invalid code.
image

### PR DESCRIPTION
**Pull request by mavasani**
Another case where we need PointsTo analysis for precise flow analysis, we bail out as we currently do not perform any PointsTo analysis.

Fixes #32903

### CODE REVIEW

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs [hunk 1]
```diff
@@ -285,7 +302,17 @@ private bool ShouldAnalyze(IOperation operationBlock, ISymbol owningSymbol)
                         return false;
                     }
 
-                    //  6. Otherwise, we execute analysis by walking the reaching symbol write chain to attempt to
+                    //  6. Bail out if we have a delegate wrapped in a tuple.
+                    //     This indicates the delegate targets (such as lambda/local functions) have been wrapped
+                    //     within a tuple and passed around and invoked, and these invocations can read values written
+                    //     to any local/parameter in the current method. We cannot reliably flag any write to a 
+                    //     local/parameter as unused for such cases.
+                    if (_delegateWrappedInTuple)
```
Comment (genlu) [inline src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs]: We have a few different flags here related to having delegates that might escape, is that possible simplify it by combining them into a single flag?

Comment (mavasani) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs]: I had that initially implemented it with a single flag, but split it out into separate flags for clarity and better documentation.

**Comment by mavasani** [comment]
Thanks @genlu!

@jinujoseph @vatsalyaagrawal for approval
