### PR TITLE
Fix VB incorrectly reported redundant casts in compound assignment statements

### LINKED ISSUE #2560: Wrong Cast is redundant with Option Strict On in VB
In a VB.NET project with Option Strict On the following code with += operator trigger "Cast is redundant" but when apply the fix, the code became broken:
```vb
Dim b As Byte
b += CByte(1) ' IDE0004 Cast is redundant
```
After the fix:
```vb
Dim b As Byte
b += 1 ' Option Strict On disallows implicit conversions from 'Integer' to 'Byte'.
```
This happens with any data type requires explicit conversion.

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes #2560

**Customer Scenario**:

VB remove unnecessary cast reports false positives for common cases with compound assignment where applying the code fix can break the user's code.

*Redundant cast incorrectly reported*:

image

*Error after removing cast*:

image

**Issue Description**:

Consider the following code:

```VB
Dim b As Byte
b += CByte(1)
```

The `CByte` cast can be removed if the Option Strict is Off. However, if Option Strict is On, the compiler produces an error ("Option Strict On disallows implicit conversions from 'Integer' to 'Byte'").

The issue here is that compound statements are not considered by unnecessary cast detection. Unfortunately, supporting is not as straight forward as I'd hoped for a couple of reasons:

1. There is no compiler API to get the built-in operator used by a VB assignment statement. If there were, this would be a straightforward fix since removing the cast results in the compiler choosing `System.Int32.op_Add(Int32, Int32)` rather than `System.Byte.op_Add(Byte, Byte)`.

2. There is a hidden narrowing-numeric conversion of a constant value in the following code:

```VB
b += 1
```

Using the compiler API to classify conversion from the expression `1` to the type of `b` results in a widening-numeric conversion, which is misleading since the type of `1` is `System.Int32` and the type of `b` is `System.Byte`.

**Fix Description**:

Fixing the problem requires two changes:

1. Actually support assignment statements in the speculative analyzer and check to see if replacement would break the compound assignment.
2. Add a special case in the VB speculative analyzer in the case that Option Strict is not Off and the expression has a constant value. In that case, we use a different compiler API to classify *the type of the expression* `1` to the type of `b`, rather than classifying *the expression* `1` to the type of `b`.

**Testing Done**:
* Unit test coverage added for negative and positive cases.

Tagging @dotnet/roslyn-ide

### CODE REVIEW

File: src/EditorFeatures/Test2/Simplification/CastSimplificationTests.vb [hunk 1]
```diff
@@ -7687,7 +7687,7 @@ End Class
 
         <WpfFact, Trait(Traits.Feature, Traits.Features.Simplification)>
         <WorkItem(995855)>
-        Public Sub VisualBasic_Remove_UnnecessaryCastInTernaryExpression()
+        Public Sub VisualBasic_DontRemove_NecessaryCastInTernaryExpression1()
```
Comment (DustinCampbell) [inline src/EditorFeatures/Test2/Simplification/CastSimplificationTests.vb]: Note: This test was simply wrong. Removing either cast to CByte(0) would result in the type of the ternary conditional changing from `Byte` to `Int32`. These should only be marked as redundant if the type of the ternary conditional is already `Int32`.

**Comment by MattGertz** [comment]
Approved pending successful test completion & code reviews.

**Comment by CyrusNajmabadi** [comment]
:+1: 

But could you open bugs to track getting proper VB semantic model APIs to classify statements properly?  Thanks!

**Comment by Pilchie** [comment]
:+1:

**Comment by DustinCampbell** [comment]
Filed #6365 and #6366 to track the VB compiler issues.
