### PR TITLE
VB: Report non-Const locals used in an expression that must have a constant value.

### LINKED ISSUE #49902: Bug VB.NET misses the Error "The expression being assigned to '...' must be constant" and gives the misterious Error BC36970
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Bug-VBNET-misses-the-Error-The-expressi/1165582)._

---
[severity:I'm frustrated, but able to complete my work]

Example:

```
Module Module1

Sub Main()

Dim z As Integer = 2
        Const w As Integer = 2 ^ z

End Sub

End Module
```

Running latest Microsoft Visual Studio Professional 2019 (Version 16.7.2)

No Compiler/IntelliSense Error, not even a Warning.
 
But it fails to build/run with the misterious error:
Error	BC36970	Failed to emit module 'tempTest1.exe': Unable to determine specific cause of the failure.	
 
In my example, that is very simple, is not that hard to find the offending line ("Const w"), that compiles if we change it to "Dim w", but yesterday, on a very larger piece of code, this was not easy to debug.
 
This is a defect (BUG), and I kindly ask you to take a look and fix it.

---
#### Feedback Bot on 8/28/2020, 00:41 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 9/16/2020, 11:27 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #49902.

### CODE REVIEW

File: src/Compilers/VisualBasic/Portable/Binding/Binder_Utils.vb [hunk 1]
```diff
@@ -1330,9 +1331,8 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
                             Dim binaryOperator = DirectCast(boundExpression, BoundBinaryOperator)
                             ' the right side is expected to be shorter for binary operations, so we use
                             ' recursion for this side.
-                            If GetExpressionConstantValueIfAny(binaryOperator.Right, diagnostics, context) Is Nothing Then
-                                nonConstantDetected = True
-                            End If
+                            GetExpressionConstantValueIfAny(binaryOperator.Right, diagnostics, context)
```
Comment (RikkiGibson) [inline src/Compilers/VisualBasic/Portable/Binding/Binder_Utils.vb:1334]: Does this change cause some expressions that used to be considered constant to no longer be considered constant? Do we need breaking change documentation for that?

Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Portable/Binding/Binder_Utils.vb:1334]: > Does this change cause some expressions that used to be considered constant to no longer be considered constant?

Not really. We wouldn't get here if an expression was considered a constant. See the comment right below ```Case BoundKind.BinaryOperator``` and, based on review of the algorithm, I think it is accurate. Given that, unless there is a bug similar to the one I am fixing, an error is going to be reported anyway. What we could end up with before is that, despite an error, a ```ConstantValue``` for a left operand of a binary operator could be returned. That value, clearly, doesn't represent the result of a binary operator itself and perhaps could have wrong type. That probably could affect what our internal structures hold and the constant value that SemanticModel or a symbol reports, but I do not consider that a breaking change. Compiler simply becomes more "accurate" in error scenarios. 

---
In reply to: [540555923](https://github.com/dotnet/roslyn/pull/49912#discussion_r540555923) [](ancestors = 540555923)

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

**Review by cston — APPROVED** [review]

**Review by jaredpar — APPROVED** [review]
