### PR TITLE
Allow the DeclareAsNullable code fix to work for CS8618

### LINKED ISSUE #41869: Build the survey with nullable and non-nullable types
@ericbrunner commented on [Fri Feb 21 2020](https://github.com/dotnet/docs/issues/17159)

Hi 
In VS 2019 the warning is issued when the nullable reference type option is enabled like

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nito.AsyncEx" Version="5.0.0" />
    <PackageReference Include="System.Linq.Async" Version="4.0.0" />
  </ItemGroup>

</Project>
```

for a property like that

`public string QuestionText { get; }
`

But, the `light bulb` das not offer to add the `?` to the type and make it nullable.

For clarification please take a look on that screenshot.

**Actual Behaviour**
A `Configure or Suppress Issue` suggestion. That is counter-intuitive.

**Expected Behaviour**
Refactoring suggestion from VS2019 to declare that property as nullable. 

The warning message clearly says it. 

> Warning	CS8618	Non-nullable property 'QuestionText' is uninitialized. 
> **Consider declaring the property as nullable**.	

nullable_reference_types

Well, currently I notices that on the `is `operator it suggests to declare the reference type as nullable. Could be a tooling issue in Microsoft Visual Studio Community 2019 Version 16.4.5.

nullable_reference_types_suggestion

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b991cba9-efd4-68ae-283a-b575054b4907
* Version Independent ID: 793f790b-e2aa-e292-b12b-f4ba9763f172
* Content: [Design with nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types#next-steps)
* Content Source: [docs/csharp/tutorials/nullable-reference-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/nullable-reference-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---

@BillWagner commented on [Fri Feb 21 2020](https://github.com/dotnet/docs/issues/17159#issuecomment-589713568)

This is a product question / issue.  @jinujoseph where should I move this?

---

@jinujoseph commented on [Fri Feb 21 2020](https://github.com/dotnet/docs/issues/17159#issuecomment-589780051)

@BillWagner can you move this to roslyn repo pls

### PR DESCRIPTION
**Pull request by ryzngard**
Fixes #41869

### CODE REVIEW

**Comment by sharwell** [comment]
@ryzngard Can you double-check the issue number?

**Comment by ryzngard** [comment]
@sharwell  fixed

File: src/EditorFeatures/CSharpTest/Diagnostics/Nullable/CSharpDeclareAsNullableCodeFixTests.cs [hunk 1]
```diff
@@ -950,5 +950,24 @@ void M()
     int this[string x] { get { throw null!; } set { throw null!; } }
 }", parameters: s_nullableFeature);
         }
+
+        [Fact]
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Diagnostics/Nullable/CSharpDeclareAsNullableCodeFixTests.cs:954]: workitem
