### PR TITLE
Fix Selection Tracking In Rename

### LINKED ISSUE #63933: Selection overflows to next line during rename
**Version Used**: Version 17.4.0 Preview 3.0 [32911.17.main]

See GIF. I have the new "Selection Matches" feature turns on, but this repros with it off too

RenameSelection

### PR DESCRIPTION
**Pull request by ryzngard**
Fixes #63933

### CODE REVIEW

File: src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs [hunk 1]
```diff
@@ -389,6 +389,11 @@ private void OnWorkspaceChanged(object sender, WorkspaceChangeEventArgs args)
         {
             if (args.Kind != WorkspaceChangeKind.DocumentChanged)
             {
+                Logger.Log(FunctionId.Rename_InlineSession_Cancel_WorkspaceChanged, KeyValueLogMessage.Create(m =>
```
Comment (ryzngard) [inline src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs:392]: While I was here I've seen bugs about rename dismissing without any user interaction. I _believe_ this is the cause, but this will help track down more accurately.

File: src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyout.xaml.cs [hunk 2]
```diff
@@ -200,5 +201,15 @@ private void ToggleExpand(object sender, RoutedEventArgs e)
         {
             _viewModel.IsExpanded = !_viewModel.IsExpanded;
         }
+
+        private void IdentifierTextBox_SelectionChanged(object sender, RoutedEventArgs e)
+        {
+            var start = IdentifierTextBox.SelectionStart;
+            var length = IdentifierTextBox.SelectionLength;
+
+            var textStartPoint = _viewModel.InitialTrackingSpan.GetStartPoint(_textView.TextSnapshot);
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyout.xaml.cs:210]: small concert about using TextSnapshot here.  does this work for projection buffers?  do you have the actual subject buffer we're applying to?

(note: this may be irrelevant if everything here expects to work at that layer.  but it's a bit suspect compared to normal roslyn patterns for view/buffers/snapshots).

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs [hunk 3]
```diff
@@ -589,6 +589,7 @@ internal enum FunctionId
 
         // 670-680 for newer rename ids
         Rename_TryApplyRename_WorkspaceChanged = 670,
+        Rename_InlineSession_Cancel_WorkspaceChanged = 671,
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Log/FunctionId.cs:592]:
```suggestion
        Rename_InlineSession_Cancel_NonDocumentWorkspaceChanged = 671,
```

nit.

File: src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyout.xaml.cs [hunk 4]
```diff
@@ -200,5 +201,15 @@ private void ToggleExpand(object sender, RoutedEventArgs e)
         {
             _viewModel.IsExpanded = !_viewModel.IsExpanded;
         }
+
+        private void IdentifierTextBox_SelectionChanged(object sender, RoutedEventArgs e)
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyout.xaml.cs:205]: nit: consider doc'ing.

**Review by CyrusNajmabadi — APPROVED** [review]
lgtm, presuming the TextView top buffer vs subject buffer logic is correct.  Thanks for looking into this!

**Comment by DoctorKrolic** [comment]
This also fixes https://github.com/dotnet/roslyn/issues/64676, right?

**Comment by ryzngard** [comment]
> This also fixes #64676, right?

Yup!

File: src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyout.xaml.cs (hunk 2 above)
Comment (ryzngard) [reply src/EditorFeatures/Core.Wpf/InlineRename/UI/Adornment/RenameFlyout.xaml.cs]: Verified, and changed to use the same buffer the `InitialTrackingSpan` was created with. That will make sure we're doing the right thing with projection buffers
