### PR TITLE
Update naming style code fix to support underscore between words

### LINKED ISSUE #22754: Naming style code fix does not insert underscores between words
**Version Used**: 15.5 preview 1

**Steps to Reproduce**:

Create a style definition for a common test naming style.

1. Add an `.editorconfig` file with the following:

```ini
[*.cs] 
dotnet_naming_rule.public_methods_all_lowercase_with_underscores.symbols= public_methods
dotnet_naming_rule.public_methods_all_lowercase_with_underscores.style = lowercase_with_underscores
dotnet_naming_rule.public_methods_all_lowercase_with_underscores.severity = error

dotnet_naming_symbols.public_methods.applicable_kinds = method
dotnet_naming_symbols.public_methods.applicable_accessibilities = public

dotnet_naming_style.lowercase_with_underscores.capitalization  = all_lower
dotnet_naming_style.lowercase_with_underscores.word_separator = _
```

2. Have code like the following:

```C#
class C
{
    public void ThisIsMyMethod()
    {
    }
}
```

3. Apply fix for naming style violation

**Expected Behavior**:

Method name is changed to all lowercase with underscores: `this_is_my_method`.

**Actual Behavior**:

Method name is changed to all lowercase with common underscores: `thisismymethod`.

image

### PR DESCRIPTION
**Pull request by 06needhamt**
Fixes #22754 

This can also be done to fix the same bug with AllUpper if required see #22832

### CODE REVIEW

File: src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs [hunk 1]
```diff
@@ -313,7 +314,10 @@ private string FinishFixingName(string name)
             {
                 words = name.Split(new[] { WordSeparator }, StringSplitOptions.RemoveEmptyEntries);
             }
-
+            if(CapitalizationScheme == Capitalization.AllLower && !string.IsNullOrEmpty(WordSeparator))
```
Comment (DustinCampbell) [inline src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs]: nit: space after `if`

File: src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs [hunk 2]
```diff
@@ -313,7 +314,10 @@ private string FinishFixingName(string name)
...
+            {
+                words = Regex.Split(name, @"(?<!^)(?=[A-Z])");
+            }
             words = ApplyCapitalization(words);
```
Comment (DustinCampbell) [inline src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs]: nit: blank line after `}`

**Comment by DustinCampbell** [comment]
Note: The test failures are real. It looks like `Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.UnitTests.NamingStyleTests.TestAllLowerNoncomplianceWithNoncapitalizationOfSomeWords` fails.

File: src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs [hunk 3]
```diff
@@ -313,7 +314,10 @@ private string FinishFixingName(string name)
             {
                 words = name.Split(new[] { WordSeparator }, StringSplitOptions.RemoveEmptyEntries);
             }
-
+            if(CapitalizationScheme == Capitalization.AllLower && !string.IsNullOrEmpty(WordSeparator))
+            {
+                words = Regex.Split(name, @"(?<!^)(?=[A-Z])");
```
Comment (DustinCampbell) [inline src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs]: I believe we already have code in Roslyn that splits identifiers into "words"

Comment (DustinCampbell) [reply src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs]: @dotnet/roslyn-ide  : I'm not finding that API. Does anyone know which I'm thinking of?

Comment (DustinCampbell) [reply src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs]: Also, @CyrusNajmabadi

Comment (rchande) [reply src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs]: http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Shared/Utilities/StringBreaker.cs,e4e6edc6966e2d2f

**Comment by 06needhamt** [comment]
The tests now pass without problems on my machine

File: src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs [hunk 4]
```diff
@@ -314,6 +315,14 @@ private string FinishFixingName(string name)
                 words = name.Split(new[] { WordSeparator }, StringSplitOptions.RemoveEmptyEntries);
             }
 
+            if (CapitalizationScheme == Capitalization.AllLower && !string.IsNullOrEmpty(WordSeparator))
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs]: Remove the second check and put inside the block above?

File: src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs [hunk 5]
```diff
@@ -314,6 +315,14 @@ private string FinishFixingName(string name)
...
+            {
+                if (words.Count() == 1) // Only Split if words have not been split before
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs]: I think we can get away with making the `IEnumerable<string>` into `IList<string>` and then avoid the extension method. Yeah, it'll do the casting under the covers but no reason to waste the time.

**Comment by jasonmalinowski** [comment]
Should we get a test added for this?

File: src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs (hunk 5 above)
Comment (DustinCampbell) [reply src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs]: Actually, don't all of these return string arrays?

File: src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs [hunk 6]
```diff
@@ -314,6 +315,14 @@ private string FinishFixingName(string name)
                 words = name.Split(new[] { WordSeparator }, StringSplitOptions.RemoveEmptyEntries);
             }
 
+            if (CapitalizationScheme == Capitalization.AllLower && !string.IsNullOrEmpty(WordSeparator))
+            {
+                if (words.Count() == 1) // Only Split if words have not been split before 
+                {
+                    words = Regex.Split(name, @"(?<!^)(?=[A-Z])");
```
Comment (DustinCampbell) [inline src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs]: Could we use `Microsoft.CodeAnalysis.Shared.Utilities.StringBreaker` instead of `Regex`

File: src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs (hunk 4 above)
Comment (06needhamt) [reply src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs]: Done

File: src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs (hunk 6 above)
Comment (06needhamt) [reply src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs]: I'm not familiar with that API as this will be the first issue I have worked on in Roslyn could you point me to the documentation and i will look into it

Comment (06needhamt) [reply src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs]: Done

File: src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs (hunk 5 above)
Comment (06needhamt) [reply src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs]: Not sure I've left it as is for now

**Comment by 06needhamt** [comment]
@jasonmalinowski I just added some tests

File: src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs [hunk 7]
```diff
@@ -312,6 +313,20 @@ private string FinishFixingName(string name)
             if (!string.IsNullOrEmpty(WordSeparator))
             {
                 words = name.Split(new[] { WordSeparator }, StringSplitOptions.RemoveEmptyEntries);
+
+                if (CapitalizationScheme == Capitalization.AllUpper || CapitalizationScheme == Capitalization.AllLower)
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs]: Why just in these two cases? If I had it set to PascalCase and a word separator, don't we still want the same behavior?

File: src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs [hunk 8]
```diff
@@ -312,6 +313,20 @@ private string FinishFixingName(string name)
...
+                {
+                    if (words.Count() == 1) // Only Split if words have not been split before 
+                    {
+                        var parts = StringBreaker.GetParts(name, true);
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs]: For Booleans like this, we'll add a named argument (`foo:`) so it's easier to read.

File: src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs (hunk 7 above)
Comment (06needhamt) [reply src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs]: Done for all cases

File: src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs (hunk 8 above)
Comment (06needhamt) [reply src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs]: Done

**Comment by 06needhamt** [comment]
I also added more tests to cover all cases

**Comment by sharwell** [comment]
@dotnet-bot retest this please

**Comment by sharwell** [comment]
@dotnet-bot retest windows_debug_unit32_prtest please

**Comment by sharwell** [comment]
@dotnet-bot retest windows_release_unit64_prtest please
