### PR TITLE
IDE0060 doesn't warn about unused params in ISerializable constructors

### LINKED ISSUE #32133: IDE0060 (remove unused parameter) should not fire for deserialization constructor
**Version Used**: 

28502.214.d16.0stg

**Steps to Reproduce**:

```c#
internal sealed class NonSerializable
{
    private readonly string _value;
    public NonSerializable(string value) => _value = value;
    public string Value => _value;
}

[Serializable]
internal sealed class CustomSerializingType : ISerializable
{
    private readonly NonSerializable _nonSerializable;

    public CustomSerializingType(SerializationInfo info, StreamingContext context) // IDE0060 wants to remove 'context'
    {
        _nonSerializable = new NonSerializable(info.GetString("KEY"));
    }

    public void GetObjectData(SerializationInfo info, StreamingContext context)
    {
        info.AddValue("KEY", _nonSerializable.Value);
    }
}
```

**Expected Behavior**:

No diagnostic.

**Actual Behavior**:

Diagnostic.

### PR DESCRIPTION
**Pull request by drewnoakes**
Fixes #32133.

Logic that tests for such constructors is pulled out to a helper struct, `SerializationConstructorCheck`. I couldn't find existing patterns for this kind of thing, so perhaps a different approach is preferred. It cannot be an extension method as it caches symbols from the compilation for reuse across multiple calls.

Fixed some typos too, in a separate commit.

### CODE REVIEW

File: src/Features/Core/Portable/Shared/Utilities/SerializationConstructorCheck.cs [hunk 1]
```diff
@@ -0,0 +1,28 @@
+﻿// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
+
+using Microsoft.CodeAnalysis.Shared.Extensions;
+
+namespace Microsoft.CodeAnalysis.Shared.Utilities
+{
+    internal readonly struct SerializationConstructorCheck
+    {
+        private readonly INamedTypeSymbol _iSerializableType, _serializationInfoType, _streamingContextType;
```
Comment (sharwell) [inline src/Features/Core/Portable/Shared/Utilities/SerializationConstructorCheck.cs]: 💡 

```suggestion
        private readonly INamedTypeSymbol _iSerializableType;
        private readonly INamedTypeSymbol _serializationInfoType;
        private readonly INamedTypeSymbol _streamingContextType;
```

File: src/EditorFeatures/CSharpTest/RemoveUnusedParametersAndValues/RemoveUnusedParametersTests.cs [hunk 2]
```diff
@@ -83,10 +83,10 @@ public async Task Parameter_Unused_NonPrivate_NotApplicable(string typeAccesibil
         [InlineData("internal", "public")]
         [InlineData("internal", "internal")]
         [InlineData("internal", "protected")]
-        public async Task Parameter_Unused_NonPublicMethod(string typeAccesibility, string methodAccessibility)
+        public async Task Parameter_Unused_NonPublicMethod(string typeAccessibility, string methodAccessibility)
         {
             await TestDiagnosticsAsync(
-$@"{typeAccesibility} class C
```
Comment (mavasani) [inline src/EditorFeatures/CSharpTest/RemoveUnusedParametersAndValues/RemoveUnusedParametersTests.cs]: Thanks for fixing the typos!

**Comment by mavasani** [comment]
Tagging @jinujoseph @vatsalyaagrawal for approval

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs [hunk 3]
```diff
@@ -34,12 +36,14 @@ private sealed partial class SymbolStartAnalyzer
...
                 INamedTypeSymbol eventArgsTypeOpt,
-                ImmutableHashSet<INamedTypeSymbol> attributeSetForMethodsToIgnore)
+                ImmutableHashSet<INamedTypeSymbol> attributeSetForMethodsToIgnore,
+                Compilation compilation)
             {
                 _compilationAnalyzer = compilationAnalyzer;
 
                 _eventArgsTypeOpt = eventArgsTypeOpt;
                 _attributeSetForMethodsToIgnore = attributeSetForMethodsToIgnore;
+                _serializationConstructorCheck = new SerializationConstructorCheck(compilation);
```
Comment (sharwell) [inline src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs]: ❓ Can we avoid looking these types up for analysis of _every symbol_, and instead do it once for the compilation?

File: src/Features/Core/Portable/Shared/Utilities/SerializationConstructorCheck.cs [hunk 4]
```diff
@@ -0,0 +1,28 @@
+﻿// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
+
+using Microsoft.CodeAnalysis.Shared.Extensions;
+
+namespace Microsoft.CodeAnalysis.Shared.Utilities
+{
+    internal readonly struct SerializationConstructorCheck
```
Comment (sharwell) [inline src/Features/Core/Portable/Shared/Utilities/SerializationConstructorCheck.cs]: 💡 

```suggestion
    internal readonly struct DeserializationConstructorCheck
```

File: src/Features/Core/Portable/Shared/Utilities/SerializationConstructorCheck.cs [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+        public SerializationConstructorCheck(Compilation compilation)
+        {
+            _iSerializableType = compilation.ISerializableType();
+            _serializationInfoType = compilation.SerializationInfoType();
+            _streamingContextType = compilation.StreamingContextType();
+        }
+
+        // True if the method is a constructor adhereing to the pattern used for custom
+        // deserialisation by types that implement System.Runtime.Serialization.ISerializable
+        public bool IsISerializableConstructor(IMethodSymbol methodSymbol)
```
Comment (sharwell) [inline src/Features/Core/Portable/Shared/Utilities/SerializationConstructorCheck.cs]: 💡 

```suggestion
        public bool IsDeserializationConstructor(IMethodSymbol methodSymbol)
```

File: src/Features/Core/Portable/Shared/Utilities/SerializationConstructorCheck.cs [hunk 6]
```diff
@@ -0,0 +1,28 @@
...
+
+        public SerializationConstructorCheck(Compilation compilation)
+        {
+            _iSerializableType = compilation.ISerializableType();
+            _serializationInfoType = compilation.SerializationInfoType();
+            _streamingContextType = compilation.StreamingContextType();
+        }
+
+        // True if the method is a constructor adhereing to the pattern used for custom
+        // deserialisation by types that implement System.Runtime.Serialization.ISerializable
```
Comment (sharwell) [inline src/Features/Core/Portable/Shared/Utilities/SerializationConstructorCheck.cs]: 💡 

```suggestion
        // deserialization by types that implement System.Runtime.Serialization.ISerializable
```

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs [hunk 7]
```diff
@@ -191,7 +195,8 @@ private bool IsUnusedParameterCandidate(IParameterSymbol parameter)
                     !method.ExplicitOrImplicitInterfaceImplementations().IsEmpty ||
                     method.IsAccessor() ||
                     method.IsAnonymousFunction() ||
-                    _compilationAnalyzer.MethodHasHandlesClause(method))
+                    _compilationAnalyzer.MethodHasHandlesClause(method) ||
+                    _serializationConstructorCheck.IsISerializableConstructor(method))
```
Comment (sharwell) [inline src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs]: 💡 

```suggestion
                    _deserializationConstructorCheck.IsDeserializationConstructor(method))
```

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs (hunk 3 above)
Comment (sharwell) [inline src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs]: 💡 

```suggestion
                _deserializationConstructorCheck = new DeserializationConstructorCheck(compilation);
```

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs [hunk 8]
```diff
@@ -22,6 +23,7 @@ private sealed partial class SymbolStartAnalyzer
 
             private readonly INamedTypeSymbol _eventArgsTypeOpt;
             private readonly ImmutableHashSet<INamedTypeSymbol> _attributeSetForMethodsToIgnore;
+            private readonly SerializationConstructorCheck _serializationConstructorCheck;
```
Comment (sharwell) [inline src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs]: 💡 

```suggestion
            private readonly DeserializationConstructorCheck _deserializationConstructorCheck;
```

File: src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs [hunk 9]
```diff
@@ -563,7 +563,7 @@ private bool IsCandidateSymbol(ISymbol memberSymbol)
                                     // ISerializable constructor is invoked by the runtime for deserialization
                                     // and it is a common pattern to have a private serialization constructor
                                     // that is not explicitly referenced in code.
-                                    if (IsISerializableConstructor(methodSymbol))
+                                    if (_serializationConstructorCheck.IsISerializableConstructor(methodSymbol))
```
Comment (sharwell) [inline src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: 💡 

```suggestion
                                    if (_deserializationConstructorCheck.IsDeserializationConstructor(methodSymbol))
```

File: src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs [hunk 10]
```diff
@@ -83,9 +85,7 @@ private sealed class CompilationAnalyzer
                 _debuggerDisplayAttributeType = compilation.DebuggerDisplayAttributeType();
                 _structLayoutAttributeType = compilation.StructLayoutAttributeType();
                 _eventArgsType = compilation.EventArgsType();
-                _iSerializableType = compilation.ISerializableType();
-                _serializationInfoType = compilation.SerializationInfoType();
-                _streamingContextType = compilation.StreamingContextType();
+                _serializationConstructorCheck = new SerializationConstructorCheck(compilation);
```
Comment (sharwell) [inline src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: 💡 

```suggestion
                _deserializationConstructorCheck = new DeserializationConstructorCheck(compilation);
```

File: src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs [hunk 11]
```diff
@@ -64,7 +65,8 @@ private sealed class CompilationAnalyzer
             private readonly object _gate;
             private readonly Dictionary<ISymbol, ValueUsageInfo> _symbolValueUsageStateMap;
             private readonly INamedTypeSymbol _taskType, _genericTaskType, _debuggerDisplayAttributeType, _structLayoutAttributeType;
-            private readonly INamedTypeSymbol _eventArgsType, _iSerializableType, _serializationInfoType, _streamingContextType;
+            private readonly INamedTypeSymbol _eventArgsType;
+            private readonly SerializationConstructorCheck _serializationConstructorCheck;
```
Comment (sharwell) [inline src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: 💡 

```suggestion
            private readonly DeserializationConstructorCheck _deserializationConstructorCheck;
```

File: src/Features/Core/Portable/Shared/Utilities/SerializationConstructorCheck.cs (hunk 4 above)
Comment (sharwell) [inline src/Features/Core/Portable/Shared/Utilities/SerializationConstructorCheck.cs]: Unfortunately I can use the GitHub suggested changes feature to rename this file, so even though the rest of the changes can be automated the rename will need to be done manually.

File: src/EditorFeatures/CSharpTest/RemoveUnusedParametersAndValues/RemoveUnusedParametersTests.cs (hunk 2 above)
Comment (drewnoakes) [reply src/EditorFeatures/CSharpTest/RemoveUnusedParametersAndValues/RemoveUnusedParametersTests.cs]: No problem. I introduced on of my own actually (fixed in d7c0209080b27429195f0f7390bf06eda640341c) 😃

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs (hunk 3 above)
Comment (drewnoakes) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs]: Good idea. Fixed in 7898c2d97af61d4161c1c7942d420dfad9d71fe8.

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs [hunk 12]
```diff
@@ -34,12 +36,14 @@ private sealed partial class SymbolStartAnalyzer
             public SymbolStartAnalyzer(
                 AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer compilationAnalyzer,
                 INamedTypeSymbol eventArgsTypeOpt,
-                ImmutableHashSet<INamedTypeSymbol> attributeSetForMethodsToIgnore)
+                ImmutableHashSet<INamedTypeSymbol> attributeSetForMethodsToIgnore,
+                in DeserializationConstructorCheck deserializationConstructorCheck)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs]: this being 'in' seems unnecessary.  the copy is going to happen below anyways.

Comment (drewnoakes) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs]: Doesn't this result in one fewer copies though?

File: src/Features/Core/Portable/Shared/Utilities/DeserializationConstructorCheck.cs [hunk 13]
```diff
@@ -0,0 +1,30 @@
+﻿// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
+
+using Microsoft.CodeAnalysis.Shared.Extensions;
+
+namespace Microsoft.CodeAnalysis.Shared.Utilities
+{
+    internal readonly struct DeserializationConstructorCheck
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Shared/Utilities/DeserializationConstructorCheck.cs]: is there a huge benefit to this type, versus just having an extension method on `Compilation` to do this?

**Comment by drewnoakes** [comment]
@sharwell I did the renaming in a single commit rather than leaving non-compiling commits (4f3c7e8d3c8bbfea40b53394938908003acf3f55).

Also used destructuring of KVP in a39a93beef933c5a6e38113358add58f599cecea.

**Comment by CyrusNajmabadi** [comment]
Please do not force-push PRs.  It means that comments someone is in the middle of cannot be posted.  I lost a bunch of comments this way and now have to start over in the review :-/   Also, it makes reviewing commit-by-commit extremely difficult.

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs (hunk 12 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs]: i don't see the value in that sort of microoptimization.  Is a copy a problem that needs to be avoided?

**Comment by drewnoakes** [comment]
> Please do not force-push PRs

Apologies. They were only up for a few seconds. You're fast!

How does merging happen here? Are PRs generally squash merged?

**Comment by CyrusNajmabadi** [comment]
> How does merging happen here? Are PRs generally squash merged?

Up to the committer.  Some people like to squash.  Others merge.  Others rebase.  The team has no requirement here.  My preference is just merging.  I have to go back enough to older PRs of mine that i like having the breakdown of commits to help me understand things better.

File: src/Features/Core/Portable/Shared/Utilities/DeserializationConstructorCheck.cs (hunk 13 above)
Comment (drewnoakes) [reply src/Features/Core/Portable/Shared/Utilities/DeserializationConstructorCheck.cs]: I hinted at this in the PR description:

> It cannot be an extension method as it caches symbols from the compilation for reuse across multiple calls.

"Cannot" isn't strictly true. Of course it can. But that would end up being three lookups per symbol, rather than three per compilation. Do you prefer an extension method here all the same?

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs (hunk 12 above)
Comment (drewnoakes) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs]: No, this is called once per compilation. I've removed it.

File: src/Features/Core/Portable/Shared/Utilities/DeserializationConstructorCheck.cs (hunk 13 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/Shared/Utilities/DeserializationConstructorCheck.cs]: > "Cannot" isn't strictly true. Of course it can. But that would end up being three lookups per symbol, rather than three per compilation. Do you prefer an extension method here all the same?

I would.  Three lookups seems like nothing... especially since Compilations cache these calls to GetTypeByMetadataName.  Now, if we had perf data indicating a cost here, i would feel differently.

*That said*: i'm not opposed to this PR in this form.  So don't go changing it for me :)   I was just pointing out that a bunch of this felt like premature-optimization territory, and i'd prefer to avoid that as a general principle.  But, there's nothing wrong with this work at all, and you've gotten it this far, so i'm totally ok taking as-is :)

Comment (drewnoakes) [reply src/Features/Core/Portable/Shared/Utilities/DeserializationConstructorCheck.cs]: I admit I hadn't looked at how the symbols were resolved. That does appear to be pretty inexpensive.

Would you define such an extension method on `ISymbolExtensions`?

@mavasani you mentioned porting this code in https://github.com/dotnet/roslyn/issues/32133#issuecomment-451255084. How do you see this?

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/Shared/Utilities/DeserializationConstructorCheck.cs]: > Would you define such an extension method on ISymbolExtensions?

That would be reasonable :)

Comment (mavasani) [reply src/Features/Core/Portable/Shared/Utilities/DeserializationConstructorCheck.cs]: Normally, we recommend caching well known types per-compilation in the analyzers, especially if only the analyzer needs a well known type. I am personally fine with all the three approaches here (your original approach, Sam's recommended approach and Cyrus' recommended approach) - we can always tune it if we see performance issues, which seem unlikely given GetTypeByMetadataName does cache.

**Comment by sharwell** [comment]
> Please do not force-push PRs. It means that comments someone is in the middle of cannot be posted.

This should not be the case with the new force-push support from GitHub. Can you send me a detailed set of steps that results in a lost comment so I can file a bug report?

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs [hunk 14]
```diff
@@ -50,13 +54,14 @@ private sealed partial class SymbolStartAnalyzer
             {
                 var attributeSetForMethodsToIgnore = ImmutableHashSet.CreateRange(GetAttributesForMethodsToIgnore(context.Compilation).WhereNotNull());
                 var eventsArgType = context.Compilation.EventArgsType();
+                var serializationConstructorCheck = new DeserializationConstructorCheck(context.Compilation);
```
Comment (sharwell) [inline src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs]: 💡 

```suggestion
                var deserializationConstructorCheck = new DeserializationConstructorCheck(context.Compilation);
```

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs [hunk 15]
```diff
@@ -50,13 +54,14 @@ private sealed partial class SymbolStartAnalyzer
...
                 context.RegisterSymbolStartAction(symbolStartContext =>
                 {
                     // Create a new SymbolStartAnalyzer instance for every named type symbol
                     // to ensure there is no shared state (such as identified unused parameters within the type),
                     // as that would lead to duplicate diagnostics being reported from symbol end action callbacks
                     // for unrelated named types.
-                    var symbolAnalyzer = new SymbolStartAnalyzer(analyzer, eventsArgType, attributeSetForMethodsToIgnore);
+                    var symbolAnalyzer = new SymbolStartAnalyzer(analyzer, eventsArgType, attributeSetForMethodsToIgnore, serializationConstructorCheck);
```
Comment (sharwell) [inline src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs]: 💡 

```suggestion
                    var symbolAnalyzer = new SymbolStartAnalyzer(analyzer, eventsArgType, attributeSetForMethodsToIgnore, deserializationConstructorCheck);
```

**Comment by CyrusNajmabadi** [comment]
> This should not be the case with the new force-push support from GitHub. Can you send me a detailed set of steps that results in a lost comment so I can file a bug report?

I was writing up comments for the PR.  i tried to submit them.  I got some sort of "cannot find OID" message from github.  

> The two force-push events in the timeline above seem to be the intended use for such a feature

This only works if you use the "conversation" tab for tracking commits.  I do not as i find it super hard to actually work with a timeline that intersperses long discussions with commit notifications.  Instead, i use the "commits" tab, since it's simple and easy to just walk through the commits and pick up where you left off.  However, when a force-push happens, all that info is lost and you have to start all over again from the beginning since you don't know how the 'force' actually affected previous things you reviewed.

File: src/Features/Core/Portable/Shared/Utilities/DeserializationConstructorCheck.cs (hunk 13 above)
Comment (sharwell) [reply src/Features/Core/Portable/Shared/Utilities/DeserializationConstructorCheck.cs]: GetTypeByMetadataName only caches the most recently used 50 items. The current approach doesn't seem to have a real downside and saves those 50 slots for extension analyzers.

**Comment by mavasani** [comment]
@drewnoakes Is this ready to merge?

@jinujoseph for approval

**Comment by jinujoseph** [comment]
holding till we snap for preview2

**Comment by drewnoakes** [comment]
> @drewnoakes Is this ready to merge?

I'm happy for this to be merged once approved. Thanks.
