### PR TITLE
Fix connection issues in server

### LINKED ISSUE #2866: Fix the issue in CheckConnectionTask
The `CheckConnectionTask` method in the compiler server [is asserting](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/VBCSCompiler/ServerDispatcher.cs#L287) in Debug builds of the compiler.  This assertion is not definitive but happening with decent regularity during both builds and running of the unit tests.  

``` csharp
Debug.Assert(current.ChangeKeepAliveTask == null);
```

This code is being disabled for the moment to get Jenkins unstuck but needs to be investigated and fixed.

### PR DESCRIPTION
**Pull request by jaredpar**
This addresses the following issues:

- GitHub #2866: Asserts in the check connection loop.
- DevDiv 1175084: Crashes when server is unable to complete the connection to the named pipe.

These issues are being addressed together because they stem from the same
underlying problem.  The code is not fulfilling two of the main invariants
of connection processing in the server:

- The `Task` representing a client connection should never throw an exception.
Failed connections are instead represented by the data returned from the `Task`.
- A connection should always provide a new timeout value before completing the
compilation process.

The `Connection` type is responsible for the majority of the processing here
and is careful to maintain these invariants.  The `ServerDispatcher` type though
didn't fully account for exceptions.  This meant that errors actually completing
the `NamedPipeClientStream` connection ended up violating both of the core
invariants.

The solution here is two fold:

1. Properly handle the exceptional cases that can come from completing the named
pipe connection.
2. Use a single `Task` to represent a client connection instead of a separate one
for the compilation and keep alive.

close #2866

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @agocke @pharring @VSadov

File: src/Compilers/Core/VBCSCompiler/ServerDispatcher.cs [hunk 1]
```diff
@@ -154,15 +142,15 @@ public ServerDispatcher(IRequestHandler handler, IDiagnosticListener diagnosticL
         /// test framework.  The code hooks <see cref="AppDomain.AssemblyResolve"/> in a way
         /// that prevents xUnit from running correctly and hence must be disabled. 
         /// </remarks>
-        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2001:AvoidCallingProblematicMethods", 
-            MessageId = "System.GC.Collect", 
-            Justification ="We intentionally call GC.Collect when anticipate long period on inactivity.")]
+        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2001:AvoidCallingProblematicMethods",
+            MessageId = "System.GC.Collect",
+            Justification = "We intentionally call GC.Collect when anticipate long period on inactivity.")]
```
Comment (pharring) [inline src/Compilers/Core/VBCSCompiler/ServerDispatcher.cs]: Nit: 'of' not 'on'. i.e. "...long period of inactivity."

**Comment by MattGertz** [comment]
Approved 5/22 by ML Shiproom.

File: src/Compilers/Core/VBCSCompiler/ServerDispatcher.cs [hunk 2]
```diff
@@ -407,15 +385,27 @@ private void ChangeKeepAlive(Task<TimeSpan?> task, ref TimeSpan? keepAlive, ref
...
-            var connection = new Connection(clientConnection, _handler);
-            return await connection.ServeConnection(changeKeepAliveSource, cancellationToken).ConfigureAwait(false);
+            Connection connection;
+            try
+            {
+                var pipeStream = await pipeStreamTask.ConfigureAwait(false);
+                var clientConnection = new NamedPipeClientConnection(pipeStream);
+                connection = new Connection(clientConnection, handler);
+            }
+            catch
```
Comment (agocke) [inline src/Compilers/Core/VBCSCompiler/ServerDispatcher.cs]: Do we want to log this?

**Comment by agocke** [comment]
LGTM. The logging could be useful in diagnosing issues, but isn't necessary.
