### PR TITLE
Lookup for new well-known types to fail if duplicates are found

### LINKED ISSUE #11322: Tuple literals should not be allowed if the corresponding VT cannot be unambiguously looked up.
Based on the latest LDM decision:
- Tuple literals are not allowed if the corresponding VT cannot be unambiguously looked up.

I'll submit unit-tests shortly. The tests are passing right now because they reflect existing behavior, but comments are indicating places that should change behavior according to the decision above.

### LINKED ISSUE #11327: We should require uniqueness of well known types over picking an arbitrary one for types added for C# 7 and later versions.
This is about WRN_MultiplePredefTypes warning. For new types, that warning shouldn't be reported, the lookup should fail instead.

### PR DESCRIPTION
**Pull request by jcouv**
The lookup for well-known types currently succeeds (with a `WRN_MultiplePredefTypes` warning) when more than one candidate is found.
Per LDM discussion last week, well-known types introduced with C# 7 or later will adopt a stricter behavior. Their lookup will fail if the result is ambiguous.

Overview: 
This change introduces `CSharp7Sentinel` as a marker in the `WellKnownType` enum. The `GetWellKnownType` method passes a new `allowAmbiguity` flag during the lookup. 
The method that used to issue a warning, now could generate an error.
Also, to fix #11322, we'll lookup the proper VT types even for tuple literals that don't have a natural type.

I didn't have to add a test to verify the old behavior (for old well-known types), as we already have a couple.

Fixes #11327 and #11322

CC @dotnet/roslyn-compiler for review.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Errors/ErrorCode.cs [hunk 1]
```diff
@@ -1391,5 +1391,6 @@ internal enum ErrorCode
         ERR_TupleExplicitNamesOnAllMembersOrNone = 8204,
 
         ERR_PredefinedTypeMemberNotFoundInAssembly = 8205,
+        ERR_PredefinedTypeNotUniquelyFound = 8206,
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Errors/ErrorCode.cs]: Perhaps `ERR_PredefinedTypeAmbiguous` or `ERR_AmbiguousPredefinedType`.

Comment (jcouv) [inline src/Compilers/CSharp/Portable/Errors/ErrorCode.cs]: @cston Hold on on further review. From discussion with Aleksey just now, I am making a significant simplification. We'll return null instead and not introduce a new error.

**Comment by jcouv** [comment]
@cston Just pushed the simplification I mentioned. Re-using existing error message is ok, although a little bit less informative.

File: src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs [hunk 2]
```diff
@@ -97,8 +97,18 @@ internal NamedTypeSymbol GetWellKnownType(WellKnownType type)
                 }
                 else
                 {
-                    result = this.Assembly.GetTypeByMetadataName(
-                        mdName, includeReferences: true, useCLSCompliantNameArityEncoding: true, isWellKnownType: true, warnings: warnings);
+                    if (type <= WellKnownType.CSharp7Sentinel)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs]: Consider using conditional on `warnings` parameter in call: `warnings: (type < Sentinel) ? null : warnings`.

File: src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs [hunk 3]
```diff
@@ -369,6 +369,33 @@ private static NamedTypeSymbol GetTupleUnderlyingType(ImmutableArray<TypeSymbol>
...
+        /// For tuples with no natural type, we still need to verify that an underlying type of proper arity exists, and report if otherwise.
+        /// </summary>
+        internal static void VerifyTupleTypePresent(int cardinality, CSharpSyntaxNode syntax, CSharpCompilation compilation, DiagnosticBag diagnostics)
+        {
+            int remainder;
+            int chainLength = NumberOfValueTuples(cardinality, out remainder);
+
+            NamedTypeSymbol firstTupleType = compilation.GetWellKnownType(GetTupleType(remainder));
+
+            if ((object)diagnostics != null && (object)syntax != null)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs]: It feels like the whole purpose of this method is to report errors when types are missing. Consider asserting that diagnostics is not null on entry and dropping the null checks.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs]: Same for syntax.

---
In reply to: [63761762](https://github.com/dotnet/roslyn/pull/11389#discussion_r63761762) [](ancestors = 63761762)

File: src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs [hunk 4]
```diff
@@ -369,6 +369,33 @@ private static NamedTypeSymbol GetTupleUnderlyingType(ImmutableArray<TypeSymbol>
...
+
+            if (chainLength > 1)
+            {
+                NamedTypeSymbol chainedTupleType = compilation.GetWellKnownType(GetTupleType(RestPosition));
+
+                if ((object)diagnostics != null && (object)syntax != null)
+                {
+                    Binder.ReportUseSiteDiagnostics(chainedTupleType, diagnostics, syntax);
+
+                }
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs]: An unnecessary empty line above.

File: src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs [hunk 5]
```diff
@@ -572,6 +572,233 @@ public void AllWellKnownTypes()
...
+            Assert.True(WellKnownType.System_Runtime_CompilerServices_AsyncTaskMethodBuilder_T <= WellKnownType.CSharp7Sentinel);
+            Assert.True(WellKnownType.System_Runtime_CompilerServices_AsyncStateMachineAttribute <= WellKnownType.CSharp7Sentinel);
+            Assert.True(WellKnownType.System_Runtime_CompilerServices_IteratorStateMachineAttribute <= WellKnownType.CSharp7Sentinel);
+
+            Assert.True(WellKnownType.System_Windows_Forms_Form <= WellKnownType.CSharp7Sentinel);
+            Assert.True(WellKnownType.System_Windows_Forms_Application <= WellKnownType.CSharp7Sentinel);
+
+            Assert.True(WellKnownType.System_Environment <= WellKnownType.CSharp7Sentinel);
+
+            Assert.True(WellKnownType.System_Runtime_GCLatencyMode <= WellKnownType.CSharp7Sentinel);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs]: Are all members in WellKnownType tightly packed? Consider asserting actual difference between First and CSharp7Sentinel in order to make sure that none of the new types are inserted into the range.

Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs]: ```foreach (var type = new [] { WellKnownType.System_Math, ..., WellKnownType.GCLatencyMode }) Assert.True(type ...);```

**Comment by AlekseyTs** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs (hunk 2 above)
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs]: I left this one as-is because I found it hard to read.

File: src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs (hunk 3 above)
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs]: Done. Thanks

File: src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs (hunk 4 above)
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs]: Removed

File: src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs (hunk 2 above)
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs]: Duplicating the line means the reader has to spot the differences between the two and also increases the chance the two cases will get out of sync.

Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs]: That's a good point. Would introducing a local be ok?

**Comment by VSadov** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs (hunk 2 above)
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs]: Sounds good, thanks.

File: src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs (hunk 5 above)
Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs]: Done and done.

This made me wonder. Should there be a similar change for special types too?

**Comment by cston** [comment]
LGTM

**Comment by jcouv** [comment]
Thanks for the review.
The latest commit I pushed addressed the suggestions. 

As Aleksey suggested, I copied the list of well-known types from `master` branch (authority on CSharp6) and found that one type had already moved. This is corrected now.

**Comment by AlekseyTs** [comment]
LGTM

File: src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs (hunk 5 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs]: I don't think they were ever affected. There could be no ambiguity with special types because they are always looked up in one assembly.

Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/Symbols/MissingSpecialMember.cs]: Makes sense. Thanks
