### PR TITLE
Qualify member accesses with type name in nameof

### LINKED ISSUE #1193: Rename resolves NameOf conflict with erroneous "this"
In the following example, when "z" is renamed to "Fail", the ambiguity within the nameof is resolved by qualifying "Fail" with "this.". This is invalid, since F is static.

```C#
class C
{
    // Rename z to Fail
    static void F(int z)
    {
        string x = nameof(Fail);
    }

    int Fail;
}

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #1193

During expansion, directly accessed members need to be qualified with
"this." or "TypeName.". Prior to this change, we always qualified
instance members with "this." and static members with "TypeName.", but
this technique fails in nameof contexts where an instance member can be
referenced from a static method, resulting in an improper "this."
qualification. We can only legally use "this." when both the member
being accessed and the context from which we are accessing it are
non-static. However, this change updates the expanders to always use
"TypeName." qualification in nameof contexts regardless of the
staticness of either member because it is always legal and feels more
natural in nameof expressions (where no actual value is being accessed).

### CODE REVIEW

File: src/EditorFeatures/Test2/Rename/RenameEngineTests.vb [hunk 1]
```diff
@@ -2723,7 +2723,7 @@ End Class
 
         <WorkItem(866094)>
         <Fact, Trait(Traits.Feature, Traits.Features.Rename)>
-        Public Sub Bug866094_DaveTest()
+        Public Sub Bug866094()
```
Comment (dpoeschl) [inline src/EditorFeatures/Test2/Rename/RenameEngineTests.vb]: Just sneaking in an embarrassing fix. Please look the other way.

**Comment by dpoeschl** [comment]
Tagging potential reviewers: @rchande @balajikris @basoundr @brettfo @jasonmalinowski @Pilchie

File: src/EditorFeatures/Test2/Rename/RenameEngineTests.vb (hunk 1 above)
Comment (Pilchie) [inline src/EditorFeatures/Test2/Rename/RenameEngineTests.vb]: :wink:

**Comment by Pilchie** [comment]
:+1:

**Comment by rchande** [comment]
LGTM

**Comment by basoundr** [comment]
:+1:

File: src/Workspaces/CSharp/Portable/Simplification/CSharpSimplificationService.Expander.cs [hunk 2]
```diff
@@ -507,7 +508,9 @@ private ExpressionSyntax VisitSimpleName(SimpleNameSyntax rewrittenSimpleName, S
                     symbol.Kind == SymbolKind.Field ||
                     symbol.Kind == SymbolKind.Property)
                 {
-                    if (symbol.IsStatic || originalSimpleName.IsParentKind(SyntaxKind.NameMemberCref))
+                    if (symbol.IsStatic ||
+                        originalSimpleName.IsParentKind(SyntaxKind.NameMemberCref) ||
```
Comment (jasonmalinowski) [inline src/Workspaces/CSharp/Portable/Simplification/CSharpSimplificationService.Expander.cs]: Are both checks necessary?

Comment (jasonmalinowski) [inline src/Workspaces/CSharp/Portable/Simplification/CSharpSimplificationService.Expander.cs]: Oh, reading is hard.

Comment (dpoeschl) [inline src/Workspaces/CSharp/Portable/Simplification/CSharpSimplificationService.Expander.cs]: :smile:
