### PR TITLE
Ignore explicit interface implementation in naming style

### LINKED ISSUE #49535: IDE1006 false positive for `global` prefix
**Version Used**: 
VS 16.8.1

**Steps to Reproduce**:

Context: 
https://github.com/microsoft/CsWinRT/blob/cca8f405d87f29d0e2b76f298daa8f8a0640047b/WinRT.Runtime/Projections/Bindable.net5.cs#L1386
```csharp
bool global::System.Collections.IList.IsFixedSize
```
Explicit interface implementation with `global` prefix required.

**Expected Behavior**:
No naming style should be triggered.

**Actual Behavior**:
IDE1006: suggests change to `Global::System.Collections.IList.IsFixedSize`.

### PR DESCRIPTION
**Pull request by huoyaoyuan**
Fixes #49535

The diagnostic triggers for `C.X`, which is not marked with interface implementation in `ISymbol`. `C.I.X` is the one marked with interface implementation.

I believe just ignoring everything cannot be referenced by name should be correct.

### CODE REVIEW

File: src/Analyzers/CSharp/Analyzers/NamingStyle/CSharpNamingStyleDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -27,8 +27,9 @@ internal sealed class CSharpNamingStyleDiagnosticAnalyzer : NamingStyleDiagnosti
         // Parameters of positional record declarations should be ignored because they also
         // considered properties, and that naming style makes more sense
         protected override bool ShouldIgnore(ISymbol symbol)
-            => symbol.IsKind(SymbolKind.Parameter)
-            && IsParameterOfRecordDeclaration(symbol.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax());
+            => (symbol.IsKind(SymbolKind.Parameter)
+            && IsParameterOfRecordDeclaration(symbol.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax()))
+            || !symbol.CanBeReferencedByName;
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/NamingStyle/CSharpNamingStyleDiagnosticAnalyzer.cs:32]: this expression is too confusing for me (it mixes `&&` and `||` and `!`).  Can you please make this a normal method with statements.  and then doc each case as to why it should apply.  Thanks!

**Comment by huoyaoyuan** [comment]
Run flaky test again.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks!
