### PR TITLE
Fix VSIX based analyzers installed in the extensions hive

### LINKED ISSUE #6285: VSIX based analyzers don't work in VS2015 Update1 CTP/RC
1. Install a CTP/RC drop of VS2015 Update1
2. Open VS -> New project -> Download the Roslyn compiler SDK
3. Create a C# analyzer + code fix project
4. F5 to start debugging the VSIX project in another instance of VS.
5. Create a C# console application

**Expected:** You see the analyzer diagnostic (Type name 'Program' contains lowercase letters) and code fix to make the name uppercase.
**Got:** Analyzer exception diagnostic that analyzer could not be loaded.

IDE analyzers work fine as they seem to be getting loaded from the PrivateAssemblies folder. User analyzers that get installed in the extensions hive are failing to load.

### PR DESCRIPTION
**Pull request by mavasani**
**Customer scenario:** User installs any VSIX based analyzer into their extensions hive, but the analyzers and fixers from the installed extension don't work.

**Reason:** While making the features layer portable, we changed the analyzer assembly loader for VSIX based analyzers to use the PEReader to get the assembly name for loading the assembly. Prior to that, we used to invoke the desktop API "AssemblyName.GetAssemblyName", which sets the CodeBase property of the returned assembly name to be full path of the assembly. Assembly.Load would attempt to load the ngen'ed image of the assembly, and if it doesn't exist then search will eventually fall back to loading the managed assembly at the CodeBase location. We lost the latter functionality when we made the above change, which causes the assembly loader to fail loading the assembly at the specified full path.

**Fix:** Move the analyzer assembly loader to the non-portable VS diagnostic analyzer provider service. Any host which needs to support VSIX based analyzers must also implement the assembly loader for VSIX analyzers.

**Testing:** Verified that assemblies from VSIX based analyzer extensions get loaded successfully and the diagnostics/code fixes work fine. Also added a unit test to verify that host analyzer manager can load assemblies from custom install paths - verified that test fails prior to this change.

**Fixes #6285**

### CODE REVIEW

**Comment by mavasani** [comment]
@srivatsn @heejaechang @tmeschter @jmarolf @Pilchie

**Comment by jmarolf** [comment]
:+1:

**Comment by mavasani** [comment]
**Update:** I have added a unit test for this scenario. I verified that test fails prior to this change with the same assembly load exception.

**Comment by heejaechang** [comment]
:+1:

File: src/Compilers/Core/Portable/PortableShim.cs [hunk 1]
```diff
@@ -504,6 +504,24 @@ internal static class Assembly
...
+        {
+            private const string TypeName = "System.Reflection.AssemblyName";
+
+            internal static readonly Type Type = ReflectionUtilities.GetTypeFromEither(
+                contractName: $"{TypeName}, {CoreNames.System_Reflection}",
+                desktopName: TypeName);
+
+            private static readonly PropertyInfo CodeBase = Type
+                .GetTypeInfo()
+                .GetDeclaredProperty(nameof(CodeBase));
```
Comment (Pilchie) [inline src/Compilers/Core/Portable/PortableShim.cs]: `CodeBase` is not part of the contract API for CoreFx at https://github.com/dotnet/corefx/blob/master/src/System.Reflection/ref/System.Reflection.cs.  Is it part of whatever implementation that forwards to, such that this will work on CoreCLR?

Our normal pattern for PortableShim is that it's only things that actually supported on both Desktop and CoreCLR, just not included in the portable profile we're currently targeting.

Tagging @tmat, @agocke, and @jaredpar to see if they have suggestions here.

Comment (mavasani) [inline src/Compilers/Core/Portable/PortableShim.cs]: In that case, a better alternative might be to require the workspace host to provide the implementation of the host analyzer assembly loader. [GetHostDiagnosticAnalyzerPackages](http://source.roslyn.io/Microsoft.CodeAnalysis.Features/R/c64619a460b7e1ad.html) API implemented in VS Workspace host should provide the assembly loader for loading the host analyzers (VSIX analyzers). We can then use the prior non-portable implementation of the assembly loader in the VS layer. In future, if we have a CoreCLR based workspace host, that host would be responsible for providing an appropriate analyzer loader. @srivatsn @heejaechang what do you think?

Comment (mavasani) [inline src/Compilers/Core/Portable/PortableShim.cs]: I looked at our current analyzer assembly loaders and all of them are implemented in the non-portable layer - which makes sense as all the analyzer hosts are also in the non-portable layer. I am going to move this particular loader to the VS layer and we can figure out later how to load analyzer assemblies in the portable layer, when such a host exists.

Comment (jaredpar) [inline src/Compilers/Core/Portable/PortableShim.cs]: @Pilchie is correct.  The PortableShim type is meant for only APIs that are available in the portable .Net Core subset.  This way when we move to 4.6 then PortableShim can be deleted entirely.

**Comment by mavasani** [comment]
@Pilchie @jaredpar @jmarolf @heejaechang 

I have update the PR as per the review feedback, below is the new fix:

_**Fix**: Move the analyzer assembly loader to the non-portable VS diagnostic analyzer provider service. Any host which needs to support VSIX based analyzers must also implement the assembly loader for VSIX analyzers._

**Comment by mavasani** [comment]
**NOTE:** prtest/win/dbg/eta is expected to fail as it requires a change in the closed layer.

**Comment by Pilchie** [comment]
:+1:

**Comment by jmarolf** [comment]
:shipit:

**Comment by srivatsn** [comment]
:+1:

**Comment by mavasani** [comment]
@dotnet-bot retest prtest/win/dbg/eta please.

**Comment by mavasani** [comment]
ETA tests pass now, merging this in.
