### PR TITLE
Remove suggestion to upgrade to latest language version

### LINKED ISSUE #23392: Language version upgrade suggests using the language version 'latest'
**Version Used**: 15.5 Preview 4

**Steps to Reproduce**:

1. Define a ref struct
2. Use the code fix to upgrade the project

**Expected Behavior**:

1. A code fix is provided to upgrade the project to either language version '7.2' *or* to the latest language version
2. Applying the code fix adds the property `<LangVersion>7.2</LangVersion>`

**Actual Behavior**:

1. A code fix is provided to upgrade the project to language version 'latest'
2. Applying the code fix for language version 'latest' adds the property `<LangVersion>latest</LangVersion>` to the project

**Additional Details**:

The key underlying problem here is the use of the special value 'latest' in the code fix output. This value exists for backwards compatibility purposes, and should never actually be used in a project. The IDE fails to take the necessary steps to discourage users from using this value.¹

For those wondering, the key problem with the value 'latest' is it results in a project that varies in behavior depending on the current minor version of C# in use. In a multi-user team, once every few months team members are forced to either upgrade all at exactly the same time, or users on the team will start to see IDE assistance related to functionality that only a subset of the team can use successfully. On the other hand, projects specifying a language version by number see a consistent experience even across different versions of the IDE, reducing the customer risk involved with adopting new versions of the IDE.

The easiest fix is to simply remove 'default' and/or 'latest' from the set of fixes offered to the user. An alternative approach would involve offering 'default' and/or 'latest' when they are newer than the required language version, but updating the code fix to substitute the corresponding specific language version when applying the fix.

¹ The options 'default' and 'latest' remain available from the Advanced Build Settings page, and/or can be specified by manually editing the project file. This issue does not suggest changes be made to the availability or behavior of these settings, but merely intends to modify the apparent recommendation to reflect known best practices that apply to the majority user base.

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #23392

This pull request current adopts the "simplest" fix described in the original issue.

### CODE REVIEW

**Comment by sharwell** [comment]
@dotnet/roslyn-ide for review

File: src/Features/CSharp/Portable/UpgradeProject/CSharpUpgradeProjectCodeFixProvider.cs [hunk 1]
```diff
@@ -39,16 +38,7 @@ internal class CSharpUpgradeProjectCodeFixProvider : AbstractUpgradeProjectCodeF
         public override ImmutableArray<string> SuggestedVersions(ImmutableArray<Diagnostic> diagnostics)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/UpgradeProject/CSharpUpgradeProjectCodeFixProvider.cs]: seems like this should just be SuggestedVersion and return just a string/null.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UpgradeProject/CSharpUpgradeProjectCodeFixProvider.cs]: If that happens, it looks like a whole lot of code in the base class gets simplified.

Comment (sharwell) [reply src/Features/CSharp/Portable/UpgradeProject/CSharpUpgradeProjectCodeFixProvider.cs]: 💭 I'm not convinced we won't want to bring back some form of "multiple options" in the future.

File: src/EditorFeatures/CSharpTest/Diagnostics/UpgradeProject/UpgradeProjectTests.cs [hunk 2]
```diff
@@ -69,7 +69,7 @@ void A()
 }",
                 LanguageVersion.CSharp7,
                 new CSharpParseOptions(LanguageVersion.CSharp6),
-                index: 1);
+                index: 0);
```
Comment (jcouv) [inline src/EditorFeatures/CSharpTest/Diagnostics/UpgradeProject/UpgradeProjectTests.cs]: Perhaps remove the `index: 0` parameter in all the modified tests (since no longer useful).

File: src/EditorFeatures/CSharpTest/Diagnostics/UpgradeProject/UpgradeProjectTests.cs [hunk 3]
```diff
@@ -51,7 +51,7 @@ void A()
         var x = [|(1, 2)|];
     }
 }",
-                LanguageVersion.Default,
+                LanguageVersion.Default.MapSpecifiedToEffectiveVersion(),
```
Comment (jcouv) [inline src/EditorFeatures/CSharpTest/Diagnostics/UpgradeProject/UpgradeProjectTests.cs]: I'd remove this test entirely, since duplicate of one below (`UpgradeProjectFromCSharp6ToCSharp7`)

**Comment by Pilchie** [comment]
Approved - thanks!

**Comment by sharwell** [comment]
@jcouv I would value a second look from you since I rewrote this to address the simplification requests.

File: src/EditorFeatures/CSharpTest/Diagnostics/UpgradeProject/UpgradeProjectTests.cs [hunk 4]
```diff
@@ -212,20 +191,19 @@ public class Program
 }
 ",
                 LanguageVersion.CSharp7_1,
-                new CSharpParseOptions(LanguageVersion.CSharp7),
-                index: 0);
+                new CSharpParseOptions(LanguageVersion.CSharp7));
         }
 
-#region C# 7.3
+        #region C# 7.3
```
Comment (jcouv) [inline src/EditorFeatures/CSharpTest/Diagnostics/UpgradeProject/UpgradeProjectTests.cs]: Nit: We have the same problem in compiler code. I thought our preference was to leave regions left-aligned. Can you revert this?

File: src/EditorFeatures/CSharpTest/Diagnostics/UpgradeProject/UpgradeProjectTests.cs [hunk 5]
```diff
@@ -212,20 +191,19 @@ public class Program
...
         [Fact]
-        public async Task UpgradeProjectFromCSharp7_3ToLatest()
+        public async Task UpgradeProjectFromCSharp7_2ToLatest()
```
Comment (jcouv) [inline src/EditorFeatures/CSharpTest/Diagnostics/UpgradeProject/UpgradeProjectTests.cs]: Nit: Test name still seems wrong after latest change.

Comment (sharwell) [reply src/EditorFeatures/CSharpTest/Diagnostics/UpgradeProject/UpgradeProjectTests.cs]: ➡️ Test name is correct

File: src/EditorFeatures/CSharpTest/Diagnostics/UpgradeProject/UpgradeProjectTests.cs (hunk 4 above)
Comment (sharwell) [reply src/EditorFeatures/CSharpTest/Diagnostics/UpgradeProject/UpgradeProjectTests.cs]: ➡️ I was going to revert this change since it was a formatting change outside the intended scope of the PR, but since the current form matches the indentation of the `#endregion` and no other changes are required to the PR, I'm going to leave it.
