### PR TITLE
The subsumption tree must treat an unconstrained type parameter as possibly null.

### LINKED ISSUE #16671: Pattern Matching and Generics types confusion
**Version Used**: Visual Studio 2017 RC

**Steps to Reproduce**:

Here is a piece of code that doesn't compile ([gist](https://gist.github.com/Pvlerick/80f610e67033b434ab949dd60b23add1#file-program01-cs))
```CSharp
static void PatternMatching<TBase, TDerived>(TBase o) where TDerived : TBase
{
    switch (o)
    {
        case TDerived td:
            Console.WriteLine(nameof(TDerived));
            break;
        case TBase tb:
            //Error CS8120  The switch case has already been handled by a previous case.
            Console.WriteLine(nameof(TBase));
            break;
        default:
            break;
    }
}
```
In this case, the compile seems to assume that any TBase is going to be handled by the TDerived case.

Removing the problematic case and leaving only the TDerived case and calling the method with a TBase gives this ([gist](https://gist.github.com/Pvlerick/80f610e67033b434ab949dd60b23add1#file-program02-cs)):
```CSharp
using System;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            var c = new C();
            PatternMatching<C, D>(c);
        }

        static void PatternMatching<TBase, TDerived>(TBase o) where TDerived : TBase
        {
            switch (o)
            {
                case TDerived td:
                    //This is where we end up...
                    Console.WriteLine(nameof(TDerived));
                    //This prints "ConsoleApp2.Program+C"
                    Console.WriteLine(td.GetType());
                    break;
                default:
                    Console.WriteLine("Unmatched");
                    break;
            }
        }

        class C { }
        class D : C { }
    }
}
```
Decompiling this with ILSpy gives this:
```CSharp
// ConsoleApp2.Program
private static void PatternMatching<TBase, TDerived>(TBase o) where TDerived : TBase
{
	TDerived td = o;
	Console.WriteLine("TDerived");
	Console.WriteLine(td.GetType());
}
```
So it seems the compiler emits code that "transforms" a C into a D.

Knowing that the real type is C but that the compiler made it into a D, it's possible to act on it as if it was a D while it's not ([gist](https://gist.github.com/Pvlerick/80f610e67033b434ab949dd60b23add1#file-program03-cs)):
```CSharp
using System;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            var c = new C();
            PatternMatching<C, D>(c, d => d.M());
        }

        static void PatternMatching<TBase, TDerived>(TBase o, Action<TDerived> a) where TDerived : TBase
        {
            switch (o)
            {
                case TDerived td:
                    //This is where we end up...
                    Console.WriteLine(nameof(TDerived));
                    //This prints "ConsoleApp2.Program+C"
                    Console.WriteLine(td.GetType());
                    a(td);
                    break;
                default:
                    Console.WriteLine("Unmatched");
                    break;
            }
        }

        class C { }

        class D : C {
            private int _i = 42;
            private string _s = "Initialized";

            public void M()
            {
                Console.WriteLine(_i); //0
                Console.WriteLine(_s); //null
                Console.WriteLine(this.GetType()); //ConsoleApp2.Program+C
                //But still, can write to it
                _i = 5;
                Console.WriteLine(_i);
                _s = "What am I in the end?";
                Console.WriteLine(_s);
            }
        }
    }
}
```

**Expected Behavior**: The compiler shouldn't reject the case with TBase to begin with.

**Actual Behavior**: As demonstrated.

I discovered this when investigating on question raised during @BillWagner's talk in NDL London on Friday on pattern matching.

### PR DESCRIPTION
**Pull request by gafter**
**Customer scenario**

Using a pattern switch on a value whose type is an unconstrained type parameter results in bad code (that would fail verification) or an incorrect error message. Since few users run with verification enabled, this can result in loss of customer data. For example, this
```cs
        static void PatternMatching<TBase, TDerived>(TBase o) where TDerived : TBase
        {
            switch (o)
            {
                case TDerived td:
                    Console.WriteLine(nameof(TDerived));
                    Console.WriteLine(td.GetType());
                    break;
                default:
                    Console.WriteLine("Unmatched");
                    break;
            }
        }
```
is incorrectly compiled to this
```cs
private static void PatternMatching<TBase, TDerived>(TBase o) where TDerived : TBase
{
    TDerived td = o;
    Console.WriteLine("TDerived");
    Console.WriteLine(td.GetType());
}
```

**Bugs this fixes:** 

Fixes #16671

**Workarounds, if any**

Do not use the new type switch feature with type parameter types.

**Risk**

Low. Code change affects only the problematic scenario.

**Performance impact**

Low. Replaces one simple test (may this type be assigned null) with another (may a value of this type be null).

**Is this a regression from a previous update?**

No; the bug is in a new feature.

**Root cause analysis:**

Insufficient test coverage of scenarios that cross-cut language features. Failure to follow through on our plan to assign a developer to an adversarial test role for each feature under development.

**How was the bug found?**

Customer reported.

@AlekseyTs @agocke @dotnet/roslyn-compiler Please review this RTM bug fix.

See also https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?_a=edit&id=373449

### CODE REVIEW

**Comment by gafter** [comment]
@AlekseyTs @agocke @dotnet/roslyn-compiler Please review this RTM bug fix.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs [hunk 1]
```diff
@@ -53,7 +53,7 @@ public static DecisionTree Create(BoundExpression expression, TypeSymbol type, S
                 expression = new BoundLocal(expression.Syntax, temp, null, type);
             }
 
-            if (expression.Type.CanBeAssignedNull())
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs]: It looks like this helper is also used in localrewriter_patternswitchstatement.cs, is it possible that that code should be adjusted as well?

Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs]: The code there is correct as written - you can't have `case null` if you're switching on a value whose type is an unconstrained type parameter, precisely because `null` can't be assigned to that type. However, the code would probably be clearer with the test there changed as well (and more efficient at runtime in the case that the input is actually null). So I'll change it. I'll also introduce a helper for `CanContainNull` for clarity.

**Comment by gafter** [comment]
@agocke Please review this RTM bug fix.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 2]
```diff
@@ -4664,5 +4664,187 @@ public static void Main(string[] args)
...
+        }
+
+        [Fact(Skip = "https://github.com/dotnet/roslyn/issues/16696")]
+        public void TypeParameterSubsumption04()
+        {
+            var program = @"
+using System.Collections.Generic;
+public class Program
+{
+    private static void Pattern<T, TDerived>(object thing) where T : class where TDerived : T
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Consider using `TBase` rather than `T`, as in previous tests.

**Comment by cston** [comment]
LGTM

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: This is how this test differs from previous tests. It is intended to test this different scenario.

**Comment by gafter** [comment]
@MattGertz For ask mode

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 3]
```diff
@@ -4664,5 +4664,187 @@ public static void Main(string[] args)
...
+        }
+
+        [Fact(Skip = "https://github.com/dotnet/roslyn/issues/16696")]
+        public void TypeParameterSubsumption05()
+        {
+            var program = @"
+using System.Collections.Generic;
+public class Program
+{
+    private static void Pattern<T, TDerived>(object thing) where T : class where TDerived : T
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Is `T` needed or could the constraint be `TDerived : class`?

Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: This test checks the behavior of variance when the type arguments (to `IEnumerable`) are related type parameters. Due to a bug in the compiler where the conversion from `IEnumerable<Derived>` from `IEnumerable<T>` isn't supported as required by the language spec, this test fails. So no, changing the constraint would test a different scenario.

**Comment by natidea** [comment]
Approved to merge via [373449](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/373449)
