### PR TITLE
Collection expression spread optimization

### LINKED ISSUE #69626: Collection expressions should use AddRange(ReadOnlySpan) when available and compatible to bulk add spread elements.
Conclusion of: https://github.com/dotnet/csharplang/blob/main/meetings/working-groups/collection-literals/CL-2023-05-26.md#addrange-and-boxing

Tracking here so it doesn't get lost.

Relates to test plan https://github.com/dotnet/roslyn/issues/66418

### LINKED ISSUE #69988: Analyzer suggestion `IDE0305` ("Collection initialization can be simplified") leads to performance regressions
## Description

With the addition of collection literals in .NET 8, analyzer suggestion `IDE0305` has been introduced. This suggestion appears on code such as this;
```cs
int[] M(List<int> foo) => foo.ToArray(); // Collection initialization can be simplified
```
The suggested change is the following;
```cs
int[] M(List<int> foo) => [.. foo];
```

## Issue

The new syntax is certainly very nice, but actually leads to non-trivial performance regressions (up to 4x worse). You can find some benchmarking results below. I completely understand the desire for this suggestion, but find it questionable when it doesn't actually offer an equivalent outcome. Especially with all the performance-related analyzer suggestions that .NET 8 added elsewhere.

## Benchmark

```cs
[MemoryDiagnoser(displayGenColumns: false)]
public class Benchmarks
{
    private readonly List<int> _list = new();

    [Params(10, 100, 1_000, 100_000, 1_000_000)]
    public int Count { get; set; }

    [GlobalSetup]
    public void Setup()
    {
        for (int i = 0; i < Count; i++)
        {
            _list.Add(i);
        }
    }

    [GlobalCleanup]
    public void Cleanup()
    {
        _list.Clear();
    }

    [Benchmark]
    public int[] ToArray_Linq()
    {
        return _list.ToArray();
    }

    [Benchmark]
    public int[] ToArray_Literal()
    {
        return [.. _list];
    }
}
```
And here are the results on my machine;
```
BenchmarkDotNet v0.13.8, Windows 11 (10.0.22621.2283/22H2/2022Update/SunValley2)
AMD Ryzen 5 PRO 4650U with Radeon Graphics, 1 CPU, 12 logical and 6 physical cores
.NET SDK 8.0.100-rc.1.23455.8
  [Host]     : .NET 8.0.0 (8.0.23.41904), X64 RyuJIT AVX2
  DefaultJob : .NET 8.0.0 (8.0.23.41904), X64 RyuJIT AVX2


| Method          | Count   | Mean            | Error          | StdDev         | Ratio | RatioSD | Allocated  | Alloc Ratio |
|---------------- |-------- |----------------:|---------------:|---------------:|------:|--------:|-----------:|------------:|
| ToArray_Linq    | 10      |        14.64 ns |       0.353 ns |       0.911 ns |  1.00 |    0.00 |       64 B |        1.00 |
| ToArray_Literal | 10      |        83.89 ns |       1.667 ns |       2.546 ns |  5.79 |    0.39 |      280 B |        4.38 |
|                 |         |                 |                |                |       |         |            |             |
| ToArray_Linq    | 100     |        33.40 ns |       0.726 ns |       1.516 ns |  1.00 |    0.00 |      424 B |        1.00 |
| ToArray_Literal | 100     |       390.53 ns |      10.235 ns |      29.695 ns | 11.67 |    0.92 |     1608 B |        3.79 |
|                 |         |                 |                |                |       |         |            |             |
| ToArray_Linq    | 1000    |       213.75 ns |       4.800 ns |      13.618 ns |  1.00 |    0.00 |     4024 B |        1.00 |
| ToArray_Literal | 1000    |     3,241.95 ns |      84.984 ns |     245.200 ns | 15.24 |    1.54 |    12448 B |        3.09 |
|                 |         |                 |                |                |       |         |            |             |
| ToArray_Linq    | 100000  |   173,960.87 ns |   3,476.459 ns |   8,329.374 ns |  1.00 |    0.00 |   400066 B |        1.00 |
| ToArray_Literal | 100000  |   535,941.57 ns |  10,345.524 ns |  11,069.595 ns |  3.09 |    0.14 |  1449123 B |        3.62 |
|                 |         |                 |                |                |       |         |            |             |
| ToArray_Linq    | 1000000 | 1,294,022.79 ns |  25,686.070 ns |  27,483.807 ns |  1.00 |    0.00 |  4000091 B |        1.00 |
| ToArray_Literal | 1000000 | 7,649,278.75 ns | 184,894.259 ns | 515,411.292 ns |  5.83 |    0.56 | 12389341 B |        3.10 |
```

---

Wasn't sure whether this is a runtime or a Roslyn issue. Sorry if this is misplaced.

### LINKED ISSUE #70656: IDE0305 recommends collection expression that results in worse IL
**Version Used**: 
Version 17.9.0 Preview 1.0 [34231.268.main]

**Steps to Reproduce**:
```C#
static int[] GetArray(List<int> list) => list.ToArray(); 
```

IDE0305 recommends rewriting this to:
```C#
static int[] GetArray(List<int> list) => [.. list];
```
which would be fine if that still compiled down to a `list.ToArray()` call, but instead it compiles down to the equivalent of:
```C#
int[] array = new int[list.Count];
int num = 0;
foreach (int item in list)
{
    array[num] = item;
    num++;
}
```
which is significantly less efficient, especially for longer lists where the entire copy would instead be done as a vectorized memcpy invocation.

It's also worse if the list was actually empty: `List<T>.ToArray()` will return an empty array singleton if the count is 0, but the above code will end up always allocating a new empty array 😦 

cc: @cston, @CyrusNajmabadi

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #70656
Closes #69988
Closes #69626 (I didn't see which types expose a well-known `AddRange(ReadOnlySpan)` though.)

- Convert a collection-expr of the form `[..expr]` to `expr.ToArray()` when possible.
    - When expr is `List<T>`, using `List<T>.ToArray()`
    - Otherwise by converting expr to Span/ReadOnlySpan then calling ToArray
- Convert a collection-expr of the form `[elems, ..expr]` to use `expr.CopyTo(dest)` when possible.
    - Converting `dest` to `Span<T>`
    - Converting `expr` to `Span<T>` or `ReadOnlySpan<T>`
- Convert a collection-expr of the form `[elems, ..expr]` to `dest.AddRange(expr)` for `List<T>` when CollectionsMarshal is not available
    -  Converting `expr` to `IEnumerable<T>` (only if it is an implicit reference conversion)

Perf data for these various strategies can be found here:
(for arrays) https://github.com/dotnet/roslyn/issues/70656#issuecomment-1813492292
(for lists) https://github.com/dotnet/roslyn/issues/70656#issuecomment-1851047218

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
This is awesome. 

I think it would be good to have a simple doc that lists the patterns we optimize, and the version of the compiler (maybe) that introduced the optimization.  It would be good for people who want to know when this stuff does or doesn't happen.

**Comment by RikkiGibson** [comment]
It looks like a change in the base branch is preventing optimized codegen in 7 tests in CollectionExpressionTests, and I forgot to update a VB WellKnownMembers test. I'll look into it tomorrow.

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs [hunk 1]
```diff
@@ -25980,5 +25775,841 @@ public void Add(MyCollection c)
...
+                using System.Collections.Generic;
+
+                class C
+                {
+                    static void Main()
+                    {
+                        M([1, 2, 3], [4, 5, 6]);
+                    }
+
+                    static void M(ReadOnlySpan<int> e1, ReadOnlySpan<int> e2)
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:26141]: >ReadOnlySpan [](http://example.com/codeflow?start=34&length=12)

Should these parameters be `Span<int>` instead? (It looks like `ReadOnlySpan<T>` is covered in the following test.)

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs [hunk 2]
```diff
@@ -25980,5 +25775,841 @@ public void Add(MyCollection c)
...
+                    static void M(int[] e1, int[] e2)
+                    {
+                        List<int> result = [..e1, ..e2];
+                        result.Report();
+                    }
+                }
+                """;
+
+            var verifier = CompileAndVerify(new[] { source, s_collectionExtensionsWithSpan }, expectedOutput: IncludeExpectedOutput("[1, 2, 3, 4, 5, 6],"), targetFramework: TargetFramework.Net80);
+            System.IO.File.WriteAllBytes(@"C:\Users\rikki\Desktop\assembly.dll", verifier.EmittedAssemblyData.ToArray());
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:26310]: >System.IO.File.WriteAllBytes(@"C:\Users\rikki\Desktop\assembly.dll", verifier.EmittedAssemblyData.ToArray()); [](http://example.com/codeflow?start=12&length=109)

Remove?

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs [hunk 3]
```diff
@@ -25980,5 +25775,841 @@ public void Add(MyCollection c)
...
+                    static void M(ReadOnlySpan<int> e1, ReadOnlySpan<int> e2)
+                    {
+                        List<int> result = [..e1, ..e2];
+                        result.Report();
+                    }
+                }
+                """;
+
+            var verifier = CompileAndVerify(new[] { source, s_collectionExtensionsWithSpan }, expectedOutput: IncludeExpectedOutput("[1, 2, 3, 4, 5, 6],"), targetFramework: TargetFramework.Net80, options: TestOptions.ReleaseExe);
+            verifier.Diagnostics.Where(d => d.Severity > DiagnosticSeverity.Hidden).Verify();
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:26230]: >verifier.Diagnostics.Where(d => d.Severity > DiagnosticSeverity.Hidden).Verify() [](http://example.com/codeflow?start=12&length=80)

Consider using `verifier.Compilation.VerifyEmitDiagnostics()` for these cases instead.

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs [hunk 4]
```diff
@@ -25980,5 +25775,837 @@ public void Add(MyCollection c)
...
+                class C
+                {
+                    static void Main()
+                    {
+                        List<int> li = [1, 2, 3];
+                        li.Report();
+                        int[] arr = [..li];
+                        arr.Report();
+                    }
+                }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:25794]: >} [](http://example.com/codeflow?start=16&length=1)

Consider testing cases where the element types are considered distinct in C# but not in the runtime:
- `List<nint>` and `System.IntPtr[]`
- `List<object>` and `object?[]`
- `List<dynamic>` and `object[]`

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs [hunk 5]
```diff
@@ -25980,5 +25775,837 @@ public void Add(MyCollection c)
...
+                  IL_002f:  ldloca.s   V_0
+                  IL_0031:  call       "void CollectionExtensions.Report<int>(in System.Span<int>)"
+                  IL_0036:  ldloca.s   V_0
+                  IL_0038:  call       "int[] System.Span<int>.ToArray()"
+                  IL_003d:  ldc.i4.0
+                  IL_003e:  call       "void CollectionExtensions.Report(object, bool)"
+                  IL_0043:  ret
+                }
+                """);
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:25881]: >} [](http://example.com/codeflow?start=8&length=1)

Consider testing other target types, if not tested already:
- spans: `Span<int> y = [..x];`
- immutable interfaces: `IEnumerable<int> y = [..x];`
- mutable interfaces: `ICollection<int> y = [..x];`

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs (hunk 4 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:25794]: > - `List<dynamic>` and `object[]`

It looks like the `dynamic` case in particular is not optimized. I don't think we should try to optimize this case, but it would be good to capture the current behavior.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 6]
```diff
@@ -520,6 +521,44 @@ private BoundExpression CreateAndPopulateArray(BoundCollectionExpression node, A
...
+                        var rewrittenSpreadExpression = VisitExpression(spreadExpression);
+                        if (asSpanMethod is not null)
+                            rewrittenSpreadExpression = CallAsSpanMethod(rewrittenSpreadExpression, asSpanMethod);
+                        return Factory.Call(rewrittenSpreadExpression, toArrayMethod.AsMember((NamedTypeSymbol)rewrittenSpreadExpression.Type!));
+                    }
+                }
+
+                MethodSymbol? tryGetToArrayMethod(TypeSymbol spreadTypeOriginalDefinition, WellKnownType wellKnownType, WellKnownMember wellKnownMember)
+                {
+                    if (spreadTypeOriginalDefinition.Equals(this._compilation.GetWellKnownType(wellKnownType)))
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:553]: >Equals [](http://example.com/codeflow?start=53&length=6)

It wasn't clear to me what compare options this uses. Consider being explicit, perhaps by using `TypeSymbol.Equals(..., TypeCompareKind.AllIgnoreOptions)`, or since these are original definitions of well-known types, perhaps just `Reference.Equals()`.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 7]
```diff
@@ -520,6 +521,44 @@ private BoundExpression CreateAndPopulateArray(BoundCollectionExpression node, A
...
+            // Optimize to `spreadExpression.ToArray()` if possible.
+            if (node is { Elements: [BoundCollectionExpressionSpreadElement { Expression: { } spreadExpression } spreadElement] }
+                && spreadElement.IteratorBody is BoundExpressionStatement expressionStatement
+                && expressionStatement.Expression is not BoundConversion)
+            {
+                var spreadTypeOriginalDefinition = spreadExpression.Type!.OriginalDefinition;
+                if (tryGetToArrayMethod(spreadTypeOriginalDefinition, WellKnownType.System_Collections_Generic_List_T, WellKnownMember.System_Collections_Generic_List_T__ToArray) is { } listToArrayMethod)
+                {
+                    var rewrittenSpreadExpression = VisitExpression(spreadExpression);
+                    return Factory.Call(rewrittenSpreadExpression, listToArrayMethod.AsMember((NamedTypeSymbol)spreadExpression.Type!));
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:534]: >Factory [](http://example.com/codeflow?start=27&length=7)

Minor: Consider using `_factory` here and in the `Factory.Call()` below, for consistency with other calls and so it's clear we're not relying on additional behavior in a property.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 8]
```diff
@@ -612,6 +671,157 @@ private BoundExpression CreateAndPopulateArray(BoundCollectionExpression node, A
...
+        {
+            var type = expression.Type;
+            Debug.Assert(type is not null);
+
+            if (!TryGetSpanConversion(type, out var asSpanMethod))
+            {
+                return null;
+            }
+
+            return asSpanMethod is null ? expression : CallAsSpanMethod(expression, asSpanMethod);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:725]: >asSpanMethod is null ? expression : CallAsSpanMethod(expression, asSpanMethod) [](http://example.com/codeflow?start=19&length=78)

It looks like all calls to `CallAsSpanMethod()` use this same pattern. Perhaps rename the method to `CallOptionalAsSpanMethod(expression, asSpanMethod)` and allow `asSpanMethod` to be `null`, to simplify callers.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 9]
```diff
@@ -612,6 +671,157 @@ private BoundExpression CreateAndPopulateArray(BoundCollectionExpression node, A
...
+            {
+                asSpanMethod = spanCtorArray.AsMember(spanCtorArray.ContainingType.Construct(arrayType.ElementType));
+                return true;
+            }
+
+            if (type is NamedTypeSymbol immutableArrayType
+                && immutableArrayType.OriginalDefinition.Equals(_compilation.GetWellKnownType(WellKnownType.System_Collections_Immutable_ImmutableArray_T), TypeCompareKind.ConsiderEverything)
+                && _factory.WellKnownMethod(WellKnownMember.System_Collections_Immutable_ImmutableArray_T__AsSpan, isOptional: true) is { } immutableArrayAsSpanMethod)
+            {
+                asSpanMethod = immutableArrayAsSpanMethod!.AsMember(immutableArrayType);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:699]: >! [](http://example.com/codeflow?start=57&length=1)

Is `!` necessary?

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs [hunk 10]
```diff
@@ -25980,5 +25775,837 @@ public void Add(MyCollection c)
...
+                    {
+                        M([1, 2, 3], [4, 5, 6]);
+                    }
+
+                    static void M(int[] e1, int[] e2)
+                    {
+                        List<int> result = [..e1, ..e2];
+                        result.Report();
+                    }
+                }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:26305]: >} [](http://example.com/codeflow?start=16&length=1)

Consider testing spreading a multi-dimensional array, to verify we're skipping the optimization.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 11]
```diff
@@ -599,6 +639,25 @@ private BoundExpression CreateAndPopulateArray(BoundCollectionExpression node, A
                             _factory.Binary(BinaryOperatorKind.Addition, indexTemp.Type, indexTemp, _factory.Literal(1)),
                             isRef: false,
                             indexTemp.Type));
+                },
+                (sideEffects, targetArray, spreadElement, rewrittenSpreadOperand) =>
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:643]: >targetArray [](http://example.com/codeflow?start=30&length=11)

Consider calling this `arrayTemp`, for consistency with lambda expression above, and to shadow the `arrayTemp` from outside this lambda expression.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 12]
```diff
@@ -738,6 +957,24 @@ private BoundExpression CreateAndPopulateList(BoundCollectionExpression node, Ty
...
+                    {
+                        if (addRangeMethod is null)
+                            return false;
+
+                        var type = rewrittenSpreadOperand.Type!;
+
+                        var useSiteInfo = GetNewCompoundUseSiteInfo();
+                        var conversion = _compilation.Conversions.ClassifyConversionFromType(type, addRangeMethod.Parameters[0].Type, isChecked: false, ref useSiteInfo);
+                        _diagnostics.Add(rewrittenSpreadOperand.Syntax, useSiteInfo);
+                        if (conversion.IsImplicit && conversion.IsReference)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:971]: >conversion.IsReference [](http://example.com/codeflow?start=53&length=22)

Are we testing cases other than reference conversions? For instance:
- Identity conversion, where the spread collection is an `IEnumerable<T>`
- Variance conversion, where the spread collection is an `IEnumerable<U> where U : T`
- Boxing conversion, where the spread collection is a `struct`

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 13]
```diff
@@ -738,6 +957,24 @@ private BoundExpression CreateAndPopulateList(BoundCollectionExpression node, Ty
...
+                        {
+                            sideEffects.Add(_factory.Call(listTemp, addRangeMethod, MakeConversionNode(rewrittenSpreadOperand, type, @checked: false, markAsChecked: true)));
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:973]: >MakeConversionNode(rewrittenSpreadOperand, type, @checked: false, markAsChecked: true) [](http://example.com/codeflow?start=84&length=86)

We've already calculated the `conversion` above. Could we call the following instead?
```csharp
conversion.MarkUnderlyingConversionsCheckedRecursive();
sideEffects.Add(_factory.Call(listTemp, addRangeMethod,
    MakeConversionNode(rewrittenSpreadOperand.Syntax, rewrittenSpreadOperand, conversion, type, checked: false)));
```

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 14]
```diff
@@ -782,7 +1019,8 @@ private BoundExpression RewriteCollectionExpressionElementExpression(BoundNode e
             ArrayBuilder<BoundLocal> rewrittenExpressions,
             int numberIncludingLastSpread,
             ArrayBuilder<BoundExpression> sideEffects,
-            Action<ArrayBuilder<BoundExpression>, BoundExpression, BoundExpression> addElement)
+            Action<ArrayBuilder<BoundExpression>, BoundExpression, BoundExpression> addElement,
+            Func<ArrayBuilder<BoundExpression>, BoundExpression, BoundCollectionExpressionSpreadElement, BoundExpression, bool>? tryOptimizeSpreadElement = null)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:1023]: >tryOptimizeSpreadElement = null [](http://example.com/codeflow?start=129&length=31)

All callers pass a non-null value. The parameter can be changed to non-optional and non-nullable.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 15]
```diff
@@ -599,6 +639,25 @@ private BoundExpression CreateAndPopulateArray(BoundCollectionExpression node, A
...
                             indexTemp.Type));
+                },
+                (sideEffects, targetArray, spreadElement, rewrittenSpreadOperand) =>
+                {
+                    if (TryPrepareCopyToOptimization(spreadElement, rewrittenSpreadOperand) is not var (spanSliceMethod, spreadElementAsSpan, getLengthMethod, copyToMethod))
+                        return false;
+
+                    if (targetSpanTemp is null)
+                    {
+                        var targetSpan = TryConvertToSpanOrReadOnlySpan(targetArray);
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:650]: It could be, but I wasn't able to cook up a scenario that outright breaks things. I am going to try microbenchmarking doing repeated conversions to Span versus using a Span temp.

[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:650]: My conclusion on this is:
- Yes, overhead is minimal. Probably on the order of 2% execution time for collection-exprs we are likely to see.
- I believe that the impl is currently "await-safe". All the spread elements have been evaluated to temps at the time we take a span-temp of the destination. So we won't visit any awaits while copying the spreads.
- However, this assumption is fragile, and the failure mode of that assumption breaking later could be bad.
- So, for simplicity, let's eliminate the dest temp for now, and open an issue to reintroduce it later if we want.

**Comment by cston** [comment]
>                 }

Consider also testing the following. I believe in that case we're not including the `CopyTo()` optimization. Again, that seems reasonable if that is the case, but it would be good to capture that behavior in a test.
```csharp
List<dynamic> x = [1, 2, 3];
object[] y = [..x];
```

---
Refers to: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:7486 in 501d5b1. [](commit_id = 501d5b1410eb7c659c5c07f6eedebdd449aef574, deletion_comment = False)

**Comment by cston** [comment]
>             verifier.VerifyIL("C.Main", """

Should this verify `C.<Main>d__1.System.Runtime.CompilerServices.IAsyncStateMachine.MoveNext()` instead?

---
Refers to: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:27100 in cce39d0. [](commit_id = cce39d03d29b8749244cfd58f647e420eaec5380, deletion_comment = False)

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 16]
```diff
@@ -520,6 +521,42 @@ private BoundExpression CreateAndPopulateArray(BoundCollectionExpression node, A
...
+                    if ((tryGetToArrayMethod(spanType, WellKnownType.System_Span_T, WellKnownMember.System_Span_T__ToArray)
+                            ?? tryGetToArrayMethod(spanType, WellKnownType.System_ReadOnlySpan_T, WellKnownMember.System_ReadOnlySpan_T__ToArray))
+                        is { } toArrayMethod)
+                    {
+                        var rewrittenSpreadExpression = CallAsSpanMethod(VisitExpression(spreadExpression), asSpanMethod);
+                        return _factory.Call(rewrittenSpreadExpression, toArrayMethod.AsMember((NamedTypeSymbol)rewrittenSpreadExpression.Type!));
+                    }
+                }
+
+                MethodSymbol? tryGetToArrayMethod(TypeSymbol spreadTypeOriginalDefinition, WellKnownType wellKnownType, WellKnownMember wellKnownMember)
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:549]: This isn't really a try-get in traditional form, and it feels like the code that uses it is a bit convoluted because of it. Consider refactoring to be a standard `tryGet` with an `out` parameter.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 17]
```diff
@@ -599,6 +636,20 @@ private BoundExpression CreateAndPopulateArray(BoundCollectionExpression node, A
                             _factory.Binary(BinaryOperatorKind.Addition, indexTemp.Type, indexTemp, _factory.Literal(1)),
                             isRef: false,
                             indexTemp.Type));
+                },
+                (sideEffects, arrayTemp, spreadElement, rewrittenSpreadOperand) =>
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:640]: Consider naming these delegate parameters, especially now that there are multiple of them.

Comment (333fred) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:640]: Also, please spell out the types of these parameters. Same goes for the other similar delegates below.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 18]
```diff
@@ -612,6 +663,161 @@ private BoundExpression CreateAndPopulateArray(BoundCollectionExpression node, A
                 arrayType);
         }
 
+        /// <summary>
+        /// Returns true if type is convertible to Span or ReadOnlySpan.
+        /// If non-identity conversion, also returns a non-null asSpanMethod.
+        /// </summary>
+        private bool TryGetSpanConversion(TypeSymbol type, out MethodSymbol? asSpanMethod)
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:670]: Let's rearrange this method to simplify things. First, check to see if it's the array case. The rest of the cases depend on it being a named type symbol, so you can do that check once and bail if false, rather than type-checking against NamedTypeSymbol 3 times.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 19]
```diff
@@ -612,6 +663,161 @@ private BoundExpression CreateAndPopulateArray(BoundCollectionExpression node, A
...
+            {
+                asSpanMethod = collectionsMarshalAsSpanMethod.Construct(listType.TypeArgumentsWithAnnotationsNoUseSiteDiagnostics[0].Type);
+                return true;
+            }
+
+            asSpanMethod = null;
+            return false;
+        }
+
+        private BoundExpression? TryConvertToSpanOrReadOnlySpan(BoundExpression expression)
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:707]: It feels like this is another method that would be better served by following the standard `TryGet` pattern.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 20]
```diff
@@ -612,6 +663,161 @@ private BoundExpression CreateAndPopulateArray(BoundCollectionExpression node, A
...
+            (MethodSymbol getLengthMethod, MethodSymbol copyToMethod)? tryGetSpanMethodsForSpread(
+                WellKnownType wellKnownSpanType,
+                WellKnownMember getLengthMember,
+                WellKnownMember copyToMember)
+            {
+                if (spreadOperandAsSpan.Type!.OriginalDefinition.Equals(this._compilation.GetWellKnownType(wellKnownSpanType))
+                    && _factory.WellKnownMethod(getLengthMember, isOptional: true) is { } getLengthMethod
+                    && _factory.WellKnownMethod(copyToMember, isOptional: true) is { } copyToMethod)
+                {
+                    return (getLengthMethod!, copyToMethod!);
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:778]: Why do we need suppressions on this line?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 21]
```diff
@@ -612,6 +663,161 @@ private BoundExpression CreateAndPopulateArray(BoundCollectionExpression node, A
...
+                    || spanType.OriginalDefinition.Equals(_compilation.GetWellKnownType(WellKnownType.System_ReadOnlySpan_T), TypeCompareKind.ConsiderEverything)))
+            {
+                asSpanMethod = null;
+                return true;
+            }
+
+            if (type is ArrayTypeSymbol { IsSZArray: true } arrayType
+                && _factory.WellKnownMethod(WellKnownMember.System_Span_T__ctor_Array, isOptional: true) is { } spanCtorArray)
+            {
+                asSpanMethod = spanCtorArray.AsMember(spanCtorArray.ContainingType.Construct(arrayType.ElementType));
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:683]: What if the element type is something that can't be a valid type parameter, like a pointer? Do we have a test covering that?

**Review by 333fred — COMMENTED** [review]
Done review pass

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs (hunk 17 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:640]: I wasn't sure what you meant by name the delegate parameters. Were you suggesting that I declare a named delegate type which has these parameter names?

Comment (333fred) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:640]: No, I mean specify the parameter name for each of these delegate arguments. What is the parameter this delegate is being passed to?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 22]
```diff
@@ -612,6 +663,166 @@ private BoundExpression CreateAndPopulateArray(BoundCollectionExpression node, A
...
+        /// <summary>
+        /// Returns true if type is convertible to Span or ReadOnlySpan.
+        /// If non-identity conversion, also returns a non-null asSpanMethod.
+        /// </summary>
+        private bool TryGetSpanConversion(TypeSymbol type, out MethodSymbol? asSpanMethod)
+        {
+            if (type is ArrayTypeSymbol { IsSZArray: true } arrayType
+                && _factory.WellKnownMethod(WellKnownMember.System_Span_T__ctor_Array, isOptional: true) is { } spanCtorArray)
+            {
+                asSpanMethod = spanCtorArray.AsMember(spanCtorArray.ContainingType.Construct(arrayType.ElementType));
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:675]: How do we know the element type is always going to be a valid type argument? Can we assert something?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 23]
```diff
@@ -599,6 +637,19 @@ private BoundExpression CreateAndPopulateArray(BoundCollectionExpression node, A
                             _factory.Binary(BinaryOperatorKind.Addition, indexTemp.Type, indexTemp, _factory.Literal(1)),
                             isRef: false,
                             indexTemp.Type));
+                },
+                (ArrayBuilder<BoundExpression> sideEffects, BoundExpression arrayTemp, BoundCollectionExpressionSpreadElement spreadElement, BoundExpression rewrittenSpreadOperand) =>
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:641]: Still missing `tryOptimizeSpreadElement: ` naming.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs (hunk 22 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:675]: I would be fine with asserting, for example, that element type is implicitly convertible to object.

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs (hunk 22 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs]: This was a faulty assumption. The conversion to object is now checked in retail builds and if it isn't what we expect then we don't use either the ToArray or CopyTo optimization paths.

Comment (cston) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs]: Do we have a test that hits this? (It looks like the existing tests were unchanged, other than setting the target framework.)

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs]: The new tests require the object conversion check in order to work properly.

**Review by 333fred — APPROVED** [review]
