### PR TITLE
Fix crash in semantic model when using unmanaged constraint

### LINKED ISSUE #37021: Generic unmanaged type used with extension method causes 100% repro crash in VS2019
VSF_TYPE_MARKDOWNThe attached file causes VS2019 to crash when it's loaded.

If I remove the `where T : unmanaged` constraints, it stops crashing.

It also doesn't crash until I add the `foo. GenericExtension();` line, where it will crash as soon as I type the `n` in `foo. GenericExtension`.

```
using System;

namespace UnmanagedGenericCrash
{
    public static class FooExtensions
    {
        public static T GenericExtension&lt;T&gt;(ref this T self) where T : unmanaged
        {
            return self;
        }
    }

class Program
    {
        public struct Foo&lt;T&gt; where T : unmanaged
        {
            T t;
        }

static void UseFoo&lt;T&gt;(Foo&lt;T&gt; foo) where T : unmanaged
        {
            foo. GenericExtension();
        }

static void Main(string[] args)
        {
            Console.WriteLine(&quot;Hello World!&quot;);
        }
    }
}
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/598828/generic-unmanaged-type-used-with-extension-method.html
VSTS ticketId: 911278_
_These are the original issue comments:_

Visual Studio Feedback System on 6/10/2019, 01:06 AM (25 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

### PR DESCRIPTION
**Pull request by agocke**
The semantic model often creates ReducedExtensionMethods for the public API,
but the creation of ReducedExtensionMethod does constraint checking, which
requires a compilation, which isn't always available. This change removes constraint
checking from all creation of ReducedExtensionMethod and adds asserts that we
always have a compilation during constraint checking.

Fixes #37021

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs [hunk 1]
```diff
@@ -873,8 +873,11 @@ private static bool HasDuplicateInterfaces(NamedTypeSymbol type, ConsList<TypeSy
                     diagnosticsBuilder.Add(new TypeParameterDiagnosticInfo(typeParameter, new CSDiagnosticInfo(ErrorCode.ERR_UnmanagedConstraintNotSatisfied, containingSymbol.ConstructedFrom(), typeParameter, typeArgument.Type)));
                     return false;
                 }
-                else if (managedKind == ManagedKind.UnmanagedWithGenerics)
+                else if (managedKind == ManagedKind.UnmanagedWithGenerics && currentCompilation is object)
                 {
+                    // In batch scenarios currentCompilation should always be non-null, but the public API
+                    // can check constraints in multiple places and there may not be a current compilation.
+                    // For these scenarios, we'll skip checking
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs]: Is there any way that we can assert that if `currentCompilation` is null, we're not in a batch compilation scenario? Or is that a guaranteed fact in the first place?

File: src/Compilers/CSharp/Test/Emit/Emit/UnmanagedTypeModifierTests.cs [hunk 2]
```diff
@@ -1,6 +1,8 @@
 ﻿// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
 
 using System.Linq;
+using Microsoft.CodeAnalysis.CSharp.Symbols;
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Emit/Emit/UnmanagedTypeModifierTests.cs]: Are these necessary?

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs [hunk 3]
```diff
@@ -16,6 +16,60 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
 {
     public class SemanticTests : CSharpTestBase
     {
+        [Fact]
+        public void UnamangedConstraintOnExtensionMethod()
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs]: nit: spelling

File: src/Compilers/CSharp/Test/Emit/Emit/UnmanagedTypeModifierTests.cs (hunk 2 above)
Comment (agocke) [reply src/Compilers/CSharp/Test/Emit/Emit/UnmanagedTypeModifierTests.cs]: No, will revert

File: src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs (hunk 1 above)
Comment (agocke) [reply src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs]: I don't know of a way to assert that, unfortunately.

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs [hunk 4]
```diff
@@ -16,6 +16,60 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+            comp2.VerifyDiagnostics();
+            Assert.NotNull(checkSymbolInfo(comp2).Symbol);
+
+            comp2 = CreateCompilation(src2, parseOptions: TestOptions.Regular7_3,
+                references: new[] { comp1.ToMetadataReference() });
+            comp2.VerifyDiagnostics(
+                    // (11,14): error CS8652: The feature 'unmanaged constructed types' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
+                    //         foo. GenericExtension();
+                    Diagnostic(ErrorCode.ERR_FeatureInPreview, "GenericExtension").WithArguments("unmanaged constructed types").WithLocation(11, 14));
+            var info = checkSymbolInfo(comp2);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs]: Does this test contain the scenario where `currentCompilation` is null due to the public APIs called by the semantic model? Sorry that I'm a little unclear on when/why this can happen.

Comment (agocke) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs]: Yup, the chain is GetSymbolInfo -> try to get reduced extension method -> check constraints -> boom

Comment (agocke) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs]: The problem is http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Symbols/MethodSymbol.cs,684 where we just assume you can reduce extension methods without a compilation. I mean, you can, but you may not get full constraint checks if you do.

Comment (agocke) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs]: Note: public API: http://source.roslyn.io/#Microsoft.CodeAnalysis/Symbols/IMethodSymbol.cs,fe1886144a64d90d,references

Comment (agocke) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs]: I thought about just skipping constraint checking entirely when `currentCompilation` is null but that seemed even more risky.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs]: OK, just to be crystal clear: do both calls to `checkSymbolInfo` wind up creating a ReducedExtensionMethodSymbol with a `null` Compilation?

Is this an issue where there's not necessarily a "correct" compilation we can associate with the ReducedExtensionMethodSymbol?

Comment (agocke) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs]: Yup, both calls pass null as the compilation. The problem is that reducing extension methods may involve constraint checking, which we don't necessarily have a compilation to do that in

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs]: Is that true any time we construct a generic method with constraints on the type parameters?

**Comment by RikkiGibson** [comment]
Are we going to take this fix in servicing or in the next release?

**Comment by 333fred** [comment]
@agocke ^

**Comment by agocke** [comment]
@RikkiGibson 16.3p2

**Comment by agocke** [comment]
I'm currently thinking if I want to try to split the graph into two methods, one which takes a compilation and one which doesn't and be explicit about the one without a compilation only being used in public API scenarios.

**Comment by RikkiGibson** [comment]
If it's easy to factor out, then great, otherwise consider using the `compilationOpt` naming convention in constraint checking or some other relevant code paths to let future developers know it could be null in some scenarios. (I assume `#nullable enable` is not an option in this code just yet.)

**Comment by agocke** [comment]
@RikkiGibson I've removed constraint checking entirely from this code path.

File: src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs [hunk 5]
```diff
@@ -511,6 +511,8 @@ void populateDiagnosticsAndClear(ArrayBuilder<TypeParameterDiagnosticInfo> build
         {
             Debug.Assert(!type.IsTupleType);
             Debug.Assert(typeArgumentsSyntax.Count == 0 /*omitted*/ || typeArgumentsSyntax.Count == type.Arity);
+            Debug.Assert(currentCompilation is object);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs]: :tada:

File: src/Compilers/CSharp/Portable/Symbols/ReducedExtensionMethodSymbol.cs [hunk 6]
```diff
@@ -96,6 +97,92 @@ private ReducedExtensionMethodSymbol(MethodSymbol reducedFrom)
...
+                    }
+
+                    typeArgsForConstruct = builder.ToImmutableAndFree();
+                }
+            }
+
+            if (typeArgsForConstruct.IsDefault)
+            {
+                typeArgsForConstruct = typeArgs;
+            }
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/ReducedExtensionMethodSymbol.cs]: Consider simplifying. Perhaps:
```C#
var typeArgsForConstruct = typeArgs;
if (typeArgs.Any(t => !t.HasType))
{
    typeArgsForConstruct = typeArgs.ZipAsArray(
        method.TypeParameters,
        (t, tp) => t.HasType ? t : TypeWithAnnotations.Create(tp));
}
```

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs [hunk 7]
```diff
@@ -16,6 +16,60 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+    public static T GenericExtension<T>(ref this T self) where T : unmanaged
+    {
+        return self;
+    }
+}
+";
+            var src2 = @"
+public class Program
+{
+    public struct Foo<T> where T : unmanaged
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs]: >Foo [](start = 18, length = 3)

Perhaps `F` instead.

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs [hunk 8]
```diff
@@ -16,6 +16,60 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
 {
     public class SemanticTests : CSharpTestBase
     {
+        [Fact]
+        public void UnmanagedConstraintOnExtensionMethod()
+        {
+            var src = @"
+public static class FooExtensions
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs]: >Foo [](start = 20, length = 3)

Remove.

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs [hunk 9]
```diff
@@ -16,6 +16,60 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+
+            var comp2 = CreateCompilation(src2, parseOptions: TestOptions.Regular8,
+                references: new[] { comp1.ToMetadataReference() });
+            comp2.VerifyDiagnostics();
+            Assert.NotNull(checkSymbolInfo(comp2).Symbol);
+
+            comp2 = CreateCompilation(src2, parseOptions: TestOptions.Regular7_3,
+                references: new[] { comp1.ToMetadataReference() });
+            comp2.VerifyDiagnostics(
+                    // (11,14): error CS8652: The feature 'unmanaged constructed types' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs]: >         [](start = 12, length = 8)

Indenting seems off.
