### PR TITLE
Visit all local function return types during lowering

### LINKED ISSUE #16038: Local function references should visit the return type during lowering
The following test fails on master

```csharp
        [Fact]
        public void RecursiveGenericLocalFunction8()
        {
            var src = @"
using System;
class C<T0>
{
    T0 t0;

    public C(T0 t0)
    {
        this.t0 = t0;
    }

    public void M<T1>(T1 t1)
    {
        (T0, T1, T2) L1<T2>(T2 t2)
        {
            (T0, T1, T2, T3) L2<T3>(T3 t3, int count)
            {
                if (count > 0)
                {
                    Console.Write(t0);
                    Console.Write(t1);
                    Console.Write(t2);
                    Console.Write(t3);
                    return L2(t3, count - 1);
                }
                return (t0, t1, t2, t3);
            }
            var (t4, t5, t6, t7) = L2(""A"", 5);
            return (t4, t5, t6);
        }
        L1(""B"");
    }
}

class Program
{
    public static void Main()
    {
        var c = new C<string>(""C"");
        c.M(""D"");
    }
}";
            CompileAndVerify(src, expectedOutput: "CDBACDBACDBACDBACDBA",
                additionalRefs: new[] { SystemRuntimeFacadeRef, ValueTupleRef });
```

### PR DESCRIPTION
**Pull request by agocke**
**Customer scenario**

Write a recursive local function that captures a generic type from a parent scope.

**Bugs this fixes:** 

Fixes #16038 

**Workarounds, if any**

Pass the generic parameter as a generic parameter, rather than capturing it.

**Risk**

This only affects lowering of local function references.

**Performance impact**

Low. Generic substitution is a cheap, common operation in the compiler.

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

@AlekseyTs noted an inconsistency in a previous PR.

**How was the bug found?**

Code review.

### CODE REVIEW

**Comment by agocke** [comment]
@AlekseyTs @dotnet/roslyn-compiler Please review.

File: src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.LocalFunctionReferenceRewriter.cs [hunk 1]
```diff
@@ -82,10 +82,8 @@ public override BoundNode VisitDelegateCreationExpression(BoundDelegateCreationE
                         out method,
                         ref arguments);
 
-                    var newType = _lambdaRewriter.VisitType(node.Type);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.LocalFunctionReferenceRewriter.cs]: >var newType = _lambdaRewriter.VisitType(node.Type); [](start = 20, length = 51)

Is visiting ```node.Type``` no longer necessary? Consider adding an assert that ```node.Type == method.ReturnType```. And for other similar places in this file.

**Comment by AlekseyTs** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.LocalFunctionReferenceRewriter.cs (hunk 1 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.LocalFunctionReferenceRewriter.cs]: I just inlined that call. It's still necessary. I do like the assert idea though, I will add that.

Comment (agocke) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/LambdaRewriter.LocalFunctionReferenceRewriter.cs]: @AlekseyTs And I talked about this offline.

It turns out to be slightly harder than I expected to assert all the things I want to assert.

Rather than spend a lot of time to only get a little extra value here, I've filed https://github.com/dotnet/roslyn/issues/16057 to try to do more of these things in a structured way.

**Comment by VSadov** [comment]
LGTM

**Comment by agocke** [comment]
@srivatsn For ask mode approval
