### PR TITLE
Call DkmClrValue.Close more conservatively

### LINKED ISSUE #901: DataTips not available for items with AggregateExpansion (ObjectDisposedException in DkmClrValue.EvalFlags)
1. Create a C# Console App with the following code:
```
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;

namespace Test
{
    public class ListNotify<T> : List<T>
    {
        public int ItemAdded;

        public new int Add(T item)
        {
            ItemAdded = 1;
            return 1;
        }
    }

    public class ClassCollection : ListNotify<int>
    {
    }
    
    class Program
    {
        static int Main ()
        {
            ClassCollection c = new ClassCollection();
            
            Debugger.Break ();                      //break here
                                                    //list locals2 4
                                                    //eval (((Test.ListNotify<int>)(c))).ItemAdded
                                                    //go
                                                    
            return 0;
        }
    }
}
```
2. F5 (hit breakpoint)
3. Open Locals Window (see that "c" exists)
4. Attempt to expand DataTip for "c".

**RESULTS:**
DataTip displays "?"
```
>	Microsoft.VisualStudio.Debugger.Evaluation.ClrCompilation.DkmClrValue.EvalFlags.get
 	Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProvider.GetTypeExpansion
 	Microsoft.CodeAnalysis.ExpressionEvaluator.DebuggerTypeProxyExpansion.CreateRawView
 	Microsoft.CodeAnalysis.ExpressionEvaluator.DebuggerTypeProxyExpansion.CreateRawViewRow
 	Microsoft.CodeAnalysis.ExpressionEvaluator.DebuggerTypeProxyExpansion.GetRows
 	Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProvider.GetItemsAndContinue
	Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProvider.Microsoft.VisualStudio.Debugger.ComponentInterfaces.IDkmClrResultProvider.GetItems
 	Microsoft.VisualStudio.Debugger.EntryPoint.IDkmClrResultProvider_GetItems
```

### PR DESCRIPTION
**Pull request by amcasey**
The problem arises when more than one expanion shares the same value - for
example, those parented by a common AggregateExpansion.  Since this is an
optimization anyway (the debugger would eventually close them on its own),
we'll just conservatively focus on member and array expensions, since they
always "own" the value in aggregate expansions.

Fixes #901.

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @KevinH-MS @cston @pnelsonmsft @ManishJayaswal

**Comment by ManishJayaswal** [comment]
LGTM

File: src/ExpressionEvaluator/Core/Source/ResultProvider/Expansion/MemberExpansion.cs [hunk 1]
```diff
@@ -241,6 +241,8 @@ private static DkmClrValue GetMemberValue(DkmClrValue container, MemberAndDeclar
             return container.GetMemberValue(member.Name, (int)member.MemberType, member.DeclaringType.FullName, inspectionContext);
         }
 
+        internal sealed override bool OwnsValue => false;
```
Comment (KevinH-MS) [inline src/ExpressionEvaluator/Core/Source/ResultProvider/Expansion/MemberExpansion.cs]: true?

**Comment by KevinH-MS** [comment]
:+1:

File: src/ExpressionEvaluator/Core/Source/ResultProvider/Helpers/EvalResultDataItem.cs [hunk 2]
```diff
@@ -154,7 +154,15 @@ private static DkmEvaluationResultFlags GetFlags(DkmClrValue value, DkmInspectio
...
-            Value.Close();
+            // If we have an expansion, there's a danger that more than one data item is 
+            // referring to the same DkmClrValue (e.g. if it's an AggregateExpansion).
+            // To be safe, we'll only call Close when there's no expansion.  Since this
+            // is only an optimization (the debugger will eventually close the value
+            // anyway), a conservative approach is acceptable.
+            if (this.Expansion == null)
+            {
+                Value.Close();
+            }
```
Comment (cston) [inline src/ExpressionEvaluator/Core/Source/ResultProvider/Helpers/EvalResultDataItem.cs]: Should we close array element values of reference types?
