### PR TITLE
Fix crash on "is type" operator with typeless tuple expression.

### LINKED ISSUE #13746: Compiler crashes with typeless tuple on the left of an is-type operator
```cs
        [Fact]
        public void ExpressionWithoutAType()
        {
            var source =
@"
public class Vec
{
    public static void Main()
    {
        if ((1, null) is Vec)
        {}
    }
}
";

            CreateCompilationWithMscorlib45(source, options: TestOptions.DebugExe).VerifyDiagnostics(
                );
        }
```

this crashes the C# compiler.

### PR DESCRIPTION
**Pull request by gafter**
Add tests for non-reproducible issue #13723
Fixes #13746 
Also rename an error code for clarity.

@VSadov @jcouv Please review
@dotnet/roslyn-compiler More reviews welcome!

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs [hunk 1]
```diff
@@ -2550,6 +2550,20 @@ private bool IsOperandErrors(CSharpSyntaxNode node, ref BoundExpression operand,
...
 
                     return true;
+
+                default:
+                    if ((object)operand.Type == null && !operand.IsLiteralNull())
+                    {
+                        if (!operand.HasAnyErrors)
+                        {
+                            // Operator 'is' cannot be applied to operand of type '(int, <null>)'
+                            diagnostics.Add(ErrorCode.ERR_BadUnaryOp, node.Location, "is", operand.Display);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs]: >"is" [](start = 85, length = 4)

There isn't a single place in the codebase where we hardcode textual representation of a token while reporting ERR_BadUnaryOp error, please use SyntaxFacts.GetText(SyntaxKind) instead.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 2]
```diff
@@ -14617,9 +14617,86 @@ static void M(object o)
...
+                //         if ((1, null) is var x4) {}
+                Diagnostic(ErrorCode.ERR_PredefinedValueTupleTypeNotFound, "(1, null)").WithArguments("System.ValueTuple`2").WithLocation(13, 13),
+                // (13,13): error CS0023: Operator 'is' cannot be applied to operand of type '(int, <null>)'
+                //         if ((1, null) is var x4) {}
+                Diagnostic(ErrorCode.ERR_BadUnaryOp, "(1, null) is var x4").WithArguments("is", "(int, <null>)").WithLocation(13, 13)
+                );
+        }
+
+        [Fact, WorkItem(13746, "https://github.com/dotnet/roslyn/issues/13746")]
+        public void ExpressionWithoutAType02()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: >ExpressionWithoutAType02 [](start = 20, length = 24)

Please add [CompilerTrait(CompilerFeature.Tuples)] attribute.

File: src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs]: I'll change it to `IsToken.Text`, just in case we decide to change it in the future.

---
In reply to: [78599437](https://github.com/dotnet/roslyn/pull/13747#discussion_r78599437) [](ancestors = 78599437)

**Comment by jcouv** [comment]
:shipit:

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Sure, done.

---
In reply to: [78599996](https://github.com/dotnet/roslyn/pull/13747#discussion_r78599996) [](ancestors = 78599996)

**Comment by AlekseyTs** [comment]
LGTM

**Comment by gafter** [comment]
@jaredpar @MattGertz I forgot that this was for the preview branch and integrated the change before getting approval for the preview branch. So I hereby beg permission. Note that this fixes a compiler crash.

**Comment by Pilchie** [comment]
Approved in @MattGertz's absence.
