### PR TITLE
Always create dedicated InitializerSemanticModel for parameter default value.

### LINKED ISSUE #16374: Bound nodes not preserved for local function parameter default values
The following proposed test (for `OutVarTests.cs`) would fail because a few of the SemanticModel APIs don't work without bound nodes, and we don't have bound nodes for the parameter default values.

I would not be surprised if we have similar issues for other contexts requiring constants.

```cs
        [Fact, WorkItem(16167, "https://github.com/dotnet/roslyn/issues/16167")]
        public void DeclarationInLocalFunctionParameterDefault()
        {
            var text = @"
class C
{
    public static void Main(int arg)
    {
        void Local2(bool b = M(M(out int z1), z1), int s2 = z1) {}
        void Local5(bool b = M(M(out var z2), z2), int s2 = z2) {}

        int x = z1 + z2;
    }
    static int M(out int z) => z = 1;
    static int M(int a, int b) => a+b;
}
";
            // the scope of an expression variable introduced in the default expression
            // of a local function parameter is that default expression.
            var compilation = CreateCompilationWithMscorlib45(text);
            compilation.VerifyDiagnostics(
                // (6,30): error CS1736: Default parameter value for 'b' must be a compile-time constant
                //         void Local2(bool b = M(M(out int z1), z1), int s2 = z1) {}
                Diagnostic(ErrorCode.ERR_DefaultValueMustBeConstant, "M(M(out int z1), z1)").WithArguments("b").WithLocation(6, 30),
                // (6,61): error CS0103: The name 'z1' does not exist in the current context
                //         void Local2(bool b = M(M(out int z1), z1), int s2 = z1) {}
                Diagnostic(ErrorCode.ERR_NameNotInContext, "z1").WithArguments("z1").WithLocation(6, 61),
                // (6,56): error CS1750: A value of type '?' cannot be used as a default parameter because there are no standard conversions to type 'int'
                //         void Local2(bool b = M(M(out int z1), z1), int s2 = z1) {}
                Diagnostic(ErrorCode.ERR_NoConversionForDefaultParam, "s2").WithArguments("?", "int").WithLocation(6, 56),
                // (7,30): error CS1736: Default parameter value for 'b' must be a compile-time constant
                //         void Local5(bool b = M(M(out var z2), z2), int s2 = z2) {}
                Diagnostic(ErrorCode.ERR_DefaultValueMustBeConstant, "M(M(out var z2), z2)").WithArguments("b").WithLocation(7, 30),
                // (7,61): error CS0103: The name 'z2' does not exist in the current context
                //         void Local5(bool b = M(M(out var z2), z2), int s2 = z2) {}
                Diagnostic(ErrorCode.ERR_NameNotInContext, "z2").WithArguments("z2").WithLocation(7, 61),
                // (7,56): error CS1750: A value of type '?' cannot be used as a default parameter because there are no standard conversions to type 'int'
                //         void Local5(bool b = M(M(out var z2), z2), int s2 = z2) {}
                Diagnostic(ErrorCode.ERR_NoConversionForDefaultParam, "s2").WithArguments("?", "int").WithLocation(7, 56),
                // (9,17): error CS0103: The name 'z1' does not exist in the current context
                //         int x = z1 + z2;
                Diagnostic(ErrorCode.ERR_NameNotInContext, "z1").WithArguments("z1").WithLocation(9, 17),
                // (9,22): error CS0103: The name 'z2' does not exist in the current context
                //         int x = z1 + z2;
                Diagnostic(ErrorCode.ERR_NameNotInContext, "z2").WithArguments("z2").WithLocation(9, 22),
                // (6,14): warning CS0168: The variable 'Local2' is declared but never used
                //         void Local2(bool b = M(M(out int z1), z1), int s2 = z1) {}
                Diagnostic(ErrorCode.WRN_UnreferencedVar, "Local2").WithArguments("Local2").WithLocation(6, 14),
                // (7,14): warning CS0168: The variable 'Local5' is declared but never used
                //         void Local5(bool b = M(M(out var z2), z2), int s2 = z2) {}
                Diagnostic(ErrorCode.WRN_UnreferencedVar, "Local5").WithArguments("Local5").WithLocation(7, 14)
                );
            var tree = compilation.SyntaxTrees[0];
            var model = compilation.GetSemanticModel(tree);

            for (int i = 1; i <= 2; i++)
            {
                var name = $"z{i}";
                var decl = GetOutVarDeclaration(tree, name);
                var refs = GetReferences(tree, name).ToArray();
                Assert.Equal(3, refs.Length);
                VerifyModelForOutVarInNotExecutableCode(model, decl, refs[0]);
                VerifyNotInScope(model, refs[1]);
                VerifyNotInScope(model, refs[2]);
                var symbol = (ILocalSymbol)model.GetDeclaredSymbol(decl.Designation);
                Assert.Equal("System.Int32", symbol.Type.ToTestDisplayString());
            }
        }
```

### LINKED ISSUE #16748: Crash in SemanticModel when an expression variable is declared in default parameter value of an Anonymous Method
```
        [Fact]
        public void DeclarationInAnonymousMethodParameterDefault()
        {
            var text = @"
class C
{
    public static void Main(int arg)
    {
        System.Action<bool, int> d1 = delegate (
                                                bool b = M(M(out int z1), z1), 
                                                int s2 = z1) 
                                            { var t = z1; };
        System.Action<bool, int> d2 = delegate (
                                                bool b = M(M(out var z2), z2), 
                                                int s2 = z2)  
                                            { var t = z2; };

        int x = z1 + z2;
        d1 = d2 = null;
    }
    static int M(out int z) => z = 1;
    static int M(int a, int b) => a+b;
}
";
            var compilation = CreateCompilationWithMscorlib45(text);

            var tree = compilation.SyntaxTrees[0];
            var model = compilation.GetSemanticModel(tree);

            var z1 = tree.GetRoot().DescendantNodes().OfType<IdentifierNameSyntax>().Where(id => id.Identifier.ValueText == "z1").First();
            Assert.Equal("", model.GetTypeInfo(z1).Type.ToTestDisplayString());
        }
```

```
Test 'DeclarationInAnonymousMethodParameterDefault' failed: 
    System.InvalidOperationException : This program location is thought to be unreachable.
	at Microsoft.CodeAnalysis.CSharp.Binder.BindOutVariableDeclarationArgument(DeclarationExpressionSyntax declarationExpression, DiagnosticBag diagnostics)
	at Microsoft.CodeAnalysis.CSharp.Binder.BindOutVariableArgument(DeclarationExpressionSyntax declarationExpression, DiagnosticBag diagnostics)
	at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentValue(DiagnosticBag diagnostics, ArgumentSyntax argumentSyntax, Boolean allowArglist, RefKind refKind)
	at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentAndName(AnalyzedArguments result, DiagnosticBag diagnostics, Boolean hadError, ArgumentSyntax argumentSyntax, Boolean allowArglist, Boolean isDelegateCreation)
	at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentsAndNames(SeparatedSyntaxList`1 arguments, DiagnosticBag diagnostics, AnalyzedArguments result, Boolean allowArglist, Boolean isDelegateCreation)
	at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentsAndNames(ArgumentListSyntax argumentListOpt, DiagnosticBag diagnostics, AnalyzedArguments result, Boolean allowArglist, Boolean isDelegateCreation)
	at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(InvocationExpressionSyntax node, DiagnosticBag diagnostics)
	at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
	at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionAllowArgList(ExpressionSyntax node, DiagnosticBag diagnostics)
	at Microsoft.CodeAnalysis.CSharp.Binder.BindValueAllowArgList(ExpressionSyntax node, DiagnosticBag diagnostics, BindValueKind valueKind)
	at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentExpression(DiagnosticBag diagnostics, ExpressionSyntax argumentExpression, RefKind refKind, Boolean allowArglist)
	at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentValue(DiagnosticBag diagnostics, ArgumentSyntax argumentSyntax, Boolean allowArglist, RefKind refKind)
	at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentAndName(AnalyzedArguments result, DiagnosticBag diagnostics, Boolean hadError, ArgumentSyntax argumentSyntax, Boolean allowArglist, Boolean isDelegateCreation)
	at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentsAndNames(SeparatedSyntaxList`1 arguments, DiagnosticBag diagnostics, AnalyzedArguments result, Boolean allowArglist, Boolean isDelegateCreation)
	at Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentsAndNames(ArgumentListSyntax argumentListOpt, DiagnosticBag diagnostics, AnalyzedArguments result, Boolean allowArglist, Boolean isDelegateCreation)
	at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(InvocationExpressionSyntax node, DiagnosticBag diagnostics)
	at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
	at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
	at Microsoft.CodeAnalysis.CSharp.Binder.BindNamespaceOrTypeOrExpression(ExpressionSyntax node, DiagnosticBag diagnostics)
	at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.Bind(Binder binder, CSharpSyntaxNode node, DiagnosticBag diagnostics)
	at Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.Bind(Binder binder, CSharpSyntaxNode node, DiagnosticBag diagnostics)
	at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node)
	at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode(CSharpSyntaxNode node)
	at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node, CSharpSyntaxNode& bindableNode, BoundNode& lowestBoundNode, BoundNode& highestBoundNode, BoundNode& boundParent)
	at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetTypeInfoWorker(CSharpSyntaxNode node, CancellationToken cancellationToken)
	at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetTypeInfoWorker(CSharpSyntaxNode node, CancellationToken cancellationToken)
	at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetTypeInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
	at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetTypeInfoFromNode(SyntaxNode node, CancellationToken cancellationToken)
	at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetTypeInfoCore(SyntaxNode node, CancellationToken cancellationToken)
	at Microsoft.CodeAnalysis.SemanticModel.GetTypeInfo(SyntaxNode node, CancellationToken cancellationToken)
	Semantics\OutVarTests.cs(28978,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.OutVarTests.DeclarationInAnonymousMethodParameterDefault()
```

### LINKED ISSUE #16757: SemanticModel.GetDeclaredSymbol(ParameterSyntax) doesn't work for parameters of a Local Function
This is going to affect IDE experience. I noticed that IDE doesn't show tooltips on the parameters and "Find All References" finds nothing when invoked on the parameters. This issue is the likely reason for the behavior.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Even for cases when the parameter is not part of a type member declaration, i.e. owned by an anonymous method or a local function.
Fixes #16748. Fixes #16374.

Also implement SemanticModel.GetDeclaredSymbol(ParameterSyntax) for parameters of a Local Function.
Fixes #16757.

@dotnet/roslyn-compiler Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

File: src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs [hunk 1]
```diff
@@ -102,6 +102,8 @@ public override CSharpSemanticModel ParentModel
 
         internal override MemberSemanticModel GetMemberModel(SyntaxNode node)
         {
+            // We do have to override this method, but should never call it because it might not do the right thing.
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs]: throw unreachable exception?

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 2]
```diff
@@ -360,7 +360,7 @@ internal BoundExpression BindValueAllowArgList(ExpressionSyntax node, Diagnostic
             out BoundExpression valueBeforeConversion)
         {
             Debug.Assert(this.InParameterDefaultValue);
-            Debug.Assert(this.ContainingMember().Kind == SymbolKind.Method || this.ContainingMember().Kind == SymbolKind.Property);
+            Debug.Assert(this.ContainingMemberOrLambda.Kind == SymbolKind.Method || this.ContainingMemberOrLambda.Kind == SymbolKind.Property);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: I didn't understand the second part of the condition (`this.ContainingMemberOrLambda.Kind == SymbolKind.Property`).
How can we get a lambda that is a property?

**Comment by jcouv** [comment]
>             if (paramList == null)

Consider removing one nesting below by doing `if (paramList == null || paramList.Parent == null) { return null; }` here.

---
Refers to: src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:688 in ac8d10c. [](commit_id = ac8d10c4726e4985b9d11e0b25080279787f3f4e, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 2 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: Containing **Member** **Or** Lambda. Property is a member.

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs [hunk 3]
```diff
@@ -736,28 +736,21 @@ internal override MemberSemanticModel GetMemberModel(SyntaxNode node)
 
                 switch (memberDecl.Kind())
                 {
-                    case SyntaxKind.DelegateDeclaration:
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs]: I'm assuming we do have tests on delegate declaration, but this code was simply no longer needed?

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs]: It only handled parameter defaults, which are handled as the last case now.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 2 above)
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: Right. Then it seems the original check (`this.ContainingMember().Kind == SymbolKind.Property`) was good, no?

---
In reply to: [98312669](https://github.com/dotnet/roslyn/pull/16789#discussion_r98312669) [](ancestors = 98312669)

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: We should check immediate symbol without skipping through anything.

---
In reply to: [98313514](https://github.com/dotnet/roslyn/pull/16789#discussion_r98313514) [](ancestors = 98313514,98312669)

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: Both checks should be performed on the same symbol.

---
In reply to: [98314006](https://github.com/dotnet/roslyn/pull/16789#discussion_r98314006) [](ancestors = 98314006,98313514,98312669)

File: src/EditorFeatures/Test2/FindReferences/FindReferencesTests.ParameterSymbol.vb [hunk 4]
```diff
@@ -534,5 +534,107 @@ end class
 </Workspace>
             Await TestAPIAndFeature(input)
         End Function
+
+        <WorkItem(16757, "https://github.com/dotnet/roslyn/issues/16757")>
+        <WpfFact, Trait(Traits.Feature, Traits.Features.FindReferences)>
+        <Test.Utilities.CompilerTrait(Test.Utilities.CompilerFeature.LocalFunctions)>
```
Comment (VSadov) [inline src/EditorFeatures/Test2/FindReferences/FindReferencesTests.ParameterSymbol.vb]: I'd add some FAR tests too. 
The parameter tests are in "FindReferencesTests.ParameterSymbol", but perhaps local functions deserve their own file/partial

**Comment by VSadov** [comment]
> 

perhaps add some comments or even rename the _memberModels field. Parameters are not exactly members.

---
Refers to: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:25 in ac8d10c. [](commit_id = ac8d10c4726e4985b9d11e0b25080279787f3f4e, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs [hunk 5]
```diff
@@ -688,12 +690,23 @@ internal override ImmutableArray<ISymbol> GetDeclaredSymbols(BaseFieldDeclaratio
                 return null;
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs]: Maybe just `if (paramList == null || paramList.Parent == null)` above?

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs [hunk 6]
```diff
@@ -840,18 +834,42 @@ private static bool IsInDocumentationComment(SyntaxNode node)
...
+                return GetOrAddModelIfContains(defaultValueSyntax, span);
             }
 
-            return null;
+            if (defaultValueSyntax != null && defaultValueSyntax.FullSpan.Contains(span))
+            {
+                var parameterSymbol = (ParameterSymbol)containing.GetDeclaredSymbol(paramDecl);
+                if ((object)parameterSymbol != null)
+                {
+                    return ImmutableInterlocked.GetOrAdd(ref _memberModels, defaultValueSyntax,
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs]: Can you put all args on different lines?

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs [hunk 7]
```diff
@@ -1124,7 +1142,8 @@ private Binder GetFieldOrPropertyInitializerBinder(FieldSymbol symbol, Binder ou
 
         private static bool IsMemberDeclaration(CSharpSyntaxNode node)
         {
-            return (node is MemberDeclarationSyntax) || (node is AccessorDeclarationSyntax) || (node is AttributeSyntax);
+            return (node is MemberDeclarationSyntax) || (node is AccessorDeclarationSyntax) ||
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs]: Consider turning this into a Kind check.

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs [hunk 8]
```diff
@@ -840,18 +834,42 @@ private static bool IsInDocumentationComment(SyntaxNode node)
             return false;
         }
 
-        // Check each parameter for a default value containing span, and create an InitializerSemanticModel for binding the default value if so.
-        // Otherwise, return null.
-        private MemberSemanticModel GetOrAddModelForParameterDefaultValue(SeparatedSyntaxList<ParameterSyntax> parameterList, TextSpan span)
+        // Check parameter for a default value containing span, and create an InitializerSemanticModel for binding the default value if so.
+        // Otherwise, return model for enclosing context.
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs]: What's the enclosing context here? The Binder for the declaration, including type parameters?

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs (hunk 6 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs]: Why should we load local functions into `_memberModel`?

Comment (agocke) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs]: It looks like there's an implicit contract in this class about going through `GetOrAddModel` and using the `_createMemberModelFunction`. Why is it safe to bypass that in this method?

File: src/EditorFeatures/Test2/FindReferences/FindReferencesTests.ParameterSymbol.vb (hunk 4 above)
Comment (AlekseyTs) [inline src/EditorFeatures/Test2/FindReferences/FindReferencesTests.ParameterSymbol.vb]: @VSadov I am not sure I am following. Could you please elaborate what tests do you have in mind?

File: src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs]: I am not comfortable doing this because it might break code that works today.

File: src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs (hunk 5 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs]: Yes, @jcouv already suggested this, I'll refactor.

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs (hunk 8 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs]: Enclosing context here is the context for the code that contains the parameter declaration. The comment doesn't talk about binders and doesn't specify what should they be. From the behavior point of view. If we are inside parameter's default, we should create special model, otherwise return what we used to return before this change.

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs (hunk 6 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs]: Is there such requirement?

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs]: @agocke Could you clarify the question, please. This code does not "load local functions into _memberModel".

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs]: I don't believe there is such a contract. From my point of view, there is a contract that member models are reused between different SemanticModel requests, this is achieved by caching them in _memberModels, which is done here in the same manner as done by GetOrAddModel. The _createMemberModelFunction simply won't do what we need to do for declarations inside method bodies, it only handles top level declarations, that is exactly why we have a bug.

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs (hunk 7 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs]: We would have to check multiple kinds for each class, it is more efficient to do a type check in this case.

**Comment by AlekseyTs** [comment]
> 

I'll add a comment, cannot suggest a better name. That is the terminology we use and the PR does not change anything about the usage of this field. 

---
In reply to: [275814007](https://github.com/dotnet/roslyn/pull/16789#issuecomment-275814007) [](ancestors = 275814007)

---
Refers to: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:25 in ac8d10c. [](commit_id = ac8d10c4726e4985b9d11e0b25080279787f3f4e, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs (hunk 6 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs]: By that I meant, add to the `_memberModels` Dictionary.

**Comment by agocke** [comment]
@AlekseyTs One thing I still don't understand: I see why we cache the semantic models for members, but why do it for parameters of lambdas and local functions? We don't cache semantic models for locals, do we?

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs (hunk 6 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs]: I am still not following the question, this code does not "add local functions into _memberModel". As I mentioned in response to a different question, member models are reused between different SemanticModel requests, this is achieved by caching them in _memberModels. That is why the code is caching the new member model that it creates, we don't want to recreate it for every SemanticModel request.

**Comment by AlekseyTs** [comment]
> One thing I still don't understand: I see why we cache the semantic models for members, but why do it for parameters of lambdas and local functions? We don't cache semantic models for locals, do we?

There is no dedicated member semantic model for locals, they are handled by member models for other "things": method body, field initializer, parameter default, etc. All member models are cached because it is our goal to reuse them, even those created for parameter default values before this change.

**Comment by agocke** [comment]
@AlekseyTs I see, that makes sense. LGTM
