### PR TITLE
Fix Equals override for CompilerDiagnostic reported by CompilerDiagnosticAnalyzer

### LINKED ISSUE #63923: CS0657 diagnostic suppressor is not reflected in IDE/errors (but it is in build output)
> **Note**: this is big issue for the (Microsoft) MVVM Toolkit, as we need this to work properly for https://github.com/CommunityToolkit/dotnet/issues/413, which I plan on shipping in the 8.1 release, which will align with the 17.4 release as well. If this is confirmed to be a bug, would it be possible to slip a fix for this in time for 17.4? Otherwise customers will have to manually suppress warnings everywhere, which would be a really really bad user experience for them. cc. @chsienki

**Version Used**: VS 17.3.3

**Steps to Reproduce**:

1. Define the following diagnostic suppressor:
```csharp
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

namespace DiagnosticSuppressorAnalyzers
{
    [DiagnosticAnalyzer(LanguageNames.CSharp)]
    public sealed class ObservablePropertyAttributeWithPropertyTargetDiagnosticSuppressor : DiagnosticSuppressor
    {
        public static readonly SuppressionDescriptor PropertyAttributeListForObservablePropertyField = new SuppressionDescriptor(
            id: "MVVMTKSPR0001",
            suppressedDiagnosticId: "CS0657",
            justification: "Fields using [ObservableProperty] can use [property:] attribute lists to forward attributes to the generated properties");

        public override ImmutableArray<SuppressionDescriptor> SupportedSuppressions => ImmutableArray.Create(PropertyAttributeListForObservablePropertyField);

        public override void ReportSuppressions(SuppressionAnalysisContext context)
        {
            foreach (Diagnostic diagnostic in context.ReportedDiagnostics)
            {
                context.ReportSuppression(Suppression.Create(PropertyAttributeListForObservablePropertyField, diagnostic));
            }
        }
    }
}

```
2. Reference the analyzer above in a blank project
3. Paste the following code:
```csharp
namespace DiagnosticSuppressorRepro;

public class SomeClass
{
    [property: Test]
    [property: AnotherTest]
    public string? Name;
}

internal class TestAttribute : Attribute
{

}

internal class AnotherTestAttribute : Attribute
{

}
```
4. Build the project

Full standalone repro: [DiagnosticSuppressorRepro.zip](https://github.com/dotnet/roslyn/files/9543149/DiagnosticSuppressorRepro.zip)

**Expected Behavior**:

No warnings should show up in either the build output, nor the IDE nor the errors list.

**Actual Behavior**:

Warnings are suppressed in the build output, but still show up in the IDE, solution explorer and errors list.

image

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #63923
For compiler diagnostics which have a non-null property bag attached to it, the `CompilerDiagnosticAnalyzer` reports a wrapping `CompilerDiagnostic`: https://github.com/dotnet/roslyn/blob/c71fa5419aa035a8d76c8a82387353e3892180a7/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilerDiagnosticAnalyzer.CompilationAnalyzer.cs#L70-L71 Equality check for this wrapping diagnostic always compared the other diagnostic with the underlying original diagnostic, but did not account for comparison with itself. I have added a unit test that fails prior to the fix and also verified the original repro case in the bug works fine after this fix.

**NOTE:** I do not have historical context on why we report this wrapping `CompilerDiagnostic` in presence of a non-null property bag on the diagnostic. We may want to consider experimenting removing this type and verify what, if anything, breaks. At the minimum, we should document the reason behind this wrapping diagnostic.
~~I'll file a tracking issue for this work~~ - Filed #63938

### CODE REVIEW

**Comment by Youssef1313** [comment]
@mavasani Recently there was a discussion on Discord about `SimpleDiagnostic` equality. The arguments are compared by reference:

https://github.com/dotnet/roslyn/blob/c71fa5419aa035a8d76c8a82387353e3892180a7/src/Compilers/Core/Portable/Diagnostic/Diagnostic_SimpleDiagnostic.cs#L165

Anything needs to be fixed there?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilerDiagnosticAnalyzer.CompilationAnalyzer.cs [hunk 1]
```diff
@@ -111,6 +111,9 @@ public override int GetHashCode()
 
                 public override bool Equals(Diagnostic? obj)
                 {
+                    if (obj is CompilerDiagnostic other)
+                        return _original.Equals(other._original);
+
                     return _original.Equals(obj);
```
Comment (cston) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilerDiagnosticAnalyzer.CompilationAnalyzer.cs:117]: >_original.Equals(obj) [](http://example.com/codeflow?start=27&length=21)

Presumably the existing code was handling wrapped == unwrapped. Are we handling unwrapped == wrapped? If we need to handle that case, that may be another reason to remove this type instead.

File: src/Compilers/CSharp/Test/Emit2/Diagnostics/GetDiagnosticsTests.cs [hunk 2]
```diff
@@ -775,5 +775,38 @@ void M1()
...
+                //     [property: Test]
+                Diagnostic(ErrorCode.WRN_AttributeLocationOnBadDeclaration, "property").WithArguments("property", "field").WithLocation(5, 6));
+            var compilationDiagnostic = compilationDiagnostics.Single();
+
+            // Verify equality for the compiler diagnostic fetched from Compilation and diagnostic reported from 'CSharpCompilerDiagnosticAnalyzer'.
+            var analyzers = ImmutableArray.Create<DiagnosticAnalyzer>(new CSharpCompilerDiagnosticAnalyzer());
+            var compilationWithAnalyzers = compilation.WithAnalyzers(analyzers);
+            var analyzerDiagnostics = await compilationWithAnalyzers.GetAnalyzerDiagnosticsAsync();
+            var analyzerDiagnostic = analyzerDiagnostics.Single();
+            Assert.Equal(analyzerDiagnostic, compilationDiagnostic);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit2/Diagnostics/GetDiagnosticsTests.cs:808]: >Assert.Equal(analyzerDiagnostic, compilationDiagnostic); [](http://example.com/codeflow?start=12&length=56)

Consider also asserting ```Assert.Equal(compilationDiagnostic, analyzerDiagnostic);```

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilerDiagnosticAnalyzer.CompilationAnalyzer.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilerDiagnosticAnalyzer.CompilationAnalyzer.cs:117]: Agree. It looks like equality is not symmetrical.

Comment (AlekseyTs) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilerDiagnosticAnalyzer.CompilationAnalyzer.cs:117]: >_original.Equals(obj) [](http://example.com/codeflow?start=27&length=21)

Perhaps component that depends on "wrapped == unwrapped" should use custom comparer that ensure that equality is symmetrical. And this implementation should return false here.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 1)

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilerDiagnosticAnalyzer.CompilationAnalyzer.cs (hunk 1 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilerDiagnosticAnalyzer.CompilationAnalyzer.cs]: Thanks @AlekseyTs. After putting more thought, I agree your suggestion is correct. I have updated the code and also the unit test to match this behavior.

Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilerDiagnosticAnalyzer.CompilationAnalyzer.cs]: Thanks, I have adjusted the check so we only support comparing two instances of _wrapped_ diagnostics. Any host that wants to compare wrapped against unwrapped should use a custom comparer.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilerDiagnosticAnalyzer.CompilationAnalyzer.cs [hunk 3]
```diff
@@ -111,7 +111,12 @@ public override int GetHashCode()
 
                 public override bool Equals(Diagnostic? obj)
                 {
-                    return _original.Equals(obj);
+                    // We only support equality check with another instance of "CompilerDiagnostic".
+                    // Hosts that want to compare compiler diagnostics from different sources,
+                    // such as with diagnostic reported from comilation.GetDiagnostics(), should
```
Comment (cston) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilerDiagnosticAnalyzer.CompilationAnalyzer.cs:116]: >comilation [](http://example.com/codeflow?start=61&length=10)

Typo.

**Comment by cston** [comment]
>             private class CompilerDiagnostic : Diagnostic

Consider using `sealed`.

---
Refers to: src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilerDiagnosticAnalyzer.CompilationAnalyzer.cs:76 in 45866ab. [](commit_id = 45866ab7bdf42cbd4a36c23ba889ea3354074df0, deletion_comment = False)

File: src/Compilers/CSharp/Test/Emit2/Diagnostics/GetDiagnosticsTests.cs [hunk 4]
```diff
@@ -775,5 +775,44 @@ void M1()
...
+            var analyzerDiagnostics = await compilationWithAnalyzers.GetAnalyzerDiagnosticsAsync();
+            var analyzerDiagnostic = analyzerDiagnostics.Single();
+
+            // Verify equality for the compiler diagnostic reported from 'CSharpCompilerDiagnosticAnalyzer' with itself.
+            Assert.Equal(analyzerDiagnostic, analyzerDiagnostic);
+
+            // Verify that diagnostic equality check fails when compared with the same compiler diagnostic
+            // fetched from 'compilation.GetDiagnostics()'. Hosts that want to compare compiler diagnostics from
+            // different sources should use custom equality comparer.
+            Assert.NotEqual(analyzerDiagnostic, compilationDiagnostic);
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit2/Diagnostics/GetDiagnosticsTests.cs:814]: >analyzerDiagnostic, compilationDiagnostic [](http://example.com/codeflow?start=28&length=41)

How do we know the underlying diagnostics would compare equal for these two?

Would it make sense to make `CompilationAnalyzer.CompilerDiagnostic` an `internal class` so we could test constructing and comparing two instances directly here?

**Comment by AlekseyTs** [comment]
Done with review pass (commit 2)

File: src/Compilers/CSharp/Test/Emit2/Diagnostics/GetDiagnosticsTests.cs (hunk 4 above)
Comment (mavasani) [reply src/Compilers/CSharp/Test/Emit2/Diagnostics/GetDiagnosticsTests.cs:817]: Thanks, I added a check to verify ToString representations for both diagnostics are equal.

File: src/Compilers/CSharp/Test/Emit2/Diagnostics/GetDiagnosticsTests.cs [hunk 5]
```diff
@@ -775,5 +775,44 @@ void M1()
             var diagnosticsByAnalyzerMap = result.SemanticDiagnostics[syntaxTree];
             Assert.Empty(diagnosticsByAnalyzerMap);
         }
+
+        [Fact]
+        [WorkItem(63923, "https://github.com/dotnet/roslyn/issues/63923")]
+        public async Task TestEqualityForCompilerAnalyzerDiagnosticWithPropertyBag()
```
[the remark this answers is not in the document]
Comment (mavasani) [reply src/Compilers/CSharp/Test/Emit2/Diagnostics/GetDiagnosticsTests.cs:781]: Thanks, I added scenario to the test to verify the diagnostic can be suppressed with a suppressor. Confirmed that this fails without the product change.

**Review by cston — APPROVED** [review]

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 3)
