### PR TITLE
Fixes duplicate namespace insertion

### LINKED ISSUE #9228: ImportAdderService adds duplicate namespace import when already exists
A user of my analyzer [reported](https://github.com/bkoelman/ResharperCodeContractNullability/issues/16) duplicate namespace insertion.

I have created a simplified repro:
1. Download the [target solution](https://github.com/imanushin/ColorsMagic)
2. Run the next console application, which dumps the duplication to console:

```csharp
using System;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Editing;
using Microsoft.CodeAnalysis.Formatting;
using Microsoft.CodeAnalysis.MSBuild;
using Microsoft.CodeAnalysis.Simplification;

namespace DuplicateUsingRepro
{
    internal class Program
    {
        private static readonly SyntaxAnnotation NamespaceImportAnnotation = new SyntaxAnnotation();

        private static void Main(string[] args)
        {
            string solutionPath = @"E:\Bart\Downloads\ColorsMagic-master\Source\ColorsMagic\ColorsMagic.sln";
            var msWorkspace = MSBuildWorkspace.Create();

            var solution = msWorkspace.OpenSolutionAsync(solutionPath).Result;
            var project = solution.Projects.Single(p => p.Name == "ColorsMagic.Common");
            var document = project.Documents.Single(d => d.Name == "GridGenerator.cs");

            Console.WriteLine("*** BEFORE ****");
            DumpUsings(document);

            var compilation = project.GetCompilationAsync().Result;
            var notNullAttribute = GetNotNullAttribute(compilation);
            var syntaxNode = GetSyntaxNode(compilation);

            var document2 = WithAttributeAsync(notNullAttribute, document, syntaxNode, CancellationToken.None).Result;

            Console.WriteLine("*** AFTER ****");
            DumpUsings(document2);
        }

        private static void DumpUsings(Document document)
        {
            var syntaxRoot = document.GetSyntaxRootAsync().Result;
            var usings = syntaxRoot.ChildNodes().OfType<UsingDirectiveSyntax>().ToList();
            var text = string.Join(Environment.NewLine, usings.Select(u => u.ToString()));
            Console.WriteLine(text);
        }

        private static INamedTypeSymbol GetNotNullAttribute(Compilation compilation)
        {
            var result = compilation.GetTypeByMetadataName("JetBrains.Annotations.NotNullAttribute");
            if (result != null)
            {
                return result;
            }

            foreach (MetadataReference reference in compilation.References)
            {
                var externalAssemblySymbol = compilation.GetAssemblyOrModuleSymbol(reference) as IAssemblySymbol;
                if (externalAssemblySymbol != null)
                {
                    result = externalAssemblySymbol.GetTypeByMetadataName("JetBrains.Annotations.NotNullAttribute");
                    if (result != null)
                    {
                        return result;
                    }
                }
            }

            throw new Exception("Not found.");
        }

        private static SyntaxNode GetSyntaxNode(Compilation compilation)
        {
            var gridGenerator = compilation.GetTypeByMetadataName("ColorsMagic.Common.GameModel.GridGenerator");
            var ctor = gridGenerator.Constructors.First();
            var prm = ctor.Parameters.Skip(1).First();
            var syntaxReference = prm.DeclaringSyntaxReferences.First();
            return syntaxReference.GetSyntax();
        }

        private static async Task<Document> WithAttributeAsync(INamedTypeSymbol attribute,
            Document document, SyntaxNode syntaxNode, CancellationToken cancellationToken)
        {
            DocumentEditor editor = await DocumentEditor.CreateAsync(document, cancellationToken).ConfigureAwait(false);

            // Add NotNull/CanBeNull/ItemNotNull/ItemCanBeNull attribute.
            SyntaxNode attributeSyntax =
                editor.Generator.Attribute(editor.Generator.TypeExpression(attribute))
                    .WithAdditionalAnnotations(Simplifier.Annotation, Formatter.Annotation, NamespaceImportAnnotation);
            editor.AddAttribute(syntaxNode, attributeSyntax);
            Document documentWithAttribute = editor.GetChangedDocument();

            // Add namespace import.
            Task<Document> addImportsAsync = ImportAdder.AddImportsAsync(documentWithAttribute,
                NamespaceImportAnnotation, null,
                cancellationToken);

            ConfiguredTaskAwaitable<Document> configuredTaskAwaitable = addImportsAsync.ConfigureAwait(false);
            Document documentWithImport = await configuredTaskAwaitable;

            return documentWithImport;
        }
    }
}
```

### PR DESCRIPTION
**Pull request by bkoelman**
Fixes #9228

### CODE REVIEW

**Comment by davkean** [comment]
@dotnet-bot test eta please

tag @dotnet/roslyn-ide

**Comment by davkean** [comment]
tag @CyrusNajmabadi

**Comment by jmarolf** [comment]
@bkoelman would it be possible to wright a regression test for this?

**Comment by jmarolf** [comment]
test vsi please

**Comment by bkoelman** [comment]
@jmarolf I've thought about writing a test for this. But, to be honest, I don't know why it fails on the supplied solution. Can you help with investigating that?

**Comment by jmarolf** [comment]
@bkoelman I'm working on getting a bug fix into Update 2 right now.  I'll take a look later this evening and see if I can explain the behavior.

File: src/Workspaces/Core/Portable/Editing/ImportAdderService.cs [hunk 1]
```diff
@@ -53,7 +53,7 @@ internal abstract class ImportAdderService : ILanguageService
             var existingNamespaces = new HashSet<INamespaceSymbol>();
             await this.GetExistingImportedNamespacesAsync(document, model, existingNamespaces, cancellationToken).ConfigureAwait(false);
 
-            var namespacesToAdd = new HashSet<INamespaceSymbol>(namespaces);
+            var namespacesToAdd = new HashSet<INamespaceSymbol>(namespaces, NamespaceEqualityComparer.Singleton);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Editing/ImportAdderService.cs]: symbols implement value equality.  is there a reason we need the comparer here?

Comment (bkoelman) [inline src/Workspaces/Core/Portable/Editing/ImportAdderService.cs]: I have tried using .Equals. When debugging, it calls into Symbol.Equals, which does reference equality:

```csharp
        // By default, we do reference equality. This can be overridden.
        public override bool Equals(object obj)
        {
            return (object)this == obj;
        }

        public bool Equals(ISymbol other)
        {
            return this.Equals((object)other);
        }
```

I chose this approach to localize the fix, without affecting lots of working code.

**Comment by bkoelman** [comment]
@jmarolf I believe I have found the root cause. The repro solution has NuGet packages that define the same type (`JetBrains.Annotations.NotNullAttribute`) in different assemblies: `portable-net4+sl4+wp7+win8\CheckContracts.dll` and `portable-net4+sl5+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1\JetBrains.Annotations.PCL328.dll`.

I do not know how to write a test for that. I tried to create two in-memory references, but that causes a compiler error. The closest I came up with is a test that defines an attribute both in source and an external assembly, which only produces a warning.

The repro solution does not produce any errors or warnings, I don't know why. So, although it is not the same scenario, the added test does fail without the fix.

File: src/Workspaces/Core/Portable/Editing/ImportAdderService.cs (hunk 1 above)
Comment (bkoelman) [inline src/Workspaces/Core/Portable/Editing/ImportAdderService.cs]: I did some more testing. Usually, namespaces are of type `Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamespaceSymbol` or `Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENestedNamespaceSymbol`. They both return true for reference equality, so the missing override for Equals does not hurt.

The scenario for this issue concerns `Microsoft.CodeAnalysis.CSharp.Symbols.MergedNamespaceSymbol` types (because the target symbol is defined in two assemblies). In that case, reference equality returns false. And because Equals is not overriden, it fails.

**Comment by davkean** [comment]
tag @dotnet/roslyn-ide can we have another look at this?

@dotnet-bot test eta please

**Comment by davkean** [comment]
Ping @dotnet/roslyn-ide again

**Comment by Pilchie** [comment]
@CyrusNajmabadi/@mattwar - what do you think?

**Comment by jmarolf** [comment]
test vsi please

**Comment by bkoelman** [comment]
I have seen no activity for some time. Is anything needed from me to get this merged in?

**Comment by Pilchie** [comment]
Ping @CyrusNajmabadi @jmarolf - can we get this sorted out and merged?

**Comment by jmarolf** [comment]
@bkoelman can you resolve the merge conflicts? Once that's done I'll validate and merge this in.

**Comment by bkoelman** [comment]
Conflicts resolved. All tests pass locally.

**Comment by jmarolf** [comment]
Thanks, taking a look

**Comment by jmarolf** [comment]
:shipit:

**Comment by jmarolf** [comment]
test vsi please

**Comment by mattwar** [comment]
You should be able to compare namespace symbols without needing to construct display strings. Though I don't think this GC noise is going to matter.

**Comment by Pilchie** [comment]
@mattwar I think the difference here is the difference between a `MergedNamespaceSymbol` and a single assembly one.

**Comment by mattwar** [comment]
@Pilchie I just meant you can compare the symbol's name and the parent's on up without needing to construct strings.

**Comment by jmarolf** [comment]
test vsip0 please
