### PR TITLE
Expand the lifetime of locals declared within CasePatternSwitchLabelSyntax to the entire switch body.

### LINKED ISSUE #15536: Bad codegen in call-forward to local function in different switch block
From #15322:

```csharp
class Program
{
    static void Main(string[] args)
    {
        object o = null;
        switch (o)
        {
            case string x:
                Assign();
                Foo();
                break;
            case int x:
                void Assign() { x = 5; }
                void Foo() => System.Console.WriteLine(x);
                break;
        }
    }
}
```

The problem seems to be getting the information for the local in CodeGen. It's not clear if this is an issue

### LINKED ISSUE #16066: Pattern matching crashes if lambda captures pattern variable
**Version Used**: 
Microsoft Visual Studio Enterprise 2017 RC
Version 15.0.26014.0 D15REL
Microsoft .NET Framework
Version 4.6.01055

**Steps to Reproduce**:
Run the following app:

```
using System.Collections.Generic;
using System.Linq;

namespace ConsoleApp2017
{
    class Program
    {
        class A
        {
        }
        
        static void Main(string[] args)
        {                           
            var dummy = new List<int>();

            switch((object)new A())
            {
                case A a:
                    {
                        dummy.Any(x => a != null);
                    }
                    break;
            }
        }
    }
}
```
**Expected Behavior**:
App just runs, no output.

**Actual Behavior**:
Null-reference on the switch statement, when trying to initialize not created instance of a hidden class <>c__DisplayClass27_0 CS$<>8__locals0;

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at ConsoleApp2017.Program.Main(String[] args) in D:\Temp\ConsoleApp2017\ConsoleApp2017\Program.cs:line 16

### PR DESCRIPTION
**Pull request by AlekseyTs**
**Customer scenario**
When a lambda or a local function references a local declared within CasePatternSwitchLabelSyntax, either compiler crashes or an application crashes at runtime because corresponding closure isn't properly initialized.  

**Bugs this fixes:** 
Fixes #15536. 
Fixes #16066. 
Tracked by VSO https://devdiv.visualstudio.com/DevDiv/_workitems?id=369824

**Workarounds, if any**
Avoid directly referencing such locals in a lambda or a local function. 

**Risk**
Low. The fix is a targeted change for a pattern switch feature, which is the only feature affected by this issue. 

**Performance impact**
Low. We allocate one additional bound tree node per switch section with locals.

**Is this a regression from a previous update?**
No. New feature.

**Root cause analysis:**
A test gap for a new feature. Tests added.

**How was the bug found?**
Customer reported.

@dotnet/roslyn-compiler, @gafter, @agocke Please review.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Lowering/StateMachineRewriter/MethodToStateMachineRewriter.cs [hunk 1]
```diff
@@ -621,6 +622,52 @@ public override BoundNode VisitBlock(BoundBlock node)
             return PossibleIteratorScope(node.Locals, () => (BoundStatement)base.VisitBlock(node));
         }
 
+        public override BoundNode VisitScope(BoundScope node)
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Lowering/StateMachineRewriter/MethodToStateMachineRewriter.cs]: There's no change to the LambdaRewriter analysis -- I assume that this Scope just naturally gets picked in the analysis when assigning variables to scopes?

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/StateMachineRewriter/MethodToStateMachineRewriter.cs]: Could you elaborate what do you expect the LambdaRewriter to do?

File: src/Compilers/CSharp/Portable/Symbols/LocalSymbol.cs [hunk 2]
```diff
@@ -25,6 +25,11 @@ protected LocalSymbol()
             get;
         }
 
+        /// <summary>
+        /// Syntax node that is used as the scope designator. Otherwise, null.
+        /// </summary>
+        internal abstract SyntaxNode ScopeDesignatorOpt { get; }
```
Comment (VSadov) [inline src/Compilers/CSharp/Portable/Symbols/LocalSymbol.cs]: would it be simpler to add another SynthesizedLocalKind for switch section locals?

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 3]
```diff
@@ -2375,5 +2375,135 @@ public static void Main(string[] args)
...
+        switch (o)
+        {
+            case int x:
+                void Assign() { x = 5; }
+                void Print() => System.Console.WriteLine(x);
+                break;
+            case string x:
+                Assign();
+                Print();
+                break;
```
Comment (VSadov) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: Do we need a test that  removing "Assign();" above would lead to definite assignment error on Print() ?

File: src/Compilers/CSharp/Portable/Symbols/LocalSymbol.cs (hunk 2 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/LocalSymbol.cs]: These are user-defined locals regardless of where they are declared, they are not synthesized. I do not believe it is appropriate to change SynthesizedLocalKind for them.

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs (hunk 3 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: In general, it would be good to have a test like this. We already might have one, @agocke can comment on this. However, I think that this scenario is out of scope of the change because result of initial binding, which is used to analyse definite assignments, is not affected by the change..

File: src/Compilers/CSharp/Portable/Lowering/StateMachineRewriter/MethodToStateMachineRewriter.cs (hunk 1 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Lowering/StateMachineRewriter/MethodToStateMachineRewriter.cs]: I assume each variable gets assigned a scope, then that scope will get added to the various dictionaries, where it will then be turned into a lambda frame.

So my reading here is that your change "just works" in the sense that your new BoundScope is chosen as the appropriate scope node and the lambda frame is built off that (including the introduction of the various proxies).

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs (hunk 3 above)
Comment (agocke) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: There should be some existing tests for this in definite assignment, including http://source.roslyn.io/#Roslyn.Compilers.CSharp.Semantic.UnitTests/FlowAnalysis/LocalFunctions.cs,698f0bb0c9ca4287 which is similar to your case.

File: src/Compilers/CSharp/Portable/Lowering/StateMachineRewriter/MethodToStateMachineRewriter.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/StateMachineRewriter/MethodToStateMachineRewriter.cs]: Lambda frames are build for life-time scopes, the added node is a visibility scope, no frames are build for it as that would not allow us to expand the lifetime of the locals that belong to it.

File: src/Compilers/CSharp/Portable/Symbols/LocalSymbol.cs (hunk 2 above)
Comment (VSadov) [inline src/Compilers/CSharp/Portable/Symbols/LocalSymbol.cs]: The name is a bit misleading. It mostly just for tagging locals into special groups. It seems we have got another kind which is tagged via ScopeDesignatorOpt.  Since we do not seem to be really using the actual syntax except for checking its kind, perhaps just adding one more SynthesizedLocalKind would be sufficient.

---
In reply to: [96762026](https://github.com/dotnet/roslyn/pull/16593#discussion_r96762026) [](ancestors = 96762026)

Comment (VSadov) [inline src/Compilers/CSharp/Portable/Symbols/LocalSymbol.cs]: I'd not require that in this change. Especially since we might not want to touch SynthesizedLocalKind this close to RTW. It might make sense to add a tracking issue on revisiting this.

---
In reply to: [96769556](https://github.com/dotnet/roslyn/pull/16593#discussion_r96769556) [](ancestors = 96769556,96762026)

**Comment by VSadov** [comment]
:shipit:

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 4]
```diff
@@ -2375,5 +2375,135 @@ public static void Main(string[] args)
...
+    {
+        Test(string.Empty);
+    }
+
+    static void Test(object o)
+    {
+        switch (o)
+        {
+            case string x:
+                Assign();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: Added test CallFromDifferentSwitchSection_05 for this scenario.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler, @gafter, @agocke Please review, need a second sign-off.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler, @gafter, @agocke Please review, need a second sign-off.

**Comment by AlekseyTs** [comment]
@MattGertz For Ask Mode sign-off.

**Comment by jcouv** [comment]
Was approved by shiproom.
