### PR TITLE
Ensure target-typed constructs are bound during initial binding in an error scenario.

### LINKED ISSUE #38686: Unexpected value exception with switch expression in error scenarios
**Version Used**: master

**Steps to Reproduce**:

```cs
using System;
#nullable enable
public static class C {
    static void M(object p) {
       // either of these would crash
        _= (C)(o switch { _ => default }); 
        _= (C)(o switch { _ => throw null }); 
    }
}
```

See the [stack trace](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATARgFgAoAYgDsBXAG2omGrgAI5z7GTsBmJ7fANl64mAYSYBvEk2m8BvACxMAsgAoA9sABWcAMYwmOgJQSpMswH0AvCpGGVBplADuASxg6AFuKZWAfDA8ENScmKlomAF9DAG5TaQiSCKA)

([sharplab repro](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMBGAsAKAMQB2ArgDYkTAlwAEcBFVuKAzNShgGxtrUDC1Ab1zURbTmwAs1ALIAKAPbAAVnADGMavICUg4aNEB6A7QCWMABaJNAM2oW4UGgHd5pACbVVCaOb36RAPoAvNSyvFoK1FBOZqrmgtQB1EEAfNRucNYQpBoAvloA3NR+/sGh4ZHRsfECiclpFgjyTtTEZNT5RSW5uLlAA=))

**Expected Behavior**: no thrown exception

**Actual Behavior**: `System.InvalidOperationException: Unexpected value 'SwitchExpression' of type 'Microsoft.CodeAnalysis.CSharp.ConversionKind'`

Discovered while working on new(). Basically, this can occur with any untyped arm which yields a valid conversion to *any* type. We should either handle the conversion in the error case or return NoConversion when the target type is invalid. If we decide to do the former, it means an unconverted switch expression *can* sneak into the next stage and we may need to take it into account everywhere.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #38686

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs [hunk 1]
```diff
@@ -1386,5 +1386,38 @@ public static (int?, int) Get(string name)
 ";
             CompileAndVerify(CreateCompilation(source, options: TestOptions.ReleaseExe).VerifyDiagnostics(), expectedOutput: "null");
         }
+
+        [Fact, WorkItem(38686, "https://github.com/dotnet/roslyn/issues/38686")]
+        public void TargetTypedSwitch_AnyTypedSwitchWithoutTargetType()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs]: >TargetTypedSwitch_AnyTypedSwitchWithoutTargetType [](start = 20, length = 49)

Please add corresponding IOperation tests to make sure that all constituent pieces are properly represented in the tree.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs]: >TargetTypedSwitch_AnyTypedSwitchWithoutTargetType [](start = 20, length = 49)

Please add a test for a scenario when similar "invalid" conversion is applied implicitly. For IOperation as well.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1)

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs]: Can you please give the specific scenario you'd like tested (i.e. the code to be compiled)?

---
In reply to: [326337342](https://github.com/dotnet/roslyn/pull/38750#discussion_r326337342) [](ancestors = 326337342)

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs [hunk 2]
```diff
@@ -172,13 +173,22 @@ private BoundExpression ConvertSwitchExpression(BoundUnconvertedSwitchExpression
...
+            Conversion conversion,
+            bool isCast,
+            ConversionGroup conversionGroup,
+            TypeSymbol destination,
+            DiagnosticBag diagnostics,
+            bool hasErrors)
         {
             Debug.Assert(conversionGroup != null);
 
             if (!conversion.IsValid)
```
[the remark this answers is not in the document]
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: No.  I'm only trying to circumvent `GenerateImplicitConversionError`, not the rest of this method when `hasErrors`.

---
In reply to: [326333161](https://github.com/dotnet/roslyn/pull/38750#discussion_r326333161) [](ancestors = 326333161)

**Comment by gafter** [comment]
@Aleksey Do you have any other comments?

@dotnet/roslyn-compiler May I please have a second review?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs]: > Can you please give the specific scenario you'd like tested (i.e. the code to be compiled)?

I don't have a specific scenario at the moment. Perhaps assigning to a variable typed ```C``` instead of using a cast operator would do, I don't have that intimate knowledge of this area (target-typing + switch expressions) in the compiler. The title of the PR says: "Ensure target-typed constructs are bound during initial binding in an error scenario." It only changes and tests explicit cast scenario. I am assuming that target typing can occur with implicit conversions as well. We need to make sure that "target-typed constructs are bound during initial binding in an error scenario" for those cases too. At the very least we should have tests verifying that. I believe you added target-typing infrastructure into the compiler and added support for switch expressions, therefore, I think you have better chances to come up with right scenarios to test than anyone else on the team. It is quite possible we already have tests like these, then we need to add IOperation tree verification.

---
In reply to: [326408524](https://github.com/dotnet/roslyn/pull/38750#discussion_r326408524) [](ancestors = 326408524,326337342)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs]: Please add test for IOperation tree limited to the switch expression of at most the containing statement (see IOperationTests_SwitchExpression.SwitchExpression_Basic for example) as opposed to a control flow graph test.

---
In reply to: [326335381](https://github.com/dotnet/roslyn/pull/38750#discussion_r326335381) [](ancestors = 326335381)

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 2)

**Comment by alrz** [comment]
This is interesting. I think we should make sure `new()` is also bound in error cases so we don't have to deal with an unconverted node in a later phase.

 Curiously why this doesn't apply to `default` or `throw`, shouldn't they also bind in error scenarios?

**Comment by AlekseyTs** [comment]
Should something special be done to expressions that are subject for target typing in BuildArgumentsForErrorRecovery method to make sure they are in a "proper" state?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs]: The IOperation test below (line 1548 and beyond) shows the IOperation tree for both switch expressions.  I am not going to modify it to test less than it already does.

---
In reply to: [326429634](https://github.com/dotnet/roslyn/pull/38750#discussion_r326429634) [](ancestors = 326429634,326335381)

Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs]: We have assertions in the compiler to ensure target typing for many other error scenarios, and they have caught hundreds of places that needed to be (and were) modified.  This specific one slipped through.  We already have tests for those other scenarios.  If you have a specific scenario you believe is not tested, I will be happy to either find a test that demonstrates it is fixed, or add a test.  In the absence of a specific suggestion, your request is not actionable.

---
In reply to: [326428679](https://github.com/dotnet/roslyn/pull/38750#discussion_r326428679) [](ancestors = 326428679,326408524,326337342)

Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs]: The title is intended to convey that we are fixing **an** error scenario, not all error scenarios.

---
In reply to: [326801296](https://github.com/dotnet/roslyn/pull/38750#discussion_r326801296) [](ancestors = 326801296,326428679,326408524,326337342)

**Comment by gafter** [comment]
`default` is handled, and `throw` does not require conversion to a target type.

---
In reply to: [533507141](https://github.com/dotnet/roslyn/pull/38750#issuecomment-533507141) [](ancestors = 533507141)

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs [hunk 3]
```diff
@@ -597,14 +597,15 @@ private void ValidateUnsafeParameters(DiagnosticBag diagnostics, ImmutableArray<
         private BoundLambda ReallyInferReturnType(NamedTypeSymbol delegateType, ImmutableArray<TypeWithAnnotations> parameterTypes, ImmutableArray<RefKind> parameterRefKinds)
         {
             var diagnostics = DiagnosticBag.GetInstance();
+            // TypeWithAnnotations
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: >// TypeWithAnnotations [](start = 12, length = 22)

Is this comment intentional?

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs [hunk 4]
```diff
@@ -597,14 +597,15 @@ private void ValidateUnsafeParameters(DiagnosticBag diagnostics, ImmutableArray<
...
             var lambdaSymbol = new LambdaSymbol(
                 Binder.Compilation,
                 Binder.ContainingMemberOrLambda,
                 _unboundLambda,
                 parameterTypes,
                 parameterRefKinds,
                 refKind: CodeAnalysis.RefKind.None,
-                returnType: default,
+                returnType: delegateType is null ? TypeWithAnnotations.Create(new ExtendedErrorTypeSymbol(this.Binder.Compilation, "", arity: 0, errorInfo: null, unreported: false)) : default,
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: > returnType: delegateType is null ? TypeWithAnnotations.Create(new ExtendedErrorTypeSymbol(this.Binder.Compilation, "", arity: 0, errorInfo: null, unreported: false)) : default, [](start = 15, length = 177)

It is not clear what is the benefit of this change. Could you please elaborate?

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs [hunk 5]
```diff
@@ -792,8 +793,17 @@ private BoundLambda ReallyBindForErrorRecovery()
 
             return
                 GuessBestBoundLambda(_bindingCache)
-                ?? GuessBestBoundLambda(_returnInferenceCache)
+                ?? rebind(GuessBestBoundLambda(_returnInferenceCache))
                 ?? ReallyInferReturnType(null, ImmutableArray<TypeWithAnnotations>.Empty, ImmutableArray<RefKind>.Empty);
+
+            // Rebind a lambda to push target conversions through the return/result expressions
+            BoundLambda rebind(BoundLambda lambda)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: >BoundLambda rebind(BoundLambda lambda) [](start = 12, length = 38)

Consider making this local function static by adding necessary pieces as explicit parameters.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 6]
```diff
@@ -234,6 +234,19 @@ internal BoundExpression BindRValueWithoutTargetType(ExpressionSyntax node, Diag
...
         }
 
+        internal BoundExpression BindToTypeForErrorRecovery(BoundExpression expression, TypeSymbol type = null)
+        {
+            if (expression is null)
+                return null;
+            var discardedDiagnostics = DiagnosticBag.GetInstance();
+            var result =
+                (!expression.NeedsToBeConverted() || expression.WasConverted) ? expression :
+                type is null ? BindToNaturalType(expression, discardedDiagnostics) :
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: >BindToNaturalType(expression, discardedDiagnostics) [](start = 31, length = 51)

```reportDefaultMissingType=false```?

**Comment by AlekseyTs** [comment]
>         private BoundExpression BindDeclarationVariables(TypeWithAnnotations declTypeWithAnnotations, VariableDesignationSyntax node, CSharpSyntaxNode syntax, DiagnosticBag diagnostics)

Consider adjusting the name of the method to reflect that its purpose is to "Bind a declaration variable **where it isn't permitted**."

---
Refers to: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:768 in e3bf28f. [](commit_id = e3bf28f85d5536ca2397b5cd0d0718c394597cfd, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 7]
```diff
@@ -7040,7 +7044,9 @@ private BoundExpression BindArrayAccess(ExpressionSyntax node, BoundExpression e
                 ? arrayType
                 : arrayType.ElementType;
 
-            return new BoundArrayAccess(node, expr, convertedArguments.AsImmutableOrNull(), resultType, hasErrors);
+            return hasErrors
+                ? new BoundArrayAccess(node, BindToTypeForErrorRecovery(expr), convertedArguments.Select(e => BindToTypeForErrorRecovery(e)).AsImmutableOrNull(), resultType, hasErrors: true)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: >AsImmutableOrNull [](start = 141, length = 17)

```AsImmutable```? Otherwise if ```convertedArguments``` could be null, ```Select``` could crash.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 8]
```diff
@@ -7040,7 +7044,9 @@ private BoundExpression BindArrayAccess(ExpressionSyntax node, BoundExpression e
...
+                : new BoundArrayAccess(node, expr, convertedArguments.AsImmutableOrNull(), resultType, hasErrors: false);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: >AsImmutableOrNull [](start = 70, length = 17)

```AsImmutable```?

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs [hunk 9]
```diff
@@ -1419,10 +1391,46 @@ private ImmutableArray<BoundExpression> BuildArgumentsForErrorRecovery(AnalyzedA
...
+                            newArguments[i] = BindToTypeForErrorRecovery(argument, getCorrespondingParameterType(i));
+                            break;
+                        }
                 }
             }
 
+            discardedDiagnostics.Free();
             return newArguments.ToImmutableAndFree();
+
+            TypeSymbol getCorrespondingParameterType(int i)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: >TypeSymbol getCorrespondingParameterType(int i) [](start = 12, length = 47)

Consider making this function static.

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs [hunk 10]
```diff
@@ -1419,10 +1391,46 @@ private ImmutableArray<BoundExpression> BuildArgumentsForErrorRecovery(AnalyzedA
                             newArguments[i] = ((OutDeconstructVarPendingInference)argument).FailInference(this);
                             break;
                         }
+                    case BoundKind.Parameter:
+                    case BoundKind.Local:
+                        {
+                            newArguments[i] = argument.WithWasConverted();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: >newArguments[i] = argument.WithWasConverted(); [](start = 28, length = 46)

It feels like this special handling of locals and parameters belongs in ```BindToTypeForErrorRecovery```. I think we would want all callers of that API to take advantage of it.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs [hunk 11]
```diff
@@ -206,8 +206,8 @@ protected override void VisitRvalue(BoundExpression node, bool isKnownToBeAnLval
                 isKnownToBeAnLvalue || node == null ||
                 !node.NeedsToBeConverted() ||
                 node.WasConverted ||
-                node.WasCompilerGenerated ||
-                methodMainNode.HasErrors, "expressions should have been converted");
+                node.WasCompilerGenerated /* ||
+                methodMainNode.HasErrors */, "expressions should have been converted");
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs]: >methodMainNode.HasErrors */ [](start = 16, length = 27)

I believe we have a policy to not check-in commented out code

File: src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IAnonymousFunctionExpression.cs [hunk 12]
```diff
@@ -201,22 +201,25 @@ static void F()
...
-      null
+    IVariableDeclarationGroupOperation (1 declarations) (OperationKind.VariableDeclarationGroup, Type: null, IsInvalid) (Syntax: 'var x = () => F();')
+      IVariableDeclarationOperation (1 declarators) (OperationKind.VariableDeclaration, Type: null, IsInvalid) (Syntax: 'var x = () => F()')
+        Declarators:
+            IVariableDeclaratorOperation (Symbol: var x) (OperationKind.VariableDeclarator, Type: null, IsInvalid) (Syntax: 'x = () => F()')
+              Initializer: 
+                IVariableInitializerOperation (OperationKind.VariableInitializer, Type: null, IsInvalid) (Syntax: '= () => F()')
+                  IAnonymousFunctionOperation (Symbol: lambda expression) (OperationKind.AnonymousFunction, Type: null, IsInvalid) (Syntax: '() => F()')
+                    IBlockOperation (1 statements) (OperationKind.Block, Type: null, IsInvalid, IsImplicit) (Syntax: 'F()')
+                      IReturnOperation (OperationKind.Return, Type: null, IsInvalid, IsImplicit) (Syntax: 'F()')
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IAnonymousFunctionExpression.cs]: >IReturnOperation (OperationKind.Return, Type: null, IsInvalid, IsImplicit) (Syntax: 'F()') [](start = 22, length = 90)

I think the previous shape of the tree is better. I suspect this change is related to the change in ```ReallyInferReturnType```. Whatever problem you are trying to address, I think we should look for an alternative solution that doesn't lead to addition of a return statement for a lambda that simply calls a void returning function. I believe there could be other scenarios as well, certain forms of conditional access, etc.

File: src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IAnonymousFunctionExpression.cs [hunk 13]
```diff
@@ -247,24 +250,27 @@ static void F()
...
+      IVariableDeclarationOperation (1 declarators) (OperationKind.VariableDeclaration, Type: null, IsInvalid) (Syntax: 'Action<int> ... = () => F()')
+        Declarators:
+            IVariableDeclaratorOperation (Symbol: System.Action<System.Int32> x) (OperationKind.VariableDeclarator, Type: null, IsInvalid) (Syntax: 'x = () => F()')
+              Initializer: 
+                IVariableInitializerOperation (OperationKind.VariableInitializer, Type: null, IsInvalid) (Syntax: '= () => F()')
+                  IDelegateCreationOperation (OperationKind.DelegateCreation, Type: System.Action<System.Int32>, IsInvalid, IsImplicit) (Syntax: '() => F()')
+                    Target: 
+                      IAnonymousFunctionOperation (Symbol: lambda expression) (OperationKind.AnonymousFunction, Type: null, IsInvalid) (Syntax: '() => F()')
+                        IBlockOperation (1 statements) (OperationKind.Block, Type: null, IsInvalid, IsImplicit) (Syntax: 'F()')
+                          IReturnOperation (OperationKind.Return, Type: null, IsInvalid, IsImplicit) (Syntax: 'F()')
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IAnonymousFunctionExpression.cs]: >IReturnOperation  [](start = 26, length = 17)

Same comment.

File: src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IAnonymousFunctionExpression.cs [hunk 14]
```diff
@@ -349,24 +355,27 @@ static void F()
...
+      IVariableDeclarationOperation (1 declarators) (OperationKind.VariableDeclaration, Type: null, IsInvalid) (Syntax: 'Action<int> ... (() => F())')
+        Declarators:
+            IVariableDeclaratorOperation (Symbol: System.Action<System.Int32> x) (OperationKind.VariableDeclarator, Type: null, IsInvalid) (Syntax: 'x = (Action ... (() => F())')
+              Initializer: 
+                IVariableInitializerOperation (OperationKind.VariableInitializer, Type: null, IsInvalid) (Syntax: '= (Action<i ... (() => F())')
+                  IDelegateCreationOperation (OperationKind.DelegateCreation, Type: System.Action<System.Int32>, IsInvalid) (Syntax: '(Action<int>)(() => F())')
+                    Target: 
+                      IAnonymousFunctionOperation (Symbol: lambda expression) (OperationKind.AnonymousFunction, Type: null, IsInvalid) (Syntax: '() => F()')
+                        IBlockOperation (1 statements) (OperationKind.Block, Type: null, IsInvalid, IsImplicit) (Syntax: 'F()')
+                          IReturnOperation (OperationKind.Return, Type: null, IsInvalid, IsImplicit) (Syntax: 'F()')
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IAnonymousFunctionExpression.cs]: >IReturnOperation [](start = 26, length = 16)

Same comment.

File: src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_InvalidExpression.cs [hunk 15]
```diff
@@ -344,17 +344,20 @@ static void F()
...
-              IInvocationOperation (void Program.F()) (OperationKind.Invocation, Type: System.Void, IsInvalid) (Syntax: 'F()')
-                Instance Receiver: 
-                  null
-                Arguments(0)
+    IVariableDeclaratorOperation (Symbol: var x) (OperationKind.VariableDeclarator, Type: null, IsInvalid) (Syntax: 'x = () => F()')
+      Initializer: 
+        IVariableInitializerOperation (OperationKind.VariableInitializer, Type: null, IsInvalid) (Syntax: '= () => F()')
+          IAnonymousFunctionOperation (Symbol: lambda expression) (OperationKind.AnonymousFunction, Type: null, IsInvalid) (Syntax: '() => F()')
+            IBlockOperation (1 statements) (OperationKind.Block, Type: null, IsInvalid, IsImplicit) (Syntax: 'F()')
+              IReturnOperation (OperationKind.Return, Type: null, IsInvalid, IsImplicit) (Syntax: 'F()')
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_InvalidExpression.cs]: >IReturnOperation [](start = 14, length = 16)

Same comment.

File: src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_InvalidExpression.cs [hunk 16]
```diff
@@ -385,14 +388,17 @@ static void F()
...
-  IBlockOperation (1 statements) (OperationKind.Block, Type: null, IsInvalid, IsImplicit) (Syntax: 'F()')
-    IExpressionStatementOperation (OperationKind.ExpressionStatement, Type: null, IsInvalid, IsImplicit) (Syntax: 'F()')
-      Expression: 
-        IInvocationOperation (void Program.F()) (OperationKind.Invocation, Type: System.Void, IsInvalid) (Syntax: 'F()')
-          Instance Receiver: 
-            null
-          Arguments(0)
+    IAnonymousFunctionOperation (Symbol: lambda expression) (OperationKind.AnonymousFunction, Type: null, IsInvalid) (Syntax: '() => F()')
+      IBlockOperation (1 statements) (OperationKind.Block, Type: null, IsInvalid, IsImplicit) (Syntax: 'F()')
+        IReturnOperation (OperationKind.Return, Type: null, IsInvalid, IsImplicit) (Syntax: 'F()')
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_InvalidExpression.cs]: >IReturnOperation [](start = 8, length = 16)

Same comment.

File: src/Compilers/CSharp/Test/Semantic/Semantics/QueryTests.cs [hunk 17]
```diff
@@ -1842,58 +1842,67 @@ static void Main(string[] args)
...
+                      Children(1):
+                          ILiteralOperation (OperationKind.Literal, Type: null, Constant: null, IsInvalid) (Syntax: 'null')
+              IAnonymousFunctionOperation (Symbol: lambda expression) (OperationKind.AnonymousFunction, Type: null, IsInvalid, IsImplicit) (Syntax: 'true')
+                IBlockOperation (1 statements) (OperationKind.Block, Type: null, IsInvalid, IsImplicit) (Syntax: 'true')
+                  IReturnOperation (OperationKind.Return, Type: null, IsInvalid, IsImplicit) (Syntax: 'true')
+                    ReturnedValue: 
+                      IConversionOperation (TryCast: False, Unchecked) (OperationKind.Conversion, Type: TKey, IsInvalid, IsImplicit) (Syntax: 'true')
+                        Conversion: CommonConversion (Exists: False, IsIdentity: False, IsNumeric: False, IsReference: False, IsUserDefined: False) (MethodSymbol: null)
+                        Operand: 
+                          ILiteralOperation (OperationKind.Literal, Type: System.Boolean, Constant: True, IsInvalid) (Syntax: 'true')
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/QueryTests.cs]: >ILiteralOperation (OperationKind.Literal, Type: System.Boolean, Constant: True, IsInvalid) [](start = 26, length = 90)

This change feels unexpected. There is nothing wrong with the literal itself, so it shouldn't be marked with IsInvalid flag.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/QueryTests.cs]: For example, the other literal below isn't changed this way.

---
In reply to: [328311167](https://github.com/dotnet/roslyn/pull/38750#discussion_r328311167) [](ancestors = 328311167)

File: src/Compilers/CSharp/Test/Semantic/Semantics/QueryTests.cs [hunk 18]
```diff
@@ -1842,58 +1842,67 @@ static void Main(string[] args)
...
                 Diagnostic(ErrorCode.ERR_TypeExpected, "null").WithLocation(8, 66),
-                // CS1001: Identifier expected
+                // file.cs(8,66): error CS1001: Identifier expected
                 //         var query = /*<bind>*/from int i in new int[] { 1 } join null on true equals true select i/*</bind>*/; //CS1031
                 Diagnostic(ErrorCode.ERR_IdentifierExpected, "null").WithLocation(8, 66),
-                // CS1003: Syntax error, 'in' expected
+                // file.cs(8,66): error CS1003: Syntax error, 'in' expected
+                //         var query = /*<bind>*/from int i in new int[] { 1 } join null on true equals true select i/*</bind>*/; //CS1031
+                Diagnostic(ErrorCode.ERR_SyntaxError, "null").WithArguments("in", "null").WithLocation(8, 66),
+                // file.cs(8,74): error CS0029: Cannot implicitly convert type 'bool' to 'TKey'
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/QueryTests.cs]: >// file.cs(8,74): error CS0029: Cannot implicitly convert type 'bool' to 'TKey' [](start = 16, length = 79)

This looks like a cascading diagnostics. Would it be possible to suppress it?

File: src/Compilers/CSharp/Test/Semantic/Semantics/QueryTests.cs [hunk 19]
```diff
@@ -2761,44 +2770,65 @@ static void Main()
 }
 ";
             var expectedDiagnostics = new DiagnosticDescription[] {
-                // CS0718: 'GC': static types cannot be used as type arguments
+                // file.cs(9,18): error CS0718: 'GC': static types cannot be used as type arguments
                 //         var q2 = string.Empty.Cast<GC>().Select(x => x);
                 Diagnostic(ErrorCode.ERR_GenericArgIsStaticClass, "string.Empty.Cast<GC>").WithArguments("System.GC").WithLocation(9, 18),
-                // CS0718: 'GC': static types cannot be used as type arguments
+                // file.cs(9,54): error CS0029: Cannot implicitly convert type 'System.GC' to 'TResult'
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/QueryTests.cs]: >// file.cs(9,54): error CS0029: Cannot implicitly convert type 'System.GC' to 'TResult' [](start = 16, length = 87)

It looks like three additional errors in this scenario are cascading and the experience would be better if they are not reported.

File: src/Compilers/CSharp/Test/Semantic/Semantics/QueryTests.cs [hunk 20]
```diff
@@ -4043,47 +4073,53 @@ public ValueTuple(T1 item1, T2 item2)
...
-                // (21,46): error CS8320: Feature 'declaration of expression variables in member initializers and queries' is not available in C# 7.2. Please use language version 7.3 or greater.
-                //         var zn = from x in a group M(x, (int z, int w) = x) by x; // error 11
-                Diagnostic(ErrorCode.ERR_FeatureNotAvailableInVersion7_2, "z").WithArguments("declaration of expression variables in member initializers and queries", "7.3").WithLocation(21, 46),
-                // (22,51): error CS8320: Feature 'declaration of expression variables in member initializers and queries' is not available in C# 7.2. Please use language version 7.3 or greater.
-                //         var zo = from x in a group x by M(x, (int z, int w) = x); // error 12
-                Diagnostic(ErrorCode.ERR_FeatureNotAvailableInVersion7_2, "z").WithArguments("declaration of expression variables in member initializers and queries", "7.3").WithLocation(22, 51)
-                );
+            //CreateCompilationWithMscorlib40AndSystemCore(csSource, parseOptions: TestOptions.Regular7_2)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/QueryTests.cs]: >//CreateCompilationWithMscorlib40AndSystemCore(csSource, parseOptions: TestOptions.Regular7_2) [](start = 12, length = 94)

It is not clear why this verification was commented out

**Comment by AlekseyTs** [comment]
>             Debug.Assert(

It looks like there are legitimate test failures caused by this assert failing.

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs:204 in e3bf28f. [](commit_id = e3bf28f85d5536ca2397b5cd0d0718c394597cfd, deletion_comment = False)

File: src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs [hunk 21]
```diff
@@ -16901,9 +16901,9 @@ static void Main()
     }
 }
 ").VerifyDiagnostics(
-                // (14,23): error CS1943: An expression of type 'int' is not allowed in a subsequent from clause in a query expression with source type 'Test.F1'.  Type inference failed in the call to 'SelectMany'.
+                // (14,13): error CS1942: The type of the expression in the from clause is incorrect.  Type inference failed in the call to 'SelectMany'.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs]: >// (14,13): error CS1942: The type of the expression in the from clause is incorrect.  Type inference failed in the call to 'SelectMany'. [](start = 16, length = 137)

Was the original error more descriptive?

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetSemanticInfoTests.cs [hunk 22]
```diff
@@ -5635,7 +5635,7 @@ public static void Main()
             Assert.Equal(1, lambdaSym.Parameters.Length);
             Assert.Equal("str", lambdaSym.Parameters[0].Name);
             Assert.Equal(TypeKind.Error, lambdaSym.Parameters[0].Type.TypeKind);
-            Assert.Equal("System.Int32", lambdaSym.ReturnType.ToTestDisplayString());
+            Assert.Equal("?", lambdaSym.ReturnType.ToTestDisplayString());
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetSemanticInfoTests.cs]: >Assert.Equal("?", lambdaSym.ReturnType.ToTestDisplayString()); [](start = 12, length = 62)

I think the original result is what we should expect.

**Comment by AlekseyTs** [comment]
I would expect this change to have no observable effect for scenarios that do not involve recently added target-typed constructs (those with lambdas, etc). However, this doesn't appear to be the case.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 3)

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs (hunk 4 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: `delegateType` is null only in the error scenario when it is being called from `ReallyBindForErrorRecovery`.  Since it will be returned into the bound tree, we need to ensure that the returned expressions have been converted.  So we produce an error type as the conversion target.  However, I am going to try another approach, as this undermines the selection of an appropriate return type for IDE scenarios.

---
In reply to: [328268618](https://github.com/dotnet/roslyn/pull/38750#discussion_r328268618) [](ancestors = 328268618)

File: src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_InvalidExpression.cs (hunk 15 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_InvalidExpression.cs]: Every return expression in a lambda must be converted to the inferred return type of the lambda.  In this case we fail to infer a return type. Perhaps we should infer `void`?

---
In reply to: [328308503](https://github.com/dotnet/roslyn/pull/38750#discussion_r328308503) [](ancestors = 328308503)

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 7 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: (this comment does not appear in CodeFlow)
That code is not changed from the version in the existing compiler.

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs (hunk 10 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: I want to avoid converting to the corresponding parameter type, and leave the type as-is.  Otherwise a large number of test scenarios are affected.

---
In reply to: [328287208](https://github.com/dotnet/roslyn/pull/38750#discussion_r328287208) [](ancestors = 328287208)

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 6 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: That would have no observable effect.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: > That would have no observable effect.

But it would avoid unnecessary  creation of diagnostics.

---
In reply to: [328380506](https://github.com/dotnet/roslyn/pull/38750#discussion_r328380506) [](ancestors = 328380506)

**Comment by gafter** [comment]
There were conversions missing in the trees previously, specifically on the returned expression from a lambda that could not be bound.  Those are intentionally added here, and that affects some existing scenarios.

---
In reply to: [535207983](https://github.com/dotnet/roslyn/pull/38750#issuecomment-535207983) [](ancestors = 535207983)

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs [hunk 23]
```diff
@@ -623,6 +628,28 @@ private BoundLambda ReallyInferReturnType(NamedTypeSymbol delegateType, Immutabl
             }
             lambdaSymbol.SetInferredReturnType(inferredReturnType.RefKind, returnType);
 
+            if (forErrorRecovery)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: >if (forErrorRecovery) [](start = 12, length = 21)

Is there a reason to do this work if inference failed?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: If there is still a chance that we have something unconverted within the bound lambda, then perhaps we want to bind for error recovery those parts without target type when the return type is ```LambdaSymbol.InferenceFailureReturnType```

---
In reply to: [328732473](https://github.com/dotnet/roslyn/pull/38750#discussion_r328732473) [](ancestors = 328732473)

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs [hunk 24]
```diff
@@ -623,6 +628,28 @@ private BoundLambda ReallyInferReturnType(NamedTypeSymbol delegateType, Immutabl
...
+                    Binder.Compilation,
+                    Binder.ContainingMemberOrLambda,
+                    _unboundLambda,
+                    parameterTypes,
+                    parameterRefKinds,
+                    refKind: CodeAnalysis.RefKind.None,
+                    returnType: returnType,
+                    diagnostics: diagnostics);
+                lambdaBodyBinder = new ExecutableCodeBinder(_unboundLambda.Syntax, lambdaSymbol, ParameterBinder(lambdaSymbol, Binder));
+                block = BindLambdaBody(lambdaSymbol, lambdaBodyBinder, diagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: >block = BindLambdaBody(lambdaSymbol, lambdaBodyBinder, diagnostics); [](start = 16, length = 68)

It looks like this statement and the two statements above is almost a copy of  similar lines above. Consider extracting them into a helper and reusing in both places.

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs [hunk 25]
```diff
@@ -623,6 +628,28 @@ private BoundLambda ReallyInferReturnType(NamedTypeSymbol delegateType, Immutabl
             }
             lambdaSymbol.SetInferredReturnType(inferredReturnType.RefKind, returnType);
 
+            if (forErrorRecovery)
+            {
+                // When binding the lambda for error recovery, we bind one more time to permit the return expressions
+                // to be converted to the inferred return type so that no unconverted expressions remain in the bound tree.
+                diagnostics = DiagnosticBag.GetInstance();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: >diagnostics = DiagnosticBag.GetInstance(); [](start = 16, length = 42)

Leaking the bag from the pool?

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 5)

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs (hunk 23 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: When binding during return type inference, there is nothing wrong with having some returned expressions unbound.  Binding them to any particular type would cause us to infer an incorrect result type.  Even in error recovery scenarios.

---
In reply to: [328733772](https://github.com/dotnet/roslyn/pull/38750#discussion_r328733772) [](ancestors = 328733772,328732473)

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs (hunk 25 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: No, `diagnostics.ToReadOnlyAndFree()` appears below.

---
In reply to: [328736220](https://github.com/dotnet/roslyn/pull/38750#discussion_r328736220) [](ancestors = 328736220)

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs (hunk 5 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: I prefer not to as it uses `this`, so acts more like an instance method.

---
In reply to: [328269540](https://github.com/dotnet/roslyn/pull/38750#discussion_r328269540) [](ancestors = 328269540)

**Comment by gafter** [comment]
@Aleksey I think I've addressed all of your concerns.  Do you have any other comments?

**Comment by gafter** [comment]
If the email threading of git notifications were not messed up, I would now change the title from

> Ensure target-typed constructs are bound during initial binding in **an** error scenario.

to

> Ensure target-typed constructs are bound during initial binding in error scenario**s**.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 6 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: >BindToNaturalType(expression, discardedDiagnostics) [](start = 31, length = 51)

Consider passing ```reportDefaultMissingType=false```. Even though that will not have any observable effect outside of the compiler, this will decrease unnecessary allocations of diagnostic.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 26]
```diff
@@ -167,7 +167,7 @@ private BoundBadExpression BadExpression(SyntaxNode syntax, LookupResultKind res
             return new BoundBadExpression(syntax,
                 resultKind,
                 symbols,
-                childNodes,
+                childNodes.SelectAsArray(e => BindToTypeForErrorRecovery(e)),
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: >BindToTypeForErrorRecovery [](start = 46, length = 26)

This lambda cannot be cached, which is something we typically try to avoid. Consider either using a foreach loop, or using the `SelectAsArray` overload that allows you pass an extra parameter and pass `this` to allow the lambda to be cached.

File: src/Compilers/CSharp/Portable/BoundTree/Constructors.cs [hunk 27]
```diff
@@ -132,7 +132,7 @@ internal partial class BoundCall
 
             Debug.Assert(arguments.IsDefaultOrEmpty || (object)receiverOpt != (object)arguments[0]);
 
-            return new BoundCall(node, receiverOpt, method, arguments, namedArguments,
+            return new BoundCall(node, binder.BindToTypeForErrorRecovery(receiverOpt), method, arguments.SelectAsArray(e => binder.BindToTypeForErrorRecovery(e)), namedArguments,
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/BoundTree/Constructors.cs]: Same lambda capture comment. Consider passing the `binder` as the argument.

File: src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IAnonymousFunctionExpression.cs [hunk 28]
```diff
@@ -201,22 +201,22 @@ static void F()
 }
 ";
             string expectedOperationTree = @"
-IVariableDeclarationGroupOperation (1 declarations) (OperationKind.VariableDeclarationGroup, Type: null, IsInvalid) (Syntax: 'var x = () => F();')
```
Comment (333fred) [inline src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IAnonymousFunctionExpression.cs]: Unless I'm missing something, the only changes in these tests are now whitespace. Consider reverting this file to avoid unnecessary changes.

File: src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_InvalidExpression.cs [hunk 29]
```diff
@@ -344,17 +344,17 @@ static void F()
 }
 ";
             string expectedOperationTree = @"
-IVariableDeclaratorOperation (Symbol: var x) (OperationKind.VariableDeclarator, Type: null, IsInvalid) (Syntax: 'x = () => F()')
```
Comment (333fred) [inline src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_InvalidExpression.cs]: Same comment.

File: src/Compilers/CSharp/Test/Semantic/Semantics/QueryTests.cs [hunk 30]
```diff
@@ -1842,56 +1842,56 @@ static void Main(string[] args)
 }
 ";
             string expectedOperationTree = @"
-ITranslatedQueryOperation (OperationKind.TranslatedQuery, Type: ?, IsInvalid) (Syntax: 'from int i  ... ue select i')
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/QueryTests.cs]: Same comment about the IOperation diffs in this file.

**Comment by 333fred** [comment]
Done review pass (commit 8)

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 6 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: This is error recovery code.  As such it is executed rarely, and maintainability is more important than micro-optimizations.

---
In reply to: [329687441](https://github.com/dotnet/roslyn/pull/38750#discussion_r329687441) [](ancestors = 329687441)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: > This is error recovery code.  As such it is executed rarely, and maintainability is more important than micro-optimizations.

Could you elaborate please on the maintainability issue that you are referring to. What is it. Why it is a problem, etc? 

---
In reply to: [330260351](https://github.com/dotnet/roslyn/pull/38750#discussion_r330260351) [](ancestors = 330260351,329687441)

Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: Generally speaking, less code, fewer parameters, etc, is easier to maintain because the reader has less to understand while maintaining the code.  Code that is more complex than necessary is a problem because it is more complex to maintain.

---
In reply to: [330262709](https://github.com/dotnet/roslyn/pull/38750#discussion_r330262709) [](ancestors = 330262709,330260351,329687441)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: I do not believe that adding an argument in this particular case creates a maintainability problem. I'll add it myself after this PR gets merged.

---
In reply to: [330264141](https://github.com/dotnet/roslyn/pull/38750#discussion_r330264141) [](ancestors = 330264141,330262709,330260351,329687441)

**Comment by gafter** [comment]
@333fred Do you have any further comments?
