### PR TITLE
prevent duplicate signature help items from surfacing to the UI

### LINKED ISSUE #1181: Signature Help chokes on duplicate overloads
Source:

```C#
class X {
	void M(int a) { }
	void M(int a) { M(1); }
}
```

Quick Info works fine, but signature help is invisible.
After pressing Control+Shift+Space, nothing appears to happen, but the up & down arrows are swallowed.

The editor throws a duplicate key exception with the following stack trace:

```
>	System.Collections.Immutable.dll!System.Collections.Immutable.ImmutableDictionary<TKey, TValue>.HashBucket.Add(TKey key, TValue value, System.Collections.Generic.IEqualityComparer<System.Collections.Generic.KeyValuePair<TKey, TValue>> keyOnlyComparer, System.Collections.Generic.IEqualityComparer<TValue> valueComparer, System.Collections.Immutable.ImmutableDictionary<TKey, TValue>.KeyCollisionBehavior behavior, System.Collections.Immutable.ImmutableDictionary<TKey, TValue>.OperationResult result)	Unknown
 	System.Collections.Immutable.dll!System.Collections.Immutable.ImmutableDictionary<TKey, TValue>.Add(TKey key, TValue value, System.Collections.Immutable.ImmutableDictionary<TKey, TValue>.KeyCollisionBehavior behavior, System.Collections.Immutable.ImmutableDictionary<TKey, TValue>.MutationInput origin)	Unknown
 	System.Collections.Immutable.dll!System.Collections.Immutable.ImmutableDictionary<TKey, TValue>.Add(TKey key, TValue value)	Unknown
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.BidirectionalMap<TKey, TValue>.Add(TKey key, TValue value)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Presentation.SignatureHelpPresenter.SignatureHelpPresenterSession.CreateSignatures(Microsoft.VisualStudio.Text.ITrackingSpan triggerSpan, int? selectedParameter)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Presentation.SignatureHelpPresenter.SignatureHelpPresenterSession.PresentItems(Microsoft.VisualStudio.Text.ITrackingSpan triggerSpan, System.Collections.Generic.IList<Microsoft.CodeAnalysis.Editor.SignatureHelpItem> signatureHelpItems, Microsoft.CodeAnalysis.Editor.SignatureHelpItem selectedItem, int? selectedParameter)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller.OnModelUpdated(Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Model modelOpt)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AbstractController<TSession, TModel, TPresenterSession, TEditorSession>.Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.IController<TModel>.OnModelUpdated(TModel result)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.ModelComputation<TModel>.OnModelUpdated(TModel result, bool updateController)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.ModelComputation<TModel>.ChainTaskAndNotifyControllerWhenFinished.AnonymousMethod__4(System.Threading.Tasks.Task[] tasks)	Unknown
```

### PR DESCRIPTION
**Pull request by brettfo**
This could cause weird issues where sig help would have the first item highlighted then trying to use the arrow keys to navigate the list would always reset to the top item and it would appear to the user that their arrow key presses were being swallowed.

The only case where duplicate items could appear in the list are during error cases, so nothing is lost from the user's perspective.  See the linked issue for an example of when this might appear.

The approach taken here was chosen because it seemed excessive to mandate that all signature help providers return a distinct set.

Fixes #1181.

Tagging @Pilchie @dpoeschl @jasonmalinowski @DustinCampbell @rchande @balajikris @jmarolf @davkean as reviewers.

### CODE REVIEW

**Comment by rchande** [comment]
Given that the editor asserts that duplicate items aren't provided (which is sounds like since the linked bug mentions DuplicateKeyException), it seems like it's fair for us to also assert that we're not asked to present duplicate items.

File: src/EditorFeatures/Test2/IntelliSense/SignatureHelpControllerTests.vb [hunk 1]
```diff
@@ -98,6 +98,18 @@ Namespace Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense
             GetMocks(controller).PresenterSession.Verify(Sub(p) p.SelectNextItem(), Times.Once)
         End Sub
 
+        <WorkItem(1181, "https://github.com/dotnet/roslyn/issues/1181")>
+        <Fact>
+        Public Sub brettfo_UpAndDownKeysShouldStillNavigateWhenDuplicateItemsAreFiltered()
```
Comment (dpoeschl) [inline src/EditorFeatures/Test2/IntelliSense/SignatureHelpControllerTests.vb]: "brettfo_"

**Comment by rchande** [comment]
Sorry, glanced too quickly at the stack in the bug; that's our (current) assertion, which still seems reasonable to me.

File: src/EditorFeatures/Core/Extensibility/SignatureHelp/SignatureHelpItems.cs [hunk 2]
```diff
@@ -72,7 +74,24 @@ internal class SignatureHelpItems
...
+                // `selectedItem` index has already been determined to be valid, it now needs to be adjusted to account for duplicates being removed.
+                // E.g.,
+                //   items = {A, A, B, B, C, D}
+                //   selectedItem = 4 (index for item C)
+                // ergo
+                //   distinctItems = {A, B, C, D}
+                //   actualItem = C
+                //   selectedItem = 2 (index for item C)
+                var actualItem = items[selectedItem.Value];
+                selectedItem = distinctItems.TakeWhile(item => item != actualItem).Count();
```
Comment (rchande) [inline src/EditorFeatures/Core/Extensibility/SignatureHelp/SignatureHelpItems.cs]: Since distinctItems is already a list, can't you just use indexof?

Comment (dpoeschl) [inline src/EditorFeatures/Core/Extensibility/SignatureHelp/SignatureHelpItems.cs]: List.IndexOf()?

File: src/EditorFeatures/Test2/IntelliSense/SignatureHelpControllerTests.vb (hunk 1 above)
Comment (brettfo) [inline src/EditorFeatures/Test2/IntelliSense/SignatureHelpControllerTests.vb]: Ahh, good find.  That made it easier to find and run just my test :)

Comment (dpoeschl) [inline src/EditorFeatures/Test2/IntelliSense/SignatureHelpControllerTests.vb]: Oh, I know. I've had to make checkins to remove such test names that I've introduced before. :smile:

Comment (brettfo) [inline src/EditorFeatures/Test2/IntelliSense/SignatureHelpControllerTests.vb]: Updated.

File: src/EditorFeatures/Core/Extensibility/SignatureHelp/SignatureHelpItems.cs (hunk 2 above)
Comment (brettfo) [inline src/EditorFeatures/Core/Extensibility/SignatureHelp/SignatureHelpItems.cs]: Fixed.

**Comment by dpoeschl** [comment]
:+1:

**Comment by rchande** [comment]
:+1:

File: src/EditorFeatures/Core/Extensibility/SignatureHelp/SignatureHelpItems.cs [hunk 3]
```diff
@@ -72,7 +74,24 @@ internal class SignatureHelpItems
...
+                // E.g.,
+                //   items = {A, A, B, B, C, D}
+                //   selectedItem = 4 (index for item C)
+                // ergo
+                //   distinctItems = {A, B, C, D}
+                //   actualItem = C
+                //   selectedItem = 2 (index for item C)
+                var actualItem = items[selectedItem.Value];
+                selectedItem = distinctItems.IndexOf(actualItem);
+                Debug.Assert(selectedItem.Value >= 0, "actual item was not part of the final list");
```
Comment (Pilchie) [inline src/EditorFeatures/Core/Extensibility/SignatureHelp/SignatureHelpItems.cs]: It's seems like it is completely reasonable for the `.Distinct` to drop this item, and not the other item which is identical.  What prevents that?

Comment (brettfo) [inline src/EditorFeatures/Core/Extensibility/SignatureHelp/SignatureHelpItems.cs]: Looking through the [reference source](http://referencesource.microsoft.com), both `.Distinct()` and `.IndexOf()` eventually use `object.Equals()` (through `EqualityComparer<T>.Default`), so I could override `.Equals()` and guarantee this.  Thoughts?

Comment (Pilchie) [inline src/EditorFeatures/Core/Extensibility/SignatureHelp/SignatureHelpItems.cs]: Well, a perhaps simpler approach would be to just inline the `.Distinct` call, making sure that you add `selectedItem` first.

Comment (brettfo) [inline src/EditorFeatures/Core/Extensibility/SignatureHelp/SignatureHelpItems.cs]: After discussing this offline, @Pilchie, @dpoeschl, and I determined that equivalence, not necessarily object reference equality, is the important factor and that `.Distinct()` and `.IndexOf()` appropriately handle that through `EqualityComparer<T>.Default`.

Comment has been updated to reflect this.

**Comment by Pilchie** [comment]
:+1:

File: src/EditorFeatures/Test2/IntelliSense/SignatureHelpControllerTests.vb [hunk 4]
```diff
@@ -98,6 +98,18 @@ Namespace Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense
             GetMocks(controller).PresenterSession.Verify(Sub(p) p.SelectNextItem(), Times.Once)
         End Sub
 
+        <WorkItem(1181, "https://github.com/dotnet/roslyn/issues/1181")>
+        <Fact>
+        Public Sub UpAndDownKeysShouldStillNavigateWhenDuplicateItemsAreFiltered()
+            Dim item = CreateItems(1).Single()
+            Dim controller = CreateController(items:={item, item}, waitForPresentation:=True)
```
Comment (dpoeschl) [inline src/EditorFeatures/Test2/IntelliSense/SignatureHelpControllerTests.vb]: Maybe pass in two equivalent but not reference equals items (in both orders)?

Comment (brettfo) [inline src/EditorFeatures/Test2/IntelliSense/SignatureHelpControllerTests.vb]: Digging in it gets a little more interesting.  Using `Items:=CreateItems(2)`, the set is kept at 2 items because `CreateItems()` creates simple `SignatureHelpItem`s and that class doesn't provide any sort of equality comparison; using the implementation here, `object.ReferenceEquals()` will return true because they're the same item; the manual repro from the bug causes `SymbolKeySignatureHelpItem` items to be created which _does_ override `bool Equals(object)`.  Hence the desired behavior with the manual repro as well as `items:={item, item}`, but not with `items:=CreateItems(2)`.

This leads us back to an earlier question: should `SignatureHelpItem` override `.Equals()`?  What does it mean to be equal?  Or should I update the test to use `SymbolKeySignatureHelpItem`?

**Comment by MattGertz** [comment]
Approved 5/28 by ML Shiproom.

File: src/EditorFeatures/Test2/IntelliSense/SignatureHelpControllerTests.vb (hunk 4 above)
Comment (brettfo) [inline src/EditorFeatures/Test2/IntelliSense/SignatureHelpControllerTests.vb]: Final update: in the case of `items:=CreateItems(2)` where both items have the same contents but aren't considered equal (or equivalent), the arrow keys won't appear to get swallowed so this is a non-issue.  Leaving the test with `items:={item, item}` as it correctly verifies that duplicate items (in this case `ReferenceEquals()`, in the manual repro case `bool Equals(object)`) are appropriately removed.
