### PR TITLE
Align the implementations of IAssemblySymbol.GivesAccessTo

### LINKED ISSUE #26459: IAssemblySymbol.GivesAccessTo returns incorrect result cross languages
The following test demonstrates that `IAssemblySymbol.GivesAccessTo` gives an incorrect result when the two assemblies result from compilations in different languages. The consequence of this bug is that the [new extension API `ISymbol.IsAccessibleWithin`](https://github.com/dotnet/roslyn/pull/26367) gives an incorrect result for some cases across languages.

``` c#
        [Fact]
        public void TestCrossCompilationIVT()
        {
            var csharpTree = CSharpSyntaxTree.ParseText(@"
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo(""VB"")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo(""CS2"")]
internal class CS
{
}
");
            var csharpTree2 = CSharpSyntaxTree.ParseText(@"
internal class CS2
{
}
");
            var vbTree = VisualBasicSyntaxTree.ParseText(@"
<assembly: System.Runtime.CompilerServices.InternalsVisibleTo(""CS"")>
<assembly: System.Runtime.CompilerServices.InternalsVisibleTo(""VB2"")>
Friend Class VB
End Class
");
            var vbTree2 = VisualBasicSyntaxTree.ParseText(@"
Friend Class VB2
End Class
");
            var csc = CSharpCompilation.Create("CS", new[] { csharpTree }, new MetadataReference[] { TestBase.MscorlibRef });
            var CS = csc.GlobalNamespace.GetMembers("CS")[0] as INamedTypeSymbol;

            var csc2 = CSharpCompilation.Create("CS2", new[] { csharpTree2 }, new MetadataReference[] { TestBase.MscorlibRef });
            var CS2 = csc2.GlobalNamespace.GetMembers("CS2")[0] as INamedTypeSymbol;

            var vbc = VisualBasicCompilation.Create("VB", new[] { vbTree }, new MetadataReference[] { TestBase.MscorlibRef });
            var VB = vbc.GlobalNamespace.GetMembers("VB")[0] as INamedTypeSymbol;

            var vbc2 = VisualBasicCompilation.Create("VB2", new[] { vbTree2 }, new MetadataReference[] { TestBase.MscorlibRef });
            var VB2 = vbc2.GlobalNamespace.GetMembers("VB2")[0] as INamedTypeSymbol;

            // The following results are correct
            Assert.True(CS.ContainingAssembly.GivesAccessTo(CS2.ContainingAssembly));
            Assert.True(VB.ContainingAssembly.GivesAccessTo(VB2.ContainingAssembly));
            Assert.True(CS.IsAccessibleWithin(CS2));
            Assert.True(VB.IsAccessibleWithin(VB2));

            // The following results are incorrect
            Assert.False(CS.ContainingAssembly.GivesAccessTo(VB.ContainingAssembly)); // should be Assert.True
            Assert.False(VB.ContainingAssembly.GivesAccessTo(CS.ContainingAssembly)); // should be Assert.True
            Assert.False(CS.IsAccessibleWithin(VB)); // should be Assert.True
            Assert.False(VB.IsAccessibleWithin(CS)); // should be Assert.True
        }
```

### LINKED ISSUE #26723: No way to compile a VB NetModule that has InternalsVisibleTo access to a strong named assembly
In C#, it is possible to compile a netmodule that has InternalsVisibleTo access to a strong named assembly. You just tell the compilation (for the netmodule) that the name of the assembly is the name of the final assembly into which it will be included. But that doesn't work in VB, because the netmodule doesn't have the correct strong name (you can't strong name a netmodule). We should adjust the VB compiler to permit this to work the same way it works in C#.

### PR DESCRIPTION
**Pull request by gafter**
It now has a shared core implementation that permits operation across IAssemblySymbol implementations.
Fixes #26459
Fixes #26723
One remaining difference is in the treatment of a strong named assembly and a weak named assembly.  C# treats them as being (capable of being) related for error recovery.  VB does not. We would like to strengthen C# but that may be a breaking change, so we're leaving it as is, at least for now.
See also #26722

### CODE REVIEW

File: src/Compilers/VisualBasic/Portable/Symbols/AssemblySymbol.vb [hunk 1]
```diff
@@ -576,48 +576,6 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols
...
-            Match
-            OneSignedOneNot
-            PublicKeyDoesntMatch
-            NoRelationshipClaimed
-        End Enum
-
-        Protected Function PerformIVTCheck(key As ImmutableArray(Of Byte), otherIdentity As AssemblyIdentity) As IVTConclusion
-            ' Implementation of this function in C# compiler is somewhat different, but we believe
-            ' that the difference doesn't affect any real world scenarios that we know/care about.
-            ' At the moment we don't feel it is worth porting the logic, but we might reconsider in the future.
```
Comment (gafter) [inline src/Compilers/VisualBasic/Portable/Symbols/AssemblySymbol.vb]: That moment has passed. But rather than porting the logic we moved it to a shared layer.

**Comment by gafter** [comment]
@dotnet/roslyn-compiler Please review this refactoring of duplicate compiler code to shared code.
@AlekseyTs I suspect you are interested in this.

File: src/Compilers/Core/Portable/IVTConclusion.cs [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+        /// </summary>
+        PublicKeyDoesntMatch,
+
+        /// <summary>
+        /// This indicates that friend access should not be granted because the other assembly 
+        /// does not name this assembly as a friend in any way whatsoever.
+        /// </summary>
+        NoRelationshipClaimed
+    }
+}
```
Comment (jcouv) [inline src/Compilers/Core/Portable/IVTConclusion.cs]: Not related to this PR, but I thought I should mention it since you're working in that area: [https://github.com/dotnet/roslyn/issues/17322](https://github.com/dotnet/roslyn/issues/17322) (improving diagnostics related to IVT)

File: src/Compilers/Core/Portable/Symbols/ISymbolExtensions_PerformIVTCheck.cs [hunk 3]
```diff
@@ -0,0 +1,99 @@
+﻿// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
+
+using System.Collections.Immutable;
+using Microsoft.CodeAnalysis.Collections;
+
+namespace Microsoft.CodeAnalysis
```
Comment (jcouv) [inline src/Compilers/Core/Portable/Symbols/ISymbolExtensions_PerformIVTCheck.cs]: Nit: Should the filename use a dot as a separator instead of underscore, to be consistent with rest of codebase?

File: src/Compilers/Core/Portable/Symbols/ISymbolExtensions_PerformIVTCheck.cs [hunk 4]
```diff
@@ -0,0 +1,99 @@
...
+            ImmutableArray<byte> assemblyWantingAccessKey,
+            ImmutableArray<byte> grantedToPublicKey)
+        {
+            // This gets a bit complicated. Let's break it down.
+            //
+            // First off, let's assume that the "other" assembly is Smith.DLL, that the "this"
+            // assembly is "Jones.DLL", and that Smith has named Jones as a friend (that is a precondition
+            // to calling this method). Whether we allow Jones to see internals of Smith depends on these four factors:
+            //
+            // q1) Is Smith strong-named?
```
Comment (jcouv) [inline src/Compilers/Core/Portable/Symbols/ISymbolExtensions_PerformIVTCheck.cs]: Nit: Could I suggest "Granting.dll" and "Wanting.dll" to align on terminology? (no "this"/"other", "Smith"/"Jones")

File: src/Compilers/Core/Portable/Symbols/ISymbolExtensions_PerformIVTCheck.cs [hunk 5]
```diff
@@ -0,0 +1,99 @@
...
+            //   a strong-named Smith that names a weak-named Jones as its friend.
+            //
+            // * If the answer to q1 is "no" and the answer to q3 is "yes" then we are in a situation where
+            //   strong-named Jones is referencing weak-named Smith, which is illegal. In the dev10 compiler
+            //   we do not give an error about this until emit time. In Roslyn we have a new error, CS7029,
+            //   which we give before emit time when we detect that weak-named Smith has given friend access
+            //   to strong-named Jones, which then references Smith. However, we still want to give friend
+            //   access to Jones for the purposes of semantic analysis.
+            //
+            // TODO: Roslyn C# does not yet give an error in other circumstances whereby a strong-named assembly
```
Comment (jcouv) [inline src/Compilers/Core/Portable/Symbols/ISymbolExtensions_PerformIVTCheck.cs]: TODO's should be replaced with open issues.

File: src/Compilers/CSharp/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.cs [hunk 6]
```diff
@@ -829,6 +829,45 @@ protected B(C o)
...
+    }
+}",
+                references: new[] { MetadataReference.CreateFromImage(other.EmitToArray()) },
+                assemblyName: "John",
+                options: TestOptions.ReleaseDll.WithCryptoKeyFile(s_keyPairFile).WithStrongNameProvider(s_defaultDesktopProvider));
+
+            // We allow John to access Paul's internal Goo even though strong-named John should not be referencing weak-named Paul.
+            // Paul has, after all, specifically granted access to John.
+
+            // TODO: During emit time we should produce an error that says that a strong-named assembly cannot reference
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/Attributes/InternalsVisibleToAndStrongNameTests.cs]: >TODO [](start = 15, length = 4)

Nit: TODO

File: src/Compilers/VisualBasic/Portable/Symbols/MetadataOrSourceAssemblySymbol.vb [hunk 7]
```diff
@@ -131,14 +131,26 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols
...
+            ' look for one that works, if none work, then return the failure for the last one examined.
             For Each key In publicKeys
-                If result <> IVTConclusion.Match Then
-                    result = PerformIVTCheck(key, potentialGiverOfAccess.Identity)
+                ' We pass the public key of this assembly explicitly so PerformIVTCheck does not need
+                ' to get it from this.Identity, which would trigger an infinite recursion.
+                result = potentialGiverOfAccess.Identity.PerformIVTCheck(Me.PublicKey, key)
+
+                If result = IVTConclusion.Match Then
+                    ' Note that C# includes  OrElse result = IVTConclusion.OneSignedOneNot
```
Comment (jcouv) [inline src/Compilers/VisualBasic/Portable/Symbols/MetadataOrSourceAssemblySymbol.vb]: >   [](start = 43, length = 2)

Nit: double space

Comment (gafter) [reply src/Compilers/VisualBasic/Portable/Symbols/MetadataOrSourceAssemblySymbol.vb]: The double space is intentional, as it precedes a code quotation.

File: src/Compilers/Core/Portable/Symbols/ISymbolExtensions_PerformIVTCheck.cs (hunk 4 above)
Comment (gafter) [reply src/Compilers/Core/Portable/Symbols/ISymbolExtensions_PerformIVTCheck.cs]: I tried doing that and now the comment is readable!

---
In reply to: [187128624](https://github.com/dotnet/roslyn/pull/26727#discussion_r187128624) [](ancestors = 187128624)

File: src/Compilers/Core/CodeAnalysisTest/GivesAccessTo.cs [hunk 8]
```diff
@@ -0,0 +1,59 @@
...
+
+            Assert.True(CS.ContainingAssembly.GivesAccessTo(CS2.ContainingAssembly));
+            Assert.True(CS.ContainingAssembly.GivesAccessTo(VB.ContainingAssembly));
+            Assert.False(CS.ContainingAssembly.GivesAccessTo(VB2.ContainingAssembly));
+
+            Assert.True(VB.ContainingAssembly.GivesAccessTo(VB2.ContainingAssembly));
+            Assert.True(VB.ContainingAssembly.GivesAccessTo(CS.ContainingAssembly));
+            Assert.False(VB.ContainingAssembly.GivesAccessTo(CS2.ContainingAssembly));
+
+        }
```
Comment (OmarTawfik) [inline src/Compilers/Core/CodeAnalysisTest/GivesAccessTo.cs]: nit: empty line
