### PR TITLE
Caller of an async local function cannot expect any of the callee’s code to execute

### LINKED ISSUE #43697: Definite assignment bug when not awaiting an async closure
**Version Used**: master as of 10th march 2020

**Steps to Reproduce**:

```csharp
using System;
using System.Threading.Tasks;

public class C {
    public void M() {
        bool a;
        M1();
        Console.WriteLine(a);
        async Task M1()
        {
            if ("" == String.Empty)
            {
                throw new Exception();
            }
            else
            {
                a = true;
            }
        }
    }
}
```

**Expected Behavior**:

error CS0165: Use of unassigned local variable 'a'

**Actual Behavior**:

Compiles without error

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #43697.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@RikkiGibson, @dotnet/roslyn-compiler Please review

**Comment by AlekseyTs** [comment]
@RikkiGibson, @dotnet/roslyn-compiler Please review

**Comment by RikkiGibson** [comment]
Should we update the breaking change doc in this PR?
Will we perform any test insertions to VS or runtime before merging to gauge the impact of the breaking change?

**Review by RikkiGibson — APPROVED** [review]

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 1)

**Comment by AlekseyTs** [comment]
@RikkiGibson 
>Will we perform any test insertions to VS or runtime before merging to gauge the impact of the breaking change?

It looks like test insertion succeeded - https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6814361&view=results

**Comment by RikkiGibson** [comment]
That indicates success of creating the insertion, located at https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/429093. We should see the results for that by this afternoon.

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs [hunk 1]
```diff
@@ -1320,7 +1320,11 @@ protected void VisitLocalFunctionUse(LocalFunctionSymbol symbol, SyntaxNode synt
             if (isCall)
             {
                 Join(ref State, ref localFunctionState.StateFromBottom);
-                Meet(ref State, ref localFunctionState.StateFromTop);
+
+                if (!symbol.IsAsync)
+                {
+                    Meet(ref State, ref localFunctionState.StateFromTop);
```
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:1326]: > Should we have a follow-up issue to track the decision to also perform this Meet when the call is "immediately awaited"?

That is a language design change that I am not planning to champion at the moment.

File: docs/compilers/CSharp/Compiler Breaking Changes - DotNet 7.md [hunk 2]
```diff
@@ -1,5 +1,32 @@
 # This document lists known breaking changes in Roslyn after .NET 6 all the way to .NET 7.
 
+## Caller of an async local function cannot expect any of the callee�s code to execute.
```
Comment (jcouv) [inline docs/compilers/CSharp/Compiler Breaking Changes - DotNet 7.md:3]: nit: GitHub diff shows some unicode character as the apostrophe for "callee's". Is that intentional?

File: docs/compilers/CSharp/Compiler Breaking Changes - DotNet 7.md [hunk 3]
```diff
@@ -1,5 +1,32 @@
...
+
+***Introduced in Visual Studio 2022 version 17.5***
+
+See https://github.com/dotnet/roslyn/issues/43697 for the rational.
```
Comment (jcouv) [inline docs/compilers/CSharp/Compiler Breaking Changes - DotNet 7.md:7]: typo: rationale

Comment (jcouv) [inline docs/compilers/CSharp/Compiler Breaking Changes - DotNet 7.md:7]: Consider adding a one sentence summary, maybe something like:
For definite assignment analysis, invocations of async local functions are no longer treated as being awaited and therefore the local function is not considered executed.

Let's send an email as FYI to compat council for new compat break.

It would be good to add a note to the [spec](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-7.0/local-functions.md) even though it's an older/incomplete document, and tag Rex on the edit (so that definite assignment rules in standard can reflect this change as appropriate).

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 3)

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 5)
