### PR TITLE
Disabled cross function inlining if used the same type parameter name.

### LINKED ISSUE #21907: 'Inline out variable' breaks code logic
**Version Used**: 
```
Microsoft Visual Studio Professional 2017 
Version 15.3.3
VisualStudio.15.Release/15.3.3+26730.12
Microsoft .NET Framework
Version 4.7.02053
```

**Steps to Reproduce**:

Paste the following code into VS:
```cs
using System;

class Program
{
  static void Main(string[] args)
  {
    Method<string>();
  }

  public static void Method<T>()
  { 
    T t;
    void Local<T>()
    {
      Out(out t);
      Console.WriteLine(t);
    }
    Local<int>();
  }

  public static void Out<T>(out T t) => t = default;
}
```

**Expected Behavior**:
No suggestion to inline the variable `t` as its type cannot be used explicitly inside the `Local` function

**Actual Behavior**:
Roslyn suggests to change the code into following:
```cs
using System;

class Program
{
  static void Main(string[] args)
  {
    Method<string>();
  }

  public static void Method<T>()
  {
    void Local<T>()
    {
      Out(out T t);
      Console.WriteLine(t);
    }
    Local<int>();
  }

  public static void Out<T>(out T t) => t = default;
}
```

Which does not behave the same as Roslyn changes type argument of the `Out(out t)`  invocation from 'string' to 'int' so the program above prints `0` instead of an empty line.

### PR DESCRIPTION
**Pull request by zaytsev-victor**
**Customer scenario**
Cross function inlining in case of generic functions with the same type parameter name may breaks code logic

**Bugs this fixes:**
Fixes #21907 

**Risk**
Low

**Is this a regression from a previous update?**
No

**Root cause analysis:**
Not covered case

**How was the bug found?**
customer reported

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @dotnet/roslyn-ide for review.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -194,6 +194,17 @@ private void AnalyzeSyntaxNode(SyntaxNodeAnalysisContext context, INamedTypeSymb
             // rewrite things.
             var outArgumentScope = GetOutArgumentScope(argumentExpression);
 
+            if (enclosingBlockOfLocalStatement != outArgumentScope &&
+                enclosingBlockOfLocalStatement.Parent.IsKind(SyntaxKind.LocalFunctionStatement, SyntaxKind.MethodDeclaration) &&
```
Comment (sharwell) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationDiagnosticAnalyzer.cs]: ❓ Does this still catch cases like this?

```csharp
  public static void Method<T>()
  { 
    T t;
    void Local<T>()
    {
      { // <-- note this set of added braces
        Out(out t);
        Console.WriteLine(t);
      }
    }
    Local<int>();
  }
```

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationDiagnosticAnalyzer.cs [hunk 2]
```diff
@@ -433,5 +444,23 @@ private SyntaxNode GetOutArgumentScope(SyntaxNode argumentExpression)
             // No accesses detected
             return false;
         }
+
+        private static bool HasTypeParameter(SyntaxNode node, ILocalSymbol symbol)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationDiagnosticAnalyzer.cs]: I would prefer this to be something more like ```HasTypeParameterWithName(SyntaxNode node, string name)```  You don't really need the symbol at all except to get the name of it.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationDiagnosticAnalyzer.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationDiagnosticAnalyzer.cs]: And also:

```c#
 public static void Method<T>()
  {
   { 
    T t;
    void Local<T>()
    {
      { // <-- note this set of added braces
        Out(out t);
        Console.WriteLine(t);
      }
    }
    Local<int>();
   }
  }
```

**Comment by zaytsev-victor** [comment]
I found that we have the same issue with 'Move declaration near reference' refactoring.
Should I file another issue or it can be fixed in scope of this bug?

Probably it should be a helper method to reuse the same logic. Could you please suggest best place for it?

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationDiagnosticAnalyzer.cs [hunk 3]
```diff
@@ -194,6 +194,19 @@ private void AnalyzeSyntaxNode(SyntaxNodeAnalysisContext context, INamedTypeSymb
             // rewrite things.
             var outArgumentScope = GetOutArgumentScope(argumentExpression);
 
+            if (enclosingBlockOfLocalStatement != outArgumentScope)
+            {
+                var localFunctionOrMethodDeclaration = enclosingBlockOfLocalStatement.AncestorsAndSelf().FirstOrDefault(node => node.IsKind(SyntaxKind.LocalFunctionStatement, SyntaxKind.MethodDeclaration));
+                var localFunctionStatement = outArgumentScope.AncestorsAndSelf().FirstOrDefault(node => node.IsKind(SyntaxKind.LocalFunctionStatement));
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationDiagnosticAnalyzer.cs]: this can be simplified to ```outArgumentScope.FirstAncestorOrSelf<LocalFunctionStatementSyntax>();```

**Comment by CyrusNajmabadi** [comment]
> I found that we have the same issue with 'Move declaration near reference' refactoring.
Should I file another issue or it can be fixed in scope of this bug?

I would file a new bug personally.  But i think it would also be fine to just roll into this fix since they're related.

> Probably it should be a helper method to reuse the same logic. Could you please suggest best place for it?

First, i'd like to see that helper method.  The code may have to be different enough that merging isn't really doable.  In which case it can stay in one place.  If it can be merged (which you can demonstrate by having one analyzer expose it as a internal-static member that you use from the other), then we can figure out where it should go.

File: src/Features/CSharp/Portable/MoveDeclarationNearReference/CSharpMoveDeclarationNearReferenceCodeRefactoringProvider.cs [hunk 4]
```diff
@@ -54,5 +55,42 @@ protected override SyntaxToken GetIdentifierOfVariableDeclarator(VariableDeclara
 
             return true;
         }
+
+        protected override bool CanMoveToBlock(ILocalSymbol localSymbol, SyntaxNode currentBlock, SyntaxNode destinationBlock)
```
Comment (zaytsev-victor) [inline src/Features/CSharp/Portable/MoveDeclarationNearReference/CSharpMoveDeclarationNearReferenceCodeRefactoringProvider.cs]: I think it should be moved to helper.
@CyrusNajmabadi Could you please suggest a proper place for it?

**Comment by CyrusNajmabadi** [comment]
Best place i can thnk of is to put it on ISemanticFactsService and call it something like "CanSafelyMoveLocalToBlock".  

*Alternatively* as this appears to be purely a C# issue, you could just add a new ILocalSymbolExtensions.cs file and make this an extension method on ILocalSymbol.  This specific file would go in CSharpWorkspace next to Extensions\ITypeSymbolExtensions.cs

I'm leaning toward the former.  In the future there may be VB checks we need to perform.  And then we'll want a single location to dispatch this across both languages.

**Comment by sharwell** [comment]
@MattGertz for ask mode

**Comment by sharwell** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please
