### PR TITLE
Produce much better code for CInt(Fix(number))

### LINKED ISSUE #25692: Produce much better code for CInt(Fix(number))
We believe the code produced for `CInt(Fix(number))` can be significantly improved by emitting an IL instruction for simply truncating the floating-point number to its integral part.
1. Check this assumption, and
2. Change the Roslyn VB compiler to produce the more efficient sequence

This is a compiler-only change that requires no change to the VB language specification, as the emitted code would be functionally equivalent.

See also https://github.com/dotnet/vblang/issues/86 and https://github.com/dotnet/vblang/issues/82

/cc @AnthonyDGreen

### PR DESCRIPTION
**Pull request by gafter**
Fixes #25692

@dotnet/roslyn-compiler May I please have a couple of reviews of this smallish VB code-gen improvement?
/cc @KathleenDollard FYI

### CODE REVIEW

**Comment by jcouv** [comment]
It looks like no existing test was affected, so it's not obvious what the old IL was. Could you share an example to illustrate the point of the change?

**Comment by gafter** [comment]
Here is an example of the old code:

``` none
.method public static int32  DoubleToInteger(float64 number) cil managed
{
  // Code size       13 (0xd)
  .maxstack  8
  IL_0000:  ldarg.0
  IL_0001:  call       float64 [Microsoft.VisualBasic]Microsoft.VisualBasic.Conversion::Fix(float64)
  IL_0006:  call       float64 [mscorlib]System.Math::Round(float64)
  IL_000b:  conv.ovf.i4
  IL_000c:  ret
} // end of method Module1::DoubleToInteger
```

File: src/Compilers/Core/Portable/WellKnownMembers.cs [hunk 1]
```diff
@@ -2968,14 +2968,29 @@ static WellKnownMembers()
...
                      0,                                                                                                                                         // Method Signature
                      (byte)SignatureTypeCode.TypeHandle, (byte)SpecialType.System_Void,
 
+                 // Microsoft.VisualBasic.Conversion.Fix(Number As System.Single)
+                (byte)(MemberFlags.Method | MemberFlags.Static),                                                                                    // Flags
+                 (byte)WellKnownType.ExtSentinel, (byte)(WellKnownType.Microsoft_VisualBasic_Conversion - WellKnownType.ExtSentinel),               // DeclaringTypeId
+                0,                                                                                                                                  // Arity
+                    1,                                                                                                                              // Method Signature
+                    (byte)SignatureTypeCode.TypeHandle, (byte)SpecialType.System_Single,                                    // Return type
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/WellKnownMembers.cs]: >// Return type [](start = 124, length = 14)

Please align the comment with a comment on the previous line

File: src/Compilers/Core/Portable/WellKnownMembers.cs [hunk 2]
```diff
@@ -2968,14 +2968,29 @@ static WellKnownMembers()
...
+                    (byte)SignatureTypeCode.TypeHandle, (byte)SpecialType.System_Single,
+
+                // Microsoft.VisualBasic.Conversion.Fix(Number As System.Double)
+                (byte)(MemberFlags.Method | MemberFlags.Static),                                                                                    // Flags
+                 (byte)WellKnownType.ExtSentinel, (byte)(WellKnownType.Microsoft_VisualBasic_Conversion - WellKnownType.ExtSentinel),               // DeclaringTypeId
+                0,                                                                                                                                  // Arity
+                    1,                                                                                                                              // Method Signature
+                    (byte)SignatureTypeCode.TypeHandle, (byte)SpecialType.System_Double,                                    // Return type
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/WellKnownMembers.cs]: >// Return type [](start = 124, length = 14)

Same comment

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.vb [hunk 3]
```diff
@@ -1295,19 +1295,24 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
         Private Function RewriteFloatingToIntegralConversion(node As BoundConversion, typeFrom As TypeSymbol, underlyingTypeTo As TypeSymbol) As BoundExpression
             Debug.Assert(typeFrom.IsFloatingType() AndAlso underlyingTypeTo.IsIntegralType())
             Dim result As BoundExpression = node
+            Dim operand = node.Operand
 
-            Dim mathRound As MethodSymbol
-            ' Call Math.Round method to enforce VB style rounding.
+            ' CInt(Fix(number)) and the like can be simplified to just truncate the number to the integral type
+            If TypeOf operand Is BoundCall Then
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.vb]: >TypeOf operand Is BoundCall [](start = 15, length = 27)

Consider replacing this with a kind check, otherwise the type check is done twice

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.vb [hunk 4]
```diff
@@ -1334,6 +1339,21 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
             Return result
         End Function
 
+        Private Function IsFixInvocation(node As BoundCall) As Boolean
+            If node.Method.Name <> "Fix" Then
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.vb]: >node.Method.Name <> "Fix" [](start = 15, length = 25)

It is better to explicitly call an API from string so that readers won't be left thinking what Option Compare is in effect and what king of comparison as actually intended here.

File: src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenExpression.vb [hunk 5]
```diff
@@ -0,0 +1,519 @@
...
+        CheckDouble(Integer.MaxValue + 0D, Integer.MaxValue)
+        CheckDouble(Integer.MaxValue + 1D, Integer.MinValue)  ' overflow
+        CheckDouble(Integer.MaxValue + 2D, Integer.MinValue)  ' overflow
+
+        Console.WriteLine("done")
+    End Sub
+
+    Public Shared Sub CheckSingle(s As Single, expected As Integer)
+        Dim result As Integer = SingleToInteger(s)
+        If result &lt;> expected
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenExpression.vb]: >&lt;> [](start = 18, length = 5)

Consider using CDATA around the entire code snippet to avoid using XML entities and make source code for the test scenario readable

File: src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenExpression.vb [hunk 6]
```diff
@@ -0,0 +1,519 @@
...
+<compilation>
+    <file name="a.vb">
+Option Strict On
+
+Imports System
+Imports Microsoft.VisualBasic
+
+Class C1
+    Public Shared Function SingleToSByte(number as Single) As SByte
+        Return CSByte(Fix(number))
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenExpression.vb]: >Fix(number) [](start = 22, length = 11)

It looks like these tests cover only explicit conversions. I think we also need to have tests for implicit conversions applied to a Fix calls.

**Comment by KathleenDollard** [comment]
👍 

Thank you!!

File: src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenExpression.vb [hunk 7]
```diff
@@ -0,0 +1,519 @@
...
+        Return CLng(Fix(number))
+    End Function
+    Public Shared Function SingleToULong(number as Single) As ULong
+        Return CULng(Fix(number))
+    End Function
+    Public Shared Function DoubleToULong(number as Double) As ULong
+        Return CULng(Fix(number))
+    End Function
+    Public Shared Sub Main()
+        CheckSingle(Integer.MinValue - 65F, Integer.MinValue)
```
[the remark this answers is not in the document]
Comment (gafter) [reply src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenExpression.vb]: At this point we'd just be stress-testing the CLR's implementation of the `conv` instruction.

File: src/Compilers/Core/Portable/WellKnownMembers.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/Core/Portable/WellKnownMembers.cs]: This indentation was intentional, and corresponds to the indentation on the left.

**Comment by gafter** [comment]
test windows_debug_unit32_prtest please

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.vb [hunk 8]
```diff
@@ -1295,19 +1295,24 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
             Debug.Assert(typeFrom.IsFloatingType() AndAlso underlyingTypeTo.IsIntegralType())
             Dim result As BoundExpression = node
+            Dim operand = node.Operand
 
-            Dim mathRound As MethodSymbol
-            ' Call Math.Round method to enforce VB style rounding.
+            ' CInt(Fix(number)) and the like can be simplified to just truncate the number to the integral type
+            If TypeOf operand Is BoundCall Then
+                Dim callOperand = DirectCast(operand, BoundCall)
+                If IsFixInvocation(callOperand) Then
```
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.vb]: > If you think so, please open an issue for it.

Why should we create more paperwork if you already changing the area and these scenarios fall into the same category - more efficient code emitted for converting floating point numbers to integrals?

---
In reply to: [188351960](https://github.com/dotnet/roslyn/pull/26846#discussion_r188351960) [](ancestors = 188351960)

File: src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenExpression.vb (hunk 7 above)
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenExpression.vb]: > At this point we'd just be stress-testing the CLR's implementation of the conv instruction.

I don't think this is the only thing we would be doing. We would also make sure that there is no behavior change for scenarios like these and simply assuming that this is the case is not good enough, at least for me.

---
In reply to: [188352169](https://github.com/dotnet/roslyn/pull/26846#discussion_r188352169) [](ancestors = 188352169)

File: src/Compilers/Core/Portable/WellKnownMembers.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/Core/Portable/WellKnownMembers.cs]: Look at the alignment on the left. The method signature part is indented differently. The same is true here for the comment on the right.

---
In reply to: [188366864](https://github.com/dotnet/roslyn/pull/26846#discussion_r188366864) [](ancestors = 188366864,188352605)

Comment (gafter) [reply src/Compilers/Core/Portable/WellKnownMembers.cs]: The indentation here is intentional. The data for the method signature are not indented the same on the left, and the comments for the method signature, forming a separate self-contained data block, are indented differently on the right.

---
In reply to: [188368103](https://github.com/dotnet/roslyn/pull/26846#discussion_r188368103) [](ancestors = 188368103,188366864,188352605)

Comment (AlekseyTs) [reply src/Compilers/Core/Portable/WellKnownMembers.cs]: > Look at the alignment on the left. The method signature part is indented differently. The same is true here for the comment on the right.

Please follow the established pattern in this file and align comments for all lines involved into description of each member. Or remove the comment, if you arguing that no where else in the file return type lines have comments. 

---
In reply to: [188368103](https://github.com/dotnet/roslyn/pull/26846#discussion_r188368103) [](ancestors = 188368103,188366864,188352605)

Comment (AlekseyTs) [reply src/Compilers/Core/Portable/WellKnownMembers.cs]: Please do not mark this thread as resolved, because the concern is not addressed 

---
In reply to: [188373239](https://github.com/dotnet/roslyn/pull/26846#discussion_r188373239) [](ancestors = 188373239,188368103,188366864,188352605)

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.vb (hunk 8 above)
[the remark this answers is not in the document]
Comment (jaredpar) [reply src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.vb]: Don't see a reason to open a new issue here: either we fix this now or let it go. My 2 cents: lets just fix it as it's pretty straight forward. 

---
In reply to: [188366095](https://github.com/dotnet/roslyn/pull/26846#discussion_r188366095) [](ancestors = 188366095,188351960)

[the remark this answers is not in the document]
Comment (gafter) [reply src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.vb]: We had this discussion in the VB LDM. The consensus was to fix just this one case. I'm not opposed to other cases being fixed, but that's not what I'm trying to accomplish here.

**Comment by gafter** [comment]
test windows_release_unit32_prtest please

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.vb (hunk 8 above)
[the remark this answers is not in the document]
Comment (gafter) [reply src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.vb]: Filed [https://github.com/dotnet/roslyn/issues/26907](https://github.com/dotnet/roslyn/issues/26907) for optimizing calls to other numeric functions such as Math.Ceiling.

---
In reply to: [188389072](https://github.com/dotnet/roslyn/pull/26846#discussion_r188389072) [](ancestors = 188389072,188386888)

File: src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.vb [hunk 9]
```diff
@@ -1334,6 +1339,22 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
             Return result
         End Function
 
+        Private Function IsFixInvocation(node As BoundCall) As Boolean
+            ' Quick test to eliminate most calls to something other that Conversion.Fix
+            If Not "Fix".Equals(node.Method.Name) Then
```
Comment (jcouv) [inline src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.vb]: Should this comparison be case-insensitive (VB-style)?

Comment (gafter) [reply src/Compilers/VisualBasic/Portable/Lowering/LocalRewriter/LocalRewriter_Conversion.vb]: No. That is the actual name of the method. This is not a name lookup.
