### PR TITLE
Avoid unnecessary up-front captures to temps while lowering indexer access that uses “Index Pattern”

### LINKED ISSUE #54085: Non spec-conformant eval order for System.Index Expression
**Version Used**: https://github.com/dotnet/roslyn/commit/7475a4a86589e1fd9733e67e20b4ea5778ecd228

**Steps to Reproduce**:
Compile the following code:
```csharp
using System;

class CollectionX
{
    private int[] _array = new[] { 1, 2, 3 };

    public int Length
    {
        get
        {
            Console.WriteLine("Length ");
            return _array.Length;
        }
    }

    public ref int this[int index]
    {
        get
        {
            Console.WriteLine("Indexer get");
            return ref _array[index];
        }
    }
}

static class SideEffect
{
    static CollectionX Get()
    {
        Console.WriteLine("Get ");
        return new CollectionX();
    }
    static int GetIdx()
    {
        Console.WriteLine("GetIdx ");
        return 1;
    }

    public static void Main()
    {
        int i2 =  Get()[Index.FromEnd(GetIdx())];
        Console.WriteLine(i2);
    }
}
```

**Expected Behavior**:
It should [print](https://dotnetfiddle.net/du5MLd) as described in [spec](https://github.com/dotnet/csharplang/blob/22a8d8976ee245da0390e8a4e63f2e029ff99f14/proposals/csharp-8.0/ranges.md):

```
Get 
GetIdx 
Length 
Indexer get
3
```

From spec:
> Otherwise, it will be translated as expr.GetOffset(receiver.Length)

so `expr` should be evaluated first, then `receiver.Length`

**Actual Behavior**:
It prints actually:
```
Get 
Length 
GetIdx 
Indexer get
3
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #54085, ensures order of evaluation that matches language specification.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs [hunk 1]
```diff
@@ -220,37 +220,16 @@ private BoundSequence VisitIndexOrRangePatternIndexerAccess(BoundIndexOrRangePat
...
-
-            if (usedLength)
-            {
-                locals.Add(lengthLocal.LocalSymbol);
-                sideEffects.Add(lengthStore);
-            }
-
-            locals.Add(indexLocal.LocalSymbol);
-            sideEffects.Add(indexStore);
+            var indexAccess = MakePatternIndexOffsetExpression(argument, F.Property(receiverLocal, lengthOrCountProperty), out _);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs:223]: Should the "Lowered code:" comment above be adjusted?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs:223]: > Should the "Lowered code:" comment above be adjusted?

I'll remove the comment because it is redundand.

File: src/Compilers/CSharp/Test/Emit/CodeGen/IndexAndRangeTests.cs [hunk 2]
```diff
@@ -3104,5 +3039,64 @@ static string Print(Range? arg)
...
+        return 1;
+    }
+
+    public static void Main()
+    {
+        int i2 =  Get()[Index.FromEnd(GetIdx())];
+        Console.WriteLine(i2);
+    }
+}
+", TestOptions.ReleaseExe); ;
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Emit/CodeGen/IndexAndRangeTests.cs:3092]: nit: Looks like there's an unnecessary empty statement here.

File: src/Compilers/CSharp/Test/Emit/CodeGen/IndexAndRangeTests.cs [hunk 3]
```diff
@@ -3104,5 +3039,64 @@ static string Print(Range? arg)
...
+    }
+    static int GetIdx()
+    {
+        Console.WriteLine(""GetIdx"");
+        return 1;
+    }
+
+    public static void Main()
+    {
+        int i2 =  Get()[Index.FromEnd(GetIdx())];
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Emit/CodeGen/IndexAndRangeTests.cs:3088]: Is there any value in having a version of the test which uses `Get()[^GetIdx()]`?

**Review by RikkiGibson — APPROVED** [review]
LGTM modulo response to the pending comments.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Need a second review.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

**Review by cston — APPROVED** [review]
