### PR TITLE
Ref safety analysis should take into consideration defensive copy of a call receiver performed by IL gen.

### LINKED ISSUE #64776: The compiler should report an error about references to out-of-scope stack memory generated by `[UnscopedRef]` and defensively copied struct.
**Version Used**: 

.NET7 RC2
C# 11

**Steps to Reproduce**:

Execute the following code.

It occurs accessing to undefined memory (the stack memory already out of scope). 
Remember that there is no `unsafe` keyword in this code.

```cs
using System;
using System.Runtime.CompilerServices;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.InteropServices;

namespace Net7Test;

internal class Program
{
    private static readonly Vec4 ReadOnlyVec = new Vec4(1, 2, 3, 4);

    static void Main(string[] args)
    {
        Console.WriteLine(RuntimeInformation.FrameworkDescription);

        // This refers to stack memory that has already been left out.
        ref Vec4 foo = ref Foo();

        Console.WriteLine(foo);
        MakeStackDirty();
        Console.WriteLine(foo);

        Console.ReadKey();
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static ref Vec4 Foo()
    {
        // Defensive copy occurs and it is placed in stack memory implicitly.
        // The method returns a reference to the copy, which happens invalid memory access.
        ref Vec4 xyzw = ref ReadOnlyVec.Self;
        return ref xyzw;
    }

    [MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.NoOptimization)]
    private static void MakeStackDirty()
    {
        Span<byte> mem = stackalloc byte[1024];
        mem.Clear();
    }
}

public struct Vec4
{
    public float X, Y, Z, W;
    public Vec4(float x, float y, float z, float w) => (X, Y, Z, W) = (x, y, z, w);

    [UnscopedRef]
    public ref Vec4 Self => ref this;

    public override string ToString() => $"<{X}, {Y}, {Z}, {W}>";
}
```

**Expected Behavior**:

The compiler should report an error about accessing to the out-of-scope stack memory
at the method `Foo()`.

**Actual Behavior**:

No compiling error.
We can access the stack memory which is already out of scope, and the program does undefined behaviour.

bug

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #64776.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 1]
```diff
@@ -1912,7 +1912,29 @@ bool isRefEscape
...
             {
-                var tuple = getReceiver(symbol, receiver);
+                var method = symbol switch
+                {
+                    MethodSymbol m => m,
+                    PropertySymbol p => p.GetMethod ?? p.SetMethod,
+                    _ => throw ExceptionUtilities.UnexpectedValue(symbol)
+                };
+
+                if (receiver is not BoundValuePlaceholderBase && method is not null && receiver.Type!.IsVerifierValue())
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1922]: nit: consider changing IsVerifierValue to IsValueType here.

It looks like an implicit defensive copy can still occur when `receiver.Type` is a type parameter. [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgPgAQMwAJYBcCmAnAZhAY0xQEkBYAKAG9KU6UEAWFAWQAoBKAbkoF9LKyBgCYUAYQA8AFQB8KAO4ALHMSkoQKAM7psAVwLoANKRQ0K9FNkwQAJgHsYAGwCeKNeh7n6Qpq06naC3p0ADp2bkC6fgpeIA==). But since we check `IsVerifierValue()` instead of `IsValueType`, we won't create a placeholder for it in this analysis pass.

It looks like a ref to such an implicit local can't escape in this case, because you can't call an `[UnscopedRef]` method on a receiver of type parameter type. However, it seems like it would be more robust to create the placeholder anyway, even if it will never escape under the current language rules. Eventually we might make it possible to add `[UnscopedRef]` to an interface method, for example, in which case the right behavior will just fall out.

**Review by RikkiGibson — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@cston, @jaredpar  For the second review.

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs [hunk 2]
```diff
@@ -4846,6 +4846,1176 @@ .maxstack  1
...
+    {
+        var r = this;
+        ref Vec4 xyzw4 = ref r.Self2();
+        return ref xyzw4;
+    }
+}";
+            var comp = CreateCompilation(source, targetFramework: TargetFramework.Net70);
+            comp.VerifyEmitDiagnostics(
+                // (16,30): warning CS8656: Call to non-readonly member 'Vec4.Self2()' from a 'readonly' member results in an implicit copy of 'this'.
+                //         ref Vec4 xyzw3 = ref this.Self2();
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs:5409]: Trying to reconcile this behavior with some behavior from earlier tests in `DefensiveCopy_02` 

```csharp
static ref Wrap m1(in Wrap i)
{
    ref Wrap r1 = ref i.Self; // defensive copy
    return ref r1; // ref to the local copy
}
```

This seems similar in that its a `ref` call to a member that causes a defensive copy to occur. In the case of `DefensiveCopy_02` we allowed the `ref` call without error but error'd when the local was attempted to be returned. In this case though we're erroring on both the defensive copy and the return. 

Is there something subtly different about this call site that I'm missing here?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs:5409]: > Is there something subtly different about this call site that I'm missing here? 

If I am understanding the question correctly, in this case we are copying ```this```. Also, at the call site we are not reporting an error, it is a warning. And it is not about memory safety, but about accessing non-readonly member from a readonly one. This is yet another reason to perform a defensive copy and two different features report diagnostics because of that.

Comment (jaredpar) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs:5409]: Doh, I was reading that as an error, not a warning. This all makes sense now that I've read the actual words 😄

**Review by jaredpar — APPROVED** [review]
