### PR TITLE
Fix exception in PackageSettingsPersister

### LINKED ISSUE #70740: Diagnostics do not work when configured from Solution Explorer
**Version Used**: Version 17.9.0 Preview 2.0 [34305.10.main]

**Steps to Reproduce**:

1. Open a solution
2. Open a source file within the solution
3. Open **Tools &rarr; Options... &rarr; Text Editor &rarr; C# &rarr; Advanced**
    1. Set **Run background code analysis for:** to **None**
    2. Set **Show compiler errors and warnings for:** to **None**
    3. Enable (check) **Enable 'pull' diagnostics**
4. Right click the solution node in **Solution Explorer &rarr; Analyze and Code Cleanup &rarr; Set Analysis Scope &rarr; Open Documents**
5. Close Visual Studio
6. Reopen Visual Studio by double clicking the same solution from (1), so previously opened document from (2) is again open
7. Introduce an error within the document, e.g. by removing a required `;`

**Expected Behavior**:

Diagnostics appear for the open document.

**Actual Behavior**:

Diagnostics do not appear in any document.

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #70740

~~PackageSettingsPersister attempts to get or load RoslynPackage during initialization. Package load might not succeed at this point under certain circumstances (the reasons for which are not clearly understood as of now). Instead of assuming package load succeeded during PackageSettingsPersister initialization, we start listening to package load events for this case and perform the initialization when RoslynPackage gets loaded in future.~~

Initialize the `PackageSettingsPersister` from the `RoslynPackage` directly instead of it attempting to get or load `RoslynPackage` and initialize itself.

Verified that fixes the repro in #70740

### CODE REVIEW

File: src/VisualStudio/Core/Def/Options/PackageSettingsPersister.cs [hunk 1]
```diff
@@ -40,9 +44,28 @@ private async Task InitializeAsync(CancellationToken cancellationToken)
         {
             await _threadingContext.JoinableTaskFactory.SwitchToMainThreadAsync(cancellationToken);
 
-            _lazyRoslynPackage = await RoslynPackage.GetOrLoadAsync(_threadingContext, _serviceProvider, cancellationToken).ConfigureAwait(true);
-            Assumes.Present(_lazyRoslynPackage);
+            // We attempt to get or load the RoslynPackage to proceed with the core initialization.
+            // However, this package load might fail under certain circumstances.
```
Comment (mavasani) [inline src/VisualStudio/Core/Def/Options/PackageSettingsPersister.cs:48]:
```suggestion
            // However, this package load might not succeed at this point under certain circumstances and we get a null value here.
```

File: src/VisualStudio/Core/Def/Options/PackageSettingsPersister.cs [hunk 2]
```diff
@@ -40,9 +44,28 @@ private async Task InitializeAsync(CancellationToken cancellationToken)
         {
             await _threadingContext.JoinableTaskFactory.SwitchToMainThreadAsync(cancellationToken);
 
-            _lazyRoslynPackage = await RoslynPackage.GetOrLoadAsync(_threadingContext, _serviceProvider, cancellationToken).ConfigureAwait(true);
-            Assumes.Present(_lazyRoslynPackage);
+            // We attempt to get or load the RoslynPackage to proceed with the core initialization.
```
Comment (davkean) [inline src/VisualStudio/Core/Def/Options/PackageSettingsPersister.cs:47]: This seems like a workaround this chick and egg problem; the package retrieval fails because you are overlapping with it.

Why don't you just reverse the dependency, have the package call into this "persister" (via a private interface) passing itself when its done?

Comment (mavasani) [reply src/VisualStudio/Core/Def/Options/PackageSettingsPersister.cs:47]: > Why don't you just reverse the dependency, have the package call into this "persister" (via a private interface) passing itself when its done?

I thought about it but there is no clear point in RoslynPackage where we know the package has finished loading. However, it seems the PackageSettingsPersister doesn't really care about the package loading stage, it just needs a reference to the instance of RoslynPackage to hookup an event handler. I'll implement your suggestion and confirm if all works, thanks!

File: src/VisualStudio/Core/Def/RoslynPackage.cs [hunk 3]
```diff
@@ -194,7 +195,9 @@ private async Task LoadOptionPersistersAsync(IComponentModel componentModel, Can
 
             foreach (var provider in persisterProviders)
             {
-                _ = await provider.GetOrCreatePersisterAsync(cancellationToken).ConfigureAwait(true);
+                var persister = await provider.GetOrCreatePersisterAsync(cancellationToken).ConfigureAwait(true);
+                if (persister is PackageSettingsPersister packageSettingsPersister)
+                    packageSettingsPersister.Initialize(this);
```
Comment (mavasani) [inline src/VisualStudio/Core/Def/RoslynPackage.cs:200]: Thanks @davkean, turned out to be much cleaner.

**Review by sharwell — APPROVED** [review]

File: src/VisualStudio/Core/Def/Options/PackageSettingsPersisterProvider.cs [hunk 4]
```diff
@@ -6,37 +6,21 @@
...
 using Microsoft.CodeAnalysis.Host.Mef;
 using Microsoft.CodeAnalysis.Options;
-using IAsyncServiceProvider = Microsoft.VisualStudio.Shell.IAsyncServiceProvider;
-using SAsyncServiceProvider = Microsoft.VisualStudio.Shell.Interop.SAsyncServiceProvider;
 
 namespace Microsoft.VisualStudio.LanguageServices.Options
 {
     [Export(typeof(IOptionPersisterProvider))]
-    internal sealed class PackageSettingsPersisterProvider : IOptionPersisterProvider
+    [method: ImportingConstructor]
```
Comment (davkean) [inline src/VisualStudio/Core/Def/Options/PackageSettingsPersisterProvider.cs:15]: Ha, TIL this was possible.

**Review by genlu — APPROVED** [review]
:shipit:

File: src/VisualStudio/Core/Def/Options/PackageSettingsPersisterProvider.cs [hunk 5]
```diff
@@ -6,37 +6,21 @@
 using System.ComponentModel.Composition;
 using System.Threading;
 using System.Threading.Tasks;
-using Microsoft.CodeAnalysis.Editor.Shared.Utilities;
 using Microsoft.CodeAnalysis.Host.Mef;
 using Microsoft.CodeAnalysis.Options;
-using IAsyncServiceProvider = Microsoft.VisualStudio.Shell.IAsyncServiceProvider;
-using SAsyncServiceProvider = Microsoft.VisualStudio.Shell.Interop.SAsyncServiceProvider;
 
 namespace Microsoft.VisualStudio.LanguageServices.Options
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Def/Options/PackageSettingsPersisterProvider.cs:12]: nit: move to file scoped at the same time.  up to you.

File: src/VisualStudio/Core/Def/RoslynPackage.cs (hunk 3 above)
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Def/RoslynPackage.cs:200]: consider doc'ing in some form.  like why we're special casing this here.  not a huge deal.

File: src/VisualStudio/Core/Def/Options/PackageSettingsPersister.cs [hunk 6]
```diff
@@ -3,54 +3,27 @@
...
-
-        private async Task InitializeAsync(CancellationToken cancellationToken)
-        {
-            await _threadingContext.JoinableTaskFactory.SwitchToMainThreadAsync(cancellationToken);
-
-            _lazyRoslynPackage = await RoslynPackage.GetOrLoadAsync(_threadingContext, _serviceProvider, cancellationToken).ConfigureAwait(true);
-            Assumes.Present(_lazyRoslynPackage);
-
-            _optionService.RefreshOption(new OptionKey2(SolutionCrawlerOptionsStorage.SolutionBackgroundAnalysisScopeOption), _lazyRoslynPackage.AnalysisScope);
+            _lazyRoslynPackage = package;
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Def/Options/PackageSettingsPersister.cs:18]: nit: i would like if we added a check that this happens *once* and dies otherwise.  seems like it would be bad if we got double initialized.

**Review by CyrusNajmabadi — APPROVED** [review]
lgtm.  just small nits.  would like some assert that we don't double-initialize.

File: src/VisualStudio/Core/Def/Options/PackageSettingsPersister.cs [hunk 7]
```diff
@@ -3,54 +3,27 @@
...
-            IGlobalOptionService optionService)
+        public void Initialize(RoslynPackage package)
         {
-            _threadingContext = threadingContext;
-            _serviceProvider = serviceProvider;
-            _optionService = optionService;
-
-            // Start the process of loading the Roslyn package and getting options, but don't wait for it to complete.
-            // The setting will be refreshed once available.
-            InitializeAsync(_threadingContext.DisposalToken).ReportNonFatalErrorAsync().Forget();
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Options/PackageSettingsPersister.cs:36]: My concern here is nothing is ensuring the package might actually load at all -- if you open a CPS-only solution and no documents are open, I don't imagine we'd get a package load at all. And even if you run that case under a debugger and it works _now_, that might only be because of somebody else randomly triggering the load which means we're relying on side effects of somebody other component in VS.

Comment (jasonmalinowski) [reply src/VisualStudio/Core/Def/Options/PackageSettingsPersister.cs:36]: I think it might be best to keep the new pattern as is (that the package load initializes this), but still have the creation of the persister still trigger a load of the package. But unlike before we can just call LoadPackageAsync() and not worry about getting anything back -- it's just a fire and forget to make sure that process is started.

File: src/VisualStudio/Core/Def/Options/PackageSettingsPersister.cs (hunk 2 above)
Comment (jasonmalinowski) [reply src/VisualStudio/Core/Def/Options/PackageSettingsPersister.cs]: @davkean There's one bit I'm still not quite following here -- if an async package load is already underway, what is IVsShell7's LoadPackageAsync doing? I would have assumed it also waits until the package is done loading, but maybe not?

**Comment by mavasani** [comment]
@jasonmalinowski Can you please take another look? I'll wait for your approval before merging.

**Review by sharwell — CHANGES_REQUESTED** [review]
Need more time to review after significant changes

File: src/VisualStudio/Core/Def/Options/PackageSettingsPersisterProvider.cs [hunk 8]
```diff
@@ -9,35 +9,24 @@
...
+    private PackageSettingsPersister? _lazyPersister;
 
-        public ValueTask<IOptionPersister> GetOrCreatePersisterAsync(CancellationToken cancellationToken)
-        {
-            _lazyPersister ??= new PackageSettingsPersister(_threadingContext, _serviceProvider, _optionService);
-            return new ValueTask<IOptionPersister>(_lazyPersister);
-        }
+    public ValueTask<IOptionPersister> GetOrCreatePersisterAsync(CancellationToken cancellationToken)
+    {
+        _lazyPersister ??= new PackageSettingsPersister(threadingContext, serviceProvider, optionService);
```
Comment (sharwell) [inline src/VisualStudio/Core/Def/Options/PackageSettingsPersisterProvider.cs:29]: 📝 These are now breaking naming style conventions, and explicit fields should be added back. I'll start working on an analyzer to disallow direct references to a captured primary constructor parameter to avoid this in the future.

File: src/VisualStudio/Core/Def/Options/PackageSettingsPersisterProvider.cs [hunk 9]
```diff
@@ -6,22 +6,27 @@
...
 using System.Threading;
 using System.Threading.Tasks;
+using Microsoft.CodeAnalysis.Editor.Shared.Utilities;
 using Microsoft.CodeAnalysis.Host.Mef;
 using Microsoft.CodeAnalysis.Options;
+using Microsoft.VisualStudio.Shell;
+using Microsoft.VisualStudio.Shell.Interop;
 
-namespace Microsoft.VisualStudio.LanguageServices.Options
+namespace Microsoft.VisualStudio.LanguageServices.Options;
```
Comment (sharwell) [inline src/VisualStudio/Core/Def/Options/PackageSettingsPersisterProvider.cs:15]: 📝 In the future, please make changes to file-scoped namespaces a separate commit.

File: src/VisualStudio/Core/Def/Options/PackageSettingsPersisterProvider.cs (hunk 8 above)
Comment (CyrusNajmabadi) [reply src/VisualStudio/Core/Def/Options/PackageSettingsPersisterProvider.cs:29]: I would reject that analyzer. This is written the normal way the ldm expects with primary constructors and parameters. 

The naming is correct as well. These are parameters and as such are named as parameters.

Comment (jasonmalinowski) [reply src/VisualStudio/Core/Def/Options/PackageSettingsPersisterProvider.cs:29]: Yeah, this is now idiomatic C# code. (I'm not a huge fan of it personally, but it _is_ idiomatic.)

Comment (CyrusNajmabadi) [reply src/VisualStudio/Core/Def/Options/PackageSettingsPersisterProvider.cs:29]: i find this much easier to read and reason about.  That the entire type is now like 5 lines total, and i can clearly see the constructor parameters flow into this method makes it much clearer to me than having to do all the tracking of parameter to assignment to field to reference.

Comment (sharwell) [reply src/VisualStudio/Core/Def/Options/PackageSettingsPersisterProvider.cs:29]: > but it is idiomatic

I would also be OK with the compiler layer policy of just blocking a new feature that isn't compatible with general style we've had.

Comment (CyrusNajmabadi) [reply src/VisualStudio/Core/Def/Options/PackageSettingsPersisterProvider.cs:29]: This is compatible with the style we've always had.  It was intentionally designed that way.  The style for parameters and captures has been established for the team for years, and this entirely follows that design.

**Review by jasonmalinowski — APPROVED** [review]
