### PR TITLE
Fix Code Model race for real this time

### LINKED ISSUE #8576: InvalidOperationException in Roslyn.VisualStudio.Services.UnitTests.dll
We encountered a System.InvalidOperationException in Roslyn.VisualStudio.Services.UnitTests.dll from an internal build, which looks like a race.

```
xUnit.net Console Runner (32-bit .NET 4.0.30319.42000)
  Discovering: Roslyn.VisualStudio.Services.UnitTests
  Discovered:  Roslyn.VisualStudio.Services.UnitTests
  Starting:    Roslyn.VisualStudio.Services.UnitTests
    Microsoft.VisualStudio.LanguageServices.UnitTests.Snippets.VisualBasicSnippetExpansionClientTests.TestAddImport_AddsOnlyNewAliasAndNamespacePairs [SKIP]
      Issue #321
      System.InvalidOperationException : Key already exists in table.
      Stack Trace:
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Def\Implementation\Interop\CleanableWeakComHandleTable.cs(179,0): at Microsoft.VisualStudio.LanguageServices.Implementation.Interop.CleanableWeakComHandleTable`2.Add(TKey key, TValue value)
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Impl\CodeModel\InternalElements\CodeVariable.cs(23,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeVariable.Create(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNodeKey nodeKey, Nullable`1 nodeKind)
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\CSharp\Impl\CodeModel\CSharpCodeModelService.cs(566,0): at Microsoft.VisualStudio.LanguageServices.CSharp.CodeModel.CSharpCodeModelService.CreateInternalCodeElement(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node)
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Impl\CodeModel\FileCodeModel_CodeGen.cs(85,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.CreateInternalCodeMember(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node)
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Impl\CodeModel\FileCodeModel_CodeGen.cs(431,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.AddVariable(SyntaxNode containerNode, String name, Object type, Object position, vsCMAccess access)
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Impl\CodeModel\InternalElements\CodeClass.cs(200,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeClass.<>c__DisplayClass27_0.<AddVariable>b__0()
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Impl\CodeModel\FileCodeModel.cs(309,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.EnsureEditor[T](Func`1 action)
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Impl\CodeModel\InternalElements\CodeClass.cs(196,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeClass.AddVariable(String name, Object type, Object position, vsCMAccess access, Object location)
           at EnvDTE80.CodeClass2.AddVariable(String Name, Object Type, Object Position, vsCMAccess Access, Object Location)
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Test\CodeModel\CSharp\CodeClassTests.vb(3848,0): at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeClassTests._Closure$__._Lambda$__187-0(CodeModelTestState state, CodeClass2 codeClass)
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Test\CodeModel\AbstractCodeElementTests`1.vb(39,0): at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.AbstractCodeElementTests`1.VB$StateMachine_5_TestElement.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\VisualStudio\Core\Test\CodeModel\CSharp\CodeClassTests.vb(3845,0): at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.CSharp.CodeClassTests.VB$StateMachine_187_TestAddAndRemoveViaTextChangeManyTimes.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  Finished:    Roslyn.VisualStudio.Services.UnitTests
=== TEST EXECUTION SUMMARY ===
   Roslyn.VisualStudio.Services.UnitTests  Total: 3277, Errors: 0, Failed: 1, Skipped: 1, Time: 751.327s
```

FYI @dotnet/roslyn-infrastructure

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes #8576

I thought I'd fixed this race with PR #8607. After all, the check-in tests were passing on the PR and the tests all passed locally on my machine. However, it still failed consistently on the build server. Clearly the problem was more subtle that I'd originally thought.

Finally, I noticed that the only test passes that were failing were on x86 *Release* (insert sound of forehead being smacked). After compiling Release, I could reproduce the problem locally.

It turns out that this was a race with GC. In a previous fix, when adding an element to FileCodeModel's element cache, we would first check to see if the element was already in the cache. If it was in the cache, we'd remove it before adding it. However, the test to see if the element was in the cache called `CleanableWeakComHandleTable.TryGetValue(TKey key, out TValue value)`, which would only return true if `key` was in the cache and `value` was not set to null. In essence, it's defined like so:

```C#
public bool TryGetValue(TKey key, out TValue value)
{
    this.AssertIsForeground();

    WeakComHandle<TValue, TValue> handle;
    if (_table.TryGetValue(key, out handle))
    {
        value = handle.ComAggregateObject;
        return value != null;
    }

    value = null;
    return false;
}
```

Notice how it only returns true when value is not null? Since the `CleanableWeakComHandleTable` weakly holds onto elements, calling this to determine whether a key is in the table is clearly not correct because the element can get GC'd. In Release, the GC can be a bit more aggressive (often due to additional hints in the optimized JIT code), causing more situations where a key would be in the table with a null value. For those items, `TryGetValue` returns false, so we wouldn't remove the key from the table before adding it again, resulting in a collision.

The fix is to create a simpler `CleanableWeakComHandleTable.ContainsKey(TKey key)` that doesn't rely on the value in the table and use that instead.

```C#
public bool ContainsKey(TKey key)
{
    this.AssertIsForeground();

    return _table.ContainsKey(key);
}
```

tagging @dotnet/roslyn-ide

### CODE REVIEW

**Comment by DustinCampbell** [comment]
Note: I removed the extra logging in the unit tests in this change because it ultimately didn't help. Well, it did help in the sense that it validated that the build failed with my latest changes, since the extra information was present. But, the information didn't help identify the problem.

**Comment by DustinCampbell** [comment]
This passed all PR tests. I'm going to optimistically check this in since it's failing x86 release builds.

**Comment by dpoeschl** [comment]
:+1:

**Comment by balajikris** [comment]
subtle indeed! :+1:

**Comment by Pilchie** [comment]
:+1:

File: src/VisualStudio/Core/Impl/CodeModel/FileCodeModel.cs [hunk 1]
```diff
@@ -199,8 +199,7 @@ internal void OnCodeElementCreated(SyntaxNodeKey nodeKey, EnvDTE.CodeElement ele
             // If we're creating an element with the same node key as an element that's already in the table, just remove
             // the old element. The old element will continue to function but the new element will replace it in the cache.
 
-            EnvDTE.CodeElement oldElement;
-            if (_codeElementTable.TryGetValue(nodeKey, out oldElement))
+            if (_codeElementTable.ContainsKey(nodeKey))
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Impl/CodeModel/FileCodeModel.cs]: Would it have made more sense just to have a "Replace" method? Given there's sufficient magic going on with it, I still get there's a try-and-then-do pattern.

**Comment by jasonmalinowski** [comment]
:+1:
