### PR TITLE
Disable navigate to decompiled sources for assemblies with SuppressIldasmAttribute

### LINKED ISSUE #24175: Navigate to disassembled source fails to check for SuppressIldasmAttribute
**Version Used**: 15.6 Preview 2

**Steps to Reproduce**:

1. Create a library which has `[assembly: SuppressIldasm]` applied to it
2. In a separate project, add a reference to the assembly produced by step 1
3. Invoke a method defined in the library, and use Go To Definition

**Expected Behavior**:

The metadata as source window appears, without showing decompiled method bodies.

**Actual Behavior**:

The code runs through ILSpy and shows decompiled method bodies.

### PR DESCRIPTION
**Pull request by sharwell**
### Customer scenario

A customer enables the Navigate to Decompiled Sources feature, accepts the terms for use, and navigates to a symbol defined in an assembly that has `SuppressIldasmAttribute` applied to it. The source code for the symbol is shown when only the metadata should be showing.

### Bugs this fixes

Fixes #24175

### Workarounds, if any

None.

### Risk

Low.

### Performance impact

Low.

### Is this a regression from a previous update?

No.

### Root cause analysis

The initial ILSpy integration (behind a feature flag and disabled by default) was not tested for this case. Manual testing revealed the bug.

### How was the bug found?

Manual compliance testing.

### Test documentation updated?

A manual test scenario was added.

### CODE REVIEW

File: src/EditorFeatures/Core/Implementation/MetadataAsSource/MetadataAsSourceFileService.cs [hunk 1]
```diff
@@ -114,6 +115,11 @@ private string GetRootPathWithGuid_NoLock()
                                                                      .GetDocument(temporaryProjectInfoAndDocumentId.Item2);
 
                     var useDecompiler = allowDecompilation;
+                    if (useDecompiler)
+                    {
+                        useDecompiler = !symbol.ContainingAssembly.GetAttributes().Any(attribute => attribute.AttributeClass.Name == nameof(SuppressIldasmAttribute));
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/MetadataAsSource/MetadataAsSourceFileService.cs]: Should this be checking fully qualified name?

Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/MetadataAsSource/MetadataAsSourceFileService.cs]: My original approach was to check the fully-qualified name. The more I though about it, it didn't seem to add anything.

**Comment by sharwell** [comment]
> Tests?

I don't have tests yet. I'm working on an approach to add them but this is a particularly important PR to take for Preview 4.

**Comment by jinujoseph** [comment]
Approved to merge via [link](https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_workitems/edit/558445)
