### PR TITLE
Fix/76886 await nullable value type

### LINKED ISSUE #76886: Nullability tracking is broken for `Nullable<T>` with awaits
**Version Used**: 
Version 17.14.0 Preview 1.0 [35717.212.main]

**Steps to Reproduce**:
```C#
MyStruct? myStruct = await GetStructAsync();
MyStruct s1 = myStruct.Value;

static async Task<MyStruct?> GetStructAsync()
{
    await Task.Yield();
    return new MyStruct();
}

struct MyStruct { }
```

**Diagnostic Id**:

n/a

**Expected Behavior**:
This should produce `warning CS8629: Nullable value type may be null.` when accessing `.Value`.

**Actual Behavior**:
No warning.

### PR DESCRIPTION
**Pull request by Metalaka**
### Summary
Fixes a bug where `await` on a `Nullable<T>` (e.g., `Task<int?>`) was incorrectly treated as `NotNull` by the nullable flow analysis.

- **Actual Behavior:** Awaiting a `Task<int?>` resulted in a [`NotNull`](https://github.com/dotnet/roslyn/blob/bdf7c2666c7f3fe949f9f591272b23decf6d6be8/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs#L12575C17-L12575C33) flow state, causing the compiler to miss warnings when the result was potentially null.
- **Expected Behavior:** The nullability of the awaited result should follow the return type of the awaiter's `GetResult` method.

### Description
In `NullableWalker.VisitAwaitExpression`, the compiler previously assumed that any `await` result of a [`ValueType`](https://github.com/dotnet/roslyn/blob/bdf7c2666c7f3fe949f9f591272b23decf6d6be8/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs#L12573C17-L12573C38) was inherently non-null.

```csharp
if (node.Type.IsValueType || node.HasErrors || awaitableInfo.GetResult is null)
{
    SetNotNullResult(node);
}
```

This PR updates `VisitAwaitExpression` to explicitly check if the type is a `Nullable<T>` before deciding to mark it as `NotNull`. If it is a `Nullable<T>`, the flow analysis now correctly uses the nullability information from the `GetResult` method of the awaiter.

### Impact on Existing Code
By correctly identifying the result of `await Task<T?>` as potentially null, this change **will introduce new CS8629 (Nullable value type may be null) warnings** in existing code where these potential nulls were previously ignored by the flow analysis. This is intended behavior to ensure correct nullable safety.

### Fixed Issues
Fixes #76886

### Tests Added
Added new test cases to `NullableReferenceTypesTests.cs`:

**Regression Tests (validating the fix for #76886):**
- `AwaitedNullableValueTypeAssignedToNonNullable_ProducesCS8629`
- `AwaitResultNullableValueTypeAssignedToNonNullable_ProducesCS8629`

**Baseline Tests (validating actual/expected behavior for non-awaited types):**
- `AwaitedNullableTypeAssignedToNonNullable_ProducesCS8600`
- `AwaitResultNullableTypeAssignedToNonNullable_ProducesCS8600`
- `NullableValueTypeAssignedToNonNullable_ProducesCS8629`

### CODE REVIEW

**Comment by Metalaka** [comment]
@dotnet-policy-service agree

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 1]
```diff
@@ -12570,7 +12570,13 @@ protected override void AfterLeftChildOfBinaryLogicalOperatorHasBeenVisited(Boun
             Visit(awaitableInfo);
             RemovePlaceholderReplacement(placeholder);
 
-            if (node.Type.IsValueType || node.HasErrors || awaitableInfo.GetResult is null)
+            bool isNullableValueType = node.Type.IsValueType &&
+                                       node.Type is NamedTypeSymbol nts &&
+                                       nts.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;
+
+            if ((node.Type.IsValueType && !isNullableValueType) ||
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: I think the `IsValueType` check was wrong to begin with, even for non-nullable value types. See, even if something is a value type, it may contain reference types as type arguments, which we need to reinfer and use.

For example:

```cs
class C
{
    public async Task<ImmutableArray<T>> M<T>(T value) => [value];

    public async Task M1()
    {
        string? s = null;
        var res = await M(s);
        res[0].ToString(); // expect warning on receiver of 'ToString()'
    }
}
```

(Please add the test.)

For this reason I think we should remove all the conditions from this `if`, *except* for `awaitableInfo.GetResult is null`. In that case, the task-like type being used is malformed, and the symbol we expected to get a result type out of, is missing. Simply setting a non-null result of the `node` type and moving on in that case is OK.

We also have a helper which can probably be used to simplify the `else` block as follows:
```cs
var reinferredGetResult = (MethodSymbol)AsMemberOfType(_visitResult.RValueType.Type, awaitableInfo.GetResult);
```

Comment (Metalaka) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Hi, thanks for the feedback! You're absolutely right; it took me a moment to grasp the subtlety here because I was seeing the expected warnings with `ImmutableArray<int?>`.
I've updated the implementation as you suggested: Simplified the `if` and used the `AsMemberOfType` helper for the reinference logic.
I've also added a comprehensive test case using `KeyValuePair<TKey, TValue>` to verify that nullability propagates correctly for both reference types and nullable value types when contained within an awaited value type.
```cs
class C
{
    public async Task<KeyValuePair<T1, T2>> M<T1, T2>(T1 t1, T2 t2) => default;

    public async Task M1()
    {
        string? s = null;
        int? i = null;
        var res = await M(s, i);
        res.Key.ToString();   // expect warning on receiver of 'ToString()'
        _ = res.Value.Value;  // expect warning on 'Value'
    }
}
```

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 2]
```diff
@@ -12570,20 +12570,13 @@ protected override void AfterLeftChildOfBinaryLogicalOperatorHasBeenVisited(Boun
             Visit(awaitableInfo);
             RemovePlaceholderReplacement(placeholder);
 
-            if (node.Type.IsValueType || node.HasErrors || awaitableInfo.GetResult is null)
+            if (node.HasErrors || awaitableInfo.GetResult is null)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]:
```suggestion
            if (awaitableInfo.GetResult is null)
```

I believe the HasErrors condition is also not necessary. Basically, it's normal for a node to be erroneous in some way, but for us to still be able to operate on it, and report the information we do know about it.

For example, I think a test like this would show the way in which we want to recover. My expectation is that there isn't a nullable warning with the current version of your changes, but there would be a warning once the HasErrors check is deleted.

```cs
class C
{
    public async Task<ImmutableArray<T>> M<T>(T value) => [value];

    public Task M1()
    {
        string? s = null;
        var res = await M(s); // error: 'await' without 'async'
        res[0].ToString(); // expect warning on receiver of 'ToString()'
    }
}
```

**Review by RikkiGibson — COMMENTED** [review]
LGTM aside from suggestion to delete HasErrors check.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableAwaitTests.cs [hunk 3]
```diff
@@ -0,0 +1,176 @@
...
+            comp.VerifyDiagnostics(
+                // (14,9): warning CS8602: Dereference of a possibly null reference.
+                //         res.Key.ToString(); // expect warning on receiver of 'ToString()'
+                Diagnostic(ErrorCode.WRN_NullReferenceReceiver, "res.Key")
+                    .WithLocation(14, 9),
+                // (15,13): warning CS8629: Nullable value type may be null.
+                //          _ = res.Value.Value; // warn
+                Diagnostic(ErrorCode.WRN_NullableValueTypeMayBeNull, "res.Value")
+                    .WithLocation(15, 13));
+        }
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableAwaitTests.cs:167]: Please add the scenario from https://github.com/dotnet/roslyn/pull/82146#discussion_r2738550396 as a test case to demonstrate significance of deleting the HasErrors check:

```cs
class C
{
    public async Task<ImmutableArray<T>> M<T>(T value) => [value];

    public Task M1()
    {
        string? s = null;
        var res = await M(s); // error: 'await' without 'async'
        res[0].ToString(); // expect warning on receiver of 'ToString()'
    }
}
```

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler for second review

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableAwaitTests.cs (hunk 3 above)
Comment (Metalaka) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableAwaitTests.cs:167]: Done ;)

**Review by RikkiGibson — APPROVED** [review]

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableAwaitTests.cs [hunk 4]
```diff
@@ -0,0 +1,214 @@
...
+        
+        int? result = await GetNullableIntAsync();
+        int nonNullableInt = result.Value;
+    }
+}";
+
+            var comp = CreateCompilation(src);
+            comp.VerifyDiagnostics(
+                // (11,30): warning CS8629: Nullable value type may be null.
+                //          int nonNullableInt = result.Value; // warn expected
```
Comment (jjonescz) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableAwaitTests.cs]: nit: this comment doesn't correspond to the original source (there is no `// warn expected` there).
This applies to a few other places in this file too

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableAwaitTests.cs [hunk 5]
```diff
@@ -0,0 +1,214 @@
...
+        string nonNullableString = result;
+    }
+}";
+
+            var comp = CreateCompilation(src);
+            comp.VerifyDiagnostics(
+                // (11,36): warning CS8600: Converting null literal or possible null value to non-nullable type.
+                //          string nonNullableString = result; // warn
+                Diagnostic(ErrorCode.WRN_ConvertingNullableToNonNullable, "result")
+                    .WithLocation(11, 36));
```
Comment (jjonescz) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableAwaitTests.cs]: Consider leaving the diagnostics formatted exactly as they come from the test output - i.e., with the `.WithLocation` on the same line as `Diagnostic(`. To keep the style consistent but also simpler to update if diagnostics change in the future (and resulting in smaller diffs).

Comment (Metalaka) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableAwaitTests.cs]: It's now done for the entire file, Thanks

**Comment by RikkiGibson** [comment]
It looks like the change revealed legitimate new nullable warnings in the compiler source code. Here are my recommendations for what to try to resolve the warnings

```patch
diff --git a/src/EditorFeatures/Test/InheritanceMargin/InheritanceMarginTests.cs b/src/EditorFeatures/Test/InheritanceMargin/InheritanceMarginTests.cs
index f4650be4a5a..8806c2c248e 100644
--- a/src/EditorFeatures/Test/InheritanceMargin/InheritanceMarginTests.cs
+++ b/src/EditorFeatures/Test/InheritanceMargin/InheritanceMarginTests.cs
@@ -167,6 +167,7 @@ private static async Task VerifyInheritanceTargetAsync(Workspace workspace, Test
             for (var i = 0; i < actualDocumentSpans.Length; i++)
             {
                 var docSpan = await actualDocumentSpans[i].TryRehydrateAsync(workspace.CurrentSolution, CancellationToken.None);
+                Assert.True(docSpan.HasValue);
                 Assert.Equal(expectedDocumentSpans[i].SourceSpan, docSpan.Value.SourceSpan);
                 Assert.Equal(expectedDocumentSpans[i].Document.FilePath, docSpan.Value.Document.FilePath);
             }
diff --git a/src/Workspaces/Core/Portable/Rename/IRemoteRenamerService.cs b/src/Workspaces/Core/Portable/Rename/IRemoteRenamerService.cs
index 1b4348b70c3..f0984a8ae0d 100644
--- a/src/Workspaces/Core/Portable/Rename/IRemoteRenamerService.cs
+++ b/src/Workspaces/Core/Portable/Rename/IRemoteRenamerService.cs
@@ -136,7 +136,7 @@ internal sealed partial class SymbolicRenameLocations
             serializableLocations.Options,
             locations,
             implicitLocations,
-            referencedSymbols);
+            referencedSymbols!);
     }
 }
 
diff --git a/src/Workspaces/Core/Portable/Rename/LightweightRenameLocations.cs b/src/Workspaces/Core/Portable/Rename/LightweightRenameLocations.cs
index ad9b98cce7f..8891be76f91 100644
--- a/src/Workspaces/Core/Portable/Rename/LightweightRenameLocations.cs
+++ b/src/Workspaces/Core/Portable/Rename/LightweightRenameLocations.cs
@@ -63,7 +63,7 @@ internal sealed partial class LightweightRenameLocations
             Options,
             Locations,
             implicitLocations,
-            referencedSymbols);
+            referencedSymbols!);
     }
 
     /// <summary>
```

**Comment by RikkiGibson** [comment]
@davidwengier there is a pretty good chance that when we take this change, downstream projects will get new nullable warnings. Just a heads up

**Comment by RikkiGibson** [comment]
Finally got a test insertion going, am seeing new nullable warnings and pushing commits to address, to try and get the VS build all the way through and hopefully see the extent of the impact. https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/713230

Will want to do the same in dotnet/runtime. Have an agent following the steps to validate changes in dotnet/runtime and will see what comes up when I get back to investigating it sometime this week.

**Comment by RikkiGibson** [comment]
Verified VS and dotnet/runtime builds. There were just a few new test warnings in VS and no new warnings in dotnet/runtime.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 6]
```diff
@@ -12594,20 +12594,13 @@ protected override void AfterLeftChildOfBinaryLogicalOperatorHasBeenVisited(Boun
                 // This is AsyncHelpers.Await. We can directly use `_visitResult`
                 SetResult(node, _visitResult, updateAnalyzedNullability: true, isLvalue: false);
             }
-            else if (node.Type.IsValueType || node.HasErrors || awaitableInfo.GetResult is null)
+            if (awaitableInfo.GetResult is null)
```
Comment (Metalaka) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]:
```suggestion
            else if (awaitableInfo.GetResult is null)
```
The `else` has been lost in the merge/conflict

Comment (Metalaka) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: I'm letting @RikkiGibson apply the suggestion if the removal wasn't intentional ;)

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Putting the else seems correct, thanks

**Comment by RikkiGibson** [comment]
@Metalaka do you think you can push a change to address the bootstrap build warnings? (i.e. the change is causing the compiler to report new warnings in this codebase).

See failures: https://github.com/dotnet/roslyn/pull/82146/checks?check_run_id=65622138083
See also: https://github.com/dotnet/roslyn/pull/82146#issuecomment-3829015894

edit: nevermind, it looks like my recommendations from way back cover everything. I'll just apply them.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs
Comment (jjonescz) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:1]: Should we add an entry to our breaking change doc?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:1]: To me, it's just under the bar. We have had nullable bugs that impacted accuracy before, and, in most cases never added entries to the breaking change doc for them.

However, I do know we have some deadlines for 3xx to make this week, so, to avoid potential disruption I think we should wait for the next band.

**Comment by Metalaka** [comment]
Thanks so much @RikkiGibson for the great review and guidance on this 🙌 💖

**Comment by RikkiGibson** [comment]
@Metalaka thanks for the contribution!
