### PR TITLE
Track state table removal due to input separately from removal due to selection

### LINKED ISSUE #57991: Incremental source generator hint name issue
**Version Used**: VS 2022 17.0.1

**Steps to Reproduce**:

In our scenario we're generating hundreds of immutable partial classes, which are 1 : 1 to source SyntaxNodes.
We have there a pipeline like this: 
SyntaxNode -> Type1 -> CachedType2 -> CachedType3
In CachedType3 we generate unique hintName, which is also cached,
and  CachedType3 is then calling AddSource with this hintName.

Then in a solution using this generator generate a lot of changes in source, e.g. when switching branches

**Expected Behavior**:

No exception from generator, generator not getting disabled

**Actual Behavior**:

quite often in this scenario we're ending with ArgumentException about not unique hint name. But this is not coming from our call to AddSource, but from internal call in GeneratorDriver.

This is the callstack:
```
Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.AdditionalSourcesCollection.Add(string hintName, Microsoft.CodeAnalysis.Text.SourceText source) Line 63	C#
Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.SourceOutputNode<System.__Canon>.AppendOutputs(Microsoft.CodeAnalysis.IncrementalExecutionContext context, System.Threading.CancellationToken cancellationToken) Line 100	C#
Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.GeneratorDriver.UpdateOutputs(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.IIncrementalGeneratorOutputNode> outputNodes, Microsoft.CodeAnalysis.IncrementalGeneratorOutputKind outputKind, System.Threading.CancellationToken cancellationToken, Microsoft.CodeAnalysis.DriverStateTable.Builder driverStateBuilder) Line 277	C#
Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.GeneratorDriver.RunGeneratorsCore(Microsoft.CodeAnalysis.Compilation compilation, Microsoft.CodeAnalysis.DiagnosticBag diagnosticsBag, System.Threading.CancellationToken cancellationToken) Line 253	C#
Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.GeneratorDriver.RunGenerators(Microsoft.CodeAnalysis.Compilation compilation, System.Threading.CancellationToken cancellationToken) Line 45	C#
```

This happens even when the hintName we generate in CachedType3 has completely random string inside. So there should not exist 2 instances of CachedType3 having the same hintName, but it still happens.

And since this happens outside of our call, the generator has no chance to catch this exception and handle it, so it'll always disable the generator.

As a workaround, is there maybe a way how to handle this exception or how to re-enable/not disable the generator when this happens?

### LINKED ISSUE #64841: CS8785 ForAttributeWithMetadataName issue with source generator
**Version Used**: 

	<PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="6.0.0"
	<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.3"
	<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.1" 

## VS Info
<details>
  <summary>Expand</summary>
  
Microsoft Visual Studio Community 2022
Version 17.3.5
VisualStudio.17.Release/17.3.5+32922.545
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

ASP.NET and Web Tools   17.3.376.3011
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.3.376.3011
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.3.376.3011
Azure Functions and Web Jobs Tools

C# Tools   4.3.0-3.22470.13+80a8ce8d5fdb9ceda4101e2acb8e8eb7be4ebcea
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Markdown Editor v2   2.0.130
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.3.20 (3f4cb00)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2232702+e1d654e792aa2fe6646a6935bcca80ff0aff4387
Provides languages services for ASP.NET Core Razor.

Solution Colors   1.1.44
Allows you to associate a color with a solution and display it in various locations within Visual Studio. Inspired by the Peacock extension for VS Code.

SQL Server Data Tools   17.0.62207.04100
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

TypeScript Tools   17.0.10701.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.3.0-3.22470.13+80a8ce8d5fdb9ceda4101e2acb8e8eb7be4ebcea
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.22363.4+1b94f89d4d1f41f20f9be73c76f4b229d4e49078
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Web Compiler   1.14.8
Compiler for LESS, Sass and CoffeeScript files

Xamarin   17.3.0.308 (d17-3@56b9f7e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.3.0.217 (remotes/origin/d17-3@b81db1dcc0)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.2.28 (9b3d244)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.0.0.0 (d17-3/030cd63)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: dffa5ab
    Java.Interop: xamarin/java.interop/d17-3@7716ae53
    SQLite: xamarin/sqlite/3.38.5@df4deab
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@14076a6

Xamarin.iOS and Xamarin.Mac SDK   16.0.0.75 (e4f48bed7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

</details>

**Steps to Reproduce**:

```cs

[Generator(LanguageNames.CSharp)]
internal class HierarchyGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var childProvider = context.SyntaxProvider.ForAttributeWithMetadataName(Constants.ChildAttributeName, IsCommandClass, GetHierarchicFlow)
			.SelectMany(static (tuples, token) => tuples);
		var parentProvider = context.SyntaxProvider.ForAttributeWithMetadataName(Constants.ParentAttributeName, IsCommandClass, GetHierarchicFlow)
			.SelectMany(static (tuples, token) => tuples);
		
		var mergedHierarchy = childProvider.Collect().Combine(parentProvider.Collect());
		context.RegisterSourceOutput(mergedHierarchy, GenerateHierarchy);
	}

	private void GenerateHierarchy(SourceProductionContext context, (ImmutableArray<(bool root, string parent, string child)> Left, ImmutableArray<(bool root, string parent, string child)> Right) input)
	{
		try
		{
			GenerateInternal(context, input);
		}
		catch (Exception e) when (e is not OperationCanceledException)
		{
			context.ReportDiagnostic(Diagnostic.Create(
				new DiagnosticDescriptor(
					"ATSCG0000",
					"An exception was thrown by the Hierarchy generator",
					"An exception was thrown by the Hierarchy generator: '{0}'",
					"Hierarchy",
					DiagnosticSeverity.Error,
					isEnabledByDefault: true),
				Location.None,
				e.ToString()));
		}
	}

	private void GenerateInternal(SourceProductionContext context, (ImmutableArray<(bool root, string parent, string child)> Left, ImmutableArray<(bool root, string parent, string child)> Right) input)
	{
		context.CancellationToken.ThrowIfCancellationRequested();

		var result = new HashSet<(bool root, string parent, string child)>(input.Left.Concat(input.Right));
		var roots = new HashSet<string>(result.Where(static d => d.root).Select(d => d.parent));
		var globalHierarchy = result.ToLookup(d => d.parent);
		var hierarchyPerRoot = roots
			.Select(root =>
			{
				var children = new HashSet<(string parent, string child)>();
				AddChildrenRecursive(root, globalHierarchy, children);
				return (root, children);
			}).ToDictionary(d => d.root, d => d.children);

		context.CancellationToken.ThrowIfCancellationRequested();

		var sb = new StringBuilder();
		AppendSource(sb, hierarchyPerRoot);
		context.AddSource("GeneratedHierarchy.g.cs", sb.ToString());
	}

	private void AppendSource(StringBuilder stringBuilder, Dictionary<string, HashSet<(string parent, string child)>> hierarchyPerRoot)
	{
		/*
		 *	// <auto-generated/>
		 *	using Amusoft.Toolkit.System.CommandLine.CommandModel;
			using Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.TestResources.HierarchyGenerator;

			namespace Amusoft.Toolkit.System.CommandLine.Generator.UnitTests.Samples;

			public static class GeneratedHierarchy
			{
				public static readonly ICommandHierarchy ParentCommand = CommandHierarchyBuilder.FromArray(
					new[,]
					{
						{typeof(MixedChainParent), typeof(MixedChainChild1)},
						{typeof(MixedChainParent), typeof(MixedChainChild2)},
					});
			}
		 */

		if (hierarchyPerRoot.Count == 0)
			return;

		var nsParts = hierarchyPerRoot.Keys.First().Split('.');
		var ns = string.Join(".", nsParts.Take(nsParts.Length - 1).ToArray());

		stringBuilder.AppendLine($$"""
			// <auto-generated/>
			using Amusoft.Toolkit.System.CommandLine.CommandModel;

			namespace {{ns}};

			public static class GeneratedHierarchy
			{
			""");

		foreach (var hierarchy in hierarchyPerRoot)
		{
			stringBuilder.AppendLine(AppendSourceHierarchy(hierarchy));
		}

		stringBuilder.Append("""
			}
			"""

			);
	}

	private string AppendSourceHierarchy(KeyValuePair<string, HashSet<(string parent, string child)>> hierarchy)
	{
		var sb = new StringBuilder();
		/* 
				public static readonly ICommandHierarchy ParentCommand = CommandHierarchyBuilder.FromArray(
					new[,]
					{
						{typeof(MixedChainParent), typeof(MixedChainChild1)},
						{typeof(MixedChainParent), typeof(MixedChainChild2)},
					});
		 */

		var hierarchyName = hierarchy.Key.Split('.').Reverse().Take(1).First();

		sb.AppendLine($$"""
			public static readonly ICommandHierarchy {{hierarchyName}} = 
				CommandHierarchyBuilder.FromArray(new[,]
				{
		""");
		foreach (var tuple in hierarchy.Value)
		{
			sb.AppendLine($"\t\t\t{{typeof({tuple.parent}), typeof({tuple.child})}},");
		}

		sb.Append("""		
				});
		""");

		return sb.ToString();
	}

	private void AddChildrenRecursive(string root, ILookup<string, (bool root, string parent, string child)> globalHierarchy, HashSet<(string parent, string child)> results)
	{
		foreach (var tuple in globalHierarchy[root])
		{
			if (results.Add((tuple.parent, tuple.child)))
			{
				AddChildrenRecursive(tuple.child, globalHierarchy, results);
			}
		}
	}

	private static IEnumerable<(bool root, string parent, string child)> GetHierarchicFlow(GeneratorAttributeSyntaxContext context, CancellationToken cancellationToken)
	{
		if (context.TargetSymbol is INamedTypeSymbol classSymbol)
		{
			var hierarchyAttribute = context.Attributes
				.Select(static d => GetHierarchyData(d))
				.Where(static d => d is not null);

			var isRoot = classSymbol is {BaseType.MetadataName: "RootCommand"};

			foreach (var attributeData in hierarchyAttribute)
			{
				if (attributeData is {Data.ConstructorArguments.Length: > 0} && attributeData.Data.ConstructorArguments[0].Value is INamedTypeSymbol {} firstParameterType)
				{
					if (attributeData.ChildAttribute)
						yield return (isRoot, classSymbol.ToDisplayString(), firstParameterType.ToDisplayString());
					if (attributeData.ParentAttribute)
						yield return (isRoot, firstParameterType.ToDisplayString(), classSymbol.ToDisplayString());
				}
			}
		}
	}

	private static HierarchyData? GetHierarchyData(AttributeData attributeData)
	{
		if (attributeData is {AttributeClass: { } attrClass} && attrClass.ToDisplayString() is {} metadataName)
		{
			if (metadataName is Constants.ChildAttributeName)
				return new HierarchyData(attributeData, true, false);
			if (metadataName is Constants.ParentAttributeName)
				return new HierarchyData(attributeData, false, true);
		}

		return default;
	}

	private record HierarchyData(AttributeData Data, bool ChildAttribute, bool ParentAttribute);

	private static bool IsCommandClass(SyntaxNode node, CancellationToken cancellationToken)
	{
		if (node is ClassDeclarationSyntax classDeclaration)
		{
			if (classDeclaration.BaseList is {Types.Count: > 0} baseList)
			{
				return baseList.Types[0].Type is IdentifierNameSyntax {Identifier.Text: "Command" or "RootCommand"};
			}
		}

		return false;
	}
}
```

**Expected Behavior**:
Source generator does not run into fail states from calling sdk methods

**Actual Behavior**:
ForAttributeWithMetadataName crashes the generator

**Additional context**:

grafik

### LINKED ISSUE #66451: ForAttributeWithMetadataName in IIncrementalGenerator failing with ArgumentException
**Version Used**: 
Visual studio: 17.4.4
Microsoft.CodeAnalysis: 4.4.0.0

**Steps to Reproduce**:

1. Create IIncrementalGenerator using ForAttributeWithMetadataName
2. In the core remove attribute to trigger generator in one file
3. Switch to another file using the generator, navigate to definition
4. Repeat combinations of above until getting ArgumentException from the generator

**Expected Behavior**:

No exception thrown

**Actual Behavior**:

The generator will stop working with following error:

Warning	CS8785	Generator '...Generator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'SyntaxTree is not part of the compilation
Parameter name: syntaxTree'		Generator threw the following exception:
'System.ArgumentException: SyntaxTree is not part of the compilation
Parameter name: syntaxTree
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility)
   at Microsoft.CodeAnalysis.SyntaxValueProvider.<>c__DisplayClass11_0`1.<ForAttributeWithMetadataName>b__0(ValueTuple`2 tuple, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.UserFunctionExtensions.<>c__DisplayClass0_0`2.<WrapUserFunction>b__0(TInput input, CancellationToken token)'.

### LINKED ISSUE #66840: IncrementalValuesProvider returns wrong cached objects
**Version Used**: Microsoft.CodeAnalysis.CSharp v4.4.0

**Steps to Reproduce**:

1. Edit PropertyName Attribute value in GenerateProperties.LetPropiertiesGenerate for the first field from one char to zero chars and back to one char
2. Check the generated output
3. Issue is reproduceable with every field expect the last two

**Diagnostic Id**:
Sorry I don't really know how to get one.

**Expected Behavior**:
No matter how often I change the value of the property from one char to zero chars, the source generator is generating the properties for all remaining fields, depending on the rules.

**Actual Behavior**:
Every time I execute the steps to reproduce, the next field below the field that was changed is gone. 
Instead the last field of the class gets duplicated and is generated multiple times.

**Additional information:**
If I remove the caching, by making my struct cache unfriendly everything works fine. And since I'm checking for equality by comparing all properties which are value types, I don't think the issue is in the equality check of the transformed objects.

**Solution with IIncrementalSourceGenerator and one class** 
[AutoPropertySourceGenerator.zip](https://github.com/dotnet/roslyn/files/10719617/AutoPropertySourceGenerator.zip)

### PR DESCRIPTION
**Pull request by jjonescz**
Fixes #66451.
Fixes #64841.
Fixes #66840.
Fixes #57991.

Tracks entries removed due to their input being removed separately from entries removed because they were filtered out. The former can be removed from the compacted table. The latter must be kept to avoid reusing incorrect state in later generations.

<details>
<summary>
Simple version of the bug:
</summary>

1. Let's have `Class1` and `Class2` as inputs (source) of a transform node.
2. `Class1` gets modified and the transform node removes it from its table.
4. `Class2` gets modified, i.e., the source table contains cached `Class1` and modified `Class2`. The previous table of the transform node contains only cached `Class2` (because `Class1` has been removed and compacted away).
   The transform node creates wrong new table in this step (iterating over source table entries):
   1. It sees cached source `Class1` and cached previous `Class2`, so puts `Class2` in the new table (thinking it can just reuse previous cached entries, doesn't know something has been removed from the previous table).
   2. Now it sees modified source `Class2`, re-runs the transformation, and puts modified `Class2` in the new table.

   So, the new table contains `Class2` twice, and the first one is from an old syntax tree, causing the exception.

This PR causes `Class1` to remain in the previous table as "removed", so in step 4, the new table correctly contains an empty entry and modified `Class2`.
</details>

### CODE REVIEW

**Comment by jcouv** [comment]
Marking as draft for now (until @chsienki can investigate/advise)

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs [hunk 1]
```diff
@@ -484,6 +489,7 @@ private TableEntry(OneOrMany<T> items, ImmutableArray<EntryState> states)
 
                 _items = items;
                 _states = states;
+                _anyRemoved = states.Contains(EntryState.Removed);
```
Comment (chsienki) [inline src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs:492]: Let's either just do the `states.Contains(...)` check when we call `AsCached()` or track the removal state when we're making the builder (set a flag as soon as `RemoveEntries()` is called and pass that in here)

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs [hunk 2]
```diff
@@ -108,12 +108,15 @@ public NodeStateTable<T> AsCached()
             if (IsCached)
                 return this;
 
-            var nonRemovedCount = _states.Count(static e => !e.IsRemoved);
+            // It's only safe to remove entries that were removed due to their input being removed,
```
Comment (chsienki) [inline src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs:111]: We should try and clarify this comment a bit, I think. Something like

`If the input to an entry was removed, we also need to remove the entry. However, if the input was present, but the entry didn't produce any values (or removed them all) we need to keep the empty entry as a placeholder, so that on the next generation pass we can retrieve it as the cached value of the input. `

Although I'm also having a hard time succinctly describing it 😆

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs (hunk 1 above)
Comment (jjonescz) [reply src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs]: > track the removal state when we're making the builder (set a flag as soon as `RemoveEntries()` is called and pass that in here)

Not sure what exactly you mean, but tried computing the flag more efficiently.

> Let's either just do the `states.Contains(...)` check when we call `AsCached()`

That seems the simplest option, could do that instead.

**Comment by jjonescz** [comment]
@chsienki @dotnet/roslyn-compiler PTAL

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs [hunk 3]
```diff
@@ -465,8 +469,10 @@ private static (T chosen, EntryState state, bool chosePrevious) GetModifiedItemA
             private static readonly ImmutableArray<EntryState> s_allCachedEntries = ImmutableArray.Create(EntryState.Cached);
             private static readonly ImmutableArray<EntryState> s_allModifiedEntries = ImmutableArray.Create(EntryState.Modified);
             private static readonly ImmutableArray<EntryState> s_allRemovedEntries = ImmutableArray.Create(EntryState.Removed);
+            private static readonly ImmutableArray<EntryState> s_allRemovedDueToInputRemoval = ImmutableArray.Create(EntryState.Removed);
```
Comment (jcouv) [inline src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs:472]: nit: a comment here could be helpful (why we need a sentinel similar to `s_allRemovedEntries` but different)

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs [hunk 4]
```diff
@@ -515,9 +522,27 @@ public bool Matches(TableEntry entry, IEqualityComparer<T> equalityComparer)
...
+                        itemBuilder.Add(this.GetItem(i));
+                    }
+                }
+
+                Debug.Assert(itemBuilder.Count < this.Count);
+                return new TableEntry(OneOrMany.Create(itemBuilder.ToImmutableArray()), s_allCachedEntries, anyRemoved: false);
+            }
 
-            public TableEntry AsRemoved() => new(_items, s_allRemovedEntries);
+            public TableEntry AsRemovedDueToInputRemoval() => new(_items, s_allRemovedDueToInputRemoval, anyRemoved: true);
```
Comment (jcouv) [inline src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs:545]: Not related to this PR (ie. don't fix, but keep in mind in future changes): we have a policy to avoid target-typed `new` in the compiler codebase, consider fixing the few that snuck in when you encounter them and touch that code.

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs [hunk 5]
```diff
@@ -199,7 +203,7 @@ public bool TryRemoveEntries(TimeSpan elapsedTime, ImmutableArray<(IncrementalGe
                 }
 
                 // Mark the corresponding entries to this node execution in the previous table as removed.
-                var previousEntries = _previous._states[_states.Count].AsRemoved();
+                var previousEntries = _previous._states[_states.Count].AsRemovedDueToInputRemoval();
```
Comment (jcouv) [inline src/Compilers/Core/Portable/SourceGeneration/Nodes/NodeStateTable.cs:206]: nit: this is the only place where we use `AsRemovedDueToInputRemoval()`. It may be helpful to adjust the comment for more details on why.

File: src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs [hunk 6]
```diff
@@ -1233,6 +1236,69 @@ class YAttribute : System.Attribute { }
...
+            """);
+        verify(ref driver, compilation);
+
+        // Modify Class2 (make it internal).
+        replace(ref compilation, parseOptions, "Class2", """
+            [Generate]
+            [System.Obsolete]
+            internal partial class Class2 { }
+            """);
+        verify(ref driver, compilation);
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs:1286]: nit: If I understood correctly, the main thing we're verifying is that we didn't assert/crash. Consider also verifying the correct output from the incremental generator at each step.

File: src/Compilers/CSharp/Test/Semantic/SourceGeneration/StateTableTests.cs [hunk 7]
```diff
@@ -983,6 +983,72 @@ public void Modified_Entry_Adding_Outputs_Records_Added_Step_State()
...
 
+        [Fact, WorkItem(66451, "https://github.com/dotnet/roslyn/issues/66451")]
+        public void Node_Table_When_Previous_Was_Larger()
+        {
+            ImmutableArray<ImmutableArray<string>> values = ImmutableArray.Create(ImmutableArray.Create("class1"), ImmutableArray.Create("class2"));
+            var inputNode = new InputNode<ImmutableArray<string>>(_ => values).WithTrackingName("Input");
+            var transformNode = new TransformNode<ImmutableArray<string>, string>(inputNode, (arr, ct) => arr[0] == "class3" ? ImmutableArray<string>.Empty : arr, name: "SelectMany");
+
+            DriverStateTable.Builder dstBuilder = GetBuilder(DriverStateTable.Empty, trackIncrementalGeneratorSteps: false);
+            _ = dstBuilder.GetLatestStateTableForNode(transformNode);
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/SourceGeneration/StateTableTests.cs:994]: nit: Consider also asserting the table entries from the `transformNode` before making changes

File: src/Compilers/CSharp/Test/Semantic/SourceGeneration/StateTableTests.cs [hunk 8]
```diff
@@ -983,6 +983,72 @@ public void Modified_Entry_Adding_Outputs_Records_Added_Step_State()
...
+
+            AssertTableEntries(table, ImmutableArray.Create(("class4", EntryState.Modified, 0)));
+
+            // now, remove the first input altogether
+            values = ImmutableArray.Create(ImmutableArray.Create("class1"));
+            dstBuilder = GetBuilder(dstBuilder.ToImmutable(), trackIncrementalGeneratorSteps: false);
+            table = dstBuilder.GetLatestStateTableForNode(transformNode);
+
+            AssertTableEntries(table, ImmutableArray.Create(("class4", EntryState.Removed, 0), ("class1", EntryState.Added, 0)));
+            AssertTableEntries(table.AsCached(), ImmutableArray.Create(("class1", EntryState.Cached, 0)));
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/SourceGeneration/StateTableTests.cs:1016]: If I understood correctly, the core of this PR is that `AsCached()` may keep some deleted entries.
Could we add a test at this level that shows that?

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 9). Looks good, mainly some clarifications and a test suggestion.

File: src/Compilers/CSharp/Test/Semantic/SourceGeneration/StateTableTests.cs (hunk 8 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Test/Semantic/SourceGeneration/StateTableTests.cs:1016]: The NodeStateTable doesn't expose much details about this state, but I can assert count.

**Comment by jcouv** [comment]
@chsienki for second review. Thanks

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 14)
