### PR TITLE
Fix Double-to-Long overflow check

### LINKED ISSUE #73032: VB.NET compiler erroneously reports error BC30439 when converting certain large Double values to Long
Any constant or literal `Double` should be convertible to `Long` at compile time if its value is within the range of the `Long` data type (approximately ±9.223E+18). However, if the value is a large positive number between `&H7000000000000400L` and `&H7FFFFFFFFFFFFC00L`, then the error `"BC30439: Constant expression not representable in type 'Long'."` occurs:
```vb
Console.WriteLine(CType(9.0E+18, Long))
'                       ~~~~~~~
Console.WriteLine(CType(CDbl(&H7000000000000400L), Long))
'                       ~~~~~~~~~~~~~~~~~~~~~~~~~
Console.WriteLine(CType(CDbl(&H7FFFFFFFFFFFFC00L), Long))
'                       ~~~~~~~~~~~~~~~~~~~~~~~~~

' Expected behavior: No errors.
' Actual behavior: Error BC30439 is reported on each line as indicated.
```

This bug does not affect `Double` values in the range `&H8000000000000000L` (`Long.MinValue`) through `&H7000000000000000L`:
```vb
Console.WriteLine(CType(-9.0E+18, Long))                  ' -9000000000000000000
Console.WriteLine(CType(CDbl(&H8000000000000000L), Long)) ' -9223372036854775808
Console.WriteLine(CType(CDbl(&H8000000000000400L), Long)) ' -9223372036854774784
Console.WriteLine(CType(CDbl(&H8FFFFFFFFFFFFC00L), Long)) ' -8070450532247929856
Console.WriteLine(CType(CDbl(&H9000000000000000L), Long)) ' -8070450532247928832
Console.WriteLine(CType(CDbl(&H7000000000000000L), Long)) '  8070450532247928832

' Expected and actual behavior: No errors.
```

This bug also does not affect run-time conversions:
```vb
Dim a = 9.0E+18
Dim b = CDbl(&H7000000000000400L)
Dim c = CDbl(&H7FFFFFFFFFFFFC00L)
Console.WriteLine(CType(a, Long)) ' 9000000000000000000
Console.WriteLine(CType(b, Long)) ' 8070450532247929856
Console.WriteLine(CType(c, Long)) ' 9223372036854774784

' Expected and actual behavior: No errors.
```

It looks like this bug affects all versions of the VB.NET compiler, including pre-Roslyn versions like C:\Windows\Microsoft.NET\Framework\v2.0.50727\vbc.exe.

This bug does not affect the C# compiler.

### PR DESCRIPTION
**Pull request by MichaelJLiu**
Fixes #73032.

This PR addresses a bug in the VB.NET compiler.

# Description

Any constant or literal `Double` should be convertible at compile time to `Long` if its value is within the range of the `Long` data type (approximately ±9.223E+18). However, if the value is a large positive number between `&H7000000000000400L` and `&H7FFFFFFFFFFFFC00L`, then the error `"BC30439: Constant expression not representable in type 'Long'."` occurs:
```vb
Const w As Long = CType(9.0E+18, Long)
'                       ~~~~~~~ BC30439
Const x As Long = &H7000000000000400L
Const y As Double = x
Const z As Long = CType(y, Long)
'                       ~ BC30439
```

In contrast, large negative numbers are unaffected:
```vb
Const w As Long = CType(-9.0E+18, Long) ' OK

Const x As Long = Long.MinValue
Const y As Double = x
Const z As Long = CType(y, Long) ' OK
```

# Root Cause

Lines 603-609 of the [CompileTimeCalculations.DetectFloatingToIntegralOverflow method](https://github.com/dotnet/roslyn/blob/Visual-Studio-2022-Version-17.9/src/Compilers/VisualBasic/Portable/Semantics/CompileTimeCalculations.vb#L603,L609) check whether the input value is between `&H7000000000000000L` and `&H8000000000000000UL`, exclusive:

```vb
If sourceValue > &H7000000000000000L Then
    Dim temporary As Double = (sourceValue - &H7000000000000000L)

    If temporary < &H7000000000000000L AndAlso UncheckedCLng(temporary) > &H1000000000000000L Then
        Return False
    End If
Else
    Return False
End If
```

On line 606, however, the comparison `UncheckedCLng(temporary) > &H1000000000000000L` is incorrect; it should use `<` instead. This can be confirmed in two ways:

1.  In the `isUnsigned` branch earlier in this same method, the analogous comparison uses the correct operator:
    ```vb
    Dim temporary As Double = (sourceValue - &HF000000000000000UL)

    If temporary < &H7000000000000000L AndAlso UncheckedCLng(temporary) < &H1000000000000000L Then
        Return False
    End If
    ```

2.  Comments in this method reference the Shared Source CLI source file fjitdef.h, from which this code was presumably adapted. [There](https://github.com/SSCLI/sscli20_20060311/blob/707ae167cb556e76297df525369a5bdb0c6abee7/clr/src/fjit/fjitdef.h#L4440), the comparison also uses the correct operator:

    ```cpp
    if (val > I64(0x7000000000000000)) {
        double tmp = val - I64(0x7000000000000000);
        if (tmp < I64(0x7000000000000000) &&
            (__int64)tmp < I64(0x1000000000000000)) {
            goto success;
        }
    }
    else {
        goto success;
    }
    ```

# Unit Tests

I added test cases for the minimum and maximum `Double` values that are convertible to `Long`: `CDbl(&H8000000000000000L)` (which has always worked) and `CDbl(&H7FFFFFFFFFFFFC00L)` (which was previously broken).

The original test case `CDbl(&H70000000000000F0L)` failed to catch this bug because `CDbl` rounded it down to `&H7000000000000000L`.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@MichaelJLiu Could you please open an issue and link this PR to it? Also, please include information whether the issue is present in the legacy (non-Roslyn) VB compiler. It is a part of the .NET Framework for Desktop and, usually, can be found as ```c:\Windows\Microsoft.NET\Framework\v4.0.30319\vbc.exe```

**Comment by MichaelJLiu** [comment]
@AlekseyTs I've opened issue #73032 as requested, but I don't have permission to link it to this PR.

**Comment by AlekseyTs** [comment]
> but I don't have permission to link it to this PR.

You already did by mentioning the issue by its number in your comment.

File: src/Compilers/VisualBasic/Test/Semantic/Semantics/Conversions.vb [hunk 1]
```diff
@@ -605,7 +605,8 @@ End Class
                     New TypeAndValue(uint64Type, CULng(18)),
                     New TypeAndValue(decimalType, CDec(-11.3)),
                     New TypeAndValue(doubleType, CDbl(&HF000000000000000UL)),
-                    New TypeAndValue(doubleType, CDbl(&H70000000000000F0L)),
+                    New TypeAndValue(doubleType, CDbl(&H8000000000000000L)),
+                    New TypeAndValue(doubleType, CDbl(&H7FFFFFFFFFFFFC00L)),
```
Comment (cston) [inline src/Compilers/VisualBasic/Test/Semantic/Semantics/Conversions.vb:609]: Should these cases be added to `ConstantExpressionConversions2` as well, at line 1169?

**Comment by cston** [comment]
@MichaelJLiu, thanks for the detailed description.

> However, if the value is a large positive number between &H7000000000000400L and &H7FFFFFFFFFFFFC00L, then the error "BC30439: Constant expression not representable in type 'Long'." occurs:

For reference, the corresponding C# code succeeds (see [sharplab.io](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7NAExAGoAfAAQCYBGAWAChGBvRgAg7cjwGcM2ANhDwBzNgHc2AXjYAKIaICUATgB0ABgCiJGgA4A3O07c+g4WITS26hAHZ1Dx04coHAGUMNOXYacIQcYAEYNgBPKwRPbxN+BTEALyt5c0VQzyMOChplWXFFKM4snIR8jLYi2XjShgBfRkYwAAsYMABrGEIWMpizUQkkuJUNbT0Cjh64tksZG3tnedd1D27ffn9A4LCIsZ9eWPM2RJlkpTT6r0Ls3OrvCpKdiqrPOoYgA===)):
```csharp
const long w = (long)9.0E+18; // ok
const long x = 0x7000000000000400L;
const double y = x;
const long z = (long)y; // ok
```

File: src/Compilers/VisualBasic/Test/Semantic/Semantics/Conversions.vb [hunk 2]
```diff
@@ -605,7 +605,8 @@ End Class
                     New TypeAndValue(uint64Type, CULng(18)),
                     New TypeAndValue(decimalType, CDec(-11.3)),
                     New TypeAndValue(doubleType, CDbl(&HF000000000000000UL)),
-                    New TypeAndValue(doubleType, CDbl(&H70000000000000F0L)),
```
Comment (cston) [inline src/Compilers/VisualBasic/Test/Semantic/Semantics/Conversions.vb:608]: >&H70000000000000F0L [](http://example.com/codeflow?start=54&length=19)

Would it make sense to use the other value from the description, `&H7000000000000400L`, instead of this case?

**Comment by cston** [comment]
>                     }

Perhaps we should also have a separate specific test for [https://github.com/dotnet/roslyn/issues/73032](https://github.com/dotnet/roslyn/issues/73032), that compiles and runs the code from that issue and checks the expected values:
```vb
Console.WriteLine(CType(9.0E+18, Long))
Console.WriteLine(CType(CDbl(&H7000000000000400L), Long))
Console.WriteLine(CType(CDbl(&H7FFFFFFFFFFFFC00L), Long))
```
If so, please include a `<WorkItem()>` attribute on that test that references the issue.

---
Refers to: src/Compilers/VisualBasic/Test/Semantic/Semantics/Conversions.vb:614 in e8946b3. [](commit_id = e8946b363f0195fb0368365e5bb067965d531cd8, deletion_comment = False)

**Review by cston — APPROVED** [review]

**Comment by cston** [comment]
Thanks @MichaelJLiu. Please avoid using force-push while the PR is being reviewed since it makes it difficult to see the differences between commits. We'll use "squash and merge" when merging.

**Comment by cston** [comment]
@AlekseyTs, @dotnet/roslyn-compiler, please review.

File: src/Compilers/VisualBasic/Test/Semantic/Semantics/Conversions.vb (hunk 2 above)
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/Semantics/Conversions.vb:608]: >New TypeAndValue(doubleType, CDbl(&H70000000000000F0L)), [](http://example.com/codeflow?start=20&length=56)

Please keep this value

File: src/Compilers/VisualBasic/Test/Semantic/Semantics/Conversions.vb [hunk 3]
```diff
@@ -1165,7 +1166,8 @@ End Class
...
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/Semantics/Conversions.vb:1168]: >New TypeAndValue(doubleType, CDbl(&H70000000000000F0L)), [](http://example.com/codeflow?start=20&length=56)

Please keep this value

File: src/Compilers/VisualBasic/Test/Semantic/Semantics/Conversions.vb [hunk 4]
```diff
@@ -5095,5 +5097,42 @@ End Module
...
 
+        <WorkItem(73032, "https://github.com/dotnet/roslyn/issues/73032")>
+        <Fact()>
+        Public Sub ConvertLargeDoubleConstantsAndLiteralsToLong()
+            Dim compilation = CreateCompilationWithMscorlib40AndVBRuntime(
+    <compilation>
+        <file name="a.vb"><![CDATA[
+Module Program
+    Sub Main()
+        System.Console.WriteLine(CType(CDbl(&H8000000000000000L), Long))
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/Semantics/Conversions.vb:5108]: >System.Console.WriteLine(CType(CDbl(&H8000000000000000L), Long)) [](http://example.com/codeflow?start=8&length=64)

Instead of outputting the values, I think we should compare them with result of conversions performed at runtime. For example it is not obvious to me that the values in the output are correct. I think the overflow check for VB is set to true by default, but it would be good to set this option explicitly (`WithOverflowChecks`).

**Comment by AlekseyTs** [comment]
Done with review pass (commit 1)

File: src/Compilers/VisualBasic/Test/Semantic/Semantics/Conversions.vb (hunk 4 above)
Comment (MichaelJLiu) [reply src/Compilers/VisualBasic/Test/Semantic/Semantics/Conversions.vb:5108]: In each case, the Long argument to CDbl is the expected result of calling CType. So I could write
```
System.Console.WriteLine(CType(CDbl(&H8000000000000000L), Long) = &H8000000000000000L)
```
and verify that the output is True. Is that acceptable?

File: src/Compilers/VisualBasic/Test/Semantic/Semantics/Conversions.vb (hunk 2 above)
Comment (MichaelJLiu) [reply src/Compilers/VisualBasic/Test/Semantic/Semantics/Conversions.vb:608]: I don't think we should keep `CDbl(&H70000000000000F0L)` because it's misleading: the integer `&H70000000000000F0L` can't be represented exactly by a Double. As I noted in the PR description, CDbl rounds it down to `&H7000000000000000L`, which is why it failed to catch this bug.

Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Test/Semantic/Semantics/Conversions.vb:608]: Thanks for the explanation. Sounds reasonable.

File: src/Compilers/VisualBasic/Test/Semantic/Semantics/Conversions.vb (hunk 4 above)
Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Test/Semantic/Semantics/Conversions.vb:5108]: This is going to rely on compile time constant folding for equality, which would be desirable to avoid. The goal is to compare result of compile time constant folding with result that doesn't rely on constant folding. I have some thing like the following in mind:
```
 System.Console.WriteLine(CType(CDbl(&H8000000000000000L), Long) = ConvertToLong(CDbl(&H8000000000000000L)))


Function ConvertToLong(x as Double) As Long
    Return CType(x, Long)
End Function
```

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 2)

**Comment by cston** [comment]
Thanks @MichaelJLiu!
