### PR TITLE
Fix couple of false positives in unused parameter analyzer

### LINKED ISSUE #36816: False positive of IDE0060 on a partial method with parameters
VSF_TYPE_MARKDOWNWhen defining a partial method such as 

```
    Partial Private Sub ShowIdeMessage(msg As String)
    End Sub
```
IDE0060 is shown in the messages with the suggestion to remove the parameter
This should not happen because the parameter can be needed in the real implementation.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/448246/false-positive-of-ide0060-on-a-partial-method-with.html
VSTS ticketId: 788478_
_These are the original issue comments:_

Johan Gillis on 2/11/2019, 01:21 AM (136 days ago): <p>another false positive:</p><p>following code gives: IDE0060 Remove unused parameter 'xyz' </p><pre>    Private Function ExtractInfo(xyz As XDocument) As String
        Dim txt = xyz.Root.&lt;ad&gt;.&lt;title&gt;.&lt;tx&gt;.Value & vbCrLf
        Return txt
    End Function
<br></pre>

Visual Studio Feedback System on 2/19/2019, 06:58 PM (127 days ago): <p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact.See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq  . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/  . We'll keep you posted on any updates to this feedback.</p>

_These are the original issue solutions:_
(no solutions)

### LINKED ISSUE #36817: IDE0060 Remove Unused Parameter reported for code I'm still working on
VSF_TYPE_MARKDOWNI'm adding a new parameter to a method that already exists. As I'm typing the type of the parameter, VS immediately suggests I should fix the &quot;error&quot; of having an unused parameter by suppressing the IDE0060 code warning. However, in this scenario I haven't even typed in the parameter's *name* yet, so there's no point warning me about an unused parameter because the code isn't even valid!

Please see the screenshot where I've typed in `IMemoryCache` as the type name for my constructor parameter, but I haven't typed in the parameter name. The suppression suggestion shouldn't show up until I at least have a variable name.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/586149/ide0060-remove-unused-parameter-reported-for-code.html
VSTS ticketId: 900624_
_These are the original issue comments:_

Visual Studio Feedback System on 5/29/2019, 01:18 AM (29 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 5/30/2019, 07:50 PM (27 days ago): <p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/ . We'll keep you posted on any updates to this feedback.</p>

Visual Studio Feedback System on 6/10/2019, 06:19 PM (16 days ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

_These are the original issue solutions:_
(no solutions)

### PR DESCRIPTION
**Pull request by mavasani**
1. Do not flag parameters whose name has not yet been written (empty string). Fixes #36817
2. Do not flag parameters of partial method definition part. Fixes #36816

### CODE REVIEW

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs [hunk 1]
```diff
@@ -183,13 +183,15 @@ private bool IsUnusedParameterCandidate(IParameterSymbol parameter)
                 // we don't have to bail out on reporting unused parameters for all public methods.
 
                 if (parameter.IsImplicitlyDeclared ||
+                    parameter.Name.Length == 0 ||
```
Comment (genlu) [inline src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs]: Is it possible to check for error in this case and bail early?

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs]: Could we also consider just not doing this analysis on methods that have *any* syntax errors in them.  I think it's a bit odd to think of something as "unused" when we dont' even know what the code means :)

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs [hunk 2]
```diff
@@ -183,13 +183,15 @@ private bool IsUnusedParameterCandidate(IParameterSymbol parameter)
...
                     parameter.Name == DiscardVariableName ||
                     !(parameter.ContainingSymbol is IMethodSymbol method) ||
                     method.IsImplicitlyDeclared ||
                     method.IsExtern ||
                     method.IsAbstract ||
                     method.IsVirtual ||
                     method.IsOverride ||
+                    method.PartialImplementationPart != null ||
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs]: i hate this entire check because it's just a blob of conditions, with no explanation on any of it as to why they're relevant.

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs [hunk 3]
```diff
@@ -57,13 +57,35 @@ private sealed partial class SymbolStartAnalyzer
...
                     var symbolAnalyzer = new SymbolStartAnalyzer(analyzer, eventsArgType, attributeSetForMethodsToIgnore, deserializationConstructorCheck);
                     symbolAnalyzer.OnSymbolStart(symbolStartContext);
                 }, SymbolKind.NamedType);
+
+                return;
+
+                // Local functions
+                static bool HasSyntaxErrors(INamedTypeSymbol namedTypeSymbol, CancellationToken cancellationToken)
+                {
+                    foreach (var tree in namedTypeSymbol.Locations.Select(l => l.SourceTree))
```
Comment (jasonmalinowski) [inline src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs]: A comment on exactly *what* span this is might be helpful here.

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs [hunk 4]
```diff
@@ -57,13 +57,35 @@ private sealed partial class SymbolStartAnalyzer
...
+                    {
+                        if (tree.GetDiagnostics(cancellationToken).Any(d => d.Severity == DiagnosticSeverity.Error))
```
Comment (jasonmalinowski) [inline src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs]: There's no node we can grab and call SyntaxNode.ContainsDiagnostics?

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs (hunk 3 above)
Comment (mavasani) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs]: I am just being ultra-conservative and bailing on any syntax errors in file.

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs (hunk 4 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs]: Unfortunately 'containsdiagnostic' is often wrong.  For example, syntactic *warnings* will trigger it.  

We should just get the SyntaxReferences for the NamedTypeSymbol though and check those directly (i.e. checking for the right severity).  

so this should be more like:

```c#
foreach (var syntaxRef in namedTypeSymbol.DeclaringSyntaxReferences) 
     if (syntaxRef.GetSyntax(cancellationToken).GetDiagnostics(...))`

**Comment by JoeRobich** [comment]
Integration GitHub check failed to update from AzDO. All green https://dev.azure.com/dnceng/public/_build/results?buildId=241955
