### PR TITLE
Pay attention to sizes and lower bounds specified for multi-dimensional arrays in metadata signatures.

### LINKED ISSUE #4954: Compilers are unable to consume signatures that do not specify bounds for multi-dimensional arrays.
```
class Program
{
    static void Main()
    {
        var t = new Test();
        t.Test3();
        t.Test4(new double[1,1]);

	t = new C();
        t.Test3();
        t.Test4(new double[1,1]);
    }
}

class C : Test
{
    public override double[,] Test3()
    {
        System.Console.WriteLine("Overriden3");
        return null;
    }
    public override void Test4(double[,] a)
    {
        System.Console.WriteLine("Overriden4");
    }
}
```

Compile code above by referencing a library with a type built from this IL:
```
.class public auto ansi beforefieldinit Test
       extends [mscorlib]System.Object
{
    .method public hidebysig specialname rtspecialname 
            instance void  .ctor() cil managed
    {
      // Code size       7 (0x7)
      .maxstack  1
      IL_0000:  ldarg.0
      IL_0001:  call       instance void [mscorlib]System.Object::.ctor()
      IL_0006:  ret
    } // end of method Test1::.ctor

    .method public hidebysig newslot virtual 
            instance float64[,] Test3() cil managed
    {
      // Code size       11 (0xb)
      .maxstack  4
      IL_0000:  ldstr      "Test3"
      IL_0005:  call       void [mscorlib]System.Console::WriteLine(string)
      IL_0007:  ldc.i4.1
      IL_0008:  ldc.i4.1
      IL_0009:  newobj     instance void float64[,]::.ctor(int32,int32)
      IL_000a:  ret
    } // end of method Test::Test3

    .method public hidebysig newslot virtual 
            instance void Test4(float64[,] x) cil managed
    {
      // Code size       11 (0xb)
      .maxstack  2
      IL_0000:  ldstr      "Test4"
      IL_0005:  call       void [mscorlib]System.Console::WriteLine(string)
      IL_000a:  ret
    } // end of method Test::Test4
} // end of class Test
```

An executable produced by VS2015 compiler fails with the following errors:
```
Unhandled Exception: System.MissingMethodException: Method not found: 'Double[,] Test.Test3()'.
   at Program.Main()
Unhandled Exception: System.MissingMethodException: Method not found: 'Void Test.Test4(Double[,])'.
   at Program.Main()
```

An executable produced by VS2013 compiler successfully calls the methods, but overriding methods aren't considered as valid overrides by CLR.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #4954.

We will treat Sizes and LowerBounds similar to custom modifiers. They should match for the purpose
of signature comparison (overriding/implementing, etc), but shouldn't affect conversions.

@gafter, @VSadov, @jaredpar, @agocke Please review. Many files for C# compiler were modified due to simple parameter rename.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
Ping. @gafter, @VSadov, @jaredpar, @agocke Please review.

File: src/Compilers/CSharp/Portable/Emitter/Model/ArrayTypeSymbolAdapter.cs [hunk 1]
```diff
@@ -39,11 +39,25 @@ IEnumerable<int> Cci.IArrayTypeReference.LowerBounds
         {
             get
             {
-                for (int i = 0; i < this.Rank; ++i)
-                    yield return 0;
+                var lowerBounds = this.LowerBounds;
+
+                if (lowerBounds.IsDefault)
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Emitter/Model/ArrayTypeSymbolAdapter.cs]: Can this be `return lowerBounds ?? DefaultLowerBounds(this.Rank);`?

File: src/Compilers/CSharp/Portable/Emitter/Model/ArrayTypeSymbolAdapter.cs [hunk 2]
```diff
@@ -39,11 +39,25 @@ IEnumerable<int> Cci.IArrayTypeReference.LowerBounds
...
+                    return DefaultLowerBounds(this.Rank);
+                }
+                else
+                {
+                    return lowerBounds;
+                }
             }
         }
 
+        private static IEnumerable<int> DefaultLowerBounds(int rank)
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Emitter/Model/ArrayTypeSymbolAdapter.cs]: Use `Enumerable.Repeat` instead?

File: src/Compilers/CSharp/Portable/Emitter/Model/ArrayTypeSymbolAdapter.cs [hunk 3]
```diff
@@ -56,7 +70,20 @@ IEnumerable<ulong> Cci.IArrayTypeReference.Sizes
...
+                    return SpecializedCollections.EmptyEnumerable<ulong>();
+                }
+
+                return GetSizes();
+            }
+        }
+
+        private IEnumerable<ulong> GetSizes()
+        {
+            foreach (var size in this.Sizes)
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Emitter/Model/ArrayTypeSymbolAdapter.cs]: Use `Enumerable.Repeat`?

File: src/Compilers/CSharp/Portable/Emitter/Model/ArrayTypeSymbolAdapter.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Emitter/Model/ArrayTypeSymbolAdapter.cs]: I don't think so. ImmutableArray is not a reference type and is not a Nullable type. Regardless, I prefer code written this way.

File: src/Compilers/CSharp/Portable/Emitter/Model/ArrayTypeSymbolAdapter.cs (hunk 3 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Emitter/Model/ArrayTypeSymbolAdapter.cs]: I do not think it is applicable here.

File: src/Compilers/CSharp/Portable/Emitter/Model/ArrayTypeSymbolAdapter.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Emitter/Model/ArrayTypeSymbolAdapter.cs]: OK

File: src/Compilers/CSharp/Portable/Emitter/Model/ArrayTypeSymbolAdapter.cs (hunk 3 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Emitter/Model/ArrayTypeSymbolAdapter.cs]: Right, sorry.

**Comment by gafter** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Emitter/Model/ArrayTypeSymbolAdapter.cs (hunk 2 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Emitter/Model/ArrayTypeSymbolAdapter.cs]: This is an option, I guess. However this is not a new code, it is the original implementation of Cci.IArrayTypeReference.LowerBounds extracted into a method. I would prefer to keep decision about changing it outside of scope of this PR. I'll open a separate issue to track this.

**Comment by VSadov** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Emitter/Model/ArrayTypeSymbolAdapter.cs (hunk 2 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Emitter/Model/ArrayTypeSymbolAdapter.cs]: Opened #5080.
