### PR TITLE
Fix UseNullPropagation codefix doesn't recognize `x is null ? null : x.y` pattern

### LINKED ISSUE #23043: UseNullPropagation codefix doesn't recognize `x is null ? null : x.y` pattern
Also, `ReferenceEquals(foo, null) ? null : foo.y`

```C#
        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseNullPropagation)]
        public async Task TestWithNullableTypeAndIsNull()
        {
            await TestInRegularAndScriptAsync(
@"
class C
{
    public int? f;
    void M(C c)
    {
        int? x = [||]c is null ? null : c.f;
    }
}",
@"
class C
{
    public int? f;
    void M(C c)
    {
        int? x = c?.f;
    }
}");
        }
```

### PR DESCRIPTION
**Pull request by schovanec**
Fixes #23043. This should handle both the `x is null` and the `ReferenceEquals(x, null)` scenarios.

### Customer scenario

Visual Studio 2017 contains a "Use Null Propagation" analyzer and code fix that helps users convert conditional code (`if` statements and ternary expressions) into the new `?.` syntax. While the analysis already supports the most common styles of null checks, there were two specific cases that were simply ignored:

* Conditions based on the new pattern syntax: `x is null`
* Conditions based on calls to `object.ReferenceEquals`

### Bugs this fixes

Fixes #23043 

### Workarounds, if any

None needed

### Risk

Low¹. Changes are restricted to a single analyzer/fix, and tests² are added for all newly supported cases.

¹ ✔️ I need to apply a Fix All on Roslyn before and after this change to review the difference for bugs. (Confirmed via https://github.com/dotnet/roslyn/pull/23610#issuecomment-350328171)
² ✔️ Negative tests would be good as well. I am requesting them in review. (Confirmed via https://github.com/dotnet/roslyn/pull/23610#issuecomment-350294478)

### Performance impact

Should be low. The code was reviewed with consideration for known performance sensitivities in analyzers, and will be run through AnalyzerRunner prior to final release.

### Is this a regression from a previous update?

No.

### Root cause analysis

Previously identified optional work from a prior feature.

### How was the bug found?

Spec review of the original feature.

### Test documentation updated?

No.

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/UseNullPropagation/UseNullPropagationTests.cs [hunk 1]
```diff
@@ -478,5 +478,125 @@ void Main(S? s)
...
+        public async Task TestWithNullableTypeAndReferenceEquals()
+        {
+            await TestInRegularAndScriptAsync(
+@"
+class C
+{
+    public int? f;
+    void M(C c)
+    {
+        int? x = [||]ReferenceEquals(c, null) ? null : c.f;
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/UseNullPropagation/UseNullPropagationTests.cs]: Cool changes :)

Consider also supporting:

```!ReferenceEquals(c, null) ? c.f : null```

File: src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs [hunk 2]
```diff
@@ -49,18 +50,27 @@ protected AbstractUseNullPropagationDiagnosticAnalyzer()
...
+
         protected override void InitializeWorker(AnalysisContext context)
         {
             context.RegisterCompilationStartAction(startContext =>
             {
                 var expressionTypeOpt = startContext.Compilation.GetTypeByMetadataName("System.Linq.Expressions.Expression`1");
+
+                var objectType = startContext.Compilation.GetSpecialType(SpecialType.System_Object);
+                var referenceEqualsMethod = objectType?.GetMembers(nameof(ReferenceEquals))
+                                      .OfType<IMethodSymbol>()
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs]: try to align these with the previous line.

File: src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs [hunk 3]
```diff
@@ -88,21 +98,13 @@ private void AnalyzeSyntax(SyntaxNodeAnalysisContext context, INamedTypeSymbol e
 
             conditionNode = syntaxFacts.WalkDownParentheses(conditionNode);
 
-            var condition = conditionNode as TBinaryExpressionSyntax;
-            if (condition == null)
+            var isEqualityLikeCondition = TryAnalyzeCondition(
+                context, syntaxFacts, referenceEqualsMethod, conditionNode, out var conditionLeft, out var conditionRight, out var isEquals);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs]: can you wrap this so the outvars are on the next line.

File: src/EditorFeatures/CSharpTest/UseNullPropagation/UseNullPropagationTests.cs (hunk 1 above)
Comment (schovanec) [reply src/EditorFeatures/CSharpTest/UseNullPropagation/UseNullPropagationTests.cs]: That’s a good idea. I’ll look into that later tonight.

File: src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs (hunk 2 above)
Comment (sharwell) [reply src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs]: ➡️ No need to align expressions that the editor doesn't align automatically (which is only the LINQ syntax). If you adjust the indentation, just make it a single indentation, like this:

```csharp
var referenceEqualsMethod = objectType?.GetMembers(nameof(ReferenceEquals))
    .OfType<IMethodSymbol>()
```

File: src/EditorFeatures/CSharpTest/UseNullPropagation/UseNullPropagationTests.cs [hunk 4]
```diff
@@ -478,5 +478,125 @@ void Main(S? s)
 }
 ");
         }
+
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseNullPropagation)]
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/UseNullPropagation/UseNullPropagationTests.cs]: :bulb: Also add a `WorkItem` attribute to each of the new tests:

```csharp
[WorkItem("https://github.com/dotnet/roslyn/issues/23043")]
```

File: src/EditorFeatures/CSharpTest/UseNullPropagation/UseNullPropagationTests.cs (hunk 1 above)
Comment (sharwell) [reply src/EditorFeatures/CSharpTest/UseNullPropagation/UseNullPropagationTests.cs]: :bulb: Also have an opportunity here for `!(c is null)`

File: src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs [hunk 5]
```diff
@@ -49,18 +50,27 @@ protected AbstractUseNullPropagationDiagnosticAnalyzer()
...
+
                 startContext.RegisterSyntaxNodeAction(
-                    c => AnalyzeSyntax(c, expressionTypeOpt), GetSyntaxKindToAnalyze());
+                    c => AnalyzeSyntax(c, expressionTypeOpt, referenceEqualsMethod), GetSyntaxKindToAnalyze());
             });
 
         }
 
-        private void AnalyzeSyntax(SyntaxNodeAnalysisContext context, INamedTypeSymbol expressionTypeOpt)
+        private void AnalyzeSyntax(SyntaxNodeAnalysisContext context, INamedTypeSymbol expressionTypeOpt, IMethodSymbol referenceEqualsMethod)
```
Comment (sharwell) [inline src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs]: :bulb: This should be `referenceEqualsMethodOpt`. The `Opt` suffix indicates locally that the argument could be null. The local variables that get passed for this argument should also get renamed.

File: src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs [hunk 6]
```diff
@@ -181,9 +183,94 @@ private void AnalyzeSyntax(SyntaxNodeAnalysisContext context, INamedTypeSymbol e
...
+
+            var arguments = syntaxFacts.GetArgumentsOfInvocationExpression(invocation);
+            if (arguments.Count != 2)
+            {
+                return false;
+            }
+
+            var semanticModel = context.SemanticModel;
+            var cancellationToken = context.CancellationToken;
+            var symbol = semanticModel.GetSymbolInfo(invocation, cancellationToken).Symbol;
```
Comment (sharwell) [inline src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs]: :bulb: `GetSymbolInfo` is quite expensive. Consider updating the code to place the syntax-based null checks (the calls to `IsNullLiteralExpression`) before the call to `GetSymbolInfo`. I'm not overly concerned since you do have the name equality check a few lines above and `ReferenceEquals` isn't a particularly common name, so if it's not easy to make the change feel free to just create a new issue to address this later.

File: src/Workspaces/CSharp/Portable/LanguageServices/CSharpSyntaxFactsService.cs [hunk 7]
```diff
@@ -651,6 +651,9 @@ public SyntaxNode GetExpressionOfArgument(SyntaxNode node)
         public RefKind GetRefKindOfArgument(SyntaxNode node)
             => (node as ArgumentSyntax).GetRefKind();
 
+        public bool IsArgument(SyntaxNode node)
+            => node is ArgumentSyntax;
```
Comment (sharwell) [inline src/Workspaces/CSharp/Portable/LanguageServices/CSharpSyntaxFactsService.cs]: 💭 This makes me wonder why we aren't using `node.IsKind(SyntaxKind.Argument)`, but I see other methods like `IsCastExpression` doing the same thing. Should be fine.

**Comment by schovanec** [comment]
Thanks for the suggestions @sharwell. I'll make some changes when I get home tonight.

File: src/EditorFeatures/CSharpTest/UseNullPropagation/UseNullPropagationTests.cs (hunk 4 above)
Comment (zaytsev-victor) [reply src/EditorFeatures/CSharpTest/UseNullPropagation/UseNullPropagationTests.cs]: I think it should be ```[WorkItem(23043, "https://github.com/dotnet/Roslyn/issues/22699")]``` (:

Comment (sharwell) [reply src/EditorFeatures/CSharpTest/UseNullPropagation/UseNullPropagationTests.cs]: Ugh yes. Except to make me feel a bit better you changed the link by accident 😆 Third try?

```
[WorkItem(23043, "https://github.com/dotnet/roslyn/issues/23043")]
```

File: src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs (hunk 2 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs]: Note: we do often try to align long chains of linq-as-method calls.  In C# we try to align on the ```.```, and in VB we put the dot on the previous line and align on the name.  It would be nice to preserve that.

That said, going with single indentation is also acceptable.  It's usually strange indentation like this that we try to avoid.

File: src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs (hunk 6 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs]: Note: this should be fine in practice IMO.  By the time we're checking what symbol this is, we've already ensure the shape is ```ReferenceEquals(e1, e2) ? ... : ...``` that's going to be syntactically rare enough that we'll only being doing the semantic check sparingly.

File: src/Workspaces/CSharp/Portable/LanguageServices/CSharpSyntaxFactsService.cs (hunk 7 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/CSharp/Portable/LanguageServices/CSharpSyntaxFactsService.cs]: It never showed up in perf traces, and it kept things simple i.e. ```IsArgument -> "is Argument"```.  But feel free to change for any nodes that has a 1:1 correspondence with kinds.

File: src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs [hunk 8]
```diff
@@ -181,9 +183,94 @@ private void AnalyzeSyntax(SyntaxNodeAnalysisContext context, INamedTypeSymbol e
...
+
+            conditionLeft = syntaxFacts.GetExpressionOfArgument(arguments[0]);
+            conditionRight = syntaxFacts.GetExpressionOfArgument(arguments[1]);
+            return true;
+        }
+
         internal static SyntaxNode GetWhenPartMatch(
             ISyntaxFactsService syntaxFacts, ISemanticFactsService semanticFacts, SemanticModel semanticModel, SyntaxNode expressionToMatch, SyntaxNode whenPart)
         {
+            expressionToMatch = GetExpressionIfArgument(syntaxFacts, expressionToMatch);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs]: I'm curious why this is needed.  The only time you deal with argumetns is back in TryAnalyzeInvocationCondition.  But at the end of that, you always unwrap arguments to expressions.  So it's unclear how you would get an argument here.

File: src/EditorFeatures/VisualBasicTest/UseNullPropagation/UseNullPropagationTests.vb [hunk 9]
```diff
@@ -321,6 +321,90 @@ Class C
...
+
+        <Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseNullPropagation)>
+        Public Async Function TestWithNullableTypeAndReferenceEquals() As Task
+            Await TestInRegularAndScriptAsync(
+"
+Imports System
+
+Class C
+    Sub M(o As Object)
+        Dim v = [||]If (ReferenceEquals(o, Nothing), Nothing, o.ToString())
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/VisualBasicTest/UseNullPropagation/UseNullPropagationTests.vb]: so VB has 'ommitted' arguments which are funky and which may end up breaking some of the code htat assumes normal arguments.  Can you try this as a test:

```If (ReferenceEquals(o, ), Nothing, o.ToString())```
```If (ReferenceEquals(, nothing), Nothing, o.ToString())```

Note: i don't expect any actual code change, i just want to make sure we don't crash :)

File: src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs [hunk 10]
```diff
@@ -181,9 +183,94 @@ private void AnalyzeSyntax(SyntaxNodeAnalysisContext context, INamedTypeSymbol e
...
+            var cancellationToken = context.CancellationToken;
+            var symbol = semanticModel.GetSymbolInfo(invocation, cancellationToken).Symbol;
+            if (!referenceEqualsMethod.Equals(symbol))
+            {
+                return false;
+            }
+
+            conditionLeft = syntaxFacts.GetExpressionOfArgument(arguments[0]);
+            conditionRight = syntaxFacts.GetExpressionOfArgument(arguments[1]);
+            return true;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs]: i would change this to ```return conditionLeft != null && conditionRight != null; ``` as GetExpressionOfArgument can return null in VB.

File: src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs (hunk 8 above)
Comment (schovanec) [reply src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs]: The code fix calls into this and passes the node it finds at the location given as part of the diagnostic. With the ReferenceEquals case that node is an argument.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs]: Ah, that's a result of an earlier piece of code that needs to change.  Specifically, in the fixer change it from:

```c#
                var conditionalExpression = root.FindNode(diagnostic.AdditionalLocations[0].SourceSpan, getInnermostNodeForTie: true);
                var conditionalPart = root.FindNode(diagnostic.AdditionalLocations[1].SourceSpan);
                var whenPart = root.FindNode(diagnostic.AdditionalLocations[2].SourceSpan);
```

To:

```c#
                var conditionalExpression = root.FindNode(diagnostic.AdditionalLocations[0].SourceSpan, getInnermostNodeForTie: true);
                var conditionalPart = root.FindNode(diagnostic.AdditionalLocations[1].SourceSpan, getInnermostNodeForTie: true);
                var whenPart = root.FindNode(diagnostic.AdditionalLocations[2].SourceSpan, getInnermostNodeForTie: true);
```

Then you should not need to do the argument unwrapping.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs]: Sorry i didn't catch that earlier!

**Comment by chborl** [comment]
@dotnet-bot retest windows_debug_unit32_prtest please

**Comment by chborl** [comment]
@dotnet-bot retest windows_debug_unit64_prtest please

**Comment by chborl** [comment]
@dotnet-bot retest windows_release_unit64_prtest please

File: src/EditorFeatures/CSharpTest/UseNullPropagation/UseNullPropagationTests.cs (hunk 1 above)
Comment (schovanec) [reply src/EditorFeatures/CSharpTest/UseNullPropagation/UseNullPropagationTests.cs]: It was quite simple to implement this so that logical negation would be recognized on any condition, including `!(c == null)` and `!(c != null)`. If to only support it on the `ReferenceEquals` and pattern syntax I can change it.

File: src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs (hunk 6 above)
Comment (schovanec) [reply src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs]: It wasn't to difficult to shuffle this around so I changed it so that `GetSymbolInfo` is called last.

File: src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs (hunk 2 above)
Comment (schovanec) [reply src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs]: I originally had the dots lined up but I think I renamed the variable at some point. I put things back so the dots are lined up.

File: src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs (hunk 5 above)
Comment (schovanec) [reply src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs]: I changed this too. Let me know if I misinterpreted anything here.

File: src/Workspaces/CSharp/Portable/LanguageServices/CSharpSyntaxFactsService.cs (hunk 7 above)
Comment (schovanec) [reply src/Workspaces/CSharp/Portable/LanguageServices/CSharpSyntaxFactsService.cs]: I removed this method. I don't need it anymore with the change that @CyrusNajmabadi suggested in the code fix class.

File: src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs (hunk 8 above)
Comment (schovanec) [reply src/Features/Core/Portable/UseNullPropagation/AbstractUseNullPropagationDiagnosticAnalyzer.cs]: This change seems to work perfectly, thanks @CyrusNajmabadi.

**Comment by sharwell** [comment]
@schovanec I filled out the Ask Mode template in the original post. While reviewing the risk section, I identified two areas for potential improvement:

1. All of the newly added tests focus on one of the expressions being `null` (or `Nothing` in VB). The test suite would be improved if for each one of the existing tests *that you added*, a paired test was added that uses a value other than `null`. These tests ensure that the diagnostic does not flag cases where patterns and/or `ReferenceEquals` are used for a purpose other than a null check.

    ❓ @schovanec Do you want to implement these tests, or do you want me to get them added?

2. A manual differential regression test needs to be run on Roslyn.sln. This is a fairly involved process that I perform myself to ensure each step works as intended. However, since the test strategy has proven enormously valuable to me in other projects in the past, I'll repeat it here should you wish to follow along.
    1. Check out, build, and run the current Roslyn master branch

        <details>

        1. Check out the current **master** branch commit
        1. Set **VisualStudioSetup.Next** as the startup project
        1. Press <kbd>Ctrl</kbd>+<kbd>F5</kbd> to launch an experimental instance

        </details>

    1. Close the copy of Visual Studio where you had Roslyn.sln open
    1. Create a new branch in Git, e.g. **baseline**
    1. Write some code that will trigger the original diagnostic, and apply a Fix All in Solution to correct all instances of it
    1. Commit all changes to the new branch in Git
    1. Close the experimental instance of Visual Studio
    1. Check out the branch for this pull request, and merge the **master** branch into it. Then build an run it like you did for step (i).
    1. Repeat steps (ii) through (vi), but change the branch name to something else, e.g. **modified** (Make sure to create the **modified** branch at the same starting commit where you created **baseline** above)
    1. :arrow_right: Carefully review the difference between the **baseline** and **modified** branches in Git to identify any cases where the code fix did not apply the expected change.

**Comment by schovanec** [comment]
Those extra test cases make sense. I can add those but probably not until tomorrow at the earliest.

**Comment by schovanec** [comment]
I added some negative test cases. Let me know if any seem incorrect or if anything obvious (or not obvious) is missing.

I'm going to try and see if I can go through your manual procedure for my own benefit.

Dumb newbie question: If I push my branch after merging from master will it confuse anything in this pull request?

**Comment by schovanec** [comment]
@sharwell I was able to run through your regression steps and the result was zero differences between the two branches. I thought this was odd at first since there are new condition patterns that could be recognized. However after some searching there does not appear to be any occurrences of the new condition patterns anywhere in the Roslyn source. There are a few cases that match structurally but are not comparing with null and those were correctly not replaced, which is good.

I look forward to hearing what your results are.

**Comment by sharwell** [comment]
@Pilchie for ask mode

**Comment by Pilchie** [comment]
Approved - thanks.

**Comment by jcouv** [comment]
Nice. Thanks @schovanec!
