### PR TITLE
Remove strong reference to AnalyzerOptions in the analyzer manager ex…

### LINKED ISSUE #20065: Previews for light bulbs leaks solutions
**Version Used**: 400238e370ef760e178dd7a9db790e5feae7f3fb

**Steps to Reproduce**:

1. Create a new console app.
2. Invoke removed unused usings on the top.
3. Wait for the preview to appear.
4. Dismiss the preview.
5. GC.
6. Run !dumpheap -type PreviewWorkspace

**Expected Behavior**: There shouldn't be any.
**Actual Behavior**: There are two, because the solutions created to drive the preview are being leaked. The bad part of the GC root is I believe here:

            ->  27343b70 Microsoft.CodeAnalysis.CSharp.UseCollectionInitializer.CSharpUseCollectionInitializerDiagnosticAnalyzer
            ->  2733fea0 Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager+AnalyzerExecutionContext (dependent handle)
            ->  27381f58 System.Collections.Generic.Dictionary`2[[Microsoft.CodeAnalysis.Diagnostics.AnalyzerOptions, Microsoft.CodeAnalysis],[System.Runtime.CompilerServices.ConditionalWeakTable`2[[Microsoft.CodeAnalysis.Compilation, Microsoft.CodeAnalysis],[System.Threading.Tasks.Task`1[[Microsoft.CodeAnalysis.Diagnostics.HostCompilationStartAnalysisScope, Microsoft.CodeAnalysis]], mscorlib]], mscorlib]]
            ->  27382050 System.Collections.Generic.Dictionary`2+Entry[[Microsoft.CodeAnalysis.Diagnostics.AnalyzerOptions, Microsoft.CodeAnalysis],[System.Runtime.CompilerServices.ConditionalWeakTable`2[[Microsoft.CodeAnalysis.Compilation, Microsoft.CodeAnalysis],[System.Threading.Tasks.Task`1[[Microsoft.CodeAnalysis.Diagnostics.HostCompilationStartAnalysisScope, Microsoft.CodeAnalysis]], mscorlib]], mscorlib]][]
            ->  27644ef0 Microsoft.CodeAnalysis.Diagnostics.WorkspaceAnalyzerOptions
            ->  275a6700 Microsoft.CodeAnalysis.Solution

### PR DESCRIPTION
**Pull request by mavasani**
…ecution context

Fixes #20065

**Customer scenario**

Performance: We are leaking solution instances in preview workspace (which is created every time we invoke a lightbulb preview). See https://github.com/dotnet/roslyn/issues/20065#issue-234071975 for details.

**Bugs this fixes:**

Fixes #20065 

**Workarounds, if any**

N/A

**Risk**

Low, as we are not changing any functionality here. Instead of having a `Dictionary<AnalyzerOptions, ConditionalWeakTable<Compilation, Task<HostCompilationStartAnalysisScope>>>` with strong reference to AnalyzerOptions, we now use a `ConditionalWeakTable<Compilation, Dictionary<AnalyzerOptions, Task<HostCompilationStartAnalysisScope>>>`, which has a weak reference and will let go AnalyzerOptions instance once the compilation is GC'ed.

**Performance impact**

This should improve performance as we are preventing a leak of solutions in preview workspace.

**Is this a regression from a previous update?**

Yes, we recently refactored the WorkspaceAnalyzerOptions to strongly hold onto the solution snapshot. This was needed to fix an IDE race. This in turn is causing the map in question here to leak these solution instances.

**Root cause analysis:**

We don't have tests to catch and prevent leaks. We are going to further improve the design in this area when we tackle #2830 in 15.6, so we prevent such regressions in future.

**How was the bug found?**

Dogfooding.

### CODE REVIEW

**Comment by mavasani** [comment]
Test failure in https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/5272/ with output: ```xunit produced no error output but had exit code 1```

**Comment by mavasani** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

**Comment by mavasani** [comment]
Tagging @dotnet/roslyn-compiler @dotnet/analyzer-ioperation for review.

**Comment by mavasani** [comment]
@heejaechang Can you please buddy test this change and double check analyzer execution in OOP with FSA turned on? I can share the locally built VSIX if you need.

**Comment by heejaechang** [comment]
👍 sure, I will do the buddy testing.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs [hunk 1]
```diff
@@ -20,7 +20,7 @@ private sealed class AnalyzerExecutionContext
 
             // This map stores the tasks to compute HostCompilationStartAnalysisScope for per-compilation analyzer actions, i.e. AnalyzerActions registered by analyzer's CompilationStartActions.
             // Compilation start actions will get executed once per-each AnalyzerAndOptions as user might want to return different set of custom actions for each compilation/analyzer options.
```
Comment (jasonmalinowski) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs]: Not sure if the comment needs an update here.

**Comment by jasonmalinowski** [comment]
> Yes, we recently refactored the WorkspaceAnalyzerOptions to strongly hold onto the solution snapshot. This was needed to fix an IDE race.

I'm still not convinced this is what regressed it. Previously we were holding onto the Workspace, which would have still rooted the Solution anyways.

**Comment by mavasani** [comment]
> I'm still not convinced this is what regressed it. Previously we were holding onto the Workspace, which would have still rooted the Solution anyways.

Probably something else regressed it before that change, but nevertheless, we shouldn't be leaking anymore after this change.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs (hunk 1 above)
Comment (mavasani) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs]: I am going to delete a bunch of code around this in dev15.6 branch soon, we are going to get rid of the singleton.

**Comment by mavasani** [comment]
Tagging @MattGertz for approval

**Comment by heejaechang** [comment]
confirmed that there is no PreviewWorkspace leaked with this change.

**Comment by mavasani** [comment]
@heejaechang - Thank you very much!

**Comment by gafter** [comment]
(I'm not signing off yet because I'd like to see if this is testable, and we need another sign-off from the compiler team)

**Comment by jasonmalinowski** [comment]
We do have https://github.com/dotnet/roslyn/blob/6a98a959cbd296991411e3e9d124aeeb4827ae1f/src/Test/Utilities/Portable/ObjectReference.cs as a tool you can use for asserting that objects are no longer held. It holds our current "GC until it goes away" pattern.

**Comment by heejaechang** [comment]
@jasonmalinowski I see you meant this kind of lifetime check test. to explicitly see whether something left alive after certain operation. ya. I guess we could try to add this kind of test.

**Comment by natidea** [comment]
Director Approved to Merge

**Comment by mavasani** [comment]
@gafter @jasonmalinowski @heejaechang - Added a unit test

**Comment by mavasani** [comment]
@dotnet/roslyn-compiler Can I get another review? FYI that this fixes an Urgency-Now bug #20093 which already has director approval to merge.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs [hunk 2]
```diff
@@ -61,51 +61,32 @@ public void ClearSessionScopeTask()
...
-                    _lazyCompilationScopeMap.Add(analyzerOptions, compilationActionsCache);
-                    return compilationActionsCache;
+                    return task;
                 }
             }
 
-            public void ClearCompilationScopeMap(AnalyzerOptions analyzerOptions, Compilation compilation)
+            public void ClearCompilationScopeMap(Compilation compilation)
             {
                 lock (_gate)
```
Comment (sharwell) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs]: :bulb: This lock is now technically unnecessary (`ConditionalWeakTable` provides synchronization), but I think it would be confusing to some readers to remove it.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs [hunk 3]
```diff
@@ -20,7 +20,7 @@ private sealed class AnalyzerExecutionContext
 
             // This map stores the tasks to compute HostCompilationStartAnalysisScope for per-compilation analyzer actions, i.e. AnalyzerActions registered by analyzer's CompilationStartActions.
             // Compilation start actions will get executed once per-each AnalyzerAndOptions as user might want to return different set of custom actions for each compilation/analyzer options.
-            private Dictionary<AnalyzerOptions, ConditionalWeakTable<Compilation, Task<HostCompilationStartAnalysisScope>>> _lazyCompilationScopeMap;
+            private ConditionalWeakTable<Compilation, Dictionary<AnalyzerOptions, Task<HostCompilationStartAnalysisScope>>> _lazyCompilationScopeCache;
```
Comment (sharwell) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs]: ❓ Is there any reason why this can't be `private static readonly`? More specifically, is it possible for two different `AnalyzerExecutionContext` instances to have the same `Compilation` instance with different maps associated?

File: src/EditorFeatures/Test/Preview/PreviewWorkspaceTests.cs [hunk 4]
```diff
@@ -275,6 +276,37 @@ public void TestPreviewDiagnostic()
...
+            Assert.NotNull(previewWorkspace.CurrentSolution);
+            var project = previewWorkspace.CurrentSolution.AddProject("project", "project.dll", LanguageNames.CSharp);
+            Assert.True(previewWorkspace.TryApplyChanges(project.Solution));
+            var solutionObjectReference = ObjectReference.Create(previewWorkspace.CurrentSolution);
+
+            var analyzers = ImmutableArray.Create<DiagnosticAnalyzer>(new CommonDiagnosticAnalyzers.NotConfigurableDiagnosticAnalyzer());
+            ExecuteAnalyzers(previewWorkspace, analyzers);
+
+            previewWorkspace.Dispose();
+            solutionObjectReference.AssertReleased();
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Test/Preview/PreviewWorkspaceTests.cs]: Consider asserting that the workspace is also disposed, just to make sure that's covered.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs (hunk 3 above)
Comment (mavasani) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs]: I am going to remove this map in a refactoring in dev15.6 very soon.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs (hunk 2 above)
Comment (mavasani) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs]: Yes, leaving unchanged for now. I am going to remove a whole bunch of code in this file in dev15.6 soon.

**Comment by mavasani** [comment]
@gafter Any other feedback?

File: src/EditorFeatures/Test/Preview/PreviewWorkspaceTests.cs (hunk 4 above)
Comment (mavasani) [inline src/EditorFeatures/Test/Preview/PreviewWorkspaceTests.cs]: I am explicitly disposing the workspace in the previous line. I am not sure what your recommendation is over here?

**Comment by AlekseyTs** [comment]
Was Neal's feedback about test addressed?

**Comment by mavasani** [comment]
@AlekseyTs - yes, I have added a unit test.

**Comment by AlekseyTs** [comment]
I sign-off on Neal's behalf.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs (hunk 3 above)
Comment (jaredpar) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs]: Is there a bug tracking this we can reference here?

Comment (mavasani) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs]: I have a PR out: https://github.com/dotnet/roslyn/pull/20109
