### PR TITLE
When converting to LINQ calls, omit .Select(x => x) when possible.

### LINKED ISSUE #31784: Convert to LINQ (call form) generates extra .Select() overhead
**Version Used**: VS 2019 Preview 1

Related to #31780. An example of this in action:
image

**Steps to Reproduce**:
```#
// Boilerplate
private static readonly List<string> _items = Enumerable.Range(0, 50000).Select(i => "Num" + i).ToList();
```

1. Enter the following code:
```c#
foreach (var item in _items)
{
    if (item.Length < 3)
    {
        yield return item;
    }
}
```
2. Check suggestions and select "Convert to LINQ (call form)

**Expected Behavior**:
Generated code would be:
```c#
_items.Where(item => item.Length < 3).Consume(consumer);
```

**Actual Behavior**:
Generated code is:
```c#
_items.Where(item => item.Length < 3).Select(item => item).Consume(consumer);
```

It would seen the `.Select(...)` is part of an always-generated formula, but it could be better here. There's overhead involved in the call - so can we avoid that overhead in the generated code?

Sample benchmarks:
```c#
private static readonly List<string> _items = Enumerable.Range(0, 50000).Select(i => "Num" + i).ToList();
private readonly Consumer consumer = new Consumer();

[Benchmark(Description = "foreach")]
public void ForEach()
{
    IEnumerable<string> Inner()
    {
        foreach (var item in _items)
        {
            if (item.Length < 3)
            {
                yield return item;
            }
        }
    }
    Inner().Consume(consumer);
}

[Benchmark(Description = "LINQ (call form)")]
public void LINQCallForm()
{
    _items.Where(item => item.Length < 3).Select(item => item).Consume(consumer);
}

[Benchmark(Description = "LINQ (call form optimal)")]
public void LINQCallFormOptimal()
{
    _items.Where(item => item.Length < 3).Consume(consumer);
}
```

|                     Method |  Job | Runtime |     Mean |    Error |   StdDev | Allocated Memory/Op |
|--------------------------- |----- |-------- |---------:|---------:|---------:|--------------------:|
|                    foreach |  Clr |     Clr | 262.0 us | 3.138 us | 2.782 us |                60 B |
|         'LINQ (call form)' |  Clr |     Clr | 401.6 us | 1.783 us | 1.580 us |               156 B |
| 'LINQ (call form optimal)' |  Clr |     Clr | 363.8 us | 3.123 us | 2.769 us |                76 B |
|                    foreach | Core |    Core | 233.4 us | 1.989 us | 1.861 us |                56 B |
|         'LINQ (call form)' | Core |    Core | 543.7 us | 4.368 us | 4.086 us |               152 B |
| 'LINQ (call form optimal)' | Core |    Core | 549.4 us | 8.623 us | 7.644 us |                72 B |

Note: the performance on Core is within the margin of error and note the minimal jitter- it's always equal or faster. The allocations are always higher. [Benchmarks are in a repo here](https://github.com/NickCraver/PerfBenchmarks/blob/0b98537fd20d807ab1766a67f1417ffea47d6e4a/Benchmarks/LINQLoops.cs)

To run:
```ps
cd Benchmarks
dotnet run -c Release -f netcoreapp2.2 -- LINQLoop
```

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #31784

In cases where converting to LINQ calls would leave no LINQ calls at all,
we leave the .Select(x => x) in case the user is trying to do some different
operation.

### CODE REVIEW

**Comment by dpoeschl** [comment]
@ivanbasov Can we take a look at this together?

File: src/Features/CSharp/Portable/ConvertLinq/ConvertForEachToLinqQuery/AbstractConverter.cs [hunk 1]
```diff
@@ -183,6 +183,15 @@ private static QueryClauseSyntax CreateQueryClause(ExtendedSyntaxNode node)
...
             //   c1.SelectMany(n1 => ...
             //
+
+            // Avoid `.Select(x => x)`
+            if (lambdaBody is IdentifierNameSyntax identifier &&
+                identifier.Identifier.ValueText == forEachStatement.Identifier.ValueText &&
+                receiverForInvocation is InvocationExpressionSyntax receiverInvocationExpression)
+            {
+                return receiverInvocationExpression;
+            }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ConvertLinq/ConvertForEachToLinqQuery/AbstractConverter.cs]: shouldn't you only do this if `!hasForEachChild`?  Otherwise, this will elide `.SelectMany(x => x)` right? (can we also add a test for this)?

File: src/Features/CSharp/Portable/ConvertLinq/ConvertForEachToLinqQuery/AbstractConverter.cs [hunk 2]
```diff
@@ -183,6 +183,15 @@ private static QueryClauseSyntax CreateQueryClause(ExtendedSyntaxNode node)
...
+
             var invokedMethodName = !hasForEachChild ? nameof(Enumerable.Select) : nameof(Enumerable.SelectMany);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ConvertLinq/ConvertForEachToLinqQuery/AbstractConverter.cs]: consider moving this above, and tehn only doing your check if `invokedMethodName` is actually `Select`.

Comment (dpoeschl) [reply src/Features/CSharp/Portable/ConvertLinq/ConvertForEachToLinqQuery/AbstractConverter.cs]: Done, thanks.

File: src/Features/CSharp/Portable/ConvertLinq/ConvertForEachToLinqQuery/AbstractConverter.cs (hunk 1 above)
Comment (dpoeschl) [reply src/Features/CSharp/Portable/ConvertLinq/ConvertForEachToLinqQuery/AbstractConverter.cs]: Thanks. Done with code change (but no tests yet).

File: src/EditorFeatures/CSharpTest/CodeActions/ConvertLinq/ConvertForEachToLinqQueryTests.cs [hunk 3]
```diff
@@ -4126,11 +4126,7 @@ int M(IEnumerable<int> nums)
         /*21*/
         return /*22*/ /* 1 *//* 2 *//* 3 *//* 4 */// 5
 /*23*/
-(nums /* 12 */.Select(
```
Comment (dpoeschl) [inline src/EditorFeatures/CSharpTest/CodeActions/ConvertLinq/ConvertForEachToLinqQueryTests.cs]: I need to figure out how to keep these comments around.

File: src/Features/CSharp/Portable/ConvertLinq/ConvertForEachToLinqQuery/AbstractConverter.cs (hunk 1 above)
Comment (dpoeschl) [reply src/Features/CSharp/Portable/ConvertLinq/ConvertForEachToLinqQuery/AbstractConverter.cs]: @CyrusNajmabadi Does this look like a good enough example, or were you thinking of something else?

image

Comment (dpoeschl) [reply src/Features/CSharp/Portable/ConvertLinq/ConvertForEachToLinqQuery/AbstractConverter.cs]: Added the above as a test: QueryWhichRequiresSelectManyWithIdentityLambda

**Comment by dpoeschl** [comment]
Taking out of Draft state.
Tagging @dotnet/roslyn-ide and @ivanbasov for review. Thanks!

File: src/Features/CSharp/Portable/ConvertLinq/ConvertForEachToLinqQuery/AbstractConverter.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/ConvertLinq/ConvertForEachToLinqQuery/AbstractConverter.cs]: That's perfect :)

File: src/EditorFeatures/CSharpTest/CodeActions/ConvertLinq/ConvertForEachToLinqQueryTests.cs [hunk 4]
```diff
@@ -4,6 +4,7 @@
 using Microsoft.CodeAnalysis.CodeRefactorings;
 using Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.CodeRefactorings;
 using Microsoft.CodeAnalysis.Test.Utilities;
+using Roslyn.Test.Utilities;
 using Xunit;
 namespace Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.CodeActions.ConvertLinq
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/CodeActions/ConvertLinq/ConvertForEachToLinqQueryTests.cs]: blank line above ths.

File: src/EditorFeatures/CSharpTest/CodeActions/ConvertLinq/ConvertForEachToLinqQueryTests.cs [hunk 5]
```diff
@@ -3864,7 +3903,7 @@ class C
 {
     void M(IEnumerable<int> nums)
     {
-        int c = (nums.AsQueryable().Select(n1 => n1)).Count();
+        int c = (nums.AsQueryable()).Count();
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/CodeActions/ConvertLinq/ConvertForEachToLinqQueryTests.cs]: nit: can you file bug about removing these unnecessary parens.

Comment (dpoeschl) [reply src/EditorFeatures/CSharpTest/CodeActions/ConvertLinq/ConvertForEachToLinqQueryTests.cs]: Filed as https://github.com/dotnet/roslyn/issues/39727
