### PR TITLE
Fix block comments editing when caret on EOF

### LINKED ISSUE #16128: Extra * added on the line after a block comment ends.
```C#
/*
class C {}
*/
```
Place the cursor at the end of the comment and press Enter.

**Expected Behavior**:
A newline.

**Actual Behavior**:
A newline plus another `*`.

Originally reported at https://developercommunity.visualstudio.com/content/problem/8316/c-multiline-comment-bug-adds-a-out-of-multiline-ar.html

### PR DESCRIPTION
**Pull request by diryboy**
Fixes #16128

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @dotnet/roslyn-ide for review.

File: src/EditorFeatures/CSharp/BlockCommentEditing/BlockCommentEditingCommandHandler.cs [hunk 1]
```diff
@@ -170,7 +171,39 @@ private static bool IsCaretInsideBlockCommentSyntax(SnapshotPoint caretPosition)
...
+                // FindTriviaAndAdjustForEndOfFile always returns something if position is EOF,
+                // whether or not the result includes the position.
+                // And the SyntaxTrivia for block comments always ends on EOF, closed or not.
+                // So we need to handle
+                // /**/|EOF
+                // and
+                // /*  |EOF
+                if (caretPosition == snapshot.Length)
+                {
+                    if (span.Length < 4) // "/**/".Length
```
Comment (Pilchie) [inline src/EditorFeatures/CSharp/BlockCommentEditing/BlockCommentEditingCommandHandler.cs]: Instead of the comment, I would just put `/**/.Length`

File: src/EditorFeatures/CSharp/BlockCommentEditing/BlockCommentEditingCommandHandler.cs [hunk 2]
```diff
@@ -170,7 +171,39 @@ private static bool IsCaretInsideBlockCommentSyntax(SnapshotPoint caretPosition)
...
+                    {
+                        return true;
+                    }
+
+                    if (!trivia.ContainsDiagnostics)
+                    {
+                        return false;
+                    }
+
+                    var textBeforeCaret = snapshot.GetText((int)caretPosition - 2, 2);
```
Comment (Pilchie) [inline src/EditorFeatures/CSharp/BlockCommentEditing/BlockCommentEditingCommandHandler.cs]: Instead of the cast, I think you want `caretPosition.Position`

File: src/EditorFeatures/CSharp/BlockCommentEditing/BlockCommentEditingCommandHandler.cs [hunk 3]
```diff
@@ -170,7 +171,39 @@ private static bool IsCaretInsideBlockCommentSyntax(SnapshotPoint caretPosition)
...
+                // and
+                // /*  |EOF
+                if (caretPosition == snapshot.Length)
+                {
+                    if (span.Length < 4) // "/**/".Length
+                    {
+                        return true;
+                    }
+
+                    if (!trivia.ContainsDiagnostics)
```
Comment (Pilchie) [inline src/EditorFeatures/CSharp/BlockCommentEditing/BlockCommentEditingCommandHandler.cs]: Could you comment what this is for?

Comment (diryboy) [inline src/EditorFeatures/CSharp/BlockCommentEditing/BlockCommentEditingCommandHandler.cs]: If the block comment is not closed, the SyntaxTrivia contains diagnostics. So if SyntaxTrivia is clean, the block comment should be closed. This if statement tries again to avoid string allocations below.

**Comment by Pilchie** [comment]
Thanks @diryboy!  Can you re-target to `post-dev15` now though - we're trying to shut down on issues for 2.0 right now and I don't think this is severe enough to warrant fixing in that release.

**Comment by Pilchie** [comment]
@dotnet/roslyn-ide Can we get a second reviewer?

File: src/EditorFeatures/CSharp/BlockCommentEditing/BlockCommentEditingCommandHandler.cs [hunk 4]
```diff
@@ -170,7 +171,41 @@ private static bool IsCaretInsideBlockCommentSyntax(SnapshotPoint caretPosition)
             var trivia = syntaxTree.FindTriviaAndAdjustForEndOfFile(caretPosition, CancellationToken.None);
 
             var isBlockComment = trivia.IsKind(SyntaxKind.MultiLineCommentTrivia) || trivia.IsKind(SyntaxKind.MultiLineDocumentationCommentTrivia);
-            return isBlockComment && trivia.FullSpan.Start < caretPosition;
+            if (isBlockComment)
+            {
+                var span = trivia.FullSpan;
+                if (span.Start < caretPosition && caretPosition < span.End)
```
Comment (jasonmalinowski) [inline src/EditorFeatures/CSharp/BlockCommentEditing/BlockCommentEditingCommandHandler.cs]: What happens if we're in a `/**/` and we're between the `*/`? I'm not sure it's clear what _should_ happen, but it might be worth having a test for it.

Comment (diryboy) [inline src/EditorFeatures/CSharp/BlockCommentEditing/BlockCommentEditingCommandHandler.cs]: Did you mean a test case like `/**$$/`? See https://github.com/diryboy/roslyn/blob/021bac42a0ccdefcdd6a83d247e3ed7274f5220d/src/EditorFeatures/CSharpTest/BlockCommentEditing/BlockCommentEditingTests.cs#L397

Comment (diryboy) [inline src/EditorFeatures/CSharp/BlockCommentEditing/BlockCommentEditingCommandHandler.cs]: Congratulations, you found another bug! I tried `/**$$/` and it results `* $$/` on the new line, not expected! But the problem is not caused by this line here. And this issue is not what this PR trying to fix.

I'll look into that.

**Comment by diryboy** [comment]
@Pilchie I retargeted this PR to `post-dev15`

**Comment by Pilchie** [comment]
Thanks @diryboy!
