### PR TITLE
Fix inline rename in MAUI

### LINKED ISSUE #65397: Rename constantly failing in MAUI Apps
**Version Used**: 17.5p1 public

**Steps to Reproduce**:

1. Create a new .NET MAUI App
2. Open a CS file, insert a method named M.
3. Attempt to rename the method to M2.

**Expected Behavior**:

Method is renamed

**Actual Behavior**:

image

It does not appear to work correctly with any combination of old/new rename UI or async/sync rename.

### PR DESCRIPTION
**Pull request by ryzngard**
When applying our changes for rename we switch to a background thread to compute the text/syntax changes and apply them. Then we call TryOnBeforeGlobalSymbolRenamed to indicate we're about to rename the item. For MAUI, this causes InvisibleEditors opening/closing and causes a mutation in the workspace, which updates the `Workspace.CurrentSolution.WorkspaceVersion` making our calculated solution invalid to apply. 

The fix here is to recompute the changes on the mutated workspace if needed. Adding telemetry here to make sure we understand the impact, but the guess is that this keeps _most_ users on the non UI blocking expensive work, and _some_ users having an expensive recompute. 

Fixes #65397

### CODE REVIEW

File: src/EditorFeatures/Core/InlineRename/AbstractInlineRenameUndoManager.cs [hunk 1]
```diff
@@ -97,6 +97,12 @@ public void Disconnect()
             this.RedoStack.Clear();
             this.initialState = null;
             this.currentState = null;
+
+            if (_trackedSession is not null)
```
Comment (LycianSeattle) [inline src/EditorFeatures/Core/InlineRename/AbstractInlineRenameUndoManager.cs:101]: This fix is unrelated, just something I noticed while debugging. There were cases where we would disconnect and cause a nullref on session changing. This helps mitigate that. AFAIK we don't see many in the wild, so it could have been unique to pausing the debugger some how. Still safer code than before.

File: src/EditorFeatures/Core/InlineRename/AbstractInlineRenameUndoManager.cs [hunk 2]
```diff
@@ -97,6 +97,12 @@ public void Disconnect()
...
+            {
+                _trackedSession.ReplacementTextChanged -= InlineRenameSession_ReplacementTextChanged;
```
Comment (ryzngard) [inline src/EditorFeatures/Core/InlineRename/AbstractInlineRenameUndoManager.cs:103]: This fix is unrelated. I noticed while debugging and it makes the code safer

File: src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs [hunk 3]
```diff
@@ -897,6 +875,12 @@ private async Task CommitCoreAsync(IUIThreadOperationContext operationContext, b
             if (!_renameInfo.TryOnBeforeGlobalSymbolRenamed(_workspace, changedDocumentIDs, this.ReplacementText))
                 return (NotificationSeverity.Error, EditorFeaturesResources.Rename_operation_was_cancelled_or_is_not_valid);
 
+            if (finalSolution.WorkspaceVersion != _workspace.CurrentSolution.WorkspaceVersion)
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs:878]: Rather than just checking this, move this handling into the if (!TryApplyChanges()) path and you could then call the TryApplyChanges a second time.

Comment (ryzngard) [reply src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs:878]: if it fails for a different reason, do we want to call `TryApplyChanges` twice?

File: src/EditorFeatures/Core/InlineRename/AbstractInlineRenameUndoManager.cs (hunk 1 above)
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/InlineRename/AbstractInlineRenameUndoManager.cs:101]: This part seems a bit strange to me: I would have expected the only thing that could possibly hold this type would have been the session -- once the session has been let go, this would have fallen away too. Did you see something being held being fixed by this, or you generally noticed this wasn't being updated? Because honestly I'd actually just _delete_ this Disconnect method -- if anything leaks this type directly, we should know that up front it seems?

Comment (ryzngard) [reply src/EditorFeatures/Core/InlineRename/AbstractInlineRenameUndoManager.cs:101]: `_trackedSession` only is used to hook up to `ReplacementTextChanged`, which then checks the `currentState`. If `Disconnect` is called prior to the last `ReplacementTextChanged` event we would nullref in  `InlineRenameSession_ReplacementTextChanged`. 

I agree lifetime here is a bit weird. Can pull this out. It was just something I noticed while debugging, did hit a nullref in `InlineRenameSession_ReplacementTextChanged`, so I fixed it. If we're resetting initial and current state, we no longer care about handling `ReplacementTextChanged`. Logically that makes sense to me.

Comment (jasonmalinowski) [reply src/EditorFeatures/Core/InlineRename/AbstractInlineRenameUndoManager.cs:101]: (there is a pattern that some parts of Roslyn tried doing which was "if I'm leaked as an object, don't leak other stuff", but it's not a well-liked pattern generally)

File: src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs [hunk 4]
```diff
@@ -864,31 +864,9 @@ private async Task CommitCoreAsync(IUIThreadOperationContext operationContext, b
             var changes = _baseSolution.GetChanges(newSolution);
             var changedDocumentIDs = changes.GetProjectChanges().SelectMany(c => c.GetChangedDocuments()).ToList();
 
+            // Go to the background thread ofr initial calculation of the final solution
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs:867]:
```suggestion
            // Go to the background thread for initial calculation of the final solution
```

File: src/EditorFeatures/Core/InlineRename/AbstractInlineRenameUndoManager.cs (hunk 1 above)
Comment (jasonmalinowski) [reply src/EditorFeatures/Core/InlineRename/AbstractInlineRenameUndoManager.cs:101]: (that second comment I posted after a call, but GitHub helpfully didn't show your reply yet)

Comment (jasonmalinowski) [reply src/EditorFeatures/Core/InlineRename/AbstractInlineRenameUndoManager.cs:101]: > did hit a nullref in InlineRenameSession_ReplacementTextChanged

Is the null ref just because we're nulling everything else out there? Because that'd be a stronger argument for "just delete" if that's practical.

Comment (ryzngard) [reply src/EditorFeatures/Core/InlineRename/AbstractInlineRenameUndoManager.cs:101]: It is, and we could do that. I'm happy to do a separate change for that instead of piling into here

Comment (jasonmalinowski) [reply src/EditorFeatures/Core/InlineRename/AbstractInlineRenameUndoManager.cs:101]: @ryzngard Sure, that seem good.

File: src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs (hunk 3 above)
Comment (jasonmalinowski) [reply src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs:878]: TryApplyChanges will return false if you hit the version issue, and will throw for anything else.

Comment (CyrusNajmabadi) [reply src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs:878]: note: We special case tryApplyChanges returning false in ApplyChangesOperation (https://github.com/dotnet/roslyn/blob/main/src/Workspaces/Core/Portable/CodeActions/Operations/ApplyChangesOperation.cs#L50).  Not sure if that would be helpful here in any way.

The general idea though is that we still attempt to make the change, as long as it's just text changes to files taht themselves haven't been changed.

File: src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs [hunk 5]
```diff
@@ -898,7 +876,15 @@ private async Task CommitCoreAsync(IUIThreadOperationContext operationContext, b
...
-                return (NotificationSeverity.Error, EditorFeaturesResources.Rename_operation_could_not_complete_due_to_external_change_to_workspace);
+            {
+                // If the workspace changed in TryOnBeforeGlobalSymbolRenamed retry, this prevents rename from failing for cases
+                // where text changes to other files or workspace state change doesn't impact the text changes being applied. 
+                Logger.Log(FunctionId.Rename_TryApplyRename_WorkspaceChanged, message: null, LogLevel.Information);
+                finalSolution = CalculateFinalSolutionSynchronously(newSolution, _workspace, changedDocumentIDs, cancellationToken);
+
+                if (!_workspace.TryApplyChanges(finalSolution))
+                    return (NotificationSeverity.Error, EditorFeaturesResources.Rename_operation_could_not_complete_due_to_external_change_to_workspace);
+            }
```
Comment (sharwell) [inline src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs:887]: 💭 Can we not check `_workspace.CurrentSolution` explicitly to avoid having two calls to `TryApplyChanges`?

Comment (ryzngard) [reply src/EditorFeatures/Core/InlineRename/InlineRenameSession.cs:887]: From my understanding this is preferred, and TryApplyChanges will throw for all cases except workspace versions being different

**Review by jasonmalinowski — APPROVED** [review]
