### PR TITLE
restrict keywords that trigger <see langword> tag and don't offer tag inside XML attribute

### LINKED ISSUE #22278: 'is' keyword can be converted to "see langword" tag when it is already part of a "see langword" tag
**Version Used**: 
VSUML 26920.4001
**Steps to Reproduce**:
1.  Create a new VB console app
2. At the start of the file, above module, add summary comments. Inside them add the text: "test 1 is"
3. Select 'is' in the comment, open up quick actions and choose "`Use <see langword= "is"/>`
4. Select is from inside the resulting see tag, and open up quick actions again. As you can see you can make a second tag inside the first tag.
**Expected Behavior**:
Either 'is' shouldn't be selectable at all for this action as 'is' isn't present elsewhere in the code file, or 'is' shouldn't be selectable when it is already in the tag.
**Actual Behavior**:
You're able to make a second `<see langword="is"/>` inside the first.
image

### PR DESCRIPTION
**Pull request by chborl**
Fixes #22278 by restricting the keywords that will trigger the `<see langword=" ">`  refactoring.  Also, prevents the doc comment tags from being offered when already in an XML attribute

**Customer scenario**
When a user types a keyword in a doc comments section, they are offered a refactoring to insert a `<see langword="  ">` tag.  This fix restricts the keywords that trigger the refactoring to only the most likely candidates so it isn't triggered on more common words like `is`, `as`, `for`, etc...  It also prevents the refactoring from being offered when the cursor is already in an XML attribute.

**Bugs this fixes:**
#22278 

**Workarounds, if any**
n/a

**Risk**
low, this only affects the ReplaceDocCommentTextWithTag refactoring code

**Performance impact**
low since it reduces the scenarios in which this refactoring is offered.

**Is this a regression from a previous update?**
no

**Root cause analysis:**
initial design of this feature allowed all keywords in any part of the doc comments to trigger this refactoring.  

How did we miss it?  What tests are we adding to guard against it in the future?
Tests have been updated and added to cover the new scenarios

**How was the bug found?**
internal test team

**Test documentation updated?**
n/a

If this is a new non-compiler feature or a significant improvement to an existing feature, update https://github.com/dotnet/roslyn/wiki/Manual-Testing once you know which release it is targeting.

### CODE REVIEW

**Comment by chborl** [comment]
@dotnet/roslyn-ide

**Comment by chborl** [comment]
@dotnet/roslyn-ide, @dotnet/roslyn-analysis  please review

**Comment by chborl** [comment]
ping @dotnet/roslyn-analysis  and @dotnet/roslyn-ide  for review, thanks!

File: src/Features/CSharp/Portable/ReplaceDocCommentTextWithTag/CSharpReplaceDocCommentTextWithTagCodeRefactoringProvider.cs [hunk 1]
```diff
@@ -11,15 +12,37 @@ namespace Microsoft.CodeAnalysis.CSharp.ReplaceDocCommentTextWithTag
     internal class CSharpReplaceDocCommentTextWithTagCodeRefactoringProvider :
         AbstractReplaceDocCommentTextWithTagCodeRefactoringProvider
     {
+        private static HashSet<string> s_keywords = new HashSet<string>
```
Comment (heejaechang) [inline src/Features/CSharp/Portable/ReplaceDocCommentTextWithTag/CSharpReplaceDocCommentTextWithTagCodeRefactoringProvider.cs]: readonly and using ImmutableHashset if it doesn't get changed?

File: src/Features/CSharp/Portable/ReplaceDocCommentTextWithTag/CSharpReplaceDocCommentTextWithTagCodeRefactoringProvider.cs [hunk 2]
```diff
@@ -11,15 +12,37 @@ namespace Microsoft.CodeAnalysis.CSharp.ReplaceDocCommentTextWithTag
...
         protected override bool IsXmlTextToken(SyntaxToken token)
             => token.Kind() == SyntaxKind.XmlTextLiteralToken ||
                token.Kind() == SyntaxKind.XmlTextLiteralNewLineToken;
 
-        protected override bool IsAnyKeyword(string text)
-            => SyntaxFacts.GetKeywordKind(text) != SyntaxKind.None ||
-               SyntaxFacts.GetContextualKeywordKind(text) != SyntaxKind.None;
+        protected override bool IsInXMLAttribute(SyntaxToken token)
+        {
+            return (token.Parent.Kind() == SyntaxKind.XmlCrefAttribute
```
Comment (heejaechang) [inline src/Features/CSharp/Portable/ReplaceDocCommentTextWithTag/CSharpReplaceDocCommentTextWithTagCodeRefactoringProvider.cs]: this seems very specific list. would be better if it is done reversed way like listing kinds that should work? if statements above, isXmlText and etc seems explicitly checking allowed case.

Comment (heejaechang) [reply src/Features/CSharp/Portable/ReplaceDocCommentTextWithTag/CSharpReplaceDocCommentTextWithTagCodeRefactoringProvider.cs]: actually I might miss read, this might be only cases for token to be in xml attributes

**Comment by jinujoseph** [comment]
@chborl  can you follow-up on the this

File: src/Features/CSharp/Portable/ReplaceDocCommentTextWithTag/CSharpReplaceDocCommentTextWithTagCodeRefactoringProvider.cs (hunk 2 above)
Comment (chborl) [reply src/Features/CSharp/Portable/ReplaceDocCommentTextWithTag/CSharpReplaceDocCommentTextWithTagCodeRefactoringProvider.cs]: Correct, this is a list of the keywords that we .want to trigger on.

**Comment by chborl** [comment]
@dotnet/roslyn-ide  and @dotnet/roslyn-analysis for review.

**Comment by chborl** [comment]
ping @dotnet/roslyn-ide and @dotnet/roslyn-analysis for review.

File: src/EditorFeatures/VisualBasicTest/ReplaceDocCommentTextWithTag/ReplaceDocCommentTextWithTagTests.vb [hunk 3]
```diff
@@ -315,5 +315,39 @@ interface I
...
+class C(Of TKey)
+end class")
+        End Function
+
+        <WorkItem(22278, "https://github.com/dotnet/roslyn/issues/22278")>
+        <Fact, Trait(Traits.Feature, Traits.Features.CodeActionsReplaceDocCommentTextWithTag)>
+        Public Async Function TestInXMLAttribute() As Task
+            Await TestMissingAsync(
+"
+''' Testing keyword inside <see lang=""nu[||]ll"">
```
Comment (sharwell) [inline src/EditorFeatures/VisualBasicTest/ReplaceDocCommentTextWithTag/ReplaceDocCommentTextWithTagTests.vb]: ❕ This should use `Nothing` instead of `null`
❕ The attribute should be named `langword` instead of `lang`

File: src/EditorFeatures/VisualBasicTest/ReplaceDocCommentTextWithTag/ReplaceDocCommentTextWithTagTests.vb [hunk 4]
```diff
@@ -315,5 +315,39 @@ interface I
...
+    end sub
+end class")
+        End Function
+
+        <WorkItem(22278, "https://github.com/dotnet/roslyn/issues/22278")>
+        <Fact, Trait(Traits.Feature, Traits.Features.CodeActionsReplaceDocCommentTextWithTag)>
+        Public Async Function TestInXMLAttribute2() As Task
+            Await TestMissingAsync(
+"
+''' Testing keyword inside <see lang=""nu[||]ll""
```
Comment (sharwell) [inline src/EditorFeatures/VisualBasicTest/ReplaceDocCommentTextWithTag/ReplaceDocCommentTextWithTagTests.vb]: ❕ This should use `Nothing` instead of `null`
❕ The attribute should be named `langword` instead of `lang`

File: src/EditorFeatures/CSharpTest/ReplaceDocCommentTextWithTag/ReplaceDocCommentTextWithTagTests.cs [hunk 5]
```diff
@@ -408,5 +408,42 @@ class C
...
+}");
+        }
+
+        [WorkItem(22278, "https://github.com/dotnet/roslyn/issues/22278")]
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsReplaceDocCommentTextWithTag)]
+        public async Task TestInXMLAttribute()
+        {
+            await TestMissingAsync(
+@"
+/// Testing keyword inside <see lang=""nu[||]ll""/>
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/ReplaceDocCommentTextWithTag/ReplaceDocCommentTextWithTagTests.cs]: ❕ The attribute should be named `langword` instead of `lang`

File: src/EditorFeatures/CSharpTest/ReplaceDocCommentTextWithTag/ReplaceDocCommentTextWithTagTests.cs [hunk 6]
```diff
@@ -408,5 +408,42 @@ class C
...
+}");
+        }
+
+        [WorkItem(22278, "https://github.com/dotnet/roslyn/issues/22278")]
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsReplaceDocCommentTextWithTag)]
+        public async Task TestInXMLAttribute2()
+        {
+            await TestMissingAsync(
+@"
+/// Testing keyword inside <see lang=""nu[||]ll""
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/ReplaceDocCommentTextWithTag/ReplaceDocCommentTextWithTagTests.cs]: ❕ The attribute should be named `langword` instead of `lang`

File: src/Features/VisualBasic/Portable/ReplaceDocCommentTextWithTag/VisualBasicReplaceDocCommentTextWithTagCodeRefactoringProvider.vb [hunk 7]
```diff
@@ -9,18 +10,35 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.ReplaceDocCommentTextWithTag
     Friend Class VisualBasicReplaceDocCommentTextWithTagCodeRefactoringProvider
         Inherits AbstractReplaceDocCommentTextWithTagCodeRefactoringProvider
 
+        Private Shared s_keywords As New HashSet(Of String) From
```
Comment (sharwell) [inline src/Features/VisualBasic/Portable/ReplaceDocCommentTextWithTag/VisualBasicReplaceDocCommentTextWithTagCodeRefactoringProvider.vb]: :bulb: Can this be read only?

**Comment by chborl** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please
