### PR TITLE
Track enclosing symbol in data flow analysis, which might be a field or property.

### LINKED ISSUE #19845: ExtractMethodCodeRefactoringProvider throws on property reference in initializer
**Version Used**:  15.2 (26430.6) Release

```C#
class C {
    static int X { get; set; }
    int Y = X;
}
```

Select the second `X` and press Ctrl+Dot.

````
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.Binder.AccessingAutoPropertyFromConstructor(BoundExpression receiver,PropertySymbol propertySymbol,Symbol fromMember)
   at Microsoft.CodeAnalysis.CSharp.DataFlowPass.VisitPropertyAccess(BoundPropertyAccess node)
   at Microsoft.CodeAnalysis.CSharp.BoundPropertyAccess.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitExpressionWithoutStackGuard(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth,BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitWithStackGuard(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitAlways(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.Scan(Boolean& badRegion)
   at Microsoft.CodeAnalysis.CSharp.DataFlowPass.Scan(Boolean& badRegion)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.Analyze(Boolean& badRegion)
   at Microsoft.CodeAnalysis.CSharp.DataFlowPass.Analyze(Boolean& badRegion,DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.UnassignedVariablesWalker.Analyze(CSharpCompilation compilation,Symbol member,BoundNode node,Boolean convertInsufficientExecutionStackExceptionToCancelledByStackGuardException)
   at Microsoft.CodeAnalysis.CSharp.CSharpDataFlowAnalysis.get_UnassignedVariables()
   at Microsoft.CodeAnalysis.CSharp.CSharpDataFlowAnalysis.get_DataFlowsIn()
   at Microsoft.CodeAnalysis.CSharp.CSharpDataFlowAnalysis.get_Succeeded()
   at Microsoft.CodeAnalysis.CSharp.CSharpDataFlowAnalysis.AnalyzeReadWrite()
   at Microsoft.CodeAnalysis.CSharp.CSharpDataFlowAnalysis.get_Captured()
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GenerateVariableInfoMap(SemanticModel model,DataFlowAnalysis dataFlowAnalysisData,Dictionary`2 symbolMap)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.AnalyzeAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

### LINKED ISSUE #27969: Crash in DataFlowAnalysis
**Version Used**: 
Microsoft.CodeAnalysis v2.8.2

**Steps to Reproduce**:
Consider the next program, which runs data flow analysis on lambda expression `x => true`:
```csharp
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace RoslynDataFlowCrash
{
    class Program
    {
        static void Main()
        {
            const string source = @"
class C
{
    object P { get; } = Create(nameof(P), x => true);

    static object Create(string name, Func<string, bool> f) => throw null;
}
";

            SyntaxTree tree = CSharpSyntaxTree.ParseText(source);
            var compilation = CSharpCompilation.Create("test.dll", new[] { tree });
            var model = compilation.GetSemanticModel(tree);

            SimpleLambdaExpressionSyntax lambdaSyntax = tree.GetRoot().DescendantNodes().OfType<SimpleLambdaExpressionSyntax>().First();

            DataFlowAnalysis dataFlowAnalysis = model.AnalyzeDataFlow(lambdaSyntax.Body);

            bool succeeded = dataFlowAnalysis.Succeeded; // NullReferenceException
        }
    }
}
```

**Expected Behavior**:
No exception.

**Actual Behavior**:
`NullReferenceException`. Full stack trace:
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.CodeAnalysis.CSharp
  StackTrace:
   at Microsoft.CodeAnalysis.CSharp.Binder.AccessingAutoPropertyFromConstructor(BoundExpression receiver, PropertySymbol propertySymbol, Symbol fromMember)
   at Microsoft.CodeAnalysis.CSharp.Binder.AccessingAutoPropertyFromConstructor(BoundPropertyAccess propertyAccess, Symbol fromMember)
   at Microsoft.CodeAnalysis.CSharp.DataFlowPass.VisitPropertyAccess(BoundPropertyAccess node)
   at Microsoft.CodeAnalysis.CSharp.BoundPropertyAccess.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitExpressionWithoutStackGuard(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitWithStackGuard(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitAlways(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitNameOfOperator(BoundNameOfOperator node)
   at Microsoft.CodeAnalysis.CSharp.BoundNameOfOperator.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitExpressionWithoutStackGuard(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitWithStackGuard(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitAlways(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitArguments(ImmutableArray`1 arguments, ImmutableArray`1 refKindsOpt, MethodSymbol method)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitCall(BoundCall node)
   at Microsoft.CodeAnalysis.CSharp.DataFlowPass.VisitCall(BoundCall node)
   at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(BoundTreeVisitor visitor)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitExpressionWithoutStackGuard(BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitWithStackGuard(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.VisitAlways(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.Visit(BoundNode node)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.Scan(Boolean& badRegion)
   at Microsoft.CodeAnalysis.CSharp.DataFlowPass.Scan(Boolean& badRegion)
   at Microsoft.CodeAnalysis.CSharp.PreciseAbstractFlowPass`1.Analyze(Boolean& badRegion)
   at Microsoft.CodeAnalysis.CSharp.DataFlowPass.Analyze(Boolean& badRegion, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.UnassignedVariablesWalker.Analyze(CSharpCompilation compilation, Symbol member, BoundNode node, Boolean convertInsufficientExecutionStackExceptionToCancelledByStackGuardException)
   at Microsoft.CodeAnalysis.CSharp.CSharpDataFlowAnalysis.get_UnassignedVariables()
   at Microsoft.CodeAnalysis.CSharp.CSharpDataFlowAnalysis.get_DataFlowsIn()
   at Microsoft.CodeAnalysis.CSharp.CSharpDataFlowAnalysis.get_Succeeded()
   at RoslynDataFlowCrash.Program.Main() in E:\Bart\Source\Visual Studio 2017\RoslynDataFlowCrash\RoslynDataFlowCrash\Program.cs:line 29
```

### PR DESCRIPTION
**Pull request by gafter**
Code used to assume it was (and typed it as) a method.
Fixes #19845
Fixes #27969

@dotnet/roslyn-compiler May I please have a couple of reviews?

<details>

### Customer scenario

Code containing a reference to a property in an initializer undergoes region analysis. The compiler crashes.

### Bugs this fixes

Fixes #19845
Fixes #27969

### Workarounds, if any

None known.

### Risk

Low. This is a localized correction that widens the type of a field so that we can track the enclosing symbol when it is not a method.

### Performance impact

None expected.

### Is this a regression from a previous update?

Probably.

### How was the bug found?

Customer reported.

### Test documentation updated?

N/A

</details>

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs [hunk 1]
```diff
@@ -6152,6 +6152,83 @@ struct MyStruct
...
+        {
+            var analysisResults = CompileAndAnalyzeDataFlowExpression(@"
+using System;
+class C
+{
+    object P { get; } = Create(P, /*<bind>*/x => true/*</bind>*/);
+
+    static object Create(object name, Func<string, bool> f) => throw null;
+}
+");
```
[the remark this answers is not in the document]
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs]: Yes, it uses `P` instead of `nameof(P)`.

---
In reply to: [199827816](https://github.com/dotnet/roslyn/pull/28252#discussion_r199827816) [](ancestors = 199827816)

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 2]
```diff
@@ -114,9 +114,9 @@ internal partial class DataFlowPass : AbstractFlowPass<DataFlowPass.LocalState>
         private BitVector _alreadyReported;
 
         /// <summary>
-        /// Reflects the enclosing method or lambda at the current location (in the bound tree).
+        /// Reflects the enclosing member or lambda at the current location (in the bound tree).
         /// </summary>
-        protected MethodSymbol currentMethodOrLambda { get; private set; }
+        protected Symbol currentMember { get; private set; }
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: Is it worth it to just call this CurrentSymbol? It's not necessarily a member (possibly a lambda or local function) and now it may not even be a function. This name just seems confusing.

Also, I believe our style guidelines require protected properties to be capitalized.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 3]
```diff
@@ -283,7 +282,7 @@ protected override ImmutableArray<PendingBranch> RemoveReturns()
 
         protected virtual void ReportUnassignedOutParameter(ParameterSymbol parameter, SyntaxNode node, Location location)
         {
-            if (!_requireOutParamsAssigned && topLevelMethod == currentMethodOrLambda)
+            if (!_requireOutParamsAssigned && topLevelMethod == (object)currentMember)
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: `ReferenceEquals` seems clearer here. I thought our `(object)` pattern was only for comparing to `null`.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 4]
```diff
@@ -439,7 +438,7 @@ private static bool IsCaptured(Symbol variable, MethodSymbol containingMethodOrL
                  currentFunction != null;
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: May want to add an object cast here too.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs (hunk 2 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: We are more consistent in this area using lowercase spelling (e.g. `topLevelMethod`, `nextVariableSlot`). If we're going to make a change, I'd rather we not do it piecemeal.

---
In reply to: [199903748](https://github.com/dotnet/roslyn/pull/28252#discussion_r199903748) [](ancestors = 199903748)

**Comment by gafter** [comment]
@agocke I think the changes I've just pushed address your comments.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs (hunk 2 above)
Comment (agocke) [reply src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: Sounds good.

File: src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs [hunk 5]
```diff
@@ -6152,6 +6152,83 @@ struct MyStruct
...
+            var dataFlowAnalysisResults = analysisResults;
+            Assert.Equal("x", GetSymbolNamesJoined(dataFlowAnalysisResults.VariablesDeclared));
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs]: >Assert.Equal [](start = 12, length = 12)

Not related to this PR: consider adding a helper method in this test file to do the assert plus the `GetSymbolNamesJoined`, so that `GetSymbolNamesJoined` doesn't have to be repeated. 

It could look like: `ValidateSymbolNames("x", dataFlowAnalysisResults.VariablesDeclared)`

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 6]
```diff
@@ -1443,7 +1442,7 @@ private void EnterParameters(ImmutableArray<ParameterSymbol> parameters)
 
         protected virtual void EnterParameter(ParameterSymbol parameter)
         {
-            if (parameter.RefKind == RefKind.Out && !this.currentMethodOrLambda.IsAsync) // out parameters not allowed in async
+            if (parameter.RefKind == RefKind.Out && !(this.currentSymbol is MethodSymbol currentMethod && currentMethod.IsAsync)) // out parameters not allowed in async
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: >is [](start = 73, length = 2)

recursive pattern? ;-)

**Comment by jcouv** [comment]
@jaredpar for ask-mode approval. Thanks

**Comment by jaredpar** [comment]
approved

File: src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs (hunk 5 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs]: Filed [https://github.com/dotnet/roslyn/issues/28273](https://github.com/dotnet/roslyn/issues/28273)

---
In reply to: [199961497](https://github.com/dotnet/roslyn/pull/28252#discussion_r199961497) [](ancestors = 199961497)
