### PR TITLE
Harden flow analysis with assertions, and clean up some of its code.

### LINKED ISSUE #13943: Test for missing State.Clone operations in flow analysis
It was suggested in https://github.com/dotnet/roslyn/pull/13875#issuecomment-248064739 that

> I think it would be a great idea to modify DataFlowPass so that in debug mode there is no inline 32-bit data, and all data is allocated. That would probably have caught this issue long ago.

Quite simply, any bug in failing to clone would surface as a bug on the very first variable, and would not require a test case with 33 variables to repro. We have many, many tests with different scenarios with fewer than 33 variables. This would therefore increase our flow analysis test coverage substantially.

### LINKED ISSUE #13945: Reduce code overhead in out var changes in flow analysis
There was a significant amount of code added in flow analysis when out var was added that is unnecessary, and can be removed. For example, see https://github.com/dotnet/roslyn/pull/13935#issuecomment-248458447

In this case we have a large number of lines of code supporting what are essentially unnecessary assertions (the assertions do not support assumptions that are made by flow analysis). If these assertions are desirable, they can be placed in other phases that already loop through the locals.

As an example, this code

```cs
        public override BoundNode VisitUsingStatement(BoundUsingStatement node)
        {
            ImmutableArray<LocalSymbol> localsOpt = node.Locals;

            if (localsOpt.IsDefaultOrEmpty)
            {
                return base.VisitUsingStatement(node);
            }

            foreach (LocalSymbol local in localsOpt)
            {
                switch (local.DeclarationKind)
                {
                    case LocalDeclarationKind.RegularVariable:
                    case LocalDeclarationKind.PatternVariable:
                        DeclareVariable(local);
                        break;

                    default:
                        Debug.Assert(local.DeclarationKind == LocalDeclarationKind.UsingVariable);
                        break;
                }
            }

            var result = base.VisitUsingStatement(node);

            foreach (LocalSymbol local in localsOpt)
            {
                switch (local.DeclarationKind)
                {
                    case LocalDeclarationKind.UsingVariable:
                        NoteRead(local); // At the end of the statement, there's an implied read when the local is disposed
                        break;
                }
            }

            Debug.Assert(localsOpt.Where(l => l.DeclarationKind == LocalDeclarationKind.UsingVariable).All(_usedVariables.Contains));

            return result;
        }
```

can be replaced by this

```cs
        public override BoundNode VisitUsingStatement(BoundUsingStatement node)
        {
            var localsOpt = node.Locals;
            DeclareLocals(localOpt);
            var result = base.VisitUsingStatement(node);
            if (!localsOpt.IsDefaultOrEmpty)
            {
                foreach (LocalSymbol local in localsOpt)
                {
                    if (local.DeclarationKind == LocalDeclarationKind.UsingVariable)
                    {
                        NoteRead(local); // At the end of the statement, there's an implied read when the local is disposed
                        Debug.Assert(_usedVariables.Contains(local));
                    }
                }
            }

            return result;
        }
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #13945
Fixes #13943

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a couple of code reviews?
@VSadov This was partially motivated by your work on #13867.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 1]
```diff
@@ -2083,14 +2090,30 @@ protected override void VisitCatchBlock(BoundCatchBlock catchBlock, ref LocalSta
         {
             if (trackUnassignments)
             {
+#if REFERENCE_STATE
+                LocalState oldTryState = _tryState;
```
Comment (VSadov) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: instead of adding all these ```#if```, it would seem simpler to have a local FakeNullable class with a Value field, just to hold the try state.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 2]
```diff
@@ -1,5 +1,20 @@
 ﻿// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
 
+#if DEBUG
+// We use a struct rather than a class to represent the state for efficiency
+// for data flow analysis, with 32 bits of data inline. Merely copying the state
```
Comment (VSadov) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: need similar thing for VB. 
Where C# was missing _some_ Clone() calls when pending branches, VB was missing them entirely.

**Comment by VSadov** [comment]
LGTM, but needs a VB counterpart of the change as well.

**Comment by gafter** [comment]
@VSadov Both suggestions taken (using Optional, and implemented for VB)

**Comment by gafter** [comment]
@dotnet-bot Please retest perf_correctness_prtest

**Comment by VSadov** [comment]
LGTM

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I have a second review please?

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I have a second review please?

**Comment by gafter** [comment]
@agocke Could you please review this flow analysis change? It adds stronger correctness assertions.

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I have a second review please?

**Comment by gafter** [comment]
@agocke Could you please review this flow analysis change? It adds stronger correctness assertions.

**Comment by agocke** [comment]
LGTM
