### PR TITLE
Fix import completion for extension methods declared in conflicting types

### LINKED ISSUE #42325: Completion for unimported extension method  can't handle containing types with conflicts
image

### PR DESCRIPTION
**Pull request by genlu**
Fix #42325

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ExtensionMethodImportCompletionProviderTests.cs [hunk 1]
```diff
@@ -701,53 +702,6 @@ public void M(int x)
                  inlineDescription: "Foo");
         }
 
-        [InlineData(ReferenceType.Project)]
-        [InlineData(ReferenceType.Metadata)]
-        [Theory, Trait(Traits.Feature, Traits.Features.Completion)]
-        public async Task TestConflictingInternalExtensionMethods_NoIVT_InReference(ReferenceType refType)
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ExtensionMethodImportCompletionProviderTests.cs]: don't remove tests.  just update to expected behavir.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs [hunk 2]
```diff
@@ -121,142 +116,162 @@ async Task<(ImmutableArray<SerializableImportCompletionItem>, StatisticCounter)>
...
+            if (!indices.HasResult)
+            {
+                return ImmutableArray<SerializableImportCompletionItem>.Empty;
+            }
 
-            using var syntaxDisposer = ArrayBuilder<CacheEntry>.GetInstance(out var syntaxBuilder);
-            using var symbolDisposer = ArrayBuilder<SymbolTreeInfo>.GetInstance(out var symbolBuilder);
+            var currentProject = document.Project;
+            var semanticModel = await document.GetRequiredSemanticModelAsync(cancellationToken).ConfigureAwait(false);
+            var currentCompilation = await currentProject.GetRequiredCompilationAsync(cancellationToken).ConfigureAwait(false);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: `var currentCompilation = semanticModel.Compilation;`

**Comment by CyrusNajmabadi** [comment]
Ok.  it's a big change . can you give info on what the main thrust of hte issue is and what your fix is?

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ExtensionMethodImportCompletionProviderTests.cs (hunk 1 above)
Comment (genlu) [reply src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ExtensionMethodImportCompletionProviderTests.cs]: Didn't remove this. Just moved it to the bottom and made some changes

**Comment by genlu** [comment]
> can you give info on what the main thrust of hte issue is and what your fix is

The issue is `Compilation.GetTypeByMetadataName` would returns null when there's conflict for types declared in references (corresponding to error CS0433), whereas for conflict between types declared in current compilation and from reference, it will return the one in current compilation w/o any hints about this conflict (i.e. the warning CS0436). Since we were using `Compilation.GetTypeByMetadataName` to find container types, we would miss those from references if they conflict with in-compilation one. 

The fix is to switch to `Assembly.GetTypeByMetadataName` to find symbols from individual compilation/PE

**Comment by CyrusNajmabadi** [comment]
> The fix is to switch to Assembly.GetTypeByMetadataName to find symbols from individual compilation/PE

Gotcha.  The fix seems quite large if that's the case.  What's the core reason for the size change?  Thanks!

**Comment by genlu** [comment]
The actual logic doesn't change much, but I had to rearrange the code a bit to accommodate the GetTypeByMetadataName change.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs [hunk 3]
```diff
@@ -121,142 +116,162 @@ async Task<(ImmutableArray<SerializableImportCompletionItem>, StatisticCounter)>
...
+                var assembly = compilation.Assembly;
 
-                if (cacheEntry == null)
-                {
-                    // Don't provide anything if we don't have all the required SyntaxTreeIndex created.
-                    return GetIndicesResult.NoneResult;
-                }
+                var internalsVisible = currentAssembly.IsSameAssemblyOrHasFriendAccessTo(assembly);
+                CheckDefaultAccessibility(compilation, internalsVisible, out var ignoreUnspecifiedContainerAccessibility, out var ignoreUnspecifiedMethodAccessibility);
+                var matchingMethodSymbols = GetPotentialMatchingSymbolsFromAssembly(compilation.Assembly, filter, namespaceFilter, !internalsVisible, ignoreUnspecifiedContainerAccessibility, ignoreUnspecifiedMethodAccessibility, counter, cancellationToken);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: please wrap crazy lines :)

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs [hunk 4]
```diff
@@ -121,142 +116,162 @@ async Task<(ImmutableArray<SerializableImportCompletionItem>, StatisticCounter)>
...
-                }
-
-                if (info.ContainsExtensionMethod)
+                var filter = CreateAggregatedFilter(targetTypeNames, symbolInfo);
+                if (currentCompilation.GetAssemblyOrModuleSymbol(peReference) is IAssemblySymbol assembly)
                 {
-                    symbolBuilder.Add(info);
+                    var internalsVisible = currentAssembly.IsSameAssemblyOrHasFriendAccessTo(assembly);
+                    var matchingMethodSymbols = GetPotentialMatchingSymbolsFromAssembly(assembly, filter, namespaceFilter, !internalsVisible, ignoreUnspecifiedContainerAccessibility: true, ignoreUnspecifiedMethodAccessibility: true, counter, cancellationToken);
+                    GetExtensionMethodItemsWorker(position, semanticModel, receiverTypeSymbol, matchingMethodSymbols, isSymbolFromCurrentCompilation: false, builder, namespaceNameCache);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: wrap.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs [hunk 5]
```diff
@@ -121,142 +116,162 @@ async Task<(ImmutableArray<SerializableImportCompletionItem>, StatisticCounter)>
...
 
-            var syntaxIndices = syntaxBuilder.ToImmutable();
-            var symbolInfos = symbolBuilder.ToImmutable();
-
-            return new GetIndicesResult(hasResult: true, syntaxIndices, symbolInfos);
+            return builder.ToImmutable();
         }
 
-        private static MultiDictionary<string, string> CreateAggregatedFilter(ImmutableArray<string> targetTypeNames, ImmutableArray<CacheEntry> syntaxIndices, ImmutableArray<SymbolTreeInfo> symbolInfos)
+        private static void CheckDefaultAccessibility(Compilation compilation, bool internalsVisible, out bool ignoreUnspecifiedContainerAccessibility, out bool ignoreUnspecifiedMethodAccessibility)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: doc why we need this.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs [hunk 6]
```diff
@@ -121,142 +116,162 @@ async Task<(ImmutableArray<SerializableImportCompletionItem>, StatisticCounter)>
...
-            foreach (var index in syntaxIndices)
+        private static void GetExtensionMethodItemsWorker(
+            int position,
+            SemanticModel semanticModel,
+            ITypeSymbol receiverTypeSymbol,
+            ImmutableArray<IMethodSymbol> matchingMethodSymbols,
+            bool isSymbolFromCurrentCompilation,
+            ArrayBuilder<SerializableImportCompletionItem> builder,
+            Dictionary<INamespaceSymbol, string> stringCache)
+        {
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: can you doc the bodies of this

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs [hunk 7]
```diff
@@ -121,142 +116,162 @@ async Task<(ImmutableArray<SerializableImportCompletionItem>, StatisticCounter)>
...
 
-                // By default, don't trigger index creation except for documents in current project.
-                var loadOnly = !forceIndexCreation && projectId != currentProject.Id;
-                var cacheEntry = await GetCacheEntryAsync(project, loadOnly, cacheService, cancellationToken).ConfigureAwait(false);
+            // Get extension method items from source
+            foreach (var (project, syntaxIndex) in indices.SyntaxIndices!)
+            {
+                var filter = CreateAggregatedFilter(targetTypeNames, syntaxIndex);
+                var compilation = await project.GetRequiredCompilationAsync(cancellationToken).ConfigureAwait(false);
+                var assembly = compilation.Assembly;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: so this can be expensive.  i forget how this feature works.  is it gated on time?

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs [hunk 8]
```diff
@@ -121,142 +116,162 @@ async Task<(ImmutableArray<SerializableImportCompletionItem>, StatisticCounter)>
...
+                // In C#, default accessibility for type is internal and for method is private.
+                case LanguageNames.CSharp:
+                    ignoreUnspecifiedContainerAccessibility = !internalsVisible;
+                    ignoreUnspecifiedMethodAccessibility = true;
+                    break;
+
+                // In VB, extension methods are declared in modules and default to public
+                case LanguageNames.VisualBasic:
+                    ignoreUnspecifiedContainerAccessibility = false;
+                    ignoreUnspecifiedMethodAccessibility = false;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: i'm a bit confused by this.  do you not have symbols you can ask teh real accessibility for?

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs [hunk 9]
```diff
@@ -121,142 +116,162 @@ async Task<(ImmutableArray<SerializableImportCompletionItem>, StatisticCounter)>
...
+                        reducedMethodSymbol.Arity,
+                        reducedMethodSymbol.GetGlyph(),
+                        GetFullyQualifiedNamespaceName(reducedMethodSymbol.ContainingNamespace, stringCache)));
                 }
             }
+        }
 
-            // Find matching extension methods from metadata
-            foreach (var info in symbolInfos)
+        private static string GetFullyQualifiedNamespaceName(INamespaceSymbol symbol, Dictionary<INamespaceSymbol, string> stringCache)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: are there any threading concerns here?  i.e. is ther eany concurrency here?

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs [hunk 10]
```diff
@@ -265,197 +280,168 @@ async Task<(ImmutableArray<SerializableImportCompletionItem>, StatisticCounter)>
...
-                // Alternatively, we can try to get symbols out of each assembly, instead of the compilation (which includes all references), 
-                // to avoid such conflict. We should give this approach a try and see if any perf improvement can be achieved.
-                var containerSymbol = compilation.GetTypeByMetadataName(fullyQualifiedContainerName);
-
-                if (containerSymbol != null)
+                var containerSymbol = assembly.GetTypeByMetadataName(fullyQualifiedContainerName);
+
+                if (containerSymbol == null
+                    || !containerSymbol.MightContainExtensionMethods
+                    || ShouldIgnoreSymbol(containerSymbol, ignoreInternal, ignoreUnspecifiedContainerAccessibility))
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: can we push .MightContainExtensions into ShouldIgnore?

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: oh, you use it for the extensions as well

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs [hunk 11]
```diff
@@ -265,197 +280,168 @@ async Task<(ImmutableArray<SerializableImportCompletionItem>, StatisticCounter)>
...
+
+            // A syntax based check for accessibility, a semantic based check is still required later.
+            // Since we are dealing with extension methods and their container (top level static class and modules),
+            // only public, internal and private modifiers are in play here.
+            static bool ShouldIgnoreSymbol(ISymbol symbol, bool ignoreInternal, bool ignoreUnspecifiedAccessibility)
+                => symbol.DeclaredAccessibility switch
+                {
+                    Accessibility.Public => false,
+                    Accessibility.Internal => ignoreInternal,
+                    Accessibility.NotApplicable => ignoreUnspecifiedAccessibility,
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: i don't understand when the NotApplicable bit would happen.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs [hunk 12]
```diff
@@ -265,197 +280,168 @@ async Task<(ImmutableArray<SerializableImportCompletionItem>, StatisticCounter)>
...
-                !IsSymbolAccessible(containerSymbol, position, semanticModel))
-            {
-                return;
-            }
+            var syntaxIndices = new Dictionary<Project, CacheEntry>();
+            var symbolInfos = new Dictionary<PortableExecutableReference, SymbolTreeInfo>();
 
-            foreach (var methodName in methodNames)
+            foreach (var projectId in relevantProjectIds)
             {
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: add cancellation check inside these expensive loops.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs [hunk 13]
```diff
@@ -265,197 +280,168 @@ async Task<(ImmutableArray<SerializableImportCompletionItem>, StatisticCounter)>
...
-            StatisticCounter counter)
-        {
-            Debug.Assert(!conflictTypeNodes.NamespaceAndMethodNames.HasValue);
+                syntaxIndices.Add(project, cacheEntry.Value);
+            }
 
-            foreach (var child in conflictTypeNodes.Children.Values)
+            // Search through all direct PE references.
+            foreach (var peReference in currentProject.MetadataReferences.OfType<PortableExecutableReference>())
             {
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: add cancellation check.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs [hunk 14]
```diff
@@ -265,197 +280,168 @@ async Task<(ImmutableArray<SerializableImportCompletionItem>, StatisticCounter)>
...
+
+                if (info == null)
                 {
-                    var childNamespace = containingNamespaceSymbol.GetMembers(child.Name).OfType<INamespaceSymbol>().FirstOrDefault();
-                    if (childNamespace != null)
-                    {
-                        GetItemsFromConflictingTypes(childNamespace, child, builder, receiverTypeSymbol, semanticModel, position, counter);
-                    }
+                    // Don't provide anything if we don't have all the required SymbolTreeInfo created.
+                    return GetIndicesResult.NoneResult;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: this seems really sucky.  so i'm unable to add extensions for things i *do* know about, jsut because we don't know everything?  i would really change this all to be best effort.  return what you do have.

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ExtensionMethodImportCompletionProviderTests.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ExtensionMethodImportCompletionProviderTests.cs]: ah ok.  in the future, don't move tests if possible :)

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs (hunk 8 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: Yes, but symbol only have declared accessibility, this is meant for a quick filter when they don't have explicit accessibility modifier.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs (hunk 9 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: Right now it's single threaded, although we might want to try making it parallel for potential perf gains.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs (hunk 11 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: When they are declared w/o explicit accessibility modifier.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs (hunk 7 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: No, it will run to the end as long as we have the index available.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs (hunk 14 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: I think this is OK, since the expander button is still available when we hit this path (as unselected). And when user explicitly click the expander, we will force the index creation and wait for it to finish.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs (hunk 7 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: Also I'm thinking maybe more caching can be done to improve perf, e.g. cache SymbolIds once we've got the symbols from assemblies

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs (hunk 14 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: @CyrusNajmabadi ?

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: still dont' like it.  seems unnecessary and is code that only exists to degrade the user experience.  i still don't have a good idea of why we don't just skip this index and move onto the next one...

Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: I don't agree. I think returning a different collection of unimported extension methods for a given object based on the availability of indices is more of an UX degrade, i.e. it makes the behavior unpredictable in the sense that you never know for sure if all the ext methods are returned (well, supported one at least, since we don't show all of them, e.g. internals from PE references). Say if someone hit this case and couldn't find an existing ext method they are looking for, they might think it doesn't exist. Expecting them to try to trigger the completion again as a way to correct the issue in my opinion would be a leak of implementation detail, or worse, it gives users the impression this might be a bug.

In contrast, not providing unimported extension methods if we don't have all the info, and show expander icon as unselected, has the advantage of clarity. Most of the time when someone hit this, they are likely not even looking for ext methods so this would be ignored, whereas when it happens when they do, they would know for sure that unimported ext method is not included in the list, and can be added by clicking expander.

And I'd like to emphasis this again, this only happens when the indices of references are not fully constructed, which shouldn't be very common scenario (usually created by solution crawler, but using expander, as well as other index back features would force the construction)

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs (hunk 7 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: @CyrusNajmabadi  Do you know how compilation cache works (if there's one)? In what case a built final compilation is kicked off the cache?

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: Tagging @jasonmalinowski

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs [hunk 15]
```diff
@@ -265,197 +265,163 @@ async Task<(ImmutableArray<SerializableImportCompletionItem>, StatisticCounter)>
...
-
             return builder.ToImmutable();
+
+            // An quick accessibility check based on declared accessibility only, a semantic based check is still required later.
+            // Since we are dealing with extension methods and their container (top level static class and modules), only public,
+            // internal and private modifiers are in play here. 
+            // Also, this check is called for a method symbol only when the container was checked and is accessible.
+            static bool IsAccessible(ISymbol symbol, bool internalsVisible) =>
+                symbol.DeclaredAccessibility == Accessibility.Public ||
+                symbol.DeclaredAccessibility == Accessibility.Internal && internalsVisible;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]:
```suggestion
                (symbol.DeclaredAccessibility == Accessibility.Internal && internalsVisible);
```

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs (hunk 14 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: Synced offline. Seems we have regressed completion's "partial semantic" behavior with async completion, which would return incomplete result if solution isn't fully loaded. IN that case, it makes sense to make import completion stick to this behavior.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs (hunk 11 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: I was wrong, fixed

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs (hunk 8 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs]: I was wrong, fixed

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs [hunk 16]
```diff
@@ -121,142 +116,147 @@ async Task<(ImmutableArray<SerializableImportCompletionItem>, StatisticCounter)>
...
-                    solution, peReference, loadOnly: !forceIndexCreation, cancellationToken).ConfigureAwait(false);
-
-                if (info == null)
+                var filter = CreateAggregatedFilter(targetTypeNames, symbolInfo);
+                if (currentCompilation.GetAssemblyOrModuleSymbol(peReference) is IAssemblySymbol assembly)
                 {
-                    // Don't provide anything if we don't have all the required SymbolTreeInfo created.
-                    return GetIndicesResult.NoneResult;
-                }
+                    var internalsVisible = currentAssembly.IsSameAssemblyOrHasFriendAccessTo(assembly);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs:176]: nit: but `IsSameAssembly` couldn't be true here right?  becuase that would mean the compilation had a reference to itself?

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs (hunk 7 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs:158]: in the future we should optimize this to search the current project first.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs (hunk 16 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs:176]: n/m.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs (hunk 14 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs:357]: i disagree still :)

note: this isn't a hypothetical.  async completion returns everything int he normal symbol system.  but throws out the import completoin stuff.  i hit this routinely and i hate it :)

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs [hunk 17]
```diff
@@ -265,197 +265,163 @@ async Task<(ImmutableArray<SerializableImportCompletionItem>, StatisticCounter)>
...
-                    foreach (var type in types)
-                    {
-                        var (namespaceName, methodNames) = child.NamespaceAndMethodNames.Value;
-                        GetItemsFromTypeContainsPotentialMatches(type, namespaceName, methodNames, receiverTypeSymbol, semanticModel, position, counter, builder);
-                    }
+                    symbolInfos.Add(peReference, info);
                 }
             }
+
+            return new GetIndicesResult(syntaxIndices, symbolInfos);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs:366]: nit for the future.  the names syntaxIndicies and symbolInfos was very confusing when seeing it confused up above.  You might want something more like ProjectSourceInfo and MetadataInfo to make it clearer what each represented.

Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/ExtensionMethodImportCompletionHelper.cs:366]: will fix in the follow up PR
