### PR TITLE
Fix import completion in LSP workspace

### LINKED ISSUE #68791: Completion for global using static attempts to insert a regular using
**Version Used**: VSCode 1.80.0-insider, C# extension v2.0.246-gc81fc4a054

**Steps to Reproduce**:

1. Go to the top of a C# file.
2. Type `global using static List`
3. Hit enter to accept the suggestion for `List<T>` from `System.Collections.Generic`

**Expected Behavior**:

`global using static System.Collections.Generic.List` is inserted.

**Actual Behavior**:

image

### PR DESCRIPTION
**Pull request by genlu**
1. Provide unimported extension methods
2. Fully qualify unimported type in using statement

Fix #68791 and #69576

### CODE REVIEW

File: src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionFeaturesTests.cs [hunk 1]
```diff
@@ -164,6 +169,88 @@ void M()
...
+}";
+        await using var testLspServer = await CreateTestLspServerAsync(markup, mutatingLspWorkspace, DefaultClientCapabilities);
+        var completionParams = CreateCompletionParams(
+            testLspServer.GetLocations("caret").Single(),
+            invokeKind: LSP.VSInternalCompletionInvokeKind.Explicit,
+            triggerCharacter: "\0",
+            triggerKind: LSP.CompletionTriggerKind.Invoked);
+
+        // Make sure the import completion option is on.
+        testLspServer.TestWorkspace.GlobalOptions.SetGlobalOption(CompletionOptionsStorage.ShowItemsFromUnimportedNamespaces, LanguageNames.CSharp, true);
```
Comment (dibarbet) [inline src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionFeaturesTests.cs:204]: do we need to ensure these options are also turned on in vscode?  Or is it covered by 
image

**Review by dibarbet — APPROVED** [review]

File: src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionFeaturesTests.cs (hunk 1 above)
Comment (genlu) [reply src/Features/LanguageServer/ProtocolUnitTests/Completion/CompletionFeaturesTests.cs:204]: Yea, they are the same https://github.com/dotnet/vscode-csharp/blob/b5f8db1c1b890a7d6c6412e27216ac8e9752f4fe/package.json#L1210
