### PR TITLE
Fix to unused value assignment analyzer for #31583

### LINKED ISSUE #31583: move redundant assignment below add using
image

we probably want to keep "add using" as top suggested code fix at least when no third party fixers are installed.

### PR DESCRIPTION
**Pull request by mavasani**
1. Do not offer remove unused local assignment for locals with error type
2. Make sure that this code fix is ordered after Add usings code fix, in case there are more similar unknown cases, by adding the ExtensionOrder attribute

Fixes #31583

### CODE REVIEW

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs [hunk 1]
```diff
@@ -366,7 +366,8 @@ private void AnalyzeOperationBlockEnd(OperationBlockAnalysisContext context)
                         out ImmutableDictionary<string, string> properties)
                     {
                         properties = null;
-                        if (_options.UnusedValueAssignmentSeverity == ReportDiagnostic.Suppress)
+                        if (_options.UnusedValueAssignmentSeverity == ReportDiagnostic.Suppress ||
+                            symbol.GetSymbolType().IsErrorType())
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs]: should we maybe also fail if the symbol type is null?

Comment (mavasani) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs]: Hmm, I am nit sure that is possible for locals/parameters.

File: src/Features/CSharp/Portable/RemoveUnusedParametersAndValues/CSharpRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs [hunk 2]
```diff
@@ -11,6 +12,7 @@
 namespace Microsoft.CodeAnalysis.CSharp.RemoveUnusedParametersAndValues
 {
     [DiagnosticAnalyzer(LanguageNames.CSharp)]
+    [ExtensionOrder(After = PredefinedCodeFixProviderNames.AddImport)]
     internal class CSharpRemoveUnusedParametersAndValuesDiagnosticAnalyzer : AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer
```
Comment (heejaechang) [inline src/Features/CSharp/Portable/RemoveUnusedParametersAndValues/CSharpRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs]: is this actually honored? we have this complex ordering logic
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures.Wpf/Suggestions/SuggestedActionsSource.cs,376

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs]: Yeah, i'm not sure either...  at one point i tried to convince myself of these sorts of invariants, but ended up finding that it looked like in some (extremely esoteric mind you) cases, you might end up with null.  I sent out mails if that would be considered buggy behavior or not, but i don't remember the resolution.

I'm ok keeping the code as is mind you.  It was just a thought :)

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs]: > so, I don't see any issue it marking local name as unused.

I would prefer we not mark things when there are obvious errors in the code. 

The intuition here is that clearly the code isn't complete, so overly aggressively telling users to remove things is more annoyance than value.  This is why, for example, i believe we shouldn't offer this feature with syntactic errors as well (and i think that's how the feature works).

Another way to think about is this:  the compiler learned over tiem that overly aggressively giving people errors (or cascading errors) isn't a great experience.  So once an initial error is reported on something, they attempt to suppress (with varying levels of success) further errors.  Depending on the type of change we're offering, we often want to do the same.  

Note that this is dependent on the type of change being offered.  If we are helping them generate/fix code, then we really want to be resilient to errors.  However, if we are removing/destroying code, we want to be conservative and wait until we have higher confidence we know what's going on.

File: src/Features/CSharp/Portable/RemoveUnusedParametersAndValues/CSharpRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs (hunk 2 above)
Comment (mavasani) [reply src/Features/CSharp/Portable/RemoveUnusedParametersAndValues/CSharpRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs]: Thanks, and I will also test it manually to confirm.

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs (hunk 1 above)
Comment (heejaechang) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs]: if we truly believe that, we should show this kind of diagnostics when we know that users are done with changing code, we should make this build only diagnostics like unused field. otherwise, it is just random point we decide based on our implementation.

even after adding using, it still shows local as unused which I will use soon since I am not done yet.. which someone can say it is noise.

anyway, it wasn't a distraction for me either way. so doesn't matter for me, but if we truly care about people who get distracted easily, sounds like there should be an option to make it build only errors.

**Comment by mavasani** [comment]
Integration test failure is known - VerifyNavBar.
