### PR TITLE
Insert documentation comments in the face of trim_whitespace

### LINKED ISSUE #18713: XML Doc Comment handles Enter incorrectly when there is whitespace before caret
**Version Used**: 15.1.26405.1

**Steps to Reproduce**:

```Csharp
/// <summary>
/// 
/// </summary>
class C
{

}
```
1. Place cursor on middle line of doc comment. (Ensure that there is space before cursor)
2. Press enter

**Expected Behavior**:
```CSharp
/// <summary>
///
/// 
/// </summary>
class C
{

}
```

**Actual Behavior**:

```CSharp
/// <summary>
///

/// </summary>
class C
{

}
```

image

### PR DESCRIPTION
**Pull request by rchande**
If the .editorconfig option "trim trailing whitespace" is enabled, the editor removes trailing whitespace from a line when the user presses enter. The automatic documentation comment feature used to do span math that assumed the whitespace was left in place in order to determine whether to insert ///. Now, the feature performs its initial checks on the SourceText prior to the handling of the enter command.

Fixes #18713

### CODE REVIEW

File: src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs [hunk 1]
```diff
@@ -209,8 +209,8 @@ private void AddLineBreaks(SourceText text, IList<string> lines)
         }
 
         private bool InsertOnEnterTyped(
-            SyntaxTree syntaxTree,
```
Comment (sharwell) [inline src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs]: :question: Why not pass `originalDocument` as the first argument, but keeping `syntaxTree` and `text` as they are now? It seems that would allow the continued use of `CompleteComment`.

File: src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs [hunk 2]
```diff
@@ -324,64 +326,101 @@ private void AddLineBreaks(SourceText text, IList<string> lines)
         }
 
         private bool TryGenerateExteriorTriviaAfterEnter(
-            SyntaxTree syntaxTree,
-            SourceText text,
-            int position,
+            Document newDocument,
```
Comment (sharwell) [inline src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs]: :memo: I'm not a fan of the reordering of `newDocument` and `originalDocument` here compared to `InsertOnEnterTyped`. They should each use the same order.

File: src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs [hunk 3]
```diff
@@ -324,64 +326,101 @@ private void AddLineBreaks(SourceText text, IList<string> lines)
...
+            int newPosition,
             int originalPosition,
             ITextBuffer subjectBuffer,
             ITextView textView,
             DocumentOptionSet options,
             CancellationToken cancellationToken)
         {
-            // Find the documentation comment before the new line that was just pressed
-            var token = GetTokenToRight(syntaxTree, originalPosition, cancellationToken);
-            if (!IsDocCommentNewLine(token) || token.SpanStart != originalPosition)
```
Comment (sharwell) [inline src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs]: :question: Would the following change allow us to continue using just the new text here?

```csharp
var token = GetTokenToLeft(syntaxTree, newPosition, cancellationToken);
if (!IsDocCommentNewLine(token) || token.SpanStop != newPosition))
```

**Comment by Pilchie** [comment]
@rchande can you retarget this to `dev15.3.x` until we figure out if this meets the bar for that or not?

File: src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs (hunk 2 above)
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs]: 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍

File: src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs (hunk 1 above)
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs]: I would be ok with @sharwell's suggestion.  But then i would want syntaxTree and text to be renamed to make it clear they are not related to "originalDocument".

File: src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs [hunk 4]
```diff
@@ -324,64 +326,101 @@ private void AddLineBreaks(SourceText text, IList<string> lines)
...
+        }
 
+        private bool ValidateCurrentText(SourceText text, TextLine currentLine, TextLine previousLine)
+        {
             // if previous line has only exterior trivia, current line is empty and next line doesn't begin
             // with exterior trivia then stop inserting auto generated xml doc string
-            if (previousLineText.Equals(ExteriorTriviaText) &&
-                string.IsNullOrWhiteSpace(currentLine.ToString()) &&
-                !nextLineStartsWithDocComment)
+            var nextLineStartsWithDocComment = NextLineStartsWithDocComment(text, currentLine);
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs]: inline this.  bonus, only gets computed when necessary.

**Comment by dpoeschl** [comment]
Lots of these failures are known and will be fixed by https://github.com/dotnet/roslyn/pull/21069

File: src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs [hunk 5]
```diff
@@ -324,64 +326,101 @@ private void AddLineBreaks(SourceText text, IList<string> lines)
...
+                   EndsWithSingleExteriorTrivia(documentationComment))
+                {
+                    return false;
+                }
+            }
 
             return true;
         }
 
+        private bool NextLineStartsWithDocComment(SourceText text, TextLine currentLine) =>
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs]: => on next line.  fix indentation.

**Comment by CyrusNajmabadi** [comment]
> If the .editorconfig option "trim trailing whitespace" is enabled, the editor removes trailing whitespace from a line when the user presses enter. The automatic documentation comment feature used to do span math that assumed the whitespace was left in place in order to determine whether to insert ///

So if you just have ```///``` (without a space) and you hit ```<enter>```, the feature didn't work?

**Comment by CyrusNajmabadi** [comment]
> The automatic documentation comment feature used to do span math that assumed the whitespace was left in place in order to determine whether to insert ///

This change seems surprisingly complicated versus what it is trying to handle.

**Comment by CyrusNajmabadi** [comment]
Presumably the bug is in TryGenerateDocumentationCommentAfterEnter.  Can you point to which line it is that is doing this bad span math?

File: src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs (hunk 3 above)
Comment (sharwell) [inline src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs]: @rchande I verified that this change alone (slightly modified to correct typos) did fix the issue revealed by your unit test. Here's the code I actually ran in the end:

```csharp
var token = GetTokenToLeft(syntaxTree, position, cancellationToken);
if (!IsDocCommentNewLine(token) || token.Span.End != position)
```

**Comment by dpoeschl** [comment]
retest this please

File: src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs (hunk 3 above)
Comment (rchande) [inline src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs]: Hm, thought I found issues with this approach last week but I'm not seeing them any more today. Will switch to this.

**Comment by rchande** [comment]
**Customer scenario:** Customer adds a .editorconfig file with the option "trim_trailing_whitespace" on. When this option is turned on, automatic insertion of `///` in documentation comments does not work.
**Bugs this fixes:** https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20IDE/_workitems/edit/468638
**Workarounds, if any:** None
**Risk:** Moderate
**Performance impact:** None, we simply change which token we look for when the user presses enter.
**Is this a regression from a previous update?** Yes. 
**Root cause analysis:** When the trim_trailing_whitespace option is on, the editor removes trailing whitespace from the line above where the caret ends. The feature used perform range checks and look for tokens assuming that nothing before the caret position had changed. Now that that assumption no longer holds, we simply have to look for the token to the left in order to determine whether the user typed enter inside a documentation comment.
**How was the bug found?** Internal feedback

**Comment by sharwell** [comment]
@rchande @CyrusNajmabadi There appears to be a bug in the way `FindTokenOnLeftOfPosition` handles trivia. When a documentation comment appears in the *trailing* trivia of a token, it is possible for this method to return a token further to the left than requested. I created sharwell/roslyn@9daf4dcbc21591609cbcef5b2e73ede2aba2a31c to correct the behavior of the method and return the expected token. The other part to fixing my original proposal was allowing for whitespace trivia (specifically indentation) to appear between the token and the caret position. I fixed the handling for this case in sharwell/roslyn@e5928f3ab2404aeb33ce199154746640ad2ba4f2. Together, these two commits appear to fix the original bug with less "magic" placed in the documentation comment handler (i.e. more responsibility is placed on finding the *correct* token to the left). Let me know what you think.

File: src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs [hunk 6]
```diff
@@ -334,10 +334,18 @@ private void AddLineBreaks(SourceText text, IList<string> lines)
...
-            var token = GetTokenToRight(syntaxTree, originalPosition, cancellationToken);
-            if (!IsDocCommentNewLine(token) || token.SpanStart != originalPosition)
+            var token = GetTokenToLeft(syntaxTree, position, cancellationToken);
+            if (!IsDocCommentNewLine(token))
             {
-                return false;
+                // See PressingEnter_InsertSlashes11 for an example of
+                // a case where multiple skipped tokens trivia appear at the same position.
+                // In that case, we need to ask for the token from the next position over.
+                token = GetTokenToLeft(syntaxTree, position + 1, cancellationToken);
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs]: i think you would only want to do this if the token you got back had ceratin characteristics (like it has trailing skipped tokens).

File: src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs [hunk 7]
```diff
@@ -334,10 +334,18 @@ private void AddLineBreaks(SourceText text, IList<string> lines)
...
+
+                if (!IsDocCommentNewLine(token))
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs]: i think you'd want to validate this token against the *original* position (not position + 1) to ensure it's appropriate to look at.

**Comment by CyrusNajmabadi** [comment]
My general concern with discussing this was ravi was the risk of changing a low level syntax navigation primitive (we believe there may be a bug in FindToken itself).  As such, we wanted (for 15.3.x) to have a low risk fix where any specialized logic was handled at the feature level itself.  We could then revisit the best fix for 15.4+.

**Comment by CyrusNajmabadi** [comment]
As it looks like you're not changing anything low level (you're touching Workspaces, not CodeAnalysis) i think it would be ok to take your change.  but i think i would prefer to take it for master, not for 15.3.x.

**Comment by sharwell** [comment]
@dotnet-bot rebuild windows_release_unit64_prtest please

**Comment by sharwell** [comment]
@rchande I'm going to merge this into 15.6 tomorrow unless you have an objection per the last comments from @CyrusNajmabadi.
