### PR TITLE
Avoid unnecessary defensive copy for constrained calls on readonly struct receivers

### LINKED ISSUE #66365: Consider optimizing constrained calls to base methods on readonly struct in some cases
Follow-up issue on comment https://github.com/dotnet/roslyn/pull/66189#issuecomment-1379235958

In the following test, we could avoid copying the instance of `S1` as receiver for constrained call to `object.ToString()`.
Aleksey's proposal: Perhaps we could optimize cases like this as long as consumer and the consumed type are in the same module.

```
        [Fact]
        public void InvokeOnThisBaseMethods()
        {
            var text = @"
class Program
{
    static void Main()
    {
        default(S1).Test();
    }
    readonly struct S1
    {
        public void Test()
        {
            System.Console.Write(this.GetType());
            System.Console.Write(ToString());
        }
    }
}
";

            var comp = CompileAndVerify(text, parseOptions: TestOptions.Regular, verify: Verification.Passes, expectedOutput: @"Program+S1Program+S1");

            comp.VerifyIL("Program.S1.Test()", @"
{
  // Code size       47 (0x2f)
  .maxstack  1
  .locals init (Program.S1 V_0)
  IL_0000:  ldarg.0
  IL_0001:  ldobj      ""Program.S1""
  IL_0006:  box        ""Program.S1""
  IL_000b:  call       ""System.Type object.GetType()""
  IL_0010:  call       ""void System.Console.Write(object)""
  IL_0015:  ldarg.0
  IL_0016:  ldobj      ""Program.S1""
  IL_001b:  stloc.0
  IL_001c:  ldloca.s   V_0
  IL_001e:  constrained. ""Program.S1""
  IL_0024:  callvirt   ""string object.ToString()""
  IL_0029:  call       ""void System.Console.Write(string)""
  IL_002e:  ret
}");
        }
```

If we can avoid this copy, we would instead have the following IL (like before):

```
            comp.VerifyIL("Program.S1.Test()", @"
{
  // Code size       39 (0x27)
  .maxstack  1
  IL_0000:  ldarg.0
  IL_0001:  ldobj      ""Program.S1""
  IL_0006:  box        ""Program.S1""
  IL_000b:  call       ""System.Type object.GetType()""
  IL_0010:  call       ""void System.Console.Write(object)""
  IL_0015:  ldarg.0
  IL_0016:  constrained. ""Program.S1""
  IL_001c:  callvirt   ""string object.ToString()""
  IL_0021:  call       ""void System.Console.Write(string)""
  IL_0026:  ret
}");
```

Relates to PR https://github.com/dotnet/roslyn/pull/66189 which fixed some correctness issues with such constrained calls.

### LINKED ISSUE #76288: Unnecessary defensive copy on `readonly struct` when performing a constrained call
**Version Used**: sharplab.io

**Steps to Reproduce**:

Here we go again with another unnessary defensive copy 😆

```csharp
struct X
{
    private Y a;
    public readonly string W() => a.ToString(); //defensive copy for call to ToString
}

readonly struct Y
{
}
```

https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHwM4IE4FcDGCABABoCwAUAN6VF1EAO2UAbhAgKZECaREA3LXoABAMxFsHCABMA9jBQBPIsICMABiIB1ABQBKIgF4AfHwB0AFVkBlHLADm+wRQC+lSpJnylRLHkI8lDSulEA=

**Diagnostic Id**:

N/A

**Expected Behavior**:

No defensive copy is emitted for the call to `.ToString()`, since `Y` is `readonly`, and the default implementation provided by valuetype base classes also does not mutate (since they box & run on that, and also just don't mutate anyway, which is guaranteed by `III.2.1`) & any future overriding `ToString` implementation would have to be `readonly` since `Y` is `readonly`.

**Actual Behavior**:

A defensive copy of `a` is made (see below).

`W` marked `readonly`:
```cil
    .method public hidebysig 
        instance string W () cil managed 
    {
        .custom instance void [System.Runtime]System.Runtime.CompilerServices.IsReadOnlyAttribute::.ctor() = (
            01 00 00 00
        )
        .custom instance void [System.Runtime]System.Runtime.CompilerServices.NullableContextAttribute::.ctor(uint8) = (
            01 00 01 00 00
        )
        // Method begins at RVA 0x2050
        // Code size 21 (0x15)
        .maxstack 1
        .locals init (
            [0] valuetype Y
        )

        IL_0000: ldarg.0
        IL_0001: ldfld valuetype Y X::a
        IL_0006: stloc.0
        IL_0007: ldloca.s 0
        IL_0009: constrained. Y
        IL_000f: callvirt instance string [System.Runtime]System.Object::ToString()
        IL_0014: ret
    } // end of method X::W
```

`W` not marked `readonly`:
```cil
    .method public hidebysig 
        instance string W () cil managed 
    {
        .custom instance void [System.Runtime]System.Runtime.CompilerServices.NullableContextAttribute::.ctor(uint8) = (
            01 00 01 00 00
        )
        // Method begins at RVA 0x2050
        // Code size 18 (0x12)
        .maxstack 8

        IL_0000: ldarg.0
        IL_0001: ldflda valuetype Y X::a
        IL_0006: constrained. Y
        IL_000c: callvirt instance string [System.Runtime]System.Object::ToString()
        IL_0011: ret
    } // end of method X::W
```

### PR DESCRIPTION
**Pull request by stevenelliottjr**
## Summary

- When calling base class virtual methods (e.g., `ToString()`, `GetHashCode()`, `Equals()`) on readonly struct receivers via `constrained. callvirt`, the compiler previously used `AddressKind.Writeable` for the receiver address
- This caused unnecessary defensive copies when the receiver was in a readonly context (e.g., a field accessed through a readonly method's `this`, or a direct `this` reference in a readonly struct method)
- Since readonly structs guarantee non-mutation for all their methods, and constrained calls either resolve to a non-mutating method or box the value (which copies it), the original receiver is never mutated
- Changed to use `AddressKind.ReadOnly` for readonly value type receivers, eliminating the defensive copy

**Example (from #76288):**
```csharp
struct X
{
    private Y a;
    public readonly string W() => a.ToString();
}
readonly struct Y { }
```

**Before (21 bytes, 1 local):**
```il
ldarg.0
ldfld      "Y X.a"    // load value
stloc.0                // store to temp
ldloca.s   V_0         // address of temp
constrained. "Y"
callvirt   "string object.ToString()"
ret
```

**After (18 bytes, 0 locals):**
```il
ldarg.0
ldflda     "Y X.a"    // direct field address
constrained. "Y"
callvirt   "string object.ToString()"
ret
```

Fixes #76288
Closes #66365

## Test plan

- [x] Updated `InvokeOnThisBaseMethods` test to reflect eliminated defensive copy for `ToString()` on readonly struct `this`
- [x] Added new test `NoDefensiveCopy_ReadonlyStructField_ConstrainedCall` verifying the exact scenario from #76288
- [x] All 45 readonly struct codegen tests pass
- [x] Full Emit test suite passes (6986 passed, 0 failed)

### CODE REVIEW

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenReadonlyStructTests.cs [hunk 1]
```diff
@@ -512,29 +512,56 @@ public void Test()
...
+    public readonly string W() => a.ToString();
+}
+
+readonly struct Y
+{
+}
+";
+            var comp = CreateCompilation(text, options: TestOptions.ReleaseDll);
+            comp.VerifyDiagnostics(
+                // (4,15): warning CS0649: Field 'X.a' is never assigned to, and will always have its default value
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenReadonlyStructTests.cs]: >// (4,15): warning CS0649: Field 'X.a' is never assigned to, and will always have its default value [](http://example.com/codeflow?start=16&length=99)

Consider suppressing the warning with ```#pragma``` #Closed

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenReadonlyStructTests.cs [hunk 2]
```diff
@@ -512,29 +512,56 @@ public void Test()
...
+    private Y a;
+    public readonly string W() => a.ToString();
+}
+
+readonly struct Y
+{
+}
+";
+            var comp = CreateCompilation(text, options: TestOptions.ReleaseDll);
+            comp.VerifyDiagnostics(
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenReadonlyStructTests.cs]: >VerifyDiagnostics [](http://example.com/codeflow?start=17&length=17)

We generally prefer combining ```VerifyDiagnostics``` with ```CompileAndVerify``` since it collects diagnostics anyway and collects all diagnostics. #Closed

**Comment by AlekseyTs** [comment]
Done with review pass (commit 1) #Closed

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenReadonlyStructTests.cs [hunk 3]
```diff
@@ -512,29 +512,56 @@ public void Test()
 
             var comp = CompileAndVerify(text, parseOptions: TestOptions.Regular, verify: Verification.Passes, expectedOutput: @"Program+S1Program+S1");
 
-            // We may be able to optimize this case (ie. avoid defensive copy) since the struct and the caller are in the same module
-            // Tracked by https://github.com/dotnet/roslyn/issues/66365
```
Comment (jjonescz) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenReadonlyStructTests.cs:516]: Consider marking the issue as closed by the PR (writing literally `closes #66365` in the PR's description)

**Review by jjonescz — APPROVED** [review]

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 2)

**Comment by AlekseyTs** [comment]
@stevenelliottjr Thank you for the contribution
