### PR TITLE
Commit attribute named parameter items on space

### LINKED ISSUE #16236: Intellisense eats "=" while typing attribute parameter without committing completion
**Version Used**: 

VS 2017 RC public.d15rel/15.0.26014.0

**Steps to Reproduce**:

1. paste the following code into a C# code file

```csharp

[A()]
class AAttribute: Attribute
{
    public string Skip { get; set; }
}
```

2. type "Skip = " in "()" of "A[()]"

**Expected Behavior**:
"Skip " inserted in the editor

**Actual Behavior**:
"Skip = " inserted in the editor

### PR DESCRIPTION
**Pull request by rchande**
Fixes #16236 

Tag @dotnet/roslyn-ide for review

### CODE REVIEW

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb [hunk 1]
```diff
@@ -2911,5 +2911,22 @@ class Program
...
+                              <Document>
+[A($$)]
+class AAttribute: Attribute
+{
+    public string Skip { get; set; }
+} </Document>)
+                state.SendTypeChars("Skip")
+                Await state.AssertCompletionSession()
+                state.SendTypeChars(" ")
+                Await state.AssertNoCompletionSession()
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: can you assert what the line text is?

**Comment by CyrusNajmabadi** [comment]
👍 with test fix.

**Comment by rchande** [comment]
**Ask Mode Info**
- **Customer scenario**: Named parameter completion for attribute constructors does not commit items when the user types <space>. 
- **Bugs this fixes**: #16240
- **Workarounds**: The user has to remember to commit with tab, this breaks muscle memory
- **Risk**: Very low
- **Performance impact**: None.
- **Is this a regression from a previous update?**: Yes, this was regressed as part of the work to make completion into a public API.
- **How was the bug found?**: customer feedback
