### PR TITLE
Fix Code Model tests

### LINKED ISSUE #5800: Broken unit test Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeAttributeTests.TestAddArgument3
Test 'Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeAttributeTests.TestAddArgument3' failed:
	System.InvalidOperationException : Key already exists in table.
	Implementation\Interop\CleanableWeakComHandleTable.cs(174,0): at Microsoft.VisualStudio.LanguageServices.Implementation.Interop.CleanableWeakComHandleTable`2.Add(TKey key, TValue value)
	CodeModel\FileCodeModel.cs(193,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.OnCodeElementCreated(SyntaxNodeKey nodeKey, CodeElement element)
	CodeModel\InternalElements\CodeClass.cs(31,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeClass.Create(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNodeKey nodeKey, Nullable`1 nodeKind)
	CodeModel\VisualBasicCodeModelService.vb(563,0): at Microsoft.VisualStudio.LanguageServices.VisualBasic.CodeModel.VisualBasicCodeModelService.CreateInternalCodeElement(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node)
	CodeModel\FileCodeModel.cs(226,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.GetOrCreateCodeElement[T](SyntaxNode node)
	CodeModel\AbstractCodeModelService.cs(400,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.AbstractCodeModelService.CreateInternalCodeAttribute(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node)
	CodeModel\AbstractCodeModelService.cs(506,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.AbstractCodeModelService.CreateInternalCodeAttributeArgument(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node)
	CodeModel\VisualBasicCodeModelService.vb(538,0): at Microsoft.VisualStudio.LanguageServices.VisualBasic.CodeModel.VisualBasicCodeModelService.CreateInternalCodeElement(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node)
	CodeModel\FileCodeModel_CodeGen.cs(155,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.AddAttributeArgument(SyntaxNode containerNode, String name, String value, Object position)
	CodeModel\InternalElements\CodeAttribute.cs(150,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeAttribute.<>c__DisplayClass23_0.<AddArgument>b__0()
	CodeModel\FileCodeModel.cs(275,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.EnsureEditor[T](Func`1 action)
	CodeModel\InternalElements\CodeAttribute.cs(148,0): at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.CodeAttribute.AddArgument(String value, Object nameObj, Object position)
	at EnvDTE80.CodeAttribute2.AddArgument(String Value, Object Name, Object Position)
	CodeModel\AbstractCodeAttributeTests.vb(55,0): at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.AbstractCodeAttributeTests.AddAttributeArgument(CodeAttribute2 codeElement, AttributeArgumentData data)
	CodeModel\AbstractCodeAttributeTests.vb(123,0): at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.AbstractCodeAttributeTests.TestAddAttributeArgument(XElement code, XElement expectedCode, AttributeArgumentData data)
	CodeModel\VisualBasic\CodeAttributeTests.vb(847,0): at Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel.VisualBasic.CodeAttributeTests.TestAddArgument3()

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes #5800 

There were cases where the CleanableWeakComHandleTable could become inconsistent and the FileCodeModel could inadvertantly miss the need to remove a key from the table.

Sorry about the project.lock.json file changes. These were on my machine after a NuGet restore and getting rid of them meant that I couldn't build. I guess they're necessary?

Tagging @dotnet/roslyn-ide, @jaredpar, @tannergooding, @jmarolf

### CODE REVIEW

**Comment by DustinCampbell** [comment]
test linux please

**Comment by jasonmalinowski** [comment]
As far as the project.lock.json changes, I would expect they wouldn't really merge well since @tannergooding merged #5812 which upgraded us to a newer package. In theory that should also fix those issues. I think I would try rebasing atop current master, eliding your commit that touched the lock files, and pushing that to see what Jenkins thinks about that.

**Comment by DustinCampbell** [comment]
Rebased without the project.lock.json changes.

File: src/VisualStudio/Core/Test/CodeModel/VisualBasic/CodeAttributeTests.vb [hunk 1]
```diff
@@ -798,7 +798,7 @@ End Class
 
         End Sub
 
-        <ConditionalFact(GetType(x86), Skip:="https://github.com/dotnet/roslyn/issues/5800"), Trait(Traits.Feature, Traits.Features.CodeModel)>
+        <ConditionalFact(GetType(x86)), Trait(Traits.Feature, Traits.Features.CodeModel)>
```
Comment (balajikris) [inline src/VisualStudio/Core/Test/CodeModel/VisualBasic/CodeAttributeTests.vb]: Feel free to add a workitem attribute to the bug if you prefer.

**Comment by balajikris** [comment]
LGTM.
