### PR TITLE
Fix space formatting of exception filter.

### LINKED ISSUE #5099: There's no way to control the spacing within exception filter parentheses
### The problem

I have C# editor configured to insert spaces within non-empty parentheses for argument lists, expressions and control flow statements. However, none of these options affect the spacing within exception filter parentheses. Here's an example of what the code looks like today:

```
try
{
	DoSomething( path );
}
catch ( IOException ) when (File.Exists( path ))
{
}
```

I would like to set up the editor to format it this way:

```
try
{
	DoSomething( path );
}
catch ( IOException ) when ( File.Exists( path ) )
{
}
```

But, unfortunately, it's impossible to achieve with the options currently presented in VS.

### The solution

I believe it may be appropriate to use `Insert spaces within parentheses of control flow statements` option when formatting exception filters. After all, they do affect the execution flow =)

### PR DESCRIPTION
**Pull request by diryboy**
Fixes #5099 and another related bug: the spacing option after the `when` keyword.

### CODE REVIEW

File: src/Workspaces/CSharpTest/Formatting/FormattingTests.cs [hunk 1]
```diff
@@ -4942,7 +4942,7 @@ public void foo()
 
         try
         { }
-        catch(System.Exception e)
+        catch(System.Exception e) when(true)
```
Comment (diryboy) [inline src/Workspaces/CSharpTest/Formatting/FormattingTests.cs]: There is no options on how the space before `when` should behave, currently defaults forcing 1 space if same line, I left it as.

**Comment by diryboy** [comment]
retest this please, I don't think the failed test is related.

**Comment by diryboy** [comment]
Just documenting the previously unrelated [failed test](http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win/5707/testReport/Microsoft.CodeAnalysis.Editor.UnitTests.Rename/InlineRenameTests/RenameOverloadsCSharp/) here.

**Comment by DustinCampbell** [comment]
:+1: looks good!

**Comment by Pilchie** [comment]
LGTM too.
