### PR TITLE
Fix code gen for some increment/compound assignment scenarios involving constrained calls.

### LINKED ISSUE #79268: Unexpected behavior of property increment when receiver is a generic type parameter substituted with a reference type
```
interface I1
{
    public int P1 {get; set;}
}

class C1 : I1
{
    public int F1;

    public int P1
    {
        get
        {
            System.Console.Write(F1);
            Program.F = new C1 { F1 = Program.F.F1 + 1 };
            return 0;
        }
        set
        {
            System.Console.Write(F1);
        }
    }
}

class Program
{
    public static C1 F = new C1 { F1 = 123 };

    static void Main()
    {
        Test1(ref F);
        System.Console.Write(F.F1);

        System.Console.WriteLine();
        System.Console.WriteLine("----------");
        
        F = new C1 { F1 = 123 };
        Test2(ref F);
        System.Console.Write(F.F1);
    }

    static void Test1<T>(ref T f) where T : I1
    {
        f.P1++;
    }

    static void Test2(ref C1 f)
    {
        f.P1++;
    }
}
```

Observed:
```
123124124
----------
123123124
```

Property setter prints "124" for generic scenario (it is the number in the middle of the first line in the output). Which means that getter and setter are executed on a different instances, but the receiver is supposed to be the same for both. 

It is clear from IL why this is happening (the receiver is captured by reference and is used for constrained. calls):
```
    .method private hidebysig static 
        void Test1<(I1) T> (
            !!T& f
        ) cil managed 
    {
        // Method begins at RVA 0x2128
        // Code size 31 (0x1f)
        .maxstack 3
        .locals init (
            [0] int32
        )

        IL_0000: nop
        IL_0001: ldarg.0
        IL_0002: dup
        IL_0003: constrained. !!T
        IL_0009: callvirt instance int32 I1::get_P1()
        IL_000e: stloc.0
        IL_000f: ldloc.0
        IL_0010: ldc.i4.1
        IL_0011: add
        IL_0012: constrained. !!T
        IL_0018: callvirt instance void I1::set_P1(int32)
        IL_001d: nop
        IL_001e: ret
    } // end of method Program::Test1
```

Expected:
```
123123124
----------
123123124
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #79268

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review. There is extension specific code gen change in the pipeline that is being built on top of this fix.

**Comment by jcouv** [comment]
Spent some time today digging through this but will need more time to look tomorrow. I don't understand the role of `IsKnownToReferToTempIfReferenceType` yet. For instance, it seems strange to set it when the receiver is a value type.
It would be good to leave a comment for what we're trying to achieve (capture the receiver such that both getter and setter see the same instance and it can't be changed in the intervening time).

**Comment by AlekseyTs** [comment]
> I don't understand the role of `IsKnownToReferToTempIfReferenceType` yet. For instance, it seems strange to set it when the receiver is a value type. 

Its value is insignificant when we know that the type is not a reference type. And setting it when we know that the type cannot be a reference type doesn't really contradict anything given its conditional meaning ("IfReferenceType"), similar to ```All(<predicate>)``` LINQ method returning `true` for an empty set.

About the effect of the value. Leaving it `false` is always safe, `true` enables some optimizations if the value can be an instance of a reference type. The new code that sets it is not added for correctness, but to reduce effect of a change in ```VisitBuiltInOrStaticIncrementOperator``` on existing tests, and keeping IL the same.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review. There is extension specific code gen change in the pipeline that is being built on top of this fix.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs [hunk 1]
```diff
@@ -274,7 +274,16 @@ BoundExpression rewriteAssignment(BoundExpression leftRead, BoundExpression righ
             Debug.Assert(rewrittenReceiver.Type is { });
             var variableRepresentsLocation = rewrittenReceiver.Type.IsValueType || rewrittenReceiver.Type.Kind == SymbolKind.TypeParameter;
 
-            var receiverTemp = _factory.StoreToTemp(rewrittenReceiver, out assignmentToTemp, refKind: variableRepresentsLocation ? RefKind.Ref : RefKind.None);
+            var receiverTemp = _factory.StoreToTemp(
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs:277]: nit: it would be useful to comment on: 
1. the purpose of `isKnownToReferToTempIfReferenceType` is to drive how the value is captured, either using the gymnastic (if (default(T) != null) { ... just use/copy the ref to value type we have ... } else { ... dereference the ref to reference type, save it to temp and use ref to the temp ... }) or simple capture
2. the principle/goal: we want to avoid dereferencing a ref to reference type more than once, so we know the getter and setter see the same

**Review by jcouv — APPROVED** [review]
LGTM Thanks (commit 1)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs [hunk 2]
```diff
@@ -274,7 +274,16 @@ BoundExpression rewriteAssignment(BoundExpression leftRead, BoundExpression righ
...
+                rewrittenReceiver,
+                out assignmentToTemp,
+                refKind: variableRepresentsLocation ? RefKind.Ref : RefKind.None,
+                isKnownToReferToTempIfReferenceType: !variableRepresentsLocation || rewrittenReceiver.Type.IsValueType ||
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs:281]: >!variableRepresentsLocation || rewrittenReceiver.Type.IsValueType || [](http://example.com/codeflow?start=53&length=68)

Could this be simplified to `!rewrittenReceiver.Type.IsReferenceType || !HasHome(...)`?

**Review by jjonescz — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs:281]: > Could this be simplified to `!rewrittenReceiver.Type.IsReferenceType || !HasHome(...)`?

This condition doesn't look equivalent. Let's say we are dealing with an unconstrained type parameter, ```!rewrittenReceiver.Type.IsReferenceType``` is `true`, but that doesn't guarantee that we are referring to a copy.
