### PR TITLE
Suppress IDE0004 for switch case label when casting is required

### LINKED ISSUE #19987: Incorrect IDE0004 (Cast is redundant) in pattern matching
**Version Used**: 15.3 Preview 1

🔗 Originally reported by [Thomas Castiglione](https://developercommunity.visualstudio.com/users/21348/873dad1a-b02f-4f5a-8da9-37ef170c009b.html).

**Steps to Reproduce**:

```csharp
using System;

namespace ConsoleApp4
{
    class Program
    {
        static void Main(string[] args)
        {
            object x = 1f;
            switch (x)
            {
            case (float)1:
                Console.WriteLine("one");
                break;

            default:
                Console.WriteLine("not one");
                break;
            }
        }
    }
}
```

**Expected Behavior**:

* IDE0004 is not reported on the cast in `(float)1`
* Fixing all violations of IDE0004 does not remove the cast

**Actual Behavior**:

* The cast is removed when fixing IDE0004, resulting in a change in program behavior

### PR DESCRIPTION
**Pull request by elijah6**
Fixes #19987

**Customer scenario**

Explicit casting used in `switch` case label is sometimes incorrectly given IDE0004 (Cast is redundant) in Visual Studio, and users could incorrectly follow the suggestion, which changes the behaviour of the program.
A specific scenario described at #19987  

**Bugs this fixes:**

#19987 

**Workarounds, if any**

Ignore IDE suggestion.

**Risk**

**Performance impact**

Low, as there is no complexity change. Only an additional check for switch case label. 

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

There was no unit test for this specific case before (probably rarely used scenario). Tests added in this PR branch.

**How was the bug found?**

#19987 (🔗Originally reported by [Thomas Castiglione](https://developercommunity.visualstudio.com/users/21348/873dad1a-b02f-4f5a-8da9-37ef170c009b.html))

### CODE REVIEW

File: src/Workspaces/CSharp/Portable/Utilities/SpeculationAnalyzer.cs [hunk 1]
```diff
@@ -379,6 +379,39 @@ protected override bool ReplacementChangesSemanticsForNodeLanguageSpecific(Synta
...
+                
+                // if conversion only exists for either original or new, then semantics changed.
+                if (originalConversion.Exists != newConversion.Exists)
+                {
+                    return true;
+                }
+
+                // Same conversion cannot result in both originalCaseType and newCaseType, which means the semantics changed
+                // (since originalCaseType != newCaseType)
+                return originalConversion == newConversion;
```
Comment (elijah6) [inline src/Workspaces/CSharp/Portable/Utilities/SpeculationAnalyzer.cs]: Here, I am being quite generic and trying to check if the conversions from switch expression to `originalCaseType` and `newCaseType` are the same, then the resulting types should have been the same in order to have the same semantics. Since the types are different at this point, have the same conversions mean that the semantics actually changed. 
I couldn't think of any exceptional case that this would break something else.

File: src/Workspaces/CSharp/Portable/Utilities/SpeculationAnalyzer.cs [hunk 2]
```diff
@@ -379,6 +379,39 @@ protected override bool ReplacementChangesSemanticsForNodeLanguageSpecific(Synta
...
+                }
+
+                var originalConversion = this.OriginalSemanticModel.ClassifyConversion(oldSwitchStatement.Expression, originalCaseType);
+                var newConversion = this.SpeculativeSemanticModel.ClassifyConversion(newSwitchStatement.Expression, newCaseType);
+                
+                // if conversion only exists for either original or new, then semantics changed.
+                if (originalConversion.Exists != newConversion.Exists)
+                {
+                    return true;
+                }
```
Comment (elijah6) [inline src/Workspaces/CSharp/Portable/Utilities/SpeculationAnalyzer.cs]: I was thinking of returning `false` if `originalConversion.Exists` and `newConversion.Exists` are both false, but then I believe the resulting type should have been the same in order for the semantic to have remained the same. So I don't think I should return `false` straight away.

**Comment by elijah6** [comment]
restest windows_release_vs-integration_prtest please

**Comment by elijah6** [comment]
retest windows_release_vs-integration_prtest please

**Comment by Pilchie** [comment]
Thanks for the contribution @elijah6!  Tagging @dotnet/roslyn-ide for review.

**Comment by elijah6** [comment]
retest windows_release_vs-integration_prtest please

**Comment by dpoeschl** [comment]
retest windows_release_vs-integration_prtest please

**Comment by dpoeschl** [comment]
retest windows_debug_vs-integration_prtest please

File: src/Workspaces/CSharp/Portable/Utilities/SpeculationAnalyzer.cs [hunk 3]
```diff
@@ -379,6 +379,39 @@ protected override bool ReplacementChangesSemanticsForNodeLanguageSpecific(Synta
...
+
+                // If case label is changing, then need to check if the semantics will change for the switch expression.  
+                // e.g. if switch expression is "switch(x)" where "object x = 1f", then "case 1:" and "case (float) 1:" are different.
+                var originalCaseType = this.OriginalSemanticModel.GetTypeInfo(previousOriginalNode, this.CancellationToken).Type;
+                var newCaseType = this.SpeculativeSemanticModel.GetTypeInfo(previousReplacedNode, this.CancellationToken).Type;
+
+                if (originalCaseType == newCaseType)
+                    return false;
+
+                var oldSwitchStatement = originalCaseSwitchLabel?.Parent?.Parent as SwitchStatementSyntax;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Utilities/SpeculationAnalyzer.cs]: ?. not necessary here or next statement.
'as' not necessary.  Do direct cast.

File: src/Workspaces/CSharp/Portable/Utilities/SpeculationAnalyzer.cs [hunk 4]
```diff
@@ -379,6 +379,39 @@ protected override bool ReplacementChangesSemanticsForNodeLanguageSpecific(Synta
...
+                var newSwitchStatement = newCaseSwitchLabel?.Parent?.Parent as SwitchStatementSyntax;
+                if (oldSwitchStatement == null || newSwitchStatement == null)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Utilities/SpeculationAnalyzer.cs]: null checks not necessary.

**Comment by elijah6** [comment]
Thank you for the review. I've removed unnecessary casts as per comments and rebased.

File: src/Workspaces/CSharp/Portable/Utilities/SpeculationAnalyzer.cs [hunk 5]
```diff
@@ -379,6 +379,35 @@ protected override bool ReplacementChangesSemanticsForNodeLanguageSpecific(Synta
...
+
+                // If case label is changing, then need to check if the semantics will change for the switch expression.  
+                // e.g. if switch expression is "switch(x)" where "object x = 1f", then "case 1:" and "case (float) 1:" are different.
+                var originalCaseType = this.OriginalSemanticModel.GetTypeInfo(previousOriginalNode, this.CancellationToken).Type;
+                var newCaseType = this.SpeculativeSemanticModel.GetTypeInfo(previousReplacedNode, this.CancellationToken).Type;
+
+                if (originalCaseType == newCaseType)
+                    return false;
+
+                var oldSwitchStatement = (SwitchStatementSyntax) originalCaseSwitchLabel.Parent.Parent;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Utilities/SpeculationAnalyzer.cs]: nit: no space after casts.

Comment (elijah6) [inline src/Workspaces/CSharp/Portable/Utilities/SpeculationAnalyzer.cs]: Oops, corrected.

**Comment by elijah6** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by elijah6** [comment]
retest windows_release_vs-integration_prtest  please
