### PR TITLE
Do not fade code for IDE0016 (UseThrowExpressionDiagnosticId)

### LINKED ISSUE #27213: IDE0016 should not be dimming the text as that indicates the code is unused.
I dont want to turn the inspection off, but it needs to have some other style of annotating the code. 

Also, the recommended action for these combines the property set with an exception throw, and that can makes the text harder to read by either causing line breaks to be added or makes for more scrolling.

I'm not sure if I want this feature at all or not. Its useful when its in a constructor and it can be used for something like

```csharp
_privateField = constructorParam ?? throw new ArgumentNullException(nameof(constructorParam)); 
```

but not for general use in a class where it wants to do take this... 

```csharp
var someObject = new Thing();
var thingCandidateField = _controller.GetStuff(SomeOtherObject.SearchField);
if (thingCandidateField == null)
{
   throw new InvalidOperationException($"Cant make a new thing. The paramter {nameof(SomeOtherObject.SearchField)} had value {SomeOtherObject.SearchField} that returned no results.");
}
someObject.Prop1 = thingCandidateField;
```

and make this...

```csharp
var someObject = new Thing();
var thingCandidateField = _controller.GetStuff(SomeOtherObject.SearchField);
someObject.Prop1 = thingCandidateField ?? throw new InvalidOperationException($"Cant make a new thing. The parameter {nameof(SomeOtherObject.SearchField)} had value {SomeOtherObject.SearchField} that returned no results.");
```

Sorry about the formatting if its bad.  That last statement should be one long single line. This feedback tool is still very hard to use when sharing code.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/256320/ide0016-should-not-be-dimming-the-text-as-that-ind.html
VSTS ticketId: 618902_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #27213

Analyzer recommends using throw expression for null checks instead of throw statement within an if statement with null check. We used to fade the entire if statement for discoverability and increased code fix span, but this was undesirable as we want to fade only unnecessary or dead code. Instead, we now generate a hidden non-configurable fixable diagnostic for the increased code fix span and do not generate any fading.

### CODE REVIEW

File: src/Features/Core/Portable/UseThrowExpression/AbstractUseThrowExpressionDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -143,29 +163,13 @@ private void AnalyzeOperation(OperationAnalysisContext context, INamedTypeSymbol
...
+            // Report a configurable diagnostic on the throw statement span.
             context.ReportDiagnostic(
-                DiagnosticHelper.Create(Descriptor, throwStatementSyntax.GetLocation(), option.Notification.Severity, additionalLocations: allLocations, properties: null));
-
-            // Fade out the rest of the if that surrounds the 'throw' exception.
+                DiagnosticHelper.Create(s_descriptor, throwStatementSyntax.GetLocation(), option.Notification.Severity, additionalLocations: allLocations, properties: null));
 
-            var tokenBeforeThrow = throwStatementSyntax.GetFirstToken().GetPreviousToken();
-            var tokenAfterThrow = throwStatementSyntax.GetLastToken().GetNextToken();
+            // Report a non-configurable hidden fixable diagnostic on the "if" span so the code fix can be invoked from anywhere inside the "if" span.
```
Comment (sharwell) [inline src/Features/Core/Portable/UseThrowExpression/AbstractUseThrowExpressionDiagnosticAnalyzer.cs]: 💭 I would also be fine with this part just going away

Comment (mavasani) [reply src/Features/Core/Portable/UseThrowExpression/AbstractUseThrowExpressionDiagnosticAnalyzer.cs]: That broke existing unit tests and might also break anyone who is used to triggering the fix from if statement header instead of throw statement. I have tried to be conservative in the sense that only user observable change after this PR would be no fading. I would have probably implemented it as per your suggestion if this was a new analyzer. If required, we can certainly come back and remove the hidden fixable diagnostic in future.

File: src/Features/Core/Portable/UseThrowExpression/AbstractUseThrowExpressionDiagnosticAnalyzer.cs [hunk 2]
```diff
@@ -33,12 +33,32 @@ namespace Microsoft.CodeAnalysis.UseThrowExpression
...
+        internal const string UseThrowExpressionFixableDiagnosticId = IDEDiagnosticIds.UseThrowExpressionDiagnosticId + "_Fixable";
+
+        private static readonly LocalizableString s_title = new LocalizableResourceString(nameof(FeaturesResources.Use_throw_expression), FeaturesResources.ResourceManager, typeof(FeaturesResources));
+        private static readonly LocalizableString s_message = new LocalizableResourceString(nameof(FeaturesResources.Null_check_can_be_simplified), FeaturesResources.ResourceManager, typeof(FeaturesResources));
+
+        private static readonly DiagnosticDescriptor s_descriptor = CreateDescriptorWithId(
+            IDEDiagnosticIds.UseThrowExpressionDiagnosticId,
+            s_title,
+            s_message);
+        private static readonly DiagnosticDescriptor s_fixableDescriptor = CreateDescriptorWithId(
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/UseThrowExpression/AbstractUseThrowExpressionDiagnosticAnalyzer.cs]: can you doc the difference between these two?

File: src/Features/Core/Portable/UseThrowExpression/AbstractUseThrowExpressionDiagnosticAnalyzer.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/UseThrowExpression/AbstractUseThrowExpressionDiagnosticAnalyzer.cs]: i would also prefer this going away.  we really don't generally have the concept of "this is available where there isn't some UI affordance" (which is also why it looks like you had to fight against this class above).  I would just change the tests to say that this does *not* show up there anymore.

THere will be a `...`.  The user will have a message in the task-list.  That's sufficient IMO.

Comment (mavasani) [reply src/Features/Core/Portable/UseThrowExpression/AbstractUseThrowExpressionDiagnosticAnalyzer.cs]: Sounds good - given we have more than one vote on just removing this and changing unit tests, I will do the same.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/UseThrowExpression/AbstractUseThrowExpressionDiagnosticAnalyzer.cs]: thanks!

File: src/Features/Core/Portable/UseThrowExpression/AbstractUseThrowExpressionDiagnosticAnalyzer.cs (hunk 2 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/UseThrowExpression/AbstractUseThrowExpressionDiagnosticAnalyzer.cs]: note: this concern looks like it will go away once you address the above point :)

File: src/Features/Core/Portable/UseThrowExpression/AbstractUseThrowExpressionDiagnosticAnalyzer.cs (hunk 1 above)
Comment (mavasani) [reply src/Features/Core/Portable/UseThrowExpression/AbstractUseThrowExpressionDiagnosticAnalyzer.cs]: Reverted my original commit and pushed a new commit to remove the fading diagnostic and update unit tests.

**Comment by JoeRobich** [comment]
Merging since we are flowing through a change to temporarily disable the mono test leg.

**Comment by CyrusNajmabadi** [comment]
Wait, is master back open for PRs?

**Comment by JoeRobich** [comment]
@CyrusNajmabadi Open for IDE bug fixes at the moment. Should move to being open for 16.4 p1 development tomorrow evening.
