### PR TITLE
Don't attach trivia to nodes that will be removed, fixes #28323

### LINKED ISSUE #28323: NRE in InlineDeclarationCodeFix with more than one local on the same line
**Version Used**: 
VS 15.8 Preview 3

**Steps to Reproduce**:
```csharp
using System;

public static class Program
{
    public static void Main()
    {
        long ip; int port;
        Int64.TryParse("", out ip);
        Int32.TryParse("", out port);
    }
}
```
1. Create a console application with code above
2. Make sure code cleanup is enabled
3. Press CTRL + K, CTRL + D to format the document

**Expected Behavior**:
```csharp
using System;

public static class Program
{
    public static void Main()
    {
        Int64.TryParse("", out long ip);
        Int32.TryParse("", out int port);
    }
}
```

**Actual Behavior**:
VS shows servicehub host clr x86_2018-07-06_04-18-01 for a long time, followed by
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Shared.Extensions.SyntaxNodeExtensions.WithAppendedTrailingTrivia[T](T node, SyntaxTriviaList trivia)
   at Microsoft.CodeAnalysis.CSharp.InlineDeclaration.CSharpInlineDeclarationCodeFixProvider.<>c__DisplayClass4_0.<AddEditsAsync>b__1(SyntaxNode s, SyntaxGenerator g)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.ReplaceChange.Apply(SyntaxNode root, SyntaxGenerator generator)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.<FixAllWithEditorAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.SyntaxEditorBasedFixAllProvider.<GetFixAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.SyntaxEditorBasedFixAllProvider.<GetFixAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.<GetFixAllCodeActionAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.<GetFixAllChangedSolutionAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CSharp.CodeCleanup.CSharpCodeCleanupService.<ApplyCodeFixesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CSharp.CodeCleanup.CSharpCodeCleanupService.<CleanupAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Editor.Implementation.Formatting.FormatCommandHandler.<GetCodeCleanupAndFormatChangesAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Formatting.FormatCommandHandler.ExecuteCommand(FormatDocumentCommandArgs args, CommandExecutionContext context)
   at Microsoft.VisualStudio.Commanding.CommandHandlerExtensions.ExecuteCommand[T](ICommandHandler commandHandler, T args, Action nextCommandHandler, CommandExecutionContext executionContext)
   at Microsoft.VisualStudio.UI.Text.Commanding.Implementation.EditorCommandHandlerService.<>c__DisplayClass14_1`1.<Execute>b__1()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

### PR DESCRIPTION
**Pull request by Suchiman**
Fixes #28323

The issue was that in FixAll mode, it was trying to move trivia to nodes that would be deleted or already were deleted. The fix is to first find all Statements that are going to be removed and then skip over them when searching for Statements to attach the trivia to

<details><summary>Ask Mode template not completed</summary>

### Customer scenario

What does the customer do to get into this situation, and why do we think this
is common enough to address for this release.  (Granted, sometimes this will be
obvious "Open project, VS crashes" but in general, I need to understand how
common a scenario is)

### Bugs this fixes

(either VSO or GitHub links)

### Workarounds, if any

Also, why we think they are insufficient for RC vs. RC2, RC3, or RTW

### Risk

This is generally a measure our how central the affected code is to adjacent
scenarios and thus how likely your fix is to destabilize a broader area of code

### Performance impact

(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")

### Root cause analysis

How did we miss it?  What tests are we adding to guard against it in the future?

### How was the bug found?

(E.g. customer reported it vs. ad hoc testing)

### Test documentation updated?

If this is a new non-compiler feature or a significant improvement to an existing feature, update https://github.com/dotnet/roslyn/wiki/Manual-Testing once you know which release it is targeting.

</details>

### CODE REVIEW

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 1]
```diff
@@ -84,33 +92,66 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
+                            continue;
+                        }
+                        if (sourceText.AreOnSameLine(statementSyntax.GetLastToken(), localDeclarationToken))
+                        {
+                            statement = statementSyntax;
+                            return true;
+                        }
+                    }
+                    return false;
+                }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: in general, the preference is for nested functions to go at teh end of the main function, after an explicit 'return' statement of some form.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 2]
```diff
@@ -84,33 +92,66 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
+                        var statementSyntax = block.Statements[i];
+                        if (declarationsToRemove.Contains(statementSyntax))
+                        {
+                            continue;
+                        }
+                        if (sourceText.AreOnSameLine(statementSyntax.GetLastToken(), localDeclarationToken))
+                        {
+                            statement = statementSyntax;
+                            return true;
+                        }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: it feels like we would want to break here and return false.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 3]
```diff
@@ -84,33 +92,66 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
+
+                    var localDeclarationToken = localDeclarationStatement.GetFirstToken();
+                    for (int i = declarationIndex - 1; i >= 0; i--)
+                    {
+                        var statementSyntax = block.Statements[i];
+                        if (declarationsToRemove.Contains(statementSyntax))
+                        {
+                            continue;
+                        }
+                        if (sourceText.AreOnSameLine(statementSyntax.GetLastToken(), localDeclarationToken))
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: blank line after }

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 4]
```diff
@@ -84,33 +92,66 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
+                        {
+                            statement = statementSyntax;
+                            return true;
+                        }
+                    }
+                    return false;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: blank line after }

File: src/EditorFeatures/CSharpTest/InlineDeclaration/CSharpInlineDeclarationTests_FixAllTests.cs [hunk 5]
```diff
@@ -94,6 +95,53 @@ void M()
...
+
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsInlineDeclaration)]
+        public async Task FixAllInDocument5()
+        {
+            await TestInRegularAndScriptAsync(
+@"class C
+{
+    void M()
+    {
+        int {|FixAllInDocument:ip|}, port;
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/InlineDeclaration/CSharpInlineDeclarationTests_FixAllTests.cs]: let's have tests with 3 locals on the same line, where either hte first/second, first/third, or second/third get removed.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 6]
```diff
@@ -84,33 +92,66 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
+                        if (!declarationsToRemove.Contains(statement))
+                        {
+                            nextStatementSyntax = statement;
+                            break;
+                        }
+                    }
+
                     editor.ReplaceNode(
-                        block.Statements[declarationIndex + 1],
+                        nextStatementSyntax,
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: this coudl end up being null.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs (hunk 1 above)
Comment (Suchiman) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: `declarationIndex` and `localDeclarationStatement` are out of scope if i move it to the end of the method.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs (hunk 6 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: can you add a comment to that effect.  THanks!

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: Then pass them in as arguments :)   There's little need for this to be a nested function in teh first place.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: Note: it's not like this class is particularly large.  it's entire purpose is to provide the fix.  So i have no problem with this just being a helper method as well.  it's not super important that everything be scoped as narrowly as humanly possible in teh code :)

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 7]
```diff
@@ -84,33 +92,66 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
                 // this local statement will be moved to be above the statement containing
-                // the out-var. 
+                // the out-var.
                 var localDeclarationStatement = (LocalDeclarationStatementSyntax)declaration.Parent;
                 var block = (BlockSyntax)localDeclarationStatement.Parent;
                 var declarationIndex = block.Statements.IndexOf(localDeclarationStatement);
 
-                if (declarationIndex > 0 &&
-                    sourceText.AreOnSameLine(block.Statements[declarationIndex - 1].GetLastToken(), localDeclarationStatement.GetFirstToken()))
+                bool TryFindPriorSurvivingStatementOnSameLine(out StatementSyntax statement)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: note:  in Roslyn 'Try' already implies 'can return null'.  So this could just be ```StatementSyntax TryFindPrior...()```.  So no need for out params and whatnot.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 8]
```diff
@@ -84,33 +92,66 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
+                        if (sourceText.AreOnSameLine(statementSyntax.GetLastToken(), localDeclarationToken))
+                        {
+                            statement = statementSyntax;
+                            return true;
+                        }
+                    }
+                    return false;
+                }
+
+                if (declarationIndex > 0 && TryFindPriorSurvivingStatementOnSameLine(out var priorStatementSyntax))
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: The check for ```declarationIndex > 0``` is now unnecessary.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs (hunk 6 above)
Comment (Suchiman) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: Done

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 9]
```diff
@@ -93,35 +92,33 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
-                        if (sourceText.AreOnSameLine(statementSyntax.GetLastToken(), localDeclarationToken))
-                        {
-                            statement = statementSyntax;
-                            return true;
-                        }
+                        break;
                     }
-                    return false;
+
+                    priorStatementSyntax = statementSyntax;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: shouldn't we break right after this?  otherwise, we'll keep looking back on the same line, when really we just want the nearest one that will stay.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 10]
```diff
@@ -84,33 +91,67 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
+                        continue;
+                    }
+
+                    if (!sourceText.AreOnSameLine(statementSyntax.GetLastToken(), localDeclarationToken))
+                    {
+                        break;
+                    }
+
+                    priorStatementSyntax = statementSyntax;
+                    break;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: both these codepaths break.  so this seems simpler as:

```c#
+                    if (sourceText.AreOnSameLine(statementSyntax.GetLastToken(), localDeclarationToken))
+                    {
+                        priorStatementSyntax = statementSyntax;
+                    }
+
+                    break;
```

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs (hunk 6 above)
Comment (AdamSpeight2008) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: @Suchiman Wouldn't an assertion be more appropriate?

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 11]
```diff
@@ -39,11 +38,19 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
             SyntaxEditor editor, CancellationToken cancellationToken)
         {
             var options = await document.GetOptionsAsync(cancellationToken).ConfigureAwait(false);
 
+            // Gather all statements to be removed
+            // We need this to find the statements we can safely attach trivia to
+            var declarationsToRemove = new HashSet<StatementSyntax>();
+            foreach (var diagnostic in diagnostics)
+            {
+                declarationsToRemove.Add((LocalDeclarationStatementSyntax)diagnostic.AdditionalLocations[0].FindNode(cancellationToken).Parent.Parent);
```
Comment (heejaechang) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: so what is the location in additionalLocations[0] and what findNode will return?

Comment (heejaechang) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: if we are trying to find statement syntax node, how about just calling GetAncestor<StatementSyntax>().First() ?

Comment (Suchiman) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: `AdditionalLocations[0]` contains the declarator as can be seen here https://github.com/dotnet/roslyn/pull/28793/files#diff-7634d845769381db613da4beabce8ef6R76 so `.Parent.Parent` should always give the correct `LocalDeclarationStatementSyntax` but `GetAncestor<LocalDeclarationStatementSyntax>()` should work as well (although slower)

File: src/EditorFeatures/CSharpTest/InlineDeclaration/CSharpInlineDeclarationTests_FixAllTests.cs [hunk 12]
```diff
@@ -94,6 +95,212 @@ void M()
...
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsInlineDeclaration)]
+        [WorkItem(28323, "https://github.com/dotnet/roslyn/issues/28323")]
+        public async Task FixAllInDocument6()
+        {
+            await TestInRegularAndScriptAsync(
+@"class C
+{
+    void M()
+    {
+        int {|FixAllInDocument:i1|}; int dummy; int i2;
```
Comment (heejaechang) [inline src/EditorFeatures/CSharpTest/InlineDeclaration/CSharpInlineDeclarationTests_FixAllTests.cs]: can we have some tests with comments? like /* 0 */int /* 1 */ dummy /* 2 */; /* 3*/

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs [hunk 13]
```diff
@@ -84,33 +91,66 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
+                }
+
+                if (priorStatementSyntax != null)
                 {
                     // There's another statement on the same line as this declaration statement.
                     // i.e.   int a; int b;
                     //
                     // Just move all trivia from our statement to be trailing trivia of the previous
                     // statement
                     editor.ReplaceNode(
```
Comment (heejaechang) [inline src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: where would other trivia that is in between will go except the one that you explicitly attach? can you add some test that shows how comments are handled?

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs (hunk 11 above)
Comment (heejaechang) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: alright. just checking since it assumes span that map to the certain node to be in additional locations in the certain order which I am not sure whether that is hard contract or just happen to be that way.

if that assumption got broken, unit test will fail, so fine with that.

File: src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs (hunk 13 above)
Comment (Suchiman) [reply src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs]: The comment handling is already covered in detail in the non fixall case here https://github.com/dotnet/roslyn/blob/9305ede18b0432055929ef70a2dfdd895a085707/src/EditorFeatures/CSharpTest/InlineDeclaration/CSharpInlineDeclarationTests.cs#L649-L924

**Comment by Suchiman** [comment]
@heejaechang while adding one of the comment tests, i've noticed that when it removes several statements on the same line, it will flip around the order of the comments as can be seen here https://github.com/dotnet/roslyn/blob/fd8e3abfa79223eba321d8c29cfb14cef5da4df4/src/EditorFeatures/CSharpTest/InlineDeclaration/CSharpInlineDeclarationTests_FixAllTests.cs#L312-L330
I've stared at this now for a few hours on different week(day)s (hence the delay in response) and came up with no good solution that doesn't introduce more weirdness in trivia or uncovers more ordering dependencies in this code (e.g. if you process the diagnostics in reverse order).
If this isn't acceptable (at least it's an improvement over throwing a `NullReferenceException`), i would appreciate some guidance.

**Comment by heejaechang** [comment]
@Suchiman can you open an issue on the comment handling and link the issue in this PR? I don't think it is severe enough to block this PR. we probably need to come up with more general trivia/comment handling system people can use rather than asking each fixer to do thier own thing.

**Comment by heejaechang** [comment]
@Suchiman have you used "WIP" word in any of your commits? I can't find one but somehow WIP is pending.

**Comment by Suchiman** [comment]
@heejaechang i don't think i've ever used "WIP". 
Filed #31459 for the trivia ordering

**Comment by Suchiman** [comment]
@heejaechang rebased onto master. The conflict was only about trailing whitespace.

**Comment by genlu** [comment]
@jinujoseph @vatsalyaagrawal for p3 approval.
@Suchiman @heejaechang I assume this is good to merge now?

**Comment by jinujoseph** [comment]
@heejaechang good to merge ?

**Comment by heejaechang** [comment]
thank you!
