### PR TITLE
Turn on the compiler server by default for the compiler VSIX

### LINKED ISSUE #15696: RC insider VSIX can dramatically increase build times?
**Version Used**: Visual Studio 2015 Update 3 + RC insider VSIX

**Steps to Reproduce**:

While trying to build Roslyn, I installed VS 2015 Preview 4 and RC insider VSIX as the [installation instructions](https://github.com/dotnet/roslyn/wiki/Building-Testing-and-Debugging) suggested. After that I was [not able to build Roslyn](https://github.com/dotnet/roslyn/issues/15667), but that's a separate issue. Around the same time, I noticed [my projects were building very slowly](http://stackoverflow.com/questions/40953934/vs-2015-suddenly-builds-very-slowly/40993332#40993332). With help online I eventually noticed that my compiler was running from inside the Extensions\14.0 folder, making me think "RC Insider" was the cause. I think that's true because [uninstalling RC insider fixed the problem](http://stackoverflow.com/a/40993332/22820).

**Expected Behavior**: Normal speed build.

**Actual Behavior**: 8x slower build than normal.

How could RC insider cause this issue?

I would request that the Roslyn build instructions be updated to inform users that they are **globally** replacing the C# compiler used by Visual Studio, so that when all their builds start acting up, they have some hint what the cause might be.

Also, the build instructions say that following the RC insider uninstall instructions will also delete any other VS extensions that the user might have - which is horrible. Is there a more precise way to uninstall it? (On the plus side, Visual Studio reports that some of my extensions are still installed.)

### PR DESCRIPTION
**Pull request by agocke**
Fix #15696

### CODE REVIEW

File: src/Compilers/Extension/CompilerPackage.cs [hunk 1]
```diff
@@ -70,12 +70,11 @@ private void WriteMSBuildFiles(string packagePath, string hiveName)
                     $@"<?xml version=""1.0"" encoding=""utf-8""?>
 <Project xmlns=""http://schemas.microsoft.com/developer/msbuild/2003"">
   <!-- If we're not using the compiler server, set ToolPath/Exe to direct to the exes in this package -->
-  <PropertyGroup Condition=""'$(RoslynHive)' == '{hiveName}' and '$(UseSharedCompilation)' != 'true'"">
+  <PropertyGroup Condition=""'$(RoslynHive)' == '{hiveName}' and '$(UseSharedCompilation)' == 'false'"">
```
Comment (jasonmalinowski) [inline src/Compilers/Extension/CompilerPackage.cs]: So setting CscToolPath/VbcToolPath disables shared compilation? Then what's setting the path to the compiler otherwise?

Comment (agocke) [reply src/Compilers/Extension/CompilerPackage.cs]: The targets should import the task, then the task uses Assembly.GetExecutingLocation to find the location of the server next to it.

Comment (agocke) [reply src/Compilers/Extension/CompilerPackage.cs]: (The code for UsingTask is a half-dozen lines above)
