### PR TITLE
[SQLite] Fix continuous probing for sqlite

### LINKED ISSUE #24042: [PersistentStorage] Should not try to re-create the database if native lib probing exceptions occur
**Version Used**: 
2.6.0

**Steps to Reproduce**:

1. Use SQLiteStorage
2. Remove the e_sqlite.dll (to mirror what would happen on Linux, for example, when the library can't be probed)
3. Observe that a lot of exceptions are being logged with this stacktrace

```
  at Microsoft.CodeAnalysis.Storage.StorageDatabaseLogger.LogExceptionWorker (System.Exception) [0x00020] in <eba66fb254b64fc2bac5f4dea6d5a28c>:0
  at Microsoft.CodeAnalysis.Storage.StorageDatabaseLogger.LogException (System.Exception) [0x00006] in <eba66fb254b64fc2bac5f4dea6d5a28c>:0
  at Microsoft.CodeAnalysis.Storage.AbstractPersistentStorageService.TryCreatePersistentStorage (Microsoft.CodeAnalysis.Solution,string,Microsoft.CodeAnalysis.Host.AbstractPersistentStorage&) [0x0003e] in <eba66fb254b64fc2bac5f4dea6d5a28c>:0
  at Microsoft.CodeAnalysis.Storage.AbstractPersistentStorageService.TryCreatePersistentStorage (Microsoft.CodeAnalysis.Solution,string) [0x00011] in <eba66fb254b64fc2bac5f4dea6d5a28c>:0
  at Microsoft.CodeAnalysis.Storage.AbstractPersistentStorageService.GetStorage (Microsoft.CodeAnalysis.Solution,string) [0x000a4] in <eba66fb254b64fc2bac5f4dea6d5a28c>:0
  at Microsoft.CodeAnalysis.Storage.AbstractPersistentStorageService.GetStorage (Microsoft.CodeAnalysis.Solution,bool) [0x00057] in <eba66fb254b64fc2bac5f4dea6d5a28c>:0
  at Microsoft.CodeAnalysis.Storage.AbstractPersistentStorageService.GetStorage (Microsoft.CodeAnalysis.Solution) [0x00003] in <eba66fb254b64fc2bac5f4dea6d5a28c>:0
  at Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticDataSerializer/<DeserializeAsync>d__5.MoveNext () [0x0002a] in <9b2be15306ff44fbad0829eadaca768a>:0
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<System.Runtime.CompilerServices.StrongBox`1<System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Diagnostics.DiagnosticData>>>.Start<Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticDataSerializer/<DeserializeAsync>d__5> (Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticDataSerializer/<DeserializeAsync>d__5&) [0x0002c] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471
  at Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticDataSerializer.DeserializeAsync (object,string,System.Threading.CancellationToken) [0x00044] in <9b2be15306ff44fbad0829eadaca768a>:0
  at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectState.DeserializeAsync (Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticDataSerializer,object,object,string,System.Threading.CancellationToken) [0x0005d] in <c687f5f16d954d66b706836583783302>:0
  at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectState/<TryDeserializeAsync>d__26`2<TKey_REF, TArg_REF>.MoveNext () [0x00035] in <c687f5f16d954d66b706836583783302>:0
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<bool>.Start<Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectState/<TryDeserializeAsync>d__26`2<Microsoft.CodeAnalysis.DocumentId, Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectState/Builder>> (Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectState/<TryDeserializeAsync>d__26`2<Microsoft.CodeAnalysis.DocumentId, Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectState/Builder>&) [0x0002c] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471
  at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectState.TryDeserializeAsync<TKey_REF, TArg_REF> (Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticDataSerializer,object,TKey_REF,string,System.Action`3<TArg_REF, TKey_REF, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Diagnostics.DiagnosticData>>,TArg_REF,System.Threading.CancellationToken) [0x00063] in <c687f5f16d954d66b706836583783302>:0
  at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectState/<TryDeserializeDocumentAsync>d__25.MoveNext () [0x0005d] in <c687f5f16d954d66b706836583783302>:0
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<bool>.Start<Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectState/<TryDeserializeDocumentAsync>d__25> (Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectState/<TryDeserializeDocumentAsync>d__25&) [0x0002c] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471
  at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectState.TryDeserializeDocumentAsync (Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticDataSerializer,Microsoft.CodeAnalysis.Document,Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectState/Builder,System.Threading.CancellationToken) [0x00048] in <c687f5f16d954d66b706836583783302>:0
  at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectState/<LoadInitialAnalysisDataAsync>d__17.MoveNext () [0x00110] in <c687f5f16d954d66b706836583783302>:0
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResult>.Start<Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectState/<LoadInitialAnalysisDataAsync>d__17> (Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectState/<LoadInitialAnalysisDataAsync>d__17&) [0x0002c] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471
  at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectState.LoadInitialAnalysisDataAsync (Microsoft.CodeAnalysis.Project,System.Threading.CancellationToken) [0x00037] in <c687f5f16d954d66b706836583783302>:0
  at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectState/<GetAnalysisDataAsync>d__9.MoveNext () [0x0006b] in <c687f5f16d954d66b706836583783302>:0
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<Microsoft.CodeAnalysis.Workspaces.Diagnostics.DiagnosticAnalysisResult>.Start<Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectState/<GetAnalysisDataAsync>d__9> (Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectState/<GetAnalysisDataAsync>d__9&) [0x0002c] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471
  at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectState.GetAnalysisDataAsync (Microsoft.CodeAnalysis.Project,bool,System.Threading.CancellationToken) [0x0003f] in <c687f5f16d954d66b706836583783302>:0
  at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectAnalysisData/<CreateAsync>d__9.MoveNext () [0x00074] in <c687f5f16d954d66b706836583783302>:0
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectAnalysisData>.Start<Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectAnalysisData/<CreateAsync>d__9> (Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectAnalysisData/<CreateAsync>d__9&) [0x0002c] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471
  at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectAnalysisData.CreateAsync (Microsoft.CodeAnalysis.Project,System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/StateSet>,bool,System.Threading.CancellationToken) [0x0003f] in <c687f5f16d954d66b706836583783302>:0
  at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/Executor/<GetProjectAnalysisDataAsync>d__4.MoveNext () [0x000f5] in <c687f5f16d954d66b706836583783302>:0
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/ProjectAnalysisData>.Start<Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/Executor/<GetProjectAnalysisDataAsync>d__4> (Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/Executor/<GetProjectAnalysisDataAsync>d__4&) [0x0002c] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471
  at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/Executor.GetProjectAnalysisDataAsync (Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers,Microsoft.CodeAnalysis.Project,System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/StateSet>,bool,System.Threading.CancellationToken) [0x00051] in <c687f5f16d954d66b706836583783302>:0
  at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/<AnalyzeProjectAsync>d__84.MoveNext () [0x00168] in <c687f5f16d954d66b706836583783302>:0
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/<AnalyzeProjectAsync>d__84> (Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer/<AnalyzeProjectAsync>d__84&) [0x0002c] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:316
  at Microsoft.CodeAnalysis.Diagnostics.EngineV2.DiagnosticIncrementalAnalyzer.AnalyzeProjectAsync (Microsoft.CodeAnalysis.Project,bool,Microsoft.CodeAnalysis.SolutionCrawler.InvocationReasons,System.Threading.CancellationToken) [0x00038] in <c687f5f16d954d66b706836583783302>:0
  at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService/WorkCoordinator/IncrementalAnalyzerProcessor/LowPriorityProcessor/<>c__DisplayClass11_0.<ProcessProjectAsync>b__0 (Microsoft.CodeAnalysis.SolutionCrawler.IIncrementalAnalyzer,Microsoft.CodeAnalysis.Project,System.Threading.CancellationToken) [0x0000f] in <c687f5f16d954d66b706836583783302>:0
  at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService/WorkCoordinator/IncrementalAnalyzerProcessor/<>c__DisplayClass32_1`1/<<RunAnalyzersAsync>b__0>d<T_REF>.MoveNext () [0x0002e] in <c687f5f16d954d66b706836583783302>:0
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<object>.Start<Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService/WorkCoordinator/IncrementalAnalyzerProcessor/<>c__DisplayClass32_1`1/<<RunAnalyzersAsync>b__0>d<Microsoft.CodeAnalysis.Project>> (Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService/WorkCoordinator/IncrementalAnalyzerProcessor/<>c__DisplayClass32_1`1/<<RunAnalyzersAsync>b__0>d<Microsoft.CodeAnalysis.Project>&) [0x0002c] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471
  at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService/WorkCoordinator/IncrementalAnalyzerProcessor/<>c__DisplayClass32_1`1<T_REF>.<RunAnalyzersAsync>b__0 (T_REF,System.Threading.CancellationToken) [0x00037] in <c687f5f16d954d66b706836583783302>:0
  at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService/WorkCoordinator/IncrementalAnalyzerProcessor/<GetOrDefaultAsync>d__34`2<TData_REF, TResult_REF>.MoveNext () [0x0001f] in <c687f5f16d954d66b706836583783302>:0
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<object>.Start<Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService/WorkCoordinator/IncrementalAnalyzerProcessor/<GetOrDefaultAsync>d__34`2<Microsoft.CodeAnalysis.Project, object>> (Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService/WorkCoordinator/IncrementalAnalyzerProcessor/<GetOrDefaultAsync>d__34`2<Microsoft.CodeAnalysis.Project, object>&) [0x0002c] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:471
  at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService/WorkCoordinator/IncrementalAnalyzerProcessor.GetOrDefaultAsync<TData_REF, TResult_REF> (TData_REF,System.Func`3<TData_REF, System.Threading.CancellationToken, System.Threading.Tasks.Task`1<TResult_REF>>,System.Threading.CancellationToken) [0x00037] in <c687f5f16d954d66b706836583783302>:0
  at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService/WorkCoordinator/IncrementalAnalyzerProcessor/<RunAnalyzersAsync>d__32`1<T_REF>.MoveNext () [0x0009b] in <c687f5f16d954d66b706836583783302>:0
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService/WorkCoordinator/IncrementalAnalyzerProcessor/<RunAnalyzersAsync>d__32`1<Microsoft.CodeAnalysis.Project>> (Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService/WorkCoordinator/IncrementalAnalyzerProcessor/<RunAnalyzersAsync>d__32`1<Microsoft.CodeAnalysis.Project>&) [0x0002c] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:316
  at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService/WorkCoordinator/IncrementalAnalyzerProcessor.RunAnalyzersAsync<T_REF> (System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.SolutionCrawler.IIncrementalAnalyzer>,T_REF,System.Func`4<Microsoft.CodeAnalysis.SolutionCrawler.IIncrementalAnalyzer, T_REF, System.Threading.CancellationToken, System.Threading.Tasks.Task>,System.Threading.CancellationToken) [0x0003f] in <c687f5f16d954d66b706836583783302>:0
  at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService/WorkCoordinator/IncrementalAnalyzerProcessor/LowPriorityProcessor/<ProcessProjectAsync>d__11.MoveNext () [0x00110] in <c687f5f16d954d66b706836583783302>:0
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService/WorkCoordinator/IncrementalAnalyzerProcessor/LowPriorityProcessor/<ProcessProjectAsync>d__11> (Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService/WorkCoordinator/IncrementalAnalyzerProcessor/LowPriorityProcessor/<ProcessProjectAsync>d__11&) [0x0002c] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:316
  at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService/WorkCoordinator/IncrementalAnalyzerProcessor/LowPriorityProcessor.ProcessProjectAsync (System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.SolutionCrawler.IIncrementalAnalyzer>,Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService/WorkCoordinator/WorkItem,System.Threading.CancellationTokenSource) [0x0003f] in <c687f5f16d954d66b706836583783302>:0
  at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService/WorkCoordinator/IncrementalAnalyzerProcessor/LowPriorityProcessor/<ExecuteAsync>d__3.MoveNext () [0x000c0] in <c687f5f16d954d66b706836583783302>:0
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService/WorkCoordinator/IncrementalAnalyzerProcessor/LowPriorityProcessor/<ExecuteAsync>d__3> (Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService/WorkCoordinator/IncrementalAnalyzerProcessor/LowPriorityProcessor/<ExecuteAsync>d__3&) [0x0002c] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:316
  at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService/WorkCoordinator/IncrementalAnalyzerProcessor/LowPriorityProcessor.ExecuteAsync () [0x00027] in <c687f5f16d954d66b706836583783302>:0
  at Microsoft.CodeAnalysis.SolutionCrawler.IdleProcessor/<ProcessAsync>d__12.MoveNext () [0x0012f] in <c687f5f16d954d66b706836583783302>:0
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner.InvokeMoveNext (object) [0x00000] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1089
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00071] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:957
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00000] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:904
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner.Run () [0x00024] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1070
  at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction (System.Action,bool,System.Threading.Tasks.Task&) [0x0001c] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:823
  at System.Threading.Tasks.Task.FinishContinuations () [0x00068] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:3631
  at System.Threading.Tasks.Task.FinishStageThree () [0x0003c] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2373
  at System.Threading.Tasks.Task`1<System.Threading.Tasks.VoidTaskResult>.TrySetResult (System.Threading.Tasks.VoidTaskResult) [0x0004f] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Future.cs:488
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<System.Threading.Tasks.VoidTaskResult>.SetResult (System.Threading.Tasks.VoidTaskResult) [0x0003e] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:608
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<System.Threading.Tasks.VoidTaskResult>.SetResult (System.Threading.Tasks.Task`1<System.Threading.Tasks.VoidTaskResult>) [0x00010] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:636
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult () [0x00000] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:378
  at Microsoft.CodeAnalysis.SolutionCrawler.IdleProcessor/<WaitForIdleAsync>d__11.MoveNext () [0x000ec] in <c687f5f16d954d66b706836583783302>:0
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner.InvokeMoveNext (object) [0x00000] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1089
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00071] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:957
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00000] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:904
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore/MoveNextRunner.Run () [0x00024] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1070
  at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction (System.Action,bool,System.Threading.Tasks.Task&) [0x0001c] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:823
  at System.Threading.Tasks.Task.FinishContinuations () [0x00068] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:3631
  at System.Threading.Tasks.Task.FinishStageThree () [0x0003c] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2373
  at System.Threading.Tasks.Task`1<System.Threading.Tasks.VoidTaskResult>.TrySetResult (System.Threading.Tasks.VoidTaskResult) [0x0004f] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Future.cs:488
  at System.Threading.Tasks.Task/DelayPromise.Complete () [0x00045] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:5962
  at System.Threading.Tasks.Task/<>c.<Delay>b__276_1 (object) [0x00000] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:5916
  at System.Threading.Timer/Scheduler.TimerCB (object) [0x00007] in /home/mkrueger/work/install/mono/mcs/class/corlib/System.Threading/Timer.cs:327
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00015] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1279
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:856
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in /home/mkrueger/work/install/mono/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1211
  at (wrapper runtime-invoke) <Module>.runtime_invoke_bool (object,intptr,intptr,intptr) [0x0001f] in <0f34c28ae3cf4341a062f0b0237f7ae9>:0
```

**Expected Behavior**:
The sqlite storage service should not probe again and again if the native library can't be resolved.

**Actual Behavior**:
Slows down CPU, as it tries to re-create the database on every database operation and failing.

Possible fix:
If the exception is something like `DllNotFoundException`, it might be ok to return NOOP storage on subsequent tries.

### PR DESCRIPTION
**Pull request by Therzok**
The static constructor of SQLitePersistentStorage would throw an
exception, which would then get logged by the exception logger.

This changes the following logic:

* Don't delete the database if e_sqlite is not found.
* Disable persistent storage if e_sqlite is not found.
* Releases the db ownership lock if e_sqlite is not found.

Fixes #24042

Extra story:
There is a architectures of e_sqlite not existing for some platforms,
i.e. ARM64. Therefore, in MonoDevelop, it would throw a
TypeInitializationException on trying to initialize the SQLitePersistentStorage.

In this case, what would happen is:
* The persistent storage service would create the lock file.
* It would throw in the static constructor, without having passed
ownership
* Thus, the lock file is created by the service, not held by anyone
specifically
* The exception wasn't accounted for, so the storage file would be
deleted
* We now have a lock file present and no storage created
* Roslyn will keep trying to create the persistent storage on every
subsequent try, ending up in a performance issue caused by continuous
IO on trying to get ownership on the lock file, but it can't take it
because nobody released the old lock

Therefore, shortcircuiting and disabling persistent storage in case the
lib is not found is better.

<details><summary>Ask Mode template not completed</summary>

### Customer scenario

What does the customer do to get into this situation, and why do we think this
is common enough to address for this release.  (Granted, sometimes this will be
obvious "Open project, VS crashes" but in general, I need to understand how
common a scenario is)

### Bugs this fixes

(either VSO or GitHub links)

### Workarounds, if any

Also, why we think they are insufficient for RC vs. RC2, RC3, or RTW

### Risk

This is generally a measure our how central the affected code is to adjacent
scenarios and thus how likely your fix is to destabilize a broader area of code

### Performance impact

(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")

### Root cause analysis

How did we miss it?  What tests are we adding to guard against it in the future?

### How was the bug found?

(E.g. customer reported it vs. ad hoc testing)

### Test documentation updated?

If this is a new non-compiler feature or a significant improvement to an existing feature, update https://github.com/dotnet/roslyn/wiki/Manual-Testing once you know which release it is targeting.

</details>

### CODE REVIEW

**Comment by Therzok** [comment]
cc @sharwell @CyrusNajmabadi 👀 

@jasonmalinowski is there a way to get nupkgs for this PR so I can test this locally?

File: src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs [hunk 1]
```diff
@@ -64,6 +64,13 @@ protected override string GetDatabaseFilePath(string workingFolderPath)
                 sqlStorage.Initialize(solution);
 
             }
+            catch (Exception ex) when (ex is DllNotFoundException || ex is EntryPointNotFoundException)
```
Comment (Therzok) [inline src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: Need to catch TypeInitializationException and check InnerException for the data and throw that

File: src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs [hunk 2]
```diff
@@ -64,6 +64,14 @@ protected override string GetDatabaseFilePath(string workingFolderPath)
                 sqlStorage.Initialize(solution);
 
             }
+            catch (TypeInitializationException ex) when (ex.InnerException is DllNotFoundException || ex.InnerException is EntryPointNotFoundException)
+            {
+                // Probing for e_sqlite3 failed, so manually dispose the ownership lock as
+                // sqlStorage was not instantiated yet, due to an exception in the static constructor.
+                dbOwnershipLock.Dispose();
+                DisableStorage();
+                throw ex.InnerException;
```
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: ❓ Why not just `throw;` here?

Comment (Therzok) [reply src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: The exception thrown from here propagates into `ShouldDeleteDatabase`, via here:
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces.Desktop/Workspace/Storage/AbstractPersistentStorageService.cs,184

Maybe `throw;` is the better option here, and the check in `ShouldDeleteDatabase` should be done for TypeInitializationException and its inner exception.

Comment (Therzok) [reply src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: We're masking an exception and changing its stacktrace, so yes, I'll fix this.

Comment (sharwell) [reply src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: 💭 It seems like the less risky change in the absence of a need to drop the outer exception.

Comment (Therzok) [reply src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: Fixed.

File: src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs [hunk 3]
```diff
@@ -98,10 +114,23 @@ private static void EnsureDirectory(string databaseFilePath)
             Directory.CreateDirectory(directory);
         }
 
+        static bool IsNativeLibraryResolutionException(Exception ex)
```
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: :bulb: Missing access modifier (will send PR to add code style rule so this is more apparent)

File: src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs [hunk 4]
```diff
@@ -98,10 +114,23 @@ private static void EnsureDirectory(string databaseFilePath)
...
+        {
+            // Check for a type initialization exception as this can be thrown in the static constructor
+            // of SQLiteStorage.
+            if (ex is TypeInitializationException typeInitializationException)
+            {
+                ex = typeInitializationException.InnerException;
+            }
+
+            return exception is DllNotFoundException || exception is EntryPointNotFoundException;
```
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: ❗️ ~~`exception`~~ `ex`

File: src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs [hunk 5]
```diff
@@ -64,9 +64,29 @@ protected override string GetDatabaseFilePath(string workingFolderPath)
                 sqlStorage.Initialize(solution);
 
             }
-            catch (Exception)
+            catch (Exception exception)
             {
-                sqlStorage?.Dispose();
+                if (IsNativeLibraryResolutionException(exception))
```
Comment (heejaechang) [inline src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: rather than doing this way, can we add explicit check for those dependencies? basically, rather than doing this implicitly through static constructor (http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces.Desktop/Workspace/SQLite/SQLitePersistentStorage.cs,96)

make an explicit static API for it such as bool SQLitePersistentStorage.InitLibraries(). which will run the LoadLibrary once and cache the result. and next time it is called, if it just return true or false.

and in TryOpenDatabase, before TryGetDatabaseOwnership, it calls SQLitePersistentStorage.InitiLibrary and if that return false, return storage = null and return false like what dbOwnershipLock does.

I think that is more explicit check and follow pattern already in this method.

...

if you are worry about same thing repeatedly get called, then, I think that check should move up to here.
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces.Desktop/Workspace/Storage/PersistenceStorageServiceFactory.cs,24

since the condition where that LoadLibrary will fail is process wide, not per workspace or solution. the factory itself should check such condition and return 
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Host/PersistentStorage/NoOpPersistentStorageService.cs,0ec32e8cdd068f49

since in the process, SQLite will be never supported.

Comment (Therzok) [reply src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: Yeah, that's a better solution. This PR ended up being bigger than I initially imagined 😛 

I'll open a PR writing it way.

**Comment by Therzok** [comment]
This came up so testing doesn't work
```
error MSB6002: The command-line for the "CreatePkgDef" task is too long. Command-lines longer than 32000 characters are likely to fail. Try reducing the length of the command-line by breaking down the call to "CreatePkgDef" into multiple calls with fewer parameters per call. [D:\j\workspace\windows_relea---233a1cda\src\VisualStudio\IntegrationTest\TestSetup\VisualStudioIntegrationTestSetup.csproj]
```

**Comment by Therzok** [comment]
Hmmm, so I think I'm hitting a rather peculiar bug right now. It seems to say that it can't probe for e_sqlite.dll in either x86/x64 dir relative to the workspaces.dll, but that should definitely be copied over.

Any help here? I don't really understand how this could've passed before, except for a hidden exception in FatalError/DatabaseLogger

**Comment by Therzok** [comment]
Ah, I think I figured it out.

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure is our jenkins currently having some issues?

File: src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs [hunk 6]
```diff
@@ -66,7 +104,17 @@ protected override string GetDatabaseFilePath(string workingFolderPath)
             }
             catch (Exception)
             {
-                sqlStorage?.Dispose();
+                if (sqlStorage != null)
```
Comment (heejaechang) [inline src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: if exception was thrown, shouldn't we always dispose the owner lock?

File: src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs [hunk 7]
```diff
@@ -100,7 +148,7 @@ private static void EnsureDirectory(string databaseFilePath)
 
         protected override bool ShouldDeleteDatabase(Exception exception)
```
Comment (heejaechang) [inline src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: nit: convert to => ?

File: src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs (hunk 6 above)
Comment (heejaechang) [reply src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: ah. just realized that the dispose of the storage will dispose the lock. sorry about that.

**Comment by jinujoseph** [comment]
@Pilchie for ask mode approval for 15.7 preview 4

**Comment by Pilchie** [comment]
Approved - pending passing unit test runs...

**Comment by Therzok** [comment]
Rebasing again hoping they pass...

**Comment by sharwell** [comment]
@Therzok Looks like the 64-bit tests have a legitimate failure

File: src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs [hunk 8]
```diff
@@ -19,6 +20,59 @@ internal partial class SQLitePersistentStorageService : AbstractPersistentStorag
...
+        internal static bool TryInitializeLibraries()
+        {
+            if (_initialized)
+            {
+                return true;
+            }
+                
+            lock (_gate)
+            {
+                if (_initialized)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: please don't do double checked locking.  i still don't trust that .net has a consistent story around reordered writes and whatnot to make this safe.  It's trivial, and no perf problem, to just take the lock and do the check.

File: src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs [hunk 9]
```diff
@@ -19,6 +20,59 @@ internal partial class SQLitePersistentStorageService : AbstractPersistentStorag
 
         private readonly IPersistentStorageFaultInjector _faultInjectorOpt;
 
+        [DllImport("kernel32.dll")]
+        private static extern IntPtr LoadLibrary(string dllToLoad);
+        private static bool _initialized;
+        private static object _gate = new object();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: it might make a lot of sense to extract all this code related to laoding sqlite and put it in its own class.  The class would expose almost nothing except a bit saying if you can use sqlite or not.  You would never have to care or look for exceptions relating to asking the question in teh first place if you can use it.

File: src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs [hunk 10]
```diff
@@ -19,6 +20,59 @@ internal partial class SQLitePersistentStorageService : AbstractPersistentStorag
...
+            {
+                return true;
+            }
+                
+            lock (_gate)
+            {
+                if (_initialized)
+                {
+                    return true;
+                }
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: i feel like the momeent after checking, we should set _initialized to true, so we never execute this block more than once.

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: Instead of just returning 'true', i feel a better API would be to have it actually have a different bool stating if we actually initialized properly or not.  (Alternatively, use a ```bool?``` where 'null' means 'have not computed', and non-null is the actual value.)

File: src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs [hunk 11]
```diff
@@ -19,6 +20,59 @@ internal partial class SQLitePersistentStorageService : AbstractPersistentStorag
...
+
+                try
+                {
+                    // Necessary to initialize SQLitePCL.
+                    SQLitePCL.Batteries_V2.Init();
+                }
+                catch (Exception e) when (e is DllNotFoundException || e is EntryPointNotFoundException)
+                {
+                    StorageDatabaseLogger.LogException(e);
+                    return false;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: i really dislike that we haven't marked _iniitialized here.  so this can just be hit over and over again.

File: src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs [hunk 12]
```diff
@@ -66,7 +120,17 @@ protected override string GetDatabaseFilePath(string workingFolderPath)
             }
             catch (Exception)
             {
-                sqlStorage?.Dispose();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: i feel like, at the top of this method, we would see in the first place if we had been able to load sqlite.  And, if not, we wouldn't do *any* work.  no need for locks, exception handling, and wahtnot in that case.  Basically, we shouldn't even be trying this complex logic if we can't even get at sqlite in the first place.

File: src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs (hunk 8 above)
Comment (Therzok) [reply src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: Oh, this part was just for testing. This is not needed after all.

File: src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs (hunk 11 above)
Comment (Therzok) [reply src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: This was just to test whether unit tests passed with this. I used to have a `Lazy<bool>` in an earlier version, but that broke unit tests in the same way they are broken now.

File: src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs (hunk 12 above)
Comment (Therzok) [reply src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: This isn't even called if we haven't been able to load sqlite.

Comment (heejaechang) [reply src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: @Therzok the tests probably are failing because some unrelated tests ran before the Sqlite tests and set the static field to false and Sqlite tests are bailing out due to the static field already being set as false.

I bet before, except Sqlite tests, other conditions made Sqlite service to bail out before creating SqliteStorage (so no static ctor get called) and let the tests to actually run.

...

I think either you take out Sqlite persistent service out from default test MEF so that only SQLite test uses real Sqlite persistent service, or addin test checking code somewhere.

Comment (heejaechang) [reply src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: or you don't save the flag as you did :) that will work as well.

**Comment by heejaechang** [comment]
@Therzok alright, test is still failing. so I looked through tests. looks like Sqlite tests by pass Factory and create Sqlite service directly. so there is no one who initialize sqlite. I think that is why your test is failing.

put the initialize in here
http://source.roslyn.io/#Roslyn.VisualStudio.CSharp.UnitTests/PersistentStorage/SQLitePersistentStorageTests.cs,18

you probably can add it as static ctor of the test. and I think you can put back the flag to make it not run twice if you want to. looks like test MEF doesn't include Sqlite service so static flag shouldn't be a problem.

**Comment by Therzok** [comment]
Omg, thanks! I missed that! Will fix!

File: src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs [hunk 13]
```diff
@@ -19,6 +20,47 @@ internal partial class SQLitePersistentStorageService : AbstractPersistentStorag
 
         private readonly IPersistentStorageFaultInjector _faultInjectorOpt;
 
+        [DllImport("kernel32.dll")]
+        private static extern IntPtr LoadLibrary(string dllToLoad);
+
+        internal static bool TryInitializeLibraries() => _initialized.Value;
+
+        private static Lazy<bool> _initialized = new Lazy<bool>(() => TryInitializeLibrariesLazy());
```
Comment (heejaechang) [inline src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorageService.cs]: readonly and s_initialized

**Comment by Therzok** [comment]
Thanks!
