### PR TITLE
ExpressionVariableFinder should properly handle misplaces DeclarationExpressions with ParenthesizedVariableDesignation.

### LINKED ISSUE #17572: VS crashes when typing valid deconstructing declaration
Uncomment the second line in the following code to crash VS 2017 RC4

```cs
  class Program
  {
    static void Main(string[] args)
    {
       (var (a,b), var c) = ((1,2),3); // this line compiles
    // (var (a,b), var c)
    }
```

This is rather unfortunate as this could be a start of some valid syntax construct as demonstrated by the first line.

vscrash

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #17572.
This change also ensures consistent SemanticModel behavior between valid and invalid usages of DeclarationExpressions.

@dotnet/roslyn-compiler Please review.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/DeconstructionTests.cs [hunk 1]
```diff
@@ -2790,5 +2790,879 @@ static void Main()
...
+        public void StandAlone_09()
+        {
+            string source1 = @"
+using al = System.Int32;
+
+class C
+{
+    static void Main()
+    {
+        (al (a,b), al c);
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/DeconstructionTests.cs]: This is likely to parse as an invocation of a method `al`.

File: src/Compilers/CSharp/Test/Semantic/Semantics/DeconstructionTests.cs [hunk 2]
```diff
@@ -2790,5 +2790,879 @@ static void Main()
...
+            var d = model.GetDeclaredSymbol(designations[3]);
+            Assert.Equal("System.Int32 d", d.ToTestDisplayString());
+            Assert.Equal(localDeclarationKind, ((LocalSymbol)d).DeclarationKind);
+
+            var declarations = tree.GetCompilationUnitRoot().DescendantNodes().OfType<DeclarationExpressionSyntax>().ToArray();
+            Assert.Equal(3, declarations.Count());
+
+            Assert.Equal("var (a,b)", declarations[0].ToString());
+            var typeInfo = model.GetTypeInfo(declarations[0]);
+            Assert.Equal("(var, var)", typeInfo.Type.ToTestDisplayString());
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/DeconstructionTests.cs]: Whoa! This surprised me (but it makes sense).

File: src/Compilers/CSharp/Test/Semantic/Semantics/DeconstructionTests.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/DeconstructionTests.cs]: Yes, it is parsed like that today.

**Comment by AlekseyTs** [comment]
> Are the changes herein only intended to test support for declaration expressions in tuples in a statement expression? Or does the underlying issue arise even when the tuple containing a declaration expression is in another context?

I believe the fix is not specific to declaration expressions contained in a tuple. I would expect it to handle misplaces DeclarationExpressions with ParenthesizedVariableDesignation in other contexts as well, assuming ExpressionVariableFinder visits them.

**Comment by gafter** [comment]
> I believe the fix is not specific to declaration expressions contained in a tuple. I would expect it to handle misplaces DeclarationExpressions with ParenthesizedVariableDesignation in other contexts as well, assuming ExpressionVariableFinder visits them.

We should have tests for those other scenarios, as well as tests for scenarios in a tuple that is somewhere other than a top-level expression in an expression-statement.

**Comment by AlekseyTs** [comment]
@gafter 

>  as well as tests for scenarios in a tuple that is somewhere other than a top-level expression

Neither the root cause analysis for the issue being addressed, nor the nature of the fix makes me to believe that the depth of nesting is material to verifying correctness of the fix. Nevertheless, in the spirit of "more tests is better than less tests", I added tests for scenarios with DeclarationExpressions not at the top level.  

> We should have tests for those other scenarios

Completely agree with that sentiment. However, it is not a goal of this PR to perform discovery testing or close test gaps that might exist around DeclarationExpressions in general. As one of the designers behind the DeclarationExpression nodes and as the developer owning the recent changes in the parser around these nodes, you are the most qualified person on the team to identify possible test gaps in this area. If you believe such gaps exist, please open dedicated issue(s), identifying specific scenarios that lack test coverage.

**Comment by AlekseyTs** [comment]
@cston, @jaredpar, @VSadov Please review if you have time, I need a second sign-off.

**Comment by cston** [comment]
LGTM
