### PR TITLE
Don't emit casing-related naming violations when the violating character has no casing (making the feature noisy/unusable in other cultures)

### LINKED ISSUE #15326: Naming style "require uppercase" doesn't allow numerics or non-Latin characters
From: https://developercommunity.visualstudio.com/content/problem/2440/uppercase-naming-with-number.html

```C#
internal enum ButtonState : uint
{
    FROM_LEFT_1ST_BUTTON_PRESSED = 0x01,
    RIGHTMOST_BUTTON_PRESSED = 0x02,
    FROM_LEFT_2ND_BUTTON_PRESSED = 0x04,
    FROM_LEFT_3RD_BUTTON_PRESSED = 0x08,
    FROM_LEFT_4TH_BUTTON_PRESSED = 0x10
}
```

All of the enums that contain a number 1,2,3,4 fail the naming convention of uppercase.  Is there anyway to configure naming to force uppercase and allow numbers?

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #15326, #15486

Escrow Template
================

**Customer scenario**: A Japanese user (for example) has the default Naming Styles applied but uses an identifier where the first character is neither upper-case nor lower-case. We currently flag this as a violation of that Naming Style. Note that this will be their default experience out-of-the-box.

**Bugs this fixes:** #15326, #15486

**Workarounds, if any:** They can manually turn off all Naming Rules.

**Risk**: Low. We just add a check to see if the character being inspected has casing at all to 4 different places. This is specific to the Naming Styles feature, and nothing else relies on this code.

**Performance impact**: For the more common naming styles, it can create an additional struct per symbol (the .ToUpper or .ToLower'd version of the first character). For the less common naming styles, it can create an additional struct per character in each symbol analyzed.

**Is this a regression from a previous update?** No.

**Root cause analysis:** It was missed as part of the original feature work. There are unit tests to validate and protect against regressions.

**How was the bug found?** Customer reports and dogfooding.

### CODE REVIEW

**Comment by dpoeschl** [comment]
This change will eventually be included in a larger PR, but it can be reviewed independently. Tagging @dotnet/roslyn-ide @jmarolf @davkean for review.

File: src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs [hunk 1]
```diff
@@ -264,6 +264,11 @@ private bool CheckFirstUpper(string name, TextSpan nameSpan, out string reason)
                 WorkspacesResources.These_non_leading_words_must_begin_with_a_lowercase_letter_colon_0,
                 out reason);
 
+        private static bool DoesCharacterHaveCasing(char c)
+        {
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs]: =>

**Comment by CyrusNajmabadi** [comment]
👍

**Comment by dpoeschl** [comment]
Tagging @MattGertz for Escrow consideration.

**Comment by MattGertz** [comment]
Blocker for alphabets with no concept of upper/lower case.

**Comment by dpoeschl** [comment]
@natidea I've filed https://devdiv.visualstudio.com/DevDiv/_workitems?id=370237&fullScreen=false&_a=edit to track this. Can you verify that it looks okay and will show up in the shiproom query?

**Comment by natidea** [comment]
Approved to merge via [370237](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/370237)

File: src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs [hunk 2]
```diff
@@ -264,6 +264,8 @@ private bool CheckFirstUpper(string name, TextSpan nameSpan, out string reason)
                 WorkspacesResources.These_non_leading_words_must_begin_with_a_lowercase_letter_colon_0,
                 out reason);
 
+        private static bool DoesCharacterHaveCasing(char c) => char.ToLower(c) != char.ToUpper(c);
```
Comment (miloush) [inline src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs]: Wouldn't char.IsLower(c) != char.IsUpper(c) be faster?

Comment (miloush) [inline src/Workspaces/Core/Portable/NamingStyles/NamingStyle.cs]: Wouldn't char.IsLower(c) != char.IsUpper(c) be faster?
