### PR TITLE
Handle CodeFix with bad ImmutableArray

### LINKED ISSUE #2002: we should log non-fatal watson when extension throws an exception
we need at least to do that for our own ones such as code fixer, code refactoring and etc.

### PR DESCRIPTION
**Pull request by jmarolf**
Check IsDefaultOrEmpty of any ImmutableArray given for FixableDiagnosticIds, to ensure that it has been properly initialized.
Throw and ArgumentException to let the user know to fix their CodeFixer.
Fixes #2002

### CODE REVIEW

**Comment by jmarolf** [comment]
Reviewers: @balajikris, @brettfo, @CyrusNajmabadi, @davkean, @dpoeschl, @jasonmalinowski, @DustinCampbell, @Pilchie, @rchande

File: src/Features/Core/Portable/CodeFixes/CodeFixService.cs [hunk 1]
```diff
@@ -430,6 +430,16 @@ private ImmutableArray<DiagnosticId> GetFixableDiagnosticIds(CodeFixProvider fix
             }
         }
 
+        private ImmutableArray<string> GetAndTestFixableDiagnosticIds(CodeFixProvider f)
+        {
+            var ids = f.FixableDiagnosticIds;
+            if(ids.IsDefaultOrEmpty)
```
Comment (brettfo) [inline src/Features/Core/Portable/CodeFixes/CodeFixService.cs]: space

File: src/Features/Core/Portable/CodeFixes/CodeFixService.cs [hunk 2]
```diff
@@ -430,6 +430,16 @@ private ImmutableArray<DiagnosticId> GetFixableDiagnosticIds(CodeFixProvider fix
...
+            {
+                throw new ArgumentException(WorkspacesResources.ImmutableArrayIncorrectlyInitialized, "FixableDiagnosticIds");
```
Comment (brettfo) [inline src/Features/Core/Portable/CodeFixes/CodeFixService.cs]: nameof()

File: src/Features/Core/Portable/CodeFixes/CodeFixService.cs [hunk 3]
```diff
@@ -430,6 +430,16 @@ private ImmutableArray<DiagnosticId> GetFixableDiagnosticIds(CodeFixProvider fix
...
+            }
```
Comment (brettfo) [inline src/Features/Core/Portable/CodeFixes/CodeFixService.cs]: newline after curly

**Comment by brettfo** [comment]
:shipit:

File: src/Workspaces/Core/Portable/WorkspacesResources.resx [hunk 4]
```diff
@@ -456,4 +456,7 @@
   <data name="Exceptions" xml:space="preserve">
     <value>Exceptions:</value>
   </data>
+  <data name="ImmutableArrayIncorrectlyInitialized" xml:space="preserve">
+    <value>ImmutableArray was incorrectly initialized, consider using ImmutableArray&lt;T&gt;.Empty</value>
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/WorkspacesResources.resx]: Don't you throw on 'Empty' as well? Shouldn't this be more like "DiagnosticIds cannot be null or empty"?

Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/WorkspacesResources.resx]: How does this get displayed to the user?

Comment (jmarolf) [inline src/Workspaces/Core/Portable/WorkspacesResources.resx]: @jasonmalinowski It is shown in Visual Studio as an adornment indicating that a codefix has been disabled for throwing an exception.  The activity log will contain the stack trace and exception that was thrown.

@CyrusNajmabadi Good point, I'll update the message.

**Comment by dpoeschl** [comment]
A couple thoughts:

1. This change can break existing, valid fixers. Imagine a fixer that decides what DiagnosticIds it can provide dynamically based on some static environment state, and in one case (say, on one particular domain/network, or on all-but-one OS, or ...) decides it cannot provide any value and so returns an empty array in that case. It may be unlikely, and it may not be the architecture you'd want (you may want them to do that in ```RegisterCodeFixesAsync``` instead), but it could exist currently, and this would break it. And if an entire *set* of fixers gets implemented that way, now you open a project and immediately get nailed with a bunch of (not-actually-problematic) failure notifications.
2. If we decide we can deal with the problems from 1 above, ```FixableDiagnosticIds``` would now be required to be non-empty, but the public API for it is not documented as such. These should stay in sync. **NOTE**: This mismatch also holds for ```DiagnosticAnalyzer.SupportedDiagnostics```, so we should probably fix the docs there too.

I support the idea of us throwing if the FixableDiagnosticIds (or, honestly, SupportedDiagnostics) is *inconsistent* over time, because that completely violates the contract. Not handling a consistently empty set of things seems like an unnecessary restriction on our part. Certainly the developer of the analyzer or fixer will have tested that something works on *their* machine, and them consistently offering to handle/provide nothing in any *individual* case is something our engine can easily deal with.

**Comment by jmarolf** [comment]
After talking this through with David at lunch, I think we should only throw for cases where ImmutableArray is incorrectly initialized.  There are valid cases where we may receive an empty ImmutableArray.

File: src/EditorFeatures/Test/CodeFixes/ErrorCases/CodeFixExceptionInFixableDiagnosticIds2.cs [hunk 5]
```diff
@@ -0,0 +1,20 @@
...
+using System.Collections.Immutable;
+using System.Composition;
+using System.Threading.Tasks;
+using Microsoft.CodeAnalysis.CodeFixes;
+
+namespace Microsoft.CodeAnalysis.Editor.UnitTests.CodeFixes.ErrorCases
+{
+    public class ExceptionInFixableDiagnosticIds2 : CodeFixProvider
+    {
+        public sealed override ImmutableArray<string> FixableDiagnosticIds => new ImmutableArray<string>();
```
Comment (sharwell) [inline src/EditorFeatures/Test/CodeFixes/ErrorCases/CodeFixExceptionInFixableDiagnosticIds2.cs]: :bulb: I would prefer this use `default(ImmutableArray<string>)` instead of `new ImmutableArray<string>()`.

File: src/Features/Core/Portable/CodeFixes/CodeFixService.cs [hunk 6]
```diff
@@ -408,13 +408,13 @@ private ImmutableArray<DiagnosticId> GetFixableDiagnosticIds(CodeFixProvider fix
...
                     fixer,
-                    () => ImmutableInterlocked.GetOrAdd(ref _fixerToFixableIdsMap, fixer, f => f.FixableDiagnosticIds),
+                    () => ImmutableInterlocked.GetOrAdd(ref _fixerToFixableIdsMap, fixer, GetAndTestFixableDiagnosticIds),
                     defaultValue: ImmutableArray<DiagnosticId>.Empty);
             }
 
             try
             {
-                return ImmutableInterlocked.GetOrAdd(ref _fixerToFixableIdsMap, fixer, f => f.FixableDiagnosticIds);
+                return ImmutableInterlocked.GetOrAdd(ref _fixerToFixableIdsMap, fixer, GetAndTestFixableDiagnosticIds);
```
Comment (sharwell) [inline src/Features/Core/Portable/CodeFixes/CodeFixService.cs]: :bulb: Consider using `f => GetAndTestFixableDiagnosticIds(f)` instead of just `GetAndTestFixableDiagnosticIds` so the delegate is cached.

File: src/Features/Core/Portable/CodeFixes/CodeFixService.cs [hunk 7]
```diff
@@ -408,13 +408,13 @@ private ImmutableArray<DiagnosticId> GetFixableDiagnosticIds(CodeFixProvider fix
             {
                 return extensionManager.PerformFunction(
                     fixer,
-                    () => ImmutableInterlocked.GetOrAdd(ref _fixerToFixableIdsMap, fixer, f => f.FixableDiagnosticIds),
+                    () => ImmutableInterlocked.GetOrAdd(ref _fixerToFixableIdsMap, fixer, GetAndTestFixableDiagnosticIds),
```
Comment (sharwell) [inline src/Features/Core/Portable/CodeFixes/CodeFixService.cs]: :bulb: Consider using `f => GetAndTestFixableDiagnosticIds(f)` instead of just `GetAndTestFixableDiagnosticIds` so the delegate is cached.

File: src/Features/Core/Portable/CodeFixes/CodeFixService.cs [hunk 8]
```diff
@@ -430,6 +430,17 @@ private ImmutableArray<DiagnosticId> GetFixableDiagnosticIds(CodeFixProvider fix
             }
         }
 
+        private ImmutableArray<string> GetAndTestFixableDiagnosticIds(CodeFixProvider f)
```
Comment (dpoeschl) [inline src/Features/Core/Portable/CodeFixes/CodeFixService.cs]: ugh, one-letter parameter names

File: src/Features/Core/Portable/CodeFixes/CodeFixService.cs [hunk 9]
```diff
@@ -430,6 +430,17 @@ private ImmutableArray<DiagnosticId> GetFixableDiagnosticIds(CodeFixProvider fix
...
+        {
+            var ids = f.FixableDiagnosticIds;
+            if (ids.IsDefault)
+            {
+                throw new ArgumentException(WorkspacesResources.FixableDiagnosticIdsIncorrectlyInitialized, nameof(f.FixableDiagnosticIds));
```
Comment (dpoeschl) [inline src/Features/Core/Portable/CodeFixes/CodeFixService.cs]: It's weird for the ArgumentException to have the ParamName of "FixableDiagnosticIds", which isn't a parameter name for this method or the caller above (GetFixableDiagnosticIds), right?

File: src/EditorFeatures/Test/CodeFixes/ErrorCases/CodeFixExceptionInFixableDiagnosticIds2.cs (hunk 5 above)
Comment (jmarolf) [inline src/EditorFeatures/Test/CodeFixes/ErrorCases/CodeFixExceptionInFixableDiagnosticIds2.cs]: This was written because I would expect people to accidentally call `new  ImmutableArray<string>()` expecting it to produce a valid `ImmutableArray<string>`.  In terms of the test why is `default(ImmutableArray<string>)` going to be superior?

File: src/Features/Core/Portable/CodeFixes/CodeFixService.cs (hunk 9 above)
Comment (sharwell) [inline src/Features/Core/Portable/CodeFixes/CodeFixService.cs]: I agree. I would recommend renaming `f` to `codeFixProvider`, and using `nameof(codeFixProvider)` for the exception.

File: src/Features/Core/Portable/CodeFixes/CodeFixService.cs [hunk 10]
```diff
@@ -430,6 +430,20 @@ private ImmutableArray<DiagnosticId> GetFixableDiagnosticIds(CodeFixProvider fix
...
 
+        private static ImmutableArray<string> GetAndTestFixableDiagnosticIds(CodeFixProvider codeFixProvider)
+        {
+            var ids = codeFixProvider.FixableDiagnosticIds;
+            if (ids.IsDefault)
+            {
+                throw new InvalidOperationException(
+                    string.Format(
+                        WorkspacesResources.FixableDiagnosticIdsIncorrectlyInitialized, 
+                        codeFixProvider.GetType().Name+ ".FixableDiagnosticIds"));
```
Comment (dpoeschl) [inline src/Features/Core/Portable/CodeFixes/CodeFixService.cs]: ```nameof(CodeFixProvider.FixableDiagnosticIds)```?

**Comment by dpoeschl** [comment]
:+1:

File: src/EditorFeatures/Test/CodeFixes/ErrorCases/CodeFixExceptionInFixableDiagnosticIds2.cs (hunk 5 above)
Comment (sharwell) [inline src/EditorFeatures/Test/CodeFixes/ErrorCases/CodeFixExceptionInFixableDiagnosticIds2.cs]: The test would still be doing that. However, as currently written it requires the reader to decipher the point of the test, which is to ensure that the handler throws an exception for `default(ImmutableArray<string>)` regardless of the manner/syntax in which that instance was obtained.

File: src/Workspaces/Core/Portable/WorkspacesResources.resx [hunk 11]
```diff
@@ -456,4 +456,7 @@
   <data name="Exceptions" xml:space="preserve">
     <value>Exceptions:</value>
   </data>
+  <data name="FixableDiagnosticIdsIncorrectlyInitialized" xml:space="preserve">
+    <value>{0} returned an uninitialized ImmutableArray</value>
```
Comment (Pilchie) [inline src/Workspaces/Core/Portable/WorkspacesResources.resx]: NitPick, but it's nice to put replacements like this into single quotes.

**Comment by Pilchie** [comment]
:+1:
