### PR TITLE
Respect current Environment.NewLine in MSBuild task

### LINKED ISSUE #24736: csc.dll exited with code 1
_From @ryanbrandenburg on February 9, 2018 19:58_

## Steps to reproduce
1. dotnet new mvc
2. Add `.AddFormatterMappings(m => {);` between `.AddMvc()` and `.SetCompatibilityVersion` in 'Startup.cs'.
3. dotnet run

## Expected  behavior
I would expect to get an informative error message about the mistakes I've just made (leaving off a trailing "}" and adding a ";", then trying to call `.SetCompatibilityVersion`.).

## Actual behavior
It returns:
```
/home/rybrande/dotnet/sdk/2.1.300-preview1-008030/Roslyn/Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.dll" exited with code 1. [/home/rybrande/functional/src/Fail/Fail.csproj]

The build failed. Please fix the build errors and run again.
```
with no other identifying or helpful information.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.300-preview1-008030)

Product Information:
 Version:            2.1.300-preview1-008030
 Commit SHA-1 hash:  be228a492f

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /home/rybrande/dotnet/sdk/2.1.300-preview1-008030/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26207-04
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153
```

Ubuntu 16.04

Found while doing aspnet/Release#215.

_Copied from original issue: dotnet/cli#8581_

### PR DESCRIPTION
**Pull request by rainersigwald**
The compiler server uses `WriteLine` to generate its output stream,
which uses the correct newlines for the current OS. When splitting
the string back into lines in the MSBuild task, though, the split
was done on Windows newlines.

Fixes #24736 by using `Environment.NewLine` instead of `\r\n` to
pass lines to MSBuild's logger, which expects errors one-per-line.

<details><summary>Ask Mode template not completed</summary>

### Customer scenario

What does the customer do to get into this situation, and why do we think this
is common enough to address for this release.  (Granted, sometimes this will be
obvious "Open project, VS crashes" but in general, I need to understand how
common a scenario is)

### Bugs this fixes

(either VSO or GitHub links)

### Workarounds, if any

Also, why we think they are insufficient for RC vs. RC2, RC3, or RTW

### Risk

This is generally a measure our how central the affected code is to adjacent
scenarios and thus how likely your fix is to destabilize a broader area of code

### Performance impact

(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")

### Root cause analysis

How did we miss it?  What tests are we adding to guard against it in the future?

### How was the bug found?

(E.g. customer reported it vs. ad hoc testing)

### Test documentation updated?

If this is a new non-compiler feature or a significant improvement to an existing feature, update https://github.com/dotnet/roslyn/wiki/Manual-Testing once you know which release it is targeting.

</details>

### CODE REVIEW

**Comment by agocke** [comment]
@rainersigwald Nice catch! So I presume what's going on here is that the output is being logged as a single blob of text instead of as individual errors. Since it looks like the errors would still have the right formatting, how is MSBuild deciding whether or not this is an error? Is it purely based on whether it's a multiline string or not?

File: src/Compilers/Core/MSBuildTask/ManagedCompiler.cs [hunk 1]
```diff
@@ -625,7 +625,7 @@ private void LogErrorOutput(string output)
 
         internal static void LogErrorOutput(string output, TaskLoggingHelper log)
         {
-            string[] lines = output.Split(new string[] { "\r\n" }, StringSplitOptions.RemoveEmptyEntries);
```
Comment (agocke) [inline src/Compilers/Core/MSBuildTask/ManagedCompiler.cs]: Can we just extract this into a protected readonly static and reference from both subclasses?

**Comment by agocke** [comment]
@jaredpar This probably affects the compiler server in 15.6.

**Comment by rainersigwald** [comment]
@agocke Right, the problem is that the compiler server hands a response including its "console output" back to the task, which logs it:

https://github.com/dotnet/roslyn/blob/0b63531a0478cfee685dae1c516fcb4e85f948c6/src/Compilers/Core/MSBuildTask/ManagedCompiler.cs#L592-L594

https://github.com/dotnet/roslyn/blob/0b63531a0478cfee685dae1c516fcb4e85f948c6/src/Compilers/Core/MSBuildTask/Csc.cs#L152-L161

The first argument to `LogMessageFromText` is `lineOfText`, though it doesn't appear to do any validation that it is in fact a single line.

https://github.com/Microsoft/msbuild/blob/6851538897f5d7b08024a6d8435bc44be5869e53/src/Shared/TaskLoggingHelper.cs#L1294

That gets passed to MSBuild's `CanonicalError.Parse` which strongly assumes a single line (but again doesn't bother to check that assumption).

Since the string return value doesn't match a CanonicalError (it starts with the csc version logo), it doesn't become an error and just gets logged as a message, which in the default CLI console verbosity doesn't get echoed.

File: src/Compilers/Core/MSBuildTask/ManagedCompiler.cs (hunk 1 above)
Comment (agocke) [reply src/Compilers/Core/MSBuildTask/ManagedCompiler.cs]: Never mind -- if we have to take this escrow, please keep the change as is.

**Comment by jaredpar** [comment]
@rainersigwald 

Thanks for the explanation. But as I'm reading it I'm still finding it hard to rationalize the behavior here. We've asked MSBuild to please log this message and MSbuild responded by neither logging nor throwing an exception.

**Comment by agocke** [comment]
@jaredpar I think it logged the message, but not as an *error*, which is why it didn't appear in a listing of errors, but did appear inline in the MSBuild log.

**Comment by agocke** [comment]
@rainersigwald Can we rebase this to 15.6.x? I think we'll have to take this bug through escrow.

**Comment by rainersigwald** [comment]
> I think it logged the message, but not as an error, which is why it didn't appear in a listing of errors, but did appear inline in the MSBuild log.

Exactly.

**Comment by jaredpar** [comment]
The goal here is to print an error. Is there an API we can use that will print the error (without having to worry about how MSBuild will interpret the string)?

File: src/Compilers/Core/MSBuildTask/ManagedCompiler.cs (hunk 1 above)
Comment (rainersigwald) [reply src/Compilers/Core/MSBuildTask/ManagedCompiler.cs]: whoops, force-pushing back to where it was

**Comment by rainersigwald** [comment]
> Is there an API we can use that will print the error (without having to worry about how MSBuild will interpret the string)?

Yes, you can `Log.LogError` as you do here:

https://github.com/dotnet/roslyn/blob/469fc641a6bafe92a81e1efae05ff8153906ee99/src/Compilers/Core/MSBuildTask/ManagedCompiler.cs#L626-L637

Note, though, that you _aren't_ printing an error. You're printing the "console output" of the compiler, including the logo, and depending on MSBuild's error parsing. It looks like that was an explicit decision, since there used to be an `ErrorOutput` field on the compiler server protocol but it is now not used:
https://github.com/dotnet/roslyn/blob/e8f0a191bc45fbe7c949338b6227af5f7ed8bece/src/Compilers/Core/CommandLine/BuildProtocol.cs#L396-L399

**Comment by rainersigwald** [comment]
@agocke Latest push has only the minimal change, without that refactoring. I was already using 15.6 as a base branch, just in case, so I updated the PR branch target.

**Comment by agocke** [comment]
@rainersigwald Thanks!

@MeiChin-Tsai FYI, this probably has to go through 15.6 escrow. I'm creating an escrow tracking bug right now.

**Comment by agocke** [comment]
@jaredpar I suspect we tried to eliminate the explicit error logging to avoid diverging code paths around error reporting between the compiler server and the client. Ironically, that probably would have prevented this bug.

**Comment by rainersigwald** [comment]
I tested a manual insertion of the task binary to a known-bad CLI (`2.1.300-preview1-008117`), and observed the expected errors on the command line:

```sh-session
$ /home/raines/src/roslyn/Binaries/Tools/dotnet/dotnet build --no-restore ~/src/roslyn/src/Compilers/Core/MSBuildTask/MSBuildTask.csproj /p:BuildProjectReferences=false && cp -v /home/raines/src/roslyn/Binaries/Debug/Dlls/MSBuildTask/Microsoft.Build.Tasks.CodeAnalysis.dll ~/Downloads/dotnet-sdk/sdk/2.1.300-preview1-008117/Roslyn/ && ~/Downloads/dotnet-sdk/dotnet build --no-restore /m:1 /flp:v=diag
Microsoft (R) Build Engine version 15.5.178.35674 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  MSBuildTask -> /home/raines/src/roslyn/Binaries/Debug/Dlls/MSBuildTask/Microsoft.Build.Tasks.CodeAnalysis.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.78
'/home/raines/src/roslyn/Binaries/Debug/Dlls/MSBuildTask/Microsoft.Build.Tasks.CodeAnalysis.dll' -> '/home/raines/Downloads/dotnet-sdk/sdk/2.1.300-preview1-008117/Roslyn/Microsoft.Build.Tasks.CodeAnalysis.dll'
Microsoft (R) Build Engine version 15.7.10.24921 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Program.cs(18,13): error CS0103: The name 'foo' does not exist in the current context [/home/raines/src/signalr-verification/signalr-verification.csproj]
Program.cs(18,13): error CS0201: Only assignment, call, increment, decrement, and new object expressions can be used as a statement [/home/raines/src/signalr-verification/signalr-verification.csproj]

Build FAILED.

Program.cs(18,13): error CS0103: The name 'foo' does not exist in the current context [/home/raines/src/signalr-verification/signalr-verification.csproj]
Program.cs(18,13): error CS0201: Only assignment, call, increment, decrement, and new object expressions can be used as a statement [/home/raines/src/signalr-verification/signalr-verification.csproj]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:04.00
```
