### PR TITLE
Lambdas in array initializers checked in nullable walker

### LINKED ISSUE #34299: Lambdas in array initializers not checked in nullable walker
The following proposed test fails.  The second warning is not produced.

``` c#
        [Fact, WorkItem(34299, "https://github.com/dotnet/roslyn/issues/34299")]
        public void CheckLambdaInArrayInitializer()
        {
            var source =
@"using System;

class C
{
    static void G(object? o)
    {
        Func<object> f = () => o; // possible null reference return
        var fa3 = new[] {
            f, // this defines the array element type as Func<object>
            () => o, // possible null reference return
            };
        fa3[0]().ToString();
    }
}
";
            var comp = CreateCompilation(new[] { source }, options: WithNonNullTypesTrue());
            comp.VerifyDiagnostics(
                // (7,32): warning CS8603: Possible null reference return.
                //         Func<object> f = () => o; // possible null reference return
                Diagnostic(ErrorCode.WRN_NullReferenceReturn, "o").WithLocation(7, 32),
                // (11,19): warning CS8603: Possible null reference return.
                //            () => o, // possible null reference return
                Diagnostic(ErrorCode.WRN_NullReferenceReturn, "o").WithLocation(11, 19));
        }
```

### PR DESCRIPTION
**Pull request by gafter**
Also fixes a corresponding issue in the switch expression
Fixes #34299
See also #35029

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 1]
```diff
@@ -91877,5 +91877,123 @@ class Derived<T> : Base<T> where T : class
...
+            () => o, // 2
+            () => {
+                    s = null; // 3
+                    return null; // 4
+                },
+            };
+        _ = fa3 /*T:System.Func<object!>![]!*/;
+        fa3[0]().ToString();
+    }
+}
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Could you also add tests for lambdas with multiple returns and ternaries?

Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Lambdas with multiple returns are tested below in `CheckLambdaInLambdaInference`

I tested ternaries and found that the behavior was wrong and filed [https://github.com/dotnet/roslyn/issues/35029](https://github.com/dotnet/roslyn/issues/35029)

---
In reply to: [276122618](https://github.com/dotnet/roslyn/pull/35030#discussion_r276122618) [](ancestors = 276122618)

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a second review?
