### PR TITLE
Filter source generator diagnostics by `SuppressMessageAttribute`

### LINKED ISSUE #66337: Warnings raised by incremental source generators are not disabled by the SuppressMessage attribute
**Version Used**: 

Code generator using Microsoft.CodeAnalysis.CSharp 4.3.0
Consuming project targeting net6.0
Compiling using .net sdk 7.0.100
On Visual Studio 17.4.2

**Steps to Reproduce**:

1. Create an incremental source generator that adds a diagnostic warning
2. Create a consuming project that raises the warning. Use Visual Studio to generate the SuppressMessage attribute to disable the warning
image

**Expected Behavior**:

The warning is disabled both in the IDE and in the output of the next build.

**Actual Behavior**:

The warning is not disabled (both in the IDE and during the next project build). The attribute is shown in "dimmed" color as if there wasn't a matching warning being raised.
image

### PR DESCRIPTION
**Pull request by jjonescz**
Fixes #66337.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs [hunk 1]
```diff
@@ -1280,6 +1280,92 @@ void verifyDiagnosticsWithSource(string source, (Diagnostic, TextSpan)[] reportD
             }
         }
 
+        [Fact, WorkItem(66337, "https://github.com/dotnet/roslyn/issues/66337")]
+        public void Diagnostics_Respect_SuppressMessageAttribute()
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs:1284]: Can we get the same tests for VB?

Comment (jjonescz) [reply src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests.cs:1284]: Didn't notice there are VB tests for this. Added.

**Review by chsienki — APPROVED** [review]

**Review by 333fred — APPROVED** [review]
