### PR TITLE
Switch MSBuildWorkspace to running builds out of proc

### LINKED ISSUE #61454: Workspace failed with could not load "NuGet.Frameworks" error
**Version Used**: 4.2.0

**Steps to Reproduce**:

There's a sample: https://github.com/WeihanLi/dotnet-exec/blob/c856424abe605ada9f4d2bedb68c3526d1241bc8/src/dotnet-exec/AdvancedCodeCompiler.cs

**Expected Behavior**:

Should work without error

**Actual Behavior**:

```
Failure, Msbuild failed when processing the file 'C:\projects\sources\SamplesInPractice\net7Sample\Net7Sample\Net7Sample.csproj' with message: C:\Program Files\dotnet\sdk\7.0.100-preview.4.22252.9\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets: (90, 5): The "ProcessFrameworkReferences" task failed unexpectedly.
      System.IO.FileLoadException: Could not load file or assembly 'NuGet.Frameworks, Version=6.3.0.32, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621)
      File name: 'NuGet.Frameworks, Version=6.3.0.32, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
       ---> System.IO.FileLoadException: Could not load file or assembly 'NuGet.Frameworks, Version=6.3.0.32, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
         at System.Runtime.Loader.AssemblyLoadContext.<LoadFromPath>g____PInvoke__|5_0(IntPtr ptrNativeAssemblyBinder, UInt16* ilPath, UInt16* niPath, ObjectHandleOnStack retAssembly)
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyBinder, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
         at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
         at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
         at Microsoft.NET.Build.Tasks.ProcessFrameworkReferences.ExecuteCore()
         at Microsoft.NET.Build.Tasks.TaskBase.Execute()
         at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
         at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

And I could not find the `NuGet.Frameworks` package with version `6.3.0` on the NuGet website, I finally find it in the sdk folder,  did I miss some config?

### PR DESCRIPTION
**Pull request by jasonmalinowski**
This switches MSBuildWorkspace over to using out-of-proc builds using the same mechanism we use for our LSP process. This brings a few advantages:

1. Applications on .NET Framework can now analyze .NET Core projects and vice versa without special work on the application author's side. Today your best workaround is to do something like multi-target your app for both platforms and hope the user knows which one to pick.
2. It ensures we're better isolated from the application's deployed binaries. For example, applications could now deploy MSBuild as a regular library without breaking MSBuildLocator (since that's not needed in proc), which simplifies things like our LSIF generator. This also fixes #61454 (and similar bugs) where an extra binary being deployed can potentially break MSBuild. There's further isolation work to still do here, to ensure we're more isolated even against what the BuildHost ships, but since it means the environment for running stuff is far more controlled, we'll have more confidence of what we test in our own tests will represent the behavior in the wild.
3. It ensures that the user doesn't have to worry about things like MSBuildLocator or binding redirects, etc. For example, we always have a [non-stop](https://stackoverflow.com/questions/75377255/how-do-i-make-roslyn-aka-msbuildworkspace-behave-the-same-way-visual-studio-msbu) [stream](https://stackoverflow.com/questions/72227113/c-sharp-programm-cant-find-my-workspace-with-msbuildworkspace) [of](https://stackoverflow.com/questions/43330915/could-not-load-file-or-assembly-microsoft-build-frameworkvs-2017/71128638#71128638) [questions](https://stackoverflow.com/questions/70106717/parameter-toolspath-cannot-be-null-when-calling-msbuildworkspace-openprojec) [on](https://stackoverflow.com/q/69297342/972216) [StackOverflow](https://stackoverflow.com/a/65640715/972216) of [people](https://stackoverflow.com/questions/77393405/roslyn-workspace-api-not-loading-properly-for-a-third-party-solution) having issues this way and those are fixed for good.

The one major caveat here is we did have some entrypoints for MSBuildWorkspace that accept an ILogger; currently these will be broken. I'm still reaching out to folks to decide what to do here. We can simply obsolete them, or try to get them to work in a few scenarios. (For example, I could detect if the logger you passed is a well known built in logger we can just recreate that on the OOP side). This will also break any apps that were really expecting the build to be in-proc (like by tinkering with MSBuild properties in advance) but such a behavior wasn't really supported anyways.

Work still to do prior to merge:

- [x] Add support back for TryApplyChanges; I have that commented out at the moment while I got the core stable first.
- [x] Replace StreamJsonRpc with a different RPC mechanism since that's not source build friendly.
- [x] Fix some bugs around locked/corrupted project files that the new code isn't dealing with as well.
- [x] Add support back for setting properties like debug/release configurations.
- [x] Write a bunch more tests for the StreamJsonRpc replacement.

Things that will be tracked for follow-up:

- [ ] Right now we are shipping two BuildHost layouts as a part of any use, which means duplicating the BuildHost and all it's references twice. We can definitely trim down number of binaries to reduce the disk size. For example we're shipping Microsoft.CodeAnalysis.Workspaces and Microsoft.CodeAnalysis mostly for various helpers or trivial enums that we could either link or just remove.
- [ ] Investigate the logic of MSBuildWorkspace's support for adding documents, which seems to be repeatedly converting between relative and absolute paths.
- [ ] Unit tests for metadata reference removal, since there aren't any today.
- [ ] More formally obsolete the ILogger APIs.
- [ ] Switching the OOP serialization to System.Text.Json so that way we're not shipping Newtonsoft.Json. Ironically we're shipping both libraries at the moment...

### CODE REVIEW

File: src/Tools/AnalyzerRunner/AnalyzerRunnerHelper.cs [hunk 1]
```diff
@@ -2,46 +2,17 @@
...
         public static MSBuildWorkspace CreateWorkspace()
         {
             var properties = new Dictionary<string, string>
             {
-#if NETCOREAPP
-                // This property ensures that XAML files will be compiled in the current AppDomain
-                // rather than a separate one. Any tasks isolated in AppDomains or tasks that create
-                // AppDomains will likely not work due to https://github.com/Microsoft/MSBuildLocator/issues/16.
-                { "AlwaysCompileMarkupFilesInSeparateDomain", bool.FalseString },
-#endif
```
Comment (jasonmalinowski) [inline src/Tools/AnalyzerRunner/AnalyzerRunnerHelper.cs:44]: If this is still necessary, it doesn't belong in this assembly anymore since the "is this .NET Core?" test ishould be in a different process. (And if it's generally necessary for XAML projects, then we should have this as a central fix.)

File: src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj [hunk 2]
```diff
@@ -58,22 +72,15 @@
...
-    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);GetBuildHostBinaries</TargetsForTfmSpecificBuildOutput>
-    <TargetsForTfmSpecificDebugSymbolsInPackage>$(TargetsForTfmSpecificBuildOutput);GetBuildHostDebugSymbols</TargetsForTfmSpecificDebugSymbolsInPackage>
+    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);GetAdditionalBinariesToPackage</TargetsForTfmSpecificBuildOutput>
   </PropertyGroup>
-  <Target Name="GetBuildHostBinaries" DependsOnTargets="ResolveReferences">
-      <MSBuild Projects="..\MSBuild.BuildHost\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj" Targets="_GetBuildOutputFilesWithTfm">
-        <Output TaskParameter="TargetOutputs" ItemName="BuildOutputInPackage" />
-      </MSBuild>
-  </Target>
-  <Target Name="GetBuildHostDebugSymbols">
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj]: I can't figure out what scenario symbol packing was happening in, so just removing it.

File: eng/Versions.props [hunk 3]
```diff
@@ -215,24 +214,14 @@
...
     <RestSharpVersion>105.2.3</RestSharpVersion>
     <RichCodeNavEnvVarDumpVersion>0.1.1643-alpha</RichCodeNavEnvVarDumpVersion>
     <RoslynBuildUtilVersion>0.9.8-beta</RoslynBuildUtilVersion>
     <RoslynDependenciesOptimizationDataVersion>3.0.0-beta2-19053-01</RoslynDependenciesOptimizationDataVersion>
     <RoslynDiagnosticsAnalyzersVersion>$(RoslynDiagnosticsNugetPackageVersion)</RoslynDiagnosticsAnalyzersVersion>
-    <!--
-      The package "Microsoft.CodeAnalysis.Analyzer.Testing" brings in an earlier version of these NuGet dependencies than
-      is expected by the NET SDK used in the Workspace.MSBuild UnitTests. In order to test against the same verion of NuGet
-      as our configured SDK, we must set the version to be the same.
-     -->
```
Comment (jasonmalinowski) [inline eng/Versions.props:229]: NuGet dependencies don't matter anymore, so this workaround can be removed for good.

File: src/Features/Lsif/Generator/Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.csproj [hunk 4]
```diff
@@ -55,22 +55,13 @@
   </ItemGroup>
 
   <ItemGroup>
-    <PackageReference Include="Microsoft.Build.Locator" Version="$(MicrosoftBuildLocatorVersion)" />
+    <PackageReference Include="Microsoft.Extensions.Logging" Version="$(MicrosoftExtensionsLoggingVersion)" />
+    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="$(MicrosoftExtensionsLoggingAbstractionsVersion)" />
+    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="$(MicrosoftExtensionsLoggingConsoleVersion)" />
```
Comment (jasonmalinowski) [inline src/Features/Lsif/Generator/Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.csproj:60]: These were implicitly coming along with the BuildHost ProjectReference, but now it's just explicit.

File: src/Tools/IdeBenchmarks/IdeBenchmarks.csproj [hunk 5]
```diff
@@ -12,7 +12,6 @@
   <ItemGroup>
     <PackageReference Include="BenchmarkDotNet" Version="$(BenchmarkDotNetVersion)" />
     <PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" Version="$(BenchmarkDotNetDiagnosticsWindowsVersion)" />
-    <PackageReference Include="Microsoft.Build.Locator" Version="$(MicrosoftBuildLocatorVersion)" />
```
Comment (jasonmalinowski) [inline src/Tools/IdeBenchmarks/IdeBenchmarks.csproj:15]: This PR generally goes through the repo and removes uses of MSBuild Locator that was used in places that were using MSBuildWorkspace. Those just aren't necessary anymore.

File: src/Workspaces/Core/MSBuild.BuildHost/BuildHost.cs [hunk 6]
```diff
@@ -118,29 +122,29 @@ private void CreateBuildManager()
...
     }
 
     private void EnsureMSBuildLoaded(string projectFilePath)
     {
-        Contract.ThrowIfFalse(TryEnsureMSBuildLoaded(projectFilePath), $"We don't have an MSBuild to use; {nameof(HasUsableMSBuildAsync)} should have been called first to check.");
+        Contract.ThrowIfFalse(TryEnsureMSBuildLoaded(projectFilePath), $"We don't have an MSBuild to use; {nameof(HasUsableMSBuild)} should have been called first to check.");
     }
 
-    public Task<ImmutableArray<(string ProjectPath, string ProjectGuid)>> GetProjectsInSolutionAsync(string solutionFilePath, CancellationToken cancellationToken)
+    public ImmutableArray<(string ProjectPath, string ProjectGuid)> GetProjectsInSolution(string solutionFilePath)
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/MSBuild.BuildHost/BuildHost.cs:140]: The mini RPC library implemeted here is less strict about requiring things to be Task-returning, so this is just updating to the simpler pattern. (It originally started not having async support at all until I realized I needed it.)

File: src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs [hunk 7]
```diff
@@ -386,132 +393,75 @@ public void RemoveDocument(string filePath)
             }
         }
 
-        public void AddMetadataReference(MetadataReference reference, AssemblyIdentity identity)
+        public void AddMetadataReference(string metadataReferenceIdentity, MetadataReferenceProperties properties, string? hintPath)
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs:396]: The rest of this file are MSBuildWorkspace's support for TryApplyChanges. Previously this would be called in the same process of the Roslyn workspace, so it could pass around workspace objects directly. Now this is on the server side of the RPC channel, so we need simpler types. You'll see some of this logic is now in MSBuildWorkspace directly.

File: src/Workspaces/Core/MSBuild.BuildHost/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj [hunk 8]
```diff
@@ -4,27 +4,21 @@
...
   <ItemGroup>
     <PackageReference Include="Microsoft.Build" Version="$(RefOnlyMicrosoftBuildVersion)" ExcludeAssets="Runtime" PrivateAssets="All" />
     <PackageReference Include="Microsoft.Build.Framework" Version="$(RefOnlyMicrosoftBuildFrameworkVersion)" ExcludeAssets="Runtime" />
     <PackageReference Include="Microsoft.Build.Tasks.Core" Version="$(RefOnlyMicrosoftBuildTasksCoreVersion)" ExcludeAssets="Runtime" PrivateAssets="All" />
     <PackageReference Include="Microsoft.Build.Locator" Version="$(MicrosoftBuildLocatorVersion)" PrivateAssets="All" />
     <PackageReference Include="System.Text.Json" Version="$(SystemTextJsonVersion)" />
-    <PackageReference Include="StreamJsonRpc" Version="$(StreamJsonRpcVersion)" Condition="'$(DotNetBuildFromSource)' != 'true'" />
     <PackageReference Include="System.CommandLine" Version="$(SystemCommandLineVersion)" />
     <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="$(MicrosoftExtensionsLoggingConsoleVersion)" />
+    <PackageReference Include="Newtonsoft.Json" Version="$(NewtonsoftJsonVersion)" />
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/MSBuild.BuildHost/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj:21]: Right now we're using Newtonsoft.Json for RPC, since that's previously what StreamJsonRpc was using. We'll transition the RPC to using System.Text.Json in another PR.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs [hunk 9]
```diff
@@ -0,0 +1,146 @@
...
+                            if (result is Task task)
+                            {
+                                await task.ConfigureAwait(false);
+
+                                // If it's actually a Task<T> then get the result; we're looking at the declared return type because in some cases a method might
+                                // return a Task<T> under the covers as a workaround for the lack of TaskCompletionSource on .NET Framework but we don't want to see
+                                // that workaround since the result isn't intended to be seen.
+                                if (method.ReturnType.IsConstructedGenericType)
+                                {
+                                    result = task.GetType().GetProperty("Result")!.GetValue(task);
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:102]: If there's a better way to do this, I'd love to know it.

File: src/Workspaces/MSBuildTest/Microsoft.CodeAnalysis.Workspaces.MSBuild.UnitTests.csproj [hunk 10]
```diff
@@ -26,42 +26,6 @@
     <ProjectReference Include="..\Remote\Core\Microsoft.CodeAnalysis.Remote.Workspaces.csproj" />
     <ProjectReference Include="..\VisualBasic\Portable\Microsoft.CodeAnalysis.VisualBasic.Workspaces.vbproj" />
   </ItemGroup>
-  <ItemGroup>
```
Comment (jasonmalinowski) [inline src/Workspaces/MSBuildTest/Microsoft.CodeAnalysis.Workspaces.MSBuild.UnitTests.csproj:29]: This demonstrates how much simpler a MSBuildWorkspace-consuming project can now become!

File: src/Workspaces/MSBuildTest/Utilities/DotNetSdkMSBuildInstalled.cs [hunk 11]
```diff
@@ -111,22 +33,29 @@ static string GetSolutionFolder()
...
-        // https://github.com/dotnet/roslyn/issues/67566
         public override bool ShouldSkip
-            => true;
+            => s_skipReason is not null;
 
         public override string SkipReason
-#if NETCOREAPP
-            => $"Could not locate .NET SDK version {VersionString}.";
-#else
-            => $"Test runs on .NET Core only.";
```
Comment (jasonmalinowski) [inline src/Workspaces/MSBuildTest/Utilities/DotNetSdkMSBuildInstalled.cs:129]: This is a general change with this PR: previously we had two sets of tests. Some tests tested "classic" projects and those tests ran in .NET Framework. Some tests tested SDK-style projects, and those ran in .NET Core. That was necessary because until this PR, that was the only supported combo. Since .NET Framework projects can now launch a .NET Core OOP process to read SDK projects and vice versa, this goes from unsupported to supported, and thus now in need of testing!

File: src/Workspaces/MSBuildTest/Utilities/VisualStudioMSBuildInstalled.cs [hunk 12]
```diff
@@ -2,63 +2,52 @@
...
-        internal VisualStudioMSBuildInstalled(Version minimumVersion)
-        {
-#if NET472_OR_GREATER
-            _minimumVersion = minimumVersion;
-#endif
+            try
+            {
+                buildHostProcessManager = new BuildHostProcessManager();
+
+                var buildHost = buildHostProcessManager.GetBuildHostAsync(BuildHostProcessManager.BuildHostProcessKind.NetFramework, CancellationToken.None).Result;
```
Comment (jasonmalinowski) [inline src/Workspaces/MSBuildTest/Utilities/VisualStudioMSBuildInstalled.cs:36]: Unfortunately the only way to use MSBuildLocator right now to find a VS install is to launch a .NET Framework process if you're on .NET Core. I've been talking to the MSBuild team to lift this requirement.

File: src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Microsoft.CodeAnalysis.LanguageServer.csproj [hunk 13]
```diff
@@ -120,34 +119,6 @@
     </ItemGroup>
   </Target>
 
-  <!--
-    Deploy a net472 version of the BuildHost process.
-  -->
-  <Target Name="DeployNetFrameworkBuildHost" AfterTargets="ResolveProjectReferences" Condition="'$(DesignTimeBuild)' != 'true'">
```
Comment (jasonmalinowski) [inline src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/Microsoft.CodeAnalysis.LanguageServer.csproj:126]: This all moves to the MSBuildWorkspace project directly. You'll see this oevr there (with some changes to make NuGet happier.)

File: src/Workspaces/Core/MSBuild.BuildHost/Program.cs [hunk 14]
```diff
@@ -3,34 +3,34 @@
...
-    }
-
-#else
-
     internal static async Task Main(string[] args)
     {
+        var propertyOption = new CliOption<string[]>("--property") { Arity = ArgumentArity.ZeroOrMore };
         var binaryLogOption = new CliOption<string?>("--binlog") { Required = false };
-        var command = new CliRootCommand { binaryLogOption };
+        var command = new CliRootCommand { binaryLogOption, propertyOption };
```
Comment (JoeRobich) [inline src/Workspaces/Core/MSBuild.BuildHost/Program.cs:21]: Random thought. Since this will eventually ship in the SDK, by being used in dotnet-format and dotnet-watch, System.CommandLine will need to be updated to the version used by the SDK being inserted into. In a perfect world they could just patch the version when doing a source build, but the reality is that there are often breaking changes in that library.

File: src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj [hunk 15]
```diff
@@ -16,44 +22,103 @@
     </PackageDescription>
   </PropertyGroup>
   <ItemGroup>
-    <PackageReference Include="Microsoft.Build" Version="$(RefOnlyMicrosoftBuildVersion)" ExcludeAssets="Runtime" PrivateAssets="All" />
-    <PackageReference Include="Microsoft.Build.Framework" Version="$(RefOnlyMicrosoftBuildFrameworkVersion)" ExcludeAssets="Runtime" />
-    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="$(RefOnlyMicrosoftBuildTasksCoreVersion)" ExcludeAssets="Runtime" PrivateAssets="All" />
+    <PackageReference Include="Microsoft.Build" Version="$(RefOnlyMicrosoftBuildVersion)" />
+    <PackageReference Include="Microsoft.Build.Framework" Version="$(RefOnlyMicrosoftBuildFrameworkVersion)" />
+    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="$(RefOnlyMicrosoftBuildTasksCoreVersion)" />
```
Comment (JoeRobich) [inline src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj:27]: Do we want these to become transitive dependencies? Wouldn't they be loaded by the BuildHost from the MSBuild directory?

**Review by JoeRobich — COMMENTED** [review]
I am excited to see this get in.

File: src/Workspaces/Core/MSBuild.BuildHost/Build/ProjectBuildManager.cs [hunk 16]
```diff
@@ -243,7 +243,7 @@ public void EndBatchBuild()
             {
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Build/ProjectBuildManager.cs:243]: this commit seems fine.

File: src/Workspaces/Core/MSBuild.BuildHost/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj [hunk 17]
```diff
@@ -40,7 +40,6 @@
     <InternalsVisibleTo Include="Microsoft.CodeAnalysis.Workspaces.Test.Utilities" />
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj]: this commit LGTM.

File: src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs [hunk 18]
```diff
@@ -20,7 +20,7 @@
 using Microsoft.Extensions.Logging;
```
Comment (CyrusNajmabadi) [inline src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:20]: > - Right now we're still using StreamJsonRpc, so that'll break Source
  Build.

Is there an effort to get those two to work together?

File: src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs [hunk 19]
```diff
@@ -203,9 +205,9 @@ private async Task<(LSP.MessageType? FailureType, BuildHostProcessKind? Preferre
 
             (var buildHost, preferredBuildHostKind) = await buildHostProcessManager!.GetBuildHostAsync(projectPath, cancellationToken);
 
-            if (await buildHost.IsProjectFileSupportedAsync(projectPath, cancellationToken))
+            if (_projectFileExtensionRegistry.TryGetLanguageNameFromProjectPath(projectPath, DiagnosticReportingMode.Ignore, out var languageName))
```
Comment (CyrusNajmabadi) [inline src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:208]: minor nit.  but would love to see this 'if' flipped in the future.

File: src/Workspaces/Core/MSBuild.BuildHost/IBuildHost.cs [hunk 20]
```diff
@@ -20,12 +20,9 @@ internal interface IBuildHost
...
     Task<ImmutableArray<(string ProjectPath, string ProjectGuid)>> GetProjectsInSolutionAsync(string solutionFilePath, CancellationToken cancellationToken);
 
-    /// <summary>
-    /// Returns whether this project's is supported by this host.
-    /// </summary>
-    Task<bool> IsProjectFileSupportedAsync(string projectFilePath, CancellationToken cancellationToken);
+    Task<IRemoteProjectFile> LoadProjectFileAsync(string projectFilePath, string languageName, CancellationToken cancellationToken);
 
-    Task<IRemoteProjectFile> LoadProjectFileAsync(string projectFilePath, CancellationToken cancellationToken);
+    Task<string?> TryGetProjectOutputPathAsync(string projectFilePath, CancellationToken cancellationToken);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/IBuildHost.cs]: what's an example of where this fails?

File: src/Workspaces/Core/MSBuild/Host/Mef/MSBuildMefHostServices.cs [hunk 21]
```diff
@@ -2,66 +2,30 @@
...
             {
-                if (s_defaultServices == null)
-                {
-                    Interlocked.CompareExchange(ref s_defaultServices, MefHostServices.Create(DefaultAssemblies), null);
-                }
-
-                return s_defaultServices;
+                // At this point, we don't have any MEF types in this assembly, so we can just defer to the default set.
+                // This type is just maintained for public API compatibility (and future expansion if we were to have to add types back in.)
+                return MefHostServices.DefaultHost;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/Host/Mef/MSBuildMefHostServices.cs:18]: 1. API compat with who?
2. would love to consider just reomving this altogether if possible.

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/MSBuild/Host/Mef/MSBuildMefHostServices.cs:18]: 3. maybe still wrap .DefaultAssemblies (like we did before), that way if that ever changes, this automatically picks it up.  But i don't feel strongly on this.

File: src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs [hunk 22]
```diff
@@ -53,11 +59,11 @@ public async Task<(IBuildHost, BuildHostProcessKind? PreferredKind)> GetBuildHos
         // us to discover VS instances in .NET Framework hosts right now.
         if (neededBuildHostKind == BuildHostProcessKind.NetFramework)
         {
-            if (!await buildHost.HasUsableMSBuildAsync(projectFilePath, cancellationToken))
+            if (!await buildHost.HasUsableMSBuildAsync(projectFilePath, cancellationToken).ConfigureAwait(false))
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs:65]: how were tehse misssed before?  analyzer bug?

File: src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs [hunk 23]
```diff
@@ -134,10 +140,12 @@ private ProcessStartInfo CreateDotNetCoreBuildHostStartInfo()
         // We need to roll forward to the latest runtime, since the project may be using an SDK (or an SDK required runtime) newer than we ourselves built with.
         // We set the environment variable since --roll-forward LatestMajor doesn't roll forward to prerelease SDKs otherwise.
         processStartInfo.Environment["DOTNET_ROLL_FORWARD_TO_PRERELEASE"] = "1";
-        processStartInfo.ArgumentList.Add("--roll-forward");
-        processStartInfo.ArgumentList.Add("LatestMajor");
+        AddArgument(processStartInfo, "--roll-forward");
+        AddArgument(processStartInfo, "LatestMajor");
 
-        processStartInfo.ArgumentList.Add(typeof(IBuildHost).Assembly.Location);
+        var netCoreBuildHostPath = Path.Combine(Path.GetDirectoryName(typeof(BuildHostProcessManager).Assembly.Location)!, "BuildHost-net6.0", "Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll");
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs:156]: ok to hardcode these values in?  the `-net6.0` part seems fishy to me

File: src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs [hunk 24]
```diff
@@ -197,6 +205,23 @@ private void AppendBuildHostCommandLineArgumentsConfigureProcess(ProcessStartInf
...
+        // On .NET Core 2.1 and higher we can just use ArgumentList to do the right thing; downlevel we need to manually
+        // construct the string
+#if NET
+        processStartInfo.ArgumentList.Add(argument);
+#else
+        if (processStartInfo.Arguments.Length > 0)
+            processStartInfo.Arguments += ' ';
+
+        if (argument.Contains(' '))
+            processStartInfo.Arguments += '"' + argument + '"';
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs:235]: maybe cleaner to always quote?

File: src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.Worker.cs [hunk 25]
```diff
@@ -132,72 +132,67 @@ public async Task<ImmutableArray<ProjectInfo>> LoadAsync(CancellationToken cance
                 var results = ImmutableArray.CreateBuilder<ProjectInfo>();
                 var processedPaths = new HashSet<string>(PathUtilities.Comparer);
 
-                _buildManager.StartBatchBuild(_globalProperties);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.Worker.cs:135]: why did this go away?

File: src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.Worker.cs [hunk 26]
```diff
@@ -132,72 +132,67 @@ public async Task<ImmutableArray<ProjectInfo>> LoadAsync(CancellationToken cance
...
 
                 // If there were any failures during load, we won't be able to build the project. So, bail early with an empty project.
-                if (projectFile.Log.HasFailure)
+                var diagnosticItems = await projectFile.GetDiagnosticLogItemsAsync(cancellationToken).ConfigureAwait(false);
+                if (diagnosticItems.Any(d => d.Kind == WorkspaceDiagnosticKind.Failure))
                 {
-                    _diagnosticReporter.Report(projectFile.Log);
+                    _diagnosticReporter.Report(diagnosticItems);
 
+                    // TODO: correct language type!
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.Worker.cs:193]: yeah, seems wonky.  what impact does this have?

File: src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.cs [hunk 27]
```diff
@@ -144,7 +144,9 @@ private DiagnosticReportingMode GetReportingModeForUnrecognizedProjects()
         public async Task<SolutionInfo> LoadSolutionInfoAsync(
             string solutionFilePath,
             IProgress<ProjectLoadProgress>? progress = null,
+#pragma warning disable IDE0060 // TODO: decide what to do with this unusued ILogger, since we can't reliabily use it if we're sending builds out of proc
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.cs:147]: couldn't hte OOP work log to its own logger that forwards to this?

File: src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.cs [hunk 28]
```diff
@@ -256,14 +261,15 @@ private DiagnosticReportingMode GetReportingModeForUnrecognizedProjects()
                 onPathFailure: reportingMode,
                 onLoaderFailure: reportingMode);
 
-            var buildManager = new ProjectBuildManager(Properties, msbuildLogger);
+            var buildHostProcessManager = new BuildHostProcessManager();
+            await using var _ = buildHostProcessManager.ConfigureAwait(false);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.cs:265]: i'm really confused ny this line.  you're configuring the new object you created above?  which was not a task?

File: src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs [hunk 29]
```diff
@@ -158,11 +149,15 @@ public void CloseSolution()
             }
         }
 
+#if SUPPORT_TRYAPPLYCHANGES
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs]: wha'ts this?

File: src/Workspaces/CoreTestUtilities/MEF/UseExportProviderAttribute.cs [hunk 30]
```diff
@@ -65,7 +65,6 @@ static UseExportProviderAttribute()
         public override void Before(MethodInfo? methodUnderTest)
         {
             // Need to clear cached MefHostServices between test runs.
-            MSBuildMefHostServices.TestAccessor.ClearCachedServices();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CoreTestUtilities/MEF/UseExportProviderAttribute.cs:68]: don't love that this went away.  if we add mef stuf in the future, won't this be necessary?  should we keep the stubs for this around?

i'd feel more comfortable if we got rid of all the mef stuff entirely.

File: eng/Versions.props [hunk 31]
```diff
@@ -222,17 +222,6 @@
     <RoslynBuildUtilVersion>0.9.8-beta</RoslynBuildUtilVersion>
```
Comment (CyrusNajmabadi) [inline eng/Versions.props:222]: this commit LGTM.

File: eng/Versions.props [hunk 32]
```diff
@@ -82,7 +82,6 @@
     <MicrosoftBuildRuntimeVersion>$(MicrosoftBuildPackagesVersion)</MicrosoftBuildRuntimeVersion>
```
Comment (CyrusNajmabadi) [inline eng/Versions.props:82]: this commit LGTM.

File: src/Workspaces/Core/MSBuild.BuildHost/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj [hunk 33]
```diff
@@ -37,7 +37,6 @@
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj:31]: this commit LGTM

File: src/Features/Lsif/Generator/Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.csproj [hunk 34]
```diff
@@ -55,25 +55,13 @@
   </ItemGroup>
```
Comment (CyrusNajmabadi) [inline src/Features/Lsif/Generator/Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.csproj:55]: so how does this end up working?  does the MSBuild libs we reference automatically locate properly?

File: src/Workspaces/MSBuildTest/VisualStudioMSBuildWorkspaceTests.cs [hunk 35]
```diff
@@ -3106,7 +3106,7 @@ public async Task TestOpenProject_LogsEvaluationOnly()
```
Comment (CyrusNajmabadi) [inline src/Workspaces/MSBuildTest/VisualStudioMSBuildWorkspaceTests.cs]: this commit lgtm.

File: src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs [hunk 36]
```diff
@@ -442,39 +442,31 @@ protected override void ApplyDocumentAdded(DocumentInfo info, SourceText text)
         {
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs:449]: this commit lgtm.

File: src/Workspaces/Core/MSBuild.BuildHost/IRemoteProjectFile.cs [hunk 37]
```diff
@@ -16,7 +16,7 @@
 namespace Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/IRemoteProjectFile.cs]: this commit LGTM.

File: src/Workspaces/Core/MSBuild.BuildHost/IRemoteProjectFile.cs [hunk 38]
```diff
@@ -25,4 +25,15 @@ internal interface IRemoteProjectFile : IDisposable
 {
     Task<ImmutableArray<ProjectFileInfo>> GetProjectFileInfosAsync(CancellationToken cancellationToken);
     Task<ImmutableArray<DiagnosticLogItem>> GetDiagnosticLogItemsAsync(CancellationToken cancellationToken);
+
+    Task<string> GetDocumentExtensionAsync(SourceCodeKind sourceCodeKind, CancellationToken cancellationToken);
+    Task AddDocumentAsync(string filePath, string? logicalPath, CancellationToken cancellationToken);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/IRemoteProjectFile.cs]: for my underatnding, what's the diff between a filepath and a logicalpath?

File: src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs [hunk 39]
```diff
@@ -391,132 +391,75 @@ public void RemoveDocument(string filePath)
...
-                    var relativePath = PathUtilities.GetRelativePath(_loadedProject.DirectoryPath, peRef.FilePath);
-                    var fileName = Path.GetFileNameWithoutExtension(peRef.FilePath);
-                    metadata.Add(MetadataNames.HintPath, relativePath);
-                    _loadedProject.AddItem(ItemNames.Reference, fileName, metadata);
-                }
-            }
-        }
+            var metadata = new Dictionary<string, string>();
+            if (!properties.Aliases.IsEmpty)
+                metadata.Add(MetadataNames.Aliases, string.Join(",", properties.Aliases));
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs:405]: why collapse the aliases into a comma separated list?  can't we still operate on them all as individual strings without collapsing/exploding strings?  this makes me wary.

File: src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs [hunk 40]
```diff
@@ -391,132 +391,75 @@ public void RemoveDocument(string filePath)
...
+        public void RemoveMetadataReference(string shortAssemblyName, string fullAssemblyName, string filePath)
         {
             if (_loadedProject is null)
             {
                 return;
             }
 
-            if (reference is PortableExecutableReference peRef && peRef.FilePath != null)
+            var item = FindReferenceItem(shortAssemblyName, fullAssemblyName, filePath);
+            if (item != null)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs:421]: it is a bug if we can't find the item?

File: src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs [hunk 41]
```diff
@@ -391,132 +391,75 @@ public void RemoveDocument(string filePath)
...
             var fileName = Path.GetFileNameWithoutExtension(filePath);
 
-            if (identity != null)
-            {
-                var shortAssemblyName = identity.Name;
-                var fullAssemblyName = identity.GetDisplayName();
-
-                // check for short name match
-                item = references.FirstOrDefault(it => string.Compare(it.EvaluatedInclude, shortAssemblyName, StringComparison.OrdinalIgnoreCase) == 0);
+            // check for short name match
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs:436]: i guess we had this logic before.  but it's reallly oogy to me that we're doing all this munging.

File: src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs (hunk 40 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs:421]: actually, looks like FindReferenceItem throws if it can't find the item.  so do you need htis check here?

File: src/Workspaces/Core/MSBuild.BuildHost/RemoteProjectFile.cs [hunk 42]
```diff
@@ -29,4 +29,61 @@ public Task<ImmutableArray<ProjectFileInfo>> GetProjectFileInfosAsync(Cancellati
     public Task<ImmutableArray<DiagnosticLogItem>> GetDiagnosticLogItemsAsync(CancellationToken cancellationToken)
         => Task.FromResult(_projectFile.Log.ToImmutableArray());
 
+    public Task<string> GetDocumentExtensionAsync(SourceCodeKind sourceCodeKind, CancellationToken cancellationToken)
+        => Task.FromResult(_projectFile.GetDocumentExtension(sourceCodeKind));
+
+    public Task AddDocumentAsync(string filePath, string? logicalPath, CancellationToken cancellationToken)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/RemoteProjectFile.cs]: all of these methods complete synchronously.  consider making ValueTasks

File: src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs [hunk 43]
```diff
@@ -295,31 +292,41 @@ private static bool HasProjectFileChanges(ProjectChanges changes)
...
 
+        private BuildHostProcessManager? _applyChangesBuildHostProcessManager;
 
-        private IProjectFile? _applyChangesProjectFile;
-#endif
+        /// <summary>
+        /// The loaded project file that we are currently applying changes to. This is set in <see cref="ApplyProjectChanges(ProjectChanges)"/> if we're modifying a project that is going to require
+        /// file changes; it's cleared once we're done with that project.
+        /// </summary>
+        private IRemoteProjectFile? _applyChangesProjectFile;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs]: nit: move to top of file.

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs]: the comment could use work.  what does it mean to be "done with that project".  

since many projects could need changing, what ensures this is serialized properly and we dont' stomp on things?

File: src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs [hunk 44]
```diff
@@ -295,31 +292,41 @@ private static bool HasProjectFileChanges(ProjectChanges changes)
...
+                try
+                {
+                    Debug.Assert(_applyChangesBuildHostProcessManager == null);
+                    _applyChangesBuildHostProcessManager = new BuildHostProcessManager();
+
+                    return base.TryApplyChanges(newSolution, progressTracker);
+                }
+                finally
+                {
+                    _applyChangesBuildHostProcessManager!.DisposeAsync().AsTask().Wait();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs:321]: wow :'(

my hate is strong here :)

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs:321]: do we need to do this "create" and "synchronously dispose and clear" pattern?  could we instead just make a single manager that stays alive which we know we're serializging messages to by virtue of hte lock above?

File: src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs [hunk 45]
```diff
@@ -360,7 +367,7 @@ protected override void ApplyProjectChanges(ProjectChanges projectChanges)
                 {
                     try
                     {
-                        _applyChangesProjectFile.Save();
+                        _applyChangesProjectFile.SaveAsync(CancellationToken.None).Wait();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs:370]: i'm heavily leaning toward us making everything async, and only having the outermost public *legacy* entrypoints wait.  i don't like all these waits scattered everywhere.

File: src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs [hunk 46]
```diff
@@ -499,7 +506,7 @@ protected override void ApplyDocumentRemoved(DocumentId documentId)
             var document = this.CurrentSolution.GetDocument(documentId);
             if (document?.FilePath is not null)
             {
-                _applyChangesProjectFile.RemoveDocument(document.FilePath);
+                _applyChangesProjectFile.RemoveDocumentAsync(document.FilePath, CancellationToken.None).Wait();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs:509]: yup.  really dislike this.  can we make thse methods async and push the non-cancellable waits up to the topmost legacy point?

File: src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj [hunk 47]
```diff
@@ -5,7 +5,7 @@
     <OutputType>Library</OutputType>
     <RootNamespace>Microsoft.CodeAnalysis</RootNamespace>
     <TargetFrameworks>$(SourceBuildTargetFrameworks);net472</TargetFrameworks>
-    <DefineConstants>$(DefineConstants);WORKSPACE_MSBUILD</DefineConstants>
+    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj:8]: why?

File: src/Workspaces/Core/MSBuild.BuildHost/IRemoteProjectFile.cs [hunk 48]
```diff
@@ -25,4 +25,15 @@ internal interface IRemoteProjectFile : IDisposable
 {
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/IRemoteProjectFile.cs]: this commit is currently concerning to me.

File: src/Tools/AnalyzerRunner/AnalyzerRunner.csproj [hunk 49]
```diff
@@ -12,8 +12,6 @@
   <ItemGroup>
```
Comment (CyrusNajmabadi) [inline src/Tools/AnalyzerRunner/AnalyzerRunner.csproj:12]: red code makes me happy.  lgtm.

File: src/Workspaces/MSBuildTest/Microsoft.CodeAnalysis.Workspaces.MSBuild.UnitTests.csproj [hunk 50]
```diff
@@ -26,31 +26,6 @@
     <ProjectReference Include="..\Remote\Core\Microsoft.CodeAnalysis.Remote.Workspaces.csproj" />
```
Comment (CyrusNajmabadi) [inline src/Workspaces/MSBuildTest/Microsoft.CodeAnalysis.Workspaces.MSBuild.UnitTests.csproj:26]: this si very clean. lgtm.

File: src/Workspaces/Core/MSBuild.BuildHost/Build/ProjectBuildManager.cs [hunk 51]
```diff
@@ -66,7 +66,7 @@ internal class ProjectBuildManager
         {
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Build/ProjectBuildManager.cs:66]: > If we don't, the finalizer can run and tear down the test process when
other tests are still running.

I odn't have a problem with this change, but the explaantion doesn't really make sense ot me.  being in a finally block shouldn't change anything *except* for having that code run in the case of early-exit/exception.  Which shoudln't apply in the code below because nothing seems exceptional.

File: src/Workspaces/Core/MSBuild.BuildHost/BuildHost.cs [hunk 52]
```diff
@@ -14,23 +14,25 @@
 using Microsoft.Build.Logging;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/BuildHost.cs:14]: > taking the dependency (even though
it's open source) would produce a long-term maintenance burden.

this seems crazy to me.  Where is the issue here?  VS is betting big on streamjsonrpc.  We already use it for OOP heavily.  It's the foundation of gladstone.  What part of our org is making it challenging for a first party like us to use this?

File: src/Workspaces/Core/MSBuild.BuildHost/BuildHost.cs (hunk 6 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/Core/MSBuild.BuildHost/BuildHost.cs:140]: note: if these still are RPC calls, i would *very* much like them to be Task-based.  that way we understand *virally* where async work (like cross process calls) are happening, and we have to code appropriately.

File: src/Workspaces/Core/MSBuild.BuildHost/BuildHost.cs [hunk 53]
```diff
@@ -171,15 +176,16 @@ public async Task<IRemoteProjectFile> LoadProjectFileAsync(string projectFilePat
...
     }
 
-    public Task<string?> TryGetProjectOutputPathAsync(string projectFilePath, CancellationToken cancellationToken)
+    public Task<string?> TryGetProjectOutputPathAsync(string projectFilePath)
     {
         EnsureMSBuildLoaded(projectFilePath);
         CreateBuildManager();
 
-        return _buildManager.TryGetOutputFilePathAsync(projectFilePath, cancellationToken);
+        return _buildManager.TryGetOutputFilePathAsync(projectFilePath, CancellationToken.None);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/BuildHost.cs:190]: i am not a fan.  i would still prefer these take cancellation tokens, and we thread things outwards as much as possible.

File: src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs [hunk 54]
```diff
@@ -39,6 +39,8 @@ protected ProjectFile(ProjectFileLoader loader, MSB.Evaluation.Project? loadedPr
             Log = log;
         }
 
+        public ImmutableArray<DiagnosticLogItem> GetDiagnosticLogItems() => Log.ToImmutableArray();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs:42]: nit: `=>` on the next line.

File: src/Workspaces/Core/MSBuild.BuildHost/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj (hunk 8 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/Core/MSBuild.BuildHost/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.csproj:21]: :'(

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/Request.cs [hunk 55]
```diff
@@ -0,0 +1,29 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+// See the LICENSE file in the project root for more information.
+
+using System.Collections.Generic;
+using Newtonsoft.Json.Linq;
+
+namespace Microsoft.CodeAnalysis.Rpc
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/Request.cs:8]: nit: this is a very vague/general namespace.  this looks to be specific to MSBuild, so i would love if that was in the namespace somehow.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/Request.cs [hunk 56]
```diff
@@ -0,0 +1,29 @@
...
+{
+    internal sealed class Request
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/Request.cs:10]: including MSBuild in the name here would also be ncie IMO.  like MSBuildRPCRequest :)

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/Request.cs [hunk 57]
```diff
@@ -0,0 +1,29 @@
...
+        /// The index of the targeted object.
+        /// </summary>
+        public int TargetObject { get; set; }
+
+        /// <summary>
+        /// The name of the method to call.
+        /// </summary>
+        public required string Method { get; set; }
+
+        public required List<JToken> Parameters { get; set; }
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/Request.cs:27]: why is all of this mutable?

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/Request.cs [hunk 58]
```diff
@@ -0,0 +1,29 @@
...
+    {
+        /// <summary>
+        /// The request ID.
+        /// </summary>
+        public int Id { get; set; }
+
+        /// <summary>
+        /// The index of the targeted object.
+        /// </summary>
+        public int TargetObject { get; set; }
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/Request.cs:20]: index into waht?

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/Response.cs [hunk 59]
```diff
@@ -0,0 +1,20 @@
...
+using System.Linq;
+using System.Text;
+using System.Threading.Tasks;
+using Newtonsoft.Json.Linq;
+
+namespace Microsoft.CodeAnalysis.Rpc
+{
+    internal sealed class Response
+    {
+        public int Id { get; set; }
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/Response.cs:16]: doc this a bit.  is this the same ID as the request id?

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/Response.cs [hunk 60]
```diff
@@ -0,0 +1,20 @@
...
+        public JToken? Value { get; set; }
+        public string? Exception { get; set; }
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/Response.cs:18]: why is all of this mutable?

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs [hunk 61]
```diff
@@ -0,0 +1,146 @@
...
+{
+    /// <summary>
+    /// Implements the server side of the RPC channel used to communicate with the build host.
+    /// </summary>
+    /// <remarks>
+    /// The RPC system implemented here is pretty close to something like JSON-RPC; however since we need the Build Host to be usable in Source Build
+    /// scenarios, we are limited to using only what is either in .NET or can be easily made buildable in Source Build. Thus existing solutions like StreamJsonRpc 
+    /// are out. If at some point there is a standard RPC mechanism exposed in .NET, we should just delete this and use that instead.
+    /// </remarks>
+    internal sealed class RpcServer
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:26]: the level to which i don't want to review this and validate it for correctness is HUGE.  to the point htat i'm willing to throw weight into unblocking whatever is blocking the ability to use streamjsonrpc.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs [hunk 62]
```diff
@@ -0,0 +1,146 @@
...
+    {
+        private readonly TextWriter _sendingStream;
+        private readonly SemaphoreSlim _sendingStreamSemaphore = new SemaphoreSlim(initialCount: 1);
+        private readonly TextReader _receivingStream;
+
+        private readonly ConcurrentDictionary<int, object> _rpcTargets = new();
+        private volatile int _nextRpcTargetIndex = -1; // We'll start at -1 so the first value becomes zero
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:33]: don't think this needs to be volaite if you're using Interlocked on it.  @stephentoub ?

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs [hunk 63]
```diff
@@ -0,0 +1,146 @@
...
+
+        public RpcServer(Stream sendingStream, Stream receivingStream)
+        {
+            _sendingStream = new StreamWriter(sendingStream, Encoding.UTF8);
+            _receivingStream = new StreamReader(receivingStream, Encoding.UTF8);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:38]: it is terrifying to me that an RPC streaming system specifies an encoding in any way.  What happens if we need to send things like null bytes etc?  is something ensuring that everything in this system is pure, legal, text from end to end?

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs [hunk 64]
```diff
@@ -0,0 +1,146 @@
...
+                    return nextIndex;
+            }
+        }
+
+        public async Task RunAsync()
+        {
+            var runningTasks = new ConcurrentSet<Task>();
+
+            string? line;
+            while ((line = await _receivingStream.ReadLineAsync().ConfigureAwait(false)) != null)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:58]: i cannot express how much i dislike that this is line-based.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs [hunk 65]
```diff
@@ -0,0 +1,146 @@
...
+            {
+                var request = JsonConvert.DeserializeObject<Request>(line);
+
+                Contract.ThrowIfNull(request);
+
+                var runningTask = Task.Run(async () =>
+                    {
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:65]: could you extract this body into a helper.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs [hunk 66]
```diff
@@ -0,0 +1,146 @@
...
+                        Response response;
+
+                        try
+                        {
+                            Contract.ThrowIfFalse(
+                            _rpcTargets.TryGetValue(request.TargetObject, out var rpcTarget),
+                            $"Received a request for target object {request.TargetObject} but we don't have a registered object for that.");
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:72]: fix indentation.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs [hunk 67]
```diff
@@ -0,0 +1,146 @@
...
+
+                            var method = rpcTarget.GetType().GetMethod(request.Method, BindingFlags.Public | BindingFlags.Instance);
+
+                            Contract.ThrowIfNull(method, $"The invoked method '{method}' could not be found.");
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:76]: can you doc somewhere the exception semantics of hte server.  specifically that inner exceptions don't tear down the server.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs [hunk 68]
```diff
@@ -0,0 +1,146 @@
...
+                            var arguments = new object?[methodParameters.Length];
+
+                            for (var i = 0; i < methodParameters.Length; i++)
+                            {
+                                // If the method we're calling accepts a cancellation token, we wouldn't have passed that, so add in a CancellationToken.None here. Although we could
+                                // remove the cancellation from the underlying method, this keeps that support around should we need it.
+                                if (i == methodParameters.Length - 1 && methodParameters[i].ParameterType == typeof(CancellationToken))
+                                    arguments[i] = CancellationToken.None;
+                                else
+                                    arguments[i] = request.Parameters[i].ToObject(methodParameters[i].ParameterType);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:88]: we're blindly indexing into the request paramteers.  can you do some more validation of htat up front so we can give good error messages?

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs [hunk 69]
```diff
@@ -0,0 +1,146 @@
...
+                            }
+
+                            var result = method.Invoke(rpcTarget, arguments);
+
+                            if (result is Task task)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:93]: what about valuetasks?  it's *super* common for our RPC apis to be written to be valuetask returning.  hardcoding only task support here seems like it could easily be pit of fail.  at the very least, if valuetask is not allowed, check for it and throw an error so people aren't super confused.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs [hunk 70]
```diff
@@ -0,0 +1,146 @@
...
+                            }
+
+                            response = new Response { Id = request.Id, Value = result is not null ? JToken.FromObject(result) : null };
+                        }
+                        catch (Exception e)
+                        {
+                            if (e is TargetInvocationException)
+                                e = e.InnerException ?? e;
+
+                            response = new Response { Id = request.Id, Exception = $"An exception of type {e.GetType()} was thrown: {e.Message}" };
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:118]: losing stack trace seems super painful here.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs [hunk 71]
```diff
@@ -0,0 +1,146 @@
...
+            // billions of long lived projects, but...
+            while (true)
+            {
+                var nextIndex = Interlocked.Increment(ref _nextRpcTargetIndex);
+                if (_rpcTargets.TryAdd(nextIndex, rpcTarget))
+                    return nextIndex;
+            }
+        }
+
+        public async Task RunAsync()
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:53]: what shuts down the server?

File: src/Workspaces/Core/MSBuild/Rpc/RemoteBuildHost.cs [hunk 72]
```diff
@@ -0,0 +1,45 @@
...
+            var remoteProjectFileTargetObject = await _client.InvokeAsync<int>(BuildHostTargetObject, nameof(BuildHost.LoadProjectFileAsync), [projectFilePath, languageName], cancellationToken).ConfigureAwait(false);
+
+            return new RemoteProjectFile(_client, remoteProjectFileTargetObject);
+        }
+
+        public Task<string?> TryGetProjectOutputPathAsync(string projectFilePath, CancellationToken cancellationToken)
+            => _client.InvokeNullableAsync<string>(BuildHostTargetObject, nameof(BuildHost.TryGetProjectOutputPathAsync), [projectFilePath], cancellationToken);
+
+        public Task ShutdownAsync(CancellationToken cancellationToken)
+            => _client.InvokeAsync(BuildHostTargetObject, nameof(BuildHost.ShutdownAsync), [], cancellationToken);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/Rpc/RemoteBuildHost.cs:42]: named param for `[]`?

File: src/Workspaces/Core/MSBuild/Rpc/RemoteInvocationException.cs [hunk 73]
```diff
@@ -0,0 +1,15 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+// See the LICENSE file in the project root for more information.
+
+using System;
+
+namespace Microsoft.CodeAnalysis.Rpc
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/Rpc/RemoteInvocationException.cs:7]: file scoped namespace.

File: src/Workspaces/Core/MSBuild/Rpc/RemoteProjectFile.cs [hunk 74]
```diff
@@ -0,0 +1,60 @@
...
+// The .NET Foundation licenses this file to you under the MIT license.
+// See the LICENSE file in the project root for more information.
+
+using System.Collections.Immutable;
+using System.Threading;
+using System.Threading.Tasks;
+using Microsoft.CodeAnalysis.MSBuild;
+using Microsoft.CodeAnalysis.MSBuild.Logging;
+
+namespace Microsoft.CodeAnalysis.Rpc
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/Rpc/RemoteProjectFile.cs:11]: file scoped namespace.

File: src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs [hunk 75]
```diff
@@ -0,0 +1,129 @@
...
+
+        public RpcClient(Stream sendingStream, Stream receivingStream)
+        {
+            _sendingStream = new StreamWriter(sendingStream, Encoding.UTF8);
+            _receivingStream = new StreamReader(receivingStream, Encoding.UTF8);
+        }
+
+        public void Start()
+        {
+            Task.Run(async () =>
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs:36]: fire and forget task in this void method makes me unhappy.

File: src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs [hunk 76]
```diff
@@ -0,0 +1,129 @@
...
+            {
+                string? line;
+                while ((line = await _receivingStream.ReadLineAsync().ConfigureAwait(false)) != null)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs:39]: :'(

File: src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs [hunk 77]
```diff
@@ -96,8 +96,8 @@ public async Task OpenSolutionAsync(string solutionFilePath)
```
Comment (CyrusNajmabadi) [inline src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:96]: this commit LGTM>

File: src/Workspaces/MSBuildTest/VisualStudioMSBuildWorkspaceTests.cs [hunk 78]
```diff
@@ -3051,18 +3051,11 @@ public async Task TestOpenProject_CommandLineArgsHaveNoErrors()
```
Comment (CyrusNajmabadi) [inline src/Workspaces/MSBuildTest/VisualStudioMSBuildWorkspaceTests.cs:3083]: this commit LGTM.

File: src/Workspaces/MSBuildTest/VisualStudioMSBuildWorkspaceTests.cs [hunk 79]
```diff
@@ -3271,8 +3271,8 @@ public async Task TestInvalidSolutionFilterDoesNotLoad()
             Assert.Equal(0, workspace.CurrentSolution.ProjectIds.Count);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/MSBuildTest/VisualStudioMSBuildWorkspaceTests.cs:3256]: this commit LGTM.

File: src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs [hunk 80]
```diff
@@ -249,10 +249,26 @@ private static BuildHostProcessKind GetKindForProject(string projectFilePath)
...
+            // Read the XML, prohibiting DTD processing due the the usual security concerns there.
+            using (var fileStream = FileUtilities.OpenRead(projectFilePath))
+            using (var xmlReader = XmlReader.Create(fileStream, s_xmlSettings))
+                document = XDocument.Load(xmlReader);
+        }
+        catch (Exception e) when (e is IOException or XmlException)
+        {
+            // We were unable to read the file; rather than having callers of the build process manager have to deal with this special case
+            // we'll instead just give them a host that corresponds to what they are running as; we know that host unquestionably exists
+            // and the rest of the code can deal with this cleanly.
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs:265]: could you clarify this more.  i don't really undrstand what the comment means.

File: src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj [hunk 81]
```diff
@@ -26,6 +26,11 @@
     <PackageReference Include="Microsoft.Build.Framework" Version="$(RefOnlyMicrosoftBuildFrameworkVersion)" />
     <PackageReference Include="Microsoft.Build.Tasks.Core" Version="$(RefOnlyMicrosoftBuildTasksCoreVersion)" />
     <PackageReference Include="System.Text.Json" Version="$(SystemTextJsonVersion)" />
+
+    <!-- These PackageReferences aren't needed to make our build work, but ensure correct NuGet packaging. We get references to these packages because
+         we have a ProjectReference to BuildHost.csproj, but since it's PrivateAssets="true" they don't flow into this package's package references when packaging. -->
+    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="$(MicrosoftExtensionsLoggingAbstractionsVersion)" />
+    <PackageReference Include="Newtonsoft.Json" Version="$(NewtonsoftJsonVersion)" />
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj:33]: really not happy about newtonsoft dep either.  we're trying to heavily get off of it (both ourselves and razor) since it's so heavyweight.

File: src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj [hunk 82]
```diff
@@ -34,10 +34,24 @@
   </ItemGroup>
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj:34]: ignoring commits like this.  i'm not qualified to comment on this stuff :)

**Review by CyrusNajmabadi — CHANGES_REQUESTED** [review]
Done with pass.  This was mostly good for me *until* i reached the part about us writing our rpc client/server.  Starting an offline convo about this.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs (hunk 62 above)
Comment (stephentoub) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:33]: It looks like the only use is in an Interlocked.Increment? In which case, correct, the volatile here is not needed (nor will it have any impact).

File: src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj (hunk 81 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj:33]: This will be addressed as a mop-up -- today the use of StreamJsonRpc was already using Newtonsoft.Json for marshalling, so it requires a bit of care to ensure the JSON types we were using today will still work and we don't break any other serialization if there are shared types involved. I don't think it's too bad to fix but that'll be a follow-up.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs (hunk 63 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:38]: This is the text encoding _of the JSON representation._ So any nulls in the text are serialized as a JSON string with embedded escaping.

File: src/Workspaces/Core/MSBuild/Host/Mef/MSBuildMefHostServices.cs (hunk 21 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/Host/Mef/MSBuildMefHostServices.cs:18]: > API compat with who?

Somebody could be make MSBuildWorkspaces by referencing MSBuildMefHostServices.DefaultAssemblies, adding their own additional assemblies and then creating the workspace that way. There's no good way to know if anybody does that (and we can't add telemetry), but even then I can absolutely imagine in the future we'd need to add additional assemblies again. It just happens to be a state of the world _today_ we don't need it, I can't predict the future.

File: src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs (hunk 22 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs:65]: This code previously lived in the LSP server project. Since that's not a library but instead the executable where we know we don't have UI threads, we have the ConfigureAwait() analyzer turned off. Once the file moved to the library, then it was required (and indeed, the tooling caught it all automatically.)

File: src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.Worker.cs (hunk 26 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.Worker.cs:193]: Ooh oops, sorry that should have gotten cleaned up since we now have languageName available.

File: src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.cs (hunk 27 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.cs:147]: @CyrusNajmabadi: yes, we could. I don't want to do that engineering work unless we have some belief we need to do it though.

File: src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.cs (hunk 28 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.cs:265]: It's not a task, but it's IAsyncDisposable; the ConfigureAwait here is ensuring the DisposeAsync() is done ConfigureAwait-falsy. Unfortunately the ConfigureAwait in that case seems to lose the underlying type of the object so this was the only way I could figure out how to actually use it.

File: src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs (hunk 29 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs]: Removed in a later commit -- this was just me temporarily removing this code in one commit while the other parts of the system got working.

File: src/Features/Lsif/Generator/Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.csproj (hunk 34 above)
Comment (jasonmalinowski) [reply src/Features/Lsif/Generator/Microsoft.CodeAnalysis.LanguageServerIndexFormat.Generator.csproj:55]: We invoke MSBuild locator in the BulidHost processes and just do the right thing in that case. (Or nearly right thing -- there are some edge cases we might not support, but nobody else does those either.)

File: src/Workspaces/Core/MSBuild.BuildHost/IRemoteProjectFile.cs (hunk 38 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/IRemoteProjectFile.cs]: File path is physical file on disk. In the linked file case, the file appears in solution explorer and can be added in a subdirectory. For example, consider places where we might link in the workspaces layer to some files in the compiler layer, but in the process we then say "oh put it in the CompilerUtilities subfolder". File path is the physical path on disk, logical path is "its in CompilerUtilities".

File: src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs (hunk 39 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs:405]: This is updating the project file and that's the syntax used there, for example:

https://github.com/dotnet/roslyn/blob/4203ffd588ff7a0e05117a5c189649fd3dcc3056/src/EditorFeatures/Core/Microsoft.CodeAnalysis.EditorFeatures.csproj#L27

File: src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs (hunk 41 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs:436]: Yeah it's not ideal at all, but changing it is well out of scope of this PR.

File: src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj (hunk 47 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj:8]: Some of the adding-and-removing references in the project file logic calls into methods in the CLR to ask where the GAC path is which uses unsafe code. You'll see the AllowUnsafeBlocks being removed from the BuildHost project since that is just code moving.

File: src/Workspaces/Core/MSBuild.BuildHost/Build/ProjectBuildManager.cs (hunk 51 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Build/ProjectBuildManager.cs:66]: So when I was working on the change, I did break things at times where exceptions were being thrown. Since the process would then tear down I woudln't even see the full test results!

In a later commit these tests got rewritten anyways.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/Request.cs (hunk 55 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/Request.cs:8]: Sure, can change.

File: src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.Worker.cs (hunk 25 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.Worker.cs:135]: Becuase this now happens in the other process.

File: src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs (hunk 23 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs:156]: These match the names of the folders we deploy in the NuGet package, so yes, these can be hardcoded.

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs:156]: consider doc'ing :)

File: src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs [hunk 83]
```diff
@@ -197,6 +205,23 @@ private void AppendBuildHostCommandLineArgumentsConfigureProcess(ProcessStartInf
...
+#if NET
+        processStartInfo.ArgumentList.Add(argument);
+#else
+        if (processStartInfo.Arguments.Length > 0)
+            processStartInfo.Arguments += ' ';
+
+        if (argument.Contains(' '))
+            processStartInfo.Arguments += '"' + argument + '"';
+        else
+            processStartInfo.Arguments += argument;
```
[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs:237]: Ah good question and probably "yes" now. If you're on Linux you're just taking the #if NET path, so the primary need here is if you're on Windows. And there you can't have quotes in file paths. When I wrote this the only thing being passed were file paths, but now since we're passing MSBuild options there's potential escaping too since those could have quotes. Will dig into this.

File: src/Workspaces/MSBuildTest/Resources/ProjectFiles/CSharp/MSBuildEvaluationErrorWithSyntax.csproj [hunk 84]
```diff
@@ -0,0 +1,47 @@
...
+    <Platform Condition="'$(Platform)' == ''">AnyCPU</Platform>
+    <PlatformTarget>AnyCPU</PlatformTarget>
+    <ProductVersion>8.0.30703</ProductVersion>
+    <SchemaVersion>2.0</SchemaVersion>
+    <ProjectGuid>{686DD036-86AA-443E-8A10-DDB43266A8C4}</ProjectGuid>
+    <OutputType>Library</OutputType>
+    <AppDesignerFolder>Properties</AppDesignerFolder>
+    <RootNamespace>CSharpProject</RootNamespace>
+    <AssemblyName>CSharpProject</AssemblyName>
+   <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
```
[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/Workspaces/MSBuildTest/Resources/ProjectFiles/CSharp/MSBuildEvaluationErrorWithSyntax.csproj]: This was how the indenting was in all the existing files, but I've fixed all of them too.

**Review by dibarbet — COMMENTED** [review]
I think Cyrus already mentioned anything I would mention.  I also didn't look at the RPC part since that is up in the air.

File: src/Workspaces/MSBuildTest/Utilities/DotNetSdkMSBuildInstalled.cs [hunk 85]
```diff
@@ -2,102 +2,24 @@
...
-        public static string? SdkPath { get; private set; } = null;
-
-#if NETCOREAPP
-        private static string? VersionString { get; } = null;
+        private static readonly string? s_skipReason;
 
         static DotNetSdkMSBuildInstalled()
         {
-            var solutionFolder = GetSolutionFolder();
+            // We'll use the same .NET as we use for our own build, since that's the only SDK guaranteed to be installed
```
[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/Workspaces/MSBuildTest/Utilities/DotNetSdkMSBuildInstalled.cs:17]: It's unclear to me if they were, and indeed a yearish ago they weren't: https://github.com/dotnet/roslyn/pull/64830.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs (hunk 63 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:38]: And tests have also been added to cover the null/unicode/newline cases.

File: src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs [hunk 86]
```diff
@@ -0,0 +1,129 @@
...
+
+                // We've disconnected, so cancel any remaining outstanding tasks
+                foreach (var (request, _) in _outstandingRequests.Values)
+                    request.SetException(new System.Exception("The server disconnected unexpectedly."));
+
+                Disconnected?.Invoke(this, EventArgs.Empty);
+            });
+        }
+
+        public event EventHandler? Disconnected;
```
[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs]: Moved.

File: src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs (hunk 75 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs]: This is still a start method, but there's now an equivalent disconnect to stop it.

Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs]: I could make this also return the task, but the caller would just ignore it that case.

File: src/Workspaces/Core/MSBuild/Rpc/RemoteBuildHost.cs (hunk 72 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/Rpc/RemoteBuildHost.cs]: Done.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs (hunk 71 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs]: Added cleaner disconnect; the server would have been shutting down on pipe closure or just the fallback of process kill, but added extra now.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs [hunk 87]
```diff
@@ -0,0 +1,146 @@
...
+                                e = e.InnerException ?? e;
+
+                            response = new Response { Id = request.Id, Exception = $"An exception of type {e.GetType()} was thrown: {e.Message}" };
+                        }
+
+                        var responseJson = JsonConvert.SerializeObject(response, JsonSettings.SingleLineSerializerSettings);
+
+#if DEBUG
+                        // Assert we didn't put a newline in this, since if we did the receiving side won't know how to parse it
+                        Contract.ThrowIfTrue(responseJson.Contains("\r") || responseJson.Contains("\n"));
```
[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs]: This was being covered by tests, otherwise it means we're running this over not-small strings in the case of the larger responses. If you want the extra check sure, it's just extra CPU in production which isn't exactly cheap here!

File: src/Workspaces/MSBuildTest/Utilities/VisualStudioMSBuildInstalled.cs (hunk 12 above)
Comment (jasonmalinowski) [reply src/Workspaces/MSBuildTest/Utilities/VisualStudioMSBuildInstalled.cs:36]: MSBuildLocator generally only allows you to discover MSBuilds that match your runtime so a .NET Core process can't enumerate .NET Framework MSBuilds or vice versa. Before this PR, the tests that tested .NET Framework style projects only ran in net472, and SDK style projects in .NET Core, since that's all that was compatible. Now that we can launch processes to do that for us, we want to run the tests for either TFM as long as there's an MSBuild we can use. Unfortunately due to the current MSBuildLocator behavior we can't do that yet.

I do plan to follow-up with the MSBuild locator owners to discuss adding this. I mentioned it to one of them and there were some concerns about runtime compatibility we'd have to work through (it means loading SDK discovery in .NET Framework processes, and COM in .NET Core processes). I would absolutely like to be able to use MSBuildLocator here though because launching processes here is a bit icky -- it means that a catastrophic bug (say a hung buildhost) can then hang test discovery due to how our conditional facts work.

File: src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj (hunk 15 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj:27]: These are now fine to be transitive, since ILogger is still on the surface area (and also we might still want to use MSBuild inproc for things like SLN reading...)

File: src/Workspaces/Core/MSBuild.BuildHost/IBuildHost.cs (hunk 20 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/IBuildHost.cs]: The user could theoretically have a <ProjectFileReference> in their project to something very random and they have some custom MSBuild that would do something bad.

File: src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj (hunk 15 above)
Comment (JoeRobich) [reply src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj:27]: Ah, ok. ILogger. Was just thinking about packaging and deploying dotnet-format. I guess we currently have these as top-level dependencies and exclude them. So likely no change necessary on our end there.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs (hunk 68 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs]: Extra validation added.

File: src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs (hunk 43 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs]: TryApplyChanges loops through each project and applies changes one at a time. This approach is no different than how it worked before.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs [hunk 88]
```diff
@@ -0,0 +1,167 @@
...
+                e = e.InnerException ?? e;
+
+            response = new Response { Id = request.Id, Exception = $"An exception of type {e.GetType()} was thrown: {e.Message}" };
+        }
+
+        var responseJson = JsonConvert.SerializeObject(response, JsonSettings.SingleLineSerializerSettings);
+
+#if DEBUG
+        // Assert we didn't put a newline in this, since if we did the receiving side won't know how to parse it
+        Contract.ThrowIfTrue(responseJson.Contains("\r") || responseJson.Contains("\n"));
```
Comment (dibarbet) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:154]: If the serialization above throws, or this throws - what happens to the exception? will we be able to know it happened?

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs [hunk 89]
```diff
@@ -0,0 +1,167 @@
...
+
+namespace Microsoft.CodeAnalysis.MSBuild.Rpc;
+
+/// <summary>
+/// Implements the server side of the RPC channel used to communicate with the build host.
+/// </summary>
+/// <remarks>
+/// The RPC system implemented here is pretty close to something like JSON-RPC; however since we need the Build Host to be usable in Source Build
+/// scenarios, we are limited to using only what is either in .NET or can be easily made buildable in Source Build. Thus existing solutions like StreamJsonRpc 
+/// are out. If at some point there is a standard RPC mechanism exposed in .NET or Source Build, we should delete this and use that instead.
```
Comment (dibarbet) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:24]: Do we have a tracking issue on this?  I would like to get out of this situation as soon as possible :)

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs [hunk 90]
```diff
@@ -0,0 +1,167 @@
...
+                    result = task.GetType().GetProperty("Result")!.GetValue(task);
+                }
+                else
+                {
+                    // It's just a simple Task so no result to return
+                    result = null;
+                }
+            }
+
+            response = new Response { Id = request.Id, Value = result is not null ? JToken.FromObject(result) : null };
```
Comment (dibarbet) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:140]: Why do we need to explicitly convert to JToken first, instead of passing it in and letting SerializeObject serialize the original vlaue?

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs [hunk 91]
```diff
@@ -0,0 +1,167 @@
...
+    }
+
+    public int AddTarget(object rpcTarget)
+    {
+        // Loop until we successfully have a new index for this; practically we don't expect this to ever collide, since that'd mean we'd have
+        // billions of long lived projects, but...
+        while (true)
+        {
+            var nextIndex = Interlocked.Increment(ref _nextRpcTargetIndex);
+            if (_rpcTargets.TryAdd(nextIndex, rpcTarget))
```
Comment (dibarbet) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:50]: I'm probably just dumb, but I'm not understanding this loop.  Won't `nextIndex` always be unique?  Why do we need to loop here.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs [hunk 92]
```diff
@@ -0,0 +1,167 @@
...
+
+            var runningTask = Task.Run(() => ProcessRequestAsync(request));
+
+            // We'll add this task to the list of running tasks, and then create a continuation to remove it from the list again; this ensures
+            // that we won't try to remove it before it was added in case the task completed by the time we got here.
+            runningTasks.Add(runningTask);
+            _ = runningTask.ContinueWith(
+                _ => Contract.ThrowIfFalse(runningTasks.Remove(runningTask)),
+                CancellationToken.None,
+                TaskContinuationOptions.ExecuteSynchronously, TaskScheduler.Default);
```
Comment (dibarbet) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:78]: do we need to do anything to explicitly continue if the task throws?

File: src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs [hunk 93]
```diff
@@ -0,0 +1,150 @@
...
+        Task.Run(async () =>
+        {
+            string? line;
+            while ((line = await _receivingStream.TryReadLineOrReturnNullIfCancelledAsync(_shutdownTokenSource.Token).ConfigureAwait(false)) != null)
+            {
+                var response = JsonConvert.DeserializeObject<Response>(line);
+
+                Contract.ThrowIfNull(response);
+
+                Contract.ThrowIfFalse(_outstandingRequests.TryRemove(response.Id, out var completionSourceAndExpectedType), $"We got a response for request ID {response.Id} but that was already completed.");
```
Comment (dibarbet) [inline src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs:57]: are these exceptions logged anywhere?

File: src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs [hunk 94]
```diff
@@ -0,0 +1,150 @@
...
+    private async Task<object?> InvokeCoreAsync(int targetObject, string methodName, List<object?> parameters, Type? expectedReturnType, CancellationToken cancellationToken)
+    {
+        int requestId;
+        var requestCompletionSource = new TaskCompletionSource<object?>(TaskCreationOptions.RunContinuationsAsynchronously);
+
+        // Loop until we successfully have a new index for this; practically we don't expect this to ever collide, since that'd mean we'd have
+        // billions of requests outstanding, but...
+        do
+        {
+            requestId = Interlocked.Increment(ref _nextRequestId);
```
Comment (dibarbet) [inline src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs:128]: Seems like the first requestId here will be 1, whereas the target object id start at 0.  Does it matter?  Probably not but slightly strange we're doing them differently?

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/Readme.md [hunk 95]
```diff
@@ -0,0 +1,13 @@
+﻿# Purpose
+
+This folder implements a custom RPC system between the hosting application and the build host processes. This is implemented only because as of this writing there isn't an RPC system we can use that is compatible with the .NET Source Build environment, so a small one is implemented here that has just enough of what we need. If we're able to use one of the existing solutions out there (StreamJsonRpc, gRPC) we should delete this in favor of those.
+
+# Protocol
+
+The protocol only supports sending a request from the client to the server, and the server sends a reply. Standard out/in is used to communicate with the child process. The request and response are sent as JSON formatted message without newlines, so the message in each direction comprises of a single line. A request consists of a numeric ID which is used to match it up with the response since requests can be overlapped. The ID is just incremented, and may be reused by the client once it's gotten the response for the previous ID. The request also consists of a method name (which matches the method being invoked by .NET Reflection on the server) and the list of parameters.
```
[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/Readme.md:7]: That is encoded in the JSON as a \r or \n. There's now tests to this effect.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs (hunk 90 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:140]: Response being typed as JToken here is needed on the client side, since the client knows what the target type is that's being expected. For example, if we're serializing a list of things across, we have to tell Newtonsoft.Json that we want an ImmutableArray() or whatever else we want, or it might pick the wrong type. So on the deserialization side, we need this as JToken so we can be explicit about the type. Since Request is used for sending too, it's going to be come a JToken as well.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs (hunk 88 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:154]: Practically it's hard to do much at this point: we did the serialization of the actual result data under the try/catch intentionally to report any failures there, so any failure at this point means we can't serialize anything or the input/output itself is dead. So not that we _couldn't_ try to reply with an error of some kind...how can I?

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs (hunk 91 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:50]: We really should add removal and disposal for the project objects too, at which point a long-lived process could theoretically reuse them. This otherwise just copy/paste from the other target code that's doing the same thing.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/Readme.md [hunk 96]
```diff
@@ -0,0 +1,13 @@
...
+
+The server has one or more target objects registered with it. Each targeted object is given a numeric ID, starting with zero. So the initial BuildHost object is target 0, and then any projects loaded (which have their own set of methods) are given target 1, target 2, etc.
+
+The server side takes the method and parameters and invokes methods via reflection. The methods must be public instance methods. Since the communication mechanism is stdin/out and the process is running as the same user as the invoking application, the client/server is not considered to be a security boundary in any way.
+
+The Invoke method on the client takes a CancellationToken, but it can only be cancelled before it actually goes across the wire. Once a request is sent, there is no cancelling it. Any method on the server that takes a CancellationToken as the last argument will get CancellationToken.None filled in for it.
```
[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/Readme.md:13]: In the StreamJsonRpc world, we did pass through cancellation tokens. I don't know if anybody actually did (we don't really use them in the LSP server), and I don't think we have any tests on the correctness of it anyways or whether that leaves MSBuild in some bad state.

File: src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs [hunk 97]
```diff
@@ -386,132 +393,75 @@ public void RemoveDocument(string filePath)
...
-                throw new InvalidOperationException($"Unable to find reference item '{identity?.Name}'");
-            }
+            Contract.ThrowIfNull(_loadedProject, "The project was not loaded.");
 
             var references = _loadedProject.GetItems(ItemNames.Reference);
             MSB.Evaluation.ProjectItem? item = null;
 
             var fileName = Path.GetFileNameWithoutExtension(filePath);
 
-            if (identity != null)
```
Comment (ToddGrun) [inline src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs:480]: >if (identity != null) [](http://example.com/codeflow?start=12&length=21)

is fileName being used anywhere?

File: src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs [hunk 98]
```diff
@@ -386,132 +393,75 @@ public void RemoveDocument(string filePath)
...
-            if (item == null)
-            {
-                var relativePath = PathUtilities.GetRelativePath(_loadedProject.DirectoryPath, filePath);
+            var relativePath = PathUtilities.GetRelativePath(_loadedProject.DirectoryPath, filePath);
 
-                item = references.FirstOrDefault(it => PathUtilities.PathsEqual(it.EvaluatedInclude, filePath)
+            item = references.FirstOrDefault(it => PathUtilities.PathsEqual(it.EvaluatedInclude, filePath)
                                                     || PathUtilities.PathsEqual(it.EvaluatedInclude, relativePath)
                                                     || PathUtilities.PathsEqual(GetHintPath(it), filePath)
                                                     || PathUtilities.PathsEqual(GetHintPath(it), relativePath));
```
Comment (ToddGrun) [inline src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs:452]: It's a nit and was there before, but GetHintPath is potentially called twice here, each one doing a string search through all metadata items

File: src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs [hunk 99]
```diff
@@ -386,132 +393,75 @@ public void RemoveDocument(string filePath)
...
-            }
 
-            // check for partial name match
-            if (item == null && identity != null)
+            if (item is not null)
+                return item;
+
+            var partialName = shortAssemblyName + ",";
+            var items = references.Where(it => it.EvaluatedInclude.StartsWith(partialName, StringComparison.OrdinalIgnoreCase)).ToList();
```
Comment (ToddGrun) [inline src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs:458]: >Where [](http://example.com/codeflow?start=35&length=5)

another nit, but changing this to just use Single instead of Where/ToList/Count/throw would be easier to read

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs (hunk 88 above)
Comment (dibarbet) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:154]: Wondering if we should somehow log to a file or something.  Because right now if this fails will we ever know and figure out that this caused it?

File: src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs (hunk 93 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs:57]: I'm trying to think what the best opportunity would be. I can't just easily throw the exception from somewhere, and since this is an API not running in something like VS I can't just do our usual reporting that way. Thoughts?

File: src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs (hunk 94 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs:128]: I think they both started at one, and then when hardcoding the target index starting at zero seemed superficially better. I can change to match (but that's the only reason) or have the target index start at 1 if you'd like.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/JsonSettings.cs [hunk 100]
```diff
@@ -2,18 +2,22 @@
...
 {
+    public static readonly Encoding StreamEncoding = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);
+
     public static readonly JsonSerializerSettings SingleLineSerializerSettings = new JsonSerializerSettings
     {
         Formatting = Newtonsoft.Json.Formatting.None,
         NullValueHandling = NullValueHandling.Ignore,
         ContractResolver = new CamelCasePropertyNamesContractResolver(),
         TypeNameHandling = TypeNameHandling.None,
+        StringEscapeHandling = StringEscapeHandling.EscapeNonAscii
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/JsonSettings.cs:21]: why?

File: src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs [hunk 101]
```diff
@@ -135,7 +135,17 @@ private void BuildHostProcess_Disconnected(object? sender, EventArgs e)
...
     public async ValueTask DisposeAsync()
     {
-        foreach (var process in _processes.Values)
+        List<BuildHostProcess> processesToDispose;
+
+        // Copy the list out while we're in the lock, otherwise as we dispose these events will get fired, which
+        // may try to mutate the list while we're enumerating.
+        using (await _gate.DisposableWaitAsync().ConfigureAwait(false))
+        {
+            processesToDispose = _processes.Values.ToList();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs:144]: is the addition to _processes also under this lock?

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs (hunk 89 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:24]: agreed.  let's have a tracking bug to remove this high pri in the next 0-2 months.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs [hunk 102]
```diff
@@ -0,0 +1,175 @@
...
+                throw new Exception($"Failure while deserializing '{line}'", innerException: e);
+            }
+
+            var runningTask = Task.Run(() => ProcessRequestAsync(request));
+
+            // We'll add this task to the list of running tasks, and then create a continuation to remove it from the list again; this ensures
+            // that we won't try to remove it before it was added in case the task completed by the time we got here.
+            runningTasks.Add(runningTask);
+            _ = runningTask.ContinueWith(
+                _ => Contract.ThrowIfFalse(runningTasks.Remove(runningTask)),
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:84]: instead of this, should we just make it so that ProcessRequestAsync has a try finall that ends with this?

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs [hunk 103]
```diff
@@ -0,0 +1,175 @@
...
+
+        // Wait until all outstanding requests are processed
+        await Task.WhenAll(runningTasks).ConfigureAwait(false);
+    }
+
+    private async Task ProcessRequestAsync(Request request)
+    {
+        Response response;
+
+        try
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:97]: my preference would a high level method that has the try/catch/finally, and almost nthing else.  and then have another method that is for the body of the try.

File: src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs (hunk 93 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs:57]: woudl like the body of this while to be in its own helper.

File: src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs [hunk 104]
```diff
@@ -0,0 +1,150 @@
...
+
+    public RpcClient(Stream sendingStream, Stream receivingStream)
+    {
+        _sendingStream = new StreamWriter(sendingStream, JsonSettings.StreamEncoding);
+        _receivingStream = new StreamReader(receivingStream, JsonSettings.StreamEncoding);
+    }
+
+    public event EventHandler? Disconnected;
+
+    public void Start()
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs:45]: would prefer async gets pushed out of this as well.

File: src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs [hunk 105]
```diff
@@ -0,0 +1,150 @@
...
+
+    private readonly CancellationTokenSource _shutdownTokenSource = new CancellationTokenSource();
+
+    public RpcClient(Stream sendingStream, Stream receivingStream)
+    {
+        _sendingStream = new StreamWriter(sendingStream, JsonSettings.StreamEncoding);
+        _receivingStream = new StreamReader(receivingStream, JsonSettings.StreamEncoding);
+    }
+
+    public event EventHandler? Disconnected;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs:43]: don't love that there are events here as well :'(

File: src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs [hunk 106]
```diff
@@ -0,0 +1,150 @@
...
+            Method = methodName,
+            Parameters = parameters.SelectAsArray(static p => p is not null ? JToken.FromObject(p) : JValue.CreateNull())
+        };
+
+        var requestJson = JsonConvert.SerializeObject(request, JsonSettings.SingleLineSerializerSettings);
+
+        using (await _sendingStreamSemaphore.DisposableWaitAsync(cancellationToken).ConfigureAwait(false))
+        {
+            _sendingStream.WriteLine(requestJson);
+            _sendingStream.Flush();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs:145]: what ensures the stream doesn't block?

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs (hunk 93 above)
Comment (dibarbet) [reply src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs:57]: Wondering if we want to somehow hookup NFW, or have a specific file log or something.
We can pass in like the vscode extension logs folder and write something there if needed.

**Review by dibarbet — APPROVED** [review]
Definitely need the tracking item removing this, but otherwise fine.  

I think the places I commented on before where we throw, but won't ever see the exception would be nice to somehow log to file / NFW, but not going to block on that especially since we're planning on removing this in a couple months.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs (hunk 102 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:84]: The challenge is ensuring it runs _after_ the Add in that case. The method could add and then remove, but then there's a window of time where the task isn't in the list at all where this loop could then exit.

File: src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs (hunk 104 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs:45]: In this case it wouldn't be useful, since the start/end surrounds the client calls. Think of this like https://learn.microsoft.com/en-us/dotnet/api/streamjsonrpc.jsonrpc.startlistening?view=streamjsonrpc-2.9 which isn't async either.

File: src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs (hunk 105 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs:43]: This is the same as https://learn.microsoft.com/en-us/dotnet/api/streamjsonrpc.jsonrpc.disconnected?view=streamjsonrpc-2.9 which gets fired on stream disconnect.

File: src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs (hunk 101 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs:144]: Yes, see BuildHostProcessManager.GetBuildHostAsync.

File: src/Workspaces/Core/MSBuild.BuildHost/BuildHost.cs (hunk 6 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/BuildHost.cs:140]: This change was reverted and they're task-returning again.

File: src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj (hunk 15 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/Microsoft.CodeAnalysis.Workspaces.MSBuild.csproj:27]: @JoeRobich: no change should be necessary. If you are an app that was not deploying them and using MSBuildLocator, then you're still fine (it was just unnecessary to do that!); if you were deploying them it's still fine now too.

File: src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs (hunk 23 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs]: Will defer to follow-up PR.

File: src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs (hunk 83 above)
[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs:248]: Deferring to follow-up PR.

File: src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs (hunk 24 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs:246]: This is also used to add regular switches to dotnet and friends. It'd look quite odd if those were escaped (which would make people think there were bugs) and potentially also might trigger bugs if those don't expect it.

File: src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.Worker.cs (hunk 26 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/MSBuild/MSBuildProjectLoader.Worker.cs]: Fixed now.

File: src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs (hunk 99 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs:458]: Going to defer this to a follow-up PR, if for no other reason then there aren't many existing tests in this area, so I want to make sure we've got the cases well tested first before we tinker.

File: src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs (hunk 98 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs:452]: Going to defer this to a follow-up PR, if for no other reason then there aren't many existing tests in this area, so I want to make sure we've got the cases well tested first before we tinker.

File: src/Workspaces/CoreTestUtilities/MEF/UseExportProviderAttribute.cs (hunk 30 above)
Comment (jasonmalinowski) [reply src/Workspaces/CoreTestUtilities/MEF/UseExportProviderAttribute.cs:68]: All the MEF stuff is gone except the public API which is now a no-op. If it needs to come back we can do so. (And frankly I was quite surprised this also existed, which seemed like a bit of a hack in this test code to even have to be aware of this.)

File: src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs (hunk 40 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs:421]: Going to defer this along with Todd's comments for cleanup: I believe you are correct, but this code isn't new. It was also throwing prior to this PR and also doing a null check. Will investigate once we have additional tests in place.

File: src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs (hunk 97 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs:480]: Deferring to a mop-up PR.

File: src/Workspaces/MSBuildTest/Utilities/DotNetSdkMSBuildInstalled.cs (hunk 85 above)
[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/Workspaces/MSBuildTest/Utilities/DotNetSdkMSBuildInstalled.cs:17]: Going to use my other PR's existence to track further investigation here.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs (hunk 102 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:84]: (and oh: I actually tried to write it the way you were thinking of first, and then realized it didn't work)

File: src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs (hunk 44 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs:321]: @CyrusNajmabadi not sure I followed this comment -- we _are_ making a single manager that stays alive; we just want to  ensure the processes are shut down once we're done. I could also just leave them around for forever but wasn't sure if that'd create other surprises -- right now we're making this API launch processes when it didn't before, leaving it running might make further surprises.

File: src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs (hunk 46 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs:509]: We could, but out of scope for this PR since it'd have some non-trivial public API impacts. I'll create a follow-up task to track and contain the discussion.

File: src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs (hunk 45 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs:370]: (replied to second comment)

File: src/Workspaces/Core/MSBuild.BuildHost/BuildHost.cs (hunk 52 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/BuildHost.cs:14]: Discussed offline.

File: src/Workspaces/Core/MSBuild.BuildHost/BuildHost.cs (hunk 53 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/BuildHost.cs]: Change was made to pass tokens around (and just the RPC layer is sticking in the CancellationToken.None)

File: src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs (hunk 54 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/MSBuild/ProjectFile/ProjectFile.cs:42]: It's plenty short here.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/Request.cs (hunk 56 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/Request.cs]: Namespace is now specific enough there's not much ambgiuity anymore.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/Request.cs (hunk 57 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/Request.cs]: Now is init-only.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/Request.cs (hunk 58 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/Request.cs]: Explained in the RPC readme.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/Response.cs (hunk 60 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/Response.cs]: This was fixed.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs (hunk 65 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs]: Extracted.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs (hunk 69 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs]: If ValueTask support is needed prior to removal, we can add it at that time.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs (hunk 88 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:172]: Any thrown exceptions here can potentially end up in the console output from the build host process, so we'll still see it (just admittedly in a harder to find place.) The challenge is we don't have a good other place to communicate problems like this.

File: src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs (hunk 93 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs:57]: As mentioned: server exceptions go to the client if they were a part of a client call, otherwise go to stderr which we log. We otherwise don't have a place we can really log some of these, since this at such a low level we won't have NFW in practical scenarios. For example, if it's an end-user app we don't have NFWs at all, and if this is being used in VS Code it'd be Blue-only so we won't have telemetry either.

File: src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs (hunk 106 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs:145]: If your question is "why is this not WriteLineAsync?" I'll switch it. The stream of course could theoretically get blocked up if the other side isn't reading fast enough, but that's always a problem no matter what here. But since nothing else uses the stream other than this write location, we'll just be queuing the writes (the rest of the method is async) and they'll get there eventually.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs (hunk 103 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/RpcServer.cs:107]: Going to leave as is.

File: src/Workspaces/Core/MSBuild.BuildHost/RemoteProjectFile.cs (hunk 42 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/RemoteProjectFile.cs]: File no longer exists.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/JsonSettings.cs [hunk 107]
```diff
@@ -0,0 +1,20 @@
...
+using Newtonsoft.Json.Serialization;
+
+namespace Microsoft.CodeAnalysis.Rpc
+{
+    internal static class JsonSettings
+    {
+        public static readonly JsonSerializerSettings SingleLineSerializerSettings = new JsonSerializerSettings
+        {
+            Formatting = Newtonsoft.Json.Formatting.None,
+            NullValueHandling = NullValueHandling.Ignore,
```
[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/JsonSettings.cs]: Documentation written.

File: src/Workspaces/Core/MSBuild.BuildHost/Rpc/JsonSettings.cs (hunk 100 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild.BuildHost/Rpc/JsonSettings.cs:27]: Comment added: we had a failure in CI on Friday where the stdin/out of the external process was impacted by the process codepage so the Unicode BOM got mangled. Curiously not stable! Either way ensuring that the actual text on the stream stays out of any potential complexity ensures we aren't broken by obscure Windows settings that way.

**Comment by jasonmalinowski** [comment]
I'll be making a GitHub project later this week to track the follow-up work to this PR.

File: src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs (hunk 83 above)
[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/Workspaces/Core/MSBuild/MSBuild/BuildHostProcessManager.cs:248]: https://github.com/dotnet/roslyn/issues/71021 was filed to track this.
