### PR TITLE
Fix CodeFixService.GetProjectDiagnostics to handle compilation end diagn...

### LINKED ISSUE #247: Running Fix All across a project or solution doesn't always fix all
Ported from TFS WorkItem: <b>1114847</b>

------------------------------

<p><b>Repro Steps:</b></p>
<P><B>Affected Branch:</B> <BR><B>Affected Build:</B> <BR><B>Affected Product Language:</B> <BR><BR><B>Steps to reproduce:</B><BR><BR>1. Open Roslyn.sln.</P>
<P>2.&nbsp;Delete the contexts of a bunch of the PublicAPI.txt files.</P>
<P>3. Apply the DeclarePublicAPI fix across the whole solution.</P>
<P>&nbsp;</P>
<P><STRONG>Expected</STRONG></P>
<P>All public APIs across the whole solution are added to the proper PublicAPI.txt files.</P>
<P>&nbsp;</P>
<P><STRONG>Actual</STRONG></P>
<P>Not all PublicAPI.txt files are updated. Sometimes even the ones that are updated are missing items that should be present.</P>

------------------------------

<p><b>Revisions:</b></p>

1) Created By Tom Meschter (1/26/2015 11:14:51 AM)

<p>This is something I ran across while writing the DeclarePublicAPI analyzer and fix. Running Fix All across a document always worked, but when I ran Fix All across a project or solution it didn't actually fix everything--sometimes it only found and fixed a few issues.&nbsp;I wound up running it repeatedly until it found everything.</p>
<p>&nbsp;</p>
<p>My guess is that we don't block waiting for the Solution Crawler to actually find all issues across the solution, and instead the Fix All provider just gets whatever issues it is currently aware of. I think it would be preferable to block until we really have found all the problems and can fix them all at once.</p>

------------------------------

### PR DESCRIPTION
**Pull request by mavasani**
...ostics. Currently it was just force computing all document diagnostics, not the project diagnostics, which executes the compilation end actions.

Additionally, also fix the BatchFixAllProvider to correctly handle compilation end diagnostics.

Fixes #247 

@tmeschter @heejaechang @JohnHamby @srivatsn @shyamnamboodiripad @jmarolf can you please take a look?

### CODE REVIEW

File: src/Features/Core/Diagnostics/EngineV1/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs [hunk 1]
```diff
@@ -312,7 +332,7 @@ public IDECachedDiagnosticGetter(DiagnosticIncrementalAnalyzer owner) : base(own
 
                     foreach (var document in project.Documents)
                     {
-                        await AppendProjectAndDocumentDiagnosticsAsync(state, project, predicate, cancellationToken).ConfigureAwait(false);
+                        await AppendProjectAndDocumentDiagnosticsAsync(state, document, predicate, cancellationToken).ConfigureAwait(false);
```
Comment (heejaechang) [inline src/Features/Core/Diagnostics/EngineV1/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs]: I thought @shyamnamboodiripad fixed this. you might have conflict with @shyamnamboodiripad change.

File: src/Features/Core/Diagnostics/EngineV1/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs [hunk 2]
```diff
@@ -493,12 +513,43 @@ protected override void FilterDiagnostics(AnalysisData analysisData, Func<Diagno
 
         private class IDELatestDiagnosticGetter : LatestDiagnosticsGetter
         {
-            public IDELatestDiagnosticGetter(DiagnosticIncrementalAnalyzer owner) : this(owner, null)
+            private readonly bool _concurrent;
```
Comment (heejaechang) [inline src/Features/Core/Diagnostics/EngineV1/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs]: I thought you added property for this.

File: src/Features/Core/Diagnostics/EngineV1/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs [hunk 3]
```diff
@@ -493,12 +513,43 @@ protected override void FilterDiagnostics(AnalysisData analysisData, Func<Diagno
...
             {
             }
 
-            public IDELatestDiagnosticGetter(DiagnosticIncrementalAnalyzer owner, ImmutableHashSet<string> diagnosticIds) : base(owner, diagnosticIds)
+            public IDELatestDiagnosticGetter(DiagnosticIncrementalAnalyzer owner, ImmutableHashSet<string> diagnosticIds, bool concurrent = false) : base(owner, diagnosticIds)
             {
+                _concurrent = concurrent;
+            }
+
+            protected override bool ConcurrentDocumentComputation => _concurrent;
```
Comment (heejaechang) [inline src/Features/Core/Diagnostics/EngineV1/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs]: ah :)

File: src/Features/Core/Diagnostics/EngineV1/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs (hunk 2 above)
Comment (heejaechang) [inline src/Features/Core/Diagnostics/EngineV1/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs]: since you added field to the base one, why not move this to base as well? and pass down concurrent flag to the base?

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs [hunk 4]
```diff
@@ -228,47 +229,97 @@ public virtual string GetFixAllTitle(FixAllContext fixAllContext)
...
-                            .SelectMany(p => p.Documents);
+                            .ToImmutableArray();
+
+                        var diagnostics = new ConcurrentBag<Diagnostic>();
+                        var options = new ParallelOptions() { CancellationToken = fixAllContext.CancellationToken };
+                        Parallel.ForEach(projectsToFix, options, projectToFix =>
+                        {
+                            fixAllContext.CancellationToken.ThrowIfCancellationRequested();
+
+                            var projectDiagnostics = fixAllContext.GetAllDiagnosticsAsync(projectToFix).WaitAndGetResult(fixAllContext.CancellationToken);
```
Comment (heejaechang) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs]: any reason not using the Task[] and WhenAll pattern we are using other places? this method itself is async so no reason to use Parallel (synchronous one) now.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs [hunk 5]
```diff
@@ -228,47 +229,97 @@ public virtual string GetFixAllTitle(FixAllContext fixAllContext)
...
+                }
+            }
+
+            return builder.ToImmutable();
+        }
 
-                    return documentAndDiagnostics.ToImmutableDictionary();
+        private static async Task<ImmutableDictionary<SyntaxTree, Document>> GetTreeToDocumentMapAsync(ImmutableArray<Project> projects, CancellationToken cancellationToken)
+        {
+            var builder = ImmutableDictionary.CreateBuilder<SyntaxTree, Document>();
```
Comment (heejaechang) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs]: this seems duplicated with the one above.

**Comment by heejaechang** [comment]
:+1:

File: src/Features/Core/Diagnostics/EngineV1/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs (hunk 2 above)
Comment (mavasani) [inline src/Features/Core/Diagnostics/EngineV1/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs]: I don't know what that implies for other diagnostic getters. For now adding this support only for FixAll path, we can add support for other getters when needed.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs (hunk 4 above)
Comment (mavasani) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs]: Thanks, yes I was just too lazy :) I have changed it now, will update the PR after running tests locally.

File: src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs (hunk 5 above)
Comment (mavasani) [inline src/Workspaces/Core/Portable/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs]: One above is reverse map from doc Id to the tree.

**Comment by mavasani** [comment]
I have updated the PR after addressing feedback from Heejae.

File: src/Features/Core/Diagnostics/EngineV1/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs (hunk 1 above)
Comment (shyamnamboodiripad) [inline src/Features/Core/Diagnostics/EngineV1/DiagnosticIncrementalAnalyzer_GetDiagnostics.cs]: Thanks @heejaechang. My changes aren't in yet. It is likely Manish's change will go in first. So I will merge his changes.
