### PR TITLE
Include CodeLens on remaining types and members

### LINKED ISSUE #69583: Codelens to get the references on fields is missing
From vscode-dotnettools created by [Goshlok-git](https://github.com/Goshlok-git): microsoft/vscode-dotnettools#350  

Type: <b>Bug</b>

- Reference of fields are gone, there are only references for methods and classes
- Constant readonly modifier advices for some private fields
alt text
alt text

C# and C# Dev Kit extension is updated
Visual Studio Editor package is updated
.NET 7 is installed

Extension version: 0.9.0
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.63GB free)|
|Process Argv|--crash-reporter-id db49d959-a85e-4b8f-96a2-6f8616d89334|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

### PR DESCRIPTION
**Pull request by sharwell**
Support the following items in the LSP implementation of CodeLens:

* C#
    * Delegates
    * Enum members
    * Fields
    * Events (both full form and field form)
    * Destructors
* Visual Basic
    * Delegates
    * Enum members
    * Fields
    * Events

Fixes #69583

### CODE REVIEW

File: src/Features/CSharp/Portable/CodeLens/CSharpCodeLensMemberFinder.cs [hunk 1]
```diff
@@ -83,5 +84,41 @@ public override void VisitRecordDeclaration(RecordDeclarationSyntax node)
...
+                _memberBuilder.Add(new CodeLensMember(variable, variable.Identifier.Span));
+            }
+        }
+
+        public override void VisitEventDeclaration(EventDeclarationSyntax node)
+        {
+            _memberBuilder.Add(new CodeLensMember(node, node.Identifier.Span));
+        }
+
+        public override void VisitDestructorDeclaration(DestructorDeclarationSyntax node)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeLens/CSharpCodeLensMemberFinder.cs:119]: note: won't ever have results.  so this may be likely to annoy people as it will always have "0 references" showing for it.  Would prefer to not do this.

File: src/Features/CSharp/Portable/CodeLens/CSharpCodeLensMemberFinder.cs [hunk 2]
```diff
@@ -83,5 +84,41 @@ public override void VisitRecordDeclaration(RecordDeclarationSyntax node)
             _memberBuilder.Add(new CodeLensMember(node, node.Identifier.Span));
             base.VisitRecordDeclaration(node);
         }
+
+        public override void VisitDelegateDeclaration(DelegateDeclarationSyntax node)
+        {
+            _memberBuilder.Add(new CodeLensMember(node, node.Identifier.Span));
+        }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeLens/CSharpCodeLensMemberFinder.cs:91]: definitely approve of this.

File: src/Features/CSharp/Portable/CodeLens/CSharpCodeLensMemberFinder.cs [hunk 3]
```diff
@@ -83,5 +84,41 @@ public override void VisitRecordDeclaration(RecordDeclarationSyntax node)
...
+
+        public override void VisitFieldDeclaration(FieldDeclarationSyntax node)
+        {
+            foreach (var variable in node.Declaration.Variables)
+            {
+                _memberBuilder.Add(new CodeLensMember(variable, variable.Identifier.Span));
+            }
+        }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeLens/CSharpCodeLensMemberFinder.cs:104]: 1. what's teh consequence of this in VS for multi-declarator members?
2. does thsi light up code-lens for fields for *all* users in VS.  if so, i think this should be gated behind a user option peopel can opt into.

File: src/Features/CSharp/Portable/CodeLens/CSharpCodeLensMemberFinder.cs (hunk 1 above)
Comment (sharwell) [reply src/Features/CSharp/Portable/CodeLens/CSharpCodeLensMemberFinder.cs:119]: I think that's fine, for a few reasons:

1. Behavior matches current Visual Studio behavior
2. Destructors are rare and generally discouraged, so most users won't ever see the difference
3. For the remaining users, it's less likely someone will ask why it shows 0 than for someone to ask why it's missing

File: src/Features/CSharp/Portable/CodeLens/CSharpCodeLensMemberFinder.cs (hunk 3 above)
Comment (sharwell) [reply src/Features/CSharp/Portable/CodeLens/CSharpCodeLensMemberFinder.cs:104]: This has no impact on Visual Studio. This is a VS Code feature.

**Review by Cosifne — APPROVED** [review]

File: src/Features/CSharp/Portable/CodeLens/CSharpCodeLensMemberFinder.cs (hunk 3 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/CodeLens/CSharpCodeLensMemberFinder.cs:104]: > I'm not sure how to test the UI in VS Code

@dibarbet  can you guide sam on this?

Comment (dibarbet) [reply src/Features/CSharp/Portable/CodeLens/CSharpCodeLensMemberFinder.cs:104]: > I'm not sure how to test the UI in VS Code, but I would expect it to be able to handle this since today it's already possible to declare multiple properties on the same line of code.

If you mean seeing the actual code lens items inside vscode, it should be relatively straightforward.  Basically:
1.  Make sure the C# extension is installed and you can open a C# project
2.  Point the C# extension to your locally built server as described here - https://github.com/dotnet/vscode-csharp/blob/main/CONTRIBUTING.md#using-a-locally-developed-roslyn-server
3.  Reload the window

Comment (sharwell) [reply src/Features/CSharp/Portable/CodeLens/CSharpCodeLensMemberFinder.cs:104]: It's going to end up working like this:
image
