### PR TITLE
"Extract Interface ..." preserves banner at the top of the file

### LINKED ISSUE #23855: "Extract Interface ..." does not preserve banner at the top of the file
**Version Used**: VS 15.5.2

**Steps to Reproduce**:

```csharp
// Copyright ...

public class Foo
{
    public void Bar()
    {
    }
}
```
**Expected Behavior**:
```csharp
// Copyright ...

public interface IFoo
{
    void Bar();
}
```

**Actual Behavior**:
```csharp
public interface IFoo
{
    void Bar();
}
```

### PR DESCRIPTION
**Pull request by ryzngard**
Fixes #23855 

Original from PR #26223

### CODE REVIEW

**Comment by ryzngard** [comment]
@sharwell 	@heejaechang 	this is originally from #26223 and updated to be based on the current implementation.

File: src/Features/Core/Portable/ExtractInterface/AbstractExtractInterfaceService.cs [hunk 1]
```diff
@@ -178,6 +178,10 @@ public async Task<ExtractInterfaceResult> ExtractInterfaceFromAnalyzedTypeAsync(
                 refactoringResult.TypeNode,
                 cancellationToken).ConfigureAwait(false);
 
+            var syntaxFactsService = refactoringResult.DocumentToExtractFrom.GetLanguageService<ISyntaxFactsService>();
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ExtractInterface/AbstractExtractInterfaceService.cs]: nit: we almost always call the local 'syntaxFacts'
