### PR TITLE
Use global properties to iterate over TFMs in MSBuildWorkspace

### LINKED ISSUE #39724: MSBuildWorkspace incorrectly evaluates project when iterating over TargetFrameworks
When a project which uses multi-targeting is loaded into `MSBuildWorkspace`, the code iterates over the values in `TargetFrameworks`, and evaluates the project after setting `TargetFramework` for each value.

This is done here:

https://github.com/dotnet/roslyn/blob/4f38fdac37fabe1414f089de9759f7e1a7d90c03/src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/ProjectFile.cs#L65

This code uses `SetProperty`, which simulates a `TargetFramework` property being set from *inside* the XML of the project.

I believe this to be incorrect, and I think that `SetGlobalProperty` should be used here instead. This is what happens during a real build.

Since the `TargetFramework` property is currently not global, it is set *too late* during evaluation and there are observable side effects, most notably in NuGet imports.

**Version Used**: 3.3.1

**Steps to Reproduce**:

Here's what currently happens for a project with `TargetFrameworks` set to `net48;netcoreapp3.0`, and which includes an `ExamplePackage` NuGet that has `props` and `targets` imports:

On restore, NuGet will generate the following code in the `*.nuget.g.props` file (similar code is also generated in the `*.nuget.g.targets` file):

```XML
<ImportGroup Condition=" '$(TargetFramework)' == 'net48' AND '$(ExcludeRestorePackageImports)' != 'true' ">
  <Import Project="$(NuGetPackageRoot)examplepackage\1.0.0\build\ExamplePackage.props" Condition="Exists('$(NuGetPackageRoot)examplepackage\1.0.0\build\ExamplePackage.props')" />
</ImportGroup>
```

However, this file is included **before** the `TargetFramework` property is set, and therefore the `ExamplePackage.props` import is skipped. On the other hand, the `ExamplePackage.targets` import is included, since the `TargetFramework` property is set by then.

Setting the `TargetFramework` as global would fix this issue and cause the `ExamplePackage.props` file to be imported correctly.

**Expected Behavior**: `ExamplePackage.props` and `ExamplePackage.targets` should be included in the evaluation.

**Actual Behavior**: Only `ExamplePackage.targets` is included in the evaluation.

### PR DESCRIPTION
**Pull request by ltrzesniewski**
This ensures that conditions based on the TFM work correctly in MSBuild files which are included early, like in NuGet props files for instance.

Fixes #39724 - the issue is explained in more detail there.

### CODE REVIEW

**Comment by ltrzesniewski** [comment]
It looks like the CI build failed for an unrelated reason.

File: src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/ProjectFile.cs [hunk 1]
```diff
@@ -56,32 +56,20 @@ public async Task<ImmutableArray<ProjectFileInfo>> GetProjectFileInfosAsync(Canc
...
-                {
-                    var targetFrameworkProp = _loadedProject.GetProperty(PropertyNames.TargetFramework);
-                    _loadedProject.RemoveProperty(targetFrameworkProp);
-                }
-                else
-                {
-                    _loadedProject.SetProperty(PropertyNames.TargetFramework, targetFrameworkValue);
-                }
-
+                _loadedProject.RemoveGlobalProperty(PropertyNames.TargetFramework);
```
Comment (swesonga) [inline src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/ProjectFile.cs]: Removing this global property whether or not it had been set cannot result in any side effects?

Comment (ltrzesniewski) [reply src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/ProjectFile.cs]: I thought it wasn't necessary with global properties, since the only case which could have been impacted is if someone instantiates a `MSBuildWorkspace` with a `TargetFramework` property set to an empty string, which seemed wrong in the first place.

But I guess someone could instantiate `MSBuildWorkspace` with an empty `TargetFramework` but also a non-empty `TargetFrameworks` property to force a single-targeted project to use a different set of TFMs.

I can add some defensive code to handle this case.

Comment (rainersigwald) [reply src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/ProjectFile.cs]: That sounds like a nice change to me--I agree it's funky but possible.

Comment (ltrzesniewski) [reply src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/ProjectFile.cs]: OK I added the safeguard, along with a simple unit test to document the possible use case.

I tried to find possible side effects of always removing the global property, and the only thing I could come up with is when all of the following conditions are combined:

 - You call `MSBuildWorkspace.TryApplyChanges`
 - On a `MSBuildWorkspace` with the `TargetFramework` global property set to an empty string
 - On a project that sets the `TargetFramework` property
 - With changes that affect a project which includes a condition on the `TargetFramework` property that would alter the effect of the MSBuild project `AddItem` or `RemoveItem` method (such as a conditional glob for instance)

Needless to say, that seems *very* contrived and unlikely, so I didn't try to write a unit test which would simulate such a mess, if you're OK with that. I don't think that would bring any real value.

Note that after loading the `MSBuildWorkspace` project, the MSBuild project is thrown away along with the `ProjectFile` instance. It's only used after the initial evaluation in `MSBuildWorkspace.TryApplyChanges`.

**Comment by sharwell** [comment]
@ltrzesniewski thanks for the work to get this resolved 🎉
