### PR TITLE
Fix for UseDeconstruction with default literal

### LINKED ISSUE #25260: "Deconstruct variable declaration" introduces error.
Start with code:

```c#
        (int x, int y) t = default;
        Console.WriteLine(t.x + t.y);
```

Use 'Deconstruct variable declaration' on 't'.  It produces the following code:

```c#
        (int x, int y) = default;
        Console.WriteLine(x + y);
```

This is not allowed because 'default' is not deconstructable to a tuple.

### PR DESCRIPTION
**Pull request by Neme12**
fixes #25260

The previous PR #25282 didn't actually fix the issue with a default literal. The test (which asserts that "use deconstruction" isn't offered) actually passes because it is using the default language version - 7.0, which doesn't allow default literals, therefore the code is incorrect. With C# 7.1 enabled, it *is* offered (and shouldn't be). The implementation is wrong. It is currently checking the type of the expression but a default literal does have an inferred type.

The failure was discovered in #26115 where the test fails when default language version is changed to 8.0.

### CODE REVIEW

**Comment by Neme12** [comment]
Tagging @jcouv @CyrusNajmabadi @jinujoseph who reviewed the old PR.

**Comment by Neme12** [comment]
Can we get this resolved soon so that I don't have to feel bad / ashamed about this for too long? :smile:

**Comment by Neme12** [comment]
retest windows_release_unit32_prtest please

File: src/Features/CSharp/Portable/UseDeconstruction/CSharpUseDeconstructionDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -171,9 +171,16 @@ private void AnalyzeNode(SyntaxNodeAnalysisContext context)
                 return false;
             }
 
+            if (conversion.Exists &&
+                !conversion.IsIdentity &&
+                !conversion.IsTupleConversion &&
+                !conversion.IsTupleLiteralConversion)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/UseDeconstruction/CSharpUseDeconstructionDiagnosticAnalyzer.cs]: probably would benefit from a comment.

Comment (Neme12) [reply src/Features/CSharp/Portable/UseDeconstruction/CSharpUseDeconstructionDiagnosticAnalyzer.cs]: comment added

**Comment by Neme12** [comment]
retest windows_debug_vs-integration_prtest please
