### PR TITLE
'Use local function' suppress if used in expression tree.

### LINKED ISSUE #24344: Convert delegate to local function suggested fix breaks code in expressions
**Version Used**: 
2.6.0.62329 (5429b35d)
Visual Studio 15.5.2

**Steps to Reproduce**:
```csharp
void Method(Action action)
{
            
}

Expression<Action> Example()
{
    Action action = () => Method(null);

    return () => Method(action);
}
```

**Expected Behavior**:
Not to suggest a fix

**Actual Behavior**:
A fix is suggested to replace the delegate with a local function; if fix is implemented it breaks the code as local functions cannot be referenced by expression trees.

### PR DESCRIPTION
**Pull request by MaStr11**
Test case for #24344. Just an additional test case that verifies that this was already fixed in #23136.

Closes #24344

### CODE REVIEW

**Comment by sharwell** [comment]
Rebased and retargeted this test-only change.

File: src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs [hunk 1]
```diff
@@ -1508,6 +1508,27 @@ public void Caller()
 }");
         }
 
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseLocalFunction)]
+        [WorkItem(22672, "https://github.com/dotnet/roslyn/issues/24344")]
```
Comment (MaStr11) [inline src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: @sharwell The work item number is wrong here (22672 instead of 24344). I think I can't correct it because you changed the target branch and if I push it will bring other changes with it. Can you correct this or should we leave it?

Comment (sharwell) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: Sure I can fix it thanks :)

**Comment by sharwell** [comment]
Fixed and just waiting for tests to pass now
