### PR TITLE
Use default parameter values in flow analysis

### LINKED ISSUE #37903: Roslyn incorrectly handles optional parameters when processing [NotNullIfNotNull] annotation
Similar to https://github.com/dotnet/roslyn/issues/37832

**Version Used**: 

```cs
Branch master (10 Aug 2019)
Latest commit c21548 by dotnet-automerge-bot:
Merge pull request #37896 from dotnet/merges/release/dev16.3-preview2-to-master

Merge release/dev16.3-preview2 to master
```

**Steps to Reproduce**:

Compile the following code:
```cs
#nullable enable
using System.Diagnostics.CodeAnalysis;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
public class C {
    [return: NotNullIfNotNull("p")]
    public string? M1(string? p = "defualt") => p;
    
    [return: NotNullIfNotNull("p")]
    public string? M2([Optional, DefaultParameterValue("defualtParameterValue")] string? p) => p;
    
    [return: NotNullIfNotNull("p")]
    public string? M3([CallerMemberName] string? p = null) => p;
    
    void Test()
    {
        var s1 = M1();
        s1.ToString();
        
        var s2 = M2();
        s2.ToString();
        
        var s3 = M3();
        s3.ToString();
    }
}
```

**Expected Behavior**:
No warnings. Roslyn will handle every invocation and insert a non-nullable argument for each of them. According to the called members' signatures non-nullable argument results in a non-nullable return value.

**Actual Behavior**:
```
    warning CS8602: Dereference of a possibly null reference.
    warning CS8602: Dereference of a possibly null reference.
    warning CS8602: Dereference of a possibly null reference.
```
Warnings reported for `s1.ToString()`, `s2.ToString()` and `s3.ToString()`.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #37903

/cc @jcouv. This flows data around in a somewhat disjunct way but I felt that adding lots of additional return values (i.e. `ImmutableArray<BoundExpression> arguments, ImmutableArray<BoundExpression> argumentsNoConversions, ImmutableArray<Conversion> conversions`) which "augment" the original arrays with the default parameter values was also kind of clumsy.

### CODE REVIEW

**Comment by RikkiGibson** [comment]
This change seems to consistently make the build hang. I don't understand why, though, because it seems to build fine locally.

**Comment by AlekseyTs** [comment]
> This change seems to consistently make the build hang. I don't understand why, though, because it seems to build fine locally.

That is probably because CI builds compiler with compiler that includes the change. Try ```build -restore -bootstrap``` locally

**Comment by RikkiGibson** [comment]
So, the on-the-fly creation of default parameter values is causing analysis to run an indefinite number of times on certain

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 1]
```diff
@@ -3542,24 +3566,85 @@ protected override void VisitArguments(ImmutableArray<BoundExpression> arguments
...
+                var previousDisableNullabilityAnalysis = _disableNullabilityAnalysis;
+                _disableNullabilityAnalysis = true;
+                for (int i = 0; i < parametersOpt.Length; i++)
+                {
+                    var parameter = parametersOpt[i];
+                    // fill in unspecified optional arguments
+                    if (parameter.IsOptional && !visitedParameters.Contains(parameter))
+                    {
+                        var annotations = GetParameterAnnotations(parameter);
+                        if (!_defaultValues.TryGetValue((syntax, parameter), out var argument))
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >syntax [](start = 57, length = 6)

Why do we need the syntax as part of the key? I would think that ParameterSymbol -> BoundExpression would be a sufficient map, no?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 2]
```diff
@@ -366,6 +375,7 @@ protected override void Free()
             _updatedSymbolMapOpt = updatedSymbolMapOpt;
             _returnTypesOpt = returnTypesOpt;
             _snapshotBuilderOpt = snapshotBuilderOpt;
+            _defaultValues = defaultValues;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >defaultValues [](start = 29, length = 13)

from our discussion, is it possible to initialize the empty dictionary here? When do we need a dictionary passed in across analyses?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 3]
```diff
@@ -3442,15 +3463,17 @@ protected override void VisitArguments(ImmutableArray<BoundExpression> arguments
...
+            (results, argsToParamsOpt, refKindsOpt) = VisitArgumentsEvaluate(node.Syntax, argumentsNoConversions, refKindsOpt, parametersOpt, argsToParamsOpt, expanded);
 
             // Re-infer method type parameters
             if ((object)method != null && method.IsGenericMethod)
             {
                 if (HasImplicitTypeArguments(node))
                 {
-                    method = InferMethodTypeArguments(node, method, GetArgumentsForMethodTypeInference(argumentsNoConversions, results));
-                    parameters = method.Parameters;
+                    var binder = (node as BoundCall)?.BinderOpt ?? (node as BoundCollectionElementInitializer)?.BinderOpt ?? throw ExceptionUtilities.UnexpectedValue(node);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >BoundCall [](start = 42, length = 9)

Looking at the different kinds of bound nodes that have `BinderOpt` I noticed `BoundIndexerAccess`. and `BoundObjectCreation`. Should they be handled too?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 4]
```diff
@@ -3459,26 +3482,27 @@ protected override void VisitArguments(ImmutableArray<BoundExpression> arguments
...
 
-                    var argumentNoConversion = argumentsNoConversions[i];
+                    var argumentNoConversion = results[i].ArgumentNoConversion;
+                    var argument = i < arguments.Length ? arguments[i] : results[i].ArgumentNoConversion;
                     VisitArgumentConversionAndInboundAssignmentsAndPreConditions(
-                        GetConversionIfApplicable(arguments[i], argumentNoConversion),
+                        GetConversionIfApplicable(argument, argumentNoConversion),
                         argumentNoConversion,
-                        conversions.IsDefault ? Conversion.Identity : conversions[i],
+                        conversions.IsDefault || i >= conversions.Length ? Conversion.Identity : conversions[i],
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >i >= conversions.Length [](start = 49, length = 23)

I didn't understand this. Are we using the right index?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: The LocalRewriter.GetDefaultParameterValue uses the provided Syntax to get the actual values when CallerMemberName, CallerLineNumber, etc. attributes are in use. The produced BoundExpression uses the containing invocation such as `BoundCall` for its `Syntax` property.

It's possible we could make it work without actually providing syntax to the BoundExpression for the default argument but I'm not sure what would break/need to change as a result.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 5]
```diff
@@ -3542,24 +3566,85 @@ protected override void VisitArguments(ImmutableArray<BoundExpression> arguments
...
             int n = arguments.Length;
-            if (n == 0)
+            if (n == 0 && parametersOpt.IsDefaultOrEmpty)
             {
-                return ImmutableArray<VisitArgumentResult>.Empty;
+                return (ImmutableArray<VisitArgumentResult>.Empty, argsToParamsOpt, refKindsOpt);
             }
-            var builder = ArrayBuilder<VisitArgumentResult>.GetInstance(n);
+
+            var visitedParameters = PooledHashSet<ParameterSymbol>.GetInstance();
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >() [](start = 78, length = 2)

can use `n` as size hint?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: This conversions array was not resized as part of `VisitArgumentsEvaluate`.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 1 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Makes sense. May be worth a comment

---
In reply to: [329248471](https://github.com/dotnet/roslyn/pull/38788#discussion_r329248471) [](ancestors = 329248471)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 6]
```diff
@@ -3542,24 +3566,85 @@ protected override void VisitArguments(ImmutableArray<BoundExpression> arguments
...
+                    argRefKindsBuilder = null;
+                }
+                else
+                {
+                    argRefKindsBuilder = ArrayBuilder<RefKind>.GetInstance(parametersOpt.Length);
+                    argRefKindsBuilder.AddRange(refKindsOpt);
+                }
+
+                var previousDisableNullabilityAnalysis = _disableNullabilityAnalysis;
+                _disableNullabilityAnalysis = true;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >true [](start = 46, length = 4)

consider adding a comment too

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Perhaps, I only did these because the overload of InferMethodTypeArguments that I deleted would switch on these two types and reject any other types.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 7]
```diff
@@ -207,6 +210,11 @@ public VisitArgumentResult(VisitResult visitResult, Optional<LocalState> stateFo
         /// </summary>
         private VisitResult _currentConditionalReceiverVisitResult;
 
+        /// <summary>
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >summary [](start = 13, length = 7)

May be worth adding a note as to why we save/cache these

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 1 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Also, could you add a test with CallerExpression or some other attribute, if we don't have one already?

---
In reply to: [329250289](https://github.com/dotnet/roslyn/pull/38788#discussion_r329250289) [](ancestors = 329250289,329248471)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 8]
```diff
@@ -3542,24 +3566,85 @@ protected override void VisitArguments(ImmutableArray<BoundExpression> arguments
...
+                for (int i = 0; i < parametersOpt.Length; i++)
+                {
+                    var parameter = parametersOpt[i];
+                    // fill in unspecified optional arguments
+                    if (parameter.IsOptional && !visitedParameters.Contains(parameter))
+                    {
+                        var annotations = GetParameterAnnotations(parameter);
+                        if (!_defaultValues.TryGetValue((syntax, parameter), out var argument))
+                        {
+                            _defaultValues[(syntax, parameter)] = argument = LocalRewriter.GetDefaultParameterValue(syntax, parameter, ThreeState.Unknown, localRewriter: null, _binder, Diagnostics);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >Unknown [](start = 146, length = 7)

Should this be `ThreeState.True` instead?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 9]
```diff
@@ -3542,24 +3566,85 @@ protected override void VisitArguments(ImmutableArray<BoundExpression> arguments
...
-                FlowAnalysisAnnotations parameterAnnotations = GetCorrespondingParameter(i, parameters, argsToParamsOpt, expanded).Annotations;
-                builder.Add(VisitArgumentEvaluate(arguments[i], GetRefKind(refKindsOpt, i), parameterAnnotations));
+                var (parameter, _, parameterAnnotations, _) = GetCorrespondingParameter(i, parametersOpt, argsToParamsOpt, expanded);
+
+                resultsBuilder.Add(VisitArgumentEvaluate(arguments[i], GetRefKind(refKindsOpt, i), parameterAnnotations));
+                visitedParameters.Add(parameter);
+            }
+
+            if (!parametersOpt.IsDefaultOrEmpty)
+            {
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >{ [](start = 12, length = 1)

It may also be good to leave a comment explaining that it's okay to analyze the optional arguments after the real arguments because they won't have any side-effects (constants only)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 10]
```diff
@@ -23146,6 +23146,94 @@ static void M(C c, string? p1, string? p2)
             CompileAndVerify(comp2);
         }
 
+        [Fact]
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >Fact [](start = 9, length = 4)

Please add a test with attribute on a local function. It will fail for now, but will pass sometime soon ;-)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 4 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: I see. The important thing is that the extended arrays start the same as the original arrays, and only have some items appended at the end.
Thanks

---
In reply to: [329248859](https://github.com/dotnet/roslyn/pull/38788#discussion_r329248859) [](ancestors = 329248859)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 5 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: This seems reasonable, as long as it doesn't cause a bad behavior when we have a call with a large params array.

---
In reply to: [329248589](https://github.com/dotnet/roslyn/pull/38788#discussion_r329248589) [](ancestors = 329248589)

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Scratch that, PooledHashSet.GetInstance does not actually accept a size hint.

---
In reply to: [329263552](https://github.com/dotnet/roslyn/pull/38788#discussion_r329263552) [](ancestors = 329263552,329248589)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Adding additional comments to the declaration of _defaultValues

---
In reply to: [329250289](https://github.com/dotnet/roslyn/pull/38788#discussion_r329250289) [](ancestors = 329250289,329248471)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: The reason I only handled these two is that the InferMethodTypeArguments overload that I deleted only handled these two.

---
In reply to: [329246636](https://github.com/dotnet/roslyn/pull/38788#discussion_r329246636) [](ancestors = 329246636)

Comment (jcouv) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Could you add a test with indexer and default parameter?

---
In reply to: [329251239](https://github.com/dotnet/roslyn/pull/38788#discussion_r329251239) [](ancestors = 329251239)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 5 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Ah, good point

---
In reply to: [329263995](https://github.com/dotnet/roslyn/pull/38788#discussion_r329263995) [](ancestors = 329263995,329263552,329248589)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 8 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: I think so, because we know we are in an invocation. It seems that passing Unknown makes it examine the syntax to decide if the default argument is contained in a kind of syntax where caller info makes sense.

---
In reply to: [329256664](https://github.com/dotnet/roslyn/pull/38788#discussion_r329256664) [](ancestors = 329256664)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: I will add the test with the expectation that NotNullIfNotNull will not have an effect.

---
In reply to: [329269700](https://github.com/dotnet/roslyn/pull/38788#discussion_r329269700) [](ancestors = 329269700,329251239)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: It seems that we don't, I somehow got the impression that we did when I was troubleshooting the bootstrap build

---
In reply to: [329245259](https://github.com/dotnet/roslyn/pull/38788#discussion_r329245259) [](ancestors = 329245259)

**Comment by RikkiGibson** [comment]
@jcouv @dotnet/roslyn-compiler sorry that I neglected this PR for a bit, I have addressed review comments and have the bootstrap build working again.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 11]
```diff
@@ -365,6 +377,7 @@ protected override void Free()
             _analyzedNullabilityMapOpt = analyzedNullabilityMapOpt;
             _returnTypesOpt = returnTypesOpt;
             _snapshotBuilderOpt = snapshotBuilderOpt;
+            _defaultValues = new Dictionary<(SyntaxNode, ParameterSymbol), BoundExpression>();
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >new Dictionary<(SyntaxNode, ParameterSymbol), BoundExpression>() [](start = 29, length = 64)

Consider using `PooledDictionary<,>` and delaying the allocation until the first use, similar to other dictionary fields.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 12]
```diff
@@ -3608,24 +3626,81 @@ protected override void VisitArguments(ImmutableArray<BoundExpression> arguments
...
             {
-                FlowAnalysisAnnotations parameterAnnotations = GetCorrespondingParameter(i, parameters, argsToParamsOpt, expanded).Annotations;
-                builder.Add(VisitArgumentEvaluate(arguments[i], GetRefKind(refKindsOpt, i), parameterAnnotations));
+                var (parameter, _, parameterAnnotations, _) = GetCorrespondingParameter(i, parametersOpt, argsToParamsOpt, expanded);
+
+                resultsBuilder.Add(VisitArgumentEvaluate(arguments[i], GetRefKind(refKindsOpt, i), parameterAnnotations));
+                visitedParameters.Add(parameter);
+            }
+
+            if (!parametersOpt.IsDefaultOrEmpty)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >) [](start = 47, length = 1)

Can we skip this block (and avoid allocating new arrays for `arguments`, etc.) if `visitedParameters.Count == parametersOpt.Length`?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: This is the scenario where we know every parameter was visited, right? Maybe we can change the condition to `!parametersOpt.IsDefaultOrEmpty && parametersOpt.Length != visitedParameters.Count`

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 13]
```diff
@@ -23140,6 +23140,154 @@ static void M(C c, string? p1, string? p2)
...
+    void M2()
+    {
+        _ = M1(p2: null).ToString();
+        _ = M1(p1: null).ToString(); // 1
+        _ = M1(p1: ""hello"", p2: null).ToString();
+        _ = M1(p2: ""hello"", p1: null).ToString(); // 2
+        _ = M1(p1: null, p2: ""hello"").ToString(); // 3
+        _ = M1(p2: null, p1: ""hello"").ToString();
+    }
+}
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Are we testing cases where the optional value is `null`?
```C#
using System.Diagnostics.CodeAnalysis;
public class C
{
    [return: NotNullIfNotNull("p1")]
    string? M1(string? p1 = null, string? p2 = null) => p1;

    void M2()
    {
        _ = M1(p2: "a").ToString(); // 1
        _ = M1(p1: "b").ToString();
        _ = M1(p1: "a", p2: null).ToString();
        _ = M1(p2: "a", p1: null).ToString(); // 2
        _ = M1(p1: null, p2: "b").ToString(); // 3
        _ = M1(p2: null, p1: "b").ToString();
    }
}
```

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Looks like no, will add the test

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 14]
```diff
@@ -3608,24 +3625,82 @@ protected override void VisitArguments(ImmutableArray<BoundExpression> arguments
...
+                for (int i = 0; i < parametersOpt.Length; i++)
+                {
+                    var parameter = parametersOpt[i];
+                    // Fill in unspecified optional arguments
+                    // Note that the order of visiting the optional arguments doesn't matter because they are constants.
+                    if (parameter.IsOptional && !visitedParameters.Contains(parameter))
+                    {
+                        var annotations = GetParameterAnnotations(parameter);
+
+                        _defaultValues ??= new Dictionary<(SyntaxNode, ParameterSymbol), BoundExpression>();
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >Dictionary [](start = 47, length = 10)

`PooledDictionary`

**Comment by cston** [comment]
>         {

`_defaultValues?.Free();`

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:347 in a320fcb. [](commit_id = a320fcb6777954c2a321a61dba733c2ec83a4d2f, deletion_comment = False)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 14 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Oops, pushed too soon.
