### PR TITLE
Fix missing extension-type symbol handling in VarianceSafety.cs

### LINKED ISSUE #78222: Compiler crash when attempting to define extension inside interface type
**Version Used**: 
4.14.0-3.25179.1 (304768b7)

**Steps to Reproduce**:

Attempt to compile the following code:
```cs
interface IInterface
{
    extension(object)
    {
    }
}
```

**Expected Behavior**:
`CS9283: Extensions must be declared in a top-level, non-generic, static class`

**Actual Behavior**:
`Process terminated. System.InvalidOperationException: Unexpected value 'Extension' of type 'Microsoft.CodeAnalysis.TypeKind'`

### PR DESCRIPTION
**Pull request by bernd5**
fixes #78222

Add missing handling for extension type symbols in variance safety check...

### CODE REVIEW

File: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs [hunk 1]
```diff
@@ -947,6 +947,48 @@ public static class Extensions
         Assert.Equal("Extensions.<>E__1<T>", symbol2.ToTestDisplayString());
     }
 
+    [Fact]
+    [WorkItem("https://github.com/dotnet/roslyn/issues/78222")]
+    public void ExtensionInInterface()
+    {
+        var src = """
+interface IInterface
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests.cs:955]: Let's add tests to cover more containers: structs, records, enums, ...

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 5)

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 5)

**Comment by jcouv** [comment]
Merged/squashed. Thanks for the contribution @bernd5 !
