### PR TITLE
No "implement implicitly" when class implements no interface

### LINKED ISSUE #48027: CSharpImplementImplicitlyCodeRefactoringProvider crash
```
System.InvalidOperationException : Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at System.Linq.ImmutableArrayExtensions.First[T](ImmutableArray`1 immutableArray)
   at async Microsoft.CodeAnalysis.CSharp.ImplementInterface.AbstractChangeImplementionCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

Repro code (try invoke codeactions at $$):
```cs
using System;
using System.Collections;


namespace Foo
{
    public class Bar
    {

        IEnumerator $IEnumerable$.GetEnumerator()
        {
            throw new NotImplementedException();
        }
    }
}

```

### PR DESCRIPTION
**Pull request by louis-z**
Fixes #48027

- If a method implements explicitly a method but its class implements no interface (and thus the code does not compile), don't suggest switching to an implicit implementation.

### CODE REVIEW

File: src/Features/CSharp/Portable/ImplementInterface/AbstractChangeImplementionCodeRefactoringProvider.cs [hunk 1]
```diff
@@ -69,7 +69,10 @@ public sealed override async Task ComputeRefactoringsAsync(CodeRefactoringContex
             // member.  Interface member names are the expected names that people expect to see
             // (like "GetEnumerator"), instead of the auto-generated names that the compiler makes
             // like: "System.IEnumerable.GetEnumerator"
-            directlyImplementedMembers.AddRange(member, member.ExplicitOrImplicitInterfaceImplementations());
+            var interfaceImplementations = member.ExplicitOrImplicitInterfaceImplementations();
+            if (interfaceImplementations.Length == 0)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ImplementInterface/AbstractChangeImplementionCodeRefactoringProvider.cs:73]: doc this case in the code.

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/Features/CSharp/Portable/ImplementInterface/AbstractChangeImplementionCodeRefactoringProvider.cs (hunk 1 above)
Comment (davidwengier) [inline src/Features/CSharp/Portable/ImplementInterface/AbstractChangeImplementionCodeRefactoringProvider.cs:73]: Would it be clearer to add logic to `CheckMemberCanBeConverted` that checks if the interface appears in the `member.ContainingType.AllInterfaces` list?

This feels a little like this is working by side effect of `ExplicitOrImplicitInterfaceImplementations` iterating through the interfaces.

Comment (louis-z) [reply src/Features/CSharp/Portable/ImplementInterface/AbstractChangeImplementionCodeRefactoringProvider.cs:73]: Yes it might make things a bit clearer.

@CyrusNajmabadi what do you think?

Comment (louis-z) [reply src/Features/CSharp/Portable/ImplementInterface/AbstractChangeImplementionCodeRefactoringProvider.cs]: Ok so I went ahead with that idea anyway. I had to duplicate code though, since `CheckMemberCanBeConverted` lies in the concrete classes.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/ImplementInterface/AbstractChangeImplementionCodeRefactoringProvider.cs]: works for me :)

Comment (louis-z) [reply src/Features/CSharp/Portable/ImplementInterface/AbstractChangeImplementionCodeRefactoringProvider.cs]: Done.

I feel the code is now self-documenting enough. Do you? 🤔

**Review by davidwengier — APPROVED** [review]

**Review by genlu — APPROVED** [review]
Thanks!

**Review by jmarolf — APPROVED** [review]
