### PR TITLE
Restore SemanticModel behavior for invocations of not invocable targets

### LINKED ISSUE #79930: Regression in SemanticModel.GetSymbolInfo?
This test passes when run against Roslyn versions 3.11.0, 4.0.1, 4.4.0, 4.8.0 and 4.12.0:
```
[TestMethod]
public async Task T1()
{
    var code = """
public class OuterClass
{
    void M()
    {
        var s = OuterClass.InnerClass();
    }

    public class InnerClass
    {
    }
}
""";

    var syntaxTree = CSharpSyntaxTree.ParseText(code);
    var syntaxRoot = await syntaxTree.GetRootAsync().ConfigureAwait(false);
    var invocationNode = syntaxRoot.DescendantNodes().OfType<InvocationExpressionSyntax>().Single();
    var expressionNode = invocationNode.Expression;

    var compilation = CSharpCompilation.Create(
        "scratch",
        [syntaxTree],
        await ReferenceAssemblies.NetStandard.NetStandard20.ResolveAsync(LanguageNames.CSharp, default).ConfigureAwait(false));

    var semanticModel = compilation.GetSemanticModel(syntaxTree);
    var diagnostics = semanticModel.GetDiagnostics();
    Assert.HasCount(1, diagnostics);
    Assert.AreEqual("CS1955", diagnostics[0].Id); // Non-invocable member ‘{0}’ cannot be used like a method

    var info = semanticModel.GetSymbolInfo(expressionNode);
    Assert.IsNull(info.Symbol);
    Assert.AreEqual(CandidateReason.NotInvocable, info.CandidateReason);
    Assert.HasCount(1, info.CandidateSymbols);
    Assert.IsInstanceOfType<INamedTypeSymbol>(info.CandidateSymbols[0]);
}
```

When running against 4.14.0, this fails because there is no candidate reported.

Is this a regression or an intentional change?

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #79930

### CODE REVIEW

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetSemanticInfoTests.cs [hunk 1]
```diff
@@ -268,14 +268,18 @@ class K
...
-            Assert.Null(semanticInfo.ConvertedType);
+            Assert.Equal("System.Int32", semanticInfo.Type.ToTestDisplayString());
+            Assert.Equal(TypeKind.Struct, semanticInfo.Type.TypeKind);
+            Assert.Equal("System.Int32", semanticInfo.ConvertedType.ToTestDisplayString());
+            Assert.Equal(TypeKind.Struct, semanticInfo.ConvertedType.TypeKind);
             Assert.Equal(ConversionKind.Identity, semanticInfo.ImplicitConversion.Kind);
 
             Assert.Null(semanticInfo.Symbol);
-            Assert.Equal(CandidateReason.None, semanticInfo.CandidateReason);
-            // Tracked by https://github.com/dotnet/roslyn/issues/78957 : public API, see if we can restore a behavior closer to previous (ie. returning the field as candidate symbol)
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetSemanticInfoTests.cs:277]: Does this PR fix the "Improve handling of BoundBadExpression in GetMemberGroup" bullet in https://github.com/dotnet/roslyn/issues/78957? If so, consider adding "Related to" in the PR description and making sure to check off the bullet when merged.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetSemanticInfoTests.cs:277]: > Does this PR fix the "Improve handling of BoundBadExpression in GetMemberGroup" bullet in #78957?

I don't know what that bullet is about exactly. @jcouv?

Comment (jcouv) [reply src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetSemanticInfoTests.cs:277]: That bullet refers to `PreferMoreSpecific_Static_MethodAndProperty`, `PreferMoreSpecific_Static_MethodAndProperty_Generic`, `TwoExtensions_MethodAndProperty`. 
They have tracking links: `Assert.Empty(model.GetMemberGroup(memberAccess)); // Tracked by https://github.com/dotnet/roslyn/issues/78957 : consider handling BoundBadExpression better`
I'll update the bullet in tracking issue to reference those tests

**Review by jcouv — APPROVED** [review]
LGTM Thanks (commit 1)
