### PR TITLE
Handle cycles in IsValueType and IsReferenceType binding constraints

### LINKED ISSUE #45713: StackOverflowException in BindTypeParameterConstraints
`StackOverflowException` in `BindTypeParameterConstraints()` compiling the following:
```C#
class A<T>
{
    internal interface IA { }
}

#nullable enable

class B<T> : A<T>
    where T : B<T>.IA
{
}
```

### LINKED ISSUE #45863: Stack overflow error while building code with nested interfaces
**Version Used**: 
.Net Core SDK 3.1.301

**Steps to Reproduce**:
1. Create new C# console application project (.net core 3.1, C# 8.0)
2. **Enable Nullable reference types**. .csproj looks like:
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>
</Project>
```
3. Add next code to Program.cs:
```
public interface IInterface
{
    public interface INestedInterface<T> 
    {
    }

    public interface INestedSubInterface<T1, T2> : INestedInterface<T1>
        where T2 : INestedSubInterface<T1, T2>.IDoubleNestedInterface
    {
        public interface IDoubleNestedInterface
        {
        }
    }
}
```
4. `dotnet build NestedInterfaces.csproj`

**Alternative Steps to Reproduce**:
1. Clone solution from https://github.com/mordraugwe/NestedInterfaces
2. `dotnet build NestedInterfaces.csproj`

**Expected Behavior**:
`Build succeeded.`

**Actual Behavior**:
```
Build FAILED.
C:\Program Files\dotnet\sdk\3.1.301\Roslyn\Microsoft.CSharp.Core.targets(59,5): error : Stack overflow. [D:\dev\NestedInterfaces\NestedInterfaces\NestedInterfaces.csproj]
```

While writing this code in Visual Studio 16.6.3 it hangs and crashes. [Issue has been reported](https://developercommunity.visualstudio.com/content/problem/1108255/visual-studio-1663-crashes-while-parsing-nested-in.html)
JetBrains Rider 2020.1.4 and Visual Studio Code with Omni plugin allows writing code but `dotnet build` gives Stack overflow error.

### PR DESCRIPTION
**Pull request by cston**
Ignore `#nullable` context when evaluating `IsValueType` and `IsReferenceType`.

Fixes #45713.
Fixes #45863.

Binding constraints in the repros results in a call to `TypeWithAnnotations.SubstituteTypeCore()` which calls `IsTypeParameterDisallowingAnnotationsInCSharp8()` which calls `SourceTypeParameterSymbol.IsValueType`. The call to `IsValueType` requires binding constraints. It seems unnecessary to have `IsValueType` or `IsReferenceType` depend on nullability though.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Symbols/Source/TypeParameterConstraintClause.cs [hunk 1]
```diff
@@ -212,6 +218,15 @@ static void adjustConstraintTypes(Symbol container, ImmutableArray<TypeWithAnnot
 
     internal static class TypeParameterConstraintClauseExtensions
     {
+        internal static bool IsSet(this ImmutableArray<TypeParameterConstraintClause> constraintClauses, bool canIgnoreNullableContext)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/TypeParameterConstraintClause.cs:221]: >IsSet [](start = 29, length = 5)

HasValue?

File: src/Compilers/CSharp/Portable/Symbols/TypeParameterBounds.cs [hunk 2]
```diff
@@ -17,6 +17,16 @@ internal sealed class TypeParameterBounds
     {
         public static readonly TypeParameterBounds Unset = new TypeParameterBounds();
 
+        /// <summary>
+        /// Creates a "early" bound instance that has constraint types set
+        /// but no other fields.
+        /// </summary>
+        public TypeParameterBounds(ImmutableArray<TypeWithAnnotations> constraintTypes)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/TypeParameterBounds.cs:24]: >TypeParameterBounds [](start = 15, length = 19)

Would it make sense to keep this constructor private and to add a factory method with very specific name for consumers to use?

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs [hunk 3]
```diff
@@ -251,15 +251,18 @@ private ImmutableArray<TypeParameterSymbol> MakeTypeParameters(DiagnosticBag dia
...
             var clauses = _lazyTypeParameterConstraints;
-            if (clauses.IsDefault)
+            if (!clauses.HasValue(canIgnoreNullableContext))
             {
                 var diagnostics = DiagnosticBag.GetInstance();
-                if (ImmutableInterlocked.InterlockedInitialize(ref _lazyTypeParameterConstraints, MakeTypeParameterConstraints(diagnostics)))
+                if (ImmutableInterlocked.InterlockedCompareExchange(ref _lazyTypeParameterConstraints, MakeTypeParameterConstraints(canIgnoreNullableContext, diagnostics), clauses) == clauses)
                 {
-                    this.AddDeclarationDiagnostics(diagnostics);
+                    if  (_lazyTypeParameterConstraints.HasValue(canIgnoreNullableContext: false))
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs:262]: nit: formatting

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs [hunk 4]
```diff
@@ -251,15 +251,18 @@ private ImmutableArray<TypeParameterSymbol> MakeTypeParameters(DiagnosticBag dia
...
-        internal TypeParameterConstraintClause GetTypeParameterConstraintClause(int ordinal)
+        internal TypeParameterConstraintClause GetTypeParameterConstraintClause(bool canIgnoreNullableContext, int ordinal)
         {
             var clauses = _lazyTypeParameterConstraints;
-            if (clauses.IsDefault)
+            if (!clauses.IsSet(canIgnoreNullableContext))
             {
                 var diagnostics = DiagnosticBag.GetInstance();
-                if (ImmutableInterlocked.InterlockedInitialize(ref _lazyTypeParameterConstraints, MakeTypeParameterConstraints(diagnostics)))
+                if (ImmutableInterlocked.InterlockedCompareExchange(ref _lazyTypeParameterConstraints, MakeTypeParameterConstraints(canIgnoreNullableContext, diagnostics), clauses) == clauses)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs:260]: >InterlockedCompareExchange [](start = 41, length = 26)

Is there a possibility of a race here? If a thread with ```canIgnoreNullableContext==true``` completes first, is the thread with ```canIgnoreNullableContext==true``` going to return expected value?

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs [hunk 5]
```diff
@@ -215,23 +215,27 @@ internal override void EnsureAllConstraintsAreResolved()
...
-            if (!_lazyBounds.IsSet())
+            var currentBounds = _lazyBounds;
+            if (!currentBounds.IsSet(canIgnoreNullableContext))
             {
                 var diagnostics = DiagnosticBag.GetInstance();
-                var bounds = this.ResolveBounds(inProgress, diagnostics);
+                var bounds = this.ResolveBounds(inProgress, canIgnoreNullableContext, diagnostics);
 
-                if (ReferenceEquals(Interlocked.CompareExchange(ref _lazyBounds, bounds, TypeParameterBounds.Unset), TypeParameterBounds.Unset))
+                if (ReferenceEquals(Interlocked.CompareExchange(ref _lazyBounds, bounds, currentBounds), currentBounds))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs:229]: >Interlocked.CompareExchange(ref _lazyBounds, bounds, currentBounds), currentBounds) [](start = 36, length = 83)

Is there a race here?

**Comment by AlekseyTs** [comment]
>         public override ImmutableArray<TypeParameterConstraintClause> GetTypeParameterConstraintClauses()

Should we add ```bool canIgnoreNullableContext``` here as well?

---
Refers to: src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs:284 in cbbf3b8. [](commit_id = cbbf3b8fe55674b135b0594273b9e6e7ca2b8ca0, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>         public override ImmutableArray<TypeParameterConstraintClause> GetTypeParameterConstraintClauses()

Should we add bool canIgnoreNullableContext here as well?

---
Refers to: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs:464 in cbbf3b8. [](commit_id = cbbf3b8fe55674b135b0594273b9e6e7ca2b8ca0, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs [hunk 6]
```diff
@@ -63,7 +63,7 @@ internal ImmutableArray<TypeWithAnnotations> TypeArgumentsWithDefinitionUseSiteD
 
             foreach (var typeArgument in result)
             {
-                typeArgument.Type.OriginalDefinition.AddUseSiteDiagnostics(ref useSiteDiagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs:66]: >Type [](start = 29, length = 4)

Why not simply access DefaultType here?

File: src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs [hunk 7]
```diff
@@ -72,7 +72,7 @@ internal ImmutableArray<TypeWithAnnotations> TypeArgumentsWithDefinitionUseSiteD
         internal TypeWithAnnotations TypeArgumentWithDefinitionUseSiteDiagnostics(int index, ref HashSet<DiagnosticInfo> useSiteDiagnostics)
         {
             var result = TypeArgumentsWithAnnotationsNoUseSiteDiagnostics[index];
-            result.Type.OriginalDefinition.AddUseSiteDiagnostics(ref useSiteDiagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs:75]: >Type [](start = 19, length = 4)

Why not simply access DefaultType here?

File: src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs [hunk 8]
```diff
@@ -428,6 +430,9 @@ public bool IsAtLeastAsVisibleAs(Symbol sym, ref HashSet<DiagnosticInfo> useSite
             return NullableUnderlyingTypeOrSelf.IsAtLeastAsVisibleAs(sym, ref useSiteDiagnostics);
         }
 
+        public void AddUseSiteDiagnostics(ref HashSet<DiagnosticInfo> useSiteDiagnostics) =>
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs:433]: >AddUseSiteDiagnostics [](start = 20, length = 21)

AddDefinitionUseSiteDiagnostics?

File: src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs [hunk 9]
```diff
@@ -468,9 +473,18 @@ internal TypeWithAnnotations SubstituteTypeCore(AbstractTypeMap typeMap)
 
             NullableAnnotation newAnnotation;
 
-            Debug.Assert(!IsIndexedTypeParameter(newTypeWithModifiers.Type) || newTypeWithModifiers.NullableAnnotation.IsOblivious());
+            //Debug.Assert(!IsIndexedTypeParameter(newTypeWithModifiers.Type) || newTypeWithModifiers.NullableAnnotation.IsOblivious());
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/TypeWithAnnotations.cs:476]: >//Debug. [](start = 12, length = 8)

Commented out code

File: src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs [hunk 10]
```diff
@@ -295,7 +297,7 @@ internal static class ConstraintsHelper
                 return null;
             }
 
-            var bounds = new TypeParameterBounds(constraintTypes, interfaces, effectiveBaseClass, deducedBaseType);
+            var bounds = new TypeParameterBounds(constraintTypes, interfaces, effectiveBaseClass, deducedBaseType, ignoresNullableContext);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/ConstraintsHelper.cs:300]: >ignoresNullableContext [](start = 115, length = 22)

It doesn't look like this value actually affects other content in the TypeParameterBounds instance. Why not always use ```false``` and and getting rid of the parameter.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs [hunk 11]
```diff
@@ -680,7 +684,7 @@ private TypeParameterConstraintClause GetTypeParameterConstraintClause()
             return constraintClauses.IsEmpty ? TypeParameterConstraintClause.Empty : constraintClauses[Ordinal];
         }
 
-        protected override TypeParameterBounds ResolveBounds(ConsList<TypeParameterSymbol> inProgress, DiagnosticBag diagnostics)
+        protected override TypeParameterBounds ResolveBounds(ConsList<TypeParameterSymbol> inProgress, bool canIgnoreNullableContext, DiagnosticBag diagnostics)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs:687]: >canIgnoreNullableContext [](start = 108, length = 24)

It looks like the parameter is no longer used. Is this intentional?

File: src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs (hunk 6 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Symbols/NamedTypeSymbol.cs:66]: It would be good to avoid repeating `type.Default.OriginalDefinition.AddUseSiteDiagnostics()`. Moved the helper method here.

---
In reply to: [493955260](https://github.com/dotnet/roslyn/pull/47968#discussion_r493955260) [](ancestors = 493955260)

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs (hunk 4 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs:260]: Good catch, thanks.

---
In reply to: [493779200](https://github.com/dotnet/roslyn/pull/47968#discussion_r493779200) [](ancestors = 493779200)

File: src/Compilers/CSharp/Portable/Symbols/TypeParameterBounds.cs [hunk 12]
```diff
@@ -75,14 +79,42 @@ private TypeParameterBounds()
...
+            if (boundsOpt == null)
+            {
+                return true;
+            }
+            return canIgnoreNullableContext || !boundsOpt.IgnoresNullableContext;
+        }
+
+        // Returns true if bounds was updated with value.
+        // Returns false if bounds already had a value with expected 'IgnoresNullableContext'
+        // or was updated to a value with the expected 'IgnoresNullableContext' value on another thread.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/TypeParameterBounds.cs:102]: >another [](start = 89, length = 7)

"this"?

**Review by AlekseyTs — APPROVED** [review]
LGTM (iteration 11), assuming CI is passing.

File: src/Compilers/CSharp/Portable/Symbols/TypeParameterBounds.cs [hunk 13]
```diff
@@ -75,14 +79,42 @@ private TypeParameterBounds()
...
+            }
+            if (boundsOpt == null)
+            {
+                return true;
+            }
+            return canIgnoreNullableContext || !boundsOpt.IgnoresNullableContext;
+        }
+
+        // Returns true if bounds was updated with value.
+        // Returns false if bounds already had a value with expected 'IgnoresNullableContext'
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Symbols/TypeParameterBounds.cs:101]: nit: consider wording this as "a value with *sufficient* IgnoresNullableContext". Similar on the next line.

Something to indicate that when the caller requests a bounds that ignores nullable context, the symbol may provide a bounds that doesn't ignore nullable context.

File: src/Compilers/CSharp/Portable/Symbols/Source/TypeParameterConstraintClause.cs [hunk 14]
```diff
@@ -212,9 +218,43 @@ static void adjustConstraintTypes(Symbol container, ImmutableArray<TypeWithAnnot
...
+            return constraintClauses.Any(clause => clause.IgnoresNullableContext);
+        }
+
         internal static bool ContainsOnlyEmptyConstraintClauses(this ImmutableArray<TypeParameterConstraintClause> constraintClauses)
         {
             return constraintClauses.All(clause => clause.IsEmpty);
         }
+
+        // Returns true if constraintClauses was updated with value.
+        // Returns false if constraintClauses already had a value with expected 'IgnoresNullableContext'
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Symbols/Source/TypeParameterConstraintClause.cs:241]: Same comment here as in `TypeParameterBounds.cs`.

**Review by RikkiGibson — APPROVED** [review]
LGTM, just had some comment nits to pick. No need to address in this PR if it is not practical

File: src/Compilers/CSharp/Portable/Symbols/TypeParameterBounds.cs (hunk 13 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Symbols/TypeParameterBounds.cs:101]: Thanks. I'll update the comment in a subsequent PR.
