### PR TITLE
VB - fix broken code generated when converting to auto property

### LINKED ISSUE #28989: "Use auto property" generates invalid code for Visual Basic
**Version Used**: 
Version 15.9.0 Preview 1.0 [27920.3000.d15.9stg]

**Steps to Reproduce**:

``` VB 
Public Class PropertyPageException
    Inherits ApplicationException

    Private _showHeaderAndFooterInErrorControl As Boolean = True ' Use auto prop

    Public Property ShowHeaderAndFooterInErrorControl() As Boolean
        Get
            Return _showHeaderAndFooterInErrorControl
        End Get
        Set(value As Boolean)
            _showHeaderAndFooterInErrorControl = value
        End Set
    End Property


End Class

```

**Expected Behavior**:
``` VB
Public Class PropertyPageException
    Inherits ApplicationException

    Public Property ShowHeaderAndFooterInErrorControl() As Boolean = True


End Class

```

**Actual Behavior**:
``` VB
Public Class PropertyPageException
    Inherits ApplicationException

    Public Property ShowHeaderAndFooterInErrorControl() As Boolean
= True


End Class

```

Which results in the following syntax error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	BC30035	Syntax error.	ConsoleApp187	C:\Users\davkean\Source\Repos\ConsoleApp187\ConsoleApp187\Module1.vb	5	Active

```

### PR DESCRIPTION
**Pull request by chborl**
Fixes #28989

Customer scenario:
VB only - when a backing field has an initial value, converting it to an auto property will put the initializer on a new line which results in broken code

Fix:
If the statement has trailing end of line trivia, remove it before adding the initializer

### CODE REVIEW

File: src/Features/VisualBasic/Portable/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb [hunk 1]
```diff
@@ -36,7 +36,8 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.UseAutoProperty
 
             Dim initializer = Await GetFieldInitializer(fieldSymbol, cancellationToken).ConfigureAwait(False)
             If initializer.equalsValue IsNot Nothing Then
-                statement = statement.WithInitializer(initializer.equalsValue)
+                'Before adding initializer, need to remove any end of line trivia from the statement
+                statement = If(statement.GetTrailingTrivia.Any(SyntaxKind.EndOfLineTrivia), statement.WithTrailingTrivia(SyntaxFactory.Space).WithInitializer(initializer.equalsValue), statement.WithInitializer(initializer.equalsValue))
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb]: i think it might be better as:  `statement.WithoutTrailingTrivia().WithInitializer(...).WithTrailingTrivia(statement.GetTrailingTrivia())`

File: src/EditorFeatures/VisualBasicTest/UseAutoProperty/UseAutoPropertyTests.vb [hunk 2]
```diff
@@ -173,6 +173,26 @@ End Class",
...
+        Get
+            Return _b
+        End Get
+        Set(value As Boolean)
+            _b = value
+        End Set
+    End Property
+End Class",
+"Public Class C
+    Public Property P() As Boolean = True 'Comments2 'Comments1
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/VisualBasicTest/UseAutoProperty/UseAutoPropertyTests.vb]: cute.

File: src/EditorFeatures/VisualBasicTest/UseAutoProperty/UseAutoPropertyTests.vb [hunk 3]
```diff
@@ -173,6 +173,26 @@ End Class",
...
+End Class")
+        End Function
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/VisualBasicTest/UseAutoProperty/UseAutoPropertyTests.vb]: can we have a test with a multiline field initializer?

File: src/Features/VisualBasic/Portable/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb [hunk 4]
```diff
@@ -7,6 +7,7 @@ Imports Microsoft.CodeAnalysis.Editing
 Imports Microsoft.CodeAnalysis.Formatting.Rules
 Imports Microsoft.CodeAnalysis.UseAutoProperty
 Imports Microsoft.CodeAnalysis.VisualBasic.Syntax
+Imports Microsoft.CodeAnalysis.VisualBasic.Symbols
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb]: this doesn't feel like it shoudl be necessary...

File: src/Features/VisualBasic/Portable/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb [hunk 5]
```diff
@@ -36,7 +37,10 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.UseAutoProperty
 
             Dim initializer = Await GetFieldInitializer(fieldSymbol, cancellationToken).ConfigureAwait(False)
             If initializer.equalsValue IsNot Nothing Then
-                statement = statement.WithInitializer(initializer.equalsValue)
+                statement = statement.WithTrailingTrivia(SyntaxFactory.Space) _
+                    .WithInitializer(initializer.equalsValue) _
+                    .WithTrailingTrivia(statement.GetTrailingTrivia.Where(Function(x) x.Kind <> SyntaxKind.EndOfLineTrivia)) _
+                    .WithAppendedTrailingTrivia(initializer.equalsValue.GetTrailingTrivia())
```
Comment (chborl) [inline src/Features/VisualBasic/Portable/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb]: If I don't add the Space it looks like `Public Property P() As Boolean= True`  Is there any issue with adding the space in this way?  In syntax visualizer it looks like the space should be trailing trivia on the keyword Boolean.

Also, is this an acceptable way to concatenate the comments from both the property and the field?

Comment (CyrusNajmabadi) [reply src/Features/VisualBasic/Portable/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb]: 1. the way you're doing it is acceptable. 
2. another way would be to do this:

`WithInitializer(initializer.equalsValue.WithPrependedLeadingTrivia(SyntaxFactory.ElasticTrivia))`

This will get the formatter to format the space between these two nodes however is best appropriate.

**Comment by chborl** [comment]
Thanks for the help, @CyrusNajmabadi!  @dotnet/roslyn-ide and @dotnet/roslyn-analysis  for review.

File: src/Features/VisualBasic/Portable/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb (hunk 5 above)
Comment (CyrusNajmabadi) [reply src/Features/VisualBasic/Portable/UseAutoProperty/VisualBasicUseAutoPropertyCodeFixProvider.vb]: Indeed :)
