### PR TITLE
Fix make method async/sync and some related code fixes

### LINKED ISSUE #30325: MakeMethodAsync isn't aware of nullability
image

FYI @dpoeschl

### PR DESCRIPTION
**Pull request by jasonmalinowski**
Fixes #30325.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
let me know when you want review.

File: src/Features/Core/Portable/ExtractInterface/AbstractExtractInterfaceService.cs [hunk 1]
```diff
@@ -616,7 +616,7 @@ private bool DoesTypeReferenceTypeParameter(ITypeSymbol type, ITypeParameterSymb
                 return false;
             }
 
-            if (type == typeParameter ||
+            if (type.Equals(typeParameter) ||
```
Comment (jasonmalinowski) [inline src/Features/Core/Portable/ExtractInterface/AbstractExtractInterfaceService.cs]: This one is a bit subtle: it was doing direct object equality, and the type could be a wrapped type parameter with nullable annotations. Our Equals method here (on the wrapper) is now implementing the effective new behavior for symbol equals which is it ignores nullability unless you opt in.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/ExtractInterface/AbstractExtractInterfaceService.cs]: won't this produce a warning/error soon though?  i thought we were obsoleting ISymbol.Equals so that people would call the right version where you pass in the type of equality you want.

Should we not use htat overload and pass in the right enum value here?  at least to be more up front about what we're doing?

Comment (jasonmalinowski) [reply src/Features/Core/Portable/ExtractInterface/AbstractExtractInterfaceService.cs]: Ah yeah, I guess we are, so yes, I'll update this now.

**Comment by jasonmalinowski** [comment]
I'm not sure I'd say "soon" but it's "as soon as possible", which is still potentially a bit of a ways out (a month or two) depending on existing load and other work being done.

**Comment by CyrusNajmabadi** [comment]
> which is still potentially a bit of a ways out (a month or two) depending on existing load and other work being done.

I still consider that 'soon' :)  Basically, "in the forseeable future" as opposed to "so far out, it's likely to not happen" :)
