### PR TITLE
Report missing Exception type when binding throw

### LINKED ISSUE #39960: BindThrownExpression doesn't ensure that System.Exception type exists
The code was added under umbrella of the Switch Expression feature:
```
                // In C# 8 and later we follow the ECMA specification, which neatly handles null and expressions of exception type.
                boundExpr = GenerateConversionForAssignment(Compilation.GetWellKnownType(WellKnownType.System_Exception), boundExpr, diagnostics);
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #39960

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 1]
```diff
@@ -400,7 +400,7 @@ private BoundExpression BindThrownExpression(ExpressionSyntax exprSyntax, Diagno
             else
             {
                 // In C# 8 and later we follow the ECMA specification, which neatly handles null and expressions of exception type.
-                boundExpr = GenerateConversionForAssignment(Compilation.GetWellKnownType(WellKnownType.System_Exception), boundExpr, diagnostics);
+                boundExpr = GenerateConversionForAssignment(GetWellKnownType(WellKnownType.System_Exception, diagnostics, exprSyntax), boundExpr, diagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: >GetWellKnownType(WellKnownType.System_Exception, diagnostics, exprSyntax) [](start = 60, length = 73)

Is this now be a breaking change for ```throw null;``` by comparison to earlier language versions?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 2]
```diff
@@ -6854,5 +6854,40 @@ public R M4()
...
+            ? throw new System.NullReferenceException()
+            : throw null;
+        L();
+        throw null;
+        void L() => throw d;
+    }
+}
+");
+            comp.MakeTypeMissing(WellKnownType.System_Exception);
+            comp.VerifyDiagnostics(
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: >comp.VerifyDiagnostics( [](start = 12, length = 23)

Please test also with 7.0 language version.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1).

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: No, because there is a conversion for assignment from `null` to `System.Exception`.

---
In reply to: [354033064](https://github.com/dotnet/roslyn/pull/40145#discussion_r354033064) [](ancestors = 354033064)

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs (hunk 2 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Sure, but that will be testing none of the code that changed in this PR.

---
In reply to: [354033690](https://github.com/dotnet/roslyn/pull/40145#discussion_r354033690) [](ancestors = 354033690)

**Comment by gafter** [comment]
@AlekseyTs I think I've responded to your comments.  Do you have any others?

@dotnet/roslyn-compiler May I have a second review, please?

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: > No, because there is a conversion for assignment from null to System.Exception.

I think the adjusted test clearly demonstrates that ```throw null;``` is broken in the current language version, works in 7.0.

---
In reply to: [357854151](https://github.com/dotnet/roslyn/pull/40145#discussion_r357854151) [](ancestors = 357854151,354033064)

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 2)

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: You mean when there is no `Exception` type?  Sure, `throw null;` will no longer bind.

**Comment by gafter** [comment]
@AlekseyTs Not sure what you're looking for at this point. Do you want a breaking change doc that we will no longer bind "throw null" when there is no `Exception` type? It is hard for me to imagine how such documentation could be useful to any customer.

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: > You mean when there is no Exception type?  Sure, throw null; will no longer bind.

I think compat council should approve this.

---
In reply to: [357870727](https://github.com/dotnet/roslyn/pull/40145#discussion_r357870727) [](ancestors = 357870727)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: And the breaking change documented

---
In reply to: [357871177](https://github.com/dotnet/roslyn/pull/40145#discussion_r357871177) [](ancestors = 357871177,357870727)

**Comment by gafter** [comment]
Waiting for a Compat Council decision (EOD Wednesday).

**Comment by gafter** [comment]
@AlekseyTs I think I've responded to all of your code review comments.  Do you have any others?

@dotnet/roslyn-compiler May I have a second review please?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 3]
```diff
@@ -6854,5 +6854,52 @@ public R M4()
 ").VerifyDiagnostics(
                 );
         }
+
+        [Fact]
+        [WorkItem(39960, "https://github.com/dotnet/roslyn/issues/39960")]
+        public void MissingExceptionType()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: >MissingExceptionType [](start = 20, length = 20)

Please add a regression test verifying that we are able to compile the code below with System.Exception missing at compile time and execute the code successfully:

```
class C
{
    static void Main()
    {
        try
        {
            Test();
        }
        catch
        {
            System.Console.WriteLine("in catch");
        }
    }

    static void Test()
    {
        throw null;
    }
}
```

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: For 7.0 at least.

---
In reply to: [359067146](https://github.com/dotnet/roslyn/pull/40145#discussion_r359067146) [](ancestors = 359067146)

Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Sure, though that would not exercise any code in this PR.

File: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml [hunk 4]
```diff
@@ -1764,6 +1764,10 @@
   </Node>
 
   <Node Name="BoundStackAllocArrayCreation" Base="BoundExpression">
+    <!-- A BoundStackAllocArrayCreation is given a null type when it is in a
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml]: ><!-- A BoundStackAllocArrayCreation is given a null type when it is in a [](start = 4, length = 72)

I think this change got pushed to a wrong PR

**Comment by gafter** [comment]
@AlekseyTs I've added the requested test for existing compiler code.  Do you have any other requests?
