### PR TITLE
Check EditorBrowsable attribute for unimported ext-methods completion

### LINKED ISSUE #47551: Extension methods with EditorBrowsable(Never) defined in a referenced assembly show up in VS intellisense
**Version Used**: VS 16.7.3

**Steps to Reproduce**:

1. Create a library project with a public extension method. Put `[EditorBrowsable(EditorBrowsableState.Never)]` on it.
2. Build the project.
3. Create a second library project and reference the `bin/Debug` assembly that was created by building the first project.
4. See the never-browsable extension method showing up in intellisense for the second library project where it offers to autocomplete extension methods that are in an unimported namespace.

**Expected Behavior**: The extension methods should stop polluting intellisense. They can't be removed without causing binary-breaking changes and they should remain extension methods so that code that used them gets the obsoletion message rather than a "method does not exist" compiler error.

**Actual Behavior**: The extension methods did not stop polluting intellisense.

### PR DESCRIPTION
**Pull request by genlu**
Fix #47551

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ExtensionMethodImportCompletionProviderTests.cs [hunk 1]
```diff
@@ -1723,6 +1726,165 @@ public void M(int x)
...
+            }
+        }
+
+        [InlineData(ReferenceType.Project, true, true)]
+        [InlineData(ReferenceType.Project, false, true)]
+        [InlineData(ReferenceType.Metadata, true, false)]
+        [InlineData(ReferenceType.Metadata, false, true)]
+        [Theory, Trait(Traits.Feature, Traits.Features.Completion)]
+        [WorkItem(47551, "https://github.com/dotnet/roslyn/issues/47551")]
+        public async Task TestBrowsableAdvanced(ReferenceType refType, bool hideAdvanced, bool shouldContainItem)
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/ExtensionMethodImportCompletionProviderTests.cs:1835]: 💡 I've started making the expected result a switch statement value instead of a parameter. I like how it separates the true inputs to test parameterization from the outputs.

```
var shouldContainItem = (refType, hideAdvanced) switch
{
  (ReferenceType.Project, _) => true,
  (_, false) => true,
  _ => throw ExceptionUtilities.Unreachable,
};
```

**Review by sharwell — APPROVED** [review]
