### PR TITLE
Save CustomAttributesBag before post decoding well known attributes.

### LINKED ISSUE #64392: StackOverflowException in code analyzer for simple class
Create a `.NET 6` console app, and add the following erroneous class:
```c#
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;

namespace SimpleTest;

[Display(x => $"{Name}")]
public class Foo
{
    [Display(Name = "Name")]
    public string Name { get; }
}
```

Wait for the Code Analyzer to analyze the code...

**Visual Studio crashes**
Sometimes the process doesn't get killed, and you get a chance to copy the exception details:
```
StreamJsonRpc.ConnectionLostException : The JSON-RPC connection with the remote party was lost before the request could complete.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.TryInvokeAsync[TService,TResult](<Unknown Parameters>)
```

Then, in Event Viewer, I can find some more details:
```
Faulting application name: devenv.exe, version: 17.3.32901.215, time stamp: 0x63112d8a
Faulting module name: Microsoft.CodeAnalysis.CSharp.ni.dll, version: 4.300.22.42310, time stamp: 0x84a74681
Exception code: 0xc00000fd
Fault offset: 0x0000000000ea35d9
Faulting application start time: 0x01d8d4d3ac9b88d7
Faulting application path: C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.exe
Faulting module path: C:\Windows\assembly\NativeImages_v4.0.30319_64\Microsoft.C1d3c2215#\47032c6832869df03ca7a311375febdc\Microsoft.CodeAnalysis.CSharp.ni.dll
```

**Version Used**: 
Microsoft Visual Studio Professional 2022
Version 17.3.4
VisualStudio.17.Release/17.3.4+32901.215
Microsoft .NET Framework
Version 4.8.04084
C# Tools   4.3.0-3.22423.10+b35bb0baca1071d50cc4f8cf5a1a89e7cc112461

### PR DESCRIPTION
**Pull request by AlekseyTs**
This avoids infinite cycle in binding attributes for two or more different symbols.
Fixes #64392.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

File: src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs [hunk 1]
```diff
@@ -389,17 +389,17 @@ internal virtual void PostDecodeWellKnownAttributes(ImmutableArray<CSharpAttribu
...
-            removeObsoleteDiagnosticsForForwardedTypes(boundAttributes, attributesToBind, ref diagnostics);
-            Debug.Assert(diagnostics.DiagnosticBag is not null);
-
             // Store attributes into the bag.
             bool lazyAttributesStoredOnThisThread = false;
             if (lazyCustomAttributesBag.SetAttributes(boundAttributes))
             {
                 if (attributeMatchesOpt is null)
                 {
+                    this.PostDecodeWellKnownAttributes(boundAttributes, attributesToBind, diagnostics, symbolPart, wellKnownAttributeData);
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs:398]: Why is it ok to move this from being unconditionally executed to only being executed if there's no matching filter?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs:398]: > Why is it ok to move this from being unconditionally executed to only being executed if there's no matching filter?

The only allowed side effect of this call is error reporting into ```diagnostics``` (from doc comment: "This method should not have any side effects on the symbol, i.e. it SHOULD NOT change the symbol state."), and this code path is the only code path that preserves the ```diagnostics```.

Comment (333fred) [reply src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs:398]: Thanks for the explanation.

**Review by 333fred — APPROVED** [review]
LGTM (commit 1)
