### PR TITLE
Test/fix scoping rules for pattern locals declared within a switch statement.

### LINKED ISSUE #8815: Scope of a pattern variable in the when clause of a case
The scope of a pattern variable declared in the when clause of a case should extend to the whole switch section. That should be (implemented if necessary and) tested:

```cs
case 3 when (someObject is int i && i == 3):
    Console.WriteLine(i); // scope of i extends to the case block.
    break;
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Also fix a bug in lowering of a switch statement where the target expression was not lowered.

Fixes #8815.
Related to #8817.

@gafter, @jaredpar, @dotnet/roslyn-compiler Please review.
CC @MattGertz For "Ask Mode".

### CODE REVIEW

**Comment by MattGertz** [comment]
Approved pending code reviews.

File: src/Compilers/CSharp/Portable/Syntax/LookupPosition.cs [hunk 1]
```diff
@@ -320,7 +320,7 @@ private static SyntaxToken GetFirstIncludedToken(StatementSyntax statement, bool
                 case SyntaxKind.ReturnStatement:
                     return ((ReturnStatementSyntax)statement).ReturnKeyword;
                 case SyntaxKind.SwitchStatement:
-                    return ((SwitchStatementSyntax)statement).OpenBraceToken;
+                    return ((SwitchStatementSyntax)statement).Expression.GetFirstToken();
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Syntax/LookupPosition.cs]: Are you causing the local declarations within the switch blocks to be in scope within the switch expression? I don't think that is the way it is supposed to be.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 2]
```diff
@@ -4811,5 +4835,1166 @@ class C
...
+    //         switch (y10 + 10 is var x10 ? x10 : 0)
+    Diagnostic(ErrorCode.ERR_NameNotInContext, "y10").WithArguments("y10").WithLocation(85, 17),
+    // (87,25): error CS0841: Cannot use local variable 'y10' before it is declared
+    //             case 0 when y10:
+    Diagnostic(ErrorCode.ERR_VariableUsedBeforeDeclaration, "y10").WithArguments("y10").WithLocation(87, 25),
+    // (89,18): error CS0841: Cannot use local variable 'y10' before it is declared
+    //             case y10:
+    Diagnostic(ErrorCode.ERR_VariableUsedBeforeDeclaration, "y10").WithArguments("y10").WithLocation(89, 18),
+    // (98,17): error CS0103: The name 'y11' does not exist in the current context
+    //         switch (y11 + 11 is var x11 ? x11 : 0)
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Yes, good.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 3]
```diff
@@ -4811,5 +4835,1166 @@ class C
...
+            Assert.Equal(4, y10Ref.Length);
+            VerifyNotInScope(model, y10Ref[0]);
+            VerifyNotAPatternLocal(model, y10Ref[1]);
+            VerifyNotAPatternLocal(model, y10Ref[2]);
+            VerifyNotAPatternLocal(model, y10Ref[3]);
+
+            var y11Decl = tree.GetRoot().DescendantNodes().OfType<LetStatementSyntax>().Where(p => p.Identifier.ValueText == "y11").Single();
+            var y11Ref = tree.GetRoot().DescendantNodes().OfType<IdentifierNameSyntax>().Where(id => id.Identifier.ValueText == "y11").ToArray();
+            Assert.Equal(4, y11Ref.Length);
+            VerifyNotInScope(model, y11Ref[0]);
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Yes, good.

**Comment by gafter** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Syntax/LookupPosition.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Syntax/LookupPosition.cs]: Note, this change doesn't affect the binding, it only affects the process of looking up an enclosing binder within SemanticModel.
Before this change, only things inside ```{}``` were considered by SemanticModel to be in scope owned by a switch statement. After this change, the switch expression is also considered to be in scope owned by the switch. There are two scopes owned by a switch, the first spans expression and all switch sections, the second spans just switch sections and is nested into the first. Binder.GetBinder API returns binder representing the second scope, it never returns binder for the first scope. The change in MemberSemanticModel.AdjustBinderForPositionWithinStatement takes care of that. 
There was a bug in the binding as well, where a binder for the second scope was used to bind a switch expression, making locals declared in switch sections visible there. That was addressed by the change in Binder.BindPatternSwitch.

Comment (gafter) [inline src/Compilers/CSharp/Portable/Syntax/LookupPosition.cs]: Awesome.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off for this future-stabilization change.

File: src/Compilers/CSharp/Portable/Binder/PatternVariableFinder.cs [hunk 4]
```diff
@@ -13,51 +13,42 @@ namespace Microsoft.CodeAnalysis.CSharp
     class PatternVariableFinder : CSharpSyntaxWalker
     {
         ArrayBuilder<DeclarationPatternSyntax> declarationPatterns;
-        ArrayBuilder<ExpressionSyntax> expressionsToVisit = ArrayBuilder<ExpressionSyntax>.GetInstance();
+        ArrayBuilder<CSharpSyntaxNode> nodesToVisit = ArrayBuilder<CSharpSyntaxNode>.GetInstance();
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Binder/PatternVariableFinder.cs]: These are instance variables, right? They don't seem to match our style conventions.

File: src/Compilers/CSharp/Portable/Binder/PatternVariableFinder.cs [hunk 5]
```diff
@@ -13,51 +13,42 @@ namespace Microsoft.CodeAnalysis.CSharp
     class PatternVariableFinder : CSharpSyntaxWalker
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/PatternVariableFinder.cs]: Explicit visibility

File: src/Compilers/CSharp/Portable/Binder/PatternVariableFinder.cs [hunk 6]
```diff
@@ -13,51 +13,42 @@ namespace Microsoft.CodeAnalysis.CSharp
...
-                foreach (var subExpression in expressions)
+                foreach (var subExpression in nodes)
                 {
-                    if (subExpression != null) expressionsToVisit.Add(subExpression);
+                    if (subExpression != null) nodesToVisit.Add(subExpression);
                 }
             }
 
-            expressionsToVisit.ReverseContents();
+            nodesToVisit.ReverseContents();
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Binder/PatternVariableFinder.cs]: Is it worth it to use a `Queue` instead of an `ArrayBuilder` here so we don't have to reverse (another potentially large allocation)?

File: src/Compilers/CSharp/Portable/Binder/PatternVariableFinder.cs (hunk 5 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/PatternVariableFinder.cs]: This is a preexisting condition. I will open an issue for this.

File: src/Compilers/CSharp/Portable/Binder/PatternVariableFinder.cs (hunk 4 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/PatternVariableFinder.cs]: This is a preexisting condition common to pattern matching implementation (CC @gafter ). I will open an issue to track this. For stabilization, I'd rather keep the churn to a minimum and follow the style used in this class.

Comment (agocke) [inline src/Compilers/CSharp/Portable/Binder/PatternVariableFinder.cs]: :+1:

File: src/Compilers/CSharp/Portable/Binder/PatternVariableFinder.cs (hunk 6 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/PatternVariableFinder.cs]: Good observation. This code, however, is essentially obsolete, there is a pending PR (https://github.com/dotnet/roslyn/pull/9396) that eliminates this ArrayBuilder. The code is doing what it is supposed to do and perf is not a priority for it for the preview.

Comment (agocke) [inline src/Compilers/CSharp/Portable/Binder/PatternVariableFinder.cs]: :+1:

**Comment by agocke** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Binder/PatternVariableFinder.cs (hunk 4 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/PatternVariableFinder.cs]: This code is gone in later versions.
