### PR TITLE
Ensure SqlConnection gets disposed on exceptional paths

### LINKED ISSUE #42365: Roslyn OOP repeatedly crashing
I don't have a specific repro, but it often seems to be Find References doing this:

```
Application: ServiceHub.RoslynCodeAnalysisService32.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.InvalidOperationException: SqlConnection was not properly closed
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.WatsonReporter.ReportFatal(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.SQLite.Interop.SqlConnection.Finalize()
```

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #42365

### CODE REVIEW

File: src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs [hunk 1]
```diff
@@ -174,7 +174,18 @@ private void ReleaseConnection(SqlConnection connection)
...
+                {
+                    _connectionsPool.Push(connection);
+                }
+                catch
+                {
+                    // An exception (likely OutOfMemoryException) occurred while returning the connection to the pool.
+                    // The connection will be discarded, so make sure to close it so the finalizer doesn't crash the
+                    // process later.
+                    connection.Close_OnlyForUseBySqlPersistentStorage();
+                    throw;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs]: yikes.  what a crazy case.

File: src/Workspaces/Core/Portable/Storage/SQLite/Interop/SqlConnection.cs [hunk 2]
```diff
@@ -69,13 +69,17 @@ public static SqlConnection Create(IPersistentStorageFaultInjector faultInjector
 
             raw.sqlite3_busy_timeout(handle, (int)TimeSpan.FromMinutes(1).TotalMilliseconds);
 
-            return new SqlConnection(faultInjector, handle);
+            var queryToStatement = new Dictionary<string, SqlStatement>();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Storage/SQLite/Interop/SqlConnection.cs]: i wouldn't mind a comment here as well.

File: src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs [hunk 3]
```diff
@@ -174,7 +174,18 @@ private void ReleaseConnection(SqlConnection connection)
...
                 }
 
-                _connectionsPool.Push(connection);
+                try
+                {
+                    _connectionsPool.Push(connection);
+                }
+                catch
+                {
+                    // An exception (likely OutOfMemoryException) occurred while returning the connection to the pool.
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs]: Why isn't the process crashing from an OutOfMemory in the first place? Surely we don't want to try hardening the *entire* process against this, since this just might move the crash somewhere else?

**Comment by jasonmalinowski** [comment]
This feels odd to me: why isn't the process crashing once it ran out of memory? Why was it running out of memory just minutes after opening the solution in the first place?

**Comment by CyrusNajmabadi** [comment]
Started an offline discussion with you two.  There is definitely badness going on.  I approve of Sam's fix in the sense that it properly designs this component to deal with that badness better.  but we still need to root cause why OOP is having issues.

File: src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs (hunk 1 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs]: Finalizers.

File: src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs (hunk 3 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs]: It's a problem because finalizers. Finalizers almost always cause problems, but rarely provide answers.

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs]: > but rarely provide answers.

These finalizers caught *several* issues.  They are really useful for preventing the easy mistake of forgetting to close the connection. 

That said, we could change the finalizer here to report an issue without tearing down the process.

Comment (jasonmalinowski) [reply src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs]: I guess I would have assumed the OOP would have been torn down the moment the OutOfMemoryException happened and the finalizers never would have ran; the finalizer assertion could have been kept as is. Even if we don't trigger a finalizer, the rest of the system is not safe; the Workspace has no guarantee it's handing out functional Compilations, for example...

File: src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs [hunk 4]
```diff
@@ -174,7 +174,18 @@ private void ReleaseConnection(SqlConnection connection)
                     return;
                 }
 
-                _connectionsPool.Push(connection);
+                try
+                {
+                    _connectionsPool.Push(connection);
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs]: Is it guaranteed that Push() throwing an OutOfMemoryException leaves the _connectionsPool in a functional state?

File: src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs [hunk 5]
```diff
@@ -174,7 +174,18 @@ private void ReleaseConnection(SqlConnection connection)
...
+                }
+                catch
+                {
+                    // An exception (likely OutOfMemoryException) occurred while returning the connection to the pool.
+                    // The connection will be discarded, so make sure to close it so the finalizer doesn't crash the
+                    // process later.
+                    connection.Close_OnlyForUseBySqlPersistentStorage();
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs]: It looks like this method allocates; is that worrisome?

File: src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs (hunk 3 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs]: > I guess I would have assumed the OOP would have been torn down the moment the OutOfMemoryException happened

I don't think that actually happens.  I think OOM is a normal exception that can be recovered from.

File: src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs (hunk 5 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs]: Are you sure?  why do you think that?

File: src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs (hunk 3 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs]: We frequently hit OOM cases in practice.

**Comment by CyrusNajmabadi** [comment]
@sharwell Another possible approach here would be to have the Connection consturctor do its work and then set a bool at the end saying "i constructed successfully".  We could then only hve the assert in that case.

Alternatively, we could remove the finalizer.  it was valuable during active development, but now seems like we could just remove it and trust PRs and comments to help ensure people don't forget to dispose these guys.

File: src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs (hunk 5 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs]: No, because the allocation happens _after_ the call to `GC.SuppressFinalize`.

File: src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs (hunk 4 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs]: The only thing we're relying on here is that `_connectionsPool` doesn't contain `connection` if an `OutOfMemoryException` is thrown.

File: src/Workspaces/Core/Portable/Storage/SQLite/Interop/SqlConnection.cs (hunk 2 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Storage/SQLite/Interop/SqlConnection.cs]: I already have a comment in one location, and it would be impossible to change this location without seeing the other location. I prefer to not duplicate.

File: src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs (hunk 4 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs]: This seems like a safe change since the exception is getting rethrown.

File: src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs (hunk 5 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs]: @CyrusNajmabadi I see a foreach being used, so it'll allocate the enumerator (likely).

My concern here was we'll still be leaking the connection if that allocation were to throw. It feels like we really should be using a SafeHandle here or something to ensure that cleanup happens regardless?

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Storage/SQLite/SQLitePersistentStorage.cs]: > @CyrusNajmabadi I see a foreach being used, so it'll allocate the enumerator (likely).

The GC.suppressfinalize happens first.  So we don't run the finalizer.

> My concern here was we'll still be leaking the connection if that allocation were to throw. It feels like we really should be using a SafeHandle here or something to ensure that cleanup happens regardless?

Sure.  That seems reasonable to me.  I don't have experience with these.  Do you have an example i can look at for using that?
