### PR TITLE
Don't report diagnostic on typeof(void).Name in C#

### LINKED ISSUE #54233: typeof().Name to nameof analyzer should ignore void type
**Version Used**:  3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

**Steps to Reproduce**:

```cs
var voidTypeName = typeof(void).Name;
```

**Expected Behavior**:
no errors from analyzers

**Actual Behavior**:
`IDE0082: typeof can be converted to nameof`
resulting in
```cs
// CS0673: System.Void cannot be used from C# -- use typeof(void) to get the void type object
var voidTypeName = nameof(void);
```

Related to #45806, #18284

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #54233

### CODE REVIEW

File: src/Analyzers/CSharp/CodeFixes/ConvertTypeOfToNameOf/CSharpConvertTypeOfToNameOfCodeFixProvider.cs [hunk 1]
```diff
@@ -30,7 +30,7 @@ protected override string GetCodeFixTitle()
             if (node is MemberAccessExpressionSyntax { Expression: TypeOfExpressionSyntax typeOfExpression })
             {
                 var typeSymbol = model.GetSymbolInfo(typeOfExpression.Type, cancellationToken).Symbol.GetSymbolType();
-                return typeSymbol?.GenerateTypeSyntax();
+                return typeSymbol?.GenerateExpressionSyntax();
```
Comment (Youssef1313) [inline src/Analyzers/CSharp/CodeFixes/ConvertTypeOfToNameOf/CSharpConvertTypeOfToNameOfCodeFixProvider.cs:33]: nameof argument is an expression. To the end-user this doesn't change anything. This only uses the correct type of syntax nodes for the tests to pass (text representation is still the same in both cases.)

File: src/Analyzers/CSharp/Analyzers/ConvertTypeofToNameof/CSharpConvertTypeOfToNameOfDiagnosticAnalyzer.cs [hunk 2]
```diff
@@ -33,7 +34,9 @@ protected override bool IsValidTypeofAction(OperationAnalysisContext context)
             // Make sure that the syntax that we're looking at is actually a typeof expression and that
             // the parent syntax is a member access expression otherwise the syntax is not the kind of
             // expression that we want to analyze
-            return node is TypeOfExpressionSyntax { Parent: MemberAccessExpressionSyntax _ };
+            return node is TypeOfExpressionSyntax { Parent: MemberAccessExpressionSyntax } &&
+                // nameof(System.Void) isn't allowed in C#.
+                ((ITypeOfOperation)context.Operation).TypeOperand.SpecialType != SpecialType.System_Void;
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/ConvertTypeofToNameof/CSharpConvertTypeOfToNameOfDiagnosticAnalyzer.cs:39]: also, if we ahve `typeof(Dictionary<,>.KeyValuePair)` we shouldn't do `nameof` here either most likely.

Comment (CyrusNajmabadi) [reply src/Analyzers/CSharp/Analyzers/ConvertTypeofToNameof/CSharpConvertTypeOfToNameOfDiagnosticAnalyzer.cs:39]: i think this can be simpler.  System.Void literally cannot be referenced no matter what.  so the ony way to get this is `typeof(void)`.  so we can just do `not is TypeOfExpressionSyntax { type: not PredefinedTypeSyntax { Keyword ...`

but it's up to you.

**Review by CyrusNajmabadi — APPROVED** [review]
lgtm.  up to you if you want to make changes here.  let me know if you do, or if you want me to merge.

File: src/Analyzers/CSharp/Analyzers/ConvertTypeofToNameof/CSharpConvertTypeOfToNameOfDiagnosticAnalyzer.cs (hunk 2 above)
Comment (Youssef1313) [reply src/Analyzers/CSharp/Analyzers/ConvertTypeofToNameof/CSharpConvertTypeOfToNameOfDiagnosticAnalyzer.cs]: > also, if we ahve typeof(Dictionary<,>.KeyValuePair) we shouldn't do nameof here either most likely.

Generics are already handled here, there are existing tests for it too:

https://github.com/dotnet/roslyn/blob/d4e8ed5bc68dd4d3bb374ee73fdaf5d80ab6e2e3/src/Analyzers/Core/Analyzers/ConvertTypeofToNameof/AbstractConvertTypeOfToNameOfDiagnosticAnalyzer.cs#L87

---

> i think this can be simpler. System.Void literally cannot be referenced no matter what. so the ony way to get this is typeof(void). so we can just do not is TypeOfExpressionSyntax { type: not PredefinedTypeSyntax { Keyword ...

I'm not a big fan of using syntax when a semantic check can be done, but I went for it anyway.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Awesome.  Thanks!
