### PR TITLE
Remove code for tweaking "$" on object IDs

### LINKED ISSUE #3094: Object IDs should preserve the leading '$' in the Locals window.
After creating object IDs for some local variables (parameters to the current method), they appeared in the Locals window as `1` and `2` but should have appeared as `$1` and `$2` just like `$exception`.  See screenshot:
objectid

### PR DESCRIPTION
**Pull request by amcasey**
The debugger will now produce and consume them with the "$" prepended, so
we no longer have to add and remove it explicitly.

Fixes #3094.

Without this fix, ```$1``` will show up as ```1``` in the Locals window (and Add Watch will produce ```1```).

### CODE REVIEW

**Comment by amcasey** [comment]
Relevant leads: @ManishJayaswal 
Potential code reviewers: @KevinH-MS @pnelsonmsft @cston

File: src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/ExpressionCompilerTestBase.cs [hunk 1]
```diff
@@ -293,8 +293,7 @@ internal static Alias ObjectIdAlias(uint id, string typeAssemblyQualifiedName)
         {
             Assert.NotEqual(0u, id); // Not a valid id.
             var name = $"${id}";
-            var fullName = id.ToString();
-            return new Alias(DkmClrAliasKind.ObjectId, name, fullName, typeAssemblyQualifiedName, default(CustomTypeInfo));
+            return new Alias(DkmClrAliasKind.ObjectId, name, name, typeAssemblyQualifiedName, default(CustomTypeInfo));
```
Comment (KevinH-MS) [inline src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/ExpressionCompilerTestBase.cs]: Since we're assuming that ```name == fullName``` for the purposes of testing, it might be good to add a ```Debug.Assert(name == fullName)``` to ```ExpressionCompiler.GetAliases``` in the ObjectId case.

**Comment by KevinH-MS** [comment]
LGTM :shipit:

**Comment by KevinH-MS** [comment]
:+1:

File: src/ExpressionEvaluator/Core/Source/ResultProvider/Helpers/ValueHelpers.cs [hunk 2]
```diff
@@ -16,7 +16,7 @@ internal static string IncludeObjectId(this DkmClrValue value, string valueStr)
                 string alias = value.Alias;
                 if (!string.IsNullOrEmpty(alias))
                 {
-                    return string.Format("{0} {{${1}}}", valueStr, alias);
+                    return $"{valueStr} {{{alias}}}";
```
Comment (KevinH-MS) [inline src/ExpressionEvaluator/Core/Source/ResultProvider/Helpers/ValueHelpers.cs]: Consider asserting that alias begins with '$'.

**Comment by amcasey** [comment]
This won't be ready for merging (or buddy testing) until some additional internal code flow has happened.

**Comment by cston** [comment]
LGTM

**Comment by dpoeschl** [comment]
retest this please

**Comment by amcasey** [comment]
retest this please

**Comment by MattGertz** [comment]
Approved 6/2 by ML Shiproom.

**Comment by amcasey** [comment]
I moved to the new base drop early and validated that the Roslyn and Debugger changes work together.
