### PR TITLE
Fix interpolated string refactoring to work for Console.Write*

### LINKED ISSUE #55053: String interpolation refactoring doesn't work on Console.WriteLine
image

SDK: 6.0.100-preview.6.21355.2
VS: 17.0p2

### PR DESCRIPTION
**Pull request by ryzngard**
Fixes #55053

### CODE REVIEW

File: src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs [hunk 1]
```diff
@@ -57,28 +61,83 @@ public override async Task ComputeRefactoringsAsync(CodeRefactoringContext conte
                 return;
             }
 
-            var (invocation, invocationSymbol) = await TryFindInvocationAsync(textSpan, document, semanticModel, formatMethods, syntaxFactsService, context.CancellationToken).ConfigureAwait(false);
-            if (invocation != null && invocationSymbol != null &&
-                IsArgumentListCorrect(syntaxFactsService.GetArgumentsOfInvocationExpression(invocation), invocationSymbol, formatMethods, semanticModel, syntaxFactsService, cancellationToken))
+            var addedRefactorings = await TryAddRefactoringsAsync(
```
Comment (davidwengier) [inline src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs:64]: I don't know how slow this is, to know if its a problem to call it twice, but an alternate suggestion:

```cs
var allMethods = replaceInvocationMethods.AddRange(keepInvocationMethds);
var (invocation, invocationSymbol) = await TryFindInvocationAsync(..., allMethods ...);
var shouldReplaceInvocation = (keepInvocationMethods.Contains(invocation);
...
```

If that makes any sense? I thought of it while watching the stream but couldn't type it out in twitch chat.

**Review by davidwengier — APPROVED** [review]

File: src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs [hunk 2]
```diff
@@ -35,18 +35,22 @@ public override async Task ComputeRefactoringsAsync(CodeRefactoringContext conte
...
             {
                 return;
             }
 
-            var formatMethods = stringType
-                .GetMembers(nameof(string.Format))
-                .OfType<IMethodSymbol>()
-                .Where(ShouldIncludeFormatMethod)
-                .ToImmutableArray();
+            var consoleType = semanticModel.Compilation.GetTypeByMetadataName(typeof(Console).FullName);
```
Comment (jmarolf) [inline src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs:44]: Should we eventually support all methods mentioned in [composite-formatting](https://docs.microsoft.com/dotnet/standard/base-types/formatting-types#composite-formatting)?

File: src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs (hunk 1 above)
Comment (ryzngard) [reply src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs:64]: hmm, that's a good question. It's really a problem of what is slower. Let me look further into this. Agree that the implementation is sus right now

File: src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs (hunk 2 above)
Comment (ryzngard) [reply src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs:44]: maybe. The intention of this PR was to open that possibility up easily without adding them, since the original issue and design only mentioned console.

**Review by jmarolf — APPROVED** [review]

File: src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs [hunk 3]
```diff
@@ -35,18 +35,22 @@ public override async Task ComputeRefactoringsAsync(CodeRefactoringContext conte
...
+
+            var stringMethods = CollectMethods(stringType, nameof(string.Format));
+            var consoleMethods = CollectMethods(consoleType, nameof(Console.Write), nameof(Console.WriteLine));
+
+
```
Comment (JoeRobich) [inline src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs:49]:
```suggestion
```

File: src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs [hunk 4]
```diff
@@ -35,18 +35,22 @@ public override async Task ComputeRefactoringsAsync(CodeRefactoringContext conte
             var semanticModel = await document.GetRequiredSemanticModelAsync(cancellationToken).ConfigureAwait(false);
 
             var stringType = semanticModel.Compilation.GetSpecialType(SpecialType.System_String);
-            if (stringType == null)
+
+            if (stringType is null)
```
Comment (Youssef1313) [inline src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs:39]: This if condition is unreachable. Only `GetTypeByMetadataName` can return null. For special type if it doesn't exist, the compiler returns an error symbol.

File: src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs (hunk 2 above)
Comment (ryzngard) [reply src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs:44]: yea, I'm really thinking there should be some sort of abstraction here for all of that...

File: src/EditorFeatures/CSharpTest/ConvertToInterpolatedString/ConvertPlaceholderToInterpolatedStringTests.cs [hunk 5]
```diff
@@ -43,6 +43,338 @@ void M()
...
+        {
+            await TestInRegularAndScriptAsync(
+@"using System;
+
+class T
+{
+    void M()
+    {
+        var i = 25;
+        Console.WriteLine(""[||]{0}"", i);
```
[the remark this answers is not in the document]
Comment (ryzngard) [reply src/EditorFeatures/CSharpTest/ConvertToInterpolatedString/ConvertPlaceholderToInterpolatedStringTests.cs:112]: oh, thank you. I actually think these would be better as theory with some params but this is a good catch!

File: src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs [hunk 6]
```diff
@@ -57,28 +71,54 @@ public override async Task ComputeRefactoringsAsync(CodeRefactoringContext conte
                 return;
             }
 
-            var (invocation, invocationSymbol) = await TryFindInvocationAsync(textSpan, document, semanticModel, formatMethods, syntaxFactsService, context.CancellationToken).ConfigureAwait(false);
-            if (invocation != null && invocationSymbol != null &&
-                IsArgumentListCorrect(syntaxFactsService.GetArgumentsOfInvocationExpression(invocation), invocationSymbol, formatMethods, semanticModel, syntaxFactsService, cancellationToken))
+
```
Comment (JoeRobich) [inline src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs:74]:
```suggestion
```

File: src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs (hunk 2 above)
Comment (ryzngard) [reply src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs]: Updated included ones in this PR

File: src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs [hunk 7]
```diff
@@ -27,6 +28,17 @@ internal abstract class AbstractConvertPlaceholderToInterpolatedStringRefactorin
         where TLiteralExpressionSyntax : SyntaxNode
         where TArgumentListExpressionSyntax : SyntaxNode
     {
+
+        // Methods that are not string.Format but still should qualify to be replaced.
+        // Ex: Console.WriteLine("{0}", a) => Console.WriteLine($"{a}");
+        private static readonly (string? typeName, string[] methods)[] TypeMethodPairs = new (string?, string[])[]
```
Comment (davidwengier) [inline src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs:34]: I think it would be much more meaningful if this was called `CompositFormattingMethods` or something. `TypeMethodPairs` is very generic, and if the docs use "composite formatting" for this pattern, it would make sense to mirror that in code.

File: src/EditorFeatures/CSharpTest/ConvertToInterpolatedString/ConvertPlaceholderToInterpolatedStringTests.cs [hunk 8]
```diff
@@ -19,27 +21,131 @@ public class ConvertPlaceholderToInterpolatedStringTests : AbstractCSharpCodeAct
...
+                }
+
+                // Makes a string of form "{0} {1}..."
+                static string MakeInterpolatedString(int numberOfParameters)
+                {
+                    var interpolatedString = "\"";
+
+                    for (var i = 0; i < numberOfParameters; i++)
+                    {
+                        interpolatedString += $"{{{i}}}";
```
Comment (davidwengier) [inline src/EditorFeatures/CSharpTest/ConvertToInterpolatedString/ConvertPlaceholderToInterpolatedStringTests.cs:70]: I cannot enumerate the ways in which I don't like this, but I'm going to grit my teeth and ignore it :D

**Review by davidwengier — APPROVED** [review]

File: src/EditorFeatures/CSharpTest/ConvertToInterpolatedString/ConvertPlaceholderToInterpolatedStringTests.cs (hunk 8 above)
Comment (ryzngard) [reply src/EditorFeatures/CSharpTest/ConvertToInterpolatedString/ConvertPlaceholderToInterpolatedStringTests.cs:70]: I'm not in love with this whole thing, but it seemed the best way to write it... What would you suggest? I''m happy to at least take it and ignore it :P

Comment (davidwengier) [reply src/EditorFeatures/CSharpTest/ConvertToInterpolatedString/ConvertPlaceholderToInterpolatedStringTests.cs:70]: oh yeah, the whole thing is annoying because its test code that is bordering on being more complex than the real code. I was just having a whinge about the interpolation here, so big deal.

File: src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs (hunk 4 above)
Comment (ryzngard) [reply src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertPlaceholderToInterpolatedStringRefactoringProvider.cs:51]: I see. Looks like the initial code was wrong then. Fixing

File: src/EditorFeatures/CSharpTest/ConvertToInterpolatedString/ConvertPlaceholderToInterpolatedStringTests.cs [hunk 9]
```diff
@@ -43,6 +43,338 @@ void M()
...
+
+class T
+{
+    void M()
+    {
+        var i = 25;
+        [|Console.WriteLine(GetString(), i)|];
+    }
+
+    void GetString() => """";
```
[the remark this answers is not in the document]
Comment (JoeRobich) [reply src/EditorFeatures/CSharpTest/ConvertToInterpolatedString/ConvertPlaceholderToInterpolatedStringTests.cs:127]: @ryzngard Should this be updated?

**Review by JoeRobich — APPROVED** [review]
