### PR TITLE
Fix EditorFeatures2 flakiness

### LINKED ISSUE #42586: EditorFeatures2 is crashing and causing build flakiness
Failing builds: 
- https://dev.azure.com/dnceng/public/_build/results?buildId=565072&view=results
- https://dev.azure.com/dnceng/public/_build/results?buildId=560944&view=results
- https://dev.azure.com/dnceng/public/_build/results?buildId=559951&view=results
- https://dev.azure.com/dnceng/public/_build/results?buildId=559931&view=results
- https://dev.azure.com/dnceng/public/_build/results?buildId=559325&view=results
- https://dev.azure.com/dnceng/public/_build/results?buildId=559117&view=results
- https://dev.azure.com/dnceng/public/_build/results?buildId=558757&view=results
- https://dev.azure.com/dnceng/public/_build/results?buildId=558245&view=results

The xunit run is crashing and not triggering a procdump for unknown reasons. Running locally should hopefully reproduce the failure. 

Command line used to run the tests:

> C:\Users\vsagent\.nuget\packages\xunit.runner.console\2.4.1-pre.build.4059\tools\net472\xunit.console.x86.exe "F:\workspace\_work\1\s\artifacts\bin\Microsoft.CodeAnalysis.EditorFeatures2.UnitTests\Debug\net472\Microsoft.CodeAnalysis.EditorFeatures2.UnitTests.dll" -class "ExpectedItem" -class "Microsoft.CodeAnalysis.Editor.Implementation.CodeFixes.UnitTests.CodeFixServiceTests" -class "Microsoft.CodeAnalysis.Editor.Implementation.CodeFixes.UnitTests.CodeFixServiceTests+ProjectCodeFixProvider" -class "Microsoft.CodeAnalysis.Editor.Implementation.CodeFixes.UnitTests.CodeFixServiceTests+WorkspaceCodeFixProvider" -class "Microsoft.CodeAnalysis.Editor.Implementation.CodeFixes.UnitTests.CodeFixServiceTests+WorkspaceDiagnosticAnalyzer" -class "Microsoft.CodeAnalysis.Editor.Implementation.Compilation.UnitTests.CompilationTests" -class "Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.UnitTests.DiagnosticProviderTests" -class "Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.UnitTests.DiagnosticServiceTests" -class "Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.UnitTests.DiagnosticServiceTests+CodeBlockEndedAnalyzer" -class "Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.UnitTests.DiagnosticServiceTests+CodeBlockOrSyntaxNodeAnalyzer" -class "Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.UnitTests.DiagnosticServiceTests+CodeBlockStartedAnalyzer`1" -class "Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.UnitTests.DiagnosticServiceTests+CodeBlockStartedAndEndedAnalyzer`1" -class "Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.UnitTests.DiagnosticServiceTests+CompilationAnalyzerWithAnalyzerOptions" -class "Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.UnitTests.DiagnosticServiceTests+CompilationEndedAnalyzer" -class "Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.UnitTests.DiagnosticServiceTests+DummySymbolAnalyzer" -class "Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.UnitTests.DiagnosticServiceTests+FailingTextLoader" -class "Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.UnitTests.DiagnosticServiceTests+FieldDeclarationAnalyzer" -class "Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.UnitTests.DiagnosticServiceTests+MethodSymbolAnalyzer" -class "Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.UnitTests.DiagnosticServiceTests+MustOverrideMethodAnalyzer" -class "Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.UnitTests.DiagnosticServiceTests+NamedTypeAnalyzer" -class "Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.UnitTests.DiagnosticServiceTests+PartialTypeDiagnosticAnalyzer" -class "Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.UnitTests.DiagnosticServiceTests+ProjectDiagnosticAnalyzer" -class "Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.UnitTests.DiagnosticServiceTests+ProjectDiagnosticAnalyzer2" -class "Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.UnitTests.DiagnosticServiceTests+StatefulCompilationAnalyzer" -class "Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.UnitTests.DiagnosticServiceTests+ThrowsExceptionAnalyzer" -class "Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.UnitTests.DiagnosticServiceTests+WorkspaceDiagnosticAnalyzer" -class "Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics.UnitTests.NamingStyleTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.Classification.ClassificationTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.Classification.ClassificationTests+NoCompilationEditorClassificationService" -class "Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AddImport.AddImportCrossLanguageTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AdditionalFiles.AdditionalFileAnalyzer" -class "Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AdditionalFiles.AdditionalFileDiagnosticsTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AdditionalFiles.AdditionalFileFixer" -class "Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.AddMissingReference.AddMissingReferenceTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.GenerateConstructor.GenerateConstructorCrossLanguageTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.GenerateEvent.GenerateEventCrossLanguageTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.GenerateMethod.GenerateMethodCrossLanguageTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.GenerateVariable.GenerateVariableCrossLanguageTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.ImplementInterface.ImplementInterfaceCrossLanguageTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.UseAutoProperty.UseAutoPropertyTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.Expansion.ExtensionMethodExpansionRewriteTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.Expansion.LambdaParameterExpansionTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.Expansion.ModuleNameExpansionTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.Expansion.NameExpansionTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.FindReferences.FindReferencesCommandHandlerTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.FindReferences.FindReferencesTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.FindReferences.FindReferencesTests+FileNameAndSpans" -class "Microsoft.CodeAnalysis.Editor.UnitTests.FindReferences.FindReferencesTests+TestHost" -class "Microsoft.CodeAnalysis.Editor.UnitTests.FindReferences.FindReferencesTests+TestKind" -class "Microsoft.CodeAnalysis.Editor.UnitTests.GoToBase.CSharpGoToBaseTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.GoToBase.VisualBasicGoToBaseTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.GoToDefinition.GoToDefinitionCancellationTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.GoToDefinition.GoToDefinitionTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.GoToImplementation.GoToImplementationTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CompletionRulesTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CompletionServiceTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CompletionServiceTests_Exclusivity" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CompletionServiceTests_Exclusivity+CompletionItemExclusive2CompletionProvider" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CompletionServiceTests_Exclusivity+CompletionItemExclusiveCompletionProvider" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CompletionServiceTests_Exclusivity+CompletionItemNonExclusiveCompletionProvider" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CompletionServiceTests+TestCompletionProvider" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests_InternalsVisibleTo" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests_Projections" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests_Regex" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests_XmlDoc" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests+BooleanTaskControlledCompletionProvider" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests+CompletedTaskControlledCompletionProvider" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests+IntelliCodeMockProvider" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests+IntelliCodeMockWeirdProvider" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests+MultipleChangeCompletionProvider" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests+SlowProvider" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests+TaskControlledCompletionProvider+ProviderCalledEventHandler" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpIntelliSenseCommandHandlerTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpSignatureHelpCommandHandlerTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.FormattingCommandHandlerTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.IntellisenseQuickInfoBuilderTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.IntellisenseQuickInfoBuilderTests_Inheritdoc" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.IntellisenseQuickInfoBuilderTests_Links" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.IntellisenseQuickInfoBuilderTests_Lists" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.IntellisenseQuickInfoBuilderTests_Styles" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.ModelTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.ModelTests+TestModelComputation" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.SessionTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.SignatureHelpControllerTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicCompletionCommandHandlerTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicCompletionCommandHandlerTests_InternalsVisibleTo" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicCompletionCommandHandlerTests_Projections" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicCompletionCommandHandlerTests_Regex" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicCompletionCommandHandlerTests_XmlDoc" -class "Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicSignatureHelpCommandHandlerTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.InteractivePaste.InteractivePasteCommandhandlerTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.KeywordHighlighting.CSharpKeywordHighlightingTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.KeywordHighlighting.VisualBasicKeywordHighlightingTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.LanguageServices.SyntaxFactsServiceTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.NavigableSymbols.NavigableSymbolsTest" -class "Microsoft.CodeAnalysis.Editor.UnitTests.NavigationBar.CSharpNavigationBarTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.NavigationBar.NavigationBarControllerTests" -class "Microsoft.CodeAnalysis.Editor.UnitTests.NavigationBar.VisualBasicNavigationBarTests"  -xml "F:\workspace\_work\1\s\artifacts\TestResults\Debug\Microsoft.CodeAnalysis.EditorFeatures2.UnitTests.dll.1.xml" -noshadow -verbose

### PR DESCRIPTION
**Pull request by jaredpar**
The EditorFeatures2 flakiness was being caused by two separate issues.
The first underlying problem is a simple bug in async completion. This
issue is being tracked by the VS editor team here

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1091056

The second issue is how the Roslyn test framework handles unexpected
extension exceptions. It was using a `FailFast` call when this happened
vs. using `Assert.Fail` or similar. The reason being that at the point
the unexpected exception is detected using `Assert.Fail` isn't effective
because the editor is going to catch and swallow all exceptions. The
`FailFast` is the only way to guarantee that the test will fail.

The downside to `FailFast` though is that it doesn't produce actionable
information. The xUnit process will simply exit with no stack trace,
failure message, etc .... just a fail fast error code. This makes
failures like this incredibly hard to track down.

To fix this the `TestExtensionErrorHandler` will now store the
unexpected `Exception` object and the containing workspace will look for
it and fail the test in `Dispose`. This will reliably fail the tests
that use `TestWorkspace` in this manner.

closes #42586

### CODE REVIEW

File: src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs [hunk 1]
```diff
@@ -75,6 +76,7 @@ public TestWorkspace(ExportProvider exportProvider, string? workspaceKind = null
             _backgroundParser.Start();
 
             _metadataAsSourceFileService = exportProvider.GetExportedValues<IMetadataAsSourceFileService>().FirstOrDefault();
+            _testExtensionErrorHandler = exportProvider.GetExportedValue<TestExtensionErrorHandler>();
```
Comment (sharwell) [inline src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs:79]: ❗️ This should move to `UseExportProviderAttribute`. `TestExtensionErrorHandler` is a MEF part, and that attribute contains the test cleanup code that applies to all tests using MEF, whether or not they use `TestWorkspace`.

Comment (jaredpar) [reply src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs:79]: Not sure what you're suggesting here. Can you provide an example for me to use as reference here?

Comment (sharwell) [reply src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs:79]: I was being literal. Here is the MEF cleanup code:

https://github.com/dotnet/roslyn/blob/b2254719aa74c9c96bd3df1b9be96fb73727fec1/src/Workspaces/CoreTestUtilities/MEF/UseExportProviderAttribute.cs#L80-L153

Comment (sharwell) [reply src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs:79]: This one will almost certainly operate in the same manner as `listenerProvider`, and occur _after_ that one in the `try` block to ensure we still throw if pending asynchronous work ends up triggering the failure.

**Comment by jaredpar** [comment]
PR updated
