### PR TITLE
Fix "IDE0057: Invalid code fix with string.Substring and null-conditional operator"

### LINKED ISSUE #47183: IDE0057: Invalid code fix with string.Substring and null-conditional operator
**Version Used**: 
16.8.0 Preview 2.0

**Steps to Reproduce**:
```C#
#nullable enable
public class Test
{
    public string? M(string? arg)
        => arg?.Substring(42); // IDE0057
}
```

**Expected Behavior**:
```C#
#nullable enable
public class Test
{
    public string? M(string? arg)
        => arg?[42..]; // IDE0057
}
```

**Actual Behavior**:
The code fix generates invalid code:
```C#
#nullable enable
public class Test
{
    public static string? M(string? arg)
        => arg?.Substring[42..]; // IDE0057
}
```
Note that the `.Substring` is still there.

image

### PR DESCRIPTION
**Pull request by MaStr11**
Fixes #47183

### CODE REVIEW

File: src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs [hunk 1]
```diff
@@ -842,5 +842,33 @@ void Goo(string s, int[] bar)
...
+    public string? M(string? arg)
+        => arg?[42..];
+}";
+            await new VerifyCS.Test
+            {
+                ReferenceAssemblies = ReferenceAssemblies.NetCore.NetCoreApp31,
+                TestCode = source,
+                FixedCode = fixedSource,
+            }.RunAsync();
+        }
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs:872]: can we have a test for cases like:

`a?.b.Substring(42)`  and
`a?.Substring(42).Length`

?

Thanks!

Comment (MaStr11) [reply src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs:872]: Done in cddd46ce6019fb5e82c95e8608eee821e845f75e

**Review by MaStr11 — COMMENTED** [review]
@CyrusNajmabadi tests are added and I also simplified the switch expression in 645c80ddf3cd9c32b40884fe243a2cba42c5eed8.

File: src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs [hunk 2]
```diff
@@ -842,5 +842,108 @@ void Goo(string s, int[] bar)
...
+
+        [WorkItem(47183, "https://github.com/dotnet/roslyn/issues/47183")]
+        [Theory, Trait(Traits.Feature, Traits.Features.CodeActionsUseRangeOperator)]
+        [InlineData(
+            "c.Prop.Substring([|42|])",
+            "c.Prop[42..]")]
+        [InlineData(
+            "c.Prop.Substring([|42, c.Prop.Length - 1|])",
+            "c.Prop[42..^(-41)]")]
```
Comment (MaStr11) [inline src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs:907]: This one looks odd. I this right or another bug?

Comment (CyrusNajmabadi) [reply src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs:907]: I think it's right given that substring is start/length, not start/end. 

Test with likely be clearer as: .Substring(1, c.Prop.Length-2)

I.e. an attempt to trim the first and last char from the string.

Comment (MaStr11) [reply src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs:907]: The range looks odd because the SubString call is bogus (OutOfRangeException). Must be more like `c.Prop.Substring(42, c.Prop.Length - 43)`. I will change the test case to more sensible values.

File: src/Analyzers/CSharp/CodeFixes/UseIndexOrRangeOperator/CSharpUseRangeOperatorCodeFixProvider.cs [hunk 3]
```diff
@@ -99,23 +99,28 @@ private static InvocationExpressionSyntax GetInvocationExpression(Diagnostic d,
...
             var argument = Argument(rangeExpression).WithAdditionalAnnotations(Formatter.Annotation);
             var arguments = SingletonSeparatedList(argument);
 
             if (result.MemberInfo.OverloadedMethodOpt == null)
             {
+                var expression = invocation.Expression switch
+                {
+                    MemberAccessExpressionSyntax memberAccess => memberAccess.Expression,
+                    MemberBindingExpressionSyntax _ => null,
+                    _ => invocation.Expression
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/CodeFixes/UseIndexOrRangeOperator/CSharpUseRangeOperatorCodeFixProvider.cs:113]: i think this piece should be doc'ed

File: src/Analyzers/CSharp/CodeFixes/UseIndexOrRangeOperator/CSharpUseRangeOperatorCodeFixProvider.cs [hunk 4]
```diff
@@ -99,23 +99,28 @@ private static InvocationExpressionSyntax GetInvocationExpression(Diagnostic d,
...
+
                 var argList = invocation.ArgumentList;
-                return ElementAccessExpression(
-                    expression,
-                    BracketedArgumentList(
+                var argumentList = BracketedArgumentList(
                         Token(SyntaxKind.OpenBracketToken).WithTriviaFrom(argList.OpenParenToken),
                         arguments,
-                        Token(SyntaxKind.CloseBracketToken).WithTriviaFrom(argList.CloseParenToken)));
+                        Token(SyntaxKind.CloseBracketToken).WithTriviaFrom(argList.CloseParenToken));
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/CodeFixes/UseIndexOrRangeOperator/CSharpUseRangeOperatorCodeFixProvider.cs:120]: i think it would be cleaner/nicer to just unilateraly make the argument list first, then specifically do a check if the expr is a member binding.  If so, you make an ElementBinding.  Then there's no weird tracking of this null value that has special meaning later on.

File: src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs:872]: i don't see the test for `a?.Substring(42).Length`, can you link me to the line for that?

Comment (CyrusNajmabadi) [reply src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs:872]: (note, conditional access, and property access in teh same expr).

File: src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs [hunk 5]
```diff
@@ -842,5 +842,108 @@ void Goo(string s, int[] bar)
...
+            {
+                ReferenceAssemblies = ReferenceAssemblies.NetCore.NetCoreApp31,
+                TestCode = source,
+                FixedCode = fixedSource,
+            }.RunAsync();
+        }
+
+        [WorkItem(47183, "https://github.com/dotnet/roslyn/issues/47183")]
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseRangeOperator)]
+        public async Task TestExpressionWithNullConditionalAccessWithPropertyAccess()
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs:876]: ther'es no null-conditional access in this test.

Comment (MaStr11) [reply src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs:876]: D'oh! Fixed in 22abd62b

File: src/Analyzers/CSharp/CodeFixes/UseIndexOrRangeOperator/CSharpUseRangeOperatorCodeFixProvider.cs (hunk 4 above)
Comment (MaStr11) [reply src/Analyzers/CSharp/CodeFixes/UseIndexOrRangeOperator/CSharpUseRangeOperatorCodeFixProvider.cs:113]: Done in 26cc13fb.

File: src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs (hunk 2 above)
Comment (MaStr11) [reply src/Analyzers/CSharp/Tests/UseIndexOrRangeOperator/UseRangeOperatorTests.cs]: I change the values in 22abd62b

**Comment by MaStr11** [comment]
> would still like this specially handled, instead of using null here. note: i'm happy to make this change if you'd prefer.

It should be fine now (26cc13fb). If not you may change it as desired. I pushed all my local changes.

File: src/Analyzers/CSharp/CodeFixes/UseIndexOrRangeOperator/CSharpUseRangeOperatorCodeFixProvider.cs [hunk 6]
```diff
@@ -110,12 +107,19 @@ private static ExpressionSyntax FixOne(Result result, SyntaxGenerator generator)
...
+                if (invocation.Expression is MemberBindingExpressionSyntax)
+                {
+                    return ElementBindingExpression(argumentList);
+                }
+
+                var expression = invocation.Expression is MemberAccessExpressionSyntax memberAccess
+                    ? memberAccess.Expression
+                    : invocation.Expression;
+                return ElementAccessExpression(expression, argumentList);
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/CodeFixes/UseIndexOrRangeOperator/CSharpUseRangeOperatorCodeFixProvider.cs:122]: nice, i like thsi a lot more.  my only suggestion (optional) is that in cases like this, we just show the before->After.  i.e. `x?.Substring(...) -> x?[...]` to help make it clear which user cases each is handling.  but it's not required here :)

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/Analyzers/CSharp/CodeFixes/UseIndexOrRangeOperator/CSharpUseRangeOperatorCodeFixProvider.cs [hunk 7]
```diff
@@ -110,12 +107,20 @@ private static ExpressionSyntax FixOne(Result result, SyntaxGenerator generator)
...
+                if (invocation.Expression is MemberBindingExpressionSyntax)
+                {
+                    // x?.Substring(...) -> x?[...]
+                    return ElementBindingExpression(argumentList);
+                }
+
+                var expression = invocation.Expression is MemberAccessExpressionSyntax memberAccess
+                    ? memberAccess.Expression // x.Substring(...) -> x[...]
+                    : invocation.Expression;
+                return ElementAccessExpression(expression, argumentList);
```
Comment (MaStr11) [inline src/Analyzers/CSharp/CodeFixes/UseIndexOrRangeOperator/CSharpUseRangeOperatorCodeFixProvider.cs:123]: @CyrusNajmabadi Another nice variation would be this. It's slightly better IMO and I tested it locally. But because you already approved the current state, I will leave it as optional here. You may approve the suggestion if you think it is worth it. Furthermore, the last case `{ } otherInvocation => ElementAccessExpression(otherInvocation, argumentList),` case is never hit by the tests, so I don't know what this is about.
```suggestion
                return invocation.Expression switch
                {
                    MemberBindingExpressionSyntax _ => ElementBindingExpression(argumentList), // x?.SubString(...) -> x?[...]
                    MemberAccessExpressionSyntax memberAccess => ElementAccessExpression(memberAccess.Expression, argumentList), // x.SubString(...) -> x[...]
                    { } otherInvocation => ElementAccessExpression(otherInvocation, argumentList),
                };
```

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks!
