### PR TITLE
Do not attempt to prepare for an event hookup for a Handles clause in an invalid context.

### LINKED ISSUE #3448: VS & vbc.exe crash in M.CA.VB.Symbols.SourceMemberMethodSymbol.BindSingleHandlesClause
Two different repros using the following VB code:

```VB
Interface I
    Event E()
    Sub M() Handles Me.E
End Interface
```

**vbc.exe repro**

When I run vbc.exe directly against this code, it runs and appears to finish, but prints nothing to the console and returns -2146232797 (= 0x80131623 = FailFast). I would expect ```BC30270: 'Handles' is not valid on an interface method declaration.```

**VS repro**
Paste the above code into a VB file causes a crash. Lots of features lead down into the [Debug.Assert & subsequent IndexOutOfRangeException](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Symbols/Source/SourceMemberMethodSymbol.vb,761) in SourceMemberMethodSymbol.BindSingleHandlesClause, whether through binding a symbol or trying to get all diagnostics.

A failfast in classification finally brings down VS:

```	
Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler) Line 151	C#
 >Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Classification.AbstractClassificationService.AddSemanticClassificationsAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan textSpan, System.Func<Microsoft.CodeAnalysis.SyntaxNode, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.Classifiers.ISyntaxClassifier>> getNodeClassifiers, System.Func<Microsoft.CodeAnalysis.SyntaxToken, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.Classifiers.ISyntaxClassifier>> getTokenClassifiers, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.ClassifiedSpan> result, System.Threading.CancellationToken cancellationToken) Line 34	C#
 	[Resuming Async Method]	
 	[Native to Managed Transition]	
 	System.Collections.Immutable.dll!System.Collections.Immutable.ImmutableArray<System.__Canon>.this[int].get(int index) Line 123	C#
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceMemberMethodSymbol.BindSingleHandlesClause(Microsoft.CodeAnalysis.VisualBasic.Syntax.HandlesClauseItemSyntax singleHandleClause, Microsoft.CodeAnalysis.VisualBasic.Binder typeBinder, Microsoft.CodeAnalysis.DiagnosticBag diagBag, Microsoft.CodeAnalysis.ArrayBuilder(Of Microsoft.CodeAnalysis.VisualBasic.Symbol) candidateEventSymbols, Microsoft.CodeAnalysis.ArrayBuilder(Of Microsoft.CodeAnalysis.VisualBasic.Symbol) candidateWithEventsSymbols, Microsoft.CodeAnalysis.ArrayBuilder(Of Microsoft.CodeAnalysis.VisualBasic.Symbol) candidateWithEventsPropertySymbols, Microsoft.CodeAnalysis.VisualBasic.LookupResultKind resultKind) Line 765	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetHandledEventOrContainerSymbolsAndResultKind(Microsoft.CodeAnalysis.ArrayBuilder(Of Microsoft.CodeAnalysis.VisualBasic.Symbol) eventSymbolBuilder, Microsoft.CodeAnalysis.ArrayBuilder(Of Microsoft.CodeAnalysis.VisualBasic.Symbol) containerSymbolBuilder, Microsoft.CodeAnalysis.ArrayBuilder(Of Microsoft.CodeAnalysis.VisualBasic.Symbol) propertySymbolBuilder, Microsoft.CodeAnalysis.VisualBasic.Syntax.HandlesClauseItemSyntax handlesClause) Line 761	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetHandlesEventSymbolInfo(Microsoft.CodeAnalysis.VisualBasic.Syntax.HandlesClauseItemSyntax handlesClause, Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.SymbolInfoOptions options) Line 789	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetExpressionSymbolInfo(Microsoft.CodeAnalysis.VisualBasic.Syntax.ExpressionSyntax node, Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.SymbolInfoOptions options, System.Threading.CancellationToken cancellationToken) Line 234	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetSymbolInfo(Microsoft.CodeAnalysis.VisualBasic.Syntax.ExpressionSyntax expression, System.Threading.CancellationToken cancellationToken) Line 152	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.VisualBasicExtensions.GetSymbolInfo(Microsoft.CodeAnalysis.SemanticModel semanticModel, Microsoft.CodeAnalysis.VisualBasic.Syntax.ExpressionSyntax expression, System.Threading.CancellationToken cancellationToken) Line 1266	Basic
 	Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll!Microsoft.CodeAnalysis.VisualBasic.Classification.Classifiers.NameSyntaxClassifier.ClassifyNameSyntax(Microsoft.CodeAnalysis.VisualBasic.Syntax.NameSyntax node, Microsoft.CodeAnalysis.SemanticModel semanticModel, System.Threading.CancellationToken cancellationToken) Line 48	Basic
 	Microsoft.CodeAnalysis.VisualBasic.Workspaces.dll!Microsoft.CodeAnalysis.VisualBasic.Classification.Classifiers.NameSyntaxClassifier.ClassifyNode(Microsoft.CodeAnalysis.SyntaxNode syntax, Microsoft.CodeAnalysis.SemanticModel semanticModel, System.Threading.CancellationToken cancellationToken) Line 26	Basic
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Classification.AbstractClassificationService.Worker.ClassifyNode(Microsoft.CodeAnalysis.SyntaxNode syntax) Line 120	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Classification.AbstractClassificationService.Worker.ClassifyNodeOrToken(Microsoft.CodeAnalysis.SyntaxNodeOrToken nodeOrToken) Line 107	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Classification.AbstractClassificationService.Worker.ProcessNodes() Line 92	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Classification.AbstractClassificationService.Worker.Classify(Microsoft.CodeAnalysis.Workspace workspace, Microsoft.CodeAnalysis.SemanticModel semanticModel, Microsoft.CodeAnalysis.Text.TextSpan textSpan, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.ClassifiedSpan> list, System.Func<Microsoft.CodeAnalysis.SyntaxNode, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.Classifiers.ISyntaxClassifier>> getNodeClassifiers, System.Func<Microsoft.CodeAnalysis.SyntaxToken, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.Classifiers.ISyntaxClassifier>> getTokenClassifiers, System.Threading.CancellationToken cancellationToken) Line 63	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Classification.AbstractClassificationService.AddSemanticClassifications(Microsoft.CodeAnalysis.SemanticModel semanticModel, Microsoft.CodeAnalysis.Text.TextSpan textSpan, Microsoft.CodeAnalysis.Workspace workspace, System.Func<Microsoft.CodeAnalysis.SyntaxNode, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.Classifiers.ISyntaxClassifier>> getNodeClassifiers, System.Func<Microsoft.CodeAnalysis.SyntaxToken, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.Classifiers.ISyntaxClassifier>> getTokenClassifiers, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.ClassifiedSpan> result, System.Threading.CancellationToken cancellationToken) Line 42	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Classification.AbstractClassificationService.AddSemanticClassificationsAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan textSpan, System.Func<Microsoft.CodeAnalysis.SyntaxNode, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.Classifiers.ISyntaxClassifier>> getNodeClassifiers, System.Func<Microsoft.CodeAnalysis.SyntaxToken, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.Classifiers.ISyntaxClassifier>> getTokenClassifiers, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.ClassifiedSpan> result, System.Threading.CancellationToken cancellationToken) Line 32	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.Classification.AbstractEditorClassificationService.AddSemanticClassificationsAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan textSpan, System.Collections.Generic.List<Microsoft.CodeAnalysis.Classification.ClassifiedSpan> result, System.Threading.CancellationToken cancellationToken) Line 31	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.Classification.SemanticClassificationTaggerProvider.TagProducer.ProduceTagsAsync(Microsoft.CodeAnalysis.Document document, Microsoft.VisualStudio.Text.SnapshotSpan snapshotSpan, int? caretPosition, System.Threading.CancellationToken cancellationToken) Line 65	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Shared.Tagging.AbstractSingleDocumentTagProducer<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>.ProduceTagsAsync(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan> snapshotSpans, Microsoft.VisualStudio.Text.SnapshotPoint? caretPosition, System.Threading.CancellationToken cancellationToken) Line 45	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Shared.Tagging.ProducerPopulatedTagSource<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>.RecomputeTagsAsync(Microsoft.VisualStudio.Text.SnapshotPoint? caretPosition, Microsoft.CodeAnalysis.Text.TextChangeRange? textChangeRange, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan> spansToCompute, System.Threading.CancellationToken cancellationToken) Line 573	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Shared.Tagging.TagSources.SemanticBufferTagSource<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>.<>n__0(Microsoft.VisualStudio.Text.SnapshotPoint? caretPosition, Microsoft.CodeAnalysis.Text.TextChangeRange? textChangeRange, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan> spansToCompute, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Shared.Tagging.TagSources.SemanticBufferTagSource<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>.RecomputeTagsAsync(Microsoft.CodeAnalysis.Text.TextChangeRange? range, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan> spansToCompute, Microsoft.CodeAnalysis.Document document, Microsoft.VisualStudio.Text.ITextSnapshot snapshot, Microsoft.CodeAnalysis.VersionStamp oldVersion, Microsoft.CodeAnalysis.VersionStamp newVersion, System.Threading.CancellationToken cancellationToken) Line 103	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Shared.Tagging.TagSources.SemanticBufferTagSource<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>.RecomputeTagsAsync(Microsoft.VisualStudio.Text.SnapshotPoint? caret, Microsoft.CodeAnalysis.Text.TextChangeRange? range, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan> spansToCompute, System.Threading.CancellationToken cancellationToken) Line 68	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Shared.Tagging.ProducerPopulatedTagSource<Microsoft.VisualStudio.Text.Tagging.IClassificationTag>.RecomputeTagsForeground.AnonymousMethod__0(System.Threading.CancellationToken ct) Line 408	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Shared.Threading.AsynchronousSerialWorkQueue.EnqueueBackgroundTask.AnonymousMethod__0(System.Threading.Tasks.Task _) Line 130	C#
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #3448.

@VSadov, @gafter, @agocke, @jaredpar, @khyperia Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
- Bug number - Fixes #3448.
- Customer scenario – An attempt to use Handles clause in an interface (an error scenario) causes a crash of VS and compiler:
```
Interface I
    Event E()
    Sub M() Handles Me.E
End Interface
```   
- Fix description - Do not attempt to prepare for an event hookup for a Handles clause in an invalid context.
- Testing done - unit-tests.

@jaredpar FYI

**Comment by AlekseyTs** [comment]
Ping. @VSadov, @gafter, @agocke, @jaredpar, @khyperia Please review.

**Comment by VSadov** [comment]
LGTM

File: src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberMethodSymbol.vb [hunk 1]
```diff
@@ -743,6 +743,18 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols
...
+            Select Case ContainingType.TypeKind
+                Case TypeKind.Interface, TypeKind.Structure, TypeKind.Enum, TypeKind.Delegate
+                    ' Handles clause is invalid in this context. 
+                    Return Nothing
+
+                Case TypeKind.Class, TypeKind.Module
+                    ' Valid context
+
+                Case Else
+                    Debug.Assert(False)
```
Comment (amcasey) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberMethodSymbol.vb]: If you used the assert in ```ExceptionUtilities.UnexpectedValue``` it would include the type and value in the assert message.  Also, do you want to return ```Nothing```?

**Comment by amcasey** [comment]
LGTM

File: src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberMethodSymbol.vb (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberMethodSymbol.vb]: RE: ExceptionUtilities.UnexpectedValue
I don't want to throw here, just to assert.

RE: do you want to return Nothing?
No, my intent is to continue.

Comment (gafter) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberMethodSymbol.vb]: If your intent is to continue... you believe the continuation (the rest of this method) will have no problem in that case?

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberMethodSymbol.vb]: Yes, there is a very good chance that it would just work. For example, it would work fine for Structures. It wouldn't for an Interface because an Interface doesn't have a constructor.

Comment (gafter) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberMethodSymbol.vb]: If the following code depends on there being a constructor, it seems you should check for one rather than plowing ahead, no?

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberMethodSymbol.vb]: I don't see any value in throwing here vs. crashing five lines below. Returning ```Nothing``` is not an option in my opinion.

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberMethodSymbol.vb]: Note that we are talking about hypothetical scenario that, to my best knowledge, doesn't exist.

Comment (gafter) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberMethodSymbol.vb]: Crashing in production seems a poor plan.

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceMemberMethodSymbol.vb]: Thank you for your feedback. I tested the code to the best of my ability. As we discussed offline, I prefer the code with the switch and with an assert.

**Comment by MattGertz** [comment]
Approved 6/12 by ML Shiproom.
