### PR TITLE
Prefer converting to ReadOnlySpan for spread optimization when we do not need to write

### LINKED ISSUE #71720: Collection expression spreads on arrays can result in variance exceptions
**Version Used**: 
Version 17.10.0 Preview 1.0 [34516.246.main]

**Steps to Reproduce**:
```C#
Base[] array = new Derived[3];
Base[] copy = [.. array];

class Base { }
class Derived : Base { }
```

**Expected Behavior**:
Creates a copy of the array.

**Actual Behavior**:
Throws an exception:
```
Unhandled exception. System.ArrayTypeMismatchException: Attempted to access an element as a type incompatible with the array.
```

The problem is that the compiler is generating the equivalent of this code for the collection expression:
```C#
Base[] copy = new Span<Base>(array).ToArray();
```
`Span`'s constructor does a variance check that throws an exception if `typeof(T[]) != array.GetType()`, because if that was allowed, you could end up in a situation where you're able to violate type safety by writing things other than `Derived` into the array.

The fix should be simple: generate use of `ReadOnlySpan` instead of `Span`, e.g.
```C#
Base[] copy = new ReadOnlySpan<Base>(array).ToArray();
```
ReadOnlySpan doesn't do such checks because you can't write into it and thus it doesn't need to protect against such variance issues. That also means it's a tad faster, as it doesn't have to do the extra check.

cc: @RikkiGibson, @cston

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #71720

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 1]
```diff
@@ -538,11 +538,11 @@ private BoundExpression CreateAndPopulateArray(BoundCollectionExpression node, A
...
                 }
 
-                if (TryGetSpanConversion(spreadExpression.Type, out var asSpanMethod))
+                if (TryGetSpanConversion(spreadExpression.Type, writableOnly: false, out var asSpanMethod))
                 {
                     var spanType = CallAsSpanMethod(spreadExpression, asSpanMethod).Type!.OriginalDefinition;
-                    if (tryGetToArrayMethod(spanType, WellKnownType.System_Span_T, WellKnownMember.System_Span_T__ToArray, out var toArrayMethod)
-                        || tryGetToArrayMethod(spanType, WellKnownType.System_ReadOnlySpan_T, WellKnownMember.System_ReadOnlySpan_T__ToArray, out toArrayMethod))
+                    if (tryGetToArrayMethod(spanType, WellKnownType.System_ReadOnlySpan_T, WellKnownMember.System_ReadOnlySpan_T__ToArray, out var toArrayMethod)
+                        || tryGetToArrayMethod(spanType, WellKnownType.System_Span_T, WellKnownMember.System_Span_T__ToArray, out toArrayMethod))
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:545]: Reordered these as I think the ReadOnlySpan case will now be more common

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs [hunk 2]
```diff
@@ -29653,6 +29653,158 @@ .maxstack  5
...
+                  IL_0006:  dup
+                  IL_0007:  ldc.i4.0
+                  IL_0008:  newobj     "Derived..ctor()"
+                  IL_000d:  stelem.ref
+                  IL_000e:  stloc.0
+                  IL_000f:  ldloc.0
+                  IL_0010:  dup
+                  IL_0011:  ldc.i4.0
+                  IL_0012:  call       "void CollectionExtensions.Report(object, bool)"
+                  IL_0017:  newobj     "System.ReadOnlySpan<Base>..ctor(Base[])"
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:29695]: >IL_0017:  newobj     "System.ReadOnlySpan<Base>..ctor(Base[])" [](http://example.com/codeflow?start=18&length=62)

Are we testing scenario when this constructor is marked as missing?

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs [hunk 3]
```diff
@@ -29653,6 +29653,158 @@ .maxstack  5
...
+                  IL_0021:  conv.i4
+                  IL_0022:  add
+                  IL_0023:  newarr     "Base"
+                  IL_0028:  stloc.3
+                  IL_0029:  ldloca.s   V_4
+                  IL_002b:  ldloc.0
+                  IL_002c:  call       "System.ReadOnlySpan<Base>..ctor(Base[])"
+                  IL_0031:  ldloca.s   V_4
+                  IL_0033:  ldloc.3
+                  IL_0034:  newobj     "System.Span<Base>..ctor(Base[])"
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:29769]: >IL_0034:  newobj     "System.Span<Base>..ctor(Base[])" [](http://example.com/codeflow?start=18&length=54)

What are we creating this span for?

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs [hunk 4]
```diff
@@ -29653,6 +29653,158 @@ .maxstack  5
...
+                  IL_0050:  ldloca.s   V_4
+                  IL_0052:  call       "int System.ReadOnlySpan<Base>.Length.get"
+                  IL_0057:  add
+                  IL_0058:  stloc.2
+                  IL_0059:  ldloca.s   V_5
+                  IL_005b:  ldloc.1
+                  IL_005c:  call       "System.ReadOnlySpan<Base>..ctor(Base[])"
+                  IL_0061:  ldloca.s   V_5
+                  IL_0063:  ldloc.3
+                  IL_0064:  newobj     "System.Span<Base>..ctor(Base[])"
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:29787]: >IL_0064:  newobj     "System.Span<Base>..ctor(Base[])" [](http://example.com/codeflow?start=18&length=54)

Here as well?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 5]
```diff
@@ -667,15 +667,16 @@ bool tryGetToArrayMethod(TypeSymbol spreadTypeOriginalDefinition, WellKnownType
                 arrayType);
         }
 
-        /// <summary>
-        /// Returns true if type is convertible to Span or ReadOnlySpan.
-        /// If non-identity conversion, also returns a non-null asSpanMethod.
-        /// </summary>
+        /// <returns>
+        /// If <paramref name="writableOnly"/> is <see langword="true"/>, will only return true with a conversion to writable Span.
+        /// Otherwise, will return a conversion directly to ReadOnlySpan if one is known, and may return a conversion to Span if no direct conversion to ReadOnlySpan is known, or if the type is already a Span.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:672]: >and may return a conversion to Span if no direct conversion to ReadOnlySpan is known, or if the type is already a Span. [](http://example.com/codeflow?start=90&length=119)

I think we should never be doing this for array types. In other words, if we do not intend to write into the span, we should never attempt to convert it to ```Span```

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:29769]: We do this so we can use the result collection as a destination in `ReadOnlySpan<T>.CopyTo(Span<T> destination)`. The optimization is oriented around using this method because it is fast and usable with a variety of source and destination types.

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:29787]: We are creating a new "destination" span each time we copy a spread element to the resulting collection. Issue #71270 tracks improving this.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs (hunk 5 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:672]: It is quite possible that we are doing the right thing, but the comment is confusing. What does it mean for the conversion to be known?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 6]
```diff
@@ -692,14 +693,15 @@ private bool TryGetSpanConversion(TypeSymbol type, out MethodSymbol? asSpanMetho
...
-                || namedType.OriginalDefinition.Equals(_compilation.GetWellKnownType(WellKnownType.System_ReadOnlySpan_T), TypeCompareKind.ConsiderEverything))
+            if ((!writableOnly && namedType.OriginalDefinition.Equals(_compilation.GetWellKnownType(WellKnownType.System_ReadOnlySpan_T), TypeCompareKind.ConsiderEverything))
+                || namedType.OriginalDefinition.Equals(_compilation.GetWellKnownType(WellKnownType.System_Span_T), TypeCompareKind.ConsiderEverything))
             {
                 asSpanMethod = null;
                 return true;
             }
 
-            if (namedType.OriginalDefinition.Equals(_compilation.GetWellKnownType(WellKnownType.System_Collections_Immutable_ImmutableArray_T), TypeCompareKind.ConsiderEverything)
+            if (!writableOnly
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:703]: >!writableOnly [](http://example.com/codeflow?start=16&length=13)

It looks like we are returning conversion to a writable ```Span``` regardless. Why do the check then? And is there a conversion to ```ReadOnlySpan``` we can use?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:703]: It looks like ```ImmutableArray.AsSpan``` returns ```ReadOnlySpan ```. It all makes sense now.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:703]: [ImmutableArray<T>.AsSpan](https://learn.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablearray-1.asspan?view=net-8.0#system-collections-immutable-immutablearray-1-asspan) returns `ReadOnlySpan`, so in this path, we are returning a conversion to `ReadOnlySpan`. Perhaps it would be helpful to add a comment about the signature of this method.

**Comment by RikkiGibson** [comment]
> Also, please confirm that there are no other places where we request a `Span` from an array during collection expression lowering. The destination array that we create ourselves is an exception, of course.

That's correct, the only time we are converting an array to Span for this optimization is for the destination array.

Thinking on it now, we could probably simplify here by having a one-off bit of codegen for converting the array to writable Span, adjusting 'TryGetSpanConversion' to remove the "writableOnly" parameter, and making it simply return the "best" Span type for use as a receiver in a call to either `Span/ReadOnlySpan.CopyTo(Span)`.

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs [hunk 7]
```diff
@@ -30048,6 +30287,381 @@ .maxstack  3
...
+                        int[] arr = [1, 2, 3];
+                        arr.Report();
+                        int[] arr1 = [..arr];
+                        arr1.Report();
+                    }
+                }
+                """;
+
+            var comp = CreateCompilation([source, s_collectionExtensions], targetFramework: TargetFramework.Net80, options: TestOptions.ReleaseExe);
+            comp.VerifyEmitDiagnostics();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:30307]: >VerifyEmitDiagnostics [](http://example.com/codeflow?start=17&length=21)

Minor, non-blocking suggestion: Consider calling ```VerifyDiagnoctics``` on result of ```CompileAndVerify``` instead. This should eliminate a redundant emit and will make the test faster a bit.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 2)
