### PR TITLE
Ensure that an attempt to embed a generic type from PIA results in an error.

### LINKED ISSUE #13200: References to generic types when linking/embedding should fail compilation
This came up in the [PR for missing tuple handling cases](https://github.com/dotnet/roslyn/pull/13024#discussion_r74807282).

``` C#
        [ClrOnlyFact]
        public void CannotEmbedValueTupleImplicitlyReferred()
        {
            string piaSource = @"
using System;
using System.Runtime.InteropServices;

[assembly: Guid(""f9c2d51d-4f44-45f0-9eda-c9d599b58257"")]
[assembly: ImportedFromTypeLib(""Pia1.dll"")]

public struct S<T> { }

namespace System
{
    public struct ValueTuple<T1, T2>
    {
        public ValueTuple(T1 item1, T2 item2) { }
    }
}

[ComImport()]
[Guid(""f9c2d51d-4f44-45f0-9eda-c9d599b58280"")]
public interface ITest1
{
    (int, int) M();
    S<int> M2();
}";

            var pia = CreateCompilationWithMscorlib(piaSource, options: TestOptions.ReleaseDll, assemblyName: "pia");
            pia.VerifyEmitDiagnostics();

            string source = @"
public interface ITest2 : ITest1 { }
";

            // We should expect errors as generic types cannot be embedded
            var expectedDiagnostics = new DiagnosticDescription[]
            {
            };

            var comp1 = CreateCompilationWithMscorlib(source, options: TestOptions.ReleaseDll,
                            references: new MetadataReference[] { pia.ToMetadataReference(embedInteropTypes: true) });
            comp1.VerifyEmitDiagnostics(expectedDiagnostics);

            var comp2 = CreateCompilationWithMscorlib(source, options: TestOptions.ReleaseDll,
                            references: new MetadataReference[] { pia.EmitToImageReference(embedInteropTypes: true) });
            comp2.VerifyEmitDiagnostics(expectedDiagnostics);
        }

        [ClrOnlyFact]
        public void CannotEmbedValueTupleImplicitlyReferredFromMetadata()
        {
            string piaSource = @"
using System;
using System.Runtime.InteropServices;

[assembly: Guid(""f9c2d51d-4f44-45f0-9eda-c9d599b58257"")]
[assembly: ImportedFromTypeLib(""Pia1.dll"")]

public struct S<T> { }

namespace System
{
    public struct ValueTuple<T1, T2>
    {
        public ValueTuple(T1 item1, T2 item2) { }
    }
}";

            var libSource = @"
public class D
{
    public static (int, int) M() { throw new System.Exception(); }
    public static S<int> M2() { throw new System.Exception(); }
}";

            var pia = CreateCompilationWithMscorlib(piaSource, options: TestOptions.ReleaseDll, assemblyName: "pia");
            pia.VerifyDiagnostics();

            var lib = CreateCompilationWithMscorlib(libSource, options: TestOptions.ReleaseDll, references: new[] { pia.ToMetadataReference() });
            lib.VerifyEmitDiagnostics();

            string source = @"
public class C
{
    public void TestTupleFromMetadata()
    {
        D.M();
        D.M2();
    }
    public void TestTupleAssignmentFromMetadata()
    {
        var t = D.M();
        t.ToString();
        var t2 = D.M2();
        t2.ToString();
    }
}";

            // We should expect errors, as generic types cannot be embedded
            var expectedDiagnostics = new DiagnosticDescription[]
            {
            };

            var comp1 = CreateCompilationWithMscorlib(source, options: TestOptions.ReleaseDll,
                            references: new MetadataReference[] { pia.ToMetadataReference(embedInteropTypes: true), lib.ToMetadataReference() });
            comp1.VerifyEmitDiagnostics(expectedDiagnostics);

            var comp2 = CreateCompilationWithMscorlib(source, options: TestOptions.ReleaseDll,
                            references: new MetadataReference[] { pia.EmitToImageReference(embedInteropTypes: true), lib.EmitToImageReference() });
            comp2.VerifyEmitDiagnostics(expectedDiagnostics);
        }
```

FYI for @AlekseyTs

### PR DESCRIPTION
**Pull request by AlekseyTs**
**Customer scenario**
Customer implicitly references a generic type defined in a linked (/link) assembly. Implicitly meaning that the customer inherits from an interface, which uses the type in one of its members, or the customer references a structure, which uses the type in one of its members, but never actually references the generic type itself. No error is reported, the type is not embedded, the assembly is referenced by the resulting binary as if it was referenced rather than linked. However, other types from the same assembly might still be embedded into the resulting binary.

**Bugs this fixes:** 
Fixes #13200.

**Workarounds, if any**
Avoid an implicit reference to a generic type defined in a linked (/link) assembly.

**Risk**
Low.

**Performance impact**
Low perf impact because no extra allocations and no complexity added.

**Is this a regression from a previous update?**
No

**Root cause analysis:**
A test gap for a non-common error scenario. Added unit-tests to close the gap.

**How was the bug found?**
Ad hoc testing

@dotnet/roslyn-compiler Please review.

### CODE REVIEW

File: src/Compilers/Core/Portable/PEWriter/Types.cs [hunk 1]
```diff
@@ -323,10 +320,7 @@ internal interface ISpecializedNestedTypeReference : INestedTypeReference
         /// type of a generic type instance), then the unspecialized member refers to a member from the unspecialized containing type. (I.e. the unspecialized member always
         /// corresponds to a definition that is not obtained via specialization.)
         /// </summary>
-        INestedTypeReference/*!*/ UnspecializedVersion
-        {
-            get;
-        }
+        INestedTypeReference/*!*/ GetUnspecializedVersion(EmitContext context);
```
Comment (jcouv) [inline src/Compilers/Core/Portable/PEWriter/Types.cs]: >/*!*/ [](start = 28, length = 5)

Just curious, what does `/*!*/` mean?

Comment (AlekseyTs) [inline src/Compilers/Core/Portable/PEWriter/Types.cs]: Probably "Not Null". The comments were inherited from CCI code base.

**Comment by cston** [comment]
LGTM

**Comment by jcouv** [comment]
>                 return this.ContainingType;

Unrelated to your change, but why don't we need to do translation here? (from `NamedTypeSymbol` to a Cci type)

---
Refers to: src/Compilers/CSharp/Portable/Emitter/Model/NamedTypeSymbolAdapter.cs:875 in d2c508d. [](commit_id = d2c508daf120975dcd2e9c6b1111dceefe348064, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>                 return this.ContainingType;

We already deal with definition (**ITypeDefinitionMember**.ContainingTypeDefinition) from the module being built (CheckDefinitionInvariant), ```this.ContainingType``` must be a definition as well, therefore, it has correct implementation of Cci.ITypeDefinition. Since Cci.ITypeDefinitionMember.ContainingTypeDefinition isn't used for indexing references, translating it is not likely to have any useful effect.

---
In reply to: [265301681](https://github.com/dotnet/roslyn/pull/15694#issuecomment-265301681) [](ancestors = 265301681)

---
Refers to: src/Compilers/CSharp/Portable/Emitter/Model/NamedTypeSymbolAdapter.cs:875 in d2c508d. [](commit_id = d2c508daf120975dcd2e9c6b1111dceefe348064, deletion_comment = False)

**Comment by AlekseyTs** [comment]
CC @MattGertz For Ask Mode sign-off.

**Comment by MattGertz** [comment]
Approved for RC3.
