### PR TITLE
Don't lose local function optional parameter information

### LINKED ISSUE #51518: Optional ParameterInfo is lost at runtime for local functions
**Version Used**: 

master (24 Feb 2021) on sharplab.io

**Steps to Reproduce**:

View [this sharplab.io snippet](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATARgFgAobAZgAI8KBhCgbxIuasuwBYKBZACgEoGTFsI4UAKnFgAZAPYBjCABts+XDwCWAOxgUIFALwVcfIcOaNiZlgF9TZu8K4QADirU83AHi0wAfHwlYLjgYAAsZFDc+AG4HFidXVR4PVW9tf0CYWQVlVRi7W0sWO3IqTkzgsIi3DW1dAyMTIvMCuxK2TgSagBE4RTgAcwh4XTkYdRlNJuELYULrIA=) and observe that this:

```C#
using System;
public class C {
    public void M() {
        void TestLocalAction(int a = 2)
        {
        }
        
        MapAction((Action<int>)TestMethodAction);
        MapAction((Action<int>)TestLocalAction);
    }
    
    public void TestMethodAction(int a = 2)
    {
    }
    
    public void MapAction(Delegate action)
    {
    }
}
```

results in this:

```C#
// ...
public class C
{
    public void M()
    {
        MapAction(new Action<int>(TestMethodAction));
        MapAction(new Action<int>(<M>g__TestLocalAction|0_0));
    }

    public void TestMethodAction(int a = 2)
    {
    }

    public void MapAction(Delegate action)
    {
    }

    [CompilerGenerated]
    internal static void <M>g__TestLocalAction|0_0(int a)
    {
    }
}
```

And that `<M>g__TestLocalAction|0_0` does not have a default value unlike `TestMethodAction`.

**Expected Behavior**:

`<M>g__TestLocalAction|0_0` should have `int a = 2` in its parameter list.

**Actual Behavior**:

`<M>g__TestLocalAction|0_0` does not have `int a = 2` in its parameter lists. This becomes a problem for `MapAction` if it wants to call `TestLocalAction` with the default parameter value. `Delegate.Method.GetParameters()[0].HasDefaultValue` ends up returning false instead of true.

Thanks @Kahbazi for finding this! https://github.com/dotnet/aspnetcore/pull/30434/files#r583502436

### LINKED ISSUE #53478: Local methods and delegates aren't populating ParameterInfo.DefaultValue
### Description

`ParameterInfo.DefaultValue` isn't available with local methods (and I'm guessing delegates as well). In [this ASP.NET Core feature](https://github.com/dotnet/aspnetcore/issues/32375) we want to use the default value information to make decisions about how a delegate will be called. e.g. use the default value when calling the method if no other value is available.

```cs
[Fact]
public void DefaultValueTest()
{
    void TestAction([FromRoute] int foo1 = 5)
    {
    }

    var method = GetType().GetMethod(nameof(TestAction), BindingFlags.Instance | BindingFlags.NonPublic)!;
    var p1 = method.GetParameters();
    Console.WriteLine(p1[0].HasDefaultValue);
    Console.WriteLine(p1[0].DefaultValue);
    // true
    // 5

    var d = (Action<int>)TestAction;
    var p2 = d.Method.GetParameters();
    Console.WriteLine(p2[0].HasDefaultValue);
    Console.WriteLine(p2[0].DefaultValue);
    // false
    // DBNull.Value
}

private void TestAction([FromRoute] int foo1 = 5)
{
}
```

### Configuration

Host (useful for support):
  Version: 6.0.0-preview.2.21154.6
  Commit:  3eaf1f316b

### Regression?

No

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #51518
Fixes #53478

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs [hunk 1]
```diff
@@ -285,5 +284,9 @@ public override ImmutableArray<CSharpAttributeData> GetAttributes()
         public bool HasEnumeratorCancellationAttribute => _baseParameterForAttributes?.HasEnumeratorCancellationAttribute ?? false;
 
         internal override MarshalPseudoCustomAttributeData? MarshallingInformation => _baseParameterForAttributes?.MarshallingInformation;
+
+        internal override bool IsMetadataOptional => _baseParameterForAttributes?.IsMetadataOptional == true;
+
+        internal override ConstantValue? ExplicitDefaultConstantValue => _baseParameterForAttributes?.ExplicitDefaultConstantValue;
```
Comment (Youssef1313) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs:290]: I'm not sure if there are other properties I should override, and what they'll affect.

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs [hunk 2]
```diff
@@ -285,5 +284,9 @@ public override ImmutableArray<CSharpAttributeData> GetAttributes()
         public bool HasEnumeratorCancellationAttribute => _baseParameterForAttributes?.HasEnumeratorCancellationAttribute ?? false;
 
         internal override MarshalPseudoCustomAttributeData? MarshallingInformation => _baseParameterForAttributes?.MarshallingInformation;
+
+        internal override bool IsMetadataOptional => _baseParameterForAttributes?.IsMetadataOptional == true;
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs:288]: We should verify if this causes a behavior change in any other scenarios, and if so, do we want that behavior change. For example, could this cause parameter default value info to be emitted for some other kind of declaration that we don't want it emitted for.

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs:288]: @RikkiGibson Based on @jaredpar comment on the issue, a breaking change is okay here.

One possible code that's going to have a behavioral change:

```csharp
using System;
public static class Program
{
    public static void Main()
    {
        void TestLocalAction(int a = 2)
        {
        }

        MapAction((Action<int>)TestMethodAction);
        MapAction((Action<int>)TestLocalAction);
    }

    public static void TestMethodAction(int a = 2)
    {
    }

    public static void MapAction(Delegate action)
    {
        Console.WriteLine(action.Method.GetParameters()[0].HasDefaultValue);
    }
}
```


I couldn't come up with a more "realistic" scenario.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs:288]: I agree that it is good to "break" this scenario, I just want to make sure that we've enumerated the other places in the compiler where a SynthesizedParameterSymbol can be created with a non-null `_baseParameterForAttributes`, in case this might impact other kinds of symbols.

I'll try and sit down later this afternoon and make sure of it myself. I think local functions might be the only scenario where we set a non-null value for this field, although lambdas might do it too now (cc @cston), and we probably would want the same kind of behavior for lambdas as we want for local functions here.

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs:288]: I think the only place for `_baseParameterForAttributes` to be non-null is `SynthesizedClosureMethod` (either a lambda or a local function).

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs:288]: > I think the only place for _baseParameterForAttributes to be non-null is SynthesizedClosureMethod (either a lambda or a local function).

It feels like we might want to add negative tests for other scenarios consuming ```SynthesizedParameterSymbol.Create```.

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs:288]: @AlekseyTs Any concrete/specific test cases you have in mind? For example, top-level entry point and record copy ctor are using `SynthesizedParameterSymbol.Create`. How a test for them would look like? they're never synthesized with optional parameters.

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs:290]: I looked over the `ParameterSymbol` members and all that comes to mind is `IsIDispatchConstant` and `IsIUnknownConstant`.

I think that synthesized parameter symbols with non-null `_baseParameterForAttributes` are only produced for lowering/emit, so we don't expect to actually check the `IsIDispatchConstant` or `IsIUnknownConstant` members from the `_baseParameterForAttributes`.

I am not certain whether it makes more sense to:
1. Do nothing to override or verify `IsIDispatchConstant` or `IsIUnknownConstant` on `SynthesizedComplexParameterSymbol` (i.e. don't change the implementation in this PR)
2. Change `IsIDispatchConstant` and `IsIUnknownConstant` on `SynthesizedParameterSymbolBase` to `throw ExceptionUtilities.Unreachable`, since we don't expect to check those members on such parameters, because we don't expect to bind a default argument based on such a parameter, for example. (I'm not certain about this--if it results in new CI failures then we'll have learned something about the usage :smile:)
3. Override `IsIDispatchConstant` and `IsIUnknownConstant` on `SynthesizedComplexParameterSymbol` to delegate to the `_baseParameterForAttributes`.

I'm leaning slightly toward (2).

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs:290]: @RikkiGibson Thanks. I took the second approach as you suggested.

Is there anything needed for nullable analysis here?

e.g, override `FlowAnalysisAnnotation` and things related to nullable analysis?

**Comment by Youssef1313** [comment]
D:\workspace\_work\1\s\src\Tools\Source\CompilerGeneratorTools\Source\CSharpSyntaxGenerator\CSharpSyntaxGenerator.csproj : error NU3037: Package 'System.Numerics.Vectors 4.4.0' from source 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json': The repository primary signature validity period has expired. [D:\workspace\_work\1\s\src\NuGet\Microsoft.Net.Compilers.Toolset\Microsoft.Net.Compilers.Toolset.Package.csproj]

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs [hunk 3]
```diff
@@ -2070,6 +2070,38 @@ void NamedOptional(int x = 2)
...
+            {
+                Signature("C", "Main", ".method public hidebysig static System.Void Main() cil managed"),
+                Signature("C", "<Main>g__LocalFunc|0_0", ".method [System.Runtime.CompilerServices.CompilerGeneratedAttribute()] assembly hidebysig static System.Void <Main>g__LocalFunc|0_0([opt] System.Int32 a = 2) cil managed")
+            });
+        }
+
+        [Fact, WorkItem(53478, "https://github.com/dotnet/roslyn/issues/53478")]
+        public void OptionalParameterCodeGen_Reflection()
+        {
+            VerifyOutputInMain(@"void TestAction(int goo = 5) { }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs:2097]: >goo [](http://example.com/codeflow?start=53&length=3)

`i` perhaps

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs:290]: I had a few more overrides and assertions in mind but I felt like enumerating them was equal work to adding the implementations, so I went ahead and pushed a commit to your PR.

**Comment by RikkiGibson** [comment]
@AlekseyTs Did you have any further comments on this PR?

**Comment by Youssef1313** [comment]
@AlekseyTs Can you please take a look? Thanks!

**Comment by RikkiGibson** [comment]
Sorry, I synced with Aleksey offline about this PR and he said he had no further comments. Then I forgot to finish driving this PR 😅

**Comment by Youssef1313** [comment]
> Sorry, I synced with Aleksey offline about this PR and he said he had no further comments. Then I forgot to finish driving this PR 😅

No problem!

**Review by RikkiGibson — APPROVED** [review]

**Review by cston — APPROVED** [review]

**Comment by RikkiGibson** [comment]
Thanks for the contribution @Youssef1313!
