### PR TITLE
Include GetAwaiter() extension method namespace in AddImport suggestions

### LINKED ISSUE #29313: Don't get offered to "resolve using" for extension methods that provide awaiters
Unlike normal extension methods (such as LINQ), you don't get offered to resolve a using if it provides a `GetAwaiter` method:

``` C#
using System;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

internal class Program
{
    private static async Task Main(string[] args)
    {
        await TaskScheduler.Default; // <-- Expect to get offered to resolve using
    }
}

namespace Microsoft.VisualStudio.Threading
{
    public static class AwaitExtensions
    {
        public static CustomAwaiter GetAwaiter(this TaskScheduler scheduler)
        {
            return default(CustomAwaiter);
        }

        public struct CustomAwaiter : INotifyCompletion
        {

            public bool IsCompleted
            {
                get;
            }

            public void OnCompleted(Action action)
            {
            }

            public void GetResult()
            {
            }
        }
    }
}

```

Error:
```
Error	CS1061	'TaskScheduler' does not contain a definition for 'GetAwaiter' and no accessible extension method 'GetAwaiter' accepting a first argument of type 'TaskScheduler' could be found (are you missing a using directive or an assembly 
```

If I manually add the using, this code compiles.

### PR DESCRIPTION
**Pull request by Scott-Caldwell**
This PR expands the Add Import feature to include addition of a namespace that contains a `GetAwaiter()` extension method for an awaited expression.

image

Fixes #29313.

### CODE REVIEW

File: src/Features/CSharp/Portable/AddImport/CSharpAddImportFeatureService.cs [hunk 1]
```diff
@@ -225,6 +229,16 @@ private static SimpleNameSyntax GetLeftMostSimpleName(QualifiedNameSyntax qn)
             return semanticModel.GetTypeInfo(node).Type;
         }
 
+        protected override ITypeSymbol GetAwaitInfo(
+            SemanticModel semanticModel, SyntaxNode node, CancellationToken cancellationToken)
+        {
+            var @await = node.AncestorsAndSelf().OfType<AwaitExpressionSyntax>().First();
```
Comment (sharwell) [inline src/Features/CSharp/Portable/AddImport/CSharpAddImportFeatureService.cs]: ❓ Any reason to not use `node.FirstAncestorOrSelf<AwaitExpressionSyntax>()`?

💡 `var awaitExpression`

File: src/Features/CSharp/Portable/AddImport/CSharpAddImportFeatureService.cs [hunk 2]
```diff
@@ -132,6 +132,10 @@ protected override bool CanAddImport(SyntaxNode node, CancellationToken cancella
         protected override bool CanAddImportForDeconstruct(string diagnosticId, SyntaxNode node)
             => diagnosticId == CS8129;
 
+        protected override bool CanAddImportForGetAwaiter(string diagnosticId, SyntaxNode node) =>
+            diagnosticId == CS1061 &&
+            node.AncestorsAndSelf().Any(n => n is AwaitExpressionSyntax);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/AddImport/CSharpAddImportFeatureService.cs]: IDE style is => on the next line for methods.  thanks!

Comment (sharwell) [inline src/Features/CSharp/Portable/AddImport/CSharpAddImportFeatureService.cs]: 📝 See other discussion, but this subexpression might be better as `node.FirstAncestorOrSelf<AwaitExpressionSyntax>() != null`

File: src/Features/Core/Portable/AddImport/SymbolReferenceFinder.cs [hunk 3]
```diff
@@ -463,6 +464,28 @@ private async Task<ImmutableArray<SymbolReference>> GetReferencesForQueryPattern
...
+            {
+                searchScope.CancellationToken.ThrowIfCancellationRequested();
+
+                if (_owner.CanAddImportForGetAwaiter(_diagnosticId, _node))
+                {
+                    var type = _owner.GetAwaitInfo(_semanticModel, _node, searchScope.CancellationToken);
+                    if (type != null)
+                    {
+                        return await GetReferencesForExtensionMethodAsync(searchScope, "GetAwaiter", type,
+                            m => m.IsValidGetAwaiter()).ConfigureAwait(false);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/AddImport/SymbolReferenceFinder.cs]: any existing GetAwaiter you could use nameof on instead of hardcoding this string?

File: src/Features/VisualBasic/Portable/AddImport/VisualBasicAddImportFeatureService.vb [hunk 4]
```diff
@@ -208,6 +213,14 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.AddImport
             Return Nothing
         End Function
 
+        Protected Overrides Function GetAwaitInfo(semanticModel As SemanticModel, node As SyntaxNode, cancellationToken As CancellationToken) As ITypeSymbol
+            Dim await = node.AncestorsAndSelf().OfType(Of AwaitExpressionSyntax)().First()
```
Comment (sharwell) [inline src/Features/VisualBasic/Portable/AddImport/VisualBasicAddImportFeatureService.vb]: 📝 Discussions from above can apply here too

File: src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs [hunk 5]
```diff
@@ -915,6 +915,8 @@ public static bool IsAwaitableNonDynamic(this ISymbol symbol, SemanticModel sema
             return getAwaiters.Any(VerifyGetAwaiter);
         }
 
+        public static bool IsValidGetAwaiter(this IMethodSymbol symbol) => VerifyGetAwaiter(symbol);
+
         private static bool VerifyGetAwaiter(IMethodSymbol getAwaiter)
         {
             var returnType = getAwaiter.ReturnType;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs]: seems super strange that *neither* of these methods is actually verifying that the name is actually 'GetAwaiter'.

File: src/Features/CSharp/Portable/AddImport/CSharpAddImportFeatureService.cs (hunk 2 above)
Comment (Scott-Caldwell) [reply src/Features/CSharp/Portable/AddImport/CSharpAddImportFeatureService.cs]: I should've realized that... there was an example of exactly that on the line above. Haha. Thanks for catching that

File: src/Features/Core/Portable/AddImport/SymbolReferenceFinder.cs (hunk 3 above)
Comment (Scott-Caldwell) [reply src/Features/Core/Portable/AddImport/SymbolReferenceFinder.cs]: Good point, I should've looked harder. Looks like there's a perfectly useful `WellKnownMemberNames` class that I've been neglecting

File: src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs (hunk 5 above)
Comment (Scott-Caldwell) [reply src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs]: Really good point. I'll add that to the method I added since it's public

File: src/Features/CSharp/Portable/AddImport/CSharpAddImportFeatureService.cs (hunk 1 above)
Comment (Scott-Caldwell) [reply src/Features/CSharp/Portable/AddImport/CSharpAddImportFeatureService.cs]: Admittedly, I just took that line from the `GetQueryClauseInfo()` implementation below mine. Apologies, I should have realized they did the same thing and used your suggestion to begin with

File: src/Features/VisualBasic/Portable/AddImport/VisualBasicAddImportFeatureService.vb [hunk 6]
```diff
@@ -208,6 +213,14 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.AddImport
...
+
+            Dim expression = await.Expression
+
+            Return semanticModel.GetTypeInfo(expression).Type
+        End Function
```
[the remark this answers is not in the document]
Comment (Scott-Caldwell) [reply src/Features/VisualBasic/Portable/AddImport/VisualBasicAddImportFeatureService.vb]: Clever! That would clean things up

**Comment by Scott-Caldwell** [comment]
Thank you both for all of your guidance (and patience) as I become familiar with the Roslyn codebase! Your comments are always really helpful, and I feel like I've already learned a lot in the short time since I started contributing to this repo.

File: src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs [hunk 7]
```diff
@@ -540,5 +541,20 @@ private CodeAction TryCreateCodeAction(Document document, AddImportFixData fixDa
...
+            var innerExpression = syntaxFactsService.GetExpressionOfAwaitExpression(node);
+
+            return semanticModel.GetTypeInfo(innerExpression).Type;
+        }
+
+        protected bool AncestorOrSelfIsAwaitExpression(SyntaxNode node, ISyntaxFactsService syntaxFactsService)
+            => FirstAwaitExpressionAncestor(node, syntaxFactsService) != null;
+
+        private SyntaxNode FirstAwaitExpressionAncestor(SyntaxNode node, ISyntaxFactsService syntaxFactsService)
+            => node.FirstAncestorOrSelf<SyntaxNode>(n => syntaxFactsService.IsAwaitExpression(n));
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs]: Seems it won't be a problem. We can revisit if the type shows up as relevant during profiling, but since other methods allocate on the same path I'm not expecting a problem.

File: src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs [hunk 8]
```diff
@@ -540,5 +541,20 @@ private CodeAction TryCreateCodeAction(Document document, AddImportFixData fixDa
 
             throw ExceptionUtilities.Unreachable;
         }
+
+        protected ITypeSymbol GetAwaitInfo(SemanticModel semanticModel, SyntaxNode node, ISyntaxFactsService syntaxFactsService, CancellationToken cancellationToken)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs]: does this need to be protected?

**Comment by sharwell** [comment]
Yeah, it's a huge help in applications that use vs-threading. 🎉

File: src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs (hunk 8 above)
Comment (sharwell) [reply src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs]: Good call, looks like it doesn't 👍 

```suggestion
        private ITypeSymbol GetAwaitInfo(SemanticModel semanticModel, SyntaxNode node, ISyntaxFactsService syntaxFactsService, CancellationToken cancellationToken)
```

Comment (Scott-Caldwell) [reply src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs]: Makes sense, private works fine

File: src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs [hunk 9]
```diff
@@ -30,6 +30,7 @@ internal abstract partial class AbstractAddImportFeatureService<TSimpleNameSynta
         protected abstract bool CanAddImportForMethod(string diagnosticId, ISyntaxFactsService syntaxFacts, SyntaxNode node, out TSimpleNameSyntax nameNode);
         protected abstract bool CanAddImportForNamespace(string diagnosticId, SyntaxNode node, out TSimpleNameSyntax nameNode);
         protected abstract bool CanAddImportForDeconstruct(string diagnosticId, SyntaxNode node);
+        protected abstract bool CanAddImportForGetAwaiter(string diagnosticId, SyntaxNode node, ISyntaxFactsService syntaxFactsService);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs]: super nitpicky.  but the ordering here vs CanAddImportForMethod annoys me.  Up to you if you wantt to fix it :)

Comment (Scott-Caldwell) [reply src/Features/Core/Portable/AddImport/AbstractAddImportFeatureService.cs]: Would be nice for consistency. I'll make the change in a couple of hours when I'm free :)
