### PR TITLE
Fix ref safety of ref-struct IEnumerable collection expressions

### LINKED ISSUE #76374: Unexpected ref safety error reported when a collection expression is used to construct a ref struct with Add method
**Version Used**: main 2024-12-10

**Steps to Reproduce**:

```cs
using System.Collections;
class C
{
    R M()
    {
        var local = 1;
        return [local]; // error CS9203: A collection expression of type 'R' cannot be used in this context because it may be exposed outside of the current scope.
    }
}
ref struct R : IEnumerable
{
    public void Add(in int x) { }
    IEnumerator IEnumerable.GetEnumerator() => throw null;
}
```

**Expected Behavior**: Compiles successfully, the `in int x` parameter of the `Add` method cannot be captured into the ref struct. Replacing the collection expression with a collection initializer `new() { local };` also works fine. So does making the struct a non-ref struct. See also https://github.com/dotnet/roslyn/pull/76237#discussion_r1878652403.

**Actual Behavior**: Error is reported: "CS9203: A collection expression of type 'R' cannot be used in this context because it may be exposed outside of the current scope."

### LINKED ISSUE #81520: 'ref safety' analysis is wrong for collection expressions targeting ref-types that implement IEnumerable.
The compiler hard-codes in that a ref-struct collection expression that implements IEnumerable has 'local scope'.  This was hardcoded in because originally this was just an error (it used to not be legal to have a ref-struct implementing an interface).

For example, the following is legal:

```c#
ref struct R : IEnumerable
{
    public void Add(int x) { }

    // implementation of IEnumerable...
}
```

Now that that's legal we need to properly do the analysis here.  The analysis of `R r = [with(...), x, y, .. z]` is complex.  Basically,  it should be hte intersection of the ref-safety of hte call to the constructor that `with(...)` defers to, along with the ref-safety of all the `.Add` calls that are made for `.Add(x)`, `.Add(y)`, `foreach (var v in z) .Add(v)`.

This is challenging as the determination of what .Add methods are called is deferred till lowering.

### PR DESCRIPTION
**Pull request by jjonescz**
Fixes https://github.com/dotnet/roslyn/issues/81520.
Fixes https://github.com/dotnet/roslyn/issues/76374.
Related to https://github.com/dotnet/roslyn/issues/80750 and https://github.com/dotnet/csharplang/pull/10088.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@jjonescz In #76374 you state the following:

> the `in int x` parameter of the `Add` method cannot be captured into the ref struct.

However, you are not providing any explanation why is that the case. Could you please elaborate? #Closed

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 1]
```diff
@@ -4407,6 +4408,7 @@ internal SafeContext GetValEscape(BoundExpression expr)
                 case BoundKind.AwaitableValuePlaceholder:
                 case BoundKind.ValuePlaceholder:
                 case BoundKind.CollectionBuilderElementsPlaceholder:
+                case BoundKind.ObjectOrCollectionValuePlaceholder:
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:4421]: >case BoundKind.ObjectOrCollectionValuePlaceholder: [](http://example.com/codeflow?start=16&length=50)

It looks like this change can lead to an observable change for an object creation expression. Is this intentional? Is there a test that observes the difference?  #Closed

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 2]
```diff
@@ -4726,7 +4728,6 @@ internal SafeContext GetValEscape(BoundExpression expr)
                     return _localScopeDepth;
 
                 case BoundKind.ImplicitReceiver:
-                case BoundKind.ObjectOrCollectionValuePlaceholder:
                     // binder uses this as a placeholder when binding members inside an object initializer
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: >// binder uses this as a placeholder when binding members inside an object initializer [](http://example.com/codeflow?start=20&length=86)

It doesn't look like this comment is applicable to remaining ```case BoundKind.ImplicitReceiver:``` #Closed

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 3]
```diff
@@ -4407,6 +4408,7 @@ internal SafeContext GetValEscape(BoundExpression expr)
                 case BoundKind.AwaitableValuePlaceholder:
                 case BoundKind.ValuePlaceholder:
                 case BoundKind.CollectionBuilderElementsPlaceholder:
+                case BoundKind.ObjectOrCollectionValuePlaceholder:
                     return GetPlaceholderScope((BoundValuePlaceholderBase)expr);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:4422]: >GetPlaceholderScope [](http://example.com/codeflow?start=27&length=19)

Do we properly set up environment for this helper when placeholder is created for object creation scenarios? #Closed

**Comment by AlekseyTs** [comment]
Done with review pass (commit 20) #Closed

**Comment by jjonescz** [comment]
> > the `in int x` parameter of the `Add` method cannot be captured into the ref struct.
> 
> However, you are not providing any explanation why is that the case. Could you please elaborate?

Because the parameter has ref-escape-scope return-only by default:

```cs
ref struct R
{
    private ref readonly int _f;
    public void Add(in int x) { _f = ref x; } // error CS9079: Cannot ref-assign 'x' to '_f' because 'x' can only escape the current method through a return statement.
}
```

It would have to have the scope wider for it to work:

```cs
using System.Diagnostics.CodeAnalysis;

ref struct R
{
    private ref readonly int _f;
    public void Add([UnscopedRef] in int x) { _f = ref x; }
}
```

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 1 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:4421]: Yes, for example `RefEscapingTests.CollectionExpression_AddMethod_Spread` would fail on an assert (unhandled case `ObjectOrCollectionValuePlaceholder` in `GetValEscape` which is now called from `VisitCollectionExpression` through `CheckInvocationArgMixing`).

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:4421]: I am talking about an object creation expression, not a collection expression

Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:4421]: That's not reachable (and hence observable by tests) as far as I can tell, because ref safety analysis never calls `GetValEscape` on the placeholder inside a `BoundObjectCreationExpression`. The placeholder is used for receivers of implicit calls that the object creation is made of. And we shouldn't need a val escape of that - at most we call `GetInvocationEscapeToReceiver` which doesn't need the val escape of the receiver.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 3 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:4422]: I think the same response as above applies here too. This is unreachable for object creation expressions.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 21)

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs [hunk 4]
```diff
@@ -984,49 +984,57 @@ private void VisitObjectCreationExpressionBase(BoundObjectCreationExpressionBase
...
+            // back into the ref parameters of the constructor.
+            //
+            // At the moment this is only a hypothetical problem. Because the language 
+            // doesn't support ref field of ref struct mixing like this could not actually
+            // happen in practice. At the same time we want to error on this now so that 
+            // in a future when we do have ref field to ref struct this is not a breaking 
+            // change. Customers can respond to failures like this by putting scoped on
+            // such parameters in the constructor.
+            var escapeValues = ArrayBuilder<EscapeValue>.GetInstance();
+            var escapeFrom = initializerEscape;
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs]: non-blocking/nit: 'escapeFrom' local feels redundant now.

File: src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs [hunk 5]
```diff
@@ -1333,9 +1343,83 @@ private static ImmutableArray<BoundExpression> GetDeconstructionRightParts(Bound
...
+                    elementsScope = elementsScope.Intersect(GetInvocationEscapeToReceiver(
+                        MethodInvocationInfo.FromCollectionElementInitializer(colElement)));
+                }
+                else if (element is BoundExpression elementExpression)
+                {
+                    elementsScope = elementsScope.Intersect(GetValEscape(elementExpression));
+                }
+                else if (element is BoundCollectionExpressionSpreadElement spreadElement)
+                {
+                    elementsScope = elementsScope.Intersect(GetValEscape(spreadElement.Expression));
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/RefSafetyAnalysis.cs]: I might have missed something, but it seems like `tryGetValEscapeOfElement()` added to `Binder.ValueChecks.cs`, handles an additional case for this, when the IteratorBody contains BoundCollectionElementInitializer. i.e. it doesn't seem like this method would always calculate a correct `elementsScope` for that case.

Perhaps it would be useful to try and extract a helper like `GetCollectionExpressionElementValEscape`, and use it here, and then add an additional check for the spread-element case, to ensure we separately do a mixing check on an inner `Add()` invocation.

Also, I didn't see any tests in Emit3 or Semantic which fail when this statement is commented out.

**Review by RikkiGibson — APPROVED** [review]

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs [hunk 6]
```diff
@@ -4784,6 +4784,88 @@ public void Add({{attr}} in int x) { }
...
+                    {
+                        MySource source = default;
+                        MyCollection result = [..source];
+                        return result;
+                    }
+
+                    static MyCollection M1s()
+                    {
+                        MySource source = default;
+                        scoped MyCollection result = [..source];
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs]: Wasn't sure what marking the result scoped was meant to demonstrate. It feels like marking the source scoped and observing that things propagate in the expected way might be more meaningful.

**Comment by jjonescz** [comment]
@AlekseyTs @RikkiGibson for another look on the latest changes, thanks

**Comment by AlekseyTs** [comment]
> for another look on the latest changes, thanks

I'll let my previous sign-off stand if @RikkiGibson signs off on the changes

**Review by RikkiGibson — APPROVED** [review]
