### PR TITLE
Simplification should remove parentheses around the expression of an expression-bodied member

### LINKED ISSUE #12600: Remove Unnecessary Cast adds extra parentheses in arrow method
**Version Used**: 

Visual Studio "15" Preview 3

**Steps to Reproduce**:
1.  Add code
   
   ``` C#
   public object GetValue() => (object)new object();
   ```
2. Invoke "Remove Unnecessary Cast" on `(object)new object();`.

**Expected Behavior**:

``` C#
public object GetValue() => new object();
```

**Actual Behavior**:

``` C#
public object GetValue() => (new object());
```

Method body doesn't matter, also tried member accessing or method calling body.

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes #12600

Tagging @dotnet/roslyn-ide

### CODE REVIEW

File: src/EditorFeatures/Test2/Simplification/ParenthesisSimplificationTests.vb [hunk 1]
```diff
@@ -1190,6 +1190,58 @@ class Program
...
+
+            Dim expected =
+<code>
+class C
+{
+    object GetValue() => new object();
+}
+</code>
+
+            Await TestAsync(input, expected)
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Test2/Simplification/ParenthesisSimplificationTests.vb]: test lambda case?
