### PR TITLE
Unify error messages on extension methods omitted type arguments

### LINKED ISSUE #13617: Invalid generic extension call does not report error and then fail to emit module.
**Version Used**: 

VS2015 Update 3 with .NET Core Tools Preview 2

**Steps to Reproduce**:
1. Create a generic extension method which return `T` e.g. `public static T Foo<T>(this object obj) => default(T)`
2. Call it somewhere without specifying `T` and invoke any arbitrary member name, like `"abc".Foo<>().FooValue`
3. Compile.

**Expected Behavior**:

Compilation fail with proper error message.

**Actual Behavior**:

No typical compilation error reported but fail to build with error CS7038 : Fail to emit module

**Sample class**:

```
public static class FooExtensions
{
    public static T Foo<T>(this object obj) => default(T);
}

public class Class1
{
    public void Test()
    {
        var a = "a".Foo<>().Run();
        // the line below fail to compile as expected
        //var b = FooExtensions.Foo<>().Abc;
    }
}
```

https://dotnetfiddle.net/JvacT3

### PR DESCRIPTION
**Pull request by OmarTawfik**
This PR reverts #15718, and proposes a better way to fix #13617 (as suggested by @AlekseyTs).

The original behavior was:
1. The check for omitted type arguments was a specialized check for a code path that happens just when looking up instance methods, but never on extension methods.
2. Lookup was based on arity/number of type arguments (**1 in case if they're omitted**).
3. In case of methods with one type argument, lookup would succeed, and compiler would crash later during checking symbols.
4. In case of methods with more type arguments, binding would fail because it won't be able to find methods with correct arity.

#15718 proposed a check for omitted type arguments, which our report `ErrorCode.ERR_BadArity` if any (during step #2 above). With further testing, this error was:
- Inconsistent since compiler reports `ErrorCode.ERR_NoSuchMemberOrExtension` with other arities.
- Duplicate errors will occur in case of arity > 1.

This PR adds more tests, and fixes the original method by checking for omitted type arguments during binding. This will:
1. No more duplicate errors (using `ErrorCode.ERR_BadArity` was a bad call).
2. Make error messages consistent with the rest of how Roslyn reports extension methods errors.

### CODE REVIEW

**Comment by OmarTawfik** [comment]
@AlekseyTs @dotnet/roslyn-compiler

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 1]
```diff
@@ -5609,78 +5602,97 @@ private static void CombineExtensionMethodArguments(BoundExpression receiver, An
             var firstResult = new MethodGroupResolution();
             AnalyzedArguments actualArguments = null;
 
-            foreach (var scope in new ExtensionMethodScopes(this))
+            var expressionHasOmittedTypeArgs = false;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: I'd consider extracting the new block into a method.

File: src/Compilers/CSharp/Test/Semantic/Semantics/BindingTests.cs [hunk 2]
```diff
@@ -3420,27 +3420,72 @@ public void MissingTypeArgumentInGenericExtensionMethod()
...
-        var defaultB = FooExtensions.Foo<>(""b"");
+        var omittedArg0 = ""string literal"".ExtensionMethod0<>();
+        var omittedArg1 = ""string literal"".ExtensionMethod1<>();
+        var omittedArg2 = ""string literal"".ExtensionMethod2<>();
+
+        var moreArgs0 = ""string literal"".ExtensionMethod0<int>();
+        var moreArgs1 = ""string literal"".ExtensionMethod1<int, bool>();
+        var moreArgs2 = ""string literal"".ExtensionMethod2<int, bool, string>();
+
+        var lessArgs1 = ""string literal"".ExtenionMethod1();
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/BindingTests.cs]: Typo on this line and below. s/Extenion/Extension/

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 3]
```diff
@@ -5609,78 +5602,97 @@ private static void CombineExtensionMethodArguments(BoundExpression receiver, An
...
-                var diagnostics = DiagnosticBag.GetInstance();
-
-                this.PopulateExtensionMethodsFromSingleBinder(scope, methodGroup, expression, left, methodName, typeArguments, diagnostics);
+                var memberAccessSyntax = (MemberAccessExpressionSyntax)expression;
+                if (memberAccessSyntax.Name.Kind() == SyntaxKind.GenericName)
+                {
+                    var genericNameSyntax = (GenericNameSyntax)memberAccessSyntax.Name;
+                    if (genericNameSyntax.TypeArgumentList.Arguments.Any(SyntaxKind.OmittedTypeArgument))
+                    {
+                        expressionHasOmittedTypeArgs = true;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: >expressionHasOmittedTypeArgs = true; [](start = 24, length = 36)

Consider simply returning from here rather than increasing nesting of the code below.

File: src/Compilers/VisualBasic/Test/Semantic/Binding/BindingErrorTests.vb [hunk 4]
```diff
@@ -25979,15 +25979,39 @@ Imports System.Runtime.CompilerServices
...
+    Public Function ExtensionMethod2(Of T1, T2)(ByVal obj As Object)
+        Return GetType(T1)
+    End Function
 End Module
 
 Module Module1
     Sub Main()
-        Dim typeA As Type = "a".Foo()
-        Dim typeB As Type = "b".Foo()()
+        Dim omittedArg0 As Type = "string literal".ExtensionMethod0()()
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/Binding/BindingErrorTests.vb]: >() [](start = 67, length = 2)

Is the first ```()``` supposed to be an empty argument list? It should be ```(Of )``` then.

**Comment by AlekseyTs** [comment]
>         public void MissingTypeArgumentInGenericExtensionMethod()

Please add tests for delegate conversion scenarios vs. an invocation scenarios.

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/BindingTests.cs:3417 in 894cb8b. [](commit_id = 894cb8b507739a53b5cf0dcb0ae47faa7f1c326b, deletion_comment = False)

File: src/Compilers/CSharp/Test/Semantic/Semantics/BindingTests.cs [hunk 5]
```diff
@@ -3420,27 +3420,72 @@ public void MissingTypeArgumentInGenericExtensionMethod()
...
+        var exactArgs0 = ""string literal"".ExtensionMethod0();
+        var exactArgs1 = ""string literal"".ExtensionMethod1<int>();
+        var exactArgs2 = ""string literal"".ExtensionMethod2<int, bool>();
     }
 }
 ";
             var compilation = CreateCompilationWithMscorlibAndSystemCore(source);
 
             compilation.VerifyDiagnostics(
-                // (11,24): error CS0305: Using the generic method group 'Foo' requires 1 type arguments
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/BindingTests.cs]: >// (11,24): error CS0305: Using the generic method group 'Foo' requires 1 type arguments [](start = 16, length = 88)

I think we should keep this error. My recommendation would be to tot change implementation and simply add more tests.

**Comment by OmarTawfik** [comment]
PR updated with test comments.

**Comment by AlekseyTs** [comment]
Please add tests for delegate conversion scenarios for C#.

**Comment by AlekseyTs** [comment]
LGTM
