### PR TITLE
Report an error for an initialization of a ref-returning property as part of an object initializer inside an expression tree.

### LINKED ISSUE #49617: Crash when assigning ref property in compiler-generated expression tree
**Version Used**: Microsoft (R) Visual C# Compiler version 3.8.0-5.20519.18 (4c195c3a) from Dotnet SDK 5.0.100.

**Steps to Reproduce**:

1. Define a class with a ref property.
2. Define a method that takes an Expression.
3. Call the method using a lambda expression that assigns to the ref property.

**Expected Behavior**:

The code should compile or return a sensible compile error if it is not possible to represent this property assignment using the current expression tree model.

**Actual Behavior**:

The compiler crashes.

**Additional Info**:

I found this yesterday using the same SDK but compiling for net480 (attached repro is for net5.0) from within Visual Studio. In that case, the process exits with code COR_E_FAILFAST and the exception detail is sent to the Windows event log instead of the console like when using `dotnet build`.

I've uploaded a small repro at https://github.com/mdonoughe/ref-prop-crash .

**Output**:

```
Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error : Process terminated. System.NullReferenceException: Object reference not set to an instance of an object. [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.SyntheticBoundNodeFactory.MethodInfo(MethodSymbol method) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.InitializerMemberSetter(Symbol symbol) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitInitializer(BoundExpression node, InitializerKind& kind) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitObjectCreationContinued(BoundExpression creation, BoundExpression initializerExpressionOpt) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitObjectCreationExpression(BoundObjectCreationExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitExpressionWithoutStackGuard(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitInternal(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.Visit(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.TranslateLambdaBody(BoundBlock block) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitLambdaInternal(BoundLambda node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.RewriteLambda(BoundLambda node, TypeCompilationState compilationState, TypeMap typeMap, Int32 recursionDepth, DiagnosticBag diagnostics) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.RewriteLambdaConversion(BoundLambda node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.VisitConversion(BoundConversion conversion) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundConversion.Accept(BoundTreeVisitor visitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(BoundNode node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.DoVisitList[T](ImmutableArray`1 list) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.MethodToClassRewriter.VisitCall(BoundCall node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.VisitCall(BoundCall node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(BoundTreeVisitor visitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(BoundNode node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitExpressionStatement(BoundExpressionStatement node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement.Accept(BoundTreeVisitor visitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(BoundNode node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitSequencePoint(BoundSequencePoint node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundSequencePoint.Accept(BoundTreeVisitor visitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.RewriteBlock(BoundBlock node, ArrayBuilder`1 prologue, ArrayBuilder`1 newLocals) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.VisitBlock(BoundBlock node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(BoundNode node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.Rewrite(BoundStatement loweredBody, NamedTypeSymbol thisType, ParameterSymbol thisParameter, MethodSymbol method, Int32 methodOrdinal, MethodSymbol substitutedSourceMethod, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, VariableSlotAllocator slotAllocatorOpt, TypeCompilationState compilationState, DiagnosticBag diagnostics, HashSet`1 assignLocals) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.LowerBodyOrInitializer(MethodSymbol method, Int32 methodOrdinal, BoundStatement body, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState, Boolean instrumentForDynamicAnalysis, DebugDocumentProvider debugDocumentProvider, ImmutableArray`1& dynamicAnalysisSpans, DiagnosticBag diagnostics, VariableSlotAllocator& lazyVariableSlotAllocator, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, StateMachineTypeSymbol& stateMachineTypeOpt) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass22_0.<CompileNamedTypeAsync>b__0() [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at System.Environment.FailFast(System.String, System.Exception) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.FatalError.Report(System.Exception, System.Action`1<System.Exception>) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.FatalError.ReportUnlessCanceled(System.Exception) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass22_0.<CompileNamedTypeAsync>b__0() [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.SyntheticBoundNodeFactory.MethodInfo(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.InitializerMemberSetter(Microsoft.CodeAnalysis.CSharp.Symbol) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitInitializer(Microsoft.CodeAnalysis.CSharp.BoundExpression, InitializerKind ByRef) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitObjectCreationContinued(Microsoft.CodeAnalysis.CSharp.BoundExpression, Microsoft.CodeAnalysis.CSharp.BoundExpression) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitObjectCreationExpression(Microsoft.CodeAnalysis.CSharp.BoundObjectCreationExpression) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitInternal(Microsoft.CodeAnalysis.CSharp.BoundExpression) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.Visit(Microsoft.CodeAnalysis.CSharp.BoundExpression) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.TranslateLambdaBody(Microsoft.CodeAnalysis.CSharp.BoundBlock) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitLambdaInternal(Microsoft.CodeAnalysis.CSharp.BoundLambda) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.RewriteLambda(Microsoft.CodeAnalysis.CSharp.BoundLambda, Microsoft.CodeAnalysis.CSharp.TypeCompilationState, Microsoft.CodeAnalysis.CSharp.Symbols.TypeMap, Int32, Microsoft.CodeAnalysis.DiagnosticBag) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.RewriteLambdaConversion(Microsoft.CodeAnalysis.CSharp.BoundLambda) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.VisitConversion(Microsoft.CodeAnalysis.CSharp.BoundConversion) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundConversion.Accept(Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32 ByRef, Microsoft.CodeAnalysis.CSharp.BoundExpression) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.DoVisitList[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Immutable.ImmutableArray`1<System.__Canon>) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.MethodToClassRewriter.VisitCall(Microsoft.CodeAnalysis.CSharp.BoundCall) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.VisitCall(Microsoft.CodeAnalysis.CSharp.BoundCall) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32 ByRef, Microsoft.CodeAnalysis.CSharp.BoundExpression) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitExpressionStatement(Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement.Accept(Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitSequencePoint(Microsoft.CodeAnalysis.CSharp.BoundSequencePoint) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundSequencePoint.Accept(Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.RewriteBlock(Microsoft.CodeAnalysis.CSharp.BoundBlock, Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.CSharp.BoundExpression>, Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.CSharp.Symbols.LocalSymbol>) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.VisitBlock(Microsoft.CodeAnalysis.CSharp.BoundBlock) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.Rewrite(Microsoft.CodeAnalysis.CSharp.BoundStatement, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.ParameterSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Int32, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.CodeGen.LambdaDebugInfo>, Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.CodeGen.ClosureDebugInfo>, Microsoft.CodeAnalysis.CodeGen.VariableSlotAllocator, Microsoft.CodeAnalysis.CSharp.TypeCompilationState, Microsoft.CodeAnalysis.DiagnosticBag, System.Collections.Generic.HashSet`1<Microsoft.CodeAnalysis.CSharp.Symbols.LocalSymbol>) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.LowerBodyOrInitializer(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Int32, Microsoft.CodeAnalysis.CSharp.BoundStatement, Microsoft.CodeAnalysis.CSharp.SynthesizedSubmissionFields, Microsoft.CodeAnalysis.CSharp.TypeCompilationState, Boolean, Microsoft.CodeAnalysis.CodeGen.DebugDocumentProvider, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CodeGen.SourceSpan> ByRef, Microsoft.CodeAnalysis.DiagnosticBag, Microsoft.CodeAnalysis.CodeGen.VariableSlotAllocator ByRef, Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.CodeGen.LambdaDebugInfo>, Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.CodeGen.ClosureDebugInfo>, Microsoft.CodeAnalysis.CSharp.StateMachineTypeSymbol ByRef) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Int32, ProcessedFieldInitializers ByRef, Microsoft.CodeAnalysis.CSharp.SynthesizedSubmissionFields, Microsoft.CodeAnalysis.CSharp.TypeCompilationState) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass22_0.<CompileNamedTypeAsync>b__0() [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Roslyn.Utilities.UICultureUtilities+<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at System.Threading.Tasks.Task.InnerInvoke() [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at System.Threading.Tasks.Task+<>c.<.cctor>b__277_0(System.Object) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at System.Threading.ThreadPoolWorkQueue.Dispatch() [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error : System.NullReferenceException: Object reference not set to an instance of an object. [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.SyntheticBoundNodeFactory.MethodInfo(MethodSymbol method) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.InitializerMemberSetter(Symbol symbol) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitInitializer(BoundExpression node, InitializerKind& kind) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitObjectCreationContinued(BoundExpression creation, BoundExpression initializerExpressionOpt) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitObjectCreationExpression(BoundObjectCreationExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitExpressionWithoutStackGuard(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitInternal(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.Visit(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.TranslateLambdaBody(BoundBlock block) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitLambdaInternal(BoundLambda node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.RewriteLambda(BoundLambda node, TypeCompilationState compilationState, TypeMap typeMap, Int32 recursionDepth, DiagnosticBag diagnostics) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.RewriteLambdaConversion(BoundLambda node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.VisitConversion(BoundConversion conversion) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundConversion.Accept(BoundTreeVisitor visitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(BoundNode node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.DoVisitList[T](ImmutableArray`1 list) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.MethodToClassRewriter.VisitCall(BoundCall node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.VisitCall(BoundCall node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(BoundTreeVisitor visitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(BoundNode node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitExpressionStatement(BoundExpressionStatement node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement.Accept(BoundTreeVisitor visitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(BoundNode node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitSequencePoint(BoundSequencePoint node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundSequencePoint.Accept(BoundTreeVisitor visitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.RewriteBlock(BoundBlock node, ArrayBuilder`1 prologue, ArrayBuilder`1 newLocals) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.VisitBlock(BoundBlock node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(BoundNode node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.Rewrite(BoundStatement loweredBody, NamedTypeSymbol thisType, ParameterSymbol thisParameter, MethodSymbol method, Int32 methodOrdinal, MethodSymbol substitutedSourceMethod, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, VariableSlotAllocator slotAllocatorOpt, TypeCompilationState compilationState, DiagnosticBag diagnostics, HashSet`1 assignLocals) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.LowerBodyOrInitializer(MethodSymbol method, Int32 methodOrdinal, BoundStatement body, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState, Boolean instrumentForDynamicAnalysis, DebugDocumentProvider debugDocumentProvider, ImmutableArray`1& dynamicAnalysisSpans, DiagnosticBag diagnostics, VariableSlotAllocator& lazyVariableSlotAllocator, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, StateMachineTypeSymbol& stateMachineTypeOpt) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass22_0.<CompileNamedTypeAsync>b__0() [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]

Build FAILED.

C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error : Process terminated. System.NullReferenceException: Object reference not set to an instance of an object. [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.SyntheticBoundNodeFactory.MethodInfo(MethodSymbol method) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.InitializerMemberSetter(Symbol symbol) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitInitializer(BoundExpression node, InitializerKind& kind) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitObjectCreationContinued(BoundExpression creation, BoundExpression initializerExpressionOpt) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitObjectCreationExpression(BoundObjectCreationExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitExpressionWithoutStackGuard(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitInternal(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.Visit(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.TranslateLambdaBody(BoundBlock block) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitLambdaInternal(BoundLambda node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.RewriteLambda(BoundLambda node, TypeCompilationState compilationState, TypeMap typeMap, Int32 recursionDepth, DiagnosticBag diagnostics) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.RewriteLambdaConversion(BoundLambda node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.VisitConversion(BoundConversion conversion) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundConversion.Accept(BoundTreeVisitor visitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(BoundNode node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.DoVisitList[T](ImmutableArray`1 list) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.MethodToClassRewriter.VisitCall(BoundCall node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.VisitCall(BoundCall node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(BoundTreeVisitor visitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(BoundNode node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitExpressionStatement(BoundExpressionStatement node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement.Accept(BoundTreeVisitor visitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(BoundNode node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitSequencePoint(BoundSequencePoint node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundSequencePoint.Accept(BoundTreeVisitor visitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.RewriteBlock(BoundBlock node, ArrayBuilder`1 prologue, ArrayBuilder`1 newLocals) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.VisitBlock(BoundBlock node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(BoundNode node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.Rewrite(BoundStatement loweredBody, NamedTypeSymbol thisType, ParameterSymbol thisParameter, MethodSymbol method, Int32 methodOrdinal, MethodSymbol substitutedSourceMethod, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, VariableSlotAllocator slotAllocatorOpt, TypeCompilationState compilationState, DiagnosticBag diagnostics, HashSet`1 assignLocals) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.LowerBodyOrInitializer(MethodSymbol method, Int32 methodOrdinal, BoundStatement body, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState, Boolean instrumentForDynamicAnalysis, DebugDocumentProvider debugDocumentProvider, ImmutableArray`1& dynamicAnalysisSpans, DiagnosticBag diagnostics, VariableSlotAllocator& lazyVariableSlotAllocator, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, StateMachineTypeSymbol& stateMachineTypeOpt) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass22_0.<CompileNamedTypeAsync>b__0() [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at System.Environment.FailFast(System.String, System.Exception) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.FatalError.Report(System.Exception, System.Action`1<System.Exception>) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.FatalError.ReportUnlessCanceled(System.Exception) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass22_0.<CompileNamedTypeAsync>b__0() [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.SyntheticBoundNodeFactory.MethodInfo(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.InitializerMemberSetter(Microsoft.CodeAnalysis.CSharp.Symbol) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitInitializer(Microsoft.CodeAnalysis.CSharp.BoundExpression, InitializerKind ByRef) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitObjectCreationContinued(Microsoft.CodeAnalysis.CSharp.BoundExpression, Microsoft.CodeAnalysis.CSharp.BoundExpression) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitObjectCreationExpression(Microsoft.CodeAnalysis.CSharp.BoundObjectCreationExpression) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitInternal(Microsoft.CodeAnalysis.CSharp.BoundExpression) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.Visit(Microsoft.CodeAnalysis.CSharp.BoundExpression) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.TranslateLambdaBody(Microsoft.CodeAnalysis.CSharp.BoundBlock) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitLambdaInternal(Microsoft.CodeAnalysis.CSharp.BoundLambda) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.RewriteLambda(Microsoft.CodeAnalysis.CSharp.BoundLambda, Microsoft.CodeAnalysis.CSharp.TypeCompilationState, Microsoft.CodeAnalysis.CSharp.Symbols.TypeMap, Int32, Microsoft.CodeAnalysis.DiagnosticBag) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.RewriteLambdaConversion(Microsoft.CodeAnalysis.CSharp.BoundLambda) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.VisitConversion(Microsoft.CodeAnalysis.CSharp.BoundConversion) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundConversion.Accept(Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32 ByRef, Microsoft.CodeAnalysis.CSharp.BoundExpression) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.DoVisitList[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Immutable.ImmutableArray`1<System.__Canon>) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.MethodToClassRewriter.VisitCall(Microsoft.CodeAnalysis.CSharp.BoundCall) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.VisitCall(Microsoft.CodeAnalysis.CSharp.BoundCall) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Microsoft.CodeAnalysis.CSharp.BoundExpression) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32 ByRef, Microsoft.CodeAnalysis.CSharp.BoundExpression) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitExpressionStatement(Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement.Accept(Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitSequencePoint(Microsoft.CodeAnalysis.CSharp.BoundSequencePoint) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundSequencePoint.Accept(Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.RewriteBlock(Microsoft.CodeAnalysis.CSharp.BoundBlock, Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.CSharp.BoundExpression>, Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.CSharp.Symbols.LocalSymbol>) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.VisitBlock(Microsoft.CodeAnalysis.CSharp.BoundBlock) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(Microsoft.CodeAnalysis.CSharp.BoundNode) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.Rewrite(Microsoft.CodeAnalysis.CSharp.BoundStatement, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.ParameterSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Int32, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.CodeGen.LambdaDebugInfo>, Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.CodeGen.ClosureDebugInfo>, Microsoft.CodeAnalysis.CodeGen.VariableSlotAllocator, Microsoft.CodeAnalysis.CSharp.TypeCompilationState, Microsoft.CodeAnalysis.DiagnosticBag, System.Collections.Generic.HashSet`1<Microsoft.CodeAnalysis.CSharp.Symbols.LocalSymbol>) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.LowerBodyOrInitializer(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Int32, Microsoft.CodeAnalysis.CSharp.BoundStatement, Microsoft.CodeAnalysis.CSharp.SynthesizedSubmissionFields, Microsoft.CodeAnalysis.CSharp.TypeCompilationState, Boolean, Microsoft.CodeAnalysis.CodeGen.DebugDocumentProvider, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CodeGen.SourceSpan> ByRef, Microsoft.CodeAnalysis.DiagnosticBag, Microsoft.CodeAnalysis.CodeGen.VariableSlotAllocator ByRef, Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.CodeGen.LambdaDebugInfo>, Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder`1<Microsoft.CodeAnalysis.CodeGen.ClosureDebugInfo>, Microsoft.CodeAnalysis.CSharp.StateMachineTypeSymbol ByRef) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Int32, ProcessedFieldInitializers ByRef, Microsoft.CodeAnalysis.CSharp.SynthesizedSubmissionFields, Microsoft.CodeAnalysis.CSharp.TypeCompilationState) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass22_0.<CompileNamedTypeAsync>b__0() [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Roslyn.Utilities.UICultureUtilities+<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at System.Threading.Tasks.Task.InnerInvoke() [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at System.Threading.Tasks.Task+<>c.<.cctor>b__277_0(System.Object) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at System.Threading.ThreadPoolWorkQueue.Dispatch() [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error : System.NullReferenceException: Object reference not set to an instance of an object. [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.SyntheticBoundNodeFactory.MethodInfo(MethodSymbol method) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.InitializerMemberSetter(Symbol symbol) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitInitializer(BoundExpression node, InitializerKind& kind) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitObjectCreationContinued(BoundExpression creation, BoundExpression initializerExpressionOpt) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitObjectCreationExpression(BoundObjectCreationExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitExpressionWithoutStackGuard(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitInternal(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.Visit(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.TranslateLambdaBody(BoundBlock block) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitLambdaInternal(BoundLambda node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.RewriteLambda(BoundLambda node, TypeCompilationState compilationState, TypeMap typeMap, Int32 recursionDepth, DiagnosticBag diagnostics) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.RewriteLambdaConversion(BoundLambda node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.VisitConversion(BoundConversion conversion) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundConversion.Accept(BoundTreeVisitor visitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(BoundNode node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.DoVisitList[T](ImmutableArray`1 list) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.MethodToClassRewriter.VisitCall(BoundCall node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.VisitCall(BoundCall node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(BoundTreeVisitor visitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(BoundNode node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitExpressionStatement(BoundExpressionStatement node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement.Accept(BoundTreeVisitor visitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(BoundNode node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitSequencePoint(BoundSequencePoint node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundSequencePoint.Accept(BoundTreeVisitor visitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.RewriteBlock(BoundBlock node, ArrayBuilder`1 prologue, ArrayBuilder`1 newLocals) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.VisitBlock(BoundBlock node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(BoundNode node) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.ClosureConversion.Rewrite(BoundStatement loweredBody, NamedTypeSymbol thisType, ParameterSymbol thisParameter, MethodSymbol method, Int32 methodOrdinal, MethodSymbol substitutedSourceMethod, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, VariableSlotAllocator slotAllocatorOpt, TypeCompilationState compilationState, DiagnosticBag diagnostics, HashSet`1 assignLocals) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.LowerBodyOrInitializer(MethodSymbol method, Int32 methodOrdinal, BoundStatement body, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState, Boolean instrumentForDynamicAnalysis, DebugDocumentProvider debugDocumentProvider, ImmutableArray`1& dynamicAnalysisSpans, DiagnosticBag diagnostics, VariableSlotAllocator& lazyVariableSlotAllocator, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, StateMachineTypeSymbol& stateMachineTypeOpt) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
C:\Program Files\dotnet\sdk\5.0.100\Roslyn\Microsoft.CSharp.Core.targets(71,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass22_0.<CompileNamedTypeAsync>b__0() [C:\Users\mdono\Documents\GitHub\ref-prop-crash\RefPropCrash.csproj]
    0 Warning(s)
    133 Error(s)

Time Elapsed 00:00:05.55
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #49617.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs [hunk 1]
```diff
@@ -409,6 +409,11 @@ public override BoundNode VisitObjectInitializerMember(BoundObjectInitializerMem
                 Error(ErrorCode.ERR_DictionaryInitializerInExpressionTree, node);
             }
 
+            if (node.MemberSymbol is PropertySymbol property)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs:412]: Is there a reason that this doesn't go through `VisitPropertyAccess`? I'm curious if there are other places in the compiler where `VisitPropertyAccess` could be missing a property in this case similar to what was missed here. I did a quick audit of all the `VisitPropertyAccess` and checked to make sure that the corresponding logic also existed in `VisitObjectInitializer`. Seems like we're okay but worries me a bit we could have future holes here.

**Review by jaredpar — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs:412]: > Is there a reason that this doesn't go through VisitPropertyAccess? 

In this scenario there is no BoundPropertyAccess in the tree.

---
In reply to: [533889046](https://github.com/dotnet/roslyn/pull/49719#discussion_r533889046) [](ancestors = 533889046)

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 1)
