### PR TITLE
The default label is considered reachable in a traditional switch statement

### LINKED ISSUE #33783: Different handling of unreachable code and default fallthrough in switch block
**Version Used**: 
Visual Studio 2019 RC (csc.exe 3.0.19.12206 (ec366687))

**Steps to Reproduce**:
Compile this code (I used `csc.exe Class1.cs -target:library -langversion:7.3`):

    int Foo(bool a)
    {
        switch (a)
        {
            case true:
                return 1;
            case false:
                return 2;
            default:
                return 3;
        }
    }

**Expected Behavior**:
No warnings.

**Actual Behavior**:
You'll get warning CS0162: Unreachable code detected. This wasn't the case with Visual Studio 2017 (csc.exe 2.10.0.0 (b9fb1610)). This warning is of course promoted to an error if warnings as errors is enabled, which is how I found it. Is this a problem? I realize that analysis may have improved.

However, 2019 then suggests replacing it with:

    int Foo(bool a)
    {
        switch (a)
        {
            case true:
                return 1;
            case false:
                return 2;
            default:
        }
    }

Which now compiles without warnings. This code *fails* with Visual Studio 2017:

    CS8070: Control cannot fall out of switch from final case label ('default')
    CS0161: 'Class1.Foo(bool)': not all code paths return a value

But I am using langversion 7.3 for both. Shouldn't the same language version mean that it should compile with the same result?

### PR DESCRIPTION
**Pull request by gafter**
This fixes a compatibility bug (the new compiler complains about unreachable code, but if you remove it the old compiler complains about a switch fall-through).

Fixes #33783

### CODE REVIEW

**Comment by gafter** [comment]
@agocke @dotnet/roslyn-compiler May I please have a couple of reviews of this small compatibility bug fix?

File: src/Compilers/CSharp/Test/Semantic/Semantics/SwitchTests.cs [hunk 1]
```diff
@@ -2918,6 +2918,35 @@ public static void Main()
...
+        }
+    }
+}";
+            CreateCompilation(text, parseOptions: TestOptions.Regular6).VerifyDiagnostics();
+            CreateCompilation(text, parseOptions: TestOptions.Regular7_3).VerifyDiagnostics();
+            CreateCompilation(text).VerifyDiagnostics(
+                // (14,17): warning CS0162: Unreachable code detected
+                //                 break; //1
+                Diagnostic(ErrorCode.WRN_UnreachableCode, "break").WithLocation(14, 17));
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/SwitchTests.cs]: >} [](start = 8, length = 1)

Consider adding a similar test when switching on a constant.

File: src/Compilers/CSharp/Test/Semantic/Semantics/SwitchTests.cs [hunk 2]
```diff
@@ -2918,6 +2918,35 @@ public static void Main()
...
+    public static void Main()
+    {
+        bool b = false;
+        switch (b)
+        {
+            case true:
+                break;
+            case false:
+                break;
+            default:
```
Comment (agocke) [inline src/Compilers/CSharp/Test/Semantic/Semantics/SwitchTests.cs]: I'd add tests for `default when ...` and `default` in a switch statement with type tests

File: src/Compilers/CSharp/Test/Semantic/Semantics/SwitchTests.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/SwitchTests.cs]: We already have such tests.

File: src/Compilers/CSharp/Test/Semantic/Semantics/SwitchTests.cs (hunk 2 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/SwitchTests.cs]: There are no backward compat issues for a switch in which a when clause or type tests appears.  We have tests for those scenarios.

`default when ...` is a syntax error.
