### PR TITLE
Preserve trivia for 'Use Collection Expression' fixer in more cases

### LINKED ISSUE #73740: "Use collection expression" code fix drops comments in certain cases
**Version Used**: `Compiler version: 4.10.0-3.24230.3` (abc35d6d)

**Steps to Reproduce**:

[sharplab](https://sharplab.io/#v2:EYLgtghglgdgPrALgbQLprQAgpgvJmAUwHdMkN1UBYAKAG9bMmCSyYVLMB6LsAT0wBjAPZgwhdo2YMazOS1LlUmOpgCMAJgDMAGkwAWAKwA2TAF8pTMzssK2HLD35DR49pg22Z85kUXssVQB2AA4ATj01AAY1c1sLGjMAbiA)
```csharp
int[][][] a = new int[][][]
{
    new int[][] //my comment
    {
        new int[] { 123, 456 }
    },
    new int[][] //my comment 2
    {
        new int[] { 789, 101 }
    }
};
```

**Diagnostic Id**: IDE0300

**Expected Behavior**:
Comments are preserved.

**Actual Behavior**:
Comments are lost when fix is applied.

For the above case its trivial to replace the comments, however for large lookups the comments can help add a lot of context and its very tedious to manually perform changes to manually preserve the comments.

### PR DESCRIPTION
**Pull request by JakeYallop**
Fixes #73740.

See tests for some of the corner cases that are now better than before, but not perfect. I opted not to fix all of them due to the fact that fixing would involve complicating what is already a very complicated fixer. See comments for specific examples and what additional improvements are left on the table.

It does fix the original problem raised in the issue, which in my (definitely biased) opinion, should be a more common case.

### CODE REVIEW

File: src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs [hunk 1]
```diff
@@ -5348,4 +5348,355 @@ private void Test1(dynamic obj, int?[] args)
...
+                {
+                    int[] i = [|[|new|][]|] //Test
+                    { 1, 2, 3 };
+                }
+                """,
+            FixedCode = """
+                class C
+                {
+                    int[] i =
+                    //Test
```
Comment (JakeYallop) [inline src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs:5368]: This extra newline is caused by the elastic marker here: https://github.com/dotnet/roslyn/blob/540092f62346918037f444927c8cdef038519157/src/Analyzers/CSharp/Analyzers/UseCollectionExpression/UseCollectionExpressionHelpers.cs#L729-L733

This does a lot of heavy lifting in many other tests. Removing it would mean manually cleaning up a lot of different cases that are not currently catered for.

File: src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs [hunk 2]
```diff
@@ -5348,4 +5348,355 @@ private void Test1(dynamic obj, int?[] args)
...
+                class C
+                {
+                    int[] i = [|[|new|] int[]|]
+                    { };
+                }
+                """,
+            FixedCode = """
+                class C
+                {
+                    int[] i =
```
Comment (JakeYallop) [inline src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs:5524]: There is extra space here after the `=`. I wasn't too sure how to approach fixing this, as the whitespace trivia is part of the  equals expression and not the initializer, as in most other cases.

File: src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs [hunk 3]
```diff
@@ -5348,4 +5348,355 @@ private void Test1(dynamic obj, int?[] args)
...
+                {
+                    int[] i = [|[|new|][]|] /* Test */
+                    { 1, 2, 3 };
+                }
+                """,
+            FixedCode = """
+                class C
+                {
+                    int[] i =
+                    /* Test */
```
Comment (JakeYallop) [inline src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs:5548]: Same case as https://github.com/dotnet/roslyn/pull/74052/files#r1645054160

**Comment by CyrusNajmabadi** [comment]
I will be able to review this later this week. Please feel free to ping on Monday if I haven't. Thanks!

**Comment by JakeYallop** [comment]
@CyrusNajmabadi, pinging as requested

File: src/Analyzers/CSharp/Analyzers/UseCollectionExpression/UseCollectionExpressionHelpers.cs [hunk 4]
```diff
@@ -733,11 +733,20 @@ or ImplicitStackAllocArrayCreationExpressionSyntax
                 .WithPrependedLeadingTrivia(ElasticMarker);
     }
 
+    private static bool HasStructuredTriviaBetweenCloseTokenAndInitializer(InitializerExpressionSyntax initializer)
+    {
+        static bool IsComment(SyntaxTrivia trivia) => trivia.IsKind(SyntaxKind.SingleLineCommentTrivia) || trivia.IsKind(SyntaxKind.MultiLineCommentTrivia);
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/UseCollectionExpression/UseCollectionExpressionHelpers.cs:738]: we place local helper functions at the end of the method.

File: src/Analyzers/CSharp/Analyzers/UseCollectionExpression/UseCollectionExpressionHelpers.cs [hunk 5]
```diff
@@ -733,11 +733,20 @@ or ImplicitStackAllocArrayCreationExpressionSyntax
                 .WithPrependedLeadingTrivia(ElasticMarker);
     }
 
+    private static bool HasStructuredTriviaBetweenCloseTokenAndInitializer(InitializerExpressionSyntax initializer)
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/UseCollectionExpression/UseCollectionExpressionHelpers.cs:736]: note: this name is not correct.   'structured trivia' means something specific in Roslyn.  Specifically it is things like doc-comments or pp-directives.  Trivia that have parse trees under them themselves.  This function is asking "is there single or multiline trivia before this node"

File: src/Analyzers/CSharp/Analyzers/UseCollectionExpression/UseCollectionExpressionHelpers.cs [hunk 6]
```diff
@@ -733,11 +733,20 @@ or ImplicitStackAllocArrayCreationExpressionSyntax
...
+    {
+        static bool IsComment(SyntaxTrivia trivia) => trivia.IsKind(SyntaxKind.SingleLineCommentTrivia) || trivia.IsKind(SyntaxKind.MultiLineCommentTrivia);
+        return initializer.OpenBraceToken.GetPreviousToken().TrailingTrivia.Any(IsComment);
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/UseCollectionExpression/UseCollectionExpressionHelpers.cs:739]: we have a utility method for this already: IsSingleOrMultiLineComment.  I would use that, remove this method, and just inline this code at the callsites.

File: src/Analyzers/CSharp/Analyzers/UseCollectionExpression/UseCollectionExpressionHelpers.cs [hunk 7]
```diff
@@ -733,11 +733,20 @@ or ImplicitStackAllocArrayCreationExpressionSyntax
...
+    }
+
     private static bool ShouldReplaceExistingExpressionEntirely(
         SourceText sourceText,
         InitializerExpressionSyntax initializer,
         bool newCollectionIsSingleLine)
     {
+        if (HasStructuredTriviaBetweenCloseTokenAndInitializer(initializer))
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/UseCollectionExpression/UseCollectionExpressionHelpers.cs:747]: the method name is also super confusing as it references the CloseToken, but is actually checking the OpenBrace of hte initializer.

File: src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs [hunk 8]
```diff
@@ -5348,4 +5348,355 @@ private void Test1(dynamic obj, int?[] args)
             LanguageVersion = LanguageVersion.CSharp12,
         }.RunAsync();
     }
+
+    [Fact]
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs:5352]:
```suggestion
    [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/73740")]
```

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxTriviaListExtensions.cs [hunk 9]
```diff
@@ -42,6 +42,9 @@ internal static class SyntaxTriviaListExtensions
     public static IEnumerable<SyntaxTrivia> SkipInitialWhitespace(this SyntaxTriviaList triviaList)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Extensions/SyntaxTriviaListExtensions.cs:42]: can you remove this extension?

**Comment by CyrusNajmabadi** [comment]
Done with pass.  Thanks for this PR.  Looking very good.  Just needs some small bits of cleanup to proceed.

**Comment by JakeYallop** [comment]
This is ready for review again. Test failure looks unrelated.

File: src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpCollectionExpressionRewriter.cs [hunk 10]
```diff
@@ -171,7 +171,41 @@ CollectionExpressionSyntax CreateCollectionExpressionWithoutExistingElements()
...
+                // ]
+                var shouldIncludeAdditionalLeadingTrivia = initializer is not null &&
+                    initializer.OpenBraceToken.GetPreviousToken().TrailingTrivia.Any(static x => x.IsSingleOrMultiLineComment() || x.IsEndOfLine());
+
+                if (shouldIncludeAdditionalLeadingTrivia)
+                {
+                    var additionalLeadingTrivia = initializer!.OpenBraceToken.GetPreviousToken().TrailingTrivia
+                        .SkipInitialWhitespace()
+                        .Concat(initializer.OpenBraceToken.LeadingTrivia);
+                    collectionExpression = collectionExpression.WithLeadingTrivia(additionalLeadingTrivia);
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpCollectionExpressionRewriter.cs:200]:
```suggestion
                    return collectionExpression.WithLeadingTrivia(additionalLeadingTrivia);
```

File: src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpCollectionExpressionRewriter.cs [hunk 11]
```diff
@@ -171,7 +171,41 @@ CollectionExpressionSyntax CreateCollectionExpressionWithoutExistingElements()
...
+                }
+                else
+                {
+                    // otherwise, we want to unconditionally preserve any and all trivia in the original expression
+                    collectionExpression = collectionExpression.WithTriviaFrom(expressionToReplace);
+                }
+
+                return collectionExpression;
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/CodeFixes/UseCollectionExpression/CSharpCollectionExpressionRewriter.cs:208]:
```suggestion
                    // otherwise, we want to unconditionally preserve any and all trivia in the original expression
                    return collectionExpression.WithTriviaFrom(expressionToReplace);
                }
```

File: src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs (hunk 2 above)
Comment (CyrusNajmabadi) [reply src/Analyzers/CSharp/Tests/UseCollectionExpression/UseCollectionExpressionForArrayTests.cs:5524]: can live with this.

File: src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests_CollectionExpression.cs [hunk 12]
```diff
@@ -2937,7 +2938,8 @@ class C
             {
                 void M()
                 {
-                    List<int> c = [];
+                    List<int> c = 
+                    [];
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/UseCollectionInitializer/UseCollectionInitializerTests_CollectionExpression.cs:2942]: i don't think this is a desirable change.  i think we should only be doing your new logic when there's a comment, not just a newline.

**Comment by JakeYallop** [comment]
Pushed up the changes.

**Review by CyrusNajmabadi — APPROVED** [review]
Looks great.  Thanks!
