### PR TITLE
Fix parameter code refactoring provider crash

### LINKED ISSUE #41824: coderefactoringprovider crashes with undocumented functions
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/920789/coderefactoringprovider-crashes-with-undocumented.html)._

---
Code:

```
 private static void RefX()
        {
            float i = 21.001f;
            TypedReference tr = __makeref(i);
            Type t = __reftype(tr);
            Console.WriteLine(t.ToString());
            var rv = __refvalue(tr, float);
            Console.WriteLine(rv);

DisplayNumbersOnConsole(__arglist(1, 2, 3, 5, 6));
        }

public static void DisplayNumbersOnConsole(__arglist)
        {
            ArgIterator ai = new ArgIterator(__arglist);
            while (ai. GetRemainingCount() > 0)
            {
                TypedReference tr = ai. GetNextArg();
                Console.WriteLine(TypedReference.ToObject(tr));
            }
        }
```

Errors:

csharpinitializememberfromparametercoderefactorprovider
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.InitializeParameter.AbstractInitializeParameterCodeRefactoringProvider`3. <ComputeRefactoringsAsync>g__TryGetParameterSymbol|7_0(SyntaxNode parameterNode,SemanticModel semanticModel,IParameterSymbol& parameter,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.InitializeParameter.AbstractInitializeParameterCodeRefactoringProvider`3.ComputeRefactoringsAsync[TParameterSyntax,TStatementSyntax,TExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

csharpaddparametercheckcoderefactoringprovider

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.InitializeParameter.AbstractInitializeParameterCodeRefactoringProvider`3. <ComputeRefactoringsAsync>g__TryGetParameterSymbol|7_0(SyntaxNode parameterNode,SemanticModel semanticModel,IParameterSymbol& parameter,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.InitializeParameter.AbstractInitializeParameterCodeRefactoringProvider`3.ComputeRefactoringsAsync[TParameterSyntax,TStatementSyntax,TExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

---
#### Visual Studio Feedback System on 2/19/2020, 05:11 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by allisonchou**
Fixes #41824.

### CODE REVIEW

File: src/Features/Core/Portable/InitializeParameter/AbstractInitializeParameterCodeRefactoringProvider.cs [hunk 1]
```diff
@@ -135,7 +135,8 @@ public override async Task ComputeRefactoringsAsync(CodeRefactoringContext conte
                 CancellationToken cancellationToken)
             {
                 parameter = (IParameterSymbol)semanticModel.GetDeclaredSymbol(parameterNode, cancellationToken);
-                return parameter.Name != "";
+
+                return parameter != null && parameter.Name != "";
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/InitializeParameter/AbstractInitializeParameterCodeRefactoringProvider.cs:139]:
```suggestion
                return parameter?.Name != "";
```

File: src/Features/Core/Portable/InitializeParameter/AbstractInitializeParameterCodeRefactoringProvider.cs [hunk 2]
```diff
@@ -135,7 +135,8 @@ public override async Task ComputeRefactoringsAsync(CodeRefactoringContext conte
                 CancellationToken cancellationToken)
             {
                 parameter = (IParameterSymbol)semanticModel.GetDeclaredSymbol(parameterNode, cancellationToken);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/InitializeParameter/AbstractInitializeParameterCodeRefactoringProvider.cs:137]: we likely have this issue in a lot of places :(

tagging @dpoeschl  for visibility in his 'add parameter' work.

Comment (mavasani) [reply src/Features/Core/Portable/InitializeParameter/AbstractInitializeParameterCodeRefactoringProvider.cs:137]: Interesting that the [file](http://sourceroslyn.io/#Microsoft.CodeAnalysis/Compilation/Extensions.cs,136) with GetDeclaredSymbol is nullable enabled, the comment on the method says it can return null, but return type is not annotated as a nullable symbol. Should we file a compiler bug to catch these issues?

Comment (allisonchou) [reply src/Features/Core/Portable/InitializeParameter/AbstractInitializeParameterCodeRefactoringProvider.cs:137]: Opened up an issue here: #42992
