### PR TITLE
Fix hang in compiler server

### LINKED ISSUE #23734: VBCSCompiler hangs in CLI build
PR is here: https://github.com/dotnet/cli/pull/8214.

When I tried this branch locally on OSX, the first time we build something using the VBCSCompiler, it actually hangs. If I kill that process, then the build progresses until the next compilation, compiles but then hangs again.

You should be able to repro it by simply checking out that branch and running build.sh. I haven't tried on Windows yet.

### PR DESCRIPTION
**Pull request by agocke**
### Customer scenario

The dotnet CLI has been seeing a hang from VBCSCompiler in their build
on non-Windows platforms. The cause is this:

    1. dotnet build starts a child process to do `dotnet pack` and
    redirects its output to a buffer.
    2. `dotnet pack` starts a child process to do `compile`.
    3. `compile` starts vbcscompiler because one is not already running.
    4. VBCSCompiler inherits the output handles from (1).
    5. VBCSCompiler process finishes and processes (1) and (2) exit.
    6. The parent `dotnet build` process  is waiting for (1) to exit,
    which it has, but also to see EOF on its output stream. Because that
    stream has been captured and held open by VBCSCompiler, the EOF
    never comes.
    7. `dotnet build` hangs.

This change fixes the problem by creating new streams for input and
output for the compiler server process. This isn't quite what we do on
Windows -- on Windows we create invalid handles for the input and output
-- but it's as close as we can get using the portable APIs in
System.Diagnostics.Process.

### Bugs this fixes

Fixes #23734

### Workarounds, if any

Disable the compiler server.

### Risk

The change is only for the compiler server on non-Windows platforms and changes the process start code to as closely match the Windows version as possible.

### Performance impact

None, just changing some perf-irrelevent process start options.

### Is this a regression from a previous update?

No.

### Root cause analysis

This bug needs multiple intermediate dotnet processes to appear. I haven't been able to repro this in a unit test yet, but I have done manually testing with the CLI.

### How was the bug found?

Found in CLI build

### CODE REVIEW

File: src/Compilers/Shared/BuildServerConnection.cs [hunk 1]
```diff
@@ -416,7 +416,19 @@ internal static bool TryCreateServerCore(string clientDir, string pipeName)
...
+                    var startInfo = new ProcessStartInfo()
+                    {
+                        FileName = expectedPath,
+                        Arguments = processArguments,
+                        UseShellExecute = false,
+                        WorkingDirectory = clientDir,
+                        RedirectStandardInput = true,
+                        RedirectStandardOutput = true,
+                        RedirectStandardError = true,
+                        CreateNoWindow = true
```
Comment (jaredpar) [inline src/Compilers/Shared/BuildServerConnection.cs]: Where are the streams redirected to in this case?

Comment (agocke) [reply src/Compilers/Shared/BuildServerConnection.cs]: On Unix, CoreFX calls into CoreCLR to create an anonymous pipe, then puts the child end in the new process and the parent end in the calling process. It closes the dangling files on both ends. Then it creates a wrapper FileStream for each fd.

This sounds OK except for one scenario: we never read from the output pipes in the caller. In theory this should be fine since we should never be writing to the pipe anyway, but if we ever did write to the pipe in VBCSCompiler we could end up filling up a buffer and blocking, which would be bad, but I'm counting on creating invalid output streams on Windows to catch that.

I looked into immediately trying to close these streams after completing process creation successfully, but couldn't convince myself it was always safe.

**Comment by agocke** [comment]
cc @MeiChin-Tsai for ask mode approval

**Comment by jaredpar** [comment]
Approved.
