### PR TITLE
Guard against EventListener dispose race

### LINKED ISSUE #8936: Roslyn.InteractiveWindow tests are still running into EventListener bug
We're still hitting this ~3 or 4 builds a week:

```
xUnit.net Console Runner (32-bit .NET 4.0.30319.42000)
  Discovering: Roslyn.InteractiveWindow.UnitTests
  Discovered:  Roslyn.InteractiveWindow.UnitTests
  Starting:    Roslyn.InteractiveWindow.UnitTests
  Finished:    Roslyn.InteractiveWindow.UnitTests
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Diagnostics.Tracing.EventListener.DisposeOnShutdown(Object sender, EventArgs e)
```

Bounty

### PR DESCRIPTION
**Pull request by jaredpar**
The underlying issue here is EventListener.DisposeOnShutdown has a race
condition if a new EventSource is added during an AppDomain or Process
exit.  When this occurs there is an unhandled exception during shutdown
due to a modified collection during enumeration that causes xunit to
falsely fail the run.

The type CDSCollectionETWBCLProvider triggers this bug in our tests.  It
is an EventSource for concurrent collections that is loaded on many
concurrent collection operations.  These operations are not triggered
directly in some of our tests and hence lead to the race.

This test guards against them force loading, albeit indirectly, the EventSource
instance of CDSCollectionETWBCLProvider.  Hence uses during shutdown
are just re-using this instance and don't trigger the race.

closes #8936

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @davkean, @dotnet/roslyn-interactive

File: src/Test/Shared/EventListenerGuard.cs [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+        /// The type CDSCollectionETWBCLProvider triggers this bug in our tests.  It
+        /// is an EventSource for concurrent collections that is loaded on many 
+        /// concurrent collection operations.  These operations are not triggered 
+        /// directly in some of our tests and hence lead to the race.  
+        /// 
+        /// This test guards against them force loading, albeit indirectly, the EventSource 
+        /// instance of CDSCollectionETWBCLProvider.  Hence uses during shutdown 
+        /// are just re-using this instance and don't trigger the race.
+        /// </summary>
+        [Fact]
```
Comment (amcasey) [inline src/Test/Shared/EventListenerGuard.cs]: `[WorkItem]`?

**Comment by amcasey** [comment]
Seems like a plausible explanation.  How on earth did you figure that out?

**Comment by amcasey** [comment]
Seems like a plausible explanation.  How on earth did you figure that out?

**Comment by amcasey** [comment]
:+1:

File: src/Test/Shared/EventListenerGuard.cs (hunk 1 above)
Comment (jaredpar) [inline src/Test/Shared/EventListenerGuard.cs]: Will add.

Comment (davkean) [inline src/Test/Shared/EventListenerGuard.cs]: Confused as to why you need to use reflection - why don't make sure the path is initialized via public means?

**Comment by jaredpar** [comment]
> How on earth did you figure that out?

I used private reflection to dump the list of `EventSource` instances at various intervals in the xunit run.  In failed runs the CDSCollectionETWBCLProvider was in the list, in non-failed runs it wasn't.  I walked backwards from that type to the triggers that cause it to be add into the `EventSource` list and discovered they're never directly used in this unit test project.  Directly used them and re-ran it in a loop and have not seen the failure since.

File: src/Test/Shared/EventListenerGuard.cs (hunk 1 above)
Comment (jaredpar) [inline src/Test/Shared/EventListenerGuard.cs]: The `CDSCollectionETWBCLProvider` type is `internal`.  No public means available.

**Comment by KevinH-MS** [comment]
Super Sleuth Parsons, FTW!  Ideally, I think this would be better to have in a shared constructor on some shared base class (so we don't bake in the assumption that all tests in the assembly run in the same AppDomain and it just seems more intuitive to have it there), but it doesn't appear that the InteractiveWindowTests have a shared base class, so LGTM :wink:

**Comment by ManishJayaswal** [comment]
:+1: Great to see this. Thanks you @jaredpar !!
