### PR TITLE
Diagnostics from Parse Options

### LINKED ISSUE #15797: CSharpParseOptions doesn't validate preprocessor symbols in some entry points
CSharpParseOptions validate given preprocessor names in ctor.

```csharp
public CSharpParseOptions(
            LanguageVersion languageVersion = LanguageVersion.Default,
            DocumentationMode documentationMode = DocumentationMode.Parse,
            SourceCodeKind kind = SourceCodeKind.Regular,
            IEnumerable<string> preprocessorSymbols = null)
            : this(languageVersion, documentationMode, kind, preprocessorSymbols.ToImmutableArrayOrEmpty())
        {
            // We test the mapped value, LanguageVersion, rather than the parameter, languageVersion,
            // which has not had "Latest" mapped to the latest version yet.
            if (!LanguageVersion.IsValid())
            {
                throw new ArgumentOutOfRangeException(nameof(languageVersion));
            }

            if (!kind.IsValid())
            {
                throw new ArgumentOutOfRangeException(nameof(kind));
            }

            if (preprocessorSymbols != null)
            {
                foreach (var preprocessorSymbol in preprocessorSymbols)
                {
                    if (!SyntaxFacts.IsValidIdentifier(preprocessorSymbol))
                    {
                        throw new ArgumentException(nameof(preprocessorSymbol));
                    }
                }
            }
        }
```

but, there are other API to update those preprocessor and those doesn't validate preprocessor which lead to invalidate preprocessor names in parse options.

for example, this (WithPreprocessorSymbols) doesnt validate preprocessor names.

```csharp
public CSharpParseOptions WithPreprocessorSymbols(ImmutableArray<string> symbols)
        {
            if (symbols.IsDefault)
            {
                symbols = ImmutableArray<string>.Empty;
            }

            if (symbols.Equals(this.PreprocessorSymbols))
            {
                return this;
            }

            return new CSharpParseOptions(this) { PreprocessorSymbols = symbols };
        }
```

this is causing serialization to fail since csharp parse option has a way for user to set preprocessor name that is not valid.

### LINKED ISSUE #15900: Change how pre-processor symbols are verified
Today the `CSharpParseOptions` type is inconsistent with how it verifies pre-processor symbols:

- The constructor will verify all symbols are valid identifiers and throw an exception when they are not. 
- The `WithPreProcessorSymbols` method does no verification. 

This inconsistency is bad for bot the compiler and consumers of the compiler API.  After some discussion the compiler team decided to change the API in the following way:

- The `CSharpParseOptions` type will never throw on pre-processor symbols that are invalid identifiers.
- Diagnostics will be produced for invalid identifiers in the pre-processor symbols

As a part of fixing this we should examine uses like in the following PR to see if they need to be cleaned up after the change.  

https://github.com/dotnet/roslyn/pull/15798

### PR DESCRIPTION
**Pull request by OmarTawfik**
Fixes #15900.
Fixes #15797.
Reverts #15798.

### CODE REVIEW

**Comment by OmarTawfik** [comment]
@dotnet-bot test this please

**Comment by OmarTawfik** [comment]
@dotnet-bot test this please

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-compiler

File: src/Compilers/Core/Portable/SourceCodeKind.cs [hunk 1]
```diff
@@ -32,6 +32,24 @@ public enum SourceCodeKind
...
+                    return SourceCodeKind.Regular;
+
+                case SourceCodeKind.Script:
+#pragma warning disable CS0618 // SourceCodeKind.Interactive is obsolete
+                case SourceCodeKind.Interactive:
+#pragma warning restore CS0618 // SourceCodeKind.Interactive is obsolete
+                    return SourceCodeKind.Script;
+
+                default:
+                    throw new NotSupportedException($"SourceCodeKind {kind} not supported");
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/SourceCodeKind.cs]: >throw new NotSupportedException($"SourceCodeKind {kind} not supported"); [](start = 20, length = 72)

I thought we decided to not throw while constructing ParseOptions. Consider using SourceCodeKind.Regular as a fallback kind instead.

File: src/Compilers/CSharp/Portable/CSharpParseOptions.cs [hunk 2]
```diff
@@ -50,90 +50,46 @@ public override IEnumerable<string> PreprocessorSymbolNames
...
-            if (features == null)
-            {
-                throw new ArgumentNullException(nameof(features));
-            }
-
-            _features = features;
+            this.SpecifiedLanguageVersion = languageVersion;
+            this.LanguageVersion = languageVersion.MapSpecifiedToEffectiveVersion();
+            this.PreprocessorSymbols = preprocessorSymbols.ToImmutableArrayOrEmpty();
+            _features = features?.ToImmutableDictionary() ?? ImmutableDictionary<string, string>.Empty;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CSharpParseOptions.cs]: >features?.ToImmutableDictionary() [](start = 24, length = 33)

Is this going to allocate a new ImmutableDictionary even when parameter is already an ImmutableDictionary?

File: src/Compilers/CSharp/Portable/CSharpResources.resx [hunk 3]
```diff
@@ -3318,10 +3318,7 @@ Give the compiler some way to differentiate the methods. For example, you can gi
     <value>'id#' syntax is no longer supported. Use '$id' instead.</value>
   </data>
   <data name="WRN_DefineIdentifierRequired" xml:space="preserve">
-    <value>Invalid value for '/define'; '{0}' is not a valid identifier</value>
-  </data>
-  <data name="WRN_DefineIdentifierRequired_Title" xml:space="preserve">
-    <value>Invalid value for '/define'; not a valid identifier</value>
+    <value>Invalid value for a preprocessing symbol; '{0}' is not a valid identifier</value>
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CSharpResources.resx]: It looks like the message became somewhat confusing, I believe it is the name of the symbol is incorrect, not its value.

File: src/Compilers/CSharp/Portable/CSharpResources.resx [hunk 4]
```diff
@@ -5011,4 +5008,19 @@ To remove the warning, you can use /reference instead (set the Embed Interop Typ
...
+  <data name="WRN_BadSourceCodeKind" xml:space="preserve">
+    <value>Provided Source Code Kind is unsupported or invalid: '{0}'</value>
+  </data>
+  <data name="ERR_BadLanguageVersion" xml:space="preserve">
+    <value>Provided Language Version is unsupported or invalid: '{0}'.</value>
+  </data>
+  <data name="WRN_BadSourceCodeKind_Title" xml:space="preserve">
+    <value>Provided Source Code Kind is unsupported or invalid</value>
+  </data>
+  <data name="WRN_DefineIdentifierRequired_Title" xml:space="preserve">
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CSharpResources.resx]: >WRN_DefineIdentifierRequired_Title [](start = 14, length = 34)

Consider keeping this string next to WRN_DefineIdentifierRequired, where it was before.

File: src/Compilers/CSharp/Portable/CSharpResources.resx [hunk 5]
```diff
@@ -5011,4 +5008,19 @@ To remove the warning, you can use /reference instead (set the Embed Interop Typ
   <data name="ERR_TypeForwardedToMultipleAssemblies" xml:space="preserve">
     <value>Module '{0}' in assembly '{1}' is forwarding the type '{2}' to multiple assemblies: '{3}' and '{4}'.</value>
   </data>
+  <data name="ERR_BadDocumentationMode" xml:space="preserve">
+    <value>Provided Documentation Mode is unsupported or invalid: '{0}'.</value>
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CSharpResources.resx]: >Documentation Mode [](start = 20, length = 18)

"**d**ocumentation **m**ode"

File: src/Compilers/CSharp/Portable/CSharpResources.resx [hunk 6]
```diff
@@ -5011,4 +5008,19 @@ To remove the warning, you can use /reference instead (set the Embed Interop Typ
...
+  </data>
+  <data name="WRN_BadSourceCodeKind" xml:space="preserve">
+    <value>Provided Source Code Kind is unsupported or invalid: '{0}'</value>
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CSharpResources.resx]: >Source Code Kind [](start = 20, length = 16)

"**s**ource **c**ode **k**ind"?

File: src/Compilers/CSharp/Portable/CSharpResources.resx [hunk 7]
```diff
@@ -5011,4 +5008,19 @@ To remove the warning, you can use /reference instead (set the Embed Interop Typ
...
+  </data>
+  <data name="ERR_BadLanguageVersion" xml:space="preserve">
+    <value>Provided Language Version is unsupported or invalid: '{0}'.</value>
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CSharpResources.resx]: >Language Version [](start = 20, length = 16)

"*l**anguage **v**ersion"?

File: src/Compilers/CSharp/Portable/CSharpResources.resx [hunk 8]
```diff
@@ -5011,4 +5008,19 @@ To remove the warning, you can use /reference instead (set the Embed Interop Typ
...
+  </data>
+  <data name="WRN_BadSourceCodeKind_Title" xml:space="preserve">
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CSharpResources.resx]: >WRN_BadSourceCodeKind_Title [](start = 14, length = 27)

Consider keeping this string next to WRN_BadSourceCodeKind.

File: src/Compilers/CSharp/Portable/CommandLine/CSharpCommandLineParser.cs [hunk 9]
```diff
@@ -1221,7 +1221,10 @@ public new CSharpCommandLineArguments Parse(IEnumerable<string> args, string bas
                 features: parsedFeatures
             );
 
-            var scriptParseOptions = parseOptions.WithKind(SourceCodeKind.Script);
+            if (IsScriptRunner)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CommandLine/CSharpCommandLineParser.cs]: >if (IsScriptRunner) [](start = 12, length = 19)

Could we inline this into the constructor above, in place of the kind argument?

File: src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs [hunk 10]
```diff
@@ -1927,6 +1927,7 @@ internal ImmutableArray<Diagnostic> GetDiagnostics(CompilationStage stage, bool
                             var syntaxTree = syntaxTrees[i];
                             AppendLoadDirectiveDiagnostics(builder, _syntaxAndDeclarations, syntaxTree);
                             builder.AddRange(syntaxTree.GetDiagnostics(cancellationToken));
+                            builder.AddRange(syntaxTree.Options.Errors);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs]: Let's discuss offline.

---
In reply to: [101836220](https://github.com/dotnet/roslyn/pull/17113#discussion_r101836220) [](ancestors = 101836220)

File: src/Compilers/CSharp/Portable/Errors/ErrorCode.cs [hunk 11]
```diff
@@ -1439,7 +1439,13 @@ internal enum ErrorCode
         ERR_DelegateRefMismatch = 8189,
         #endregion stragglers for C# 7
 
-        // Available  = 8190-8195
+        #region diagnostics for parse options
+        WRN_BadSourceCodeKind = 8190,
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Errors/ErrorCode.cs]: >WRN_BadSourceCodeKind [](start = 8, length = 21)

It is not clear why this is a warning.

File: src/Compilers/CSharp/Test/Syntax/Parsing/CSharpParseOptionsTests.cs [hunk 12]
```diff
@@ -73,5 +52,189 @@ public void TestFieldsForEqualsAndGetHashCode()
...
+            options.Errors.Verify();
+
+            options = new CSharpParseOptions(kind: SourceCodeKind.Script);
+            Assert.Equal(SourceCodeKind.Script, options.Kind);
+            Assert.Equal(SourceCodeKind.Script, options.SpecifiedKind);
+
+            options.Errors.Verify();
+
+#pragma warning disable CS0618 // SourceCodeKind.Interactive is obsolete
+            options = new CSharpParseOptions(kind: SourceCodeKind.Interactive);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Syntax/Parsing/CSharpParseOptionsTests.cs]: >options = new CSharpParseOptions(kind: SourceCodeKind.Interactive); [](start = 12, length = 67)

Please add a test with int.MinValue

File: src/Compilers/CSharp/Test/Syntax/Parsing/CSharpParseOptionsTests.cs [hunk 13]
```diff
@@ -73,5 +52,189 @@ public void TestFieldsForEqualsAndGetHashCode()
...
         }
+
+        [Fact]
+        public void SpecifiedKindIsMappedCorrectly()
+        {
+            var options = new CSharpParseOptions(kind: SourceCodeKind.Regular);
+            Assert.Equal(SourceCodeKind.Regular, options.Kind);
+            Assert.Equal(SourceCodeKind.Regular, options.SpecifiedKind);
+
+            options.Errors.Verify();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Syntax/Parsing/CSharpParseOptionsTests.cs]: >options.Errors.Verify(); [](start = 12, length = 24)

Consider testing that an instance, which is created without passing any explicit values, has no errors.

File: src/Compilers/VisualBasic/Portable/VisualBasicParseOptions.vb [hunk 14]
```diff
@@ -318,6 +239,32 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
+
+            ' Validate LanguageVersion Not SpecifiedLanguageVersion, after Latest/Default has been converted
+            If Not LanguageVersion.IsValid Then
+                builder.Add(Diagnostic.Create(MessageProvider.Instance, ERRID.ERR_BadLanguageVersion, LanguageVersion.ToString))
+            End If
+
+            If Not PreprocessorSymbols.IsDefaultOrEmpty Then
+                For Each symbol In PreprocessorSymbols
+                    If Not IsValidIdentifier(symbol.Key) OrElse SyntaxFacts.GetKeywordKind(symbol.Key) <> SyntaxKind.None Then
+                        builder.Add(Diagnostic.Create(MessageProvider.Instance, ERRID.ERR_ProjectCCError1, VBResources.ERR_ExpectedIdentifier, symbol.Key))
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/VisualBasicParseOptions.vb]: >ERR_ProjectCCError1 [](start = 86, length = 19)

It doesn't look like this error is applicable to this situation.

File: src/Compilers/VisualBasic/Portable/VisualBasicParseOptions.vb [hunk 15]
```diff
@@ -318,6 +239,32 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
+                    Else
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/VisualBasicParseOptions.vb]: >Else [](start = 20, length = 4)

Consider checking the value regardless whether the name is valid or not.

File: src/Compilers/VisualBasic/Portable/VisualBasicParseOptions.vb [hunk 16]
```diff
@@ -318,6 +239,32 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
+
+                        Debug.Assert(SyntaxFactory.ParseTokens(symbol.Key).Select(Function(t) t.Kind).SequenceEqual({SyntaxKind.IdentifierToken, SyntaxKind.EndOfFileToken}))
+
+                        Dim constant = InternalSyntax.CConst.TryCreate(symbol.Value)
+                        If constant Is Nothing Then
+                            builder.Add(Diagnostic.Create(MessageProvider.Instance, ERRID.IDS_InvalidPreprocessorConstantType, symbol.Key, symbol.Value.GetType))
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/VisualBasicParseOptions.vb]: >IDS_InvalidPreprocessorConstantType [](start = 90, length = 35)

IDS_InvalidPreprocessorConstantType is neither an error number, nor a warning number, it simply designates a string in the resource file. It should not be used to create diagnostics.

**Comment by AlekseyTs** [comment]
It feels like Errors for VisualBasicCompilationOption should include errors from ParseOptions property when   it is not Nothing.

**Comment by AlekseyTs** [comment]
Done with review pass.

File: src/Compilers/CSharp/Portable/CSharpParseOptions.cs [hunk 17]
```diff
@@ -228,6 +173,32 @@ public new CSharpParseOptions WithFeatures(IEnumerable<KeyValuePair<string, stri
             }
         }
 
+        internal override void ValidateOptions(ArrayBuilder<Diagnostic> builder)
+        {
+            ValidateOptions(builder, MessageProvider.Instance);
+
+            // Validate LanguageVersion not SpecifiedLanguageVersion, after Latest/Default has been converted:
+            if (!LanguageVersion.IsValid())
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/CSharpParseOptions.cs]: I don't know why we're adding a diagnostic for this. `LanguageVersion` is something that is specified as an `enum`, not as a string that is parsed, which under our guidelines suggests that it should throw an ArgumentException when a bad language version is specified. The underlying bug to be fixed here doesn't suggest a diagnsotic for this.

File: src/Compilers/CSharp/Portable/CSharpParseOptions.cs [hunk 18]
```diff
@@ -184,11 +135,6 @@ public new CSharpParseOptions WithDocumentationMode(DocumentationMode documentat
                 return this;
             }
 
-            if (!documentationMode.IsValid())
-            {
-                throw new ArgumentOutOfRangeException(nameof(documentationMode));
-            }
-
             return new CSharpParseOptions(this) { DocumentationMode = documentationMode };
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/CSharpParseOptions.cs]: Same issue with DocumentationMode. Since it is an enum specified programmatically, it should be diagnosed as an `ArgumentException` of some sort, not a diagnostic. See the [Compiler Design Notes](https://microsoft.sharepoint.com/teams/managedlanguages/_layouts/OneNote.aspx?id=%2Fteams%2Fmanagedlanguages%2Ffiles%2FTeam%20Notebook%2FRoslyn%20Team%20Notebook%20-%20New&wd=target%28Compilers%2FCompiler%20Design.one%7CD0427C1F-43BD-44AA-A337-20E46E56BB4C%2FRE%3A%20diagnostics%20vs.%20exceptions%7C3394BDFB-E7C9-40B6-B1C9-A8B87DD46ED7%2F%29) for guidance.

File: src/Compilers/CSharp/Portable/CSharpResources.resx (hunk 6 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/CSharpResources.resx]: This should revert to an exception, not a diagnostic.

File: src/Compilers/CSharp/Portable/CSharpResources.resx (hunk 5 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/CSharpResources.resx]: This should revert to an exception, not a diagnostic.

File: src/Compilers/CSharp/Portable/CSharpResources.resx (hunk 7 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/CSharpResources.resx]: This should revert to an exception, not a diagnostic.

File: src/Compilers/CSharp/Portable/CSharpParseOptions.cs (hunk 18 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CSharpParseOptions.cs]: I think we are moving towards the same model we have with CompilationOptions. I.e. construction doesn't throw. Never. Instead errors are surfaced as diagnostics. For example, Platform an enum, OutputKind is an enum, OptimizationLevel is an enum, but compilation options does not throw on invalid values for them.

File: src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs (hunk 10 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs]: Reporting the diagnostics here unconditionally will have the unfortunate consequence of causing parse option errors to be duplicated for every tree in the compilation. Since a compilation does use the parse options (e.g. language version), even if it is an indirect input, we probably do want to report problems with the parse options if a broken parse options is used to construct a tree which is used in a compilation. However, we should only report the diagnostics for any given parse options object once.

Comment (gafter) [inline src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs]: I should add that it makes sense for the syntax option diagnostics to be reported here for the same reason that it makes sense for the syntax diagnostics to be reported here. However, the syntax option diagnostics should not be reported repeatedly for the same syntax options. When the same options are used for multiple trees (which is the normal case) they should be reported once per options object.

File: src/Compilers/CSharp/Portable/CSharpParseOptions.cs (hunk 2 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/CSharpParseOptions.cs]: It shouldn't: [http://source.dot.net/#System.Collections.Immutable/System/Collections/Immutable/ImmutableDictionary.cs,c7a8ca73f530a839](http://source.dot.net/#System.Collections.Immutable/System/Collections/Immutable/ImmutableDictionary.cs,c7a8ca73f530a839)

---
In reply to: [101830042](https://github.com/dotnet/roslyn/pull/17113#discussion_r101830042) [](ancestors = 101830042)

File: src/Compilers/CSharp/Portable/Errors/ErrorCode.cs (hunk 11 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/Errors/ErrorCode.cs]: Because the Obsolete attribute is a warning. We can turn it into an error when the obsolete attribute changes as well:
[https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/SourceCodeKind.cs#L28](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/SourceCodeKind.cs#L28)

---
In reply to: [101839466](https://github.com/dotnet/roslyn/pull/17113#discussion_r101839466) [](ancestors = 101839466)

File: src/Compilers/CSharp/Portable/CSharpParseOptions.cs (hunk 17 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/CSharpParseOptions.cs]: Discussed offline. Agreed that we shouldn't throw at all.

---
In reply to: [101868422](https://github.com/dotnet/roslyn/pull/17113#discussion_r101868422) [](ancestors = 101868422)

File: src/Compilers/CSharp/Portable/CSharpParseOptions.cs (hunk 18 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/CSharpParseOptions.cs]: Same.

---
In reply to: [101868868](https://github.com/dotnet/roslyn/pull/17113#discussion_r101868868) [](ancestors = 101868868)

File: src/Compilers/CSharp/Portable/CSharpResources.resx (hunk 5 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/CSharpResources.resx]: Same.

---
In reply to: [101869014](https://github.com/dotnet/roslyn/pull/17113#discussion_r101869014) [](ancestors = 101869014)

File: src/Compilers/CSharp/Portable/CSharpResources.resx (hunk 7 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/CSharpResources.resx]: Same.

---
In reply to: [101869018](https://github.com/dotnet/roslyn/pull/17113#discussion_r101869018) [](ancestors = 101869018)

File: src/Compilers/CSharp/Portable/CSharpResources.resx (hunk 6 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/CSharpResources.resx]: Same.

---
In reply to: [101868992](https://github.com/dotnet/roslyn/pull/17113#discussion_r101868992) [](ancestors = 101868992)

File: src/Compilers/VisualBasic/Portable/VisualBasicParseOptions.vb (hunk 14 above)
Comment (OmarTawfik) [inline src/Compilers/VisualBasic/Portable/VisualBasicParseOptions.vb]: Can you please elaborate?
    <value>Project-level conditional compilation constant '{1}' is not valid: {0}</value>
Which evaluates to:
Project-level conditional compilation constant 'XX' is not valid: Identifier expected.

---
In reply to: [101844385](https://github.com/dotnet/roslyn/pull/17113#discussion_r101844385) [](ancestors = 101844385)

File: src/Compilers/CSharp/Portable/Errors/ErrorCode.cs (hunk 11 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/Errors/ErrorCode.cs]: Following up, it is correct that it should be an error (replacing the existing exception). Will fix it.

---
In reply to: [105035896](https://github.com/dotnet/roslyn/pull/17113#discussion_r105035896) [](ancestors = 105035896,101839466)

File: src/Compilers/VisualBasic/Portable/VisualBasicParseOptions.vb (hunk 14 above)
Comment (OmarTawfik) [inline src/Compilers/VisualBasic/Portable/VisualBasicParseOptions.vb]: Following up, there should be a different error message as these options are file-level, not project-level.

---
In reply to: [105271724](https://github.com/dotnet/roslyn/pull/17113#discussion_r105271724) [](ancestors = 105271724,101844385)

Comment (OmarTawfik) [inline src/Compilers/VisualBasic/Portable/VisualBasicParseOptions.vb]: Conditional compilation constant '{1}' is not valid: {0}

---
In reply to: [105281980](https://github.com/dotnet/roslyn/pull/17113#discussion_r105281980) [](ancestors = 105281980,105271724,101844385)

File: src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs (hunk 10 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs]: I believe they should align with how we're reporting  CompilationOptions errors below:
builder.AddRange(Options.Errors);

We should be able to report both (deduping in the process).

---
In reply to: [101836674](https://github.com/dotnet/roslyn/pull/17113#discussion_r101836674) [](ancestors = 101836674,101836220)

**Comment by tannergooding** [comment]
test windows_debug_vs-integration_prtest please

**Comment by OmarTawfik** [comment]
@gafter @AlekseyTs @heejaechang @dotnet/roslyn-compiler 
Comments addressed.

File: src/Compilers/CSharp/Portable/CSharpParseOptions.cs [hunk 19]
```diff
@@ -228,6 +173,32 @@ public new CSharpParseOptions WithFeatures(IEnumerable<KeyValuePair<string, stri
...
+                builder.Add(Diagnostic.Create(MessageProvider.Instance, (int)ErrorCode.ERR_BadLanguageVersion, LanguageVersion.ToString()));
+            }
+            
+            if (!PreprocessorSymbols.IsDefaultOrEmpty)
+            {
+                foreach (var symbol in PreprocessorSymbols)
+                {
+                    if (symbol == null)
+                    {
+                        builder.Add(Diagnostic.Create(MessageProvider.Instance, (int)ErrorCode.WRN_DefineIdentifierRequired, "null"));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CSharpParseOptions.cs]: >WRN_DefineIdentifierRequired [](start = 95, length = 28)

Why are we reporting warnings here? If condition used to cause an exception, we should report an error instead, I believe.

**Comment by OmarTawfik** [comment]
@dotnet-bot test windows_debug_vs-integration_prtest please

File: src/Compilers/CSharp/Portable/CSharpResources.resx [hunk 20]
```diff
@@ -3321,10 +3321,7 @@ Give the compiler some way to differentiate the methods. For example, you can gi
     <value>'id#' syntax is no longer supported. Use '$id' instead.</value>
   </data>
   <data name="WRN_DefineIdentifierRequired" xml:space="preserve">
-    <value>Invalid value for '/define'; '{0}' is not a valid identifier</value>
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CSharpResources.resx]: ><value>Invalid value for a preprocessing symbol; '{0}' is not a valid identifier</value> [](start = 4, length = 88)

I don't think we there is a need to modify this warning. Its wording is fine for command line parser, we simply shouldn't be reusing it for parse options diagnostics because they should be errors instead.

File: src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs [hunk 21]
```diff
@@ -1927,17 +1928,26 @@ internal ImmutableArray<Diagnostic> GetDiagnostics(CompilationStage stage, bool
                             var syntaxTree = syntaxTrees[i];
                             AppendLoadDirectiveDiagnostics(builder, _syntaxAndDeclarations, syntaxTree);
                             builder.AddRange(syntaxTree.GetDiagnostics(cancellationToken));
+                            if (parseOptionsReported.Add(syntaxTree.Options))
+                            {
+                                builder.AddRange(syntaxTree.Options.Errors);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs]: >builder.AddRange(syntaxTree.Options.Errors) [](start = 32, length = 43)

What is going to be the location for the errors? How a client can figure out what parse options are causing them? I think the location of the errors should be adjusted to point to the associated syntax tree.

File: src/Compilers/CSharp/Portable/CSharpResources.resx (hunk 20 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CSharpResources.resx]: Actually,the message is clearer now even for command line parser.

---
In reply to: [105717049](https://github.com/dotnet/roslyn/pull/17113#discussion_r105717049) [](ancestors = 105717049)

File: src/Compilers/VisualBasic/Portable/CommandLine/VisualBasicCommandLineParser.vb [hunk 22]
```diff
@@ -1683,7 +1682,7 @@ lVbRuntimePlus:
                     Dim constant = InternalSyntax.CConst.TryCreate(symbol.Value)
 
                     If constant Is Nothing Then
-                        Throw New ArgumentException(String.Format(ErrorFactory.IdToString(ERRID.IDS_InvalidPreprocessorConstantType, Culture), symbol.Key, symbol.Value.GetType()), parameterName)
+                        diagnosticBuilder.Add(Diagnostic.Create(VisualBasic.MessageProvider.Instance, ERRID.ERR_InvalidPreprocessorConstantType, symbol.Key, symbol.Value.GetType))
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/CommandLine/VisualBasicCommandLineParser.vb]: >GetType [](start = 170, length = 7)

Is this a function? Please add ```()``` at the end.

File: src/Compilers/VisualBasic/Portable/CommandLine/VisualBasicCommandLineParser.vb [hunk 23]
```diff
@@ -1674,6 +1672,7 @@ lVbRuntimePlus:
         ''' </summary>
         ''' <exception cref="ArgumentException">Invalid value provided.</exception>
         Private Shared Function PublicSymbolsToInternalDefines(symbols As IEnumerable(Of KeyValuePair(Of String, Object)),
+                                                               diagnosticBuilder As ArrayBuilder(Of Diagnostic),
                                                                parameterName As String) As ImmutableDictionary(Of String, InternalSyntax.CConst)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/CommandLine/VisualBasicCommandLineParser.vb]: >parameterName As String [](start = 63, length = 23)

It looks like this parameter is no longer used. Please remove.

**Comment by AlekseyTs** [comment]
>         IDS_InvalidPreprocessorConstantType = 56010

Consider marking this value as available, or using it for the next constant.

---
Refers to: src/Compilers/VisualBasic/Portable/Errors/Errors.vb:1975 in c67bd7b. [](commit_id = c67bd7be88eb34b762e96469158ce68130cd884f, deletion_comment = True)

File: src/Compilers/CSharp/Test/Syntax/Parsing/CSharpParseOptionsTests.cs [hunk 24]
```diff
@@ -73,5 +52,203 @@ public void TestFieldsForEqualsAndGetHashCode()
...
+            options = new CSharpParseOptions(kind: SourceCodeKind.Interactive);
+            Assert.Equal(SourceCodeKind.Script, options.Kind);
+            Assert.Equal(SourceCodeKind.Interactive, options.SpecifiedKind);
+#pragma warning restore CS0618 // SourceCodeKind.Interactive is obsolete
+
+            options.Errors.Verify(
+                // error CS8190: Provided source code kind is unsupported or invalid: 'Interactive'.
+                Diagnostic(ErrorCode.ERR_BadSourceCodeKind).WithArguments("Interactive").WithLocation(1, 1));
+
+            options = new CSharpParseOptions(kind: (SourceCodeKind)int.MinValue);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Syntax/Parsing/CSharpParseOptionsTests.cs]: >(SourceCodeKind)int.MinValue [](start = 51, length = 28)

Do we have similar test for VB?

File: src/Compilers/VisualBasic/Test/Semantic/Diagnostics/GetDiagnosticsTests.vb [hunk 25]
```diff
@@ -224,6 +224,145 @@ End Namespace
...
+            dict1.Add("1", Nothing)
+            Dim dict2 = New Dictionary(Of String, Object)
+            dict2.Add("2", Nothing)
+
+            Dim parseOptions1 = New VisualBasicParseOptions().WithPreprocessorSymbols(dict1)
+            Dim parseOptions2 = New VisualBasicParseOptions().WithPreprocessorSymbols(dict2)
+
+            Dim syntaxTree1 = Parse(String.Empty, options:=parseOptions1)
+
+            Dim options = New VisualBasicCompilationOptions(OutputKind.DynamicallyLinkedLibrary, concurrentBuild:=concurrentBuild, parseOptions:=parseOptions2)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/Diagnostics/GetDiagnosticsTests.vb]: >Dim options = New VisualBasicCompilationOptions(OutputKind.DynamicallyLinkedLibrary, concurrentBuild:=concurrentBuild, parseOptions:=parseOptions2) [](start = 12, length = 147)

We should assert errors from compilation options, unless we have another unit-test that is doing this.

**Comment by AlekseyTs** [comment]
Done with review pass.

**Comment by OmarTawfik** [comment]
>         IDS_InvalidPreprocessorConstantType = 56010

Added a comment specifying so.

---
In reply to: [286186223](https://github.com/dotnet/roslyn/pull/17113#issuecomment-286186223) [](ancestors = 286186223)

---
Refers to: src/Compilers/VisualBasic/Portable/Errors/Errors.vb:1975 in c67bd7b. [](commit_id = c67bd7be88eb34b762e96469158ce68130cd884f, deletion_comment = True)

File: src/Compilers/CSharp/Portable/CSharpParseOptions.cs (hunk 19 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/CSharpParseOptions.cs]: I chose it to match the warning returned by the command line parser. I believe they should match. The user shouldn't get a warning from the command line and an error from the API (for the same input).
Should we turn both into an error? thoughts?

---
In reply to: [105716480](https://github.com/dotnet/roslyn/pull/17113#discussion_r105716480) [](ancestors = 105716480)

File: src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs (hunk 21 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs]: a couple of questions:
What if the same ParseOptions object was associated to multiple trees? use additional locations? which one takes precedence?
In VB, what if the same object is used in the CompilationOptions.ParseOptions as well?

---
In reply to: [105718150](https://github.com/dotnet/roslyn/pull/17113#discussion_r105718150) [](ancestors = 105718150)

File: src/Compilers/CSharp/Portable/CSharpParseOptions.cs (hunk 19 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/CSharpParseOptions.cs]: After discussion, we're ok with the mismatch between command line and API.

---
In reply to: [105762061](https://github.com/dotnet/roslyn/pull/17113#discussion_r105762061) [](ancestors = 105762061,105716480)

File: src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs [hunk 26]
```diff
@@ -1927,17 +1928,36 @@ internal ImmutableArray<Diagnostic> GetDiagnostics(CompilationStage stage, bool
                             var syntaxTree = syntaxTrees[i];
                             AppendLoadDirectiveDiagnostics(builder, _syntaxAndDeclarations, syntaxTree);
                             builder.AddRange(syntaxTree.GetDiagnostics(cancellationToken));
+
+                            if (!syntaxTree.Options.Errors.IsDefaultOrEmpty && parseOptionsReported.Add(syntaxTree.Options))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs]: >if (!syntaxTree.Options.Errors.IsDefaultOrEmpty && parseOptionsReported.Add(syntaxTree.Options)) [](start = 28, length = 96)

It feels like this should be done outside of Parallel.For, otherwise the location is not deterministic.

File: src/Compilers/CSharp/Test/Semantic/Diagnostics/GetDiagnosticsTests.cs [hunk 27]
```diff
@@ -299,5 +299,97 @@ public void TestEventQueueCompletionForEmptyCompilation()
...
+            var syntaxTree1 = Parse(string.Empty, options: new CSharpParseOptions().WithPreprocessorSymbols(new[] { "1" }));
+            var syntaxTree2 = Parse(string.Empty, options: new CSharpParseOptions().WithPreprocessorSymbols(new[] { "2" }));
+            var syntaxTree3 = Parse(string.Empty, options: new CSharpParseOptions().WithPreprocessorSymbols(new[] { "3" }).WithDocumentationMode(unchecked((DocumentationMode)100)));
+
+            var compilation = CreateCompilation(new[] { syntaxTree1, syntaxTree2, syntaxTree3 });
+
+            compilation.VerifyDiagnostics(
+                // (1,1): error CS8301: Invalid name for a preprocessing symbol; '2' is not a valid identifier
+                // 
+                Diagnostic(ErrorCode.ERR_InvalidPreprocessingSymbol, "").WithArguments("2").WithLocation(1, 1),
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Diagnostics/GetDiagnosticsTests.cs]: >Diagnostic(ErrorCode.ERR_InvalidPreprocessingSymbol, "").WithArguments("2").WithLocation(1, 1), [](start = 16, length = 95)

It is not clear with which SyntaxTree the errors are associated.

File: src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb [hunk 28]
```diff
@@ -1920,13 +1920,42 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
+                        parseOptionsReported.Add(Options.ParseOptions) ' This is reported in Options.Errors at CompilationStage.Declare
+                    End If
+
+                    Dim parallelOptions = New ParallelOptions() With {.CancellationToken = cancellationToken}
+                    Parallel.For(0, SyntaxTrees.Length, parallelOptions,
+                            UICultureUtilities.WithCurrentUICulture(Sub(i As Integer)
+                                                                        Dim syntaxTree = SyntaxTrees(i)
+                                                                        builder.AddRange(syntaxTree.GetDiagnostics(cancellationToken))
+
+                                                                        If Not syntaxTree.Options.Errors.IsDefaultOrEmpty And parseOptionsReported.Add(syntaxTree.Options) Then
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb]: >And [](start = 122, length = 3)

AndAlso?

File: src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb [hunk 29]
```diff
@@ -1920,13 +1920,42 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
+                    Dim parseOptionsReported = New HashSet(Of ParseOptions)
+                    If Options.ParseOptions IsNot Nothing Then
+                        parseOptionsReported.Add(Options.ParseOptions) ' This is reported in Options.Errors at CompilationStage.Declare
+                    End If
+
                     For Each tree In SyntaxTrees
                         cancellationToken.ThrowIfCancellationRequested()
                         builder.AddRange(tree.GetDiagnostics(cancellationToken))
+
+                        If Not tree.Options.Errors.IsDefaultOrEmpty And parseOptionsReported.Add(tree.Options) Then
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb]: >And [](start = 68, length = 3)

AndAlso?

File: src/Compilers/VisualBasic/Portable/Errors/Errors.vb [hunk 30]
```diff
@@ -1968,7 +1973,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
         IDS_LogoLine1 = 56007
         IDS_LogoLine2 = 56008
         IDS_VBCHelp = 56009
-        IDS_InvalidPreprocessorConstantType = 56010
+        ' IDS_InvalidPreprocessorConstantType = 56010           Replaced by ERR_InvalidPreprocessorConstantType
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Errors/Errors.vb]: This looks more like reserved value, did you mean to reserve it?

**Comment by AlekseyTs** [comment]
Done with review pass.

File: src/Compilers/VisualBasic/Portable/Errors/Errors.vb (hunk 30 above)
Comment (OmarTawfik) [inline src/Compilers/VisualBasic/Portable/Errors/Errors.vb]: From what I can see in the rest of the file, old values that are no longer used are commented out, with a note about why they were so, which leads to using new enum values for new messages.
Do you see otherwise? should this line be removed and the number marked as available so that it can be reused?

---
In reply to: [105784631](https://github.com/dotnet/roslyn/pull/17113#discussion_r105784631) [](ancestors = 105784631)

Comment (OmarTawfik) [inline src/Compilers/VisualBasic/Portable/Errors/Errors.vb]: Discussed offline. Will mark as available as this value is not exposed externally to compiler consumers.

---
In reply to: [105975443](https://github.com/dotnet/roslyn/pull/17113#discussion_r105975443) [](ancestors = 105975443,105784631)

File: src/Compilers/VisualBasic/Test/Semantic/Diagnostics/GetDiagnosticsTests.vb [hunk 31]
```diff
@@ -224,6 +224,189 @@ End Namespace
...
+
+            CompilationUtils.AssertTheseDiagnostics(diagnostics,
+<errors>
+BC31030: Conditional compilation constant '1' is not valid: Identifier expected.
+BC31030: Conditional compilation constant '2' is not valid: Identifier expected.
+
+~
+</errors>)
+
+            Assert.Equal(diagnostics(0).Arguments, {"Identifier expected.", "2"})
```
Comment (OmarTawfik) [inline src/Compilers/VisualBasic/Test/Semantic/Diagnostics/GetDiagnosticsTests.vb]: CompilationUtils sorts errors before comparison. Added a comment and an assert for the correct order.
