### PR TITLE
Optimize single spread of IEnumerable to array

### LINKED ISSUE #71296: Poor codegen for collection expression spread (IEnumerable<T> -> ImmutableArray<T>)
Related to #71195

**Version Used**: 4.9.0-ci (https://github.com/dotnet/roslyn/commit/a8119d1e97dd6e926ad3d6599c6c15ae6e5f2a8f)

**Steps to Reproduce**:

```csharp
using System.Collections.Generic;
using System.Collections.Immutable;

static ImmutableArray<string> Test(IEnumerable<string> items)
{
    return [.. items];
}
```

[sharplab](https://sharplab.io/#v2:EYLgtghglgdgPgAQAwAIEEYAsBuAsAKGTXQDoBhAewBsqBTAYwBcoKYBnEgSTDAFdGIwOnnwEMANhTc+AobQCCAJ0UQAngB4MSAHwoAKrTaMAFBgDMm9DpRRGtMGwCUBAN4EUHtAHYUAbRIkNnYOALoiAL5AA===)

**Expected Behavior**:

```csharp
return ImmutableArray.CreateRange(items);
```

**OR**

```csharp
return items.ToImmutableArray();
```

**Actual Behavior**:

```csharp
List<string> list = new List<string>();
IEnumerator<string> enumerator = items.GetEnumerator();
try
{
    while (enumerator.MoveNext())
    {
        string current = enumerator.Current;
        list.Add(current);
    }
}
finally
{
    if (enumerator != null)
    {
        enumerator.Dispose();
    }
}
return ImmutableCollectionsMarshal.AsImmutableArray(list.ToArray());
```

@RikkiGibson @CyrusNajmabadi not entirely sure whether the spec allows this, I think the problem is that the factory API is `CreateRange`, but `[CollectionBuilder]` over `ImmutableArray<T>` uses `Create` as the method name. Perhaps it would be possible to just hardcode these additional `ImmutableArray<T>` cases? Though it'd be nice to have a more general solution 🤔

### LINKED ISSUE #71755: Imperfect IEnumerable<T> -> Span<T> collection expression conversion
Trying out the new collection expressions on existing code, there are some areas where perf and memory allocation could be brought up to par with already-existing code.

Currently, converting from IEnumerable<T> to Span<T> goes through numerous unnecessary allocations. in [.NET 8](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwCwG5lqZwB0AMgJYB2AjvkgQMyYzoDCyA3ut+sj5kywA2dABV0AMQBOAewC2AeQA2wADyiAfAAosDdRvQA3AIZKArgFMAzgEo+PDvf7coAdkmy5rGVItaT5tbEojIAglJSxgCeWjbEoVYAygAOxpSxNnT8AL5OvEj8UIJwIuLS8gByFgDu+jpweppGppa2eY4Fzi7u5V4+fgDaxMTNgVYAupl5uZ3ceclS5CYALhZEpR7y3r51KWn6o612s+gdXdwA+ugAvIfWWedu6MAWAGbGZkrLAIQP3DPZIA) and in the [current main](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKHQAYACdbAFgG4DizsA6AGVgEcb9aBmMzEgYQIBvEqJIExZHuQBsJACokAYgCcA9mADyAGwQAeeQD4AFOS4HDJAG4RtAVwCmAZwCUEsUPeTR6AOzL1MH41FQdjG3tnBnk1AEEVFQgAT2MXBlinAGUABwgYVJcOSQBfL3F8SXRpbDlFVQ0AOQcAdwtTbHMja1tHVzLPCu8ff3qgkLCAbQYGbsinAF1CstLB0TLslSgbABcHelqAjWDQtpy8i1net1WSAaHRAH0SAF5L5yL7vxIEBwAzCDs2m2AEIPqIVsUgA===), these are both inferior to the simple `Enumerable.ToArray` method.

Benchmark:

<details>
<summary>Benchmark code</summary>

``` csharp
// dotnet run -c Release -f net8.0 --filter "*"

using System.Diagnostics.CodeAnalysis;

using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkSwitcher.FromAssembly(typeof(Tests).Assembly).Run(args);

[HideColumns("Error", "StdDev", "Median", "RatioSD")]
[MemoryDiagnoser(false)]
public class Tests
{
    public IEnumerable<object> Numbers()
    {
        yield return new string[] { "a", "b", "c", "d" };

        yield return new List<string> { "a", "b", "c", "d" };

        yield return new string[] { "adminToken2", "adminToken3", "adminToken4", "adminToken5", "adminToken6", "adminToken7", "adminToken8", "adminToken9", "adminToken10", "adminToken11", "adminToken12", "adminToken13" };

        yield return GetTokenNames();
    }

    private static IEnumerable<string> GetTokenNames()
    {
        yield return "adminToken2";
        yield return "adminToken3";
        yield return "adminToken4";
        yield return "adminToken5";
        yield return "adminToken6";
        yield return "adminToken7";
        yield return "adminToken8";
        yield return "adminToken9";
        yield return "adminToken10";
        yield return "adminToken11";
        yield return "adminToken12";
        yield return "adminToken13";
    }

    [Benchmark]
    [ArgumentsSource(nameof(Numbers))]
    public string RunFromOld(IEnumerable<string> values)
    {
        return FromOld(values);
    }

    [Benchmark]
    [ArgumentsSource(nameof(Numbers))]
    public string RunFromNewNet8(IEnumerable<string> values)
    {
        return FromNewNet8(values);
    }

    [Benchmark]
    [ArgumentsSource(nameof(Numbers))]
    public string RunFromNewMain(IEnumerable<string> values)
    {
        return FromNewMain(values);
    }

    public static T FromOld<T>(IEnumerable<T> values)
    {
        return FromCore(values.ToArray().AsSpan());
    }

    public static T FromNewNet8<T>(IEnumerable<T> values)
    {
        List<T> list = new List<T>();
        IEnumerator<T> enumerator = values.GetEnumerator();
        try
        {
            while (enumerator.MoveNext())
            {
                T current = enumerator.Current;
                list.Add(current);
            }
        }
        finally
        {
            if (enumerator != null)
            {
                enumerator.Dispose();
            }
        }
        return FromCore(new Span<T>(list.ToArray()));
    }

    public static T FromNewMain<T>(IEnumerable<T> values)
    {
        List<T> list = new List<T>();
        list.AddRange(values);
        return FromCore(new Span<T>(list.ToArray()));
    }

    private static T FromCore<T>(Span<T> values)
    {
        if (values.IsEmpty)
        {
            ThrowArgumentEmptyException();
        }
        return values[Random.Shared.Next(0, values.Length)];
    }

    [DoesNotReturn]
    private static void ThrowArgumentEmptyException() => throw new ArgumentException("'options' cannot be empty", "options");
}
```

</details>

| Method         | values               | Mean      | Allocated |
|--------------- |--------------------- |----------:|----------:|
| RunFromOld     | Syste(...)ring] [48] |  29.17 ns |      56 B |
| RunFromNewNet8 | Syste(...)ring] [48] | 101.84 ns |     184 B |
| RunFromNewMain | Syste(...)ring] [48] |  65.35 ns |     144 B |
| RunFromOld     | String[12]           |  48.91 ns |     120 B |
| RunFromNewNet8 | String[12]           | 187.63 ns |     480 B |
| RunFromNewMain | String[12]           |  89.81 ns |     272 B |
| RunFromOld     | String[4]            |  35.01 ns |      56 B |
| RunFromNewNet8 | String[4]            |  85.19 ns |     176 B |
| RunFromNewMain | String[4]            |  69.62 ns |     144 B |
| RunFromOld     | Tests(...)>d__1 [25] | 212.73 ns |     384 B |
| RunFromNewNet8 | Tests(...)>d__1 [25] | 214.77 ns |     480 B |
| RunFromNewMain | Tests(...)>d__1 [25] | 231.45 ns |     480 B |

**Version Used**: 

.NET 8, as well as current main.

**Steps to Reproduce**:

[Sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4AEBMBGAsAKHQAYACdbAFgG4DizsA6AGVgEcb9bN6B2AgbwIlhZAMxkKJAGIAnAPZgA8gBsEAHgAqAPgAU5UZq0kAbhGUBXAKYBnAJRCRg/CJfT5YAMJyZlnaYs2DBpyAIIyMhAAnjq2DCHWAMoADhAwMbYcLgC+DsK5YhJuCgBylgDuhnrYBtomZlZ2+U6uIrIKXj46ANoMDHUB1gC6Gfk5nM4i6OLokm2e3paVyamG/Q32E8LNLSQA+iQAvGs2mSJjWUA=).

**Expected Behavior**:

Collection expressions are at least as fast as the old way.

**Actual Behavior**:

Collection expressions are can't keep up in terms of perf and memory allocations.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #71296
Closes #71755

Some of these issues also discuss optimization in cases when multiple spreads of unknown length are present in the collection-expr, such as `[..e1, e2, ..e3]` and so on. I am thinking we should just handle the single spread case `[..e]` for now as this is the source of majority of complaints. This is now handled by simply calling `System.Linq.Enumerable.ToArray<T>(IEnumerable<T>)` in most cases when the spread value is convertible to IEnumerable.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 1]
```diff
@@ -791,6 +821,17 @@ bool tryGetToArrayMethod(TypeSymbol spreadTypeOriginalDefinition, WellKnownType
                 arrayType);
         }
 
+        private bool IsConvertibleToObject(TypeSymbol type)
+        {
+            // conversion to 'object' will fail if, for example, 'arrayType.ElementType' is a pointer.
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:826]: >'arrayType.ElementType' [](http://example.com/codeflow?start=65&length=23)

`'type'`?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 2]
```diff
@@ -660,6 +659,15 @@ private BoundExpression CreateAndPopulateArray(BoundCollectionExpression node, A
                     var rewrittenSpreadExpression = VisitExpression(spreadExpression);
                     return _factory.Call(rewrittenSpreadExpression, listToArrayMethod.AsMember((NamedTypeSymbol)spreadExpression.Type!));
                 }
+                else if (IsConvertibleToObject(arrayType.ElementType)
+                    && _factory.WellKnownMethod(WellKnownMember.System_Linq_Enumerable__ToArray) is { } linqToArrayMethodGeneric)
+                {
+                    var linqToArrayMethod = linqToArrayMethodGeneric.Construct([arrayType.ElementTypeWithAnnotations]);
+                    if (ShouldUseAddRangeOrToListMethod(spreadExpression.Type!, linqToArrayMethod.Parameters[0].Type, spreadElement.EnumeratorInfoOpt?.GetEnumeratorInfo.Method))
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:666]: >ShouldUseAddRangeOrToListMethod [](http://example.com/codeflow?start=24&length=31)

Does this method need a more general name since this case is neither `AddRange()` nor `ToList()`?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 3]
```diff
@@ -660,6 +659,15 @@ private BoundExpression CreateAndPopulateArray(BoundCollectionExpression node, A
...
+                    {
+                        return _factory.Call(receiver: null, linqToArrayMethod, VisitExpression(spreadExpression));
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:668]: >VisitExpression [](http://example.com/codeflow?start=80&length=15)

Do we have a test case that fails if we don't rewrite `spreadExpression`?

File: src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionTests.cs [hunk 4]
```diff
@@ -35563,16 +35312,13 @@ .locals init (int[] V_0, //arr
...
-                  IL_0026:  stloc.1
-                  IL_0027:  ldloca.s   V_1
-                  IL_0029:  call       "int[] System.ReadOnlySpan<int>.ToArray()"
-                  IL_002e:  newobj     "System.Span<int>..ctor(int[])"
-                  IL_0033:  call       "System.ReadOnlySpan<int> System.Span<int>.op_Implicit(System.Span<int>)"
-                  IL_0038:  stloc.1
-                  IL_0039:  ldloca.s   V_1
-                  IL_003b:  call       "void CollectionExtensions.Report<int>(in System.ReadOnlySpan<int>)"
-                  IL_0040:  ret
+                  IL_0021:  call       "int[] System.Linq.Enumerable.ToArray<int>(System.Collections.Generic.IEnumerable<int>)"
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionTests.cs:35315]: >Enumerable.ToArray [](http://example.com/codeflow?start=58&length=18)

Are we testing missing `Enumerable.ToArray()`?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 5]
```diff
@@ -632,36 +647,37 @@ private static bool ShouldUseKnownLength(BoundCollectionExpression node, out int
             return false;
         }
 
-        /// <summary>
-        /// Create and populate an array from a collection expression where the
-        /// collection has a known length, although possibly including spreads.
-        /// </summary>
-        private BoundExpression CreateAndPopulateArray(BoundCollectionExpression node, ArrayTypeSymbol arrayType)
+        /// <summary>Attempt to optimize conversion of a single-spread collection expr to array, even if the spread length is not known.</summary>
+        private BoundExpression? TryOptimizeSingleSpreadToArray(BoundCollectionExpression node, ArrayTypeSymbol arrayType)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:651]: There's now 3 possible optimizations this method will try, in order:

1. List.ToArray if the spread value is a list
2. IEnumerable.ToArray if our checks say we should convert the spread value in this way
3. ReadOnlySpan.ToArray if we can convert the spread value to ReadOnlySpan

In my opinion this is the best order to try these, in part because IEnumerable.ToArray tends to produce less IL than the span conversions.

File: src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionTests.cs [hunk 6]
```diff
@@ -34985,53 +34816,347 @@ .locals init (int[] V_0,
...
                 class C
                 {
-                    static void Main()
-                    {
-                        int[] arr = [1, 2];
-                        arr.Report();
-                        int[] arr1 = [..arr, ..arr];
-                        arr1.Report();
-                    }
+                    public static object[] M(string[] arr) => [..arr];
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionTests.cs:34869]: >object[] [](http://example.com/codeflow?start=34&length=8)

Let's also test when the target type is `Span<object>`.

Comment (cston) [reply src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionTests.cs:34869]: Perhaps test the following cases:
```
string[] x = ["a"];
M1(x);
M2(x);
static Span<object> M1(string[] arr) => [..arr];
static Span<object> M2(object[] arr) => [..arr];
```

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:675]: Added test 'SingleSpread_ToArray_MustLowerSpreadOperand'.

File: src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionTests.cs [hunk 7]
```diff
@@ -34882,6 +34882,93 @@ .maxstack  1
...
         }
 
+        [Fact]
+        public void SingleSpread_ArrayToSpan_CovariantVersusInvariant()
+        {
+            var source = """
+                using System;
+
+                C.M1(["a"]);
+                C.M2(["b"]);
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionTests.cs:34892]: `["b"]` creates an `object[]` rather than a `string[]`. Consider rewriting as:
```
string[] s = ["a"];
C.M1(s);
C.M2(s);
```

**Review by cston — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@RikkiGibson It looks like #71755 is going to be partially addressed, but this PR is closing it. Do we have a different issue tracking the work for a more general case?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 8]
```diff
@@ -632,36 +647,37 @@ private static bool ShouldUseKnownLength(BoundCollectionExpression node, out int
...
+                if (spreadElementHasIdentityConversion
+                    && tryGetToArrayMethod(spreadTypeOriginalDefinition, WellKnownType.System_Collections_Generic_List_T, WellKnownMember.System_Collections_Generic_List_T__ToArray, out MethodSymbol? listToArrayMethod))
                 {
                     var rewrittenSpreadExpression = VisitExpression(spreadExpression);
                     return _factory.Call(rewrittenSpreadExpression, listToArrayMethod.AsMember((NamedTypeSymbol)spreadExpression.Type!));
                 }
 
-                if (TryGetSpanConversion(spreadExpression.Type, writableOnly: false, out var asSpanMethod))
+                // See if 'Enumerable.ToArray<T>(IEnumerable<T>)' will work, possibly due to a covariant conversion on the spread value.
+                if (IsConvertibleToObject(arrayType.ElementType)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:669]: >IsConvertibleToObject(arrayType.ElementType) [](http://example.com/codeflow?start=20&length=44)

What is the purpose of this check?

**Comment by AlekseyTs** [comment]
Done with review pass (commit 9)

**Comment by RikkiGibson** [comment]
> @RikkiGibson It looks like #71755 is going to be partially addressed, but this PR is closing it. Do we have a different issue tracking the work for a more general case?

Yes, I think #75863 represents the extent of the further improvement we could realistically make to the general case of #71755.

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs (hunk 5 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs:657]: Done

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs [hunk 9]
```diff
@@ -812,9 +861,7 @@ private bool TryGetSpanConversion(TypeSymbol type, bool writableOnly, out Method
             if (type is ArrayTypeSymbol { IsSZArray: true } arrayType
                 && _factory.WellKnownMethod(writableOnly ? WellKnownMember.System_Span_T__ctor_Array : WellKnownMember.System_ReadOnlySpan_T__ctor_Array, isOptional: true) is { } spanCtorArray)
             {
-                // conversion to 'object' will fail if, for example, 'arrayType.ElementType' is a pointer.
-                var useSiteInfo = CompoundUseSiteInfo<AssemblySymbol>.Discarded;
-                if (_compilation.Conversions.ClassifyConversionFromType(source: arrayType.ElementType, destination: _compilation.GetSpecialType(SpecialType.System_Object), isChecked: false, ref useSiteInfo).IsImplicit)
+                if (IsConvertibleToObject(arrayType.ElementType))
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CollectionExpression.cs]: Done

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 10)
