### PR TITLE
Code fix for CS1615 (Remove 'in' keyword)

### LINKED ISSUE #44187: Code fix for CS1615 (Remove 'in' keyword)
**Version Used**: 16.6 Preview 5

**Steps to Reproduce**:

```csharp
void M(int value) => throw null;

void N(int value)
{
  M(in value); // CS1615: Argument 1 may not be passed with the 'in' keyword
}
```

**Expected Behavior**:

A code fix is provided that offers to remove the `in` keyword.

🔗 Related to #23326

### PR DESCRIPTION
**Pull request by eugenesmlv**
Closes #44187 

I'm not sure about handling 'in' keyword's trivia. Should we keep it and prepend to the argument or just remove the keyword with its trivia?

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/Diagnostics/RemoveInKeyword/RemoveInKeywordCodeFixProviderTests.cs [hunk 1]
```diff
@@ -0,0 +1,244 @@
...
+        M2(in i, s);
+    }
+
+    void N3(int i, string s)
+    {
+        M1(i);
+        M2(in i, s);
+    }
+}");
+        }
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Diagnostics/RemoveInKeyword/RemoveInKeywordCodeFixProviderTests.cs:242]: do we have negative tests showing we don't remove `in` when it should be kept around?

File: src/Features/CSharp/Portable/CSharpFeaturesResources.resx [hunk 2]
```diff
@@ -621,4 +621,7 @@
     <value>Apply preferred 'using' placement preferences</value>
     <comment>'using' is a C# keyword and should not be localized</comment>
   </data>
+  <data name="Remove_in_keyword" xml:space="preserve">
+    <value>Remove 'in' keyword</value>
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CSharpFeaturesResources.resx:625]: check out the other resource strings.  There should be a way to mark `in` as `locked`.  this will tell the loc team to not localize that word when they do the different languages.

File: src/Features/CSharp/Portable/CodeFixes/RemoveInKeyword/RemoveInKeywordCodeFixProvider.cs [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+            var diagnostic = context.Diagnostics.First();
+            var diagnosticSpan = diagnostic.Location.SourceSpan;
+
+            var token = root.FindToken(diagnosticSpan.Start);
+
+            var argumentSyntax = token.GetAncestor<ArgumentSyntax>();
+            if (argumentSyntax == null || argumentSyntax.GetRefKind() != RefKind.In)
+                return;
+
+            var generator = context.Document.GetRequiredLanguageService<SyntaxGenerator>();
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeFixes/RemoveInKeyword/RemoveInKeywordCodeFixProvider.cs:50]: remove this line.  you can get the generation inside FixAsync.

File: src/EditorFeatures/CSharpTest/Diagnostics/RemoveInKeyword/RemoveInKeywordCodeFixProviderTests.cs (hunk 1 above)
Comment (eugenesmlv) [reply src/EditorFeatures/CSharpTest/Diagnostics/RemoveInKeyword/RemoveInKeywordCodeFixProviderTests.cs:242]: Something like `M2` method in this case?
https://github.com/dotnet/roslyn/blob/4f7211b80ba975aea4d0d9504aa82d9fd138d1d3/src/EditorFeatures/CSharpTest/Diagnostics/RemoveInKeyword/RemoveInKeywordCodeFixProviderTests.cs#L200-L220
Or do you mean it would be nice to add more tests for that particular case?

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/Diagnostics/RemoveInKeyword/RemoveInKeywordCodeFixProviderTests.cs:242]: i'd like a test htat purely verifies the negative scenario and nothing else :)

Comment (eugenesmlv) [reply src/EditorFeatures/CSharpTest/Diagnostics/RemoveInKeyword/RemoveInKeywordCodeFixProviderTests.cs:256]: Added :)

**Comment by CyrusNajmabadi** [comment]
@eugenesmlv Is this ready for a final review?

**Comment by eugenesmlv** [comment]
Yes, it is.

**Comment by CyrusNajmabadi** [comment]
Thanks!
