### PR TITLE
Fixes binder-choosing around typeof expressions

### LINKED ISSUE #5170: Assert failure from MemberSemanticModel.GetLambdaParameterSymbol
Split bug 2 of 2 from #4918

```C#
using System.Linq;
using System.Text;

public static class LazyToStringExtension
{
    public static string LazyToString<T>(this T obj) where T : class
    {
        StringBuilder sb = new StringBuilder();
        typeof(T)
            .GetProperties(System.Reflection.BindingFlags.Public)
            .Select($$x => x.GetValue(obj))
    }
}
```
With caret at `$$`, either to the left or right of `x`, we get an assert failure.

~~~
Debug.Assert(this.GetMemberModel(lambda) == null,  "Did not find a 
unique LambdaSymbol for lambda in member.");
~~~

 ~~~	
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLambdaParameterSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.ParameterSyntax parameter, Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax lambda, System.Threading.CancellationToken cancellationToken) Line 598	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLambdaParameterSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.ParameterSyntax parameter, System.Threading.CancellationToken cancellationToken) Line 558	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetDeclaredSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.ParameterSyntax declarationSyntax, System.Threading.CancellationToken cancellationToken) Line 540	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDeclaredSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.ParameterSyntax declarationSyntax, System.Threading.CancellationToken cancellationToken) Line 1813	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetDeclaredSymbolCore(Microsoft.CodeAnalysis.SyntaxNode declaration, System.Threading.CancellationToken cancellationToken) Line 4469	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.SemanticModel.GetDeclaredSymbolForNode(Microsoft.CodeAnalysis.SyntaxNode declaration, System.Threading.CancellationToken cancellationToken) Line 358	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.ModelExtensions.GetDeclaredSymbol(Microsoft.CodeAnalysis.SemanticModel semanticModel, Microsoft.CodeAnalysis.SyntaxNode declaration, System.Threading.CancellationToken cancellationToken) Line 135	C#
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.CSharpSemanticFactsService.GetDeclaredSymbol.AnonymousMethod__0(Microsoft.CodeAnalysis.SyntaxNode node) Line 130	C#
 	System.Core.dll!System.Linq.Enumerable.WhereSelectEnumerableIterator<Microsoft.CodeAnalysis.SyntaxNode, <>f__AnonymousType3<Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.ISymbol>>.MoveNext() Line 285	C#
 	System.Core.dll!System.Linq.Enumerable.WhereSelectEnumerableIterator<<>f__AnonymousType3<Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.ISymbol>, Microsoft.CodeAnalysis.ISymbol>.MoveNext() Line 282	C#
 	System.Core.dll!System.Linq.Enumerable.FirstOrDefault<Microsoft.CodeAnalysis.ISymbol>(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.ISymbol> source) Line 950	C#
 	Microsoft.CodeAnalysis.CSharp.Workspaces.dll!Microsoft.CodeAnalysis.CSharp.CSharpSemanticFactsService.GetDeclaredSymbol(Microsoft.CodeAnalysis.SemanticModel semanticModel, Microsoft.CodeAnalysis.SyntaxToken token, System.Threading.CancellationToken cancellationToken) Line 134	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Shared.Extensions.SemanticModelExtensions.GetSymbolsEnumerable(Microsoft.CodeAnalysis.SemanticModel semanticModel, Microsoft.CodeAnalysis.LanguageServices.ISemanticFactsService semanticFacts, Microsoft.CodeAnalysis.LanguageServices.ISyntaxFactsService syntaxFacts, Microsoft.CodeAnalysis.SyntaxToken token, bool bindLiteralsToUnderlyingType, System.Threading.CancellationToken cancellationToken) Line 112	C#
 	System.Core.dll!System.Linq.Enumerable.WhereSelectEnumerableIterator<Microsoft.CodeAnalysis.ISymbol, Microsoft.CodeAnalysis.ISymbol>.MoveNext() Line 282	C#
 	System.Core.dll!System.Linq.Enumerable.FirstOrDefault<Microsoft.CodeAnalysis.ISymbol>(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.ISymbol> source) Line 950	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindSymbolAtPosition(Microsoft.CodeAnalysis.SemanticModel semanticModel, int position, Microsoft.CodeAnalysis.Workspace workspace, bool bindLiteralsToUnderlyingType, System.Threading.CancellationToken cancellationToken) Line 48	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.FindSymbols.SymbolFinder.FindSymbolAtPosition(Microsoft.CodeAnalysis.SemanticModel semanticModel, int position, Microsoft.CodeAnalysis.Workspace workspace, System.Threading.CancellationToken cancellationToken) Line 30	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.ReferenceHighlighting.AbstractDocumentHighlightsService.GetDocumentHighlightsAsync(Microsoft.CodeAnalysis.Document document, int position, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Document> documentsToSearch, System.Threading.CancellationToken cancellationToken) Line 25	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.ReferenceHighlighting.ReferenceHighlightingViewTaggerProvider.ProduceTagsAsync(Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext<Microsoft.CodeAnalysis.Editor.Shared.Tagging.NavigableHighlightTag> context, Microsoft.VisualStudio.Text.SnapshotPoint position, Microsoft.CodeAnalysis.Workspace workspace, Microsoft.CodeAnalysis.Document document) Line 139	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.ReferenceHighlighting.ReferenceHighlightingViewTaggerProvider.ProduceTagsAsync(Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext<Microsoft.CodeAnalysis.Editor.Shared.Tagging.NavigableHighlightTag> context) Line 114	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider<Microsoft.CodeAnalysis.Editor.Shared.Tagging.NavigableHighlightTag>.TagSource.ProduceTagsAsync(Microsoft.CodeAnalysis.Editor.Tagging.TaggerContext<Microsoft.CodeAnalysis.Editor.Shared.Tagging.NavigableHighlightTag> context) Line 570	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider<Microsoft.CodeAnalysis.Editor.Shared.Tagging.NavigableHighlightTag>.TagSource.RecomputeTagsAsync(object oldState, Microsoft.VisualStudio.Text.SnapshotPoint? caretPosition, Microsoft.CodeAnalysis.Text.TextChangeRange? textChangeRange, System.Collections.Generic.List<Microsoft.CodeAnalysis.Editor.DocumentSnapshotSpan> spansToTag, System.Collections.Immutable.ImmutableDictionary<Microsoft.VisualStudio.Text.ITextBuffer, Microsoft.CodeAnalysis.Editor.Shared.Tagging.TagSpanIntervalTree<Microsoft.CodeAnalysis.Editor.Shared.Tagging.NavigableHighlightTag>> oldTagTrees, System.Threading.CancellationToken cancellationToken) Line 553	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Tagging.AbstractAsynchronousTaggerProvider<Microsoft.CodeAnalysis.Editor.Shared.Tagging.NavigableHighlightTag>.TagSource.RecomputeTagsForeground.AnonymousMethod__0(System.Threading.CancellationToken ct) Line 294	C#
~~~

### PR DESCRIPTION
**Pull request by TyOverby**
Closes #5170

Previously, it was possible for the semantic model to think
that you were *inside* of a typeof when you were merely near it.

This commit adds an additional check that the cursor position is
actually inside of the parenthesis that make up the typeof
invocation.

### CODE REVIEW

**Comment by TyOverby** [comment]
CC: @dotnet/roslyn-compiler 

@AlekseyTs: Thanks for all the help!

**Comment by gafter** [comment]
:+1:

File: src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs [hunk 1]
```diff
@@ -199,8 +199,19 @@ private Binder GetEnclosingBinder(CSharpSyntaxNode node, int position)
...
+                    var currentTypeofExpr = (TypeOfExpressionSyntax)current;
+
+                    // A span that contains everything inbetween the parenthesis in a typeof expression.
+                    // typeof   (    ThisIsAType       )
+                    //           |--------------------|
+                    var insideParensSpan = TextSpan.FromBounds(
+                        currentTypeofExpr.OpenParenToken.Span.Start + 1,
+                        currentTypeofExpr.CloseParenToken.Span.End);
+
+                    if (insideParensSpan.Contains(position)) {
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs]: Nit: braces on separate lines

**Comment by jaredpar** [comment]
:+1:  modula minor formatting issue.

File: src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs (hunk 1 above)
Comment (TyOverby) [inline src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs]: Reviewers: This check should in theory be a part of the `else if` directly above.  However, I avoided it for style reasons.  This means that the Debug.Assert(..) call in the `else` case doesn't execute.  Should this code:

1. Be moved entirely into the `else if`
2. Put the span up above the whole `if` chain
3. Keep as-is but with an extra Debug.Assert
4. Just keep as-is

**Comment by TyOverby** [comment]
@jaredpar I added a note in the source code.  Could you take a look at that and give advice before I merge?

File: src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs (hunk 1 above)
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs]: I tend to favor option 3

File: src/Compilers/CSharp/Test/Semantic/Semantics/BindingTests.cs [hunk 2]
```diff
@@ -2692,5 +2692,40 @@ public class B<T>
             Assert.Equal("void NS.A.B<System.String>.M1<System.String>()", m1Symbol.Symbol.ToTestDisplayString());
             Assert.Equal(CandidateReason.None, m1Symbol.CandidateReason);
         }
+
+        [Fact, WorkItem(5170, "https://github.com/dotnet/roslyn/issues/5170")]
+        public void GetLambdaParameterSymbolBug() // TODO: rename once you figure out what's going on
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/BindingTests.cs]: TODO?

File: src/Compilers/CSharp/Test/Semantic/Semantics/BindingTests.cs [hunk 3]
```diff
@@ -2692,5 +2692,40 @@ public class B<T>
...
+                //             .Select(x => x.GetValue(obj))
+                Diagnostic(ErrorCode.ERR_BadArgCount, "GetValue").WithArguments("GetValue", "1").WithLocation(12, 28),
+                // (7,26): error CS0161: 'LazyToStringExtension.LazyToString<T>(T)': not all code paths return a value
+                //     public static string LazyToString<T>(this T obj) where T : class
+                Diagnostic(ErrorCode.ERR_ReturnExpected, "LazyToString").WithArguments("LazyToStringExtension.LazyToString<T>(T)").WithLocation(7, 26));
+            var tree = compilation.SyntaxTrees[0];
+            var model = compilation.GetSemanticModel(tree);
+            var node = tree.GetRoot().DescendantNodes().Where(n => n.IsKind(SyntaxKind.SimpleLambdaExpression)).Single();
+            var param = node.ChildNodes().Where(n => n.IsKind(SyntaxKind.Parameter)).Single();
+            model.GetDeclaredSymbol(param);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/BindingTests.cs]: Assert what you get back, make sure this is what you expect

File: src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs]: Consider using LookupPosition.IsBetweenTokens helper instead.

**Comment by VSadov** [comment]
LGTM

**Comment by AlekseyTs** [comment]
LGTM
