### PR TITLE
Bug fixes in SwitchStatementHighlighter

### LINKED ISSUE #25039: Bugs in SwitchStatementHighlighter
#### 1. It highlights unrelated goto statements

```c#
class C
{
    void M()
    {
        unrelated:
        switch (true)
        {
            case true:
                goto case true;
                goto unrelated;
        }
    }
}
```
Click on switch. Second goto is highlighted. It shouldn't be.

#### 2. It doesn't highlight nested break/goto statements.
```c#
class C
{
    void M()
    {
        switch (true)
        {
            default:
            case true:
                if (true)
                {
                    break;
                    goto case true;
                    goto default;
                }
                break;
                goto case true;
                goto default;
        }
    }
}
```
Click on switch. Top-level break/goto get highlighted, but not those inside the if statement.

### PR DESCRIPTION
**Pull request by Neme12**
fixes #25039

### CODE REVIEW

**Comment by Neme12** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please

File: src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs [hunk 1]
```diff
@@ -26,12 +27,14 @@ internal class SwitchStatementHighlighter : AbstractKeywordHighlighter<SwitchSta
...
                     spans.Add(label.Keyword.Span);
                     spans.Add(EmptySpan(label.ColonToken.Span.End));
-                }
 
-                foreach (var statement in switchSection.Statements)
-                {
-                    HighlightRelatedKeywords(statement, spans);
+                    if (label is CasePatternSwitchLabelSyntax patternLabel && patternLabel.WhenClause != null)
+                    {
+                        spans.Add(patternLabel.WhenClause.WhenKeyword.Span);
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs]: not sure highlighting these is what we want.

File: src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs [hunk 2]
```diff
@@ -26,12 +27,14 @@ internal class SwitchStatementHighlighter : AbstractKeywordHighlighter<SwitchSta
...
+                    }
                 }
+
+                HighlightRelatedKeywords(switchSection, spans, true, true);
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs]: named parameters for contants.

File: src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs (hunk 1 above)
Comment (Neme12) [reply src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs]: i noticed that `when` is highlighted on catch clauses and though it would be appropriate for consistency to have that here as well... but i can remove it

File: src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs [hunk 3]
```diff
@@ -41,35 +44,39 @@ internal class SwitchStatementHighlighter : AbstractKeywordHighlighter<SwitchSta
...
-                    var end = !gotoStatement.CaseOrDefaultKeyword.IsKind(SyntaxKind.None)
-                        ? gotoStatement.CaseOrDefaultKeyword.Span.End
-                        : gotoStatement.GotoKeyword.Span.End;
+            if (highlightBreaks && node is BreakStatementSyntax breakStatement)
+            {
+                spans.Add(breakStatement.BreakKeyword.Span);
+                spans.Add(EmptySpan(breakStatement.SemicolonToken.Span.End));
+            }
+            else if (highlightGotos && node is GotoStatementSyntax gotoStatement
+                && (!gotoStatement.IsKind(SyntaxKind.GotoStatement) || gotoStatement.Expression.IsMissing))
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs]: this expression is too hard to read.  Please take the ``` && (!gotoStatement.IsKind(SyntaxKind.GotoStatement) || gotoStatement.Expression.IsMissing))``` part out of the else-if clause and just do the test inside the block body.  Also, document what this code is trying to accomplish.

**Comment by CyrusNajmabadi** [comment]
Done with pass.

File: src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs (hunk 2 above)
Comment (Neme12) [reply src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs]: similar code is in https://github.com/dotnet/roslyn/blob/6847f1e5a909395aae9456e8f366cbf4deb86b69/src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/LoopHighlighter.cs#L57 fix it there as well?

File: src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs]: Gotcha.  I don't think it's a good idea for either TBH :)   THe purpose of this highlighting is to quickly help jump between the relation between  constructs that can be far apart.  i.e. "this case belongs to thsi switch" (and vice versa).  i don't see the same need for 'when' given that it's much more tightly associated with a 'case' clause making it obvious what the relation is.

File: src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs (hunk 2 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs]: Yes please.

File: src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs (hunk 1 above)
Comment (Neme12) [reply src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs]: so should i just remove it?

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs]: My personal preference would be that it was not added as i don't think it adds value, or fits into the goals of the keyword highlighting feature.  You can ping @dotnet/roslyn-ide  for more minds on this if you feel strongly like this should stay.

File: src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs [hunk 4]
```diff
@@ -41,35 +44,39 @@ internal class SwitchStatementHighlighter : AbstractKeywordHighlighter<SwitchSta
...
-                    spans.Add(EmptySpan(breakStatement.SemicolonToken.Span.End));
-                    break;
+            Debug.Assert(highlightBreaks || highlightGotos);
 
-                case GotoStatementSyntax gotoStatement:
-                    var start = gotoStatement.GotoKeyword.SpanStart;
-                    var end = !gotoStatement.CaseOrDefaultKeyword.IsKind(SyntaxKind.None)
-                        ? gotoStatement.CaseOrDefaultKeyword.Span.End
-                        : gotoStatement.GotoKeyword.Span.End;
+            if (highlightBreaks && node is BreakStatementSyntax breakStatement)
```
Comment (Neme12) [inline src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs]: I thought about keeping this as a switch with highlightBreaks inside `when` (and doing the same in LoopHighlighter).. not sure if that would be the best thing to do here but at least i'd be dogfooding my own highlighting :D

File: src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs (hunk 3 above)
Comment (Neme12) [reply src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs]: fixed

**Comment by Neme12** [comment]
@dotnet-bot retest ubuntu_16_mono_debug_prtest please

File: src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs (hunk 1 above)
Comment (jasonmalinowski) [reply src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs]: Note that "jump between constructs far apart" is already somewhat broken: we would highlight breaks inside of a case, which means you might have to an arbitrary number of jumps to get around. I think this is fine, especially because we already do it in other places.

**Comment by Neme12** [comment]
@dotnet-bot retest ubuntu_16_mono_debug_prtest please

File: src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs (hunk 1 above)
Comment (Neme12) [reply src/EditorFeatures/CSharp/Highlighting/KeywordHighlighters/SwitchStatementHighlighter.cs]: removed

**Comment by Neme12** [comment]
retest windows_coreclr_debug_prtest please

**Comment by DustinCampbell** [comment]
@dotnet-bot retest this please

**Comment by Neme12** [comment]
Thanks, I just checked this out locally and fixed a real build issue.

**Comment by Neme12** [comment]
@DustinCampbell It looks like everything is passing now.

**Comment by DustinCampbell** [comment]
Yup! Thanks for your contributions!
