### PR TITLE
Fix obsolete warning for delegate creation

### LINKED ISSUE #47308: Obsolete diagnostics not reported for delegate creation
```
using System;
public class C {
    [Obsolete]
    public void M() {
    }
    
    void M2()
    {
        Action a = M; // Diagnostic reported
        a = new Action(M); // No diagnostic reported
    }
}
```

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #47308

### CODE REVIEW

**Comment by Youssef1313** [comment]
The approach I took doesn't seem to work, and also it's very bad even if it works.
But going to mark as ready for review as I'm stuck here.

**Comment by 333fred** [comment]
I believe you'll want to make a similar change to what I'm doing here: https://github.com/dotnet/roslyn/pull/47311/files#diff-098c83159f29ad4768223015c6455902R1123. I'd prefer if we put this PR on hold until after the `UnmanagedCallersOnly` stuff is merged to prevent conflicts though, if you don't mind :).

We'll also need to update https://github.com/dotnet/roslyn/blob/master/docs/compilers/CSharp/Compiler%20Breaking%20Changes%20-%20post%20VS2019.md, and I'm going to send an email to the compat council to see if this is a break that we'd accept.

**Comment by 333fred** [comment]
Alright @YairHalberstadt, it seems like this is a change we'd accept. Feel free to continue working on it.

**Comment by YairHalberstadt** [comment]
Did you mean @Youssef1313?

**Comment by 333fred** [comment]
I did, sorry Yair :sweat_smile:

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs [hunk 1]
```diff
@@ -65,6 +66,12 @@ internal partial class Binder
             RoslynDebug.Assert((object)destination != null);
             RoslynDebug.Assert(!isCast || conversionGroupOpt != null);
 
+            if (source is BoundDelegateCreationExpression delegateCreationExpression &&
+                delegateCreationExpression.MethodOpt is not null)
+            {
+                ReportDiagnosticsIfObsolete(diagnostics, delegateCreationExpression.MethodOpt, delegateCreationExpression.Argument.Syntax, hasBaseReceiver: false);
+            }
```
Comment (Youssef1313) [inline src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:73]: @333fred I'm unsure of this is how you'd prefer to fix that. Can you take a look?

Comment (333fred) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:73]: I believe it would be better to put this check in `MethodGroupConversionHasErrors`, like the change to report UnmanagedCallersOnly errors.

---
In reply to: [490915535](https://github.com/dotnet/roslyn/pull/47332#discussion_r490915535) [](ancestors = 490915535)

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs [hunk 2]
```diff
@@ -85,13 +85,13 @@ internal partial class Binder
...
             }
 
-            ReportDiagnosticsIfObsolete(diagnostics, conversion, syntax, hasBaseReceiver: false);
-
             if (conversion.IsMethodGroup)
             {
                 return CreateMethodGroupConversion(syntax, source, conversion, isCast: isCast, conversionGroupOpt, destination, diagnostics);
             }
 
+            ReportDiagnosticsIfObsolete(diagnostics, conversion, syntax, hasBaseReceiver: false);
```
Comment (Youssef1313) [inline src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:93]: I moved this from line 88 to 93 to avoid repeated diagnostic.

Comment (333fred) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:93]: Moving to here is fine. We should leave it though, because there could be some other user-defined conversion operator involved that doesn't have anything to do with a method group. Please do add a comment to mention that obsolete diagnostics are reported as part of creating the method group conversion though.

---
In reply to: [491224318](https://github.com/dotnet/roslyn/pull/47332#discussion_r491224318) [](ancestors = 491224318)

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:93]:
```suggestion
            // Obsolete diagnostics for method group are reported as part of creating the method group conversion.
            ReportDiagnosticsIfObsolete(diagnostics, conversion, syntax, hasBaseReceiver: false);
```

**Review by 333fred — APPROVED** [review]
LGTM (commit 8). @dotnet/roslyn-compiler for a second review of this community PR please.

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs [hunk 3]
```diff
@@ -1119,7 +1120,7 @@ static ErrorCode getRefMismatchErrorCode(TypeKind type)
             }
 
             ReportDiagnosticsIfUnmanagedCallersOnly(diagnostics, selectedMethod, location, isDelegateConversion: true);
-
+            ReportDiagnosticsIfObsolete(diagnostics, selectedMethod, syntax, hasBaseReceiver: false);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:1123]: >ReportDiagnosticsIfObsolete [](start = 12, length = 27)

Should this check occur before the unsafe checks above? For instance, are we reporting an obsolete error for `M1()` below?
```C#
using System;
unsafe delegate byte* D();
class C
{
    [Obsolete(null, true)] unsafe static byte* F() => default;
    unsafe static D M1() => new D(F);
    static D M2() => new D(F);
}
```

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:1123]: I don't think the warning is currently reported if unsafe not allowed error is reported. This should apply to UnmanagedCallersOnly warnings too.

I'll move both of them.

File: src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests.cs [hunk 4]
```diff
@@ -9110,6 +9110,54 @@ public class C2
...
+            string source = @"
+using System;
+unsafe delegate byte* D();
+class C
+{
+    [Obsolete(null, true)] unsafe static byte* F() => default;
+    unsafe static D M1() => new D(F);
+    static D M2() => new D(F);
+}";
+            var comp = CreateCompilation(source);
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests.cs:9156]: >) [](start = 47, length = 1)

`options: TestOptions.UnsafeReleaseDll`

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs [hunk 5]
```diff
@@ -1093,6 +1094,14 @@ static ErrorCode getRefMismatchErrorCode(TypeKind type)
             MethodSymbol selectedMethod = conversion.Method;
 
             var location = syntax.Location;
+
+            if (!isAddressOf)
+            {
+                ReportDiagnosticsIfUnmanagedCallersOnly(diagnostics, selectedMethod, location, isDelegateConversion: true);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:1100]: >ReportDiagnosticsIfUnmanagedCallersOnly [](start = 16, length = 39)

If we're moving the call to `ReportDiagnosticsIfUnmanagedCallersOnly()`, we should have a test that covers the change in behavior.

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs [hunk 6]
```diff
@@ -1093,6 +1094,14 @@ static ErrorCode getRefMismatchErrorCode(TypeKind type)
             MethodSymbol selectedMethod = conversion.Method;
 
             var location = syntax.Location;
+
+            if (!isAddressOf)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:1098]: >if (!isAddressOf) [](start = 12, length = 17)

Moving this entire block to the start of this method seems unnecessary. It might result in additional diagnostics for scenarios where we already report errors. But unless this catches error cases that previously compiled without errors, we should avoid changing the set of diagnostics reported.

Consider moving immediately above the `if (selectedMethod.HasUnsafeParameter ...) { ... }` block instead.

Comment (333fred) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: I believe we did have a bug here with `UnmanagedCallersOnly` verification, but I think we should be consistent about reporting cascaded attributes. Either we should always report `UnmanagedCallersOnly` and `Obsolete` with the other errors, or we should never do so. Consider instead a structure like this:
```cs
if ((selectedMethod.HasUnsafeParameter() || selectedMethod.ReturnType.IsUnsafe()) && ReportUnsafeIfNotAllowed(syntax, diagnostics))
{
    return true;
}

if (!isAddressOf)
{
    ReportDiagnosticsIfUnmanagedCallersOnly(diagnostics, selectedMethod, location, isDelegateConversion: true);
}
ReportDiagnosticsIfObsolete(diagnostics, selectedMethod, syntax, hasBaseReceiver: false);
```

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs (hunk 5 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: An example test:
```C#
using System.Runtime.InteropServices;
unsafe delegate byte* D();
class C
{
    [UnmanagedCallersOnly]
    unsafe static byte* F() => default;
    unsafe static D M1() => new D(F);
    static D M2() => new D(F);
}
```

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs (hunk 6 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: @333fred With this structure, the `Obsolete` and `UnmanagedCallersOnly` warnings won't be reported if unsafe errors are reported. I think it's better if the warning existed with the error.

Comment (333fred) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: > With this structure, the Obsolete and UnmanagedCallersOnly warnings won't be reported if unsafe errors are reported. I think it's better if the warning existed with the error.

This is correct. IMO, we should be consistent and either always report Obsolete/UnmanagedCallersOnly (ie, moving this to the front of the method), or only every report these errors when there are no others (ie, moving them to the bottom). Currently, we're just inconsistent, sometimes reporting these errors when other errors are present, and sometimes not.

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: @333fred I currently have both of them together with before the unsafe checks

Comment (333fred) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: > @333fred I currently have both of them together with before the unsafe checks

I understand. And that behavior is the inconsistent behavior I'm talking about. We should either always report these, no matter what other errors might be reported, or only report these when there are no other errors.

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: @333fred Got it. I thought they were always reported.

Should I move the warnings check above just above the following IsConditional check, so they'are always reported?

```
           if (selectedMethod.IsConditional)
            {
                // CS1618: Cannot create delegate with '{0}' because it has a Conditional attribute
                Error(diagnostics, ErrorCode.ERR_DelegateOnConditional, location, selectedMethod);
                return true;
            }

Comment (333fred) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: @cston preferred to have this not be reported if other errors are reported, so I'll defer to his preference. Let's move this to the end of the method, only reported if no other errors are reported.

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: @333fred The checks were originally at the end of the method. I moved them based on @cston's comment (https://github.com/dotnet/roslyn/pull/47332#discussion_r492318014)

Comment (333fred) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: I'm aware. That comment was about a bug in the unsafe reporting logic. With the suggested code I gave [here](https://github.com/dotnet/roslyn/pull/47332#discussion_r492366626), that is no longer an issue.

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs [hunk 7]
```diff
@@ -1114,15 +1115,16 @@ static ErrorCode getRefMismatchErrorCode(TypeKind type)
...
             }
 
-            if (selectedMethod.HasUnsafeParameter() || selectedMethod.ReturnType.IsUnsafe())
+            if ((selectedMethod.HasUnsafeParameter() || selectedMethod.ReturnType.IsUnsafe()) && ReportUnsafeIfNotAllowed(syntax, diagnostics))
             {
-                return ReportUnsafeIfNotAllowed(syntax, diagnostics);
+                return true;
             }
-
+
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:1122]:
```suggestion

```
Correctness is probably complaining about these spaces

**Review by 333fred — APPROVED** [review]
LGTM (commit 17), other than the whitespace

**Comment by 333fred** [comment]
Just in case, I'm going to do a test VS insertion with this change and see if it breaks anything horribly.

**Comment by 333fred** [comment]
Test insertion (Microsoft-internal accessible only) https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/277471

**Comment by 333fred** [comment]
We've had some infrastructure fires over the past week, so I'm redoing my smoke test. Will update when it's done.

**Comment by Youssef1313** [comment]
@333fred I'm not sure what the couple of previous comments mean

**Comment by 333fred** [comment]
Nothing you need to do. I'm testing to make sure that this doesn't break the VS build.

**Comment by 333fred** [comment]
Alright, just did another test build and VS continues to work correctly: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/279194. @jaredpar, I'd like sign off from you on this change before I merge.

**Comment by 333fred** [comment]
Talked with Jared offline, we're good.

**Comment by 333fred** [comment]
Thanks @Youssef1313!
