### PR TITLE
Adjust design behind Nullable analysis for target-typed expressions and add handling for target-typed new.

### LINKED ISSUE #49736: Target-typed new expressions don't update their types with nullability
**Version Used**: 
```
Branch master (1 Dec 2020)
Latest commit 195cc4b by Manish Vasani:
Merge pull request #49120 from huoyaoyuan/foreach-var

Do not cast when refactoring 'foreach var'
```

**Steps to Reproduce**:

```
#nullable enable
string? s = null;
s = "";
var c = GetC(s);
c = new(null);
c.field.ToString();

static C<T> GetC<T>(T t) => new C<T>(t);

class C<T>
{
  public T field;
  public C(T t) => field = t;
}
```

**Expected Behavior**:
Warning for `new(null)`. The target type is `C<string>` with non-nullable string and the argument of the constructor is not nullable

**Actual Behavior**:
No warnings. The program crashes at runtime with `NullReferenceException`

### LINKED ISSUE #58369: NullableWalker: operator inference shouldn't infer from target typed conditional expresion
```
#nullable enable

#pragma warning disable CS0164
class C<T>
{
    static void M2(bool b, string? s)
    {
WarnHere:   _ = C.GetCT(s) + (b ? new C1() : new C2());
ButNotHere: _ = (b ? new C3() : new C4()) + C.GetCT(s);
    }
    
    public static C<T> operator + (C<T> x, C<T> y)
    {
        throw null!;
    }
}

class C
{
    public static C<T> GetCT<T>(T x) => new C<T>(); 
}

class C1 : C<string> {}
class C2 : C<string> {}
class C3 : C<string> {}
class C4 : C<string> {}
```

Observed warnings only on "WarnHere" line:
```
warning CS8619: Nullability of reference types in value of type 'C1' doesn't match target type 'C<string?>'.
warning CS8619: Nullability of reference types in value of type 'C2' doesn't match target type 'C<string?>'.
```

Expected similar warnings on the "ButNotHere" line.

### PR DESCRIPTION
**Pull request by AlekseyTs**
With the new approach the analysis steps that should be completed later, when the target type with all nullability information becomes known, are stored in a map as a delegate. The delegate is invoked by `VisitConversion` and completes the analysis.

The implementation is intentionally carefully structured in such a way that it avoids code duplication and deviations between regular analysis and target-typed analysis . Helper functions are either executed normally for a non-target-typed scenario, or are folded into the final completion as delegates. Effectively the final completion delegate is a composition of delegates.

This change also creates a BoundConversion node for successful target-typed new conversions. Here is the quote from ([https://github.com/dotnet/csharplang/blob/main/proposals/csharp-9.0/target-typed-new.md#specification](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-9.0/target-typed-new.md#specification)): "**there is a new object creation conversion that is an implicit conversion from expression**, that exists from a target_typed_new to every type." Presence of this node simplifies Nullable analysis.

Fixes #49736.
Fixes #58369.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs [hunk 1]
```diff
@@ -336,65 +328,67 @@ internal void CheckConstraintLanguageVersionAndRuntimeSupportForConversion(Synta
...
-                    type: destination);
+            BoundExpression expr = bindObjectCreationExpression(node, destination.StrippedType(), arguments, diagnostics);
+            arguments.Free();
+
+            Debug.Assert(expr is BoundObjectCreationExpressionBase { WasTargetTyped: true } or
+                                 BoundDelegateCreationExpression { WasTargetTyped: true } or
+                                 BoundBadExpression);
 
-                diagnostics.Add(syntax, useSiteInfo);
+            Debug.Assert(expr is not BoundBadExpression { ChildBoundNodes: var children } || !children.Any((child, node) => child.Syntax == node.Syntax, node));
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:343]: >(child, node) => child.Syntax == node.Syntax, node [](http://example.com/codeflow?start=107&length=50)

What in particular is bad about violating this? Is this IOperation related? Consider adding a comment for clarification.

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs [hunk 2]
```diff
@@ -336,65 +328,67 @@ internal void CheckConstraintLanguageVersionAndRuntimeSupportForConversion(Synta
...
+            {
+                expr.MakeCompilerGenerated();
             }
-            arguments.Free();
+
+            expr = new BoundConversion(
+                                  syntax,
+                                  expr,
+                                  expr is BoundBadExpression ? Conversion.NoConversion : conversion,
+                                  CheckOverflowAtRuntime,
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:354]: >CheckOverflowAtRuntime [](http://example.com/codeflow?start=34&length=22)

Is there a test covering this change?

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 3]
```diff
@@ -4202,65 +4202,74 @@ private BoundExpression BindImplicitObjectCreationExpression(ImplicitObjectCreat
...
-            var typeWithAnnotations = BindType(node.Type, diagnostics);
-            var type = typeWithAnnotations.Type;
-            var originalType = type;
+            BoundExpression result = bindObjectCreationExpression(node, diagnostics);
 
-            if (typeWithAnnotations.NullableAnnotation.IsAnnotated() && !type.IsNullableType())
-            {
-                diagnostics.Add(ErrorCode.ERR_AnnotationDisallowedInObjectCreation, node.Location, type);
-            }
+            Debug.Assert(result is not BoundBadExpression { ChildBoundNodes: var children } || !children.Any((child, node) => child.Syntax == node, node));
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:4207]: >result is not BoundBadExpression { ChildBoundNodes: var children } || !children.Any((child, node) => child.Syntax == node, node) [](http://example.com/codeflow?start=25&length=128)

Since we're using this assertion twice, should we perhaps make it a conditional method that more explicitily elaborates what the condition violation breaks?

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 4]
```diff
@@ -5354,7 +5364,8 @@ private bool IsConstructorAccessible(MethodSymbol constructor, ref CompoundUseSi
                     diagnostics,
                     out MemberResolutionResult<MethodSymbol> memberResolutionResult,
                     out ImmutableArray<MethodSymbol> candidateConstructors,
-                    allowProtectedConstructorsOfBaseType: false))
+                    allowProtectedConstructorsOfBaseType: false) &&
+                !type.IsAbstract)
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:5368]: >!type.IsAbstract) [](http://example.com/codeflow?start=16&length=17)

Is this change related to the PR?

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:343]: > What in particular is bad about violating this? Is this IOperation related? Consider adding a comment for clarification.

 We don't want the node be "bifurcated". We could end up in a situation when the ```BoundObjectCreationExpressionBase``` was "buried" inside a ```BoundBadExpression```, both referring to the same syntax. That was "breaking" (causing an assert) ```NullableWalker``` because we expect a conversion node on top of the target-typed expression and the ```BoundBadExpression``` was getting in the middle.

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:354]: > Is there a test covering this change?

This value is not important for the purpose of the ObjectCreation conversion. Any value would work, but I decided to capture the value from the environment. This is what we normally do without thinking too much.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 4 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:5368]: > Is this change related to the PR?

Yes, it allows us to avoid the wrapping at the end of this ```if``` body. See the removed code. We don't want to end up with a bad expression on top of ```BoundObjectCreationExpression```. We should have either one node, or the other.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 3 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:4207]: > Since we're using this assertion twice, should we perhaps make it a conditional method that more explicitily elaborates what the condition violation breaks?

Any name suggestions for the method? I decided to avoid this problem all together. Didn't feel like there is much code duplication to avoid.

Comment (333fred) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:4207]: `AssertNoDuplicatedBadExpressionSyntax`?

**Comment by 333fred** [comment]
>                         Debug.Assert(TypeSymbol.Equals(resultTypeWithAnnotations.Type, node.Type, TypeCompareKind.IgnoreNullableModifiersForReferenceTypes));

Should this use the `AreCloseEnough` helper instead?

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3253 in 327f215. [](commit_id = 327f21535962a961be6069c6edf8fcfec61ad343, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 3 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:4207]: It is not really about syntax though. The syntax is not the root cause of the problem, it is not what is causing the problem. The syntax check is a good enough simplification  to detect a possible problem. The Assert doesn't have to be 100% accurate as long as it doesn't produce false violations.

**Comment by AlekseyTs** [comment]
>                         Debug.Assert(TypeSymbol.Equals(resultTypeWithAnnotations.Type, node.Type, TypeCompareKind.IgnoreNullableModifiersForReferenceTypes));

> Should this use the AreCloseEnough helper instead?

I do not think so. This is exactly what I would like to assert.

---
In reply to: [1002281993](https://github.com/dotnet/roslyn/pull/58509#issuecomment-1002281993) [](http://example.com/codeflow?ancestors=1002281993,1002281993)

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3253 in 327f215. [](commit_id = 327f21535962a961be6069c6edf8fcfec61ad343, deletion_comment = False)

**Comment by 333fred** [comment]
>                 Symbol symbol, BoundObjectInitializerExpressionBase initializer, int slot, Action<int,

Nit: consider not splitting the generic across multiple lines, it threw me for a second while reading.

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3546 in 327f215. [](commit_id = 327f21535962a961be6069c6edf8fcfec61ad343, deletion_comment = False)

**Comment by 333fred** [comment]
>                 return (int containigSlot, TypeSymbol containingType) =>

Typo: containing

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3694 in 327f215. [](commit_id = 327f21535962a961be6069c6edf8fcfec61ad343, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>                 Symbol symbol, BoundObjectInitializerExpressionBase initializer, int slot, Action<int,

> consider not splitting the generic across multiple lines, it threw me for a second while reading.

That wasn't intentional. I'll adjust formatting.

---
In reply to: [1002288996](https://github.com/dotnet/roslyn/pull/58509#issuecomment-1002288996) [](http://example.com/codeflow?ancestors=1002288996,1002288996)

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3546 in 327f215. [](commit_id = 327f21535962a961be6069c6edf8fcfec61ad343, deletion_comment = False)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 5]
```diff
@@ -53323,6 +53323,52 @@ class B { public static implicit operator C(B b) => new C(); }
...
+
+            comp.VerifyDiagnostics(
+                // (7,35): warning CS8619: Nullability of reference types in value of type 'C1' doesn't match target type 'C<string?>'.
+                // WarnHere:   _ = C.GetCT(s) + (b ? new C1() : new C2());
+                Diagnostic(ErrorCode.WRN_NullabilityMismatchInAssignment, "new C1()").WithArguments("C1", "C<string?>").WithLocation(7, 35),
+                // (7,46): warning CS8619: Nullability of reference types in value of type 'C2' doesn't match target type 'C<string?>'.
+                // WarnHere:   _ = C.GetCT(s) + (b ? new C1() : new C2());
+                Diagnostic(ErrorCode.WRN_NullabilityMismatchInAssignment, "new C2()").WithArguments("C2", "C<string?>").WithLocation(7, 46),
+                // (8,22): warning CS8619: Nullability of reference types in value of type 'C3' doesn't match target type 'C<string?>'.
+                // ButNotHere: _ = (b ? new C3() : new C4()) + C.GetCT(s);
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:53364]: >ButNotHere [](http://example.com/codeflow?start=19&length=10)

Are these warnings correct?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:53364]: The warnings, match my expectations. The labels are not meant to convey expectations, the base line is. The code matches the repro used in #58369.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 6]
```diff
@@ -154076,5 +154122,1342 @@ class C { }
...
+    }
+
+    static C<T>? GetC<T>(T t) => new C<T>(t);
+}
+
+struct C<T> : System.Collections.IEnumerable
+{
+    public C(){}
+    public C(T t){}
+    public void Add(T t){}
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:154669]: Consider a variation on this test where `Add` is a generic method constrained by `T`: something like `Add<U>(U u) where U : T`.

Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:154669]: (And giving the `null`s a type to facilitiate type inference of the `Add` call)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:154669]: Are ```ObjectCreationExpression_TargetTyped_06``` and ```ObjectCreationExpression_TargetTyped_12``` not good enough? I think they involve inference for the ```Add``` call. I guess not exactly what you are asking, but feels sufficient to me. If not, please construct the complete test scenario and what you expect for it and I will be happy to add it as a test.

Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:154669]: The scenario would be:

```cs
class C
{
    static void M()
    {
        var b = GetC(""b"");
        b = new() { default(string), ""b""};

        var c = new C<string>?(new C<string>() { null, ""c""});
        C<string>? d = new() { default(string), ""d""};
    }

    static C<T>? GetC<T>(T t) => new C<T>(t);
}

struct C<T> : System.Collections.IEnumerable
{
    public C(){}
    public C(T t){}
    public void Add<U>(U u) where U : T {}

    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => throw null!;
}
```

I'd expect to see the same warnings as in this test case: What I'm thinking is interesting about it (and different from _06 and _12) is that the `Add` method needs to be retargeted to the new `C<string>` type, and then have method inference run over it.

**Comment by 333fred** [comment]
Done review pass (commit 2). Just a couple of minor comments and a test suggestion.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 6 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:154669]: > I'd expect to see the same warnings as in this test case

Not quite the same, but still warnings:
```
// (7,21): warning CS8631: The type 'string?' cannot be used as type parameter 'U' in the generic type or method 'C<string>.Add<U>(U)'. Nullability of type argument 'string?' doesn't match constraint type 'string'.
//         b = new() { default(string), "b"};
Diagnostic(ErrorCode.WRN_NullabilityMismatchInTypeParameterConstraint, "default(string)").WithArguments("C<string>.Add<U>(U)", "string", "U", "string?").WithLocation(7, 21),
// (9,50): error CS0411: The type arguments for method 'C<string>.Add<U>(U)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
//         var c = new C<string>?(new C<string>() { null, "c"});
Diagnostic(ErrorCode.ERR_CantInferMethTypeArgs, "null").WithArguments("C<string>.Add<U>(U)").WithLocation(9, 50),
// (10,32): warning CS8631: The type 'string?' cannot be used as type parameter 'U' in the generic type or method 'C<string>.Add<U>(U)'. Nullability of type argument 'string?' doesn't match constraint type 'string'.
//         C<string>? d = new() { default(string), "d"};
Diagnostic(ErrorCode.WRN_NullabilityMismatchInTypeParameterConstraint, "default(string)").WithArguments("C<string>.Add<U>(U)", "string", "U", "string?").WithLocation(10, 32)
```

Does this match your expectations?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:154669]: I guess you meant to use ```default(string)``` everywhere where ```null``` was used.

Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:154669]: Yeah, I wasn't entirely sure whether it was going to be the mismatched type parameter warning or the possible null reference parameter warning. Thanks.

Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:154669]: > I guess you meant to use `default(string)` everywhere where `null` was used.

Yeah, I missed one in my example.

**Review by 333fred — APPROVED** [review]
LGTM (commit 3)

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

**Comment by AlekseyTs** [comment]
@cston, @dotnet/roslyn-compiler For the second review.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 7]
```diff
@@ -154076,5 +154122,1383 @@ class C { }
...
+    {
+    }
+
+    CL0<string?> M1(CL0<string> x) { throw new System.Exception(); }
+    CL0<string> M2(CL0<string> x) { throw new System.Exception(); }
+    delegate CL0<string> D1(CL0<string?> x);
+
+    void Test1()
+    {
+        D1 x1 = new   (M1);
```
Comment (alrz) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:155411]: Is this case relevant here?
```cs
#nullable enable
var c = Get("");
c = new(() => null); // warning expected
static System.Func<T> Get<T>(T t) => () => t;
```

File: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml [hunk 8]
```diff
@@ -1769,29 +1772,31 @@
       <Field Name="InitializerOpt" Type="InitializerExpressionSyntax?" Null="allow"/>
   </Node>
 
+  <AbstractNode Name="BoundObjectCreationExpressionBase" Base="BoundExpression">
```
Comment (alrz) [inline src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml:1775]: Would it make sense to define a base for all target-typed expressions?

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 7 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:155411]: > Is this case relevant here?

Lambdas are tested in the next test.

File: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml (hunk 8 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml:1775]: > Would it make sense to define a base for all target-typed expressions?

That might not be a smooth change. For example, ```BoundConvertedSwitchExpression``` doesn't inherit directly from ```BoundExpression```. We might revisit this later, but for now I am comfortable stopping at this level. Especially that this common base will be needed regardless, there is a bunch of abstract properties specific to object creation declared explicitly elsewhere.

**Comment by AlekseyTs** [comment]
@cston, @dotnet/roslyn-compiler For the second review.

**Comment by AlekseyTs** [comment]
@cston, @dotnet/roslyn-compiler For the second review.

File: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml [hunk 9]
```diff
@@ -1945,11 +1950,12 @@
     <Field Name="Property" Type="PropertySymbol" Null="disallow"/>
   </Node>
   
-  <Node Name="BoundNewT" Base="BoundExpression">
+  <Node Name="BoundNewT" Base="BoundObjectCreationExpressionBase">
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml:1953]: Can we remove `<Field Name="Type" Type="TypeSymbol" Override="true" Null="disallow"/>` from `BoundNewT` and `BoundNoPiaObjectCreationExpression` now?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml:1953]: > Can we remove ```<Field Name="Type" Type="TypeSymbol" Override="true" Null="disallow"/>``` from ```BoundNewT``` and ```BoundNoPiaObjectCreationExpression``` now?

Yes, I think those can be removed.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs [hunk 10]
```diff
@@ -881,54 +883,93 @@ private void VisitSwitchExpressionCore(BoundSwitchExpression node, bool inferTyp
...
+            {
+                TargetTypedAnalysisCompletion[node] =
+                    (TypeWithAnnotations inferredTypeWithAnnotations) =>
+                    {
+                        return convertArms(node, labelStateMap, conversions, resultTypes, expressions, inferredTypeWithAnnotations, isTargetTyped: false);
+                    };
+            }
 
-            LocalState getStateForArm(BoundSwitchExpressionArm arm)
+            LocalState getStateForArm(BoundSwitchExpressionArm arm, PooledDictionary<LabelSymbol, (LocalState state, bool believedReachable)> labelStateMap)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs:972]: static?

**Comment by cston** [comment]
>             (_, ImmutableArray<VisitArgumentResult> argumentResults, _, Func<ImmutableArray<VisitArgumentResult>, ImmutableArray<ParameterSymbol>, MethodSymbol?, (MethodSymbol? method, bool returnNotNull)>? argumentsCompletion) =

Consider creating an explicit `delegate` type for this, to improve readability of the uses.

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3189 in 56feeb8. [](commit_id = 56feeb89e4527f5df881af339bdeb07e33a8075d, deletion_comment = False)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs (hunk 10 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs:972]: ```UnreachableState``` is an instance method.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 11]
```diff
@@ -5398,159 +5830,229 @@ protected override void VisitArguments(ImmutableArray<BoundExpression> arguments
...
+                ImmutableArray<Conversion> conversions,
+                ImmutableArray<VisitArgumentResult> results,
+                ImmutableArray<RefKind> refKindsOpt,
+                ImmutableArray<ParameterSymbol> parametersOpt,
+                ImmutableArray<int> argsToParamsOpt,
+                BitVector defaultArguments,
+                bool expanded,
+                bool invokedAsExtensionMethod,
+                MethodSymbol? method,
+                bool delayCompletionForTargetMemeber)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]:
```suggestion
                bool delayCompletionForTargetMember)
```

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs [hunk 12]
```diff
@@ -881,54 +883,93 @@ private void VisitSwitchExpressionCore(BoundSwitchExpression node, bool inferTyp
...
+                BoundSwitchExpression node,
+                PooledDictionary<LabelSymbol, (LocalState state, bool believedReachable)> labelStateMap,
+                ArrayBuilder<Conversion> conversions,
+                ArrayBuilder<TypeWithState> resultTypes,
+                ArrayBuilder<BoundExpression> expressions,
+                TypeWithAnnotations inferredTypeWithAnnotations,
+                bool isTargetTyped)
+            {
+
+                if (!isTargetTyped)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker_Patterns.cs:922]: nit: empty line above

**Comment by cston** [comment]
>             Func<TypeSymbol, MethodSymbol?, int> inferInitialObjectStateAsContinuation(

`static`

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3351 in 56feeb8. [](commit_id = 56feeb89e4527f5df881af339bdeb07e33a8075d, deletion_comment = False)

**Comment by jcouv** [comment]
>                            constructor, delayCompletionForTargetMemeber: isTargetTyped);

typo is "...Member"

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3193 in 56feeb8. [](commit_id = 56feeb89e4527f5df881af339bdeb07e33a8075d, deletion_comment = False)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 13]
```diff
@@ -3274,93 +3405,332 @@ private void VisitObjectCreationInitializer(Symbol? containingSymbol, int contai
...
-                        if (!objectInitializer.Arguments.IsDefaultOrEmpty)
-                        {
-                            // It is an error for an interpolated string to use the receiver of an object initializer indexer here, so we just use
-                            // a default visit result
-                            VisitArguments(objectInitializer, objectInitializer.Arguments, objectInitializer.ArgumentRefKindsOpt, (PropertySymbol?)symbol, objectInitializer.ArgsToParamsOpt, objectInitializer.DefaultArguments, objectInitializer.Expanded);
-                        }
+                        return visitMemberinitializer(containingSlot, containingType, node, delayCompletionForType);
 
-                        if (symbol is object)
+                        Action<int, TypeSymbol>? visitMemberinitializer(int containingSlot, TypeSymbol containingType, BoundAssignmentOperator node, bool delayCompletionForType)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]:
```suggestion
                        Action<int, TypeSymbol>? visitMemberInitializer(int containingSlot, TypeSymbol containingType, BoundAssignmentOperator node, bool delayCompletionForType)
```

**Comment by jcouv** [comment]
>                         Action<int, TypeSymbol>? visitMemberinitializer(int containingSlot, TypeSymbol containingType, BoundAssignmentOperator node, bool delayCompletionForType)

Can we avoid local function in middle of code flow and with nested local function? I understand you probably wanted to minimize the diff, but this impairs readability and doesn't seem necessary in this instance.

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3432 in 56feeb8. [](commit_id = 56feeb89e4527f5df881af339bdeb07e33a8075d, deletion_comment = False)

**Comment by jcouv** [comment]
>             return setUpdatedSymbol(node, containingType, reinferredMethod, delayCompletionForType ? argumentResults : default, visitArgumentsCompletion, delayCompletionForType);

nit: `setAnalyzedNullability` above (line 3210, in `VisitObjectCreationExpression`) could use a similar pattern (only uses argument results in case of delayed completion). Consider aligning one way or the other (ie. always passing argument results, or conditionally passing `default`)

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3656 in 56feeb8. [](commit_id = 56feeb89e4527f5df881af339bdeb07e33a8075d, deletion_comment = False)

**Comment by jcouv** [comment]
>             void addConvertArmsAsCompletion(

nit: the naming pattern in this PR suggests this should be called `convertArmsAsContinuation`

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:5246 in 56feeb8. [](commit_id = 56feeb89e4527f5df881af339bdeb07e33a8075d, deletion_comment = False)

**Comment by cston** [comment]
>         private bool IsTargetTypedExpression(BoundExpression node)

`static`

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3976 in 56feeb8. [](commit_id = 56feeb89e4527f5df881af339bdeb07e33a8075d, deletion_comment = False)

**Comment by cston** [comment]
>                 TypeSymbol? asMemberOfType = getTypeIfContainingType(methodContainer, leftUnderlyingType.Type, leftOperand) ??

`TypeSymbol!`

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:4348 in 56feeb8. [](commit_id = 56feeb89e4527f5df881af339bdeb07e33a8075d, deletion_comment = False)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 14]
```diff
@@ -5398,159 +5830,229 @@ protected override void VisitArguments(ImmutableArray<BoundExpression> arguments
...
+            BoundNode node,
+            ImmutableArray<BoundExpression> arguments,
+            ImmutableArray<RefKind> refKindsOpt,
+            ImmutableArray<ParameterSymbol> parametersOpt,
+            ImmutableArray<int> argsToParamsOpt,
+            BitVector defaultArguments,
+            bool expanded,
+            bool invokedAsExtensionMethod,
+            MethodSymbol? method,
+            bool delayCompletionForTargetMemeber)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]:
```suggestion
            bool delayCompletionForTargetMember)
```

**Comment by jcouv** [comment]
>                             Debug.Assert(!IsTargetTypedExpression(argumentNoConversion) || _targetTypedAnalysisCompletionOpt?.ContainsKey(argumentNoConversion) is not (null or false));

nit: `is true`?

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:5938 in 56feeb8. [](commit_id = 56feeb89e4527f5df881af339bdeb07e33a8075d, deletion_comment = False)

**Comment by jcouv** [comment]
>                 void visitHandlerConstruction(InterpolatedStringHandlerData handlerData)

consider unnesting this local function too

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:8106 in 56feeb8. [](commit_id = 56feeb89e4527f5df881af339bdeb07e33a8075d, deletion_comment = False)

**Comment by jcouv** [comment]
>                     }

Could remove the braces/scopes in this switch.

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:8391 in 56feeb8. [](commit_id = 56feeb89e4527f5df881af339bdeb07e33a8075d, deletion_comment = False)

**Comment by jcouv** [comment]
>         private void VisitObjectCreationExpression(BoundObjectCreationExpressionBase node)

nit: Consider renaming `VisitObjectCreationExpressionBase` and removing casts at call sites



---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3182 in 56feeb8. [](commit_id = 56feeb89e4527f5df881af339bdeb07e33a8075d, deletion_comment = False)

**Comment by jcouv** [comment]
>                 ImmutableArray<BoundExpression> arguments, ImmutableArray<VisitArgumentResult> argumentResults)

nit: break `argumentResults` to next line?

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3353 in 56feeb8. [](commit_id = 56feeb89e4527f5df881af339bdeb07e33a8075d, deletion_comment = False)

**Comment by jcouv** [comment]
>             Debug.Assert(!_completingTargetTypedExpression);

It looks like the only real usage for `_completingTargetTypedExpression` is in this assertion. Should the field and accompanying logic be if/def'ed?

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3150 in 56feeb8. [](commit_id = 56feeb89e4527f5df881af339bdeb07e33a8075d, deletion_comment = False)

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 3)

**Comment by AlekseyTs** [comment]
>             Func<TypeSymbol, MethodSymbol?, int> inferInitialObjectStateAsContinuation(

> ```static```?

The method captures ```this```.

---
In reply to: [1004462333](https://github.com/dotnet/roslyn/pull/58509#issuecomment-1004462333) [](http://example.com/codeflow?ancestors=1004462333,1004462333)

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3351 in 56feeb8. [](commit_id = 56feeb89e4527f5df881af339bdeb07e33a8075d, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>             void addConvertArmsAsCompletion(

> : the naming pattern in this PR suggests this should be called convertArmsAsContinuation
The same comment applies to addConvertArmsAsCompletion in the patterns logic.

The naming is intentional. The method isn't returning continuation delegate, it builds the final completion delegate and saves it in the map. 

---
In reply to: [1004482571](https://github.com/dotnet/roslyn/pull/58509#issuecomment-1004482571) [](http://example.com/codeflow?ancestors=1004482571,1004482571)

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:5246 in 56feeb8. [](commit_id = 56feeb89e4527f5df881af339bdeb07e33a8075d, deletion_comment = False)

**Review by cston — APPROVED** [review]

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 4)
