### PR TITLE
Handle errors in RequestExecutionQueue

### LINKED ISSUE #46051: [LSP] Order messages in the LSP server
JsonRPC doesn't necessarily preserve order of responses.  We need to ensure that messages are ordered properly (especially once we implement text document change notifications) so that we do not process things out of order.  We shouldn't serialize all messages as the LSP spec allows us to process some messages in parallel.

TODO:
* [x] Introduce a RequestContext to hold all of the parameters that a handler needs (#46557)
* [x] Create a RequestExecutionQueue to run requests in order and block as necessary (#46660)
* [x] Handlers to provide a way to indicate which document they need to operate on, which is passed back to them (#46896)
* [x] Remove SolutionProvider from AbstractRequestHandler to force new handlers to use the RequestContext.Solution (#47022)
* [x] `mutatesSolutionState` parameter on `ExportLspMethodAttribute` to be non-optional (#47022)
  * and cleanup: https://github.com/dotnet/roslyn/pull/46660#discussion_r468172882
* [x] Queue lifetime should be per LSP-server, not shared via MEF, and problems should close the connection (#47107)
  * see: https://github.com/dotnet/roslyn/pull/46660#discussion_r468227975
  * and: https://github.com/dotnet/roslyn/pull/46660#discussion_r468229986
  * and: https://github.com/dotnet/roslyn/pull/46660#discussion_r471669025
* [x] Does StreamJsonRpc guarantee that message B won't start processing until message A at least returns a task from its handler?
  * ie, can a message be added to the async queue in the wrong order, if a previous message gets unlucky threading
    * Yes, after v2.6 StreamJsonRpc ensures ordering by default until the first await: https://github.com/microsoft/vs-streamjsonrpc/blob/master/doc/resiliency.md#default-ordering-and-concurrency-behavior
* [ ] Does/Can GetTextDocumentWithContextHandler use the right solution snapshots?
* Actual solution merging will come with #45427

### PR DESCRIPTION
**Pull request by davidwengier**
Fixes #46051

This PR is the "final" piece of request queue stuff, except merging the solutions.

This introduces error handling in the request queue including sending back a message to the client and disconnecting. I've tested this in Live Share and the client reconnects silently when it next needs to, and correctly calls Initialize and everything continues as expected.

This also changes the lifetime of the RequestExecutionQueue so its not a MEF component, but is directly constructed by each server. In addition the queue is used directly from the InProcLanguageServer instead of going through the AbstractRequestHandlerProvider, though it still needs to know about it.

### CODE REVIEW

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs [hunk 1]
```diff
@@ -280,6 +291,31 @@ private async void DiagnosticService_DiagnosticsUpdated(object sender, Diagnosti
...
+                    Message = e.Message
+                };
+
+                await _jsonRpc.NotifyWithParameterObjectAsync(Methods.WindowLogMessageName, message).ConfigureAwait(false);
+            }
+            catch (Exception ex) when (FatalError.ReportWithoutCrash(ex))
+            {
+            }
+
+            await ExitAsync(/* cancellationToken: */ default).ConfigureAwait(false);
```
Comment (davidwengier) [inline src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs:316]: ExitAsync doesn't use its cancellation token, so the named parameter for this is `_`, hence this style

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs [hunk 2]
```diff
@@ -38,20 +37,63 @@ namespace Microsoft.CodeAnalysis.LanguageServer.Handler
...
-        private readonly AsyncQueue<QueueItem> _queue = new AsyncQueue<QueueItem>();
         private readonly ILspSolutionProvider _solutionProvider;
-        private readonly CancellationTokenSource _cancelSource;
+        // The queue and the cancellation token should both be null or non-null at all times
+        private AsyncQueue<QueueItem>? _queue;
+        private CancellationTokenSource? _cancelSource;
+
+        /// <summary>
+        /// Raised when the execution queue has failed, or the solution state its tracking is in an unknown state
+        /// and so the only course of action is the shutdown the server so that the client re-connects and we can
```
Comment (davidwengier) [inline src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:55]:
```suggestion
        /// and so the only course of action is to shutdown the server so that the client re-connects and we can
```

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs [hunk 3]
```diff
@@ -280,6 +291,31 @@ private async void DiagnosticService_DiagnosticsUpdated(object sender, Diagnosti
             }
         }
 
+#pragma warning disable VSTHRD100 // Avoid async void methods
+        private async void RequestExecutionQueue_Errored(object sender, RequestShutdownEventArgs e)
+#pragma warning restore VSTHRD100 // Avoid async void methods
```
Comment (sharwell) [inline src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs:296]: ❗ Do not suppress VSTHRD100. This method must either be `async Task`, or just `void`.

**Review by sharwell — DISMISSED** [review]

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs (hunk 3 above)
Comment (davidwengier) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs:296]: Am I exempt because there already was one of these in this file? 😛

Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs:296]: If you just moved existing code here then yes (i.e. this is the same suppression, just in a different location than it was previously).

Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs:296]: I submitted #47115 to remove the other one.

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs [hunk 4]
```diff
@@ -38,20 +37,63 @@ namespace Microsoft.CodeAnalysis.LanguageServer.Handler
     /// and any consumers observing the results of the task returned from <see cref="ExecuteAsync{TRequestType, TResponseType}(bool, IRequestHandler{TRequestType, TResponseType}, TRequestType, ClientCapabilities, string?, CancellationToken)"/>
     /// will see the results of the handling of the request, whenever it occurred.
     /// </para>
+    /// <para>
+    /// Exceptions in the handling of non-mutating requests are sent back to callers. Exceptions in the processing of
+    /// the queue will close the LSP connection so that the client can reconnect. Exceptions in the handling of mutating
+    /// requests will also close the LSP connection, as at that point the mutated solution is in an unknown state.
```
Comment (CyrusNajmabadi) [inline src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:43]: should we put ourselves into a failure state, and just reject all future calls from that point until we resync?

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs [hunk 5]
```diff
@@ -38,20 +37,63 @@ namespace Microsoft.CodeAnalysis.LanguageServer.Handler
...
-            _cancelSource = new CancellationTokenSource();
+        }
+
+        /// <summary>
+        /// Initializes the queue if its not already initialized and starts it processing messages
+        /// </summary>
+        public void Initialize()
+        {
+            // If the queue is already running, do nothing because we don't want to run multiple or lose any queued messages
+            if (_cancelSource == null || _cancelSource.IsCancellationRequested)
```
Comment (CyrusNajmabadi) [inline src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:74]: re-initializing when cancellation happens seems pretty confusing.  can we just create a new queue and have the higher layer use that?

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs [hunk 6]
```diff
@@ -38,20 +37,63 @@ namespace Microsoft.CodeAnalysis.LanguageServer.Handler
...
         public RequestExecutionQueue(ILspSolutionProvider solutionProvider)
         {
             _solutionProvider = solutionProvider;
-            _cancelSource = new CancellationTokenSource();
+        }
+
+        /// <summary>
+        /// Initializes the queue if its not already initialized and starts it processing messages
+        /// </summary>
+        public void Initialize()
```
Comment (CyrusNajmabadi) [inline src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:71]: what are the threading guarantees around any of this.  it def worries me that thsi stuff coudl be called while interleaved with otehr work that is happening.

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs [hunk 7]
```diff
@@ -79,6 +121,13 @@ public RequestExecutionQueue(ILspSolutionProvider solutionProvider)
             // Create a task completion source that will represent the processing of this request to the caller
             var completion = new TaskCompletionSource<TResponseType>();
```
Comment (CyrusNajmabadi) [inline src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:122]: what's the threading invariants around this being called at the same time as Shutdown/Initialize?

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs [hunk 8]
```diff
@@ -121,42 +170,99 @@ public RequestExecutionQueue(ILspSolutionProvider solutionProvider)
...
-                {
-                    // Non mutating request get given the current solution state, but are otherwise fire-and-forget
-                    _ = work.CallbackAsync(context, cancellationToken);
-                }
+            }
+            catch (Exception e) when (FatalError.ReportWithoutCrash(e))
+            {
+                OnRequestServerShutdown($"Error occured processing queue: {e.Message}.");
+            }
+        }
```
Comment (CyrusNajmabadi) [inline src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:237]: skipped this for now.

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs [hunk 9]
```diff
@@ -121,42 +170,99 @@ public RequestExecutionQueue(ILspSolutionProvider solutionProvider)
...
+        private void OnRequestServerShutdown(string message)
+        {
+            RequestServerShutdown?.Invoke(this, new RequestShutdownEventArgs(message));
+
+            if (_cancelSource != null)
+            {
+                _cancelSource.Cancel();
+                DrainQueue();
+            }
+        }
```
Comment (CyrusNajmabadi) [inline src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:248]: all these shoudl have some rich comments explaining what is going on and what state this leaves thigns in.

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs (hunk 4 above)
Comment (davidwengier) [reply src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:43]: That is what happens via the `Contract.ThrowIfNull` in `ExecuteAsync`, but I will clarify the comment.

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs (hunk 5 above)
Comment (davidwengier) [reply src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:74]: Yes, the higher level could create a new `RequestExecutionQueue`, sure.

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs (hunk 6 above)
Comment (davidwengier) [reply src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:71]: This is called from the "initialize" LSP request, and StreamJsonRpc guarantees that requests don't run concurrently up to their first await, so this can't overlap with another "initialize" request. I'm not sure how best to express that in the code though. In a doc comment? Use a lock just in case?

Would appreciate any guidance you have here.

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs (hunk 7 above)
Comment (davidwengier) [reply src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:122]: As above, StreamJsonRpc. I think moving the lifetime to the higher level might make this clearer, will see.

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs (hunk 3 above)
Comment (davidwengier) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs:296]: Thank you, I'll copy that pattern once it merges through :)

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs (hunk 9 above)
Comment (davidwengier) [reply src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:235]: Depending on how "rich" you are talking about, I might have done this :)

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs (hunk 7 above)
Comment (davidwengier) [reply src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:109]: I think changing the lifetime here makes this clearer. Let me know what you think

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs [hunk 10]
```diff
@@ -123,40 +166,91 @@ private async Task ProcessQueueAsync()
...
+            {
+                OnRequestServerShutdown($"Error occured processing queue: {e.Message}.");
+            }
+        }
+
+        private void OnRequestServerShutdown(string message)
+        {
+            RequestServerShutdown?.Invoke(this, new RequestShutdownEventArgs(message));
+
+            _cancelSource.Cancel();
```
Comment (dibarbet) [inline src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:233]: could call Shutdown method here for consistency

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs [hunk 11]
```diff
@@ -123,6 +130,8 @@ public Task ExitAsync(CancellationToken _)
         {
             Contract.ThrowIfFalse(_shuttingDown, "Shutdown has not been called yet.");
 
+            ShutdownRequestQueue();
```
Comment (dibarbet) [inline src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs:133]: I think this should be done in Shutdown.  Per the spec any requests sent after a shutdown (other than exit) should error
https://microsoft.github.io/language-server-protocol/specification#shutdown

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs [hunk 12]
```diff
@@ -123,40 +166,91 @@ private async Task ProcessQueueAsync()
...
-                    var ranToCompletion = await work.CallbackAsync(context, cancellationToken).ConfigureAwait(false);
+                    if (work.MutatesSolutionState)
+                    {
+                        // Mutating requests block other requests from starting to ensure an up to date snapshot is used.
+                        var ranToCompletion = false;
+                        try
+                        {
+                            ranToCompletion = await work.CallbackAsync(context, cancellationToken).ConfigureAwait(false);
+                        }
+                        catch (OperationCanceledException)
```
Comment (jasonmalinowski) [inline src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:195]: So now that we're having to do these catches _anyways_, does do we really need the ranToCompletion boolean as well? If instead work.CallbackAsync just returns the same task from the TaskCompletionSource it returned to the original caller, then you can just simplify this to:

```
try
{
   await work.CallbackAsync(....);
   lastMutatedSolution = mutatedSolution ?? lastMutatedSolution;
}
catch (OperationCanceledException)
{
}
catch (Exception e)
{
    OnRequestServerShutdown($"An error occured processing a mutating request and the solution is in an invalid state. Check LSP client logs for any error information.");
}
```

Which also means you now have the exception in hand if you want to pass a message back to the OnRequestServerShutdown rather than eating the exception if the logs are unavailable.

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs (hunk 1 above)
Comment (jasonmalinowski) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs:337]: I'd add that comment in the code as otherwise anybody else looking at this will wonder why we didn't use named parameters.

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs [hunk 13]
```diff
@@ -123,40 +166,91 @@ private async Task ProcessQueueAsync()
...
+        private void DrainQueue()
+        {
+            // Tell the queue not to accept any more items
+            _queue.Complete();
+
+            // Spin through the queue and pass in our cancelled token, so that the waiting tasks are cancelled.
+            // NOTE: This only really works because the first thing that CallbackAsync does is check for cancellation
+            // but generics make it annoying to store the TaskCompletionSource<TResult> on the QueueItem so this
+            // is the best we can do for now. Ideally we would manipulate the TaskCompletionSource directly here
+            // and just call SetCanceled
```
Comment (jasonmalinowski) [inline src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:250]: Is cancellation here the right thing or is that going to surprise people? Are we better off erroring the requests that we can never service?

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs [hunk 14]
```diff
@@ -123,40 +166,91 @@ private async Task ProcessQueueAsync()
...
             Solution? lastMutatedSolution = null;
-            var queueToken = _cancelSource.Token;
 
-            while (!queueToken.IsCancellationRequested)
+            try
             {
-                var work = await _queue.DequeueAsync().ConfigureAwait(false);
+                while (!_cancelSource.IsCancellationRequested)
+                {
+                    var work = await _queue.DequeueAsync().ConfigureAwait(false);
```
[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:174]: Potentially it means the `while (!_cancelSource.IsCancellationRequested)` condition isn't necessary now since it could get cancelled here.

File: src/Features/LanguageServer/Protocol/AbstractRequestHandlerProvider.cs [hunk 15]
```diff
@@ -39,9 +37,15 @@ public AbstractRequestHandlerProvider(IEnumerable<Lazy<IRequestHandler, IRequest
             return requestHandlerDictionary.ToImmutable();
         }
 
+        public void SetRequestQueue(RequestExecutionQueue queue)
```
[the remark this answers is not in the document]
Comment (davidwengier) [reply src/Features/LanguageServer/Protocol/AbstractRequestHandlerProvider.cs:40]: I was wondering if AbstractRequestHandlerProvider needs to exist at all. Passing in the queue is a bit more painful for testing, but seems like a nice middle ground. See what you think :)

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs [hunk 16]
```diff
@@ -79,6 +108,12 @@ public RequestExecutionQueue(ILspSolutionProvider solutionProvider)
             // Create a task completion source that will represent the processing of this request to the caller
             var completion = new TaskCompletionSource<TResponseType>();
 
+            // If the queue is not accepting any more items then we just fault immediately as this queue has been shut down.
+            if (_queue.IsCompleted)
+            {
+                completion.SetException(new InvalidOperationException("Server has not been initialized, or was requested to shut down."));
+            }
```
[the remark this answers is not in the document]
Comment (davidwengier) [reply src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:115]: I thought it looked wrong to not have it, but I'll remove it and adjust the comments.

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs [hunk 17]
```diff
@@ -123,40 +166,91 @@ private async Task ProcessQueueAsync()
...
-                Solution? mutatedSolution = null;
-                var context = new RequestContext(solution, work.ClientCapabilities, work.ClientName, document, s => mutatedSolution = s);
+                    Solution? mutatedSolution = null;
+                    var context = new RequestContext(solution, work.ClientCapabilities, work.ClientName, document, s => mutatedSolution = s);
 
-                if (work.MutatesSolutionState)
-                {
-                    // Mutating requests block other requests from starting to ensure an up to date snapshot is used.
-                    var ranToCompletion = await work.CallbackAsync(context, cancellationToken).ConfigureAwait(false);
+                    if (work.MutatesSolutionState)
```
[the remark this answers is not in the document]
Comment (davidwengier) [reply src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:187]: Good point!

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs (hunk 12 above)
Comment (davidwengier) [reply src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:195]: This could work, but I don't think I'm a big fan because the Callback will have to catch and rethrow the exceptions, and I think it will generally be harder to understand what is going on. You're right it would make for a better log message, which might be useful.

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs (hunk 13 above)
Comment (davidwengier) [reply src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:250]: Cancellation feels more appropriate here to me because we never even started processing, but I could be convinced otherwise ¯\\\_(ツ)_/¯

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs [hunk 18]
```diff
@@ -123,40 +166,91 @@ private async Task ProcessQueueAsync()
...
+            _queue.Complete();
+
+            // Spin through the queue and pass in our cancelled token, so that the waiting tasks are cancelled.
+            // NOTE: This only really works because the first thing that CallbackAsync does is check for cancellation
+            // but generics make it annoying to store the TaskCompletionSource<TResult> on the QueueItem so this
+            // is the best we can do for now. Ideally we would manipulate the TaskCompletionSource directly here
+            // and just call SetCanceled
+            while (_queue.TryDequeue(out var item))
+            {
+                _ = item.CallbackAsync(default, new CancellationToken(true));
```
[the remark this answers is not in the document]
Comment (davidwengier) [reply src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:253]: If we don't call the callback, then the original request message task is never completed so StreamJsonRpc would be holding on to things. We need to complete the TaskCompletionSource that we created, and because its a generic type with no base class, the only way to do so is calling the callback.

And no, there is no Clear or Dispose method :P

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs [hunk 19]
```diff
@@ -78,6 +83,8 @@ internal class InProcLanguageServer
         [JsonRpcMethod(Methods.InitializeName, UseSingleObjectParameterDeserialization = true)]
         public async Task<InitializeResult> InitializeAsync(InitializeParams initializeParams, CancellationToken cancellationToken)
         {
+            InitializeRequestQueue();
```
[the remark this answers is not in the document]
Comment (davidwengier) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs:86]: Yes, your comments about the external Activate are relevant here, so this could move to the constructor.

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs (hunk 1 above)
Comment (davidwengier) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs:337]: Inline parameter hints is going to make these types of things more prevalent.. when looking in the IDE its immediately obvious, if you ask me :)

image

Will add a comment for lesser IDEs, like GitHub :P

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs (hunk 11 above)
Comment (davidwengier) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs:133]: Yep, this is another one from my Inialize/Shutdown confusion, I didn't want to unsubscribe to the diagnostics event incorrectly :)

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs (hunk 14 above)
[the remark this answers is not in the document]
Comment (davidwengier) [reply src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:174]: Good point about the exception, I've added a catch. Going to leave the condition on the while loop though, because if we cancel the token I think its still easier to let the DrainQueue method handle things than having this loop run through as well.

**Comment by davidwengier** [comment]
Ping @sharwell @jasonmalinowski all feedback has been addressed, except the bool return from the callback.

File: src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs [hunk 20]
```diff
@@ -341,6 +341,13 @@ private protected static LanguageServerProtocol GetLanguageServer(Solution solut
             return workspace.ExportProvider.GetExportedValue<LanguageServerProtocol>();
         }
 
+        private protected static RequestExecutionQueue GetRequestQueue(Solution solution)
```
Comment (jasonmalinowski) [inline src/EditorFeatures/TestUtilities/LanguageServer/AbstractLanguageServerProtocolTests.cs:344]:
```suggestion
        private protected static RequestExecutionQueue CreateRequestQueue(Solution solution)
```

The name would have implied that if called multiple times it'd get the same queue; I worry that the the tests could have some 'surprises' if somebody thought that'd be the case.

File: src/Features/LanguageServer/ProtocolUnitTests/Definitions/GoToDefinitionTests.cs [hunk 21]
```diff
@@ -103,7 +103,10 @@ void M()
         }
 
         private static async Task<LSP.Location[]> RunGotoDefinitionAsync(Solution solution, LSP.Location caret)
-            => await GetLanguageServer(solution).ExecuteRequestAsync<LSP.TextDocumentPositionParams, LSP.Location[]>(LSP.Methods.TextDocumentDefinitionName,
-                CreateTextDocumentPositionParams(caret), new LSP.ClientCapabilities(), null, CancellationToken.None);
+        {
+            var queue = GetRequestQueue(solution);
```
Comment (jasonmalinowski) [inline src/Features/LanguageServer/ProtocolUnitTests/Definitions/GoToDefinitionTests.cs:107]: Is there a way to avoid each test having to duplicate this? Should it just be calling into the underlying handler directly rather than having to make a queue that won't really do anything? Or is this a "feature" in that it ensures the test queueing isn't broken in some way that would prevent stuff working?

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs [hunk 22]
```diff
@@ -123,40 +162,97 @@ private async Task ProcessQueueAsync()
...
+                        var ranToCompletion = false;
+                        try
+                        {
+                            ranToCompletion = await work.CallbackAsync(context, cancellationToken).ConfigureAwait(false);
+                        }
+                        catch (OperationCanceledException)
+                        {
+                            // Since the cancellationToken passed to the callback is a linked source it could be cancelled
+                            // without the queue token being cancelled, but ranToCompletion will be false so no need to
+                            // do anything special here.
```
Comment (jasonmalinowski) [inline src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:195]: Should we assert that it's false?

File: src/Features/LanguageServer/ProtocolUnitTests/Ordering/RequestOrderingTests.cs [hunk 23]
```diff
@@ -165,32 +169,10 @@ public async Task ThrowingMutableTaskDoesntBringDownQueue()
...
-            };
-
-            var waitables = StartTestRun(requests);
-
-            // second task should have failed
-            await Assert.ThrowsAsync<InvalidOperationException>(async () => await waitables[1]);
-
-            var responses = await Task.WhenAll(waitables.Where(t => !t.IsFaulted));
+            // remaining tasks should be canceled
+            await Assert.ThrowsAsync<TaskCanceledException>(async () => await Task.WhenAll(waitables.Skip(1)));
```
Comment (jasonmalinowski) [inline src/Features/LanguageServer/ProtocolUnitTests/Ordering/RequestOrderingTests.cs:173]:
```suggestion
            await Assert.ThrowsAsync<TaskCanceledException>(Task.WhenAll(waitables.Skip(1)));
```

Does that work? The async to just await something else looks a bit odd otherwise.

File: src/VisualStudio/Core/Test.Next/Services/LspDiagnosticsTests.cs [hunk 24]
```diff
@@ -379,8 +379,9 @@ static InProcLanguageServer CreateLanguageServer(Stream inputStream, Stream outp
             {
                 var protocol = workspace.ExportProvider.GetExportedValue<LanguageServerProtocol>();
                 var listenerProvider = workspace.ExportProvider.GetExportedValue<IAsynchronousOperationListenerProvider>();
+                var solutionProvider = ((TestWorkspace)workspace).ExportProvider.GetExportedValue<ILspSolutionProvider>();
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Test.Next/Services/LspDiagnosticsTests.cs:382]: workspace is already a TestWorkspace?

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs [hunk 25]
```diff
@@ -51,6 +53,7 @@ internal class InProcLanguageServer
             CodeAnalysis.Workspace workspace,
             IDiagnosticService diagnosticService,
             IAsynchronousOperationListenerProvider listenerProvider,
+            ILspSolutionProvider solutionProvider,
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs:56]: Now that this is being passed, can we remove the 'workspace' parameter in favor of using the main workspace as handed through the ILspSolutionProvider?

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs [hunk 26]
```diff
@@ -79,6 +108,8 @@ public RequestExecutionQueue(ILspSolutionProvider solutionProvider)
             // Create a task completion source that will represent the processing of this request to the caller
             var completion = new TaskCompletionSource<TResponseType>();
 
+            // Note: If the queue is not accepting any more items then TryEnqueue below will fail.
+
             var textDocument = handler.GetTextDocumentIdentifier(request);
             var item = new QueueItem(mutatesSolutionState, clientCapabilities, clientName, textDocument,
                 callbackAsync: async (context, cancellationToken) =>
```
Comment (jasonmalinowski) [inline src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:115]: Should the call to completion.SetCancelled in here be passing along the cancellation token so we can better diagnose if things are going wrong? You might have to Debug.Assert(completion.TrySetCancelled(...)) since I don't know if the overload was added.

**Review by jasonmalinowski — APPROVED** [review]
I think this looks OK from the threading perspective (modulo some comments), although I'm still cautious about what the merging logic is ultimately going to look like. Depending on how it ultimately works this RequestExecutionQueue implementation can be greatly simplified (I think) with the pattern we use other parts of Roslyn where we just have a queue of Tasks created with ContinueWith calls; the non-mutating in that case are just tasks that branch off and don't actually get placed in the queue. I think that approach gets us the error handling and cancellation logic automatically. But that's very much contingent on how that "TODO" comment gets resolved!

I admit the big picture of how an ILspSolutionProvider vs. AbstractRequestHandlerProvider vs. AbstractLanguageServerClient isn't clear to me, and although that's not the doing of this pull request it means I can't say with any confidence whether the changes to that structure here are right. So hopefully somebody else can confirm that bit. :smile:

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs (hunk 25 above)
Comment (jasonmalinowski) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs:56]: Or put a different way: what happens if a workspace other than the main workspace from ILspSolutionProvider is passed? Is that bad?

**Comment by davidwengier** [comment]
> But that's very much contingent on how that "TODO" comment gets resolved!

Indeed, I was originally expecting the "merge" to be complicated but I think it might end up being relatively simple so some of this could be looked at again. We're still working out what exactly the merge will do though :)

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs (hunk 25 above)
Comment (davidwengier) [reply src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs:56]: At one stage I wanted to get rid of the ILspSolutionProvider altogether, and I wouldn't rule it out in the end. As you note there is an odd relationship here.

File: src/Features/LanguageServer/ProtocolUnitTests/Definitions/GoToDefinitionTests.cs (hunk 21 above)
Comment (davidwengier) [reply src/Features/LanguageServer/ProtocolUnitTests/Definitions/GoToDefinitionTests.cs:107]: I think its a small feature to help people write successful tests. Once a request handler is changed to use `context.Document` for example, then there needs to be something that ensures the RequestContext passed in is set up correctly by calling into the handler to get the document, etc. Either each test, or the base class, needs to do that work, or the tests can just ask the base class for a queue.

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs (hunk 26 above)
Comment (davidwengier) [reply src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:115]: I didn't even know that overload existed! Looks like nothing else calls it in Debug.Assert so I'm just gonna go for it. Given that the completion tokens entire lifetime is in this method I don't know why it would ever fail, but I'm happy to educated.

File: src/VisualStudio/Core/Test.Next/Services/LspDiagnosticsTests.cs (hunk 24 above)
Comment (davidwengier) [reply src/VisualStudio/Core/Test.Next/Services/LspDiagnosticsTests.cs:382]: It is now!

File: src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs [hunk 27]
```diff
@@ -123,40 +162,97 @@ private async Task ProcessQueueAsync()
...
+                        _ = work.CallbackAsync(context, cancellationToken).ReportNonFatalErrorAsync();
                     }
                 }
-                else
-                {
-                    // Non mutating request get given the current solution state, but are otherwise fire-and-forget
-                    _ = work.CallbackAsync(context, cancellationToken);
-                }
+            }
+            catch (OperationCanceledException)
```
[the remark this answers is not in the document]
Comment (davidwengier) [reply src/Features/LanguageServer/Protocol/Handler/RequestExecutionQueue.cs:221]: Makes a lot of sense, thank you. I would not have thought of this :)
