### PR TITLE
Remove incorrect condition in SynthesizedParameterSymbol.AddSynthesizedAttributes

### LINKED ISSUE #6126: Incorrect condition in `AddSynthesizedAttributes`
See the comment https://github.com/dotnet/roslyn/pull/5447#discussion_r40827825

The offending code is at 
https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs#L161 :

```cs
                compilation.GetSpecialType(SpecialType.System_Boolean).SpecialType == SpecialType.System_Boolean)
```

This condition is always true.

### PR DESCRIPTION
**Pull request by cston**
Fixes #6126

### CODE REVIEW

**Comment by cston** [comment]
@dotnet/roslyn-compiler, @jaredpar, @gafter, @AlekseyTs

**Comment by AlekseyTs** [comment]
Is there an issue for this change?

**Comment by cston** [comment]
Fixes #6126

File: src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs [hunk 1]
```diff
@@ -471,19 +471,25 @@ internal SynthesizedAttributeData SynthesizeDynamicAttribute(TypeSymbol type, in
...
+                var booleanType = argumentType.ElementType;
+                Debug.Assert(booleanType.SpecialType == SpecialType.System_Boolean);
                 var transformFlags = DynamicTransformsEncoder.Encode(type, booleanType, customModifiersCount, refKindOpt);
-                var boolArray = ArrayTypeSymbol.CreateSZArray(booleanType.ContainingAssembly, booleanType, customModifiers: ImmutableArray<CustomModifier>.Empty);
-                var arguments = ImmutableArray.Create<TypedConstant>(new TypedConstant(boolArray, transformFlags));
-                return TrySynthesizeAttribute(WellKnownMember.System_Runtime_CompilerServices_DynamicAttribute__ctorTransformFlags, arguments);
+                arguments = ImmutableArray.Create<TypedConstant>(new TypedConstant(argumentType, transformFlags));
             }
+
+            return new SynthesizedAttributeData(ctorSymbol, arguments, ImmutableArray<KeyValuePair<string, TypedConstant>>.Empty);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs]: What is the motivation for this change? Was this function doing something wrong? Is it safe to assume that the constructor of the right shape will be found? TrySynthesizeAttribute is handling the case of a missing constructor.

Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs]: The motivation for this change was to avoid calling ```Compilation.GetSpecialType(SpecialType.System_Boolean)``` which I believe was assumed could fail. However, by the time we get here, the caller has already verified that DynamicAttribute .ctor method is valid so System.Boolean should be defined as well. In short ```GetSpecialType(SpecialType.System_Boolean)``` should not fail here. 

An alternative fix is to leave this method unchanged but simply remove the invalid check from `AddSynthesizedAttributes` below since it will not fail after checking for ```DynamicAttribute..ctor```.

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs [hunk 2]
```diff
@@ -159,9 +159,7 @@ internal override void AddSynthesizedAttributes(ModuleCompilationState compilati
             // this is a no-op.  Emitting an error here, or when the original parameter was bound, would
             // adversely effect the compilation or potentially change overload resolution.  
             var compilation = this.DeclaringCompilation;
-            if (Type.ContainsDynamic() && 
-                compilation.HasDynamicEmitAttributes() &&
-                compilation.GetSpecialType(SpecialType.System_Boolean).SpecialType == SpecialType.System_Boolean)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs]: If I remember correctly, Jared's intent was to ensure boolean type is available and is good (similar to how it is done in Binder.ReportUseSiteDiagnosticForDynamic). Simply removing this condition wouldn't be the right thing to do, instead we should change it to check that symbol for the boolean type doesn't have use-site error (use-site warning is Ok).

File: src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs]: GetSpecialType never fails, i.e. it never returns null and this is what the assert was about. I think changes to this function should be reverted.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs]: BTW, presence of the constructor doesn't guarantee that boolean type is available. This fact should be checked separately.

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs (hunk 2 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs]: The link to a PR comment in the issue has the following information regarding the value returned by GetSpecialType:
if GetUseSiteDiagnostic() for it returns non-null DiagnosticInfo with Severity == error then it is bad/missing.

Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs]: Updated to call `GetUseSiteDiagnostic()`.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs]: The diagnostic can be a warning, our goal is to check for errors. See my previous comment in this thread.

File: src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_Dynamic.cs [hunk 3]
```diff
@@ -1235,8 +1229,40 @@ public static void Main()
...
                     "C+<>c", 
                     "<Main>b__0_0",
-                    ".method assembly hidebysig instance System.Object <Main>b__0_0([System.Runtime.CompilerServices.DynamicAttribute()] System.Object x) cil managed")
+                    ".method assembly hidebysig instance System.Object <Main>b__0_0([System.Runtime.CompilerServices.DynamicAttribute()] System.Object x, [System.Runtime.CompilerServices.DynamicAttribute(System.Collections.ObjectModel.ReadOnlyCollection`1[System.Reflection.CustomAttributeTypedArgument])] System.Object[] y) cil managed")
             });
         }
+
+        [Fact]
+        [WorkItem(6126, "https://github.com/dotnet/roslyn/issues/6126")]
+        public void DynamicLambdaParametersMissingBoolean()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_Dynamic.cs]: Thank you for  adding the test.

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs (hunk 2 above)
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs]: Updated condition.

**Comment by AlekseyTs** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs [hunk 4]
```diff
@@ -159,11 +159,14 @@ internal override void AddSynthesizedAttributes(ModuleCompilationState compilati
...
+            if (Type.ContainsDynamic() && compilation.HasDynamicEmitAttributes())
             {
-                AddSynthesizedAttribute(ref attributes, compilation.SynthesizeDynamicAttribute(this.Type, this.CustomModifiers.Length, this.RefKind));
+                var boolType = compilation.GetSpecialType(SpecialType.System_Boolean);
+                var diagnostic = boolType.GetUseSiteDiagnostic();
+                if ((diagnostic == null) || (diagnostic.Severity != DiagnosticSeverity.Error))
+                {
+                    AddSynthesizedAttribute(ref attributes, compilation.SynthesizeDynamicAttribute(this.Type, this.CustomModifiers.Length, this.RefKind));
+                }
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedParameterSymbol.cs]: Can we be sure (in the hypothetical `else` clause of this `if`) that an error has already been reported?

File: src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_Dynamic.cs [hunk 5]
```diff
@@ -1235,8 +1229,40 @@ public static void Main()
...
+        d(null);
+    }
+}";
+            var comp = CreateCompilation(source0);
+            comp.VerifyDiagnostics();
+            var ref0 = comp.EmitToImageReference();
+            comp = CreateCompilation(source1, references: new[] { ref0, SystemCoreRef });
+            comp.VerifyDiagnostics();
+            // Make sure we emit without errors when System.Boolean is missing.
+            CompileAndVerify(comp, verify: false);
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_Dynamic.cs]: Should there be an emit error or something? It seems we shouldn't allow this compilation to emit the incorrect API (which has `dynamic` appearing as `object`)?

Comment (cston) [inline src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_Dynamic.cs]: I believe the intention was to not emit the `[DynamicAttribute]` in this case (and not generate any errors, allowing emit to succeed) since the attribute is only used in the debugger EE.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_Dynamic.cs]: @gafter This is correct. The intention is to not emit the [DynamicAttribute] in this case (and not generate any errors, allowing emit to succeed). In any case this question is out of scope of this PR and the issue we are trying to address. This decision was made when the original PR (the one that introduced the modified condition) was worked on.

**Comment by cston** [comment]
Test prtest/win/dbg/eta please
