### PR TITLE
Statically bind invocations in presence of dynamic arguments only for local functions

### LINKED ISSUE #72750: Language changes are breaking real-world use of dynamic
**Version Used**: 
Version 17.10.0 Preview 3.0 [34721.271.main]

**Steps to Reproduce**:
```C#
using System.Text.Json;

public class C
{
    public static C M(IFoo foo, dynamic value)
    {
        var result = foo.Bar("name", value);
        return JsonSerializer.Deserialize<C>(result);
    }
}

public interface IFoo
{
    object Bar(string name, object value);
}
```

**Expected Behavior**:
Previously this compiled fine.
[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgPgAQAwAIEEYB0AVApgDwBdMApAZwHsYBuAWACgGEBmNAJhQGEGBvBlAWlYYAbFxQBZABQBJAGIUKKAGaKANCgAmATxgQwUAMYoAbhAA2AV1wBKfoL71Bz0xABOKN7jKXzhFAC8KoqYAELuUgBEemC4kRpmVrZ0Ti4CCADsKORUAMq4blAWUABeBZgAIt4FRealuAA8nAB8Ul4+fjYpzgC+DH2M9CwosIQFyhCGuCjyirz2AhTAAFa4hv7hblIYqDG4Gkur665JXf1AA=)

**Actual Behavior**:
Now it fails to compile:
```
error CS1503: Argument 1: cannot convert from 'object' to 'System.IO.Stream'
```
After the recent changes around `dynamic`, the type of `result` is now `object` whereas previously it was `dynamic`.

[jcouv:] Relates to https://github.com/dotnet/roslyn/pull/71421

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #72750.

This implements the latest LDM decision.
In order to make sure all artifacts of the previous fix (#72964) were removed, I reverted all implementation (but not test changes) from that PR by using 'git revert`. All cleanups/refactorings that are still relevant were manually ported back.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
>                 // (10,18): warning CS8624: Argument of type 'dynamic' cannot be used as an output of type 'int' for parameter 'x' in 'void C2.Deconstruct(out int x, out int y)' due to differences in the nullability of reference types.

This warning looks very strange. I'll open an issue to follow-up.

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/DynamicTests.cs:10599 in 8c74aca. [](commit_id = 8c74acaccad416fd681fea4e2d9fa6f6c2227156, deletion_comment = False)

**Comment by AlekseyTs** [comment]
@jcouv, @RikkiGibson, @dotnet/roslyn-compiler Please review

**Comment by AlekseyTs** [comment]
@jcouv, @RikkiGibson, @dotnet/roslyn-compiler Please review

**Comment by jcouv** [comment]
Let's refresh https://github.com/dotnet/csharplang/pull/8027 to capture the final design

**Comment by AlekseyTs** [comment]
I am planning to do that. The change mostly will be as simple as moving the "Dynamic" section into the alternatives section.

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs [hunk 1]
```diff
@@ -1118,23 +1118,20 @@ internal bool HasCollectionExpressionApplicableAddMethod(SyntaxNode syntax, Type
...
-                                Debug.Assert(finalApplicableCandidates.Length > 0);
-
                                 addMethods = filterOutBadGenericMethods(addMethodBinder, syntax, methodGroup, analyzedArguments, resolution, finalApplicableCandidates, ref useSiteInfo);
                                 result = !addMethods.IsEmpty;
 
                                 if (!result)
                                 {
                                     diagnostics.Add(ErrorCode.ERR_CollectionExpressionMissingAdd, syntax, methodGroup.ReceiverOpt.Type);
                                 }
+                                else if (addMethods.Length == 1)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:1130]: It's hard to tell whether we're keeping the correspondence with `BindMethodGroupInvocation`. What does this correspond to?

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 8)

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:1130]: > It's hard to tell whether we're keeping the correspondence with ```BindMethodGroupInvocation```. What does this correspond to?

It corresponds to the code at the end of ```bindInvocationExpressionContinued``` below. We are not going after exact match with ```BindMethodGroupInvocation``` because the argument that we are using is fake and we aways end up here we we have a single applicable candidate. Before the change we were ending up in ```bindInvocationExpressionContinued``` through ```tryEarlyBindSingleCandidateInvocationWithDynamicArgument```.

**Comment by AlekseyTs** [comment]
@RikkiGibson, @dotnet/roslyn-compiler For the second review

**Comment by AlekseyTs** [comment]
@RikkiGibson, @dotnet/roslyn-compiler For the second review

**Comment by RikkiGibson** [comment]
Taking a look

**Review by RikkiGibson — APPROVED** [review]

**Comment by AlekseyTs** [comment]
>                 // (10,18): warning CS8624: Argument of type 'dynamic' cannot be used as an output of type 'int' for parameter 'x' in 'void C2.Deconstruct(out int x, out int y)' due to differences in the nullability of reference types.

Opened # 73374

---
In reply to: [2091415087](https://github.com/dotnet/roslyn/pull/73314#issuecomment-2091415087) [](http://example.com/codeflow?ancestors=2091415087)

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/DynamicTests.cs:10599 in 8c74aca. [](commit_id = 8c74acaccad416fd681fea4e2d9fa6f6c2227156, deletion_comment = False)
