### PR TITLE
Adjust ERR_PartialMisplaced diagnostic message

### LINKED ISSUE #48472: CS0267 error message no longer correct (for C#9 partial methods)
**Version Used**: 

Microsoft Visual Studio Community 2019 Preview
Version 16.8.0 Preview 3.1

C# Tools   3.8.0-3.20458.6+b446afd34759150c2ea3b86ab794104e12e64db1

**Steps to Reproduce**:

1. Write code:
```c#
class X
{
    partial public string Foo();
}
```
2. Observe CS0267 on `partial` modifier.
3. Be confused by error message.

**Expected Behavior**:

Error message communicating invalid `partial` placement taking new partial methods (non-void) into account. I don't have a good proposal, but maybe addition of 'or method return type' would be enough.

**Actual Behavior**:

CS0267 says
> The partial modifier can only appear immediately before 'class', 'record', 'struct', 'interface' or 'void'

It misses the non-void return type allowed on C#9 partial methods.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #48472

### CODE REVIEW

**Review by cston — APPROVED** [review]

**Comment by Youssef1313** [comment]
Parallel docs PR: https://github.com/dotnet/docs/pull/21047

**Review by AlekseyTs — APPROVED** [review]
LGTM (iteration 1)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 1]
```diff
@@ -52748,6 +52748,29 @@ static void F3(object? x3, object y3)
                 Diagnostic(ErrorCode.WRN_NullReferenceReceiver, "z2").WithLocation(22, 9));
         }
 
+        [Fact]
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:52751]: welp, I pushed to the wrong branch.
