### PR TITLE
Fix XmlTextAttribute space normalization

### LINKED ISSUE #60884: SyntaxTree generated XML document comments attribute params source text incorrect
**Version Used**:  Microsoft.CodeAnalysis.CSharp v4.1.0

**Steps to Reproduce**:

1.  Open a command shell, and Run the following commands:

```
dotnet new console -o syntaxtree
cd syntaxtree
dotnet add package Microsoft.CodeAnalysis.CSharp
```

2.  Open `Program.cs` and replace the content with the following code:

```csharp
using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

/*
public interface IScoreGrain
{
    /// <param name="pid" example="10455"></param>
    public Task<int> GetScore(string pid);
}
*/

var tree = SyntaxTree(
//CODE FROM ROSLYN QUOTER:
CompilationUnit()
.WithMembers(
    SingletonList<MemberDeclarationSyntax>(
        InterfaceDeclaration("IScoreGrain")
        .WithModifiers(
            TokenList(
                Token(SyntaxKind.PublicKeyword)))
        .WithMembers(
            SingletonList<MemberDeclarationSyntax>(
                MethodDeclaration(
                    GenericName(
                        Identifier("Task"))
                    .WithTypeArgumentList(
                        TypeArgumentList(
                            SingletonSeparatedList<TypeSyntax>(
                                PredefinedType(
                                    Token(SyntaxKind.IntKeyword))))),
                    Identifier("GetScore"))
                .WithModifiers(
                    TokenList(
                        Token(
                            TriviaList(
                                Trivia(
                                    DocumentationCommentTrivia(
                                        SyntaxKind.SingleLineDocumentationCommentTrivia,
                                        List<XmlNodeSyntax>(
                                            new XmlNodeSyntax[]{
                                                XmlText()
                                                .WithTextTokens(
                                                    TokenList(
                                                        XmlTextLiteral(
                                                            TriviaList(
                                                                DocumentationCommentExterior("///")),
                                                            " ",
                                                            " ",
                                                            TriviaList()))),
                                                XmlExampleElement()
                                                .WithStartTag(
                                                    XmlElementStartTag(
                                                        XmlName(
                                                            Identifier(
                                                                TriviaList(),
                                                                SyntaxKind.ParamKeyword,
                                                                "param",
                                                                "param",
                                                                TriviaList())))
                                                    .WithAttributes(
                                                        List<XmlAttributeSyntax>(
                                                            new XmlAttributeSyntax[]{
                                                                XmlNameAttribute(
                                                                    XmlName(
                                                                        Identifier("name")),
                                                                    Token(SyntaxKind.DoubleQuoteToken),
                                                                    IdentifierName("pid"),
                                                                    Token(SyntaxKind.DoubleQuoteToken)),
                                                                XmlTextAttribute(
                                                                    XmlName(
                                                                        Identifier("example")),
                                                                    Token(SyntaxKind.DoubleQuoteToken),
                                                                    Token(SyntaxKind.DoubleQuoteToken))
                                                                .WithTextTokens(
                                                                    TokenList(
                                                                        XmlTextLiteral(
                                                                            TriviaList(),
                                                                            "10455",
                                                                            "10455",
                                                                            TriviaList())))})))
                                                .WithEndTag(
                                                    XmlElementEndTag(
                                                        XmlName(
                                                            Identifier(
                                                                TriviaList(),
                                                                SyntaxKind.ParamKeyword,
                                                                "param",
                                                                "param",
                                                                TriviaList())))),
                                                XmlText()
                                                .WithTextTokens(
                                                    TokenList(
                                                        XmlTextNewLine(
                                                            TriviaList(),
                                                            "\n",
                                                            "\n",
                                                            TriviaList())))})))),
                            SyntaxKind.PublicKeyword,
                            TriviaList())))
                .WithParameterList(
                    ParameterList(
                        SingletonSeparatedList<ParameterSyntax>(
                            Parameter(
                                Identifier("pid"))
                            .WithType(
                                PredefinedType(
                                    Token(SyntaxKind.StringKeyword))))))
                .WithSemicolonToken(
                    Token(SyntaxKind.SemicolonToken))))))
.NormalizeWhitespace()
//END
);

Console.WriteLine(tree.ToString());
```

3. Run app

```
dotnet run
```

**Expected Behavior**:

```csharp
public interface IScoreGrain
{
    /// <param name="pid" example="10455"></param>
    public Task<int> GetScore(string pid);
}
```

**Actual Behavior**:

```csharp
public interface IScoreGrain
{
    /// <param name = "pid"example="10455"></param>
    public Task<int> GetScore(string pid);
}
```

### PR DESCRIPTION
**Pull request by andrew-boyarshin**
Fixes #60884

### CODE REVIEW

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs [hunk 1]
```diff
@@ -1245,5 +1245,40 @@ private void TestNormalize(SyntaxTriviaList trivia, string expected)
...
+        [WorkItem(60884, "https://github.com/dotnet/roslyn/issues/60884")]
+        public void TestNormalizeXmlArgumentsInDocComment2()
+        {
+            const string Expected = @"/// Prefix <b a=""x"" b=""y"">S_OK</b> suffix";
+            TestNormalizeDeclaration(Expected, Expected);
+        }
+
+        [Fact]
+        [WorkItem(60884, "https://github.com/dotnet/roslyn/issues/60884")]
+        public void TestNormalizeXmlArgumentsInDocComment3()
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs:1268]: Can you add a version of this that does not have a leading space before the `/>` in the original text?

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs [hunk 2]
```diff
@@ -1265,5 +1265,19 @@ private static int GetDeclarationDepth(SyntaxNode? node)
...
+            var attribute = (XmlTextAttributeSyntax?)base.VisitXmlTextAttribute(node);
+
+            if (attribute is null or { HasTrailingTrivia: true })
+            {
+                return attribute;
+            }
+
+            return GetNextRelevantToken(node.EndQuoteToken).Kind() != SyntaxKind.GreaterThanToken
+                       ? attribute.WithTrailingTrivia(GetSpace())
+                       : attribute;
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs:1280]:
```suggestion
                ? attribute.WithTrailingTrivia(GetSpace())
                : attribute;
```

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs [hunk 3]
```diff
@@ -1245,5 +1245,40 @@ private void TestNormalize(SyntaxTriviaList trivia, string expected)
...
+        {
+            const string Expected = @"/// Prefix <b a=""x"" b=""y"" /> suffix";
+            const string Text = @"/// Prefix <b a=""x"" b=""y"" /> suffix";
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs:1271]: >  [](http://example.com/codeflow?start=55&length=1)

Is it syntactically valid to omit the space between the XML attributes? Consider adding a test.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 1)

**Comment by andrew-boyarshin** [comment]
@333fred @CyrusNajmabadi @AlekseyTs I believe I addressed concerns raised during review pass 1.

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs (hunk 3 above)
Comment (andrew-boyarshin) [reply src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs:1271]: No, it's not, at least not for all XML parsers. I actually need this fix in Roslyn because `DocumentationCommentCompiler` failed on generated Roslyn syntax trees after normalization. However, I added 2 tests to show normalization can now fix issues in XML trees such as the missing spaces between the attributes.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 2)

**Comment by AlekseyTs** [comment]
@333fred For the second review.

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs [hunk 4]
```diff
@@ -1265,5 +1265,19 @@ private static int GetDeclarationDepth(SyntaxNode? node)
...
+        {
+            var attribute = (XmlTextAttributeSyntax?)base.VisitXmlTextAttribute(node);
+
+            if (attribute is null or { HasTrailingTrivia: true })
+            {
+                return attribute;
+            }
+
+            return GetNextRelevantToken(node.EndQuoteToken).Kind() != SyntaxKind.GreaterThanToken
+                ? attribute.WithTrailingTrivia(GetSpace())
```
Comment (sharwell) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs:1279]: ❗ While this space is generally desirable for highly structured documents (e.g. project files), it causes unnecessary noise and wrapping characteristics for the common self-closing XML elements in documentation (e.g. `<see langword="null"/>` or `<paramref name="text"/>`. There should not be any space between `"` and `/>` for these elements.

**Review by sharwell — CHANGES_REQUESTED** [review]

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs (hunk 1 above)
Comment (sharwell) [reply src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs:1268]: ➡️ I have requested the other form in https://github.com/dotnet/roslyn/pull/61012#discussion_r866469118.

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs (hunk 4 above)
Comment (sharwell) [reply src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs:1279]: 📝 Note that two other features we have today will generate code without this space:

1. Type `null` and press <kbd>Ctrl</kbd>+<kbd>Space</kbd>
2. Type `null` and press <kbd>Ctrl</kbd>+<kbd>.</kbd> &rarr; **Use &lt;see langword="null"/>**

**Comment by andrew-boyarshin** [comment]
I see the reasoning behind such formatting style, and like I said before, it's up to Roslyn team in the end. I believe I made the necessary change and reflected that in tests.

**Review by sharwell — APPROVED** [review]

**Review by 333fred — APPROVED** [review]

**Comment by 333fred** [comment]
Thanks @andrew-boyarshin!
