### PR TITLE
Handle TMP correctly in compiler server

### LINKED ISSUE #13995: Compiler server doesn't handle bad TMP values correctly
In order to sign binaries today the compiler has to write the PEs temporarily out to a temporary folder.  That is to satisfy the constraint of the CLR signing mechanism which can only work with on disk binaries.  In the future we are going to move to in memory signing but for now we must write to disk.

The compiler uses `Path.GetTempFileName` to create this file.  This was ported from the native compiler that used Win32 `GetTempFileName`.  Both of these functions call into Win32 `GetTempPath`.  

The use of `GetTempPath` in the server is questionable.  One of the values that is considered by this function is `GetCurrentDirectory`.  In particular when `%TMP%` is a relative path, `GetTempPath` will essentially attempt to resolve it as:

```
Path.Combine(
  Environment.GetCurrentDirectory()
  Environment.GetEnvironmentVariable("TMP"));
```

This works fine in the command line compiler because there is one compilation and one working directory.  In the server it can fail because a collection of compilations share a working directory.  

This appears to be one bit of process wide state that we haven't accounted for.

### PR DESCRIPTION
**Pull request by jaredpar**
This PRC is broken into two commits to help with reviewing: 

1. Threading `BuildPaths` through the entire code base.  This unified argument passing of build paths and greatly simplified the second change.  This change is mechanical.
2. Implementing the TMP change.  

Here is the full commit message from the second commit which explains the purpose in need. 

The compiler must make use of a temporary path when signing files.  This is a restriction forced on us by the underlying CLR signing APIs.

Historically the compiler used `Path.GetTempPath` (`GetTempPath` in native) as the location to write the temporary files.  This is unsuitable for the compiler server as it makes use of several pieces of process global state that be different between build invocations: TMP, TEMP, USERPROFILE and the current working directory.

In general these variables are the same between invocations but in larger build systems it's not uncommon for TEMP / TMP in particular to be manipulated and set to invalid values.  This can lead to builds where signing fails in the server but passes in the command line.  This occurs because the server gets the initial TEMP value and uses it for all compilations while the command line gets a fresh TEMP value on every invocation.

To work around this the compiler must thread through the temporary path as a build parameter.  This is the general approach we've taken for all state that is typically process global but can differ from invocation to invocation.

Also need a custom implementation of `GetTempPath` in order to pass down the correct working directory.

closes #13995

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-compiler

**Comment by jaredpar** [comment]
CC @MattGertz for ask mode approval.

**Comment by MattGertz** [comment]
Scenario meets the bar; approved pending signoff & test success.

**Comment by jasonmalinowski** [comment]
FYI this pull request missed the snap from master and will need to be retargeted to dev15-rc. GitHub supports doing that now, just hit edit at the top.

**Comment by jaredpar** [comment]
@jasonmalinowski thanks.  Updated.

**Comment by AlekseyTs** [comment]
It looks like all windows based tests failed. Is this related to the change?

**Comment by jaredpar** [comment]
@AlekseyTs the unit tests are all passing (save one DLL which I'm about to push a fix for).  There is a problem in MSBuild loading the new binaries during the self host build.  I'm currently trying to debug this and figure out what is going on.

File: src/Compilers/Server/VBCSCompilerTests/DesktopBuildClientTests.cs [hunk 1]
```diff
@@ -70,16 +70,17 @@ public bool TryConnectToNamedPipeWithSpinWait(int timeoutMs, CancellationToken c
...
             private readonly BuildPaths _buildPaths;
             private readonly List<ServerData> _serverDataList = new List<ServerData>();
             private bool _allowServer = true;
             private int _failedCreatedServerCount = 0;
 
             public ServerTests()
             {
-                _tempDirectory = Temp.CreateDirectory();
-                _buildPaths = ServerUtil.CreateBuildPaths(workingDir: _tempDirectory.Path);
+                var wo = Temp.CreateDirectory();
```
Comment (AlekseyTs) [inline src/Compilers/Server/VBCSCompilerTests/DesktopBuildClientTests.cs]: >var wo = Temp.CreateDirectory() [](start = 16, length = 31)

Why is this line needed?

**Comment by AlekseyTs** [comment]
LGTM

**Comment by jaredpar** [comment]
This is the MSBuild bug that I had to work around with an explicit reference to MSBuild 14.0. 

https://github.com/Microsoft/msbuild/issues/1183

I'm unsure how to approach this with respect to checking in.  Going to follow up with @jasonmalinowski in the morning.

File: src/Compilers/Server/VBCSCompilerTests/DesktopBuildClientTests.cs (hunk 1 above)
Comment (jaredpar) [inline src/Compilers/Server/VBCSCompilerTests/DesktopBuildClientTests.cs]: It's not.  It's a line left over from an earlier version of the change.  Will delete.

**Comment by jaredpar** [comment]
@agocke can you review this please?

File: src/Compilers/CSharp/Test/Emit/Emit/DesktopStrongNameProviderTests.cs [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+    public partial class DesktopStrongNameProviderTests : CSharpTestBase
+    {
+        [WorkItem(13995, "https://github.com/dotnet/roslyn/issues/13995")]
+        [Fact]
+        public void RespectCustomTempPath()
+        {
+            var tempDir = Temp.CreateDirectory();
+            Directory.CreateDirectory(tempDir.Path);
+            var provider = new DesktopStrongNameProvider(tempPath: tempDir.Path);
+            var stream = (DesktopStrongNameProvider.TempFileStream)provider.CreateInputStream();
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit/Emit/DesktopStrongNameProviderTests.cs]: Consider `using (var stream = ...) { ... }` in these tests.

File: src/Compilers/CSharp/Test/Emit/Emit/DesktopStrongNameProviderTests.cs [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+namespace Microsoft.CodeAnalysis.CSharp.UnitTests
+{
+    public partial class DesktopStrongNameProviderTests : CSharpTestBase
+    {
+        [WorkItem(13995, "https://github.com/dotnet/roslyn/issues/13995")]
+        [Fact]
+        public void RespectCustomTempPath()
+        {
+            var tempDir = Temp.CreateDirectory();
+            Directory.CreateDirectory(tempDir.Path);
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit/Emit/DesktopStrongNameProviderTests.cs]: Doesn't `Temp.CreateDirectory()` create the directory?

File: src/Compilers/Core/CommandLine/BuildClient.cs [hunk 4]
```diff
@@ -233,5 +207,46 @@ private static IEnumerable<string> GetCommandLineWindows(IEnumerable<string> arg
...
+                }
+            }
+
+            var userProfile = Environment.GetEnvironmentVariable("USERPROFILE");
+            if (Path.IsPathRooted(userProfile))
+            {
+                return userProfile;
+            }
+
+            return Environment.GetEnvironmentVariable("SYSTEMROOT");
```
Comment (cston) [inline src/Compilers/Core/CommandLine/BuildClient.cs]: These environment variables look Windows specific. Is this method used on other platforms?

File: src/Compilers/Core/CommandLine/BuildProtocol.cs [hunk 5]
```diff
@@ -507,6 +514,9 @@ public enum ArgumentId
 
             // Request a server shutdown from the client
             Shutdown,
+
+            // The directory to use for temporary operations.
+            TempDirectory,
```
Comment (cston) [inline src/Compilers/Core/CommandLine/BuildProtocol.cs]: Should `ProtocolVersion` change?

File: src/Compilers/Server/ServerShared/CompilerRequestHandler.cs [hunk 6]
```diff
@@ -94,6 +93,14 @@ public BuildResponse RunCompilation(RunRequest request, CancellationToken cancel
                 Log($"Argument[{i}] = '{request.Arguments[i]}'");
             }
 
+            // Compiler server must be provided wiht a valid temporary directory in order to correctly
```
Comment (cston) [inline src/Compilers/Server/ServerShared/CompilerRequestHandler.cs]: Typo: `with`

File: src/Compilers/Server/VBCSCompilerTests/CompilerServerHostTests.cs [hunk 7]
```diff
@@ -0,0 +1,47 @@
...
+                return true;
+            }
+        }
+
+        [WorkItem(13995, "https://github.com/dotnet/roslyn/issues/13995")]
+        [Fact]
+        public void RejectEmptyTempPath()
+        {
+            var host = new TestableCompilerServerHost();
+            var request = new RunRequest(LanguageNames.CSharp, currentDirectory: @"c:\current", tempDirectory: null, libDirectory: null, arguments: Array.Empty<string>());
```
Comment (cston) [inline src/Compilers/Server/VBCSCompilerTests/CompilerServerHostTests.cs]: Consider using `currentDirectory: Temp.CreateDirectory().Path` instead, to ensure the path matches the current platform, and to ensure that if `RunRequest` actually writes to that path (now or in the future), the path is temporary.

File: src/Compilers/Test/Utilities/CSharp.Desktop/MockCSharpCompiler.cs [hunk 8]
```diff
@@ -19,12 +19,21 @@ public MockCSharpCompiler(string responseFile, string baseDirectory, string[] ar
...
 
-        public MockCSharpCompiler(string responseFile, string baseDirectory, string[] args, ImmutableArray<DiagnosticAnalyzer> analyzers)
-            : base(CSharpCommandLineParser.Default, responseFile, args, Path.GetDirectoryName(typeof(CSharpCompiler).Assembly.Location), baseDirectory, RuntimeEnvironment.GetRuntimeDirectory(), Environment.GetEnvironmentVariable("LIB"), new DesktopAnalyzerAssemblyLoader())
+        public MockCSharpCompiler(string responseFile, string workingDirectory, string[] args, ImmutableArray<DiagnosticAnalyzer> analyzers)
+            : base(CSharpCommandLineParser.Default, responseFile, args, CreateBuildPaths(workingDirectory), Environment.GetEnvironmentVariable("LIB"), new DesktopAnalyzerAssemblyLoader())
         {
             _analyzers = analyzers;
         }
 
+        public static BuildPaths CreateBuildPaths(string workingDirectory)
```
Comment (cston) [inline src/Compilers/Test/Utilities/CSharp.Desktop/MockCSharpCompiler.cs]: `private`, here and in other instances of `CreateBuildPaths` below.

File: src/Compilers/CSharp/Test/Emit/Emit/DesktopStrongNameProviderTests.cs [hunk 9]
```diff
@@ -0,0 +1,70 @@
...
+}";
+            var tempDir = Temp.CreateDirectory();
+            Directory.CreateDirectory(tempDir.Path);
+            var provider = new VirtualizedStrongNameProvider(tempPath: tempDir.Path);
+            var options = TestOptions
+                .DebugExe
+                .WithStrongNameProvider(provider)
+                .WithCryptoKeyFile(SigningTestHelpers.KeyPairFile);
+            var comp = CreateCompilationWithMscorlib(src, options: options);
+            comp.Emit(new MemoryStream()).Diagnostics.Verify();
```
Comment (agocke) [inline src/Compilers/CSharp/Test/Emit/Emit/DesktopStrongNameProviderTests.cs]: Or just `VerifyEmitDiagnostics()`

File: src/Compilers/Shared/DesktopBuildClient.cs [hunk 10]
```diff
@@ -122,6 +118,16 @@ protected override int RunLocalCompilation(string[] arguments, BuildPaths buildP
             Func<string, string, bool> tryCreateServerFunc,
             CancellationToken cancellationToken)
         {
+            if (pipeName == null)
```
Comment (agocke) [inline src/Compilers/Shared/DesktopBuildClient.cs]: Why is this moved down?

File: src/Compilers/CSharp/Test/Emit/Emit/DesktopStrongNameProviderTests.cs (hunk 3 above)
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Emit/Emit/DesktopStrongNameProviderTests.cs]: Could have sworn it wasn't in my tests.  Must be user error.  Will remove.

File: src/Compilers/CSharp/Test/Emit/Emit/DesktopStrongNameProviderTests.cs (hunk 2 above)
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Emit/Emit/DesktopStrongNameProviderTests.cs]: Will do

File: src/Compilers/Core/CommandLine/BuildClient.cs (hunk 4 above)
Comment (jaredpar) [inline src/Compilers/Core/CommandLine/BuildClient.cs]: Not at the moment.  The server is Windows specific.  On non-windows machines we don't use temp path either due to not supporting signing.  But point taken.  Should contider an alternate implementation here for non-Windows.

File: src/Compilers/Core/CommandLine/BuildProtocol.cs (hunk 5 above)
Comment (jaredpar) [inline src/Compilers/Core/CommandLine/BuildProtocol.cs]: I think it should probably be deleted.  It's not even relevant with the way we changed the pipe names.  Let me think about it for a sec.

File: src/Compilers/Shared/DesktopBuildClient.cs (hunk 10 above)
Comment (jaredpar) [inline src/Compilers/Shared/DesktopBuildClient.cs]: So that I could do all argument verification in one function.

File: src/Compilers/Core/CommandLine/BuildClient.cs (hunk 4 above)
Comment (jaredpar) [inline src/Compilers/Core/CommandLine/BuildClient.cs]: https://github.com/dotnet/roslyn/issues/14685

File: src/Compilers/Core/CommandLine/BuildProtocol.cs (hunk 5 above)
Comment (jaredpar) [inline src/Compilers/Core/CommandLine/BuildProtocol.cs]: https://github.com/dotnet/roslyn/issues/14686

**Comment by agocke** [comment]
LGTM
