### PR TITLE
Simplify diagnostic tagging by making it use the standard tagging model.

### LINKED ISSUE #24055: Microsoft CodeAnalysis OOM Exception
Ported from https://github.com/dotnet/roslyn-analyzers/issues/1503

-----------------------------
@chillryan

I've reported this issue through the visual studio feedback tool [see link](https://developercommunity.visualstudio.com/content/problem/174842/visual-studio-155-crashes-when-switching-git-branc.html) but figured I'd try my chances posting here.

I'm using the Code Analysis 2017 extension for VS 2017 15.5. In looking at the stack trace, I can only assume that since the extension is running inside the devenv process, when its analysis a loaded solution, it hits the OOM. 

Since I've hit this situation a very frequent basis, I've disabled solution analysis for C# projects hoping that will help. I'll report back here if there are any changes or comment on the visual studio feedback link posted prior.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
### Customer scenario

User is working on a big solution and switching between git branches multiple times or close and reopen solutions multiple times. and on some unfortunate cases, VS will crash with out of memory exception. 

### Bugs this fixes

Fixes #24055
Fixes [DevDiv 512757](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/512757)

Supersedes #22920, #23377, #23409, #23411

### Workarounds, if any

after each git branch switching or solution open/close, give VS sometimes to process pending works enqueued by the operation.

### Risk

this simplify our diagnostic tagger dramatically. so there is a risk where behavior might not exactly same as before. but we believe this is right direction to go. 

### Performance impact

this should remove OOM due to too many pending UI work items completely. that is source of most of our OOM crash.

### Is this a regression from a previous update?

No

### Root cause analysis

previously, diagnostic service didn't support pull model for all diagnostics source. so, tagger used event (push model) to hold onto last reported diagnostics and later use that to report tags. and that made us to use custom logic for the tagger which ends up forcing us to use UI thread to synchronize many states to remove potential race. and that caused us to push too many work items to UI thread in certain case such as git branch switching.

now, diagnostic service fully supporting pull model for all sources, this moves diagnostic taggers to follow our tagger framework which doesn't require UI thread for state synchronization. removing the root cause of OOM from the picture completely.

### How was the bug found?

MemoryWatson

....

more dev detail.

From a conversation with @heejaechang https://github.com/dotnet/roslyn/pull/23409#issuecomment-347675771 

A while back the diagnostics subsystem had a limitation where you could only hear about some diagnostics if you explicitly listened for diagnostic events.  i.e. if you weren't listenting and capturing those events, you couldn't go back and ask for those diagnostics later.  This meant that we couldn't do diagnostic tagging (squiggles/fading/suggestions) like we did normal tagging. Normal tagging hears about events, pauses a bit, then goes and gets all the data necessary later to produce the tags.  Because that data wasn't available 'later', diagnostic tagging had to aggregate the info and contort things to fit into the tagging infrastructure.

This restriction from the diagnostics service no longer exists. THat means we can great simplify how we do our tagging computation.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @heejaechang @sharwell .

Note: this approach in incorrect in a very fundamental way currently.  Wanted to start the discussion with you on how we might fix that.

**Comment by CyrusNajmabadi** [comment]
@heejaechang I took the appraoch whereby the event passes along the diagnostic id that was updated. However, this approach is fundamentally flawed with how tagging works currently.  The reason for that is that tagging is hugely cancellable.  i.e. any time tagging gets an event, it cancels the current work and enqueues the new recomputation.  The assumption is that any recomputation supersedes any previous or inflight computation.  

That's not the case with this optimization.  For example, if we heard about a global "recompute tags for all providers" notification, we can't supersede that with a request to recompute tags for a single provider id.

We have a few options here afaict (other suggestions welcome!):

1. don't pass along the data about which provider changed.  always recompute all providers.  Pros: super simple.  Cons: possibly expensive (though we are on the BG).
2. somehow make some parts of tagging conditionally cancellable.  so a single provider update could cancel an update for that provider.  But a provider update would not cancel the updates for other providers.  Pros: fine grained updating.  Cons: super complex (i can't see a suitable way to do this, not with how cancellation is threaded through tagging).
3. have the diagnostic service track which providers changed.  have a way for tagging to call in and ask if things have changed for any of the Ids.  Pros: simple on the tagging side.  Cons: may not actually be any more efficient.  May be just as complex on the diagnostic side.

Thoughts?

**Comment by heejaechang** [comment]
I think we can go with simple approach and do some perf investigation and see whether we need to optimize more.

...

by the way, even with this approach, it doesnt remove the fact that diagnostic service is based on solution, and tagger is based on buffer and dynamically buffer to workspace and buffer to document association can be changed. in other word, we still need to filter out diagnostic events that is not associated with this subject buffer 

(see https://github.com/dotnet/roslyn/pull/22920/files#r153666048 if we want document specific events)

..

we also can make diagnostic event source to aggregate object ids as we aggregate text changes on text change event source.

**Comment by CyrusNajmabadi** [comment]
> by the way, even with this approach, it doesnt remove the fact that diagnostic service is based on solution, and tagger is based on buffer and dynamically buffer to workspace and buffer to document association can be changed. in other word, we still need to filter out diagnostic events that is not associated with this subject buffer

That already happens here: https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/Shared/Tagging/EventSources/TaggerEventSources.DiagnosticsChangedEventSource.cs#L28

**Comment by CyrusNajmabadi** [comment]
> I think we can go with simple approach and do some perf investigation and see whether we need to optimize more.

Do you mean approach #1 ?

**Comment by heejaechang** [comment]
ha, we had that before? interesting...

**Comment by heejaechang** [comment]
@CyrusNajmabadi yep. I mean (1).

basically whenever there is event source changes, we do what we currently do for initial tags. ask all diagnostics reported on this file, filter out empty and not related ones (suggestion/unnecessary/regular), and report rest. we no longer need sub taggers since we always report all of them.

really simple. and common case, probably good enough. probably will have issues for corner cases where file contains thousands of errors since it will repeatedly report those.

**Comment by CyrusNajmabadi** [comment]
> probably will have issues for corner cases where file contains thousands of errors since it will repeatedly report those.

Well, we'll still always diff the spans against the old ones.  So we'll only report the change.

**Comment by CyrusNajmabadi** [comment]
Ok.  I pushed the simpler model.  take a look when you get a chance.

File: src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs [hunk 1]
```diff
@@ -22,47 +31,131 @@ namespace Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics
...
+            var id = updateArgs.Id;
+            var diagnostics = _diagnosticService.GetDiagnostics(
+                workspace, document.Project.Id, document.Id, id, false, cancellationToken);
+
+            var isLiveUpdate = id is ISupportLiveUpdate;
+
+            var requestedSpan = spanToTag.SnapshotSpan;
+            var requestedSnapshot = requestedSpan.Snapshot;
+
+            foreach (var diagnosticData in diagnostics)
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: Logic copied from:
https://github.com/dotnet/roslyn/pull/23448/files#diff-736f55c2945c85cc9e7af36d167b5145L132

File: src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs [hunk 2]
```diff
@@ -22,47 +31,131 @@ namespace Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics
...
             IAsynchronousOperationListener listener)
+            : base(listener, notificationService)
         {
             _diagnosticService = diagnosticService;
-            _notificationService = notificationService;
-            _listener = listener;
         }
 
-        protected internal abstract IEnumerable<Option<bool>> Options { get; }
+        protected override TaggerDelay AddedTagNotificationDelay => TaggerDelay.OnIdle;
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: From:
https://github.com/dotnet/roslyn/pull/23448/files#diff-736f55c2945c85cc9e7af36d167b5145L60

**Comment by CyrusNajmabadi** [comment]
Tagging @sharwell @heejaechang @dotnet/roslyn-ide  -500 lines in diagnostic tagging FTW.

Note: this should probably be smoke tested and also perf tested.  While is simplifies things greatly, and pushes a lot of work to the BG.  It may end up performing more work and make have unintended consequences.

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by sharwell** [comment]
:memo: I'm planning to look at this for 15.7+ unless we get indications of more substantial problems.

File: src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs [hunk 3]
```diff
@@ -22,47 +31,131 @@ namespace Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics
...
+
+        protected override ITaggerEventSource CreateEventSource(ITextView textViewOpt, ITextBuffer subjectBuffer)
+        {
+            return TaggerEventSources.Compose(
```
Comment (heejaechang) [inline src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: I would add ActiveContextChanged Event source here as well. and remove this (http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Diagnostics/DiagnosticAnalyzerService_IncrementalAnalyzer.cs,58)

looks like we added the code above as a quick way to handle context change when it is first introduced to workspace. but that is not right way to handle it. DiagnosticAnalyzerService shouldn't care about buffer. it should only care about solution.

File: src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs [hunk 4]
```diff
@@ -22,47 +31,131 @@ namespace Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics
...
+
+                var cancellationToken = context.CancellationToken;
+                var workspace = document.Project.Solution.Workspace;
+                
+                // See if we've marked any spans as those we want to suppress diagnostics for.
+                // This can happen for buffers used in the preview workspace where some feature
+                // is generating code that it doesn't want errors shown for.
+                var buffer = spanToTag.SnapshotSpan.Snapshot.TextBuffer;
+                var suppressedDiagnosticsSpans = default(NormalizedSnapshotSpanCollection);
+                buffer?.Properties.TryGetProperty(PredefinedPreviewTaggerKeys.SuppressDiagnosticsSpansKey, out suppressedDiagnosticsSpans);
```
Comment (heejaechang) [inline src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: can buffer ever be null? I don't believe snapshot can have null buffer.

File: src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs [hunk 5]
```diff
@@ -22,47 +31,131 @@ namespace Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics
...
+                    workspace, document.Project.Id, document.Id, context.CancellationToken);
+
+                foreach (var updateArg in eventArgs)
+                {
+                    ProduceTags(
+                        context, spanToTag, workspace, document, sourceText, editorSnapshot,
+                        suppressedDiagnosticsSpans, updateArg, cancellationToken);
+                }
+            }
+            catch (ArgumentOutOfRangeException ex) when (FatalError.ReportWithoutCrash(ex))
```
Comment (heejaechang) [inline src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: can we move this try/catch down to ProduceTags for one specific updateArg so that even if 1 fails, we still can get other analyzers squiggles?

**Comment by heejaechang** [comment]
awesome! things got really simpler! and tests are all passed!

**Comment by heejaechang** [comment]
probably need to do some manual testing before we check this in.

@jasonmalinowski what would be branch we can check this in not affecting ask mode? like post 15.6 branch or something?

File: src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs (hunk 4 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: probably not. though i was just preserving hte code from before.  so i would prefer to not change this.

File: src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs (hunk 5 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: Sure.

Comment (CyrusNajmabadi) [reply src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: Done.

File: src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs (hunk 3 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: hrmm.. can a buffer even cross workspaces though?  i think it can (from Misc Workspace to normal workspace, and vice versa).  So i think we need WorkspaceRegistrationChanged as well.  I will add ActiveContextChanged though.

**Comment by jasonmalinowski** [comment]
@heejaechang We have no such branch -- even if we did nobody would be looking at it. If your desire is for some dogfooding/testing on it, there's a few things we can do.

**Comment by heejaechang** [comment]
if we have a few release left for 15.6 RTM, then I think we should just check this in to 15.6

File: src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs [hunk 6]
```diff
@@ -22,47 +31,132 @@ namespace Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics
...
+                return;
+            }
+
+            var document = spanToTag.Document;
+            if (document == null)
+            {
+                return;
+            }
+
+            if (!document.TryGetText(out var sourceText))
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: Why is this preferred over just GetText()? It should be available either way so be equally fast. But if something goes sideways, this version is broken.

File: src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs [hunk 7]
```diff
@@ -22,47 +31,132 @@ namespace Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics
...
+            {
+                return;
+            }
+
+            var editorSnapshot = sourceText.FindCorrespondingEditorTextSnapshot();
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: How is this ever different than `spanToTag.SnapshotSpan.Snapshot`? This code and then the .TranslateTo in ProduceTags(...) implies with much vigor they can be different, but I don't see how.

File: src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs (hunk 6 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: agreed.  i can change to just using GetText.

File: src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs (hunk 7 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: i think some of this logic dates back like 10ish years.  It's quite possible that it was back at a time where we had less invariants about Documents/SourceTexts/Snapshots.  I'm happy to remove (or assert it must be hte same).

Comment (jasonmalinowski) [reply src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: Well, it can only date 8 years ago... ;-)

Where did this move from originally? Was originally the snapshot you're mapping from related to the snapshot the diagnostics were computed for? It implies I can get stale spans, but since those buffers will be the same we're not correctly mapping things forward.

Comment (CyrusNajmabadi) [reply src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: This moved from: https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.AggregatingTagger.cs#L290

Comment (CyrusNajmabadi) [reply src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: Comment on that says:

```
                // Make sure we can find an editor snapshot for these errors.  Otherwise we won't
                // be able to make ITagSpans for them.  If we can't, just bail out.  This happens
                // when the solution crawler is very far behind.  However, it will have a more
                // up to date document within it that it will eventually process.  Until then
                // we just keep around the stale tags we have.
```

I think a lot of the complexity here was that in the old system you had notifications from the diagnostic engine about a set of data, and we were trying to relate it to the editor-based data.  There were moving at different speeds, with different invariants, and we had code like this to try to be resilient to that sort of thing.

If we're now just querying the diagnostic subsystem with teh correct tagger info we have, i don't think we have any issues adn we can likely clean this up even more.

Comment (CyrusNajmabadi) [reply src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: Yup, looking at this, i don't think we need it anymore.

**Comment by CyrusNajmabadi** [comment]
Ok.  Made the changes @jasonmalinowski

File: src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs [hunk 8]
```diff
@@ -78,30 +78,22 @@ private void ProduceTags(TaggerContext<TTag> context, DocumentSnapshotSpan spanT
...
-            {
-                return;
-            }
-
-            var editorSnapshot = sourceText.FindCorrespondingEditorTextSnapshot();
-            if (editorSnapshot == null)
-            {
-                return;
-            }
+            var editorSnapshot = spanToTag.SnapshotSpan.Snapshot;
```
Comment (heejaechang) [inline src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: @jasonmalinowski @CyrusNajmabadi if spanToTag.SnapshotSpan.Snapshot is same as sourceText.FindCorrespondingEditorTextSnapshot, then how that ever can be failed? either 2 are different if that ever returned (TryGetText or FindCorrespoindingEditorTextSnapshot returned false or null) or there is a bug here.

we should add debug assert or NFW to make sure spanToTag.SnapshotSpan.Snapshot and document.FindCorrespondingEditorTextSnapshot returned same editorSnapshot otherwise, editorSnapshot and document is pointing to different snapshot.

Comment (heejaechang) [reply src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: by the way, I believe existing code does exactly same thing as this? this code is just copied over from the original one.

File: src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs (hunk 7 above)
Comment (heejaechang) [reply src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: old one did translate to since DiagnosticUpdated event is not part of tag event source. due to that it didn't update internal interval tree when diagnostic is updated, rather it just hold onto snapshot at the moment. and later did "translate to" move spans to right one itself.

this new one no longer does that, now DiagnosticUpdated is part of tag event source. when diagnostic changed, it save spans in taggers internal interval tree and let tagger's own mechanism to handle translate to.

Comment (heejaechang) [reply src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: "// Make sure we can find an editor snapshot for these errors.  Otherwise we won't
                // be able to make ITagSpans for them.  If we can't, just bail out.  This happens
                // when the solution crawler is very far behind.  However, it will have a more
                // up to date document within it that it will eventually process.  Until then
                // we just keep around the stale tags we have."

agree this is not needed anymore. since there is no longer 2 documents as we used to.

File: src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs (hunk 8 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: These have to be the same due to: https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/Tagging/AbstractAsynchronousTaggerProvider.TagSource_ProduceTags.cs#L353

i.e. we only ask providers for the ITextSnapshot+TextSpan to produce tags for.  The tagger infrastructure then gets the document by calling GetOpenDocumentInCurrentContextWithChanges on that snapshot.   So the Document is always the proper one for the data we started with (unless something catastrophically bad happened in the workspace).

File: src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs [hunk 9]
```diff
@@ -22,47 +31,124 @@ namespace Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics
...
+
+                var requestedSpan = spanToTag.SnapshotSpan;
+                var requestedSnapshot = requestedSpan.Snapshot;
+
+                foreach (var diagnosticData in diagnostics)
+                {
+                    if (this.IncludeDiagnostic(diagnosticData))
+                    {
+                        var actualSpan = diagnosticData
+                            .GetExistingOrCalculatedTextSpan(sourceText)
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: Chatted with @heejaechang and he confirmed there is still one problem: when we call GetDiagnostics, those spans may be against an older version of the text snapshot than we are querying here. GetExistingOrCalculatedTextSpan may return a span that is past the end of editorSnapshot, which will result in exceptions being thrown. The try/catch surrounding this might catch it...or might not.

The .TranslateTo of course is a no-op which looks like we're trying to deal with this case. We should really just delete that.

Comment (CyrusNajmabadi) [reply src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: Good points!  Let me make sure the code is resilient to all this.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski Made the change.

**Comment by CyrusNajmabadi** [comment]
Note: we could also consider updating this code:

https://github.com/dotnet/roslyn/blob/8f70a5287a5de6b651153424da9f70da07414c0b/src/Workspaces/Core/Portable/Diagnostics/DiagnosticData.cs#L235

We could make it so that the DiagnosticData itself always hands back a span that is within the bounds of the SourceText passed to it.  @heejaechang Thoughts?

**Comment by CyrusNajmabadi** [comment]
> not sure if @heejaechang will take this from here or not.

@jasonmalinowski Unless there is a strong reason for this to be picked up by a team member (for example, needs major rewrite, or fits into something else they're doing), and as long as i can support the PR, i would prefer to keep it on my plate.  :)

**Comment by heejaechang** [comment]
+1 on updating GetExistingOrCalculatedTextSpan to always return valid span against sorucetext

**Comment by CyrusNajmabadi** [comment]
Done.

**Comment by heejaechang** [comment]
thank you!

File: src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs [hunk 10]
```diff
@@ -22,47 +31,132 @@ namespace Microsoft.CodeAnalysis.Editor.Implementation.Diagnostics
...
+            try
+            {
+                var id = updateArgs.Id;
+                var diagnostics = _diagnosticService.GetDiagnostics(
+                    workspace, document.Project.Id, document.Id, id, false, cancellationToken);
+
+                var isLiveUpdate = id is ISupportLiveUpdate;
+
+                var requestedSpan = spanToTag.SnapshotSpan;
+                var requestedSnapshot = requestedSpan.Snapshot;
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: Nit: this is still the same instance as `editorSnapshot`, let's just get rid of this...

Comment (jasonmalinowski) [reply src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: (or it's just unused now?)

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi This will need a rebase to dev15.6.x.

**Comment by CyrusNajmabadi** [comment]
Not a problem (i hope).

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski  Did i do this properly?

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Well done!

**Comment by jinujoseph** [comment]
Thanks @CyrusNajmabadi 
Adding @Pilchie  for ask mode approval

**Comment by jinujoseph** [comment]
just realized this is missing ask mode template

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski Can you help with the template?

**Comment by CyrusNajmabadi** [comment]
Also, i would recommend this be smoke tested.

File: src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs (hunk 10 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/Core/Implementation/Diagnostics/AbstractDiagnosticsTaggerProvider.cs]: yeah, i can remove.

**Comment by heejaechang** [comment]
@jinujoseph added ask mode template.

**Comment by sharwell** [comment]
@heejaechang I updated the ask mode template to link the other bugs

**Comment by CyrusNajmabadi** [comment]
thanks @sharwell !

**Comment by heejaechang** [comment]
@jinujoseph @mattscheffer we probably want to have manual testing as soon as possible.

**Comment by jinujoseph** [comment]
@richaverma1 to help with manual testing

**Comment by Pilchie** [comment]
The scenario meets the bar.  Consider this approved, pending satisfactory results from the manual testing.  @richaverma1 Can you add the "Approved to merge" label when testing is complete and you are happy with the results?

**Comment by heejaechang** [comment]
merged! thank you everyone! thank you @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Any time!

**Comment by yuvalshtemer** [comment]
Pardon me for being a github beginner, but I'm in real pain because of this issue.. would appreciate some assistance on how to pull & install the fix

**Comment by heejaechang** [comment]
@yuvalshtemer latest VS should have this fix, you don't need to pull anything. just move to latest VS.
