### PR TITLE
Ensure analyzer actions are invoked for SimpleProgramNamedTypeSymbol.

### LINKED ISSUE #44663: Symbol start analyzer actions are not invoked for top-level statements
**Version Used**: 4f286be

**Steps to Reproduce**:

1. Register a symbol start action for `SymbolKind.NamedType`
2. Create a simple program with top-level statements

**Expected Behavior**:

The analyzer callback is invoked for the generated `$Program` class.

**Actual Behavior**:

The analyzer callback is not invoked.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #44663.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
CC @sharwell

**Comment by AlekseyTs** [comment]
@cston, @RikkiGibson, @dotnet/roslyn-compiler Please review a fix for a bug that is blocking several IDE features for Top-level statements.

File: src/Compilers/CSharp/Portable/Symbols/Source/SimpleProgramNamedTypeSymbol.cs [hunk 1]
```diff
@@ -224,7 +224,7 @@ protected override MembersAndInitializers BuildMembersAndInitializers(Diagnostic
                                               instanceInitializersSyntaxLength: 0);
         }
 
-        public override bool IsImplicitlyDeclared => true;
+        public override bool IsImplicitlyDeclared => false;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/SimpleProgramNamedTypeSymbol.cs:227]: >false [](start = 53, length = 5)

It seems surprising that this type is not marked implicitly declared. (Note, the comment on the `class` indicates that it is implicitly declared.)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SimpleProgramNamedTypeSymbol.cs:227]: > It seems surprising that this type is not marked implicitly declared. (Note, the comment on the class indicates that it is implicitly declared.)

It seems that IDE features and AnalyzerDriver have strong dependency on the fact that anything containing user-written code returns true from this API. So, yes the type doesn't have explicit TypeDeclarationSyntax, but to follow the established dependencies, we return false because it contains user-written code.

---
In reply to: [433040558](https://github.com/dotnet/roslyn/pull/44716#discussion_r433040558) [](ancestors = 433040558)

**Comment by AlekseyTs** [comment]
@RikkiGibson, @dotnet/roslyn-compiler Please review, need a second sign-off for a fix for a bug that is blocking several IDE features for Top-level statements.

File: src/Compilers/CSharp/Portable/Symbols/Source/SimpleProgramNamedTypeSymbol.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SimpleProgramNamedTypeSymbol.cs:227]: It does feel odd that this is required, considering that for example synthesized constructors are considered to be "implicitly declared" but they contain user-written field initializers.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SimpleProgramNamedTypeSymbol.cs:227]: > It does feel odd that this is required, considering that for example synthesized constructors are considered to be "implicitly declared" but they contain user-written field initializers.

Synthesized constructors do not contain user-written code, field initializers are not "inside" the constructor, they are associated with fields rather that with the constructor

---
In reply to: [433351758](https://github.com/dotnet/roslyn/pull/44716#discussion_r433351758) [](ancestors = 433351758)
