### PR TITLE
Fix extract local function bugs

### LINKED ISSUE #40188: Extract method does not respect .editorconfig settings
**Version Used**: 16.4.0 Preview 6.0

**Steps to Reproduce**:

1. Have .editorconfig containing ```csharp_style_expression_bodied_methods = true:silent```
2. With the following code:
```
class Program
{
    static void Main(string[] args)
    {
        bool b = true;
        System.Console.WriteLine(b != true ? b = true : b = false);
    }
}
```
highlight ```b != true``` and select the extract method code action.

**Expected Behavior**:
```
class Program
{
    static void Main(string[] args)
    {
        bool b = true;
        System.Console.WriteLine({|Rename:NewMethod|}(b) ? b = true : b = false);
    }

    private static bool NewMethod(bool b) => b != true;
}
```

**Actual Behavior**:
```
class Program
{
    static void Main(string[] args)
    {
        bool b = true;
        System.Console.WriteLine(NewMethod(b) ? b = true : b = false);
    }

    private static bool NewMethod(bool b)
    {
        return b != true;
    }
}
```
It seems that the issue involves extract method getting its options from the workspace rather than the document (thanks to @mavasani for helping figure this out).

### LINKED ISSUE #40214: ExtractLocalFunction: code style for naming local functions isn't respected
Currently, if you extract a block of code to a local function, the local function will be named using PascalCase convention, instead of honoring the user's preference.

### PR DESCRIPTION
**Pull request by allisonchou**
Fixes #40188 and fixes #40214

Previously, a fix for #40188 was opened in [this PR](https://github.com/dotnet/roslyn/pull/40265), but while working on the fix for #40214, I realized some of the code overlapped and thus decided to just merge everything into one PR. I have also addressed all the feedback from the initial PR.

### CODE REVIEW

File: src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs [hunk 1]
```diff
@@ -210,6 +217,11 @@ private DeclarationModifiers CreateMethodModifiers()
                 var isStatic = !this.AnalyzerResult.UseInstanceMember;
                 var isReadOnly = this.AnalyzerResult.ShouldBeReadOnly;
 
+                if (LocalFunction && !this.Options.GetOption(CSharpCodeStyleOptions.PreferStaticLocalFunction).Value)
+                {
+                    isStatic = false;
+                }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs]: do you need to check language version as well?

File: src/Features/Core/Portable/ExtractMethod/MethodExtractor.cs [hunk 2]
```diff
@@ -173,11 +176,16 @@ public async Task<ExtractMethodResult> ExtractMethodAsync(CancellationToken canc
             return Tuple.Create(true, status);
         }
 
-        internal static string MakeMethodName(string prefix, string originalName)
+        internal static string MakeMethodName(string prefix, string originalName, bool localFunction = false, bool camelCase = false)
         {
             var startingWithLetter = originalName.ToCharArray().SkipWhile(c => !char.IsLetter(c)).ToArray();
             var name = startingWithLetter.Length == 0 ? originalName : new string(startingWithLetter);
 
+            if (localFunction && camelCase && !prefix.IsEmpty())
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ExtractMethod/MethodExtractor.cs]: why do you need the 'localFunction' boolean?

File: src/Features/Core/Portable/ExtractMethod/MethodExtractor.cs [hunk 3]
```diff
@@ -173,11 +176,16 @@ public async Task<ExtractMethodResult> ExtractMethodAsync(CancellationToken canc
             return Tuple.Create(true, status);
         }
 
-        internal static string MakeMethodName(string prefix, string originalName)
+        internal static string MakeMethodName(string prefix, string originalName, bool localFunction = false, bool camelCase = false)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ExtractMethod/MethodExtractor.cs]: i would not make these optional.  it makes it too easy for existing code to not pass in the right values.

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpCodeGenerationService.cs [hunk 4]
```diff
@@ -113,6 +113,11 @@ protected override TDeclarationNode AddMethod<TDeclarationNode>(TDeclarationNode
         {
             CheckDeclarationNode<TypeDeclarationSyntax, CompilationUnitSyntax, NamespaceDeclarationSyntax>(destination);
 
+            if (options.Options == null)
+            {
+                options = options.With(options: Workspace.Options);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/CodeGeneration/CSharpCodeGenerationService.cs]: `options.Options ??= ...`

File: src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs (hunk 1 above)
Comment (ryzngard) [reply src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs]: LocalFunction should already be false if the language version doesn't support it right?

File: src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.ExpressionCodeGenerator.cs [hunk 5]
```diff
@@ -44,15 +51,17 @@ protected override SyntaxToken CreateMethodName(bool localFunction)
                     return SyntaxFactory.Identifier(nameGenerator.CreateUniqueMethodName(containingScope, methodName));
                 }
 
-                private static string GetMethodNameBasedOnExpression(string methodName, SyntaxNode expression)
+                private string GetMethodNameBasedOnExpression(string methodName, SyntaxNode expression)
                 {
+                    var preferLocalFunctionCamelCaseName = methodName.Equals("newMethod");
```
Comment (ryzngard) [inline src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.ExpressionCodeGenerator.cs]: You should probably make "newMethod" a const value to compare against

File: src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractLocalFunctionTests.cs [hunk 6]
```diff
@@ -3790,6 +3791,581 @@ static int NewMethod()
 }", CodeActionIndex);
         }
 
+        [Fact, WorkItem(40188, "https://github.com/dotnet/roslyn/issues/40188"), Trait(Traits.Feature, Traits.Features.CodeActionsExtractLocalFunction)]
+        public async Task TestEditorconfigSetting_StaticLocalFunction_True()
+        {
+            var input = @"
+<Workspace>
```
Comment (ryzngard) [inline src/EditorFeatures/CSharpTest/CodeActions/ExtractMethod/ExtractLocalFunctionTests.cs]: nit: In the future try to separate out the code and editorconfig files. It's hard to read them bunched together, especially since the editorconfig doesn't change :)

File: src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs [hunk 7]
```diff
@@ -210,6 +217,11 @@ private DeclarationModifiers CreateMethodModifiers()
                 var isStatic = !this.AnalyzerResult.UseInstanceMember;
                 var isReadOnly = this.AnalyzerResult.ShouldBeReadOnly;
 
+                if (LocalFunction && !this.Options.GetOption(CSharpCodeStyleOptions.PreferStaticLocalFunction).Value)
+                {
+                    isStatic = false;
```
Comment (ryzngard) [inline src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs]: 💡 I wonder if PreferStaticLocalFunction should also mean that if instance members or locals are used, we generate a static local but with them passed as a parameter.

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpCodeGenerationService.cs [hunk 8]
```diff
@@ -573,6 +578,11 @@ public override SyntaxNode CreateFieldDeclaration(IFieldSymbol field, CodeGenera
                 }
             }
 
+            if (options.Options == null)
```
Comment (ryzngard) [inline src/Workspaces/CSharp/Portable/CodeGeneration/CSharpCodeGenerationService.cs]: `options.Options ??=`

File: src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs (hunk 1 above)
Comment (ryzngard) [reply src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs]: doi, static local is c# 8 only

Comment (ryzngard) [reply src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs]: although, logistically I'm not opposed to the MethodGenerator caring if the language version supports local static. This is just stating that the user prefers it to be static. Having the check where it's at in `GenerateModifiers` makes sense to me

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpCodeGenerationService.cs (hunk 4 above)
Comment (allisonchou) [reply src/Workspaces/CSharp/Portable/CodeGeneration/CSharpCodeGenerationService.cs]: Thanks so much for the review. If I'm not mistaken, since options.Options doesn't have a set method, I don't think we can assign to it. We could have options.Options support a set method, but I don't know if this is the right move since none of the existing settings in CodeGenerationOptions have set methods.

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpCodeGenerationService.cs (hunk 8 above)
Comment (allisonchou) [reply src/Workspaces/CSharp/Portable/CodeGeneration/CSharpCodeGenerationService.cs]: If I'm not mistaken, since options.Options doesn't have a set method, I don't think we can assign to it. We could have options.Options support a set method, but I don't know if this is the right move since none of the existing settings in CodeGenerationOptions have set methods.

File: src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs (hunk 7 above)
Comment (allisonchou) [reply src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs]: Great idea. 👍  I believe locals are already passed into the method 100% of the time by default, but I think having instance members passed as well would be a good addition. Would this have to go through design review?

File: src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs (hunk 1 above)
Comment (allisonchou) [reply src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs]: I decided to switch the check over to CSharpCodeGenerator since, for example, if the user has a camelCase naming rule that applies exclusively to static local functions but they're in an earlier version of C#, the naming rule shouldn't apply. I think this is an extreme edge case but thought it probably wouldn't hurt to just move the check over.

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpCodeGenerationService.cs (hunk 4 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/CSharp/Portable/CodeGeneration/CSharpCodeGenerationService.cs]: sorry...  sould be:  `options = options.With(options: options.options ?? Workspace.Options)`

Comment (allisonchou) [reply src/Workspaces/CSharp/Portable/CodeGeneration/CSharpCodeGenerationService.cs]: Thanks! Updated.

File: src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs (hunk 7 above)
Comment (ryzngard) [reply src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs]: Not a bad idea to make sure that the behavior of "PreferStaticLocalFunction" makes sense still with that change.

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpCodeGenerationService.cs (hunk 8 above)
Comment (ryzngard) [reply src/Workspaces/CSharp/Portable/CodeGeneration/CSharpCodeGenerationService.cs]: I see
