### PR TITLE
Quote variable/array expansions in shell scripts

### LINKED ISSUE #22259: Path names with spaces fail in build/scripts/obtain_dotnet.sh
**Version Used**: 
```
$ git describe
Visual-Studio-2017-Version-15.3-3100-gf827f7a88c
```

**Steps to Reproduce**:

1. Clone `roslyn` into a directory with spaces in the path (e.g. `/Volumes/G-DRIVE ev RaW SSD/Home/roslyn`)
2. Run `./build/scripts/obtain_dotnet.sh` to obtain dotnet-CLI in order to build roslyn

**Expected Behavior**:

The pathname is handled accordingly.

**Actual Behavior**:

```
$ ./build/scripts/obtain_dotnet.sh
./build/scripts/obtain_dotnet.sh: line 25: /Volumes/G-DRIVE: No such file or directory
```

**Possible Solution**

Line 25 reads:
```bash
    source ${THIS_DIR}/build-utils.sh
```

There are other lines, both in `obtain_dotnet.sh` and other `*.sh` files that contain *unquoted* variables. This is problematic, as the variables undergo word splitting and causes issues like the above. See e.g. [BashPitfalls](http://mywiki.wooledge.org/BashPitfalls#cd_.24.28dirname_.22.24f.22.29) for many discussions on this.

### PR DESCRIPTION
**Pull request by benknoble**
Lack of quoting causes issues when files have spaces or are empty names.
Additionally, some arrays (though single elements) were treated like
simple variables.

The careful reader will note that I have left BUILD_ARGS

`dotnet build "${ROOT_PATH}"/CrossPlatform.sln ${BUILD_ARGS}`

untouched, because it contains spaces meant to separate arguments. Word
expansion is somewhat desired there (I believe) to ensure the arguments
are properly parsed. Unfortunately, BUILD_ARGS may contains paths with
spaces in them, causing this to still fail.

Fix #22259

**Customer scenario**

Try to build roslyn in a path with spaces and fail.

**Bugs this fixes:**

#22259 

**Workarounds, if any**

Don't use a path with spaces.

**Risk**

I'm very wary of this particular change, as it *likely* won't break anything currently (no paths with spaces) but is hard to guarantee for paths with spaces (we don't have test coverage).
As this is my first real contribution, I may have inadvertently quoted something I shouldn't have.

**Performance impact**

Low: these are shell scripts anyways, and the extra quotes should require negligible time compared to the scripts.

**Is this a regression from a previous update?**

I don't think so.

**Root cause analysis:**

We still don't have test coverage (although it appears there has been some discussion on getting some #20929), so I'm not sure we can 100% verify this yet. This is a known issue.

**How was the bug found?**

I tried to build roslyn in a directory whose full name contained spaces.

### CODE REVIEW

File: build/scripts/build-utils.sh [hunk 1]
```diff
@@ -28,16 +28,16 @@ get_version_core()
 #   get_package_version System.Console
 get_package_version() 
 {
-    local repoDir=$(get_repo_dir)
-    local version=$(get_version_core $1 ${repoDir}/build/Targets/Packages.props)
-    echo $version
+    local repoDir="$(get_repo_dir)"
```
Comment (khyperia) [inline build/scripts/build-utils.sh]: I'm not sure if things of the form `var=$(command)` need quoting (quick testing says I don't think so?), but it can't hurt, I guess. (Lots of places in this PR do this, just pointing it out at an example place)

File: build/scripts/obtain_dotnet.sh [hunk 2]
```diff
@@ -36,6 +36,6 @@ install_dotnet () {
         echo "Skipping download of .NET CLI: Already installed at ${DOTNET_PATH}"
     fi
 
-    export PATH=${DOTNET_PATH}:${PATH}
+    export PATH="${DOTNET_PATH}:${PATH}"
```
Comment (khyperia) [inline build/scripts/obtain_dotnet.sh]: Again, not sure if this is strictly necessary, but it can't hurt, I guess.

File: build/scripts/tests.sh [hunk 3]
```diff
@@ -27,29 +27,29 @@ need_publish=(
...
-    deps_json="${file_name%.*}.deps.json"
-    runtimeconfig_json="${file_name%.*}.runtimeconfig.json"
-    echo "Running ${file_name}"
-    dotnet exec --depsfile "${deps_json}" --runtimeconfig "${runtimeconfig_json}" ${xunit_console} "$file_name" -xml "${log_file}"
+    file_name=( "${test_path}"/*.UnitTests.dll )
+    log_file="${log_dir}"/"$(basename "${file_name%.*}.xml")"
+    deps_json="${file_name%.*}".deps.json
+    runtimeconfig_json="${file_name%.*}".runtimeconfig.json
+    echo Running "${file_name[@]}"
+    dotnet exec --depsfile "${deps_json}" --runtimeconfig "${runtimeconfig_json}" "${xunit_console}" "${file_name[@]}" -xml "${log_file}"
```
Comment (khyperia) [inline build/scripts/tests.sh]: This actually might be incorrect... I'm not sure if xunit supports passing multiple dlls in a single run. If there _are_ multiple dlls, though, something is horribly broken, and failing is okay.

File: cibuild.sh [hunk 4]
```diff
@@ -97,34 +97,34 @@ fi
...
 PUBLISH_ARGS="-f ${TARGET_FRAMEWORK} -r ${RUNTIME_ID} ${BUILD_ARGS}"
 
 echo "Building bootstrap csc"
-dotnet publish ${SRC_PATH}/Compilers/CSharp/csc -o ${BOOTSTRAP_PATH}/csc ${PUBLISH_ARGS}
+dotnet publish "${SRC_PATH}"/Compilers/CSharp/csc -o "${BOOTSTRAP_PATH}"/csc ${PUBLISH_ARGS}
 echo "Building bootstrap vbc"
-dotnet publish ${SRC_PATH}/Compilers/VisualBasic/vbc -o ${BOOTSTRAP_PATH}/vbc ${PUBLISH_ARGS}
-rm -rf ${BINARIES_PATH}/${BUILD_CONFIGURATION}
+dotnet publish "${SRC_PATH}"/Compilers/VisualBasic/vbc -o "${BOOTSTRAP_PATH}"/vbc ${PUBLISH_ARGS}
+rm -rf "${BINARIES_PATH:?}"/"${BUILD_CONFIGURATION}"
```
Comment (khyperia) [inline cibuild.sh]: Why was the `:?` added here?

For reference to other reviewers - `${parameter:?err_msg}` "[If parameter set, use it, else print err_msg and abort the script with an exit status of 1.](http://www.tldp.org/LDP/abs/html/parameter-substitution.html)" - we already have `set -u`.

(Perhaps you're just being extra careful and guarding against [nuking a computer](https://www.theregister.co.uk/2015/01/17/scary_code_of_the_week_steam_cleans_linux_pcs/)?)

**Comment by jasonmalinowski** [comment]
@khyperia I think you and @agocke might be the only real experts here, so if you think it's good feel free to merge. :smile:

File: cibuild.sh (hunk 4 above)
Comment (benknoble) [reply cibuild.sh]: Yeah this was a "**don't accidentally** `rm -rf /` **no matter what**" thing.

(I didn't actually notice the `set -u` 😅 )

File: build/scripts/tests.sh (hunk 3 above)
Comment (benknoble) [reply build/scripts/tests.sh]: I wasn't sure about this one, but your reasoning sounds right

File: build/scripts/build-utils.sh (hunk 1 above)
Comment (benknoble) [reply build/scripts/build-utils.sh]: It's a strange case: if we were applying a command (like in `cat $(get some files)`), we would *definitely* want quoting. Here, likely not strictly necessary. But it sets a better code style for the future, I should think.
