### PR TITLE
Consider types having a valid GetEnumerator for pluralization

### LINKED ISSUE #37366: The Suggested Name should recognize [ReadOnly]Span/Memory
**Version Used**: 
16.2.0 Preview 4.0

**Steps to Reproduce**:
Create a function parameter of `Span<Value>`.

**Expected Behavior**:
As with `Value[]`, the suggested name should be `values`.

**Actual Behavior**:
The suggested name ist just `span`

span-suggested-name

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #37366

### CODE REVIEW

File: src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs [hunk 1]
```diff
@@ -178,24 +178,30 @@ private static Glyph GetGlyph(SymbolKind kind, Accessibility? declaredAccessibil
...
 
-                if (ienumerableOfT != null)
+                if (getEnumeratorMethod is not null)
                 {
+                    var members = getEnumeratorMethod.ReturnType.AllInterfaces.Concat(returnType.GetBaseTypesAndThis())
+                        .SelectMany(x => x.GetMembers())
+                        .Where(x => x.DeclaredAccessibility == Accessibility.Public)
+                        .ToList();
+
+                    var currentProperty = members.OfType<IPropertySymbol>().FirstOrDefault(p => p.Name == WellKnownMemberNames.CurrentPropertyName && p.GetMethod != null);
```
Comment (Youssef1313) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs:190]: A copy from:

https://github.com/dotnet/roslyn/blob/0ff47433e7fdb834f76fb711c5cdd78d0b0cb342/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/ISymbolExtensions.cs#L709-L718


Probably figure a better approach to share the code instead of duplicating it?

File: src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs [hunk 2]
```diff
@@ -178,24 +178,30 @@ private static Glyph GetGlyph(SymbolKind kind, Accessibility? declaredAccessibil
...
-                var originalDefinition = namedType.OriginalDefinition;
-
-                var ienumerableOfT = namedType.GetAllInterfacesIncludingThis().FirstOrDefault(
-                    t => t.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T);
+                var getEnumeratorMethod = namedType.GetMembers().OfType<IMethodSymbol>().FirstOrDefault(m => m.IsValidGetEnumerator() || m.IsValidGetAsyncEnumerator());
 
-                if (ienumerableOfT != null)
+                if (getEnumeratorMethod is not null)
                 {
+                    var members = getEnumeratorMethod.ReturnType.AllInterfaces.Concat(returnType.GetBaseTypesAndThis())
```
Comment (Youssef1313) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs:185]:
```suggestion
                    var returnType = getEnumeratorMethod.ReturnType;
                    var members = returnType.AllInterfaces.Concat(returnType.GetBaseTypesAndThis())
```

File: src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs [hunk 3]
```diff
@@ -178,24 +178,31 @@ private static Glyph GetGlyph(SymbolKind kind, Accessibility? declaredAccessibil
...
-                var originalDefinition = namedType.OriginalDefinition;
-
-                var ienumerableOfT = namedType.GetAllInterfacesIncludingThis().FirstOrDefault(
-                    t => t.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T);
+                var getEnumeratorMethod = namedType.GetMembers().OfType<IMethodSymbol>().FirstOrDefault(m => m.IsValidGetEnumerator() || m.IsValidGetAsyncEnumerator());
 
-                if (ienumerableOfT != null)
+                if (getEnumeratorMethod is not null)
                 {
+                    var returnType = getEnumeratorMethod.ReturnType;
```
Comment (Youssef1313) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs:185]:
```suggestion
                    var returnType = getEnumeratorMethod.ReturnType;
                    Debug.Assert(returnType is not null);
```

File: src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs [hunk 4]
```diff
@@ -178,24 +179,30 @@ private static Glyph GetGlyph(SymbolKind kind, Accessibility? declaredAccessibil
 
             if (type is INamedTypeSymbol namedType && namedType.OriginalDefinition != null)
             {
-                var originalDefinition = namedType.OriginalDefinition;
-
-                var ienumerableOfT = namedType.GetAllInterfacesIncludingThis().FirstOrDefault(
-                    t => t.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T);
+                var getEnumeratorMethod = namedType.GetMembers()
```
Comment (Youssef1313) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs:182]: When `namedType` is a `Span<T>`, `GetMembers` returns an empty immutable array. Why it doesn't return the existing GetEnumerator and all other methods?

Could someone assist here?

File: src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs [hunk 5]
```diff
@@ -178,24 +179,30 @@ private static Glyph GetGlyph(SymbolKind kind, Accessibility? declaredAccessibil
...
+                    .OfType<IMethodSymbol>()
+                    .FirstOrDefault(m => m.IsValidGetEnumerator() || m.IsValidGetAsyncEnumerator());
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs:184]: So system.string implements this interface. Can you add a test that shows this won't apply to that type when naming? (And, if it does, blacklist that case).

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs [hunk 6]
```diff
@@ -1181,6 +1181,50 @@ class Test
...
+        [WorkItem(37366, "https://github.com/dotnet/roslyn/issues/37366")]
+        [Fact, Trait(Traits.Feature, Traits.Features.Completion)]
+        public async Task PluralizeSpan()
+        {
+            var markup = @"
+using System;
+
+class Test
+{
+    void M(Span<Test> $$) { }
```
Comment (Youssef1313) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs:1193]: This test doesn't seem to be run against a runtime that have a `Span<T>` definition. What's the correct way to fix that? (besides having to clone part of the implementation from dotnet/runtime repo)

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs [hunk 7]
```diff
@@ -1651,7 +1695,7 @@ public void Method()
   }
 }
 ";
-            await VerifyItemExistsAsync(markup, "vs");
+            await VerifyItemExistsAsync(markup, "immutableArray");
```
Comment (Youssef1313) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs:1698]: Both the old and the new behavior are incorrect here. There is tracked by #36364.

File: src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs (hunk 5 above)
Comment (Youssef1313) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs]: @CyrusNajmabadi This is already tested in `NoSuggestionsForString`:

https://github.com/dotnet/roslyn/blob/3655d5490eef0df4717087caaaeb2ca85fed1eca/src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs#L651-L661

The part that skips it is the last line of the following method:

https://github.com/dotnet/roslyn/blob/9f82a08241f46854e2a1ccb0c3f40195a2c7a70b/src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs#L109-#L127

**Comment by CyrusNajmabadi** [comment]
@Youssef1313 can you fixup the failures here?

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs [hunk 8]
```diff
@@ -25,6 +25,185 @@ namespace Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Completion.CompletionSe
 {
     public class DeclarationNameCompletionProviderTests : AbstractCSharpCompletionProviderTests
     {
+        internal const string Span = @"
```
Comment (Youssef1313) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs:28]: Copy/paste from:

https://github.com/dotnet/roslyn/blob/afd10305a37c0ffb2cfb2c2d8446154c68cfa87a/src/Compilers/Test/Utilities/CSharp/TestSources.cs#L11

File: src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs [hunk 9]
```diff
@@ -178,24 +180,33 @@ private static Glyph GetGlyph(SymbolKind kind, Accessibility? declaredAccessibil
...
+                // if namedType is a Span<Person>, collectionType should be Person.
+                var collectionType = namedType.GetMembers()
+                    .OfType<IMethodSymbol>()
+                    .FirstOrDefault(m => m.IsValidGetEnumerator() || m.IsValidGetAsyncEnumerator())
+                    ?.ReturnType?.GetMembers(WellKnownMemberNames.CurrentPropertyName)
+                    .OfType<IPropertySymbol>().FirstOrDefault(p => p.GetMethod != null)?.Type;
+
+                // This can happen for an un-implemented IEnumerable.
+                collectionType ??= namedType.GetAllInterfacesIncludingThis().FirstOrDefault(
+                        t => t.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T)?.TypeArguments[0];
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs:194]: In the higher up code you look for GEtEnumerator and GetAsyncEnumerator.  But here, you only chec for IEnumerable and not IAsyncEnumerable.  Intentional?

**Review by CyrusNajmabadi — APPROVED** [review]
Ok with going with this.  Or lmk if you want to make changes.

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs [hunk 10]
```diff
@@ -1181,6 +1360,50 @@ class Test
...
+    public class MyEnumerator
+    {
+        public T Current { get; }
+        
+        public bool MoveNext() { return false; }
+    }
+}
+";
+            await VerifyItemExistsAsync(markup, "myClasses");
+        }
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs:1405]: i don't see tests for:

1. valid GetAsyncEnumerator
2. not finding GetEnumerator and looking to see if an interface is implemented.

File: src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs (hunk 9 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs:194]: also, would it not be sufficient to just do this check and skip the higher up check?

Comment (Youssef1313) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs:194]: > In the higher up code you look for GEtEnumerator and GetAsyncEnumerator. But here, you only chec for IEnumerable and not IAsyncEnumerable. Intentional?

Nope, I'd add a check for IAsyncEnumerable too.

Comment (Youssef1313) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs:194]: > also, would it not be sufficient to just do this check and skip the higher up check?

Both handles different cases. The main part of this is the first check, this second one won't be the common scenario.

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs (hunk 10 above)
Comment (Youssef1313) [reply src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs:1405]: Sure, I'll add more tests.

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs (hunk 8 above)
Comment (sharwell) [reply src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs]: `ReferenceAssemblies.Net.Net50` should already be available to tests, but I'm not sure `AbstractCSharpCompletionProviderTests` is set up to use it. Such a change should probably be a separate pull request.

**Comment by CyrusNajmabadi** [comment]
Thanks!
