### PR TITLE
Fix race conditions caused by doing something *after* the corresponding symbol completion bit was set.

### LINKED ISSUE #16706: InvalidOperationException "Cannot enqueue data after PromiseNotToEnqueue." if an analyzer calls GetDiagnostics in the RegisterCompilationAction callback
**Version Used**: 1.3.2 (also repros in 2.0.0-rc2)

**Steps to Reproduce**:
Full repro code available at https://github.com/dpaoliello/PromiseNotToEnqueueRepro

This requires two threads:

Thread 1 (Main C# Compiler thread):
1. Calls `CommonCompiler.RunCore`.
2. Which calls `CSharpCompilation.GetDeclarationDiagnostics`.
3. Which calls `ForceComplete` on symbols recursively.
4. Which calls a method that calls `SymbolCompletionState.NotePartCompleted` *before* calling `CSharpCompilation.SymbolDeclaredEvent` (e.g. `SourceMemberFieldSymbol.FixedSize`).
5. After calling `NotePartCompleted` the thread is suspended (note that `SymbolDeclaredEvent` has not yet been called).

Thread 2 (Thread for analyzer):
1. Calls `CSharpCompilation.GetDiagnostics`.
2. Which calls `ForceComplete` on symbols recursively.
3. Since Thread 1 has marked part of the compilation complete, continues to complete the compilation.
4. `GetDiagnostics` then calls `Compilation.EnsureCompilationEventQueueCompleted` which marks the `EventQueue` as completed and promises not to enqueue any other events.

Thread 1 then continues, and calls `SymbolDeclaredEvent` which attempts to enqueue the event, but finds that the queue has been completed, thus throws the `InvalidOperationException`.

There are two possible ways I can think of to fix this:
1. A careful review of each call to `NotePartCompleted` to ensure that all events are queued *before* completing the part.
2. Ensure that only one thread is walking the `ForceComplete` chain at a time - perhaps the first thread that does this can atomically set a task that other threads can then wait on.

### PR DESCRIPTION
**Pull request by gafter**
**Customer scenario**

Compiler occasionally crashes while using VS normally, causing VS to crash.

**Bugs this fixes:** 

Fixes #16706

**Workarounds, if any**

None known.

**Risk**

Low. The changes slightly reorganize code to eliminate race conditions.

**Performance impact**

Tiny, if any. No new operations added, but rather existing operations are now performed in a different order.

**Is this a regression from a previous update?**

This has been a longstanding bug in the Roslyn C# compiler since the addition of support for analyzers.

**Root cause analysis:**

Race conditions are difficult to detect, diagnose, repair, and test for. The fixes included in this PR resulted from a survey of our use of completion bits throughout the C# compiler and a systematic elimination of race conditions caused by doing something *after* the caller was the unique setter of some bit. A test written to prevent regressions here (see #16753) has exhibited a different race condition previously unknown (i.e. it fails), so it is not included with this PR.

**How was the bug found?**

Customer reported. The customer also provided a very clear explanation of where (one instance of) the race condition can be found in the compiler.

@dotnet/roslyn-compiler May I please have a couple of reviews of this bug fix for 2.1?

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a couple of reviews of this bug fix for RTM?

**Comment by gafter** [comment]
Note that I don't have a regression test for this. I tried writing one - see #16753 - but that test fails due to a different rare race condition.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceEnumConstantSymbol.cs [hunk 1]
```diff
@@ -115,17 +115,13 @@ internal sealed override void ForceComplete(SourceLocation locationOpt, Cancella
...
-                    case CompletionPart.ConstantValue:
-                        GetConstantValue(ConstantFieldsInProgress.Empty, earlyDecodingWellKnownAttributes: false);
-                        break;
-
                     case CompletionPart.FixedSize:
                         Debug.Assert(!this.IsFixed);
-                        if (state.NotePartComplete(CompletionPart.FixedSize)) // Not applicable
-                        {
-                            // FixedSize is the last completion part for fields.
-                            DeclaringCompilation.SymbolDeclaredEvent(this);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceEnumConstantSymbol.cs]: >DeclaringCompilation.SymbolDeclaredEvent(this); [](start = 28, length = 47)

Is this now handled by SourceFieldSymbol?

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceFixedFieldSymbol.cs [hunk 2]
```diff
@@ -122,11 +122,7 @@ public sealed override int FixedSize
                     if (Interlocked.CompareExchange(ref _fixedSize, size, FixedSizeNotInitialized) == FixedSizeNotInitialized)
                     {
                         this.AddDeclarationDiagnostics(diagnostics);
-                        if (state.NotePartComplete(CompletionPart.FixedSize))
-                        {
-                            // FixedSize is the last completion part for fields.
-                            DeclaringCompilation.SymbolDeclaredEvent(this);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceFixedFieldSymbol.cs]: > DeclaringCompilation.SymbolDeclaredEvent(this); [](start = 27, length = 48)

Is this now handled by SourceFieldSymbol?

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberFieldSymbol.cs [hunk 3]
```diff
@@ -120,12 +120,7 @@ public override int FixedSize
             get
             {
                 Debug.Assert(!this.IsFixed, "Subclasses representing fixed fields must override");
-                if (state.NotePartComplete(CompletionPart.FixedSize))
-                {
-                    // FixedSize is the last completion part for fields.
-                    DeclaringCompilation.SymbolDeclaredEvent(this);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberFieldSymbol.cs]: >DeclaringCompilation.SymbolDeclaredEvent(this); [](start = 20, length = 47)

Is this now handled by SourceFieldSymbol?

**Comment by MattGertz** [comment]
Unless we can link this to a high-hit Watson bucket, we can do this in 15.1.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceFixedFieldSymbol.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceFixedFieldSymbol.cs]: Yes, sort of. It is handled where the completion part `ConstantValue` is set in `SourceFieldSymbolWithSyntaxReference` in `SourceFieldSymbol.cs`. `SourceFieldSymbolWithSyntaxReference` is the only direct subclass of the abstract class `SourceFieldSymbol` (perhaps we should consider merging them).

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberFieldSymbol.cs (hunk 3 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberFieldSymbol.cs]: Same answer.

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a second review of this bug fix?

File: src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs [hunk 4]
```diff
@@ -1263,24 +1243,61 @@ internal override void ForceComplete(SourceLocation locationOpt, CancellationTok
                                     parameter.Type.CheckAllConstraints(conversions, parameter.Locations[0], diagnostics);
                                 }
 
-                                if (_state.NotePartComplete(CompletionPart.Parameters))
+                                if (_state.NotePartComplete(CompletionPart.StartPropertyParameters))
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs]: Should `if (_state.NotePartComplete(CompletionPart.StartPropertyParameters)) { ... }` wrap the entire `case`, so that only one thread needs to check parameter constraints?

File: src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs [hunk 5]
```diff
@@ -1263,24 +1243,61 @@ internal override void ForceComplete(SourceLocation locationOpt, CancellationTok
...
                                 }
                             }
                         }
                         break;
 
+                    case CompletionPart.FinishPropertyParameters:
+                        // since StartPropertyParameters was not the next incomplete part, it must have
+                        // been completed by another thread. Wait for it to finish the parameters.
+                        _state.SpinWaitComplete(CompletionPart.FinishPropertyParameters, cancellationToken);
+                        break;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs]: Other cases of `case CompletionPart.Finish...` are bundled with the `case CompletionPart.Start...`. Consider doing that here as well, so we don't need the comment explaining this case and so to avoid having two cases that complete this part.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs [hunk 6]
```diff
@@ -1263,24 +1243,61 @@ internal override void ForceComplete(SourceLocation locationOpt, CancellationTok
...
+
+                            diagnostics.Free();
+                        }
+                        break;
+
+                    case CompletionPart.FinishPropertyType:
+                        // since StartPropertyType was not the next incomplete part, it must have
+                        // been completed by another thread. Wait for it to finish the type.
+                        _state.SpinWaitComplete(CompletionPart.FinishPropertyType, cancellationToken);
+                        break;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs]: Consider merging with `case CompletionPart.StartPropertyType:`.

**Comment by cston** [comment]
Minor comments only. LGTM.

**Comment by gafter** [comment]
@cston Can you please review the last commit, which improves the code as you suggested?

**Comment by cston** [comment]
Last commit LGTM, thanks.
