### PR TITLE
Port changes from #13024 to VB for various tuple fixes

### LINKED ISSUE #14895: Port compiler changes for tuples in #13024 from C# to VB
Port compiler changes for tuples in #13024 from the C# compiler to the VB compiler

### PR DESCRIPTION
**Pull request by gafter**
Fixes #14895 

@dotnet/roslyn-compiler Please review this port of an assortment of C# fixes for tuples.

### CODE REVIEW

**Comment by gafter** [comment]
@CyrusNajmabadi you reviewed the two IDE code changes that are ported here; can you please check them?

**Comment by CyrusNajmabadi** [comment]
IDE side is 👍

File: src/EditorFeatures/VisualBasicTest/ChangeSignature/ReorderParametersTests.Cascading.vb [hunk 1]
```diff
@@ -32,6 +32,34 @@ End Class]]></Text>.NormalizedValue()
 
             Await TestChangeSignatureViaCommandAsync(LanguageNames.VisualBasic, markup, updatedSignature:=permutation, expectedUpdatedInvocationDocumentCode:=updatedCode)
         End Function
+        <WpfFact, Trait(Traits.Feature, Traits.Features.ChangeSignature)>
```
Comment (jcouv) [inline src/EditorFeatures/VisualBasicTest/ChangeSignature/ReorderParametersTests.Cascading.vb]: Empty line above would help readability

File: src/Compilers/VisualBasic/Portable/SymbolDisplay/SymbolDisplayVisitor.Types.vb [hunk 2]
```diff
@@ -210,6 +210,27 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
                 symbol = symbol.TupleUnderlyingType
             End If
 
+            ' It would be nice to handle C# NoPia symbols too, but it's not worth the effort.
+
+            Dim illegalGenericInstantiationSymbol = TryCast(symbol, NoPiaIllegalGenericInstantiationSymbol)
```
Comment (jcouv) [inline src/Compilers/VisualBasic/Portable/SymbolDisplay/SymbolDisplayVisitor.Types.vb]: If you remember, what test was affected by this added block?

Comment (gafter) [inline src/Compilers/VisualBasic/Portable/SymbolDisplay/SymbolDisplayVisitor.Types.vb]: I don't remember exactly which ones. The NoPia tests were printing the error types as "?" in the error messages rather than giving the name of the underlying type. This is code I ported, which was already in the C# code base and simply missing from the VB code base.

**Comment by gafter** [comment]
@AlekseyTs You reviewed the C# changes; could you please check this VB port of them? I still need another code review.

File: src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/VisualBasicSymbolMatcher.vb [hunk 3]
```diff
@@ -396,6 +396,13 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Emit
 
                     Dim typeMap = TypeSubstitution.Create(otherDef, otherTypeParameters, otherTypeArguments, False)
                     Return otherDef.Construct(typeMap)
+                ElseIf type.IsTupleType Then
+                    Dim otherDef = DirectCast(Me.Visit(type.TupleUnderlyingType), NamedTypeSymbol)
+                    If otherDef Is Nothing OrElse Not otherDef.IsTupleOrCompatibleWithTupleOfCardinality(type.TupleElementTypes.Length) Then
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/VisualBasicSymbolMatcher.vb]: >IsTuple [](start = 63, length = 7)

It doesn't look like TupleTypeSymbol.Create can handle a tuple type symbols as the first argument.

File: src/Compilers/VisualBasic/Portable/Emit/NoPia/EmbeddedTypesManager.vb [hunk 4]
```diff
@@ -194,6 +194,10 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Emit.NoPia
                     TypeKind.Enum,
                     TypeKind.Delegate
 
+                    If type.IsTupleType Then
+                        type = type.TupleUnderlyingType
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Emit/NoPia/EmbeddedTypesManager.vb]: >type = type.TupleUnderlyingType [](start = 24, length = 31)

This probably was fine when we were simply propagating TypeKind of underlying type through TupleTypeSymbol. I think we are not doing this any more. Consider moving this substitution out of the Select Case. This also applies to C# code.

File: src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/MetadataDecoder.vb [hunk 5]
```diff
@@ -204,6 +204,10 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols.Metadata.PE
                     End If
 
                     Do
+                        If symbol.IsTupleType Then
+                            Return IsOrClosedOverATypeFromAssemblies(symbol.TupleUnderlyingType, assemblies)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/MetadataDecoder.vb]: >Return IsOrClosedOverATypeFromAssemblies(symbol.TupleUnderlyingType, assemblies) [](start = 28, length = 80)

symbol = symbol.TupleUnderlyingType ?

File: src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTuples.vb [hunk 6]
```diff
@@ -15329,8 +15335,84 @@ additionalRefs:=s_valueTupleRefs)
...
+    Private Class C2
+    End Class
+End Class
+    </file>
+</compilation>,
+additionalRefs:=s_valueTupleRefs)
 
+            comp.AssertTheseDiagnostics(
+<errors>
+BC30508: 'M' cannot expose type 'C.C2' in namespace '&lt;Default&gt;' through class 'C'.
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTuples.vb]: >'&lt;Default&gt;' [](start = 52, length = 17)

Consider using CDATA section instead of using ```&lt```, etc.

**Comment by AlekseyTs** [comment]
Done with review pass.

File: src/Compilers/VisualBasic/Portable/Emit/NoPia/EmbeddedTypesManager.vb (hunk 4 above)
Comment (gafter) [inline src/Compilers/VisualBasic/Portable/Emit/NoPia/EmbeddedTypesManager.vb]: I'd rather not do any refactorings of the changes I'm porting, or write new tests for those changes. Please file an issue if you'd like that done.

File: src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/VisualBasicSymbolMatcher.vb (hunk 3 above)
Comment (gafter) [inline src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/VisualBasicSymbolMatcher.vb]: This code appears to be correct and precisely parallel to the C# implementation, so I'll leave it as it stands.

File: src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/MetadataDecoder.vb (hunk 5 above)
Comment (gafter) [inline src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/MetadataDecoder.vb]: This code appears to be correct and precisely parallel to the C# implementation, so I'll leave it as it stands.

**Comment by gafter** [comment]
@AlekseyTs OK, I used CDATA instead of `&lt;` in the test. Please re-review.

**Comment by gafter** [comment]
@jaredpar @dotnet/roslyn-compiler Need a second review, please.

File: src/Compilers/VisualBasic/Portable/VBResources.Designer.vb [hunk 7]
```diff
@@ -5577,6 +5595,78 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
+        End Property
+        
+        '''<summary>
+        '''  Looks up a localized string similar to Interface &apos;{0}&apos; (via &apos;{1}&apos;) can be inherited only once by this interface, but already appears with different tuple element names, as &apos;{2}&apos;..
+        '''</summary>
+        Friend ReadOnly Property ERR_InterfaceInheritedTwiceWithDifferentTupleNamesReverse3() As String
+            Get
+                Return ResourceManager.GetString("ERR_InterfaceInheritedTwiceWithDifferentTupleNamesReverse3", resourceCulture)
+            End Get
+        End Property
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/VBResources.Designer.vb]: Are these changes expected?

**Comment by cston** [comment]
LGTM

File: src/Compilers/VisualBasic/Portable/VBResources.Designer.vb (hunk 7 above)
Comment (gafter) [inline src/Compilers/VisualBasic/Portable/VBResources.Designer.vb]: I'm guessing changes in this generated file were missed by a previous checkin.

File: src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/VisualBasicSymbolMatcher.vb (hunk 3 above)
Comment (gafter) [inline src/Compilers/VisualBasic/Portable/Emit/EditAndContinue/VisualBasicSymbolMatcher.vb]: I don't know why `Me.Visit(type.TupleUnderlyingType)` would return a tuple type, unless a tuple type's underlying type *could* be a tuple type, which I think you're saying isn't the case. But if it does, I agree an exception could arise.
