### PR TITLE
Adding code fix to unseal a class

### LINKED ISSUE #31832: Code fix for CS0509 to unseal a class
```c#
sealed class C
{
}

class D : C // CS0509: 'D': cannot derive from sealed type 'C'
{
}
```

It would be nice to have a code fix to remove `sealed` from C.

### PR DESCRIPTION
**Pull request by Neme12**
Fixes #31832

### CODE REVIEW

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs [hunk 1]
```diff
@@ -1523,16 +1523,17 @@ public override SyntaxNode WithAccessibility(SyntaxNode declaration, Accessibili
...
+        private static readonly DeclarationModifiers s_indexerModifiers = DeclarationModifiers.Abstract | DeclarationModifiers.New | DeclarationModifiers.Override | DeclarationModifiers.ReadOnly | DeclarationModifiers.Sealed | DeclarationModifiers.Static | DeclarationModifiers.Virtual | DeclarationModifiers.Unsafe;
+        private static readonly DeclarationModifiers s_classModifiers = DeclarationModifiers.Abstract | DeclarationModifiers.New | DeclarationModifiers.Partial | DeclarationModifiers.Sealed | DeclarationModifiers.Static | DeclarationModifiers.Unsafe;
+        private static readonly DeclarationModifiers s_structModifiers = DeclarationModifiers.New | DeclarationModifiers.Partial | DeclarationModifiers.Unsafe;
+        private static readonly DeclarationModifiers s_interfaceModifiers = DeclarationModifiers.New | DeclarationModifiers.Partial | DeclarationModifiers.Unsafe;
         private static readonly DeclarationModifiers s_accessorModifiers = DeclarationModifiers.Abstract | DeclarationModifiers.New | DeclarationModifiers.Override | DeclarationModifiers.Virtual;
```
Comment (Neme12) [inline src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs]: These lists should be reviwed. I can see at least a few bugs right away:
- ref & readonly for structs isn't allowed
- readonly is allowed for properties but shouldn't be
- nothing is allowed for local declarations, but const should be
- nothing is allowed for parameters, but ref, in & out should be

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol_Bases.cs [hunk 2]
```diff
@@ -399,14 +399,14 @@ private static BaseListSyntax GetBaseListOpt(SingleTypeDeclaration decl)
...
-                            diagnostics.Add(ErrorCode.ERR_DeriveFromEnumOrValueType, Locations[0], this, baseType);
+                            diagnostics.Add(ErrorCode.ERR_DeriveFromEnumOrValueType, location, this, baseType);
                             continue;
                         }
                     }
 
                     if (baseType.IsSealed && !this.IsStatic) // Give precedence to ERR_StaticDerivedFromNonObject
                     {
-                        diagnostics.Add(ErrorCode.ERR_CantDeriveFromSealedType, Locations[0], this, baseType);
+                        diagnostics.Add(ErrorCode.ERR_CantDeriveFromSealedType, location, this, baseType);
```
Comment (Neme12) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol_Bases.cs]: I made a compiler change to report the error on the base type instead of the deriving type declaration. I think this is better for a few reasons:
- It just seems better for clarity. If I see a squiggle on the base type, I immediately know where the problem is, but seeing a squiggle on the type declaration doesn't give me much of an idea as to what could be wrong. The problem is really with the base type, so why not make the location more specific to that?
- In case of a partial class, the current location might not even be at the same declaration. I don't think it's a good experience to show a squiggle for a problem that's in a completely different location.
- Other errors that have to do with invalid bases already report a location of the base itself, see below for `ERR_StaticDerivedFromNonObject`, `ERR_DuplicateInterfaceInBaseList` etc.
- This is what VB does as well.

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs (hunk 1 above)
Comment (Neme12) [reply src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs]: ➡️ Filed 32423

**Comment by Neme12** [comment]
@jcouv Could you please take a look at the compiler change? Thanks

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol_Bases.cs (hunk 2 above)
Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol_Bases.cs]: Tagging @jcouv @dotnet/roslyn-compiler

File: src/Features/Core/Portable/UnsealClass/AbstractUnsealClassCodeFixProvider.cs [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+        public override FixAllProvider GetFixAllProvider()
+        {
+            // This code fix addresses a very specific compiler error. It's unlikely there will be more than 1 of them at a time.
+            return null;
+        }
+
+        public override async Task RegisterCodeFixesAsync(CodeFixContext context)
+        {
+            var syntaxRoot = await context.Document.GetSyntaxRootAsync(context.CancellationToken).ConfigureAwait(false);
+            var semanticModel = await context.Document.GetSemanticModelAsync(context.CancellationToken).ConfigureAwait(false);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/UnsealClass/AbstractUnsealClassCodeFixProvider.cs]: can you make locals for the parts of 'contxt' you repeatedly access.  i.e. 'context.Document' and 'context.CancellationToken'.

File: src/Features/Core/Portable/UnsealClass/AbstractUnsealClassCodeFixProvider.cs [hunk 4]
```diff
@@ -0,0 +1,88 @@
...
+
+                solution = solution.WithDocumentSyntaxRoot(documentId, editor.GetChangedRoot());
+            }
+
+            return solution;
+        }
+
+        private sealed class MyCodeAction : CodeAction.SolutionChangeAction
+        {
+            public MyCodeAction(Func<CancellationToken, Task<Solution>> createChangedSolution, string title)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/UnsealClass/AbstractUnsealClassCodeFixProvider.cs]: take title first to match base constructor.

File: src/Features/VisualBasic/Portable/UnsealClass/VisualBasicUnsealClassCodeFixProvider.vb [hunk 5]
```diff
@@ -0,0 +1,21 @@
...
+    Friend NotInheritable Class VisualBasicUnsealClassCodeFixProvider
+        Inherits AbstractUnsealClassCodeFixProvider
+
+        Private Const BC30299 As String = NameOf(BC30299) ' 'D' cannot inherit from class 'C' because 'C' is declared 'NotInheritable'.
+
+        Public Overrides ReadOnly Property FixableDiagnosticIds As ImmutableArray(Of String) =
+            ImmutableArray.Create(BC30299)
+
+        Protected Overrides ReadOnly Property TitleFormat As String = VBFeaturesResources.Make_0_inheritable
+
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/UnsealClass/VisualBasicUnsealClassCodeFixProvider.vb]: unnecessary blank line.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol_Bases.cs (hunk 2 above)
Comment (333fred) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol_Bases.cs]: I disagree with this reasoning, particularly 1. The problem is _not_ that the base class is sealed, the problem is that you cannot derive from a sealed class. This becomes problematic in several aspects:

1. `sealed` is a very intentional modifier. I tend to think of it as one of the most intentional modifiers, along with `private` and `readonly`, and certainly more intentional than deriving.
2. Our behavior for deriving from sealed classes from another compilation or dependency differs from the same compilation scenario.
3. The base class does not actually have a problem here. It is unaffected by someone trying to derive from it.

Comment (333fred) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol_Bases.cs]: I would rather see VB's behavior brought in line with C# tbh, as that feels like a bug to me.

Comment (Neme12) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol_Bases.cs]: I think I worded my reasoning poorly. I agree the problem isn't that the base class is sealed - the problem is that I'm deriving from a sealed class. That's why I think the squiggle should be in the location where I'm specifying the base type - that's where I'm trying to derive from that class and that is the part that needs to be removed to fix the error.

Comment (333fred) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol_Bases.cs]: I misunderstood. For some reason I thought you meant squiggling the base class _definition_. I have no idea why I thought that was what you meant. Disregard my arguments, this sounds like a good change.

Comment (Neme12) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol_Bases.cs]: @333fred Is it possible there was a misunderstanding? I am referring to the base specification, not the declaration of the base class.

Comment (333fred) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol_Bases.cs]: Yeah, this is what I get for looking at code reviews on my phone at midnight.

File: src/Features/VisualBasic/Portable/UnsealClass/VisualBasicUnsealClassCodeFixProvider.vb (hunk 5 above)
Comment (Neme12) [reply src/Features/VisualBasic/Portable/UnsealClass/VisualBasicUnsealClassCodeFixProvider.vb]: ➡️ Fixed in 644aaa3d2ca272f59e78587ada2bde5d281e493b

File: src/Features/Core/Portable/UnsealClass/AbstractUnsealClassCodeFixProvider.cs (hunk 4 above)
Comment (Neme12) [reply src/Features/Core/Portable/UnsealClass/AbstractUnsealClassCodeFixProvider.cs]: ➡️ Fixed in 644aaa3d2ca272f59e78587ada2bde5d281e493b

File: src/Features/Core/Portable/UnsealClass/AbstractUnsealClassCodeFixProvider.cs (hunk 3 above)
Comment (Neme12) [reply src/Features/Core/Portable/UnsealClass/AbstractUnsealClassCodeFixProvider.cs]: ➡️ Fixed in 644aaa3d2ca272f59e78587ada2bde5d281e493b

**Comment by Neme12** [comment]
@sharwell Could you please review this? Thanks.

**Comment by Neme12** [comment]
@CyrusNajmabadi Is there a concern about cluttering up the lightbulb menu and providing too many actions? I'm surprised that's the case because this is a very specific compiler error and doesn't occur very often.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi Is there a concern about cluttering up the lightbulb menu and offering too many actions?

No, that's not the concern.

The concern is primarily one of expectations.  If we start having these trivial fixes which just save the user from editing one token, then we're effectively signing ourselves up to need to supply that for all these sorts of cases.  And that's a lot of code to write/maintain/etc.  Given the small amount of value to the user, it was deemed to be too high a development tax.

Now, as per above, i'm not saying this should not be done.  It's just that i want the team to make a conscientious decision if the attitude around this space has changed.  If so, great.  I have no problems with that.  However, it's def worth the discussion given that it would indicate a shift in the direction specifically taken in the past.

**Comment by YairHalberstadt** [comment]
@CyrusNajmabadi
Is there any reason these analysers have to be in the main repo?
Couldn't they be in a seperate repository? That would make clear that they are a seperate project from the main compiler effort.
It would also help improve the performance of Visual Studio when working on either code base.

**Comment by Neme12** [comment]
@YairHalberstadt That seems like it would only complicate work and refactorings that span across the repos. Often you want to make changes in the workspace layer or even in the compiler at the same time when implementing a feature. (I did both here as you can see)

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi
Is there any reason these analysers have to be in the main repo?
Couldn't they be in a seperate repository? That would make clear that they are a seperate project from the main compiler effort.

This is not the Compiler repo.  This is the Roslyn repo.  And Roslyn is very intentionally a combined/hybrid compiler/IDE platform.  

> It would also help improve the performance of Visual Studio when working on either code base.

I disagree.  Perf would likely get worse because there would be less pressure on this team to get perf acceptable for a huge project like Roslyn.sln.  It's good to have to have hte main teams here having to work on the most extreme cases.  It helps ensure that for the vast majority of users that perf will be good enough since it's much less likely that their own project will dwarf roslyn.

**Comment by YairHalberstadt** [comment]
> I disagree. Perf would likely get worse because there would be less pressure on this team to get perf acceptable for a huge project like Roslyn.sln. It's good to have to have hte main teams here having to work on the most extreme cases. It helps ensure that for the vast majority of users that perf will be good enough since it's much less likely that their own project will dwarf roslyn.

You always tend to have a different way of looking at things. It's great fun 😃

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol_Bases.cs (hunk 2 above)
Comment (jasonmalinowski) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol_Bases.cs]: @333fred I read it the same way at first and was equally confused: this statement:

> I made a compiler change to report the error on the base type instead of the deriving type declaration

It just says "base type". :smile:

Comment (Neme12) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol_Bases.cs]: Sorry. I don't know what it's actually called, I haven't read the spec.

**Comment by CyrusNajmabadi** [comment]
> You always tend to have a different way of looking at things. It's great fun 😃

I'm glad you feel that way :)

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi:

> Note: something that changes the equation here is that we are now open source. So, whereas in the past this would have been something that was potentially a large amount of cost for the team to take on, this could now be considered something that would be much less of an issue thanks to community contributions. These types of fixes would be ideal. They're a great way for people to dip their toes into roslyn, and it can allow many to 'scratch an itch' that wasn't available to them before.

To me this is entirely the game changer. If this code fix had some notable maintenance burden to it, maybe I'd be a bit concerned. But I'm not worried n this case.

**Comment by CyrusNajmabadi** [comment]
> To me this is entirely the game changer. If this code fix had some notable maintenance burden to it, maybe I'd be a bit concerned. But I'm not worried n this case.

Yaay!  Do you think it's ok to just make a call in the PR?  Or do you think it would be valuable to just get agreement in a design meeting?  If the latter, can you drive in the next meeting?  Thanks!

File: src/EditorFeatures/VisualBasicTest/CodeActions/MoveType/MoveTypeTests.MoveToNewFile.vb [hunk 6]
```diff
@@ -63,14 +63,14 @@ End Class
 "
             Dim codeAfterMove =
 "
-Public Partial Class Class1
+Partial Public Class Class1
```
[the remark this answers is not in the document]
Comment (Neme12) [reply src/EditorFeatures/VisualBasicTest/CodeActions/MoveType/MoveTypeTests.MoveToNewFile.vb]: It was surprising to me too that partial is preferred to be first, but I'm not a VB dev. I wonder though if it would be possible to change at this point given that the IDE has literally rewritten the code if you used the opposite order until now, and now it started doing the opposite. I'm guessing that 99% current VB code uses what the IDE enforced and now they would open a file, navigate to a location and have it all messed up.

**Comment by Neme12** [comment]
@jasonmalinowski What's the status of this PR? Is this waiting for a design review or not? Thanks

**Comment by jasonmalinowski** [comment]
@Neme12 Ah, this just never got a buddy assigned to it.

**Comment by Neme12** [comment]
I thought you were the buddy since you were the first to review :smile:

**Comment by jasonmalinowski** [comment]
Nah, that's just because hell froze over and I actually reviewed something promptly for once. :trollface: 

The buddy in our case is whoever the PR is "assigned" to. In any case, this is ready to go in but we'll have to switch the branch first.

**Comment by Neme12** [comment]
@jasonmalinowski good to merge?

**Comment by jasonmalinowski** [comment]
@Neme12: I forgot there's still the VB modifier ordering question here. Changing the ordering to match line commit isn't wrong _per se_ but juts grepping through the Roslyn source I see a bunch of places where we do "Partial" second. I'm wondering if some work is done there.

I'll chat with our VB people internally and get back on this bit.

**Comment by Neme12** [comment]
@jasonmalinowski any updates?

**Comment by jasonmalinowski** [comment]
@Neme12: some internal conversation concluded that yeah, let's keep "Partial" first so it's in sync with the formatter. At this point this is good for me.

We'll need to resolve those merge conflicts. I'm happy to do it as long as you're OK for me to push to your branch. Permissions-wise it should be granted; as a courtesy I don't like pushing to people's branches unless they have the heads up, in case you're trying to do rebase/rewriting of history.

**Comment by jcouv** [comment]
Since the change got the required sign-offs from the compiler team, I'm removing the compiler label so the PR doesn't show up in our "to review" list. In case any compiler changes are added (after iteration 5), please ping us.

**Comment by jasonmalinowski** [comment]
Thanks @Neme12 (once again!) for the awesome work.
