### PR TITLE
Localization test failures VB Fix creation of diagnostic in VisualBasicParseOptions.ValidateOptions

### LINKED ISSUE #24604: Test localization failures on non english machines: VisualBasicParseOptions.ValidateOptions localizes error argument eager.
Extracted from the closed PR #24539 

**Steps to Reproduce**:

Run `Microsoft.CodeAnalysis.VisualBasic.UnitTests.GetDiagnosticsTests.CompilingCodeWithInvalidPreProcessorSymbolsShouldProvideDiagnostics` on a non-english machine. (There are more tests affected by this bug. See the original PR for details).

**Expected Behavior**:

Test passes.

**Actual Behavior**:

Test fails because [VisualBasicParseOptions.ValidateOptions](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/VisualBasicParseOptions.vb#L255) localizes the error argument eager.

**History**

The issue was discussed but not resolved in #24539. The relevant sections are:

@Mastr11
The diagnostic under test is created here like so:
`builder.Add(Diagnostic.Create(MessageProvider.Instance, ERRID.ERR_ConditionalCompilationConstantNotValid, VBResources.ERR_ExpectedIdentifier, symbol.Key))`
If I got you you right it should be created like this one:
```CS
diagnostics.Add(
    messageProvider.CreateDiagnostic(code, Location.None, 
        new CodeAnalysisResourcesLocalizableErrorArgument(errorArgumentResourceId)));
```
It seems there isn't a VBResourcesLocalizableErrorArgument class (at least I couldn't find anything suitable).

@AlekseyTs
There is Microsoft.CodeAnalysis.VisualBasic.LocalizableErrorArgument type.
Alternatively, for consistency with other places where the same diagnostics is created (that is the approach I would prefer), we should be able to call Diagnostic.Create overload that takes DiagnosticInfo. Like this:
```CS
Diagnostic.Create(ErrorFactory.ErrorInfo(ERRID.ERR_ConditionalCompilationConstantNotValid,
                                            ErrorFactory.ErrorInfo(ERRID.ERR_ExpectedIdentifier),
                                            symbol.Key))
```

### PR DESCRIPTION
**Pull request by MaStr11**
### Customer scenario

Running unit test `Microsoft.CodeAnalysis.VisualBasic.UnitTests.GetDiagnosticsTests.CompilingCodeWithInvalidPreProcessorSymbolsShouldProvideDiagnostics` and about 6 others on non English machines failed due to localization issues. The root cause was that the diagnostic for error `ERR_ConditionalCompilationConstantNotValid` wasn't created properly.

The solution was proposed by @AlekseyTs in #24604 
> Alternatively, for consistency with other places where the same diagnostics is created (that is the approach I would prefer), we should be able to call Diagnostic.Create overload that takes DiagnosticInfo. Like this:

```CS
Diagnostic.Create(ErrorFactory.ErrorInfo(ERRID.ERR_ConditionalCompilationConstantNotValid,
                                            ErrorFactory.ErrorInfo(ERRID.ERR_ExpectedIdentifier),
                                            symbol.Key))
```

With this change in place the unit tests do not fail on a German machine.

### Bugs this fixes

Fixes #24604 

### Workarounds, if any

Ignore test failures.

### Risk

Low. 

### Performance impact

Low.

### Is this a regression from a previous update?

No.

### Root cause analysis

Diagnostics are meant to be localization neutral. This diagnostic was created with eager localized arguments.

### How was the bug found?

Contributor reported.

### Test documentation updated?

No.

### CODE REVIEW

File: src/Compilers/VisualBasic/Test/Semantic/Diagnostics/GetDiagnosticsTests.vb [hunk 1]
```diff
@@ -363,10 +363,10 @@ BC31030: Conditional compilation constant '2' is not valid: Identifier expected.
 ~
 </errors>)
 
-            Assert.Equal(diagnostics(0).Arguments, {"Identifier expected.", "2"})
+            Assert.Equal({ErrorFactory.ErrorInfo(ERRID.ERR_ExpectedIdentifier), "2"}, diagnostics(0).Arguments)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/Diagnostics/GetDiagnosticsTests.vb]: >{ErrorFactory.ErrorInfo(ERRID.ERR_ExpectedIdentifier), "2"} [](start = 25, length = 59)

This doesn't look right, we should be comparing against base-line in English, otherwise this assert doesn't verify that premature localization doesn't happen. In fact, this Assert is useless, we already used CompilationUtils.AssertTheseDiagnostics to verify the message. Just remove this and other similar asserts

Comment (AlekseyTs) [reply src/Compilers/VisualBasic/Test/Semantic/Diagnostics/GetDiagnosticsTests.vb]: On the other hand, it is possible that this assert is used to support the next one in a sense that it ensures we look at the diagnostics object that we want (among the two we have). Given that, it is better to keep the assert, but change it to check only the second argument, that should be enough to identify the object.

---
In reply to: [171931674](https://github.com/dotnet/roslyn/pull/25194#discussion_r171931674) [](ancestors = 171931674)

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 3)

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off.

**Comment by AlekseyTs** [comment]
@MaStr11 Could you please re-target this PR to dev15.7.x branch?

**Comment by MaStr11** [comment]
Oh. This looks bad. @AlekseyTs can you help me fixing this mess?

**Comment by jcouv** [comment]
@MaStr11 I'm taking a look. Hold on.

**Comment by AlekseyTs** [comment]
> Oh. This looks bad.

- Create a back-up branch from what you have locally, just in case.  
- **git fetch** the current state of dev15.7.x
- **git rebase -i dotnet/dev15.7.x** 
- In the editor that will be opened your commits should be at the end of the list of commits, remove all the other commits, save and close the editor. The rebase command should succeed.
- **git push -f**

That should do the trick.

**Comment by jcouv** [comment]
Should be good now.
Please verify the PR is still what you intend.

**Comment by MaStr11** [comment]
Looks good. Thank you @jcouv (and @AlekseyTs for the instructions. I will follows these next time). Sorry for the inconvenience.

**Comment by jcouv** [comment]
@jaredpar for ask-mode approval for 15.7. Thanks

**Comment by jaredpar** [comment]
approved

**Comment by AlekseyTs** [comment]
@MaStr11 Thanks for the contribution!
