### PR TITLE
Handle extension `ref this` usage via collection initializer

### LINKED ISSUE #25862: Collection initialiser of struct via extension method should compile when using ref this
**Version Used**:

VS 15.6.4, LangVersion 7.2

**Steps to Reproduce**:

Given:

```c#
public struct MyStruct : IEnumerable
{
    public int Sum { get; set; }

    IEnumerator IEnumerable.GetEnumerator() => throw new NotImplementedException();
}

public static class MyStructExtensions
{
    public static void Add(this MyStruct s, int i) => s.Sum += i;
}
```

The following code compiles and prints zero twice, as a copy is modified:

```c#
var s1 = new MyStruct();
s1.Add(1);

var s2 = new MyStruct { 1 };

Console.WriteLine(s1.Sum);
Console.WriteLine(s2.Sum);
```

7.2 introduces `ref this`. However if you add a `ref` modifier to the `this` parameter, the `s2` construction no longer compiles:

> CS1510: A ref or out value must be an assignable variable

The first form compiles and prints one.

**Expected Behavior**:

Should be able to compile second form.

**Actual Behavior**:

The second form won't compile.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Resolves #25862 

Questions:
- How should it be decided in `Binder.ValueChecks.CheckValueKind()` if the ImplicitReceiver is compatible with a given BindValueKind? Can't think of an example where CheckValueKind returns false, but I might not know about all the places where an ImplicitReceiver comes about.
- What other test coverage is needed?

### CODE REVIEW

**Comment by jcouv** [comment]
Since you mentioned those other scenarios that involve implicit receivers, it would be good to add tests for them.
I suspect there is also an implicit receiver in anonymous object creation, but I'm not sure if that's already covered by `ObjectInitializerExpression` or if it is a dedicated bound node.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs [hunk 1]
```diff
@@ -654,7 +654,18 @@ private static ImmutableArray<RefKind> GetEffectiveArgumentRefKinds(ImmutableArr
...
                                         methodOrIndexer.ContainingType;
-            isComReceiver = (object)receiverNamedType != null && receiverNamedType.IsComImport;
+                isComReceiver = (object)receiverNamedType != null && receiverNamedType.IsComImport;
+            }
+
+            var @params = methodOrIndexer.GetParameters();
+            if (!@params.IsDefaultOrEmpty)
+            {
+                var thisParam = @params[0];
+                var isRefParam = (thisParam.RefKind & RefKind.Ref) != RefKind.None;
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: Here you are using a bitwise check but in the other file a simple `==` is being done. Why the difference?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs [hunk 2]
```diff
@@ -654,7 +654,18 @@ private static ImmutableArray<RefKind> GetEffectiveArgumentRefKinds(ImmutableArr
...
                                         ((MethodSymbol)methodOrIndexer).Parameters[0].Type.TypeSymbol as NamedTypeSymbol :
                                         methodOrIndexer.ContainingType;
-            isComReceiver = (object)receiverNamedType != null && receiverNamedType.IsComImport;
+                isComReceiver = (object)receiverNamedType != null && receiverNamedType.IsComImport;
+            }
+
+            var @params = methodOrIndexer.GetParameters();
+            if (!@params.IsDefaultOrEmpty)
+            {
+                var thisParam = @params[0];
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: Can elements of this array be `null`?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectOrCollectionInitializerExpression.cs [hunk 3]
```diff
@@ -156,6 +156,14 @@ private BoundExpression MakeCollectionInitializer(BoundExpression rewrittenRecei
             // such as generating a params array, re-ordering arguments based on argsToParamsOpt map, inserting arguments for optional parameters, etc.
             ImmutableArray<LocalSymbol> temps;
             var argumentRefKindsOpt = default(ImmutableArray<RefKind>);
+            if (addMethod.Parameters[0].RefKind == RefKind.Ref)
+            {
+                // If the Add method is an extension which takes a `ref this` as the first parameter, implicitly add a `ref` to the argument
+                var builder = ArrayBuilder<RefKind>.GetInstance(addMethod.Parameters.Length, RefKind.None);
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectOrCollectionInitializerExpression.cs]: What happens when one of the other parameters is being passed by `ref`, `in`, etc ... Will this array eventually get rewritten to have the proper values? Or will the use of `RefKind.None` override the user code?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: There's no real reason for this to not just be `==` as-is, but I am wondering if other RefKinds need to be accounted for when rewriting.

Will try adding a test case for an `in this` extension method.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefExtensionMethodsTests.cs [hunk 4]
```diff
@@ -38,6 +38,35 @@ public static void Main()
                 Diagnostic(ErrorCode.ERR_RefLvalueExpected, "5").WithLocation(13, 9));
         }
 
+        [Fact]
+        public void ExtensionMethods_StructCollectionInitializer()
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefExtensionMethodsTests.cs]: Should add a test where `this` is passed by `ref` and one of the arguments is passed by `in`. Use a custom struct for the latter parameter. Want to make sure the implicit `in` is handled correctly in that case.

**Comment by jaredpar** [comment]
Done with review pass (iteration 2)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: Hard to say for sure, but it seems like the symbol would have to be malformed for that to happen.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectOrCollectionInitializerExpression.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectOrCollectionInitializerExpression.cs]: `ref`, `in`, and `out` keywords are not allowed in collection initializer element syntax. Therefore the only RefKinds we'll find for the subsequent arguments are `RefKind.None`.

If the Add method's subsequent parameters use `in`, the generated Add call's argument's RefKind will be updated to `RefKind.In` in `LocalRewriter.BuildStoresToTemps`.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs (hunk 2 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: I would look at other uses of this method and see if those pieces of code consider `null` a valid value.

---
In reply to: [224925020](https://github.com/dotnet/roslyn/pull/30481#discussion_r224925020) [](ancestors = 224925020)

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefExtensionMethodsTests.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefExtensionMethodsTests.cs]: How should I verify the correct usage of implicit `in`? Is it necessary to verify IL?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: All usages of `GetParameters()` that I see so far assume the returned array will not contain null elements.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefExtensionMethodsTests.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefExtensionMethodsTests.cs]: Added a test which passes `in MyStruct` as the "element" parameter of `Add`.
- One with an explicit temp
- One where the compiler creates a temp
Verified that the struct is passed by ref in both cases.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefExtensionMethodsTests.cs [hunk 5]
```diff
@@ -38,6 +38,136 @@ public static void Main()
...
+        var s = new MyStruct { other };
+        System.Console.Write(s.i);
+    }
+}";
+            var verifier = CompileAndVerify(code, expectedOutput: "2");
+            verifier.VerifyIL("Program.Main", @"{
+  // Code size       47 (0x2f)
+  .maxstack  2
+  .locals init (MyStruct V_0, //other
+                MyStruct V_1)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefExtensionMethodsTests.cs]: In the future consider using different types here. It makes reading the IL a bit easier. Change is fine though as is.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs [hunk 6]
```diff
@@ -654,7 +654,17 @@ private static ImmutableArray<RefKind> GetEffectiveArgumentRefKinds(ImmutableArr
...
+                if (thisParam.RefKind == RefKind.Ref)
+                {
+                    return false;
+                }
             }
 
             return rewrittenArguments.Length == methodOrIndexer.GetParameterCount() &&
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: >methodOrIndexer.GetParameterCount() [](start = 48, length = 35)

`@params.Length`

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs [hunk 7]
```diff
@@ -654,7 +654,17 @@ private static ImmutableArray<RefKind> GetEffectiveArgumentRefKinds(ImmutableArr
                 var receiverNamedType = invokedAsExtensionMethod ?
                                         ((MethodSymbol)methodOrIndexer).Parameters[0].Type.TypeSymbol as NamedTypeSymbol :
                                         methodOrIndexer.ContainingType;
-            isComReceiver = (object)receiverNamedType != null && receiverNamedType.IsComImport;
+                isComReceiver = (object)receiverNamedType != null && receiverNamedType.IsComImport;
+            }
+
+            var @params = methodOrIndexer.GetParameters();
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: >var @params = methodOrIndexer.GetParameters(); [](start = 12, length = 46)

Consider moving this above `if (!ignoreComReceiver)` so `@params` can be used in that `if` block.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: Changed the method to make more use of `@params`. Thanks!

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: Actually doesn't seem quite right, I'm gonna move the declaration up but the IsDefaultOrEmpty check back to where it originally was after ignoreComReceiver

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectOrCollectionInitializerExpression.cs (hunk 3 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectOrCollectionInitializerExpression.cs]: Consider adding an assert that the remaining parameters are either `None` or `In`, and a comment that `In` will be updated as you mentioned.

---
In reply to: [224926176](https://github.com/dotnet/roslyn/pull/30481#discussion_r224926176) [](ancestors = 224926176)

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectOrCollectionInitializerExpression.cs]: Added in 23085c7

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 8]
```diff
@@ -460,6 +460,9 @@ internal bool CheckValueKind(SyntaxNode node, BoundExpression expr, BindValueKin
 
                     return true;
 
+                case BoundKind.ImplicitReceiver:
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: >case BoundKind.ImplicitReceiver: [](start = 16, length = 32)

It would be good to review the different `BindValueKind`s and only return `true` for those that make sense and that you can reach with test.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs [hunk 9]
```diff
@@ -652,12 +654,21 @@ private static ImmutableArray<RefKind> GetEffectiveArgumentRefKinds(ImmutableArr
...
             {
                 var receiverNamedType = invokedAsExtensionMethod ?
-                                        ((MethodSymbol)methodOrIndexer).Parameters[0].Type.TypeSymbol as NamedTypeSymbol :
+                                        @params[0].Type.TypeSymbol as NamedTypeSymbol :
                                         methodOrIndexer.ContainingType;
-            isComReceiver = (object)receiverNamedType != null && receiverNamedType.IsComImport;
+                isComReceiver = (object)receiverNamedType != null && receiverNamedType.IsComImport;
+            }
+
+            if (!@params.IsDefaultOrEmpty)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: >IsDefaultOrEmpty [](start = 25, length = 16)

nit: Technically this could just be `IsEmpty` as the doc for `MethodSymbol.Parameters` says it returns empty array when no parameters, so the same applies to `GetParameters()` on a method symbol.

nit: consider adding a comment on the `return false;`

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefExtensionMethodsTests.cs [hunk 10]
```diff
@@ -38,6 +38,136 @@ public static void Main()
...
+            var code = @"
+public struct MyStruct : System.Collections.IEnumerable
+{
+    public int i;
+    public System.Collections.IEnumerator GetEnumerator() => throw new System.NotImplementedException();
+}
+
+public static class MyStructExtension
+{
+    public static void Add(ref this MyStruct s, in MyStruct other)
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefExtensionMethodsTests.cs]: >Add(ref this MyStruct s, in MyStruct other) [](start = 23, length = 43)

Could you also add tests for the `Add(ref, ref)` and `Add(in, ref)` combinations if we don't have them already?

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 8 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: It seems like the ImplicitReceiver is compatible with `RValue`, `Assignable`, and `RefersToLocation`.

I don't think it is compatible with `RefAssignable` because the temp local we create will not be a `ref`. It doesn't seem possible to construct a program which attempts to ref assign to an implicit receiver.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefExtensionMethodsTests.cs [hunk 11]
```diff
@@ -38,6 +38,136 @@ public static void Main()
                 Diagnostic(ErrorCode.ERR_RefLvalueExpected, "5").WithLocation(13, 9));
         }
 
+        [Fact]
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefExtensionMethodsTests.cs]: >Fact [](start = 9, length = 4)

nit: consider adding `WorkItem(25862, "[https://github.com/dotnet/roslyn/issues/25862](https://github.com/dotnet/roslyn/issues/25862)")` on the added tests

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs (hunk 9 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: Dug back into this and am thinking this doesn't actually make sense. This method is used in more contexts than just lowering of collection initializers and wasn't actually preventing the lowering of the BoundCollectionElementInitializer as I thought it was earlier. I've reverted back to the master version of this file and all the tests are continuing to pass.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 8 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: Fixed in 70377c6

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: Thinking on it a bit, I'd assume that:
- an extension method taking `ref this` must be `RefersToLocation` and `Assignable`
- an extension method taking `in this` must be `RefersToLocation`, Assignable doesn't matter
- an extension method or instance method taking `this` must be `RValue`, other BindValueKind bits don't matter
Perhaps the check should be modified to check each of these cases?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: Digging in one more time to make sure I understand this precisely.

BoundImplicitReceiver represents:
- the "this" parameter in an object initializer expression
- the "this" parameter in a collection initializer expression
- the collection being enumerated in a `foreach` statement

It seems like in the context of the `case BoundKind.ImplicitReceiver` we don't have the MethodSymbol for the Add method. So it's hard to do anything more specific down there than say: "we're going to create a temporary before calling .Add() if needed, and the temporary isn't going to be a ref to another variable".

I think there's not much else I could do in here besides change it to something like
```cs
case BoundKind.ImplicitReceiver:
    Debug.Assert(!RequiresRefAssignableVariable(valueKind));
    return true;
```
to convey that it should be impossible to use a BoundImplicitReceiver expression in a context that requires a ref assignable variable.

**Comment by RikkiGibson** [comment]
linux mono tests are busted :/

**Comment by RikkiGibson** [comment]
```sh
Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.DestructorTests.GenericBaseTypeHasNonVirtualFinalize [FAIL]
  Roslyn.Test.Utilities.ExecutionException : 
  Execution failed for assembly ''.
  Expected: ~Derived
  ~Base
  Actual:   
  
  Stack Trace:
      at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
      at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0003b] in <5a872f306a874e34bfe4796f739b7324>:0 
```
I think it would be illuminative to debug this test. May wind up needing to go back to the b925bcd version of the check.

**Comment by RikkiGibson** [comment]
We're green now that GenericBaseTypeHasNonVirtualFinalize is disabled so will :shipit:
