### PR TITLE
Reparse type after async

### LINKED ISSUE #11959: Cannot rename or get completion for using alias
**Version Used**: VS2015.2

**Steps to Reproduce**:
**File1**

``` csharp
namespace AliasRepro.Ns.Test
{
    class TestClass
    {
    }
}
```

**File2**

``` csharp
using System.Threading.Tasks;
using NsTest = AliasRepro.Ns.Test;

namespace AliasRepro
{
    class Program
    {
        static void Main(string[] args)
        {
        }

        static async Task Method()
        {

        }
    }
}
```
# Cannot Rename
1. Select `NsTest` in the second line of the second file and press F2 to rename it
2. NsTest will be selected and rename dialog appears but text isn't green
3. Typing any character will abort inline rename session

**Expected Behavior**:
I can rename the using alias `NsTest`

**Actual Behavior**:
devenv_2016-06-13_11-19-58
# Cannot get completion
1. Go to `static async Task Method()`
2. Change `Task` to `Task<NsTest.`

**Expected Behavior**:
I get IntelliSense for `TestClass`

**Actual Behavior**:
No IntelliSense shows up

### PR DESCRIPTION
**Pull request by ivanbasov**
Fixes #11959

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 1]
```diff
@@ -2371,8 +2374,14 @@ private MemberDeclarationSyntax ParseMemberDeclarationOrStatementCore(SyntaxKind
                     identifierOrThisOpt != null &&
                     (typeParameterListOpt != null && typeParameterListOpt.ContainsDiagnostics
                       || this.CurrentToken.Kind != SyntaxKind.OpenParenToken && this.CurrentToken.Kind != SyntaxKind.OpenBraceToken && this.CurrentToken.Kind != SyntaxKind.EqualsGreaterThanToken) &&
-                    ReconsiderTypeAsAsyncModifier(ref modifiers, ref type, ref explicitInterfaceOpt, identifierOrThisOpt, typeParameterListOpt))
-                {
+                    ReconsiderTypeAsAsyncModifier(ref modifiers, type, identifierOrThisOpt))
+                {
+                    this.Reset(ref afterTypeResetPoint);
+                    this.Release(ref afterTypeResetPoint);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: >this.Release(ref afterTypeResetPoint); [](start = 20, length = 38)

This doesn't look right. This means that we will release the reset point conditionally. See how reset point is released in  ```EatNullableQualifierIfApplicable```, for example.

**Comment by AlekseyTs** [comment]
>         private TypeArgumentListSyntax TypeArgumentFromTypeParameters(TypeParameterListSyntax typeParameterList)

Can we remove this method now?

---
Refers to: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:2439 in 5a219c9. [](commit_id = 5a219c9b5d5a94e36e6f35d307d73c8bd645bd14, deletion_comment = False)

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1)

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 2]
```diff
@@ -2276,124 +2276,139 @@ private MemberDeclarationSyntax ParseMemberDeclarationOrStatementCore(SyntaxKind
...
+                    // (with the type parameters) as the type (with type arguments).  Then we go back to looking for
+                    // the member name again.
+                    // For example, if we get
+                    //     async Task<
+                    // then we want async to be a modifier and Task<MISSING> to be a type.
+                    if (!sawRef &&
+                        identifierOrThisOpt != null &&
+                        (typeParameterListOpt != null && typeParameterListOpt.ContainsDiagnostics
+                          || this.CurrentToken.Kind != SyntaxKind.OpenParenToken && this.CurrentToken.Kind != SyntaxKind.OpenBraceToken && this.CurrentToken.Kind != SyntaxKind.EqualsGreaterThanToken) &&
+                        ReconsiderTypeAsAsyncModifier(ref modifiers, type, identifierOrThisOpt))
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: this if-statement is hte poster child for something that breaks my brain.  i literally can't understand it.

File: src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs [hunk 3]
```diff
@@ -458,5 +458,287 @@ public void TrashAfterDeclaration()
...
+                UsingDeclaration("async Task<SomeNamespace.SomeType Method();", options: options,
+                    // (1,1): error CS1073: Unexpected token '('
+                    // async Task<SomeNamespace.SomeType Method();
+                    Diagnostic(ErrorCode.ERR_UnexpectedToken, "async Task<SomeNamespace.SomeType Method").WithArguments("(").WithLocation(1, 1),
+                    // (1,35): error CS1003: Syntax error, ',' expected
+                    // async Task<SomeNamespace.SomeType Method();
+                    Diagnostic(ErrorCode.ERR_SyntaxError, "Method").WithArguments(",", "").WithLocation(1, 35),
+                    // (1,41): error CS1003: Syntax error, '>' expected
+                    // async Task<SomeNamespace.SomeType Method();
+                    Diagnostic(ErrorCode.ERR_SyntaxError, "(").WithArguments(">", "(").WithLocation(1, 41)
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs]: why are there so many diagnostics?  shouldn't we just want a diagnostic for a single missing `>`?

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 4]
```diff
@@ -2276,124 +2276,139 @@ private MemberDeclarationSyntax ParseMemberDeclarationOrStatementCore(SyntaxKind
...
-
-                    return _syntaxFactory.IncompleteMember(attributes, modifiers.ToList(), type);
-                }
+                var afterTypeResetPoint = this.GetResetPoint();
 
-parse_member_name:;
-                // If we've seen the ref keyword, we know we must have an indexer, method, or property.
-                if (!sawRef)
+                try
                 {
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: i dislike this entire method.  the complexity level is so high.  i would love if we could extract out someone useful here instead of just making this even harder to understand than it already is.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs (hunk 2 above)
Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: this also seems strange in that i would have expected ParseModifiers to have this logic.  When we see 'async' i would think we could make the decision there (using whatever lookahead is necessary) to think it's a mod or not.  instead of needing to undo our original decision back there.

**Comment by AlekseyTs** [comment]
CC @dotnet/roslyn-compiler  for the second review.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs (hunk 4 above)
Comment (alrz) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: I have removed this part in https://github.com/alrz/roslyn/commit/6a4d586859559d7a949aef8b64b518f4593f4e0b on top of https://github.com/dotnet/roslyn/pull/23533 long ago (probably needs update now)

File: src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs (hunk 3 above)
Comment (ivanbasov) [reply src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs]: Because it considers "async Task<SomeNamespace.SomeType Method();"
as 
"async Task<SomeNamespace.SomeType,Method>();"

So, Method goes as the second type argument and it could not find the member identified after that. Then, it could not understand why '()' are provided.

We discussed this with @AlekseyTs. It seems there it would be useful to have re-considering this parsing but not for now.

---
In reply to: [252524863](https://github.com/dotnet/roslyn/pull/32983#discussion_r252524863) [](ancestors = 252524863)

Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs]: > We discussed this with @AlekseyTs. It seems there it would be useful to have re-considering this parsing but not for now.

Pity.  That parsing is truly terrible :)   I'll put it on my backburner to see if there's a way to improve things.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs (hunk 4 above)
Comment (ivanbasov) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: Agree :-) The method is very complex. A refactoring is desired.

---
In reply to: [252525562](https://github.com/dotnet/roslyn/pull/32983#discussion_r252525562) [](ancestors = 252525562)

Comment (ivanbasov) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: Thank you!

---
In reply to: [252779167](https://github.com/dotnet/roslyn/pull/32983#discussion_r252779167) [](ancestors = 252779167)

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs (hunk 2 above)
Comment (ivanbasov) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: @AlekseyTs, do you have any thoughts on this?

---
In reply to: [252526047](https://github.com/dotnet/roslyn/pull/32983#discussion_r252526047) [](ancestors = 252526047)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: I prefer us to not do any refactoring under umbrella of this fix. It will make reviewing and proving correctness of the fix much harder rather than easier. The goal of the fix is to adjust the way we reinterpret the sequence of tokens, we are not changing the conditions under which the sequence is reinterpreted.

**Comment by ivanbasov** [comment]
@dotnet/roslyn-compiler , could you please make a second review? 
@jaredpar , do we need an M2 approval for merge into master?

**Comment by ivanbasov** [comment]
@dotnet/roslyn-compiler , could you please make a second review?
