### PR TITLE
Fixed #20437

### LINKED ISSUE #20437: out var ignores explicit type preference
**Version Used**: 2.3.0.61814

**Steps to Reproduce**:
```C#
int.TryParse("0", out var i);
```

untitled

**Expected Behavior**: IDE0008: Use explicit type instead of 'var'

**Actual Behavior**: Nothing.

### PR DESCRIPTION
**Pull request by zaytsev-victor**
**Customer scenario**
out var ignores explicit type preference
**Note:** Also fixed ignoring implicit type preference

**Bugs this fixes:**
[#20437](https://github.com/dotnet/roslyn/issues/20437)

**Workarounds, if any**
None

**Risk**
Low

**Performance impact**

**Is this a regression from a previous update?**

**Root cause analysis:**
Analizers don't support new DeclarationExpressionSyntax

**How was the bug found?**
customer reported

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/Diagnostics/UseImplicitOrExplicitType/UseExplicitTypeTests.cs [hunk 1]
```diff
@@ -1186,5 +1186,31 @@ static void M()
 }",
 options: ExplicitTypeEverywhere());
         }
+
+        [WpfFact, Trait(Traits.Feature, Traits.Features.CodeActionsUseExplicitType)]
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Diagnostics/UseImplicitOrExplicitType/UseExplicitTypeTests.cs]: These tests likely shouldn't be WpfFacts. @dpoeschl @jasonmalinowski do you know why these would need that.  

@zaytsev-victor (you don't need to change this).

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs [hunk 2]
```diff
@@ -91,6 +92,24 @@ private void HandleVariableDeclaration(SyntaxNodeAnalysisContext context)
                     shouldAnalyze = IsStylePreferred(semanticModel, optionSet, state, cancellationToken);
                 }
             }
+            else if (declarationStatement.IsKind(SyntaxKind.Argument))
+            {
+                shouldAnalyze = false;
+                declaredType = null;
+
+                if ((declarationStatement as ArgumentSyntax)?.Expression is DeclarationExpressionSyntax declaration)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: doesn't need 'as', and doesn't need '?'.  This should be a straight case.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs [hunk 3]
```diff
@@ -37,7 +38,7 @@ public override bool OpenFileOnly(Workspace workspace)
 
         protected override void InitializeWorker(AnalysisContext context)
             => context.RegisterSyntaxNodeAction(
-                HandleVariableDeclaration, SyntaxKind.VariableDeclaration, SyntaxKind.ForEachStatement);
+                HandleVariableDeclaration, SyntaxKind.VariableDeclaration, SyntaxKind.ForEachStatement, SyntaxKind.Argument);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: This seems odd.  We should just register on SyntaxKind.DeclarationExpression

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs (hunk 2 above)
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: Instead of registering on Argument and then checking if the Argument.Expression is a DeclarationExpression, we should just registered to be called back on DeclarationExpressions.  Bonus is that we'll get far less callbacks if we do that.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs [hunk 4]
```diff
@@ -91,6 +92,24 @@ private void HandleVariableDeclaration(SyntaxNodeAnalysisContext context)
...
+
+                if ((declarationStatement as ArgumentSyntax)?.Expression is DeclarationExpressionSyntax declaration)
+                {
+                    declaredType = declaration.Type;
+
+                    shouldAnalyze = ShouldAnalyzeDeclarationExpression(declaration, semanticModel, cancellationToken);
+
+                    if (shouldAnalyze)
+                    {
+                        state = State.Generate(declarationStatement, semanticModel, optionSet, isVariableDeclarationContext: false, cancellationToken: cancellationToken);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: is 'isVariableDeclarationContext: false' correct?

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseExplicitTypeDiagnosticAnalyzer.cs [hunk 5]
```diff
@@ -144,5 +144,18 @@ protected override bool TryAnalyzeVariableDeclaration(TypeSyntax typeName, Seman
...
+        protected override bool ShouldAnalyzeDeclarationExpression(DeclarationExpressionSyntax declaration, SemanticModel semanticModel, CancellationToken cancellationToken)
+        {
+            if (!declaration.Type.IsVar)
+            {
+                // If the type is not 'var', this analyze has no work to do
+                return false;
+            }
+
+            // The base analyzer may impose further limitations
+
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseExplicitTypeDiagnosticAnalyzer.cs]: nit: no blank line.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs [hunk 6]
```diff
@@ -182,5 +187,18 @@ protected override bool TryAnalyzeVariableDeclaration(TypeSyntax typeName, Seman
...
+        protected override bool ShouldAnalyzeDeclarationExpression(DeclarationExpressionSyntax declaration, SemanticModel semanticModel, CancellationToken cancellationToken)
+        {
+            if (declaration.Type.IsVar)
+            {
+                // If the type is already 'var', this analyze has no work to do
+                return false;
+            }
+
+            // The base analyzer may impose further limitations
+
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpUseImplicitTypeDiagnosticAnalyzer.cs]: nit: no blank line.

File: src/EditorFeatures/CSharpTest/Diagnostics/UseImplicitOrExplicitType/UseExplicitTypeTests.cs (hunk 1 above)
Comment (jasonmalinowski) [inline src/EditorFeatures/CSharpTest/Diagnostics/UseImplicitOrExplicitType/UseExplicitTypeTests.cs]: Off the top of my head, no idea. Switch it to Fact locally and see what happens!

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs (hunk 4 above)
Comment (zaytsev-victor) [inline src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: Yeah, it should be false as for ```ForEachStatement```. I forgot to change it back to false after testing. :)

**Comment by dpoeschl** [comment]
retest windows_release_vs-integration_prtest please

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs [hunk 7]
```diff
@@ -91,6 +92,19 @@ private void HandleVariableDeclaration(SyntaxNodeAnalysisContext context)
...
+            else if (declarationStatement.IsKind(SyntaxKind.DeclarationExpression))
+            {
+                var declaration = (DeclarationExpressionSyntax) declarationStatement;
+                declaredType = declaration.Type;
+
+                shouldAnalyze = ShouldAnalyzeDeclarationExpression(declaration, semanticModel, cancellationToken);
+
+                if (shouldAnalyze)
+                {
+                    state = State.Generate(declarationStatement, semanticModel, optionSet, isVariableDeclarationContext: false, cancellationToken: cancellationToken);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: Dumb question, is "isVariableDeclarationContext" necessary given that State.Generate can infer it from the first parameter passed in?

**Comment by CyrusNajmabadi** [comment]
Still LGTM.   Needs another IDE review.

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-ide can we get another set of eyes?

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs [hunk 8]
```diff
@@ -91,6 +92,19 @@ private void HandleVariableDeclaration(SyntaxNodeAnalysisContext context)
                     shouldAnalyze = IsStylePreferred(semanticModel, optionSet, state, cancellationToken);
                 }
             }
+            else if (declarationStatement.IsKind(SyntaxKind.DeclarationExpression))
+            {
+                var declaration = (DeclarationExpressionSyntax) declarationStatement;
```
Comment (Pilchie) [inline src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.cs]: Nit: No space after cast.

**Comment by Pilchie** [comment]
Sorry for the delay in merging, and thanks for the contribution!
