### PR TITLE
Load codepages earlier

### LINKED ISSUE #10785: .NET Core csc output non-ASCII characters correctly in the Console output
This issue is spawned from: https://github.com/dotnet/cli/issues/2486, which is an RC2 partner blocking bug (VS Code).

**Version Used**: 1.3.0.60410

**Steps to Reproduce**:
1. I have an .rsp file with the following input file:

```
"C:\Users\eerhardt\Tést\Program.cs"
```

And that Program.cs file contains a build error.
1. Compile it using the .NET Core csc
   - C:\cli\artifacts\win10-x64\stage1\dotnet.exe C:\cli\artifacts\win10-x64\stage1\sdk\1.0.0-rc2-002476\csc.dll @C:\Temp\dotnet-compile-csc.rsp

**OLD REPRO:**
    cd /d %USERPROFILE%
    mkdir Tést
    cd Tést
    dotnet new
    dotnet restore
    dotnet build

**Expected Behavior**:

The strings written to the console should contain the correct path:

```
C:\Users\eerhardt\Tést\Program.cs(9,17): error CS1001: Identifier expected
C:\Users\eerhardt\Tést\Program.cs(9,17): error CS1002: ; expected
```

**Actual Behavior**:

Incorrect strings are written to the console:

```
C:\Users\eerhardt\T├⌐st\Program.cs(9,17): error CS1001: Identifier expected
C:\Users\eerhardt\T├⌐st\Program.cs(9,17): error CS1002: ; expected
```

**OLD behavior:**
On my machine I'm seeing a crash in the csc process:

```
Unhandled Exception: System.IO.FileNotFoundException: C:\cli\artifacts\win10-x64\stage1\sdk\1.0.0-rc2-002476\Microsoft.CodeAnalysis.dll
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at Roslyn.Utilities.PortableShim.Misc.GetFileVersion(String path)
   at Microsoft.CodeAnalysis.CommonCompiler.GetAssemblyFileVersion()
   at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.PrintLogo(TextWriter consoleOutput)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.CoreClrBuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
```

I can pare the "dotnet build" call down to starting the following process:

```
C:\Users\eerhardt\Tést>C:\cli\artifacts\win10-x64\stage1\dotnet.exe C:\cli\artifacts\win10-x64\stage1\sdk\1.0.0-rc2-002476\csc.dll -noconfig @C:\Users\eerhardt\Tést\obj\Debug\netcoreapp1.0\dotnet-compile-csc.rsp
```

Looking through the callstack, it is trying to write the logo, so I shut that off:

```
C:\Users\eerhardt\Tést>C:\cli\artifacts\win10-x64\stage1\dotnet.exe C:\cli\artifacts\win10-x64\stage1\sdk\1.0.0-rc2-002476\csc.dll -nologo -noconfig @C:\Users\eerhardt\Tést\obj\Debug\netcoreapp1.0\dotnet-compile-csc.rsp
```

and now I get:

```
error CS2011: Error opening response file 'C:\Users\eerhardt\T├â┬⌐st\obj\Debug\netcoreapp1.0\dotnet-compile-csc.rsp'
warning CS2008: No source files specified.
error CS1562: Outputs without source must have the /out option specified
```
# Solution

The underlying problem is a difference in encoding handling in .NET Core vs. .NET Framework. (See the ".NET Core Notes" section in https://msdn.microsoft.com/en-us/library/system.diagnostics.process(v=vs.110).aspx) .NET Core uses a minimal set of code pages, and falls back to Utf8 when it can't find the right code page. In order to get the same behavior as the .NET Framework, console apps have to add the correct code pages into their process.

One possible way of doing this is:

``` C#
using System.Text;
...
    Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
```

~~In order to fix https://github.com/dotnet/cli/issues/2486, we need to make that same call in the CLI's Main method.  But to fully fix the scenario, we need Roslyn to also add this call in the .NET Core version of csc.exe's Main method.~~

/cc @Petermarcu @jaredpar 
/bcc @tarekgh - who provided me guidance on the .NET Core behavior difference

### PR DESCRIPTION
**Pull request by agocke**
**Customer scenario**

.NET CLI and other hosts of the CoreCLR version of csc cannot currently use encodings
not available on CoreCLR by default to print to the console. This change allows standard
encodings to be used as long as they're installed on the machine.

**Bugs this fixes:** 

Fixes #10785

**Workarounds, if any**

None.

**Risk**

Very small, well understood change to load encodings earlier (we are in fact
already loading these encodings, just too late to be used by the Console).

**Performance impact**

None -- we already run this code later.

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

We run a very limited set of tests on CoreCLR at the moment.

**How was the bug found?**

Customer reported.

### CODE REVIEW

**Comment by agocke** [comment]
test this please

File: src/Compilers/Shared/CoreClrBuildClient.cs [hunk 1]
```diff
@@ -6,6 +6,7 @@
 using System.Net.Sockets;
 using System.Threading;
 using System.Threading.Tasks;
+using System.Text;
```
Comment (jaredpar) [inline src/Compilers/Shared/CoreClrBuildClient.cs]: Sort usings.

File: src/Compilers/Shared/CoreClrBuildClient.cs [hunk 2]
```diff
@@ -25,6 +26,9 @@ private CoreClrBuildClient(RequestLanguage language, CompileFunc compileFunc)
 
         internal static int Run(IEnumerable<string> arguments, RequestLanguage language, CompileFunc compileFunc)
         {
+            // Register encodings for console
+            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
```
Comment (jaredpar) [inline src/Compilers/Shared/CoreClrBuildClient.cs]: Do we still need this code then?  

https://github.com/dotnet/roslyn/blob/acc053dbd9d3cb25f086f86f36f80896c8379466/src/Compilers/Core/Portable/EncodedStringText.cs#L29

Comment (agocke) [inline src/Compilers/Shared/CoreClrBuildClient.cs]: I'm not sure. I don't think so, but I also would rather not take that risk in ask mode.

Comment (jaredpar) [inline src/Compilers/Shared/CoreClrBuildClient.cs]: That's reasonable.  Please file a bug though to kill this in the next release.

File: src/Compilers/Shared/CoreClrBuildClient.cs [hunk 3]
```diff
@@ -25,6 +26,9 @@ private CoreClrBuildClient(RequestLanguage language, CompileFunc compileFunc)
 
         internal static int Run(IEnumerable<string> arguments, RequestLanguage language, CompileFunc compileFunc)
         {
+            // Register encodings for console
```
Comment (AlekseyTs) [inline src/Compilers/Shared/CoreClrBuildClient.cs]: >// Register encodings for console [](start = 12, length = 33)

Consider adding a link to the issue.

**Comment by AlekseyTs** [comment]
LGTM

**Comment by agocke** [comment]
@srivatsn For ask mode approval

**Comment by agocke** [comment]
@MattGertz For ask mode approval

**Comment by MattGertz** [comment]
We are in Escrow even for RTW now, so pending Shiproom approval.

**Comment by natidea** [comment]
@agocke I'm bringing this to shiproom in RC3. Please review "Ask Mode" tab in [366261](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/366261)

**Comment by natidea** [comment]
Approved to merge
