### PR TITLE
Bind operator statements when requesting optional parameter values

### LINKED ISSUE #14688: Optional value in VB operator causes crash
Consider the following code:

``` vb
    Public Class Foo
        Public Shared Operator Not(Optional x As Foo) As Foo
        End Operator
    End Class
```

This will cause an exception and VS crash.  I believe it's illegal for optional to be in operators.  Either way though this should not crash VS.

### PR DESCRIPTION
**Pull request by OmarTawfik**
Fixes #14688

Having optional parameters in operator statements is illegal in VB, so `BinderFactory` ignored creating binders for `SyntaxKind.OperatorStatement`. This PR changes that, and adds tests to make sure we generate the correct semantic information and error messages.

### CODE REVIEW

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-compiler this is ready for review.
Tagging @jaredpar and @AlekseyTs as they previously reviewed #14784 (this PR proposes a better way of handling the issue).

File: src/Compilers/VisualBasic/Portable/Binding/BinderFactory.vb [hunk 1]
```diff
@@ -342,6 +342,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
                         Select Case methodSyntax.Kind
                             Case SyntaxKind.SubNewStatement,
                                 SyntaxKind.FunctionStatement,
+                                SyntaxKind.OperatorStatement,
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Binding/BinderFactory.vb]: >SyntaxKind.OperatorStatement [](start = 32, length = 28)

I think VisitParameter should still be adjusted to not call this method with NodeUsage.ParameterDefaultValue unless position is actually within the default value.

File: src/Compilers/VisualBasic/Test/Semantic/Semantics/UserDefinedBinaryOperators.vb [hunk 2]
```diff
@@ -2546,6 +2546,88 @@ End Module
...
+            Assert.Equal("x", identifierSyntax.Identifier.Value)
+
+            Dim typeSyntax = CompilationUtils.FindBindingText(Of IdentifierNameSyntax)(compilation, "a.vb", 2)
+            Dim symbolInfo = model.GetSymbolInfo(typeSyntax)
+            Assert.NotNull(symbolInfo.Symbol)
+            Dim symbol = TryCast(symbolInfo.Symbol, NamedTypeSymbol)
+            Assert.NotNull(symbol)
+            Assert.Equal("Foo", symbol.Name)
+
+            Dim literalSyntax = CompilationUtils.FindBindingText(Of LiteralExpressionSyntax)(compilation, "a.vb", 3)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/Semantics/UserDefinedBinaryOperators.vb]: >literalSyntax [](start = 16, length = 13)

It doesn't look like we are actually testing SementicModel for this syntax. Also, consider using more complex expression (non-Nothing).

File: src/Compilers/VisualBasic/Test/Semantic/Semantics/UserDefinedBinaryOperators.vb [hunk 3]
```diff
@@ -2546,6 +2546,88 @@ End Module
...
+        Return False
+    End Operator
+End Class
+    ]]></file>
+</compilation>
+
+            Dim compilation = CreateCompilationWithMscorlibAndVBRuntime(compilationDef)
+            Dim model = GetSemanticModel(compilation, "a.vb")
+
+            Dim identifierSyntax = CompilationUtils.FindBindingText(Of ModifiedIdentifierSyntax)(compilation, "a.vb", 1)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/Semantics/UserDefinedBinaryOperators.vb]: >identifierSyntax [](start = 16, length = 16)

It doesn't look like we are actually testing SementicModel for this syntax.

File: src/Compilers/VisualBasic/Test/Semantic/Semantics/UserDefinedBinaryOperators.vb [hunk 4]
```diff
@@ -2546,6 +2546,88 @@ End Module
...
+        Return True
+    End Operator
+End Class
+    ]]></file>
+</compilation>
+
+            Dim compilation = CreateCompilationWithMscorlibAndVBRuntime(compilationDef)
+            Dim model = GetSemanticModel(compilation, "a.vb")
+
+            Dim identifierSyntax = CompilationUtils.FindBindingText(Of ModifiedIdentifierSyntax)(compilation, "a.vb", 1)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/Semantics/UserDefinedBinaryOperators.vb]: >identifierSyntax [](start = 16, length = 16)

It doesn't look like we are actually testing SementicModel for this syntax.

**Comment by AlekseyTs** [comment]
Done with review pass.

**Comment by OmarTawfik** [comment]
@AlekseyTs can you please clarify on not using the semantic model? it is used to verify the type of the parameter `Foo` in both tests.

**Comment by OmarTawfik** [comment]
@AlekseyTs comments addressed.
@dotnet/roslyn-compiler can I get a second review?

File: src/Compilers/VisualBasic/Test/Semantic/Semantics/UserDefinedBinaryOperators.vb [hunk 5]
```diff
@@ -2546,6 +2546,93 @@ End Module
...
         End Sub
 
+        <WorkItem(14688, "https://github.com/dotnet/roslyn/issues/14688")>
+        <Fact>
+        Public Sub OperatorsWithDefaultParameters_WithoutValue()
+            Dim compilationDef =
+<compilation name="OperatorsWithDefaultValuesAreNotBound">
+    <file name="a.vb"><![CDATA[
+Public Class Foo
+    Public Shared Operator Not(Optional x As Foo) As Boolean 'BIND1:"Foo"
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/Semantics/UserDefinedBinaryOperators.vb]: >Foo [](start = 45, length = 3)

Let's avoid using words "foo" and "bar", they are flagged by policheck.

File: src/Compilers/VisualBasic/Test/Semantic/Semantics/UserDefinedBinaryOperators.vb [hunk 6]
```diff
@@ -2546,6 +2546,93 @@ End Module
...
+        End Sub
+
+        <WorkItem(14688, "https://github.com/dotnet/roslyn/issues/14688")>
+        <Fact>
+        Public Sub OperatorsWithDefaultParameters_WithValue()
+            Dim compilationDef =
+<compilation name="OperatorsWithDefaultValuesAreNotBound">
+    <file name="a.vb"><![CDATA[
+Public Class Foo
+    Dim Property1 As Foo
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/Semantics/UserDefinedBinaryOperators.vb]: >Dim Property1 As Foo [](start = 4, length = 20)

In VB this is a field declaration. This is just an FYI.

File: src/Compilers/VisualBasic/Test/Semantic/Semantics/UserDefinedBinaryOperators.vb [hunk 7]
```diff
@@ -2546,6 +2546,93 @@ End Module
...
+
+            Dim equalsSyntax = CompilationUtils.FindBindingText(Of EqualsValueSyntax)(compilation, "a.vb", 2)
+            Assert.NotNull(equalsSyntax.EqualsToken)
+            Assert.Equal("=", equalsSyntax.EqualsToken.Value)
+
+            Assert.NotNull(equalsSyntax.Value)
+            Dim valueSyntax = TryCast(equalsSyntax.Value, IdentifierNameSyntax)
+            Assert.NotNull(valueSyntax)
+            Dim valueSymbolInfo = model.GetSymbolInfo(valueSyntax)
+            Assert.NotNull(valueSymbolInfo.Symbol)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/Semantics/UserDefinedBinaryOperators.vb]: >Assert.NotNull(valueSymbolInfo.Symbol) [](start = 12, length = 38)

It would be sufficient to test ```Assert.Equal("...", valueSymbolInfo.Symbol.ToTestDisplayString())```, it would cover this and all asserts below. This is just an FYI.

**Comment by AlekseyTs** [comment]
LGTM, modulo usage of "foo" in the tests.

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-compiler  can I get a second sign off?

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-compiler ping
