### PR TITLE
Extended partial methods

### LINKED ISSUE #43883: Partial methods should not be overloadable on parameter ref kind
**Version Used**: 441c154 (3.6.x compiler)

**Steps to Reproduce**:
```cs
partial class C {
    partial void M1(ref int i);
    partial void M1(ref int i) { }
    partial void M1(in int i);
    partial void M1(in int i) { }
}
```

**Expected Behavior**:
`error CS0663: 'C' cannot define an overloaded method that differs only on parameter modifiers 'ref' and 'in'`, as is produced for the following program:

```cs
class C {
    void M1(in int i) { }
    void M1(ref int i) { }
}
```

**Actual Behavior**:
No diagnostics. Both methods are emitted, and both methods are actually callable.

/cc @cston whose test idea ended up uncovering this bug.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Test plan: #43795
Fixes #43883 (see test `ConflictingOverloads_RefOut_02`)

This PR enables 'out' parameters, non-'void' returns, accessibility modifiers, and several other modifiers to be used with 'partial' methods.

Draft spec: dotnet/csharplang#3417

### CODE REVIEW

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs [hunk 1]
```diff
@@ -0,0 +1,558 @@
...
+        {
+            const string text1 = @"
+class C
+{
+    internal void M1() { }
+}
+
+partial class D : C
+{
+    new partial void M1();
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:506]: I've been contemplating the behavior and precedent around 'new' and have been thinking that maybe we should just generally relax the requirements around 'new': adding 'new' doesn't require providing an implementation part, and both parts will behave as if 'new' was specified if either part has a 'new' keyword. Since the purpose of 'new' is just to conspicuously call out that we are not overriding something.

Just for context, in the shipped language there is no recourse if you want to declare a partial method with the same name as an accessible base member.

```cs
class C
{
    internal void M1() { }
}
partial class D : C
{
    // warning CS0108: 'D.M1()' hides inherited member 'C.M1()'. Use the new keyword if hiding was intended.
    partial void M1();
}
```

**Comment by RikkiGibson** [comment]
At this point I believe that 'new' should not be allowed when there is no implementation part. It just seems so confusing to shadow a method with a partial that has no implementation, and then erase the call sites.

**Comment by jaredpar** [comment]
> At this point I believe that 'new' should not be allowed when there is no implementation part. It just seems so confusing to shadow a method with a partial that has no implementation, and then erase the call site

Please add a PROTOTYPE to note this, or an issue in the running spec and we can follow up with LDM later.

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs [hunk 2]
```diff
@@ -0,0 +1,552 @@
...
+    {
+        new C().M1(out var value);
+        System.Console.WriteLine(value);
+    }
+}";
+
+            const string text2 = @"
+partial class C
+{
+    partial void M1(out int value) { value = 42; }
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:133]: Indeed this is the correct answer.

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs [hunk 3]
```diff
@@ -0,0 +1,552 @@
...
+    static extern partial void M1();
+}";
+            var comp = CreateCompilation(text1);
+            comp.VerifyDiagnostics(
+                // (9,32): error CS8652: The feature 'extended partial methods' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
+                //     static extern partial void M1();
+                Diagnostic(ErrorCode.ERR_FeatureInPreview, "M1").WithArguments("extended partial methods").WithLocation(9, 32));
+
+            comp = CreateCompilation(text1, parseOptions: TestOptions.RegularWithExtendedPartialMethods);
+            comp.VerifyDiagnostics();
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:465]: Do we have a test that verifies the `DllImportAttribute` is emitted correctly in this scenario?

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs [hunk 4]
```diff
@@ -0,0 +1,552 @@
...
+partial class D : C
+{
+    partial void M1();
+    new partial void M1() { }
+}";
+            var comp = CreateCompilation(text1, parseOptions: TestOptions.RegularWithExtendedPartialMethods);
+            comp.VerifyDiagnostics();
+        }
+    }
+}
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:552]: Feel like there are several categories of tests missing here. Apologies if I read past them:

- `partial` methods implementing `interface` members
- `partial` methods which `override` members
- `partial` methods which are both `override` and have nullability attributes like `[MaybeNull]` which impact our OHI checks.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs [hunk 5]
```diff
@@ -905,23 +932,25 @@ private ImmutableArray<TypeParameterSymbol> MakeTypeParameters(MethodDeclaration
             return result.ToImmutableAndFree();
         }
 
+        const DeclarationModifiers PartialMethodExtendedModifierMask =
+            DeclarationModifiers.Virtual |
+            DeclarationModifiers.Override |
+            DeclarationModifiers.New |
+            DeclarationModifiers.Sealed |
+            DeclarationModifiers.Extern;
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs:940]: Partial methods are already permitted to be static.

[the remark this answers is not in the document]
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs:940]: Ah yes. I keep forgetting that.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs [hunk 6]
```diff
@@ -637,6 +641,15 @@ internal bool IsPartialWithoutImplementation
             }
         }
 
+        internal sealed override bool IsNew
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs:644]: I think I have just run myself in a circle on this. My intention was to propose making this legal to support a scenario where a user declares a partial stub which hides a base member, and the generator that produces the implementation doesn't have to think about whether to copy over the 'new' modifier or not. I'll just revert this part.

One question I have: the precedent for misuse of 'new' is to give a warning, not an error. So should the mismatch of 'new' modifiers between parts be a warning or an error?

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:552]: have converted your bullet points to checkboxes :)

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs [hunk 7]
```diff
@@ -2566,6 +2566,25 @@ internal Binder GetBinder(CSharpSyntaxNode syntaxNode)
...
+                        {
+                            diagnostics.Add(ErrorCode.ERR_PartialMethodWithOutParamMustHaveImplementation, method.Locations[0], method);
+                        }
+                        else if (method.HasExplicitAccessMod)
+                        {
+                            diagnostics.Add(ErrorCode.ERR_PartialMethodWithAccessibilityModsMustHaveImplementation, method.Locations[0], method);
+                        }
+                        else if (method.HasExtendedPartialModifier)
+                        {
+                            diagnostics.Add(ErrorCode.ERR_PartialMethodWithExtendedModMustHaveImplementation, method.Locations[0], method);
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:2585]: Hmm, sounds like these diagnostics will change from "MustHaveImplementation" to "MustHaveAccessibility".

File: src/Compilers/CSharp/Portable/Errors/ErrorCode.cs [hunk 8]
```diff
@@ -1777,6 +1777,16 @@ internal enum ErrorCode
         ERR_ExpressionTreeContainsFromEndIndexExpression = 8791,
         ERR_ExpressionTreeContainsRangeExpression = 8792,
 
+        ERR_PartialMethodWithNonVoidReturnMustHaveImplementation = 9050,
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Errors/ErrorCode.cs:1780]: >9050 [](start = 67, length = 4)

Consider using one of the gaps above (for instance, 8755-), especially if some of these errors will be collapsed.

File: src/Compilers/CSharp/Portable/CSharpResources.resx [hunk 9]
```diff
@@ -6070,4 +6070,34 @@ To remove the warning, you can use /reference instead (set the Embed Interop Typ
...
+    <value>Both partial method declarations must have equivalent accessibility modifiers.</value>
+  </data>
+  <data name="ERR_PartialMethodVirtualDifference" xml:space="preserve">
+    <value>Both partial method declarations must be 'virtual' or neither may be 'virtual'.</value>
+  </data>
+  <data name="ERR_PartialMethodOverrideDifference" xml:space="preserve">
+    <value>Both partial method declarations must be 'override' or neither may be 'override'.</value>
+  </data>
+  <data name="ERR_PartialMethodSealedDifference" xml:space="preserve">
+    <value>Both partial method declarations must be 'sealed' or neither may be 'sealed'.</value>
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/CSharpResources.resx:6101]: the existing diagnostics have a distinct error code for 'static' mismatch, 'unsafe' mismatch and 'readonly' mismatch, but I am fine with grouping these together.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs [hunk 10]
```diff
@@ -289,13 +290,16 @@ private void MethodChecks(MethodDeclarationSyntax syntax, Binder withTypeParamsB
 
             if (IsPartial)
             {
-                // check that there are no out parameters in a partial
-                foreach (var p in this.Parameters)
+                if (MessageID.IDS_FeatureExtendedPartialMethods.GetFeatureAvailabilityDiagnosticInfo(DeclaringCompilation) is { } info)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs:293]: >if (MessageID.IDS_FeatureExtendedPartialMethods.GetFeatureAvailabilityDiagnosticInfo(DeclaringCompilation) is { } info) [](start = 16, length = 119)

Consider moving this inside `if (p.RefKind == RefKind.Out) { ... }`.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs [hunk 11]
```diff
@@ -905,23 +932,25 @@ private ImmutableArray<TypeParameterSymbol> MakeTypeParameters(MethodDeclaration
             return result.ToImmutableAndFree();
         }
 
+        const DeclarationModifiers PartialMethodExtendedModifierMask =
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs:935]: >const [](start = 8, length = 5)

`private`

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs [hunk 12]
```diff
@@ -7474,15 +7474,18 @@ public partial class C2
...
                 //     partial System.Collections.Generic.IAsyncEnumerable<int> M([EnumeratorCancellation] CancellationToken token); // 5
-                Diagnostic(ErrorCode.ERR_PartialMethodMustReturnVoid, "M").WithLocation(16, 62),
+                Diagnostic(ErrorCode.ERR_PartialMethodWithNonVoidReturnMustHaveImplementation, "M").WithArguments("C2.M(System.Threading.CancellationToken)").WithLocation(16, 62),
                 // (16,65): warning CS8424: The EnumeratorCancellationAttribute applied to parameter 'token' will have no effect. The attribute is only effective on a parameter of type CancellationToken in an async-iterator method returning IAsyncEnumerable
                 //     partial System.Collections.Generic.IAsyncEnumerable<int> M([EnumeratorCancellation] CancellationToken token); // 5
                 Diagnostic(ErrorCode.WRN_UnconsumedEnumeratorCancellationAttributeUsage, "EnumeratorCancellation").WithArguments("token").WithLocation(16, 65),
-                // (17,68): error CS0766: Partial methods must have a void return type
+                // (17,68): error CS1994: The 'async' modifier can only be used in methods that have a body.
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs:7483]: >The 'async' modifier can only be used in methods that have a body [](start = 42, length = 65)

Are we testing a `partial async` method with an implementation?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs:7483]: hmm, 'async' is a good catch. It feels like we could allow 'async' on only the implementation part of a partial method.

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs [hunk 13]
```diff
@@ -0,0 +1,552 @@
...
+partial class C
+{
+    partial void M1(out int value) { value = 42; }
+}
+";
+            var verifier = CompileAndVerify(new[] { text1, text2 }, parseOptions: TestOptions.RegularWithExtendedPartialMethods, expectedOutput: "42");
+            verifier.VerifyDiagnostics();
+        }
+
+        public static readonly object[][] s_accessMods = new[]
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:140]: >public [](start = 8, length = 6)

`private`?

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs [hunk 14]
```diff
@@ -0,0 +1,552 @@
...
+            comp.VerifyDiagnostics(
+                // (4,38): error CS8652: The feature 'extended partial methods' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
+                //     internal override partial string ToString();
+                Diagnostic(ErrorCode.ERR_FeatureInPreview, "ToString").WithArguments("extended partial methods").WithLocation(4, 38),
+                // (5,38): error CS8652: The feature 'extended partial methods' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
+                //     internal override partial string ToString() => "hello";
+                Diagnostic(ErrorCode.ERR_FeatureInPreview, "ToString").WithArguments("extended partial methods").WithLocation(5, 38)
+            );
+            comp = CreateCompilation(text1, parseOptions: TestOptions.RegularWithExtendedPartialMethods);
+            comp.VerifyDiagnostics();
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:450]: >VerifyDiagnostics [](start = 17, length = 17)

Shouldn't we report an error that the `override` of `ToString()` is `internal`?

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs [hunk 15]
```diff
@@ -0,0 +1,552 @@
...
+            );
+        }
+
+        [Fact]
+        public void Sealed_LangVersion()
+        {
+            const string text1 = @"
+class C
+{
+    internal virtual void M1() { }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:529]: >internal virtual void M1() { } [](start = 4, length = 30)

Not used.

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs (hunk 3 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:638]: Please also verify the IL for a call to `M1()` to ensure the call is emitted.

---
In reply to: [417430836](https://github.com/dotnet/roslyn/pull/43582#discussion_r417430836) [](ancestors = 417430836)

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs [hunk 16]
```diff
@@ -0,0 +1,552 @@
...
+
+partial class D : C
+{
+    partial void M1();
+    new partial void M1() { }
+}";
+            var comp = CreateCompilation(text1, parseOptions: TestOptions.RegularWithExtendedPartialMethods);
+            comp.VerifyDiagnostics();
+        }
+    }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:840]: >} [](start = 4, length = 1)

Please include a test with the same modifiers in definition and implementation parts but different order.

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs [hunk 17]
```diff
@@ -12551,44 +12551,6 @@ protected struct S<T, U, V>
                 Diagnostic(ErrorCode.ERR_BadVisBound, "A<A<V>>").WithArguments("C2.S<T, U, V>", "C1.A<C1.A<V>>").WithLocation(12, 19));
         }
 
-        [Fact]
-        public void CS07ERR_BadVisBound02()
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs:12555]: >CS07ERR_BadVisBound02 [](start = 20, length = 21)

Why remove this test? It seems like the `ERR_BadVisBound` errors should still be reported.

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs (hunk 14 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:450]: Weird, I will look into why this is happening.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs [hunk 18]
```diff
@@ -289,13 +290,16 @@ private void MethodChecks(MethodDeclarationSyntax syntax, Binder withTypeParamsB
...
             {
-                // check that there are no out parameters in a partial
-                foreach (var p in this.Parameters)
+                if (MessageID.IDS_FeatureExtendedPartialMethods.GetFeatureAvailabilityDiagnosticInfo(DeclaringCompilation) is { } info)
                 {
-                    if (p.RefKind == RefKind.Out)
+                    // check that there are no out parameters in a partial
+                    foreach (var p in this.Parameters)
                     {
-                        diagnostics.Add(ErrorCode.ERR_PartialMethodCannotHaveOutParameters, location);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs:297]: >ERR_PartialMethodCannotHaveOutParameters [](start = 50, length = 40)

If we are no longer reporting this error, please consider commenting out the `ErrorCode` field and removing the resource string.

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs [hunk 19]
```diff
@@ -13564,26 +13546,6 @@ public static int Main()
                 new ErrorDescription { Code = (int)ErrorCode.ERR_PartialMethodOnlyInPartialClass, Line = 5, Column = 18 });
         }
 
-        [Fact]
-        public void CS0752ERR_PartialMethodCannotHaveOutParameters()
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs:13568]: >CS0752ERR_PartialMethodCannotHaveOutParameters [](start = 20, length = 46)

Let's keep the test, even though the behavior has changed.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs [hunk 20]
```diff
@@ -905,23 +932,25 @@ private ImmutableArray<TypeParameterSymbol> MakeTypeParameters(MethodDeclaration
...
-                     DeclarationModifiers.New |
-                     DeclarationModifiers.Sealed |
-                     DeclarationModifiers.Extern;
-
             bool isExplicitInterfaceImplementationInInterface = isExplicitInterfaceImplementation && ContainingType.IsInterface;
 
-            if (IsPartial && !ReturnsVoid)
+            if (IsPartial && (!ReturnsVoid || HasExplicitAccessMod || HasExtendedPartialModifier))
             {
-                diagnostics.Add(ErrorCode.ERR_PartialMethodMustReturnVoid, location);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs:922]: >ERR_PartialMethodMustReturnVoid [](start = 42, length = 31)

If we are no longer reporting this error, please consider commenting out the `ErrorCode` field and removing the resource.

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs [hunk 21]
```diff
@@ -13950,31 +13912,6 @@ public void CS0764ERR_PartialMethodUnsafeDifference()
                 Diagnostic(ErrorCode.ERR_PartialMethodUnsafeDifference, "M2").WithLocation(5, 25));
         }
 
-        [Fact]
-        public void CS0766ERR_PartialMethodMustReturnVoid()
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs:13954]: >CS0766ERR_PartialMethodMustReturnVoid [](start = 20, length = 37)

Please keep the test even though behavior has changed.

**Comment by cston** [comment]
>         }

Do we have a test for the following? Do we report "CS0663: 'Program' cannot define an overloaded method that differs only on parameter modifiers 'out' and 'ref'"?
```
class Program
{
    partial static void M(ref object o);
    partial static void M(out object o);
    partial static void M(out object o) { o = null; }
}
```

---
Refers to: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs:20480 in 94e8743. [](commit_id = 94e8743bf65ec3ad680edbeaba6ad20c61a1cf4d, deletion_comment = False)

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs [hunk 22]
```diff
@@ -0,0 +1,841 @@
...
+        }
+
+        [Fact]
+        public void NonVoidReturnType_NoImpl()
+        {
+            const string text = @"
+partial class C
+{
+    private partial int M1();
+}";
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:65]: Please also test:
```
partial class C
{
    partial int M1();
}
```

**Comment by RikkiGibson** [comment]
After examining the existing behavior for 'async partial' methods it feels like the declaration part of a method should not have 'IsExtern == true' just because the implementation uses the 'extern' keyword. So I will revert that bit of the change+tests.

File: src/Compilers/CSharp/Portable/CSharpResources.resx [hunk 23]
```diff
@@ -6070,4 +6070,28 @@ To remove the warning, you can use /reference instead (set the Embed Interop Typ
...
+    <value>Partial method '{0}' must have an implementation part because it has accessibility modifiers.</value>
+  </data>
+  <data name="ERR_PartialMethodWithExtendedModMustHaveAccessMods" xml:space="preserve">
+    <value>Partial method '{0}' must have accessibility modifiers because it has a 'virtual', 'override', 'sealed', or 'new', or 'extern' modifier.</value>
+  </data>
+  <data name="ERR_PartialMethodExplicitAccessibilityDifference" xml:space="preserve">
+    <value>Both partial method declarations must have accessibility modifiers or neither may have accessibility modifiers.</value>
+  </data>
+  <data name="ERR_PartialMethodAccessibilityDifference" xml:space="preserve">
+    <value>Both partial method declarations must have equivalent accessibility modifiers.</value>
```
Comment (cston) [inline src/Compilers/CSharp/Portable/CSharpResources.resx:6092]: >equivalent accessibility modifiers [](start = 54, length = 34)

Consider saying "identical accessibility modifiers" instead. With "equivalent", in an "internal class" could one part use "public" and the other part use "internal" for instance?

File: src/Compilers/CSharp/Portable/CSharpResources.resx [hunk 24]
```diff
@@ -6070,4 +6070,28 @@ To remove the warning, you can use /reference instead (set the Embed Interop Typ
...
+  </data>
+  <data name="ERR_PartialMethodExtendedModDifference" xml:space="preserve">
+    <value>Both partial method declarations must have equal combinations of 'virtual', 'override', 'sealed', or 'new' modifiers.</value>
```
Comment (cston) [inline src/Compilers/CSharp/Portable/CSharpResources.resx:6095]: >equal combinations of [](start = 54, length = 21)

Perhaps "identical".

File: src/Compilers/CSharp/Portable/CSharpResources.resx [hunk 25]
```diff
@@ -6070,4 +6070,34 @@ To remove the warning, you can use /reference instead (set the Embed Interop Typ
...
+  </data>
+  <data name="ERR_PartialMethodWithOutParamMustHaveImplementation" xml:space="preserve">
+    <value>Partial method {0} must have an implementation part because it has 'out' parameters.</value>
+  </data>
+  <data name="ERR_PartialMethodWithAccessibilityModsMustHaveImplementation" xml:space="preserve">
+    <value>Partial method {0} must have an implementation part because it has accessibility modifiers.</value>
+  </data>
+  <data name="ERR_PartialMethodWithExtendedModMustHaveImplementation" xml:space="preserve">
+    <value>Partial method {0} must have an implementation part because it has a 'virtual', 'override', 'sealed', or 'new', or 'extern' modifier.</value>
+  </data>
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/CSharpResources.resx:6087]: Fixed

File: src/Compilers/CSharp/Portable/CSharpResources.resx (hunk 9 above)
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/CSharpResources.resx]: Fixed

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs [hunk 26]
```diff
@@ -2566,6 +2566,25 @@ internal Binder GetBinder(CSharpSyntaxNode syntaxNode)
                     {
                         diagnostics.Add(ErrorCode.ERR_PartialMethodInconsistentTupleNames, method.Locations[0], method, method.OtherPartOfPartial);
                     }
+                    else if (method.IsPartialDefinition && method.OtherPartOfPartial is null)
+                    {
+                        if (!method.ReturnType.IsVoidType())
+                        {
+                            diagnostics.Add(ErrorCode.ERR_PartialMethodWithNonVoidReturnMustHaveImplementation, method.Locations[0], method);
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs]: Fixed

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs [hunk 27]
```diff
@@ -2566,6 +2566,25 @@ internal Binder GetBinder(CSharpSyntaxNode syntaxNode)
...
+                        }
+                        else if (method.Parameters.Any(p => p.RefKind == RefKind.Out))
+                        {
+                            diagnostics.Add(ErrorCode.ERR_PartialMethodWithOutParamMustHaveImplementation, method.Locations[0], method);
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs]: Fixed

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs (hunk 7 above)
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs]: Fixed

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs]: For now we will simply require identical combinations of 'new' modifiers. Can revisit if there is a compelling reason to.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs [hunk 28]
```diff
@@ -756,7 +769,9 @@ internal override bool IsExpressionBodied
             get { return _isExpressionBodied; }
         }
 
-        private DeclarationModifiers MakeModifiers(SyntaxTokenList modifiers, MethodKind methodKind, bool hasBody, Location location, DiagnosticBag diagnostics, out bool modifierErrors)
+        internal bool HasExplicitAccessMod { get; }
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs]: Fixed

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:788]: Fixed

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs (hunk 10 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs]: Moved the check to 'CheckModifiers'.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs (hunk 12 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs]: Turns out this is a pre-existing behavior.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs (hunk 11 above)
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs]: Fixed

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs]: Fixed

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs (hunk 22 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:65]: Done

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs (hunk 14 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:578]: Fixed

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs (hunk 15 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:649]: Fixed

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs (hunk 16 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:1429]: Added test `SealedOverride_Reordered`.

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs (hunk 17 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs]: Restored the test.

File: src/Compilers/CSharp/Portable/Errors/ErrorCode.cs (hunk 8 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Errors/ErrorCode.cs]: Fixed

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs (hunk 18 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs:297]: Done

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs (hunk 19 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs:13568]: Restored the test.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs (hunk 20 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs:922]: Done.

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs (hunk 21 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs]: Restored the test.

**Comment by RikkiGibson** [comment]
https://github.com/dotnet/roslyn/pull/43582#issuecomment-621487730

> Do we have a test for the following? Do we report "CS0663: 'Program' cannot define an overloaded method that differs only on parameter modifiers 'out' and 'ref'"?
> ```
> class Program
> {
>     partial static void M(ref object o);
>     partial static void M(out object o);
>     partial static void M(out object o) { o = null; }
> }
> ```

No, but `PartialMethodsConsiderRefKindDifferences_RefWithOut` is similar. Will add the test.

File: src/Compilers/CSharp/Portable/CSharpResources.resx [hunk 29]
```diff
@@ -6070,4 +6064,25 @@ To remove the warning, you can use /reference instead (set the Embed Interop Typ
...
+    <value>Partial method '{0}' must have accessibility modifiers because it has a non-void return type.</value>
+  </data>
+  <data name="ERR_PartialMethodWithOutParamMustHaveAccessMods" xml:space="preserve">
+    <value>Partial method '{0}' must have accessibility modifiers because it has 'out' parameters.</value>
+  </data>
+  <data name="ERR_PartialMethodWithAccessibilityModsMustHaveImplementation" xml:space="preserve">
+    <value>Partial method '{0}' must have an implementation part because it has accessibility modifiers.</value>
+  </data>
+  <data name="ERR_PartialMethodWithExtendedModMustHaveAccessMods" xml:space="preserve">
+    <value>Partial method '{0}' must have accessibility modifiers because it has a 'virtual', 'override', 'sealed', or 'new', or 'extern' modifier.</value>
```
Comment (cston) [inline src/Compilers/CSharp/Portable/CSharpResources.resx:6080]: >or  [](start = 116, length = 3)

Minor: Was this "or" intentional ("new" is not the last item)?

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs [hunk 30]
```diff
@@ -0,0 +1,1430 @@
...
+";
+            var verifier = CompileAndVerify(text, parseOptions: TestOptions.RegularWithExtendedPartialMethods, expectedOutput: "1");
+            verifier.VerifyDiagnostics(
+                // (7,31): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
+                //     private static async Task CompletedTask() { }
+                Diagnostic(ErrorCode.WRN_AsyncLacksAwaits, "CompletedTask").WithLocation(7, 31));
+
+            var method = (MethodSymbol)verifier.Compilation.GetMembers("C.M1")[0];
+            Assert.True(method.IsPartialDefinition());
+            // PROTOTYPE: it feels like both IsAsync/IsExtern should be shared between
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:1054]: >IsAsync/IsExtern should be shared between [](start = 45, length = 41)

Do we have a test with `async` on both parts or `async` on the declaration only?
```C#
private static partial async Task F();
private static partial Task F()
{
    await Task.Yield(); // error on await?
}
```

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs [hunk 31]
```diff
@@ -0,0 +1,1430 @@
...
+                //     override partial void M1();
+                Diagnostic(ErrorCode.ERR_PartialMethodWithExtendedModMustHaveAccessMods, "M1").WithArguments("D.M1()").WithLocation(9, 27),
+                // (9,27): error CS0507: 'D.M1()': cannot change access modifiers when overriding 'internal' inherited member 'C.M1()'
+                //     override partial void M1();
+                Diagnostic(ErrorCode.ERR_CantChangeAccessOnOverride, "M1").WithArguments("D.M1()", "internal", "C.M1()").WithLocation(9, 27),
+                // (10,27): error CS8796: Partial method 'D.M1()' must have accessibility modifiers because it has a 'virtual', 'override', 'sealed', or 'new', or 'extern' modifier.
+                //     override partial void M1() { }
+                Diagnostic(ErrorCode.ERR_PartialMethodWithExtendedModMustHaveAccessMods, "M1").WithArguments("D.M1()").WithLocation(10, 27)
+            );
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:641]: >} [](start = 8, length = 1)

Consider asserting value of `comp.GetMember<MethodSymbol>("D.M1").OverriddenMethod`, even if `null`, to catch cases where the behavior changes perhaps unexpectedly.

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs [hunk 32]
```diff
@@ -0,0 +1,1430 @@
...
+
+partial class C
+{
+    public partial void M([AllowNull] string s1) // 1
+    {
+        s1.ToString(); // 2
+    }
+}
+";
+            // PROTOTYPE: should it be allowed to specify duplicate nullability attributes?
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:1351]: >should it be allowed to specify duplicate nullability attributes? [](start = 26, length = 65)

If we allow nullability attributes on both parts, we should allow attributes on both parts for all attributes.

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs (hunk 19 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs:13568]: Thanks. It looks like the order of this method and the previous method has changed. Please consider reverting the order.

---
In reply to: [418715785](https://github.com/dotnet/roslyn/pull/43582#discussion_r418715785) [](ancestors = 418715785)

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs [hunk 33]
```diff
@@ -20495,15 +20512,15 @@ public void PartialMethodsConsiderRefKindDifferences_NoneWithOut()
         {
             CreateCompilation(@"
 partial class C {
-    partial void M(int i);
-    partial void M(out int i) { i = 0; }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs:20499]: Just curious - is there a reason to change the test (from no accessibility to `internal`)? If not, please consider reverting even though behavior has changed.

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs (hunk 19 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs:13568]: Thanks, I figured out how to easily compare my working copy to the base, now it's easier to spot these kinds of mixups.

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs (hunk 32 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:1351]: It is feeling like maybe we should just ship the current rules and see how people feel about it. Adding special allowances for duplicate attributes in partials seems like something you can't just implement speculatively, we have to see how people end up using/experiencing it.

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs (hunk 30 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:1093]: Added the tests.

File: src/Compilers/CSharp/Portable/CSharpResources.resx (hunk 29 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/CSharpResources.resx]: Fixed.

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs (hunk 31 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:680]: Added some checks of the OverriddenMethod

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs (hunk 33 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs:20499]: Reverted, thanks. This was more of an artifact from the way this change originally worked.

File: src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs [hunk 34]
```diff
@@ -9228,56 +9228,59 @@ public partial interface I1
...
-                //     static extern partial void M10(); 
-                Diagnostic(ErrorCode.ERR_PartialMethodInvalidModifier, "M10").WithLocation(22, 32),
-                // (22,32): error CS0756: A partial method may not have multiple defining declarations
-                //     static extern partial void M10(); 
-                Diagnostic(ErrorCode.ERR_PartialMethodOnlyOneLatent, "M10").WithLocation(22, 32),
-                // (23,35): error CS0750: A partial method cannot have access modifiers or the virtual, abstract, override, new, sealed, or extern modifiers
+                // (21,25): error CS0111: Type 'I1' already defines a member called 'M9' with the same parameter types
+                //     static partial void M9();
+                Diagnostic(ErrorCode.ERR_MemberAlreadyExists, "M9").WithArguments("M9", "I1").WithLocation(21, 25),
+                // (22,32): error CS8796: Partial method 'I1.M10()' must have accessibility modifiers because it has a 'virtual', 'override', 'sealed', or 'new', or 'extern' modifier.
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs:9242]: >or 'new', or 'extern' [](start = 152, length = 21)

Minor: It looks like there a number of comments with the previous error text.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs [hunk 35]
```diff
@@ -1682,10 +1682,13 @@ private void CheckMemberNameConflicts(DiagnosticBag diagnostics)
         // UNDONE: Consider adding a secondary location pointing to the second method.
         private void ReportMethodSignatureCollision(DiagnosticBag diagnostics, SourceMemberMethodSymbol method1, SourceMemberMethodSymbol method2)
         {
-            // Partial methods are allowed to collide by signature.
-            if (method1.IsPartial && method2.IsPartial)
+            switch (method1, method2)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:1685]: >switch (method1, method2) [](start = 12, length = 25)

Does this `switch` statement represent a change in behavior from the original `if`?

Unless there is a change in behavior, we should stick with the `if` statement since it is significantly simpler.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs [hunk 36]
```diff
@@ -7460,29 +7460,29 @@ public partial class C2
...
-                // (15,80): warning CS8424: The EnumeratorCancellationAttribute applied to parameter 'token' will have no effect. The attribute is only effective on a parameter of type CancellationToken in an async-iterator method returning IAsyncEnumerable
+                // (15,80): warning CS8424: The EnumeratorCancellationAttribute applied to parameter 'token' will have no effect. The attribute is only effective on a parameter of type CancellationToken in an async-iterator method returning IAsyncEnumerable    
                 //     public delegate System.Collections.Generic.IAsyncEnumerable<int> Delegate([EnumeratorCancellation] CancellationToken token); // 4
                 Diagnostic(ErrorCode.WRN_UnconsumedEnumeratorCancellationAttributeUsage, "EnumeratorCancellation").WithArguments("token").WithLocation(15, 80),
-                // (16,62): error CS0766: Partial methods must have a void return type
+                // (16,62): error CS9051: Partial method 'C2.M(CancellationToken)' must have accessibility modifiers because it has a non-void return type.
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs:7477]: >CS9051 [](start = 34, length = 6)

There are a number of instances of CS9051.

File: src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs [hunk 37]
```diff
@@ -9228,56 +9228,59 @@ public partial interface I1
                 //     static partial void M7();
                 Diagnostic(ErrorCode.ERR_MemberAlreadyExists, "M7").WithArguments("M7", "I1").WithLocation(19, 25),
                 // (20,25): error CS0757: A partial method may not have multiple implementing declarations
-                //     static partial void M8() {} 
+                //     static partial void M8() {}
                 Diagnostic(ErrorCode.ERR_PartialMethodOnlyOneActual, "M8").WithLocation(20, 25),
+                // (20,25): error CS0111: Type 'I1' already defines a member called 'M8' with the same parameter types
+                //     static partial void M8() {}
+                Diagnostic(ErrorCode.ERR_MemberAlreadyExists, "M8").WithArguments("M8", "I1").WithLocation(20, 25),
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs:9235]: >ERR_MemberAlreadyExists [](start = 37, length = 23)

Are we reporting a redundant error in some cases?

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs [hunk 38]
```diff
@@ -0,0 +1,1794 @@
...
+    {
+        M1();
+    }
+}";
+            var verifier = CompileAndVerify(
+                new[] { text1, text2 },
+                parseOptions: TestOptions.RegularWithExtendedPartialMethods,
+                expectedOutput: "1");
+            verifier.VerifyDiagnostics();
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:1632]: >} [](start = 8, length = 1)

Consider testing access outside the type hierarchy as well.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs (hunk 35 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:1685]: Yes, this fixes #43883. This solution ends up creating additional diagnostics in some error scenarios. I tried moving the checks for PartialMethodOnlyOneLatent/PartialMethodOnlyOneActual in here, but because partial method merging already happened in an earlier step, it causes us to miss diagnostics for multiple "actual" methods.

If we could do this at the same time or right before we merge partial methods, we might be able to get higher quality diagnostics in some scenarios when members have conflicting signatures:

1. if the methods are not 'partial', we report `ErrorCode.ERR_MemberAlreadyExists`
1. if we detect that both methods are partial implementations, we give `ErrorCode.ERR_PartialMethodOnlyOneActual`
1. if we detect that both methods are partial definitions, we give `ErrorCode.ERR_PartialMethodOnlyOneLatent`

It might also be possible to fix this by modifying the partial method signature comparer, that groups declarations that might be part of the same partial method, to be aware of RefKind differences.

Comment (cston) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:1685]: > This solution ends up creating additional diagnostics in some error scenarios.

That sounds ok. We can revisit this later if necessary.

---
In reply to: [418977822](https://github.com/dotnet/roslyn/pull/43582#discussion_r418977822) [](ancestors = 418977822)

File: src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs (hunk 37 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs:9235]: Yes https://github.com/dotnet/roslyn/pull/43582#discussion_r418977822

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs (hunk 36 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs]: Fixed

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs (hunk 38 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:1702]: Added more accessibility tests.

File: src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs (hunk 34 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs:9242]: Fixed.

**Comment by RikkiGibson** [comment]
@jaredpar please let me know if I have addressed all your comments.

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs [hunk 39]
```diff
@@ -0,0 +1,2018 @@
...
+using System.Diagnostics.CodeAnalysis;
+
+partial class C
+{
+    internal virtual partial void M1([AllowNull] string s1);
+    internal virtual partial void M1(string s1) { }
+}
+class D : C
+{
+    internal override void M1(string s1) // 1
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:504]: What about tests in the other direction: where the `override` is the `partial` member?

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs [hunk 40]
```diff
@@ -0,0 +1,2018 @@
...
+            var comp = CreateCompilation(new[] { text1, AllowNullAttributeDefinition }, parseOptions: TestOptions.RegularWithExtendedPartialMethods);
+            comp.VerifyDiagnostics(
+                // (11,36): warning CS8765: Nullability of type of parameter 's1' doesn't match overridden member (possibly because of nullability attributes).
+                //     internal override partial void M1(string s1); // 1
+                Diagnostic(ErrorCode.WRN_TopLevelNullabilityMismatchInParameterTypeOnOverride, "M1").WithArguments("s1").WithLocation(11, 36)
+            );
+        }
+
+        [Fact]
+        public void Override_AllowNull_02()
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:752]: Where is there a test where we have a `override partial` which involves `[AllowNull]` that succeeds?

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs [hunk 41]
```diff
@@ -0,0 +1,2018 @@
...
+{
+    internal override void M1([AllowNull] string s1)
+    {
+    }
+}";
+            var comp = CreateCompilation(new[] { text1, AllowNullAttributeDefinition }, parseOptions: TestOptions.RegularWithExtendedPartialMethods);
+            comp.VerifyDiagnostics();
+        }
+
+        [Fact]
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:586]: Consider an `override` test where the types change from generic parameters to actual types. Example:

```cs
class Base<T> {
  protected virtual void M(T p) { } 
}

partial class Derived : Base<string> {
  protected override partial void M(string p); 
  protected override partial void M(string p) { }
}
```

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs (hunk 40 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:752]: I'm not sure I understand. `Override_AllowNull_02` has the expected combination of `[AllowNull]` given on the parameters of the override, and it warns on dereference of the parameters. That seems successful.

File: src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs (hunk 41 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/Symbols/ExtendedPartialMethodsTests.cs:586]: Adding to the test plan and will address in a follow-up PR.
