### PR TITLE
Delay metadata reload

### LINKED ISSUE #12189: We should asynchronously retry reading of metadata if the file is locked
If the Workspaces layer fails to read a source file, we return an empty file for that particular snapshot, and then start an asynchronous retry process. If we can successfully read the file, we then force a new Solution snapshot to be created with the new text. We should do something similar for metadata references. if we try to read a metadata reference and it's still locked for some external process, we will continue to use a cached (and broken) `VisualStudioMetadataReference` until the file gets touched again.

### PR DESCRIPTION
**Pull request by Pilchie**
Fixes #12189, and restores the behavior of the native C# language service.

The problem here is that we frequently get the file change notification
while something is still writing the file, and so we get an IOException when
we try to read it, resulting in us caching empty metadata and reporting
spurious errors.

### CODE REVIEW

**Comment by Pilchie** [comment]
Same as #12640, but against `microupdate`, and with feedback applied.

**Comment by Pilchie** [comment]
test vsi please

**Comment by Pilchie** [comment]
@dotnet/roslyn-ide, @tmat please review.

@jasonmalinowski I've addressed almost all of your review feedback in the second commit here.  If we need waiters for this, I'm not sure how to implement them, since we don't know when the `IVsFileChangeEx` will dispatch the initial notification anyway :-S.

Do you feel comfortable with *just* this approach, or do you think I should continue pursuing the strategy in #12189?

**Comment by jasonmalinowski** [comment]
:shipit: I'd say #12189 is probably something to leave open for now, but could be left deprioritized if we get enough evidence this is sufficient in most real-world cases.

**Comment by Pilchie** [comment]
test vsi please

**Comment by Pilchie** [comment]
Hit #12503 and #11984 on VSI tests.

**Comment by Pilchie** [comment]
test vsi please

**Comment by Pilchie** [comment]
Can I get another signoff @dotnet/roslyn-ide?

@MattGertz - this is a DTS bug that I'd like to get approved, pending validation from the customer, who has private bits at the moment.

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/AbstractProject.cs [hunk 1]
```diff
@@ -584,8 +600,34 @@ private void RemoveMetadataReferenceCore(VisualStudioMetadataReference reference
...
+
+            delayTaskCancellationTokenSource = new CancellationTokenSource();
+            _changedReferencesPendingUpdate[reference] = delayTaskCancellationTokenSource;
+
+            var task = Task.Delay(TimeSpan.FromSeconds(5), delayTaskCancellationTokenSource.Token)
+                .ContinueWith(
+                    OnImportChangedAfterDelay,
+                    reference,
+                    delayTaskCancellationTokenSource.Token,
+                    TaskContinuationOptions.None,
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/AbstractProject.cs]: TaskContinuationOptions.OnlyOnNotCanceled.

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/AbstractProject.cs [hunk 2]
```diff
@@ -584,8 +600,34 @@ private void RemoveMetadataReferenceCore(VisualStudioMetadataReference reference
         /// </summary>
         private void OnImportChanged(object sender, EventArgs e)
         {
+            AssertIsForeground();
+
             VisualStudioMetadataReference reference = (VisualStudioMetadataReference)sender;
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/AbstractProject.cs]: var

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/AbstractProject.cs (hunk 1 above)
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/AbstractProject.cs]: does this overload only allow for an 'object' state?  Is it not strongly typed to the actual state (thus allowing you to make OnImportChangedAfterDelay take a VisualStudioMetadataReference instead?

If not, could you just pass a capturing lambda to make a typesafe call?  Is there a lot of value in doing it this way?

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/AbstractProject.cs [hunk 3]
```diff
@@ -584,8 +600,34 @@ private void RemoveMetadataReferenceCore(VisualStudioMetadataReference reference
         /// </summary>
         private void OnImportChanged(object sender, EventArgs e)
         {
+            AssertIsForeground();
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/AbstractProject.cs]: easier would be to make this an "async void" method.  Then you can just call "await" below and not need to manually continuewith.

(though you would need a try/catch for cancellation exceptions).  so your call.

**Comment by Pilchie** [comment]
Just wanted to point out that https://msdn.microsoft.com/en-us/library/mt752379.aspx  now contains this fix.
