### PR TITLE
Recover gracefully from a decision dag that somehow has cycles during construction.

### LINKED ISSUE #45946: ArgumentException in TopologicalSort.IterativeSort called from DecisionDagBuilder
Tracked internally at https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1131818?src=WorkItemMention&src-action=artifact_link

```none
uncaught ArgumentException
Microsoft.CodeAnalysis.ni!Microsoft.CodeAnalysis.TopologicalSort.IterativeSort[[System.__Canon,_mscorlib]] in TopologicalSort.cs
at Microsoft.CodeAnalysis.CSharp.ni!Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder in DecisionDagBuilder.cs
at Microsoft.CodeAnalysis.CSharp.ni!Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.ComputeBoundDecisionDagNodes in DecisionDagBuilder.cs
at Microsoft.CodeAnalysis.CSharp.ni!Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.MakeBoundDecisionDag in DecisionDagBuilder.cs
at Microsoft.CodeAnalysis.CSharp.ni!Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.CreateDecisionDagForIsPattern in DecisionDagBuilder.cs
at Microsoft.CodeAnalysis.CSharp.ni!Microsoft.CodeAnalysis.CSharp.Binder.MakeIsPatternExpression in Binder_Patterns.cs
at Microsoft.CodeAnalysis.CSharp.ni!Microsoft.CodeAnalysis.CSharp.Binder.BindIsPatternExpression in Binder_Patterns.cs
at Microsoft.CodeAnalysis.CSharp.ni!Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal in Binder_Expressions.cs
at Microsoft.CodeAnalysis.CSharp.ni!Microsoft.CodeAnalysis.CSharp.Binder.BindExpression in Binder_Expressions.cs
at Microsoft.CodeAnalysis.CSharp.ni!Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement in Binder_Statements.cs
at Microsoft.CodeAnalysis.CSharp.ni!Microsoft.CodeAnalysis.CSharp.Binder.BindStatement in Binder_Statements.cs
at Microsoft.CodeAnalysis.CSharp.ni!Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts in Binder_Statements.cs
at Microsoft.CodeAnalysis.CSharp.ni!Microsoft.CodeAnalysis.CSharp.Binder.BindBlock in Binder_Statements.cs
at Microsoft.CodeAnalysis.CSharp.ni!Microsoft.CodeAnalysis.CSharp.Binder.BindStatement in Binder_Statements.cs
at Microsoft.CodeAnalysis.CSharp.ni!Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody in Binder_Statements.cs
at Microsoft.CodeAnalysis.CSharp.ni!Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody in Binder_Statements.cs
at Microsoft.CodeAnalysis.CSharp.ni!Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody in MethodCompiler.cs
at Microsoft.CodeAnalysis.CSharp.ni!Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod in MethodCompiler.cs
...
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #45946
Because we do not know how to construct a scenario that reproduces the underlying issue, I do
not have an end-to-end test that demonstrates that this recovers gracefully. So review carefully!

### CODE REVIEW

**Comment by gafter** [comment]
A serious github bug is preventing this PR from showing any more iterations (e.g. a merge from master that addresses the CI failures)

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a couple of reviews of this code to prevent the compiler from crashing?

File: src/Compilers/Core/Portable/Collections/TopologicalSort.cs [hunk 1]
```diff
@@ -62,14 +63,11 @@ public static ImmutableArray<TNode> IterativeSort<TNode>(IEnumerable<TNode> node
...
             // At this point all the nodes should have been output, otherwise there was a cycle
-            if (predecessorCounts.Count != resultBuilder.Count)
-            {
-                throw new ArgumentException("Cycle in the input graph");
-            }
-
+            bool hadCycle = predecessorCounts.Count != resultBuilder.Count;
+            result = hadCycle ? ImmutableArray<TNode>.Empty : resultBuilder.ToImmutable();
             predecessorCounts.Free();
             ready.Free();
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/Collections/TopologicalSort.cs:69]: Looks like there is a missing `resultBuilder.Free();` here.

File: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs [hunk 2]
```diff
@@ -809,7 +809,23 @@ DagState uniqifyState(ImmutableArray<StateForCase> cases, ImmutableDictionary<Bo
...
+            // Process the states in topological order, leaves first, and assign a BoundDecisionDag to each DagState.
+            bool wasAcyclic = decisionDag.TryGetTopologicallySortedReachableStates(out ImmutableArray<DagState> sortedStates);
+            if (!wasAcyclic)
+            {
+                // If the dag contains a cycle, return a short-circuit dag instead.
+
+                // Since we intended the set of DagState nodes to be acyclic by construction, we do not know how
+                // this can happen, but since it does occasionally happen we need to recover gracefully to avoid
+                // crashing the compiler.  See also https://github.com/dotnet/roslyn/issues/45946
+                // If you figure out how it occurs, please modify the DagState construction process to avoid that.
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs:824]: Should we include a `Debug.Assert(false)` call here? That way if we do hit this in the future while dogfooding Roslyn we will get an alert and can investigate.

File: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs [hunk 3]
```diff
@@ -1332,10 +1346,15 @@ private static ImmutableArray<DagState> Successor(DagState state)
...
+            /// <summary>
+            /// Produce the states in topological order.
+            /// </summary>
+            /// <param name="result">Topologically sorted <see cref="DagState"/> nodes.</param>
+            /// <returns>True if the graph was acyclic.</returns>
+            public bool TryGetTopologicallySortedReachableStates(out ImmutableArray<DagState> result)
             {
-                // Now process the states in topological order, leaves first, and assign a BoundDecisionDag to each DagState.
-                return TopologicalSort.IterativeSort<DagState>(SpecializedCollections.SingletonEnumerable<DagState>(this.RootNode), Successor);
+                //
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs:1356]: Empty comment?

File: src/Compilers/Core/Portable/Collections/TopologicalSort.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/Core/Portable/Collections/TopologicalSort.cs:69]: It isn't pooled.

---
In reply to: [455509300](https://github.com/dotnet/roslyn/pull/45983#discussion_r455509300) [](ancestors = 455509300)

**Comment by gafter** [comment]
@jaredpar I've responded to your comments. Do you have any others?
@dotnet/roslyn-compiler @cston May I please have a second review?

**Comment by cston** [comment]
Regarding a repro, calling `GetDiagnostics()` on the following hits the issue.
```C#
class C
{
    void F(object o)
    {
        _ = is this.F(1);
    }
}
```

**Comment by gafter** [comment]
@cston Thank you for the repro! I have verified that this code no longer crashes (commit 1, except in debug builds), and have corrected the cycle in decision dag construction (commit 2). Could you please re-review?
@jaredpar Please review the updated PR including responses to your comments.

**Comment by cston** [comment]
>             // that a cycle is induced. Nevertheless, to avoid flakiness in the tests, we do not

Is the comment still correct? Based on the `Assert.False(wasAcyclic)`, it looks like a cycle is expected always.

---
Refers to: src/Compilers/Core/CodeAnalysisTest/Collections/TopologicalSortTests.cs:150 in 31591c8. [](commit_id = 31591c8bc58216caf65b3f8834f5ac927e1ade96, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs [hunk 4]
```diff
@@ -809,7 +809,23 @@ DagState uniqifyState(ImmutableArray<StateForCase> cases, ImmutableDictionary<Bo
...
+            bool wasAcyclic = decisionDag.TryGetTopologicallySortedReachableStates(out ImmutableArray<DagState> sortedStates);
+            if (!wasAcyclic)
+            {
+                // If the dag contains a cycle, return a short-circuit dag instead.
+                decisionDag.RootNode.Dag = defaultDecision;
+
+                // Since we intended the set of DagState nodes to be acyclic by construction, we do not know how
+                // this can happen, but since it does occasionally happen we need to recover gracefully to avoid
+                // crashing the compiler.  See also https://github.com/dotnet/roslyn/issues/45946
+                // If you figure out how it occurs, please modify the DagState construction process to avoid that.
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs:825]: Should this comment be updated? Perhaps: "Since we intended the set of DagState nodes to be acyclic by construction this is not expected. If the assert fails, please modify the DagState construction process to avoid the cycle."

**Comment by cston** [comment]
>                 return true;

This check can be removed.

---
Refers to: src/Compilers/CSharp/Portable/Binder/SwitchExpressionBinder.cs:89 in 31591c8. [](commit_id = 31591c8bc58216caf65b3f8834f5ac927e1ade96, deletion_comment = False)

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests2.cs [hunk 5]
```diff
@@ -2943,5 +2943,23 @@ void checkType(ExpressionSyntax expr, string expectedNaturalType, string expecte
...
+    {
+        _ = is this.F(1);
+    }
+}";
+            CreateCompilation(source).VerifyDiagnostics(
+                // (6,13): error CS1525: Invalid expression term 'is'
+                //         _ = is this.F(1);
+                Diagnostic(ErrorCode.ERR_InvalidExprTerm, "is").WithArguments("is").WithLocation(6, 13)
+                );
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests2.cs:2963]: >} [](start = 8, length = 1)

Consider testing a `switch` expression as well.
```C#
class C
{
    void F(object o)
    {
        _ = switch { this.F(1) => true };
    }
}
```

**Comment by gafter** [comment]
>                 return true;

It still serves to suppress cascaded diagnostics.

---
In reply to: [660260314](https://github.com/dotnet/roslyn/pull/45983#issuecomment-660260314) [](ancestors = 660260314)

---
Refers to: src/Compilers/CSharp/Portable/Binder/SwitchExpressionBinder.cs:89 in 31591c8. [](commit_id = 31591c8bc58216caf65b3f8834f5ac927e1ade96, deletion_comment = False)

**Comment by cston** [comment]
>                 return true;

The same condition is checked below. One of the two checks can be removed.

---
In reply to: [660303072](https://github.com/dotnet/roslyn/pull/45983#issuecomment-660303072) [](ancestors = 660303072,660260314)

---
Refers to: src/Compilers/CSharp/Portable/Binder/SwitchExpressionBinder.cs:89 in 31591c8. [](commit_id = 31591c8bc58216caf65b3f8834f5ac927e1ade96, deletion_comment = False)

**Comment by gafter** [comment]
>             // that a cycle is induced. Nevertheless, to avoid flakiness in the tests, we do not

The additional edge induces a cycle for all of the specific seeds that this test runs on (see the `[Theory]` above).

---
In reply to: [660245120](https://github.com/dotnet/roslyn/pull/45983#issuecomment-660245120) [](ancestors = 660245120)

---
Refers to: src/Compilers/Core/CodeAnalysisTest/Collections/TopologicalSortTests.cs:150 in 31591c8. [](commit_id = 31591c8bc58216caf65b3f8834f5ac927e1ade96, deletion_comment = False)

**Comment by gafter** [comment]
@cston I have replied to your comments. Do you have any others?

**Comment by gafter** [comment]
@cston @jaredpar I have replied to your comments. Do you have any others?
