### PR TITLE
Move merging of partial members to an earlier phase of members construction.

### LINKED ISSUE #75002: Ambiguity errors reported from `SemanticModel.GetDiagnostics()` for calls to partial members on type with primary constructor
**Version Used**: 2ff1a4768213b0e6d8d5762fae6cebd2af6b04bd

**Steps to Reproduce**:

Run the following unit test.

```csharp
[Fact]
public void PartialMembers()
{
    var source1 = """
        C c = null;
        c.M();
        _ = c.P;
        """;
    var source2 = """
        partial class C(int p)
        {
            public partial void M() { }
            public partial void M();
            public partial object P { get; }
            public partial object P { get => null; }
        }
        """;
    var comp = CreateCompilation([source1, source2]);
    var tree = comp.SyntaxTrees[0];
    var model = comp.GetSemanticModel(tree);
    model.GetDiagnostics().Verify(
        // (2,3): error CS0121: The call is ambiguous between the following methods or properties: 'C.M()' and 'C.M()'
        // c.M();
        Diagnostic(ErrorCode.ERR_AmbigCall, "M").WithArguments("C.M()", "C.M()").WithLocation(2, 3),
        // (3,7): error CS0229: Ambiguity between 'C.P' and 'C.P'
        // _ = c.P;
        Diagnostic(ErrorCode.ERR_AmbigMember, "P").WithArguments("C.P", "C.P").WithLocation(3, 7));
}
```

**Expected Behavior**:
No errors from the call to `model.GetDiagnostics()`.

**Actual Behavior**:
Ambiguity errors included above.

### LINKED ISSUE #76651: Incorrect "CS0229 Ambiguity between" for partial prop with primary ctor, at design time only
**Version Used**: 17.13.0 Preview 2.1

Thanks to @RoccoZero who reported that this issue has been happening for a few months.

1. Building succeeds, though the error list and code editor show the errors.
1. The repro requires separate source files.
1. The repro disappears if the primary ctor is deleted.

###### .csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

</Project>
```

###### File 1

```cs
partial class PartialClass
{
    public partial string Prop => null;
}

partial class PartialClass(int p)
{
    public partial string Prop { get; }
}
```

###### File 2

```cs
class Repro
{
    void M(PartialClass c)
    {
        // ❌ CS0229 Ambiguity between 'PartialClass.Prop' and 'PartialClass.Prop'
        _ = c.Prop;
        _ = c.Prop; // Yep, error still here.
        _ = new PartialClass(0).Prop; // No error here!
        _ = c.Prop; // ERROR DISAPPEARS
        _ = c.Prop; // IT'S STILL GONE
    }
}
```

Image

Image

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #76651.
Fixes #75002.
Related to #76842.
Related to #76870.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@RikkiGibson, @cston, @dotnet/roslyn-compiler Please review

**Comment by AlekseyTs** [comment]
@jjonescz, FYI

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs [hunk 1]
```diff
@@ -3691,9 +3755,31 @@ private void MergePartialMembers(
...
+            static void fixupNotMergedPartialProperty(Symbol symbol)
+            {
+                Debug.Assert(symbol.IsPartialMember());
+                if (symbol is SourcePropertySymbol { OtherPartOfPartial: null } property)
+                {
+                    property.SetMergedBackingField(property.DeclaredBackingField);
+                }
+            }
+
+            void mergePartialMethods(ArrayBuilder<Symbol> nonTypeMembers, SourceOrdinaryMethodSymbol currentMethod, SourceOrdinaryMethodSymbol prevMethod, BindingDiagnosticBag diagnostics)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:3782]: >mergePartialMethods [](http://example.com/codeflow?start=17&length=19)

static?

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs [hunk 2]
```diff
@@ -3709,12 +3795,11 @@ void mergePartialMethods(ref Dictionary<ReadOnlyMemory<char>, ImmutableArray<Sym
...
                 else
                 {
-                    DuplicateMembersByNameIfCached(ref membersByName);
-                    membersByName[name] = FixPartialMethod(membersByName[name], prevMethod, currentMethod);
+                    FixPartialMethod(nonTypeMembers, prevMethod, currentMethod);
                 }
             }
 
-            void mergePartialProperties(ref Dictionary<ReadOnlyMemory<char>, ImmutableArray<Symbol>> membersByName, ReadOnlyMemory<char> name, SourcePropertySymbol currentProperty, SourcePropertySymbol prevProperty, BindingDiagnosticBag diagnostics)
+            void mergePartialProperties(ArrayBuilder<Symbol> nonTypeMembers, SourcePropertySymbol currentProperty, SourcePropertySymbol prevProperty, BindingDiagnosticBag diagnostics)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:3802]: >mergePartialProperties [](http://example.com/codeflow?start=17&length=22)

static?

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:3782]: > static?

I do not think I changed anything that affects ability to place the modifier on the method. Therefore, I won't try adding it, unless there is other feedback to take care.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:3802]: > static?

Same response

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:3782]: Scratch that, it looks like I removed ```DuplicateMembersByNameIfCached``` call

Comment (jcouv) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:3782]: It looks like the containing method `MergePartialMembers` could be marked static too

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 2)

**Comment by AlekseyTs** [comment]
@RikkiGibson, @cston, @dotnet/roslyn-compiler For the second review

**Comment by AlekseyTs** [comment]
@RikkiGibson, @cston, @dotnet/roslyn-compiler For the second review

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs [hunk 3]
```diff
@@ -3816,27 +3890,28 @@ private static void FixPartialProperty(ref Dictionary<ReadOnlyMemory<char>, Immu
...
 
             SourcePropertySymbol.InitializePartialPropertyParts(definition, implementation);
 
             // a partial property is represented in the member list by its definition part:
-            membersByName[name] = Remove(membersByName[name], implementation);
+            Remove(nonTypeMembers, implementation);
         }
 
-        private static ImmutableArray<Symbol> Remove(ImmutableArray<Symbol> symbols, Symbol symbol)
+        private static void Remove(ArrayBuilder<Symbol> symbols, Symbol symbol)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:3902]: >ArrayBuilder<Symbol> symbols [](http://example.com/codeflow?start=35&length=28)

It looks like we call `Remove` once for each partial method or property that has both parts. Does the `symbols` array contain all non-type members? If that's the case, the number of `ReferenceEquals()` calls across all `Remove` calls for the containing type will be roughly N*M where N is the number of non-type members and M is the number of partial members. Are there cases where that might be an issue?

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs (hunk 3 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:3902]: > Are there cases where that might be an issue?

It is hard to tell for sure. I assume that ```ReferenceEquals``` call is pretty fast, since it is optimized away and probably roughly close to a pointer comparison. Also, M is likely not very big and no more than N/2. Also, on average, the match will be found before we check all N items, and each removal decreases N by one.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:3902]: The `M` that I am using is not the number of partial members. It is the number of partial members that we are going to remove, which is no more than the number of partial members divided by two.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs [hunk 4]
```diff
@@ -74,7 +75,7 @@ private enum Flags : ushort
 
 #nullable enable
         private SynthesizedBackingFieldSymbol? _lazyDeclaredBackingField;
-        private SynthesizedBackingFieldSymbol? _lazyMergedBackingField;
+        private StrongBox<SynthesizedBackingFieldSymbol?>? _lazyMergedBackingField;
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs:78]: I didn't understand what is accomplished by using a StrongBox here, could you please explain?

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs [hunk 5]
```diff
@@ -2948,7 +2957,7 @@ public void Free()
 
         protected sealed class DeclaredMembersAndInitializers
         {
-            public readonly ImmutableArray<Symbol> NonTypeMembers;
+            public readonly ImmutableArray<Symbol> NonTypeMembersWithPartialImplementations;
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:2960]: It might be good to also rename the corresponding field of `DeclaredMembersAndInitializersBuilder`.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs (hunk 4 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs:78]: > I didn't understand what is accomplished by using a StrongBox here, could you please explain?

`null` is a valid value for the backing field. Therefore, `null` couldn't be used as a sentinel value (a value representing a not initialized state). But it was used this way in ```BackingField.get```. Potentially causing us to get into the `if` over and over again. Also there was no guarantee that we wouldn't get into the `if` for a partial case. StrongBox allows us to know for sure whether the value is initialized, `null` - not initialized, `not null` initialized.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs:78]: Thank you

**Review by RikkiGibson — APPROVED** [review]
