### PR TITLE
Fixed crashes when there are multiple type forwarders for the same type

### LINKED ISSUE #16484: csc crashes when referencing module that forwards same type to multiple assemblies
To reproduce:

1) Save the following il into `forwarder.il`:
```assembly
.assembly extern Destination1
{                 
}

.assembly extern Destination2
{                 
}

.class extern forwarder Destination.TestClass
{
	.assembly extern Destination1
}

.class extern forwarder Destination.TestClass
{
	.assembly extern Destination2
}
```
2) Compile this into a module using `ilasm` to produce `forwarder.dll`.
3) Compile the following C# code referencing `forwarder.dll`:

```csharp
namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
        }
    }
}
```

**Native compiler behaviour:**
`error CS1577: Assembly generation failed -- Type 'Destination.TestClass' is forwarded to multiple assemblies: 'Destination2' and 'Destination1'`

**Roslyn compiler behaviour:**
Crashes with the following exception:
```
Unhandled Exception: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.CodeAnalysis.PEModule.EnsureForwardTypeToAssemblyMap()
   at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEModuleSymbol.<GetForwardedTypes>d__77.MoveNext()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.LoadAndValidateNetModuleAttributes(CustomAttributesBag`1& lazyNetModuleAttributesBag)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.GetNetModuleDecodedWellKnownAttributeData()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.GetWellKnownAttributeDataStringField(Func`2 fieldGetter, String missingValue)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.ComputeStrongNameKeys()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.get_StrongNameKeys()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.ValidateAttributeSemantics(DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSourceDeclarationDiagnostics(SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Func`4 locationFilterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDeclarationDiagnostics(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
   at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter)
   at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.Run(IEnumerable`1 arguments, IEnumerable`1 extraArguments, RequestLanguage language, CompileFunc compileFunc, IAnalyzerAssemblyLoader analyzerAssemblyLoader)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args, String[] extraArgs)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
```

@AlekseyTs comment: We should only report the error if the user is referencing the type, and we should ignore the multiple forwards and resume normally otherwise.

@jaredpar copy of VSO 223973.

### PR DESCRIPTION
**Pull request by OmarTawfik**
Fixes #16484

### CODE REVIEW

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-compiler

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-compiler this is ready for review.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs [hunk 1]
```diff
@@ -2583,9 +2583,17 @@ internal override NamedTypeSymbol TryLookupForwardedMetadataTypeWithCycleDetecti
...
+                    var forwardedToAssemblies = peModuleSymbol.GetAssembliesForForwardedType(ref emittedName);
+
+                    if (!forwardedToAssemblies.IsDefaultOrEmpty)
                     {
+                        if (forwardedToAssemblies.Length > 1)
+                        {
+                            return new MultipleForwardedTypeSymbol(emittedName, forwardedToAssemblies[0], forwardedToAssemblies[1]);
+                        }
+
+                        AssemblySymbol forwardedToAssembly = forwardedToAssemblies.First();
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs]: >First [](start = 83, length = 5)

Nit: Single?

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs [hunk 2]
```diff
@@ -1929,12 +1929,19 @@ private CSDiagnosticInfo NotFound(SyntaxNode where, string simpleName, int arity
...
+                        if (encounteredForwardingError.Code == (int)ErrorCode.ERR_CycleInTypeForwarder)
+                        {
+                            Debug.Assert((object)forwardedToAssembly != null, "How did we find a cycle if there was no forwarding?");
+                            diagnostics.Add(ErrorCode.ERR_CycleInTypeForwarder, location, fullName, forwardedToAssembly.Name);
+                        }
+                        else if (encounteredForwardingError.Code == (int)ErrorCode.ERR_TypeForwardedToMultipleAssemblies)
+                        {
+                            return diagnostics.Add(ErrorCode.ERR_TypeForwardedToMultipleAssemblies, location, encounteredForwardingError.Arguments);
+                        }
                     }
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs]: This block (from line 1932 to 1945) is duplicated below. Consider factoring out?

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs [hunk 3]
```diff
@@ -1895,7 +1895,7 @@ private CSDiagnosticInfo NotFound(SyntaxNode where, string simpleName, int arity
             // as a type forwarder.  We'll look for type forwarders in the containing and
             // referenced assemblies and report more specific diagnostics if they are found.
             AssemblySymbol forwardedToAssembly;
-            bool encounteredForwardingCycle;
+            DiagnosticInfo encounteredForwardingError;
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs]: This local feels suspicious.  It's declared at an outer scope but used as a distinct local in this scope and an inner scope.

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs [hunk 4]
```diff
@@ -1929,12 +1929,19 @@ private CSDiagnosticInfo NotFound(SyntaxNode where, string simpleName, int arity
                         fullName = qualifierOpt.ToDisplayString(SymbolDisplayFormat.QualifiedNameOnlyFormat) + "." + fullName;
                     }
 
-                    forwardedToAssembly = GetForwardedToAssembly(fullName, arity, out encounteredForwardingCycle);
+                    forwardedToAssembly = GetForwardedToAssembly(fullName, arity, out encounteredForwardingError);
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs]: This is where it feels like there should be a different local.

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEAssemblySymbol.cs [hunk 5]
```diff
@@ -128,32 +128,40 @@ public override ImmutableArray<CSharpAttributeData> GetAttributes()
...
+            var forwardedToAssemblies = LookupAssembliesForForwardedMetadataType(ref emittedName);
+
+            if (!forwardedToAssemblies.IsDefaultOrEmpty)
             {
+                if (forwardedToAssemblies.Length > 1)
+                {
+                    return new MultipleForwardedTypeSymbol(emittedName, forwardedToAssemblies[0], forwardedToAssemblies[1]);
+                }
+
+                AssemblySymbol forwardedToAssembly = forwardedToAssemblies.First();
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEAssemblySymbol.cs]: Nit: Single too

File: src/Compilers/CSharp/Portable/Errors/ErrorCode.cs [hunk 6]
```diff
@@ -740,7 +740,7 @@ internal enum ErrorCode
         WRN_BadXMLRef = 1574,
         ERR_BadStackAllocExpr = 1575,
         ERR_InvalidLineNumber = 1576,
-        //ERR_ALinkFailed = 1577,               No alink usage in Roslyn
+        ERR_TypeForwardedToMultipleAssemblies = 1577,
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Errors/ErrorCode.cs]: Consider a new error number.  Existing hits for CS1577.

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs [hunk 7]
```diff
@@ -19412,6 +19412,142 @@ public void AbstractInSubmission()
...
+{
+	.assembly extern Destination2
+}";
+            var forwardingCompilation = CreateCompilationWithCustomILSource(forwardingCode, forwardingIL);
+
+            forwardingCompilation.VerifyDiagnostics(
+                // (8,29): error CS1577: Type 'Destination.TestClass' is forwarded to multiple assemblies: 'Destination1' and 'Destination2'
+                //             new Destination.TestClass();
+                Diagnostic(ErrorCode.ERR_TypeForwardedToMultipleAssemblies, "TestClass").WithArguments("Destination.TestClass", "Destination1", "Destination2").WithLocation(8, 29));
+        }
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs]: Maybe add a test with more than 2 duplicate type forwards (in that case we still expect only one pair of duplicates to be reported).

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs (hunk 2 above)
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs]: These are the only two callers to `GetForwardedToAssembly`. Could the `DiagnosticBag` and `location` be passed into that method and create the diagnostic there?

File: src/Compilers/Core/Portable/MetadataReader/PEModule.cs [hunk 8]
```diff
@@ -2865,31 +2865,49 @@ private void EnsureForwardTypeToAssemblyMap()
...
                         if (!exportedType.IsForwarder)
                         {
                             continue;
                         }
 
+                        AssemblyReferenceHandle newReference = (AssemblyReferenceHandle)exportedType.Implementation;
+
+                        if (newReference.IsNil)
+                        {
+                            continue;
```
Comment (jcouv) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: Previously, when `(AssemblyReferenceHandle)exportedType.Implementation` was `Nil`, it would still be added to the map. Does this make a difference?

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs [hunk 9]
```diff
@@ -641,32 +642,48 @@ internal NamedTypeSymbol LookupTopLevelMetadataType(ref MetadataTypeName emitted
...
+            var assemblies = ArrayBuilder<AssemblySymbol>.GetInstance();
+
+            if (assemblyRefs != null)
+            {
+                foreach (var reference in assemblyRefs)
+                {
+                    var assembly = this.GetReferencedAssemblySymbol(reference);
+                    if (assembly != null)
+                    {
+                        assemblies.Add(assembly);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs]: If we had a `Nil` assembly ref here before, we would not call `GetReferencedAssemblySymbol` but now it seems we do.

File: src/Compilers/Core/Portable/MetadataReader/PEModule.cs (hunk 8 above)
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: I am also curious why do we need this special case.

File: src/Compilers/Core/Portable/MetadataReader/PEModule.cs [hunk 10]
```diff
@@ -2865,31 +2865,49 @@ private void EnsureForwardTypeToAssemblyMap()
...
+                        }
+
                         string name = MetadataReader.GetString(exportedType.Name);
-                        StringHandle ns = exportedType.Namespace;
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: Is there a reason for removing this local?

File: src/Compilers/VisualBasic/Portable/Binding/Binder_Symbols.vb [hunk 11]
```diff
@@ -413,28 +414,36 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
+                    If Not encounteredForwardingError Is Nothing Then
+                        If encounteredForwardingError.Code = ERRID.ERR_TypeFwdCycle2 Then
+                            Debug.Assert(forwardedToAssembly IsNot Nothing, "How did we find a cycle if there is no forwarding?")
+                            Binder.ReportDiagnostic(diagBag, typeSyntax, ERRID.ERR_TypeFwdCycle2, diagName, forwardedToAssembly)
+                        ElseIf encounteredForwardingError.Code = ERRID.ERR_TypeForwardedToMultipleAssemblies Then
+                            Binder.ReportDiagnostic(diagBag, typeSyntax, ERRID.ERR_TypeForwardedToMultipleAssemblies, encounteredForwardingError.Arguments)
+                            Return encounteredForwardingError
+                        End If
+                    End If
+                End If
```
Comment (jcouv) [inline src/Compilers/VisualBasic/Portable/Binding/Binder_Symbols.vb]: Nit: 2 empty lines below

File: src/Compilers/VisualBasic/Portable/Binding/Binder_Symbols.vb [hunk 12]
```diff
@@ -413,28 +414,36 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
                 End If
 
                 If Not reportedAnError Then
-                    Binder.ReportDiagnostic(diagBag, typeSyntax, diagInfo)
-
-                    If encounteredForwardingCycle Then
-                        Debug.Assert(forwardedToAssembly IsNot Nothing, "How did we find a cycle if there is no forwarding?")
-                        Binder.ReportDiagnostic(diagBag, typeSyntax, ERRID.ERR_TypeFwdCycle2, diagName, forwardedToAssembly)
-                    End If
+                    binder.ReportDiagnostic(diagBag, typeSyntax, diagInfo)
```
Comment (jcouv) [inline src/Compilers/VisualBasic/Portable/Binding/Binder_Symbols.vb]: Is the change to lower-case `binder` intentional? VB casing confuses me :-(

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs [hunk 13]
```diff
@@ -1929,12 +1929,19 @@ private CSDiagnosticInfo NotFound(SyntaxNode where, string simpleName, int arity
...
 
-                    if (encounteredForwardingCycle)
+                    if (encounteredForwardingError != null)
                     {
-                        Debug.Assert((object)forwardedToAssembly != null, "How did we find a cycle if there was no forwarding?");
-                        diagnostics.Add(ErrorCode.ERR_CycleInTypeForwarder, location, fullName, forwardedToAssembly.Name);
+                        if (encounteredForwardingError.Code == (int)ErrorCode.ERR_CycleInTypeForwarder)
+                        {
+                            Debug.Assert((object)forwardedToAssembly != null, "How did we find a cycle if there was no forwarding?");
+                            diagnostics.Add(ErrorCode.ERR_CycleInTypeForwarder, location, fullName, forwardedToAssembly.Name);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs]: Why are we creating new diagnostic infos instead of using the ones we already have. If the ones we have a re missing something, perhaps we shouldn't be creating them in GetForwardedToAssembly, but should simply return the error number back.

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs [hunk 14]
```diff
@@ -1929,12 +1929,19 @@ private CSDiagnosticInfo NotFound(SyntaxNode where, string simpleName, int arity
...
+                        }
+                        else if (encounteredForwardingError.Code == (int)ErrorCode.ERR_TypeForwardedToMultipleAssemblies)
+                        {
+                            return diagnostics.Add(ErrorCode.ERR_TypeForwardedToMultipleAssemblies, location, encounteredForwardingError.Arguments);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs]: Same question. Why are we creating new diagnostic infos instead of using the ones we already have?

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs [hunk 15]
```diff
@@ -1974,12 +1981,19 @@ private CSDiagnosticInfo NotFound(SyntaxNode where, string simpleName, int arity
...
 
-            if (encounteredForwardingCycle)
+            if (encounteredForwardingError != null)
             {
-                Debug.Assert((object)forwardedToAssembly != null, "How did we find a cycle if there was no forwarding?");
-                diagnostics.Add(ErrorCode.ERR_CycleInTypeForwarder, location, fullName, forwardedToAssembly.Name);
+                if (encounteredForwardingError.Code == (int)ErrorCode.ERR_CycleInTypeForwarder)
+                {
+                    Debug.Assert((object)forwardedToAssembly != null, "How did we find a cycle if there was no forwarding?");
+                    diagnostics.Add(ErrorCode.ERR_CycleInTypeForwarder, location, fullName, forwardedToAssembly.Name);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs]: Same here.

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs [hunk 16]
```diff
@@ -1974,12 +1981,19 @@ private CSDiagnosticInfo NotFound(SyntaxNode where, string simpleName, int arity
...
+                }
+                else if (encounteredForwardingError.Code == (int)ErrorCode.ERR_TypeForwardedToMultipleAssemblies)
+                {
+                    return diagnostics.Add(ErrorCode.ERR_TypeForwardedToMultipleAssemblies, location, encounteredForwardingError.Arguments);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs]: Same here.

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs [hunk 17]
```diff
@@ -19412,6 +19412,142 @@ public void AbstractInSubmission()
...
+{
+	.assembly extern Destination1
+}
+.class extern forwarder Destination.TestClass
+{
+	.assembly extern Destination2
+}";
+            var forwardingCompilation = CreateCompilationWithCustomILSource(string.Empty, forwardingIL);
+
+            forwardingCompilation.VerifyDiagnostics();
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs]: There are no type references to the forwarding DLL. Consider adding a reference to a non-forwarded type so it's clear the assembly wasn't skipped entirely.

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs [hunk 18]
```diff
@@ -1929,12 +1929,19 @@ private CSDiagnosticInfo NotFound(SyntaxNode where, string simpleName, int arity
...
+                    if (encounteredForwardingError != null)
                     {
-                        Debug.Assert((object)forwardedToAssembly != null, "How did we find a cycle if there was no forwarding?");
-                        diagnostics.Add(ErrorCode.ERR_CycleInTypeForwarder, location, fullName, forwardedToAssembly.Name);
+                        if (encounteredForwardingError.Code == (int)ErrorCode.ERR_CycleInTypeForwarder)
+                        {
+                            Debug.Assert((object)forwardedToAssembly != null, "How did we find a cycle if there was no forwarding?");
+                            diagnostics.Add(ErrorCode.ERR_CycleInTypeForwarder, location, fullName, forwardedToAssembly.Name);
+                        }
+                        else if (encounteredForwardingError.Code == (int)ErrorCode.ERR_TypeForwardedToMultipleAssemblies)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs]: Perhaps we should throw if we get errors other than the ones we handle.

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs [hunk 19]
```diff
@@ -1974,12 +1981,19 @@ private CSDiagnosticInfo NotFound(SyntaxNode where, string simpleName, int arity
...
+            if (encounteredForwardingError != null)
             {
-                Debug.Assert((object)forwardedToAssembly != null, "How did we find a cycle if there was no forwarding?");
-                diagnostics.Add(ErrorCode.ERR_CycleInTypeForwarder, location, fullName, forwardedToAssembly.Name);
+                if (encounteredForwardingError.Code == (int)ErrorCode.ERR_CycleInTypeForwarder)
+                {
+                    Debug.Assert((object)forwardedToAssembly != null, "How did we find a cycle if there was no forwarding?");
+                    diagnostics.Add(ErrorCode.ERR_CycleInTypeForwarder, location, fullName, forwardedToAssembly.Name);
+                }
+                else if (encounteredForwardingError.Code == (int)ErrorCode.ERR_TypeForwardedToMultipleAssemblies)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs]: Perhaps we should throw if we get errors other than the ones we handle.

File: src/Compilers/CSharp/Portable/Errors/ErrorCode.cs (hunk 6 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Errors/ErrorCode.cs]: I don't think we should reuse this error code. It looks like native compiler was using for all possible ALink errors.

File: src/Compilers/Core/Portable/MetadataReader/PEModule.cs [hunk 20]
```diff
@@ -2865,31 +2865,49 @@ private void EnsureForwardTypeToAssemblyMap()
...
+                        if (typesToAssemblyMap.TryGetValue(name, out references))
+                        {
+                            references.Add(newReference);
+                        }
+                        else
+                        {
+                            references = new HashSet<AssemblyReferenceHandle>();
+                            references.Add(newReference);
+                            typesToAssemblyMap.Add(name, references);
+                        }
```
Comment (cston) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: Consider moving `references.Add(newReference);` after the `if`.

File: src/Compilers/CSharp/Portable/Symbols/MultipleForwardedTypeSymbol.cs [hunk 21]
```diff
@@ -0,0 +1,36 @@
+﻿// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
+
+namespace Microsoft.CodeAnalysis.CSharp.Symbols
+{
+    internal sealed class MultipleForwardedTypeSymbol : ErrorTypeSymbol
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/MultipleForwardedTypeSymbol.cs]: Do we have to add this type? Can we use MissingMetadataTypeSymbol.TopLevelWithCustomErrorInfo instead?

File: src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEAssemblySymbol.vb [hunk 22]
```diff
@@ -141,32 +141,39 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols.Metadata.PE
...
         Friend Overrides Function TryLookupForwardedMetadataTypeWithCycleDetection(ByRef emittedName As MetadataTypeName, visitedAssemblies As ConsList(Of AssemblySymbol), ignoreCase As Boolean) As NamedTypeSymbol
             ' Check if it is a forwarded type.
             Dim matchedName As String = Nothing
-            Dim forwardedToAssembly = LookupAssemblyForForwardedMetadataType(emittedName, ignoreCase, matchedName)
-            ' Don't bother to check the forwarded-to assembly if we've already seen it.
-            If forwardedToAssembly IsNot Nothing Then
+            Dim forwardedToAssemblies = LookupAssembliesForForwardedMetadataType(emittedName, ignoreCase, matchedName)
+
+            If (Not forwardedToAssemblies.IsDefaultOrEmpty) Then
+                If (forwardedToAssemblies.Length > 1) Then
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEAssemblySymbol.vb]: Parentheses are not needed around `If` expression.

File: src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEModuleSymbol.vb [hunk 23]
```diff
@@ -423,30 +423,42 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols.Metadata.PE
...
-        Friend Function GetAssemblyForForwardedType(ByRef fullName As MetadataTypeName, ignoreCase As Boolean, <Out> ByRef matchedName As String) As AssemblySymbol
-            Dim assemblyRef As AssemblyReferenceHandle = Me.Module.GetAssemblyForForwardedType(fullName.FullName, ignoreCase, matchedName)
-            Return If(assemblyRef.IsNil, Nothing, GetReferencedAssemblySymbol(assemblyRef))
+        Friend Function GetAssembliesForForwardedType(ByRef fullName As MetadataTypeName, ignoreCase As Boolean, <Out> ByRef matchedName As String) As ImmutableArray(Of AssemblySymbol)
+            Dim assemblyRefs As IEnumerable(Of AssemblyReferenceHandle) = Me.Module.GetAssemblyRefsForForwardedType(fullName.FullName, ignoreCase, matchedName)
+            Dim assemblies = ArrayBuilder(Of AssemblySymbol).GetInstance()
+
+            If Not assemblyRefs Is Nothing Then
+                For Each reference As AssemblyReferenceHandle In assemblyRefs
+                    Dim Assembly = GetReferencedAssemblySymbol(reference)
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEModuleSymbol.vb]: Lowercase first letter for local.

File: src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEModuleSymbol.vb [hunk 24]
```diff
@@ -423,30 +423,42 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols.Metadata.PE
...
+                    If Not Assembly Is Nothing Then
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEModuleSymbol.vb]: Minor point: This is typically `IsNot Nothing`.

File: src/Compilers/VisualBasic/Portable/Symbols/Source/SourceAssemblySymbol.vb [hunk 25]
```diff
@@ -1693,9 +1693,15 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols
                 ' Similar to attributes, type forwarders from the second added module should override type forwarders from the first added module, etc. 
                 For i As Integer = _modules.Length - 1 To 1 Step -1
                     Dim peModuleSymbol = DirectCast(_modules(i), PEModuleSymbol)
+                    Dim forwardedToAssemblies = peModuleSymbol.GetAssembliesForForwardedType(emittedName, ignoreCase, matchedName)
+
+                    If (Not forwardedToAssemblies.IsDefaultOrEmpty) Then
+                        If (forwardedToAssemblies.Length > 1) Then
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceAssemblySymbol.vb]: Parentheses are not needed.

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEAssemblySymbol.cs [hunk 26]
```diff
@@ -128,32 +128,40 @@ public override ImmutableArray<CSharpAttributeData> GetAttributes()
...
             // Check if it is a forwarded type.
-            var forwardedToAssembly = LookupAssemblyForForwardedMetadataType(ref emittedName);
-            if ((object)forwardedToAssembly != null)
+            var forwardedToAssemblies = LookupAssembliesForForwardedMetadataType(ref emittedName);
+
+            if (!forwardedToAssemblies.IsDefaultOrEmpty)
             {
+                if (forwardedToAssemblies.Length > 1)
+                {
+                    return new MultipleForwardedTypeSymbol(emittedName, forwardedToAssemblies[0], forwardedToAssemblies[1]);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEAssemblySymbol.cs]: It looks like we should be able to reuse MissingMetadataTypeSymbol.TopLevelWithCustomErrorInfo type, see how CreateCycleInTypeForwarderErrorTypeSymbol does that.

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs [hunk 27]
```diff
@@ -641,32 +642,48 @@ internal NamedTypeSymbol LookupTopLevelMetadataType(ref MetadataTypeName emitted
...
-            return assemblyRef.IsNil ? null : this.GetReferencedAssemblySymbol(assemblyRef);
+            HashSet<AssemblyReferenceHandle> assemblyRefs = Module.GetAssemblyRefsForForwardedType(fullName.FullName, ignoreCase: false, matchedName: out matchedName);
+            var assemblies = ArrayBuilder<AssemblySymbol>.GetInstance();
+
+            if (assemblyRefs != null)
+            {
+                foreach (var reference in assemblyRefs)
+                {
+                    var assembly = this.GetReferencedAssemblySymbol(reference);
+                    if (assembly != null)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs]: Do we ever expect to get null from GetReferencedAssemblySymbol here. Under what conditions? Why is it Ok to simply ignore such entry?

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs [hunk 28]
```diff
@@ -641,32 +642,48 @@ internal NamedTypeSymbol LookupTopLevelMetadataType(ref MetadataTypeName emitted
...
         /// </summary>
         /// <param name="fullName">Type to look up.</param>
-        /// <returns>Assembly symbol or null.</returns>
+        /// <returns>An <see cref="ImmutableArray"/> of the forwarded to assemblies.</returns>
         /// <remarks>
-        /// The returned assembly may also forward the type.
+        /// The returned assemblies may also forward the type.
         /// </remarks>
-        internal AssemblySymbol GetAssemblyForForwardedType(ref MetadataTypeName fullName)
+        internal ImmutableArray<AssemblySymbol> GetAssembliesForForwardedType(ref MetadataTypeName fullName)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs]: It looks like we are never interested in more than two assembly symbols. Perhaps we should simply return conflicting symbol as a new out parameter and avoid allocating arrays. Alternatively we could return a tuple with the second element null when there is no ambiguity.

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs [hunk 29]
```diff
@@ -641,32 +642,48 @@ internal NamedTypeSymbol LookupTopLevelMetadataType(ref MetadataTypeName emitted
...
         }
 
         internal IEnumerable<NamedTypeSymbol> GetForwardedTypes()
         {
-            foreach (KeyValuePair<string, AssemblyReferenceHandle> forwarder in Module.GetForwardedTypes())
+            foreach (KeyValuePair<string, HashSet<AssemblyReferenceHandle>> forwarder in Module.GetForwardedTypes())
             {
-                var assemblySymbol = this.GetReferencedAssemblySymbol(forwarder.Value);
-                if ((object)assemblySymbol == null)
+                foreach (AssemblyReferenceHandle assemblyRef in forwarder.Value)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs]: It feels suspicious that we are ignoring the ambiguity case in this function. Given that we cannot rely on any deterministic order in this loop, the order of ambiguous types is not deterministic and consumers (like LoadAndValidateNetModuleAttributes) could be spreading the non-determinism down the pipeline.

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs (hunk 17 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs]: At the very least we should emit and verify the produced assembly. It would be good to have it print something so that we could also verify that we can run the code.

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs [hunk 30]
```diff
@@ -19412,6 +19412,142 @@ public void AbstractInSubmission()
...
+            var forwardedToReference = CreateCompilationWithMscorlib(forwardedToCode, assemblyName: "Destination").EmitToImageReference();
+
+            var forwardingCode = @"
+namespace ForwardingNamespace
+{
+    public class Program
+    {
+        public static void Main()
+        {
+            System.Console.WriteLine(Destination.TestClass.Value);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs]: I believe this code doesn't test lookup through forwarders.

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs [hunk 31]
```diff
@@ -19412,6 +19412,142 @@ public void AbstractInSubmission()
...
+            var forwardedToReference2 = forwardedToCompilation2.EmitToImageReference();
+
+            var forwardingCode = @"
+namespace ForwardingNamespace
+{
+    public class Program
+    {
+        public static void Main()
+        {
+            new Destination.TestClass();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs]: I believe this code doesn't test lookup through forwarders.

File: src/Compilers/Core/Portable/MetadataReader/PEModule.cs [hunk 32]
```diff
@@ -2822,7 +2822,7 @@ private ConstantValue GetConstantValueOrThrow(ConstantHandle handle)
             return ConstantValue.Bad;
         }
 
-        internal AssemblyReferenceHandle GetAssemblyForForwardedType(string fullName, bool ignoreCase, out string matchedName)
+        internal HashSet<AssemblyReferenceHandle> GetAssemblyRefsForForwardedType(string fullName, bool ignoreCase, out string matchedName)
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: Perhaps we should return a tuple instead of a HasSet, we probably are never interested in more than two references.

File: src/Compilers/Core/Portable/MetadataReader/PEModule.cs [hunk 33]
```diff
@@ -38,7 +38,7 @@ internal sealed class PEModule : IDisposable
         private MetadataReader _lazyMetadataReader;
 
         private ImmutableArray<AssemblyIdentity> _lazyAssemblyReferences;
-        private Dictionary<string, AssemblyReferenceHandle> _lazyForwardedTypesToAssemblyMap;
+        private Dictionary<string, HashSet<AssemblyReferenceHandle>> _lazyForwardedTypesToAssemblyMap;
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: Perhaps we should store a tuple instead of a HashSet, we probably are never interested in more than two references.

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs (hunk 13 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs]: I understand now why we are doing this for ERR_CycleInTypeForwarder.

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs (hunk 15 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs]: I understand now why we are doing this for ERR_CycleInTypeForwarder.

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs (hunk 17 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs]: That's the purpose of the test. The following test does the exact opposite. Am I missing something?

---
In reply to: [97432370](https://github.com/dotnet/roslyn/pull/16634#discussion_r97432370) [](ancestors = 97432370)

Comment (OmarTawfik) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs]: Discussed offline. Should add a reference to a valid type to ensure that the binary is loaded correctly.

---
In reply to: [97449614](https://github.com/dotnet/roslyn/pull/16634#discussion_r97449614) [](ancestors = 97449614,97432370)

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs (hunk 14 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs]: It looks like we shouldn't return, but should continue instead.

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs (hunk 16 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs]: It looks like this code path is not covered by any test.

File: src/Compilers/Core/Portable/MetadataReader/PEModule.cs (hunk 8 above)
Comment (OmarTawfik) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: So we have two options in case of invalid metadata, either discard it, or keep the null references. I chose to discard invalid values for now. If we have a repro for invalid IL that we need to handle in a different way, I'll open another bug for that. But for now, I chose to discard it.

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs (hunk 27 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs]: So we have two options in case of invalid metadata, either discard it, or keep the null references. I chose to discard invalid values for now. If we have a repro for invalid IL that we need to handle in a different way, I'll open another bug for that. But for now, I chose to discard it.

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs [hunk 34]
```diff
@@ -19412,6 +19412,142 @@ public void AbstractInSubmission()
...
+}
+.class extern forwarder Destination.TestClass
+{
+	.assembly extern Destination2
+}";
+            var forwardingCompilation = CreateCompilationWithCustomILSource(forwardingCode, forwardingIL, new MetadataReference[] { forwardedToReference1, forwardedToReference2 });
+
+            forwardingCompilation.VerifyDiagnostics();
+        }
     }
```
Comment (OmarTawfik) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs]: Note to self: In Binder.NotFound(), there are two paths that the check can go. With or without type qualifiers. Add another test to ensure that both paths are tested.

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEAssemblySymbol.cs [hunk 35]
```diff
@@ -128,41 +128,53 @@ public override ImmutableArray<CSharpAttributeData> GetAttributes()
...
-            return this.PrimaryModule.GetAssemblyForForwardedType(ref emittedName);
+            return this.PrimaryModule.GetAssembliesForForwardedType(ref emittedName);
         }
 
         internal override NamedTypeSymbol TryLookupForwardedMetadataTypeWithCycleDetection(ref MetadataTypeName emittedName, ConsList<AssemblySymbol> visitedAssemblies)
         {
             // Check if it is a forwarded type.
-            var forwardedToAssembly = LookupAssemblyForForwardedMetadataType(ref emittedName);
-            if ((object)forwardedToAssembly != null)
+            (AssemblySymbol FirstSymbol, AssemblySymbol SecondSymbol) forwardedToAssemblies = LookupAssembliesForForwardedMetadataType(ref emittedName);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEAssemblySymbol.cs]: Consider deconstructing: `var (firstSymbol, secondSymbol) = LookupAssemblies...;`

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs [hunk 36]
```diff
@@ -641,47 +641,55 @@ internal NamedTypeSymbol LookupTopLevelMetadataType(ref MetadataTypeName emitted
...
-        /// The returned assembly may also forward the type.
+        /// The returned assemblies may also forward the type.
         /// </remarks>
-        internal AssemblySymbol GetAssemblyForForwardedType(ref MetadataTypeName fullName)
+        internal (AssemblySymbol FirstSymbol, AssemblySymbol SecondSymbol) GetAssembliesForForwardedType(ref MetadataTypeName fullName)
         {
             string matchedName;
-            AssemblyReferenceHandle assemblyRef = Module.GetAssemblyForForwardedType(fullName.FullName, ignoreCase: false, matchedName: out matchedName);
-            return assemblyRef.IsNil ? null : this.GetReferencedAssemblySymbol(assemblyRef);
+            (int FirstIndex, int SecondIndex) indices = this.Module.GetAssemblyRefsForForwardedType(fullName.FullName, ignoreCase: false, matchedName: out matchedName);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs]: Consider deconstructing.

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs [hunk 37]
```diff
@@ -641,47 +641,55 @@ internal NamedTypeSymbol LookupTopLevelMetadataType(ref MetadataTypeName emitted
...
+                if ((object)firstSymbol == null)
+                {
+                    continue;
+                }
+
+                if (forwarder.Value.SecondIndex >= 0)
+                {
+                    var secondSymbol = this.GetReferencedAssemblySymbol(forwarder.Value.SecondIndex);
+
+                    if ((object)secondSymbol != null)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs]: Are we testing the case where there are multiple forwards but the second referenced assembly is missing? Shouldn't we `continue` in that case rather than `yield return firstSymbol;`, to match the case when the first referenced assembly is missing?

Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs]: Good point. I'll do that change and make sure that it is covered in tests.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs [hunk 38]
```diff
@@ -2583,18 +2583,30 @@ internal override NamedTypeSymbol TryLookupForwardedMetadataTypeWithCycleDetecti
...
+                    if ((object)firstSymbol != null)
                     {
+                        if ((object)secondSymbol != null)
+                        {
+                            var forwardingErrorInfo = new DiagnosticInfo(
+                                MessageProvider.Instance,
+                                (int)ErrorCode.ERR_TypeForwardedToMultipleAssemblies,
+                                emittedName.FullName,
+                                firstSymbol.Name,
+                                secondSymbol.Name);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs]: Consider passing the symbols as arguments rather than just the names, so the diagnostic contains fully-qualified names.

File: src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEAssemblySymbol.vb [hunk 39]
```diff
@@ -142,32 +142,43 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols.Metadata.PE
...
             ' Check if it is a forwarded type.
             Dim matchedName As String = Nothing
-            Dim forwardedToAssembly = LookupAssemblyForForwardedMetadataType(emittedName, ignoreCase, matchedName)
-            ' Don't bother to check the forwarded-to assembly if we've already seen it.
-            If forwardedToAssembly IsNot Nothing Then
-                If visitedAssemblies IsNot Nothing AndAlso visitedAssemblies.Contains(forwardedToAssembly) Then
+            Dim forwardedToAssemblies = LookupAssembliesForForwardedMetadataType(emittedName, ignoreCase, matchedName)
+
+            If DirectCast(forwardedToAssemblies.FirstSymbol, Object) IsNot Nothing
+                If DirectCast(forwardedToAssemblies.SecondSymbol, Object) IsNot Nothing
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEAssemblySymbol.vb]: `If symbol IsNot Nothing Then`

Comment (cston) [inline src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEAssemblySymbol.vb]: The cast to `Object` is not needed - `IsNot` uses `ReferenceEquals`.

File: src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEAssemblySymbol.vb [hunk 40]
```diff
@@ -142,32 +142,43 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols.Metadata.PE
...
+                    Dim forwardingErrorInfo = New DiagnosticInfo(
+                        MessageProvider.Instance,
+                        ERRID.ERR_TypeForwardedToMultipleAssemblies,
+                        emittedName.FullName,
+                        forwardedToAssemblies.FirstSymbol.Name,
+                        forwardedToAssemblies.SecondSymbol.Name)
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEAssemblySymbol.vb]: Consider passing symbols rather than names.

File: src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEModuleSymbol.vb [hunk 41]
```diff
@@ -423,30 +423,44 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols.Metadata.PE
...
+            For Each forwarder As KeyValuePair(Of String, (FirstIndex As Integer, SecondIndex As Integer)) In Me.Module.GetForwardedTypes()
+                If forwarder.Value.FirstIndex < 0 Then
                     Continue For
                 End If
 
                 Dim name = MetadataTypeName.FromFullName(forwarder.Key)
-                Yield assembly.LookupTopLevelMetadataType(name, digThroughForwardedTypes:=True)
+
+                Dim firstSymbol = GetReferencedAssemblySymbol(forwarder.Value.FirstIndex)
+                Debug.Assert(DirectCast(firstSymbol, Object) IsNot Nothing, "Invalid indexes (out of bound) are discarded during reading metadata in PEModule.EnsureForwardTypeToAssemblyMap()")
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEModuleSymbol.vb]: Cast is not needed, here and in other assert below.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs [hunk 42]
```diff
@@ -2583,18 +2583,30 @@ internal override NamedTypeSymbol TryLookupForwardedMetadataTypeWithCycleDetecti
...
+                            return new MissingMetadataTypeSymbol.TopLevelWithCustomErrorInfo(SourceModule, ref emittedName, forwardingErrorInfo);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs]: Consider extracting a helper method to create the `MissingMetadataTypeSymbol` and associated diagnostic, for use here and in `PEModuleSymbol`.

File: src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEModuleSymbol.vb [hunk 43]
```diff
@@ -423,30 +423,44 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols.Metadata.PE
...
+
+                If forwarder.Value.SecondIndex >= 0 Then
+                    Dim secondSymbol = GetReferencedAssemblySymbol(forwarder.Value.SecondIndex)
+                    Debug.Assert(DirectCast(secondSymbol, Object) IsNot Nothing, "Invalid indexes (out of bound) are discarded during reading metadata in PEModule.EnsureForwardTypeToAssemblyMap()")
+
+                    Dim forwardingErrorInfo = New DiagnosticInfo(MessageProvider.Instance, ERRID.ERR_TypeForwardedToMultipleAssemblies, forwarder.Key, firstSymbol.Name, secondSymbol.Name)
+                    Yield New MissingMetadataTypeSymbol.TopLevelWithCustomErrorInfo(Me, name, forwardingErrorInfo)
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEModuleSymbol.vb]: Consider extracting a helper method to construct the `MissingMetadataTypeSymbol`, for use here and in `PEAssemblySymbol` and `SourceAssemblySymbol`.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs (hunk 42 above)
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs]: ... and `PEAssemblySymbol`.

File: src/Compilers/Core/Portable/MetadataReader/PEModule.cs [hunk 44]
```diff
@@ -2878,6 +2885,27 @@ private void EnsureForwardTypeToAssemblyMap()
...
+                        try
+                        {
+                            referencedAssemblyIndex = this.GetAssemblyReferenceIndexOrThrow(refHandle);
+                        }
+                        catch (BadImageFormatException)
+                        {
+                            continue;
+                        }
+
+                        if (referencedAssemblyIndex >= this.ReferencedAssemblies.Length)
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: > if (referencedAssemblyIndex >= this.ReferencedAssemblies.Length) [](start = 23, length = 65)

Consider also checking for a negative value.

File: src/Compilers/Core/Portable/MetadataReader/PEModule.cs [hunk 45]
```diff
@@ -2889,13 +2917,27 @@ private void EnsureForwardTypeToAssemblyMap()
                             }
                         }
 
-                        typesToAssemblyMap.Add(name, (AssemblyReferenceHandle)exportedType.Implementation);
+                        (int FirstIndex, int SecondIndex) indices;
+
+                        if (typesToAssemblyIndexMap.TryGetValue(name, out indices))
+                        {
+                            // Store it only if it was not a duplicate
+                            if (indices.FirstIndex != referencedAssemblyIndex && indices.SecondIndex < 0)
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: >if (indices.FirstIndex != referencedAssemblyIndex && indices.SecondIndex < 0) [](start = 28, length = 77)

Consider asserting before this 'if' that FirstIndex is not negative.

File: src/Compilers/CSharp/Portable/CSharpResources.resx [hunk 46]
```diff
@@ -5008,4 +5008,7 @@ To remove the warning, you can use /reference instead (set the Embed Interop Typ
   <data name="ERR_AttributesInLocalFuncDecl" xml:space="preserve">
     <value>Attributes are not allowed on local function parameters or type parameters</value>
   </data>
+  <data name="ERR_TypeForwardedToMultipleAssemblies" xml:space="preserve">
+    <value>Type '{0}' is forwarded to multiple assemblies: '{1}' and '{2}'</value>
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CSharpResources.resx]: Would it be useful to include which assembly/module is causing the problem?

**Comment by OmarTawfik** [comment]
Moved to `post-dev15` branch based on original issue triage.

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEAssemblySymbol.cs [hunk 47]
```diff
@@ -130,39 +130,51 @@ public override ImmutableArray<CSharpAttributeData> GetAttributes()
...
             // Check if it is a forwarded type.
-            var forwardedToAssembly = LookupAssemblyForForwardedMetadataType(ref emittedName);
-            if ((object)forwardedToAssembly != null)
+            (AssemblySymbol firstSymbol, AssemblySymbol secondSymbol) = LookupAssembliesForForwardedMetadataType(ref emittedName);
+
+            if ((object)firstSymbol != null)
             {
+                if ((object)secondSymbol != null)
+                {
+                    var forwardingErrorInfo = new DiagnosticInfo(
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEAssemblySymbol.cs]: >var forwardingErrorInfo = new DiagnosticInfo( [](start = 20, length = 45)

It feels like it is much simpler to create new CSDiagnosticInfo the way CreateCycleInTypeForwarderErrorTypeSymbol does this.

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs [hunk 48]
```diff
@@ -641,47 +641,51 @@ internal NamedTypeSymbol LookupTopLevelMetadataType(ref MetadataTypeName emitted
...
         /// </remarks>
-        internal AssemblySymbol GetAssemblyForForwardedType(ref MetadataTypeName fullName)
+        internal (AssemblySymbol FirstSymbol, AssemblySymbol SecondSymbol) GetAssembliesForForwardedType(ref MetadataTypeName fullName)
         {
             string matchedName;
-            AssemblyReferenceHandle assemblyRef = Module.GetAssemblyForForwardedType(fullName.FullName, ignoreCase: false, matchedName: out matchedName);
-            return assemblyRef.IsNil ? null : this.GetReferencedAssemblySymbol(assemblyRef);
+            (int firstIndex, int secondIndex) = this.Module.GetAssemblyRefsForForwardedType(fullName.FullName, ignoreCase: false, matchedName: out matchedName);
+
+            var firstSymbol = firstIndex < 0 ? null : GetReferencedAssemblySymbol(firstIndex);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs]: >var firstSymbol = firstIndex < 0 ? null : GetReferencedAssemblySymbol(firstIndex); [](start = 12, length = 82)

I believe ```firstIndex``` should never be negative. We should assert that and call ```GetReferencedAssemblySymbol(firstIndex)``` unconditionally.

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs [hunk 49]
```diff
@@ -641,47 +641,51 @@ internal NamedTypeSymbol LookupTopLevelMetadataType(ref MetadataTypeName emitted
...
         }
 
         internal IEnumerable<NamedTypeSymbol> GetForwardedTypes()
         {
-            foreach (KeyValuePair<string, AssemblyReferenceHandle> forwarder in Module.GetForwardedTypes())
+            foreach (KeyValuePair<string, (int FirstIndex, int SecondIndex)> forwarder in Module.GetForwardedTypes())
             {
-                var assemblySymbol = this.GetReferencedAssemblySymbol(forwarder.Value);
-                if ((object)assemblySymbol == null)
+                if (forwarder.Value.FirstIndex < 0)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs]: >if (forwarder.Value.FirstIndex < 0) [](start = 16, length = 35)

I do not believe it is possible for this condition to ever be true. We should assert that and remove the ```if```.

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs [hunk 50]
```diff
@@ -641,47 +641,51 @@ internal NamedTypeSymbol LookupTopLevelMetadataType(ref MetadataTypeName emitted
...
-                return null;
+                AssemblySymbol firstSymbol = this.GetReferencedAssemblySymbol(forwarder.Value.FirstIndex);
+                Debug.Assert((object)firstSymbol != null, "Invalid indexes (out of bound) are discarded during reading metadata in PEModule.EnsureForwardTypeToAssemblyMap()");
+
+                if (forwarder.Value.SecondIndex >= 0)
+                {
+                    var secondSymbol = this.GetReferencedAssemblySymbol(forwarder.Value.SecondIndex);
+                    Debug.Assert((object)secondSymbol != null, "Invalid indexes (out of bound) are discarded during reading metadata in PEModule.EnsureForwardTypeToAssemblyMap()");
+
+                    var forwardingErrorInfo = new DiagnosticInfo(MessageProvider.Instance, (int)ErrorCode.ERR_TypeForwardedToMultipleAssemblies, forwarder.Key, firstSymbol.Name, secondSymbol.Name);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs]: >var forwardingErrorInfo = new DiagnosticInfo(MessageProvider.Instance, (int)ErrorCode.ERR_TypeForwardedToMultipleAssemblies, forwarder.Key, firstSymbol.Name, secondSymbol.Name); [](start = 20, length = 177)

It looks like we are duplicating code with PEAssemblySymbol, consider adding a helper similar to the one we have for a cycle and reusing it.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs (hunk 42 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs]: >return new MissingMetadataTypeSymbol.TopLevelWithCustomErrorInfo(SourceModule, ref emittedName, forwardingErrorInfo); [](start = 28, length = 117)

Do we have a test for this scenario?

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs [hunk 51]
```diff
@@ -641,47 +641,51 @@ internal NamedTypeSymbol LookupTopLevelMetadataType(ref MetadataTypeName emitted
...
+                    yield return new MissingMetadataTypeSymbol.TopLevelWithCustomErrorInfo(this, ref name, forwardingErrorInfo);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs]: >yield return new MissingMetadataTypeSymbol.TopLevelWithCustomErrorInfo(this, ref name, forwardingErrorInfo); [](start = 20, length = 108)

Do we have a test for this scenario?

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs [hunk 52]
```diff
@@ -19412,6 +19412,361 @@ public void AbstractInSubmission()
...
+	.assembly extern Destination3
+}
+.class extern forwarder Destination.TestClass
+{
+	.assembly extern Destination4
+}
+.class extern forwarder Destination.TestClass
+{
+	.assembly extern Destination5
+}";
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs]: >}" [](start = 0, length = 2)

Consider adding duplicate forwards to Destination1 and Destination2 at the end.

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs [hunk 53]
```diff
@@ -19412,6 +19412,361 @@ public void AbstractInSubmission()
...
+{
+	.assembly extern D
+}";
+
+            var referenceC2 = CompileIL(codeC2, appendDefaultHeader: false);
+
+            CreateCompilationWithMscorlib(codeA, references: new MetadataReference[] { referenceB, referenceC2 }).VerifyDiagnostics(
+                // (10,38): error CS0012: The type 'ClassC' is defined in an assembly that is not referenced. You must add a reference to assembly 'D, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
+                //             System.Console.WriteLine(ClassB.MethodB(null));
+                Diagnostic(ErrorCode.ERR_NoTypeDef, "ClassB.MethodB").WithArguments("C.ClassC", "D, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null").WithLocation(10, 38));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs]: >Diagnostic(ErrorCode.ERR_NoTypeDef, "ClassB.MethodB").WithArguments("C.ClassC", "D, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null").WithLocation(10, 38)); [](start = 16, length = 162)

Now let's try adding a reference to an assembly D, we should be able to compile and execute.

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs [hunk 54]
```diff
@@ -19412,6 +19412,361 @@ public void AbstractInSubmission()
...
+.class extern forwarder Testspace.TestType
+{
+	.assembly extern D2
+}";
+
+            ImmutableArray<byte> ilBytes;
+            ImmutableArray<byte> pdbBytes;
+            EmitILToArray(ilSource, appendDefaultHeader: false, includePdb: false, assemblyBytes: out ilBytes, pdbBytes: out pdbBytes);
+
+            var ilModule = ModuleMetadata.CreateFromImage(ilBytes).GetReference();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs]: >var ilModule = ModuleMetadata.CreateFromImage(ilBytes).GetReference(); [](start = 12, length = 70)

Would it be useful to create a helper for this, or adjust CompileIL so that it could produce a reference like this based on parameter?

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs [hunk 55]
```diff
@@ -19412,6 +19412,361 @@ public void AbstractInSubmission()
...
+
+            CreateCompilationWithMscorlib(string.Empty, references: new MetadataReference[] { ilModule }).VerifyDiagnostics(
+                // error CS0012: The type 'TestType' is defined in an assembly that is not referenced. You must add a reference to assembly 'D1, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
+                Diagnostic(ErrorCode.ERR_NoTypeDef).WithArguments("Testspace.TestType", "D1, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null").WithLocation(1, 1));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs]: >   Diagnostic(ErrorCode.ERR_NoTypeDef).WithArguments("Testspace.TestType", "D1, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null").WithLocation(1, 1)); [](start = 13, length = 156)

Now let's try to add a reference and verify that compilation succeeds. After that we should verify that the assembly forwards the type.

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs [hunk 56]
```diff
@@ -19412,6 +19412,361 @@ public void AbstractInSubmission()
...
+{
+    .ver 1:0:0:0
+}
+.class extern forwarder Destination.TestClass
+{
+	.assembly extern Destination1
+}
+.class extern forwarder Destination.TestClass
+{
+	.assembly extern Destination2
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs]: You were going to add a test verifying that even if the chain of forwarders results in the same type, we still get an error, but I don't see a test like this. Consider adding it.

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs (hunk 54 above)
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs]: `CommonTestBase.CompileIL()`

File: src/Compilers/VisualBasic/Portable/Binding/Binder_Symbols.vb [hunk 57]
```diff
@@ -516,10 +511,15 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
                 Next
 
                 If forwardedType IsNot Nothing Then
-                    If forwardedType.IsErrorType Then
-                        Dim diagInfo As DiagnosticInfo = DirectCast(forwardedType, ErrorTypeSymbol).ErrorInfo
-                        If diagInfo.Code = ERRID.ERR_TypeFwdCycle2 Then
-                            encounteredCycle = True
+                    If Not reportedAnError And forwardedType.IsErrorType Then
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Binding/Binder_Symbols.vb]: >And [](start = 43, length = 3)

AndAlso?

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Binding/Binder_Symbols.vb]: >Not reportedAnError [](start = 23, length = 19)

Consider simply passing null (Nothing) bag if we are not interested in diagnostics.

File: src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEAssemblySymbol.vb [hunk 58]
```diff
@@ -142,32 +142,43 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols.Metadata.PE
...
         Friend Overrides Function TryLookupForwardedMetadataTypeWithCycleDetection(ByRef emittedName As MetadataTypeName, visitedAssemblies As ConsList(Of AssemblySymbol), ignoreCase As Boolean) As NamedTypeSymbol
             ' Check if it is a forwarded type.
             Dim matchedName As String = Nothing
-            Dim forwardedToAssembly = LookupAssemblyForForwardedMetadataType(emittedName, ignoreCase, matchedName)
-            ' Don't bother to check the forwarded-to assembly if we've already seen it.
-            If forwardedToAssembly IsNot Nothing Then
-                If visitedAssemblies IsNot Nothing AndAlso visitedAssemblies.Contains(forwardedToAssembly) Then
+            Dim forwardedToAssemblies = LookupAssembliesForForwardedMetadataType(emittedName, ignoreCase, matchedName)
+
+            If DirectCast(forwardedToAssemblies.FirstSymbol, Object) IsNot Nothing
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEAssemblySymbol.vb]: >DirectCast( [](start = 15, length = 11)

Cast to object is not needed for Is/IsNot checks. Please remove.

File: src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEModuleSymbol.vb [hunk 59]
```diff
@@ -423,30 +423,44 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols.Metadata.PE
...
-        ''' The returned assembly may also forward the type.
+        ''' The returned assemblies may also forward the type.
         ''' </remarks>
-        Friend Function GetAssemblyForForwardedType(ByRef fullName As MetadataTypeName, ignoreCase As Boolean, <Out> ByRef matchedName As String) As AssemblySymbol
-            Dim assemblyRef As AssemblyReferenceHandle = Me.Module.GetAssemblyForForwardedType(fullName.FullName, ignoreCase, matchedName)
-            Return If(assemblyRef.IsNil, Nothing, GetReferencedAssemblySymbol(assemblyRef))
+        Friend Function GetAssembliesForForwardedType(ByRef fullName As MetadataTypeName, ignoreCase As Boolean, <Out> ByRef matchedName As String) As (FirstSymbol As AssemblySymbol, SecondSymbol As AssemblySymbol)
+            Dim indices = Me.Module.GetAssemblyRefsForForwardedType(fullName.FullName, ignoreCase, matchedName)
+            
+            Dim firstSymbol = If(indices.FirstIndex < 0, Nothing, GetReferencedAssemblySymbol(indices.FirstIndex))
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEModuleSymbol.vb]: >indices.FirstIndex < 0 [](start = 33, length = 22)

FirstIndex is never negative, please remove conditional code. Assert instead.

File: src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEModuleSymbol.vb [hunk 60]
```diff
@@ -423,30 +423,44 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols.Metadata.PE
...
+
+            return (firstSymbol, secondSymbol)
         End Function
 
         Friend Iterator Function GetForwardedTypes() As IEnumerable(Of NamedTypeSymbol)
-            For Each forwarder As KeyValuePair(Of String, AssemblyReferenceHandle) In Me.Module.GetForwardedTypes()
-                Dim assembly As AssemblySymbol = GetReferencedAssemblySymbol(forwarder.Value)
-                If assembly Is Nothing Then
+            For Each forwarder As KeyValuePair(Of String, (FirstIndex As Integer, SecondIndex As Integer)) In Me.Module.GetForwardedTypes()
+                If forwarder.Value.FirstIndex < 0 Then
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEModuleSymbol.vb]: >If forwarder.Value.FirstIndex < 0 Then [](start = 16, length = 38)

FirstIndex is never negative, please remove conditional code. Assert instead.

File: src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEModuleSymbol.vb [hunk 61]
```diff
@@ -423,30 +423,44 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols.Metadata.PE
...
 
                 Dim name = MetadataTypeName.FromFullName(forwarder.Key)
-                Yield assembly.LookupTopLevelMetadataType(name, digThroughForwardedTypes:=True)
+
+                Dim firstSymbol = GetReferencedAssemblySymbol(forwarder.Value.FirstIndex)
+                Debug.Assert(DirectCast(firstSymbol, Object) IsNot Nothing, "Invalid indexes (out of bound) are discarded during reading metadata in PEModule.EnsureForwardTypeToAssemblyMap()")
+
+                If forwarder.Value.SecondIndex >= 0 Then
+                    Dim secondSymbol = GetReferencedAssemblySymbol(forwarder.Value.SecondIndex)
+                    Debug.Assert(DirectCast(secondSymbol, Object) IsNot Nothing, "Invalid indexes (out of bound) are discarded during reading metadata in PEModule.EnsureForwardTypeToAssemblyMap()")
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEModuleSymbol.vb]: >DirectCast [](start = 33, length = 10)

Please remove the cast

File: src/Compilers/VisualBasic/Portable/Symbols/Source/SourceAssemblySymbol.vb [hunk 62]
```diff
@@ -1693,11 +1693,16 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols
                 ' Similar to attributes, type forwarders from the second added module should override type forwarders from the first added module, etc. 
                 For i As Integer = _modules.Length - 1 To 1 Step -1
                     Dim peModuleSymbol = DirectCast(_modules(i), PEModuleSymbol)
+                    Dim forwardedToAssemblies = peModuleSymbol.GetAssembliesForForwardedType(emittedName, ignoreCase, matchedName)
+
+                    If DirectCast(forwardedToAssemblies.FirstSymbol, Object) IsNot Nothing Then
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceAssemblySymbol.vb]: >DirectCast [](start = 23, length = 10)

Please remove the cast

File: src/Compilers/VisualBasic/Portable/Symbols/Source/SourceAssemblySymbol.vb [hunk 63]
```diff
@@ -1693,11 +1693,16 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols
...
+                        If DirectCast(forwardedToAssemblies.SecondSymbol, Object) IsNot Nothing Then
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceAssemblySymbol.vb]: >DirectCast [](start = 27, length = 10)

Please remove the cast

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs (hunk 38 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs]: @cston the type `MetadataTypeName` is not serializable, so, I'll use the `FullName` property instead, and the full assembly symbol as suggested.

File: src/Compilers/CSharp/Portable/CSharpResources.resx (hunk 46 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/CSharpResources.resx]: Good point. I was considering parity with the native compiler, but adding it should improve the user experience.

**Comment by OmarTawfik** [comment]
Note to self, since I'll add the module name to the error message, consider adding tests that verify that we report the correct module (modules forwarding the same type will override other modules in the same assembly).

**Comment by OmarTawfik** [comment]
Note to self, forwarders in later modules should override forwarders in earlier modules in a compilation. Consider adding a test that reports we're reporting the correct module in that sense, since we're including the module name in error messages.

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs (hunk 54 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs]: `CommonTestBase.CompileIL()` returns an assembly reference. Will create another method that returns a module reference. I need to include this module in the assembly I'm compiling.

**Comment by OmarTawfik** [comment]
Note to self: might want to file a separate PR after this one to rename `CommonTestBase.CompileIL` to `CommonTestBase.GetILAssemblyReferece`.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs (hunk 42 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs]: Where would that helper live for all three? My quick search in `CSharpCodeAnalysis` failed to find such a place for one-liners.

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs (hunk 48 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs]: @AlekseyTs In case the type is not forwarded for that `fullName`, we will return two -1s.

Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs]: It can be changed to:
```csharp
if (first < 0)
      return (null, null);
if (second < 0)
      return (GetReferencedAssemblySymbol(first), null);
return (GetReferencedAssemblySymbol(first), GetReferencedAssemblySymbol(second));
```

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs]: Yes, I think this would make code easier to follow. Consider extracting GetReferencedAssemblySymbol(first) into a local.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEModuleSymbol.cs]: I guess the same applies to a VB counterpart.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs (hunk 42 above)
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs]: Perhaps a static method on `MissingMetadataTypeSymbol` or an instance method on `ModuleSymbol`. Note, it's not strictly a one-liner since the `DiagnosticInfo` can be constructed in the helper too. We should fix this to avoid the code duplication.

Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs]: @AlekseyTs yes. Check `AddingReferenceToModuleWithMultipleForwardersToDifferentAssembliesShouldErrorOut`

File: src/Compilers/VisualBasic/Portable/Binding/Binder_Symbols.vb (hunk 57 above)
Comment (OmarTawfik) [inline src/Compilers/VisualBasic/Portable/Binding/Binder_Symbols.vb]: From what I can tell in the rest of the binder code, both are passed around for various checks. Do we want to make the exception here (changing it to use a Nothing bag if reportedAnError was true, doing the null check before reporting?).

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Binding/Binder_Symbols.vb]: Why pass two pieces of information about the same thing, allowing people to pass information that can contradict each other. For example, do we handle a case when reportedAnError is false and the bag is null at the same time? Why complicate things when they can be very simple, i.e. simply pass a diagnostics bag when you want to get diagnostics, pass null otherwise.

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Binding/Binder_Symbols.vb]: BTW, from looking at the signature of the method, it is not clear that no diagnostics is going to be produced when reportedAnError is true. At the very least I think the parameter should be renamed to reportDiagnostics and its meaning should be reversed, but ideally we should remove it.

**Comment by OmarTawfik** [comment]
@AlekseyTs comments addressed.

**Comment by OmarTawfik** [comment]
@jaredpar @cston @jcouv can I get a second sign off?

File: src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEAssemblySymbol.vb [hunk 64]
```diff
@@ -142,32 +142,38 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols.Metadata.PE
...
             Dim matchedName As String = Nothing
-            Dim forwardedToAssembly = LookupAssemblyForForwardedMetadataType(emittedName, ignoreCase, matchedName)
-            ' Don't bother to check the forwarded-to assembly if we've already seen it.
-            If forwardedToAssembly IsNot Nothing Then
-                If visitedAssemblies IsNot Nothing AndAlso visitedAssemblies.Contains(forwardedToAssembly) Then
+            Dim forwardedToAssemblies = LookupAssembliesForForwardedMetadataType(emittedName, ignoreCase, matchedName)
+
+            If forwardedToAssemblies.FirstSymbol IsNot Nothing Then
+                If forwardedToAssemblies.SecondSymbol IsNot Nothing Then
+                    ' Report the main module as that Is the only one checked. clr does Not honor type forwarders in non-primary modules.
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PEAssemblySymbol.vb]: `... is ... not` rather than `... Is ... Not`

**Comment by cston** [comment]
LGTM
