### PR TITLE
Don't drop a token passed to a syntax factory method.

### LINKED ISSUE #37467: SyntaxFactory.MethodDeclaration bug
**Version Used**: 
v3.1.0 Microsoft.CodeAnalysis.CSharp

**Steps to Reproduce**:
Use `SyntaxFactory.MethodDeclaration(SyntaxList<AttributeListSyntax>, SyntaxTokenList, TypeSyntax, ExplicitInterfaceSpecifierSyntax, SyntaxToken, TypeParameterListSyntax, ParameterListSyntax, SyntaxList<TypeParameterConstraintClauseSyntax>, BlockSyntax, SyntaxToken)` overload

**Expected Behavior**:
Semicolon SyntaxToken passed to wrapped method

**Actual Behavior**:
Semicolon SyntaxToken replaced with `default(SyntaxToken)`

Checked IL in downloaded nugget package to verify issue.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #37467

@dotnet/roslyn-compiler May I please have a couple of reviews for this one-line bug fix for 16.3?

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Syntax/MethodDeclarationSyntax.cs [hunk 1]
```diff
@@ -34,7 +34,18 @@ public partial class SyntaxFactory
...
+                attributeLists,
+                modifiers,
+                returnType,
+                explicitInterfaceSpecifier,
+                identifier,
+                typeParameterList,
+                parameterList,
+                constraintClauses,
+                body,
+                null,
```
Comment (sharwell) [inline src/Compilers/CSharp/Portable/Syntax/MethodDeclarationSyntax.cs]: 💡 I'm not sure what this one is, so a named argument might improve readability
