### PR TITLE
Fix Integration test MetadataReference

### LINKED ISSUE #55711: Re-enable MetadataReference integration test
Disabled in PR - https://github.com/dotnet/roslyn/pull/55681

The test generally passes when run locally as a single test, however consistently fails for me when run along with other tests (re-suing the same VS instance) after upgrading the integration test machines to dev17p3.

Disabling to unblock CI.

### PR DESCRIPTION
**Pull request by Cosifne**
The reason for the test failure is:
image

Net461 SDK is not installed by the workload by default.
Therefore in the CI, all the referenced assemblies could not be found
image

Simply change it to Net462 would fix the problem
Closes #55711

### CODE REVIEW

**Comment by jaredpar** [comment]
@sharwell

File: src/VisualStudio/IntegrationTest/IntegrationTests/Workspace/WorkspacesNetCore.cs [hunk 1]
```diff
@@ -40,7 +40,7 @@ public override void MetadataReference()
             VisualStudio.SolutionExplorer.EditProjectFile(project);
             VisualStudio.Editor.SetText(@"<Project Sdk=""Microsoft.NET.Sdk"">
   <PropertyGroup>
-    <TargetFramework>net461</TargetFramework>
+    <TargetFramework>net462</TargetFramework>
```
Comment (sharwell) [inline src/VisualStudio/IntegrationTest/IntegrationTests/Workspace/WorkspacesNetCore.cs:43]: We can't assume net462 will be installed either. The harness only requires net46:

https://github.com/dotnet/roslyn/blob/cb400a925dc235b505ee2163dc1501d3433d2a12/src/VisualStudio/IntegrationTest/IntegrationTests/SharedIntegrationHostFixture.cs#L22

Any of the following changes would be acceptable:

1. Change the test to use net46
2. Change the test to add a `<PackageReference>` for the .NET 4.6.1 targeting pack from NuGet
3. Update the harness to require .NET 4.6.1 targeting pack be installed in the test instance
4. Update the test to use net462 _and_ perform either (2) or (3) for .NET 4.6.2

I believe the approach most likely to work in the future without maintainability problems is (2).

**Review by sharwell — CHANGES_REQUESTED** [review]

File: src/VisualStudio/IntegrationTest/IntegrationTests/Workspace/WorkspacesNetCore.cs (hunk 1 above)
Comment (Cosifne) [reply src/VisualStudio/IntegrationTest/IntegrationTests/Workspace/WorkspacesNetCore.cs]: Update the test to use PackageRefernece instead

Comment (sharwell) [reply src/VisualStudio/IntegrationTest/IntegrationTests/Workspace/WorkspacesNetCore.cs]: Sorry I wasn't more clear. For the PackageReference, I was expecting a reference to this package:
https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies/

The package provides targeting support for .NET Framework versions in cases where the targeting pack is not installed locally. Originally this was primarily used to provide support for builds on Linux, but it also works for providing support for scenarios like we encountered here.

**Review by sharwell — APPROVED** [review]
I would slightly prefer the call to `PackageReference` be inlined (placing it before the existing call to `RestoreNuGetPackages` means it will only be 2 lines total), but functionally this is what I was hoping to see.

File: src/VisualStudio/IntegrationTest/IntegrationTests/Workspace/WorkspacesNetCore.cs [hunk 2]
```diff
@@ -49,6 +49,9 @@ public override void MetadataReference()
             // https://github.com/dotnet/roslyn/issues/34264
             VisualStudio.Workspace.WaitForAllAsyncOperations(Helper.HangMitigatingTimeout);
             VisualStudio.SolutionExplorer.OpenFile(project, "Class1.cs");
+            var referenceAssemblies = new ProjectUtils.PackageReference("Microsoft.NETFramework.ReferenceAssemblies.net461", "1.0.2");
+            VisualStudio.SolutionExplorer.AddPackageReference(project, referenceAssemblies);
+            VisualStudio.SolutionExplorer.RestoreNuGetPackages(project);
```
Comment (sharwell) [inline src/VisualStudio/IntegrationTest/IntegrationTests/Workspace/WorkspacesNetCore.cs:54]: 💡 If this moves up 3 lines (above the existing call to `RestoreNuGetPackages`), the second call to `RestoreNuGetPackages` can be removed.

**Review by sharwell — APPROVED** [review]

File: src/VisualStudio/IntegrationTest/IntegrationTests/Workspace/WorkspacesNetCore.cs [hunk 3]
```diff
@@ -40,7 +40,7 @@ public override void MetadataReference()
             VisualStudio.SolutionExplorer.EditProjectFile(project);
             VisualStudio.Editor.SetText(@"<Project Sdk=""Microsoft.NET.Sdk"">
   <PropertyGroup>
-    <TargetFramework>net461</TargetFramework>
+    <TargetFramework>net46</TargetFramework>
```
Comment (sharwell) [inline src/VisualStudio/IntegrationTest/IntegrationTests/Workspace/WorkspacesNetCore.cs:43]: Have we tried this?

```suggestion
    <TargetFramework>net461</TargetFramework>
    <UseWPF>true</UseWPF>
```

Comment (sharwell) [reply src/VisualStudio/IntegrationTest/IntegrationTests/Workspace/WorkspacesNetCore.cs:43]: Oh, right, that would change because we need the reference to not exist initially, and then be added.

This test really needs to be rewritten to use `BigInteger` instead of `System.Windows.Point`. The WPF dependency isn't correctly handled by our features.

Comment (Cosifne) [reply src/VisualStudio/IntegrationTest/IntegrationTests/Workspace/WorkspacesNetCore.cs:43]: Yep I tried <UseWPF> and it doens't work.
For using https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies/, solution explorer is complaining it can't find WindowsBase dll
And so I try to switch back to net46 to see if it works..

Comment (Cosifne) [reply src/VisualStudio/IntegrationTest/IntegrationTests/Workspace/WorkspacesNetCore.cs:43]: Maybe `BigInteger` is not the best choice because the default template is referecing System.Numerics by default
image
We may want to find a struct in other assemblies

Comment (sharwell) [reply src/VisualStudio/IntegrationTest/IntegrationTests/Workspace/WorkspacesNetCore.cs:43]: Yes, we'll want to find a different assembly. I was thinking System.Numerics wasn't included by default.
