### PR TITLE
Fix `is` and pattern-matching behavior in presence of implicit UD conversion

### LINKED ISSUE #24522: is operator not working if implicit conversion operator exists on generic type
**Version Used**: 7.2

**Steps to Reproduce**:

    class Base<T>
    {
        //without implicit operator everything works as expected
        public static implicit operator Derived(Base<T> obj)
        {
            return new Derived();
        }
    }

    class Derived : Base<object>
    {

    }

    class Program
    {
        static void Main(string[] args)
        {
            Base<object> x = new Derived();
            if (x is Derived) //Problem: this is always false!!
            {

            }
        }
    }

**Expected Behavior**: (x is Derived) should be true in this case (it worked like that in the old csc.exe).

**Actual Behavior**: (x is Derived) is always false.

### PR DESCRIPTION
**Pull request by gafter**
Fix `is` and pattern-matching behavior in presence of implicit UD conversion
and also an explicit reference conversion between the same types.
User-defined conversions should never be considered for `is` and pattern-matching.

### Customer scenario

See #24522 

### Bugs this fixes

Fixes #24522

### Workarounds, if any

Casting the left-hand-side to `object` is often a work-around.

### Risk

Low, as the fix is quite localized.

### Performance impact

Should be slight performance improvement, as we now only check built-in conversions for certain type-check operations.

### Is this a regression from a previous update?

Yes. C#6 did not have this bug.

### Root cause analysis

We did not realize that it is possible for an implicit user-defined operator to be present when an explicit reference conversion applies.

We now have tests for the ways that symptoms can arise.

### How was the bug found?

Customer reported.

### Test documentation updated?

N/A

### CODE REVIEW

**Comment by gafter** [comment]
@agocke @dotnet/roslyn-compiler may I please have a couple of reviews of this pattern-matching bug fix?

File: src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs [hunk 1]
```diff
@@ -504,7 +504,8 @@ public BoundAsOperator As(BoundExpression operand, TypeSymbol type)
         public BoundIsOperator Is(BoundExpression operand, TypeSymbol type)
         {
             HashSet<DiagnosticInfo> discarded = null;
-            Conversion c = Compilation.Conversions.ClassifyConversionFromExpression(operand, type, ref discarded);
+            const bool preferBuiltinConversion = true;
+            Conversion c = Compilation.Conversions.ClassifyConversionFromExpression(operand, type, ref discarded, preferBuiltinConversion);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs]: >preferBuiltinConversion [](start = 114, length = 23)

It doesn't look like passing this value guarantees that user defined conversions are ignored completely.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1).

File: src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs]: That isn't the intended behavior. It just needs to prioritize builtin conversions over user-defined conversions.

**Comment by gafter** [comment]
Done with responses to review pass (iteration 1). Do you have any other comments?

File: src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs]: >  It just needs to prioritize builtin conversions over user-defined conversions.

What would be a valid scenario when a user defined conversion should be accepted here?

Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs]: I don't know what you mean by "accepted". The conversion is required in the node but isn't used subsequent to lowering. The `is` operator in the language does not actually require that a conversion exist. The conversion is stored to assist with semantics (specifically warnings) and lowering when the `is` operator appears in source. Those don't apply to the node produced here.

If it would make it more clear, we can use `NoConversion` here.

Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs]: Or, if you prefer, we can compute a built-in conversion from type.

**Comment by gafter** [comment]
@agocke Can you please review this pattern-matching bug fix?

**Comment by gafter** [comment]
@agocke Can you please review this pattern-matching bug fix?

**Comment by agocke** [comment]
@gafter Looking now.
