### PR TITLE
Fix WarningLevel for hidden diagnostics

### LINKED ISSUE #41784: Warning Level 3 breaks Remove Unused Usings and Simplify Type Name
**Version Used**: 16.5 Preview 2

**Steps to Reproduce**:

Regression of #20377

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #41784

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs [hunk 1]
```diff
@@ -198,8 +198,8 @@ internal static int GetWarningLevel(ErrorCode code)
         {
             if (IsInfo(code) || IsHidden(code))
             {
-                // Info and hidden diagnostics have default warning level.
-                return Diagnostic.DefaultWarningLevel;
+                // Info and hidden diagnostics should always be produced because some analyzers depend on them.
+                return 1;
```
Comment (Youssef1313) [inline src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs:202]: Should this return 0 instead?

Comment (333fred) [reply src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs:202]: Changing both info and hidden seems fine to me, as info doesn't affect the command line build.

---
In reply to: [501191632](https://github.com/dotnet/roslyn/pull/48397#discussion_r501191632) [](ancestors = 501191632)

File: src/Compilers/CSharp/Test/Symbol/Compilation/GetUnusedImportDirectivesTests.cs [hunk 2]
```diff
@@ -287,6 +287,16 @@ void M()
                 // using System.Collections.Generic;
                 Diagnostic(ErrorCode.HDN_UnusedUsingDirective, "using System.Collections.Generic;")
                 );
+
+            comp = CreateCompilation(source, options: TestOptions.ReleaseDll.WithWarningLevel(3));
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Symbol/Compilation/GetUnusedImportDirectivesTests.cs:291]: Please also add a test with `WarningLevel(0)`

**Comment by 333fred** [comment]
Done review pass (commit 2). One minor test to ad.

**Review by 333fred — APPROVED** [review]
LGTM (commit 3). @dotnet/roslyn-compiler for a second review.

File: src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs (hunk 1 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs:202]: Rather than use a literal here I think we should use a named constant. I would add one next to `DefaultWarningLevel` with a doc comment summarizing what it represents

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Errors/ErrorFacts.cs]: @jaredpar Done

**Review by jaredpar — APPROVED** [review]

File: src/Compilers/Core/Portable/Diagnostic/Diagnostic.cs [hunk 3]
```diff
@@ -26,6 +26,11 @@ public abstract partial class Diagnostic : IEquatable<Diagnostic?>, IFormattable
         /// </summary>
         internal const int DefaultWarningLevel = 4;
 
+        /// <summary>
+        /// The warning level used for hidden and info diagnostics.
```
Comment (333fred) [inline src/Compilers/Core/Portable/Diagnostic/Diagnostic.cs:30]: Nit: can you add a more complete description? IE, why this is different from Default

Comment (Youssef1313) [reply src/Compilers/Core/Portable/Diagnostic/Diagnostic.cs:30]:
```suggestion
        /// The warning level used for hidden and info diagnostics. Because these diagnostics interact with other editor features, we want them to always be produced unless /warn:0 is set.
```

**Comment by 333fred** [comment]
@Youssef1313 looks like the formatting is off.

**Comment by 333fred** [comment]
Thanks @Youssef1313!
