### PR TITLE
Format on Typing Colon For Switch Case Default and Labels

### LINKED ISSUE #464: Space key should be swallowed if space is inserted by previous completion
Ported from TFS WorkItem: **908729**

------------------------------

**Repro Steps:**

1. EditorTestApp

2. Paste this code:

&nbsp;
<PRE style="FONT-SIZE: 16px; FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink"><SPAN style="COLOR: blue">class</SPAN> <SPAN style="COLOR: #2b91af">C</SPAN>
<SPAN style="COLOR: black">{</SPAN>
    <SPAN style="COLOR: blue">static</SPAN> <SPAN style="COLOR: blue">void</SPAN> <SPAN style="COLOR: black">Main</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">string</SPAN><SPAN style="COLOR: black">[]</SPAN> <SPAN style="COLOR: black">args</SPAN><SPAN style="COLOR: black">)</SPAN>
    <SPAN style="COLOR: black">{</SPAN>
        <SPAN style="COLOR: black">Main</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">null</SPAN><SPAN style="COLOR: black">);</SPAN>
    <SPAN style="COLOR: black">}</SPAN>
<SPAN style="COLOR: black">}</SPAN></PRE>

3. Place the caret before null and after (

4. Type args: followed by SPACE

&nbsp;

**Expected:** since pressing : inserts a space into the buffer, subsequent space should be swallowed

&nbsp;

**Actual:** second space is inserted

&nbsp;

Dev12 behavior is also annoying: in Dev12, after we press : we popup completion list with null preselected, so pressing space inserts a second null, which is also undesired.

------------------------------

**Revisions:**

1) Created By Kirill Osenkov (3/19/2014 7:55:37 PM)

------------------------------

2) Edited By Ravi Chande (3/20/2014 1:46:09 PM)

Smart token formatting inserts a space between a named argument and the value after you type :. I also find this very confusing, so I think we should not do this. What does triage think?

------------------------------

### PR DESCRIPTION
**Pull request by basoundr**
Fixes #464 : Formatting should be triggered on typing colon only in the context of Switch cases, switch default and labelled statement

### CODE REVIEW

File: src/EditorFeatures/CSharp/Formatting/CSharpEditorFormattingService.cs [hunk 1]
```diff
@@ -142,7 +142,8 @@ private static bool TokenShouldNotFormatOnReturn(SyntaxToken token)
 
         private static bool TokenShouldNotFormatOnTypeChar(SyntaxToken token)
         {
-            return token.IsKind(SyntaxKind.CloseParenToken) && !token.Parent.IsKind(SyntaxKind.UsingStatement);
+            return token.IsKind(SyntaxKind.CloseParenToken) && !token.Parent.IsKind(SyntaxKind.UsingStatement) ||
```
Comment (brettfo) [inline src/EditorFeatures/CSharp/Formatting/CSharpEditorFormattingService.cs]: Can you add parens around the appropriate clauses?  It'll be a lot easier to read and modify.

**Comment by brettfo** [comment]
:shipit:

**Comment by DustinCampbell** [comment]
:+1:
