### PR TITLE
Correct nullability analysis in conditional access

### LINKED ISSUE #29956: Incorrect nullability analysis in conditional access
```C#
        public override BoundNode VisitConditionalAccess(BoundConditionalAccess node)
        {
            Debug.Assert(!IsConditionalState);

            var receiver = node.Receiver;
            var receiverType = VisitRvalueWithResult(receiver);

            var receiverState = this.State.Clone();

            if (receiver.Type?.IsValueType == false)
            {
                if (receiverType.IsNullable == false)
                {
                    ReportDiagnostic(ErrorCode.HDN_ExpressionIsProbablyNeverNull, receiver.Syntax);
                }

                int slot = MakeSlot(SkipReferenceConversions(receiver));
                if (slot > 0)
                {
                    if (slot >= this.State.Capacity) Normalize(ref this.State);
                    this.State[slot] = true;
                }
            }

            if (IsConstantNull(node.Receiver))
            {
                SetUnreachable();
            }

            VisitRvalue(node.AccessExpression);
            IntersectWith(ref this.State, ref receiverState);

            // PROTOTYPE(NullableReferenceTypes): Use flow analysis type rather than node.Type
            // so that nested nullability is inferred from flow analysis. See VisitConditionalOperator.
            _resultType = TypeSymbolWithAnnotations.Create(node.Type, isNullableIfReferenceType: receiverType.IsNullable | _resultType.IsNullable);
            // PROTOTYPE(NullableReferenceTypes): Report conversion warnings.
            return null;
        }


        public override BoundNode VisitConditionalReceiver(BoundConditionalReceiver node)
        {
            var result = base.VisitConditionalReceiver(node);
            // PROTOTYPE(NullableReferenceTypes): ConditionalReceiver does not
            // have a result type. Should this be moved to ConditionalAccess?
            _resultType = TypeSymbolWithAnnotations.Create(node.Type, isNullableIfReferenceType: false);
            return result;
        }
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #29956

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a couple of reviews of this change?

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a couple of reviews of this change?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 1]
```diff
@@ -2221,27 +2221,28 @@ public override BoundNode VisitConditionalAccess(BoundConditionalAccess node)
...
             {
-                ReportSafetyDiagnostic(ErrorCode.WRN_ConditionalAccessMayReturnNull, node.Syntax, node.Type);
+                ReportSafetyDiagnostic(ErrorCode.WRN_ConditionalAccessMayReturnNull, node.Syntax, accessType);
             }
 
+            var resultType =
+                accessType.SpecialType == SpecialType.System_Void || accessType.IsPointerType() || accessType.IsRestrictedType() ? compilation.GetSpecialType(SpecialType.System_Void) :
+                accessType.CanBeAssignedNull() ? accessType :
+                accessType.IsNonNullableValueType() ? compilation.GetSpecialType(SpecialType.System_Nullable_T).Construct(ImmutableArray.Create(accessTypeWithAnnotations)) :
+                compilation.GetSpecialType(SpecialType.System_Void);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >compilation.GetSpecialType(SpecialType.System_Void); [](start = 16, length = 52)

This logic is way too complicated and it looks like it is trying to duplicate similar logic from the binding layer. Either we should extract the logic and share it between the two layers, or use much simple logic here that is simply based off of the type that the original node has:
- If original type is void -> void
- if original type is ```Nullable<T>`` and ```accessType``` is not -> ```Nullable<accessType>```
- Otherwise accessType

We should also add an assert that the type we get at the end is equal to the original type, ignoring all possible aspects.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 2]
```diff
@@ -89050,5 +89050,93 @@ class Derived<T> : Base<T> where T : class
             Assert.False(dGoo.Parameters[0].Type.IsNullableType());
             Assert.True(dGoo.Parameters[0].TypeWithAnnotations.NullableAnnotation == NullableAnnotation.Annotated);
         }
+
+        [Fact, WorkItem(29956, "https://github.com/dotnet/roslyn/issues/29956")]
+        public void ConditionalExpression_InferredResultType()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >ConditionalExpression_InferredResultType [](start = 20, length = 40)

It doesn't look like this code covers all the code paths introduced by the result type inference code in ```NullableWalker.VisitConditionalAccess```. I think we would want at least all branches be covered by targeted tests.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: See also scenario in [https://github.com/dotnet/roslyn/issues/35075](https://github.com/dotnet/roslyn/issues/35075), even though there is a bug in the binder layer, I think we would want to end up with the "same" result type. Please incorporate it into one of the tests.

---
In reply to: [276453260](https://github.com/dotnet/roslyn/pull/34973#discussion_r276453260) [](ancestors = 276453260)

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 2)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Unfortunately, the code in the binder is intertwined with error reporting and other error recovery in a way that makes sharing it nontrivial.  Like most of the nullable walker, I believe this code simply has to reproduce the correct language semantics.  I did try a simpler logic, but it is wrong.

---
In reply to: [276447420](https://github.com/dotnet/roslyn/pull/34973#discussion_r276447420) [](ancestors = 276447420)

Comment (gafter) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: I misread your suggestion.  I'll try that.

---
In reply to: [278341199](https://github.com/dotnet/roslyn/pull/34973#discussion_r278341199) [](ancestors = 278341199,276447420)

Comment (gafter) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: The suggested assertion appears in `VisitExpressionWithoutStackGuard`, which is on the path from the caller.

---
In reply to: [278345603](https://github.com/dotnet/roslyn/pull/34973#discussion_r278345603) [](ancestors = 278345603,278341199,276447420)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 3]
```diff
@@ -2483,27 +2483,28 @@ public override BoundNode VisitConditionalAccess(BoundConditionalAccess node)
                 LearnFromNonNullTest(receiver, ref this.State);
             }
 
-            var accessExpressionType = VisitRvalueWithState(node.AccessExpression);
+            var accessTypeWithAnnotations = VisitLvalueWithAnnotations(node.AccessExpression);
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >VisitLvalueWithAnnotations [](start = 44, length = 26)

Why is this correct? The left-side of a conditional access expression is still an rvalue.

Comment (gafter) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: The is visiting the right-hand-side of the ?. expression.  The result is not the final result of the whole expression.  We get the lvalue of the right-hand-side (as a type with annotations) so we can use it as a type argument to `System.Nullable` if necessary.

---
In reply to: [278710760](https://github.com/dotnet/roslyn/pull/34973#discussion_r278710760) [](ancestors = 278710760)

**Comment by gafter** [comment]
@AlekseyTs @333fred I think I've addressed all of your comments so far.  Do you have any others?

**Comment by gafter** [comment]
@AlekseyTs You may want to have another look.  This PR now introduces a helper `.IsVoidType()`.

**Comment by 333fred** [comment]
@gafter tests are failing.

**Comment by gafter** [comment]
@333fred All tests pass now.  Do you have any further comments?
