### PR TITLE
Ensure we do not drop interfaces on partial type declarations when bases have oblivious differences

### LINKED ISSUE #63490: CS0540 partial type with generic base does not implement interface
**Version Used**: `4.4.0-2.22405.13 (dcfe294d)` / `7.0.100-preview.4.22252.9`

**Steps to Reproduce**:

**Test1.cs**
```C#
interface ITest
{
    void Test();
}

class Generic<T> { }
class Argument { }
partial class Partial : Generic<Argument> { }
```

**Test1.cs**
```C#
partial class Partial : Generic<Argument>, ITest
{
    void ITest.Test() { }
}
```

Now either
1. include `#nullable enable` in Test1.cs; or
2. set `<Nullable>enable</Nullable>` in the project and add `// <auto-generated />` to Test2.cs

**Expected Behavior**: Compiles without errors. As per [Partial and Methods](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods) "Parts can specify different base interfaces, and the final type implements all the interfaces listed by all the partial declarations."

**Actual Behavior**:
```
Test2.cs(5,10,5,15): error CS0540: 'Partial.ITest.Test()': containing type does not implement interface 'ITest'
```

**Related:**
#32041, #31858

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #63490

When we did #55861 we didn't realize that the `continue` would cause interfaces to be skipped.

### CODE REVIEW

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 1)

File: src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs [hunk 1]
```diff
@@ -9794,5 +9794,29 @@ class C2 : I
 ";
             var comp = CreateCompilation(source).VerifyDiagnostics();
         }
+
+        [Fact]
+        [WorkItem(63490, "https://github.com/dotnet/roslyn/issues/63490")]
+        public void MultipleBasesWithObliviousDifferencesAndInterfaces()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs:9800]: >MultipleBasesWithObliviousDifferencesAndInterfaces [](http://example.com/codeflow?start=20&length=50)

Consider testing with different order for partial declarations to make sure the behavior is not order dependent

**Review by 333fred — APPROVED** [review]
