### PR TITLE
fixed a race where solution cralwer used wrong solution for it to pro…

### LINKED ISSUE #30420: Solution crawler does not tell analyzer (registered via ISolutionCrawlerRegistrationService) about all versions of a document
**Version Used**: Recent build from lab/d16.0stg

**Steps to Reproduce**:

1. Create machine with recent 16.0 build
2. Clone bugrepro branch in testimpact repo: https://github.com/dotnet/testimpact/tree/bugrepro
3. Run “build -sbd -skiptest” from root of the repo
4. Copy down \\<internal share>\public\<my folder>\Repros\SolutionCrawlerBug\Tests
5. Delete .vs folder for the solution before each repro attempt
6. Launch devenv /rootsuffix SourceBasedTestDiscovery
7. Open Test Explorer window
8. Open Output pane
9. Open Tests.sln

**Expected Behavior**:
Real time unit test discovery (which uses Roslyn)  should discover 11 tests in the TW once the solution completes loading

**Actual Behavior**:
Real time discovery discovers less than 11 tests (most often just 8, sometime 5)

**Root Cause**:
Looks like solution crawler is not calling the real time test discovery analyzer for all ‘versions’ of all files. With the logging I added in the above bugrepro branch, I see the following text in the “Tests” tab of the Output window.

```
[10/8/2018 8:13:37 PM Informational] Called for MSTestTests::UnitTest1.cs (workspace version: 7)
[10/8/2018 8:13:38 PM Informational] Called for MSTestTests::.NETCoreApp,Version=v2.1.AssemblyAttributes.cs (workspace version: 513)
[10/8/2018 8:13:38 PM Informational] Called for MSTestTests::MSTestTests.AssemblyInfo.cs (workspace version: 513)
[10/8/2018 8:13:38 PM Informational] Called for MSTestTests::TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs (workspace version: 513)
[10/8/2018 8:13:38 PM Informational] Called for MSTestTests::TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs (workspace version: 513)
[10/8/2018 8:13:38 PM Informational] Called for MSTestTests::MSTestTests.Program.cs (workspace version: 513)
[10/8/2018 8:13:38 PM Informational] Called for MSTestTests::TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs (workspace version: 513)
[10/8/2018 8:13:38 PM Informational] Called for NUnitTests::UnitTest1.cs (workspace version: 513)
[10/8/2018 8:13:38 PM Informational] Called for NUnitTests::NUnitTests.Program.cs (workspace version: 513)
[10/8/2018 8:13:38 PM Informational] Called for NUnitTests::.NETCoreApp,Version=v2.0.AssemblyAttributes.cs (workspace version: 513)
[10/8/2018 8:13:38 PM Informational] Called for NUnitTests::NUnitTests.AssemblyInfo.cs (workspace version: 513)
[10/8/2018 8:13:38 PM Informational] Called for xUnitTests::UnitTest1.cs (workspace version: 513)
[10/8/2018 8:13:38 PM Informational] Called for xUnitTests::.NETCoreApp,Version=v2.1.AssemblyAttributes.cs (workspace version: 513)
[10/8/2018 8:13:38 PM Informational] Called for xUnitTests::TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs (workspace version: 513)
[10/8/2018 8:13:38 PM Informational] Called for xUnitTests::TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs (workspace version: 513)
[10/8/2018 8:13:38 PM Informational] Called for xUnitTests::xUnitTests.Program.cs (workspace version: 513)
[10/8/2018 8:13:38 PM Informational] Called for xUnitTests::TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs (workspace version: 513)
[10/8/2018 8:13:38 PM Informational] Called for xUnitTests::xUnitTests.AssemblyInfo.cs (workspace version: 513)
```

As you can see from the above log, the analyzer is never being called for the first MSTestsTests::UnitTest1.cs document at the stable workspace version 513. The analyzer is being told about this document at workspace version 7 - however, the document does not contain all nuget metadata references at workspace version 7 – mstest framework reference is missing – so the analyzer can’t discover the tests at this version. The references are present in version 513, but since solution crawler never calls us for this version of the MSTestsTests::UnitTest1.cs document, we never discover the tests.

The analyzer is being registered via ISolutionCrawlerRegistrationService.AddAnalyzerProvider(). Not sure if there is some race that causes document versions to be missed if we register while solution is still changing after solution load?

**Caveats**:
1. I am able to repro this consistently with above steps on a 2 core VM where @vsccarl originally reported the problem. I haven’t run into this on any other machine yet. In case you are unable to repro on regular dev machine, you can use the same machine to debug. Please ping me offline for machine details.
2. The problem will not repro if I don’t delete .vs folder. (In this case looks like solution crawler only tells SBD analyzer about one version of all documents and this version has all required nuget metadata references.)

### PR DESCRIPTION
**Pull request by heejaechang**
…cess.

race is this.

1. solution crawler picked up a solution
2. before processing the solution, workitem got changed
3. and then picked up an work item from the queue
4. and use the work item with the solution that got picked up in step 1

step 2 is happening beacuse solution has changed, but step 4 used old solution from step 1
that doesn't have effects of the solution changes.

solution crawler must pick up solution after it has picked up work item from the queue so that new changes of a solution get enqueued as new work item,

fix #30420

### CODE REVIEW

**Comment by heejaechang** [comment]
@shyamnamboodiripad this should fix the issue you were having on source based discovery. do you have a bug for it?

**Comment by heejaechang** [comment]
tagging @dotnet/roslyn-ide @mavasani 

tagging @jinujoseph for preview 2

File: src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs [hunk 1]
```diff
@@ -309,12 +306,31 @@ private async Task ProcessDocumentAsync(ImmutableArray<IIncrementalAnalyzer> ana
...
 
+                        // we should always use solution snapshot after workitem is removed from the queue.
+                        // otherwise, we can have a race such as below.
+                        //
+                        // 1.solution crawler picked up a solution
+                        // 2.before processing the solution, an workitem got changed
+                        // 3.and then the work item got picked up from the queue
+                        // 4.and use the work item with the solution that got picked up in step 1
+                        // 
+                        // step 2 is happening beacuse solution has changed, but step 4 used old solution from step 1
```
Comment (Therzok) [inline src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs]:
```suggestion
                        // step 2 is happening because solution has changed, but step 4 used old solution from step 1
```

File: src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs [hunk 2]
```diff
@@ -441,40 +457,31 @@ private static void RemoveDocument(ImmutableArray<IIncrementalAnalyzer> analyzer
...
 
-                            _processingSolution = currentSolution;
+                            ResetLogAggregatorIfNeeded();
 
                             // synchronize new solution to OOP
                             await currentSolution.Workspace.SynchronizePrimaryWorkspaceAsync(currentSolution, this.CancellationToken).ConfigureAwait(false);
 
-                            await RunAnalyzersAsync(this.Analyzers, currentSolution, (a, s, c) => a.NewSolutionSnapshotAsync(s, c), this.CancellationToken).ConfigureAwait(false);
+                            // always run analyzers with latest solution
+                            await RunAnalyzersAsync(this.Analyzers, this.Processor.CurrentSolution, (a, s, c) => a.NewSolutionSnapshotAsync(s, c), this.CancellationToken).ConfigureAwait(false);
```
Comment (mavasani) [inline src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs]: >this.Processor.CurrentSolution [](start = 68, length = 30)

So solution snapshot used here could be different from the one used for `SynchronizePrimaryWorkspaceAsync` invocation above?

File: src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs [hunk 3]
```diff
@@ -441,40 +457,31 @@ private static void RemoveDocument(ImmutableArray<IIncrementalAnalyzer> analyzer
...
-                        }
-
-                        SolutionCrawlerLogger.LogIncrementalAnalyzerProcessorStatistics(
-                            this.Processor._registration.CorrelationId, _processingSolution, this.Processor._logAggregator, this.Analyzers);
-
-                        this.Processor.ResetLogAggregator();
-                    }
+                   // this is only used in ResetState to find out solution has changed
+                   // and reset some states
+                    private Solution _lastSolution = null;
```
Comment (genlu) [inline src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs]: nit: Move private field to the top of type definition

File: src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs (hunk 2 above)
Comment (genlu) [inline src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs]: If the current solution is different than `currentSolution`, would this cause OOP to not receive update or update being delayed?

File: src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs (hunk 3 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs]: can this explanation be expanded on.  IT tells me 'what', but not 'why'.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs]: can we document threading expectations here?  Is this field used across multiple threads?

File: src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs [hunk 4]
```diff
@@ -487,13 +494,28 @@ private async Task ResetStatesAsync()
                         {
                             throw ExceptionUtilities.Unreachable;
                         }
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs]: this catch seems to broadly cover a lot of code. can it be narrowed to only a specific region of code we're trying to protect?

File: src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs [hunk 5]
```diff
@@ -441,40 +457,31 @@ private static void RemoveDocument(ImmutableArray<IIncrementalAnalyzer> analyzer
...
+                            _lastSolution = currentSolution;
 
-                            _processingSolution = currentSolution;
+                            ResetLogAggregatorIfNeeded();
 
                             // synchronize new solution to OOP
                             await currentSolution.Workspace.SynchronizePrimaryWorkspaceAsync(currentSolution, this.CancellationToken).ConfigureAwait(false);
 
-                            await RunAnalyzersAsync(this.Analyzers, currentSolution, (a, s, c) => a.NewSolutionSnapshotAsync(s, c), this.CancellationToken).ConfigureAwait(false);
+                            // always run analyzers with latest solution
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs]: 1. i dont' really understand this comment.  
2. we already assigned `this.Processor.CurrentSolution` above, can we not use that?  If not, why not?

File: src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs (hunk 2 above)
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs]: varirables 'a', 's', and 'c' are not clear.

File: src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs [hunk 6]
```diff
@@ -487,13 +494,28 @@ private async Task ResetStatesAsync()
...
                             throw ExceptionUtilities.Unreachable;
                         }
+
+                        void ResetLogAggregatorIfNeeded()
+                        {
+                            if (currentSolution == null || oldSolution == null ||
+                                currentSolution.Id == oldSolution.Id)
+                            {
+                                return;
+                            }
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs]: can we add some explanatory comments?

**Comment by CyrusNajmabadi** [comment]
> race is this.

Could we simplify things by just having the work-item point to the solution it corresponds to?  Or pair the workitem and solution together?  That way we don't have two things that shouldbe in sync have hte potential of getting out of sync.

File: src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs (hunk 2 above)
Comment (heejaechang) [reply src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs]: what SynchronizePrimaryWorkspace doesn't matter what solution being used since that's just a call to pre-emptively send solution to OOP. 

I can make it to use CurrentSolution or add some comment on what it is doing.

File: src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs (hunk 3 above)
Comment (heejaechang) [reply src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs]: that field is supposed to be used only in ResetState, that's why I moved here, but sure, I can move it back up to the top.

sure, I can add why part as well.

File: src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs (hunk 2 above)
Comment (heejaechang) [reply src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs]: OOP will pull solution when it needs, it just pre-populate OOP with new data so that actual call can be done more quickly. so it doesn't actually matter what solution it is pushing much. but we can change it to CurrentSolution if that is less confusing or add comments.

File: src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs (hunk 5 above)
Comment (heejaechang) [reply src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs]: current solution could have changed since it is assigned to local. so, I want to always use latest solution.

File: src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs (hunk 4 above)
Comment (heejaechang) [reply src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs]: it is fatal watson. catch is here since we wanted to have fatal watson without await magic thing wrapped actual exception.

**Comment by heejaechang** [comment]
the bug it is fixing is issue @shyamnamboodiripad found during his source based discovery testing on slow machine on VS start up. Shyam, do you have a bug for it? @jinujoseph so, do you need a bug to take a PR?

**Comment by jinujoseph** [comment]
isn't it this one https://github.com/dotnet/roslyn/issues/30420 ? 
@heejaechang , to answer your question , Not all PR needs a bug (atleast at this point ) but its a good practice to connect with the bug so we understand and have right context for the fix.

**Comment by heejaechang** [comment]
when closing solution, old solution is not null. when VS shutdown, it has other code path to log telemetry. also, that code has not been changed in this PR.

**Comment by CyrusNajmabadi** [comment]
> when closing solution, old solution is not null.

Right.  I was talking about the case where oldSolution is *non-null*, but currentSolution is null.  I'm basically trying to mentally enumerate the different cases in this check to see if there's an issue to be concerned about:

```c#
                           if (currentSolution == null || oldSolution == null ||
                                currentSolution.Id == oldSolution.Id)
                            {
```

File: src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs (hunk 2 above)
Comment (genlu) [reply src/Features/Core/Portable/SolutionCrawler/WorkCoordinator.NormalPriorityProcessor.cs]: Either way would be fine.

**Comment by genlu** [comment]
> Could we simplify things by just having the work-item point to the solution it corresponds to? Or pair the workitem and solution together? That way we don't have two things that shouldbe in sync have hte potential of getting out of sync.

I like this, unless there's perf benefit by using latest snapshot.

File: src/VisualStudio/Core/Def/Implementation/Remote/RemoteSolutionPopulatorProvider.cs [hunk 7]
```diff
@@ -0,0 +1,34 @@
...
+    internal class RemoteSolutionPopulatorProvider : IIncrementalAnalyzerProvider
+    {
+        public IIncrementalAnalyzer CreateIncrementalAnalyzer(Workspace workspace)
+        {
+            return new RemoteSolutionPopulator();
+        }
+
+        private class RemoteSolutionPopulator : IncrementalAnalyzerBase
+        {
+            public override Task NewSolutionSnapshotAsync(Solution solution, CancellationToken cancellationToken)
```
Comment (mavasani) [inline src/VisualStudio/Core/Def/Implementation/Remote/RemoteSolutionPopulatorProvider.cs]: >NewSolutionSnapshotAsync [](start = 33, length = 24)

Thanks, much cleaner!

**Comment by heejaechang** [comment]
@jinujoseph can I get approval?
