### PR TITLE
Fix for #7840: add missing check for DynamicAttribute type

### LINKED ISSUE #7840: Missing check for an ability to emit DynamicAttribute in SynthesizedFieldSymbolBase.AddSynthesizedAttributes
Note the assumption comment in the code below. I believe the assumption is incorrect. For example, a dynamic local, for which we don't verify the presence of the attributes, can become a field in a lambda closure.  
```
            if (this.Type.TypeSymbol.ContainsDynamic())
            {
                // Assume that someone checked earlier that the attribute ctor is available and has no use-site errors.
                AddSynthesizedAttribute(ref attributes, compilation.SynthesizeDynamicAttribute(this.Type.TypeSymbol, this.Type.CustomModifiers.Length));
            }
```

 I think this code should use the same logic that is used by SynthesisedParameterSymbol.AddSynthesizedAttributes at the moment.

### PR DESCRIPTION
**Pull request by jcouv**
Adding missing check to verify the DynamicAttribute type is present.

Technically, this can't be hit right now because either this is in a context where DynamicAttribute was already needed for something else, or you can't reach this point (because of check on line 41).

For validation, I had to disable the check on line 41 and I used this [unittest](https://gist.github.com/jcouv/03517507739c74165336).

Fixes #7840.

CC @dotnet/roslyn-compiler

### CODE REVIEW

**Comment by jcouv** [comment]
CC @dotnet/roslyn-compiler for code review.

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedFieldSymbolBase.cs [hunk 1]
```diff
@@ -45,13 +45,10 @@ internal override void AddSynthesizedAttributes(ModuleCompilationState compilati
...
 
-            // Assume that someone checked earlier that the attribute ctor is available and has no use-site errors.
             AddSynthesizedAttribute(ref attributes, compilation.TrySynthesizeAttribute(WellKnownMember.System_Runtime_CompilerServices_CompilerGeneratedAttribute__ctor));
 
-            // TODO (tomat): do we need to emit dynamic attribute on any synthesized field?
-            if (this.Type.ContainsDynamic())
+            if (this.Type.ContainsDynamic() && compilation.HasDynamicEmitAttributes())
             {
-                // Assume that someone checked earlier that the attribute ctor is available and has no use-site errors.
                 AddSynthesizedAttribute(ref attributes, compilation.SynthesizeDynamicAttribute(this.Type, customModifiersCount: 0));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedFieldSymbolBase.cs]: I think we should also fix the customModifiersCount on this call. We shouldn't assume it is always 0, we should get the actual value from the symbol..

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedFieldSymbolBase.cs [hunk 2]
```diff
@@ -45,13 +45,10 @@ internal override void AddSynthesizedAttributes(ModuleCompilationState compilati
 
             CSharpCompilation compilation = this.DeclaringCompilation;
 
-            // Assume that someone checked earlier that the attribute ctor is available and has no use-site errors.
             AddSynthesizedAttribute(ref attributes, compilation.TrySynthesizeAttribute(WellKnownMember.System_Runtime_CompilerServices_CompilerGeneratedAttribute__ctor));
 
-            // TODO (tomat): do we need to emit dynamic attribute on any synthesized field?
-            if (this.Type.ContainsDynamic())
+            if (this.Type.ContainsDynamic() && compilation.HasDynamicEmitAttributes())
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedFieldSymbolBase.cs]: This check is not complete, see similar method in SynthesizedParameterSymbol, it also checks goodness of a boolean type. Perhaps that check should be moved to HasDynamicEmitAttributes.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/SynthesizedFieldSymbolBase.cs]: Given how HasDynamicEmitAttributes is used in BinderSymbols, modifying it wouldn't be a good idea, but we can create another helper.

**Comment by jcouv** [comment]
@dotnet/roslyn-compiler, @AlekseyTs, please code review when you have some time.

**Comment by AlekseyTs** [comment]
LGTM

**Comment by jcouv** [comment]
@dotnet/roslyn-compiler A second review would be much appreciated. Thanks

**Comment by cston** [comment]
LGTM
