### PR TITLE
Ensure nullability mismatch in implemented interface types is treated as a warning.

### LINKED ISSUE #31858: Many errors reported when enabling nullable reference types
**Version Used**: Microsoft.Net.Compilers 3.0.0-beta2-18616-01

🔗 https://github.com/tunnelvisionlabs/dotnet-trees/pull/65
🔗 https://ci.appveyor.com/project/sharwell/dotnet-trees/builds/21060162

**Steps to Reproduce**:

tunnelvisionlabs/dotnet-trees#65

**Expected Behavior**:

The project compiles, with zero or more new warnings related to nullable reference types reported.

**Actual Behavior**:

The project does not compile. The reported errors appear to be unrelated to nullable reference types.

```
1>SortedTreeDictionary`2.cs(89,14,89,53): error CS0540: 'SortedTreeDictionary<TKey, TValue>.ICollection<KeyValuePair<TKey, TValue>>.IsReadOnly': containing type does not implement interface 'ICollection<KeyValuePair<TKey, TValue>>'
1>TreeDictionary`2.cs(89,14,89,53): error CS0540: 'TreeDictionary<TKey, TValue>.ICollection<KeyValuePair<TKey, TValue>>.IsReadOnly': containing type does not implement interface 'ICollection<KeyValuePair<TKey, TValue>>'
1>TreeDictionary`2.cs(187,14,187,53): error CS0540: 'TreeDictionary<TKey, TValue>.ICollection<KeyValuePair<TKey, TValue>>.Add(KeyValuePair<TKey, TValue>)': containing type does not implement interface 'ICollection<KeyValuePair<TKey, TValue>>'
1>TreeDictionary`2.cs(189,14,189,53): error CS0540: 'TreeDictionary<TKey, TValue>.ICollection<KeyValuePair<TKey, TValue>>.Contains(KeyValuePair<TKey, TValue>)': containing type does not implement interface 'ICollection<KeyValuePair<TKey, TValue>>'
1>SortedTreeDictionary`2.cs(191,14,191,53): error CS0540: 'SortedTreeDictionary<TKey, TValue>.ICollection<KeyValuePair<TKey, TValue>>.Add(KeyValuePair<TKey, TValue>)': containing type does not implement interface 'ICollection<KeyValuePair<TKey, TValue>>'
1>SortedTreeDictionary`2.cs(193,14,193,53): error CS0540: 'SortedTreeDictionary<TKey, TValue>.ICollection<KeyValuePair<TKey, TValue>>.Contains(KeyValuePair<TKey, TValue>)': containing type does not implement interface 'ICollection<KeyValuePair<TKey, TValue>>'
1>SortedTreeDictionary`2.cs(199,14,199,53): error CS0540: 'SortedTreeDictionary<TKey, TValue>.ICollection<KeyValuePair<TKey, TValue>>.CopyTo(KeyValuePair<TKey, TValue>[], int)': containing type does not implement interface 'ICollection<KeyValuePair<TKey, TValue>>'
1>TreeDictionary`2.cs(195,14,195,53): error CS0540: 'TreeDictionary<TKey, TValue>.ICollection<KeyValuePair<TKey, TValue>>.CopyTo(KeyValuePair<TKey, TValue>[], int)': containing type does not implement interface 'ICollection<KeyValuePair<TKey, TValue>>'
1>SortedTreeDictionary`2.cs(201,49,201,88): error CS0540: 'SortedTreeDictionary<TKey, TValue>.IEnumerable<KeyValuePair<TKey, TValue>>.GetEnumerator()': containing type does not implement interface 'IEnumerable<KeyValuePair<TKey, TValue>>'
1>TreeDictionary`2.cs(197,49,197,88): error CS0540: 'TreeDictionary<TKey, TValue>.IEnumerable<KeyValuePair<TKey, TValue>>.GetEnumerator()': containing type does not implement interface 'IEnumerable<KeyValuePair<TKey, TValue>>'
1>SortedTreeDictionary`2.cs(207,14,207,53): error CS0540: 'SortedTreeDictionary<TKey, TValue>.ICollection<KeyValuePair<TKey, TValue>>.Remove(KeyValuePair<TKey, TValue>)': containing type does not implement interface 'ICollection<KeyValuePair<TKey, TValue>>'
1>TreeDictionary`2.cs(203,14,203,53): error CS0540: 'TreeDictionary<TKey, TValue>.ICollection<KeyValuePair<TKey, TValue>>.Remove(KeyValuePair<TKey, TValue>)': containing type does not implement interface 'ICollection<KeyValuePair<TKey, TValue>>'
1>SortedTreeDictionary`2.cs(13,63,13,88): error CS0535: 'SortedTreeDictionary<TKey, TValue>' does not implement interface member 'ICollection<KeyValuePair<TKey, TValue>>.Add(KeyValuePair<TKey, TValue>)'
1>SortedTreeDictionary`2.cs(13,63,13,88): error CS0535: 'SortedTreeDictionary<TKey, TValue>' does not implement interface member 'ICollection<KeyValuePair<TKey, TValue>>.Contains(KeyValuePair<TKey, TValue>)'
1>SortedTreeDictionary`2.cs(13,63,13,88): error CS0535: 'SortedTreeDictionary<TKey, TValue>' does not implement interface member 'ICollection<KeyValuePair<TKey, TValue>>.CopyTo(KeyValuePair<TKey, TValue>[], int)'
1>SortedTreeDictionary`2.cs(13,63,13,88): error CS0535: 'SortedTreeDictionary<TKey, TValue>' does not implement interface member 'ICollection<KeyValuePair<TKey, TValue>>.Remove(KeyValuePair<TKey, TValue>)'
1>SortedTreeDictionary`2.cs(13,63,13,88): error CS0535: 'SortedTreeDictionary<TKey, TValue>' does not implement interface member 'ICollection<KeyValuePair<TKey, TValue>>.IsReadOnly'
1>SortedTreeDictionary`2.cs(13,63,13,88): error CS0738: 'SortedTreeDictionary<TKey, TValue>' does not implement interface member 'IEnumerable<KeyValuePair<TKey, TValue>>.GetEnumerator()'. 'SortedTreeDictionary<TKey, TValue>.GetEnumerator()' cannot implement 'IEnumerable<KeyValuePair<TKey, TValue>>.GetEnumerator()' because it does not have the matching return type of 'IEnumerator<KeyValuePair<TKey, TValue>>'.
1>TreeDictionary`2.cs(13,57,13,82): error CS0535: 'TreeDictionary<TKey, TValue>' does not implement interface member 'ICollection<KeyValuePair<TKey, TValue>>.Add(KeyValuePair<TKey, TValue>)'
1>TreeDictionary`2.cs(13,57,13,82): error CS0535: 'TreeDictionary<TKey, TValue>' does not implement interface member 'ICollection<KeyValuePair<TKey, TValue>>.Contains(KeyValuePair<TKey, TValue>)'
1>TreeDictionary`2.cs(13,57,13,82): error CS0535: 'TreeDictionary<TKey, TValue>' does not implement interface member 'ICollection<KeyValuePair<TKey, TValue>>.CopyTo(KeyValuePair<TKey, TValue>[], int)'
1>TreeDictionary`2.cs(13,57,13,82): error CS0535: 'TreeDictionary<TKey, TValue>' does not implement interface member 'ICollection<KeyValuePair<TKey, TValue>>.Remove(KeyValuePair<TKey, TValue>)'
1>TreeDictionary`2.cs(13,57,13,82): error CS0535: 'TreeDictionary<TKey, TValue>' does not implement interface member 'ICollection<KeyValuePair<TKey, TValue>>.IsReadOnly'
1>TreeDictionary`2.cs(13,57,13,82): error CS0738: 'TreeDictionary<TKey, TValue>' does not implement interface member 'IEnumerable<KeyValuePair<TKey, TValue>>.GetEnumerator()'. 'TreeDictionary<TKey, TValue>.GetEnumerator()' cannot implement 'IEnumerable<KeyValuePair<TKey, TValue>>.GetEnumerator()' because it does not have the matching return type of 'IEnumerator<KeyValuePair<TKey, TValue>>'.
```

When I add `ICollection<KeyValuePair<TKey, TValue>>` explicitly to the set of interfaces for the two types reporting these errors, the output changes but still fails:

```
1>SortedTreeDictionary`2+Enumerator.cs(10,26,10,46): error CS0695: 'SortedTreeDictionary<TKey, TValue>' cannot implement both 'IEnumerable<KeyValuePair<TKey, TValue>>' and 'IEnumerable<KeyValuePair<TKey, TValue>>' because they may unify for some type parameter substitutions
1>SortedTreeDictionary`2+Enumerator.cs(10,26,10,46): error CS0695: 'SortedTreeDictionary<TKey, TValue>' cannot implement both 'ICollection<KeyValuePair<TKey, TValue>>' and 'ICollection<KeyValuePair<TKey, TValue>>' because they may unify for some type parameter substitutions
1>TreeDictionary`2+Enumerator.cs(10,26,10,40): error CS0695: 'TreeDictionary<TKey, TValue>' cannot implement both 'IEnumerable<KeyValuePair<TKey, TValue>>' and 'IEnumerable<KeyValuePair<TKey, TValue>>' because they may unify for some type parameter substitutions
1>TreeDictionary`2+Enumerator.cs(10,26,10,40): error CS0695: 'TreeDictionary<TKey, TValue>' cannot implement both 'ICollection<KeyValuePair<TKey, TValue>>' and 'ICollection<KeyValuePair<TKey, TValue>>' because they may unify for some type parameter substitutions
```

### LINKED ISSUE #31974: C# compiler fails to detect duplicate explicit implementation for the same member, an invalid assembly is emitted
```
namespace Ns1
{
    public interface I1<I1T1>
    {
        void M();
    }

    public class C0<ST1, ST2>
    { }

    public interface I2<I2T1, I2T2> : I1<C0<I2T1, I2T2>>
    {
    }

    class C1<C1T1, C1T2> : I2<C1T1, C1T2>
    {
        void I1<C0<C1T1, C1T2>>.M()
        {
        }

        void global::Ns1.I1<C0<C1T1, C1T2>>.M()
        {
        }
    }
}
```

Observed:
No compilation errors.
```
Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

[MD]: Error: MethodImpl has a duplicate (rid=0x00000002). [token:0x19000001]
```

Expected:
A compilation error. For example,  ```c:\Windows\Microsoft.NET\Framework\v4.0.30319\csc``` reports
```
error CS0111: Type 'Ns1.C1<C1T1,C1T2>' already defines a member called 'global::Ns1.I1<...>.M' with the same parameter types
```
Probably a special error would be better.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #31974
Related to #30655, fixes for C#
Related to #31977, fixes for C#
Fixes #31858

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@cston, @jcouv, @333fred Please review

**Comment by jcouv** [comment]
Looking now

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/MetadataDecoder.cs [hunk 1]
```diff
@@ -515,8 +515,8 @@ internal override Symbol GetSymbolForMemberRef(MemberReferenceHandle memberRef,
                 HashSet<DiagnosticInfo> useSiteDiagnostics = null;
                 if (!TypeSymbol.Equals(scope, targetTypeSymbol, TypeCompareKind.ConsiderEverything2) &&
                     !(targetTypeSymbol.IsInterfaceType()
-                        ? scope.AllInterfacesNoUseSiteDiagnostics.IndexOf((NamedTypeSymbol)targetTypeSymbol, 0, TypeSymbol.EqualsIgnoringNullableComparer) != -1
-                        : scope.IsDerivedFrom(targetTypeSymbol, TypeCompareKind.IgnoreNullableModifiersForReferenceTypes, useSiteDiagnostics: ref useSiteDiagnostics)))
+                        ? scope.AllInterfacesNoUseSiteDiagnostics.IndexOf((NamedTypeSymbol)targetTypeSymbol, 0, TypeSymbol.EqualsAllIgnoreOptionsPlusCustomModifiersAndArraySizesAndLowerBounds) != -1
+                        : scope.IsDerivedFrom(targetTypeSymbol, TypeCompareKind.AllIgnoreOptions & ~TypeCompareKind.IgnoreCustomModifiersAndArraySizesAndLowerBounds, useSiteDiagnostics: ref useSiteDiagnostics)))
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/MetadataDecoder.cs]: >TypeCompareKind.AllIgnoreOptions & ~TypeCompareKind.IgnoreCustomModifiersAndArraySizesAndLowerBounds [](start = 64, length = 100)

Consider giving this option a name. I think it corresponds to the notion of runtime type equality, is that right?

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/MetadataDecoder.cs [hunk 2]
```diff
@@ -515,8 +515,8 @@ internal override Symbol GetSymbolForMemberRef(MemberReferenceHandle memberRef,
                 HashSet<DiagnosticInfo> useSiteDiagnostics = null;
                 if (!TypeSymbol.Equals(scope, targetTypeSymbol, TypeCompareKind.ConsiderEverything2) &&
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/MetadataDecoder.cs]: >TypeCompareKind.ConsiderEverything2 [](start = 64, length = 35)

while you're here, consider fixing this TypeCompareKind

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs [hunk 3]
```diff
@@ -22873,6 +23317,105 @@ class Derived2 : Base, I<(int a, int b)>
                 );
         }
 
+        [Fact]
+        [WorkItem(14841, "https://github.com/dotnet/roslyn/issues/14841")]
+        public void ExplicitBaseImplementationNotConsideredImplementationForInterfaceWithDifferentTupleNames_02()
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: >ExplicitBaseImplementationNotConsideredImplementationForInterfaceWithDifferentTupleNames_02 [](start = 20, length = 91)

Looks like a new error (compat issue). It would be good to dig up the latest LDM notes on the topic. If I recall, the previous behavior was intentional.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 4]
```diff
@@ -6931,6 +6931,884 @@ class B3 : IA3
...
+        var x = (C1)new C2();
+        var y = (I1<A>)x;
+        y.M1();
+        y.M2();
+    }
+}
+";
+            var comp = CreateCompilation(source, options: WithNonNullTypesTrue(TestOptions.DebugExe));
+            comp.VerifyDiagnostics(
+                // (17,23): warning CS8644: 'C2' does not implement interface member 'I1<A>.M2()'. Nullability of reference types in interface implemented by the base type doesn't match.
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >'C2' does not implement interface member 'I1<A>.M2()'. [](start = 44, length = 54)

nit: Perhaps the message should say that the member is "implemented with incorrect nullability" instead. "Does not implement" sounds like it should be an error.

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/MetadataDecoder.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Metadata/PE/MetadataDecoder.cs]: > while you're here, consider fixing this TypeCompareKind

Fixing often requires thinking if the kind should be changed and adding tests proving one or the other. I prefer to not include this work into the current PR.

---
In reply to: [244437039](https://github.com/dotnet/roslyn/pull/32041#discussion_r244437039) [](ancestors = 244437039)

File: src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs [hunk 5]
```diff
@@ -65,7 +70,7 @@ private class InterfaceInfo
             }
 
             // key = interface method/property/event, value = explicitly implementing method/property/event declared on this type
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/TypeSymbol.cs]: >// key = interface method/property/event, value = explicitly implementing method/property/event declared on this type [](start = 12, length = 117)

Should this comment be updated?

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs (hunk 3 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: There is no intent to change language rules here. There was a bug that compiler picked ```public (int notA, int notB) M() { return (1, 2); }``` as an implicit implementation for the interface, but that is incorrect because for CLR tuple names do not matter and explicit implementation takes priority. The behavior should be similar to one in
ExplicitBaseImplementationNotConsideredImplementationForInterfaceWithDifferentTupleNames_01

---
In reply to: [244438573](https://github.com/dotnet/roslyn/pull/32041#discussion_r244438573) [](ancestors = 244438573)

**Comment by AlekseyTs** [comment]
@cston, @333fred Please review

**Comment by AlekseyTs** [comment]
@cston, @333fred Please review

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs [hunk 6]
```diff
@@ -18973,6 +18974,446 @@ public class C5<T, U> : I0<(int a, int b)>, I0<(T notA, U notB)> { }
...
+        [WorkItem(31977, "https://github.com/dotnet/roslyn/issues/31977")]
+        public void DuplicateInterfaceDetectionWithDifferentTupleNames_05()
+        {
+            var source = @"
+public interface I1<T> 
+{
+    void M();
+}
+
+public class C3<T, U> : I1<(T a, T b)>, I1<(U c, U d)>
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: What happens in the case where `T` and `U` have constraints that prevent this from happening? ie `T` is constrained to `class` and `U` is constrained to `struct`?

Comment (333fred) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: And by "this", I mean the error below.

---
In reply to: [245091217](https://github.com/dotnet/roslyn/pull/32041#discussion_r245091217) [](ancestors = 245091217)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: > What happens in the case where T and U have constraints that prevent this from happening? ie T is constrained to class and U is constrained to struct?

Constraints and unification are orthogonal, I think. In any case, I do not believe this PR changes behavior in this area. 

---
In reply to: [245092033](https://github.com/dotnet/roslyn/pull/32041#discussion_r245092033) [](ancestors = 245092033,245091217)

File: src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs [hunk 7]
```diff
@@ -7653,5 +7639,149 @@ public class B : A
 }";
             CreateCompilation(source).VerifyDiagnostics();
         }
+
+        [Fact]
+        [WorkItem(31974, "https://github.com/dotnet/roslyn/issues/31974")]
+        public void Issue31974()
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs]: Please add a note in docs/CSharp/Compiler Breaking Changes - VS2019.md

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs]: > Please add a note in docs/compilers/CSharp/Compiler Breaking Changes - VS2019.md

I don't think this is a breaking change, this is a bug fix for producing an invalid assembly and for a regression from native compiler

---
In reply to: [245095253](https://github.com/dotnet/roslyn/pull/32041#discussion_r245095253) [](ancestors = 245095253)

Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs]: It is a regression from the native compiler, but everyone is on roslyn now, and it _is_ technically a breaking change.

---
In reply to: [245096054](https://github.com/dotnet/roslyn/pull/32041#discussion_r245096054) [](ancestors = 245096054,245095253)

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol_Bases.cs [hunk 8]
```diff
@@ -133,24 +133,34 @@ protected override void CheckInterfaces(DiagnosticBag diagnostics)
...
-                            diagnostics.Add(ErrorCode.ERR_DuplicateInterfaceWithTupleNamesInBaseList, location, @interface, other, this);
-                        }
-                        else
+                        @interface.CheckAllConstraints(conversions, location, diagnostics);
+                    }
+
+                    if (set.Count > 1)
+                    {
+                        NamedTypeSymbol other = null;
+                        foreach (var @interface in set)
```
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol_Bases.cs]: > Can we not merge these loops so we can avoid looping through the set twice?

I guess we could, but we had two loops before this change. I do not see much benefit in optimizing for an error case, we are not going to get here otherwise. Let me know if you still want me to refactor the code 

---
In reply to: [245106096](https://github.com/dotnet/roslyn/pull/32041#discussion_r245106096) [](ancestors = 245106096)

[the remark this answers is not in the document]
Comment (333fred) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol_Bases.cs]: It's fine, it was just a thought I had as I was reading the method.

---
In reply to: [245111937](https://github.com/dotnet/roslyn/pull/32041#discussion_r245111937) [](ancestors = 245111937,245106096)
