### PR TITLE
Clarify behavior when RunServerCompilation throws an exception

### LINKED ISSUE #7866: Figure out what should be done in response to exceptions from RunServerCompilation and HandleResponse in BuildClient
See https://github.com/dotnet/roslyn/pull/7841

### PR DESCRIPTION
**Pull request by jaredpar**
A question was raised about the behavior of the compiler when RunServerCompilation throws an exception. After looking through the code I decided the approach most consistent with our existing code is:

1. Stop using `null` as a valid value in this API.  If the client determines it can't make the call use the Rejected coede.
2. Gracefully handle case where Task is faulted.  This puts the IO handling in a single place.
3. If the compilation could not complete on the server, for whatever reason, always fall back to local compilation.

closes #7866

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-compiler

**Comment by AlekseyTs** [comment]
LGTM

**Comment by jaredpar** [comment]
@dotnet/roslyn-compiler can I get one more review please.

File: src/Compilers/Core/CommandLine/BuildClient.cs [hunk 1]
```diff
@@ -149,36 +136,65 @@ public Task<RunCompilationResult> RunCompilationAsync(IEnumerable<string> origin
...
+                    CancellationToken.None);
+                buildResponse = buildResponseTask.Result;
+
+                Debug.Assert(buildResponse != null);
+                if (buildResponse == null)
+                {
+                    return null;
+                }
+            }
+            catch (Exception)
```
Comment (agocke) [inline src/Compilers/Core/CommandLine/BuildClient.cs]: Why not just `catch`? Don't want to catch objects?

File: src/Compilers/Core/CommandLine/BuildClient.cs [hunk 2]
```diff
@@ -149,36 +136,65 @@ public Task<RunCompilationResult> RunCompilationAsync(IEnumerable<string> origin
...
                 case BuildResponse.ResponseType.Rejected:
                 case BuildResponse.ResponseType.AnalyzerInconsistency:
-                    var exitCode = RunLocalCompilation(arguments, buildPaths, textWriter);
-                    return new RunCompilationResult(exitCode);
-
+                    // Build could not be completed on the server.
+                    return null;
                 default:
-                    throw new InvalidOperationException("Encountered unknown response type");
+                    // Will not happen with our server but hypothetically could be sent by a rouge server.  Should
```
Comment (agocke) [inline src/Compilers/Core/CommandLine/BuildClient.cs]: Why are the rouge servers any worse than regular servers? Got something against the color red?

**Comment by agocke** [comment]
:+1:

File: src/Compilers/Core/CommandLine/BuildClient.cs (hunk 2 above)
Comment (jaredpar) [inline src/Compilers/Core/CommandLine/BuildClient.cs]: I'm such a bad speller ...

File: src/Compilers/Core/CommandLine/BuildClient.cs (hunk 1 above)
Comment (jaredpar) [inline src/Compilers/Core/CommandLine/BuildClient.cs]: I did give this some consideration and looking through Roslyn it seems we are a bit inconsistent with our `catch` usage in this area.  In general it shouldn't be a problem since the runtime defaults to converting objects to an exception type.  In theory though we could be run in an environment which didn't wrap object in exception and actually threw one via an extensibility point. Eventually I decided that was a bit extreme.  Willing to be convinced otherwise.
