### PR TITLE
Port Rename and Formatting tests to the new framework

### LINKED ISSUE #18065: Shift-Enter commits completion, but doesn't complete the current statement
**Version Used**: VS2015 and VS2017

**Steps to Reproduce**:

1. Paste C# code:
```C#
class Program
{
    static void Main(string[] args)
    {
        Main
    }
}
```
2. Type `(ar`
3. The completion list should be up with "args" selected
4. Type <kbd>Shift</kbd>+<kbd>Enter</kbd>

**Expected Behavior**: Completion is committed, and the current statement is completed (semicolon added, newline added, caret moved to next line)

**Actual Behavior**: Completion is committed.

### LINKED ISSUE #45895: AbstractEditorInlineRenameService.SymbolRenameInfo.CanRenameAttributePrefix has buggy implementation
See https://github.com/dotnet/roslyn/pull/45847/commits/c54743b71f398738408cbb4be860ab1a53d8e7cc#diff-18aee645fd759fd2e86ce36bfe560751R98

Method has many unused parameters and last line always returns true:
https://github.com/dotnet/roslyn/blob/e5a8db4ff486983f531ab56adc585c191cf95885/src/EditorFeatures/Core.Wpf/InlineRename/AbstractEditorInlineRenameService.SymbolRenameInfo.cs#L86-L101

### LINKED ISSUE #67244: AlignOpenBraceWithMethodDeclaration is flaky
Runfo Tracking Issue: [AlignOpenBraceWithMethodDeclaration is flaky](https://runfo.azurewebsites.net/tracking/issue/481)
|Build|Definition|Kind|Run Name|
|---|---|---|---|
|[204760](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204760)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_false OOPCoreClr_false|
|[204760](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204760)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_false OOPCoreClr_false|
|[204760](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204760)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_true OOPCoreClr_false|
|[204566](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204566)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67303](https://github.com/dotnet/roslyn/pull/67303)|1-Integration Release OOP64_false OOPCoreClr_false|
|[204566](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204566)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67303](https://github.com/dotnet/roslyn/pull/67303)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[204299](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204299)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_false OOPCoreClr_false|
|[204299](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204299)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_false OOPCoreClr_false|
|[204299](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204299)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_true OOPCoreClr_false|
|[204299](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204299)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_true OOPCoreClr_false|
|[204240](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204240)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67126](https://github.com/dotnet/roslyn/pull/67126)|1-Integration Release OOP64_false OOPCoreClr_false|
|[204240](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204240)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67126](https://github.com/dotnet/roslyn/pull/67126)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[204106](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204106)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67279](https://github.com/dotnet/roslyn/pull/67279)|1-Integration Release OOP64_false OOPCoreClr_false|
|[204106](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204106)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67279](https://github.com/dotnet/roslyn/pull/67279)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[202983](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202983)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67126](https://github.com/dotnet/roslyn/pull/67126)|1-Integration Release OOP64_false OOPCoreClr_false|
|[202983](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202983)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67126](https://github.com/dotnet/roslyn/pull/67126)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[202948](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202948)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67279](https://github.com/dotnet/roslyn/pull/67279)|1-Integration Release OOP64_false OOPCoreClr_false|
|[202948](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202948)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67279](https://github.com/dotnet/roslyn/pull/67279)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[202845](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202845)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_false OOPCoreClr_false|
|[202845](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202845)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_false OOPCoreClr_false|
|[202845](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202845)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_true OOPCoreClr_false|
|[202845](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202845)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_true OOPCoreClr_false|
|[202683](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202683)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67279](https://github.com/dotnet/roslyn/pull/67279)|1-Integration Release OOP64_false OOPCoreClr_false|
|[202683](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202683)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67279](https://github.com/dotnet/roslyn/pull/67279)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[200137](https://dev.azure.com/dnceng-public/public/_build/results?buildId=200137)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67126](https://github.com/dotnet/roslyn/pull/67126)|1-Integration Release OOP64_false OOPCoreClr_false|
|[200137](https://dev.azure.com/dnceng-public/public/_build/results?buildId=200137)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67126](https://github.com/dotnet/roslyn/pull/67126)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[199298](https://dev.azure.com/dnceng-public/public/_build/results?buildId=199298)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_false OOPCoreClr_false|
|[199298](https://dev.azure.com/dnceng-public/public/_build/results?buildId=199298)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_false OOPCoreClr_false|
|[199298](https://dev.azure.com/dnceng-public/public/_build/results?buildId=199298)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_true OOPCoreClr_false|
|[199298](https://dev.azure.com/dnceng-public/public/_build/results?buildId=199298)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_true OOPCoreClr_false|
|[199067](https://dev.azure.com/dnceng-public/public/_build/results?buildId=199067)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67189](https://github.com/dotnet/roslyn/pull/67189)|1-Integration Release OOP64_false OOPCoreClr_false|
|[199067](https://dev.azure.com/dnceng-public/public/_build/results?buildId=199067)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67189](https://github.com/dotnet/roslyn/pull/67189)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[199057](https://dev.azure.com/dnceng-public/public/_build/results?buildId=199057)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 66958](https://github.com/dotnet/roslyn/pull/66958)|1-Integration Release OOP64_false OOPCoreClr_false|
|[199057](https://dev.azure.com/dnceng-public/public/_build/results?buildId=199057)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 66958](https://github.com/dotnet/roslyn/pull/66958)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198826](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198826)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_false OOPCoreClr_false|
|[198826](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198826)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_false OOPCoreClr_false|
|[198826](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198826)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198826](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198826)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_true OOPCoreClr_false|
|[198810](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198810)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67191](https://github.com/dotnet/roslyn/pull/67191)|1-Integration Release OOP64_false OOPCoreClr_false|
|[198810](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198810)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67191](https://github.com/dotnet/roslyn/pull/67191)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198589](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198589)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 65780](https://github.com/dotnet/roslyn/pull/65780)|1-Integration Release OOP64_false OOPCoreClr_false|
|[198589](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198589)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 65780](https://github.com/dotnet/roslyn/pull/65780)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198502](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198502)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 65641](https://github.com/dotnet/roslyn/pull/65641)|1-Integration Release OOP64_false OOPCoreClr_false|
|[198502](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198502)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 65641](https://github.com/dotnet/roslyn/pull/65641)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198499](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198499)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67241](https://github.com/dotnet/roslyn/pull/67241)|1-Integration Release OOP64_false OOPCoreClr_false|
|[198499](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198499)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67241](https://github.com/dotnet/roslyn/pull/67241)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198496](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198496)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67240](https://github.com/dotnet/roslyn/pull/67240)|1-Integration Release OOP64_false OOPCoreClr_false|
|[198496](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198496)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67240](https://github.com/dotnet/roslyn/pull/67240)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198491](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198491)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 59491](https://github.com/dotnet/roslyn/pull/59491)|1-Integration Release OOP64_false OOPCoreClr_false|
|[198491](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198491)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 59491](https://github.com/dotnet/roslyn/pull/59491)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198474](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198474)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67126](https://github.com/dotnet/roslyn/pull/67126)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198474](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198474)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67126](https://github.com/dotnet/roslyn/pull/67126)|1-Integration Release OOP64_false OOPCoreClr_false|
|[198432](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198432)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67136](https://github.com/dotnet/roslyn/pull/67136)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198330](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198330)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67238](https://github.com/dotnet/roslyn/pull/67238)|1-Integration Release OOP64_false OOPCoreClr_false|
|[198330](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198330)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67238](https://github.com/dotnet/roslyn/pull/67238)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198330](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198330)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67238](https://github.com/dotnet/roslyn/pull/67238)|2-Integration Release OOP64_false OOPCoreClr_false|
|[198330](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198330)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67238](https://github.com/dotnet/roslyn/pull/67238)|2-Integration Debug OOP64_true OOPCoreClr_false|
|[198225](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198225)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 65641](https://github.com/dotnet/roslyn/pull/65641)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198124](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198124)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67167](https://github.com/dotnet/roslyn/pull/67167)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198124](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198124)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67167](https://github.com/dotnet/roslyn/pull/67167)|2-Integration Release OOP64_false OOPCoreClr_false|
|[198124](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198124)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67167](https://github.com/dotnet/roslyn/pull/67167)|2-Integration Debug OOP64_true OOPCoreClr_false|
|[197983](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197983)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67175](https://github.com/dotnet/roslyn/pull/67175)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[197939](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197939)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_true OOPCoreClr_false|
|[197939](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197939)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_true OOPCoreClr_false|
|[197912](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197912)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_true OOPCoreClr_false|
|[197912](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197912)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_true OOPCoreClr_false|
|[197902](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197902)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_false OOPCoreClr_false|
|[197902](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197902)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_true OOPCoreClr_false|
|[197902](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197902)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_true OOPCoreClr_false|
|[197808](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197808)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67189](https://github.com/dotnet/roslyn/pull/67189)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[197808](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197808)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67189](https://github.com/dotnet/roslyn/pull/67189)|2-Integration Debug OOP64_true OOPCoreClr_false|
|[197808](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197808)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67189](https://github.com/dotnet/roslyn/pull/67189)|3-Integration Release OOP64_false OOPCoreClr_false|
|[197398](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197398)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67207](https://github.com/dotnet/roslyn/pull/67207)|2-Integration Release OOP64_false OOPCoreClr_false|
|[197398](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197398)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67207](https://github.com/dotnet/roslyn/pull/67207)|2-Integration Debug OOP64_true OOPCoreClr_false|
|[197398](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197398)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67207](https://github.com/dotnet/roslyn/pull/67207)|3-Integration Release OOP64_false OOPCoreClr_false|
|[197398](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197398)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67207](https://github.com/dotnet/roslyn/pull/67207)|3-Integration Debug OOP64_true OOPCoreClr_false|
|[197358](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197358)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67126](https://github.com/dotnet/roslyn/pull/67126)|1-Integration Release OOP64_false OOPCoreClr_false|
|[197358](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197358)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67126](https://github.com/dotnet/roslyn/pull/67126)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[197332](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197332)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67135](https://github.com/dotnet/roslyn/pull/67135)|5-Integration Debug OOP64_true OOPCoreClr_false|
|[197332](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197332)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67135](https://github.com/dotnet/roslyn/pull/67135)|6-Integration Debug OOP64_true OOPCoreClr_false|
|[197043](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197043)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67232](https://github.com/dotnet/roslyn/pull/67232)|2-Integration Debug OOP64_true OOPCoreClr_false|
|[191900](https://dev.azure.com/dnceng-public/public/_build/results?buildId=191900)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67164](https://github.com/dotnet/roslyn/pull/67164)|2-Integration Release OOP64_false OOPCoreClr_false|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|5|30|35|

### LINKED ISSUE #67245: VerifyLocalVariableRename is flaky
Runfo Tracking Issue: [VerifyLocalVariableRename is flaky](https://runfo.azurewebsites.net/tracking/issue/482)
|Build|Definition|Kind|Run Name|
|---|---|---|---|
|[204760](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204760)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_false OOPCoreClr_false|
|[204760](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204760)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_false OOPCoreClr_false|
|[204760](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204760)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_true OOPCoreClr_false|
|[204566](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204566)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67303](https://github.com/dotnet/roslyn/pull/67303)|1-Integration Release OOP64_false OOPCoreClr_false|
|[204566](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204566)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67303](https://github.com/dotnet/roslyn/pull/67303)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[204299](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204299)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_false OOPCoreClr_false|
|[204299](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204299)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_false OOPCoreClr_false|
|[204299](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204299)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_true OOPCoreClr_false|
|[204299](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204299)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_true OOPCoreClr_false|
|[204240](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204240)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67126](https://github.com/dotnet/roslyn/pull/67126)|1-Integration Release OOP64_false OOPCoreClr_false|
|[204240](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204240)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67126](https://github.com/dotnet/roslyn/pull/67126)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[204106](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204106)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67279](https://github.com/dotnet/roslyn/pull/67279)|1-Integration Release OOP64_false OOPCoreClr_false|
|[204106](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204106)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67279](https://github.com/dotnet/roslyn/pull/67279)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[202983](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202983)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67126](https://github.com/dotnet/roslyn/pull/67126)|1-Integration Release OOP64_false OOPCoreClr_false|
|[202983](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202983)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67126](https://github.com/dotnet/roslyn/pull/67126)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[202948](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202948)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67279](https://github.com/dotnet/roslyn/pull/67279)|1-Integration Release OOP64_false OOPCoreClr_false|
|[202948](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202948)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67279](https://github.com/dotnet/roslyn/pull/67279)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[202845](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202845)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_false OOPCoreClr_false|
|[202845](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202845)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_false OOPCoreClr_false|
|[202845](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202845)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_true OOPCoreClr_false|
|[202845](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202845)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_true OOPCoreClr_false|
|[202683](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202683)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67279](https://github.com/dotnet/roslyn/pull/67279)|1-Integration Release OOP64_false OOPCoreClr_false|
|[202683](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202683)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67279](https://github.com/dotnet/roslyn/pull/67279)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[200137](https://dev.azure.com/dnceng-public/public/_build/results?buildId=200137)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67126](https://github.com/dotnet/roslyn/pull/67126)|1-Integration Release OOP64_false OOPCoreClr_false|
|[200137](https://dev.azure.com/dnceng-public/public/_build/results?buildId=200137)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67126](https://github.com/dotnet/roslyn/pull/67126)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[199298](https://dev.azure.com/dnceng-public/public/_build/results?buildId=199298)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_false OOPCoreClr_false|
|[199298](https://dev.azure.com/dnceng-public/public/_build/results?buildId=199298)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_false OOPCoreClr_false|
|[199298](https://dev.azure.com/dnceng-public/public/_build/results?buildId=199298)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_true OOPCoreClr_false|
|[199298](https://dev.azure.com/dnceng-public/public/_build/results?buildId=199298)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_true OOPCoreClr_false|
|[199067](https://dev.azure.com/dnceng-public/public/_build/results?buildId=199067)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67189](https://github.com/dotnet/roslyn/pull/67189)|1-Integration Release OOP64_false OOPCoreClr_false|
|[199067](https://dev.azure.com/dnceng-public/public/_build/results?buildId=199067)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67189](https://github.com/dotnet/roslyn/pull/67189)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[199057](https://dev.azure.com/dnceng-public/public/_build/results?buildId=199057)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 66958](https://github.com/dotnet/roslyn/pull/66958)|1-Integration Release OOP64_false OOPCoreClr_false|
|[199057](https://dev.azure.com/dnceng-public/public/_build/results?buildId=199057)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 66958](https://github.com/dotnet/roslyn/pull/66958)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198826](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198826)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_false OOPCoreClr_false|
|[198826](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198826)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_false OOPCoreClr_false|
|[198826](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198826)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198826](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198826)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_true OOPCoreClr_false|
|[198810](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198810)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67191](https://github.com/dotnet/roslyn/pull/67191)|1-Integration Release OOP64_false OOPCoreClr_false|
|[198810](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198810)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67191](https://github.com/dotnet/roslyn/pull/67191)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198589](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198589)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 65780](https://github.com/dotnet/roslyn/pull/65780)|1-Integration Release OOP64_false OOPCoreClr_false|
|[198589](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198589)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 65780](https://github.com/dotnet/roslyn/pull/65780)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198502](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198502)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 65641](https://github.com/dotnet/roslyn/pull/65641)|1-Integration Release OOP64_false OOPCoreClr_false|
|[198502](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198502)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 65641](https://github.com/dotnet/roslyn/pull/65641)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198499](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198499)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67241](https://github.com/dotnet/roslyn/pull/67241)|1-Integration Release OOP64_false OOPCoreClr_false|
|[198499](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198499)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67241](https://github.com/dotnet/roslyn/pull/67241)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198496](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198496)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67240](https://github.com/dotnet/roslyn/pull/67240)|1-Integration Release OOP64_false OOPCoreClr_false|
|[198496](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198496)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67240](https://github.com/dotnet/roslyn/pull/67240)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198491](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198491)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 59491](https://github.com/dotnet/roslyn/pull/59491)|1-Integration Release OOP64_false OOPCoreClr_false|
|[198491](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198491)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 59491](https://github.com/dotnet/roslyn/pull/59491)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198474](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198474)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67126](https://github.com/dotnet/roslyn/pull/67126)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198474](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198474)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67126](https://github.com/dotnet/roslyn/pull/67126)|1-Integration Release OOP64_false OOPCoreClr_false|
|[198432](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198432)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67136](https://github.com/dotnet/roslyn/pull/67136)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198330](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198330)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67238](https://github.com/dotnet/roslyn/pull/67238)|1-Integration Release OOP64_false OOPCoreClr_false|
|[198330](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198330)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67238](https://github.com/dotnet/roslyn/pull/67238)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198330](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198330)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67238](https://github.com/dotnet/roslyn/pull/67238)|2-Integration Release OOP64_false OOPCoreClr_false|
|[198330](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198330)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67238](https://github.com/dotnet/roslyn/pull/67238)|2-Integration Debug OOP64_true OOPCoreClr_false|
|[198225](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198225)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 65641](https://github.com/dotnet/roslyn/pull/65641)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198124](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198124)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67167](https://github.com/dotnet/roslyn/pull/67167)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[198124](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198124)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67167](https://github.com/dotnet/roslyn/pull/67167)|2-Integration Release OOP64_false OOPCoreClr_false|
|[198124](https://dev.azure.com/dnceng-public/public/_build/results?buildId=198124)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67167](https://github.com/dotnet/roslyn/pull/67167)|2-Integration Debug OOP64_true OOPCoreClr_false|
|[197983](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197983)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67175](https://github.com/dotnet/roslyn/pull/67175)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[197939](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197939)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_true OOPCoreClr_false|
|[197939](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197939)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_true OOPCoreClr_false|
|[197912](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197912)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_true OOPCoreClr_false|
|[197912](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197912)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_true OOPCoreClr_false|
|[197902](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197902)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_false OOPCoreClr_false|
|[197902](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197902)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Debug OOP64_true OOPCoreClr_false|
|[197902](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197902)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|Rolling|1-Integration Release OOP64_true OOPCoreClr_false|
|[197808](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197808)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67189](https://github.com/dotnet/roslyn/pull/67189)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[197808](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197808)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67189](https://github.com/dotnet/roslyn/pull/67189)|2-Integration Debug OOP64_true OOPCoreClr_false|
|[197808](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197808)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67189](https://github.com/dotnet/roslyn/pull/67189)|3-Integration Release OOP64_false OOPCoreClr_false|
|[197398](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197398)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67207](https://github.com/dotnet/roslyn/pull/67207)|2-Integration Release OOP64_false OOPCoreClr_false|
|[197398](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197398)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67207](https://github.com/dotnet/roslyn/pull/67207)|2-Integration Debug OOP64_true OOPCoreClr_false|
|[197398](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197398)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67207](https://github.com/dotnet/roslyn/pull/67207)|3-Integration Release OOP64_false OOPCoreClr_false|
|[197398](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197398)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67207](https://github.com/dotnet/roslyn/pull/67207)|3-Integration Debug OOP64_true OOPCoreClr_false|
|[197358](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197358)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67126](https://github.com/dotnet/roslyn/pull/67126)|1-Integration Release OOP64_false OOPCoreClr_false|
|[197358](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197358)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67126](https://github.com/dotnet/roslyn/pull/67126)|1-Integration Debug OOP64_true OOPCoreClr_false|
|[197332](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197332)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67135](https://github.com/dotnet/roslyn/pull/67135)|5-Integration Debug OOP64_true OOPCoreClr_false|
|[197332](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197332)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67135](https://github.com/dotnet/roslyn/pull/67135)|6-Integration Debug OOP64_true OOPCoreClr_false|
|[197043](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197043)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67232](https://github.com/dotnet/roslyn/pull/67232)|2-Integration Debug OOP64_true OOPCoreClr_false|
|[191900](https://dev.azure.com/dnceng-public/public/_build/results?buildId=191900)|[roslyn-integration-CI](https://dnceng-public.visualstudio.com/public/_build?definitionId=96)|[PR 67164](https://github.com/dotnet/roslyn/pull/67164)|2-Integration Release OOP64_false OOPCoreClr_false|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|5|30|35|

### PR DESCRIPTION
**Pull request by sharwell**
Closes #18065
Closes #45895
Closes #67244
Closes #67245

### CODE REVIEW

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
I don't see anything about this PR taht prevents https://github.com/dotnet/roslyn/pull/67073 from going in.  All that PR does is extract the same logic that rename has today into a reusable class, instead of embedding it into the inline-rename type.

File: src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicRename.cs [hunk 1]
```diff
@@ -0,0 +1,401 @@
...
+            var tags = await TestServices.Editor.GetRenameTagsAsync(HangMitigatingCancellationToken);
+            var tagSpans = tags.SelectAsArray(tag => new TextSpan(tag.Span.Start, tag.Span.Length));
+            AssertEx.SetEqual(renameSpans, tagSpans);
+
+            await TestServices.Input.SendWithoutActivateAsync(new InputKey[] { "Custom", VirtualKeyCode.RETURN }, HangMitigatingCancellationToken);
+            await TestServices.Workspace.WaitForRenameAsync(HangMitigatingCancellationToken);
+            await TestServices.EditorVerifier.TextEqualsAsync(@"
+Imports System
+
+Public Class CustomAttribute$$
```
Comment (genlu) [inline src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicRename.cs:396]:
```suggestion
Public Class CustomA$$ttribute
```

This is what the actual result looks like in the failure

Comment (sharwell) [reply src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicRename.cs:408]: I tested Version 17.6.0 Preview 3.0 [33505.110.main] both with and without this change, and so far I have not been able to reproduce a caret position anywhere except at the end of the line.

Comment (genlu) [reply src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicRename.cs:408]: This is what I got in 17.6p3
rename

Comment (sharwell) [reply src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicRename.cs:408]: That's a different test. The one here is only the behavior for attributes.

Comment (sharwell) [reply src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicRename.cs:399]: I modified the test to support both caret placement outcomes. It's not clear how/why the caret gets placed at the end of a rename operation so I wasn't sure how to start debugging this.
