### PR TITLE
Pick the right project for P2P refs in lightweight solution load and cross-targeting

### LINKED ISSUE #17570: VS crash in VisualStudioProjectTracker.GetOrCreateProjectFromArgumentsAndReferences
_From @AArnott on March 6, 2017 3:4_

d15rel 26228.00
I have lightweight solution load turned on.
This crashed twice in a row (2 out of 2 attempts)

```
git clone https://github.com/aarnott/pinvoke
cd pinvoke
git checkout bugrepro/roslyn-project-system/1678
devenv src\pinvoke.sln
```

Crashes with:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Linq.Enumerable.Single[[System.Byte, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<Byte>)
   at System.Linq.ImmutableArrayExtensions.SingleOrDefault[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Immutable.ImmutableArray`1<System.__Canon>, System.Func`2<System.__Canon,Boolean>)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker.GetOrCreateProjectFromArgumentsAndReferences(Microsoft.VisualStudio.LanguageServices.ProjectSystem.IWorkspaceProjectContextFactory, Microsoft.CodeAnalysis.IAnalyzerAssemblyLoader, System.String, System.Collections.Generic.IReadOnlyDictionary`2<System.String,Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.DeferredProjectInformation>, System.Collections.Generic.IReadOnlyDictionary`2<System.String,System.String>)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker+<PopulateWorkspaceFromDeferredProjectInfoAsync>d__69.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker+<LoadSolutionFromMSBuildAsync>d__62.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Roslyn.Utilities.TaskExtensions+<FireAndForget>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

_Copied from original issue: dotnet/roslyn-project-system#1678_

### PR DESCRIPTION
**Pull request by Pilchie**
If a project being loaded in lightweight solution load references a CPS project
that does cross-targeting, we may crash trying to hook up P2P references,
because we were looking for a single project matching the project file name, and
language.  In the case of cross-targeting though, we create a project for each
TFM, and the .Single call would blow up.

To fix this, we now continue looking through projects until we find one with an
output path that matches our reference.

Fixes #17570.

**Ask Mode Template**
Customer and Scenario Info

Who is impacted by this bug: Customers using .NET Core with cross-targeting, Desktop projects, and lightweight solution load.
What is the customer scenario and impact of the bug: Sometime not long after opening the solution, VS may crash.  This is timing dependent, and most likely to happen on the first open after LSL is enabled.
What is the workaround: Disable LSL
How was the bug found: Watson - 57 hits in RTW, 1460 altogether, Customer report from AArnott
If this fix is for a regression - what had regressed, when was the regression introduced, and why was the regression originally missed: This is not a regression.
​What is a Customer Rea​dy description of change should we need to document this: VS no longer crashes in lightweight solution load if a .NET Framework project references a cross-targeted .NET Core project.
Bug Fix Details

Overview of the fix: Instead of assuming that there is only a single IntelliSense project for a give project file path, find the one that matches the reference by output path if there is one.
Which VS products, SKUs, or components need the fix: All Skus - Roslyn insertion
What branch does the fix go into: D15Rel
What feature areas are impacted by the fix: Solution Load, LSL, .NET Core projects.
What is the risk of the code change: Low, the original path is preserved, but instead of crashing if there are multiple entries, we try to pick the best one, falling back to the first if there is no best match.
Does this change have impact on anything else (e.g. setup, perf, stress, ux, visual freeze, go live, breaking change, samples, etc): We now walk the list of references of each project 
How is this fix rolling forward in the next major release / sprintly train (e.g. Dev15):​ Regular merges in Roslyn repo.
​Validation
What testing/validation was done on the fix, and what were the results:
Forced a repro by adding a delay to the code, and stepped through ensure it behaves as expected.  
Vendor team buddy tested the fix.
Val build running
Will provide to Andrew to validate in his scenario.
(Binary/Component Insertions only) have you validated that your insertion does not regress DDRIT / RPS: Pending completion of VAL build, but chance is low, given DDRIT/RPS doesn't cover LSL scenarios.
Which engineering partner teams have signed off on the fix: 
Who code reviewed the fix: JasonMal

### CODE REVIEW

**Comment by Pilchie** [comment]
test vsi please

**Comment by Pilchie** [comment]
Tagging @dotnet/roslyn-ide for review.

**Comment by Pilchie** [comment]
Retest windows_release_unit32_prtest please

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker.cs [hunk 1]
```diff
@@ -844,6 +835,47 @@ private void OutputToOutputWindow(string message)
             return (AbstractProject)projectContext;
         }
 
+        private AbstractProject TryFindExistingProjectForProjectReference(string projectReferencePath, ImmutableArray<MetadataReference> metadataReferences)
+        {
+            // NOTE: ImmutableProjects might contain projects for other languages like
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker.cs]: Should this comment go closer to line 845?

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker.cs [hunk 2]
```diff
@@ -844,6 +835,47 @@ private void OutputToOutputWindow(string message)
             return (AbstractProject)projectContext;
         }
 
+        private AbstractProject TryFindExistingProjectForProjectReference(string projectReferencePath, ImmutableArray<MetadataReference> metadataReferences)
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker.cs]: Make this multiple lines?

**Comment by Pilchie** [comment]
Tagging @MattGertz for escrow consideration

**Comment by MattGertz** [comment]
@Pilchie Can you add the VSO number?  I will want to start cross-correlating.
Also this needs the template filled out.

**Comment by Pilchie** [comment]
@Mattgertz: Sorry - VSO Bug is https://devdiv.visualstudio.com/DevDiv/_workitems/edit/294080, and I've filled out the ask mode template there.  Updating above here too.
