### PR TITLE
Fix stack overflow compiling deeply nested generic

### LINKED ISSUE #33909: StackOverflow when compiling CoreCLR
Building CoreCLR using either the Desktop compiler on Windows or the core compiler on OSX results in a stackoverflow: https://github.com/dotnet/coreclr/issues/22757

Stack trace is [stacktrace.txt](https://github.com/dotnet/coreclr/files/2891861/stacktrace.txt)

### PR DESCRIPTION
**Pull request by jaredpar**
As a part of implementing nullable reference types many of our locals
switched from `TypeSymbol` to `TypeSymbolWithAnnotations`. In the vast
majority of cases this doesn't have a meaningful impact on compilation.
They are bigger (about 3X) but it's still a relatively small `struct`
(three words).

The size difference is significant though in
`BindNamespaceOrTypeOrAliasSymbol`. This method is used in recursive
parts of binding and is mutually recursive with `BindQualifiedNam`. This
method defines a large number of locals which contribute to every layer
of recursion. When they moved to `TypeSymbolWithAnnotations` this pushed
us outside our tolerance levels and we hit an overflow in extreme cases.

Virtually none of these locals are used in the recursive case. Factored
their use into local functions so we only pay the stack usage on demand.

closes #33909
fixes https://github.com/dotnet/coreclr/issues/22757

### CODE REVIEW

**Comment by jaredpar** [comment]
@dotnet/roslyn-compiler for review

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs [hunk 1]
```diff
@@ -478,6 +439,76 @@ void reportNullableReferenceTypesIfNeeded(SyntaxToken questionToken, TypeSymbolW
                     LazyMissingNonNullTypesContextDiagnosticInfo.ReportNullableReferenceTypesIfNeeded(isNullableEnabled, typeArgument, location, diagnostics);
                 }
             }
+
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs]: FYI: I changed no logic in the local functions here, just copy and pasted.

File: src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs [hunk 2]
```diff
@@ -6,10 +6,28 @@
...
+        /// <param name="action"></param>
+        private static void RunInThread(Action action)
+        {
+            var thread = new System.Threading.Thread(() =>
+            {
+                action();
+            }, 0);
+            thread.Start();
+            thread.Join();
+        }
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs]: >} [](start = 8, length = 1)

nit: double empty line below

File: src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs [hunk 3]
```diff
@@ -75,16 +93,68 @@ void tryCompileDeepFluentCalls(int depth)
...
+
+            var source = builder.ToString();
+
+            RunInThread(() =>
+            {
+                var compilation = CreateCompilation(source, options: TestOptions.DebugExe);
+                CompileAndVerify(compilation, expectedOutput: "Pass");
+            });
+
+            void genType(int level)
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs]: >genType [](start = 17, length = 7)

nit: spell out function name

File: src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs [hunk 4]
```diff
@@ -75,16 +93,68 @@ void tryCompileDeepFluentCalls(int depth)
...
+            int nestingLevel = 500;
+            var builder = new StringBuilder();
+            builder.AppendLine(@"
+using System;
+
+public class Test
+{
+    public static int Main()
+    {
+        #pragma warning disable 219
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs]: >219 [](start = 32, length = 3)

could you add a comment (what is 219?)

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs [hunk 5]
```diff
@@ -338,44 +344,28 @@ internal NamespaceOrTypeOrAliasSymbolWithAnnotations BindNamespaceOrTypeSymbol(E
             return UnwrapAlias(result, diagnostics, syntax, basesBeingResolved);
         }
 
+        /// <summary>
+        /// Bind the syntax into a namespace, type or alias symbol. 
+        /// </summary>
+        /// <remarks>
+        /// This method is used in deeply recursive parts of the compiler. Specifically this and <see cref="BindQualifiedName(ExpressionSyntax, SimpleNameSyntax, DiagnosticBag, ConsList{TypeSymbol}, bool)"/>
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs]: ><see [](start = 97, length = 4)

Consider splitting to new line.

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs [hunk 6]
```diff
@@ -338,44 +344,28 @@ internal NamespaceOrTypeOrAliasSymbolWithAnnotations BindNamespaceOrTypeSymbol(E
...
+        /// are mutually recursive. The non-recursive parts of this method tend to reserve siginficantly large
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs]: >siginficantly [](start = 91, length = 13)

Typo

File: src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs [hunk 7]
```diff
@@ -75,16 +93,68 @@ void tryCompileDeepFluentCalls(int depth)
...
-                thread.Join();
+                });
+            }
+        }
+
+        [Fact]
+        [WorkItem(33909, "https://github.com/dotnet/roslyn/issues/33909")]
+        public void DeeplyNestedGeneric()
+        {
+            int nestingLevel = 500;
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs]: >int nestingLevel = 500; [](start = 12, length = 23)

I'm surprised this is not per-platform. Did you just pick a level that works everywhere? If so, I'm not sure that is the best for detecting changes. 
Might it be possible to regress in RELEASE without regressing in DEBUG for example?

**Comment by cston** [comment]
> using Roslyn.Test.Utilities;

Missing file header.

---
Refers to: src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs:1 in e8679b0. [](commit_id = e8679b04eceb245a1d00bb8610317ad5594886c9, deletion_comment = False)

**Comment by jcouv** [comment]
>                     {

Does it help to extract the remaining cases (like this one) out to local functions too?

---
Refers to: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs:411 in e8679b0. [](commit_id = e8679b04eceb245a1d00bb8610317ad5594886c9, deletion_comment = False)

File: src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs (hunk 7 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs]: I will tune this a biit. 

---
In reply to: [263977314](https://github.com/dotnet/roslyn/pull/33985#discussion_r263977314) [](ancestors = 263977314)

Comment (jcouv) [reply src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs]: Consider adding some code to detect and print out the current limit (as we do in `OverflowOnFluentCall` above)

File: src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs [hunk 8]
```diff
@@ -75,16 +93,68 @@ void tryCompileDeepFluentCalls(int depth)
...
+
+            void genType(int level)
+            {
+                if (level >= nestingLevel)
+                {
+                    return;
+                }
+
+                builder.AppendLine($"public struct MyStruct{level}<T{level}> {{");
+                genType(level + 1);
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs]: >genType(level + 1); [](start = 16, length = 19)

Are we likely to exceed the stack limit here?
Perhaps replace with a loop:
```
for (int i = 0; i < n; i++)
    builder.AppendLine("struct MyStruct{i}<T{i}> {");
for (int i = 0; i < n; i++)
    builder.AppendLine("}");

Comment (jaredpar) [reply src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs]: Haven't hit it locally and I went all the way to 20,000. I can fix though. 

---
In reply to: [263978256](https://github.com/dotnet/roslyn/pull/33985#discussion_r263978256) [](ancestors = 263978256)

File: src/Tools/ILAsm/IlAsmDeploy.csproj [hunk 9]
```diff
@@ -43,7 +43,7 @@
   </PropertyGroup>
 
   <Target Name="_PublishILAsm"
-          BeforeTargets="AfterBuild"
+          AfterTargets="Build"
```
Comment (RikkiGibson) [inline src/Tools/ILAsm/IlAsmDeploy.csproj]: Why did this change?

File: src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs [hunk 10]
```diff
@@ -1,44 +1,77 @@
...
     {
+
+#if DEBUG
+        public static bool IsDebug => true;
+#else
+        public static bool IsDebug => false;
+#endif
+
+
+        /// <summary>
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs]: nit: double empty lines above

File: src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs [hunk 11]
```diff
@@ -75,16 +108,82 @@ void tryCompileDeepFluentCalls(int depth)
...
+            int nestingLevel = (IntPtr.Size * 8) switch
+            {
+                32 when IsDebug => 100,
+                32 when !IsDebug => 100,
+                64 when IsDebug => 100,
+                64 when !IsDebug => 100,
+                _ => throw new Exception($"unexpected pointer size {IntPtr.Size}")
+            };
+
+            // Un-comment loop below and use above commands to figure out the new limits
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs]: Don't forget to comment the loop before merging

File: src/Tools/ILAsm/IlAsmDeploy.csproj (hunk 9 above)
Comment (jaredpar) [reply src/Tools/ILAsm/IlAsmDeploy.csproj]: Working around a bad merge in another PR that broke the build. Going to revert before I merge.

**Comment by jaredpar** [comment]
@jcouv, @cston and @rikkigibson may want to take another look. I changed the style of the tests a bit and wanted to make sure you all approved that. I also had to change the approach for tolerances to not fully excercise them in release. It takes longer than the entirety of the rest of the DLL's tests. Instead had to establish a reasonable release number and let the debug tolerances catch fine grained regressions.

File: src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs (hunk 11 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs]: Blah bad merge.
