### PR TITLE
Fix QuickInfo tests

### LINKED ISSUE #19914: Unskip quickinfo tests after moving to new VS build
https://github.com/dotnet/roslyn/pull/19728 removes our QuickInfo command handler now that one is implemented by the editor. However, we haven't yet moved Jenkins to a machine with editor bits that have their command handler. Skipping all tests that use the quickinfo command until we move to a new build. We'll need to unskip when we move forward.

### PR DESCRIPTION
**Pull request by sharwell**
Closes #19914

### CODE REVIEW

File: src/VisualStudio/IntegrationTest/TestUtilities/InProcess/QuickInfoToStringConverter.cs [hunk 1]
```diff
@@ -28,6 +28,15 @@ private static string GetStringFromItem(object item)
                     return GetStringFromTextBlock(textBlock);
                 case ITextBuffer textBuffer:
                     return textBuffer.CurrentSnapshot.GetText();
+                case ContainerElement containerElement:
```
Comment (sharwell) [inline src/VisualStudio/IntegrationTest/TestUtilities/InProcess/QuickInfoToStringConverter.cs]: 📝 This was broken since #25181, but since all the Quick Info integration tests were disabled and never restored, no one ever knew.

**Comment by sharwell** [comment]
@jaredpar for approval
