### PR TITLE
Adhere to new lines for braces formatting option in property pattern clauses

### LINKED ISSUE #52413: Pattern matching should adhere to `csharp_new_line_before_open_brace = none` (IDE0055)
**Version Used**: 
Visual Studio 16.9.3

**Steps to Reproduce**:
See attached solution: [Bugs.Roslyn.PatternMatchingBraces.zip](https://github.com/dotnet/roslyn/files/6255806/Bugs.Roslyn.PatternMatchingBraces.zip)

1. Create `.editorconfig` with 
```editorconfig
[*.cs]
csharp_new_line_before_open_brace = none
dotnet_diagnostic.IDE0055.severity = error
```
2. Write something like:
```csharp
public bool IsAbc(Test test) {
    return test is {
        Name: "Abc"
    };
}
```

**Expected Behavior**:
IDE0055 has no concerns about the code as it matches editorconfig.

**Actual Behavior**:
IDE0055 is reported at `test is {`, suggested quickfix converts code into
```csharp
public bool IsAbc(Test test) {
    return test is
    {
        Name: "Abc"
    };
}
```

### PR DESCRIPTION
**Pull request by mrahhal**
Example:

```editorconfig
[*.cs]
csharp_new_line_before_open_brace = none
```

```cs
public class TestInner {
    public string Name { get; }
}

public class Test {
    public string Name { get; }
    public TestInner Inner { get; }
}

public class Program {
    public bool IsAbc(Test test) {
        return test is { // Here
            Name: "foo",
            Inner: { // Here
                Name: "bar"
            }
        };
    }
}
```

Before this change, the lines noted above would report IDE0055 and the suggested code fix converts to using a new line (violating our config). After this change, the formatting rule is now respected in `is` pattern matching clauses, just like in all other places.

Closes #52413

### CODE REVIEW

**Review by Youssef1313 — CHANGES_REQUESTED** [review]
I think `CurlyBraceCompletionService` will need a similar change

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/NewLineUserSettingFormattingRule.cs [hunk 1]
```diff
@@ -537,6 +562,7 @@ public override int GetHashCode()
                 hashCode = (hashCode << 1) + (NewLinesForBracesInProperties ? 1 : 0);
                 hashCode = (hashCode << 1) + (NewLinesForBracesInMethods ? 1 : 0);
                 hashCode = (hashCode << 1) + (NewLinesForBracesInAccessors ? 1 : 0);
+                hashCode = (hashCode << 1) + (NewLinesForBracesInPropertyPatternClauses ? 1 : 0);
                 hashCode = (hashCode << 1) + (NewLinesForBracesInAnonymousMethods ? 1 : 0);
                 hashCode = (hashCode << 1) + (NewLinesForBracesInLambdaExpressionBody ? 1 : 0);
                 hashCode = (hashCode << 1) + (NewLinesForBracesInControlBlocks ? 1 : 0);
```
Comment (Youssef1313) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/NewLineUserSettingFormattingRule.cs:568]: I'm on favor to convert this to a record struct once the feature is shipped in C# 10 🎉

**Review by Youssef1313 — CHANGES_REQUESTED** [review]
Needs tests.

**Review by Youssef1313 — CHANGES_REQUESTED** [review]
Needs to be added in Visual Studio UI as well (see `NewLinesViewModel`).

https://github.com/dotnet/roslyn/blob/315c2e149ba7889b0937d872274c33fcbfe9af5f/src/VisualStudio/CSharp/Impl/Options/Formatting/NewLinesViewModel.cs#L204-L213

**Review by Youssef1313 — CHANGES_REQUESTED** [review]
Needs to be added to `CSharpFormattingSettingsProvider` too.

**Review by Youssef1313 — COMMENTED** [review]
It should be added in AutomationObject as well, but please don't add it for now since it will cause conflicts for a PR I'm working on. I'll add it in my PR after your PR goes in.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/CSharpFormattingOptions2.cs [hunk 2]
```diff
@@ -350,6 +351,9 @@ private static Option2<bool> CreateNewLineForBracesOption(NewLineOption newLineO
         public static Option2<bool> NewLinesForBracesInAccessors { get; } = CreateNewLineForBracesOption(
             NewLineOption.Accessors, nameof(NewLinesForBracesInAccessors));
 
+        public static Option2<bool> NewLinesForBracesInPropertyPatternClauses { get; } = CreateNewLineForBracesOption(
```
Comment (Youssef1313) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/CSharpFormattingOptions2.cs:354]: @333fred FYI in case this needs change in O# as well:

https://github.com/OmniSharp/omnisharp-roslyn/blob/c9a8563c36acc6dfba6b28e1491d1267593c0732/src/OmniSharp.Shared/Options/FormattingOptions.cs#L138-L166

**Comment by mrahhal** [comment]
> Needs tests.

Wanted to ask, at first glance I wasn't able to find existing similar tests for the different new line formatting. Any idea where exactly?

> I think `CurlyBraceCompletionService` will need a similar change

If you think it deserves to be in the same PR, I can have a look at that.

> It should be added in AutomationObject as well, but please don't add it for now since it will cause conflicts for a PR I'm working on. I'll add it in my PR after your PR goes in.

Noted.

**Comment by Youssef1313** [comment]
> Wanted to ask, at first glance I wasn't able to find existing similar tests for the different new line formatting. Any idea where exactly?
> 
> >

https://github.com/dotnet/roslyn/blob/465f627608beb559272e182f4fb66c605532d968/src/Workspaces/CSharpTest/Formatting/FormattingTests.cs#L9830-L9862

https://github.com/dotnet/roslyn/blob/1cca63b/src/CodeStyle/CSharp/Tests/FormattingAnalyzerTests.cs#L248-L284

**Comment by Youssef1313** [comment]
> > I think `CurlyBraceCompletionService` will need a similar change
> 
> If you think it deserves to be in the same PR, I can have a look at that.
> 
> >

You can wait for @sharwell on this. If it won't be included in this PR, please add a comment for me in https://github.com/dotnet/roslyn/issues/50275 to get that fixed when I start working on that issue.

File: src/EditorFeatures/CSharpTest/EditorConfigSettings/DataProvider/DataProviderTests.cs [hunk 3]
```diff
@@ -130,7 +130,7 @@ public void TestGettingFormattingSettingProviderLanguageServiceAsync()
             var model = new TestViewModel();
             settingsProvider.RegisterViewModel(model);
             var dataSnapShot = settingsProvider.GetCurrentDataSnapshot();
-            Assert.Equal(47, dataSnapShot.Length);
+            Assert.Equal(48, dataSnapShot.Length);
```
Comment (mrahhal) [inline src/EditorFeatures/CSharpTest/EditorConfigSettings/DataProvider/DataProviderTests.cs:133]: image

This error was in the build, so I simply incremented the expected value to 48 since a new setting was added. Is this correct?

File: src/VisualStudio/CSharp/Impl/Options/Formatting/NewLinesViewModel.cs [hunk 4]
```diff
@@ -206,6 +206,7 @@ public NewLinesViewModel(OptionStore optionStore, IServiceProvider serviceProvid
             Items.Add(new CheckBoxOptionViewModel(CSharpFormattingOptions.NewLinesForBracesInMethods, CSharpVSResources.Place_open_brace_on_new_line_for_methods_local_functions, s_methodPreview, this, optionStore));
             Items.Add(new CheckBoxOptionViewModel(CSharpFormattingOptions.NewLinesForBracesInProperties, CSharpVSResources.Place_open_brace_on_new_line_for_properties_indexers_and_events, s_propertyPreview, this, optionStore));
             Items.Add(new CheckBoxOptionViewModel(CSharpFormattingOptions.NewLinesForBracesInAccessors, CSharpVSResources.Place_open_brace_on_new_line_for_property_indexer_and_event_accessors, s_propertyPreview, this, optionStore));
+            Items.Add(new CheckBoxOptionViewModel(CSharpFormattingOptions.NewLinesForBracesInPropertyPatternClauses, CSharpVSResources.Place_open_brace_on_new_line_for_property_pattern_clauses, s_propertyPreview, this, optionStore));
```
Comment (Youssef1313) [inline src/VisualStudio/CSharp/Impl/Options/Formatting/NewLinesViewModel.cs:209]: `s_propertyPreview` isn't correct here. You'll need to add a new constant `s_popertyPatternPreview`.

**Comment by sharwell** [comment]
📝 This should reuse the existing option NewLinesForBracesInObjectCollectionArrayInitializers. I haven't checked yet whether or not it does this.

File: src/EditorFeatures/CSharp/EditorConfigSettings/DataProvider/Formatting/CSharpFormattingSettingsProvider.cs [hunk 5]
```diff
@@ -74,6 +74,7 @@ private static IEnumerable<FormattingSetting> GetNewLineOptions(AnalyzerConfigOp
             yield return FormattingSetting.Create(CSharpFormattingOptions2.NewLinesForBracesInMethods, CSharpEditorResources.Place_open_brace_on_new_line_for_methods_local_functions, editorConfigOptions, visualStudioOptions, updaterService);
             yield return FormattingSetting.Create(CSharpFormattingOptions2.NewLinesForBracesInProperties, CSharpEditorResources.Place_open_brace_on_new_line_for_properties_indexers_and_events, editorConfigOptions, visualStudioOptions, updaterService);
             yield return FormattingSetting.Create(CSharpFormattingOptions2.NewLinesForBracesInAccessors, CSharpEditorResources.Place_open_brace_on_new_line_for_property_indexer_and_event_accessors, editorConfigOptions, visualStudioOptions, updaterService);
+            yield return FormattingSetting.Create(CSharpFormattingOptions2.NewLinesForBracesInPropertyPatternClauses, CSharpEditorResources.Place_open_brace_on_new_line_for_property_pattern_clauses, editorConfigOptions, visualStudioOptions, updaterService);
```
Comment (sharwell) [inline src/EditorFeatures/CSharp/EditorConfigSettings/DataProvider/Formatting/CSharpFormattingSettingsProvider.cs:77]: ❗ This should reuse the existing option `NewLinesForBracesInObjectCollectionArrayInitializers`, and not add a new option. The design that established this precedent (which it's certainly understandable you didn't see because it's a comment buried in a seemingly-unrelated topic) is https://github.com/dotnet/roslyn/issues/36913#issuecomment-546015089.

**Review by sharwell — CHANGES_REQUESTED** [review]

File: src/EditorFeatures/CSharp/EditorConfigSettings/DataProvider/Formatting/CSharpFormattingSettingsProvider.cs (hunk 5 above)
Comment (mrahhal) [reply src/EditorFeatures/CSharp/EditorConfigSettings/DataProvider/Formatting/CSharpFormattingSettingsProvider.cs:77]: I see, makes sense if it's getting renamed to `NewLinesForBracesInExpressions` eventually. Will do.

Comment (Youssef1313) [reply src/EditorFeatures/CSharp/EditorConfigSettings/DataProvider/Formatting/CSharpFormattingSettingsProvider.cs:77]: @mrahhal I don't think renaming it is desired. It's a [public shipped API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.formatting.csharpformattingoptions.newlinesforbracesinobjectcollectionarrayinitializers?view=roslyn-dotnet-3.9.0#Microsoft_CodeAnalysis_CSharp_Formatting_CSharpFormattingOptions_NewLinesForBracesInObjectCollectionArrayInitializers), so renaming will be a breaking change.

Comment (mrahhal) [reply src/EditorFeatures/CSharp/EditorConfigSettings/DataProvider/Formatting/CSharpFormattingSettingsProvider.cs:77]: I meant will revert to reusing `NewLinesForBracesInObjectCollectionArrayInitializers`. I won't be renaming this!

File: src/Workspaces/CSharpTest/Formatting/FormattingTests.cs [hunk 6]
```diff
@@ -9861,6 +9861,74 @@ void Goo(R r)
...
+        return a is {
+            Name: ""foo"",
+        };
+    }
+}");
+        }
+
+        [Fact, Trait(Traits.Feature, Traits.Features.Formatting)]
+        [WorkItem(52413, "https://github.com/dotnet/roslyn/issues/52413")]
+        public async Task NewLinesForBraces_PropertyPatternClauses_NonDefault()
```
Comment (sharwell) [inline src/Workspaces/CSharpTest/Formatting/FormattingTests.cs:9898]: 💡 Can you also add a test showing that the pattern stays on one line if it starts that way?

```
[Theory, CombinatorialData]
public async Task NewLinesForBraces_PropertyPattern_SingleLine(bool option)
{
  var changingOptions = new OptionsCollection(LanguageNames.CSharp)
  {
    { NewLinesForBracesInObjectCollectionArrayInitializers, option },
  };

  // test here...
}
```
}

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/NewLineUserSettingFormattingRule.cs [hunk 7]
```diff
@@ -159,6 +159,15 @@ private static bool IsControlBlock(SyntaxNode node)
                 }
             }
 
+            // * { - in property pattern clauses in pattern matching context
```
Comment (sharwell) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/NewLineUserSettingFormattingRule.cs:162]: 💡 This block can be combined with the block on line 130 for `new {` and `with {`

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/NewLineUserSettingFormattingRule.cs [hunk 8]
```diff
@@ -371,6 +380,19 @@ private static bool IsControlBlock(SyntaxNode node)
...
```
Comment (sharwell) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/NewLineUserSettingFormattingRule.cs:383]: 💡 This block can be combined with the block above for `new MyObject {`, `new List<int> {`, and `with {`

**Review by sharwell — COMMENTED** [review]
This is looking much more manageable 👍 

I have one request for a new test, and two suggestions for additional simplification.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/NewLineUserSettingFormattingRule.cs (hunk 7 above)
Comment (mrahhal) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/NewLineUserSettingFormattingRule.cs:162]: Wanted to ask if you prefer that 👍🏻

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/NewLineUserSettingFormattingRule.cs [hunk 9]
```diff
@@ -126,9 +126,11 @@ private static bool IsControlBlock(SyntaxNode node)
                 }
             }
 
-            // new { - Object Initialization, or with { - Record with initializer
+            // new { - Object Initialization, or with { - Record with initializer, or is { - property pattern clauses
             if (currentToken.IsKind(SyntaxKind.OpenBraceToken) &&
-                (currentToken.Parent.IsKind(SyntaxKind.ObjectInitializerExpression) || currentToken.Parent.IsKind(SyntaxKind.WithInitializerExpression)))
+                (currentToken.Parent.IsKind(SyntaxKind.ObjectInitializerExpression) ||
+                currentToken.Parent.IsKind(SyntaxKind.WithInitializerExpression) ||
+                currentToken.Parent.IsKind(SyntaxKind.PropertyPatternClause)))
```
Comment (sharwell) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/NewLineUserSettingFormattingRule.cs:133]: 💡 The `IsKind` overload in namespace Microsoft.CodeAnalysis.CSharp.Extensions can simplify this. This can be done in a follow-up if it's not part of this PR.

```suggestion
                currentToken.Parent.IsKind(SyntaxKind.ObjectInitializerExpression, SyntaxKind.WithInitializerExpression, SyntaxKind.PropertyPatternClause))
```

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/NewLineUserSettingFormattingRule.cs [hunk 10]
```diff
@@ -313,10 +315,12 @@ private static bool IsControlBlock(SyntaxNode node)
...
-            if (currentToken.Kind() == SyntaxKind.OpenBraceToken &&
-                (currentToken.Parent.Kind() == SyntaxKind.ObjectInitializerExpression ||
-                currentToken.Parent.Kind() == SyntaxKind.CollectionInitializerExpression ||
-                currentToken.Parent.Kind() == SyntaxKind.WithInitializerExpression))
+            // is { - property pattern clauses
+            if (currentToken.IsKind(SyntaxKind.OpenBraceToken) &&
+                (currentToken.Parent.IsKind(SyntaxKind.ObjectInitializerExpression) ||
+                currentToken.Parent.IsKind(SyntaxKind.CollectionInitializerExpression) ||
+                currentToken.Parent.IsKind(SyntaxKind.WithInitializerExpression) ||
+                currentToken.Parent.IsKind(SyntaxKind.PropertyPatternClause)))
```
Comment (sharwell) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/NewLineUserSettingFormattingRule.cs:323]: 💡 The `IsKind` overload in namespace Microsoft.CodeAnalysis.CSharp.Extensions can simplify this. This can be done in a follow-up if it's not part of this PR.

```suggestion
                currentToken.Parent.IsKind(SyntaxKind.ObjectInitializerExpression, SyntaxKind.CollectionInitializerExpression, SyntaxKind.WithInitializerExpression, SyntaxKind.PropertyPatternClause))
```

File: src/Workspaces/CSharpTest/Formatting/FormattingTests.cs [hunk 11]
```diff
@@ -9861,6 +9861,109 @@ void Goo(R r)
...
+    public string Name { get; }
+
+    public bool IsFoo(A a)
+    {
+        return a is {
+            Name: ""foo"",
+        };
+    }
+}", changedOptionSet: changingOptions);
+        }
```
Comment (sharwell) [inline src/Workspaces/CSharpTest/Formatting/FormattingTests.cs:9965]: This test isn't actually testing the single-line form 😄 

```suggestion
        [Theory, CombinatorialData, Trait(Traits.Feature, Traits.Features.Formatting)]
        [WorkItem(52413, "https://github.com/dotnet/roslyn/issues/52413")]
        public async Task NewLinesForBraces_PropertyPatternClauses_SingleLine(bool option)
        {
            var changingOptions = new OptionsCollection(LanguageNames.CSharp)
            {
                { NewLinesForBracesInObjectCollectionArrayInitializers, option },
            };
            var code =
                @"
class A
{
    public string Name { get; }

    public bool IsFoo(A a)
    {
        return a is { Name: ""foo"" };
    }
}";

            await AssertFormatAsync(code, code, changedOptionSet: changingOptions);
        }
```

Comment (mrahhal) [reply src/Workspaces/CSharpTest/Formatting/FormattingTests.cs:9965]: I thought you meant something else completely by single line. Just saw the other SingleLine tests in this file. My bad, working on it.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/NewLineUserSettingFormattingRule.cs (hunk 10 above)
Comment (mrahhal) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/NewLineUserSettingFormattingRule.cs:323]: I prefer this to be a separate PR, as I also noticed a lot of other inconsistencies in this file (`.Kind == x` vs `.IsKind(x)`). Maybe a follow-up PR can iron out the usage inconsistencies and also use this simpler overload.

**Review by sharwell — APPROVED** [review]

**Comment by mrahhal** [comment]
image

I noticed this unrelated error happening randomly at times on CI. So I re-pushed to invoke the build again.
