### PR TITLE
Fix descriptions in completion for local functions

### LINKED ISSUE #14163: Local functions are missing descriptions in completion
Type the following code:

image

_Expected:_ there's a tooltip describing localFunction
_Actual:_ you get a cute little empty box

### PR DESCRIPTION
**Pull request by agocke**
**Customer scenario**

The completion service provides descriptions for symbols being offered. Without this change, local functions will appear only as names, with no descriptions of their type or parameters.

This wires up local functions through the semantic model and the SymbolId
service so the description is available to the editor.

**Bugs this fixes:** 

Fixes #14163

**Workarounds, if any**

None.

**Risk**

This is merely exposing existing functionality through the semantic model for local functions.

**Performance impact**

Low. This code path is only taken when requested and it is almost identical to that taken for all other symbols.

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

New feature.

**How was the bug found?**

Testing by the IDE team for problems with the language features in the IDE.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs [hunk 1]
```diff
@@ -118,7 +118,8 @@ internal static bool CanGetSemanticInfo(CSharpSyntaxNode node, bool allowNamedAr
                         (node is ExpressionSyntax && (isSpeculative || allowNamedArgumentName || !SyntaxFacts.IsNamedArgumentName(node))) ||
                         (node is ConstructorInitializerSyntax) ||
                         (node is AttributeSyntax) ||
-                        (node is CrefSyntax);
+                        (node is CrefSyntax) ||
+                        (node is LocalFunctionStatementSyntax);
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs]: this seems odd to me.  I wouldn't expect to be able to do things like GetSymbolInfo on local function.  I would expect to be able to do GetDeclaredSymbol

File: src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs [hunk 2]
```diff
@@ -645,6 +646,15 @@ public SymbolInfo GetSymbolInfo(CrefSyntax crefSyntax, CancellationToken cancell
                 : SymbolInfo.None;
         }
 
+        public SymbolInfo GetSymbolInfo(LocalFunctionStatementSyntax localFunctionSyntax, CancellationToken cancellationToken = default(CancellationToken))
+        {
+            CheckSyntaxNode(localFunctionSyntax);
+
+            return CanGetSemanticInfo(localFunctionSyntax)
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs]: won't this always return true for a LocalFunction?  If so, i'm not sure what purpose this serves.

File: src/Workspaces/Core/Portable/SymbolKey/SymbolKey.AnonymousFunctionOrDelegateSymbolKey.cs [hunk 3]
```diff
@@ -18,7 +18,10 @@ private static class AnonymousFunctionOrDelegateSymbolKey
         {
             public static void Create(ISymbol symbol, SymbolKeyWriter visitor)
             {
-                Debug.Assert(symbol.IsAnonymousDelegateType() || symbol.IsAnonymousFunction());
+                Debug.Assert(
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/SymbolKey/SymbolKey.AnonymousFunctionOrDelegateSymbolKey.cs]: File/type needs to be renamed to reflect it can handle LocalFunctions.  Though i find the use of this type weird.  anonymous-functions/delegates are rather strange beasts.  I would think you could have used "BodyLevelSymbolKey" and just had this work.

**Comment by CyrusNajmabadi** [comment]
This approach does not seem right to me.

**Comment by agocke** [comment]
@CyrusNajmabadi @jasonmalinowski I've rewritten it with your suggestions.

**Comment by AlekseyTs** [comment]
LGTM

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs [hunk 4]
```diff
@@ -9036,5 +9036,46 @@ void M()
...
+            await VerifyItemExistsAsync(@"
+class C
+{
+    void M()
+    {
+        void Local() { }
+        
+        $$
+    }
+}", "Local", "void Local()");
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs]: FYI, we probably want to say something like "(local function) void Local()".  But that can be considered a feature request if you want to file a bug on it.

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs [hunk 5]
```diff
@@ -9036,5 +9036,46 @@ void M()
...
+        }
+
+        [WorkItem(14163, "https://github.com/dotnet/roslyn/issues/14163")]
+        [Fact]
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs]: Merge top two aattributes.

**Comment by CyrusNajmabadi** [comment]
👍 Glad the IDE side was much easier :)

**Comment by agocke** [comment]
test windows_release_unit32_prtest please

**Comment by agocke** [comment]
@MattGertz For ask mode review
