### PR TITLE
Handle misc project having an AdditionalDocument and not a Document

### LINKED ISSUE #82949: InvalidOperationException thrown by LanguageSerfver when creating a new project
Repro:
- Open VS Code
- Create a new project via "New Project", select Maui Blazor hybrid app

Exception with message "Sequence contains no elements" is thrown

```
>	Microsoft.CodeAnalysis.LanguageServer.dll!Microsoft.CodeAnalysis.LanguageServer.FileBasedPrograms.FileBasedProgramsProjectSystem.AddDocumentAsync(Roslyn.LanguageServer.Protocol.DocumentUri documentUri, Microsoft.CodeAnalysis.LanguageServer.TrackedDocumentInfo documentInfo) Line 216	C#
 	Microsoft.CodeAnalysis.LanguageServer.Protocol.dll!Microsoft.CodeAnalysis.LanguageServer.LspWorkspaceManager.GetLspDocumentInfoAsync(Roslyn.LanguageServer.Protocol.TextDocumentIdentifier textDocumentIdentifier, System.Threading.CancellationToken cancellationToken) Line 288	C#
 	Microsoft.CodeAnalysis.LanguageServer.Protocol.dll!Microsoft.CodeAnalysis.LanguageServer.Handler.RequestContext.CreateAsync(bool mutatesSolutionState, bool requiresLSPSolution, Roslyn.LanguageServer.Protocol.TextDocumentIdentifier textDocument, Microsoft.CodeAnalysis.LanguageServer.WellKnownLspServerKinds serverKind, Roslyn.LanguageServer.Protocol.ClientCapabilities clientCapabilities, System.Collections.Immutable.ImmutableArray<string> supportedLanguages, Microsoft.CommonLanguageServerProtocol.Framework.ILspServices lspServices, Microsoft.CommonLanguageServerProtocol.Framework.ILspLogger logger, string method, System.Threading.CancellationToken cancellationToken) Line 265	C#
 	Microsoft.CodeAnalysis.LanguageServer.Protocol.dll!Microsoft.CodeAnalysis.LanguageServer.Handler.RequestContextFactory.CreateRequestContextAsync<Roslyn.LanguageServer.Protocol.DocumentDiagnosticParams>(Microsoft.CommonLanguageServerProtocol.Framework.QueueItem<Microsoft.CodeAnalysis.LanguageServer.Handler.RequestContext> queueItem, Microsoft.CommonLanguageServerProtocol.Framework.IMethodHandler methodHandler, Roslyn.LanguageServer.Protocol.DocumentDiagnosticParams requestParam, System.Threading.CancellationToken cancellationToken) Line 71	C#
 	Microsoft.CodeAnalysis.LanguageServer.Protocol.dll!Microsoft.CommonLanguageServerProtocol.Framework.QueueItem<Microsoft.CodeAnalysis.LanguageServer.Handler.RequestContext>.CreateRequestContextAsync<Roslyn.LanguageServer.Protocol.DocumentDiagnosticParams>(Microsoft.CommonLanguageServerProtocol.Framework.IMethodHandler handler, Microsoft.CommonLanguageServerProtocol.Framework.RequestHandlerMetadata requestHandlerMetadata, Microsoft.CommonLanguageServerProtocol.Framework.AbstractLanguageServer<Microsoft.CodeAnalysis.LanguageServer.Handler.RequestContext> languageServer, System.Threading.CancellationToken cancellationToken) Line 103	C#
 	Microsoft.CodeAnalysis.LanguageServer.Protocol.dll!Microsoft.CommonLanguageServerProtocol.Framework.RequestExecutionQueue<Microsoft.CodeAnalysis.LanguageServer.Handler.RequestContext>.ProcessQueueCoreAsync<Roslyn.LanguageServer.Protocol.DocumentDiagnosticParams, Roslyn.LanguageServer.Protocol.FullDocumentDiagnosticReport>(Microsoft.CommonLanguageServerProtocol.Framework.QueueItem<Microsoft.CodeAnalysis.LanguageServer.Handler.RequestContext> work, Microsoft.CommonLanguageServerProtocol.Framework.IMethodHandler handler, Microsoft.CommonLanguageServerProtocol.Framework.RequestHandlerMetadata metadata, System.Collections.Concurrent.ConcurrentDictionary<System.Threading.Tasks.Task, System.Threading.CancellationTokenSource> concurrentlyExecutingTasks, System.Threading.CancellationTokenSource currentWorkCts, System.Threading.CancellationToken cancellationToken) Line 342	C#
 	[External Code]	
 	Microsoft.CodeAnalysis.LanguageServer.Protocol.dll!Microsoft.CommonLanguageServerProtocol.Framework.RequestExecutionQueue<Microsoft.CodeAnalysis.LanguageServer.Handler.RequestContext>.InvokeProcessCoreAsync(Microsoft.CommonLanguageServerProtocol.Framework.QueueItem<Microsoft.CodeAnalysis.LanguageServer.Handler.RequestContext> work, Microsoft.CommonLanguageServerProtocol.Framework.RequestHandlerMetadata metadata, Microsoft.CommonLanguageServerProtocol.Framework.IMethodHandler handler, System.Reflection.MethodInfo methodInfo, System.Collections.Concurrent.ConcurrentDictionary<System.Threading.Tasks.Task, System.Threading.CancellationTokenSource> concurrentlyExecutingTasks, System.Threading.CancellationTokenSource currentWorkCts, System.Threading.CancellationToken cancellationToken) Line 318	C#
 	Microsoft.CodeAnalysis.LanguageServer.Protocol.dll!Microsoft.CommonLanguageServerProtocol.Framework.RequestExecutionQueue<Microsoft.CodeAnalysis.LanguageServer.Handler.RequestContext>.ProcessQueueAsync() Line 277	C#

```

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #82949

Haven't yet been able to repro the actual scenario locally though.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/roslyn/pull/82956)

### CODE REVIEW

File: src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/FileBasedPrograms/FileBasedProgramsProjectSystem.cs [hunk 1]
```diff
@@ -213,10 +213,11 @@ private async ValueTask<LooseDocumentKind> ClassifyDocumentAsync(string filePath
         var projectInfo = MiscellaneousFileUtilities.CreateMiscellaneousProjectInfoForDocument(
             workspace, documentFilePath, sourceTextLoader, languageInformation, documentInfo.SourceText.ChecksumAlgorithm, workspace.Services.SolutionServices, [], enableFileBasedPrograms);
         projectFactory.ApplyChangeToWorkspace(workspace => workspace.OnProjectAdded(projectInfo));
-        var id = projectInfo.Documents.Single().Id;
-        var primordialDoc = workspace.CurrentSolution.GetRequiredDocument(id);
+        var projectId = projectInfo.Id;
+        var project = workspace.CurrentSolution.GetRequiredProject(projectId);
+        var primordialDoc = project.Documents.SingleOrDefault() ?? project.AdditionalDocuments.Single();
```
Comment (dibarbet) [inline src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/FileBasedPrograms/FileBasedProgramsProjectSystem.cs:218]: Very weird that the test didn't hit this.  Should verify that the test is written properly so we don't hit this again

Comment (RikkiGibson) [reply src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/FileBasedPrograms/FileBasedProgramsProjectSystem.cs:218]: It was a mef composition issue. The implementations of property `Composition` and method `CreateExportProviderAsync()` are out of sync with each other. So, tests in `FileBasedProgramsWorkspaceTests` that manually pass a composition to `CreateLspTestServer` will quietly not use the types in `MS.CA.LanguageServer.dll`.

Comment (RikkiGibson) [reply src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/FileBasedPrograms/FileBasedProgramsProjectSystem.cs:218]: I don't have a general solution for this. It seems like the `Composition` path and `override CreateExportProvider()` path which works by directory scanning are at odds. But, I can at least get the bug to repro when I pass a null `composition`. So making that change for now.
