### PR TITLE
Fix for nested param/typeparam suggestions

### LINKED ISSUE #11487: <param/> incorrectly offered within summary, exception, etc.
1. At $ CTRL+Space

``` C#
        /// <summary>
        ///     Returns a value indicating whether the current project has the specified capability
        /// </summary>
        /// <exception cref="ArgumentNullException">
        ///     <$
        /// </exception>
        bool Contains(string capability);
```

Expected: `<param name="capability"` to not show up
Actual: `<param name="capability"` shows up.

`<param/>` is a sister tag to summary and exception, and shouldn't show inside them. You want `<paramref` instead to refer to parameter names.

### PR DESCRIPTION
**Pull request by lorcanmooney**
Fixes #11487.

This separates out the top-level `param`/`typeparam`-element suggestions from `name`-attribute suggestions, and calls each in the correct context. It also removes a couple of redundant symbol lookups in the VB implementation.

### CODE REVIEW

**Comment by Pilchie** [comment]
Tag @dotnet/roslyn-ide 

test vsi please

**Comment by tannergooding** [comment]
test windows_eta_open_prtest please

**Comment by lorcanmooney** [comment]
test windows_vsi_p3_open_prtest please

**Comment by crummel** [comment]
Build triggered. sha1 is original commit.

File: src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/XmlDocCommentCompletionProviderTests.vb [hunk 1]
```diff
@@ -293,6 +293,50 @@ End Class
...
+    Sub Foo(Of T)(bar as T)
+    End Sub
+End Class
+"
+
+            Await VerifyItemIsAbsentAsync(text, "typeparam name=""T""")
+        End Function
+
+        <Fact, Trait(Traits.Feature, Traits.Features.Completion)>
+        Public Async Function TestNoNestedParam() As Task
```
Comment (Pilchie) [inline src/EditorFeatures/VisualBasicTest/Completion/CompletionProviders/XmlDocCommentCompletionProviderTests.vb]: You could add the `<WorkItem>` attributes here too.

**Comment by Pilchie** [comment]
This LGTM - anyone on @dotnet/roslyn-ide want to review?  @CyrusNajmabadi and/or @rchande  in particular.

**Comment by Pilchie** [comment]
@lorcanmooney any chance you could bring this up to date?

**Comment by lorcanmooney** [comment]
@Pilchie Done, and added the missing work item attributes.

There are a few extra changes in there. Someone removed a lot of the completion spans threaded through these providers, but didn't quite finish the job. Since there were a bunch of merge conflicts around that, I removed whatever was left.

**Comment by lorcanmooney** [comment]
Would anyone else like to take a look at this?

**Comment by CyrusNajmabadi** [comment]
I will look

**Comment by CyrusNajmabadi** [comment]
:+1:

**Comment by Pilchie** [comment]
Just because it's been a few weeks, @dotnet-bot retest this please

**Comment by Pilchie** [comment]
and test vsi please

**Comment by lorcanmooney** [comment]
Just the usual reminder that I don't have access to the vsi results. If there's a failure I need to investigate, please let me know here.

**Comment by Pilchie** [comment]
retest windows_vsi_p1_open_prtest please
retest windows_vsi_p2_open_prtest please 

p1 seems to have a hung machine, and in p2 the test automation failed to connect to VS.

**Comment by lorcanmooney** [comment]
Can someone take a look at vsi_p2 please? I'd _really_ like to get this in so I can finish up some additional XML doc fixes and features.

**Comment by Pilchie** [comment]
The failure is in an Extract Method test, where it's expecting to see two extract method options but only found one (from the screenshot).  @balajikris @heejaechang any idea what might have happened here?  I highly doubt it's related to @lorcanmooney's changes.

**Comment by balajikris** [comment]
I suspect the test is flakey here, couldn't imagine this change affecting ExtractMethod feature. though I haven't seen this test fail this way before :)

**Comment by Pilchie** [comment]
retest windows_vsi_p2_open_prtest please - unrelated extract method failure at http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/458/

**Comment by heejaechang** [comment]
@Pilchie looks like some race on option setting? looks like setExtractMethodOption right before the test didn't actually observed by extract method refactoring so it returns just 1.

**Comment by Pilchie** [comment]
Tag @jasonmalinowski - any idea how @heejaechang's idea might have happened?

**Comment by lorcanmooney** [comment]
Now that all the tests are green, I presume this is good to merge?

**Comment by Pilchie** [comment]
Done - thanks again for the contribution, and the ping.

**Comment by jasonmalinowski** [comment]
@heejaechang: when options change, what code invalidates previously computed analyzers or code fixes or whatever? I guess we have a longstanding bug/design issue where if you have a Solution snapshot the only way to get options is to jump back to the workspace where you might be seeing options from "the future". This would seem like something didn't invalidate the computation-already-in-flight after it was changed.
