### PR TITLE
Fixed smart variable naming

### LINKED ISSUE #19260: Smart variable naming should escape keywords
**Version Used**: 2.3.0.61627

**Steps to Reproduce**:
```c#
class For
{
    For |
}
```
Commit `for`.

**Expected Behavior**: `@for` inserted;

**Actual Behavior**: `for` inserted and CS1519.

### PR DESCRIPTION
**Pull request by zaytsev-victor**
**Customer scenario**

Keywords aren't escaped in Smart variable naming

**Bugs this fixes:**
Fixed #19260

**Workarounds, if any**

**Risk**
Low

**Performance impact**
Low

**Is this a regression from a previous update?**
No

**Root cause analysis:**
Not implemented escaping for keywords

**How was the bug found?**
customer reported

### CODE REVIEW

File: src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs [hunk 1]
```diff
@@ -177,7 +177,7 @@ private ITypeSymbol UnwrapType(ITypeSymbol type, Compilation compilation)
                     {
                         foreach (var baseName in baseNames)
                         {
-                            var name = rule.NamingStyle.CreateName(baseName);
+                            var name = EscapeIdentifier(rule.NamingStyle.CreateName(baseName));
```
Comment (rchande) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs]: We have a helper for this: (http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Extensions/StringExtensions.cs,14). You should be able to get the "isQueryContext" parameter from the CSharpSyntaxContext that's passed in.

**Comment by rchande** [comment]
Thanks for your contribution, @zaytsev-victor! I've merged the change.
