### PR TITLE
Remove trailing commas during conversion to class

### LINKED ISSUE #45747: "Convert to class" refactoring for anonymous types generates a syntax error from trailing comma
**Version Used**: 
16.6.3

**Steps to Reproduce**:
```C#
public class Test
{
    public object M() => new
    {
        Foo = 1,
        Bar = 2,
    };
}
```
Run the "Convert to class" refactoring from the `new` keyword.

**Expected Behavior**:
```c#
    public object M() => new NewClass(
1,
2
    );
}
// […]
```
(maybe without the strange indenting)

**Actual Behavior**:
```c#
    public object M() => new NewClass(
1,
2,
    );
}
// […]
```
Note the comma after the second constructor parameter resulting in an immediate syntax error.

image

### PR DESCRIPTION
**Pull request by mahalex**
Fixes #45747

### CODE REVIEW

File: src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs [hunk 1]
```diff
@@ -41,7 +42,19 @@ private ArgumentListSyntax CreateArgumentList(AnonymousObjectCreationExpressionS
...
+            => SyntaxFactory.SeparatedList<ArgumentSyntax>(CreateArguments(OmitTrailingComma(initializers.GetWithSeparators())));
+
+        private static SyntaxNodeOrTokenList OmitTrailingComma(SyntaxNodeOrTokenList list)
+        {
+            // Trailing comma is allowed in initializer list, but disallowed in method calls.
+            return list.Count >= 2 && list[^1].IsToken
+                ? list
+                    .Replace(
+                        list[^2],
+                        list[^2].AsNode().WithAppendedTrailingTrivia(list[^1].GetTrailingTrivia()))
```
Comment (sharwell) [inline src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs:54]: ❔ Shouldn't this be leading and trailing trivia?

```suggestion
                        list[^2].AsNode().WithAppendedTrailingTrivia(list[^1].GetLeadingTrivia()).WithAppendedTrailingTrivia(list[^1].GetTrailingTrivia()))
```

Comment (mahalex) [reply src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs]: You are right! Fixed.

File: src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs [hunk 2]
```diff
@@ -41,7 +42,21 @@ private ArgumentListSyntax CreateArgumentList(AnonymousObjectCreationExpressionS
...
+            // Trailing comma is allowed in initializer list, but disallowed in method calls.
+            return list.Count >= 2 && list[^1].IsToken
+                ? list
+                    .Replace(
+                        list[^2],
+                        list[^2].AsNode()
+                            .WithAppendedTrailingTrivia(list[^1].GetLeadingTrivia())
+                            .WithAppendedTrailingTrivia(list[^1].GetTrailingTrivia()))
+                    .RemoveAt(list.Count - 1)
+                : list;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs:58]: this has gotten to bee too much of a mouthful.  Can you just have this be:
```suggestion
            if (list.Count % 2 == 1)
                return list;
                
            // now just return the list without the comma.
```

File: src/EditorFeatures/CSharpTest/ConvertAnonymousTypeToClass/ConvertAnonymousTypeToClassTests.cs [hunk 3]
```diff
@@ -1399,6 +1399,126 @@ void Method()
...
+";
+            var expected = @"
+class Test
+{
+    void Method()
+    {
+        var t1 = new {|Rename:NewClass|}(
+1,
+2
+        );
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/ConvertAnonymousTypeToClass/ConvertAnonymousTypeToClassTests.cs:1456]:
```suggestion
2
        );
```

this doesn't seem desirable.  If there is only whitespace trivia, i think it would be appropriate to just not transfer that along.

Comment (mahalex) [reply src/EditorFeatures/CSharpTest/ConvertAnonymousTypeToClass/ConvertAnonymousTypeToClassTests.cs:1456]: Do you want to change the behavior in the no-trailing-comma case as well? Right now
```
            var t1 = new
            {
                a = 1,
                b = 2
            };
```
is transformed into
```
            var t1 = new NewClass(
1,
2
            );
```
Also, other refactorings (like "Convert to tuple") have similar behavior, and I feel there should be consistency.

File: src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs (hunk 1 above)
Comment (mahalex) [reply src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs]: By the way, currently some trivia of deleted parts in the initializer list is lost. For example,
```
            var t1 = new
            {
                // Hi
                a = 1,
                b = 2
            };
```
is transformed into
```
            var t1 = new NewClass(
1,
2
            );
```
Is this considered a bug?

File: src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs (hunk 2 above)
Comment (mahalex) [reply src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs:58]: `list.Count % 2 == 1` would break the empty list case, so we really need the `list.Count >= 2` condition. But I agree that it's better to get rid of the ternary conditional.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs:58]: sounds good.

File: src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs]: yup, i would def consider that a bug :)

File: src/EditorFeatures/CSharpTest/ConvertAnonymousTypeToClass/ConvertAnonymousTypeToClassTests.cs (hunk 3 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/ConvertAnonymousTypeToClass/ConvertAnonymousTypeToClassTests.cs:1456]: i think there is a distinct difference int he patterns used when using `{` style versus (an initialization list) vs `(` style (an argument list).  I would prefer we matched the end style we expect people to most commonly use.  That said, i'm ok with this being out of scope for this PR as we'd likely need to update a few things at the same time for consistency :)

File: src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs (hunk 1 above)
Comment (mahalex) [reply src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs]: Preserving leading trivia from the initializers would also produce more reasonable indentation.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs]: yes.  i woudl consider preservatin of leading trivia appropriate, as well as the removal of the final trailing trivia of the last element.

File: src/EditorFeatures/CSharpTest/ConvertAnonymousTypeToClass/ConvertAnonymousTypeToClassTests.cs (hunk 3 above)
Comment (mahalex) [reply src/EditorFeatures/CSharpTest/ConvertAnonymousTypeToClass/ConvertAnonymousTypeToClassTests.cs:1456]: Agreed, I'll create an issue for that.

File: src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs (hunk 2 above)
Comment (mahalex) [reply src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs]: Fixed.

File: src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs [hunk 4]
```diff
@@ -47,15 +47,18 @@ private SeparatedSyntaxList<ArgumentSyntax> CreateArguments(SeparatedSyntaxList<
...
-                    .Replace(
-                        list[^2],
-                        list[^2].AsNode()
-                            .WithAppendedTrailingTrivia(list[^1].GetLeadingTrivia())
-                            .WithAppendedTrailingTrivia(list[^1].GetTrailingTrivia()))
-                    .RemoveAt(list.Count - 1)
-                : list;
+            if (list.Count == 0 || list.Count % 2 == 1)
+            {
+                return list;
```
Comment (sharwell) [inline src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs:52]: 💡 

```suggestion
                // The list is either empty, or does not end with a trailing comma
                return list;
```

Comment (mahalex) [reply src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs:53]: Fixed.

File: src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs (hunk 1 above)
Comment (mahalex) [reply src/Features/CSharp/Portable/ConvertAnonymousTypeToClass/CSharpConvertAnonymousTypeToClassCodeRefactoringProvider.cs]: Created issue #45792

File: src/EditorFeatures/CSharpTest/ConvertAnonymousTypeToClass/ConvertAnonymousTypeToClassTests.cs (hunk 3 above)
Comment (mahalex) [reply src/EditorFeatures/CSharpTest/ConvertAnonymousTypeToClass/ConvertAnonymousTypeToClassTests.cs:1456]: Created issue #45792

**Comment by mahalex** [comment]
@CyrusNajmabadi looks like the build agents are feeling unwell.

**Comment by CyrusNajmabadi** [comment]
Thankjs for the PR!
