### PR TITLE
Handle opening/closing of additional files in VS Workspace open file …

### LINKED ISSUE #31540: Additional file code fixes are not updating in memory snapshot of the additional file text
**Version Used**: Latest Dev16 Preview2 dogfood build

**Steps to Reproduce**:

1. Enlist into Roslyn master 
2. Restore and build Roslyn.sln
3. Open Roslyn.sln and add two or more new public APIs to CodeAnalysis.csproj
4. Notice multiple RS0016 diagnostics from public API analyzer `Symbol 'X' is not part of the declared API.`
5. Sequentially apply code fixes to each RS0016 diagnostic

**Expected Behavior**:
Unshipped public API file is correctly updated and contains all new public API entries

**Actual Behavior**:
Unshipped public API file only contains the entry from the last code fix application. The reasons seems to be that we are somehow not updating the in-memory additional file snapshot after each code fix application, and each successive code fix application works on the original additional file text.

### PR DESCRIPTION
**Pull request by mavasani**
…tracker

Fixes #31540

### CODE REVIEW

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProject.cs [hunk 1]
```diff
@@ -347,14 +347,15 @@ private void OnBatchScopeDisposed()
...
                 var documentFileNamesAdded = ImmutableArray.CreateBuilder<string>();
-                var documentsToOpen = new List<(DocumentId, SourceTextContainer)>();
+                var documentsToOpen = new List<(DocumentId documentId, SourceTextContainer textContainer, bool isAdditionalDocument)>();
 
                 _workspace.ApplyBatchChangeToProject(Id, solution =>
                 {
                     solution = _sourceFiles.UpdateSolutionForBatch(
                         solution,
                         documentFileNamesAdded,
                         documentsToOpen,
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProject.cs]: It seems we should just have a separate "documentsToOpen" and "additionalDocumentsToOpen" collection.

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.OpenFileTracker.cs [hunk 2]
```diff
@@ -350,9 +358,16 @@ private void TryClosingDocumentsForCookie(uint cookie)
...
                     {
-                        if (_workspace.IsDocumentOpen(documentId) && !_workspace._documentsNotFromFiles.Contains(documentId))
+                        if (!_workspace._documentsNotFromFiles.Contains(documentId))
                         {
-                            w.OnDocumentClosed(documentId, new FileTextLoader(moniker, defaultEncoding: null));
+                            if (_workspace.IsDocumentOpen(documentId))
+                            {
+                                w.OnDocumentClosed(documentId, new FileTextLoader(moniker, defaultEncoding: null));
+                            }
+                            else if (w.CurrentSolution.ContainsAdditionalDocument(documentId))
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.OpenFileTracker.cs]: Shouldn't this be paralleling the logic in the open case above? You need to check if it's a regular document before OnDocumentClosed, and if it's not that assert it's an AdditionalDocument?

File: src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs [hunk 3]
```diff
@@ -483,19 +483,18 @@ public SolutionState AddProject(ProjectInfo projectInfo)
...
-        private ImmutableDictionary<string, ImmutableArray<DocumentId>> CreateLinkedFilesMapWithAddedProject(ProjectState projectState)
+        private ImmutableDictionary<string, ImmutableArray<DocumentId>> CreateFilePathToDocumentIdsMapWithAddedProject(ProjectState projectState)
         {
-            return CreateLinkedFilesMapWithAddedDocuments(projectState, projectState.DocumentIds);
+            var documentIdsAndFilePaths = GetDocumentIdsAndFilePaths(projectState, projectState.DocumentIds, projectState.AdditionalDocumentIds);
+            return CreateFilePathToDocumentIdsMapWithAddedDocuments(documentIdsAndFilePaths);
         }
 
-        private ImmutableDictionary<string, ImmutableArray<DocumentId>> CreateLinkedFilesMapWithAddedDocuments(ProjectState projectState, IEnumerable<DocumentId> documentIds)
+        private ImmutableDictionary<string, ImmutableArray<DocumentId>> CreateFilePathToDocumentIdsMapWithAddedDocuments(IEnumerable<(DocumentId documentId, string filePath)> documentIdsAndFilePaths)
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs]: Any reason this shouldn't just take an `IEnumerable<TextDocumentState>` rather than decomposing into tuples? It'll save you the allocation overhead of the Select methods in GetDocumentIdsAndFilePaths and that method just becomes ProjectState.DocumentStates.Concat(ProjectState.AdditionalDocumentStates) which you can probably re-inline.

File: src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs [hunk 4]
```diff
@@ -528,40 +534,37 @@ public SolutionState RemoveProject(ProjectId projectId)
...
         {
-            return CreateLinkedFilesMapWithRemovedDocuments(projectState, projectState.DocumentIds);
+            var documentIdsAndFilePaths = GetDocumentIdsAndFilePaths(projectState, projectState.DocumentIds, projectState.AdditionalDocumentIds);
+            return CreateFilePathToDocumentIdsMapWithRemovedDocuments(documentIdsAndFilePaths);
         }
 
-        private ImmutableDictionary<string, ImmutableArray<DocumentId>> CreateLinkedFilesMapWithRemovedDocuments(
-            ProjectState projectState,
-            IEnumerable<DocumentId> documentIds)
+        private ImmutableDictionary<string, ImmutableArray<DocumentId>> CreateFilePathToDocumentIdsMapWithRemovedDocuments(IEnumerable<(DocumentId documentId, string filePath)> documentIdsAndFilePaths)
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs]: Ditto earlier comment: just use `IEnumerable<TextDocumentState>`.

File: src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs [hunk 5]
```diff
@@ -1213,8 +1219,10 @@ public SolutionState RemoveAdditionalDocument(DocumentId documentId)
 
             var oldProject = this.GetProjectState(documentId.ProjectId);
             var newProject = oldProject.RemoveAdditionalDocument(documentId);
+            var removedDocumentIdAndFilePath = SpecializedCollections.SingletonEnumerable((documentId, oldProject.GetAdditionalDocumentState(documentId).FilePath));
 
-            return this.ForkProject(newProject);
+            return this.ForkProject(newProject,
+                newFilePathToDocumentIdsMap: CreateFilePathToDocumentIdsMapWithRemovedDocuments(removedDocumentIdAndFilePath));
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs]: Do we have any tests for the GetDocumentIdsWithFilePath today that we can expand to confirm we're correctly adding additional files now?

File: src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs [hunk 6]
```diff
@@ -66,7 +66,7 @@ internal partial class SolutionState
             _projectIds = projectIds.ToImmutableReadOnlyListOrEmpty();
             _projectIdToProjectStateMap = idToProjectStateMap;
             _projectIdToTrackerMap = projectIdToTrackerMap;
-            _linkedFilesMap = linkedFilesMap;
+            _filePathToDocumentIdsMap = filePathToDocumentIdsMap;
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs]: Did we do an audit through existing callers of GetDocumentIdsForFilePath to see if this is going to crash anybody if they get new results? A lot of the places do actually do a GetDocument and handle nulls so I'm not terribly worried, but I had some hesitation going this direction if that was going to be a big problem.

File: src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs (hunk 3 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs]: It also saves you other cases where you're already fetching the state and then decomposing it anyways.

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.OpenFileTracker.cs (hunk 2 above)
Comment (mavasani) [reply src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspaceImpl.OpenFileTracker.cs]: I'll make it consistent.

File: src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs (hunk 6 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs]: Yes, I did confirm so.

File: src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs (hunk 5 above)
Comment (mavasani) [reply src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs]: I will add a test.

**Comment by mavasani** [comment]
@jasonmalinowski Addressed feedback

File: src/Workspaces/Core/Portable/Workspace/Workspace_Editor.cs [hunk 7]
```diff
@@ -644,6 +655,10 @@ protected virtual Solution AdjustReloadedSolution(Solution oldSolution, Solution
                 {
                     newSolution = newSolution.WithDocumentText(docId, this.GetOpenDocumentText(oldSolution, docId), PreservationMode.PreserveIdentity);
                 }
+                else if (newSolution.ContainsAdditionalDocument(docId))
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Workspace/Workspace_Editor.cs]: Honestly this is giving me hope making GetOpenDocumentIds do the right thing is actually the right way to go: your audit turned up a legitimate bug. :smile:

**Comment by mavasani** [comment]
Thanks @jasonmalinowski - will address the feedback.

Tagging @dotnet/roslyn-ide for additional review(s) and @jinujoseph @vatsalyaagrawal for approval
