### PR TITLE
Export classification type definitions for new classification types

### LINKED ISSUE #25716: [Regression] Syntax no longer shows up in Find All References if it refers to symbols outside of the project
**Version Used**: 
Version 15.7.0 Preview 3.0 [27523.0.d15.7]

**Steps to Reproduce**:

1. File -> New Console App (.NET Framework)
2. In `Main` in Program.cs, add:
``` C#
            Console.WriteLine("Foo");
```
3. Right-click on WriteLine and choose _Find All References_

**Expected Behavior**:
In 15.6.3:
image

**Actual Behavior**:
image

~Note: I tried to repro this on a new project and couldn't - however, it repros in every FAR I've done in project-system and CPS solution.~

I've found a 100% repro, updated steps.

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #25716

### Customer scenario

Find all references fails to show code preview on lines with method names and other similar cases.

### Bugs this fixes

Fixes #25716

### Workarounds, if any

None.

### Risk

Low.

### Performance impact

N/A

### Is this a regression from a previous update?

Yes, introduced by 1063c092d2ca0a48f4bd189e53002ae714348955.

### Root cause analysis

The failure occurs in the presentation layer of the Find All References window, where exceptions are caught and fields are simply displayed as empty to avoid crashing the IDE. Our integration tests operate against the model rather than the view, so errors in the presentation logic are not revealed by automated testing.

The underlying cause was a failure to export a `ClassificationTypeDefinition` for new classification types used in IDE code. A reflection-based test was added to detect regressions of this exact type, though no general protection is offered against other types of failures in the presentation layer. A failure of the new test will result in output like the following:

> Message: ClassificationTypeNames.FieldName has value "field name", but no matching ClassificationTypeDefinition was exported.
> Expected: True
> Actual:   False

### How was the bug found?

Dogfooding

### Test documentation updated?

No

### CODE REVIEW

**Comment by jinujoseph** [comment]
@DustinCampbell for review

**Comment by jasonmalinowski** [comment]
@sharwell @jinujoseph I presume we're taking this escrow for Preview 3, right? We'll get your branch in a moment.

**Comment by jinujoseph** [comment]
yes , i will work on getting the VSO bug for approval

**Comment by jasonmalinowski** [comment]
@tmeschter Let  us know once the non -vs-deps will be up.

File: src/EditorFeatures/Test/Workspaces/ClassificationTypeNamesTests.cs [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+            {
+                foreach (var field in typeof(ClassificationTypeNames).GetFields(BindingFlags.Static | BindingFlags.Public))
+                {
+                    yield return new object[] { field.Name, field.GetRawConstantValue() };
+                }
+            }
+        }
+
+        [Theory]
+        [MemberData(nameof(AllClassificationTypeNames))]
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Test/Workspaces/ClassificationTypeNamesTests.cs]: Nifty!

File: src/EditorFeatures/Test/Workspaces/ClassificationTypeNamesTests.cs [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+        [WorkItem(25716, "https://github.com/dotnet/roslyn/issues/25716")]
+        public void ClassificationTypeExported(string fieldName, object constantValue)
+        {
+            Assert.IsType<string>(constantValue);
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Test/Workspaces/ClassificationTypeNamesTests.cs]: Random tip: Assert.IsType returns the type cast to the underlying type, so you can nicely combine this with the line below.

File: src/EditorFeatures/Test/Workspaces/ClassificationTypeNamesTests.cs [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+            string classificationTypeName = (string)constantValue;
+            var exportProvider = TestExportProvider.ExportProviderWithCSharpAndVisualBasic;
+            var exports = exportProvider.GetExports<ClassificationTypeDefinition, IClassificationTypeDefinitionMetadata>();
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Test/Workspaces/ClassificationTypeNamesTests.cs]: Should this just import the IContentTypeRegistryService and ask that for the content type by name? I can imagine cases where we could screw something up (cycles in base types, maybe?) that might pass this.

Comment (sharwell) [reply src/EditorFeatures/Test/Workspaces/ClassificationTypeNamesTests.cs]: I was thinking that type wouldn't be available in unit tests, but maybe it is. I'll switch to it if available.

**Comment by jinujoseph** [comment]
Approved to merge in d15.7.Preview3 via [link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/589807)
@sharwell make sure to retarget the branch to dev15.7-preview3
