### PR TITLE
Overload resolution was ignoring HasTypeArgumentInferredFromFunctionType for calls in expanded form

### LINKED ISSUE #57627: .NET 6.100 The call is ambiguous between the following methods or properties breaking change
**Version Used**: 

```
 dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  3.0.103 [C:\Program Files\dotnet\sdk]
  3.1.120 [C:\Program Files\dotnet\sdk]
  3.1.200-preview-014883 [C:\Program Files\dotnet\sdk]
  3.1.414 [C:\Program Files\dotnet\sdk]
  5.0.208 [C:\Program Files\dotnet\sdk]
  5.0.402 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Steps to Reproduce**:

1. `dotnet new nunit`
2.
``` C#
using System;
using System.Threading.Tasks;
using NUnit.Framework;

Assert.That(async () => await Task.FromResult<object>(null), Throws.InstanceOf<ArgumentNullException>(), "");
```
3. dotnet build 

**Expected Behavior**:

Builds

**Actual Behavior**:
```
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
D:\temp\nunitb\UnitTest1.cs(12,16): error CS0121: The call is ambiguous between the following methods or properties: 'Assert.That<TActual>(ActualValueDelegate<TActual>, IResolveConstraint, string?, params object?[]?)' and 'Assert.That<TActual>(TActual, IResolveConstraint, string?, params object?[]?)' [D:\temp\nunitb\nunitb.csproj]
D:\temp\nunitb\UnitTest1.cs(12,63): warning CS8625: Cannot convert null literal to non-nullable reference type. [D:\temp\nunitb\nunitb.csproj]
```

**NOTE:** the same sample builds with `<LangVersion>9</LangVersion>`

### PR DESCRIPTION
**Pull request by cston**
For calls to generic overloads with a `params` parameter, overload resolution was ignoring whether type inference relied on _function types_, so the "better function member" was not preferring calls with no _function types_.

Fixes #57627.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs [hunk 1]
```diff
@@ -3401,9 +3398,7 @@ internal EffectiveParameters(ImmutableArray<TypeWithAnnotations> types, Immutabl
                 useSiteInfo: ref useSiteInfo);
 
             return result.Result.IsValid ?
-                new MemberResolutionResult<TMember>(
-                    result.Member,
-                    result.LeastOverriddenMember,
+                result.WithResult(
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:3401]: >result.WithResult [](http://example.com/codeflow?start=16&length=17)

The fix is this change to retain `result.HasTypeInferredFromFunctionType`.

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs [hunk 2]
```diff
@@ -3465,7 +3460,7 @@ internal EffectiveParameters(ImmutableArray<TypeWithAnnotations> types, Immutabl
                                             ref useSiteInfo);
                         if (typeArguments.IsDefault)
                         {
-                            return new MemberResolutionResult<TMember>(member, leastOverriddenMember, inferenceError);
+                            return new MemberResolutionResult<TMember>(member, leastOverriddenMember, inferenceError, hasTypeArgumentInferredFromFunctionType: false);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:3463]: >hasTypeArgumentInferredFromFunctionType: false [](http://example.com/codeflow?start=118&length=46)

Why not simply pass ```hasTypeArgumentsInferredFromFunctionType```?

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 1)

**Review by 333fred — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 2 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:3463]: We could although when `typeArguments.IsDefault`, then `hasTypeArgumentsInferredFromFunctionType == false`.
