### PR TITLE
Don't skip executing analyzer compilation actions in the IDE when Clo…

### LINKED ISSUE #4068: CompilationAction not Triggering
I'm running into an issue with VS 2015 + Roslyn v1.

I read through the analyzer semantic documentation[1].

According to it, I expect that the compilation action I registered in the Initializer, to be executed once at the end of a compilation.

However I am not getting this behavior. The StartCompilation action gets called, but the End never does.
Is this a bug? Am I doing it wrong?

```
        public override void Initialize(AnalysisContext context)
        {
            context.RegisterCompilationAction(this.OnCompilation);
            context.RegisterCompilationStartAction(this.OnStartCompilation);
        }
```

[1] https://github.com/dotnet/roslyn/blob/master/docs/analyzers/Analyzer%20Actions%20Semantics.md

### PR DESCRIPTION
**Pull request by mavasani**
…sedFileDiagnostics flag is turned off OR the analyzer reports only hidden diagnostics. Compilation actions and compilation end actions can report diagnostics on open files, so they must always be executed.

Fixes #4068

### CODE REVIEW

**Comment by mavasani** [comment]
@heejaechang @JohnHamby @srivatsn @basoundr can you please review?

File: src/Features/Core/Diagnostics/EngineV1/DiagnosticIncrementalAnalyzer.cs [hunk 1]
```diff
@@ -329,7 +330,8 @@ internal IEnumerable<DiagnosticAnalyzer> GetAnalyzers(Project project)
                 var versions = new VersionArgument(projectTextVersion, semanticVersion, projectVersion);
                 foreach (var stateSet in _stateManager.GetOrUpdateStateSets(project))
                 {
-                    if (SkipRunningAnalyzer(project.CompilationOptions, analyzerDriver, openedDocument: false, skipClosedFileChecks: false, stateSet: stateSet))
+                    // Compilation actions can report diagnostics on open files, so we skipClosedFileChecks.
+                    if (SkipRunningAnalyzer(project.CompilationOptions, analyzerDriver, openedDocument: true, skipClosedFileChecks: true, stateSet: stateSet))
                     {
```
Comment (heejaechang) [inline src/Features/Core/Diagnostics/EngineV1/DiagnosticIncrementalAnalyzer.cs]: are we going to filter out result?

Comment (mavasani) [inline src/Features/Core/Diagnostics/EngineV1/DiagnosticIncrementalAnalyzer.cs]: You mean if compilation end action reports diagnostics on closed files? Current implementation doesn't, but I am not sure whether it should or should not. Its a valid diagnostic within the project, so why not show it to the user if it already been computed? Probably warrants creating a separate issue for discussion?

Comment (heejaechang) [inline src/Features/Core/Diagnostics/EngineV1/DiagnosticIncrementalAnalyzer.cs]: asking because I am not sure whether the option will be understood as perf related option or user experience related option. since the option make us to behavior like vs2013.

Comment (mavasani) [inline src/Features/Core/Diagnostics/EngineV1/DiagnosticIncrementalAnalyzer.cs]: I agree, let me open another issue to iron out the required semantics of the flag.

Comment (mavasani) [inline src/Features/Core/Diagnostics/EngineV1/DiagnosticIncrementalAnalyzer.cs]: https://github.com/dotnet/roslyn/issues/4364
