### PR TITLE
Exclude constant and static fields from record's PrintMembers

### LINKED ISSUE #47867: MissingFieldException on record types with consts
### Description

A record type with a public const field, throws _MissingFieldException_ when calling _ToString()_

```
public record RecordTypeWithConst(int Id, string Value)
{
    public const string SomeString = "1234";
}
```

I would expect the ToString() method to ignore the the const.

### Configuration

Visual studio 16.8.0 preview 3.0, with dotnet 5.0 rc 1 on windows 10.

### Other information

threw exception: 
System.MissingFieldException: Field not found: 'RecordTypeWithConst.SomeString'.

Stack Trace: 
    RecordTypeWithConst.PrintMembers(StringBuilder builder)
    RecordTypeWithConst.ToString()

### PR DESCRIPTION
**Pull request by Youssef1313**
Might fix #47867, will confirm after adding a test.

But:

1. Should constants be excluded?
2. Why constants currently cause a problem in the first place?

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPrintMembers.cs [hunk 1]
```diff
@@ -214,7 +214,7 @@ static bool isPrintable(Symbol m)
                     return false;
                 }
 
-                if (m.Kind is SymbolKind.Field)
+                if (m is SymbolField { IsConst: false })
                 {
                     return true;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPrintMembers.cs:219]: >true [](start = 27, length = 4)

We should exclude `static` fields and properties as well.

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPrintMembers.cs:219]: I have added a check for `IsStatic`. I think IsConst should be redundant now because constant fields are implicitly static?

**Comment by jcouv** [comment]
Thanks for jumping on this.
Here are the tests I wanted to add. I'll let you incorporate:
```

        [Fact]
        public void ToString_RecordWithStaticMembers()
        {
            var src = @"
var c1 = new C1(42);
System.Console.Write(c1.ToString());

record C1(int I1)
{
    public static int field1 = 44;
    public const int field2 = 44;
    public static int P1 { set { } }
    public static int P2 { get { return 1; } set { } }
    public static int P3 { get { return 1; } }
}
";

            var comp = CreateCompilation(new[] { src, IsExternalInitTypeDefinition }, options: TestOptions.DebugExe);
            CompileAndVerify(comp, expectedOutput: "C1 { I1 = 42 }", verify: Verification.Skipped /* init-only */);
            comp.VerifyEmitDiagnostics();
        }

        [Fact]
        public void ToString_NestedRecord()
        {
            var src = @"
var c1 = new Outer.C1(42);
System.Console.Write(c1.ToString());

public class Outer
{
    public record C1(int I1);
}
";

            var comp = CreateCompilation(new[] { src, IsExternalInitTypeDefinition }, options: TestOptions.DebugExe);
            CompileAndVerify(comp, expectedOutput: "C1 { I1 = 42 }", verify: Verification.Skipped /* init-only */);
            comp.VerifyEmitDiagnostics();
        }

```

**Comment by Youssef1313** [comment]
@cston Thanks for writing these tests!
I've added them with only a minor change (testing debug+release).
I'm not sure if this is valuable or not, but I done that because *currently*, there is a different behavior between Debug and Release.

See https://github.com/dotnet/roslyn/issues/47867#issuecomment-695341170

**Comment by jcouv** [comment]
Corresponding spec update: https://github.com/dotnet/csharplang/pull/3919

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 4)

**Review by cston — APPROVED** [review]

**Comment by jcouv** [comment]
Merged/squashed. Thanks @Youssef1313 !
