### PR TITLE
Fix failure to hook up TODO processing in-process

### LINKED ISSUE #58780: Task list not working with VB.Net
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Task-list-not-working-with-VBNet/1630738)._

---
[severity:It's more difficult to complete my work]
The task list in Visual Studio Professional 2019 Version 16.11.8 is not displaying any tasks from VB.Net source code.  The task list appears to work correctly with C# code, but not with VB.Net code.

---
#### Feedback Bot on 1/6/2022, 08:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/10/2022, 10:02 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #58780

### CODE REVIEW

File: src/VisualStudio/Core/Def/Implementation/TodoComments/VisualStudioTodoCommentsService.cs [hunk 1]
```diff
@@ -114,6 +114,9 @@ private async Task StartWorkerAsync()
             var client = await RemoteHostClient.TryGetClientAsync(_workspace, cancellationToken).ConfigureAwait(false);
             if (client == null)
             {
+                // Now that we've started, let the VS todo list know to start listening to us
+                _eventListenerTracker.EnsureEventListener(_workspace, this);
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Def/Implementation/TodoComments/VisualStudioTodoCommentsService.cs:118]: can we just pull this above the call to TryGetClient, and also remove the EnsureEventListener below.  The goal of this was simply to wait until StartWorkerAsync, not necessarily to wait until the remote connection was made.

we could also just do it in StartAsync.  either woudl be fine.  

--

i would very much prefer not to do it in two places.

Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/TodoComments/VisualStudioTodoCommentsService.cs]: ➡️ Done

**Review by CyrusNajmabadi — APPROVED** [review]
