### PR TITLE
Fix xml doc gen

### LINKED ISSUE #2936: Inconsistent handling of escaped identifiers in <param> and <paramref>
An extremely minor bug, but filing per @jasonmalinowski's request to be captured and triaged appropriately :smile:

## Environment
Windows 8.1 x64 with Media Center, fully patched.
Visual Studio Community 2015 RC, Version 14.0.22823.1 D14REL

## Repro Steps

In a new C# file, enter code:
```csharp
namespace Foo
{
    interface Bar
    {
        void Baz(object @event);
    }
}
```
Open a new line above method declaration and type `///` to trigger automatic xmldoc generation. Text is updated to this:
```csharp
namespace Foo
{
    interface Bar
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="@event"></param>
        void Baz(object @event);
    }
}
```
Note that hovering over `@event` *does not* raise a tooltip identifying this as a reference to `(parameter) object @event` in the same manner that hovering over the parameter identifier itself does, in the method declaration.

Begin entering this text as the contents of the summary: `Processes the <paramref name=""/>` and note that Intellisense suggests `event` as the contents of the `name` attribute.  Accept the suggestion (i.e. do not include the `@` escape).

Note that hovering over this `<paramref>` *does* yield a tooltip identifying the method parameter.  (Hideous fake cursor mine :stuck_out_tongue_winking_eye:)
image

The behavior of Intellisense is consistent for both `<param>` and `<paramref>`.  If the `@` escape is included, no tooltip is shown.  If it is elided, a tooltip is shown.

## Observed Results
The behavior of the auto-generated xmldoc is inconsistent with the Intellisense behavior.  The auto-generated documentation includes the escape for the escaped identifier while Intellisense does not.  Further, intellisense offers tooltips only when not escaped.

## Expected Results
The behaviors should be consistent. Either the auto-generated documentation should elide the `@` escape, or Intellisense should include it.

I cannot find (or am not understanding :smile:) a definition of the correct behavior in Appendix A of the C# Language Specification, so I am not sure the correct outcome here other than to request that they be consistent.

Thanks!

### PR DESCRIPTION
**Pull request by diryboy**
Fix #2936

IMHO the name value for xml doc should not include language specific escape token "@", so I prefer fixing the generating part.

### CODE REVIEW

**Comment by Pilchie** [comment]
@DustinCampbell Care to take a look at this?

**Comment by sharwell** [comment]
Assuming the tests pass, :+1:

**Comment by Pilchie** [comment]
@DustinCampbell care to take a look?

File: src/EditorFeatures/CSharpTest/DocumentationComments/DocumentationCommentTests.cs [hunk 1]
```diff
@@ -58,6 +58,31 @@ public void TypingCharacter_Method()
         }
 
         [Fact, Trait(Traits.Feature, Traits.Features.DocumentationComments)]
+        public void TypingCharacter_Method_WithVerbatimParams()
```
Comment (Pilchie) [inline src/EditorFeatures/CSharpTest/DocumentationComments/DocumentationCommentTests.cs]: What is the right behavior if the identifier actually requires escaping?  Can you add a test for that case?

Comment (DustinCampbell) [inline src/EditorFeatures/CSharpTest/DocumentationComments/DocumentationCommentTests.cs]: Yes, I'd be more interested in the case where the code is something like:

```C#
int M<@int>(int x) { return 0; }
```

**Comment by diryboy** [comment]
Updated tests, actual value is used whether the identifiers require escaping or not
@sharwell @Pilchie @DustinCampbell please review.

**Comment by sharwell** [comment]
:+1: To the tests in d7499c4 (that's the only part I reviewed).

**Comment by Pilchie** [comment]
Thanks - LGTM
