### PR TITLE
Fix VariablesDeclaredWalker with recursive patterns

### LINKED ISSUE #79489: "Extract Method" handles variables defined from pattern matching poorly
**Version Used**: 
5.0.0-1.25319.11

**Steps to Reproduce**:

1. Have some statements/expressions doing pattern matching and extracting variables
2. Select said code and invoke extract method refactoring

Original code:

```csharp
static void PatternMatchingUsage()
{
  var t = (1, 2);
  // selection start
  switch (t)
  {
    case (var x, 2):
      Console.WriteLine(x);
      break;
  }
  // selection end
}
```

**Expected Behavior**:

Extract method treats extracted variables as belonging to the scope they are extracted in and does not introduce out parameters, extra declarations etc.

**Actual Behavior**:

Extracted method has extra declaration of extracted variable.

```csharp
static void PatternMatchingUsage()
{
  var t = (1, 2);
  NewMethod(t);
}

private static void NewMethod((int, int) t)
{
  int x;
  switch (t)
  {
    case (var x, 2) when x % 2 is 0:
      Console.WriteLine(x);
      break;
  }
}
```

With more involved examples Extract method might introduce out parameters which then also produce actual compiler errors, not just warnings of unused variable declarations like in the example.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #79489
@CyrusNajmabadi PTAL

### CODE REVIEW

File: src/Compilers/CSharp/Portable/FlowAnalysis/VariablesDeclaredWalker.cs [hunk 1]
```diff
@@ -73,6 +73,17 @@ private void NoteDeclaredPatternVariables(BoundPattern pattern)
             {
                 switch (pattern)
                 {
+                    case BoundRecursivePattern r:
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/VariablesDeclaredWalker.cs]: >BoundRecursivePattern [](http://example.com/codeflow?start=25&length=21)

It looks like ```BoundRecursivePattern``` is a ```BoundObjectPattern``` and whatever the case below is doing should be done for it as well. #Closed

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/VariablesDeclaredWalker.cs]: >case [](http://example.com/codeflow?start=20&length=4)

Are there other "complex" pattern forms that should be tread specially here? Like: ```BoundListPattern```, ```BoundSlicePattern```, etc. #Closed

**Comment by AlekseyTs** [comment]
>         private void NoteDeclaredPatternVariables(BoundPattern pattern)

Instead of having a helper that must know how to dive deep into patterns and rely on containing nodes to call it, can we override appropriate ```Visit...``` methods for various bound patterns and rely on regular visit process to record information for them? #Closed

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/VariablesDeclaredWalker.cs:70 in e745150. [](commit_id = e7451503a597d516fec873b1fa2e1573b55fbf6b, deletion_comment = False)

**Comment by AlekseyTs** [comment]
Done with review pass (commit 2), tests were not looked at. #Closed

**Comment by RikkiGibson** [comment]
> can we override appropriate `Visit...` methods for various bound patterns and rely on regular visit process to record information for them?

I don't think this could be solved, for example, by only overriding Visit for the specific BoundPattern kinds, which directly contain variables. Instead you would have to declare all the Visit methods for all the pattern subtypes, and write the code to traverse the parts of the patterns which could contain variables. This is because the base type Visit methods already don't do this, to the best of my understanding. I think this approach, as well as the approach in iteration 2, would also end up requiring re-implementing "safe" traversal of binary patterns (because of the need to find variables in `expr is > 0 and var variable`, for example.)

A few alternatives I considered:
1. Declare an inner class `PatternVisitor : BoundTreeWalkerWithStackGuardWithoutRecursionOnTheLeftOfBinaryOperator`, which we call into to visit patterns, which adds the variables it finds to `VariablesDeclaredWalker._variablesDeclared`. This would assume that we can't enter/exit the region in the middle of a pattern.
2. Change the base type `class VariablesDeclaredWalker : AbstractRegionDataFlowPass` and override some virtual method on `DefiniteAssignment` to allow reusing the definite assignment logic which traverses patterns in order to mark them as assigned.

It's possible I missed something that would make fixing this easier to accomplish. Let me know if you have any further thoughts.

**Comment by AlekseyTs** [comment]
>I don't think this could be solved, for example, by only overriding Visit for the specific BoundPattern kinds, which directly contain variables. Instead you would have to declare all the Visit methods for all the pattern subtypes, and write the code to traverse the parts of the patterns which could contain variables.

I guess it would be fine for `NoteDeclaredPatternVariables` to implement its own traversal, but let's do it similar to the way  `DefiniteAssignmentPass.VisitPattern` does it. I.e. it should throw for `default` case. #Closed

**Comment by AlekseyTs** [comment]
>             if (IsInside)

Are there situations when we need to adjust the ```IsInside``` state while traversing the pattern? #Closed

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/VariablesDeclaredWalker.cs:72 in e745150. [](commit_id = e7451503a597d516fec873b1fa2e1573b55fbf6b, deletion_comment = False)

**Comment by RikkiGibson** [comment]
> Are there situations when we need to adjust the `IsInside` state while traversing the pattern?

It looks like it is possible to AnalyzeDataFlow with the Expression inside a pattern which takes constant values. I think only in error cases can you declare variables in such expressions, but, I added test `RegionWithinSubpattern03` to make sure the API indicates that the variable declaration is present.

File: src/Compilers/CSharp/Portable/FlowAnalysis/VariablesDeclaredWalker.cs [hunk 2]
```diff
@@ -45,13 +44,13 @@ internal VariablesDeclaredWalker(CSharpCompilation compilation, Symbol member, B
...
             base.Free();
-            _variablesDeclared = null;
+            _variablesDeclared = null!;
         }
 
         public override void VisitPattern(BoundPattern pattern)
         {
-            base.VisitPattern(pattern);
             NoteDeclaredPatternVariables(pattern);
+            base.VisitPattern(pattern);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/VariablesDeclaredWalker.cs:53]: >base.VisitPattern(pattern); [](http://example.com/codeflow?start=12&length=27)

Order of operations was changed. Is the order significant? #Closed

File: src/Compilers/CSharp/Test/Emit3/FlowAnalysis/PatternsVsRegions.cs [hunk 3]
```diff
@@ -148,5 +148,557 @@ public static void Main(string[] args)
...
+        public void RegionInSwitch01()
+        {
+            var dataFlowAnalysisResults = CompileAndAnalyzeDataFlowExpression("""
+                static void PatternMatchingUsage()
+                {
+                  var t = (1, 2);
+                  // selection start
+                  switch (t)
+                  {
+                    case /*<bind>*/(var x, 2)/*</bind>*/:
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit3/FlowAnalysis/PatternsVsRegions.cs]: >var x [](http://example.com/codeflow?start=36&length=5)

Why is it not considered declared? #Closed

File: src/Compilers/CSharp/Portable/FlowAnalysis/VariablesDeclaredWalker.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/VariablesDeclaredWalker.cs:53]: Yes, previously the base call would split the state, and we would end up visiting an expression while in a split state. The caller of VisitPattern does expect to be in a split state afterwards so opted to solve by moving the base call to the end.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 9)

File: src/Compilers/CSharp/Test/Emit3/FlowAnalysis/PatternsVsRegions.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Emit3/FlowAnalysis/PatternsVsRegions.cs]: The `/*<bind>*/` comment was incorrect, it resulted in analyzing dataflow for the `2` expression inside the pattern. Since AnalyzeDataFlow does not accept patterns as arguments, I'm changing the test to pass the switch statement.

File: src/Compilers/CSharp/Portable/FlowAnalysis/VariablesDeclaredWalker.cs [hunk 4]
```diff
@@ -69,26 +68,104 @@ protected override void VisitSwitchSection(BoundSwitchSection node, bool isLastS
         /// </summary>
         private void NoteDeclaredPatternVariables(BoundPattern pattern)
         {
-            if (IsInside)
+            switch (pattern)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/FlowAnalysis/VariablesDeclaredWalker.cs:71]: This walk is roughly based on [DefiniteAssignment.VisitPattern](https://github.com/dotnet/roslyn/blob/7b48e0879c2f350cfc8b5d828c120c902873ce0c/src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs#L1953).
