### PR TITLE
Harden access to MetadataReader

### LINKED ISSUE #2992: Throw an ObjectDisposedException instead of an AccessViolationException
In the following code, Roslyn throws an AccessViolationException on the last line. 
```c#
var md = AssemblyMetadata.CreateFromFile(typeof(object).Assembly.Location);
var compilation = CSharpCompilation.Create("test", references: new[] { md.GetReference() });

// Use the Compilation once to force lazy initialization of the underlying MetadataReader
compilation.GetTypeByMetadataName("System.Version").GetMembers();

md.Dispose();

compilation.GetTypeByMetadataName("System.Exception").GetMembers(); // <-- AccessViolationException is thrown here
```

### PR DESCRIPTION
**Pull request by tmat**
Fixes #2992 and #2988. Both are crashes.

**Scenarios**
1) When a referenced metadata image is empty the compiler should report an error and not crash. 
2) When ModuleMetadata is disposed the compiler should throw ObjectDisposedException and not AV. The primary benefit is that ObjectDisposedException clearly identifies what went wrong (so the code that disposed the metadata object can be blamed) while AV just means some memory is read that shouldn't and usually results in blaming the MetadataReader, which is not in fault. This was also reported by a customer (https://github.com/dotnet/roslyn/pull/25) and also happened in XAML designer in VS.

**Fix**
Add a couple of additional checks to PEModule.MetadataReader property. As described in https://github.com/dotnet/roslyn/pull/25 we don't guarantee (2), it would be too much work and it might negatively impact perf. However we can do a very cheap check that avoids AV i 99% cases (when there is not a race between a thread that disposes the metadata and the thread accessing PE symbols).

The root cause of 1) is in System.Reflection.Metadata and is being fixed (dotnet/corefx#1815). To avoid a bigger change of updating the nuget package for RTM we can do a simple check in Roslyn to avoid hitting the PE reader issue.

**Testing**
Added unit tests for both languages.

@ManishJayaswal

### CODE REVIEW

**Comment by tmat** [comment]
@VSadov @AlekseyTs @jaredpar Please review.

File: src/Compilers/Core/Portable/MetadataReader/PEModule.cs [hunk 1]
```diff
@@ -139,35 +140,54 @@ internal PEReader PEReaderOpt
...
                 {
-                    MetadataReader newReader;
+                    InitializeMetadataReader();
+                }
+                else if (_isDisposed)
+                {
+                    // Without locking, which might be expensive, we can't guarantee that the underlying memory 
+                    // won't be accessed after the metadata object is disposed. However we can do a cheap check here that 
+                    // handles most cases.
+                    ThrowMetadataDisposed();
```
Comment (VSadov) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: I agree. I actually think many cases may not even involve threading.

File: src/Compilers/Core/Portable/MetadataReader/PEModule.cs [hunk 2]
```diff
@@ -139,35 +140,54 @@ internal PEReader PEReaderOpt
...
+        internal MetadataReader MetadataReader
         {
             get
             {
                 if (_lazyMetadataReader == null)
                 {
-                    MetadataReader newReader;
+                    InitializeMetadataReader();
+                }
+                else if (_isDisposed)
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: Why not just make this an unconditional check?  In the current form it doesn't appear this will protect against this pattern:

``` 
var m = new MetadataReader();
m.Dispose();
m.MetadataReader ... 
```

Yeah that's a bit pathological.

**Comment by VSadov** [comment]
LGTM and recommend for the stabilization branch.

File: src/Compilers/Core/Portable/MetadataReader/PEModule.cs (hunk 2 above)
Comment (tmat) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: No the pattern is:
1) host creates ModuleMetadata 
2) hosted code accesses PE Symbols from a compilation provided by the host 
3) host disposes ModuleMetadata because it thinks nobody is using the PE Symbols anymore
4) hosted code uses the PE Symbols

Comment (jaredpar) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: @tmat i agree that's the existing pattern.  But while we're taking the time to harden the code why not just harden it against future scenarios, and other bugs, as well.

Comment (tmat) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: Oh, I see what you mean. Actually the fix is guarding against your pattern as well. ```m.MetadataReader``` goes thru the same code path.

Comment (tmat) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: @jaredpar Now I also see what you mean by unconditional :) Yes, I'll do that.

**Comment by jaredpar** [comment]
:+1:

**Comment by AlekseyTs** [comment]
LGTM

**Comment by MattGertz** [comment]
Approved 5/21 by ML Shiproom.

**Comment by MattGertz** [comment]
Two unit tests are failing, so we cannot approve this yet.

**Comment by MattGertz** [comment]
MoreInfo on 5/21 by ML Shiproom.

**Comment by tmat** [comment]
@mattgertz Oops. Sorry about that, I accidentally run just a subset of the tests locally. Fixed.

**Comment by tmat** [comment]
@dotnet-bot retest this please

**Comment by MattGertz** [comment]
Approved 5/22 by ML Shiproom.

File: src/Compilers/Core/Portable/MetadataReader/PEModule.cs [hunk 3]
```diff
@@ -139,35 +140,55 @@ internal PEReader PEReaderOpt
...
+            if (_metadataPointerOpt != IntPtr.Zero)
+            {
+                newReader = new MetadataReader((byte*)_metadataPointerOpt, _metadataSizeOpt, MetadataReaderOptions.ApplyWindowsRuntimeProjections, StringTableDecoder.Instance);
+            }
+            else
+            {
+                Debug.Assert(_peReaderOpt != null);
+
+                // Checking for an empty image is a workaround for https://github.com/dotnet/corefx/issues/1815: 
+                if (_peReaderOpt.IsEntireImageAvailable && _peReaderOpt.GetEntireImage().Length == 0 || !_peReaderOpt.HasMetadata)
```
Comment (pharring) [inline src/Compilers/Core/Portable/MetadataReader/PEModule.cs]: GetEntireImage causes the entire image to be memory mapped. This causes a VM regression in the Picasso "Start Debugging scenario."
