### PR TITLE
Change the order of operands to object.Equals() for constant pattern match

### LINKED ISSUE #16513: The semantic of constant pattern
I propose to change the semantic of constant pattern match from current:
```c#
foo is 42 /* == */ object.Equals(foo, 42)
```
…to the opposite:
```c#
foo is 42 /* == */ object.Equals(42, foo)
```

And this is how `object.Equals(object, object)` is implemented:
```c#
public static bool Equals(Object objA, Object objB) {
  if (objA==objB) {
    return true;
  }
  if (objA==null || objB==null) {
    return false;
  }
  return objA.Equals(objB);
}
```

The reasons behind proposed change:
1. Currently the "constant patterns" are not that "constant": generated code involves the execution of arbitrary 'object.Equals(object)' implementation on `foo` instance (in the case it is not `null`), since `object.Equals(object, object)` invokes it on first argument.
2. The idiom `foo is null` do not actually means `((object) foo) == null` as most of users would expect. It is easy to define a type that would pass `foo is null` check while being not-`null` (how would this play with future non-nullable types and their dataflow analysis?).
3. You won't be able to get rid of suboptimal code for constant patterns of reference types #13247, since such optimizations would change the semantic of matching.
4. If the arguments of `object.Equals()` would be reversed, the nice property of `is` expression would be restored — if right operand (type or pattern) has a type, the `is` expression only produce `true` if the left operand is of implicitly convertible type. Constant patterns do have types, literal expression do have types, `42` is of type `int`… who would expect `(int) foo` after successful `foo is 42` check to throw `InvalidCastException`?

p.s. Maybe it's a good idea to behave like F#: literal patterns of type `int` are only allowed when pattern is matched against the value of `int` type (but that's because of ML's "no implicit conversions" rule, I think).

cc @gafter

### PR DESCRIPTION
**Pull request by gafter**
**Customer scenario**

The semantics of pattern-matching against a constant are different between the `is` operator and the `switch` statement. They were intended to be the same, but the order of operands to `object.Equals` in the generated code is backwards for the `is` operator. We need to fix this today, before RTM, so that users do not come to depend on the incorrect behavior (now-or-never language change). See also #16513.

**Bugs this fixes:** 

Fixes #16513

**Workarounds, if any**

Avoid using the new `is` operator with a constant right-hand-side.

**Risk**

Tiny. The fix is a one-line change to place the operands in the correct order.

**Performance impact**

None, as we are still executing the same code as before, albeit in a different order. However, with the changed order it will be possible for us to generate much better code in the future.

**Is this a regression from a previous update?**

No, as the feature is new.

**Root cause analysis:**

A subtle oversight in code generation. This might have been caught earlier if the compiler team had followed through on its plan to assign a developer to perform adversarial testing of each new feature under development.

**How was the bug found?**

Customer reported.

@dotnet/roslyn-compiler Please review this teensy tiny RTM fix.

### CODE REVIEW

**Comment by TyOverby** [comment]
👍

**Comment by gafter** [comment]
@MattGertz Tagging for ask mode.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 1]
```diff
@@ -4295,6 +4295,40 @@ public static void Main(int* a, var* c, Typ* e)
...
+    override public bool Equals(object other)
+    {
+        return other is int x;
+    }
+    override public int GetHashCode() => 0;
+}
+";
+            var compilation = CreateCompilationWithMscorlib45(source, options: TestOptions.DebugExe);
+            compilation.VerifyDiagnostics();
+            var comp = CompileAndVerify(compilation, expectedOutput: @"False
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: >var comp = CompileAndVerify(compilation, expectedOutput: @"False [](start = 12, length = 64)

A check like this potentially might fail on non-English OS.

**Comment by AlekseyTs** [comment]
LGTM

**Comment by jcouv** [comment]
This was approved by shiproom.

**Comment by natidea** [comment]
Approved to merge via [369789](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/369789)

**Comment by alrz** [comment]
In #16710 its decided to generate 42.Equals but this only changes the order of args. Is that correct?

**Comment by gafter** [comment]
@alrz Almost. It changes the order of args, but by doing so it opens up the possibility of generating much better (equivalent) code later.
