### PR TITLE
Fixed crash in `RemoveUnnecessarySuppressions` caused by multi-variable declaration 

### LINKED ISSUE #78786: Crash in `RemoveUnnecessarySuppressions` caused by multi-variable declaration
Crash in `RemoveUnnecessarySuppressions` caused by multi-variable declaration 

**Version Used**: 

Encountered in VS 2022 17.14.0 Preview 7.0. Also repro'ed in main.

**Steps to Reproduce**:

Attempt to remove the unnecessary suppression in the following declaration:

```cs
namespace Test;

public static class C
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>")]
    public static event EventHandler Foo, Bar;
}
```

**Expected Behavior**:
Removal of unncessary suppression attribute.

**Actual Behavior**:
Crash:

Image

**Stack Trace**:

```
StreamJsonRpc.RemoteInvocationException: An item with the same key has already been added. Key: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>")
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__156`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__18`1.MoveNext()
RPC server exception:
System.ArgumentException: An item with the same key has already been added. Key: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>")
      at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
      at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
      at Microsoft.CodeAnalysis.RemoveUnnecessarySuppressions.AbstractRemoveUnnecessaryInlineSuppressionsDiagnosticAnalyzer.ProcessSuppressMessageAttributesAsync(SyntaxNode root, SemanticModel semanticModel, Nullable`1 span, PooledDictionary`2 idToSuppressMessageAttributesMap, PooledDictionary`2 suppressMessageAttributesToIsUsedMap, ImmutableArray`1 userIdExclusions, ImmutableArray`1 userCategoryExclusions, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.RemoveUnnecessarySuppressions.AbstractRemoveUnnecessaryInlineSuppressionsDiagnosticAnalyzer.AnalyzeAsync(SemanticModel semanticModel, Nullable`1 span, CompilationWithAnalyzers compilationWithAnalyzers, Func`2 getSupportedDiagnostics, Action`1 reportDiagnostic, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.Extensions.<GetPragmaSuppressionAnalyzerDiagnosticsAsync>g__AnalyzeDocumentAsync|12_0(CompilationWithAnalyzers hostCompilationWithAnalyzers, DiagnosticAnalyzerInfoCache analyzerInfoCache, IPragmaSuppressionsAnalyzer suppressionAnalyzer, Document document, Nullable`1 span, Action`1 reportDiagnostic, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.Extensions.GetPragmaSuppressionAnalyzerDiagnosticsAsync(CompilationWithAnalyzersPair compilationWithAnalyzers, DocumentAnalysisScope documentAnalysisScope, Project project, DiagnosticAnalyzerInfoCache analyzerInfoCache, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.Extensions.GetAnalysisResultAsync(CompilationWithAnalyzersPair compilationWithAnalyzers, DocumentAnalysisScope documentAnalysisScope, Project project, DiagnosticAnalyzerInfoCache analyzerInfoCache, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.AnalyzeAsync(CompilationWithAnalyzersPair compilationWithAnalyzers, BidirectionalMap`2 analyzerToIdMap, ImmutableArray`1 projectAnalyzers, ImmutableArray`1 hostAnalyzers, SkippedHostAnalyzersInfo skippedAnalyzersInfo, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.GetDiagnosticsAsync(ImmutableArray`1 projectAnalyzerIds, ImmutableArray`1 hostAnalyzerIds, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.GetHighPriorityDiagnosticsAsync(ImmutableArray`1 projectAnalyzerIds, ImmutableArray`1 hostAnalyzerIds, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.<>c__DisplayClass3_0.<<CalculateDiagnosticsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass7_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.CalculateDiagnosticsAsync(Checksum solutionChecksum, DiagnosticArguments arguments, CancellationToken cancellationToken)

```

### PR DESCRIPTION
**Pull request by John-Leitch**
This PR fixes multi-variable declaration support in `RemoveUnnecessarySuppressions` by preventing redundant evaluation of symbols from variable declaration nodes containing more than one variable.

Fixes #78786

### CODE REVIEW

File: src/Features/CSharpTest/Diagnostics/Suppression/RemoveUnnecessaryPragmaSuppressionsTests.cs [hunk 1]
```diff
@@ -461,6 +461,40 @@ void M()
...
+        {
+            Field,
+            Event
+        }
+
+        [Theory, CombinatorialData]
+        [WorkItem("https://github.com/dotnet/roslyn/issues/78786")]
+        public async Task TestRemoveDiagnosticSuppression_Attribute_MultiVariableDeclaration(MultiVariableTestKind testKind)
+        {
+            var (keyword, type) = testKind switch
```
Comment (DoctorKrolic) [inline src/Features/CSharpTest/Diagnostics/Suppression/RemoveUnnecessaryPragmaSuppressionsTests.cs]: Don't overengineere, just make `keyword` and `type` test parameters directly

File: src/Analyzers/Core/Analyzers/RemoveUnnecessarySuppressions/AbstractRemoveUnnecessaryPragmaSuppressionsDiagnosticAnalyzer.cs [hunk 2]
```diff
@@ -811,9 +817,17 @@ private async Task<bool> ProcessSuppressMessageAttributesAsync(
                             // NOTE: For attributes on partial symbols with multiple declarations, we conservatively
                             // consider them as used and avoid unnecessary attribute analysis because that would potentially
                             // require analysis across multiple files, which can be expensive from a performance standpoint.
+
```
Comment (DoctorKrolic) [inline src/Analyzers/Core/Analyzers/RemoveUnnecessarySuppressions/AbstractRemoveUnnecessaryPragmaSuppressionsDiagnosticAnalyzer.cs]:
```suggestion
```

**Comment by DoctorKrolic** [comment]
Also please add "Fixes https://github.com/dotnet/roslyn/issues/78786" to your PR description, so that GH automatically links that issue with the PR and closes it when the PR is merged

File: src/Features/CSharpTest/Diagnostics/Suppression/RemoveUnnecessaryPragmaSuppressionsTests.cs (hunk 1 above)
Comment (John-Leitch) [reply src/Features/CSharpTest/Diagnostics/Suppression/RemoveUnnecessaryPragmaSuppressionsTests.cs]: Simplified with `InlineDataAttribute`.

**Comment by CyrusNajmabadi** [comment]
Unclear why we need a loop in the first place. If we're just going to break when we have multiple. Why not just process the first symbol only?

**Comment by John-Leitch** [comment]
> Unclear why we need a loop in the first place. If we're just going to break when we have multiple. Why not just process the first symbol only?

I assumed it was there for a reason, but now that you mention it, I don't see why. None of the tests seem to get more than one symbol except the case I've added, so they all pass just checking the first. Not sure if there are uncovered case though.

**Comment by CyrusNajmabadi** [comment]
Ok.  Can you change to no loop, with a comment explaining why that is desirable here?  Thanks!

**Comment by John-Leitch** [comment]
Updated as requested. However, upon doing some testing to confirm the safety of checking only the first symbol, I caught a variant of the issue that is triggered by partial methods and props. I've included a fix for that as well as some test coverage.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks!
