### PR TITLE
Fixing IntroduceVariable for expression bodied void-returning methods, local functions & accessors

### LINKED ISSUE #13218: "IntroduceVariable" refactoring does not preserve empty line above local declaration
**Steps to Reproduce**:
Apply refactoring "Introduce local for all occurrences of 'string.Empty'

**Code Before**:

``` csharp
public class Foo
{
    public void Bar(string s)
    {
        s = null;

        Bar(string.Empty);

        s = string.Empty;
    }
}
```

**Code After**:

``` csharp
public class Foo
{
    public void Bar(string s)
    {
        s = null;
        var empty = string.Empty;
        Bar(empty);

        s = empty;
    }
}
```

**Expected Behavior**:
Empty line above local declaration should be preserved

**Actual Behavior**:
Empty line above local declaration is removed

### LINKED ISSUE #24807: Introduce Local generates an invalid return statement for void-returning expression methods
**Version Used**:

VS 15.6 Preview 4

**Steps to Reproduce**:

```cs
private void bar(int baz)
{ }

private void foo()
    => bar(100);
```

Mark the `100` and "Introduce local constant"

**Expected Behavior**:
```cs
private void bar(int baz)
{ }

private void foo()
{
    const int Baz = 100;
    bar(Baz);
}
```

**Actual Behavior**:
```cs
private void bar(int baz)
{ }

private void foo()
{
    const int Baz = 100;
    return bar(Baz); // note the additional return statement
}
```

introduce-local-return

### PR DESCRIPTION
**Pull request by Neme12**
fixes #24807 + missing support for new language features: expression bodied constructors, accessors & local functions

fixes #13218

[edited - jcouv]
### Example for #24807
```C#
private void foo()
    => bar([|100|]);
```
currently refactors to
```C#
private void foo()
{
    const int Baz = 100;
    return bar(Baz); // note the additional return statement
}
```

### Example for #13218

**Code Before**:

``` csharp
public class Foo
{
    public void Bar(string s)
    {
        s = null;

        Bar(string.Empty);

        s = string.Empty;
    }
}
```

**Code After**:

``` csharp
public class Foo
{
    public void Bar(string s)
    {
        s = null; // note: empty line below was removed
        var empty = string.Empty;
        Bar(empty);

        s = empty;
    }
}
```

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/CodeActions/IntroduceVariable/IntroduceVariableTests.cs [hunk 1]
```diff
@@ -3172,7 +3172,31 @@ class B
 
         [WorkItem(528, "http://github.com/dotnet/roslyn/issues/528")]
         [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsIntroduceVariable)]
-        public async Task TestIntroduceLocalInExpressionBodiedMethod()
+        public async Task TestIntroduceFieldInExpressionBodiedMethod()
```
Comment (Neme12) [inline src/EditorFeatures/CSharpTest/CodeActions/IntroduceVariable/IntroduceVariableTests.cs]: I actually reordered this test (TestIntroduce**Field**InExpressionBodiedMethod, TestIntroduce**Local**InExpressionBodiedMethod) and another test down below, because the sequence in the tests was: local field, local field and then the rest of the tests is field local, field local. I hope it's not too bad in the diff.

File: src/EditorFeatures/CSharpTest/CodeActions/IntroduceVariable/IntroduceVariableTests.cs [hunk 2]
```diff
@@ -3197,16 +3221,42 @@ int M1()
...
+        const int {|Rename:V|} = 1;
+        Console.WriteLine(V + 2 + 3 + m);
+    }
+}";
+
+            await TestInRegularAndScriptAsync(code, expected, index: 2);
+        }
+
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsIntroduceVariable)]
+        public async Task TestIntroduceFieldInExpressionBodiedConstructor()
```
Comment (Neme12) [inline src/EditorFeatures/CSharpTest/CodeActions/IntroduceVariable/IntroduceVariableTests.cs]: there were also bugs related to constructors (the case just wasn't covered)

File: src/EditorFeatures/CSharpTest/CodeActions/IntroduceVariable/IntroduceVariableTests.cs [hunk 3]
```diff
@@ -3215,22 +3265,99 @@ class T
...
+    }
+}";
+
+            await TestInRegularAndScriptAsync(code, expected, index: 2);
+        }
+
         [WorkItem(528, "http://github.com/dotnet/roslyn/issues/528")]
         [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsIntroduceVariable)]
-        public async Task TestIntroduceLocalInExpressionBodiedOperator()
+        public async Task TestIntroduceFieldInExpressionBodiedOperator()
```
Comment (Neme12) [inline src/EditorFeatures/CSharpTest/CodeActions/IntroduceVariable/IntroduceVariableTests.cs]: this is the second test I reordered with the one below

File: src/EditorFeatures/CSharpTest/CodeActions/IntroduceVariable/IntroduceVariableTests.cs [hunk 4]
```diff
@@ -3330,6 +3457,46 @@ public struct DBBool
             await TestInRegularAndScriptAsync(code, expected);
         }
 
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsIntroduceVariable)]
+        public async Task TestIntroduceLocalInExpressionBodiedConversionOperator()
```
Comment (Neme12) [inline src/EditorFeatures/CSharpTest/CodeActions/IntroduceVariable/IntroduceVariableTests.cs]: This test was just missing. It must have been left out. So I added it.

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs [hunk 5]
```diff
@@ -74,7 +77,7 @@ internal partial class CSharpIntroduceVariableService
         {
             var anonymousMethodParameters = GetAnonymousMethodParameters(document, expression, cancellationToken);
             var lambdas = anonymousMethodParameters.SelectMany(p => p.ContainingSymbol.DeclaringSyntaxReferences.Select(r => r.GetSyntax(cancellationToken)).AsEnumerable())
-                                                   .Where(n => n is ParenthesizedLambdaExpressionSyntax || n is SimpleLambdaExpressionSyntax)
+                                                   .OfType<LambdaExpressionSyntax>()
```
Comment (Neme12) [inline src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: this change is unrelated, I just cleaned it up

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs [hunk 6]
```diff
@@ -173,70 +176,60 @@ private bool CanUseVar(ITypeSymbol typeSymbol)
...
+                : SyntaxFactory.ExpressionStatement(newExpression) as StatementSyntax;
+
+            var newBody = SyntaxFactory.Block(declarationStatement, convertedStatement)
                                        .WithLeadingTrivia(leadingTrivia)
                                        .WithTrailingTrivia(oldBody.GetTrailingTrivia())
                                        .WithAdditionalAnnotations(Formatter.Annotation);
 
-            SyntaxNode newParentingNode = null;
-            if (oldParentingNode is BasePropertyDeclarationSyntax baseProperty)
+            SyntaxNode newParentingNode = oldParentingNode; // in case we fail for some reason, at least don't remove it!
```
Comment (Neme12) [inline src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: before it used to completely remove local functions if it was invoked inside them because of the null

File: src/Workspaces/CSharp/Portable/Extensions/BaseMethodDeclarationSyntaxExtensions.cs [hunk 7]
```diff
@@ -6,17 +6,17 @@ namespace Microsoft.CodeAnalysis.CSharp.Extensions
 {
     internal static class BaseMethodDeclarationSyntaxExtensions
     {
-        public static BaseMethodDeclarationSyntax WithSemicolonToken(this BaseMethodDeclarationSyntax node, SyntaxToken token)
+        public static BaseMethodDeclarationSyntax WithSemicolonToken(this BaseMethodDeclarationSyntax node, SyntaxToken semicolonToken)
```
Comment (Neme12) [inline src/Workspaces/CSharp/Portable/Extensions/BaseMethodDeclarationSyntaxExtensions.cs]: I renamed this parameter to exactly match the one in MethodDeclarationSyntax.WithSemicolonToken and the other methods

Comment (Neme12) [reply src/Workspaces/CSharp/Portable/Extensions/BaseMethodDeclarationSyntaxExtensions.cs]: BTW, why do these extension methods ignore nulls?

File: src/Workspaces/CSharp/Portable/Extensions/BasePropertyDeclarationSyntaxExtensions.cs [hunk 8]
```diff
@@ -0,0 +1,58 @@
...
+                }
+            }
+
+            return node;
+        }
+
+        /// <summary>
+        /// Available if <paramref name="node"/> is <see cref="PropertyDeclarationSyntax"/> or <see cref="IndexerDeclarationSyntax"/>.
+        /// </summary>
+        public static SyntaxToken TryGetSemicolonToken(this BasePropertyDeclarationSyntax node)
```
Comment (Neme12) [inline src/Workspaces/CSharp/Portable/Extensions/BasePropertyDeclarationSyntaxExtensions.cs]: I'm not exactly sure this is the right solution. SemicolonToken is on properties & indexers but not event declarations, so I'm not sure if it belongs here. TryGetSemicolonToken is OK-ish but TryWithSemicolonToken seems ugly. But it's still useful to help avoid code duplication.

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs [hunk 9]
```diff
@@ -56,9 +56,12 @@ internal partial class CSharpIntroduceVariableService
                         document, block, expression, newLocalName, declarationStatement, allOccurrences, cancellationToken).ConfigureAwait(false);
 
                 case ArrowExpressionClauseSyntax arrowExpression:
+                    var method = document.SemanticModel.GetDeclaredSymbol(arrowExpression.Parent) as IMethodSymbol;
+                    bool createReturnStatement = !method?.ReturnsVoid ?? true; // this will be null for properties & indexers, both of which return a value
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: what if it's the body of a setter?   Or will that give you an IMethodSymbol?  Is htis *only* for properties without accessors that have ```=> expr;```?

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs [hunk 10]
```diff
@@ -173,70 +176,60 @@ private bool CanUseVar(ITypeSymbol typeSymbol)
...
-            if (oldParentingNode is BasePropertyDeclarationSyntax baseProperty)
+            SyntaxNode newParentingNode = oldParentingNode; // in case we fail for some reason, at least don't remove it!
+            
+            switch (oldParentingNode)
             {
-                var getAccessor = SyntaxFactory.AccessorDeclaration(SyntaxKind.GetAccessorDeclaration, newBody);
-                var accessorList = SyntaxFactory.AccessorList(SyntaxFactory.List(new[] { getAccessor }));
+                case BasePropertyDeclarationSyntax baseProperty:
+                    var getAccessor = SyntaxFactory.AccessorDeclaration(SyntaxKind.GetAccessorDeclaration, newBody);
+                    var accessorList = SyntaxFactory.AccessorList(SyntaxFactory.List(new[] { getAccessor }));
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: i think there SyntaxFactory.SingletonList right?

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs (hunk 9 above)
Comment (Neme12) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: the setter will give a symbol, getter will too, it's only a top level expression body like this that won't: `int A => 5;`

and there are tests for setters too

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs (hunk 10 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: do you use getAccessor below?  If not, consider inlining directly.

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs [hunk 11]
```diff
@@ -173,70 +176,60 @@ private bool CanUseVar(ITypeSymbol typeSymbol)
...
+            var newBody = SyntaxFactory.Block(declarationStatement, convertedStatement)
                                        .WithLeadingTrivia(leadingTrivia)
                                        .WithTrailingTrivia(oldBody.GetTrailingTrivia())
                                        .WithAdditionalAnnotations(Formatter.Annotation);
 
-            SyntaxNode newParentingNode = null;
-            if (oldParentingNode is BasePropertyDeclarationSyntax baseProperty)
+            SyntaxNode newParentingNode = oldParentingNode; // in case we fail for some reason, at least don't remove it!
+            
+            switch (oldParentingNode)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: consider extracting this all into a helper method.

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs [hunk 12]
```diff
@@ -173,70 +176,60 @@ private bool CanUseVar(ITypeSymbol typeSymbol)
...
-
-                if (newParentingNode.IsKind(SyntaxKind.PropertyDeclaration))
-                {
-                    var propertyDeclaration = ((PropertyDeclarationSyntax)newParentingNode);
-                    newParentingNode = propertyDeclaration
+                    newParentingNode = baseProperty
+                        .RemoveNode(oldBody, SyntaxRemoveOptions.KeepNoTrivia)
                         .WithAccessorList(accessorList)
+                        .TryWithSemicolonToken(SyntaxFactory.Token(SyntaxKind.None))
+                        .WithTrailingTrivia(baseProperty.TryGetSemicolonToken().TrailingTrivia);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: this feels strange.  why not just do:   baseProperty.WithoutTrivia().WithAccessorList(...).TryWith()...WithTriviaFrom(baseProperty)?

Comment (Neme12) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: i don't know, this is the original code, I tried to only change what I needed and not question it

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs [hunk 13]
```diff
@@ -173,70 +176,60 @@ private bool CanUseVar(ITypeSymbol typeSymbol)
...
+                    break;
+                case AccessorDeclarationSyntax accessor:
+                    newParentingNode = accessor
+                        .RemoveNode(oldBody, SyntaxRemoveOptions.KeepNoTrivia)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: the removenode parts seems weird.  I'm not sure what you're trying to accomplish here.  I feel like we'd want the concept to be "move all the leading/trailing trivia from the original accessor over to the new accessor.  Is that right?

File: src/Workspaces/CSharp/Portable/Extensions/BaseMethodDeclarationSyntaxExtensions.cs (hunk 7 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/CSharp/Portable/Extensions/BaseMethodDeclarationSyntaxExtensions.cs]: > BTW, why do these extension methods ignore nulls?

As per the gitter conversation: to make it less unpleasant to transform trees and have to up front deal with all the null possible nodes in a tree

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs (hunk 13 above)
Comment (Neme12) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: it does... but i'm not the one who wrote it... as i said, if i could i would probably rewrite the whole thing

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: > it does... but i'm not the one who wrote it... as i said, if i could i would probably rewrite the whole thing

You are allowed to do this :)

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs (hunk 12 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: IN this case, since you're changing it, i think it would be beneficial to just do things in a cleaner way if possible.

Comment (Neme12) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: OK

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: Discussed in gitter.  What i suggested would lead to a change in behavior.  That change would likely be *beneficial*.  But to keep the scope of this PR down, it doesn't have to happen here.

File: src/Workspaces/CSharp/Portable/Extensions/BasePropertyDeclarationSyntaxExtensions.cs (hunk 8 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/CSharp/Portable/Extensions/BasePropertyDeclarationSyntaxExtensions.cs]: Seems fine.  It's an internal helper.

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs (hunk 12 above)
Comment (Neme12) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: it wouldn't, I was talking about making use of [ArrowExpressionClauseSyntaxExtensions.TryConvertToBlock](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Extensions/ArrowExpressionClauseSyntaxExtensions.cs,bb53b4cb5bf05658). That would bring consistency with other code fixes that expend expression bodies into blocks, but would change behavior. Also it's called "Try" because in some cases with preprocessor directives it will just return false - this can't be expanded. I don't know what that should even do here. Not offer "inline variable"?

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: >  I don't know what that should even do here. Not offer "inline variable"?

Seems acceptable.  If you can't make the transformation, then you can't really offer the feature.

> I would definitely like to get consistent behavior across these fixes but I don't know if I can do it here.

That seems fine.

> And there are questions to be answered about which behavior to pick. And what to do about the directives.

Do you have any specific questions?  If so, we can attempt to answer them here (or gitter, or through some other issue).

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs (hunk 11 above)
Comment (Neme12) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: I did in fact consider that :D i'll do it after all

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs [hunk 14]
```diff
@@ -95,16 +100,14 @@ internal partial class CSharpIntroduceVariableService
...
             ExpressionSyntax expression,
             IdentifierNameSyntax newLocalName,
             LocalDeclarationStatementSyntax declarationStatement,
             bool allOccurrences,
             CancellationToken cancellationToken)
         {
-            var oldBody = oldLambda is ParenthesizedLambdaExpressionSyntax
-                ? (ExpressionSyntax)((ParenthesizedLambdaExpressionSyntax)oldLambda).Body
-                : (ExpressionSyntax)((SimpleLambdaExpressionSyntax)oldLambda).Body;
+            var oldBody = (ExpressionSyntax)oldLambda.Body;
```
Comment (Neme12) [inline src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: completely unrelated, this was just really bothering me

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs [hunk 15]
```diff
@@ -115,24 +118,20 @@ internal partial class CSharpIntroduceVariableService
                 ? SyntaxFactory.Block(declarationStatement)
                 : SyntaxFactory.Block(declarationStatement, SyntaxFactory.ReturnStatement(rewrittenBody));
 
-            newBody = newBody.WithAdditionalAnnotations(Formatter.Annotation);
-
-            var newLambda = oldLambda is ParenthesizedLambdaExpressionSyntax
-                ? ((ParenthesizedLambdaExpressionSyntax)oldLambda).WithBody(newBody)
-                : (SyntaxNode)((SimpleLambdaExpressionSyntax)oldLambda).WithBody(newBody);
+            var newLambda = oldLambda.WithBody(newBody.WithAdditionalAnnotations(Formatter.Annotation));
```
Comment (Neme12) [inline src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: completely unrelated, this was just really bothering me

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs (hunk 14 above)
Comment (Neme12) [inline src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: completely unrelated, this was just really bothering me

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs [hunk 16]
```diff
@@ -98,16 +100,14 @@ internal partial class CSharpIntroduceVariableService
...
             ExpressionSyntax expression,
             IdentifierNameSyntax newLocalName,
             LocalDeclarationStatementSyntax declarationStatement,
             bool allOccurrences,
             CancellationToken cancellationToken)
         {
-            var oldBody = oldLambda is ParenthesizedLambdaExpressionSyntax
-                ? (ExpressionSyntax)((ParenthesizedLambdaExpressionSyntax)oldLambda).Body
-                : (ExpressionSyntax)((SimpleLambdaExpressionSyntax)oldLambda).Body;
+            var oldBody = (ExpressionSyntax)oldLambda.Body;
```
Comment (Neme12) [inline src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: completely unrelated, this was just really bothering me

**Comment by Neme12** [comment]
I got a little carried away and decided to change/refactor 2 unrelated methods in the same file, specifically with `IntroduceLocalDeclarationIntoBlockAsync` and `IntroduceLocalForSingleOccurrenceIntoBlock` (this method is now gone).

This introduces some changes in existing behavior (but in my opinion results in better behavior), so if these changes are undesirable, I can remove the last commit.

I wanted to get rid of the special case and unify these methods. Now, instead of the code at one point branching out into these completely different cases, there's just an if statement with the rest of the method being the same (so after branching out the code converges again). This affects a few places where the code fix was behaving a little inconsistently in different scenarios that are now more in line with each other.

(I also hoped the code would get a lot shorter - and it is shorter, it's just not huge difference. Instead of the code branching out to give completely different results, there now has to be a partial change on the tree done conditionally. Because of immutability, this had to come with some of its own complexity around tracking nodes and changes, so the result is not as pretty as I hoped. But I'd say it's still an improvement).

These are the changes from previous behavior that I know of:

### Trivia changes

Introduce local on the first "hello":

```c#
Console.WriteLine();

// some useful constants
var a = "hello";
var b = "hello";
```

puts the local directly before the statement, but inside its trivia (after the comment),

```c#
Console.WriteLine();

// some useful constants
const string V = "hello";
var a = V;
var b = "hello";
```
this was very much intentional and there's an existing test that checks this and links to an issue.
#### Current behavior
but if I do introduce for all occurences, this behavior doesn't take affect
and instead the code looks like this:

```c#
Console.WriteLine();
const string V = "hello";

// some useful constants
var a = V;
var b = V;
```

#### New behavior
variable is always inserted after the comment, even with "fix all occurences"

```c#
Console.WriteLine();

// some useful constants
const string V = "hello";
var a = V;
var b = V;
```

### Switch statement changes

introduce local on first "hello"

```c#
switch (true)
{
    case true:
        Console.WriteLine("hello");
        Console.WriteLine("hello");
        break;
}
```

puts the variable inside the switch section:

```c#
switch (true)
{
    case true:
        const string Value = "hello";
        Console.WriteLine(Value);
        Console.WriteLine("hello");
        break;
}
```
#### Current behavior
however doing "fix for all occurences" puts the variable outside:

```c#
const string Value = "hello";
switch (true)
{
    case true:
        Console.WriteLine(Value);
        Console.WriteLine(Value);
        break;
}
```

#### New behavior
it is still inside the switch section:

```c#
switch (true)
{
    case true:
        const string Value = "hello";
        Console.WriteLine(Value);
        Console.WriteLine(Value);
        break;
}
```

please note that if the expression is present in multiple switch cases, the variable is still inserted outside. this work correctly

I didn't add any tests for any of these changes (should I?) because it wasn't my intention to change this. I only came across this inconsistency when looking through the code and making the cleanup. This is sort of just a nice unintended side effect.

**Comment by Neme12** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

**Comment by Neme12** [comment]
@CyrusNajmabadi 

> You are allowed to do this :)

The perfect thing would definitely be to change this and use a common API with other refactorings for converting expression-body to block-body, but I'm not going to do that in this PR. (and I think I changed more than enough already). From looking at the code, there's a lot of things that could be improved here.

But this PR fixes a real issue that people are having right now - using this code fix not only leads to invalid code with #24807 but it is also completely broken with new language features such as expression-bodied constructors, accessors & local functions. This PR fixes that.

**Comment by Neme12** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

**Comment by Neme12** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs [hunk 17]
```diff
@@ -173,74 +172,62 @@ private bool CanUseVar(ITypeSymbol typeSymbol)
...
+                        .WithTriviaFrom(localFunction);
+                default:
+                    throw ExceptionUtilities.UnexpectedValue(node);
             }
-
-            var newRoot = document.Root.ReplaceNode(oldParentingNode, newParentingNode);
-            return document.Document.WithSyntaxRoot(newRoot);
         }
 
         private async Task<Document> IntroduceLocalDeclarationIntoBlockAsync(
```
Comment (Neme12) [inline src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: from this point down these changes are also completely unrelated to the original issue

**Comment by Neme12** [comment]
@dotnet-bot retest windows_debug_unit64_prtest please

**Comment by Neme12** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

**Comment by Neme12** [comment]
this would also fix #13218

**Comment by Neme12** [comment]
retest windows_coreclr_release_prtest please

**Comment by Neme12** [comment]
not the integration tests though :(

**Comment by jcouv** [comment]
test windows_coreclr_debug_prtest please

File: src/Workspaces/CSharp/Portable/Extensions/BaseMethodDeclarationSyntaxExtensions.cs [hunk 18]
```diff
@@ -39,5 +39,22 @@ public static BaseMethodDeclarationSyntax WithBody(this BaseMethodDeclarationSyn
 
             return node;
         }
+
+        public static BaseMethodDeclarationSyntax WithExpressionBody(this BaseMethodDeclarationSyntax node, ArrowExpressionClauseSyntax expressionBody)
```
Comment (jcouv) [inline src/Workspaces/CSharp/Portable/Extensions/BaseMethodDeclarationSyntaxExtensions.cs]: Note: if this PR gets merged after [https://github.com/dotnet/roslyn/pull/25945](https://github.com/dotnet/roslyn/pull/25945), then the new `With` method here should be removed.

Comment (Neme12) [reply src/Workspaces/CSharp/Portable/Extensions/BaseMethodDeclarationSyntaxExtensions.cs]: Yes, I was just thinking that

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs [hunk 19]
```diff
@@ -175,74 +176,65 @@ private bool CanUseVar(ITypeSymbol typeSymbol)
...
             var leadingTrivia = oldBody.GetLeadingTrivia()
                                        .AddRange(oldBody.ArrowToken.TrailingTrivia);
 
-            var newStatement = Rewrite(document, expression, newLocalName, document, oldBody.Expression, allOccurrences, cancellationToken);
-            var newBody = SyntaxFactory.Block(declarationStatement, SyntaxFactory.ReturnStatement(newStatement))
+            var newExpression = Rewrite(document, expression, newLocalName, document, oldBody.Expression, allOccurrences, cancellationToken);
+
+            var convertedStatement = createReturnStatement
+                ? SyntaxFactory.ReturnStatement(newExpression)
+                : SyntaxFactory.ExpressionStatement(newExpression) as StatementSyntax;
```
Comment (jcouv) [inline src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: This should be a cast, since we necessarily have a `StatementSyntax`

Comment (Neme12) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: Yes, but we also know we necessarily have a `StatementSyntax` at compile time. The "cast" only exists to appease the type system. I'll change it, but in reality, neither a cast or 'as' is great - if there was another type of cast that only allowed implicit conversions (as if I just assigned to a variable with this type), that would be the most appropriate.

**Comment by jcouv** [comment]
@DustinCampbell @dotnet/roslyn-ide for review of this community PR. Thanks

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs (hunk 19 above)
Comment (jcouv) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: Yes, both a cast and an `as` appease the compiler. But a cast is unambiguous to the human reader.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: 👍 A cast is how we handle this in the rest of hte IDE codebase.  I would def appreciate if you could stick with that informal convention.

**Comment by jcouv** [comment]
@DustinCampbell @dotnet/roslyn-ide for review of this community PR. Thanks

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs (hunk 19 above)
Comment (Neme12) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: fixed in c1b12c90a788d95048193d2e2eb0047b3a632b75

File: src/Workspaces/CSharp/Portable/Extensions/BaseMethodDeclarationSyntaxExtensions.cs (hunk 18 above)
Comment (Neme12) [reply src/Workspaces/CSharp/Portable/Extensions/BaseMethodDeclarationSyntaxExtensions.cs]: fixed in a0c5999d887ae519b6cb61e71af684f09e3d47ef

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs [hunk 20]
```diff
@@ -252,98 +244,75 @@ private bool CanUseVar(ITypeSymbol typeSymbol)
...
+                document, expression, newLocalName, document, innermostCommonBlock, allOccurrences, cancellationToken);
 
-                var newRoot = document.Root.ReplaceNode(oldStatement, newBlock);
-                return document.Document.WithSyntaxRoot(newRoot);
-            }
+            var statements = InsertWithinTriviaOfNext(GetStatements(newInnerMostBlock), declarationStatement, firstStatementAffectedIndex);
+            var finalInnerMostBlock = WithStatements(newInnerMostBlock, statements);
+
+            var newRoot = root.ReplaceNode(innermostCommonBlock, finalInnerMostBlock);
+            return document.Document.WithSyntaxRoot(newRoot);
```
[the remark this answers is not in the document]
Comment (DustinCampbell) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: I'm also OK if you'd like to punt on this one. :smile:

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs [hunk 21]
```diff
@@ -163,74 +164,65 @@ private bool CanUseVar(ITypeSymbol typeSymbol)
...
-            {
-                var getAccessor = SyntaxFactory.AccessorDeclaration(SyntaxKind.GetAccessorDeclaration, newBody);
-                var accessorList = SyntaxFactory.AccessorList(SyntaxFactory.List(new[] { getAccessor }));
+            // Add an elastic newline so that the formatter will place this new block across multiple lines.
+            newBody = newBody.WithOpenBraceToken(newBody.OpenBraceToken.WithAppendedTrailingTrivia(SyntaxFactory.ElasticCarriageReturnLineFeed))
+                             .WithAdditionalAnnotations(Formatter.Annotation);
 
-                newParentingNode = baseProperty.RemoveNode(oldBody, SyntaxRemoveOptions.KeepNoTrivia);
+            var newRoot = document.Root.ReplaceNode(oldParentingNode, WithBlockBody(oldParentingNode, newBody));
+            return document.Document.WithSyntaxRoot(newRoot);
```
[the remark this answers is not in the document]
Comment (DustinCampbell) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: I'm also OK if you'd like to punt on this one. :smile:

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs [hunk 22]
```diff
@@ -56,9 +56,14 @@ internal partial class CSharpIntroduceVariableService
                         document, block, expression, newLocalName, declarationStatement, allOccurrences, cancellationToken).ConfigureAwait(false);
 
                 case ArrowExpressionClauseSyntax arrowExpression:
+                    // this will be null for expression-bodied properties & indexer (not for individual getters & setters, those do have a symbol),
+                    // both of which are a shorthand for the getter and always return a value
+                    var method = document.SemanticModel.GetDeclaredSymbol(arrowExpression.Parent) as IMethodSymbol;
+                    bool createReturnStatement = !method?.ReturnsVoid ?? true;
```
[the remark this answers is not in the document]
Comment (DustinCampbell) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: FYI: Not necessary to merge.

**Comment by DustinCampbell** [comment]
@Neme12: Looking back at my comments, I'm OK to go ahead and merge this without the tiny nits I suggested. This is a very welcome change. Thank you!

File: src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs [hunk 23]
```diff
@@ -163,74 +164,65 @@ private bool CanUseVar(ITypeSymbol typeSymbol)
...
-                {
-                    var indexerDeclaration = ((IndexerDeclarationSyntax)newParentingNode);
-                    newParentingNode = indexerDeclaration
-                        .WithAccessorList(accessorList)
-                        .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.None))
-                        .WithTrailingTrivia(indexerDeclaration.SemicolonToken.TrailingTrivia);
-                }
-            }
-            else if (oldParentingNode is BaseMethodDeclarationSyntax baseMethod)
+        private static SyntaxNode WithBlockBody(SyntaxNode node, BlockSyntax body)
```
[the remark this answers is not in the document]
Comment (Neme12) [reply src/Features/CSharp/Portable/IntroduceVariable/CSharpIntroduceVariableService_IntroduceLocal.cs]: I agree. Filed #26456
