### PR TITLE
FAWMN add support for [method: MyGenerator] to target primary constructors

### LINKED ISSUE #79575: ForAttributeWithMetadataName doesn't work with [method: MyGenerator] applied to primary or record constructor
**Version Used**: 

.NET 10.0.100-preview.6.25358.103
Microsoft.CodeAnalysis.Analyzers 4.14.0 (and 5.0.0-1.25277.114)
Microsoft.CodeAnalysis.CSharp 4.14.0

**Steps to Reproduce**:

1. Create a source generator that defines an attribute `MyGeneratorAttribute` with usage target `Constructor`, and calls `ForAttributeWithMetadataName`
2. Apply the attribute to the constructor of a record type using `[method: MyGenerator]`
3. Observe that the generator's transform is not called

A minimal repro, with source-code provided:

MyGenerator.cs
```csharp
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace MyAnalyzers;

[Generator]
public class MyGenerator : IIncrementalGenerator
{
    private const string _AttributeNamespace = "MyNamespace";
    private const string _AttributeName = "MyGeneratorAttribute";
    private const string _AttributeQualName = $"{_AttributeNamespace}.{_AttributeName}";

    private const string _AttributeDefinition = @$"
        namespace {_AttributeNamespace};

        [Microsoft.CodeAnalysis.Embedded]
        [System.AttributeUsage(System.AttributeTargets.Constructor)]
        internal sealed class {_AttributeName} : System.Attribute;
    ";

    public void Initialize(IncrementalGeneratorInitializationContext Init)
    {
        Init.RegisterPostInitializationOutput(static post =>
        {
            post.AddEmbeddedAttributeDefinition();
            post.AddSource($"{_AttributeName}.g.cs", SourceText.From(_AttributeDefinition, System.Text.Encoding.UTF8));
        });

        var pipeline = Init.SyntaxProvider.ForAttributeWithMetadataName(
            _AttributeQualName,
            static (syntaxNode, _) => true,
            static (context, _) =>
            {
                // Issue an error diagnostic so we can see whether the transform ran or not.
                // We could also observe the bug by simply throwing an exception here:
                // the generator will throw if we add the attribute to MyClass, but not if we add it to MyRecord.

                var loc = context.TargetNode.GetLocation();
                var diagLoc = Location.Create(loc.GetMappedLineSpan().Path, loc.SourceSpan, loc.GetLineSpan().Span);

                var typeSym = context.TargetSymbol.ContainingType ?? context.TargetSymbol;
                var msg = $"{context.TargetNode.GetType().Name} {typeSym}";

                return Diagnostic.Create
                (
                    id: "MYGENERATOR01",
                    category: "MyCategory",
                    message: msg,
                    severity: DiagnosticSeverity.Error,
                    defaultSeverity: DiagnosticSeverity.Error,
                    isEnabledByDefault: true,
                    warningLevel: 0,
                    location: diagLoc
                );
            }
        );

        Init.RegisterSourceOutput(pipeline, static (context, model) => context.ReportDiagnostic(model));
    }
}
```

MyGeneratorTest.cs
```csharp
namespace MyNamespace;

[method: MyGenerator]
public record MyRecord();

[method: MyGenerator]
public class MyClass1();

public class MyClass2
{
    [MyGenerator]
    public MyClass2()
    {
    }
}
```

**Expected Behavior**:

Error diagnostic on MyRecord, MyClass1, and MyClass2

**Actual Behavior**:

Error diagnostic only on MyClass2

### PR DESCRIPTION
**Pull request by jharjung**
Add support to ForAttributeWithMetadataName for [method: MyGenerator] to target primary and record constructors.

```csharp
[method: MyGenerator]
public record MyRecord();

[method: MyGenerator]
public class MyClass1();
```

Resolves #79575

### CODE REVIEW

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs [hunk 1]
```diff
@@ -137,14 +137,26 @@ public IncrementalValuesProvider<T> ForAttributeWithMetadataName<T>(
...
+            string fullyQualifiedMetadataName,
+            ISyntaxHelper syntaxHelper)
         {
             var targetSyntaxTree = attributeTarget.SyntaxTree;
             var result = ArrayBuilder<AttributeData>.GetInstance();
 
             addMatchingAttributes(symbol.GetAttributes());
             addMatchingAttributes((symbol as IMethodSymbol)?.GetReturnTypeAttributes());
 
+            if (symbol is INamedTypeSymbol namedTypeSymbol && syntaxHelper.IsTypeDeclaration(attributeTarget))
```
Comment (333fred) [inline src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs]: This feels overly complicated and like it shouldn't need any new syntax helpers. We should just be able to go through the constructors, see if any have the same syntax as the attribute target, and include only that constructor's attributes.

File: src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs:1]: Please add some tests for partial type declarations.

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs (hunk 1 above)
Comment (jharjung) [reply src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs]: Extending SyntaxHelper was a suggestion by @CyrusNajmabadi 

We need to abstract over C# vs VB, because we're in Compilers.Core.Portable, so we don't have access to Microsoft.CodeAnalysis.CSharp/VisualBasic.

If we attempt to inspect language-specific syntax in `getMatchingAttributes` like:

```csharp
if (attributeTarget is Microsoft.CodeAnalysis.CSharp.Syntax.TypeDeclarationSyntax)
{
}
```

We get the error: The type or namespace name 'CSharp' does not exist in the namespace 'Microsoft.CodeAnalysis' (are you missing an assembly reference?)

File: src/Compilers/CSharp/Portable/SourceGeneration/CSharpSyntaxHelper.cs [hunk 2]
```diff
@@ -25,12 +25,25 @@ public override bool IsValidIdentifier(string name)
...
+
         public override bool IsAttribute(SyntaxNode node)
             => node is AttributeSyntax;
 
         public override SyntaxNode GetNameOfAttribute(SyntaxNode node)
             => ((AttributeSyntax)node).Name;
 
+        public override bool DoesAttributeHaveMethodTarget(SyntaxNode node)
+        {
+            var list = ((AttributeSyntax)node).FirstAncestorOrSelf<AttributeListSyntax>();
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/SourceGeneration/CSharpSyntaxHelper.cs]: don't need to do FirstAncestorOrSelft.  Can just hit .Parent

Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Portable/SourceGeneration/CSharpSyntaxHelper.cs]:
```suggestion
return node is AttributeSyntax { Parent: AttributeListSyntax { Target.Identifer.RawKind: (int)SyntaxKind.MethodKeyword } };
```

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs (hunk 1 above)
Comment (333fred) [reply src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs]: I don't think we need to check the type of the node. I think we just need to compare equality.

Comment (jharjung) [reply src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs]: How about this?

```csharp
if (symbol is INamedTypeSymbol namedTypeSymbol)
{
    var attrs = namedTypeSymbol
        .InstanceConstructors
        .SelectMany(c => c.GetAttributes())
        .Where(a => a.ApplicationSyntaxReference?.GetSyntax().Parent?.Parent == attributeTarget)
        .ToImmutableArray();

    addMatchingAttributes(attrs);
}
```

Comment (CyrusNajmabadi) [reply src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs]: i think fred is saying you should check the syntax of the instanceconstructor against the syntax of the inamedtype.  if they're the same, and the constructor has attributes on it, then this is necessairly a case where you have the primary constructor and `[method: ...]` attributes.

Comment (jharjung) [reply src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs]: Ahh. I didn't think the constructor would have any syntax, since it's part of the class/record declaration rather than an independent syntactic element. But it does of course.

```csharp
if (symbol is INamedTypeSymbol namedTypeSymbol)
{
    var attrs = namedTypeSymbol
        .InstanceConstructors
        .Where(c => c.DeclaringSyntaxReferences.Any(r => r.GetSyntax() == attributeTarget))
        .SelectMany(c => c.GetAttributes())
        .ToImmutableArray();

    addMatchingAttributes(attrs);
}
```

File: src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs
Comment (jharjung) [reply src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs:1]: I added a variant of each of the constructor tests where the class/record is partial.

Please let me know if you'd like any other tests.

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs (hunk 1 above)
Comment (jharjung) [reply src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs]: Committed and pushed but let me know if it needs further revision

File: src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs [hunk 3]
```diff
@@ -569,6 +569,274 @@ internal partial void M() { }
...
+    }
+
+    [Fact]
+    public void FindConstructorAttribute4()
+    {
+        var source = """
+            using System;
+
+            [method: CLSCompliant(true)]
+            partial class C()
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs:788]: We need tests with multiple partial parts, preferably also with different attributes spread across the parts. Even if there are errors, we should assert the behavior.

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs (hunk 1 above)
Comment (333fred) [reply src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs]: Yep, this looks like what I was thinking. Thanks!

File: src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs (hunk 3 above)
Comment (jharjung) [reply src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs:788]: This feature is specifically adding support for `[method: MyGenerator]` on a primary constructor, and primary constructors can't be partial, so I'm not sure what else we're trying to test.

Could you give more detail? A concrete example of the source you'd like to see tests for would also be helpful.

Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs:788]: We're looking at syntax. We need to make sure that types with multiple parts are handled correctly, in both valid and error scenarios.

Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs:788]: Some examples:

```cs
partial class C() {}

[method: CLSCompliant(true)] // Warning about ignored attribute application
partial class C {}
```

```cs
[method: CLSCompliant(true)] // Should be found
partial class C() {}

partial class C {}
```

Comment (jharjung) [reply src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs:788]: Thanks. Do you have an example of different attributes spread across the parts?

Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs:788]: For example:

```cs
[method: CLSCompliant(true)]
partial class C() {}

[method: SomeOtherAttribute]
partial class C {}
```
or
```cs
[method: CLSCompliant(true)]
partial class C() {}

[method: SomeOtherAttribute]
partial class C() {}
```

Comment (jharjung) [reply src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs:788]:
```csharp
[method: CLSCompliant(true)]
partial class C() {}

[method: SomeOtherAttribute]
partial class C() {}
```

This won't compile (CS8863 Only a single partial type declaration may have a parameter list). So we can't test any behavior around FAWMN there.

Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs:788]: > This won't compile (CS8863 Only a single partial type declaration may have a parameter list). So we can't test any behavior around FAWMN there.

Yes we can. 99% of the code source generators see is bad. We should be testing what FAWMN will do in these cases.

Comment (jharjung) [reply src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs:788]: Doh, of course you're right. For some reason I was thinking `CreateCompilation` would fail, which is obviously wrong, it just produces a compilation with errors.

Updated tests are pushed.

**Review by 333fred — APPROVED** [review]

File: src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs
Comment (jjonescz) [inline src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs:1]: > See: #79575

Is this PR resolving the issue or just related to it? If it's the former, consider using "Resolves #79575" syntax instead so merging the PR closes the issue automatically.

File: src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs [hunk 4]
```diff
@@ -569,6 +569,503 @@ internal partial void M() { }
             step => Assert.True(step.Outputs.Single().Value is MethodDeclarationSyntax { Identifier.ValueText: "M", Body: not null }));
     }
 
+    [Fact]
```
Comment (jjonescz) [inline src/Compilers/CSharp/Test/Semantic/SourceGeneration/GeneratorDriverTests_Attributes_FullyQualifiedName.cs:572]: Consider adding `WorkItem("https://github.com/dotnet/roslyn/issues/79575")` attribute to relevant tests.

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs [hunk 5]
```diff
@@ -145,6 +145,17 @@ static ImmutableArray<AttributeData> getMatchingAttributes(
             addMatchingAttributes(symbol.GetAttributes());
             addMatchingAttributes((symbol as IMethodSymbol)?.GetReturnTypeAttributes());
 
+            if (symbol is INamedTypeSymbol namedTypeSymbol)
+            {
+                var attrs = namedTypeSymbol
+                    .InstanceConstructors
+                    .Where(c => c.DeclaringSyntaxReferences.Any(r => r.GetSyntax() == attributeTarget))
```
Comment (jjonescz) [inline src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs]: Should we be propagating `cancellationToken` to the `GetSyntax` call here?

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs [hunk 6]
```diff
@@ -145,6 +145,17 @@ static ImmutableArray<AttributeData> getMatchingAttributes(
...
+                    .SelectMany(c => c.GetAttributes())
+                    .ToImmutableArray();
```
Comment (jjonescz) [inline src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs]: Consider using explicit loops and pooled immutable array builder instead of LINQ.

I guess we could avoid the intermediate immutable array construction altogether - just add the attributes to `result`.

**Review by jjonescz — APPROVED** [review]

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs (hunk 6 above)
Comment (CyrusNajmabadi) [reply src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs]: agreed.  i would prefer normal imperative code here.  

also, can we only do this check if we see the attribute being looked at is of the form `[method:`? instead of always having to bind an dproduce the instance constructors?

Comment (jharjung) [reply src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs]: I've updated the implementation to use explicit loops and avoid the intermediate array.

Comment (jharjung) [reply src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs]: @CyrusNajmabadi 

>  can we only do this check if we see the attribute being looked at is of the form `[method:`?

I think we already explored that and decided this was best?
- https://github.com/dotnet/roslyn/issues/79575#issuecomment-3113860708
- https://github.com/dotnet/roslyn/pull/79609#discussion_r2231646759

But let me know if you've had any new ideas around that.

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs [hunk 7]
```diff
@@ -137,14 +137,30 @@ public IncrementalValuesProvider<T> ForAttributeWithMetadataName<T>(
...
+            if (symbol is INamedTypeSymbol namedTypeSymbol)
+            {
+                foreach (var constructorSymbol in namedTypeSymbol.InstanceConstructors)
+                {
+                    foreach (var syntaxRef in constructorSymbol.DeclaringSyntaxReferences)
+                    {
+                        if (syntaxRef.GetSyntax(cancellationToken) == attributeTarget)
+                        {
+                            addMatchingAttributes(constructorSymbol.GetAttributes());
+                            break;
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs]: since we lack `break label;` this really should be a goto that jumps out of the second foreach, since we can stop searching the moment we hit the single instance constructor that corresponds to the primary constructor.

Comment (CyrusNajmabadi) [reply src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs]: this can also be accomplished with a local function for the inner loop.

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs (hunk 7 above)
Comment (jharjung) [reply src/Compilers/Core/Portable/SourceGeneration/Nodes/SyntaxValueProvider_ForAttributeWithMetadataName.cs]: Updated to factor out a local function for the whole outer loop so it can just return to break out when it finds the primary constructor.

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Review by jjonescz — APPROVED** [review]

**Review by 333fred — APPROVED** [review]

**Comment by 333fred** [comment]
Thanks @jharjung! Sorry for the delay on review and merge.
