### PR TITLE
Report error if 'record struct' constructor calls default parameterless constructor

### LINKED ISSUE #58328: System.InvalidProgramException when constructing a record struct with parameter list and calling the default constructor
**Version Used**: 
.NET SDK:
 Version: 6.0.100
 Commit: 9e8b04bbff

**Steps to Reproduce**:

1. Create a record struct with a parameter list with at least two parameters:
```csharp
public record struct S(char First, char Second)
{
}
```
2. Add a constructor that takes a parameter of some type (the exact type seems to not matter):
```csharp
public record struct S(char First, char Second)
{
    public S(object o)
    {
    }
}
```
3. This produces CS8862: A constructor declared in a record with parameter list must have 'this' constructor initializer, which is expected. To fix this error, add a call to the _default_ constructor:
```csharp
public record struct S(char First, char Second)
{
    public S(object o) : this()
    {
    }
}
```
4. Attempt to create an instance of the struct:
```csharp
var s = new S(new object());

Console.WriteLine(s);
```

**Expected Behavior**:
The struct is created and printed with `First` and `Second` set to `default(char)`.

**Actual Behavior**:
A `System.InvalidProgramException` is thrown during execution:

```
Unhandled exception. System.InvalidProgramException: Common Language Runtime detected an invalid program. 
    at S..ctor(Object o)                                                                                                    
    at Program.<Main>$(String[] args) in D:\<path_ommited>\Program.cs:line 1
```

**Full code**:

Occurs both when running compiled to Debug and Release.

```csharp
var s = new S(new object());

System.Console.WriteLine(s);

public record struct S(char First, char Second)
{
    public S(object o) : this()
    {
    }
}
```

https://dotnetfiddle.net/85o0Th

### PR DESCRIPTION
**Pull request by cston**
Confirmed with C# LDT: 
In a `record struct` with a primary constructor, explicit constructors require a `this()` initializer that invokes the primary constructor or _another explicitly declared constructor_.

Fixes #58328

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs [hunk 1]
```diff
@@ -10616,5 +10616,349 @@ record struct Value(int I)
...
+
+-1
+2
+-2
+");
+        }
+
+        [Fact]
+        [WorkItem(58328, "https://github.com/dotnet/roslyn/issues/58328")]
+        public void ExplicitConstructors_05()
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs:10770]: >ExplicitConstructors_05 [](http://example.com/codeflow?start=20&length=23)

The `this()` constructor initializer calls in this test and the following resulted in invalid code previously.

File: src/Compilers/CSharp/Portable/Errors/ErrorCode.cs [hunk 2]
```diff
@@ -1993,7 +1993,7 @@ internal enum ErrorCode
         WRN_CallerArgumentExpressionParamForUnconsumedLocation = 8966,
         ERR_NewlinesAreNotAllowedInsideANonVerbatimInterpolatedString = 8967,
         ERR_AttrTypeArgCannotBeTypeVar = 8968,
-        // WRN_AttrDependentTypeNotAllowed = 8969, // Backed out of of warning wave 6, may be reintroduced later
+        ERR_RecordStructConstructorCallsDefaultConstructor = 8969, // Added in 17.1 for an invalid C#10 scenario.
```
Comment (Youssef1313) [inline src/Compilers/CSharp/Portable/Errors/ErrorCode.cs:1996]: Is reusing the warning number okay here?

Comment (cston) [reply src/Compilers/CSharp/Portable/Errors/ErrorCode.cs:1996]: Maybe, but reusing seems unnecessary. Updated.

**Review by 333fred — APPROVED** [review]
LGTM (commit 1)

**Review by chsienki — APPROVED** [review]

**Review by 333fred — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 3]
```diff
@@ -3524,6 +3530,9 @@ private BoundNode BindConstructorBody(ConstructorDeclarationSyntax constructor,
                                                       null :
                                                       bodyBinder.BindExpressionBodyAsBlock(constructor.ExpressionBody,
                                                                                            constructor.Body == null ? diagnostics : BindingDiagnosticBag.Discarded));
+
+            bool hasAnyRecordConstructors() =>
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:3534]: >hasAnyRecordConstructors [](http://example.com/codeflow?start=17&length=24)

I think the name is confusing. The body is checking for a primary constructor, not just any constructor.

File: src/Compilers/CSharp/Portable/CSharpResources.resx [hunk 4]
```diff
@@ -6911,6 +6911,9 @@ To remove the warning, you can use /reference instead (set the Embed Interop Typ
   <data name="ERR_LambdaWithAttributesToExpressionTree" xml:space="preserve">
     <value>A lambda expression with attributes cannot be converted to an expression tree</value>
   </data>
+  <data name="ERR_RecordStructConstructorCallsDefaultConstructor" xml:space="preserve">
+    <value>A 'this' initializer for a 'record struct' constructor must call the primary constructor or an explicitly declared constructor.</value>
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CSharpResources.resx:6915]: >A 'this' initializer for a 'record struct' constructor must call the primary constructor or an explicitly declared constructor. [](http://example.com/codeflow?start=11&length=127)

The wording looks too general. The requirement is only for records with primary constructors, I think the message should reflect that. See, for example, how we do that for ```UnexpectedOrMissingConstructorInitializerInRecord```:

```
  <data name="ERR_UnexpectedOrMissingConstructorInitializerInRecord" xml:space="preserve">
    <value>A constructor declared in a record with parameter list must have 'this' constructor initializer.</value>
  </data>
```

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 5]
```diff
@@ -3514,6 +3514,12 @@ private BoundNode BindConstructorBody(ConstructorDeclarationSyntax constructor,
                 && thisInitializer
                 && ContainingType.IsDefaultValueTypeConstructor(initializer);
 
+            if (skipInitializer &&
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:3517]: >skipInitializer [](http://example.com/codeflow?start=16&length=15)

Should we also check if ```!constructorSymbol.IsStatic```?

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs [hunk 6]
```diff
@@ -10616,5 +10616,349 @@ record struct Value(int I)
...
+        {
+            var source =
+@"record struct S3(char A)
+{
+    public S3(object o) : this() { }
+}
+record struct S4(char A, char B)
+{
+    public S4(object o) : this() { }
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs:10779]: >public S4(object o) : this() { } [](http://example.com/codeflow?start=4&length=32)

Consider also testing with static constructors. For example:
```
record struct S(int x)
{
    static S() : this()
    {}
}
```

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs (hunk 5 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:3517]: >skipInitializer [](http://example.com/codeflow?start=16&length=15)

The fact that ```skipInitializer``` depends on ```includesFieldInitializers``` looks suspicious. I think it is technically possible to have a primary constructor and no initializers. It would be good trying to construct a scenario like that. Consider instead using condition ```thisInitializer && ContainingType.IsDefaultValueTypeConstructor(initializer)```, I think that would exactly reflect the condition that design requires us to check.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 2)

**Comment by cston** [comment]
Responded to additional feedback in https://github.com/dotnet/roslyn/pull/58430.
