### PR TITLE
Maintain a separate decision tree for subsumption and code gen

### LINKED ISSUE #13520: Fail to detect pattern subsumption when there is an intervening case of a supertype
The following test fails. It succeeds when the `case object o...` line is commented out.

```cs
        [Fact]
        public void Bug13520()
        {
            var source =
@"class Program
{
    public static void Main(string[] args)
    {
        object value = false;
        switch (value)
        {
            case true: break;
            case object o when args.Length == -1: break;
            case false: break;
            case bool b: throw null; // error: bool already handled by previous cases.
        }
    }
    public static bool IsB(char value)
    {
        return value == 'b';
    }
}
";
            var compilation = CreateCompilationWithMscorlib45(source, options: TestOptions.DebugExe);
            compilation.VerifyDiagnostics(
                // (11,18): error CS8120: The switch case has already been handled by a previous case.
                //             case bool b: ; // error: bool already handled by previous cases.
                Diagnostic(ErrorCode.ERR_PatternIsSubsumed, "bool b").WithLocation(11, 18)
                );
        }
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #13520 

@dotnet/roslyn-compiler Please review.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs [hunk 1]
```diff
@@ -197,6 +198,11 @@ internal DecisionTree ComputeDecisionTree()
                         else
                         {
                             AddToDecisionTree(result, label);
+                            if (label.Guard == null || label.Guard.ConstantValue == ConstantValue.True)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs]: >label.Guard.ConstantValue == ConstantValue.True [](start = 55, length = 47)

Do we have a test that demonstrates that this condition makes a difference?

**Comment by AlekseyTs** [comment]
LGTM, modulo the test coverage question.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs]: Yes. See, for example, `EqualConstant02`

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a second review of this?

**Comment by gafter** [comment]
@agocke Please review.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs [hunk 2]
```diff
@@ -162,6 +162,7 @@ internal DecisionTree ComputeDecisionTree()
             }
 
             var result = DecisionTree.Create(_switchStatement.Expression, _switchStatement.Expression.Type, _enclosingSymbol);
+            var subsumptionTree = DecisionTree.Create(_switchStatement.Expression, _switchStatement.Expression.Type, _enclosingSymbol);
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs]: How is this different from the `result` tree above?

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs [hunk 3]
```diff
@@ -197,6 +198,11 @@ internal DecisionTree ComputeDecisionTree()
                         else
                         {
                             AddToDecisionTree(result, label);
+                            if (label.Guard == null || label.Guard.ConstantValue == ConstantValue.True)
+                            {
+                                // Only unconditional switch labels contribute to subsumption
+                                AddToDecisionTree(subsumptionTree, label);
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs]: I'm a bit confused -- does `CheckSubsumed` itself modify the tree? Otherwise, haven't we just added the same tree as on line 200?

Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs]: No, we are maintaining separate decision trees for sybsumption checking (`subsumption`) and for code generation (`result`). Like it says on the tin.

---
In reply to: [79474816](https://github.com/dotnet/roslyn/pull/13770#discussion_r79474816) [](ancestors = 79474816)

Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs]: CheckSubsumped just looks in the subsumption tree to see if the proposed new pattern is already handled. It doesn't modify the tree.

---
In reply to: [79641466](https://github.com/dotnet/roslyn/pull/13770#discussion_r79641466) [](ancestors = 79641466,79474816)

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs]: We are maintaining separate decision trees for sybsumption checking (`subsumption`) and for code generation (`result`).

---
In reply to: [79474487](https://github.com/dotnet/roslyn/pull/13770#discussion_r79474487) [](ancestors = 79474487)

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs (hunk 3 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs]: No, `CheckSubsumed` only checks whether the a pattern is subsumed by a decision tree. It doesn't modify the tree.

**Comment by gafter** [comment]
@dotnet-bot Please test windows_release_unit32_prtest windows_release_unit64_prtest

**Comment by jaredpar** [comment]
:+1:
