### PR TITLE
Generate direct GetHashCode calls for value types when they would be non-boxing

### LINKED ISSUE #31984: 'Generate GetHashCode' unnecessarily uses EqualityComparer for Nullable<>
Visual Studio 2019 Preview 1.1

There should be more consistency between `int` and `int?`. Actual:

```cs
private int a;
private int? b;

public override int GetHashCode()
{
    var hashCode = 2118541809;
    hashCode = hashCode * -1521134295 + a.GetHashCode();
    hashCode = hashCode * -1521134295 + EqualityComparer<int?>.Default.GetHashCode(b);
    return hashCode;
}
```

Expected:

```cs
var hashCode = 2118541809;
hashCode = hashCode * -1521134295 + a.GetHashCode();
hashCode = hashCode * -1521134295 + b.GetHashCode();
return hashCode;
```

`Nullable<>.GetHashCode` does not throw NullReferenceException because the struct overrides `Object.GetHashCode` and the overriding implementation has no null reference to operate on.

### PR DESCRIPTION
**Pull request by jnm2**
Closes #31984.

⚠ I updated the PR to reflect my discovery at https://github.com/dotnet/roslyn/issues/31984#issuecomment-535310922.

### CODE REVIEW

File: src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions_CreateGetHashCodeMethod.cs [hunk 1]
```diff
@@ -179,11 +179,19 @@ public static IMethodSymbol GetBaseGetHashCodeMethod(INamedTypeSymbol containing
                 return thisSymbol;
             }
 
-            var memberType = member.GetSymbolType();
-            var primitiveValue = IsPrimitiveValueType(memberType) && memberType.SpecialType != SpecialType.System_String;
-            var isTupleType = memberType?.IsTupleType == true;
-            if (primitiveValue || isTupleType)
+            if (member.GetSymbolType().IsValueType)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions_CreateGetHashCodeMethod.cs]: above code seems to imply that GetSymbolType could return null.  can you be resilient to that?

File: src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions_CreateGetHashCodeMethod.cs [hunk 2]
```diff
@@ -179,11 +179,19 @@ public static IMethodSymbol GetBaseGetHashCodeMethod(INamedTypeSymbol containing
...
             {
+                /* No reason to use the bulkier EqualityComparer<>.Default.GetHashCode. No null check is necessary, and
+                calling GetHashCode directly will not cause boxing. (The decision to box is at jit time. If boxing
+                happens, there will have been no way to avoid it anyway.)
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions_CreateGetHashCodeMethod.cs]: I'm not entirely sure I'm following this comment. I'd assume the JIT won't actually be doing a box and would elide the null check since it'll be doing a custom JIT for value types anyways (there's no System.__Canon version it can use). Are we sure this is actually faster? This feels like something we'd tell the runtime to do instead...?

Comment (jnm2) [reply src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions_CreateGetHashCodeMethod.cs]: You're right. I don't know the right term to use instead of 'boxing.'

> Are we sure this is actually faster? This feels like something we'd tell the runtime to do instead...?

Not faster, but equivalent and nicer-looking.

.NET Core x64: [sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGFAbgFgAoJ4gJnIGEmBvJ8/8gAcoASwBu2DDHKxsAEwgA7ADYBPcgHURGABYB5MTCii50gO7b9h4yNMNGAoaIlSZMeUrWbLEAK4YDIxNzH39Amzs+ASj+YgBmchFFDHIAcRgMAAk8HQ4IUy1dcOCACgBKGPJeB0cBYgB2cgsi62CAOnSsnLzTcvtHAF9KyvjE5PIAUQBHX2xlbVU8/EFsWChCqyDbGHLK6tq6xunZ+YxFiGXVowAeDeLtgD42gBEYADNsX2UMDozs3Fy+R2zU2ERgZX6AiGNX4IwSSRSnX+gIKoQCrW2uxhVUqjgaTTR91Mvy6AJ6OwhlWhjjhYxSxzmCyWKzWGz86K2vQq2P2B0oRxmjLOzKuUFuhIxpierw+Xx+SO6QJKIPZRPBkP40OhTFwGCgvjAKTukpgPFpCPIAAUoBBBEYzlVyABzDK0cja7GjCAmulpP6KrnkAC8DytNrtUDO9g9uv1hu8ulVJrNnvh42ttvt6m4ztd7qY0KAA===)

.NET Framework x64: [sharplab](https://sharplab.io/#v2:EYLgHgbALANALiAhgZwLYB8ACAGABJgRigG4BYAKAswCZcBhCgbwt1dwAcAnASwDdE4AU1ydBiACYB7AHYAbAJ64A6tzgALAPK9BnHuOEB3VZu27u+suTYce/ISLFS5ileskBXOFp17Dxj16mvpbWLGyYAMy43NJwuADignAAEihqdJL6riY+5oIAFACUYazMVtbhAOy4RureZvoAdIkpaRn6RSFsAL4luH2R0bG4AKIAju6IsqryGajsiKKc2fW+RX1lFVWjE1MzcwtLADwrQXkAfI0AIoIAZojusnDNSanI6ZkFtTkNgoVdrF65VYAyiMTiLTeHyy/k8qzy62BuE2W3w1W+AXhTUhbU+nT6QNCSMG4J2k2mcFmknmix02UxZw6xSRKK2mGq43J+2phx0J1hgVy+kuN3uj2eOPe7S+AqxfwBuCBQIoyDgnHcAGM4qchYImKChnEAAqcSTsHSU5G4ADmSWIiooBskjOEpMl0IKhVwAF5zrgTWaLfJLMryKr1VrlLKXfriWDhgHzZxLYwbXaHeQgUA===) (EqualityComparer.Default actually gens much worse code than calling GetHashCode directly)

Comment (jnm2) [reply src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions_CreateGetHashCodeMethod.cs]: System.HashCode is used to implement GetHashCode on .NET Core, so if this code is running, we're on .NET Framework or .NET Standard etc. The poorer performance on .NET Framework seems like it would be another reason to avoid using EqualityComparer<>.Default on value types.

**Comment by jnm2** [comment]
@CyrusNajmabadi @jasonmalinowski Updated.

**Comment by jasonmalinowski** [comment]
@jnm2 Thanks; I've signed off and @CyrusNajmabadi might take a look tonight or tomorrow. Otherwise I'll merge in the next day or two.

**Comment by jasonmalinowski** [comment]
(and thanks for all the tests!)

**Comment by CyrusNajmabadi** [comment]
LGTM.  Thanks!

**Comment by jasonmalinowski** [comment]
That was quick, thanks @CyrusNajmabadi.
