### PR TITLE
Ensure '/warnaserror-:DiagnosticId' does not nullify globalconfig severity setting

### LINKED ISSUE #70570: '/warnaserror-:DiagnosticId' should not nullify diagnostic severity settings for 'DiagnosticId' in globalconfig
This is quite identical to #49446, which addressed same issue with severity setting in editorconfig file, it seems we still have the issue if the setting is specified in a globalconfig.

**Steps to Reproduce**:

1. Create a C# class library project with `net5` target framework with below code:
```csharp
class C
{
    void M() { }
}
```
2. Verify IDE suggestion/message [CA1822: Mark members as static](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1822) is reported for method 'M'
3. Add a globalconfig file to the project root with following contents:
```editorconfig
is_global = true

dotnet_diagnostic.CA1822.severity = warning
```
4. Build and verify `CA1822` warning
5. Edit the csproj file to add `/warnaserror-:CA1822`:
```xml
<PropertyGroup>
  <WarningsNotAsErrors>CA1822</WarningsNotAsErrors>
</PropertyGroup>
```
6. Rebuild project

**Expected Behavior**:
`CA1822` is reported as a warning

**Actual Behavior**:
`CA1822` is not reported as a warning. `/warnaserror-:CA1822` seems to cause compiler fallback `CA1822` to its default severity `Info`/`Suggestion` and ignores globalconfig entry that promotes it to a warning.

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #70570

[First commit](f99e8234f90ee17069c795f4bdc31d71e6c010e4) adds unit tests that fail for the scenario corresponding to #70570.

[Second commit](382431c2f3139f83bad26226049811016c0f426f) adds the fix that fixes the added unit tests. I also verified that manually that the end-to-end scenario mentioned in #70570 is fixed with the new compiler.

### CODE REVIEW

**Comment by mavasani** [comment]
Tagging @AlekseyTs and @333fred for reviews as they help review a similar issue in #49449 for editorconfig.
- The fix in #49449 handles both editorconfig and globalconfig with respect to `/warnaserror-:RuleID` in _post-filtering_ logic for reported diagnostics.
- This PR is the fix for globalconfig with respect to `/warnaserror-:RuleID` in _pre-filtering_ logic when we try to determine if an analyzer is suppressed for the entire compilation and hence can be avoided to execute completely to improve performance.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.cs [hunk 1]
```diff
@@ -379,9 +379,8 @@ bool isEnabledWithAnalyzerConfigOptions(DiagnosticDescriptor descriptor)
                 // Compilation wide user settings (diagnosticOptions) from ruleset/nowarn/warnaserror overrides the analyzer author and global editorconfig settings.
                 // Note that "/warnaserror-:DiagnosticId" adds a diagnostic option with value 'ReportDiagnostic.Default',
                 // which should not alter 'isSuppressed'.
-                if ((diagnosticOptions.TryGetValue(diag.Id, out var severity) ||
-                    options.SyntaxTreeOptionsProvider is object && options.SyntaxTreeOptionsProvider.TryGetGlobalDiagnosticValue(diag.Id, cancellationToken, out severity)) &&
-                    severity != ReportDiagnostic.Default)
+                if (diagnosticOptions.TryGetValue(diag.Id, out var severity) && severity != ReportDiagnostic.Default ||
```
Comment (mavasani) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.cs:382]: Note the comment above was already correct, but because the `severity != ReportDiagnostic.Default` check was outside the `||` it ended up preventing `TryGetGlobalDiagnosticValue` when `/warnaserror-:DiagnosticId` was specified for diagnosticOptions.

Comment (333fred) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.cs:382]: I'd prefer if we added parenthesis for clarity here. I don't want to remember whether && or || binds tighter in order to read this code.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 2)

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.cs (hunk 1 above)
Comment (mavasani) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.cs:382]:
```suggestion
                if ((diagnosticOptions.TryGetValue(diag.Id, out var severity) && severity != ReportDiagnostic.Default) ||
```

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.cs [hunk 2]
```diff
@@ -379,9 +379,8 @@ bool isEnabledWithAnalyzerConfigOptions(DiagnosticDescriptor descriptor)
...
+                    options.SyntaxTreeOptionsProvider is object && options.SyntaxTreeOptionsProvider.TryGetGlobalDiagnosticValue(diag.Id, cancellationToken, out severity))
```
Comment (mavasani) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.cs:383]:
```suggestion
                    (options.SyntaxTreeOptionsProvider is object && options.SyntaxTreeOptionsProvider.TryGetGlobalDiagnosticValue(diag.Id, cancellationToken, out severity)))
```

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.cs (hunk 1 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.cs]: Thanks, added

**Comment by mavasani** [comment]
@333fred Can you please take another look? thanks.

**Review by 333fred — APPROVED** [review]
