### PR TITLE
Fix couple of issues related to SerializableOptionSet which were leading to checkum validation asserts

### LINKED ISSUE #44791: Incremental solution update in OOP applies options incorrectly in solution with F# and C# project
Repro as in https://github.com/dotnet/roslyn/issues/24408. Attach to Roslyn ServiceHub process to observe the exception.

```
Differences detected in solution checksum: assets only in the incremental solution but not in the request
ifKIrMmYfMBBmH8xzKUHktFcGZ0=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
26ODxwbeXJweaiZJsDvomrJ6yks=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in new solution but not in incremental solution
9jgbGouy4/3vFpPCih/QoY2rN7w=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
6ZY6HgF9PjRLPfKsnGWTuTvOHeM=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in incremental solution but not in new solution
ifKIrMmYfMBBmH8xzKUHktFcGZ0=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
26ODxwbeXJweaiZJsDvomrJ6yks=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in the request but not in incremental solution
9jgbGouy4/3vFpPCih/QoY2rN7w=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
6ZY6HgF9PjRLPfKsnGWTuTvOHeM=, Microsoft.CodeAnalysis.Options.SerializableOptionSet
```

### PR DESCRIPTION
**Pull request by mavasani**
**Strongly recommended to review commit by commit**

[First commit](https://github.com/dotnet/roslyn/commit/0feca6ce9b4fb0199ea745e063a8cb96ef5c711e) fixes the options checksum validation assert in servicehub dumps found in https://dev.azure.com/dnceng/public/_build/results?buildId=753622&view=artifacts&type=publishedArtifacts. The test added in that commit fails prior to the product changes in the commit.

[Second commit](https://github.com/dotnet/roslyn/commit/c471139857d924ae96468816ca4ab5b865ed180a) fixes #44791. The test added in the commit fails with the same assert as repro provided in #24408 prior to the product changes in the commit. Verified that the repro in #24408 also succeeds without asserts after this commit

### CODE REVIEW

**Comment by mavasani** [comment]
Ping for reviews.

File: src/Workspaces/CoreTest/Execution/SnapshotSerializationTests.cs [hunk 1]
```diff
@@ -700,12 +708,19 @@ void VerifyOptions(CompilationOptions originalOptions)
             }
         }
 
-        private static async Task VerifyOptionSetsAsync(Workspace workspace, Action<OptionSet> verifyOptionValues)
+        private static Task VerifyOptionSetsAsync(Action<OptionSet> verifyOptionValues)
         {
-            var solution = new AdhocWorkspace()
+            var workspace = new AdhocWorkspace()
```
Comment (tmat) [inline src/Workspaces/CoreTest/Execution/SnapshotSerializationTests.cs:713]: >var workspace [](start = 12, length = 13)

`using`

File: src/Workspaces/CoreTest/Execution/SnapshotSerializationTests.cs [hunk 2]
```diff
@@ -700,12 +708,19 @@ void VerifyOptions(CompilationOptions originalOptions)
...
                 .CurrentSolution.AddProject("Project1", "Project.dll", LanguageNames.CSharp)
-                .Solution.AddProject("Project2", "Project.dll", LanguageNames.VisualBasic)
-                .Solution;
+                .Solution.AddProject("Project2", "Project2.dll", LanguageNames.VisualBasic)
+                .Solution.Workspace;
```
Comment (tmat) [inline src/Workspaces/CoreTest/Execution/SnapshotSerializationTests.cs:716]: >.Workspace [](start = 25, length = 10)

Fetching workspace back from solution is odd.

**Comment by tmat** [comment]
>             var workspace = new AdhocWorkspace();

`using var workspace`

---
Refers to: src/Workspaces/CoreTest/Execution/SnapshotSerializationTests.cs:367 in 191848f. [](commit_id = 191848ff27b9547430a8c2ad90fab18f250dd1ca, deletion_comment = False)

File: src/Workspaces/CoreTest/Execution/SnapshotSerializationTests.cs [hunk 3]
```diff
@@ -700,12 +708,19 @@ void VerifyOptions(CompilationOptions originalOptions)
             }
         }
 
-        private static async Task VerifyOptionSetsAsync(Workspace workspace, Action<OptionSet> verifyOptionValues)
+        private static Task VerifyOptionSetsAsync(Action<OptionSet> verifyOptionValues)
```
Comment (tmat) [inline src/Workspaces/CoreTest/Execution/SnapshotSerializationTests.cs:711]: >VerifyOptionSetsAsync [](start = 28, length = 21)

This seems to be used only once, let's just inline it.

**Comment by mavasani** [comment]
Thanks @tmat @jasonmalinowski
