### PR TITLE
Check for uninitialized non-nullable static fields in interfaces

### LINKED ISSUE #46609: Static fields in interfaces don't get nullable initialization checks
**Version Used**: 4aaaed7

**Steps to Reproduce**:

```cs
#nullable enable
public interface I1 {
    public static string Prop { get; set; } // 1
}
```

**Expected Behavior**: Warning that `Prop` was not initialized

**Actual Behavior**: No warning

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #46609 

Static interface fields are still somewhat rare, so I don't know if this will introduce new warnings to our major consumers, but it's understandable if we want to wait to take this change for the moment. 😉

### CODE REVIEW

**Comment by jcouv** [comment]
I'm confused about https://github.com/dotnet/roslyn/issues/46609. The title says "field", but the example uses a property.
Anyways, please add the scenario from linked issue to this PR before closing.

File: src/Compilers/CSharp/Test/Semantic/Semantics/UninitializedNonNullableFieldTests.cs [hunk 1]
```diff
@@ -1638,6 +1638,9 @@ interface I
                 // (5,26): error CS8701: Target runtime doesn't support default interface implementation.
                 //     public static object F2;
                 Diagnostic(ErrorCode.ERR_RuntimeDoesNotSupportDefaultInterfaceImplementation, "F2").WithLocation(5, 26),
+                // (5,26): warning CS8618: Non-nullable field 'F2' must contain a non-null value when exiting constructor. Consider declaring the field as nullable.
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/UninitializedNonNullableFieldTests.cs:1641]: I'm not sure we care about this warning, since there's an error on F2 already.
Even with a runtime that supports DIM, we'd get an error because interfaces cannot contain state.
So I'm tempted to say we shouldn't make this change at all.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/UninitializedNonNullableFieldTests.cs:1640]: Static fields are allowed on interfaces when the runtime supports DIM.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/UninitializedNonNullableFieldTests.cs:1640]: > I'm not sure we care about this warning, since there's an error on F2 already.

The warning on F2 is completely different in nature and we generally accept both warnings being given simultaneously. Such a warning would be removed if the member is written anywhere in the program. The nullable init warning would only be removed by adding an initializer or static constructor which initializes the member.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/UninitializedNonNullableFieldTests.cs:1640]: I would also be happy to just make the interface public in this test in order to reduce the noise of the uninitialized field warnings.

Comment (jcouv) [reply src/Compilers/CSharp/Test/Semantic/Semantics/UninitializedNonNullableFieldTests.cs:1637]: Thanks much for the clarification. I'd forgotten that we allowed static fields (and constructors) in interfaces.

---
In reply to: [472494540](https://github.com/dotnet/roslyn/pull/46928#discussion_r472494540) [](ancestors = 472494540)

File: src/Compilers/CSharp/Test/Semantic/Semantics/UninitializedNonNullableFieldTests.cs [hunk 2]
```diff
@@ -1618,29 +1618,78 @@ static S()
...
 {
-    object F1;
-    public static object F2;
+    public object F1; // 1
+    public static object F2; // 2
+    public static object F3 { get; set; } // 3
+    public static event System.Action E1; // 4, 5
 }";
-            var comp = CreateCompilation(source);
+            var comp = CreateCompilation(source, targetFramework: TargetFramework.NetCoreApp30);
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/UninitializedNonNullableFieldTests.cs:1632]: >targetFramework: TargetFramework.NetCoreApp30 [](start = 49, length = 45)

Consider also compiling with default framework.
