### PR TITLE
Fix compiler server on CoreCLR and enable bootstrapping on CoreCLR build

### LINKED ISSUE #20900: Move Microsoft.NETCore.Compilers to a release package
This should be an "official" release package for CoreCLR as soon as https://github.com/dotnet/roslyn/issues/16717 is completed.

### PR DESCRIPTION
**Pull request by agocke**
### Customer scenario

This PR fixes the CoreCLR compiler server on Windows and changes our bootstrap build to act as a test case. The bug in the compiler server was we were attempting to do user ID verification on CoreCLR on Windows, but those APIs are not available on CoreCLR, so this would always fail. This fix disables user ID verification and relies only on Windows pipe ACLs, which should be enough to ensure that only properly privileged users can connect.

### Bugs this fixes

Fixes #20900 and #24072

### Workarounds, if any

There are no workarounds for using the compiler server under CoreCLR on Windows.

### Risk

This change is substantially similar to what we do on Linux, so has already been given a fair amount of coverage. 

### Performance impact

This should make the compiler much faster on CoreCLR.

### Is this a regression from a previous update?

No.

### Root cause analysis

We didn't bootstrap using the compiler server on CoreCLR, which I've now added.

### How was the bug found?

Customer reported.

### CODE REVIEW

File: netci.groovy [hunk 1]
```diff
@@ -87,7 +87,7 @@ commitPullList.each { isPr ->
     def myJob = job(jobName) {
       description("Windows CoreCLR unit tests")
             steps {
-              batchFile(""".\\build\\scripts\\cibuild.cmd ${(configuration == 'debug') ? '-debug' : '-release'} -testCoreClr""")
+              batchFile("""powershell -noprofile -executionPolicy RemoteSigned -file .\\build\\scripts\\cibuild.cmd ${(configuration == 'debug') ? '-debug' : '-release'} -restore -cibuild -bootstrap -coreClrBuild -testCoreClr -binaryLog""")
```
Comment (jaredpar) [inline netci.groovy]: This looks wrong. It's using powershell to target a CMD file. Not sure why we'd change this to use powershell here in any case.

File: build/NuGetAdditionalFiles/Microsoft.NETCore.Compilers.props [hunk 2]
```diff
@@ -9,15 +9,17 @@
              AssemblyFile="$(MSBuildThisFileDirectory)..\tools\Microsoft.Build.Tasks.CodeAnalysis.dll" />
   <UsingTask TaskName="Microsoft.CodeAnalysis.BuildTasks.CopyRefAssembly"
              AssemblyFile="$(MSBuildThisFileDirectory)..\tools\Microsoft.Build.Tasks.CodeAnalysis.dll" />
+
   <PropertyGroup>
+    <!-- Don't use the compiler server by default in the NuGet package. -->
+    <UseSharedCompilation Condition="'$(UseSharedCompilation)' == ''">false</UseSharedCompilation>
```
Comment (jaredpar) [inline build/NuGetAdditionalFiles/Microsoft.NETCore.Compilers.props]: Why are we making this change? We made this "true" by default in the NuGet package in response to customer feedback here around performance.

File: build/scripts/build.ps1 [hunk 3]
```diff
@@ -110,6 +111,12 @@ function Process-Arguments() {
         exit 1
     }
 
+    if ($build -and $coreClrBuild)
+    {
```
Comment (jaredpar) [inline build/scripts/build.ps1]: Powershell braces start on same line as previous construct.

File: build/scripts/build.ps1 [hunk 4]
```diff
@@ -164,17 +181,30 @@ function Run-MSBuild([string]$projectFilePath, [string]$buildArgs = "", [string]
...
-    Run-MSBuild "build\Toolset\Toolset.csproj" "/p:UseShippingAssemblyVersion=true /p:InitialDefineConstants=BOOTSTRAP" -logFileName "Bootstrap"
     $dir = Join-Path $binariesDir "Bootstrap"
+    Write-Host "Building Bootstrap compiler"
+    $bootstrapArgs = "/p:UseShippingAssemblyVersion=true /p:InitialDefineConstants=BOOTSTRAP"
     Remove-Item -re $dir -ErrorAction SilentlyContinue
     Create-Directory $dir
-    Move-Item "$configDir\Exes\Toolset\*" $dir
+    if ($coreClrBuild) {
+        $bootstrapFramework = "netcoreapp2.0"
+        Exec-Console "dotnet" "publish --no-restore src/Compilers/CSharp/csc -o `"$dir/bincore`" --framework $bootstrapFramework $bootstrapArgs -bl:$binariesDir/BootstrapCsc.binlog"
```
Comment (jaredpar) [inline build/scripts/build.ps1]: Log files should go into `Binaries\Logs`

File: src/Compilers/Core/MSBuildTask/Utilities.cs [hunk 5]
```diff
@@ -214,6 +215,7 @@ public static string GenerateFullPathToTool(string toolName)
                     }
                 }
 
+
```
Comment (jaredpar) [inline src/Compilers/Core/MSBuildTask/Utilities.cs]: Extraneous blank line.

File: build/NuGetAdditionalFiles/Microsoft.NETCore.Compilers.props (hunk 2 above)
Comment (agocke) [reply build/NuGetAdditionalFiles/Microsoft.NETCore.Compilers.props]: I don't think that's true -- this matches the desktop behavior as far as I can see.

File: netci.groovy (hunk 1 above)
Comment (agocke) [reply netci.groovy]: Yeah this should have been `build.ps1`. The problem is that `cibuild.cmd` passes the `-build` arg, which I made incompatible with `-coreClrBuild`. Would you prefer that both flags are required, and `coreClrBuild` just forces coreclr instead of desktop?

File: build/NuGetAdditionalFiles/Microsoft.NETCore.Compilers.props (hunk 2 above)
Comment (tannergooding) [reply build/NuGetAdditionalFiles/Microsoft.NETCore.Compilers.props]: Any projects using the "new" project format will have `UseSharedCompilation` set to `true` by default: https://github.com/dotnet/sdk/blob/8a24663345cc5952062cb898431dbd8800b4da85/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.targets#L428

Comment (agocke) [reply build/NuGetAdditionalFiles/Microsoft.NETCore.Compilers.props]: https://github.com/dotnet/roslyn/blob/6db04109879e42fbe99a3c1e8f1d44175c041e73/build/NuGetAdditionalFiles/Microsoft.Net.Compilers.props#L31

I'm not sure why the line above says "in Visual Studio" -- this applies to the NuGet package.

File: netci.groovy (hunk 1 above)
Comment (jaredpar) [reply netci.groovy]: I would do the following:

- Rename `-coreClrBuild` to `-buildCoreClr`.
- Allow mixing of `-build` and `-buildCoreClr`. Would actually set `-build` to true if `-buildCoreClr` is true in `Process-Arguments`

This would give `-buildCoreClr` a lot of symetry with `-buildAll`

File: build/NuGetAdditionalFiles/Microsoft.NETCore.Compilers.props (hunk 2 above)
Comment (agocke) [reply build/NuGetAdditionalFiles/Microsoft.NETCore.Compilers.props]: @tannergooding That line won't be evaluated until after we evaluate this property if the package is installed via NuGet.

Comment (tannergooding) [reply build/NuGetAdditionalFiles/Microsoft.NETCore.Compilers.props]: Yes, but this line will prevent the compiler server from being used on new SDK which has a different default from Desktop.

Comment (agocke) [reply build/NuGetAdditionalFiles/Microsoft.NETCore.Compilers.props]: @tannergooding The same property is set on Desktop: https://github.com/dotnet/roslyn/blob/6db04109879e42fbe99a3c1e8f1d44175c041e73/src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets#L79

File: netci.groovy (hunk 1 above)
Comment (agocke) [reply netci.groovy]: The reason I didn't do that is because, unlike buildAll, this doesn't build the same stuff as `-build` (it only builds Compilers.sln). Is that still OK?

**Comment by agocke** [comment]
@jaredpar Can you take another look at this? I think I've addressed your comments.

File: src/Compilers/Shared/BuildServerConnection.cs [hunk 6]
```diff
@@ -454,6 +454,13 @@ private static bool CheckPipeConnectionOwnership(NamedPipeClientStream pipeStrea
             {
                 if (PlatformInformation.IsWindows)
                 {
+                    if (CoreClrShim.IsRunningOnCoreClr)
+                    {
+                        // CoreCLR doesn't have these APIs, so we just have to rely on
+                        // Windows ACLs for security
+                        return true;
```
Comment (jaredpar) [inline src/Compilers/Shared/BuildServerConnection.cs]: Unfortunately at this point on CoreClr we don't have ACLs 

https://github.com/dotnet/corefx/issues/24040

This means we no longer have ACLs or identity verification.

File: build/scripts/build.ps1 [hunk 7]
```diff
@@ -164,22 +180,41 @@ function Run-MSBuild([string]$projectFilePath, [string]$buildArgs = "", [string]
...
-    Move-Item "$configDir\Exes\Toolset\*" $dir
+    if ($buildCoreClr) {
+        $bootstrapFramework = "netcoreapp2.0"
+        $logDir = Join-Path $binariesDir "Logs"
+        Create-Directory $logDir
+        Exec-Console "dotnet" "publish --no-restore src/Compilers/CSharp/csc -o `"$dir/bincore`" --framework $bootstrapFramework $bootstrapArgs -bl:$logDir/BootstrapCsc.binlog"
+        Exec-Console "dotnet" "publish --no-restore src/Compilers/VisualBasic/vbc -o `"$dir/bincore`" --framework $bootstrapFramework $bootstrapArgs -bl:$logDir/BootstrapVbc.binlog"
+        Exec-Console "dotnet" "publish --no-restore src/Compilers/Server/VBCSCompiler -o `"$dir/bincore`" --framework $bootstrapFramework $bootstrapArgs -bl:$logDir/BootstrapVBCSCompiler.binlog"
+        Exec-Console "dotnet" "publish --no-restore src/Compilers/Core/MSBuildTask -o `"$dir`" $bootstrapArgs -bl:$binariesDir/BootstrapMSBuildTask.binlog"
+        Exec-Console "dotnet" "$dir/bincore/VBCSCompiler.dll" -shutdown
```
Comment (jaredpar) [inline build/scripts/build.ps1]: Add `exec` to be explicit here.

File: build/scripts/build.ps1 [hunk 8]
```diff
@@ -164,22 +180,41 @@ function Run-MSBuild([string]$projectFilePath, [string]$buildArgs = "", [string]
...
-    Write-Host "Cleaning Bootstrap compiler artifacts"
-    Run-MSBuild "build\Toolset\Toolset.csproj" "/t:Clean" -logFileName "BootstrapClean"
-    Stop-BuildProcesses
     return $dir
 }
 
 function Build-Artifacts() { 
-    if ($build) { 
+    if ($buildCoreClr)
+    {
```
Comment (jaredpar) [inline build/scripts/build.ps1]: Open braces same line.

File: build/scripts/build.ps1 [hunk 9]
```diff
@@ -628,7 +663,7 @@ try {
         $bootstrapDir = Make-BootstrapBuild
     }
 
-    if ($build -or $pack) {
+    if ($build -or $buildCoreClr -or $pack) {
```
Comment (jaredpar) [inline build/scripts/build.ps1]: I think we should be consistent with `$buildAll` here. Inside `Process-Arguments` we should set `$build` to `$true` if `$buildCoreClr` is also `$true`.

File: build/scripts/build.ps1 [hunk 10]
```diff
@@ -155,7 +161,17 @@ function Run-MSBuild([string]$projectFilePath, [string]$buildArgs = "", [string]
 
     $args += " $buildArgs"
     $args += " $projectFilePath"
-    Exec-Console $msbuild $args
+
+    if ($useDotnetBuild)
```
Comment (jaredpar) [inline build/scripts/build.ps1]: Braces same line in powershell

File: build/scripts/build.ps1 [hunk 11]
```diff
@@ -164,22 +180,40 @@ function Run-MSBuild([string]$projectFilePath, [string]$buildArgs = "", [string]
...
     Create-Directory $dir
-    Move-Item "$configDir\Exes\Toolset\*" $dir
+    if ($buildCoreClr) {
+        $bootstrapFramework = "netcoreapp2.0"
+        $logDir = Join-Path $binariesDir "Logs"
+        Create-Directory $logDir
+        Exec-Console "dotnet" "publish --no-restore src/Compilers/CSharp/csc -o `"$dir/bincore`" --framework $bootstrapFramework $bootstrapArgs -bl:$logDir/BootstrapCsc.binlog"
+        Exec-Console "dotnet" "publish --no-restore src/Compilers/VisualBasic/vbc -o `"$dir/bincore`" --framework $bootstrapFramework $bootstrapArgs -bl:$logDir/BootstrapVbc.binlog"
+        Exec-Console "dotnet" "publish --no-restore src/Compilers/Server/VBCSCompiler -o `"$dir/bincore`" --framework $bootstrapFramework $bootstrapArgs -bl:$logDir/BootstrapVBCSCompiler.binlog"
+        Exec-Console "dotnet" "publish --no-restore src/Compilers/Core/MSBuildTask -o `"$dir`" $bootstrapArgs -bl:$binariesDir/BootstrapMSBuildTask.binlog"
```
Comment (jaredpar) [inline build/scripts/build.ps1]: Why aren't we killing the server here

Comment (agocke) [reply build/scripts/build.ps1]: No server to kill. The server can't be used via NuGet package until this is merged :)

Comment (jaredpar) [reply build/scripts/build.ps1]: But once this is merged will need to kill the server. I would add back the kill and just catch the failure condition.

File: build/NuGetAdditionalFiles/Microsoft.NETCore.Compilers.props [hunk 12]
```diff
@@ -9,15 +9,17 @@
...
     <BasicCoreTargetsPath>$(MSBuildThisFileDirectory)..\tools\Microsoft.VisualBasic.Core.targets</BasicCoreTargetsPath>
   </PropertyGroup>
 
-  <!-- Set ToolPath/Exe to direct to the exes in this package -->
-  <PropertyGroup>
-    <!-- Compiler server is not currently supported on CoreCLR -->
-    <UseSharedCompilation>false</UseSharedCompilation>
+  <!-- Older versions of the CLI didn't set the DOTNET_HOST_PATH variable, which
+       means we have to use our shell wrappers and hope 'dotnet' is on the path. -->
+  <PropertyGroup Condition="'$(DOTNET_HOST_PATH)' == ''">
```
Comment (jaredpar) [inline build/NuGetAdditionalFiles/Microsoft.NETCore.Compilers.props]: Can we file an issue to track deleting this? Once we get past 2.1 we should no longer support this case.

File: build/NuGetAdditionalFiles/Microsoft.NETCore.Compilers.props [hunk 13]
```diff
@@ -29,7 +31,9 @@
   <!-- If packaged on Windows, the RunCsc and RunVbc scripts may not be marked
        executable. If we're not running on Windows, mark them as such, just in case -->
   <Target Name="MakeCompilerScriptsExecutable"
-          Condition="'$(BuildingProject)' == 'true' AND '$(OS)' != 'Windows_NT'"
+          Condition="'$(BuildingProject)' == 'true' AND
+                     '$(OS)' != 'Windows_NT' AND
+                     '$(CscToolPath)' != ''"
```
Comment (jaredpar) [inline build/NuGetAdditionalFiles/Microsoft.NETCore.Compilers.props]: Don't agree with the `CscToolPath` condition here. Consider the case where only `CscToolPath` was set but not `VbcToolPath`. In that case we still need to make the scripts executable.

File: build/scripts/build.ps1 [hunk 14]
```diff
@@ -28,6 +28,7 @@ param (
     [switch]$pack = $false,
     [switch]$binaryLog = $false,
     [string]$signType = "",
+    [switch]$buildCoreClr = $false,
```
Comment (jaredpar) [inline build/scripts/build.ps1]: Please group this with the other build options.

File: build/scripts/build.ps1 (hunk 10 above)
Comment (jaredpar) [reply build/scripts/build.ps1]: Ping

File: build/scripts/build.ps1 [hunk 15]
```diff
@@ -155,7 +161,17 @@ function Run-MSBuild([string]$projectFilePath, [string]$buildArgs = "", [string]
...
-    Exec-Console $msbuild $args
+
+    if ($useDotnetBuild)
+    {
+        $args = " build --no-restore " + $args
+        $args += " -m:1"
+        Exec-Console $dotnet $args
+    }
+    else
+    {
```
Comment (jaredpar) [inline build/scripts/build.ps1]: Open Braces on same line in powershell.

File: src/Compilers/Core/MSBuildTask/AssemblyResolution.cs [hunk 16]
```diff
@@ -85,6 +102,34 @@ private static bool TryRedirect(AssemblyName name, byte[] token, int major, int
             return false;
         }
 
+        private static readonly string s_assemblyLocation = Utilities.TryGetAssemblyPath(typeof(AssemblyResolution).GetTypeInfo().Assembly);
+        private static Assembly TryRedirectToRuntimesDir(AssemblyName name)
```
Comment (jaredpar) [inline src/Compilers/Core/MSBuildTask/AssemblyResolution.cs]: Do we have a bug tracking the undo'ing of this at a later date?

File: src/NuGet/Microsoft.NETCore.Compilers.nuspec [hunk 17]
```diff
@@ -26,9 +26,12 @@
...
     <!-- Targets and task files -->
-    <file src="Dlls/MSBuildTask/Microsoft.Build.Tasks.CodeAnalysis.dll" target="tools" />
-    <file src="Dlls/MSbuildTask/Microsoft.CSharp.Core.targets" target="tools" />
-    <file src="Dlls/MSbuildTask/Microsoft.VisualBasic.Core.targets" target="tools" />
+    <file src="Dlls/MSBuildTask/netstandard1.3/publish/Microsoft.Build.Tasks.CodeAnalysis.dll" target="tools" />
+    <file src="Dlls/MSbuildTask/netstandard1.3/publish/Microsoft.CSharp.Core.targets" target="tools" />
+    <file src="Dlls/MSbuildTask/netstandard1.3/publish/Microsoft.VisualBasic.Core.targets" target="tools" />
+    <!-- N.B.: The backslashes below cannot be replaced with forward slashes. -->
+    <file src="Dlls\MSBuildTask\netstandard1.3\publish\System.*.dll" target="tools" />
+    <file src="Dlls\MSBuildTask\netstandard1.3\publish\runtimes\**" target="tools\runtimes" />
```
Comment (jaredpar) [inline src/NuGet/Microsoft.NETCore.Compilers.nuspec]: Can we pick `\` or `/` for the slash direction? Don't care which we use, just prefer we use one of them.

File: src/NuGet/Microsoft.NETCore.Compilers.nuspec [hunk 18]
```diff
@@ -49,6 +52,7 @@
     <file src="Exes/VBCSCompiler/netcoreapp2.0/publish/VBCSCompiler.runtimeconfig.json" target="tools/bincore" />
 
     <!-- References that are either not in the target framework or are a higher version -->
+    <!-- N.B.: The backslashes below cannot be replaced with forward slashes. -->
```
Comment (jaredpar) [inline src/NuGet/Microsoft.NETCore.Compilers.nuspec]: I don't want to ask but I have to ... why?

Comment (agocke) [reply src/NuGet/Microsoft.NETCore.Compilers.nuspec]: It looks like NuGet has different behavior -- the backslashes are interpreted as "everything in this directory" while forward slashes are "the entire directory tree, including parent directories"

File: build/NuGetAdditionalFiles/Microsoft.NETCore.Compilers.props (hunk 13 above)
Comment (agocke) [reply build/NuGetAdditionalFiles/Microsoft.NETCore.Compilers.props]: Yeah good point.

File: src/NuGet/Microsoft.NETCore.Compilers.nuspec (hunk 17 above)
Comment (agocke) [reply src/NuGet/Microsoft.NETCore.Compilers.nuspec]: I'm now worried about changing anything here because I have no idea what it will do to the package layout.

File: build/NuGetAdditionalFiles/Microsoft.NETCore.Compilers.props (hunk 12 above)
Comment (agocke) [reply build/NuGetAdditionalFiles/Microsoft.NETCore.Compilers.props]: I think we'll have to support installing newer compilers on older runtimes for quite a while, no? Is there any reason not to support that, if this is the only complexity?

File: build/scripts/build.ps1 (hunk 11 above)
Comment (jaredpar) [reply build/scripts/build.ps1]: Ping on this Q

File: src/Compilers/Core/MSBuildTask/AssemblyResolution.cs (hunk 16 above)
Comment (agocke) [reply src/Compilers/Core/MSBuildTask/AssemblyResolution.cs]: Will we actually undo it? I'm not sure MSBuild or CoreCLR are going to do anything about this.

File: build/NuGetAdditionalFiles/Microsoft.NETCore.Compilers.props (hunk 12 above)
Comment (jaredpar) [reply build/NuGetAdditionalFiles/Microsoft.NETCore.Compilers.props]: I didn't think it was possible at all in older CLI. Could be wrong.

File: build/scripts/build.ps1 (hunk 8 above)
Comment (jaredpar) [reply build/scripts/build.ps1]: Open braces on same line.

File: src/Compilers/Core/MSBuildTask/AssemblyResolution.cs [hunk 19]
```diff
@@ -68,11 +70,25 @@ private static bool TryRedirect(AssemblyName name)
                 case "System.Reflection":
                     return TryRedirect(name, s_b03f5f7f11d50a3a, 4, 1, 1, 0);
 
+                // Assemblies in the runtimes directory
```
Comment (jaredpar) [inline src/Compilers/Core/MSBuildTask/AssemblyResolution.cs]: Please expand the comment on why this makes a difference.

File: src/Compilers/Core/MSBuildTask/AssemblyResolution.cs (hunk 16 above)
Comment (jaredpar) [reply src/Compilers/Core/MSBuildTask/AssemblyResolution.cs]: The solution can't be this code though. We need to file a bug with CoreClr to get them to tell us the right way to do this, or provide an assembly load context that has rationale behavior.

Comment (agocke) [reply src/Compilers/Core/MSBuildTask/AssemblyResolution.cs]: Filed https://github.com/dotnet/coreclr/issues/15982. I'll add a link

Comment (agocke) [reply src/Compilers/Core/MSBuildTask/AssemblyResolution.cs]: Also filed https://github.com/dotnet/roslyn/issues/24397

File: build/scripts/build.ps1 (hunk 11 above)
Comment (agocke) [reply build/scripts/build.ps1]: Added Stop-BuildProcesses at the end here, so when this works we'll be all set.

File: build/scripts/build.ps1 (hunk 7 above)
Comment (agocke) [reply build/scripts/build.ps1]: `exec` is not really supported, AFAIK. The official guidance is just to pass the DLL as an argument.

File: build/scripts/build.ps1 (hunk 11 above)
Comment (jasonmalinowski) [reply build/scripts/build.ps1]: @agocke Don't you want to do it at the beginning in case there is detritus from a previous run? Imagine somebody running this script locally to test changes.

Comment (agocke) [reply build/scripts/build.ps1]: I believe that's the purpose of the call in the try-finally at the top-level.
