### PR TITLE
Remove places where the compiler is swallowing exceptions

### LINKED ISSUE #58375: Delete FatalError.ReportIfNonFatalAndCatchUnlessCanceled
https://github.com/dotnet/roslyn/pull/58094 introduced this method as a shim for several places in the compiler that needed that specific behavior. It was agreed that we really don't _want_ that behavior, but it was prudent to not change things for 17.1 given our relative lateness in the cycle. We want to rip it out immediately at the start of 17.2, so if there are any bugs still being masked we can have sufficient time to react to them.

The last commit in the PR details the precise set of steps we want to do to undo it.

### PR DESCRIPTION
**Pull request by jasonmalinowski**
There are a few places where compiler APIs are swallowing internal exceptions and returning null from APIs as a way to march on; this removes those places, and then removes our ReportAndCatch* APIs from the compiler layer entirely. We currently have no (cross platform) way of implementing those in a way that would allow for non-fatal error reporting.

Closes #58375

### CODE REVIEW

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs [hunk 1]
```diff
@@ -1657,9 +1657,7 @@ private static string CreateDisablingMessage(DiagnosticAnalyzer analyzer)
                     diagnosticIds = diagnosticIds.Add(diagnostic.Id);
                 }
             }
-#pragma warning disable CS0618 // ReportIfNonFatalAndCatchUnlessCanceled is obsolete; tracked by https://github.com/dotnet/roslyn/issues/58375
-            catch (Exception e) when (FatalError.ReportIfNonFatalAndCatchUnlessCanceled(e))
-#pragma warning restore CS0618 // ReportIfNonFatalAndCatchUnlessCanceled is obsolete
+            catch (Exception)
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs:1660]: this seems undesirable... pure swallow that gets reported nowhere?

File: src/Compilers/Core/Portable/InternalUtilities/ExceptionUtilities.cs [hunk 2]
```diff
@@ -27,5 +28,26 @@ internal static Exception Unreachable
...
+        /// Determine if an exception was not an <see cref="OperationCanceledException"/>, and optionally check that the provided token was cancelled.
+        /// </summary>
+        /// <remarks>
+        /// Used in exception filters to determine if the exception should be handled or not.
+        /// </remarks>
+        /// <param name="exception">The exception to test.</param>
+        /// <param name="cancellationToken">Optional. Checked to see if the cancellation was caused by the provided token and considered not cancelled if not.</param>
+        /// <returns><see langword="true"/> if the exception should be handled by the caller, or <see langword="false"/> if the exception was caused by cancellation.</returns>
+        internal static bool IsNotCancelled(Exception exception, CancellationToken? cancellationToken = null)
+            => !IsCurrentOperationBeingCancelled(exception, cancellationToken ?? new CancellationToken(true));
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/InternalUtilities/ExceptionUtilities.cs:42]: somewhat don't love this.  can't figure out why.  but it might be the weirdness witht he optional params and the !...

Comment (CyrusNajmabadi) [reply src/Compilers/Core/Portable/InternalUtilities/ExceptionUtilities.cs:42]: i'm trying to think of a reason why the CT should be optional here.  if someone is asking if it IsNotCancelled... i feel like they should have the CT to be checking against...

File: src/Compilers/Core/Portable/InternalUtilities/ExceptionUtilities.cs [hunk 3]
```diff
@@ -27,5 +28,26 @@ internal static Exception Unreachable
...
+
+         /// <summary>
+        /// Determine if an exception was an <see cref="OperationCanceledException"/>, and that the token was cancelled.
+        /// </summary>
+        /// <param name="exception">The exception to test.</param>
+        /// <param name="cancellationToken">Checked to see if the provided token was cancelled.</param>
+        /// <returns><see langword="true"/> if the exception was an <see cref="OperationCanceledException" /> and the token was canceled.</returns>
+        internal static bool IsCurrentOperationBeingCancelled(Exception exception, CancellationToken cancellationToken)
+            => exception is OperationCanceledException && cancellationToken.IsCancellationRequested;
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/InternalUtilities/ExceptionUtilities.cs:51]: this feels loosygoosy.  do we want to check that the OCE points at this CT instead?

File: src/Compilers/Core/Portable/SourceGeneration/UserFunction.cs [hunk 4]
```diff
@@ -52,9 +50,7 @@ internal static Action<TInput> WrapUserAction<TInput>(this Action<TInput> userAc
                 {
                     userAction(input);
                 }
-#pragma warning disable CS0618 // ReportIfNonFatalAndCatchUnlessCanceled is obsolete; tracked by https://github.com/dotnet/roslyn/issues/58375
-                catch (Exception e) when (FatalError.ReportIfNonFatalAndCatchUnlessCanceled(e))
-#pragma warning restore CS0618 // ReportIfNonFatalAndCatchUnlessCanceled is obsolete
+                catch (Exception e) when (ExceptionUtilities.IsNotCancelled(e))
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/SourceGeneration/UserFunction.cs:53]: maybe WrapUserAction should take a CT?

**Comment by CyrusNajmabadi** [comment]
I'm pro making things better here.  i always get worried when i feel that we're potentially introducing more non-invariant-behaving code over CTs though.

**Comment by AraHaan** [comment]
I also think the CT should ne required in that function as well.

**Comment by jasonmalinowski** [comment]
So note the first commit here is actually @chsienki's PR #58843, and this was building off of it. So @CyrusNajmabadi and @AraHaan your feedback should go there. (This is a draft so we can get the second part working while @chsienski finishes his part.)

File: src/Compilers/Core/Portable/InternalUtilities/ExceptionUtilities.cs (hunk 2 above)
Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/InternalUtilities/ExceptionUtilities.cs]: These changes are no longer part of this PR.

File: src/Compilers/Core/Portable/SourceGeneration/UserFunction.cs (hunk 4 above)
Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/SourceGeneration/UserFunction.cs]: These changes are no longer part of this PR.

File: src/Compilers/Core/Portable/InternalUtilities/ExceptionUtilities.cs (hunk 3 above)
Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/InternalUtilities/ExceptionUtilities.cs]: This is no longer part of this PR.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs (hunk 1 above)
Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs:1660]: @mavasani any suggestions here?

**Review by ryzngard — APPROVED** [review]
Everything but the open question https://github.com/dotnet/roslyn/pull/58870/files#r794881243 LGTM. Signing off with the assumption that will be resolved before merge

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs (hunk 1 above)
Comment (333fred) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs:1660]: Most of the PR seems fine to me, except this bit. Now it won't even get reported.

Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs:1660]: And note that the current behavior here to "report" only would have sent telemetry to us; there's no user indication here at all of what happened.

Comment (333fred) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs:1660]: Right, I didn't assume that users would understand what was happening. I meant we wouldn't even be able to understand that there's a problem.

Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs:1660]: So more confusingly, this seems to only be used in CreateAnalyzerExceptionDiagnostic above; it seems in the command line case that disabling message this is producing isn't even shown. It also seems we don't show analyzer exceptions in the IDE _either_, so this might be (accidentally) dead code.

I think the reasonable thing to do here is change the "intentionally empty" to actually return a string saying further errors occurred, but right now I'm unable to prove that string is actually shown anywhere. :-/

Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs]: So further investigation led to https://github.com/dotnet/roslyn/issues/59214. I've updated this to also include the exception text here if we were to get exceptions thrown at this point.

Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs]: @mavasani Any recommendations for where to add a test for this?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs [hunk 5]
```diff
@@ -1657,11 +1657,9 @@ private static string CreateDisablingMessage(DiagnosticAnalyzer analyzer)
                     diagnosticIds = diagnosticIds.Add(diagnostic.Id);
                 }
             }
-#pragma warning disable CS0618 // ReportIfNonFatalAndCatchUnlessCanceled is obsolete; tracked by https://github.com/dotnet/roslyn/issues/58375
-            catch (Exception e) when (FatalError.ReportIfNonFatalAndCatchUnlessCanceled(e))
-#pragma warning restore CS0618 // ReportIfNonFatalAndCatchUnlessCanceled is obsolete
+            catch (Exception ex)
             {
-                // Intentionally empty
+                return string.Format(CodeAnalysisResources.AnalyzerDriverThrowsDescription, ex.CreateDiagnosticDescription())
```
Comment (RikkiGibson) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs:1662]:
```suggestion
                return string.Format(CodeAnalysisResources.AnalyzerDriverThrowsDescription, ex.CreateDiagnosticDescription());
```

**Review by 333fred — APPROVED** [review]
LGTM once the missing semicolon is added :stuck_out_tongue:

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs (hunk 1 above)
Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs]: Chatting with @mavasani privately we'll add a unit test after this goes in, just so we can get this in for our current cutoff.

**Review by RikkiGibson — APPROVED** [review]
LGTM to merge once validation completes

**Comment by jasonmalinowski** [comment]
@RikkiGibson @333fred @mavasani  Turned out that change did require a test baseline to be updated in one test, and required another small tweak. I've made the update and [you can view the diff here](https://github.com/dotnet/roslyn/compare/45fbb5564e826071436884041e4bc3dfd1b65ad5..b250868832c6b324266d2d6bb56b01e97461519f) since I force-pushed.

We do have a test that confirms that nulls being returned from analyzers already produce diagnostics that it's bad, so no reason to report further exceptions there. The other test got a baseline update so we do have coverage on this path after all. I can't say the output of the exception in that case is _pretty_ but if we want to tweak that further let's do so after this is in.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs (hunk 1 above)
Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs]: This change did break a test due to the new exception message so I've updated that accordingly.

**Review by 333fred — APPROVED** [review]

**Comment by RikkiGibson** [comment]
Validation run is clean. Go for it @jasonmalinowski.
