### PR TITLE
Address feedback on the "references newer compiler" diagnostic in the analyzer loader

### LINKED ISSUE #62583: Public API for "Compiler needs to declaratively fail when loading newer analyzers"
## Background and Motivation

Follow-up to #61252

Similarly to `ReferencesFramework` #47100, we want to produce a specific error for a specific kind of analyzer misconfiguration. In this case, we want to give a warning when the compiler loads an analyzer which references a newer compiler than the one currently running.

One common place where this might occur is if you are running VS 17.0 and editing a project which uses dotnet sdk version 6.0.300. This is a supported configuration, but when we build in VS, we end up loading analyzers which need a newer compiler, and the build fails in a fairly opaque way:

`Warning CS8032: An instance of analyzer Microsoft.CodeAnalysis.MakeFieldReadonly.MakeFieldReadonlyDiagnosticAnalyzer cannot be created from C:\hostedtoolcache\windows\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CodeStyle.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..`

This change lets us give a more specific error like the following:

`warning CS9057: The analyzer assembly 'C:\hostedtoolcache\windows\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CodeStyle.dll' references version '4.2.0.0' of the compiler, which is newer than the currently running version '4.0.0.0'.`

## Proposed API

```diff
namespace Microsoft.CodeAnalysis.Diagnostics
{
    public sealed class AnalyzerLoadFailureEventArgs : EventArgs
    {
        public enum FailureErrorCode
        {
            None = 0,
            UnableToLoadAnalyzer = 1,
            UnableToCreateAnalyzer = 2,
            NoAnalyzers = 3,
            ReferencesFramework = 4,
+            ReferencesNewerCompiler = 5
        }

        public string? TypeName { get; }

        public string Message { get; }

        public FailureErrorCode ErrorCode { get; }

        public Exception? Exception { get; }

+        public Version? ReferencedCompilerVersion { get; init; }

        public AnalyzerLoadFailureEventArgs(FailureErrorCode errorCode, string message, Exception? exceptionOpt = null, string? typeNameOpt = null)
```

## Usage Examples

The IDE needs to check for this specific error condition in order to add the right diagnostic to the error list and update the analyzer node in Solution Explorer appropriately.

https://github.com/dotnet/roslyn/blob/be8eed3a523fb33b747fdc258a175ca8875fe94d/src/Features/LanguageServer/Protocol/Features/Diagnostics/DocumentAnalysisExecutor_Helpers.cs#L101-L109

## Alternative Designs

We could reduce the accessibility of `ReferencedCompilerVersion.init` to `internal`. There isn't really a reason for users of the compiler to produce these load failure events--just to consume them. However, it is already possible to create these EventArgs and pass everything they need to them from the public context, so it would be inconsistent to disallow just this property.

We could also delete the `init` accessor here and instead introduce another constructor with an additional parameter. We might want to eliminate the default arguments from the existing constructor at that time, so that binary compat is preserved and we also match our guideline to avoid multiple overloads with optional parameters.

## Risks

The rest of the type uses get-only properties. I'm not sure if we've exposed init-only properties in Roslyn yet, so that could also be risky, since `init` properties are not technically supported in some of the settings we ship in.

Tagging @mavasani and @333fred as area owners.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Follow-up to #61261
Closes #62583

### CODE REVIEW

File: src/EditorFeatures/Test/Diagnostics/AnalyzerLoadFailureTests.cs [hunk 1]
```diff
@@ -31,10 +31,7 @@ public class AnalyzerLoadFailureTests
             var eventArgs = new AnalyzerLoadFailureEventArgs(
                 errorCode,
                 message: errorCode.ToString(),
-                typeNameOpt: expectsTypeName ? analyzerTypeName : null)
-            {
-                ReferencedCompilerVersion = errorCode is AnalyzerLoadFailureEventArgs.FailureErrorCode.ReferencesNewerCompiler ? new Version(100, 0, 0, 0) : null
-            };
+                typeNameOpt: expectsTypeName ? analyzerTypeName : null);
```
Comment (RikkiGibson) [inline src/EditorFeatures/Test/Diagnostics/AnalyzerLoadFailureTests.cs:34]: It feels like the goal of this test could be accomplished by introducing some internal helper to `CreateAnalyzerLoadFailureDiagnostic` which asserts that the `FailureErrorCode` falls within an expected range, then running the test on that helper instead of `CreateAnalyzerLoadFailureDiagnostic` itself. I'd prefer to keep the change minimal here for now, though.

**Comment by RikkiGibson** [comment]
@333fred did we expect fabric-bot to leave a comment here?

**Review by jaredpar — APPROVED** [review]

**Comment by RikkiGibson** [comment]
@Cosifne once we get this merged, we should be good to push thru QB.

**Review by cston — APPROVED** [review]
