### PR TITLE
Corrects the ConvertToAutoPropertyCS sample

### LINKED ISSUE #2127: ConvertToAutoPropertyCS sample doesn't delete the backing field (CTP2)
Ported from TFS WorkItem: **529534**

------------------------------

**Repro Steps:**

When you build and run the sample, then try to apply it on this code:  

```
class Program 
{ 
    private string name; 
    public string Name 
    { 
        get 
        { 
            return this.name; 
        } 
        set 
        { 
            this.name = value; 
        } 
    } 
} 
```

It is expected to remove the backing field, however the backing field isn&#39;t removed.

### PR DESCRIPTION
**Pull request by AmadeusW**
Correctly checks for the field variable's symbol in the **ConvertToAutoPropertyCS** sample

This fixes #2127 

---

This fix could be improved by also cleaning up fields with multiple variables declared. Currently a field with multiple variables is left intact. Do we want to demonstrate such scenario in a code fix provider?

img

This can be accomplished with the following code:
```csharp
            else if (field.Declaration.Variables.Count > 1)
            {
                return field.WithDeclaration(
                    field.Declaration.WithVariables(
                        SyntaxFactory.SeparatedList(
                            field.Declaration.Variables.Where(
                                v => !object.Equals(semanticModel.GetDeclaredSymbol(v), backingField)
                            )
                        )
                    )
                );
            }
```

However, this would require Linq which is against [the contribution guidelines](https://github.com/dotnet/roslyn/wiki/Contributing-Code) regarding the compiler hot path. This is an analyzer, is Linq ok here?

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/roslyn-ide

**Comment by Pilchie** [comment]
:+1:, though we're actually looking at bringing this functionality directly into VS2015.

Tagging @CyrusNajmabadi again.

File: src/Samples/CSharp/ConvertToAutoProperty/Impl/PropertyRewriter.cs [hunk 1]
```diff
@@ -57,10 +57,10 @@ public override SyntaxNode VisitPropertyDeclaration(PropertyDeclarationSyntax pr
 
         public override SyntaxNode VisitFieldDeclaration(FieldDeclarationSyntax field)
         {
-            // Retrieve the symbol for the field
+            // Retrieve the symbol for the field's variable
             if (field.Declaration.Variables.Count == 1)
             {
-                if (object.Equals(semanticModel.GetDeclaredSymbol(field), backingField))
+                if (object.Equals(semanticModel.GetDeclaredSymbol(field.Declaration.Variables.FirstOrDefault()), backingField))
```
Comment (jasonmalinowski) [inline src/Samples/CSharp/ConvertToAutoProperty/Impl/PropertyRewriter.cs]: Nitpick: I'd call .Single() since you've already established there's exactly one. Sometimes FirstOrDefault is used to mean "I haven't thought about which one I should pick" and so is sometimes a code smell.

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by AmadeusW** [comment]
> I'd call .Single() since you've already established there's exactly one
We're not `using System.Linq;` and so `Single()` is unavailable, so I changed it to `SeparatedSyntaxList.First()`

Strangely, that incorrect commit got a checkmark above (it doesn't build) and the one that builds has a failing test. Can we re-run the checks? And should I cherry-pick these commits into a single, final commit?

**Comment by davkean** [comment]
That failure doesn't look like yours, filed https://github.com/dotnet/roslyn/issues/6815.

retest prtest/win/dbg/unit32 please

**Comment by davkean** [comment]
test eta please

**Comment by davkean** [comment]
retest eta please

**Comment by davkean** [comment]
test prtest/win/dbg/eta please

**Comment by davkean** [comment]
okay to test

**Comment by davkean** [comment]
retest eta please

**Comment by davkean** [comment]
test this please

**Comment by davkean** [comment]
test eta please

**Comment by davkean** [comment]
Sorry for the spam, testing our builds on a community PR - we'll merge this in soon.

**Comment by davkean** [comment]
okay to test

**Comment by davkean** [comment]
test eta please

**Comment by mmitche** [comment]
@dotnet-bot test eta please

**Comment by mmitche** [comment]
@dotnet-bot test eta please

**Comment by jmarolf** [comment]
retest  prtest/mac/dbg/unit32 please

**Comment by davkean** [comment]
Merging this in, thanks for your contribution!
