### PR TITLE
Add Make Field Readonly analyzer/code fix

### LINKED ISSUE #10273: Add "Make readonly" analyzer and code fix
Filed on behalf of a customer from interviews

### PR DESCRIPTION
**Pull request by Hosch250**
VSO bug : https://devdiv.visualstudio.com/DevDiv/_workitems/edit/590185

Close #10273

## Specs

- Only works on private fields (more accessible fields should be replaced with properties anyway)
- Quick fix separates any fields declared in a single statement
- Fields are split for Fix One and declared in the same order as originally
- For Fix All, if all the fields in a declaration can be readonly, they are not split
- User-facing option allows user to enable/disable and set the severity for this analyzer

### CODE REVIEW

**Comment by JohanLarsson** [comment]
Add a test for when the field is assigned in a lamda defined in the ctor.
Pseudo code:

```C#
public class Foo
{
    private int a;
    public Foo()
    {
        this.E += (_, __) => this.a = 5;
    }

    public event EventHandler E;
}
```

**Comment by JohanLarsson** [comment]
Test for when another instance is assigned in te constructor.
Pseudo code:

```C#
public class Foo
{
    private int value;

    public Foo()
    {
        var foo = new Foo();
        foo.value = 5;
    }
}
```

Remember to check when the field is assigned using object intitailizer style also.

**Comment by Pilchie** [comment]
Tagging @dotnet/roslyn-ide for review.

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs [hunk 1]
```diff
@@ -0,0 +1,616 @@
...
+{
+    class MyClass
+    {
+        public int [|_foo|];
+    }
+}");
+        }
+
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsMakeFieldReadonly)]
+        public async Task FieldIsInternal()
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: any protected or protected-internal tests?

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs [hunk 2]
```diff
@@ -0,0 +1,616 @@
...
+    {
+        private int [|_foo|] = 0, _bar = 0;
+    }
+}",
+@"namespace ConsoleApplication1
+{
+    class MyClass
+    {
+        private int _bar = 0;
+        private readonly int _foo = 0;
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: i don't like this.  if both could be made readonly, the user is going to want the declarations to stay together.  only if one coudl not be made readonly should it be split.

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs [hunk 3]
```diff
@@ -0,0 +1,616 @@
...
+            _foo = 0;
+        }
+    }
+}");
+        }
+
+        public async Task PassedAsParameter()
+        {
+            await TestMissingInRegularAndScriptAsync(
+@"namespace ConsoleApplication1
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: all the namespaces can be removed from all tests.

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs [hunk 4]
```diff
@@ -0,0 +1,616 @@
...
+{
+    class MyClass
+    {
+        private int [|_foo|];
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: why can't this be readonly?

File: src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 5]
```diff
@@ -0,0 +1,59 @@
...
+    [DiagnosticAnalyzer(LanguageNames.CSharp)]
+    internal class CSharpMakeFieldReadonlyDiagnosticAnalyzer :
+        AbstractMakeFieldReadonlyDiagnosticAnalyzer<ConstructorDeclarationSyntax, LambdaExpressionSyntax>
+    {
+        protected override void InitializeWorker(AnalysisContext context)
+            => context.RegisterSyntaxNodeAction(AnalyzeType, SyntaxKind.ClassDeclaration, SyntaxKind.StructDeclaration);
+
+        internal override bool CanBeReadonly(SemanticModel model, SyntaxNode node)
+        {
+            if (node.Parent is AssignmentExpressionSyntax assignmentNode && assignmentNode.Left == node)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs]: We have a helper called IsWrittenTo that you can use for this purpose.  It should replace this entire method.

File: src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 6]
```diff
@@ -0,0 +1,59 @@
...
+                return false;
+            }
+
+            return true;
+        }
+
+        internal override bool IsMemberOfThisInstance(SyntaxNode node)
+        {
+            // if it is a qualified name, make sure it is `this.name`
+            if (node.Parent is MemberAccessExpressionSyntax memberAccess)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs]: Consider using IOperation and getting the IFieldReference operation for this, and validating it that way.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs [hunk 7]
```diff
@@ -0,0 +1,94 @@
...
+            {
+                var generator = SyntaxGenerator.GetGenerator(document);
+                editor.SetModifiers(fieldDeclaration, generator.GetModifiers(fieldDeclaration) | DeclarationModifiers.ReadOnly);
+            }
+            else
+            {
+                var model = await document.GetSemanticModelAsync().ConfigureAwait(false);
+                var symbol = (IFieldSymbol)model.GetDeclaredSymbol(declaration);
+
+                var generator = SyntaxGenerator.GetGenerator(document);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs]: generator available off of the 'editor' instance.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs [hunk 8]
```diff
@@ -0,0 +1,94 @@
...
+                var root = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
+                var diagnosticSpan = diagnostic.Location.SourceSpan;
+
+                var variableDeclarator = (TVariableDeclaratorSyntax)root.FindNode(diagnosticSpan);
+
+                MakeFieldReadonly(document, editor, root, variableDeclarator);
+            }
+        }
+
+        private async void MakeFieldReadonly(Document document, SyntaxEditor editor, SyntaxNode root, TVariableDeclaratorSyntax declaration)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs]: i don't think you use root.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs [hunk 9]
```diff
@@ -0,0 +1,94 @@
...
+                                                                generator.GetModifiers(fieldDeclaration) | DeclarationModifiers.ReadOnly,
+                                                                GetInitializerNode(declaration))
+                                                .WithAdditionalAnnotations(Formatter.Annotation);
+                
+                editor.InsertAfter(fieldDeclaration, newDeclaration);
+                editor.RemoveNode(declaration);
+            }
+        }
+
+        internal abstract SyntaxNode GetInitializerNode(TVariableDeclaratorSyntax declaration);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs]: internal?  can this be protected?

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs [hunk 10]
```diff
@@ -0,0 +1,94 @@
...
+        internal abstract int GetVariableDeclaratorCount(TFieldDeclarationSyntax declaration);
+
+        protected override Task FixAllAsync(
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs]: why did you need this override?

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 11]
```diff
@@ -0,0 +1,114 @@
...
+
+        public override bool OpenFileOnly(Workspace workspace) => false;
+
+        public override DiagnosticAnalyzerCategory GetAnalyzerCategory() => DiagnosticAnalyzerCategory.SemanticDocumentAnalysis;
+
+        internal void AnalyzeType(SyntaxNodeAnalysisContext context)
+        {
+            var typeSymbol = (ITypeSymbol)context.SemanticModel.GetDeclaredSymbol(context.Node);
+
+            var nonReadonlyFieldMembers = new HashSet<IFieldSymbol>();
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: pool this set.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 12]
```diff
@@ -0,0 +1,114 @@
...
+                    !symbol.IsImplicitlyDeclared)
+                {
+                    nonReadonlyFieldMembers.Add(symbol);
+                }
+            }
+
+            var membersCanBeReadonly = nonReadonlyFieldMembers;
+            foreach (var syntaxReference in typeSymbol.DeclaringSyntaxReferences)
+            {
+                var typeNode = syntaxReference.SyntaxTree.GetRoot().FindNode(syntaxReference.Span);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: use cancellation token for GEtRoot.

File: src/Workspaces/Core/Portable/WorkspacesResources.resx [hunk 13]
```diff
@@ -613,4 +613,7 @@
   <data name="Changing_document_property_is_not_supported" xml:space="preserve">
     <value>Changing document properties is not supported</value>
   </data>
+  <data name="Make_field_readonly" xml:space="preserve">
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/WorkspacesResources.resx]: Should be at feature level, not workspace leve.

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs (hunk 1 above)
Comment (Hosch250) [inline src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: No, I can add those if you like.

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs (hunk 2 above)
Comment (Hosch250) [inline src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: OK. I split them to make the fix simpler, and because I don't like fields being declared together anyway. It should be fairly trivial to move some of the code to a helper file and use it in the code fix too.

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs (hunk 4 above)
Comment (Hosch250) [inline src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: Huh, it can be. I must have missed that when I copy/pasted the test.

File: src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 6 above)
Comment (Hosch250) [inline src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs]: I can't use IOperation because it doesn't fire on field declarations without assignments.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs (hunk 9 above)
Comment (Hosch250) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs]: Yes.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs (hunk 10 above)
Comment (Hosch250) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs]: It is required by the base class.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 11 above)
Comment (Hosch250) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: Pool it?

File: src/Workspaces/Core/Portable/WorkspacesResources.resx (hunk 13 above)
Comment (Hosch250) [inline src/Workspaces/Core/Portable/WorkspacesResources.resx]: OK. Is there any particular reason the [Populate Switch message](https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/PopulateSwitch/PopulateSwitchDiagnosticAnalyzer.cs#L19) is at workspace level?

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs (hunk 4 above)
Comment (Hosch250) [inline src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: That one is missing the attribute. No wonder it didn't fail on me.

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs (hunk 1 above)
Comment (Hosch250) [inline src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: Fixed.

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs (hunk 4 above)
Comment (Hosch250) [inline src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: Fixed.

File: src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 5 above)
Comment (Hosch250) [inline src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs]: Fixed.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs (hunk 7 above)
Comment (Hosch250) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs]: Fixed.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs (hunk 8 above)
Comment (Hosch250) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs]: Fixed.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs (hunk 9 above)
Comment (Hosch250) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs]: Fixed.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 12 above)
Comment (Hosch250) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: Fixed.

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs (hunk 1 above)
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: @CyrusNajmabadi This would be a place where I would have used a `[Theory]` instead of `[Fact]`, in order to highlight that the only change in the individual test cases is the accessibility modifier.

@Hosch250 This is just a comment, no action required.

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs (hunk 2 above)
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: @CyrusNajmabadi I'm not worried. This is a relatively rare case. A follow-up issue could be added to make the Fix All handle the case differently where possible.

❗️ @Hosch250 The part I definitely don't like here is the reordering of the initializers. When splitting multiple initializers, the order should not change. This is required in order to preserve the semantics of the original statement during the change. Make sure to test all three cases:

```
private int _changed, _extra;
private int _extra, _changed;
private int _extra1, _changed, _extra2;
```

In the latter case the result should be this:

```csharp
private int _extra1;
private readonly int _changed;
private int _extra2;
```

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs [hunk 14]
```diff
@@ -0,0 +1,657 @@
...
+        void Foo()
+        {
+            Bar(ref _foo);
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: :bulb: Add a test where this is used only in the constructor (allowed).

:bulb: Add matching tests for passing an `out` variable.

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs (hunk 2 above)
Comment (Hosch250) [inline src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: OK. I'll change this.

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs (hunk 14 above)
Comment (Hosch250) [inline src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: OK. That *should* work because I do the ctor test first.

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs (hunk 2 above)
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: :bulb: Would be good to have tests for preserving comments when splitting.

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs (hunk 1 above)
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: So i'm amenable to theories *if* the following is true:

1. The theories are entirely self describing.  
2. The theory only changes one aspect of the test.

The thing i want to avoid (which i've seen in other tests in our codebase) is something like so:

```c#
public void Test()
{
      Test($".........{ subst1 } ........ { subst2 } .......... { subst3 } ......... { subst4 } .........");
}
```

When this happens, the test, and the permutated data become so decoupled as to great diminish the ability to understand what's happening.  You lose the forest for the trees as it were.  

If the test is really only permuting a single thing, i would have less issue with this sort of approach.

**Comment by CyrusNajmabadi** [comment]
This will need a user facing option if we're going to take this :)

Note: i'm not sure if this belongs in Roslyn, or would be better in the Roslyn-analyzers repo.  Thoughts @Pilchie ?

**Comment by Hosch250** [comment]
Don't bother checking my last changes--I broke things, then committed without compiling and accidentally synced instead of waiting until I'd fixed everything.

**Comment by Hosch250** [comment]
Would you like the user-facing option in this PR, or would you take it in another PR? I think I'll wait until this is finished before adding that either way.

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs (hunk 3 above)
Comment (Hosch250) [inline src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: Fixed.

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs (hunk 14 above)
Comment (Hosch250) [inline src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: Fixed.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 11 above)
Comment (Hosch250) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: @CyrusNajmabadi Would using a `List<T>` fix this? It doesn't have to be a `HashSet<T>`.

File: src/Workspaces/Core/Portable/WorkspacesResources.resx (hunk 13 above)
Comment (Hosch250) [inline src/Workspaces/Core/Portable/WorkspacesResources.resx]: Fixed.

**Comment by CyrusNajmabadi** [comment]
> Would you like the user-facing option in this PR,

It would need to be in this PR.  We only really want to add features if they can be considered ready for shipping to users.  Thanks!

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 11 above)
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: Check out PooledHashSet :)

Comment (Hosch250) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: Fixed.

**Comment by Hosch250** [comment]
@CyrusNajmabadi @sharwell Please check out my latest changes. I followed sharwell's suggestion about splitting the declarations for Fix One and keeping them in the same order, but I do not split them for Fix All if they can all be readonly. When any need to be split, I split them all just to be consistent.

**Comment by sharwell** [comment]
> It would need to be in this PR.

@Hosch250 Note that this would fall into a category where it may lie outside your area of expertise, and we wouldn't want to reject a feature that comes with tests and all just because of this. If this is a requirement for acceptance, then we would do one of the following to help you through it:

1. Find time to help you through the details in a timely manner, or
2. Create a feature branch in the repository so this could be incorporated without the user-facing option there, and finally merged into master after someone adds the option.

In the next week, we'll have a discussion about the scope of analyzers we want to see here as opposed to separately (e.g. dotnet/roslyn-analyzers, or some other location). For analyzers in those other repositories, the user-facing option is much simpler - it isn't supported so it's not required. :smile:

**Comment by Hosch250** [comment]
@sharwell This would not be outside of my experience--I did it for another feature, but didn't have time to follow it through to completion because college started. It is pretty much just copy/pasting code from other options.

**Comment by Hosch250** [comment]
@sharwell @CyrusNajmabadi The user-facing option is done.

**Comment by sharwell** [comment]
@Hosch250 Some users may not realize that adding `readonly` to a field whose type is a mutable value type (struct) can change semantics and possibly break the behavior of an application. Have we taken any steps in the analysis or the code fix (especially the Fix All) to help avoid quietly breaking the behavior in ways that a user is likely to not understand?

**Comment by Hosch250** [comment]
I'm not sure. I have 70-some unit tests checking that it is only fired when the field is not assigned to, except for the constructor, which doesn't allow assignments in lambdas. If you have a specific test in mind, I could see if it works.

**Comment by sharwell** [comment]
@Hosch250 Here's an example:

```csharp
internal class SomeType
{
    private MutableInt _value; // This field cannot be made readonly

    public SomeType()
    {
        _value = new MutableInt(0);
    }

    public void ThisMethodWritesValue()
    {
        _value.Increment();
    }
}

internal struct MutableInt
{
    public int Value;

    public MutableInt(int value)
    {
        Value = value;
    }

    public void Increment()
    {
        Value++;
    }
}
```

**Comment by Hosch250** [comment]
That field is allowed to become readonly in this. It seems it would compile with `readonly`, what would happen if was?

**Comment by sharwell** [comment]
@Hosch250 I edited the comment to give a usage case and concrete example of behavior change if `readonly` is added.

**Comment by sharwell** [comment]
@Hosch250 The scary part is the example is not hypothetical. I actually made this change in the immutable collections type during an experiment because it seemed totally safe. There I was saved by comprehensive unit tests but we can't assume that will happen for others.

**Comment by Hosch250** [comment]
Wow, I didn't know about this. Should I just not fire this on fields where the type is a `struct`?

**Comment by sharwell** [comment]
@Hosch250 Yeah, it's a sneaky one for sure! I think it was last year I learned of it myself. The reason it behaves this way is when you have a `readonly` value type, it copies the value to a local variable before calling instance methods on it. The two things this can negatively impact are:

1. Performance (if the value type is large, the copying could have an observable cost)
2. Correctness (as shown in the prior examples)

One really cool way to avoid breaking users while still allowing readonly to be added in *most* cases where it would be allowed is to only disable the analysis for a field whose type is a value type that contains an instance field which is not itself readonly. This information should be accessible even if the type is defined in metadata (some referenced assembly), but make sure to check all instance fields including private ones.

**Comment by Hosch250** [comment]
Yes, I think I can get that information from the `ISymbol`s. I'll work on it later.

**Comment by sharwell** [comment]
@Hosch250 When I looked into this analysis in the past, it did not occur to me that we could detect mutable value types so easily. At the time I was looking into things like hard-coded lists of types that where known to be immutable. This approach should be much more powerful. 👍

**Comment by CyrusNajmabadi** [comment]
I would not fire an a user defined struct.  But I would in any of the well known built in value types.

**Comment by sharwell** [comment]
@CyrusNajmabadi Is your concern more a performance concern or a semantics concern? The restriction I mentioned certainly covers the semantics concerns, but it leaves open the issue of "large" value types.

**Comment by Hosch250** [comment]
Oh, I just got @sharwell's suggestion done. It is really easy with `ITypeSymbol`.

**Comment by Hosch250** [comment]
@sharwell What about static fields? Should they be ignored as well, like `const`?

**Comment by CyrusNajmabadi** [comment]
> Is your concern more a performance concern or a semantics concern? 

The semantics concern.  The built-in value types are known to be immutable, and safe to the "readonly" optimization.

**Comment by Hosch250** [comment]
I'm open to doing this either way. Let me know when you decide.

**Comment by CyrusNajmabadi** [comment]
@Hosch250 

> It is really easy with ITypeSymbol.

Note: it's unclear if that's always the case due to things like reference-assemblies or other tools that strip out, or otherwise rewrite private data.  

Though, in practice this may be good enough.  

I'm a tad bit worried here since your fix comes with a 'fix all'.  It could *definitely* end up breaking someone if they did a fix-all and they were referencing a value type in a manner whereby we didn't know if the underlying fields were accurate or not.

**Comment by CyrusNajmabadi** [comment]
I would go the 'whitelist' approach for now.  Just have your whitelist function only check for built-in types for now :)

**Comment by Hosch250** [comment]
OK.

**Comment by sharwell** [comment]
> What about static fields? Should they be ignored as well, like `const`?

Yes, static fields do not affect this one way or the other.

> Note: it's unclear if that's always the case due to things like reference-assemblies or other tools that strip out, or otherwise rewrite private data.

Do ref assemblies strip layout details from value types?

**Comment by CyrusNajmabadi** [comment]
> Do ref assemblies strip layout details from value types?

The compiler team is currently discussing this.  The feeling is that they may leave some layout detail in. But replacing types and any other information that's not relevant.  So, for example, all reference-type fields may be typed to 'object'.  The idea is that you would be able to tell the size of the struct, but nothing else.  

I don't know if they've firmly landed on a final design here.

**Comment by Hosch250** [comment]
OK, I'm going with just checking `IsValueType` and `SpecialType != None`.

**Comment by Hosch250** [comment]
It appears I broke a couple serialization tests when I added the option. How would I go about fixing that?

**Comment by CyrusNajmabadi** [comment]
Ok.  I talked to @jcouv About this. Currently struct fields are not stripped, and for the IDE scenario, there is no intent to do so.  So i thin kyou could write the check that actually looks for writable instance fields on the struct.

**Comment by jcouv** [comment]
Yes, in IDE scenarios, the compilation is emitted with `EmitMetadataOnly` set to `true` (which strips out method bodies), but `IncludePrivateMembers` is also `true` so all the members are included. Those are called "metadata-only" assemblies. Private members/fields are preserved for IDE completion scenarios.
Once you strip private members, then you get a "ref assembly". Currently, ref assemblies are only used by MSBuild (not IDE) scenario, and they don't strip fields in structs (but this could change in the future).

If you have any concerns, make sure to add tests with clear comments so that we don't break your assumptions in the future.

https://github.com/dotnet/roslyn/blob/features/refout/docs/features/refout.md

**Comment by sharwell** [comment]
`ImmutableArray<T>` is a fascinating case. By [looking at the fields](https://github.com/dotnet/corefx/blob/6b3207a63b4240c9d19e1824b671c62ff703a9a4/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray_1.Minimal.cs#L51), it would be considered mutable. However, the mutable field is only used so it can provide an [`InterlockedExchange`](https://github.com/dotnet/corefx/blob/6b3207a63b4240c9d19e1824b671c62ff703a9a4/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableInterlocked.cs#L112) feature, and it doesn't change the fact that to external code it appears to be immutable.

**Comment by Hosch250** [comment]
OK, I'm switching back to @sharwell's suggestion. It made me catch a bug where it offered to make a `const` field `readonly`, too.

**Comment by sharwell** [comment]
@Hosch250 I've requested this subject be included in a meeting we're having late tomorrow, with the intent of not only letting you know the plan for including this feature (whether or not it's in this repository), but also providing better community guidance regarding which analyzers we would expect to go in which repository. 👍

**Comment by Hosch250** [comment]
Any more news here? How can I fix those broken serialization tests?

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
Retesting so i can see what the issues are.

**Comment by Hosch250** [comment]
@CyrusNajmabadi I posted the failing tests here: https://github.com/dotnet/roslyn/pull/19067#issuecomment-298187789

File: src/Workspaces/Core/Portable/Execution/AbstractOptionsSerializationService.cs [hunk 15]
```diff
@@ -250,6 +251,7 @@ protected OptionSet ReadOptionSetFrom(OptionSet options, string language, Object
             options = ReadOptionFrom(options, language, CodeStyleOptions.PreferNullPropagation, reader, cancellationToken);
             options = ReadOptionFrom(options, language, CodeStyleOptions.PreferObjectInitializer, reader, cancellationToken);
             options = ReadOptionFrom(options, language, CodeStyleOptions.PreferThrowExpression, reader, cancellationToken);
+            options = ReadOptionFrom(options, language, CodeStyleOptions.PreferReadonly, reader, cancellationToken);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Execution/AbstractOptionsSerializationService.cs]: this is the wrong order.  you are writing the option last, but reading it second to last.

**Comment by CyrusNajmabadi** [comment]
@Hosch250 I think i identified the problem.

File: src/Workspaces/Core/Portable/Execution/AbstractOptionsSerializationService.cs (hunk 15 above)
Comment (Hosch250) [inline src/Workspaces/Core/Portable/Execution/AbstractOptionsSerializationService.cs]: Ah, I didn't realize the order here was important.

**Comment by Hosch250** [comment]
Thanks for the help. I start work on Wednesday, so I will only be available for a limited time on weekends after that until I make the shift from being a student to being an employee.

**Comment by Hosch250** [comment]
Shoot. I messed up merging the conflicts. I'll fix tomorrow.

**Comment by Hosch250** [comment]
Retest windows_release_unit32_prtest please.

**Comment by Hosch250** [comment]
Retest windows_debug_unit32_prtest please.

**Comment by Hosch250** [comment]
Retest windows_determinism_prtest please.

**Comment by Hosch250** [comment]
:( I guess I resolved the conflicts wrong. I'll roll it back and take another look later.

**Comment by Hosch250** [comment]
Bah. Work on it later, unless someone else kindly does it for me.

**Comment by sharwell** [comment]
@Hosch250 I rebased this onto **dev15.7.x**. During the rebase, I verified that each commit *compiled* successfully, but for any test fixes I'll wait and apply those as new commits at the end.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 16]
```diff
@@ -0,0 +1,174 @@
...
+            var typeSymbol = (ITypeSymbol)context.SemanticModel.GetDeclaredSymbol(context.Node);
+
+            var nonReadonlyFieldMembers = PooledHashSet<IFieldSymbol>.GetInstance();
+            foreach (var item in typeSymbol.GetMembers())
+            {
+                if (item is IFieldSymbol symbol &&
+                    symbol.DeclaredAccessibility == Accessibility.Private &&
+                    !symbol.IsReadOnly &&
+                    !symbol.IsConst &&
+                    !symbol.IsImplicitlyDeclared &&
```
Comment (sharwell) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: :exclamation: this needs to filter to only include fields in the part declared by `context.Node`. This is the underlying cause of some formatting bugs we observed and I'm already in the process of preparing the fix with tests.

Comment (sharwell) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: ➡️ Fixed in 1491c33

**Comment by Hosch250** [comment]
Thanks so much, Mr. Harwell. This was approved to go out with VS 15.7 then?

**Comment by jinujoseph** [comment]
@CyrusNajmabadi  you want to re-review this ?

**Comment by sharwell** [comment]
💭 I'm thinking this may need to be modified to be a semantic model or symbol analyzer for performance reasons, but it shouldn't be a particularly challenging change. Now that the behavior is correct I'm waiting to hear back on reviews before making other changes.

> Thanks so much, Mr. Harwell. This was approved to go out with VS 15.7 then?

It hasn't been formally approved, but I am advocating for it in hopes of reaching that goal.

**Comment by CyrusNajmabadi** [comment]
Yes.  i would like to rereview.  I can get to it by EOD.  After that, feel free to just go ahead with it.

**Comment by sharwell** [comment]
@Hosch250 If anything comes up during review that needs to be changed, I'm planning to go ahead and make the changes to keep this moving forward. If at any point you decide you want to take over, let me know to stop with that approach. 😄

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs [hunk 17]
```diff
@@ -0,0 +1,748 @@
...
+    public class MakeFieldReadonlyTests : AbstractCSharpDiagnosticProviderBasedUserDiagnosticTest
+    {
+        internal override (DiagnosticAnalyzer, CodeFixProvider) CreateDiagnosticProviderAndFixer(Workspace workspace)
+            => (new CSharpMakeFieldReadonlyDiagnosticAnalyzer(), new CSharpMakeFieldReadonlyCodeFixProvider());
+
+        [Theory, Trait(Traits.Feature, Traits.Features.CodeActionsMakeFieldReadonly)]
+        [InlineData("public")]
+        [InlineData("internal")]
+        [InlineData("protected")]
+        [InlineData("protected internal")]
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: add test for "private protected"?

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs [hunk 18]
```diff
@@ -0,0 +1,748 @@
...
+        {
+            await TestInRegularAndScriptAsync(
+@"class MyClass
+{
+    private int [|_goo|] = 0, _bar = 0;
+}",
+@"class MyClass
+{
+    private readonly int _goo = 0;
+    private int _bar = 0;
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: this seems unfortunate.  my preference would be to have at least two code actions.  one which splits things (and add 'readonly') to the one item.  The other which adds readonly to the whole declaration if applicable.  i.e. if all hte fields can become readonly, that should be something you can do without having to split hte declaration.

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: Note: this is distinct from having "fix all".  Fix-all will scope to a file/project/solution.  i think it would be worthwhile to have a code action to just fix the fields in a single declaration (if possible).

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs [hunk 19]
```diff
@@ -0,0 +1,748 @@
...
+
+        private static readonly Func<int, bool> _test4 = x =>
+        {
+            return x != 0;
+        };
+    }
+
+    partial struct MyClass { }");
+        }
+    }
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: i'd like a test where the field is written to from inside a nested type inside the class.  i.e. something like this:

```
class C
{
    private int i;

    class D : C
    {
        public D()
        {
            i++;
        }
    }
}
```

This should not be allowed to change even though 'i' is chnaged in a constructor.

File: src/EditorFeatures/VisualBasicTest/MakeFieldReadonly/MakeFieldReadonlyTests.vb [hunk 20]
```diff
@@ -0,0 +1,532 @@
...
+Namespace Microsoft.CodeAnalysis.Editor.VisualBasic.UnitTests.MakeFieldReadonly
+    Public Class MakeFieldReadonlyTests
+        Inherits AbstractVisualBasicDiagnosticProviderBasedUserDiagnosticTest
+
+        Friend Overrides Function CreateDiagnosticProviderAndFixer(workspace As Workspace) As (DiagnosticAnalyzer, CodeFixProvider)
+            Return (New VisualBasicMakeFieldReadonlyDiagnosticAnalyzer(),
+                New VisualBasicMakeFieldReadonlyCodeFixProvider())
+        End Function
+
+        <Theory, Trait(Traits.Feature, Traits.Features.CodeActionsMakeFieldReadonly)>
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/VisualBasicTest/MakeFieldReadonly/MakeFieldReadonlyTests.vb]: i haven't looked deeply at this file.  But i wanted to check if you have tests for all the interesting vb field forms.  i.e. they can do things like:

```vb
    Dim x As Integer, y As String
```

or

```vb
Dim x, y As Integer, z, w As String
```

or:

```vb
    Dim x, y() As Integer, z, w As String
```
(note the parens after y).

File: src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 21]
```diff
@@ -0,0 +1,42 @@
...
+namespace Microsoft.CodeAnalysis.CSharp.MakeFieldReadonly
+{
+    [DiagnosticAnalyzer(LanguageNames.CSharp)]
+    internal class CSharpMakeFieldReadonlyDiagnosticAnalyzer :
+        AbstractMakeFieldReadonlyDiagnosticAnalyzer<IdentifierNameSyntax, ConstructorDeclarationSyntax>
+    {
+        protected override void InitializeWorker(AnalysisContext context)
+            => context.RegisterSyntaxNodeAction(AnalyzeType, SyntaxKind.ClassDeclaration, SyntaxKind.StructDeclaration);
+
+        protected override ISyntaxFactsService GetSyntaxFactsService() =>
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs]: please place => on the next line (indented).

File: src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 22]
```diff
@@ -0,0 +1,42 @@
...
+        protected override bool IsMemberOfThisInstance(SyntaxNode node)
+        {
+            // if it is a qualified name, make sure it is `this.name`
+            if (node.Parent is MemberAccessExpressionSyntax memberAccess)
+            {
+                return memberAccess.Expression is ThisExpressionSyntax;
+            }
+
+            // make sure it isn't in an object initializer
+            if (node.Parent.Parent is InitializerExpressionSyntax)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs]: what if you have:

```c#
class C {
     int i;

     public C() { new D { X = i };
}
```

(or someting like that).  basically, what happens if it's on the right hand side and in a construct such that .parent.parent is the InitializeExpression?
}

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs [hunk 23]
```diff
@@ -0,0 +1,111 @@
...
+using Microsoft.CodeAnalysis.CodeFixes;
+using Microsoft.CodeAnalysis.Diagnostics;
+using Microsoft.CodeAnalysis.Editing;
+using Microsoft.CodeAnalysis.Formatting;
+using Roslyn.Utilities;
+
+namespace Microsoft.CodeAnalysis.MakeFieldReadonly
+{
+    internal abstract class AbstractMakeFieldReadonlyCodeFixProvider
+        <TSymbolSyntax, TFieldDeclarationSyntax>
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs]: please put typeparameters on previous line.  (wrapping is ok if they're really long).  that doesn't apply here.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs [hunk 24]
```diff
@@ -0,0 +1,111 @@
...
+                    var model = await document.GetSemanticModelAsync().ConfigureAwait(false);
+                    var generator = editor.Generator;
+                    
+                    foreach (var declarator in declarationDeclarators.Reverse())
+                    {
+                        var symbol = (IFieldSymbol)model.GetDeclaredSymbol(declarator);
+                        var modifiers = generator.GetModifiers(fieldDeclarators.Key);
+
+                        var newDeclaration = generator.FieldDeclaration(symbol.Name,
+                                                                        generator.TypeExpression(symbol.Type),
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs]: i'm the fence if we should go back to the symbol here.  technically you can figure out hte name from the declarator.  And you can just use the same type node that was on the original field declaration right?

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs [hunk 25]
```diff
@@ -0,0 +1,111 @@
...
+                                                                        fieldDeclarators.Contains(declarator)
+                                                                            ? modifiers | DeclarationModifiers.ReadOnly
+                                                                            : modifiers,
+                                                                        GetInitializerNode(declarator))
+                                                      .WithAdditionalAnnotations(Formatter.Annotation);
+
+                        editor.InsertAfter(fieldDeclarators.Key, newDeclaration);
+                    }
+
+                    editor.RemoveNode(fieldDeclarators.Key);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs]: do we have fix-all tests that remove multiple declarators from a declaration (but not all).  I just want to make sure that works.  i.e. have 3 variable decls in the field, then have 2 of them pulled out while one remains.

(also, all the crazy VB cases).

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 26]
```diff
@@ -0,0 +1,194 @@
...
+{
+    internal abstract class AbstractMakeFieldReadonlyDiagnosticAnalyzer<TIdentifierNameSyntax, TConstructorDeclarationSyntax>
+        : AbstractCodeStyleDiagnosticAnalyzer
+        where TIdentifierNameSyntax : SyntaxNode
+        where TConstructorDeclarationSyntax : SyntaxNode
+    {
+        private static readonly LocalizableString s_localizableTitle = new LocalizableResourceString(nameof(FeaturesResources.Add_readonly_modifier), FeaturesResources.ResourceManager, typeof(FeaturesResources));
+        private static readonly LocalizableString s_localizableMessage = new LocalizableResourceString(nameof(FeaturesResources.Make_field_readonly), WorkspacesResources.ResourceManager, typeof(WorkspacesResources));
+
+        public AbstractMakeFieldReadonlyDiagnosticAnalyzer()
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: make protectec.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 27]
```diff
@@ -0,0 +1,194 @@
...
+
+namespace Microsoft.CodeAnalysis.MakeFieldReadonly
+{
+    internal abstract class AbstractMakeFieldReadonlyDiagnosticAnalyzer<TIdentifierNameSyntax, TConstructorDeclarationSyntax>
+        : AbstractCodeStyleDiagnosticAnalyzer
+        where TIdentifierNameSyntax : SyntaxNode
+        where TConstructorDeclarationSyntax : SyntaxNode
+    {
+        private static readonly LocalizableString s_localizableTitle = new LocalizableResourceString(nameof(FeaturesResources.Add_readonly_modifier), FeaturesResources.ResourceManager, typeof(FeaturesResources));
+        private static readonly LocalizableString s_localizableMessage = new LocalizableResourceString(nameof(FeaturesResources.Make_field_readonly), WorkspacesResources.ResourceManager, typeof(WorkspacesResources));
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: in general, we inline these into the constructor as no one else should have to refernece these.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 28]
```diff
@@ -0,0 +1,194 @@
...
+            : base(IDEDiagnosticIds.MakeFieldReadonlyDiagnosticId,
+                   s_localizableTitle, s_localizableMessage)
+        {
+        }
+
+        public override bool OpenFileOnly(Workspace workspace) => false;
+
+        public override DiagnosticAnalyzerCategory GetAnalyzerCategory() => DiagnosticAnalyzerCategory.SemanticDocumentAnalysis;
+
+        internal void AnalyzeType(SyntaxNodeAnalysisContext context)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: why internal?

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 29]
```diff
@@ -0,0 +1,194 @@
...
+                    {
+                        nonReadonlyFieldMembers.Add(symbol);
+                    }
+                }
+            }
+
+            var syntaxFactsService = GetSyntaxFactsService();
+            foreach (var syntaxReference in typeSymbol.DeclaringSyntaxReferences)
+            {
+                var typeNode = syntaxReference.SyntaxTree.GetRoot(context.CancellationToken).FindNode(syntaxReference.Span);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: isn't this just syntaxReference.GetSyntax(cancellationToken)?

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 30]
```diff
@@ -0,0 +1,194 @@
...
+                    continue;
+                }
+
+                var symbol = model.GetSymbolInfo(descendant).Symbol as IFieldSymbol;
+                if (symbol == null || !unassignedSymbols.Contains(symbol))
+                {
+                    continue;
+                }
+
+                if (!IsMemberOfThisInstance(descendant))
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: i don't think this is right.  you might be in a nested type.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 31]
```diff
@@ -0,0 +1,194 @@
...
+                    }
+
+                    if (isInAnonymousOrLocalFunction)
+                    {
+                        unassignedSymbols.Remove(symbol);
+                    }
+                    else
+                    {
+                        var ctorSymbol = model.GetDeclaredSymbol(ctorNode);
+                        if (!ctorSymbol.ContainingType.Equals(symbol.ContainingType))
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: ah, you check the containing type here.  ok :)

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 32]
```diff
@@ -0,0 +1,194 @@
...
+            }
+
+            foreach (var member in type.GetMembers())
+            {
+                if (member is IFieldSymbol fieldSymbol &&
+                    !(fieldSymbol.IsConst || fieldSymbol.IsReadOnly || fieldSymbol.IsStatic))
+                {
+                    return true;
+                }
+            }
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: there's a major problem/concern i have here.  This works if we can accurately get the members of hte struct.  But what does this mean for reference assemblies (where fields have been stripped out)?

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 33]
```diff
@@ -0,0 +1,194 @@
...
+
+            return false;
+        }
+
+        protected abstract ISyntaxFactsService GetSyntaxFactsService();
+        protected abstract bool IsWrittenTo(TIdentifierNameSyntax node, SemanticModel model, CancellationToken cancellationToken);
+        protected abstract bool IsMemberOfThisInstance(SyntaxNode node);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: minor nit:  in general we place hte abstracts below the constructor and above the concrete methods.

File: src/Workspaces/Core/Portable/CodeStyle/CodeStyleOptions.cs [hunk 34]
```diff
@@ -184,6 +184,14 @@ public class CodeStyleOptions
                     new EditorConfigStorageLocation<CodeStyleOption<AccessibilityModifiersRequired>>("dotnet_style_require_accessibility_modifiers", s => ParseAccessibilityModifiersRequired(s)),
                     new RoamingProfileStorageLocation("TextEditor.%LANGUAGE%.Specific.RequireAccessibilityModifiers")});
 
+        internal static readonly PerLanguageOption<CodeStyleOption<bool>> PreferReadonly = new PerLanguageOption<CodeStyleOption<bool>>(
+            nameof(CodeStyleOptions),
+            nameof(PreferReadonly),
+            defaultValue: TrueWithSuggestionEnforcement,
+            storageLocations: new OptionStorageLocation[]{
+                EditorConfigStorageLocation.ForBoolCodeStyleOption("dotnet_style_readonly_field"),
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeStyle/CodeStyleOptions.cs]: note sure about this name.  @sharwell @kuhlenh ?

File: src/Workspaces/Core/Portable/CodeStyle/CodeStyleOptions.cs [hunk 35]
```diff
@@ -184,6 +184,14 @@ public class CodeStyleOptions
                     new EditorConfigStorageLocation<CodeStyleOption<AccessibilityModifiersRequired>>("dotnet_style_require_accessibility_modifiers", s => ParseAccessibilityModifiersRequired(s)),
                     new RoamingProfileStorageLocation("TextEditor.%LANGUAGE%.Specific.RequireAccessibilityModifiers")});
 
+        internal static readonly PerLanguageOption<CodeStyleOption<bool>> PreferReadonly = new PerLanguageOption<CodeStyleOption<bool>>(
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeStyle/CodeStyleOptions.cs]: i can imagine this epxanding to multiple values in the future. as such, we may want to make it an enum value instead of a bool.

File: src/Workspaces/Core/Portable/LanguageServices/SyntaxFactsService/ISyntaxFactsService.cs [hunk 36]
```diff
@@ -250,6 +250,8 @@ internal interface ISyntaxFactsService : ILanguageService
 
         bool IsAnonymousFunction(SyntaxNode n);
 
+        bool IsAnonymousOrLocalFunction(SyntaxNode n);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/LanguageServices/SyntaxFactsService/ISyntaxFactsService.cs]: this is not generally what we put in ISyntaxFacts.  We put the low level primitives, which can be implemented by both langauges.  As there is already IsAnonymousFunction here, you should only add IsLocalFunction.

Then, your feature can make it's own IsAnonymousOrLocalFunction(ISyntaxFacts) function.

**Comment by CyrusNajmabadi** [comment]
Overall looks good.  Have a few questions i'd like clarity on.  And i would like extra tests for some crazy cases.

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs (hunk 18 above)
Comment (sharwell) [reply src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: :memo: I believe this one can be a follow-up change.

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs (hunk 19 above)
Comment (sharwell) [reply src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: ➡️ This was implemented with tests in f19cceb66030ae14c9f11850b08d3ac9694059bd

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 32 above)
Comment (sharwell) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: ➡️ All fields are kept for `struct` types. https://github.com/dotnet/roslyn/blob/master/docs/features/refout.md#definition-of-ref-assemblies

Comment (sharwell) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: I made a comment in #19994 documenting our reliance on this behavior.

File: src/Workspaces/Core/Portable/CodeStyle/CodeStyleOptions.cs (hunk 35 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/CodeStyle/CodeStyleOptions.cs]: What would the values now be?

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 30 above)
Comment (sharwell) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: ➡️ Covered by the next comment.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 31 above)
Comment (sharwell) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: ➡️ No action required.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: i'd still like a test.  it's an easy case to miss, and it would be helpful in case any of this code gets refactored :)

File: src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 22 above)
Comment (sharwell) [reply src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs]: ➡️ The concern here is *writing* to `C.i` for an instance which is not `this`:

```csharp
class C {
  int i;

  C() {
    // C.i is written to, but this.i is not
    _ = new C { i = 3 };
  }
}
```

As far as I can tell, the situation you are concerned about can only happen if `i` is *read*.

File: src/Workspaces/Core/Portable/LanguageServices/SyntaxFactsService/ISyntaxFactsService.cs (hunk 36 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/LanguageServices/SyntaxFactsService/ISyntaxFactsService.cs]: ➡️ Fixed in commit 38db528

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 33 above)
Comment (sharwell) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: ➡️ Fixed in commit 38db528

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 28 above)
Comment (sharwell) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: ➡️ `protected` in commit 38db528

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 27 above)
Comment (sharwell) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: ➡️ Fixed in commit 38db528

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 26 above)
Comment (sharwell) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: ➡️ Fixed in commit 38db528

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs (hunk 25 above)
Comment (sharwell) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs]: ➡️ Added in commit 38db528 (One such VB case already exists, others are treated separately)

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs (hunk 23 above)
Comment (sharwell) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyCodeFixProvider.cs]: ➡️ Fixed in commit 38db528

File: src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 21 above)
Comment (sharwell) [reply src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs]: ➡️ Added in commit 38db528

File: src/EditorFeatures/VisualBasicTest/MakeFieldReadonly/MakeFieldReadonlyTests.vb (hunk 20 above)
Comment (sharwell) [reply src/EditorFeatures/VisualBasicTest/MakeFieldReadonly/MakeFieldReadonlyTests.vb]: ➡️ Added in commit 38db528

File: src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs (hunk 17 above)
Comment (sharwell) [reply src/EditorFeatures/CSharpTest/MakeFieldReadonly/MakeFieldReadonlyTests.cs]: ➡️ Added in commit 38db528

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 29 above)
Comment (sharwell) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: :memo: I tried to make this change, but it broke a bunch of the VB tests. I have no idea why.

**Comment by Hosch250** [comment]
@sharwell Feel free to take this over. I don't really have time to maintain this anymore, but I'm happy to have provided the base work to include this.

**Comment by sharwell** [comment]
@dotnet-bot retest this please

**Comment by sharwell** [comment]
@jinujoseph this needs a second review but is otherwise ready

File: src/EditorFeatures/VisualBasicTest/MakeFieldReadonly/MakeFieldReadonlyTests.vb [hunk 37]
```diff
@@ -0,0 +1,670 @@
...
+    Private z As String
+    Private ReadOnly w As String
+End Class")
+        End Function
+
+        <Fact, Trait(Traits.Feature, Traits.Features.CodeActionsMakeFieldReadonly)>
+        Public Async Function MultipleFieldsAssignedInline_VBSpecialForms07() As Task
+            Await TestInRegularAndScriptAsync(
+"Class C
+    Dim [|x|], y() As Integer, z(), w As String
```
Comment (mavasani) [inline src/EditorFeatures/VisualBasicTest/MakeFieldReadonly/MakeFieldReadonlyTests.vb]: Do we have a test for `As New` applicable to multiple declarators? For e.g., `Dim [|x|], y As New Integer()`, where `x` is candidate to become readonly should change to:
```
Dim ReadOnly x As New Integer()
Dim y As New Integer()
```

File: src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 38]
```diff
@@ -0,0 +1,42 @@
...
+        protected override void InitializeWorker(AnalysisContext context)
+            => context.RegisterSyntaxNodeAction(AnalyzeType, SyntaxKind.ClassDeclaration, SyntaxKind.StructDeclaration);
+
+        protected override ISyntaxFactsService GetSyntaxFactsService()
+            => CSharpSyntaxFactsService.Instance;
+
+        protected override bool IsWrittenTo(IdentifierNameSyntax name, SemanticModel model, CancellationToken cancellationToken)
+            => name.IsWrittenTo();
+
+        protected override bool IsMemberOfThisInstance(SyntaxNode node)
```
Comment (mavasani) [inline src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs]: This is would not needed to be language specific if written as an IOperation analyzer.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 39]
```diff
@@ -0,0 +1,193 @@
...
+    {
+        protected AbstractMakeFieldReadonlyDiagnosticAnalyzer()
+            : base(
+                IDEDiagnosticIds.MakeFieldReadonlyDiagnosticId,
+                new LocalizableResourceString(nameof(FeaturesResources.Add_readonly_modifier), FeaturesResources.ResourceManager, typeof(FeaturesResources)),
+                new LocalizableResourceString(nameof(FeaturesResources.Make_field_readonly), WorkspacesResources.ResourceManager, typeof(WorkspacesResources)))
+        {
+        }
+
+        protected abstract ISyntaxFactsService GetSyntaxFactsService();
```
Comment (mavasani) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: Analyzer using `ISyntaxFactsService` seems extremely fishy, and will likely cause issues when we try to remove the `IBuildInAnalyzer` hack that exposes `Workspace` to the IDE analyzers.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 40]
```diff
@@ -0,0 +1,193 @@
...
+                    continue;
+                }
+
+                var symbol = model.GetSymbolInfo(descendant).Symbol as IFieldSymbol;
+                if (symbol == null || !unassignedSymbols.Contains(symbol))
+                {
+                    continue;
+                }
+
+                if (!IsMemberOfThisInstance(descendant))
```
Comment (mavasani) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: In IOperation world this check is simple kind check: `IFieldReferenceOperation.Instance?.Kind == OperationKind.InstanceReference`

**Comment by sharwell** [comment]
> This should be written as an IOperation analyzer to avoid (a) language specific implementations and (b) IBuildInAnalyzer hack to get to workspace services.

This is out of scope for the initial implementation.

**Comment by mavasani** [comment]
> I am very much hoping this is out of scope for the initial implementation.

Why? It is few hours of work mostly involving deleting lot of redundant and hacky code using workspace.

**Comment by mavasani** [comment]
Note that figuring out writes to property symbols is still non trivial in IOperation world, but it should be easy to check if an IFieldReferenceOperation is in context of a write or not.

File: src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 38 above)
Comment (sharwell) [reply src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs]: ➡️ Resolved by filing #25652

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 39 above)
Comment (sharwell) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: ➡️ Resolved by filing #25652

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 40 above)
Comment (sharwell) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: ➡️ Resolved by filing #25652

File: src/EditorFeatures/VisualBasicTest/MakeFieldReadonly/MakeFieldReadonlyTests.vb (hunk 37 above)
Comment (sharwell) [reply src/EditorFeatures/VisualBasicTest/MakeFieldReadonly/MakeFieldReadonlyTests.vb]: Not yet, I'll get some added.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 39 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: Tons of analyzers use ISyntaxFactsService.    I'm not sure why this is a problem.

>and will likely cause issues when we try to remove the IBuildInAnalyzer hack that exposes Workspace to the IDE analyzers.

We don't need the workspace to get at these services.  They're effectively singletons.

Comment (mavasani) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: > Tons of analyzers use ISyntaxFactsService

Unless the analyzer is doing extremely workspace specific analysis, it should not be using any workspace services, otherwise we can never port this analyzer to run in command line builds.

**Comment by jinujoseph** [comment]
test windows_debug_es_unit32_prtest

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 41]
```diff
@@ -0,0 +1,193 @@
...
+
+                    if (isInCurrentNode)
+                    {
+                        nonReadonlyFieldMembers.Add(symbol);
+                    }
+                }
+            }
+
+            var syntaxFactsService = GetSyntaxFactsService();
+            foreach (var syntaxReference in typeSymbol.DeclaringSyntaxReferences)
```
Comment (mavasani) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: >typeSymbol.DeclaringSyntaxReferences [](start = 44, length = 36)

Note that compiler does not cache declaring syntax references on the symbol, and this will allocate an array every time. Consider adding code prior to this loop to check for empty `nonReadonlyFieldMembers` and bail out.

Comment (mavasani) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: >foreach (var syntaxReference in typeSymbol.DeclaringSyntaxReferences) [](start = 12, length = 69)

This seems super convoluted and an extremely expensive n*n algorithm with tons of unnecessary allocations. For a type with `n` partial declarations and `m` field symbols, we will execute this loop `n` times (once for each declaration), allocate this syntax references array `n` times (potentially for every named type in the compilation). We also allocate n*n semantic model instances (compilation does not cache semantic model for trees), and invoke very similar semantic queries on different instances of these semantic models (each adds to binding cost).

An IOperation based implementation will analyze every field reference and type declaration exactly once, without any of these performance overheads. I think it is worth spending half a day converting this to IOperation analyzer then shipping an implementation with known performance problems.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 39 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: > Unless the analyzer is doing extremely workspace specific analysis, it should not be using any workspace services

ISyntaxFactsService is not an IWorkspaceService it's an ILanguageService.  It exists so we can abstract away differences between the languages.

We use lots of ILanguageServices in analyzers because, unsurprisingly, we have written lots of glue code that works across languages, and we want to be able to share them in analyzers.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: Note that we should have no problem using ISyntaxFactsService from the command line.  It's literally an aggregation of static helpers, wrapped into an interface so it can be called uniformly across VB and C#.  It's the moral equivalent of SyntaxFacts+SyntaxFactory, just usable from both languages.  It should be 100% fine to use now, and even if we move these to be command line analyzers.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 42]
```diff
@@ -0,0 +1,193 @@
...
+                return;
+            }
+
+            var option = optionSet.GetOption(CodeStyleOptions.PreferReadonly, context.Node.Language);
+            if (!option.Value)
+            {
+                return;
+            }
+
+            var typeSymbol = (ITypeSymbol)context.SemanticModel.GetDeclaredSymbol(context.Node);
```
Comment (mavasani) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: >var typeSymbol = (ITypeSymbol)context.SemanticModel.GetDeclaredSymbol(context.Node); [](start = 12, length = 84)

We should write a meta-analyzer that flags this! We should never register a syntax node analyzer that goes back to the declared symbol and then traverses all the declaring references. That is a guaranteed performance issue and there is invariably a better, performant way to write such analysis.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 41 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: >  allocate this syntax references array n times

Can you clarify that bit.  It seems like this is only being allocated once per type.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 39 above)
Comment (mavasani) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: Would it be worthwhile to ship these publically as analyzer utilities? I recall we have talked about this in the past when we started working on roslyn-analyzers, and we took the easier route of just copy-paste useful helpers/extension methods from workspaces layer to the analyzers repo.

---
In reply to: [176218519](https://github.com/dotnet/roslyn/pull/19067#discussion_r176218519) [](ancestors = 176218519)

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 41 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: Actually, i think i see what you're saying.  because thsi is a syntax-node algorithm, we'll both hit all the declaration nodes for a partial type.  And then for each part, we'll then go examine all the other parts.  Yes, that seems wonky.  It seems like this could either be made into an IOperation analyzer (which likely wouldn't be that hard), or it could be a symbol analyzer that registers for INamedTypeSymbols.

Comment (mavasani) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: > Can you clarify that bit.  It seems like this is only being allocated once per type.  

The analyzer is registering a syntax node action, not a symbol action. So there will be `n` callbacks, once per each partial declaration of the containing type and each callback can potentially execute this loop.

---
In reply to: [176219860](https://github.com/dotnet/roslyn/pull/19067#discussion_r176219860) [](ancestors = 176219860)

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 39 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: > Would it be worthwhile to ship these publically as analyzer utilities? 

Sure.  As long as that doesn't negatively impede teh IDE's ability to make changes easily, and as long as it doesn't lock the IDE into having to support a public API.  These APIs underpin tons of our features, and we need to be able to efficiently and effectively make updates here.  If that isn't impacted, then i see no problem making this available to others.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 41 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: Yup.  Got it.  That does seem wonky.

File: src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 38 above)
Comment (Hosch250) [reply src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs]: I tried to write this as an `IOperation` analzyer before. It was a lot cleaner, but failed because the given API's didn't provide something about property setters, I believe. It should be in some of the previous review comments, but some of the discussion probably happened in gitter.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 40 above)
Comment (Hosch250) [reply src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: See comment about `IOperation` above. Maybe the API has changed now; it would make most of the logic a lot simpler.

File: src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 38 above)
Comment (mavasani) [reply src/Features/CSharp/Portable/MakeFieldReadonly/CSharpMakeFieldReadonlyDiagnosticAnalyzer.cs]: Yes, detecting property writes is still not trivial, and @333fred had a tracking issue to improve the IOperation APIs for it. However, given this analyzer only deals with fields, we should consider making it an IOperation analyzer, field writes should be easier to detect.

---
In reply to: [176229105](https://github.com/dotnet/roslyn/pull/19067#discussion_r176229105) [](ancestors = 176229105)

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 43]
```diff
@@ -0,0 +1,190 @@
...
+                        !symbol.IsImplicitlyDeclared &&
+                        symbol.Locations.Length == 1 &&
+                        !IsMutableValueType(symbol.Type);
+
+                // Stores the state for fields:
+                //  'isCandidate' : Indicates whether the field is a candidate to be made readonly based on it's declaration and options.
+                //  'written'     : Indicates if there are any writes to the field outside the constructor and field initializer.
+                var fieldStateMap = new ConcurrentDictionary<IFieldSymbol, (bool isCandidate, bool written)>();
+
+                void OnFieldWrite(IFieldSymbol field)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: can you name local functions "camelCase"?  Also, in the IDE we generally like to put hte local functions *after* the last return statement, with a "// local functions" comment on them.  It makes it really easy to read the normal function logic without having to jump over large nested functions in between.

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 44]
```diff
@@ -0,0 +1,190 @@
...
+
+                (bool isCandidate, bool written) TryGetOrComputeIsCandidateField(IFieldSymbol fieldSymbol, AnalyzerOptions options, CancellationToken cancellationToken)
+                {
+                    return fieldStateMap.GetOrAdd(fieldSymbol, valueFactory: ComputeIsCandidate);
+
+                    (bool isCandidate, bool written) ComputeIsCandidate(IFieldSymbol field)
+                    {
+                        if (!IsCandidateField(field))
+                        {
+                            return (false, false);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: return default;?

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 45]
```diff
@@ -0,0 +1,190 @@
...
+                        }
+
+                        var option = GetCodeStyleOption(field, options, cancellationToken);
+                        if (option == null || !option.Value)
+                        {
+                            return (false, false);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: return default;?

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 46]
```diff
@@ -0,0 +1,190 @@
...
+                        }
+
+                        return (isCandidate: true, written: false);
+                    }
+                }
+
+                compilationStartContext.RegisterSymbolAction(symbolContext =>
+                {
+                    var _ = TryGetOrComputeIsCandidateField((IFieldSymbol)symbolContext.Symbol, symbolContext.Options, symbolContext.CancellationToken);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: why the variable?

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 47]
```diff
@@ -0,0 +1,190 @@
...
+
+                compilationStartContext.RegisterOperationBlockStartAction(operationBlockStartContext =>
+                {
+                    var isConstructor = operationBlockStartContext.OwningSymbol.IsConstructor();
+                    var isStaticConstructor = operationBlockStartContext.OwningSymbol.IsStaticConstructor();
+
+                    operationBlockStartContext.RegisterOperationAction(operationContext =>
+                    {
+                        var fieldReference = (IFieldReferenceOperation)operationContext.Operation;
+                        IFieldSymbol field = fieldReference.Field;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: var please.

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 48]
```diff
@@ -0,0 +1,190 @@
...
+
+                        (bool isCandidate, bool written) fieldState = TryGetOrComputeIsCandidateField(field, operationContext.Options, operationContext.CancellationToken);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: deconstruct:  ```var (isCandidate, written) = ...```?

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 49]
```diff
@@ -0,0 +1,190 @@
...
+
+                        // Ignore fields that are not candidates or have already been analyzed to have been written outside the constructor/field initializer.
+                        if (!fieldState.isCandidate || fieldState.written)
+                        {
+                            return;
+                        }
+
+                        // Field writes: assignment, increment/decrement or field passed by ref.
+                        bool isFieldAssignemnt = fieldReference.Parent is IAssignmentOperation assignmentOperation && assignmentOperation.Target == fieldReference;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: 1: var
2: wrap long lines.

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 50]
```diff
@@ -0,0 +1,190 @@
...
+                            fieldReference.Parent is IIncrementOrDecrementOperation ||
+                            fieldReference.Parent is IArgumentOperation argumentOperation && argumentOperation.Parameter.RefKind != RefKind.None)
+                        {
+                            // Reads and writes of instance fields inside constructor are ignored, except for the below cases:
+                            //  1. Instance reference of field being written is not the instance being initialized by the constructor.
+                            //  2. Field is being written inside a lambda or local function. 
+                            if (field.ContainingType == operationBlockStartContext.OwningSymbol.ContainingType &&
+                                (isConstructor && fieldReference.Instance?.Kind == OperationKind.InstanceReference && (!isFieldAssignemnt || fieldReference.Parent.Parent?.Kind != OperationKind.ObjectOrCollectionInitializer) ||
+                                 isStaticConstructor && field.IsStatic) &&
+                                !IsInAnonymousFunctionOrLocalFunction(fieldReference))
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: this entire check is far too complex.  Please extract out named locals to make it clear what each clause is checking for.

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 51]
```diff
@@ -0,0 +1,190 @@
...
+                            }
+
+                            OnFieldWrite(field);
+                        }
+                    }, OperationKind.FieldReference);
+                });
+
+                compilationStartContext.RegisterCompilationEndAction(compilationEndContext =>
+                {
+                    foreach (var kvp in fieldStateMap)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: you can deconstruct in the foreach variable.  i.e.   ```foreach (var (field, (isCandidate, written)) in ...)```

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 52]
```diff
@@ -0,0 +1,190 @@
...
+                        }
+                    }
+                });
+            });
+        }
+
+        private static CodeStyleOption<bool> GetCodeStyleOption(IFieldSymbol field, AnalyzerOptions options, CancellationToken cancellationToken)
+        {
+            var optionSet = options.GetDocumentOptionSetAsync(field.Locations[0].SourceTree, cancellationToken).GetAwaiter().GetResult();
+            if (optionSet == null)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: nit: can you just use ?.

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 53]
```diff
@@ -0,0 +1,190 @@
...
+                    Debug.Assert(fieldStateMap.ContainsKey(field));
+
+                    fieldStateMap[field] = (isCandidate: true, written: true);
+                }
+
+                (bool isCandidate, bool written) TryGetOrComputeIsCandidateField(IFieldSymbol fieldSymbol, AnalyzerOptions options, CancellationToken cancellationToken)
+                {
+                    return fieldStateMap.GetOrAdd(fieldSymbol, valueFactory: ComputeIsCandidate);
+
+                    (bool isCandidate, bool written) ComputeIsCandidate(IFieldSymbol field)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: i'm not a huge fan of excessive nesting of functions.  it makes flow control harder at times.

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 51 above)
Comment (mavasani) [reply src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: > foreach (var (field, (isCandidate, written)) in ...)

That causes a syntax error.

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 43 above)
Comment (sharwell) [reply src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: PascalCase is expected for local functions, to distinguish them from instances of delegates.

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 46 above)
Comment (sharwell) [reply src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: :grey_exclamation: use just `_` (no `var`) for discards

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 53 above)
Comment (mavasani) [reply src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: We are capturing couple of parameters from the enclosing local function.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: i realize that :)  i'm just saying that excessive nesting makes things less clear.  it can be nicer for readability to keep things simpler.  My personal preference is really to not go deeper than one level of local functions.

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 43 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: IDE goes the opposite route in many cases.  It's camelCased (like all locals) since it is a local.  It also helps distinguish from actual methods.

Comment (sharwell) [reply src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: ➡️ All instances of local functions in the code base current marked with a `// local functions` comment (case insensitive) use PascalCase. In the event of non-uniformity, PascalCase is preferred.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: Alright.  The naming is less of a concern for me and i'm fine with pascal being used.  The more important part is placing the code not inline with the main sequential logic for the function.  If we can move to after teh final return, that would be nice.  Thanks!

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 54]
```diff
@@ -0,0 +1,205 @@
...
+        {
+        }
+
+        public override bool OpenFileOnly(Workspace workspace) => false;
+
+        public override DiagnosticAnalyzerCategory GetAnalyzerCategory() => DiagnosticAnalyzerCategory.ProjectAnalysis;
+
+        protected override void InitializeWorker(AnalysisContext context)
+        {
+            context.RegisterCompilationStartAction(compilationStartContext =>
```
Comment (sharwell) [inline src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: ❕ Refactor this callback to be a method (not local function) named `HandleCompilationStart`

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 55]
```diff
@@ -0,0 +1,205 @@
...
+            {
+                // Stores the state for fields:
+                //  'isCandidate' : Indicates whether the field is a candidate to be made readonly based on it's declaration and options.
+                //  'written'     : Indicates if there are any writes to the field outside the constructor and field initializer.
+                var fieldStateMap = new ConcurrentDictionary<IFieldSymbol, (bool isCandidate, bool written)>();
+
+                compilationStartContext.RegisterSymbolAction(symbolContext =>
```
Comment (sharwell) [inline src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: ❕ Refactor this callback to be a method (not local function) named `HandleField`

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 56]
```diff
@@ -0,0 +1,205 @@
...
+                {
+                    tryGetOrComputeIsCandidateField((IFieldSymbol)symbolContext.Symbol, symbolContext.Options, symbolContext.CancellationToken);
+                }, SymbolKind.Field);
+
+                compilationStartContext.RegisterOperationBlockStartAction(operationBlockStartContext =>
```
Comment (sharwell) [inline src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: ❕ Refactor this callback to be a method (not local function) named `HandleOperationBlockStart`

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 57]
```diff
@@ -0,0 +1,205 @@
...
+                {
+                    var isConstructor = operationBlockStartContext.OwningSymbol.IsConstructor();
+                    var isStaticConstructor = operationBlockStartContext.OwningSymbol.IsStaticConstructor();
+
+                    operationBlockStartContext.RegisterOperationAction(operationContext =>
```
Comment (sharwell) [inline src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: ❕ Refactor this callback to be a method (not local function) named `HandleFieldReference`

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 58]
```diff
@@ -0,0 +1,205 @@
...
+                                    }
+                                }
+                            }
+
+                            onFieldWrite(field);
+                        }
+                    }, OperationKind.FieldReference);
+                });
+
+                compilationStartContext.RegisterCompilationEndAction(compilationEndContext =>
```
Comment (sharwell) [inline src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: ❕ Are compilation end actions already supported in the IDE layer?

* If so, refactor this callback to be a method (not local function) named `HandleCompilationEnd`
* If not, the analyzer needs to be refactored to avoid relying on this unsupported method

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 54 above)
Comment (mavasani) [reply src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: I disagree with this suggestion - all analyzer actions and nested actions **should** be registered in a single method to make it easier to understand the overall analysis logic. We follow this across all analyzers in the repos we own and was also the primary reason that the design team decided on analyzer actions being delegates during original analyzer API design.

I have added more comments and refactored out logic within the registered actions into separate helper methods to improve readability.

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 55 above)
Comment (mavasani) [reply src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: As explained above. This action has one line of code and does not need a separate method.

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 56 above)
Comment (mavasani) [reply src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: Refactored the logic for field write detection into a helper to improve readability.

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 57 above)
Comment (mavasani) [reply src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: Refactored the logic for field write detection into a helper to improve readability.

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 58 above)
Comment (mavasani) [reply src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: > Are compilation end actions already supported in the IDE layer?

I don't think this is relevant here, though @heejaechang is planning to fix the compilation end action bug soon. This problem cannot be solved with local analysis without introducing performance problems or writing spaghetti code. Detection of unused fields, readonly fields, etc. should be a compilation analyzer. Presence of unrelated bugs in the IDE engine should not affect this analyzer's implementation logic.

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 43 above)
Comment (mavasani) [reply src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: I have switched back to using PascalCase naming for local functions. However, it is extremely frustrating that differing personal style preferences for different reviewers and different parts of Roslyn code base (IDE, compiler), are attempted to be enforced via code reviews:

1. `var` or explicit type: Reviewers on IDE team prefer var and those on compiler team prefer explicit type.
2. Local function names: Some IDE team reviewers prefer pascal casing, while some prefer camel casing. Reviewers on compiler team prefer camel casing.

Neither compiler nor IDE code bases have consistent usage in these style preferences to enforce this strongly via analyzers/editor config. This leads to the PR author to choose their own preferred style and waste time in iterations to jump between preferences as it gets reviewed.

I think the rule should be simple for all teams (compiler/IDE) wrt corresponding code bases they own: either make your code base consistent enough so you can enforce preferred style on your code base via editor config OR if this is too much work, then loosen the style requirements for PRs from folks that don't normally work on your code base and ensure that your team members follow these style preferences and cleanup code to abide by them whenever they change it.

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 54 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: > I disagree with this suggestion - all analyzer actions and nested actions should be registered in a single method to make it easier to understand the overall analysis logic.

@mavasani  Your reasoning seems fine.  *Except* for the fact that you're going against the patterns and practices the IDE uses.  I'm not a fan of this as recently several PR have been coming in that do this sort of thing.  If you want to change the patterns here, please discuss it with the relevant stakeholders, and come to consensus on these sorts of things.  Then, we can decide if we like it, and if so *uniformly* move all the code to be consistent *or* we can decide "no, we like it as is".

Right now, these PRs are increasing inconsistency in the IDE codebase.  And that's not good.  If you believe this approach is better, it can be discussed.  But it should only go forward with team acceptance, and with a plan to ensure we don't have total inconsistency across the features.

> We follow this across all analyzers in the repos we own and was also the primary reason that the design team decided on analyzer actions being delegates during original analyzer API design.

I do not recall that part of the discussion at all.  The primary reason i remember being stated was so that people could easily register callbacks in strongly typed fashion.  i.e. i would ask to be called back for some event, and i would be given the context that i could only do the right thing with.  That was better than a whole host of events and callbacks on a single object that you would have to know how they all worked together.

Also, a common pattern we showed when during this time was simply:  ```x.RegisterXXXAction(() => DoSomething(), Kinds);```  It was never a core outcome that the expected or desired way was to put all logic in the lambda.  That was always up to the final user depending on if they felt such an approach was more pleasant or not.

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 58 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: > I don't think this is relevant here, though @heejaechang is planning to fix the compilation end action bug soon. This problem cannot be solved with local analysis without introducing performance problems or writing spaghetti code. 

I don't think it's spaghetti code.  It's simply analysis of a symbol, which shouldn't have a perf problem.  

> Presence of unrelated bugs in the IDE engine should not affect this analyzer's implementation logic.

That's ok *only* if the fix for compilation end actions truly is coming soon.  We literally had features not on *for years* because we wrote them, expecting this part of the analysis engine to work, and it was never fixed.  So, i'm skeptical of any approach that depends on this until we actually fixed the underlying IDE analysis problem.

File: src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs (hunk 43 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: > Neither compiler nor IDE code bases have consistent usage in these style preferences to enforce this strongly via analyzers/editor config.

I disagree.  IDE is highly consistent with usage of "var".  I'm going to guess that it's 95% plus (and could be made more consistent pretty easily).

It's true that we're inconsistent with local function names.  I was hesitant originally around allowing local functions, but we let them creep in slowly without doing a team assessment about what we'd like the pattern there to be.  Team should decide acceptable style (probably whatever the majority of the IDE code uses), and then apply that consistently.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: > This leads to the PR author to choose their own preferred style and waste time in iterations to jump between preferences as it gets reviewed.

The IDE has strongly been opinionated on 'var' for over a decade (and many other non-checked systems).  PR authors should respect that.  IDE shoudl also attempt to see what can be enforced stylistically, potentially through tools like StyleCopAnalyzers.  I know @sharwell seems particularly interested in this, and i would be totally supportive of adopting such a system on the *IDE* side.

Note that the compiler is its own project with its own rules.  Devs are expected to know and follow the conventions each team prefers for their respective codebases.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/MakeFieldReadonly/MakeFieldReadonlyDiagnosticAnalyzer.cs]: > I think the rule should be simple for all teams (compiler/IDE) wrt corresponding code bases they own: either make your code base consistent enough so you can enforce preferred style on your code base via editor config

Yes.  I would be fine with this.  @sharwell For the IDE team, do you know why we haven't flipped on certain options?

> then loosen the style requirements for PRs from folks that don't normally work on your code base 

Sorry, i don't think that's ok.  There are thousands of projects out there that accept contributions from external people, but expect those people to follow the conventions of that project.  That ranges from coding style, to tests, to documentation, to whatever.  The onus is on the contributer to follow the wishes of the project they're contributing to.  Though i certainly agree anything the project can do to make that easier is desirable.  However, the lack of nice-ness here is not an pass to just say that contributers don't have to care and the team is responsible for cleaning up after the fact.

**Comment by sharwell** [comment]
In a design meeting today, we came to two conclusions relevant to this feature:

1. In the short term (target 15.7) we will leverage the same approach used by the Use Auto Property analyzer in #23237 to avoid the need to use a compilation end analyzer. In addition to the restriction to only consider private fields, we will avoid false positives by excluding `partial` classes from consideration, except where they are nested within a non-`partial` class.
2. In the medium term, we will continue to use analyzers like these as inputs to our overall design goal of enabling compilation end analyzer scenarios in the IDE.

**Comment by mavasani** [comment]
@sharwell I have pushed my commits to a separate branch: https://github.com/mavasani/roslyn/tree/MakeFieldReadOnly_IOperationAnalyzer. Feel free to revert these commits in this PR and fix the original analyzer implementation.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 59]
```diff
@@ -0,0 +1,214 @@
...
+            var option = optionSet.GetOption(CodeStyleOptions.PreferReadonly, semanticModel.Language);
+            if (!option.Value)
+            {
+                return;
+            }
+
+            var syntaxFactsService = GetSyntaxFactsService();
+            var root = semanticModel.SyntaxTree.GetRoot(cancellationToken);
+            var candidateTypes = PooledHashSet<(ITypeSymbol, SyntaxNode)>.GetInstance();
+            AddCandidateTypesInCompilationUnit(semanticModel, root, candidateTypes, cancellationToken);
```
Comment (mavasani) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: We would not need this method if the analyzer were to be written as a symbol analyzer which registers for `SymbolKind.NamedType`. We can directly check if the symbol has 1 declaring reference/location to consider it as a candidate.

File: src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs [hunk 60]
```diff
@@ -0,0 +1,214 @@
...
+                }
+
+                analyzedTypes.Free();
+            }
+
+            candidateTypes.Free();
+            candidateFields.Free();
+        }
+
+        private void AddCandidateFieldsInType(SemanticModelAnalysisContext context, ITypeSymbol typeSymbol, SyntaxNode typeSyntax, PooledHashSet<IFieldSymbol> candidateFields)
```
Comment (mavasani) [inline src/Features/Core/Portable/MakeFieldReadonly/AbstractMakeFieldReadonlyDiagnosticAnalyzer.cs]: static?

**Comment by CyrusNajmabadi** [comment]
> In addition to the restriction to only consider private fields, we will avoid false positives by excluding partial classes from consideration, except where they are nested within a non-partial class.

Hrm.  This doesn't seem necessary.  As you mentioned "In the short term (target 15.7) we will leverage the same approach used by the Use Auto Property analyzer".  UseAutoProp doesn't need to exclude partial classes.  It just analyzes the properties it finds in the parts it finds within a SemanticModel.  It feels liek the same would be done for MakeFieldReadOnly.  We would analyze in practically the same manner.  

Both features feel very similar from an implementation perspective. They look at properties or fields in a single part of a partial type at a time.  And they also look for things that disallow the conversion from happening.  Once hte whole semantic model has been walked, eligible matches are reported.

**Comment by sharwell** [comment]
> Hrm. This doesn't seem necessary.

Partial classes are excluded to ensure no diagnostic is reported in the following case:

```csharp
// A.cs
partial class MyType
{
  private int _value;
}

// B.cs
partial class MyType
{
  private void SetValue(int value) { _value = value; }
}
```

**Comment by CyrusNajmabadi** [comment]
Note: while UseAutoProperty does necessarily have to examine all parts when deciding on eligibility, it does so batched up at the end.  i.e. after finding **all** the properties htat could be made into an auto-property in a single file, it then goes and batches them, aggregating all their containing types (in case they belonged to different types).  It then groups those types by the files their parts are contained in.  And it processes each of those files once, examining them in their entirety for things that would make the fix ineligible. 

This approach seems like it would fit to a T what we need for MakeFieldReadOnly.

**Comment by CyrusNajmabadi** [comment]
> Partial classes are excluded to ensure no diagnostic is reported in the following case:

UseAutoProp has no problem with that scenario.  There are two passes.  The first pass collects the candidates (in your case ```_value```).  The second pass computes eligibility.  The second pass would see here that _value was written in a disallowed location and would remove _value from the candidate set.

See:

CSharpUseAutoPropertyAnalyzer.RegisterIneligibleFieldsAction
https://github.com/dotnet/roslyn/blob/5fbba2075b94dceb214ff7ee018a448f714b0275/src/EditorFeatures/CSharp/UseAutoProperty/CSharpUseAutoPropertyAnalyzer.cs#L64-L85

**Comment by sharwell** [comment]
@CyrusNajmabadi It's possible we could expand support in the future, but we decided to scope limit the analysis to single-file cases only to increase confidence in the runtime performance of the initial implementation given the relatively short time we'll have to evaluate it before release.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi It's possible we could expand support in the future, but we decided to scope limit the analysis to single-file cases only to increase confidence in the runtime performance of the initial implementation given the relatively short time we'll have to evaluate it before release.

That's a reasonable reason.  Could we file an issue on that.  Perhaps linking to this discussion?  I perf tested UseAutoProp out on roslyn, and didn't encounter any issues.  But i can understand not wanting to risk things.  it would be nice though if this could be added later when proper due diligence can be done!  Thanks!

**Comment by sharwell** [comment]
@CyrusNajmabadi Sure, I filed an issue to migrate to IOperation but you could separately call out the improvement to handling partial types.

**Comment by heejaechang** [comment]
@jinujoseph are we going to push making compilation end analyzer first citizen in VS as we discussed in the meeting? I think we should have bug opened to track the work.

the work we discussed

1. make full solution analysis per solution option and make it on by default
2. make full solution analysis to be 3 state.s On, Open Files, Off
3. reduce delay from currently 5 seconds to 2 or less 
4. make code fix to work with compilation end analyzer (requires editor team's help making LB to be asyncly updated) as good as other code fixes.
5. change diagnostic analyzer contract that only compilation end analyzer can produce non local diagnostics (diagnostic that belong to other portion of compilation that it is currently analyzed such as tree, symbol and etc)
6. add an option to CompilationWithAnalyzer that runs only analyzers with compilation end analysis

..

we want 
(1) to gives users full experience. 
(2) is for people with solution whose machine can't handle/beefy enough to handle FSA.
(3, 4) are too make compilation end analyzer/fixer has similar experience as other analyzer/fixer
(5, 6) are needed so that we can run limit work we needs for compilation end analyzers.

**Comment by sharwell** [comment]
> Please remove the unncessary `AddCandidateTypesInCompilationUnit` method by changing it to a named type symbol analyzer.

The current implementation avoids analyzing the contents of nested types multiple times. Switching to a symbol analyzer makes it difficult to preserve this functionality without losing the simplicity benefit of switching to a symbol analyzer, and increases the discrepancy between this and the Use Auto Property analyzer.

**Comment by mavasani** [comment]
>The current implementation avoids analyzing the contents of nested types multiple times. Switching to a symbol analyzer makes it difficult to preserve this functionality

I feel this is an extremely rare scenario, especially given our claim here that partial types are not important enough and we are going to skip past large number of types. Personally, I would rather not complicate this already over-complicated implementation to potentially gain perf benefit for corner cases. However, given that we plan to fix the compilation end action bug soon, and delete this implementation, I am okay with this approach.

> increases the discrepancy between this and the Use Auto Property analyzer.

I don't think that should be relevant.

**Comment by sharwell** [comment]
> I don't think that should be relevant.

It typically wouldn't be. It only became relevant as a secondary benefit when the primary change didn't yield a clear net advantage to either approach.

**Comment by jinujoseph** [comment]
Approval pending for 15.7 Preview 4 (new feature )

**Comment by jinujoseph** [comment]
Approved to merge the feature in 15.7 Preview 4 ( make sure to address review feedback and conflict )  cc @Pilchie  for info

**Comment by Pilchie** [comment]
Hooray! 🎆

**Comment by Hosch250** [comment]
Great job, everyone.
