### PR TITLE
IDE Features fix for code generation for ref-readonly

### LINKED ISSUE #22238: Extract interface loses "ref readonly" on parameters and returns
parameters become an ordinary `ref`, returns become ordinary byval returns.

### LINKED ISSUE #22239: Change Signature does not show "ref readonly" modifier on parameters
The Change Signature  shows  other modifiers like "out" but not "ref readonly" - not sure if it does not understand it or because it simply does not fit. There is no much space in that UI.

### LINKED ISSUE #22240: Add Accessibility modifier removes "ref" from a ref struct
Invoke Refactor/Add Accessibility modifiers on 

```cs
readonly unsafe ref struct S1 { }
```
The dialog offers adding "private", but also offers to remove "ref"

### LINKED ISSUE #22241: Replace lambda with local function loses "ref readonly"
```cs
        delegate ref readonly int D1(ref readonly int arg);

            D1 dd = (ref readonly int a) => ref a;
```

Replace dd with a local function using IDE. - loses "ref readonly"

### LINKED ISSUE #22242: Implement Interface loses "ref readonly"
Implement interface refactoring loses "ref readonly" on parameters. 

Inherit from abstract class does this too.

### PR DESCRIPTION
**Pull request by OmarTawfik**
Fixes #22242 - Implement Interface loses "ref readonly"
Fixes #22241 - Replace lambda with local function loses "ref readonly"
Fixes #22240 - Add Accessibility modifier removes "ref" from a ref struct
Fixes #22239 - Change Signature does not show "ref readonly" modifier on parameters
Fixes #22238 - Extract interface loses "ref readonly" on parameters and returns

I split this PR into two commits:
* One has all the refactoring (threading RefKinds through various APIs)
* Another for the tests, roughly one test file change per bug above.

### CODE REVIEW

**Comment by OmarTawfik** [comment]
cc @dotnet/roslyn-compiler @dotnet/roslyn-ide @VSadov

File: src/Compilers/Core/Portable/Symbols/RefKind.cs [hunk 1]
```diff
@@ -49,7 +50,7 @@ internal static string ToArgumentDisplayString(this RefKind kind)
             {
                 case RefKind.Out: return "out";
                 case RefKind.Ref: return "ref";
```
Comment (agocke) [inline src/Compilers/Core/Portable/Symbols/RefKind.cs]: Per latest LDM, this should probably say `ref readonly now`

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs [hunk 2]
```diff
@@ -120,17 +120,36 @@ public override SyntaxNode ParameterDeclaration(string name, SyntaxNode type, Sy
...
+                    throw ExceptionUtilities.UnexpectedValue(refKind);
+            }
+        }
+
+        internal static SyntaxToken GetArgumentModifiers(RefKind refKind)
+        {
+            switch (refKind)
+            {
+                case RefKind.None:
+                case RefKind.RefReadOnly:
```
Comment (agocke) [inline src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs]: This should now be "ref"

File: src/Compilers/Core/Portable/PublicAPI.Unshipped.txt [hunk 3]
```diff
@@ -36,6 +36,7 @@ Microsoft.CodeAnalysis.Diagnostics.Telemetry.AnalyzerTelemetryInfo.OperationBloc
 Microsoft.CodeAnalysis.Diagnostics.Telemetry.AnalyzerTelemetryInfo.OperationBlockEndActionsCount.set -> void
 Microsoft.CodeAnalysis.Diagnostics.Telemetry.AnalyzerTelemetryInfo.OperationBlockStartActionsCount.get -> int
 Microsoft.CodeAnalysis.Diagnostics.Telemetry.AnalyzerTelemetryInfo.OperationBlockStartActionsCount.set -> void
+Microsoft.CodeAnalysis.IMethodSymbol.RefKind.get -> Microsoft.CodeAnalysis.RefKind
 Microsoft.CodeAnalysis.IMethodSymbol.ReturnsByRefReadonly.get -> bool
```
Comment (VSadov) [inline src/Compilers/Core/Portable/PublicAPI.Unshipped.txt]: >ReturnsByRefReadonly [](start = 37, length = 20)

If RefKind stays, we may want to remove "ReturnsByRefReadonly". And if we do, perhaps before 15.5 - should we add a tracking issue?

Comment (VSadov) [reply src/Compilers/Core/Portable/PublicAPI.Unshipped.txt]: I do thin RefKind is a good idea. Just makes ReturnsByRefReadonly redundant and since that one is also new, we can remove it.

---
In reply to: [141178011](https://github.com/dotnet/roslyn/pull/22285#discussion_r141178011) [](ancestors = 141178011)

File: src/Compilers/Core/Portable/Symbols/RefKind.cs (hunk 1 above)
Comment (VSadov) [reply src/Compilers/Core/Portable/Symbols/RefKind.cs]: Per LDM it can match a ref ore ref readonly parameters. But on the argument side it is a ref. I think returning "ref" is correct. - that is all we know given just the argument.

---
In reply to: [141171113](https://github.com/dotnet/roslyn/pull/22285#discussion_r141171113) [](ancestors = 141171113)

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs [hunk 4]
```diff
@@ -120,8 +120,8 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
 
             var invokeMethod = delegateType.DelegateInvokeMethod;
 
-            var returnType = invokeMethod.ReturnsVoid
-                ? s_voidType
+            var returnType = invokeMethod.ReturnsByRef ? invokeMethod.ReturnType.GenerateRefTypeSyntax()
+                : invokeMethod.ReturnsByRefReadonly ? invokeMethod.ReturnType.GenerateRefReadOnlyTypeSyntax()
                 : invokeMethod.ReturnType.GenerateTypeSyntax();
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: better to look like

```c#
var returnType = invokeMethod.ReturnsByRef ? invokeMethod.ReturnType.GenerateRefTypeSyntax() : invokeMethod.ReturnsByRefReadonly 
                                           ? invokeMethod.ReturnType.GenerateRefReadOnlyTypeSyntax() : invokeMethod.ReturnType.GenerateTypeSyntax();

File: src/Features/Core/Portable/GenerateMember/GenerateVariable/AbstractGenerateVariableService.CodeAction.cs [hunk 5]
```diff
@@ -70,7 +70,7 @@ protected override Task<Document> GetChangedDocumentAsync(CancellationToken canc
                         accessibility: DetermineMaximalAccessibility(_state),
                         modifiers: new DeclarationModifiers(isStatic: _state.IsStatic, isUnsafe: generateUnsafe),
                         type: _state.TypeMemberType,
-                        returnsByRef: _returnsByRef,
+                        refKind: _returnsByRef ? RefKind.Ref : RefKind.None,
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/GenerateMember/GenerateVariable/AbstractGenerateVariableService.CodeAction.cs]: is this sufficient?  is there a ref-readonly case this won't work for?

File: src/VisualStudio/Core/Test/ChangeSignature/ChangeSignatureViewModelTests.vb [hunk 6]
```diff
@@ -13,6 +13,7 @@ Imports Microsoft.CodeAnalysis.Shared.Extensions
 Imports Roslyn.Test.Utilities
 Imports Microsoft.VisualStudio.LanguageServices.Implementation.ChangeSignature
 Imports Microsoft.CodeAnalysis.Editor.UnitTests.Utilities
+Imports Roslyn.Utilities
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Test/ChangeSignature/ChangeSignatureViewModelTests.vb]: sorting.

File: src/Workspaces/CSharp/Portable/CodeGeneration/MethodGenerator.cs [hunk 7]
```diff
@@ -90,8 +90,8 @@ internal static class MethodGenerator
 
             var explicitInterfaceSpecifier = GenerateExplicitInterfaceSpecifier(method.ExplicitInterfaceImplementations);
 
-            var returnType = method.ReturnsByRef
-                ? method.ReturnType.GenerateRefTypeSyntax()
+            var returnType = method.ReturnsByRef ? method.ReturnType.GenerateRefTypeSyntax()
+                : method.ReturnsByRefReadonly ? method.ReturnType.GenerateRefReadOnlyTypeSyntax()
                 : method.ReturnType.GenerateTypeSyntax();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/CodeGeneration/MethodGenerator.cs]: formatting.  also, try to share code with teh other snippet that is identical to this.

File: src/Workspaces/CSharp/Portable/CodeGeneration/ParameterGenerator.cs [hunk 8]
```diff
@@ -92,23 +92,21 @@ internal static ParameterSyntax GetParameter(IParameterSymbol p, CodeGenerationO
...
-                return SyntaxFactory.TokenList(SyntaxFactory.Token(SyntaxKind.ParamsKeyword));
+                list = list.Add(SyntaxFactory.Token(SyntaxKind.ParamsKeyword));
             }
 
-            return parameter.RefKind == RefKind.None
-                ? new SyntaxTokenList()
-                : parameter.RefKind == RefKind.Out
-                    ? SyntaxFactory.TokenList(SyntaxFactory.Token(SyntaxKind.OutKeyword))
-                    : SyntaxFactory.TokenList(SyntaxFactory.Token(SyntaxKind.RefKeyword));
+            return list;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/CodeGeneration/ParameterGenerator.cs]: where does out/ref get added now?

File: src/Workspaces/CSharp/Portable/CodeGeneration/PropertyGenerator.cs [hunk 9]
```diff
@@ -109,9 +109,9 @@ public static bool CanBeGenerated(IPropertySymbol property)
 
         private static TypeSyntax GeneratePropertyType(IPropertySymbol property)
         {
-            return property.ReturnsByRef
-                            ? property.Type.GenerateRefTypeSyntax()
-                            : property.Type.GenerateTypeSyntax();
+            return property.ReturnsByRef ? property.Type.GenerateRefTypeSyntax()
+                : property.ReturnsByRefReadonly ? property.Type.GenerateRefReadOnlyTypeSyntax()
+                : property.Type.GenerateTypeSyntax();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/CodeGeneration/PropertyGenerator.cs]: formatting.  also, share code with the other duplicated locations.

File: src/Workspaces/CSharp/Portable/Extensions/ITypeSymbolExtensions.cs [hunk 10]
```diff
@@ -54,6 +54,17 @@ internal static partial class ITypeSymbolExtensions
             return SyntaxFactory.RefType(refKeyword, underlyingType);
         }
 
+        public static TypeSyntax GenerateRefReadOnlyTypeSyntax(
+            this INamespaceOrTypeSymbol symbol)
+        {
+            var underlyingType = GenerateTypeSyntax(symbol)
+                .WithPrependedLeadingTrivia(SyntaxFactory.ElasticMarker)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Extensions/ITypeSymbolExtensions.cs]: this elastic marker seems unnecessary.  You'll already get one for the refkeyword token.

File: src/Workspaces/CSharp/Portable/Extensions/ITypeSymbolExtensions.cs [hunk 11]
```diff
@@ -54,6 +54,17 @@ internal static partial class ITypeSymbolExtensions
             return SyntaxFactory.RefType(refKeyword, underlyingType);
         }
 
+        public static TypeSyntax GenerateRefReadOnlyTypeSyntax(
+            this INamespaceOrTypeSymbol symbol)
+        {
+            var underlyingType = GenerateTypeSyntax(symbol)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Extensions/ITypeSymbolExtensions.cs]: GenerateTypeSyntax already adds the simplifier annotation.

File: src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationPropertySymbol.cs [hunk 12]
```diff
@@ -82,11 +82,27 @@ public bool IsWriteOnly
 
         public new IPropertySymbol OriginalDefinition => this;
 
+        public RefKind RefKind
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationPropertySymbol.cs]: use autoprop

File: src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationPropertySymbol.cs [hunk 13]
```diff
@@ -82,11 +82,27 @@ public bool IsWriteOnly
...
+        {
+            get
+            {
+                return this._refKind;
+            }
+        }
+
+        public bool ReturnsByRef
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/CodeGeneration/Symbols/CodeGenerationPropertySymbol.cs]: use =>

File: src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs [hunk 14]
```diff
@@ -125,6 +125,11 @@ public bool IsWriteOnly
             get { return (_modifiers & Modifiers.WriteOnly) != 0; }
         }
 
+        public bool IsRef
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs]: use =>

File: src/Workspaces/Core/Portable/Shared/Extensions/IParameterSymbolExtensions.cs [hunk 15]
```diff
@@ -11,7 +11,14 @@ internal static class IParameterSymbolExtensions
     {
         public static bool IsRefOrOut(this IParameterSymbol symbol)
         {
-            return symbol.RefKind != RefKind.None;
+            switch(symbol.RefKind)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Shared/Extensions/IParameterSymbolExtensions.cs]: seems like ```return  symbol.RefKind == Ref || symbol.RefKind == Out``` would be sufficient here.  Switch seems like overkill.

**Comment by CyrusNajmabadi** [comment]
Overall, IDE side seems good.

File: src/Compilers/Core/Portable/PublicAPI.Unshipped.txt [hunk 16]
```diff
@@ -36,6 +36,7 @@ Microsoft.CodeAnalysis.Diagnostics.Telemetry.AnalyzerTelemetryInfo.OperationBloc
 Microsoft.CodeAnalysis.Diagnostics.Telemetry.AnalyzerTelemetryInfo.OperationBlockEndActionsCount.set -> void
 Microsoft.CodeAnalysis.Diagnostics.Telemetry.AnalyzerTelemetryInfo.OperationBlockStartActionsCount.get -> int
 Microsoft.CodeAnalysis.Diagnostics.Telemetry.AnalyzerTelemetryInfo.OperationBlockStartActionsCount.set -> void
+Microsoft.CodeAnalysis.IMethodSymbol.RefKind.get -> Microsoft.CodeAnalysis.RefKind
```
Comment (jcouv) [inline src/Compilers/Core/Portable/PublicAPI.Unshipped.txt]: FYI @gafter for public API change.

File: src/Compilers/Core/Portable/Symbols/RefKind.cs (hunk 1 above)
Comment (OmarTawfik) [reply src/Compilers/Core/Portable/Symbols/RefKind.cs]: I agree. We cannot tell from the argument display which method it will bind to.

---
In reply to: [141179053](https://github.com/dotnet/roslyn/pull/22285#discussion_r141179053) [](ancestors = 141179053,141171113)

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs (hunk 2 above)
Comment (OmarTawfik) [reply src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs]: I'll leave this to @vsadov, as LDM changed it again today.

---
In reply to: [141172627](https://github.com/dotnet/roslyn/pull/22285#discussion_r141172627) [](ancestors = 141172627)

File: src/Compilers/Core/Portable/PublicAPI.Unshipped.txt (hunk 3 above)
Comment (OmarTawfik) [reply src/Compilers/Core/Portable/PublicAPI.Unshipped.txt]: I do think that the redundency of `ReturnsByRefReadOnly` is the same as `ReturnsByRef`. Why should one exist without the other?

---
In reply to: [141178222](https://github.com/dotnet/roslyn/pull/22285#discussion_r141178222) [](ancestors = 141178222,141178011)

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs (hunk 4 above)
Comment (OmarTawfik) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: IMHO, putting the condition always on the  left handside makes it more readable. In the following:
```csharp
var returnType = invokeMethod.ReturnsByRef ? invokeMethod.ReturnType.GenerateRefTypeSyntax() : invokeMethod.ReturnsByRefReadonly 
                                           ? invokeMethod.ReturnType.GenerateRefReadOnlyTypeSyntax() : invokeMethod.ReturnType.GenerateTypeSyntax();
```
The first line will read to me as a complete sentence, in which `invokeMethod.ReturnsByRefReadonly  returns the false result, and it will be separate from the following line.

---
In reply to: [141180523](https://github.com/dotnet/roslyn/pull/22285#discussion_r141180523) [](ancestors = 141180523)

File: src/Features/Core/Portable/GenerateMember/GenerateVariable/AbstractGenerateVariableService.CodeAction.cs (hunk 5 above)
Comment (OmarTawfik) [reply src/Features/Core/Portable/GenerateMember/GenerateVariable/AbstractGenerateVariableService.CodeAction.cs]: Right now, we don't have the mechanism to guess that from syntax at call-site. I added #22385 to track that.

---
In reply to: [141180693](https://github.com/dotnet/roslyn/pull/22285#discussion_r141180693) [](ancestors = 141180693)

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs (hunk 4 above)
Comment (OmarTawfik) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: refactored

---
In reply to: [141180523](https://github.com/dotnet/roslyn/pull/22285#discussion_r141180523) [](ancestors = 141180523)

File: src/Workspaces/CSharp/Portable/CodeGeneration/ParameterGenerator.cs (hunk 8 above)
Comment (OmarTawfik) [reply src/Workspaces/CSharp/Portable/CodeGeneration/ParameterGenerator.cs]: in CSharpSyntaxGenerator.GetParameterModifiers(RefKind)

---
In reply to: [141181107](https://github.com/dotnet/roslyn/pull/22285#discussion_r141181107) [](ancestors = 141181107)

File: src/Workspaces/CSharp/Portable/Extensions/ITypeSymbolExtensions.cs (hunk 11 above)
Comment (OmarTawfik) [reply src/Workspaces/CSharp/Portable/Extensions/ITypeSymbolExtensions.cs]: Then why is it specified in `GenerateRefTypeSyntax()`?

---
In reply to: [141181527](https://github.com/dotnet/roslyn/pull/22285#discussion_r141181527) [](ancestors = 141181527)

File: src/Workspaces/CSharp/Portable/Extensions/ITypeSymbolExtensions.cs (hunk 10 above)
Comment (OmarTawfik) [reply src/Workspaces/CSharp/Portable/Extensions/ITypeSymbolExtensions.cs]: Not here, since this is following the same pattern as `GenerateRefTypeSyntax()`. Am I missing something?

---
In reply to: [141181425](https://github.com/dotnet/roslyn/pull/22285#discussion_r141181425) [](ancestors = 141181425)

File: src/Workspaces/Core/Portable/Shared/Extensions/IParameterSymbolExtensions.cs (hunk 15 above)
Comment (OmarTawfik) [reply src/Workspaces/Core/Portable/Shared/Extensions/IParameterSymbolExtensions.cs]: in case of this symbol calculating refkind from child symbols, this saves a few cycles. Also, same as saving into a temp followed by an if statement.

---
In reply to: [141181968](https://github.com/dotnet/roslyn/pull/22285#discussion_r141181968) [](ancestors = 141181968)

**Comment by OmarTawfik** [comment]
@CyrusNajmabadi I left one reply on the comment in `ITypeSymbolExtensions.GenerateRefReadOnlyTypeSyntax()`. I'll merge now since you signed off. Please feel free to assign a bug to me if that doesn't resolve your concern.
