### PR TITLE
Better exclude local functions from region analysis

### LINKED ISSUE #17165: ExtractMethodMatrix.GetVariableStyle Throws exception on code with errors
**Version Used**: 
image

**Steps to Reproduce**:

1.  Use Alt+Arrow to move members into lambda that is an argument into a method that is missing semicolon

**Expected Behavior**:
No Crash

**Actual Behavior**:
```
System.InvalidOperationException : Unexpected false
   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition,String message)
   at Microsoft.CodeAnalysis.ExtractMethod.ExtractMethodMatrix.GetVariableStyle(Boolean captured,Boolean dataFlowIn,Boolean dataFlowOut,Boolean alwaysAssigned,Boolean variableDeclared,Boolean readInside,Boolean writtenInside,Boolean readOutside,Boolean writtenOutside,Boolean unsafeAddressTaken)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GetVariableStyle(Dictionary`2 symbolMap,ISymbol symbol,SemanticModel model,ITypeSymbol type,Boolean captured,Boolean dataFlowIn,Boolean dataFlowOut,Boolean alwaysAssigned,Boolean variableDeclared,Boolean readInside,Boolean writtenInside,Boolean readOutside,Boolean writtenOutside,Boolean unsafeAddressTaken)
   at Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.GenerateVariableInfoMap(SemanticModel model,DataFlowAnalysis dataFlowAnalysisData,Dictionary`2 symbolMap)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.Analyzer.AnalyzeAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Also reported at https://developercommunity.visualstudio.com/content/problem/14869/extractmethodcoderefactoringprovider-encountered-a.html

### PR DESCRIPTION
**Pull request by agocke**
By design, when data flow analyzes local functions it does so devoid of
surrounding context and records possibly unassigned variables rather
than reporting a diagnostic. Thus, all captured variables are expected
to be marked unassigned during data flow analysis without reporting a
diagnostic.

However, reporting a diagnostic is not the only side effect of running
data flow analysis. By calling virtual methods data flow analysis
informs derived types of unassigned variables. While the diagnostic is
suppressed and recorded, currently the virtual method is still called.
This has negative consequences for region analysis, which considers
these calls as indications of variables flowing out of the given
region, which may not be the case for local functions.

This PR changes data flow analysis to only call the ReportUnassigned
virtual method if not inside a local function, excluding local functions
from all unassignment reporting.

Fixes #17165, #18347

**Customer scenario**

Extract method crashes when analyzing code that contains variables captured by
local functions.

**Bugs this fixes:**

Fixes #17165, #18347

**Workarounds, if any**

Don't ask for refactorings around these variables.

**Risk**

This is a code change to data flow analysis and could affect definite assignment for local functions,
but is mostly focused around code flow to region analysis, which is only used by extract method.

**Performance impact**

Low. No extra allocations, minimal extra logic.

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

Local functions were a new feature in C# 7 and there are known issues around region analysis.

**How was the bug found?**

Customer reported.

### CODE REVIEW

**Comment by agocke** [comment]
@sharwell @dotnet/roslyn-compiler This should be ready for review now.

**Comment by agocke** [comment]
cc @Pilchie about the fix for IDE bugs I mentioned.

**Comment by agocke** [comment]
test windows_debug_vs-integration_prtest please

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 1]
```diff
@@ -903,42 +903,47 @@ protected void CheckAssigned(Symbol symbol, SyntaxNode node)
...
 
+            ReportUnassigned(symbol, node, slot, skipIfUseBeforeDeclaration);
+        }
+
+        /// <summary>
+        /// Report a given variable as not definitely assigned.  Once a variable has been so
+        /// reported, we suppress further reports of that variable.
+        /// </summary>
+        protected virtual void ReportUnassigned(Symbol symbol, SyntaxNode node, int slot, bool skipIfUseBeforeDeclaration)
+            => ReportUnassignedHelper(symbol, node, slot, skipIfUseBeforeDeclaration: skipIfUseBeforeDeclaration);
```
Comment (sharwell) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: :bulb: Seems no need for named argument.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 2]
```diff
@@ -903,42 +903,47 @@ protected void CheckAssigned(Symbol symbol, SyntaxNode node)
...
+
+        private void ReportUnassignedHelper(Symbol symbol, SyntaxNode node, int slot, bool skipIfUseBeforeDeclaration)
+        {
+            if (slot <= 0) return;
```
Comment (sharwell) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: :bulb: Expand with braces

❔ Is slot 0 not the first argument or local variable for static methods?

Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: Slot 0 is a special bit that indicates reachability.

**Comment by agocke** [comment]
cc @VSadov

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: > Slot 0 is a special bit that indicates reachability.

Don't let @sharwell know that, else [he'll ask we use it to report unreachable expressions](https://github.com/dotnet/csharplang/issues/656)!

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 3]
```diff
@@ -903,43 +903,55 @@ protected void CheckAssigned(Symbol symbol, SyntaxNode node)
...
-            if (slot <= 0) return;
+            // If the symbol is captured by the nearest
+            // local function, record the read and skip the diagnostic
+            if ((object)GetNearestLocalFunctionOpt(currentMethodOrLambda) != null)
+            {
+                // If this is a constant, constants are always definitely assigned
+                // so we should skip reporting. This can happen in a local function
+                // where we use a constant before we actually visit its definition
+                // (since local function declarations are visited before other statements).
+                if (symbol is LocalSymbol local && local.IsConst)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: >if (symbol is LocalSymbol local && local.IsConst) [](start = 16, length = 49)

It is not clear why do we perform this check only when we are inside a local function. It looks like we used to do this regardless of context before.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 4]
```diff
@@ -903,43 +903,55 @@ protected void CheckAssigned(Symbol symbol, SyntaxNode node)
...
+                {
+                    return;
+                }
+                else if (IsCapturedInLocalFunction(slot))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: >IsCapturedInLocalFunction(slot) [](start = 25, length = 31)

We already called GetNearestLocalFunctionOpt, it looks like we could save some CPU cycles by calling IsCaptured directly rather than going through this helper.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 5]
```diff
@@ -903,43 +903,55 @@ protected void CheckAssigned(Symbol symbol, SyntaxNode node)
...
+                {
+                    RecordReadInLocalFunction(slot);
+                    return;
+                }
+            }
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: >} [](start = 12, length = 1)

Given the name of this function, I would expect us to return at the end of this ```if``` block.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 6]
```diff
@@ -903,43 +903,55 @@ protected void CheckAssigned(Symbol symbol, SyntaxNode node)
...
+        /// </summary>
+        protected virtual void ReportUnassigned(Symbol symbol, SyntaxNode node, int slot, bool skipIfUseBeforeDeclaration)
+            => ReportUnassignedHelper(symbol, node, slot, skipIfUseBeforeDeclaration);
 
-            // If this is a constant, constants are always definitely assigned
-            // so we should skip reporting. This can happen in a local function
-            // where we use a constant before we actually visit its definition
-            // (since local function declarations are visited before other statements).
-            if (symbol.Kind == SymbolKind.Local && ((LocalSymbol)symbol).IsConst)
+        private void ReportUnassignedHelper(Symbol symbol, SyntaxNode node, int slot, bool skipIfUseBeforeDeclaration)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: >ReportUnassignedHelper [](start = 21, length = 22)

It doesn't look like we are taking any advantage from having this helper method. Please merge it with ReportUnassigned.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.LocalFunctions.cs [hunk 7]
```diff
@@ -94,7 +94,7 @@ private void CheckIfAssignedDuringLocalFunctionReplay(Symbol symbol, SyntaxNode
                         // Local functions can "call forward" to after a variable has
                         // been declared but before it has been assigned, so we can never
                         // consider the declaration location when reporting errors.
-                        ReportUnassigned(symbol, node, slot, skipIfUseBeforeDeclaration: false);
+                        ReportUnassignedIfOutsideLocalFunction(symbol, node, slot, skipIfUseBeforeDeclaration: false);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.LocalFunctions.cs]: >ReportUnassignedIfOutsideLocalFunction [](start = 24, length = 38)

Are we not guaranteed to be inside a local function when we are here?

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowsInWalker.cs [hunk 8]
```diff
@@ -91,15 +91,20 @@ public override BoundNode VisitRangeVariable(BoundRangeVariable node)
             return null;
         }
 
-        protected override void ReportUnassigned(Symbol symbol, SyntaxNode node)
+        protected override void ReportUnassigned(Symbol symbol, SyntaxNode node, int slot, bool skipIfUseBeforeDeclaration)
         {
             // TODO: how to handle fields of structs?
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowsInWalker.cs]: >// TODO: how to handle fields of structs? [](start = 12, length = 41)

Is this TODO addressed now?

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowsOutWalker.cs [hunk 9]
```diff
@@ -249,20 +255,5 @@ protected override void ReportUnassignedOutParameter(ParameterSymbol parameter,
             }
             base.ReportUnassignedOutParameter(parameter, node, location);
         }
-
-        protected override void ReportUnassigned(FieldSymbol fieldSymbol, int unassignedSlot, SyntaxNode node)
-        {
-            if (!IsInside)
-            {
-                //  if the field access is reported as unassigned it should mean the original local 
-                //  or parameter flows out, so we should get the symbol associated with the expression
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowsOutWalker.cs]: >//  or parameter flows out, so we should get the symbol associated with the expression [](start = 16, length = 86)

It feels like we should preserve this comment.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowsOutWalker.cs [hunk 10]
```diff
@@ -232,13 +232,19 @@ public override BoundNode VisitQueryClause(BoundQueryClause node)
             return base.VisitQueryClause(node);
         }
 
-        protected override void ReportUnassigned(Symbol symbol, SyntaxNode node)
+        protected override void ReportUnassigned(Symbol symbol, SyntaxNode node, int slot, bool skipIfUseBeforeDeclaration)
         {
-            if (!_dataFlowsOut.Contains(symbol) && !(symbol is FieldSymbol) && !IsInside)
+            if (symbol.Kind == SymbolKind.Field)
+            {
+                symbol = GetNonFieldSymbol(slot);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowsOutWalker.cs]: >symbol = GetNonFieldSymbol(slot); [](start = 16, length = 33)

Should the base call be affected by this transformation?

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowsInWalker.cs [hunk 11]
```diff
@@ -91,15 +91,20 @@ public override BoundNode VisitRangeVariable(BoundRangeVariable node)
...
-            if (RegionContains(node.Span) && !(symbol is FieldSymbol))
+            if (symbol.Kind == SymbolKind.Field)
+            {
+                symbol = GetNonFieldSymbol(slot);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowsInWalker.cs]: >symbol = GetNonFieldSymbol(slot); [](start = 16, length = 33)

Should the base call be affected by this transformation?

File: src/Compilers/CSharp/Portable/FlowAnalysis/UnassignedVariablesWalker.cs [hunk 12]
```diff
@@ -48,26 +49,26 @@ private new HashSet<Symbol> Analyze(ref bool badRegion)
             return _result;
         }
 
-        protected override void ReportUnassigned(Symbol symbol, SyntaxNode node)
+        protected override void ReportUnassigned(Symbol symbol, SyntaxNode node, int slot, bool skipIfUseBeforeDeclaration)
         {
             // TODO: how to handle fields of structs?
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/UnassignedVariablesWalker.cs]: >// TODO: how to handle fields of structs? [](start = 12, length = 41)

Has this been addressed?

File: src/Compilers/CSharp/Portable/FlowAnalysis/UnassignedVariablesWalker.cs [hunk 13]
```diff
@@ -48,26 +49,26 @@ private new HashSet<Symbol> Analyze(ref bool badRegion)
...
             if (symbol.Kind != SymbolKind.Field)
             {
                 _result.Add(symbol);
             }
+            else
+            {
+                symbol = GetNonFieldSymbol(slot);
+                Debug.Assert((object)symbol != null);
+                _result.Add(symbol);
+                base.ReportUnassigned(symbol, node, slot, skipIfUseBeforeDeclaration);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/UnassignedVariablesWalker.cs]: >base.ReportUnassigned(symbol, node, slot, skipIfUseBeforeDeclaration); [](start = 16, length = 70)

It is not clear why the base call is done only in ```else``` block.

File: src/Compilers/CSharp/Portable/FlowAnalysis/UnassignedVariablesWalker.cs [hunk 14]
```diff
@@ -48,26 +49,26 @@ private new HashSet<Symbol> Analyze(ref bool badRegion)
...
+        protected override void ReportUnassigned(Symbol symbol, SyntaxNode node, int slot, bool skipIfUseBeforeDeclaration)
         {
             // TODO: how to handle fields of structs?
             if (symbol.Kind != SymbolKind.Field)
             {
                 _result.Add(symbol);
             }
+            else
+            {
+                symbol = GetNonFieldSymbol(slot);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/UnassignedVariablesWalker.cs]: >symbol = GetNonFieldSymbol(slot); [](start = 16, length = 33)

Should the base call be affected by this transformation?

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs [hunk 15]
```diff
@@ -19158,705 +19158,6 @@ public class Derived : Base
         }
 
         [Fact]
-        public void DefiniteAssignment001()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: >DefiniteAssignment001 [](start = 20, length = 21)

Please move the the test back here.

**Comment by AlekseyTs** [comment]
Done with review pass.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs (hunk 3 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: The comment is meant to describe this, but basically this can only happen in local functions. Otherwise, if you were to use a constant before visiting it you would get a use-before-declaration error and the definite assignment issue wouldn't be reported.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs (hunk 4 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: Yes, I think I'm duplicating some work here. I'll file a bug to refactor later, since I think this is slightly easier to show equivalence with the old code.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowsInWalker.cs (hunk 8 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowsInWalker.cs]: It features no more specific handling than it did before. So I would say it handles no more than it did before, but I don't know what this comment meant anyway -- it appears to me that this handles struct fields just fine.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs (hunk 15 above)
Comment (agocke) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: Why? It seems like they have nothing to do with codegen.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.LocalFunctions.cs (hunk 7 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.LocalFunctions.cs]: No, you could call another local function (or even the same local function, recursively) from inside a local function.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs (hunk 3 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: Ah, actually I think you're right -- this may be possible to hit outside of a local function as well. I will try to write a test for this.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs (hunk 5 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: I agree, I'll try to find a new name. We currently `ReportUnassigned` for all non-captured variables in local functions and I don't intend to change that behavior in this PR.

File: src/Compilers/CSharp/Portable/FlowAnalysis/UnassignedVariablesWalker.cs (hunk 13 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/UnassignedVariablesWalker.cs]: The non-field symbol override did not contain a base call. I can file a bug to look into whether this is the right decision, but I think this code is equivalent to the previous.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowsInWalker.cs (hunk 8 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowsInWalker.cs]: I've filed bug https://github.com/dotnet/roslyn/issues/20141 for this

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowsOutWalker.cs (hunk 9 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowsOutWalker.cs]: https://github.com/dotnet/roslyn/issues/20141 as above

File: src/Compilers/CSharp/Portable/FlowAnalysis/UnassignedVariablesWalker.cs (hunk 12 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/UnassignedVariablesWalker.cs]: https://github.com/dotnet/roslyn/issues/20141 as above

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowsOutWalker.cs [hunk 16]
```diff
@@ -232,13 +232,20 @@ public override BoundNode VisitQueryClause(BoundQueryClause node)
...
+        protected override void ReportUnassigned(Symbol symbol, SyntaxNode node, int slot, bool skipIfUseBeforeDeclaration)
         {
-            if (!_dataFlowsOut.Contains(symbol) && !(symbol is FieldSymbol) && !IsInside)
+            if (!IsInside)
             {
-                _dataFlowsOut.Add(symbol);
+                // If the field access is reported as unassigned it should mean the original local
+                // or parameter flows out, so we should get the symbol associated with the expression
+                var outSymbol = symbol.Kind == SymbolKind.Field ? GetNonFieldSymbol(slot) : symbol;
+                if (!_dataFlowsOut.Contains(outSymbol))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowsOutWalker.cs]: >if (!_dataFlowsOut.Contains(outSymbol)) [](start = 16, length = 39)

It looks like ```_dataFlowsOut``` is a HashSet, it feels redundant to call Contains before Add.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs (hunk 4 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: Yes, please open an issue to follow-up.

File: src/Compilers/CSharp/Portable/FlowAnalysis/UnassignedVariablesWalker.cs (hunk 13 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/UnassignedVariablesWalker.cs]: >  I can file a bug to look into whether this is the right decision, but I think this code is equivalent to the previous.

Please open an issue to follow up.

File: src/Compilers/CSharp/Portable/FlowAnalysis/UnassignedVariablesWalker.cs (hunk 14 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/UnassignedVariablesWalker.cs]: > Should the base call be affected by this transformation?

It doesn't look like you responded to this question.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 6).

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs (hunk 3 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: It turns out there are already a number of tests which test this: `FlowAnalysisTests.TestCaptured02` and `TestNullCoalescingWithConstNullLeft` for instance.

**Comment by agocke** [comment]
retest windows_debug_vs-integration_prtest please

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs [hunk 17]
```diff
@@ -19849,13 +19840,12 @@ static void Main(string[] args)
...
-            comp.VerifyEmitDiagnostics(
-                // (22,34): error CS0170: Use of possibly unassigned field 'I3'
+            comp.VerifyDiagnostics(
+                // (21,34): error CS0170: Use of possibly unassigned field 'I3'
                 //         System.Console.WriteLine(ss.I3);
-                Diagnostic(ErrorCode.ERR_UseDefViolationField, "ss.I3").WithArguments("I3").WithLocation(22, 34)
+                Diagnostic(ErrorCode.ERR_UseDefViolationField, "ss.I3").WithArguments("I3").WithLocation(21, 34)
             );
         }
-
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: Please restore the empty line between tests.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 9).

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 18]
```diff
@@ -903,43 +903,60 @@ protected void CheckAssigned(Symbol symbol, SyntaxNode node)
...
-        private void ReportUnassigned(Symbol symbol, SyntaxNode node, int? slotOpt, bool skipIfUseBeforeDeclaration = true)
+        private void ReportUnassignedIfNotCapturedInLocalFunction(Symbol symbol, SyntaxNode node, int slot, bool skipIfUseBeforeDeclaration = true)
         {
-            int slot = slotOpt ?? VariableSlot(symbol);
-            if (slot <= 0) return;
+            // If the symbol is captured by the nearest
+            // local function, record the read and skip the diagnostic
+            if ((object)GetNearestLocalFunctionOpt(currentMethodOrLambda) != null)
+            {
+                if (IsCapturedInLocalFunction(slot))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: >if (IsCapturedInLocalFunction(slot)) [](start = 16, length = 36)

This condition can be merged into the previous ```if```

**Comment by agocke** [comment]
@jaredpar For forwarding to escrow bar check. Not sure who I'm supposed to include.

**Comment by Pilchie** [comment]
I'm happy to support the scenario here - this is one of the IDE team's top reported vs-feedback issues, where Extract Method causes a "gold bar/non-fatal Watson"

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 19]
```diff
@@ -903,43 +903,57 @@ protected void CheckAssigned(Symbol symbol, SyntaxNode node)
...
-        private void ReportUnassigned(Symbol symbol, SyntaxNode node, int? slotOpt, bool skipIfUseBeforeDeclaration = true)
+        private void ReportUnassignedIfNotCapturedInLocalFunction(Symbol symbol, SyntaxNode node, int slot, bool skipIfUseBeforeDeclaration = true)
         {
-            int slot = slotOpt ?? VariableSlot(symbol);
-            if (slot <= 0) return;
+            // If the symbol is captured by the nearest
+            // local function, record the read and skip the diagnostic
+            if (IsCapturedInLocalFunction(slot))
+            {
+                RecordReadInLocalFunction(slot);
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: The method name says "Report" which I interpreted as non-mutating.  Yet this is apparently mutating by noting a read here.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs [hunk 20]
```diff
@@ -992,20 +1006,11 @@ private void ReportUnassigned(Symbol symbol, SyntaxNode node, int? slotOpt, bool
...
 
-        /// <summary>
-        /// Report a given variable as not definitely assigned.  Once a variable has been so
-        /// reported, we suppress further reports of that variable.
-        /// </summary>
-        protected virtual void ReportUnassigned(Symbol symbol,
-                                                SyntaxNode node) =>
-            ReportUnassigned(symbol, node, slotOpt: null);
-
         protected virtual void CheckAssigned(BoundExpression expr, FieldSymbol fieldSymbol, SyntaxNode node)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: This is another example:  A "Check" method is mutating now as well.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs (hunk 19 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: `ReportUnassigned` is meant to be interpreted as "report" to user. Ignoring the record, report almost always is mutating because it adds a diagnostic to a global bag.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs (hunk 20 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs]: `Check` has also always mutated state since it always indirectly called `ReportUnassigned`

**Comment by jaredpar** [comment]
CC @MeiChin-Tsai, @MattGertz for escrow approval. It's a cross cutting change: IDE scenario, mostly compiler change.

**Comment by MeiChin-Tsai** [comment]
approved. thx.

**Comment by MattGertz** [comment]
Approved by me.  @MeiChin-Tsai , will you take this one to JoC?

**Comment by MeiChin-Tsai** [comment]
Will do that, Matt.

**Comment by MeiChin-Tsai** [comment]
@MattGertz Will do that.

**Comment by MeiChin-Tsai** [comment]
@jaredpar Let me know when the fix is ready.

**Comment by MattGertz** [comment]
@MeiChin-Tsai I believe that Jared already took this one to JoC a few days ago and it was approved & merged,

**Comment by MeiChin-Tsai** [comment]
@MattGertz You are right. I saw that Agocke has merged it.
