### PR TITLE
Fix IDE diagnostics test framework to use DiagnosticAnalyzerService to compute diagnostics

### LINKED ISSUE #249: Fix IDE diagnostics/code fix test framework to use DiagnosticAnalyzerService to compute diagnostics rather than DiagnosticAnalyzerDriver
Ported from TFS WorkItem: <b>1114332</b>

------------------------------
<p>Our test framework for IDE diagnostics and fixes tests uses DiagnosticAnalyzerDriver directly to compute diagnostics. However, this in turn means that we don’t exercise the end-to-end test path of going via the DiagnosticAnalyzerService. Lot of recent bugs&nbsp;is a case where DiagnosticAnalyzerDriver does the right thing, but it’s caller&nbsp;has a bug in filtering logic&nbsp;and we end up with missing or wrong diagnostics in error list OR missing code fixes due to filtered diagnostics in IDE, though the same test passes fine with our unit test framework.</p>
<p>&nbsp;</p>
<p>I guess we need to fix up at least&nbsp;<a id=db7d18e25e2715bb class=t href="http://index/Roslyn.Services.Editor.UnitTests/R/db7d18e25e2715bb.html"><u><font color="#0066cc">DiagnosticProviderTestUtilities</font></u></a> type<a href="http://index/Roslyn.Services.Editor.UnitTests/R/db7d18e25e2715bb.html">,</a> not sure if there are other places too</p>

------------------------------

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #249 : Fix IDE diagnostics test framework to use DiagnosticAnalyzerService to compute diagnostics rather than DiagnosticAnalyzerDriver.

This change serves multiple purposes:
1) Makes our test framework consistent with the IDE scenario in fetching diagnostics. We have missed out on multiple regressions where the core IDE DiagnosticAnalyzerDriver does the right thing and hence the tests pass, but the DiagnosticService in IDE does additional filtering and certain diagnostics are not reported in VS. This change should avoid such bugs.
2) Enable testing for diagnostics V2 engine work that JohnHamby is doing to merge IDE and compiler analyzer drivers. For this engine, there is no IDE driver and hence existing IDE diagnostics tests can't be run. This change should enable running IDE diagnostic tests on V2 engine.
3) Move a whole bunch of test only code in DiagnosticAnalyzerService_Test.cs into the test layer.

@heejaechang @JohnHamby you may want to take a look as this might affect you.

### CODE REVIEW

File: src/EditorFeatures/Test/Diagnostics/TestDiagnosticAnalyzerService.cs [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+
+using System;
+using System.Collections.Immutable;
+using System.Linq;
+using Microsoft.CodeAnalysis.Diagnostics.Log;
+using Roslyn.Utilities;
+
+namespace Microsoft.CodeAnalysis.Diagnostics
+{
+    internal sealed class TestDiagnosticAnalyzerService : DiagnosticAnalyzerService
```
Comment (mavasani) [inline src/EditorFeatures/Test/Diagnostics/TestDiagnosticAnalyzerService.cs]: @JohnHamby all the IDE diagnostic analyzer tests would now use this test only implementation of DiagnosticAnalyzerService. I would suggest that if you want to locally verify functionality changes for your v2 engine work, you can turn on the IDE v2 Engine in the constructors here and all tests should use the v2 engine.

One category of tests that will fail are those that supply a custom onAnalyzerException delegate. CompilationWithAnalyzers has no public API support to accept such an handler, and currently just logs all analyzer exception diagnostics here (http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/CompilationWithAnalyzers.cs,53737f78dfb37533,references) and returns them as part of all diagnostics. We would eventually need a public API change to take this delegate as a parameter.

**Comment by JohnHamby** [comment]
I like these changes very much. Thanks Manish!

**Comment by heejaechang** [comment]
:+1: nice.
