### PR TITLE
Prevent SqlConnection from being held past an async boundary

### LINKED ISSUE #22650: Unbounded SQLite instances/connections contributing to OOM failures
**Version Used**: 15.3

Currently we fail to bound the number of instances of the following types which are created at runtime:

* `SQLitePCL.sqlite3`
* `Microsoft.CodeAnalysis.SQLite.Interop.SqlConnection`

Associated with these types is a pair of allocations in the native heap. One is 64,000 bytes, and the other is 425,600 bytes. Ordinarily, this would not be a problem. However, it appears that it is possible for the number of connections to grow over time, resulting in overwhelming memory pressure stemming from the (mis-)use of SQLite. The following image shows one such case:

image

After fixing this for 15.5, we should port the fix to 15.4 servicing.

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #22650

Rather than place a hard cap on the number of connections, I updated the code to ensure database connections are only held for the duration where they are actually in use.

CC: @dotnet/roslyn-ide @heejaechang @CyrusNajmabadi @onyxmaster

**Customer scenario**

A customer opens a large solution with 15.3 or 15.4. The IDE is at high risk for encountering OOM errors.

**Bugs this fixes:**

#22650 
[DevDiv 507560](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/507560)

**Workarounds, if any**

None

**Risk**

Relatively low.

**Performance impact**

For scenarios where database writes to disk are slow, performance is improved by allowing database connection sharing.

**Is this a regression from a previous update?**

Yes.

**Root cause analysis:**

As a best guess:

1. Our drives are faster, so we didn't observe the stalls locally (a local reproducer would mean we could sample the native allocations at runtime to get call stacks, as opposed to looking at a heap dump post-mortem)
2. The memory allocation impacting the process was a native memory allocation, which we were aware in statistics but did not have insight into the cause (we now know to treat the managed `SqlConnection` and `sqlite3` objects as heavier to account for this, similar to what we already did for `MemoryMappedView`)

**How was the bug found?**

The 425600 byte allocation pattern was discovered by Lee Culver on the .NET Fundamentals team. Text contents in some of these blocks made me suspicious of SQLite, leading me to search for "425600 SQLite". The value appeared twice in interesting results:

https://forums.plex.tv/discussion/256008/pms-crashes-randomly-under-load

> ERROR - SQLITE3:1B3E069A, 7, failed to allocate 425600 bytes of memory

http://iamoracleadmin.blogspot.com/p/sqlite-cheat-sheet.html

> Largest Allocation: 425600 bytes

I then used PerfView to review the number of connections present in the managed heap, and found it exactly matched the number of native allocations.

**Test documentation updated?**

N/A

### CODE REVIEW

**Comment by heejaechang** [comment]
oops button clicked by mistake sorry.

**Comment by heejaechang** [comment]
by the way, how many connections where there? surprised even though connections were held cross async, that lead to that many concurrent connectinos to be needed.

**Comment by sharwell** [comment]
> I think the pool must be still upper bounded

The pool has a soft upper bound of the number of managed threads. I was actually originally planning to add a second commit to add a hard limit on the pool itself, but realized there's no longer a code path to do anything interesting there.

**Comment by sharwell** [comment]
> by the way, how many connections where there?

The issue was found in a heap that had 2740. The screenshot for the issue was another heap with 3429. I've seen OOM heap dumps with ~900 all the way up to a winner of ~7000.

**Comment by heejaechang** [comment]
I still don't see why upper limit is bad? if you really don't want, put crash there so that if limit is upper than we expect, we explicitly crash VS.

**Comment by heejaechang** [comment]
hmmm.. still can't understand how there can be 7000 pooled connections. are we having thread starvation issue again?

**Comment by sharwell** [comment]
@heejaechang There is no need to crash VS since it may recover from such a situation if the user waits longer. The telemetry team has new red flags in place and will alert us if they see low memory conditions with a large number of these instances.

**Comment by sharwell** [comment]
> hmmm.. still can't understand how there can be 7000 pooled connections. are we having thread starvation issue again?

We don't allow reads while writes are pending. Previously the read operations would claim a connection before waiting (asynchronously) for pending operations to complete. Now read operations return the connection to the pool before waiting.

**Comment by Pilchie** [comment]
In other words, when FAR starts a per-document search, if the SyntaxTreeIndex is being written, then there will be a connection per document?

File: src/Workspaces/Core/Desktop/Workspace/SQLite/Interop/SqlConnection.cs [hunk 1]
```diff
@@ -53,7 +53,7 @@ public static SqlConnection Create(IPersistentStorageFaultInjector faultInjector
 
             // Enable shared cache so that multiple connections inside of same process share cache
             // see https://sqlite.org/threadsafe.html for more detail
-            var flags = OpenFlags.SQLITE_OPEN_CREATE | OpenFlags.SQLITE_OPEN_READWRITE | OpenFlags.SQLITE_OPEN_SHAREDCACHE;
+            var flags = OpenFlags.SQLITE_OPEN_CREATE | OpenFlags.SQLITE_OPEN_READWRITE | OpenFlags.SQLITE_OPEN_NOMUTEX | OpenFlags.SQLITE_OPEN_SHAREDCACHE;
```
Comment (Pilchie) [inline src/Workspaces/Core/Desktop/Workspace/SQLite/Interop/SqlConnection.cs]: Why this flag?

**Comment by heejaechang** [comment]
I don't understand, if we are sure connection won't be pooled to 7000, then we should put that assumption in the code, if we are not sure, we should guard from it. otherwise, we are just hiding.

**Comment by heejaechang** [comment]
current implementation, if we are hit 100 and never hit more than 20, the pool still hold onto 100. improvement on pool to do eviction and etc, we should remove upper limit when we implement that. no reason we don't do since we might do the eviction in the future.

...

also, I still can't understand there is 7000 connection pooled. are we sure we are not leaking something?

**Comment by sharwell** [comment]
@Pilchie 

> In other words, when FAR starts a per-document search, if the SyntaxTreeIndex is being written, then there will be a connection per document?

I don't know enough about the reasons why we read from the database to answer this directly. However, I do know two things:

1. I'd like to improve the overall cache behavior to make reads not dependent on flushing writes to disk
2. SyntaxTreeIndex has shown up as a red flag recently (#22605)

> I don't understand, if we are sure connection won't be pooled to 7000, then we should put that assumption in the code, if we are not sure, we should guard from it. otherwise, we are just hiding.

There are some edge cases which make it very difficult to predict the hard upper bound. I'm willing to implement telemetry and perhaps a time-based pool eviction policy so we are aware of regressions, but to me it's not worth causing a user to crash (coded assertions) or severe performance degradation (SQL connections getting created due to exceeding pool limits).

**Comment by heejaechang** [comment]
``` severe performance degradation (SQL connections getting created due to exceeding pool limits). ```

are you sure this cause severe performance degradation. currently we have evidence that pooling cause severe performance degradation - oom, but not the other way?

**Comment by heejaechang** [comment]
by the way, any pool or cache that doesn't have upper limit is I think code smell.

**Comment by sharwell** [comment]
> by the way, any pool or cache that doesn't have upper limit is I think code smell.

I agree. But one step at a time is good, especially on a rush change like this.

**Comment by onyxmaster** [comment]
The `nomutex` flag should be beneficial in terms of performance and allow for cross-thread connection migration when lock is held on this connection, but is it needed for shared cache scenario?

As for original case -- when developing #22340 I had file logging enabled, and I've seen a large chunk of connections running amok (I had a log file for each pid+thread_id combo on connection open, so I noticed lots of files quickly appearing), but it appears that having a fast CPU/disk prevents process death. I didn't report it in the #22340 because I believed it's the "normal" mode of operation and I had this even without proposed locking changes.

With the connection pool limit, I'd put a cap on a connection pool. Crashing is of course not an option, but logging (not sure what policy Roslyn have for these kinds of errors) + wait queue/reverting to non-pooled approach looks fine to me (yes, it will slow down, and it would be another case to solve, but it's still an improvement over crashing).

**Comment by sharwell** [comment]
> The `nomutex` flag should be beneficial in terms of performance and allow for cross-thread connection migration when lock is held on this connection, but is it needed for shared cache scenario?

Given that we use more than one connection object, it appears `nomutex` is the behavior we always coded for. I'm not sure why shared cache has been enabled - it appears to be more relevant for embedded applications. However, its primary impact involves cases with multiple writers which appears to be "less common" (though not impossible) with our code.

> With the connection pool limit, I'd put a cap on a connection pool.

There is a soft cap in place equivalent to the maximum number of active threads concurrently accessing the database. Given that the threads are generally within the .NET thread pool, this is loosely related to the number of logical processors on the machine, but can vary a bit from that. I would not expect this to ever exceed the number of logical processors times two, and plan to verify this through telemetry.

**Comment by heejaechang** [comment]
shared cache is beneficial to us since it doesn't cause each connection to be so expansive.
https://sqlite.org/sharedcache.html

**Comment by sharwell** [comment]
@heejaechang 

> shared cache is beneficial to us since it doesn't cause each connection to be so expansive.

Shared cache also causes concurrent write attempts on separate connection objects to block on each other. I'm hoping this is rare but we should be watching to see if performance reports deviate from expectation. For now it is acting as a secondary safeguard against runaway memory problems due to connection pool growing (and for the 15.5 Preview 1 release, will be the only remediation in place).

**Comment by heejaechang** [comment]
by the way, with exclusive mode and shared cache, we might no longer need to wait for writer since only 1 process uses the db and doesn't require file system or mutex to communicate db's state with other process or other connection.

**Comment by heejaechang** [comment]
not sure how write can't be serialized. I think WAL basically does that for us. before it was issue since multiple process can write to db, but I believe that is no longer possible?

**Comment by heejaechang** [comment]
anyway, okay, if other people are okay with not having upper limit.

**Comment by onyxmaster** [comment]
Shared cache is a must if #22340 is going to be used, because without it exclusive locking mode would prevent multiple threads from accessing database at all (only the first connection that attempted a write would have access).

File: src/Workspaces/Core/Desktop/Workspace/SQLite/Interop/SqlConnection.cs (hunk 1 above)
Comment (sharwell) [reply src/Workspaces/Core/Desktop/Workspace/SQLite/Interop/SqlConnection.cs]: This flag says we are only using connection instances on one thread at a time. We were already doing this, but since we didn't specify the flag the database fell back to SQLITE_OPEN_FULLMUTEX which added a second layer of locks.

File: src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorage.Accessor.cs [hunk 2]
```diff
@@ -60,25 +60,31 @@ public Accessor(SQLitePersistentStorage storage)
...
+                    TDatabaseId dataId;
                     using (var pooledConnection = Storage.GetPooledConnection())
                     {
-                        var connection = pooledConnection.Connection;
-                        if (TryGetDatabaseId(connection, key, out var dataId))
-                        {
-                            // Ensure all pending document writes to this name are flushed to the DB so that 
-                            // we can find them below.
-                            await FlushPendingWritesAsync(connection, key, cancellationToken).ConfigureAwait(false);
+                        haveDataId = TryGetDatabaseId(pooledConnection.Connection, key, out dataId);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorage.Accessor.cs]: nice.

**Comment by Pilchie** [comment]
> There is a soft cap in place equivalent to the maximum number of active threads concurrently accessing the database. Given that the threads are generally within the .NET thread pool, this is loosely related to the number of logical processors on the machine, but can vary a bit from that. I would not expect this to ever exceed the number of logical processors times two, and plan to verify this through telemetry.

In practice we regularly see bugs which cause threadpool starvation, and the CLRs hill-climbing algorithm adds many more threads.  IIRC, @jasonmalinowski saw several with counts as high as 700 threads when something used an AsyncLazy without a sync path.

File: src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorage.cs [hunk 3]
```diff
@@ -233,6 +233,14 @@ private void CloseWorker()
             }
         }
 
+        /// <summary>
+        /// Gets an <see cref="SqlConnection"/> from the connection pool, or creates one if none are available.
+        /// </summary>
+        /// <remarks>
+        /// Database connections have a large amount of overhead, and should be returned to the pool when they are no
+        /// longer in use. In particular, make sure to avoid letting a connection lease cross an <see langword="await"/>
+        /// boundary, as it will prevent code in the asynchronous operation from using the existing connection.
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorage.cs]: d'oh!

**Comment by CyrusNajmabadi** [comment]
> I'd like to improve the overall cache behavior to make reads not dependent on flushing writes to disk

Any thoughts on how to do that?

**Comment by CyrusNajmabadi** [comment]
> Given that we use more than one connection object, it appears nomutex is the behavior we always coded for. I'm not sure why shared cache has been enabled - it appears to be more relevant for embedded applications. However, its primary impact involves cases with multiple writers which appears to be "less common" (though not impossible) with our code.

The original reason was because of this clause:

> In version 3.5.0 (2007-09-04), shared-cache mode was modified so that the same cache can be shared across an entire process rather than just within a single thread. Prior to this change, there were restrictions on passing database connections between threads. Those restrictions were dropped in 3.5.0 update. This document describes shared-cache mode as of version 3.5.0.

thus, the thinking was that all our connections could "share a single data and schema cache."  It seemed like a simple improvement without a downside at the time.

**Comment by CyrusNajmabadi** [comment]
> In practice we regularly see bugs which cause threadpool starvation, and the CLRs hill-climbing algorithm adds many more threads. IIRC, @jasonmalinowski saw several with counts as high as 700 threads when something used an AsyncLazy without a sync path.

Yes.  This is still my primary concern with the design around how i did the original sqlite work.  Right now we have blocking IO in our threadpool threads, and that can certainly lead to some awful hill climbing behavior.  My ideal would be that we move the blocking IO entirely off the threadpool to keep it behaving nicely.  That would also allow us to move to a single connection object for writing.  Reading can also be done in a similar manner.  Either reusing the same thread, or utilizing a second thread for that purpose.  Given that reads need to currently flush writes (of the specific queue, not all writes in general), it probably makes sense to have all reading/writing done by a single thread so that no coordination between a read thread and write thread needs to happen.  

IMO, this should not be difficult to do, and would be the cleaner design overall.  It would come at the cost of a thread.  But at hte benefit of a massively simpler model, and no worries about connections, locking, sharing, etc.   Effectively, we'd be using sqlite in single-thread mode, and using that to side step all these concurrency issues.

**Comment by onyxmaster** [comment]
Actually the #22340 removes about 90% of flushes with "synchronous" set to "normal". The only real place where flushing takes place is WAL checkpointing, but this [can be run on a separate thread](https://www.sqlite.org/wal.html#checkpointing).

**Comment by jasonmalinowski** [comment]
> Right now we have blocking IO in our threadpool threads, and that can certainly lead to some awful hill climbing behavior.

On the list of terrible sins, IO on the threadpool is bad, but blocking a thread pool thread on another thread (or worse: other scheduled thread pool work) is far worse since you can starve things pretty easily. That's how we've hit the hundreds-of-threads bugs. I haven't caught up on this full thread yet, but don't replace blocking IO with blocking on other threadpool work. :-)

**Comment by sharwell** [comment]
> In practice we regularly see bugs which cause threadpool starvation, and the CLRs hill-climbing algorithm adds many more threads. 

These cases are rare compared to the set of users impacted by this bug. If a subset of users continue to see large numbers of connections after this change, we'll be alerted by Adrian's team to the extent (frequency and severity).

> Yes. This is still my primary concern with the design around how i did the original sqlite work. ...

I'll keep this in mind when looking at alternative approaches, subject to two conditions:

1. If the work here plus the work from @onyxmaster means SQLite is no longer showing up on perf/reliability reports, then I'll skip it since there is other work to do
2. It would be for 15.6 since it's a much broader change

**Comment by CyrusNajmabadi** [comment]
>On the list of terrible sins, IO on the threadpool is bad, but blocking a thread pool thread on another thread (or worse: other scheduled thread pool work) is far worse since you can starve things pretty easily. That's how we've hit the hundreds-of-threads bugs. I haven't caught up on this full thread yet, but don't replace blocking IO with blocking on other threadpool work. 😄

My suggestion is not to block a threadpool thread on another thread.  There would be no blocking in my model *except* on the dedicated sqlite thread.  

i.e. you have one new thread that just sits in a loop waiting for work.  When it gets work it waits up and performs it.  (It may delay a bit so it can batch work for efficiency reasons).  

Then, you have our normal threadpool threads that need to read/write data from the persistence layer.  They're already callign through async APIs.  When their calls come in, they enqueue their work to the sqlite IO thread, *providing a TCS to represent the work*.  They can then just return that TCS's Task, and can yield immediately.  Importantly, the threadpool threads never are waiting/blocking on the sqlite IO thread.  The sqlite IO thread will block on sqlite doing it's work.  But it's all limited to that single thread, which no other threads should block on.

**Comment by CyrusNajmabadi** [comment]
> I'll keep this in mind when looking at alternative approaches, subject to two conditions:

Absolutely :)  I completely agree with that.

If you do run into issues in the future, let me know.  If i have time, i'd be happy to contribute a PR.

**Comment by heejaechang** [comment]
just curious why we need write flush before read? is it because 2 connections can't see changes done by other connection? doesn't shared connection remove that issue? I am just confused on what is SQLite role on coordinating transactions and read/write?

this is weird requirement for db to enforce to flush all writes (which already happened and done to SQLite for the users point of view) before reading. that seems something SQLite should take care.

**Comment by CyrusNajmabadi** [comment]
> just curious why we need write flush before read? 

We're flushing the queue that *precedes* sqlite.  We're not flushing sqlite itself.  

Basically, for performance reasons, we want to batch up writes.  i.e. we may get 1k write requests in a quarter second.  Instead of doing 1k inserts into sqlite, we will batch and do one insert.  However, because we insert that batching delay, it's possible for a read to come in while we're waiting.  The read needs to see the write (and we test for this).

Now, to make things efficient, a read does not cause all pending writes to be flushed into sqlite.  It only causes writes *of that key that is being read* to be flushed.

**Comment by CyrusNajmabadi** [comment]
> SQLite role on coordinating transactions and read/write?

sqlite actually doesn't coordinate anything.  it acts completely as an atomic store of data.  But we have a layer that wraps it to improve performance.  Note: that layer is optional, and can be removed *if* we find that sqlite perf is good enough.

However, when i tested (and even with WAL) it was not fast enough.  An easy test was simply to remove the buffering layer, remove the DB, and then just load roslyn.sln.  With the buffering layer, we could produce all data for roslyn.sln and write it to sqlite in roughly two minutes on my box.  Without it, it took more like 15 minutes due to hundreds of K of writes that had to happen (with each write going through teh entire sqlite resiliency stack).

**Comment by heejaechang** [comment]
ah, I see so that flush is our own cache. esent had that cache itself so we didn't need to do such thing. it put changes in memory cache and then journals and then db.

I guess SQLite doesn't have that kind of mode? I think it might have one.

**Comment by CyrusNajmabadi** [comment]
> It put changes in memory cache and then journals and then db.
> I guess SQLite doesn't have that kind of mode? I think it might have one.

The problem was simply that it was effectively 100s of K of transactions.  Each write by some component into the persistence layer needed the full cost of being handled by sqlite properly.  A single transactoin that inserts 10k rows is way better than 10k transactions that insert one row each.

Even with WAL that remains true.  If there's a way to configure sqlite to make it the same, then by all means switch :)   But i could find nothing that would give the same perf.

--

To repeat: i would love to remove the buffering layer :)   it's just added complexity for a perf win.  If we can get the perf win without it, be my guest :D

**Comment by heejaechang** [comment]
I searched a bit and looks like what you did was the recommendation. :)

**Comment by sharwell** [comment]
@heejaechang Rebased this on dev15.4.x, and included #21532.

@jasonmalinowski This should be the first PR we were after.

**Comment by heejaechang** [comment]
I think we should bring this too (https://github.com/dotnet/roslyn/pull/22340)

**Comment by sharwell** [comment]
@heejaechang After this is merged, we will rebase #22340 and bring it in as a separate change.

**Comment by onyxmaster** [comment]
A word of caution. It appears that the problems I encountered with #22340 are not related to exclusive locking, they are related with shared cache.

With shared cache enabled, VS sometimes crashes (stacktrace below), with SQLite returning [`SQLITE_LOCKED`](https://sqlite.org/rescode.html#locked), which is an [`SQLITE_BUSY`](https://sqlite.org/rescode.html#busy) counterpart. While the `busy` case is handled in many places in the code, the `locked` one is not.

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: Microsoft.CodeAnalysis.SQLite.Interop.SqlException: database table is locked: StringInfo1
database table is locked
   at Microsoft.CodeAnalysis.SQLite.Interop.SqlConnection.Throw(sqlite3 handle, Result result)
   at Microsoft.CodeAnalysis.SQLite.SQLitePersistentStorage.TryFetchStringTable(SqlConnection connection)
   at Microsoft.CodeAnalysis.SQLite.SQLitePersistentStorage.BulkPopulateProjectIds(SqlConnection connection, Project project, Boolean fetchStringTable)
   at Microsoft.CodeAnalysis.SQLite.SQLitePersistentStorage.TryGetDocumentDataId(SqlConnection connection, Document document, String name, Int64& dataId)
   at Microsoft.CodeAnalysis.SQLite.SQLitePersistentStorage.DocumentAccessor.TryGetDatabaseId(SqlConnection connection, ValueTuple`2 key, Int64& dataId)
   at Microsoft.CodeAnalysis.SQLite.SQLitePersistentStorage.Accessor`3.<ReadStreamAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.FindSymbols.SyntaxTreeIndex.<PrecalculatedAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.FindSymbols.SyntaxTreeIndex.<PrecalculateAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<>c__DisplayClass32_1`1.<<RunAnalyzersAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<GetOrDefaultAsync>d__34`2.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception)
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService+WorkCoordinator+IncrementalAnalyzerProcessor+<GetOrDefaultAsync>d__34`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService+WorkCoordinator+IncrementalAnalyzerProcessor+<GetOrDefaultAsync>d__34`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService+WorkCoordinator+IncrementalAnalyzerProcessor+<GetOrDefaultAsync>d__34`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], Microsoft.CodeAnalysis.Features, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<GetOrDefaultAsync>d__34`2<System.__Canon,System.__Canon> ByRef)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService+WorkCoordinator+IncrementalAnalyzerProcessor.GetOrDefaultAsync[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon, System.Func`3<System.__Canon,System.Threading.CancellationToken,System.Threading.Tasks.Task`1<System.__Canon>>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService+WorkCoordinator+IncrementalAnalyzerProcessor+<RunAnalyzersAsync>d__32`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService+WorkCoordinator+IncrementalAnalyzerProcessor+<GetOrDefaultAsync>d__34`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService+WorkCoordinator+IncrementalAnalyzerProcessor+<>c__DisplayClass32_1`1+<<RunAnalyzersAsync>b__0>d[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.TodoComments.TodoCommentIncrementalAnalyzer+<AnalyzeSyntaxAsync>d__7.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1[[System.Collections.Immutable.ImmutableArray`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].TrySetResult(System.Collections.Immutable.ImmutableArray`1<System.__Canon>)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Collections.Immutable.ImmutableArray`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].SetResult(System.Collections.Immutable.ImmutableArray`1<System.__Canon>)
   at Microsoft.CodeAnalysis.Editor.Implementation.TodoComments.TodoCommentIncrementalAnalyzer+<CreateItemsAsync>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   at Microsoft.CodeAnalysis.TextDocumentState+<GetTextAsync>d__30.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   at Microsoft.CodeAnalysis.TextDocumentState+<GetTextAndVersionAsync>d__37.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   at Microsoft.CodeAnalysis.RecoverableTextAndVersion+<GetValueAsync>d__14.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TrySetResult(System.__Canon)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SetResult(System.__Canon)
   at Microsoft.CodeAnalysis.Host.RecoverableWeakValueSource`1+<GetValueAsync>d__16[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by sharwell** [comment]
@onyxmaster Sounds like I need to bring #21800 back as well, and then update it to treat BUSY and LOCKED the same way.

**Comment by sharwell** [comment]
This is now updated to include #21800. I then modified the two locations which handle SQLITE_BUSY to also handle SQLITE_LOCKED as a second return value with the same impact on our code.

File: src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorage_StringIds.cs [hunk 4]
```diff
@@ -12,23 +12,34 @@ internal partial class SQLitePersistentStorage
...
+                        // we want.  we don't want the strings we've allocated from the DB to be what
+                        // we hold onto.  We'd rather hold onto the strings we get from sources like
+                        // the workspaces.  This helps avoid unnecessary string instance duplication.
+                        _stringToIdMap.TryAdd(value, id);
+                    }
                 }
+
+                return true;
+            }
+            catch (SqlException e) when (e.Result == Result.BUSY || e.Result == Result.LOCKED)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorage_StringIds.cs]: I'm a little nervous about this.  Do we need to make the change that causes these 'locked' errors to start happening.  What gain are we getting to warrant it?

My specific concern is that this now means that many more sql calls may have to be protected from locked errors, where we didn't have to worry about that before.  There may be more places that are missing that may end up leading to actual application errors in the wild.

Comment (sharwell) [reply src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorage_StringIds.cs]: My understanding is the BUSY and LOCKED are similar, and the one getting reported depends on the current connection configuration. The original configuration produced BUSY errors (which we saw in Watson), but the change to use a shared and exclusive locks (required for follow-up work) changed a subset of those cases to return LOCKED instead.

Comment (onyxmaster) [reply src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorage_StringIds.cs]: @CyrusNajmabadi I'd like to note that `busy` states are almost the same as `locked`, so the argument about unknown places in code that may fail are relevant to the `busy`.

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Desktop/Workspace/SQLite/SQLitePersistentStorage_StringIds.cs]: If they are effectively 1:1, then i'm ok with things.  My concern was that locked might show up in different places where 'busy' woudl not have.  If you guys are convinced that that's not an issue, then i'm def ok with this then :)  Thanks!

**Comment by onyxmaster** [comment]
Minor note: the #22340 [no longer proposes](https://github.com/dotnet/roslyn/pull/22340#issuecomment-336345097) the use of exclusve locking (and dependence on shared cache), so at least a part of the discussion might need reconsideration.

**Comment by natidea** [comment]
Approved to merge via [507562](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/507562)
