### PR TITLE
Fix nullable walker cycle

### LINKED ISSUE #64599: Recursive lambda reference crashes nullable analysis
**Version Used**: main (8 Oct 2022)

**Steps to Reproduce**:

```cs
#nullable enable
using System;
class Program
{
    public static void Main(string[] args)
    {
        var lam = ([A(nameof(lam))] int x) => { };
    }
}
[AttributeUsage(AttributeTargets.Parameter)]
class A : Attribute
{
    public A(string _) {}
}
```

(SharpLab demo of this is not particularly useful as it crashes without giving any errors.)

Similar bug can be reproduced for [lambda default parameters](https://github.com/dotnet/roslyn/issues/62485):

```cs
#nullable enable
using System;
class Program
{
    public static void Main(string[] args)
    {
        var lam = (Delegate d = lam) => { };
    }
}
```

**Expected Behavior**:

```
(6,37): error CS0841: Cannot use local variable 'lam' before it is declared
```

**Actual Behavior**:

Compiler crashes with `StackOverflowException` when nullability is enabled. The `NullableWalker` tries to resolve type of `var lam` which in turn invokes another `NullableWalker` on the same expression, leading to an infinite cycle.

### PR DESCRIPTION
**Pull request by jjonescz**
Fixes #64599.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 1]
```diff
@@ -2846,6 +2846,14 @@ private bool TryGetReturnType(out TypeWithAnnotations type, out FlowAnalysisAnno
         public override BoundNode? VisitLocal(BoundLocal node)
         {
             var local = node.LocalSymbol;
+
+            // Avoid cycles in nullable analysis.
+            if ((local as SourceLocalSymbol)?.IsVar == true && local.ForbiddenZone?.Contains(node.Syntax) == true)
```
Comment (Youssef1313) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:2851]: This is just a stylistic suggestion.

```suggestion
            if (local is SourceLocalSymbol { IsVar: true } && local.ForbiddenZone?.Contains(node.Syntax) == true)
```

Comment (jjonescz) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Thanks.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 2]
```diff
@@ -2846,6 +2846,14 @@ private bool TryGetReturnType(out TypeWithAnnotations type, out FlowAnalysisAnno
         public override BoundNode? VisitLocal(BoundLocal node)
         {
             var local = node.LocalSymbol;
+
+            // Avoid cycles in nullable analysis.
+            if (local is SourceLocalSymbol { IsVar: true } && local.ForbiddenZone?.Contains(node.Syntax) == true)
+            {
+                SetResult(node, TypeWithState.ForType(node.Type), LvalueResultType, isLvalue: true);
```
Comment (jjonescz) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:2853]: I'm not entirely sure what to call here. I don't really care for the result of the nullable analysis since this is an erroneous case. I just want to end the visit early.

Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:2853]: The lvalue state seems incorrect. Perhaps call `SetResult(node, TypeWithState.ForType(node.Type));` instead.

Comment (jjonescz) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:2853]: Alright, such overload does not exist; but what about this? 9e2cb23a6b49d6dce925fc3536057d3c9830942c

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 3]
```diff
@@ -156450,5 +156450,29 @@ public class C
                 Diagnostic(ErrorCode.ERR_NoSuchMember, "B").WithArguments("S", "B").WithLocation(12, 24)
                 );
         }
+
+        [Fact, WorkItem(64599, "https://github.com/dotnet/roslyn/issues/64599")]
+        public void LambdaNullabilityCycle()
+        {
+            var source = """
+using System;
```
[the remark this answers is not in the document]
Comment (jjonescz) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:156458]: Good catch, thanks. Added: 5a0b4ad95f0e5c3de96c62e9ecaec1b01a00beaf

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 2 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Sorry, I meant `SetResultType` rather than `SetResult`: 
```
SetResultType(node, TypeWithState.ForType(node.Type));`
```

Comment (jjonescz) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Oh, right, that makes sense. Changed: 75de5a29d374f2bffc25a99a01784b58a866f6ab

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 4]
```diff
@@ -2846,6 +2846,14 @@ private bool TryGetReturnType(out TypeWithAnnotations type, out FlowAnalysisAnno
         public override BoundNode? VisitLocal(BoundLocal node)
         {
             var local = node.LocalSymbol;
+
+            // Avoid cycles in nullable analysis.
+            if (local is SourceLocalSymbol { IsVar: true } && local.ForbiddenZone?.Contains(node.Syntax) == true)
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:2851]: Can we document how exactly this helps avoid cycles?

Comment (jjonescz) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:2854]: Good idea, added: ae067f41afe43f44aa062bf8c31178b112e060ed

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 5]
```diff
@@ -2846,6 +2846,17 @@ private bool TryGetReturnType(out TypeWithAnnotations type, out FlowAnalysisAnno
         public override BoundNode? VisitLocal(BoundLocal node)
         {
             var local = node.LocalSymbol;
+
+            // Ignore var self-references (e.g., the RHS of `var x = x;`) to avoid cycles.
+            // While inferring the type of a more complex construct (like lambda),
+            // nullability analysis could be triggered against a reference of the local being inferred,
+            // querying its type and hence starting the same type inferrence recursively.
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:2853]: >inferrence [](http://example.com/codeflow?start=66&length=10)

"inference"

Comment (jjonescz) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Thanks. Fixed: 38d32fb324678f3d601df4b30d8f62d76bc1d790

**Review by cston — APPROVED** [review]

**Review by 333fred — APPROVED** [review]
