### PR TITLE
Fix early attribute decoding when an argument is interpolated string

### LINKED ISSUE #64605: Obsolete-Attribute with interpolated string as message does not raise warnings
**Version Used**: 
Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.3.3

Microsoft (R) Visual C# Compiler Version 4.3.0-3.22423.10 (b35bb0ba)

**Steps to Reproduce**:

[sharplab repro](https://sharplab.io/#gist:ad48e238601ae6acdb1a3f84b71522b6)

```csharp
using System;

internal class Program
{
    static void Main(string[] args)
    {
        // this does not raise a warning
        var object1 = new LegacyObject1();

        // but this does
        var object2 = new LegacyObject2();
    }
}

[Obsolete($"Do not use {nameof(LegacyObject1)}")]
public class LegacyObject1
{
}

[Obsolete("Do not use" + nameof(LegacyObject2))]
public class LegacyObject2
{
}
```

**Expected Behavior**:
I'm not sure about the actual problem. Either the attribute for `LegacyObject1` should not compile, as the value for `message` is not compile-time constant (or is it?), or the instantiation of it should raise a CS0618 warning.

**Actual Behavior**:
This compiles and does not raise a warning.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #64605

### CODE REVIEW

**Comment by Youssef1313** [comment]
Tagging @333fred for review (since you were assigned the issue). Thanks!

File: src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_WellKnownAttributes.cs [hunk 1]
```diff
@@ -13803,5 +13803,44 @@ public struct S2 { }
...
+    {
+        // this does not raise a warning
+        var object1 = new LegacyObject1();
+
+        // but this does
+        var object2 = new LegacyObject2();
+    }
+}
+
+[Obsolete($"Do not use {nameof(LegacyObject1)}")]
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Emit2/Attributes/AttributeTests_WellKnownAttributes.cs:13825]: Let's add some dedicated tests for when the interpolated string has non-constant underlying components in this location.

**Review by 333fred — COMMENTED** [review]
Done review pass (commit 2)

**Comment by 333fred** [comment]
Unfortunate: it looks like this change has caught actual instances of this in roslyn itself. Given that, we'll need a test insertion of this PR to see whether it breaks the VS build.

**Comment by Youssef1313** [comment]
> Unfortunate: it looks like this change has caught actual instances of this in roslyn itself. Given that, we'll need a test insertion of this PR to see whether it breaks the VS build.

Let me know the result of the test insertion please. Thanks!

**Comment by Youssef1313** [comment]
> What is meant by "a test insertion"? Thank you

I'm not the best to talk about it since it's something internal in Microsoft, but as far as I know, it checks how VS build goes with the compiler change made in this PR.
If this PR will cause errors in VS build, they should be fixed first.

**Comment by jaredpar** [comment]
> I'm not the best to talk about it since it's something internal in Microsoft, but as far as I know, it checks how VS build goes with the compiler change made in this PR.

A "test insertion" does a few things but the one most relevant here is that it builds the entire VS code base with the compiler that results from taking this change. The VS code base is both huge and has projects that were developed at all points in the C# history so it has a wide breadth of usage for all the features that we've done. It's an excellent test bed for scouting how disruptive a change will or won't be. Also just really good at shaking out bugs in the compiler. 

Our ability to ship in VS is predicated on our ability to build VS. When there is a change that potentially causes a build break in VS we first do a "test insertion" to see how bad it will be and determine if we need to do any pre-work in the VS repo to accept this change.

**Review by 333fred — APPROVED** [review]

**Comment by 333fred** [comment]
Test Insertion Pipeline: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6809216&view=results (internal only)

**Review by cston — APPROVED** [review]

**Comment by 333fred** [comment]
@dotnet/roslyn-ide can we have a quick review?

File: src/Workspaces/Core/Portable/Workspace/Solution/Project.cs [hunk 2]
```diff
@@ -106,7 +106,9 @@ internal Project(Solution solution, ProjectState projectState)
         /// Immutable snapshot of language services from the host environment associated with this project's language.
         /// Use this over <see cref="LanguageServices"/> when possible.
         /// </summary>
+#pragma warning disable CS0618 // Type or member is obsolete. Use Services instead. - This is the implementation of Services.
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Workspace/Solution/Project.cs:109]: So this was needed now because the compiler previously wasn't processing the Obsolete attribute during the source build?

**Review by jasonmalinowski — APPROVED** [review]

File: src/Workspaces/Core/Portable/Workspace/Solution/Project.cs (hunk 2 above)
Comment (Youssef1313) [reply src/Workspaces/Core/Portable/Workspace/Solution/Project.cs:109]: Yes the compiler didn't produce obsolete diagnostics when the attribute argument was interpolated string constant. This error was caught in the boostrapping build.

**Comment by 333fred** [comment]
Thanks @Youssef1313~
