### PR TITLE
[Ask Mode] Fix NRE in "Literal.Text" when the constant value is null

### LINKED ISSUE #9116: NRE in `Microsoft.CodeAnalysis.Semantics.Expression.Literal.Text`
For the following code, parameter default value of `o` is `null`, which results the value of `_value.Value` to be `null`.
```cs
struct S
{
    void M(
        int i = 1,
        string str = ""hello"",
        object o = null,
        S s = default(S))
    {
        M();
    }
}
```
Call stack:
```
Test 'Microsoft.CodeAnalysis.CSharp.UnitTests.GetSemanticInfoTests.ParameterDefaultValues' failed: System.NullReferenceException : Object reference not set to an instance of an object.
	Compilation\Expression.cs(311,0): at Microsoft.CodeAnalysis.Semantics.Literal.get_Text()
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(415,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.VisitLiteralExpression(ILiteralExpression operation)
	Compilation\Expression.cs(325,0): at Microsoft.CodeAnalysis.Semantics.Literal.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(41,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.Visit(IOperation operation)
	Compilation\OperationWalker.cs(204,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitArgument(IArgument operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(229,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.VisitArgument(IArgument operation)
	BoundTree\Expression.cs(261,0): at Microsoft.CodeAnalysis.CSharp.BoundCall.ArgumentBase.Microsoft.CodeAnalysis.IOperation.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(41,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.Visit(IOperation operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(210,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.VisitInvocationExpression(IInvocationExpression operation)
	BoundTree\Expression.cs(77,0): at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(41,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.Visit(IOperation operation)
	Compilation\OperationWalker.cs(181,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitExpressionStatement(IExpressionStatement operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(185,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.VisitExpressionStatement(IExpressionStatement operation)
	BoundTree\Statement.cs(699,0): at Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(41,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.Visit(IOperation operation)
	Compilation\OperationWalker.cs(21,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitArray[T](ImmutableArray`1 list)
	Compilation\OperationWalker.cs(45,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitBlockStatement(IBlockStatement operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(51,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.VisitBlockStatement(IBlockStatement operation)
	BoundTree\Statement.cs(52,0): at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	C:\GitHub\roslyn-internal\Open\src\Test\Utilities\Shared\Compilation\TestOperationWalker.cs(41,0): at Microsoft.CodeAnalysis.Test.Utilities.TestOperationWalker.Visit(IOperation operation)
	CSharpTestBase.cs(582,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBaseBase.WalkOperationTree(CSharpCompilation compilation)
	CSharpTestBase.cs(529,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBaseBase.CreateCompilation(IEnumerable`1 trees, IEnumerable`1 references, CSharpCompilationOptions options, String assemblyName)
	CSharpTestBase.cs(443,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBaseBase.CreateCompilationWithMscorlib(IEnumerable`1 trees, IEnumerable`1 references, CSharpCompilationOptions options, String assemblyName)
	CSharpTestBase.cs(434,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBaseBase.CreateCompilationWithMscorlib(SyntaxTree syntaxTree, IEnumerable`1 references, CSharpCompilationOptions options, String assemblyName)
	Compilation\GetSemanticInfoTests.cs(1819,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.GetSemanticInfoTests.ParameterDefaultValues()
```

### PR DESCRIPTION
**Pull request by genlu**
thIs fixes #9116.

@JohnHamby @dotnet/roslyn-interactive

### CODE REVIEW

File: src/Compilers/Core/Portable/Compilation/OperationWalker.cs [hunk 1]
```diff
@@ -193,7 +193,7 @@ public override void VisitEndStatement(IEndStatement operation)
         public override void VisitInvocationExpression(IInvocationExpression operation)
         {
             Visit(operation.Instance);
-            VisitArray(operation.ArgumentsInSourceOrder);
+            VisitArray(operation.ArgumentsInParameterOrder);
```
Comment (JohnHamby) [inline src/Compilers/Core/Portable/Compilation/OperationWalker.cs]: I assume this isn't related, but it seems like a good change.

File: src/Compilers/Core/Portable/Compilation/Expression.cs [hunk 2]
```diff
@@ -308,7 +308,7 @@ public Literal(ConstantValue value, ITypeSymbol resultType, SyntaxNode syntax)
             this.Syntax = syntax;
         }
 
-        public string Text => _value.Value.ToString();
+        public string Text => _value.GetValueToDisplay();
```
Comment (JohnHamby) [inline src/Compilers/Core/Portable/Compilation/Expression.cs]: Does the VB implementation have a similar issue?

**Comment by JohnHamby** [comment]
I sign off. I would also sign off on removing the ILiteralExpression.Text property, because its implementation is problematic and its utility questionable.

File: src/Compilers/Core/Portable/Compilation/OperationWalker.cs (hunk 1 above)
Comment (genlu) [inline src/Compilers/Core/Portable/Compilation/OperationWalker.cs]: Oh right, this is not related to this PR. Just a bug I wanted to fix a while ago but forgot. Without this change, user's callback for `OperationKind.Argument` will never be invoked for parameter using default value.

File: src/Compilers/Core/Portable/Compilation/Expression.cs (hunk 2 above)
Comment (genlu) [inline src/Compilers/Core/Portable/Compilation/Expression.cs]: This type is shared by both C# and VB (but I don't think VB is using it).

File: src/Compilers/CSharp/Test/Semantic/Diagnostics/OperationAnalyzerTests.cs [hunk 3]
```diff
@@ -748,7 +748,8 @@ enum E
                 Diagnostic(SeventeenTestAnalyzer.SeventeenDescriptor.Id, "17").WithLocation(4, 40),
                 Diagnostic(SeventeenTestAnalyzer.SeventeenDescriptor.Id, "17").WithLocation(9, 21),
                 Diagnostic(SeventeenTestAnalyzer.SeventeenDescriptor.Id, "17").WithLocation(14, 16),
-                Diagnostic(SeventeenTestAnalyzer.SeventeenDescriptor.Id, "17").WithLocation(24, 9)
+                Diagnostic(SeventeenTestAnalyzer.SeventeenDescriptor.Id, "17").WithLocation(24, 9),
+                Diagnostic(SeventeenTestAnalyzer.SeventeenDescriptor.Id, "M0()").WithLocation(16, 9)
```
Comment (genlu) [inline src/Compilers/CSharp/Test/Semantic/Diagnostics/OperationAnalyzerTests.cs]: @JohnHamby Since the change I made in walker breaks this, just want to be safe, it is the correct behavior, right?

Comment (JohnHamby) [inline src/Compilers/CSharp/Test/Semantic/Diagnostics/OperationAnalyzerTests.cs]: It's at least defensible. The pre-walker strategy didn't find the argument-supplied-by-default because it only found operations that had corresponding syntax. One can make a case that there should be no semantic difference between passing 17 explicitly and passing it implicitly.

I'm too tired to trust my own judgment, but I believe that the new behavior is correct.

I tried the change in the walker myself a few days ago, got as far as noticing the test failure, and abandoned the change. Perseverance furthers.

**Comment by genlu** [comment]
@dotnet-bot retest prtest/mac/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/4209/
// Retest reason:  Build Timed Out
