### PR TITLE
Make Local Functions follow brace newline option for methods

### LINKED ISSUE #14119: Local functions do not respect newline formatting options
**Steps to Reproduce**:
1. Go to Options -> Text Editor -> C# -> Code Style -> Formatting -> New Lines
2.  Uncheck all "New line options for braces"

image
3. Write a local function
4. Format the document (default shortcut is Ctrl +K, D )

**Expected Behavior**:

``` C#
class A {
    static void M() {
        void Local() {
        }
    }
}
```

**Actual Behavior**:

``` C#
class A {
    static void M() {
        void Local() 
        {
        }
    }
}
```

### PR DESCRIPTION
**Pull request by SLaks**
**Customer scenario**

Make local functions follow customer newline options

User types a local function with their preferred newline formatting, such as:
```C#
void M() {
    throw null;
}
```
Even if they disable the VS option to insert newlines for braces in functions, auto-formatting will turn it into:
```C#
void M()
{
    throw null;
}
```

**Bugs this fixes:** 
Fixes #14119

**Workarounds, if any**
Have an inconsistent codebase, or don't use the auto-formatter on files with local functions.

**Risk** 
Low. Additional case in formatting rules, specific to local functions.

**Performance impact**
Low; simple new codepath with one allocations in non-hot path.

**Is this a regression from a previous update?** 
No

**Root cause analysis:** 
New feature

**How was the bug found?** 
Ad-hoc testing

### CODE REVIEW

**Comment by jcouv** [comment]
@dotnet/roslyn-ide for review.
FYI @agocke

**Comment by agocke** [comment]
@SLaks Two things here: 

1. The brace newline options in VS have different settings for methods, anonymous methods, and lambdas. Why would we want local functions to share the setting for methods instead of getting its own setting like everything else?

2. Be aware that this may not meet the escrow bar for 2.0.

File: src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs [hunk 1]
```diff
@@ -116,6 +116,15 @@ public override AdjustSpacesOperation GetAdjustSpacesOperation(SyntaxToken previ
                 }
             }
 
+            // * { - in the anonymous Method context
```
Comment (agocke) [inline src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs]: This comment seems wrong. Should it read `// * { - in the local function context`?

File: src/Workspaces/CSharpTest/Formatting/FormattingTests.cs [hunk 2]
```diff
@@ -1617,6 +1627,10 @@ public class foo : System.Object {
             {
                             };
 
+        async void LocalFunction() 
+            {
```
Comment (agocke) [inline src/Workspaces/CSharpTest/Formatting/FormattingTests.cs]: Why's the indentation here all screwed up?

**Comment by agocke** [comment]
@SLaks Thanks for the PR though, if this doesn't meet the escrow bar we'll be sure to put it in for 2.1!

File: src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs (hunk 1 above)
Comment (SLaks) [inline src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs]: Yes.

File: src/Workspaces/CSharpTest/Formatting/FormattingTests.cs (hunk 2 above)
Comment (SLaks) [inline src/Workspaces/CSharpTest/Formatting/FormattingTests.cs]: To make sure the formatter fixes indent too.

**Comment by SLaks** [comment]
@agocke Good question.
I think there are too many discrete options there already, and I don't think it's worth adding another one.

Having separate options for lambdas / anonymous methods makes (some) sense, since they happen inside an expression.  I could see people wanting top-level declarations to have braces on their lines, but not inside expressions.

However, since local functions cannot appear inside expressions, I don't see why anyone would want them to be inconsistent from normal methods.

File: src/Workspaces/CSharpTest/Formatting/FormattingTests.cs (hunk 2 above)
Comment (agocke) [inline src/Workspaces/CSharpTest/Formatting/FormattingTests.cs]: 👍

**Comment by agocke** [comment]
@SLaks I've stopped asking why users want things and just assume that they do 😝

**Comment by SLaks** [comment]
@agocke Has anyone actually asked for a separate option? (as opposed to just having some way to remove the newline)

**Comment by agocke** [comment]
@SLaks I'll defer to the IDE team for that. They'll know if there's a history of people asking to configure these things separately.

**Comment by SLaks** [comment]
Should I wait for them to reply or just add the option?

**Comment by agocke** [comment]
@jmarolf Seems in favor of the option

**Comment by jmarolf** [comment]
@SLaks At the very least we would need to add a description explaining that this option controls both methods and local functions
image
 Considering that local functions appear inside of methods I can see people wanting them to have different styling than normal methods.

**Comment by jmarolf** [comment]
@SLaks see [here](https://github.com/dotnet/roslyn/compare/master...jmarolf:bugfix/local-functions-formatting-options?expand=1) for an example of how to add this option

**Comment by jcouv** [comment]
I don't have a strong opinion on adding extra option either. It makes sense that methods and local functions would be formatted the same, and maybe the option could be separated later if that is requested. I'll defer to @dotnet/roslyn-ide

**Comment by SLaks** [comment]
I added the option.
I can remove that commit if the IDE team prefers.

**Comment by jmarolf** [comment]
Thanks @SLaks looks good

**Comment by Pilchie** [comment]
Tagging @kuhlenh and @DustinCampbell for their opinions.  Personally, I'd rather *not* add a discrete option, until/unless someone has an established pattern that relies on a difference.

**Comment by jcouv** [comment]
Talked to @Pilchie and @DustinCampbell and got decision that we don't need a new setting for this (can be added later if requested).
@SLaks I'll let you remove that part of the PR. Thanks

**Comment by jmarolf** [comment]
Sorry for making you do extra work @SLaks.  Lets remove the option but add text that this option controls formatting for methods and local functions.

**Comment by SLaks** [comment]
I assume I should merge this into Methods, not Lambdas or Anonymous methods?

**Comment by jmarolf** [comment]
@SLaks correct, everyone feels that methods make the most sense.  If we get overwhelming feedback that people want an option for this then we can add it later.

**Comment by SLaks** [comment]
I rebased out the new option and added local functions to the name & preview for methods.

File: src/VisualStudio/CSharp/Impl/CSharpVSResources.resx [hunk 3]
```diff
@@ -189,8 +189,8 @@
   <data name="Place_open_brace_on_new_line_for_lambda_expression" xml:space="preserve">
     <value>Place open brace on new line for lambda expression</value>
   </data>
-  <data name="Place_open_brace_on_new_line_for_methods" xml:space="preserve">
-    <value>Place open brace on new line for methods</value>
+  <data name="Place_open_brace_on_new_line_for_methods_local_functions" xml:space="preserve">
+    <value>Place open brace on new line for methods and local functions</value>
```
Comment (Pilchie) [inline src/VisualStudio/CSharp/Impl/CSharpVSResources.resx]: @nguerrera Are we safe to do this now for loc, or should we leave the resource unchanged for RTW, and update in the `post-dev15` branch after this merges there?

File: src/VisualStudio/CSharp/Impl/Options/Formatting/NewLinesViewModel.cs [hunk 4]
```diff
@@ -21,6 +21,13 @@ class C {
...
 //[
     void Foo(){
+        int bar = 42;
+
+        int LocalFunction(int x) {
+            return 2 * x;
+        }
+
+        var baz = 9.75;
     }
```
Comment (Pilchie) [inline src/VisualStudio/CSharp/Impl/Options/Formatting/NewLinesViewModel.cs]: This preview text should be localized (see the other viewmodel classes).  Also, we're supporsed to avoid identifiers like `bar` and `baz`.

File: src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs [hunk 5]
```diff
@@ -116,6 +116,15 @@ public override AdjustSpacesOperation GetAdjustSpacesOperation(SyntaxToken previ
                 }
             }
 
+            // * { - in the local function context
+            if (currentToken.IsKind(SyntaxKind.OpenBraceToken) && currentTokenParentParent != null && currentTokenParentParent.IsKind(SyntaxKind.LocalFunctionStatement))
```
Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs]: Nit: Since I see the rest of this code uses the same pattern

1. `IsKind` checks for a `null` receiver (sneaky extension method).
2. Even if it didn't, `?.` is a thing now :)

Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs]: Yes.  It is an expected roslyn pattern that IsKind and IsParentKind will do null checks, and thus you can elide the null check here.  Sneaky, but idiomatic in our codebase now.

File: src/VisualStudio/CSharp/Impl/CSharpVSResources.resx (hunk 3 above)
Comment (nguerrera) [inline src/VisualStudio/CSharp/Impl/CSharpVSResources.resx]: The latter. Please leave the string as it was for RTW.

Comment (SLaks) [inline src/VisualStudio/CSharp/Impl/CSharpVSResources.resx]: So should I rebase out a5d215ac0c7b2ad544377aada06918b1f12c2c26 entirely?

Comment (Pilchie) [inline src/VisualStudio/CSharp/Impl/CSharpVSResources.resx]: Yes please.  We can make the string changes in `post-dev15`.

File: src/VisualStudio/CSharp/Impl/Options/Formatting/NewLinesViewModel.cs (hunk 4 above)
Comment (CyrusNajmabadi) [inline src/VisualStudio/CSharp/Impl/Options/Formatting/NewLinesViewModel.cs]: I would also undo this.

**Comment by CyrusNajmabadi** [comment]
👍 on this if we undo all the loc/preview changes.   Those can happen in post-dev15.  Thanks!

**Comment by SLaks** [comment]
I removed that commit; this should be ready now.

**Comment by Pilchie** [comment]
Tagging @MattGertz for approval to bring to escrow.

**Comment by MattGertz** [comment]
Rejected for RTW; please move to 15.1.

**Comment by SLaks** [comment]
:disappointed: Why?

**Comment by CyrusNajmabadi** [comment]
Put simply, we are trying to ship and our willingness to take on risk is extremely low.  We absolutely want to fix this.  And we will take this fix.  Just not for RTM.  Please rebase to post-dev15 and we'll merge it in immediately.  It will then make it in for Update1.

Don't worry, you'll still get this fix soon.  And, IMO, it's better to not focus on a specific release, but instead realize that eventually this will all flow in and improve things for everyone.

**Comment by CyrusNajmabadi** [comment]
Also, since you're pushing this to post-dev15, you can include the loc changes.  They're no problem now.  But please change the examples to not use foo/bar.  Thanks!

**Comment by SLaks** [comment]
I rebased & updated the names

**Comment by Pilchie** [comment]
@dotnet/roslyn-infrastructure is the failure in `windows_eta_open_prtest` known?

```
12:24:07 C:\Program Files (x86)\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [D:\j\workspace\windows_eta_o---d880a2eb\Closed\Hosting\CodeEditorControl\CodeEditorControl\CodeEditorControl.csproj]
12:24:07 
CSC : error CS1705: Assembly 'Microsoft.VisualStudio.Text.UI.Wpf' with identity 'Microsoft.VisualStudio.Text.UI.Wpf, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' uses 'Microsoft.VisualStudio.CoreUtility, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'Microsoft.VisualStudio.CoreUtility' with identity 'Microsoft.VisualStudio.CoreUtility, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [D:\j\workspace\windows_eta_o---d880a2eb\Closed\Hosting\CodeEditorControl\CodeEditorControl\CodeEditorControl.csproj]
12:24:07 CSC : error CS1705: Assembly 'Microsoft.VisualStudio.Text.UI' with identity 'Microsoft.VisualStudio.Text.UI, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' uses 'Microsoft.VisualStudio.CoreUtility, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'Microsoft.VisualStudio.CoreUtility' with identity 'Microsoft.VisualStudio.CoreUtility, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [D:\j\workspace\windows_eta_o---d880a2eb\Closed\Hosting\CodeEditorControl\CodeEditorControl\CodeEditorControl.csproj]
```

@jaredpar

**Comment by jcouv** [comment]
@dotnet-bot test windows_eta_open_prtest please
// warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [D:\j\workspace\windows_eta_o---d880a2eb\Closed\Hosting\CodeEditorControl\CodeEditorControl\CodeEditorControl.csproj]

**Comment by jasonmalinowski** [comment]
Ah, this is probably a merge issue with some of @tmat's stuff. @jmarolf you might have to fix this up in the next merge to post-dev15.

**Comment by jcouv** [comment]
@dotnet-bot test windows_eta_open_prtest please

**Comment by jmarolf** [comment]
Thanks @SLaks !
