### PR TITLE
Fix space formatting for bracket parents

### LINKED ISSUE #5358: Weird Formatter behaviour when formatting multidimensional arrays
Let's jump right to the code:
```csharp
private void FormatterWeirdnessExample()
{
	AdhocWorkspace workspace = new AdhocWorkspace();
	workspace.Options = workspace.Options
		.WithChangedOption( CSharpFormattingOptions.SpaceAfterComma, true )
		.WithChangedOption( CSharpFormattingOptions.SpaceBetweenEmptySquareBrackets, false )
		.WithChangedOption( CSharpFormattingOptions.SpaceWithinSquareBrackets, true );

	SyntaxTree tree = CSharpSyntaxTree.ParseText( "int[ , ] array = new int[ 1, 1 ];" );
	SyntaxNode root = tree.GetRoot();
	Debug.WriteLine( root );

	IList<TextChange> changes = Formatter.GetFormattedTextChanges( root, workspace );
	foreach ( var change in changes )
		Debug.WriteLine( change );

	SyntaxNode formatted = Formatter.Format( root, workspace );
	Debug.WriteLine( formatted );
}
```

And here's the output:
```
int[ , ] array = new int[ 1, 1 ];
TextChange: { [4..5), "" }
TextChange: { [6..7), "" }
TextChange: { [7..7), " " }
int[, ] array = new int[ 1, 1 ];
```

First of all, the result of `Formatter.Format` looks kind of strange. I expected to get either the spaces both before and after the comma (`int[ , ]`) or no spaces around the comma at all (`int[,]`), but getting just the space after looks unexpected (and probably a bit ugly).

Second, the contradicting changes (`TextChange: { [6..7), "" }` and `TextChange: { [7..7), " " }`) are very confusing. That's actually how I stumbled upon this issue: I was writing an analyzer that checks if the document violates the formatting rules, so I used `GetFormattedTextChanges()` to detect the possible formatting changes. But apparently it's possible for the text changes to negate each other so the `Format()` method doesn't actually change anything. I don't know if it's a bug or a feature, but it definitely makes using `GetFormattedTextChanges()` a lot more difficult.

### PR DESCRIPTION
**Pull request by diryboy**
Fixes #5358

### CODE REVIEW

**Comment by Pilchie** [comment]
@dotnet-bot okay to test.

@diryboy Thanks for the PR!  Given that in #5358 we identified 3 options that are involved here, it might be good to have tests that cover the 8 possible combinations of those options to ensure we preserve the precedence.  What do you think?

**Comment by diryboy** [comment]
Speaking of ensure, `SpaceBeforeComma` could also conflict `SpaceWithinBrackets`, so 16 it is. And what about `< , >` for generics? I can see a similar test in `OmittedTypeArgument`. So 32 cases should have been there. :scream: 

Well, yes, why not? I'll do that.

**Comment by diryboy** [comment]
OK, there's no options to control generics, so I won't do another 16.

After comparing VS2013, I found that VS2013 can produce `[, ,]` and `[ , , ]` but no `[ ,, ]`, these formats are so bizarre so I now treat `[ , ]` as empty and control them using `SpacesWithinEmptyBracket`, and always either `[ , , ]` or `[,,]`, regardless what combination of `SpaceBeforeComma` and `SpaceAfterComma`.

**Comment by Pilchie** [comment]
LGTM, but need to figure out how to get @dotnet-bot to run our integration tests.

Also - can either @basoundr or @heejaechang take a look too?

**Comment by tannergooding** [comment]
test eta please

**Comment by tannergooding** [comment]
ok to test

**Comment by tannergooding** [comment]
ok to test

**Comment by tannergooding** [comment]
test eta please

File: src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs [hunk 1]
```diff
@@ -174,22 +176,12 @@ public override AdjustSpacesOperation GetAdjustSpacesOperation(SyntaxToken previ
             {
                 return AdjustSpacesOperationZeroOrOne(optionSet, CSharpFormattingOptions.SpaceWithinSquareBrackets);
             }
-            else if (currentKind == SyntaxKind.CloseBracketToken && HasFormattableBracketParent(currentToken))
+            if (currentKind == SyntaxKind.CloseBracketToken && previousKind != SyntaxKind.OmittedArraySizeExpressionToken && HasFormattableBracketParent(currentToken))
```
Comment (basoundr) [inline src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs]: Please introduce a linebreak

File: src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs [hunk 2]
```diff
@@ -174,22 +176,12 @@ public override AdjustSpacesOperation GetAdjustSpacesOperation(SyntaxToken previ
...
-                        // int []: added spacing operation on open [
-                        // int[1], int[,]: need spacing operation
-                        return AdjustSpacesOperationZeroOrOne(optionSet, CSharpFormattingOptions.SpaceWithinSquareBrackets);
-                    }
-                }
-                else
-                {
-                    return AdjustSpacesOperationZeroOrOne(optionSet, CSharpFormattingOptions.SpaceWithinSquareBrackets);
-                }
+                // int []: added spacing operation on [
```
Comment (basoundr) [inline src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs]: Move the comments outside the if block

Comment (basoundr) [inline src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs]: Usually we add the case that gets handled by the `if` block next to the `if` block. So initially, I got confused by reading the comments that all 3 cases were handled by this block. 

For clarity, could you please add the first 2 comments next to the appropriate `if` block that handles these cases. Modify this comment to something like. 
```C#
\\ The following 2 cases have been handled earlier\later. It is *NOT* handled here
\\ case1: int []
\\ case2: int[,]

\\ The cases handled here are:
\\ case1: int[1]
```

File: src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs [hunk 3]
```diff
@@ -205,15 +197,21 @@ public override AdjustSpacesOperation GetAdjustSpacesOperation(SyntaxToken previ
             }
 
             // For spacing delimiters - after comma
-            if ((previousToken.IsCommaInArgumentOrParameterList() && currentKind != SyntaxKind.OmittedTypeArgumentToken) ||
-                previousToken.IsCommaInInitializerExpression())
+            if ((previousToken.IsCommaInArgumentOrParameterList() && currentKind != SyntaxKind.OmittedTypeArgumentToken)
+                || previousToken.IsCommaInInitializerExpression()
+                || (previousKind == SyntaxKind.CommaToken
```
Comment (basoundr) [inline src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs]: Can you extract this condition into a method? Readability decreases with more conditions within `if`

File: src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs [hunk 4]
```diff
@@ -205,15 +197,21 @@ public override AdjustSpacesOperation GetAdjustSpacesOperation(SyntaxToken previ
...
             {
                 return AdjustSpacesOperationZeroOrOne(optionSet, CSharpFormattingOptions.SpaceAfterComma);
             }
 
             // For spacing delimiters - before comma
-            if ((currentToken.IsCommaInArgumentOrParameterList() && previousKind != SyntaxKind.OmittedTypeArgumentToken) ||
-                currentToken.IsCommaInInitializerExpression())
+            if ((currentToken.IsCommaInArgumentOrParameterList() && previousKind != SyntaxKind.OmittedTypeArgumentToken)
+                || currentToken.IsCommaInInitializerExpression()
+                || (currentKind == SyntaxKind.CommaToken
```
Comment (basoundr) [inline src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs]: Extract the condition into a method here too?

File: src/Workspaces/CSharpTest/Formatting/FormattingTests.cs [hunk 5]
```diff
@@ -5352,22 +5353,271 @@ void foo()
...
+            {
+                { SpaceBeforeComma, false },
+                { SpaceAfterComma, false },
+                { SpaceBetweenEmptySquareBrackets, false },
+                { SpaceWithinSquareBrackets, false },
+            };
+            AssertFormat("// 00" + expected00, "// 00" +  code, changedOptionSet: options);
+
+            options[SpaceBeforeComma] = true;
+            AssertFormat("// 10" + expected10, "// 10" +  code, changedOptionSet: options);
```
Comment (basoundr) [inline src/Workspaces/CSharpTest/Formatting/FormattingTests.cs]: The combinations of the testcases are really good. It would be nice if the asserts fall into its own testcase. This way, when something fails, there is just one scenario that is at fault and we dont want to be looking at which assert, among the 4, that failed the whole testcase.

Also a different name instead of `expected00` would be more readable. In this case, it would be something like `expectedWithNoSpaceBeforeCommaAndAfterComma`. When this particular assert fails, the user will automatically know what the expectation is instead of trying to understand the naming convention and finding out what went wrong. Descriptive variable names are always preferred over cryptic names

File: src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs (hunk 2 above)
Comment (diryboy) [inline src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs]: Comments were kept from the original code, I had the same confusion when I first read that, will fix up.

File: src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs (hunk 3 above)
Comment (diryboy) [inline src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs]: But there are too many parameters, `previousToken` `previousKind` `currentKind`, in a similar check later: `currentToken` `currentKind` `previousKind`, if cut the kind parameter for corresponding token, then another call to `.Kind()` would be introduced,  in worst would introduce 2+2 calls in total. There are code paths like `currentKind == Comma && HasFormattableBracketParent(currentToken)`, I don't think adding another check to ensure the nearby token not being OmittedArraySizeExpressionToken needs a separate method.

What do you think?

File: src/Workspaces/CSharpTest/Formatting/FormattingTests.cs (hunk 5 above)
Comment (diryboy) [inline src/Workspaces/CSharpTest/Formatting/FormattingTests.cs]: Ah, sure, just tried to be lazy about the names.
