### PR TITLE
Suppress $ReturnValue in the Locals window

### LINKED ISSUE #6755: EE:  Remove duplicate return value row for Update 2
To fix VSO bug 137772, I added a "$ReturnValue" alias.  This fixes the bug but has the effect of duplicating the last return value in the Locals window.  We need to fix the EC to filter out "$ReturnValue" (no number) when populating Locals to avoid a regression in Update 2.

**Repro:**

Install a vsucorediag build 24713 or later (won't repro before my fix)

Create a Console app with this code:
```C#
class P
{
    static void Main()
    {
        int i = F();
    }

    public static int F()
    {
        return 1;
    }
}
```
Set a breakpoint at the call to F();
Run to breakpoint
Single Step (F10)
View Locals window

**Result:** Two entries named `P.F returned` in the Locals Window

### PR DESCRIPTION
**Pull request by amcasey**
...since it will always be redundant with the last $ReturnValueN.

Fixes #6755.

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @KevinH-MS @pnelsonmsft @cston

File: src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/LocalsTests.cs [hunk 1]
```diff
@@ -262,15 +262,16 @@ .maxstack  1
...
+                // $ReturnValue is suppressed since it always matches the last $ReturnValueN
+//                VerifyLocal(testData, typeName, locals[2], "<>m2", "$ReturnValue", "Method M returned", expectedFlags: DkmClrCompilationResultFlags.ReadOnlyResult, expectedILOpt:
+//@"{
+//  // Code size        7 (0x7)
+//  .maxstack  1
+//  IL_0000:  ldc.i4.0
+//  IL_0001:  call       ""object Microsoft.VisualStudio.Debugger.Clr.IntrinsicMethods.GetReturnValue(int)""
+//  IL_0006:  ret
+//}");
+                VerifyLocal(testData, typeName, locals[2], "<>m2", "$2", expectedFlags: DkmClrCompilationResultFlags.ReadOnlyResult, expectedILOpt:
```
Comment (cston) [inline src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/LocalsTests.cs]: Commented out code can be deleted.

Comment (cston) [inline src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/LocalsTests.cs]: Or move the IL verification to the additional `CompileExpression` below.

File: src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs [hunk 2]
```diff
@@ -297,6 +297,12 @@ private static string GetNextMethodName(ArrayBuilder<MethodSymbol> builder)
                             var typeNameDecoder = new EETypeNameDecoder(Compilation, (PEModuleSymbol)_currentFrame.ContainingModule);
                             foreach (var alias in aliases)
                             {
+                                if (alias.IsReturnValue0())
+                                {
+                                    Debug.Assert(aliases.Where(a => a.Kind == DkmClrAliasKind.ReturnValue).Count() > 1);
```
Comment (cston) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs]: ```aliases.Count(a => a.Kind == DkmClrAliasKind.ReturnValue) > 1```

Comment (pnelsonmsft) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs]: Or `aliases.Any(a => a.Kind == DkmClrAliasKind.ReturnValue)`

File: src/ExpressionEvaluator/Core/Source/ExpressionCompiler/PseudoVariableUtilities.cs [hunk 3]
```diff
@@ -54,5 +54,14 @@ internal static DkmClrCompilationResultFlags GetLocalResultFlags(this Alias alia
...
         }
+
+        internal static bool IsReturnValue0(this Alias alias)
+        {
+            int index;
+            return
+                alias.Kind == DkmClrAliasKind.ReturnValue &&
+                TryParseReturnValueIndex(alias.FullName, out index) &&
+                index == 0;
+        }
```
Comment (cston) [inline src/ExpressionEvaluator/Core/Source/ExpressionCompiler/PseudoVariableUtilities.cs]: Does this return `true` for `$ReturnValue` and `$ReturnValue0`? Is that intended?

File: src/ExpressionEvaluator/Core/Source/ExpressionCompiler/PseudoVariableUtilities.cs [hunk 4]
```diff
@@ -54,5 +54,14 @@ internal static DkmClrCompilationResultFlags GetLocalResultFlags(this Alias alia
                     return DkmClrCompilationResultFlags.None;
             }
         }
+
+        internal static bool IsReturnValue0(this Alias alias)
```
Comment (pnelsonmsft) [inline src/ExpressionEvaluator/Core/Source/ExpressionCompiler/PseudoVariableUtilities.cs]: The return values are 1-based.  You'll either need to filter out "$ReturnValue" or "$ReturnValue1"

Comment (pnelsonmsft) [inline src/ExpressionEvaluator/Core/Source/ExpressionCompiler/PseudoVariableUtilities.cs]: Actually you want to filter out "$ReturnValue".  $ReturnValue is an alias for the last return value (largest number)

File: src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs (hunk 2 above)
Comment (KevinH-MS) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs]: I like the predicate to Count one, but I don't think Any has the same semantics (that would be ```>= 1``` vs ```> 1```)

File: src/ExpressionEvaluator/Core/Source/ExpressionCompiler/PseudoVariableUtilities.cs (hunk 4 above)
Comment (KevinH-MS) [inline src/ExpressionEvaluator/Core/Source/ExpressionCompiler/PseudoVariableUtilities.cs]: "The more you know..."  :smile:

File: src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/LocalsTests.cs (hunk 1 above)
Comment (amcasey) [inline src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/LocalsTests.cs]: Deleted.

File: src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs (hunk 2 above)
Comment (amcasey) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs]: Merged `Where` into `Count`.

File: src/ExpressionEvaluator/Core/Source/ExpressionCompiler/PseudoVariableUtilities.cs (hunk 3 above)
Comment (amcasey) [inline src/ExpressionEvaluator/Core/Source/ExpressionCompiler/PseudoVariableUtilities.cs]: There is no `$ReturnValue0`, but you're correct that the function will accept it.  Revising.

File: src/ExpressionEvaluator/Core/Source/ExpressionCompiler/PseudoVariableUtilities.cs (hunk 4 above)
Comment (amcasey) [inline src/ExpressionEvaluator/Core/Source/ExpressionCompiler/PseudoVariableUtilities.cs]: I struggled to find a name for this method and obviously I failed.  Its purpose is to filter out `$ReturnValue`.  What about `IsReturnValueWithoutIndex`?

**Comment by amcasey** [comment]
```
internal static bool IsReturnValueWithoutIndex(this Alias alias)
{
    Debug.Assert(alias.Kind != DkmClrAliasKind.ReturnValue || 
        alias.FullName.StartsWith("$ReturnValue", StringComparison.OrdinalIgnoreCase));
    return
        alias.Kind == DkmClrAliasKind.ReturnValue &&
        alias.FullName.Length == 12; // "$ReturnValue"
}
```

File: src/ExpressionEvaluator/Core/Source/ExpressionCompiler/PseudoVariableUtilities.cs [hunk 5]
```diff
@@ -54,5 +54,14 @@ internal static DkmClrCompilationResultFlags GetLocalResultFlags(this Alias alia
...
             }
         }
+
+        internal static bool IsReturnValueWithoutIndex(this Alias alias)
+        {
+            Debug.Assert(alias.Kind != DkmClrAliasKind.ReturnValue || 
+                alias.FullName.StartsWith("$ReturnValue", StringComparison.OrdinalIgnoreCase));
+            return
+                alias.Kind == DkmClrAliasKind.ReturnValue &&
+                alias.FullName.Length == 12; // "$ReturnValue"
```
Comment (cston) [inline src/ExpressionEvaluator/Core/Source/ExpressionCompiler/PseudoVariableUtilities.cs]: Consider extracting a constant shared with `TryParseReturnValueIndex`.

**Comment by cston** [comment]
LGTM

File: src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/LocalsTests.vb [hunk 6]
```diff
@@ -169,6 +169,7 @@ End Class"
   IL_0005:  castclass  ""System.IO.IOException""
   IL_000a:  ret
 }")
+                    ' $ReturnValue is suppressed since it always matches the last $ReturnValueN
                     VerifyLocal(testData, typeName, locals(1), "<>m1", "$ReturnValue2", "Method M2 returned", expectedFlags:=DkmClrCompilationResultFlags.ReadOnlyResult, expectedILOpt:=
```
Comment (KevinH-MS) [inline src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/LocalsTests.vb]: Do we have tests for the case where there's *just* ```$ReturnValue``` (not ```$ReturnValue1```, ```ReturnValue2```, ...)

Comment (KevinH-MS) [inline src/ExpressionEvaluator/VisualBasic/Test/ExpressionCompiler/LocalsTests.vb]: Discussed offline...it doesn't matter, because we never show "$ReturnValue" in the locals window...it gets transformed back into "FunctionX returned" for display.

**Comment by KevinH-MS** [comment]
:+1:
