### PR TITLE
Handle function pointer and xml normalization

### LINKED ISSUE #49732: NormalizeWhitespace corrupts, invalidates xml doc comments when xml tags have namespaces
**Version Used**: Microsoft.CodeAnalysis.CSharp 3.8.0

**Steps to Reproduce**:

Use `ParseLeadingTrivia` on a string such as this:

```cs
/// <returns>
/// If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>.
/// </returns>
```

Then use`NormalizeWhitespace` on the overall `CompilationUnitSyntax`.

**Expected Behavior**:

A C# file with a valid xml doc comment

**Actual Behavior**:

I end up with xml in the generated .cs file such as this::

```cs
/// <returns>
/// If this method succeeds, it returns <b xmlns: loc = "http://microsoft.com/wdcml/l10n">S_OK</b>.
/// </returns>
```

Note the added space between `xmlns:` and `loc`. This is enough to break xml parsing and causes the C# lang svc to altogether throw out the entire leading trivia so that no xml doc comment for that member shows up in Intellisense.

Now, of course we can ask why the namespaced tag. It's an artifact of the scraping we're doing of other documentation in order to apply it to APIs for showing up in Intellisense. We want to clean these up over time. But in the meantime, I think we can all agree that `NormalizeWhitespace` should not introduce parsing errors.

### LINKED ISSUE #50664: NormalizeWhitespace should handle function pointers
It doesn't put the right spacing. We should have no spacing between `delegate` and `*`, no spacing between `*` and `<`, but some spacing between `>` and following identifier.
We should also test with calling conventions.

See https://github.com/dotnet/roslyn/pull/49919

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #50664 (commit 1)
Fixes #49732 (commit 2)

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs [hunk 1]
```diff
@@ -490,6 +495,18 @@ private static bool NeedsSeparator(SyntaxToken token, SyntaxToken next)
                 return true;
             }
 
+            // No space after asterisk in function pointer.
+            if (token.IsKind(SyntaxKind.AsteriskToken) && token.Parent.IsKind(SyntaxKind.FunctionPointerType))
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs:505]: It's a bit more complicated than this. The IDE rules I implemented are:

1. If there is no calling convention, no spaces.
2. If there is a calling convention, put a space between the asterisk and the calling convention. So, for example, `delegate* unmanaged<void>`. See the IDE spacing rules here: [https://github.com/dotnet/roslyn/blob/main/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/SpacingFormattingRule.cs#L321-L413](https://github.com/dotnet/roslyn/blob/main/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Formatting/Rules/SpacingFormattingRule.cs#L321-L413).

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs [hunk 2]
```diff
@@ -456,7 +461,8 @@ private static bool NeedsSeparator(SyntaxToken token, SyntaxToken next)
 
             if (token.IsKind(SyntaxKind.ColonToken))
             {
-                return !token.Parent.IsKind(SyntaxKind.InterpolationFormatClause);
+                return !token.Parent.IsKind(SyntaxKind.InterpolationFormatClause)
+                    && !token.Parent.IsKind(SyntaxKind.XmlPrefix);
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs:465]: Nit: formatting feels weird here. I'd expect the `&&` to either be in line with the previous condition, or on the previous line.

**Comment by 333fred** [comment]
Done review pass (commit 2)

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs (hunk 2 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs:465]: @333fred Agree. I was only being consistent with the above formatting:

https://github.com/dotnet/roslyn/blob/021549aa433a48c0476bf88af54577888e31333a/src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs#L455-L457

I'll stick to place `&&` at the end of previous line instead of start of new line.

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs (hunk 1 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs:505]: Thanks @333fred. This makes it much easier.

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs [hunk 3]
```diff
@@ -485,9 +491,108 @@ private static bool NeedsSeparator(SyntaxToken token, SyntaxToken next)
...
+            if (token.IsKind(SyntaxKind.LessThanToken) && token.Parent.IsKind(SyntaxKind.FunctionPointerParameterList))
+            {
+                return false;
+            }
+
+            // No space before the > in function pointer parameter lists
+            // delegate*<void>
+            if (next.IsKind(SyntaxKind.GreaterThanToken) && next.Parent.IsKind(SyntaxKind.FunctionPointerParameterList))
+            {
+                return false;
```
Comment (Youssef1313) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs:595]: The IDE spacing is using an IDE option, which I don't think is available to use here. I defaulted to the more common convention, which is no space before `>` and no space after `<`.

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs [hunk 4]
```diff
@@ -649,6 +649,92 @@ public void TestNormalizeTuples()
             TestNormalizeDeclaration("public (string prefix,string uri)Foo()", "public (string prefix, string uri) Foo()");
         }
 
+        [Fact]
```
Comment (Youssef1313) [inline src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs:652]: Tests are copy from IDE tests, except 2 tests that produce an invalid tree and have different behavior (which I think is acceptable):

https://github.com/dotnet/roslyn/blob/6da1274c9d24c2f90a48290394a951b23617f2a3/src/Workspaces/CSharpTest/Formatting/FormattingTests_FunctionPointers.cs#L88-L122

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs (hunk 3 above)
Comment (333fred) [reply src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs:595]: Yeah, the normalizer isn't customized. There's one normalization.

---
In reply to: [598105046](https://github.com/dotnet/roslyn/pull/51981#discussion_r598105046) [](ancestors = 598105046)

**Review by 333fred — APPROVED** [review]
LGTM (commit 7). Thanks for the ping, this had slipped off my radar. @dotnet/roslyn-compiler for a second review.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 7)

**Comment by jcouv** [comment]
Merged/squashed. Thanks @Youssef1313
