### PR TITLE
Fix ValueTracking for index parameters

### LINKED ISSUE #57100: InvalidCastException in ValueTracking
**Version Used**: 
VS2022 Version 17.0.0 Preview 4.1

**Steps to Reproduce**:
```cs
        public int this[string key] => 0;
```
1.  Right click, and click `Track Value Source` with `key`

**Expected Behavior**:

**Actual Behavior**:
```cs
System.InvalidCastException: Cannot cast an object of type "Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.PropertySymbol" to type "Microsoft.CodeAnalysis.IMethodSymbol".
      at Microsoft.CodeAnalysis.ValueTracking.ValueTracker.<TrackParameterSymbolAsync>d__4.MoveNext()
      at Microsoft.CodeAnalysis.ValueTracking.ValueTracker.<TrackValueSourceAsync>d__1.MoveNext()
      at Microsoft.CodeAnalysis.Remote.RemoteValueTrackingService.<>c__DisplayClass3_0.<<TrackValueSourceAsync>b__0>d.MoveNext()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__12`1.MoveNext()
```

### PR DESCRIPTION
**Pull request by ryzngard**
Index values weren't properly handled previously, and it was assumed all parameters existed in a method. In reality some exist in properties. Who knew!??!

No need to worry about the cast, symbol finder will do the right thing. Code does need to be updated to handle the fact that we want to track potentially two things with index: the argument passed in as the index in callsites, and potentially the item being indexed to. Update the FindReferencesProgress to handle references for index specifically.

Fixes #57100

### CODE REVIEW

File: src/Features/Core/Portable/ValueTracking/ValueTracker.FindReferencesProgress.cs [hunk 1]
```diff
@@ -86,6 +86,53 @@ public async ValueTask OnReferenceFoundAsync(SymbolGroup _, ISymbol symbol, Refe
...
+                            }
+                        }
+                    }
+
+                    if (expression is not null)
+                    {
+                        // We do not want to track "this" as part of an index operation, but we do 
+                        // want to track other variables that are accessed. Arguably they "contribute" even if
+                        // not specifically to the argument of the element access.
+                        if (syntaxFacts.IsThisExpression((expression)))
```
Comment (davidwengier) [inline src/Features/Core/Portable/ValueTracking/ValueTracker.FindReferencesProgress.cs:124]: Nit
```suggestion
                        if (syntaxFacts.IsThisExpression(expression))
```

**Review by davidwengier — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
> Index values weren't properly handled previously, and it was assumed all parameters existed in a method. In reality some exist in properties. Who knew!??!

this can also be true for VB properties, if you haven't, can you test that out?

Also, it woudl be good to test tracking of the standard 'value' value in a C# property if we're not already doing that.

**Comment by ryzngard** [comment]
> > Index values weren't properly handled previously, and it was assumed all parameters existed in a method. In reality some exist in properties. Who knew!??!
> 
> this can also be true for VB properties, if you haven't, can you test that out?
> 
> Also, it woudl be good to test tracking of the standard 'value' value in a C# property if we're not already doing that.

Added tests for this :)
