### PR TITLE
Fix for generate constructor naming bug

### LINKED ISSUE #44708: Name 'immutableArrays' is suggested for ImmutableArray<Frog> rather than 'frogs'
**Version Used**: 16.6.0

```cs
using System.Collections.Immutable;

class Frog { }

class C
{
    void M()
    {
        var builder = ImmutableArray.CreateBuilder<Frog>();

        return new [||]C(builder.ToImmutable());
    }
}
```

🛠 Generate constructor in 'C':

```cs
using System.Collections.Immutable;

class Frog { }

class C
{
    private ImmutableArray<Frog> immutableArrays;

    public C(ImmutableArray<Frog> immutableArrays)
    {
        this.immutableArrays = immutableArrays;
    }

    void M()
    {
        var builder = ImmutableArray.CreateBuilder<Frog>();

        return new C(builder.ToImmutable());
    }
}
```

### PR DESCRIPTION
**Pull request by allisonchou**
Fixes #44708 by looking at type arguments to potentially determine a name.
Only considers cases with one type argument. This logic can potentially be expanded upon in the future.

### CODE REVIEW

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs [hunk 1]
```diff
@@ -220,14 +220,40 @@ private static ImmutableArray<ParameterName> GenerateNames(IList<string> reserve
...
+        private static bool TryGenerateNameFromTypeArgument(ITypeSymbol type, bool capitalize, bool pluralize, out string parameterName)
+        {
+            var typeArguments = type.GetAllTypeArguments();
+
+            // We only consider generating a name if there's one type argument.
+            // This logic can potentially be expanded upon in the future.
+            if (typeArguments.Length == 1)
+            {
+                var typeArgument = typeArguments.Single().ToNameDisplayString();
+                if (SyntaxFacts.IsValidIdentifier(typeArgument))
```
Comment (davidwengier) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs:245]: I'm mainly just curious, but is it possible for a type argument to not be a valid identifier?

**Review by davidwengier — APPROVED** [review]

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs [hunk 2]
```diff
@@ -220,14 +220,40 @@ private static ImmutableArray<ParameterName> GenerateNames(IList<string> reserve
...
             var type = info.Type;
             var pluralize = Pluralize(semanticModel, type);
 
+            // We may be able to use the type's arguments to generate a name.
+            if (TryGenerateNameFromTypeArgument(type, capitalize, pluralize, out var typeArgumentParameterName))
+            {
+                return typeArgumentParameterName;
+            }
+
             var parameterName = type.CreateParameterName(capitalize);
```
Comment (davidwengier) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs:232]: Could this change go in `CreateParameterName`? Looks like it already has cases for array types and pointer types, so generic types is maybe not too much of a stretch?

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs:245]: possibly in error conditions.  i.e. `ImmutableArray<>`.  (taht's worth testing btw).

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs [hunk 3]
```diff
@@ -220,14 +220,40 @@ private static ImmutableArray<ParameterName> GenerateNames(IList<string> reserve
...
+            // We only consider generating a name if there's one type argument.
+            // This logic can potentially be expanded upon in the future.
+            if (typeArguments.Length == 1)
+            {
+                var typeArgument = typeArguments.Single().ToNameDisplayString();
+                if (SyntaxFacts.IsValidIdentifier(typeArgument))
+                {
+                    parameterName = capitalize ? typeArgument.ToPascalCase() : typeArgument.ToCamelCase();
+                    parameterName = pluralize ? parameterName.Pluralize() : parameterName;
+                    return true;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs:249]: i don't think this is a great approach.  say i have `IServiceLocator<Frob>`, this will generate the name `Frobs`, insead of `serviceLocator`.

I think what we want is to take the following approach if the type is generic *and* derives from IEnumerable<T>.  That way we could at least believe it's a collection type and thus we shlud pluralize the element ttype.

File: src/EditorFeatures/VisualBasicTest/GenerateConstructor/GenerateConstructorTests.vb [hunk 4]
```diff
@@ -1434,21 +1434,22 @@ End Enum
 Public Class MyAttribute
     Inherits System.Attribute
 
-    Private v1 As Short()
```
Comment (allisonchou) [inline src/EditorFeatures/VisualBasicTest/GenerateConstructor/GenerateConstructorTests.vb:1437]: This test change brings VB closer to the [equivalent C# test](http://sourceroslyn.io/#Microsoft.CodeAnalysis.CSharp.EditorFeatures.UnitTests/GenerateConstructor/GenerateConstructorTests.cs,b8dec7376531facc).

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs [hunk 5]
```diff
@@ -219,25 +220,7 @@ private static ImmutableArray<ParameterName> GenerateNames(IList<string> reserve
             // Otherwise, figure out the type of the expression and generate a name from that
             // instead.
             var info = semanticModel.GetTypeInfo(expression, cancellationToken);
-
-            // If we can't determine the type, then fallback to some placeholders.
```
Comment (allisonchou) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs:223]: The removed code here was moved to SemanticModelExtensions in the core Workspaces layer for dual use between C# and VB.

File: src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs [hunk 6]
```diff
@@ -171,5 +174,57 @@ public static SemanticMap GetSemanticMap(this SemanticModel semanticModel, Synta
...
+            if (pluralize && TryGenerateNameFromTypeArgument(syntaxFacts, type, capitalize, out var typeArgumentParameterName))
+            {
+                return typeArgumentParameterName;
+            }
+
+            var parameterName = type.CreateParameterName(capitalize);
+            return pluralize ? parameterName.Pluralize() : parameterName;
+        }
+
+        private static bool Pluralize(this SemanticModel semanticModel, ITypeSymbol type)
```
Comment (allisonchou) [inline src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs:193]: This Pluralize method already existed and was just moved over from C# layer.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Extensions/SemanticModelExtensions.vb [hunk 7]
```diff
@@ -78,97 +75,6 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Extensions
             Return semanticModel.GetSymbolInfo(expression)
         End Function
 
-        <Extension()>
-        Public Function GenerateNameForArgument(semanticModel As SemanticModel,
```
Comment (allisonchou) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Extensions/SemanticModelExtensions.vb:82]: All of these methods were moved over the VB Workspaces layer.

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs (hunk 2 above)
Comment (allisonchou) [reply src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs]: Thanks for the review! I just updated the code to put the change instead in the core Workspaces layer so that it can be used by both C# and VB.

**Review by davidwengier — APPROVED** [review]

File: src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs [hunk 8]
```diff
@@ -171,5 +174,62 @@ public static SemanticMap GetSemanticMap(this SemanticModel semanticModel, Synta
 
             return new TokenSemanticInfo(declaredSymbol, aliasSymbol, allSymbols, type, convertedType, token.Span);
         }
+
+        public static string GenerateNameFromType(this SemanticModel semanticModel, ITypeSymbol type, ISyntaxFacts syntaxFacts, bool capitalize)
+        {
+            var pluralize = semanticModel.Pluralize(type);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs:180]:
```suggestion
            var pluralize = semanticModel.ShouldPluralize(type);
```

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs:180]: `Pluralize` makes it sound as if you're actually doing the work, not querying if it should be done.

File: src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs [hunk 9]
```diff
@@ -171,5 +174,62 @@ public static SemanticMap GetSemanticMap(this SemanticModel semanticModel, Synta
...
+            var typeArguments = type.GetAllTypeArguments();
+
+            // We may be able to use the type's arguments to generate a name if we're working with an enumerable type.
+            if (pluralize && TryGenerateNameFromTypeArgument(syntaxFacts, typeArguments, capitalize, out var typeArgumentParameterName))
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs:184]:
```suggestion
            if (pluralize && TryGeneratePluralizedNameFromTypeArgument(syntaxFacts, typeArguments, capitalize, out var typeArgumentParameterName))
```

File: src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs [hunk 10]
```diff
@@ -171,5 +174,62 @@ public static SemanticMap GetSemanticMap(this SemanticModel semanticModel, Synta
...
+            {
+                return typeArgumentParameterName;
+            }
+
+            // If there's no type argument and we have an array type, we should pluralize, e.g. frogs[] instead of frog[]
+            if (type.TypeKind == TypeKind.Array && typeArguments.IsEmpty)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs:190]: if you have an array, we should probaly use .ElementType to drive the plural name.

File: src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs [hunk 11]
```diff
@@ -171,5 +174,62 @@ public static SemanticMap GetSemanticMap(this SemanticModel semanticModel, Synta
...
+            // plural forms
+            return type.CreateParameterName(capitalize);
+        }
+
+        private static bool Pluralize(this SemanticModel semanticModel, ITypeSymbol type)
+        {
+            if (type == null)
+                return false;
+
+            if (type.SpecialType == SpecialType.System_String)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs:205]: this isappropriate.  however, it's worth doc'ing why we need to special case.

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs (hunk 11 above)
Comment (allisonchou) [reply src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs:205]: I just moved the method over and I'm actually not quite sure why this string case is needed. Could you possibly elaborate?

Comment (allisonchou) [reply src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs:205]: Ohhh. Is it because string implements System.Collections.Generic.IEnumerable<char>?

File: src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs (hunk 10 above)
Comment (allisonchou) [reply src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs:190]: Would that not be the same behavior as the current code?
I think using ElementType would require casting to ArrayTypeSymbol, right? But this class is language agnostic and so I don't think we can make the cast here.

File: src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs (hunk 11 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs:205]: bingo :)

File: src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs (hunk 10 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs:190]: > Would that not be the same behavior as the current code?

i'm not sure.  would it be? :)

> I think using ElementType would require casting to ArrayTypeSymbol, right?

yup!

> But this class is language agnostic 

So the IXXXSymbols are already language agnostic.  it's totally fine to do something like `if (type is IArrayTypeSymbol arrayType ...)`

Comment (allisonchou) [reply src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs:190]: > i'm not sure. would it be? :)

I don't *think* so? The check verifies that we have an array with no type arguments, so I believe that leaves us only with cases like `new Frog[]`. The existing code will generate `frogs` which I think is the best name.
For arrays with a type argument, the element type is already used in an earlier check.

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs:190]: > For arrays with a type argument,

FWIW, this cannot happen :)

You can think of 'arrays' as a way that generics worked *prior* to generics existing.  But if arrays are handled to already pluralize elsewhere, i guess we don't need to do anything special here :)

Comment (allisonchou) [reply src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs:190]: Ah, I guess I was thinking of something like `Array<Integer>`, but I guess that would fall under a class with a type argument instead of an array with a type argument?

I think we do need to keep in the check to handle the `int[]` array case, but I believe the current logic is equivalent to using `ElementType`.

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Shared/Extensions/SemanticModelExtensions.cs:190]: > Ah, I guess I was thinking of something like Array<Integer>, but I guess that would fall under a class with a type argument instead of an array with a type argument?

Correct :)

If we had generics in .net 1.0 there likely wouldn't have been this ultra special 'array' type.  it would have likely been, as you said: `Array<T>`.  but System.Array dates back to 1.0, non-generic, days and is very special in how this type information is encoded (both for the runtime and language) :)

>but I believe the current logic is equivalent to using ElementType.

SGTM as long as there's a test to validate.
