### PR TITLE
Fix outlining for parenthesized lambdas

### LINKED ISSUE #8259: Outlining spans are not created for parenthesized lambda expressions
image

```C#
class Program
{
    static void Main(string[] args)
    {
        Func<int> f1 = () =>
        {
            return 1;
        };

        Func<int, int> f2 = x =>
        {
            return x;
        };

        Func<int, int, int> f3 = (x, y) =>
        {
            return x + y;
        };

        Func<int> f4 = delegate
        {
            return 1;
        };
    }
}
```

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes #8259

We shipped with outlining working for simple lambdas and anonymous delegates, but parenthesized lambdas apparently got missed at some point.

tagging @dotnet/roslyn-ide

### CODE REVIEW

File: src/EditorFeatures/CSharp/Outlining/CSharpOutliningService.cs [hunk 1]
```diff
@@ -40,6 +40,7 @@ internal class CSharpOutliningService : AbstractOutliningService
             builder.Add<MethodDeclarationSyntax, MethodDeclarationOutliner, MetadataAsSource.MethodDeclarationOutliner>();
             builder.Add<NamespaceDeclarationSyntax, NamespaceDeclarationOutliner>();
             builder.Add<OperatorDeclarationSyntax, OperatorDeclarationOutliner, MetadataAsSource.OperatorDeclarationOutliner>();
+            builder.Add<ParenthesizedLambdaExpressionSyntax, ParenthesizedLambdaExpressionOutliner>();
```
Comment (Pilchie) [inline src/EditorFeatures/CSharp/Outlining/CSharpOutliningService.cs]: Wait, so we have the code for this, we just forgot to add it to the builder when we moved away from MEF? :sob:

**Comment by Pilchie** [comment]
:+1:

File: src/EditorFeatures/CSharp/Outlining/CSharpOutliningService.cs (hunk 1 above)
Comment (DustinCampbell) [inline src/EditorFeatures/CSharp/Outlining/CSharpOutliningService.cs]: Correct. I tried to explain that to you at one point when I lamented them not working for parenthesized lambdas, but I don't think I was clear. We also have lots of unit tests for the parenthesized lambda outliner. It just wasn't being composed.

**Comment by CyrusNajmabadi** [comment]
:+1:
