### PR TITLE
Fix race conditions in attribute asserts

### LINKED ISSUE #52372: NullableReferenceTypesTests.NotNullWhenFalse_WithNullLiteral unit test sometimes fails with an assert that might indicate a real product issue
https://dev.azure.com/dnceng/public/_build/results?buildId=1069907&view=ms.vss-test-web.build-test-results-tab&runId=32887608&resultId=202470&paneView=debug

Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.NullableReferenceTypesTests.NotNullWhenFalse_WithNullLiteral

Result Details
Failed 1h ago
Duration0:00:00.197
Ownernot available
Date started4/2/2021, 9:44:36 AM
Date completed4/2/2021, 9:44:36 AM
Failing since1h ago
Failing since build20210402.15

Debug

Work items

Attachments

History

Helix Test Logs (Beta)

Comments
{ "HelixJobId": "fbb13a8a-0fbe-4e19-a2aa-137b3ffbf1dd", "HelixWorkItemName": "Microsoft.CodeAnalysis.CSharp.Semantic.UnitTests.dll.11" }

Error message
System.AggregateException : One or more errors occurred.
---- System.InvalidOperationException : Assertion failed

Stack trace
```
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
   at Roslyn.Utilities.RoslynParallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/InternalUtilities/RoslynParallel.cs:line 23
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamespaceSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Symbols/Source/SourceNamespaceSymbol_Completion.cs:line 56
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceModuleSymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Symbols/Source/SourceModuleSymbol.cs:line 267
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.ForceComplete(SourceLocation locationOpt, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs:line 913
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSourceDeclarationDiagnostics(SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Func`4 locationFilterOpt, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:line 2951
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsWithoutFiltering(CompilationStage stage, Boolean includeEarlierStages, BindingDiagnosticBag builder, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:line 2721
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, DiagnosticBag diagnostics, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:line 2647
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:line 2639
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:line 2633
   at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyDiagnostics[TCompilation](TCompilation c, DiagnosticDescription[] expected) in /_/src/Compilers/Test/Core/Diagnostics/DiagnosticExtensions.cs:line 103
   at Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.NullableReferenceTypesTests.NotNullWhenFalse_WithNullLiteral() in /_/src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:line 35693
----- Inner Stack Trace -----
   at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage) in /_/src/Compilers/Test/Core/ThrowingTraceListener.cs:line 26
   at System.Diagnostics.TraceListener.Fail(String message)
   at System.Diagnostics.TraceInternal.Fail(String message)
   at System.Diagnostics.Debug.Assert(Boolean condition)
   at Microsoft.CodeAnalysis.CustomAttributesBag`1.get_IsEarlyDecodedWellKnownAttributeDataComputed() in /_/src/Compilers/Core/Portable/Symbols/Attributes/CustomAttributesBag.cs:line 179
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamedTypeSymbol.GetEarlyDecodedWellKnownAttributeData() in /_/src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs:line 855
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamedTypeSymbol.GetAppliedCon```  


From https://github.com/dotnet/roslyn/blob/MainSnapshot/src/Compilers/Core/Portable/Symbols/Attributes/CustomAttributesBag.cs#L179:

```
                // If late attributes are complete, early attributes must also be complete
                Debug.Assert(!IsPartComplete(CustomAttributeBagCompletionPart.DecodedWellKnownAttributeData) || earlyComplete);
```

### PR DESCRIPTION
**Pull request by jaredpar**
There are asserts in our `CustomAttributeBag` to verify we maintain the
invariant that early decoding occurs before the full decoding. The
asserts though done in the getters and take the following form:

```cs
bool earlyComplete = IsPartComplete(CustomAttributeBagCompletionPart.EarlyDecodedWellKnownAttributeData);
// If late attributes are complete, early attributes must also be complete
Debug.Assert(!IsPartComplete(CustomAttributeBagCompletionPart.DecodedWellKnownAttributeData) || earlyComplete);
return earlyComplete;
```

This pattern is subject to race conditions. Consider the case where the
`bool earlyComplete` statement runs to completion and returns `false`. Then
another thread swaps in and completes both early and full decoding. At
that point the original thread resumes and the `Debug.Assert` will fail
yet no invariant has been violated.

Moved the `Debug.Assert` into the setters where we can reliably test the
state invariants.

closes #52372
related to #52368

### CODE REVIEW

**Comment by jaredpar** [comment]
@dotnet/roslyn-compiler PTAL

**Review by RikkiGibson — APPROVED** [review]

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 1)

**Comment by AlekseyTs** [comment]
@jaredpar It looks like bootstrap build is broken. Could it be related to the changes around the asserts?

**Comment by jaredpar** [comment]
@AlekseyTs 
 
The tests were failing due to the asserts I added. I had to remove one because it's a fundamentally racy scenario. It's not really possible to assert full decoding hasn't completed before noting early decoding has completed. Another thread can always interrupt and do an early + full decode. Hence I had to remove that. I left the assert that we verify that early decoding is done before full decoding. That is safe. 

The bootstrap seems to be failing for the existing issue around the VB compiler crashing that I've been looking into. It's been tough to track down because the compiler is apparently exiting with no information. Been working with Sam on how to best track that down.

File: src/Compilers/Core/Portable/Symbols/Attributes/CustomAttributesBag.cs [hunk 1]
```diff
@@ -68,6 +68,8 @@ public bool IsEmpty
         public bool SetEarlyDecodedWellKnownAttributeData(EarlyWellKnownAttributeData data)
         {
             WellKnownAttributeData.Seal(data);
+            // Early decode must complete before full decode
+            Debug.Assert(!IsPartComplete(CustomAttributeBagCompletionPart.DecodedWellKnownAttributeData));
             var setOnOurThread = Interlocked.CompareExchange(ref _earlyDecodedWellKnownAttributeData, data, null) == null;
             NotePartComplete(CustomAttributeBagCompletionPart.EarlyDecodedWellKnownAttributeData);
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Symbols/Attributes/CustomAttributesBag.cs]: >Debug.Assert(!IsPartComplete(CustomAttributeBagCompletionPart.DecodedWellKnownAttributeData)); [](start = 12, length = 94)

Perhaps instead of removing the assert it could be changed to:
```
Debug.Assert(!IsPartComplete(CustomAttributeBagCompletionPart.DecodedWellKnownAttributeData) || IsPartComplete(CustomAttributeBagCompletionPart.EarlyDecodedWellKnownAttributeData));
```

Comment (jaredpar) [reply src/Compilers/Core/Portable/Symbols/Attributes/CustomAttributesBag.cs:74]: Good suggestion. I think I've convinced myself that this is safe 😄 

I was concerned about potential read reordering issues but these are just loading the same block of memory and the state changes are atomic on that same piece of memory. Hence this should be robust to that type of problem.

File: eng/test-rebuild.ps1 [hunk 2]
```diff
@@ -51,6 +51,7 @@ try {
 # Rebuilds with compilation errors
 # Rebuilds with missing references
 # Rebuilds with other issues
+  " --exclude net472\Microsoft.CodeAnalysis.EditorFeatures2.UnitTests.dll" +
```
Comment (RikkiGibson) [inline eng/test-rebuild.ps1:54]: Was this change necessitated by other changes in the PR?

Comment (jaredpar) [reply eng/test-rebuild.ps1:54]: No, I think there is a flaky issue there. I saw it pop up on a few other PRs. I'm looking at the diff locally right now to seew hat's going on.
