### PR TITLE
Avoid duplicate syntax node callbacks for record declarations

### LINKED ISSUE #53136: SyntaxNodeAction is invoked twice for the same syntax node in case of positional records
Microsoft.CodeAnalysis.CSharp: 3.8.0-5.final 

**Steps to Reproduce**:

1. `RegisterSyntaxNodeAction` for `SyntaxKind.RecordDeclaration`
2. Verify that for the following syntax the action is invoked twice:
 `public record Person(string FirstName, string LastName);`

 Looks like the only difference is in the `ContainingSymbol`.

**Expected Behavior**:
 The action is invoked only once for the RecordDeclaration.
**Actual Behavior**:
The action is invoked twice for the same RecordDeclaration.

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #53136

Verified that the added unit test fails with duplicate diagnostics before the product fix.

### CODE REVIEW

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs [hunk 1]
```diff
@@ -2824,6 +2824,15 @@ void executeCodeBlockActions(ImmutableArray<SyntaxNode> executableCodeBlocks, IE
...
             AnalyzerExecutor analyzerExecutor)
         {
+            // Skip syntax nodes when analyzing record declaration constructor to avoid duplicate syntax node callbacks.
+            // We will analyze these nodes while analyzing the record declaration type symbol.
+            if (declaredSymbol is IMethodSymbol method &&
+                method.ContainingType.IsRecord &&
+                method.MethodKind == MethodKind.Constructor)
+            {
+                return ImmutableArray<SyntaxNode>.Empty;
+            }
```
Comment (Youssef1313) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs:2834]: The two actions that were fired previously had two different `context.ContainingSymbol`s (the type and the primary ctor). Do we know which one we're ignoring now or is it even deterministic?

**Comment by AlekseyTs** [comment]
@mavasani Do we have similar issue with top-level statements?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs (hunk 1 above)
Comment (sharwell) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs:2834]: The skipped callback _should_ be for a syntax node, not a symbol. Maybe add some additional tests showing each related callback occurs exactly once for syntax and symbols in a record declaration?

Comment (Youssef1313) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs:2834]: @sharwell I know it's for a syntax node, but it's still tied with a symbol I think? I'm referring to [`SyntaxNodeAnalysisContext.ContainingSymbol`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.diagnostics.syntaxnodeanalysiscontext.containingsymbol?view=roslyn-dotnet-4.0.1#Microsoft_CodeAnalysis_Diagnostics_SyntaxNodeAnalysisContext_ContainingSymbol)

Comment (sharwell) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs:2834]: I had no idea that property existed 🤣 

That said, I believe the type should be the containing symbol.

Comment (Youssef1313) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs:2834]: @sharwell Yeah I never needed to use it. All the property usages in Roslyn (per sourceroslyn.io) are only tests. I don't know why it even existed 😄 

> That said, I believe the type should be the containing symbol.

That's exactly what I meant.

File: src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs [hunk 2]
```diff
@@ -3762,5 +3762,43 @@ public void VerifyCachedModel(SyntaxTree tree, SemanticModel model)
...
+        {
+            string source = @"
+public record A(int X, int Y);";
+            var analyzers = new DiagnosticAnalyzer[] { new RecordDeclarationAnalyzer() };
+
+            CreateCompilation(new[] { source, IsExternalInitTypeDefinition })
+                .VerifyDiagnostics()
+                .VerifyAnalyzerDiagnostics(analyzers, null, null,
+                     Diagnostic("MyDiagnostic", @"public record A(int X, int Y);").WithLocation(2, 1));
+        }
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs:3802]: need test that shows that we hit any other declared constructors the record has (e.g. non-primary-constructor constructors).

Comment (mavasani) [reply src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs:3802]: Yes, @AlekseyTs has added existing tests which already failed with my changes here. I’ll convert the PR to draft while I work through this.

Comment (Youssef1313) [reply src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs:3802]: @mavasani I attempted to fix this in https://github.com/dotnet/roslyn/pull/58496, which I hope can help even if it's not the correct fix.

Comment (mavasani) [reply src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs:3802]: My latest commits ensure that the tests now pass. Cyrus, your original concern is address as existing tests already verify we hit all other declared constructors in the record.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 3]
```diff
@@ -26281,11 +26281,9 @@ class Attr3 : System.Attribute {}
             Assert.Equal(1, analyzer.FireCount7);
             Assert.Equal(1, analyzer.FireCount8);
             Assert.Equal(1, analyzer.FireCount9);
-            Assert.Equal(1, analyzer.FireCount10);
```
Comment (mavasani) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:26284]: @AlekseyTs I had to adjust the existing tests to match the new behavior. This leads to holes now in the `FireCountXXX` counter in the analyzer. Please let me know if current change to tests looks fine or you'd prefer I adjust the `XXX` suffixes to avoid the counter holes.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs [hunk 4]
```diff
@@ -5697,7 +5696,6 @@ private class AnalyzerActions_01_Analyzer : DiagnosticAnalyzer
         {
             public int FireCount0;
             public int FireCountRecordStructDeclarationA;
-            public int FireCountRecordStructDeclarationACtor;
```
Comment (Youssef1313) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs:5700]: Consider keeping the integer but assert against the new expected value.

**Comment by mavasani** [comment]
> Do we have similar issue with top-level statements?

@AlekseyTs - did you mean issue with records as top-level statements or just top-level statements in general? I am not really sure about the existing behavior for either of these, but can verify and add tests as appropriate. It would be helpful if you can also point me to any existing test files with analyzer tests for top-level statements, if you are aware.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs (hunk 4 above)
Comment (mavasani) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordStructTests.cs:5700]: @Youssef1313 After this change, `FireCountRecordStructDeclarationACtor` has no writes and would always have its default value. We do assert that the default case in the switch is never encountered.

**Comment by Youssef1313** [comment]
@mavasani

https://github.com/dotnet/roslyn/blob/80d7e32b44a83246eb26ecac9bca3c2283b8d938/src/Compilers/CSharp/Test/Semantic/Semantics/SimpleProgramsTests.cs#L5138

**Comment by Youssef1313** [comment]
@mavasani This specific assert may be undesired behavior:

https://github.com/dotnet/roslyn/blob/80d7e32b44a83246eb26ecac9bca3c2283b8d938/src/Compilers/CSharp/Test/Semantic/Semantics/SimpleProgramsTests.cs#L5714

**Comment by Youssef1313** [comment]
Here is a *seemingly* suspicious assert:

https://github.com/dotnet/roslyn/blob/80d7e32b44a83246eb26ecac9bca3c2283b8d938/src/Compilers/CSharp/Test/Semantic/Semantics/SimpleProgramsTests.cs#L5111-L5122

Specifically, both `FireCount3` and `FireCount5` are 1

Here is where those counters are incremented:

https://github.com/dotnet/roslyn/blob/80d7e32b44a83246eb26ecac9bca3c2283b8d938/src/Compilers/CSharp/Test/Semantic/Semantics/SimpleProgramsTests.cs#L5156

https://github.com/dotnet/roslyn/blob/80d7e32b44a83246eb26ecac9bca3c2283b8d938/src/Compilers/CSharp/Test/Semantic/Semantics/SimpleProgramsTests.cs#L5189-L5199

So it looks like `Handle2` was called for the same syntax node but different `ContainingSymbol`.

**Comment by mavasani** [comment]
> Here is a _seemingly_ suspicious assert:
> 
> https://github.com/dotnet/roslyn/blob/80d7e32b44a83246eb26ecac9bca3c2283b8d938/src/Compilers/CSharp/Test/Semantic/Semantics/SimpleProgramsTests.cs#L5111-L5122
> 
> Specifically, both `FireCount3` and `FireCount5` are 1
> 
> Here is where those counters are incremented:
> 
> https://github.com/dotnet/roslyn/blob/80d7e32b44a83246eb26ecac9bca3c2283b8d938/src/Compilers/CSharp/Test/Semantic/Semantics/SimpleProgramsTests.cs#L5156
> 
> https://github.com/dotnet/roslyn/blob/80d7e32b44a83246eb26ecac9bca3c2283b8d938/src/Compilers/CSharp/Test/Semantic/Semantics/SimpleProgramsTests.cs#L5189-L5199
> 
> So it looks like `Handle2` was called for the same syntax node but different `ContainingSymbol`.

Thanks @Youssef1313. That confirms similar issue exists with top-level statements. I am going to create a separate tracking issue and PR to address that one.

**Review by Youssef1313 — COMMENTED** [review]
I think it's worth adding tests for syntax checked in this method:

https://github.com/dotnet/roslyn/blob/cb400a925dc235b505ee2163dc1501d3433d2a12/src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs#L2422

- [ ] `SyntaxKind.CompilationUnit` (there are already tests that likely need to be adjusted)
- [ ] `SyntaxKind.RecordDeclaration` (already done)
- [ ] `SyntaxKind.RecordStructDeclaration` (already done)
- [ ] `SyntaxKind.PrimaryConstructorBaseType`
- [ ] `SyntaxKind.Parameter`

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs (hunk 3 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:26284]: >  I had to adjust the existing tests to match the new behavior. This leads to holes now in the FireCountXXX counter in the analyzer. Please let me know if current change to tests looks fine or you'd prefer I adjust the XXX suffixes to avoid the counter holes.

Are you saying you remove some of the fields because they become obsolete? I am fine with the gaps in names.

Comment (mavasani) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:26284]: Yes, that is correct

**Comment by AlekseyTs** [comment]
>> Do we have similar issue with top-level statements?

> did you mean issue with records as top-level statements or just top-level statements in general?

No the question is not related to records in any way. I think we might have similar "duplicate syntax node callbacks" problem for top-level statements. In particular around a compilation unit node, it declares a namespace, an entry point method and its containing type at the same time.

**Comment by mavasani** [comment]
Thanks @AlekseyTs - I have filed https://github.com/dotnet/roslyn/issues/58561 for top-level statements.

File: src/Compilers/Core/Portable/Compilation/SemanticModel.cs [hunk 5]
```diff
@@ -875,6 +875,8 @@ public PreprocessingSymbolInfo GetPreprocessingSymbolInfo(SyntaxNode nameSyntax)
 
         internal virtual Func<SyntaxNode, bool>? GetSyntaxNodesToAnalyzeFilter(SyntaxNode declaredNode, ISymbol declaredSymbol) => null;
 
+        internal abstract bool IsSynthesizedRecordConstructor(ISymbol symbol);
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Compilation/SemanticModel.cs:878]: >internal abstract bool IsSynthesizedRecordConstructor(ISymbol symbol); [](http://example.com/codeflow?start=8&length=70)

This change looks surprising to me. I felt that we could simply revert relevant changes made in [https://github.com/dotnet/roslyn/pull/46308](https://github.com/dotnet/roslyn/pull/46308).

**Comment by AlekseyTs** [comment]
My intuition tells me that we are likely taking a "wrong" approach for achieving the goal. I feel like a better approach would be to revert relevant parts of  #46308 instead of adding special APIs to neutralize their effect. We could simply remove the effect in the first place. I also think that it might make sense to deal with top level statements at the same time and in the same manner (finding the PR that changed the behavior for them), because they are likely to be closely related in terms of implementation strategy. Records probably build on top of what was added for top level statements, etc. And dealing with them together is likely to be much easier, more code can be removed at once rather than carefully trying to maintain an undesired behavior for one feature, but not for the other.

**Comment by mavasani** [comment]
@AlekseyTs The changes made in #46308 are correct and required - it is adding missing executable code blocks in declarations which need callbacks. We can make a minor change in that the `PrimaryConstructorBaseTypeSyntax` added in [line 108-111](https://github.com/dotnet/roslyn/pull/46308/files#diff-eaf15fa2d12db0e74ce574afeb6805007c8fa144365eda90214fec28ac951e22R108-R111) should be added when we are processing the record type symbol, not it's synthesized ctor so the analyzer callback gets the correct containing symbol.

The core reason why the approach chosen in this PR is the only feasible approach to tackle this issue is that syntax node analysis in analyzer driver works off SymbolDeclared compilation events and divides the syntax nodes by their owning symbol. For every declared symbol, we walk through its declarations and executable code blocks and descend into its nodes until we hit a node that declares another symbol, at which point we don't descend further and let those nodes be processed when the corresponding symbol's SymbolDeclared event is raised.

Given the above, any syntax node which declares multiple non-ImplicitlyDeclared symbols will get multiple symbol declared events and multiple syntax node callbacks for the declaring syntax node by default. The code added in #46308 is not the reason for the multiple callbacks. 

> I also think that it might make sense to deal with top level statements at the same time and in the same manner

That sounds reasonable. Once we come to a consensus on the nature of the fix, I can combine both changes into this PR.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs [hunk 6]
```diff
@@ -2864,17 +2864,27 @@ void executeCodeBlockActions(ImmutableArray<SyntaxNode> executableCodeBlocks, IE
                 first = false;
             }
 
+            var isSynthesizedRecordConstructor = semanticModel.IsSynthesizedRecordConstructor(declaredSymbol);
```
[the remark this answers is not in the document]
Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs:2867]: @AlekseyTs Everything you suggested sounds good, I'll give it a try for records first and then add support for top-level statements in this same PR. Thanks!

**Review by Youssef1313 — COMMENTED** [review]
Note: It might worth adding some comments around the interesting parts of code of https://github.com/dotnet/roslyn/pull/46308 so that whenever a developer adds a new syntax kind that is to cause a problem, hopefully the comment will remind the developer to have the appropriate fix.

File: src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs [hunk 7]
```diff
@@ -2352,6 +2352,11 @@ internal override Symbol RemapSymbolIfNecessaryCore(Symbol symbol)
             throw ExceptionUtilities.Unreachable;
         }
 
+        internal override bool ShouldSkipSyntaxNodeAnalysis(SyntaxNode declaredNode, ISymbol declaredSymbol)
+        {
+            throw new NotImplementedException();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:2357]: >throw new NotImplementedException(); [](http://example.com/codeflow?start=12&length=36)

```throw ExceptionUtilities.Unreachable;```? As in the helper above?

Comment (mavasani) [reply src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs:2357]: Yes sure

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs [hunk 8]
```diff
@@ -2864,30 +2864,49 @@ void executeCodeBlockActions(ImmutableArray<SyntaxNode> executableCodeBlocks, IE
...
+            foreach (var node in declaredNode.DescendantNodesAndSelf(descendIntoChildren, descendIntoTrivia: true))
             {
-                if (!shouldAddNode(node))
+                // Skip nodes in descendantDeclsToSkip.
+                if (descendantDeclsToSkip?.Contains(node) == true)
                     continue;
 
-                // Skip node if we are doing partial analysis and the current node is outside the analysis scope.
-                if (isPartialDeclAnalysis && !analysisScope.ShouldAnalyze(node))
+                if (shouldSkipNodeAndDescendants(node))
```
Comment (mavasani) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs:2875]: So, I wasn’t able to completely separate the filters into shouldAnalyzeNode and descendIntoChildren, but I simplified the descendIntoChildren to completely be based off descendantDeclsToSkip and the language specific filters can either filter out just an individual node OR a node and all it’s descendants (existing filter). This did simplify the code quite a bit. Let me know if this looks reasonable to you.

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs [hunk 9]
```diff
@@ -2528,5 +2528,19 @@ internal override Symbol RemapSymbolIfNecessaryCore(Symbol symbol)
...
             return null;
         }
+
+        internal override bool ShouldSkipSyntaxNodeAnalysis(SyntaxNode declaredNode, ISymbol declaredSymbol)
+        {
+            // Skip the topmost record declaration syntax node when analyzing synthesized record declaration constructor
+            // to avoid duplicate syntax node callbacks.
+            // We will analyze this node when analyzing the record declaration type symbol.
+            if (declaredNode.Kind() is SyntaxKind.RecordDeclaration or SyntaxKind.RecordStructDeclaration &&
+                declaredSymbol.GetSymbol() is SynthesizedRecordConstructor)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:2538]: It feels like we can simplify and align this check with how the helper above is doing that. This will make it easier to see relationship between the two and keep them aligned in the future. I am thinking about something like ```declaredNode is RecordDeclarationSyntax && declaredSymbol.Kind is SymbolKind.Method```

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs (hunk 8 above)
Comment (AlekseyTs) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs:2875]: > So, I wasn’t able to completely separate the filters into shouldAnalyzeNode and descendIntoChildren, but I simplified the descendIntoChildren to completely be based off descendantDeclsToSkip and the language specific filters can either filter out just an individual node OR a node and all it’s descendants (existing filter). This did simplify the code quite a bit. Let me know if this looks reasonable to you.

It feels like the new code is unnecessary verbose and probably a lot less optimal (nodes are filtered out later, more nodes are iterated through). Even if you find it difficult to pull apart what ```shouldAddNode``` used to be into two targeted delegates, I think it would be sufficient to add a new condition to the existing ```if``` in the loop. I am thinking about code like:
```
            bool shouldAddNode(SyntaxNode node) => (descendantDeclsToSkip == null || !descendantDeclsToSkip.Contains(node)) && (additionalFilter is null || additionalFilter(node));
            var nodeBuilder = ArrayBuilder<SyntaxNode>.GetInstance();
            foreach (var node in declaredNode.DescendantNodesAndSelf(descendIntoChildren: shouldAddNode, descendIntoTrivia: true))
            {
                if (shouldAddNode(node) &&
                    !semanticModel.ShouldSkipSyntaxNodeAnalysis(declaredNode, declaredSymbol) &&
                    (!isPartialDeclAnalysis || analysisScope.ShouldAnalyze(node)))
                {
                    nodeBuilder.Add(node);
                }
            }

```

File: src/Compilers/Core/Portable/Compilation/SemanticModel.cs [hunk 10]
```diff
@@ -874,6 +874,7 @@ public PreprocessingSymbolInfo GetPreprocessingSymbolInfo(SyntaxNode nameSyntax)
         internal abstract void ComputeDeclarationsInNode(SyntaxNode node, ISymbol associatedSymbol, bool getSymbol, ArrayBuilder<DeclarationInfo> builder, CancellationToken cancellationToken, int? levelsToCompute = null);
 
         internal virtual Func<SyntaxNode, bool>? GetSyntaxNodesToAnalyzeFilter(SyntaxNode declaredNode, ISymbol declaredSymbol) => null;
+        internal virtual bool ShouldSkipSyntaxNodeAnalysis(SyntaxNode declaredNode, ISymbol declaredSymbol) => false;
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Compilation/SemanticModel.cs:877]: >ShouldSkipSyntaxNodeAnalysis [](http://example.com/codeflow?start=30&length=28)

It is unfortunate that you were not able to clearly separate the two filters. I was hoping that we would be able to rename the previous helper to something like "DescendIntoChildrenSyntaxNodesToAnalyzeFilter" and have its implementation follow the new purpose. However, I can see that that might require some non-trivial changes in the implementation of the helper and it is fine to avoid the additional risk and complexity at this point. However, I think it would be good to add some comment clarifying the distinction between the helpers for the benefit of implementers. Otherwise, an implementer could be confused where exactly a node should be filtered and not filtered out. For example, right now one might ask a question: "Why do we need the ```ShouldSkipSyntaxNodeAnalysis``` when ```GetSyntaxNodesToAnalyzeFilter``` could filter that node out. It would be good to have this question answered in a doc comment.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 5)

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 7), assuming CI is passing.

**Comment by mavasani** [comment]
Thanks @AlekseyTs! @dotnet/roslyn-compiler for second review.

**Comment by mavasani** [comment]
@dotnet/roslyn-compiler for second review.

**Comment by mavasani** [comment]
@dotnet/roslyn-compiler for second review.

**Review by cston — APPROVED** [review]

**Comment by mavasani** [comment]
Thank you @cston

**Comment by mavasani** [comment]
@AlekseyTs @Youssef1313 I will create a follow-up PR on the same lines for top level statements.
