### PR TITLE
Bug fixes and improvements to UseLocalFunction

### LINKED ISSUE #24760: 'Use local function' should be offered for anonymous methods as well as lambdas
**Steps to Reproduce**:

```c#
Action a = () => { Console.WriteLine(); };
Action b = delegate () { Console.WriteLine(); };
```

Click on `a`. 'Use local function' is suggested. No such thing on `b`.

### LINKED ISSUE #24764: 'Use local function' breaks code that uses named arguments
**Steps to Reproduce**:

```c#
delegate void MyDelegate(string arg);

void M()
{
    MyDelegate d = s => { };

    d(arg: "hello");
}
```

after invoking 'Use local function' on `d`:

```c#
void d(string s)
{ }

d(arg: "hello");
```

code doesn't compile because there's no `arg` on `d`.

### PR DESCRIPTION
**Pull request by Neme12**
### Features added:
- **support for anonymous methods**: fixes #24760
- support for split initialization with no initializer - here there used to be a fix offered:
    ```c#
    Action a = null;
    a = () => { };
    ```
   here there was not (now there is too):
    ```c#
    Action a;
    a = () => { };
    ```
### Bugs fixed:
Sorry for including a new feature & bug fixes in one PR. I didn't originally set out to fix bugs but I found so many of them while working on the feature:
fixes #24764
https://github.com/dotnet/roslyn/issues/24760#issuecomment-364655480
https://github.com/dotnet/roslyn/issues/24760#issuecomment-364764542
https://github.com/dotnet/roslyn/issues/24760#issuecomment-364807853
https://github.com/dotnet/roslyn/issues/24760#issuecomment-364879443
https://github.com/dotnet/roslyn/issues/24760#issuecomment-364935495
with a lot of tests added to cover these

### Performance impact
Most of the work I did is the code fix (which is invoked on demand), not the analyzer. So I hope none.

### CODE REVIEW

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs [hunk 1]
```diff
@@ -46,18 +46,18 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
             var nodesToTrack = new HashSet<SyntaxNode>();
             var explicitInvokeCalls = new List<MemberAccessExpressionSyntax>();
             foreach (var diagnostic in diagnostics)
             {
                 var localDeclaration = (LocalDeclarationStatementSyntax)diagnostic.AdditionalLocations[0].FindNode(cancellationToken);
-                var lambda = (LambdaExpressionSyntax)diagnostic.AdditionalLocations[1].FindNode(cancellationToken);
+                var function = (AnonymousFunctionExpressionSyntax)diagnostic.AdditionalLocations[1].FindNode(cancellationToken);
 
-                localDeclarationToLambda[localDeclaration] = lambda;
+                localDeclarationToFunction[localDeclaration] = function;
```
Comment (Neme12) [inline src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: still not sure about the name "function"... but "localDeclarationToAnonymousFunction" is just too long

File: src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs [hunk 2]
```diff
@@ -256,6 +256,46 @@ void M()
...
+    void M()
+    {
+        int fibonacci(int v)
+        {
+            if (v <= 1)
+            {
+                return 1;
+            }
+
+            return fibonacci(v - 1, v - 2);
```
Comment (Neme12) [inline src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: @CyrusNajmabadi git says you are responsible for this... fibonacci is obviously called with the wrong number number of arguments, is this intentional?

File: src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs [hunk 3]
```diff
@@ -1694,6 +1816,133 @@ public void Caller(T t)
...
+    void M()
+    {
+        string local(string s = ""hello"")
+        { return s; }
+    }
+}");
+        }
+
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseLocalFunction)]
+        public async Task TestWithAsync1()
```
Comment (Neme12) [inline src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: I added some tests for async, there weren't any

**Comment by Neme12** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

File: src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs (hunk 2 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: not intentional.  but it's doing the right thing.

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: 'localDeclarationToAnonymousFunction' seems fine to me.

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs [hunk 4]
```diff
@@ -159,60 +159,48 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
-        private ParameterListSyntax GenerateSimpleLambdaParameterList(
-            SemanticModel semanticModel, SimpleLambdaExpressionSyntax lambdaExpression, IMethodSymbol delegateInvokeMethod, CancellationToken cancellationToken)
-        {
-            var parameter = semanticModel.GetDeclaredSymbol(lambdaExpression.Parameter, cancellationToken);
-            var type = parameter?.Type.GenerateTypeSyntax() ?? s_objectType;
+            int i = 0;
+
+            return parameterList != null
+                ? parameterList.ReplaceNodes(parameterList.Parameters, (parameterNode, _) => PromoteParameter(parameterNode, i++))
+                : SyntaxFactory.ParameterList(SyntaxFactory.SeparatedList<ParameterSyntax>().Add(PromoteParameter(simpleParameter, 0)));
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: instead of calling .Add, just pass PromoteParameter directory to SeparatedList();

Comment (Neme12) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: ok... with new[]? this was there before, so I presumed other people were smarter than me and didn't change it

File: src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs [hunk 5]
```diff
@@ -1694,6 +1816,133 @@ public void Caller(T t)
...
+    }
+}",
+ @"class C
+{
+    delegate string MyDelegate(string arg = ""hello"");
+
+    void M()
+    {
+        string local(string s = ""hello"")
+        { return s; }
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: formatting seems non-great.  is this the same we do for lambdas?

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs (hunk 4 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: > ok... with new[]?

No, .SeparatedList can take a single item and make a list out of it.

File: src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs [hunk 6]
```diff
@@ -256,6 +256,46 @@ void M()
...
+        public async Task TestSimpleInitialization_AnonymousMethod()
+        {
+            await TestInRegularAndScriptAsync(
+@"using System;
+
+class C
+{
+    void M()
+    {
+        Func<int, int> [||]fibonacci = delegate (int v)
```
[the remark this answers is not in the document]
Comment (Neme12) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: oops

File: src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs (hunk 5 above)
Comment (Neme12) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: @CyrusNajmabadi yes... it's already reported here #23872

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: do you want to take a stab at fixing that while you're here?  Basically, the logic i would have is:  if hte lambda body and parameter is on the same line, then use non-elastic trivia with the new local function that is created between the ```)``` and the body.

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs (hunk 4 above)
Comment (Neme12) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: you mean SingletoneSeparatedList?

File: src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs (hunk 5 above)
Comment (Neme12) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: i don't know how those things work

File: src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs (hunk 2 above)
Comment (Neme12) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: to fix or not to fix?

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs (hunk 4 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: Sure :)

File: src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs (hunk 5 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: Would you like to know more? :)

Comment (Neme12) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: sure

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: i'm on gitter if you want to chat there :)

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs [hunk 7]
```diff
@@ -159,60 +158,46 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
-            var type = parameter?.Type.GenerateTypeSyntax() ?? s_objectType;
+            return parameterList != null
+                ? parameterList.ReplaceNodes(parameterList.Parameters, (parameterNode, _) => PromoteParameter(parameterNode, delegateMethod.Parameters[i++]))
+                : SyntaxFactory.ParameterList(SyntaxFactory.SeparatedList(delegateMethod.Parameters.Select(parameter =>
+                    PromoteParameter(SyntaxFactory.Parameter(parameter.Name.ToIdentifierToken()), parameter))));
 
-            var parameterSyntax = SyntaxFactory.Parameter(lambdaExpression.Parameter.Identifier).WithType(type);
-            var param = delegateInvokeMethod.Parameters[0];
-            if (param.HasExplicitDefaultValue)
+            ParameterSyntax PromoteParameter(ParameterSyntax parameterNode, IParameterSymbol delegateParameter)
```
Comment (Neme12) [inline src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: I noticed I'm not capturing any variables anymore, should it still be a local function?

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs [hunk 8]
```diff
@@ -159,60 +158,46 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
+                    parameterNode = parameterNode.WithDefault(GetDefaultValue(delegateParameter));
+                }
+
+                return parameterNode;
+            }
         }
 
-        private ParameterListSyntax GenerateParenthesizedLambdaParameterList(
-            SemanticModel semanticModel, ParenthesizedLambdaExpressionSyntax lambdaExpression, IMethodSymbol delegateInvokeMethod, CancellationToken cancellationToken)
+        private static ParameterListSyntax GetOrMakeParameterList(AnonymousFunctionExpressionSyntax anonymousFunction)
```
Comment (Neme12) [inline src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: not a great name... hard to come up with one, because this thing actually does return null if it's an anonymous method with no parameter list - i concluded that this case is really fundamentally different because it isn't equivalent to having an empty parameter list there, this should really be a special case

File: src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (Neme12) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: now we do

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs (hunk 7 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: My thoughts are:  if the code is readable and maintainable (and you're not violating any guidelines), then code however you like.  WRT local functions, we've cautiously accepted them.  We don't go overboard with them, but we allow devs to use them if they feel like it's worthwhile.

--

My personal preference is that all local functions go *after* teh last return point in the method.  i.e. after the final ```return``` statement in the method.  i usually add a ```// local functions``` comment as well, as i find that helps distinguish these from normal methods.  Otherwise, when reviewing i have a tendency to then say "you're missing accessibility modifiers here" since it's harder to tell in github when something is a method vs local function.

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs (hunk 8 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: So, originally, we had separate helpers to deal with the simple lambda and parenthesized lambda cases.  I don't see why it would be that bad to have 3 helpers here, maybe with sub helpers that are shared.

File: src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs (hunk 2 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: to fix.  the code is technically invalid.  But the fix changes it to be just as invalid as before.  If we didn't fix, users could be confused as to why the fix wasn't be offered.

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs [hunk 9]
```diff
@@ -71,46 +71,46 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
                 var currentLocalDeclaration = currentRoot.GetCurrentNode(originalLocalDeclaration);
-                var currentLambda = currentRoot.GetCurrentNode(originalLambda);
+                var currentAnonymousFunction = currentRoot.GetCurrentNode(originalAnonymousFunction);
 
                 currentRoot = ReplaceAnonymousWithLocalFunction(
                     document.Project.Solution.Workspace, currentRoot,
-                    currentLocalDeclaration, currentLambda,
-                    delegateType, parameterList, explicitInvokeCalls.Select(node => currentRoot.GetCurrentNode(node)).ToImmutableArray(),
+                    currentLocalDeclaration, currentAnonymousFunction,
+                    delegateType.DelegateInvokeMethod, parameterList, explicitInvokeCalls.Select(node => currentRoot.GetCurrentNode(node)).ToImmutableArray(),
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: nit: could you put explicit... on the next line?  Thanks!

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs (hunk 8 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: Also, in this case, why not always return a parameter list, even for anonymous-delegates.  if they don't ahve an existing parameter list, then just synthesize one.  That's what we do for simple-lambdas.

Comment (Neme12) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: @CyrusNajmabadi that would be the wrong thing to do because as I sad a missing parameter list is not equivalent to an empty one there. The delegate method may have a lot of parameters after all, so I have to check if this returns null and in that case forget about this and synthesize parameters from the delegate method.

With simple lambdas this is OK because there's no difference between a simple lambda and a parenthesized one with the same argument.

File: src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs (hunk 2 above)
Comment (Neme12) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: maybe it's good after all to have tests with invalid code?

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs (hunk 8 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: Ah, i see what you mean.  Yes, an empty parameter list is wrong.  You shoudl synthesize one based on the types/names of hte delegate Invoke method.

**Comment by CyrusNajmabadi** [comment]
> The delegate method may have a lot of parameters after all, so I have to check if this returns null
Gotcha.  Call is TryGetOrCreateParameterList then :)  Doc that for anonymous-delegates, ```null``` may be returned.

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs (hunk 8 above)
Comment (Neme12) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: it's already implemented, you can see a new test for it

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: I think my point is: do that in this method.  i.e. call the method GetOrCreateParameterList.  In the case of an anonymous-delegate with no parameter list, just do the 'Create' part here (possibly using helpers you have elsewhere).

Comment (Neme12) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: I'd prefer not to.
1. this is sort of a general purpose method that could be used to extract a parameter list from lambdas/delegates
2. right now both cases are handled right next to each other on the next line. that's how i like it, they won't deviate as much from each other

Comment (Neme12) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: if what you mean is just empty an empty parameter list and then check if it's empty... again, that's wrong because an empty one isn't the same as a missing one.

Comment (Neme12) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: in broken code like this:
```c#
Action<string> a = delegate() {};
```
I convert it to a local function taking no parameters (the code is already broken anyway). But if you omit the `()`, I do create a parameter list for you.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: > if what you mean is just return an empty parameter list and then check if it's empty and fill it with something... 

Definitely not what i meant :)

> I'd prefer not to.

Your call :)  It was just a suggestion.

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs [hunk 10]
```diff
@@ -46,111 +46,128 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
         {
             var semanticModel = await document.GetSemanticModelAsync(cancellationToken).ConfigureAwait(false);
 
-            var localDeclarationToLambda = new Dictionary<LocalDeclarationStatementSyntax, LambdaExpressionSyntax>();
```
Comment (Neme12) [inline src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: IMO this should never have been a dictionary. It wasn't used for dictionary lookup, only iteration. If all you need is iteration, just use a List. The dictionary was just a hacky way to group 2 things together.

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs [hunk 11]
```diff
@@ -46,111 +46,128 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
+            var nodesFromDiagnostics = new List<(
+                LocalDeclarationStatementSyntax declaration,
+                AnonymousFunctionExpressionSyntax function,
+                List<InvocationExpressionSyntax> invocations)>();
```
Comment (Neme12) [inline src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: that said, I'm still not convinced that a tuple with 3 elements is the best thing to do here, but
1. i don't think this should be a named type, because
    1. i can't even come up with a name for it
    2. it's only used locally in this method
2. as i said, what other people might have thought about doing here is a dictionary or after this fix, 2 dictionaries, one from declaration to anonymous function, one from declaration to invocation. i think that's not the right solution because again, there's no actual lookup needed when you're just iterating through it. this is not what hash tables are for.

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs [hunk 12]
```diff
@@ -46,111 +46,128 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
+
             var nodesToTrack = new HashSet<SyntaxNode>();
```
Comment (Neme12) [inline src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: speaking of which, why is this a hash set? it's also only used for iterating to add those to nodesToTrack. is there a concern for finding duplications? but if there are duplications then it's probably a bug in the analyzer

**Comment by Neme12** [comment]
The only remaining bug I know of is this:

```c#
Func<string, string> a = s => s;

a.Invoke(a.Invoke(null));
```

Both invocations have to be replaced. I don't know how to fix it.

**Comment by Neme12** [comment]
Alright, I can't think of any other ways how to break this.

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs [hunk 13]
```diff
@@ -159,60 +172,80 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
-                    var param = delegateInvokeMethod.Parameters[i++];
-                    if (param.HasExplicitDefaultValue)
-                    {
-                        parameterNode = parameterNode.WithDefault(GetDefaultValue(param));
-                    }
-
-                    return parameterNode;
-                });
+            var name = argumentNameColon.Name.Identifier.ValueText;
+            return method.Parameters.IndexOf(p => p.Name == name);
```
Comment (Neme12) [inline src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: This logic is basically copied from [ArgumentSyntaxExtensions.DetermineParameter](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Extensions/ArgumentSyntaxExtensions.cs,46). I'm not too happy about having to reimplement the logic for C# argument resolution here, but I suppose it's fine. `DetermineParameter` also takes care of positional arguments which I don't need but more importantly it requires the semantic model, I can't just give it a symbol for it to use.

If I used it, then I'd have to either recalculate the semantic model after every change, or bring alone old nodes along with the new ones etc etc. This seemed like the simplest solution after all. Argument resolution isn't likely to change anyway.

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs (hunk 10 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: That seems fine.  Some people (like me) say "there's an association here.  a dictionary is a clear way to express that association".  A list of tuples is equally fine for that purpose if you want :)

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs (hunk 12 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: Simplicity.  You can feel free to use another type if you want.

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs (hunk 10 above)
Comment (Neme12) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: right - but there's no clear "key" and no clear "value", meaning there's no clear association *from* one thing *to* another, there's only association *between* them

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: That seems fine. Some people (like me) say "there's an association here. a dictionary is a clear way to express that association". A list of tuples is equally fine for that purpose if you want :)

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs (hunk 12 above)
Comment (Neme12) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: i'll leave it there, but why is `new HashSet<SyntaxNode>` simpler than `new List<SyntaxNode>`?

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: It's simpler (to me) because it means i don't even have to think about what might go wrong if i get a duplicate.  it just can't happen.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: Other's may think a list is simpler as it may not mask a duplication bug.  To each their own :)

**Comment by Neme12** [comment]
By the way, 4 of the bugs I fixed actually crash the code fix and are a regression from 15.5.

File: src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs (hunk 2 above)
Comment (Neme12) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: I actually meant whether I should have "fixed" the tests, I agree with should offer a fix even though it's invalid

**Comment by CyrusNajmabadi** [comment]
> I actually meant whether I should have "fixed" the tests,

No.  The tests are fine.  Please leave them as is.

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionDiagnosticAnalyzer.cs [hunk 14]
```diff
@@ -238,17 +238,22 @@ private void SyntaxNodeAction(SyntaxNodeAnalysisContext syntaxContext, INamedTyp
...
-                        if (nodeToCheck.Parent is MemberAccessExpressionSyntax memberAccessExpression)
+                        if (nodeToCheck.Parent is InvocationExpressionSyntax invocationExpression)
                         {
-                            if (memberAccessExpression.Name.Identifier.Text != WellKnownMemberNames.DelegateInvokeName)
+                            invocations.Add(invocationExpression.GetLocation());
+                        }
+                        else if (nodeToCheck.Parent is MemberAccessExpressionSyntax memberAccessExpression)
+                        {
+                            if (memberAccessExpression.Parent is InvocationExpressionSyntax explicitInvocationExpression &&
+                                memberAccessExpression.Name.Identifier.Text == WellKnownMemberNames.DelegateInvokeName)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionDiagnosticAnalyzer.cs]: this should be .ValueText.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionDiagnosticAnalyzer.cs]: (yes, previous code was wrong as well).

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs [hunk 15]
```diff
@@ -159,60 +172,80 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
-            var type = parameter?.Type.GenerateTypeSyntax() ?? s_objectType;
-
-            var parameterSyntax = SyntaxFactory.Parameter(lambdaExpression.Parameter.Identifier).WithType(type);
-            var param = delegateInvokeMethod.Parameters[0];
-            if (param.HasExplicitDefaultValue)
+            return invocation.ReplaceNodes(invocation.ArgumentList.Arguments, (argumentNode, _) =>
             {
-                parameterSyntax = parameterSyntax.WithDefault(GetDefaultValue(param));
-            }
+                if (argumentNode.NameColon == null || argumentNode.NameColon.IsMissing)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: can't have a missing NameColon.  It should either be there or not.

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs [hunk 16]
```diff
@@ -159,60 +172,80 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
+                var parameterIndex = TryDetermineParameterIndex(argumentNode.NameColon, method);
+                if (parameterIndex == -1)
+                {
+                    return argumentNode;
+                }
 
-            return SyntaxFactory.ParameterList(
-                SyntaxFactory.SeparatedList<ParameterSyntax>().Add(parameterSyntax));
+                var newParameter = newParameterList.Parameters.ElementAtOrDefault(parameterIndex);
+                if (newParameter == null || newParameter.Identifier.IsMissing)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: "IsMissing" here, on the other hand *is* appropriate.

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-ide can someone else look at this community PR?  Thanks!

File: src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs [hunk 17]
```diff
@@ -1932,9 +1932,7 @@ class C
     void M()
     {
         Action [||]local = null;
-        local = () => {
-            local.Invoke();
-        }
+        local = () => { local.Invoke(); }
```
Comment (Neme12) [inline src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: just making use of the fix... I wanted this to be on one line originally but didn't do that because of the bug

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs [hunk 18]
```diff
@@ -148,13 +148,15 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
 
-            var returnType = delegateMethod.GenerateReturnTypeSyntax();
-
             // We add a space directly after the return-type, as the default presence of an elastic 
             // trivia makes the formatting engine thing it can take a single-line local function and
             // wrap it over multiple lines.
-            var returnType = invokeMethod.GenerateReturnTypeSyntax().WithTrailingTrivia(SyntaxFactory.Space);
-            
+            var returnType = delegateMethod.GenerateReturnTypeSyntax().WithTrailingTrivia(SyntaxFactory.Space);
+            if (modifiers.Count > 0) // if it's async, we need to add one before the return type as well...
```
Comment (Neme12) [inline src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: @CyrusNajmabadi's fix didn't work for async

**Comment by Neme12** [comment]
I merged to incorporate changes from @CyrusNajmabadi's PR: #24773

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs (hunk 15 above)
Comment (Neme12) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: then why is the check here? http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Extensions/ArgumentSyntaxExtensions.cs,73

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: No clue.  That code is *old* :)   It's likely it existed at a point in time with the syntax model where such a thing was possible.  Feel free to fix this up as well.

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs (hunk 18 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: should we put the space on the trailing trivia on the async keyword instead?

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: alternatively, we could create the entire thing, then do a final:  localFunction.ReplaceToken(localFunction.GetFirstToken(), localFunction.GetFirstToken().WithTrailingTrivia(...))

Comment (Neme12) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: > should we put the space on the trailing trivia on the async keyword instead?
I tried that, it didn't work

Comment (Neme12) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: > localFunction.ReplaceToken(localFunction.GetFirstToken(), localFunction.GetFirstToken().WithTrailingTrivia(...))

didn't work either. and if you had a more complex type, a space after the first token inside it might be undesirable

File: src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs [hunk 19]
```diff
@@ -2495,6 +2520,56 @@ void Goo()
 }");
         }
 
+        [WorkItem(23872, "https://github.com/dotnet/roslyn/issues/23872")]
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseLocalFunction)]
+        public async Task TestSimpleInitialization_SingleLine4()
```
Comment (Neme12) [inline src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: @CyrusNajmabadi  how do I reconcile this with your new set of tests from #24867? I think anon. methods have to be here as well and I added an async version of tests 2 & 4 everywhere. If you want int[] as a return type covered maybe it can be put in existing tests instead of making even more of them?

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: >  how do I reconcile this with your new set of tests

Copy/paste woudl work?  :)   I think it would make sense to just merge this branch into yours.  If there's a conflict with tests, just keep yours and then manually add these few tests in afterwards.

Thanks!

Comment (Neme12) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: @CyrusNajmabadi yes but I added more tests yesterday and some of them do the same thing as your test for async (but not for int[]) and mine are organized differently, I have tests 1, 2, 2Async, 3, 4, 4Async (previously your progression was just for different kinds of lambdas, so I added 4 for anonymous methods and a separate async version of some tests).

if i add yours just the way they are it's going to be a mess with duplicates

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: If you feel like your tests cover the same set of cases that mine do, you can just remove my tests and use yours.  If you feel like your tests don't get the same coverage (for example, they don't test multi-token return types), then i would keep my tests (but organize/augment them however you want).

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: i.e. you can rename them, order them anywhere, even edit them.  The core goal of these tests was to just ensure multi-token return types (in either async or sync contexts) don't cause wrapping.

Comment (Neme12) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: I was asking if it would be OK to have a multi-token return type in every test

Comment (Neme12) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: mine have to cover anonymous methods with async as well of course, so one option would be to add another set of tests with AsyncMultitoken or something like that to both lambdas &anon. methods, or just always use multitoken with async, or with all tests, which would be simpler

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: > I was asking if it would be OK to have a multi-token return type in every test

I'm always fine with more tests :)

It's totally up to you.  I was satisfied with the number of tests i wrote to validate this scenario.  If you think it's not enough, adding more is totally up to you :)

Comment (Neme12) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: no that's not what I meant, I was asking if it would be a bad idea to put int[] on all of them

Comment (Neme12) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: otherwise i'm going to have to add 2(non async multitoken + async multitoken) * 2(lambdas+anon.methods) * 3 more tests, so that's 12

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: >  I was asking if it would be a bad idea to put int[] on all of them

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: > otherwise i'm going to have to add 2(non async multitoken + async multitoken) * 2(lambdas+anon.methods) * 3 more tests, so that's 12... there's already 24 tests for this single line issue

Again, this is up to you.  I'm satisfied with the current level of testing.  If you are not, you are perfectly free to add more tests.  I'm not going to stop you.  :)

Comment (Neme12) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: not more variants, only int[] instead of int everywhere... otherwise i'll have to add 12 more tests

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: > not more variants, only int[] instead of int everywhere... 

i would be fine with you using int[] everywhere (though at least one single-token return type test would be good then too).

> otherwise i'll have to add 12 more tests to cover these variations for anon methods as well as lambdas

Sorry, i'm not getting the "have to add" part.  As i mentioned already, i think the current level of coverage for this case is fine.  I'm not asking you to add all these tests.  So i'm not sure why you think you would "have" to do it :)

BTW, i'm in gitter if you'd like to discuss things there.  It might make things go a lot faster :)

**Comment by Neme12** [comment]
@dotnet-bot retest windows_release_unit32_prtest please

**Comment by Neme12** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please

**Comment by Neme12** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please

**Comment by Neme12** [comment]
@CyrusNajmabadi 
> We can do this a few ways. I can merge myself, and you can preemptively merge my branch into yours. Or we can just merge my work into yours and have you submit it all. It's up to you which you'd prefer.

I did a merge directly from your fork into here so it should work either way now.

**Comment by Neme12** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please

**Comment by Neme12** [comment]
@dotnet-bot retest windows_release_unit64_prtest please
@dotnet-bot retest windows_debug_unit64_prtest please

**Comment by Neme12** [comment]
@dotnet-bot retest windows_debug_unit64_prtest please

**Comment by Neme12** [comment]
@dotnet-bot retest windows_release_unit64_prtest please

**Comment by Neme12** [comment]
@dotnet retest windows_release_unit64_prtest please

**Comment by Neme12** [comment]
@dotnet-bot retest windows_release_unit64_prtest please

**Comment by Neme12** [comment]
retest windows_coreclr_debug_prtest please

**Comment by Neme12** [comment]
I'm sorry the final diff in the tests looks so bad... this is because there was a formatting issue merged while I was working on this and the tests added in that PR and my tests are now mixed together in the diff. When fixing the merge conflict, I kept my tests in place (because I thought they fit more in that place as a progression after the previous tests) and put the merged ones at the end (rather than the other way around, which would make the diff better).

It might be really helpful to either review this PR commit by commit or look at the first 9 commits (https://github.com/dotnet/roslyn/pull/24763/files/b49573454e74ab09c805d04cf730bd3229545150, up to including b495734 Adding a comprehensive test) and then the rest.

File: src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs [hunk 20]
```diff
@@ -257,6 +257,46 @@ void M()
...
+        public async Task TestSimpleInitialization_AnonymousMethod()
+        {
+            await TestInRegularAndScriptAsync(
+@"using System;
+
+class C
+{
+    void M()
+    {
+        Func<int, int> [||]fibonacci = delegate (int v)
```
Comment (jcouv) [inline src/EditorFeatures/CSharpTest/UseLocalFunction/UseLocalFunctionTests.cs]: >int [](start = 18, length = 3)

Consider returning a long instead, to distinguish the input and return types.

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs [hunk 21]
```diff
@@ -46,112 +46,124 @@ public override Task RegisterCodeFixesAsync(CodeFixContext context)
...
+            LocalDeclarationStatementSyntax localDeclaration, AnonymousFunctionExpressionSyntax anonymousFunction,
+            IMethodSymbol delegateMethod, ParameterListSyntax parameterList)
         {
-            var newLocalFunctionStatement = CreateLocalFunctionStatement(
-                localDeclaration, lambda, delegateType, parameterList, cancellationToken);
-
-            newLocalFunctionStatement = newLocalFunctionStatement.WithTriviaFrom(localDeclaration)
-                                                                 .WithAdditionalAnnotations(Formatter.Annotation);
+            var newLocalFunctionStatement = CreateLocalFunctionStatement(localDeclaration, anonymousFunction, delegateMethod, parameterList)
+                .WithTriviaFrom(localDeclaration)
```
Comment (jcouv) [inline src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: >WithTriviaFrom [](start = 17, length = 14)

This makes me think it would be good to tests with trivia.

For instance:
```C#
/* comment 1 */
Action [||]local = null; // comment 2
/* comment 3 */
local = () => local.Invoke(); // comment 4
```

I'm not sure how to handle clashes like this (between comments 2 and 4 in this example).

Comment (Neme12) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: I am sorry but I would prefer not going out of my way to solve a design problem with comments here. This PR already fixes 6 different bugs, all of which were unrelated to the issue I was originally trying to solve.

Comment (Neme12) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionCodeFixProvider.cs]: Thanks

**Comment by sharwell** [comment]
:memo: Since this already had two knowledgeable reviewers I focused my review on the diagnostic analyzer, especially the performance perspective.

**Comment by jinujoseph** [comment]
Approved to merge for 15.8.Preview4
