### PR TITLE
Cp1252

### LINKED ISSUE #2081: Bug: A C# comment with HORIZONTAL ELLIPSIS (U+2026) results in incorrect parse
Compile this:

    // Test.cs
    // Hello … world

Result:

    csc.exe /target:library Test.cs
    Microsoft (R) Visual C# Compiler version 1.0.0.50415
    Copyright (C) Microsoft Corporation. All rights reserved.

    test.cs(3,2): error CS0116: A namespace cannot directly contain members such as fields or methods

Expect:
Compiles with no error.

### PR DESCRIPTION
**Pull request by pharring**
Fixes #2081
@jaredpar FYI (in case you were working on it)

### CODE REVIEW

**Comment by pharring** [comment]
Note: If this encoding gets used, then it's possible to access it from the SourceText.Encoding property. And, if you try and use that for encoding from Unicode to ANSI, you'll hit a NotSupportedException. We could address that by implementing an encoder, but that's quite a bit more code (have to deal with unsupported code points and, possibly, surrogate pairs) for an edge case. Does that seem like a big problem to anyone?

File: src/Compilers/Core/Desktop/CodePage1252Encoding.cs [hunk 1]
```diff
@@ -0,0 +1,123 @@
...
+using System.Text;
+
+namespace Microsoft.CodeAnalysis.Text
+{
+    /// <summary>
+    /// CodePage 1252 decoder. This is a single byte character set encoding that is very close
+    /// to Latin1 except some of the code points in the control set 1 range (0x80 to 0x9F) are
+    /// replaced with typographic characters.
+    /// </summary>
+    internal class CodePage1252Encoding : Encoding
```
Comment (jaredpar) [inline src/Compilers/Core/Desktop/CodePage1252Encoding.cs]: `sealed`

File: src/Compilers/Core/Desktop/CodePage1252Encoding.cs [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+    {
+        public static readonly CodePage1252Encoding Instance = new CodePage1252Encoding();
+
+        public override int CodePage => 1252;
+
+        public override int GetByteCount(char[] chars, int index, int count)
+        {
+            // This is a decoder only
```
Comment (jaredpar) [inline src/Compilers/Core/Desktop/CodePage1252Encoding.cs]: Should we change the type name to reflect this behavior?

**Comment by jaredpar** [comment]
Thanks for taking care of this!

File: src/Compilers/Core/Desktop/CodePage1252Encoding.cs (hunk 2 above)
Comment (pharring) [inline src/Compilers/Core/Desktop/CodePage1252Encoding.cs]: You mean "CodePage1252Decoder"? I think that might be a bit incongruous since it "is-a" Encoding and we might, indeed, need to fill in the encoder parts at a later date.

File: src/Compilers/Core/Desktop/CodePage1252Encoding.cs (hunk 1 above)
Comment (pharring) [inline src/Compilers/Core/Desktop/CodePage1252Encoding.cs]: Agreed. Will do.

**Comment by pharring** [comment]
@angocke @tmat FYI
@gafter, @AlekseyTs, @VSadov, @theoy Need a 2nd reviewer, please.

File: src/Compilers/Core/CodeAnalysisTest/Text/EncodedStringTextTests.cs [hunk 3]
```diff
@@ -97,7 +97,7 @@ public void CheckSum_SHA256()
         public void Decode_NonUtf8()
         {
             var utf8 = new UTF8Encoding(false, true);
-            var encoding = Encoding.GetEncoding(name: "Latin1");
+            var encoding = Encoding.Default;
```
Comment (jaredpar) [inline src/Compilers/Core/CodeAnalysisTest/Text/EncodedStringTextTests.cs]: Can we change this line to `Encoding.GetEncoding(codePage: 1252)`?  

Soon we are going to begin running our unit test on top of CoreCLR at which point this line won't compile anymore.  The `GetEncoding` call will compile but fail at runtime.  That is okay though because we can then mark the test to only run on Desktop.

**Comment by agocke** [comment]
LGTM, pending Jared's comment

**Comment by mavasani** [comment]
Will this fix #2048? If so, can you please add a comment to that issue to re-enable the skipped test after next toolset update?

File: src/Compilers/Core/CodeAnalysisTest/Text/EncodedStringTextTests.cs (hunk 3 above)
Comment (pharring) [inline src/Compilers/Core/CodeAnalysisTest/Text/EncodedStringTextTests.cs]: @jaredpar Yes, I'll change it. How do I mark the test to run only on Desktop?

Comment (AlekseyTs) [inline src/Compilers/Core/CodeAnalysisTest/Text/EncodedStringTextTests.cs]: Should we use CodePage1252Encoding here?

**Comment by jaredpar** [comment]
@pharring the code to make it run Desktop only isn't in master yet.  I'll take care of updating this test once I start getting the CoreCLR runs going.

File: src/Compilers/Core/CodeAnalysisTest/Text/EncodedStringTextTests.cs (hunk 3 above)
Comment (pharring) [inline src/Compilers/Core/CodeAnalysisTest/Text/EncodedStringTextTests.cs]: @AlekseyTs Unfortunately, as it stands right now, CodePage1252Encoding is a decoder only, so it won't work here.

**Comment by pharring** [comment]
Thanks, @jaredpar. I actually rewrote that test so it didn't need an encoding at all. Hard-coding the Unicode text and its 1252-encoded equivalent in a byte array.

**Comment by pharring** [comment]
Note: There was a follow up fix for this: #2151 
We abandoned the hand-written Encoding and now use Encoding.GetEncoding(1252) if available or "Latin1" if not.
