### PR TITLE
Fixed the Go To Definition for ValueTuple

### LINKED ISSUE #71680: Unable to go-to-def on a `ValueTuple`
**Version Used**:
VS 17.8.4

**Steps to Reproduce**:
```cs
using System;
using System.Runtime.CompilerServices;

ITuple iTuple;
Tuple<int, int> tuple;
ValueTuple<int, int> valueTuple;
```
Execute 'Go to definition' on `ITuple`, `Tuple` and `ValueTuple`

**Expected Behavior**:
I can go-to-def on all 3 types

**Actual Behavior**:
go-to-def works fine for `ITuple` and `Tuple`, but fails for `ValueTuple` (you get a popup saying that it isn't possible to go-do-def where the cursor is)

### PR DESCRIPTION
**Pull request by victor-pogor**
Fixes #71680.

### CODE REVIEW

**Comment by victor-pogor** [comment]
@dotnet-policy-service agree

File: src/Features/Core/Portable/FindUsages/IDefinitionsAndReferencesFactory.cs [hunk 1]
```diff
@@ -151,7 +151,7 @@ internal static class DefinitionItemExtensions
 
             var properties = GetProperties(definition, isPrimary);
 
-            if (sourceLocations.IsDefault)
+            if (sourceLocations.IsDefault || definition.IsTupleType())
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/FindUsages/IDefinitionsAndReferencesFactory.cs:154]: doc.

File: src/Features/LanguageServer/Protocol/Handler/Definitions/AbstractGoToDefinitionHandler.cs [hunk 2]
```diff
@@ -70,6 +70,12 @@ public AbstractGoToDefinitionHandler(IMetadataAsSourceFileService metadataAsSour
             {
                 // No definition found - see if we can get metadata as source but that's only applicable for C#\VB.
                 var symbol = await SymbolFinder.FindSymbolAtPositionAsync(document, position, cancellationToken).ConfigureAwait(false);
+
+                if (symbol.IsTupleType())
```
Comment (CyrusNajmabadi) [inline src/Features/LanguageServer/Protocol/Handler/Definitions/AbstractGoToDefinitionHandler.cs:74]: doc.

not sure hwo i feel about this.  I think i'd prefer if _metadataAsSourceFileService.GetGeneratedFileAsync jsut worked on a tuple type.  so less special casing here.

Comment (victor-pogor) [reply src/Features/LanguageServer/Protocol/Handler/Definitions/AbstractGoToDefinitionHandler.cs:74]: `_metadataAsSourceFileService.IsNavigableMetadataSymbol(symbol)` will not let me reach that code.

```csharp
if (!symbol.Locations.Any(static l => l.IsInMetadata)) // locations are preserved in OriginalDefinition
{
    return false;
}
```

I was thinking of adding this special case to this method but it is used in several places so was not sure if is safe to do so.

1. [src\EditorFeatures\Core\CodeDefinitionWindow\DefinitionContextTracker.cs](https://github.com/dotnet/roslyn/blob/e7cae311ab49148335e969b94fb47f0dffaa95df/src/EditorFeatures/Core/CodeDefinitionWindow/DefinitionContextTracker.cs#L198-L204)
2. [src\EditorFeatures\Core.Wpf\Peek\PeekableItemFactory.cs](https://github.com/dotnet/roslyn/blob/e7cae311ab49148335e969b94fb47f0dffaa95df/src/EditorFeatures/Core.Wpf/Peek/PeekableItemFactory.cs#L82-L95)
3. [src\Features\LanguageServer\Protocol\Handler\Definitions\AbstractGoToDefinitionHandler.cs - Current](https://github.com/dotnet/roslyn/blob/e7cae311ab49148335e969b94fb47f0dffaa95df/src/Features/LanguageServer/Protocol/Handler/Definitions/AbstractGoToDefinitionHandler.cs#L69-L88)
4. [src\VisualStudio\Core\Def\Workspace\VisualStudioSymbolNavigationService.cs](https://github.com/dotnet/roslyn/blob/e7cae311ab49148335e969b94fb47f0dffaa95df/src/VisualStudio/Core/Def/Workspace/VisualStudioSymbolNavigationService.cs#L85-L90)
5. [src\VisualStudio\Xaml\Impl\Implementation\LanguageServer\Handler\Definitions\GoToDefinitionHandler.cs](https://github.com/dotnet/roslyn/blob/e7cae311ab49148335e969b94fb47f0dffaa95df/src/VisualStudio/Xaml/Impl/Implementation/LanguageServer/Handler/Definitions/GoToDefinitionHandler.cs#L173-L189)

Or maybe changing indeed this method and adjusting the references of this method to capture the correct locations and construct the metadata definition item?

Comment (CyrusNajmabadi) [reply src/Features/LanguageServer/Protocol/Handler/Definitions/AbstractGoToDefinitionHandler.cs:74]: All of those are ones that i'd want to do the right thing wrt to tuples and ValueTuple, so that makes me want thsi mroe strongly.

Comment (CyrusNajmabadi) [reply src/Features/LanguageServer/Protocol/Handler/Definitions/AbstractGoToDefinitionHandler.cs:74]: Note: IsNavigableMetadataSymbol should absolutely be getting to the original symbol (including with tuples, seeing through to the underlying ValueTuple).  That seems like a great place to put things :)

Comment (victor-pogor) [reply src/Features/LanguageServer/Protocol/Handler/Definitions/AbstractGoToDefinitionHandler.cs:74]: I was thinking maybe replacing the symbol with the `OriginalDefinition` for tuple types but there are references of this method that are already doing this, so I'm afraid of duplicate access to original definition.

Maybe something like this:
```diff
// Raw code, it may be simplified/refactored for readability
- if (!symbol.Locations.Any(static l => l.IsInMetadata))
+ if (!(symbol.Locations.Any(static l => l.IsInMetadata) || (symbol.IsValueTuple() && symbol.OriginalDefinition.Locations.Any(static l => l.IsInMetadata))))
{
    return false;
}
```

... and adjusting all those 5 references to ensure the location is correctly retrieved?

Comment (CyrusNajmabadi) [reply src/Features/LanguageServer/Protocol/Handler/Definitions/AbstractGoToDefinitionHandler.cs:74]: i would jsut do:

`symbol = symobl.OriginalDefinition;` above the if check.

Comment (CyrusNajmabadi) [reply src/Features/LanguageServer/Protocol/Handler/Definitions/AbstractGoToDefinitionHandler.cs:74]: >  so I'm afraid of duplicate access to original definition.

it's not a problem.

Comment (victor-pogor) [reply src/Features/LanguageServer/Protocol/Handler/Definitions/AbstractGoToDefinitionHandler.cs:74]: Ok, then I will it a try. Thanks.

Comment (CyrusNajmabadi) [reply src/Features/LanguageServer/Protocol/Handler/Definitions/AbstractGoToDefinitionHandler.cs:74]: you're welcome :)

File: src/Features/Core/Portable/FindUsages/IDefinitionsAndReferencesFactory.cs (hunk 1 above)
Comment (victor-pogor) [reply src/Features/Core/Portable/FindUsages/IDefinitionsAndReferencesFactory.cs:154]: added

File: src/Features/Core/Portable/MetadataAsSource/MetadataAsSourceFileService.cs [hunk 3]
```diff
@@ -305,6 +305,8 @@ private static void TryDeleteFolderWhichContainsReadOnlyFiles(string directoryPa
 
         public bool IsNavigableMetadataSymbol(ISymbol symbol)
         {
+            symbol = symbol.OriginalDefinition;
```
Comment (victor-pogor) [inline src/Features/Core/Portable/MetadataAsSource/MetadataAsSourceFileService.cs:308]: is doc needed?

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/MetadataAsSource/MetadataAsSourceFileService.cs:308]: I'm ok with no docs here

**Comment by victor-pogor** [comment]
@CyrusNajmabadi I resolved the comments. Is there anything else I can do?

File: src/EditorFeatures/Test2/CodeDefinitionWindow/CSharpCodeDefinitionWindowTests.vb [hunk 4]
```diff
@@ -95,6 +95,29 @@ class C
...
+class C
+{{
+    void M()
+    {{
+        $${expression} valueTuple;
+    }}
+}}"
+
+            Await VerifyContextLocationInMetadataAsSource(code, expectedDisplayName, "ValueTuple.cs")
+
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Test2/CodeDefinitionWindow/CSharpCodeDefinitionWindowTests.vb:118]:
```suggestion
```

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
lgtm.  thankS!
