### PR TITLE
Fix crash in Inline Rename

### LINKED ISSUE #8412: Inline rename crash
ArgumentOutOfRangeException at ```CSharpSimplificationService.Expander.VisitParenthesizedLambdaExpression```

Crash dump:
%internal_share%\public\tomat\Bugs\8412

Repro:
1) Pull Roslyn branch from ```https://github.com/tmat/roslyn/tree/EEPPDB```, commit ab6cc9cb34683323cf0d9065a6cd77b328753bb5
2) In ```src\ExpressionEvaluator\CSharp\Test\ExpressionCompiler\ExpressionCompilerTestBase.cs``` rename

```C#
internal static void WithRuntimeInstancePortableBug(Compilation compilation, IEnumerable<MetadataReference> references, Action<RuntimeInstance> validator)
```

to ```WithRuntimeInstance``` and accept the rename even though there is a collision with existing method.

Stack trace:
```
   at Microsoft.CodeAnalysis.SeparatedSyntaxList`1.Replace(TNode nodeInList, TNode newNode) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\Core\Portable\Syntax\SeparatedSyntaxList.cs:line 480
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.VisitParenthesizedLambdaExpression(ParenthesizedLambdaExpressionSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 212
   at Microsoft.CodeAnalysis.CSharp.Syntax.ParenthesizedLambdaExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 51330
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 71
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitArgument(ArgumentSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 69607
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.VisitArgument(ArgumentSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 274
   at Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 50774
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 71
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 165
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SeparatedSyntaxList`1 list) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 179
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitArgumentList(ArgumentListSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 69592
   at Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentListSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 50571
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 71
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitInvocationExpression(InvocationExpressionSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 69577
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.VisitInvocationExpression(InvocationExpressionSyntax originalNode) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 1027
   at Microsoft.CodeAnalysis.CSharp.Syntax.InvocationExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 50379
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 71
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitExpressionStatement(ExpressionStatementSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 69905
   at Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionStatementSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 54282
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 71
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 165
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 142
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitBlock(BlockSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 69870
   at Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 53836
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 71
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitSimpleLambdaExpression(SimpleLambdaExpressionSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 69643
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.VisitSimpleLambdaExpression(SimpleLambdaExpressionSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 254
   at Microsoft.CodeAnalysis.CSharp.Syntax.SimpleLambdaExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 51208
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 71
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitArgument(ArgumentSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 69607
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.VisitArgument(ArgumentSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 274
   at Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 50774
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 71
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 165
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SeparatedSyntaxList`1 list) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 218
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitArgumentList(ArgumentListSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 69592
   at Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentListSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 50571
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 71
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitInvocationExpression(InvocationExpressionSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 69577
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.VisitInvocationExpression(InvocationExpressionSyntax originalNode) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 1027
   at Microsoft.CodeAnalysis.CSharp.Syntax.InvocationExpressionSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 50379
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 71
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitExpressionStatement(ExpressionStatementSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 69905
   at Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionStatementSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 54282
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expander.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.Expander.cs:line 71
   at Microsoft.CodeAnalysis.CSharp.Simplification.CSharpSimplificationService.Expand(SyntaxNode node, SemanticModel semanticModel, SyntaxAnnotation annotationForReplacedAliasIdentifier, Func`2 expandInsideNode, Boolean expandParameter, CancellationToken cancellationToken) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Simplification\CSharpSimplificationService.cs:line 50
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Complexify(SyntaxNode originalNode, SyntaxNode newNode) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 248
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 161
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 165
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 142
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitBlock(BlockSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 69870
   at Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 53836
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 161
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitMethodDeclaration(MethodDeclarationSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 70428
   at Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 60770
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 161
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 165
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 142
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitClassDeclaration(ClassDeclarationSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 70276
   at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 58673
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 161
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 165
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 142
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitNamespaceDeclaration(NamespaceDeclarationSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 70196
   at Microsoft.CodeAnalysis.CSharp.Syntax.NamespaceDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 57680
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 161
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 165
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 142
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitCompilationUnit(CompilationUnitSyntax node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 70167
   at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Syntax.xml.Generated.cs:line 57295
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxRewriter.cs:line 39
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.RenameRewriter.Visit(SyntaxNode node) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 161
   at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.AnnotateAndRename(RenameRewriterParameters parameters) in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\CSharp\Portable\Rename\CSharpRenameRewriterLanguageService.cs:line 39
   at Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.<AnnotateAndRename_WorkerAsync>d__26.MoveNext() in F:\Builds\5530\DevDiv\Roslyn-Master-Signed-Release\src\Open\src\Workspaces\Core\Portable\Rename\ConflictEngine\ConflictResolver.Session.cs:line 752
```

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes #8412

As the types into an Inline Rename field, the Rename engine attempts to resolve conflicts at each reference. It does this by expanding nodes are the references and then simplifying them down to the smallest node that does not change semantics.

During this process, one of the expansion steps is to add explicit types to lambda parameters that were defined without types. However, the expander wasn't rewriting lambdas with multiple parameters correctly. Essentially, the rewriter assumed that, when replacing a node within a `SeparatedSyntaxList<T>`, the identities of other nodes within the list would not change. However, that's not the case. So, it would successfully replace the first parameter within a lambda's parameter list. However, when it attempted to replace the second parameter, the *original* second parameter could no longer be found in the `SeparatedSyntaxList<T>` because the identity of the second parameter in the list had changed. At this point, `SepratedSyntaxList<T>.Replace(...)` would throw an `ArgumentOutOfRangeException` and VS would crash.

The user scenario is that typing within an Inline Rename field can cause Visual Studio to simply crash, resulting in potenal data loss. Explicitly, this will happen if the user is renaming something that affects a lambda with two or parameters, which is not uncommon.

The fix changes the rewriter to not pass the original parameters to `SeparatedSyntaxList<T>.Replace(...)`. Instead, it passes the parameters that are contained when the new list as it builds it up.

This is a regression introduced after Update 1 with PR #6432.

cc @roslyn-ide, @davkean 

Also, @MattGertz to approve/disapprove the user scenario against the current bar.

### CODE REVIEW

**Comment by DustinCampbell** [comment]
cc @dotnet/roslyn-ide

File: src/EditorFeatures/Test2/Expansion/LambdaParameterExpansionTests.vb [hunk 1]
```diff
@@ -0,0 +1,175 @@
...
+        Action<int, int> a = (System.Int32 x, System.Int32 y) => { };
+    }
+}
+]]></code>
+
+            Await TestAsync(input, expected, expandParameter:=True)
+        End Function
+
+        <Fact, Trait(Traits.Feature, Traits.Features.Expansion)>
+        Public Async Function TestCSharp_ExpandLambdaWithThreearameters() As Task
```
Comment (Pilchie) [inline src/EditorFeatures/Test2/Expansion/LambdaParameterExpansionTests.vb]: spelling (missing P in Parameters).

File: src/EditorFeatures/Test2/Expansion/LambdaParameterExpansionTests.vb [hunk 2]
```diff
@@ -0,0 +1,175 @@
...
+        Action a = () => { };
+    }
+}
+</code>
+
+            Await TestAsync(input, expected, expandParameter:=True)
+        End Function
+
+        <Fact, Trait(Traits.Feature, Traits.Features.Expansion)>
+        Public Async Function TestCSharp_ExpandLambdaWithSingleParameters_NoParens() As Task
```
Comment (Pilchie) [inline src/EditorFeatures/Test2/Expansion/LambdaParameterExpansionTests.vb]: Spelling: `SingleParameters`

**Comment by Pilchie** [comment]
:+1:

File: src/EditorFeatures/Test2/Expansion/LambdaParameterExpansionTests.vb (hunk 2 above)
Comment (DustinCampbell) [inline src/EditorFeatures/Test2/Expansion/LambdaParameterExpansionTests.vb]: I'm on a role!

Errr... roll. :smile:

**Comment by DustinCampbell** [comment]
I'm going to fix the spelling mistakes in unit tests, but will wait until the VSI tests are complete before pushing.

**Comment by davkean** [comment]
@MattGertz Make note this is an escrow bug.

@DustinCampbell Can you open this same thing against future-stabilization? This is going to miss the merge.

**Comment by davkean** [comment]
@MattGertz Strike that - we might be able to get it under Ask Mode, but still tell me if this meets Escrow bar, just in case we miss.

**Comment by MattGertz** [comment]
Yes, it would meet that Escrow bar IMO.  (If possible I'd rather avoid bringing it in Escrow of course, but I can only expect superhuman effort :-))

**Comment by DustinCampbell** [comment]
vsi tests passed

**Comment by davkean** [comment]
Oh, damn did you restart the build?

**Comment by davkean** [comment]
The commit did, because you were out of date
