### PR TITLE
Reduce the number of attributes that should be bound in order to determine if there are NoPia local types explicitly defined in code.

### LINKED ISSUE #23179: SourceModuleSymbol.ContainsExplicitDefinitionOfNoPiaLocalTypes forces expensive binding
`SourceModuleSymbol.ContainsExplicitDefinitionOfNoPiaLocalTypes` forces all attributes to be bound, resulting in extreme performance and/or reliability problems when using the IDE.

https://github.com/dotnet/roslyn/blob/a604cefecd2cba10803a872c580cfb7a9e0883ad/src/Compilers/CSharp/Portable/Symbols/Source/SourceModuleSymbol.cs#L146-L150

🔗 [Slowdown and then crash](https://developercommunity.visualstudio.com/content/problem/136307/slowdown-and-then-crash.html) ([Internal feedback ticket](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/513336))
:link: [Slowdown and Crash #3](https://developercommunity.visualstudio.com/content/problem/136317/slowdown-and-crash-3.html) ([Internal feedback ticket](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/513345))

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #23179.

### Customer scenario

Today compilers bind all attributes on all top level types in order to determine if there are NoPia local types explicitly defined in code. This information is necessary every time a project to project reference is created. NoPia local types explicitly defined in code are extremely uncommon, but attributes binding can be expensive if there are a lot of them. We have a customer that apparently experiences IDE performance and/or reliability problems because of that.

### Bugs this fixes

#23179

### Workarounds, if any

None

### Risk

Low

### Performance impact

Low perf impact because in a common scenario we will be doing less work than before.

### Is this a regression from a previous update?

No

### Root cause analysis

Unit-tests added.

### How was the bug found?

Customer reported

### Test documentation updated?

N/A

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs [hunk 1]
```diff
@@ -770,6 +770,77 @@ internal override bool IsExplicitDefinitionOfNoPiaLocalType
...
+
+                        if (attr.Name == simpleName)
+                        {
+                            // Check if the name matches an alias bound to the TypeIdentifierAttribute
+                            if (binder == null)
+                            {
+                                binder = this.DeclaringCompilation.GetBinderFactory(list.Node.SyntaxTree).GetBinder(list.Node);
+                            }
+
+                            string nameWithAttribute = name + "Attribute";
```
Comment (sharwell) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs]: ❓ Can we lazily initialize this after we know `usingAliases` is not empty?

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs [hunk 2]
```diff
@@ -770,6 +770,77 @@ internal override bool IsExplicitDefinitionOfNoPiaLocalType
...
+                            // This attribute syntax might be an application of TypeIdentifierAttribute.
+                            // Let's bind it.
+                            // For simplicity we bind all attributes.
+                            GetAttributes();
+                            return;
+                        }
+
+                        if (attr.Name == simpleName)
+                        {
+                            // Check if the name matches an alias bound to the TypeIdentifierAttribute
```
Comment (sharwell) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs]: :bulb: Consider an alternate approach where you look only at the namespaces in the syntax tree. If you see a using alias directive that maps to `TypeIdentifierAttribute`, assume that the directive is used and call `GetAttributes`. You will avoid needing to check every attribute usage against aliases, further improving fast paths.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs]: > further improving fast paths

This is a speculation. Figuring out if alias binds to a type requires binding to occur. Checking if name matches an alias is a simple lookup in a hash table.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs]: > Can we lazily initialize this after we know usingAliases is not empty?

Sure, we can do this.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs]: I believe it is not common for an attribute application to use an alias, therefore we can completely avoid binding anything.

Comment (sharwell) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs]: For the case I mentioned, you could check to see if any alias maps to the string name "TypeIdentifierAttribute". Binding would not be necessary.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs]: If we find out that with this approach SourceModuleSymbol.ContainsExplicitDefinitionOfNoPiaLocalTypes still has noticeable negative effect for the customer, I'll see how can we adopt VB approach, which is completely syntax based.

**Comment by AlekseyTs** [comment]
@sharwell Please see if you like the new approach for C# better.

**Comment by AlekseyTs** [comment]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/9161/

Test Result (1 failure / +1)Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpFormatting.PasteCodeWithLambdaBody3
--

**Comment by AlekseyTs** [comment]
Test windows_release_vs-integration_prtest please

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs [hunk 3]
```diff
@@ -770,6 +770,37 @@ internal override bool IsExplicitDefinitionOfNoPiaLocalType
...
+                var syntaxTree = list.Node.SyntaxTree;
+                HashSet<string> quickCheckSet = this.DeclaringCompilation.GetBinderFactory(list.Node.SyntaxTree).GetBinder(list.Node).QuickTypeIdentifierAttributeCheckSet;
+
+                foreach (AttributeListSyntax attrList in list)
+                {
+                    foreach (AttributeSyntax attr in attrList.Attributes)
+                    {
+                        string name = attr.Name.GetUnqualifiedName().Identifier.ValueText;
+
+                        if (quickCheckSet.Contains(name) || quickCheckSet.Contains(name + "Attribute"))
```
Comment (sharwell) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs]: 💭 It would be nice to avoid this allocation, by using a `Contains` implementation that ignores `Attribute` suffix(es).

File: src/Compilers/CSharp/Portable/Binder/InContainerBinder.cs [hunk 4]
```diff
@@ -101,6 +102,33 @@ internal override ImportChain ImportChain
...
+        internal override HashSet<string> QuickTypeIdentifierAttributeCheckSet
+        {
+            get
+            {
+                if (_lazyQuickTypeIdentifierAttributeCheckSet == null)
+                {
+                    HashSet<string> previousSet = this.Next.QuickTypeIdentifierAttributeCheckSet;
+                    HashSet<string> newSet = null;
+
+                    if ((object)_container == null || _container.Kind == SymbolKind.Namespace)
```
Comment (sharwell) [inline src/Compilers/CSharp/Portable/Binder/InContainerBinder.cs]: :bulb: If you're going to have the cast to `(object)`, you may as well use `_container is null`.

File: src/Compilers/CSharp/Portable/Binder/Binder.cs [hunk 5]
```diff
@@ -304,6 +304,14 @@ internal virtual ImportChain ImportChain
             }
         }
 
+        internal virtual HashSet<string> QuickTypeIdentifierAttributeCheckSet
```
Comment (sharwell) [inline src/Compilers/CSharp/Portable/Binder/Binder.cs]: 💡 Consider using `ImmutableHashSet<string>`. Since the algorithm allows reference sharing between certain binders, immutability helps reason about the code. In addition, the majority case involves only a single element in the set, and `ImmutableHashSet<string>` should perform similarly to `HashSet<string>` for this case.

:memo: This is a "strong suggestion"; it appears to be a clear win for maintainability, and should *at least* be faster than the original implementation which had generally-acceptable performance.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs [hunk 6]
```diff
@@ -770,6 +770,37 @@ internal override bool IsExplicitDefinitionOfNoPiaLocalType
...
+            foreach (SyntaxList<AttributeListSyntax> list in attributeLists)
+            {
+                var syntaxTree = list.Node.SyntaxTree;
+                HashSet<string> quickCheckSet = this.DeclaringCompilation.GetBinderFactory(list.Node.SyntaxTree).GetBinder(list.Node).QuickTypeIdentifierAttributeCheckSet;
+
+                foreach (AttributeListSyntax attrList in list)
+                {
+                    foreach (AttributeSyntax attr in attrList.Attributes)
+                    {
+                        string name = attr.Name.GetUnqualifiedName().Identifier.ValueText;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs]: Would it be sufficient to search for attributes named `"TypeIdentifier"` or `"TypeIdentifierAttribute"`?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs]: > Would it be sufficient to search for attributes named "TypeIdentifier" or "TypeIdentifierAttribute", without creating the QuickTypeIdentifierAttributeCheckSet?

That would not take aliases into account, and therefore could produce inaccurate result.

File: src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Metadata/PE/NoPiaLocalHideAndTypeSubstitutionTests.vb [hunk 7]
```diff
@@ -245,6 +245,48 @@ End Class
             Assert.IsType(Of VisualBasic.Symbols.Metadata.PE.PENamedTypeSymbol)(interfaceType)
         End Sub
 
+        <Fact>
+        Public Sub NoPiaTypeSubstitutionWithHandAuthoredLocalType()
+            ' Try to apply attributes to the local type that indicates that the type Is intended to be used for type equivalence.
```
Comment (cston) [inline src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Metadata/PE/NoPiaLocalHideAndTypeSubstitutionTests.vb]: `is` rather than `Is`.

File: src/Compilers/CSharp/Test/Symbol/Symbols/TypeTests.cs [hunk 8]
```diff
@@ -1850,5 +1850,415 @@ static void Main()
...
+            var i1 = compilation.SourceAssembly.GetTypeByMetadataName("NS1.I1");
+
+            Assert.False(i1.IsExplicitDefinitionOfNoPiaLocalType);
+
+            compilation.GetDeclarationDiagnostics().Verify(
+                // (6,6): error CS0616: 'System.Runtime.InteropServices' is not an attribute class
+                //     [alias1]
+                Diagnostic(ErrorCode.ERR_NotAnAttributeClass, "alias1").WithArguments("System.Runtime.InteropServices").WithLocation(6, 6)
+                );
+        }
```
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Symbol/Symbols/TypeTests.cs]: > Is there a test for using alias = System.Runtime.InteropServices.TypeIdentifierAttribute;?

With fully qualified name? No, I'll add one.

File: src/Compilers/CSharp/Portable/Binder/Binder.cs [hunk 9]
```diff
@@ -304,6 +304,14 @@ internal virtual ImportChain ImportChain
...
+        {
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Binder.cs]: Please add a doc comment. It wasn't clear to me until I scoured the implementation that "TypeIdentifierAttribute" is a type we are checking quickly for, rather than being part of the description of the function of this property.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder.cs]: > Please add a doc comment.

Will do.

**Comment by AlekseyTs** [comment]
@gafter, @cston Please review the latest revision.

**Comment by AlekseyTs** [comment]
CC @MeiChin-Tsai For ask mode approval.

**Comment by MeiChin-Tsai** [comment]
approved

File: src/Compilers/CSharp/Portable/Symbols/Source/QuickTypeIdentifierAttributeChecker.cs [hunk 10]
```diff
@@ -0,0 +1,82 @@
...
+    /// </summary>
+    /// <remarks>
+    /// It works by maintaining a dictionary of all possible simple names that might map to a TypeIdentifier
+    /// attribute.
+    /// </remarks>
+    internal class QuickTypeIdentifierAttributeChecker
+    {
+        private readonly HashSet<string> _candidates;
+#if DEBUG
+        bool _sealed;
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Symbols/Source/QuickTypeIdentifierAttributeChecker.cs]: Need an accessibility modifier here.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/QuickTypeIdentifierAttributeChecker.cs]: > Need an accessibility modifier here.

Agree.

**Comment by AlekseyTs** [comment]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit64_prtest/11073/

Test Result (1 failure / +1)Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicCompletionCommandHandlerTests_XmlDoc.InvokeWithMustInheritKeywordCommitSeeLangword
--

**Comment by AlekseyTs** [comment]
Test windows_release_unit64_prtest please

**Comment by AlekseyTs** [comment]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/9371/

Test Result (1 failure / +1)Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpFormatting.PasteCodeWithLambdaBody3
--

**Comment by AlekseyTs** [comment]
Test windows_debug_vs-integration_prtest please
