### PR TITLE
Document outline updates

### LINKED ISSUE #69292: Cursor jumps during editing with Document Outline enabled
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/when-i-wanna-write-code-in-my-class-c/10426310)._

---
\[regression\] \[worked-in:17.7.0 preview 4.0\]  
Greetings!

“When I want to type some code in an old class I made, the Visual Studio editor goes to another line. I would like to write a function, ‘Hello, World!’, and when I’m typing, it jumps to another line, just like in the screenshot example. However, it jumps to the main class! Please take a look at the example screenshots below.”

image

---
#### Feedback Bot on 7/30/2023, 09:16 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### LINKED ISSUE #69902: Document Outline clicking isn't working with collapsed regions
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Document-Outline-clicking-isnt-working-/10456291)._

---
When clicking methods in Document Outline, nothing happens when the file have everything collapsed in regions.  See videos...

---
#### Feedback Bot on 9/3/2023, 10:29 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 9/7/2023, 10:05 PM: 

(private comment, text removed)
#### Marc Roussel on 9/7/2023, 10:34 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 9/8/2023, 00:22 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### LINKED ISSUE #69903: Freeze when switching to some C# file tabs while Document Outline feature is enabled
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Freeze-when-switching-to-some-C-file-ta/10454171)._

---
[severity:It bothers me. A fix would be nice]
When the Document Outline feature is enabled (Text Editor > Advanced > Enable document outline), Visual Studio will freeze for a couple seconds when switching to some C# file tabs. It's worth noting that this does not occur the first time the tab is switched to, it only occurs after switching away to another tab and then switching back to the tab. Then, it will continue to happen every time when switching back to the tab.

It is also important to note that this occurs even when the Document Outline window is not open and has not been open at any point in the session. It only requires the Document Outline feature to be enabled.

If the Document Outline feature is disabled, this issue does not occur.

This is admittedly less of an issue at present because the Document Outline feature can be disabled in Options as it is an experimental feature, the only downside is not being able to use this potentially useful feature. However, if in the future, the ability to disable Document Outline is removed, it would become a more significant issue for anyone having this problem.

---
#### Feedback Bot on 8/30/2023, 09:13 PM: 

(private comment, text removed)
#### Sam Harwell [MSFT] on 8/31/2023, 11:22 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by sharwell**
* Only move caret in editor if Document Outline has keyboard focus (Fixes #69292)
* Expand outlining regions if necessary (Fixes #69902)
* Avoid updating the UI if the tree view is not visible (Fixes #69903)

### CODE REVIEW

File: src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineViewModel.cs [hunk 1]
```diff
@@ -262,6 +292,13 @@ private async ValueTask ComputeViewStateAsync(CancellationToken cancellationToke
             if (_isDisposed)
                 return;
 
+            if (Visibility != Visibility.Visible)
+            {
+                // Retry the update after a delay
+                _workQueue.AddWork(cancelExistingWork: true);
+                return;
+            }
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineViewModel.cs:300]: instead of all 3, it likely suffices to just have teh first case.  worst that happens is that the user switches away, and we finish up the work here.  but any future work requsts will bail out at the top.

File: src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineView.xaml.cs [hunk 2]
```diff
@@ -282,7 +288,8 @@ private void SymbolTreeItem_SourceUpdated(object sender, DataTransferEventArgs e
                 {
                     var textView = _viewTracker.GetActiveView();
                     textView.TryMoveCaretToAndEnsureVisible(
-                        symbolModel.Data.SelectionRangeSpan.TranslateTo(textView.TextSnapshot, SpanTrackingMode.EdgeInclusive).Start);
+                        symbolModel.Data.SelectionRangeSpan.TranslateTo(textView.TextSnapshot, SpanTrackingMode.EdgeInclusive).Start,
+                        _outliningManagerService);
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineView.xaml.cs:292]: how does this work, does this helper just know to expand in that case? 

note: if so, it seems like a super weird helper since we'd always want htis behavior, in which case we should always require the outlining manager.  but this is ok for now.

File: src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineViewModel.cs (hunk 1 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineViewModel.cs:300]: Sure, that works for me

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineView.xaml.cs (hunk 2 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineView.xaml.cs:292]: This was exactly my conclusion

File: src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineViewModel.cs (hunk 1 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineViewModel.cs:300]: On second thought, given the difficulty of proving the change works, I'm concerned about edge cases like switching back and forth between a Windows Forms designer and a C# source document (resulting in a visibility change for each switch). I'm more comfortable with the original change in terms of confidence that work is avoided when the UI is not visible. If you'd like, I could eliminate the _middle_ of the three checks.

**Review by arkalyanms — APPROVED** [review]

**Comment by ToddGrun** [comment]
>             await _threadingContext.JoinableTaskFactory.SwitchToMainThreadAsync(cancellationToken);

Could the searchText, sortOption, and lastPresentedViewState locals be captured in the first time on the ui thread in this method, and thus not need this UI thread hop?

---
Refers to: src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineViewModel.cs:291 in 7404ed0. [](commit_id = 7404ed06255cf44b18451581583b13374f00b780, deletion_comment = False)

**Comment by CyrusNajmabadi** [comment]
> Could the searchText, sortOption, and lastPresentedViewState locals be captured in the first time on the ui thread in this method, and thus not need this UI thread hop?

only if changes to those are guaranteed to kick off new computation.  otherwise you risk the user chnaging UI state and that not being respected when updating the UI with new results.

**Comment by sharwell** [comment]
> Could the searchText, sortOption, and lastPresentedViewState locals be captured in the first time on the ui thread in this method, and thus not need this UI thread hop?

The background work to compute the items in the document could take a noticeable amount of time, so I prefer to capture these variables after the long-running work is complete.

**Review by ToddGrun — APPROVED** [review]
:shipit:

**Comment by sharwell** [comment]
@arkalyanms Do you know what milestone this will ship in?

**Comment by arkalyanms** [comment]
> @arkalyanms Do you know what version this will ship in?

Its inserted into the next 17.7 servicing build. We are waiting on the final build next week. Barring any unexpected regressions, it should catch 17.7.5.
