### PR TITLE
Fix brace code style for switch expressions

### LINKED ISSUE #36913: Add brace new line code style for switch expressions
<p>Currently in Visual Studio 2019 release, there is no option to specify new line options for braces when using the new switch expression.  Visual Studio will always place the opening brace on a new line, regardless of what has been specified for a switch statement, and there is no switch statement specific setting to change the option to having the opening brace on the same line.  I typically change all of my code style options for all braces to begin on the same line as the statement/expression creating the brace, but this is one expression where I am unable to configure currently.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/524975/add-brace-new-line-code-style-for-switch-expressio.html
VSTS ticketId: 843465_
_These are the original issue comments:_

Jane Wu [MSFT] on 4/10/2019, 00:52 AM (82 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

### PR DESCRIPTION
**Pull request by tiesmaster**
This fixes #36913 where `switch` expressions don't honor the user setting `NewLinesForBracesInControlBlocks`.

/cc @sharwell @CyrusNajmabadi

### CODE REVIEW

File: src/Workspaces/CSharpTest/Formatting/FormattingTests.cs [hunk 1]
```diff
@@ -9498,5 +9498,64 @@ enum TestEnum
...
+        };
+    }
+}",
+                @"
+class A
+{
+    void br()
+    {
+        var msg = 1 switch
+{
```
Comment (sharwell) [inline src/Workspaces/CSharpTest/Formatting/FormattingTests.cs]: ❔ Is there a reason this is not indented?

File: src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs [hunk 2]
```diff
@@ -370,6 +379,19 @@ public override AdjustNewLinesOperation GetAdjustNewLinesOperation(SyntaxToken p
                 }
             }
 
+            // * { - in the switch expression context
+            if (currentToken.Kind() == SyntaxKind.OpenBraceToken && currentToken.Parent != null && currentToken.Parent.IsKind(SyntaxKind.SwitchExpression))
```
Comment (sharwell) [inline src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs]:
```suggestion
            if (currentToken.IsKind(SyntaxKind.OpenBraceToken) && currentToken.Parent.IsKind(SyntaxKind.SwitchExpression))
```

File: src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs [hunk 3]
```diff
@@ -159,6 +159,15 @@ public override AdjustSpacesOperation GetAdjustSpacesOperation(SyntaxToken previ
...
```
Comment (sharwell) [inline src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs]:
```suggestion
            if (currentToken.IsKind(SyntaxKind.OpenBraceToken) && currentToken.Parent.IsKind(SyntaxKind.SwitchExpression))
```

File: src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs [hunk 4]
```diff
@@ -370,6 +379,19 @@ public override AdjustNewLinesOperation GetAdjustNewLinesOperation(SyntaxToken p
...
+            {
+                if (optionSet.GetOption(CSharpFormattingOptions.NewLinesForBracesInControlBlocks))
+                {
+                    return CreateAdjustNewLinesOperation(1, AdjustNewLinesOption.PreserveLines);
```
Comment (sharwell) [inline src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs]: ❔ Why is this using `PreserveLines` and not `ForceLinesIfOnSingleLine`. I see both approaches in the surrounding code but the difference is not clear to me.

File: src/Workspaces/CSharpTest/Formatting/FormattingTests.cs (hunk 1 above)
Comment (tiesmaster) [reply src/Workspaces/CSharpTest/Formatting/FormattingTests.cs]: TBH I started out in the test `NewLineForOpenBracesNonDefault()`, where most of input control blocks aren't indented. However, during development, a separate test case worked much better for me, when I was debugging how everything worked in the formatting engine.

I thought it makes most sense to keep a separate test like this, but didn't consider oddness of the indentation. I think it makes most sense to change it to being indented. Shall I change it to that?

File: src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs (hunk 2 above)
Comment (tiesmaster) [reply src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs]: Is see both approaches being used throughout the code base, and it trips me up every time. I don't see a difference between usages, except for personal preference, is there?

My preference also goes to `.IsKind()`. I'll update the PR with that.

File: src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs (hunk 4 above)
Comment (tiesmaster) [reply src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs]: I actually don't know what the difference is. I looked at how this works for the control blocks (`unsafe`, `if`, etc.), and took that approach.

I'll see if I can look into this, and explain if, and what the difference is.

File: src/Workspaces/CSharpTest/Formatting/FormattingTests.cs (hunk 1 above)
Comment (sharwell) [reply src/Workspaces/CSharpTest/Formatting/FormattingTests.cs]: It seems like this one brace should be indented, as that's the most likely scenario for formatting.

Comment (sharwell) [reply src/Workspaces/CSharpTest/Formatting/FormattingTests.cs]:
```suggestion
        {
```

File: src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs (hunk 2 above)
Comment (sharwell) [reply src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs]: `IsKind` is a bit cleaner, especially when compound conditions are involved. If someone sent a pull request that changed the use of `Kind` to `IsKind` for consistency, we'd likely merge it (as long as it only contained those changes and wasn't part of some other change).

File: src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs (hunk 4 above)
Comment (tiesmaster) [reply src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs]: Ok, just looked into to this, but cannot really make any sense of how this _exactly_ works. I've been playing around a bit with this option, and a couple scenario's that might trigger something here. For example, when I change the option to `ForceLinesIfOnSingleLine` on the given scenario then nothing changes, which is also what you'd expect (it will still apply a single line, since it's `...OnSingleLine`).

However, when you change the scenario to something like:

```csharp
var msg = 1 switch


{
    _ => null
};
```

Then I'd expect `PreserveLines` to maintain the lines between the `switch` keyword, and the opening brace, which is _what happens`. However, even with `ForceLinesIfOnSingleLine` I see identical behavior :( So I cannot really make any sense of how this is consumed exactly.

I might dig into this a bit further, but don't hold your breath for it ;)

Comment (sharwell) [reply src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs]: Is there a difference in the two for this?

```csharp
var msg = 1 switch { _ => null };
```

Thanks for looking into it the amount you did 😄

Comment (tiesmaster) [reply src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs]: No, there isn't. I just checked it now, but with all 4 branches (default vs. non-default, and `PreserveLines` vs `ForceLinesIfOnSingleLine`). It puzzles me how this supposes to work...

**Comment by tiesmaster** [comment]
@sharwell What was the outcome of the design meeting yesterday? Does it have any effect on this PR?

BTW I don't know if you've noticed, but the build is failing, but it's kinda weird. It is failing on the `SyntaxKind.SwitchExpression`:

```
error CS0117: 'SyntaxKind' does not contain a definition for 'SwitchExpression'
```

However, I don't see how that can happen (there shouldn't be any additional imports you need for this), and it wasn't failing for me in VS, but on the command-line build, locally, it also fails. Any ideas?

File: src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs [hunk 5]
```diff
@@ -159,6 +159,15 @@ public override AdjustSpacesOperation GetAdjustSpacesOperation(SyntaxToken previ
                 }
             }
 
+            // * { - in the switch expression context
+            if (currentToken.IsKind(SyntaxKind.OpenBraceToken) && currentToken.Parent.IsKind(SyntaxKind.SwitchExpression))
```
Comment (sharwell) [inline src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs]:
```suggestion
            if (currentToken.IsKind(SyntaxKind.OpenBraceToken) && currentToken.Parent.IsKind(SyntaxKindEx.SwitchExpression))
```

File: src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs [hunk 6]
```diff
@@ -159,6 +159,15 @@ public override AdjustSpacesOperation GetAdjustSpacesOperation(SyntaxToken previ
...
+            {
+                if (!optionSet.GetOption(CSharpFormattingOptions.NewLinesForBracesInControlBlocks))
```
Comment (sharwell) [inline src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs]: ❗️  See https://github.com/dotnet/roslyn/issues/36913#issuecomment-546015089 for the design review conclusion here.

```suggestion
                if (!optionSet.GetOption(CSharpFormattingOptions.NewLinesForBracesInObjectCollectionArrayInitializers))
```

File: src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs [hunk 7]
```diff
@@ -370,6 +379,19 @@ public override AdjustNewLinesOperation GetAdjustNewLinesOperation(SyntaxToken p
                 }
             }
 
+            // * { - in the switch expression context
+            if (currentToken.IsKind(SyntaxKind.OpenBraceToken) && currentToken.Parent.IsKind(SyntaxKind.SwitchExpression))
```
Comment (sharwell) [inline src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs]:
```suggestion
            if (currentToken.IsKind(SyntaxKind.OpenBraceToken) && currentToken.Parent.IsKind(SyntaxKindEx.SwitchExpression))
```

File: src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs [hunk 8]
```diff
@@ -370,6 +379,19 @@ public override AdjustNewLinesOperation GetAdjustNewLinesOperation(SyntaxToken p
...
+            {
+                if (optionSet.GetOption(CSharpFormattingOptions.NewLinesForBracesInControlBlocks))
```
Comment (sharwell) [inline src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs]:
```suggestion
                if (optionSet.GetOption(CSharpFormattingOptions.NewLinesForBracesInObjectCollectionArrayInitializers))
```

File: src/Workspaces/CSharpTest/Formatting/FormattingTests.cs [hunk 9]
```diff
@@ -9498,5 +9498,64 @@ enum TestEnum
...
+}");
+        }
+
+        [Fact, Trait(Traits.Feature, Traits.Features.Formatting)]
+        [WorkItem(36913, "https://github.com/dotnet/roslyn/issues/36913")]
+        public async Task NewLinesForBraces_SwitchExpression_NonDefault()
+        {
+            var changingOptions = new Dictionary<OptionKey, object>
+            {
+                { NewLinesForBracesInControlBlocks, false },
```
Comment (sharwell) [inline src/Workspaces/CSharpTest/Formatting/FormattingTests.cs]:
```suggestion
                { NewLinesForBracesInObjectCollectionArrayInitializers, false },
```

File: src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs (hunk 5 above)
Comment (tiesmaster) [reply src/Workspaces/CSharp/Portable/Formatting/Rules/NewLineUserSettingFormattingRule.cs]: Ah, I see. That's the trick ;)

Thnx, I'll incorporate all the suggestions now.

**Comment by cremor** [comment]
@sharwell It seems like this PR was approved several months ago, but was never merged. Why? I'd really like to see this fix in Visual Studio.

**Comment by sharwell** [comment]
I'll get this updated and prepared for merge.
