### PR TITLE
When we're loading dependencies, don't require exact versions

### LINKED ISSUE #53672: Compiler can't load an analyzer where a binding redirect may be needed
In https://github.com/microsoft/CsWin32/discussions/218, we had a report of a source generator that was failing to load in Omnisharp. Debugging revealed it the analyzer depends on System.Text.Json, and the NuGet package there depends on assembly version 4.1.3 of System.Numerics.Vectors. However, another dependency brings in 4.1.4 of System.Numerics.Vectors, which in a normal app would be resolved with a binding redirect at runtime. Since https://github.com/microsoft/CsWin32/issues/261 was fixed, the analyzer does package 4.1.4.

For our command line compilers, right now it works out that this analyzer will load, only because System.Numerics.Vectors 4.1.4 happens to be a dependency of the compiler and thus a direct is in place for it. But that's somewhat an implementation detail and could change. For Omnisharp however, it doesn't have a redirect and thus won't load. And there's no practical way to package both 4.1.3 and 4.1.4 versions of the dependency in the same NuGet package to work around the issues.

Discussing with @jaredpar it seems the best resolution here is to change our assembly loading rules a bit. When we load an analyzer, we require _exact matches_ of dependencies [here](https://github.com/dotnet/roslyn/blob/ac284e677662baaf9274eeb5dba45d2300ade0d6/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs#L188); changing that to allow an "or higher" would mean we'd be effectively doing a binding redirect at runtime, which would resolve these issues.

Omnisharp currently has a copy/paste of the analyzer assembly loading code in it's repo; once we have the compiler change in hand we should update that copy. Since we have an External Access shim, I'd propose we simply make an API for them to fetch the implementation Roslyn has and they can reuse that directly.

### LINKED ISSUE #56216: roslyn Code generators having issues when using external dependencies,. ex: Newtonsoft.Json
**Version Used**: 
3.11.0

**Steps to Reproduce**:

1. I created a generator project and added Newtonsoft.Json to it
2. my demo app does not has any reference to Newtonsoft.Json
3. ran the generator and it fails generation because Newtonsoft.Json is not found or one of its dependencies 
4. sometimes this works, but I haven't figure out yet, then it actually works.

NOTE:
I tried with the default System.Text.Json, and that's also failing.

**Expected Behavior**:
as mentioned in the github, we should be able to include external dlls
https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md#use-functionality-from-nuget-packages

**Actual Behavior**:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Description></Description>
    <AssemblyVersion>0.1</AssemblyVersion>
    <FileVersion>0.1</FileVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild> <!-- Generates a package at build -->
    <IncludeBuildOutput>false</IncludeBuildOutput> <!-- Do not include the generator as a lib dependency -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.11.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" PrivateAssets="all" GeneratePathProperty="true" />

    <!-- Package the generator in the analyzer directory of the nuget package -->
    <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />

    <!-- Package the Newtonsoft.Json dependency alongside the generator assembly -->
    <None Include="$(PkgNewtonsoft_Json)\lib\netstandard2.0\*.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
	
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StandardSDK.Attributes\StandardSDK.Attributes.csproj" />
  </ItemGroup>

</Project>

```
Exception:
```
=== Pre-bind state information ===
LOG: DisplayName = Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files/Microsoft Visual Studio/2022/Preview/MSBuild/Current/Bin/Roslyn/
LOG: Initial PrivatePath = NULL
Calling assembly : StandardSDKAnalyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn\VBCSCompiler.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Visual Studio/2022/Preview/MSBuild/Current/Bin/Roslyn/Newtonsoft.Json.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Visual Studio/2022/Preview/MSBuild/Current/Bin/Roslyn/Newtonsoft.Json/Newtonsoft.Json.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Visual Studio/2022/Preview/MSBuild/Current/Bin/Roslyn/Newtonsoft.Json.EXE.
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Visual Studio/2022/Preview/MSBuild/Current/Bin/Roslyn/Newtonsoft.Json/Newtonsoft.Json.EXE.
LOG: Attempting download of new URL file:///C:/Users/[user]/AppData/Local/Temp/VBCSCompiler/AnalyzerAssemblyLoader/1b1099df6f184afdae38c7566ffa98e4/5/Newtonsoft.Json.DLL.
LOG: Attempting download of new URL file:///C:/Users/[user]/AppData/Local/Temp/VBCSCompiler/AnalyzerAssemblyLoader/1b1099df6f184afdae38c7566ffa98e4/5/Newtonsoft.Json/Newtonsoft.Json.DLL.
LOG: Attempting download of new URL file:///C:/Users/[user]/AppData/Local/Temp/VBCSCompiler/AnalyzerAssemblyLoader/1b1099df6f184afdae38c7566ffa98e4/5/Newtonsoft.Json.EXE.
LOG: Attempting download of new URL file:///C:/Users/[user]/AppData/Local/Temp/VBCSCompiler/AnalyzerAssemblyLoader/1b1099df6f184afdae38c7566ffa98e4/5/Newtonsoft.Json/Newtonsoft.Json.EXE.

```

### PR DESCRIPTION
**Pull request by jasonmalinowski**
When we're loading analyzer dependencies, our current logic was to require the exact version that was requested from the loading assembly. This is problematic in a lot of cases where you would normally have a binding redirect to ensure assemblies load cleanly; by requiring exact versions we'd end up in diamond dependency cases where you couldn't practically produce an analyzer package that would cleanly load.

While doing this change, @RikkiGibson and I noticed several other problems:

1. There was an errant cache that was left in the .NET Core implementation, which meant that we'd sometimes reuse assemblies even when we were able to load them correctly. This has also been fixed as a prerequisite to the main fix, since otherwise it was difficult to prove that the behavior changes here weren't also going to impact the .NET Core implementation.
2. There were some race conditions in the implementation.

**REVIEWING COMMIT-AT-A-TIME IS HIGHLY RECOMMENDED**, since those changes are broken out to separate commits.

Fixes #53672
Fixes #56216

### CODE REVIEW

File: src/Workspaces/Core/Portable/Diagnostics/ShadowCopyAndAllowRedirectsAssemblyLoader.cs [hunk 1]
```diff
@@ -0,0 +1,50 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+// See the LICENSE file in the project root for more information.
+
+// We'll only build this into our netstasndard2.0 build to target .NET Framework;
+// if you're on .NET Core then you should be using Assembly Load Contexts which removes
+// the need to use this type entirely.
+
+#if !NETCOREAPP
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Diagnostics/ShadowCopyAndAllowRedirectsAssemblyLoader.cs:9]: Note, this is not included in our netcoreapp version, which is similar to what we do lower in the stack: the default one is implemented differently depending on target.

File: src/Tools/ExternalAccess/OmniSharp/Analyzers/OmnisharpAnalyzerLoaderFactory.cs [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+// The .NET Foundation licenses this file to you under the MIT license.
+// See the LICENSE file in the project root for more information.
+
+using Microsoft.CodeAnalysis.Diagnostics;
+
+namespace Microsoft.CodeAnalysis.ExternalAccess.OmniSharp.Analyzers
+{
+    internal static class OmnisharpAnalyzerAssemblyLoaderFactory
+    {
+        public static IAnalyzerAssemblyLoader CreateShadowCopyAssemblyLoader(string? baseDirectory = null)
```
Comment (jasonmalinowski) [inline src/Tools/ExternalAccess/OmniSharp/Analyzers/OmnisharpAnalyzerLoaderFactory.cs:11]: Right now Omnisharp is using a copy/paste of our shadow copy implementation. It hasn't gotten some of the fixes we've done over the years; this is simply going to offer them the opportunity to use ours directly.

Comment (jasonmalinowski) [reply src/Tools/ExternalAccess/OmniSharp/Analyzers/OmnisharpAnalyzerLoaderFactory.cs:11]: We should also just consider making our implementation public entirely.

File: src/Compilers/Test/Core/AssemblyLoadTestFixture.cs [hunk 3]
```diff
@@ -19,12 +20,34 @@ public sealed class AssemblyLoadTestFixture : IDisposable
...
+        /// </summary>
         public TempFile Delta1 { get; }
+
+        /// <summary>
+        /// An assembly with a reference to <see cref="Delta1"/>.
+        /// </summary>
         public TempFile Gamma { get; }
+
+        /// <summary>
+        /// An assembly with a reference to <see cref="Beta"/>.
```
Comment (RikkiGibson) [inline src/Compilers/Test/Core/AssemblyLoadTestFixture.cs:34]: I think this comment should say "Gamma".

File: src/Compilers/Test/Core/AssemblyLoadTestFixture.cs [hunk 4]
```diff
@@ -19,12 +20,34 @@ public sealed class AssemblyLoadTestFixture : IDisposable
...
+        /// </summary>
         public TempFile Alpha { get; }
 
+        /// <summary>
+        /// An assembly with no references, assembly version 2.
+        /// </summary>
         public TempFile Delta2 { get; }
+
+        /// <summary>
+        /// An assembly with a reference to <see cref="Delta1"/>.
```
Comment (RikkiGibson) [inline src/Compilers/Test/Core/AssemblyLoadTestFixture.cs:49]: I think this comment should say "Delta2".

File: src/Workspaces/Core/Portable/Diagnostics/ShadowCopyAndAllowRedirectsAssemblyLoader.cs [hunk 5]
```diff
@@ -0,0 +1,52 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+// See the LICENSE file in the project root for more information.
+
+// We'll only build this into our netstasndard2.0 build to target .NET Framework;
```
Comment (RikkiGibson) [inline src/Workspaces/Core/Portable/Diagnostics/ShadowCopyAndAllowRedirectsAssemblyLoader.cs:5]:
```suggestion
// We'll only build this into our netstandard2.0 build to target .NET Framework;
```

File: src/Workspaces/CoreTest/ShadowCopyAndAllowRedirectsAssemblyLoaderTests.cs [hunk 6]
```diff
@@ -0,0 +1,62 @@
...
+
+        [Fact]
+        public void AssemblyLoading_MultipleVersions()
+        {
+            var sb = new StringBuilder();
+
+            var loader = new ShadowCopyAndAllowRedirectsAssemblyLoader(baseDirectory: null);
+            loader.AddDependencyLocation(_testFixture.Gamma.Path);
+            loader.AddDependencyLocation(_testFixture.Epsilon.Path);
+            loader.AddDependencyLocation(_testFixture.Delta2.Path);
```
Comment (RikkiGibson) [inline src/Workspaces/CoreTest/ShadowCopyAndAllowRedirectsAssemblyLoaderTests.cs:41]: I was surprised that Delta1 wasn't included via 'AddDependencyLocation' here. Isn't that necessary for us to be put in a position to have to choose between Delta1 and Delta2?

File: src/Compilers/Test/Core/AssemblyLoadTestFixture.cs [hunk 7]
```diff
@@ -19,12 +20,34 @@ public sealed class AssemblyLoadTestFixture : IDisposable
         private readonly TempRoot _temp;
         private readonly TempDirectory _directory;
 
+        /// <summary>
+        /// An assembly with no references, assembly version 1.
```
Comment (RikkiGibson) [inline src/Compilers/Test/Core/AssemblyLoadTestFixture.cs:24]: Thanks for adding these.

File: src/Compilers/Test/Core/AssemblyLoadTestFixture.cs [hunk 8]
```diff
@@ -9,6 +9,7 @@
 using Microsoft.CodeAnalysis;
 using Microsoft.CodeAnalysis.CSharp;
 using Roslyn.Test.Utilities;
+using Xunit;
```
Comment (RikkiGibson) [inline src/Compilers/Test/Core/AssemblyLoadTestFixture.cs:12]: New using looks unused.

File: src/Workspaces/CoreTest/ShadowCopyAndAllowRedirectsAssemblyLoaderTests.cs (hunk 6 above)
Comment (jasonmalinowski) [reply src/Workspaces/CoreTest/ShadowCopyAndAllowRedirectsAssemblyLoaderTests.cs:41]: Delta1 isn't here because there is no Delta1 being shipped. In an actual source generator package, how would you ship two versions of the same DLL?

File: src/Compilers/Test/Core/AssemblyLoadTestFixture.cs (hunk 8 above)
Comment (jasonmalinowski) [reply src/Compilers/Test/Core/AssemblyLoadTestFixture.cs]: Removed.

File: src/Compilers/Test/Core/AssemblyLoadTestFixture.cs (hunk 3 above)
Comment (jasonmalinowski) [reply src/Compilers/Test/Core/AssemblyLoadTestFixture.cs]: Correct, fixed.

File: src/Workspaces/CoreTest/ShadowCopyAndAllowRedirectsAssemblyLoaderTests.cs (hunk 6 above)
Comment (jasonmalinowski) [reply src/Workspaces/CoreTest/ShadowCopyAndAllowRedirectsAssemblyLoaderTests.cs:41]: In some sense, that's the whole point of this PR: there's no actual way to make an analyzer package do what the other test does.

Comment (genlu) [reply src/Workspaces/CoreTest/ShadowCopyAndAllowRedirectsAssemblyLoaderTests.cs:41]: > Delta1 isn't here because there is no Delta1 being shipped. In an actual source generator package, how would you ship two versions of the same DLL?

I had the same question when I read the test. Please add a comment here :)

**Review by genlu — DISMISSED** [review]

**Comment by sharwell** [comment]
If I have a solution with two different projects, each with their own version of StyleCop.Analyzers installed, will the IDE still load both versions and match them with the corresponding project after this change?

**Comment by jasonmalinowski** [comment]
@sharwell, hmm, good point. Will add tests.

**Comment by jasonmalinowski** [comment]
> If I have a solution with two different projects, each with their own version of StyleCop.Analyzers installed, will the IDE still load both versions and match them with the corresponding project after this change?

@sharwell I've added a test for this to ensure that continues to work.

File: src/Workspaces/Core/Portable/Diagnostics/ShadowCopyAndAllowRedirectsAssemblyLoader.cs (hunk 1 above)
Comment (jasonmalinowski) [reply src/Workspaces/Core/Portable/Diagnostics/ShadowCopyAndAllowRedirectsAssemblyLoader.cs]: This is now obsolete since we're not doing different behavior.

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs [hunk 9]
```diff
@@ -326,6 +326,34 @@ public void AssemblyLoading_MultipleVersions_MultipleEqualMatches()
...
+
+            Assembly delta2 = loader.LoadFromPath(_testFixture.Delta2.Path);
+            Assembly delta2B = loader.LoadFromPath(_testFixture.Delta2B.Path);
+
+            // 2B or not 2B? That is the question...that depends on whether we're on .NET Core or not.
+
+#if NETCOREAPP
+
+            // On Core, we're able to load both of these into separate AssemblyLoadContexts.
+            Assert.NotEqual(delta2B.Location, delta2.Location);
```
Comment (RikkiGibson) [inline src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:347]: Should we additionally test that these locations are equal to `_testFixture.Delta2B.Path` and `_testFixture.Delta2.Path` respectively?

File: src/Compilers/Test/Core/AssemblyLoadTestFixture.cs [hunk 10]
```diff
@@ -327,16 +389,28 @@ public int GetFileAttributes(string path)
 
         private static TempFile GenerateDll(string assemblyName, TempDirectory directory, string csSource, params MetadataReference[] additionalReferences)
         {
+            return GenerateDll(assemblyName, directory, csSource, additionalReferences, publicSign: false);
+        }
+
+        private static TempFile GenerateDll(string assemblyName, TempDirectory directory, string csSource, MetadataReference[] additionalReferences, bool publicSign)
```
Comment (RikkiGibson) [inline src/Compilers/Test/Core/AssemblyLoadTestFixture.cs:395]: Should 'publicSign' be before 'additionalReferences' here so 'additionalReferences' can still be 'params'?

**Review by RikkiGibson — APPROVED** [review]
Change looks good to me! Thanks so much for the refactoring of desktop-specific stuff and for making the test fixture much more clear.

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs (hunk 9 above)
Comment (jasonmalinowski) [reply src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:347]: Sure, that'd be good to add.

File: src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs [hunk 11]
```diff
@@ -326,6 +326,34 @@ public void AssemblyLoading_MultipleVersions_MultipleEqualMatches()
...
+            StringBuilder sb = new StringBuilder();
+
+            var loader = new DefaultAnalyzerAssemblyLoader();
+            loader.AddDependencyLocation(_testFixture.Delta2.Path);
+            loader.AddDependencyLocation(_testFixture.Delta2B.Path);
+
+            Assembly delta2 = loader.LoadFromPath(_testFixture.Delta2.Path);
+            Assembly delta2B = loader.LoadFromPath(_testFixture.Delta2B.Path);
+
+            // 2B or not 2B? That is the question...that depends on whether we're on .NET Core or not.
```
[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/Compilers/Core/CodeAnalysisTest/DefaultAnalyzerAssemblyLoaderTests.cs:342]: Eh, I assume it'll become as famous as the rest of Shakespeare.

File: src/Compilers/Test/Core/AssemblyLoadTestFixture.cs (hunk 10 above)
Comment (jasonmalinowski) [reply src/Compilers/Test/Core/AssemblyLoadTestFixture.cs:395]: Oh, hmm, it does mean we then need to specify it for everything, but maybe that's for the best to be explicit!

Comment (RikkiGibson) [reply src/Compilers/Test/Core/AssemblyLoadTestFixture.cs:395]: > it does mean we then need to specify it for everything

I don't think I understood this, but given this, the existing way is fine, and if you happen to find a way of adjusting the signature that makes it feel nicer that's great too.

Comment (jasonmalinowski) [reply src/Compilers/Test/Core/AssemblyLoadTestFixture.cs:395]: Oh I see what you mean, keep the params but make the bool go first. Yeah that's better.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 12]
```diff
@@ -54,31 +52,18 @@ public Assembly LoadFromPath(string fullPath)
 
         #endregion
 
-        private Assembly LoadFromPathUnchecked(string fullPath)
-        {
-            return LoadFromPathUncheckedCore(fullPath);
-        }
-
-        private Assembly LoadFromPathUncheckedCore(string fullPath, AssemblyIdentity identity = null)
+        protected Assembly LoadFromPathUnchecked(string fullPath)
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:55]: Please add a doc comment that helps differentiate why you should call this method over `LoadFromPathImpl`. 

Given the relationship between these two methods perhaps consider naming them such that they have an obvious relationship. Example: 

- `LoadFromPathUncheckedImpl(string fullPath)`
- `LoadFromPathUnchecked(string fullPath)`

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs [hunk 13]
```diff
@@ -49,6 +87,96 @@ private Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs a
...
+                Debug.Assert(pathList.Count > 0);
+                candidatePaths = pathList.ToImmutableArray();
+            }
+
+            // Find the highest version that satisfies the original request. We'll match for the highest version we can, assuming it
+            // actually matches the original request
+            string? bestPath = null;
+            Version? bestIdentityVersion = null;
+
+            foreach (var candidatePath in candidatePaths)
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs:157]: This introduces a bit of non-determinism. Consider that if the same assembly is listed with two different paths the path we pick for the assembly is non-deterministic because we don't sort the paths here. 

That will matter because while it's identical assemblies the contents of the containing directory are not necessarily identical. If memory serves the CLR will look for dependencies of an assembly in `LoadFrom` in the same directory the assembly was loaded from. Hence the set of dependent `Assembly` resolved could be diff in diff directories.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs [hunk 14]
```diff
@@ -49,6 +87,96 @@ private Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs a
...
+            lock (_guard)
+            {
+
+                // First, check if this loader already loaded the requested assembly:
+                if (_loadedAssembliesByIdentity.TryGetValue(requestedIdentity, out var existingAssembly))
+                {
+                    return existingAssembly;
+                }
+                // Second, check if an assembly file of the same simple name was registered with the loader:
+                var pathList = GetPaths(requestedIdentity.Name);
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs:142]: Consider `pathSet` instead of `pathList` as the return type is a hashset

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs [hunk 15]
```diff
@@ -49,6 +87,96 @@ private Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs a
...
+                if (pathList is null)
+                {
+                    return null;
+                }
+
+                Debug.Assert(pathList.Count > 0);
+                candidatePaths = pathList.ToImmutableArray();
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs:149]: Given that `pathList` is immutable already and we don't sort what is the value in creating a new immutable collection here?

**Review by jaredpar — CHANGES_REQUESTED** [review]

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs [hunk 16]
```diff
@@ -49,6 +87,96 @@ private Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs a
...
+            lock (_guard)
+            {
+                if (_loadedAssemblyIdentitiesByPath.TryGetValue(fullPath, out var existingIdentity))
+                {
+                    return existingIdentity;
+                }
+            }
+
+            var identity = AssemblyIdentityUtils.TryGetAssemblyIdentity(fullPath);
+            return AddToCache(fullPath, identity);
```
[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs:104]: @jaredpar: this is unchanged from the current implementation:

https://github.com/dotnet/roslyn/blob/196e9531ce3c8a104676c4590fe2b323ad542901/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs#L123-L137

I don't know why it's done that way either.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 17]
```diff
@@ -87,129 +72,32 @@ private Assembly LoadFromPathUncheckedCore(string fullPath, AssemblyIdentity ide
                 loadedAssembly = LoadFromPathImpl(fullPath);
```
[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:72]: It's null annotated now, do you want something stronger? (That's not a pattern we're doing in the IDE at least, if that's a common pattern in the compiler that's new to me.)

[the remark this answers is not in the document]
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:72]: It's `null` annotated but at this layer in the compiler it's hard to confirm that everyone who implemented has enabled nullable. That's why I was suggesting an `Assert` and nothing more. Simple check on return. Don't feel incredibly strong about it.

File: src/Workspaces/CoreTest/ShadowCopyAndAllowRedirectsAssemblyLoaderTests.cs (hunk 6 above)
Comment (jasonmalinowski) [reply src/Workspaces/CoreTest/ShadowCopyAndAllowRedirectsAssemblyLoaderTests.cs]: Comment clarified.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs (hunk 15 above)
Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs:149]: Old code, fixing.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs (hunk 14 above)
Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs:142]: This local is now removed in and just using "candidatePaths" instead.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs [hunk 18]
```diff
@@ -49,6 +87,96 @@ private Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs a
...
+                else
+                {
+                    _loadedAssemblyIdentitiesByPath[fullPath] = identity;
+                }
+            }
+
+            return identity;
+        }
+
+        private Assembly? Load(string displayName)
```
[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs:125]: Name change seems appropriate, will do.

For your second question, are you referring to the AssemblyResolve hook also catching all exceptions and returning null? That behavior apparently dates back to f8f20f002630e74e14285c19a4aed1b9d4a0ea50, which I think appears to be a general "let's not let exceptions leak of any kind" sort of change. Maybe @tmeschter remembers why that was done...

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs [hunk 19]
```diff
@@ -49,6 +87,96 @@ private Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs a
...
+                    return existingIdentity;
+                }
+            }
+
+            var identity = AssemblyIdentityUtils.TryGetAssemblyIdentity(fullPath);
+            return AddToCache(fullPath, identity);
+        }
+
+        [return: NotNullIfNotNull("identity")]
+        private AssemblyIdentity? AddToCache(string fullPath, AssemblyIdentity? identity)
```
[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs:108]: Inlined.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs (hunk 17 above)
[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:72]: Going to leave this as is unless you have strong pushback -- we don't do this generally...

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs (hunk 13 above)
Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs:156]: @jaredpar any specific preference to the preferred sort, or just sort via StringComparer.Ordinal or something?

Oddly the current comparer for the hashset-based comparer is PathComparer, which does a bunch of extra comparisons around relative pathing and such to attempt to "normalize" the path. I was going to just switch this over to an ImmutableSortedSet but PathComparer doesn't implement that (since it would seem insane to do so).

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs (hunk 18 above)
[the remark this answers is not in the document]
Comment (tmeschter) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs]: I have a vague idea that an `AssemblyResolve` hook throwing an exception may prevent other hooks from running, and in that case we don't want a failure in Roslyn to hork some other part of the product.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs (hunk 12 above)
Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:55]: Added some docs and also took your rename since that made things clearer now, especially now that the "Core" method is out of the way.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs [hunk 20]
```diff
@@ -25,6 +29,11 @@ namespace Microsoft.CodeAnalysis
     /// </remarks>
     internal class DefaultAnalyzerAssemblyLoader : AnalyzerAssemblyLoader
```
[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs:30]: I added a remark to the base type. One general observation is IAnalyzerAssemblyLoader's docs themselves state that:

https://github.com/dotnet/roslyn/blob/948cccc09fa88a638bc6c67871c37fec91742c99/src/Compilers/Core/Portable/DiagnosticAnalyzer/IAnalyzerAssemblyLoader.cs#L34-L37

Which seems to more or less say that if files change, you're expected to ignore them and keep returning old values. Why that comment is there is unclear.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs [hunk 21]
```diff
@@ -87,129 +72,32 @@ private Assembly LoadFromPathUncheckedCore(string fullPath, AssemblyIdentity ide
...
-                {
-                    _loadedAssembliesByIdentity.Add(identity, assembly);
-                }
-
-                // An assembly file might be replaced by another file with a different identity.
-                // Last one wins.
-                _loadedAssembliesByPath[fullPath] = assembly;
-
-                return assembly;
+                _loadedAssembliesByPath[fullPath] = loadedAssembly;
```
[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerAssemblyLoader.cs:93]: This appears to be a bug if the goal is to ensure that two loads for the same path always return the same thing per the interface documentation, but it's been around since https://github.com/dotnet/roslyn/pull/11956. @mavasani or @tmat any chance if this is a load-bearing bug?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs (hunk 13 above)
Comment (jaredpar) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs:152]: Lets use `StringComparer.Ordinal`. It's really the only sane decision when it comes to path analysis

Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs:152]: @jaredpar Switched to sort with StringComparer.Ordinal; there's still a different equality comparer in the hash set that is used for determining whether two paths are the same, that's being left untouched (but would be an easy follow-up PR to clean up.)

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs (hunk 18 above)
[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs]: Indeed, a quick test confirms that throwing prevents futher AssemblyResolve hooks from being called, and the exception is treated an inner exception to the mail failure itself. I'll add a comment as having a try/catch here seems generally prudent, at least in the VS case.

[the remark this answers is not in the document]
Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/DefaultAnalyzerAssemblyLoader.Desktop.cs]: Comment added.

**Review by jaredpar — APPROVED** [review]
