### PR TITLE
Fix TypeParamRefs in included xml docs in C# not resolving correctly:

### LINKED ISSUE #21348: `typeparamref` in a member's doc comment which refers to the containing type's type parameter raises an error if in an included XML file
**Version Used**: 2.3.1

**Steps to Reproduce**:

Consider the following C# file:
```csharp
class Foo<T>
{
    /// <include file='Foo.xml' path='docs/*'/>
    public void DoWork()
    { }
}
```

`Foo.xml` is:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<docs>
  <summary>
    <typeparamref name="T" />
  </summary>
</docs>
```

When compiled this produces the following error:
```
Foo.cs(3,9,3,48): warning CS1735: XML comment on 'Foo<T>.DoWork()' has a typeparamref tag for 'T', but there is no type parameter by that name
```

However, when the doc comment is moved inline, there is no error:
```csharp
class Foo<T>
{
    /// <summary>
    /// <typeparamref name="T" />
    /// </summary>
    public void DoWork()
    { }
}
```

### PR DESCRIPTION
**Pull request by chsienki**
- When resolving TypeParamRefs in an included xml comment in c#, ensure we add any parent generic types to the binder we create
 - Add a repro test (essentially a copy of the VB test Include_TypeParamAndTypeParamRefHandling)

Fixes #21348

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.IncludeElementExpander.cs [hunk 1]
```diff
@@ -576,23 +579,27 @@ private static Binder MakeNameBinder(bool isParameter, Symbol memberSymbol, CSha
                 }
                 else
                 {
-                    switch (memberSymbol.Kind)
+                    bool continueSearch = true;
+                    for (var currentSymbol = memberSymbol; currentSymbol != null && continueSearch; currentSymbol = currentSymbol.ContainingSymbol, continueSearch = isTypeRef)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.IncludeElementExpander.cs]: >continueSearch = isTypeRef [](start = 148, length = 26)

I didn't fully understand this. Could the loop be written differently (maybe a do/while) to make the intent clearer?
In particular `continueSearch = isTypeRef` was strange. Maybe it would be clearer to have a flag for "first iteration" (if needed).

File: src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs [hunk 2]
```diff
@@ -3782,6 +3782,167 @@ Part 2.
...
+            var includeElementTemplate = @"<include file='{0}' path='//target'/>";
+            string includeElement = string.Format(includeElementTemplate, xmlFilePath);
+
+            var sourceTemplate = @"
+
+/// {0}
+class OuterClass<X>
+{{
+    /// {0}
+    class InnerClass<Y>
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs]: Is the binding for a method significantly enough different that we should add a test for that?

File: src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.IncludeElementExpander.cs [hunk 3]
```diff
@@ -220,12 +220,15 @@ private XNode[] Rewrite(XNode node, string currentXmlFilePath, CSharpSyntaxNode
...
-                            else if (ElementNameIs(element, DocumentationCommentXmlNames.TypeParameterElementName) ||
-                                ElementNameIs(element, DocumentationCommentXmlNames.TypeParameterReferenceElementName))
+                            else if (ElementNameIs(element, DocumentationCommentXmlNames.TypeParameterElementName))
                             {
-                                BindName(attribute, originatingSyntax, isParameter: false);
+                                BindName(attribute, originatingSyntax, isParameter: false, isTypeRef: false);
+                            }
+                            else if(ElementNameIs(element, DocumentationCommentXmlNames.TypeParameterReferenceElementName))
+                            {
+                                BindName(attribute, originatingSyntax, isParameter: false, isTypeRef: true);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.IncludeElementExpander.cs]: >isTypeRef [](start = 91, length = 9)

nit: consider renaming `isTypeRef` to `isTypeParameterRef` (here and throughout the stack)

**Comment by jaredpar** [comment]
Done with review pass (iteration 1)

File: src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs (hunk 2 above)
Comment (chsienki) [reply src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs]: It's not, but this test covers both the outer/inner classes, and a method inside

File: src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.IncludeElementExpander.cs (hunk 3 above)
Comment (chsienki) [reply src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.IncludeElementExpander.cs]: We special case the included files, meaning the logic between a inline and an included document is actually different. Primarily the inline case uses the binder factory and visitor to do binding, whereas inline has its own logic (the binder factory uses parent nodes to figure out the relationships, and in the include case we're in a different syntax tree, so the parent relationship isn't there). 

I played around trying to make the factory work for the include case, but it started getting quite complicated; it seemed simpler to fix the 'special' include binding logic to properly handle this one extra case, rather than swap in the more generic walker.

File: src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.IncludeElementExpander.cs [hunk 4]
```diff
@@ -576,24 +579,28 @@ private static Binder MakeNameBinder(bool isParameter, Symbol memberSymbol, CSha
...
+                                break;
+                            case SymbolKind.Method:
+                                MethodSymbol methodSymbol = (MethodSymbol)currentSymbol;
+                                if (methodSymbol.Arity > 0)
+                                {
+                                    binder = new WithMethodTypeParametersBinder(methodSymbol, binder);
+                                }
+                                break;
+                        }
+                    } while (isTypeParameterRef && (currentSymbol = currentSymbol.ContainingSymbol) != null);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.IncludeElementExpander.cs]: >(currentSymbol = currentSymbol.ContainingSymbol) [](start = 51, length = 48)

Cast to `(object)` to use reference equals.
