### PR TITLE
Do not require an assembly-level ExtensionAttribute...

### LINKED ISSUE #365: Roslyn C# compiler doesn't recognize extension methods from most libraries written in C++/CLI and other CLI languages
@latkin reported:

The Roslyn C# compiler, unlike the legacy compiler, requires an assembly-level `ExtensionAttribute` in order for extension methods defined in that assembly to be considered.  The legacy compiler only required method-level and class-level `ExtensionAttributes`.

This is a breaking change that was deemed acceptable due to perf wins.  It did not affect C# and VB libraries, since C# and VB compilers have always provided special support for extension methods, by automatically adding the assembly-level `ExtensionAttribute` for you even if you leave it out.

Besides C# and VB, though, I don't know of any other CLI languages that have special compiler support for defining extension members.  C# usage of libraries from all of these languages is now broken by Roslyn.

F# was noticed early, and has already been special-cased to preserve back-compat.

C++/CLI suffers from the same issue, though, and is still broken.  All online documentation and sample code I can find leaves out the assembly-level attribute, because it was never needed in the past.  Even the estimable Jon Skeet forgets that the assembly-level attribute is required: [http://stackoverflow.com/a/995154/1366219](http://stackoverflow.com/a/995154/1366219)  Another highly-voted answer here: [http://stackoverflow.com/a/6012771/1366219](http://stackoverflow.com/a/6012771/1366219)

Other CLI languages like Nemerle, Boo, Iron*, etc will also be affected.

### PR DESCRIPTION
**Pull request by gafter**
in order for the C# compiler to recognize extension methods
contained within the assembly. In other words, we assume every
PE assembly may contain extension methods.
Fixes #365

What we want to do with this PR depends on performance run results that we should have by tomorrow morning.
/cc @jaredpar @VSadov @pharring

### CODE REVIEW

**Comment by VSadov** [comment]
I guess it is the easiest way to know for sure.

**Comment by VSadov** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEAssemblySymbol.cs [hunk 1]
```diff
@@ -233,20 +228,11 @@ public override bool MightContainExtensionMethods
...
-                    var mightContainExtensionMethods = module.HasExtensionAttribute(_assembly.Handle, ignoreCase: false) ||
-                                                       module.HasFSharpInterfaceDataVersionAttribute(_assembly.Handle);
-
-                    _lazyContainsExtensionMethods = mightContainExtensionMethods.ToThreeState();
-                }
-
-                return _lazyContainsExtensionMethods.Value();
+                // While the specification for ExtensionAttribute requires that the containing assembly
+                // have the attribute if any type in the assembly has the attribute, some compilers do
+                // not propertly follow that spec. Therefore we pessimistically assume every assembly
```
Comment (pharring) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEAssemblySymbol.cs]: typo: properly

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEAssemblySymbol.cs [hunk 2]
```diff
@@ -233,20 +228,11 @@ public override bool MightContainExtensionMethods
...
             {
-                if (!_lazyContainsExtensionMethods.HasValue())
-                {
-                    var moduleSymbol = this.PrimaryModule;
-                    var module = moduleSymbol.Module;
-                    // The F# compiler may not emit an assembly-level ExtensionAttribute, and previous versions of C# never checked for it.
-                    // In order to avoid a breaking change (while preserving the perceived performance benefits of not looking for extension
-                    // methods in assemblies that don't contain them), we'll also look for FSharpInterfaceDataVersionAttribute.
-                    var mightContainExtensionMethods = module.HasExtensionAttribute(_assembly.Handle, ignoreCase: false) ||
-                                                       module.HasFSharpInterfaceDataVersionAttribute(_assembly.Handle);
```
Comment (KevinH-MS) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEAssemblySymbol.cs]: Should we also remove these helper methods (at least the "HasFSharpInterfaceDataVersionAttribute" one...assuming it's not used elsewhere)?

**Comment by KevinH-MS** [comment]
:+1:

**Comment by jaredpar** [comment]
:+1:

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEAssemblySymbol.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEAssemblySymbol.cs]: Yes... done.

**Comment by gafter** [comment]
Batch compiler performance tests reveal no regression. Running IDE and typing performance tests now...

**Comment by pharring** [comment]
IDE tests look good too.
From a performance point of view, this change has negligible impact.

**Comment by davkean** [comment]
Do you have tests that test a large set of reference assemblies, such as Store, Phone, UAP, or portable?

**Comment by tmat** [comment]
Also some 30MB assembly produced by C++/CLI would be good to include in such testing

**Comment by pharring** [comment]
@davkean  We have large sets, but all our perf tests are desktop solutions. Why do you think other target frameworks would be significant?

@tmat why? The perf concern is that we now have to check *all* assemblies, so a C++/CLI assembly with hand-written extension methods would be treated just the same as a VB or C# one.

**Comment by davkean** [comment]
@pharring Because, unlike desktop which typically only references small amounts of assemblies from the framework (only the ones the templates or user has chosen), the rest of the project types automatically reference  60 - 100 assemblies _by default_.

**Comment by davkean** [comment]
@pharring Should clarify, what I mean is that it doesn't matter if it's desktop or something else, as long as something with a significant amount of referenced assemblies is represented.

**Comment by tmat** [comment]
@pharring 
If an assembly reference doesn't have an extension attribute on its AssemblyDef wouldn't we now need to check all its methods for the attribute to determine that there are no public extension methods declared in it?

**Comment by pharring** [comment]
@tmat Yes, exactly. That's why this is a performance concern for all compilations. It doesn't matter whether the referenced assembly is written in C#, C++/CLI or Martian.

@davkean I understand. We don't have such automated tests today. We can do manual testing for it. Do you think that building the portable pieces of Roslyn itself would be a good enough test?

**Comment by gafter** [comment]
@tmat Not exactly. We now have to check all *types* in the assembly. We still require the containing type to be attributed.

**Comment by davkean** [comment]
@pharring Yes, assuming that you are opt'ing into the default behavior of portable (<ImplicitlyExpandTargetFramework>true</ImplicitlyExpandTargetFramework>), and not building against packages representing the framework.

**Comment by tmat** [comment]
@gafter @pharing OK, so we check all types. The reason why I'm mentioning C++ is that managed C++ may generate an enormous assemblies with a lot of types, unlike C# and VB.

**Comment by gafter** [comment]
@AlekseyTs FYI
