### PR TITLE
Do not report unused expression value (IDE0058) for expression body

### LINKED ISSUE #32942: Fix IDE0058 on lambda expression results in unexpected behavior
**Version Used**: 3.0.19.6832 (231aeb8b)

**Steps to Reproduce**:

1. The following code is common in EF Core migrations.

```
_ = migrationBuilder.CreateTable(
                name: "",
                columns: table => new {},
                constraints: table => table.PrimaryKey("PK_", x => x.Id));
                                      ^^^
```

2. Fix IDE0058 on code highlighted.

**Expected Behavior**:

Discard is added at correct position.

```
_ = migrationBuilder.CreateTable(
                name: "",
                columns: table => new {},
                constraints: table => _ = table.PrimaryKey("PK_", x => x.Id));
```

**Actual Behavior**:

Discard is added at wrong position.

```
_ = _ = migrationBuilder.CreateTable(
                name: "",
                columns: table => new {},
                constraints: table => table.PrimaryKey("PK_", x => x.Id));
```

Also, if fix other IDE0058, then select fix all, which includes the one shown above, SyntaxEditorBasedFixAllProvider will crash.

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.Kind(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.GetDeclarationKind(SyntaxNode declaration)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.AsNodeLike(SyntaxNode existingNode,SyntaxNode newNode)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.ReplaceNode(SyntaxNode root,SyntaxNode declaration,SyntaxNode newDeclaration)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.ReplaceChange.Apply(SyntaxNode root,SyntaxGenerator generator)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at async Microsoft.CodeAnalysis.RemoveUnusedParametersAndValues.AbstractRemoveUnusedValuesCodeFixProvider`11.FixAllAsync[TExpressionSyntax,TStatementSyntax,TBlockSyntax,TExpressionStatementSyntax,TLocalDeclarationStatementSyntax,TVariableDeclaratorSyntax,TForEachStatementSyntax,TSwitchCaseBlockSyntax,TSwitchCaseLabelOrClauseSyntax,TCatchStatementSyntax,TCatchBlockSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.SyntaxEditorBasedFixAllProvider.FixDocumentAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.SyntaxEditorBasedFixAllProvider.GetFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.SyntaxEditorBasedFixAllProvider.GetFixAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(<Unknown Parameters>)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass17_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #32942

### CODE REVIEW

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs [hunk 1]
```diff
@@ -173,7 +173,10 @@ private void AnalyzeExpressionStatement(OperationAnalysisContext context)
                     //  4. Bail out if there is language specific syntax to indicate an explicit discard.
                     //     For example, VB call statement is used to explicitly ignore the value returned by
                     //     an invocation by prefixing the invocation with keyword "Call".
-                    if (_symbolStartAnalyzer._compilationAnalyzer.IsCallStatement(expressionStatement))
+                    //     Similarly, we do not want to flag an expression of a C# expression body.
+                    if (_symbolStartAnalyzer._compilationAnalyzer.IsCallStatement(expressionStatement) ||
+                        (expressionStatement.Parent is IBlockOperation blockParent &&
+                         _symbolStartAnalyzer._compilationAnalyzer.IsExpressionBody(blockParent)))
```
Comment (sharwell) [inline src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs]: 💡 Having both `||` and `&&` in the expression is hard to read, especially when they are placed at the end of the line. Any of the following would be better:

1. Make sure the parenthesized `&&` expression fits on one line
2. Move the `&&` expression evaluation to a local function or helper method
3. Place the operators at the beginning of the line instead of the end of the line (not as good as the previous two options, but it at least makes the reader aware of the situation)

Comment (mavasani) [reply src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.BlockAnalyzer.cs]: Thanks, hope https://github.com/dotnet/roslyn/pull/33042/commits/7db8845eca416b9ae32ecb7223d7a2667e250693 improves the readability.

**Comment by mavasani** [comment]
@jinujoseph @vatsalyaagrawal for approval

File: src/Features/CSharp/Portable/RemoveUnusedParametersAndValues/CSharpRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs [hunk 2]
```diff
@@ -32,6 +32,10 @@ protected override bool IsIfConditionalDirective(SyntaxNode node)
         protected override bool IsCallStatement(IExpressionStatementOperation expressionStatement)
             => false;
 
+        protected override bool IsExpressionOfExpressionBody(IExpressionStatementOperation expressionStatementOperation)
+            => expressionStatementOperation.Parent is IBlockOperation blockOperation &&
+               !blockOperation.Syntax.IsKind(SyntaxKind.Block);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/RemoveUnusedParametersAndValues/CSharpRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs]: hrmmm... the `!blockOperation.Syntax.IsKind(SyntaxKind.Block)` seems a little iffy to me.  I'd much rather have it be an explicit `.IsKind(ArrowExpressionClause)` or something like that...

**Comment by EamonNerbonne** [comment]
This fix for #32942 appears to be wrong or at least surprising.  I use this warning to detect possibly misused methods, and while this change avoids the incorrect *autofix* for an unused expression value, it also suppressed the warning.

Specifically, the warning now no longer works whenever an expression is unused due to being the result of a void-returning expression-bodied lambda; before, the warning was reported (as expected), yet the autofix was wrong.

Is that by design?  It certainly surprised me...
