### PR TITLE
Correct parsing of a parenthesized constant pattern expression in switch expression arm

### LINKED ISSUE #33675: Wrong parsing of parenthesized constant pattern expression in switch expression arm
**Version Used**: 

master branch from feb 26

**Steps to Reproduce**:

Compile the following code:
```c#
class C {
  bool M(object o) {
    const int X = 42;
    return o switch { (X) => true, _ => false };
  }
}
```

**Expected Behavior**:

Compile fine, do constant pattern matching at runtime.

**Actual Behavior**:

> CS0118: 'X' is a variable but is used like a type
> CS1525: Invalid expression term '=>'

cc @gafter

### PR DESCRIPTION
**Pull request by gafter**
Fixes #33675

### CODE REVIEW

File: src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs [hunk 1]
```diff
@@ -7564,5 +7564,42 @@ public void BrokenSwitchExpression_03()
             }
             EOF();
         }
+
+        [Fact, WorkItem(33675, "https://github.com/dotnet/roslyn/issues/33675")]
+        public void ParenthesizedNamedConstantPatternInSwitchExpression()
+        {
+            UsingExpression("e switch { (X) => 1 }");
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs]: We are considering adding onepls at some point, right? Is this going to interfere with being able to pattern match on them?

File: src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs [hunk 2]
```diff
@@ -547,16 +547,17 @@ class Program
...
-            var source = @"
+            var t = typeof(NameofTests);
+            var source = @"using System.Linq;
 class C
 {
     public static void Main(string[] args)
     {
         var t = typeof(C);
-        foreach (var m in t.GetMethods())
+        foreach (var m in t.GetMethods().Where(m => m.DeclaringType == t).OrderBy(m => m.Name))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs]: >.Where(m => m.DeclaringType == t) [](start = 40, length = 33)

I think this can be achieved by including ```DeclaredOnly.BindingFlags``` into flags passed to ```GetMethods```

File: src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs [hunk 3]
```diff
@@ -547,16 +547,17 @@ class Program
                 );
         }
 
-        [ClrOnlyFact(ClrOnlyReason.MemberOrder)]
+        [Fact]
         public void TestNameofIndexerName()
         {
-            var source = @"
+            var t = typeof(NameofTests);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs]: >var t = typeof(NameofTests); [](start = 12, length = 28)

Is this local used?

File: src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs]: >UsingExpression("e switch { (X) => 1 }"); [](start = 12, length = 41)

Please add a unit test that executes the scenario from the issue and verifies expected runtime behavior.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 2)

File: src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs]: No.  Parsing oneple patterns will require some other disambiguating syntax.

Comment (gafter) [reply src/Compilers/CSharp/Test/Syntax/Parsing/PatternParsingTests.cs]: I think we already have tests for binding and code gen of parenthesized constants, but I'll add another if you think it is valuable.

**Comment by gafter** [comment]
I believe I have resolved all of the comments?  Do you have any others?
