### PR TITLE
Make SymbolDisplay show nullable enum values as enums

### LINKED ISSUE #66514: Nullable enums in parameter value shown as numbers in SymbolDisplay
**Version Used**: 4.4.0

**Steps to Reproduce**:

Hover the following methods in Visual Studio and see display text in quick info:
```csharp
public void Enum(ConsoleKey key = ConsoleKey.P) { }
public void NullableEnum(ConsoleKey? key = ConsoleKey.P) { }
```

**Expected Behavior**:

Both display the enum names:

```csharp
void Test.Enum([ConsoleKey key = ConsoleKey.P])
void Test.NullableEnum([ConsoleKey? key = ConsoleKey.P])
```

**Actual Behavior**:

`NullableEnum` displays a number:

```csharp
void Test.Enum([ConsoleKey key = ConsoleKey.P])
void Test.NullableEnum([ConsoleKey? key = 80])
```

### PR DESCRIPTION
**Pull request by yufeih**
Fixes #66514

Shows nullable enum values as enums instead of numbers

### CODE REVIEW

File: src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor.cs [hunk 1]
```diff
@@ -120,6 +123,23 @@ private void AddEnumConstantValue(INamedTypeSymbol enumType, object constantValu
...
+            if (typeSymbol.TypeKind != TypeKind.Struct)
+                return typeSymbol;
+
+            var namedTypeSymbol = (INamedTypeSymbol)typeSymbol;
+            if (namedTypeSymbol.IsGenericType && namedTypeSymbol.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T)
+            {
+                return namedTypeSymbol.TypeArguments[0];
+            }
+
+            return typeSymbol;
```
Comment (cston) [inline src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor.cs:140]: >return typeSymbol; [](http://example.com/codeflow?start=12&length=18)

It looks like there are a couple of existing helper methods: IsNullableType() and GetNullableUnderlyingType(). Consider using those here.

File: src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs [hunk 2]
```diff
@@ -3997,6 +3997,112 @@ void P(E e = (E)(-2), E f = (E)(-1), E g = (E)0, E h = (E)(-3))
                 SymbolDisplayPartKind.Punctuation); //)
         }
 
+        [Fact]
+        public void DefaultParameterValues_NullableEnum()
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs:4001]: >DefaultParameterValues_NullableEnum [](http://example.com/codeflow?start=20&length=35)

Consider adding a corresponding test for VB.

File: src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs [hunk 3]
```diff
@@ -3997,6 +3997,112 @@ void P(E e = (E)(-2), E f = (E)(-1), E g = (E)0, E h = (E)(-3))
...
+    A1 = -2,
+    B = 1,
+    B1 = 1,
+    C = 0,
+    C1 = 0,
+}
+
+struct S
+{
+    void P(E? e = null, E? f = E.A, E? g = E.A | E.B, E? h = (E)(-3))
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs:4017]: >) [](http://example.com/codeflow?start=68&length=1)

Consider adding `E? i = 0`.

File: src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor.cs (hunk 1 above)
Comment (yufeih) [reply src/Compilers/Core/Portable/SymbolDisplay/AbstractSymbolDisplayVisitor.cs]: Yep these are exactly what I'm looking for.

File: src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs (hunk 2 above)
Comment (yufeih) [reply src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs:4001]: vb doesn't seem to have existing tests on enum parameter values so I am also adding an enum and a flags enum test.

File: src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs (hunk 3 above)
Comment (yufeih) [reply src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs]: Done.

File: src/Compilers/VisualBasic/Test/Symbol/SymbolDisplay/SymbolDisplayTests.vb [hunk 4]
```diff
@@ -2896,6 +2896,283 @@ End Class
...
+                SymbolDisplayPartKind.EnumMemberName,
+                SymbolDisplayPartKind.Punctuation
+                })
+        End Sub
+
+        <Fact()>
+        Public Sub TestOptionalParameterValue_FlagsEnum()
+            Dim text =
+<compilation>
+    <file name="a.vb">
```
Comment (cston) [inline src/Compilers/VisualBasic/Test/Symbol/SymbolDisplay/SymbolDisplayTests.vb:2979]: ><file name="a.vb"> [](http://example.com/codeflow?start=4&length=18)

Consider using `CDATA` to avoid needing to escape `<` and `>` in the tests:
```
<compilation>
    <file name="a.vb"><![CDATA[
<System.FlagsAttribute>
...
    ]]></file>
</compilation>
```

**Review by cston — APPROVED** [review]

**Comment by cston** [comment]
It looks like unit test `IOperationTests_IArgument.NullableEnumDefaultArgument_NonZeroValue()` is failing currently. The expected output may need to be updated.

File: src/Compilers/VisualBasic/Test/Symbol/SymbolDisplay/SymbolDisplayTests.vb (hunk 4 above)
Comment (yufeih) [reply src/Compilers/VisualBasic/Test/Symbol/SymbolDisplay/SymbolDisplayTests.vb:2979]: The other VB tests seems to be using `&lt; &gt;` for attributes

**Review by cston — APPROVED** [review]

**Comment by cston** [comment]
@dotnet/roslyn-compiler for a second review.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 3)

**Comment by jcouv** [comment]
Thanks for the contribution @yufeih!
