### PR TITLE
Use inherited properties for records

### LINKED ISSUE #44616: Records implementation produces properties that spec says it should not.
Regarding the spec sentence

> If no concrete (i.e. non-abstract) property with a get accessor and with this name and type is explicitly declared or inherited, it is produced by the compiler as follows

There are a number of tests (like `Inheritance_01`) added in https://github.com/dotnet/roslyn/pull/44595 that demonstrate that the compiler produces properties that the spec says it should not.

### LINKED ISSUE #44692: System.ArgumentException adding record with duplicate property
```C#
data class C(object Q)
{
    public object P { get; }
    public object P { get; }
}
```
System.ArgumentException: An item with the same key has already been added. Key: C.P
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.AddSynthesizedRecordMembersIfNecessary(MembersAndInitializersBuilder builder, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:line 2952
...
See [example](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRIMYHsEBNkA0MIAlgDYA+usUABAAIBMtAwgBRbABWEGMtARQCUAWABQAb3G0ZDAMy1OPPrQAKtCbQDmEGAG5aAX2mz6Cpb37rNO/UfGGgA==)

### PR DESCRIPTION
**Pull request by cston**
Spec: https://github.com/dotnet/csharplang/blob/master/proposals/records.md

Fixes #44616
Fixes #44692

### CODE REVIEW

**Comment by cston** [comment]
@dotnet/roslyn-compiler please review.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 1]
```diff
@@ -2035,6 +2145,633 @@ interface IB
...
+    public object P2 { get; }
+    public object P3 { get; }
+    public object P4 { get; }
+}
+class B : A
+{
+    public new int P1 { get; }
+    public new int P2 { get; }
+}
+data class C(object P1, int P2, object P3, int P4) : B
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:2225]: >object P3 [](start = 32, length = 9)

The spec has changed again. See [https://github.com/dotnet/csharplang/pull/3527](https://github.com/dotnet/csharplang/pull/3527) ... Now it appears P3 *should* be generated.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 2]
```diff
@@ -2510,20 +2564,69 @@ public void Inheritance_07()
...
+}
+abstract class B : A
+{
+    public override abstract int Y { get; }
+}
+data class C(int X, int Y, int Z) : B
+{
+}";
+            var comp = CreateCompilation(source);
+            comp.VerifyDiagnostics(
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:2601]: >VerifyDiagnostics [](start = 17, length = 17)

These diagnostics look incorrect. According to the latest spec at [https://github.com/dotnet/csharplang/pull/3527](https://github.com/dotnet/csharplang/pull/3527) 'Each "matching" inherited abstract accessor is overridden'

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 3]
```diff
@@ -2425,17 +2501,7 @@ public void Inheritance_04()
...
-                "System.Object B.P1 { get; init; }",
-                "System.Object B.P2 { get; init; }",
-                "System.Object B.P3 { get; init; }",
-                "System.Object B.P4 { get; init; }",
-                "System.Object B.P5 { get; init; }",
-                "System.Object B.P6 { get; init; }",
-                "System.Object B.P7 { get; init; }",
-            };
-            AssertEx.Equal(expectedMembers, actualMembers);
+            AssertEx.Equal(new string[0], actualMembers);
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:2504]: >string [](start = 31, length = 6)

`P5` should be synthesized per  [https://github.com/dotnet/csharplang/pull/3527](https://github.com/dotnet/csharplang/pull/3527)

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 4]
```diff
@@ -2510,20 +2564,69 @@ public void Inheritance_07()
...
 {
 }";
             var comp = CreateCompilation(source);
             comp.VerifyDiagnostics(
-                // (6,12): error CS0534: 'B' does not implement inherited abstract member 'A.X.get'
-                // data class B(int X, int Y) : A
-                Diagnostic(ErrorCode.ERR_UnimplementedAbstractMethod, "B").WithArguments("B", "A.X.get").WithLocation(6, 12));
+                // (9,12): error CS0534: 'B2' does not implement inherited abstract member 'A.X.get'
+                // data class B2(int X, int Y) : A
+                Diagnostic(ErrorCode.ERR_UnimplementedAbstractMethod, "B2").WithArguments("B2", "A.X.get").WithLocation(9, 12));
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:2577]: >ERR_UnimplementedAbstractMethod [](start = 37, length = 31)

Error is incorrect per [https://github.com/dotnet/csharplang/pull/3527](https://github.com/dotnet/csharplang/pull/3527)

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 5]
```diff
@@ -2593,6 +2696,701 @@ interface IB
...
+    public object X { get; }
+    public object Y { get; }
+}
+data class B(object X, object Y) : A
+{
+    public object X { get; }
+    public object Y { get; }
+}";
+            var comp = CreateCompilation(source);
+            comp.VerifyDiagnostics(
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:2714]: >VerifyDiagnostics [](start = 17, length = 17)

Per [https://github.com/dotnet/csharplang/pull/3527](https://github.com/dotnet/csharplang/pull/3527): 'Members are synthesized unless an accessible concrete (non-abstract) member with a "matching" signature is 
either inherited or declared in the record body.'

Since such a member is inherited, it should not be synthesized.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 6]
```diff
@@ -2510,20 +2564,69 @@ public void Inheritance_07()
...
+        public void Inheritance_09()
+        {
+            var source =
+@"abstract data class C(int X, int Y)
+{
+    public abstract int X { get; }
+    public virtual int Y { get; }
+}";
+            var comp = CreateCompilation(source);
+            comp.VerifyDiagnostics();
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:2623]: >VerifyDiagnostics [](start = 17, length = 17)

This should be an error because `C` contains both a declared property `X` and a synthesized one, because, from [https://github.com/dotnet/csharplang/pull/3527](https://github.com/dotnet/csharplang/pull/3527)

'Members are synthesized unless an accessible concrete (non-abstract) member with a "matching" signature is either inherited or declared in the record body.'

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs (hunk 3 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:2504]: `P5` is `virtual` in the base class rather than `abstract`.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs (hunk 4 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:2577]: Yes, we're not synthesizing overrides for `abstract` properties currently. That is tracked by https://github.com/dotnet/roslyn/issues/44785.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs (hunk 1 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:2776]: The spec currently allows the base member to differ by signature (or member kind) if the record property would hide the base member:
> Two members are considered matching if they have the same signature or would be considered "hiding" in an inheritance scenario.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 7]
```diff
@@ -2510,20 +2564,69 @@ public void Inheritance_07()
...
         }
 
         [Fact]
         public void Inheritance_08()
         {
             var source =
+@"abstract class A
+{
+    public abstract int X { get; }
+    public virtual int Y { get; }
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:2590]: Please add a test like this (`X`) but in which the type of the property in `A` and in `C` are incompatible. There should be an error that the override has the wrong type.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs (hunk 2 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:2601]: [https://github.com/dotnet/roslyn/issues/44785](https://github.com/dotnet/roslyn/issues/44785)

---
In reply to: [434217176](https://github.com/dotnet/roslyn/pull/44705#discussion_r434217176) [](ancestors = 434217176)

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs (hunk 7 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:2590]: Or do it when handling [https://github.com/dotnet/roslyn/issues/44785](https://github.com/dotnet/roslyn/issues/44785)

---
In reply to: [434231286](https://github.com/dotnet/roslyn/pull/44705#discussion_r434231286) [](ancestors = 434231286)

Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:2590]: Added https://github.com/dotnet/roslyn/issues/44785#issuecomment-637872297

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs [hunk 8]
```diff
@@ -3016,12 +3019,37 @@ void addProperties(ImmutableArray<ParameterSymbol> recordParameters)
                 }
             }
 
+            static bool hidesInheritedMember(Symbol symbol, NamedTypeSymbol type)
+            {
+                while ((type = type.BaseTypeNoUseSiteDiagnostics) is object)
+                {
+                    OverriddenOrHiddenMembersHelpers.FindOverriddenOrHiddenMembersInType(
+                        symbol,
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:3027]: I was suggesting something different in this check, I think.

What we currently do is lookup in the dictionary for signature conflicts. My idea was that we would instead look for conflicts as defined by the same equality metrics as hiding.

So we wouldn't apply this check just for actual inherited members, but all members -- including the ones declared in source.

Effectively, the rule for a "matching" member is hiding, regardless of where that member came from. The difference would be that some synthesized members should not be synthesized if an inherited member exists (like the syntheiszed properties), while some would not be synthesized only is already declared (like the equality members).

Comment (cston) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:3027]: Thanks. I'll try the hiding comparison for members declared in the record class in the next PR.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs (hunk 6 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:2625]: I assume you will work with @agocke to resolve the conflict (I expect by modifying the spec).

---
In reply to: [434224682](https://github.com/dotnet/roslyn/pull/44705#discussion_r434224682) [](ancestors = 434224682)

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs [hunk 9]
```diff
@@ -3016,12 +3019,37 @@ void addProperties(ImmutableArray<ParameterSymbol> recordParameters)
...
+                return false;
+            }
+
             void addObjectEquals(MethodSymbol thisEquals)
             {
                 var objEquals = new SynthesizedRecordObjEquals(this, thisEquals);
                 if (!memberSignatures.ContainsKey(objEquals))
                 {
-                    // PROTOTYPE: Don't add if the overridden method is sealed
+                    // https://github.com/dotnet/roslyn/issues/44617: Don't add if the overridden method is sealed
```
[the remark this answers is not in the document]
Comment (cston) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:3052]: Thanks. I'll address with the `Equals` changes in a separate PR.
