### PR TITLE
fixing error formatting for generic attribute missing errors

### LINKED ISSUE #69700: Incorrect error formatting for generic attribute missing errors
**Version Used**: 5fcefbef

**Steps to Reproduce**:

```cs
[SomeAttribute<int>] // error CS0246: The type or namespace name 'SomeAttribute<>Attribute' could not be found (are you missing a using directive or an assembly reference?)
void Foo() {}
```
[Sharplab](https://sharplab.io/#v2:C4LghgzsA0AmIGoA+BtAygewLYFMCCwwATgJYBGArsDgDwkB2wAfALoCwAUAAIAsABADEMGABQBKPgG8AvkA)

**Diagnostic Id**: CS0246

**Expected Behavior**:

`The type or namespace name 'SomeAttributeAttribute<>' could not be found (are you missing a using directive or an assembly reference?)`

**Actual Behavior**:

`The type or namespace name 'SomeAttribute<>Attribute' could not be found (are you missing a using directive or an assembly reference?)`

### PR DESCRIPTION
**Pull request by kinkeadian25**
Hi, added a check on arity in the construction of the message.

Hopefully as I get more and more comfortable, I can have everything necessary added each PR. Stoked to be back working on Roslyn! Please let me know any changes I need to make to this.

Closes #69700

### CODE REVIEW

**Comment by kinkeadian25** [comment]
> @kinkeadian25 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@dotnet-policy-service agree

**Comment by kinkeadian25** [comment]
@dotnet-policy-service agree

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs [hunk 1]
```diff
@@ -3470,6 +3470,26 @@ public void CS0246ERR_SingleTypeNameNotFound06()
                 );
         }
 
+        [WorkItem(69700, "https://github.com/dotnet/roslyn/issues/69700")]
+        [Fact]
```
Comment (DoctorKrolic) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs:3474]:
```suggestion
        [Fact, WorkItem(69700, "https://github.com/dotnet/roslyn/issues/69700")]
```

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs [hunk 2]
```diff
@@ -3470,6 +3470,25 @@ public void CS0246ERR_SingleTypeNameNotFound06()
...
+@"class C
+{
+    [SomeAttribute<int>] // Error should occur here
+    static void Foo()
+    {
+    }
+}
+";
+            CreateCompilation(text).
+                VerifyDiagnostics(
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs:3486]: nit: if you run the test with empty (or incorrect) expected diagnostics, the test failure output will give you a block of text that can be copy&pasted. It'll include a human-readable comment, like in the test above (line 3467). That's slightly nicer, as it shows where the error occurs and what the error message says.

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs [hunk 3]
```diff
@@ -2512,8 +2512,10 @@ private CSDiagnosticInfo NotFound(SyntaxNode where, string simpleName, int arity
             // for attributes, suggest both, but not for verbatim name
             if (options.IsAttributeTypeLookup() && !options.IsVerbatimNameAttributeTypeLookup())
             {
-                // just recurse one level, so cheat and OR verbatim name option :)
-                NotFound(where, simpleName, arity, whereText + "Attribute", diagnostics, aliasOpt, qualifierOpt, options | LookupOptions.VerbatimNameAttributeTypeOnly);
+                // Check for generic attribute
+                string expectedDiagnostic = arity > 0 ? $"{simpleName}Attribute<>" : $"{simpleName}Attribute";
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs:2516]: >expectedDiagnostic [](http://example.com/codeflow?start=23&length=18)

The name of this local seems strange. Consider `attributeName` or some such.

File: src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs [hunk 4]
```diff
@@ -2512,8 +2512,10 @@ private CSDiagnosticInfo NotFound(SyntaxNode where, string simpleName, int arity
             // for attributes, suggest both, but not for verbatim name
             if (options.IsAttributeTypeLookup() && !options.IsVerbatimNameAttributeTypeLookup())
             {
-                // just recurse one level, so cheat and OR verbatim name option :)
-                NotFound(where, simpleName, arity, whereText + "Attribute", diagnostics, aliasOpt, qualifierOpt, options | LookupOptions.VerbatimNameAttributeTypeOnly);
+                // Check for generic attribute
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Symbols.cs:2515]: nit: the comment doesn't provide much benefit in terms of clarifying the purpose or intent. It could be removed.

**Comment by jcouv** [comment]
Thanks for looking at this recently opened issue so quickly :-)

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 3)

**Comment by kinkeadian25** [comment]
> Thanks for looking at this recently opened issue so quickly :-)

Thanks for the quick review, I definitely agree with all of it. Sorry it took a bit; I was at work!

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs [hunk 5]
```diff
@@ -3470,6 +3470,29 @@ public void CS0246ERR_SingleTypeNameNotFound06()
...
         }
 
+        [Fact, WorkItem(69700, "https://github.com/dotnet/roslyn/issues/69700")]
+        public void CS0246ERR_SingleTypeNameNotFound07()
+        {
+            var text =
+@"class C
+{
+    [SomeAttribute<int>]
+    static void Foo()
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs:3480]: >Foo [](http://example.com/codeflow?start=16&length=3)

Sorry, I missed that in first go. "Foo" is disallowed in the codebase because it triggers some internal word check rules.

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs [hunk 6]
```diff
@@ -3470,6 +3470,29 @@ public void CS0246ERR_SingleTypeNameNotFound06()
                 );
         }
 
+        [Fact, WorkItem(69700, "https://github.com/dotnet/roslyn/issues/69700")]
+        public void CS0246ERR_SingleTypeNameNotFound07()
+        {
+            var text =
+@"class C
+{
+    [SomeAttribute<int>]
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs:3479]: Consider also testing with `[Some<int>]`

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 5)

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 5)

**Comment by jcouv** [comment]
@dotnet/roslyn-compiler for another review. Thanks

**Review by 333fred — APPROVED** [review]

**Comment by 333fred** [comment]
Thanks @kinkeadian25!

**Comment by kinkeadian25** [comment]
> Thanks @kinkeadian25!

Thank you for posting the issue @333fred!! Cool to get a compiler issue done!
