### PR TITLE
Fix new rename showing overloads when not applicable

### LINKED ISSUE #62267: New rename UI shouldn't show "Include overload(s)" for locals/params/properties/fields
**Version Used**: 17.3.0 Preview 3.0 [32629.347.main]

**Steps to Reproduce**:

```c#
class C
{
    public string _field;
    public string Property { get; }
    public C(string parameter)
    {
        string local = "";
    }
}
```

**Expected Behavior**:

The new UI doesn't show "Include overload(s)" for `_field`, `Property`, `parameter` or `local`.

In the case of a method rename, ideally the dialog would only include this option when an actual overload existed.

**Actual Behavior**:

The new UI shows "Include overload(s)" for `_field`, `Property`, `parameter` or `local`.

image

### PR DESCRIPTION
**Pull request by ryzngard**
Fixes #62267

### CODE REVIEW

**Review by JoeRobich — APPROVED** [review]

File: src/EditorFeatures/Test2/Rename/RenameViewModelTests.vb [hunk 1]
```diff
@@ -613,14 +613,30 @@ class D : B
                     Assert.Equal(severity, model.Severity)
                 End Using
 
+                Using flyout = New RenameFlyout(
+                    New RenameFlyoutViewModel(DirectCast(sessionInfo.Session, InlineRenameSession), registerOleComponent:=False),
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Test2/Rename/RenameViewModelTests.vb:617]: doc why false.

**Review by CyrusNajmabadi — APPROVED** [review]
