### PR TITLE
Guard the 'CustomSeverityConfigurable' tag with AnalysisLevel 9.0

### LINKED ISSUE #72094: It seems dotnet_diagnostic.IDE0058.severity in .editorconfig started to be ignored with today's VS update (13 feb 2024)
**Version Used**: 

VS 2022 version 17.9.0. (MSBuild version seems to be 17.9.4+90725d08d for .NET)

**Steps to Reproduce**:

1. Add `dotnet_diagnostic.IDE0058.severity = none` to .editorconfig
2. Build solution
3. See how "Expression value is never used" issues are reported

Today I updated VS 2022 to version 17.9.0. It seems that the configuration for rule IDE0058 is being ignored. Not only the issues are reported even though I set the severity as `none` but even if I set it as `error` the code compiles just fine. We have SonarQube running for our builds and now the PR is full of comments saying "Bug (info): Expression value is never used (external_roslyn:IDE0058)". 

**Diagnostic Id**:

IDE0058

**Expected Behavior**:

Ignore rule just like it was being done in the previous versions.

**Actual Behavior**:

Issues with code IDE0058 are being reported with severity = info.

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #72094

Recently, as part of implementing support for #52991, we started respecting `option_name = option_value:severity` in build. As part of this change, if user has conflicting severity configurations from `option_name = option_value:severity` and `dotnet_diagnostic.IDExxxx.severity`, the former was given preference. We knew that this would likely break some customers, hence added functionality to guard this feature by enabling it only when AnalysisLevel was >= 9.0. However, that guard was only implemented for command line build path. This meant the feature was still being enabled by default in the IDE live analysis, which was unintentional. We now ensure that we respect the AnalysisLevel value even for this path and filter out CustomSeverityConfigurable custom tag for AnalysisLevel less than 9.

**NOTE:** Even though this PR touches almost all the IDE analyzer files, the fix is only limited to one change, rest all are cascaded changes. I'll add a comment on the PR to point out this fix.

**SDK bug**
As part of this change, I also identified a bug in the SDK targets: https://github.com/dotnet/sdk/blob/3075c3bc8d8aa4e0ffcf2945459ef2ee383e3ae0/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets#L117-L120 We shouldn't be conditioning the inclusion of CodeStyle targets file on `EnforceCodeStyleInBuild` as we want the target to execute even for live analysis for IDE analyzers shipping inside VS, not only when enabled on build. Fix to remove that condition is required to ensure we thread in AnalysisLevel property value to the analyzers for live analysis when `EnforceCodeStyleInBuild = false`. I have created https://github.com/dotnet/sdk/pull/38968 for fixing the SDK issue.

### CODE REVIEW

File: src/Analyzers/CSharp/Tests/UseObjectInitializer/UseObjectInitializerTests.cs [hunk 1]
```diff
@@ -1041,5 +1041,89 @@ class MyClass
                 }
                 """, OutputKind.ConsoleApplication);
         }
+
+        [Theory]
+        [InlineData(8.0)]
+        [InlineData(9.0)]
+        [WorkItem("https://github.com/dotnet/roslyn/issues/72094")]
+        public async Task TestWithConflictingSeverityConfigurationEntries(double analysisLevel)
```
Comment (mavasani) [inline src/Analyzers/CSharp/Tests/UseObjectInitializer/UseObjectInitializerTests.cs:1049]: This is the unit test that mimics the behavior pointed out in #72094. Verified that this test fails for analysisLevel `8.0` prior to the product change

File: src/Analyzers/Core/Analyzers/Helpers/DiagnosticHelper.cs [hunk 2]
```diff
@@ -253,11 +264,24 @@ static string EncodeIndices(IEnumerable<int> indices, int additionalLocationsLen
...
                 location,
                 additionalLocations,
-                GetEffectiveCustomTags(descriptor, notificationOption),
+                GetEffectiveCustomTags(descriptor, notificationOption, analyzerOptions),
                 properties);
 
-            static IEnumerable<string> GetEffectiveCustomTags(DiagnosticDescriptor descriptor, NotificationOption2 notificationOption)
+            static IEnumerable<string> GetEffectiveCustomTags(DiagnosticDescriptor descriptor, NotificationOption2 notificationOption, AnalyzerOptions analyzerOptions)
             {
+                // 'CustomSeverityConfigurable' is only enabled when AnalysisLevel >= 9.
```
Comment (mavasani) [inline src/Analyzers/Core/Analyzers/Helpers/DiagnosticHelper.cs:272]: This is the only change needed for this fix. We now ensure that if AnalysisLevel is lesser than 9.0, we filter out the `CustomSeverityConfigurable` tag from the reported code style diagnostics. This tag enables the feature support added for #52991

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/AnalyzerConfigOptionsExtensions.cs [hunk 3]
```diff
@@ -55,5 +52,15 @@ public static bool TryGetEditorConfigOption<T>(this AnalyzerConfigOptions analyz
             value = default!;
             return false;
         }
+
+        public static bool IsAnalysisLevelGreaterThanOrEquals(this AnalyzerConfigOptions analyzerConfigOptions, int minAnalysisLevel)
```
Comment (mavasani) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/AnalyzerConfigOptionsExtensions.cs:56]: This is an existing method that just has been refactored to an internal extension method so it can be invoked from DiagnosticHelper type as well. No functionality changes here.

**Review by sharwell — APPROVED** [review]

**Review by arkalyanms — APPROVED** [review]

**Comment by cremor** [comment]
Which VS version will include this fix?

**Comment by CyrusNajmabadi** [comment]
@cremor When this is merged into VS a bot will update this PR with that information.

**Comment by cremor** [comment]
This PR is assigend to the milestone "17.10 P2". But I can still reproduce the bug in VS 17.10.1
Did the fix not get merged to the correct VS branch or is there still something else broken?

**Comment by sharwell** [comment]
@cremor Can you file a new issue for the behavior you are experiencing, including a sample project?

**Comment by cremor** [comment]
@sharwell Done: #73858
