### PR TITLE
Fix crash if client completes the event queue before the compiler is finished with it.

### LINKED ISSUE #8178: Crash in diagnostics analyzer
Was editing in roslyn when i got this:

```
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.InvalidOperationException: Cannot call Enqueue when the queue is already completed.
   at Microsoft.CodeAnalysis.Diagnostics.AsyncQueue`1.Enqueue(TElement value)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.SymbolDeclaredEvent(Symbol symbol)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamespaceSymbol.GetNameToMembersMap()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamespaceSymbol.GetMembers(String name)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDeclaredMember(NamespaceOrTypeSymbol container, TextSpan declarationSpan, String name)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDeclaredNamedType(CSharpSyntaxNode declarationSyntax, String name)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDeclaredType(BaseTypeDeclarationSyntax declarationSyntax)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDeclaredSymbol(BaseTypeDeclarationSyntax declarationSyntax, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetDeclaredSymbolCore(SyntaxNode declaration, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DeclarationComputer.GetDeclaredSymbol(SemanticModel model, SyntaxNode node, Boolean getSymbol, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DeclarationComputer.GetDeclarationInfo(SemanticModel model, SyntaxNode node, Boolean getSymbol, IEnumerable`1 executableCodeBlocks, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DeclarationComputer.GetDeclarationInfo(SemanticModel model, SyntaxNode node, Boolean getSymbol, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpDeclarationComputer.ComputeDeclarations(SemanticModel model, SyntaxNode node, Func`3 shouldSkip, Boolean getSymbol, List`1 builder, Nullable`1 levelsToCompute, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpDeclarationComputer.ComputeDeclarations(SemanticModel model, SyntaxNode node, Func`3 shouldSkip, Boolean getSymbol, List`1 builder, Nullable`1 levelsToCompute, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpDeclarationComputer.ComputeDeclarationsInNode(SemanticModel model, SyntaxNode node, Boolean getSymbol, List`1 builder, CancellationToken cancellationToken, Nullable`1 levelsToCompute)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.ComputeDeclarationsInNode(SyntaxNode node, Boolean getSymbol, List`1 builder, CancellationToken cancellationToken, Nullable`1 levelsToCompute)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.ComputeDeclarationAnalysisData(ISymbol symbol, SyntaxReference declaration, SemanticModel semanticModel, Boolean shouldExecuteSyntaxNodeActions, AnalysisScope analysisScope, Func`1 allocateData, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.<>c__DisplayClass37_0.<ExecuteDeclaringReferenceActions>b__0(Func`1 allocateData)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.CompilationData.GetOrComputeDeclarationAnalysisData(SyntaxReference declaration, Func`2 computeDeclarationAnalysisData, Boolean cacheAnalysisData)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.ExecuteDeclaringReferenceActions(SyntaxReference decl, Int32 declarationIndex, SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, AnalysisState analysisStateOpt, Boolean shouldExecuteSyntaxNodeActions, Boolean shouldExecuteOperationActions, Boolean shouldExecuteCodeBlockActions, Boolean shouldExecuteOperationBlockActions, Boolean isInGeneratedCode, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1.ExecuteDeclaringReferenceActions(SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, AnalysisState analysisStateOpt, Boolean isGeneratedCodeSymbol, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessSymbolDeclared(SymbolDeclaredCompilationEvent symbolEvent, AnalysisScope analysisScope, AnalysisState analysisStateOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessEventCore(CompilationEvent e, AnalysisScope analysisScope, AnalysisState analysisStateOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<ProcessCompilationEventsCoreAsync>d__64.MoveNext()
Stack:
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.CodeAnalysis.FatalError.Report(System.Exception, System.Action`1<System.Exception>)
   at Microsoft.CodeAnalysis.FatalError.ReportUnlessCanceled(System.Exception)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<ProcessCompilationEventsCoreAsync>d__64.MoveNext()
   at Microsoft.CodeAnalysis.Diagnostics.AsyncQueue`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Enqueue(System.__Canon)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.SymbolDeclaredEvent(Microsoft.CodeAnalysis.CSharp.Symbol)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamespaceSymbol.GetNameToMembersMap()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamespaceSymbol.GetMembers(System.String)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDeclaredMember(Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceOrTypeSymbol, Microsoft.CodeAnalysis.Text.TextSpan, System.String)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDeclaredNamedType(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode, System.String)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDeclaredType(Microsoft.CodeAnalysis.CSharp.Syntax.BaseTypeDeclarationSyntax)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDeclaredSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.BaseTypeDeclarationSyntax, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetDeclaredSymbolCore(Microsoft.CodeAnalysis.SyntaxNode, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.DeclarationComputer.GetDeclaredSymbol(Microsoft.CodeAnalysis.SemanticModel, Microsoft.CodeAnalysis.SyntaxNode, Boolean, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.DeclarationComputer.GetDeclarationInfo(Microsoft.CodeAnalysis.SemanticModel, Microsoft.CodeAnalysis.SyntaxNode, Boolean, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.SyntaxNode>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.DeclarationComputer.GetDeclarationInfo(Microsoft.CodeAnalysis.SemanticModel, Microsoft.CodeAnalysis.SyntaxNode, Boolean, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpDeclarationComputer.ComputeDeclarations(Microsoft.CodeAnalysis.SemanticModel, Microsoft.CodeAnalysis.SyntaxNode, System.Func`3<Microsoft.CodeAnalysis.SyntaxNode,System.Nullable`1<Int32>,Boolean>, Boolean, System.Collections.Generic.List`1<Microsoft.CodeAnalysis.DeclarationInfo>, System.Nullable`1<Int32>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpDeclarationComputer.ComputeDeclarations(Microsoft.CodeAnalysis.SemanticModel, Microsoft.CodeAnalysis.SyntaxNode, System.Func`3<Microsoft.CodeAnalysis.SyntaxNode,System.Nullable`1<Int32>,Boolean>, Boolean, System.Collections.Generic.List`1<Microsoft.CodeAnalysis.DeclarationInfo>, System.Nullable`1<Int32>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpDeclarationComputer.ComputeDeclarationsInNode(Microsoft.CodeAnalysis.SemanticModel, Microsoft.CodeAnalysis.SyntaxNode, Boolean, System.Collections.Generic.List`1<Microsoft.CodeAnalysis.DeclarationInfo>, System.Threading.CancellationToken, System.Nullable`1<Int32>)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.ComputeDeclarationsInNode(Microsoft.CodeAnalysis.SyntaxNode, Boolean, System.Collections.Generic.List`1<Microsoft.CodeAnalysis.DeclarationInfo>, System.Threading.CancellationToken, System.Nullable`1<Int32>)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1[[Microsoft.CodeAnalysis.CSharp.SyntaxKind, Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ComputeDeclarationAnalysisData(Microsoft.CodeAnalysis.ISymbol, Microsoft.CodeAnalysis.SyntaxReference, Microsoft.CodeAnalysis.SemanticModel, Boolean, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope, System.Func`1<DeclarationAnalysisData>, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1+<>c__DisplayClass37_0[[Microsoft.CodeAnalysis.CSharp.SyntaxKind, Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].<ExecuteDeclaringReferenceActions>b__0(System.Func`1<DeclarationAnalysisData>)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+CompilationData.GetOrComputeDeclarationAnalysisData(Microsoft.CodeAnalysis.SyntaxReference, System.Func`2<System.Func`1<DeclarationAnalysisData>,DeclarationAnalysisData>, Boolean)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1[[Microsoft.CodeAnalysis.CSharp.SyntaxKind, Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ExecuteDeclaringReferenceActions(Microsoft.CodeAnalysis.SyntaxReference, Int32, Microsoft.CodeAnalysis.Diagnostics.SymbolDeclaredCompilationEvent, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState, Boolean, Boolean, Boolean, Boolean, Boolean, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver`1[[Microsoft.CodeAnalysis.CSharp.SyntaxKind, Microsoft.CodeAnalysis.CSharp, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]].ExecuteDeclaringReferenceActions(Microsoft.CodeAnalysis.Diagnostics.SymbolDeclaredCompilationEvent, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState, Boolean, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessSymbolDeclared(Microsoft.CodeAnalysis.Diagnostics.SymbolDeclaredCompilationEvent, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessEventCore(Microsoft.CodeAnalysis.Diagnostics.CompilationEvent, Microsoft.CodeAnalysis.Diagnostics.AnalysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<ProcessCompilationEventsCoreAsync>d__64.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<ProcessCompilationEventsCoreAsync>d__64, Microsoft.CodeAnalysis, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<ProcessCompilationEventsCoreAsync>d__64 ByRef)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessCompilationEventsCoreAsync(Microsoft.CodeAnalysis.Diagnostics.AnalysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState, Boolean, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<>c__DisplayClass63_0+<<ProcessCompilationEventsAsync>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<>c__DisplayClass63_0+<<ProcessCompilationEventsAsync>b__0>d, Microsoft.CodeAnalysis, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<<ProcessCompilationEventsAsync>b__0>d ByRef)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<>c__DisplayClass63_0.<ProcessCompilationEventsAsync>b__0()
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #8178

@dotnet/roslyn-compiler Please review

### CODE REVIEW

**Comment by AlekseyTs** [comment]
+1 For @jaredpar 's suggestion.

**Comment by natidea** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please
@dotnet-bot retest prtest/win/dbg/unit64 please
// Retest reason: Failure tracked by #8807 Tests Disabled by #8844

**Comment by gafter** [comment]
@jaredpar I am reluctant to add new APIs during the stabilization period.

**Comment by jaredpar** [comment]
@gafter i'm reluctant to ship the compiler in a state that is less able to diagnose failure correctly.

**Comment by gafter** [comment]
@dotnet/roslyn-compiler All comments addressed. Please re-review.

File: src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs [hunk 1]
```diff
@@ -1715,13 +1715,14 @@ private void CompleteTree(SyntaxTree tree)
...
-                EventQueue.Enqueue(new CompilationUnitCompletedEvent(this, tree));
+                EventQueue.TryEnqueue(new CompilationUnitCompletedEvent(this, tree));
             }
 
             if (completedCompilation)
             {
-                EventQueue.Enqueue(new CompilationCompletedEvent(this));
-                EventQueue.Complete(); // signal the end of compilation events
+                EventQueue.TryEnqueue(new CompilationCompletedEvent(this));
+                EventQueue.PromiseNotToEnqueue(); // Trigger an assertion if any further events are queued
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs]: `Throw an exception` rather than `Trigger an assertion`.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AsyncQueue.cs [hunk 2]
```diff
@@ -140,6 +146,11 @@ public void Complete()
             }
         }
 
+        public void PromiseNotToEnqueue()
```
Comment (cston) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AsyncQueue.cs]: Could `TryComplete` and `PromiseNotToEnqueue` be replaced with `Complete` and `Cancel` where the `Compiler` calls `Complete` and the `AnalyzerDriver` calls `Cancel`?

**Comment by natidea** [comment]
Infrastructure note: prtest/mac/dbg/unit32 is backed up but should complete in a few hours

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AsyncQueue.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AsyncQueue.cs]: That is possible, but it would require a more invasive reworking of the API, and I'd prefer not to do that on the stabilization branch.

File: src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs]: Reordered and reworded.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AsyncQueue.cs (hunk 2 above)
Comment (cston) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AsyncQueue.cs]: The suggestion was in support of fixing the bug, although I agree that `Complete` and `Cancel` would involve more reworking.

`Complete` makes explicit which caller should be completing: `CSharpCompilation.CompleteTree`. The cases where `TryComplete` is used today are really attempts to `Cancel` instead. Perhaps `TryComplete` should be renamed to `Cancel`.

Note there are indirect uses of `TryComplete` through calls to `DiagnosticQueue.TryComplete` as well. It feels like those should explicit there too. All but one of those calls should be called `Cancel` and the other should be `Complete`.

Comment (cston) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AsyncQueue.cs]: With `Complete` and `Cancel`, `PromiseNotToEnqueue` is unnecessary since `_disallowEnqueue` would be set by `Complete`.

Comment (gafter) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AsyncQueue.cs]: I would be happy to see this internal API reviewed and possible reorganized or overhauled, though we should be careful to separate out those parts that would make sense for a platform API. In any case, I want to keep the bug fix for the stabilization branch as simple and obviously correct as possible.

File: src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb [hunk 3]
```diff
@@ -1647,17 +1647,18 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
-                EventQueue.Complete() ' signal the End Of compilation events
+                EventQueue.TryEnqueue(New CompilationCompletedEvent(Me))
+                EventQueue.PromiseNotToEnqueue()
+                EventQueue.TryComplete() ' signal the End Of compilation events
             End If
         End Sub
 
         Friend Function ShouldAddEvent(symbol As Symbol) As Boolean
-            If EventQueue Is Nothing Then
+            If EventQueue Is Nothing OrElse EventQueue.IsCompleted Then
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb]: It is not obvious why making this change is the right thing to do.

Comment (cston) [inline src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb]: +1. And consider removing this method and changing the callers to match the C# approach.

Comment (gafter) [inline src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb]: I have no place to move the VB-specific assertions to if I were to remove this method.

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb]: Why is it correct to not throw in the case when we promised to not try to en-queue any more?

Comment (gafter) [inline src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb]: EventQueue.IsCompleted isn't a promise not the enqueue any further; that can occur when the queue is cancelled by the client. Promising not to enqueue any further is a separate API.

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb]: Why are we not checking if we promised to not try to en-queue any more?

Comment (gafter) [inline src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb]: The structure of the compiler is such that it produces all events before promising not to enqueue any longer. Once we promise not to enqueue any longer, a flag is set inside the async queue and the queue throws an exception if any event is queued. In other words, we do check, but at a different layer. Those changes are all included in this PR.

**Comment by gafter** [comment]
@dotnet-bot retest prtest/mac/dbg/unit32 please

File: src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb (hunk 3 above)
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb]: But it looks like the added condition will cancel an attempt to en-queue and we will not take an advantage of the check in a different layer. Why is this new condition necessary?

Comment (gafter) [inline src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb]: The two conditions "promised not to enqueue" and "cancelled/completed" are separate and have nothing to do with each other.

"promise not to enqueue" occurs when the compiler is in a state where all events that could possibly be produced should have already been produced. It is checked in the queue, and it causes an exception to be raised if there is an attempt to enqueue an event.

Cancelled, or Completed, can occur because the client says they are not interested in any further events. In this case we just stop producing events due to the client's declaration. That is what this new check is for.

Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb]: I do not see similar change made on C# side. Why?

Comment (gafter) [inline src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb]: I'll revert this change.

**Comment by cston** [comment]
LGTM

**Comment by gafter** [comment]
@jaredpar @AlekseyTs Need a second review, please.

**Comment by AlekseyTs** [comment]
LGTM

**Comment by jaredpar** [comment]
I'll submit this for ask mode today.

**Comment by gafter** [comment]
@jaredpar Has this gone through ask mode? Or are we waiting for the test queueueues to be fixed?

**Comment by gafter** [comment]
@jaredpar Are we going to have this IDE crash fixed in Update 2?

**Comment by jaredpar** [comment]
Let's meet tomorrow and discuss this.  I want to better understand the queue model here.

**Comment by jaredpar** [comment]
Looking at this change it seems like we've introduced a new crash path into the code base.  Here is the behavior before this change:

|Operation|Queue State|Outcome|
|---|---|---|---|
|TryEnqueue|Active|Queues|
|TryEnqueue|Complete|Nop|
|TryEnqueue|Cancel|Nop|
|Enqueue|Active|Queues|
|Enqueue|Complete|Throw|
|Enqueue|Cancel|Throw|

This PR is meant to address a portion of `Enqueue` calls which can occur in the `Cancel` state.  Those cases which can correctly occur during cancellation should become tolerant of cancellation.  Either by moving to `TryEnqueue` or by introducing a new method which has the following behavior:

|Operation|Queue State|Outcome|
|---|---|---|---|
|NewMethod|Active|Queues|
|NewMethod|Cancel|Nop|
|NewMethod|Complete|Throw|

The change in its current form though is changing the behavior of `TryEnqueue`.  After this change the behavior is:

|Operation|Queue State|Outcome|
|---|---|---|---|
|TryEnqueue|Active|Queues|
|TryEnqueue|Complete|**Throws**|
|TryEnqueue|Cancel|Nop|

This means we are opening ourselves to new crashes via this change.  I agree any such crashes are likely programming errors.  However it's too late in the game to start finding these out in the stabilization branch.  I think we should fix this bug, and this bug only, in this PR and move the other behavior change to `master` or `future`.

**Comment by gafter** [comment]
@jaredpar wrote

> This means we are opening ourselves to new crashes via this change.  I agree any such crashes are likely programming errors.  However it's too late in the game to start finding these out in the stabilization branch.  I think we should fix this bug, and this bug only, in this PR and move the other behavior change to `master` or `future`. 

Your analysis is mistaken. The queue does not throw when `TryEnqueue` is called after the queue has been completed. It only crashes after the new API `PromiseNotToEnqueue` has been called followed by `Enqueue` or `TryEnqueue`.
That new crash path was added in response to *your* request here: https://github.com/dotnet/roslyn/pull/8836#issuecomment-185423507.

Note that there are *no* uses of `TryEnqueue` before this change anywhere in Roslyn (except two lines of tests), only `Enqueue`, which did throw an exception when the queue was completed. `PromiseNotToEnqueue` is an `internal` API (because the enclosing type is `internal`) used only by the compiler, so that we do not lose that exception in the change from using `Enqueue` to `TryEnqueue`. It is difficult to see what code path you're imagining might encounter a new crash.

**Comment by jaredpar** [comment]
> Your analysis is mistaken

I believe my analysis is correct, there are just no uses of `TryEnqueue` that could exploit it :smile:.  

Given the presence of the API I assumed we took advantage of it somewhere other than the unit tests.  Yeah yeah, I know, assumed.  

Will bring this up tomorrow.

**Comment by jaredpar** [comment]
@MattGertz ask mode approval

**Comment by MattGertz** [comment]
@jaredpar @gafter Can you please summarize the offline discussion before I approve?  The comments above jump from disagreement to a request for approval.

**Comment by jaredpar** [comment]
@MattGertz  Summary:

- @jaredpar: There is a breaking change the behavior of `TryEnqueue` after this change.
- @gafter: There are no uses of `TryEnqueue` in the production code base, only our unit tests.  All uses of `TryEnqueue` are new and meet the behavior we want from this change.  
- @jaredpar: Gotcha.

**Comment by MattGertz** [comment]
Approved pending successful completion of tests.

**Comment by davkean** [comment]
@dotnet-bot test win/dbg please

Resync'ing with Jenkins. @gafter We're shutting down this week, you'll want to get it soon.

**Comment by jaredpar** [comment]
This was approved so once the tests pass we should merge.
