### PR TITLE
Fix formatting of positional patterns

### LINKED ISSUE #27268: Formatting for positional pattern should drop a space
current formatting rule is to put a space between type and positional sub-pattern. I think it should be formatted like an invocation instead (ie. no space).

For example, given
``` c#
    Point p = new Point(3, 4);
```
you should write
``` c#
    if (p is Point(3, 4)) ...
```
rather than
``` c#
    if (p is Point (3, 4)) ...
```

The reason I suggest there should be no space is that the syntax was designed to mirror the construction syntax for objects (i.e. a constructor invocation), where there is no space.

### PR DESCRIPTION
**Pull request by sharwell**
Closes #27268 

<details><summary>Ask Mode</summary>

### Customer scenario

A customer uses the new C# 8 recursive patterns feature with a positional pattern. The IDE ignores the users code style preferences for formatting the new construct, and by default does not follow the default recommended style for these patterns.

### Bugs this fixes

#27268

### Workarounds, if any

None.

### Risk

Low. This change only impacts the formatting of positional patterns, and tests are included to show the expected behavior is followed for both default and customized scenarios.

### Performance impact

Negligible.

### Is this a regression from a previous update?

No.

### Root cause analysis

Reported during feature development, but work to correct it waited for the feature to land in the main development branch.

### How was the bug found?

Reported by feature author.

### Test documentation updated?

No.

</details>

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/Formatting/FormattingEngineTests.cs [hunk 1]
```diff
@@ -1970,6 +1970,41 @@ void MyMethod()
...
+        [Trait(Traits.Feature, Traits.Features.Formatting)]
+        [WorkItem(27268, "https://github.com/dotnet/roslyn/issues/27268")]
+        public async Task PositionalPattern()
+        {
+            var code = @"[|
+class MyClass
+{
+    void MyMethod()
+    {
+        var point = new Point (3, 4);
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/Formatting/FormattingEngineTests.cs]: @gafter I have a couple questions:

1. Can the parentheses be empty?
2. Right now I account for the option to have a space between a method call and the opening parenthesis. Should it also account for options to place spaces inside method call parentheses?

**Comment by sharwell** [comment]
@jasonmalinowski Do you know what the point of this test is? It seems like gibberish.

https://github.com/dotnet/roslyn/blob/c4f962a97c82d690d08edd0e72fada6fd1619541/src/Workspaces/CSharpTest/Formatting/FormattingTests.cs#L5219-L5244

**Comment by jasonmalinowski** [comment]
@sharwell No idea. What does blame say?

**Comment by Neme12** [comment]
It shows @jcouv

**Comment by jcouv** [comment]
@sharwell Here's an example of code you might be in the process of typing, except with extremely weird formatting ;-)

```C#
class C 
{ 
     void M() 
     { 
          _ = this is (1, 2) { Property: 3 }; // recursive pattern with positional and property sub-patterns
         M(); 
     }
 } 
```

**Comment by jcouv** [comment]
Correction, the intent (based on the name of the test:
```C#
class C 
{ 
     void M() 
     { 
          _ = this is (1, 2) // typing here
         { // scope
             M(); 
         }
     }
 } 
```

File: src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs [hunk 2]
```diff
@@ -377,7 +377,7 @@ public override AdjustSpacesOperation GetAdjustSpacesOperation(SyntaxToken previ
 
                 if (recursivePatternType != null)
                 {
-                    return CreateAdjustSpacesOperation(1, AdjustSpacesOption.ForceSpaces);
+                    return AdjustSpacesOperationZeroOrOne(optionSet, CSharpFormattingOptions.SpaceAfterMethodCallName);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs]: the comment above seems like it is no longer valid.  maybe it should be `update the space between a type and a positional pattern`?

File: src/EditorFeatures/CSharpTest/Formatting/FormattingEngineTests.cs (hunk 1 above)
Comment (gafter) [reply src/EditorFeatures/CSharpTest/Formatting/FormattingEngineTests.cs]: 1. Yes, the parens can be empty, can contain just one pattern, or any number of comma-separated patterns.
2. I would expect the options that apply to the object creation expression to equally apply to the positional part of a pattern.  I think that is a yes.

---
In reply to: [246495924](https://github.com/dotnet/roslyn/pull/32286#discussion_r246495924) [](ancestors = 246495924)

File: src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs [hunk 3]
```diff
@@ -377,7 +377,7 @@ public override AdjustSpacesOperation GetAdjustSpacesOperation(SyntaxToken previ
 
                 if (recursivePatternType != null)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs]: Also: it seems risky to assume that a DeconstructionPatternClause must be parented by a RecursivePatternSyntax.  That appears to be hte case now, but it's unclear why this would have to be the case in the future.

File: src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs (hunk 2 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs]: `CSharpFormattingOptions.SpaceAfterMethodCallName`

It's unclear to me why this would be the right option to use.  For one thing, this is not really a method-call, it's a positional pattern.  For another, the syntax is `Type DeconstructionPattern`.  So, it's not really the name of a method, it's the name of a type.  And, importantly, we don't use this formatting option to separate out a Type+List when you have `new Foo(...)`.  So i don't see why we would separate it out now that you have `Foo (...)` in a pattern.

Comment (CyrusNajmabadi) [reply src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs]: Objection retracted.  Something was messed up with my VS. Even though i enabled this option, it didn't add a space.  However, closing/reopening caused it to start adding the space.  So i agree with this change.

Comment (sharwell) [reply src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs]: Fixed!

File: src/EditorFeatures/CSharpTest/Formatting/FormattingEngineTests.cs (hunk 1 above)
Comment (sharwell) [reply src/EditorFeatures/CSharpTest/Formatting/FormattingEngineTests.cs]: Thanks, I updated the formatter to treat the recursive pattern like a method call.

File: src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs (hunk 3 above)
Comment (sharwell) [reply src/Workspaces/CSharp/Portable/Formatting/Rules/SpacingFormattingRule.cs]: This should be resolved now.

**Comment by sharwell** [comment]
@jasonmalinowski I rewrote this to better handle spacing both before and inside these parentheses. Can you look again?

File: src/EditorFeatures/CSharpTest/Formatting/FormattingEngineTests.cs [hunk 4]
```diff
@@ -1970,6 +1970,41 @@ void MyMethod()
...
+        if (point is Point(3, 4) _
+            && point is Point { x: 3, y: 4 } _)
+        {
+        }
+    }
+}
+";
+
+            await AssertFormatWithBaseIndentAsync(expected, code, baseIndentation: 4);
+        }
```
Comment (jcouv) [inline src/EditorFeatures/CSharpTest/Formatting/FormattingEngineTests.cs]: >} [](start = 8, length = 1)

Would it be useful to also test different options, since it looks like positional patterns will be formatted like methods, and methods are governed by certain options?

Comment (sharwell) [reply src/EditorFeatures/CSharpTest/Formatting/FormattingEngineTests.cs]: Tests updated

**Comment by sharwell** [comment]
@jinujoseph for approval

**Comment by jinujoseph** [comment]
@sharwell lets retrarget to master
