### PR TITLE
Show nearby comments in QuickInfo for scope blocks.

### LINKED ISSUE #325: QuickInfo on close curly at end of scope block shows too much code
Ported from TFS WorkItem: **887257**

------------------------------

**Repro Steps:**

**Affected Branch:** <BR>**Affected Build:** <BR>**Affected Product Language:** <BR><BR>**Steps to reproduce:**<BR><BR>1. Copy/paste C# code:

&nbsp;
<PRE style="FONT-SIZE: 16px; FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink"><FONT size=2><SPAN style="COLOR: blue">using</SPAN> <SPAN style="COLOR: black">System</SPAN><SPAN style="COLOR: black">;</SPAN>
 
<SPAN style="COLOR: blue">class</SPAN> <SPAN style="COLOR: #2b91af">Program</SPAN>
<SPAN style="COLOR: black">{</SPAN>
    <SPAN style="COLOR: blue">static</SPAN> <SPAN style="COLOR: blue">void</SPAN> <SPAN style="COLOR: black">Main</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">string</SPAN><SPAN style="COLOR: black">[]</SPAN> <SPAN style="COLOR: black">args</SPAN><SPAN style="COLOR: black">)</SPAN>
    <SPAN style="COLOR: black">{</SPAN>
        <SPAN style="COLOR: blue">if</SPAN> <SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">true</SPAN><SPAN style="COLOR: black">)</SPAN>
        <SPAN style="COLOR: black">{</SPAN>
            <SPAN style="COLOR: #2b91af">Console</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">WriteLine</SPAN><SPAN style="COLOR: black">();</SPAN>
            <SPAN style="COLOR: #2b91af">Console</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">WriteLine</SPAN><SPAN style="COLOR: black">();</SPAN>
 
            <SPAN style="COLOR: blue">if</SPAN> <SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">false</SPAN><SPAN style="COLOR: black">)</SPAN>
            <SPAN style="COLOR: black">{</SPAN>
                </FONT><FONT size=2><SPAN style="COLOR: green">/*
                This
                is
                the
                if
                block
                */</SPAN>
            <SPAN style="COLOR: black">}</SPAN>
 
            <SPAN style="COLOR: #2b91af">Console</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">WriteLine</SPAN><SPAN style="COLOR: black">();</SPAN>
            <SPAN style="COLOR: #2b91af">Console</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">WriteLine</SPAN><SPAN style="COLOR: black">();</SPAN>
 
            <SPAN style="COLOR: black">{</SPAN>
                </FONT><FONT size=2><SPAN style="COLOR: green">/*
                This
                is
                just
                a
                block
                */</SPAN>
            <SPAN style="COLOR: black"><FONT style="BACKGROUND-COLOR: #ff8000">}</FONT></SPAN> <SPAN style="COLOR: green">// ******** Hover on the close curly ********</SPAN>
 
            <SPAN style="COLOR: #2b91af">Console</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">WriteLine</SPAN><SPAN style="COLOR: black">();</SPAN>
            <SPAN style="COLOR: #2b91af">Console</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">WriteLine</SPAN><SPAN style="COLOR: black">();</SPAN>
 
            <SPAN style="COLOR: blue">for</SPAN> <SPAN style="COLOR: black">(;</SPAN> <SPAN style="COLOR: black">;)</SPAN>
            <SPAN style="COLOR: black">{</SPAN>
                </FONT><FONT size=2><SPAN style="COLOR: green">/*
                This
                is
                the
                for
                block
                */</SPAN>
            <SPAN style="COLOR: black">}</SPAN>
        <SPAN style="COLOR: black">}</SPAN>
    <SPAN style="COLOR: black">}</SPAN>
<SPAN style="COLOR: black">}</SPAN></FONT></PRE>

&nbsp;

2. Hover on the close curly brace on line 34 (<FONT style="BACKGROUND-COLOR: #ff8000">highlighted</FONT> above).

&nbsp;

**Expected:** Less code. Maybe just the **{**, or the **{** and the line immediately after?

**Actual**:
<PRE style="FONT-SIZE: 16px; FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink"><SPAN style="COLOR: black">{</SPAN>
<SPAN style="COLOR: #2b91af"><FONT color=#ff69b4>    </FONT>Console</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">WriteLine</SPAN><SPAN style="COLOR: black">();</SPAN>
    <SPAN style="COLOR: #2b91af">Console</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">WriteLine</SPAN><SPAN style="COLOR: black">();</SPAN>
 
    <SPAN style="COLOR: blue">if</SPAN> <SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">false</SPAN><SPAN style="COLOR: black">)</SPAN>
    <SPAN style="COLOR: black">{</SPAN>
        <SPAN style="COLOR: green">/*
        This
        is
        the
        if
        block
        */</SPAN>
    <SPAN style="COLOR: black">}</SPAN>
 
    <SPAN style="COLOR: #2b91af">Console</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">WriteLine</SPAN><SPAN style="COLOR: black">();</SPAN>
    <SPAN style="COLOR: #2b91af">Console</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black">WriteLine</SPAN><SPAN style="COLOR: black">();</SPAN>
 
    <SPAN style="COLOR: black">{</SPAN></PRE>

------------------------------

**Revisions:**

1) Created By David Poeschl (2/19/2014 12:58:04 PM)

It's currently just going to the block's parent, which is usually correct but not in this case.

### PR DESCRIPTION
**Pull request by diryboy**
Fixes #325

### CODE REVIEW

**Comment by diryboy** [comment]
LOL what happened to the dotnet bot?

**Comment by diryboy** [comment]
test win/dbg/unit32 please

**Comment by diryboy** [comment]
test unit32 please

**Comment by davkean** [comment]
Yep, sorry about that - he got very excited. Should be fixed now. 

tag @dotnet/roslyn-ide Can someone take a look at this?

@dotnet-bot okay to test

**Comment by tannergooding** [comment]
test eta please

**Comment by diryboy** [comment]
test eta please

File: src/EditorFeatures/CSharp/QuickInfo/SyntacticQuickInfoProvider.cs [hunk 1]
```diff
@@ -76,8 +85,66 @@ internal class SyntacticQuickInfoProvider : AbstractQuickInfoProvider
...
+
+            var nextToken = block.FindToken(openBrace.FullSpan.End);
+            if (nextToken.HasLeadingTrivia && FindFurthestNearbyComment(nextToken.LeadingTrivia, out nearbyTrivia))
+            {
+                spanEnd = nearbyTrivia.Span.End;
+                return;
+            }
+        }
+
+        private static bool FindFurthestNearbyComment(IEnumerable<SyntaxTrivia> triviaSearchList, out SyntaxTrivia nearbyTrivia)
```
Comment (diryboy) [inline src/EditorFeatures/CSharp/QuickInfo/SyntacticQuickInfoProvider.cs]: Boxing

File: src/EditorFeatures/CSharp/QuickInfo/SyntacticQuickInfoProvider.cs [hunk 2]
```diff
@@ -76,8 +85,66 @@ internal class SyntacticQuickInfoProvider : AbstractQuickInfoProvider
...
+        {
+            var searchList = triviaSearchList.SkipWhile(IsIndentation).ToArray();
```
Comment (diryboy) [inline src/EditorFeatures/CSharp/QuickInfo/SyntacticQuickInfoProvider.cs]: To avoid allocation and the boxing passing in the first parameter, I have another implementation of this method, but it looks rather ugly as it uses state machine, goto..
```C#
        const int MarkIfMultiLineComment = 1;
        const int MarkIfSingleLineComment = 2;
        const int CrawlFurtherIfPreviouslyMarkedSingleLineComment = 3;

        private static bool FindFurthestNearbyComment<T>(ref T triviaSearchList, out SyntaxTrivia nearbyTrivia)
            where T : IEnumerable<SyntaxTrivia>
        {
            nearbyTrivia = default(SyntaxTrivia);

            var skipped = 0;
            var state = MarkIfMultiLineComment;

            foreach (var trivia in triviaSearchList)
            {
                switch (state)
                {
                    case MarkIfMultiLineComment:

                        if (IsIndentation(trivia, skipped))
                        {
                            skipped++;
                            continue;
                        }

                        if (trivia.IsKind(SyntaxKind.MultiLineCommentTrivia))
                        {
                            nearbyTrivia = trivia;
                            return true;
                        }

                        goto case MarkIfSingleLineComment;

                    case MarkIfSingleLineComment:

                        if (trivia.IsKind(SyntaxKind.SingleLineCommentTrivia))
                        {
                            nearbyTrivia = trivia;

                            skipped = 0;
                            state = CrawlFurtherIfPreviouslyMarkedSingleLineComment;
                            continue;
                        }

                        break;

                    case CrawlFurtherIfPreviouslyMarkedSingleLineComment:

                        if (IsIndentation(trivia, skipped))
                        {
                            skipped++;
                            continue;
                        }

                        goto case MarkIfSingleLineComment;

                    default:
                        break;
                }
            }

            return nearbyTrivia.IsKind(SyntaxKind.SingleLineCommentTrivia);
        }
```

File: src/EditorFeatures/CSharp/QuickInfo/SyntacticQuickInfoProvider.cs (hunk 1 above)
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharp/QuickInfo/SyntacticQuickInfoProvider.cs]: This all seems very overwrought.  Why not just keeping consuming comment+whitespace+newline trivia. Then, at the end, as long as you have at least one comment, then you're good to use this comment section.

Comment (diryboy) [inline src/EditorFeatures/CSharp/QuickInfo/SyntacticQuickInfoProvider.cs]: @CyrusNajmabadi My current implementation only allow one kind of comments that immediately above/below the open brace.

Assuming you allow
```C#
/* haha */

// dada

{
```
Then I am OK, we can even loosen the check to first non-empty trivia so that this method is not needed, so, your call?

Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharp/QuickInfo/SyntacticQuickInfoProvider.cs]: I would just allow that.  First, I don't see why allowing that would be bad.  Second, you have to write so much logic to disallow it.

It's much simpler to just keep consuming as long as it's a reasonable form of trivia (i.e. not 'preprocessor trivia'), and just attaching it as long as you see at least one comment.

**Comment by diryboy** [comment]
retest unit64 please

**Comment by diryboy** [comment]
retest this please

**Comment by diryboy** [comment]
retest unit64 please

File: src/EditorFeatures/CSharp/QuickInfo/SyntacticQuickInfoProvider.cs (hunk 2 above)
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharp/QuickInfo/SyntacticQuickInfoProvider.cs]: A nicer way might just be to allow a syntax trivia list, and hten have a bool parameter saying if you want to consume forward or backward.

**Comment by diryboy** [comment]
@CyrusNajmabadi I've changed the checking logic by your comment, please take a look.

@Pilchie @dpoeschl Could you also take a look?

File: src/EditorFeatures/CSharp/QuickInfo/SyntacticQuickInfoProvider.cs [hunk 3]
```diff
@@ -76,8 +85,53 @@ internal class SyntacticQuickInfoProvider : AbstractQuickInfoProvider
...
+            var nextToken = block.FindToken(openBrace.FullSpan.End);
+            var searchListBelow = nextToken.LeadingTrivia;
+            if (FindFurthestNearbyComment(ref searchListBelow, out nearbyComment))
+            {
+                spanEnd = nearbyComment.Span.End;
+                return;
+            }
+        }
+
+        private static bool FindFurthestNearbyComment<T>(ref T triviaSearchList, out SyntaxTrivia nearbyTrivia)
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharp/QuickInfo/SyntacticQuickInfoProvider.cs]: Interesting.  Does this work?  You're going to get specializations for each T.  And I suppose these will be constrained interface calls through IEnumerable, which the JIT can optimize.  So, if this works, very cute and nifty :-)

Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharp/QuickInfo/SyntacticQuickInfoProvider.cs]: Rename to TryFind...

**Comment by CyrusNajmabadi** [comment]
:+1:  With the naming change I've asked for.  Thanks for this contribution!

File: src/EditorFeatures/CSharp/QuickInfo/SyntacticQuickInfoProvider.cs (hunk 3 above)
Comment (diryboy) [inline src/EditorFeatures/CSharp/QuickInfo/SyntacticQuickInfoProvider.cs]: @CyrusNajmabadi Yes, as you described it's an attempt to avoid boxing and copy. Some say it can be annotated with `[MethodImpl(MethodImplOptions.AggressiveInlining)]` to further avoid method call overhead, but I don't think it need this far here.

Sure, renamed.

**Comment by davkean** [comment]
Can one more @dotnet/roslyn-ide sign off please?

File: src/EditorFeatures/CSharp/QuickInfo/SyntacticQuickInfoProvider.cs [hunk 4]
```diff
@@ -59,12 +60,20 @@ internal class SyntacticQuickInfoProvider : AbstractQuickInfoProvider
...
             }
 
-            // If the open brace is the first token of the node (like in the case of a block node or
-            // an accessor list node), then walk up one higher so we can show more useful context
-            // (like the method a block belongs to).
-            if (parent.GetFirstToken() == openBrace)
+            var spanStart = parent.SpanStart;
+            var spanEnd = openBrace.Span.End;
+
+            // If the parent is a scope block, check and include nearby comments around the open brace
```
Comment (dpoeschl) [inline src/EditorFeatures/CSharp/QuickInfo/SyntacticQuickInfoProvider.cs]: @amcasey I assume scripting will support floating blocks? The current check as proposed only applies to blocks within blocks (the usual case, since regular C# doesn't support blocks floating in nowhere-land), but we might want this logic for standalone blocks in scripting... 

I'm not sure if the previous implementation attempted to do the "right" thing for scripts anyway, but I just wanted to bring it up for discussion.

Comment (amcasey) [inline src/EditorFeatures/CSharp/QuickInfo/SyntacticQuickInfoProvider.cs]: Assuming that "floating" means "top-level", yes I believe they're allowed in ```SourceCodeKind.Script```.  @tmat can confirm (or you could try it :)).

File: src/EditorFeatures/CSharpTest/QuickInfo/SyntacticQuickInfoSourceTests.cs [hunk 5]
```diff
@@ -34,6 +34,87 @@ public void Brackets_1()
...
+
+        [WpfFact, Trait(Traits.Feature, Traits.Features.QuickInfo)]
+        public void ScopeBrackets_4()
+        {
+            TestInMethod(@"
+            if (true)
+            {
+                {
+                    /* comment */
+                }$$
```
Comment (dpoeschl) [inline src/EditorFeatures/CSharpTest/QuickInfo/SyntacticQuickInfoSourceTests.cs]: Can you add a test with comments before *and* after the open curly, for your "prefer leading comments" case?

Comment (dpoeschl) [inline src/EditorFeatures/CSharpTest/QuickInfo/SyntacticQuickInfoSourceTests.cs]: And, if you could, one for leading trivia with blank lines in between (I know it will work, but just for the scenario coverage):
```C#
// This comment is basically a dissertation!

// Part 1: Stuff.

// Part 2: More stuff!
{
}
```

Comment (dpoeschl) [inline src/EditorFeatures/CSharpTest/QuickInfo/SyntacticQuickInfoSourceTests.cs]: And finally, can you vary the tests by what the block is contained in? Reading the test makes me think this might only work for blocks inside blocks inside methodblocks, but it should also work for blocks inside methodblocks. So in some of the cases maybe remove the if (true) block.

File: src/EditorFeatures/CSharpTest/QuickInfo/SyntacticQuickInfoSourceTests.cs [hunk 6]
```diff
@@ -34,6 +34,87 @@ public void Brackets_1()
             ExpectedContent("if (true)\r\n{"));
         }
 
+        [WpfFact, Trait(Traits.Feature, Traits.Features.QuickInfo)]
```
Comment (dpoeschl) [inline src/EditorFeatures/CSharpTest/QuickInfo/SyntacticQuickInfoSourceTests.cs]: Can you add ```[WorkItem(325, "https://github.com/dotnet/roslyn/issues/325")]" to these tests?

**Comment by diryboy** [comment]
@dpoeschl I updated the tests according to your comment, please take a look.

About the `SourceKind.Script` scenario, if you have conclusion, please open another PR, as top level scope block should fall into the old logic that I did not change, what's more, I don't know how to test scripts.

**Comment by dpoeschl** [comment]
@diryboy The tests look awesome! Thanks for expanding on them.

I would think the scripting top-level scope block issue does fall into this bugfix. Top-level methods, loops, etc. in scripting do *not* fall into this, and these scenarios should really already have had tests. But, as you can see, we never added any scripting tests for this feature. Of course, you shouldn't be responsible for any of that just because you wanted to fix this bug and *we* have existing test debt here. However, we do want to make sure we get scripting tests added here before merging (or the functionality/testing gap between regular code & scripting code will continue to grow, and we're really trying to fix that).

So, I'm happy add the test infrastructure for this (shouldn't be too difficult, basically just adding a "TestInScript" helper to the abstract test base class that passes the ```SourceCodeKind.Script``` into the final ```Test(...)``` method and applies it to the ParseOptions), but it might take me a while to get around to it (we're focusing more on the *stabilization* branch at the moment). I expect I'll be able to add that helper and some initial scripting tests (not including top-level scope blocks) within the next week. You're always welcome to do this work if you'd like, but it's **definitely** not required.

Thanks for your patience as we incrementally clean up our testing debt around scripting. I'm *really* happy someone took the time to fix this issue, and I'm excited to merge it once we have tests proving how well it works in scripting as well!

**Comment by dpoeschl** [comment]
To clarify a bit more, we're also happy to add the scripting top-level scope block tests as well (I apologize if it sounded like we intended for you to wait a week, then add more tests when it's convenient for us). We can branch from your PR branch, add test infrastructure, add all of the required tests, and check in (the commits made by you will still be attributed to you).

**Comment by diryboy** [comment]
@dpoeschl Thanks for the pointer, I'll try add them.

I find `CSharpWorkspaceFactory.CreateWorkspaceFromFile` takes `CSharpParseOptions` as the second parameter, and I've seen tests passing `Options.Script` where its definition passes `SourceCodeKind.Script`.

But it took me minutes to realize that `Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Options` is a namespace in the `EditorServicesTest` project where `AbstractQuickInfoSourceTests` in written in!

What's more, `AbstractQuickInfoSourceTests` is only designed for C# and VB does not have it's implementation at all! I'll empty the methods and move them down.

BTW I'm not sure how to detect the top level scope block in script, what is the `.Parent` of a top level scope block? Still a `CompilationUnit`?

**Comment by diryboy** [comment]
@dpoeschl I updated the code supporting top level scope blocks in script as well as scope blocks within switch section, additionally with few more tests asserting the existing behavior for other kinds of blocks.

**Comment by dpoeschl** [comment]
Thanks @diryboy! I'll take a look later today, but wanted to add a note-to-self that we should internally verify that the Syntax Visualizer works on script files, so that future devs will be able to more easily answer the "what does the tree look like in script" questions.

**Comment by dpoeschl** [comment]
Tried it out in script files locally, it works great.

**Comment by dpoeschl** [comment]
:+1: Thanks @diryboy!

**Comment by dpoeschl** [comment]
@dotnet/roslyn-ide Last call for reviews.

**Comment by davkean** [comment]
Thanks again for the contribution and going above and beyond on the tests!

**Comment by davkean** [comment]
test eta please
