### PR TITLE
Fix !! incremental parsing

### LINKED ISSUE #59580: Issues with formatting and whitespace around !! annotation
**Version Used**: 
Version 17.2.0 Preview 2.0 [32207.482.main]

Blocks dogfooding.

Attempted to use `!!` in Roslyn.sln:

1) Compiler reports error when whitespace is in between parameter name and `!!`:
image

2) Formatter reports warning (#58798):
image

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #59580

cc @RikkiGibson @tmat

Relates to test plan https://github.com/dotnet/roslyn/issues/36024

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 1]
```diff
@@ -4517,6 +4517,11 @@ private ParameterSyntax ParseParameter()
                         this.GetExpectedTokenError(expected: SyntaxKind.ExclamationExclamationToken, actual: firstExclamation.Kind));
                 }
             }
+            else if (this.CurrentToken.Kind is SyntaxKind.ExclamationExclamationToken)
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:4520]: I'm very confused. I'm on mobile so maybe I'm missing something. But this appears to be the same as the first check in the if-chain, right?  What am I missing?

Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:4520]: Ignore. I misread

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 2]
```diff
@@ -4517,6 +4517,11 @@ private ParameterSyntax ParseParameter()
...
+            {
+                // This is reachable for incremental parsing.
+                exclamationExclamationToken = EatToken();
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:4523]: I have mixed feelings. Not in front of a computer, but I feel like we have some logic elsewhere (maybe in the blender) for dealing with merged tokens (like `>>`). I think that same location should be updated for this special token.

**Comment by CyrusNajmabadi** [comment]
Look for a method that has 'Fabricated' in its name.  That should be what we are updating.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs (hunk 2 above)
Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:4523]: Actually, this is certainly wrong.  because it means that if the edit to the tree is such that the synthesized `!!` gets moved somewhere else (e.g. to now be a suffix suppression operator), that code will break because it won't see this as two exclamation tokens, but a single token as well.  These merged tokens can't be returned from the incremental lexer as they do not correspond to what the lexer would have produced originally.

**Comment by Youssef1313** [comment]
There is `IsFabricatedToken`. I'll see if updating it fixes the issue.

**Review by CyrusNajmabadi — CHANGES_REQUESTED** [review]
Needs a tweak.  If you can't find the relevant method, LMK and i can hunt it down on monday.  THanks!

**Review by CyrusNajmabadi — APPROVED** [review]
LGTM!

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Thanks for the hint!

File: src/Compilers/CSharp/Portable/Parser/Blender.Reader.cs [hunk 3]
```diff
@@ -305,6 +305,7 @@ private static bool IsFabricatedToken(SyntaxKind kind)
                 {
                     case SyntaxKind.GreaterThanGreaterThanToken:
                     case SyntaxKind.GreaterThanGreaterThanEqualsToken:
+                    case SyntaxKind.ExclamationExclamationToken:
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Parser/Blender.Reader.cs:308]: my bad on forgetting about this @Youssef1313 @RikkiGibson .  The merging tokens bit totally should have triggered things for me!

Comment (jcouv) [reply src/Compilers/CSharp/Portable/Parser/Blender.Reader.cs:308]: Consider adding a note to `MergeAdjacent` to mention this method should be updated when used.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 3)

File: src/Compilers/CSharp/Portable/Parser/Blender.Reader.cs (hunk 3 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Parser/Blender.Reader.cs:308]: > Consider adding a note to MergeAdjacent to mention this method should be updated when used.

It looks `LanguageParser.ParseLambdaExpression()` also uses `MergeAdjacent()` for `SyntaxKind.EqualsGreaterThanToken`.

File: src/Compilers/CSharp/Test/Syntax/IncrementalParsing/IncrementalParsingTests.cs [hunk 4]
```diff
@@ -432,7 +463,6 @@ public void TestStatementToGlobalStatementChange()
                             SyntaxKind.IdentifierName,
                             SyntaxKind.SemicolonToken);
         }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Syntax/IncrementalParsing/IncrementalParsingTests.cs:465]: >} [](http://example.com/codeflow?start=8&length=1)

Consider adding back the blank line.

File: src/Compilers/CSharp/Portable/Parser/Blender.Reader.cs (hunk 3 above)
Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Portable/Parser/Blender.Reader.cs:308]: good catch!

Comment (cston) [reply src/Compilers/CSharp/Portable/Parser/Blender.Reader.cs:308]: Consider adding an assert to `MergeAdjacent()`: `Debug.Assert(IsFabricatedToken(kind));`

**Review by RikkiGibson — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Parser/Blender.Reader.cs (hunk 3 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Parser/Blender.Reader.cs:308]: Logged [https://github.com/dotnet/roslyn/issues/60002](https://github.com/dotnet/roslyn/issues/60002).

**Review by cston — APPROVED** [review]

**Review by CyrusNajmabadi — CHANGES_REQUESTED** [review]
changing my vote.  we're jsut asking to eb be bitten by the other merged token.  we should just fix the code now and not have some random tree corruption issue someone has to figure out months down the line :)

**Comment by RikkiGibson** [comment]
> changing my vote. we're jsut asking to eb be bitten by the other merged token. we should just fix the code now and not have some random tree corruption issue someone has to figure out months down the line :)

making sure I understand your concern here. Are you asking that #60002 be addressed now and not afterwards? Since we do have #60005 open currently which should address it.

**Comment by CyrusNajmabadi** [comment]
> https://github.com/dotnet/roslyn/pull/60005 open currently which should address it.

That adds the assert (which is good).  But i see no code change that adds the merged token taht the parser is creating to the blnder-reader to make sure we don't try to reuse that.  or is the theory there that that's ok because `=>` is a token that the lexer *would* produce?  if so, i could be offbase and maybe this change is totally fine, just very subtle.

**Review by CyrusNajmabadi — COMMENTED** [review]
retracting my objection.

**Comment by RikkiGibson** [comment]
@Youssef1313 do you think it's reasonable to do https://github.com/dotnet/roslyn/pull/59977#issuecomment-1061197402 as part of this PR, just to ensure it's all out of the way?

**Comment by Youssef1313** [comment]
@RikkiGibson This one is now already merged. I'm not sure it will be easy to reproduce the problem with lambdas parsing.

The `else` part of this condition will eat the fabricated token.

https://github.com/dotnet/roslyn/blob/347cd02a80446b47eb93d1effc6d675810457bc2/src/Compilers/CSharp/Portable/Parser/LanguageParser.cs#L13018-L13031

Per @CyrusNajmabadi explanation, this is in general not correct because the merged token can be moved to a place where it contextually have a different meaning and hence a different SyntaxKind.

For the `!!` case it could be a double null suppression.

For the `=>` case, I can't think of it having a different meaning. That opens two questions:

- Why it's not a single token at first place so that we don't need merging.
- Should we add it to `IsFabricatedToken` just in case `=>` had a different meaning in future. Or probably leave everything as is now until an issue is reported?
