### PR TITLE
Respect code style option severity in ConvertSwitchStatementToExpress…

### LINKED ISSUE #36086: IDE0066 (ConvertSwitchStatementToExpression) does not respect severity from CSharpCodeStyleOptions.PreferSwitchExpression
**Version Used**: 

Latest master

**Steps to Reproduce**:

1. Create a C# project with following code and `<LangVersion>preview</LangVersion>`:
```csharp
using System;

namespace ConvertToSwitchExpression
{
    public class A
    {
        public string M1(int i)
        {
            switch (i)
            {
                case 0:
                    return "Zero";
                case 1:
                    return "One";
                default:
                    return "Multiple";
            }
        }
    }
}
```
2. Verify code fix to convert switch statement to switch expression is shown, and IDE0066 is a hidden diagnostic
3. Change severity of `CSharpCodeStyleOptions.PreferSwitchExpression` to Warning
image

**Expected Behavior**:
See a warning in error list and a squiggle in the editor on switch keyword.

**Actual Behavior**:
IDE0066 is always reported as a hidden diagnostic

### PR DESCRIPTION
**Pull request by mavasani**
…ionDiagnosticAnalyzer

Fixes #36086

### CODE REVIEW

**Comment by mavasani** [comment]
Tag @alrz @CyrusNajmabadi

File: src/Features/CSharp/Portable/ConvertSwitchStatementToExpression/ConvertSwitchStatementToExpressionDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -61,9 +61,10 @@ private void AnalyzeSyntax(SyntaxNodeAnalysisContext context)
                 return;
             }
 
-            context.ReportDiagnostic(Diagnostic.Create(Descriptor,
+            context.ReportDiagnostic(DiagnosticHelper.Create(Descriptor,
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ConvertSwitchStatementToExpression/ConvertSwitchStatementToExpressionDiagnosticAnalyzer.cs]: if this is an optional arg, we should consider making mandatory, so that this can't happen.

File: src/EditorFeatures/CSharpTest/ConvertSwitchStatementToExpression/ConvertSwitchStatementToExpressionTests.cs [hunk 2]
```diff
@@ -624,5 +629,36 @@ int M(int i)
...
+                return 5;
+            case 3:
+                return 6;
+            default:
+                return 7;
+        }
+    }
+}";
+            var warningOption = new CodeStyleOption<bool>(true, NotificationOption.Warning);
+            var options = Option(CSharpCodeStyleOptions.PreferSwitchExpression, warningOption);
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/ConvertSwitchStatementToExpression/ConvertSwitchStatementToExpressionTests.cs]: can just say `CodeStyleOptions.TrueWithSuggestionEnforcement`  then just validate you got a suggestion back.

File: src/EditorFeatures/CSharpTest/ConvertSwitchStatementToExpression/ConvertSwitchStatementToExpressionTests.cs [hunk 3]
```diff
@@ -624,5 +629,36 @@ int M(int i)
...
+            var testParameters = new TestParameters(options: options, parseOptions: TestOptions.Regular8);
+            using var workspace = CreateWorkspaceFromOptions(source, testParameters);
+            var diags = await GetDiagnosticsAsync(workspace, testParameters);
+            Assert.Single(diags);
+            Assert.Equal(DiagnosticSeverity.Warning, diags.First().Severity);
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/ConvertSwitchStatementToExpression/ConvertSwitchStatementToExpressionTests.cs]: could just remove the line above and have this be diags.Single().Severity.  But i don't care that much :)

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/ConvertSwitchStatementToExpression/ConvertSwitchStatementToExpressionTests.cs]: also, can we check if the diag ID is actually the one we expect here?

File: src/Features/CSharp/Portable/ConvertSwitchStatementToExpression/ConvertSwitchStatementToExpressionDiagnosticAnalyzer.cs (hunk 1 above)
Comment (mavasani) [reply src/Features/CSharp/Portable/ConvertSwitchStatementToExpression/ConvertSwitchStatementToExpressionDiagnosticAnalyzer.cs]: This is a mandatory argument already for `DiagnosticHelper.Create` API. The issue was the analyzer directly invoked the `Diagnostic.Create` public API, which is meant for all non-code style analyzers.

**Comment by mavasani** [comment]
> Tiny nits/suggestions. Up to you on taking them.

Thanks. I am going to do these as a follow-up change as we have a targeted snap for today and I want to ensure this change makes it in.

File: src/Features/CSharp/Portable/ConvertSwitchStatementToExpression/ConvertSwitchStatementToExpressionDiagnosticAnalyzer.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/ConvertSwitchStatementToExpression/ConvertSwitchStatementToExpressionDiagnosticAnalyzer.cs]: ah, got it.  yeah... hrmm, i wonder if we should have an analyzer to catch usages of Diagnostic.Create!
