### PR TITLE
Ensure that we register to analyze generated code for MakeFieldReadO…

### LINKED ISSUE #50925: IDE0044 suggests making field readonly when generated code writes to it
**Version Used**: 

Visual Studio 16.8.4

**Steps to Reproduce**:

Given the following program and source generator:

```cs
namespace ConsoleApp
{
    [TestGenerator]
    public sealed partial class Test
    {
        private int _value;
    }

    public static class Program
    {
        public static void Main()
            => _ = new Test { Value = 1 };
    }
}
```

```cs
namespace SourceGenerator
{
    [Generator]
    internal class TestGenerator : ISourceGenerator
    {
        private const string AttributeText = @"
using System;
[AttributeUsage(AttributeTargets.Class)]
internal sealed class TestGeneratorAttribute : Attribute
{
}
";

        public void Execute(GeneratorExecutionContext context)
        {
            context.AddSource("TestGeneratorAttribute.g.cs", SourceText.From(AttributeText, Encoding.UTF8));

            if (context.SyntaxReceiver is not TypeSyntaxReceiver)
                return;

            context.AddSource("TestGenerator.g.cs", @"
namespace ConsoleApp
{
    partial class Test
    {
        public int Value
        {
            get => _value;
            set => _value = value;
        }
    }
}
");
        }

        public void Initialize(GeneratorInitializationContext context)
            => context.RegisterForSyntaxNotifications(() => new TypeSyntaxReceiver());

        private sealed class TypeSyntaxReceiver : ISyntaxReceiver
        {
            public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
            {
            }
        }
    }
}
```

**Expected Behavior**:

Expect no IDE0044 for `_value`, since the generated code has a property that uses it as a backing field.

**Actual Behavior**:

image

Applying the suggested fix and adding `readonly` results in CS0191 (a readonly field cannot be assigned to.)

Adding `<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>` in the program's `csproj` also makes IDE0044 show up in the build output, not just in the IDE.

### PR DESCRIPTION
**Pull request by mavasani**
…nly analyzer

Fixes #50925
Note that we only pass in the `Analyze` flag, not the `ReportDiagnostics` flag, so that fields defined in generated code are not flagged.

### CODE REVIEW

File: src/Analyzers/Core/Analyzers/AbstractBuiltInCodeStyleDiagnosticAnalyzer_Core.cs [hunk 1]
```diff
@@ -65,10 +65,12 @@ protected AbstractBuiltInCodeStyleDiagnosticAnalyzer(ImmutableArray<DiagnosticDe
                     customTags: DiagnosticCustomTags.Create(isUnnecessary, isConfigurable, enforceOnBuild));
 #pragma warning restore RS0030 // Do not used banned APIs
 
+        // Code style analyzers should not run on generated code, unless explicitly required by the analyzer.
```
Comment (Youssef1313) [inline src/Analyzers/Core/Analyzers/AbstractBuiltInCodeStyleDiagnosticAnalyzer_Core.cs:68]: Might be better as a doc comment. Probably also extend the statement to say it should either be None or Analyze, but not ReportDiagnostic?

Comment (mavasani) [reply src/Analyzers/Core/Analyzers/AbstractBuiltInCodeStyleDiagnosticAnalyzer_Core.cs:68]: > Probably also extend the statement to say it should either be None or Analyze, but not ReportDiagnostic?

Hmm, I did not want to be so pedantic given we may have some analyzer that also wants to report on generated code? I can actually make this simple by just making this a bool property though, which may make the purpose more explicit.

**Review by davidwengier — APPROVED** [review]

**Review by sharwell — APPROVED** [review]
