### PR TITLE
Add tests to improve coverage of pattern-matching implementation and fix a crash.

### LINKED ISSUE #9542: Test code coverage of pattern-matching implementation.
The pattern-matching implementation started out as a prototype, and reflects a specification that is in flux; it is not in its final production-ready form. The implementation needs to be reviewed in detail against the final specification once it exists, and we should ensure we have code coverage of the relevant code paths of the implementation.

### LINKED ISSUE #16876: Crash (assertion error) compiling pattern switch
Crash (assertion error) compiling pattern switch

The following switch crashes the compiler with an assertion error in Miltstone 2.0 RTM.

``` c#
    static void M2(object o, bool b)
    {
        switch (o)
        {
            case null:
                Console.WriteLine(""M2a""); break;
            case var _ when b:
                Console.WriteLine(""M2b""); break;
            case 1:
                Console.WriteLine(""M2c""); break;
        }
    }
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #9542
Fixes #16876

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a review of this mostly-test addition? I have moved it to post-dev15 because there are also changes to product code included.

**Comment by gafter** [comment]
@AlekseyTs @agocke May I please have a couple of reviews?

File: src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs [hunk 1]
```diff
@@ -129,6 +129,8 @@ private ErrorCode CheckSubsumed(BoundPattern pattern, DecisionTree decisionTree,
                         // the input can no longer be null. In that case a null pattern is subsumed.
                         if (isNull && !inputCouldBeNull)
                         {
+                            // Note: we do not have any test covering this. Is it reachable?
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs]: >// Note: we do not have any test covering this. Is it reachable? [](start = 28, length = 64)

I am not sure how are we going to track the work of adding tests for this and other similar code paths if we are closing #9542 with this PR. Are we going to open different issue(s)?

**Comment by AlekseyTs** [comment]
>     internal class SubsumptionDiagnosticBuilder : DecisionTreeBuilder

Would it be worth adding a description of the algorithm?

---
Refers to: src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs:14 in 5514caf. [](commit_id = 5514caf47266c5405342d5437f3a77c35e0e91d7, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>     internal abstract class DecisionTreeBuilder

I think we should have a somewhat detailed description of the algorithm in the comment above, what are the nodes, what do they mean, how the tree is built, etc. This doesn't have to be done in this PR.

---
Refers to: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs:19 in 5514caf. [](commit_id = 5514caf47266c5405342d5437f3a77c35e0e91d7, deletion_comment = False)

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs [hunk 2]
```diff
@@ -108,14 +105,11 @@ private DecisionTree AddByValue(DecisionTree.Guarded guarded, BoundConstantPatte
         {
             if (guarded.Default != null)
             {
-                if (guarded.Default.MatchIsComplete)
-                {
-                    return null;
-                }
+                Debug.Assert(!guarded.Default.MatchIsComplete); // otherwise we would have given a subsumption error
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: >Debug.Assert(!guarded.Default.MatchIsComplete); // otherwise we would have given a subsumption error [](start = 16, length = 100)

Should we throw instead?

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs [hunk 3]
```diff
@@ -108,14 +105,11 @@ private DecisionTree AddByValue(DecisionTree.Guarded guarded, BoundConstantPatte
...
             }
             else
             {
-                guarded.Default = new DecisionTree.ByValue(guarded.Expression, guarded.Type, null);
+                guarded.Default = new DecisionTree.ByType(guarded.Expression, guarded.Type, null);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: >guarded.Default = new DecisionTree.ByType(guarded.Expression, guarded.Type, null); [](start = 16, length = 82)

Consider adding a comment why we should do this. Why change ```Default``` at all and this way in particular.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs [hunk 4]
```diff
@@ -165,15 +159,16 @@ private DecisionTree AddByValue(DecisionTree.ByType byType, BoundConstantPattern
                 {
                     if (byType.Default.MatchIsComplete)
                     {
+                        // This code may be unreachable due to https://github.com/dotnet/roslyn/issues/16878
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: >// This code may be unreachable due to https://github.com/dotnet/roslyn/issues/16878 [](start = 24, length = 84)

Are we going to track code coverage of this path in that issue?

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs [hunk 5]
```diff
@@ -303,33 +298,28 @@ private DecisionTree AddByType(DecisionTree.ByType byType, TypeSymbol type, Deci
...
+            // if the last type is the type we need, add to it
+            DecisionTree result = null;
+            if (byType.TypeAndDecision.Count != 0)
             {
-                var MatchedType = kvp.Key;
-                var Decision = kvp.Value;
-                // See if matching Type matches this value
-                switch (ExpressionOfTypeMatchesPatternType(type, MatchedType, ref _useSiteDiagnostics))
+                var lastTypeAndDecision = byType.TypeAndDecision.Last();
+                if (lastTypeAndDecision.Key.TupleUnderlyingTypeOrSelf() == type.TupleUnderlyingTypeOrSelf())
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: >lastTypeAndDecision.Key.TupleUnderlyingTypeOrSelf() == type.TupleUnderlyingTypeOrSelf() [](start = 20, length = 87)

Should this comparison consider custom modifiers or tuple name difference? For example, identity conversion does not pay attention to custom modifiers.

**Comment by AlekseyTs** [comment]
>     internal abstract class DecisionTreeBuilder

This is a very complex machinery and I have to admit, I do not have complete understanding what this code is supposed to do and whether what it is doing matches that. None of the methods have comments about their intent and I am not able to infer it from the names. Code within methods lacks comments as well. For the majority of it I cannot tell if it is doing the right thing. Pretty much none of it looks obvious to me. Finding a problem in this code and fixing it will be a hard task for anyone, but the author, I believe. Signing-off on changes with high degree of confidence is going to be a problem as well.  

---
In reply to: [278862933](https://github.com/dotnet/roslyn/pull/16928#issuecomment-278862933) [](ancestors = 278862933)

---
Refers to: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs:19 in 5514caf. [](commit_id = 5514caf47266c5405342d5437f3a77c35e0e91d7, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_PatternSwitchStatement.cs [hunk 6]
```diff
@@ -63,13 +63,13 @@ private BoundStatement MakeLoweredForm(BoundPatternSwitchStatement node)
...
-                // EnC: We need to insert a hidden sequence point to handle function remapping in case 
-                // the containing method is edited while methods invoked in the expression are being executed.
-                if (!node.WasCompilerGenerated && _localRewriter.Instrument)
-                {
-                    expression = _localRewriter._instrumenter.InstrumentSwitchStatementExpression(node, expression, _factory);
+                    // EnC: We need to insert a hidden sequence point to handle function remapping in case 
+                    // the containing method is edited while methods invoked in the expression are being executed.
+                    if (!node.WasCompilerGenerated && _localRewriter.Instrument)
+                    {
+                        expression = _localRewriter._instrumenter.InstrumentSwitchStatementExpression(node, expression, _factory);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_PatternSwitchStatement.cs]: >expression = _localRewriter._instrumenter.InstrumentSwitchStatementExpression(node, expression, _factory); [](start = 24, length = 106)

Doing instrumentation conditionally based on whether we have a constant value is inconsistent with normal switch. If lowering depends on the ConstantValue, we can either pass it separately, or can move the instrumentation to later point in time, after all analysis is done, right before we put expression to the lowered tree.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_PatternSwitchStatement.cs [hunk 7]
```diff
@@ -333,6 +333,7 @@ private BoundExpression TypeTestAndCopyToTemp(BoundExpression input, BoundExpres
                 // invariant: the input has already been tested, to ensure it is not null
                 if (input == temp)
                 {
+                    // this may not be reachable due to https://github.com/dotnet/roslyn/issues/16878
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_PatternSwitchStatement.cs]: >// this may not be reachable due to https://github.com/dotnet/roslyn/issues/16878 [](start = 20, length = 81)

Are we tracking coverage for this code path in that issue?

File: src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs]: I don't have evidence that adding such a test is possible.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: No, we should not throw unconditionally.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs (hunk 4 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: If this is not covered by fixing that issue, this code or comment would be changed as needed.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs (hunk 5 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: No.

File: src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs]: Why do we have this ```if``` then? I think we should either remove it, perhaps adding an assert, or throw from it.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs (hunk 2 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: > No, we should not throw unconditionally.

That is not what I am suggesting. I am asking if we should conditionally throw instead.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs (hunk 4 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: Please at least add an explicit note about this code path in the issue so that we definitely address it, even if we decide to do nothing about sub-optimal code generation. Ideally, I would prefer us to track code coverage in a separate issue, not mixing it with issues about sub-optimal behaviors.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs (hunk 5 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: > No.

Now it takes both into consideration. It doesn't ignore custom modifiers and it ignores tuple names only at the top level. Given your answer, it looks like we should call Equals explicitly and pass appropriate flags (should think about dynamic mismatch as well). The TupleUnderlyingTypeOrSelf call might not be needed then.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: Please add targeted tests at least for dynamic and tuple name mismatch (both not limited to the top level).

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_PatternSwitchStatement.cs (hunk 6 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_PatternSwitchStatement.cs]: When the expression is a constant, that expression is not put in the lowered tree for evaluation.

File: src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs]: The `if` is there because of the expectation that this code path will come into play as the set of supported patterns is expanded.

---
In reply to: [100589351](https://github.com/dotnet/roslyn/pull/16928#discussion_r100589351) [](ancestors = 100589351)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_PatternSwitchStatement.cs (hunk 6 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_PatternSwitchStatement.cs]: We should still find a way for the pattern switch to play nice with instrumentation.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: I don't think that is necessary. The called code following should handle the situation. The purpose of this `if` is to create a decision tree for `guarded.Default` if it has none.

---
In reply to: [100589692](https://github.com/dotnet/roslyn/pull/16928#discussion_r100589692) [](ancestors = 100589692)

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs (hunk 3 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: As you can see from the enclosing `if`, it is `null` and therefore needs to be initialized before being used.

---
In reply to: [100474813](https://github.com/dotnet/roslyn/pull/16928#discussion_r100474813) [](ancestors = 100474813)

File: src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs]: I don't think we should keep dead code just because something might get expanded in the future. If it gets expanded, the code should be added as part of the feature development process, go through standard review and testing process. 

---
In reply to: [100596825](https://github.com/dotnet/roslyn/pull/16928#discussion_r100596825) [](ancestors = 100596825,100589351)

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs (hunk 3 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: Perhaps, it is still not clear why it should be initialized in this particular way. I assume the previous code was incorrect. Why this is correct in general, for all possible scenarios?

---
In reply to: [100598334](https://github.com/dotnet/roslyn/pull/16928#discussion_r100598334) [](ancestors = 100598334,100474813)

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs (hunk 5 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: It is impossible to use tuple types (with names) as the type of a declaration pattern. There simply isn't any syntax for it. So it cannot appear as a type in the map. Moreover, whether or not those are taken into account can only make a difference for performance, not correctness (until we support recursive patterns).

I'll file an issue to investigate, test, and fix if necessary the behavior for nested tuple types.

As for `dynamic`, it is not intended to be supported as the type of a declaration pattern (no runtime object ever has the type `dynamic`). However, I note the compiler does accept it; I'll file a bug.

---
In reply to: [100591895](https://github.com/dotnet/roslyn/pull/16928#discussion_r100591895) [](ancestors = 100591895)

Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: Filed #17088 for differences in nested tuple names.
Filed #17089 for the treatment of dynamic.

---
In reply to: [100601157](https://github.com/dotnet/roslyn/pull/16928#discussion_r100601157) [](ancestors = 100601157,100591895)

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs (hunk 3 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: It was not correct because the guarded type was not necessarily the type of the constant value. A `ByType` decision tree checks the type first. There are tests that catch this included in this PR.

---
In reply to: [100600126](https://github.com/dotnet/roslyn/pull/16928#discussion_r100600126) [](ancestors = 100600126,100598334,100474813)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_PatternSwitchStatement.cs (hunk 6 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_PatternSwitchStatement.cs]: I've opened #17090 to track that.

---
In reply to: [100597429](https://github.com/dotnet/roslyn/pull/16928#discussion_r100597429) [](ancestors = 100597429)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_PatternSwitchStatement.cs (hunk 7 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_PatternSwitchStatement.cs]: Yes.

---
In reply to: [100478333](https://github.com/dotnet/roslyn/pull/16928#discussion_r100478333) [](ancestors = 100478333)

**Comment by gafter** [comment]
>     internal class SubsumptionDiagnosticBuilder : DecisionTreeBuilder

Yes, but that isn't related to adding tests to improve code coverage. I've added #17091 to track adding documentation.

---
In reply to: [278862666](https://github.com/dotnet/roslyn/pull/16928#issuecomment-278862666) [](ancestors = 278862666)

---
Refers to: src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs:14 in 5514caf. [](commit_id = 5514caf47266c5405342d5437f3a77c35e0e91d7, deletion_comment = False)

**Comment by gafter** [comment]
>     internal abstract class DecisionTreeBuilder

#17091 tracks documentation. I held a compiler team design session around this, though I admit you were not fully engaged.

---
In reply to: [278866896](https://github.com/dotnet/roslyn/pull/16928#issuecomment-278866896) [](ancestors = 278866896,278862933)

---
Refers to: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs:19 in 5514caf. [](commit_id = 5514caf47266c5405342d5437f3a77c35e0e91d7, deletion_comment = False)

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs (hunk 5 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: Can't you match against List of tuples or list of dynamic? Please add the requested tests. I will not sign off without them and the line of the code being adjusted according to the intent. 

---
In reply to: [100602791](https://github.com/dotnet/roslyn/pull/16928#discussion_r100602791) [](ancestors = 100602791,100601157,100591895)

**Comment by AlekseyTs** [comment]
>     internal abstract class DecisionTreeBuilder

> I held a compiler team design session around this, though I admit you were not fully engaged.

Regardless how you grade my engagement at the session (I am not sure how it is relevant to this discussion at all because I am not commenting on the quality of the session), my feedback is about the state of code. Whether you held a design session or not doesn't decrease the complexity of the code and doesn't replace the lack of comments in the code. And it certainly wouldn't help anyone who didn't attend the session. 

---
In reply to: [279039461](https://github.com/dotnet/roslyn/pull/16928#issuecomment-279039461) [](ancestors = 279039461,278866896,278862933)

---
Refers to: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs:19 in 5514caf. [](commit_id = 5514caf47266c5405342d5437f3a77c35e0e91d7, deletion_comment = False)

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs (hunk 3 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: Could you please capture that in a comment here?

---
In reply to: [100603286](https://github.com/dotnet/roslyn/pull/16928#discussion_r100603286) [](ancestors = 100603286,100600126,100598334,100474813)

**Comment by jaredpar** [comment]
> Regardless how you grade my engagement at the session (I am not sure how it is relevant ...)

It's not relevant.  

I agree with @AlekseyTs here.  Add the comment.

File: src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs]: I have not attempted to produce a proof that the code is unreachable, which would be a prerequisite for throwing there.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs (hunk 5 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: I think you misunderstand the intent. The code isn't intended to adapt two types that differ in those ways. It is intended to treat tuple types as their underlying types, because the binder turns a constructed type into a tuple type in some circumstances, and then test for type equality. Whether relaxing that to account for differences in custom modifiers (which as far as I know cannot be designated in source, and therefore cannot appear in this map) and nested tuple names would produce correct (and perhaps slightly better) code in some circumstances is an open question that I am not investigating at this time.

---
In reply to: [100616402](https://github.com/dotnet/roslyn/pull/16928#discussion_r100616402) [](ancestors = 100616402,100602791,100601157,100591895)

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: You are adding a new piece of code. I think it, at least, should be tested for correct behavior under conditions that I described. Let's add tests for scenarios that go through this code path with types that differ only in dynamic or tuple name mismatch (both not limited to the top level) and confirm that result is what we would expect to get.

---
In reply to: [100627591](https://github.com/dotnet/roslyn/pull/16928#discussion_r100627591) [](ancestors = 100627591,100616402,100602791,100601157,100591895)

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: BTW, custom modifiers can come from metadata as parts of result types of methods or properties. Are you saying that both types here originate exclusively from type name syntax in source?

---
In reply to: [100629224](https://github.com/dotnet/roslyn/pull/16928#discussion_r100629224) [](ancestors = 100629224,100627591,100616402,100602791,100601157,100591895)

Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: Yes, that is exactly what I am saying.

---
In reply to: [100629991](https://github.com/dotnet/roslyn/pull/16928#discussion_r100629991) [](ancestors = 100629991,100629224,100627591,100616402,100602791,100601157,100591895)

Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: Moreover, this code is present not for correctness of the generated code, but for its quality.

---
In reply to: [100643714](https://github.com/dotnet/roslyn/pull/16928#discussion_r100643714) [](ancestors = 100643714,100629991,100629224,100627591,100616402,100602791,100601157,100591895)

**Comment by gafter** [comment]
@AlekseyTs I have added some comments and tests as requested. If this is not sufficient to help you understand the code I can recommend some reading material for decisions trees as they relate to pattern-matching. Please re-review.

**Comment by gafter** [comment]
@agocke Please review these tests and small changes to pattern-matching.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternSwitchTests.cs [hunk 8]
```diff
@@ -2539,5 +2539,251 @@ static bool TakeOutVar(out int x)
...
+            var source =
+@"
+class Program
+{
+    static void Main()
+    {
+        dynamic d = 1;
+        switch (d)
+        {
+            case dynamic x: // should be an error
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternSwitchTests.cs]: >case dynamic x: // should be an error [](start = 12, length = 37)

Do we have similar tests for tuple types?

File: src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs [hunk 9]
```diff
@@ -9,7 +9,11 @@ namespace Microsoft.CodeAnalysis.CSharp
 
     /// <summary>
     /// Helper class for binding the pattern switch statement. It helps compute which labels
-    /// are subsumed and/or reachable.
+    /// are subsumed and/or reachable. The strategy, implemented in <see cref="PatternSwitchBinder"/>,
+    /// is to start with an empty decision tree, and for each case
+    /// we visit the decision tree to see if the case is subsumed. If it is, we report an error.
+    /// If it is not subsumed and there is no guard expression, we then add it to the decision
+    /// tree.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs]: Is there another comment describing where in the decision tree a new case is supposed to be added? If not please consider adding this information here. Otherwise, please add a reference to that comment here.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs]: Doesn't have to be done in this PR.

---
In reply to: [101109657](https://github.com/dotnet/roslyn/pull/16928#discussion_r101109657) [](ancestors = 101109657)

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs [hunk 10]
```diff
@@ -15,12 +15,30 @@ namespace Microsoft.CodeAnalysis.CSharp
...
         public LocalSymbol Temp;
+        /// <summary>
+        /// True if this decision tree fully handles all possible values of its input.
+        /// </summary>
         public bool MatchIsComplete;
 
+        /// <summary>
+        /// The three different kinds of nodes in the decision tree.
+        /// </summary>
         public enum DecisionKind { ByType, ByValue, Guarded }
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs]: >public enum DecisionKind { ByType, ByValue, Guarded } [](start = 8, length = 53)

Please add detailed comments about each kind.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs [hunk 11]
```diff
@@ -78,16 +83,13 @@ protected DecisionTree AddToDecisionTree(DecisionTree decisionTree, SyntaxNode s
             }
         }
 
-        protected delegate DecisionTree DecisionMaker(
+        protected delegate DecisionTree.Guarded DecisionMaker(
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: >protected delegate DecisionTree.Guarded DecisionMaker( [](start = 8, length = 54)

Consider adding a comment about the purpose of this delegate, when it it invoked and what is it supposed to do.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs (hunk 10 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs]: I prefer not to repeat the comments that are on the decision tree classes themselves. Are you concerned that this undermines the tests that are added in this PR?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternSwitchTests.cs (hunk 8 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternSwitchTests.cs]: I don't know what you mean by that. A tuple type syntax is not permitted in a pattern; yes, we have tests showing that error message. Using the ordinary generic syntax, it works because of the existence of the identity conversion (i.e. there is nothing special about it), and tests for that are in this PR.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs (hunk 10 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs]: Perhaps it is worth adding links to the corresponding types then? This is not a requirement for this PR.

File: src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs (hunk 9 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs]: For the purposes of this class, it doesn't matter where in the decision tree a new case is added (as long as the addition correctly models the pattern). The ordering of decisions in the decision tree built by `SubsumptionDiagnosticBuilder` is irrelevant to its correct computation of subsumption diagnostics.

**Comment by gafter** [comment]
@jaredpar Can you please do the second review here? @agocke is on infrastructure this sprint.

**Comment by jaredpar** [comment]
I'm OOF the rest of the day.  Can try and get to it in the AM.  @jcouv, @cston do either of you have time to look this over today?

File: src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs [hunk 12]
```diff
@@ -193,10 +203,10 @@ private ErrorCode CheckSubsumed(BoundPattern pattern, DecisionTree decisionTree,
                                 }
                             case DecisionTree.DecisionKind.Guarded:
                                 {
-                                    var guarded = (DecisionTree.Guarded)decisionTree;
-                                    return
-                                        (guarded.Guard == null || guarded.Guard.ConstantValue == ConstantValue.True) ? ErrorCode.ERR_PatternIsSubsumed :
-                                        guarded.Default == null ? 0 : CheckSubsumed(pattern, guarded.Default, inputCouldBeNull);
+                                    // This is unreachable because the subsimption version of the decision tree
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs]: Typo: `subsumption`

File: src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs (hunk 1 above)
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs]: I agree with @AlekseyTs regarding removing code that we think is unreachable and is not tested. If we'd rather not delete the few lines of code here and below, consider commenting it out and `throw ExceptionUtilities.Unreachable;` instead.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs [hunk 13]
```diff
@@ -41,6 +78,13 @@ public DecisionTree(BoundExpression expression, TypeSymbol type, LocalSymbol tem
...
         }
 
+        /// <summary>
+        /// Create a fresh decision tree for the given input expression of the given type.
+        /// </summary>
+        /// <param name="expression"></param>
+        /// <param name="type"></param>
+        /// <param name="enclosingSymbol"></param>
+        /// <returns></returns>
         public static DecisionTree Create(BoundExpression expression, TypeSymbol type, Symbol enclosingSymbol)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs]: Empty `<param/>` and `<returns/>` can be removed.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs [hunk 14]
```diff
@@ -70,6 +114,11 @@ public static DecisionTree Create(BoundExpression expression, TypeSymbol type, S
             }
         }
 
+        /// <summary>
+        /// A decisoin tree node that branches based on (1) whether the input value is null, (2) the runtime
```
Comment (cston) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs]: Typo: `decision`

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs [hunk 15]
```diff
@@ -129,15 +190,35 @@ internal override void DumpInternal(StringBuilder builder, string indent)
...
+        /// </summary>
         public class Guarded : DecisionTree
         {
-            // A sequence of bindings to be assigned before evaluation of the guard or jump to the label.
-            // Each one contains the source of the assignment and the destination of the assignment, in that order.
+            /// <summary>
+            /// A sequence of bindings to be assigned before evaluation of the guard or jump to the label.
+            /// Each one contains the source of the assignment and the destination of the assignment, in that order.
+            /// </summary>
             public readonly ImmutableArray<KeyValuePair<BoundExpression, BoundExpression>> Bindings;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTree.cs]: Consider using `(BoundExpression, BoundExpression)` tuple instead.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs [hunk 16]
```diff
@@ -204,8 +212,10 @@ private DecisionTree AddByValue(DecisionTree.ByType byType, BoundConstantPattern
 
             DecisionTree forType = null;
 
-            // Find an existing decision tree for the expression's type. Since this new test
-            // should logically be last, we look for the last one we can piggy-back it onto.
+            // This new type test should logically be last. However it might be the same type as the one that is already
+            // last. In that case we can produce better code by piggy-backing our new case on to the last decision.
+            // Also, the last one might be a non-overlapping type, in which case we can piggy-back onto the second-last
+            // type test.
             for (int i = byType.TypeAndDecision.Count - 1; i >= 0 && forType == null; i--)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: Check `forType == null` is not necessary since there is an explicit `break;` inside the loop after `forType` is set.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 17]
```diff
@@ -4971,5 +4971,396 @@ public class Program
...
+    public struct Boolean { private Boolean m_value; Boolean Use(Boolean b) { m_value = b; return m_value; } }
+    public struct Int32 { private Int32 m_value; Int32 Use(Int32 b) { m_value = b; return m_value; } }
+    public struct Char { }
+    public class String { }
+}
+namespace System
+{
+    public struct Single
+    {
+        private Single m_value;
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Isn't this field a cycle in `struct Single`?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 18]
```diff
@@ -4971,5 +4971,396 @@ public class Program
...
+        }
+    }
+}
+namespace System
+{
+    public class Object { }
+    public abstract class ValueType { }
+    public struct Void { }
+    public struct Boolean { private Boolean m_value; Boolean Use(Boolean b) { m_value = b; return m_value; } }
+    public struct Int32 { private Int32 m_value; Int32 Use(Int32 b) { m_value = b; return m_value; } }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Are `Boolean` and `Int32` necessary?

File: src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs]: I don't have a belief that this code is unreachable. Having said that, I don't know how to reach it. I'd rather not find out by breaking customer code, when the correct behavior is obvious.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs (hunk 17 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Yes, as required by the CLI specification. And the compiler has special code to accept this so that core libraries can be compiled.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs (hunk 18 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: A pattern-matching operation internally has type `bool`, for example. It is possible that we don't need some part of this; if so, I don't care.

**Comment by cston** [comment]
LGTM

**Comment by gafter** [comment]
@cston I've made changes responsive to your comments. Please let me know if there are any further problems with this change. Since this is principally a change to add test coverage, I didn't take your suggestion to refactor the internal types to use `ValueTuple` instead of `KeyValuePair`.

**Comment by gafter** [comment]
Thanks; our comments crossed in the ether.
