### PR TITLE
Fix several issues with sequence points and switch expressions

### LINKED ISSUE #37232: Compiler emits incorrect EnC closure data to PDB for nested switch expressions
```C#
using System;
public class C
{
    static int M() 
    {
        return F() switch 
        {
            1 => F() switch
                 {
                     C { P: int p, Q: C { P: int q } } => G(() => p + q),
                     _ => 10
                 },
            C { Q: int s } => G(() => s),
            _ => 0
        };
    }

    object P { get; set; }
    object Q { get; set; }
    static object F() => null;
    static int G(Func<int> f) => 0;
}
```

A display class is emitted for each switch expression:
image

`pdb2xml` output:

```xml
...
<encLambdaMap>
  <methodOrdinal>0</methodOrdinal>
  <closure offset="59" />
  <closure offset="59" />
  <lambda offset="255" closure="0" />
  <lambda offset="157" closure="1" />
</encLambdaMap>
...
```

The `offset` attribute of `closure` identifies the syntax node that's associated with the closure. This offset must be unique, but in this case the compiler emits the same value - the offset of the outer switch expression node. 

The lowering creates a spill sequence with locals defined in the switch expression. The spill sequence node is correctly associated with the switch expression syntax at this point.
Later on `SpillSequenceSpiller.VisitSpillSequence` takes these locals and puts them in `BoundSpillSequenceBuilder`. Finally, `SpillSequenceSpiller.UpdateStatement` creates a new `BoundBlock` with these locals. The `BoundBlock` is however no longer associated with the right switch expression syntax node. 

See test See test `PDBTests.Patterns_SwitchExpression_Closures`.

### LINKED ISSUE #37237: Compiler shouldn't emit hidden sequence points on display class creation instruction in expression context
```C#
using System;
public class C
{
    static int M() 
    {
        return F() switch 
        {
            1 => F() switch
                 {
                     C { P: int p, Q: C { P: int q } } => G(() => p + q),
                     _ => 10
                 },
            C { Q: int s } => G(() => s),
            _ => 0
        };
    }

    object P { get; set; }
    object Q { get; set; }
    static object F() => null;
    static int G(Func<int> f) => 0;
}
```

PDB contains sequence points
```xml
      <sequencePoints>
        <entry offset="0x0" startLine="5" startColumn="5" endLine="5" endColumn="6" document="1" />
        <entry offset="0x1" hidden="true" document="1" />
        <entry offset="0x5b" hidden="true" document="1" />
        <entry offset="0x118" startLine="16" startColumn="5" endLine="16" endColumn="6" document="1" />
      </sequencePoints>
```

The one at offset 0x5b shouldn't be emitted since it's in the middle of expression evaluation:

```
  IL_005b:  newobj     instance void C/'<>c__DisplayClass0_1'::.ctor()
```

If we decide to merge closure scopes of the nested switch expressions to fix https://github.com/dotnet/roslyn/issues/37232, this issue will be resolved as well. If we decide to keep both closures then we need to avoid emitting the hidden sequence point on the inner one.

See test `PDBTests.Patterns_SwitchExpression_Closures`.

As it turns out, the outer hidden sequence point is also problematic: see https://github.com/dotnet/roslyn/issues/37261

### LINKED ISSUE #37261: Expression bodied method whose expression is a switch expression is missing debug info
```C#
using System;
public class C
{
    static int M() => F() switch
    {
        1 => 1,
        C { P: int p, Q: C { P: int q } } => G(() => p + q),
        _ => 0
    };

    object P { get; set; }
    object Q { get; set; }
    static object F() => null;
    static int G(Func<int> f) => 0;
}
```

Produces no debug info for method `C.M` (specifically, no sequence points).

Analysis:

`ILBuilder.AllocateILMarker` creates 2 ILMarkers, both at BlockOffset = 0: one user-code sequence point and another hidden one.
`RealizeSequencePoints` uses the last defined sequence point for the offset (the hidden one).
`SequencePointList.GetSequencePoints` then emits no sequence points since the only sequence point in the list is hidden.

The issue is with the hidden sequence point emitted for the switch expression closure.

See `PDBTests.SwitchExpression_MethodBody`.

### LINKED ISSUE #43468: Switch expression stepping not working correctly
**Version Used**: 

**Steps to Reproduce**:

```C#
    class Program
    {
        static void Main(string[] args)
        {
            var x = 1;
            var y = x switch { 1 => /*BP*/2, _ => 3 };
        }
    }
```

1. Place breakpoint as indicated.
2. Step.

**Expected Behavior**:

Steps to `}`.

**Actual Behavior**:

image

Seems like we are missing a hidden sequence point on the artificial conditional branch.

```
  ...
  // (10, 45) - (10, 46)
  IL_0017:  ldc.i4.3
  IL_0018:  stloc.2
  IL_0019:  br.s       IL_001f

  // (10, 53) - (10, 54)
  IL_001b:  ldc.i4.4
  IL_001c:  stloc.2
  IL_001d:  br.s       IL_001f

  // missing <hidden>
  IL_001f:  ldc.i4.1
  IL_0020:  brtrue.s   IL_0023

  // (10, 13) - (10, 57)
  IL_0022:  nop

  // <hidden>
  IL_0023:  ldloc.2
  IL_0024:  stloc.1

  // (11, 9) - (11, 10)
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #37237
Fixes #37232
Fixes #37261
Fixes #43468

### CODE REVIEW

**Comment by gafter** [comment]
There will be one (hopefully last) tweak to these sequence points implemented by a bug fix in the 10th iteration of https://github.com/dotnet/roslyn/pull/43430.

File: src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs [hunk 1]
```diff
@@ -37,8 +37,8 @@ private sealed class BoundSpillSequenceBuilder : BoundExpression
             private ArrayBuilder<LocalSymbol> _locals;
             private ArrayBuilder<BoundStatement> _statements;
 
-            public BoundSpillSequenceBuilder(BoundExpression value = null)
-                : base(SpillSequenceBuilderKind, null, value?.Type)
+            public BoundSpillSequenceBuilder(SyntaxNode syntax, BoundExpression value = null)
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs:40]: `nullable enable` and `SyntaxNode?`

File: src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs [hunk 2]
```diff
@@ -9380,23 +9374,29 @@ .maxstack  2
                     C V_18,
                     object V_19,
                     int V_20)
-     -IL_0000:  nop
-     ~IL_0001:  newobj     ""C.<>c__DisplayClass0_0..ctor()""
+      // sequence point: {
+      IL_0000:  nop
+      // sequence point: <hidden>
```
Comment (agocke) [inline src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs:9379]: Why does the closure class creation get a sequence point? What purpose does that serve in debugging?

Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs:9379]: I believe these will be necessary to enable edit-and-continue for switch expressions. In any case, that didn't change here.  We are just displaying the information in a different format (sequence point comments instead of funny squiggles before the instructions due to the change at line 9353).

---
In reply to: [416899613](https://github.com/dotnet/roslyn/pull/43471#discussion_r416899613) [](ancestors = 416899613)

File: src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs:40]: Not in this PR.

---
In reply to: [416896544](https://github.com/dotnet/roslyn/pull/43471#discussion_r416896544) [](ancestors = 416896544)
