### PR TITLE
Avoid stack overflow due to deep recursion on long chain of calls.

### LINKED ISSUE #67912: Unable to compile project with large amount of grpc proto messages and services
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1754743

_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-compile-project-with-large-amo/10292708)._

---
\[severity:I’m unable to use this version\]  
A .net 4.8 framework solution using GRPC split across 2 projects does not compile and shows the following error:

47>C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\MSBuild\\Current\\Bin\\Roslyn\\Microsoft.CSharp.Core.targets(80,5): error MSB6006: “csc.exe” exited with code -2146232797.

Using protoroot, the grpc contracts are stored in one project and the service implementations are stored in another.

There are about 1300 rpc statements and about 4000 messages.

Note: this compiles successfully in 17.2 and 17.3. Fails with 17.4 and 17.5

The contracts project compiles successfully. The implementation project fails.

---
#### james harvey on 2/27/2023, 02:18 AM: 

(private comment, text removed)
#### james harvey on 2/27/2023, 03:34 AM: 

(private comment, text removed)
#### Feedback Bot on 2/27/2023, 06:25 PM: 

(private comment, text removed)
#### Feedback Bot on 4/11/2023, 11:49 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #67912.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 1]
```diff
@@ -5707,9 +5712,67 @@ private static BoundExpression CreatePlaceholderIfNecessary(BoundExpression expr
...
+                    CheckCallReceiver(receiver, receiverType, node.Method);
+                }
+
+                _expressionIsRead = originalExpressionIsRead;
+
+                calls.Free();
+            }
+            else
+            {
+                TypeWithState receiverType = visitAndCheckReceiver(node);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:5758]: Why don't we need to update/track the expressionIsRead value when dealing with a single invocation?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:5758]: > Why don't we need to update/track the expressionIsRead value when dealing with a single invocation?

Because the calling Visit does that. Above we are setting it for nested calls.

File: src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs [hunk 2]
```diff
@@ -438,10 +439,42 @@ public override BoundNode VisitObjectInitializerMember(BoundObjectInitializerMem
...
+                node = receiver1;
+
+                while (node.ReceiverOpt is BoundCall receiver2)
+                {
+                    calls.Push(node);
+                    node = receiver2;
+                }
+
+                CheckReceiverIfField(node.ReceiverOpt);
+                this.Visit(node.ReceiverOpt);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs:456]: The ordering for these two calls (`CheckReceiverIfField(node.ReceiverOpt)` and `this.Visit(node.ReceiverOpt)`) seems a bit different than in the original code. I'm not sure if it matters...
Is that intentional?

In comparison, the order for single invocation case below matches the previous order:
1. VisitCall
2. CheckReceiverIfField
3. CheckReferenceToMethodIfLocalFunction
4. Visit receiver
5. Visit arguments

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs:456]: As far as I understand there is no order dependency between  Visit and Check methods.

File: src/Compilers/CSharp/Portable/Binder/ExpressionVariableFinder.cs [hunk 3]
```diff
@@ -348,6 +339,50 @@ public override void VisitBinaryExpression(BinaryExpressionSyntax node)
...
+        public override void VisitInvocationExpression(InvocationExpressionSyntax node)
+        {
+            if (receiverIsInvocation(node, out InvocationExpressionSyntax nested))
+            {
+                var invocations = ArrayBuilder<InvocationExpressionSyntax>.GetInstance();
+
+                invocations.Push(node);
+
+                node = nested;
+                if (receiverIsInvocation(node, out nested))
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/ExpressionVariableFinder.cs:351]: It looks like we'll push at most two nodes into the `invocations` queue. Should this be a `while` loop instead?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/ExpressionVariableFinder.cs:351]: > Should this be a while loop instead?

Yes, this is a typo.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/ExpressionVariableFinder.cs:351]:
```suggestion
                while (receiverIsInvocation(node, out nested))
```

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 4]
```diff
@@ -5707,9 +5712,67 @@ private static BoundExpression CreatePlaceholderIfNecessary(BoundExpression expr
...
+
+                calls.Push(node);
+                node = receiver;
+
+                bool originalExpressionIsRead = _expressionIsRead;
+                _expressionIsRead = true;
+
+                while (node.ReceiverOpt is BoundCall receiver2)
+                {
+                    TakeIncrementalSnapshot(node); // Visit does this before visiting each node
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:5727]: I have a general concern about the repetition that occurs in this PR: If we make a change to a method that is referenced by a "// Method does this before visiting each node", I'm concerned that we will not catch all these other places that should also be updated.
I don't have a great solution for this, but maybe it would be useful to add cref comments from those methods back to all the places that duplicate some of the logic.

Comment (jcouv) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:5727]: I guess there's also the broader question of whether the gain is worth all this additional complexity in the codebase. I'm curious what the team thinks (@dotnet/roslyn-compiler for thoughts).

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 4) but would like to get team's opinion

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 4 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:5727]: > I have a general concern about the repetition that occurs in this PR: If we make a change to a method that is referenced by a "// Method does this before visiting each node", I'm concerned that we will not catch all these other places that should also be updated.

We already have to face the same for visiting binary expressions

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs [hunk 5]
```diff
@@ -175,17 +175,67 @@ private static ImmutableArray<MethodSymbol> GetOriginalMethods(OverloadResolutio
...
+
+                    if (!invocations.TryPop(out node))
+                    {
+                        break;
+                    }
+
+                    Debug.Assert(node.Expression.Kind() is SyntaxKind.SimpleMemberAccessExpression);
+                    var memberAccess = (MemberAccessExpressionSyntax)node.Expression;
+                    analyzedArguments.Clear();
+                    VerifyUnchecked(nested, diagnostics, result);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs:205]:
```suggestion
                    VerifyUnchecked(nested, diagnostics, result); // BindExpression does this after calling BindExpressionInternal  
```

[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs]: > I didn't follow where this came from. May be worth a comment

Added a comment

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review

**Review by jaredpar — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Binder/ExpressionVariableFinder.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/ExpressionVariableFinder.cs]: > Shouldn't this be while not if? 

Yes, the typo has been fixed already

File: src/Compilers/CSharp/Portable/Binder/LocalBinderFactory.cs [hunk 6]
```diff
@@ -240,9 +241,49 @@ public override void VisitInvocationExpression(InvocationExpressionSyntax node)
                 return;
             }
 
-            base.VisitInvocationExpression(node);
+            if (receiverIsInvocation(node, out InvocationExpressionSyntax? nested))
```
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/LocalBinderFactory.cs:244]: > ? Did you consider putting a helper directly there that we could access? 

There are only two of them and they are slightly different. I do not think it is worth adding an abstraction across them

File: src/Compilers/CSharp/Portable/BoundTree/BoundTreeWalker.cs [hunk 7]
```diff
@@ -135,5 +135,49 @@ protected BoundTreeWalkerWithStackGuardWithoutRecursionOnTheLeftOfBinaryOperator
...
+                calls.Push(node);
+
+                node = receiver1;
+                while (node.ReceiverOpt is BoundCall receiver2)
+                {
+                    calls.Push(node);
+                    node = receiver2;
+                }
+
+                VisitReceiver(node);
```
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/BoundTree/BoundTreeWalker.cs:154]: > Why isn't this inside the ```do``` loop below? Seems like we miss intermediate ```receiver``` calls as written.

The intermediate ```receiver``` is the previous call and we already visited all interesting parts of it. It is our intention to not call VisitReceiver for them. I'll add a comment.

File: src/Compilers/CSharp/Portable/BoundTree/BoundTreeWalker.cs [hunk 8]
```diff
@@ -135,5 +135,49 @@ protected BoundTreeWalkerWithStackGuardWithoutRecursionOnTheLeftOfBinaryOperator
...
+            else
+            {
+                VisitReceiver(node);
+                VisitArguments(node);
+            }
+
+            return null;
+        }
+
+        protected virtual void VisitReceiver(BoundCall node)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/BoundTreeWalker.cs:173]:
```suggestion
        /// <summary>
        /// Called only for the first (in evaluation order) <see cref="BoundCall"/> in the chain.
        /// </summary>
        protected virtual void VisitReceiver(BoundCall node)
```
