### PR TITLE
make SyntaxFactory.AreEquivalent ignore => bodies if topLevel:true

### LINKED ISSUE #7380: SyntaxFactory.AreEquivalent improperly compares expression-bodied method bodies
The following proposed new unit test (for `SyntaxEquivalenceTests.cs`) fails:

```cs
        [Fact(DisplayName = "https://github.com/dotnet/roslyn/issues/7380")]
        public void TestExpressionBodiedMethod()
        {
            var tree1 = SyntaxFactory.ParseSyntaxTree("class C { void M() => 1; }");
            var tree2 = SyntaxFactory.ParseSyntaxTree("class C { void M() => 2; }");

            VerifyEquivalent(tree1, tree2, topLevel: true);
            VerifyNotEquivalent(tree1, tree2, topLevel: false);
        }
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #7380 
@dotnet/roslyn-compiler Please review this tiny change

### CODE REVIEW

**Comment by sharwell** [comment]
:question: Should the following be equivalent when `topLevel` is true?

```csharp
class C { void M() => 1; }

class C { void M() { return 1; } }
```

:bulb: It would be good to add a test covering this case.

File: src/Compilers/CSharp/Portable/Syntax/SyntaxEquivalence.cs [hunk 1]
```diff
@@ -110,11 +110,13 @@ private static bool AreEquivalentRecursive(GreenNode before, GreenNode after, Fu
 
             if (topLevel)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxEquivalence.cs]: The name "topLevel" is somewhat confusing. At least, I wouldn't guess this is about method bodies.

File: src/Compilers/CSharp/Portable/Syntax/SyntaxEquivalence.cs [hunk 2]
```diff
@@ -110,11 +110,13 @@ private static bool AreEquivalentRecursive(GreenNode before, GreenNode after, Fu
...
             {
-                // Once we get down to the block level we don't need to go any further and we can
+                // Once we get down to the body level we don't need to go any further and we can
                 // consider these trees equivalent.
-                if ((SyntaxKind)before.RawKind == SyntaxKind.Block)
+                switch ((SyntaxKind)before.RawKind)
                 {
-                    return true;
+                    case SyntaxKind.Block:
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxEquivalence.cs]: In general block doesn't mean a method body, is there a guarantee that we are always start "above" bodies?

**Comment by AlekseyTs** [comment]
LGTM. I am not that familiar with this area, but the change appears to make the test to pass.

File: src/Compilers/CSharp/Portable/Syntax/SyntaxEquivalence.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxEquivalence.cs]: The idea of "topLevel" is to check APIs and not "code". Blocks only appear in "code". From what I can see, this is always invoked on a whole compilation unit.

**Comment by gafter** [comment]
@sharwell I am not sure we care whether `=>expr` and `{}` are treated as equivalent for the purposes of this change. I think the way this API is used it is expected to err on the side of conservatism. Since both `=>expr` and `{}` are bodies we could go either way, but treating them as equivalent (when `topLevel` is true) feels like a more accurate result.

Having said that, I agree more test coverage is better.

**Comment by gafter** [comment]
@dotnet-bot test this please

**Comment by gafter** [comment]
@dotnet/roslyn-compiler Can I please have a second review of this tiny change

**Comment by davkean** [comment]
Mac's should be back up:
@dotnet-bot test prtest/mac/dbg/unit32 please

@gafter Do you think that [test failure](http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/2020/testReport/junit/Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics/DiagnosticsSquiggleTaggerProviderTests/TaggerProviderCreatedAfterInitialDiagnosticsReported/) was caused by your change?

**Comment by gafter** [comment]
@dotnet/roslyn-compiler Can I please have a second review of this tiny change?

**Comment by cston** [comment]
LGTM

**Comment by gafter** [comment]
@dotnet-bot test this please

**Comment by gafter** [comment]
@dotnet-bot test this please

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxEquivalenceTests.cs [hunk 3]
```diff
@@ -437,5 +437,15 @@ public void TestUpdateInterpolatedString()
             VerifyEquivalent(tree1, tree2, topLevel: true);
             VerifyNotEquivalent(tree1, tree2, topLevel: false);
         }
+
+        [Fact(DisplayName = "https://github.com/dotnet/roslyn/issues/7380")]
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxEquivalenceTests.cs]: Why `DisplayName` here?  My understanding is issues were always linked with `WorkItem` attributes.  The effect of using this method is that xunit will use this name vs. the method name when displaying this suite.  I don't think that is the intention.  Additionally it will make it more difficult to programitically link suites and bugs.

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxEquivalenceTests.cs [hunk 4]
```diff
@@ -437,5 +437,15 @@ public void TestUpdateInterpolatedString()
...
+        public void TestExpressionBodiedMethod()
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxEquivalenceTests.cs]: What happens if there is a syntax error in the arrow clause?  Should we have a test for that?

Comment (gafter) [inline src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxEquivalenceTests.cs]: Since the arrow clause is not part of the API (when `topLevel:true`), we don't care about the errors. When `topLevel:false`, we retain the old behavior.

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxEquivalenceTests.cs (hunk 3 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxEquivalenceTests.cs]: Darn auto-complete!

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxEquivalenceTests.cs (hunk 4 above)
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxEquivalenceTests.cs]: @gafter do we have a test verifying that?
