### PR TITLE
Fix issues around NotConfigurable diagnostics

### LINKED ISSUE #1473: Fix FilterDiagnostic methods on CSharpDiagnosticFilter and VisualBasicDiagnosticFilter for NotConfigurable diagnostics
The check for IsNotConfigurable here: http://index/#Microsoft.CodeAnalysis.CSharp/Compilation/CSharpDiagnosticFilter.cs,32 means that we end up reporting a NotConfigurable but disabled diagnostic as non-suppressed. We should move that check out of this place and instead have it here: http://index/#Microsoft.CodeAnalysis.CSharp/Compilation/CSharpDiagnosticFilter.cs,90 so that IsEnabledByDefault is respected for NotConfigurable diagnostics.

### PR DESCRIPTION
**Pull request by mavasani**
1. NotConfigurable diagnostic shouldn't be reported if it is disabled ( fixes #1473 )
2. NotConfigurable enabled diagnostics implies analyzer is never suppressed. NotConfigurable disable diagnostics shouldn't participate in deciding whether or not analyzer is suppressed.

See comments in #1379 for more context.

@heejaechang @JohnHamby @shyamnamboodiripad @jmarolf  @tmeschter  @srivatsn  @sharwell please review the change.

### CODE REVIEW

File: src/Compilers/Core/AnalyzerDriver/AnalyzerManager.cs [hunk 1]
```diff
@@ -301,6 +301,20 @@ internal bool IsSupportedDiagnostic(DiagnosticAnalyzer analyzer, Diagnostic diag
 
             foreach (var diag in supportedDiagnostics)
             {
+                if (HasNotConfigurableTag(diag.CustomTags))
```
Comment (shyamnamboodiripad) [inline src/Compilers/Core/AnalyzerDriver/AnalyzerManager.cs]: Consider creating extension method diag.IsNotConfigurable() (similar to what we use in CSharpFilterDiagnostics.cs)

**Comment by sharwell** [comment]
I am obviously :-1: on this. While the current behavior does not match the original expectations of the implementing developers, it (unintentionally) provided an efficient, reliable mechanism for certain features which our analyzers now rely on. The proposed alternatives might be more easily discovered, but each of them comes with overhead in the form of some combination of the following:

* **Decreased usability**: Disabled diagnostics might now be invoked by the analyzer service; in these cases the diagnostic must insert manual checks to see if the diagnostic should be invoked and find a way to conditionally register event listeners.
* **Unwanted items in the UI**: The only way to fully disable an analyzer leveraging "linked diagnostics" is to expose the linked diagnostic as configurable and require that the user configure both diagnostics together.
* **Performance impact for disabled analyzers**: If NotConfigurable diagnostics cannot be reported while they are also disabled by default, then the analyzer service will always make calls to analyzers with this type of linked diagnostic. There will be no way to fully eliminate the overhead associated with a linked diagnostic of this form.

I think #1473 should be intentionally left uncorrected until the current use cases for these diagnostics is directly addressed.

**Comment by mavasani** [comment]
@sharwell I understand your concern. However, the design decision from the team is to have *no explicit* support for linked diagnostics or descriptors. Only scenario where there is a use-case for linked diagnostics/descriptors is for presentation related descriptors, and there is a separate work item to address that. There was never any official support for *linked* diagnostics or descriptors in the analyzer API, the bug fixes here just make this contract very explicit. If an analyzer wishes to have dependencies between descriptors/diagnostics that you report, analyzer must do so itself.

Relying on bugs to get unsupported features is never a good approach. Retaining functionality bugs to improve performance for such extremely rare analyzers is also not a good approach. 

If there is extreme concern about perform of such analyzers, they can check upfront for this. Just create a dummy primary diagnostic and check for its effective severity at beginning of any action callback. Yes, there is no clean performant workaround for your scenario as of now. However, that shouldn't imply that we retain functionality bugs in analyzer driver, as long there is some workaround for a pending feature.

Probably @heejaechang @srivatsn @JohnHamby can comment more on this.

File: src/Compilers/Core/AnalyzerDriver/AnalyzerManager.cs (hunk 1 above)
Comment (mavasani) [inline src/Compilers/Core/AnalyzerDriver/AnalyzerManager.cs]: @shyamnamboodiripad This code lies in the shared AnalyzerDriver project, and it cannot access the internal DiagnosticDescriptor.IsNotConfigurable method when compiled into the Features project.

**Comment by heejaechang** [comment]
@sharwell we appreciate that you start using our diagnostics API early on and building such a nice set of analyzers. but we need to close this otherwise, more and more people start to pig back into this bug (especially, when they see other analyzers doing this cool effect and saw how you guys did it) and we will never be able to close this, and provide proper way to provide this.

we know that current workaround is not ideal, but we are not saying that is something you will stuck with, we just asking some time (or you can even participate on building up proper support in our engine) until we add support this in engine. which will address concern you mentioned above. and doesn't need to add some fake diagnostics just to gray something out in the view.

File: src/Compilers/Core/AnalyzerDriver/AnalyzerManager.cs (hunk 1 above)
Comment (heejaechang) [inline src/Compilers/Core/AnalyzerDriver/AnalyzerManager.cs]: code seems a bit duplicated though. anyway, I guess we don't have a way reduce..

**Comment by heejaechang** [comment]
:+1:

**Comment by tmeschter** [comment]
:+1:

**Comment by sharwell** [comment]
Well you can't blame me for standing up for my devs! :smile: You know we'll make it work.

**Comment by mavasani** [comment]
@sharwell Your opposition is truly understandable, and its unfortunate we ever used such hidden trigger diagnostics for presentation concept in our built-in analyzers itself (remove unnecessary usings). Well, lets wait till you find another sneaky workaround that uncovers another subtle bug :) you guys are really smart at getting around this unsupported feature! Hopefully the underlying missing feature is soon implemented and you folks can implement this in a clean, performant, supported way.
Once again, sorry for the trouble and thanks for reporting all the issues!

**Comment by srivatsn** [comment]
I second Manish. Thanks for all your participation Sam!
