### PR TITLE
Disallow attributes in local function definitions

### LINKED ISSUE #14640: Roslyn doesn't report errors for unknown attributes in local functions' type parameters lists
Roslyn doesn't report any errors for this code sample (it should report unresolved attribute)

``` cs
public class C {
    public static void Main()
    {
        void Local<[A] T>(){}
        Local<int>();
     }
}
```

attempts to compile this code from VS15 Preview 5 ends with following error (which is not very helpful)

```
"csc.exe" exited with code -532462766.
```

currently this test fails 

``` cs
        [Fact]
        public void UnknownAttribute()
        {
            var src = @"
public class C {
    public static void Main()
    {
        void Local<[A] T>(){}
        Local<int>();
     }
}";
          VerifyDiagnostics(src,
            // (5,21): error CS0246: The type or namespace name 'AAttribute' could not be found (are you missing a using directive or an assembly reference?)
            //         void Local<[A] T>(){}
            Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "A").WithArguments("AAttribute").WithLocation(5, 21),
            // (5,21): error CS0246: The type or namespace name 'A' could not be found (are you missing a using directive or an assembly reference?)
            //         void Local<[A] T>(){}
            Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "A").WithArguments("A").WithLocation(5, 21));
        }
```

with following output:

```
Expected:
    Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "A").WithArguments("AAttribute"),
    Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "A").WithArguments("A")
Actual:
```

### PR DESCRIPTION
**Pull request by agocke**
**Scenario**

Mentioning an attribute on a type parameter which doesn't exist, e.g.

```csharp
class C
{
    public void M()
    {
        void Local< [A] T >() {}
    }
}
```
causes the compiler to crash. This also revealed a design hole: attributes
are currently allowed on type parameters and parameters, but not on
the local function itself or its return type.

After the fix attributes will not be permitted on type parameters or parameters of
local functions. This matches the existing behavior for the return type
and symbol itself, neither of which allow attributes to be applied to
them. Also, the compiler no longer crashes in these scenarios and correctly binds the attributes, even if they are invalid.

**Bugs this fixes:** 

Fixes #14640

**Workarounds, if any**

None.

**Risk**

We are disabling specific behavior and the error messages are tested, so this change should be focused narrowly to the problem and not affect anything outside of attributes on parameters/type parameters.

**Performance impact**

None -- the work was being done, but the diagnostics were being discarded.

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

New feature.

**How was the bug found?**

Customer reported.

### CODE REVIEW

**Comment by agocke** [comment]
@dotnet/roslyn-compiler For review

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs [hunk 1]
```diff
@@ -157,6 +157,15 @@ private void ComputeParameters()
 
             var diagnostics = DiagnosticBag.GetInstance();
             SyntaxToken arglistToken;
+
+            foreach (var param in _syntax.ParameterList.Parameters)
+            {
+                foreach (var attrList in param.AttributeLists)
+                {
+                    diagnostics.Add(ErrorCode.ERR_AttributesInLocalFuncDecl, attrList.Location);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: I don't know if we need to report on every single occurrence. Maybe stopping after the first error would be better?

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs [hunk 2]
```diff
@@ -159,10 +159,16 @@ AttributeLocation IAttributeTargetSymbol.AllowedAttributeLocations
...
         }
 
-        internal override CustomAttributesBag<CSharpAttributeData> GetAttributesBag()
+        /// <summary>
+        /// Returns a bag of applied custom attributes and data decoded from well-known attributes. Returns null if there are no attributes applied on the symbol.
+        /// </summary>
+        /// <remarks>
+        /// Forces binding and decoding of attributes.
+        /// </remarks>
+        internal virtual CustomAttributesBag<CSharpAttributeData> GetAttributesBag(DiagnosticBag diagnosticsOpt)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs]: I didn't get why `virtual`.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs [hunk 3]
```diff
@@ -171,12 +177,15 @@ internal override CustomAttributesBag<CSharpAttributeData> GetAttributesBag()
                 var sourceMethod = this.ContainingSymbol as SourceMemberMethodSymbol;
                 if ((object)sourceMethod == null || (object)sourceMethod.SourcePartialDefinition == null)
                 {
-                    lazyAttributesStored = LoadAndValidateAttributes(OneOrMany.Create(this.MergedAttributeDeclarationSyntaxLists), ref _lazyCustomAttributesBag);
+                    lazyAttributesStored = LoadAndValidateAttributes(
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs]: How does `LoadAndValidateAttributes` behave if `diagnosticsOpt` is null?

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs (hunk 2 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs]: I just moved this method up from the base, so rather than `override` this became `virtual`. Note that inheriting classes do override this.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs (hunk 3 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs]: It creates and adds the diagnostics to the declaration diagnostics.

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs (hunk 1 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: If we don't report for every location then you won't get red squigglies in the IDE for each location.

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs [hunk 4]
```diff
@@ -371,6 +385,9 @@ private ImmutableArray<TypeParameterSymbol> MakeTypeParameters(DiagnosticBag dia
                         ImmutableArray.Create(location),
                         ImmutableArray.Create(parameter.GetReference()));
 
+                // Force attribute binding for diagnostics
+                typeParameter.GetAttributesBag(diagnostics);
+
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: We are doing more and more while the symbol is being created, it looks like this function is called from the constructor. This feels dangerous, might potentially be a source of a circularity. We need a symbol to create binders, if we try to bind something at the time the symbol is created, we might try to create the binder again, and so on, and so on. We should avoid performing any binding while we create a symbol for a local function.

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs [hunk 5]
```diff
@@ -371,6 +385,9 @@ private ImmutableArray<TypeParameterSymbol> MakeTypeParameters(DiagnosticBag dia
                         ImmutableArray.Create(location),
                         ImmutableArray.Create(parameter.GetReference()));
 
+                // Force attribute binding for diagnostics
+                typeParameter.GetAttributesBag(diagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: >diagnostics [](start = 47, length = 11)

Where do similar diagnostics for parameters go, what bag?

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs (hunk 4 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: You have in fact pre-empted my change to fix the circularity in binding the default value of parameter symbols. :)

My second PR relies on this one and also moves most of these checks to the GrabDiagnostics method, which I delay calling until the binder has finished creating the symbol.

I will attempt to push some of these changes back into this PR.

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs (hunk 5 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: With my second PR they will go to the same bag -- the one that is passed to `GrabDiagnostics`. I think that makes sense for consistency.

**Comment by controlflow** [comment]
Any explanation on why attributes are disallowed completely now? Language design notes or something?

ReSharper users rely on `[NotNull]`/`[CanBeNull]` annotations to help static analysis and check code for possible null dereference errors, the inability of return type annotation for local methods was already a big hit for us (but I understand the reasons for this: parsing such attributes inside method body is hard) and now you disallow attributes completely.

AOP frameworks also rely on parameter attributes a lot.

Also I constantly see people asking for attribute support on lambda expressions, local functions were kinda nice workaround for them, no this is gone.

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs (hunk 4 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: Consider renaming ```GrabDiagnostics``` to "GetDeclarationDiagnostics" or something similar. In general, we should make sure that diagnostics for a local function declaration never makes its way to the global (Compilation wide) diagnostics bag, which is used to cache declaration errors for regular declarations.

**Comment by jcouv** [comment]
@controlflow The rationale is mostly time/risk constraint at this point. It is better to close a scenario that is  untested or low-confidence than ship it with uncertainty and let people build incorrect expectations (ie depend on bugs). It's a hard call, but it is the right thing to do in the short-term.

@agocke Is enabling this on the table in the future? Maybe open an issue so that we can collect the feedback and requests (it is useful to collect such examples where attributes are valuable on local functions).

**Comment by agocke** [comment]
@controlflow @jcouv No, this is not a scheduling decision. There were existing tests that covered scenarios like this one and there was a previous PR which fixed only this issue rather than disallowing attributes entirely.

This was a design decision due to disallowing attributes on local function symbols and return types. Allowing attributes only in some places is inconsistent, and it was seen to be better to disallow for now, with a plan to enable later, then to allow partial usage.

**Comment by jcouv** [comment]
Thanks for the clarification.

**Comment by agocke** [comment]
@controlflow Btw thanks for lending your feedback on specific use cases. That will help in prioritizing enabling this feature later. This is the kind of thing I could expect to see in a language point release (in the months-rather-than-years time frame).

**Comment by AlekseyTs** [comment]
>                 addTo.AddRange(_lazyParametersAndDiagnostics.Diagnostics);

Not part of this change, but is looks suspicious that we are doing this only when ```diags``` is not default. Same is true for the code below.

---
Refers to: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs:127 in 00759f4. [](commit_id = 00759f4bdbb3313206a41c985594153d371c59d4, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs [hunk 6]
```diff
@@ -157,6 +163,15 @@ private void ComputeParameters()
 
             var diagnostics = DiagnosticBag.GetInstance();
             SyntaxToken arglistToken;
+
+            foreach (var param in _syntax.ParameterList.Parameters)
+            {
+                foreach (var attrList in param.AttributeLists)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: >foreach (var attrList in param.AttributeLists) [](start = 16, length = 46)

Are we binding the attributes? Where do the binding errors go?

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 7]
```diff
@@ -32,6 +31,116 @@ internal void VerifyDiagnostics(string source, CSharpCompilationOptions options,
...
+class C
+{
+    public void M()
+    {
+        void Local<[A, B, CLSCompliant, D]T>() { }
+        Local<int>();
+    }
+}");
+            var comp = CreateCompilationWithMscorlib(tree);
+            comp.VerifyDiagnostics(
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: >comp.VerifyDiagnostics( [](start = 12, length = 23)

Should also verify that none of the errors end up in DeclarationDiagnostics.

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 8]
```diff
@@ -32,6 +31,116 @@ internal void VerifyDiagnostics(string source, CSharpCompilationOptions options,
...
         [Fact]
+        public void LocalFunctionAttributeOnTypeParameter()
+        {
+            var tree = SyntaxFactory.ParseSyntaxTree(@"
+using System;
+class C
+{
+    public void M()
+    {
+        void Local<[A, B, CLSCompliant, D]T>() { }
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: >[A, B, CLSCompliant, D] [](start = 19, length = 23)

Should test SemanticModel behavior on attribute types and attribute parameters.

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 9]
```diff
@@ -32,6 +31,116 @@ internal void VerifyDiagnostics(string source, CSharpCompilationOptions options,
...
+class C
+{
+    public void M()
+    {
+        void Local([A, B]int x, [CLSCompliant]string s = """") { }
+        Local(0);
+    }
+}");
+            var comp = CreateCompilationWithMscorlib(tree);
+            comp.VerifyDiagnostics(
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: >comp.VerifyDiagnostics( [](start = 12, length = 23)

Should also verify that none of the errors end up in DeclarationDiagnostics.

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 10]
```diff
@@ -32,6 +31,116 @@ internal void VerifyDiagnostics(string source, CSharpCompilationOptions options,
...
+        [Fact]
+        public void LocalFunctionAttributeOnParameters()
+        {
+            var tree = SyntaxFactory.ParseSyntaxTree(@"
+using System;
+class C
+{
+    public void M()
+    {
+        void Local([A, B]int x, [CLSCompliant]string s = """") { }
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: >[A, B]int x, [CLSCompliant] [](start = 19, length = 27)

Should test SemanticModel behavior on attribute types and attribute parameters.

**Comment by AlekseyTs** [comment]
Consider adjusting all relevant local function tests to verify that none of the local function diagnostics end up in a global declaration bag.

**Comment by AlekseyTs** [comment]
Done with review pass.

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs (hunk 6 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: This is fixed in the next PR, where attribute binding is done after we compute the parameters above.

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs (hunk 8 above)
Comment (agocke) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: @AlekseyTs I use model.GetDeclaredSymbol to fetch and assert the attribute symbol below, was that similar to what you were thinking?

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs (hunk 10 above)
Comment (agocke) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: This test also uses model.GetDeclaredSymbol. Does that work?

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs (hunk 6 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: The parameter symbol itself is binding the attributes and they go into the bag which is passed to the constructor.

In the second PR, this "strict" symbol is removed entirely and the attribute forcing code is moved into this method.

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs [hunk 11]
```diff
@@ -348,6 +364,11 @@ private ImmutableArray<TypeParameterSymbol> MakeTypeParameters(DiagnosticBag dia
                 var location = identifier.GetLocation();
                 var name = identifier.ValueText;
 
+                foreach (var attr in parameter.AttributeLists)
+                {
+                    diagnostics.Add(ErrorCode.ERR_AttributesInLocalFuncDecl, attr.Location);
+                }
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: Consider extracting a helper method for the loop, for use here and in `ComputeParameters`.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs (hunk 3 above)
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs]: Does that mean there's a race condition where the diagnostics are either added to a bag passed as an argument or to the declaration diagnostics, depending on which call is first? Is there a reason to pass in a bag rather than adding to declaration diagnostics always?

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs (hunk 8 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: No, we should test SemanticModel for the syntax that is part of the attribute application. The APIs that we should test are: GetTypeInfo, GetSymbolInfo, GetAliasInfo, Lookup...

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs (hunk 10 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: It doesn't test behavior for the attribute syntax.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs (hunk 3 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs]: This is a method body diagnostics, it shouldn't go into the declaration diagnostics. We might indeed  have a race here if it is possible to get symbol (perhaps through SemanticModel) before binding the Local Function statement and then look at attributes off of symbols.

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 12]
```diff
@@ -32,6 +31,119 @@ internal void VerifyDiagnostics(string source, CSharpCompilationOptions options,
...
+class C
+{
+    public void M()
+    {
+        void Local<[A, B, CLSCompliant, D]T>() { }
+        Local<int>();
+    }
+}");
+            var comp = CreateCompilationWithMscorlib(tree);
+            comp.DeclarationDiagnostics.Verify();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: >comp.DeclarationDiagnostics.Verify(); [](start = 12, length = 37)

Could you also assert this at the end of the test to make sure examining symbols doesn't add anything? Same for the other test.

Comment (agocke) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: Done.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs (hunk 3 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs]: I managed to expose the inconsistency in the error reporting (strictly speaking it is not a race), see modified unit-test below (we should have similar tests for other diagnostics reported by symbols). The unmodified test doesn't expose the problem because there is a bug in implementation of GetDeclaredSymbol for local functions. It binds the declaration node and gets symbol from it, instead it should simply get symbol from the enclosing binder, similar to how it is done for locals. 
```
        [Fact]
        public void LocalFunctionAttributeOnTypeParameter()
        {
            var tree = SyntaxFactory.ParseSyntaxTree(@"
using System;
class C
{
    public void M()
    {
        void Local<[A, B, CLSCompliant, D]T>() 
        {
            var x = new object(); 
        }
        Local<int>();
    }
}");
            var comp = CreateCompilationWithMscorlib(tree);
            comp.DeclarationDiagnostics.Verify();
            comp.VerifyDiagnostics(
                // (7,20): error CS8204: Attributes are not allowed on local function parameters or type parameters
                //         void Local<[A, B, CLSCompliant, D]T>() { }
                Diagnostic(ErrorCode.ERR_AttributesInLocalFuncDecl, "[A, B, CLSCompliant, D]").WithLocation(7, 20),
                // (7,21): error CS0246: The type or namespace name 'AAttribute' could not be found (are you missing a using directive or an assembly reference?)
                //         void Local<[A, B, CLSCompliant, D]T>() { }
                Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "A").WithArguments("AAttribute").WithLocation(7, 21),
                // (7,21): error CS0246: The type or namespace name 'A' could not be found (are you missing a using directive or an assembly reference?)
                //         void Local<[A, B, CLSCompliant, D]T>() { }
                Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "A").WithArguments("A").WithLocation(7, 21),
                // (7,24): error CS0246: The type or namespace name 'BAttribute' could not be found (are you missing a using directive or an assembly reference?)
                //         void Local<[A, B, CLSCompliant, D]T>() { }
                Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "B").WithArguments("BAttribute").WithLocation(7, 24),
                // (7,24): error CS0246: The type or namespace name 'B' could not be found (are you missing a using directive or an assembly reference?)
                //         void Local<[A, B, CLSCompliant, D]T>() { }
                Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "B").WithArguments("B").WithLocation(7, 24),
                // (7,41): error CS0246: The type or namespace name 'DAttribute' could not be found (are you missing a using directive or an assembly reference?)
                //         void Local<[A, B, CLSCompliant, D]T>() { }
                Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "D").WithArguments("DAttribute").WithLocation(7, 41),
                // (7,41): error CS0246: The type or namespace name 'D' could not be found (are you missing a using directive or an assembly reference?)
                //         void Local<[A, B, CLSCompliant, D]T>() { }
                Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "D").WithArguments("D").WithLocation(7, 41),
                // (7,27): error CS7036: There is no argument given that corresponds to the required formal parameter 'isCompliant' of 'CLSCompliantAttribute.CLSCompliantAttribute(bool)'
                //         void Local<[A, B, CLSCompliant, D]T>() { }
                Diagnostic(ErrorCode.ERR_NoCorrespondingArgument, "CLSCompliant").WithArguments("isCompliant", "System.CLSCompliantAttribute.CLSCompliantAttribute(bool)").WithLocation(7, 27));


            var model = comp.GetSemanticModel(tree);

            var x = tree.GetRoot().DescendantNodes().OfType<VariableDeclaratorSyntax>().Where(v => v.Identifier.ValueText == "x").Single();
            var localSymbol = (LocalFunctionSymbol)model.GetDeclaredSymbol(x).ContainingSymbol;
            var typeParam = localSymbol.TypeParameters.Single();
            var attrs = typeParam.GetAttributes();

            Assert.True(attrs[0].AttributeClass.IsErrorType());
            Assert.True(attrs[1].AttributeClass.IsErrorType());
            Assert.False(attrs[2].AttributeClass.IsErrorType());
            Assert.Equal(comp.GlobalNamespace
                             .GetMember<NamespaceSymbol>("System")
                             .GetMember<NamedTypeSymbol>("CLSCompliantAttribute"),
                attrs[2].AttributeClass);
            Assert.True(attrs[3].AttributeClass.IsErrorType());
            comp.DeclarationDiagnostics.Verify();
        }
``` 

There is a bunch of DeclarationDiagnostics at the end of the test.

Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs]: @AlekseyTs I added your test and am working to fix it, but I don't understand how `GetDeclaredSymbol` is the problem here. It looks like diagnostics are only gathered in `BindStatement`, which is not called through any pathway in the semantic model. Shouldn't I force diagnostics in that code path as well (and then throw them away)?

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs]: > I don't understand how GetDeclaredSymbol is the problem here.

GetDeclaredSymbol is not a source of this problem. I am just saying that implementation of GetDeclaredSymbol for local functions has a separate problem, it is not supposed to perform any binding. SemanticModel is supposed to do the minimal possible amount of work to perform the task. The task can be performed without binding, therefore we shouldn't bind in order to find the symbol. Difference in behavior between my test and your test exposes the problem, makes it observable.

> Shouldn't I force diagnostics in that code path as well (and then throw them away)? 

I don't think so. The problem is that for local functions (their parameters, type parameters, etc.) we are reusing symbols that are designed for regular declarations. Part of design for them is that they spill all diagnostics eagerly into global declaration bag. That should never be done for local functions, all diagnostics should be channeled through GetDeclarationDiagnostics(bag) method, no matter what is the order in which symbol APIs are accessed.

Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs]: @AlekseyTs OK, that makes more sense. I do think that this is a problem but is out of the scope of this PR.

I'm going to file another bug for fixing this since it will require some significant refactoring of parameter symbols.

**Comment by agocke** [comment]
@AlekseyTs I think I've addressed your concerns

**Comment by agocke** [comment]
@AlekseyTs Ping :)

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 13]
```diff
@@ -32,6 +31,304 @@ internal void VerifyDiagnostics(string source, CSharpCompilationOptions options,
...
+                .Where(id => id.Identifier.ValueText == "CLSCompliant")
+                .Single();
+            var clsCompliantSymbol = comp.GlobalNamespace
+                .GetMember<NamespaceSymbol>("System")
+                .GetTypeMember("CLSCompliantAttribute");
+
+            Assert.Null(model.GetDeclaredSymbol(clsCompliant));
+
+            var clsCompliantSymbolInfo = model.GetSymbolInfo(clsCompliant);
+            Assert.Null(clsCompliantSymbolInfo.Symbol);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: >Assert.Null(clsCompliantSymbolInfo.Symbol); [](start = 12, length = 43)

Is this consistent with behavior outside of a method body?

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 14]
```diff
@@ -32,6 +31,304 @@ internal void VerifyDiagnostics(string source, CSharpCompilationOptions options,
...
+            Assert.Equal(clsCompliantSymbol.GetMember<MethodSymbol>(".ctor"),
+                clsCompliantSymbolInfo.CandidateSymbols.Single());
+            Assert.Equal(CandidateReason.OverloadResolutionFailure, clsCompliantSymbolInfo.CandidateReason);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: >Assert.Equal(CandidateReason.OverloadResolutionFailure, clsCompliantSymbolInfo.CandidateReason); [](start = 12, length = 96)

Is this correct? Are there any errors reported for the attribute application?

**Comment by AlekseyTs** [comment]
LGTM, assuming we have issues tracking problems outlined in https://github.com/dotnet/roslyn/pull/16498#discussion_r97137306 and  https://github.com/dotnet/roslyn/pull/16498#issuecomment-273894190.

**Comment by agocke** [comment]
I've filed issues https://github.com/dotnet/roslyn/issues/16699 and https://github.com/dotnet/roslyn/issues/16652 to address the two unrelated issues that @AlekseyTs pointed out.

**Comment by agocke** [comment]
@MattGertz For escrow approval

**Comment by natidea** [comment]
Approved to merge via [369810](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/369810)
