### PR TITLE
fix ref returns in expression bodied local functions

### LINKED ISSUE #42259: Roslyn didn't report CS8333 for local function.
**Version Used**: 
VS 16.5.0 Preview 5.0

**Steps to Reproduce**:
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQGAzAATakDCpA3oaQ+TkuSqQLICGAlgHYAUASjoFGY0rABmpPgBdSnUgF4JMae35ZBAbnriGUmb3nBlq9f2I69+jDgCc/TgGpg10ftI3xhuR358RvLcgsoAfOYyuh4MAL7eAPQJvsb+gX4h4ZHc0bFAA
```cs
    static void Main(){
        ref int a = ref M(2);
        ref int b = ref M(3);
        Console.WriteLine(a+b);
        
        ref int M(in int i) => ref i;
    }
    //ref int M(in int i) => ref i;
```

**Expected Behavior**:
Also report CS8333 as it does for normal functions.
`error CS8333: Cannot return variable 'in int' by writable reference because it is a readonly variable`

**Actual Behavior**:
Code compile without any error, but it return an ref of local var from inner stack.
And it may lead to unexpected behavior(for the above code, get 6 in netcoreapp3.1, and 5 for net472).

Update: 
CS8333 will also be reported if the local function is defined as block instead of expression.
```cs
    static void Main(){
        ref int a = ref M(2);
        ref int b = ref M(3);
        Console.WriteLine(a+b);
        
        ref int M(in int i) {
            return ref i;
        }
    }
```

### PR DESCRIPTION
**Pull request by YairHalberstadt**
Fix #42259 caused by use of incorrect binder when checking ref return type.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 1]
```diff
@@ -3163,9 +3163,8 @@ private static bool IsValidExpressionBody(SyntaxNode expressionSyntax, BoundExpr
             Binder bodyBinder = this.GetBinder(expressionBody);
             Debug.Assert(bodyBinder != null);
 
-            RefKind refKind = RefKind.None;
-            ExpressionSyntax expressionSyntax = expressionBody.Expression.CheckAndUnwrapRefExpression(diagnostics, out refKind);
-            BindValueKind requiredValueKind = GetRequiredReturnValueKind(refKind);
+            ExpressionSyntax expressionSyntax = expressionBody.Expression.CheckAndUnwrapRefExpression(diagnostics, out var refKind);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: >var [](start = 119, length = 3)

Please revert the change. At the very least the type of the out declaration should be spelled out

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 2]
```diff
@@ -3163,9 +3163,8 @@ private static bool IsValidExpressionBody(SyntaxNode expressionSyntax, BoundExpr
...
+            BindValueKind requiredValueKind = bodyBinder.GetRequiredReturnValueKind(refKind);
             BoundExpression expression = bodyBinder.BindValue(expressionSyntax, diagnostics, requiredValueKind);
             expression = ValidateEscape(expression, Binder.ExternalScope, refKind != RefKind.None, diagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: >ValidateEscape [](start = 25, length = 14)

It looks like this is an instance method. Let's use ```bodyBinder``` to call it as well. Since it is very easy to make a mistake and call something on ```this```, consider extracting a helper method, either a static local function, or a new instance method which will be called with only the right binder available to them.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefLocalsAndReturnsTests.cs [hunk 3]
```diff
@@ -313,6 +313,60 @@ class C
...
+        ref int M1(in int i) => ref i;
+        ref int M2(in int i) { return ref i; }
+        ref readonly int M3(in int i) => ref i;
+        ref readonly int M4(in int i) { return ref i; }
+    }
+}";
+            CreateCompilation(source).VerifyDiagnostics(
+                // (4,17): warning CS8321: The local function 'M1' is declared but never used
+                //         ref int M1(in int i) => ref i;
+                Diagnostic(ErrorCode.WRN_UnreferencedLocalFunction, "M1").WithArguments("M1").WithLocation(4, 17),
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefLocalsAndReturnsTests.cs]: >WRN_UnreferencedLocalFunction [](start = 37, length = 29)

Consider adding a ```#pragma``` to disable this warning for the test scenario.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefLocalsAndReturnsTests.cs [hunk 4]
```diff
@@ -313,6 +313,60 @@ class C
...
+        }
+
+        [Fact, WorkItem(42259, "https://github.com/dotnet/roslyn/issues/42259")]
+        public void RefReadonlyReturnLocalFunction()
+        {
+            var source = @"
+class C {
+    ref int M(){
+        throw new System.Exception();
+        ref readonly int M1(in int i) => ref i;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefLocalsAndReturnsTests.cs]: >ref readonly int M1(in int i) => ref i; [](start = 8, length = 39)

It looks like these scenarios are tested above? Is there something special about this specific scenario?

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefLocalsAndReturnsTests.cs [hunk 5]
```diff
@@ -313,6 +313,60 @@ class C
...
+        ref readonly int M2(in int i) { return ref i; }
+    }
+}";
+            CreateCompilation(source).VerifyDiagnostics(
+                    // (5,26): warning CS8321: The local function 'M1' is declared but never used
+                    //         ref readonly int M1(in int i) => ref i;
+                    Diagnostic(ErrorCode.WRN_UnreferencedLocalFunction, "M1").WithArguments("M1").WithLocation(5, 26),
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefLocalsAndReturnsTests.cs]: >WRN_UnreferencedLocalFunction [](start = 41, length = 29)

Same comment, consider adding usage, or disabling the warning with pragma.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 2)

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefLocalsAndReturnsTests.cs (hunk 4 above)
Comment (YairHalberstadt) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefLocalsAndReturnsTests.cs]: This is a different bug caused by the same underlying issue, namely https://github.com/dotnet/roslyn/issues/42259#issuecomment-597283942

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefLocalsAndReturnsTests.cs [hunk 6]
```diff
@@ -313,6 +313,43 @@ class C
...
+        ref readonly int M4(in int i) { return ref i; }
+    }
+}";
+            CreateCompilation(source).VerifyDiagnostics(
+                    // (5,37): error CS8333: Cannot return variable 'in int' by writable reference because it is a readonly variable
+                    //         ref int M1(in int i) => ref i;
+                    Diagnostic(ErrorCode.ERR_RefReturnReadonlyNotField, "i").WithArguments("variable", "in int").WithLocation(5, 37),
+                    // (6,43): error CS8333: Cannot return variable 'in int' by writable reference because it is a readonly variable
+                    //         ref int M2(in int i) { return ref i; }
+                    Diagnostic(ErrorCode.ERR_RefReturnReadonlyNotField, "i").WithArguments("variable", "in int").WithLocation(6, 43));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefLocalsAndReturnsTests.cs]: >); [](start = 132, length = 2)

Consider moving ```);``` on a new line. Makes it easier to add/remove expected diagnostics in the future. Also, it looks like the lines we shifted to the right on an extra tab in the 3rd commit. We usually use single tab (4 spaces) offset.

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 7]
```diff
@@ -3163,13 +3163,19 @@ private static bool IsValidExpressionBody(SyntaxNode expressionSyntax, BoundExpr
...
-            RefKind refKind = RefKind.None;
-            ExpressionSyntax expressionSyntax = expressionBody.Expression.CheckAndUnwrapRefExpression(diagnostics, out refKind);
-            BindValueKind requiredValueKind = GetRequiredReturnValueKind(refKind);
-            BoundExpression expression = bodyBinder.BindValue(expressionSyntax, diagnostics, requiredValueKind);
-            expression = ValidateEscape(expression, Binder.ExternalScope, refKind != RefKind.None, diagnostics);
+            return BindExpressionBodyAsBlockInternal(expressionBody, bodyBinder, diagnostics);
 
-            return bodyBinder.CreateBlockFromExpression(expressionBody, bodyBinder.GetDeclaredLocalsForScope(expressionBody), refKind, expression, expressionSyntax, diagnostics);
+            // Use static local function to prevent accidentally calling instance methods on `this` instead of `bodyBinder`
+            static BoundBlock BindExpressionBodyAsBlockInternal(ArrowExpressionClauseSyntax expressionBody, Binder bodyBinder, DiagnosticBag diagnostics)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: >BindExpressionBodyAsBlockInternal [](start = 30, length = 33)

We have a convention to start names of local functions with a small letter.

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 8]
```diff
@@ -3163,13 +3163,19 @@ private static bool IsValidExpressionBody(SyntaxNode expressionSyntax, BoundExpr
             Binder bodyBinder = this.GetBinder(expressionBody);
             Debug.Assert(bodyBinder != null);
 
-            RefKind refKind = RefKind.None;
-            ExpressionSyntax expressionSyntax = expressionBody.Expression.CheckAndUnwrapRefExpression(diagnostics, out refKind);
-            BindValueKind requiredValueKind = GetRequiredReturnValueKind(refKind);
-            BoundExpression expression = bodyBinder.BindValue(expressionSyntax, diagnostics, requiredValueKind);
-            expression = ValidateEscape(expression, Binder.ExternalScope, refKind != RefKind.None, diagnostics);
+            return BindExpressionBodyAsBlockInternal(expressionBody, bodyBinder, diagnostics);
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]:
```suggestion
            return bindExpressionBodyAsBlockInternal(expressionBody, bodyBinder, diagnostics);
```

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs (hunk 7 above)
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]:
```suggestion
            static BoundBlock bindExpressionBodyAsBlockInternal(ArrowExpressionClauseSyntax expressionBody, Binder bodyBinder, DiagnosticBag diagnostics)
```

**Comment by YairHalberstadt** [comment]
@jaredpar Done

**Comment by AlekseyTs** [comment]
@YairHalberstadt Thanks for the contribution.
