### PR TITLE
Fix parsing of 'file[]' and 'required[]' in old language versions

### LINKED ISSUE #66646: Visual Studio 17.4 Incorrect Enforcing of New Breaking Change in Earlier C# Versions
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-174-Enforcing-of-File-Key/10260528)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.3]
Visual Studio 2022 version 17.4 and above contains a breaking change for C# 11 and the use of the word "file" which is now reserved:

https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/breaking-changes/compiler%20breaking%20changes%20-%20dotnet%207#types-cannot-be-named-file

However, this is incorrectly being enforced in earlier versions of C# and breaks existing builds. In this case we use .NET Framework 4.8 with C# 7.3. See attached screenshots and the attached solution which demonstrates the problem.

[breaking_change_err.png](https://aka.ms/dc/file?name=B899cb9e658574c47801e3a758a5b4fb2638101572133334642_breaking_change_err.png&tid=899cb9e658574c47801e3a758a5b4fb2638101572133334642)
[breaking_change_err_02.png](https://aka.ms/dc/file?name=B238dcf7628224c439844904d93a2900b638101572256796962_breaking_change_err_02.png&tid=238dcf7628224c439844904d93a2900b638101572256796962)

---
#### Feedback Bot on 1/27/2023, 10:07 PM: 

(private comment, text removed)
#### Feedback Bot on 1/31/2023, 05:29 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #66646

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 1]
```diff
@@ -1291,13 +1291,12 @@ private bool ShouldContextualKeywordBeTreatedAsModifier(bool parsingStatementNot
...
             // anything other than async methods are detected as erroneous later, during the define phase
-            // The comments in general were not updated to add "async or required" everywhere to preserve
-            // history, but generally wherever async occurs, it can also be required.
+            // Generally wherever we refer to 'async' here, it can also be 'required' or 'file'.
 
             if (!parsingStatementNotDeclaration)
             {
                 var currentTokenKind = this.CurrentToken.Kind;
-                if (IsPossibleStartOfTypeDeclaration(currentTokenKind) ||
+                if ((IsPossibleStartOfTypeDeclaration(currentTokenKind) && currentTokenKind != SyntaxKind.OpenBracketToken) ||
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:1299]: what happens with other sorts of suffixes?  like `?` and `*`?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:1299]: We do the right thing in those cases. I think the issue here is `IsPossibleStartOfTypeDeclaration` is the wrong helper to use here. That helper tells us if we might be at the start of an attribute list, or start of a modifier list, or at a type declaration keyword like `class`/`struct`.

I think what we actually want to know is, is this a non-contextual modifier or a type declaration keyword like `class`/`struct`/etc. Since there's no valid case in which this contextual keyword would be followed by an attribute list.

Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:1299]: can you document this explicitly (and make sure we have tests here if not already present).

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 2]
```diff
@@ -325,6 +325,7 @@ internal CompilationUnitSyntax ParseCompilationUnitCore()
             }
         }
 
+        /// <summary>Are we possibly at the start of an attribute list, or at a modifier which is valid on a type, or on a keyword of a type declaration?</summary>
         private static bool IsPossibleStartOfTypeDeclaration(SyntaxKind kind)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:329]: Note that the usage of this method on line 1187 (ParseModifiers) really is "is this a valid modifier for a type declaration".

It really makes one wish for reusable/composable patterns, versus being tempted to copy/paste this switch statement around.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:329]: The only fully valid usage of this method IMO is in IsPossibleNamespaceMemberDeclaration.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: Done, thanks

File: src/Compilers/CSharp/Test/Syntax/Parsing/ExpressionParsingTests.cs [hunk 3]
```diff
@@ -1367,6 +1367,45 @@ public void TestNewArray()
             Assert.Null(ac.Initializer);
         }
 
+        [Fact]
+        public void TestNewPartialArray()
+        {
+            UsingTree("new partial[1]");
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Syntax/Parsing/ExpressionParsingTests.cs:1373]: This used to parse as a bad member declaration, as if it were `new partial` followed by an attribute list, which doesn't really make sense.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Syntax/Parsing/ExpressionParsingTests.cs:1373]: Might want to check the behavior of `new file[1]` and `new required[1]` at the top level as well.

**Comment by RikkiGibson** [comment]
As part of this issue I found (I think) that we regressed scenarios like `new required();` as a top level statement (which I think worked in C# 9 but not 11).

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 4]
```diff
@@ -8062,7 +8068,7 @@ private bool IsPossibleNewExpression()
 
                 // class, struct, enum, interface keywords, but also other modifiers that are not allowed after 
                 // partial keyword but start class declaration, so we can assume the user just swapped them.
-                if (IsPossibleStartOfTypeDeclaration(PeekToken(2).Kind))
+                if (IsTypeModifierOrTypeKeyword(PeekToken(2).Kind))
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs:8071]: 2 things to note:
1. this helper is only called for ParseMemberDeclarationOrStatement. i.e., top-level declarations that could either be a member or a statement.
2. The intent here seems to be to ask: are we looking at `new partial` followed by something which indicates this is part of a member declaration. `new partial [` isn't going to parse as a single member declaration. `new partial MODIFIER` is not valid, but we still try to keep going and parse as a member declaration in such a case

This probably doesn't behave well when `new partial` is followed by a contextual keyword like `new partial file ...`. That is still an error case at this point, though, so it just means our error recovery won't be the best. Eventually I'm sure we'll do the work to relax partial modifier ordering, at which point we might be able to refactor a bunch of this code, and maybe do something like "parse the modifiers and see if we had a partial modifier. if it's not the last modifier then do a LangVersion check".

File: src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs [hunk 5]
```diff
@@ -1870,6 +1870,373 @@ public void RequiredModifierIncompleteMember_05()
             EOF();
         }
 
+        [Fact]
+        public void TypeNamedRequired_CSharp10()
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs:1874]: There's no type named required in this test, unlike the file version :).

**Review by 333fred — APPROVED** [review]

File: src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs (hunk 5 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs:1874]: I'll add back 'class required' here, perhaps it's helpful to be clear about how it parses in each language version.

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler for a second review

**Comment by RikkiGibson** [comment]
Missed the window for 17.5, so will merge to 17.6 to start with.

File: src/Compilers/CSharp/Test/Syntax/Parsing/ExpressionParsingTests.cs [hunk 6]
```diff
@@ -1367,6 +1367,503 @@ public void TestNewArray()
...
+                }
+                N(SyntaxKind.EndOfFileToken);
+            }
+            EOF();
+        }
+
+        [Theory]
+        [InlineData("file")]
+        [InlineData("required")]
+        public void TopLevel_NewContextualKeywordArray(string keyword)
```
Comment (cston) [inline src/Compilers/CSharp/Test/Syntax/Parsing/ExpressionParsingTests.cs:1536]: >TopLevel_NewContextualKeywordArray [](http://example.com/codeflow?start=20&length=34)

Consider adding `[InlineData("async")]` or a separate test if `async` is parsed differently than the other cases here.

File: src/Compilers/CSharp/Test/Syntax/Parsing/FileModifierParsingTests.cs [hunk 7]
```diff
@@ -1538,6 +1538,486 @@ class @file { }
...
 
+    [Fact]
+    public void TypeNamedFile_03_CSharp10()
+    {
+        UsingNode($$"""
+            public struct file { public int item; }
+
+            public unsafe class C
+            {
+                public file _file;
```
Comment (cston) [inline src/Compilers/CSharp/Test/Syntax/Parsing/FileModifierParsingTests.cs:1549]: >public [](http://example.com/codeflow?start=16&length=6)

Consider testing the same class declaration but without the `public` modifier on the fields.

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Test/Syntax/Parsing/FileModifierParsingTests.cs (hunk 7 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Syntax/Parsing/FileModifierParsingTests.cs:1549]: I feel this is adequately covered by `TypeNamedRequired_CSharp10` and `TypeNamedRequired_CSharp11`

**Review by cston — APPROVED** [review]
