### PR TITLE
Harden compilers against misplaced global code plus some clean-up around ScriptClass.

### LINKED ISSUE #10023: semanticModel.GetSymbolInfo throws internal NullReferenceException
**Version Used**: 
NuGet package "Microsoft.CodeAnalysis": "1.2.0-rc"

**Steps to Reproduce**:

Create a console app, add a reference to Microsoft.CodeAnalysis NuGet package, and write the following code inside Sub Main():

``` vb
Dim ref = MetadataReference.CreateFromFile(GetType(Object).Assembly.Location)
Dim code = "System.Console.WriteLine();"
Dim compilationUnit = CSharp.SyntaxFactory.ParseCompilationUnit(code, options:=New CSharp.CSharpParseOptions(kind:=SourceCodeKind.Script))
Dim syntaxTree = compilationUnit.SyntaxTree
Dim compilation = CSharp.CSharpCompilation.Create("dummyAssemblyName", {syntaxTree}, {ref})
Dim semanticModel = compilation.GetSemanticModel(syntaxTree, True)
Dim node1 = TryCast(syntaxTree.GetRoot(), CSharp.Syntax.CompilationUnitSyntax)
Dim node2 = TryCast(node1.Members.First, CSharp.Syntax.GlobalStatementSyntax)
Dim node3 = TryCast(node2.Statement, CSharp.Syntax.ExpressionStatementSyntax)
Dim node4 = TryCast(node3.Expression, CSharp.Syntax.InvocationExpressionSyntax)
Dim node5 = TryCast(node4.Expression, CSharp.Syntax.MemberAccessExpressionSyntax)
Console.WriteLine(node5.Name) ' "WriteLine"
Dim writelineInfo = semanticModel?.GetSymbolInfo(node5.Name) ' throws NullReferenceException
```

**Expected Behavior**:

I think that semanticModel.GetSymbolInfo(node) should never throw a NullReferenceException when given a non-null node. The API has other well-defined ways for returning a failed lookup.

**Actual Behavior**:

It throws a NullReferenceException.

I don't even know the meaning of this exception, and don't know why it's being triggered in this case but not in others.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #10023.

@dotnet/roslyn-compiler, @cston, @tmat  Please review.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs [hunk 1]
```diff
@@ -1181,13 +1181,42 @@ internal new NamedTypeSymbol ScriptClass
         /// <returns>The Script class symbol or null if it is not defined.</returns>
         private ImplicitNamedTypeSymbol BindScriptClass()
         {
-            if (_options.ScriptClassName == null || !_options.ScriptClassName.IsValidClrTypeName())
+            string scriptClassName = _options.ScriptClassName ?? "";
+
+            string[] parts = scriptClassName.Split('.');
```
Comment (tmat) [inline src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs]: Perhaps extract this logic to ```NamedTypeSymbol GetNamedTypeByQualifiedName(string)```

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs [hunk 2]
```diff
@@ -1011,10 +1011,11 @@ private MemberSemanticModel CreateMemberModel(CSharpSyntaxNode node)
 
                 case SyntaxKind.GlobalStatement:
                     {
-                        Debug.Assert(!this.IsRegularCSharp);
                         var parent = node.Parent;
                         // TODO (tomat): handle misplaced global statements
```
Comment (tmat) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs]: Is the TODO still relevant?

File: src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs]: So far there is only one use and the code is not general.

File: src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs [hunk 3]
```diff
@@ -958,5 +958,178 @@ public void FixedBuffer_02()
                 Diagnostic(ErrorCode.ERR_UnsafeNeeded, "x[3]").WithLocation(1, 11)
                 );
         }
+
+        [Fact]
+        [WorkItem(10023, "https://github.com/dotnet/roslyn/issues/10023")]
+        public void Errors_01()
```
Comment (tmat) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs]: This test is pretty long, I suggest splitting it to multiple methods.

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs (hunk 2 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs]: I think it is still relevant as we don't support SemanticModel for global code if it is not part of a Script. Nothing changed in that regard.

File: src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs [hunk 4]
```diff
@@ -958,5 +958,178 @@ public void FixedBuffer_02()
...
+            compilation.VerifyDiagnostics(
+                // (1,34): error CS7019: Type of 'x' cannot be inferred since its initializer directly or indirectly refers to the definition.
+                // System.Console.WriteLine(out var x, x);
+                Diagnostic(ErrorCode.ERR_RecursivelyTypedVariable, "x").WithArguments("x").WithLocation(1, 34)
+                );
+        }
+
+        [Fact]
+        [WorkItem(10023, "https://github.com/dotnet/roslyn/issues/10023")]
+        public void Errors_03()
```
Comment (tmat) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs]: Shouldn't this test rather be in the test class along with other CSharpParseOptions tests?

File: src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb [hunk 5]
```diff
@@ -1770,14 +1770,38 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
         ''' The Script class symbol or null if it is not defined.
         ''' </returns>
         Private Function BindScriptClass() As ImplicitNamedTypeSymbol
-            If Options.ScriptClassName Is Nothing OrElse Not Options.ScriptClassName.IsValidClrTypeName() Then
-                Return Nothing
-            End If
+            Dim scriptClassName As String = If(Options.ScriptClassName, "")
+
+            Dim parts() As String = scriptClassName.Split("."c)
```
Comment (tmat) [inline src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb]: Perhaps this logic can be shared with C#.

File: src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs (hunk 4 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs]: It feels Script  specific to me, correctness of scripting implementation depends on this.

File: src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs [hunk 6]
```diff
@@ -958,5 +958,178 @@ public void FixedBuffer_02()
...
+            CompileAndVerify(compilation, expectedOutput:"1").VerifyDiagnostics();
+
+            syntaxTree = SyntaxFactory.ParseSyntaxTree(code, options: new CSharp.CSharpParseOptions(kind: SourceCodeKind.Script));
+            compilation = CreateCompilationWithMscorlib45(new[] { syntaxTree }, options: TestOptions.ReleaseExe.WithScriptClassName("Script"));
+            semanticModel = compilation.GetSemanticModel(syntaxTree, true);
+            node5 = ErrorTestsGetNode(syntaxTree);
+            Assert.Equal("WriteLine", node5.Name.ToString());
+            Assert.Equal("void System.Console.WriteLine(System.Int32 value)", semanticModel.GetSymbolInfo(node5.Name).Symbol.ToTestDisplayString());
+
+            CompileAndVerify(compilation, expectedOutput: "1").VerifyDiagnostics();
```
Comment (tmat) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs]: Perhaps add a test with 2 syntax trees: one is a script syntax tree and the other is regular.

File: src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs (hunk 4 above)
Comment (tmat) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs]: Sure but I'd not categorize it as a semantic test. There is a lot of other stuff that scripting implementation depends on.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs]: I see no reason to spread tests for particular feature across multiple types. My preference is to put all related tests into one class.

File: src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs (hunk 6 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs]: Is this scenario specially related to any change in this PR?

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs]: Or did you mean the regular tree should have CompilationUnit parsed as Script?

Comment (tmat) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs]: Yes. It would validate that we allow the global statement in the script syntax tree and report an error for the other syntax tree.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs]: Yes, this is a good scenario to test, I'll add it. Thanks.

File: src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs (hunk 4 above)
Comment (tmat) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs]: The reason is that we already have tests that check invalid SourceCodeKind, just not this specific value

http://source.roslyn.io/#Roslyn.Compilers.CSharp.Syntax.UnitTests/Parsing/CSharpParseOptionsTests.cs,32

So I see no reason why to spread tests for particular feature across multiple types.

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs (hunk 2 above)
Comment (tmat) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs]: ok

File: src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs (hunk 4 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs]: I guess the test is related to multiple features, it can go to either place and I think it is more appropriate here because it makes self-explanatory why we are not testing trees with this SourceCodeKind.

File: src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs (hunk 6 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ScriptSemanticsTests.cs]: Added.

File: src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb (hunk 5 above)
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Compilation/VisualBasicCompilation.vb]: Shared.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler, @cston Please review.

File: src/Compilers/Core/Portable/Compilation/Compilation.cs [hunk 7]
```diff
@@ -824,6 +824,51 @@ public INamedTypeSymbol GetSpecialType(SpecialType specialType)
...
+        protected INamedTypeSymbol CommonBindScriptClass()
+        {
+            string scriptClassName = this.Options.ScriptClassName ?? "";
+
+            string[] parts = scriptClassName.Split('.');
+            INamespaceSymbol container = this.SourceModule.GlobalNamespace;
+
+            for (int i = 0; i < parts.Length - 1; i++)
+            {
+                INamespaceSymbol next = container.GetNestedNamespace(parts[i]);
```
Comment (cston) [inline src/Compilers/Core/Portable/Compilation/Compilation.cs]: Do we need to support nested types for the script class?

Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Compilation/Compilation.cs]: I don't think so, declaration table always creates top level type declaration for it. See CreateScriptClass method in src\compilers\csharp\portable\declarations\declarationtreebuilder.cs

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler, @cston Please review.

**Comment by cston** [comment]
LGTM

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs [hunk 8]
```diff
@@ -2864,14 +2863,14 @@ private static bool HasNonConstantInitializer(ArrayBuilder<ImmutableArray<FieldO
                     return;
                 }
 
-                bool reportMisplacedGlobalCode = !globalCodeAllowed && !m.HasErrors;
+                bool reportMisplacedGlobalCode = !m.HasErrors;
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs]: Why does the absence of member errors indicate these members are in a bad global context?

File: src/Compilers/Core/Portable/Compilation/Compilation.cs [hunk 9]
```diff
@@ -824,6 +824,51 @@ public INamedTypeSymbol GetSpecialType(SpecialType specialType)
...
+                    AssertNoScriptTrees();
+                    return null;
+                }
+
+                container = next;
+            }
+
+            foreach (INamedTypeSymbol candidate in container.GetTypeMembers(parts[parts.Length - 1]))
+            {
+                if (candidate.IsScriptClass)
```
Comment (jcouv) [inline src/Compilers/Core/Portable/Compilation/Compilation.cs]: Might we find more than one candidate? 
If yes, is the enumeration of type members ordered? If it is not deterministic, then maybe ambiguity should be an error.

Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Compilation/Compilation.cs]: We shouldn't find more than one candidate, that is how declarations are added.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs (hunk 8 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs]: > Why does the absence of member errors indicate these members are in a bad global context?

It doesn't, this local is used to suppress cascading diagnostics.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs (hunk 8 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs]: Ah, maybe a comment to that effect would be useful.
