### PR TITLE
IDE0220 (foreach cast): Consider T of IEnumerable<T> for weakly-typed GetEnumerator

### LINKED ISSUE #63470: IDE0220 on foreach (Match m in regex.Matches) – Should Not Occur
Using the following code snippet results in Roslyn analyzer adding an informational warning to the list of analysis results:

```c#
foreach (Match m in regex.Matches(text))
{
  ...
}
```

```
IDE0220  'foreach' statement implicitly converts 'object' into 'System.Text.RegularExpressions.Match'. Add an explicit cast to indicate your intention as it may fail at runtime.
```

[`MatchCollection.Item[]`](https://docs.microsoft.com/dotnet/api/system.text.regularexpressions.matchcollection.item), however, doesn't return `object`. It returns a [`Match`](https://docs.microsoft.com/dotnet/api/system.text.regularexpressions.match).

## Version Used 

.NET 6

## Steps to Reproduce

1. Create a [regular expression](https://docs.microsoft.com/dotnet/api/system.text.regularexpressions.regex) object.
2. Run the [`Regex.Matches()`](https://docs.microsoft.com/dotnet/api/system.text.regularexpressions.regex.matches) method on that regular expression and feed immediately to a [`Match`](https://docs.microsoft.com/dotnet/api/system.text.regularexpressions.match) variable in a `foreach` loop.

## Expected Behavior

This should be analyzed by the Roslyn analyzer without flaw.

## Actual Behavior

The Roslyn analyzer adds an information to the analysis result (roughly translated by me from German to English):

```
IDE0220  'foreach' statement implicitly converts 'object' into 'System.Text.RegularExpressions.Match'. Add an explicit cast to indicate your intention as it may fail at runtime.
```

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #63470

### CODE REVIEW

File: src/Analyzers/Core/Analyzers/ForEachCast/AbstractForEachCastDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -81,12 +80,39 @@ protected override void InitializeWorker(AnalysisContext context)
...
+            // }
+
+            // This collection have GetEnumerator method that returns non-strongly-typed IEnumerator, but also implements strongly-typed IEnumerable<T> explicitly.
+            // In this case, the compiler considers the non-strongly-typed GetEnumerator and adds explicit cast for `foreach (Match m in new C())`.
+            // This cast can fail if the collection is badly implemented such that the strongly-typed and non-strongly-typed GetEnumerator implemetations return different types.
+            // So, we want to consider the collectionElementType as System.Object (that's what the compiler returns).
+            // However, we trust CorLib, so we adjust collectionElementType for the case above to be `Match` instead of object if the type comes from CorLib.
+            if (collectionElementType.SpecialType == SpecialType.System_Object &&
+                collectionType.ContainingAssembly is { } collectionTypeContainingAssembly &&
+                collectionTypeContainingAssembly.Identity.PublicKey.SequenceEqual(context.Compilation.GetSpecialType(SpecialType.System_Object).ContainingAssembly?.Identity.PublicKey))
```
Comment (Youssef1313) [inline src/Analyzers/Core/Analyzers/ForEachCast/AbstractForEachCastDiagnosticAnalyzer.cs:106]: Regex and System.Object come from different assemblies, but the assemblies have the same public key. So I relied on that to know whether `collectionType` is something built-in or not.

Comment (RikkiGibson) [reply src/Analyzers/Core/Analyzers/ForEachCast/AbstractForEachCastDiagnosticAnalyzer.cs:106]: I wasn't sure why we enforce that these come from the same assembly. Does it matter if the collection is built-in or not?

File: src/Analyzers/Core/Analyzers/ForEachCast/AbstractForEachCastDiagnosticAnalyzer.cs [hunk 2]
```diff
@@ -81,12 +80,39 @@ protected override void InitializeWorker(AnalysisContext context)
...
+            // Consider:
+            // public class C : IEnumerable<Match>
+            // {
+            //     public IEnumerator GetEnumerator() => null; // compiler picks this for the foreach loop.
+            //
+            //     IEnumerator<Match> IEnumerable<Match>.GetEnumerator() => null; // compiler doesn't use this.
+            // }
+
+            // This collection have GetEnumerator method that returns non-strongly-typed IEnumerator, but also implements strongly-typed IEnumerable<T> explicitly.
+            // In this case, the compiler considers the non-strongly-typed GetEnumerator and adds explicit cast for `foreach (Match m in new C())`.
```
Comment (dibarbet) [inline src/Analyzers/Core/Analyzers/ForEachCast/AbstractForEachCastDiagnosticAnalyzer.cs:100]:
```suggestion
            // In this case, the compiler chooses the non-strongly-typed GetEnumerator and adds explicit cast for `foreach (Match m in new C())`.
```

File: src/Analyzers/Core/Analyzers/ForEachCast/AbstractForEachCastDiagnosticAnalyzer.cs (hunk 1 above)
Comment (dibarbet) [reply src/Analyzers/Core/Analyzers/ForEachCast/AbstractForEachCastDiagnosticAnalyzer.cs:106]: I see technically that someone could write code that intentionally fails this (e.g. your sharplab example) but I think its probably rare enough that I wouldn't bother doing this check.  If not we'll hear feedback otherwise

Comment (Youssef1313) [reply src/Analyzers/Core/Analyzers/ForEachCast/AbstractForEachCastDiagnosticAnalyzer.cs:106]: > I see technically that someone could write code that intentionally fails this (e.g. your sharplab example) but I think its probably rare enough that I wouldn't bother doing this check. If not we'll hear feedback otherwise

Yeah that was my intention to guard against this rare case. Going to revert this part now.

**Comment by Youssef1313** [comment]
@RikkiGibson @dibarbet This is ready for another look.

File: src/Analyzers/Core/Analyzers/ForEachCast/AbstractForEachCastDiagnosticAnalyzer.cs [hunk 3]
```diff
@@ -51,12 +51,11 @@ protected override void InitializeWorker(AnalysisContext context)
                 var ienumerableType = compilation.IEnumerableType();
                 var ienumerableOfTType = compilation.IEnumerableOfTType();
                 if (ienumerableType != null && ienumerableOfTType != null)
-                    context.RegisterSyntaxNodeAction(context => AnalyzeSyntax(context, ienumerableType, ienumerableOfTType), GetSyntaxKinds());
```
Comment (CyrusNajmabadi) [inline src/Analyzers/Core/Analyzers/ForEachCast/AbstractForEachCastDiagnosticAnalyzer.cs:54]: So we even need the above two variables anymore?

**Review by dibarbet — APPROVED** [review]

File: src/Analyzers/CSharp/Tests/ForEachCast/ForEachCastTests.cs [hunk 4]
```diff
@@ -1043,5 +1046,104 @@ public static void M((object, object)[] x)
...
+        }
+    }
+}
+";
+            await TestAlwaysAsync(test, code);
+            await TestWhenStronglyTypedAsync(test, code);
+        }
+
+        [Fact, WorkItem(63470, "https://github.com/dotnet/roslyn/issues/63470")]
+        public async Task WeaklyTypedGetEnumeratorWithIEnumerableOfT()
```
Comment (RikkiGibson) [inline src/Analyzers/CSharp/Tests/ForEachCast/ForEachCastTests.cs:1105]: It would be good to test the "BadCast" case in this form as well, where the implemented interfaces and GetEnumerator behavior are apparent from the test.

**Comment by RikkiGibson** [comment]
It looks like there is outstanding feedback and conflicts in this PR. I will move to draft for the time being.

File: src/Analyzers/CSharp/Tests/ForEachCast/ForEachCastTests.cs [hunk 5]
```diff
@@ -27,6 +29,7 @@ public class ForEachCastTests
                 [*]
                 dotnet_style_prefer_foreach_explicit_cast_in_source=
                 """ + optionValue,
+                ReferenceAssemblies = ReferenceAssemblies.Net.Net60,
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/ForEachCast/ForEachCastTests.cs:32]: please don't change the core test.  make it so that some tests use different references assemblies so we can see the different behaviors.

File: src/Analyzers/CSharp/Tests/ForEachCast/ForEachCastTests.cs [hunk 6]
```diff
@@ -1096,8 +1096,8 @@ public static void M(Regex regex, string text)
     }
 }
 ";
-            await TestAlwaysAsync(test, test);
-            await TestWhenStronglyTypedAsync(test, test);
+            await TestAlwaysAsync(test, test, ReferenceAssemblies.Net.Net80);
+            await TestWhenStronglyTypedAsync(test, test, ReferenceAssemblies.Net.Net80);
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Tests/ForEachCast/ForEachCastTests.cs:1100]: don't change existing tests, write new ones.  for the existing tests show the new behaviors with the same args :)

Comment (Youssef1313) [reply src/Analyzers/CSharp/Tests/ForEachCast/ForEachCastTests.cs:1100]: @CyrusNajmabadi These are the new tests.

Comment (CyrusNajmabadi) [reply src/Analyzers/CSharp/Tests/ForEachCast/ForEachCastTests.cs:1100]: weird! it showed up strange in the diff. thanks!

File: src/Analyzers/Core/Analyzers/ForEachCast/AbstractForEachCastDiagnosticAnalyzer.cs [hunk 7]
```diff
@@ -84,12 +76,36 @@ protected override void InitializeWorker(AnalysisContext context)
...
+            //     IEnumerator<Match> IEnumerable<Match>.GetEnumerator() => null; // compiler doesn't use this.
+            // }
+
+            // This collection have GetEnumerator method that returns non-strongly-typed IEnumerator, but also implements strongly-typed IEnumerable<T> explicitly.
+            // In this case, the compiler chooses the non-strongly-typed GetEnumerator and adds explicit cast for `foreach (Match m in new C())`.
+            // This cast can fail if the collection is badly implemented such that the strongly-typed and non-strongly-typed GetEnumerator implemetations return different types.
+            // Given it's very rare that implementation can be bad, and to reduce false positives, we adjust collectionElementType for the case above to be `Match` instead of object.
+            if (collectionElementType.SpecialType == SpecialType.System_Object)
+            {
+                var ienumerableOfT = collectionType.AllInterfaces.SingleOrDefault(i => i.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T);
```
Comment (CyrusNajmabadi) [inline src/Analyzers/Core/Analyzers/ForEachCast/AbstractForEachCastDiagnosticAnalyzer.cs:101]: SingleOrDefault is not ok.  This will throw if a type impelments this interfaces multiple types.  For example `: IEnumerable<int>, IEnumerable<string>`.  Please add test.

Comment (CyrusNajmabadi) [reply src/Analyzers/Core/Analyzers/ForEachCast/AbstractForEachCastDiagnosticAnalyzer.cs:101]: (note: this does occur with some real world types we've seen that both implement multiple times to simulate a variance relationship with nonvariant types).

Comment (Youssef1313) [reply src/Analyzers/Core/Analyzers/ForEachCast/AbstractForEachCastDiagnosticAnalyzer.cs:101]: @CyrusNajmabadi Hmmm.. In that case should we allow `foreach` with any of types? That will require more work in the analyzer to check the conversion of all the candidate types in `IEnumerable<T>`s. Or could I use `FirstOrDefault` for now and open an issue to follow-up with proper handling for multiple `IEnumerable<T>`s?

File: src/Analyzers/CSharp/Tests/ForEachCast/ForEachCastTests.cs [hunk 8]
```diff
@@ -1178,5 +1178,80 @@ public void Reset()
...
+
+public class C : IEnumerable<string>
+{
+    public IEnumerator GetEnumerator() => new Enumerator(); // compiler picks this for the foreach loop.
+
+    IEnumerator<string> IEnumerable<string>.GetEnumerator() => null; // compiler doesn't use this.
+
+    public static void M(C c)
+    {
+        foreach (C x in c.Cast<C>())
```
Comment (RikkiGibson) [inline src/Analyzers/CSharp/Tests/ForEachCast/ForEachCastTests.cs:1233]: Sorry, I don't have this all paged in, but why is it an improvement to call `.Cast()` here?

Comment (RikkiGibson) [reply src/Analyzers/CSharp/Tests/ForEachCast/ForEachCastTests.cs:1233]: I guess the point is "this is how you suppress teh warning"? Since the IEnumerable<T> impl is not IEnumerable<C>, it doesn't meet what we want/expect to use with `foreach (C x in c...)`

File: src/Analyzers/Core/Analyzers/ForEachCast/AbstractForEachCastDiagnosticAnalyzer.cs (hunk 7 above)
Comment (RikkiGibson) [reply src/Analyzers/Core/Analyzers/ForEachCast/AbstractForEachCastDiagnosticAnalyzer.cs:101]: I agree, if someone is implementing IEnumerable<T> multiple times, *and* they are doing the legacy `object Current` thing, *and* someone is getting an unwanted foreach cast diagnostic here, we can revisit and make this code more complex at that time, not now.

Comment (RikkiGibson) [reply src/Analyzers/Core/Analyzers/ForEachCast/AbstractForEachCastDiagnosticAnalyzer.cs:101]:
```suggestion
                var ienumerableOfT = collectionType.AllInterfaces.FirstOrDefault(i => i.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T);
```

**Review by RikkiGibson — COMMENTED** [review]
lgtm modulo changing SingleOrDefault to FirstOrDefault and adding a test where IEnumerable<T> is implemented multiple times

**Comment by RikkiGibson** [comment]
We've seen a steady stream of +1s and comments on the linked issue. Since the solution is mostly complete let's try to get it over the finish line and merged in 17.10. Let me know if you will be able to work on this @Youssef1313. Otherwise I can try to get it done in the next few weeks.

**Comment by Youssef1313** [comment]
@RikkiGibson Yup sure. I think the remaining comment is to use `FirstOrDefault` instead of `SingleOrDefault` and add a test. I'll do that now.

**Review by RikkiGibson — APPROVED** [review]

**Comment by RikkiGibson** [comment]
@dibarbet @CyrusNajmabadi for review

**Review by dibarbet — APPROVED** [review]

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks @Youssef1313 !
