### PR TITLE
Fix localization test failure in TestReportingUnsupportedDiagnostic.

### LINKED ISSUE #1392: Microsoft.CodeAnalysis.CSharp.UnitTests.DiagnosticAnalyzerTests.TestReportingUnsupportedDiagnostic fails in presence of localized resources
Assemblies Run

F:\Roslyn\Main\Open\Binaries\Debug\Roslyn.Compilers.CSharp.Semantic.UnitTests.dll

Summary

Tests run: 3330   Failures: 1, Skipped: 12, Run time: 130.619s

Failed tests

0.037s
✘
 Microsoft.CodeAnalysis.CSharp.UnitTests.DiagnosticAnalyzerTests.TestReportingUnsupportedDiagnostic : Expected: Diagnostic("AD0001").WithArguments("Microsoft.CodeAnalysis.CSharp.UnitTests.DiagnosticAnalyzerTests+AnalyzerReportingUnsupportedDiagnostic", "Reported diagnostic with ID 'ID_2' is not supported by the analyzer. Parameter name: diagnostic") Actual: Diagnostic("AD0001").WithArguments("Microsoft.CodeAnalysis.CSharp.UnitTests.DiagnosticAnalyzerTests+AnalyzerReportingUnsupportedDiagnostic", "!cSUx2!Reported diagnostic with ID 'ID_2' is not supported by the analyzer. ЁЧЫюрфя ! Имя параметра: diagnostic").WithLocation(1, 1) Diff: ++> Diagnostic("AD0001").WithArguments("Microsoft.CodeAnalysis.CSharp.UnitTests.DiagnosticAnalyzerTests+AnalyzerReportingUnsupportedDiagnostic", "!cSUx2!Reported diagnostic with ID 'ID_2' is not supported by the analyzer. ЁЧЫюрфя ! ++> Имя параметра: diagnostic").WithLocation(1, 1) --> Diagnostic("AD0001").WithArguments("Microsoft.CodeAnalysis.CSharp.UnitTests.DiagnosticAnalyzerTests+AnalyzerReportingUnsupportedDiagnostic", "Reported diagnostic with ID 'ID_2' is not supported by the analyzer. --> Parameter name: diagnostic")
   в Xunit.Assert.True(Boolean condition, String userMessage)
   в Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected, Boolean errorCodeOnly) в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\Test\Utilities\DiagnosticExtensions.cs:строка 83
   в Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(IEnumerable`1 actual, DiagnosticDescription[] expected) в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\Test\Utilities\DiagnosticExtensions.cs:строка 45
   в Microsoft.CodeAnalysis.DiagnosticExtensions.Verify(ImmutableArray`1 actual, DiagnosticDescription[] expected) в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\Test\Utilities\DiagnosticExtensions.cs:строка 60
   в Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyAnalyzerDiagnostics[TCompilation](TCompilation c, DiagnosticAnalyzer[] analyzers, AnalyzerOptions options, Action`3 onAnalyzerException, Boolean logAnalyzerExceptionAsDiagnostics, DiagnosticDescription[] expected) в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\Test\Utilities\DiagnosticExtensions.cs:строка 123
   в Microsoft.CodeAnalysis.CSharp.UnitTests.DiagnosticAnalyzerTests.TestReportingUnsupportedDiagnostic() в C:\Builds\Roslyn\Main-PerCheckin-Debug\src\Open\src\Compilers\CSharp\Test\Semantic\Diagnostics\DiagnosticAnalyzerTests.cs:строка 950

See https://github.com/dotnet/roslyn/issues/821 for repro steps.

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #1392 

@srivatsn @shyamnamboodiripad @heejaechang @jmarolf @tmeschter @JohnHamby should be a pretty quick review.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs [hunk 1]
```diff
@@ -945,12 +945,12 @@ public override void Initialize(AnalysisContext context)
...
         }
 
-        [Fact, WorkItem(252, "https://github.com/dotnet/roslyn/issues/252")]
+        [Fact, WorkItem(252, "https://github.com/dotnet/roslyn/issues/252"), WorkItem(1392, "https://github.com/dotnet/roslyn/issues/1392")]
         public void TestReportingUnsupportedDiagnostic()
         {
             string source = @"";
             var analyzers = new DiagnosticAnalyzer[] { new AnalyzerReportingUnsupportedDiagnostic() };
-            string message = new ArgumentException("Reported diagnostic with ID 'ID_2' is not supported by the analyzer.", "diagnostic").Message;
+            string message = new ArgumentException(string.Format(AnalyzerDriverResources.UnsupportedDiagnosticReported, AnalyzerReportingUnsupportedDiagnostic.UnsupportedDescriptor.Id), "diagnostic").Message;
```
Comment (mavasani) [inline src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs]: This is the origin of the exception that is converted into a diagnostic: http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalysisContextHelpers.cs,37

**Comment by shyamnamboodiripad** [comment]
:+1:

**Comment by srivatsn** [comment]
:+1:
