### PR TITLE
Preserve parent hoisted variables in nested async `catch`

### LINKED ISSUE #67091: C# compilation fails: Process terminated. System.Collections.Generic.KeyNotFoundException
**Version Used**: 
.NET SDK 6.0.406
.NET SDK 7.0.200

**Steps to Reproduce**:

1.  In a .NET project add a file with the following code. 
```csharp
using System;
using System.Net;
using System.Threading.Tasks;

namespace ConsoleApp29
{
    public sealed class EventSubscriptionListener
    {
        public async Task Listen()
        {
            try
            {
            }
            catch (WebException ex) when (ex.Response is HttpWebResponse)
            {
                await NotifyConnectionError(ex);
            }
            catch (WebException ex) when (ex.Response is HttpWebResponse)
            {
                try
                {
                }
                catch 
                {
                    await NotifyConnectionError(ex);
                }
            }
        }

        private Task NotifyConnectionError(Exception ex)
        {
            return Task.Delay(1000);
        }
    }
}

```
2.  Compile using VS or dotnet build
3. csc crashes

**Expected Behavior**:
Successful compilation

**Actual Behavior**:
```
Process terminated. System.Collections.Generic.KeyNotFoundException: The given key 'ex' was not present in the dictionary. [Sample.csproj]
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key) [Sample.csproj]
   at Microsoft.CodeAnalysis.CodeGen.LocalSlotManager.GetLocal(ILocalSymbolInternal symbol) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitLocalLoad(BoundLocal local, Boolean used) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpressionCore(BoundExpression expression, Boolean used) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitConversionExpression(BoundConversion conversion, Boolean used) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpressionCore(BoundExpression expression, Boolean used) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitArgument(BoundExpression argument, RefKind refKind) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitArguments(ImmutableArray`1 arguments, ImmutableArray`1 parameters, ImmutableArray`1 argRefKindsOpt) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitInstanceCallExpression(BoundCall call, UseKind useKind) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitCallExpression(BoundCall call, UseKind useKind) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpressionCore(BoundExpression expression, Boolean used) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitInstanceCallExpression(BoundCall call, UseKind useKind) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitCallExpression(BoundCall call, UseKind useKind) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpressionCore(BoundExpression expression, Boolean used) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitAssignmentValue(BoundAssignmentOperator assignmentOperator) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitAssignmentExpression(BoundAssignmentOperator assignmentOperator, UseKind useKind) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpressionCore(BoundExpression expression, Boolean used) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpressionCoreWithStackGuard(BoundExpression expression, Boolean used) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(ImmutableArray`1 statements) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(BoundBlock block) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(ImmutableArray`1 statements) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(BoundBlock block) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatementAndCountInstructions(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitSequencePointStatement(BoundSequencePoint node) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(ImmutableArray`1 statements) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(BoundBlock block) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(ImmutableArray`1 statements) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(BoundBlock block) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(ImmutableArray`1 statements) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(BoundBlock block) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(ImmutableArray`1 statements) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(BoundBlock block) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(ImmutableArray`1 statements) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(BoundBlock block) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(ImmutableArray`1 statements) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(BoundBlock block) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(ImmutableArray`1 statements) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(BoundBlock block) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(ImmutableArray`1 statements) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(BoundBlock block) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(ImmutableArray`1 statements) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(BoundBlock block) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(ImmutableArray`1 statements) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(BoundBlock block) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(ImmutableArray`1 statements) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(BoundBlock block) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(ImmutableArray`1 statements) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(BoundBlock block) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStateMachineScope(BoundStateMachineScope scope) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(ImmutableArray`1 statements) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(BoundBlock block) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(ImmutableArray`1 statements) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(BoundBlock block) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(ImmutableArray`1 statements) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(BoundBlock block) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitTryStatement(BoundTryStatement statement, Boolean emitCatchesOnly) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(ImmutableArray`1 statements) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(BoundBlock block) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatementAndCountInstructions(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitSequencePointStatement(BoundSequencePoint node) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(ImmutableArray`1 statements) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(BoundBlock block) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.GenerateImpl() [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.Generate(Int32& asyncCatchHandlerOffset, ImmutableArray`1& asyncYieldPoints, ImmutableArray`1& asyncResumePoints, Boolean& hasStackAlloc) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol method, Int32 methodOrdinal, BoundStatement block, ImmutableArray`1 lambdaDebugInfo, ImmutableArray`1 closureDebugInfo, ImmutableArray`1 stateMachineStateDebugInfos, StateMachineTypeSymbol stateMachineTypeOpt, VariableSlotAllocator variableSlotAllocatorOpt, BindingDiagnosticBag diagnostics, DebugDocumentProvider debugDocumentProvider, ImportChain importChainOpt, Boolean emittingPdb, Boolean emitTestCoverageData, ImmutableArray`1 dynamicAnalysisSpans, AsyncForwardEntryPoint entryPointOpt) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileSynthesizedMethods(TypeCompilationState compilationState) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass25_0.<CompileNamedTypeAsync>b__0() [Sample.csproj]
   at System.Environment.FailFast(System.String, System.Exception) [Sample.csproj]
   at Microsoft.CodeAnalysis.FailFast.OnFatalException(System.Exception) [Sample.csproj]
   at Microsoft.CodeAnalysis.FailFast+<>c.<.cctor>b__5_0(System.Exception, Microsoft.CodeAnalysis.ErrorReporting.ErrorSeverity, Boolean) [Sample.csproj]
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception, Microsoft.CodeAnalysis.ErrorReporting.ErrorSeverity, Boolean) [Sample.csproj]
   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportAndPropagateUnlessCanceled(System.Exception, Microsoft.CodeAnalysis.ErrorReporting.ErrorSeverity) [Sample.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass25_0.<CompileNamedTypeAsync>b__0() [Sample.csproj]
```

### PR DESCRIPTION
**Pull request by jjonescz**
Fixes #67091.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs [hunk 1]
```diff
@@ -2104,5 +2104,43 @@ static void Main()
 ";
             CompileAndVerify(source, expected);
         }
+
+        [Fact, WorkItem(67091, "https://github.com/dotnet/roslyn/issues/67091")]
+        public void NestedCatch_DuplicateWhen()
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs:2109]: >DuplicateWhen() [](http://example.com/codeflow?start=32&length=15)

Is it the duplicate `when` that causes the bug or is it the duplicated local name and type of the hoisted locals? (Just trying to confirm my understanding.)

**Review by cston — DISMISSED** [review]

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs (hunk 1 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs:2109]: It's the duplicated local name and type. I just didn't know that yet when writing the test name. But having two `when` clauses is also needed, otherwise we couldn't have duplicate locals. I guess I will update the test name to make it clearer.
```suggestion
        public void NestedCatch_DuplicateLocal()
```

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs [hunk 2]
```diff
@@ -2104,5 +2104,43 @@ static void Main()
 ";
             CompileAndVerify(source, expected);
         }
+
+        [Fact, WorkItem(67091, "https://github.com/dotnet/roslyn/issues/67091")]
+        public void NestedCatch_DuplicateLocal()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs:2109]: Can we add a test with for a similar scenario in VB?

File: src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncExceptionHandlerRewriter.cs [hunk 3]
```diff
@@ -24,7 +24,7 @@ internal sealed class AsyncExceptionHandlerRewriter : BoundTreeRewriterWithStack
         private readonly SyntheticBoundNodeFactory _F;
         private readonly AwaitInFinallyAnalysis _analysis;
 
-        private AwaitCatchFrame _currentAwaitCatchFrame;
+        private AwaitCatchFrame _parentAwaitCatchFrame, _currentAwaitCatchFrame;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncExceptionHandlerRewriter.cs:27]: >private AwaitCatchFrame _parentAwaitCatchFrame, _currentAwaitCatchFrame; [](http://example.com/codeflow?start=8&length=72)

I think it is rather unusual for out code to declare multiple fields or locals in one statement. Makes code less readable, in my opinion.

File: src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncExceptionHandlerRewriter.cs [hunk 4]
```diff
@@ -1004,14 +1007,18 @@ private sealed class AwaitCatchFrame
...
                 this.pendingCatch = new SynthesizedLocal(F.CurrentFunction, TypeWithAnnotations.Create(F.SpecialType(SpecialType.System_Int32)), SynthesizedLocalKind.TryAwaitPendingCatch, tryStatementSyntax);
 
                 this.handlers = new List<BoundBlock>();
-                _hoistedLocals = new Dictionary<LocalSymbol, LocalSymbol>();
-                _orderedHoistedLocals = new List<LocalSymbol>();
+                _hoistedLocals = parentOpt != null
+                    ? new Dictionary<LocalSymbol, LocalSymbol>(parentOpt._hoistedLocals)
+                    : new Dictionary<LocalSymbol, LocalSymbol>();
+                _orderedHoistedLocals = parentOpt != null
+                    ? new List<LocalSymbol>(parentOpt._orderedHoistedLocals)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncExceptionHandlerRewriter.cs:1020]: >new List<LocalSymbol>(parentOpt._orderedHoistedLocals) [](http://example.com/codeflow?start=22&length=54)

Is this the right thing to do? It looks like these locals are getting added to a ```BoundBlock``` corresponding to the ```AwaitCatchFrame```. Are we going to add parent locals for all children now? If so, is this intentional?

**Comment by AlekseyTs** [comment]
>                 return _hoistedLocals.TryGetValue(originalLocal, out hoistedLocal);

Is it our intent to return parent local here or is our intent only to affect behavior of ```HoistLocal```? If we want to affect behavior of this method, are we testing the effect?

---
Refers to: src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncExceptionHandlerRewriter.cs:1052 in 43ad4ba. [](commit_id = 43ad4baa4d22d5a11d8d2012f3e79000e549fa29, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncExceptionHandlerRewriter.cs [hunk 5]
```diff
@@ -1004,14 +1007,18 @@ private sealed class AwaitCatchFrame
...
+            public AwaitCatchFrame(SyntheticBoundNodeFactory F, TryStatementSyntax tryStatementSyntax, AwaitCatchFrame parentOpt = null)
             {
                 this.pendingCaughtException = new SynthesizedLocal(F.CurrentFunction, TypeWithAnnotations.Create(F.SpecialType(SpecialType.System_Object)), SynthesizedLocalKind.TryAwaitPendingCaughtException, tryStatementSyntax);
                 this.pendingCatch = new SynthesizedLocal(F.CurrentFunction, TypeWithAnnotations.Create(F.SpecialType(SpecialType.System_Int32)), SynthesizedLocalKind.TryAwaitPendingCatch, tryStatementSyntax);
 
                 this.handlers = new List<BoundBlock>();
-                _hoistedLocals = new Dictionary<LocalSymbol, LocalSymbol>();
-                _orderedHoistedLocals = new List<LocalSymbol>();
+                _hoistedLocals = parentOpt != null
+                    ? new Dictionary<LocalSymbol, LocalSymbol>(parentOpt._hoistedLocals)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncExceptionHandlerRewriter.cs:1017]: >parentOpt._hoistedLocals [](http://example.com/codeflow?start=63&length=24)

Instead of copying data, could we simply chain  ```AwaitCatchFrame``` and iterate through the chain when appropriate?

File: src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncExceptionHandlerRewriter.cs [hunk 6]
```diff
@@ -1004,14 +1007,18 @@ private sealed class AwaitCatchFrame
             private readonly Dictionary<LocalSymbol, LocalSymbol> _hoistedLocals;
             private readonly List<LocalSymbol> _orderedHoistedLocals;
 
-            public AwaitCatchFrame(SyntheticBoundNodeFactory F, TryStatementSyntax tryStatementSyntax)
+            public AwaitCatchFrame(SyntheticBoundNodeFactory F, TryStatementSyntax tryStatementSyntax, AwaitCatchFrame parentOpt = null)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncExceptionHandlerRewriter.cs:1010]: >, AwaitCatchFrame parentOpt = null [](http://example.com/codeflow?start=101&length=34)

Optional parameters are error prone. It is easy to fail to pass a value when it is required. Also, attention of reviewers is not drawn to call sites that are left unmodified.

**Comment by AlekseyTs** [comment]
>         public override BoundNode VisitCatchBlock(BoundCatchBlock node)

Do we expect this method to be called only for ```node.CatchBlocks``` in ```var rewrittenCatches = this.VisitList(node.CatchBlocks);``` in ```RewriteFinalizedRegion``` above? 

If not, then what makes us think the ```_parentAwaitCatchFrame``` is properly initialized for the other cases?

If yes, then I suggest:
- adding ```parentAwaitCatchFrame``` as a parameter to this method and removing the `override` modifier
- calling it explicitly from ```RewriteFinalizedRegion``` instead of relying on ```VisitList```
- getting rid of the ```_parentAwaitCatchFrame``` field  
- Throwing unreachable from ```public override BoundNode VisitCatchBlock(BoundCatchBlock node)```.

---
Refers to: src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncExceptionHandlerRewriter.cs:505 in 43ad4ba. [](commit_id = 43ad4baa4d22d5a11d8d2012f3e79000e549fa29, deletion_comment = False)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs (hunk 2 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs:2109]: >NestedCatch_DuplicateLocal [](http://example.com/codeflow?start=20&length=26)

Is it possible to add a test with more levels of nesting? For example, where locals from at least two distinct parent ```AwaitCatchFrame```s would cause problems at the bottom ```AwaitCatchFrame``` before the change. Basically, if we think that it is required to pay attention to ```_hoistedLocals``` across the entire hierarchy, are we demonstrating this with a test?

**Comment by AlekseyTs** [comment]
Done with review pass (commit 3)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs (hunk 2 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs:2109]: Seems impossible, I'm getting:
<samp>error BC36943: 'Await' cannot be used inside a 'Catch' statement, a 'Finally' statement, or a 'SyncLock' statement.</samp>

File: src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncExceptionHandlerRewriter.cs (hunk 4 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncExceptionHandlerRewriter.cs:1020]: Good catch, thanks. That was indeed wrong. After updating the tests to print output, it even caused a crash in `StackOptimizerPass1`.

**Comment by jjonescz** [comment]
> > ```
> >             return _hoistedLocals.TryGetValue(originalLocal, out hoistedLocal);
> > ```
> 
> Is it our intent to return parent local here or is our intent only to affect behavior of `HoistLocal`? If we want to affect behavior of this method, are we testing the effect?

The intention was to change effect of this method only - so it finds even parent hoisted locals. `HoistLocal` shouldn't have been changed.

**Comment by jjonescz** [comment]
>                 return _hoistedLocals.TryGetValue(originalLocal, out hoistedLocal);

The intention was to change effect of this method only - so it finds even parent hoisted locals. `HoistLocal` shouldn't have been changed.

---
In reply to: [1474225304](https://github.com/dotnet/roslyn/pull/67122#issuecomment-1474225304) [](http://example.com/codeflow?ancestors=1474225304,1474225304)

---
Refers to: src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncExceptionHandlerRewriter.cs:1052 in 43ad4ba. [](commit_id = 43ad4baa4d22d5a11d8d2012f3e79000e549fa29, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncExceptionHandlerRewriter.cs [hunk 7]
```diff
@@ -458,7 +459,8 @@ private BoundStatement RewriteFinalizedRegion(BoundTryStatement node)
             var origAwaitCatchFrame = _currentAwaitCatchFrame;
             _currentAwaitCatchFrame = null;
 
-            var rewrittenCatches = this.VisitList(node.CatchBlocks);
+            var rewrittenCatches = node.CatchBlocks.SelectAsArray(catchBlock =>
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/AsyncRewriter/AsyncExceptionHandlerRewriter.cs:462]: >SelectAsArray [](http://example.com/codeflow?start=52&length=13)

Is there an overload that takes another argument and passes it to the delegate. If not, perhaps we should add one and use it in order to avoid capturing ```this``` and ```origAwaitCatchFrame``` in a closure.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs [hunk 8]
```diff
@@ -2104,5 +2104,148 @@ static void Main()
...
+                                throw new Exception("M1-catch2");
+                            }
+                            catch 
+                            {
+                                await M2(ex);
+                            }
+                        }
+                    }
+
+                    async Task M2(Exception ex)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs:2155]: >async Task M2(Exception ex) [](http://example.com/codeflow?start=20&length=27)

It is hard to judge from the output about call site of this method. Consider explicitly passing some kind of call site id at each call site and printing it as well.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs [hunk 9]
```diff
@@ -2104,5 +2104,148 @@ static void Main()
...
+
+                    async Task M1()
+                    {
+                        try
+                        {
+                            throw new Exception("M1");
+                        }
+                        catch (Exception ex) when (F(ex))
+                        {
+                            await M2(ex);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs:2140]: >await M2(ex); [](http://example.com/codeflow?start=28&length=13)

I think it would be good to test invocation of `M1` that goes though this code path.  Perhaps result of `F` could be configurable and we invoke `M1` for two configurations.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs [hunk 10]
```diff
@@ -2104,5 +2104,148 @@ static void Main()
...
+                F: 2 M1
+                M2: M1
+                """;
+
+            CompileAndVerify(source, options: TestOptions.DebugExe, expectedOutput: expectedOutput).VerifyDiagnostics();
+            CompileAndVerify(source, options: TestOptions.ReleaseExe, expectedOutput: expectedOutput).VerifyDiagnostics();
+        }
+
+        [Fact, WorkItem(67091, "https://github.com/dotnet/roslyn/issues/67091")]
+        public void NestedCatch_DuplicateLocal_Level2()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs:2173]: >NestedCatch_DuplicateLocal_Level2 [](http://example.com/codeflow?start=20&length=33)

Is this test going to fail if we do not go through the entire parent chain in ```TryGetHoistedLocal```, but instead only check in an immediate parent?

**Comment by AlekseyTs** [comment]
Done with review pass (commit 9)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs (hunk 10 above)
Comment (jjonescz) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs:2173]: Yes, I have tried that.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs [hunk 11]
```diff
@@ -2104,5 +2104,166 @@ static void Main()
...
+                        }
+                        catch (Exception ex) when (F("M1-catch2", ex, true))
+                        {
+                            try
+                            {
+                                throw new Exception("M1-catch2");
+                            }
+                            catch (Exception ex2) when (F("M1-catch2-catch1", ex2, catchFirst2))
+                            {
+                                await M2("M1-catch2-catch1", ex2);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncEHTests.cs:2220]: >await M2("M1-catch2-catch1", ex2); [](http://example.com/codeflow?start=32&length=34)

Consider also checking if we can successfully access ```ex``` here.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 13), assuming CI is passing
