### PR TITLE
 Editor completion: tests for non-block for completion items

### LINKED ISSUE #29112: Editor Completion -- Support CompletionOptions.BlockForCompletionItems to enable TestNoBlockOnCompletionItems* tests [impacts TypeScript and F#]
**Version Used**: 

**Steps to Reproduce**:

1. 
2. 
3. 

**Expected Behavior**:

**Actual Behavior**:

### LINKED ISSUE #31287: async completion: revisit AssertNoCompletionSession for non-blocking scenarios
Wait for 5 seconds looks suspicious.

### PR DESCRIPTION
**Pull request by ivanbasov**
Fixes #29112 
Fixes #31287 

Tagging @AmadeusW as well

Let us agree how BlockForCompletionItems = false works in the new completion:
1. It does not block GetCompletionContextAsync, Update and Filter.
2. It blocks UIThread when executing CommitIfUnique

Please review TestNoBlockOnCompletionItems* (1-4) tests and let me know if either scenario or tests should be corrected.

Please let me know if you see a better approach for validation rather than one thread waiting for another.

Let us agree here and then include TypeScript and F# for review as well.

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@ivanbasov Since I'm not entirely familiar with this bit, what's the general goal of this code here? We're trying to test that in general async completion "works", or we're saying that some providers (TypeScript?) just don't block on commit characters because it's expected they're really slow?

**Comment by ivanbasov** [comment]
@jasonmalinowski, there are two changes comparing to the old completion:
1. CommitIfUnique now blocks the UI thread even if the block option is set to false. So, we have a change of behavior. Let us validate it within Roslyn and then I'll add F# and TypeScript folks for a sign off.
2. Test approach changed. I extracted this scenario into ModernCompletionTestState.AssertNoCompletionSessionWithNoBlock. Let us see if we are fine with this test approach (I do not like Task.Delays here) or if we can improve it.

Editor will not block if GetCompletionContextAsync, UpdateAsync or SortAsync are executed for a long time. Our existing tests TestNoBlockOnCompletionItems1, TestNoBlockOnCompletionItems2 and ones calling AssertNoCompletionSessionWithNoBlock should check this.

**Comment by jasonmalinowski** [comment]
So what behavior of Roslyn's then is this testing that isn't just testing core editor behavior?

> CommitIfUnique now blocks the UI thread even if the block option is set to false. So, we have a change of behavior. Let us validate it within Roslyn and then I'll add F# and TypeScript folks for a sign off.

I'd reach out to them first; my impression is that was built for them -- we wouldn't have wanted to use it.

**Comment by ivanbasov** [comment]
@amcasey and @brettfo, could you please take a look if `TestNoBlockOnCompletionItems3`and `TestNoBlockOnCompletionItems4` work for you? 

Those tests cover `CommitIfUnique`scenarios in the new completion. The new completion Blocks on `CommitIfUnique` even if the _Block_ option is set to _false_.

We would like to get F# and TypeScript signoffs for this.

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb [hunk 1]
```diff
@@ -3429,61 +3429,149 @@ class C
...
+                Else
+                    Dim task1 As Task = Nothing
+                    Dim task2 As Task = Nothing
+
+                    Dim providerCalledHandler = Sub()
+                                                    task1 = Task.Run(Sub()
+                                                                         ' 2. Hang here as well.
+                                                                         Dim completionItem = state.GetSelectedItemOpt()
+                                                                     End Sub)
+                                                    Task.Delay(250)
```
Comment (amcasey) [inline src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: My VB's pretty rusty, but it looks like the resulting task isn't consumed.  Does that mean there's never a delay?

**Comment by amcasey** [comment]
@ivanbasov Happy to take a look but I think I'm going to need a plain-language explanation of the steps taken by the test.

**Comment by ivanbasov** [comment]
> @ivanbasov Happy to take a look but I think I'm going to need a plain-language explanation of the steps taken by the test.

Thank you, @amcasey ! I have added comments explaining scenarios updated. Could you please take a look and let me know if you need more explanations?

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb [hunk 2]
```diff
@@ -3429,61 +3429,174 @@ class C
...
+                Else
+                    Dim task1 As Task = Nothing
+                    Dim task2 As Task = Nothing
+
+                    Dim providerCalledHandler = Sub()
+                                                    task1 = Task.Run(Sub()
+                                                                         ' 2. Hang here as well.
+                                                                         Dim completionItem = state.GetSelectedItemOpt()
+                                                                     End Sub)
+                                                    Thread.Sleep(250)
```
Comment (amcasey) [inline src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: I'm still not clear on what the `Sleep` accomplishes.  Maybe it's supposed to be in `task2`?

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb [hunk 3]
```diff
@@ -3429,61 +3429,174 @@ class C
...
+                    Await state.AssertNoCompletionSession()
+                    Assert.Contains("System", state.GetLineTextFromCaretPosition())
+                Else
+                    Dim task1 As Task = Nothing
+                    Dim task2 As Task = Nothing
+
+                    Dim providerCalledHandler = Sub()
+                                                    task1 = Task.Run(Sub()
+                                                                         ' 2. Hang here as well.
+                                                                         Dim completionItem = state.GetSelectedItemOpt()
```
Comment (amcasey) [inline src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: So this blocks until the `tcs.SetResult` call?

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb [hunk 4]
```diff
@@ -3429,61 +3429,174 @@ class C
...
-        <InlineData(CompletionImplementation.Modern, Skip:="https://github.com/dotnet/roslyn/issues/29112")>
+        <MemberData(NameOf(AllCompletionImplementations))>
         <WpfTheory, Trait(Traits.Feature, Traits.Features.Completion)>
         Public Async Function TestNoBlockOnCompletionItems4(completionImplementation As CompletionImplementation) As Task
+            ' This test verifies a scenario with the following conditions:
+            ' a. A slow completion provider
+            ' b. The block option set to false.
+            ' Scenario:
+            ' 1. Type 'Sys'
+            ' 2. Send CommitIfUnique (Ctrl + space)
```
Comment (amcasey) [inline src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: CommitIfUnique is always triggered by an explicit user action, correct?

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb [hunk 5]
```diff
@@ -3429,61 +3429,174 @@ class C
...
+                                                                         End Try
+                                                                     End Sub)
+                                                End Sub
+
+                    Try
+                        AddHandler provider.ProviderCalled, providerCalledHandler
+
+                        ' In the new completion, when pressed <ctrl>-<space>, we have to wait for the aggregate operation to complete.
+                        ' 1. Hang here.
+                        state.SendCommitUniqueCompletionListItem()
```
Comment (amcasey) [inline src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: If this blocks until completion has been committed, aren't `task1` and `task2` already complete when it returns?  If so, what is the `WhenAll` for?

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb [hunk 6]
```diff
@@ -3429,61 +3429,174 @@ class C
...
+                                                                             tcs.SetResult(True)
+                                                                         End Try
+                                                                     End Sub)
+                                                End Sub
+
+                    Try
+                        AddHandler provider.ProviderCalled, providerCalledHandler
+
+                        ' In the new completion, when pressed <ctrl>-<space>, we have to wait for the aggregate operation to complete.
+                        ' 1. Hang here.
```
Comment (amcasey) [inline src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: Is a cancellation dialog offered while the UI thread is blocked?

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb [hunk 7]
```diff
@@ -3429,61 +3429,174 @@ class C
...
+            ' 1. Type 'Sys'
+            ' 2. Send CommitIfUnique (Ctrl + space)
+            ' 3. Wait for 250ms.
+            ' 4. Verify that there is no completion window shown. In the new completion, we can just start the verification and check that the verification is still running.
+            ' 5. Check that the commit is not yet provided: there is 'Sys' but no 'System'
+            ' 6. The next statement in the UI thread after CommitIfUnique is typing 'a'.
+            ' 7. Simulate unblocking the provider.
+            ' 8. Verify that 
+            ' 8.a. The old completion adds 'a' to 'Sys' and displays 'Sysa'. CommitIfUnique is canceled because it was interrupted by typing 'a'.
+            ' 8.b. The new completion completes CommitIfUnique and then add 'a'.
```
Comment (amcasey) [inline src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: I can't remember all the details of our discussion.  We're going with 8.b. because 8.a. is impossible in the new system?

**Comment by amcasey** [comment]
Oh, and the comments helped a lot.  Thanks, @ivanbasov!

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb (hunk 3 above)
Comment (ivanbasov) [reply src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: yes, 
Dim completionItem = state.GetSelectedItemOpt()
and 
 state.SendCommitUniqueCompletionListItem()
are both blocked by 
tcs.SetResult 

---
In reply to: [239971037](https://github.com/dotnet/roslyn/pull/31534#discussion_r239971037) [](ancestors = 239971037)

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb (hunk 4 above)
Comment (ivanbasov) [reply src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: Yes, CommitIfUnique is an explicit user action: Ctrl + Space

**Comment by AmadeusW** [comment]
> Is a cancellation dialog offered while the UI thread is blocked?

@amcasey yes, the wait dialog appears when a command takes more time than certain threshold. 
Slow provider may cause the wait dialog to open by virtue of completion implementing `ICommandHandler`

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb (hunk 5 above)
Comment (ivanbasov) [reply src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: `task1` can still been executing when `state.SendCommitUniqueCompletionListItem()` is done. I'd like to guarantee the order of actions. Checks 
```
                 Await state.WaitForAsynchronousOperationsAsync()
                 Await state.AssertNoCompletionSession()
                 Assert.Contains("System", state.GetLineTextFromCaretPosition())
```
should not be started before `task1` completion. `task2` is added here just for consistency.

**Comment by amcasey** [comment]
@AmadeusW Great!  As long as completion is cancellable, I believe TS is fine with having it block on CommitIfUnique.

**Comment by CyrusNajmabadi** [comment]
That's potentially a problem.  We explicitly decided to *not* have a wait dialog for completion/typng *ever* in the early days of roslyn.  That's because a wait dialog sensibly comes to the user when they did an explicit action that they thought could take a long time.   

If we show wait dialog for completion, that's bad on several levels:
1. it's flashy and distracting.  this is not good when typing.
2. the dialog can capture keystrokes.  imagine i keep typing, but the wait dialog now grabs one of my characters (like hitting space).  This leads to strange outcomes.
3. the dialog is not actually useful.  Consider this: The dialog effectively comes up because things are running too slowly. So waht can the user do at that point?  They can either wait for things to finish (in which case the dialog wasn't helpful), or they can try to cancel.  But if they do the latter, and then type again, it's likely they'll hit the dialog again, just annoying them more.

Effectively, this basically harms the experience a bunch (especially around temporary hiccoughs), while not really making anything better.  This is particularly true because this relates to typing.  Wait-dialogs for other scnearios are totally appropriate and reasonable.  But, with typing, it just ends up bad.  

--

Again, this was tried and thought through in the past, and the outcome was a deliberately thought through decision.  We should stick with that decision unless something major has changed here (which doesn't seem to be the case for me).

**Comment by CyrusNajmabadi** [comment]
> Please review TestNoBlockOnCompletionItems* (1-4) tests and let me know if either scenario or tests should be corrected.

What happens if the user commits with something else (like tab, space, character, etc.)?

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb (hunk 7 above)
Comment (ivanbasov) [reply src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: Yes, in the new system, if we would cancel it on on each immediate keypress, it seems to be inconsistent.
Therefore, if we want to be able to cancel it after some time, it is difficult to define a valid threshold: do not cancel if pressed before, and cancel if pressed after it.

**Comment by ivanbasov** [comment]
> > Please review TestNoBlockOnCompletionItems* (1-4) tests and let me know if either scenario or tests should be corrected.
> 
> What happens if the user commits with something else (like tab, space, character, etc.)?

@CyrusNajmabadi 
1. Here we test hanging on GetCompletionContext or Update (with block set to false).
2. If GetCompletionContext was still running; tab, space, character just breaks the completion. There is no commit. There is no change comparing to the original behavior.

**Comment by ivanbasov** [comment]
@jinujoseph , @jasonmalinowski , @AmadeusW , @olegtk and @ivanbasov discussed the issue offline.
We found there are two consistent scenarios:
1. Old completion: if the blocking option is set to false, then CommitIfUnique can be canceled by pressing keys during calculations. 
2. New completion: if the blocking option is set to false, but the CommitIfUnique ignores the blocking option and proceeds up to the end:
a. The completion should be completed.
b. Keys pressed should be queued for next actions.
c. The progress bar with the cancellation button should be displayed.

So, both scenarios seem to be consistent from our perspective. We agreed that if @amcasey and @brettfo do not find any serious contradictions, we will ship the current implementation with the feature flag set ON.

We found that implementing Scenario 1 on the editor side in the new completion is difficult. We would prefer avoiding it if there would not be strong user concerns. I have created https://devdiv.visualstudio.com/DevDiv/_workitems/edit/750631 to track user feedback for addressed for the issue.

@amcasey and @brettfo we would like you to review/signoff the PR.

**Comment by minestarks** [comment]
Thanks @ivanbasov - we'd like to test this out in a few of our scenarios, could you give us a build or machine to try it out on?

**Comment by ivanbasov** [comment]
> Thanks @ivanbasov - we'd like to test this out in a few of our scenarios, could you give us a build or machine to try it out on?

Thank you, minestarks! I have replied over email with details.

**Comment by minestarks** [comment]
@ivanbasov thanks. I gave this a spin for TypeScript. When I artificially introduce long delays in completion, cancellation works as expected.

However I'm getting weird dismiss / retrigger behavior in the most basic scenario. The completion list isn't triggered after typing `.`.

BAD:
baddismiss

EXPECTED (behavior without these bits applied):
gooddismiss

**Comment by amcasey** [comment]
Looks okay for TS (cc @minestarks)

File: src/EditorFeatures/TestUtilities2/Intellisense/ModernCompletionTestState.vb [hunk 8]
```diff
@@ -123,10 +123,22 @@ Namespace Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense
...
+            If session Is Nothing Then
+                Return
+            End If
+
+            If session.IsDismissed Then
+                Return
             End If
+
+            Dim completionItems = session.GetComputedItems(CancellationToken.None)
+            Assert.True(session.IsDismissed OrElse completionItems.Items.Count() = 0)
```
[the remark this answers is not in the document]
Comment (ivanbasov) [reply src/EditorFeatures/TestUtilities2/Intellisense/ModernCompletionTestState.vb]: Thanks! Not necessary now. Removing

---
In reply to: [247000481](https://github.com/dotnet/roslyn/pull/31534#discussion_r247000481) [](ancestors = 247000481)

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb [hunk 9]
```diff
@@ -3429,61 +3429,174 @@ class C
...
+                    Await state.WaitForAsynchronousOperationsAsync()
+                    Await state.AssertNoCompletionSession()
+                    Assert.Contains("System", state.GetLineTextFromCaretPosition())
+                Else
+                    Dim task1 As Task = Nothing
+                    Dim task2 As Task = Nothing
+
+                    Dim providerCalledHandler = Sub()
+                                                    task1 = Task.Run(Sub()
+                                                                         ' 2. Hang here as well.
```
[the remark this answers is not in the document]
Comment (ivanbasov) [reply src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: This one waits for the provider to respond. The provider is blocked.

Added a comment.

---
In reply to: [246999922](https://github.com/dotnet/roslyn/pull/31534#discussion_r246999922) [](ancestors = 246999922)

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb [hunk 10]
```diff
@@ -3429,61 +3429,174 @@ class C
...
+
+                        Assert.NotNull(task1)
+                        Assert.NotNull(task2)
+                        Await Task.WhenAll(task1, task2)
+
+                        Await state.WaitForAsynchronousOperationsAsync()
+                        Await state.AssertNoCompletionSession()
+                        Assert.Contains("System", state.GetLineTextFromCaretPosition())
+                    Finally
+                        RemoveHandler provider.ProviderCalled, providerCalledHandler
```
[the remark this answers is not in the document]
Comment (ivanbasov) [reply src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: Agree. This is an overprotection. Not necessary for tests. Removing.

---
In reply to: [246999415](https://github.com/dotnet/roslyn/pull/31534#discussion_r246999415) [](ancestors = 246999415)

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb [hunk 11]
```diff
@@ -3429,61 +3429,174 @@ class C
...
+                                                                         Dim completionItem = state.GetSelectedItemOpt()
+                                                                     End Sub)
+                                                    task2 = Task.Run(Sub()
+                                                                         Thread.Sleep(250)
+                                                                         Try
+                                                                             ' 3. Check that the other task is running/hanging.
+                                                                             Assert.Equal(TaskStatus.Running, task1.Status)
+                                                                             Assert.Contains("Sys", state.GetLineTextFromCaretPosition())
+                                                                             Assert.DoesNotContain("System", state.GetLineTextFromCaretPosition())
+                                                                         Finally
```
[the remark this answers is not in the document]
Comment (ivanbasov) [reply src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: To avoid hangs waiting for the task to complete if any of asserts failed. Added a comment

---
In reply to: [246999978](https://github.com/dotnet/roslyn/pull/31534#discussion_r246999978) [](ancestors = 246999978)

File: src/EditorFeatures/TestUtilities2/Intellisense/ModernCompletionTestState.vb (hunk 8 above)
[the remark this answers is not in the document]
Comment (ivanbasov) [reply src/EditorFeatures/TestUtilities2/Intellisense/ModernCompletionTestState.vb]: Actually, we can dismiss the session during computations and provide completion items. We can also do not dismiss a session but provide no completion items.
We we can do both at the same time.

Even one of those conditions is enough to say that there is no active completion.

---
In reply to: [247000481](https://github.com/dotnet/roslyn/pull/31534#discussion_r247000481) [](ancestors = 247000481)

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb [hunk 12]
```diff
@@ -3429,61 +3429,174 @@ class C
...
+                                                                         End Try
+                                                                     End Sub)
+                                                End Sub
+
+                    Try
+                        AddHandler provider.ProviderCalled, providerCalledHandler
+
+                        ' In the new completion, when pressed <ctrl>-<space>, we have to wait for the aggregate operation to complete.
+                        ' 1. Hang here.
+                        state.SendCommitUniqueCompletionListItem()
```
[the remark this answers is not in the document]
Comment (ivanbasov) [reply src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: Yes, it guarantees because SendCommitUniqueCompletionListItem is a synchronous operation. Added a comment.

---
In reply to: [247000131](https://github.com/dotnet/roslyn/pull/31534#discussion_r247000131) [](ancestors = 247000131)

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb [hunk 13]
```diff
@@ -3556,61 +3556,179 @@ class C
...
+                    ' SendCommitUniqueCompletionListItem is a synchronous operation. 
+                    ' It guarantees that ProviderCalled will be triggered and after that the completion will hang waiting for a task to be resolved.
+                    ' In the new completion, when pressed <ctrl>-<space>, we have to wait for the aggregate operation to complete.
+                    ' 1. Hang here.
+                    state.SendCommitUniqueCompletionListItem()
+
+                    Assert.NotNull(task1)
+                    Assert.NotNull(task2)
+                    Await Task.WhenAll(task1, task2)
+                    RemoveHandler provider.ProviderCalled, providerCalledHandler
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: Honestly just remove it entirely -- if it's a problem we have bigger problems.

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb [hunk 14]
```diff
@@ -3556,61 +3556,179 @@ class C
...
+                    Assert.DoesNotContain("System", state.GetLineTextFromCaretPosition())
+                    tcs.SetResult(True)
+                Else
+                    Dim task1 As Task = Nothing
+                    Dim task2 As Task = Nothing
+
+                    Dim providerCalledHandler =
+                        Sub()
+                            task1 = Task.Run(
+                            Sub()
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: This probably *should* go in one more level. But this is vastly more readable, thanks.

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb [hunk 15]
```diff
@@ -3556,61 +3556,179 @@ class C
...
+                                ' 2. Hang here as well: getting items is waiting provider to respond.
+                                Dim completionItem = state.GetSelectedItemOpt()
+                            End Sub)
+                            task2 = Task.Run(
+                                Sub()
+                                    Thread.Sleep(250)
+                                    Try
+                                        ' 3. Check that the other task is running/hanging.
+                                        Assert.Equal(TaskStatus.Running, task1.Status)
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: This is potentially a race: there's no guarantee that task1 will in fact have started yet if the thread pool is sufficiently slammed. The thread pool also doesn't make any guarantees (I don't think) about fairness: this might be able to run before the other one does.
