### PR TITLE
Disallow declaration of indexers in absence of proper DefaultMemberAttribute.

### LINKED ISSUE #75032: Assert failure when building runtime: Synthesized attribute constructor missing
**Version Used**: 9cf652f838e2e09872f9f03ebdd00b353c480d13

Happens when building the `src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj` project. From the stack, the `DefaultMemberAttribute` constructor is not present, and we expect it to be.

```
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error : Process terminated. Assertion failed. [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.TrySynthesizeAttribute(WellKnownMember constructor, ImmutableArray`1 arguments, ImmutableArray`1 namedArguments, Boolean isOptionalUse) in /workspaces/roslyn/src/Compilers/CSharp/Portable/Symbols/Compilation_WellKnownMembers.cs:line 399 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamedTypeSymbol.AddSynthesizedAttributes(PEModuleBuilder moduleBuilder, ArrayBuilder`1& attributes) in /workspaces/roslyn/src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs:line 1714 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbol.GetCustomAttributesToEmit(PEModuleBuilder moduleBuilder, Boolean emittingAssemblyAttributesInNetModule) in /workspaces/roslyn/src/Compilers/CSharp/Portable/Emitter/Model/SymbolAdapter.cs:line 100 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.Symbol.GetCustomAttributesToEmit(PEModuleBuilder moduleBuilder) in /workspaces/roslyn/src/Compilers/CSharp/Portable/Emitter/Model/SymbolAdapter.cs:line 89 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.SymbolAdapter.Microsoft.Cci.IReference.GetAttributes(EmitContext context) in /workspaces/roslyn/src/Compilers/CSharp/Portable/Emitter/Model/SymbolAdapter.cs:line 43 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.Cci.ReferenceIndexerBase.VisitTypeDefinitionNoMembers(ITypeDefinition typeDefinition) in /workspaces/roslyn/src/Compilers/Core/Portable/PEWriter/ReferenceIndexerBase.cs:line 273 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.Cci.ReferenceIndexerBase.Visit(ITypeDefinition typeDefinition) in /workspaces/roslyn/src/Compilers/Core/Portable/PEWriter/ReferenceIndexerBase.cs:line 299 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.Cci.MetadataVisitor.Visit(IEnumerable`1 types) in /workspaces/roslyn/src/Compilers/Core/Portable/PEWriter/MetadataVisitor.cs:line 379 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.Cci.ReferenceIndexer.Visit(CommonPEModuleBuilder module) in /workspaces/roslyn/src/Compilers/Core/Portable/PEWriter/ReferenceIndexer.cs:line 35 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.Cci.MetadataWriter.CreateIndices() in /workspaces/roslyn/src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs:line 483 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.Cci.MetadataWriter.BuildMetadataAndIL(PdbWriter nativePdbWriterOpt, BlobBuilder ilBuilder, PooledBlobBuilder& mappedFieldDataBuilder, PooledBlobBuilder& managedResourceDataBuilder, Blob& mvidFixup, Blob& mvidStringFixup) in /workspaces/roslyn/src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs:line 1779 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken) in /workspaces/roslyn/src/Compilers/Core/Portable/PEWriter/PeWriter.cs:line 111 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.Compilation.SerializePeToStream(CommonPEModuleBuilder moduleBeingBuilt, DiagnosticBag metadataDiagnostics, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getMetadataPeStreamOpt, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, RebuildData rebuildData, Boolean metadataOnly, Boolean includePrivateMembers, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken) in /workspaces/roslyn/src/Compilers/Core/Portable/Compilation/Compilation.cs:line 3361 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider metadataPEStreamProvider, EmitStreamProvider pdbStreamProvider, RebuildData rebuildData, Func`2 testSymWriterFactory, DiagnosticBag diagnostics, EmitOptions emitOptions, Nullable`1 privateKeyOpt, CancellationToken cancellationToken) in /workspaces/roslyn/src/Compilers/Core/Portable/Compilation/Compilation.cs:line 3260 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 generators, ImmutableArray`1 additionalTextFiles, AnalyzerConfigSet analyzerConfigSet, ImmutableArray`1 sourceFileAnalyzerConfigOptions, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, ErrorLogger errorLogger, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, AnalyzerDriver& analyzerDriver, Nullable`1& generatorTimingInfo) in /workspaces/roslyn/src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs:line 1445 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) in /workspaces/roslyn/src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs:line 956 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken) in /workspaces/roslyn/src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs:line 781 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw) in /workspaces/roslyn/src/Compilers/Shared/Csc.cs:line 28 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[T](Boolean utf8Output, TextWriter textWriter, Func`2 func) in /workspaces/roslyn/src/Compilers/Core/CommandLine/ConsoleUtil.cs:line 53 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader) in /workspaces/roslyn/src/Compilers/Shared/Csc.cs:line 28 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter) in /workspaces/roslyn/src/Compilers/Shared/BuildClient.cs:line 196 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter, String pipeName) in /workspaces/roslyn/src/Compilers/Shared/BuildClient.cs:line 167 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc, CompileOnServerFunc compileOnServerFunc, ICompilerServerLogger logger) in /workspaces/roslyn/src/Compilers/Shared/BuildClient.cs:line 117 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.MainCore(String[] args) in /workspaces/roslyn/src/Compilers/CSharp/csc/Program.cs:line 37 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args) in /workspaces/roslyn/src/Compilers/CSharp/csc/Program.cs:line 18 [/workspaces/runtime/src/coreclr/nativeaot/Test.CoreLib/src/Test.CoreLib.csproj]
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #75032.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs [hunk 1]
```diff
@@ -1713,7 +1713,7 @@ internal override void AddSynthesizedAttributes(PEModuleBuilder moduleBuilder, r
 
                 AddSynthesizedAttribute(ref attributes, compilation.TrySynthesizeAttribute(
                     WellKnownMember.System_Reflection_DefaultMemberAttribute__ctor,
-                    ImmutableArray.Create(defaultMemberNameConstant)));
+                    ImmutableArray.Create(defaultMemberNameConstant), isOptionalUse: true));
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs:1716]: I guess my question is, why is this ok to not emit?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs:1716]: It is not ok, but this is what we were doing for many years. If we start reporting an error (like VB), we are going to break runtime build, at least. I don't think this is worth it. The scenario is very uncommon.

Comment (333fred) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs:1716]: My feeling is, this is a test-only component of NativeAOT that is fairly new. It seems likely to me that it should be including this attribute, and not having it could end up masking a bug. /cc @agocke

Comment (agocke) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs:1716]: What’s the actual proposal? That the compiler emits an error for this case and the runtime fixes the test code?

I’m fine with that.

Is it possible that anyone could hit the error without hitting the assert? If so the question really is what happens if you get a bug from windows or office about the new error. Will you change the compiler or tell them to fix their code? Whatever is the answer to that question is the path I would take.

Comment (333fred) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs:1716]: > That the compiler emits an error for this case and the runtime fixes the test code?

That's what I would do, yes.

Comment (333fred) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs:1716]: > Is it possible that anyone could hit the error without hitting the assert?

Sure. The runtime does right now 🙂.

**Review by 333fred — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs [hunk 2]
```diff
@@ -1796,27 +1796,30 @@ protected override void AfterMembersCompletedChecks(BindingDiagnosticBag diagnos
...
+                    {
+                        // Required member '{0}' should not be attributed with 'ObsoleteAttribute' unless the containing type is obsolete or all constructors are obsolete.
+                        diagnostics.Add(ErrorCode.WRN_ObsoleteMembersShouldNotBeRequired, member.GetFirstLocation(), member);
+                    }
                 }
             }
 
+            if (Indexers.FirstOrDefault() is PropertySymbol indexerSymbol)
+            {
+                Binder.GetWellKnownTypeMember(DeclaringCompilation, WellKnownMember.System_Reflection_DefaultMemberAttribute__ctor, diagnostics, indexerSymbol.TryGetFirstLocation() ?? GetFirstLocation());
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs:1820]: >indexerSymbol.TryGetFirstLocation() ?? GetFirstLocation() [](http://example.com/codeflow?start=145&length=57)

nit: I didn't follow the intricacy of the `Location` logic. Do we have a test where `indexerSymbol.TryGetFirstLocation()` is null?

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 5) with a clarifying question

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceNamedTypeSymbol.cs:1820]: This is defense in depth, theoretically the API can return null, even though we don't expect it to. This pattern is also used elsewhere in this function.

**Review by jcouv — APPROVED** [review]
