### PR TITLE
No IDE0060 for unused parameter in partial method implementation

### LINKED ISSUE #57814: False positive IDE0060 for partial method with SG
**Version Used**: 
VS 17.0.0

**Steps to Reproduce**:

1. Write a source generator to define a partial method with parameter for a class
2. Implement the partial method in user code, without touching the parameter

**Expected Behavior**:
No IDE0060 reported, at least when the source generator is fully loaded.

**Actual Behavior**:
IDE0060 unused parameter reported for the partial method.

Should we disable IDE0060 for any partial method? Their signature should match for different sources of code, and user code may not change it.

### PR DESCRIPTION
**Pull request by louis-z**
If a partial method implementation does not use a parameter, do not generate an IDE0060 diagnostic.

Also, fix minor typos ("Unsued" vs "Unused")

Fixes #57814

### CODE REVIEW

File: src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs [hunk 1]
```diff
@@ -216,7 +216,7 @@ private bool IsUnusedParameterCandidate(IParameterSymbol parameter)
                     method.IsAbstract ||
                     method.IsVirtual ||
                     method.IsOverride ||
-                    method.PartialImplementationPart != null ||
```
Comment (louis-z) [inline src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs:219]: Wasn't sure if I should replace `method.PartialImplementationPart != null` by `method.PartialDefinitionPart != null` or keep both conditions, but it turns out the former condition does not appear to be needed to make the tests pass... Let me know if you think I should put it back.

**Review by Youssef1313 — COMMENTED** [review]
Consider adding a test with partial definition without implementation.

File: src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs (hunk 1 above)
Comment (louis-z) [reply src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs:219]: NVM, we do need `method.PartialImplementationPart != null` for certain tests to pass...

**Comment by louis-z** [comment]
> Consider adding a test with partial definition without implementation.

Just did.

File: src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs [hunk 2]
```diff
@@ -217,6 +217,7 @@ private bool IsUnusedParameterCandidate(IParameterSymbol parameter)
                     method.IsVirtual ||
                     method.IsOverride ||
                     method.PartialImplementationPart != null ||
+                    method.PartialDefinitionPart != null ||
```
Comment (Youssef1313) [inline src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs:220]: I don't know, but I feel the check is *too* strong.

Comment (louis-z) [reply src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs:220]: Given that
- a partial method definition might be generated by some tool, with a parameter list as part of its signature
- the corresponding implementation must have the same signature

I believe it's pointless to run the IDE0060 rule on the implementation (i.e. when `method.PartialDefinitionPart != null` ).

After all, if any of the parameters are unused by the implementation, what can the developer do? They probably have no control over the autogenerated definition and the implementation's signature must match the definition's...

Comment (Youssef1313) [reply src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs:220]: I think we should specifically check for generated code. This check can probably be easier when https://github.com/dotnet/roslyn/pull/63447/ is merged

Comment (louis-z) [reply src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs:220]: I didn't know about this upcoming `IsGeneratedCode` flag. You're right, waiting for it sounds like a good idea.

Comment (mavasani) [reply src/Analyzers/Core/Analyzers/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.SymbolStartAnalyzer.cs:220]: I am not sure if `IsGeneratedCode` check helps here. The callback would only be made for non-generated code for IDE0060 analyzer, and you can't check whether or not the other partial symbol is generated or not from this callback.

**Review by mavasani — APPROVED** [review]

**Comment by mavasani** [comment]
@louis-z Can you please resolve merge conflicts?
