### PR TITLE
Fix commit of import completion

### LINKED ISSUE #35614: Committing unimorted type item doesn't add the missing using directive

### PR DESCRIPTION
**Pull request by genlu**
Fix #35614, which is a regression introduced in #35434. I have also added a completion command handler test to cover this.

@dpoeschl @ivanbasov @jasonmalinowski @CyrusNajmabadi for review

@vatsalyaagrawal @jinujoseph We need this in 16.1

**Customer and scenario info**
**Who is impacted by this bug?**
Users who enabled import completion
**What is the customer scenario and impact of the bug?**
Committing import completion doesn't add using, which basically completely breaks this feature.
**What is the workaround?**
None
**How was the bug found?**
dogfooding
**If this fix is for a regression - what had regressed, when was the regression introduced, and why was the regression originally missed?**
This is a regression from previous inserted version. The regression was missed because (1) A through manual testing wasn't done at the time of merging (2) There's gap in our unit test, which is fixed as part of this PR.

### CODE REVIEW

File: src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CompletionSource.cs [hunk 1]
```diff
@@ -348,55 +348,56 @@ public VSCompletionItemData(string displayText, ImageElement icon, ImmutableArra
             Document document,
             RoslynCompletionItem roslynItem)
         {
-            if (roslynItem.IsCached && s_roslynItemToVsItemData.TryGetValue(roslynItem, out var itemData))
+            VSCompletionItemData itemData;
+
+            if (roslynItem.IsCached && s_roslynItemToVsItemData.TryGetValue(roslynItem, out var boxedItemData))
             {
-                return new VSCompletionItem(
```
Comment (genlu) [inline src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CompletionSource.cs]: so the actual bug is here, i didn't add the Roslyn item to the property bag

File: src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CompletionSource.cs [hunk 2]
```diff
@@ -49,8 +49,8 @@ internal class CompletionSource : ForegroundThreadAffinitizedObject, IAsyncCompl
         private static readonly EditorOptionKey<bool> NonBlockingCompletionEditorOption = new EditorOptionKey<bool>(NonBlockingCompletion);
 
         // Use CWT to cache data needed to create VSCompletionItem, so the table would be cleared when Roslyn completion item cache is cleared.
-        private static readonly ConditionalWeakTable<RoslynCompletionItem, VSCompletionItemData> s_roslynItemToVsItemData =
-            new ConditionalWeakTable<RoslynCompletionItem, VSCompletionItemData>();
+        private static readonly ConditionalWeakTable<RoslynCompletionItem, StrongBox<VSCompletionItemData>> s_roslynItemToVsItemData =
+            new ConditionalWeakTable<RoslynCompletionItem, StrongBox<VSCompletionItemData>>();
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CompletionSource.cs]: Hmm, I had thought that VSCompletionItemData was a struct for some reason. Why did we need the StrongBox again if it's a class?

Comment (jasonmalinowski) [reply src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CompletionSource.cs]: (I know I mentioned it in my previous review, but I'm not remembering why I thought that was necessary. It's also Friday and I'm a bit sleepy so it could be something dumb.)

Comment (genlu) [reply src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CompletionSource.cs]: Oh, right, I forgot to make it a struct in this PR (but done it in a stale branch which I copied code from)

Comment (jasonmalinowski) [reply src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CompletionSource.cs]: @genlu: ah, that's what it was. thanks.
