### PR TITLE
Handle field reference from semantic model in non-field-backed property

### LINKED ISSUE #75893: visual studio provider errors with use of field keyword - when typing
**Version Used**: 
Visual Studio 17.12.0
c# project with language preview enabled

**Steps to Reproduce**:

1. In a type in:
```
    private string? foo = null;
    public string Foo
    {
        get
        {
            if (this.foo is null)
            {
                FieldInfo field = typeof(String).GetField(nameof(string.Length), BindingFlags.Public | BindingFlags.Instance)!;
                this.foo = field.GetValue("hi");
            }

            return this.foo;
        }
    }
```
2. When typeing in the `field.GetValue` part, many provider errors are produced by Visual Studio

**Expected Behavior**:
no provider errors

**Actual Behavior**:
The call stack of all of them looks similar enough that I'll only include one.

Errors in:
```
UnnamedSymbolCompletionProvider
ExtensionMethodImportCompletionProvider
PreprocessorCompletionProvider
TypeImportCompletionProvider
KeywordCompletionProvider
EnumAndCompletionListTagCompletionProvider
AwaitCompletionProvider
System.InvalidOperationException : Unexpected value 'FooProj.FooClass.Foo.get' of type 'Microsoft.CodeAnalysis.CSharp.Symbols.SourcePropertyAccessorSymbol'
at Microsoft.CodeAnalysis.CSharp.Binder.BindFieldExpression(FieldExpressionSyntax node,BindingDiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.Binder.g__bindExpressionInternal|337_0(ExpressionSyntax node,BindingDiagnosticBag diagnostics,Boolean invoked,Boolean indexed)
at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node,BindingDiagnosticBag diagnostics,Boolean invoked,Boolean indexed)
at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node,BindingDiagnosticBag diagnostics,Boolean invoked,Boolean indexed)
at Microsoft.CodeAnalysis.CSharp.Binder.BindLeftOfPotentialColorColorMemberAccess(ExpressionSyntax left,BindingDiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.Binder.BindMemberAccess(MemberAccessExpressionSyntax node,Boolean invoked,Boolean indexed,BindingDiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.Binder.g__bindExpressionInternal|337_0(ExpressionSyntax node,BindingDiagnosticBag diagnostics,Boolean invoked,Boolean indexed)
at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node,BindingDiagnosticBag diagnostics,Boolean invoked,Boolean indexed)
at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node,BindingDiagnosticBag diagnostics,Boolean invoked,Boolean indexed)
at Microsoft.CodeAnalysis.CSharp.Binder.BindAssignment(AssignmentExpressionSyntax node,BindingDiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.Binder.g__bindExpressionInternal|337_0(ExpressionSyntax node,BindingDiagnosticBag diagnostics,Boolean invoked,Boolean indexed)
at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node,BindingDiagnosticBag diagnostics,Boolean invoked,Boolean indexed)
at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node,BindingDiagnosticBag diagnostics,Boolean invoked,Boolean indexed)
at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(CSharpSyntaxNode node,ExpressionSyntax syntax,Boolean allowsAnyExpression,BindingDiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(ExpressionStatementSyntax node,BindingDiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node,BindingDiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node,BindingDiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node,BindingDiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node,BindingDiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.Binder.BindPossibleEmbeddedStatement(StatementSyntax node,BindingDiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.Binder.BindIfStatement(IfStatementSyntax node,BindingDiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node,BindingDiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node,BindingDiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node,BindingDiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node,BindingDiagnosticBag diagnostics)
at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.EnsureNullabilityAnalysisPerformedIfNecessary()
at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node)
at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode(CSharpSyntaxNode node)
at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node,CSharpSyntaxNode& bindableNode,BoundNode& lowestBoundNode,BoundNode& highestBoundNode,BoundNode& boundParent)
at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetTypeInfoWorker(CSharpSyntaxNode node,CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CSharp.SpeculativeSemanticModelWithMemberModel.GetTypeInfoWorker(CSharpSyntaxNode node,CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetTypeInfo(ExpressionSyntax expression,CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetTypeInfo(SemanticModel semanticModel,ExpressionSyntax expression,CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.SyntaxTokenExtensions.IsNumericTypeContext(SyntaxToken token,SemanticModel semanticModel,CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.CSharpSyntaxContext.CreateContextWorker(Document document,SemanticModel semanticModel,Int32 position,CancellationToken cancellationToken)
at Microsoft.CodeAnalysis.CSharp.Extensions.ContextQuery.CSharpSyntaxContextService.CreateContext(Document document,SemanticModel semanticModel,Int32 position,CancellationToken cancellationToken)
at async Microsoft.CodeAnalysis.Completion.Utilities.CreateSyntaxContextWithExistingSpeculativeModelAsync()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at async Microsoft.CodeAnalysis.CSharp.Completion.Providers.SpeculativeTCompletionProvider.ProvideCompletionsAsync()
at async Microsoft.CodeAnalysis.Completion.Providers.AbstractPreprocessorCompletionProvider.ProvideCompletionsAsync()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at async Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.GetUnionItemsFromDocumentAndLinkedDocumentsAsyncT
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at async Microsoft.CodeAnalysis.Completion.Providers.AbstractKeywordCompletionProvider`1.ProvideCompletionsAsyncTContext
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync()
```

### PR DESCRIPTION
**Pull request by cston**
Fixes #75893

### CODE REVIEW

**Review by RikkiGibson — APPROVED** [review]

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/Compilers/CSharp/Test/Emit3/FieldKeywordTests.cs [hunk 1]
```diff
@@ -10464,6 +10464,40 @@ .locals init (System.Runtime.CompilerServices.DefaultInterpolatedStringHandler V
             VerifyMergedProperties(actualProperties, actualFields);
         }
 
+        [WorkItem("https://github.com/dotnet/roslyn/issues/75893")]
+        [Theory]
+        [CombinatorialData]
+        public void SpeculativeSemanticModel(bool includeLocal)
```
Comment (Youssef1313) [inline src/Compilers/CSharp/Test/Emit3/FieldKeywordTests.cs:10470]: Just FYI, doesn't have to be done in this PR, but when I previously worked on the feature, I have written relatively large amount of tests which also include SpeculativeSemanticModel. I haven't checked if the exact case in this test is one of those I wrote, but generally I think it may be a good idea to copy those tests. Some test outcomes may be different from the now-expected behavior and may require adjustments though.

The tests are here: https://github.com/dotnet/roslyn/blob/32d6c1db46fd613888d08970908257fbacf328ba/src/Compilers/CSharp/Test/Emit2/Semantics/PropertyFieldKeywordTests.cs

There was also this test:

https://github.com/dotnet/roslyn/blob/32d6c1db46fd613888d08970908257fbacf328ba/src/Compilers/CSharp/Test/Emit/PDB/PDBWinMdExpTests.cs#L246

And this:

https://github.com/dotnet/roslyn/blob/32d6c1db46fd613888d08970908257fbacf328ba/src/Compilers/CSharp/Test/Semantic/Semantics/InteractiveSemanticModelTests.cs#L99C21-L99C37

And https://github.com/dotnet/roslyn/blob/32d6c1db46fd613888d08970908257fbacf328ba/src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs#L2011, and finally https://github.com/dotnet/roslyn/blob/32d6c1db46fd613888d08970908257fbacf328ba/src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/ExpressionCompilerTests.cs#L6959C21-L6959C52

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit3/FieldKeywordTests.cs:10470]: >SpeculativeSemanticModel [](http://example.com/codeflow?start=20&length=24)

Consider adding a test for a success scenario (speculating with `field` works in a field-backed property), if we don't have one already.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 2)

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 2]
```diff
@@ -1465,9 +1465,12 @@ private BoundExpression BindFieldExpression(FieldExpressionSyntax node, BindingD
                     }
             }
 
+            // Field will be null when binding a field expression in a speculative
+            // semantic model when the property does not have a backing field.
```
[the remark this answers is not in the document]
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:1469]: It wasn't obvious what to assert here since the `Binder` is not specific to the semantic model (`IsSemanticModelBinder == false`), even when called from that code path.

File: src/Compilers/CSharp/Test/Emit3/FieldKeywordTests.cs (hunk 1 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Emit3/FieldKeywordTests.cs]: Thanks @Youssef1313 for links to your tests from the earlier branch. I had previously referenced the tests in `PropertyFieldKeywordTests` in https://github.com/dotnet/roslyn/issues/75398, and I've added a link to your comment there. I'll investigate the tests as part of that issue. In the meantime, this particular issue seemed straightforward enough to handle directly.
