### PR TITLE
Fixes #1766 by treating System.Void as the absence of a type.

### LINKED ISSUE #1766: VB's SyntaxGenerator.MethodDeclaration does not round-trip on System.Void
When passing a return type to VB's `SyntaxGenerator.MethodDeclaration` method, passing a type symbol for `System.Void` results in a `Function` rather than a `Sub`:

```VB
<Fact>
Public Sub MethodDeclarationCanRoundTrip()
    Dim tree = VisualBasicSyntaxTree.ParseText(
<x>
Public Sub Test()
End Sub</x>.Value)
    Dim compilation = VisualBasicCompilation.Create("AssemblyName", syntaxTrees:={tree})
    Dim model = compilation.GetSemanticModel(tree)
    Dim node = tree.GetRoot().DescendantNodes().First()
    Dim symbol = CType(model.GetDeclaredSymbol(node), IMethodSymbol)
    VerifySyntax(Of MethodBlockSyntax)(
        _g.MethodDeclaration("m", returnType:=_g.TypeExpression(symbol.ReturnType)),
<x>Sub m()
End Sub</x>.Value)
End Sub
```

This fails with:

```
Expected: Sub m()
          End Sub
Actual:   Function m() As Global.System.Void
          End Function
```

### PR DESCRIPTION
**Pull request by kentcb**
This PR fixes #1766 by ensuring `System.Void` is treating as the absence of a type within VB's syntax generator.

This *seems* like the right thing to do to me, but I also feel like this could be the wrong approach. If you'd like a different approach let me know and I'll update the PR. Technically, only the `TypeExpression(ITypeSymbol)` overload requires the change in order to make the test pass, but I figured it makes sense for the `TypeExpression(SyntaxKind)` to function in a consistent manner.

### CODE REVIEW

**Comment by kentcb** [comment]
**UPDATE**: thinking about this more, it may be better to modify the abstract `SyntaxGenerator` such that its `MethodDeclaration(IMethodSymbol)` overload does this for `returnType`:

```C#
returnType: method.ReturnType.IsSystemVoid ? null : TypeExpression(method.ReturnType)
```

This way the VB-specific syntax generator would not need to change at all. Let me know if you agree and I'll modify the PR.

File: src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb [hunk 1]
```diff
@@ -248,6 +248,10 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.CodeGeneration
         End Function
 
         Public Overrides Function TypeExpression(typeSymbol As ITypeSymbol) As SyntaxNode
+            If typeSymbol.IsSystemVoid Then
```
Comment (CyrusNajmabadi) [inline src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb]: I'm not a fan of this as it means someone can't intentionally use the return type System.Void.  

When does this situation arise, and why can't the situation be solved by just using 'null' as the return type, instead of the syntax node for System.Void?

Comment (kentcb) [inline src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb]: Firstly, it's not technically possible to return `System.Void` from a function. It's a special type representing the absence of a value. The compiler flat out disallows this scenario.

Second, the situation arises when you obtain a symbol from an existing interface and pass that symbol onto `SyntaxGenerator.MethodDeclaration`.  If there are any `void` methods in that interface, VB's `SyntaxGenerator` implementation balks.

Lastly, please note my comments in the PR about altering the approach altogether. I think it would be better if the abstract `SyntaxGenerator` checked if the return type is void and, if so, passes through `null`. Both the C# and VB syntax generators would then operate correctly. I just want someone from MS to verify my thinking before I change the PR.

Comment (CyrusNajmabadi) [inline src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb]: > Lastly, please note my comments in the PR about altering the approach altogether. I think it would be better if the abstract SyntaxGenerator checked if the return type is void and, if so, passes through null. Both the C# and VB syntax generators would then operate correctly. 

The alternate approach seems more sensible to me.  Right now changing "TypeExpression" is not ok as it will prevent being able to type *Legal Code*, and that's unacceptable IMO.

> Firstly, it's not technically possible to return System.Void from a function.

That may be true, but the purpose of our codegen APIs is not just to create legal code, but to create the code that was asked for :)    It's quite common that we may generate code that is not legal, but which is useful as an intermediate point as a user refactors what they have.

That said, have a 'void' returning method properly show up as a Sub for VB makes a ton of sense, and seems reasonable to have.  So i would go that way.

Comment (kentcb) [inline src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb]: Ah, great point about generating invalid code - that had completely slipped my mind.

OK, so I've updated the PR such that it only affects `SyntaxGenerator.MethodDeclaration(IMethodSymbol)`.

Thanks.
