### PR TITLE
Report when a `void` value is the subject of a pattern-match

### LINKED ISSUE #20452: "Neither 'is' nor 'as' are valid on void type"
**Version Used**: Visual Studio Enterprise 2017 15.2 (26430.12), .NET Framework 4.6.2

Consider the following line of code:
```c#
bool b = Console.Write("A") is var _;
```
Visual Studio shows a red squiggle with the following error:
>Neither 'is' nor 'as' are valid on void type

However, the code successfully builds. 

I suspect this is not the desired behavior.

### PR DESCRIPTION
**Pull request by gafter**
**Customer scenario**

If the operand of a pattern-match is a void expression, and the pattern is a wildcard, the compiler produces code that crashes.

**Bugs this fixes:**

Fixes #20452

**Workarounds, if any**

Avoid that pattern of code.

**Risk**

Very low, as the fix is a simple local fix for the scenario.

**Performance impact**

None to tiny.

**Is this a regression from a previous update?**

No. The bug has been present since VS2017 when pattern-matching was introduced.

**Root cause analysis:**

We did not test this scenario.

**How was the bug found?**

Customer reported.

@dotnet/roslyn-compiler May I please have two reviews of this trivial bug fix?

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 1]
```diff
@@ -16,7 +16,7 @@ private BoundExpression BindIsPatternExpression(IsPatternExpressionSyntax node,
             var expression = BindValue(node.Expression, diagnostics, BindValueKind.RValue);
             var hasErrors = IsOperandErrors(node, ref expression, diagnostics);
             var expressionType = expression.Type;
-            if ((object)expressionType == null)
+            if ((object)expressionType == null || expressionType.SpecialType == SpecialType.System_Void)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: Opportunity to use `expressionType is null` ;-)

Comment (VSadov) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: if ( !(expressionType?.SpecialType != SpecialType.System_Void))

:)

**Comment by gafter** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by gafter** [comment]
retest windows_release_vs-integration_prtest please

**Comment by gafter** [comment]
retest windows_release_vs-integration_prtest please


https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/5778/

**Comment by gafter** [comment]
retest windows_release_vs-integration_prtest please
