### PR TITLE
Inaccessible extension methods should not be considered eligible candidates.

### LINKED ISSUE #25813: C# compiler chooses inaccessible extension method over accessible one
**Version Used**: 
Microsoft (R) Visual C# Compiler version 2.6.0.62329 (5429b35d)

**Steps to Reproduce**:

1. Create new console application with following code in `Program.cs`:
```csharp
using System;
using System.Collections.Generic;
using System.Linq;

public class Program
{
    static void Main(string[] args)
    {
        var a = new[] { 0 };
        var b = new[] { 1, 2, 3 };
        Console.WriteLine(b.Count(a.Contains));
    }
}

public static class Extensions
{
    // NOTE: private access modifier simulates internal class public method in referenced assembly.
    private static bool Contains<T>(this IEnumerable<T> a, T value) =>
        throw new NotImplementedException();
}
```
2. Build project or wait full solution analysis to complete

**Expected Behavior**:
Project compiled successfully. `System.Linq.Enumerable.Contains()` used as an argument of `System.Linq.Enumerable.Count()` function.

**Actual Behavior**:
Compiler error CS0122: 'Extensions.Contains<T>(IEnumerable<T>, T)' is inaccessible due to its protection level

Original case is described in [C# compiler chooses wrong extension method](https://stackoverflow.com/questions/49554228/c-sharp-compiler-chooses-wrong-extension-method#comment86117664_49554228) question on StackOverflow. [CS0122 wrong member inaccessible when overload does not exist](https://github.com/dotnet/roslyn/issues/15401) issue looks related.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #25813

@dotnet/roslyn-compiler Please review this small bug fix.

Note that there is a slight regression in the quality of our diagnostics for inaccessible extension methods. I think this is unavoidable unless we go to the two-pass technique used to diagnose problems with non-extension methods (first look for viable methods, then if that fails try again looking for anything, viable or not).

There is also a slight regression in one `SemanticModel` case caused by `SemanticModel` attempting to compensate for the fact that we don't take a two-pass approach. I've filed https://github.com/dotnet/roslyn/issues/26344 for that, as fixing it probably requires some deep refactoring of the `SemanticModel` and binding of overload resolution. Since the cost and risk of that is high and the benefits small, I do not consider that worth doing in this bug fix.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetSemanticInfoTests.cs [hunk 1]
```diff
@@ -11484,7 +11483,7 @@ static void Main(string[] args)
             Assert.Equal(ConversionKind.Identity, semanticInfo.ImplicitConversion.Kind);
 
             Assert.Null(semanticInfo.Symbol);
-            Assert.Equal(CandidateReason.Inaccessible, semanticInfo.CandidateReason);
+            Assert.Equal(CandidateReason.OverloadResolutionFailure, semanticInfo.CandidateReason);
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelGetSemanticInfoTests.cs]: https://github.com/dotnet/roslyn/issues/26344

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 2]
```diff
@@ -6084,7 +6084,7 @@ private static void CombineExtensionMethodArguments(BoundExpression receiver, An
             this.LookupExtensionMethodsInSingleBinder(scope, lookupResult, rightName, arity, options, ref useSiteDiagnostics);
             diagnostics.Add(node, useSiteDiagnostics);
 
-            if (!lookupResult.IsClear)
+            if (lookupResult.IsMultiViable)
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: This is the bug fix.

File: src/Compilers/CSharp/Portable/Binder/MethodGroupResolution.cs [hunk 3]
```diff
@@ -88,7 +88,7 @@ public bool IsExtensionMethodGroup
         }
 
         public bool IsLocalFunctionInvocation =>
-            MethodGroup.Methods.Count == 1 && // Local functions cannot be overloaded
+            MethodGroup?.Methods.Count == 1 && // Local functions cannot be overloaded
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/MethodGroupResolution.cs]: This is another little bug fix while I was in the area. It prevents the debugger from displaying exceptions for this property when viewing the members of a `MethodGroupResolution`.

**Comment by gafter** [comment]
@dotnet/roslyn-compiler Please review this small bug fix.

File: src/Compilers/CSharp/Test/Emit/PrivateProtected.cs [hunk 4]
```diff
@@ -783,9 +783,9 @@ public static void M(string s)
                 // (4,35): error CS1057: 'Extensions.SomeExtension(string)': static classes cannot contain protected members
                 //     static private protected void SomeExtension(this string s) { } // error: no pp in static class
                 Diagnostic(ErrorCode.ERR_ProtectedInStatic, "SomeExtension").WithArguments("Extensions.SomeExtension(string)").WithLocation(4, 35),
-                // (11,11): error CS0122: 'Extensions.SomeExtension(string)' is inaccessible due to its protection level
+                // (11,11): error CS1061: 'string' does not contain a definition for 'SomeExtension' and no extension method 'SomeExtension' accepting a first argument of type 'string' could be found (are you missing a using directive or an assembly reference?)
```
[the remark this answers is not in the document]
Comment (333fred) [reply src/Compilers/CSharp/Test/Emit/PrivateProtected.cs]: Agreed on making this change.

---
In reply to: [183898009](https://github.com/dotnet/roslyn/pull/26345#discussion_r183898009) [](ancestors = 183898009)

File: src/Compilers/CSharp/Portable/Binder/MethodGroupResolution.cs (hunk 3 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/MethodGroupResolution.cs]: No, because there is no crash. It is just very poor experience in the debugger that I am fixing.

File: src/Compilers/CSharp/Test/Emit/CodeGen/UnsafeTests.cs [hunk 5]
```diff
@@ -5072,12 +5072,9 @@ public static class FixableExt
             var compVerifier = CreateCompilationWithMscorlib46(text, options: TestOptions.UnsafeReleaseExe);
 
             compVerifier.VerifyDiagnostics(
-                // (6,25): error CS9385: The given expression cannot be used in a fixed statement
-                //         fixed (int* p = new Fixable(1))
-                Diagnostic(ErrorCode.ERR_ExprCannotBeFixed, "new Fixable(1)").WithLocation(6, 25),
-                // (6,25): error CS0122: 'FixableExt.GetPinnableReference(Fixable)' is inaccessible due to its protection level
+                // (6,25): error CS8385: The given expression cannot be used in a fixed statement
```
[the remark this answers is not in the document]
Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/CodeGen/UnsafeTests.cs]: The problem is it currently gives *no* hints. Should this diagnostic also mention that the method `GetPinnableReference` could be called if it were found, but that it must be non-static, what its signature should be, and that it could be either an instance or extension method? I think this PR is the wrong place to start educating users about the new feature.

File: src/Compilers/CSharp/Test/Emit/PrivateProtected.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/PrivateProtected.cs]: Agree, sure.

**Comment by gafter** [comment]
I've adjusted the diagnostic as suggested (one of the two). Please let me know if there is anything else.

File: src/Compilers/CSharp/Test/Semantic/Semantics/OverloadResolutionTests.cs [hunk 6]
```diff
@@ -11145,5 +11145,33 @@ static void Main()
                 Diagnostic(ErrorCode.ERR_BadRetType, "F").WithArguments("Program.F(in System.DateTime)", "string").WithLocation(16, 15)
             );
         }
+
+        [Fact, WorkItem(25813, "https://github.com/dotnet/roslyn/issues/25813")]
+        public void InaccessibleExtensionMethod()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/OverloadResolutionTests.cs]: >InaccessibleExtensionMethod [](start = 20, length = 27)

It would be interesting to test scenario when there are instance candidates and extension candidates and all of them are inaccessible. What would be the error message and candidates returned by SemanticModel?

**Comment by gafter** [comment]
test windows_debug_spanish_unit32_prtest please

**Comment by gafter** [comment]
test windows_release_vs-integration_prtest please
