### PR TITLE
Handle IWorkspaceProjectContext creation requests with broken BinTarg…

### LINKED ISSUE #14520: Handle IWorkspaceProjectContext creation requests with broken BinTargetPath
CPS Projects which are in unrestored state do have a valid value for binTargetPath - Roslyn should handle this case by creating a unique dummy path per project.

### PR DESCRIPTION
**Pull request by mavasani**
…etPath

CPS might provide such invalid paths during initialization or when project is in unrestored state. Now we handle these cases to ensure that BinOutputPath is either null or a rooted path.

Fixes #14520

### CODE REVIEW

**Comment by mavasani** [comment]
Tagging @dotnet/project-system for review.
@MattGertz for ask mode approval.

**Comment by MattGertz** [comment]
Approved pending signoffs and tests passing.

File: src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject.cs [hunk 1]
```diff
@@ -27,6 +28,21 @@ internal sealed partial class CPSProject : AbstractProject
...
+                // Ensure that binOutputPath is either null or a rooted path.
+                // CPS might provide such invalid paths during initialization or when project is in unrestored state.
+                if (binOutputPath == String.Empty)
+                {
+                    binOutputPath = null;
+                }
+                else if (!Path.IsPathRooted(binOutputPath))
+                {
+                    // Make it a rooted path.
+                    binOutputPath = Path.Combine(Path.GetTempPath(), binOutputPath);
```
Comment (srivatsn) [inline src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject.cs]: What does CPS pass in when the path is unrooted? Is it something like bin\debug? If so, should we make the path be `Path.Combine(Path.GetDirectoryName(projectFilePath), binOutputPath)'?

File: src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject.cs [hunk 2]
```diff
@@ -27,6 +28,21 @@ internal sealed partial class CPSProject : AbstractProject
             : base(projectTracker, reportExternalErrorCreatorOpt, projectDisplayName, projectFilePath,
                    hierarchy, language, projectGuid, serviceProvider, visualStudioWorkspaceOpt, hostDiagnosticUpdateSourceOpt, commandLineParserServiceOpt)
         {
+            if (binOutputPath != null)
+            {
+                // Ensure that binOutputPath is either null or a rooted path.
+                // CPS might provide such invalid paths during initialization or when project is in unrestored state.
+                if (binOutputPath == String.Empty)
+                {
+                    binOutputPath = null;
```
Comment (srivatsn) [inline src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject.cs]: Is null okay? I thought we blow up when the path is null - or is that only if was empty?

Comment (mavasani) [inline src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject.cs]: Null is fine, empty and non rooted paths causes us to blow up.

File: src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject.cs (hunk 1 above)
Comment (mavasani) [inline src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject.cs]: It's just the project name. Using the file path sounds better, will change.

File: src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject.cs [hunk 3]
```diff
@@ -39,7 +39,10 @@ internal sealed partial class CPSProject : AbstractProject
                 else if (!Path.IsPathRooted(binOutputPath))
                 {
                     // Make it a rooted path.
-                    binOutputPath = Path.Combine(Path.GetTempPath(), binOutputPath);
+                    var basePath = !string.IsNullOrEmpty(projectFilePath) && Path.IsPathRooted(projectFilePath) ?
```
Comment (Pilchie) [inline src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject.cs]: Oh - one more piece of feedback - we have our own `PathUtilities` class - should use be using that instead of `Path`?

**Comment by mavasani** [comment]
@dotnet-bot retest microbuild_prtest please

**Comment by mavasani** [comment]
@dotnet-bot retest windows_release_unit64_prtest please
