### PR TITLE
Restore packages after creating a CPS project in tests

### LINKED ISSUE #34165: CSharpUpdateProjectToAllowUnsafe.CPSProject_GeneralPropertyGroupUpdated Fails
[Test Logs](https://dev.azure.com/dnceng/public/_build/results?buildId=125135&view=ms.vss-test-web.build-test-results-tab)

```
Assert.Contains() Failure
Not found: (filter expression)
In value: WhereEnumerableIterator<XElement> [<PropertyGroup>
 <TargetFramework>netstandard2.0</TargetFramework>
</PropertyGroup>]
```

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #34165

### CODE REVIEW

File: src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpUpgradeProject.cs [hunk 1]
```diff
@@ -37,6 +37,7 @@ public void CPSProject_GeneralPropertyGroupUpdated()
 
             VisualStudio.SolutionExplorer.CreateSolution(SolutionName);
             VisualStudio.SolutionExplorer.AddProject(project, WellKnownProjectTemplates.CSharpNetStandardClassLibrary, LanguageNames.CSharp);
+            VisualStudio.SolutionExplorer.RestoreNuGetPackages(project);
```
Comment (jasonmalinowski) [inline src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpUpgradeProject.cs]: Any reason this should just be inlined into AddProject if you're adding a CSharpNetStandardClassLibrary?

Comment (sharwell) [reply src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpUpgradeProject.cs]: It might be possible to do that. If it wasn't such a slow operation we could apply it to all project additions.
