### PR TITLE
Ensure that flow analysis calls VisitRvalue instead of Visit for expressions in order to enforce proper state transition.

### LINKED ISSUE #5992: Unexpected System.NullReferenceException in VB flow analysis
This is a port of DevDiv 150405 (Watson crash)

Compile the following code:
```
Public Class Class1

    Sub Test()
        Dim x As S1
        Dim y As New C1() With {.F1 = x.F1 AndAlso x.F2, .F3 = x.F3}
    End Sub

End Class

Public Structure S1
    Public F1 As Boolean
    Public F2 As Boolean
    Public F3 As Object
End Structure
```

Observed: 
System.NullReferenceException
```
>	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler) Line 151	C#
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.<closure>.<lambda0>() Line 496	Basic
 	[Native to Managed Transition]	
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.BitVector.EnsureCapacity(int newCapacity) Line 91	C#
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.Normalize(Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState _state) Line 96	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.MakeSlot(Microsoft.CodeAnalysis.VisualBasic.Symbol local, Integer containingSlot) Line 490	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.IsAssigned(Microsoft.CodeAnalysis.VisualBasic.BoundExpression node, Integer unassignedSlot) Line 986	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.CheckAssigned(Microsoft.CodeAnalysis.VisualBasic.BoundFieldAccess fieldAccess, Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxNode node, Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).ReadWriteContext rwContext) Line 922	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.VisitFieldAccess(Microsoft.CodeAnalysis.VisualBasic.BoundFieldAccess node) Line 1719	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.BoundFieldAccess.Accept(Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor visitor) Line 3866	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.Visit(Microsoft.CodeAnalysis.VisualBasic.BoundNode node) Line 126	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.VisualBasic.BoundExpression node) Line 704	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.VisitExpressionWithStackGuard(Integer recursionDepth, Microsoft.CodeAnalysis.VisualBasic.BoundExpression node) Line 175	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitWithStackGuard(Microsoft.CodeAnalysis.VisualBasic.BoundNode node) Line 697	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitAlways(Microsoft.CodeAnalysis.VisualBasic.BoundNode node, Boolean dontLeaveRegion) Line 677	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).Visit(Microsoft.CodeAnalysis.VisualBasic.BoundNode node, Boolean dontLeaveRegion) Line 669	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).Visit(Microsoft.CodeAnalysis.VisualBasic.BoundNode node) Line 661	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitObjectInitializerExpressionBase(Microsoft.CodeAnalysis.VisualBasic.BoundObjectInitializerExpressionBase node) Line 1545	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitObjectInitializerExpression(Microsoft.CodeAnalysis.VisualBasic.BoundObjectInitializerExpression node) Line 1556	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.BoundObjectInitializerExpression.Accept(Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor visitor) Line 3461	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.Visit(Microsoft.CodeAnalysis.VisualBasic.BoundNode node) Line 126	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.VisualBasic.BoundExpression node) Line 704	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.VisitExpressionWithStackGuard(Integer recursionDepth, Microsoft.CodeAnalysis.VisualBasic.BoundExpression node) Line 175	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitWithStackGuard(Microsoft.CodeAnalysis.VisualBasic.BoundNode node) Line 697	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitAlways(Microsoft.CodeAnalysis.VisualBasic.BoundNode node, Boolean dontLeaveRegion) Line 677	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).Visit(Microsoft.CodeAnalysis.VisualBasic.BoundNode node, Boolean dontLeaveRegion) Line 669	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitRvalue(Microsoft.CodeAnalysis.VisualBasic.BoundExpression node, Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).ReadWriteContext rwContext, Boolean dontLeaveRegion) Line 810	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitBadExpression(Microsoft.CodeAnalysis.VisualBasic.BoundBadExpression node) Line 1324	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.BoundBadExpression.Accept(Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor visitor) Line 636	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.Visit(Microsoft.CodeAnalysis.VisualBasic.BoundNode node) Line 126	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitExpressionWithoutStackGuard(Microsoft.CodeAnalysis.VisualBasic.BoundExpression node) Line 704	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.VisitExpressionWithStackGuard(Microsoft.CodeAnalysis.VisualBasic.BoundExpression node) Line 193	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.VisitExpressionWithStackGuard(Integer recursionDepth, Microsoft.CodeAnalysis.VisualBasic.BoundExpression node) Line 177	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitWithStackGuard(Microsoft.CodeAnalysis.VisualBasic.BoundNode node) Line 697	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitAlways(Microsoft.CodeAnalysis.VisualBasic.BoundNode node, Boolean dontLeaveRegion) Line 677	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).Visit(Microsoft.CodeAnalysis.VisualBasic.BoundNode node, Boolean dontLeaveRegion) Line 669	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitRvalue(Microsoft.CodeAnalysis.VisualBasic.BoundExpression node, Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).ReadWriteContext rwContext, Boolean dontLeaveRegion) Line 810	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitLocalDeclaration(Microsoft.CodeAnalysis.VisualBasic.BoundLocalDeclaration node) Line 1057	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.VisitLocalDeclaration(Microsoft.CodeAnalysis.VisualBasic.BoundLocalDeclaration node) Line 1559	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.BoundLocalDeclaration.Accept(Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor visitor) Line 4167	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.Visit(Microsoft.CodeAnalysis.VisualBasic.BoundNode node) Line 126	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitWithStackGuard(Microsoft.CodeAnalysis.VisualBasic.BoundNode node) Line 700	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitAlways(Microsoft.CodeAnalysis.VisualBasic.BoundNode node, Boolean dontLeaveRegion) Line 677	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).Visit(Microsoft.CodeAnalysis.VisualBasic.BoundNode node, Boolean dontLeaveRegion) Line 669	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).Visit(Microsoft.CodeAnalysis.VisualBasic.BoundNode node) Line 661	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitStatement(Microsoft.CodeAnalysis.VisualBasic.BoundStatement statement) Line 853	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitDimStatement(Microsoft.CodeAnalysis.VisualBasic.BoundDimStatement node) Line 1748	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.BoundDimStatement.Accept(Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor visitor) Line 4258	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.Visit(Microsoft.CodeAnalysis.VisualBasic.BoundNode node) Line 126	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitWithStackGuard(Microsoft.CodeAnalysis.VisualBasic.BoundNode node) Line 700	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitAlways(Microsoft.CodeAnalysis.VisualBasic.BoundNode node, Boolean dontLeaveRegion) Line 677	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).Visit(Microsoft.CodeAnalysis.VisualBasic.BoundNode node, Boolean dontLeaveRegion) Line 669	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).Visit(Microsoft.CodeAnalysis.VisualBasic.BoundNode node) Line 661	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitStatement(Microsoft.CodeAnalysis.VisualBasic.BoundStatement statement) Line 853	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitBlock(Microsoft.CodeAnalysis.VisualBasic.BoundBlock node) Line 1083	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.VisitBlock(Microsoft.CodeAnalysis.VisualBasic.BoundBlock node) Line 1622	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.BoundBlock.Accept(Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor visitor) Line 4050	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.BoundTreeVisitor.Visit(Microsoft.CodeAnalysis.VisualBasic.BoundNode node) Line 126	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitWithStackGuard(Microsoft.CodeAnalysis.VisualBasic.BoundNode node) Line 700	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).VisitAlways(Microsoft.CodeAnalysis.VisualBasic.BoundNode node, Boolean dontLeaveRegion) Line 677	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).Visit(Microsoft.CodeAnalysis.VisualBasic.BoundNode node, Boolean dontLeaveRegion) Line 669	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).Visit(Microsoft.CodeAnalysis.VisualBasic.BoundNode node) Line 661	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).Scan() Line 211	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.Scan() Line 143	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.AbstractFlowPass(Of Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.LocalState).Analyze() Line 223	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.DataFlowPass.Analyze(Microsoft.CodeAnalysis.VisualBasic.FlowAnalysisInfo info, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, Boolean suppressConstExpressionsSupport) Line 198	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.FlowAnalysisPass.Analyze(Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation compilation, Microsoft.CodeAnalysis.VisualBasic.Symbols.MethodSymbol method, Microsoft.CodeAnalysis.VisualBasic.BoundBlock block, Microsoft.CodeAnalysis.DiagnosticBag diagnostics) Line 27	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.FlowAnalysisPass.Analyze(Microsoft.CodeAnalysis.VisualBasic.Symbols.MethodSymbol method, Microsoft.CodeAnalysis.VisualBasic.BoundBlock block, Microsoft.CodeAnalysis.DiagnosticBag diagnostics) Line 22	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.Analyzer.AnalyzeMethodBody(Microsoft.CodeAnalysis.VisualBasic.Symbols.MethodSymbol method, Microsoft.CodeAnalysis.VisualBasic.BoundBlock body, Microsoft.CodeAnalysis.DiagnosticBag diagnostics) Line 33	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.BindAndAnalyzeMethodBody(Microsoft.CodeAnalysis.VisualBasic.Symbols.MethodSymbol method, Microsoft.CodeAnalysis.VisualBasic.TypeCompilationState compilationState, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, Microsoft.CodeAnalysis.VisualBasic.Binder containingTypeBinder, Microsoft.CodeAnalysis.VisualBasic.Symbols.MethodSymbol referencedConstructor, Boolean injectDefaultConstructorCall, Microsoft.CodeAnalysis.VisualBasic.Binder methodBodyBinder) Line 1628	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileMethod(Microsoft.CodeAnalysis.VisualBasic.Symbols.MethodSymbol method, Integer methodOrdinal, Integer withEventPropertyIdDispenser, Integer delegateRelaxationIdDispenser, System.Predicate(Of Microsoft.CodeAnalysis.VisualBasic.Symbol) filter, Microsoft.CodeAnalysis.VisualBasic.TypeCompilationState compilationState, Microsoft.CodeAnalysis.VisualBasic.Binder.ProcessedFieldOrPropertyInitializers processedInitializers, Microsoft.CodeAnalysis.VisualBasic.Binder containingTypeBinder, Microsoft.CodeAnalysis.VisualBasic.SynthesizedSubmissionFields previousSubmissionFields, Microsoft.CodeAnalysis.VisualBasic.Symbols.MethodSymbol referencedConstructor) Line 1165	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.CompileNamedType(Microsoft.CodeAnalysis.VisualBasic.Symbols.NamedTypeSymbol containingType, System.Predicate(Of Microsoft.CodeAnalysis.VisualBasic.Symbol) filter) Line 653	Basic
 	Microsoft.CodeAnalysis.VisualBasic.dll!Microsoft.CodeAnalysis.VisualBasic.MethodCompiler.<closure>.<lambda0>() Line 495	Basic
 	Microsoft.CodeAnalysis.dll!Roslyn.Utilities.UICultureUtilities.WithCurrentUICulture.AnonymousMethod__0() Line 136	C#
 	mscorlib.dll!System.Threading.Tasks.Task.Execute() Line 2498	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot) Line 2827	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution) Line 2756	C#
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 820	C#
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #5992.

If logical expression is not visited with VisitRvalue method, current state remains splitted, which causes a NullReferenceException when the next expression is visited.

@gafter, @VSadov, @jaredpar, @agocke, @TyOverby Please review.

### CODE REVIEW

File: src/Compilers/VisualBasic/Portable/Analysis/FlowAnalysis/AbstractFlowPass.vb [hunk 1]
```diff
@@ -1542,7 +1552,7 @@ lUnsplitAndFinish:
 
         Private Function VisitObjectInitializerExpressionBase(node As BoundObjectInitializerExpressionBase) As BoundNode
             For Each initializer In node.Initializers
-                Visit(initializer)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Analysis/FlowAnalysis/AbstractFlowPass.vb]: This line is causing an incorrect state when ```initializer``` is a logical expression, which can happen in presence of errors.

**Comment by TyOverby** [comment]
LGTM

**Comment by VSadov** [comment]
LGTM

**Comment by gafter** [comment]
LGTM

**Comment by MattGertz** [comment]
Approved.
