### PR TITLE
Eliminate host dependence for constant folding floating-point to integral conversions.

### LINKED ISSUE #37527: Constant folding produces different IL depending on host architecture
**Version Used**: 

3.3.0-beta2-19374-02

**Steps to Reproduce**:

1. Compile and run the following program:
```csharp
Test program:

using System;

namespace HelloWorld
{
    class Program
    {
        static double nan = double.NaN;
        static float nanf = float.NaN;
        static double ninf = double.NegativeInfinity;
        static float ninff = float.NegativeInfinity;
        static double inf = double.PositiveInfinity;
        static float inff = float.PositiveInfinity;

        static void Main(string[] args)
        {
            Console.WriteLine(unchecked((ulong)double.NaN));
            Console.WriteLine(unchecked((ulong)nan));
            Console.WriteLine(unchecked((uint)double.NaN));
            Console.WriteLine(unchecked((uint)nan));
            Console.WriteLine(unchecked((ulong)float.NaN));
            Console.WriteLine(unchecked((ulong)nanf));
            Console.WriteLine(unchecked((uint)float.NaN));
            Console.WriteLine(unchecked((uint)nanf));

            Console.WriteLine(unchecked((ulong)double.NegativeInfinity));
            Console.WriteLine(unchecked((ulong)ninf));
            Console.WriteLine(unchecked((uint)double.NegativeInfinity));
            Console.WriteLine(unchecked((uint)ninf));
            Console.WriteLine(unchecked((ulong)float.NegativeInfinity));
            Console.WriteLine(unchecked((ulong)ninff));
            Console.WriteLine(unchecked((uint)float.NegativeInfinity));
            Console.WriteLine(unchecked((uint)ninff));

            Console.WriteLine(unchecked((ulong)double.PositiveInfinity));
            Console.WriteLine(unchecked((ulong)inf));
            Console.WriteLine(unchecked((uint)double.PositiveInfinity));
            Console.WriteLine(unchecked((uint)inf));
            Console.WriteLine(unchecked((ulong)float.PositiveInfinity));
            Console.WriteLine(unchecked((ulong)inff));
            Console.WriteLine(unchecked((uint)float.PositiveInfinity));
            Console.WriteLine(unchecked((uint)inff));
        }
    }
}
```
2. Repeat step 1 on different architectures (x64, ARM64)

**Expected Behavior**:

Identical IL is produced.

**Actual Behavior**:

`(ulong)double.PositiveInfinity` is constant folded to `0` on x64 host. On ARM host it is folded to `ulong.MaxValue`. Similarly for all the other variations of `PositiveInfinity`.

While the actual behavior for this conversion in C# may be undefined this causes some hard to debug issues. When program is compiled and run on the same architecture the values are self-consistent. However, when the program is compiled on x64 and run on ARM64 it produces inconsistent results.

This was hit in practice with CoreFX tests for System.Linq.Expressions. The tests are compiled on x64 and consumed in binary form for CoreCLR and Mono tests. Cross-reference: https://github.com/mono/mono/pull/15871

x64 code:
```
        IL_0000: ldc.i4.0
        IL_0001: conv.i8
        IL_0002: call void [System.Console]System.Console::WriteLine(uint64)
        IL_0007: ldsfld float64 HelloWorld.Program::nan
        IL_000c: conv.u8
        IL_000d: call void [System.Console]System.Console::WriteLine(uint64)
        IL_0012: ldc.i4.0
        IL_0013: call void [System.Console]System.Console::WriteLine(uint32)
        IL_0018: ldsfld float64 HelloWorld.Program::nan
        IL_001d: conv.u4
        IL_001e: call void [System.Console]System.Console::WriteLine(uint32)
        IL_0023: ldc.i4.0
        IL_0024: conv.i8
        IL_0025: call void [System.Console]System.Console::WriteLine(uint64)
        IL_002a: ldsfld float32 HelloWorld.Program::nanf
        IL_002f: conv.u8
        IL_0030: call void [System.Console]System.Console::WriteLine(uint64)
        IL_0035: ldc.i4.0
        IL_0036: call void [System.Console]System.Console::WriteLine(uint32)
        IL_003b: ldsfld float32 HelloWorld.Program::nanf
        IL_0040: conv.u4
        IL_0041: call void [System.Console]System.Console::WriteLine(uint32)
        IL_0046: ldc.i8 -9223372036854775808
        IL_004f: call void [System.Console]System.Console::WriteLine(uint64)
        IL_0054: ldsfld float64 HelloWorld.Program::ninf
        IL_0059: conv.u8
        IL_005a: call void [System.Console]System.Console::WriteLine(uint64)
        IL_005f: ldc.i4.0
        IL_0060: call void [System.Console]System.Console::WriteLine(uint32)
        IL_0065: ldsfld float64 HelloWorld.Program::ninf
        IL_006a: conv.u4
        IL_006b: call void [System.Console]System.Console::WriteLine(uint32)
        IL_0070: ldc.i8 -9223372036854775808
        IL_0079: call void [System.Console]System.Console::WriteLine(uint64)
        IL_007e: ldsfld float32 HelloWorld.Program::ninff
        IL_0083: conv.u8
        IL_0084: call void [System.Console]System.Console::WriteLine(uint64)
        IL_0089: ldc.i4.0
        IL_008a: call void [System.Console]System.Console::WriteLine(uint32)
        IL_008f: ldsfld float32 HelloWorld.Program::ninff
        IL_0094: conv.u4
        IL_0095: call void [System.Console]System.Console::WriteLine(uint32)
        IL_009a: ldc.i4.0
        IL_009b: conv.i8
        IL_009c: call void [System.Console]System.Console::WriteLine(uint64)
        IL_00a1: ldsfld float64 HelloWorld.Program::inf
        IL_00a6: conv.u8
        IL_00a7: call void [System.Console]System.Console::WriteLine(uint64)
        IL_00ac: ldc.i4.0
        IL_00ad: call void [System.Console]System.Console::WriteLine(uint32)
        IL_00b2: ldsfld float64 HelloWorld.Program::inf
        IL_00b7: conv.u4
        IL_00b8: call void [System.Console]System.Console::WriteLine(uint32)
        IL_00bd: ldc.i4.0
        IL_00be: conv.i8
        IL_00bf: call void [System.Console]System.Console::WriteLine(uint64)
        IL_00c4: ldsfld float32 HelloWorld.Program::inff
        IL_00c9: conv.u8
        IL_00ca: call void [System.Console]System.Console::WriteLine(uint64)
        IL_00cf: ldc.i4.0
        IL_00d0: call void [System.Console]System.Console::WriteLine(uint32)
        IL_00d5: ldsfld float32 HelloWorld.Program::inff
        IL_00da: conv.u4
        IL_00db: call void [System.Console]System.Console::WriteLine(uint32)
        IL_00e0: ret
```

ARM64 code:
```
	IL_0000: nop
	IL_0001: ldc.i4.0
	IL_0002: conv.i8
	IL_0003: call void [System.Console]System.Console::WriteLine(uint64)
	IL_0008: nop
	IL_0009: ldsfld float64 HelloWorld.Program::nan
	IL_000e: conv.u8
	IL_000f: call void [System.Console]System.Console::WriteLine(uint64)
	IL_0014: nop
	IL_0015: ldc.i4.0
	IL_0016: call void [System.Console]System.Console::WriteLine(uint32)
	IL_001b: nop
	IL_001c: ldsfld float64 HelloWorld.Program::nan
	IL_0021: conv.u4
	IL_0022: call void [System.Console]System.Console::WriteLine(uint32)
	IL_0027: nop
	IL_0028: ldc.i4.0
	IL_0029: conv.i8
	IL_002a: call void [System.Console]System.Console::WriteLine(uint64)
	IL_002f: nop
	IL_0030: ldsfld float32 HelloWorld.Program::nanf
	IL_0035: conv.u8
	IL_0036: call void [System.Console]System.Console::WriteLine(uint64)
	IL_003b: nop
	IL_003c: ldc.i4.0
	IL_003d: call void [System.Console]System.Console::WriteLine(uint32)
	IL_0042: nop
	IL_0043: ldsfld float32 HelloWorld.Program::nanf
	IL_0048: conv.u4
	IL_0049: call void [System.Console]System.Console::WriteLine(uint32)
	IL_004e: nop
	IL_004f: ldc.i4.0
	IL_0050: conv.i8
	IL_0051: call void [System.Console]System.Console::WriteLine(uint64)
	IL_0056: nop
	IL_0057: ldsfld float64 HelloWorld.Program::ninf
	IL_005c: conv.u8
	IL_005d: call void [System.Console]System.Console::WriteLine(uint64)
	IL_0062: nop
	IL_0063: ldc.i4.0
	IL_0064: call void [System.Console]System.Console::WriteLine(uint32)
	IL_0069: nop
	IL_006a: ldsfld float64 HelloWorld.Program::ninf
	IL_006f: conv.u4
	IL_0070: call void [System.Console]System.Console::WriteLine(uint32)
	IL_0075: nop
	IL_0076: ldc.i4.0
	IL_0077: conv.i8
	IL_0078: call void [System.Console]System.Console::WriteLine(uint64)
	IL_007d: nop
	IL_007e: ldsfld float32 HelloWorld.Program::ninff
	IL_0083: conv.u8
	IL_0084: call void [System.Console]System.Console::WriteLine(uint64)
	IL_0089: nop
	IL_008a: ldc.i4.0
	IL_008b: call void [System.Console]System.Console::WriteLine(uint32)
	IL_0090: nop
	IL_0091: ldsfld float32 HelloWorld.Program::ninff
	IL_0096: conv.u4
	IL_0097: call void [System.Console]System.Console::WriteLine(uint32)
	IL_009c: nop
	IL_009d: ldc.i4.m1
	IL_009e: conv.i8
	IL_009f: call void [System.Console]System.Console::WriteLine(uint64)
	IL_00a4: nop
	IL_00a5: ldsfld float64 HelloWorld.Program::inf
	IL_00aa: conv.u8
	IL_00ab: call void [System.Console]System.Console::WriteLine(uint64)
	IL_00b0: nop
	IL_00b1: ldc.i4.m1
	IL_00b2: call void [System.Console]System.Console::WriteLine(uint32)
	IL_00b7: nop
	IL_00b8: ldsfld float64 HelloWorld.Program::inf
	IL_00bd: conv.u4
	IL_00be: call void [System.Console]System.Console::WriteLine(uint32)
	IL_00c3: nop
	IL_00c4: ldc.i4.m1
	IL_00c5: conv.i8
	IL_00c6: call void [System.Console]System.Console::WriteLine(uint64)
	IL_00cb: nop
	IL_00cc: ldsfld float32 HelloWorld.Program::inff
	IL_00d1: conv.u8
	IL_00d2: call void [System.Console]System.Console::WriteLine(uint64)
	IL_00d7: nop
	IL_00d8: ldc.i4.m1
	IL_00d9: call void [System.Console]System.Console::WriteLine(uint32)
	IL_00de: nop
	IL_00df: ldsfld float32 HelloWorld.Program::inff
	IL_00e4: conv.u4
	IL_00e5: call void [System.Console]System.Console::WriteLine(uint32)
	IL_00ea: nop
	IL_00eb: ret
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #37527

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/ConstantTests.cs [hunk 1]
```diff
@@ -2513,6 +2594,30 @@ class c1
             Assert.False(((FieldSymbol)symbol).HasConstantValue);
         }
 
+        [WorkItem(544620, "http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/544620")]
+        [Fact]
+        public void NoConstantValueForOverflows_02()
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ConstantTests.cs]: >NoConstantValueForOverflows_02 [](start = 20, length = 30)

This test passes.  At least it does on Intel.  AMD possibly not.

File: src/Compilers/CSharp/Test/Semantic/Semantics/ConstantTests.cs [hunk 2]
```diff
@@ -2798,35 +2903,6 @@ public static int Main()
...
-        {
-            string source = @"
-using System;
- 
-class Program
-{
-    static void Main()
-    {
-        double aslocal = 65535.17567;
-        Console.WriteLine(""As local: {0}"", unchecked((short)aslocal));
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ConstantTests.cs]: >(short)aslocal [](start = 55, length = 14)

This test passes.  At least it does on Intel.  AMD possibly not.  The result here is undefined and therefore this is not suitable for a unit test.

File: src/Compilers/CSharp/Test/Semantic/Semantics/ConstantTests.cs [hunk 3]
```diff
@@ -2798,35 +2903,6 @@ public static int Main()
...
-        // We used to return constant zero in unchecked conversion from a floating-point type to an integral type
-        // in a constant expression if the value being converted is not within the target type.
-        // The C# spec says that in this case the result of the conversion is an unspecified value of the destination type.
-        // Zero is a perfectly valid unspecified value, so that behavior was formally correct.
-        // But it did not agree with the behavior of the native C# compiler, that apparently returned a value that
-        // would resulted from a runtime conversion with normal CLR overflow behavior.
-        // To avoid breaking programs that might accidentally rely on that unspecified behavior
-        // we now match the native compiler behavior, and we are going to keep this behavior for compatibility.
-        [Fact, WorkItem(1020273, "http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/1020273")]
-        public void Bug1020273()
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ConstantTests.cs]: An internally reported "issue" such as [http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/1020273](http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/1020273) should not have taken priority over determinism (see [https://github.com/dotnet/roslyn/commit/c121bc53e4cadd98a1beda3c902e0521c833eaa8](https://github.com/dotnet/roslyn/commit/c121bc53e4cadd98a1beda3c902e0521c833eaa8)).  Now we have a user-reported issue about that determinism bug at [https://github.com/dotnet/roslyn/issues/37527](https://github.com/dotnet/roslyn/issues/37527), so I'm reverting that fix.

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs [hunk 4]
```diff
@@ -1297,14 +1297,10 @@ private static object DoUncheckedConversion(SpecialType destinationType, Constan
...
-                        // Zero is a perfectly valid unspecified value, so that behavior was formally correct.
-                        // But it did not agree with the behavior of the native C# compiler, that apparently returned a value that
-                        // would resulted from a runtime conversion with normal CLR overflow behavior.
-                        // To avoid breaking programs that might accidentally rely on that unspecified behavior
-                        // we now removed that check and just allow conversion to overflow.
-                        double doubleValue = value.DoubleValue;
+                        // When converting from a floating-point type to an integral type, if the checked conversion would
+                        // throw an overflow exception, then the unchecked conversion is undefined.  So that we have
+                        // identical behavior on every host platform, we yield a result of zero in that case.
+                        double doubleValue = CheckConstantBounds(destinationType, value.DoubleValue) ? value.DoubleValue : 0D;
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: >doubleValue [](start = 31, length = 11)

Reverting [https://github.com/dotnet/roslyn/commit/c121bc53e4cadd98a1beda3c902e0521c833eaa8](https://github.com/dotnet/roslyn/commit/c121bc53e4cadd98a1beda3c902e0521c833eaa8)

File: src/Compilers/CSharp/Test/Semantic/Semantics/ConstantTests.cs (hunk 3 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/ConstantTests.cs]: I see that internally-reported issue was split from user reported http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/1019366.

**Comment by gafter** [comment]
This will go do the compat council for resolution.

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs (hunk 4 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: It would be good to dig on bug 1020273. Did someone report the difference in behavior between roslyn and native compiler? Should we document this change even though we're only changing an unspecified behavior?

---
In reply to: [311307945](https://github.com/dotnet/roslyn/pull/37772#discussion_r311307945) [](ancestors = 311307945)

Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs]: Yes, a customer did report a difference between the native compiler and Roslyn.  However, the "fixed" behavior still differs depending on what platform you run the compiler on (as I suspect the native compiler also differed among platforms).  This PR ensures we get consistent (deterministic) behavior on all host platforms.

File: docs/compilers/CSharp/Compiler Breaking Changes - post VS2019.md [hunk 5]
```diff
@@ -8,3 +8,5 @@ Each entry should include a short description of the break, followed by either a
     bool M<T>(T t) => t is null;
     ```
 However, in *Visual Studio 2019* we improperly permitted this to compile in language versions `7.0`, `7.1`, `7.2`, and `7.3`.  In *Visual Studio 2019 Update 1* we will make it an error (as it was in *Visual Studio 2017*), and suggest updating to `preview` or `8.0`.
+
+2. https://github.com/dotnet/roslyn/issues/37527 The constant folding behavior of the compiler differed depending on your host architecture when converting a floating-point constant to an integral type where that conversion would be a compile-time error if not in an `unchecked` context.  We now yield a zero result for such conversions on all host architectures.
```
Comment (tannergooding) [inline docs/compilers/CSharp/Compiler Breaking Changes - post VS2019.md]: For additional reference, from IEEE 754:2008 (the same wording exists in the new 754:2019 spec, but the entry is `ii`, rather than `i`):
> For operations producing no result in floating-point format, the operations that signal the invalid operation exception are:
>
> i) conversion of a floating-point number to an integer format, when the source is NaN, infinity, or a value that would convert to an integer outside the range of the result format under the applicable rounding attribute

This leaves the result as undefined. The C and C++ language specifications do not explicitly define a result for these either.

File: docs/compilers/CSharp/Compiler Breaking Changes - post VS2019.md [hunk 6]
```diff
@@ -47,4 +47,5 @@ Each entry should include a short description of the break, followed by either a
     ```
 
     Such code will produce an error in version 16.4.
-    
\ No newline at end of file
+
+6. https://github.com/dotnet/roslyn/issues/37527 The constant folding behavior of the compiler differed depending on your host architecture when converting a floating-point constant to an integral type where that conversion would be a compile-time error if not in an `unchecked` context.  We now yield a zero result for such conversions on all host architectures.
```
Comment (tannergooding) [inline docs/compilers/CSharp/Compiler Breaking Changes - post VS2019.md]: Should an issue be logged against dotnet/coreclr to see if they want to take a similar fix for their constant folding and potentially for the result handling of the `Math.Round` functions?

CoreCLR already took similar fixes for `NaN` (where x86 and ARM return different NaN by default).

Comment (gafter) [reply docs/compilers/CSharp/Compiler Breaking Changes - post VS2019.md]: Given that the result is undefined, I don't care too much that the result is platform-dependent. However, I encourage you to file an issue if you think that would be a good idea.
