### PR TITLE
Fix parsing of local functions with line breaks

### LINKED ISSUE #12280: Line feeds break parsing of local methods
Line feeds between a local method's return type and its name prevent it from being parsed as a valid local method.

Due to this issue code could be easily broken by formatting.

Test code included at the bottom of this report.

local functions parsing

```cs
class Bug
{
    static void Main()
    {
        int
            foo() => 5;

        int bar() => 5;
    }
}
````

### PR DESCRIPTION
**Pull request by agocke**
The compiler has various heuristics around line breaks, specifically to
handle the case where someone is typeing above an existing statement.
Preserving these heuristics is important for the IDE, so we'll lookahead
to verify the presence of a local function and, if one is not present,
we'll fallback to the existing heuristics.

Fixes #12280.

### CODE REVIEW

**Comment by gafter** [comment]
Tests not passing?

**Comment by agocke** [comment]
@gafter Should be fixed now. There was some weird merging going on, I had to rebase.

**Comment by agocke** [comment]
ping @dotnet/roslyn

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 1]
```diff
@@ -4770,11 +4770,19 @@ private static bool CanReuseVariableDeclarator(CSharp.Syntax.VariableDeclaratorS
                                 currentTokenKind == SyntaxKind.MinusGreaterThanToken ||
                                 isNonEqualsBinaryToken)
                             {
-                                var missingIdentifier = CreateMissingIdentifierToken();
-                                missingIdentifier = this.AddError(missingIdentifier, offset, width, ErrorCode.ERR_IdentifierExpected);
+                                var isPossibleLocalFunctionToken =
+                                    currentTokenKind == SyntaxKind.OpenParenToken |
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: ||?

Comment (gafter) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: Also, why not just remove `currentTokenKind == SyntaxKind.OpenParenToken` from the enclosing `if` statement instead of testing for it again?

---
In reply to: [76164331](https://github.com/dotnet/roslyn/pull/13263#discussion_r76164331) [](ancestors = 76164331)

Comment (gafter) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: Oh, I get it.

---
In reply to: [76164551](https://github.com/dotnet/roslyn/pull/13263#discussion_r76164551) [](ancestors = 76164551,76164331)

**Comment by gafter** [comment]
:shipit:

**Comment by agocke** [comment]
@dotnet/roslyn-compiler One more review?

**Comment by TyOverby** [comment]
LGTM
