### PR TITLE
Use a pattern-specific diagnostic for pointer types.

### LINKED ISSUE #18727: Confusing error message when using a var pattern in switch/case with pointer input
**Version Used**:  2.1.0.61520

**Steps to Reproduce**:

```csharp
using System;

class Test
{
    unsafe static void Main()
    {
        fixed (char *x = "hello")
        {
            switch (x)
            {
                case var y: break;
            }
        }
    }
}
```

**Expected Behavior**:

An error message that helps the user understand what's wrong.

**Actual Behavior**:

> Test.cs(11,22): error CS0244: Neither 'is' nor 'as' is valid on pointer types

This is confusing (if you don't happen to be thinking about patterns in general) as the code doesn't contain an `is` or `as` operator.

I can't immediately think of any pattern match that would be valid for pointer types, so perhaps it would be clearer to make that the error message, even for `is` / `as` operators? ("Pattern matching is not valid on pointer types".) Of course, it's possible that I've misunderstood and there *are* patterns that match pointers, or will be in the future...

### PR DESCRIPTION
**Pull request by gafter**
Fixes #18727

@agocke @cston Could you please review this small bug fix?
/cc @dotnet/roslyn-compiler

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 1]
```diff
@@ -276,6 +276,12 @@ internal BoundExpression ConvertPatternExpression(TypeSymbol inputType, CSharpSy
             {
                 return false;
             }
+            else if (inputType.TypeKind == TypeKind.Pointer || patternType.TypeKind == TypeKind.Pointer)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: Are we testing the second condition: `patternType.TypeKind == TypeKind.Pointer`?

Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: @cston This is a kind of future-proofing. I don't know of a way a pointer type can arise as a pattern's type due to the structure of the language grammar, but if it does arise (due to some future kind of type alias, for example) we'd want this behavior.
