### PR TITLE
fix rename crash when an invalid for-loop control variable exist in VB syntax tree

### LINKED ISSUE #32086: Crash "Visual Studio" at rename variable in code
<p>If the code contains a line with an error, and you are trying to rename the variable, the development environment crashes and Visual Studio restarts.

Visual Studio Verion 15.9.3 
Simple code: (Console app, Visual Basic)

```
Module Module1

    Sub Main()

        ' Try renaming the variable "val". (Right Click -> Rename...)
        Dim val As Integer = 10

        ' Line code with error
        For (Int() i = 0; i <val; i++)

    End Sub

End Module
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/394687/crash-visual-studio-at-rename-variable-in-code.html
VSTS ticketId: 736894_
_These are the original issue comments:_

Fiona Niu[MSFT] on 11/29/2018, 06:20 PM (32 days ago): <p>Thank you for your feedback. In order for us to investigate this further, could you please give us a dump file so that we can conduct further research? </p><p> </p><p> 1. Please follow the instructions below, especially &quot;Provide a trace and heap dump&quot; section to record the issue you are experiencing.</p><p> 2.  https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017 </p><p> 3. The recorded files can be found under %TEMP%\Microsoft\VSFeedbackCollector.</p><p> 4. Upload the files to this ticket by choosing insert file tag on add comment field then submit.</p><p> </p><p>We look forward to hearing from you!</p>

Тютрюмов Максим on 11/29/2018, 08:42 PM (32 days ago): <p>Sent a record. Is that what you wanted?</p><p>Memory_8252_1543552764291.dmp 669 100 Kb (O_O). This is madness.</p>

Fiona Niu[MSFT] on 11/29/2018, 11:32 PM (32 days ago): <p>Thank you for providing the information. We are forwarding the issue to the engineering team for investigating. The engineer will investigate the issue and keep you posted. </p>
_These are the original issue solutions:_
(no solutions)

### PR DESCRIPTION
**Pull request by genlu**
fix #32086 

@dotnet/roslyn-ide @CyrusNajmabadi

### CODE REVIEW

File: src/EditorFeatures/Test2/Rename/RenameEngineTests.VisualBasicConflicts.vb [hunk 1]
```diff
@@ -3129,6 +3129,26 @@ End Class
...
+            <WorkItem(32086, "https://github.com/dotnet/roslyn/issues/32086")>
+            Public Sub InvalidControlVariableInForLoopDoNotCrash()
+                Using result = RenameEngineResult.Create(_outputHelper,
+                    <Workspace>
+                        <Project Language="Visual Basic" CommonReferences="true">
+                            <Document><![CDATA[
+Module Program
+    Sub Main()
+        Dim [|$$val|] As Integer = 10
+        For (Int() i = 0; i < val; i++)
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Test2/Rename/RenameEngineTests.VisualBasicConflicts.vb]: ok.  so it's intentional that this is completely bogus VB code?

File: src/Workspaces/VisualBasic/Portable/Rename/LocalConflictVisitor.vb [hunk 2]
```diff
@@ -155,7 +154,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Rename
                     ' is this local declared in the for or for each loop?
                     ' if not it was already added to the tracker before.
                     If local.IsFor OrElse local.IsForEach Then
-                        tokens.Add(identifierToken)
+                        tokens.Add(DirectCast(controlVariable, IdentifierNameSyntax).Identifier)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/VisualBasic/Portable/Rename/LocalConflictVisitor.vb]: how do we know the control variable is an identifier name?   Just because it's bound to a local?

Comment (CyrusNajmabadi) [reply src/Workspaces/VisualBasic/Portable/Rename/LocalConflictVisitor.vb]: if it's not typed this way in the syntax model, i would not assume it.  For example, i believe VB can reference other values (including fields) in a for-loop.  So i'm pretty sure you could say something like `for me.i = 1 to 10` and have that be legal. 

(note: these would be good test cases).

Comment (jasonmalinowski) [reply src/Workspaces/VisualBasic/Portable/Rename/LocalConflictVisitor.vb]: Indeed. Also, what about type characters? For `blah% = 1 To 10`? I forget how those are represented.

Comment (genlu) [reply src/Workspaces/VisualBasic/Portable/Rename/LocalConflictVisitor.vb]: OK, I have added a `SyntaxKind` check, although I'm still not convinced it could be anything other than `IdentifierNameSyntax` at this location. We reach the cast only when:
1. `controlVariable` is not an inline declaration
2. `controlVariable` is bind to a local
3. the local is declared in the loop

this should exclude the cases you mentioned above.

Comment (CyrusNajmabadi) [reply src/Workspaces/VisualBasic/Portable/Rename/LocalConflictVisitor.vb]: @genlu You're *most likely* correct.  But i'd prefer us to be a bit paranoid here as that doesn't really cost us, and may save an unfortunate crash/investigation in the future.  Thanks! :D

Comment (genlu) [reply src/Workspaces/VisualBasic/Portable/Rename/LocalConflictVisitor.vb]: Check added.

**Comment by genlu** [comment]
@jinujoseph @vatsalyaagrawal for approval
