### PR TITLE
Fix syntax associated with bound block of foreach

### LINKED ISSUE #1443: Compiler assertion when foreach iterator variable is captured in lambda expression  and foreach statement doesn't use braces for body
Compile the following code:

```
using System;
using System.Collections.Generic;
using System.Linq;

public class Program
{
    public static void Main()
    {
        IList<string> list1 = null;

        foreach (string list1Item in list1)
            Foo(() => list1Item == null);
    }

    static void Foo(Func<bool> func) { }
}
```

EXPECTED: Code compiles successfully
ACTUAL: UnexpectedValue Assert/Exception

This doesn't repro for me with the CTP6 compilers, but does when I compile the code from GitHub, so it appears to be a recent regression.

Here's the stack trace:

```
Unexpected value 'ExpressionStatement' of type 'Microsoft.CodeAnalysis.CSharp.SyntaxKind'

   at Roslyn.Utilities.ExceptionUtilities.UnexpectedValue(Object o) in C:\git\roslyn\src\Compilers\Core\Portable\InternalUtilities\ExceptionUtilities.cs:line 13
   at Microsoft.CodeAnalysis.CSharp.LambdaFrame.AssertIsClosureScopeSyntax(CSharpSyntaxNode syntaxOpt) in C:\git\roslyn\src\Compilers\CSharp\Portable\Lowering\LambdaRewriter\LambdaFrame.cs:line 90
   at Microsoft.CodeAnalysis.CSharp.LambdaFrame..ctor(VariableSlotAllocator slotAllocatorOpt, MethodSymbol topLevelMethod, MethodDebugId methodId, CSharpSyntaxNode scopeSyntaxOpt, Int32 closureOrdinal) in C:\git\roslyn\src\Compilers\CSharp\Portable\Lowering\LambdaRewriter\LambdaFrame.cs:line 40
   at Microsoft.CodeAnalysis.CSharp.LambdaRewriter.GetFrameForScope(BoundNode scope, ArrayBuilder`1 closureDebugInfo) in C:\git\roslyn\src\Compilers\CSharp\Portable\Lowering\LambdaRewriter\LambdaRewriter.cs:line 312
   at Microsoft.CodeAnalysis.CSharp.LambdaRewriter.MakeFrames(ArrayBuilder`1 closureDebugInfo) in C:\git\roslyn\src\Compilers\CSharp\Portable\Lowering\LambdaRewriter\LambdaRewriter.cs:line 28
   at Microsoft.CodeAnalysis.CSharp.LambdaRewriter.Rewrite(BoundStatement loweredBody, NamedTypeSymbol thisType, ParameterSymbol thisParameter, MethodSymbol method, Int32 methodOrdinal, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, VariableSlotAllocator slotAllocatorOpt, TypeCompilationState compilationState, DiagnosticBag diagnostics, Boolean assignLocals) in C:\git\roslyn\src\Compilers\CSharp\Portable\Lowering\LambdaRewriter\LambdaRewriter.cs:line 219
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.LowerBodyOrInitializer(MethodSymbol method, Int32 methodOrdinal, BoundStatement body, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState, DiagnosticBag diagnostics, VariableSlotAllocator& lazyVariableSlotAllocator, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, StateMachineTypeSymbol& stateMachineTypeOpt) in C:\git\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 1192
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in C:\git\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 955
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol symbol) in C:\git\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 440
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass21_0.<CompileNamedTypeAsTask>b__0() in C:\git\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 341
   at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in C:\git\roslyn\src\Compilers\Core\Portable\InternalUtilities\UICultureUtilities.cs:line 136
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

### PR DESCRIPTION
**Pull request by tmat**
Fixes #1443.

### CODE REVIEW

**Comment by VSadov** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs [hunk 1]
```diff
@@ -125,6 +125,14 @@ private BoundStatement RewriteEnumeratorForEachStatement(BoundForEachStatement n
             //     V v = (V)(T)e.Current;
             //     /* node.Body */
             // }
+
+            // The scope of the iteration variable is the foreach statement syntax.
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs]: This is not correct. The scope is the controlled statement only (there is a separate instance of the variable per iteration).

Comment (tmat) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs]: You are right, I'll fix the comment.

Comment (tmat) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs]: And the answer is - we create 2 closures (display classes). So the change is correct - we need to associate this block with a distinct syntax from the body of the statement (which represents a different closure). Just the comment is wrong.

Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs]: What I mean is that the code is incorrect (the comment correctly describes the incorrect behavior that is implemented here). The extent of the for-each variable on this block is the same as the controlled statement, not the foreach statement itself. Your change attaches a syntax node that has the wrong extent.

This will become a worse issue in C# 7, when we expect to have variables introduced in any statement that has a subexpression (e.g. declaration expressions or pattern matching). At that time I would expect this code to require revision. Better to attach a syntax node that has the right extent to start with.

The display class created for the foreach control variable *could be* shared with the closure for any variables declared in the controlled statement. But it *could not be* the same as for any variables declared in the expression of the foreach loop.

It feels to me as if the issue is the assertion, not the code.

Comment (tmat) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs]: First of all, for EnC mapping to work no two BoundBlocks that represent a closure in the lambda rewriter can be associated with the same syntax node. If they were the mapping would be broken.

You are correct that once expression-level declarations are introduced we need to amend the implementation of IsClosureScope (and of other code in EnC infrastructure). And that is true regardless of what node the BoundBlock is associated with. 

For now we have two options:
1) The small change implemented in this PR. 
2) A bigger change of updating the code-gen to not emit a distinct display class and instead share the closure with variables of the embedded statement.

I'm not against implementing #2 for RTM. I believe #1 is better for RC, since it's a less risky change.

BTW, the node associated with the BoundBlock does not need to exactly describe the scope of the variable. It does however need to uniquely represent it, meaning that it should be possible to unambiguously derive the exact span from the associated node. Given scope associated with a node of type ForEachStatementSyntax we know that the exact scope being represented spans the embedded statement.

Comment (tmat) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs]: First of all, for EnC mapping to work no two BoundBlocks that represent a closure in the lambda rewriter can be associated with the same syntax node. If they were the mapping would be broken.
You are correct that once expression-level declarations are introduced we need to amend the implementation of IsClosureScope (and of other code in EnC infrastructure). And that is true regardless of what node this particular BoundBlock is associated with. 
For now we have two options:
1) The small change implemented in this PR. 
2) A bigger change of updating the code-gen to not emit a distinct display class and instead share the closure with variables of the embedded statement.
I'm not against implementing [2] for RTM. I believe [1] is better for RC, since it's a less risky change.
BTW, the node associated with the BoundBlock does not need to exactly describe the scope of the variable. It does however need to uniquely represent it, meaning that it should be possible to unambiguously derive the exact span from the associated node. Given scope associated with a node of type ForEachStatementSyntax we know that the exact scope being represented spans the embedded statement.

Comment (tmat) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs]: Also, not that a BoundBlock for foreach statement iterating over IEnumerable already is associated with the foreach statement (the rewriter takes a different code path). So if we decide to go for 2) we will also need to make a change in the other code path.

Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs]: We should not have assertions about the shape of the language (syntax) in any compiler phases after lowering. The purpose of lowering is to abstract away language-specific shapes into less language-specific shapes.

Comment (tmat) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs]: Well, that's great theory but doesn't quite help me to implement EnC.

Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs]: Assertions in the lowering phases won't help you implement EnC.

It is possible you may need to record additional info in the bound trees (and the generated debug info) to implement EnC.

Comment (tmat) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs]: They absolutely help me to implement EnC. IsClosureScope is called from the IDE to find out what syntax corresponds to display classes (BoundBlocks). So the assertion is making sure that the IDE and the compiler are in sync. I agree we might want to consider improving the way how to make this information available to the IDE in future (perhaps exposing some public APIs, semantic trees, etc.). We can revisit this for C# 7. For the current version I'm not gonna change the fundamentals of the EnC infrastructure.

Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ForEachStatement.cs]: I suggest you just change IsClosureScope to return true for any statement.

**Comment by tmat** [comment]
@gafter @vsadov Added more detailed explanation to the rewriter and more tests to cover all 4 kinds of foreach loops.

**Comment by gafter** [comment]
As we discussed offline, this solution is good for now, but we'll need to introduce a nonterminal around the identifier in a foreach loop to which the block and its associated closure can be associated.

**Comment by tmat** [comment]
After an offline discussion we agreed to leave the change as is for RC, and consider changing the structure of foreach statement syntax for RTM (see #1503).

**Comment by gafter** [comment]
LGTM
