### PR TITLE
Fixes #633 - Constructor names were classifying as types within xml docs

### LINKED ISSUE #633: Constructors mentioned in crefs are classified like types
Ported from TFS WorkItem: **840118**

------------------------------

**Repro Steps:**

**Affected Branch:** <BR>**Affected Build:** <BR>**Affected Product Language:** <BR><BR>**Steps to reproduce:**<BR><BR>1. Copy/paste to a C# file:

&nbsp;
<PRE style="FONT-SIZE: 16px; FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink"><SPAN style="COLOR: gray">///</SPAN> <SPAN style="COLOR: gray">&lt;</SPAN><SPAN style="COLOR: gray">summary</SPAN><SPAN style="COLOR: gray">&gt;</SPAN>
<SPAN style="COLOR: gray">///</SPAN><SPAN style="COLOR: green"> To create an instance of MyClass, call </SPAN><SPAN style="COLOR: gray">&lt;</SPAN><SPAN style="COLOR: gray">see</SPAN> <SPAN style="COLOR: gray">cref</SPAN><SPAN style="COLOR: gray">=</SPAN><SPAN style="COLOR: gray">"</SPAN><SPAN style="COLOR: #2b91af">MyClass</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: #2b91af">MyClass</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">int</SPAN><SPAN style="COLOR: black">)</SPAN><SPAN style="COLOR: gray">"</SPAN><SPAN style="COLOR: gray">/&gt;</SPAN>
<SPAN style="COLOR: gray">///</SPAN> <SPAN style="COLOR: gray">&lt;/</SPAN><SPAN style="COLOR: gray">summary</SPAN><SPAN style="COLOR: gray">&gt;</SPAN>
<SPAN style="COLOR: blue">class</SPAN> <SPAN style="COLOR: #2b91af">MyClass</SPAN>
<SPAN style="COLOR: black">{</SPAN>
    <SPAN style="COLOR: blue">public</SPAN> <SPAN style="COLOR: black">MyClass</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">int</SPAN> <SPAN style="COLOR: black">x</SPAN><SPAN style="COLOR: black">)</SPAN> <SPAN style="COLOR: black">{</SPAN> <SPAN style="COLOR: black">}</SPAN>
<SPAN style="COLOR: black">}</SPAN></PRE>

&nbsp;

**Expected: **The cref to be colored like this: <SPAN style="COLOR: #2b91af">MyClass</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: #2b91af"><SPAN style="COLOR: black">MyClass</SPAN></SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">int</SPAN><SPAN style="COLOR: black">)</SPAN>

**Actual: **The cref is actally colored like this: <SPAN style="COLOR: #2b91af">MyClass</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: #2b91af">MyClass</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">int</SPAN><SPAN style="COLOR: black">)</SPAN>

------------------------------

**Revisions:**

1) Created By David Poeschl (12/9/2013 4:08:55 PM)

------------------------------

### LINKED ISSUE #663: Roll back warning for struct == null
Roslyn added a new warning compared to the native compiler: if you attempt to compare a struct value to null
```cs
  if (structValue == null) ...
```
Roslyn now gives you a warning (the value in this case is always false). It still typechecks because the comparison operator selected is `operator==(Struct? left, Struct? right)`.

Unfortunately this is a breaking change for someone who instructs the compiler to treat warnings as errors. So the warning should be removed.

In the longer run we want a mechanism to add warnings in which users would be required to opt-in before receiving any new warnings. When that is done this warning can be restored as one you'd need to opt in to. But that is a separate issue.

### PR DESCRIPTION
**Pull request by dpen2000**
Fixes #633
This is because NameSyntaxClassifier was choosing the parent symbol of a constructor to classify by. We're now
restricting this to only in the case of attributes (which always refer to constructors but we want to classify like
types).

I'm not 100% sure if the behaviour of using the parent symbol in the case of constructors was just intended to cover attributes but restricting it to this satisfies the existing tests.
I first did the tests in SemanticClassifierTests but it's not clear which instance of "MyClass" is being referred to so I also did a test in TotalClassifierTests.

I've tested this in Visual Studio also and now the classification in the bug looks like this:
image

### CODE REVIEW

**Comment by balajikris** [comment]
@dotnet/roslyn-ide Please review.

File: src/Workspaces/CSharp/Portable/Classification/Classifiers/NameSyntaxClassifier.cs [hunk 1]
```diff
@@ -137,8 +137,7 @@ private static bool IsNamespaceName(NameSyntax name)
                 if (symbol.Kind == SymbolKind.Alias)
                 {
                     symbol = (symbol as IAliasSymbol).Target;
-                }
-                else if (symbol.IsConstructor())
+                } else if (symbol.IsConstructor() && name.Parent.Kind() == SyntaxKind.Attribute)
```
Comment (balajikris) [inline src/Workspaces/CSharp/Portable/Classification/Classifiers/NameSyntaxClassifier.cs]: suggestion: you can use the [IsParentKind()](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Workspaces/Extensions/SyntaxNodeExtensions.cs,7616fedcf6c8707d) extension here

Comment (jasonmalinowski) [inline src/Workspaces/CSharp/Portable/Classification/Classifiers/NameSyntaxClassifier.cs]: Nit: else if should start on it's own line.

**Comment by jasonmalinowski** [comment]
Curious: this doesn't break just classification of "new Foo" in a regular context?

**Comment by dpen2000** [comment]
@jasonmalinowski Doesn't seem to be: 
image

**Comment by jasonmalinowski** [comment]
Huh. I guess the type we get in that case is a ITypeSymbol vs. the constructor? Then this looks good to me (other than the formatting nitpick). Any other takes from @dotnet/roslyn-ide?

**Comment by CyrusNajmabadi** [comment]
"Constructor names were classifying as types "

Is that a bad thing?  If you have:  "new Foo()" then we classify that constructor as a type.

**Comment by dpen2000** [comment]
@jasonmalinowski The Symbol in the "new MyClass" cases is NamedTypeSymbol.

**Comment by dpen2000** [comment]
@CyrusNajmabadi This isn't "new Foo()" though: it's "Foo.Foo" so the second "foo" is definitely a constructor, rather than a type.

**Comment by dpen2000** [comment]
@CyrusNajmabadi Also this classification as implemented here matches the classification in the tooltip as shown on the [original bug](https://github.com/dotnet/roslyn/issues/633#issuecomment-157572794)

**Comment by CyrusNajmabadi** [comment]
Right.  But i'm saying: why is it wrong to classify a constructor in this manner? :)  I'm not getting why it's a bad thing.  In general we treat constructors and types relatively interchangeably.  For example, if you do a FindRefs on a type, we find references to the constructors as well.

**Comment by dpen2000** [comment]
@CyrusNajmabadi I wouldn't say wrong. I'd say it's consistent with the colour of the name of constructor's identifier where defined and also with the display in QuickInfo. Even though it's impossible to nest a Foo class within a Foo class, it's still nice in this context where the constructor is being named to distinguish between a Nested Class and a Constructor by colour.

**Comment by CyrusNajmabadi** [comment]
LGTM with the formatting change Jason mentioned.

**Comment by CyrusNajmabadi** [comment]
That seems reasonable.  Thanks for the PR!

**Comment by dpen2000** [comment]
@jasonmalinowski @CyrusNajmabadi  I've just done formatting change (and switching to IsParentKind as suggested by @balajikris). Thanks

**Comment by Pilchie** [comment]
:+1:

**Comment by balajikris** [comment]
@dotnet-bot test vsi please

**Comment by balajikris** [comment]
@dotnet-bot retest windows_vsi_p2_open_prtest please
// previous failure:
// http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/53/consoleFull#27916441661aefe2b-268e-4e71-8c03-11b4c0acbfbc
// http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/53/testReport/junit/(root)/CSharpErrorLog_v1_Engine/Error_List_Intellisense_Diagnostics/
// retest reason: failure does not look related to the change, will investigate offline.

**Comment by balajikris** [comment]
@dotnet/roslyn-analysis : can someone from the team take a look at why this VSI test (CSharpErrorLog_v1_Engine.xml) is consistently failing on this PR with mismatched diagnostics count although the PR seemingly doesn't do anything related to diagnostics? thanks.

**Comment by balajikris** [comment]
@srivatsn @mavasani : can you or someone from the team help explain the above comment on diagnostics test failure? thanks.

**Comment by srivatsn** [comment]
@heejaechang can you please take a look here?

**Comment by dpen2000** [comment]
@balajikris Any chance we can get someone to look at this?

**Comment by CyrusNajmabadi** [comment]
retest windows_vsi_p2_open_prtest please

**Comment by balajikris** [comment]
retest windows_vsi_p2_open_prtest please

**Comment by balajikris** [comment]
@dotnet/roslyn-infrastructure : can someone take this PR through to merging, after tests pass? It has the required sign offs.

**Comment by balajikris** [comment]
All tests passed, we have sufficient sign offs. Merging.

**Comment by balajikris** [comment]
Thanks for the contribution @dpen2000
