### PR TITLE
Do not convert mutable value type fields to properties

### LINKED ISSUE #28511: code fix for IDE0032 analyser (Use auto property) creates broken code
The code fix for IDE0032 analyser (Use auto property) creates broken code. Please check the following example:

```csharp
using System.Windows;
using FluentAssertions;
using Xunit;

namespace CleanupBug
{
    public class CleanupClass
    {
        private Rect bounds = Rect.Empty;

        public Rect Bounds => this.bounds;

        public void Setup()
        {
            this.bounds = new Rect(new Point(10, 10), new Point(20, 20));
            this.bounds.Offset(10, 10);
        }
    }

    public class TestClass
    {
        [Fact]
        public void Test()
        {
            var sut = new CleanupClass();
            sut.Bounds.Should().BeEquivalentTo(Rect.Empty);

            sut.Setup();

            sut.Bounds.Should().BeEquivalentTo(new Rect(new Point(20, 20), new Point(30, 30)));
        }
    }
}
```

In VS2017 (15.7.4) the field &quot;bounds&quot; will be identified to be convertible to auto property.
Before applying the code fix the UnitTest succeed.
After applying the code fix the UnitTest fails.

The reason - I think - is that the Rect data will be copied when accessing the auto property with the Offset method, because Rect is a struct.
So, the original data will NOT be modified.

Either the analyzer should not get struct fields or the code fix should take care modifying access.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/289507/code-fix-for-ide0032-analyser-use-auto-property-cr.html
VSTS ticketId: 644840_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #28511

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/UseAutoProperty/UseAutoPropertyTests.cs [hunk 1]
```diff
@@ -39,6 +39,50 @@ int P
 }");
         }
 
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseAutoProperty)]
+        [WorkItem(28511, "https://github.com/dotnet/roslyn/issues/28511")]
+        public async Task TestMutableValueType1()
+        {
+            // Nullable<T> is a mutable value type. The diagnostic is not offered if the field is writable.
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/UseAutoProperty/UseAutoPropertyTests.cs]: That's super weird.  How is Nullable obervably mutable?  This actually seems like a regression for thsi scenario as the moment i have a nullable field, i can't use this feature?

File: src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs [hunk 2]
```diff
@@ -854,5 +854,24 @@ public static bool IsEnumType(this ITypeSymbol type)
...
+            }
+
+            foreach (var member in type.GetMembers())
+            {
+                if (member is IFieldSymbol fieldSymbol &&
+                    !(fieldSymbol.IsConst || fieldSymbol.IsReadOnly || fieldSymbol.IsStatic))
+                {
+                    return true;
+                }
+            }
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs]: i think we should whitelist some structs here.  otherwise, common patterns will break.

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs]: Note: handling Nullable specially doesn't even seem like a problem to me given it's a core language concept.

File: src/EditorFeatures/CSharpTest/UseAutoProperty/UseAutoPropertyTests.cs (hunk 1 above)
Comment (sharwell) [reply src/EditorFeatures/CSharpTest/UseAutoProperty/UseAutoPropertyTests.cs]: https://github.com/dotnet/coreclr/pull/15198

File: src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs (hunk 2 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs]: If we add special handling for `Nullable<T>`, it would be for cases where `!typeof(T).IsMutableValueType()`, which does cover a majority of relevant cases.

File: src/EditorFeatures/CSharpTest/UseAutoProperty/UseAutoPropertyTests.cs (hunk 1 above)
Comment (sharwell) [reply src/EditorFeatures/CSharpTest/UseAutoProperty/UseAutoPropertyTests.cs]: ➡️ I'll update the test to use a struct `MutableInt32` for resilience. I'll keep the `Nullable<T>` tests so the future behavior change, if any, is clear.

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/UseAutoProperty/UseAutoPropertyTests.cs]: That seems like a "them" problem, not an IDE problem :D.   I would still treat things like Nullable as being immutable since for 100% of our users it actually will be, and having this feature not show up is a worse cure :)   I'm fine for general, non-BCL, otherwise-mutable structs getting this treatment.

Comment (sharwell) [reply src/EditorFeatures/CSharpTest/UseAutoProperty/UseAutoPropertyTests.cs]: `Nullable<T>` is observably mutable if `T` is observably mutable. I'm going to add tests for this case with a clear message on each test if the user finds themselves changing the expected outcome it means they are doing something wrong.

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/UseAutoProperty/UseAutoPropertyTests.cs]: > Nullable<T> is considered observably mutable if T is considered observably mutable

I don't see how that could be.  You can only get the inner value through a Property.  So it will always be copied out even if the inner T is mutable.  

Here's a simple example showing htat:

```c#
internal struct MStruct
{
    public int i;

    public void Mutate()
    {
        i++;
    }
}

internal class C
{
    static MStruct? m = new MStruct();

    private static void Main(string[] args)
    {
        m.Value.Mutate();
        Console.WriteLine(m.Value.i);
        Console.ReadLine();
```

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/UseAutoProperty/UseAutoPropertyTests.cs]: Oh, i see the repro case:

```c#
internal struct MStruct
{
    public int i;

    public override string ToString()
    {
        i++;
        return "";
    }
}

internal class C
{
    static MStruct? m = new MStruct();

    private static void Main(string[] args)
    {
        Console.WriteLine(m.ToString());
        Console.WriteLine(m.Value.i);
        Console.ReadLine();
```

IMO, this is so staggeringly unlikely htat it would be fine to still allow this.  We have far more likely situations that can occur with other refactorings/fixes, but we still allow because the 100% case for customers is unaffected.

File: src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs (hunk 2 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs]: That would be fine with me :)

File: src/EditorFeatures/CSharpTest/UseAutoProperty/UseAutoPropertyTests.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/UseAutoProperty/UseAutoPropertyTests.cs]: I'm also fine with your approach below of make this work for Nullable if T is not a mutable valuable type.  That way if i have an `int?` then i still get this feature.

Comment (sharwell) [reply src/EditorFeatures/CSharpTest/UseAutoProperty/UseAutoPropertyTests.cs]: It's more likely to appear as a performance problem due to failure to cache a lazily-computed string. I like starting at the safe end and trying to find ways to address false positives without just ignoring the safety issue from the start.

**Comment by sharwell** [comment]
@CyrusNajmabadi This is now updated

File: src/EditorFeatures/CSharpTest/UseAutoProperty/UseAutoPropertyTests.cs [hunk 3]
```diff
@@ -39,6 +39,292 @@ int P
 }");
         }
 
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsUseAutoProperty)]
+        [WorkItem(28511, "https://github.com/dotnet/roslyn/issues/28511")]
+        public async Task TestNullable1()
+        {
+            // ⚠ The expected outcome of this test should not change.
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/UseAutoProperty/UseAutoPropertyTests.cs]: lol.  emojis!

File: src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs [hunk 4]
```diff
@@ -854,5 +854,49 @@ public static bool IsEnumType(this ITypeSymbol type)
...
+
+            if (type.IsNullable())
+            {
+                // Nullable<T> can only be mutable if T is mutable. This case ensures types like 'int?' are treated as
+                // immutable.
+                var typeArguments = type.GetTypeArguments();
+                if (typeArguments.Length != 1)
+                {
+                    return null;
+                }
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs]: i'm virtually certain that this can't happen. Indeed, all we're doing is checking for System_Nullable_T.  If you look at the compiler, for example, they assume all over the place that this means you certainly can safely get that type arg back.

The main reason i'm complaining here is that this means we now have this weird null/tri-state pattern for this method.  I'd rather us not have to have that.  Worst case, even if we're paranoid and we see this, we just default to assuming it's mutable (or immutable) or something.  It's basically fine to have this be a boolean and not a tristate.

File: src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs [hunk 5]
```diff
@@ -854,5 +854,49 @@ public static bool IsEnumType(this ITypeSymbol type)
...
+
+                if (typeArguments[0].IsNullable())
+                {
+                    // Recursion prevention. This is not a valid type anyway since the T in Nullable<T> cannot itself be
+                    // nullable.
+                    return null;
+                }
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs]: the only recursion that would really be concerning would be some sort of infinite nullable type.  But... if we had that... lots of our system would likely break anyways :)  

you could also make this more simple by just doing:

```
type = typeArgument[0];
```

Then you don't need recursion at all.  You just fall through to the bottom code here, using hte inner type parameter without any recursion.

File: src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs (hunk 4 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs]: > The main reason i'm complaining here is that this means we now have this weird null/tri-state pattern for this method.

Error type handling leaves us with tri-state even if this goes away :\

File: src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs (hunk 5 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs]: Thanks, applied this simplification in 89849ea3bbe9af28b16191d6898e8c60b991b124

File: src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs (hunk 4 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs]: > i'm virtually certain that this can't happen.

Applied this simplification

> we just default to assuming it's mutable (or immutable) or something

Pattern in similar methods appears to be "when unknown, assume *not* that kind". This causes a problem for the two analyzers which would start to have diagnostic false positives using that approach, so rather than silently using an inconsistent `bool` pattern to make the analyzers work right I changed up the signature to make it obvious that something's different.

**Comment by sharwell** [comment]
retest this please

**Comment by sharwell** [comment]
retest this please
