### PR TITLE
Made testcase  ConditionalMemberAccessRace002 to exit more reliably.

### LINKED ISSUE #760: Intermittent failure of ConditionalMemberAccessRace002
I get intermittent failures of ConditionalMemberAccessRace002

When it fails, I see this:

```none
 Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenShortCircuitOperatorTests.ConditionalMemberAccessRace002 : System.CannotUnloadAppDomainException : Error while unloading appdomain. (Exception from HRESULT: 0x80131015)
   at System.AppDomain.Unload(AppDomain domain)
   at Microsoft.CodeAnalysis.Test.Utilities.HostedRuntimeEnvironment.System.IDisposable.Dispose() in D:\Roslyn\Open\src\Test\Utilities\HostedRuntimeEnvironment.cs:line 422
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompilationVerifier.Emit(String expectedOutput, IEnumerable`1 manifestResources, Boolean peVerify, SignatureDescription[] expectedSignatures) in D:\Roslyn\Open\src\Test\Utilities\CommonTestBase.CompilationVerifier.cs:line 116
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(CommonTestBase test, Compilation compilation, IEnumerable`1 dependencies, TestEmitters emitOptions, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Action`2 assemblyValidator, Action`2 symbolValidator, Boolean collectEmittedAssembly, Boolean verify) in D:\Roslyn\Open\src\Test\Utilities\CommonTestBase.cs:line 329
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, TestEmitters emitOptions, Action`2 sourceSymbolValidator, Action`2 assemblyValidator, Action`2 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Boolean collectEmittedAssembly, Boolean verify) in D:\Roslyn\Open\src\Test\Utilities\CommonTestBase.cs:line 222
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(String[] sources, IEnumerable`1 additionalRefs, IEnumerable`1 dependencies, TestEmitters emitOptions, Action`2 sourceSymbolValidator, Action`2 assemblyValidator, Action`2 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, CompilationOptions options, Boolean collectEmittedAssembly, Boolean verify) in D:\Roslyn\Open\src\Test\Utilities\CommonTestBase.cs:line 155
   at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerify(String source, IEnumerable`1 additionalRefs, IEnumerable`1 dependencies, TestEmitters emitOptions, Action`2 sourceSymbolValidator, Action`2 assemblyValidator, Action`2 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, CompilationOptions options, Boolean collectEmittedAssembly, Boolean verify) in D:\Roslyn\Open\src\Test\Utilities\CommonTestBase.cs:line 119
   at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(String source, IEnumerable`1 additionalRefs, IEnumerable`1 dependencies, TestEmitters emitOptions, Action`1 sourceSymbolValidator, Action`2 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, CompilationOptions options, Boolean collectEmittedAssembly, Boolean verify) in D:\Roslyn\Open\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs:line 79
   at Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenShortCircuitOperatorTests.ConditionalMemberAccessRace002() in D:\Roslyn\Open\src\Compilers\CSharp\Test\Emit\CodeGen\CodeGenShortCircuitOperatorTests.cs:line 4244
```

### PR DESCRIPTION
**Pull request by VSadov**
Fixes #760

### CODE REVIEW

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenShortCircuitOperatorTests.cs [hunk 1]
```diff
@@ -4218,25 +4218,30 @@ static void Main()
...
+        tasks.Add(Task.Factory.StartNew(a));
+        tasks.Add(Task.Factory.StartNew(a));
+        tasks.Add(Task.Factory.StartNew(a));
+        tasks.Add(Task.Factory.StartNew(a));
+        tasks.Add(Task.Factory.StartNew(a));
+        tasks.Add(Task.Factory.StartNew(a));
+        tasks.Add(Task.Factory.StartNew(a));
+        tasks.Add(Task.Factory.StartNew(a));
+        tasks.Add(Task.Factory.StartNew(a));
+        tasks.Add(Task.Factory.StartNew(a));
```
Comment (VladimirReshetnikov) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenShortCircuitOperatorTests.cs]: Consider using collection initializer.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenShortCircuitOperatorTests.cs [hunk 2]
```diff
@@ -4176,7 +4176,7 @@ static void Main()
             var comp = CompileAndVerify(source, expectedOutput: @"Success");
         }
 
-        [Fact(Skip = "836"), WorkItem(836, "GitHub")]
+        [Fact(), WorkItem(836, "GitHub")]
         public void ConditionalMemberAccessRace002()
```
Comment (VladimirReshetnikov) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenShortCircuitOperatorTests.cs]: Consider removing it to `ConditionalMemberAccessRaceCondition002` (and also its siblings).

**Comment by gafter** [comment]
:+1:
