### PR TITLE
Fix bug when "End statement" is used in single-line if

### LINKED ISSUE #14761: Missing parser error BC30205: End of statement expected.
```
Module Module1

    Sub Main()

    End Sub

    Sub Test(val As Object)
        Dim r As String

        If val Is Nothing Then r = "null" GoTo label1

label1:
    End Sub
End Module
```

Expected:

```
(11) : error BC30205: End of statement expected.

        If val Is Nothing Then r = "null" GoTo label1
                                          ~~~~~~~~~~~
```

Observed: No error, compilation succeeds.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes https://github.com/dotnet/roslyn/issues/45158

The "OrElse" part was existing in `IsValidStatementTerminator` in `ParserScan.vb`.

It was removed in #14822 to fix #14761. However, this change caused the bug I mentioned in #45158.

If I put this "OrElse" part were it was originally, it will break the fix made in #14822. Hence, I moved it here where it's actually needed.

@AlekseyTs Please review.

### CODE REVIEW

File: src/Compilers/VisualBasic/Test/Semantic/Binding/Binder_Statements_Tests.vb [hunk 1]
```diff
@@ -3741,6 +3741,54 @@ Done
 
         End Sub
 
+        <WorkItem(45158, "https://github.com/dotnet/roslyn/issues/45158")>
+        <Fact>
+        Public Sub EndWithSingleLineIf()
```
Comment (333fred) [inline src/Compilers/VisualBasic/Test/Semantic/Binding/Binder_Statements_Tests.vb:3746]: Consider have a version of this test in library output that verifies the error case.

**Comment by 333fred** [comment]
One test suggestion, otherwise this looks fine.

**Comment by Youssef1313** [comment]
`roslyn-CI (Windows_Desktop_Unit_Tests debug_32) Cancelled after 26m — Windows_Desktop_Unit_Tests debug_32 was canceled`

@RikkiGibson Need build re-trigger here.

**Comment by cston** [comment]
Thanks @Youssef1313.
