### PR TITLE
Fix 'invert if' refactor to properly enclose #region/#endregion blocks

### LINKED ISSUE #73917: "Invert if" does not properly enclose an entire `#region`/`#endregion`
**Version Used**: 
VS 17.10.1

**Steps to Reproduce**:

Add something like the following code to a program:

```cssharp
		public void SomeMethod()
		{
			object something = null;

			if (something == null)
			{
				return;
			}

			#region A region
			something = new object();
			#endregion
		}
```

And then use the "Invert if" refactor on the `if` statement.

**Diagnostic Id**:

I don't know the diagnostic id. I'm not 100% sure this refactor is part of this repository.

This also might be the case for other code block refactors.

**Expected Behavior**:

After the refactor the `#endregion` should be inside the `if` block.

**Actual Behavior**:

The refactor puts it outside the closing `}`.

### PR DESCRIPTION
**Pull request by GiovanniBraconi**
## PR Description

Fixes #73917 

### Context:
While this fix targets a specific case (InvertIfStyle.IfWithoutElse_MoveSubsequentStatementsToIfBody) of GetRootWithInvertIfStatement(), it's likely that similar issues exist in other cases within this method. As I'm new to the repository i wanted to start with this specific case to ensure the approach is correct before making broader changes.

### CODE REVIEW

File: src/Features/Core/Portable/InvertIf/AbstractInvertIfCodeRefactoringProvider.cs [hunk 1]
```diff
@@ -570,6 +570,12 @@ private ImmutableArray<StatementRange> GetSubsequentStatementRanges(TIfStatement
                     var statementsAfterIf = statements.Skip(index + 1);
                     var ifBody = GetIfBody(ifNode);
 
+                    var currentParentClosingBrace = currentParent.ChildTokens().Last();
+                    var updatedLastStatement = statementsAfterIf.Last().WithTrailingTrivia(currentParentClosingBrace.LeadingTrivia);
+
+                    statementsAfterIf = statementsAfterIf.Take(statementsAfterIf.Count() - 1);
+                    statementsAfterIf = statementsAfterIf.Append(updatedLastStatement);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/InvertIf/AbstractInvertIfCodeRefactoringProvider.cs:577]: doc what's going on here.  Specifically that you're trying to take any final structured trivia on the close brace, and moving it with the statements.

File: src/Features/CSharpTest/InvertIf/InvertIfTests.Elseless.cs [hunk 2]
```diff
@@ -483,6 +483,38 @@ void M()
...
+
+                if (something != null)
+                {
+                    #region A region
+                    something = new object();
+                    #endregion
+                }
+            }
+            """);
+    }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharpTest/InvertIf/InvertIfTests.Elseless.cs:516]: can you have a test where the parent scope is a `case` block in a switch?  

also a test where we're inverting an if-statement as a top level statement?

**Comment by CyrusNajmabadi** [comment]
This looks good.  Just would like some extra tests.  Thanks!

**Comment by GiovanniBraconi** [comment]
Thanks for the review @CyrusNajmabadi 😄. I'll follow your suggestions ASAP.

File: src/Features/CSharpTest/InvertIf/InvertIfTests.Elseless.cs (hunk 2 above)
Comment (GiovanniBraconi) [reply src/Features/CSharpTest/InvertIf/InvertIfTests.Elseless.cs:516]: I added the switch case test 😃. 

I also checked for the top level if-statement but the refactor is not suggested. Am i missing something?

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks!
