### PR TITLE
Change the Using organizer to not use ElasticTrivia for the NewLine

### LINKED ISSUE #36984: Code Cleanup doesn't respect dotnet_separate_import_directive_groups
**Version Used**: 

VisualStudio.16.IntStage/16.2.0-pre.4.0+29101.197.d16.2stg

**Steps to Reproduce**:

1. Create a .NET Core console app with the following files:

.editorconfig
```
dotnet_separate_import_directive_groups = true
```

Program.cs
```
using Microsoft.CSharp.RuntimeBinder;
using System;

namespace ConsoleApp47
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            new RuntimeBinderException();
        }
    }
}
```

2. Run Code Cleanup with a profile that includes "Sort usings"

**Expected Behavior**:

Usings should have a blank line between them.

**Actual Behavior**:

No change.

Note that if you use the Remove and Sort Usings, or Sort Usings commands, they do correctly separate, and if you run Code Cleanup with them separated, they do not get recombined back together (which is correct behaviour).

### PR DESCRIPTION
**Pull request by JoeRobich**
Code Cleanup removes and sorts usings prior to running the whitespace formatter. The Using organizer used elastic trivia for the newline that it introduced between using groups which would get eaten by the formatter.

Fixes #36984

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
> The Using organizer used elastic trivia for the newline that it introduced between using groups which would get eaten by the formatter.

That also seems like a formatter bug.  The formatter should likely respect this option.  After all, if a user (i.e.a 3rd party) puts elastic trivia here, they're saying "format this appropriate as per user settings".  If the formatter isn't doing that, that's not great.

File: src/Workspaces/CSharp/Portable/Utilities/UsingsAndExternAliasesOrganizer.cs [hunk 1]
```diff
@@ -11,7 +11,7 @@ namespace Microsoft.CodeAnalysis.CSharp.Utilities
 {
     internal static partial class UsingsAndExternAliasesOrganizer
     {
-        private static readonly SyntaxTrivia s_newLine = SyntaxFactory.ElasticCarriageReturnLineFeed;
+        private static readonly SyntaxTrivia s_newLine = SyntaxFactory.CarriageReturnLineFeed;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Utilities/UsingsAndExternAliasesOrganizer.cs]: does VB have the same problem?

Comment (JoeRobich) [reply src/Workspaces/CSharp/Portable/Utilities/UsingsAndExternAliasesOrganizer.cs]: hmm, It seems that we don't have an `ICodeCleanupFixerProvider` for VisualBasic..

File: src/Workspaces/VisualBasic/Portable/Utilities/ImportsOrganizer.vb [hunk 2]
```diff
@@ -6,7 +6,7 @@ Imports Microsoft.CodeAnalysis.VisualBasic.Syntax
 
 Namespace Microsoft.CodeAnalysis.VisualBasic.Utilities
     Partial Friend Class ImportsOrganizer
-        Private Shared ReadOnly s_newLine As SyntaxTrivia = SyntaxFactory.ElasticCarriageReturnLineFeed
+        Private Shared ReadOnly s_newLine As SyntaxTrivia = SyntaxFactory.CarriageReturnLineFeed
```
Comment (CyrusNajmabadi) [inline src/Workspaces/VisualBasic/Portable/Utilities/ImportsOrganizer.vb]: test somewhere? :)

Comment (JoeRobich) [reply src/Workspaces/VisualBasic/Portable/Utilities/ImportsOrganizer.vb]: Good idea =)
