### PR TITLE
[Stabilization] Codefix ordering: Prevent Low Priority fixes from interfering with Medium Priority fix ordering

### LINKED ISSUE #9596: The presence of a Priority Low fix causes ExtensionOrdering amongst Medium Priority fixes to be violated
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/415/artifact/Open/Binaries/Release/VSIntegrationTestLogs/CSharpCodeActions.html

Rename Tracking is still provided, and the ordering between it and Generate Type wrong:
 
image

Original fix ordering based on extension order:

- Fix A, ExtensionOrder 0, Priority Low, for Diagnostic 1
- Fix C, ExtensionOrder 1, Priority Medium, for Diagnostic 2
- Fix B, ExtensionOrder 2, Priority Medium, for Diagnostic 1

Grouped by diagnostic:

- Diagnostic 1
    - Fix A, ExtensionOrder 0, Priority Low
    - Fix B, ExtensionOrder 2, Priority Medium

- Diagnostic 2
    - Fix C, ExtensionOrder 1, Priority Medium

After "Priority Low" Items moved to the bottom:

- Fix B, ExtensionOrder 2, Priority Medium
- Fix C, ExtensionOrder 1, Priority Medium
- Fix A, ExtensionOrder 0, Priority Low

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #9596

Scenario -- user is trying to rename via Rename Tracking, but Fuzzy Add Using also wants to do it's "spellcheck" behavior and add a using for the spellcheck'd name. We want `<Ctrl+<dot>, Enter>` to do the rename in this case, not the fuzzy add using.

Because fuzzy using is new to Update 2, this is a regression in behavior that folks might find unexpected, reducing trust in `Ctrl+<dot>` correctness.

### CODE REVIEW

**Comment by dpoeschl** [comment]
Ping for review @dotnet/roslyn-ide @CyrusNajmabadi @jmarolf

**Comment by dpoeschl** [comment]
Listen. @jmarolf and I confirmed that this fixes the problem. I fixed up CSharpCodeActions.xml locally and added a scenario for this, and it's wonderful. But, like, @jasonmalinowski commented out a different scenario only in master, but that scenario is actually fine and unrelated to this, so adding my new test only in stabilization won't actually ever uncomment the commented one in master, so I have to also make a change to master as well, etc. etc. Trust us for now, everything will be great. I'll put a PR out tomorrow with the test fixes for both stabilization and master. Super promise.

**Comment by davkean** [comment]
@dotnet-bot test vsi please

File: src/EditorFeatures/Core/Implementation/Suggestions/SuggestedActionsSourceProvider.cs [hunk 1]
```diff
@@ -30,6 +30,8 @@
 
 namespace Microsoft.CodeAnalysis.Editor.Implementation.Suggestions
 {
+    using CodeFixGroupKey = Tuple<DiagnosticData, CodeActionPriority>;
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/Suggestions/SuggestedActionsSourceProvider.cs]: This needs commenting.

**Comment by CyrusNajmabadi** [comment]
:+1:

**Comment by dpoeschl** [comment]
@dotnet-bot retest prtest/win/vsi/p0 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p0/418/
// Retest reason: #9555

**Comment by dpoeschl** [comment]
@dotnet-bot retest prtest/win/vsi/p1 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p1/428/
// Retest reason: https://github.com/dotnet/roslyn/issues/9556 (/cc: @jmarolf)

**Comment by dpoeschl** [comment]
@dotnet-bot retest prtest/win/vsi/p3 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p3/431/
// Retest reason: https://github.com/dotnet/roslyn/issues/9557 (/cc:@jmarolf)

**Comment by dpoeschl** [comment]
@jmarolf Oops, I switched the retest reason bug #'s, but they're still both ones that you've been looking at.

**Comment by dpoeschl** [comment]
@MattGertz @Pilchie @davkean - Can we consider this for 1.2?

Re-ping @dotnet/roslyn-ide for reviews

**Comment by MattGertz** [comment]
Rejected, please fix in next milestone.

**Comment by MattGertz** [comment]
Second thoughts... approved.

**Comment by Pilchie** [comment]
:+1:

**Comment by dpoeschl** [comment]
All green, including VSI. @davkean, may I proceed with the mission?
