### PR TITLE
Avoid quadratic lookup of namespace declarations

### LINKED ISSUE #49769: csc takes far too long to compile 47MB of source code
**Version Used**: csc /version: 3.9.0-2.20574.26 (e9fd4dc7)

**Steps to Reproduce**:

Unzip and compile [the attached source code](https://microsoft-my.sharepoint.com/:u:/p/andarno/Ee0CUIQgJ4JJmfrkwnN1t80BhrJuqtKB9RGpxHTFzKFNGQ?e=KzqdRY) as a library.

**Expected Behavior**:

Compiler should take ~1 minute to compile.

**Actual Behavior**:

Compiler takes much longer. (it's been running for 35 minutes at 100% CPU on a 16 Core 4GHz machine, and still going)

[ETL trace](https://microsoft-my.sharepoint.com/:u:/p/andarno/EZz9iCZebAZGoG7k2FUy2aUBajqTyafhOWngEL8qg1xJYA?e=3sOW4Q)

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #49769

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs [hunk 1]
```diff
@@ -1759,6 +1759,12 @@ private Symbol GetDeclaredMember(NamespaceOrTypeSymbol container, TextSpan decla
 
             // look for any member with same declaration location
             var collection = name != null ? container.GetMembers(name) : container.GetMembersUnordered();
+            if (isKnownNamespace && name != null && collection is [NamespaceSymbol knownNamespace])
```
Comment (sharwell) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:1762]: 📝 In the heap dump I collected at a sample point during a very long build (almost 3 hours), all 8 threads sitting in this member would have hit this special case and returned the correct value immediately.

**Review by Kimj2539 — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs [hunk 2]
```diff
@@ -1750,7 +1750,7 @@ private Symbol GetDeclaredMember(NamespaceOrTypeSymbol container, TextSpan decla
         /// <summary>
         /// Finds the member in the containing symbol which is inside the given declaration span.
         /// </summary>
-        private Symbol GetDeclaredMember(NamespaceOrTypeSymbol container, TextSpan declarationSpan, string name = null)
+        private Symbol GetDeclaredMember(NamespaceOrTypeSymbol container, TextSpan declarationSpan, bool isKnownNamespace, string name = null)
```
Comment (mavasani) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:1753]: I am not clear what `isKnownNamespace` indicates. Can you please add details to the doc comment?

Comment (sharwell) [reply src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:1757]: ➡️ Amended the commit to include a comment. The diff for this can be reviewed in https://github.com/dotnet/roslyn/compare/dd3d407264e187c84d4b3e5e53921394da6f5e4b..c7c1262dcd54fe9b0b11fe4d3dfd8cd9df986d08.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:1757]: @sharwell 

> Amended the commit to include a comment.

Please do not do this for PRs under review. Rewrites like this confuse CodeFlow tool that compiler team relies on for code reviews.

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs [hunk 3]
```diff
@@ -1750,7 +1750,11 @@ private Symbol GetDeclaredMember(NamespaceOrTypeSymbol container, TextSpan decla
         /// <summary>
         /// Finds the member in the containing symbol which is inside the given declaration span.
         /// </summary>
-        private Symbol GetDeclaredMember(NamespaceOrTypeSymbol container, TextSpan declarationSpan, string name = null)
+        /// <param name="isKnownNamespace"><see langword="true"/> if the result is known to be a
+        /// <see cref="NamespaceSymbol"/> (e.g. when the caller is <see cref="GetDeclaredNamespace(BaseNamespaceDeclarationSyntax)"/>;
+        /// otherwise, <see langword="false"/> if the symbol kind is either unknown or known to not be a
+        /// <see cref="NamespaceSymbol"/>.</param>
+        private Symbol GetDeclaredMember(NamespaceOrTypeSymbol container, TextSpan declarationSpan, bool isKnownNamespace, string name = null)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:1757]: >isKnownNamespace [](http://example.com/codeflow?start=105&length=16)

I think the name is somewhat confusing. Consider using "isKnownToBeANamespace" instead.

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs [hunk 4]
```diff
@@ -1759,6 +1763,12 @@ private Symbol GetDeclaredMember(NamespaceOrTypeSymbol container, TextSpan decla
 
             // look for any member with same declaration location
             var collection = name != null ? container.GetMembers(name) : container.GetMembersUnordered();
+            if (isKnownNamespace && name != null && collection is [NamespaceSymbol knownNamespace])
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:1766]: >name != null [](http://example.com/codeflow?start=36&length=12)

Let's add an assert on entry into the function that ```name``` is not null if ```declarationSpan``` is true.

**Review by Kimj2539 — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs (hunk 4 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:1766]: >collection is [NamespaceSymbol knownNamespace] [](http://example.com/codeflow?start=52&length=46)

Let's restructure the code so that we could assert that this condition is true when ```isKnownNamespace``` is true. We should still check the condition for real.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 1)

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs (hunk 3 above)
Comment (sharwell) [reply src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:1757]: ⏱️ Renaming

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs (hunk 4 above)
Comment (sharwell) [reply src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:1766]: I'm concerned that the condition would not hold for certain real-world code, for example:

```
namespace Outer {
  namespace Inner { }
  class Inner { }
}
```

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs [hunk 5]
```diff
@@ -1759,6 +1763,12 @@ private Symbol GetDeclaredMember(NamespaceOrTypeSymbol container, TextSpan decla
...
+            {
+                // Avoid O(n²) lookup for merged namespaces with a large number of parts
+                // https://github.com/dotnet/roslyn/issues/49769
+                return knownNamespace;
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:1770]: ⏱️ Adding assertion:

```
Debug.Assert(knownNamespace.HasLocationContainedWithin(SyntaxTree, declarationSpan, out _));
```

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs (hunk 2 above)
Comment (sharwell) [reply src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:1757]: Compiler team has a general policy that one pull request equals one commit in history, even though policies like that are problematic for tools (e.g. Git Extensions). I strive to make my pull requests match the expectations of the merge history.

I already make a limited exception for the case where you specifically have started a review, opting to rewrite the pull request at the end of the review instead of during it.

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs (hunk 4 above)
Comment (sharwell) [reply src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs]: ➡️ Added this assertion. Will review what to do if tests fail.

Comment (sharwell) [reply src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs]: ➡️ Added this assertion. Will review what to do if tests fail.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs]: > I'm concerned that the condition would not hold for certain real-world code, for example

I think it would be good to be proactive and add an explicit test for this scenario. Quite possibly we would like to optimize scenarios like that too. Rather than checking for ```collection is [NamespaceSymbol knownNamespace]```, probably we should use ```collection.OfType<NamespaceSymbol>().AsSingleton() is NamespaceSymbol knownNamespace```. And assert that instead too

Comment (sharwell) [reply src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs]: ➡️ Updated to use `AsSingleton`, but in a slightly different non-allocating form.

**Review by Kimj2539 — APPROVED** [review]

**Review by Kimj2539 — APPROVED** [review]
Reviewed working changes

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 4)

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

**Review by CyrusNajmabadi — APPROVED** [review]
Nice!

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs [hunk 6]
```diff
@@ -1341,7 +1341,7 @@ private NamespaceSymbol GetDeclaredNamespace(BaseNamespaceDeclarationSyntax decl
             Debug.Assert((object)container != null);
 
             // We should get a namespace symbol since we match the symbol location with a namespace declaration syntax location.
-            var symbol = (NamespaceSymbol)GetDeclaredMember(container, declarationSyntax.Span, declarationSyntax.Name);
+            var symbol = (NamespaceSymbol)GetDeclaredNamespace(container, declarationSyntax.Span, declarationSyntax.Name);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:1344]: >(NamespaceSymbol) [](http://example.com/codeflow?start=25&length=17)

Do we still need this cast?

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs [hunk 7]
```diff
@@ -1759,6 +1763,24 @@ private Symbol GetDeclaredMember(NamespaceOrTypeSymbol container, TextSpan decla
 
             // look for any member with same declaration location
             var collection = name != null ? container.GetMembers(name) : container.GetMembersUnordered();
+            if (isKnownToBeANamespace)
+            {
+                // Filter the collection to only include namespace symbols. This will not allocate a new instance for
+                // the common case where all symbols in the collection are already namespace symbols.
+                var namespaces = collection.WhereAsArray(symbol => symbol is NamespaceSymbol);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:1770]: Consider avoiding this allocation

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 4) but a couple of nits to consider

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs (hunk 7 above)
Comment (sharwell) [reply src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs:1770]: ➡️ This already avoids allocations in the common case. The remaining allocation occurs in an edge case that is also a compile-time error, so users will be "strongly encouraged" to avoid it. 😄

File: src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs (hunk 6 above)
Comment (sharwell) [reply src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs]: ➡️ No, now removed

**Review by jcouv — APPROVED** [review]
Still LGTM Thanks (iteration 5)

**Comment by sharwell** [comment]
Rebased at end of review with no resulting changes:
https://github.com/dotnet/roslyn/compare/3ec88e4e6d656ca8bd5898b8fe73159530a065e8..3bc0ad498c8e7cde59004bd98929133f25be7379
