### PR TITLE
Fix issue with disappearing newlines after multiline documentation comment

### LINKED ISSUE #76856: NormalizeWhitespace breaks multi-line comments
**Version Used**: 

4.12.0

**Steps to Reproduce**:
Parse this code:

````csharp
        /**
         * 
         * Escape XML special characters
         */
        private String EscapeXML(String str)
        {
...
````

Call `.NormalizeWhitespace().ToFullString()` and observe the output.

**Expected Behavior**:

Something similar or identical to the input.

**Actual Behavior**:

````csharp
        ///
        /// 
        /// Escape XML special characters
        //////private String EscapeXML(String str)
        {
...
````

### PR DESCRIPTION
**Pull request by dgounaris**
This PR fixes #76856, where multi-line doc comments ending in a newline would have the newline disappearing afterwards.

Based on my investigation, the situation can be described as follows:
- The structured multiline comment token does not contain the newline by itself, and the normalizer's loop for `RewriteTrivia` skips newline tokens.
- `NeedsLineBreakAfter` call can't be the target for this fix, because not every comment needs a new line after it. Wider context is needed.
- `EndsInLineBreak` can be true for the doc token in cases where in reality the documentation end token is the ending token, due to the 0 width of the `EndOfDocumentationCommentToken` type.

The proposed fix adds a linebreak if the leading SyntaxToken is a multiline documentation ending in linebreak, and forces it to be retained during rewriting by slightly modifying `EndsInLineBreak` too.

As this is my first time contributing, let me know if I have not grasped the codebase correctly and there is a cleaner way to apply this.

### CODE REVIEW

**Comment by dgounaris** [comment]
@dotnet-policy-service agree

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs [hunk 1]
```diff
@@ -174,6 +175,22 @@ private static bool NeedsIndentAfterLineBreak(SyntaxToken token)
             return !token.IsKind(SyntaxKind.EndOfFileToken);
         }
 
+        private static int LineBreaksAfterLeading(SyntaxToken token)
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs:178]: Can this be a local function?

**Review by 333fred — COMMENTED** [review]
One small comment, otherwise LGTM.

**Comment by 333fred** [comment]
@dgounaris can you update your comment to specifically say "fixes <issue>", so that github picks this up as actually fixing the issue? "Fixes the issue described at <issue>" doesn't do the trick.

**Comment by dgounaris** [comment]
@333fred Thanks for the review, addressed the comments, feel free to have a look.

**Review by 333fred — APPROVED** [review]
@dotnet/roslyn-compiler for a second review

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs [hunk 2]
```diff
@@ -3790,6 +3790,26 @@ void goo()
...
+                * 
+                * Escape XML special characters
+                */
+               private String EscapeXML(String str)
+               {
+               """, """
+                    ///
+                    /// 
+                    /// Escape XML special characters
+                    //////
```
[the remark this answers is not in the document]
Comment (333fred) [reply src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs:3807]: I thought the same thing, but that generation is outside the scope of this request, imo. The current behavior has just as many slashes, but misses the newline after them so it ends up as `//////private String EscapeXML(String str)`.

**Review by jjonescz — APPROVED** [review]

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (dgounaris) [reply src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNormalizerTests.cs:3807]: Exactly, I didn't modify the resulting slashes because I didn't know if that was the expected result from a normalization point of view.
For future reference, the reason these additional slashes exist has to do with the fact that the comment ending token is padded with a whitespace, and both the padding and the comment ending token get replaced by `///`.

If the test instead had input of 
```
/**
 * 
 * Escape XML special characters
*/
``` 
there would be 3 slashes only.

If you think this should be fixed and padding should be ignored when replacing with slashes at comment end, let me know. I can pick this up as a follow-up improvement PR.

**Comment by dgounaris** [comment]
@jjonescz  Thanks for the review, I have applied the function convention nit and explained the multiple slashes situation. Feel free to merge.

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs [hunk 3]
```diff
@@ -94,13 +94,14 @@ public override SyntaxToken VisitToken(SyntaxToken token)
 
                 var depth = GetDeclarationDepth(token);
 
+                var lineBreaksAfterLeading = LineBreaksAfterLeading(token);
```
Comment (jjonescz) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs:97]:
```suggestion
```

File: src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs [hunk 4]
```diff
@@ -94,13 +94,14 @@ public override SyntaxToken VisitToken(SyntaxToken token)
...
                 tk = tk.WithLeadingTrivia(RewriteTrivia(
                     token.LeadingTrivia,
                     depth,
                     isTrailing: false,
                     indentAfterLineBreak: NeedsIndentAfterLineBreak(token),
                     mustHaveSeparator: false,
-                    lineBreaksAfter: 0));
+                    lineBreaksAfter: lineBreaksAfterLeading));
```
Comment (jjonescz) [inline src/Compilers/CSharp/Portable/Syntax/SyntaxNormalizer.cs:104]:
```suggestion
                    lineBreaksAfter: lineBreaksAfterLeading(token)));
```

**Comment by jjonescz** [comment]
Thanks for the contribution, @dgounaris!
