### PR TITLE
Removed "sealed" from base class

### LINKED ISSUE #63929: Extract base class doesn't remove `sealed` modifier
**Version Used**: 17.4 P2

**Steps to Reproduce**:

Run extract base class on a sealed type, eg:

```
public sealed class Class1
{
    public void M()
    {
    }
}
```

(make sure you tick the box next to `M()` in the dialog or the base class that is created won't actually be used. Possibly another bug??

**Expected Behavior**:
Since the whole point of the refactoring is to create a class that is a "base", the `sealed` modifier should be removed.
```
public class Class1Base
{
    public void M()
    {
    }
}
```

**Actual Behavior**:
You end up with a sealed base class
```
public sealed class Class1Base
{
    public void M()
    {
    }
}
```
and a compile error
image

### PR DESCRIPTION
**Pull request by ryzngard**
Fixes #63929

### CODE REVIEW

**Review by CyrusNajmabadi — APPROVED** [review]

**Review by genlu — APPROVED** [review]

File: src/EditorFeatures/CSharpTest/ExtractClass/ExtractClassTests.cs [hunk 1]
```diff
@@ -2488,6 +2488,48 @@ public async Task TestTopLevelStatementSelection_NoAction()
...
+                TestCode = input,
+                FixedState =
+                {
+                    Sources =
+                    {
+                        expected1,
+                        expected2
+                    }
+                },
+                FileName = "Test1.cs"
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/ExtractClass/ExtractClassTests.cs:2529]: 😕 What is this?

Comment (sharwell) [reply src/EditorFeatures/CSharpTest/ExtractClass/ExtractClassTests.cs:2529]: ➡️ It's the file name provided by the user to the dialog.

**Review by sharwell — APPROVED** [review]

**Review by CyrusNajmabadi — APPROVED** [review]
