### PR TITLE
Fix invert if for cases where the if block is empty

### LINKED ISSUE #43224: When inverting If with code only in Else section, The code moves to the primary area and is left in the else
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/975321/when-inverting-if-with-code-only-in-else-section-t.html)._

---
I have VB.NET code that looks like:

```
If SomeValue = AnotherValue Then
Else
    DoStuff()
End If
```
When I select the Invert If code fix I end up with:

```
If SomeValue <> AnotherValue Then
    DoStuff()
Else
    DoStuff()
End If
```

I am in VS 2019 version 16.5.2

---
#### Visual Studio Feedback System on 4/2/2020, 08:05 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by ryzngard**
Fixes #43224

### CODE REVIEW

File: src/Features/CSharp/Portable/InvertIf/CSharpInvertIfCodeRefactoringProvider.cs [hunk 1]
```diff
@@ -193,6 +198,35 @@ protected override StatementSyntax AsEmbeddedStatement(IEnumerable<StatementSynt
...
+                // The statement is not expected to have children, so we know it's fine
+                // to consider this something that needs to be included. Such as 
+                // a return statement, or other similar things for single line if/else.
+                return true;
+            }
+
+            // If the stateements for the else don't pass, we still need to check
+            // if there are comments from the original if that should be included.
+            // If so, pass them along to be copied to the new else block
+            return ifStatement.Statement is BlockSyntax block
```
Comment (davidwengier) [inline src/Features/CSharp/Portable/InvertIf/CSharpInvertIfCodeRefactoringProvider.cs:224]: It would probably make more sense to put this in the if block above. Its a little confusing coming after an `else { return; }`. I would say "you should invert the if", but that seems a little too ironic to be in good taste :)

**Review by davidwengier — APPROVED** [review]

File: src/EditorFeatures/CSharpTest/InvertIf/InvertIfTests.cs [hunk 2]
```diff
@@ -1037,5 +1037,100 @@ public async Task TestIsExpression()
...
 @"class C { void M(object o) { if (o is not C) { } else { a(); } } }");
         }
+
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsInvertIf)]
+        [WorkItem(43224, "https://github.com/dotnet/roslyn/issues/43224")]
+        public async Task TestEmptyIf()
+        {
+            await TestInRegularAndScriptAsync(
+                @"class C { void M(string s){ [||]if (s == ""a""){}else{ s = ""b""}}}",
+                @"class C { void M(string s){ if (s != ""a""){ s = ""b""}}}");
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/InvertIf/InvertIfTests.cs:1047]: tbh, this seems a bit strange.  but i guess it's fine :)

File: src/EditorFeatures/VisualBasicTest/InvertIf/InvertMultiLineIfTests.vb [hunk 3]
```diff
@@ -654,5 +654,60 @@ Imports System
...
+            DoSomething()
+        End If
+    end sub
+
+    sub DoSomething()
+    end sub
+end class",
+"class C
+    sub M(x as String)
+        If x IsNot ""a"" Then
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/VisualBasicTest/InvertIf/InvertMultiLineIfTests.vb:674]: it's a bit strange that `=` got replaced with`IsNot` instead of `<>`.

File: src/Features/CSharp/Portable/InvertIf/CSharpInvertIfCodeRefactoringProvider.cs [hunk 4]
```diff
@@ -175,14 +175,19 @@ protected override StatementSyntax AsEmbeddedStatement(IEnumerable<StatementSynt
                     ? SyntaxFactory.Block(trueStatement)
                     : trueStatement);
 
-            if (falseStatementOpt != null)
+            if (falseStatementOpt != null &&
+                ShouleKeepFalse(ifNode, falseStatementOpt))
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InvertIf/CSharpInvertIfCodeRefactoringProvider.cs:179]: maybe just `            if (ShouleKeepFalse(ifNode, falseStatementOpt))` and have ShouldKeepFalse do the null check.

File: src/Features/CSharp/Portable/InvertIf/CSharpInvertIfCodeRefactoringProvider.cs [hunk 5]
```diff
@@ -193,6 +198,35 @@ protected override StatementSyntax AsEmbeddedStatement(IEnumerable<StatementSynt
                 : updatedIf.WithAdditionalAnnotations(Formatter.Annotation);
         }
 
+        private static bool ShouleKeepFalse(IfStatementSyntax ifStatement, StatementSyntax falseStatement)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InvertIf/CSharpInvertIfCodeRefactoringProvider.cs:201]: `Shoule`

File: src/Features/CSharp/Portable/InvertIf/CSharpInvertIfCodeRefactoringProvider.cs [hunk 6]
```diff
@@ -193,6 +198,35 @@ protected override StatementSyntax AsEmbeddedStatement(IEnumerable<StatementSynt
...
+                return true;
+            }
+
+            // If the stateements for the else don't pass, we still need to check
+            // if there are comments from the original if that should be included.
+            // If so, pass them along to be copied to the new else block
+            return ifStatement.Statement is BlockSyntax block
+                && block.CloseBraceToken.LeadingTrivia.Any(t => 
+                    t.IsKind(SyntaxKind.MultiLineCommentTrivia) ||
+                    t.IsKind(SyntaxKind.SingleLineCommentTrivia));
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InvertIf/CSharpInvertIfCodeRefactoringProvider.cs:227]: maybe check the openbracetopen.trailing trivia as well.  Also, i think we have some IsAnyComment extensions to unify the two kind checks.

**Review by CyrusNajmabadi — CHANGES_REQUESTED** [review]
Some small pieces of feedback.

File: src/EditorFeatures/VisualBasicTest/InvertIf/InvertMultiLineIfTests.vb (hunk 3 above)
Comment (ryzngard) [reply src/EditorFeatures/VisualBasicTest/InvertIf/InvertMultiLineIfTests.vb:674]: I didn't change the logic here... maybe worth a different bug?

File: src/EditorFeatures/CSharpTest/InvertIf/InvertIfTests.cs (hunk 2 above)
Comment (ryzngard) [reply src/EditorFeatures/CSharpTest/InvertIf/InvertIfTests.cs:1047]: which part?

File: src/Features/CSharp/Portable/InvertIf/CSharpInvertIfCodeRefactoringProvider.cs (hunk 1 above)
Comment (ryzngard) [reply src/Features/CSharp/Portable/InvertIf/CSharpInvertIfCodeRefactoringProvider.cs:224]: it's a bit confusing, because it's checking different things. One checks the original IfStatementSyntax , the other checks the else StatementSyntax

File: src/Features/CSharp/Portable/InvertIf/CSharpInvertIfCodeRefactoringProvider.cs (hunk 5 above)
Comment (ryzngard) [reply src/Features/CSharp/Portable/InvertIf/CSharpInvertIfCodeRefactoringProvider.cs:201]: woops

File: src/Features/CSharp/Portable/InvertIf/CSharpInvertIfCodeRefactoringProvider.cs (hunk 6 above)
Comment (ryzngard) [reply src/Features/CSharp/Portable/InvertIf/CSharpInvertIfCodeRefactoringProvider.cs:227]: I saw one for document comments, I'll check if I can find one for normal comments. Good idea on checking openbrace as well

File: src/Features/CSharp/Portable/InvertIf/CSharpInvertIfCodeRefactoringProvider.cs (hunk 4 above)
Comment (ryzngard) [reply src/Features/CSharp/Portable/InvertIf/CSharpInvertIfCodeRefactoringProvider.cs:179]: I like it

File: src/Features/CSharp/Portable/InvertIf/CSharpInvertIfCodeRefactoringProvider.cs (hunk 1 above)
Comment (ryzngard) [reply src/Features/CSharp/Portable/InvertIf/CSharpInvertIfCodeRefactoringProvider.cs:224]: I renamed to "originalIfStatement" to clarify

Comment (davidwengier) [reply src/Features/CSharp/Portable/InvertIf/CSharpInvertIfCodeRefactoringProvider.cs:224]: I just meant you could do:

```cs
if (falseStatement...)
{
	if (falseBlock.Statements.Any())
	{
	}

	return ifStatement.blalah
}

return true;
```

Comment (ryzngard) [reply src/Features/CSharp/Portable/InvertIf/CSharpInvertIfCodeRefactoringProvider.cs]: ah gotcha. Yea I like that, more clear.

File: src/EditorFeatures/CSharpTest/InvertIf/InvertIfTests.cs (hunk 2 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/InvertIf/InvertIfTests.cs:1047]: taht we are throwing away the empty block.  it feels like if hte user asks to invert, we should just invert.  another feature could potentially say: this block is useless

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/EditorFeatures/CSharpTest/InvertIf/InvertIfTests.cs (hunk 2 above)
Comment (ryzngard) [reply src/EditorFeatures/CSharpTest/InvertIf/InvertIfTests.cs:1047]: oh...gotcha. I'm going to leave for now because it was my gut that it's how it should work. That said, I'm not really opposed to leaving the empty block if we find that people don't like it being removed
