### PR TITLE
Run the simplifier over the expression generation tests to fix issue 26586

### LINKED ISSUE #26586: CodeGeneration produces unnecessary parentheses
**Version Used**: master

**Steps to Reproduce**:

Attempt to run CodeGeneration tests like:

https://github.com/dotnet/roslyn/blob/ef11fa5e23c823ecf76e401e0b35747d43b57169/src/EditorFeatures/Test/CodeGeneration/ExpressionGenerationTests.cs#L130-L138

**Expected Behavior**: The test passes.

**Actual Behavior**:

```
Test Name:	Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.ExpressionGenerationTests.TestAddExpression1
Test FullName:	Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.ExpressionGenerationTests.TestAddExpression1
Test Source:	C:\code\roslyn\src\EditorFeatures\Test\CodeGeneration\ExpressionGenerationTests.cs : line 129
Test Outcome:	Failed
Test Duration:	0:00:04,771

Result StackTrace:	
at Roslyn.Test.Utilities.AssertEx.Fail(String message) in C:\code\roslyn\src\Test\Utilities\Portable\Assert\AssertEx.cs:line 341
   at Roslyn.Test.Utilities.TokenUtilities.AssertTokensEqual(String expected, String actual, String language) in C:\code\roslyn\src\Test\Utilities\Portable\Syntax\TokenUtilities.cs:line 45
   at Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.AbstractCodeGenerationTests.Test(Func`2 nodeCreator, String cs, String vb) in C:\code\roslyn\src\EditorFeatures\Test\CodeGeneration\AbstractCodeGenerationTests.cs:line 31
   at Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.ExpressionGenerationTests.TestAddExpression1() in C:\code\roslyn\src\EditorFeatures\Test\CodeGeneration\ExpressionGenerationTests.cs:line 131
Result Message:	
Unexpected token.  Actual '^(^ 1 ) + ' Expected '^1^ + 2  '
Actual:
(1) + (2)
```

The test failure seems to be caused by unnecessary parentheses.

### PR DESCRIPTION
**Pull request by Paxxi**
Adds a new test helper method that runs the expressions
through the simplifier to remove parenthesis.

New test helper wraps the expression under test in some boilerplate to make sure the simplifier works properly. Without the boilerplate the simplifier never did any work. Did I miss something maybe?

Included also is a fix for one of the `TestMemberAccessOffOfElementAccess` test where the VB simplifier removed parenthesis when it shouldn't. I'm not sure the fix is correct but I included it here to allow for discussion and to get some input on it.
I'm not sure about the template and could use some help filling it out if it's required :)

<details><summary>Ask Mode template not completed</summary>

### Customer scenario

What does the customer do to get into this situation, and why do we think this
is common enough to address for this release.  (Granted, sometimes this will be
obvious "Open project, VS crashes" but in general, I need to understand how
common a scenario is)

### Bugs this fixes
#26586 

### Workarounds, if any

Also, why we think they are insufficient for RC vs. RC2, RC3, or RTW

### Risk

This is generally a measure our how central the affected code is to adjacent
scenarios and thus how likely your fix is to destabilize a broader area of code

### Performance impact
PR only touches test code so low or no perf impact.

### Is this a regression from a previous update?
No
### Root cause analysis

How did we miss it?  What tests are we adding to guard against it in the future?

### How was the bug found?

(E.g. customer reported it vs. ad hoc testing)

### Test documentation updated?

If this is a new non-compiler feature or a significant improvement to an existing feature, update https://github.com/dotnet/roslyn/wiki/Manual-Testing once you know which release it is targeting.

</details>

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Hey @Paxxi , could you update your title to something a bit more descriptive?  Thanks!

File: src/EditorFeatures/Test/CodeGeneration/AbstractCodeGenerationTests.cs [hunk 1]
```diff
@@ -14,6 +17,79 @@ namespace Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration
...
+            var annotatedRootNode = annotatedDocument.GetSyntaxRootAsync().Result;
+
+            var simplifiedDocument = Simplification.Simplifier.ReduceAsync(annotatedDocument).Result;
+
+            var rootNode = simplifiedDocument.GetSyntaxRootAsync().Result;
+
+            return rootNode;
+        }
+
+        private static SyntaxNode WrapExpressionInBoilerplate(Func<SyntaxGenerator, SyntaxNode> nodeCreator, SyntaxGenerator codeDefFactory)
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Test/CodeGeneration/AbstractCodeGenerationTests.cs]: Feels like the nodeCreator is superfluous.  Just pass the SyntaxGenerator and the generated expression to put in the local-decl-statement.

File: src/EditorFeatures/Test/CodeGeneration/ExpressionGenerationTests.cs [hunk 2]
```diff
@@ -125,21 +125,21 @@ public void TestDoubleLiteralExpression1()
...
+        [Fact]
         public void TestAddExpression1()
         {
-            Test(
+            TestWithSimplifier(
                 f => f.AddExpression(
                     f.LiteralExpression(1),
                     f.LiteralExpression(2)),
                 cs: "1 + 2",
                 vb: "1 + 2");
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Test/CodeGeneration/ExpressionGenerationTests.cs]: my preference is that TestWithSimplifier would also run the normal test.  So this should actually take 4 strings.  cs, csSimple, vb, vbSimple. 

After all, the point of this file is to test the generator not the simplifier, so we want to ensure we're always at *least* testing the generator output.

File: src/Workspaces/VisualBasic/Portable/Extensions/ParenthesizedExpressionSyntaxExtensions.vb [hunk 3]
```diff
@@ -343,7 +343,8 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Extensions
 
                 Dim parentExpression = TryCast(node.Parent, ExpressionSyntax)
                 If parentExpression IsNot Nothing Then
-                    If parentExpression.IsKind(SyntaxKind.SimpleMemberAccessExpression) Then
+                    If parentExpression.IsKind(SyntaxKind.SimpleMemberAccessExpression) OrElse
+                       parentExpression.IsKind(SyntaxKind.InvocationExpression) Then
```
Comment (CyrusNajmabadi) [inline src/Workspaces/VisualBasic/Portable/Extensions/ParenthesizedExpressionSyntaxExtensions.vb]: comment above needs to be updated to explain why this is necessary.

**Comment by CyrusNajmabadi** [comment]
> Included also is a fix for one of the TestMemberAccessOffOfElementAccess test where the VB simplifier removed parenthesis when it shouldn't. I'm not sure the fix is correct but I included it here to allow for discussion and to get some input on it.

I think the fix is likely correct.  presumably this is to deal with the ```(a + b)(0)``` case, yes?  If so, removing parens around `a + b` would definitely break things.

**Comment by CyrusNajmabadi** [comment]
> Without the boilerplate the simplifier never did any work. Did I miss something maybe?

Nope.  That's the correct way to do things.  The Simplifier needs real code to work on.  Something like "(1) + (1)" is not actually legal C#, so there's no way to properly parse that, let alone doing any semantic analysis of it to determine if can be simplified.

File: src/EditorFeatures/Test/CodeGeneration/ExpressionGenerationTests.cs (hunk 2 above)
Comment (Paxxi) [reply src/EditorFeatures/Test/CodeGeneration/ExpressionGenerationTests.cs]: Then it doesn't make so much sense to have two different test methods. I'll merge it all into the Test method. I initially separated them because some tests appeared to not result in valid syntax when used as a local declaration. Can pass null to csSimple/vbSimple if that's the case then.

File: src/EditorFeatures/Test/CodeGeneration/AbstractCodeGenerationTests.cs [hunk 4]
```diff
@@ -14,31 +17,99 @@ namespace Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration
...
         internal void Test(
             Func<SyntaxGenerator, SyntaxNode> nodeCreator,
-            string cs, string vb)
+            string cs, string csSimple,
+            string vb, string vbSimple)
         {
             var hostServices = MefV1HostServices.Create(TestExportProvider.ExportProviderWithCSharpAndVisualBasic.AsExportProvider());
             var workspace = new AdhocWorkspace(hostServices);
 
-            if (cs != null)
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Test/CodeGeneration/AbstractCodeGenerationTests.cs]: might be a good idea to assert that at least one of those 4 tests is not null.  We've def had cases in the past where you could call a test method with not enough info and always pass :D

Comment (Paxxi) [reply src/EditorFeatures/Test/CodeGeneration/AbstractCodeGenerationTests.cs]: Good idea, I'll add that :)

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-ide @jinujoseph @jcouv  can this test-only change be merged in? thanks!
