### PR TITLE
Handle string concat with no string literals in ConvertToInterpolatedString

### LINKED ISSUE #32864: "Sequence contains no matching element" in ConvertToInterpolatedString
**Version Used**: Preview 2.0

Press Ctrl+. anywhere from `$` to `)`:

```cs
class C
{
    void M()
    {
        _ = $"foo" + ("bar");
    }
}
```

Gives:

image

```
System.InvalidOperationException : Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source,Func`2 predicate)
   at async Microsoft.CodeAnalysis.ConvertToInterpolatedString.AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

### PR DESCRIPTION
**Pull request by genlu**
Fix #32864.

I have considered a few different options based on this particular scenario, e.g. 
```cs
var x = 1 + ("string");
```

1. Provide refactoring to convert it to 
```cs
var x = $"{1}{("string")}";
```

2. Provide refactoring that first removes unnecessary parentheses
```cs
var x = $"{1}string";
```

3. Don't offer to "convert to interpolated string". User must explicitly remove unnecessary parentheses first.

Option 1 is the simplest and most flexible (users might want the paren?). But once "convert to interpolated string" is selected first and then "remove paren", there's no way to flatten it to `${1}string` automatically.

Option 2 and 3 would avoid this problem by limiting the action user can take.

I ended up choosing Option 1 because (1) it's a very small change, with no behavior change to the refactoring, and (2) "flatten interpolated string" seems like a useful refactoring/codefix to have :)

@dotnet/roslyn-ide @CyrusNajmabadi

### CODE REVIEW

File: src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.cs [hunk 1]
```diff
@@ -60,25 +61,32 @@ public override async Task ComputeRefactoringsAsync(CodeRefactoringContext conte
...
+
+                // Make sure that all the string tokens we're concatenating are the same type
+                // of string literal.  i.e. if we have an expression like: @" "" " + " \r\n "
+                // then we don't merge this.  We don't want to be munging different types of
+                // escape sequences in these strings, so we only support combining the string
+                // tokens if they're all the same type.
+                var firstStringToken = stringLiterals[0].GetFirstToken();
+                isVerbatimStringLiteral = syntaxFacts.IsVerbatimStringLiteral(firstStringToken);
+                if (stringLiterals.Any(
+                    lit => isVerbatimStringLiteral != syntaxFacts.IsVerbatimStringLiteral(lit.GetFirstToken())))
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.cs]: indent this please.   the current indentation makes it look as if ths lamdba is at the same relevance level as 'stringLiterals'  but it's not, it's a child argument.

Comment (genlu) [reply src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.cs]: Fixed

**Comment by genlu** [comment]
@jinujoseph @vatsalyaagrawal for p4 approval
