### PR TITLE
Fix command line build error

### LINKED ISSUE #18204: [Flaky Test] Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpBuild.BuildWithCommandLine Test Failure
Failed in https://ci.dot.net/job/dotnet_roslyn/job/dev16/job/windows_release_vs-integration/24/. The logs only contain that the build failed with exit code 0, due to assert ordering. Submitted https://github.com/dotnet/roslyn/pull/18203 to address that issue.

### PR DESCRIPTION
**Pull request by chborl**
### Customer scenario
Create a solution and from command line run:
`devenv <solutionname>.sln /build`

### Bugs this fixes
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/559223
fixes #18204

### Workarounds, if any
build from IDE

### Risk
None, just added a null check on a method call

### Performance impact
None

### Root cause analysis
We are re-enabling this test: https://github.com/dotnet/roslyn/issues/18204 to catch this error.

### How was the bug found?
Internal - VS team

### Test documentation updated?
n/a

### CODE REVIEW

**Comment by chborl** [comment]
@jinujoseph @jasonmalinowski @heejaechang  for review

File: src/EditorFeatures/Core/Shared/Utilities/ForegroundThreadAffinitizedObject.cs [hunk 1]
```diff
@@ -32,7 +32,7 @@ internal static ForegroundThreadData CreateDefault(ForegroundThreadDataKind defa
         {
             var kind = ForegroundThreadDataInfo.CreateDefault(defaultKind);
 
-            return new ForegroundThreadData(Thread.CurrentThread, new SynchronizationContextTaskScheduler(SynchronizationContext.Current), kind);
+            return new ForegroundThreadData(Thread.CurrentThread, SynchronizationContext.Current == null ? TaskScheduler.Default : new SynchronizationContextTaskScheduler(SynchronizationContext.Current), kind);
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Shared/Utilities/ForegroundThreadAffinitizedObject.cs]: Actually, should this be TaskScheduler.Current? I don't presume we're using this much in the /build case, but Default _does_ mean we're always picking the thread pool. Current would mean it might be right (and might still be wrong, but whatever.)

Comment (heejaechang) [reply src/EditorFeatures/Core/Shared/Utilities/ForegroundThreadAffinitizedObject.cs]: https://msdn.microsoft.com/en-us/library/system.threading.tasks.taskscheduler.current(v=vs.110).aspx

Remarks
When not called from within a task, Current will return the Default scheduler.

..

so in this case, it will be Default anyway?

Comment (jasonmalinowski) [reply src/EditorFeatures/Core/Shared/Utilities/ForegroundThreadAffinitizedObject.cs]: If we run this inside of an xunit unit test, then it might pick up the xunit scheduler or something which _might_ be what we want there.

Comment (jasonmalinowski) [reply src/EditorFeatures/Core/Shared/Utilities/ForegroundThreadAffinitizedObject.cs]: Although I guess in that case SynchronizationContext.Current won't be null anyways. 🤷‍♂️

**Comment by jinujoseph** [comment]
Approved via [Link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/559223)
