### PR TITLE
Don't crash on self-referencing attribute in nullable

### LINKED ISSUE #40136: Stack overflow when attribute is applied on it's own constructor and nullability is enabled
**Version Used**: 
3.4.0 (VS 16.4.0, .NET Core SDK 3.1.100)

Worked on 3.3.1 (VS 16.3.x, .NET Core SDK 3.0.101)

**Steps to Reproduce**:

Enabled nullability (either in MSBuild or using `#nullable enable`).

Use the following:
```
[AttributeUsage(AttributeTargets.All)]
[ExplicitCrossPackageInternal]
internal sealed class ExplicitCrossPackageInternalAttribute : Attribute
{
    // Just for fun.
    [ExplicitCrossPackageInternal]
    internal ExplicitCrossPackageInternalAttribute()
    {
    }
}
```

The comment is two years old.

**Expected Behavior**:

Not crashing.

**Actual Behavior**:

```
Process is terminated due to StackOverflowException.
```

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #40136

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 1]
```diff
@@ -7235,6 +7235,25 @@ class C { }
                 );
         }
 
+        [Fact, WorkItem(40136, "https://github.com/dotnet/roslyn/issues/40136")]
+        public void SelfReferencingAttribute()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >SelfReferencingAttribute [](start = 20, length = 24)

Consider also testing scenarios when the attribute is applied to return type and parameters. Also when an attribute is applied to a member of the attribute (Field/Property/setter) initialized by the application.

**Comment by jaredpar** [comment]
Integration test are hanging. Looks like the machine allocation problem in AzDO. Given the debug integration tests are passing, the unlikely hood that this would even affect the integration tests (if it hit there would be a stack overflow) and the need to get this in for servicing I'm forcing the merge here.
