### PR TITLE
Fix overload resolution to handle binary compat in the face of covariant returns

### LINKED ISSUE #45798: Issue with inserting overrides into the hierarchy with covariant returns in retargeting scenarios
The test `BinaryCompatibility_01` in the `features/covariant-returns` branch illustrates an open issue in a retargeting scenario when an override is inserted into the hierarchy.  When there are three assemblies containing

```csharp
// assembly 1
public class Base
{
    public virtual object M() => null;
}
```

```csharp
// assembly 2
public class Mid : Base
{
}
```

```csharp
// assembly 3
public class Derived : Mid
{
    public override string M() => null;
}
```

And the following alternative version of assembly 2

```csharp
// alternative assembly 2
public class Mid : Base
{
    public override string M() => null;
}
```

And the following program is compiled in a retargeting scenario (i.e. with a different corlib) against the assemblies 1, 2 (alternate version), and 3 (which was compiled against 1 and the original 2)

```csharp
public class Program
{
    void M(Base b, Mid m, Derived d)
    {
        object x1 = b.M();
        string x2 = m.M();
        string x3 = d.M();
    }
}
```

It results in the following diagnostic:

```none
                // (8,23): error CS0121: The call is ambiguous between the following methods or properties: 'Base.M()' and 'Base.M()'
                //         string x3 = d.M();
```

It is possible that this arises because the compiler sees the methods `Mid.M` and `Derived.M` as being unrelated (neither overrides the other because they both directly override Base.M), and so both are candidates. The fact that they ultimately override the same method is not noted by the language or compiler.

It is also possible this is a symptom of or related to https://github.com/dotnet/roslyn/issues/45566.

It is not clear why this affects the retargeting view and not the metadata view.

We have a number of choices, assuming this is the problem described:
1. We could adjust the way we find overridden members in retargeting scenarios (i.e. not just follow the methodimpl).
2. We could adjust the binder code that gathers overload candidates to treat two methods that ultimately override the same method as related according to the inheritance relationship of their enclosing types (if any).
3. We could declare this scenario to be rare enough not to worry about.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #45798

### CODE REVIEW

File: src/Compilers/CSharp/Test/Emit/Emit/CovariantReturnTests.cs [hunk 1]
```diff
@@ -304,7 +313,74 @@ static void Main()
...
+        Mid m = d;
+        Base b = m;
+        Console.WriteLine(b.M().ToString());
+        Console.WriteLine(m.M().ToString());
+        Console.WriteLine(d.M().ToString());
+    }
+}
+";
+            var compilation = CreateCovariantCompilation(program, options: TestOptions.DebugExe, references: new[] { ref0, ref1b, ref2 });
+            // compilation.VerifyDiagnostics();
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/Emit/CovariantReturnTests.cs:378]: is comment intentional?

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs [hunk 2]
```diff
@@ -921,45 +921,55 @@ public static bool IsValidParams(Symbol member)
...
+            if (!baseType.IsClassType())
+            {
+                return false;
+            }
 
-                // Don't search beyond the overridden member.
-                if (TypeSymbol.Equals(current.ContainingType, overridden.ContainingType, TypeCompareKind.ConsiderEverything2))
+            for (TypeSymbol b = derivedType.BaseTypeNoUseSiteDiagnostics; (object)b != null; b = b.BaseTypeNoUseSiteDiagnostics)
+            {
+                if (b.Equals(baseType, TypeCompareKind.ConsiderEverything))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:959]: >ConsiderEverything [](start = 55, length = 18)

Why ```ConsiderEverything```?

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs [hunk 3]
```diff
@@ -921,45 +921,55 @@ public static bool IsValidParams(Symbol member)
...
+            return moreDerivedOverride.GetLeastOverriddenMember(accessingTypeOpt: null).OriginalDefinition ==
+                   member.GetLeastOverriddenMember(accessingTypeOpt: null).OriginalDefinition;
+        }
 
-                // We could be in error recovery.
-                if ((object)current == null)
-                {
-                    return false;
-                }
+        private static bool IsBaseClass(TypeSymbol derivedType, TypeSymbol baseType)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:946]: >IsBaseClass [](start = 28, length = 11)

It looks like this is a dupe of ```TypeSymbol.IsDerivedFrom``` method.

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs [hunk 4]
```diff
@@ -921,45 +921,55 @@ public static bool IsValidParams(Symbol member)
...
-                }
+            // A base class has got to be a class. The derived type might be a struct, enum, or delegate.
+            if (!baseType.IsClassType())
+            {
+                return false;
+            }
 
-                // Don't search beyond the overridden member.
-                if (TypeSymbol.Equals(current.ContainingType, overridden.ContainingType, TypeCompareKind.ConsiderEverything2))
+            for (TypeSymbol b = derivedType.BaseTypeNoUseSiteDiagnostics; (object)b != null; b = b.BaseTypeNoUseSiteDiagnostics)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:957]: >BaseTypeNoUseSiteDiagnostics [](start = 44, length = 28)

It is not clear why are we ignoring use-site diagnostics. It looks like problems in inheritance chain can affect the result. In cases like this we collect use-site diagnostics.

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs [hunk 5]
```diff
@@ -921,45 +921,55 @@ public static bool IsValidParams(Symbol member)
...
-                if (!current.IsOverride)
-                {
-                    return false;
-                }
-                current = current.GetOverriddenMember();
+            // Rather than following the member.GetOverriddenMember() chain, we check to see if both
+            // methods ultimately override the same original method.  This addresses issues in binary compat
+            // scenarios where the override chain may skip some steps.
+            // See https://github.com/dotnet/roslyn/issues/45798 for an example.
+            return moreDerivedOverride.GetLeastOverriddenMember(accessingTypeOpt: null).OriginalDefinition ==
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:942]: >OriginalDefinition [](start = 88, length = 18)

Comparing original definitions feels fragile. Methods in generic types that are constructed with different type arguments cannot override the same method, even when the overridden methods correspond to the same original definition.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOperators.cs [hunk 6]
```diff
@@ -5252,7 +5252,8 @@ public void EmitSequenceOfBinaryExpressions_03()
             const int step = 4096;
             const int limit = start * 4;
 
-            for (int count = start; count <= limit && diagnostics.IsEmpty; count += step)
+            int count;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOperators.cs:5255]: >int count; [](start = 12, length = 10)

It is not clear what motivated this change, it looks like it didn't change behavior of the method.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOperators.cs [hunk 7]
```diff
@@ -5389,7 +5390,7 @@ public static double Calculate(double[] f)
 5180801");
         }
 
-        [ConditionalFact(typeof(ClrOnly), typeof(NoIOperationValidation), Reason = "https://github.com/dotnet/roslyn/issues/29428")]
+        [ConditionalFact(typeof(ClrOnly), typeof(NoIOperationValidation), Reason = "https://github.com/dotnet/roslyn/issues/29428", AlwaysSkip = "https://github.com/dotnet/roslyn/issues/46361")]
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOperators.cs:5393]: >https://github.com/dotnet/roslyn/issues/46361 [](start = 146, length = 45)

Do other branches experience the same issue? Otherwise, we should treat this failure as possibly related to the changes around covariant returns (perhaps even in this PR), i.e. compiler is possibly consuming more stack than before, which brings this test close to the failure point.

File: src/Test/Utilities/Portable/Assert/ConditionalFactAttribute.cs [hunk 8]
```diff
@@ -166,6 +166,7 @@ public static class ExecutionConditionUtil
         public static bool IsCoreClr => !IsDesktop;
         public static bool IsCoreClrUnix => IsCoreClr && IsUnix;
         public static bool IsMonoOrCoreClr => IsMono || IsCoreClr;
+        public static bool RuntimeSupportsCovariantReturnsOfClasses => Type.GetType("System.Runtime.CompilerServices.RuntimeFeature")?.GetField("CovariantReturnsOfClasses") != null;
```
Comment (AlekseyTs) [inline src/Test/Utilities/Portable/Assert/ConditionalFactAttribute.cs:169]: >RuntimeSupportsCovariantReturnsOfClasses [](start = 27, length = 40)

This feels wrong. It shouldn't matter in which runtime a test is executed. A test should be able any Target framework for a compilation and only the actual references should determine whether covariant returns are supported within the compilation.

File: src/Test/Utilities/Portable/Assert/ConditionalFactAttribute.cs [hunk 9]
```diff
@@ -260,16 +261,9 @@ public class WindowsDesktopOnly : ExecutionCondition
...
     {
-        public override bool ShouldSkip
-        {
-            get
-            {
-                // See if the runtime supports covariant returns.
-                return Type.GetType("System.Runtime.CompilerServices.RuntimeFeature")?.GetField("CovariantReturnsOfClasses") == null;
-            }
-        }
+        public override bool ShouldSkip => !ExecutionConditionUtil.RuntimeSupportsCovariantReturnsOfClasses;
```
Comment (AlekseyTs) [inline src/Test/Utilities/Portable/Assert/ConditionalFactAttribute.cs:266]: >ShouldSkip [](start = 29, length = 10)

Same comment.

File: src/Compilers/CSharp/Test/Emit/Emit/CovariantReturnTests.cs [hunk 10]
```diff
@@ -235,10 +243,11 @@ public sealed class PreserveBaseOverridesAttribute : Attribute { }
                 source,
                 options: options,
                 parseOptions: TestOptions.WithCovariantReturns,
-                references: references);
+                references: references,
+                assemblyName: assemblyName);
         }
 
-        [ConditionalFact(typeof(CovarantReturnRuntimeOnly))]
+        [ConditionalFact(typeof(CovariantReturnRuntimeOnly))]
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/Emit/CovariantReturnTests.cs:250]: >[ConditionalFact(typeof(CovariantReturnRuntimeOnly))] [](start = 8, length = 53)

It is quite possible I am missing the motivation for conditionally disabling the tests. If it is just to avoid the failure because we are unable to execute the code in proc on some platforms, Default Interface Implementation tests solve this problem by conditionally passing null as ```expectedOutput``` to ```CompileAndVerify```. This way we get as much verification as possible on each platform.

File: src/Compilers/CSharp/Test/Emit/Emit/CovariantReturnTests.cs [hunk 11]
```diff
@@ -304,7 +313,74 @@ static void Main()
             var expectedOutput = @"";
             CompileAndVerify(compilation, expectedOutput: expectedOutput, verify: Verification.Skipped);
         }
-    }
+
+        [ConditionalFact(typeof(CovariantReturnRuntimeOnly))]
+        public void CheckPreserveBaseOverride_01()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/Emit/CovariantReturnTests.cs:318]: >CheckPreserveBaseOverride_01 [](start = 20, length = 28)

Would it make sense to have similar test with compilation references instead of image references?

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 2)

File: src/Compilers/CSharp/Test/Emit/Emit/CovariantReturnTests.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/Emit/CovariantReturnTests.cs:378]: No.

---
In reply to: [461750001](https://github.com/dotnet/roslyn/pull/46367#discussion_r461750001) [](ancestors = 461750001)

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 2 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:959]: Because methods in a method group are gathered from the inheritance hierarchy of the receiver, and therefore the receiver types must be related by precise inheritance.

---
In reply to: [461758371](https://github.com/dotnet/roslyn/pull/46367#discussion_r461758371) [](ancestors = 461758371)

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 4 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:957]: We have always ignored use site diagnostics when determining if one method is a more specific override than another in overload resolution. This is not a change from existing compiler behavior.

---
In reply to: [461764045](https://github.com/dotnet/roslyn/pull/46367#discussion_r461764045) [](ancestors = 461764045)

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 3 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:946]: It is similar. It is closer to ConversionBase.IsBaseClass.

---
In reply to: [461762763](https://github.com/dotnet/roslyn/pull/46367#discussion_r461762763) [](ancestors = 461762763)

File: src/Compilers/CSharp/Test/Emit/Emit/CovariantReturnTests.cs (hunk 11 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/Emit/CovariantReturnTests.cs:318]: The compile-time behavior is already tested in the symbol tests. If you think it would be useful I can parameterize this test by the kind of emit used.

---
In reply to: [461799460](https://github.com/dotnet/roslyn/pull/46367#discussion_r461799460) [](ancestors = 461799460)

File: src/Compilers/CSharp/Test/Emit/Emit/CovariantReturnTests.cs (hunk 10 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/Emit/CovariantReturnTests.cs:250]: Doing so here would simply duplicate tests already in the symbol tests.

---
In reply to: [461782992](https://github.com/dotnet/roslyn/pull/46367#discussion_r461782992) [](ancestors = 461782992)

File: src/Test/Utilities/Portable/Assert/ConditionalFactAttribute.cs (hunk 8 above)
Comment (gafter) [reply src/Test/Utilities/Portable/Assert/ConditionalFactAttribute.cs:169]: These are testing runtime conditions. Running covariant tests does depend on having a runtime that supports them.

---
In reply to: [461778705](https://github.com/dotnet/roslyn/pull/46367#discussion_r461778705) [](ancestors = 461778705)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOperators.cs (hunk 7 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOperators.cs:5393]: Yes, this test is flaky on other branches.  It doesn't run the test on a fresh thread.

---
In reply to: [461776977](https://github.com/dotnet/roslyn/pull/46367#discussion_r461776977) [](ancestors = 461776977)

File: src/Test/Utilities/Portable/Assert/ConditionalFactAttribute.cs (hunk 9 above)
Comment (gafter) [reply src/Test/Utilities/Portable/Assert/ConditionalFactAttribute.cs:266]: This is for conditioning tests that should only be run on runtimes that can handle covariant returns because their point is to verify the runtime behavior of the compiler-generated code.

---
In reply to: [461779636](https://github.com/dotnet/roslyn/pull/46367#discussion_r461779636) [](ancestors = 461779636)

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 5 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:942]: We've already verified that the methods' containing types are in a precise inheritance relationship.

---
In reply to: [461770335](https://github.com/dotnet/roslyn/pull/46367#discussion_r461770335) [](ancestors = 461770335)

**Comment by gafter** [comment]
@jcouv @AlekseyTs I have responded to your comments. Do you have any others?

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:959]: > Because methods in a method group are gathered from the inheritance hierarchy of the receiver, and therefore the receiver types must be related by precise inheritance.

This component is not responsible to gather candidates and doesn't control how it is done. I think we should not make any assumptions about what could be in the set. I think that Either we should come up with a test demonstrating that usage of ```ConsiderEverything``` is significant for correctness, otherwise we should ignore all options, which will be more robust approach in the log run. 

---
In reply to: [461827656](https://github.com/dotnet/roslyn/pull/46367#discussion_r461827656) [](ancestors = 461827656,461758371)

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 5 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:942]: > We've already verified that the methods' containing types are in a precise inheritance relationship.

Where and how, is that the other place I made a comment about the TypeCompareKind used?

---
In reply to: [461838954](https://github.com/dotnet/roslyn/pull/46367#discussion_r461838954) [](ancestors = 461838954,461770335)

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 4 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:957]: > We have always ignored use site diagnostics when determining if one method is a more specific override than another in overload resolution.

If that is the case, please point to the specific place in this component where use-site diagnostics is ignored when we traverse bases. 

> Use-site diagnostics would have been reported when gathering the candidates from the hierarchy of the receiver.

This component is not responsible to gather candidates and doesn't control how it is done. It can be called with any set of candidates as we more and more often build the set of candidates without relying on regular name binding from syntax.

---
In reply to: [461828701](https://github.com/dotnet/roslyn/pull/46367#discussion_r461828701) [](ancestors = 461828701,461764045)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:957]: Note, that we have a Used Assembly References feature in the pipe line that depends on us always collecting use-site diagnostics every time there is a slightest chance that presence of the errors affects the analysis result in any way. We are quite tolerant to duplicate use-site errors reporting, but not as tolerant to missing recording an assembly "usage". I think it would be more robust long term if we simply collect the diagnostics here without trying to be too smart. 

---
In reply to: [461940796](https://github.com/dotnet/roslyn/pull/46367#discussion_r461940796) [](ancestors = 461940796,461828701,461764045)

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 3 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:946]: > It is similar. It is closer to ConversionBase.IsBaseClass.

It is quite possible I am missing something, but based on a quick glance at the code in both methods, I see no meaningful difference. Please, point me to a unit-test that would demonstrate an observable difference between using this method and using ```TypeSymbol.IsDerivedFrom```  method in ```IsMoreDerivedOverride```, or add a test like that. Otherwise, I believe there is no benefit in cloning existing helpers and duplicating code in the product, and we should simply switch to using ```TypeSymbol.IsDerivedFrom```.

---
In reply to: [461831483](https://github.com/dotnet/roslyn/pull/46367#discussion_r461831483) [](ancestors = 461831483,461762763)

File: src/Compilers/CSharp/Test/Emit/Emit/CovariantReturnTests.cs (hunk 11 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit/Emit/CovariantReturnTests.cs:318]: >The runtime cannot run against compilation references.

Could you elaborate please? I am certain we can execute an verify output for a compilation which is utilizing compilation references.

---
In reply to: [461833574](https://github.com/dotnet/roslyn/pull/46367#discussion_r461833574) [](ancestors = 461833574,461799460)

File: src/Test/Utilities/Portable/Assert/ConditionalFactAttribute.cs (hunk 8 above)
Comment (AlekseyTs) [reply src/Test/Utilities/Portable/Assert/ConditionalFactAttribute.cs:169]: > Running covariant tests does depend on having a runtime that supports them.

Executing test compiled code that utilizes covariant return feature - yes. Everything else, shape of symbols, result of emit, diagnostics, etc. doesn't depend

---
In reply to: [461836199](https://github.com/dotnet/roslyn/pull/46367#discussion_r461836199) [](ancestors = 461836199,461778705)

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 3)

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 5 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:942]: In general, I do not believe taking shortcuts like that buy us anything, they do not simplify code, do not make it easer to understand and maintain. I believe that it would be more robust if we don't take them without a real benefit that can be demonstrated/measured.

---
In reply to: [461938985](https://github.com/dotnet/roslyn/pull/46367#discussion_r461938985) [](ancestors = 461938985,461838954,461770335)

File: src/Compilers/CSharp/Test/Emit/Emit/CovariantReturnTests.cs (hunk 11 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/Emit/CovariantReturnTests.cs:318]: The runtime requires actual MSIL bytecodes to execute.  In any case, the compile-time behavior for these scenarios are tested elsewhere.

---
In reply to: [461945536](https://github.com/dotnet/roslyn/pull/46367#discussion_r461945536) [](ancestors = 461945536,461833574,461799460)

File: src/Test/Utilities/Portable/Assert/ConditionalFactAttribute.cs (hunk 8 above)
Comment (gafter) [reply src/Test/Utilities/Portable/Assert/ConditionalFactAttribute.cs:169]: Right, which is why tests that are designed to test other things are not conditional.

---
In reply to: [461946462](https://github.com/dotnet/roslyn/pull/46367#discussion_r461946462) [](ancestors = 461946462,461836199,461778705)

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 5 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:942]: > Where and how, is that the other place I made a comment about the TypeCompareKind used?

The where is on line 931.  This preserves the behavior of this code for existing scenarios not involving covariant returns.  I do not intend to modify or relax the behavior of this code for existing scenarios, so this code is as intended.

---
In reply to: [461948173](https://github.com/dotnet/roslyn/pull/46367#discussion_r461948173) [](ancestors = 461948173,461938985,461838954,461770335)

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 4 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:957]: Those use site diagnostics have been reported when the candidates were collected.  I understand that you would prefer that overload resolution now be enhanced to be able to return use site diagnostics when computing the relationship between methods in the method group.  It did not do so before when traversing the inheritance hierarchy (when computing a method's overridden method) and I am not willing to do that in the context of this PR.  Please open a separate PR for that suggested work item.

---
In reply to: [461942977](https://github.com/dotnet/roslyn/pull/46367#discussion_r461942977) [](ancestors = 461942977,461940796,461828701,461764045)

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 2 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:959]: This code isn't making an assumption.  It is checking it.  This parallels the existing behavior of overload resolution (see line 949 of the old code - an exact check).  If you don't understand how this is modeling the language specification please let me know and I will explain in detail.

---
In reply to: [461938115](https://github.com/dotnet/roslyn/pull/46367#discussion_r461938115) [](ancestors = 461938115,461827656,461758371)

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 3 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:946]: This code is specialized to avoid gathering use site diagnostics and to perform an exact type check. If you don't mind the extra work of computing and discarding use-site diagnostics I will reuse that.

---
In reply to: [461944824](https://github.com/dotnet/roslyn/pull/46367#discussion_r461944824) [](ancestors = 461944824,461831483,461762763)

**Comment by gafter** [comment]
@jcouv @AlekseyTs I have responded to your comments. Do you have any others?

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 4 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs]: > If that is the case, please point to the specific place in this component where use-site diagnostics is ignored when we traverse bases. 

Original version of this code, line 941, (use-site diagnostics arising when traversing bases in order to compute the overridden member are discarded).

---
In reply to: [461940796](https://github.com/dotnet/roslyn/pull/46367#discussion_r461940796) [](ancestors = 461940796,461828701,461764045)

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs [hunk 12]
```diff
@@ -751,7 +751,7 @@ private bool FailsConstraintChecks(MethodSymbol method, out ArrayBuilder<TypePar
             }
             else if (containingTypeMapOpt == null)
             {
-                if (MemberGroupContainsOverride(members, member))
+                if (MemberGroupContainsMoreDerivedOverride(members, member, checkOverrideContainingType: true, ref useSiteDiagnostics))
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs:754]: Notes to self from chat with Neal:

The spec says that when collecting candidates for a method group, we should only keep the definition (and discard the overrides). But for practical reasons, the compiler instead keeps the most derived override instead (and we fix it up when emitting).

Previously, when comparing two candidates, we would see if one overrides the other (by looking up the overridden member chain). If they do, we keep the more derived one. But that doesn't work well in multi-assembly scenarios with particular build sequences (two overrides may not belong to the same chain).

Now, when comparing two candidates, we look all the way up their overridden member chains to find the definition, and if the definitions match, then we keep the more derived one (by looking at containing types).
