### PR TITLE
Run ref safety analysis for field initializers on bound nodes transformed to assignments to the target fields.

### LINKED ISSUE #67371: Ref-assigning a ref parameter to a ref field with primary constructor
**Version Used**: 

Visual Studio 17.6 Preview 2
C# Tools   4.6.0-2.23151.17+1314d090671dc1a1500c5303c4b5ae9150f40d98

**Steps to Reproduce**:

```cs
ref struct Ok
{
    public ref int Ref;

    public Ok(ref int x)
    {
        Ref = ref x; // OK
    }
}

ref struct Error(ref int x)
{
    public ref int Ref = ref x; // CS9077. Isn't this a bug?
}

ref struct ForReference([UnscopedRef] ref int x)
{
    public ref int Ref = ref x; // OK

    public void M1(ref int x)
    {
        Ref = ref x; // CS9077. This is correct.
    }

    public void M2([UnscopedRef] ref int x)
    {
        Ref = ref x; // OK
    }
}
```

**Expected Behavior**:

No error on `public ref int Ref = ref x;`, for consistency with `Ok` struct.

**Actual Behavior**:

CS9077 error.

See also #68610

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #67371.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@cston, @RikkiGibson, @jjonescz, @dotnet/roslyn-compiler Please review.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs [hunk 1]
```diff
@@ -17742,5 +17742,44 @@ void M()
...
+        R2 = ref x;
+    }
+}
+
+ref struct S3(ref int x)
+{
+    public ref int R3 = ref x;
+}
+
+ref struct S4([System.Diagnostics.CodeAnalysis.UnscopedRef] ref int x)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs:17776]: Should we also have a test for a `scoped ref` primary constructor parameter which is ref-assigned to ref field in a constructor and in a field initializer?

**Review by RikkiGibson — APPROVED** [review]

File: src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs [hunk 2]
```diff
@@ -17742,5 +17742,44 @@ void M()
...
+{
+    public ref int R4 = ref x;
+}
+";
+            var comp = CreateCompilation(source, options: TestOptions.ReleaseDll, targetFramework: TargetFramework.NetCoreApp);
+            comp.VerifyDiagnostics();
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs:17783]: >} [](http://example.com/codeflow?start=8&length=1)

Consider adding `ref readonly` cases as well.
```csharp
ref struct S5(in int x)
{
    ref readonly int R5 = ref x;
}
```

**Review by cston — APPROVED** [review]
