### PR TITLE
Fixed Incorrect IDE0004 (Cast is redundant) when negating enum value

### LINKED ISSUE #18510: Incorrect IDE0004 (Cast is redundant) when negating enum value
**Version Used**: Visual Studio 2017 (15.1 - 26403.0)

**Steps to Reproduce**:

```csharp
enum Sign
{
    Positive = 1,
    Negative = -1
}

class T
{
    void Foo()
    {
        Sign mySign = Sign.Positive;
        Sign invertedSign = (Sign)(-(int)mySign);
    }
}
```

**Expected Behavior**:

IDE0004 is not reported for the `(int)` cast in `(int)mySign`.

**Actual Behavior**:

IDE0004 is reported for the `(int)` cast in `(int)mySign`. Removing the cast results in the following compilation error:

> CS0023: Operator '-' cannot be applied to operand of type 'Sign'

**Reference**:

This appears related to, but not quite a duplicate of #11008.

This was originally reported here:
https://developercommunity.visualstudio.com/content/problem/39596/intellisense-suggests-invalid-cast.html

### PR DESCRIPTION
**Pull request by zaytsev-victor**
**Customer scenario**
Incorrect IDE0004 (Cast is redundant) when negating enum value

**Bugs this fixes:**

Fixes #18510

**Workarounds, if any**
None

**Risk**
Low

**Performance impact**

**Is this a regression from a previous update?**
Also repro in VS2015

**Root cause analysis:**
Not implemented check for negating enum value in CSharpRemoveUnnecessaryCastDiagnosticAnalyzer

**How was the bug found?**
customer reported

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/Diagnostics/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.cs [hunk 1]
```diff
@@ -3969,5 +3969,42 @@ private static void TakesParams(params object[] foo)
     }
 }");
         }
+
+        [WorkItem(18510, "https://github.com/dotnet/roslyn/issues/18510")]
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsRemoveUnnecessaryCast)]
+        public async Task DontRemoveCastOnNegatingEnumValue()
+        {
+            await TestInRegularAndScriptAsync(
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/Diagnostics/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.cs]: :bulb: I believe the call you want to make is `TestMissingInRegularAndScriptAsync` (meaning no diagnostic is reported).

File: src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs [hunk 2]
```diff
@@ -312,6 +312,14 @@ public static bool IsUnnecessaryCast(this CastExpressionSyntax cast, SemanticMod
             var expressionTypeInfo = semanticModel.GetTypeInfo(cast.Expression, cancellationToken);
             var expressionType = expressionTypeInfo.Type;
 
+            if (expressionType != null &&
+                expressionType.IsEnumType() 
+                && cast?.Parent is PrefixUnaryExpressionSyntax prefixUnaryExpression 
+                && prefixUnaryExpression.Kind() == SyntaxKind.UnaryMinusE xpression)
```
Comment (sharwell) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: :bulb: The type check is slow, but `IsKind()` is fast. Also, we know from code above that `cast` cannot be null, and the `IsKind` extension method handles null internally (so `cast.Parent` is covered). You can just use this for the parent check:

```
cast.Parent.IsKind(SyntaxKind.UnaryMinusExpression)
```

File: src/EditorFeatures/CSharpTest/Diagnostics/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.cs [hunk 3]
```diff
@@ -3969,5 +3969,42 @@ private static void TakesParams(params object[] foo)
...
+        Positive = 1,
+        Negative = -1
+    }
+
+    class T
+    {
+        void Foo()
+        {
+            Sign mySign = Sign.Positive;
+            Sign invertedSign = (Sign) ( |-(int) mySign| );
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Diagnostics/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.cs]: You need to use [|  and |]   not    |   and   |

File: src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs (hunk 2 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: is it only ```-``` that has this issue?  are other operators (like ```+``` and ```~```) ok?

Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: if you only care about ```-``` then just do ```cast.IsParentKind(SyntaxKind.UnaryMinusExpression)```

File: src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs [hunk 4]
```diff
@@ -312,10 +312,9 @@ public static bool IsUnnecessaryCast(this CastExpressionSyntax cast, SemanticMod
             var expressionTypeInfo = semanticModel.GetTypeInfo(cast.Expression, cancellationToken);
             var expressionType = expressionTypeInfo.Type;
 
-            if (expressionType != null &&
-                expressionType.IsEnumType() 
-                && cast?.Parent is PrefixUnaryExpressionSyntax prefixUnaryExpression 
-                && prefixUnaryExpression.Kind() == SyntaxKind.UnaryMinusE xpression)
+            if (expressionType != null 
+                && expressionType.IsEnumType() 
+                && (cast.IsParentKind(SyntaxKind.UnaryMinusExpression) || cast.IsParentKind(SyntaxKind.UnaryPlusExpression)))
```
Comment (sharwell) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: What about `-((int)mySign)`?

Comment (zaytsev-victor) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: Good catch, thanks.

File: src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs [hunk 5]
```diff
@@ -314,7 +314,7 @@ public static bool IsUnnecessaryCast(this CastExpressionSyntax cast, SemanticMod
 
             if (expressionType != null 
                 && expressionType.IsEnumType() 
-                && (cast.IsParentKind(SyntaxKind.UnaryMinusExpression) || cast.IsParentKind(SyntaxKind.UnaryPlusExpression)))
+                && (cast.WalkUpParentheses().IsParentKind(SyntaxKind.UnaryMinusExpression) || cast.WalkUpParentheses().IsParentKind(SyntaxKind.UnaryPlusExpression)))
```
Comment (sharwell) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: :bulb: There is an overload of `IsParentKind` which accepts two `SyntaxKind` arguments. Using this will allow you to call `WalkUpParentheses` one time instead of two.

:bulb: Maybe extract this block into a method `EnumCastDefinitelyCantBeRemoved`, similar to the existing `PointerCastDefinitelyCantBeRemoved` method?

**Comment by sharwell** [comment]
@zaytsev-victor Your code looks good to me now. I'm just waiting on the build to complete and @CyrusNajmabadi to take a second look before we merge it.

I wanted to talk a little bit about your root cause analysis. The interesting thing to me is I don't currently understand why the [semantic safeguard](https://github.com/zaytsev-victor/roslyn/blob/3ad7a1846872162ac74205dd88f62b6f5e272674/src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs#L364) failed to catch this. Normally when we encode special semantics in a diagnostic analyzer (like you did here with `EnumCastDefinitelyCantBeRemoved`), the goal is to improve performance by avoiding unnecessary calls to `ReplacementChangesSemantics`. Examples of this can be seen in #19258, #19895, and #20199, but you'll notice in each of those cases the previous fix was correct but slow.

:bulb: It would be good to file a separate bug to correct `ReplacementChangesSemantics` to correctly identify the elimination of this cast as a semantics-changing operation. This will help ensure that future diagnostics that happen to eliminate casts do not encounter the incorrect behavior we were fixing here.

**Comment by zaytsev-victor** [comment]
I've investigated why semantic safeguard failed in this case. Method ReplacementIntroducesErrorType (in AbstractSpeculationAnalyzer class) has the following code:

 `
var originalTypeInfo = this.OriginalSemanticModel.GetTypeInfo(originalExpression);
newTypeInfo = this.SpeculativeSemanticModel.GetTypeInfo(newExpression);
`

I've added the following code that resolves the issue
`
if (originalTypeInfo.Type != newTypeInfo.Type)
{
    return true;
 }
`
but I am not so familiar with Roslyn code base to be ensure that this code will not break something (it also fixes issue #20617, I didn't test other issues with "Incorrect IDE0004)

**Comment by sharwell** [comment]
@zaytsev-victor Nice find! If you create a new pull request with just the change for the semantic check, the team that knows more about that can help verify that.

**Comment by sharwell** [comment]
I filed #20698 to address the root cause (and hopefully clean up other outstanding bugs).

File: src/EditorFeatures/CSharpTest/Diagnostics/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.cs [hunk 6]
```diff
@@ -3969,5 +3969,93 @@ private static void TakesParams(params object[] foo)
     }
 }");
         }
+
+        [WorkItem(18510, "https://github.com/dotnet/roslyn/issues/18510")]
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsRemoveUnnecessaryCast)]
+        public async Task DontRemoveCastOnNegatingEnumValue1()
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/Diagnostics/RemoveUnnecessaryCast/RemoveUnnecessaryCastTests.cs]: :bulb: You can use `[Theory]` instead of `[Fact]` here to eliminate some redundancy:

Start by adding a parameter for the operator:

```csharp
public async Task DontRemoveCastOnUnaryOperatorEnumValue(string op)
```

Then replace `Fact` with `Theory` and provide the values for the parameter with `InlineData`:

```csharp
[Theory]
[InlineData("-")]
[InlineData("+")]
[InlineData("~")]
```

Then use `op` with an interpolated string:

```csharp
            await TestMissingInRegularAndScriptAsync(
$@"
enum Sign
    {{
        Positive = 1,
        Negative = -1
    }}

    class T
    {{
        void Foo()
        {{
            Sign mySign = Sign.Positive;
            Sign invertedSign = (Sign) ( [|{op}(int) mySign|] );
        }}
    }}");
```

:memo: If you do this, you would need two tests to cover all 6 cases (3 operators, with and without parentheses).

**Comment by zaytsev-victor** [comment]
@sharwell as far as I know it is valid syntax ```Sign invertedSign = ~mySign;```, isn't it?

**Comment by sharwell** [comment]
@zaytsev-victor 👍 Should still get a test in there because even people who are around the language all the time can get mixed up 😆

File: src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs [hunk 7]
```diff
@@ -213,6 +213,18 @@ private static bool PointerCastDefinitelyCantBeRemoved(CastExpressionSyntax cast
             return false;
         }
 
+        private static bool EnumCastDefinitelyCantBeRemoved(CastExpressionSyntax cast, ITypeSymbol expressionType)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: In the future, please don't abbr.  i.e. use Cannot or CanNot.

Comment (sharwell) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: :memo: This name was picked to be consistent with a name for a similar method above it.
