### PR TITLE
make us to accept project level build errors as well.

### LINKED ISSUE #11350: Duplicate project diagnostics from build/intellisense in the error list
**Version Used**: 1.2.1

**Steps to Reproduce**:

1. Create a C# class library project
2. Delete the AssemblyInfo.cs file from the project
3. Add NuGet package reference to Microsoft.CodeAnalysis.FxCopAnalyzers (1.2.0-beta1)
4. Edit the C# project file to enable IOperation analyzers by adding the following property: `<Features>IOperation</Features>`
5. Build and wait for intellisense and build diagnostics from the project - filter error list to show only CA1016 issues.

**Expected Behavior**:
No duplicate CA1016 (Mark assemblies with assembly version)

**Actual Behavior**:
I see duplicate diagnostics from build and intellisense:
```
Severity	Code	Description	Project	File	Line	Source	Tool	Suppression State
Warning	CA1016	Mark assemblies with assembly version	ClassLibrary1		1	IntelliSense	Microsoft.ApiDesignGuidelines.Analyzers	Active
Warning		Mark assemblies with assembly version	ClassLibrary1	C:\Users\mavasani\Documents\Visual Studio 2015\Projects\ClassLibrary1\ClassLibrary1\CSC		Build		
```

Below is the output window:
```
1>------ Rebuild All started: Project: ClassLibrary1, Configuration: Debug Any CPU ------
1>CSC : warning CA1016: Mark assemblies with assembly version
1>  ClassLibrary1 -> C:\Users\mavasani\Documents\Visual Studio 2015\Projects\ClassLibrary1\ClassLibrary1\bin\Debug\ClassLibrary1.dll
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

```

### PR DESCRIPTION
**Pull request by heejaechang**
previously we rejected those and let project system to deal with it.

with this change, we will accept all diagnostics we can handle and even show code for those errors if possible as well.

fix #11350
fix https://github.com/dotnet/roslyn/issues/11306

### CODE REVIEW

**Comment by heejaechang** [comment]
test vsi please

**Comment by heejaechang** [comment]
@mavasani can you take a look? I will add unit test soon
@dotnet/roslyn-analysis

File: src/VisualStudio/Core/Def/Implementation/TaskList/ProjectExternalErrorReporter.cs [hunk 1]
```diff
@@ -173,6 +158,34 @@ public void ReportError2(string bstrErrorMessage, string bstrErrorId, [ComAliasN
                     throw new ArgumentException(ServicesVSResources.NotAValidValue, nameof(nPriority));
             }
 
+            // We only handle errors that have positions.  For the rest, we punt back to the
```
Comment (mavasani) [inline src/VisualStudio/Core/Def/Implementation/TaskList/ProjectExternalErrorReporter.cs]: Update the comment?

**Comment by mavasani** [comment]
👍 once you add a unit test. Thanks.

**Comment by heejaechang** [comment]
test vsi please

**Comment by heejaechang** [comment]
test vsi please
