### PR TITLE
Fix struct layout error when nullable enabled:

### LINKED ISSUE #32934: #nullable enable causes bogus cycle in struct layout error
**Version Used**: VS2019 Preview 2

**Steps to Reproduce**:

1. Create a new .NET core C# library project
2. Change the C# language version to 8.0
3. Type the following code

```
#nullable enable
struct Foo<T>
{
	static Foo<T> Bar;
}
```

**Expected Behavior**: Code compiles fine whether or not `#nullable enable` is used
**Actual Behavior**: With `#nullable enable` the compiler emits this error:

`Error CS0523: Struct member 'Foo<T>.Bar' of type 'Foo<T>' causes a cycle in the struct layout`

### PR DESCRIPTION
**Pull request by chsienki**
- Change type comparison to ignore nullable
- Add a test
- Fix an existing test

Fixes #32934

### CODE REVIEW

**Comment by chsienki** [comment]
@dotnet/roslyn-compiler for review please

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 1]
```diff
@@ -84789,5 +84786,21 @@ static void MN2()
                 //         node.ToString(); // 8
                 Diagnostic(ErrorCode.WRN_NullReferenceReceiver, "node").WithLocation(118, 9));
         }
+
+        [Fact, WorkItem(32934, "https://github.com/dotnet/roslyn/issues/32934")]
+        public void NoCycleInStructLayout()
+        {
+            var source =
+@"
+#pragma warning disable 0169 // suppress field never used warning
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: nit: you could also eliminate the warning by making the field public
