### PR TITLE
Use ResolveMetadataReferences in DPL

### LINKED ISSUE #14433: With Lightweight Solution Load, a deferred project fails to build for dynamic analysis
With Lightweight Solution Load enabled for a solution that includes a VB class library project and a C# project that refers to the VB project, opening a file in the C# project in a way that triggers dynamic analysis to build the C# project also requires dynamic analysis to build the VB project. The VB project build fails as if the fundamental .Net types (System.Object, System.String, etc.) were not available.

@Pilchie @ManishJayaswal @KevinH-MS might find this to be of interest.

### PR DESCRIPTION
**Pull request by Pilchie**
Because VB implicitly adds a reference to either mscorlib or System.Runtime
we need to do that in CPSProject for CPS-based projects in VB, like
Lightweight solution load.

Fixes #14433 and #14584

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @dotnet/roslyn-ide, @mavasani, @JohnHamby for review and possible testing.

File: src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs [hunk 1]
```diff
@@ -90,6 +90,20 @@ private void PostSetOptions(CommandLineArguments commandLineArguments)
...
+            // We should consider switching to using commandLineArguments.ResolveMetadataReferences()
+            // For now, just use dynamic to add whatever 'mscorlib' or 'System.Runtime', the arguments
+            // would use.
+            if (Language == LanguageNames.VisualBasic)
+            {
+                dynamic dynArgs = commandLineArguments;
+                var coreLibReference = dynArgs.DefaultCoreLibraryReference as CommandLineReference?;
+                if (coreLibReference != null)
+                {
+                    AddMetadataReference(coreLibReference.Value.Reference, coreLibReference.Value.Properties);
```
Comment (Pilchie) [inline src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs]: A concern I have with this is whether it's safe to call multiple times if the options change.  This isn't an issue in DPL, because they never change there, but may be an issue for CPS?

Comment (mavasani) [inline src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs]: Can this cause duplicate corlib reference is user also provides an explicit corlib reference in project? Any reason not to call ResolveMetadataReferences here? @alekseyts probably can comment if this is a safe approach.

**Comment by AlekseyTs** [comment]
CC @dotnet/roslyn-compiler  It looks like this change affects compilers and public API.

File: src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs (hunk 1 above)
Comment (Pilchie) [inline src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs]: I tried it before and there was some problem with using `ResolveMetadataReferences()`, but I forget what it is :( 

Regardless, I could do that in the DPL code, but I'm not sure about here - I expect that CPS normally doesn't expect references to be added through this path.

Comment (Pilchie) [inline src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs]: I'll try to investigate what went wrong with ResolveMetadataReferences again later today.

Comment (Pilchie) [inline src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs]: But aren't those conditions the ones where `DefaultCoreLibraryReference` is non-null?

Comment (AlekseyTs) [inline src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs]: > But aren't those conditions the ones where DefaultCoreLibraryReference is non-null?

No. This property doesn't say: "Use it." It says: "If you need it, its there."

Comment (Pilchie) [inline src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs]: Can you point me to the code that does enforce those conditions?

Comment (AlekseyTs) [inline src/VisualStudio/Core/Impl/ProjectSystem/CPS/CPSProject_IWorkspaceProjectContext.cs]: VisualBasicCommandLineArguments.ResolveMetadataReferences

**Comment by Pilchie** [comment]
@mavasani @jasonmalinowski @AlekseyTs can you take another look at this?  I've changed the approach, and limited it to DPL install of all uses of `CPSProject`.

I think my previous concerns were about:
1. Some references being unresolved.
2. The fact that we might be hitting the disk earlier, since we previously would wait until we create a compilation.

But I think those are okay now.

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker_IVsSolutionLoadEvents.cs [hunk 2]
```diff
@@ -318,22 +322,31 @@ private void OutputToOutputWindow(string message)
                 }
             }
 
-            foreach (var reference in commandLineArguments.MetadataReferences)
+            foreach (var reference in commandLineArguments.ResolveMetadataReferences(project.CurrentCompilationOptions.MetadataReferenceResolver))
             {
+                // References that don't exist on disk will come back prepended with "Unresolved: ".  We'll strip that off 
+                // and still add them, so that if they appear, we'll load them (maybe they are outputs of other parts of the build).
+                const string unresolved = "Unresolved: ";
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker_IVsSolutionLoadEvents.cs]: Ignoring morals for a moment, this will break in localized builds.

**Comment by JohnHamby** [comment]
Tagging @ManishJayaswal . This might fix dynamic analysis of VB with DPL. Unfortunately, I will not be able to test this in a timely fashion.

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker_IVsSolutionLoadEvents.cs (hunk 2 above)
Comment (mavasani) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker_IVsSolutionLoadEvents.cs]: Yeah, probably safer to trycast to UnresolvedMetadataReference and access Reference property. If trycast fails, hard cast to PortableExecutableReference and access FilePath?

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker_IVsSolutionLoadEvents.cs [hunk 3]
```diff
@@ -318,22 +322,31 @@ private void OutputToOutputWindow(string message)
                 }
             }
 
-            foreach (var reference in commandLineArguments.MetadataReferences)
+            foreach (var reference in commandLineArguments.ResolveMetadataReferences(project.CurrentCompilationOptions.MetadataReferenceResolver))
```
Comment (mavasani) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker_IVsSolutionLoadEvents.cs]: Can compilation options or the resolver be null?

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker_IVsSolutionLoadEvents.cs (hunk 2 above)
Comment (Pilchie) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker_IVsSolutionLoadEvents.cs]: Good idea, done.

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker_IVsSolutionLoadEvents.cs (hunk 3 above)
Comment (Pilchie) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker_IVsSolutionLoadEvents.cs]: Once we call `projectContext.SetOptions()` on line 269, the compilationOptions will be set, and the metadatareference resolver can't be null.

**Comment by Pilchie** [comment]
@rchande It would be great if you could do some buddy testing of DPL with this branch, and @ManishJayaswal it would be good for someone from your team to verify your scenarios here too.

**Comment by rchande** [comment]
@Pilchie testing now...

**Comment by ManishJayaswal** [comment]
@JohnHamby  is on vacation, @tannergooding can you test this out to see if LUT works with this fix with DPL on?

**Comment by rchande** [comment]
Can you take a look at https://github.com/dotnet/roslyn/issues/14972 before merging?

**Comment by Pilchie** [comment]
o	Customer scenario – Enable DPL and open a solution containing VB projects.
o	Bugs this fixes:  https://github.com/dotnet/roslyn/issues/14584
o	Workarounds, if any – Don't use DPL with VB.
o	Risk – This only affects the DPL codepath.
o	Performance impact Potentially slightly slower to populate the Roslyn workspace in DPL, as we do reference resolution eagerly now.
o	Is this a regression from a previous update? - Now
o	Root cause analysis:  how did we miss it?  What tests are we adding to guard against it in the future? - Test hole around VB in DPL.  Embarassing 😊 
o	How was the bug found?  Partner team testing.

**Comment by rchande** [comment]
Validated this by opening Roslyn.sln and created other projects and verified that VB projects had mscorlib. 👍

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker_IVsSolutionLoadEvents.cs [hunk 4]
```diff
@@ -318,22 +322,30 @@ private void OutputToOutputWindow(string message)
...
             {
+                // Some references may fail to be resolved - if they are, we'll still pass them
+                // through, in case they come into existence later (they may be built by other 
+                // parts of the build system).
+                var unresolvedReference = reference as UnresolvedMetadataReference;
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioProjectTracker_IVsSolutionLoadEvents.cs]: Can these be non-file-path paths that would choke downstream?
