### PR TITLE
CodeModel now completely handles Conversion operator declarations

### LINKED ISSUE #1980: Intermittent crash in VS
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>DefaultDomain</AppDomain><Exception><ExceptionType>System.Runtime.InteropServices.COMException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))</Message><StackTrace>   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.CSharp.CodeModel.CSharpCodeModelService.CreateUnknownCodeElement(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.GetElementsForCodeModelEvent(CodeModelEvent codeModelEvent, CodeElement&amp;amp; element, Object&amp;amp; parentElement)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.FireEvents()
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.CodeModelIncrementalAnalyzerProvider.Analyzer.&amp;lt;&amp;gt;c__DisplayClass6_0.&amp;lt;FireEvents&amp;gt;b__0()
   at Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService.NotifyOnForegroundWorker()
   at Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService.NotifyOnForeground()
   at Roslyn.Utilities.TaskFactoryExtensions.&amp;lt;&amp;gt;c__DisplayClass1_0.&amp;lt;SafeStartNew&amp;gt;b__0()</StackTrace><ExceptionString>System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.CSharp.CodeModel.CSharpCodeModelService.CreateUnknownCodeElement(CodeModelState state, FileCodeModel fileCodeModel, SyntaxNode node)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.GetElementsForCodeModelEvent(CodeModelEvent codeModelEvent, CodeElement&amp;amp; element, Object&amp;amp; parentElement)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.FileCodeModel.FireEvents()
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.CodeModelIncrementalAnalyzerProvider.Analyzer.&amp;lt;&amp;gt;c__DisplayClass6_0.&amp;lt;FireEvents&amp;gt;b__0()
   at Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService.NotifyOnForegroundWorker()
   at Microsoft.CodeAnalysis.Editor.Implementation.ForegroundNotification.ForegroundNotificationService.NotifyOnForeground()
   at Roslyn.Utilities.TaskFactoryExtensions.&amp;lt;&amp;gt;c__DisplayClass1_0.&amp;lt;SafeStartNew&amp;gt;b__0()</ExceptionString></Exception></TraceRecord>

### PR DESCRIPTION
**Pull request by basoundr**
Fix #1980 : CodeModel was not handling Conversion operator declarations
in few areas. This change addresses these issues

### CODE REVIEW

**Comment by basoundr** [comment]
This is a preview bug.

Reviewers: @Pilchie @DustinCampbell @jasonmalinowski @dpoeschl @rchande @balajikris @brettfo

File: src/VisualStudio/Core/Impl/CodeModel/FileCodeModel_Events.cs [hunk 1]
```diff
@@ -136,7 +136,7 @@ private EnvDTE80.vsCMChangeKind ConvertToChangeKind(CodeModelEventType eventType
             return result;
         }
 
-        private void GetElementsForCodeModelEvent(CodeModelEvent codeModelEvent, out EnvDTE.CodeElement element, out object parentElement)
+        internal void GetElementsForCodeModelEvent(CodeModelEvent codeModelEvent, out EnvDTE.CodeElement element, out object parentElement)
```
Comment (dpoeschl) [inline src/VisualStudio/Core/Impl/CodeModel/FileCodeModel_Events.cs]: Were there any other tests that verified this method via some other entry point? If this really needs to be made internal for testing, can you mark it as ```// internal for testing```?

File: src/VisualStudio/Core/Test/CodeModel/CSharp/FileCodeModelTests.vb [hunk 2]
```diff
@@ -919,9 +921,55 @@ class $$C
...
+                    Dim changeDocument = workspace.CurrentSolution.GetDocument(workspace.Documents(0).Id)
+                    Dim changeTree = changeDocument.GetSyntaxTreeAsync().Result
+
+                    Dim codeModelEvent = workspaceAndFileCodeModel.CodeModelService.CollectCodeModelEvents(originalTree, changeTree)
+                    Dim fileCodeModel = workspaceAndFileCodeModel.FileCodeModelObject
+
+                    Dim element As EnvDTE.CodeElement = Nothing
+                    Dim parentElement As Object = Nothing
+                    fileCodeModel.GetElementsForCodeModelEvent(codeModelEvent.First(), element, parentElement)
+                    Assert.NotNull(element)
```
Comment (dpoeschl) [inline src/VisualStudio/Core/Test/CodeModel/CSharp/FileCodeModelTests.vb]: Do we need to make sure this is an "Unknown" element? Or is the non-null-ness sufficient?

File: src/VisualStudio/Core/Test/CodeModel/CSharp/FileCodeModelTests.vb [hunk 3]
```diff
@@ -919,9 +921,55 @@ class $$C
...
+
+            Dim newDefinition =
+<Workspace>
+    <Project Language=<%= LanguageName %> CommonReferences="true">
+        <Document><%= newCode.Value %></Document>
+    </Project>
+</Workspace>
+
+            Using workspaceAndFileCodeModel = CreateCodeModelTestState(GetWorkspaceDefinition(oldCode))
+                Using workspace = TestWorkspaceFactory.CreateWorkspace(newDefinition, exportProvider:=VisualStudioTestExportProvider.ExportProvider)
```
Comment (dpoeschl) [inline src/VisualStudio/Core/Test/CodeModel/CSharp/FileCodeModelTests.vb]: Names are a little confusing. Maybe "originalWorkspaceWithFileCodeModel" and "changedWorkspace" (to keep with the naming scheme used below)?

File: src/VisualStudio/Core/Impl/CodeModel/FileCodeModel_Events.cs (hunk 1 above)
Comment (basoundr) [inline src/VisualStudio/Core/Impl/CodeModel/FileCodeModel_Events.cs]: No other testcase verified this method. This was modified to be internal for the purpose of testing. Will add a comment

File: src/VisualStudio/Core/Test/CodeModel/CSharp/FileCodeModelTests.vb (hunk 2 above)
Comment (basoundr) [inline src/VisualStudio/Core/Test/CodeModel/CSharp/FileCodeModelTests.vb]: Being non-null is sufficient but it is better to do some additional assertions.

File: src/VisualStudio/Core/Test/CodeModel/CSharp/FileCodeModelTests.vb (hunk 3 above)
Comment (basoundr) [inline src/VisualStudio/Core/Test/CodeModel/CSharp/FileCodeModelTests.vb]: Sure.

**Comment by dpoeschl** [comment]
:+1:

**Comment by Pilchie** [comment]
:+1:

Please check into master, but wait for approval to port to preview.

File: src/VisualStudio/Core/Test/CodeModel/CSharp/FileCodeModelTests.vb (hunk 2 above)
Comment (DustinCampbell) [inline src/VisualStudio/Core/Test/CodeModel/CSharp/FileCodeModelTests.vb]: Was there no way to add this test to EventCollectorTests instead of adding a separate specialized test in FileCodeModelTests?

**Comment by basoundr** [comment]
test this please
