### PR TITLE
Refine parsing look-ahead for type arguments

### LINKED ISSUE #21515: Switch case pattern match compile fail for arrays of generic types in VS 15.3
**Version Used**: VS 15.3

**Steps to Reproduce**:

```c#
using System;
using System.Collections.Generic;

namespace ConsoleApp3
{
    class Program
    {
        static void Main()
        {
            Array array = new KeyValuePair<string, DateTime>[3];
            switch (array)
            {
                case KeyValuePair<string, DateTime>[] pairs:
                    Console.WriteLine("Pairs");
                    break;
            }
        }
    }
}
```

**Expected Behavior**:
This is expected to compile as it used to in VS 15.2

**Actual Behavior**:
I get several syntax errors on the `case KeyValuePair<string, DateTime>[] pairs:` line.

I discovered this after the upgrade to VS 15.3 in my `OrderedDictionary`'s implementation of `ICollection.CopyTo` similar to [Dictionary](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/Dictionary.cs#L699)'s but with pattern matching.

### PR DESCRIPTION
**Pull request by gafter**
**Customer scenario**

Switch case such as `case G<X, Y>[] v:` stopped compiling in Update 2.

**Bugs this fixes:**

Fixes #21515

**Workarounds, if any**

None.

**Risk**

Low. The change is small and has effective test coverage.

**Performance impact**

None.

**Is this a regression from a previous update?**

Yes, it is a regression from VS2017.

**Root cause analysis:**

This is a complex area with subtle interactions in the parser. We simply overlooked this case.

**How was the bug found?**

Customer reported.

**Test documentation updated?**

N/A

@dotnet/roslyn-compiler  Please review.
@CyrusNajmabadi Your comments are welcome.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
I have no comments other than: this seems to be an ideal area to just hammer away at with tests.  Basically, from my own personal experience here hte internal impl can be pretty confusing and hard to be certain of correctness.  But, if we have a very healthy test suite here, we can vet that complex impl, and most importantly prevent regressions which are all too easy in this area :)

**Comment by CyrusNajmabadi** [comment]
Perhaps even autogenerated cases might make sense.  Pick the interesting areas ("is patterns", "case labels" expressions, etc.) and generate a bunch of the hairy generic cases.

**Comment by gafter** [comment]
@CyrusNajmabadi While I agree in principle, we have a significant number of tests already in this area, and the parser is not supposed to be as context-independent as would benefit from auto-generation of tests. For example, whether `<B>` is a type argument list in the sequence of tokens `A<B>>C` depends on context. This is a valid (and even common!) expression meaning to compare the value of A to B shifted by C. But on the right-hand-side of an `is`, the syntax `A<B>` is a type (for backward compatibility) even though it would be possible, in principle, to parse `e is A<B>>C` either as `(e is A<B>) > C` or as `(e is A) < (B>>C)`.

We simply *cannot* have the implementation be as complex as we want. This all needs to be specified, and the implementation needs to align precisely with the specification, even if the result is that sometimes people need to use parens due to unfortunate language behavior. What is implemented here is easy to specify (easier than before the change), and seems to handle all the corner cases "correctly".

**Comment by gafter** [comment]
test windows_debug_vs-integration_prtest  please

**Comment by gafter** [comment]
test windows_release_vs-integration_prtest please

**Comment by CyrusNajmabadi** [comment]
> For example, whether <B> is a type argument list in the sequence of tokens A<B>>C depends on context. 

I definitely get that :)

What i meant was:  really put in several hours of effort trying to enumerate all those contexts so that we can have lots of interesting test cases to help us out in the future.  If you feel that we already have enough here, then there's nothing to be done.  The recommendation on using a generator was just to be able to take many of hte interesting cases+contexts and have it spit out a few hundred varieties just to firmly codify the current behavior and help with finding anything that changes as we are certain to do more work here in the future.

--

Importantly, here's what i'm pretty concerned with:  In general when i've had to go into the parser it has been to improve parsing in error cases/incomplete code.  Future devs will dev need to do this as the shape of hte tree during incomplete code has a large impact on how higher layers of the compiler and IDE work.  When i've made these sorts of changes i've definitely valued and depended on a solid test suite catching either actual breaks (i.e. legal code no longer parsing correctly), or at least identifying changes in behavior (i.e. a different tree for incorrect code).  For the latter, i could then go through and validate that I was not making things worse, etc. etc.

Again, if there is substantial coverage here already, then i'm a-ok with everything.  But if you feel like there are opportunities to beef things up here, i think it would be valuable.  

Thanks!

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 1]
```diff
@@ -5128,14 +5128,20 @@ private ScanTypeArgumentListKind ScanTypeArgumentList(NameOptions options)
...
                 case SyntaxKind.GreaterThanEqualsToken:  // e.g. `e is A<B> >= C`
-                case SyntaxKind.GreaterThanToken when this.PeekToken(1).Kind != SyntaxKind.GreaterThanToken: // not >>
-                                                         // e.g. `e is A<B> > C`
                 case SyntaxKind.IsKeyword:               // e.g. `e is A<B> is bool`
                 case SyntaxKind.AsKeyword:               // e.g. `e is A<B> as bool`
-                    // These tokens are added to 7.5.4.2 Grammar Ambiguities in C#7 for a possible type following the `is` keyword
-                    return ((options & NameOptions.AfterIs) != 0)
-                        ? ScanTypeArgumentListKind.DefiniteTypeArgumentList
-                        : ScanTypeArgumentListKind.PossibleTypeArgumentList;
+                    // These tokens are added to 7.5.4.2 Grammar Ambiguities in C#7
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: So the new behavior for `case List<string>[]` is to fall through to the `default` case and turn into a `PossibleTypeArgumentList`? I'm not sure I understand how this fixes the problem.

My thought process is as follows:
    1. The `<>` in `case List<string>[]` is a type argument list.
    2. It appears the previous behavior would return `DefiniteTypeArgumentList`.
    3. Why would `PossibleTypeArgumentList` be better than `DefiniteTYpeArgumentList` in this context. Where does `DefiniteTypeArgumentList` go off the rails?

Comment (gafter) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: This code returns `DefiniteTypeArgumentList` for the `List<string>[]` case, as before. `PossibleTypeArgumentList` is not better in any way, as the bug being fixed here demonstrates.

---
In reply to: [139503034](https://github.com/dotnet/roslyn/pull/22102#discussion_r139503034) [](ancestors = 139503034)

Comment (gafter) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: I think you misunderstand the flow of control here. The new behavior for case `List<string>[]` is to return `DefiniteTypeArgumentList`.

---
In reply to: [140905018](https://github.com/dotnet/roslyn/pull/22102#discussion_r140905018) [](ancestors = 140905018,139503034)

**Comment by gafter** [comment]
test windows_release_vs-integration_prtest please

**Comment by gafter** [comment]
test windows_debug_vs-integration_prtest please

**Comment by gafter** [comment]
@dotnet/roslyn-compiler @agocke Looking for two reviews, please.

**Comment by gafter** [comment]
test windows_release_vs-integration_prtest please

`Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicLineCommit.CommitOnSave` appears to be flaky

**Comment by gafter** [comment]
test windows_release_vs-integration_prtest please

**Comment by gafter** [comment]
`Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpFormatting.PasteCodeWithLambdaBody2` appears to be flaky

**Comment by gafter** [comment]
test windows_release_vs-integration_prtest please

**Comment by gafter** [comment]
@AlekseyTs Could you please review this parsing bug fix related to pattern-matching?

**Comment by gafter** [comment]
@jcouv Please approve for 15.5.

**Comment by jcouv** [comment]
@gafter Approved for 15.5

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs (hunk 1 above)
Comment (agocke) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: AH, I see.
