### PR TITLE
Fix Host Object Access in Interactive

### LINKED ISSUE #39548: C# pattern match crashes VS 2019
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/784408/c-pattern-match-crashes-vs-2019.html)._

---
In VS 2019 16.3.5, or 16.4P2, open C# interactive and type the following:
```
var x = (false, 4);
x is (false, var y)
```
Press enter after `;`
Expected the second expression to evaluate to `true`,
but instead right after typing the last `)` VS hangs then restarts.

---
#### Visual Studio Feedback System on 10/20/2019, 11:01 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/21/2019, 10:11 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Visual Studio Feedback System on 10/21/2019, 10:23 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Robert Larkins on 10/27/2019, 11:04 PM: 

<p>I was able to replicate this on 16.3.6.</p>

---
### Original Solutions
(no solutions)

### LINKED ISSUE #39565: CreateDelegate throws exception on calling function with "out var x" (Regression in Microsoft.CodeAnalysis.CSharp.Scripting 3.3.1))
**Version Used**: 
Issue can be reproduced with .net Core 2.2 or .net Core 3.0 (Not tested on older .net Core versions)
with Microsoft.CodeAnalysis.CSharp.Scripting 3.3.1 (Older versions of this package do work correctly)

**Steps to Reproduce**:
Run the following program:

```C#
using Microsoft.CodeAnalysis.CSharp.Scripting;
using Microsoft.CodeAnalysis.Scripting;
using System;

namespace CSharpScripting
{
    public class HelpResult{ }
    public class ExecutionContext
    {
        public bool TryGetFastHelp(out HelpResult helpResult)
        {
            helpResult = new HelpResult();
            return true;
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            ScriptOptions so = ScriptOptions.Default
                .AddReferences(AppDomain.CurrentDomain.GetAssemblies())
                .AddImports(new string[] {
                    "CSharpScripting"
              });

            string code = @"
            if(TryGetFastHelp(out var result)){
                Console.WriteLine(result);
            }
            return true;
            ";

            var script = CSharpScript.Create<bool>(code, globalsType: typeof(ExecutionContext), options: so);
            var d = script.CreateDelegate();
            d(new ExecutionContext()).Wait();
            Console.ReadLine();
        }
    }
}
```

**Expected Behavior**:
Runs without errors.

**Actual Behavior**:
Throws exception on line `var d = script.CreateDelegate()` with message: **only methods, properties, fields and events can take a receiver (Parameter 'symbol')**

This code works fine with versions of Microsoft.CodeAnalysis.CSharp.Scripting **prior** to 3.3.1
This has been reproduced with .net Core 2.2 and .net Core 3.0

For version 3.3.1 one can explicitly mention the type as a workaround and no exception will be thrown: replace `TryGetFastHelp(out var result)` with `TryGetFastHelp(out HelpResult result)`

### LINKED ISSUE #39581: C# Interactive static local can invoke instance method on global
**Version Used**: VS 16.4 preview 2, Microsoft.CodeAnalysis.Scripting.CSharp v 3.3.1

**Steps to Reproduce**:

Run the following:
```csharp
using Microsoft.CodeAnalysis.CSharp.Scripting;
using Microsoft.CodeAnalysis.Scripting;

public class ExecutionContext
{
	public bool TryGetValue(out object obj)
	{
		obj = new object();
		return true;
	}
}

class Program
{
	static async System.Threading.Tasks.Task Main(string[] args)
	{
		var options = ScriptOptions.Default
			.AddReferences(typeof(ExecutionContext).Assembly);

		var code = @"
			bool M()
			{
				return Inner();
				static bool Inner()
				{
					if(TryGetValue(out var result)){
					    _ = result;
					}
					return true;
				}
			}
			return M();
            ";

		await CSharpScript.RunAsync<bool>(code, globalsType: typeof(ExecutionContext), options: options, globals: new ExecutionContext());
	}
}
```

**Expected Behavior**:

error CS8422: A static local function cannot contain a reference to 'this' or 'base'.

Note that you do get `error CS0120: An object reference is required for the non-static field, method, or property 'ExecutionContext.TryGetValue(out object)'` when you run the following:

```csharp
using Microsoft.CodeAnalysis.CSharp.Scripting;
using Microsoft.CodeAnalysis.Scripting;

public class ExecutionContext
{
	public bool TryGetValue(out object obj)
	{
		obj = new object();
		return true;
	}
}

class Program
{
	static async System.Threading.Tasks.Task Main(string[] args)
	{
		var options = ScriptOptions.Default
			.AddReferences(typeof(ExecutionContext).Assembly);

		var code = @"
			static bool M()
			{
				if(TryGetValue(out var result)){
				    _ = result;
				}
				return true;
			}
			return M();
            ";

		await CSharpScript.RunAsync<bool>(code, globalsType: typeof(ExecutionContext), options: options, globals: new ExecutionContext());
	}
}
```

**Actual Behavior**:

No error

### PR DESCRIPTION
**Pull request by YairHalberstadt**
Fixes #39565
Fixes #39581
Fixes #39548

Note that instead of reporting `error CS8422: A static local function cannot contain a reference to 'this' or 'base'.` we instead report `error CS0120: An object reference is required for the non-static field, method, or property`

Given that this is an extremely edge scenario in scripting I think that's not too much of an issue?

Also fixing #39581 is a breaking change. I highly doubt it's one anyone's hit, but insofar as that's true, maybe there's no point fixing it?

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 1]
```diff
@@ -1810,9 +1810,23 @@ internal Symbol ContainingMember()
             return containingMember;
         }
 
-        private BoundExpression TryBindInteractiveReceiver(SyntaxNode syntax, Symbol currentMember, NamedTypeSymbol currentType, NamedTypeSymbol memberDeclaringType)
+        private bool IsInstanceContext()
         {
-            if (currentType.TypeKind == TypeKind.Submission && currentMember.RequiresInstanceReceiver())
+            var containingMember = this.ContainingMemberOrLambda;
+            while (containingMember.Kind != SymbolKind.NamedType && (object)containingMember.ContainingSymbol != null && containingMember.ContainingSymbol.Kind != SymbolKind.NamedType)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: > && (object)containingMember.ContainingSymbol != null && containingMember.ContainingSymbol.Kind != SymbolKind.NamedType [](start = 64, length = 119)

Can we avoid checking `Kind != SymbolKind.NamedType` and `IsStatic` twice, without making the loop unnecessarily complicated?

Would something like the following work?
```C#
    var containingMember = this.ContainingMemberOrLambda;
    do
    {
        if (containingMember.IsStatic)
        {
            return false;
        }
        if (containingMember.Kind == SymbolKind.NamedType)
        {
            break;
        }
        containingMember = containingMember.ContainingSymbol;
    } while ((object)containingMember != null);
    return true;

```

**Comment by tmat** [comment]
> Also fixing #39581 is a breaking change. I highly doubt it's one anyone's hit, but insofar as that's true, maybe there's no point fixing it?

Let's fix it.

File: src/Scripting/CSharpTest/InteractiveSessionTests.cs [hunk 2]
```diff
@@ -1776,6 +1775,95 @@ public void HostObjectAssemblyReference3()
...
+                return true;
+            }
+        }
+
+        [Fact]
+        [WorkItem(39565, "https://github.com/dotnet/roslyn/issues/39565")]
+        public async Task Regression39565()
+        {
+            var code = @"
+            if(TryGetValue(out var result)){
```
Comment (tmat) [inline src/Scripting/CSharpTest/InteractiveSessionTests.cs]: Nit: Don't indent the embedded code, it's harder to read and maintain the indentation.

```C#
            var code = @"
if (TryGetValue(out var result)){
   _ = result;
}
return true;
";
```

**Comment by YairHalberstadt** [comment]
Reopening to trigger CI

**Comment by YairHalberstadt** [comment]
Tests have passed now, so I think this is good to merge

**Comment by cston** [comment]
@dotnet/roslyn-compiler, please review.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 3]
```diff
@@ -1810,9 +1810,29 @@ internal Symbol ContainingMember()
...
+                if (containingMember.Kind == SymbolKind.NamedType)
+                {
+                    break;
+                }
+                containingMember = containingMember.ContainingSymbol;
+            } while ((object)containingMember != null);
+            return true;
+        }
+
+        private BoundExpression TryBindInteractiveReceiver(SyntaxNode syntax, NamedTypeSymbol currentType, NamedTypeSymbol memberDeclaringType)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: >NamedTypeSymbol currentType [](start = 78, length = 27)

I think this parameter should be removed. Why force consumers to understand what to pass here and make it possible to make a mistake?

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 4]
```diff
@@ -1810,9 +1810,29 @@ internal Symbol ContainingMember()
             return containingMember;
         }
 
-        private BoundExpression TryBindInteractiveReceiver(SyntaxNode syntax, Symbol currentMember, NamedTypeSymbol currentType, NamedTypeSymbol memberDeclaringType)
+        private bool IsInstanceContext()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: >IsInstanceContext [](start = 21, length = 17)

Consider making this a local function. It is used only in one place.

**Comment by gafter** [comment]
Does this fix #39548?  Testing for that would be this:

```csharp
        [Fact, WorkItem(39548, "https://github.com/dotnet/roslyn/issues/39548")]
        public async Task PatternVariableDeclaration()
        {
            var state = await CSharpScript.RunAsync("var x = (false, 4);");
            state = await state.ContinueWithAsync("x is (false, var y)");
            Assert.Equal(true, state.ReturnValue);
        }
```

**Comment by YairHalberstadt** [comment]
@gafter

Yes it does

**Comment by YairHalberstadt** [comment]
By the way @jinujoseph, isn't this Area-Interactive rather than Area-Ide?

**Comment by jinujoseph** [comment]
thanks @YairHalberstadt . fixed

**Comment by cston** [comment]
Thanks @YairHalberstadt.
