### PR TITLE
Break binding cycles caused by type forwarders.

### LINKED ISSUE #58517: Stack overflow through type forwarder
The repro scenario is inspired by Watson bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1348738.

```
        [Fact]
        public void CycleThroughForwardedType()
        {
            var source1_1 = @"
public class Base
{
}
";

            var comp1_v1 = CreateCompilation(source1_1, assemblyName: "Lib1");
            comp1_v1.VerifyDiagnostics();

            var source2 = @"
[MyAttribute]
public class Derived : Base
{
}

class MyAttribute : System.Attribute {}
";

            var comp2 = CreateCompilation(source2, references: new[] { comp1_v1.ToMetadataReference() });

            var comp2Ref = comp2.EmitToImageReference();

            var source1_2 = @"
using System.Runtime.CompilerServices;

[assembly: TypeForwardedTo(typeof(Derived)]
";

            var comp1_v2 = CreateCompilation(source1_2, assemblyName: "Lib1", references: new[] { comp2Ref });
            comp1_v2.VerifyDiagnostics();
        }
```

Observed: a stack overflow exception 
```
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.MakeDeclaredBaseType() Line 513	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.GetDeclaredBaseType(bool skipTransformsIfNecessary) Line 470	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.TypeKind.get() Line 1698	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.PrimitiveTypeCode.get() Line 510	C#
>	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.ResultSymbol.__resultSymbol|1044_0(Microsoft.CodeAnalysis.CSharp.LookupResult result, string simpleName, int arity, Microsoft.CodeAnalysis.SyntaxNode where, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, bool suppressUseSiteDiagnostics, out bool wasError, Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceOrTypeSymbol qualifierOpt, Microsoft.CodeAnalysis.CSharp.LookupOptions options) Line 2035	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.ResultSymbol(Microsoft.CodeAnalysis.CSharp.LookupResult result, string simpleName, int arity, Microsoft.CodeAnalysis.SyntaxNode where, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, bool suppressUseSiteDiagnostics, out bool wasError, Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceOrTypeSymbol qualifierOpt, Microsoft.CodeAnalysis.CSharp.LookupOptions options) Line 1708	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindNonGenericSimpleNamespaceOrTypeOrAliasSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved, bool suppressUseSiteDiagnostics, Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceOrTypeSymbol qualifierOpt) Line 908	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindNamespaceOrTypeOrAliasSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax syntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved, bool suppressUseSiteDiagnostics) Line 413	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindTypeOrAlias(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax syntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved, bool suppressUseSiteDiagnostics) Line 318	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindType(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax syntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, out Microsoft.CodeAnalysis.CSharp.Symbols.AliasSymbol alias, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved) Line 307	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindTypeOf(Microsoft.CodeAnalysis.CSharp.Syntax.TypeOfExpressionSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 1316	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, bool invoked, bool indexed) Line 692	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, bool invoked, bool indexed) Line 517	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindValue(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, Microsoft.CodeAnalysis.CSharp.Binder.BindValueKind valueKind) Line 235	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentExpression(Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax argumentExpression, Microsoft.CodeAnalysis.RefKind refKind, bool allowArglist) Line 2985	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindAttributeArguments(Microsoft.CodeAnalysis.CSharp.Syntax.AttributeArgumentListSyntax attributeArgumentList, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol attributeType, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 337	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindAttributeCore(Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax node, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol attributeType, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 157	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindAttribute(Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax node, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol attributeType, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 115	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.GetAttribute(Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax node, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol boundAttributeType, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 108	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.GetAttributes(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Binder> binders, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax> attributesToBind, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol> boundAttributeTypes, Microsoft.CodeAnalysis.CSharp.Symbols.CSharpAttributeData[] attributeDataArray, Microsoft.CodeAnalysis.CSharp.BoundAttribute[] boundAttributeArray, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 77	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbol.LoadAndValidateAttributes(Roslyn.Utilities.OneOrMany<Microsoft.CodeAnalysis.SyntaxList<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeListSyntax>> attributesSyntaxLists, ref Microsoft.CodeAnalysis.CustomAttributesBag<Microsoft.CodeAnalysis.CSharp.Symbols.CSharpAttributeData> lazyCustomAttributesBag, Microsoft.CodeAnalysis.CSharp.Symbols.AttributeLocation symbolPart, bool earlyDecodingOnly, Microsoft.CodeAnalysis.CSharp.Binder binderOpt, System.Func<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax, bool> attributeMatchesOpt) Line 344	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.GetForwardedTypes() Line 1702	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.TryLookupForwardedMetadataTypeWithCycleDetection(ref Microsoft.CodeAnalysis.MetadataTypeName emittedName, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> visitedAssemblies) Line 2726	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.NonMissingAssemblySymbol.LookupTopLevelMetadataTypeWithCycleDetection(ref Microsoft.CodeAnalysis.MetadataTypeName emittedName, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> visitedAssemblies, bool digThroughForwardedTypes) Line 160	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol.LookupTopLevelMetadataType(ref Microsoft.CodeAnalysis.MetadataTypeName emittedName, bool digThroughForwardedTypes) Line 328	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.MetadataDecoder.LookupTopLevelTypeDefSymbol(int referencedAssemblyIndex, ref Microsoft.CodeAnalysis.MetadataTypeName emittedName) Line 141	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.MetadataDecoder<Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEModuleSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol, Microsoft.CodeAnalysis.CSharp.Symbol>.GetTypeByNameOrThrow(ref Microsoft.CodeAnalysis.MetadataTypeName fullName, System.Reflection.Metadata.EntityHandle tokenResolutionScope, out bool isNoPiaLocalType) Line 552	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.MetadataDecoder<Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEModuleSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol, Microsoft.CodeAnalysis.CSharp.Symbol>.GetTypeOfTypeRef(System.Reflection.Metadata.TypeReferenceHandle typeRef, out bool isNoPiaLocalType) Line 499	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.MetadataDecoder<Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEModuleSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol, Microsoft.CodeAnalysis.CSharp.Symbol>.GetTypeOfToken(System.Reflection.Metadata.EntityHandle token, out bool isNoPiaLocalType) Line 138	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.MetadataDecoder<Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEModuleSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol, Microsoft.CodeAnalysis.CSharp.Symbol>.GetTypeOfToken(System.Reflection.Metadata.EntityHandle token) Line 116	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.MakeDeclaredBaseType() Line 513	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.GetDeclaredBaseType(bool skipTransformsIfNecessary) Line 470	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.TypeKind.get() Line 1698	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol.PrimitiveTypeCode.get() Line 510	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.ResultSymbol.__resultSymbol|1044_0(Microsoft.CodeAnalysis.CSharp.LookupResult result, string simpleName, int arity, Microsoft.CodeAnalysis.SyntaxNode where, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, bool suppressUseSiteDiagnostics, out bool wasError, Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceOrTypeSymbol qualifierOpt, Microsoft.CodeAnalysis.CSharp.LookupOptions options) Line 2035	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.ResultSymbol(Microsoft.CodeAnalysis.CSharp.LookupResult result, string simpleName, int arity, Microsoft.CodeAnalysis.SyntaxNode where, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, bool suppressUseSiteDiagnostics, out bool wasError, Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceOrTypeSymbol qualifierOpt, Microsoft.CodeAnalysis.CSharp.LookupOptions options) Line 1708	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindNonGenericSimpleNamespaceOrTypeOrAliasSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved, bool suppressUseSiteDiagnostics, Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceOrTypeSymbol qualifierOpt) Line 908	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindNamespaceOrTypeOrAliasSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax syntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved, bool suppressUseSiteDiagnostics) Line 413	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindTypeOrAlias(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax syntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved, bool suppressUseSiteDiagnostics) Line 318	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindType(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax syntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, out Microsoft.CodeAnalysis.CSharp.Symbols.AliasSymbol alias, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved) Line 307	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindTypeOf(Microsoft.CodeAnalysis.CSharp.Syntax.TypeOfExpressionSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 1316	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, bool invoked, bool indexed) Line 692	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, bool invoked, bool indexed) Line 517	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindValue(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, Microsoft.CodeAnalysis.CSharp.Binder.BindValueKind valueKind) Line 235	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentExpression(Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax argumentExpression, Microsoft.CodeAnalysis.RefKind refKind, bool allowArglist) Line 2985	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindAttributeArguments(Microsoft.CodeAnalysis.CSharp.Syntax.AttributeArgumentListSyntax attributeArgumentList, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol attributeType, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 337	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindAttributeCore(Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax node, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol attributeType, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 157	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindAttribute(Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax node, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol attributeType, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 115	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.GetAttribute(Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax node, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol boundAttributeType, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 108	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.GetAttributes(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Binder> binders, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax> attributesToBind, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol> boundAttributeTypes, Microsoft.CodeAnalysis.CSharp.Symbols.CSharpAttributeData[] attributeDataArray, Microsoft.CodeAnalysis.CSharp.BoundAttribute[] boundAttributeArray, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 77	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbol.LoadAndValidateAttributes(Roslyn.Utilities.OneOrMany<Microsoft.CodeAnalysis.SyntaxList<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeListSyntax>> attributesSyntaxLists, ref Microsoft.CodeAnalysis.CustomAttributesBag<Microsoft.CodeAnalysis.CSharp.Symbols.CSharpAttributeData> lazyCustomAttributesBag, Microsoft.CodeAnalysis.CSharp.Symbols.AttributeLocation symbolPart, bool earlyDecodingOnly, Microsoft.CodeAnalysis.CSharp.Binder binderOpt, System.Func<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax, bool> attributeMatchesOpt) Line 344	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.GetForwardedTypes() Line 1702	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.TryLookupForwardedMetadataTypeWithCycleDetection(ref Microsoft.CodeAnalysis.MetadataTypeName emittedName, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> visitedAssemblies) Line 2726	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.NonMissingAssemblySymbol.LookupTopLevelMetadataTypeWithCycleDetection(ref Microsoft.CodeAnalysis.MetadataTypeName emittedName, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> visitedAssemblies, bool digThroughForwardedTypes) Line 160	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol.LookupTopLevelMetadataType(ref Microsoft.CodeAnalysis.MetadataTypeName emittedName, bool digThroughForwardedTypes) Line 328	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.MetadataDecoder.LookupTopLevelTypeDefSymbol(int referencedAssemblyIndex, ref Microsoft.CodeAnalysis.MetadataTypeName emittedName) Line 141	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.MetadataDecoder<Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEModuleSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol, Microsoft.CodeAnalysis.CSharp.Symbol>.GetTypeByNameOrThrow(ref Microsoft.CodeAnalysis.MetadataTypeName fullName, System.Reflection.Metadata.EntityHandle tokenResolutionScope, out bool isNoPiaLocalType) Line 552	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.MetadataDecoder<Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEModuleSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol, Microsoft.CodeAnalysis.CSharp.Symbol>.GetTypeOfTypeRef(System.Reflection.Metadata.TypeReferenceHandle typeRef, out bool isNoPiaLocalType) Line 499	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.MetadataDecoder<Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEModuleSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol, Microsoft.CodeAnalysis.CSharp.Symbol>.GetTypeOfToken(System.Reflection.Metadata.EntityHandle token, out bool isNoPiaLocalType) Line 138	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.MetadataDecoder<Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEModuleSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol, Microsoft.CodeAnalysis.CSharp.Symbol>.GetTypeOfToken(System.Reflection.Metadata.EntityHandle token) Line 116	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.MakeDeclaredBaseType() Line 513	C#
```

Another scenario with a slightly different call stack, but it repeats many of the steps from the previous stack:
```
        [Fact]
        public void CycleThroughForwardedType()
        {
            var source1_1 = @"
public class Base
{
}
";

            var comp1_v1 = CreateCompilation(source1_1, assemblyName: "Lib1");
            comp1_v1.VerifyDiagnostics();

            var source2 = @"
public class Derived : Base
{
}
";

            var comp2 = CreateCompilation(source2, references: new[] { comp1_v1.ToMetadataReference() });

            var comp2Ref = comp2.EmitToImageReference();

            var source1_2 = @"
using System.Runtime.CompilerServices;

[assembly: TypeForwardedTo(typeof(Derived)]
";

            var comp1_v2 = CreateCompilation(source1_2, assemblyName: "Lib1", references: new[] { comp2Ref });
            comp1_v2.VerifyDiagnostics();
        }
```

Observed: a stack overflow exception 
```
 	[Managed to Native Transition]	
 	mscorlib.dll!System.Globalization.CompareInfo.IndexOf(string source, string value, int startIndex, int count, System.Globalization.CompareOptions options)	Unknown
 	mscorlib.dll!string.IndexOf(string value, int startIndex, int count, System.StringComparison comparisonType)	Unknown
 	mscorlib.dll!string.Contains(string value)	Unknown
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.MetadataTypeName.FromTypeName(string typeName, bool useCLSCompliantNameArityEncoding, int forcedArity) Line 125	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.MetadataDecoder<Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEModuleSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol, Microsoft.CodeAnalysis.CSharp.Symbol>.GetTypeOfTypeRef(System.Reflection.Metadata.TypeReferenceHandle typeRef, out bool isNoPiaLocalType) Line 495	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.MetadataDecoder<Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEModuleSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol, Microsoft.CodeAnalysis.CSharp.Symbol>.GetTypeOfToken(System.Reflection.Metadata.EntityHandle token, out bool isNoPiaLocalType) Line 138	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.MetadataDecoder<Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEModuleSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol, Microsoft.CodeAnalysis.CSharp.Symbol>.GetTypeOfToken(System.Reflection.Metadata.EntityHandle token) Line 116	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.MakeDeclaredBaseType() Line 513	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.GetDeclaredBaseType(bool skipTransformsIfNecessary) Line 470	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.TypeKind.get() Line 1698	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.IsUncommon() Line 118	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.GetUncommonProperties() Line 100	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.HasCodeAnalysisEmbeddedAttribute.get() Line 418	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.SymbolExtensions.IsHiddenByCodeAnalysisEmbeddedAttribute(Microsoft.CodeAnalysis.CSharp.Symbol symbol) Line 321	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.CheckViability(Microsoft.CodeAnalysis.CSharp.Symbol symbol, int arity, Microsoft.CodeAnalysis.CSharp.LookupOptions options, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol accessThroughType, bool diagnose, ref Microsoft.CodeAnalysis.CompoundUseSiteInfo<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> useSiteInfo, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved) Line 1326	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.LookupMembersInNamespace(Microsoft.CodeAnalysis.CSharp.LookupResult result, Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceSymbol ns, string name, int arity, Microsoft.CodeAnalysis.CSharp.LookupOptions options, Microsoft.CodeAnalysis.CSharp.Binder originalBinder, bool diagnose, ref Microsoft.CodeAnalysis.CompoundUseSiteInfo<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> useSiteInfo) Line 449	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.LookupMembersInternal(Microsoft.CodeAnalysis.CSharp.LookupResult result, Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceOrTypeSymbol nsOrType, string name, int arity, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved, Microsoft.CodeAnalysis.CSharp.LookupOptions options, Microsoft.CodeAnalysis.CSharp.Binder originalBinder, bool diagnose, ref Microsoft.CodeAnalysis.CompoundUseSiteInfo<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> useSiteInfo) Line 171	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.InContainerBinder.LookupSymbolsInSingleBinder(Microsoft.CodeAnalysis.CSharp.LookupResult result, string name, int arity, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved, Microsoft.CodeAnalysis.CSharp.LookupOptions options, Microsoft.CodeAnalysis.CSharp.Binder originalBinder, bool diagnose, ref Microsoft.CodeAnalysis.CompoundUseSiteInfo<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> useSiteInfo) Line 111	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.LookupSymbolsInternal(Microsoft.CodeAnalysis.CSharp.LookupResult result, string name, int arity, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved, Microsoft.CodeAnalysis.CSharp.LookupOptions options, bool diagnose, ref Microsoft.CodeAnalysis.CompoundUseSiteInfo<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> useSiteInfo) Line 99	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.LookupSymbolsOrMembersInternal(Microsoft.CodeAnalysis.CSharp.LookupResult result, Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceOrTypeSymbol qualifierOpt, string name, int arity, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved, Microsoft.CodeAnalysis.CSharp.LookupOptions options, bool diagnose, ref Microsoft.CodeAnalysis.CompoundUseSiteInfo<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> useSiteInfo) Line 137	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.LookupSymbolsSimpleName(Microsoft.CodeAnalysis.CSharp.LookupResult result, Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceOrTypeSymbol qualifierOpt, string plainName, int arity, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved, Microsoft.CodeAnalysis.CSharp.LookupOptions options, bool diagnose, ref Microsoft.CodeAnalysis.CompoundUseSiteInfo<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> useSiteInfo) Line 43	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindNonGenericSimpleNamespaceOrTypeOrAliasSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved, bool suppressUseSiteDiagnostics, Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceOrTypeSymbol qualifierOpt) Line 877	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindNamespaceOrTypeOrAliasSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax syntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved, bool suppressUseSiteDiagnostics) Line 413	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindTypeOrAlias(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax syntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved, bool suppressUseSiteDiagnostics) Line 318	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindType(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax syntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, out Microsoft.CodeAnalysis.CSharp.Symbols.AliasSymbol alias, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved) Line 307	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindTypeOf(Microsoft.CodeAnalysis.CSharp.Syntax.TypeOfExpressionSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 1316	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, bool invoked, bool indexed) Line 692	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, bool invoked, bool indexed) Line 517	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindValue(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, Microsoft.CodeAnalysis.CSharp.Binder.BindValueKind valueKind) Line 235	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentExpression(Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax argumentExpression, Microsoft.CodeAnalysis.RefKind refKind, bool allowArglist) Line 2985	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindAttributeArguments(Microsoft.CodeAnalysis.CSharp.Syntax.AttributeArgumentListSyntax attributeArgumentList, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol attributeType, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 337	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindAttributeCore(Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax node, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol attributeType, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 157	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindAttribute(Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax node, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol attributeType, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 115	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.GetAttribute(Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax node, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol boundAttributeType, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 108	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.GetAttributes(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Binder> binders, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax> attributesToBind, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol> boundAttributeTypes, Microsoft.CodeAnalysis.CSharp.Symbols.CSharpAttributeData[] attributeDataArray, Microsoft.CodeAnalysis.CSharp.BoundAttribute[] boundAttributeArray, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 77	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbol.LoadAndValidateAttributes(Roslyn.Utilities.OneOrMany<Microsoft.CodeAnalysis.SyntaxList<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeListSyntax>> attributesSyntaxLists, ref Microsoft.CodeAnalysis.CustomAttributesBag<Microsoft.CodeAnalysis.CSharp.Symbols.CSharpAttributeData> lazyCustomAttributesBag, Microsoft.CodeAnalysis.CSharp.Symbols.AttributeLocation symbolPart, bool earlyDecodingOnly, Microsoft.CodeAnalysis.CSharp.Binder binderOpt, System.Func<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax, bool> attributeMatchesOpt) Line 344	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.GetForwardedTypes() Line 1702	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.TryLookupForwardedMetadataTypeWithCycleDetection(ref Microsoft.CodeAnalysis.MetadataTypeName emittedName, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> visitedAssemblies) Line 2726	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.NonMissingAssemblySymbol.LookupTopLevelMetadataTypeWithCycleDetection(ref Microsoft.CodeAnalysis.MetadataTypeName emittedName, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> visitedAssemblies, bool digThroughForwardedTypes) Line 160	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol.LookupTopLevelMetadataType(ref Microsoft.CodeAnalysis.MetadataTypeName emittedName, bool digThroughForwardedTypes) Line 328	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.MetadataDecoder.LookupTopLevelTypeDefSymbol(int referencedAssemblyIndex, ref Microsoft.CodeAnalysis.MetadataTypeName emittedName) Line 141	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.MetadataDecoder<Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEModuleSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol, Microsoft.CodeAnalysis.CSharp.Symbol>.GetTypeByNameOrThrow(ref Microsoft.CodeAnalysis.MetadataTypeName fullName, System.Reflection.Metadata.EntityHandle tokenResolutionScope, out bool isNoPiaLocalType) Line 552	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.MetadataDecoder<Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEModuleSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol, Microsoft.CodeAnalysis.CSharp.Symbol>.GetTypeOfTypeRef(System.Reflection.Metadata.TypeReferenceHandle typeRef, out bool isNoPiaLocalType) Line 499	C#
 	[The 38 frame(s) above this were repeated 110 times]	
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.GetForwardedTypes() Line 1702	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.TryLookupForwardedMetadataTypeWithCycleDetection(ref Microsoft.CodeAnalysis.MetadataTypeName emittedName, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> visitedAssemblies) Line 2726	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.NonMissingAssemblySymbol.LookupTopLevelMetadataTypeWithCycleDetection(ref Microsoft.CodeAnalysis.MetadataTypeName emittedName, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> visitedAssemblies, bool digThroughForwardedTypes) Line 160	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol.LookupTopLevelMetadataType(ref Microsoft.CodeAnalysis.MetadataTypeName emittedName, bool digThroughForwardedTypes) Line 328	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.MetadataDecoder.LookupTopLevelTypeDefSymbol(int referencedAssemblyIndex, ref Microsoft.CodeAnalysis.MetadataTypeName emittedName) Line 141	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.MetadataDecoder<Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEModuleSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol, Microsoft.CodeAnalysis.CSharp.Symbol>.GetTypeByNameOrThrow(ref Microsoft.CodeAnalysis.MetadataTypeName fullName, System.Reflection.Metadata.EntityHandle tokenResolutionScope, out bool isNoPiaLocalType) Line 552	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.MetadataDecoder<Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEModuleSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol, Microsoft.CodeAnalysis.CSharp.Symbol>.GetTypeOfTypeRef(System.Reflection.Metadata.TypeReferenceHandle typeRef, out bool isNoPiaLocalType) Line 499	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.MetadataDecoder<Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEModuleSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol, Microsoft.CodeAnalysis.CSharp.Symbol>.GetTypeOfToken(System.Reflection.Metadata.EntityHandle token, out bool isNoPiaLocalType) Line 138	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.MetadataDecoder<Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEModuleSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.FieldSymbol, Microsoft.CodeAnalysis.CSharp.Symbol>.GetTypeOfToken(System.Reflection.Metadata.EntityHandle token) Line 116	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.MakeDeclaredBaseType() Line 513	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.GetDeclaredBaseType(bool skipTransformsIfNecessary) Line 470	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.TypeKind.get() Line 1698	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.IsUncommon() Line 118	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.GetUncommonProperties() Line 100	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.HasCodeAnalysisEmbeddedAttribute.get() Line 418	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.SymbolExtensions.IsHiddenByCodeAnalysisEmbeddedAttribute(Microsoft.CodeAnalysis.CSharp.Symbol symbol) Line 321	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.CheckViability(Microsoft.CodeAnalysis.CSharp.Symbol symbol, int arity, Microsoft.CodeAnalysis.CSharp.LookupOptions options, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol accessThroughType, bool diagnose, ref Microsoft.CodeAnalysis.CompoundUseSiteInfo<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> useSiteInfo, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved) Line 1326	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.LookupMembersInNamespace(Microsoft.CodeAnalysis.CSharp.LookupResult result, Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceSymbol ns, string name, int arity, Microsoft.CodeAnalysis.CSharp.LookupOptions options, Microsoft.CodeAnalysis.CSharp.Binder originalBinder, bool diagnose, ref Microsoft.CodeAnalysis.CompoundUseSiteInfo<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> useSiteInfo) Line 449	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.LookupMembersInternal(Microsoft.CodeAnalysis.CSharp.LookupResult result, Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceOrTypeSymbol nsOrType, string name, int arity, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved, Microsoft.CodeAnalysis.CSharp.LookupOptions options, Microsoft.CodeAnalysis.CSharp.Binder originalBinder, bool diagnose, ref Microsoft.CodeAnalysis.CompoundUseSiteInfo<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> useSiteInfo) Line 171	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.InContainerBinder.LookupSymbolsInSingleBinder(Microsoft.CodeAnalysis.CSharp.LookupResult result, string name, int arity, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved, Microsoft.CodeAnalysis.CSharp.LookupOptions options, Microsoft.CodeAnalysis.CSharp.Binder originalBinder, bool diagnose, ref Microsoft.CodeAnalysis.CompoundUseSiteInfo<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> useSiteInfo) Line 111	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.LookupSymbolsInternal(Microsoft.CodeAnalysis.CSharp.LookupResult result, string name, int arity, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved, Microsoft.CodeAnalysis.CSharp.LookupOptions options, bool diagnose, ref Microsoft.CodeAnalysis.CompoundUseSiteInfo<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> useSiteInfo) Line 99	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.LookupSymbolsOrMembersInternal(Microsoft.CodeAnalysis.CSharp.LookupResult result, Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceOrTypeSymbol qualifierOpt, string name, int arity, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved, Microsoft.CodeAnalysis.CSharp.LookupOptions options, bool diagnose, ref Microsoft.CodeAnalysis.CompoundUseSiteInfo<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> useSiteInfo) Line 137	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.LookupSymbolsSimpleName(Microsoft.CodeAnalysis.CSharp.LookupResult result, Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceOrTypeSymbol qualifierOpt, string plainName, int arity, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved, Microsoft.CodeAnalysis.CSharp.LookupOptions options, bool diagnose, ref Microsoft.CodeAnalysis.CompoundUseSiteInfo<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> useSiteInfo) Line 43	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindNonGenericSimpleNamespaceOrTypeOrAliasSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved, bool suppressUseSiteDiagnostics, Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceOrTypeSymbol qualifierOpt) Line 877	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindNamespaceOrTypeOrAliasSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax syntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved, bool suppressUseSiteDiagnostics) Line 413	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindTypeOrAlias(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax syntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved, bool suppressUseSiteDiagnostics) Line 318	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindType(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax syntax, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, out Microsoft.CodeAnalysis.CSharp.Symbols.AliasSymbol alias, Roslyn.Utilities.ConsList<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol> basesBeingResolved) Line 307	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindTypeOf(Microsoft.CodeAnalysis.CSharp.Syntax.TypeOfExpressionSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 1316	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, bool invoked, bool indexed) Line 692	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, bool invoked, bool indexed) Line 517	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindValue(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax node, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, Microsoft.CodeAnalysis.CSharp.Binder.BindValueKind valueKind) Line 235	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindArgumentExpression(Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics, Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax argumentExpression, Microsoft.CodeAnalysis.RefKind refKind, bool allowArglist) Line 2985	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindAttributeArguments(Microsoft.CodeAnalysis.CSharp.Syntax.AttributeArgumentListSyntax attributeArgumentList, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol attributeType, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 337	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindAttributeCore(Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax node, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol attributeType, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 157	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindAttribute(Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax node, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol attributeType, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 115	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.GetAttribute(Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax node, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol boundAttributeType, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 108	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.GetAttributes(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Binder> binders, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax> attributesToBind, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol> boundAttributeTypes, Microsoft.CodeAnalysis.CSharp.Symbols.CSharpAttributeData[] attributeDataArray, Microsoft.CodeAnalysis.CSharp.BoundAttribute[] boundAttributeArray, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag diagnostics) Line 77	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbol.LoadAndValidateAttributes(Roslyn.Utilities.OneOrMany<Microsoft.CodeAnalysis.SyntaxList<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeListSyntax>> attributesSyntaxLists, ref Microsoft.CodeAnalysis.CustomAttributesBag<Microsoft.CodeAnalysis.CSharp.Symbols.CSharpAttributeData> lazyCustomAttributesBag, Microsoft.CodeAnalysis.CSharp.Symbols.AttributeLocation symbolPart, bool earlyDecodingOnly, Microsoft.CodeAnalysis.CSharp.Binder binderOpt, System.Func<Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax, bool> attributeMatchesOpt) Line 344	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.EnsureAttributesAreBound() Line 1556	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol.ForceComplete(Microsoft.CodeAnalysis.SourceLocation locationOpt, System.Threading.CancellationToken cancellationToken) Line 906	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSourceDeclarationDiagnostics(Microsoft.CodeAnalysis.SyntaxTree syntaxTree, Microsoft.CodeAnalysis.Text.TextSpan? filterSpanWithinTree, System.Func<System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Diagnostic>, Microsoft.CodeAnalysis.SyntaxTree, Microsoft.CodeAnalysis.Text.TextSpan?, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Diagnostic>> locationFilterOpt, System.Threading.CancellationToken cancellationToken) Line 2942	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsWithoutFiltering(Microsoft.CodeAnalysis.CompilationStage stage, bool includeEarlierStages, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag builder, System.Threading.CancellationToken cancellationToken) Line 2712	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(Microsoft.CodeAnalysis.CompilationStage stage, bool includeEarlierStages, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, System.Threading.CancellationToken cancellationToken) Line 2638	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(Microsoft.CodeAnalysis.CompilationStage stage, bool includeEarlierStages, System.Threading.CancellationToken cancellationToken) Line 2630	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(System.Threading.CancellationToken cancellationToken) Line 2624	C#
 	Microsoft.CodeAnalysis.Test.Utilities.dll!Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyDiagnostics<Microsoft.CodeAnalysis.CSharp.CSharpCompilation>(Microsoft.CodeAnalysis.CSharp.CSharpCompilation c, Microsoft.CodeAnalysis.Test.Utilities.DiagnosticDescription[] expected) Line 103	C#
>	Microsoft.CodeAnalysis.CSharp.Symbol.UnitTests.dll!Microsoft.CodeAnalysis.CSharp.UnitTests.CompilationErrorTests.CycleThroughForwardedType() Line 21253	C#
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #58517.

### CODE REVIEW

**Comment by 333fred** [comment]
Does VB have a similar issue?

**Comment by AlekseyTs** [comment]
> Does VB have a similar issue?

VB doesn't support forwarded types. See ```TypeForwardedToAttribute``` unit-test in src\Compilers\VisualBasic\Test\Symbol\SymbolsTests\Metadata\PE\TypeForwarders.vb, for example.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

**Review by 333fred — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs [hunk 1]
```diff
@@ -1698,19 +1702,66 @@ internal HashSet<NamedTypeSymbol> GetForwardedTypes()
...
+            }
+
+            try
+            {
+                attributesBag = null;
+                LoadAndValidateAttributes(
+                    OneOrMany.Create(GetAttributeDeclarations()), ref attributesBag,
+                    attributeMatchesOpt: this.IsPossibleForwardedTypesAttribute,
+                    beforeAttributePartBound: BeforePossibleForwardedTypesAttributePartBound,
+                    afterAttributePartBound: AfterPossibleForwardedTypesAttributePartBound);
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs:1719]: How often is `GetForwardedTypes` called? This introduces two delegate allocations. If it's a hot path think we should consider caching them out but if not think we can avoid complicating the code here.

**Review by jaredpar — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs:1719]: > How often is GetForwardedTypes called? This introduces two delegate allocations. If it's a hot path think we should consider caching them out but if not think we can avoid complicating the code here. 

I was following what we did around the delegate based on ```IsPossibleForwardedTypesAttribute``` above. I.e. we were not trying to cache it, even though we could. Also, once we merge the support for caching delegates targeting static methods (which I hope going to happen soon), these will be cached.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs:1719]: @jaredpar Would you like me to add manual delegate caching for the two ne delegates here?

Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs:1719]: I think we can avoid doing it for now. If it was a known hot path I would say cache but if it's not then we can cache later if data reveals its a rpoblem.
