### PR TITLE
Don't show enum completion if text is typed after dot

### LINKED ISSUE #18359: Intellisense offers wrong suggestion after dismissal and re-opening in context of switch-case
**Version Used**: 15.0.0.+26228.9

**Steps to Reproduce**:

```CSharp
public sealed class VSConstants
{
    public enum VSStd2KCmdID
    {
        TYPECHAR = 1,
    }

    public enum VSStd97CmdID
    {
        Expand = 187,
    }
}

class Program
{
    static void Main(string[] args)
    {
        switch((VSConstants.VSStd97CmdID)5)
        {
             //Begin typing here vvvv
            case VSConstants.
        }
    }
}
```

1. Type `vss`
2. Observe completion list is correct.
3. Dismiss completion. (`Esc`)
4. Open completion (`Ctr-space`)
5. Observe that incorrect item has been inserted and selected in list.

image

### PR DESCRIPTION
**Pull request by rchande**
Fixes #18359 
Tag @dotnet/roslyn-ide for review

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/EnumAndCompletionListTagCompletionProviderTests.cs [hunk 1]
```diff
@@ -491,5 +491,32 @@ enum E
...
+        public async Task NotAfterDotWithTextTyped()
+        {
+            var markup =
+@"namespace ConsoleApplication253
+{
+    class Program
+    {
+        static void Main(string[] args)
+        {
+            M(E.a$$)
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/EnumAndCompletionListTagCompletionProviderTests.cs]: probably good to have a comment saying that the normal symbolcompletionprovider gives us the values here, so we don't need to duplicate it.  Also, we probably want a test in symbolcompletionprovidertests to make sure that we *do* get values from it.

File: src/Features/CSharp/Portable/Completion/CompletionProviders/EnumAndCompletionListTagCompletionProvider.cs [hunk 2]
```diff
@@ -52,7 +52,9 @@ internal override bool IsInsertionTrigger(SourceText text, int characterPosition
                     return;
                 }
 
-                var token = tree.FindTokenOnLeftOfPosition(position, cancellationToken);
+                var token = tree.FindTokenOnLeftOfPosition(position, cancellationToken)
+                                .GetPreviousTokenIfTouchingWord(position);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/EnumAndCompletionListTagCompletionProvider.cs]: is this a problem for VB as well?

**Comment by rchande** [comment]
Thanks @CyrusNajmabadi , VB looks good and I added the comment/test you suggested.
