### PR TITLE
Produce correct diagnostics on implicit operator conversions for stackalloc expressions

### LINKED ISSUE #26195: Visual Studio crashes while analyzing provided code
**Version Used**: 
Microsoft Visual Studio Professional 2017, Version 15.6.6

**Steps to Reproduce**:
Create new solution and copy-paste sample code there:

```C#
using System;
unsafe class Test
{
	public void Method()
	{
		Test obj1 = stackalloc int[2];
	}

	public static implicit operator Test2(int* value)
	{
		return default(Test);
	}
}
```

**Expected Behavior**:
No crasg

**Actual Behavior**:
Visual studio crashes

### PR DESCRIPTION
**Pull request by OmarTawfik**
Fixes #26195
cc @dotnet/roslyn-compiler for reivew.

### CODE REVIEW

**Comment by OmarTawfik** [comment]
@dotnet-bot test this

**Comment by OmarTawfik** [comment]
@dotnet-bot test this please

**Comment by OmarTawfik** [comment]
@jaredpar for approval.

File: src/Compilers/CSharp/Test/Semantic/Semantics/StackAllocSpanExpressionsTests.cs [hunk 1]
```diff
@@ -742,5 +742,57 @@ void M()
...
+class Test2
+{
+}
+unsafe class Test
+{
+	public void Method()
+	{
+		Test obj1 = stackalloc int[2];
+	}
+	public static implicit operator Test2(int* value) => default;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/StackAllocSpanExpressionsTests.cs]: >Test2 [](start = 33, length = 5)

Do we have tests for scenarios when this is "Test" instead of "Test2"?

File: src/Compilers/CSharp/Test/Semantic/Semantics/StackAllocSpanExpressionsTests.cs [hunk 2]
```diff
@@ -742,5 +742,57 @@ void M()
...
+class Test2
+{
+}
+unsafe class Test
+{
+	public void Method()
+	{
+		Test obj1 = stackalloc int[2];
+	}
+	public static implicit operator Test2(System.Span<int> value) => default;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/StackAllocSpanExpressionsTests.cs]: >Test2 [](start = 33, length = 5)

Do we have tests for scenarios when this is "Test" instead of "Test2"?

File: src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/UserDefinedImplicitConversions.cs [hunk 3]
```diff
@@ -583,6 +583,12 @@ private static bool IsEncompassingImplicitConversionKind(ConversionKind kind)
                 case ConversionKind.PointerToInteger:
                 case ConversionKind.IntegerToPointer:
                 case ConversionKind.IntPtr:
+
+                case ConversionKind.ExplicitTupleLiteral:
+                case ConversionKind.ExplicitTuple:
+
+                case ConversionKind.StackAllocToPointerType:
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/UserDefinedImplicitConversions.cs]: >ConversionKind.StackAllocToPointerType [](start = 21, length = 38)

It is not obvious why is this correct fix. Some explanation and perhaps a quote from relevant portion of language specification might help.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1)

File: src/Compilers/CSharp/Test/Semantic/Semantics/StackAllocSpanExpressionsTests.cs (hunk 1 above)
Comment (OmarTawfik) [reply src/Compilers/CSharp/Test/Semantic/Semantics/StackAllocSpanExpressionsTests.cs]: Yes. Please check the tests at the start of this file for semantic model, and tests at the end of `CodeGenTests.cs` for emitting the conversion.

---
In reply to: [183469924](https://github.com/dotnet/roslyn/pull/26248#discussion_r183469924) [](ancestors = 183469924)

File: src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/UserDefinedImplicitConversions.cs (hunk 3 above)
Comment (OmarTawfik) [reply src/Compilers/CSharp/Portable/Binder/Semantics/Conversions/UserDefinedImplicitConversions.cs]: There is no language spec as this is a C# 7.2 feature.
This is the up to date document: [https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.2/span-safety.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.2/span-safety.md)

About why is that the correct fix, I'll add a comment to explain.

---
In reply to: [183471406](https://github.com/dotnet/roslyn/pull/26248#discussion_r183471406) [](ancestors = 183471406)

**Comment by OmarTawfik** [comment]
@AlekseyTs comments addressed.
Had to rebase because of recent project system changes in `15.8`, but the PR is small enough that it won't cause a problem in reviewing older comments.

**Comment by OmarTawfik** [comment]
@jcouv for ask mode approval.

**Comment by OmarTawfik** [comment]
@dotnet-bot test windows_debug_unit64_prtest

**Comment by OmarTawfik** [comment]
@dotnet-bot test windows_debug_vs-integration_prtest

**Comment by jcouv** [comment]
Approved. Thanks
