### PR TITLE
Fix double negation of integral `MinValue`s

### LINKED ISSUE #29786: C# Metadata Int32 MinValue is wrong
public const Int32 MinValue = --2147483648;

-- ???? It will not compile ...

Visual Studio 15.8.2 ...

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/328206/c-metadata-int32-minvalue-is-wrong.html
VSTS ticketId: 677394_
_These are the original issue comments:_

BJ Myers on 9/11/2018, 04:25 PM (25 min ago): Reproduced in Visual Studio 15.8.4.
_These are the original issue solutions:_
(no solutions)

### PR DESCRIPTION
**Pull request by Scott-Caldwell**
Prior to this PR, integral `MinValue`s would be displayed with double minus signs when viewing the metadata source. This fix adds special casing to generate a correct expression for each `MinValue` variant.

The special casing is necessary because there is logic that checks whether a value is less than `0` and, if so, negates it. Later, a minus sign is prepended to the negated (so now positive) value. The problem there is that the negation of a `MinValue` is itself, so a minus sign was being prepended to a negative number, and we'd get a double minus.

image

Fixes #29786.

### CODE REVIEW

**Comment by jinujoseph** [comment]
cc @CyrusNajmabadi

File: src/EditorFeatures/Test/MetadataAsSource/MetadataAsSourceTests.cs [hunk 1]
```diff
@@ -1510,5 +1510,201 @@ void M([|D|]&lt;int&gt; lambda)
...
+            using (var context = TestContext.Create(LanguageNames.VisualBasic, sourceWithSymbolReference: source))
+            {
+                var navigationSymbol = await context.GetNavigationSymbolAsync();
+                var metadataAsSourceFile = await context.GenerateSourceAsync(navigationSymbol);
+                var document = context.GetDocument(metadataAsSourceFile);
+                var text = await document.GetTextAsync();
+                var line = text.Lines.GetLineFromPosition(metadataAsSourceFile.IdentifierLocation.SourceSpan.Start);
+                var lineText = line.ToString().Trim();
+
+                Assert.Equal(expected, lineText);
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Test/MetadataAsSource/MetadataAsSourceTests.cs]: these tests have a lot of duplication.  can we extract a helper function they all defer to?

File: src/Workspaces/CSharp/Portable/CodeGeneration/ExpressionGenerator.cs [hunk 2]
```diff
@@ -311,5 +312,57 @@ private static ExpressionSyntax GenerateMemberAccess(params string[] names)
...
+        {
+            if (canUseFieldReference || value > long.MinValue)
+            {
+                return GenerateLiteralExpression(type, value, LiteralSpecialValues.Int64SpecialValues, null, canUseFieldReference, SyntaxFactory.Literal, x => x < 0, x => -x);
+            }
+
+            // We have to special case how long.MinValue is printed when we can't refer to the
+            // field directly.
+            var numericLiteralToken = SyntaxFactory.Literal("-9223372036854775808", IntegerUtilities.ToUInt64(value));
+            return SyntaxFactory.LiteralExpression(SyntaxKind.NumericLiteralExpression, numericLiteralToken);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/CodeGeneration/ExpressionGenerator.cs]: all these functions seem nearly identical.  Can we not just pass in these values to the GenerateLiteralExpression helper instead?

File: src/Workspaces/CSharp/Portable/CodeGeneration/ExpressionGenerator.cs [hunk 3]
```diff
@@ -311,5 +312,57 @@ private static ExpressionSyntax GenerateMemberAccess(params string[] names)
...
+        private static ExpressionSyntax GenerateSByteLiteralExpression(ITypeSymbol type, sbyte value, bool canUseFieldReference)
+        {
+            if (canUseFieldReference || value > sbyte.MinValue)
+            {
+                return GenerateLiteralExpression(type, value, LiteralSpecialValues.SByteSpecialValues, null, canUseFieldReference, (s, v) => SyntaxFactory.Literal(s, v), x => x < 0, x => (sbyte)-x);
+            }
+
+            // We have to special case how sbyte.MinValue is printed when we can't refer to the
+            // field directly.
+            var numericLiteralToken = SyntaxFactory.Literal("-128", value);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/CodeGeneration/ExpressionGenerator.cs]: this is incorrect.  we should be generating a NegateExpression here around the LiteralExpression for 128.

File: src/EditorFeatures/Test/MetadataAsSource/MetadataAsSourceTests.cs (hunk 1 above)
Comment (Scott-Caldwell) [reply src/EditorFeatures/Test/MetadataAsSource/MetadataAsSourceTests.cs]: Sure thing

File: src/Workspaces/CSharp/Portable/CodeGeneration/ExpressionGenerator.cs (hunk 2 above)
Comment (Scott-Caldwell) [reply src/Workspaces/CSharp/Portable/CodeGeneration/ExpressionGenerator.cs]: Makes sense. Updated

File: src/Workspaces/CSharp/Portable/CodeGeneration/ExpressionGenerator.cs (hunk 3 above)
Comment (Scott-Caldwell) [reply src/Workspaces/CSharp/Portable/CodeGeneration/ExpressionGenerator.cs]: Updated

File: src/Workspaces/CSharp/Portable/CodeGeneration/ExpressionGenerator.cs [hunk 4]
```diff
@@ -79,17 +80,17 @@ private static ExpressionSyntax GenerateNullLiteral()
...
-                case long val: return GenerateLiteralExpression(type, val, LiteralSpecialValues.Int64SpecialValues, null, canUseFieldReference, SyntaxFactory.Literal, x => x < 0, x => -x);
+                case sbyte val: return GenerateLiteralExpression(type, val, LiteralSpecialValues.SByteSpecialValues, null, canUseFieldReference, (s, v) => SyntaxFactory.Literal(s, v), x => x < 0, x => (sbyte)-x, x => x == sbyte.MinValue, "128");
+                case short val: return GenerateLiteralExpression(type, val, LiteralSpecialValues.Int16SpecialValues, null, canUseFieldReference, (s, v) => SyntaxFactory.Literal(s, v), x => x < 0, x => (short)-x, x => x == short.MinValue, "32768");
+                case int val: return GenerateLiteralExpression(type, val, LiteralSpecialValues.Int32SpecialValues, null, canUseFieldReference, SyntaxFactory.Literal, x => x < 0, x => -x, x => x == int.MinValue, "2147483648");
+                case long val: return GenerateLiteralExpression(type, val, LiteralSpecialValues.Int64SpecialValues, null, canUseFieldReference, SyntaxFactory.Literal, x => x < 0, x => -x, x => x == long.MinValue, "9223372036854775808");
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/CodeGeneration/ExpressionGenerator.cs]: note: i think you may not have to pass `x => x == MinValue` here.  I think you would get the same by just seeing if you got the same value against after negating.

File: src/Workspaces/CSharp/Portable/CodeGeneration/ExpressionGenerator.cs [hunk 5]
```diff
@@ -255,14 +258,19 @@ private static ExpressionSyntax GenerateSingleLiteralExpression(ITypeSymbol type
...
             }
 
+            var signedIntegerMinValue = isSignedIntegerMinValue(value);
             var negative = isNegative(value);
-            if (negative)
+
+            if (negative && !signedIntegerMinValue)
             {
                 value = negate(value);
             }
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/CodeGeneration/ExpressionGenerator.cs]: instead of checking "isSignedIntegerMin" you could do `var negated = negate(value); if (negated.Equals(value)) { /*special logic*/ }` right?

File: src/Workspaces/CSharp/Portable/CodeGeneration/ExpressionGenerator.cs (hunk 4 above)
Comment (Scott-Caldwell) [reply src/Workspaces/CSharp/Portable/CodeGeneration/ExpressionGenerator.cs]: Clever! I'll fix that when I get a chance

File: src/Workspaces/CSharp/Portable/CodeGeneration/ExpressionGenerator.cs (hunk 5 above)
Comment (Scott-Caldwell) [reply src/Workspaces/CSharp/Portable/CodeGeneration/ExpressionGenerator.cs]: Yup, that makes sense. Good catch

**Comment by sharwell** [comment]
@jinujoseph for approval
