### PR TITLE
Global options tests

### LINKED ISSUE #61857: `PreferSystemHashCode` is not set
https://github.com/dotnet/roslyn/blob/2cb0e4d2a4c631c5a41110cb52e241eb675bfa9b/src/Features/LanguageServer/Protocol/Features/Options/IdeAnalyzerOptionsStorage.cs#L20-L37

https://github.com/dotnet/roslyn/blob/2cb0e4d2a4c631c5a41110cb52e241eb675bfa9b/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Diagnostics/IdeAnalyzerOptions.cs#L30-L49

It seems that `PreferSystemHashCode` is unintentionally missing in `IdeAnalyzerOptionsStorage`?

Does making these properties `required` make sense?

cc @tmat

### LINKED ISSUE #61859: `FadeOutComplexCollectionInitialization` is not initialized nor read
https://github.com/dotnet/roslyn/blob/2cb0e4d2a4c631c5a41110cb52e241eb675bfa9b/src/Features/LanguageServer/Protocol/Features/Options/IdeAnalyzerOptionsStorage.cs#L52-L58

It should be initialized below the following line:

https://github.com/dotnet/roslyn/blob/2cb0e4d2a4c631c5a41110cb52e241eb675bfa9b/src/Features/LanguageServer/Protocol/Features/Options/IdeAnalyzerOptionsStorage.cs#L30

---

It also should be used here:

https://github.com/dotnet/roslyn/blob/2cb0e4d2a4c631c5a41110cb52e241eb675bfa9b/src/Analyzers/Core/Analyzers/UseCollectionInitializer/AbstractUseCollectionInitializerDiagnosticAnalyzer.cs#L127

This appears to be a regression from the refactoring. cc @tmat

### PR DESCRIPTION
**Pull request by tmat**
Add test that validates that all properties of options objects are initialized when read from global options.

Use init-property pattern for all option types.

Fixes #61857
Fixes #61859

### CODE REVIEW

File: src/Features/LanguageServer/Protocol/Features/Options/IdeAnalyzerOptionsStorage.cs [hunk 1]
```diff
@@ -28,10 +28,12 @@ public static IdeAnalyzerOptions GetIdeAnalyzerOptions(this IGlobalOptionService
             FadeOutUnusedImports = globalOptions.GetOption(FadeOutUnusedImports, language),
             FadeOutUnreachableCode = globalOptions.GetOption(FadeOutUnreachableCode, language),
             FadeOutComplexObjectInitialization = globalOptions.GetOption(FadeOutComplexObjectInitialization, language),
+            FadeOutComplexCollectionInitialization = globalOptions.GetOption(FadeOutComplexCollectionInitialization, language),
```
Comment (Youssef1313) [inline src/Features/LanguageServer/Protocol/Features/Options/IdeAnalyzerOptionsStorage.cs:31]: There is a missing change in `AbstractUseCollectionInitializerDiagnosticAnalyzer` to actually use this option.

File: src/Features/LanguageServer/Protocol/Features/Options/IdeAnalyzerOptionsStorage.cs [hunk 2]
```diff
@@ -28,10 +28,12 @@ public static IdeAnalyzerOptions GetIdeAnalyzerOptions(this IGlobalOptionService
...
             ReportInvalidPlaceholdersInStringDotFormatCalls = globalOptions.GetOption(ReportInvalidPlaceholdersInStringDotFormatCalls, language),
             ReportInvalidRegexPatterns = globalOptions.GetOption(ReportInvalidRegexPatterns, language),
             ReportInvalidJsonPatterns = globalOptions.GetOption(ReportInvalidJsonPatterns, language),
             DetectAndOfferEditorFeaturesForProbableJsonStrings = globalOptions.GetOption(DetectAndOfferEditorFeaturesForProbableJsonStrings, language),
+            PreferSystemHashCode = globalOptions.GetOption(CodeStyleOptions2.PreferSystemHashCode, language),
```
Comment (Youssef1313) [inline src/Features/LanguageServer/Protocol/Features/Options/IdeAnalyzerOptionsStorage.cs:36]: I'm feeling `CodeStyleOptions2.PreferSystemHashCode` should be moved to this file to be consistent with those other options.

Comment (tmat) [reply src/Features/LanguageServer/Protocol/Features/Options/IdeAnalyzerOptionsStorage.cs:36]: Yes, there is more refactoring to do to move options to better places.

**Review by 333fred — APPROVED** [review]
O# change looks good to me. Haven't looked at anything else.

File: src/Features/Core/Portable/QuickInfo/QuickInfoOptions.cs [hunk 3]
```diff
@@ -4,18 +4,17 @@
...
-    internal readonly record struct QuickInfoOptions(
-        [property: DataMember(Order = 0)] bool ShowRemarksInQuickInfo = true,
-        [property: DataMember(Order = 1)] bool IncludeNavigationHintsInQuickInfo = true)
-    {
-        public QuickInfoOptions()
-            : this(ShowRemarksInQuickInfo: true)
-        {
-        }
+    [DataMember] public bool ShowRemarksInQuickInfo { get; init; } = true;
+    [DataMember] public bool IncludeNavigationHintsInQuickInfo { get; init; } = true;
```
Comment (sharwell) [inline src/Features/Core/Portable/QuickInfo/QuickInfoOptions.cs:13]: ❔ Are we planning to make these required as well?

File: src/Features/Core/Portable/QuickInfo/QuickInfoOptions.cs [hunk 4]
```diff
@@ -4,18 +4,17 @@
...
-namespace Microsoft.CodeAnalysis.QuickInfo
+namespace Microsoft.CodeAnalysis.QuickInfo;
+
+[DataContract]
+internal readonly record struct QuickInfoOptions
 {
-    [DataContract]
-    internal readonly record struct QuickInfoOptions(
-        [property: DataMember(Order = 0)] bool ShowRemarksInQuickInfo = true,
-        [property: DataMember(Order = 1)] bool IncludeNavigationHintsInQuickInfo = true)
```
Comment (sharwell) [inline src/Features/Core/Portable/QuickInfo/QuickInfoOptions.cs:12]: ❔ Why do we not want to keep this pattern?

File: src/Features/Core/Portable/QuickInfo/QuickInfoOptions.cs (hunk 3 above)
Comment (tmat) [reply src/Features/Core/Portable/QuickInfo/QuickInfoOptions.cs:13]: No, these are not required - they have well defined default values,

File: src/Features/Core/Portable/QuickInfo/QuickInfoOptions.cs (hunk 4 above)
Comment (tmat) [reply src/Features/Core/Portable/QuickInfo/QuickInfoOptions.cs:12]: Primary constructors do not work well with inheritance and non-constant default values. In this particular case it's not an issue (yet) but other options run into those problems. If a property is added that requires non-constant default value it would also become an issue. It's better to use init-only properties and object initializers consistently for all option types.

File: src/Features/LanguageServer/Protocol/Features/Options/IdeAnalyzerOptionsStorage.cs (hunk 1 above)
Comment (tmat) [reply src/Features/LanguageServer/Protocol/Features/Options/IdeAnalyzerOptionsStorage.cs:31]: Fixed, but it seems we don't have any tests :( Filed https://github.com/dotnet/roslyn/issues/61992

**Review by sharwell — APPROVED** [review]
