### PR TITLE
Adjust sequence point for if-then-else and switch

### LINKED ISSUE #28288: Bad sequence point in switch with pattern matching in async method
Set a breakpoint in `GenerateDeconstructMethodCodeFixProvider.RegisterCodeFixesAsync` and start debugging any of the tests for this fixer (such as `TestDeconstructionDeclaration_Simple`).
The stepping shows the `return` statement as executed, when it is not actually executed.

switch-seq-point

Unfortunately, I was not able to narrow down a small repro yet (the ones I tried behaved as expected).

This is using `VisualStudio.15.Preview/15.8.0-pre.2.0+27729.1` on PR https://github.com/dotnet/roslyn/pull/28286

### LINKED ISSUE #31665: A switch inside an if .. else .. can confuse the debugger
Moved from https://devdiv.visualstudio.com/DevDiv/_workitems/edit/729380

I reconstructed the problem in the following code:

``` c#
using System;

namespace ConsoleApp1
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            var s = "1";
            if (true)
                switch (s)
                {
                    case "1":
                        Console.Out.WriteLine("Input was 1");
                        break;
                    default:
                        throw new Exception("Default case");
                }
            else
                Console.Out.WriteLine("Too many inputs");
        }
    }
}
```

If this code is debugged, the active statement marker will jump from the break; statement, to the throw... statement.

The throw statement will not be executed, but it had me confused for a couple of hours.

### PR DESCRIPTION
**Pull request by gafter**
Addresses known issues with sequence points.

Fixes #31665
Related to #17076 (included test; unable to repro)
Fixes #28288

### CODE REVIEW

File: src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs [hunk 1]
```diff
@@ -10716,6 +11190,7 @@ .maxstack  2
     IL_0026:  br.s       IL_002a
     // sequence point: break;
     IL_0028:  br.s       IL_002a
+    // sequence point: <hidden>
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs]: Is there a general rule we should remember for why the hidden sequence point was necessary?

Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs]: It was necessary because it precedes compiler-generated code that doesn't necessarily correspond to the user code of the immediately preceding IL.

**Comment by gafter** [comment]
FYI I was able to confirm the debugging experience in the IDE.

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a second review of this small debugging bug fix?

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a second review of this small debugging bug fix?

File: src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs [hunk 2]
```diff
@@ -3805,6 +3808,472 @@ .maxstack  1
 }");
         }
 
+        [Fact]
+        [WorkItem(31665, "https://github.com/dotnet/roslyn/issues/31665")]
+        public void TestQuestionableSequencePoints_31665()
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs]: >Questionable [](start = 24, length = 12)

Consider removing this qualifier from the test names, to avoid implying the expected sequence points are questionable.
