### PR TITLE
Make simplifier remove unneeded parentheses around `this` in cast

### LINKED ISSUE #12387: SyntaxGenerator adds unneeded parentheses, which the simplifier fails to remove
**Version Used**: 
master branch at d04f1d6a512f5586912a7badcecf486c3f955fa7

**Steps to Reproduce**:
See the test at https://github.com/dotnet/roslyn-analyzers/pull/1065/files#diff-164ec4d88a0027d1f1e7d87262201e18R163:
```csharp
(IEquatable<S>)(this)
```

Code that produces this:
```csharp
generator.CastExpression(
  equatableType.Construct(typeSymbol),
  generator.ThisExpression())
```

**Expected Behavior**:
The parentheses around `this`, which were added by the `SyntaxGenerator`, are later removed by the simplifier.

**Actual Behavior**:
The simplifier does not remove the parentheses around `this`.

### PR DESCRIPTION
**Pull request by bkoelman**
Fixes #12387

### CODE REVIEW

**Comment by mavasani** [comment]
Tagging @dotnet/roslyn-ide

**Comment by jmarolf** [comment]
test vsi please

File: src/EditorFeatures/Test2/Simplification/ParenthesisSimplificationTests.vb [hunk 1]
```diff
@@ -566,6 +566,52 @@ class foo
...
+    bool IEquatable&lt;C&gt;.Equals(C other)
+    {
+        return true;
+    }
+
+    public override bool Equals(object obj)
+    {
+        return ((IEquatable&lt;C&gt;){|Simplify:(this)|}).Equals(obj as C);
+    }
+}
```
Comment (DustinCampbell) [inline src/EditorFeatures/Test2/Simplification/ParenthesisSimplificationTests.vb]: It's a good idea to put code like this in `<![CDATA[` `]]>` tags so you don't have to escape the `<>`

File: src/Workspaces/CSharp/Portable/Extensions/ParenthesizedExpressionSyntaxExtensions.cs [hunk 2]
```diff
@@ -65,6 +65,12 @@ public static bool CanRemoveParentheses(this ParenthesizedExpressionSyntax node)
                 return true;
             }
 
+            // Case: (C)(this) -> (C)this
+            if (node.IsParentKind(SyntaxKind.CastExpression) && expression.IsKind(SyntaxKind.ThisExpression))
+            {
+                return true;
+            }
+
```
Comment (DustinCampbell) [inline src/Workspaces/CSharp/Portable/Extensions/ParenthesizedExpressionSyntaxExtensions.cs]: Minor: In general, I prefer expression-level simplification tests to occur after the ambiguity tests below. Today it shouldn't change any behavior, but if `RemovalMayIntroduceCastAmbiguity(...)` is updated for some future language feature, it could be a subtle ordering bug. Maybe move this check immediately after the ambiguity tests?

File: src/EditorFeatures/Test2/Simplification/ParenthesisSimplificationTests.vb (hunk 1 above)
Comment (bkoelman) [inline src/EditorFeatures/Test2/Simplification/ParenthesisSimplificationTests.vb]: Great suggestion. Thanks for review.

**Comment by bkoelman** [comment]
I've pushed to address review feedback. Running tests locally succeeded, but the p0...3 cibuilds failed. I have insufficient access to see why. Is anything needed from me to resolve those?

File: src/Workspaces/CSharp/Portable/Extensions/ParenthesizedExpressionSyntaxExtensions.cs (hunk 2 above)
Comment (bkoelman) [inline src/Workspaces/CSharp/Portable/Extensions/ParenthesizedExpressionSyntaxExtensions.cs]: Ok, I have moved the block.

**Comment by CyrusNajmabadi** [comment]
:+1:

**Comment by jmarolf** [comment]
microbuild failure is not caused by this PR.
test vsi please

**Comment by jmarolf** [comment]
@bkoelman I'll take a look at windows_vsi_p0-3 when they are done.  If they look good, once @DustinCampbell signs off, we'll merge this in.

**Comment by jmarolf** [comment]
tests timed out
retest vsi please

**Comment by DustinCampbell** [comment]
LGTM

**Comment by crummel** [comment]
Build triggered. sha1 is merged.

**Comment by jmarolf** [comment]
test windows_vsi_p0_open_prtest please
test windows_vsi_p2_open_prtest please

**Comment by jmarolf** [comment]
test microbuild_prtest please

**Comment by jmarolf** [comment]
test windows_vsi_p0_open_prtest please
