### PR TITLE
Don't copy a massive byte-array for fuzz testing

### LINKED ISSUE #6744: CSharp compiler Unit test FuzzTesting.TestBinary is flaky
I get intermittent `System.OutOfMemoryException` from this test.

```none
Test 'Microsoft.CodeAnalysis.CSharp.UnitTests.Parsing.FuzzTesting.TestBinary' failed: System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
	at System.Text.StringBuilder.ToString()
	Parsing\FuzzTesting.cs(94,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.Parsing.FuzzTesting.TestBinary()
```

### PR DESCRIPTION
**Pull request by TyOverby**
Closes #6744

### CODE REVIEW

File: src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs [hunk 1]
```diff
@@ -81,18 +81,25 @@ public void c024928()
 
         [WorkItem(2771, "https://github.com/dotnet/roslyn/issues/2771")]
         [Fact]
-        public void TestBinary()
+        public unsafe void TestBinary()
         {
             // use a fixed seed so the test is reproducible
             var random = new System.Random(12345);
```
Comment (jmarolf) [inline src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs]: Is System.Random sufficiently random to get interesting results? Is there a mathmatical justification for not using cryptographically random numbers?

File: src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs [hunk 2]
```diff
@@ -81,18 +81,25 @@ public void c024928()
...
-                builder.Append((char)random.Next(0xffff));
+                chars[i] = (char) random.Next(char.MaxValue);
+            }
+            chars[n - 1] = (char) 0;
+            unsafe
+            {
+                fixed (char* bytePtr = chars)
+                {
+                    var tree = CSharpSyntaxTree.ParseText(new string(bytePtr));
+                }
```
Comment (davkean) [inline src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs]: How does this avoid the copy? String.String(char*) still copies.

Comment (davkean) [inline src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs]: What you can do instead, is just create a string of the size you want, and then just wrap it in a fixed block and then directly modify the individual chars (evil but works). The C# compiler split makes sure that that the pointer you get back skips the object header and length.

Alternately, there's likely (assuming, because I'm not that familiar with the Roslyn code base) an incremental way to read data that doesn't result in the whole thing requiring to be in-memory.

File: src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs (hunk 1 above)
Comment (jmarolf) [inline src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs]: As an aside, how is this fuzz testing? we pass the same seed to the pseudo-random generator each time.  Why not use a better random number generator and report the seed in the event of test failure so a dev could reproduce it?

Comment (TyOverby) [inline src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs]: @jmarolf 

That's probably a good idea.  I'll make that change inside of this PR as well.

File: src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs (hunk 2 above)
Comment (TyOverby) [inline src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs]: Good catch.  For whatever reason, I thought that the pointer constructor made a "view" over the byte ptr.

I'm going to use the unsafe string mutation method.

File: src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs [hunk 3]
```diff
@@ -79,20 +79,42 @@ public void c024928()
...
-            var tree = CSharpSyntaxTree.ParseText(source);
+        }
+
+        [WorkItem(2771, "https://github.com/dotnet/roslyn/issues/2771")]
+        [Fact]
+        public void TestBinaryRandom()
+        {
+            // If this test fails, make a new test method that
+            // calls TestBinaryWithSeed with the seed that failed.
+            var seed = new System.Random().Next();
```
Comment (jmarolf) [inline src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs]: Might want to consider using [RNGCryptoServiceProvider ](https://msdn.microsoft.com/en-us/library/system.security.cryptography.rngcryptoserviceprovider(v=vs.110).aspx) as it will provide much better randomness over System.Random

Comment (TyOverby) [inline src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs]: Do we really need cryptographic randomness?  We are only running this once per build.  Seeding with the system clock should be more than sufficient.

**Comment by TyOverby** [comment]
test prtest/lin/dbg/unit32 please

**Comment by TyOverby** [comment]
@dotnet/roslyn-compiler @jaredpar Review please

File: src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs (hunk 3 above)
Comment (VSadov) [inline src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs]: I think with the clock seed it will be random enough.

**Comment by VSadov** [comment]
LGTM

File: src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs (hunk 3 above)
Comment (davkean) [inline src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs]: This bug had nothing to do with amount of randomness, it was just that there was a bug when we attempted to parse a binary file.

Comment (gafter) [inline src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs]: Please change the seed back to 12345 and consolidate these methods. This is not a fuzz test. It is testing a particular data set that caused specific problems. This is not intended to be a nondeterministic test.

Comment (jmarolf) [inline src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs]: Then can we rename this file to not be `FuzzTesting.cs` since it doesn't do fuzz testing?

**Comment by TyOverby** [comment]
@davkean Could you please re-review?  I incorporated your suggestion into the test.

**Comment by davkean** [comment]
:+1:

**Comment by davkean** [comment]
But make sure you see @gafter's comment above.

File: src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs (hunk 3 above)
Comment (TyOverby) [inline src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs]: How about `ParserRegressionTests`?

Comment (jmarolf) [inline src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs]: Sounds great to me, sorry for randomizing you over randomness :smile:

File: src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs [hunk 4]
```diff
@@ -79,20 +79,42 @@ public void c024928()
...
+                fixed(char* chars = str)
+                {
+                    for(int i = 0; i < n; i++)
+                    {
+                        chars[i] = (char)random.Next(char.MaxValue);
+                    }
+                }
+            }
+
+            try {
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Syntax/Parsing/FuzzTesting.cs]: Braces on new lines
