### PR TITLE
Don't offer to make local functions static if they use other local functions

### LINKED ISSUE #46858: IDE0062 false positive when a local function calls another non-static local function
**Version Used**: Visual Studio Version 16.8.0 Preview 1.0

**Steps to Reproduce**:

````c#
        public static void Main()
        {
            bool isValid = false;
            A();
            Console.WriteLine(isValid);

            // IDE0062 local function can be made static 
            // => static void A() is not valid because B is not static
            void A() => B();

            void B()
            {
                // B cannot be static as it use isValid
                isValid = true;
            }
        }
````

Look similar to #40259 but there is no struct parameter implied in this case. Feel free to close the issue if you consider this is a duplicate.

**Expected Behavior**: No diagnostic reported

**Actual Behavior**: diagnostic is reported

### PR DESCRIPTION
**Pull request by davidwengier**
Fixes #46858

DataFlowAnalysis already contained information about local functions that were called, but it wasn't available to be used, so this includes a public API change to add that. I couldn't see another way to do this, other than counting them as a Capture of `this` perhaps? Anyway, feedback appreciated!

### CODE REVIEW

File: src/Analyzers/CSharp/Tests/MakeLocalFunctionStatic/MakeLocalFunctionStaticTests.cs [hunk 1]
```diff
@@ -394,6 +395,71 @@ static int fibonacci(int n)
...
+
+        void B()
+        {
+        }
+    }
+}", parameters: new TestParameters(parseOptions: CSharp8ParseOptions));
+        }
+
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsMakeLocalFunctionStatic)]
+        public async Task TestCallingOtherLocalFunction()
```
Comment (davidwengier) [inline src/Analyzers/CSharp/Tests/MakeLocalFunctionStatic/MakeLocalFunctionStaticTests.cs:426]: This test just validates that existing behaviour wasn't broken so I didn't add the `WorkItem` attribute. Is that correct?

Also didn't add a test for the recursive case, as its already covered by another test in this class.

File: src/Features/CSharp/Portable/MakeLocalFunctionStatic/PassInCapturedVariablesAsArgumentsCodeFixProvider.cs [hunk 2]
```diff
@@ -101,8 +101,7 @@ protected override Task FixAllAsync(Document document, ImmutableArray<Diagnostic
 
             foreach (var localFunction in localFunctions)
             {
-
-                if (MakeLocalFunctionStaticHelper.TryGetCaputuredSymbolsAndCheckApplicability(localFunction, semanticModel, out var captures))
+                if (MakeLocalFunctionStaticHelper.CanMakeLocalFunctionStaticByRefactoringCaptures(localFunction, semanticModel, out var captures))
```
Comment (davidwengier) [inline src/Features/CSharp/Portable/MakeLocalFunctionStatic/PassInCapturedVariablesAsArgumentsCodeFixProvider.cs:104]: This fixer is only available on static local functions, so all of the existing tests already validate that nothing is broken.

File: src/Analyzers/CSharp/Analyzers/MakeLocalFunctionStatic/MakeLocalFunctionStaticHelper.cs [hunk 3]
```diff
@@ -26,11 +26,22 @@ public static bool TryGetCaputuredSymbols(LocalFunctionStatementSyntax localFunc
                 return false;
             }
 
+            // If other local functions area called the it can't be made static
+            // unless they themselves are static, or the local function is recursive
+            if (dataFlow.UsedLocalFunctions.Any(lf => !lf.IsStatic && lf.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax() != localFunction))
```
Comment (davkean) [inline src/Analyzers/CSharp/Analyzers/MakeLocalFunctionStatic/MakeLocalFunctionStaticHelper.cs:31]: That seems unrelated to actually getting captured symbols, no? Just because it calls a local function doesn't mean it doesn't have any captured symbols.

Comment (davidwengier) [reply src/Analyzers/CSharp/Analyzers/MakeLocalFunctionStatic/MakeLocalFunctionStaticHelper.cs:31]: You are correct, but thats why I made it private, so nothing outside the context of the various "Make Local Function Static" functions can call it. TryGetCapturedSymbolsIfCanBeMadeStatic seemed like an odd name to me, but happy to rename it if people think its confusing, or have better names.

**Comment by CyrusNajmabadi** [comment]
@davidwengier to me, it feels like these local functions should show up in the 'captured' group of the data-flow-analysis.  They are referenced within the anonymous functoin, and thus must be made available to it somehow.  I don't see why a local-function would be different here from any other sort of 'local' (i.e. true-locals, parameters, range variables).  Has that approach been considered and/or discussed with compiler?

**Comment by davidwengier** [comment]
@dotnet/roslyn-compiler can I get a review on this? It's an API surface change, but no functionality change (ie, the analysis was already happening)

File: src/Analyzers/CSharp/Analyzers/MakeLocalFunctionStatic/MakeLocalFunctionStaticHelper.cs [hunk 4]
```diff
@@ -17,23 +18,46 @@ internal static class MakeLocalFunctionStaticHelper
...
-            if (dataFlow is null)
+            dataFlow = semanticModel.AnalyzeDataFlow(localFunction);
+            return dataFlow is { Succeeded: true };
+        }
+
+        private static bool CanBeCalledFromStaticContext(LocalFunctionStatementSyntax localFunction, DataFlowAnalysis dataFlow)
+        {
+            // If other local functions are called the it can't be made static unles the
+            // are static, or the local function is recursive, or its calling a child local function
+            return !dataFlow.UsedLocalFunctions.Any(lf => !lf.IsStatic && !IsChildOrSelf(localFunction, lf));
```
Comment (333fred) [inline src/Analyzers/CSharp/Analyzers/MakeLocalFunctionStatic/MakeLocalFunctionStaticHelper.cs:31]: >lf => !lf.IsStatic && !IsChildOrSelf(localFunction, lf) [](start = 52, length = 55)

Could mark this lambda `static`

File: src/Compilers/CSharp/Portable/FlowAnalysis/CSharpDataFlowAnalysis.cs [hunk 5]
```diff
@@ -372,5 +389,10 @@ private static ImmutableArray<ISymbol> Normalize(IEnumerable<Symbol> data)
         {
             return ImmutableArray.CreateRange(data.Where(s => s.CanBeReferencedByName).OrderBy(s => s, LexicalOrderSymbolComparer.Instance).GetPublicSymbols());
         }
+
+        private static ImmutableArray<IMethodSymbol> Normalize(IEnumerable<MethodSymbol> data)
+        {
+            return ImmutableArray.CreateRange(data.Where(s => s.CanBeReferencedByName).OrderBy(s => s, LexicalOrderSymbolComparer.Instance).Select(p => p.GetPublicSymbol()));
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/FlowAnalysis/CSharpDataFlowAnalysis.cs:395]: >Select(p => p.GetPublicSymbol()) [](start = 140, length = 32)

There's a `GetPublicSymbols()` extension that can be used here.

File: src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs [hunk 6]
```diff
@@ -7650,5 +7650,393 @@ static void Main()
...
+            Assert.Null(GetSymbolNamesJoined(results.CapturedOutside));
+            Assert.Null(GetSymbolNamesJoined(results.VariablesDeclared));
+            Assert.Null(GetSymbolNamesJoined(results.DataFlowsOut));
+            Assert.Null(GetSymbolNamesJoined(results.DefinitelyAssignedOnEntry));
+            Assert.Null(GetSymbolNamesJoined(results.DefinitelyAssignedOnExit));
+            Assert.Null(GetSymbolNamesJoined(results.ReadInside));
+            Assert.Null(GetSymbolNamesJoined(results.WrittenInside));
+            Assert.Null(GetSymbolNamesJoined(results.ReadOutside));
+            Assert.Null(GetSymbolNamesJoined(results.WrittenOutside));
+            Assert.Equal("Local, Sub", GetSymbolNamesJoined(results.UsedLocalFunctions));
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs:8037]: This is a pretty good set of tests. I'd like to see a couple more around lambdas, though. Such as `() => Local()`, both when the lambda creation is in the bind section and when it's bound after that section. So, for example, this:
```cs
Action a = () => Local(); // And one where bind is just around this as well.
/*<bind>*/
a();
/*</bind>*/
```

**Comment by 333fred** [comment]
Done review pass (commit 10)

File: src/Analyzers/CSharp/Analyzers/MakeLocalFunctionStatic/MakeLocalFunctionStaticHelper.cs (hunk 4 above)
Comment (davidwengier) [reply src/Analyzers/CSharp/Analyzers/MakeLocalFunctionStatic/MakeLocalFunctionStaticHelper.cs:31]: Err, no I can't, it captures `localFunction`. Unless i'm misunderstanding?

File: src/Compilers/CSharp/Portable/FlowAnalysis/CSharpDataFlowAnalysis.cs (hunk 5 above)
Comment (davidwengier) [reply src/Compilers/CSharp/Portable/FlowAnalysis/CSharpDataFlowAnalysis.cs:395]: Only if I call `ToImmutableArray` after the `OrderBy`. Doesn't seem worth it to me, but I could be wrong...

**Comment by davidwengier** [comment]
Added some tests ¯\\\_(ツ)_/¯

File: src/Analyzers/CSharp/Analyzers/MakeLocalFunctionStatic/MakeLocalFunctionStaticHelper.cs (hunk 4 above)
Comment (333fred) [reply src/Analyzers/CSharp/Analyzers/MakeLocalFunctionStatic/MakeLocalFunctionStaticHelper.cs:31]: No, I missed that.

File: src/Compilers/CSharp/Portable/FlowAnalysis/CSharpDataFlowAnalysis.cs (hunk 5 above)
Comment (333fred) [reply src/Compilers/CSharp/Portable/FlowAnalysis/CSharpDataFlowAnalysis.cs:395]: It seems to work in the method right before this one :)

Comment (davidwengier) [reply src/Compilers/CSharp/Portable/FlowAnalysis/CSharpDataFlowAnalysis.cs:395]: As discussed, that is this, and its the only extension on IEnumerable. Happy to add another, I have no context on whether this scenario is a common one
https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Symbols/SymbolExtensions.cs#L661

**Review by 333fred — APPROVED** [review]
LGTM (commit 11). @gafter, can you review this as well?

**Comment by davidwengier** [comment]
Ping @dotnet/roslyn-compiler for a second approval and @dotnet/roslyn-ide for a first

File: src/Compilers/Core/Portable/Compilation/DataFlowAnalysis.cs [hunk 7]
```diff
@@ -100,6 +100,11 @@ public abstract class DataFlowAnalysis
         /// </summary>
         public abstract ImmutableArray<ISymbol> UnsafeAddressTaken { get; }
 
+        /// <summary>
+        /// The set of local functions that are called.
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/Compilation/DataFlowAnalysis.cs:104]: The member name is `used` but this comment says `called`. This is an important distinction because local functions can be used but not called. This occurs when doing method group to delegate conversions. 

```cs
void Outer() 
{
  void Inner() { } 
  Action local = Inner; // Used, not called
}
```

Should make this consistent.

File: src/EditorFeatures/CSharpTest/MakeLocalFunctionStatic/MakeLocalFunctionStaticRefactoringTests.cs [hunk 8]
```diff
@@ -476,6 +477,71 @@ static int AddLocal(int @static)
         }
     }  
 }",
+parseOptions: CSharp8ParseOptions);
+        }
+
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsMakeLocalFunctionStatic)]
+        [WorkItem(46858, "https://github.com/dotnet/roslyn/issues/46858")]
+        public async Task ShouldNotTriggerIfCallsOtherLocalFunction()
```
Comment (jaredpar) [inline src/EditorFeatures/CSharpTest/MakeLocalFunctionStatic/MakeLocalFunctionStaticRefactoringTests.cs:485]: Please add tests that cover local function to method group conversions.

**Review by jaredpar — APPROVED** [review]

**Review by jaredpar — APPROVED** [review]
