### PR TITLE
Fix #36060: Group Completion Providers using IsExclusive

### LINKED ISSUE #36060: OverrideCompletionProvider should allow items to be added
**Version Used**: 3.1.0-beta4-19261-04

Visual Studio for Mac has a _special_ behaviour that is specific to the way Xamarin/AppKit works. We offer the user "overrides" where they actually aren't overrides but _protocol member implementations_ (note: this is also _not_ an interface implementation but an Objective-C specific):

image

Picking `AddObserver` in the list above, would result in the following code being added:

```csharp
[Export("addObserver:forKeyPath:options:context:")]
public void AddObserver(NSObject observer, NSString keyPath, NSKeyValueObservingOptions options, IntPtr context)
{
    throw new System.NotImplementedException();
}
```

Recently, when moving away from [our old implementation of how we surface completion](http://source.monodevelop.com/#MonoDevelop.CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs,466) items, we discovered that we can no longer add items to the `override` list. The assumption is that [this](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/CompletionServiceWithProviders.cs,263) and [this](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/Providers/AbstractOverrideCompletionProvider.cs,35) are the culprits. 

We're happy to contribute the required change, but feel like it should be discussed first, to make sure we take the right approach. Here are some of the possible ones:

1) Add a way to register completion providers in a way where we un-register the existing one. That way we could derive from `OverrideCompletionProvider` and extend it with our required logic.
2) Enable `OverrideCompletionProvider` to also call down to _another_ set of MEF-provided providers, to retrieve additional items. 
3) Change [this](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/CompletionServiceWithProviders.cs,263) to take *all* contexts that had `IsExclusive` set to `true`. Potentially, there could be more metadata on the provider itself (i.e. a `Tag`) and we'd group exclusivity by the same tag as well).

Are we missing something obvious? Is any of the above options something that would be acceptable to PR?

### PR DESCRIPTION
**Pull request by avodovnik**
As per the discussion in #36060, this PR attempts to introduce the change that would allow a `CompletionProvider` to add items to the list, even if another one sets `IsExclusive`, like in the example of an `OverrideCompletionProvider`. This is partially only there to support a feature used by VS Mac.

~It's marked as a WIP as I'd still like to introduce a test for this, but want comments on the change as soon as possible to see if I should change direction.~

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Seems reasonable to me.  tagging @dpoeschl @ivanbasov see linked conversation for more details (including my thoughts on why i think this is probably the best of the potential options).

**Comment by CyrusNajmabadi** [comment]
Note: if we go this path, we'd certainly benefit from tests.  We should also update our docs to explain what's going on here.  But the design is 100% ok with me personally.

**Comment by avodovnik** [comment]
I’ve added a fairly simple, happy path, test. Have you got any suggestions on how else I could test this? Happy to also update the docs if needed, TBH.

File: src/EditorFeatures/Test2/IntelliSense/CompletionServiceTests_Exclusivitiy.vb [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+            Public Overrides ReadOnly Property Language As String
+                Get
+                    Return "NoCompilation"
+                End Get
+            End Property
+
+            Private Shared s_providers As ImmutableArray(Of CompletionProvider) = ImmutableArray.Create(Of CompletionProvider)(
+                New TestCompletionProviderWithMockExclusivity(False, CompletionServiceTests_Exclusivity.CompletionItemNonExclusive, 1),
+                New TestCompletionProviderWithMockExclusivity(True, CompletionServiceTests_Exclusivity.CompletionItemExclusive, 2),
+                New TestCompletionProviderWithMockExclusivity(True, CompletionServiceTests_Exclusivity.CompletionItemExclusive, 3))
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Test2/IntelliSense/CompletionServiceTests_Exclusivitiy.vb]: thanks for the test!

**Comment by CyrusNajmabadi** [comment]
> I’ve added a fairly simple, happy path, test. Have you got any suggestions on how else I could test this? 

The test is satisfactory to me :)

> Happy to also update the docs if needed, TBH.

Please do.  Right now this is in conflict with the specified text. 

--

@ivanbasov i'm not sure if the IDE has a compat meeting.  But this likely shoudl go through that (or a design meeting) before merging, just to make sure everyone is ok.  I doubt there is an issue. But as it is a chnage of design in a public API, we should be conscientious here.

**Comment by ivanbasov** [comment]
> @ivanbasov i'm not sure if the IDE has a compat meeting. But this likely shoudl go through that (or a design meeting) before merging, just to make sure everyone is ok. I doubt there is an issue. But as it is a chnage of design in a public API, we should be conscientious here.

Thank you, @CyrusNajmabadi ! I would say that the change is a fix for a corner case bug. The original design missed the case when more than 1 provider declared itself exclusive. Taking the first one was just a temporarily solution.

I understand and support the update to the design claiming that all providers declared themselves exclusive should be considered at the same level of exclusiveness.

If we would see that one providers may be more exclusive than other exclusive providers, we would re-consider this.

Adding @jasonmalinowski, @sharwell and @jinujoseph to see if they want to consider this change on a design meeting.

**Comment by abock** [comment]
Thank you for considering this! I just want to chime in and vote for this - without it, the user experience in VS Mac will regress in the Xamarin iOS workload with the new editor that we have ported from VS Windows, since we cannot feasibly shoehorn in protocol "overrides" at the editor level anymore.

**Comment by jasonmalinowski** [comment]
I'm also not sure this is worth discussing at today's design meeting. I'd vote to remove it from the agenda unless somebody else actually wants to discuss it. FYI to @sharwell.

**Comment by jasonmalinowski** [comment]
Thanks @avodovnik for the fix!

**Comment by CyrusNajmabadi** [comment]
Nice!  I'm glad we could make such a simple solution that solved your needs!

**Comment by jinujoseph** [comment]
Should be available in 16.2.Preview4 onwards
