### PR TITLE
Extensions: Compare accessibility of implementation method with accessibility of declared extension method

### LINKED ISSUE #81180: Internal extension property + InternalsVisibleTo triggers CS0570 (not supported by the language) in consumer assembly
**Version Used**: 

.NET 10 SDK (10.0.100)
Compiler version: '5.0.0-2.25523.111 (b0f34d51)'. Language version: 14.0

**Steps to Reproduce**:

Create a class library project and a console app referencing it:

```sh
> mkdir repro && cd repro
> mkdir ReproLib && pushd ReproLib && dotnet new classlib && popd
> mkdir TestConsumer && pushd TestConsumer && dotnet new console && dotnet add reference ../ReproLib && popd
```

Ref. https://learn.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-14.0/extensions#nullability-and-attributes edit `ReproLib/Class1.cs` and replace its content with:

```csharp
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("TestConsumer")]

namespace ReproLib;

internal static class Extensions {
    extension([NotNullWhen(false)] string? text) {
        internal bool IsEmpty => string.IsNullOrEmpty(text);
        internal bool IsWhitespace => string.IsNullOrWhiteSpace(text);
    }
}
```

This defines a couple of `internal` extension properties, but note also makes internals visible to the `TestConsumer` assembly.

Edit `TestConsumer/Program.cs` and replace its content with:

```csharp
using System.Diagnostics;

using ReproLib;

static class Program {
    static void Main() {
        Debug.Assert((null as string).IsEmpty);
        Debug.Assert("".IsEmpty);
        Debug.Assert("\t".IsEmpty is false);

        Debug.Assert((null as string).IsWhiteSpace);
        Debug.Assert("".IsWhiteSpace);
        Debug.Assert("\t".IsWhiteSpace);
    }
}
```

Build the `TestConsumer` project:

```sh
> cd TestConsumer && dotnet build
```

**Expected Behavior**:

The compilation to succeed since internal types and members were explicitly exposed to `TestConsumer`.

**Actual Behavior**:

Every use of internal extension properties defined in `ReproLib` is flagged with error CS0570 in `TestConsumer`:

```
Restore complete (0.2s)
  ReproLib net10.0 succeeded (0.9s) → ~/repro/ReproLib/bin/Debug/net10.0/ReproLib.dll
  TestConsumer net10.0 failed with 8 error(s) (0.1s)
    ~/repro/TestConsumer/Program.cs(9,39): error CS0570: 'Extensions.extension(string?).IsEmpty.get' is not supported by the language
    ~/repro/TestConsumer/Program.cs(10,25): error CS0570: 'Extensions.extension(string?).IsEmpty.get' is not supported by the language
    ~/repro/TestConsumer/Program.cs(11,27): error CS0570: 'Extensions.extension(string?).IsEmpty.get' is not supported by the language
    ~/repro/TestConsumer/Program.cs(13,39): error CS0570: 'Extensions.extension(string?).IsWhitespace.get' is not supported by the language
    ~/repro/TestConsumer/Program.cs(14,25): error CS0570: 'Extensions.extension(string?).IsWhitespace.get' is not supported by the language
    ~/repro/TestConsumer/Program.cs(15,27): error CS0570: 'Extensions.extension(string?).IsWhitespace.get' is not supported by the language
    ~/repro/TestConsumer/Program.cs(16,27): error CS0570: 'Extensions.extension(string?).IsWhitespace.get' is not supported by the language
```

This is unexpected; using classic extension methods here would compile without issue.

Is this a bug or a missing feature, or is C# 14 designed not to allow internal extension properties to be used from other assemblies despite `InternalsVisibleTo`?

### PR DESCRIPTION
**Pull request by AlekseyTs**
Due to an oversight it was compared to accessibility of extension block container, which is always `public`.

Fixes #81180

Relates to test plan https://github.com/dotnet/roslyn/issues/76130

### CODE REVIEW

File: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests2.cs [hunk 1]
```diff
@@ -36877,5 +36877,84 @@ static class E4
...
+        System.Console.Write(""\t"".IsEmpty);
+    }
+}
+";
+        var compB = CreateCompilation(sourceB, references: [compA.ToMetadataReference()], assemblyName: "B", options: TestOptions.DebugExe);
+        CompileAndVerify(compB, expectedOutput: "TrueTrueFalse").VerifyDiagnostics();
+
+        compB = CreateCompilation(sourceB, references: [compA.EmitToImageReference()], assemblyName: "B", options: TestOptions.DebugExe);
+        CompileAndVerify(compB, expectedOutput: "TrueTrueFalse").VerifyDiagnostics();
+        _ = ErrorCode.ERR_BindToBogus;
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests2.cs]: Probably was meant to be deleted

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests2.cs]: > Probably was meant to be deleted

Yes, thanks!

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests2.cs]:
```suggestion
```

**Comment by AlekseyTs** [comment]
@jjonescz, @dotnet/roslyn-compiler For a second review
