### PR TITLE
Codemodel should return only Namespace when asked for CodeNamespace

### LINKED ISSUE #1923: EnvDTE.CodeClass.Namespace causes exception for nested classes
See MS Connect bug opened by Patrick Smacchia:

https://connect.microsoft.com/VisualStudio/feedback/details/1238355/envdte-codetype-namespace-throws-invalidoperationexception-for-nested-type

Steps to reproduce the problem:

1) Create a VB.NET package with this command handler:

   Protected Overrides Sub Initialize()
      MyBase.Initialize()

      ' Add our command handlers for menu (commands must exist in the .vsct file)
      Dim mcs As OleMenuCommandService = TryCast(GetService(GetType(IMenuCommandService)), OleMenuCommandService)
      If Not mcs Is Nothing Then
         ' Create the command for the menu item.
         Dim menuCommandID As New CommandID(GuidList.guidVSPackage1CmdSet, CInt(PkgCmdIDList.cmdidMyCommand))
         Dim menuItem As New MenuCommand(New EventHandler(AddressOf MenuItemCallback), menuCommandID)
         mcs.AddCommand(menuItem)
      End If
   End Sub

   Private Sub MenuItemCallback(ByVal sender As Object, ByVal e As EventArgs)

      Dim dte As EnvDTE.DTE

      dte = CType(MyBase.GetService(GetType(EnvDTE.DTE)), EnvDTE.DTE)

      ShowCodeElements(dte.ActiveDocument.ProjectItem.FileCodeModel.CodeElements)

   End Sub

   Sub ShowCodeElements(codeElements As EnvDTE.CodeElements)

      Dim codeClass As EnvDTE.CodeClass
      Dim codeNamespace As EnvDTE.CodeNamespace

      For Each codeElement As EnvDTE.CodeElement In codeElements

         Select Case codeElement.Kind

            Case EnvDTE.vsCMElement.vsCMElementNamespace

               codeNamespace = CType(codeElement, EnvDTE.CodeNamespace)
               ShowCodeElements(codeNamespace.Members)

            Case EnvDTE.vsCMElement.vsCMElementClass

               codeClass = CType(codeElement, EnvDTE.CodeClass)

               Try
                  codeNamespace = codeClass.Namespace
               Catch ex As Exception
                  System.Windows.Forms.MessageBox.Show(ex.ToString())
               End Try

               ShowCodeElements(codeClass.Members)

         End Select

      Next

   End Sub

2) Run the package and in the second VS instance, create a C# Class Library with this code in Class1.cs:

namespace ClassLibrary1
{
    public class Class1
    {
        public class Class11
        {
        }
    }
}

3) Click the Tools > My Command Name menu.

The following exception happens when retrieving the namespace of the nested Class11 class: System.InvalidOperationException: Operation is not valid due to the current state of the object

### PR DESCRIPTION
**Pull request by basoundr**
Fix #1923 AbstractCodeType should return only a namespace when asked for
a CodeNamespace but not a Type

### CODE REVIEW

**Comment by basoundr** [comment]
Reviewers: @Pilchie @DustinCampbell @jasonmalinowski 
Other Reviewers: @dpoeschl @rchande @balajikris @brettfo

File: src/VisualStudio/Core/Test/CodeModel/AbstractCodeElementTests`1.vb [hunk 1]
```diff
@@ -151,6 +151,10 @@ Namespace Microsoft.VisualStudio.LanguageServices.UnitTests.CodeModel
         Protected MustOverride Function GetName(codeElement As TCodeElement) As String
         Protected MustOverride Function GetNameSetter(codeElement As TCodeElement) As Action(Of String)
 
+        Protected Overridable Function GetNamespace(codeElement As TCodeElement) As EnvDTE.CodeNamespace
```
Comment (Pilchie) [inline src/VisualStudio/Core/Test/CodeModel/AbstractCodeElementTests`1.vb]: Does this add anything over just using `codeElement.Namespace` directly?

File: src/VisualStudio/Core/Impl/CodeModel/InternalElements/AbstractCodeType.cs [hunk 2]
```diff
@@ -123,7 +130,7 @@ public EnvDTE.CodeNamespace Namespace
         {
             get
             {
-                var namespaceNode = GetNamespaceOrTypeNode();
```
Comment (Pilchie) [inline src/VisualStudio/Core/Impl/CodeModel/InternalElements/AbstractCodeType.cs]: It looks like nothing else uses `GetNamespaceOrTypeNode()`.  Remove it?

**Comment by Pilchie** [comment]
:+1: with slight changes for feedback

File: src/VisualStudio/Core/Impl/CodeModel/InternalElements/AbstractCodeType.cs (hunk 2 above)
Comment (basoundr) [inline src/VisualStudio/Core/Impl/CodeModel/InternalElements/AbstractCodeType.cs]: [This](http://index/Microsoft.VisualStudio.LanguageServices.Implementation/R/6965f7e8fbf3f951.html) uses `GetNamespaceOrTypeNode()`

File: src/VisualStudio/Core/Test/CodeModel/AbstractCodeElementTests`1.vb (hunk 1 above)
Comment (basoundr) [inline src/VisualStudio/Core/Test/CodeModel/AbstractCodeElementTests`1.vb]: `Namespace` is an `EnvDTE80.CodeClass2` property but not `CodeElement` property.

Comment (Pilchie) [inline src/VisualStudio/Core/Test/CodeModel/AbstractCodeElementTests`1.vb]: Ah, now I see the pattern.

File: src/VisualStudio/Core/Impl/CodeModel/InternalElements/AbstractCodeType.cs (hunk 2 above)
Comment (Pilchie) [inline src/VisualStudio/Core/Impl/CodeModel/InternalElements/AbstractCodeType.cs]: Should probably use links on http://source.roslyn.io here, but oh, of course.  I even went and looked there and misinterpreted the results.  :blush:
