### PR TITLE
Collection expressions: handle missing cases for ref struct collections in HasLocalScope

### LINKED ISSUE #70638: Exception in `RefSafetyAnalysis` with nested collection initializer of `ref struct` type
**Version Used**: VS 17.8 Preview 5

**Steps to Reproduce**:
Paste this code into an editor:

```csharp
internal ref struct S : IEnumerable
{
    public void M()
    {
        S x = [[]];
    }

    public void Add(params S[] x) => throw null;

    public IEnumerator GetEnumerator() => throw null;
}
```

**Expected Behavior**: No exception.

**Actual Behavior**:
```
System.InvalidOperationException: Unexpected value 'ImplementsIEnumerable' of type 'Microsoft.CodeAnalysis.CSharp.CollectionExpressionTypeKind'
      at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.HasLocalScope(BoundCollectionExpression expr)
      at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.GetValEscape(BoundExpression expr, UInt32 scopeOfTheContainingExpression)
      at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.VisitLocalDeclaration(BoundLocalDeclaration node)
      at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitList[T](ImmutableArray`1 list)
      at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitBlock(BoundBlock node)
      at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.VisitBlock(BoundBlock node)
      at Microsoft.CodeAnalysis.CSharp.BoundTreeWalker.VisitNonConstructorMethodBody(BoundNonConstructorMethodBody node)
      at Microsoft.CodeAnalysis.CSharp.RefSafetyAnalysis.Analyze(CSharpCompilation compilation, MethodSymbol symbol, BoundNode node, BindingDiagnosticBag diagnostics)
      at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, BindingDiagnosticBag diagnostics, Boolean includeInitializersInBody, BoundNode initializersBody, Boolean reportNullableDiagnostics, ImportChain& importChain, Boolean& originalBodyNested, Boolean& prependedDefaultValueTypeConstructorInitializer, InitialState& forSemanticModel)
      at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
      at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
      at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass25_0.<CompileNamedTypeAsync>b__0()
      at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   --- End of stack trace from previous location ---
      at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
      at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.CSharp.MethodCompiler.WaitForWorkers()
      at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean emittingPdb, Boolean hasDeclarationErrors, Boolean emitMethodBodies, BindingDiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.<GetDiagnosticsForMethodBodiesInTree>g__compileMethodBodiesAndDocComments|226_0(SyntaxTree filterTree, Nullable`1 filterSpan, BindingDiagnosticBag bindingDiagnostics, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForMethodBodiesInTree(SyntaxTree tree, Nullable`1 span, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForSyntaxTree(CompilationStage stage, SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Boolean includeEarlierStages, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDiagnostics(Nullable`1 span, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<GetCompilationEventsForSingleFileAnalysis>g__generateCompilationEvents|64_0(Compilation compilation, AnalysisScope analysisScope, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.GetCompilationEventsForSingleFileAnalysis(Compilation compilation, AnalysisScope analysisScope, ImmutableArray`1 additionalFiles, Boolean hasAnyActionsRequiringCompilationEvents, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.ComputeAnalyzerDiagnosticsAsync(AnalysisScope analysisScope, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.GetAnalysisResultCoreAsync(SemanticModel model, Nullable`1 filterSpan, ImmutableArray`1 analyzers, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.Extensions.GetAnalysisResultAsync(CompilationWithAnalyzers compilationWithAnalyzers, DocumentAnalysisScope documentAnalysisScope, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Diagnostics.Extensions.GetAnalysisResultAsync(CompilationWithAnalyzers compilationWithAnalyzers, DocumentAnalysisScope documentAnalysisScope, Project project, DiagnosticAnalyzerInfoCache analyzerInfoCache, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.AnalyzeAsync(CompilationWithAnalyzers compilationWithAnalyzers, BidirectionalMap`2 analyzerToIdMap, ImmutableArray`1 analyzers, SkippedHostAnalyzersInfo skippedAnalyzersInfo, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.GetDiagnosticsAsync(IEnumerable`1 analyzerIds, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.Diagnostics.DiagnosticComputer.GetNormalPriorityDiagnosticsAsync(IEnumerable`1 analyzerIds, Boolean reportSuppressedDiagnostics, Boolean logPerformanceInfo, Boolean getTelemetryInfo, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.<>c__DisplayClass4_0.<<CalculateDiagnosticsAsync>b__0>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass9_0`1.<<RunWithSolutionAsync>g__ProcessSolutionAsync|1>d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Int32 workspaceVersion, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteDiagnosticAnalyzerService.CalculateDiagnosticsAsync(Checksum solutionChecksum, DiagnosticArguments arguments, CancellationToken cancellationToken)

```

### PR DESCRIPTION
**Pull request by cston**
Fixes #70638

### CODE REVIEW

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs [hunk 1]
```diff
@@ -22687,6 +22687,118 @@ .locals init (<>y__InlineArray1<int> V_0)
...
+            string sourceB = """
+                using System.Collections.Immutable;
+                class Program
+                {
+                    static ImmutableArray<int> F() => [1, 2, 3];
+                }
+                """;
+            var comp = CreateCompilation(new[] { sourceA, sourceB }, targetFramework: TargetFramework.Net80);
+            comp.VerifyEmitDiagnostics(
+                // 0.cs(7,31): warning CS0436: The type 'ImmutableArray' in '0.cs' conflicts with the imported type 'ImmutableArray' in 'System.Collections.Immutable, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Using the type defined in '0.cs'.
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:22785]: Is the CS0436 warning relevant to this test? If not can we consider suppressing it so we see the diagnostics that we're actually trying to enforce here

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs [hunk 2]
```diff
@@ -22687,6 +22687,118 @@ .locals init (<>y__InlineArray1<int> V_0)
...
+                // 1.cs(4,12): warning CS0436: The type 'ImmutableArray<T>' in '0.cs' conflicts with the imported type 'ImmutableArray<T>' in 'System.Collections.Immutable, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Using the type defined in '0.cs'.
+                //     static ImmutableArray<int> F() => [1, 2, 3];
+                Diagnostic(ErrorCode.WRN_SameFullNameThisAggAgg, "ImmutableArray<int>").WithArguments("0.cs", "System.Collections.Immutable.ImmutableArray<T>", "System.Collections.Immutable, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", "System.Collections.Immutable.ImmutableArray<T>").WithLocation(4, 12),
+                // 1.cs(4,39): error CS9203: A collection expression of type 'ImmutableArray<int>' cannot be used in this context because it may be exposed outside of the current scope.
+                //     static ImmutableArray<int> F() => [1, 2, 3];
+                Diagnostic(ErrorCode.ERR_CollectionExpressionEscape, "[1, 2, 3]").WithArguments("System.Collections.Immutable.ImmutableArray<int>").WithLocation(4, 39));
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:22799]: I'm confused why this is illegal. The value `[1, 2, 3]` converts to `ReadOnlySpan<int>` here but that is returnable because it's using the RVA optimization. Effectively this is legal

```csharp
ReadOnlySpan<int> M() {
  ReadOnlySpan<int> span = [1, 2, 3];
  return span;
}
```

Given that I would expect that the result of `ImmutableArray.Create([1, 2, 3])` also be returnable.

**Review by jaredpar — APPROVED** [review]

**Review by 333fred — APPROVED** [review]

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:22799]: I think if the ImmutableArray case in HasLocalScope were grouped with the CollectionBuilder case, then the expected behavior would probably happen.

FWIW, I also feel completely fine with saying: you defined ImmutableArray as a ref struct? Ok, bad inconvenient things will happen, although the compiler won't outright crash.

Comment (cston) [reply src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:22799]: `CollectionBuilderMethod` is only set for `CollectionExpressionTypeKind.CollectionBuilder` case so if we group `ImmutableArray` with that case in `HasLocalScope`, we'll consider the builder method as invalid and treat the expression as local scope always.
