### PR TITLE
Fix for InvalidCastException when passing lambda with incorrect number of parameters

### LINKED ISSUE #29333: VisualBasicAddParameterCheckCodeRefactoringProvider exception & InfoBar when passing a lambda with incorrect number of parameters
Impacts both `VisualBasicAddParameterCheckCodeRefactoringProvider` and `VisualBasicInitializeMemberFromParameterCodeRefactoringProvider`

This is particularly painful/common because it occurs in the process of typing a valid invocation in which you're passing a lambda.

```VB
Class C
    Sub M(a As Action(Of Integer, Integer))
        $$
    End Sub
End Class
```

Delete the $$, and at that location we'll type an invocation of `M`. Type the following (you can allow brace completion to add the close parens or not, either way repros):
    
```VB
        M(Sub(x
```

Now the lambda being passed has too few parameters for the `Action(Of Integer, Integer)` being expected. This causes the InfoBar with this exception:

```text
System.InvalidCastException : Unable to cast object of type 'LazyNoneOperation' to type 'Microsoft.CodeAnalysis.Operations.IBlockOperation'.
   at Microsoft.CodeAnalysis.VisualBasic.InitializeParameter.InitializeParameterHelpers.GetBlockOperation(SyntaxNode functionDeclaration,SemanticModel semanticModel,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.VisualBasic.InitializeParameter.VisualBasicAddParameterCheckCodeRefactoringProvider.GetBlockOperation(SyntaxNode functionDeclaration,SemanticModel semanticModel,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.InitializeParameter.AbstractInitializeParameterCodeRefactoringProvider`3.ComputeRefactoringsAsync[TParameterSyntax,TStatementSyntax,TExpressionSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Notes:
- Never seems to repro when the lambda has 0 parameters
- Once the lambda has > 0 parameters, it seems to happen any time there's a parameter count mismatch

### PR DESCRIPTION
**Pull request by chborl**
Fixes #29333 

Affects both AddParameterCheckCodeRefactoringProvider and InitializeMemberFromParameterCodeRefactoringProvider

- VB fixed and test added
- C# made more robust, even though I haven't been able to repro it in C#.  Any test case ideas?
- In VB, used TypeOf to check before casting. In C#, used OperationKind to check before casting.  Will these behave similarly?

### CODE REVIEW

File: src/Features/CSharp/Portable/InitializeParameter/InitializeParameterHelpers.cs [hunk 1]
```diff
@@ -19,18 +19,30 @@ public static bool IsFunctionDeclaration(SyntaxNode node)
...
 
-        public static IBlockOperation GetBlockOperation(SyntaxNode functionDeclaration, SemanticModel semanticModel, CancellationToken cancellationToken)
+        public static bool TryGetBlockOperation(SyntaxNode functionDeclaration, SemanticModel semanticModel, CancellationToken cancellationToken, out IBlockOperation blockOperation)
         {
             var bodyOpt = GetBody(functionDeclaration);
             if (bodyOpt == null)
             {
-                return null;
+                blockOperation = null;
+                return true;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InitializeParameter/InitializeParameterHelpers.cs]: "TryX" is returning null *and* true?  that's really inconsistent with all other uses of this pattern.

File: src/Features/CSharp/Portable/InitializeParameter/InitializeParameterHelpers.cs [hunk 2]
```diff
@@ -19,18 +19,30 @@ public static bool IsFunctionDeclaration(SyntaxNode node)
...
+            {
+                blockOperation = ((IAnonymousFunctionOperation)semanticModel.GetOperation(functionDeclaration, cancellationToken)).Body;
+                return true;
+            }
+
+            if (semanticModel.GetOperation(bodyOpt, cancellationToken).Kind == OperationKind.Block)
+            {
+                blockOperation = (IBlockOperation)semanticModel.GetOperation(bodyOpt, cancellationToken);
+                return true;
+            }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InitializeParameter/InitializeParameterHelpers.cs]: let's not call GetOperation redundantly :)   Instead of getting the operation, checking the kind, then getting the operation again, please call and store and use that value (this applied to both blocks).

File: src/Features/Core/Portable/InitializeParameter/AbstractInitializeParameterCodeRefactoringProvider.cs [hunk 3]
```diff
@@ -101,12 +101,15 @@ public override async Task ComputeRefactoringsAsync(CodeRefactoringContext conte
             // We support initializing parameters, even when the containing member doesn't have a
             // body. This is useful for when the user is typing a new constructor and hasn't written
             // the body yet.
-            var blockStatementOpt = GetBlockOperation(functionDeclaration, semanticModel, cancellationToken);
-          
+            if (!TryGetBlockOperation(functionDeclaration, semanticModel, cancellationToken, out var blockOperation))
+            {
+                return;
+            };
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/InitializeParameter/AbstractInitializeParameterCodeRefactoringProvider.cs]: 1. based on how you changed TryGetBlockOperation, blockOperation should still be called 'opt' since you can return null for it.
2. superfluous semicolon after the if-statement.

File: src/Features/CSharp/Portable/InitializeParameter/InitializeParameterHelpers.cs [hunk 4]
```diff
@@ -19,18 +19,30 @@ public static bool IsFunctionDeclaration(SyntaxNode node)
             || node is LocalFunctionStatementSyntax
             || node is AnonymousFunctionExpressionSyntax;
 
-        public static IBlockOperation GetBlockOperation(SyntaxNode functionDeclaration, SemanticModel semanticModel, CancellationToken cancellationToken)
+        public static bool TryGetBlockOperation(SyntaxNode functionDeclaration, SemanticModel semanticModel, CancellationToken cancellationToken, out IBlockOperation blockOperation)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/InitializeParameter/InitializeParameterHelpers.cs]: this is the c# code, but i can't see any updated C# tests.

File: src/Features/VisualBasic/Portable/InitializeParameter/InitializeParameterHelpers.vb [hunk 5]
```diff
@@ -15,9 +15,13 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.InitializeParameter
 
         Public Shared Function GetBlockOperation(functionDeclaration As SyntaxNode, semanticModel As SemanticModel, cancellationToken As CancellationToken) As IBlockOperation
             Dim operation = semanticModel.GetOperation(functionDeclaration, cancellationToken)
-            Return If(TypeOf operation Is IAnonymousFunctionOperation,
-                DirectCast(operation, IAnonymousFunctionOperation).Body,
-                DirectCast(operation, IBlockOperation))
+            If TypeOf operation Is IAnonymousFunctionOperation Then
+                Return DirectCast(operation, IAnonymousFunctionOperation).Body
+            ElseIf TypeOf operation Is IBlockOperation Then
+                Return DirectCast(operation, IBlockOperation)
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/InitializeParameter/InitializeParameterHelpers.vb]: instead of typeof+directcast, you can do TryCast+null check.  but this is minor nit.  in practice this shouldn't be that impactful.

File: src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicInitializeMemberFromParameterCodeRefactoringProvider.vb [hunk 6]
```diff
@@ -29,8 +29,9 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.InitializeParameter
             Return InitializeParameterHelpers.TryGetLastStatement(blockStatement)
         End Function
 
-        Protected Overrides Function GetBlockOperation(functionDeclaration As SyntaxNode, semanticModel As SemanticModel, cancellationToken As CancellationToken) As IBlockOperation
-            Return InitializeParameterHelpers.GetBlockOperation(functionDeclaration, semanticModel, cancellationToken)
+        Protected Overrides Function TryGetBlockOperation(functionDeclaration As SyntaxNode, semanticModel As SemanticModel, cancellationToken As CancellationToken, ByRef blockOperation As IBlockOperation) As Boolean
+            blockOperation = InitializeParameterHelpers.GetBlockOperation(functionDeclaration, semanticModel, cancellationToken)
+            Return blockOperation IsNot Nothing
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicInitializeMemberFromParameterCodeRefactoringProvider.vb]: i don't like that C# and VB are starting to diverge between impls.

Comment (chborl) [reply src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicInitializeMemberFromParameterCodeRefactoringProvider.vb]: Yeah, this one was tricky because C# still offers the refactoring even if the block is null.  So in order to distinguish between "null, but go ahead and refactor" and "null, don't refactor" I added the boolean.  VB didn't need this distinction, but I added the boolean to keep them in sync.  

Since I wasn't able to repro this in C# (thus no test was added) perhaps I should just do a simpler fix for VB and leave C# alone.

File: src/Features/VisualBasic/Portable/InitializeParameter/InitializeParameterHelpers.vb (hunk 5 above)
Comment (mavasani) [reply src/Features/VisualBasic/Portable/InitializeParameter/InitializeParameterHelpers.vb]: You can even consider a switch statement based on `OperationKind` and then direct cast to corresponding operation.

File: src/Features/VisualBasic/Portable/InitializeParameter/InitializeParameterHelpers.vb [hunk 7]
```diff
@@ -15,9 +15,13 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.InitializeParameter
 
         Public Shared Function GetBlockOperation(functionDeclaration As SyntaxNode, semanticModel As SemanticModel, cancellationToken As CancellationToken) As IBlockOperation
```
Comment (mavasani) [inline src/Features/VisualBasic/Portable/InitializeParameter/InitializeParameterHelpers.vb]: Should the signature of this method also be changed to follow `TryGet` pattern as it can return `Nothing`?

File: src/Features/CSharp/Portable/InitializeParameter/InitializeParameterHelpers.cs (hunk 1 above)
Comment (mavasani) [reply src/Features/CSharp/Portable/InitializeParameter/InitializeParameterHelpers.cs]: I agree this is very confusing.

File: src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicInitializeMemberFromParameterCodeRefactoringProvider.vb (hunk 6 above)
Comment (CyrusNajmabadi) [reply src/Features/VisualBasic/Portable/InitializeParameter/VisualBasicInitializeMemberFromParameterCodeRefactoringProvider.vb]: Yes please :)

**Comment by chborl** [comment]
@CyrusNajmabadi  and @mavasani  for review.

File: src/Features/VisualBasic/Portable/InitializeParameter/InitializeParameterHelpers.vb [hunk 8]
```diff
@@ -13,11 +13,20 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.InitializeParameter
...
+
+        Public Shared Function GetBlockOperation(functionDeclaration As SyntaxNode, semanticModel As SemanticModel, operation As IOperation, cancellationToken As CancellationToken) As IBlockOperation
+            Select Case operation.Kind
+                Case OperationKind.AnonymousFunction
+                    Return DirectCast(operation, IAnonymousFunctionOperation).Body
+                Case OperationKind.Block
+                    Return DirectCast(operation, IBlockOperation)
+                Case Else
+                    ' if previously checked with CanOfferRefactoring, this case won't happen
+                    Return Nothing
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/InitializeParameter/InitializeParameterHelpers.vb]: if something can't happen, you shoudl throw.  I recomment ExceptionUtilities.Unreachable

**Comment by chborl** [comment]
@dotnet-bot retest

**Comment by Neme12** [comment]
@chborl I'm sorry, I think this bug was introduced by my PR.

**Comment by chborl** [comment]
@Neme12 , no problem!  We'll have it fixed up soon :)

**Comment by chborl** [comment]
@CyrusNajmabadi  and @mavasani , tests are mostly passing now.  Can you take a look at the latest iteration?

File: src/Features/CSharp/Portable/InitializeParameter/InitializeParameterHelpers.cs [hunk 9]
```diff
@@ -19,7 +19,10 @@ public static bool IsFunctionDeclaration(SyntaxNode node)
             || node is LocalFunctionStatementSyntax
             || node is AnonymousFunctionExpressionSyntax;
 
-        public static IBlockOperation GetBlockOperation(SyntaxNode functionDeclaration, SemanticModel semanticModel, CancellationToken cancellationToken)
+        public static bool CanOfferRefactoring(SyntaxNode functionDeclaration, IOperation operation)
```
Comment (mavasani) [inline src/Features/CSharp/Portable/InitializeParameter/InitializeParameterHelpers.cs]: You can remove this static method.

File: src/Features/VisualBasic/Portable/InitializeParameter/InitializeParameterHelpers.vb [hunk 10]
```diff
@@ -13,11 +13,20 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.InitializeParameter
                    TypeOf node Is LambdaExpressionSyntax
         End Function
 
-        Public Shared Function GetBlockOperation(functionDeclaration As SyntaxNode, semanticModel As SemanticModel, cancellationToken As CancellationToken) As IBlockOperation
-            Dim operation = semanticModel.GetOperation(functionDeclaration, cancellationToken)
-            Return If(TypeOf operation Is IAnonymousFunctionOperation,
-                DirectCast(operation, IAnonymousFunctionOperation).Body,
-                DirectCast(operation, IBlockOperation))
+        Public Shared Function CanOfferRefactoring(functionDeclaration As SyntaxNode, operation As IOperation) As Boolean
+            Return operation.Kind = OperationKind.AnonymousFunction Or operation.Kind = OperationKind.Block
```
Comment (mavasani) [inline src/Features/VisualBasic/Portable/InitializeParameter/InitializeParameterHelpers.vb]: Syntax node is unused, so seems the API is language agnostic. Can you instead move this code directly into `AbstractInitializeParameterCodeRefactoringProvider.cs`?

File: src/Features/CSharp/Portable/InitializeParameter/InitializeParameterHelpers.cs [hunk 11]
```diff
@@ -29,7 +32,7 @@ public static IBlockOperation GetBlockOperation(SyntaxNode functionDeclaration,
 
             // body might be an expression in a lambda - in that case we wouldn't get a block operation out of that
             return functionDeclaration is AnonymousFunctionExpressionSyntax
-                ? ((IAnonymousFunctionOperation)semanticModel.GetOperation(functionDeclaration, cancellationToken)).Body
+                ? ((IAnonymousFunctionOperation)operation).Body
                 : (IBlockOperation)semanticModel.GetOperation(bodyOpt, cancellationToken);
```
Comment (mavasani) [inline src/Features/CSharp/Portable/InitializeParameter/InitializeParameterHelpers.cs]: I am not sure we should directly cast to `IBlockOperation` based on syntax here.

File: src/EditorFeatures/VisualBasicTest/InitializeParameter/AddParameterCheckTests.vb [hunk 12]
```diff
@@ -488,5 +488,17 @@ class C
...
+        <Fact, Trait(Traits.Feature, Traits.Features.CodeActionsInitializeParameter)>
+        Public Async Function TestLambdaWithIncorrectNumberOfParameters() As Task
+            Await TestMissingInRegularAndScriptAsync(
+"
+Class C
+    Sub M(a As Action(Of Integer, Integer))
+        M(Sub(x[||]
+    End Sub
+End Class")
+        End Function
```
Comment (Neme12) [inline src/EditorFeatures/VisualBasicTest/InitializeParameter/AddParameterCheckTests.vb]: I think it would be nice to have a similar test for C# as well, even though it doesn't crash now. It's a nice addition to test that the refactoring doesn't break on incorrect code.

**Comment by chborl** [comment]
@mavasani, @CyrusNajmabadi, @Neme12, want to take another look?

**Comment by genlu** [comment]
Hmm, not sure what happened, GitHub went ballistic after I sync'd the branch with master.

**Comment by genlu** [comment]
Ping @mavasani @CyrusNajmabadi

**Comment by genlu** [comment]
Ping @mavasani @CyrusNajmabadi

**Comment by genlu** [comment]
@jinujoseph @vatsalyaagrawal for approval

**Comment by genlu** [comment]
Merged. Thanks @chborl :)
