### PR TITLE
Fix goto types to include records

### LINKED ISSUE #51672: "Go to all" and "Go to types" don't work for records
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Go-to-all-and-Go-to-types-dont-work/1252528?preview=true)._

---
[severity:It bothers me. A fix would be nice]
If I declare a record type, and enter the type's name in "Go to all" or "Go to types", it isn't found.

---
#### Feedback Bot on 11/11/2020, 11:36 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Maryer Ma [MSFT] on 11/12/2020, 02:22 AM: 

<p>Thank you for your feedback! Based on your description so far, we were unable to reproduce it on 16.8.0. If we misunderstood your question, could you please correct us? In order to investigate your issue further, can you help to confirm several questions?</p>
<ol>
<li>Which project type and language you use?</li>
<li>Are you installed other extensions in your machine? (Such as Resharper? Could you try to uninstall other extensions and then check whether your issue also reproduces or not?)</li>
<li>Can you try to create a new simple solution(C# Console App or C++ Console App) and check if your problem also reproduces?</li>
<li>Can you try to reset all VS settings(Navigate to Tools-&gt; Import and Export Settings, then select ‘Reset all settings’) or repair your VS and then check whether your problem also reproduces or not?</li>
<li>Can you please provide more info with your issue (Detail repro steps, simply project or repro video)?<br>
Please feel free to let us know if you have any doubt. We look forward to hearing from you!</li>
</ol>

#### Thomas LEVESQUE on 11/12/2020, 06:24 AM: 

<ol>
<li>.NET 5.0 , C#. Project type doesn’t seem to matter (I noticed it in an <a target='_blank' href="http://ASP.NET">ASP.NET</a> Core app, but also reproduced it in a console app)</li>
<li>Just what came out of the box (fresh install).</li>
<li>Yes, I reproduce it in a new solution.</li>
<li>Like I said, it’s a fresh install. And I saw it on 2 different machines, so I don’t think it’s an installation issue.</li>
<li>See attached solution (<a target='_blank' href="https://aka.ms/dc/file?name=B3a147c2bf4674ec5b5c0bb648e9a6b7b637407876528640092_ConsoleApp1.zip&amp;tid=3a147c2bf4674ec5b5c0bb648e9a6b7b637407876528640092">ConsoleApp1.zip</a>). There is a <code>PersonClass</code> class and a <code>PersonRecord</code> record. If you open Go to all, and type <code>t Person</code>, only <code>PersonClass</code> appears, not <code>PersonRecord</code></li>
</ol>

#### Maryer Ma [MSFT] on 11/17/2020, 00:23 AM: 

<p>@<a target='_blank' href="https://developercommunity2.visualstudio.com/users/49178/ThomasLEVESQUE.html">Thomas LEVESQUE</a><br>
Thank you for replied. We tried the attached solution you provided, and found there is only one type ( PersonClass ) in the solution, so it only can search the one. It’s expected behavior. If we misunderstood your question, could you please correct us?  Please feel free to let us know if you have any doubt. We look forward to hearing from you!<br>
</p>
<p></p>

#### Thomas LEVESQUE on 11/19/2020, 01:09 AM: 

<p><a target='_blank' href="https://aka.ms/dc/u?aid=265364">Maryer Ma [MSFT]</a></p>
<blockquote>
<p>We tried the attached solution you provided, and found there is only one type ( PersonClass ) in the solution, so it only can search the one</p>
</blockquote>
<p>PersonRecord is also a type. <a target='_blank' href="https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#record-types">Record types are a new feature in C# 9</a>.<br>
The fact that it appears as a method in the solution explorer is also a bug (probably related)</p>

#### Feedback Bot on 11/25/2020, 06:52 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/30/2020, 04:01 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### microsoft on 1/14/2021, 08:57 AM: 

<p>PLEASE fix this. This is really annoying. I am using the CQRS architecture and I use command classes for every action. These are implemented with the new C# record features, but when I use CTRL-T and enter the command name (= record name), I can't find them anymore. This is very confusing!</p>

#### Feedback Bot on 2/19/2021, 10:06 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

#### Daniel Berghold on 3/3/2021, 08:57 AM: 

<p>Dear Microsoft, this bug is also causing a lot of confusion in our team! Team members are using CTRL-T to jump to DTOs or command objects but can’t find them and are confused therefore… Please consider fixing it.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by Youssef1313**
image

Fixes #51672

@jcouv FYI for record structs work.

### CODE REVIEW

File: src/Tools/ExternalAccess/FSharp/NavigateTo/FSharpNavigateToItemKind.cs [hunk 1]
```diff
@@ -13,7 +13,6 @@ internal static class FSharpNavigateToItemKind
         public static string Line => NavigateToItemKind.Line;
         public static string File = NavigateToItemKind.File;
         public static string Class => NavigateToItemKind.Class;
-        public static string Record => NavigateToItemKind.Record;
```
Comment (Youssef1313) [inline src/Tools/ExternalAccess/FSharp/NavigateTo/FSharpNavigateToItemKind.cs:16]: This is unfortunately external access, but it won't break FSharp since this isn't used on their end.

https://github.com/dotnet/fsharp/blob/d823b21a549b6c4dacf749f404e4db829844b3dd/vsintegration/src/FSharp.Editor/Navigation/NavigateToSearchService.fs#L118-L129

File: src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.InProcess.cs [hunk 2]
```diff
@@ -288,8 +288,6 @@ private static string GetItemKind(DeclaredSymbolInfo declaredSymbolInfo)
             {
                 case DeclaredSymbolInfoKind.Class:
                     return NavigateToItemKind.Class;
-                case DeclaredSymbolInfoKind.Record:
-                    return NavigateToItemKind.Record;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/NavigateTo/AbstractNavigateToSearchService.InProcess.cs:292]: i'm a little confused how this works.  if you remove this entry, and we do run into a record, won't we crash in this switch?

File: src/Workspaces/CSharp/Portable/FindSymbols/CSharpDeclaredSymbolInfoFactoryService.cs [hunk 3]
```diff
@@ -179,7 +179,7 @@ public override bool TryGetDeclaredSymbolInfo(StringTable stringTable, SyntaxNod
                         node.Kind() switch
                         {
                             SyntaxKind.ClassDeclaration => DeclaredSymbolInfoKind.Class,
-                            SyntaxKind.RecordDeclaration => DeclaredSymbolInfoKind.Record,
+                            SyntaxKind.RecordDeclaration => DeclaredSymbolInfoKind.Class,
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/FindSymbols/CSharpDeclaredSymbolInfoFactoryService.cs:182]: so i liek the old way this worked.  DeclaredSymbolInfoKind is roslyn specific, so it can represent Record here.  What i think we should do though i just map this to `Class` at the boundaries of NavTo.

Comment (Youssef1313) [reply src/Workspaces/CSharp/Portable/FindSymbols/CSharpDeclaredSymbolInfoFactoryService.cs:182]: @CyrusNajmabadi The current approach is more simpler. Just treat records as classes (and later, record structs as structs). *Especially* that we don't need any special handling for records. But let me know if you still think otherwise.

Comment (CyrusNajmabadi) [reply src/Workspaces/CSharp/Portable/FindSymbols/CSharpDeclaredSymbolInfoFactoryService.cs:182]: Yeah. I don't like it. Within roslyn itself, I think we should represent fully. Just at it boundaries would we marshall differently

**Comment by Youssef1313** [comment]
@CyrusNajmabadi I addressed your feedback.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
thanks!
