### PR TITLE
Suggest stackalloc keyword in Span legal places

### LINKED ISSUE #23584: Span<T> stackalloc IntelliSense
**Version Used**: 

VS 15.5.0

**Steps to Reproduce**:

1. type `Span<byte> s = stac`...
2. Ctrl + Space

**Expected Behavior**:

C# 7.2 introduce safe `stackalloc` with the `Span<T>` struct. So `stackalloc` keyword should be listed in the IntelliSense window.

**Actual Behavior**:

image

### PR DESCRIPTION
**Pull request by OmarTawfik**
### Customer scenario

C# 7.2 introduce safe stackalloc with the Span<T> struct. So stackalloc keyword should be listed in the IntelliSense window. The completion provider suggests other types/keywords (ex: `StackOverflowException`).

### Code this fixes:

image

### Bugs this fixes

Fixes #23584

### Workarounds, if any

None.

### Risk

Low. This is suggesting an additional keyword. Tests were added.

### Performance impact

Minimal.

### Is this a regression from a previous update?

No.

### Root cause analysis

Was not implemented yet in 7.2.

### How was the bug found?

Customer reported on github.

### Test documentation updated?

--

### CODE REVIEW

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs [hunk 1]
```diff
@@ -16,20 +16,41 @@ public StackAllocKeywordRecommender()
 
         protected override bool IsValidContext(int position, CSharpSyntaxContext context, CancellationToken cancellationToken)
         {
-            // type t = |
-            var token = context.TargetToken;
-            if (token.IsUnsafeContext())
+            var node = context.TargetToken.Parent;
+
+            if (node == null)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: can't happen.

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs [hunk 2]
```diff
@@ -16,20 +16,41 @@ public StackAllocKeywordRecommender()
...
+            {
+                return false;
+            }
+
+            if (node.IsKind(SyntaxKind.ParenthesizedExpression) || node.IsKind(SyntaxKind.CastExpression))
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: these feel weird.  in cases like this i would prefer that the token also be checked.  i.e. that you're on hte '(' or hte ')'.

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs [hunk 3]
```diff
@@ -16,20 +16,41 @@ public StackAllocKeywordRecommender()
...
+            }
+
+            while (node.IsKind(SyntaxKind.ConditionalExpression))
+            {
+                node = node.Parent;
+            }
+
+            if (node.IsKind(SyntaxKind.SimpleAssignmentExpression))
+            {
+                return node.Parent.IsKind(SyntaxKind.ExpressionStatement);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: so you can always do "a = stackalloc" now?

File: src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs [hunk 4]
```diff
@@ -124,12 +90,99 @@ unsafe static void Main(string[] args)
...
-            await VerifyAbsenceAsync(
+            await VerifyKeywordAsync(
 @"class C
 {
     unsafe static void Main(string[] args)
     {
         for (string i = $$");
         }
+
+        [WorkItem(23584, "https://github.com/dotnet/roslyn/issues/23584")]
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs]: something is super odd about thsi dif.. it looks like a test method is inside test code.

File: src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs [hunk 5]
```diff
@@ -124,12 +90,99 @@ unsafe static void Main(string[] args)
         [Fact, Trait(Traits.Feature, Traits.Features.KeywordRecommending)]
         public async Task TestInsideForStatementVarDecl3()
         {
-            await VerifyAbsenceAsync(
+            await VerifyKeywordAsync(
 @"class C
 {
     unsafe static void Main(string[] args)
     {
         for (string i = $$");
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs]: stackallow is legal here now??

File: src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs [hunk 6]
```diff
@@ -124,12 +90,99 @@ unsafe static void Main(string[] args)
...
+
+        [WorkItem(23584, "https://github.com/dotnet/roslyn/issues/23584")]
+        [Fact, Trait(Traits.Feature, Traits.Features.KeywordRecommending)]
+        public async Task TestOnRHSWithCast()
+        {
+            await VerifyKeywordAsync(AddInsideMethod(@"
+var s = (Span<char>)$$"));
+
+            await VerifyKeywordAsync(AddInsideMethod(@"
+s = (Span<char>)$$"));
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs]: code should validate that TargetToken is the close paren and only walk up in that case.

File: src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs [hunk 7]
```diff
@@ -124,12 +90,99 @@ unsafe static void Main(string[] args)
...
+        }
+
+        [WorkItem(23584, "https://github.com/dotnet/roslyn/issues/23584")]
+        [Fact, Trait(Traits.Feature, Traits.Features.KeywordRecommending)]
+        public async Task TestOnRHSWithConditionalExpression_True()
+        {
+            await VerifyKeywordAsync(AddInsideMethod(@"
+var s = value ? $$"));
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs]: hrmm.. how did this fall

File: src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs [hunk 8]
```diff
@@ -124,12 +90,99 @@ unsafe static void Main(string[] args)
...
+
+        [WorkItem(23584, "https://github.com/dotnet/roslyn/issues/23584")]
+        [Fact, Trait(Traits.Feature, Traits.Features.KeywordRecommending)]
+        public async Task TestOnRHSWithConditionalExpression_False_WithCast()
+        {
+            await VerifyKeywordAsync(AddInsideMethod(@"
+var s = value ? stackalloc int[10] : (Span<int>)$$"));
+
+            await VerifyKeywordAsync(AddInsideMethod(@"
+s = value ? stackalloc int[10] : (Span<int>)$$"));
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs]: need test of nested conditionals.

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs [hunk 9]
```diff
@@ -16,20 +16,41 @@ public StackAllocKeywordRecommender()
...
+            {
+                return false;
+            }
+
+            if (node.IsKind(SyntaxKind.ParenthesizedExpression) || node.IsKind(SyntaxKind.CastExpression))
+            {
+                node = node.Parent;
+            }
+
+            while (node.IsKind(SyntaxKind.ConditionalExpression))
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: should only do this if the would prefer this only happen if you were on the ? or :

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs (hunk 3 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: would prefer this only happen if you were on the =.

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs (hunk 1 above)
Comment (OmarTawfik) [reply src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: It can. Check `TestNotAtRoot_Interactive`. There won't be anything parsed in an empty string to have a token or a node.

---
In reply to: [155677699](https://github.com/dotnet/roslyn/pull/23655#discussion_r155677699) [](ancestors = 155677699)

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs (hunk 3 above)
Comment (OmarTawfik) [reply src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: Yes.

---
In reply to: [155677871](https://github.com/dotnet/roslyn/pull/23655#discussion_r155677871) [](ancestors = 155677871)

Comment (OmarTawfik) [reply src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: It might be nested inside other nodes, like casts or conditionals.

---
In reply to: [155678306](https://github.com/dotnet/roslyn/pull/23655#discussion_r155678306) [](ancestors = 155678306)

File: src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs (hunk 4 above)
Comment (OmarTawfik) [reply src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs]: Test string ends on line 98. Curly bracket on line 99 closes the test method :)

---
In reply to: [155677980](https://github.com/dotnet/roslyn/pull/23655#discussion_r155677980) [](ancestors = 155677980)

File: src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs (hunk 5 above)
Comment (OmarTawfik) [reply src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs]: It is enabled for all initialization statements.

---
In reply to: [155678006](https://github.com/dotnet/roslyn/pull/23655#discussion_r155678006) [](ancestors = 155678006)

Comment (OmarTawfik) [reply src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs]: This code is legal:
`for(Span<int> x = stackalloc int [10]; ;) {}`

---
In reply to: [155944492](https://github.com/dotnet/roslyn/pull/23655#discussion_r155944492) [](ancestors = 155944492,155678006)

File: src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs (hunk 7 above)
Comment (OmarTawfik) [reply src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs]: I don't understand the question?

---
In reply to: [155678159](https://github.com/dotnet/roslyn/pull/23655#discussion_r155678159) [](ancestors = 155678159)

**Comment by OmarTawfik** [comment]
@CyrusNajmabadi comments addressed.
cc @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
Reviewing again.

File: src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs [hunk 10]
```diff
@@ -54,40 +54,6 @@ public class StackAllocKeywordRecommenderTests : KeywordRecommenderTests
 @"$$"));
         }
 
-        [Fact, Trait(Traits.Feature, Traits.Features.KeywordRecommending)]
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs]: please don't remove tests.  just update what they expect to see.

File: src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs [hunk 11]
```diff
@@ -54,40 +54,6 @@ public class StackAllocKeywordRecommenderTests : KeywordRecommenderTests
...
-        public async Task TestNotInEmptySpace()
-        {
-            await VerifyAbsenceAsync(AddInsideMethod(
-@"var v = $$"));
-        }
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs]: so this test would become "TestInEmptySpace() { ... }".

File: src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs (hunk 7 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest2/Recommendations/StackAllocKeywordRecommenderTests.cs]: yeah, i don't know what this was referring to :-/

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs [hunk 12]
```diff
@@ -16,20 +16,48 @@ public StackAllocKeywordRecommender()
 
         protected override bool IsValidContext(int position, CSharpSyntaxContext context, CancellationToken cancellationToken)
         {
-            // type t = |
-            var token = context.TargetToken;
-            if (token.IsUnsafeContext())
+            var node = context.TargetToken.Parent;
+
+            // In case of an empty string
+            if (node == null)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: i think it's safer to say "When at start of file".

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs [hunk 13]
```diff
@@ -16,20 +16,48 @@ public StackAllocKeywordRecommender()
...
+            {
+                return false;
+            }
+
+            // After a cast
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: "After a cast or parenthesized expression.  i.e.:   (Span<int>)stackalloc ..."

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs [hunk 14]
```diff
@@ -16,20 +16,48 @@ public StackAllocKeywordRecommender()
...
+            if (context.TargetToken.IsKind(SyntaxKind.CloseParenToken) &&
+                (node.IsKind(SyntaxKind.ParenthesizedExpression) || node.IsKind(SyntaxKind.CastExpression)))
+            {
+                node = node.Parent;
+            }
+
+            // Inside a conditional expression: value ? stackalloc : stackalloc
+            while (node.IsKind(SyntaxKind.ConditionalExpression) &&
+                (context.TargetToken.IsKind(SyntaxKind.CloseParenToken) || context.TargetToken.IsKind(SyntaxKind.QuestionToken) || context.TargetToken.IsKind(SyntaxKind.ColonToken)))
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: i don't understand the close paren case.

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs [hunk 15]
```diff
@@ -16,20 +16,48 @@ public StackAllocKeywordRecommender()
...
+            {
+                node = node.Parent;
+            }
+
+            // assignment: x = stackalloc
+            if (node.IsKind(SyntaxKind.SimpleAssignmentExpression))
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: should check that you're after the = just to be paranoid.

Also, please add test that you don't get stackalloc here:

```x $$ = ```

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs [hunk 16]
```diff
@@ -16,20 +16,48 @@ public StackAllocKeywordRecommender()
...
-                    if (variableDeclaration.IsParentKind(SyntaxKind.LocalDeclarationStatement) ||
-                        variableDeclaration.IsParentKind(SyntaxKind.ForStatement))
+                    node = node.Parent;
+
+                    if (node.IsKind(SyntaxKind.VariableDeclaration))
                     {
-                        return variableDeclaration.Type.IsVar || variableDeclaration.Type.IsKind(SyntaxKind.PointerType);
+                        node = node.Parent;
+
+                        return node.IsKind(SyntaxKind.LocalDeclarationStatement) || node.IsKind(SyntaxKind.ForStatement);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: 'var' is also allowed in a using.  I'm guessing we don't allow stackalloc there though because it would not be disposable?

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs (hunk 14 above)
Comment (OmarTawfik) [reply src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: For cases like ` value ? (Span<int>stackalloc`
For things like this, we don't actually create the `WhenTrue` and `WhenFalse` nodes of the conditional yet.

---
In reply to: [156192660](https://github.com/dotnet/roslyn/pull/23655#discussion_r156192660) [](ancestors = 156192660)

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs (hunk 15 above)
Comment (OmarTawfik) [reply src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: We might not be after equal. We might be nested inside a conditional or a cast :)
The root node has to be an assignment, but not necessarily the direct parent.

---
In reply to: [156192877](https://github.com/dotnet/roslyn/pull/23655#discussion_r156192877) [](ancestors = 156192877)

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs (hunk 16 above)
Comment (OmarTawfik) [reply src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: That's true.

---
In reply to: [156193066](https://github.com/dotnet/roslyn/pull/23655#discussion_r156193066) [](ancestors = 156193066)

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs (hunk 14 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: Do you mean ```value ? (Span<int>)stackalloc``` ?

If so, it's not clear to me why this isn't handled with this code:

```
if (context.TargetToken.IsKind(SyntaxKind.CloseParenToken) &&
 +                (node.IsKind(SyntaxKind.ParenthesizedExpression) || node.IsKind(SyntaxKind.CastExpression)))
```

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs (hunk 15 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: This should then validate that you're on the right side of the equal.

Basically, your'e validating yourself against a certain shape of the tree and the position of the user.  We need to make sure that that shape is tight and doesn't allow for other cases like this.

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs [hunk 17]
```diff
@@ -16,20 +16,48 @@ public StackAllocKeywordRecommender()
 
         protected override bool IsValidContext(int position, CSharpSyntaxContext context, CancellationToken cancellationToken)
         {
-            // type t = |
-            var token = context.TargetToken;
-            if (token.IsUnsafeContext())
+            var node = context.TargetToken.Parent;
+
+            // When in an empty string
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: Needs to eb changed.  this sounds like "if the user has ```var v = "$$"```.  We want to say "start of file" as "empty string" is really ambiguous.

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs (hunk 14 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: So, the best way to write this would be: 

1. if the target token is the ? or : of a ternay then the node should be the ternary
2. As long as we're the expression of a cast, or the true/false side of a ternary, walk upwards.
3. finally, see if we're on the right of an assignment or variable decl.

**Comment by OmarTawfik** [comment]
@dotnet-bot test ubuntu_14_debug_prtest

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs (hunk 15 above)
Comment (OmarTawfik) [reply src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: I already have tests for that. Check `TestNotInLHSOfAssignment`. Basically, on RHS, the root node is not either `SimpleAssignmentExpression` or `EqualsValueClause`, but a `VariableDeclaratorSyntax`.

---
In reply to: [156214811](https://github.com/dotnet/roslyn/pull/23655#discussion_r156214811) [](ancestors = 156214811)

File: src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs (hunk 14 above)
Comment (OmarTawfik) [reply src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: This is not handled by the above condition because getting the node parent `node = node.Parent` doesn't move the `context.TargetToken`. It is still pointing to the cast node.

---
In reply to: [156214413](https://github.com/dotnet/roslyn/pull/23655#discussion_r156214413) [](ancestors = 156214413)

Comment (OmarTawfik) [reply src/Features/CSharp/Portable/Completion/KeywordRecommenders/StackAllocKeywordRecommender.cs]: This is exactly what the existing code is doing, with a small change to # 2 to allow nesting. What is the scenario/code example that you think is different here?

---
In reply to: [156215691](https://github.com/dotnet/roslyn/pull/23655#discussion_r156215691) [](ancestors = 156215691)

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-ide can I get a second review?

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-ide can I get a second review?

**Comment by OmarTawfik** [comment]
@dotnet-bot test ubuntu_16_mono_debug_prtest

**Comment by OmarTawfik** [comment]
cc @sharwell @jasonmalinowski

**Comment by tannergooding** [comment]
Should we have a threshold on the upper bounds for the size of the array we are suggesting?

Stack space is not unlimited and certain sizes may fail at runtime for varying architectures especially as the size of the underlying array increases.

**Comment by jasonmalinowski** [comment]
@tannergooding The keyword recommender is not a place for such logic. This just ensures you can type the keyword in the first place.

**Comment by jasonmalinowski** [comment]
(and even then, you won't have typed the size prior to the stackalloc keyword...)

**Comment by OmarTawfik** [comment]
@jaredpar for ask mode approval.

**Comment by OmarTawfik** [comment]
@jinujoseph  @jaredpar for ask mode approval.

**Comment by jinujoseph** [comment]
@Pilchie for ask mode approval
