### PR TITLE
Remove pending notifications from SolutionEventMonitor

### LINKED ISSUE #1136: Assertion failed in Microsoft.CodeAnalysis.Notification.GlobalOperationNotificationService.Done
Memory dump:

%internal_share%\public\tomat\Bugs\1136

Stack trace:

```
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.Contract.ThrowIfFalse(bool condition, string message) Line 86	C#
>	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Notification.GlobalOperationNotificationService.Done(Microsoft.CodeAnalysis.Notification.GlobalOperationRegistration registration) Line 140	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Notification.GlobalOperationRegistration.Dispose() Line 30	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.SolutionEventMonitor.TryCancelPendingNotification(string operation) Line 78	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.SolutionEventMonitor.ContextChangedWorker(Microsoft.VisualStudio.Shell.UIContextChangedEventArgs e, string operation) Line 64	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.SolutionEventMonitor.SolutionBuildingContextChanged(object sender, Microsoft.VisualStudio.Shell.UIContextChangedEventArgs e) Line 49	C#
 	Microsoft.VisualStudio.Shell.14.0.dll!Microsoft.VisualStudio.Shell.UIContext.OnActivated(bool activated) Line 107	C#
 	Microsoft.VisualStudio.Shell.14.0.dll!Microsoft.VisualStudio.Shell.UIContextImpl.OnCmdUIContextChanged(uint dwCmdUICookie, int fActive) Line 82	C#

```

### PR DESCRIPTION
**Pull request by rchande**
If we do not remove pending notifications when we cancel them, we may
try to cancel them twice.

Fixes #1136.

### CODE REVIEW

**Comment by rchande** [comment]
Can you take a look @heejaechang ?

**Comment by rchande** [comment]
Other reviewers: @Pilchie @jasonmalinowski @dpoeschl @balajikris @basoundr @brettfo

**Comment by jasonmalinowski** [comment]
Is it possible to write tests for this? Given it's in the VS layer, I can understand if it's a nightmare.

**Comment by Pilchie** [comment]
:+1: (also, what @jasonmalinowski said :smile: )

File: src/VisualStudio/Core/Def/SolutionEventMonitor.cs [hunk 1]
```diff
@@ -76,6 +76,7 @@ private void TryCancelPendingNotification(string operation)
             {
                 globalOperation.Done();
                 globalOperation.Dispose();
+                _operations.Remove(operation);
```
Comment (heejaechang) [inline src/VisualStudio/Core/Def/SolutionEventMonitor.cs]: !!!

**Comment by heejaechang** [comment]
:+1:

**Comment by rchande** [comment]
@jasonmalinowski @Pilchie I tried writing some tests but found too deep in a forest of Mocks.

**Comment by heejaechang** [comment]
@jasonmalinowski @Pilchie @rchande this one uses static type KnownUIContext from VS, probably not easy to write any test outside of VS.
