### PR TITLE
More fixes for IOperation tree.

### LINKED ISSUE #23004: System.NullReferenceException is thrown by CSharpOperationFactory.DeriveArguments for erroneous ElementAccessExpression
```
        [Fact]
        [CompilerTrait(CompilerFeature.IOperation)]
        public void CS0856ERR_IndexedPropertyRequiresParams01()
        {
            var source1 =
@"Imports System
Imports System.Runtime.InteropServices
<Assembly: PrimaryInteropAssembly(0, 0)> 
<Assembly: Guid(""165F752D-E9C4-4F7E-B0D0-CDFD7A36E210"")> 
<ComImport()>
<Guid(""165F752D-E9C4-4F7E-B0D0-CDFD7A36E211"")>
Public Interface I
    Property P(x As Object, Optional y As Object = Nothing) As Object
    Property P(Optional x As Integer = 1, Optional y As Integer = 2) As Object
    Property Q(Optional x As Integer = 1, Optional y As Integer = 2) As Object
    Property Q(x As Object, Optional y As Object = Nothing) As Object
    Property R(x As Integer, y As Integer, Optional z As Integer = 3) As Object
    Property S(ParamArray args As Integer()) As Object
End Interface";
            var reference1 = BasicCompilationUtils.CompileToMetadata(source1);
            var source2 =
@"class C
{
    static void M(I i)
    {
        object o;
        o = i.P; // CS0856 (Dev11)
        o = i.Q;
        i.R = o; // CS0856
        i.R[1] = o; // CS1501
        o = i.S; // CS0856 (Dev11)
        i.S = o; // CS0856 (Dev11)
    }
}";
            var compilation2 = CreateStandardCompilation(source2, new[] { reference1 });
            compilation2.VerifyDiagnostics(
                // (8,9): error CS0856: Indexed property 'I.R' has non-optional arguments which must be provided
                Diagnostic(ErrorCode.ERR_IndexedPropertyRequiresParams, "i.R").WithArguments("I.R").WithLocation(8, 9),
                // (9,9): error CS7036: There is no argument given that corresponds to the required formal parameter 'y' of 'I.R[int, int, int]'
                Diagnostic(ErrorCode.ERR_NoCorrespondingArgument, "i.R[1]").WithArguments("y", "I.R[int, int, int]").WithLocation(9, 9));

            var tree = compilation2.SyntaxTrees.Single();
            var node = tree.GetRoot().DescendantNodes().OfType<ElementAccessExpressionSyntax>().First();

            Assert.Equal("i.R[1]", node.ToString());

            compilation2.VerifyOperationTree(node, expectedOperationTree:
@"
");
        }
```

System.NullReferenceException: 'Object reference not set to an instance of an object.'

binder was null.

```
Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.LocalRewriter.GetDefaultParameterValue(Microsoft.CodeAnalysis.SyntaxNode syntax, Microsoft.CodeAnalysis.CSharp.Symbols.ParameterSymbol parameter, Microsoft.CodeAnalysis.ThreeState enableCallerInfo, Microsoft.CodeAnalysis.CSharp.LocalRewriter localRewriter, Microsoft.CodeAnalysis.CSharp.Binder binder, Microsoft.CodeAnalysis.DiagnosticBag diagnostics) Line 1231	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.LocalRewriter.AppendMissingOptionalArguments(Microsoft.CodeAnalysis.Operations.CSharpOperationFactory operationFactory, Microsoft.CodeAnalysis.SyntaxNode syntax, Microsoft.CodeAnalysis.CSharp.Symbol methodOrIndexer, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol optionalParametersMethod, bool expanded, Microsoft.CodeAnalysis.CSharp.Binder binder, Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder<Microsoft.CodeAnalysis.CSharp.Symbols.ParameterSymbol> missingParameters, Microsoft.CodeAnalysis.PooledObjects.ArrayBuilder<Microsoft.CodeAnalysis.Operations.IArgumentOperation> argumentsBuilder) Line 1124	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.LocalRewriter.BuildArgumentsInEvaluationOrder(Microsoft.CodeAnalysis.Operations.CSharpOperationFactory operationFactory, Microsoft.CodeAnalysis.SyntaxNode syntax, Microsoft.CodeAnalysis.CSharp.Symbol methodOrIndexer, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol optionalParametersMethod, bool expanded, System.Collections.Immutable.ImmutableArray<int> argsToParamsOpt, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.BoundExpression> arguments, Microsoft.CodeAnalysis.CSharp.Binder binder) Line 799	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.LocalRewriter.MakeArgumentsInEvaluationOrder(Microsoft.CodeAnalysis.Operations.CSharpOperationFactory operationFactory, Microsoft.CodeAnalysis.CSharp.Binder binder, Microsoft.CodeAnalysis.SyntaxNode syntax, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.BoundExpression> arguments, Microsoft.CodeAnalysis.CSharp.Symbol methodOrIndexer, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol optionalParametersMethod, bool expanded, System.Collections.Immutable.ImmutableArray<int> argsToParamsOpt, bool invokedAsExtensionMethod) Line 595	C#	Symbols loaded.
>	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.DeriveArguments(Microsoft.CodeAnalysis.CSharp.BoundNode boundNode, Microsoft.CodeAnalysis.CSharp.Binder binder, Microsoft.CodeAnalysis.CSharp.Symbol methodOrIndexer, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol optionalParametersMethod, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.BoundExpression> boundArguments, System.Collections.Immutable.ImmutableArray<string> argumentNamesOpt, System.Collections.Immutable.ImmutableArray<int> argumentsToParametersOpt, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.RefKind> argumentRefKindsOpt, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Symbols.ParameterSymbol> parameters, bool expanded, Microsoft.CodeAnalysis.SyntaxNode invocationSyntax, bool invokedAsExtensionMethod) Line 137	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundIndexerAccessOperation.AnonymousMethod__1() Line 412	C#	Symbols loaded.
 	[External Code]		Annotated Frame
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Operations.LazyPropertyReferenceExpression.ArgumentsImpl.get() Line 4181	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Operations.BasePropertyReferenceExpression.Arguments.get() Line 4129	C#	Symbols loaded.
 	Roslyn.Test.Utilities.dll!Microsoft.CodeAnalysis.Test.Utilities.OperationTreeVerifier.VisitPropertyReference(Microsoft.CodeAnalysis.Operations.IPropertyReferenceOperation operation) Line 834	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Operations.LazyPropertyReferenceExpression.Accept(Microsoft.CodeAnalysis.Operations.OperationVisitor visitor) Line 4185	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Operations.OperationWalker.Visit(Microsoft.CodeAnalysis.IOperation operation) Line 36	C#	Symbols loaded.
 	Roslyn.Test.Utilities.dll!Microsoft.CodeAnalysis.Test.Utilities.OperationTreeVerifier.Visit(Microsoft.CodeAnalysis.IOperation operation) Line 266	C#	Symbols loaded.
 	Roslyn.Test.Utilities.dll!Microsoft.CodeAnalysis.Test.Utilities.OperationTreeVerifier.GetOperationTree(Microsoft.CodeAnalysis.Compilation compilation, Microsoft.CodeAnalysis.IOperation operation, int initialIndent) Line 51	C#	Symbols loaded.
 	Roslyn.Test.Utilities.dll!Microsoft.CodeAnalysis.Test.Utilities.CompilationExtensions.AppendOperationTree(Microsoft.CodeAnalysis.SemanticModel model, Microsoft.CodeAnalysis.SyntaxNode node, System.Text.StringBuilder actualTextBuilder, int initialIndent) Line 231	C#	Symbols loaded.
 	Roslyn.Test.Utilities.dll!Microsoft.CodeAnalysis.Test.Utilities.CompilationExtensions.VerifyOperationTree(Microsoft.CodeAnalysis.Compilation compilation, Microsoft.CodeAnalysis.SyntaxNode node, string expectedOperationTree) Line 163	C#	Symbols loaded.
 	Roslyn.Compilers.CSharp.Semantic.UnitTests.dll!Microsoft.CodeAnalysis.CSharp.UnitTests.SemanticErrorTests.CS0856ERR_IndexedPropertyRequiresParams01() Line 12550	C#	Symbols loaded.
```

### LINKED ISSUE #23009: The same IOperation node is used in two places in the tree for a conditional access in an error case.
```
        [Fact]
        [CompilerTrait(CompilerFeature.IOperation)]
        public void ConditionalElementAccess001()
        {
            var text = @"
class Program
{
    public int P1
    {
        set { }
    }

    public void V() 
    { 
        var x6 = base?.ToString();
    }

    static void Main(string[] args)
    {
        var x = 123 ?[1,2];

        var p = new Program();
        var x1 = p.P1 ?[1,2];
        var x2 = p.V() ?[1,2];
        var x3 = p.V ?[1,2];
        var x4 = ()=> { return 1; } ?[1,2];

        var x5 = null?.ToString();
    }
}
";
            var compilation = CreateCompilationWithMscorlib45(text).VerifyDiagnostics(
    // (11,18): error CS0175: Use of keyword 'base' is not valid in this context
    //         var x6 = base?.ToString();
    Diagnostic(ErrorCode.ERR_BaseIllegal, "base").WithLocation(11, 18),
    // (16,21): error CS0023: Operator '?' cannot be applied to operand of type 'int'
    //         var x = 123 ?[1,2];
    Diagnostic(ErrorCode.ERR_BadUnaryOp, "?").WithArguments("?", "int").WithLocation(16, 21),
    // (19,18): error CS0154: The property or indexer 'Program.P1' cannot be used in this context because it lacks the get accessor
    //         var x1 = p.P1 ?[1,2];
    Diagnostic(ErrorCode.ERR_PropertyLacksGet, "p.P1").WithArguments("Program.P1").WithLocation(19, 18),
    // (20,24): error CS0023: Operator '?' cannot be applied to operand of type 'void'
    //         var x2 = p.V() ?[1,2];
    Diagnostic(ErrorCode.ERR_BadUnaryOp, "?").WithArguments("?", "void").WithLocation(20, 24),
    // (21,20): error CS0119: 'Program.V()' is a method, which is not valid in the given context
    //         var x3 = p.V ?[1,2];
    Diagnostic(ErrorCode.ERR_BadSKunknown, "V").WithArguments("Program.V()", "method").WithLocation(21, 20),
    // (22,18): error CS0023: Operator '?' cannot be applied to operand of type 'lambda expression'
    //         var x4 = ()=> { return 1; } ?[1,2];
    Diagnostic(ErrorCode.ERR_BadUnaryOp, "()=> { return 1; } ?[1,2]").WithArguments("?", "lambda expression").WithLocation(22, 18),
    // (24,22): error CS0023: Operator '?' cannot be applied to operand of type '<null>'
    //         var x5 = null?.ToString();
    Diagnostic(ErrorCode.ERR_BadUnaryOp, "?").WithArguments("?", "<null>").WithLocation(24, 22)
    );
            var tree = compilation.SyntaxTrees.Single();
            var node = tree.GetRoot().DescendantNodes().OfType<ConditionalAccessExpressionSyntax>().First();

            Assert.Equal("base?.ToString()", node.ToString());

            compilation.VerifyOperationTree(node, expectedOperationTree:
@"
");
        }
```

Current parent is ConditionalAccess and we are trying to set a Call.
The following expression is evaluated to true:
```
((Microsoft.CodeAnalysis.Operations.LazyConditionalAccessExpression)result).ExpressionImpl == ((Microsoft.CodeAnalysis.Operations.LazyInvocationExpression)((Microsoft.CodeAnalysis.Operations.LazyConditionalAccessExpression)result).WhenNotNullImpl).InstanceImpl
```

In other words the IOperation for ```base``` expression is used as a IConditionalAccessOperation.Expression and as a IInvocationOperation.Instance. The IInvocationOperation is a IConditionalAccessOperation.WhenNotNull in that case.

```
>	Roslyn.Test.Utilities.dll!Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(string message, string detailMessage) Line 24	C#	Symbols loaded.
 	[External Code]		Annotated Frame
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Operation.SetParentOperation(Microsoft.CodeAnalysis.IOperation parent) Line 105	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Operation.SetParentOperation<Microsoft.CodeAnalysis.IOperation>(Microsoft.CodeAnalysis.IOperation operation, Microsoft.CodeAnalysis.IOperation parent) Line 121	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Operations.BaseInvocationExpression.Instance.get() Line 2782	C#	Symbols loaded.
 	Roslyn.Test.Utilities.dll!Microsoft.CodeAnalysis.Test.Utilities.OperationTreeVerifier.VisitInvocation(Microsoft.CodeAnalysis.Operations.IInvocationOperation operation) Line 652	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Operations.BaseInvocationExpression.Accept(Microsoft.CodeAnalysis.Operations.OperationVisitor visitor) Line 2793	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Operations.OperationWalker.Visit(Microsoft.CodeAnalysis.IOperation operation) Line 36	C#	Symbols loaded.
 	Roslyn.Test.Utilities.dll!Microsoft.CodeAnalysis.Test.Utilities.OperationTreeVerifier.Visit(Microsoft.CodeAnalysis.IOperation operation) Line 266	C#	Symbols loaded.
 	Roslyn.Test.Utilities.dll!Microsoft.CodeAnalysis.Test.Utilities.OperationTreeVerifier.Visit(Microsoft.CodeAnalysis.IOperation operation, string header) Line 282	C#	Symbols loaded.
 	Roslyn.Test.Utilities.dll!Microsoft.CodeAnalysis.Test.Utilities.OperationTreeVerifier.VisitConditionalAccess(Microsoft.CodeAnalysis.Operations.IConditionalAccessOperation operation) Line 864	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Operations.BaseConditionalAccessExpression.Accept(Microsoft.CodeAnalysis.Operations.OperationVisitor visitor) Line 1204	C#	Symbols loaded.
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Operations.OperationWalker.Visit(Microsoft.CodeAnalysis.IOperation operation) Line 36	C#	Symbols loaded.
 	Roslyn.Test.Utilities.dll!Microsoft.CodeAnalysis.Test.Utilities.OperationTreeVerifier.Visit(Microsoft.CodeAnalysis.IOperation operation) Line 266	C#	Symbols loaded.
 	Roslyn.Test.Utilities.dll!Microsoft.CodeAnalysis.Test.Utilities.OperationTreeVerifier.GetOperationTree(Microsoft.CodeAnalysis.Compilation compilation, Microsoft.CodeAnalysis.IOperation operation, int initialIndent) Line 51	C#	Symbols loaded.
 	Roslyn.Test.Utilities.dll!Microsoft.CodeAnalysis.Test.Utilities.CompilationExtensions.AppendOperationTree(Microsoft.CodeAnalysis.SemanticModel model, Microsoft.CodeAnalysis.SyntaxNode node, System.Text.StringBuilder actualTextBuilder, int initialIndent) Line 231	C#	Symbols loaded.
 	Roslyn.Test.Utilities.dll!Microsoft.CodeAnalysis.Test.Utilities.CompilationExtensions.VerifyOperationTree(Microsoft.CodeAnalysis.Compilation compilation, Microsoft.CodeAnalysis.SyntaxNode node, string expectedOperationTree) Line 163	C#	Symbols loaded.
 	Roslyn.Compilers.CSharp.Semantic.UnitTests.dll!Microsoft.CodeAnalysis.CSharp.UnitTests.SemanticErrorTests.ConditionalElementAccess001() Line 23012	C#	Symbols loaded.
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #23004.
Fixes #23009.
Related to #22548 and #22229.

vso : https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_workitems/edit/521119

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler, @dotnet/analyzer-ioperation, @cston Please review 15.5 IOperation fix.

File: src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs [hunk 1]
```diff
@@ -2605,7 +2605,7 @@ private bool IsOperandErrors(CSharpSyntaxNode node, ref BoundExpression operand,
                     if (!operand.HasAnyErrors)
                     {
                         Error(diagnostics, ErrorCode.ERR_LambdaInIsAs, node);
-                        operand = BadExpression(node, operand);
+                        operand = BadExpression(node, operand).MakeCompilerGenerated();
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs]: I wonder if BadExpression should always be marked as compiler-generated. This could wait til post-15.5.

File: src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs [hunk 2]
```diff
@@ -167,6 +167,34 @@ public override Symbol ExpressionSymbol
         // DevDiv 1087283 tracks deciding whether or not to refactor this into BoundNodes.xml.
         public ImmutableArray<PropertySymbol> OriginalIndexersOpt { get; private set; }
 
+        public BoundIndexerAccess Update(bool useSetterForDefaultArgumentGeneration)
+        {
+            if (useSetterForDefaultArgumentGeneration != this.UseSetterForDefaultArgumentGeneration)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs]: Nit: consider flipping the logic around to bail out fast (if equal, then return this).

File: src/Test/Utilities/Portable/Compilation/CompilationExtensions.cs [hunk 3]
```diff
@@ -255,6 +257,7 @@ public static void ValidateIOperations(Func<Compilation> createCompilation)
         {
 #if TEST_IOPERATION_INTERFACE
```
Comment (jcouv) [inline src/Test/Utilities/Portable/Compilation/CompilationExtensions.cs]: Not related to this PR: why do we need this pragma?

**Review by jcouv — APPROVED** [review]
LGTM

File: src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs]: > I wonder if BadExpression should always be marked as compiler-generated.

Not really.

File: src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs]: > Nit: consider flipping the logic around to bail out fast (if equal, then return this).

Simply follow the pattern for the way other Update methods are implemented.

File: src/Test/Utilities/Portable/Compilation/CompilationExtensions.cs (hunk 3 above)
Comment (AlekseyTs) [reply src/Test/Utilities/Portable/Compilation/CompilationExtensions.cs]: > Not related to this PR: why do we need this pragma?

So that we don't run this costly verification by default.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler, @dotnet/analyzer-ioperation, @cston Please review 15.5 IOperation fix.

**Comment by AlekseyTs** [comment]
CC @jinujoseph For Ask mode approval

**Comment by jinujoseph** [comment]
Approved to merge via [Link](https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_workitems/edit/521119)

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler, @dotnet/analyzer-ioperation, @cston Please review 15.5 IOperation fix.

**Review by mavasani — APPROVED** [review]

**Review by cston — APPROVED** [review]
