### PR TITLE
Fix a bug in code gen for switch on byte or ushort

### LINKED ISSUE #18188: C# 7.0 Multiple values for a case bug
**Version Used**:  2.0.0.61501

**Steps to Reproduce**:

1. Create a switch that uses Byte or Ushort  

```
byte testByte = 130;

switch (testByte)
{
    case 127: // 0111 1111
    case 128: // 1000 0000
        Console.WriteLine(@"BUGGGGGGGGGGGGGGGGG");
        break;
    default:
        Console.WriteLine(@"OK :D");
        break;
}

ushort testUshort = 32769;

switch (testUshort)
{
    case 32767: // 0111 1111 1111 1111
    case 32768: // 1000 0000 0000 0000
        Console.WriteLine(@"BUGGGGGGGGGGGGGGGGG");
        break;
    default:
        Console.WriteLine(@"OK :D");
        break;
}
```

**Expected Behavior**:

The expected behavior was the switch goes to default statement

**Actual Behavior**:

The switch goes to the case statement.

The compiler converts the 'switch' to 'if', but the conversion occurs in the wrong way.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #18188

The bug arose because of an interaction of this line (new in VS2017)

``` c#
                _builder.EmitIntConstant(endConstant.Int32Value - startConstant.Int32Value);
```

in `SwitchIntegralJumpTableEmitter` and an incorrect implementation of `Int32Value` for constants of type `ushort` and `ubyte`, which is recorded as a separate bug in https://github.com/dotnet/roslyn/issues/18579. Specifically, the implementation causes improper sign extension of what should be treated as an unsigned value.

We never caught this before because we didn't rely on it. Constant folding in the compiler goes through another (redundant) code path that gets the padding vs sign extension correct. Because this is a serious regression in the compiler, I am hoping we can include this fix is some upcoming patch at our earliest opportunity. Therefore I have included a simple, local fix for the symptom, while leaving the larger issue of `ConstantValue` to be dealt with in a later larger change. 

@VSadov @dotnet/roslyn-compiler May I please have a couple of reviews of this simple fix to a nasty bug?

### CODE REVIEW

**Comment by jaredpar** [comment]
@gafter 

> The bug arose because of an interaction of this line (new in VS2017)

Can you link to where this line occurred?

**Comment by AlekseyTs** [comment]
It looks like release compiler CI tests are failing due to identical problem. Could changes in this PR be the root cause of the failure?

**Comment by gafter** [comment]
The line occurs here: https://github.com/dotnet/roslyn/blob/a98e5998db4c63609e290594698202e18b03b8c5/src/Compilers/Core/Portable/CodeGen/SwitchIntegralJumpTableEmitter.cs#L469

File: src/Compilers/Core/Portable/ConstantValueSpecialized.cs [hunk 1]
```diff
@@ -609,6 +625,22 @@ public override ushort UInt16Value
                 }
             }
 
+            public override int Int32Value
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/ConstantValueSpecialized.cs]: >public override int Int32Value [](start = 12, length = 30)

Should we also override UInt32Value property? In general, I find semantics of properties that return unsigned values unclear. For example, the following code prints two different numbers
```
                short x = -1;
                System.Console.WriteLine((uint)x);
                System.Console.WriteLine((uint)(ushort)x);
```
Which one do we want to be the result of UInt32Value property?

Comment (AlekseyTs) [inline src/Compilers/Core/Portable/ConstantValueSpecialized.cs]: >public override int Int32Value [](start = 12, length = 30)

The same question is for UInt64Value property, the following code prints three different numbers, which one is the expected result?
```
                short x = -1;
                System.Console.WriteLine((ulong)x);
                System.Console.WriteLine((ulong)(uint)x);
                System.Console.WriteLine((ulong)(ushort)x);
```

File: src/Compilers/Core/Portable/ConstantValueSpecialized.cs [hunk 2]
```diff
@@ -660,6 +692,22 @@ public override uint UInt32Value
                 }
             }
 
+            public override long Int64Value
+            {
+                get
+                {
+                    switch (this.Discriminator)
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/ConstantValueSpecialized.cs]: What does Discriminator track for ConstantValue?  There is no comment and reading the code it's hard to understand why only the values specified here would be valued for each of the new overrides.

File: src/Compilers/Core/Portable/ConstantValueSpecialized.cs [hunk 3]
```diff
@@ -560,6 +560,22 @@ public override sbyte SByteValue
                 }
             }
 
+            public override short Int16Value
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/ConstantValueSpecialized.cs]: >public override short Int16Value [](start = 12, length = 32)

Should we also override UInt16Value, Uint32Value and UInt64Value properties? For example, what value do we want to get from UInt16Value property for the following scenario (two different values are  printed)?
```
                byte x = byte.MaxValue; // ConstantValueTypeDiscriminator.SByte
                System.Console.WriteLine((ushort)x);
                System.Console.WriteLine((ushort)(sbyte)x);
```

File: src/Compilers/Core/Portable/ConstantValueSpecialized.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/Core/Portable/ConstantValueSpecialized.cs]: Yes, I believe we should.

File: src/Compilers/Core/Portable/ConstantValueSpecialized.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/Core/Portable/ConstantValueSpecialized.cs]: This method appears in the specialized class whose purpose is to implement precisely these two discriminator kinds.

File: src/Compilers/Core/Portable/ConstantValueSpecialized.cs [hunk 4]
```diff
@@ -660,6 +692,22 @@ public override uint UInt32Value
                 }
             }
 
+            public override long Int64Value
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/ConstantValueSpecialized.cs]: >public override long Int64Value [](start = 12, length = 31)

Should we also override UInt64Value property?

**Comment by AlekseyTs** [comment]
I think we:
- should clearly define the contract of all "Value" properties in ConstantValue type. Right now none of them have clear comments.
- should review the current usage of the properties within the compiler and confirm that the properties are used correctly, given the contract. 
- should add targeted test for the properties to verify behavior against the contract.

File: src/Compilers/Core/Portable/ConstantValueSpecialized.cs (hunk 3 above)
Comment (VSadov) [inline src/Compilers/Core/Portable/ConstantValueSpecialized.cs]: No, unsigned operations do not need special casing. 
The underlying field is unsigned, so it will be properly zero-extended. (returning 255 for byte.MaxValue)


---
In reply to: [110446716](https://github.com/dotnet/roslyn/pull/18521#discussion_r110446716) [](ancestors = 110446716)

Comment (VSadov) [inline src/Compilers/Core/Portable/ConstantValueSpecialized.cs]: Actually, no. I changed my mind :-)
However intuitive it might be to return same 255, it is not what C# constant conversion does, and it  might be more consistent to be consistent with that:

I.E. UInt16Value should have same behavior as in:

            System.Console.WriteLine(unchecked((ushort)sbyte.MinValue));
            System.Console.WriteLine(unchecked((ushort)sbyte.MaxValue));

            System.Console.WriteLine(unchecked((ushort)byte.MinValue));
            System.Console.WriteLine(unchecked((ushort)byte.MaxValue));

That would imply sign-extending when underlying is a signed value according to the discriminant.

Then we truly can, one day, use this in constant folding.

---
In reply to: [110450281](https://github.com/dotnet/roslyn/pull/18521#discussion_r110450281) [](ancestors = 110450281,110446716)

**Comment by gafter** [comment]
I'm thinking of placing this approach on the back burner. I think that ConstantValue needs an overhaul, but that would be too disruptive a fix for #18188 to get it into a patch release. I'll prepare a more localized fix in a fresh PR.

**Comment by gafter** [comment]
@VSadov @AlekseyTs I've reverted the changes to `ConstantValue` and opened a new issue to review and fix that. This PR now contains only a local fix to the symptom regarding code generation for the switch statement. Can you please re-review?

**Comment by gafter** [comment]
@VSadov Can you please re-review? I simplified the fix.

**Comment by gafter** [comment]
@VSadov Can you please re-review? I simplified the fix.

**Comment by gafter** [comment]
@VSadov Can you please re-review? I simplified the fix.

File: src/Compilers/Core/Portable/CodeGen/SwitchIntegralJumpTableEmitter.cs [hunk 5]
```diff
@@ -466,7 +466,20 @@ private void EmitRangeCheckedBranch(ConstantValue startConstant, ConstantValue e
             }
             else
             {
-                _builder.EmitIntConstant(endConstant.Int32Value - startConstant.Int32Value);
+                int Int32Value(ConstantValue value)
```
Comment (VSadov) [inline src/Compilers/Core/Portable/CodeGen/SwitchIntegralJumpTableEmitter.cs]: Do we need to shim `Int64Value` in the code above the same way?

Basically, if the testcase is changed slightly to be `       void RunTest(ulong testUlong)` with everything else the same, do we still have a problem?

I think we do not have a problem since labels will be statically promoted to `ulong`.
Probably worth adding a testcase though.

Comment (VSadov) [inline src/Compilers/Core/Portable/CodeGen/SwitchIntegralJumpTableEmitter.cs]: Ah, I see the literals must have signed bits, which will force them to be 64bit and thus there will be no sign or zero extending. 
Basically the case is only relevant for switch types shorter than `uint`

**Comment by VSadov** [comment]
@gafter - perhaps need to change the title of the PR.
