### PR TITLE
Ensure partial method implementation is completed when needed

### LINKED ISSUE #18348: False positive "Using directive is unnecessary" in partial classes
**Version Used**: 
VS 2017 (15.0.26228.10) / Roslyn 2.0.0

**Steps to Reproduce**:

Partial class file 1:
```C#
using RoslynCodeAnalysisTests.Attributes;

namespace RoslynCodeAnalysisTests
{
    public partial class PartialClass
    {
        partial void PartialMethod([MyAttr] string a)
        {
        }
    }
}
```

Partial class file 2:
```C#
using RoslynCodeAnalysisTests.Attributes;

namespace RoslynCodeAnalysisTests
{
    [MyAttr]
    public partial class PartialClass
    {
        partial void PartialMethod(string a);
    }
}
```

=> Roslyn shows "Using directive is unnecessary" in file 1 for `using RoslynCodeAnalysisTests.Attributes` which is wrong.

image

**Expected Behavior**:
Do not show "Using directive is unnecessary". It makes my compilation failing when doing this.

BTW: When executing the corresponding quick-fix it doesn't change anything.

### PR DESCRIPTION
**Pull request by gafter**
**Customer scenario**

Place an attribute on a parameter of a partial implementation, where the attribute is the only thing that causes some using to be required. Then refactor "remove unnecessary usings". The bug is that the required using is removed.

**Bugs this fixes:**

Fixes #18348

**Workarounds, if any**

Don't place attributes on partial method implementation parameters.

**Risk**

Very low. The change is trivial.

**Performance impact**

Tiny. A small amount of additional logic is executed for partial methods.

**Is this a regression from a previous update?**

This has been a bug in Roslyn since VS2015.

**How was the bug found?**

Customer reported.

**Test documentation updated?**

N/A

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a couple of reviews for this small bug fix?
@jcouv May I please have approval for 15.5?

File: src/Compilers/CSharp/Test/Symbol/Compilation/GetUnusedImportDirectivesTests.cs [hunk 1]
```diff
@@ -375,5 +375,61 @@ public void UnusedUsingScript()
...
+            //comp.VerifyDiagnostics(); // doing this first hides the symptoms of the bug
+            var model = comp.GetSemanticModel(tree);
+
+            // There should be no diagnostics.
+            model.GetDiagnostics().Verify(
+                //// (1,1): hidden CS8019: Unnecessary using directive.
+                //// using System.Runtime.InteropServices;
+                //Diagnostic(ErrorCode.HDN_UnusedUsingDirective, "using System.Runtime.InteropServices;").WithLocation(1, 1)
+                );
+        }
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/Compilation/GetUnusedImportDirectivesTests.cs]: Were you able to confirm this fixes the IDE behavior too?

File: src/Compilers/CSharp/Test/Symbol/Compilation/GetUnusedImportDirectivesTests.cs [hunk 2]
```diff
@@ -375,5 +375,61 @@ public void UnusedUsingScript()
...
+{
+    partial void M(ref int x);
+}";
+            var comp = CreateStandardCompilation(new[] { source1, source2 });
+            var tree = comp.SyntaxTrees[0];
+            //comp.VerifyDiagnostics(); // doing this first hides the symptoms of the bug
+            var model = comp.GetSemanticModel(tree);
+
+            // There should be no diagnostics.
+            model.GetDiagnostics().Verify(
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Compilation/GetUnusedImportDirectivesTests.cs]: >model.GetDiagnostics().Verify( [](start = 12, length = 30)

Please also add a unit-test that asserts diagnostics requested exclusively for source1 syntax tree.

File: src/Compilers/CSharp/Test/Symbol/Compilation/GetUnusedImportDirectivesTests.cs [hunk 3]
```diff
@@ -375,5 +375,61 @@ public void UnusedUsingScript()
...
+{
+    partial void M(ref int x) { }
+}";
+            var comp = CreateStandardCompilation(new[] { source1, source2 });
+            var tree = comp.SyntaxTrees[0];
+            //comp.VerifyDiagnostics(); // doing this first hides the symptoms of the bug
+            var model = comp.GetSemanticModel(tree);
+
+            // There should be no diagnostics.
+            model.GetDiagnostics().Verify(
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Compilation/GetUnusedImportDirectivesTests.cs]: >model.GetDiagnostics().Verify [](start = 12, length = 29)

Please also add a unit-test that asserts diagnostics requested exclusively for source1 syntax tree.

File: src/Compilers/VisualBasic/Test/Semantic/Semantics/GetUnusedImportDirectivesTests.vb [hunk 4]
```diff
@@ -314,5 +314,57 @@ Imports System
...
+    Partial Private Sub M(ByRef x As Integer)
+    End Sub
+End Class
+]]></file>
+</compilation>
+
+            Dim comp = CreateCompilationWithMscorlib(source)
+            Dim tree = comp.SyntaxTrees(0)
+            Dim model = comp.GetSemanticModel(tree)
+            Dim diagnostics = model.GetDiagnostics()
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Semantic/Semantics/GetUnusedImportDirectivesTests.vb]: >Dim diagnostics = model.GetDiagnostics() [](start = 12, length = 40)

Same suggestions as for C#.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs [hunk 5]
```diff
@@ -996,6 +997,18 @@ internal override void ForceComplete(SourceLocation locationOpt, CancellationTok
...
+        internal override bool IsDefinedInSourceTree(
+            SyntaxTree tree,
+            TextSpan? definedWithinSpan,
+            CancellationToken cancellationToken = default(CancellationToken))
+        {
+            // Since only the declaring (and not the implementing) part of a partial method appears in the member
+            // list, we need to ensure we complete the implementation part when needed.
+            return
+                base.IsDefinedInSourceTree(tree, definedWithinSpan, cancellationToken) ||
+                this.SourcePartialImplementation?.IsDefinedInSourceTree(tree, definedWithinSpan, cancellationToken) == true;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs]: >this.SourcePartialImplementation?.IsDefinedInSourceTree(tree, definedWithinSpan, cancellationToken) == true; [](start = 16, length = 108)

Should we also add similar condition for SourcePartialDefinition? For completeness.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs]: >this.SourcePartialImplementation?.IsDefinedInSourceTree(tree, definedWithinSpan, cancellationToken) == true; [](start = 16, length = 108)

Since we added this special case here, do we still need a an equivalent special case in CSharpCompilation.IsDefinedOrImplementedInSourceTree?

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 2).

File: src/Compilers/CSharp/Test/Symbol/Compilation/GetUnusedImportDirectivesTests.cs (hunk 2 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Symbol/Compilation/GetUnusedImportDirectivesTests.cs]: That is precisely what this line does.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs (hunk 5 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs]: No. The partial implementation does not appear among the list of members during completion (unless there is no definition part). Such a condition would have no effect.

Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceOrdinaryMethodSymbol.cs]: No, we should be able to remove that. Will update.

File: src/Compilers/CSharp/Test/Symbol/Compilation/GetUnusedImportDirectivesTests.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Symbol/Compilation/GetUnusedImportDirectivesTests.cs]: The only IDE symptom is that the using directive appears greyed out. Yes, I have verified by hand that is no longer the case.

File: src/Compilers/CSharp/Test/Symbol/Compilation/GetUnusedImportDirectivesTests.cs (hunk 3 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Symbol/Compilation/GetUnusedImportDirectivesTests.cs]: That is precisely what this line does.

File: src/Compilers/VisualBasic/Test/Semantic/Semantics/GetUnusedImportDirectivesTests.vb (hunk 4 above)
Comment (gafter) [reply src/Compilers/VisualBasic/Test/Semantic/Semantics/GetUnusedImportDirectivesTests.vb]: Same response.

**Comment by gafter** [comment]
@AlekseyTs I believe all of your comments have been addressed. Do you have any others?
