### PR TITLE
An attempt to fix some flaky tests.

### LINKED ISSUE #5631: disabling EmitSequence tests
Disabling these three tests
  ```
Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenOperatorTests.EmitSequenceOfBinaryExpressions_03
Microsoft.CodeAnalysis.VisualBasic.UnitTests.CodeGenTests.EmitSequenceOfBinaryExpressions_06
Microsoft.CodeAnalysis.VisualBasic.UnitTests.CodeGenTests.EmitSequenceOfBinaryExpressions_03
```	

as they failed in internal run http://dotnet-ci.cloudapp.net/job/roslyn-internal_master_win_rel_unit32/7/

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #5631.

@gafter, @VSadov, @jaredpar, @agocke, @TyOverby Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
Should be fixes #5631.

**Comment by TyOverby** [comment]
To be clear, bumping that constant makes it so that the compiler more reliably overflow the stack while in the emit phase?  Or is this the parser that should overflow?

**Comment by agocke** [comment]
:+1:

**Comment by AlekseyTs** [comment]
@TyOverby The stack overflow we are trying to cause is after the initial binding phase. I.e. in lowering, optimization or emit phase.

**Comment by TyOverby** [comment]
:ship:

File: src/Compilers/CSharp/Portable/Syntax/InternalSyntax/BinaryExpressionSyntax.cs [hunk 1]
```diff
@@ -0,0 +1,58 @@
+﻿// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
+
+using System.Diagnostics;
+using System.IO;
+
+namespace Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax
+{
+    internal partial class BinaryExpressionSyntax
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Syntax/InternalSyntax/BinaryExpressionSyntax.cs]: @gafter, @VSadov, @jaredpar, @agocke, @TyOverby Please review changes in this file. I had to make them in order to avoid stack overflow during syntax tree serialization.

Comment (agocke) [inline src/Compilers/CSharp/Portable/Syntax/InternalSyntax/BinaryExpressionSyntax.cs]: Should we just do this for every `WriteTo`?

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Syntax/InternalSyntax/BinaryExpressionSyntax.cs]: @agocke Could you elaborate please?

Comment (agocke) [inline src/Compilers/CSharp/Portable/Syntax/InternalSyntax/BinaryExpressionSyntax.cs]: This adds protection for BinaryExpressionSyntax only -- should all of WriteTo be changed (probably via the generator) to use a non-recursive implementation?

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Syntax/InternalSyntax/BinaryExpressionSyntax.cs]: It depends how much we are willing to complicate the system. Recursion on the left for binary expressions is very common. Note, we do not try to specially handle recursion on the right, because deep recursion on the right is not that common. The same goes for recursion for other nodes. It would probably be good to have a way to efficiently traverse a tree without using recursion, but this is definitely out of scope for what I am trying to accomplish in this change.

**Comment by VSadov** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Syntax/InternalSyntax/BinaryExpressionSyntax.cs (hunk 1 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Syntax/InternalSyntax/BinaryExpressionSyntax.cs]: @AlekseyTs Sounds good. :+1: For this change, btw.
