### PR TITLE
Stop Simplifier.ReduceAsync removing empty arg lists from delegates

### LINKED ISSUE #40442: Simplifier.ReduceAsync changes function evaluation behaviour
**Version Used**: 
Repros on both 2.10.0 and 3.5.0-beta1-final of Microsoft.CodeAnalysis.* 

**Steps to Reproduce**:
Run this failing test in the roslyn repo https://github.com/grahamthecoder/roslyn/commit/34f6dfeb57d52ab7f1dc6108e5d993d77e4139db

<details>
 <summary>Original longer repro steps</summary>
1. Clone https://github.com/icsharpcode/CodeConverter
2. Checkout branch "roslyn-simplifier-issues"
3. Run Tests project (see file [VbSimplificationServiceBugRepros](https://github.com/icsharpcode/CodeConverter/blob/roslyn-simplifier-issues/Tests/VbSimplificationServiceBugRepros.cs))
4. Observe test result - the parentheses are removed (run the resulting code and access the relevant property to see the runtime exception)
</details>

**Expected Behavior**:
Parentheses should not be removed by the simplifier - they evaluate the function producing a string
See the example fix here: https://github.com/grahamthecoder/roslyn/commit/12739f9f3248b222ff50122facca1130b317802e

**Actual Behavior**:
Parentheses are removed by the simplifier. The resulting code does not evaluate the function. It passes the function as a delegate and therefore behaves differently (throwing at runtime when trying to cast delegate to string).

**Other Details**:
* I can't find the relevant spec, but suspect VB doesn't invoke delegates, only method/property groups and therefore the logic for removing the argument list needs to check some detail of the expression type.
* I have repros for other issues in ExpandAsync and ReduceAsync for C# and VB that I'm struggling to workaround effectively. I'll see if I can write them as tests directly in the roslyn repo, but if not I'll open them as separate issues with a similar style to this.
* Thanks for all your work on Roslyn, it's great!

### PR DESCRIPTION
**Pull request by GrahamTheCoder**
Fixes #40442

* I suspect the test is in slightly the wrong place, but couldn't find a sensible place.
* I've aimed to err on the side of caution, leaving the brackets where the symbol is unresolvable except in some cases where it couldn't be anything else valid. If you can point at the spec or code that decides whether something without an arg list will be invoked then I'll happily update to use the precise logic if it differs from what I've done.

### CODE REVIEW

File: src/Workspaces/VisualBasic/Portable/Extensions/InvocationExpressionSyntaxExtensions.vb [hunk 1]
```diff
@@ -47,7 +47,8 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Extensions
                 End If
             End If
 
-            Return True
+            Dim isOrdinaryMethod = semanticModel.GetSymbolInfo(invocationExpression.Expression).Symbol?.IsOrdinaryMethod
+            Return isOrdinaryMethod.HasValue AndAlso isOrdinaryMethod.Value
```
Comment (CyrusNajmabadi) [inline src/Workspaces/VisualBasic/Portable/Extensions/InvocationExpressionSyntaxExtensions.vb]: `return isOrdinaryMethod = true`

Comment (CyrusNajmabadi) [inline src/Workspaces/VisualBasic/Portable/Extensions/InvocationExpressionSyntaxExtensions.vb]:
```suggestion
            Return isOrdinaryMethod = True
```

File: src/EditorFeatures/Test2/Simplification/ParenthesisSimplificationTests.vb [hunk 2]
```diff
@@ -294,6 +294,84 @@ Class C
...
     End Sub
 End Class
+</code>
+
+            Await TestAsync(input, expected)
+        End Function
+
+        <WorkItem(40442, "https://github.com/dotnet/roslyn/issues/40442")>
+        <Fact, Trait(Traits.Feature, Traits.Features.Simplification)>
+        Public Async Function TestVisualBasic_OnlyRemoveEmptyArgumentLisForMethodGroup() As Task
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Test2/Simplification/ParenthesisSimplificationTests.vb]:
```suggestion
        Public Async Function TestVisualBasic_DoNotRemoveEmptyArgumentListOnLambda() As Task
```

File: src/EditorFeatures/Test2/Simplification/ParenthesisSimplificationTests.vb [hunk 3]
```diff
@@ -294,6 +294,84 @@ Class C
...
+<Workspace>
+    <Project Language="Visual Basic" CommonReferences="true">
+        <Document>
+Public Class TestClass
+    Shared Function GetFour() As Integer
+        Return 4
+    End Function
+    
+    Public Shared Sub Main()
+        Dim inferredMethodGroup = MyIf({|SimplifyExtension:TestClass.GetFour()|})
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Test2/Simplification/ParenthesisSimplificationTests.vb]: please break into separate tests.  it will be much easier for diagnosing test failures and maintaining these.  thanks!

File: src/Workspaces/VisualBasic/Portable/Extensions/InvocationExpressionSyntaxExtensions.vb (hunk 1 above)
Comment (GrahamTheCoder) [reply src/Workspaces/VisualBasic/Portable/Extensions/InvocationExpressionSyntaxExtensions.vb]: I tried that originally but got
BC30512	Option Strict On disallows implicit conversions from 'Boolean?' to 'Boolean'.
Shall I do `CBool(isOrdinaryMethod)`?

**Comment by CyrusNajmabadi** [comment]
> I suspect the test is in slightly the wrong place, but couldn't find a sensible place.

This file seems reasonable.

File: src/Workspaces/VisualBasic/Portable/Extensions/InvocationExpressionSyntaxExtensions.vb (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/VisualBasic/Portable/Extensions/InvocationExpressionSyntaxExtensions.vb]: oh.  interesting!  no.  just keep what you have here.

Comment (CyrusNajmabadi) [reply src/Workspaces/VisualBasic/Portable/Extensions/InvocationExpressionSyntaxExtensions.vb]: #resolved

**Comment by CyrusNajmabadi** [comment]
From this point on, can you avoid force pushing?  It makes it difficult to review things . Thanks!

**Comment by CyrusNajmabadi** [comment]
Thanks for the PR @GrahamTheCoder !

**Comment by GrahamTheCoder** [comment]
I'll try to have a look at the other affected tests in the next day or so. Looks like `TestFixedNullExceptionCrash` should have been simplified assuming the symbol could be found.

File: src/Workspaces/VisualBasic/Portable/Extensions/InvocationExpressionSyntaxExtensions.vb [hunk 4]
```diff
@@ -12,14 +12,11 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Extensions
...
         <Extension>
         Public Function CanRemoveEmptyArgumentList(invocationExpression As InvocationExpressionSyntax, semanticModel As SemanticModel, cancellationToken As CancellationToken) As Boolean
-            If invocationExpression.ArgumentList Is Nothing Then
-                Return False
-            End If
-
-            If invocationExpression.ArgumentList.Arguments.Count > 0 Then
-                Return False
-            End If
+            Return invocationExpression.ArgumentList IsNot Nothing AndAlso invocationExpression.ArgumentList.Arguments.Count = 0 AndAlso _
```
Comment (CyrusNajmabadi) [inline src/Workspaces/VisualBasic/Portable/Extensions/InvocationExpressionSyntaxExtensions.vb]: trailing _ isn't necessary here, right?

Comment (GrahamTheCoder) [reply src/Workspaces/VisualBasic/Portable/Extensions/InvocationExpressionSyntaxExtensions.vb]: Good point - fixed

**Comment by GrahamTheCoder** [comment]
I'm assuming this is now just in a queue to look at - let me know if there's anything else I can do to help it along
