### PR TITLE
Handle invalid dotnet_diagnostic entry without ID part in configurati…

### LINKED ISSUE #45446: Exception in VS 2019 when setting analyzer rule severity level.
**Version Used**: 
Microsoft (R) Visual C# Compiler version 3.6.0-4.20251.5 (910223b6)

**Steps to Reproduce**:

1. Add CA rules to .editorconfig file
2. Add line "# dotnet_diagnostic.severity = error" to the .editorconfig file
3. Run code analysis in Visual Studio 2019 IDE (will need at least one analyzer rule failure)
4. In the Error List, right click on a rule failure and set severity for the rule to a different severity level

**Expected Behavior**:
New rule entry is added to .editorconfig file.

**Actual Behavior**:
Dialog box error as follows, and no change to the .editorconfig file:

. ---------------------------
. Microsoft Visual Studio
. ---------------------------
. Length cannot be less than zero.
. 
. Parameter name: length
. ---------------------------
. OK   
. ---------------------------

### PR DESCRIPTION
**Pull request by mavasani**
…on code fix

Fixes #45446

### CODE REVIEW

File: src/Features/Core/Portable/CodeFixes/Configuration/ConfigurationUpdater.cs [hunk 1]
```diff
@@ -488,10 +488,13 @@ private async Task<Solution> ConfigureAsync()
                                         key.EndsWith(SeveritySuffix, StringComparison.Ordinal))
                                     {
                                         var diagIdLength = key.Length - (DiagnosticOptionPrefix.Length + SeveritySuffix.Length);
-                                        var diagId = key.Substring(DiagnosticOptionPrefix.Length, diagIdLength);
-                                        if (string.Equals(diagId, _diagnostic.Id, StringComparison.OrdinalIgnoreCase))
+                                        if (diagIdLength > 0)
```
Comment (mavasani) [inline src/Features/Core/Portable/CodeFixes/Configuration/ConfigurationUpdater.cs:491]: Only change is adding this if check.

**Comment by mavasani** [comment]
Thanks!

**Comment by GaTechThomas** [comment]
Does this fix the specific issue? The problem is occurring when the specified line is included in the .editorconfig file (note the leading '#'):

`# dotnet_diagnostic.severity = error
`
