### PR TITLE
Fix regression of LambdaSymbol.GetHashCode

### LINKED ISSUE #58226: Change of behavior in symbol comparison with SymbolEqualityComparer
**Version Used**: 
`Microsoft.CodeAnalysis.CSharp` nuget package version `3.10.0` and `3.11.0`

**Steps to Reproduce**:
The following code behaves differently on version 3.10.0 and 3.11.0
```csharp
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

var code = @"
using System.Linq;

M1(args => string.Join("" "", args.Select(a => a.ToString())));
void M1<TResult>(Func<object?[], TResult>? f) { }";

var compilation = CSharpCompilation.Create(null)
    .AddSyntaxTrees(SyntaxFactory.ParseSyntaxTree(code))
    .AddReferences(MetadataReference.CreateFromFile(typeof(object).Assembly.Location));

var tree = compilation.SyntaxTrees.Single();
var lambdaSyntax = tree.GetRoot().DescendantNodes().OfType<SimpleLambdaExpressionSyntax>().First();
var semanticModel1 = compilation.GetSemanticModel(tree);
var semanticModel2 = compilation.GetSemanticModel(tree);

var lambdaSymbol = (IMethodSymbol)semanticModel1.GetSymbolInfo(lambdaSyntax).Symbol;
var p1 = lambdaSymbol.Parameters.Single();

var p2 = semanticModel2.GetDeclaredSymbol(lambdaSyntax.Parameter);

Console.WriteLine(p1.Equals(p2));                                // 3.10.0: True  | 3.11.0: True
Console.WriteLine(p1 == p2);                                     // 3.10.0: False | 3.11.0: False
Console.WriteLine(SymbolEqualityComparer.Default.Equals(p1, p2));// 3.10.0: True  | 3.11.0: True

Console.WriteLine(p1.GetHashCode() == p2.GetHashCode());         // 3.10.0: True  | 3.11.0: False <- DIFFERS
var s = new HashSet<ISymbol>(SymbolEqualityComparer.Default);
s.Add(p1);
Console.WriteLine(s.Contains(p2));                               // 3.10.0: True  | 3.11.0: False <- DIFFERS
```

**Expected Behavior**:
I expected `s.Contains(p2)` to be `true` on the last line. This is also the suggested behavior by https://github.com/dotnet/roslyn-analyzers/issues/4568.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #58226

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs [hunk 1]
```diff
@@ -384,7 +384,7 @@ static bool areEqual(SyntaxReference a, SyntaxReference b)
 
         public override int GetHashCode()
         {
-            return syntaxReferenceOpt.GetHashCode();
+            return Syntax.GetHashCode();
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs:387]: >Syntax [](http://example.com/codeflow?start=19&length=6)

Thanks for catching this. 

This looks distinct from `Equals()` which is checking the fields of `syntaxReferenceOpt`. Should `Equals()` be reverted to check `lambda.Syntax == Syntax` instead of checking `syntaxReferenceOpt`?

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs:387]: @cston I *think* both should work the same. I'll go with `lambda.Syntax == Syntax`. It's more clear, and is the original behavior before the lambda improvements work.

https://github.com/dotnet/roslyn/blob/446399422d1d8f7a97a2c04eea8775d3559d206d/src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs#L388

File: src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs [hunk 2]
```diff
@@ -369,22 +369,17 @@ public sealed override bool Equals(Symbol symbol, TypeCompareKind compareKind)
...
-            static bool areEqual(SyntaxReference a, SyntaxReference b)
-            {
-                return (object)a.SyntaxTree == b.SyntaxTree && a.Span == b.Span;
-            }
         }
 
         public override int GetHashCode()
         {
-            return syntaxReferenceOpt.GetHashCode();
+            return Syntax.GetHashCode();
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs:382]: >Syntax.GetHashCode(); [](http://example.com/codeflow?start=19&length=21)

Is `Syntax.GetHashCode()` guaranteed to return the same value each time given that `Syntax` is implemented as `syntaxReferenceOpt.GetSyntax()`? 

If we want to use the `Syntax` for `GetHashCode()` and `Equals()`, then `LambdaSymbol` should probably hold onto the `SyntaxNode` in a `readonly` field instead. Otherwise `GetHashCode()` and `Equals()` should rely on the fields of `syntaxReferenceOpt` rather than `syntaxReferenceOpt.GetSyntax()`.

For the latter approach, perhaps:
```csharp
public override int GetHashCode()
{
    return Hash.Combine(
        syntaxReferenceOpt.SyntaxTree.GetHashCode(),
        syntaxReferenceOpt.Span.GetHashCode());
}
```

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs:382]: @cston From the unit test, it seems to be working as expected. But I'm okay with either holding `Syntax` as a `_syntax` field, or implementing it using `SyntaxReference.SyntaxTree|Span`.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs:382]: >Syntax.GetHashCode(); [](http://example.com/codeflow?start=19&length=21)

I assume this is where the root cause of the problem was. SyntaxReference uses reference equality, therefore distinct syntax references almost always have different hash code. If this is correct, then I think we should simply align this implementation with the original implementation of ```Equals```. I.e. combine hash codes of the tree and span and revert changes to the ```Equals```.

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs:382]: @AlekseyTs It was exactly my intention to keep the original implementation. The changes that used the tree and the span along the `GetHashCode` change were all introduced in https://github.com/dotnet/roslyn/pull/52178. This simply reverts this small portion of #52178. I'm okay with any of the suggested approaches by you or @cston

I just wanted to point out to #52178 since this is what took me this way.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 2)

File: src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs:382]: > It was exactly my intention to keep the original implementation. 

When I said "original", I meant "original" in context of this PR. And the suggestion to revert ```Equals``` also in context of changes made in this PR.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs:382]: To clarify. I think that we shouldn't change ```Equals``` in this PR and should simply align implementation of ```GetHashCode``` with what ```Equals``` is doing.

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs]: @AlekseyTs Thanks. Fixed.

My initial thought was to keep the implementation that has been working for years, but I can also see this is not necessarily correct (ie, it may have changed for a good reason).

Though for this PR, it's likely both implementations will work equivalently anyway, so keeping `Equals` as-is and do minimal change in `GetHashCode` does make more sense.

Thanks again :)

File: src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs [hunk 3]
```diff
@@ -384,7 +384,7 @@
 
         public override int GetHashCode()
         {
-            return syntaxReferenceOpt.GetHashCode();
+            return HashCode.Combine(syntaxReferenceOpt.SyntaxTree, syntaxReferenceOpt.Span);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs:387]: >HashCode.Combine [](http://example.com/codeflow?start=19&length=16)

It looks like we standardize on ```Hash.Combine```. Also, is this call going to box the span?

**Comment by AlekseyTs** [comment]
Done with review pass (commit 3).

**Review by cston — APPROVED** [review]
Thanks @Youssef1313!

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 4)

**Comment by cston** [comment]
It looks like there are related test failures with distinct `LambdaSymbol` instances considered equal in error scenarios. I'll investigate.

**Comment by AlekseyTs** [comment]
> The simplest solution may be to add back the private readonly SyntaxNode _syntax; field from before #52178, and revert Equals() to use lambda._syntax == _syntax and revert GetHashCode() to use _syntax.GetHashCode().

I do not think going back to an extra field is necessary. The correctness problem in the ```Equals``` that is revealed by the failures  can be addressed by comparing underlying syntax nodes. Leaving GatHashCode as it is in commit 4 looks safe to me.

**Comment by cston** [comment]
> Leaving GatHashCode as it is in commit 4 looks safe to me.

Let's add back the `_syntax` field from before https://github.com/dotnet/roslyn/pull/52178 and let's revert `Equals()` and `GetHashCode()` to use `_syntax`, so that both methods are using the `SyntaxNode` rather than different state.

@Youssef1313, please add back `private readonly SyntaxNode _syntax;` and set the field in the constructor. The field should be returned from the `Syntax` property, and used in `Equals()` and `GetHashCode()`. If you'd prefer that I push a commit to your PR, let me know. Thanks.

**Comment by cston** [comment]
>         internal SyntaxNode Syntax => syntaxReferenceOpt.GetSyntax();

Can this property be removed now and uses replaced with `_syntax`. (This property was only introduced because the `_syntax` field was removed previously.)


---
Refers to: src/Compilers/CSharp/Portable/Symbols/Source/LambdaSymbol.cs:268 in a8122f7. [](commit_id = a8122f797d72179872ae2c2ec44e10157642f1e8, deletion_comment = False)

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolEqualityTests.cs [hunk 4]
```diff
@@ -911,6 +911,38 @@ public static void M(A<T> t)
...
+            var semanticModel1 = comp.GetSemanticModel(syntaxTree);
+            var semanticModel2 = comp.GetSemanticModel(syntaxTree);
+
+            var lambdaSymbol = (IMethodSymbol)semanticModel1.GetSymbolInfo(lambdaSyntax).Symbol;
+            var p1 = lambdaSymbol.Parameters.Single();
+
+            var p2 = semanticModel2.GetDeclaredSymbol(lambdaSyntax.Parameter);
+            VerifyEquality(p1, p2, expectedIncludeNullability: true);
+
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolEqualityTests.cs:944]: >} [](http://example.com/codeflow?start=8&length=1)

Let's include a test that specifically tests `Equals()` for distinct lambda expressions with the same span.
```csharp
        [Fact]
        [WorkItem(58226, "[https://github.com/dotnet/roslyn/issues/58226](https://github.com/dotnet/roslyn/issues/58226)")]
        public void LambdaSymbol_02()
        {
            var source =
@"class Program
{
    static void Main()
    {
        var q = from i in new int[] { 4, 5 } where /*pos*/
    }
}";
            var comp = CreateCompilation(source);
            var syntaxTree = comp.SyntaxTrees[0];
            var model = comp.GetSemanticModel(syntaxTree);
            var syntaxNode = syntaxTree.GetRoot().DescendantNodes().OfType<QueryExpressionSyntax>().Single();
            var operation = model.GetOperation(syntaxNode);
            var lambdas = operation.Descendants().OfType<AnonymousFunctionOperation>().Select(op => op.Symbol.GetSymbol<LambdaSymbol>()).ToImmutableArray();
            Assert.Equal(2, lambdas.Length);
            var syntaxRefs = lambdas.SelectAsArray(l => l.SyntaxRef);
            Assert.Equal(syntaxRefs[0].Span, syntaxRefs[1].Span);
            Assert.NotEqual(lambdas[0], lambdas[1]);
        }
```

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolEqualityTests.cs [hunk 5]
```diff
@@ -911,6 +911,63 @@ public static void M(A<T> t)
...
+            var syntaxNode = syntaxTree.GetRoot().DescendantNodes().
+                OfType<QueryExpressionSyntax>().Single();
+            var operation = model.GetOperation(syntaxNode);
+            var lambdas = operation.Descendants().OfType<AnonymousFunctionOperation>().
+                Select(op => op.Symbol.GetSymbol<LambdaSymbol>()).ToImmutableArray();
+            Assert.Equal(2, lambdas.Length);
+            var syntaxRefs = lambdas.SelectAsArray(l => l.SyntaxRef);
+            Assert.Equal(syntaxRefs[0].Span, syntaxRefs[1].Span);
+            Assert.NotEqual(lambdas[0], lambdas[1]);
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolEqualityTests.cs:969]: @Youssef1313, it looks like a couple of namespaces are missing:
```csharp
using System.Collections.Immutable;
using Microsoft.CodeAnalysis.Operations;
```

Comment (Youssef1313) [reply src/Compilers/CSharp/Test/Symbol/Symbols/SymbolEqualityTests.cs:971]: That's what happens when I edit via GitHub directly 😄

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolEqualityTests.cs [hunk 6]
```diff
@@ -911,6 +913,63 @@ public static void M(A<T> t)
...
+            var comp = CreateCompilation(source);
+            var syntaxTree = comp.SyntaxTrees[0];
+            var model = comp.GetSemanticModel(syntaxTree);
+            var syntaxNode = syntaxTree.GetRoot().DescendantNodes().
+                OfType<QueryExpressionSyntax>().Single();
+            var operation = model.GetOperation(syntaxNode);
+            var lambdas = operation.Descendants().OfType<AnonymousFunctionOperation>().
+                Select(op => op.Symbol.GetSymbol<LambdaSymbol>()).ToImmutableArray();
+            Assert.Equal(2, lambdas.Length);
+            var syntaxRefs = lambdas.SelectAsArray(l => l.SyntaxRef);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolEqualityTests.cs:968]: >SelectAsArray [](http://example.com/codeflow?start=37&length=13)

It looks like we could do without building this array.

**Review by cston — APPROVED** [review]

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 9)

**Comment by AlekseyTs** [comment]
@Youssef1313 Thank you for the contribution.
