### PR TITLE
Brace matcher for preprocessor directives

### LINKED ISSUE #7120: Brace navigation doesn't work for preprocessor directives
Originally reported at http://connect.microsoft.com/VisualStudio/feedback/details/1232395/brace-navigation-doesnt-work-for-regions and http://connect.microsoft.com/VisualStudio/feedback/details/2040133/brace-matching-edit-gotobrace-is-broken-for-preprocessor-directives-eg-if. Also reported internally by @pharring.

In VS2013 and earlier, we used to support Edit.GoToMatchingBrace (Ctrl+]) on `#if/#endif` and `#region/#endregion` pairs as well as braces.  In Roslyn we don't, though we do highlight them and support navigation through Edit.NextHighlightedReference and Edit.PreviousHighlightedReference (Ctrl+Shift+DownArrow and Ctrl+Shift+UpArrow).

We could implement support in GoToMatchingBrace as well.

### PR DESCRIPTION
**Pull request by balajikris**
Fixes #7120 

Implements an IBraceMatcher that matches directive trivia syntax for C# and VB.

### CODE REVIEW

**Comment by balajikris** [comment]
@dotnet/roslyn-ide

File: src/EditorFeatures/CSharpTest/BraceMatching/CSharpBraceMatcherTests.cs [hunk 1]
```diff
@@ -501,5 +501,127 @@ protected override Task<TestWorkspace> CreateWorkspaceFromCodeAsync(string code)
...
+{
+}";
+            var expected = @"
+#define CHK
+public class C 
+{
+}";
+
+            await TestAsync(code, expected);
+        }
```
Comment (Pilchie) [inline src/EditorFeatures/CSharpTest/BraceMatching/CSharpBraceMatcherTests.cs]: Consider: Tests for interleaved directives.

**Comment by Pilchie** [comment]
:+1:

File: src/EditorFeatures/CSharpTest/BraceMatching/CSharpBraceMatcherTests.cs (hunk 1 above)
Comment (balajikris) [inline src/EditorFeatures/CSharpTest/BraceMatching/CSharpBraceMatcherTests.cs]: Done, thanks.

File: src/EditorFeatures/CSharp/BraceMatching/DirectiveTriviaMatcher.cs [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+{
+    [ExportBraceMatcher(LanguageNames.CSharp)]
+    internal class DirectiveTriviaMatcher : IBraceMatcher
+    {
+        public async Task<BraceMatchingResult?> FindBracesAsync(Document document, int position, CancellationToken cancellationToken)
+        {
+            var root = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
+            var token = root.FindToken(position, findInsideTrivia: true);
+
+            var directive = token.Parent as DirectiveTriviaSyntax;
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharp/BraceMatching/DirectiveTriviaMatcher.cs]: Will the parent always be DirectiveTrivia?  What if i'm in something like   ```#if Some || Thing && Else```

I think you want to know if an ancestor is DirectiveTrivia instead.

File: src/EditorFeatures/CSharp/BraceMatching/DirectiveTriviaMatcher.cs [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+            if (directive == null)
+            {
+                return null;
+            }
+
+            DirectiveTriviaSyntax matchingDirective = null;
+            if (IsConditionalDirective(directive))
+            {
+                // #If/#elif/#else/#endIf directive cases.
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharp/BraceMatching/DirectiveTriviaMatcher.cs]: ```#if and endif```  not ```#If```

File: src/EditorFeatures/CSharp/BraceMatching/DirectiveTriviaMatcher.cs [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+                var matchingDirectives = directive.GetMatchingConditionalDirectives(cancellationToken).ToList();
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharp/BraceMatching/DirectiveTriviaMatcher.cs]: The code here seems identical to VB.  Can we share a common base class for doing most of this work.

File: src/EditorFeatures/CSharp/BraceMatching/DirectiveTriviaMatcher.cs (hunk 2 above)
Comment (balajikris) [inline src/EditorFeatures/CSharp/BraceMatching/DirectiveTriviaMatcher.cs]: It works only when the caret is on the hashtoken or the keyword (`#if$$` `$$#else`) and not on identifiers (`$$CHK`) or related trailing trivia (`$$MyRegion`). 
In that it is consistent with how Highlight references performs navigation on these and with brace matching itself in VS2013. I'm open to tweaking this if you feel we should.

File: src/EditorFeatures/CSharp/BraceMatching/DirectiveTriviaMatcher.cs (hunk 4 above)
Comment (balajikris) [inline src/EditorFeatures/CSharp/BraceMatching/DirectiveTriviaMatcher.cs]: Ah, this is purely syntactic and the shape of the tree in VB is vastly different from that of C#, so I stopped with this. However there are some common parts that could be extracted to a base type. Will do.

**Comment by balajikris** [comment]
@CyrusNajmabadi - incorporated all the feedback, please take a look.

File: src/EditorFeatures/CSharp/BraceMatching/DirectiveTriviaMatcher.cs (hunk 2 above)
Comment (balajikris) [inline src/EditorFeatures/CSharp/BraceMatching/DirectiveTriviaMatcher.cs]: agreed offline to keep the existing design as such.

File: src/EditorFeatures/Core/Extensibility/BraceMatching/AbstractDirectiveTriviaBraceMatcher.cs [hunk 5]
```diff
@@ -0,0 +1,72 @@
...
+            where TIfDirectiveTriviaSyntax : TDirectiveTriviaSyntax
+            where TElseIfDirectiveTriviaSyntax : TDirectiveTriviaSyntax
+            where TElseDirectiveTriviaSyntax : TDirectiveTriviaSyntax
+            where TEndIfDirectiveTriviaSyntax : TDirectiveTriviaSyntax
+            where TRegionDirectiveTriviaSyntax : TDirectiveTriviaSyntax
+            where TEndRegionDirectiveTriviaSyntax : TDirectiveTriviaSyntax
+    {
+        internal abstract List<TDirectiveTriviaSyntax> GetMatchingConditionalDirectives(TDirectiveTriviaSyntax directive, CancellationToken cancellationToken);
+        internal abstract TDirectiveTriviaSyntax GetMatchingDirective(TDirectiveTriviaSyntax directive, CancellationToken cancellationToken);
+        internal abstract TextSpan GetSpansForTagging(TDirectiveTriviaSyntax directive);
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Extensibility/BraceMatching/AbstractDirectiveTriviaBraceMatcher.cs]: GetSpanForTagging

File: src/EditorFeatures/Core/Extensibility/BraceMatching/AbstractDirectiveTriviaBraceMatcher.cs [hunk 6]
```diff
@@ -0,0 +1,72 @@
...
+            }
+
+            if (matchingDirective == null)
+            {
+                // one line directives, that do not have a matching begin/end directive pair.
+                return null;
+            }
+
+            return new BraceMatchingResult(
+                leftSpan: GetSpansForTagging(directive),
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Extensibility/BraceMatching/AbstractDirectiveTriviaBraceMatcher.cs]: what if the match precedes the directive?  Is left/right messed up then?

**Comment by CyrusNajmabadi** [comment]
:+1: when you make the name change and you verify that the left/right thing isn't an issue.  Also, make sure you have a test where you're on the end directive of a conditional.

**Comment by davkean** [comment]
Mac is back up
@dotnet-bot retest prtest/mac/dbg/unit32 please

File: src/EditorFeatures/Core/Extensibility/BraceMatching/AbstractDirectiveTriviaBraceMatcher.cs (hunk 5 above)
Comment (balajikris) [inline src/EditorFeatures/Core/Extensibility/BraceMatching/AbstractDirectiveTriviaBraceMatcher.cs]: Done. Thanks

File: src/EditorFeatures/Core/Extensibility/BraceMatching/AbstractDirectiveTriviaBraceMatcher.cs (hunk 6 above)
Comment (balajikris) [inline src/EditorFeatures/Core/Extensibility/BraceMatching/AbstractDirectiveTriviaBraceMatcher.cs]: This isn't an issue. `GetMatchingDirective` will not return a matching directive if its messed up and we'd deduce that condition and return. See Lines 49-55 above.

**Comment by balajikris** [comment]
@CyrusNajmabadi : thanks, made the name change, left/right thing isn't an issue and already have a test for caret at end if, it wraps over to if directive as expected. Merging.

**Comment by balajikris** [comment]
The test failure at prtest/win/dbg/unit32 is unrelated to this change. See [log](http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/2115/artifact/Binaries/Debug/xUnitResults/Roslyn.InteractiveWindow.UnitTests.dll.out.log). Investigating the failure separately.

**Comment by balajikris** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please
