### PR TITLE
Register encoding provider when `GetEncoding` throws `NotSupportedException`

### LINKED ISSUE #81381: After installing VS2026 all Builds fail with CSC : error CS2016: Code page '1252' is invalid or not installed
Created from https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2642554

_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/After-installing-VS2026-all-Builds-fail-/11002963)._

---
[severity:I'm unable to use this version] [regression] [worked-in:2022]
We have a codebase that has &lt;CodePage&gt;1252&lt;/CodePage&gt; set in all .NET-Projects. Codebase ist 50% C# with TargetFramework net48 and SDK-Style, 50% C++. Since installing the Visual Studio 2026 official release, all Visual Studios fail to build .NET-Projects with the Error 
`CSC : error CS2016: Code page '1252' is invalid or not installed`

I have reproduced the error with a fresh VM and only Visual Studio 2026 installed, creating a Hello World Console project in .NET Framework and only converting the project to SDK-Style and setting the codepage to 1252. That also does not build. If I don't use an SDK-style project everything works as intended.

The codepage is installed, I can set it on the terminal. An ASAP fix is required.

I have included a project for minimal effort replication.

---
#### Feedback Bot on 11/20/2025, 00:23 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/20/2025, 11:37 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Jared Parsons [MSFT] on 11/20/2025, 11:53 AM: 

<p>I’m sorry that you ran into this problem. Thanks for providing that simplified repro for us to look at. I believe we know the underlying problem here and we’ll be working to address this. In the meantime can you try adding the following to your <code>Directory.Build.props</code> file and it should let you work around it.</p>
<pre><code class="language-xml"><span class="hljs-tag">&lt;<span class="hljs-name">RoslynCompilerType</span>&gt;</span>Framework<span class="hljs-tag">&lt;/<span class="hljs-name">RoslynCompilerType</span>&gt;</span>
</code></pre>

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #81381

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

**Comment by AlekseyTs** [comment]
@jaredpar, @agocke Do you have any comments?

File: src/Compilers/Core/Portable/CommandLine/CommandLineParser.cs [hunk 1]
```diff
@@ -24,6 +24,7 @@ public abstract class CommandLineParser
         internal readonly bool IsScriptCommandLineParser;
         private static readonly char[] s_searchPatternTrimChars = new char[] { '\t', '\n', '\v', '\f', '\r', ' ', '\x0085', '\x00a0' };
         internal const string ErrorLogOptionFormat = "<file>[,version={1|1.0|2|2.1}]";
+        private static bool s_registeredEncodingProvider = CodePagesEncodingProvider.Instance == null;
```
Comment (jjonescz) [inline src/Compilers/Core/Portable/CommandLine/CommandLineParser.cs:27]: How can CodePagesEncodingProvider.Instance be null here? #Resolved

File: src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs [hunk 2]
```diff
@@ -5791,6 +5791,10 @@ public void Codepage()
             parsedArgs.Errors.Verify();
             Assert.Equal("Unicode (UTF-8)", parsedArgs.Encoding.EncodingName);
 
+            parsedArgs = DefaultParse(new[] { "/CodePage:1252", "a.cs" }, WorkingDirectory);
+            parsedArgs.Errors.Verify();
```
Comment (jjonescz) [inline src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs:5795]: Would this fail without the fix? #Resolved

File: src/Compilers/Core/Portable/CommandLine/CommandLineParser.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/Core/Portable/CommandLine/CommandLineParser.cs:27]: I do not control behavior of the API. In theory result of the property could be `null`. We have similar check in other places in our codebase. If it cannot be `null`, there is no harm in checking it anyway.

File: src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs:5795]: > Would this fail without the fix?

Yes, when run on CoreCLR the test fails without the fix with the error from the issue.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review

File: src/Compilers/Core/Portable/CommandLine/CommandLineParser.cs [hunk 3]
```diff
@@ -1220,10 +1221,24 @@ internal IEnumerable<CommandLineSourceFile> ParseRecurseArgument(string arg, str
...
+try_again:
                 try
                 {
                     return Encoding.GetEncoding((int)codepage);
                 }
+                catch (NotSupportedException) when (!s_registeredEncodingProvider)
+                {
+                    try
+                    {
+                        Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
```
Comment (agocke) [inline src/Compilers/Core/Portable/CommandLine/CommandLineParser.cs:1255]: Why not call RegisterProvider unconditionally before calling GetEncoding? The reason I ask is that my memory was that providing a specific encoding to the compiler was relatively rare. I think we usually don’t get a specific encoding and just assume utf8. And I think utf8 is both the most common encoding (inc ascii) and the recommended encoding.

So if we’re already in an edge case, could we assume that if someone needs a specific code page it might be a non-registered one? #Resolved

Comment (AlekseyTs) [reply src/Compilers/Core/Portable/CommandLine/CommandLineParser.cs:1255]: From documentation of the APIs, it is my understanding that calling ```Encoding.RegisterProvider``` might overwrite previous setup. So, if the environment was properly setup to support certain encoding, this call might change that setup. I.e. the encoding will be supported but by a different provider. Therefore, I felt that it might make sense to not mess with providers, unless we run into a failure.

Comment (jjonescz) [reply src/Compilers/Core/Portable/CommandLine/CommandLineParser.cs:1255]: Consider capturing this in a comment, it probably won't be obvious to future readers.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review

File: src/Compilers/Core/Portable/CommandLine/CommandLineParser.cs (hunk 3 above)
Comment (CyrusNajmabadi) [reply src/Compilers/Core/Portable/CommandLine/CommandLineParser.cs:1255]: Def agree.  The logic/flow here is complex for me (nested try/catches *with* gotos).  I think this def warrants some explanation on what's going on.
