### PR TITLE
Make method body generation not rely on destination type

### LINKED ISSUE #30750: ExtractMethodCodeRefactoringProvider threw NullReferenceException when highlighting a method invocation
**Version Used**: 

**Steps to Reproduce**:

1. Highlight the text between the '$' (remove the $ first)

``` C#
// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

using System.Collections.Immutable;

namespace Microsoft.VisualStudio.ProjectSystem.LanguageServices
{
    internal interface SimpleProjectDiff
    {
        public ProjectChangeDiff(IImmutableSet<string> addedItems, IImmutableSet<string> removedItems)
        {
            Requires.$NotEmpty$(addedItems, nameof(addedItems));
            Requires.NotEmpty(removedItems, nameof(removedItems));

            AddedItems = addedItems;
            RemovedItems = removedItems;

        }
        public IImmutableSet<string> AddedItems
        {
            get;
        }

        public IImmutableSet<string> RemovedItems
        {
            get;
        }
    }
}

```

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpTriviaResult.AnnotationResolver(SyntaxNode node,TriviaLocation location,SyntaxAnnotation annotation,SyntaxNode callsite,MethodDeclarationSyntax method)
   at Microsoft.CodeAnalysis.CSharp.ExtractMethod.CSharpMethodExtractor.CSharpTriviaResult.<>c__DisplayClass2_0.<GetAnnotationResolver>b__0(SyntaxNode node,TriviaLocation location,SyntaxAnnotation annotation)
   at Microsoft.CodeAnalysis.ExtractMethod.AbstractSyntaxTriviaService.Result.<>c__DisplayClass13_0.<RecoverTokensAtEdges>b__1(TriviaLocation location)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source,Func`2 keySelector,Func`2 elementSelector,IEqualityComparer`1 comparer)
   at Microsoft.CodeAnalysis.ExtractMethod.AbstractSyntaxTriviaService.Result.RecoverTokensAtEdges(SyntaxNode root,AnnotationResolver annotationResolver)
   at Microsoft.CodeAnalysis.ExtractMethod.AbstractSyntaxTriviaService.Result.RestoreTrivia(SyntaxNode root,AnnotationResolver annotationResolver,TriviaResolver triviaResolver)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.TriviaResult.ApplyAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.MethodExtractor.ExtractMethodAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExtractMethod.AbstractExtractMethodService`3.ExtractMethodAsync[TValidator,TExtractor,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.GetCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.ExtractMethod.ExtractMethodCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
```

### PR DESCRIPTION
**Pull request by genlu**
Fix #30750.

I think being able to extract method in an interface might be useful during a refactoring (this is how this bug was found), so I opt to make this change instead of disabling the refactoring in this scenario. Thoughts?

@dotnet/roslyn-ide @CyrusNajmabadi

### CODE REVIEW

File: src/Features/Core/Portable/GenerateMember/GenerateParameterizedMember/AbstractGenerateParameterizedMemberService.CodeAction.cs [hunk 1]
```diff
@@ -86,12 +86,14 @@ protected override async Task<Document> GetChangedDocumentAsync(CancellationToke
...
-                        new CodeGenerationOptions(afterThisLocation: _state.Location, parseOptions: syntaxTree.Options),
+                        new CodeGenerationOptions(afterThisLocation: _state.Location, generateMethodBodies: !IsInterface(_state.TypeToGenerateIn), parseOptions: syntaxTree.Options),
                         cancellationToken)
                         .ConfigureAwait(false);
 
                     return result;
                 }
+
+                bool IsInterface(INamedTypeSymbol symbol) => symbol.TypeKind == TypeKind.Interface;
             }
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/GenerateMember/GenerateParameterizedMember/AbstractGenerateParameterizedMemberService.CodeAction.cs]: I would just inline this.  Or make an isymbol extension and update everyone to use that

**Comment by genlu** [comment]
@jinujoseph @vatsalyaagrawal for approval
