### PR TITLE
remove disposal logic from recoverable tree and text

### LINKED ISSUE #2832: Contract.Fail at Microsoft.CodeAnalysis.Host.AbstractSyntaxTreeFactoryService.RecoverableSyntaxRoot`1.Recover
1. Build Roslyn.sln

2. Run `devenv /rootsuffix RoslynDev` and open Roslyn.sln in the new VS instance.

Wait for few minutes.

**Got:** VS crashes with Contract.Fail with below call stack.

**Dump shared at:** `\\manish-test\share_r\RecoverableRoot_Crash\devenv.dmp`

**Call stack:**
>   at Roslyn.Utilities.Contract.Fail(String message)
   at Roslyn.Utilities.Contract.ThrowIfNull[T](T value, String message)
   at Microsoft.CodeAnalysis.Host.AbstractSyntaxTreeFactoryService.RecoverableSyntaxRoot`1.Recover(CancellationToken cancellationToken)
   at Roslyn.Utilities.AsyncLazy`1.GetValue(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Host.RecoverableWeakValueSource`1.GetValue(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTreeFactoryServiceFactory.CSharpSyntaxTreeFactoryService.RecoverableSyntaxTree.GetRoot(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.GetRootCore(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SyntaxTree.GetRoot(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTreeFactoryServiceFactory.CSharpSyntaxTreeFactoryService.PositionalSyntaxReference.GetSyntax(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamedTypeSymbol.MakeTypeParameterConstraints(DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamedTypeSymbol.GetTypeParameterConstraintClause(Int32 ordinal)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceNamedTypeSymbol.GetTypeParameterConstraints(Int32 ordinal)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceTypeParameterSymbol.GetDeclaredConstraints()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceTypeParameterSymbol.get_HasReferenceTypeConstraint()
   at Microsoft.CodeAnalysis.CSharp.Symbols.ConstraintsHelper.CheckConstraints(Symbol containingSymbol, ConversionsBase conversions, TypeMap substitution, TypeParameterSymbol typeParameter, TypeSymbol typeArgument, Compilation currentCompilation, ArrayBuilder`1 diagnosticsBuilder, ArrayBuilder`1& useSiteDiagnosticsBuilder)
   at Microsoft.CodeAnalysis.CSharp.Symbols.ConstraintsHelper.CheckConstraints(Symbol containingSymbol, ConversionsBase conversions, TypeMap substitution, ImmutableArray`1 typeParameters, ImmutableArray`1 typeArguments, Compilation currentCompilation, ArrayBuilder`1 diagnosticsBuilder, ArrayBuilder`1& useSiteDiagnosticsBuilder, BitVector skipParameters)
   at Microsoft.CodeAnalysis.CSharp.Symbols.ConstraintsHelper.CheckTypeConstraints(NamedTypeSymbol type, ConversionsBase conversions, Compilation currentCompilation, ArrayBuilder`1 diagnosticsBuilder, ArrayBuilder`1& useSiteDiagnosticsBuilder)
   at Microsoft.CodeAnalysis.CSharp.Symbols.ConstraintsHelper.CheckConstraints(NamedTypeSymbol type, ConversionsBase conversions, CSharpSyntaxNode typeSyntax, SeparatedSyntaxList`1 typeArgumentsSyntax, Compilation currentCompilation, ConsList`1 basesBeingResolved, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.ConstructNamedType(NamedTypeSymbol type, CSharpSyntaxNode typeSyntax, SeparatedSyntaxList`1 typeArgumentsSyntax, ImmutableArray`1 typeArguments, ConsList`1 basesBeingResolved, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindGenericSimpleNamespaceOrTypeOrAliasSymbol(GenericNameSyntax node, DiagnosticBag diagnostics, ConsList`1 basesBeingResolved, NamespaceOrTypeSymbol qualifierOpt)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindNamespaceOrTypeOrAliasSymbol(ExpressionSyntax syntax, DiagnosticBag diagnostics, ConsList`1 basesBeingResolved, Boolean suppressUseSiteDiagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindTypeOrAlias(ExpressionSyntax syntax, DiagnosticBag diagnostics, ConsList`1 basesBeingResolved)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindType(ExpressionSyntax syntax, DiagnosticBag diagnostics, ConsList`1 basesBeingResolved)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindTypeArgument(TypeSyntax typeArgument, DiagnosticBag diagnostics, ConsList`1 basesBeingResolved)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindTypeArguments(SeparatedSyntaxList`1 typeArguments, DiagnosticBag diagnostics, ConsList`1 basesBeingResolved)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindGenericSimpleNamespaceOrTypeOrAliasSymbol(GenericNameSyntax node, DiagnosticBag diagnostics, ConsList`1 basesBeingResolved, NamespaceOrTypeSymbol qualifierOpt)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindNamespaceOrTypeOrAliasSymbol(ExpressionSyntax syntax, DiagnosticBag diagnostics, ConsList`1 basesBeingResolved, Boolean suppressUseSiteDiagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindTypeOrAlias(ExpressionSyntax syntax, DiagnosticBag diagnostics, ConsList`1 basesBeingResolved)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSemanticInfoSymbolInNonMemberContext(CSharpSyntaxNode node, Boolean bindVarAsAliasFirst)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSymbolInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Classification.Classifiers.NameSyntaxClassifier.ClassifyTypeSyntax(NameSyntax name, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Classification.Classifiers.NameSyntaxClassifier.ClassifyNode(SyntaxNode syntax, SemanticModel semanticModel, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.Worker.ClassifyNode(SyntaxNode syntax)
   at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.Worker.ClassifyNodeOrToken(SyntaxNodeOrToken nodeOrToken)
   at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.Worker.ProcessNodes()
   at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.Worker.Classify(Workspace workspace, SemanticModel semanticModel, TextSpan textSpan, List`1 list, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.AddSemanticClassifications(SemanticModel semanticModel, TextSpan textSpan, Workspace workspace, Func`2 getNodeClassifiers, Func`2 getTokenClassifiers, List`1 result, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.<AddSemanticClassificationsAsync>d__5.MoveNext()

### PR DESCRIPTION
**Pull request by mattwar**
Fixes #2832 

This change removed the code that was added to ensure that temporary storage gets explicitly disposed. The original change assumed that recoverable text and trees are only ever recovered once, but the truth is that they can be (and are intended to be) recovered multiple times, as once the recoverable item is stored in temporary storage, the lifetime of the data it owns is governed by the cache system and the runtime GC (via weak reference), so it can get recovered after GC more than once.

@pharring @mavasani @Pilchie @jasonmalinowski please review.

### CODE REVIEW

**Comment by pharring** [comment]
The code change looks fine. You could also remove the ```s_DisposalCount``` tracking from the TestTemporaryStorage implementation. But now it brings into question why [ITemporaryTextStorage](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Host/TemporaryStorage/ITemporaryStorage.cs,14) and [ITemporaryStreamStorage](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Host/TemporaryStorage/ITemporaryStorage.cs,22) inherit ```IDisposable```.

File: src/Workspaces/Core/Portable/Workspace/Host/SyntaxTreeFactory/AbstractSyntaxTreeFactoryService.AbstractRecoverableSyntaxRoot.cs [hunk 1]
```diff
@@ -124,10 +124,7 @@ public RecoverableSyntaxRoot<TRoot> WithSyntaxTree(IRecoverableSyntaxTree<TRoot>
 
                 using (var stream = await _storage.ReadStreamAsync(cancellationToken).ConfigureAwait(false))
                 {
-                    var retVal = RecoverRoot(stream, cancellationToken);
-                    _storage.Dispose();
-                    _storage = null;
-                    return retVal;
+                    return RecoverRoot(stream, cancellationToken);
```
Comment (pharring) [inline src/Workspaces/Core/Portable/Workspace/Host/SyntaxTreeFactory/AbstractSyntaxTreeFactoryService.AbstractRecoverableSyntaxRoot.cs]: If _storage cannot be disposed here, what's the right place to call _storage.Dispose()?

Comment (mattwar) [inline src/Workspaces/Core/Portable/Workspace/Host/SyntaxTreeFactory/AbstractSyntaxTreeFactoryService.AbstractRecoverableSyntaxRoot.cs]: There is not a right place for disposing.  A solution structure is not disposable.  We've have other services that dispose when the workspace is disposed, though that's probably not what you are looking for because that's often at app shutdown time, and its not a hard requirement to dispose a workspace either.

**Comment by pharring** [comment]
:+1:
(Needs to be ported to the stable branch)

**Comment by mattwar** [comment]
@dotnet-bot test this please
