### PR TITLE
Handle corrupted default values in metadata

### LINKED ISSUE #4196: CSC : error CS7038: Failed to emit module
After installing Visual Studio 2015 and building my project I receive the error "CSC : error CS7038: Failed to emit module".

However my solution is building fine in Visual Studio 2013.

ASP.NET webforms project in .NET 4.0

### PR DESCRIPTION
**Pull request by jaredpar**
The native compiler handled corrupted default parameter values by
substituting in default(T).  It's unclear if this was intentional
behavior in the compiler or not.

Either way though obfuscators took advantage of this behavior and at
least one prominent one will corrupt default parameter values when the
value is null.  Enough prominent libraries have shipped using such
obfuscators that it is a blocker to upgrading.  Hence we need to emulate
the native compiler behavior here.

This change is a bit large because I needed to update the test resources
with a corrupted DLL in order to test out the changes.

closes #4196

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @AlekseyTs, @gafter, @VSadov, @agocke

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs [hunk 1]
```diff
@@ -874,9 +874,15 @@ private BoundExpression GetDefaultParameterValue(CSharpSyntaxNode syntax, Parame
...
             ConstantValue defaultConstantValue = parameter.ExplicitDefaultConstantValue;
             BoundExpression defaultValue;
-
             SourceLocation callerSourceLocation;
 
+            // For compatibility with the native compiler we treat all bad imported constant
+            // values as default(T).  
+            if (defaultConstantValue != null && defaultConstantValue.IsBad)
+            {
+                defaultConstantValue = ConstantValue.Default(parameterType.SpecialType);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: Will this do the right thing for non-primitive types, a user-defined struct or class for example?

File: src/Compilers/VisualBasic/Portable/Binding/Binder_Invocation.vb [hunk 2]
```diff
@@ -3104,51 +3104,52 @@ ProduceBoundNode:
...
-                ' Only consider optional parameters when the constant value is good.  Bad constant values are ignored and result in an 
-                ' argument mismatch error.
-                If Not defaultConstantValue.IsBad Then
-
-                    Dim defaultSpecialType = defaultConstantValue.SpecialType
-                    Dim defaultArgumentType As TypeSymbol = Nothing
+                ' For compatibility with the native compiler bad metadata constants should be treated as default(T).  This 
+                ' is a possible outcome of running an obfuscator over a valid DLL 
+                If defaultConstantValue.IsBad Then
+                    defaultConstantValue = ConstantValue.Default(param.Type.SpecialType)
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Binding/Binder_Invocation.vb]: Is this going to do the right thing for non-primitive types? Consider using ConstantValue.Nothing instead.

File: src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTests.vb [hunk 3]
```diff
@@ -12850,5 +12850,34 @@ BC42104: Variable 'blah1' is used before it has been assigned a value. A null re
...
+            Dim testReference = AssemblyMetadata.CreateFromImage(TestResources.Repros.BadDefaultParameterValue).GetReference()
+            Dim compilation = CompileAndVerify(source, additionalRefs:=New MetadataReference() {testReference})
+            compilation.VerifyIL("C.Main",
+            <![CDATA[
+{
+  // Code size       12 (0xc)
+  .maxstack  2
+  IL_0000:  ldstr      "test"
+  IL_0005:  ldnull
+  IL_0006:  call       "Sub BadDefaultParameterValue.Util.M(String, String)"
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTests.vb]: Consider adding a test for user-defined class and for user-defined struct.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs (hunk 1 above)
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: No.  What is the best API to use to get essentially a `default(T)` for a given type object?

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: Try ConstantValue.Null for all types it looks like it will work.

**Comment by jaredpar** [comment]
Ping @agocke, @gafter, @VSadov

File: src/Compilers/CSharp/Test/Emit/Emit/EmitErrorTests.cs [hunk 4]
```diff
@@ -106,7 +106,11 @@ public static void Main()
     }
 }
 ";
-            VerifyEmitDiagnostics(source2, compilation1);
+            var compilation2 = CompileAndVerify(
+                source2,
+                new[] { new CSharpCompilationReference(compilation1) },
+                verify: false);
+            compilation2.Emit(expectedOutput: null, manifestResources: null, peVerify: false, expectedSignatures: null);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/Emit/EmitErrorTests.cs]: Result is not checked. Is there a reason to call Emit here?

File: src/Compilers/CSharp/Test/Emit/Emit/EmitErrorTests.cs [hunk 5]
```diff
@@ -135,7 +139,11 @@ public static void Main()
...
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/Emit/EmitErrorTests.cs]: Result is not checked. Is there a reason to call Emit here?

**Comment by AlekseyTs** [comment]
Has it been confirmed that the fix works for non-primitive structs and classes? I would really like to see regression tests added to cover these scenarios for both languages. We might be able to use compilation references to emulate "bad" constant values.

File: src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTests.vb [hunk 6]
```diff
@@ -12850,5 +12850,34 @@ BC42104: Variable 'blah1' is used before it has been assigned a value. A null re
...
+    Sub Main
+        Util.M("test")
+    End Sub
+End Module
+    </file>
+</compilation>
+
+            Dim testReference = AssemblyMetadata.CreateFromImage(TestResources.Repros.BadDefaultParameterValue).GetReference()
+            Dim compilation = CompileAndVerify(source, additionalRefs:=New MetadataReference() {testReference})
+            compilation.VerifyIL("C.Main",
```
Comment (gafter) [inline src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTests.vb]: I suggest we should prefer an executable self-verifying test rather than checking the shape of the resulting IL.

Comment (jaredpar) [inline src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTests.vb]: @gafter not sure I understand why.  In this case the core issue is whether the compiler is using the appropriate default arguments or not.  Looking at the IL is the most direct way of verifying that.

Comment (gafter) [inline src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTests.vb]: Either the behavior is correct or not. IL can change over time as the compilers change, but as long as the behavior is correct our tests should pass.

Comment (jaredpar) [inline src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTests.vb]: @gafter understood.  In this particular case changing to self verifying is about 2 hours of dev time + delaying the change for at least another day.  Would prefer to keep it as is.

Comment (gafter) [inline src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTests.vb]: ... because you'd have to produce a new "broken" test assembly? In that case OK.

**Comment by gafter** [comment]
LGTM, except where @AlekseyTs pointed out that you call Emit and ignore the result.

File: src/Compilers/CSharp/Test/Emit/Emit/EmitErrorTests.cs (hunk 4 above)
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Emit/Emit/EmitErrorTests.cs]: There is no result to check here, the return is `void`.  This `Emit` API signals failure by throwing an exception.  In both cases we are just verifying that we can emit without throwing.  Without the fix both cases will throw an exception and hence fail the test.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/Emit/EmitErrorTests.cs]: Would calling CompileAndVerify be sufficient?

Comment (jaredpar) [inline src/Compilers/CSharp/Test/Emit/Emit/EmitErrorTests.cs]: @AlekseyTs CompileAndVerify doesn't go through the Emit phase where the error occurs.

Comment (jaredpar) [inline src/Compilers/CSharp/Test/Emit/Emit/EmitErrorTests.cs]: @AlekseyTs and I looked at this and calling `CompileAndVerify` should be sufficient.  It will call through to Emit and trigger this bad code path.

**Comment by jaredpar** [comment]
@AlekseyTs added a case for a user defined struct type.

**Comment by AlekseyTs** [comment]
LGTM. BTW, it looks like there is still one redundant compilation2.Emit call.

**Comment by VSadov** [comment]
LGTM
