### PR TITLE
preserve encoding over temporary storage

### LINKED ISSUE #380: TetsTemporaryStorageText failing with null Encoding
The following failure is occurring on developer machines:

```
Microsoft.CodeAnalysis.UnitTests.TemporaryStorageServiceTests.TestTemporaryStorageText
Assert.Equal() Failure
Expected: (null)
Actual:   System.Text.UnicodeEncoding
   at Microsoft.CodeAnalysis.UnitTests.TemporaryStorageServiceTests.TestTemporaryStorage(ITemporaryStorageService temporaryStorageService, SourceText text) in E:\dd\ros-git\Src\Workspaces\CoreTest\WorkspaceServiceTests\TemporaryStorageServiceTests.cs:line 82
   at Microsoft.CodeAnalysis.UnitTests.TemporaryStorageServiceTests.TestTemporaryStorageText() in E:\dd\ros-git\Src\Workspaces\CoreTest\WorkspaceServiceTests\TemporaryStorageServiceTests.cs:line 29
Traits:
```

Disabling the suite for now.

### PR DESCRIPTION
**Pull request by heejaechang**
little bit of refactoring over temporary stroage and text factory service to preserve encoding round trip

this fixes #380 and #353

### CODE REVIEW

File: src/EditorFeatures/Test/Workspaces/TextFactoryTests.cs [hunk 1]
```diff
@@ -73,7 +72,7 @@ public void TestCreateFromTemporaryStorage()
 
                 Assert.NotSame(text, text2);
                 Assert.Equal(text.ToString(), text2.ToString());
-                Assert.Equal(text2.Encoding, Encoding.Unicode);
+                Assert.Equal(text2.Encoding, null);
```
Comment (pharring) [inline src/EditorFeatures/Test/Workspaces/TextFactoryTests.cs]: Let's add another test (or enhance this one) to test non-null encodings too.

    foreach(var encoding in new Encoding[] {
        null,
        Encoding.ASCII,
        Encoding.UTF8,
        Encoding.Unicode,
        Encoding.BigEndianUnicode})
    {
        var text = Text.SourceText.From("Hello, World!", encoding);
        // etc.

**Comment by pharring** [comment]
LGTM

File: src/EditorFeatures/Test/Workspaces/TextFactoryTests.cs (hunk 1 above)
Comment (tmeschter) [inline src/EditorFeatures/Test/Workspaces/TextFactoryTests.cs]: Yes, please do that.

**Comment by tmeschter** [comment]
LGTM

File: src/EditorFeatures/Core/Implementation/Workspaces/EditorTextFactoryService.cs [hunk 2]
```diff
@@ -72,80 +78,12 @@ private SourceText CreateTextInternal(Stream stream, Encoding encoding, Cancella
             cancellationToken.ThrowIfCancellationRequested();
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/Workspaces/EditorTextFactoryService.cs]: Can you comment this function?  I find it confusing that an Encoding is passed in, but then the code calls "detectEncodingFromBytOrderMarks" and then calls AsRoslynText, not using the encoding passed in, but instead reader.CurrentEncoding or Encoding.UTF8.

It seems like someone can be explicit about the encoding, but still have that overridden by the system.

File: src/Workspaces/Core/Portable/Workspace/Host/TextFactory/ITextFactoryService.cs [hunk 3]
```diff
@@ -28,5 +28,15 @@ internal interface ITextFactoryService : IWorkspaceService
         /// </exception>
         /// <exception cref="IOException">An IO error occurred while reading from the stream.</exception>
         SourceText CreateText(Stream stream, Encoding defaultEncoding, CancellationToken cancellationToken = default(CancellationToken));
+
+
+        /// <summary>
+        /// Creates <see cref="SourceText"/> from a reader.
+        /// </summary>
+        /// <param name="reader">The <see cref="TextReader"/> to read the text from.</param>
+        /// <param name="encoding">Specifies an encoding for the <see cref="SourceText"/>SourceText. it could be even null</param>
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Workspace/Host/TextFactory/ITextFactoryService.cs]: ~~it could be even null~~

"If null, the encoding will be determined based on the contents of the reader."

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs [hunk 4]
```diff
@@ -135,6 +139,69 @@ public Task WriteTextAsync(SourceText text, CancellationToken cancellationToken
...
                     return Task.Factory.StartNew(() => WriteText(text, cancellationToken), cancellationToken, TaskCreationOptions.None, TaskScheduler.Default);
                 }
+
+                private unsafe TextReader CreateTextReaderFromTemporaryStorage(ISupportDirectMemoryAccess accessor, int streamLength, CancellationToken cancellationToken)
+                {
+                    char* src = (char*)accessor.GetPointer();
+
+                    // BOM: Unicode, little endian
+                    // Skip the BOM when creating the reader
+                    Debug.Assert(*src == 0xFEFF);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: How are you certain that this will be true?

File: src/Workspaces/Core/Portable/Workspace/Host/TextFactory/TextFactoryService.cs [hunk 5]
```diff
@@ -17,5 +17,12 @@ public SourceText CreateText(Stream stream, Encoding defaultEncoding, Cancellati
             cancellationToken.ThrowIfCancellationRequested();
             return SourceText.From(stream, defaultEncoding);
         }
+
+        public SourceText CreateText(TextReader reader, Encoding encoding, CancellationToken cancellationToken = default(CancellationToken))
+        {
+            cancellationToken.ThrowIfCancellationRequested();
```
Comment (jaredpar) [inline src/Workspaces/Core/Portable/Workspace/Host/TextFactory/TextFactoryService.cs]: Do we really need this token?  Is it just coming as a part of an interface contract?

Comment (mattwar) [inline src/Workspaces/Core/Portable/Workspace/Host/TextFactory/TextFactoryService.cs]: The text reader could represent a large file that get's read in a loop.  We need ability to quickly abort work.

Comment (jaredpar) [inline src/Workspaces/Core/Portable/Workspace/Host/TextFactory/TextFactoryService.cs]: @mattwar but that token isn't cancelling the read, it just cancels before we start the read.  Unless I'm missing the calling context.

File: src/EditorFeatures/Test/Workspaces/TextFactoryTests.cs (hunk 1 above)
Comment (heejaechang) [inline src/EditorFeatures/Test/Workspaces/TextFactoryTests.cs]: done

File: src/EditorFeatures/Core/Implementation/Workspaces/EditorTextFactoryService.cs (hunk 2 above)
Comment (heejaechang) [inline src/EditorFeatures/Core/Implementation/Workspaces/EditorTextFactoryService.cs]: default encoding is something it use if it can't figure out Encoding from stream. that is why it is called default encoding. I will add more comments.

Comment (heejaechang) [inline src/EditorFeatures/Core/Implementation/Workspaces/EditorTextFactoryService.cs]: New API I added. CreateText(TextReader reader ... ) is the API people should use if they want to set encoding explicitly. this API doesnt have ambiguity where given Encoding and encoding embedded in the stream is different.

the first API is intended to be used in a situation where you just open a file (FileStream) and want to create a SourceText. the default encoding given is basically saying, if you can't figure out Encoding from the stream I gave you, assume it is the default encoding.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs (hunk 4 above)
Comment (heejaechang) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.cs]: because we are the one who write in and read it and no-one else has access to it.

File: src/Workspaces/Core/Portable/Workspace/Host/TextFactory/ITextFactoryService.cs (hunk 3 above)
Comment (heejaechang) [inline src/Workspaces/Core/Portable/Workspace/Host/TextFactory/ITextFactoryService.cs]: no, there is no encoding associated with TextReader. Encoding is something that is used to convert text to stream and via versa. TextReader abstract that out, so consumer of the TextReader doesn't need to care about Encoding.

the encoding given is for SourceText which will be used later when we convert sourcetext to stream. (ex, to calculate checksum or write to a file and etc)

File: src/Workspaces/Core/Portable/Workspace/Host/TextFactory/TextFactoryService.cs (hunk 5 above)
Comment (heejaechang) [inline src/Workspaces/Core/Portable/Workspace/Host/TextFactory/TextFactoryService.cs]: ya, but it is interface, there could be an implementer that read through chunk of string and check cancellation.
