### PR TITLE
Fix crash in is operator used with tuples

### LINKED ISSUE #14252: Code generation for type pattern: optimize value type cases
Currently, code generated for simple patterns like this:

``` c#
public int M(object o) => (o is int x) ? x : -1;
```

...actually involves unboxing into `Nullable<int>` and checking for it's members:

``` c#
public int M(object o)
{
  int? num = o as int?;
  int valueOrDefault = num.GetValueOrDefault();
  return num.HasValue ? valueOrDefault : -1;
}
```

This generated code seems to be verbose and suboptimal, there is no real need to rely on runtime's support of unboxing object references into `Nullable<T>` value and manipulate with it where simple unboxing is required. Equivalent method takes 2 times less MSIL instructions:

``` c#
public int M2(object o) => o is int ? (int) o : -1;
```

### LINKED ISSUE #16129: pattern matching with structs causes unnecessary boxing, nullable conversions
```c#
using System;

class C
{
    static void Main()
    {
        if (TrySomething() is ValueTuple<string, bool> v && v.Item2 == true)
        {
            System.Console.Write(v.Item1 == null);
        }
    }

    static (string Value, bool Success) TrySomething()
    {
        return (null, true);
    }
}
```

For the Main I'd expect to see an IL equivalent of

```C#
    static void Main()
    {
        {
            ValueTuple<string, bool> v = TrySomething();
            if (v.Item2 == true)
            {
                System.Console.Write(v.Item1 == null);
            }
        }
    }
```

instead I see (decompiled)
```C#
    private static void Main()
    {
        ValueTuple<string, bool>? valueTuple = (object)C.TrySomething() as ValueTuple<string, bool>?;
        ValueTuple<string, bool> valueOrDefault = valueTuple.GetValueOrDefault();
        bool flag = valueTuple.HasValue && valueOrDefault.Item2;
        if (flag)
        {
            Console.Write(valueOrDefault.Item1 == null);
        }
    }
```

### LINKED ISSUE #18944: Struct unboxing - very bad performance of pattern matching
**Version Used**: 15.1 (26403.7)

Suppose we have following struct:
```C#
struct MyStruct
{
    public readonly int Value;

    public bool Equals1(object obj)
    {
        if (obj is MyStruct)
        {
            return Equals((MyStruct)obj);
        }
        return false;
    }

    public bool Equals2(object obj)
    {
        try
        {
            return Equals((MyStruct)obj);
        }
        catch
        {
            return false;
        }
    }

    public bool Equals3(object obj)
    {
        var sn = obj as MyStruct?;
        return sn.HasValue ? Equals(sn.Value) : false;
    }

    public bool Equals4(object obj)
    {
        return obj is MyStruct s ? Equals(s) : false;
    }

    public bool Equals(MyStruct other)
    {
        return Value == other.Value;
    }
}
```

`Equals1` goes against recommendation for not using "is" and than "cast" but is the fastest one.
`Equals2` looks stupid but is the second fastest (assuming `obj` is always `MyStruct`).
`Equals3` looks more clever (i was using it before C# 7) but it is MUCH MUCH slower than `Equals1` and even `Equals2` (found out just now).
`Equals4` is the the slowest one. It is translated to similar MSIL as `Equals3` but there is one more local variable.

I believe the syntax of `Equals4` should be the recommended one (or any better idea?).
Not sure why it's so slow, but probably because of working with `Nullable<MyStruct>`.
Shouldn't compiler emit more efficient MSIL for this cases?

Here is my measurements (Win7, Intel Xeon E5-1650 v3):
Release/32bit:
Equals1: 367.0922ms
Equals2: 1084.6545ms
Equals3: 10767.0583ms
Equals4: 11156.0162ms
Equals: 93.8451ms

Release/64bit:
Equals1: 279.8061ms
Equals2: 1052.9261ms
Equals3: 8290.5574ms
Equals4: 8774.8108ms
Equals: 95.9861ms

Measuring code looks like this:
```C#
var watch = new Stopwatch();
var a = new MyStruct();
var b = (object)new MyStruct();

a.Equals1(b);
a.Equals2(b);
a.Equals3(b);
a.Equals4(b);

const int Count = 300000000;

watch.Restart();
for (int i = 0; i < Count; i++)
{
    a.Equals1(b);
}
Console.WriteLine($"Equals1: {watch.Elapsed.TotalMilliseconds}ms");

watch.Restart();
for (int i = 0; i < Count; i++)
{
    a.Equals2(b);
}
Console.WriteLine($"Equals2: {watch.Elapsed.TotalMilliseconds}ms");

watch.Restart();
for (int i = 0; i < Count; i++)
{
    a.Equals3(b);
}
Console.WriteLine($"Equals3: {watch.Elapsed.TotalMilliseconds}ms");

watch.Restart();
for (int i = 0; i < Count; i++)
{
    a.Equals4(b);
}
Console.WriteLine($"Equals4: {watch.Elapsed.TotalMilliseconds}ms");

watch.Restart();
for (int i = 0; i < Count; i++)
{
    a.Equals(a);
}
Console.WriteLine($"Equals: {watch.Elapsed.TotalMilliseconds}ms");
```

### LINKED ISSUE #19151: Matching an expression of type `byte?` with a pattern of type `int` should not be allowed
**Version Used**: 

15.3 (master)

**Steps to Reproduce**:

1. Compile the following
``` c#
    public static void M(byte? x)
    {
        switch (x)
        {
            case int i:
                Console.Write(i);
                break;
        }
    }
```

**Expected Behavior**:

Compile-time error "a value of type `byte?` can never be handled by a pattern of type `int`".

**Actual Behavior**:

Compiles with no error. Pattern never matches.

### LINKED ISSUE #19273: Merge subsumption implementations
There are a few different implementations of subsumption in the patter-matching implementation:

- One in binding
- One related implementation for warning with the old-style operator `is`
- One in lowering

They should be consolidated. It is likely we can make things more precise in the process.

### LINKED ISSUE #19310: Crash in `is` operator used with tuple
**Version Used**: 

VS2015 most recent update

**Steps to Reproduce**:

1. Type the following statements
``` c#
var x = (1, 2);
if (x is ValueTuple<long, long>) { }
```

**Expected Behavior**:

Compiler reports "warning, the given expression is never of the provided (long, long) type."

**Actual Behavior**:

Visual Studio crashes.

### PR DESCRIPTION
**Pull request by gafter**
**Customer scenario**

Certain patterns of erroneous pattern-matching were not previously diagnosed. Specifically, when you match a nullable of one integral type with a declaration pattern of another integral type, there was no error. We introduce this error. This is a breaking change in a scenario related to the recently-released pattern-matching feature, so we would like to take the break as soon as possible so that customers do not rely on being able to write the erroneous code. We do not believe the pattern of code is very likely to arise in practice.

This PR also fixes a crash in the existing `is` operator when used with tuple types.

**Bugs this fixes:**

* Fixes crash in `is` operator used with tuples
Fixes #19310

* Matching an expression of type `byte?` with a pattern of type `int` should not be allowed
Fixes #19151

* Unify subsumption implementations
Fixes #19273

* Greatly improved code gen for value type pattern match
Fixes #16129
Fixes #18944
Fixes #14252

**Workarounds, if any**

N/A

**Risk**

The purpose of the change is to reduce future risk. Also, because we now combine what were previously three separate implementations, we have one third fewer places there could be bugs.

**Performance impact**

None expected, as there are only small changes to the code paths taken during compilation.

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

For the crash, we did not test scenarios involving mixing tuples with the existing `is` operator.

**How was the bug found?**

I found the crash reviewing the existing code while preparing the fix for the other two issues.

### CODE REVIEW

**Comment by gafter** [comment]
Also fixes #16129.

**Comment by gafter** [comment]
That ubuntu_14_debug_prtest failure is a big WTF.

``` none
21:41:56 
   Microsoft.CodeAnalysis.CSharp.UnitTests.Declarations.SourcePlusMetadataTests.InterfaceName [FAIL]
21:41:56       Assert.Equal() Failure
21:41:56       Expected: System.IComparable
21:41:56       Actual:   System.IComparable
21:41:56       Stack Trace:
21:41:56             at Microsoft.CodeAnalysis.CSharp.UnitTests.Declarations.SourcePlusMetadataTests.InterfaceName()
```

**Comment by gafter** [comment]
@dotnet-bot please test ubuntu_14_debug_prtest

File: docs/compilers/CSharp/Compiler Breaking Changes - post VS2017.md [hunk 1]
```diff
@@ -14,3 +14,8 @@ For instance, `var t = (a, b.c, this.d);` will produce a tuple with element name
 Consider the case where the type of `a` is `System.Func<bool>` and you write `var local = t.a();`. This will now find the first element of the tuple and invoke it, whereas previously it could only mean "invoke an extension method named 'a'".
 
 - https://github.com/dotnet/roslyn/issues/16870 In C# 7.0 and before C# 7.1, the compiler accepted self-assignments in deconstruction-assignment. The compiler now produces a warning for that. For instance, in `(x, y) = (x, 2);`.
+
+- The compiler is now more precise in detecting erroneous pattern-matching operations because the expression could not possibly match the pattern. The following situations now cause an error:
```
Comment (jcouv) [inline docs/compilers/CSharp/Compiler Breaking Changes - post VS2017.md]: Consider adding a link to one representative issue, so that it is easier to pull for more information/details.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs [hunk 2]
```diff
@@ -223,13 +236,13 @@ BoundExpression MakeIsDeclarationPattern(SyntaxNode syntax, BoundExpression lowe
...
+                var objectType = _factory.SpecialType(SpecialType.System_Object);
                 var s = _factory.SynthesizedLocal(_factory.SpecialType(SpecialType.System_Boolean), syntax);
-                var i = _factory.SynthesizedLocal(tmpType, syntax); // we copy the input to avoid double evaluation
+                var i = _factory.SynthesizedLocal(objectType, syntax); // we copy the input to avoid double evaluation
                 return _factory.Sequence(
                     ImmutableArray.Create(s, i),
                     ImmutableArray.Create<BoundExpression>(
-                        _factory.AssignmentExpression(_factory.Local(i), _factory.Convert(tmpType, loweredInput)),
+                        _factory.AssignmentExpression(_factory.Local(i), _factory.Convert(objectType, loweredInput)),
                         _factory.AssignmentExpression(loweredTarget, _factory.Conditional(
```
Comment (alrz) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: What it would take to remove `loweredTarget` local?

Comment (alrz) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: What it would take to remove the need for `loweredTarget` local?

File: docs/compilers/CSharp/Compiler Breaking Changes - post VS2017.md (hunk 1 above)
Comment (gafter) [inline docs/compilers/CSharp/Compiler Breaking Changes - post VS2017.md]: There is only one issue, and it doesn't have more information, but I'll add a link.

File: src/Compilers/CSharp/Portable/Errors/ErrorCode.cs [hunk 3]
```diff
@@ -1468,6 +1468,8 @@ internal enum ErrorCode
         ERR_VoidInTuple = 8210,
         #endregion more stragglers for C# 7
 
+        #region diagnostics introduced for C# 7.1
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Errors/ErrorCode.cs]: Although I did some compaction on bottom of the list, I just noticed the gap from 8210 to 8300.
Opened [https://github.com/dotnet/roslyn/issues/19523](https://github.com/dotnet/roslyn/issues/19523) to compact more.

**Comment by gafter** [comment]
This appears to fix #19122 as well.

**Comment by gafter** [comment]
@AlekseyTs @dotnet/roslyn-compiler May I please have a couple of reviews for this fix for 7.1?

**Comment by gafter** [comment]
@AlekseyTs @dotnet/roslyn-compiler May I please have a couple of reviews of this fix for 7.1?

**Comment by gafter** [comment]
This change has been approved by the Compatibility Council.

File: src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs [hunk 4]
```diff
@@ -2778,6 +2791,11 @@ internal static ConstantValue GetIsOperatorConstantResult(TypeSymbol operandType
 
             Debug.Assert((object)operandType != null);
 
+            operandCouldBeNull =
+                operandCouldBeNull &&
+                operandType.CanContainNull() && // a value type is never null
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs]: >a value type is never null [](start = 51, length = 26)

Unless it is nullable, right?

**Comment by MeiChin-Tsai** [comment]
@gafter Regarding the risk, how confident that we feel? Reading from the template, reducing future risk does not imply risk of fix is low. thx.

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 5]
```diff
@@ -171,58 +171,71 @@ internal BoundExpression ConvertPatternExpression(TypeSymbol inputType, CSharpSy
...
+            Conversions conversions,
+            TypeSymbol expressionType,
+            TypeSymbol patternType,
+            ref HashSet<DiagnosticInfo> useSiteDiagnostics,
+            out Conversion conversion,
+            ConstantValue operandConstantValue = null,
+            bool operandCouldBeNull = false)
+        {
+            Debug.Assert((object)expressionType != null);
+            if (expressionType.TypeKind == TypeKind.Dynamic)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: >expressionType.TypeKind == TypeKind.Dynamic [](start = 16, length = 43)

```expressionType.IsDynamic()```?

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 6]
```diff
@@ -171,58 +171,71 @@ internal BoundExpression ConvertPatternExpression(TypeSymbol inputType, CSharpSy
...
+            {
+                // if operand is the dynamic type, we do the same thing as though it were object
+                expressionType = conversions.CorLibrary.GetSpecialType(SpecialType.System_Object);
+            }
+
+            if ((object)expressionType == (object)patternType)
+            {
+                conversion = Conversion.Identity;
+                return true;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: >return true; [](start = 16, length = 12)

It feels like ClassifyConversionFromType below can still yield Identity conversion, then operandConstantValue and operandCouldBeNull are going to be taken into consideration. It is not clear why they shouldn't be taken into consideration here.

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 7]
```diff
@@ -171,58 +171,71 @@ internal BoundExpression ConvertPatternExpression(TypeSymbol inputType, CSharpSy
                 }
 
                 HashSet<DiagnosticInfo> useSiteDiagnostics = null;
-                Conversion conversion =
-                    operand != null
-                    ? this.Conversions.ClassifyConversionFromExpression(operand, patternType, ref useSiteDiagnostics, forCast: true)
-                    : this.Conversions.ClassifyConversionFromType(operandType, patternType, ref useSiteDiagnostics, forCast: true);
+                var matchPossible = ExpressionOfTypeMatchesPatternType(Conversions, operandType, patternType, ref useSiteDiagnostics, out var conversion, operand.ConstantValue, operandCouldBeNull: true);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: >var [](start = 16, length = 3)

Please spell out the type.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: >var [](start = 138, length = 3)

Please spell out the type.

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 8]
```diff
@@ -171,58 +171,71 @@ internal BoundExpression ConvertPatternExpression(TypeSymbol inputType, CSharpSy
...
-                        // these are the conversions allowed by a pattern match
-                        break;
-                    case ConversionKind.DefaultOrNullLiteral:
-                        throw ExceptionUtilities.UnexpectedValue(conversion.Kind);
-                    //case ConversionKind.ExplicitNumeric:  // we do not perform numeric conversions of the operand
-                    //case ConversionKind.ImplicitConstant:
-                    //case ConversionKind.ImplicitNumeric:
-                    default:
-                        if (operandType.ContainsTypeParameter() || patternType.ContainsTypeParameter())
+                    if (conversion.Kind == ConversionKind.NoConversion && (operandType.ContainsTypeParameter() || patternType.ContainsTypeParameter()))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: >conversion.Kind == ConversionKind.NoConversion [](start = 24, length = 46)

```!conversion.Exists```?

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs [hunk 9]
```diff
@@ -246,7 +250,9 @@ private DecisionTree AddByValue(DecisionTree.ByType byType, BoundConstantPattern
                     case true:
                         if (decision.MatchIsComplete)
                         {
-                            return null;
+                            // Subsumed case have been eliminated by semantic analysis.
+                            throw ExceptionUtilities.Unreachable;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: >throw ExceptionUtilities.Unreachable; [](start = 28, length = 37)

Would it be less risky to assert instead?

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs [hunk 10]
```diff
@@ -246,7 +250,9 @@ private DecisionTree AddByValue(DecisionTree.ByType byType, BoundConstantPattern
...
+                            // return null;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: >// return null; [](start = 28, length = 15)

We probably shouldn't leave commented out code. Remove?

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs [hunk 11]
```diff
@@ -272,12 +278,27 @@ private DecisionTree AddByValue(DecisionTree.ByType byType, BoundConstantPattern
...
+                switch (ExpressionOfTypeMatchesPatternType(value.Value.Type, matchedType, ref _useSiteDiagnostics))
                 {
-                    // because there is overlap, we cannot reuse some earlier entry
-                    break;
+                    case true:
+                        if (decision.MatchIsComplete)
+                        {
+                            // we should have reported this case as subsumed already.
+                            throw ExceptionUtilities.Unreachable;
+                            // return null;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: >// return null; [](start = 28, length = 15)

Same comments here.

File: src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs [hunk 12]
```diff
@@ -1132,6 +1138,15 @@ public BoundExpression Convert(TypeSymbol type, BoundExpression arg, Conversion
                 return Null(type);
             }
 
+            if (conversion.Kind == ConversionKind.ExplicitNullable &&
+                arg.Type.IsNullableType() &&
+                arg.Type.GetNullableUnderlyingType().Equals(type, TypeCompareKind.IgnoreDynamicAndTupleNames))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs]: >IgnoreDynamicAndTupleNames [](start = 82, length = 26)

I think we should use AllIgnoreOptions here.

File: src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs [hunk 13]
```diff
@@ -1132,6 +1138,15 @@ public BoundExpression Convert(TypeSymbol type, BoundExpression arg, Conversion
...
+            {
+                // A conversion to unbox a nullable value is produced when binding a pattern-matching
+                // operation from an operand of type T? to a pattern of type T.
+                return this.Call(arg, this.SpecialMethod(CodeAnalysis.SpecialMember.System_Nullable_T_get_Value).AsMember((NamedTypeSymbol)arg.Type));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs]: >CodeAnalysis.SpecialMember.System_Nullable_T_get_Value [](start = 57, length = 54)

Please add a test that hits this code path with this member missing.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs [hunk 14]
```diff
@@ -142,35 +142,72 @@ private BoundExpression CompareWithConstant(BoundExpression input, BoundExpressi
...
-            switch (_compilation.Conversions.ClassifyBuiltInConversion(sourceType, targetType, ref ignoredDiagnostics).Kind)
-            {
-                case ConversionKind.Boxing:
-                case ConversionKind.ImplicitReference:
-                case ConversionKind.Identity:
-                    return true;
-                default:
-                    return false;
-            }
+            var sourceType = source.Type.IsDynamic() ? _compilation.GetSpecialType(SpecialType.System_Object) : source.Type;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: >source.Type [](start = 29, length = 11)

Is there a guarantee that ```source.Type``` is not null?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs [hunk 15]
```diff
@@ -142,35 +142,72 @@ private BoundExpression CompareWithConstant(BoundExpression input, BoundExpressi
...
-            if (MatchIsIrrefutable(loweredInput.Type, loweredTarget.Type, requiresNullTest))
+            if (matchConstantValue == true)
             {
-                var convertedInput = _factory.Convert(loweredTarget.Type, loweredInput);
-                var assignment = _factory.AssignmentExpression(loweredTarget, convertedInput);
-                return requiresNullTest
-                    ? _factory.ObjectNotEqual(assignment, _factory.Null(type))
-                    : _factory.MakeSequence(assignment, _factory.Literal(true));
+                requiresNullTest = requiresNullTest && MatchConstantValue(loweredInput, type, true) != true;
+                if (loweredInput.Type.IsNullableType())
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: >if (loweredInput.Type.IsNullableType()) [](start = 16, length = 39)

Are all branches, including nested ifs and conditional expressions, covered by tests?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_PatternSwitchStatement.cs [hunk 16]
```diff
@@ -392,7 +392,8 @@ private void LowerConstantValueDecision(DecisionTree.ByValue byValue)
                     {
                         var loweredRight = kv.Key;
                         var loweredLeft = kv.Value;
-                        loweredRight = _factory.Convert(loweredLeft.Type, loweredRight);
+                        //loweredRight = _factory.Convert(loweredLeft.Type, loweredRight);
+                        Debug.Assert(loweredLeft.Type.Equals(loweredRight.Type, TypeCompareKind.IgnoreDynamicAndTupleNames));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_PatternSwitchStatement.cs]: >IgnoreDynamicAndTupleNames [](start = 96, length = 26)

I think we should use AllIgnoreOptions here.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_PatternSwitchStatement.cs [hunk 17]
```diff
@@ -392,7 +392,8 @@ private void LowerConstantValueDecision(DecisionTree.ByValue byValue)
                     {
                         var loweredRight = kv.Key;
                         var loweredLeft = kv.Value;
-                        loweredRight = _factory.Convert(loweredLeft.Type, loweredRight);
+                        //loweredRight = _factory.Convert(loweredLeft.Type, loweredRight);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_PatternSwitchStatement.cs]: >//loweredRight = _factory.Convert(loweredLeft.Type, loweredRight); [](start = 24, length = 66)

Please remove obsolete code.

File: src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs [hunk 18]
```diff
@@ -31,16 +31,7 @@ static class C {
             compilation.GetDiagnostics().Verify();
             compilation.GetEmitDiagnostics().Verify(
                 // warning CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.
-                Diagnostic(ErrorCode.WRN_NoRuntimeMetadataVersion).WithLocation(1, 1),
-                // (9,48): error CS0518: Predefined type 'System.Nullable`1' is not defined or imported
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs]: >// (9,48): error CS0518: Predefined type 'System.Nullable`1' is not defined or imported [](start = 16, length = 87)

It looks like we lost tests for error scenarios like this one, none of them are hitting the interesting code paths. We should come up with new scenarios that do.

File: src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs (hunk 4 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs]: Yes. I meant the comment to give the reader a hint why the method is called, not to precisely specify the called method.

File: src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs [hunk 19]
```diff
@@ -31,16 +31,7 @@ static class C {
...
-                //     public static bool M() => ((object)123) is int i;
-                Diagnostic(ErrorCode.ERR_PredefinedTypeNotFound, "int i").WithArguments("System.Nullable`1").WithLocation(9, 48),
-                // (9,48): error CS0656: Missing compiler required member 'System.Nullable`1.GetValueOrDefault'
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs]: >// (9,48): error CS0656: Missing compiler required member 'System.Nullable`1.GetValueOrDefault' [](start = 16, length = 95)

It looks like we lost tests for error scenarios like this one, none of them are hitting the interesting code paths. We should come up with new scenarios that do.

File: src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs [hunk 20]
```diff
@@ -31,16 +31,7 @@ static class C {
...
-                //     public static bool M() => ((object)123) is int i;
-                Diagnostic(ErrorCode.ERR_MissingPredefinedMember, "int i").WithArguments("System.Nullable`1", "GetValueOrDefault").WithLocation(9, 48),
-                // (9,48): error CS0656: Missing compiler required member 'System.Nullable`1.get_HasValue'
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs]: >// (9,48): error CS0656: Missing compiler required member 'System.Nullable`1.get_HasValue' [](start = 16, length = 90)

It looks like we lost tests for error scenarios like this one, none of them are hitting the interesting code paths. We should come up with new scenarios that do.

**Comment by gafter** [comment]
> Regarding the risk, how confident that we feel? Reading from the template, reducing future risk does not imply risk of fix is low. thx.

@MeiChin-Tsai This fixes a few reported crashes. I expect that the compiler after this fix will be much more stable in this area than before the fix. The most significant part of this change replaces recently written code with slightly modified code that had been in production use for a long time.

File: src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs [hunk 21]
```diff
@@ -9095,500 +9108,134 @@ public static string M2(object o)
...
+  IL_008d:  stloc.s    V_7
+  IL_008f:  br.s       IL_0091
+  IL_0091:  ldloc.s    V_7
+  IL_0093:  ret
 }"
             );
         }
 
-        [Fact, WorkItem(19280, "https://github.com/dotnet/roslyn/issues/19280")]
-        public void ShareLikeKindedTemps_01()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs]: >ShareLikeKindedTemps_01 [](start = 20, length = 23)

I am not sure what happened with this test, it looks like it was deleted. Intentional?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 22]
```diff
@@ -4780,10 +4800,13 @@ public static void Main(string[] args)
             CreateCompilationWithMscorlib45(program).VerifyDiagnostics(
                 // (10,18): error CS0266: Cannot implicitly convert type 'double' to 'int?'. An explicit conversion exists (are you missing a cast?)
                 //             case double.NaN:
-                Diagnostic(ErrorCode.ERR_NoImplicitConvCast, "double.NaN").WithArguments("double", "int?").WithLocation(10, 18),
-                // (13,18): error CS8121: An expression of type int? cannot be handled by a pattern of type string.
+                Diagnostic(ErrorCode.ERR_NoImplicitConvCast, "double.NaN").WithArguments("double", "int?"),
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: >Diagnostic(ErrorCode.ERR_NoImplicitConvCast, "double.NaN").WithArguments("double", "int?"), [](start = 16, length = 91)

Location is lost, please restore.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 23]
```diff
@@ -4780,10 +4800,13 @@ public static void Main(string[] args)
...
+                // (13,18): error CS8121: An expression of type 'int?' cannot be handled by a pattern of type 'string'.
                 //             case string _:
-                Diagnostic(ErrorCode.ERR_PatternWrongType, "string").WithArguments("int?", "string").WithLocation(13, 18)
+                Diagnostic(ErrorCode.ERR_PatternWrongType, "string").WithArguments("int?", "string"),
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: >Diagnostic(ErrorCode.ERR_PatternWrongType, "string").WithArguments("int?", "string"), [](start = 16, length = 85)

Location is lost, please restore.

File: src/Compilers/CSharp/Test/Semantic/Semantics/SwitchTests.cs [hunk 24]
```diff
@@ -332,7 +350,7 @@ public void foo2(char i)
                 Diagnostic(ErrorCode.ERR_NoImplicitConvCast, "97.0f").WithArguments("float", "char").WithLocation(34, 18),
                 // (38,18): error CS0266: Cannot implicitly convert type 'int' to 'char'. An explicit conversion exists (are you missing a cast?)
                 //             case 97:
-                Diagnostic(ErrorCode.ERR_NoImplicitConvCast, "97").WithArguments("int", "char").WithLocation(38, 18)
+                Diagnostic(ErrorCode.ERR_NoImplicitConvCast, "97").WithArguments("int", "char")
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/SwitchTests.cs]: >Diagnostic(ErrorCode.ERR_NoImplicitConvCast, "97").WithArguments("int", "char") [](start = 16, length = 79)

Location is lost, please restore.

**Comment by AlekseyTs** [comment]
Done with review pass.

File: src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs (hunk 13 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs]: I'm not confident that can occur, as it is likely to be found missing at a higher level in the caller. However, I'll add tests (`MissingNullable_03`) that *would* fail here if not for the fact that it is handled earlier.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs (hunk 14 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: Yes. There are assertions in callers and in methods called from here (e.g. `ClassifyConversionFromType`)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs (hunk 15 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: Yes

File: src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs (hunk 18 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs]: We aren't hitting them because those code paths don't exist any longer. We use a different lowering strategy for this code now.

File: src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs (hunk 19 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs]: We aren't hitting them because those code paths don't exist any longer. We use a different lowering strategy for this code now.

File: src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs (hunk 20 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs]: We aren't hitting them because those code paths don't exist any longer. We use a different lowering strategy for this code now.

File: src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs (hunk 21 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs]: I think this was a merge error. Adding it again (and the next test).

**Comment by MeiChin-Tsai** [comment]
approved.

**Comment by gafter** [comment]
@AlekseyTs The PR has been modified in response to your review comments. Do you have anything else?

@dotnet/roslyn-compiler May I please have a second reviewer?

**Comment by gafter** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by AlekseyTs** [comment]
> The PR has been modified in response to your review comments. Do you have anything else?

In order to answer this question or to sign-off, I need to do another review pass. It is on my list of things to do.

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs (hunk 6 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: @gafter I see that you deleted the code. Could you please confirm that you added a test that would  fail without this fix?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs [hunk 25]
```diff
@@ -142,35 +142,72 @@ private BoundExpression CompareWithConstant(BoundExpression input, BoundExpressi
...
+                {
+                    var getValueOrDefault = _factory.SpecialMethod(SpecialMember.System_Nullable_T_GetValueOrDefault).AsMember((NamedTypeSymbol)loweredInput.Type);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: >var getValueOrDefault = _factory.SpecialMethod(SpecialMember.System_Nullable_T_GetValueOrDefault).AsMember((NamedTypeSymbol)loweredInput.Type); [](start = 20, length = 143)

Do we have a test that hits this code path with missing SpecialMember.System_Nullable_T_GetValueOrDefault?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs [hunk 26]
```diff
@@ -142,35 +142,72 @@ private BoundExpression CompareWithConstant(BoundExpression input, BoundExpressi
...
+                    if (requiresNullTest)
+                    {
+                        //bool Is<T>(T? input, out T output) where T : struct
+                        //{
+                        //    output = input.GetValueOrDefault();
+                        //    return input.HasValue;
+                        //}
+
+                        var input = _factory.SynthesizedLocal(loweredInput.Type, syntax); // we copy the input to avoid double evaluation
+                        var getHasValue = _factory.SpecialMethod(SpecialMember.System_Nullable_T_get_HasValue).AsMember((NamedTypeSymbol)loweredInput.Type);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: >var getHasValue = _factory.SpecialMethod(SpecialMember.System_Nullable_T_get_HasValue).AsMember((NamedTypeSymbol)loweredInput.Type); [](start = 24, length = 132)

Do we have a test that hits this code path with missing SpecialMember.System_Nullable_T_get_HasValue?

**Comment by AlekseyTs** [comment]
Please answer a new question https://github.com/dotnet/roslyn/pull/19413#discussion_r117360456, the thread appears as "outdated".

**Comment by AlekseyTs** [comment]
Done with review pass. Just have three questions around test coverage above.

**Comment by gafter** [comment]
The question was
> @gafter I see that you deleted the code. Could you please confirm that you added a test that would fail without this fix?

That is not possible. There are two call sites for this method, one of which passes parameters such that the extra conditions later do not make a difference in the returned value. The other call site treats `true` and `null` return values the same, so it would not care.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs (hunk 25 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: Yes (see `MissingNullable_03`).

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs (hunk 26 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: _factory.SpecialMethod handles this one the same way it handles the one you asked about a few lines earlier. Every call to that helper method is handled the same way in LocalRewriter (and causes the rest of the calling method to be skipped).

Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: Also see https://github.com/dotnet/roslyn/pull/19413/commits/9e05b042ba33f7ec3de69f46a067ee9491dc47a8 which adds a test that triggers the requested condition.

**Comment by gafter** [comment]
retest windows_release_vs-integration_prtest please

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a second review?

**Comment by gafter** [comment]
retest windows_release_vs-integration_prtest please

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a second review?

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs (hunk 7 above)
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: I think Aleksey's feedback still applies in latest iteration. Please use bool? instead of var here.

---
In reply to: [116913667](https://github.com/dotnet/roslyn/pull/19413#discussion_r116913667) [](ancestors = 116913667)
