### PR TITLE
Fix couple of bugs in unused private members analyzer

### LINKED ISSUE #31572: VS2019 thinks `int Main` is unused
**Version Used**: 

Microsoft Visual Studio Enterprise 2019 Preview
Version 16.0.0 Preview 1.0

**Steps to Reproduce**:

1. Create a new .NET Core console project
2. Possibly unrelated, but set language version to 8.0 and enable NRT with `<NullableReferenceTypes>true</NullableReferenceTypes>` in the csproj.
3. Build the following code:

```csharp
using System;

namespace ConsoleApp1
{
    class Program
    {
        static int Main(string[] args)
        {
            if (args.Length == 0)
            {
                Console.WriteLine("Usage: ConsoleApp1 <text>");
                return -1;
            }

            foreach (var arg in args)
            {
                Console.WriteLine(arg);
            }
            return 0;
        }
    }
}
```

**Expected Behavior**:

No diagnostics

**Actual Behavior**:

IDE0051 Private member 'Program.Main' is unused.

### LINKED ISSUE #31581: IDE0051 should not be reported when methods are referenced in nameof() expressions
**Version Used**: VS 16.0 Preview 1

**Steps to Reproduce**:

1. Copy the code into a C# file.

```c#
public string P => nameof(M);
private void M() { }
```

**Expected Behavior**: IDE0051 is not reported for `M`.

**Actual Behavior**: IDE0051 is reported for `M`. The code fix breaks any code that references `M`.

### PR DESCRIPTION
**Pull request by mavasani**
1. https://github.com/dotnet/roslyn/commit/1196711c981829ba53e4ef307cf79f25b3b0bff2: Fixes #31572. Fix detection of entry point methods to account for `int` return type.

2. https://github.com/dotnet/roslyn/commit/9cc8b0c5388bff6453c0807b2fbe96f7ef6f0dc8: Fixes #31581. Add a workaround for #19965 to detect references to method/property from method group/property group argument to `nameof` operator. We also provide a different diagnostic message for private methods that have name-only references.

### CODE REVIEW

**Comment by mavasani** [comment]
Ping @dotnet/roslyn-ide trivial fixes.

**Comment by mavasani** [comment]
Ping for reviews...

File: src/Features/Core/Portable/Diagnostics/DiagnosticHelper.cs [hunk 1]
```diff
@@ -86,7 +86,6 @@ internal static class DiagnosticHelper
                 throw new ArgumentNullException(nameof(descriptor));
             }
 
-            var warningLevel = effectiveSeverity.ToDiagnosticSeverity() ?? descriptor.DefaultSeverity;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Diagnostics/DiagnosticHelper.cs]: what's the reason for this change?

File: src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs [hunk 2]
```diff
@@ -294,6 +295,32 @@ private void AnalyzeInvocationOperation(OperationAnalysisContext operationContex
...
+                }
+
+                var symbolInfo = nameofArgument.SemanticModel.GetSymbolInfo(nameofArgument.Syntax, operationContext.CancellationToken);
+                foreach (var symbol in symbolInfo.GetAllSymbols())
+                {
+                    switch (symbol.Kind)
+                    {
+                        case SymbolKind.Method:
+                        case SymbolKind.Property:
+                            OnSymbolUsage(symbol, ValueUsageInfo.NameOnly);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: why only these types of symbols?

File: src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs [hunk 3]
```diff
@@ -375,14 +402,26 @@ private void OnSymbolEnd(SymbolAnalysisContext symbolEndContext, bool hasInvalid
                                 continue;
                             }
 
+                            var messageFormat = rule.MessageFormat;
+                            if (rule == s_removeUnreadMembersRule &&
+                                member is IMethodSymbol)
+                            {
+                                // IDE0052 has a different message for method symbols.
+                                messageFormat = FeaturesResources.Private_method_0_can_be_removed_as_it_is_never_invoked;
+                            }
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: this feels a bit weird.  the rule has a format... but then we'd just overriding it.  It makes it seem as if the message isn't inherent to the rule.

Either, pull all the message choosing up to here, or make it so that we query the rule for the appropriate message, apssing in whatever data is needs to make that decision (i.e. the member in this case).

File: src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs [hunk 4]
```diff
@@ -601,6 +640,7 @@ private bool IsEntryPoint(IMethodSymbol methodSymbol)
                 => methodSymbol.Name == WellKnownMemberNames.EntryPointMethodName &&
                    methodSymbol.IsStatic &&
                    (methodSymbol.ReturnsVoid ||
+                    methodSymbol.ReturnType.SpecialType == SpecialType.System_Int32 ||
                     methodSymbol.ReturnType.OriginalDefinition == _taskType ||
                     methodSymbol.ReturnType.OriginalDefinition == _genericTaskType);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: note: `==` with types isn't a great idea. (this is about the _taskType/_genericTaskType checks).

File: src/Features/Core/Portable/Diagnostics/DiagnosticHelper.cs (hunk 1 above)
Comment (mavasani) [reply src/Features/Core/Portable/Diagnostics/DiagnosticHelper.cs]: It is dead code.

File: src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs (hunk 2 above)
Comment (mavasani) [reply src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: Workaround is for missing IOperation for method groups and property groups.

File: src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs (hunk 3 above)
Comment (mavasani) [reply src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: Sure, will refactor

File: src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs (hunk 4 above)
Comment (mavasani) [reply src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: Yep, will fix.

**Comment by mavasani** [comment]
@CyrusNajmabadi addressed feedback.

@dotnet/roslyn-ide for reviews.

File: src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs [hunk 5]
```diff
@@ -435,6 +424,22 @@ private void OnSymbolEnd(SymbolAnalysisContext symbolEndContext, bool hasInvalid
...
+               DiagnosticDescriptor rule,
+               ISymbol member)
+            {
+                var messageFormat = rule.MessageFormat;
+                if (rule == s_removeUnreadMembersRule &&
+                    member is IMethodSymbol)
+                {
+                    // IDE0052 has a different message for method symbols.
+                    messageFormat = FeaturesResources.Private_method_0_can_be_removed_as_it_is_never_invoked;
+                }
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: note.  my complaint here still stands (albeit it is minor).  It definitely is a smell to have a rule specify a format string, but then have the caller just override that in particular cases.

File: src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs (hunk 2 above)
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: gotcha.  in that case, i would say that we should hav ea comment here.  For example, my natural inclination is to wonder "why not fields?  why not events?" etc.

File: src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs (hunk 5 above)
Comment (mavasani) [reply src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: Yep, but our diagnostic system provides no better solution here, other then reporting a diagnostic with separate ID here, which IMO is an overkill for this case.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: Your call :)

File: src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs (hunk 2 above)
Comment (mavasani) [reply src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: Done

**Comment by mavasani** [comment]
@jinujoseph for approval

**Comment by mavasani** [comment]
Thanks @jinujoseph
