### PR TITLE
Reduce allocations in UnboundLambda

### LINKED ISSUE #23463: Investigate allocation reduction in UnboundLambdaState constructor
**Version Used**: 2b39919ba6eebb6b22524db11a537fe247ee8a79

**Steps to Reproduce**:

Run CSharpFeatures analyzers with AnalyzerRunner on Orchard.sln.

**Result**:

660MB (3.4% overall) allocations occur in the constructor of `UnboundLambdaState` for the creation of two `ConcurrentDictionary<TKey, TValue>` instances. Two approaches for optimizing this scenario come to mind:

1. If the majority scenario during compilation involves these two dictionaries having 0-1 element, consider special-casing the state object to support storing the first result without allocating the dictionaries.
2. If the previous case is not possible, consider using an object pool for this path.

### PR DESCRIPTION
**Pull request by sharwell**
### Customer scenario

Running analyzer during a build is slower than it should be, with the analyzer driver contributing substantial overhead even when the analyzers themselves are lightweight.

### Bugs this fixes

Fixes #23463

### Workarounds, if any

None needed

### Risk

The dictionary algorithm is now optimistically concurrent, with a small risk of a performance regression in highly-contended scenarios. In addition, the dictionary lookup went from O(1) to O(log n). This should not be a problem as it favors the frequently used small dictionaries without making large edge cases unreasonable.

### Performance impact

AnalyzerRunner indicates a reduction in allocations of 2.56GiB (2.9%).

### Is this a regression from a previous update?

No.

### Root cause analysis

AnalyzerRunner is a new tool for helping us test analyzer performance in isolation.

### How was the bug found?

AnalyzerRunner.

### Test documentation updated?

No.

### CODE REVIEW

**Comment by sharwell** [comment]
@dotnet/roslyn-compiler for review

**Comment by sharwell** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs [hunk 1]
```diff
@@ -439,6 +440,11 @@ private BoundLambda ReallyBind(NamedTypeSymbol delegateType)
                 }
             }
 
+            // when binding for real (not for return inference), there is still
+            // a good chance that we could reuse a body of a lambda previously bound for 
+            // return type inference.
+            var cacheKey = ReturnInferenceCacheKey.Create(delegateType, IsAsync);
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: >cacheKey [](start = 16, length = 8)

This cache key is not used as a cache key. In fact, it really isn't used, except to get things that are available on the delegate type.

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs [hunk 2]
```diff
@@ -554,16 +560,14 @@ private BoundLambda ReallyInferReturnType(NamedTypeSymbol delegateType, Immutabl
...
-            if (!_returnInferenceCache.TryGetValue(cacheKey, out result))
+            if (_returnInferenceCache.TryGetValue(delegateType, out var result))
             {
-                result = ReallyInferReturnType(delegateType, cacheKey.ParameterTypes, cacheKey.ParameterRefKinds);
-                _returnInferenceCache.TryAdd(cacheKey, result);
+                return result;
             }
 
-            return result;
+            var cacheKey = ReturnInferenceCacheKey.Create(delegateType, IsAsync);
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: >cacheKey [](start = 16, length = 8)

Ditto

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs [hunk 3]
```diff
@@ -342,14 +349,13 @@ public virtual void GenerateAnonymousFunctionConversionError(DiagnosticBag diagn
         // Returns the inferred return type, or null if none can be inferred.
         public BoundLambda Bind(NamedTypeSymbol delegateType)
         {
-            BoundLambda result;
-            if (!_bindingCache.TryGetValue(delegateType, out result))
+            if (_bindingCache.TryGetValue(delegateType, out var result))
             {
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: Concurrency on these caches will be quite rare, and encountered solely based on concurrent calls into the compiler APIs. I think we are likely to be better served using a simple Dictionary with an explicit lock around its uses.

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs [hunk 4]
```diff
@@ -298,9 +298,16 @@ internal abstract class UnboundLambdaState
     {
         private UnboundLambda _unboundLambda; // we would prefer this readonly, but we have an initialization cycle.
         protected readonly Binder binder;
-        private readonly ConcurrentDictionary<NamedTypeSymbol, BoundLambda> _bindingCache = new ConcurrentDictionary<NamedTypeSymbol, BoundLambda>();
 
-        private readonly ConcurrentDictionary<ReturnInferenceCacheKey, BoundLambda> _returnInferenceCache = new ConcurrentDictionary<ReturnInferenceCacheKey, BoundLambda>();
+        [PerformanceSensitive(
+            "https://github.com/dotnet/roslyn/issues/23582",
+            Constraint = "Avoid " + nameof(ConcurrentDictionary<NamedTypeSymbol, BoundLambda>) + " which has a large default size, but this cache is normally small.")]
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: >which has a large default size, but this cache is normally small. [](start = 99, length = 65)

Could we provide explicit initial capacity instead, the reasonable small value?

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs [hunk 5]
```diff
@@ -342,14 +349,13 @@ public virtual void GenerateAnonymousFunctionConversionError(DiagnosticBag diagn
         // Returns the inferred return type, or null if none can be inferred.
         public BoundLambda Bind(NamedTypeSymbol delegateType)
         {
-            BoundLambda result;
-            if (!_bindingCache.TryGetValue(delegateType, out result))
+            if (_bindingCache.TryGetValue(delegateType, out var result))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: >var [](start = 60, length = 3)

Please spell out the type, or better revert the inlining of the declaration.

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs [hunk 6]
```diff
@@ -298,9 +298,16 @@ internal abstract class UnboundLambdaState
...
-        private readonly ConcurrentDictionary<ReturnInferenceCacheKey, BoundLambda> _returnInferenceCache = new ConcurrentDictionary<ReturnInferenceCacheKey, BoundLambda>();
+        [PerformanceSensitive(
+            "https://github.com/dotnet/roslyn/issues/23582",
+            Constraint = "Avoid " + nameof(ConcurrentDictionary<NamedTypeSymbol, BoundLambda>) + " which has a large default size, but this cache is normally small.")]
+        private ImmutableDictionary<NamedTypeSymbol, BoundLambda> _bindingCache = ImmutableDictionary<NamedTypeSymbol, BoundLambda>.Empty;
+
+        [PerformanceSensitive(
+            "https://github.com/dotnet/roslyn/issues/23582",
+            Constraint = "Avoid " + nameof(ConcurrentDictionary<NamedTypeSymbol, BoundLambda>) + " which has a large default size, but this cache is normally small.")]
+        private ImmutableDictionary<NamedTypeSymbol, BoundLambda> _returnInferenceCache = ImmutableDictionary<NamedTypeSymbol, BoundLambda>.Empty;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: >NamedTypeSymbol [](start = 110, length = 15)

The change in the key type looks wrong.

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs [hunk 7]
```diff
@@ -554,16 +560,14 @@ private BoundLambda ReallyInferReturnType(NamedTypeSymbol delegateType, Immutabl
 
         public BoundLambda BindForReturnTypeInference(NamedTypeSymbol delegateType)
         {
-            var cacheKey = ReturnInferenceCacheKey.Create(delegateType, IsAsync);
-
-            BoundLambda result;
-            if (!_returnInferenceCache.TryGetValue(cacheKey, out result))
+            if (_returnInferenceCache.TryGetValue(delegateType, out var result))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: >var [](start = 68, length = 3)

Please spell out the type, or better revert the inlining of the declaration. In general, ```var``` is not welcome in compilers code base.

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs (hunk 6 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: I wouldn't call it so much wrong as replacing one apparently unimportant optimization (sharing the cache for semantically identical delegate types) for another apparently important optimization. I believe the transformation preserves correctness of the compiler. Do you, @AlekseyTs, believe that change is semantically incorrect?

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: My point is, please avoid creating the cache key, and instead directly compute the parameter type array and parameter ref kind array.

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs (hunk 5 above)
Comment (sharwell) [reply src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: :memo: According to the .editorconfig for this section of the code, both forms are acceptable. We need to update the configuration to match the practices followed during the code review process.

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs (hunk 6 above)
Comment (sharwell) [reply src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: This one is going to be important to understand. According to the previous implementation of `BindForReturnTypeInference`, returning a new result from `ReallyInferReturnType` for the same delegate type is acceptable in the case of a cache miss (note the use of `TryAdd` instead of `GetOrAdd`). I verified that the conversion from `NamedTypeSymbol` to `ReturnInferenceCacheKey` is a deterministic function, but incorrectly treated it as one-to-one.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: Neither description of the change, nor comments mentioned the type change for the key. The motivation behind the change was not explained, no numbers supporting the change were provided. I am talking exclusively about the type change for the key. If you have numbers supporting that the type change **on its own** leads to noticeable improvement, and you are confident that the change is not going to regress other scenarios, then we should get rid of the ReturnInferenceCacheKey type altogether.

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs (hunk 1 above)
Comment (sharwell) [reply src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: ➡️ Reverted the key change; can evaluate separately.

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs (hunk 5 above)
Comment (sharwell) [reply src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: ➡️ Reverted style changes to the extent possible.

**Comment by sharwell** [comment]
@dotnet/roslyn-compiler This is ready for updated review. Changes are restricted to the type of dictionary used. I will update the original post with allocation savings under the new approach when available.

@gafter @AlekseyTs You both mentioned using different dictionary types. Do you have examples of where these dictionaries get large? My belief is these are typically single-element dictionaries, in which case the current tree-based dictionary would be as efficient as anything else. It seems like you would need a *very* large number of *very* large sets to give anything else an advantage. Unfortunately my test suite is limited with respect to this change.

**Comment by sharwell** [comment]
@dotnet-bot retest windows_release_unit32_prtest please

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs (hunk 5 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: > We need to update the configuration to match the practices followed during the code review process.

Note that the exact rules in compilers - ```var``` is not allowed unless the type is explicitly named in the initializer.

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs [hunk 8]
```diff
@@ -704,28 +711,29 @@ private BoundLambda ReallyBindForErrorRecovery()
...
             {
                 case 0:
                     return null;
                 case 1:
-                    return candidates.First();
+                    return candidates.First().Value;
                 default:
                     // Prefer candidates with fewer diagnostics.
-                    IEnumerable<BoundLambda> minDiagnosticsGroup = candidates.GroupBy(lambda => lambda.Diagnostics.Length).OrderBy(group => group.Key).First();
+                    IEnumerable<KeyValuePair<T, BoundLambda>> minDiagnosticsGroup = candidates.GroupBy(lambda => lambda.Value.Diagnostics.Length).OrderBy(group => group.Key).First();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: >lambda [](start = 103, length = 6)

Consider renaming parameter to ```pair``` or something similar.

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs [hunk 9]
```diff
@@ -704,28 +711,29 @@ private BoundLambda ReallyBindForErrorRecovery()
...
 
                     // If multiple candidates have the same number of diagnostics, order them by delegate type name.
                     // It's not great, but it should be stable.
                     return minDiagnosticsGroup
-                        .OrderBy(lambda => GetLambdaSortString(lambda.Symbol))
-                        .FirstOrDefault();
+                        .OrderBy(lambda => GetLambdaSortString(lambda.Value.Symbol))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: >lambda [](start = 33, length = 6)

Same suggestion here.

File: src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs [hunk 10]
```diff
@@ -704,28 +711,29 @@ private BoundLambda ReallyBindForErrorRecovery()
...
+                        .FirstOrDefault()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/UnboundLambda.cs]: >FirstOrDefault [](start = 25, length = 14)

This probably should be ```First()```, it look like we don't expect the sequence to be empty.

**Comment by sharwell** [comment]
:memo: The allocation savings do not appear to have changed significantly from the original report.

**Comment by AlekseyTs** [comment]
> The allocation savings do not appear to have changed significantly from the original report.

@sharwell Thanks for following up on this. I am curious what exactly are we measuring.  "Running analyzer during a build is slower than it should be" isn't quite clear in this respect. Does analyzer do something specific? Could you please provide more details? These questions are not blocking this PR.

**Comment by sharwell** [comment]
> I am curious what exactly are we measuring. "Running analyzer during a build is slower than it should be" isn't quite clear in this respect. Does analyzer do something specific? Could you please provide more details? These questions are not blocking this PR.

This pull request is the result of an open-ended performance investigation. A test scenario was constructed, and code changes were applied according to the prominent sources of allocations revealed by the test. Each change was described in terms of gains made against the baseline results for the constructed scenario.

**Comment by AlekseyTs** [comment]
Could you please share some details about the test scenario?

**Comment by sharwell** [comment]
@AlekseyTs I think I edited my comment while you were reading it. I added a link to the test scenario I used for this.

**Comment by sharwell** [comment]
@AlekseyTs If you know of a sample program which forces these maps to get large, let me know. I can run profiling passes on them to verify the change to a tree-based map will not cause regressions on code that differs from the input I used so far.

**Comment by AlekseyTs** [comment]
@sharwell Are we certain that analyzers executed as part of the scenario themselves doing things in an efficient manner, i.e. not causing compiler to redo work unnecessary, etc. For example, code in https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/UseThrowExpression/AbstractUseThrowExpressionDiagnosticAnalyzer.cs requests  separate SemanticModel and causes compiler to rebind the same code again and build another IOperation tree for the same code.

**Comment by sharwell** [comment]
@AlekseyTs to the contrary, by all metrics I have encountered analyzers are frequently extremely inefficient and not in obvious ways. However, with analyzers running as an integral part of the build it's increasingly hard to separate the two.

**Comment by sharwell** [comment]
@dotnet-bot retest this please

**Comment by sharwell** [comment]
@Pilchie or @MeiChin-Tsai for ask mode

**Comment by Pilchie** [comment]
I'm in favor of the change for the scenario, but I'll leave it to @MeiChin-Tsai to approve in case she has any concerns about risk.

**Comment by gafter** [comment]
Can you please rebase this to 15.7.x (which is not in ask mode)?

**Comment by MeiChin-Tsai** [comment]
I agree with @gafter

**Comment by sharwell** [comment]
@MeiChin-Tsai This is now retargeted to 15.7

**Comment by jinujoseph** [comment]
To the best i know compiler side is not in ask mode for 15.7 yet so you should be good to merge this. @jaredpar correct me if thatz not the case

**Comment by jaredpar** [comment]
@jinujoseph that is correct.

**Comment by gafter** [comment]
image
