### PR TITLE
Fixed recognition predefined types by their metadata names

### LINKED ISSUE #20244: Type style fails to recognize predefined types by their metadata names
**Version Used**: 15.2

:link: Originally reported by Josh Hufford: [Suggesting both 'var' and explicit type.](https://developercommunity.visualstudio.com/content/problem/68755/suggesting-both-var-and-explicit-type.html)

**Steps to Reproduce**:

1. Set the style for **For built-in types** to **Prefer explicit type**
1. Set the style for **When variable type is apparent** to **Prefer 'var'**
1. Use the following code

    ```csharp
    String test = new String(' ', 4);
    ```

**Expected Behavior**:

No warning is reported, because `String` is the built-in type `string`.

**Actual Behavior**:

Warning IDE0007 is reported.

### PR DESCRIPTION
**Pull request by zaytsev-victor**
**Customer scenario**
Type style fails to recognize predefined types by their metadata names

**Bugs this fixes:**
Fixes #20244

**Risk**
Low

**Performance impact**

**Is this a regression from a previous update?**
No

**Root cause analysis:**
Used incorrect check for predefined types. Tests verify incorrect behavior.
Fixed tests. Added tests.

**How was the bug found?**
customer reported

### CODE REVIEW

**Comment by sharwell** [comment]
First of all, thanks for doing my work for me, this is awesome. 😄 

With that said, if you know how to use git to amend a commit, consider changing the message of the current commit (it refers to the wrong issue).

File: src/EditorFeatures/CSharpTest/Diagnostics/UseImplicitOrExplicitType/UseImplicitTypeTests.cs [hunk 1]
```diff
@@ -1082,7 +1082,7 @@ static void M()
         [WpfFact, Trait(Traits.Feature, Traits.Features.CodeActionsUseImplicitType)]
         public async Task SuggestVarOnFrameworkTypeEquivalentToBuiltInType()
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/Diagnostics/UseImplicitOrExplicitType/UseImplicitTypeTests.cs]: :bulb: Based on the previous method, this test should actually be named `DoNotSuggestVarOnFrameworkTypeEquivalentToBuiltInType_WithOption`.

File: src/EditorFeatures/CSharpTest/Diagnostics/UseImplicitOrExplicitType/UseImplicitTypeTests.cs [hunk 2]
```diff
@@ -1244,35 +1233,33 @@ public void Process()
...
-{
-}
+}", new TestParameters(options: ImplicitTypeWhereApparent()));
+        }
 
-interface IInterface
-{
-}",
+        [WpfFact, Trait(Traits.Feature, Traits.Features.CodeActionsUseImplicitType)]
+        public async Task SuggestVarWhereTypeIsEvident_IsExpression()
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/Diagnostics/UseImplicitOrExplicitType/UseImplicitTypeTests.cs]: ❗️ This test is no longer doing what it was before. The body of process could be this to preserve intent:

```
A a = new A();
IInterface s = a as IInterface;
```

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.State.cs [hunk 3]
```diff
@@ -89,10 +89,12 @@ private bool IsTypeApparentInDeclaration(VariableDeclarationSyntax variableDecla
             /// to var. <see cref="SyntaxFacts.IsPredefinedType(SyntaxKind)"/> considers string
             /// and object but the compiler's implementation of IsIntrinsicType does not.
             /// </remarks>
-            private bool IsPredefinedTypeInDeclaration(SyntaxNode declarationStatement)
+            private bool IsPredefinedTypeInDeclaration(SyntaxNode declarationStatement, SemanticModel semanticModel, CancellationToken cancellationToken)
```
Comment (sharwell) [inline src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.State.cs]: ❓ Did you mean to use `cancellationToken`?

File: src/EditorFeatures/CSharpTest/Diagnostics/UseImplicitOrExplicitType/UseImplicitTypeTests.cs [hunk 4]
```diff
@@ -1454,7 +1441,7 @@ public void Process()
     {
         int codePoint = 1067;
         IConvertible iConv = codePoint;
-        var ch = iConv.ToChar(null);
+        var date = iConv.ToDateTime(null);
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Diagnostics/UseImplicitOrExplicitType/UseImplicitTypeTests.cs]: why did these tests change?

**Comment by CyrusNajmabadi** [comment]
I'm a little confused by this.   I thought this was part of our original design.  i.e. "int" is a "built in type" whereas "Int32" is not, it's just a regular named type.  It was intentional to not treat them the same.  Checking with @dpoeschl since my memory is hazy here.

File: src/EditorFeatures/CSharpTest/Diagnostics/UseImplicitOrExplicitType/UseImplicitTypeTests.cs (hunk 4 above)
Comment (zaytsev-victor) [inline src/EditorFeatures/CSharpTest/Diagnostics/UseImplicitOrExplicitType/UseImplicitTypeTests.cs]: because char is predefined type and DateTime is not.

File: src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.State.cs (hunk 3 above)
Comment (zaytsev-victor) [inline src/Features/CSharp/Portable/Diagnostics/Analyzers/CSharpTypeStyleDiagnosticAnalyzerBase.State.cs]: removed.

File: src/EditorFeatures/CSharpTest/Diagnostics/UseImplicitOrExplicitType/UseImplicitTypeTests.cs (hunk 2 above)
Comment (zaytsev-victor) [inline src/EditorFeatures/CSharpTest/Diagnostics/UseImplicitOrExplicitType/UseImplicitTypeTests.cs]: I've renamed the tests. It checks ```IsExpression```, so I think it should be just renamed.

**Comment by sharwell** [comment]
This will be ready to merge once the conflict is fixed. @zaytsev-victor let me know if you want me to fix the conflict for you. :smile:

**Comment by sharwell** [comment]
@CyrusNajmabadi The underlying problem here is a conflict in the current handling of the settings. Application of a code fix in the target scenario results in the introduction of a different warning. It becomes impossible to use these types without one warning or another in the resulting code.

**Comment by sharwell** [comment]
@zaytsev-victor I fixed the merge conflict and am now waiting for the build to complete 😄

**Comment by zaytsev-victor** [comment]
@sharwell thanks :)
