### PR TITLE
Fix quick info for anonymous types not escaping identifiers named as keywords

### LINKED ISSUE #71638: Verbatim identifier prefix is displayed inconsistently in tooltips for anonymous types
**Version Used**: VS 17.8.4

**Steps to Reproduce**:

Hover over the identifier `@string`.

```csharp
_ = new
{
    @string = ""
}.@string;
```

**Expected Behavior**: The verbatim prefix is used consistently, i.e. always shown whenever it's required to escape a keyword, and never shown when it's not.

**Actual Behavior**: The verbatim prefix is missing in the anonymous type description, but present in the description of the member itself.
image

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #71638

### CODE REVIEW

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs [hunk 1]
```diff
@@ -8831,5 +8831,26 @@ public async Task TestCollectionExpression_Start_Typeless()
...
+        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/71638")]
+        public async Task TestAnonymousType()
+        {
+            var markup = """
+                _ = new
+                {
+                    @string = ""
+                }.$$@string;
+                """;
+            var description = $"string 'a.@string {{ get; }}";
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs:8844]: 💡 It would be good to include a property that doesn't need the `@` as well. Not sure if there is already a test in this file for such a case.

**Review by sharwell — APPROVED** [review]

File: src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs (hunk 1 above)
Comment (Youssef1313) [reply src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs:8844]: @sharwell I think [this one](https://github.com/dotnet/roslyn/blob/7959fedb88c5dab6f2c186be4a4f3fa8e6211359/src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs#L4352) should be good to cover this case?

Comment (sharwell) [reply src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs:8844]: Yep thanks!

**Comment by Youssef1313** [comment]
@sharwell @CyrusNajmabadi The CI failure here is looking unrelated to my change. Could you restart the failing jobs please? Thanks!
