### PR TITLE
Do not permit default literals in relational patterns

### LINKED ISSUE #45292: Should not permit default literals in relational patterns
**Version Used**: master

**Steps to Reproduce**:

```cs
    public void M(byte i) {
        _ = i is > default; // compiles
        _ = i is default; // error
    } 
```

**Expected Behavior**:

`A default literal 'default' is not valid as a pattern. Use another literal (e.g. '0' or 'null') as appropriate. To match everything, use a discard pattern '_'`

**Actual Behavior**: No error

### PR DESCRIPTION
**Pull request by gafter**
Fixes #45292

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 1]
```diff
@@ -1239,6 +1239,12 @@ void addSubpatternsForTuple(ImmutableArray<TypeWithAnnotations> elementTypes)
             DiagnosticBag diagnostics)
         {
             BoundExpression value = BindExpressionForPattern(inputType, node.Expression, ref hasErrors, diagnostics, out var constantValueOpt, out _);
+            ExpressionSyntax innerExpression = node.Expression.SkipParens();
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs:1242]: We need to deal with nullable suppressions too, I think

**Comment by gafter** [comment]
@jcouv I think I've addressed your comment. Do you have any others?
