### PR TITLE
Move test RSP to artifacts directory

### LINKED ISSUE #63779: RunTests should not write response files to repo root
**Version Used**: 6cc2376ad55aa7399b1aa5451e9b2c1af956a3fb

**Steps to Reproduce**:

Run `.\Build.cmd -restore -test` in the repo root

**Expected Behavior**: File changes don't appear in `git status`

**Actual Behavior**: Many files named vstest_0.rsp, vstest_1.rsp, etc. appear in `git status`
image

It feels like these files should go somewhere under `artifacts/`.

### PR DESCRIPTION
**Pull request by jaredpar**
This moves our generated vstest RSP files into the tmp folder under artifacts. Previously they were being dropped into the root which was causing them to show up in `git status` calls.

closes #63779

### CODE REVIEW

**Comment by jaredpar** [comment]
@dotnet/roslyn-infrastructure PTAL

**Review by RikkiGibson — APPROVED** [review]

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 1)

**Review by genlu — APPROVED** [review]

File: src/Tools/Source/RunTests/ProcessTestExecutor.cs [hunk 1]
```diff
@@ -241,6 +241,19 @@ private async Task<TestResult> RunTestAsyncInternal(WorkItemInfo workItemInfo, O
                     testResultInfo,
                     commandLineArguments,
                     processResults: ImmutableArray.CreateRange(processResultList));
+
+                string getRspDirectory()
+                {
+                    // There is no artifacts directory on Helix, just use the current directory
+                    if (options.UseHelix)
```
Comment (dibarbet) [inline src/Tools/Source/RunTests/ProcessTestExecutor.cs:248]: RunTestAsyncInternal should never get called with options.UseHelix, so not necessary.

**Review by dibarbet — APPROVED** [review]
