### PR TITLE
Bug fixes and testing for completion in XML documentation comments

### LINKED ISSUE #11489: Add a <see langword option in the completion window
I often type `<see langword="true"/>`, `<see langword="false"/>`, `<see langword="abstract"/>`, etc like below. It would be great to be offered to add an add `<see langword=""/>` like there is with `<see cref=""/>`. 

``` C#
        /// <summary>
        ///     Returns a value indicating whether the current project has the specified capability
        /// </summary>
        /// <exception cref="ArgumentNullException">
        ///     <paramref name="capability"/> is <see langword="null"/>.
        /// </exception>
        bool Contains(string capability);
```

image

### LINKED ISSUE #11490: Auto suggest language keywords inside <see langword="" />
It would be great to be able to auto-suggest language keywords such as `null`, `abstract`, `true`, `false`, etc inside <see langword=""/>. Currently get offered no keywords. :(

### LINKED ISSUE #17872: <typeparamref isn't in the completion list for members of generic types
I get it for the type itself:

image

But not members of the type:

image

### PR DESCRIPTION
**Pull request by sharwell**
Supersedes #17970.

Builds on the *outstanding* original work by @lorcanmooney.

* Implements support for `<see langword="null"/>` (Fixes #11490, Fixes #11489)
* Add tests for expected behavior of `<returns>` and `<value>` (Improves upon the work in #21475)
* Implements proper support for `<typeparamref name="T"/>`, where `T` is defined by an enclosing code element (Fixes #17872)

Notable changes from the original:

* The set of keywords presented in code completion is restricted to a subset of keywords. This keeps the list from being overwhelming.
* The tests for `<returns>` and `<value>` were modified according to the new direction taken by the original bug.
* The handling of <kbd>Space</kbd> after typing `<see` was restored to the original behavior to avoid muscle memory problems for long-time users.

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs [hunk 1]
```diff
@@ -1196,5 +1196,44 @@ static void Goo()
...
+{
+    /// <exception $$
+    void Goo() { }
+}
+";
+            await VerifyItemExistsAsync(text, "cref");
+        }
+
+        [Fact, Trait(Traits.Feature, Traits.Features.Completion)]
+        public async Task PartiallyTypedAttributeName()
```
Comment (rchande) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs]: Technically, this test is redundant with the one above it because VerifyItemExistsAsync will test with the expected item partially typed (unless we override that behavior in xml doc tests?)
