### PR TITLE
Do not skip emit if errors are suppressed

### LINKED ISSUE #34101: Suppressed warning + errorlog + warnaserror -> Silent failed compilation with zero exit code
**Version Used**: 3.0.19.15604 (7d31dd6e)

**Steps to Reproduce**:

1. Create test.cs
``` C#
#pragma warning disable 1591

public class P {
    public static void Main() {}
}
```
2. `csc.exe test.cs -doc:doc.xml -errorlog:errors.json -warnaserror`

**Expected Behavior**:

Compilation succeeds, test.exe is generated.

**Actual Behavior**:

Csc.exe returns 0, but test.exe is not generated

### PR DESCRIPTION
**Pull request by agocke**
In the command line compilation we try to discover when to stop the
compilation stages based on if an error is produced. If the error was
produced by /warnaserror, then suppressed, this should not be considered
a compilation-halting error.

Fixes #34101

### CODE REVIEW

File: src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs [hunk 1]
```diff
@@ -43,6 +43,23 @@ private static void RunInThread(Action action)
             }
         }
 
+        [Fact]
+        public void EmitWithSuppressedWarnAsError()
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit/Emit/EndToEndTests.cs]: >EmitWithSuppressedWarnAsError [](start = 20, length = 29)

so far, we only have two tests in this file, which are related to depth of code. Consider looking for another test file to host this test.

File: src/Compilers/Core/Portable/Compilation/Compilation.cs [hunk 2]
```diff
@@ -1370,13 +1371,15 @@ internal bool FilterAndAppendDiagnostics(DiagnosticBag accumulator, IEnumerable<
                     continue;
                 }
 
+
                 var filtered = Options.FilterDiagnostic(d);
```
Comment (jcouv) [inline src/Compilers/Core/Portable/Compilation/Compilation.cs]: >var [](start = 16, length = 3)

nit: double empty line above (revert)

File: src/Compilers/Core/Portable/Compilation/Compilation.cs [hunk 3]
```diff
@@ -1370,13 +1371,15 @@ internal bool FilterAndAppendDiagnostics(DiagnosticBag accumulator, IEnumerable<
...
                 if (filtered == null ||
                     (!reportSuppressedDiagnostics && filtered.IsSuppressed))
                 {
                     continue;
                 }
-                else if (filtered.Severity == DiagnosticSeverity.Error)
+                else if (filtered.Severity == DiagnosticSeverity.Error &&
+                         !filtered.IsSuppressed)
```
Comment (jcouv) [inline src/Compilers/Core/Portable/Compilation/Compilation.cs]: >!filtered.IsSuppressed) [](start = 25, length = 23)

can errors be suppressed? I thought only warnings could.

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs [hunk 4]
```diff
@@ -434,6 +434,18 @@ internal bool ReportErrors(IEnumerable<Diagnostic> diagnostics, TextWriter conso
         private bool ReportErrors(DiagnosticBag diagnostics, TextWriter consoleOutput, ErrorLogger errorLoggerOpt)
             => ReportErrors(diagnostics.ToReadOnly(), consoleOutput, errorLoggerOpt);
 
+        internal static bool HasUnsuppressedErrors(DiagnosticBag diagnostics)
```
Comment (jaredpar) [inline src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: The name threw me off here a bit. Felt like has not fake error. Consider a more positive term like HasReal/ReportedError.

File: src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs [hunk 5]
```diff
@@ -95,6 +95,32 @@ private CSharpCommandLineArguments FullParse(string commandLine, string baseDire
             return CSharpCommandLineParser.Default.Parse(args, baseDirectory, sdkDirectory, additionalReferenceDirectories);
         }
 
+        [ConditionalFact(typeof(WindowsDesktopOnly), Reason = ConditionalSkipReason.TestHasWindowsPaths)]
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs]: Where is the windows path here?

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs [hunk 6]
```diff
@@ -434,6 +434,18 @@ internal bool ReportErrors(IEnumerable<Diagnostic> diagnostics, TextWriter conso
...
+        {
+            foreach (var diag in diagnostics.AsEnumerableWithoutResolution())
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: >AsEnumerableWithoutResolution [](start = 45, length = 29)

Why without resolution? What if we there is a lazy diagnostics that becomes an error after resolution?

File: src/Compilers/Core/Portable/Compilation/Compilation.cs (hunk 3 above)
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Compilation/Compilation.cs]: >!filtered.IsSuppressed [](start = 25, length = 22)

It looks like previous ```if``` takes care of checking this. Shouldn't we respect the ```reportSuppressedDiagnostics``` option?

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs (hunk 6 above)
Comment (jcouv) [reply src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: My understanding is that the next line causes resolution (checks severity) anyways.

Comment (AlekseyTs) [reply src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: > My understanding is that the next line causes resolution (checks severity) anyways.

Then why pretend that we do not resolve?

---
In reply to: [266165592](https://github.com/dotnet/roslyn/pull/34174#discussion_r266165592) [](ancestors = 266165592)

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs (hunk 4 above)
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: >HasUnsuppressedErrors [](start = 29, length = 21)

It looks like this method is supposed to be called after the filtering is applied to content of the bag. It doesn't look like this happens for every call site.

File: src/Compilers/Core/Portable/Compilation/Compilation.cs [hunk 7]
```diff
@@ -2578,7 +2581,7 @@ internal void EnsureAnonymousTypeTemplates(CancellationToken cancellationToken)
                 }
             }
 
-            if (diagnostics.HasAnyErrors())
+            if (CommonCompiler.HasUnsuppressedErrors(diagnostics))
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Compilation/Compilation.cs]: >CommonCompiler.HasUnsuppressedErrors(diagnostics) [](start = 16, length = 49)

Have we done filtering to get suppression state?

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1)

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs (hunk 6 above)
Comment (jcouv) [reply src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: I'll let Andy respond, but my assumption in reading the PR was to avoid extra processing which `AsEnumerable` does. 
But I agree it's not obvious ;-)

**Comment by nguerrera** [comment]
Something to consider here: the diagnostic actually gets persisted to error log as an "error" that is "suppressed in source". I guess this matches the compiler implementation, but my mental model (and I'll bet I'm not alone) is that a warning was raised and suppressed *before* it could be elevated to an error. I would not expect "suppressed error" to be an observable state in the API or in the error log.

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs (hunk 6 above)
Comment (agocke) [reply src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: Yes, it was for perf and the places I was looking at it I thought it was safe because we always realized diagnostics later, but it's not particularly worth the risk. I've changed it to resolve.

File: src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs (hunk 5 above)
Comment (agocke) [reply src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs]: There technically isn't one, but I'm running an exe, which only works on Windows desktop and needed a reason.

File: src/Compilers/Core/Portable/Compilation/Compilation.cs (hunk 3 above)
Comment (agocke) [reply src/Compilers/Core/Portable/Compilation/Compilation.cs]: We are respecting the option if that option is false we won't set `hasErrors`, but we also won't add the diagnostic to the bag. In this case we don't set `hasErrors` but we do add the diagnostic to the bag.

In other words, `hasErrors` is used to mean "stop compilation" if true, but that's not what was happening. In this case there were errors, but that doesn't imply we should stop compilation.

And reporting is just a completely different option that controls whether or not the diagnostic is output to the log at all.

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs (hunk 4 above)
Comment (agocke) [reply src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: I'm not sure it matters. Since you can't suppress an error that was originally an error, it shouldn't make a difference.

**Comment by agocke** [comment]
@nguerrera That may be your mental model, but it's not really how it works. Suppression is an orthogonal boolean state that is applied or not applied. There's no temporality or ordering, it's just suppressed or not suppressed. You can't suppress diagnostics that have the default severity of error, but that's just an unrelated rule.

**Comment by nguerrera** [comment]
I still think the way it works is counter-intuitive, and my confidence in betting that I'm not alone was based on:

1. The very fact that this bug was introduced 
2. https://github.com/dotnet/roslyn/pull/34174#discussion_r266152941
3. https://github.com/dotnet/roslyn/pull/34174#discussion_r266157645

I was further noting that since these "suppressed errors" actually show up as such in the log, there are user-facing consequences. In other words, we can't solve the confusion by choosing better method names because the confusion is not confined to the compiler implementation.

This still looks wrong to me:

``` js
"ruleId": "CS1591",
"level": "error",
"message": "Missing XML comment for publicly visible type or member 'P'",
"suppressionStates": [ "suppressedInSource" ],
```

**Comment by agocke** [comment]
@nguerrera Nope, looks right to me. The severity was error, because that was what it was elevated to, and it was suppressed in source.

**Comment by nguerrera** [comment]
@agocke By looks wrong, I meant it "feels" wrong. I fully understand that this is the design we have now. I just think it would be a much more intuitive design to say:

1. You cannot suppress errors.
2. Suppressed warnings are not elevated to errors.

Than:
 that suppressed warnings are not elevated to errors, rather than "you cannot suppress a diagnostic with default severity of error".

**Comment by agocke** [comment]
If you put the code in a compilation and call GetFilteredDiagnostics, this is what you get out. It may not be the design we'd like to have gone with, but that ship has sailed.

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs (hunk 4 above)
Comment (agocke) [reply src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: Suppressions may or may not be reported. A warning elevated to an error isn't a "real" error to me. This is the most accurate term I can think of.

Comment (agocke) [reply src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: @AlekseyTs Did this address your concern?

Comment (AlekseyTs) [reply src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: > Did this address your concern?

I do not think it did. If we haven't done filtering, we didn't have a chance to apply warn as error, correct?

---
In reply to: [266674162](https://github.com/dotnet/roslyn/pull/34174#discussion_r266674162) [](ancestors = 266674162)

Comment (AlekseyTs) [reply src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: Also, if it doesn't matter at many call sites, as you are saying. Then why adjusting those call sites?

---
In reply to: [266677762](https://github.com/dotnet/roslyn/pull/34174#discussion_r266677762) [](ancestors = 266677762,266674162)

Comment (agocke) [reply src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: That's correct. I guess I might be thinking of a different scenario: my intention was only to use this helper as a "bailout" mechanism to stop compilation, meaning that not catching errors as early as possible may affect how soon compilation stops but not affect semantic guarantees.

Did you find a place where I'm not doing that?
