### PR TITLE
Make captured "this" a constant in expression trees.

### LINKED ISSUE #6416: Incorrect expression is being generated, when anonymous event handler has closure inside
Hi.
I've a couple library classes, which helps to deal with `INotifyPropertyChanged`. Nothing magical:

    public class NotificationObject : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        protected void OnPropertyChanged<TProperty>(Expression<Func<TProperty>> property)
        {
            OnPropertyChanged(property.GetMemberPathString());
        }

        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    public static class ExpressionExtensions
    {
        private static string[] GetMemberPath(Expression expression)
        {
            MemberExpression memberExpression;
            var memberNames = new Stack<string>();

            while ((memberExpression = expression as MemberExpression) != null)
            {
                memberNames.Push(memberExpression.Member.Name);
                expression = memberExpression.Expression;
            }

            return memberNames.ToArray();
        }

        private static string GetMemberPathString(Expression expression)
        {
            return string.Join(".", GetMemberPath(expression));
        }

        public static string GetMemberPathString<TResult>(this Expression<Func<TResult>> expression)
        {
            return GetMemberPathString(expression.Body);
        }
    }

Consider this code, that uses `NotificationObject` from above:

    public class A : NotificationObject
    {
        private readonly M model;

        public A()
        {
            var boo = 200;

            model = new M();
            model.SomethingHappened += (sender, args) =>
            {
                Console.WriteLine(boo);
                OnPropertyChanged(() => Model);
            };
        }

        public M Model { get; private set; }
    }

**The issue**.
When `SomethingHappened` is raised, `ExpressionExtensions.GetMemberPathString` returns `<>4__this.Model` instead of `Model` because of incorrect member expression.

If I remove closure (that is, comment line `Console.WriteLine(boo);`), `GetMemberPathString` returns correct value - `Model`. Another workaround is to remove lambda, and handle event with regular method.

This code works correctly using VS 2013, either with closure, or without it.
Looks like a bug.

P.S. The real application, where this problem was located, is a WPF application, where such code occurs **very** often.

`M` in sample code is just a class, that generates some event:

    public class M
    {
        private async Task DoSomething()
        {
            await Task.Delay(5000);
            OnSomethingHappened();
        }

        public M()
        {
            var _ = DoSomething();
        }

        protected virtual void OnSomethingHappened()
        {
            SomethingHappened?.Invoke(this, EventArgs.Empty);
        }

        public event EventHandler SomethingHappened;
    }

### PR DESCRIPTION
**Pull request by VSadov**
"this" is semantically readonly, so it can be expressed as a constant in expression trees, and that is what native compiler does, and so should do Roslyn.

Fixes #6416

### CODE REVIEW

**Comment by VSadov** [comment]
VB did not have this and behavior was implementation specific. It is possible it could be different between Debug/Release.
I decided it makes sense to make VB behave similarly to C# here.

File: src/Compilers/VisualBasic/Test/Emit/ExpressionTrees/CodeGenExprLambda.vb [hunk 1]
```diff
@@ -8198,5 +8198,55 @@ End Module
...
+                         </compilation>
+
+
+            CompileAndVerify(source,
+                 additionalRefs:={SystemCoreRef},
+                 options:=TestOptions.ReleaseExe,
+                 expectedOutput:=<![CDATA[
+42
+value(Module1)
+]]>).VerifyDiagnostics()
```
Comment (VSadov) [inline src/Compilers/VisualBasic/Test/Emit/ExpressionTrees/CodeGenExprLambda.vb]: Native VB would produce:  
value(Module1+_Closure$__1).$VB$Me

Roslyn used to produce:  
value(Module1+_Closure$__4-0).$VB$Me

Now we have:  
value(Module1)

**Comment by VSadov** [comment]
@dotnet/roslyn-compiler - please review

**Comment by AlekseyTs** [comment]
LGTM. The change on VB side is a potential breaking change, I think we shoul get sign-off from compatibility council.

File: src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/ExpressionLambdaRewriter.cs [hunk 2]
```diff
@@ -202,7 +202,12 @@ private BoundExpression VisitExpressionWithoutStackGuard(BoundExpression node)
                 case BoundKind.DelegateCreationExpression:
                     return VisitDelegateCreationExpression((BoundDelegateCreationExpression)node);
                 case BoundKind.FieldAccess:
-                    return VisitFieldAccess((BoundFieldAccess)node);
+                    var fieldAccess = (BoundFieldAccess)node;
+                    if (fieldAccess.FieldSymbol.IsCapturedFrame)
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/ExpressionLambdaRewriter.cs]: It isn't clear that this is correct in the case of nested lambdas, as the inner frame may have different values on each invocation of the outer lambda. But perhaps this is OK because it is a constant each time the *inner* lambda is evaluated. It would be helpful to ensure we have coverage for this interaction.

Comment (VSadov) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/ExpressionLambdaRewriter.cs]: In a given display class instance the value of captured "this", if present, should never change after being assigned. I think, native compiler did not even lift those by reference and this optimization was a result of that.

It would be difficult to observe the value of the inner frame, since there is no way it can be directly referred to it from an expression. The testcase here actually involves a nested lambda.

Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LambdaRewriter/ExpressionLambdaRewriter.cs]: The generated code can reference an inner frame (when the source references variables captured into that frame). This change also changes how the inner frame is referenced. I don't know whether that is a problem or not, but I think one would need to construct a test that contains an inner frame to find out. I don't think any of these new tests do.

**Comment by VSadov** [comment]
@AlekseyTs  @gafter 
I do not think this is a compat break for VB. The original behavior was exposing internal implementation of closures and was unavoidably different in Roslyn. 
It was also dependent on the shape of captured data and thus would not be stable if capturing strategy would be optimized, improved or changed in some other way.

Basically - the new behavior is well defined while old was not. I do not think it is a break.

**Comment by VSadov** [comment]
@dotnet-bot test prtest/win/dbg/unit64 please

**Comment by AlekseyTs** [comment]
I am not saying the original behavior in VB (native compiler) is good. The new behavior makes sense to me and probably is better. I am just saying that there is an observable difference in behavior after this change, which, potentially, could break someone. There is an established protocol that we, usually, follow in cases like this.

**Comment by gafter** [comment]
LGTM, except I suggest it would be nice to construct a test in which an inner frame is captured using the new mechanism to verify that works correctly.

**Comment by VSadov** [comment]
@dotnet-bot test prtest/mac/dbg/unit32 please
