### PR TITLE
Records: override abstract inherited properties

### LINKED ISSUE #44618: Record property fails to override inherited abstract property
The spec in https://github.com/dotnet/csharplang/pull/3505 says

> For each record parameter of a record type declaration there is a corresponding public property member whose name and type are taken from the value parameter declaration. If no concrete (i.e. non-abstract) property with a get accessor and with this name and type is explicitly declared or inherited, it is produced by the compiler as follows:
> 
> For a record struct or a record class:
> 
> * A public `get` and `init` auto-property is created (see separate `init` accessor specification). Its value is initialized during construction with the value of the corresponding primary constructor parameter. **Each "matching" inherited abstract property's get accessor is overridden.**

(Emphasis mine)

However, the test `Inheritance_07` in https://github.com/dotnet/roslyn/pull/44595 demonstrates that the implementation does not obey the specification.

### PR DESCRIPTION
**Pull request by cston**
From the [records spec](https://github.com/dotnet/csharplang/blob/master/proposals/records.md#properties):

> For each record parameter of a record type declaration there is a corresponding public property
member whose name and type are taken from the value parameter declaration.
> 
> For a record:
> 
> * A public `get` and `init` auto-property is created (see separate `init` accessor specification).
  An inherited `abstract` property with matching type is overridden.
  It is an error if the inherited property does not have `public` overridable `get` and `init` accessors.
  The auto-property is initialized to the value of the corresponding primary constructor parameter.

Fixes #44618

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs [hunk 1]
```diff
@@ -16,15 +16,13 @@ namespace Microsoft.CodeAnalysis.CSharp.Symbols
     internal sealed class SynthesizedRecordPropertySymbol : SourceOrRecordPropertySymbol
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs:16]: >SynthesizedRecordPropertySymbol [](start = 26, length = 31)

It looks like changes made in this file are going to conflict with [https://github.com/dotnet/roslyn/pull/44883](https://github.com/dotnet/roslyn/pull/44883)

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs [hunk 2]
```diff
@@ -98,46 +97,42 @@ internal sealed class SynthesizedRecordPropertySymbol : SourceOrRecordPropertySy
...
 
-            public override MethodKind MethodKind => MethodKind.PropertyGet;
+            public abstract override MethodKind MethodKind { get; }
 
             public override int Arity => 0;
 
             public override bool IsExtensionMethod => false;
 
-            public override bool HidesBaseMethodsByName => false;
+            public override bool HidesBaseMethodsByName => false; // PROTOTYPE: Should this be true if it hides?
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs:117]: >// PROTOTYPE: Should this be true if it hides? [](start = 66, length = 46)

This PR is targeting master, no PROTOTYPE comments allowed. Also, I believe C# never hides by name.

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs [hunk 3]
```diff
@@ -187,12 +182,33 @@ internal override ImmutableArray<string> GetAppliedConditionalSymbols()
...
+                    paramName,
+                    getNotSet: true,
+                    isWinMdOutput: false /* unused for getters */);
+            }
+
+            public override MethodKind MethodKind => MethodKind.PropertyGet;
+
+            public override TypeWithAnnotations ReturnTypeWithAnnotations => _property.TypeWithAnnotations;
+
+            public override ImmutableArray<ParameterSymbol> Parameters => _property.Parameters; // PROTOTYPE: Shouldn't the parameters be owned by this symbol?
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs:210]: >// PROTOTYPE: Shouldn't the parameters be owned by this symbol? [](start = 96, length = 63)

Yes, they should be. I think [https://github.com/dotnet/roslyn/pull/44883](https://github.com/dotnet/roslyn/pull/44883) addresses that.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs [hunk 4]
```diff
@@ -3061,26 +3061,30 @@ ImmutableArray<PropertySymbol> addProperties(ImmutableArray<ParameterSymbol> rec
...
                     }
                     else if (existingMember is PropertySymbol { IsStatic: false, GetMethod: { } } prop
                         && prop.TypeWithAnnotations.Equals(param.TypeWithAnnotations, TypeCompareKind.AllIgnoreOptions))
                     {
                         // There already exists a member corresponding to the candidate synthesized property.
-                        // The deconstructor is specified to simply assign from this property to the corresponding out parameter.
-                        existingOrAddedMembers.Add(prop);
+                        if (isInherited && existingMember.IsAbstract)
+                        {
+                            addProperty(new SynthesizedRecordPropertySymbol(this, param, isOverride: true, diagnostics));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:3081]: >addProperty(new SynthesizedRecordPropertySymbol(this, param, isOverride: true, diagnostics)); [](start = 28, length = 93)

It doesn't look like we are properly inheriting custom modifiers for the property and the accessors. We should do what is done for regular properties and their accessors.

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs [hunk 5]
```diff
@@ -187,12 +182,33 @@ internal override ImmutableArray<string> GetAppliedConditionalSymbols()
...
+            internal abstract override void GenerateMethodBody(TypeCompilationState compilationState, DiagnosticBag diagnostics);
+        }
+
+        private sealed class GetAccessorSymbol : AccessorSymbol
+        {
+            public override string Name { get; }
+
+            public GetAccessorSymbol(SynthesizedRecordPropertySymbol property, string paramName) : base(property)
+            {
+                Name = SourcePropertyAccessorSymbol.GetAccessorName(
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs:200]: >Name [](start = 16, length = 4)

In case of an override, shouldn't we inherit the name of the accessor?

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs [hunk 6]
```diff
@@ -208,19 +224,17 @@ internal override void GenerateMethodBody(TypeCompilationState compilationState,
...
 
             public InitAccessorSymbol(
                 SynthesizedRecordPropertySymbol property,
                 string paramName,
-                DiagnosticBag diagnostics)
+                DiagnosticBag diagnostics) :
+                base(property)
             {
-                _property = property;
                 Name = SourcePropertyAccessorSymbol.GetAccessorName(
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs:238]: >Name [](start = 16, length = 4)

In case of an override, shouldn't we inherit the name of the accessor?

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 7]
```diff
@@ -4117,6 +4120,776 @@ End Class
...
+@"abstract record A
+{
+    public abstract object P1 { get; }
+    public abstract object P2 { get; set; }
+    public abstract object P3 { get; protected init; }
+    public abstract object P4 { protected get; init; }
+    public abstract object P5 { init; }
+    public abstract object P6 { set; }
+}
+record B(object P1, object P2, object P3, object P4, object P5, object P6) : A;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:4168]: >object [](start = 9, length = 6)

Are we testing scenario with a type mismatch?

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1)

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs [hunk 8]
```diff
@@ -98,46 +97,42 @@ internal sealed class SynthesizedRecordPropertySymbol : SourceOrRecordPropertySy
 
         public override SyntaxList<AttributeListSyntax> AttributeDeclarationSyntaxList => new SyntaxList<AttributeListSyntax>();
 
-        private sealed class GetAccessorSymbol : SynthesizedInstanceMethodSymbol
+        private abstract class AccessorSymbol : SynthesizedInstanceMethodSymbol
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs:100]: >AccessorSymbol [](start = 31, length = 14)

See also [https://github.com/dotnet/roslyn/pull/44883#discussion_r443289929](https://github.com/dotnet/roslyn/pull/44883#discussion_r443289929), this might make it easier to deal with overriding.

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs (hunk 3 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs:210]: Will merge [https://github.com/dotnet/roslyn/pull/44883](https://github.com/dotnet/roslyn/pull/44883) when that has been committed.

---
In reply to: [443269323](https://github.com/dotnet/roslyn/pull/45336#discussion_r443269323) [](ancestors = 443269323)

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 9]
```diff
@@ -4117,6 +4120,776 @@ End Class
...
+  IL_001d:  ldc.i4     0xa5555529
+  IL_0022:  mul
+  IL_0023:  call       ""System.Collections.Generic.EqualityComparer<object> System.Collections.Generic.EqualityComparer<object>.Default.get""
+  IL_0028:  ldarg.0
+  IL_0029:  ldfld      ""object C.<Y>k__BackingField""
+  IL_002e:  callvirt   ""int System.Collections.Generic.EqualityComparer<object>.GetHashCode(object)""
+  IL_0033:  add
+  IL_0034:  ret
+}");
+        }
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:4891]: >} [](start = 8, length = 1)

It might worth testing scenario when an abstract property gets shadowed in the intermediate base by some other member with the same name.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs (hunk 4 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:3081]: Added a test for now, and will wait for [https://github.com/dotnet/roslyn/pull/44883](https://github.com/dotnet/roslyn/pull/44883).

---
In reply to: [443270124](https://github.com/dotnet/roslyn/pull/45336#discussion_r443270124) [](ancestors = 443270124)

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs (hunk 9 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:4930]: Added a test but avoided overriding because the intermediate base members result in errors.

---
In reply to: [443766696](https://github.com/dotnet/roslyn/pull/45336#discussion_r443766696) [](ancestors = 443766696)

**Comment by AlekseyTs** [comment]
>             internal override bool HasSpecialName => _property.HasSpecialName;

I think this should always be true. There is really no relationship like that betwee a property and an accessor., I believe.

---
Refers to: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs:145 in d1f9199. [](commit_id = d1f9199cb9a273b5927d45ffe994d46027911aa2, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>     internal sealed class SynthesizedRecordEqualityContractProperty : PropertySymbol

It looks like there are the same issues around custom modifiers for an override case.

---
Refers to: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs:15 in d1f9199. [](commit_id = d1f9199cb9a273b5927d45ffe994d46027911aa2, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>             public override ImmutableArray<ParameterSymbol> Parameters => _property.Parameters;

Same problem as with other accessor types

---
Refers to: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs:117 in d1f9199. [](commit_id = d1f9199cb9a273b5927d45ffe994d46027911aa2, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>             internal override CallingConvention CallingConvention => CallingConvention.HasThis;

In one place this type is generalized, in others it is not. For example, is this correct for a static acessor?

---
Refers to: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs:155 in d1f9199. [](commit_id = d1f9199cb9a273b5927d45ffe994d46027911aa2, deletion_comment = False)

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 10]
```diff
@@ -4117,6 +4120,991 @@ End Class
...
+                Diagnostic(ErrorCode.ERR_BadRecordMemberForPositionalParameter, "P2").WithArguments("A.P2", "string", "P2").WithLocation(6, 28));
+
+            var actualMembers = GetProperties(comp, "B").ToTestDisplayStrings();
+            var expectedMembers = new[]
+            {
+                "System.Type B.EqualityContract { get; }",
+                "System.Object B.P1 { get; init; }",
+                "System.Object B.P2 { get; init; }",
+                "System.Object B.P3 { get; init; }",
+                "System.Object B.P4 { get; init; }",
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:4243]: >System.Object B.P4 { get; init; } [](start = 17, length = 33)

Where P3 and P4 came from?

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 11]
```diff
@@ -4117,6 +4120,991 @@ End Class
...
+                Diagnostic(ErrorCode.ERR_BadRecordMemberForPositionalParameter, "P1").WithArguments("A.P1", "string", "P1").WithLocation(6, 17),
+                // (6,28): error CS8866: Record member 'A.P2' must be a readable instance property of type 'string' to match positional parameter 'P2'.
+                // record B(string P1, string P2) : A;
+                Diagnostic(ErrorCode.ERR_BadRecordMemberForPositionalParameter, "P2").WithArguments("A.P2", "string", "P2").WithLocation(6, 28));
+
+            var actualMembers = GetProperties(comp, "B").ToTestDisplayStrings();
+            var expectedMembers = new[]
+            {
+                "System.Type B.EqualityContract { get; }",
+                "System.Object B.P1 { get; init; }",
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:4240]: >System.Object [](start = 17, length = 13)

Should this be string?

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 12]
```diff
@@ -4117,6 +4120,991 @@ End Class
...
+                "System.Object B.P2 { get; init; }",
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:4241]: >System.Object [](start = 17, length = 13)

Should this be string?

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 13]
```diff
@@ -4117,6 +4120,991 @@ End Class
...
+                // (9,21): error CS0533: 'B.X()' hides inherited abstract member 'A.X'
+                //     public new void X() { }
+                Diagnostic(ErrorCode.ERR_HidingAbstractMethod, "X").WithArguments("B.X()", "A.X").WithLocation(9, 21),
+                // (10,23): error CS0533: 'B.Y' hides inherited abstract member 'A.Y'
+                //     public new struct Y { }
+                Diagnostic(ErrorCode.ERR_HidingAbstractMethod, "Y").WithArguments("B.Y", "A.Y").WithLocation(10, 23),
+                // (12,8): error CS0534: 'C' does not implement inherited abstract member 'A.X.init'
+                // record C(object X, object Y) : B;
+                Diagnostic(ErrorCode.ERR_UnimplementedAbstractMethod, "C").WithArguments("C", "A.X.init").WithLocation(12, 8),
+                // (12,8): error CS0534: 'C' does not implement inherited abstract member 'A.Y.init'
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:4971]: >// (12,8): error CS0534: 'C' does not implement inherited abstract member 'A.Y.init' [](start = 16, length = 84)

It looks like a duplicate error is reported.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 14]
```diff
@@ -4117,6 +4120,991 @@ End Class
...
+                // record C(object X, object Y) : B;
+                Diagnostic(ErrorCode.ERR_UnimplementedAbstractMethod, "C").WithArguments("C", "A.Y.init").WithLocation(12, 8),
+                // (12,8): error CS0534: 'C' does not implement inherited abstract member 'A.X.get'
+                // record C(object X, object Y) : B;
+                Diagnostic(ErrorCode.ERR_UnimplementedAbstractMethod, "C").WithArguments("C", "A.X.get").WithLocation(12, 8),
+                // (12,8): error CS0534: 'C' does not implement inherited abstract member 'A.Y.get'
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:4977]: >// (12,8): error CS0534: 'C' does not implement inherited abstract member 'A.Y.get' [](start = 16, length = 83)

Here is another one

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 15]
```diff
@@ -4117,6 +4120,991 @@ End Class
...
+  .method public abstract virtual instance object GetProperty2() { }
+  .method public abstract virtual instance void modreq(System.Runtime.CompilerServices.IsExternalInit) SetProperty2(object 'value') { }
+}";
+            var refA = CompileIL(sourceA);
+
+            var sourceB =
+@"record B(object P) : A;";
+            var comp = CreateCompilation(sourceB, new[] { refA }, parseOptions: TestOptions.RegularPreview);
+            comp.VerifyDiagnostics();
+
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:5029]: Can we execute and observe that runtime considers things implemented by property in B?

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs (hunk 13 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:4971]: This error is for `A.Y.init`, the previous error is for `A.X.init`.

---
In reply to: [443958403](https://github.com/dotnet/roslyn/pull/45336#discussion_r443958403) [](ancestors = 443958403)

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs [hunk 16]
```diff
@@ -243,87 +261,13 @@ private sealed class InitAccessorSymbol : SynthesizedInstanceMethodSymbol
...
-
-            public override RefKind RefKind => RefKind.None;
-
-            public override FlowAnalysisAnnotations ReturnTypeFlowAnalysisAnnotations => FlowAnalysisAnnotations.None;
-
-            public override ImmutableArray<TypeWithAnnotations> TypeArgumentsWithAnnotations => ImmutableArray<TypeWithAnnotations>.Empty;
-
-            public override ImmutableArray<TypeParameterSymbol> TypeParameters => ImmutableArray<TypeParameterSymbol>.Empty;
-
             public override ImmutableArray<ParameterSymbol> Parameters => ImmutableArray.Create(SynthesizedParameterSymbol.Create(
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs:264]: >SynthesizedParameterSymbol.Create [](start = 96, length = 33)

Every time allocating a new parameter.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 17]
```diff
@@ -4117,6 +4120,991 @@ End Class
...
+  {
+  }
+  .property instance class [mscorlib]System.Type modopt(int32) EqualityContract()
+  {
+    .get instance class [mscorlib]System.Type modopt(int32) A::get_EqualityContract()
+  }
+  .property instance object modopt(uint16) P()
+  {
+    .get instance object modopt(uint16) A::get_P()
+    .set instance void modreq(System.Runtime.CompilerServices.IsExternalInit) A::set_P(object modopt(uint16))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:5071]: >modreq(System.Runtime.CompilerServices.IsExternalInit)  [](start = 23, length = 55)

Please add a modopt here in addition to the modreq.

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs (hunk 16 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs:264]: This was not part of this PR and has changed in [https://github.com/dotnet/roslyn/pull/44883](https://github.com/dotnet/roslyn/pull/44883).

---
In reply to: [443960042](https://github.com/dotnet/roslyn/pull/45336#discussion_r443960042) [](ancestors = 443960042)

**Comment by cston** [comment]
>     internal sealed class SynthesizedRecordEqualityContractProperty : PropertySymbol

If those are still issues after [https://github.com/dotnet/roslyn/pull/44883](https://github.com/dotnet/roslyn/pull/44883) is merged, I'll make the necessary changes then.

---
In reply to: [647869177](https://github.com/dotnet/roslyn/pull/45336#issuecomment-647869177) [](ancestors = 647869177)

---
Refers to: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs:15 in d1f9199. [](commit_id = d1f9199cb9a273b5927d45ffe994d46027911aa2, deletion_comment = False)

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 18]
```diff
@@ -4117,6 +4120,991 @@ End Class
...
+                {
+                    var returnType = getMethod.ReturnTypeWithAnnotations;
+                    Assert.True(getMethod.OverriddenMethod.ReturnTypeWithAnnotations.Equals(returnType, TypeCompareKind.ConsiderEverything));
+                    AssertEx.Equal(expectedModifiers, returnType.CustomModifiers);
+                }
+                if (property.SetMethod is MethodSymbol setMethod)
+                {
+                    var parameterType = setMethod.Parameters[0].TypeWithAnnotations;
+                    Assert.True(setMethod.OverriddenMethod.Parameters[0].TypeWithAnnotations.Equals(parameterType, TypeCompareKind.ConsiderEverything));
+                    AssertEx.Equal(expectedModifiers, parameterType.CustomModifiers);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:5103]: >AssertEx.Equal(expectedModifiers, parameterType.CustomModifiers); [](start = 20, length = 65)

Should also assert modifiers on return type.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 19]
```diff
@@ -4117,6 +4120,991 @@ End Class
...
+  .method family virtual instance class [mscorlib]System.Type modopt(int32) get_EqualityContract() { ldnull ret }
+  .method public abstract virtual instance object modopt(uint16) get_P() { }
+  .method public abstract virtual instance void modreq(System.Runtime.CompilerServices.IsExternalInit) set_P(object modopt(uint16) 'value') { }
+}";
+            var refA = CompileIL(sourceA);
+
+            var sourceB =
+@"record B(object P) : A;";
+            var comp = CreateCompilation(sourceB, new[] { refA }, parseOptions: TestOptions.RegularPreview);
+            comp.VerifyDiagnostics();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:5082]: >comp.VerifyDiagnostics(); [](start = 12, length = 25)

Can we execute and observe that runtime considers things implemented by property in B?

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordClone.cs [hunk 20]
```diff
@@ -19,11 +19,11 @@ internal sealed class SynthesizedRecordClone : SynthesizedInstanceMethodSymbol
         public override NamedTypeSymbol ContainingType { get; }
         public override bool IsOverride { get; }
 
-        public SynthesizedRecordClone(NamedTypeSymbol containingType)
+        public SynthesizedRecordClone(NamedTypeSymbol containingType, MethodSymbol? baseClone)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordClone.cs:22]: >MethodSymbol? baseClone [](start = 70, length = 23)

Is this change related to overriding abstract record properties?

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs [hunk 21]
```diff
@@ -46,71 +57,39 @@ protected override Location TypeLocation
...
         {
             Debug.Assert(syntax is object);
             Debug.Assert(isAutoPropertyAccessor);
+
+            var overriddenProperty = OverriddenProperty;
+            var overriddenAccessor = overriddenProperty is null ?
+                null :
+                (isGet ? overriddenProperty.GetMethod : overriddenProperty.SetMethod);
+            string name = overriddenAccessor?.Name ??
+                SourcePropertyAccessorSymbol.GetAccessorName(_sourceName, isGet, this.IsCompilationOutputWinMdObj());
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs:85]: This looks suspicious. Doesn't SourcePropertyAccessorSymbol.CreateAccessorSymbol takes care of this?

File: src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs [hunk 22]
```diff
@@ -94,39 +102,18 @@ private enum Flags : byte
...
-                out var getSyntax,
-                out var setSyntax);
-
-            var hasGetAccessor = getSyntax is object;
-            var hasSetAccessor = setSyntax is object;
-
-            bool modifierErrors;
-            _modifiers = MakeModifiers(modifiers, isExplicitInterfaceImplementation, isIndexer,
-                                       accessorsHaveImplementation, location,
-                                       diagnostics, out modifierErrors);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs:124]: I am not comfortable with removal of this code. Anything that deals with diagnostics should stay here for now. derived types shouldn't be in the business of deciding what checks should be performed

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs [hunk 23]
```diff
@@ -21,14 +17,29 @@ internal sealed class SynthesizedRecordPropertySymbol : SourcePropertySymbolBase
...
+            : base(
+                containingType,
                 binder: null,
-                backingParameter.GetNonNullSyntaxNode(),
+                syntax: syntax,
+                getSyntax: syntax,
+                setSyntax: syntax,
+                arrowExpression: null,
+                interfaceSpecifier: null,
+                modifiers: DeclarationModifiers.Public | (isOverride ? DeclarationModifiers.Override : DeclarationModifiers.None),
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs:32]: >DeclarationModifiers.Public | (isOverride ? DeclarationModifiers.Override : DeclarationModifiers.None) [](start = 27, length = 102)

This lacks required validation. Please restore original implementation when validation is performed in the base constructor.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertyAccessorSymbol.cs [hunk 24]
```diff
@@ -118,29 +118,18 @@ internal sealed class SourcePropertyAccessorSymbol : SourceMemberMethodSymbol
...
             DeclarationModifiers propertyModifiers,
-            string propertyName,
+            string name,
             Location location,
             CSharpSyntaxNode syntax,
             DiagnosticBag diagnostics)
         {
-            string name;
-            ImmutableArray<MethodSymbol> explicitInterfaceImplementations;
-            GetNameAndExplicitInterfaceImplementations(
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertyAccessorSymbol.cs:128]: >GetNameAndExplicitInterfaceImplementations [](start = 12, length = 42)

I do not understand why this call is removed. It still does useful work of figuring out the name, that shouldn't be a responsibility of the caller. Please revert.

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs (hunk 21 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordPropertySymbol.cs:85]: It looks like SourcePropertyAccessorSymbol constructor deals with this.

```
            if (this.IsOverride)
            {
                MethodSymbol overriddenMethod = this.OverriddenMethod;
                if ((object)overriddenMethod != null)
                {
                    // If this accessor is overriding a method from metadata, it is possible that
                    // the name of the overridden method doesn't follow the C# get_X/set_X pattern.
                    // We should copy the name so that the runtime will recognize this as an override.
                    _name = overriddenMethod.Name;
                }
            }
```

The ```SourcePropertyAccessorSymbol.GetAccessorName``` is also a code duplication.

I think we can remove all of it.

---
In reply to: [446523951](https://github.com/dotnet/roslyn/pull/45336#discussion_r446523951) [](ancestors = 446523951)

File: src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs (hunk 22 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs:124]: > I am not comfortable with removal of this code. 

On second thought, that is probably a change worth making. 

---
In reply to: [446524304](https://github.com/dotnet/roslyn/pull/45336#discussion_r446524304) [](ancestors = 446524304)

**Comment by AlekseyTs** [comment]
>     internal sealed class SynthesizedRecordEqualityContractProperty : PropertySymbol

I am planning to take care of this property under umbrella of #45296. There is a lot of work needed here and for the sake of speeding up this PR, which will start blocking me soon due to changes to base classes, I suggest to avoid making any changes to this property, if possible. 

---
Refers to: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs:15 in 63b0dae. [](commit_id = 63b0dae1b7bab55dc23518fb5754b1e4cb6ff3e7, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs [hunk 25]
```diff
@@ -3058,26 +3060,32 @@ ImmutableArray<PropertySymbol> addProperties(ImmutableArray<ParameterSymbol> rec
                 int addedCount = 0;
                 foreach (ParameterSymbol param in recordParameters)
                 {
-                    var property = new SynthesizedRecordPropertySymbol(this, param, diagnostics);
-                    _ = memberSignatures.TryGetValue(property, out var existingMember);
-                    existingMember ??= getInheritedMember(property, this);
+                    bool isInherited = false;
+                    var syntax = param.GetNonNullSyntaxNode();
+                    var property = new SynthesizedRecordPropertySymbol(this, syntax, param, isOverride: false, diagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:3065]: >SynthesizedRecordPropertySymbol [](start = 39, length = 31)

Consider using SignatureOnlyPropertySymbol to check for existing member. I am planning to switch all checks like that in this function to use SignatureOnly symbols. I think this will eliminate some overhead and will add some predictability in terms of what is happening and when.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs [hunk 26]
```diff
@@ -3058,26 +3060,32 @@ ImmutableArray<PropertySymbol> addProperties(ImmutableArray<ParameterSymbol> rec
...
+                    if (!memberSignatures.TryGetValue(property, out var existingMember))
+                    {
+                        Debug.Assert(property.OverriddenOrHiddenMembers.OverriddenMembers.Length == 0); // property is not virtual and should not have overrides
+                        existingMember = property.OverriddenOrHiddenMembers.HiddenMembers.FirstOrDefault();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:3069]: >property.OverriddenOrHiddenMembers.HiddenMembers.FirstOrDefault(); [](start = 41, length = 66)

Do we care if the hidden member is not a property?

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs [hunk 27]
```diff
@@ -2992,10 +2992,12 @@ private void AddSynthesizedRecordMembersIfNecessary(MembersAndInitializersBuilde
                 addDeconstruct(ctor.Parameters, existingOrAddedMembers);
             }
 
+            var baseClone = SynthesizedRecordClone.FindValidCloneMethod(BaseTypeNoUseSiteDiagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:2995]: >var baseClone = SynthesizedRecordClone.FindValidCloneMethod(BaseTypeNoUseSiteDiagnostics); [](start = 12, length = 90)

This change looks unrelated to the stated goal of this PR, consider extracting it into a separate PR in order to speed up completion of this PR.

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs [hunk 28]
```diff
@@ -16,13 +16,19 @@ internal sealed class SynthesizedRecordEqualityContractProperty : PropertySymbol
     {
         internal const string PropertyName = "EqualityContract";
 
-        public SynthesizedRecordEqualityContractProperty(NamedTypeSymbol containingType, bool isOverride)
+        public SynthesizedRecordEqualityContractProperty(NamedTypeSymbol containingType, NamedTypeSymbol? baseRecordType)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs:19]: >NamedTypeSymbol? baseRecordType [](start = 89, length = 31)

It feels like this parameter is unnecessary. If the base of containing type is object, it is virtual. Otherwise, it is override.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertyAccessorSymbol.cs (hunk 24 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertyAccessorSymbol.cs:128]: Let's not duplicate the logic of figuring out initial name in every call site.

---
In reply to: [446525457](https://github.com/dotnet/roslyn/pull/45336#discussion_r446525457) [](ancestors = 446525457)

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 15), tests are not looked at.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs [hunk 29]
```diff
@@ -71,20 +70,29 @@ private enum Flags : byte
...
+            bool isIndexer,
+            bool hasInitializer,
+            bool isAutoProperty,
+            bool hasAccessorList,
+            bool isInitOnly,
+            RefKind refKind,
+            string name,
+            Location location,
+            TypeWithAnnotations typeOpt,
+            ImmutableArray<ParameterSymbol> parametersOpt,
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs:90]: >parametersOpt [](start = 44, length = 13)

This could either be empty, or default. Consider passing a boolean "hasParameters" instead.

Comment (cston) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs:90]: `IsDefault` captures that.

---
In reply to: [446545495](https://github.com/dotnet/roslyn/pull/45336#discussion_r446545495) [](ancestors = 446545495)

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs (hunk 28 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs:19]: In error cases, when overriding a non-record type, this property should not be considered an override.

---
In reply to: [446541790](https://github.com/dotnet/roslyn/pull/45336#discussion_r446541790) [](ancestors = 446541790)

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs (hunk 26 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:3067]: > Do we care if the hidden member is not a property?

Not currently we don't. We report an error if the property hides a distinct member. (That is existing behavior.)

---
In reply to: [446540627](https://github.com/dotnet/roslyn/pull/45336#discussion_r446540627) [](ancestors = 446540627)

**Comment by cston** [comment]
>     internal sealed class SynthesizedRecordEqualityContractProperty : PropertySymbol

There are minimal changes to this file, some of which are responses to earlier comments.

---
In reply to: [650563133](https://github.com/dotnet/roslyn/pull/45336#issuecomment-650563133) [](ancestors = 650563133)

---
Refers to: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs:15 in 63b0dae. [](commit_id = 63b0dae1b7bab55dc23518fb5754b1e4cb6ff3e7, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs (hunk 25 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:3063]: That seems like a separable change.

---
In reply to: [446540258](https://github.com/dotnet/roslyn/pull/45336#discussion_r446540258) [](ancestors = 446540258)

File: src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs (hunk 29 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs:90]: > IsDefault captures that.

Why give an illusion that you can pass a non-empty array?

---
In reply to: [446549153](https://github.com/dotnet/roslyn/pull/45336#discussion_r446549153) [](ancestors = 446549153,446545495)

**Comment by AlekseyTs** [comment]
>     internal sealed class SynthesizedRecordEqualityContractProperty : PropertySymbol

> There are minimal changes to this file, some of which are responses to earlier comments.


This is all throw away work, I am going to rewrite this anyway. Up to you.

---
In reply to: [650598383](https://github.com/dotnet/roslyn/pull/45336#issuecomment-650598383) [](ancestors = 650598383,650563133)

---
Refers to: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs:15 in 63b0dae. [](commit_id = 63b0dae1b7bab55dc23518fb5754b1e4cb6ff3e7, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs (hunk 28 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs]: > In error cases, when overriding a non-record type, this property should not be considered an override.

I do not believe this is worth the added complexity. I am going to change this in an upcoming PR anyway.

---
In reply to: [446551544](https://github.com/dotnet/roslyn/pull/45336#discussion_r446551544) [](ancestors = 446551544,446541790)

**Comment by AlekseyTs** [comment]
>             internal override bool HasSpecialName => _property.HasSpecialName;

> I think this should always be true. There is really no relationship like that between a property and an accessor., I believe.

It doesn't look like the change went for the better.

---
In reply to: [647868847](https://github.com/dotnet/roslyn/pull/45336#issuecomment-647868847) [](ancestors = 647868847)

---
Refers to: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs:145 in d1f9199. [](commit_id = d1f9199cb9a273b5927d45ffe994d46027911aa2, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs (hunk 29 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs:90]: We don't often allow a `default` value for `Parameters`.

---
In reply to: [446555527](https://github.com/dotnet/roslyn/pull/45336#discussion_r446555527) [](ancestors = 446555527,446549153,446545495)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs:90]: > We don't often allow a default value for Parameters.

Sorry, I am not following. Let me rephrase the question. Why use an array type to communicate a boolean state? Things simply wouldn't work properly if one passes an array with actual parameter symbols in it. No one makes sure the symbols would be linked properly. So, why give consumer an illusion that the constructor can properly deal with the situation?

---
In reply to: [446569515](https://github.com/dotnet/roslyn/pull/45336#discussion_r446569515) [](ancestors = 446569515,446555527,446549153,446545495)

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs [hunk 30]
```diff
@@ -3058,26 +3058,32 @@ ImmutableArray<PropertySymbol> addProperties(ImmutableArray<ParameterSymbol> rec
...
-                        members.Add(property);
-                        members.Add(property.GetMethod);
-                        members.Add(property.SetMethod);
-                        members.Add(property.BackingField);
-
-                        builder.InstanceInitializersForRecordDeclarationWithParameters.Insert(addedCount, new FieldOrPropertyInitializer.Builder(property.BackingField, paramList.Parameters[param.Ordinal]));
-                        addedCount++;
+                        addProperty(property);
                     }
                     else if (existingMember is PropertySymbol { IsStatic: false, GetMethod: { } } prop
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:3074]: >GetMethod: { } [](start = 81, length = 14)

The current specification, that I think should be up to date given the time when the #44618 was created, and the rules stated in the issue disagree.

The issue:
> For each record parameter of a record type declaration there is a corresponding public property member whose name and type are taken from the value parameter declaration. If no concrete (i.e. non-abstract) property with a get accessor and with this name and type is explicitly declared or inherited, it is produced by the compiler as follows:
> 
> For a record struct or a record class:
> 
> * A public `get` and `init` auto-property is created (see separate `init` accessor specification). Its value is initialized during construction with the value of the corresponding primary constructor parameter. **Each "matching" inherited abstract property's get accessor is overridden.**

The specification:
>A public get and init auto-property is created (see separate init accessor specification). Each "matching" inherited abstract accessor is overridden. The auto-property is initialized to the value of the corresponding primary constructor parameter.
For each record parameter of a record type declaration there is a corresponding public property member whose name and type are taken from the value parameter declaration.
>
>For a record:
>
> * A public get and init auto-property is created (see separate init accessor specification). Each "matching" inherited abstract accessor is overridden. The auto-property is initialized to the value of the corresponding primary constructor parameter.

Could you please reconcile the differences? This is not blocking

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 31]
```diff
@@ -3227,15 +3230,15 @@ public void Inheritance_08()
 }";
             var comp = CreateCompilation(source);
             comp.VerifyDiagnostics(
-                // (11,8): error CS0534: 'C' does not implement inherited abstract member 'B.Y.get'
+                // (11,14): error CS0546: 'C.X.init': cannot override because 'A.X' does not have an overridable set accessor
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:3233]: >// (11,14): error CS0546: 'C.X.init': cannot override because 'A.X' does not have an overridable set accessor [](start = 16, length = 109)

It doesn't look like this error follows specification from the #44618.

It says:
> Each "matching" inherited abstract property's get accessor is overridden.

However it doesn't say anything about init/set accessors. From reading the specification I am getting an impression that we shouldn't be reporting an error for this scenario, we override the getter and leave the init accessor not overriding anything. This, however, isn't something that you can express in a regular C# today. So, it would make sense to not support this for synthesized properties as well. Please, include amended specification in the description of this PR, so that reviewers could review against it.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 32]
```diff
@@ -3920,202 +3923,1427 @@ public void Inheritance_28()
...
             var sourceB =
-@"record C(object P, object Q, object R) : B
+@"using static System.Console;
+record B(object P) : A
 {
+    static void Main()
+    {
+        B b = new B(3);
+        WriteLine(b.P);
+        WriteLine(((A)b).P);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:5238]: >WriteLine(((A)b).P); [](start = 8, length = 20)

It doesn't look like we are exercising overriding of the setter

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 33]
```diff
@@ -3920,202 +3923,1427 @@ public void Inheritance_28()
...
             var sourceB =
-@"record B(object P, object Q) : A
+@"using static System.Console;
+record B(object P) : A
 {
+    static void Main()
+    {
+        B b = new B(3);
+        WriteLine(b.P);
+        WriteLine(((A)b).P);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:5158]: >WriteLine(((A)b).P); [](start = 8, length = 20)

It doesn't look like we are exercising overriding of the setter

File: src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs (hunk 29 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbolBase.cs:90]: Makes sense, thanks.

---
In reply to: [446582904](https://github.com/dotnet/roslyn/pull/45336#discussion_r446582904) [](ancestors = 446582904,446569515,446555527,446549153,446545495)

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 34]
```diff
@@ -3920,202 +3923,1427 @@ public void Inheritance_28()
...
-@"record B(object P, object Q) : A
+@"using static System.Console;
+record B(object P) : A
 {
-    object P { get; }
+    static void Main()
+    {
+        B b = new B(3);
+        WriteLine(b.P);
+        WriteLine(((A)b).P);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:5098]: >WriteLine(((A)b).P); [](start = 8, length = 20)

It doesn't look like we are exercising overriding of the setter

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 17)

**Comment by cston** [comment]
@dotnet/roslyn-compiler, please review.

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs [hunk 35]
```diff
@@ -144,7 +147,7 @@ public GetAccessorSymbol(SynthesizedRecordEqualityContractProperty property)
 
             public override ImmutableHashSet<string> ReturnNotNullIfParameterNotNull => ImmutableHashSet<string>.Empty;
 
-            internal override bool HasSpecialName => _property.HasSpecialName;
+            internal override bool HasSpecialName => true;
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs:150]: I don't understand this change, doesn't this correspond to the 'rtspecialname' metadata flag?

Comment (cston) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordEqualityContractProperty.cs:150]: `HasSpecialName` corresponds to the `specialname` metadata bit. Property accessors should set that bit.

---
In reply to: [447926980](https://github.com/dotnet/roslyn/pull/45336#discussion_r447926980) [](ancestors = 447926980)
