### PR TITLE
"Generate method" refactoring enabled if method name is equal to imported type.

### LINKED ISSUE #16975: Refactoring "Generate method" not suggested.
**Version Used**: Visual Studio 2017 RC 15.0.0-RC3+26127.0

**Code to Reproduce**:
```csharp
using Microsoft.CodeAnalysis;

namespace My
{
    public static class Foo
    {
        public static void Bar(SyntaxNode node)
        {
            ReportDiagnostic(node); // "Generate method" not suggested here

            ReportDiagnostic2(node); // "Generate method" suggested here
        }
    }
}
```

It seems that this error occurs when there is a type with same name as method that would be generated. In this case there is enum "Microsoft.CodeAnalysis.ReportDiagnostic".

### PR DESCRIPTION
**Pull request by zaytsev-victor**
Fixes #16975

<details><summary>Ask Mode template not completed</summary>

### Customer scenario

What does the customer do to get into this situation, and why do we think this
is common enough to address for this release.  (Granted, sometimes this will be
obvious "Open project, VS crashes" but in general, I need to understand how
common a scenario is)

### Bugs this fixes

(either VSO or GitHub links)

### Workarounds, if any

Also, why we think they are insufficient for RC vs. RC2, RC3, or RTW

### Risk

This is generally a measure our how central the affected code is to adjacent
scenarios and thus how likely your fix is to destabilize a broader area of code

### Performance impact

(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")

### Root cause analysis

How did we miss it?  What tests are we adding to guard against it in the future?

### How was the bug found?

(E.g. customer reported it vs. ad hoc testing)

### Test documentation updated?

If this is a new non-compiler feature or a significant improvement to an existing feature, update https://github.com/dotnet/roslyn/wiki/Manual-Testing once you know which release it is targeting.

</details>

### CODE REVIEW

File: src/Features/VisualBasic/Portable/CodeFixes/GenerateParameterizedMember/GenerateParameterizedMemberCodeFixProvider.vb [hunk 1]
```diff
@@ -30,10 +30,15 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.CodeFixes.GenerateMethod
         Friend Const BC32045 As String = "BC32045" ' error BC32045: 'Private Sub Blah()' has no type parameters and so cannot have type arguments.
         Friend Const BC32087 As String = "BC32087" ' error BC32087: Overload resolution failed because no accessible 'Blah' accepts this number of type arguments.
         Friend Const BC36625 As String = "BC36625" ' error BC36625: Lambda expression cannot be converted to 'Integer' because 'Integer' is not a delegate type.
+        Friend Const BC30107 As String = "BC30107" ' error BC30107: 'Foo' is an Enum type and cannot be used as an expression.
+        Friend Const BC30108 As String = "BC30108" ' error BC30108: 'Foo' is a type and cannot be used as an expression.
+        Friend Const BC30109 As String = "BC30109" ' error BC30109: 'Foo' is a class type and cannot be used as an expression.
+        Friend Const BC30110 As String = "BC30110" ' error BC30110: 'Foo' is a structure type and cannot be used as an expression.
+        Friend Const BC30111 As String = "BC30111" ' error BC30111: 'Foo' is an interface type and cannot be used as an expression.
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/CodeFixes/GenerateParameterizedMember/GenerateParameterizedMemberCodeFixProvider.vb]: Thanks for checking all these cases.  It would have been easy to miss one.

Note: do we need a case for if 'Foo' is a delegate type?

File: src/EditorFeatures/CSharpTest/Diagnostics/GenerateMethod/GenerateMethodTests.cs [hunk 2]
```diff
@@ -7440,6 +7440,216 @@ private string Method()
...
+        public async Task TestWithSameMethodNameAsTypeName1()
+        {
+            await TestAsync(
+@"using System;
+
+class C
+{
+    public void M1()
+    {
+        [|Foo|]();
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Diagnostics/GenerateMethod/GenerateMethodTests.cs]: Fyi: Foo can't be used in the codebase.  You can easily rename this to Goo though.

File: src/EditorFeatures/VisualBasicTest/Diagnostics/GenerateMethod/GenerateMethodTests.vb [hunk 3]
```diff
@@ -4191,6 +4191,183 @@ Class Program
...
         End Function
 
+                    <WorkItem(16975, "https://github.com/dotnet/roslyn/issues/16975")>
+            <Fact, Trait(Traits.Feature, Traits.Features.CodeActionsGenerateMethod)>
+            Public Async Function TestWithSameMethodNameAsTypeName1() As Task
+                Await TestInRegularAndScriptAsync(
+"Imports System
+Class C
+    Sub Bar()
+        [|Foo|]()
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/VisualBasicTest/Diagnostics/GenerateMethod/GenerateMethodTests.vb]: Note: for VB we *probably* do not want to offer generate-method if you've just written Foo without parens.  In that case, it's just not that likely htat you were attempting to create a method with that name, but were instead trying to reference the type.

If that's hte current behavior, great.  Just please add a test.  If that isn't the behavior, then we should add a check to have that behavior.

File: src/Features/VisualBasic/Portable/CodeFixes/GenerateParameterizedMember/GenerateParameterizedMemberCodeFixProvider.vb (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Features/VisualBasic/Portable/CodeFixes/GenerateParameterizedMember/GenerateParameterizedMemberCodeFixProvider.vb]: I see that you added one.  Awesome!

**Comment by CyrusNajmabadi** [comment]
Thanks for the PR.  I just hit this recently and it was super annoying :)

**Comment by Neme12** [comment]
@sharwell Could you add this to your backlog or notify someone else to review so that this doesn't get lost in time? Thanks.

**Comment by DustinCampbell** [comment]
@zaytsev-victor: Could you merge in the latest master?

**Comment by jinujoseph** [comment]
retest this pls

**Comment by jinujoseph** [comment]
@dotnet-bot Test this please

**Comment by jinujoseph** [comment]
test windows_debug_vs-integration_prtest
