### PR TITLE
async completion: eats existing code on commit

### LINKED ISSUE #33626: async completion: eats existing code on commit
**Version Used**: 
VS 2019 Preview 3
**Steps to Reproduce**:

1.  Create standard Console app
2. type `override` above `static void Main..` method
3. create space and press Ctrl+Space to trigger code completion
4. type `asdasdasdasdasdasd` or any random text
5. select one of code completion options and press Enter

**Expected Behavior**:
Nicely inserted new code
**Actual Behavior**:
image

### PR DESCRIPTION
**Pull request by ivanbasov**
Fixes #33626

### CODE REVIEW

File: src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CommitManager.cs [hunk 1]
```diff
@@ -130,14 +130,20 @@ internal CommitManager(ITextView textView, RecentItemsManager recentItemsManager
...
+            if (triggerDocument == null)
+            {
+                return CommitResultUnhandled;
+            }
+
             // Commit with completion service assumes that null is provided is case of invoke. VS provides '\0' in the case.
             char? commitChar = typeChar == '\0' ? null : (char?)typeChar;
             var commitBehavior = Commit(
-                document, completionService, session.TextView, subjectBuffer, 
+                triggerDocument, completionService, session.TextView, subjectBuffer,
```
Comment (dpoeschl) [inline src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CommitManager.cs]: Already signed off, but one thing to add is that maybe we should remove the `document` variable completely so people aren't tempted to use it. Or maybe rename it to disambiguate.

Comment (ivanbasov) [reply src/EditorFeatures/Core/Implementation/IntelliSense/AsyncCompletion/CommitManager.cs]: Thank you, @dpoeschl !

The `document` variable above is used to get completionService. This service can be used even if we do not have a triggerSnapshot to process `!IsCommitCharacter` and some other cases above. 

Maybe we can get `completionService` more elegant without `document`. However, this would require a more risky fix not valid for a Shiproom Approval.
