### PR TITLE
Fix WithAsyncKeyword to not drop existing modifiers

### LINKED ISSUE #54239: WithAsyncKeyword on types derived from AnonymousFunctionExpressionSyntax removes static modifier
Calling WithAsyncKeyword on a syntax node derived from AnonymousFunctionExpressionSyntax that has static keyword replaces the static keyword with async, instead of adding async besides static.

This can easily be seen from the code:

https://github.com/dotnet/roslyn/blob/0985b4d7d1655ab0116c68acd62cef0ff3a239b8/src/Compilers/CSharp/Portable/Syntax/AnonymousMethodExpressionSyntax.cs#L26-L31

The last line above passes only async keyword as the modifier, removing any existing other modifiers.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #54239

### CODE REVIEW

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNodeTests.cs [hunk 1]
```diff
@@ -3647,6 +3647,33 @@ public void SyntaxNodeContains()
...
+        }
+
+        [Fact, WorkItem(54239, "https://github.com/dotnet/roslyn/issues/54239")]
+        public void TestWithAsyncKeyword_SimpleLambdaExpressionSyntax()
+        {
+            var text = "static a => { }";
+            var expression = (SimpleLambdaExpressionSyntax)SyntaxFactory.ParseExpression(text);
+            var withAsync = expression.WithAsyncKeyword(SyntaxFactory.Token(SyntaxKind.AsyncKeyword).WithTrailingTrivia(SyntaxFactory.Space)).ToString();
+            Assert.Equal("static async a => { }", withAsync);
+        }
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNodeTests.cs:3675]: I don't think the tests cover the four possible paths in `UpdateAsyncKeyword`

File: src/Compilers/CSharp/Portable/Syntax/AnonymousFunctionExpressionSyntax.cs [hunk 2]
```diff
@@ -23,5 +23,35 @@ public AnonymousFunctionExpressionSyntax WithAsyncKeyword(SyntaxToken asyncKeywo
             => WithAsyncKeywordCore(asyncKeyword);
 
         internal abstract AnonymousFunctionExpressionSyntax WithAsyncKeywordCore(SyntaxToken asyncKeyword);
+
+        /// <summary>
+        /// If the given <paramref name="asyncKeyword"/> is default, remove async if exists.
+        /// Otherwise, replace the existing <see cref="AsyncKeyword"/> or add a new one.
+        /// </summary>
+        /// <param name="asyncKeyword"></param>
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Syntax/AnonymousFunctionExpressionSyntax.cs:31]: `<param` and `<returns>` seem unnecessary

**Review by jcouv — COMMENTED** [review]
Done with review pass (iteration 4)

**Review by jcouv — DISMISSED** [review]
LGTM Thanks (iteration 5)

**Comment by jcouv** [comment]
@dotnet/roslyn-compiler for a second review. Thanks

**Review by CyrusNajmabadi — DISMISSED** [review]

File: src/Compilers/CSharp/Portable/Syntax/AnonymousFunctionExpressionSyntax.cs [hunk 3]
```diff
@@ -23,5 +23,33 @@ public AnonymousFunctionExpressionSyntax WithAsyncKeyword(SyntaxToken asyncKeywo
...
 
         internal abstract AnonymousFunctionExpressionSyntax WithAsyncKeywordCore(SyntaxToken asyncKeyword);
+
+        /// <summary>
+        /// If the given <paramref name="asyncKeyword"/> is default, remove async if exists.
+        /// Otherwise, replace the existing <see cref="AsyncKeyword"/> or add a new one.
+        /// </summary>
+        private protected SyntaxTokenList UpdateAsyncKeyword(SyntaxToken asyncKeyword)
+        {
+            var existingAsync = AsyncKeyword;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Syntax/AnonymousFunctionExpressionSyntax.cs:33]: >AsyncKeyword [](http://example.com/codeflow?start=32&length=12)

Should we be operating on ```Modifiers``` instead? For example, if we are asked to remove an ```async``` keyword, then, perhaps, we should remove all of them from ```Modifiers```, not just the first one.

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNodeTests.cs [hunk 4]
```diff
@@ -3647,6 +3647,114 @@ public void SyntaxNodeContains()
             Assert.True(firstParens.Contains(e));
         }
 
+        [Fact, WorkItem(54239, "https://github.com/dotnet/roslyn/issues/54239")]
+        public void TestWithAsyncKeyword_AnonymousMethodExpressionSyntax_AddAsync()
+        {
+            var text = "static delegate(int i) { }";
+            var expression = (AnonymousMethodExpressionSyntax)SyntaxFactory.ParseExpression(text);
+            var withAsync = expression.WithAsyncKeyword(SyntaxFactory.Token(SyntaxKind.AsyncKeyword).WithTrailingTrivia(SyntaxFactory.Space)).ToString();
+            Assert.Equal("static async delegate(int i) { }", withAsync);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNodeTests.cs:3656]: >Assert.Equal("static async delegate(int i) { }", withAsync); [](http://example.com/codeflow?start=12&length=60)

Is this what we normally do for tests like this, i.e checking the text rather than the shape of the tree that the API is supposed to create?

**Comment by AlekseyTs** [comment]
Done with review pass (commit 5)

File: src/Compilers/CSharp/Portable/Syntax/AnonymousFunctionExpressionSyntax.cs (hunk 3 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Syntax/AnonymousFunctionExpressionSyntax.cs:33]: @AlekseyTs My expectation of the `WithAsyncKeyword` is to be consistent with the behavior of `AsyncKeyword` property.

Since it's just "AsyncKeyword" that returns a single token, rather than "AsyncKeywords", I'm expecting `WithAsyncKeyword` to replace whatever token "AsyncKeyword" returns.

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNodeTests.cs (hunk 4 above)
Comment (Youssef1313) [reply src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNodeTests.cs:3656]: @AlekseyTs I think there is an inconsistency here among the existing tests. For example:

https://github.com/dotnet/roslyn/blob/1c7050e4cb294031f8b3030c6b090db159105962/src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNodeTests.cs#L49-L57

IMO it's okay to simply check the string in this case. We just want to assert that static doesn't get removed, which the current test does.

But I'm open to change the test here if you prefer some other form.

File: src/Compilers/CSharp/Portable/Syntax/AnonymousFunctionExpressionSyntax.cs (hunk 3 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Syntax/AnonymousFunctionExpressionSyntax.cs:33]: > My expectation of the WithAsyncKeyword is to be consistent with the behavior of AsyncKeyword property.

> Since it's just "AsyncKeyword" that returns a single token, rather than "AsyncKeywords", I'm expecting WithAsyncKeyword to replace whatever token "AsyncKeyword" returns.

Do we have tests demonstraiting behavior of AsyncKeyword property after the replacement in presence of multiple keywords in modifiers? Does it really return ```default``` after ```UpdateAsyncKeyword(default)```? Does it really return the token that was passed in in other cases?

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Syntax/AnonymousFunctionExpressionSyntax.cs:33]: > in presence of multiple keywords in modifiers? Does it really return `default` after `UpdateAsyncKeyword(default)`?

It will return the second async token in the original node (which will be the first of the new node). I see the point, and I'm a bit confused what the behavior should be. One possible approach is to operate only on the first async token when we are "adding" the token or "replacing" an existing one, but operate on all when removing. With this approach, accessing `.AsyncKeyword` after `UpdateAsyncKeyword` should always result in whatever was passed in.

> Does it really return the token that was passed in in other cases?

Yes I believe this should be the case, will update the tests after you confirm what the expected behavior of the API should be

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Syntax/AnonymousFunctionExpressionSyntax.cs:33]: > will update the tests after you confirm what the expected behavior of the API should be

I believe it was a mistake in the first place to add a With-er for a calculated property, i.e. property that is effectively readonly and isn't part of the node description in syntax.xml. But since we are already in this uncomfortable position, I believe the API should always remove all async keywords and, if a replacement is supplied, it should be placed at the position where the first async keyword used to be. But this is just my opinion, others might have different ideas.

Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Portable/Syntax/AnonymousFunctionExpressionSyntax.cs:33]: > I believe it was a mistake in the first place to add a With-er for a calculated property

Yeah.  This was an aspect of how the API morphed over time.  We initially only supported (And thus exposed) the 'AsyncKeyword' of these nodes.  Then, we moved to a token-list because we wanted to support `static async` or `async static`.  In the migration, for binary compat, we had to preserve the AsyncKeyword property (and we didn't want it to throw or return 'default'), so we had it fetch out the keyword from teh token list if present.  

Sounds like i rushed this part of that syntax work, and this type of issue was the fallout.  Next time i'll pay more close attention to when we switch forms and that causes this.

That said, here's how i think it should work:

1. AsyncKeyword being *read* should still fetch out the keyword from teh token list if present.
2. WithAsyncKeyword should be deprecated and we should tell people to use the token list.

What WithAsyncKeyword should do when there already is such a keyword is up in the air.  However, i lean toward being somewhat sensible.  So if there is an existing async keyword, it gets removed (following the logic of all other withers).  *Where* the new AsyncKeyword shoudl go is more flexible.  I'm ok with it always going at the start (or end) of the token list.  I think such uniform logic is sensible and fits with the 'syntax doesn't try to have heuristics in it'.

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/Syntax/AnonymousFunctionExpressionSyntax.cs]: > WithAsyncKeyword should be deprecated and we should tell people to use the token list.

For now I only fixed implementation. Should I open an issue for discussion about deprecating this API?

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 6)

**Comment by AlekseyTs** [comment]
@CyrusNajmabadi, @jcouv Please review the latest revision of the PR.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Is this ready to merge?

**Review by RikkiGibson — APPROVED** [review]

**Comment by RikkiGibson** [comment]
@jcouv did you have any additional feedback for this PR?

**Comment by jcouv** [comment]
Merged/squashed. Thanks @Youssef1313!

**Comment by jcouv** [comment]
Btw, sorry for the delay (last ping was from July). Don't hesitate to ping me regularly in the future if I dropped something

**Comment by Youssef1313** [comment]
@jcouv No problem!
