### PR TITLE
Test/fix scoping rules for pattern locals declared within a local declaration statement

### LINKED ISSUE #9612: Unexpected errors are reported when pattern locals conflict with regular locals declared within the same statement
The following test fails 
```
        [Fact]
        public void LocalDeclarationStmt_01()
        {
            var source =
@"
public class X
{
    public static void Main()
    {
        object x1 = Dummy(null,
                          new object() is var x1, x1);
    }

    static object Dummy(object x, params object[] y) {return x;}
}
";
            var compilation = CreateCompilationWithMscorlib45(source, options: TestOptions.DebugExe, parseOptions: patternParseOptions);
            compilation.VerifyDiagnostics(
// (7,47): error CS0136: A local or parameter named 'x1' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
//                           new object() is var x1, x1);
Diagnostic(ErrorCode.ERR_LocalIllegallyOverrides, "x1").WithArguments("x1").WithLocation(7, 47)
                );
        }
```

Unexpected error:
```
// (6,16): error CS0136: A local or parameter named 'x1' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
//         object x1 = Dummy(null,
Diagnostic(ErrorCode.ERR_LocalIllegallyOverrides, "x1").WithArguments("x1").WithLocation(6, 16),
```

The following test fails:
```
        [Fact]
        public void LocalDeclarationStmt_02()
        {
            var source =
@"
public class X
{
    public static void Main()
    {
        object l1 = Dummy(new object() is var x1),
               x1;

        x1 = null;
        System.Console.WriteLine(x1);
    }

    static object Dummy(object x, params object[] y) {return x;}
}
";
            var compilation = CreateCompilationWithMscorlib45(source, options: TestOptions.DebugExe, parseOptions: patternParseOptions);
            compilation.VerifyDiagnostics(
// (6,47): error CS0136: A local or parameter named 'x1' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
//         object l1 = Dummy(new object() is var x1),
Diagnostic(ErrorCode.ERR_LocalIllegallyOverrides, "x1").WithArguments("x1").WithLocation(6, 47)
                );
```

Unexpected error:
```
// (7,16): error CS0136: A local or parameter named 'x1' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
//                x1;
Diagnostic(ErrorCode.ERR_LocalIllegallyOverrides, "x1").WithArguments("x1").WithLocation(7, 16)
```

Related to #8817.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #9612.
Related to #8817.

@gafter, @jaredpar, @dotnet/roslyn-compiler Please review.
CC @MattGertz For Ask Mode approval.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
test vsi please

**Comment by AlekseyTs** [comment]
CC @davkean This PR targets future-stabilization.

**Comment by MattGertz** [comment]
Meets the bar, pending CRs and tests.

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 1]
```diff
@@ -791,7 +791,20 @@ private TypeSymbol BindVariableType(CSharpSyntaxNode declarationNode, Diagnostic
...
 
             // Check for variable declaration errors.
-            bool hasErrors = this.ValidateDeclarationNameConflictsInScope(localSymbol, diagnostics);
+            Binder nameConflictChecker = this;
+
+            // Step out of the PatternVariableBinder for locals declared in variable declaration statement
+            if (this is PatternVariableBinder)
+            {
+                CSharpSyntaxNode parent;
+                if ((parent = declarator.Parent)?.Kind() == SyntaxKind.VariableDeclaration &&
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: Consider assigning local variable at declaration: ```CSharpSyntaxNode parent = declarator.Parent;```

Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: How could the test in this if statement fail? A local declaration embedded in another statement (e.g. using statement)? Is that what the included test is covering?

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: Sure, I'll follow-up on that in a separate change. Don't want to reset tests because of that.

**Comment by gafter** [comment]
LGTM, assuming I am correct in my assumption that you have tested the code path I questioned above.

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: @gafter This function is called for declaration in many statements: using, for, catch, local declaration, ... My intent is to special case only local declarations. In addition to local declarations , only 'using' statement is tested. However, I believe other statements will share scope between their locals and pattern locals. Local declaration statement is special because regular locals, declared in it, belong to a different scope, by comparison to pattern locals, declared in it. Does this address your concern?

Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: Yes, thank you.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, I need a second sign-off for this stabilization change.

**Comment by cston** [comment]
LGTM
