### PR TITLE
Document handling on unused imports by GetUsedAssemblyReferences API.

### LINKED ISSUE #66188: True-negative in GetUsedAssemblyReferences
**Version Used**: 4.4.0

**Steps to Reproduce**:

Given:

`foo.csproj`:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
  </ItemGroup>

</Project>
```

and `foo.cs`

```csharp
namespace Library
{
    public static class Foo
    {
        public static string Bar() => "Baz";
    }
}
```

Repro requires an analyzer that dumps the output of `GetUsedAssemblyReferences`. An example implementation is in https://github.com/dfederm/ReferenceTrimmer/pull/20/files, the failed test case (where the above repo is taken from) is `dotnet test ReferenceTrimmer.sln --filter UnusedPackageReference`

**Expected Behavior**:

The result of `CSharpCompilation.GetUsedAssemblyReferences` does not contain Newtonsoft.Json.dll reference

**Actual Behavior**:

The result of `CSharpCompilation.GetUsedAssemblyReferences` does contain `<home>\.nuget\packages\newtonsoft.json\13.0.2\lib\net6.0\Newtonsoft.Json.dll`

### PR DESCRIPTION
**Pull request by AlekseyTs**
Closes #66188.

### CODE REVIEW

File: src/Compilers/Core/Portable/Compilation/Compilation.cs [hunk 1]
```diff
@@ -1763,6 +1763,20 @@ bool isContainingAssemblyInReferences(ISymbol s)
...
+        /// 
+        /// The effect of imported namespaces on result of this API depends on whether reporting of
+        /// unused imports is disabled for the compilation. The reporting of unused imports is disabled
+        /// if <see cref="ParseOptions.DocumentationMode"/> is set to <see cref="DocumentationMode.None"/>.
+        /// 
+        /// When unused imports reporting is disabled, all referenced assemblies containing any types
+        /// that belong to imported namespaces are included in the result. I.e. considered used.
+        /// 
+        /// When unused imports reporting is enabled, imported namespaces do not have effect on the result
+        /// of this API. Therefore, removing assembly references that aren't in the result, could potentially
```
Comment (jjonescz) [inline src/Compilers/Core/Portable/Compilation/Compilation.cs:1775]:
```suggestion
        /// of this API. Therefore, removing assembly references that aren't in the result could potentially
```

File: src/Compilers/Core/Portable/Compilation/Compilation.cs [hunk 2]
```diff
@@ -1763,6 +1763,20 @@ bool isContainingAssemblyInReferences(ISymbol s)
         /// within this compilation, the reference is considered to be used. Etc.
         /// The returned set is a subset of references returned by <see cref="References"/> API.
         /// The result is undefined if the compilation contains errors.
+        /// 
+        /// The effect of imported namespaces on result of this API depends on whether reporting of
```
Comment (jjonescz) [inline src/Compilers/Core/Portable/Compilation/Compilation.cs:1767]: Consider moving this to `<remarks>` section and using `<para>...</para>` to denote paragraphs (instead of blank lines).

**Review by jjonescz — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@jcouv, @dotnet/roslyn-compiler For the second review

File: src/Compilers/Core/Portable/Compilation/Compilation.cs [hunk 3]
```diff
@@ -1763,6 +1763,20 @@ bool isContainingAssemblyInReferences(ISymbol s)
...
+        /// unused imports is disabled for the compilation. The reporting of unused imports is disabled
+        /// if <see cref="ParseOptions.DocumentationMode"/> is set to <see cref="DocumentationMode.None"/>.
```
Comment (jcouv) [inline src/Compilers/Core/Portable/Compilation/Compilation.cs:1769]: nit: suggestion:
```suggestion
        /// if <see cref="ParseOptions.DocumentationMode"/> is set to <see cref="DocumentationMode.None"/> (i.e. when documentation is not processed).
```

**Comment by jcouv** [comment]
The subtlety of this API is challenging to explain :-/ I'm curious whether this doc will be accessible enough to avoid the pitfall that some users fell into with this API. Tagging @BillWagner in case any feedback to offer.
I don't think we want to take this compat break, but I still feel that we could safely recommend turning documentation processing on for "best result" (ie. what most users would expect/want).

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 1)

File: src/Compilers/Core/Portable/Compilation/Compilation.cs (hunk 3 above)
Comment (AlekseyTs) [reply src/Compilers/Core/Portable/Compilation/Compilation.cs:1769]: > nit: suggestion

I think ```DocumentationMode.None``` is well documented and I'd rather not duplicate its documentation here.
