### PR TITLE
Permit selecting an instance from a type in a sub-expression in nameof(...)

### LINKED ISSUE #20600: nameof requires a non-static member in a sub-expression
**Version Used**: https://github.com/dotnet/roslyn/commit/5fbdd5c567b854e9b5f6f1ea64944373a40efb26

**Steps to Reproduce**:

```cs
class C
{
    public string Instance;
    public static string Static;
      
    void M()
    {
         _ = nameof(C.Instance);             // OK         
         _ = nameof(C.Instance.Length);      // ERROR
         _ = nameof(C.Static);               // OK  
         _ = nameof(C.Static.Length);        // OK
    }
}

class C<T>
{
    public T Instance;
    public static T Static;
     
    void M()
    {
         _ = nameof(C<string>.Instance);	// OK
	 _ = nameof(C<string>.Instance.Length); // ERROR
         _ = nameof(C<string>.Static);		// OK
         _ = nameof(C<string>.Static.Length);   // OK
    }
}
```

**Expected Behavior**: No error.

**Actual Behavior**:  

`CS0120: An object reference is required for the non-static field, method, or property 'C.Instance'`

### PR DESCRIPTION
**Pull request by gafter**
Fixes #20600

@dotnet/roslyn-compiler May I please have two reviews of this tiny bug fix?

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Just to check, does IntelliSense-Completion do the right thing here?  If not, can we file a bug on it?

File: src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs [hunk 1]
```diff
@@ -1343,5 +1343,51 @@ private static void M(in string value)
...
+        _ = nameof(C<string>.Instance1.Length);
+        _ = nameof(C<string>.Static1);
+        _ = nameof(C<string>.Static1.Length);
+        _ = nameof(C<string>.Instance2);
+        _ = nameof(C<string>.Instance2.Length);
+        _ = nameof(C<string>.Static2);
+        _ = nameof(C<string>.Static2.Length);
+    }
+}
+").VerifyDiagnostics();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs]: >VerifyDiagnostics [](start = 3, length = 17)

I think we should verify expected behavior of the program, not just assert the lack of diagnostics.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs [hunk 2]
```diff
@@ -1343,5 +1343,51 @@ private static void M(in string value)
     }
 }", expectedOutput: "Main");
         }
+
+        [Fact, WorkItem(20600, "https://github.com/dotnet/roslyn/issues/20600")]
+        public void PermitInstanceQualifiedFromType()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs]: >PermitInstanceQualifiedFromType [](start = 20, length = 31)

Please add similar test for VB.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 3]
```diff
@@ -5989,9 +5987,8 @@ private static void CombineExtensionMethodArguments(BoundExpression receiver, An
                 if (!hasError)
                 {
                     var isFixedStatementExpression = SyntaxFacts.IsFixedStatementExpression(node);
-                    var isInsideNameof = this.EnclosingNameofArgument != null;
                     Symbol accessedLocalOrParameterOpt;
-                    if (IsNonMoveableVariable(receiver, out accessedLocalOrParameterOpt) == isFixedStatementExpression && !isInsideNameof)
+                    if (IsNonMoveableVariable(receiver, out accessedLocalOrParameterOpt) == isFixedStatementExpression && !IsInsideNameof)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: >!IsInsideNameof [](start = 122, length = 15)

It looks like this condition is redundant because it is checked by an enclosing ```if```.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1).

File: src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs (hunk 2 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs]: Sure, but unless VB's spec has changed since the LDM meetings (like C#'s spec has changed), these cases will result in an error at compile-time.

**Comment by gafter** [comment]
I would prefer not to encourage people to do things like this. The fact that there is a compiler bug is due to the fact that Mads "simplified" the specification for this feature when folding it into the C# language spec. The final version of the feature spec forbids this.

---
In reply to: [364623066](https://github.com/dotnet/roslyn/pull/24761#issuecomment-364623066) [](ancestors = 364623066)

**Comment by gafter** [comment]
@AlekseyTs I have added an iteration that responds to your comments. Do you have any others?

@dotnet/roslyn-compiler May I please have a second reviewer for this tiny "bug fix"?

File: src/Compilers/VisualBasic/Test/Semantic/Semantics/NameOfTests.vb [hunk 4]
```diff
@@ -3590,5 +3590,49 @@ End Module
...
+            Dim compilationDef =
+                <compilation>
+                    <file name="a.vb">
+Class C
+    Public MyInstance As String
+    Public Shared MyStatic As String
+
+    Sub M()
+        Dim X As String
+        X = NameOf(C.MyInstance)
```
Comment (jcouv) [inline src/Compilers/VisualBasic/Test/Semantic/Semantics/NameOfTests.vb]: Can we verify the values like in C#, for those that are legal?

Comment (gafter) [reply src/Compilers/VisualBasic/Test/Semantic/Semantics/NameOfTests.vb]: This test is only intended to demonstrate which cases are illegal. I believe we already have tests for the string produced by `NameOf`.

**Comment by gafter** [comment]
@jaredpar @jcouv Like my new puppy, I crave approval please.

**Comment by gafter** [comment]
@jaredpar Please approve for integration into 15.7.x.

**Comment by gafter** [comment]
test windows_release_vs-integration_prtest please

**Comment by jcouv** [comment]
@jaredpar may not be online. Approving in his absence.
