### PR TITLE
Extend SpillSequenceSpiller to handle code in a catch filter.

### LINKED ISSUE #45828: MSB6006	"csc.exe" exited with code -2146232797 - Roslyn can't seem to handle a switch expression in an exception filter
**Version Used**: 
Version 16.7.0 Preview 3.1 Enterprise

**Steps to Reproduce**:

When you have the following code (as part of a try-catch block)

```
catch (Exception e) when (e.Message switch
	{
		AConstant => true,
		AnotherConstant => true,
		_ => false
	})
{
	throw new SomeException(e.Message);
}
``` 
you will get the abоve mentioned error when you build it, along with dll files possibly missing if you cleaned up your application.

**Expected Behavior**:

The above code to work as expected.

**Actual Behavior**:

Project fails to compile with an obscure error message. - MSB6006	"csc.exe" exited with code -2146232797

### PR DESCRIPTION
**Pull request by gafter**
Fixes #45828

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a couple of reviews of this compiler crash fix?

File: src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs [hunk 1]
```diff
@@ -4153,6 +4153,208 @@ .maxstack  2
...
+{
+    const string K1 = ""frog"";
+    const string K2 = ""toad"";
+    public static void M(string msg)
+    {
+        try
+        {
+            T(msg);
+        }
+        catch (Exception e) when (e.Message switch
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs:4171]: What are the various expression types which could cause the spiller to come into play. The ones I could recall are:

1. stackalloc as a parameter (think that invokoes the spiller)
1. await 
1. patterns

The first two are illegal in a filter block. Wanted to make sure there wasn't another expression form that uses spills that we should consider testing here.

File: src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs [hunk 2]
```diff
@@ -524,6 +524,27 @@ public override BoundNode VisitYieldReturnStatement(BoundYieldReturnStatement no
...
+            var locals = node.Locals;
+
+            var exceptionFilterPrologueOpt = node.ExceptionFilterPrologueOpt;
+            Debug.Assert(exceptionFilterPrologueOpt is null); // it is introduced by this pass
+            BoundSpillSequenceBuilder builder = null;
+            var exceptionFilterOpt = VisitExpression(ref builder, node.ExceptionFilterOpt);
+            if (builder is { })
+            {
+                Debug.Assert(builder.Value is null);
+                locals = locals.AddRange(builder.GetLocals());
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs:539]: This will put the locals from the `catch` before the filter even though filter executes first. Does that have any impact on the emitted code? Don't believe it does.

**Comment by jcouv** [comment]
>         ///         ex = tmp

It would be useful to update this doc to add the filter prologue

---
Refers to: src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs:896 in e9739aa. [](commit_id = e9739aab993beffaab3dff605d7ad786244a3388, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs [hunk 3]
```diff
@@ -524,6 +524,27 @@ public override BoundNode VisitYieldReturnStatement(BoundYieldReturnStatement no
             return UpdateStatement(builder, node.Update(expression));
         }
 
+        public override BoundNode VisitCatchBlock(BoundCatchBlock node)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs:527]: >BoundCatchBlock [](start = 50, length = 15)

Is it worth reviewing the list of bound nodes to see if any other should be handled by the SpillSequenceSpiller?
Also, I'm wondering how we can help catch this issue as we add new bound nodes in the future. Maybe add a note for spill sequences in test plan, or we could document all the visitors to consider in the codebase?

File: src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.cs [hunk 4]
```diff
@@ -1205,12 +1206,17 @@ private BoundNode RewriteCatch(BoundCatchBlock node, ArrayBuilder<BoundExpressio
             else if (prologue.Count > 0)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.cs:1206]: Are we guaranteed to have `prologue.Count > 0` when an `ExceptionFilterPrologueOpt` exists?

File: src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.cs [hunk 5]
```diff
@@ -1205,12 +1206,17 @@ private BoundNode RewriteCatch(BoundCatchBlock node, ArrayBuilder<BoundExpressio
...
-                    rewrittenFilter.Type);
+                var prologueBuilder = ArrayBuilder<BoundStatement>.GetInstance(prologue.Count);
+                if (rewrittenFilterPrologue != null)
+                {
+                    prologueBuilder.AddRange(rewrittenFilterPrologue.Statements);
+                }
+                foreach (var p in prologue)
+                {
+                    prologueBuilder.Add(new BoundExpressionStatement(p.Syntax, p) { WasCompilerGenerated = true });
+                }
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.cs:1217]: I'm trying to convince myself that this is the right order between prologues, but I'm not sure.

File: src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.cs (hunk 4 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.cs:1206]: No. Those are separate mechanisms for different things. `ExceptionFilterPrologueOpt` is used to evaluate expressions (such as the switch expression) that require statements as part of the evaluation. This prologue sets up the closure frame, e.g. converting a captured local into a field by creating the frame object for the variable.

---
In reply to: [456718544](https://github.com/dotnet/roslyn/pull/46054#discussion_r456718544) [](ancestors = 456718544)

File: src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.cs (hunk 5 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/ClosureConversion/ClosureConversion.cs:1217]: This preserves the order previously in the compiler, it just stores them elsewhere.

A way to see that this order is correct is to recall the purposes of the two kinds of prologues. The one coming in as `rewrittenFilterPrologue` used to be "attached" to the expression so is part of evaluating it, which is why we put it right before the expression. The new prologue sets up a frame for any variables that are captured. Since those variables might be used in the expression and the filter prologue, that has to go first.

Having said that, what I just said doesn't correspond to what the code does. It appears to swap the order (a bug). I'll fix it and add a test showing why the order is important.

---
In reply to: [456718553](https://github.com/dotnet/roslyn/pull/46054#discussion_r456718553) [](ancestors = 456718553)

File: src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs (hunk 3 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs:527]: Yes, good idea. Reviewing all of the constructs that *could* be affected (by finding all the places that a `BoundSpillSequence` is created):
- `await` is forbidden in a catch filter.
- `stackalloc` is forbidden in a catch filter.
- `switch` and complex-enough `is-pattern` operators lower the same way, and are fixed by this PR.
I'm adding a note to the test plan.


---
In reply to: [456718535](https://github.com/dotnet/roslyn/pull/46054#discussion_r456718535) [](ancestors = 456718535)

File: src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs (hunk 2 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs:539]: These locals are all temps created by rewriting code so that statements are at the top level. It doesn't matter much where they go as long as they are surrounding the uses.

There are a number of places in the code that assumes that a catch variable, if there is one, is first in the list of variables. This ensures that remains correct.

---
In reply to: [456699808](https://github.com/dotnet/roslyn/pull/46054#discussion_r456699808) [](ancestors = 456699808)

File: src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs:4171]: That's it, today. I've added a note to the test plan in case there are others in the future.

---
In reply to: [456699320](https://github.com/dotnet/roslyn/pull/46054#discussion_r456699320) [](ancestors = 456699320)
