### PR TITLE
`scoped` should set ref escape scope to current block

### LINKED ISSUE #64009: It looks like ```RefEscapeScope``` is incorrectly calculated for a scoped local inside an explicit block.
```
        [Fact]
        public void LocalScope_04_()
        {
            var source =
@"
{
    scoped s1 = default;
    scoped ref @scoped s6 = ref s1; // 4
}

ref struct @scoped { } // 5
";
            var comp = CreateCompilation(source);
            comp.VerifyDiagnostics();
        }
```

Observed:
```
Microsoft.CodeAnalysis.CSharp.UnitTests.RefFieldTests.LocalScope_04_ [FAIL]
  System.InvalidOperationException : Assertion failed
  Stack Trace:
    src\Compilers\Test\Core\ThrowingTraceListener.cs(26,0): at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage)
       at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage)
       at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage)
       at System.Diagnostics.Debug.Fail(String message, String detailMessage)
       at System.Diagnostics.Debug.Assert(Boolean condition)
    src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs(1106,0): at Microsoft.CodeAnalysis.CSharp.Binder.BindVariableDeclaration(SourceLocalSymbol localSymbol, LocalDeclarationKind kind, Boolean isVar, VariableDeclaratorSyntax declarator, TypeSyntax typeSyntax, TypeWithAnnotations declTypeOpt, AliasSymbol aliasOpt, BindingDiagnosticBag diagnostics, Boolean includeBoundType, CSharpSyntaxNode associatedSyntaxNode)
    src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs(950,0): at Microsoft.CodeAnalysis.CSharp.Binder.BindVariableDeclaration(LocalDeclarationKind kind, Boolean isVar, VariableDeclaratorSyntax declarator, TypeSyntax typeSyntax, TypeWithAnnotations declTypeOpt, AliasSymbol aliasOpt, BindingDiagnosticBag diagnostics, Boolean includeBoundType, CSharpSyntaxNode associatedSyntaxNode)
```
 
The following assert fires:
```
                    Debug.Assert(localSymbol.RefKind == RefKind.None ||
                        localSymbol.RefEscapeScope >= GetRefEscape(initializerOpt, LocalScopeDepth));
```

It looks like ```RefEscapeScope``` is incorrectly calculated for a scoped local inside an explicit block.

### PR DESCRIPTION
**Pull request by cston**
`scoped` should set ref escape scope to the current block rather than the current method.

Fixes #64009.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceLocalSymbol.cs [hunk 1]
```diff
@@ -32,6 +32,7 @@ internal class SourceLocalSymbol : LocalSymbol
         private readonly RefKind _refKind;
         private readonly LocalDeclarationKind _declarationKind;
         private readonly DeclarationScope _scope;
+        private readonly uint _localScopeDepth;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceLocalSymbol.cs:36]: It doesn't look like we need to store this value, we have ```_scopeBinder``` readily available

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 2]
```diff
@@ -9115,6 +9115,107 @@ static void Test(ref int x)
...
+{
+    public S(ref int i) { }
+}
+";
+            var comp = CreateCompilation(source);
+            comp.VerifyDiagnostics();
+        }
+
+        [Fact]
+        public void LocalScope_11()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:9152]: >LocalScope_11 [](http://example.com/codeflow?start=20&length=13)

Does use of `scoped` make any difference for this scenario? It would be good to add tests demonstrating the difference.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 2)

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 4)

**Comment by cston** [comment]
@dotnet/roslyn-compiler please review, thanks.

**Review by RikkiGibson — APPROVED** [review]
