### PR TITLE
Fix test results publishing

### LINKED ISSUE #49697: Test results are not published for Linux and Mac runs
Before #49452: https://dev.azure.com/dnceng/public/_build/results?buildId=898232&view=results
After: https://dev.azure.com/dnceng/public/_build/results?buildId=898307&view=results

Note the warnings as well as the 110,000 missing tests in the "After" run :)

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #49697

Moves the logic from powershell/bash scripts into RunTests.

### CODE REVIEW

File: src/Tools/Source/RunTests/Options.cs [hunk 1]
```diff
@@ -185,7 +185,7 @@ internal class Options
                 Console.WriteLine($"Did not find artifacts directory at {artifactsPath}");
                 return null;
             }
-            resultFileDirectory ??= Path.Combine(artifactsPath, "TestResults");
+            resultFileDirectory ??= Path.Combine(artifactsPath, configuration, "TestResults");
```
Comment (JoeRobich) [inline src/Tools/Source/RunTests/Options.cs:188]: Should the configuration come last?

```suggestion
            resultFileDirectory ??= Path.Combine(artifactsPath, "TestResults", configuration);
```

**Comment by RikkiGibson** [comment]
Total number of tests went from 747292 on Nov 24th (before the remove restore/checkout PR) to 740755 on Dec 1st (in this PR). I don't know why there's that much of a discrepancy.

**Review by jaredpar — APPROVED** [review]
