### PR TITLE
Show expression completion within casts

### LINKED ISSUE #717: Completion list doesn't show locals in a broken code scenario with automatic brace completion.
Ported from TFS WorkItem: **707201**

------------------------------

**Repro Steps:**

REPRO:

1.&nbsp; Paste into a C# editor:

class Program<BR>{<BR>&nbsp;&nbsp;&nbsp; void M()<BR>&nbsp;&nbsp;&nbsp; {<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; for (int i = 0; i &lt; 5; i++)<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; var x = $$<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; var y = 1;<BR>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }<BR>&nbsp;&nbsp;&nbsp; }<BR>}

2.&nbsp; Place the cursor at '$$' and type "(i".&nbsp; Notice that the right paren is auto-completed.

&nbsp;

RESULT:

The identifier 'i' is not listed in the completion list.

&nbsp;

EXPECTED:

'i' should be listed.

------------------------------

**Revisions:**

1) Created By Brett Forsgren (5/30/2013 6:02:15 PM)

------------------------------

2) Edited By Dustin Campbell (5/31/2013 9:41:17 AM)

The problem is that automatic brace completion causes the parser to assume this is a cast and not an expression context. This same behavior will now exist in Dev12.

------------------------------

3) Edited By Tanner Gooding (Chinasoft International) (4/10/2014 1:46:19 PM)

Still reproing in VSPro_Platform build 21609.00

------------------------------

4) Edited By Kevin Pilch-Bisson (6/12/2014 9:39:04 AM)

Note - we also heard about this from dogfooders during Dev12 when we added brace completion to the product.&nbsp; We should add a syntactic check for this case and show more than just types.

&nbsp;

(See linked bug too).

------------------------------

5) Edited By Ravi Chande (2/13/2015 3:12:55 PM)

Repros.

------------------------------

6) Edited By Kevin Pilch-Bisson (2/19/2015 2:04:24 PM)

Yep, please port to GitHub.&nbsp; We'd like to try and do something here&nbsp;- it may be that we need to NOT filter to types only inside cast expressions because of these ambiguities.

------------------------------

### PR DESCRIPTION
**Pull request by rchande**
Automatic brace completion of "(" parses as a cast, but the user might
be trying to type a parenthesized expression.

Fixes #717

### CODE REVIEW

File: src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationService.cs [hunk 1]
```diff
@@ -75,7 +75,9 @@ internal class CSharpRecommendationService : AbstractRecommendationService
                 // Script and interactive
                 return GetSymbolsForGlobalStatementContext(context, cancellationToken);
             }
-            else if (context.IsAnyExpressionContext || context.IsStatementContext)
+            else if (context.IsAnyExpressionContext || 
+                     context.IsStatementContext || 
+                     context.SyntaxTree.IsDefiniteCastTypeContext(context.Position, context.LeftToken, cancellationToken))
```
Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationService.cs]: Add a comment?  `IsDefiniteCastTypeContext` might make people wonder why it is there.

**Comment by Pilchie** [comment]
:+1:

File: src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationService.cs [hunk 2]
```diff
@@ -75,8 +75,13 @@ internal class CSharpRecommendationService : AbstractRecommendationService
...
             {
+                // GitHub #717: With automatic brace completion active, typing '(' produces "()", which gets parsed as
+                // as cast. The user might be trying to type a parenthesized expression, so even though a cast
+                // is a type-only context, we'll show all symbols anyway.
```
Comment (dpoeschl) [inline src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationService.cs]: In the case from the bug:
```C#
        for (int i = 0; i< 5; i++)
        {
            var x = ()
            var y = 1;
        }
```
The "()" is parsed as a parenthesized expression, but when the first character is inserted inside the parentheses it then switches to a CastExpression.

I think "i" would have been in the list inside the parentheses if completion was invoked explicitly, but not once a character (the "i") is actually typed.

This is a problem with the comment but also with the unit test that was added. Can you also add another unit test for the case when the i is already in the parentheses?

Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationService.cs]: Don't our tests verify both the empty case and the just typed something case?

Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationService.cs]: Nope, we don't seem to.

**Comment by rchande** [comment]
@dpoeschl @Pilchie The test harness verifies the item is there when it's partially typed:

http://source.roslyn.io/#Roslyn.Services.Editor.CSharp.UnitTests/Completion/CompletionProviders/AbstractCSharpCompletionProviderTests.cs,7c0487dddc11f0f0,references

**Comment by Pilchie** [comment]
Ah, missed that override of `VerifyWorker`. Thanks.  As @dpoeschl points out, you should probably update the comment though.

**Comment by dpoeschl** [comment]
Yep, I missed that too. This makes the test hard enough to read that I wonder if `VerifyWorker` should be renamed to `VerifyAllCompletionScenarios` or something that makes the reader aware it's not just verifying the one exact case shown in the markup.
