### PR TITLE
Fix partial method doc comments

### LINKED ISSUE #54103: CS1591: Redundant comments are required in all partial method definitions
### Analyzer

**Diagnostic ID**: [CS1591](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1591): `Missing XML comment for publicly visible type or member`

### Analyzer source

**Version**: [SDK 5.0.100](https://dotnet.microsoft.com/download/dotnet/5.0)

### Describe the bug

The public partial method in the public partial class requires XML comments in each partial method definition. The class itself requires the documentation only in one place.

### Steps To Reproduce

Prerequisite: XML comments are enabled.

1. Define the public partial method without implementation inside a public partial class.
2. In another file: Define the same public partial class with the same public partial method, but now with implementation.
3. Add XML comment to only one file where the partial method is defined.
4. CS1591 will pop up on the other file, it does not matter in which file the XML comment was created.

### Expected behavior

It would be enough to create only one XML comment on the partial method, the same as with the partial class.

### Actual behavior

In order to dismiss CS1591, the partial method has to be documented everywhere or use suppresion.

## Additional context

Example:

Without CS1591
image
Second file with CS1591 on partial method
image

### PR DESCRIPTION
**Pull request by RikkiGibson**
Fixes #54103.

The specific rule changes implemented in this PR are laid out in dotnet/csharplang#5193.

Have added tests to ensure that the expected documentation is shown in Quick Info.

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs [hunk 1]
```diff
@@ -1140,6 +1140,70 @@ static class Test { static void Method() { int a = MyStruct.Some$$Field; } }";
...
+    public partial void MyMethod()
+    {
+    }
+}
+static class Test { static void Method() { MyClass.My$$Method(); } }";
+
+            await TestAsync(markup,
+                MainDescription($"void MyClass.MyMethod()"),
+                Documentation("My Method Implementation"));
+        }
```
Comment (jcouv) [inline src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs:1205]: Consider also testing the case with definition (with xml doc) but no implementation.

File: src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.cs [hunk 2]
```diff
@@ -276,7 +293,10 @@ public override void DefaultVisit(Symbol symbol)
             // If there are no doc comments, then no further work is required (other than to report a diagnostic if one is required).
             if (docCommentNodes.IsEmpty)
             {
-                if (maxDocumentationMode >= DocumentationMode.Diagnose && RequiresDocumentationComment(symbol))
+                if (maxDocumentationMode >= DocumentationMode.Diagnose
+                    && RequiresDocumentationComment(symbol)
+                    && !symbol.IsPartialImplementation()
+                    && !shouldSkipPartialDefinitionComments)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.cs:299]: Does this line matter? It looks like `!symbol.IsPartialImplementation()` implies `!shouldSkipPartialDefinitionComments`

File: src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs [hunk 3]
```diff
@@ -949,38 +965,288 @@ partial class C
...
+";
+
+            var source2 = @"
+public partial class C
+{
+    public partial int M();
+}
+";
+
+            var tree1 = SyntaxFactory.ParseSyntaxTree(source1, options: TestOptions.RegularWithDocumentationComments);
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs:1112]: nit: do the tests need to do this parsing step explicitly? Doesn't a regular call to `CreateCompilation` work (with correct parse options given)?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs:1112]: They do not need to. The existing tests do it, so when copying+modifying the existing test, it was less work to leave it this way :)

File: src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs [hunk 4]
```diff
@@ -949,38 +965,288 @@ partial class C
...
+
+        [Fact]
+        public void ExtendedPartialMethods_MultipleFiles_ImplementationComment()
+        {
+            var source1 = @"
+/// <summary>Summary 0</summary>
+public partial class C
+{
+    /** <summary>Summary 1</summary>*/
+    public partial int M() => 42;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs:1051]: >public partial int M() => 42; [](http://example.com/codeflow?start=4&length=29)

What is the behavior when there are paramref tags in the documentation and parameter names do not match between declaration and implementation? Will emitted method signature match the produced documentation?

File: src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.cs [hunk 5]
```diff
@@ -252,13 +252,30 @@ public override void DefaultVisit(Symbol symbol)
...
             }
 
-            bool isPartialMethodDefinitionPart = symbol.IsPartialDefinition(); // CONSIDER: ignore this if isForSingleSymbol?
-            if (isPartialMethodDefinitionPart)
+            bool shouldSkipPartialDefinitionComments = false;
+            if (symbol.IsPartialDefinition())
             {
-                MethodSymbol implementationPart = ((MethodSymbol)symbol).PartialImplementationPart;
-                if ((object)implementationPart != null)
+                if (symbol is not MethodSymbol { PartialImplementationPart: MethodSymbol implementationPart })
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.cs:258]: >is not [](http://example.com/codeflow?start=27&length=6)

I think the code will be easier to follow if negation is removed and branches are swapped.

File: src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.cs:299]: I think `symbol.IsPartialImplementation()` implies `!shouldSkipPartialDefinitionComments`.

In absence of the `!shouldSkipPartialDefinitionComments`, we give a warning in `ExtendedPartialMethods_MultipleFiles_ImplementationComment`.

In absence of the `!symbol.IsPartialImplementation()`, we give a warning in `ExtendedPartialMethods_MultipleFiles_DefinitionComment`, and give an extra warning (which is perhaps harmless) in `ExtendedPartialMethods_MultipleFiles_NoComment`.

The rule here is to never warn about absence of a doc comment on a partial method implementation, and to suppress a missing doc comment warning on a partial definition if we are not intending to output it anyway. Maybe I should add a comment.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 4)

File: src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs:1051]: I'll add some tests for this when I get the chance. If the existing behavior that we observe once tests are in place seems particularly bad, we can consider adjusting it.

File: src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.cs (hunk 5 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Compiler/DocumentationCommentCompiler.cs]: Fixed.

File: src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs:1051]: The behavior I observed is that warnings are given based off the particular declaration whose doc comments we are processing. However, the partial declaration parameter names always "win" in terms of metadata. [SharpLab](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoBBmABABwgCcAXKCAG12VwGFcBvTXF6vQ08qhAFlwFkUAClglcADxQBKANzNWOAsTKVqfQSJhjxSKY1wBfTEYxA==). Potentially, we should consider making it so when we check the validity of 'paramrefs' of a partial implementation, we look to the partial declaration instead for the parameter names.

Partial method parameter name differences are currently a warning, FWIW.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs:1051]: > Partial method parameter name differences are currently a warning, FWIW.

I do not see any warnings for the following code:
```
partial class Test
{
    partial void M(int x); 
}

partial class Test
{
    partial void M(int y){} 
}
```

File: src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs [hunk 6]
```diff
@@ -949,38 +965,521 @@ partial class C
...
+            void verify(CSharpTestSource source)
+            {
+                var compilation = CreateCompilation(source, assemblyName: "Test");
+                compilation.VerifyDiagnostics(
+                    // (5,24): warning CS8826: Partial method declarations 'int C.M(int p2)' and 'int C.M(int p1)' have signature differences.
+                    //     public partial int M(int p1) => 42;
+                    Diagnostic(ErrorCode.WRN_PartialMethodTypeDifference, "M").WithArguments("int C.M(int p2)", "int C.M(int p1)").WithLocation(5, 24));
+
+                var method = compilation.GetMember<MethodSymbol>("C.M");
+                Assert.Equal("p2", method.Parameters.Single().Name);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs:1288]: >Assert.Equal("p2", method.Parameters.Single().Name); [](http://example.com/codeflow?start=16&length=52)

I assume this assert is to verify what name is emitted. Rather than relying on the knowledge what will be emitted, we should verify what is emitted (CompileAnVerify + symbolVerifier).

File: src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs [hunk 7]
```diff
@@ -949,38 +965,521 @@ partial class C
...
+                compilation.VerifyDiagnostics(
+                    // (4,42): warning CS1734: XML comment on 'C.M(int)' has a paramref tag for 'p2', but there is no parameter by that name
+                    //     /** <summary>Accepts <paramref name="p2"/>.</summary> */
+                    Diagnostic(ErrorCode.WRN_UnmatchedParamRefTag, "p2").WithArguments("p2", "C.M(int)").WithLocation(4, 42),
+                    // (5,24): warning CS8826: Partial method declarations 'int C.M(int p2)' and 'int C.M(int p1)' have signature differences.
+                    //     public partial int M(int p1) => 42;
+                    Diagnostic(ErrorCode.WRN_PartialMethodTypeDifference, "M").WithArguments("int C.M(int p2)", "int C.M(int p1)").WithLocation(5, 24));
+
+                var method = compilation.GetMember<MethodSymbol>("C.M");
+                Assert.Equal("p2", method.Parameters.Single().Name);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs:1346]: >Assert.Equal("p2", method.Parameters.Single().Name); [](http://example.com/codeflow?start=16&length=52)

Same comment

File: src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs [hunk 8]
```diff
@@ -949,38 +965,521 @@ partial class C
...
+                compilation.VerifyDiagnostics(
+                    // (4,24): warning CS8826: Partial method declarations 'int C.M(int p2)' and 'int C.M(int p1)' have signature differences.
+                    //     public partial int M(int p1) => 42;
+                    Diagnostic(ErrorCode.WRN_PartialMethodTypeDifference, "M").WithArguments("int C.M(int p2)", "int C.M(int p1)").WithLocation(4, 24),
+                    // (4,42): warning CS1734: XML comment on 'C.M(int)' has a paramref tag for 'p1', but there is no parameter by that name
+                    //     /** <summary>Accepts <paramref name="p1"/>.</summary> */
+                    Diagnostic(ErrorCode.WRN_UnmatchedParamRefTag, "p1").WithArguments("p1", "C.M(int)").WithLocation(4, 42));
+
+                var method = compilation.GetMember<MethodSymbol>("C.M");
+                Assert.Equal("p2", method.Parameters.Single().Name);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs:1407]: >ssert.Equal("p2", method.Parameters.Single().Name); [](http://example.com/codeflow?start=17&length=51)

Same comment

File: src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs [hunk 9]
```diff
@@ -949,38 +965,521 @@ partial class C
...
+            void verify(CSharpTestSource source)
+            {
+                var compilation = CreateCompilation(source, assemblyName: "Test");
+                compilation.VerifyDiagnostics(
+                    // (4,24): warning CS8826: Partial method declarations 'int C.M(int p2)' and 'int C.M(int p1)' have signature differences.
+                    //     public partial int M(int p1) => 42;
+                    Diagnostic(ErrorCode.WRN_PartialMethodTypeDifference, "M").WithArguments("int C.M(int p2)", "int C.M(int p1)").WithLocation(4, 24));
+
+                var method = compilation.GetMember<MethodSymbol>("C.M");
+                Assert.Equal("p2", method.Parameters.Single().Name);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs:1465]: > Assert.Equal("p2", method.Parameters.Single().Name); [](http://example.com/codeflow?start=15&length=53)

Same comment

**Comment by AlekseyTs** [comment]
Done with review pass (commit 6)

File: src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/DocumentationComments/DocumentationCommentCompilerTests.cs:1051]: It's limited to a recent warning wave. You can observe the warning in e.g. `PartialMethod_Paramref_02`.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 7)

File: src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs:1205]: Have added the test, thanks.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 7)

**Comment by RikkiGibson** [comment]
Do we need sign off from @dotnet/roslyn-ide for new tests in the IDE area?

**Comment by jcouv** [comment]
Yes, we should get a review for the few added IDE tests.

File: src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs [hunk 10]
```diff
@@ -1140,6 +1140,87 @@ static class Test { static void Method() { int a = MyStruct.Some$$Field; } }";
...
+
+        [WorkItem(538638, "http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/538638")]
+        [Fact, Trait(Traits.Feature, Traits.Features.QuickInfo)]
+        public async Task TestPartialMethodDocComment_04()
+        {
+            var markup =
+@"partial class MyClass
+{
+    ///<summary>My Method Definition</summary>
+    public partial void MyMethod();
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs:1215]: can you add one more test where there is only an impl, but no def.

File: src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs [hunk 11]
```diff
@@ -1140,6 +1140,87 @@ static class Test { static void Method() { int a = MyStruct.Some$$Field; } }";
...
 
+        [WorkItem(538638, "http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/538638")]
+        [Fact, Trait(Traits.Feature, Traits.Features.QuickInfo)]
+        public async Task TestPartialMethodDocComment_01()
+        {
+            var markup =
+@"partial class MyClass
+{
+    ///<summary>My Method Definition</summary>
+    public partial void MyMethod();
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs:1151]: any concern that all thse tests test the public case?  i know ublic partials are different from nonpublic ones.  would testing that be useful?  or is all the same to the compiler?

File: src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs (hunk 10 above)
Comment (RikkiGibson) [reply src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs:1215]: Sure thing.

File: src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs (hunk 11 above)
Comment (RikkiGibson) [reply src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs:1151]: > or is all the same to the compiler?

I think it is, but I added one test where the partial method has no access modifiers for good measure.
