### PR TITLE
Fix race condition in analyzer driver for computing nodes to analyze …

### LINKED ISSUE #63225: Flaky Analyzers on latest .NET preview
## Describe the bug
Analyzers don't get reported correctly on the latest preview of .NET.
In VS there are cases where the analyzers don't get reported at all, or get reported twice. Whenever I run `dotnet build` on powershell however, the analyzers are all reported correctly.
There were also instances where I would add white space and the analyzers would no longer be reported.

## Steps To Repro
Add the following code to a sample Minimal API Program.cs:
```C#
builder.WebHost.UseStartup(typeof(Startup));

app.MapGet("/hello/{name?}", (string name) => $"Hello {name}");

builder.Host.ConfigureLogging(logging =>
{
    logging.AddConsole();
});

for (var i = 0; i < 100; i++)
{
    _ = stackalloc byte[1];
}

public class Startup { }
```
This should fire 4 analyzers

- ASP0010
- ASP0011
- ASP0007
- CA2014

I have seen cases each analyzer is reported twice in VS, or not reported at all. They are always reported correctly on the CLI, suggesting this is a VS issue.

## .NET version
7.0.100-preview.7.22376.2

## Anything Else
Example where analyzers are reported twice:
image

Example where analyzers are not reported at all:
image

### PR DESCRIPTION
**Pull request by mavasani**
…for top-level statements

Fixes #63225

We cache the syntax nodes to analyze within a given symbol's declaration in the analyzer driver for partial analysis case (when the analyzer host requests diagnostics for a file with an optional span). The key for this cache was the declaring syntax reference, which works fine in all cases except for top-level statements where the implicitly generated entry point method symbol and the entry point type symbol share the same declaration node and hence end up sharing the same key. This change fixes this issue by instead using the symbol and the declaration index as the key for the cache.

Verified that repro scenario in #63225 is consistently working fine after this fix. The missing/duplicate diagnostics in the repro was reproducing pretty consistently prior to the fix.

### CODE REVIEW

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.CompilationData.cs [hunk 1]
```diff
@@ -13,22 +13,24 @@ internal abstract partial class AnalyzerDriver : IDisposable
     {
         internal class CompilationData
         {
-            private readonly Dictionary<SyntaxReference, DeclarationAnalysisData> _declarationAnalysisDataMap;
+            private readonly record struct SyntaxReferenceAndSymbol(SyntaxReference Declaration, ISymbol Symbol);
+            private readonly Dictionary<(ISymbol, int), DeclarationAnalysisData> _declarationAnalysisDataMap;
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.CompilationData.cs:17]: 1. what's the lifetime of hte datamap?  i ask as symbols will root the entire compilation, which is a bit concerning.
2. names for the tuple items (esp. the int).

**Review by CyrusNajmabadi — APPROVED** [review]
tentative approval :)

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.CompilationData.cs (hunk 1 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.CompilationData.cs:17]: > what's the lifetime of hte datamap?

it’s strongly held by CompilationWithAnalyzers, so matches its lifetime, which is controlled by each analyzer host

> names for the tuple items (esp. the int).

Sure

Comment (CyrusNajmabadi) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.CompilationData.cs:17]: > it’s strongly held by CompilationWithAnalyzers:

Ok great.  can you add a comment to that effect?  thanks!  sign-off stands.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.CompilationData.cs [hunk 2]
```diff
@@ -13,22 +13,24 @@ internal abstract partial class AnalyzerDriver : IDisposable
     {
         internal class CompilationData
         {
-            private readonly Dictionary<SyntaxReference, DeclarationAnalysisData> _declarationAnalysisDataMap;
+            private readonly record struct SyntaxReferenceAndSymbol(SyntaxReference Declaration, ISymbol Symbol);
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.CompilationData.cs:16]: >SyntaxReferenceAndSymbol [](http://example.com/codeflow?start=43&length=24)

Is this new type used?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.CompilationData.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.CompilationData.cs:17]: >(ISymbol, int) [](http://example.com/codeflow?start=40&length=14)

Consider providing names for the properties to make their purpose clear.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.CompilationData.cs (hunk 2 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.CompilationData.cs:16]: Ah thanks, I switched to triple later. Will delete.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.CompilationData.cs (hunk 1 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.CompilationData.cs:17]: Sure, thanks

**Comment by AlekseyTs** [comment]
Done with review pass (commit 1)

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 2)

**Comment by mavasani** [comment]
@dotnet/roslyn-compiler for second review.

**Review by cston — APPROVED** [review]

**Comment by mavasani** [comment]
Thanks!
