### PR TITLE
Fix crash in ref escape around missing this param

### LINKED ISSUE #63384: "csc.exe" exited with code -2146232797, crash in MethodSymbol.get_ThisParameter()
**Version Used**: VS 17.3, toolset 4.4.0-2.22412.12

**Steps to Reproduce**:

1. Clone https://github.com/Sergio0694/ComputeSharp
2. Checkout to `dev/csharp-11`, https://github.com/Sergio0694/ComputeSharp/commit/ecb371c1603cc0d90748de22bfd6b90a9c19ef01
3. Build ComputeSharp (`dotnet build src/ComputeSharp/ComputeSharp.csproj`)

**Expected Behavior**:

Should probably fail to build (bumped to C# 11 but I haven't fixed all things just yet), but in a proper way. 

**Actual Behavior**:

csc just dies:

> "csc.exe" exited with code -2146232797

**Stack trace (from cmd build)**:

I'm seeing `Microsoft.CodeAnalysis.CSharp.Binder.<GetInvocationArgumentsForEscape>g__getReceiver` and a bunch of other ref-escape-related method names in the stack trace, so I'd imagine this is due to some of the new code for the ref-escape rules (cc. @cston).

Full `dotnet build` log: https://gist.github.com/Sergio0694/bbf5e9cef1263c2315a599d578eb154e.

### PR DESCRIPTION
**Pull request by jaredpar**
Not all symbols support a `this` parameter in our symbol model. The
`ref` escapes code needs to account for this and use
`TryGetThisParameter`.

closes #63384

### CODE REVIEW

**Comment by jaredpar** [comment]
@dotnet/roslyn-compiler PTAL

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs [hunk 1]
```diff
@@ -4058,5 +4058,22 @@ class D
...
 ", parseOptions: TestOptions.Regular.WithLanguageVersion(languageVersion), options: TestOptions.ReleaseDll).VerifyDiagnostics();
         }
+
+        [WorkItem(63384, "https://github.com/dotnet/roslyn/issues/63384")]
+        [Theory]
+        [InlineData("nuint")]
+        [InlineData("nint")]
+        public void NativeIntegerThis(string type)
+        {
+            var compilation = CreateCompilationWithMscorlibAndSpan(
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs:4068]: Minor: Consider using `CreateCompilation`.

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 2]
```diff
@@ -1796,8 +1796,16 @@ bool isRefEscape
                     PropertySymbol p => p.GetMethod ?? p.SetMethod,
                     _ => throw ExceptionUtilities.UnexpectedValue(symbol)
                 };
-                var thisParameter = method?.ThisParameter;
-                var refKind = thisParameter?.RefKind ?? RefKind.None;
+
+                var refKind = RefKind.None;
+                ParameterSymbol? thisParameter = null;
+                if (method is not null &&
+                    method.TryGetThisParameter(out thisParameter) &&
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1803]: >TryGetThisParameter [](http://example.com/codeflow?start=27&length=19)

This change seems like a necessary change, but should we also add an implementation of `TryGetThisParameter()` to `NativeIntegerMethodSymbol`?

Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1803]: I'm unsure if we should or not. The documentation on the method doesn't give a lot of insight into when it should or should not be implemented. Looking through other implementations it was hard to discern a good meaning either.

**Review by RikkiGibson — APPROVED** [review]

**Comment by jaredpar** [comment]
Spanish failure is unrelated
