### PR TITLE
Fixes #18556 - Invalid code when implementing interface through explicitly-implemented property

### LINKED ISSUE #18556: Invalid code generated when implementing interface through explicitly implemented property
**Version Used**: 
VS 2017 Update 1 and master 85ca862c20fd1cb4192f3a42521eeadcba6828cb

**Steps to Reproduce**:

1. Create a new project with the following:
```
interface IA
{
    IB B { get; }
}
interface IB
{
    int M();
}
class AB : IA, IB
{
    IB IA.B => null;
}
```
2. Put caret in `class AB : IA, IB` line and invoke `Implement interface through 'IA.B'`

**Expected Behavior**:
```
public int M()
{
    return ((IA)this).B.M();
}
```

**Actual Behavior**:
Invalid code (CS0120):
```
public int M()
{
    return IA.B.M();
}
```

### PR DESCRIPTION
**Pull request by kcnygaard**

### CODE REVIEW

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs [hunk 1]
```diff
@@ -476,13 +476,36 @@ private SyntaxNode CreateThroughExpression(SyntaxGenerator factory)
                     // uncommon case and optimize for the common one - in other words, we only apply the cast
                     // in cases where we can unambiguously figure out which interface we are trying to implement.
                     var interfaceBeingImplemented = State.InterfaceTypes.SingleOrDefault();
-                    if ((interfaceBeingImplemented != null) && (!throughMemberType.Equals(interfaceBeingImplemented)))
+                    if ((interfaceBeingImplemented != null))
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs]: remove unnecessary parens.

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs [hunk 2]
```diff
@@ -476,13 +476,36 @@ private SyntaxNode CreateThroughExpression(SyntaxGenerator factory)
...
                     {
-                        through = factory.CastExpression(interfaceBeingImplemented,
-                            through.WithAdditionalAnnotations(Simplifier.Annotation));
+                        if (!throughMemberType.Equals(interfaceBeingImplemented))
+                        {
+                            through = factory.CastExpression(interfaceBeingImplemented,
+                                through.WithAdditionalAnnotations(Simplifier.Annotation));
+
+                            var facts = this.Document.GetLanguageService<ISyntaxFactsService>();
+                            through = facts.Parenthesize(through);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs]: you can just use factory.ParenthesizedExpression.  No need for the syntaxFactsService.

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs [hunk 3]
```diff
@@ -476,13 +476,36 @@ private SyntaxNode CreateThroughExpression(SyntaxGenerator factory)
...
                     var interfaceBeingImplemented = State.InterfaceTypes.SingleOrDefault();
-                    if ((interfaceBeingImplemented != null) && (!throughMemberType.Equals(interfaceBeingImplemented)))
+                    if ((interfaceBeingImplemented != null))
                     {
-                        through = factory.CastExpression(interfaceBeingImplemented,
-                            through.WithAdditionalAnnotations(Simplifier.Annotation));
+                        if (!throughMemberType.Equals(interfaceBeingImplemented))
+                        {
+                            through = factory.CastExpression(interfaceBeingImplemented,
+                                through.WithAdditionalAnnotations(Simplifier.Annotation));
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs]: wow, this actually works?  The simplifier simplifies ```((IA)this).M()``` to "this.M()``` when it can?

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs [hunk 4]
```diff
@@ -476,13 +476,36 @@ private SyntaxNode CreateThroughExpression(SyntaxGenerator factory)
...
+
+                            var facts = this.Document.GetLanguageService<ISyntaxFactsService>();
+                            through = facts.Parenthesize(through);
+                        }
+                        else if (!ThroughMember.IsStatic && ThroughMember is IPropertySymbol throughMemberProperty && throughMemberProperty.ExplicitInterfaceImplementations.Any())
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs]: wrap lines longer than what github supports.

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs [hunk 5]
```diff
@@ -476,13 +476,36 @@ private SyntaxNode CreateThroughExpression(SyntaxGenerator factory)
...
+                                explicitlyImplementedProperty.ContainingType,
+                                factory.ThisExpression());
+
+                            var facts = this.Document.GetLanguageService<ISyntaxFactsService>();
+                            explicitImplementationCast = facts.Parenthesize(explicitImplementationCast);
+
+                            through = factory.MemberAccessExpression(explicitImplementationCast,
+                                factory.IdentifierName(explicitlyImplementedProperty.Name))
+                                .WithAdditionalAnnotations(Simplifier.Annotation);
+
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs]: extra newline.

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs [hunk 6]
```diff
@@ -476,13 +476,36 @@ private SyntaxNode CreateThroughExpression(SyntaxGenerator factory)
...
+                            //
+                            var explicitlyImplementedProperty = throughMemberProperty.ExplicitInterfaceImplementations[0];
 
-                        var facts = this.Document.GetLanguageService<ISyntaxFactsService>();
-                        through = facts.Parenthesize(through);
+                            var explicitImplementationCast = factory.CastExpression(
+                                explicitlyImplementedProperty.ContainingType,
+                                factory.ThisExpression());
+
+                            var facts = this.Document.GetLanguageService<ISyntaxFactsService>();
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs]: syntaxfacts not necessary.

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs (hunk 4 above)
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs]: it seems like you only solved the issue for properties.  what about indexers, methods and events?

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs (hunk 1 above)
Comment (kcnygaard) [inline src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs]: 👍

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs (hunk 2 above)
Comment (kcnygaard) [inline src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs]: `factory` is actually an instance of `SyntaxGenerator` not `SyntaxFactory`, which does not have a `ParenthesizedExpression` method.  I've renamed the local to clear up the confusion.  Is using facts service OK in that case?

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs (hunk 3 above)
Comment (kcnygaard) [inline src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs]: Since this code [was already here](https://github.com/dotnet/roslyn/blob/85ca862c20fd1cb4192f3a42521eeadcba6828cb/src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs#L482), yes, I believe it works. :)  My understanding is it simplifies things like `(global::IA)` to `(IA)`.

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs (hunk 5 above)
Comment (kcnygaard) [inline src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs]: :+1:

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs (hunk 6 above)
Comment (kcnygaard) [inline src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs]: Same comment as above.

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs (hunk 4 above)
Comment (kcnygaard) [inline src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs]: Unless I'm mistaken, the code action is only suggested on on fields and properties (see [here](https://github.com/dotnet/roslyn/blob/85ca862c20fd1cb4192f3a42521eeadcba6828cb/src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.cs#L91)) and therefore indexers, methods and events do not apply (this is the _implement-through_ member, not the _implemented_ member).

**Comment by kcnygaard** [comment]
@CyrusNajmabadi thanks for the review!  Updated per feedback with some comments.

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs (hunk 6 above)
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs]: it really shoudn't be necessary.  factory.MemberAccessExpression should parenthesize the left side of the dot.  see: 
https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs#L3561

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs (hunk 4 above)
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs]: ah, gotcha!

**Comment by CyrusNajmabadi** [comment]
I will rereview shortly!

**Comment by CyrusNajmabadi** [comment]
I sitll don't think you need the explicit requests to Parenthesize.

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs (hunk 6 above)
Comment (kcnygaard) [inline src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs]: You're right.  I've removed it.

**Comment by kcnygaard** [comment]
Updated and rebased to fix commit messages... (oops)

**Comment by kcnygaard** [comment]
@CyrusNajmabadi Thanks again for the review.  Let me know if there's anything else you'd like me to do.

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs [hunk 7]
```diff
@@ -476,13 +476,36 @@ private SyntaxNode CreateThroughExpression(SyntaxGenerator factory)
...
                     {
-                        through = factory.CastExpression(interfaceBeingImplemented,
-                            through.WithAdditionalAnnotations(Simplifier.Annotation));
+                        if (!throughMemberType.Equals(interfaceBeingImplemented))
+                        {
+                            through = generator.CastExpression(interfaceBeingImplemented,
+                                through.WithAdditionalAnnotations(Simplifier.Annotation));
+
+                            var facts = this.Document.GetLanguageService<ISyntaxFactsService>();
+                            through = facts.Parenthesize(through);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs]: as mentioned before, i still dont' see why you need to explicitly parenthesize.

File: src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs [hunk 8]
```diff
@@ -476,13 +476,36 @@ private SyntaxNode CreateThroughExpression(SyntaxGenerator factory)
...
-                        through = facts.Parenthesize(through);
+                            var explicitImplementationCast = generator.CastExpression(
+                                explicitlyImplementedProperty.ContainingType,
+                                generator.ThisExpression());
+                            
+                            through = generator.MemberAccessExpression(explicitImplementationCast,
+                                generator.IdentifierName(explicitlyImplementedProperty.Name));
+
+                            through = through.WithAdditionalAnnotations(Simplifier.Annotation);
+
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ImplementInterface/AbstractImplementInterfaceService.CodeAction.cs]: remove extra newline.

**Comment by kcnygaard** [comment]
@CyrusNajmabadi updated per feedback

**Comment by CyrusNajmabadi** [comment]
Thanks Kenny!

@MattGertz 

This is a great community contribution for a bug where the 'implement interface' feature wouldn't generate code properly through some complex cases involving properties.  I think it's low risk and would be nice to have for 15.3.

**Comment by MattGertz** [comment]
@CyrusNajmabadi Cool.  The scenario makes sense, so I'll approve, but we should have an ASK mode template.  It occurs to me that we should help non-MS contributors with that; I'll talk to leads about that.  We can either go with a sponsorship model where we do it for them, or have it posted somewhere on this repo, if we haven't already, along with when to use it. I'm leaning towards sponsorship as being less confusing (and since we'd have to bend it for VSO anyway), but we will see.

@kcnygaard Thanks for the contribution!

**Comment by CyrusNajmabadi** [comment]
Sounds good @MattGertz .  I think IDE would be happy to sponsor this sort of thing.  For now, here you go:

Customer scenario

Customer uses the 'implement interface' feature and selects the "i woudl like to implement this interface through this property i already have".  However, that property is an explicit property.  Our codegen in this scenario was busted and would not compile.

Bugs this fixes:

#18556 

Workarounds, if any

User doesn't use the feature :)

Risk

Very low.  This is self contained to this specific part of implement interface and should not have any deeper effect.

Performance impact

Low, for the same reason as the low risk.

Is this a regression from a previous update?

No.

Root cause analysis:

This was a complex combination of coding patterns, the feature wasn't equipped to handle it, and it slipped through as it's not a hugely common case.

How was the bug found?

Customer report.

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
retest windows_debug_vs-integration_prtest  please
