### PR TITLE
Don't preselect enums on backspace

### LINKED ISSUE #287: VB Completion on Backspace prefers Enum preselection over prefix/exact match
Ported from TFS WorkItem: <b>1015792</b>

------------------------------

<p><b>Repro Steps:</b></p>
<P><B>Affected Branch:</B> <BR><B>Affected Build:</B> <BR><B>Affected Product Language:</B> <BR><BR><B>Steps to reproduce:</B><BR><BR>1. Copy/paste VB code:</P>
<P>&nbsp;</P><PRE style="FONT-SIZE: 16px; FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink"><SPAN style="COLOR: blue">Enum</SPAN> <SPAN style="COLOR: #2b91af">E</SPAN>
    <SPAN style="COLOR: black">Bat</SPAN>
<SPAN style="COLOR: blue">End</SPAN> <SPAN style="COLOR: blue">Enum</SPAN>
 
<SPAN style="COLOR: blue">Class</SPAN> <SPAN style="COLOR: #2b91af">C</SPAN>
    <SPAN style="COLOR: blue">Sub</SPAN> <SPAN style="COLOR: black">Test</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: black">param</SPAN> <SPAN style="COLOR: blue">As</SPAN> <SPAN style="COLOR: #2b91af">E</SPAN><SPAN style="COLOR: black">)</SPAN>
        <SPAN style="COLOR: blue">Dim</SPAN> <SPAN style="COLOR: black">b</SPAN> <SPAN style="COLOR: blue">As</SPAN> <SPAN style="COLOR: #2b91af">E</SPAN>
        <SPAN style="COLOR: black">Test</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: black">b</SPAN><SPAN style="COLOR: black">.</SPAN>$$<SPAN style="COLOR: black">)</SPAN>
    <SPAN style="COLOR: blue">End</SPAN> <SPAN style="COLOR: blue">Sub</SPAN>
<SPAN style="COLOR: blue">End</SPAN> <SPAN style="COLOR: blue">Class</SPAN></PRE>
<P>&nbsp;</P>
<P>2. Remove the $$ if necessary and make sure there's no completion session active (hit ESC for good measure).</P>
<P>&nbsp;</P>
<P>3. Hit backspace.</P>
<P>&nbsp;</P>
<P><STRONG>Expected</STRONG>: Selected completion item is "b" field</P>
<P><STRONG>Actual</STRONG>: Selected completion item is "E.Bat" enum value</P>

------------------------------

<p><b>Revisions:</b></p>

1) Created By David Poeschl (8/26/2014 2:44:41 PM)

------------------------------

### PR DESCRIPTION
**Pull request by rchande**
When backspacing in VB, we used to prefer preselected items over text
matches. Dev12 does this for object creation preseletion, but not enum
preselection. We should match that behavior.

Fixes #287.

### CODE REVIEW

**Comment by Pilchie** [comment]
:+1:

File: src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests.vb [hunk 1]
```diff
@@ -613,6 +613,26 @@ End Module]]></Document>)
             End Using
         End Sub
 
+        <Fact, Trait(Traits.Feature, Traits.Features.Completion)>
```
Comment (dpoeschl) [inline src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests.vb]: WorkItem(###)? Do we have a convention for tagging tests with github workitem numbers that distinguishes from TFS workitem numbers?

Comment (dpoeschl) [inline src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests.vb]: Maybe [WorkItem(287, "https://github.com/dotnet/roslyn/issues/287")]?

Comment (Pilchie) [inline src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests.vb]: Yes, I was going to propose that too.  In the long term, maybe we make another overload that doesn't require the int param.

**Comment by dpoeschl** [comment]
:+1:
