### PR TITLE
Handle event symbols with explicit interface implementation in unused…

### LINKED ISSUE #30965: Incorrect IDE0051 (private member is unused)
**Version Used**: 2.11.0-beta1-63430-07+c96268112e069a5282fe6ab2b55db213c524b80c

**Steps to Reproduce**:

```CSharp
interface I
{
    event System.Action E;
}

class C : I
{
    event System.Action I.E // Incorrect IDE0051
    {
        add { }
        remove { }
    }
}
```

**Expected Behavior**: No IDE0051 on interface impl

**Actual Behavior**: IDE0051 on interface impl

Seems like it might be specific to events.

### PR DESCRIPTION
**Pull request by mavasani**
… members analyzer

Fixes #30965

### CODE REVIEW

File: src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -450,6 +450,9 @@ private bool IsCandidateSymbol(ISymbol memberSymbol)
                         case SymbolKind.Property:
                             return ((IPropertySymbol)memberSymbol).ExplicitInterfaceImplementations.IsEmpty;
 
+                        case SymbolKind.Event:
+                            return ((IEventSymbol)memberSymbol).ExplicitInterfaceImplementations.IsEmpty;
+
                         default:
                             return true;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: this seems to be one of the bug.  why default to 'true'?

File: src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs [hunk 2]
```diff
@@ -450,6 +450,9 @@ private bool IsCandidateSymbol(ISymbol memberSymbol)
                         case SymbolKind.Property:
                             return ((IPropertySymbol)memberSymbol).ExplicitInterfaceImplementations.IsEmpty;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: why are we not checking virtual/abstract/etc. here?

File: src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: Looking at this method, it's the opposite of what i would expect.  Because removing something has such a huge impact, i would have expected a whitelist, instead of a blacklist.  A blacklist means when we don't consider a case, we delete user code.  A whitelist means we only touch the cases we've explicitly stated we think are correct to remove.

Comment (amcasey) [reply src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: I generally agree that I'd rather have this diagnostic be under-aggressive than over-aggressive.

File: src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs (hunk 2 above)
Comment (mavasani) [reply src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: There is a check up front to only operate on private member symbols.

File: src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs (hunk 1 above)
Comment (mavasani) [reply src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: > A whitelist means we only touch the cases we've explicitly stated

I don't understand the suggestion. Can you give precise details on what such a list would be? Current check states all private member symbols are candidates to be marked as unused, and the switch case deals with exception cases where it is okay to have unreferenced private members.

File: src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs (hunk 2 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: then why do we check that stuff for methods?  Thanks!

Comment (mavasani) [reply src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: Seems like an oversight, let me delete that code.

File: src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: Right now, for example, you have to check for things like MethodKind == StaticConstructor/Destructor to say "don't apply to those guys".  That's a black-list.  You're looking for the things you don't support and you're enumerating those.

Instead, i would only enumerate the cases you *do* support.  That means every switch needs to be 'false' by default (or falls out to the bottom which is 'false), and every case needs to only identify a case you *would* support*.  This is a whitelist.  You enumerate the allowed cases.

Comment (mavasani) [reply src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: That would just invert the switch cases, without any real value add:
1. Switch sections for field/property/events will not change.
2. Switch section for method with a switch statement on method kind will be converted to list all method kinds except constructor, destructor, static constructor, and move the default case to that one.

Personally, I don't see a value add as I can't think of any unit test that I can add whose behavior will change will your suggestion. That approach also has a converse drawback of false positives (no reports) getting generated rather then false negatives (incorrect reports), former will go completely under the covers as no one will ever report them.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: > That would just invert the switch cases, without any real value add:

That is not true.  There are many benefits.  For example:
1. if we miss a case, we don't delete user code.
2. if the compiler adds a new symbol type we don't by default assume it's something we can remove.
3. it clearly shows which cases we've thought about, instead of which cases we may have forgotten.

> That approach also has a converse drawback of false positives (no reports) getting generated rather then false negatives (incorrect reports), 

That would literally be 1000% better :).  'no reports' means code keeps working.  'false' reports means we break user code by deleting things that are used.  This is a destructive feature.  Erring on the side of deleting code is irresponsible behavior on the part of this feature.  

> I don't see a value add as I can't think of any unit test that I can add whose behavior will change will your suggestion. T

That may be true today.  But it may not be true tomorrow.  Also, it depends *entirely* on you being able to enumerate all the cases in your head to validate that we haven't missed anything.  This bug *literally* exists because that strategy didn't work the last time around.

As an example, with the above, i have to ask myself "ok... what are all the different methodkinds i can get**?  is this behavior correct for all of them?".  As opposed to being in the state of going "ok, i can validate it is correct for the enumerated cases, if we miss something we can always add later in a safe manner."

Blacklist vs whitelist switches from the code needing perfect vigilance to not break users, to one where mistakes are non-impactful.  It's a clear and distinct improvement, and is usually one of the first design approaches that are chosen on with destructive systems to prevent problems.

--

** Honestly, i don't even know.  I'd have to go look at all the symbols and kinds to validate things.  That's a lot of work and still isn't correct if/when we change things in the future.  Features should try to be safe by default, and should be clear in intent.  That's no the case here.  And that's one reason why this issue was missed, and why it's hard to feel confidence about this approach going forward.

Comment (mavasani) [reply src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: > that's one reason why this issue was missed

That is not true - the issue was missed because I goofed up on not writing a test to cover this case. It wouldn't have changed even if it was written with your proposed approach :-)

I am going to move the discussion on this thread to a separate issue as this is a targeted fix for a scenario that was missed, along with a unit test.

Comment (mavasani) [reply src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: https://github.com/dotnet/roslyn/issues/30996

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: > That is not true - the issue was missed because I goofed up on not writing a test to cover this case. It wouldn't have changed even if it was written with your proposed approach :-)

Yes it woudl have.  Events would not have been candidates because they were not contained in the whitelist.  So, by default, anything missed would just be ignored.

Comment (mavasani) [reply src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: > So, by default, anything missed would just be ignored

Events were deliberately not added to the switch because I explicitly decided all private unused events should be flagged - I also added large number of tests for events to verify they **are** flagged when unused. The only thing that would have prevented this bug is me having the knowledge that event symbols can have explicit interface implementations, not just methods and properties :-)

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: > I explicitly decided all private unused events should be flagged 

But you did so through *implicit fallthrough*.  Which means the information is only in your head, and is not evident in code.  HTat's my point.  In a whitelist, the code informs the reader about the cases handled.  In a blacklist, the absence of code has to be reinterpretted by the reader as to what the final impact is.  

You've flipped this (as i've mentioned several times) from something i can look at and easily get confidence on, to something that is implicit and which reqiures a lot of analysis to ensure there are no other potential missing issues.  This changes the burden entirely and makes things more difficult.  And, as the default here is to consider something a *candidate* instead of *not* a candidate, we default to the *far worse* "false positive" state than "false negative" state.

Comment (mavasani) [reply src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: I have switched the analyzer to be more conservative to unblock the PR and left my views in https://github.com/dotnet/roslyn/issues/30996#issuecomment-436498024.

**Comment by mavasani** [comment]
Ping @dotnet/roslyn-ide for reviews.

File: src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs [hunk 3]
```diff
@@ -412,36 +412,28 @@ private bool IsCandidateSymbol(ISymbol memberSymbol)
                 if (memberSymbol.DeclaredAccessibility == Accessibility.Private &&
                     !memberSymbol.IsImplicitlyDeclared)
                 {
-                    // Do not track accessors, as we will track the associated symbol.
                     switch (memberSymbol.Kind)
                     {
                         case SymbolKind.Method:
-                            // Skip following methods:
```
Comment (sharwell) [inline src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: ❓ Can we document the definition of "candidate symbol" explicitly, either at or linked to from the documentation comment for the `IsCandidateSymbol` method?

Comment (mavasani) [reply src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: Done.

---
In reply to: [231527481](https://github.com/dotnet/roslyn/pull/30982#discussion_r231527481) [](ancestors = 231527481)

**Comment by mavasani** [comment]
Tagging @jinujoseph for approval

File: src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs [hunk 4]
```diff
@@ -405,43 +405,51 @@ void AddDebuggerDisplayAttributeArgumentsCore(ISymbol symbol, ArrayBuilder<strin
...
-                            //   6. Static constructors.
-                            //   7. Destructors.
                             var methodSymbol = (IMethodSymbol)memberSymbol;
                             switch (methodSymbol.MethodKind)
                             {
                                 case MethodKind.Constructor:
+                                    // It is fine to have an unused private constructor
+                                    // without parameters.
+                                    // This is commonly used for static holder types
+                                    // that want to block instantiation of the type.
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs]: thanks. these sorts of comments are very helpful.

**Comment by jinujoseph** [comment]
The Branch is not ready yet. I will flip the approval tag once it's ready to take the changes

**Comment by mavasani** [comment]
@jinujoseph for ask mode approval, seems the branch is now ready.
