### PR TITLE
NullableContextAttribute for property parameters is from accessor rather than containing type

### LINKED ISSUE #47221: Unexpected warning passing nullable argument to annotated indexer
A.cs:
```C#
#nullable enable
public class A
{
    public string? this[string x, string? y] => null;
    public static A F(string? s) => new A();
    public static A F(string x, string? y) => new A();
}
```
B.cs:
```C#
#nullable enable
class B
{
    static void Main()
    {
        string? s = null;
        var a = A.F("");
        _ = a["", s];
    }
}
```

Compile:
```
csc /t:library A.cs
csc /r:A.dll B.cs
```
Result:
```
B.cs(8,19): warning CS8604: Possible null reference argument for parameter 'y' in 'string? A.this[string x, string y]'.
```

### PR DESCRIPTION
**Pull request by cston**
Properties from metadata have parameters defined by the accessor including any `[Nullable]` attributes, so the `[NullableContext]` attribute should also be taken from the accessor as well.

(The `[NullableContext]` attribute for a method parameter, including accessors, is the nearest attribute on the method, or the containing types.)

Fixes #47221.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 1]
```diff
@@ -136199,5 +136199,74 @@ void M()
...
+
+            var source1 =
+@"#nullable enable
+class B
+{
+    static void F(object x, object? y)
+    {
+        var a = A.F(x, y);
+        var b = a[x, y];
+        b.ToString(); // 1
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:136226]: Previously, a warning was reported for `y` in `a[x, y]`.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 2]
```diff
@@ -136199,5 +136199,74 @@ void M()
...
+
+            var source1 =
+@"#nullable enable
+class B
+{
+    static void F(object x, object? y)
+    {
+        var a = new A();
+        var b = a[x, y]; // 1
+        b.ToString();
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:136262]: Previously, no warning was reported for `y` in `a[x, y]`.

**Comment by eerhardt** [comment]
Will we need to take a new compiler in `dotnet/runtime` in the `release/5.0` branch to pick this change up? That way our `ref` assembiles will be correct when we ship them for 5.0.

**Comment by cston** [comment]
> Will we need to take a new compiler in dotnet/runtime in the release/5.0 branch to pick this change up? That way our ref assembiles will be correct when we ship them for 5.0.

I believe the ref assemblies are emitted correctly. The issue was in decoding the attributes when loading the methods from metadata.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 3]
```diff
@@ -136199,5 +136199,74 @@ void M()
...
+        [Fact]
+        [WorkItem(47221, "https://github.com/dotnet/roslyn/issues/47221")]
+        public void PropertyAccessorWithNullableContextAttribute_02()
+        {
+            var source0 =
+@"#nullable enable
+public class A
+{
+    public object this[object? x, object y] => new object();
+    public static A? F0;
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:136245]: Are F0-4 necessary for this test?

Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:136245]: > Are F0-4 necessary for this test?

Yes, we need more annotated reference types than unannotated reference types in the type definition to generate a `[NullableContext(2)]` on type, and that attribute is needed to force a `[NullableContext(1)]` on the property accessor.

Comment (eerhardt) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:136245]: > Yes, we need more annotated reference types than unannotated reference types in the type definition

that's probably why I couldn't repro this standalone myself....
