### PR TITLE
Fix extra warning for unused local function

### LINKED ISSUE #47463: Conditional Local Functions are considered unused
```cs
using System.Diagnostics;

public class C {
    public void M() {
        local();
        
        [Conditional("DEBUG")]
        static void local() {} // Warning: unused local function
    }
}
```

This reproes when compiling for release mode.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #47463

### CODE REVIEW

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs [hunk 1]
```diff
@@ -1180,7 +1180,7 @@ public override BoundNode VisitCall(BoundCall node)
             VisitReceiverBeforeCall(node.ReceiverOpt, node.Method);
             VisitArgumentsBeforeCall(node.Arguments, node.ArgumentRefKindsOpt);
 
-            if (!callsAreOmitted && node.Method?.OriginalDefinition is LocalFunctionSymbol localFunc)
+            if (node.Method?.OriginalDefinition is LocalFunctionSymbol localFunc)
```
Comment (Youssef1313) [inline src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:1183]: Since `node` is actually a `BoundCall`, then we already know the local function is used. We want to visit it regardless it's **conditionally** omitted or not.

File: src/Compilers/CSharp/Test/Semantic/FlowAnalysis/LocalFunctions.cs [hunk 2]
```diff
@@ -1618,5 +1618,28 @@ void local1(string s1, out string s2)
...
+        local2();
+
+        [Conditional(""DEBUG"")]
+        static void local() { }
+
+        static void local2() { }
+    }
+}
+").VerifyDiagnostics();
+        }
```
Comment (Youssef1313) [inline src/Compilers/CSharp/Test/Semantic/FlowAnalysis/LocalFunctions.cs:1642]: A test where the diagnostic should be reported is already in this file:

https://github.com/dotnet/roslyn/blob/a7287667193bf2766f5b5d0b4b13f2a5c2ad8d9e/src/Compilers/CSharp/Test/Semantic/FlowAnalysis/LocalFunctions.cs#L684-L700

Feel free if you want to add more test cases.

**Comment by Youssef1313** [comment]
CI is failing due to the following test

https://github.com/dotnet/roslyn/blob/1ed3ef5f8a7f4e4264430ab3787c9dd7a7a817c6/src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs#L5513-L5540

Should I delete my test and update the expected for the failing test?

https://github.com/dotnet/roslyn/blob/1ed3ef5f8a7f4e4264430ab3787c9dd7a7a817c6/src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs#L5513-L5540

**Comment by RikkiGibson** [comment]
@Youssef1313 I went in and made the edits to the tests. Thanks for tracking down the root cause of this :smile:

**Review by RikkiGibson — APPROVED** [review]

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler Please review this very straightforward bug fix

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs (hunk 1 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:1183]: I worry that this change may be unsound (allowing accessing an unassigned variable). Please add a test for:
```
public class C 
{
    public void M() 
    {
        int i;
        local();
        i.ToString();
        
        [Conditional("DEBUG")]
        void local()
        {
           i = 1;   
        }
    }
}
```

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:1183]: It will be good to add this test. I believe it will produce the desired error on `i.ToString()` because we reset the definite assignment state after visiting the call when `callsAreOmitted` is true.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:1183]: Oh wait. I forgot that we disallow instance local functions from having `ConditionalAttribute` at all. We have [specified](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-9.0/local-function-attributes.md#attributes) that a local function must be `static` in order to be conditional.

Comment (Youssef1313) [reply src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:1183]: > we disallow non-static local functions from having ConditionalAttribute at all.

That saved some extra debugging :smile:

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:1183]: @jcouv Please take another look at your convenience. I do not think there is a supported scenario involving capturing variables in a conditional local function.

Comment (jcouv) [reply src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs:1183]: Sounds good. That's great.
Can we update the test (`LocalFunction_ConditionalAttributeDisallowed`). We should be able to remove the `#pragma warning`.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 3). Consider updating existing test for [Conditional] on non-static local function.

**Comment by Youssef1313** [comment]
@jcouv The test you're referring to should fail if we removed the #pragma warning because the local function there is *indeed* unused. The PR removes the warning only if the method is actually used.

**Comment by 333fred** [comment]
Thanks @Youssef1313!
