### PR TITLE
Guard against `string.Concat(object)` returning null

### LINKED ISSUE #34085: Inconsistent and non-compliant behaviour when ToString returns null, and is concatted with emptystring
**Version Used**: 2.9.0

**Steps to Reproduce**:

```csharp
public class C
{
    public override string ToString() => null;
}

Console.WriteLine(("" + new C()) == null);
Console.WriteLine((new C() + "") == null);
Console.WriteLine(("" + new C() + "") == null);
Console.WriteLine((new C() + "" + "") == null);
```

**Expected Behavior**:

According to section 7.8.4 "Addition Operator" of the C# Language Specification:

> String concatenation:
>        `string operator +(string x, string y);`
>        `string operator +(string x, object y);`
>        `string operator +(object x, string y);`
> These overloads of the binary + operator perform string concatenation. If an operand of string concatenation is null, an empty string is substituted. Otherwise, any non-string argument is converted to its string representation by invoking the virtual ToString method inherited from type object. **If ToString returns null, an empty string is substituted.**
> ...
> **The string concatenation operator never returns a null value**

Therefore I'd expect the code above to print

```
False
False
False
False
```

**Actual Behavior**:

```
True
True
False
False
```

The compiler folds the "" constant in all three cases, reducing them all to a call to `string.Concat(new C())`. However in the third and fourth cases, it appends a test to see if `string.Concat` returns `null`, and if so it substitutes "". `string.Concat` tests whether its argument is null (and substitutes "" if so), but doesn't test whether calling `.ToString()` on its argument results in null.

Using `null` instead of "" seems to exhibit the same behaviour. If you use `string.Empty`, the compiler doesn't do the same constant folding, and the issue doesn't appear.

Interestingly this behaviour was different pre-Roslyn - in that case, you get

```
True
True
True
True
```

[Repro on SharpLab](https://sharplab.io/#v2:EYLgHgbALANALiATgVwHYB8ACAGABJgRgG4BYAKHMwGZ8CJ8AmWgdnIG9zcv8bD7MouALIBDAJaoAFAEpO3DmW5LaATkmSARBtwBqXKgCmAd1wBhGdNwBeK/uQAbe9NKLlXQmsmGT5y3q2WNnaOznJuHupauvrGZjLRAda2qA5OLm7uBJ7ecX64Uf4agcmpoa5cAL7kVRRk1Ixm7GE8uAD2AG4GiIhiACYGtHgAKq0AynA9qADm8VYAfMH2LhVAA)

### PR DESCRIPTION
**Pull request by canton7**
This PR is intended as a starting point for any discussion on #34085.

Note that this is a **BREAKING CHANGE** (although it's a correction to align with the spec, it's very niche, and a similar case was inadvertently fixed by Roslyn and I don't believe anyone noticed).

I believe it stands on its own as a working solution (for C# - it doesn't (yet) cover VB), but anticipate that it may need to change, or be rejected entirely because of its breaking nature.

Alternatives to this approach:

1. Change `string.Concat(object)` to never return null (also a breaking change)
2. Use `o?.ToString() ?? ""` instead of `string.Concat(o) ?? ""`
3. Change the spec, or accept and live with the deviation

------------------------------

If you define an object with a ToString method which returns null:

    public class C
    {
        public override string ToString() => null;
    }

And then concatenate that with `null` or "":

    C c = new C();
    c + ""

then the compiler emits:

    string.Concat(c)

However, `string.Concat(object)` will return null if the object's
ToString method returns null. This contradicts section 7.8.4 of the
Specification, which says:

    If ToString returns null, an empty string is substituted.
    ...
    The string concatenation operator never returns a null value

On the other hand, if you write:

    c + "" + ""

then the compiler emits:

    string.Concat(c) ?? ""

This is because it reduces `c + ""` to `string.Concat(c)` as before, but
when it considers the second `+ ""`, it sees `<string> + ""` and simplifies
that to `<string> ?? ""`. This is unnecessary in this case, but
inadvertently fixes this case.

This PR always emits `string.Concat(c) ?? ""`. It enhances the logic
which extracts the arguments to a call to `string.Concat` so it can unwrap
the null coalescing operator, and it enhances the `<string> + ""` logic
so that it only adds `?? ""` if `<string>` is not a call to `string.Concat`
(or `string.Concat(object) ?? ""`), since we know that this can never
result in null.

This introduces one more allocation: a single-element ImmutableArray
in some cases.

It seems that compiled expressions were never affected by this. Their
behaviour now matches that of compiled C#.

This does not change any of the VB code. I haven't looked into what the
VB spec says here, and I want any discussions on this PR to be resolved
before I invest that effort.

Fixes #34085

### CODE REVIEW

**Comment by canton7** [comment]
The test failure is because the test case tests what happens if `string.Concat(object)` is missing, and so [this line](https://github.com/dotnet/roslyn/pull/34208/files#diff-4ba33044f27f4544fb3d1ddf4903e749R295) gets an `ErrorMethodSymbol`, which it then passes to `_factoryCoalesce`, which hits a `Debug.Assert`.

What's the correct way to handle this? Should I do an explicit check to see if `method` is an `ErrorMethodSymbol` before trying to pass it to `BoundCall.Synthesized` and subsequently `_factory.Coalesce`?

**Comment by gafter** [comment]
Continuing discussion of possible compat concerns at https://github.com/dotnet/roslyn/issues/34085

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenStringConcat.cs [hunk 1]
```diff
@@ -358,18 +358,84 @@ static void Main()
             comp.VerifyDiagnostics();
             comp.VerifyIL("Test.Main", @"
 {
-  // Code size       35 (0x23)
+  // Code size       44 (0x2c)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenStringConcat.cs]: how does this compare to the IL produced for the pre-Roslyn compiler?

Comment (canton7) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenStringConcat.cs]: In this specific case, pre-Roslyn generates the same as Roslyn did before this PR: a straight call to `string.Concat(object)` with no subsequent null-check for an object, and `S ?? ""` for a string.

Pre-Roslyn generates the same for `O + null + null` and `S + null + null` (whereas Roslyn generated `string.Concat(O) ?? ""` for the first case).

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StringConcat.cs [hunk 2]
```diff
@@ -257,14 +281,22 @@ private BoundExpression RewriteStringConcatenationOneExpr(SyntaxNode syntax, Bou
         {
             if (loweredOperand.Type.SpecialType == SpecialType.System_String)
             {
-                // loweredOperand ?? ""
-                return _factory.Coalesce(loweredOperand, _factory.Literal(""));
+                // It it's a call to string.Concat, we already know the result is not null. Otherwise return loweredOperand ?? ""
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StringConcat.cs]: >It it's a call to string.Concat, we already know the result is not null [](start = 19, length = 71)

This appears to be incorrect.  You point out in the OP a circumstance in which `string.Concat` can return null.

**Comment by gafter** [comment]
We are OK with the compat implications of this.

**Comment by Suchiman** [comment]
From what i can tell, only `String.Concat(object)` may return null, so the optimization is still valid for the other overloads.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StringConcat.cs (hunk 2 above)
Comment (canton7) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StringConcat.cs]: Right. The compiler will never emit `string.Concat(object)` on its own (it always emits `string.Concat(object) ?? ""`), but of course the user can compile the code `string.Concat(c) + null`, and that will get compiled to `string.Concat(c)`. 

I added this optimization to avoid `o + null + null` from being compiled to `string.Concat(o) ?? "" ?? ""` (which just looks like a bug to anyone inspecting the compiler output), and `o + o + ""` from being compiled to `string.Concat(o, o) ?? ""` (which is an optimization that the pre-Roslyn compiler does, but it seems it was lost in Roslyn).

I think there's a way to fix this cleanly. I'll put together a commit later, then please let me know whether you want to keep it with the fix, or remove it altogether.

File: src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs [hunk 3]
```diff
@@ -717,7 +717,7 @@ public BoundExpression ComplexConditionalReceiver(BoundExpression valueTypeRecei
 
         public BoundExpression Coalesce(BoundExpression left, BoundExpression right)
         {
-            Debug.Assert(left.Type.Equals(right.Type, TypeCompareKind.IgnoreCustomModifiersAndArraySizesAndLowerBounds | TypeCompareKind.IgnoreNullableModifiersForReferenceTypes));
+            Debug.Assert(left.Type.Equals(right.Type, TypeCompareKind.IgnoreCustomModifiersAndArraySizesAndLowerBounds | TypeCompareKind.IgnoreNullableModifiersForReferenceTypes) || left.Type.IsErrorType());
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs]: >eft.Type.IsErrorType() [](start = 183, length = 22)

The need for this confuses me.  If a program has errors, we don't lower it or perform code generation.  So why would this be needed?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StringConcat.cs [hunk 4]
```diff
@@ -168,16 +152,73 @@ private void FlattenConcatArg(BoundExpression lowered, ArrayBuilder<BoundExpress
...
+                            return true;
                         }
                     }
                     break;
             }
 
-            // fallback - if nothing above worked, leave arg as-is
-            flattened.Add(lowered);
-            return;
+            arguments = ImmutableArray<BoundExpression>.Empty;
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StringConcat.cs]: >ImmutableArray<BoundExpression>.Empty [](start = 24, length = 37)

default

File: src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs (hunk 3 above)
Comment (canton7) [reply src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs]: This assertion was triggered by the unit test which tests the case where `string.Concat(object)` is missing. I'm not at all convinced that this is the right approach: please let me know if I should do something else.

**Comment by canton7** [comment]
I'm afraid I seem to have broken some of the IntelliSense tests, but I can't reproduce them locally and I'm not sure how to get details of the failure (stack trace, etc) out of roslyn-CI. Any guidance would be appreciated.

File: src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs (hunk 3 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs]: I understand: the error bound node is triggered by an error arising during lowering.  So this is correct.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StringConcat.cs [hunk 5]
```diff
@@ -168,16 +152,73 @@ private void FlattenConcatArg(BoundExpression lowered, ArrayBuilder<BoundExpress
...
+                            loweredCanReturnNull = false;
+
+                            // The left operand might be a call to string.Concat(object)
+                            if (boundCoalesce.LeftOperand.Kind == BoundKind.Call &&
+                                TryExtractStringConcatArgsFromBoundCall((BoundCall)boundCoalesce.LeftOperand, out arguments, out _))
+                            {
+                                return true;
+                            }
+
+                            arguments = ImmutableArray<BoundExpression>.Empty.Add(boundCoalesce.LeftOperand);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StringConcat.cs]: nit: consider `ImmutableArray.Create(boundCoalesce.LeftOperand)` here

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StringConcat.cs [hunk 6]
```diff
@@ -168,16 +152,73 @@ private void FlattenConcatArg(BoundExpression lowered, ArrayBuilder<BoundExpress
...
-            flattened.Add(lowered);
-            return;
+            arguments = default;
+            loweredCanReturnNull = default;
+            return false;
+        }
+
+        private bool TryExtractStringConcatArgsFromBoundCall(BoundCall boundCall, out ImmutableArray<BoundExpression> arguments, out bool callCanReturnNull)
+        {
+            // callCanReturnNull is true if this method returns true, and boundCall is a call to a string.Concat overload which can return null
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StringConcat.cs]: Consider putting this comment which seems to describe the "contract" of this method above the signature. Same with `TryExtractStringConcatArgs`.

**Comment by gafter** [comment]
@canton7 This has been approved to integrate.  Please tell us when you're ready for us to merge it (i.e. let us know if you want to make any further changes based on the most recent review comments).

**Comment by canton7** [comment]
Thanks! I'll make some changes tomorrow in response to the good points that @RikkiGibson raised, and let you know when I'm done.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StringConcat.cs (hunk 5 above)
Comment (canton7) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_StringConcat.cs]: Aha!

**Comment by canton7** [comment]
I've implemented @RikkiGibson's comments, rebased onto master, and tidied up the commits. After the rebase the whole test suite now passes, with the exception of some of the Windows_VisualStudio_Integration_Tests tests (which seem to be failing for other PRs as well).

Once the test suite passes, I think we're good to go!

**Comment by gafter** [comment]
@canton7 In the future please do not rebase.  It makes it impossible for us to determine what was changed since we last reviewed.  We usually rebase and squash all commits when we merge.

**Comment by gafter** [comment]
@canton7 Thank you so much for your contribution!

**Comment by canton7** [comment]
Apologies, I didn't see anything about it on [Contributing Code](https://github.com/dotnet/roslyn/wiki/Contributing-Code).

Thanks everyone for your time getting this through! I appreciate the support and effort.
