### PR TITLE
Adding code fix for CS0822 (Implicitly-typed variables cannot be constant)

### LINKED ISSUE #30516: Code fix for CS0822 (Implicitly-typed variables cannot be constant)
There should be a code fix to use explicit type when this compiler error occurs:
```c#
class C
{
    void M()
    {
        const var v = ""; // CS0822: Implicitly-typed variables cannot be constant
    }
}
```
to
```c#
class C
{
    void M()
    {
        const string v = "";
    }
}
```

### PR DESCRIPTION
**Pull request by Neme12**
Fixes #30516

cc @CyrusNajmabadi

### CODE REVIEW

File: src/Features/CSharp/Portable/UseExplicitTypeForConst/UseExplicitTypeForConstCodeFixProvider.cs [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+        {
+            var root = await context.Document.GetSyntaxRootAsync(context.CancellationToken).ConfigureAwait(false);
+
+            if (root.FindNode(context.Span) is VariableDeclarationSyntax variableDeclaration &&
+                variableDeclaration.Variables.Count == 1)
+            {
+                var semanticModel = await context.Document.GetSemanticModelAsync(context.CancellationToken).ConfigureAwait(false);
+
+                var type = semanticModel.GetTypeInfo(variableDeclaration.Type, context.CancellationToken).ConvertedType;
+                if (type == null || type.TypeKind == TypeKind.Error || type.IsAnonymousType)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/UseExplicitTypeForConst/UseExplicitTypeForConstCodeFixProvider.cs]: nit: even of these, i think it would be fine to offer 'object'.  It's up to you though.

File: src/Features/CSharp/Portable/UseExplicitTypeForConst/UseExplicitTypeForConstCodeFixProvider.cs [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+            var newRoot = root.ReplaceNode(variableDeclaration.Type, type.GenerateTypeSyntax(allowVar: false));
+            return document.WithSyntaxRoot(newRoot);
+        }
+
+        private sealed class MyCodeAction : CodeAction.DocumentChangeAction
+        {
+            public MyCodeAction(Func<CancellationToken, Task<Document>> createChangedDocument) :
+                base(CSharpFeaturesResources.Use_explicit_type_instead_of_var,
+                     createChangedDocument,
+                     CSharpFeaturesResources.Use_explicit_type_instead_of_var)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/UseExplicitTypeForConst/UseExplicitTypeForConstCodeFixProvider.cs]: nit: technically don't need the equiv key since you're not doing any fix-all.

File: src/Workspaces/CSharp/Portable/Utilities/CSharpUseExplicitTypeHelper.cs [hunk 3]
```diff
@@ -88,13 +88,20 @@ protected override bool ShouldAnalyzeForEachStatement(ForEachStatementSyntax for
...
+                var variableDeclaration = (VariableDeclarationSyntax)typeName.Parent;
+                var variable = variableDeclaration.Variables.First();
                 if (!AssignmentSupportsStylePreference(
                         variable.Identifier, typeName, variable.Initializer.Value,
                         semanticModel, optionSet, cancellationToken))
                 {
                     return false;
                 }
+
+                // This is handled by another code fix.
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Utilities/CSharpUseExplicitTypeHelper.cs]: nit: mention the name of hte code fix that fixes this?  you might also want to explain that this is an error case, and that's why we don't think the main user feature is the right codepath to handle this sort of conversoin.

File: src/Features/CSharp/Portable/UseExplicitTypeForConst/UseExplicitTypeForConstCodeFixProvider.cs (hunk 1 above)
Comment (Neme12) [reply src/Features/CSharp/Portable/UseExplicitTypeForConst/UseExplicitTypeForConstCodeFixProvider.cs]: You said you didn't like that in the previous PR (where I did the IsAnonymousType check to change that to object).

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseExplicitTypeForConst/UseExplicitTypeForConstCodeFixProvider.cs]: i didn't like it in the context of the *original* "use explicit type" fixer :)   It didn't make sense there to me.  Here, it's fine since this is about an error case to begin with :)

File: src/Features/CSharp/Portable/UseExplicitTypeForConst/UseExplicitTypeForConstCodeFixProvider.cs (hunk 2 above)
Comment (Neme12) [reply src/Features/CSharp/Portable/UseExplicitTypeForConst/UseExplicitTypeForConstCodeFixProvider.cs]: ➡️ Removed in c0b9ac255eda3831499d11ff335a731348c8bf0b

File: src/Workspaces/CSharp/Portable/Utilities/CSharpUseExplicitTypeHelper.cs (hunk 3 above)
Comment (Neme12) [reply src/Workspaces/CSharp/Portable/Utilities/CSharpUseExplicitTypeHelper.cs]: ➡️ Fixed in c0b9ac255eda3831499d11ff335a731348c8bf0b

**Comment by Neme12** [comment]
Thank you!
