### PR TITLE
Ensure that we show the gold bar for .editorconfig as solution item o…

### LINKED ISSUE #39472: Too many info bars for "A new .editorconfig file was detected..."
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/787241/too-many-info-bars-for-a-new-editorconfig-file-was.html)._

---
I have a solution containing over 10 projects. I added an .editorconfig file and a whole bunch of info bars popped up--it seems like 1 per project. 

Steps to reproduce:
Create a solution with multiple projects inside a folder in VS (see attached)
Right click on folder, &quot;Add-&gt;New EditorConfig (IntelliCode) which generates the .editorconfig
After the file is generated, a whole bunch of info bars pop up asking to make .editoroconfig a solution item. 

Expected: I should only see 1 info bar.

---
#### Visual Studio Feedback System on 10/22/2019, 02:54 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by mavasani**
…nly once per solution

Fixes #39472

### CODE REVIEW

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/AnalyzerConfigDocumentAsSolutionItemHandler.cs [hunk 1]
```diff
@@ -57,9 +58,23 @@ void IDisposable.Dispose()
 
         private void OnWorkspaceChanged(object sender, WorkspaceChangeEventArgs e)
         {
-            // Check if a new analyzer config document was added and we have a non-null DTE instance.
-            if (e.Kind != WorkspaceChangeKind.AnalyzerConfigDocumentAdded ||
-                _dte == null)
+            switch (e.Kind)
+            {
+                case WorkspaceChangeKind.SolutionAdded:
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/AnalyzerConfigDocumentAsSolutionItemHandler.cs]: Can you file a bug to have us add a test against the VisualStudioWorkspace in the open/close/open again we raise SolutionAdded the second time? Looking at the code this is what we do, but I'm not sure if we have a test that would prevent us from breaking this.

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/AnalyzerConfigDocumentAsSolutionItemHandler.cs [hunk 2]
```diff
@@ -93,10 +108,14 @@ private void OnWorkspaceChanged(object sender, WorkspaceChangeEventArgs e)
                     return;
                 }
 
-                var infoBarService = _workspace.Services.GetRequiredService<IInfoBarService>();
-                infoBarService.ShowInfoBarInGlobalView(
-                    ServicesVSResources.A_new_editorconfig_file_was_detected_at_the_root_of_your_solution_Would_you_like_to_make_it_a_solution_item,
-                    GetInfoBarUIItems().ToArray());
+                if (!_infoBarShownForCurrentSolution)
+                {
+                    _infoBarShownForCurrentSolution = true;
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/AnalyzerConfigDocumentAsSolutionItemHandler.cs]: Any reason not to just set this once we've kicked off the task? Then it avoids having to re-check it a second time which seems a bit easier.

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/AnalyzerConfigDocumentAsSolutionItemHandler.cs (hunk 1 above)
Comment (mavasani) [reply src/VisualStudio/Core/Def/Implementation/ProjectSystem/AnalyzerConfigDocumentAsSolutionItemHandler.cs]: Filed https://github.com/dotnet/roslyn/issues/39476
