### PR TITLE
Bail out from emit in presence of warnings reported as errors

### LINKED ISSUE #37779: Warning diagnostics escalated to errors doesn't block emitting the output
**Version Used**: Version 16.3.0 Preview 3.0 [29205.144.master], Roslyn part is 3.3.0-beta2-19401-05+8ed56b826700926009731ca4d3de0a4e4e652969

**Steps to Reproduce**:

1. Create a new .NET Core console application.
2. Update the contents of Main to have:
```c#
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            return;

            Console.WriteLine("Hello World!");
        }
```
This is to produce a warning (unreachable code).
3. Add an .editorconfig and add `dotnet_diagnostic.CS0162.severity = error` to it so it applies to the file.
4. Build. In the build output, you see a build error. (Note: it may not reflect in the IDE due to feature flag concerns at the moment.)
5. Build a second time.

**Expected Behavior**: the second build still shows an error.
**Actual Behavior**: the second build just says "succeeded".

This is happening because the first build, despite emitting an error, is still outputting it's output binary. Thus, the second build sees "everything up to date" and simply builds successfully.

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #37779

### CODE REVIEW

File: src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs [hunk 1]
```diff
@@ -11271,6 +11271,58 @@ class C { }";
 
             CleanupAllGeneratedFiles(srcFile.Path);
         }
+
+        [Theory]
+        [InlineData(true)]
+        [InlineData(false)]
+        [WorkItem(37779, "https://github.com/dotnet/roslyn/issues/37779")]
+        public void CompilerWarnAsErrorDoesNotEmit(bool warnAsError)
```
Comment (agocke) [inline src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs]: I'd also expect tests for the API, i.e. you call Emit and it should not actually emit to the stream.

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs [hunk 2]
```diff
@@ -1044,13 +1059,13 @@ private int RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, Cancellat
...
-                                if (HasUnsuppressedErrors(diagnostics))
-                                {
-                                    success = false;
-                                }
                             }
                         }
+
+                        if (HasReportedErrors(diagnostics))
+                        {
+                            success = false;
```
Comment (agocke) [inline src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: This looks wrong, it won't catch people who call Emit with errors.

File: src/Compilers/Core/Portable/Diagnostic/Diagnostic.cs [hunk 3]
```diff
@@ -567,6 +567,12 @@ internal virtual bool IsNotConfigurable()
         /// </summary>
         internal bool IsUnsuppressableError()
             => DefaultSeverity == DiagnosticSeverity.Error && IsNotConfigurable();
+
+        /// <summary>
+        /// Returns true if this is a unsuppressed diagnostic with an effective error severity.
+        /// </summary>
+        internal bool IsReportedError()
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Diagnostic/Diagnostic.cs]: >IsReportedError [](start = 22, length = 15)

The name feels confusing. What does it mean to be reported? A Diagnostic itself cannot know whether it was reported or not. Another way to look at this is that every Diagnostic is reported, otherwise the instance wouldn't exist. Consider renaming to something like "IsNotSuppressedError" or something similar.

Comment (AlekseyTs) [reply src/Compilers/Core/Portable/Diagnostic/Diagnostic.cs]: Or "IsUnsuppressedError"

---
In reply to: [313542576](https://github.com/dotnet/roslyn/pull/37948#discussion_r313542576) [](ancestors = 313542576)

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs [hunk 4]
```diff
@@ -580,6 +580,21 @@ internal static bool HasUnsuppressedErrors(DiagnosticBag diagnostics)
             return false;
         }
 
+        /// <summary>
+        /// Returns true if there are any unsuppressed error diagnostics in the bag.
+        /// </summary>
+        private static bool HasReportedErrors(DiagnosticBag diagnostics)
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: >HasReportedErrors [](start = 28, length = 17)

Would it make sense to rename HasUnsuppressedErrors (the helper above) to HasUnsuppressableError and this helper to HasUnsuppressedErrors?

Comment (mavasani) [reply src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: Yes, that sounds better. I will do the rename of this method and even the internal helpers on `Diagnostic`.

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs [hunk 5]
```diff
@@ -1044,13 +1059,13 @@ private int RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, Cancellat
...
                                 analyzerDriver.ApplyProgrammaticSuppressions(diagnostics, compilation);
-
-                                if (HasUnsuppressedErrors(diagnostics))
-                                {
-                                    success = false;
-                                }
                             }
                         }
+
+                        if (HasReportedErrors(diagnostics))
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: >HasReportedErrors [](start = 28, length = 17)

Could you remind where do we go through process of elevating/suppressing diagnostics? Can we be sure we went through that process at this point?

Comment (AlekseyTs) [reply src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: For example, I see a couple of usages of ```HasUnsuppressedErrors``` API below. Should they be adjusted as well?

---
In reply to: [313566102](https://github.com/dotnet/roslyn/pull/37948#discussion_r313566102) [](ancestors = 313566102)

Comment (mavasani) [reply src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: Filtering of compiler diagnostics (i.e. applying the ruleset, nowarn, warnaserror, etc. options) happens at individual compilation stages (for example [here](https://github.com/dotnet/roslyn/blob/a5418f7398495db4ea858f0c9efd9b13541ff478/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs#L2336)). After each stage, we bail out in presence of unsuppressable compiler errors(for example [here](https://github.com/dotnet/roslyn/blob/ad175163a22afe8a642fc8cad967dfa41d2458b8/src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs#L846) and [here](https://github.com/dotnet/roslyn/blob/ad175163a22afe8a642fc8cad967dfa41d2458b8/src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs#L894)), but not warnings escalated to errors as these could be programattically suppressed. Filtering of analyzer diagnostics happens immediately after an analyzer diagnostic is reported (for example [here](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs#L1477). At the end of compiling all method bodies, we force complete all analyzer execution and apply programatic suppressions [here](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs#L1037-L1052).

Comment (mavasani) [reply src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: > For example, I see a couple of usages of HasUnsuppressedErrors API below. Should they be adjusted as well?

I believe the checks in this method below are just optimizations to exit earlier from `CompileAndEmit`, so we can go either way. Caller immediately invokes [ReportDiagnostics](http://source.roslyn.io/#Microsoft.CodeAnalysis/CommandLine/CommonCompiler.cs,747) after invoking `CompileAndEmit`.

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs (hunk 4 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: I was able to move this method to a static local method inside the Emit API - that should be the only place where we care about bailing out early in presence of warnings escalated as errors.

File: src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs [hunk 6]
```diff
@@ -5163,5 +5163,33 @@ public void CompileAndVerifyModuleIncludesAllModules()
...
+{
+    int _f;
+}";
+            var options = new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, generalDiagnosticOption: ReportDiagnostic.Error);
+            var compilation = CreateCompilation(source, options: options);
+
+            EmitResult emitResult;
+            using (var output = new MemoryStream())
+            {
+                emitResult = compilation.Emit(output, pdbStream: null, xmlDocumentationStream: null, win32Resources: null);
```
Comment (agocke) [inline src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: We also need to verify that the PDB and XML docs are not generated.

**Comment by CyrusNajmabadi** [comment]
Just to check, but this doesn't block 'MetadataEmit' right?  Only normal emit?  We wouldn't want warnings (Even as errors) to mean that we coudln't have our metadata-emit happening during IDE scenarios as that's how we share information and keep things up-to-date with symbols in cross-language scenarios.

**Comment by agocke** [comment]
We should definitely confirm that skeleton assemblies are unaffected

File: src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs (hunk 6 above)
Comment (mavasani) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: Updated the test to verify pdb is not generated. XML documentation generation happens [prior](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs#L1011) to the compiler [force completing](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs#L1033) the trees, which happens prior to [application of diagnostic suppressors](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs#L1046). We either need to change this ordering OR special case bailing out of XML documentation generation in presence of warnings escalated to errors + no diagnostic suppressors. I think either of these would add unnecessary complexity to this PR and should be done as a separate change. I can file a separate tracking issue if that seems reasonable.

**Comment by mavasani** [comment]
> Just to check, but this doesn't block 'MetadataEmit' right? Only normal emit? We wouldn't want warnings (Even as errors) to mean that we coudln't have our metadata-emit happening during IDE scenarios as that's how we share information and keep things up-to-date with symbols in cross-language scenarios.

Thanks @CyrusNajmabadi. Added a test to cover the metadataOnly Emit invocation for skeleton assemblies.

File: src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs (hunk 6 above)
Comment (agocke) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: No, I don't think leaving this unfixed is OK.

Comment (agocke) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: I think the previous behavior was that CompileMethods would have failed, which would have stopped XML generation. If this is broken by diagnostic suppressors, that's not acceptable.

Comment (mavasani) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: @agocke - What is your proposed fix?

Comment (agocke) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: At the moment I don't have one. If we can't think of one, we should revert the diagnostic suppressor changes.

**Comment by CyrusNajmabadi** [comment]
You're welcome!

File: src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs (hunk 6 above)
Comment (mavasani) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: > If we can't think of one, we should revert the diagnostic suppressor changes.

I did propose an option which would cover majority of cases: special case bailing out of XML documentation generation in presence of warnings escalated to errors + no diagnostic suppressors.

Comment (agocke) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: The compiler can't write doc files if the build fails. Fixing most of the cases isn't good enough.

Comment (mavasani) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: I believe the options are:

1. Revert the DiagnosticSupppressor API completely
2. Make DiagnosticSuppressor API specific to analyzer diagnostics only (compiler warnings cannot be programmatically suppressed)
3. Tweak the current PR so that XML doc file will not be generated for build failures, except in presence of warnings escalated to errors if there is at least one diagnostic suppressor.
4. Keep the PR in current state where XML doc will still get generated if there are no compiler errors, but only compiler warnings escalated to errors.

Tagging @jinujoseph @tmat @sharwell for their views. @agocke believes 3 or 4 is not acceptable.

File: src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs [hunk 7]
```diff
@@ -5163,5 +5163,64 @@ public void CompileAndVerifyModuleIncludesAllModules()
...
+{
+    int _f;
+}";
+            var options = new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, generalDiagnosticOption: ReportDiagnostic.Error);
+            var compilation = CreateCompilation(source, options: options);
+
+            using var output = new MemoryStream();
+            using var pdbStream = new MemoryStream();
+
+            var emitResult = compilation.Emit(output, pdbStream, xmlDocumentationStream: null, win32Resources: null);
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: Shouldn't we verify xml as well as PDB?

File: src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs (hunk 6 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: I agree with @agocke that 3 and 4 are not acceptable. When compilation fails no output should occur. That's not an invariant of the compiler we can change for this feature.

Comment (jaredpar) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: If there is no plan, or understood design, that will restore the compiler invariants then I think we need to consider option 1. This feature is still fresh and pulling it should impact a relatively small number of people. Also if it's not ready we should remove it before we ship .NET Core 3.0. We can work through the design separately, find the right one and put it back. 

If this was an edge case or if the change necessary to restore the invariants were understood I'd be more content to treat this as a bug and fix in the next release. Reading through the thread though it seems there is not an understanding of how this would be fixed just an expectation that it will be complex.

Comment (mavasani) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: Investigated further and https://github.com/dotnet/roslyn/pull/37948/commits/2c33e99763aa870ed56935a31ccde1e87cff3522 should give the desired behavior and has the requested unit tests.

File: src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs [hunk 8]
```diff
@@ -11271,6 +11271,72 @@ class C { }";
...
+            Assert.Contains(expectedOutput, output);
+
+            string binaryPath = Path.Combine(dir.Path, "temp.dll");
+            Assert.True(File.Exists(binaryPath) == !warnAsError);
+
+            string pdbPath = Path.Combine(dir.Path, pdbName);
+            Assert.True(File.Exists(pdbPath) == !warnAsError);
+
+            string xmlDocFilePath = Path.Combine(dir.Path, docName);
+            Assert.True(File.Exists(xmlDocFilePath) == !warnAsError);
```
Comment (mavasani) [inline src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs]: Validation of no binary, pdb and xml doc file generated on /warnaserror breaking build from command line execution.

File: src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs [hunk 9]
```diff
@@ -5163,5 +5163,66 @@ public void CompileAndVerifyModuleIncludesAllModules()
...
+            using var output = new MemoryStream();
+            using var pdbStream = new MemoryStream();
+            using var xmlDocumentationStream = new MemoryStream();
+
+            var emitResult = compilation.Emit(output, pdbStream, xmlDocumentationStream, win32Resources: null);
+            Assert.False(emitResult.Success);
+
+            Assert.Equal(0, output.Length);
+            Assert.Equal(0, pdbStream.Length);
+            Assert.Equal(0, xmlDocumentationStream.Length);
```
Comment (mavasani) [inline src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: Validation of no binary, pdb and xml doc generated on /warnaserror breaking build from Emit API invocation.

File: src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs (hunk 6 above)
Comment (mavasani) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: @agocke @jaredpar My [commit](https://github.com/dotnet/roslyn/commit/2c33e99763aa870ed56935a31ccde1e87cff3522) to establish your requested invariant leads to unit test failures in existing compiler unit tests which are validating xml documentation in presence of compiler errors:

1. [WRN_XMLDocInsideMethod](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic.Symbol.UnitTests/DocumentationComments/DocCommentTests.vb,4191)
2. [WRN_XMLDocInsideMethod_NoError](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic.Symbol.UnitTests/DocumentationComments/DocCommentTests.vb,4262)
3. [ExtendedCref_BinaryOperator](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic.Symbol.UnitTests/DocumentationComments/DocCommentTests.vb,10726):  Failing scenario is specifically [this](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic.Symbol.UnitTests/DocumentationComments/DocCommentTests.vb,10798) one where test expects xml doc output for input code with errors.

These unit tests haven't changed for quite a while, so it seems the invariant has been broken for some time, long before the diagnostic suppressors change. Let me know if you want me to fix these unit tests in this PR or revert my last commit and file a separate tracking issue for compiler team to restore the invariant.

Comment (agocke) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: Looks like Those methods are calling `Emit` directly. Sounds like we need to enumerate the expected behavior for all of these circumstances for both VB and C# and decide exactly how we want to treat each case (as a bug or as expected behavior).

Comment (agocke) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: Yes, looking the code, `Emit` does one thing, `CommonCompiler` does another. I see some VB tests that verify the Emit behavior, but not C# tests. Did you find any?

Comment (mavasani) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: Nope, only VB compiler tests. I can tweak my change to just bail out from the doc file generation in Common compiler, but let the Emit API still generate the documentation in the provided xmlDocStream. Alternatively, we can avoid any xml doc generation in presence of errors for both scenarios and just fix the unit tests.

Comment (agocke) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: Since this is an ask mode change, let's keep the current behavior, add a comment, and file a bug.

Comment (agocke) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: Also, it looks like there's a failure in NoWarnAndWarnAsError_WarningDiagnostic. Have you figured out what's going on there?

Comment (agocke) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: And we should add tests to verify all of this behavior.

Comment (mavasani) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: > Since this is an ask mode change, let's keep the current behavior, add a comment, and file a bug.

Just to confirm - we will ensure that common compiler code path does not generate xml doc file, but Emit API invocation generates xml documentation so there are no unit test changes required + file a compiler issue to revisit this behavior. Is that correct understanding?

> Also, it looks like there's a failure in NoWarnAndWarnAsError_WarningDiagnostic. Have you figured out what's going on there?

Yes, my last commit bails out completely prior to xml doc generation in presence of errors. This leads to us skipping reporting any analyzer diagnostics. I was planning to restore the original behavior of reporting analyzer diagnostics even in presence of compiler errors by just guarding xml doc generation but not returning. That should fix those unit tests.

Comment (agocke) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: > Is that correct understanding?

Yup sounds right to me.

Comment (agocke) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: Note: it still doesn't seem to generate a PE file after Emit (which is weird) but also seems like existing behavior.

Comment (mavasani) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: Filed https://github.com/dotnet/roslyn/issues/37996.

**Comment by mavasani** [comment]
@agocke @AlekseyTs any further feedback?

**Comment by mavasani** [comment]
Ping for reviews..

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs [hunk 10]
```diff
@@ -1038,25 +1069,23 @@ private int RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, Cancellat
...
                             // TryComplete, we may miss diagnostics.
                             var hostDiagnostics = analyzerDriver.GetDiagnosticsAsync(compilation).Result;
-                            diagnostics.AddRange(hostDiagnostics);
 
-                            if (!diagnostics.IsEmptyWithoutResolution)
-                            {
-                                // Apply diagnostic suppressions for analyzer and/or compiler diagnostics from diagnostic suppressors.
-                                analyzerDriver.ApplyProgrammaticSuppressions(diagnostics, compilation);
+                            // Apply diagnostic suppressions for analyzer compiler diagnostics from diagnostic suppressors.
+                            hostDiagnostics = analyzerDriver.ApplyProgrammaticSuppressions(hostDiagnostics, compilation);
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: >hostDiagnostics = analyzerDriver.ApplyProgrammaticSuppressions(hostDiagnostics, compilation); [](start = 28, length = 93)

Are we making an assumption that any diagnostics reported after the previous ```ApplyProgrammaticSuppressions``` call added above cannot be elevated or suppressed? Can we assert that in some way so that a violation of the invariant is caught early? Alternatively, consider collecting diagnostics after that ```ApplyProgrammaticSuppressions``` call into a separate bag and combining it with ```hostDiagnostics``` for the purpose of this ```ApplyProgrammaticSuppressions``` call, then merging the result into ```diagnostics```.

File: src/Compilers/Core/Portable/Compilation/Compilation.cs [hunk 11]
```diff
@@ -2517,6 +2519,11 @@ internal void EnsureAnonymousTypeTemplates(CancellationToken cancellationToken)
                     privateKeyOpt = StrongNameKeys.PrivateKey;
                 }
 
+                if (!options.EmitMetadataOnly && CommonCompiler.HasUnsuppressedErrors(diagnostics))
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Compilation/Compilation.cs]: >CommonCompiler.HasUnsuppressedErrors(diagnostics) [](start = 49, length = 49)

Have we applied pragma suppression and other diagnostic filtering by this point? Where did we do this?

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 6)

File: src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs [hunk 12]
```diff
@@ -5163,5 +5162,95 @@ public void CompileAndVerifyModuleIncludesAllModules()
...
+    int _f;
+}";
+            var compilation = CreateCompilation(source, options: options);
+
+            using var output = new MemoryStream();
+            using var pdbStream = new MemoryStream();
+            using var xmlDocumentationStream = new MemoryStream();
+            using var win32ResourcesStream = compilation.CreateDefaultWin32Resources(versionResource: true, noManifest: false, manifestContents: null, iconInIcoFormat: null);
+
+            var emitResult = compilation.Emit(output, pdbStream, xmlDocumentationStream, win32ResourcesStream);
```
Comment (agocke) [inline src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: I see that the stream is passed, but I don't see any assertion of what the result is.

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs [hunk 13]
```diff
@@ -568,7 +566,7 @@ internal bool ReportDiagnostics(IEnumerable<DiagnosticInfo> diagnostics, TextWri
         /// non-error diagnostic were later elevated to an error through filtering (e.g., through
```
Comment (agocke) [inline src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: This statement seems wrong. The above explicitly says that these are only unsuppressable errors, so anything elevated to an error wouldn't affect this check.

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs [hunk 14]
```diff
@@ -964,6 +979,22 @@ private int RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, Cancellat
                             filterOpt: null,
                             cancellationToken: cancellationToken);
 
+                        // Prior to generating the xml documentation file,
+                        // we apply programmatic suppressions for compiler warnings from diagnostic suppressors.
+                        // If there are still any unsuppressed errors or warnings escalated to errors
+                        // then we bail out from generating the documentation file.
+                        // This maintains the compiler invariant that xml documentation file should not be
+                        // generated in presence of diagnostics that break the build.
+                        if (analyzerDriver != null && !diagnostics.IsEmptyWithoutResolution)
```
Comment (agocke) [inline src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: Here you check `!diagnostics.IsEmptyWithoutResolution` but below you don't. Why the difference?

File: src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs (hunk 12 above)
Comment (mavasani) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: What assertion are you expecting, given this is a [read-only](http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/Compilation.cs,2229) stream?

File: src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs (hunk 10 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs]: I have taken the latter approach, but implemented the fix in the analyzer driver to avoid each caller of `ApplyProgrammaticSuppressions` having to track processed diagnostics.

File: src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs (hunk 12 above)
Comment (agocke) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: Doesn't Emit manipulate the resource settings in the module builder based on the input resources? Shouldn't we verify that they were/weren't changed in the presence of errors?

Comment (agocke) [reply src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs]: Ah, never mind, that's not visible here. I was looking at the wrong API. In that case we can probably ignore the resource stream.

File: src/Compilers/Core/Portable/Compilation/Compilation.cs (hunk 11 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/Compilation/Compilation.cs]: I believe diagnostic filtering is applied towards the end of each of the compilation stages. For example, applied [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Compilation/CSharpCompilation.cs,2689) for `CompileMethods`, applied [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Compilation/CSharpCompilation.cs,2732) for `GenerateResourcesAndDocumentationComments` (also verified identical implementation in VB compilation)

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs [hunk 15]
```diff
@@ -168,6 +173,7 @@ protected AnalyzerDriver(ImmutableArray<DiagnosticAnalyzer> analyzers, AnalyzerM
             _isGeneratedCode = (tree, ct) => GeneratedCodeUtilities.IsGeneratedCode(tree, isComment, ct);
             _hasDiagnosticSuppressors = this.Analyzers.Any(a => a is DiagnosticSuppressor);
             _programmaticSuppressions = _hasDiagnosticSuppressors ? new ConcurrentSet<Suppression>() : null;
+            _diagnosticsProcessedForProgrammaticSuppressions = _hasDiagnosticSuppressors ? new ConcurrentSet<Diagnostic>() : null;
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: >new ConcurrentSet<Diagnostic>() [](start = 91, length = 31)

Should we use ReferenceEqualityComparer.Instance for this set?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs [hunk 16]
```diff
@@ -631,42 +637,53 @@ private ImmutableArray<Diagnostic> ApplyProgrammaticSuppressionsCore(ImmutableAr
...
+                var builder = ArrayBuilder<Diagnostic>.GetInstance(reportedDiagnostics.Length);
+                ImmutableDictionary<Diagnostic, ProgrammaticSuppressionInfo> programmaticSuppressionsByDiagnostic = createProgrammaticSuppressionsByDiagnosticMap(_programmaticSuppressions);
+                foreach (var diagnostic in reportedDiagnostics)
                 {
-                    builder.Add(diagnostic);
+                    if (programmaticSuppressionsByDiagnostic.TryGetValue(diagnostic, out var programmaticSuppressionInfo))
+                    {
+                        Debug.Assert(suppressableDiagnostics.Contains(diagnostic));
+                        Debug.Assert(!diagnostic.IsSuppressed);
+                        builder.Add(diagnostic.WithProgrammaticSuppression(programmaticSuppressionInfo));
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: >diagnostic.WithProgrammaticSuppression(programmaticSuppressionInfo) [](start = 36, length = 67)

It is probably worth adding an assert that this diagnostic IsSuppressed now.
