### PR TITLE
UseLocalFunction should not report diagnostics on invalid decleration code

### LINKED ISSUE #29793: CSharpUseLocalFunctionCodeFixProvider failed with InvalidCastException
In the following code, drop the lightbulb at the _ in "firstAction":

``` C#
        public async Task ExecuteUnderLockAsync_AvoidsOverlappingActions()
        {
            var firstEntered = new AsyncManualResetEvent();
            var firstRelease = new AsyncManualResetEvent();
            var secondEntered = new AsyncManualResetEvent();

            var instance = CreateInstance();

            Func<Task> f_irstAction = () =>
            {
                return instance.ExecuteUnderLockAsync(async (ct) =>
                {
                    firstEntered.Set();
                    await firstRelease;
                }, CancellationToken.None);
            });
        }
```

```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.VariableDeclarationSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.LocalDeclarationStatementSyntax'.
   at async Microsoft.CodeAnalysis.CSharp.UseLocalFunction.CSharpUseLocalFunctionCodeFixProvider.FixAllAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

### PR DESCRIPTION
**Pull request by ryzngard**
If the declaration contains invalid code the analyzer should not report any fixes, they are not guaranteed to be correct. 

Fixes #29793

### CODE REVIEW

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -106,6 +106,14 @@ private void SyntaxNodeAction(SyntaxNodeAnalysisContext syntaxContext, INamedTyp
                 return;
             }
 
+            // If there are compiler diagnostics on the declaration we can't reliably
+            // tell that the refactoring will be accurate, so don't provide any
+            // code diagnostics
+            if (localDeclaration.GetDiagnostics().Any())
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionDiagnosticAnalyzer.cs]: you want to make sure it's only errors.  this will trigger for warnings as well, and we do not want that to limit this feature.

Comment (genlu) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionDiagnosticAnalyzer.cs]: I don't think you can suppress compiler errors., so a check probaably isn't necessary.

You should be able to find/add an analyzer that reports warnings and add it to the compilation of the test. See https://github.com/dotnet/roslyn/tree/master/src/Test/Utilities/Portable/Diagnostics/CommonDiagnosticAnalyzers.cs

Comment (ryzngard) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionDiagnosticAnalyzer.cs]: Since I'm only checking the declaration, none of those are valid... Adding a `#warning` above it works as a compiler diagnostic. TIL

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionDiagnosticAnalyzer.cs]: > Since I'm only checking the declaration, none of those are valid... 

the primary issue i have is that you're just disabling due to a syntactic diagnostic.  But a syntactic diagnostic doesn't mean there is a problem. it just means a diagnostic placed on the syntax.  if you want to say "disbale when there's something wrong syntactically" then you need to check if it's actually an error.

File: src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionDiagnosticAnalyzer.cs [hunk 2]
```diff
@@ -106,10 +106,10 @@ private void SyntaxNodeAction(SyntaxNodeAnalysisContext syntaxContext, INamedTyp
                 return;
             }
 
-            // If there are compiler diagnostics on the declaration we can't reliably
+            // If there are compiler error on the declaration we can't reliably
             // tell that the refactoring will be accurate, so don't provide any
             // code diagnostics
-            if (localDeclaration.GetDiagnostics().Any())
+            if (localDeclaration.GetDiagnostics().Any(d => d.Severity == DiagnosticSeverity.Error))
```
Comment (genlu) [inline src/Features/CSharp/Portable/UseLocalFunction/CSharpUseLocalFunctionDiagnosticAnalyzer.cs]: You could use `DefaultSeverity` instead to filter out diagnostics whose severity is changed by user. But I'm fine either way here.

**Comment by ryzngard** [comment]
@jinujoseph @vatsalyaagrawal this is ready for P3

**Comment by jinujoseph** [comment]
This will now ship as part of P4
