### PR TITLE
Report error when missing type arguments in extension methods

### LINKED ISSUE #13617: Invalid generic extension call does not report error and then fail to emit module.
**Version Used**: 

VS2015 Update 3 with .NET Core Tools Preview 2

**Steps to Reproduce**:
1. Create a generic extension method which return `T` e.g. `public static T Foo<T>(this object obj) => default(T)`
2. Call it somewhere without specifying `T` and invoke any arbitrary member name, like `"abc".Foo<>().FooValue`
3. Compile.

**Expected Behavior**:

Compilation fail with proper error message.

**Actual Behavior**:

No typical compilation error reported but fail to build with error CS7038 : Fail to emit module

**Sample class**:

```
public static class FooExtensions
{
    public static T Foo<T>(this object obj) => default(T);
}

public class Class1
{
    public void Test()
    {
        var a = "a".Foo<>().Run();
        // the line below fail to compile as expected
        //var b = FooExtensions.Foo<>().Abc;
    }
}
```

https://dotnetfiddle.net/JvacT3

### PR DESCRIPTION
**Pull request by OmarTawfik**
Fixes #13617 
@dotnet/roslyn-compiler

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 1]
```diff
@@ -5264,14 +5264,21 @@ private BoundExpression MakeMemberAccessValue(BoundExpression expr, DiagnosticBa
...
                         typeArguments,
                         boundLeft,
                         rightName,
                         lookupResult.Symbols.All(s => s.Kind == SymbolKind.Method) ? lookupResult.Symbols.SelectAsArray(s_toMethodSymbolFunc) : ImmutableArray<MethodSymbol>.Empty,
                         lookupResult,
                         flags);
+
+                    if (!boundMethodGroup.HasErrors && boundMethodGroup.ResultKind == LookupResultKind.Empty && typeArgumentsSyntax.Any(SyntaxKind.OmittedTypeArgument))
+                    {
+                        Error(diagnostics, ErrorCode.ERR_BadArity, node, rightName, MessageID.IDS_MethodGroup.Localize(), typeArgumentsSyntax.Count);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: I'm surprised by the localization here. Other errors reported (see `BindMemberAccessReportError` below) don't seem to do this.
Also, maybe this check should replaced by a call to `BindMemberAccessReportError` and the logic added there?

Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: @jcouv from what I can tell, `BindMemberAccessReportError` is called on lookup errors that are generated elsewhere. But there is none here. We're constructing a new diagnostics object and reporting it (check other calls to `Error()` in the file).
Am I missing something? why the surprise to see this?

Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: From talking to Omar, the `Localize()` call is also used in other places where ERR_BadArity is reported.
Also, the `BindMemberAccessReportError` requires a `lookupError` parameter (a `DiagnosticInfo`), so it won't help.

#Closed

**Comment by OmarTawfik** [comment]
@jaredpar @jcouv can I get sign offs?

**Comment by OmarTawfik** [comment]
@MattGertz Can we please get RC3 approval for this?

**Comment by jaredpar** [comment]
@MattGertz for ask mode approval

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 2]
```diff
@@ -5264,14 +5264,21 @@ private BoundExpression MakeMemberAccessValue(BoundExpression expr, DiagnosticBa
...
+                    var boundMethodGroup = new BoundMethodGroup(
                         node,
                         typeArguments,
                         boundLeft,
                         rightName,
                         lookupResult.Symbols.All(s => s.Kind == SymbolKind.Method) ? lookupResult.Symbols.SelectAsArray(s_toMethodSymbolFunc) : ImmutableArray<MethodSymbol>.Empty,
                         lookupResult,
                         flags);
+
+                    if (!boundMethodGroup.HasErrors && boundMethodGroup.ResultKind == LookupResultKind.Empty && typeArgumentsSyntax.Any(SyntaxKind.OmittedTypeArgument))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: >if (!boundMethodGroup.HasErrors && boundMethodGroup.ResultKind == LookupResultKind.Empty && typeArgumentsSyntax.Any(SyntaxKind.OmittedTypeArgument)) [](start = 20, length = 148)

@OmarTawfik Why do we need this special case here only when searchExtensionMethodsIfNecessary is true? It feels like the error should be reported when we do lookup instead.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: >typeArgumentsSyntax.Count [](start = 122, length = 25)

It feels like this error could be misleading. It uses count from syntax, which, in case of ```<>```, is always 1, regardless what the actual arity of the target method. We should test scenario with a method that has two and more type parameters.
