### PR TITLE
Disallow methods with bodies in ComImport interfaces.

### LINKED ISSUE #64238: static interface methods not emitted when interface marked ComImport
Not sure if this is a bug, an unexpected scenario, or a self-inflicted "just don't do that" thing, but: consider interface:

``` c#
public interface IFoo
{
    void Bar();
    static void Blap() => System.Console.WriteLine("IFoo.Blap");
}
```

This works fine; we can call `IFoo.Blap();`

Now imagine we decorate `IFoo` with `[ComImport]` and `[Guid]` - *because we can* (see below); at this point, the compiler *no longer emits the method body*; instead of

``` msil
    .method public hidebysig static 
        void Blap () cil managed 
    {
        // Method begins at RVA 0x2067
        // Code size 11 (0xb)
        .maxstack 8

        IL_0000: ldstr "IFoo.Blap"
        IL_0005: call void [System.Console]System.Console::WriteLine(string)
        IL_000a: ret
    } // end of method IFoo::Blap
```

we get:

``` msil
    .method public hidebysig static 
        void Blap () cil managed 
    {
    } // end of method IFoo::Blap
```

If we run the code, we now get a `TypeLoadException`, citing

> Could not load type 'IFoo' from assembly '(whatever)' because the method 'Blap' has no implementation (no RVA).

This seems ... unexpected. Not sure if this is an internal limitation due to some legacy feature of `[ComImport]`, or ... what! And yes, I acknowledge that anything under `System.Runtime.InteropServices` is basically "there are no rules here" territory.

Proposals:

1. make it emit the method body (presumably there's an `if` test that is hitting an unanticipated combination of scenarios), or
2. make it emit a compiler error/warning that this scenario is not going to work

---

As for why we might want to do this... well, historically, before static interface methods existed, the following is a sneaky way to allow instantiation of interfaces (perhaps when the concrete type is generated and unobvious - think "service proxies" etc). A `static IFoo Create() {...}` method would also have worked, but is both TFM and langver dependent, where-as `[CoClass]` et al work *all* the way back.

``` c#
IFoo obj = new();
obj.Bar();
// IFoo.Blap();

[global::System.Runtime.InteropServices.ComImport]
[global::System.Runtime.InteropServices.Guid("00112233-4455-6677-8899-aabbccddeeff")]
[global::System.Runtime.InteropServices.CoClass(typeof(Foo))]
interface IFoo
{
    void Bar();
    // static void Blap() => Console.WriteLine("IFoo.Blap");
}
class Foo : IFoo
{
    void IFoo.Bar() => Console.WriteLine("Foo.Bar");
}
```

[Here's a sharplab of the same](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoTBJAYge3wAJ9gArIgXiJgFMB3ACgEoBuTUsgOgCEIAnFuwx5CvADYQADkMyYA2gHNxpCOJAgEKLgCUArjAAuUMLS7YjtfvikBlKwDcoAY1oBnLgGF8YbGCn4/IYAugrKquqa2vpGJmYWhlY29vxOrh4A4npQACaMAEQADIUoKEhIAMwVALQALLUArA3VAGwtAOzt1QAc3QCcfdUQEMDAzs45ObS0AGYz+cyhGEoqwGoaWroGxqbmltZ2ji7uXviekm5ujIYAnlK0+DOMBPjMi5iwifwzEK5EovhMABvTBEMFEBC1Ih8QRsUHgrQtCFQniSGTMKgAPghKD6BQBEmkC2EAF9MMgiC8iCB/i9gfCwZDaWIYSwsTi8fkXrwBMTMCSgA=) - see the reversed C#:

``` c#
[ComImport]
[Guid("00112233-4455-6677-8899-aabbccddeeff")]
[CoClass(typeof(Foo))]
internal interface IFoo
{
    void Bar();

    static void Blap();
}
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #64238.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

File: src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs [hunk 1]
```diff
@@ -7232,9 +7232,9 @@ public async Task TestDoNotReorderComImportMembers_02()
 [Guid(""00000000-0000-0000-0000-000000000000"")]
 interface IComInterface
 {
-    void MOverload() { }
-    void X() { }
-    void MOverload(int i) { }
+    void {|CS0423:MOverload|}() { }
```
Comment (jasonmalinowski) [inline src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs:7235]: I'm not sure why this test exists in the IDE at all (or at least with the method name it has) -- the point of the test that was originally cloned in #17927 was that the ordering of the generated class members should (ideally) match the COM import order. But since the test isn't generating any methods at all it's moot -- all this does is assert we don't crash in this case.

Comment (AlekseyTs) [reply src/EditorFeatures/CSharpTest/ImplementInterface/ImplementInterfaceTests.cs:7235]: > But since the test isn't generating any methods at all it's moot 

It does generate property.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 1)

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

**Comment by jaredpar** [comment]
@333fred PTAL

**Review by 333fred — APPROVED** [review]
