### PR TITLE
Adjust an assert in EmitArgument

### LINKED ISSUE #75035: Assert failure when building runtime: argument captured byref
**Version Used**: 2985e58b62a4ab98455653bb6754ab9961a5e6fb

Complog is [here](https://github.com/user-attachments/files/16937640/Build.zip), rename to `Build.complog` after downloading. Failed project is `System.Numerics.Tensors.csproj (net9.0)`. Assert is as follows:

```
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error : Process terminated. Assertion failed. [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error : passing args byref should not clone them into temps [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitArgument(BoundExpression argument, RefKind refKind) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:line 736 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitArguments(ImmutableArray`1 arguments, ImmutableArray`1 parameters, ImmutableArray`1 argRefKindsOpt) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:line 958 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStaticCallExpression(BoundCall call, UseKind useKind) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:line 1662 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitCallExpression(BoundCall call, UseKind useKind) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:line 1625 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpressionCore(BoundExpression expression, Boolean used) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:line 103 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:line 67 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitArgument(BoundExpression argument, RefKind refKind) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:line 720 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitArguments(ImmutableArray`1 arguments, ImmutableArray`1 parameters, ImmutableArray`1 argRefKindsOpt) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:line 958 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStaticCallExpression(BoundCall call, UseKind useKind) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:line 1662 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitCallExpression(BoundCall call, UseKind useKind) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:line 1625 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpressionCore(BoundExpression expression, Boolean used) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:line 103 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:line 67 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitAssignmentValue(BoundAssignmentOperator assignmentOperator) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:line 2984 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitAssignmentExpression(BoundAssignmentOperator assignmentOperator, UseKind useKind) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:line 2555 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpressionCore(BoundExpression expression, Boolean used) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:line 99 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpressionCoreWithStackGuard(BoundExpression expression, Boolean used) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:line 83 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:line 71 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs:line 60 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatementAndCountInstructions(BoundStatement statement) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs:line 121 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitSequencePointStatement(BoundSequencePointWithSpan node) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/CodeGenerator.cs:line 408 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs:line 44 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatements(ImmutableArray`1 statements) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs:line 788 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitUninstrumentedBlock(BoundBlock block) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs:line 757 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitBlock(BoundBlock block) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs:line 674 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs:line 32 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatementList(BoundStatementList list) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs:line 129 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs:line 64 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.GenerateImpl() in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/CodeGenerator.cs:line 280 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.Generate(Boolean& hasStackalloc) in /workspaces/roslyn/src/Compilers/CSharp/Portable/CodeGen/CodeGenerator.cs:line 209 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.GenerateMethodBody(PEModuleBuilder moduleBuilder, MethodSymbol method, Int32 methodOrdinal, BoundStatement block, ImmutableArray`1 lambdaDebugInfo, ImmutableArray`1 orderedLambdaRuntimeRudeEdits, ImmutableArray`1 closureDebugInfo, ImmutableArray`1 stateMachineStateDebugInfos, StateMachineTypeSymbol stateMachineTypeOpt, VariableSlotAllocator variableSlotAllocatorOpt, BindingDiagnosticBag diagnostics, DebugDocumentProvider debugDocumentProvider, ImportChain importChainOpt, Boolean emittingPdb, ImmutableArray`1 codeCoverageSpans, AsyncForwardEntryPoint entryPointOpt) in /workspaces/roslyn/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 1556 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in /workspaces/roslyn/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 1305 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) in /workspaces/roslyn/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 530 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass25_0.<CompileNamedTypeAsync>b__0() in /workspaces/roslyn/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 432 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in /workspaces/roslyn/src/Compilers/Core/Portable/InternalUtilities/UICultureUtilities.cs:line 139 [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at System.Threading.ThreadPoolWorkQueue.Dispatch() [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
/home/vscode/.nuget/packages/microsoft.net.compilers.toolset/4.12.0-dev/tasks/netcore/Microsoft.CSharp.Core.targets(89,5): error :    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() [/workspaces/runtime/src/libraries/System.Numerics.Tensors/src/System.Numerics.Tensors.csproj::TargetFramework=net9.0]
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #75035.

### CODE REVIEW

**Review by 333fred — APPROVED** [review]

File: src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs [hunk 1]
```diff
@@ -733,7 +733,8 @@ private void EmitArgument(BoundExpression argument, RefKind refKind)
                     if (unexpectedTemp != null)
                     {
                         // interestingly enough "ref dynamic" sometimes is passed via a clone
-                        Debug.Assert(argument.Type.IsDynamic(), "passing args byref should not clone them into temps");
+                        // receiver of a ref field can be cloned too
+                        Debug.Assert(argument.Type.IsDynamic() || argument is BoundFieldAccess { FieldSymbol.RefKind: RefKind.Ref }, "passing args byref should not clone them into temps");
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:737]: Is it possible to get here with `FieldSymbol.RefKind: RefKind.RefReadonly` as well?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:737]: > Is it possible to get here with `FieldSymbol.RefKind: RefKind.RefReadonly` as well?

I think we will end up in the `case` above. I added a test for the scenario and it confirmed the theory. However, I am going to relax the assert anyway, just in case.

**Review by RikkiGibson — APPROVED** [review]

**Review by 333fred — APPROVED** [review]
