### PR TITLE
Add code fix for CS0513

### LINKED ISSUE #31833: Code fix for CS0513 to make class abstract
```c#
class C
{
    public abstract void M(); // CS0513: 'C.M()' is abstract but it is contained in non-abstract class 'C'
}
```
It would be nice to have a code fix to make `C` abstract.

### PR DESCRIPTION
**Pull request by Evangelink**
Make enclosing class abstract when member does not have body.

Fix #31833

### CODE REVIEW

File: src/Features/CSharp/Portable/MakeClassAbstract/CSharpMakeClassAbstractCodeFixProvider.cs [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+    internal sealed class CSharpMakeClassAbstractCodeFixProvider : AbstractMakeClassAbstractCodeFixProvider<ClassDeclarationSyntax>
+    {
+        public override ImmutableArray<string> FixableDiagnosticIds { get; } =
+               ImmutableArray.Create(
+                   "CS0513" // 'C.M()' is abstract but it is contained in non-abstract class 'C'
+               );
+
+        protected override bool IsValidMemberNode(SyntaxNode node)
+        {
+            switch (node.Kind())
```
Comment (Evangelink) [inline src/Features/CSharp/Portable/MakeClassAbstract/CSharpMakeClassAbstractCodeFixProvider.cs]: [cosmetic] Let me know if you prefer multiple if instead of this switch.

File: src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+        {
+            for (var i = 0; i < diagnostics.Length; i++)
+            {
+                var declaration = diagnostics[i].Location?.FindNode(cancellationToken);
+
+                if (IsValidMemberNode(declaration))
+                {
+                    var enclosingClass = declaration.FirstAncestorOrSelf<TClassDeclarationSyntax>();
+                    editor.ReplaceNode(enclosingClass,
+                        (currentClassDeclaration, generator) => generator.WithModifiers(currentClassDeclaration, DeclarationModifiers.Abstract));
```
Comment (Evangelink) [inline src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs]: Is it better to check it's not already having the `abstract` modifier?

File: src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+        protected sealed override Task FixAllAsync(Document document, ImmutableArray<Diagnostic> diagnostics, SyntaxEditor editor,
+            CancellationToken cancellationToken)
+        {
+            for (var i = 0; i < diagnostics.Length; i++)
+            {
+                var declaration = diagnostics[i].Location?.FindNode(cancellationToken);
+
+                if (IsValidMemberNode(declaration))
+                {
+                    var enclosingClass = declaration.FirstAncestorOrSelf<TClassDeclarationSyntax>();
```
Comment (Evangelink) [inline src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs]: `IsValidMemberNode` is already looking for the enclosing class but I wasn't a big fan of returning the class and a boolean from it so I have decided to duplicate the call.

File: src/Features/CSharp/Portable/MakeClassAbstract/CSharpMakeClassAbstractCodeFixProvider.cs [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+{
+    [ExportCodeFixProvider(LanguageNames.CSharp, Name = nameof(CSharpMakeClassAbstractCodeFixProvider)), Shared]
+    internal sealed class CSharpMakeClassAbstractCodeFixProvider : AbstractMakeClassAbstractCodeFixProvider<ClassDeclarationSyntax>
+    {
+        public override ImmutableArray<string> FixableDiagnosticIds { get; } =
+               ImmutableArray.Create(
+                   "CS0513" // 'C.M()' is abstract but it is contained in non-abstract class 'C'
+               );
+
+        protected override bool IsValidMemberNode(SyntaxNode node)
```
Comment (Evangelink) [inline src/Features/CSharp/Portable/MakeClassAbstract/CSharpMakeClassAbstractCodeFixProvider.cs]: I have just noticed that `node` could be `null` and this is not handled. I will push a separate commit for this.

File: src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs [hunk 5]
```diff
@@ -0,0 +1,60 @@
...
+using System.Threading;
+using System.Threading.Tasks;
+using Microsoft.CodeAnalysis.CodeActions;
+using Microsoft.CodeAnalysis.CodeFixes;
+using Microsoft.CodeAnalysis.Editing;
+using Microsoft.CodeAnalysis.Shared.Extensions;
+
+namespace Microsoft.CodeAnalysis.MakeClassAbstract
+{
+    internal abstract class AbstractMakeClassAbstractCodeFixProvider<TClassDeclarationSyntax> : SyntaxEditorBasedCodeFixProvider
```
Comment (Evangelink) [inline src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs]: Is it better not to have generic and to have an `abstract` method to get the enclosing class declaration?

File: src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs [hunk 6]
```diff
@@ -0,0 +1,162 @@
...
+            await TestMissingInRegularAndScriptAsync(
+@"
+public class Foo
+{
+    public abstract int P
+    {
+        [|get|] { return 1; }
+    }
+}");
+        }
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs]: can you add a test for events?

File: src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs [hunk 7]
```diff
@@ -0,0 +1,162 @@
...
+{
+    using System;
+
+    public abstract class Foo
+    {
+        public abstract void M();
+        public abstract object P { get; set; }
+        public abstract object this[object o] { get; set; }
+    }
+}");
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs]: can you add a fix-all tests where there are multiple classes?

File: src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs (hunk 6 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs]: add tests where there are no existing modifiers on the class.

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs]: add test where the class has no mods and a doc comment.

File: src/Features/CSharp/Portable/MakeClassAbstract/CSharpMakeClassAbstractCodeFixProvider.cs [hunk 8]
```diff
@@ -0,0 +1,47 @@
...
+                    {
+                        return false;
+                    }
+                    break;
+
+                default:
+                    return false;
+            }
+
+            return node.FirstAncestorOrSelf<ClassDeclarationSyntax>() != null;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/MakeClassAbstract/CSharpMakeClassAbstractCodeFixProvider.cs]: this doesn't work in a case like this:

```c#
class C
{
    struct S { abstract void Foo(); }
}
```

File: src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs [hunk 9]
```diff
@@ -0,0 +1,60 @@
...
+        where TClassDeclarationSyntax : SyntaxNode
+    {
+        internal sealed override CodeFixCategory CodeFixCategory => CodeFixCategory.Compile;
+
+        public sealed override Task RegisterCodeFixesAsync(CodeFixContext context)
+        {
+            if (context.Diagnostics.Length == 1 &&
+                IsValidMemberNode(context.Diagnostics[0].Location?.FindNode(context.CancellationToken)))
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs]: you use `.?` here, indicating that `null` coudl be passed to `IsValidMemberNode`.  But `IsValidMemberNode` is not null safe.

also, enable NRT in all these files with `#nullable enable` at the top.  thanks!

File: src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs (hunk 2 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs]: that should be checked during  RegisterCodeFixesAsync

File: src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs (hunk 7 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs]: add tests with nested classes.

File: src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs (hunk 2 above)
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs]: won't this blow away other modifiers?  don't you need to 'union' this with the existing mods?

File: src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs [hunk 10]
```diff
@@ -0,0 +1,60 @@
...
+                    var enclosingClass = declaration.FirstAncestorOrSelf<TClassDeclarationSyntax>();
+                    editor.ReplaceNode(enclosingClass,
+                        (currentClassDeclaration, generator) => generator.WithModifiers(currentClassDeclaration, DeclarationModifiers.Abstract));
+                }
+            }
+
+            return Task.CompletedTask;
+        }
+
+        protected abstract bool IsValidMemberNode(SyntaxNode node);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs]: please place abstract members below the cosntructor and above non-abstract members.

File: src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs [hunk 11]
```diff
@@ -0,0 +1,60 @@
...
+
+        private class MyCodeAction : CodeAction.DocumentChangeAction
+        {
+            public MyCodeAction(Func<CancellationToken, Task<Document>> createChangedDocument)
+                : base(FeaturesResources.Make_class_abstract, createChangedDocument, nameof(AbstractMakeClassAbstractCodeFixProvider<TClassDeclarationSyntax>))
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs]: just pass in `FeaturesResources.Make_class_abstract` as the equivalence key.

**Comment by CyrusNajmabadi** [comment]
hey @Evangelink Thanks for the PR!

**Comment by CyrusNajmabadi** [comment]
Missing VB impl and tests currently.  Can you add those?

File: src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs (hunk 11 above)
Comment (Evangelink) [reply src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs]: Ok. In the my other code fix PR I used the resource and was asked to use the class name, would you mind telling me if there is any difference in using one or the other? It might be nice (and I am willing to help) to have a standard way of doing this even if there are some criteria to chose between the solution.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs]: by and large, we just use the resource name.  So i'd prefer that for consistency :)

File: src/Features/CSharp/Portable/MakeClassAbstract/CSharpMakeClassAbstractCodeFixProvider.cs (hunk 8 above)
Comment (Evangelink) [reply src/Features/CSharp/Portable/MakeClassAbstract/CSharpMakeClassAbstractCodeFixProvider.cs]: Oh crap! I thought about that when I started to write the tests and then I forgot about it!

**Comment by Evangelink** [comment]
@CyrusNajmabadi I haven't added an impl for VB.NET because I couldn't find the equivalent error in `Errors.vb` looking for `abstract` or `mustinherit`. If you could point me to the  error, I'll gladly provide the impl.

File: src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs (hunk 2 above)
Comment (Evangelink) [reply src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs]: That was my thought at first but this seem to keep the existing modifiers and just apply the new one (with some validity check).

File: src/Features/CSharp/Portable/MakeClassAbstract/CSharpMakeClassAbstractCodeFixProvider.cs [hunk 12]
```diff
@@ -0,0 +1,59 @@
...
+using System.Collections.Immutable;
+using System.Composition;
+using Microsoft.CodeAnalysis.CodeFixes;
+using Microsoft.CodeAnalysis.CSharp.Syntax;
+using Microsoft.CodeAnalysis.MakeClassAbstract;
+
+namespace Microsoft.CodeAnalysis.CSharp.MakeClassAbstract
+{
+    [ExportCodeFixProvider(LanguageNames.CSharp, Name = nameof(CSharpMakeClassAbstractCodeFixProvider)), Shared]
+    internal sealed class CSharpMakeClassAbstractCodeFixProvider : AbstractMakeClassAbstractCodeFixProvider<ClassDeclarationSyntax>
```
Comment (Evangelink) [inline src/Features/CSharp/Portable/MakeClassAbstract/CSharpMakeClassAbstractCodeFixProvider.cs]: The generic argument is not mandatory, I could use `SyntaxNode` so let me know your preference.

File: src/Features/CSharp/Portable/MakeClassAbstract/CSharpMakeClassAbstractCodeFixProvider.cs [hunk 13]
```diff
@@ -0,0 +1,59 @@
...
+    {
+        public override ImmutableArray<string> FixableDiagnosticIds { get; } =
+               ImmutableArray.Create(
+                   "CS0513" // 'C.M()' is abstract but it is contained in non-abstract class 'C'
+               );
+
+        protected override bool IsValidRefactoringContext(SyntaxNode? node, out ClassDeclarationSyntax? classDeclaration)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/MakeClassAbstract/CSharpMakeClassAbstractCodeFixProvider.cs]: add [NotNullWhen(true)] attr.

File: src/Features/CSharp/Portable/MakeClassAbstract/CSharpMakeClassAbstractCodeFixProvider.cs (hunk 12 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/MakeClassAbstract/CSharpMakeClassAbstractCodeFixProvider.cs]: this is fine.

**Comment by CyrusNajmabadi** [comment]
Just experiment in VB to see waht you get.  For example, i tried this out:

image

And got htis error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	BC31411	'C' must be declared 'MustInherit' because it contains methods declared 'MustOverride'
```

**Comment by jcouv** [comment]
@vatsalyaagrawal I removed the Area-Compilers label as I don't see any compiler file change. Let me know if I missed something. Thanks

File: src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs [hunk 14]
```diff
@@ -0,0 +1,273 @@
...
+{
+    public class MakeClassAbstractTests : AbstractCSharpDiagnosticProviderBasedUserDiagnosticTest
+    {
+        internal override (DiagnosticAnalyzer, CodeFixProvider) CreateDiagnosticProviderAndFixer(Workspace workspace)
+            => (null, new CSharpMakeClassAbstractCodeFixProvider());
+
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsMakeClassAbstract)]
+        public async Task TestMethod()
+        {
+            await TestInRegularAndScript1Async(
```
Comment (mavasani) [inline src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs]: Can you add test for type with partial declarations? Should we add abstract modifier to all declarations or just the containing declaration from trigger diagnostic location?

File: src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs [hunk 15]
```diff
@@ -0,0 +1,59 @@
...
+    internal abstract class AbstractMakeClassAbstractCodeFixProvider<TClassDeclarationSyntax> : SyntaxEditorBasedCodeFixProvider
+        where TClassDeclarationSyntax : SyntaxNode
+    {
+        protected abstract bool IsValidRefactoringContext(SyntaxNode? node, out TClassDeclarationSyntax? classDeclaration);
+
+        internal sealed override CodeFixCategory CodeFixCategory => CodeFixCategory.Compile;
+
+        public sealed override Task RegisterCodeFixesAsync(CodeFixContext context)
+        {
+            if (context.Diagnostics.Length == 1 &&
```
Comment (mavasani) [inline src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs]: I don't believe a length check is required. I would suggest:

```csharp
   if (IsValidRefactoringContext(root.FindNode(context.Span), out _))
   {
      context.RegisterCodeFix(classDeclaration, ..., context.Diagnostics);
   }

```

File: src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs (hunk 2 above)
Comment (mavasani) [reply src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs]: Yes, the current behavior seems strange to me for a With method. Ideally it should overwrite, not merge. It is unlikely we would change the behavior though as it would be a breaking change.

Comment (Evangelink) [reply src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs]: @mavasani Well it can simply be overwrite as we need to keep the other modifiers or am I missing something?

File: src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs (hunk 14 above)
Comment (Evangelink) [reply src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs]: It's failing for `partial` but for me the issue comes from the `WithModifiers` method not doing a proper merge. The `SyntaxGenerator.Merge` method returns `public abstract` when merging `public partial` and `public abstract`. IMO it should return `public partial abstract`.

Comment (mavasani) [reply src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs]: Would it be possible to create a separate PR to fix the SyntaxGenerator, and wait for that to go in before taking this up? Alternatively, can you file an issue for the SyntaxGenerator merge, add the test with partial declarations and mark it as skipped with that issue? I am fine with either approach that works for you.

Comment (Evangelink) [reply src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs]: I would prefer the skip that would avoid too many extra master merges. I will create the ticket. Are you ok with keeping the `WithModifiers` or what is your idea?

Comment (mavasani) [reply src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs]: I think it is fine.

Comment (Evangelink) [reply src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs]: #41654

**Comment by mavasani** [comment]
@Evangelink can you please resolve conflicts and fix CI?

File: src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs (hunk 2 above)
Comment (Evangelink) [reply src/Features/Core/Portable/MakeClassAbstract/AbstractMakeClassAbstractCodeFixProvider.cs:43]: @mavasani so what do you want me to do here?

**Comment by Evangelink** [comment]
I have "fixed" the CI but I don't understand why so many cases do not work for vbnet (including the fixall), the implementation seems to match other codefix.

**Comment by Evangelink** [comment]
See #42814

File: src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs [hunk 16]
```diff
@@ -0,0 +1,299 @@
...
+using Microsoft.CodeAnalysis.CodeFixes;
+using Microsoft.CodeAnalysis.CSharp.MakeClassAbstract;
+using Microsoft.CodeAnalysis.Diagnostics;
+using Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics;
+using Microsoft.CodeAnalysis.Test.Utilities;
+using Xunit;
+
+namespace Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.MakeClassAbstract
+{
+    public class MakeClassAbstractTests : AbstractCSharpDiagnosticProviderBasedUserDiagnosticTest
```
Comment (mavasani) [inline src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs:15]: @Evangelink Can we instead just convert these tests to use the new test framework? Will that be too much work? That will avoid you having to add a public ctor for this code fixer and then suppressing `RS0033`.

File: src/Features/VisualBasic/Portable/MakeClassAbstract/VisualBasicMakeClassAbstractCodeFixProvider.vb [hunk 17]
```diff
@@ -0,0 +1,37 @@
...
+
+Imports System.Collections.Immutable
+Imports System.Composition
+Imports System.Diagnostics.CodeAnalysis
+Imports Microsoft.CodeAnalysis.CodeRefactorings
+Imports Microsoft.CodeAnalysis.MakeClassAbstract
+Imports Microsoft.CodeAnalysis.VisualBasic.Syntax
+
+Namespace Microsoft.CodeAnalysis.VisualBasic.MakeClassAbstract
+    <ExportCodeRefactoringProvider(LanguageNames.VisualBasic, Name:=NameOf(VisualBasicMakeClassAbstractCodeFixProvider)), [Shared]>
```
Comment (mavasani) [inline src/Features/VisualBasic/Portable/MakeClassAbstract/VisualBasicMakeClassAbstractCodeFixProvider.vb:13]: I believe this is causing the CI failures:

```suggestion
    <ExportCodeFixProvider(LanguageNames.VisualBasic, Name:=NameOf(VisualBasicMakeClassAbstractCodeFixProvider)), [Shared]>
```

File: src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs (hunk 16 above)
Comment (mavasani) [reply src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs:15]: If https://github.com/dotnet/roslyn/pull/40448/files#r450282581 addresses the CI, it is fine to skip changing the tests for this PR.

File: src/Features/VisualBasic/Portable/MakeClassAbstract/VisualBasicMakeClassAbstractCodeFixProvider.vb (hunk 17 above)
Comment (Evangelink) [reply src/Features/VisualBasic/Portable/MakeClassAbstract/VisualBasicMakeClassAbstractCodeFixProvider.vb:13]: OH MY GOSH! I would have never seen it v_v

File: src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs (hunk 16 above)
Comment (Evangelink) [reply src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs:15]: I have tried (if I got it right that the syntax is the same as for roslyn-analyzers) but I end-up with nuget errors: `NuGet.Protocol.Core.Types.FatalProtocolException : Unable to load the service index for source https://api.nuget.org/v3/index.json.`

Comment (mavasani) [reply src/EditorFeatures/CSharpTest/MakeClassAbstract/MakeClassAbstractTests.cs:15]: I think it is fine to not do this as part of this PR. You may want to file a follow-up issue with your questions. Also suggest looking at the existing tests which are already moved to new framework, for example: https://github.com/dotnet/roslyn/blob/master/src/Analyzers/CSharp/Tests/RemoveUnnecessaryImports/RemoveUnnecessaryImportsTests.cs
