### PR TITLE
Refine the set of NullableAnnotation values to the three speakable options

### LINKED ISSUE #33638: Incorrect nullability inferred with nested generics (nullable walker)
The following test should produce no diagnostics, but it produces diagnostics.

``` c#
        [Fact]
        public void TupleFromNestedGenerics()
        {
            var source =
@"public class G<T>
{
    public (T, U) M<U>(T t, U u) => (t, u);
}
public class C
{
    public (T, U) M<T, U>(T t, U u) => (t, u);
}
";
            var comp = CreateCompilation(new[] { source }, options: WithNonNullTypesTrue());
            comp.VerifyDiagnostics(
                // (3,37): warning CS8619: Nullability of reference types in value of type '(T t, U u)' doesn't match target type '(T, U)'.
                //     public (T, U) M<U>(T t, U u) => (t, u);
                Diagnostic(ErrorCode.WRN_NullabilityMismatchInAssignment, "(t, u)").WithArguments("(T t, U u)", "(T, U)").WithLocation(3, 37),
                // (7,40): warning CS8619: Nullability of reference types in value of type '(T t, U u)' doesn't match target type '(T, U)'.
                //     public (T, U) M<T, U>(T t, U u) => (t, u);
                Diagnostic(ErrorCode.WRN_NullabilityMismatchInAssignment, "(t, u)").WithArguments("(T t, U u)", "(T, U)").WithLocation(7, 40));
        }
```

### PR DESCRIPTION
**Pull request by gafter**
- Eliminate values of `NullableAnnotation` that are "unspeakable"
- Change the result of dynamic invocations to result in an oblivious state
- Simplify the code in a few places where we compute result annotations (TSWA and `TypeWithState` are capable of storing an annotation/state even for typeless expressions)

Fixes #33638 
Filed #33924 to fix the result state of `?:`

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs [hunk 1]
```diff
@@ -49,194 +47,96 @@ internal enum NullableFlowState : byte
...
-                annotation == NullableAnnotation.NotAnnotated ||
-                annotation == NullableAnnotation.Annotated;
+            return annotation == NullableAnnotation.Unknown;
         }
 
-        /// <summary>
-        /// This method projects nullable annotations onto a smaller set that can be expressed in source.
-        /// </summary>
-        public static NullableAnnotation AsSpeakable(this NullableAnnotation annotation, TypeSymbol type)
+        public static bool MaybeNull(this NullableFlowState state)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs]: >public static bool MaybeNull(this NullableFlowState state) [](start = 8, length = 58)

nit: this extension should be in `NullableFlowStateExtensions` not `NullableAnnotationExtensions`.

File: src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs [hunk 2]
```diff
@@ -49,194 +47,96 @@ internal enum NullableFlowState : byte
...
-            }
-
-            if (a == NullableAnnotation.Nullable || b == NullableAnnotation.Nullable)
-            {
-                return NullableAnnotation.Nullable;
-            }
-
-            return NullableAnnotation.Annotated;
-        }
+        private static int[] _permute = new[] { 1, 0, 2 };
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs]: >private static int[] _permute = new[] { 1, 0, 2 }; [](start = 8, length = 50)

This trick feels too clever (ie. hard to review). I think we should either write the Meet/Join in an expanded form, or we should re-order the enum entries.

File: src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs [hunk 3]
```diff
@@ -324,25 +224,6 @@ private TypeSymbolWithAnnotations(TypeSymbol defaultType, NullableAnnotation nul
             _extensions = extensions;
         }
 
-        public TypeSymbolWithAnnotations AsSpeakable()
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs]: >AsSpeakable [](start = 41, length = 11)

note: there is a mention of "unspeakable" in the design doc. Could you remove it too? Thanks

File: src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs [hunk 4]
```diff
@@ -577,14 +446,14 @@ public string ToDisplayString(SymbolDisplayFormat format = null)
             {
                 if (format.MiscellaneousOptions.IncludesOption(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier) &&
                     !IsNullableType() && !IsValueType &&
-                    (NullableAnnotation == NullableAnnotation.Annotated ||
-                     (NullableAnnotation == NullableAnnotation.Nullable && !TypeSymbol.IsTypeParameterDisallowingAnnotation())))
+                    (NullableAnnotation.IsAnnotated() ||
+                     (NullableAnnotation.IsAnnotated() && !TypeSymbol.IsTypeParameterDisallowingAnnotation())))
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs]: >NullableAnnotation.IsAnnotated() [](start = 22, length = 32)

redundant check

**Comment by jcouv** [comment]
>             NullableAnnotation mergeNullableAnnotation(TypeSymbol type, NullableAnnotation a, NullableAnnotation b)

I think `TSWA.MergeNullableAnnotation` can be used here, and this local function could be deleted.

---
Refers to: src/Compilers/CSharp/Portable/Symbols/Tuples/TupleTypeSymbol.cs:1520 in 0178fec. [](commit_id = 0178fec154162c000296962a1fe65a24b8cfc756, deletion_comment = False)

File: src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Types.cs [hunk 5]
```diff
@@ -98,13 +98,13 @@ private bool ShouldAddNullableAnnotation(TypeSymbolWithAnnotations typeOpt)
             else if (format.MiscellaneousOptions.IncludesOption(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier) &&
                 !typeOpt.IsNullableType() && !typeOpt.IsValueType &&
                 (typeOpt.NullableAnnotation == NullableAnnotation.Annotated ||
-                 (typeOpt.NullableAnnotation == NullableAnnotation.Nullable && !typeOpt.TypeSymbol.IsTypeParameterDisallowingAnnotation())))
+                 (typeOpt.NullableAnnotation == NullableAnnotation.Annotated && !typeOpt.TypeSymbol.IsTypeParameterDisallowingAnnotation())))
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/SymbolDisplay/SymbolDisplayVisitor.Types.cs]: >typeOpt.NullableAnnotation == NullableAnnotation.Annotated [](start = 18, length = 58)

nit: consider using `IsAnnotated()` to check

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 6]
```diff
@@ -2293,7 +2262,7 @@ public override BoundNode VisitConditionalOperator(BoundConditionalOperator node
                 else
                 {
                     visitResult = TypeSymbolWithAnnotations.Create(resultType,
-                                                                   convertedConsequenceResult.NullableAnnotation.JoinForFixingLowerBounds(convertedAlternativeResult.NullableAnnotation));
+                                                                   convertedConsequenceResult.NullableAnnotation.Join(convertedAlternativeResult.NullableAnnotation));
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >Join [](start = 113, length = 4)

not related to this PR: consider fixing atypical formatting

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 7]
```diff
@@ -73792,14 +73783,13 @@ static void F(C<object> x, C<object?>? y)
         }
 
         private readonly static NullableAnnotation[] s_AllNullableAnnotations = (NullableAnnotation[])Enum.GetValues(typeof(NullableAnnotation));
-        private readonly static NullableAnnotation[] s_AllSpeakableNullableAnnotations = new[] { NullableAnnotation.Unknown, NullableAnnotation.NotAnnotated, NullableAnnotation.Annotated };
         private readonly static NullableFlowState[] s_AllNullableFlowStates = (NullableFlowState[])Enum.GetValues(typeof(NullableFlowState));
 
         [Fact]
         public void TestJoinForFixingLowerBounds()
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >TestJoinForFixingLowerBounds [](start = 20, length = 28)

this test name should be adjusted. Same for new few tests below

File: src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs (hunk 2 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs]: I would love to reorder, but we have plenty of hand-written IL with hardcoded attribute values with the enum values hardcoded.  That would be a fair amount of work to fix up the tests but I think worth it.  Opened [https://github.com/dotnet/roslyn/issues/33952](https://github.com/dotnet/roslyn/issues/33952) to track this.

---
In reply to: [263508874](https://github.com/dotnet/roslyn/pull/33927#discussion_r263508874) [](ancestors = 263508874)

Comment (jcouv) [reply src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs]: For what it's worth, my suggestion is to re-order the enum, but keep the IL that we emit as-is (otherwise we'll be causing unnecessary surprises to early adopters)

---
In reply to: [263598753](https://github.com/dotnet/roslyn/pull/33927#discussion_r263598753) [](ancestors = 263598753,263508874)

Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/TypeSymbolWithAnnotations.cs]: @cston points out that reordering would be a breaking change.  It is really sad to be constrained by breaks at this juncture.

---
In reply to: [263598753](https://github.com/dotnet/roslyn/pull/33927#discussion_r263598753) [](ancestors = 263598753,263508874)

**Comment by gafter** [comment]
@jcouv I think I have responded to all of your comments.
@dotnet/roslyn-compiler May I please have another review?

File: src/Compilers/CSharp/Portable/Symbols/TypeWithState.cs [hunk 8]
```diff
@@ -0,0 +1,37 @@
+﻿// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
+
+using Roslyn.Utilities;
+using System;
+using System.Collections.Generic;
+using System.Collections.Immutable;
+using System.Diagnostics;
+using System.Linq;
+using System.Threading;
+using Microsoft.CodeAnalysis.PooledObjects;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/TypeWithState.cs]: Consider removing unnecessary entries.

File: src/Compilers/CSharp/Portable/Symbols/NullableAnnotation.cs [hunk 9]
```diff
@@ -0,0 +1,25 @@
+﻿// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
+
+namespace Microsoft.CodeAnalysis.CSharp.Symbols
+{
+    /// <summary>
+    /// The nullable annotations that can apply in source.
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Symbols/NullableAnnotation.cs]: Consider adding info in the comment on how this works with types nested in a generic.

File: src/Compilers/CSharp/Portable/Symbols/NullableAnnotation.cs [hunk 10]
```diff
@@ -0,0 +1,25 @@
...
+    /// </summary>
+    internal enum NullableAnnotation : byte
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Symbols/NullableAnnotation.cs]: Consider adding a comment that order is important here as the code base will do logic comparisons on the numeric value.

File: src/Compilers/CSharp/Portable/Symbols/NullableAnnotation.cs [hunk 11]
```diff
@@ -0,0 +1,25 @@
...
+    {
+        /// <summary>
+        /// No information. Think oblivious.
+        /// </summary>
+        Unknown,
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Symbols/NullableAnnotation.cs]: Why not `Oblivious` here? All the helpers that use the value use this term.

File: src/Compilers/CSharp/Portable/Symbols/NullableFlowStateExtensions.cs [hunk 12]
```diff
@@ -0,0 +1,29 @@
+﻿// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
+
+namespace Microsoft.CodeAnalysis.CSharp.Symbols
+{
+    internal static class NullableFlowStateExtensions
+    {
+        public static bool MaybeNull(this NullableFlowState state) => state == NullableFlowState.MaybeNull;
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Symbols/NullableFlowStateExtensions.cs]: `IsMaybeNull`

File: src/Compilers/CSharp/Portable/Symbols/TypeWithState.cs [hunk 13]
```diff
@@ -0,0 +1,37 @@
...
+    /// <summary>
+    /// A type and its corresponding flow state resulting from evaluating an rvalue expression.
+    /// </summary>
+    [DebuggerDisplay("{GetDebuggerDisplay(), nq}")]
+    internal readonly struct TypeWithState
+    {
+        public TypeSymbol Type { get; }
+        public NullableFlowState State { get; }
+        public bool HasNullType => Type is null;
+        public bool MaybeNull => State == NullableFlowState.MaybeNull;
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Symbols/TypeWithState.cs]: `IsMaybeNull`

**Comment by jaredpar** [comment]
Done with review pass (iteration 7). Really like where this change is taking us.

File: src/Compilers/CSharp/Portable/Symbols/TypeWithState.cs (hunk 13 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/TypeWithState.cs]: `MayBeNull`?

---
In reply to: [263853738](https://github.com/dotnet/roslyn/pull/33927#discussion_r263853738) [](ancestors = 263853738)

Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Symbols/TypeWithState.cs]: Discussed in person `IsMaybeNull` doesn't make a lot of sense when you say it out loud. Keeping as is.

File: src/Compilers/CSharp/Portable/Symbols/NullableAnnotation.cs (hunk 11 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/Symbols/NullableAnnotation.cs]: For a while we thought we should use "unknown" instead of "oblivious". 
But now, Mads' spec bolsters the term "oblivious", so we may need to revisit.

We have a tracking issue already https://github.com/dotnet/roslyn/issues/29632 (this affects docs and public API)

**Comment by gafter** [comment]
@jaredpar @jcouv @cston I believe I have addressed all comments.  Also, I have renamed "Unknown" to "Oblivious" so please review the latest iteration to see if you approve.
