### PR TITLE
Remove the use of Parallel.ForEach in ClsComplianceChecker

### LINKED ISSUE #23459: ClsComplianceChecker allocations impact performance of unrelated analyzers
**Version Used**: 15.5 Preview 4

**Steps to Reproduce**:

Use AnalyzerRunner to run all CSharpFeatures analyzers an Orchard.sln.

**Results**:

The `ClsComplianceChecker` results in substantial performance overhead. One primary cause of this impact is allocation rates due to the use of `Parallel.For`. This checker is responsible for ~20% of the overall allocations during analyzer testing. Alternative approaches that produce less GC overhead should be considered.

`ClsComplianceChecker` ends up called indirectly by `SyntaxTreeSemanticModel.GetDiagnostics`, which is in turn used by several other analyzers:

* Remove Unnecessary Imports
* Remove Unreachable Code
* Inline Declaration

### PR DESCRIPTION
**Pull request by sharwell**
### Customer scenario

Running analyzer during a build is slower than it should be, with the analyzer driver contributing substantial overhead even when the analyzers themselves are lightweight.

### Bugs this fixes

Fixes #23459

### Workarounds, if any

None needed

### Risk

Low.

### Performance impact

15-20% reduction in allocations for running IDE analyzers. The benefits extend to other analyzers that call GetDiagnostics, with a 30-70% reduction in execution time for analyzers that depend on compiler diagnostics.

### Is this a regression from a previous update?

No.

### Root cause analysis

AnalyzerRunner is a new tool for helping us test analyzer performance in isolation.

### How was the bug found?

AnalyzerRunner.

### Test documentation updated?

No.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs [hunk 1]
```diff
@@ -158,19 +157,9 @@ public override void VisitNamespace(NamespaceSymbol symbol)
                 CheckMemberDistinctness(symbol);
             }
 
-            if (_compilation.Options.ConcurrentBuild)
+            foreach (var m in symbol.GetMembersUnordered())
```
Comment (mavasani) [inline src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: Should we consider using a hybrid approach by changing the original check to:
`if (_compilation.Options.ConcurrentBuild && symbol.IsGlobalNamespace)`?

Comment (mavasani) [reply src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: We also need matching changes in VB: http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Compilation/ClsComplianceChecker.vb,97

Comment (mavasani) [reply src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: I also noted that we are kicking off parallel foreach for every single named type: http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Compiler/ClsComplianceChecker.cs,207. I think that is compounding the allocations.

We ran into similar issues when trying to make the analyzer driver concurrently process compilation events. Attempting to process all events concurrently caused huge allocation and perf hit, and we saw optimal performance with when using a worker queue limited by a certain max worker count: http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerDriver.cs,799. Probably something to consider here?

Comment (sharwell) [reply src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: > Should we consider using a hybrid approach

I did investigate an approach where the `VisitNamespace` method was not changed but `VisitNamedType` was. The result showed no improvement over baseline. I stopped looking for hybrid approaches because I couldn't find a scenario that was worse than the one I have here.

Comment (sharwell) [reply src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: ➡️ Updated the Visual Basic version of the same item.

**Comment by sharwell** [comment]
@dotnet-bot retest windows_debug_unit32_prtest please

**Comment by heejaechang** [comment]
I am not sure whether the issue is allocation or task being starved. but I believe caller of this method is probably already running in parallel so, probably no reason to its nested work parallel again. especially using Parallel.ForEach since it is blocking API and it can take quite a bit of time if there is another parallel running since it can't find task to run some of its work. block waiting task thread to available.

**Comment by sharwell** [comment]
@Pilchie for ask mode

**Comment by sharwell** [comment]
@dotnet/roslyn-compiler I need reviews from you as well

File: src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs (hunk 1 above)
Comment (mavasani) [reply src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: So now we are completely removing the parallelism in this CLS compliance visitor? Seems fine to me as long as there is no build time regression, but probably someone from @dotnet/roslyn-compiler should take a look.

Comment (tmat) [reply src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: Perhaps we should prioritize this: https://github.com/dotnet/roslyn/issues/3679

File: src/Compilers/Core/Portable/InternalUtilities/PerformanceSensitiveAttribute.cs [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+    /// <summary>
+    /// Indicates that a code element is performance sensitive under a known scenario.
+    /// </summary>
+    /// <remarks>
+    /// <para>When applying this attribute, only explicitly set the values for properties specifically indicated by the
+    /// test/measurement technique described in the associated <see cref="Uri"/>.</para>
+    /// </remarks>
+    [Conditional("EMIT_CODE_ANALYSIS_ATTRIBUTES")]
+    [AttributeUsage(AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = true, Inherited = false)]
+    internal sealed class PerformanceSensitiveAttribute : Attribute
```
Comment (jasonmalinowski) [inline src/Compilers/Core/Portable/InternalUtilities/PerformanceSensitiveAttribute.cs]: Cool!

File: src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs (hunk 1 above)
Comment (sharwell) [reply src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: @tmat I left a comment on that issue, suggesting that other scenarios would benefit from such an approach.

**Comment by sharwell** [comment]
@dotnet/roslyn-compiler for reviews

File: src/Compilers/Core/Portable/InternalUtilities/PerformanceSensitiveAttribute.cs (hunk 2 above)
Comment (jcouv) [inline src/Compilers/Core/Portable/InternalUtilities/PerformanceSensitiveAttribute.cs]: >PerformanceSensitiveAttribute [](start = 26, length = 29)

It looks like this file already exists in the repo at that same location. Is it just a case of concurrent PRs?

Comment (sharwell) [reply src/Compilers/Core/Portable/InternalUtilities/PerformanceSensitiveAttribute.cs]: ➡️ It's the same commit. If we want to wait for a new set of builds I can tell the PR to update itself and this addition will disappear from the diff.

**Comment by jcouv** [comment]
> There is a possibility for a performance regression for compilation-only scenarios with no analyzers involved, for very large projects on concurrent systems. However, during testing I was unable to find a solution for which the parallelization benefits outweighed the allocation overhead of the concurrent approach.

Thanks for the analysis.
Could you share more details about how the `Parallel.ForEach` creates those overheads. I understand that it would cause more allocations (Tasks), but it is surprising that it would be that much allocations and that on-net the runtime would be reduced by running serially.

File: src/Compilers/Core/Portable/InternalUtilities/PerformanceSensitiveAttribute.cs (hunk 2 above)
Comment (jcouv) [reply src/Compilers/Core/Portable/InternalUtilities/PerformanceSensitiveAttribute.cs]: Ok, that's fine as long as you merge and don't squash ;-)

File: src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs [hunk 3]
```diff
@@ -158,22 +158,13 @@ public override void VisitNamespace(NamespaceSymbol symbol)
                 CheckMemberDistinctness(symbol);
             }
 
-            if (_compilation.Options.ConcurrentBuild)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: >if (_compilation.Options.ConcurrentBuild) [](start = 12, length = 41)

I am not comfortable with removing this parallelization completely. Even if we didn't add it based on specific scenario, similar approach was definitely proven to improve throughput for other similar cases (when we need to visit all namespaces and types recursively and do some analysis for them). Could we use some heuristic to disable parallelization only when it is likely cause a problem? For example, only when we have cancellable _cancellationToken and probably non-null _filterTree.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 2).

**Comment by sharwell** [comment]
> Could you share more details about how the Parallel.ForEach creates those overheads.

For a reference run which is 1/4 of the size of the run described in #23582, here is some of the overhead caused by `Parallel.ForEach`:

* `ParallelForReplicaTask`: 911MB
* `IndexRange[]`: 258MB
* `System.Threading.Tasks.Shared<long>`: 257MB
* `ContingentProperties`: 151MB
* `Action<object>`: 128MB
* `Action<Symbol>`: 122MB
* `<>c__DisplayClass17_0<object>`: 104MB
* `ParallelForReplicatingTask`: 88MB
* `Action<int>`: 76MB
* `<>c__DisplayClass31_0<Symbol, Object>`: 64MB
* `Action`: 63MB
* `CancellationCallbackInfo`: 60MB
* `<>c__DisplayClass176_0`: 54MB
* `ParallelOptions`: 43MB
* `RangeManager`: 40MB
* `<>c__DisplayClass6_0<Symbol>`: 32MB
* `ParallelLoopStateFlags32`: 23MB
* `SetOnInvokeMres`: 2MB

**Comment by sharwell** [comment]
Over the weekend I ran elapsed time evaluations to compare four approaches:

1. Baseline
3. **_filterTree**: Skip parallelization when `_filterTree` is not null
2. **Sequential**: No parallelization
4. **_filterTree+NSOnly**: Only parallelize across namespaces, and skip parallelization when `_filterTree` is not null

Here are the results, with all times is milliseconds:

| Analyzer | Baseline | _filterTree | Sequential | _filterTree+NSOnly
| --- | --- | --- | --- | ---
| CSharpAddAccessibilityModifiersDiagnosticAnalyzer: | 1635 | 1930 | 1735 | 1888
| CSharpAddBracesDiagnosticAnalyzer: | 9272 | 8368 | 8176 | 8165
| CSharpAsAndNullCheckDiagnosticAnalyzer: | 25340 | 22453 | 19569 | 20745
| CSharpInlineDeclarationDiagnosticAnalyzer: | 225978 | 171636 | 159502 | 168476
| CSharpIsAndCastCheckDiagnosticAnalyzer: | 685 | 705 | 306 | 492
| CSharpNamingStyleDiagnosticAnalyzer: | 120882 | 110507 | 90558 | 114473
| CSharpOrderModifiersDiagnosticAnalyzer: | 2650 | 2879 | 3057 | 2994
| CSharpPreferFrameworkTypeDiagnosticAnalyzer: | 36416 | 35503 | 29867 | 35437
| CSharpQualifyMemberAccessDiagnosticAnalyzer: | 38703 | 33185 | 28413 | 33537
| CSharpRemoveUnnecessaryCastDiagnosticAnalyzer: | 27258 | 25254 | 23712 | 24008
| CSharpRemoveUnnecessaryImportsDiagnosticAnalyzer: | 194789 | 45457 | 35945 | 44266
| CSharpRemoveUnreachableCodeDiagnosticAnalyzer: | 178197 | 38627 | 29539 | 39477
| CSharpSimplifyTypeNamesDiagnosticAnalyzer: | 2036460 | 1871650 | 1721344 | 1812623
| CSharpUnboundIdentifiersDiagnosticAnalyzer: | 2800 | 2489 | 2554 | 2927
| CSharpUseCoalesceExpressionDiagnosticAnalyzer: | 3020 | 2369 | 1919 | 2146
| CSharpUseCoalesceExpressionForNullableDiagnosticAnalyzer: | 3244 | 2953 | 2525 | 3232
| CSharpUseCollectionInitializerDiagnosticAnalyzer: | 45378 | 40457 | 38683 | 42377
| CSharpUseDeconstructionDiagnosticAnalyzer: | 35481 | 33847 | 30305 | 34423
| CSharpUseDefaultLiteralDiagnosticAnalyzer: | 4423 | 3960 | 4042 | 3993
| CSharpUseExplicitTypeDiagnosticAnalyzer: | 97618 | 91163 | 87976 | 88354
| CSharpUseImplicitTypeDiagnosticAnalyzer: | 20463 | 18624 | 16858 | 17985
| CSharpUseInferredMemberNameDiagnosticAnalyzer: | 4727 | 3695 | 3982 | 3885
| CSharpUseIsNullCheckDiagnosticAnalyzer: | 66877 | 64729 | 58624 | 67451
| CSharpUseLocalFunctionDiagnosticAnalyzer: | 10653 | 9208 | 7224 | 9177
| CSharpUseNullPropagationDiagnosticAnalyzer: | 5658 | 6074 | 5488 | 5726
| CSharpUseObjectInitializerDiagnosticAnalyzer: | 10848 | 10756 | 9884 | 9812
| CSharpUseThrowExpressionDiagnosticAnalyzer: | 23309 | 21823 | 20907 | 20100
| CSharpValidateFormatStringDiagnosticAnalyzer: | 20877 | 20127 | 19458 | 19776
| InvokeDelegateWithConditionalAccessAnalyzer: | 11093 | 9241 | 8540 | 9133
| UseExpressionBodyDiagnosticAnalyzer: | 50178 | 51688 | 40819 | 48971
| **Total** | 3314912 | 2761357 | 2511511 | 2696049

The wall-clock elapsed time numbers lead to a similar, though less pronounced, conclusion:

| Baseline | _filterTree | Sequential | _filterTree+NSOnly
| --- | --- | --- | ---
| 233517 | 223185 | 216334 | 218797

**Comment by heejaechang** [comment]
@sharwell can you be little bit more specific on "Sequential: No parallelization".

is it no parallelization between analyzers and for a analyzer? for example, running 1 analyzer at a time and run all actions sequentially for 1 analyzer? 

or are you talking about analyzers are running concurrently, but each analyzer run sequentially? 

or are you talking about analyzer runs sequentially but each analyzer actions run concurrently?

or are you talking about specifically this ClsCompilanceChecker being sequential or parallel?

**Comment by sharwell** [comment]
@heejaechang Sequential is the current state of the pull request.

**Comment by mavasani** [comment]
> or are you talking about specifically this ClsCompilanceChecker being sequential or parallel?

I also feel that we need to get the before and after results in batch compilation with CLS compliance checker but without *any analyzers*. I presume this is the case that compiler team cares the most about.

**Comment by sharwell** [comment]
@AlekseyTs @VSadov Please review the updated change. I made the following changes:

* Re-enable parallelization across types
* Disable parallelization when information is requested only for a single syntax tree
* Use the lightweight fork-join approach from `MethodCompiler` instead of using `Parallel.ForEach`

The resulting numbers are similar to the _filterTree+NSOnly numbers, but with lower overall allocations.

**Comment by VSadov** [comment]
It is likely that the last change improves the batch compiler perf as well. ParallelFor was a bit too heavy tool for the job there.

I am not sure by how much – CLS checks do not take a lot of E2E time, as long as they run concurrently, and from the look of the change that behavior is preserved while implementation is now lighter. It might be interesting to run compiler benchmark – just to see if we got any wins on E2E time. Probably not much if at all, but there should not be any regressions either. 

The new change does not make me worried.

File: src/Compilers/VisualBasic/Portable/Compilation/ClsComplianceChecker.vb [hunk 4]
```diff
@@ -68,21 +66,16 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
...
-            If symbol.Modules.Length > 1 AndAlso _compilation.Options.ConcurrentBuild Then
-                Dim options = If(Me._cancellationToken.CanBeCanceled, New ParallelOptions() With {.CancellationToken = Me._cancellationToken}, s_defaultParallelOptions)
-                Parallel.ForEach(symbol.Modules, options, UICultureUtilities.WithCurrentUICulture(Of ModuleSymbol)(AddressOf VisitModule))
-            Else
-                For Each m In symbol.Modules
-                    VisitModule(m)
-                Next
-            End If
-
+            For Each m In symbol.Modules
```
Comment (sharwell) [inline src/Compilers/VisualBasic/Portable/Compilation/ClsComplianceChecker.vb]: ❗️ This needs to be updated to match the update in the C# compiler.

File: src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs [hunk 5]
```diff
@@ -52,7 +57,13 @@ public static void CheckCompliance(CSharpCompilation compilation, DiagnosticBag
         {
             var queue = new ConcurrentQueue<Diagnostic>();
             var checker = new ClsComplianceChecker(compilation, filterTree, filterSpanWithinTree, queue, cancellationToken);
+            if (compilation.Options.ConcurrentBuild)
```
Comment (heejaechang) [inline src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: why not check the option in side of constructor of ClsCompilanceChecker? seems it is okay to create the stack in the ctor with readonly?

Comment (sharwell) [reply src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: I was following the pattern of `MethodCompiler`. I see that the VB implementation of the same feature initializes the collection in the constructor. I'll move it there for the C# one.

File: src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs [hunk 6]
```diff
@@ -39,6 +43,11 @@ internal partial class ClsComplianceChecker : CSharpSymbolVisitor
             _cancellationToken = cancellationToken;
 
             _declaredOrInheritedCompliance = new ConcurrentDictionary<Symbol, Compliance>();
+
+            if (compilation.Options.ConcurrentBuild)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: >compilation.Options.ConcurrentBuild [](start = 16, length = 35)

Consider also checking if _filterTree is null.

Comment (sharwell) [reply src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: ➡️ I thought about it, but figured it risked regression if the conditions ever changed. The one thing we can count on is it's only needed during concurrent builds.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Compiler/ClsComplianceChecker.cs]: >  let me know and I'll extract the condition to a property

This feels like the right thing to do. Why allocate when we don't need to? 

---
In reply to: [165447222](https://github.com/dotnet/roslyn/pull/23519#discussion_r165447222) [](ancestors = 165447222)

**Comment by jinujoseph** [comment]
Approved to merge via [link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/560681)
Merge pending Val +RPS verification

**Comment by sharwell** [comment]
Validation builds passed too 👍
