### PR TITLE
Find concrete types for type parameters in completion off of lambda parameters

### LINKED ISSUE #42997: Regression: Linq.Expressions infers correct type but doesn't provide completions
This used to work before and it is now breaking some primary Razor tag helper completion scenarios.

**Version Used**: 
SDK: 3.1.300-preview-015048
VSCode version: 1.43.2
C# extension version: 1.21.16

**Steps to Reproduce**:

1. Create a new console app
2. Open it in VS Code and replace `Program.cs` content with the following content,

```c#
using System;
using System.Collections.Generic;
using System.Linq.Expressions;

namespace ModelExpressionTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var obj = new ModelExpression();
            var list = new List<Product>();

            // Hovering over 'arg' shows that it is of type 'Product' but it doesn't show 'MyProperty' in the completion list.
            obj.Create(list, arg => arg.);
            //                         ^ - invoke completions here

            // This works as expected
            obj.Create<Product>(list, arg => arg.);
        }
    }

    class ModelExpression
    {
        public object Create<T>(List<T> list, Expression<Action<T>> expression)
        {
            return null;
        }
    }

    class Product
    {
        public int MyProperty { get; set; }
    }
}

```

3. Invoke completions at the position marked by the comments

**Expected Behavior**:
`MyProperty` is part of the completion list
image

**Actual Behavior**:
No `MyProperty` in completion list
image

Note: 
Hovering over `arg` shows that it is inferred to be the correct type (`Product`) but somehow completions don't reflect that,
image

Also note, this is not VS Code specific. I noticed the same behavior in VS as well.

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #42997

### CODE REVIEW

**Comment by dpoeschl** [comment]
@CyrusNajmabadi @genlu Can you take a look? I'm not sure if there's a better way to line up Type Arguments and Type Parameters, but this seems to work (though I admittedly haven't run all tests yet... we'll see...).

File: src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs [hunk 1]
```diff
@@ -100,6 +101,43 @@ protected ImmutableArray<ISymbol> GetSymbols(IParameterSymbol parameter, int pos
...
         }
 
+        private ImmutableArray<ITypeSymbol> SubstituteTypeParameters(ImmutableArray<ITypeSymbol> parameterTypeSymbols, SyntaxNode invocationExpression)
+        {
+            if (!parameterTypeSymbols.Any(t => t.IsKind(SymbolKind.TypeParameter)))
+            {
+                return parameterTypeSymbols;
+            }
+
+            var invocationSymbols = _context.SemanticModel.GetSymbolInfo(invocationExpression).GetAllSymbols();
```
Comment (dpoeschl) [inline src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs:111]: Not sure when this regressed, but this improves on the Visual Studio 2017 experience when there are multiple overloads involved.

File: src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs [hunk 2]
```diff
@@ -100,6 +101,43 @@ protected ImmutableArray<ISymbol> GetSymbols(IParameterSymbol parameter, int pos
...
+            if (invocationSymbols.Length == 0)
+            {
+                return parameterTypeSymbols;
+            }
+
+            var concreteTypes = ArrayBuilder<ITypeSymbol>.GetInstance();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs:117]:
```suggestion
            using var _ = ArrayBuilder<ITypeSymbol>.GetInstance(out var concreteTypes);
```

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs [hunk 3]
```diff
@@ -10153,6 +10153,110 @@ void Test()
...
+}
+
+class Product3
+{
+    public void MyProperty3() { }
+}";
+
+            await VerifyItemExistsAsync(markup, "MyProperty1");
+            await VerifyItemExistsAsync(markup, "MyProperty2");
+            await VerifyItemExistsAsync(markup, "MyProperty3");
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs:10257]: thanks for the more complex cases.

File: src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs [hunk 4]
```diff
@@ -92,6 +92,7 @@ protected ImmutableArray<ISymbol> GetSymbols(IParameterSymbol parameter, int pos
                 // parameter.Ordinal is the ordinal within (a,b,c) => b.
                 // For candidate symbols of (a,b,c) => b., get types of all possible b.
                 parameterTypeSymbols = GetTypeSymbols(candidateSymbols, argumentName, ordinalInInvocation, ordinalInLambda: parameter.Ordinal);
+                parameterTypeSymbols = SubstituteTypeParameters(parameterTypeSymbols, invocationExpression);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs:95]: perhaps give a comment here as well?

File: src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs [hunk 5]
```diff
@@ -100,6 +101,43 @@ protected ImmutableArray<ISymbol> GetSymbols(IParameterSymbol parameter, int pos
...
+
+            var concreteTypes = ArrayBuilder<ITypeSymbol>.GetInstance();
+            foreach (var invocationSymbol in invocationSymbols)
+            {
+                var typeParameters = invocationSymbol.GetTypeParameters();
+                var typeArguments = invocationSymbol.GetTypeArguments();
+
+                foreach (var parameterTypeSymbol in parameterTypeSymbols)
+                {
+                    if (parameterTypeSymbol.IsKind<ITypeParameterSymbol>(SymbolKind.TypeParameter, out var typeParameter))
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs:125]: what if the parameter type references a type parameter from the *outer type* not a method type parameter?  i think the lines below will crash.  please add tests.

File: src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs [hunk 6]
```diff
@@ -100,6 +101,43 @@ protected ImmutableArray<ISymbol> GetSymbols(IParameterSymbol parameter, int pos
...
+                    {
+                        var index = typeParameters.IndexOf(typeParameter);
+                        var concreteType = typeArguments.ElementAtOrDefault(index);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs:128]: oh.  sneakky.

File: src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs [hunk 7]
```diff
@@ -100,6 +101,43 @@ protected ImmutableArray<ISymbol> GetSymbols(IParameterSymbol parameter, int pos
...
+                        concreteTypes.Add(concreteType ?? typeParameter);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs:129]: not sure ths is correct.  i think you don't want to do anything if the type parameter is not int he list of typeParmeters right?

File: src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs (hunk 4 above)
Comment (dpoeschl) [reply src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs:95]: Comment added.

File: src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs (hunk 2 above)
Comment (dpoeschl) [reply src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs:117]: Sure.

File: src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs (hunk 5 above)
Comment (dpoeschl) [reply src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs:125]: Added a comment for this.

File: src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs (hunk 6 above)
Comment (dpoeschl) [reply src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs:128]: Added a comment for this.

File: src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs (hunk 7 above)
Comment (dpoeschl) [reply src/Workspaces/Core/Portable/Recommendations/AbstractRecommendationServiceRunner.cs:133]: Need to leave it there because
1) It could be the only type, and we need it later to pull in members of object
2) It could have a type constraint from which to pull members

I've added tests for both of these.

**Comment by dpoeschl** [comment]
@CyrusNajmabadi I've responded to your feedback. Can you take another look?

**Comment by dpoeschl** [comment]
@jinujoseph Should this bugfix be targeting master or release/dev16.6?

**Comment by jinujoseph** [comment]
16.6 please
