### PR TITLE
SubstituteNoPiaLocalType - use comparison of SpecialTypes to match bases across distinct core libraries.

### LINKED ISSUE #24964: Unexpected error about inability to locate canonical definition for a NoPia local type when different core libraries are involved
```
        [Fact]
        public void UnificationAcrossDistincCoreLibs()
        {
            string pia = @"
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

[assembly: ImportedFromTypeLib(""GeneralPIA.dll"")]
[assembly: Guid(""f9c2d51d-4f44-45f0-9eda-c9d599b58257"")]

public struct Test
{
}
";

            var piaCompilation = CreateCompilationWithMscorlib45(pia, options: TestOptions.DebugDll, assemblyName: "Pia");

            string consumer1 = @"
public class UsePia1 
{
    public static Test M1()
    {
        return default;
    }
} 
";

            string consumer2 = @"
class UsePia2 
{
    public static void Main()
    {
        UsePia1.M1();
    }
} 
";

            foreach (MetadataReference piaRef in new [] { piaCompilation.EmitToImageReference(), piaCompilation.ToMetadataReference() })
            {
                var compilation1 = CreateCompilationWithMscorlib45(consumer1, references: new [] { piaRef.WithEmbedInteropTypes(true) });

                foreach (MetadataReference consumer1Ref in new[] { compilation1.EmitToImageReference(), compilation1.ToMetadataReference() })
                {
                    var compilation2 = CreateCompilationWithMscorlib46(consumer2, references: new[] { piaRef, consumer1Ref });

                    compilation2.VerifyDiagnostics();

                    Assert.NotSame(compilation1.SourceAssembly.CorLibrary, compilation2.SourceAssembly.CorLibrary);

                    var test = compilation2.GetTypeByMetadataName("Test");
                    Assert.Equal("Pia.dll", test.ContainingModule.Name);

                    var usePia1 = compilation2.GetTypeByMetadataName("UsePia1");
                    Assert.Same(test, usePia1.GetMember<MethodSymbol>("M1").ReturnType);
                }
            }
        }
```

Expected:
Actual:
                // (6,9): error CS1748: Cannot find the interop type that matches the embedded interop type 'Test'. Are you missing an assembly reference?
                //         UsePia1.M1();
                Diagnostic(ErrorCode.ERR_NoCanonicalView, "UsePia1.M1").WithArguments("Test").WithLocation(6, 9)
Diff:
++>                 Diagnostic(ErrorCode.ERR_NoCanonicalView, "UsePia1.M1").WithArguments("Test").WithLocation(6, 9)

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #24964.

### Customer scenario

From https://github.com/dotnet/project-system/issues/2954:
1. git clone github.com/dotnet/projectsystem
2. git checkout 4d3123c
3. Open ProjectSystem.sln 

Observe massive amount of unexpected errors like:
```
Error	CS1748	Cannot find the interop type that matches the embedded interop type 'Microsoft.VisualStudio.Imaging.Interop.ImageMoniker'. Are you missing an assembly reference?	Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests	E:\project-system2\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS.UnitTests\Mocks\IDependencyModelFactory.cs	125	Active
```

### Bugs this fixes

#24964
https://github.com/dotnet/project-system/issues/2954

### Workarounds, if any

Target the same version of mscorlib in projects that depend on each other

### Risk

Low

### Performance impact

Low perf impact because no extra allocations/no complexity changes

### Is this a regression from a previous update?

No

### Root cause analysis

A test gap. A unit-test is added.

### How was the bug found?

Internal customer.

### Test documentation updated?

N/A

### CODE REVIEW

File: src/Compilers/CSharp/Test/Symbol/Symbols/Retargeting/NoPia.cs [hunk 1]
```diff
@@ -2611,5 +2611,65 @@ public static void M2()
 
             CompileAndVerify(consumer);
         }
+
+        [Fact]
+        [WorkItem(24964, "https://github.com/dotnet/roslyn/issues/24964")]
+        public void UnificationAcrossDistincCoreLibs()
```
Comment (Pilchie) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Retargeting/NoPia.cs]: Nit: Missing `t` in `Distinct`

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review. This is a very small fix for 15.7

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review. This is a very small fix for 15.7

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/MetadataDecoder.cs [hunk 2]
```diff
@@ -407,7 +407,8 @@ public static bool IsOrClosedOverATypeFromAssemblies(TypeSymbol symbol, Immutabl
 
                         // Let's use a trick. To make sure the kind is the same, make sure
                         // base type is the same.
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/MetadataDecoder.cs]: Is this comment accurate now? Appears we are comparing special types now vs. base types as before.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Metadata/PE/MetadataDecoder.cs]: Yes, it is accurate, I believe. This is a form of comparison
