### PR TITLE
Handle NotNullIfNotNull in delegate creation and overrides

### LINKED ISSUE #44174: NotNullIfNotNull does not work with method group
.net version 3.1.201 (and Visual Studio 16.5.4)

Path.GetFileNameWithoutExtension is marked with NotNullIfNotNull for the input parameter.
This works for:

        public static IEnumerable<string> GetFileNameWithoutExtension1(IEnumerable<string> paths)
        {
            return paths.Select(path => Path.GetFileNameWithoutExtension(path));
        }

But not for:

        public static IEnumerable<string> GetFileNameWithoutExtension2(IEnumerable<string> paths)
        {
            return paths.Select(Path.GetFileNameWithoutExtension);
        }

**Expected Behavior**:
Both methods compile without warning.

**Actual Behavior**:
Second method gives error CS8619: Nullability of reference types in value of type 'IEnumerable<string?>' doesn't match target type

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #44174

Implements the fix described in https://github.com/dotnet/roslyn/issues/44735#issuecomment-675768560

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs [hunk 1]
```diff
@@ -1259,6 +1259,21 @@ private bool IsValidOverrideReturnType(Symbol overridingSymbol, TypeWithAnnotati
                 }
             }
 
+            TypeWithAnnotations getNotNullIfNotNullOutputType(TypeWithAnnotations outputType, ImmutableHashSet<string> notNullIfParameterNotNull)
+            {
+                for (var i = 0; i < overriddenParameters.Length; i++)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs:1264]: Can probably wrap this in an `if (!notNullIfParameterNotNull.IsEmpty)` so that we only enumerate parameters if necessary.

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler Please review

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs [hunk 2]
```diff
@@ -1259,6 +1259,21 @@ private bool IsValidOverrideReturnType(Symbol overridingSymbol, TypeWithAnnotati
...
+                {
+                    var overridingParam = overridingParameters[i + overridingMethodOffset];
+                    var overriddenParam = overriddenParameters[i];
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs:1267]: >var overriddenParam [](start = 20, length = 19)

Consider inlining in call below to avoid accessing if not needed.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs [hunk 3]
```diff
@@ -1259,6 +1259,21 @@ private bool IsValidOverrideReturnType(Symbol overridingSymbol, TypeWithAnnotati
...
+                    if (notNullIfParameterNotNull.Contains(overridingParam.Name) && !overriddenParam.TypeWithAnnotations.NullableAnnotation.IsAnnotated())
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs:1268]: >!overriddenParam.TypeWithAnnotations.NullableAnnotation.IsAnnotated() [](start = 84, length = 69)

Are we handling cases where the overridden parameter type is an unconstrained type parameter or in a `#nullable disable` context?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs:1268]: `DelegateCreation_FromMethodGroup_NotNullIfNotNull_02` has a scenario when the overridden input parameter is oblivious. Adding a test for unconstrained type parameters.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs]: Done

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 4]
```diff
@@ -54706,6 +54706,267 @@ void M()
...
+    public override string? Method(string? arg) => arg; // 1
+}
+";
+            var comp = CreateNullableCompilation(new[] { source, NotNullIfNotNullAttributeDefinition });
+            comp.VerifyDiagnostics(
+                // (37,29): warning CS8764: Nullability of return type doesn't match overridden member (possibly because of nullability attributes).
+                //     public override string? Method(string? arg) => arg; // 1
+                Diagnostic(ErrorCode.WRN_TopLevelNullabilityMismatchInReturnTypeOnOverride, "Method").WithLocation(37, 29)
+                );
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:54968]: >} [](start = 8, length = 1)

Please test a parameter or return type with multiple `[NotNullIfNotNull]` attributes.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:54968]: Done

**Review by cston — APPROVED** [review]

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler Please review

**Comment by jcouv** [comment]
Looking

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs [hunk 5]
```diff
@@ -1196,13 +1196,18 @@ private bool IsValidOverrideReturnType(Symbol overridingSymbol, TypeWithAnnotati
             }
 
             var conversions = compilation.Conversions.WithNullability(true);
+            var overriddenParameters = overriddenMethod.Parameters;
+            var overridingParameters = overridingMethod.Parameters;
+            var overridingMethodOffset = invokedAsExtensionMethod ? 1 : 0;
+            Debug.Assert(overriddenMethod.ParameterCount == overridingMethod.ParameterCount - overridingMethodOffset);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs:1202]: nit: It may be worth renaming the parameters, otherwise I found this assertion confusing. Maybe `overriddenMethod`->`targetMethod` and `overridingMethod`->`implementationMethod` or something like that?

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 3)

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs (hunk 5 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs:1202]: I am definitely open to improving the naming in a follow-up PR. I find that scanning `overriding` and `overridden` the many times they appear is very hard to get used to. `targetMethod` and `implementationMethod`, or `baseMethod` and `overrideMethod`, etc. or some other pair of terms may be more suitable.

**Comment by Logerfo** [comment]
Wasn't this supposed to be fixed for 16.8 preview 4? I'm on 16.8.3 and can reproduce the original issue.

**Comment by RikkiGibson** [comment]
Sorry, it looks like I didn't sufficiently validate that scenario in this PR. It looks like the scenario is [still broken](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+BiAdgVwBtCJhC4ACOXU8gWAChGABAJgEYWAGC59gFgDc3XuwB0AEQCWEAOa4A9rCkBjKGIDCClHACCNQgE8oUqMIbMefMQEkA8ucuixAGSm4AjuZYBmXqwoNCgBvRgpw3j8+ADZRHwAePi4APgoAcTgYADEpcgA5CDA4AHUpGAALBXwYAFEAD3hcEwVcdgAKPgSk1IAHCAqoAEowiNCGCIneAHYKPoGxAGU4chUYNoAFfvKxDOzcuAKi0oqq2obqZtxB8wmAXxHwh8jRWM7E9hT0zJz8wpKyyrVeqNS6sDrsLofXpbIZPMaTCLMGZzcrqJYrGDvLhIUQpDZbHbffaHf4nIHnJpSFrXJ73cYRJ7MKLsV4QrGpXY/A5/Y6As4gqm4HzgyGfFGw+nheEI6azGGLZZwVZtFEUAC8qU2FUJe1+RwBp2BF0FKq2gxpkoodNuQA===).

I think the problem is related to type argument inference. You can avoid the warning by explicitly supplying type arguments to `.Select()` (although IDE will indicate that they're not necessary).
