### PR TITLE
Only simplify to format interpolation component for IFormattable values

### LINKED ISSUE #42887: IDE0071 needs to factor in whether the type implements IFormattable
**Version Used**: 
3.6.0-2.20167.1+926207070b0c62d6a76aec4627ec26dee17870bb

**Steps to Reproduce**:
```C#
using System;

class Program
{
    static void Main()
    {
        MyType t = default;
        string s = $"{t.ToString("X")}";
        Console.WriteLine(s);
    }
}

struct MyType
{
    public string ToString(string format) => format;
    public override string ToString() => "hello";
}
```

**Expected Behavior**:
IDE0071 isn't offered, because MyType doesn't implement IFormattable.

**Actual Behavior**:
IDE0071 is offered, and changes the code from `$"{t.ToString("X")}"` to `$"{t:X}"`.  The former was using the `ToString(string)` method, but as the instance doesn't implement IFormattable, the latter will end up just using the `ToString()` overload, changing the meaning of the program.  Before the refactoring, this would output "X", and after, it outputs "hello", as the format string gets ignored.

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #42887

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/SimplifyInterpolation/SimplifyInterpolationTests.cs [hunk 1]
```diff
@@ -799,6 +799,101 @@ public async Task PadLeftSimplificationIsStillOfferedOnBaseToString()
 @"class C
 {
     public override string ToString() => $""Test: {base.ToString(),10}"";
+}");
+        }
+
+        [Fact, WorkItem(42887, "https://github.com/dotnet/roslyn/issues/42887")]
+        public async Task FormatComponentSimplificationIsNotOfferedOnNonIFormattableType()
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/SimplifyInterpolation/SimplifyInterpolationTests.cs]: trait?

File: src/Features/Core/Portable/SimplifyInterpolation/Helpers.cs [hunk 2]
```diff
@@ -76,7 +76,9 @@ private static IOperation Unwrap(IOperation expression)
                 !syntaxFacts.IsBaseExpression(invocation.Instance.Syntax))
             {
                 if (invocation.Arguments.Length == 1 &&
-                    invocation.Arguments[0].Value is ILiteralOperation { ConstantValue: { HasValue: true, Value: string value } } literal)
+                    invocation.Arguments[0].Value is ILiteralOperation { ConstantValue: { HasValue: true, Value: string value } } literal &&
+                    invocation.SemanticModel.Compilation.GetTypeByMetadataName("System.IFormattable") is { } systemIFormattable &&
+                    invocation.Instance.Type.Implements(systemIFormattable))
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/SimplifyInterpolation/Helpers.cs]: we likely want to ensure that this .ToString *is* the impl of the IFormattable.ToString right?  you can use .FindImplemetnationForInterfaceMember to validate that.  It would possibly be good to have a test where these are different as well (i.e. an explicit impl of htat interface).

Comment (jnm2) [reply src/Features/Core/Portable/SimplifyInterpolation/Helpers.cs]: @CyrusNajmabadi It can't be. IFormattable only declares ToString(string, IFormatProvider). That's why I didn't do anything about it at first.

File: src/EditorFeatures/CSharpTest/SimplifyInterpolation/SimplifyInterpolationTests.cs (hunk 1 above)
Comment (jnm2) [reply src/EditorFeatures/CSharpTest/SimplifyInterpolation/SimplifyInterpolationTests.cs]: Traits have all been declared on the class header because I hate boilerplate. You okayed this at one point :D

**Comment by CyrusNajmabadi** [comment]
Thanks for the speedy fix!
