### PR TITLE
Fix bugs related to IAnonymousObjectCreationOperation

### LINKED ISSUE #27338: Incorrect operation tree for anonymous object creation initializer with mixed assignment and non-assignment initializers
```
        [CompilerTrait(CompilerFeature.IOperation)]
        [Fact()]
        public void AnonymousTypeCreation_MixedInitializers()
        {
            string source = @"
using System.Collections.Generic;
using System.Linq;

class ClassA
{
    void M(int a)
    {
        var o = /*<bind>*/new { a, b = 1 }/*</bind>*/;
    }
}
";
            string expectedOperationTree = @"

";
            var expectedDiagnostics = DiagnosticDescription.None;

            VerifyOperationTreeAndDiagnosticsForTest<AnonymousObjectCreationExpressionSyntax>(source, expectedOperationTree, expectedDiagnostics);
        }
```

**Actual Operation Tree:** Contains `new { .b = a, 1 }`
```
IAnonymousObjectCreationOperation (OperationKind.AnonymousObjectCreation, Type: <anonymous type: System.Int32 a, System.Int32 b>) (Syntax: 'new { a, b = 1 }')
  Initializers(2):
      ISimpleAssignmentOperation (OperationKind.SimpleAssignment, Type: System.Int32) (Syntax: 'a')
        Left: 
          IPropertyReferenceOperation: System.Int32 <anonymous type: System.Int32 a, System.Int32 b>.b { get; } (OperationKind.PropertyReference, Type: System.Int32) (Syntax: 'b')
            Instance Receiver: 
              null
        Right: 
          IParameterReferenceOperation: a (OperationKind.ParameterReference, Type: System.Int32) (Syntax: 'a')
      ILiteralOperation (OperationKind.Literal, Type: System.Int32, Constant: 1) (Syntax: '1')
```

**Expected Operation Tree:** Contains `new { a, .b = 1 }` or `new { .a = a, .b = 1 }`
```
IAnonymousObjectCreationOperation (OperationKind.AnonymousObjectCreation, Type: <anonymous type: System.Int32 a, System.Int32 b>) (Syntax: 'new { a, b = 1 }')
  Initializers(2):
      IParameterReferenceOperation: a (OperationKind.ParameterReference, Type: System.Int32) (Syntax: 'a')
      ISimpleAssignmentOperation (OperationKind.SimpleAssignment, Type: System.Int32) (Syntax: 'b = 1')
        Left: 
          IPropertyReferenceOperation: System.Int32 <anonymous type: System.Int32 a, System.Int32 b>.b { get; } (OperationKind.PropertyReference, Type: System.Int32) (Syntax: 'b')
            Instance Receiver: 
              null
        Right: 
           ILiteralOperation (OperationKind.Literal, Type: System.Int32, Constant: 1) (Syntax: '1')
```

This seems to be a bug in both C# and VB operation factory.

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #27338, #25266, #23115, #22736, #20338

Also adjust the CFG builder and unit tests to account for IOperation tree shape changes.

<details><summary>Ask Mode template</summary>

### Customer scenario

Invalid or corrupt IOperation tree for anonymous object creation expressions.

### Bugs this fixes

Fixes #27338, #25266, #23115, #22736, #20338

### Workarounds, if any

Analyzers need to write special workaround code to detect such patterns for corrupt code, but no workaround for missing nodes (such as implicit receiver)

### Risk

Low

### Performance impact

Low

### Is this a regression from a previous update?

No, known bugs in IOperation v1, but now also affects the CFG shape.

### Root cause analysis

Missed the triage bar for IOperation v1 release, but now also affects CFG shape.

### How was the bug found?

Dogfooding and writing CFG builder

### Test documentation updated?

N/A

</details>

### CODE REVIEW

**Comment by tmeschter** [comment]
test loc

**Comment by tmeschter** [comment]
(Please ignore the 
windows_loc_status_prtest check; I'm just making sure it runs. Errors are expected and unrelated to this change.)

File: src/Compilers/Core/Portable/Operations/InstanceReferenceKind.cs [hunk 1]
```diff
@@ -15,6 +15,10 @@ public enum InstanceReferenceKind
         /// <summary>
         /// Reference to the object being initialized in a C# or VB object or collection initializer, or to the object being referred to in a VB With statement.
         /// </summary>
-        ImplicitReceiver
+        ImplicitReceiver,
+        /// <summary>
+        /// Reference to the anonymous object being initialized in a C# or VB anonymous type object initializer, or to the object being referred to in a VB With statement.
+        /// </summary>
+        ImplicitAnonymousReceiver,
```
Comment (333fred) [inline src/Compilers/Core/Portable/Operations/InstanceReferenceKind.cs]: Why not just use ImplicitReceiver for this? If we can't use ImplicitReceiver, we should rename ImplicitReceiver so that these names don't overlap (since the API hasn't shipped yet, this is our last chance)

File: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs [hunk 2]
```diff
@@ -5075,36 +5075,23 @@ public override IOperation VisitAnonymousObjectCreation(IAnonymousObjectCreation
...
-                            initializerBuilder.Add(visitedAssignment);
-                            continue;
-                        }
-                    }
-                }
+                Debug.Assert(propertyReference != null);
+                Debug.Equals(propertyReference.Property, initializedProperty);
+                Debug.Assert(propertyReference.Arguments.IsEmpty);
+                Debug.Assert(propertyReference.Instance != null);
+                Debug.Assert(propertyReference.Instance.Kind == OperationKind.InstanceReference);
```
Comment (333fred) [inline src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: Is it not possible to have nested anonymous type initializers?

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs [hunk 3]
```diff
@@ -206,28 +206,62 @@ private IInvalidOperation CreateInvalidExpressionForHasArgumentsExpression(Bound
...
+                        type: properties[i].Type,
+                        constantValue: default,
+                        isImplicit: true);
+                    isImplicitAssignment = true;
+                }
+                else
                 {
-                    builder.Add(value);
-                    continue;
+                    Debug.Assert(i == expression.Declarations[currentDeclarationIndex].PropertyIndex);
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs]: This assertion is explicitly checked by the `if`, there's no need for it.

File: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs (hunk 2 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: For nested initializers, the implicit instance is still the innermost one.

---
In reply to: [196887763](https://github.com/dotnet/roslyn/pull/28005#discussion_r196887763) [](ancestors = 196887763)

**Comment by 333fred** [comment]
Done review pass (commit 1)

File: src/Compilers/Core/Portable/Operations/InstanceReferenceKind.cs (hunk 1 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/Operations/InstanceReferenceKind.cs]: We can discuss this at today's meeting - I thought we wanted more richer information to distinguish without going back to syntax.

---
In reply to: [196878486](https://github.com/dotnet/roslyn/pull/28005#discussion_r196878486) [](ancestors = 196878486)

**Comment by AlekseyTs** [comment]
>                         foreach (var symbol in anonymousType.GetMembers(field.Name))

This is existing code, but it looks inefficient and might lead to incorrect symbol used in error cases, for example when there are duplicate names. There is an API that is supposed to return a property by index ```AnonymousTypeManager.GetAnonymousTypeProperty(anonymousType, index)```. I think we should use it here.

---
Refers to: src/Compilers/CSharp/Portable/Binder/Binder_AnonymousTypes.cs:112 in 2660a10. [](commit_id = 2660a10d23922d7adae522b8be8907eebe670bbb, deletion_comment = False)

File: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml [hunk 4]
```diff
@@ -1446,6 +1446,7 @@
     <!-- Non-null type is required for this node kind -->
     <Field Name="Type" Type="TypeSymbol" Override="true" Null="disallow"/>
     <Field Name="Property" Type="PropertySymbol" Null="disallow"/>
+    <Field Name="PropertyIndex" Type="int"/>
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml]: > <Field Name="PropertyIndex" Type="int"/> [](start = 3, length = 41)

I am not sure if we need to store the index, it should always match the index of this item in Declarations array in BoundAnonymousObjectCreationExpression

File: src/Compilers/Core/Portable/Operations/InstanceReferenceKind.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/Core/Portable/Operations/InstanceReferenceKind.cs]: > We can discuss this at today's meeting - I thought we wanted more richer information to distinguish without going back to syntax.

I think we already using it for different things like With statement as well, for example. 

---
In reply to: [196897129](https://github.com/dotnet/roslyn/pull/28005#discussion_r196897129) [](ancestors = 196897129,196878486)

**Comment by AlekseyTs** [comment]
>             var properties = operation.Type.GetMembers().OfType<IPropertySymbol>().ToImmutableArray();

It feels like we shouldn't need this local any more

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:5070 in 2660a10. [](commit_id = 2660a10d23922d7adae522b8be8907eebe670bbb, deletion_comment = False)

File: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs [hunk 5]
```diff
@@ -5075,36 +5075,23 @@ public override IOperation VisitAnonymousObjectCreation(IAnonymousObjectCreation
...
+                Debug.Assert(((IInstanceReferenceOperation)propertyReference.Instance).ReferenceKind == InstanceReferenceKind.ImplicitAnonymousReceiver);
 
-                initializerBuilder.Add(visitAndCaptureInitializer(initializedProperty, initializer));
+                IOperation visitedTarget = new PropertyReferenceExpression(initializedProperty, Visit(propertyReference.Instance), ImmutableArray<IArgumentOperation>.Empty,
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: >initializedProperty [](start = 75, length = 19)

Should use value from propertyReference

File: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml (hunk 4 above)
Comment (mavasani) [reply src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml]: For `new {a, b = i }`, Declarations array only has a single entry for property `b`, but `PropertyIndex` is 1. How can we figure out that the first element of `Arguments` has no matching element in `Declarations` array without using this property index?

---
In reply to: [196900867](https://github.com/dotnet/roslyn/pull/28005#discussion_r196900867) [](ancestors = 196900867)

File: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs [hunk 6]
```diff
@@ -5075,36 +5075,23 @@ public override IOperation VisitAnonymousObjectCreation(IAnonymousObjectCreation
...
+                    semanticModel: null, propertyReference.Syntax, propertyReference.Type, propertyReference.ConstantValue, IsImplicit(propertyReference));
+                IOperation visitedValue = visitAndCaptureInitializer(initializedProperty, simpleAssignment.Value);
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: >initializedProperty [](start = 69, length = 19)

Should use value from propertyReference

File: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml (hunk 4 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml]: > For new {a, b = i }, Declarations array only has a single entry for property b, but PropertyIndex is 1. How can we figure out that the first element of Arguments has no matching element in Declarations array without using this property index?

I see.



---
In reply to: [196904027](https://github.com/dotnet/roslyn/pull/28005#discussion_r196904027) [](ancestors = 196904027,196900867)

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs [hunk 7]
```diff
@@ -206,28 +206,62 @@ private IInvalidOperation CreateInvalidExpressionForHasArgumentsExpression(Bound
 
         private ImmutableArray<IOperation> GetAnonymousObjectCreationInitializers(BoundAnonymousObjectCreationExpression expression)
         {
-            // For error cases, the binder generates only the argument.
+            // For error cases and non-assignment initializers, the binder generates only the argument.
             Debug.Assert(expression.Arguments.Length >= expression.Declarations.Length);
 
+            var properties = expression.Type.GetMembers().OfType<IPropertySymbol>().ToImmutableArray();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs]: >var properties = expression.Type.GetMembers().OfType<IPropertySymbol>().ToImmutableArray(); [](start = 12, length = 91)

We have a helper ```AnonymousTypeManager.GetAnonymousTypeProperty``` we should use get properties by index instead.

File: src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs [hunk 8]
```diff
@@ -206,28 +206,62 @@ private IInvalidOperation CreateInvalidExpressionForHasArgumentsExpression(Bound
...
+                        referenceKind: InstanceReferenceKind.ImplicitAnonymousReceiver,
+                        semanticModel: _semanticModel,
+                        syntax: expression.Syntax,
+                        type: expression.Type,
+                        constantValue: default,
+                        isImplicit: true);
+
+                // Find matching declaration for the current argument.
+                if (currentDeclarationIndex >= expression.Declarations.Length ||
+                    i != expression.Declarations[currentDeclarationIndex].PropertyIndex)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Operations/CSharpOperationFactory_Methods.cs]: >i != expression.Declarations[currentDeclarationIndex].PropertyIndex [](start = 20, length = 67)

We have a property symbol that we can compare. Can we do without the  ```PropertyIndex``` after all?

File: src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb [hunk 9]
```diff
@@ -266,25 +266,52 @@ Namespace Microsoft.CodeAnalysis.Operations
         End Function
 
         Private Function GetAnonymousTypeCreationInitializers(expression As BoundAnonymousTypeCreationExpression) As ImmutableArray(Of IOperation)
+            ' For error cases and non-assignment initializers, the binder generates only the argument.
             Debug.Assert(expression.Arguments.Length >= expression.Declarations.Length)
 
+            Dim properties = expression.Type.GetMembers().OfType(Of IPropertySymbol)().ToImmutableArray()
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Operations/VisualBasicOperationFactory_Methods.vb]: >Dim properties = expression.Type.GetMembers().OfType(Of IPropertySymbol)().ToImmutableArray() [](start = 12, length = 93)

Should use AnonymousTypePublicSymbol.Properties instead

**Comment by AlekseyTs** [comment]
Is the plan to address #25268 separately?

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1)

**Comment by mavasani** [comment]
>                         foreach (var symbol in anonymousType.GetMembers(field.Name))

I ended up reverting all changes in this file. I have filed [https://github.com/dotnet/roslyn/issues/28042](https://github.com/dotnet/roslyn/issues/28042) to track this issue.

---
In reply to: [398851479](https://github.com/dotnet/roslyn/pull/28005#issuecomment-398851479) [](ancestors = 398851479)

---
Refers to: src/Compilers/CSharp/Portable/Binder/Binder_AnonymousTypes.cs:112 in 2660a10. [](commit_id = 2660a10d23922d7adae522b8be8907eebe670bbb, deletion_comment = False)

File: src/Compilers/Core/Portable/Operations/InstanceReferenceKind.cs (hunk 1 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/Operations/InstanceReferenceKind.cs]: Alright, I have switched back to using the existing field and updated the documentation. I also realized that distinguishing this case does not need to go back to syntax. The client can check `instanceReferenceOperation.Type.IsAnonymousType`.

---
In reply to: [196902409](https://github.com/dotnet/roslyn/pull/28005#discussion_r196902409) [](ancestors = 196902409,196897129,196878486)

**Comment by mavasani** [comment]
Yes, I think the PR was already going to big and hoping to address it in a follow-up PR.

---
In reply to: [398877819](https://github.com/dotnet/roslyn/pull/28005#issuecomment-398877819) [](ancestors = 398877819)

**Comment by mavasani** [comment]
@333fred @AlekseyTs feedback addressed.

File: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs [hunk 10]
```diff
@@ -5067,44 +5067,26 @@ public override IOperation VisitAnonymousObjectCreation(IAnonymousObjectCreation
...
-            Debug.Assert(properties.Length == operation.Initializers.Length);
-
             SpillEvalStack();
 
             var initializerBuilder = ArrayBuilder<IOperation>.GetInstance(operation.Initializers.Length);
             for (int i = 0; i < operation.Initializers.Length; i++)
             {
-                IOperation initializer = operation.Initializers[i];
-                IPropertySymbol initializedProperty = properties[i];
+                var simpleAssignment = (ISimpleAssignmentOperation)operation.Initializers[i];
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: >(ISimpleAssignmentOperation)operation.Initializers[i]; [](start = 39, length = 54)

Since we cannot change type of the ```initializers``` property. I think we should clarify the contract in its doc comment and assert the invariant in two our test visitors.

File: src/Compilers/Core/Portable/Operations/InstanceReferenceKind.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/Core/Portable/Operations/InstanceReferenceKind.cs]: > The client can check instanceReferenceOperation.Type.IsAnonymousType.

Relying on that would be error prone, an instance of an anonymous type can be a target of a With statement for example. But you are correct, one doesn't need to go back to syntax. It  will be sufficient to go up the parents chain until a node that can create a context like that is reached.

---
In reply to: [197145865](https://github.com/dotnet/roslyn/pull/28005#discussion_r197145865) [](ancestors = 197145865,196902409,196897129,196878486)

File: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs [hunk 11]
```diff
@@ -5067,44 +5067,26 @@ public override IOperation VisitAnonymousObjectCreation(IAnonymousObjectCreation
...
+                var propertyReference = (IPropertyReferenceOperation)simpleAssignment.Target;
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: >(IPropertyReferenceOperation)simpleAssignment.Target; [](start = 40, length = 53)

Same for this invariant.

File: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs [hunk 12]
```diff
@@ -5067,44 +5067,26 @@ public override IOperation VisitAnonymousObjectCreation(IAnonymousObjectCreation
...
-                            initializerBuilder.Add(visitedAssignment);
-                            continue;
-                        }
-                    }
-                }
+                Debug.Assert(propertyReference != null);
+                Debug.Assert(propertyReference.Arguments.IsEmpty);
+                Debug.Assert(propertyReference.Instance != null);
+                Debug.Assert(propertyReference.Instance.Kind == OperationKind.InstanceReference);
+                Debug.Assert(((IInstanceReferenceOperation)propertyReference.Instance).ReferenceKind == InstanceReferenceKind.ImplicitReceiver);
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: >((IInstanceReferenceOperation)propertyReference.Instance).ReferenceKind == InstanceReferenceKind.ImplicitReceiver [](start = 29, length = 113)

Should probably assert this invariant in test visitors as well.

Comment (AlekseyTs) [reply src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: Pretty much all these asserts should be there.

---
In reply to: [197207252](https://github.com/dotnet/roslyn/pull/28005#discussion_r197207252) [](ancestors = 197207252)

File: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs [hunk 13]
```diff
@@ -5225,7 +5207,8 @@ IArrayInitializerOperation popAndAssembleArrayInitializerValues(IArrayInitialize
 
         public override IOperation VisitInstanceReference(IInstanceReferenceOperation operation, int? captureIdForResult)
         {
-            if (operation.ReferenceKind == InstanceReferenceKind.ImplicitReceiver)
+            if (operation.ReferenceKind == InstanceReferenceKind.ImplicitReceiver &&
+                !operation.Type.IsAnonymousType)
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: >!operation.Type.IsAnonymousType [](start = 16, length = 31)

I am not sure why this condition is added. Also, I believe the behavior will be incorrect for the case when an instance of anonymous type is used as a target of a With statement in VB. Please add a test.

File: src/Test/Utilities/Portable/Compilation/ControlFlowGraphVerifier.cs [hunk 14]
```diff
@@ -766,8 +766,9 @@ private static bool CanBeInControlFlowGraph(IOperation n)
                              !ITypeSymbolHelpers.IsDynamicType(binary.Type));
 
                 case OperationKind.InstanceReference:
-                    // Implicit instance receivers are expected to have been removed when dealing with creations.
-                    return ((IInstanceReferenceOperation)n).ReferenceKind == InstanceReferenceKind.ContainingTypeInstance;
+                    // Implicit instance receivers, except for anonymous type creations, are expected to have been removed when dealing with creations.
+                    return ((IInstanceReferenceOperation)n).ReferenceKind == InstanceReferenceKind.ContainingTypeInstance ||
+                        ((IInstanceReferenceOperation)n).ReferenceKind == InstanceReferenceKind.ImplicitReceiver && n.Type.IsAnonymousType;
```
Comment (AlekseyTs) [inline src/Test/Utilities/Portable/Compilation/ControlFlowGraphVerifier.cs]: >((IInstanceReferenceOperation)n).ReferenceKind == InstanceReferenceKind.ImplicitReceiver && n.Type.IsAnonymousType [](start = 24, length = 114)

I think we should strengthen this condition by checking that the parent is an anonymous type property access, its parent is an assignment and its parent is an anonymous object creation.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 3)

File: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs (hunk 13 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: Added test `WithFlow_07` which verifies the old baseline was incorrect and removing this check produces the correct baseline.

---
In reply to: [197208455](https://github.com/dotnet/roslyn/pull/28005#discussion_r197208455) [](ancestors = 197208455)

File: src/Compilers/Core/Portable/Operations/InstanceReferenceKind.cs [hunk 15]
```diff
@@ -13,8 +13,9 @@ public enum InstanceReferenceKind
         /// </summary>
         ContainingTypeInstance,
         /// <summary>
-        /// Reference to the object being initialized in a C# or VB object or collection initializer, or to the object being referred to in a VB With statement.
+        /// Reference to the object being initialized in C# or VB object or collection initializer,
+        /// anonymous type creation initializer or to the object being referred to in a VB With statement.
```
Comment (333fred) [inline src/Compilers/Core/Portable/Operations/InstanceReferenceKind.cs]: Nit: I am a fan of Oxford commas

File: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs [hunk 16]
```diff
@@ -5234,6 +5216,12 @@ public override IOperation VisitInstanceReference(IInstanceReferenceOperation op
                 {
                     return OperationCloner.CloneOperation(_currentImplicitInstance.ImplicitInstance);
                 }
+                else if (operation.Type.IsAnonymousType &&
+                    (object)_currentImplicitInstance.AnonymousType == operation.Type)
+                {
+                    return new InstanceReferenceExpression(operation.ReferenceKind, semanticModel: null, operation.Syntax, operation.Type,
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: >return new InstanceReferenceExpression(operation.ReferenceKind, semanticModel: null, operation.Syntax, operation.Type,  [](start = 20, length = 119)

Is this code reachable? Can you point me to a unit-test that hits it?

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 4). The only remaining question I have at the moment is https://github.com/dotnet/roslyn/pull/28005#pullrequestreview-130997049.

File: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs (hunk 16 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: Newly added test `WithFlow_07` hits this for `IInstanceReferenceOperation (ReferenceKind: ImplicitReceiver) (OperationKind.InstanceReference, Type: <anonymous type: I As System.Int32>, IsImplicit) (Syntax: 'New With { .I = 0 }')`

---
In reply to: [197280509](https://github.com/dotnet/roslyn/pull/28005#discussion_r197280509) [](ancestors = 197280509)

**Review by 333fred — APPROVED** [review]
LGTM (commit 4)

File: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs (hunk 16 above)
Comment (AlekseyTs) [reply src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: > Newly added test WithFlow_07 hits this for IInstanceReferenceOperation (ReferenceKind: ImplicitReceiver) (OperationKind.InstanceReference, Type: <anonymous type: I As System.Int32>, IsImplicit) (Syntax: 'New With { .I = 0 }')

I see, I think it would be better to handle the implicit receivers explicitly in VisitAnonymousObjectCreation instead of trying to handle them here, potentially handling cases that we do not intend to handle. 

---
In reply to: [197285755](https://github.com/dotnet/roslyn/pull/28005#discussion_r197285755) [](ancestors = 197285755,197280509)

Comment (mavasani) [reply src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs]: Sure, refactored the code.

---
In reply to: [197290048](https://github.com/dotnet/roslyn/pull/28005#discussion_r197290048) [](ancestors = 197290048,197285755,197280509)

**Review by AlekseyTs — APPROVED** [review]
LGTM (iteration 5)

**Comment by mavasani** [comment]
Tagging @jinujoseph for approval

**Comment by jinujoseph** [comment]
Approved to merge for 15.8.Preview4
