### PR TITLE
Avoid storing information about unrelated assemblies in AssembliesToWhichInternalAccessHasBeenDetermined

### LINKED ISSUE #81820: Memory leak in ServiceHub.RoslynCodeAnalysisService.exe
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Memory-leak-in-ServiceHubRoslynCodeAnal/11021616)._

---
I often work on two solutions:
- One that has 12 projects. It has a WinUI 3 app and a bunch of Class Library projects. It has about 1,200 files (.cs, .resw, etc.)
- One that has 7 projects. It has two Blazor Server app projects, and five Class Library projects. It has about 500 files (.cs, .razor, .jpeg, etc.)

I have a consistent issue with the second solution (the one with Blazor Server apps): the memory of `ServiceHub.RoslynCodeAnalysisService.exe` increases over time, whether I edit `.razor` files or just C# files. On my 32 GB RAM device, this process can take easily 15-20GB of RAM within a few hours. When it happens, VS is barely usable:
- Light-bulb and auto-completion list are very slow to show-up.
- Rename (Ctrl+R, Ctrl+R) takes 10+ seconds just to show its UI, and much more to apply name change to the solution.
- Cleaning `usings` across the whole solution using light bulb can take minutes to run.

After a few hours, I need to restart VS in order to free all the memory and get VS running fast again. It's quite annoying.

The fact that this issue doesn't happen with my other larger solution makes me suggest there's something wrong with Razor support, even when I don't have any `.razor` file opened or edited during my whole user session.

**Please find in attachment a 16 GB memory dump of `ServiceHub.RoslynCodeAnalysisService.exe` for investigation.**

_PS: I noticed many feedback ticket are similar to mine, particularly this one: https://developercommunity.visualstudio.com/t/ServiceHubRoslynCodeAnalysisServiceexe/10986518 ; I tried telling in Dev Community that my feedback was similar and therefore just put the text above as a comment to this existing feedback, but the website crashed when I tried so._

---
#### Feedback Bot on 12/28/2025, 08:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### Feedback Bot solved on 12/30/2025, 10:20 AM, undefined votes: 

<p>Thanks for taking the time to report this issue! It seems to us that it’s describing the same thing as <a target='_blank' href="https://developercommunity.visualstudio.com/t/Memory-leak-in-ServiceHubRoslynCodeAnal/11021613">another one</a>. We’ve closed this one as a duplicate and transferred all votes from this ticket to the other one. Please follow along on the linked ticket to communicate with the team, see updates on status, and help provide any needed diagnostic info. For more information, see our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines">issue reporting guidelines</a>.</p>
<p>Happy coding!</p>

### LINKED ISSUE #81937: An expected warning about an obsolete override is missing when overridden method is defined in a generic type.
The following test fails due to a missing warning. The warning is reported when `C0` is not generic.

```
        [Fact]
        public void ObsoleteOverrideChain_02()
        {
            string source1 = @"
using System;

public class C0<T>
{
    public virtual void M(){}
}

public class C1<T> : C0<T>
{
    [Obsolete]
    public override void M(){}
}
";
            var comp1 = CreateCompilation(source1);

            string source2 = @"
using System;

internal class C2 {}

internal class C3: C1<C2>
{
    [Obsolete]
    public override void M() { }
}
";

            var comp2 = CreateCompilation(source2, references: [comp1.ToMetadataReference()]);
            comp2.VerifyDiagnostics(
                // (9,26): warning CS0809: Obsolete member 'C3.M()' overrides non-obsolete member 'C0.M()'
                //     public override void M() { }
                Diagnostic(ErrorCode.WRN_ObsoleteOverridingNonObsolete, "M").WithArguments("C3.M()", "C0.M()").WithLocation(9, 26)
                );
        }
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #81820
Also fixes #81937

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

File: src/Compilers/CSharp/Test/Semantic/Semantics/AccessCheckTests.cs [hunk 1]
```diff
@@ -843,10 +843,6 @@ class ADerived2: A
             Assert.True(compilation.IsSymbolAccessibleWithin(adiscard, sourceAssem));
             Assert.False(Symbol.IsSymbolAccessible(kdiscard.GetSymbol(), sourceAssem.GetSymbol()));
             Assert.False(compilation.IsSymbolAccessibleWithin(kdiscard, sourceAssem));
-            Assert.False(Symbol.IsSymbolAccessible(classA.GetSymbol(), mscorlibAssem.GetSymbol()));
-            Assert.False(compilation.IsSymbolAccessibleWithin(classA, mscorlibAssem));
-            Assert.False(Symbol.IsSymbolAccessible(aliasA.GetSymbol(), mscorlibAssem.GetSymbol()));
-            Assert.False(compilation.IsSymbolAccessibleWithin(aliasA, mscorlibAssem));
             Assert.True(Symbol.IsSymbolAccessible(unknownType.GetSymbol(), sourceAssem.GetSymbol()));
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/AccessCheckTests.cs:852]: It doesn't feel great that we have to remove these to avoid assertions, particularly the ones through `Compilation`, since that's a public API and we want to be able to test with invalid inputs to ensure we're not crashing. #Resolved

File: src/Compilers/VisualBasic/Test/Semantic/Semantics/AccessCheckTests.vb [hunk 2]
```diff
@@ -776,10 +776,6 @@ End Class
             Assert.True(compilation.IsSymbolAccessibleWithin(aarrayType, sourceAssem))
             Assert.False(Symbol.IsSymbolAccessible(karrayType, sourceAssem))
             Assert.False(compilation.IsSymbolAccessibleWithin(karrayType, sourceAssem))
-            Assert.False(Symbol.IsSymbolAccessible(classA, mscorlibAssem))
-            Assert.False(compilation.IsSymbolAccessibleWithin(classA, mscorlibAssem))
-            Assert.False(Symbol.IsSymbolAccessible(aliasA, mscorlibAssem))
-            Assert.False(compilation.IsSymbolAccessibleWithin(aliasA, mscorlibAssem))
             Assert.True(Symbol.IsSymbolAccessible(unknownType, sourceAssem))
```
Comment (333fred) [inline src/Compilers/VisualBasic/Test/Semantic/Semantics/AccessCheckTests.vb:785]: Similar comment here. #Resolved

File: src/Compilers/CSharp/Test/Semantic/Semantics/AccessCheckTests.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AccessCheckTests.cs:852]: > It doesn't feel great that we have to remove these to avoid assertions, particularly the ones through `Compilation`, since that's a public API and we want to be able to test with invalid inputs to ensure we're not crashing.

Do you have any specific suggestion in mind?

Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AccessCheckTests.cs:852]: My first thought was adding something to `TestOnlyCompilationData`, but that's not accessible here. Perhaps we could add a `Debug`-only flag to `Assembly` that we expect to check an invalid combination?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AccessCheckTests.cs:852]: I guess, I can restore the asserts under ```#if !DEBUG```. I don't think it is worth doing anything more than that for two tests.

Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AccessCheckTests.cs:852]: That's fine with me.

Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AccessCheckTests.cs:852]: Also consider updating the `Debug.Fail` message to mention that, if this is an explicit test, take the same approach? Or add a comment right above it for future readers?

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

File: src/Compilers/CSharp/Test/Semantic/Semantics/AccessCheckTests.cs (hunk 1 above)
Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AccessCheckTests.cs:852]: @AlekseyTs did you see the second part of the comment here?

**Comment by AlekseyTs** [comment]
@333fred 

> with the additional comment at the Debug.Fail location.

 I am not planning to add an additional comment there. The assert is an indication of a possible bug, even when public API is used. I.e. an indication that the usage of the API is likely wrong.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review

File: src/Compilers/CSharp/Test/Semantic/Semantics/AccessCheckTests.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AccessCheckTests.cs:852]: @333fred

> did you see the second part of the comment here?

 I read through the entire thread and nothing jumped out as something I missed. It is quite possible I misunderstood or didn't fully understand something. If there is still a concern, consider clearly restating/rephrasing it.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review

**Comment by RikkiGibson** [comment]
Taking a look now

**Review by RikkiGibson — APPROVED** [review]
