### PR TITLE
Fix well-known Equals method nullable analysis bug

### LINKED ISSUE #40577: Roslyn doesn't consider quasi-implemenations of IEqualityComparer.Equals and IEqutable.Equals as well known members in nullability analysis
**Version Used**: 

```
Branch master (23 Dec 2019)
Latest commit 8614121 by Charles Stoner:
Do not include binding cache in BoundLambda (#40534)
```

**Steps to Reproduce**:

Compile the following code:
```cs
#nullable enable
using System.Collections.Generic;

class Base
{
    public bool Equals(string? x, string? y) => true;
    public int GetHashCode(string x) => 0;
}

class Quasi : Base, IEqualityComparer<string>
{
   void M(string? s)
   {
     if (Equals(s, null)) return;
     
     s.ToString();
   }
}
```

**Expected Behavior**:
No warnings. `s` is compared to `null` via `IEqualityComparer<string>.Equals` and the method does not dereference it in such cases.

**Actual Behavior**:
`warning CS8602: Dereference of a possibly null reference.` is reported for `s.ToString()`

**Notes**
If you provide an implementation of `Equals` in `Quasi` instead of quasi-implementing it via the `Equals` method in `Base` the warning goes away so it seems that Roslyn just doesn't check quasi-implementations when checking for well-known equality methods in `NullableWalker.LearnFromEqualsMethod.isWellKnownEqualityMethodOrImplementation` which seems to be a bug.

i.e. there's no such warning in the following code:
```cs
#nullable enable
using System.Collections.Generic;

class Base
{
    
    public int GetHashCode(string x) => 0;
}

class Quasi : Base, IEqualityComparer<string>
{
   public bool Equals(string? x, string? y) => true;
   void M(string? s)
   {
     if (Equals(s, null)) return;
     
     s.ToString();
   }
}
```

As mentioned above the same problem exists with other well-known interfaces' metods e.g. `IEqutable.Equals`. The following code snippet does not produce any warnings for dereferencing `s` despite it being explicitly compared to `null`. It will report the warning correctly if you move the `Equals(Quasi? x)` method from `Base` to `Quasi`:
```cs
#nullable enable
using System;

class Base
{
  public bool Equals(Quasi? y) => true;
}

class Quasi : Base, IEquatable<Quasi>
{

   void M(Quasi s)
   {
     if (s.Equals(null))
     {
       s.ToString();
     }
   }
}
```

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #40577

I wrongly assumed that a method that implements e.g. IEquatable<T>.Equals would be contained in a class that implements IEquatable<T>.

edit: among other wrong assumptions! This PR has been a journey into how interfaces actually work/what's possible in .NET.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
>                 foreach (var member in constructedType.GetMembers(WellKnownMemberNames.ObjectEquals))

We have a helper for this - ```AsMemberOfType```

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3780 in d754534. [](commit_id = d7545348d3379f15edf71e06d0ce1b2437bead83, deletion_comment = False)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 1]
```diff
@@ -117959,6 +117959,73 @@ static void M1(C c, string? s)
                     Diagnostic(ErrorCode.WRN_NullReferenceReceiver, "s").WithLocation(17, 17));
         }
 
+        [Fact, WorkItem(40577, "https://github.com/dotnet/roslyn/issues/40577")]
+        public void IEquatableEqualsMethod_ImplInBaseType()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >IEquatableEqualsMethod_ImplInBaseType [](start = 20, length = 37)

Please add a unit-test for scenario like this:
```
using System;

#nullable enable
class B : IEquatable<string>
{
    public bool Equals(string? s) => throw null!;
}

class C : B, IEquatable<string>
{
    bool IEquatable<string>.Equals(string? s) => throw null!;

    static void M1(C c, string? s)
    {
        if (c.Equals(s))
        {
            _ = s.ToString();
        }
        else
        {
            _ = s.ToString(); // 1
        }
    }
}";
```

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >IEquatableEqualsMethod_ImplInBaseType [](start = 20, length = 37)

Please add a unit-test for scenario like this:
```
using System;

#nullable enable
class B : IEquatable<string>
{
    public virtual bool Equals(string? s) => throw null!;
}

class C : B
{
    public override bool Equals(string? s) => throw null!;

    static void M1(C c, string? s)
    {
        if (c.Equals(s))
        {
            _ = s.ToString();
        }
        else
        {
            _ = s.ToString(); // 1
        }
    }
}";
```

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >IEquatableEqualsMethod_ImplInBaseType [](start = 20, length = 37)

Please add a unit-test for scenario like this:
```
using System;

#nullable enable

class C 
{
    public virtual bool Equals(stsring? s) => throw null!;
static void M1(C c, string? s)
{
    if (c.Equals(s))
    {
        _ = s.ToString();
    }
    else
    {
        _ = s.ToString(); // 1
    }
}


}";
```

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >IEquatableEqualsMethod_ImplInBaseType [](start = 20, length = 37)

Please add a unit-test for scenario like this:
```
using System;

#nullable enable
class B
{
    public virtual bool Equals(string? s) => throw null!;
}

class C : B, IEquatable<string>
{
    public override bool Equals(string? s) => throw null!;
static void M1(C c, string? s)
{
    if (c.Equals(s))
    {
        _ = s.ToString();
    }
    else
    {
        _ = s.ToString(); // 1
    }
}


}";
```

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >IEquatableEqualsMethod_ImplInBaseType [](start = 20, length = 37)

Please add a unit-test for scenario like this:
```
using System;

#nullable enable
class A 
{
    public virtual bool Equals(string? s) => throw null!;
}

class B : A, IEquatable<string>
{
    public override sbool Equals(string? s) => throw null!;
}

class C : B
{
    public override bool Equals(string? s) => throw null!;

    static void M1(C c, string? s)
    {
        if (c.Equals(s))
        {
            _ = s.ToString();
        }
        else
        {
            _ = s.ToString(); // 1
        }
    }
}";
```

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 2]
```diff
@@ -3757,45 +3757,46 @@ private void LearnFromEqualsMethod(MethodSymbol method, BoundCall node, TypeWith
...
                     return true;
                 }
 
-                var implementationMethod = method.ContainingType.FindImplementationForInterfaceMember(constructedMethod);
-                return method.Equals(implementationMethod);
+                // check whether 'method', when called on this receiver, is an implementation of 'constructedMethod'.
+                for (var baseType = receiverType; baseType is object; baseType = baseType.BaseTypeNoUseSiteDiagnostics)
+                {
+                    var implementationMethod = baseType.FindImplementationForInterfaceMember(constructedMethod);
+                    for (var overriddenMethod = method; overriddenMethod is object; overriddenMethod = overriddenMethod.OverriddenMethod)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >for (var overriddenMethod = method; overriddenMethod is object; overriddenMethod = overriddenMethod.OverriddenMethod) [](start = 20, length = 117)

Is there a reason to enter the loop when implementationMethod is null?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: No.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 3]
```diff
@@ -3757,45 +3757,46 @@ private void LearnFromEqualsMethod(MethodSymbol method, BoundCall node, TypeWith
...
                 // FindImplementationForInterfaceMember doesn't check if this method is itself the interface method we're looking for
                 if (constructedMethod.Equals(method))
                 {
                     return true;
                 }
 
-                var implementationMethod = method.ContainingType.FindImplementationForInterfaceMember(constructedMethod);
-                return method.Equals(implementationMethod);
+                // check whether 'method', when called on this receiver, is an implementation of 'constructedMethod'.
+                for (var baseType = receiverType; baseType is object; baseType = baseType.BaseTypeNoUseSiteDiagnostics)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >baseType is object [](start = 50, length = 18)

For the negative case, we always traverse the entire inheritance hierarchy. We also always check all overridden methods, even those that are declared "below" ```baseType```, those will never be returned by ```FindImplementationForInterfaceMember```. I think this is an overkill.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Would this approach work?
```
for (var baseType = receiverType; baseType is object;)
{
    var implementationMethod = baseType.FindImplementationForInterfaceMember(constructedMethod);
    if (method.Equals(implementationMethod))
    {
        return true;
     }

    if (method.ContainingType.Equals(baseType))
    {
        method = method.OverriddenMethod
        baseType = method?.ContainingType;
    }
    else
    {
        baseType = baseType.BaseTypeNoUseSiteDiagnostics
    }
}
```

---
In reply to: [384828048](https://github.com/dotnet/roslyn/pull/41918#discussion_r384828048) [](ancestors = 384828048)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 4]
```diff
@@ -117959,6 +117959,161 @@ static void M1(C c, string? s)
...
+        }
+
+        [Fact, WorkItem(40577, "https://github.com/dotnet/roslyn/issues/40577")]
+        public void IEquatableEqualsMethod_ExplicitImplInDerivedType()
+        {
+            var source = @"
+using System;
+
+#nullable enable
+class B : IEquatable<string>
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >IEquatable<string> [](start = 10, length = 18)

It feels like we are missing a test for scenario when B doesn't implement the interface, but has the method.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 3 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Well, doing ```baseType = method?.ContainingType;``` is wrong. We should do ```baseType = baseType.BaseTypeNoUseSiteDiagnostics``` for both cases, but ```break``` once ```method``` is null.

---
In reply to: [384830098](https://github.com/dotnet/roslyn/pull/41918#discussion_r384830098) [](ancestors = 384830098,384828048)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Also, to handle some cases that can only arise from metadata we probably should put the loop through overridden methods back. Here is the new revision:
```
for (var baseType = receiverType; baseType is object && method is object; baseType = baseType.BaseTypeNoUseSiteDiagnostics)
{
    var implementationMethod = baseType.FindImplementationForInterfaceMember(constructedMethod);
    if (implementationMethod is object)
    {
        for (var overriddenMethod = method; overriddenMethod is object; overriddenMethod = overriddenMethod.OverriddenMethod)
        {
            if (overriddenMethod.Equals(implementationMethod))
            {
                return true;
            }
        }
    }

    if (method.ContainingType.Equals(baseType))
    {
        method = method.OverriddenMethod
    }
}
```


---
In reply to: [384834692](https://github.com/dotnet/roslyn/pull/41918#discussion_r384834692) [](ancestors = 384834692,384830098,384828048)

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 5)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: I think I have done part of your suggestion by bailing out after checking a `baseType` when it is the same as the `method.ContainingType`.

For the other part: does a method being "below" the `baseType` mean that the method is declared in a derived type? Is this really a distinct optimization or is it a different way of saying the same thing as the first optimization? Maybe we can sync offline tomorrow?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 5]
```diff
@@ -3757,45 +3757,55 @@ private void LearnFromEqualsMethod(MethodSymbol method, BoundCall node, TypeWith
...
+                            {
+                                return true;
+                            }
+                        }
+                    }
+
+                    // No point checking beyond the base type in which this method is actually declared.
+                    if (baseType.Equals(method.ContainingType))
+                    {
+                        break;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >break; [](start = 24, length = 6)

I don't think that is correct. Existing tests should probably catch that. If they don't, we should come up with one. Instead of breaking, we should do ```method = method.OverriddenMethod;```, I think.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 6]
```diff
@@ -3757,45 +3757,55 @@ private void LearnFromEqualsMethod(MethodSymbol method, BoundCall node, TypeWith
...
+                    if (implementationMethod is object)
+                    {
+                        for (var overriddenMethod = method; overriddenMethod is object; overriddenMethod = overriddenMethod.OverriddenMethod)
+                        {
+                            if (overriddenMethod.Equals(implementationMethod))
+                            {
+                                return true;
+                            }
+                        }
+                    }
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >} [](start = 20, length = 1)

Also, it feels like at the end of this block we can advance  the baseType to the containing type of the ```implementationMethod```. Because every type in between will yield the same method. And then we should make sure we adjust ```method``` to the first overridden method above that type.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 7]
```diff
@@ -3757,45 +3757,55 @@ private void LearnFromEqualsMethod(MethodSymbol method, BoundCall node, TypeWith
...
                 }
 
-                var implementationMethod = method.ContainingType.FindImplementationForInterfaceMember(constructedMethod);
-                return method.Equals(implementationMethod);
+                // check whether 'method', when called on this receiver, is an implementation of 'constructedMethod'.
+                for (var baseType = receiverType; baseType is object; baseType = baseType.BaseTypeNoUseSiteDiagnostics)
+                {
+                    var implementationMethod = baseType.FindImplementationForInterfaceMember(constructedMethod);
+                    if (implementationMethod is object)
+                    {
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >{ [](start = 20, length = 1)

Another optimization that we can do here is bail out if ```implementationMethod``` is an interface method. We need to have a test with default interface implementations anyway.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 8]
```diff
@@ -3757,45 +3757,55 @@ private void LearnFromEqualsMethod(MethodSymbol method, BoundCall node, TypeWith
...
+                        {
+                            if (overriddenMethod.Equals(implementationMethod))
+                            {
+                                return true;
+                            }
+                        }
+                    }
+
+                    // No point checking beyond the base type in which this method is actually declared.
+                    if (baseType.Equals(method.ContainingType))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >if [](start = 20, length = 2)

If ```implementationMethod``` is null, is there a good reason to continue?

**Comment by RikkiGibson** [comment]
Temporarily marking for personal review so I can start working on the WIP on another machine.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 9]
```diff
@@ -3757,45 +3757,78 @@ private void LearnFromEqualsMethod(MethodSymbol method, BoundCall node, TypeWith
...
+                    // class A -> B -> C -> D
+                    // method virtual B.Equals -> override D.Equals
+                    //
+                    // we would potentially check:
+                    // 1. D.Equals when called on D, then B.Equals when called on D
+                    // 2. B.Equals when called on C
+                    // 3. B.Equals when called on B
+                    // 4. give up when checking A, since B.Equals is not overriding anything in A
+
+                    if (baseType.Equals(method.ContainingType))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >if (baseType.Equals(method.ContainingType)) [](start = 20, length = 43)

I think we should be able to do better here and, in some cases jump over multiple base types and overridden methods. Basically, the next base type on which we should call ```FindImplementationForInterfaceMember``` should be above the ```implementationMethod.ContainingType```. For any type in between, ```FindImplementationForInterfaceMember``` is going to return the same ```implementationMethod```, but we already checked it. Consider advancing ```baseType``` here in a loop until we get to ```implementationMethod.ContainingType```. While doing so, also advance ```method``` as we pass through the bases.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LoweredDynamicOperationFactory.cs [hunk 10]
```diff
@@ -698,7 +698,7 @@ private static NamedTypeSymbol CreateCallSiteContainer(SyntheticBoundNodeFactory
 
             if (factory.TopLevelMethod.IsGenericMethod)
             {
-                return synthesizedContainer.Construct(factory.TopLevelMethod.TypeParameters.Cast<TypeParameterSymbol, TypeSymbol>());
+                return synthesizedContainer.Construct(factory.TopLevelMethod.TypeParameters);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LoweredDynamicOperationFactory.cs]: >return synthesizedContainer.Construct(factory.TopLevelMethod.TypeParameters); [](start = 16, length = 77)

It is not clear what motivated this change and how it is related to the purpose of this PR

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 11]
```diff
@@ -3757,45 +3757,78 @@ private void LearnFromEqualsMethod(MethodSymbol method, BoundCall node, TypeWith
...
+                        // we know no base type will implement this interface member either
+                        return false;
                     }
-                }
 
-                Debug.Assert(constructedMethod != null, "the original definition is present but the constructed method isn't present");
+                    if (implementationMethod.ContainingType.IsInterface)
+                    {
+                        // this doesn't make sense because an interface can only explicitly implement a method from its base interface.
+                        return false;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >return false; [](start = 24, length = 13)

Do we have a test for this code path?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 9 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Consider coming up with a test scenario and walking through this optimization under debugger to observe its effect.

---
In reply to: [390475202](https://github.com/dotnet/roslyn/pull/41918#discussion_r390475202) [](ancestors = 390475202)

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 5)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LoweredDynamicOperationFactory.cs (hunk 10 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LoweredDynamicOperationFactory.cs]: This must have been committed by accident, will revert.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 12]
```diff
@@ -3757,45 +3760,93 @@ private void LearnFromEqualsMethod(MethodSymbol method, BoundCall node, TypeWith
...
                 {
-                    return true;
+                    var implementationMethod = baseType.FindImplementationForInterfaceMember(constructedMethod);
+                    if (implementationMethod is null)
+                    {
+                        // we know no base type will implement this interface member either
+                        return false;
+                    }
+
+                    // 'method' definitely won't match if the implementation is explict.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >/ 'method' definitely won't match if the implementation is explict. [](start = 21, length = 67)

I do not think this is correct. It is definitely possible to get a callable method defined in metadata that implements interface explicitly. That method, BTW, can explicitly implement even an unrelated interface. Please, add a tests for both situations. I think there was no problem with the ```if (implementationMethod.ContainingType.IsInterface)``` check, you just needed to add a test.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 9 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: I think I understand now. Thanks for the explanation.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 12 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: In order to test this I need to define the implementing class in IL right? Are there existing tests I should look at as a starting point for this?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: > In order to test this I need to define the implementing class in IL right? Are there existing tests I should look at as a starting point for this?

- You can define a type in VB, all interface implementations in VB are explicit. 
- You can decompile a C# type with explicit implementation and remove the interface name prefix form method's name and make it public

---
In reply to: [390628812](https://github.com/dotnet/roslyn/pull/41918#discussion_r390628812) [](ancestors = 390628812)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: We have a helper CreateCompilationWithIL to "include" IL into a compilation

---
In reply to: [390630378](https://github.com/dotnet/roslyn/pull/41918#discussion_r390630378) [](ancestors = 390630378,390628812)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 13]
```diff
@@ -3757,45 +3760,93 @@ private void LearnFromEqualsMethod(MethodSymbol method, BoundCall node, TypeWith
...
+                    // we step through the intermediate bases in order to skip unnecessary override methods.
+                    while (!baseType.Equals(implementationMethod.ContainingType))
+                    {
+                        baseType = baseType.BaseTypeNoUseSiteDiagnostics;
+                        // the implementation method must be contained in this 'baseType' or one of its bases.
+                        Debug.Assert(baseType is object);
+
+                        // since we're about to move on to the base of 'method.ContainingType',
+                        // we know the implementation could only be an overridden method of 'method'.
+                        if (baseType.Equals(method.ContainingType))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >if (baseType.Equals(method.ContainingType)) [](start = 24, length = 43)

I think this should be performed before we advance the base. Otherwise, we will not move from a method that is in the original base.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >method [](start = 44, length = 6)

It looks like this can cause a NullReferenceException, if ```method``` becomes null on the previous iteration. Please add a test for a scenario like that.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 14]
```diff
@@ -118100,6 +117987,414 @@ static void M1(C c, string? s)
...
+        public void IEquatableEqualsMethod_Override()
+        {
+            var source = @"
+using System;
+
+#nullable enable
+class B : IEquatable<string>
+{
+    public virtual bool Equals(string? s) => throw null!;
+}
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >: s.ToString(); // 1 [](start = 12, length = 20)

It is fine to keep this test, but the interesting scenario is when a class implements I1 and we call Equals on that class.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 15]
```diff
@@ -3757,45 +3760,93 @@ private void LearnFromEqualsMethod(MethodSymbol method, BoundCall node, TypeWith
...
-                isWellKnownEqualityMethodOrImplementation(compilation, method, WellKnownMember.System_IEquatable_T__Equals))
+                isWellKnownEqualityMethodOrImplementation(compilation, method, receiverType.Type, WellKnownMember.System_IEquatable_T__Equals))
             {
                 Debug.Assert(arguments.Length == 1);
                 learnFromEqualsMethodArguments(node.ReceiverOpt, receiverType, arguments[0], results[0].RValueType);
                 return;
             }
 
-            static bool isWellKnownEqualityMethodOrImplementation(CSharpCompilation compilation, MethodSymbol method, WellKnownMember wellKnownMember)
+            static bool isWellKnownEqualityMethodOrImplementation(CSharpCompilation compilation, MethodSymbol method, TypeSymbol receiverType, WellKnownMember wellKnownMember)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >isWellKnownEqualityMethodOrImplementation [](start = 24, length = 41)

Do we have a test covering scenario when the name of the implementing method doesn't match the name of the method it implements? It can be easily created with VB or IL.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 11)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 13 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Also make sure to cover scenario when ```implementationMethod``` and ```method``` are in the same type

---
In reply to: [390634302](https://github.com/dotnet/roslyn/pull/41918#discussion_r390634302) [](ancestors = 390634302)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 11 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: I added some tests related to explicit implementations, including callable explicit implementations compiled from VB, but I wasn't able to think of how to actually hit this return statement.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 13 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: > Also make sure to cover scenario when ```implementationMethod``` and ```method``` are in the same type

I think this is covered by tests where the derived type has an explicit implementation of the interface method as well as an override of an implicit implementation from the base type. I'll follow up to make sure I've actually addressed this.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 15 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Done

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 14 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Done

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 13 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Done

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 12 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: I think I've added the suggested tests for callable explicit implementations. But it feels like I'm still missing something.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 11 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: > I added some tests related to explicit implementations, including callable explicit implementations compiled from VB, but I wasn't able to think of how to actually hit this return statement.

Doesn't the test I suggested with a class implementing an interface which implements IEquatable.Equals hit this path?

---
In reply to: [390700717](https://github.com/dotnet/roslyn/pull/41918#discussion_r390700717) [](ancestors = 390700717)

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: This scenario doesn't hit it. Maybe I misunderstood:

```cs
interface I1 : IEquatable<string?>
{
    bool IEquatable<string?>.Equals(string? s) => throw null!;
}

class C : I1
{
    void M1(string? s)
    {
        _ = this.Equals(s)
            ? s.ToString()
            : s.ToString(); // 1
    }
}
```

This is tested in `IEquatableEqualsMethod_DefaultImplementation_02`

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: I also tried an additional scenario in IL:

```il
.class interface public auto ansi abstract I1
    implements class [System.Runtime]System.IEquatable`1<string>
{
    // Methods
    .method public final hidebysig virtual 
    	instance bool MyEquals (
    		string other
    	) cil managed 
    {
    	.override method instance bool class [System.Runtime]System.IEquatable`1<string>::Equals(!0)
    	// Method begins at RVA 0x2050
    	// Code size 2 (0x2)
    	.maxstack 8
    	IL_0000: ldc.i4.0
    	IL_0001: ret
    } // end of method I1::'System.IEquatable<System.String>.Equals'
} // end of class I1
```

```cs
#nullable enable

class C : I1
{
    void M1(string? s)
    {
        _ = this.MyEquals(s)
            ? s.ToString()
            : s.ToString(); // 1
    }
}
```

In this scenario, the default interface method doesn't seem to be callable directly from the deriving class, even though the method is public. changing the interface to a class in the IL seems to make it callable.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: > This is tested in IEquatableEqualsMethod_DefaultImplementation_02

Does the signature of the Equals method called by M1 match the signature of ```IEquatable<string?>.Equals```?

---
In reply to: [391258729](https://github.com/dotnet/roslyn/pull/41918#discussion_r391258729) [](ancestors = 391258729)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: > In this scenario, the default interface method doesn't seem to be callable directly from the deriving class, even though the method is public. changing the interface to a class in the IL seems to make it callable.

Making interface implementation callable is not a goal here. The goal is to find an implementation method that is in the interface, ```FindImplementationForInterfaceMember``` doesn't really care whether the method is callable or not.

---
In reply to: [391259461](https://github.com/dotnet/roslyn/pull/41918#discussion_r391259461) [](ancestors = 391259461)

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Thanks, I think it's clicked for me now. Pushed a new test that hits the code path.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 16]
```diff
@@ -3739,15 +3739,16 @@ private void LearnFromEqualsMethod(MethodSymbol method, BoundCall node, TypeWith
                 || method.MethodKind != MethodKind.Ordinary
                 || method.ReturnType.SpecialType != SpecialType.System_Boolean
                 || (method.Name != SpecialMembers.GetDescriptor(SpecialMember.System_Object__Equals).Name
-                    && method.Name != SpecialMembers.GetDescriptor(SpecialMember.System_Object__ReferenceEquals).Name))
+                    && method.Name != SpecialMembers.GetDescriptor(SpecialMember.System_Object__ReferenceEquals).Name
+                    && !method.IsExplicitInterfaceImplementation()))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >!method.IsExplicitInterfaceImplementation() [](start = 23, length = 43)

I don't think this is going to help with the name mismatch. For example, the method itself might not implement an interface, but the method it overrides does. Please add a test for a scenario like that. Perhaps we should traverse all overrides and check all of them?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 12 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: > I think I've added the suggested tests for callable explicit implementations. But it feels like I'm still missing something.

Still have this feeling?

---
In reply to: [390702059](https://github.com/dotnet/roslyn/pull/41918#discussion_r390702059) [](ancestors = 390702059)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 17]
```diff
@@ -3757,45 +3758,89 @@ private void LearnFromEqualsMethod(MethodSymbol method, BoundCall node, TypeWith
...
-                        break;
+                        // we know no base type will implement this interface member either
+                        return false;
                     }
-                }
 
-                Debug.Assert(constructedMethod != null, "the original definition is present but the constructed method isn't present");
+                    if (implementationMethod.ContainingType.IsInterface)
+                    {
+                        // this doesn't make sense because an interface can only explicitly implement a method from its base interface.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >this doesn't make sense [](start = 27, length = 23)

Consider saying that "this method cannot be called directly from source" instead of "this doesn't make sense".

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 13 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >> Also make sure to cover scenario when ```implementationMethod``` and ```method``` are in the same type

>I think this is covered by tests where the derived type has an explicit implementation of the interface method as well as an override of an implicit implementation from the base type. I'll follow up to make sure I've actually addressed this. 

Let's imagine that ```implementationMethod``` and ```method``` are in the same type and that type is the ```baseType```. Are we going to get here? But I think we would want to advance the ```method``` in that case. 

---
In reply to: [390644578](https://github.com/dotnet/roslyn/pull/41918#discussion_r390644578) [](ancestors = 390644578,390634302)

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 14)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 12 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: No, now that I've figured out what scenario actually makes us find an 'implementationMethod' defined in an interface, I feel more confident.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 13 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Fixed

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 16 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Fixed

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 17 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Fixed

**Comment by AlekseyTs** [comment]
@RikkiGibson It looks like CI jobs are timing out. Could that be related to the last commit?

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler Please review
