### PR TITLE
Fixes incorrect codegen where locals could be optimized across implicit branches

### LINKED ISSUE #5530: Invalid IL when struct is constructed in-place and args are trivial values.
Repro:

```C#

    class Program
    {
        private static S1[] arr = new S1[1];

        struct S1
        {
            public int a, b;
            public S1(int a, int b)
            {
                this.a = a;
                this.b = b;
            }
        }

        static void Main(string[] args)
        {
            var arg = System.Math.Max(1, 2);
            var val = new S1(arg, arg);
            arr[0] = val;
            System.Console.WriteLine(arr[0].a);
        }
    }

```

[ : Program::Main][mdToken=0x6000001][offset 0x0000000A][found address of value 'Program+S1'][expected Int32] Unexpected type on the stack.
[ : Program::Main][mdToken=0x6000001][offset 0x0000000A][found address of value 'Program+S1'][expected Int32] Unexpected type on the stack.
[ : Program::Main][mdToken=0x6000001][offset 0x0000000A][found Int32] Call to .ctor only allowed to initialize this pointer from within a .ctor. Try newobj.

### PR DESCRIPTION
**Pull request by VSadov**
Actually this fixes two issues:
1) Conservatively, we do not want to allow local values to flow into struct constructors since those may be emitted-in-place and the receiver on the stack would prevent access to the values. The suppression was modeled as a fictional goto/label arc around the ObjectCreation node, but that is an overkill.
It is more appropriate to just simulate a possible push/pop of the receiver.

2) There was a subtle flaw in how local def-use spans were rejected when crossing into control flow regions. The code tried using the same intersection routine as for detecting conflicts between regular locals and that was not strict enough in this case. As a result we could allow invalid optimizations leading to #5530

Fixes #5530

### CODE REVIEW

**Comment by VSadov** [comment]
@AlekseyTs @jaredpar @agocke @TyOverby - please review.

File: src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs [hunk 1]
```diff
@@ -135,6 +135,8 @@ private static void RemoveIntersectingLocals(Dictionary<LocalSymbol, LocalDefUse
                 }
             }
 
+            var dummyCnt = defs.Count;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs]: Why is this a "dummy" count? Rename or comment?

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs]: It looks like we can add something to the ```defs``` and ```dummyCnt``` represents its length before we do that. Could we call it ```initialCnt``` instead?

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CodeGen/Optimizer.cs]: Ok, after expanding the code above, the name started to make sense to me.

**Comment by AlekseyTs** [comment]
LGTM. Do we need to fix VB?

**Comment by VSadov** [comment]
@AlekseyTs - yes, I think we need to do the same change to VB.
