### PR TITLE
MSBuildWorkspace needs to set a property to ensure that project references are built with the correct configuration

### LINKED ISSUE #30174: MSBuildWorkspace is not honoring Configuration property for project references
**Version Used**: 2.9.0

**Steps to Reproduce**:

1. Have project with project references, build it in Release configuration and make sure no Debug binaries are present
2. Create MSBuildWorkspace with property Configuration set to Release
3. Set LoadMetadataForReferencedProjects to true
4. Open project that have project reference using OpenProjectAsync
5. Try get compilation using GetCompilationAsync

**Expected Behavior**:
Compilation is returned with referenced project loaded as MetadataReference

**Actual Behavior**:
ArgumentException with message "Reference of type 'Microsoft.CodeAnalysis.UnresolvedMetadataReference' is not valid for this compilation." is thrown.
Further analysis showed that the UnresolvedMetadataReference points to Debug output path of referenced project.

Minimal repro implemented here: https://github.com/jirikopecky/roslyn-issue-repro

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes #30174

This change fixes an issue with MSBuildWorkspace's design to resolve project references by matching the output path of a referenced project with the reference path that is passed in the compiler command-line args. That approach works fine until the user tries to call `OpenProjectAsync(...)` on an `MSBuildWorkspace` that was created with the `Configuration` property set to `Release`. In that scenario, the `Configuration` property that was set globally doesn't get used for project references. Instead, referenced projects are built with their default `Configuration` and `Platform` values, which results in the output paths of those referenced projects being different (e.g. `bin\Debug` instead of `bin\Release`). So, project references aren't resolved properly.

The reason that the referenced projects don't use the globally set `Configuration` property is due to the following condition in [`Microsoft.Common.CurrentVersion.targets`](https://github.com/Microsoft/msbuild/blob/d1af34332573aab3de6482ac1d0b35e1d7951564/src/Tasks/Microsoft.Common.CurrentVersion.targets#L1473):

```XML
<ShouldUnsetParentConfigurationAndPlatform Condition="'$(ShouldUnsetParentConfigurationAndPlatform)' == '' and ('$(BuildingInsideVisualStudio)' == 'true' or '$(BuildingSolutionFile)' == 'true')">true</ShouldUnsetParentConfigurationAndPlatform>
```

That condition causes `ShouldUnsetParentConfigurationAndPlatform` to be set to true because `MSBuildWorkspace` sets `BuildingInsideVisualStudio` to true. And, when set to true, this property causes the global configuration not to be used for project references. So, my fix is to set the property to false in `MSBuildWorkspace`, which addresses the problem. In addition, there were situations in `MSBuildWorkspace` where the property would not flow properly to the build and most of the additional changes are about addressing that.

I'm cc'ing @rainersigwald here to verify that this is a reasonable fix and throw an exception if there's a better way to handle this situation.

cc @jinujoseph and @ManishJayaswal

### CODE REVIEW

**Comment by Pilchie** [comment]
I'm not convinced this is the right approach for when we're opening `.sln` files.  I think the problem is that in that case `Configuration` in the `MSBuildWorkspace` should probably mean the *solution configuration*, which would mean that we would want to leave this set, but have a way of building a map from *solution configuration* to *project configuration*, and have each project get it's *project configuration* somehow.  Not sure what that somehow is though :(

**Comment by DustinCampbell** [comment]
@Pilchie: We don't support solution configurations in `MSBuildWorkspace` today, so that's kind of orthogonal to the issue at hand, isn't it? In `MSBuildWorkspace`, the solution file is *only* used to gather a set of projects to load and then it loads 'em one at a time. The only facility we provide to users to handle configuration is to allow them to set global MSBuild properties. Eventually, it'd be great if we had proper solution configuration support, but the fact that we don't support them now shouldn't affect whether we set this property on not or whether or not this is the right approach.

**Comment by Pilchie** [comment]
I guess my point is that I'm not sure what scenario you're solving with this change.  I guess the most common case is that every project in a solution has the same value for *configuration* that the solution has for *solution configuration*, so this makes the occurrence of the mismatch more rare?

In general the idea of reading from a .sln file and then applying a single arbitrary `Configuration` property to all projects doesn't really make sense though.  I guess we didn't think through configurations enough when we first built MSBuildWorkspace.

**Comment by DustinCampbell** [comment]
The scenario is when the user has specified a Configuration or a Platforms different from the default and calls OpenProjectAsync and there is a project reference. Would you like me to add APIs to support solution configurations? If so, I can close this PR and go back to the drawing board.

**Comment by DustinCampbell** [comment]
Note that solution configuration support doesn't help OpenProjectAsync

**Comment by Pilchie** [comment]
Ah. `OpenProjectAsync` versus `OpenSolutionAsync` is an interesting distinction.  I can definitely see how this makes sense for `OpenProjectAsync`, and like I said, it drastically reduces the incidence of the problem for `OpenSolutionAsync`, so I'm not against it.

Will take a look at the details tomorrow.

File: src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs [hunk 1]
```diff
@@ -38,107 +39,66 @@ internal class ProjectBuildManager
             // don't actually run the compiler
             { PropertyNames.SkipCompilerExecution, bool.TrueString },
 
-            { PropertyNames.ContinueOnError, PropertyValues.ErrorAndContinue }
+            { PropertyNames.ContinueOnError, PropertyValues.ErrorAndContinue },
+
+            // this ensures that the parent project's configuration and platform will be used for
+            // referenced projects. So, setting Configuration=Release will also cause any project
+            // references to also be built with Configuration=Release. This is necessary for getting
+            // the correct output path from project references.
```
Comment (rainersigwald) [inline src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs]:
```suggestion
            // a more-likely-to-be-correct output path from project references.
```

? It's correct for the started-with-a-single-project case, and correct in the solution case if there are no solution-configuration shenanigans, but possibly wrong if there are.

**Comment by DustinCampbell** [comment]
@rainersigwald: FWIW, we don't actually open solutions any differently than projects. Essentially, we just read the solution to get the list of projects and then it's effectively just a bunch of separate project loads. The only significant functional difference is that `SolutionDir` gets set. So, I wouldn't expect the solution-configuration map to ever be involved, though that's probably a feature for later :smile:.

File: src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs (hunk 1 above)
Comment (DustinCampbell) [reply src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs]: That comment tweak expresses the right amount of paranoia. We aren't doing solution-configuration-shenanigans today, but might in the future.

Comment (rainersigwald) [reply src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs]: > the right amount of paranoia

#lifegoals

**Comment by DustinCampbell** [comment]
Will rebase this change to master once https://github.com/dotnet/roslyn/pull/30600 is merged.

**Comment by DustinCampbell** [comment]
Thanks @jasonmalinowski!

File: src/Workspaces/MSBuildTest/NetCoreTests.cs [hunk 2]
```diff
@@ -32,12 +33,29 @@ private void DotNetRestore(string solutionOrProjectFileName)
...
+
+        private void DotNetRestore(string solutionOrProjectFileName)
+        {
+            var arguments = $@"msbuild ""{solutionOrProjectFileName}"" /t:restore /bl:{Path.Combine(SolutionDirectory.Path, "restore.binlog")}";
+            RunDotNet(arguments);
+        }
+
+        private void DotNetBuild(string solutionOrProjectFileName, string configuration = null)
+        {
+            var arguments = $@"msbuild ""{solutionOrProjectFileName}"" /bl:{Path.Combine(SolutionDirectory.Path, "restore.binlog")}";
```
Comment (Pilchie) [inline src/Workspaces/MSBuildTest/NetCoreTests.cs]: Rename the log.

File: src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs [hunk 3]
```diff
@@ -53,92 +56,43 @@ internal class ProjectBuildManager
...
-            }
-
-            // We couldn't find a project with this path and the set of global properties we expect.
-            return null;
+            _additionalGlobalProperties = additionalGlobalProperties ?? ImmutableDictionary<string, string>.Empty;
         }
 
-        public async Task<(MSB.Evaluation.Project project, DiagnosticLog log)> LoadProjectAsync(
-            string path, IDictionary<string, string> globalProperties, CancellationToken cancellationToken)
+        private ImmutableDictionary<string, string> AllGlobalProperties()
```
Comment (Pilchie) [inline src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs]: Why a method?

File: src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs [hunk 4]
```diff
@@ -147,23 +101,49 @@ internal class ProjectBuildManager
...
 
-            var (project, _) = await LoadProjectAsync(path, globalProperties, cancellationToken).ConfigureAwait(false);
+            // This tries to get the project output path and retrieving the evaluated $(TargetPath) property.
+
+            var (project, _) = await LoadProjectAsync(path, cancellationToken).ConfigureAwait(false);
             return project?.GetPropertyValue(PropertyNames.TargetPath);
         }
 
-        public void Start()
+        public void Start(IDictionary<string, string> globalProperties = null)
```
Comment (Pilchie) [inline src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs]: I don't understand why this take in new properties instead of just using `AllGlobalProperties()`.

File: src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs [hunk 5]
```diff
@@ -44,13 +44,13 @@ internal class ProjectBuildManager
 
         private readonly ImmutableDictionary<string, string> _additionalGlobalProperties;
 
-        private MSB.Evaluation.ProjectCollection _projectCollection;
-        private MSBuildDiagnosticLogger _logger;
-        private bool _started;
+        private MSB.Evaluation.ProjectCollection _batchBuildProjectCollection;
+        private MSBuildDiagnosticLogger _batchBuildLogger;
+        private bool _batchBuildStarted;
```
Comment (Pilchie) [inline src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs]: 👍

File: src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs (hunk 3 above)
Comment (DustinCampbell) [reply src/Workspaces/Core/MSBuild/MSBuild/Build/ProjectBuildManager.cs]: I think I had fantasies of a more significant computation originally. I agree that it's better as a property.
