### PR TITLE
Disallow generating IEquatable for Ref Struct

### LINKED ISSUE #25708: "Generate Equals" refactorings produce faulty code when using ref structs
**Version Used**: VS 15.7 Preview 2 (2.8.0.62716)

**Steps to Reproduce**:

1. Copy the source below into a C# source file.
2. Invoke the Quick Fix menu at the marked location and select either "Generate Equals" or "Generate Equals and GetHashCode".
3. Make sure the field "r" is selected in the list, and "Implement IEquatable<ReproA>" is checked. Press "OK".

```c#
ref struct ReproA
{
	ReproB r;

	$$
}

ref struct ReproB
{
}
```

**Expected Behavior**: I'm not sure. (Is it even possible to determine equality/hash code for ref structs with the "traditional" approach?)
VS could a) not suggest these refactorings inside ref structs, and b) not suggest ref struct members in the member selection list.

**Actual Behavior**: The class looks something like this and cannot compile:

```c#
ref struct ReproA : IEquatable<ReproA> // Errors CS0306, CS8343
{
	ReproB r; // Warning CS0169

	public override bool Equals(object obj)
	{
		return obj is ReproA && Equals((ReproA)obj); // Warning CS0184, error CS0030
	}

	public bool Equals(ReproA other)
	{
		return EqualityComparer<ReproB>.Default.Equals(r, other.r); // Error CS0306
	}

	public override int GetHashCode()
	{
		return -947233955 + EqualityComparer<ReproB>.Default.GetHashCode(r); // Error CS0306
	}
}
```

### PR DESCRIPTION
**Pull request by ThadHouse**
Unlike Equals(object), which discussion seems to prefer generating broken code, generating IEquatable is always invalid

This PR makes it so IEquatable can not be generated as a fix for ref structs.

Fixes #25708

### CODE REVIEW

File: src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions_CreateEqualsMethod.cs [hunk 1]
```diff
@@ -107,6 +107,13 @@ public static IMethodSymbol CreateEqualsMethod(this Compilation compilation, Imm
         {
             var statements = ArrayBuilder<SyntaxNode>.GetInstance();
 
+            // A ref like type can only return false from equals.
+            if (containingType.IsRefLikeType)
+            {
+                statements.Add(factory.ReturnStatement(factory.FalseLiteralExpression()));
+                statements.ToImmutableAndFree();
```
Comment (RikkiGibson) [inline src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions_CreateEqualsMethod.cs]: either the return value should be consumed or this builder should be freed in a different place.

Comment (ThadHouse) [reply src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions_CreateEqualsMethod.cs]: Fixed. Also fixed the tests to actually pass, was waiting for the solution to load.

**Comment by CyrusNajmabadi** [comment]
Can you add `Fixes #BugNumber` on the first line of your post?  it will hook up all teh github goodness here.

File: src/EditorFeatures/CSharpTest/GenerateFromMembers/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersTests.cs [hunk 2]
```diff
@@ -1721,6 +1721,55 @@ public bool Equals(Program other)
 parameters: CSharp6Implicit);
         }
 
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsGenerateEqualsAndGetHashCode)]
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/GenerateFromMembers/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersTests.cs]:
```suggestion
        [WorkItem(bug_number, "linktogithubbug")]
        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsGenerateEqualsAndGetHashCode)]
```

File: src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider.cs [hunk 3]
```diff
@@ -111,7 +111,7 @@ private async Task HandleNonSelectionAsync(CodeRefactoringContext context)
             if (equatableTypeOpt != null)
             {
                 var constructedType = equatableTypeOpt.Construct(containingType);
-                if (!containingType.AllInterfaces.Contains(constructedType))
+                if (!containingType.AllInterfaces.Contains(constructedType) && !containingType.IsRefLikeType)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider.cs]: Add comment explaining why this is appropriate here.

File: src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions_CreateEqualsMethod.cs [hunk 4]
```diff
@@ -107,6 +107,13 @@ public static IMethodSymbol CreateEqualsMethod(this Compilation compilation, Imm
         {
             var statements = ArrayBuilder<SyntaxNode>.GetInstance();
 
+            // A ref like type can only return false from equals.
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions_CreateEqualsMethod.cs]: add comment that doesn't explain what we're doing, but why we're doing it .

File: src/EditorFeatures/CSharpTest/GenerateFromMembers/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersTests.cs [hunk 5]
```diff
@@ -1721,6 +1721,55 @@ public bool Equals(Program other)
...
+{
+    public string s;
+
+    public override bool Equals(object obj)
+    {
+        return false;
+    }
+}",
+chosenSymbols: null,
+parameters: CSharp6Implicit);
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/GenerateFromMembers/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersTests.cs]: why C# 6.  did we even have ref-structs in c# 6?

**Comment by sharwell** [comment]
Next design meeting we will review whether this should silently ignore the "Generate IEquatable&lt;T>" box, or if it should disable it from the start.

**Comment by ThadHouse** [comment]
@sharwell 

Based on discussions and the code, where the skip was added it will disable the "Generate IEquatable" box. It's never added as a picker option if the if statement is not entered.

File: src/EditorFeatures/CSharpTest/GenerateFromMembers/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersTests.cs (hunk 2 above)
Comment (ThadHouse) [reply src/EditorFeatures/CSharpTest/GenerateFromMembers/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersTests.cs]: Fixed

File: src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider.cs (hunk 3 above)
Comment (ThadHouse) [reply src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider.cs]: Fixed

File: src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions_CreateEqualsMethod.cs (hunk 4 above)
Comment (ThadHouse) [reply src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions_CreateEqualsMethod.cs]: Fixed

File: src/EditorFeatures/CSharpTest/GenerateFromMembers/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersTests.cs (hunk 5 above)
Comment (ThadHouse) [reply src/EditorFeatures/CSharpTest/GenerateFromMembers/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersTests.cs]: Fixed, I removed the option entirely.

**Comment by sharwell** [comment]
@ThadHouse That sounds like what we want. Can you include some screenshots?

**Comment by RikkiGibson** [comment]
@ThadHouse @CyrusNajmabadi @sharwell Are we still interested in taking this change?

**Comment by sharwell** [comment]
@RikkiGibson I think yes. If someone gets a chance to include a screenshot for this, it would be good.

File: src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider.cs [hunk 6]
```diff
@@ -176,7 +140,10 @@ private bool HasOperator(INamedTypeSymbol containingType, string operatorName)
             if (equatableTypeOpt != null)
             {
                 constructedType = equatableTypeOpt.Construct(containingType);
-                return !containingType.AllInterfaces.Contains(constructedType);
+
+                // A ref struct can never implement an interface, therefore never add IEquatable to the selection
+                // options if the type is a ref struct.
```
Comment (sharwell) [inline src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider.cs:145]: 📝 It seems like it would be easier to read this method in the following form:

```
if (containingType.IsRefLikeType)
{
  // A ref struct can never implement an interface, therefore never add IEquatable to the selection
  // options if the type is a ref struct.
  constructedType = null;
  return false;
}

var equatableTypeOpt = semanticModel.Compilation.GetTypeByMetadataName(typeof(IEquatable<>).FullName);
if (equatableTypeOpt != null)
{
  constructedType = equatableTypeOpt.Construct(containingType);
  return !containingType.AllInterfaces.Contains(constructedType);
}

constructedType = null;
return false;
```

Comment (sharwell) [reply src/Features/Core/Portable/GenerateEqualsAndGetHashCodeFromMembers/GenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider.cs:145]: I can see how this merge conflict resolution is the correct one (the PR originally implemented the check in the same form you used), but perhaps it could be simplified in a follow-up commit?

**Comment by tannergooding** [comment]
Is there an option for generating "effectively" `IEquatable<T>`? That is doing everything but adding the interface?
