### PR TITLE
Place TupleElementNamesAttribute on proper handles

### LINKED ISSUE #14844: Attributes for tuple names are applied to wrong targets in metadata
It looks like, in case of implemented interfaces and type parameter constraints, the TupleElementNames attributes are applied to type references. This is incorrect, type references are unique and are shared across all reference sites, which means that all attributes from entire program are applied to the same target. The attributes should be applied to individual records in InterfaceImpl and GenericParamConstraint tables instead.  
I believe the following unit-test demonstrates the problem:

```
        [Fact]
        public static void Test4()
        {
            var source1 = @"
public interface I1<T>{}

public interface I2 : I1<(int a, int b)> {}
public interface I3 : I1<(int c, int d)> {}
";

            var source2 = @"
class C1 : I2, I1<(int a, int b)> {}

class C2 : I3, I1<(int c, int d)> {}
";
            var comp1 = CreateCompilationWithMscorlib(source1, references: s_valueTupleRefs);
            comp1.VerifyDiagnostics();

            var comp2 = CreateCompilationWithMscorlib(source2, references: new [] { SystemRuntimeFacadeRef, ValueTupleRef, comp1.ToMetadataReference()});
            comp2.VerifyDiagnostics();

            var comp3 = CreateCompilationWithMscorlib(source2, references: new[] { SystemRuntimeFacadeRef, ValueTupleRef, comp1.EmitToImageReference() });
            comp3.VerifyDiagnostics();
        }
``` 

Observed: The following error is reported for comp3
```
                // (4,7): error CS8140: 'I1<(int c, int d)>' is already listed in the interface list on type 'C2' with different tuple element names, as 'I1<(int a, int b)>'.
                // class C2 : I3, I1<(int c, int d)> {}
                Diagnostic(ErrorCode.ERR_DuplicateInterfaceWithTupleNamesInBaseList, "C2").WithArguments("I1<(int c, int d)>", "I1<(int a, int b)>", "C2").WithLocation(4, 7)
```

Expected: No error because there should be no name mismatch. Note that the error isn't reported for compilation reference, it is reported only for metadata reference.

CC @VSadov, @jcouv, @agocke

### PR DESCRIPTION
**Pull request by agocke**
The previous code mistakenly put the TupleElementNamesAttribute on the
type ref for interface implementations and type parameter generic
constraints. This change moves the attribute to the actual interface
implementation and constraint handles, where it belongs.

Fixes #14844

### CODE REVIEW

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs [hunk 1]
```diff
@@ -203,6 +204,32 @@ public override string ToString()
...
+            comp1.VerifyDiagnostics();
+
+            var comp2 = CreateCompilationWithMscorlib(src2,
+                references: new[] { SystemRuntimeFacadeRef, ValueTupleRef, comp1.ToMetadataReference() });
+            comp2.VerifyDiagnostics();
+
+            var comp3 = CreateCompilationWithMscorlib(src2,
+                references: new[] { SystemRuntimeFacadeRef, ValueTupleRef, comp1.EmitToImageReference() });
+            comp3.VerifyDiagnostics();
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: Please add a corresponding test to VB.

**Comment by cston** [comment]
LGTM

File: src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs [hunk 2]
```diff
@@ -2072,6 +2070,17 @@ private void AddCustomAttributesToTable<T>(IEnumerable<T> parentList, Func<T, En
             }
         }
 
+        private void AddCustomAttributesToTable(ImmutableArray<HandleWithAttributes> genericConstraintAttributes)
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs]: >genericConstraintAttributes [](start = 85, length = 27)

This doesn't have to be a constraint, right? Consider renaming.

File: src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs [hunk 3]
```diff
@@ -2383,11 +2411,21 @@ private void PopulateGenericParameters(ImmutableArray<IGenericParameter> sortedG
...
                 {
-                    metadata.AddGenericParameterConstraint(
-                        genericParameter: genericParameterHandle,
-                        constraint: GetTypeHandle(refWithAttributes.TypeRef));
+                    if (builder == null)
+                    {
+                        builder = ArrayBuilder<HandleWithAttributes>.GetInstance();
+                    }
+
+                    builder.Add(new HandleWithAttributes(
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs]: >builder.Add(new HandleWithAttributes [](start = 20, length = 36)

Doc-comment for MetadataBuilder.AddCustomAttribute says: "Entries may be added in any order. The table is automatically sorted when serialized." which means that the code can be simplified if we simply add attributes right here. The same simplification can be applied to implemented interfaces as well.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs [hunk 4]
```diff
@@ -203,6 +204,32 @@ public override string ToString()
 ";
 
         [Fact]
+        [WorkItem(14844, "https://github.com/dotnet/roslyn/issues/14844")]
+        public void InterfaceImplAttributesAreNotSharedAcrossTypeRefs()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: >InterfaceImplAttributesAreNotSharedAcrossTypeRefs [](start = 20, length = 49)

Consider adding similar test for constraints.

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PETypeParameterSymbol.cs [hunk 5]
```diff
@@ -151,20 +151,20 @@ private ImmutableArray<TypeSymbol> GetDeclaredConstraintTypes()
...
             var moduleSymbol = containingType.ContainingPEModule;
-
-            EntityHandle[] constraints;
+            var metadataReader = moduleSymbol.Module.MetadataReader;
+            GenericParameterConstraintHandleCollection constraints;
 
             try
             {
-                constraints = moduleSymbol.Module.GetGenericParamConstraintsOrThrow(_handle);
+                constraints = metadataReader.GetGenericParameter(_handle).GetConstraints();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PETypeParameterSymbol.cs]: >constraints = metadataReader.GetGenericParameter(_handle).GetConstraints(); [](start = 16, length = 75)

It looks like we might need to extend try/catch because operations that used to be done by GetGenericParamConstraintsOrThrow are now done below.

File: src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PETypeParameterSymbol.vb [hunk 6]
```diff
@@ -165,25 +165,28 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols.Metadata.PE
             End If
 
             Dim moduleSymbol = containingType.ContainingPEModule
-            Dim constraints() As EntityHandle
+            Dim metadataReader = moduleSymbol.Module.MetadataReader
+            Dim constraints As GenericParameterConstraintHandleCollection
 
             Try
-                constraints = moduleSymbol.Module.GetGenericParamConstraintsOrThrow(_handle)
+                constraints = metadataReader.GetGenericParameter(_handle).GetConstraints()
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PETypeParameterSymbol.vb]: >metadataReader.GetGenericParameter(_handle).GetConstraints() [](start = 30, length = 60)

Similar to C#, might need to extend Try/Catch

File: src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs [hunk 7]
```diff
@@ -2368,8 +2377,27 @@ private void PopulateFileTableRows()
             }
         }
 
-        private void PopulateGenericParameters(ImmutableArray<IGenericParameter> sortedGenericParameters)
+        private struct HandleWithAttributes
+        {
+            private readonly EntityHandle _handle;
```
Comment (jcouv) [inline src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs]: You could remove the private fields (just use the read-only property).

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PETypeParameterSymbol.cs [hunk 8]
```diff
@@ -178,25 +178,28 @@ private ImmutableArray<TypeSymbol> GetDeclaredConstraintTypes()
                     tokenDecoder = new MetadataDecoder(moduleSymbol, containingType);
                 }
 
-                foreach (var constraint in constraints)
+                foreach (var constraintHandle in constraints)
                 {
-                    TypeSymbol typeSymbol = tokenDecoder.GetTypeOfToken(constraint);
+                    var constraint = metadataReader.GetGenericParameterConstraint(constraintHandle);
+                    var constraintTypeHandle = constraint.Type;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PETypeParameterSymbol.cs]: >constraintTypeHandle [](start = 24, length = 20)

Consider inlining temp.

File: src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PETypeParameterSymbol.vb [hunk 9]
```diff
@@ -165,25 +165,28 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols.Metadata.PE
...
                     tokenDecoder = New MetadataDecoder(moduleSymbol, containingMethod)
                 Else
                     tokenDecoder = New MetadataDecoder(moduleSymbol, containingType)
                 End If
 
-                For Each constraint In constraints
-                    Dim typeSymbol As typeSymbol = tokenDecoder.GetTypeOfToken(constraint)
+                For Each constraintHandle In constraints
+                    Dim constraint = metadataReader.GetGenericParameterConstraint(constraintHandle)
+                    Dim constraintTypeHandle = constraint.Type
```
Comment (jcouv) [inline src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PETypeParameterSymbol.vb]: Also consider inlining

File: src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs [hunk 10]
```diff
@@ -2072,6 +2061,17 @@ private void AddCustomAttributesToTable<T>(IEnumerable<T> parentList, Func<T, En
             }
         }
 
+        private void AddCustomAttributesToTable<T>(
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs]: >AddCustomAttributesToTable<T> [](start = 21, length = 29)

Does this method have to be generic? Can it simply take ```ImmutableArray<ICustomAttribute>```?

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PETypeParameterSymbol.cs [hunk 11]
```diff
@@ -151,63 +151,54 @@ private ImmutableArray<TypeSymbol> GetDeclaredConstraintTypes()
...
-            {
-                constraints = null;
-                Interlocked.CompareExchange(ref _lazyBoundsErrorInfo, new CSDiagnosticInfo(ErrorCode.ERR_BindToBogus, this), CSDiagnosticInfo.EmptyErrorInfo);
-            }
-
-            if (constraints != null && constraints.Length > 0)
-            {
-                var symbolsBuilder = ArrayBuilder<TypeSymbol>.GetInstance();
-                MetadataDecoder tokenDecoder;
+                var constraints = metadataReader.GetGenericParameter(_handle).GetConstraints();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PETypeParameterSymbol.cs]: >var [](start = 16, length = 3)

Please follow the guideline about not using ```var``` when type isn't explicitly spelled in the initializer.

**Comment by AlekseyTs** [comment]
>                 Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound).WithArguments("ITest33").WithLocation(1, 1),

It is not clear what caused this error to disappear.

---
Refers to: src/Compilers/CSharp/Test/Emit/Emit/NoPiaEmbedTypes.cs:4883 in 5b079ca. [](commit_id = 5b079ca0ed9ac61386c01cc226e73077ace177e4, deletion_comment = True)

**Comment by AlekseyTs** [comment]
Please add behavior tests for constraints CodeGenTupleTest.cs. Please add similar set of behavior tests for VB.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs (hunk 4 above)
Comment (agocke) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTupleTest.cs]: @AlekseyTs I don't see a way to make a similar test for constraints, since there's no error for a substituted type parameter and the constraint having differing tuple names.

Could you give me a hint on how to construct such a test? :)

**Comment by agocke** [comment]
@AlekseyTs Regarding the NoPia test, that additional line was added during the first implementation. What was happening was that the interface implementation check was causing an extra request for the type of ITest33, which is missing, which caused the extra error.

When I switched back to only loading the interface implementation itself, not the type, this extra error disappeared.

**Comment by agocke** [comment]
@AlekseyTs @jcouv I believe I've addressed your comments, please let me know if I missed anything.

File: src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.vb [hunk 12]
```diff
@@ -273,7 +273,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols.Metadata.PE
                     Dim interfaceHandle As EntityHandle = moduleSymbol.Module.MetadataReader.GetInterfaceImplementation(interfaceImpl).Interface
                     Dim typeSymbol As TypeSymbol = tokenDecoder.GetTypeOfToken(interfaceHandle)
 
-                    typeSymbol = DirectCast(TupleTypeDecoder.DecodeTupleTypesIfApplicable(typeSymbol, interfaceHandle, moduleSymbol), NamedTypeSymbol)
+                    typeSymbol = DirectCast(TupleTypeDecoder.DecodeTupleTypesIfApplicable(typeSymbol, interfaceImpl, moduleSymbol), NamedTypeSymbol)
```
Comment (jcouv) [inline src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.vb]: >interfaceImpl [](start = 102, length = 13)

Was some test affected by this change?

Comment (jcouv) [inline src/Compilers/VisualBasic/Portable/Symbols/Metadata/PE/PENamedTypeSymbol.vb]: Nevermind, the diff between commits 3 and 4 gave me the answer.

---
In reply to: [88167101](https://github.com/dotnet/roslyn/pull/15060#discussion_r88167101) [](ancestors = 88167101)

**Comment by jcouv** [comment]
Your PR targets master. Should it target dev15-rc2?

**Comment by agocke** [comment]
\+ @MattGertz For ask mode approval.

This PR is a backwards-incompatible change to how we read and write tuples in interface implementations and type constraints. It's unlikely that anyone is depending on the behavior now, but this change should go in ASAP to prevent people from taking dependencies and producing assemblies that can't be properly consumed with later versions of the compiler.

**Comment by agocke** [comment]
test this please
