### PR TITLE
Fix foreach spilling ref field to a local:

### LINKED ISSUE #30016: foreach (ref var) doesn't ref
**Version Used**: 

VS 15.8.4
LangVersion: latest
TargetFrameworks: netcoreapp2.1 and net472 with System.Memory 4.5.1

**Steps to Reproduce**:

```cs
using System;
using System.Threading;

class Program
{
    static void Main() { A(); B(); C(); D(); }

    static void A()
    {
        var items = new (int x, int y)[1];
        foreach (ref var t in items.AsSpan()) Interlocked.Exchange(ref t.x, 1);
        foreach (var (x, y) in items) Console.WriteLine(x); // expected: 1, actual 0
    }

    static void B() // No Exchange
    {
        var items = new (int x, int y)[1];
        foreach (ref var t in items.AsSpan()) t.x = 1;
        foreach (var (x, y) in items) Console.WriteLine(x); // 1
    }

    static void C() // "for" instead of "foreach(ref var)"
    {
        var items = new (int x, int y)[1];
        for (int i = 0; i < items.Length; i++)
        {
            ref var t = ref items[i];
            Interlocked.Exchange(ref t.x, 1);
        }
        foreach (var (x, y) in items) Console.WriteLine(x); // 1
    }

    static void D() // No tuple
    {
        var items = new int[1];
        foreach (ref var x in items.AsSpan()) Interlocked.Exchange(ref x, 1);
        foreach (var x in items) Console.WriteLine(x); // 1
    }
}
```

**Expected Behavior**:

`A` shows `1`.

**Actual Behavior**:

`A` shows `0`.

### PR DESCRIPTION
**Pull request by chsienki**
- Fix NeedsByValueFieldAccess to consider if the symbol is ref when it's not writeable (i.e. a ref foreach variable: the variable isn't writeable but any of its fields should be passed by ref, not value).
- Add a test to show the incorrect behavior is fixed

Fixes #30016

### CODE REVIEW

**Comment by chsienki** [comment]
@dotnet/roslyn-compiler ready for review please

File: src/Compilers/CSharp/Portable/BoundTree/Constructors.cs [hunk 1]
```diff
@@ -68,7 +68,7 @@ private static bool NeedsByValueFieldAccess(BoundExpression receiver, FieldSymbo
                     return ((BoundFieldAccess)receiver).IsByValue;
 
                 case BoundKind.Local:
-                    return !((BoundLocal)receiver).LocalSymbol.IsWritableVariable;
+                    return !(((BoundLocal)receiver).LocalSymbol.IsWritableVariable || ((BoundLocal)receiver).LocalSymbol.IsRef);
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/BoundTree/Constructors.cs]: Consider storing `LocalSymbol` into a local here to make this more readable.

**Comment by gafter** [comment]
@gafter is added to the review. #Closed
