### PR TITLE
Dev/toddgrun/revert 769dfa13624dae1bbba1afbdfaeb85f928843004 and use multi dictionary pool

### LINKED ISSUE #66410: High CPU Utilization with Very Basic Keypresses
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/High-CPU-Utilization-with-Very-Basic-Key/10247502)._

Internal ticket: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1714591

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.4]
Please see attached.  I am seeing high CPU utilization that is occurring in a basic .cs file.  Upwards to 50% with delays/hitches on the UI thread.

This seems new for 17.5

---
#### Feedback Bot on 1/8/2023, 06:56 PM: 

(private comment, text removed)
#### Feedback Bot on 1/10/2023, 08:51 AM: 

(private comment, text removed)
#### Cyrus Najmabadi [MSFT] on 1/11/2023, 00:26 PM: 

(private comment, text removed)
#### Mike-E-angelo on 1/11/2023, 01:16 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by ToddGrun**
Restores the behavior originally implemented in #66430, but later reverted in #67808.

Fixes #66410

### CODE REVIEW

**Comment by ToddGrun** [comment]
Removing draft status, not ready for review until test insertion PR numbers come through

File: src/Compilers/Core/Portable/ReferenceManager/CommonReferenceManager.Resolution.cs [hunk 1]
```diff
@@ -925,15 +925,19 @@ private static void AddModule(PEModule module, int referenceIndex, ResolvedRefer
...
-                AssemblyIdentity definition = definitions[i].Identity;
+                // Skip assembly being built for now; it will be considered at the very end
+                if (definitionIndex == 0)
+                {
+                    continue;
+                }
+
+                AssemblyIdentity definition = definitionData.Identity;
 
                 if (!AssemblyIdentityComparer.SimpleNameComparer.Equals(reference.Name, definition.Name))
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/ReferenceManager/CommonReferenceManager.Resolution.cs:942]: >if (!AssemblyIdentityComparer.SimpleNameComparer.Equals(reference.Name, definition.Name) [](http://example.com/codeflow?start=16&length=88)

Is this still necessary? If not, consider removing or converting to an assert.

File: src/Compilers/Core/Portable/ReferenceManager/CommonReferenceManager.Binding.cs [hunk 2]
```diff
@@ -15,6 +15,8 @@ namespace Microsoft.CodeAnalysis
 {
     internal partial class CommonReferenceManager<TCompilation, TAssemblySymbol>
     {
+        private static readonly ObjectPool<MultiDictionary<string, (AssemblyData DefinitionData, int DefinitionIndex)>> s_pool = new(() => new(AssemblyIdentityComparer.SimpleNameComparer));
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/ReferenceManager/CommonReferenceManager.Binding.cs:18]: >new [](http://example.com/codeflow?start=139&length=3)

Target typed new is not allowed in Compilers

**Comment by AlekseyTs** [comment]
Done with review pass (commit 4)

File: src/Compilers/Core/Portable/ReferenceManager/CommonReferenceManager.Resolution.cs (hunk 1 above)
Comment (333fred) [reply src/Compilers/Core/Portable/ReferenceManager/CommonReferenceManager.Resolution.cs]: This was the fast-path I added to try and move a common comparison check up sooner. I think we can remove it, and not have an assert. It will be verified by `assemblyIdentityComparer` anyway.

File: src/Compilers/Core/Portable/ReferenceManager/AssemblyData.cs [hunk 3]
```diff
@@ -69,6 +70,17 @@ internal abstract class AssemblyData
             public abstract Compilation? SourceCompilation { get; }
 
             private string GetDebuggerDisplay() => $"{GetType().Name}: [{Identity.GetDisplayName()}]";
+#if DEBUG
```
[the remark this answers is not in the document]
Comment (ToddGrun) [reply src/Compilers/Core/Portable/ReferenceManager/AssemblyData.cs:73]: This was in the original fix (Phttps://github.com/dotnet/roslyn/pull/66430). @AlekseyTs?

File: src/Compilers/Core/Portable/ReferenceManager/CommonReferenceManager.Resolution.cs (hunk 1 above)
Comment (ToddGrun) [reply src/Compilers/Core/Portable/ReferenceManager/CommonReferenceManager.Resolution.cs]: OK, will remove completely

File: src/Compilers/Core/Portable/ReferenceManager/AssemblyData.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (ToddGrun) [reply src/Compilers/Core/Portable/ReferenceManager/AssemblyData.cs]: Optimistically removed the code

File: src/Compilers/Core/Portable/ReferenceManager/AssemblyData.cs [hunk 4]
```diff
@@ -69,6 +70,17 @@ internal abstract class AssemblyData
...
+                return base.Equals(obj);
+            }
+
+            public sealed override int GetHashCode()
+            {
+                return base.GetHashCode();
+            }
+#endif
         }
     }
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/ReferenceManager/AssemblyData.cs]: Please restore the code, it is there for a reason. ```MultiDictionary``` stores only unique values. We don't want any non-trivial code to be implicitly involved into the process of working with the ```MultiDictionary``` that use to bind/resolve references.

Comment (AlekseyTs) [reply src/Compilers/Core/Portable/ReferenceManager/AssemblyData.cs]: Feel free to add a comment.

File: src/Compilers/Core/Portable/ReferenceManager/AssemblyData.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/Core/Portable/ReferenceManager/AssemblyData.cs:73]: >Is the point sealing the overrides so it can't be overridden further? 

Yes.

>If so, why not do this unconditionally?

Because we don't want to customize the behavior, we just want to prevent others from doing so. Sealing the methods in DEBUG is sufficient to ensure that, and this doesn't cost us anything in RELEASE, including the binary size. At the same time, there is no behavior difference DEBUG vs. RELEASE.

File: src/Compilers/Core/Portable/ReferenceManager/AssemblyData.cs (hunk 4 above)
Comment (ToddGrun) [reply src/Compilers/Core/Portable/ReferenceManager/AssemblyData.cs:85]: Added back. I'll defer to you to add the comment at your convenience as you understand the intent better than I do.

Comment (AlekseyTs) [reply src/Compilers/Core/Portable/ReferenceManager/AssemblyData.cs:85]: > I'll defer to you to add the comment at your convenience as you understand the intent better than I do.

Sounds good.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 8)

**Review by 333fred — APPROVED** [review]
