### PR TITLE
Join in state from parameter default value

### LINKED ISSUE #40818: No warning returning optional parameter of unconstrained type
No warning is reported for the second method:
```C#
#nullable enable

class Program
{
    static T F<T>()
    {
        T defaultValue = default;
        return defaultValue; // warning CS8603: Possible null reference return
    }

    static T F<T>(T defaultValue = default)
    {
        return defaultValue; // no warning
    }
}
```
From https://github.com/dotnet/roslyn/issues/38339#issuecomment-569571346, updated with warnings from 16.5. 
cc @Bosch-Eli-Black

### LINKED ISSUE #40975: Should not warn on null default value on [AllowNull] parameter
Follow-up on https://github.com/dotnet/roslyn/pull/40789

```
        [Fact]
        public void AllowNull_Parameter_NullDefaultValue()
        {
            var source =
@"using System.Diagnostics.CodeAnalysis;
public class C
{
    void M([AllowNull] string p = null) { }
}
";

            var comp = CreateNullableCompilation(new[] { AllowNullAttributeDefinition, source });
            // Note: fixing this was tricky as it involved a cycle (FlowAnnotations, attribute decoding, default value)
            comp.VerifyDiagnostics(
                // (4,35): warning CS8625: Cannot convert null literal to non-nullable reference type.
                //     void M([AllowNull] string p = null) { }
                Diagnostic(ErrorCode.WRN_NullAsNonNullable, "null").WithLocation(4, 35)
                );
        }
```

### LINKED ISSUE #43399: Roslyn doesn't verify nullability in [DefaultParameterValue] attributes
**Version Used**: 

```
Branch master (10 Mar 2020)
Latest commit 441c154 by msftbot[bot]:
Merge pull request #42303 from CyrusNajmabadi/useCompoundParens

Support parenthesized expressions in use-compound-operator.
```

**Steps to Reproduce**:

Compile and run the following program
```cs
using System.Runtime.InteropServices;
class C
{
  static void Main() => new C().M1();
  void M1([Optional][DefaultParameterValue(null)] object s) { s.ToString(); }
}
```

**Expected Behavior**:
Warning for `null` argument of `[DefaultParameterValue(null)]` as its target parameter doesn't allow nulls

**Actual Behavior**:
No warnings. The program crashes at runtime with a `NullReferenceException`

### LINKED ISSUE #47344: Record parameters of generic types should give safety warnings on default values
**Version Used**: e7bad77

**Steps to Reproduce**:

```cs
#nullable enable

var rec = new Rec1<string>();
rec.t.ToString(); // NRE at runtime

record Rec1<T>(T t = default) // no warning
{
}
```

**Expected Behavior**: A safety warning is given on the implicit assignment to the synthesized property `Rec1<T>.t`.

**Actual Behavior**: No warnings are given.

**Remarks**:

Once we implement non-safety warnings for unconstrained generics in C# 9 we will be halfway there, but to handle this scenario correctly we need to figure out how to distinguish compiler-generated nodes that we care about (e.g. record synthesized constructors) from compiler-generated nodes that we don't care about (e.g. synthesized default arguments at call sites).

If we just start warning on all compiler generated assignments, we will also get an undesirable warning at the `new Rec1` creation site, since we synthesize an argument for the optional parameter for flow analysis purposes.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #40818
Closes #40975
Closes #47344
Closes #43399

2 notable changes from this PR:
- diagnostics for bad parameter default values are now CS8600 (non-safety warning). This is a consequence of the "simulate an assignment" approach. We join in the bad state and we will receive warnings on usage of the parameter. I think this is probably a good (if not very significant) change.
- diagnostics for bad parameter default values on partial implementations are gone. Such default values are actually ignored in the language and produce warnings, so this seems OK.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs [hunk 1]
```diff
@@ -1454,6 +1454,10 @@ private BoundExpression GetDefaultParameterValue(SyntaxNode syntax, ParameterSym
                 defaultValue = MakeConversionNode(defaultValue, parameterType, @checked: false, acceptFailingConversion: true);
             }
 
+            // CONSIDER: it feels like determining the exact value that will be emitted for a
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs:1457]: note: this would probably be a fairly difficult/substantial change and not something we would do at this phase in the release cycle.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 2]
```diff
@@ -64220,18 +64225,106 @@ static void M()
...
+        => t; // 1
+
+    T M2<T>(T t = default) where T : class?
+        => t; // 2
+
+    T M3<T>(T t = default) where T : class // 3
+        => t; // 4
+
+    T M4<T>(T t = default) where T : notnull
+        => t; // 5
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:64257]: nit: these should be renumbered

**Comment by RikkiGibson** [comment]
Moving to draft mode until bootstrap failures are resolved

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 3]
```diff
@@ -2182,6 +2188,23 @@ private void EnterParameter(ParameterSymbol parameter, TypeWithAnnotations param
                         isDefaultValue: parameter.ExplicitDefaultConstantValue?.IsNull == true);
                 }
             }
+
+            // If we have an initial state, then we're doing the second analysis stage on a constructor
+            // and we shouldn't report assignment warnings related to parameter default values
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:2193]: Consider adding a `Debug.Assert` for this condition. I would assume the method symbol should be a constructor?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs (hunk 1 above)
Comment (333fred) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs:1457]: Agreed, we should probably open an issue to follow up.

---
In reply to: [477744390](https://github.com/dotnet/roslyn/pull/47171#discussion_r477744390) [](ancestors = 477744390)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 4]
```diff
@@ -64233,6 +64235,9 @@ static void M()
 
             var comp = CreateCompilation(new[] { source }, options: WithNonNullTypesTrue());
             comp.VerifyDiagnostics(
+                // (5,31): warning CS8600: Converting null literal or possible null value to non-nullable type.
+                //     static void F1(string x = (string)null!, string y = ((string)null)!) { }
+                Diagnostic(ErrorCode.WRN_ConvertingNullableToNonNullable, "(string)null!").WithLocation(5, 31),
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:64240]: A) Does this solve the above comment?
B) I'm not sure I agree with this comment in general: there's a `!` here. Seems like this warning should be surpressed.

**Comment by 333fred** [comment]
Done review pass (commit 5)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:64240]: Correct, this warning is wrong. We need another scenario which assigns `(string)null`.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:64240]: To properly solve suppression cases, warn on bad conversions, and so on, the best thing will be to just fix parameter default values more generally in the next release.

Right now, when we determine a parameter's "real" default value, we go through a destructive round-tripping where we bind the default value on the parameter declaration, then convert to ConstantValue, then convert back to BoundExpression.

**Comment by RikkiGibson** [comment]
Now that we actually analyze and warn about the synthesized record constructor, I had to slightly adjust a RecordTests baseline.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs:1457]: Opened #47352

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: I ended up adjusting this logic so that the constructor requirement is verified at runtime.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs [hunk 5]
```diff
@@ -1454,6 +1454,10 @@ private BoundExpression GetDefaultParameterValue(SyntaxNode syntax, ParameterSym
...
+            // parameter default value is something that should be figured out at binding time, not in lowering.
+            defaultValue = defaultValue.WithSuppression(syntax.IsKind(SyntaxKind.SuppressNullableWarningExpression));
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs:1459]: >defaultValue [](start = 12, length = 12)

Just curious, did you understand why that bound node doesn't carry the proper suppression flag already? That's rather surprising since it's handled by `BindSuppressNullableWarningExpression`

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 6]
```diff
@@ -7637,6 +7637,9 @@ static void M1(B b)
             // https://github.com/dotnet/roslyn/issues/44691
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:7637]: >// https://github.com/dotnet/roslyn/issues/44691 [](start = 12, length = 48)

This issue was closed. Consider adding a variant of this test that also has an attribute on the property.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 9). Moving the analysis to NullableWalker is elegant (avoids many problems), I much like it :-)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs (hunk 5 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs:1459]: Yeah, I think we could work around this here by somehow obtaining the bound expression for the default value, but I do not think it's worth it for now. Better to do the work in the future to factor this in a more sane way. #47352

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs (hunk 6 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs]: Done

**Comment by RikkiGibson** [comment]
2 of the integration test legs have still not started after 2 hours. I believe my change doesn't impact these legs so I will merge now.
