### PR TITLE
Bind pattern labels when producing switch label map

### LINKED ISSUE #16559: Stack Overflow in BindPatternSwitchLabelForInference
**Version Used**: VS2015 RC3

**Steps to Reproduce**:

Attempt to compile this code:

```cs
public class Program5815
{
    public static void Main(string[] args)
    {
        switch ((int)M())
        {
            case var x3:
            case true ? x3 : 4:
                break;
        }
    }
    private static object M() => null;
}
```

**Expected Behavior**: Compiler error about case label not being a constant

**Actual Behavior**: Compiler stack overflow

See also https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?_a=edit&id=369796

### PR DESCRIPTION
**Pull request by gafter**
**Customer scenario**

Attempting to use a nullable type in a type switch (which is illegal), the compiler can interpret that as a ?: operator, and attempt to bind the expression when producing a map from switch cases to the labels. But since we do not bind the pattern cases, that can result in infinite recursion when trying to bind a reference to the pattern variable. For example
```cs
switch (o)
{
    case Color Color:
    case Color? Color2:
        break;
}
```

**Bugs this fixes:** 

Fixes #16559

**Workarounds, if any**

Don't attempt to use nullable types in the typeswitch.

**Risk**

Very low, as this just causes the compiler to bind something earlier than it previously did.

**Performance impact**

Likely none for the same reason.

**Is this a regression from a previous update?**

No; this bug is in a new feature.

**Root cause analysis:**

Lack of dedicated testing team, and failure to follow-through on Engineering plans to assign a developer to an adversarial testing role for each feature under development.

**How was the bug found?**

Bug found by new test generator written to test random (and therefore unexpected) scenarios. It also identified small test cases for the three Watson crashes, which were fixed in the previous PR.

@AlekseyTs @agocke @dotnet/roslyn-compiler Please review this small RTM fix for a pattern-matching crash.

See also https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?_a=edit&id=369796

### CODE REVIEW

**Comment by gafter** [comment]
@AlekseyTs @agocke @dotnet/roslyn-compiler Please review this small RTM fix for a pattern-matching crash.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 1]
```diff
@@ -4565,20 +4565,24 @@ public static void Main(string[] args)
     private static object M() => null;
 }";
             CreateCompilationWithMscorlib45(program).VerifyDiagnostics(
+                // (9,18): error CS0150: A constant value is expected
+                //             case true ? x3 : 4:
```
Comment (agocke) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Could you also add a test for the example in your bug?

**Comment by agocke** [comment]
@gafter Is there a plan to provide a better error message for this later? It's unlikely the user will understand their case is being parsed as a ternary operator and thus the error about constants is that they're in a classic switch context with a non-constant comparator.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Sure, but it is an equivalent expression after syntax error recovery.

**Comment by gafter** [comment]
@agocke It would be nice to produce better (syntax) errors here, but that is tricky since we have to accept both types and expressions. I'll file an issue.

**Comment by cston** [comment]
LGTM

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: This test is precisely the example in the bug.

Comment (agocke) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Ah, my mistake, I thought you took the Customer Scenario example from the bug.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 2]
```diff
@@ -4547,7 +4547,40 @@ public static void Main(string[] args)
...
+                //             case Color Color:
+                Diagnostic(ErrorCode.ERR_BadSKknown, "Color").WithArguments("Color", "variable", "type").WithLocation(8, 18),
+                // (9,25): error CS0103: The name 'Color2' does not exist in the current context
+                //             case Color? Color2:
+                Diagnostic(ErrorCode.ERR_NameNotInContext, "Color2").WithArguments("Color2").WithLocation(9, 25)
+                );
+        }
+
+        [Fact, WorkItem(16559, "https://github.com/dotnet/roslyn/issues/16559")]
         public void Fuzz5815()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Please test SemanticModel behavior as well, we should have all the helpers for that.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 3]
```diff
@@ -4547,7 +4547,40 @@ public static void Main(string[] args)
                 );
         }
 
-        [Fact(Skip = "https://github.com/dotnet/roslyn/issues/16559")]
+        [Fact, WorkItem(16559, "https://github.com/dotnet/roslyn/issues/16559")]
+        public void CasePatternVariableUsedInCaseExpression()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Please test SemanticModel behavior as well, we should have all the helpers for that.

**Comment by AlekseyTs** [comment]
Done with review pass.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 4]
```diff
@@ -4565,20 +4598,24 @@ public static void Main(string[] args)
...
 }";
             CreateCompilationWithMscorlib45(program).VerifyDiagnostics(
+                // (9,18): error CS0150: A constant value is expected
+                //             case true ? x3 : 4:
+                Diagnostic(ErrorCode.ERR_ConstantExpected, "true ? x3 : 4").WithLocation(9, 18)
                 );
         }
 
-        [Fact(Skip = "This test generator is capable of producing crashes that are not yet fixed; see, for example, Fuzz5815")]
+        [Fact(Skip = "This test generator runs too long to use frequently")]
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: As long as we are changing this test please file a bug and use it in the skip reason.  If this is useful we should work on the perf here until we can get it to be a part of a normal run.  Same work was done for some @agocke generated tests.

**Comment by gafter** [comment]
Requested changes have been made. @AlekseyTs @jaredpar please re-review.

**Comment by gafter** [comment]
@MattGertz For ask mode, please.

**Comment by natidea** [comment]
Approved to merge via [369796](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/369796)
