### PR TITLE
Use new CoreFX API for creating NamedPipeServerStreams

### LINKED ISSUE #24137: Long-running VBCSCompiler.dll process runs at 100% CPU after parent process dies
**Version Used**: 
Using dotnet SDK 2.2.0-preview1-007866 on macOS 10.13.2

**Steps to Reproduce**:
TBH not sure 100% how to get into bad state. I don't know what is launching VBCSCompiler.dll. The parent process is gone...which is the issue.

But, it has been happening fairly often over the last few days while working on the https://github.com/dotnet/cli repo using VS Code - Insiders + C# extension 1.13.1.

If someone can point me to how to capture more information about how this long-running compiler server starts, I can provide a better repro.

**Expected Behavior**:
No long running compiler process after I shutdown tools and build scripts.

**Actual Behavior**:
image

VS Code is closed, and I've killed the the build.sh script, yet I have two VBCSCompiler processes running. `ps` reports the processes have been open for ~ 18 hours.

The process was launched with these arguments:
```
/Users/namc/.dotnet/dotnet /Users/namc/.dotnet/sdk/2.2.0-preview1-007866/Roslyn/bincore/VBCSCompiler.dll -pipename:namc.False.bZ9mpL2HFmG8IVwxPkEmz6_N4OMYW1cLZOeZGRjGfv0
```

Process sample: 
[processample.txt](https://github.com/dotnet/roslyn/files/1617126/processample.txt)

#### [EDIT]
See below for a workaround: https://github.com/dotnet/roslyn/issues/24137#issuecomment-388494024

### PR DESCRIPTION
**Pull request by agocke**
The bulk of this change is in the second commit. The first commit is just changing some of the compiler server test helpers to propagate exceptions instead of crashing the process so it's easier to diagnose CI test failures.

The default behavior for the NamedPipeServerStream API is to take a pipe
name and then construct a named pipe in the background using that name.
In Windows this involves creating a file in a special namespace in the
file system. On Unix, named pipes are implemented using Unix Domain
Sockets, which are actual files, and the CoreFX behavior is to create
them in the temporary directory. Unfortunately, Unix Domain Sockets also
often have a max path length limitation and the temporary directory
could be arbitrarily long, meaning that any attempt to create a named
pipe may fail on Unix.

To remedy this, CoreFX introduced an API which allows you to pass a full
path instead of just a pipe name. If a fully-qualifed path is passed,
the new behavior is used. We can use this functionality to improve
reliability of pipe name creation by using the "/tmp" directory on Unix,
which by the POSIX specification is always required to be a valid
temporary directory, and by using a fixed-length pipe name that is lower
than any known Unix Domain Socket path length restriction.

This should fix the issue for good.

Fixes #24137

### CODE REVIEW

**Comment by agocke** [comment]
test mac please

File: src/Compilers/Server/VBCSCompilerTests/CompilerServerTests.cs [hunk 1]
```diff
@@ -256,16 +256,16 @@ public async Task ServerFailsWithLongTempPathUnix()
...
-                using (var serverData = ServerUtil.CreateServer())
+                using (var serverData = await ServerUtil.CreateServer())
                 {
                     var result = RunCommandLineCompiler(
                         CSharpCompilerClientExecutable,
                         $"/shared:{serverData.PipeName} /nologo hello.cs",
                         _tempDirectory,
                         s_helloWorldSrcCs,
-                        shouldRunOnServer: false);
+                        shouldRunOnServer: true);
```
Comment (RikkiGibson) [inline src/Compilers/Server/VBCSCompilerTests/CompilerServerTests.cs]: Can you explain the false->true and 0->1 changes here?

File: src/Compilers/Server/VBCSCompilerTests/VBCSCompilerServerTests.cs [hunk 2]
```diff
@@ -112,7 +113,7 @@ public async Task NoServerConnection()
             /// the client can error out.
             /// </summary>
             /// <returns></returns>
-            [ConditionalFact(typeof(WindowsOrLinuxOnly))]
+            [Fact]
```
Comment (RikkiGibson) [inline src/Compilers/Server/VBCSCompilerTests/VBCSCompilerServerTests.cs]: Great if this fixes the hangs we were seeing on Mac.

**Comment by RikkiGibson** [comment]
Related to #34880

**Comment by jaredpar** [comment]
@agocke 

> This should fix the issue for good.

I think I'm gonna frame that for you 😄

File: src/Compilers/Shared/NamedPipeUtil.cs [hunk 3]
```diff
@@ -16,15 +16,36 @@ namespace Microsoft.CodeAnalysis
     /// </summary>
     internal static class NamedPipeUtil
     {
+        // Size of the buffers to use: 64K
```
Comment (jaredpar) [inline src/Compilers/Shared/NamedPipeUtil.cs]: What buffer?

File: src/Compilers/Shared/NamedPipeUtil.cs [hunk 4]
```diff
@@ -16,15 +16,36 @@ namespace Microsoft.CodeAnalysis
...
+        {
+            if (PlatformInformation.IsUnix)
+            {
+                // If we're on a Unix machine then named pipes are implemented using Unix Domain Sockets.
+                // Most Unix systems have a maximum path length limit for Unix Domain Sockets, with
+                // Mac having a particularly short one. Mac also has a generated temp directory that
+                // can be quite long, leaving very little room for the actual pipe name. Fortunately,
+                // '/tmp' is mandated by POSIX to always be a valid temp directory, so we can use that
+                // instead.
+                return Path.Combine("/tmp", pipeName);
```
Comment (jaredpar) [inline src/Compilers/Shared/NamedPipeUtil.cs]: Didn't @kg mention that some mono scenarios didn't have a `/tmp` directory?

File: src/Compilers/Server/VBCSCompilerTests/CompilerServerTests.cs (hunk 1 above)
Comment (agocke) [reply src/Compilers/Server/VBCSCompilerTests/CompilerServerTests.cs]: The test previously tested that the server failed. So the server would start, then shutdown, and the command line compiler would fall back to in-memory compilation. So we previously asserted that the request would not run on the server, and that the server exited without processing any compilations.

Now we do the opposite (because I fixed it) -- the compilation runs on the server successfully, and the server processes one compilation.

File: src/Compilers/Shared/NamedPipeUtil.cs (hunk 4 above)
Comment (kg) [reply src/Compilers/Shared/NamedPipeUtil.cs]: I'm not aware of these situations, but someone else brought it up on one of my PRs

Comment (agocke) [reply src/Compilers/Shared/NamedPipeUtil.cs]: Well, there are technically two things to separate here: whether /tmp exists, and whether it is the system temporary directory.

POSIX requires /tmp exist, so I think almost all reasonable platforms should have it. 

However, no system is required to choose /tmp as their system temporary directory. The most prominent example here is macOS, where they have a randomly generated one.

In this case I'm assuming that even if /tmp isn't the *preferred* system temporary directory, it's a valid directory. I think this is a reasonable assumption and probably shouldn't have severe consequences otherwise. If not for the UDS path length limit I would just use the standard system temporary directory.

File: src/Compilers/Shared/NamedPipeUtil.cs (hunk 3 above)
Comment (agocke) [reply src/Compilers/Shared/NamedPipeUtil.cs]: The Pipe buffers, of course 😉
