### PR TITLE
Fixes #18240 - "Generate class ..." causes inconsistent accessibility

### LINKED ISSUE #18240: "Generate class ..." causes inconsistent accessibility
**Version Used**: Visual Studio 2017 15.0.0-RTW+26228.4

**Code to Reproduce**:
```csharp
public class Foo<T> where T : Bar // Generate class 'Bar'
{
}
```
**Actual Behavior**:
```csharp
public class Foo<T> where T : Bar // CS0703 Inconsistent accessibility: constraint type 'Bar' is less accessible than 'Foo<T>'
{
}

internal class Bar 
{
}
```

**Expected Behavior**:
```csharp
public class Foo<T> where T : Bar
{
}

public class Bar 
{
}
```

### PR DESCRIPTION
**Pull request by dopare**
Fixes #18240.

Currently if nested class is protected then we generate internal class which can cause compilation error if  protected class is under public class.
This PR also fixes that issue.

### CODE REVIEW

**Comment by sharwell** [comment]
😎 Welcome to the project!

**Comment by dopare** [comment]
Thank you 😄

File: src/EditorFeatures/CSharpTest/Diagnostics/GenerateType/GenerateTypeTests.cs [hunk 1]
```diff
@@ -140,6 +179,302 @@ internal class Base
...
+}
+
+internal class Employee
+{
+}",
+index: 1);
+        }
+
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsGenerateType)]
+        public async Task TestGeneratePublicInterfaceFromASingleConstraintClause()
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/Diagnostics/GenerateType/GenerateTypeTests.cs]: :bulb: Another good test would be the following. Unlike other types, if you omit the accessibility keyword from an interface member (which is actually a requirement in this location), the result is effectively `pubilc` instead of `private`.

```csharp
public interface IFoo
{
    void GetSomething<T>() where T : D;
}
```

File: src/Features/CSharp/Portable/GenerateType/CSharpGenerateTypeService.cs [hunk 2]
```diff
@@ -496,6 +496,15 @@ private IMethodSymbol GetMethodSymbolIfPresent(SemanticModel semanticModel, Expr
                 state.NameOrMemberAccessExpression as TypeSyntax, cancellationToken);
         }
 
+        private bool IsAccessibilityInTypeDeclarationChainPrivateOrInternal(
+    State state,
```
Comment (Pilchie) [inline src/Features/CSharp/Portable/GenerateType/CSharpGenerateTypeService.cs]: Nit: Parameters should be indented 4 past `private` here.

File: src/Features/CSharp/Portable/GenerateType/CSharpGenerateTypeService.cs [hunk 3]
```diff
@@ -558,6 +567,21 @@ protected override Accessibility GetAccessibility(State state, SemanticModel sem
                 {
                     accessibility = accessibilityConstraint;
                 }
+                else if (accessibilityConstraint == Accessibility.Protected ||
+                         accessibilityConstraint == Accessibility.ProtectedOrInternal)
+                {
+                    //for nested types we cannot always generate internal type
+                    //we must check if one of outer classes is either internal or private
```
Comment (Pilchie) [inline src/Features/CSharp/Portable/GenerateType/CSharpGenerateTypeService.cs]: Nit: space after `//` and use Sentence case for comments.

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs [hunk 4]
```diff
@@ -451,9 +451,48 @@ public static ISet<INamespaceSymbol> GetUsingNamespacesInScope(this SemanticMode
...
+                var declaredAccessibility = semanticModel.GetDeclaredSymbol(memberDeclaration, cancellationToken).DeclaredAccessibility;
+
+                return declaredAccessibility;
+            }
+
             return Accessibility.Private;
         }
 
+        public static bool IsAccessibilityInTypeDeclarationChainPrivateOrInternal(
+           this SemanticModel semanticModel,
```
Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs]: Nit: 4 spaces, not 3.

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs [hunk 5]
```diff
@@ -451,9 +451,48 @@ public static ISet<INamespaceSymbol> GetUsingNamespacesInScope(this SemanticMode
                 }
             }
 
+            // for type constraints use declared accessibility of its member declaration (class, interface, delegate, method)
```
Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs]: Sentence case, and rationalize with the numbering in the rest of the comments in this method.

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs [hunk 6]
```diff
@@ -451,9 +451,48 @@ public static ISet<INamespaceSymbol> GetUsingNamespacesInScope(this SemanticMode
...
+           CancellationToken cancellationToken)
+        {
+            if (type == null)
+            {
+                return false;
+            }
+
+            type = GetOutermostType(type);
+
+            var typeDeclartions = type.GetAncestors<TypeDeclarationSyntax>();
```
Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs]: Spelling - `typeDeclarations`

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs [hunk 7]
```diff
@@ -451,9 +451,48 @@ public static ISet<INamespaceSymbol> GetUsingNamespacesInScope(this SemanticMode
...
+
+            foreach(var typeDeclaration in typeDeclartions)
```
Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs]: Nit: space after `foreach`

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs [hunk 8]
```diff
@@ -451,9 +451,48 @@ public static ISet<INamespaceSymbol> GetUsingNamespacesInScope(this SemanticMode
...
+            {
+                var symbol = semanticModel.GetDeclaredSymbol(typeDeclaration, cancellationToken);
+
+                //if we find private or internal in type declaration chain then generated type can be internal
+                if(symbol.DeclaredAccessibility == Accessibility.Private ||
```
Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs]: Nit: space after `if`

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs [hunk 9]
```diff
@@ -451,9 +451,48 @@ public static ISet<INamespaceSymbol> GetUsingNamespacesInScope(this SemanticMode
...
+                var memberDeclaration = type.GetAncestor<MemberDeclarationSyntax>();
+                var declaredAccessibility = semanticModel.GetDeclaredSymbol(memberDeclaration, cancellationToken).DeclaredAccessibility;
+
+                return declaredAccessibility;
+            }
+
             return Accessibility.Private;
         }
 
+        public static bool IsAccessibilityInTypeDeclarationChainPrivateOrInternal(
```
Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs]: Consider: Switching the sense of this and renaming to something like: `AllContainingTypesArePublic`.

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs [hunk 10]
```diff
@@ -451,9 +451,48 @@ public static ISet<INamespaceSymbol> GetUsingNamespacesInScope(this SemanticMode
...
             }
 
+            // for type constraints use declared accessibility of its member declaration (class, interface, delegate, method)
+            if (type.IsParentKind(SyntaxKind.TypeConstraint) &&
+                type.Parent.IsParentKind(SyntaxKind.TypeParameterConstraintClause))
+            {
+                var memberDeclaration = type.GetAncestor<MemberDeclarationSyntax>();
+                var declaredAccessibility = semanticModel.GetDeclaredSymbol(memberDeclaration, cancellationToken).DeclaredAccessibility;
+
+                return declaredAccessibility;
```
Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs]: Related to @sharwell's comment - what is `DeclaredAccessibility` for interface members?

**Comment by dopare** [comment]
Implemented requested action items from code review.
Added 2 more tests and renamed new tests' names to more meaningful names.

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs (hunk 10 above)
Comment (dopare) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs]: It is always public

**Comment by dopare** [comment]
Squashed commits for next review

File: src/EditorFeatures/CSharpTest/Diagnostics/GenerateType/GenerateTypeTests.cs [hunk 11]
```diff
@@ -140,6 +179,340 @@ internal class Base
...
+@"interface Employee
+{
+    void Action<T>() where T : [|Command|] {}
+}",
+@"interface Employee
+{
+    void Action<T>() where T : Command {}
+}
+
+public class Command
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/Diagnostics/GenerateType/GenerateTypeTests.cs]: ❗️ This one should be `internal` because `Employee` is `internal`.

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs [hunk 12]
```diff
@@ -451,9 +451,47 @@ public static ISet<INamespaceSymbol> GetUsingNamespacesInScope(this SemanticMode
                 }
             }
 
+            // For type constraints use declared accessibility of its member declaration (class, interface, delegate, method)
+            if (type.IsParentKind(SyntaxKind.TypeConstraint) &&
+                type.Parent.IsParentKind(SyntaxKind.TypeParameterConstraintClause))
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs]: When can you have a TypeConstraint that is *not* parented by a TypeParameterConstraintClause?

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs [hunk 13]
```diff
@@ -451,9 +451,47 @@ public static ISet<INamespaceSymbol> GetUsingNamespacesInScope(this SemanticMode
...
+            this SemanticModel semanticModel,
+            TypeSyntax type,
+            CancellationToken cancellationToken)
+        {
+            if (type == null)
+            {
+                return false;
+            }
+
+            type = GetOutermostType(type);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs]: this step does not seem necessary.  Can you clarify why you need to do it?

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs [hunk 14]
```diff
@@ -451,9 +451,47 @@ public static ISet<INamespaceSymbol> GetUsingNamespacesInScope(this SemanticMode
...
+
+            var typeDeclarations = type.GetAncestors<TypeDeclarationSyntax>();
+
+            foreach (var typeDeclaration in typeDeclarations)
+            {
+                var symbol = semanticModel.GetDeclaredSymbol(typeDeclaration, cancellationToken);
+
+                if (symbol.DeclaredAccessibility == Accessibility.Private ||
+                    symbol.DeclaredAccessibility == Accessibility.Internal)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs]: This check doesn't match your method name.  For example, you'll return 'true' if one of the containing types i protected.  

That may be what you want, but in tha t case the method name should be AllContainingTypesArePublicOrProtected.

File: src/Features/CSharp/Portable/GenerateType/CSharpGenerateTypeService.cs [hunk 15]
```diff
@@ -558,6 +567,19 @@ protected override Accessibility GetAccessibility(State state, SemanticModel sem
...
+                {
+                    // If nested type is declared in public type then we should generate public type instead of internal
+                    if (AllContainingTypesArePublic(state, semanticModel, cancellationToken))
+                    {
+                        accessibility = Accessibility.Public;
+                    }
+                    else
+                    {
+                        accessibility = Accessibility.Internal;
+                    }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/GenerateType/CSharpGenerateTypeService.cs]: nit, consider use ? : expression to simplify this.

File: src/EditorFeatures/CSharpTest/Diagnostics/GenerateType/GenerateTypeTests.cs [hunk 16]
```diff
@@ -89,6 +89,24 @@ internal class Employee
         }
 
         [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsGenerateType)]
+        public async Task TestGeneratePublicClassFromASingleConstraintClause()
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Diagnostics/GenerateType/GenerateTypeTests.cs]: new tests shoudl include a [WorkItem(bugnumber, "github-issue-link")] attribute on them.

File: src/EditorFeatures/CSharpTest/Diagnostics/GenerateType/GenerateTypeTests.cs [hunk 17]
```diff
@@ -140,6 +179,340 @@ internal class Base
...
+@"class Employee
+{
+    public void Action<T>() where T : [|Command|] {}
+}",
+@"class Employee
+{
+    public void Action<T>() where T : Command {}
+}
+
+public class Command
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Diagnostics/GenerateType/GenerateTypeTests.cs]: i don't think command should be public here either.

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs (hunk 13 above)
Comment (dopare) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs]: Same type is passed to `DetermineAccessibilityConstraint` which has `type = GetOutermostType(type);`

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs (hunk 12 above)
Comment (dopare) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs]: I cannot imagine case when `TypeConstraint` cannot be parented by `TypeParameterConstraintClause`. Just putted for sanity, will remove it.

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs (hunk 14 above)
Comment (dopare) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs]: I will disagree because topmost type is either public or internal. Protected can be only in the middle.

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs (hunk 13 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs]: My point is this:  immediately after you make this call, you then call ```type.GetAncestors<TypeDeclarationSyntax>()```.  You then do not use type again.  So this call, and the overwriting of 'type' seems unnecessary since it will not affect the results you get from ```type.GetAncestors<TypeDeclarationSyntax>()``` :)

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs (hunk 14 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs]: AllContainingTypeAreNotPrivateOrInternal then :)

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs (hunk 13 above)
Comment (dopare) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs]: Ah, sorry my bad. Will fix this.

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs (hunk 14 above)
Comment (dopare) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs]: sure :)

Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs]: Actually, rgd: 

> I will disagree because topmost type is either public or internal. Protected can be only in the middle.

But you still return false, even if the topmost type is internal.  So it's correct to say "AllContainingTypesArePublicOrProtected".

Comment (dopare) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs]: Got your point.

File: src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs (hunk 13 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/Extensions/SemanticModelExtensions.cs]: No worries :)

File: src/EditorFeatures/CSharpTest/Diagnostics/GenerateType/GenerateTypeTests.cs (hunk 16 above)
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/Diagnostics/GenerateType/GenerateTypeTests.cs]: :memo: For this issue, they'll have this form:

```csharp
[WorkItem(18240, "https://github.com/dotnet/roslyn/issues/18240")]
```

**Comment by dopare** [comment]
Fixed all issues from review

File: src/Features/CSharp/Portable/GenerateType/CSharpGenerateTypeService.cs [hunk 18]
```diff
@@ -558,6 +567,12 @@ protected override Accessibility GetAccessibility(State state, SemanticModel sem
                 {
                     accessibility = accessibilityConstraint;
                 }
+                else if (accessibilityConstraint == Accessibility.Protected ||
+                         accessibilityConstraint == Accessibility.ProtectedOrInternal)
+                {
+                    // If nested type is declared in public type then we should generate public type instead of internal
+                    accessibility = AllContainingTypesArePublicOrProtected(state, semanticModel, cancellationToken) ? Accessibility.Public : Accessibility.Internal;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/GenerateType/CSharpGenerateTypeService.cs]: nit: try to wrap lines longer than what github can display.  our general patter for ?: is 

```c#
accessibility = AllContainingTypesArePublicOrProtected(state, semanticModel, cancellationToken)
    ? Accessibility.Public
    : Accessibility.Internal;
```

Comment (dopare) [inline src/Features/CSharp/Portable/GenerateType/CSharpGenerateTypeService.cs]: sure

**Comment by 333fred** [comment]
Currently investigating vsi failures. Don't read anything into vsi failures for now.

**Comment by dopare** [comment]
Rebased onto roslyn/master

**Comment by sharwell** [comment]
@dopare This one has been sitting and I'd like to get it prepared for merge. Would you like to handle the updates, or would you like me to "take over" the pull request since it's likely to require more preparation given the amount of time it sat for?

**Comment by dopare** [comment]
@sharwell Please take over. Currently I don't have enough time to make updates.

**Comment by jinujoseph** [comment]
approved to merge for 15.8.preview3

**Comment by jinujoseph** [comment]
test windows_release_vs-integration_prtest

**Comment by sharwell** [comment]
@dopare Thank you! 😄

**Comment by dopare** [comment]
Holy moly, finally 😄
