### PR TITLE
Adjust inconsistent accessibility checks to properly handle protected types declared within interfaces.

### LINKED ISSUE #38398: Inconsistent accessibility checks  produce unexpected errors when types nested into interfaces are involved
```
        [Fact]
        public void InconsistentAccessibility()
        {
            var source1 =
@"
    interface I1
    {
        protected interface I2
        {
        }
    }

    class C1
    {
        protected interface I2
        {
        }
    }

    interface I3 : I1
    {
        protected I1.I2 M1();
    }

    class C3 : I1
    {
        protected void M1(I1.I2 x) { }
    }

    class C33 : C1
    {
        protected void M1(C1.I2 x) { }
    }
";
            var compilation1 = CreateCompilation(source1, options: TestOptions.DebugDll,
                                                 parseOptions: TestOptions.Regular,
                                                 targetFramework: TargetFramework.NetStandardLatest);
            compilation1.VerifyDiagnostics(
                // (18,25): error CS0050: Inconsistent accessibility: return type 'I1.I2' is less accessible than method 'I3.M1()'
                //         protected I1.I2 M1();
                Diagnostic(ErrorCode.ERR_BadVisReturnType, "M1").WithArguments("I3.M1()", "I1.I2").WithLocation(18, 25),
                // (23,24): error CS0051: Inconsistent accessibility: parameter type 'I1.I2' is less accessible than method 'C3.M1(I1.I2)'
                //         protected void M1(I1.I2 x) { }
                Diagnostic(ErrorCode.ERR_BadVisParamType, "M1").WithArguments("C3.M1(I1.I2)", "I1.I2").WithLocation(23, 24)
                );
        }
```

Expected: No errors. Note, we don't produce the error for scenario when protected interface is nested into a class, the C33 case.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #38398.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs [hunk 1]
```diff
@@ -20693,6 +20693,300 @@ class Test2 : I1, I2, I3
...
+                // (22,29): error CS0050: Inconsistent accessibility: return type 'I1.I2' is less accessible than method 'I3.I4.M4()'
+                //             protected I1.I2 M4();
+                Diagnostic(ErrorCode.ERR_BadVisReturnType, "M4").WithArguments("I3.I4.M4()", "I1.I2").WithLocation(22, 29),
+                // (41,17): error CS0535: 'CI4' does not implement interface member 'I3.I4.M4()'
+                //     class CI4 : I3.I4
+                Diagnostic(ErrorCode.ERR_UnimplementedInterfaceMember, "I3.I4").WithArguments("CI4", "I3.I4.M4()").WithLocation(41, 17),
+                // (43,12): error CS0122: 'I1.I2' is inaccessible due to its protection level
+                //         I1.I2 I3.I4.M4() => null;
+                Diagnostic(ErrorCode.ERR_BadAccess, "I2").WithArguments("I1.I2").WithLocation(43, 12),
+                // (43,21): error CS0539: 'CI4.M4()' in explicit interface declaration is not found among members of the interface that can be implemented
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs]: >CI4.M4()' [](start = 43, length = 9)

This diagnostic doesn't make sense.  There is no member `CI4.M4()`.

File: src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs [hunk 2]
```diff
@@ -20693,6 +20693,300 @@ class Test2 : I1, I2, I3
...
+                // (52,29): error CS0050: Inconsistent accessibility: return type 'I1.I2' is less accessible than method 'C3.I6.M6()'
+                //             protected I1.I2 M6();
+                Diagnostic(ErrorCode.ERR_BadVisReturnType, "M6").WithArguments("C3.I6.M6()", "I1.I2").WithLocation(52, 29),
+                // (71,17): error CS0535: 'CI6' does not implement interface member 'C3.I6.M6()'
+                //     class CI6 : C3.I6
+                Diagnostic(ErrorCode.ERR_UnimplementedInterfaceMember, "C3.I6").WithArguments("CI6", "C3.I6.M6()").WithLocation(71, 17),
+                // (73,12): error CS0122: 'I1.I2' is inaccessible due to its protection level
+                //         I1.I2 C3.I6.M6() => null;
+                Diagnostic(ErrorCode.ERR_BadAccess, "I2").WithArguments("I1.I2").WithLocation(73, 12),
+                // (73,21): error CS0539: 'CI6.M6()' in explicit interface declaration is not found among members of the interface that can be implemented
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs]: >CI6.M6()' [](start = 43, length = 9)

Similarly here.

File: src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs [hunk 3]
```diff
@@ -28962,6 +29256,190 @@ public void M1()
...
+                // (16,23): error CS0122: 'I1.I2' is inaccessible due to its protection level
+                // interface I3 : I1, I1.I2
+                Diagnostic(ErrorCode.ERR_BadAccess, "I2").WithArguments("I1.I2").WithLocation(16, 23),
+                // (21,20): error CS0246: The type or namespace name 'I2' could not be found (are you missing a using directive or an assembly reference?)
+                // interface I4 : I1, I2
+                Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "I2").WithArguments("I2").WithLocation(21, 20),
+                // (23,5): error CS0246: The type or namespace name 'I2' could not be found (are you missing a using directive or an assembly reference?)
+                //     I2 MI4();
+                Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "I2").WithArguments("I2").WithLocation(23, 5),
+                // (26,19): error CS0122: 'I1.I2' is inaccessible due to its protection level
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs]: this doesn't look correct.  That name should have been inherited.

File: src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs]: > This diagnostic doesn't make sense.  There is no member CI4.M4().

This is a preexisting condition. Not related to this PR and not related to Default Interface Implementations feature. I'll open an issue for this.
```
interface I100 { }

class C100 : I100
{
    object I100.M4() => null;
}
```

---
In reply to: [320499405](https://github.com/dotnet/roslyn/pull/38451#discussion_r320499405) [](ancestors = 320499405)

File: src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs]: Same response.

---
In reply to: [320500601](https://github.com/dotnet/roslyn/pull/38451#discussion_r320500601) [](ancestors = 320500601)

File: src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs [hunk 4]
```diff
@@ -28962,6 +29256,190 @@ public void M1()
...
+                // interface I5 : I1.I2, I1
+                Diagnostic(ErrorCode.ERR_BadAccess, "I2").WithArguments("I1.I2").WithLocation(26, 19),
+                // (31,16): error CS0246: The type or namespace name 'I2' could not be found (are you missing a using directive or an assembly reference?)
+                // interface I6 : I2, I1
+                Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "I2").WithArguments("I2").WithLocation(31, 16),
+                // (33,5): error CS0246: The type or namespace name 'I2' could not be found (are you missing a using directive or an assembly reference?)
+                //     I2 MI6();
+                Diagnostic(ErrorCode.ERR_SingleTypeNameNotFound, "I2").WithArguments("I2").WithLocation(33, 5),
+                // (36,19): error CS0122: 'I1.I2' is inaccessible due to its protection level
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs]: Same here.

File: src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs]: Opened #38467.

---
In reply to: [320501718](https://github.com/dotnet/roslyn/pull/38451#discussion_r320501718) [](ancestors = 320501718,320499405)

File: src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs (hunk 3 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs]: > this doesn't look correct.  That name should have been inherited.

Could you clarify please? Shouldn't we treat the set of base interfaces empty while we are resolving bases?
Somewhat similar to the ```class C33 : C1, C1.I2``` case, which wasn't changed in this PR.

---
In reply to: [320501659](https://github.com/dotnet/roslyn/pull/38451#discussion_r320501659) [](ancestors = 320501659)

File: src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs (hunk 4 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs]: > Same here.

Same response.

---
In reply to: [320502282](https://github.com/dotnet/roslyn/pull/38451#discussion_r320502282) [](ancestors = 320502282)

**Comment by gafter** [comment]
It would be nice to have a positive test, something like
``` c#
public interface I1
{
    protected interface I3 { }
}

public interface I2 : I1
{
    protected I3 M1();
    protected I1.I3 M2();
}
```

File: src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs (hunk 3 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs]: > Could you clarify please? Shouldn't we treat the set of base interfaces empty while we are resolving bases?

Sure, but we are not resolving bases here.  We are resolving the return type of a method.  The type declaration is
``` c#
interface I4 : I1, I2
{
    I2 MI4();
}
```
In this case the base interface `I2` isn't found so it is an error type or ignored or something.  But `I1` is resolved as a base interface, so its accessible members are inherited into the scope of `I4.  One of those members is `I2`, and that is accessible because it is `protected` and used in `I4` which is a subtype.


---
In reply to: [320506172](https://github.com/dotnet/roslyn/pull/38451#discussion_r320506172) [](ancestors = 320506172,320501659)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs]: > In this case the base interface I2 isn't found so it is an error type or ignored or something.  But I1 is resolved as a base interface, so its accessible members are inherited into the scope of I4.  One of those members isI2, and that is accessible because it isprotectedand used inI4` which is a subtype.

CodeFlow shows the original comment on a message corresponding to this code  ```interface I5 : I1.I2, I1```. Regardless, I think I already captured the issue in #38469.

---
In reply to: [320517670](https://github.com/dotnet/roslyn/pull/38451#discussion_r320517670) [](ancestors = 320517670,320506172,320501659)

**Comment by AlekseyTs** [comment]
> It would be nice to have a positive test, something like ...

I think it is covered in ```InconsistentAccessibility_01```
```
    interface I3 : I1
    {
        protected I1.I2 M1();
```

---
In reply to: [527676085](https://github.com/dotnet/roslyn/pull/38451#issuecomment-527676085) [](ancestors = 527676085)

**Comment by gafter** [comment]
When I say positive test, I mean one that compiles without errors.

---
In reply to: [527989572](https://github.com/dotnet/roslyn/pull/38451#issuecomment-527989572) [](ancestors = 527989572,527676085)

**Comment by AlekseyTs** [comment]
> When I say positive test, I mean one that compiles without errors.

That declaration doesn't produce any error. I see no good reason to separate it in a dedicated test.

---
In reply to: [527991488](https://github.com/dotnet/roslyn/pull/38451#issuecomment-527991488) [](ancestors = 527991488,527989572,527676085)

**Comment by AlekseyTs** [comment]
@gafter 

I think I responded to all your comments.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

**Comment by gafter** [comment]
In a test that has errors, it is hard to be confident that a part of it on which no errors occur would compile without error in isolation.  That is because we employ various strategies to eliminate cascaded diagnostics.  Generally speaking, positive tests should be separated from negative tests for this reason among others.

---
In reply to: [527992086](https://github.com/dotnet/roslyn/pull/38451#issuecomment-527992086) [](ancestors = 527992086,527991488,527989572,527676085)

**Comment by AlekseyTs** [comment]
>  That is because we employ various strategies to eliminate cascaded diagnostics. 

I am confident that this is not applicable to the tested scenarios.

> Generally speaking, positive tests should be separated from negative tests for this reason among others.

We don't have a requirement to do this. In fact it is our common practice to combine positive and success scenarios in one unit-test. There are exceptions, but I think they do not apply to this scenario.

---
In reply to: [527996007](https://github.com/dotnet/roslyn/pull/38451#issuecomment-527996007) [](ancestors = 527996007,527992086,527991488,527989572,527676085)

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

**Comment by AlekseyTs** [comment]
@gafter Do you have additional comments?

**Comment by gafter** [comment]
No, just that one last comment about positive tests.

**Comment by AlekseyTs** [comment]
> No, just that one last comment about positive tests.

Are you blocking this PR based on that comment?

**Comment by gafter** [comment]
I did not intend to do anything to block this PR.

**Comment by AlekseyTs** [comment]
> I did not intend to do anything to block this PR.

Would you mind signing-off then, since you already reviewed the change?

**Comment by gafter** [comment]
I would prefer to see some positive tests as described in my review comments.

**Comment by AlekseyTs** [comment]
@gafter 

> I would prefer to see some positive tests as described in my review comments.

Is this the only reason why you do not sign-off, i.e. block this PR from merging?

**Comment by gafter** [comment]
If the positive tests were separated from the negative tests, I would sign off.
