### PR TITLE
Fix run code analysis on solution not reporting results

### LINKED ISSUE #77495: Run Code Analysis continues to be broken
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Run-Code-Analysis-continues-to-be-broken/10826316)._

---
When I right click on my project in the Solution Explorer, and select Analyze and Code Cleanup | Run Code Analysis, I see in the status bar that Code Analysis is running. But when it completes, it almost never shows me any issues in the Error List window.

Occasionally, it will shows suggestions, sometimes a minute or so after Code Analysis completed. But mostly, it shows nothing, and the Error List window is empty. (I have it set to show Errors, Warnings and Messages.)

I have struggled with this feature for years. When I open a file, it will generally show the issues in that file. But for a very large project, this makes finding all the issues a major operation. Why can't Visual Studio run an analysis on my entire project and report all the issues it finds. This would be great!

I found similar issues to mine, but the closest one has been closed as fixed. I have no idea how anyone thought this was fixed as it isn't working.

---
#### Feedback Bot on 1/13/2025, 00:35 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Runtong Liu (Centific Technologies Inc) [MSFT] on 1/14/2025, 01:45 AM: 

<p>Thank you for taking the time to log this issue!</p>
<p>Do you still repro this issue now? I can’t repro this issue this issue in Visual Studio Community 2022(17.12.3).<br>
In the Error List window, make sure the Show dropdown is set to Build + IntelliSense.<br>
If the issue still exists, can you provide us a repro video using <a target='_blank' href="https://www.screentogif.com/or">https://www.screentogif.com/or</a> a similar tool?</p>
<p>We look forward to hearing from you!</p>

#### Feedback Bot on 1/22/2025, 03:51 AM: 

<p>We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.</p>

#### Feedback Bot on 3/10/2025, 01:09 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
#### Rose Hazel Joy Bigcas (CSI INTERFUSION INC) [MSFT] solved on 2/5/2025, 08:18 PM, undefined votes: 

<p>We are unable to investigate this issue further without the additional information requested. If you are able to provide more information, you can request the issue being reactivate below. See our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines">guidelines</a> for further information about our process.</p>

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #77495

### CODE REVIEW

File: src/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs [hunk 1]
```diff
@@ -2040,7 +2041,7 @@ public async Task TestWorkspaceDiagnosticsWaitsForLspTextChanges(bool useVSDiagn
         await testLspServer.OpenDocumentAsync(uri);
 
         // Assert the task completes after a change occurs
-        var results = await resultTask;
+        var results = await resultTask.WithTimeout(TimeSpan.FromSeconds(1));
```
Comment (sharwell) [inline src/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs:2044]: 📝 Changed all three event tests to include this timeout. Without it, test failure results in a hang instead of failing the test.

Comment (CyrusNajmabadi) [reply src/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs:2044]: is 1 sec long enough?

**Review by dibarbet — APPROVED** [review]

File: src/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs (hunk 1 above)
Comment (dibarbet) [reply src/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs:2044]: 1 second should generally be enough - (there is no actual work being done after).  However CI machines are slow, so I'm not 100% confident.  We can monitor and see, should be pretty easy to tell when we hit failures./

Comment (sharwell) [reply src/LanguageServer/ProtocolUnitTests/Diagnostics/PullDiagnosticTests.cs]: 1 second is not long enough. Changed to 4 minutes.
