### PR TITLE
Handle dependent slots in pattern-matching null tests.

### LINKED ISSUE #39264: Roslyn doesn't understand pattern-matching null check for properties
**Version Used**: 

```
Branch master (23 Sep 2019)
Latest commit 89b4f60 by Charles Stoner:
Allow conversion of collection initializer Add extension method this arg (#38732)
```

**Steps to Reproduce**:

Compile the following code:
```cs
#nullable enable
class C
{
    string? field;

    void M1(C c)
    {
        if (c.field == null) return;
        
        c.field.ToString();
    }
    
    void M2(C c)
    {
        if (c is { field: null }) return;
        
        c.field.ToString(); // incorrect CS8602
    }
}
```
[sharplab ](https://sharplab.io/#v2:D4AQDABCCMB0AiBLAhgcwHYHsDOAXRAxtrAMKYAmApgILrIA2AntotgNwCwAUNwMToBXevWQAjepQiU64yt24gATBBLcA3twhao0MAH4IAM0SV65CAF4Ig4Zx5dtUACwQAstAAUJCAQCUm7Q0HR21EQwgPAlhjU3MLKxt6XygAdjsQ7QCMqJizWAAVTABlXAAnRHRUD1907QBfLIhGkBdXRS8ff2CtIIytMIiCCFYINSMTMwAuayF6CDrkkDTGxxXtHInyAuKyiqqaiAB6Q+H0AkxS0soCXBUigA4ANjBFRoauOqA===)

**Expected Behavior**:
Both methods report no warnings; If `c.field` is null method returns in both cases before using it.

**Actual Behavior**:
`M2` has an incorrect warning `CS8602: Dereference of a possibly null reference` reported for `c.field.ToString()`

**Notes**
It's actually even worse since such null checks makes Roslyn think that `field` is checked for null but does not update it to non-null on the false branch. Consequently Roslyn reports the warning even if `field` is declared as **non-nullable** `string`
i.e.
```
#nullable enable
class C
{
    string field;
    
    void M2(C c)
    {
        if (c is { field: null }) return;
        
        c.field.ToString(); // incorrect CS8602
    }
}
```

Note that current behavior is quite annoyting since it does not allow me to hande nulls hvia separate patterns in switches e.g.:
```cs
#nullable enable
class C
{
    string? field;
    
    void M2(C c)
    {
        switch (c)
        {
            case { field: null }: break;
            case var copy:
            {
              copy.field.ToString(); // CS8602
              c.field.ToString(); // CS8602
              break;
            }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #39264

### CODE REVIEW

**Comment by gafter** [comment]
@agocke @RikkiGibson Could you please review this?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 1]
```diff
@@ -2702,19 +2702,53 @@ private int LearnFromNullTest(BoundExpression expression, ref LocalState state)
...
 
             return slot;
         }
 
+        // If we know for sure that a slot contains a null value, then we know for sure that dependent slots
+        // are "unreachable" so we might as well treat them as not null.  That way when this state is merged
+        // with another state, those dependent states won't pollute values from the other state.
+        private void MarkDependentSlotsNotNull(int slot, TypeSymbol expressionType, ref LocalState state)
+        {
+            var variable = variableBySlot[slot];
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >variable [](start = 16, length = 8)

This looks unused

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 2]
```diff
@@ -2702,19 +2702,53 @@ private int LearnFromNullTest(BoundExpression expression, ref LocalState state)
...
+                NamedTypeSymbol containingType = this._symbol?.ContainingType;
+                if ((member.Kind == SymbolKind.Property && !((PropertySymbol)member).IsIndexedProperty || member.Kind == SymbolKind.Field) &&
+                    member.RequiresInstanceReceiver() &&
+                    (containingType is null || AccessCheck.IsSymbolAccessible(member, containingType, ref discardedUseSiteDiagnostics)))
+                {
+                    int childSlot = GetOrCreateSlot(member, slot, true);
+                    if (childSlot > 0)
+                    {
+                        state[childSlot] = NullableFlowState.NotNull;
+                        MarkDependentSlotsNotNull(childSlot, member.GetTypeOrReturnType().Type, ref state);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Is there a test that demonstrates that this does something reasonable when the type being tested via `x is { field: null }` has a recursive field or mutually recursive fields?

**Comment by RikkiGibson** [comment]
Done with review pass (iteration 4)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 2 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Added.


---
In reply to: [353426548](https://github.com/dotnet/roslyn/pull/39625#discussion_r353426548) [](ancestors = 353426548)

**Comment by gafter** [comment]
@agocke Could you please review this?

@RikkiGibson I think I have responded to all of your comments.  Do you have any more?

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesVsPatterns.cs [hunk 3]
```diff
@@ -1933,5 +1933,81 @@ public interface IOut<out T> { }
...
+        [WorkItem(39264, "https://github.com/dotnet/roslyn/issues/39264")]
+        public void IsPatternSplitState_02()
+        {
+            CSharpCompilation c = CreateNullableCompilation(@"
+#nullable enable
+class C
+{
+    C? c = null;
+
+    void M1(C c, bool b)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesVsPatterns.cs]: >bool b [](start = 17, length = 6)

nit: this parameter looks unused

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesVsPatterns.cs [hunk 4]
```diff
@@ -1933,5 +1933,81 @@ public interface IOut<out T> { }
...
+    {
+        if (c is { c : null })
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesVsPatterns.cs]: >  [](start = 20, length = 1)

nit: formatting

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 5]
```diff
@@ -2702,19 +2702,52 @@ private int LearnFromNullTest(BoundExpression expression, ref LocalState state)
             // We should not blindly strip conversions here. Tracked by https://github.com/dotnet/roslyn/issues/36164
             var expressionWithoutConversion = RemoveConversion(expression, includeExplicitConversions: true).expression;
             var slot = MakeSlot(expressionWithoutConversion);
-            return LearnFromNullTest(slot, expressionWithoutConversion.Type, ref state);
+
+            // since we know for sure the slot is null (we just tested it), we know that dependent slots are not
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >since [](start = 15, length = 5)

Minor nit: `Since`

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 6]
```diff
@@ -2702,19 +2702,52 @@ private int LearnFromNullTest(BoundExpression expression, ref LocalState state)
...
+            // reachable and therefore can be treated as not null.  However, we have not computed the proper
+            // (inferred) type for the expression, so we cannot compute the correct symbols for the member slots here
+            // (using the incorrect symbols would result in computing an incorrect default state for them).
+            // Therefore we do not mark dependent slots not null.  See https://github.com/dotnet/roslyn/issues/39624
+            return LearnFromNullTest(slot, expressionWithoutConversion.Type, ref state, markDependentSlotsNotNull: false);
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >markDependentSlotsNotNull: false [](start = 88, length = 32)

Consider either making the parameter always explicit, or not passing the default value.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 7]
```diff
@@ -2702,19 +2702,52 @@ private int LearnFromNullTest(BoundExpression expression, ref LocalState state)
...
+        // If we know for sure that a slot contains a null value, then we know for sure that dependent slots
+        // are "unreachable" so we might as well treat them as not null.  That way when this state is merged
+        // with another state, those dependent states won't pollute values from the other state.
+        private void MarkDependentSlotsNotNull(int slot, TypeSymbol expressionType, ref LocalState state)
+        {
+            foreach (var member in expressionType.GetMembers())
+            {
+                HashSet<DiagnosticInfo> discardedUseSiteDiagnostics = null;
+                NamedTypeSymbol containingType = this._symbol?.ContainingType;
+                if ((member.Kind == SymbolKind.Property && !((PropertySymbol)member).IsIndexedProperty || member.Kind == SymbolKind.Field) &&
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >member.Kind == SymbolKind.Property && !((PropertySymbol)member [](start = 21, length = 62)

Consider using an `is` declaration pattern instead of a kind check and a cast.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 6 above)
Comment (333fred) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Alternatively, since there's only one call that actually passes true, consider not adding this flag to `LearnFromNullTest` and just calling `MarkDependentSlotsNotNull` there directly.

---
In reply to: [357310030](https://github.com/dotnet/roslyn/pull/39625#discussion_r357310030) [](ancestors = 357310030)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesVsPatterns.cs [hunk 8]
```diff
@@ -1933,5 +1933,81 @@ public interface IOut<out T> { }
...
+        {
+            if (c.c != null)
+            {
+                c.c.c.c.ToString();
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesVsPatterns.cs]: Why is there no warning here? We tested `c.c`, but not `c.c.c` and not `c.c.c.c`.

**Comment by 333fred** [comment]
Done review pass (commit 5)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesVsPatterns.cs (hunk 8 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesVsPatterns.cs]: That is the point of this change.  We don't need a warning, because the compiler has inferred that null cannot arise here as a consequence of previous tests.  (Try to write a counterexample.  You cannot.)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesVsPatterns.cs [hunk 9]
```diff
@@ -1933,5 +1933,81 @@ public interface IOut<out T> { }
...
+    void M1(C c)
+    {
+        if (c.field == null) return;
+        
+        c.field.ToString();
+    }
+    
+    void M2(C c)
+    {
+        if (c is { field: null }) return;
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesVsPatterns.cs]: Consider adding a test with an unrelated field, to ensure that we still issue a warning when its accessed.

**Comment by gafter** [comment]
@333fred I think I have responded to your comments.  Do you have any others?

@agocke Could you review this please?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 10]
```diff
@@ -2702,19 +2702,52 @@ private int LearnFromNullTest(BoundExpression expression, ref LocalState state)
...
 
             return slot;
         }
 
+        // If we know for sure that a slot contains a null value, then we know for sure that dependent slots
+        // are "unreachable" so we might as well treat them as not null.  That way when this state is merged
+        // with another state, those dependent states won't pollute values from the other state.
+        private void MarkDependentSlotsNotNull(int slot, TypeSymbol expressionType, ref LocalState state)
+        {
+            foreach (var member in expressionType.GetMembers())
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: This seems like a lot of potentially unnecessary work. Can we instead check at the point of use of a slot whether its root slot is null?

Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Or could we loop over all the known slots rather than looping over members? See `InheritNullableStateOfTrackableType` for instance:
```C#
for (int s = slot + 1; s < nextVariableSlot; s++)
{
        var variable = variableBySlot[s];
        if (variable.ContainingSlot != valueSlot)
        {
            continue;
        }
        var member = variable.Symbol;
        // ...
}
```

---
In reply to: [357859900](https://github.com/dotnet/roslyn/pull/39625#discussion_r357859900) [](ancestors = 357859900)

Comment (gafter) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: No, that doesn't work.  It might NOT be null, which is the case in the original bug report.  It is just that there was a null on a different branch with which we merged.  If it wasn't due to a pure null test, the null does not persist.

**Comment by gafter** [comment]
@dotnet/roslyn-compiler Can I get a Sr engineer to review this, please?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 10 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: No, we don't want to inherit the default state for slots not yet defined.

---
In reply to: [357865066](https://github.com/dotnet/roslyn/pull/39625#discussion_r357865066) [](ancestors = 357865066,357859900)

**Comment by gafter** [comment]
@agocke @cston I think I've responded to your comments. Do you have any others?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 10 above)
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >foreach (var member [](start = 12, length = 19)

If `expressionType` has a member of the same type (a `Next` field for instance), won't we create many slots in this method?

Comment (gafter) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Yes, we certainly will.  There is a test for that.

Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: As we discussed, would it be better to go one level deep only? That should address common cases without creating too many slots.

---
In reply to: [359603638](https://github.com/dotnet/roslyn/pull/39625#discussion_r359603638) [](ancestors = 359603638)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 11]
```diff
@@ -2702,19 +2702,52 @@ private int LearnFromNullTest(BoundExpression expression, ref LocalState state)
...
+                NamedTypeSymbol containingType = this._symbol?.ContainingType;
+                if ((member is PropertySymbol { IsIndexedProperty: false } || member.Kind == SymbolKind.Field) &&
+                    member.RequiresInstanceReceiver() &&
+                    (containingType is null || AccessCheck.IsSymbolAccessible(member, containingType, ref discardedUseSiteDiagnostics)))
+                {
+                    int childSlot = GetOrCreateSlot(member, slot, true);
+                    if (childSlot > 0)
+                    {
+                        state[childSlot] = NullableFlowState.NotNull;
+                        MarkDependentSlotsNotNull(childSlot, member.GetTypeOrReturnType().Type, ref state);
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: This certainly seems to work, but I can't figure out what the base case in this recursion is.

**Comment by gafter** [comment]
@agocke @cston I think I've addressed your comments.  Do you have any other comments?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 12]
```diff
@@ -2702,19 +2702,87 @@ private int LearnFromNullTest(BoundExpression expression, ref LocalState state)
...
+                    int childSlot = GetOrCreateSlot(member, slot, true);
+                    if (childSlot > 0)
+                    {
+                        state[childSlot] = NullableFlowState.NotNull;
+                        MarkDependentSlotsNotNull(childSlot, member.GetTypeOrReturnType().Type, ref state, depth - 1);
+                    }
+                }
+            }
+
+            IEnumerable<Symbol> getMembers(TypeSymbol type)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >IEnumerable [](start = 12, length = 11)

`static`?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 13]
```diff
@@ -2702,19 +2702,87 @@ private int LearnFromNullTest(BoundExpression expression, ref LocalState state)
...
+                        yield return member;
+
+                // Interfaces and type parameters inherit from their effective interfaces
+                foreach (NamedTypeSymbol interfaceType in inheritedInterfaces(type))
+                    foreach (var member in interfaceType.GetMembers())
+                        yield return member;
+
+                yield break;
+
+                NamedTypeSymbol effectiveBase(TypeSymbol type) => type switch
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >NamedTypeSymbol [](start = 16, length = 15)

`static`

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 14]
```diff
@@ -2702,19 +2702,87 @@ private int LearnFromNullTest(BoundExpression expression, ref LocalState state)
...
+                {
+                    TypeParameterSymbol tp => tp.EffectiveBaseClassNoUseSiteDiagnostics,
+                    var t => t.BaseTypeNoUseSiteDiagnostics,
+                };
+
+                ImmutableArray<NamedTypeSymbol> inheritedInterfaces(TypeSymbol type) => type switch
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >ImmutableArray [](start = 16, length = 14)

`static`

**Comment by gafter** [comment]
@cston I think I've addressed all of your comments.  Do you have any others?
