### PR TITLE
When producing character literals, surrogate characters should be escaped.

### LINKED ISSUE #20693: Literal should escape surrogate unicode
**Version Used**: 2.2

**Steps to Reproduce**:

1. Run following code:

    ```cs
    var sw = new StreamWriter(new MemoryStream());
    sw.Write(SyntaxFactory.LiteralExpression(
        SyntaxKind.CharacterLiteralExpression,
        SyntaxFactory.Literal('\uDBFF')));
    sw.Flush();
    ```

**Expected Behavior**:
'\uDBFF'

**Actual Behavior**:
System.Text.EncoderFallbackException: Unable to translate Unicode character \uDBFF at index 1 to specified code page.

https://github.com/dotnet/docfx/issues/1817

### PR DESCRIPTION
**Pull request by gafter**
**Customer scenario**

Use the Roslyn compiler APIs to produce a literal for a unicode character. The generated syntax should be correct (escaped). The bug is that the compiler produces a unicode surrogate directly into the generated program text.

**Bugs this fixes:**

Fixes #20693

**Workarounds, if any**

Client code that produces literals could have a special-case to work around the compiler bug.

**Risk**

Tiny, as the only effect is to handle this previously unhandled unicode category.

**Performance impact**

Tiny, if any, as it adds no new code paths.

**Is this a regression from a previous update?**

No, an old Roslyn bug only recently noticed.

**Root cause analysis:**

No test coverage for this category of unicode character in literals.

**How was the bug found?**

Customer reported.

@dotnet/roslyn-compiler May I please have a couple of reviews of this tiny bug fix?

### CODE REVIEW

**Comment by jcouv** [comment]
Looks like legitimate test failures.

File: src/ExpressionEvaluator/CSharp/Test/ResultProvider/ValueFormattingTests.cs [hunk 1]
```diff
@@ -214,8 +214,8 @@ public void String()
             Assert.Equal("\"\\uffff\"", FormatValue(s, useHexadecimal: true));
 
             string multiByte = "\ud83c\udfc8";
-            Assert.Equal(string.Format(format, "🏈"), FormatValue(multiByte));
-            Assert.Equal(string.Format(format, "🏈"), FormatValue(multiByte, useHexadecimal: true));
+            Assert.Equal(string.Format(format, "\\ud83c\\udfc8"), FormatValue(multiByte));
+            Assert.Equal(string.Format(format, "\\ud83c\\udfc8"), FormatValue(multiByte, useHexadecimal: true));
```
Comment (jaredpar) [inline src/ExpressionEvaluator/CSharp/Test/ResultProvider/ValueFormattingTests.cs]: This looks like we're introducing a breaking change. What is the justification here?

Comment (ufcpp) [inline src/ExpressionEvaluator/CSharp/Test/ResultProvider/ValueFormattingTests.cs]: Emoji is a printable character. I'd like you not to escape them.

Comment (gafter) [inline src/ExpressionEvaluator/CSharp/Test/ResultProvider/ValueFormattingTests.cs]: The justification is that the implementation is incorrect, and the test carefully tests only one case for which the incorrect implementation happens to work. If you test the existing implementation on a random sequence of data it will be wrong more than 1000 times for every time it gets it right.

The escaping logic in the compilers is today computed on a character-by-character basis. There is not enough information from a single surrogate character to determine whether or not escaping it is necessary, so escaping it is the only correct approach without considering more context.

It might be worth changing the escaping logic by making it more complex such that it scans the sequence of characters and considers each character in the context of the characters that precede it and follow it to determine if escaping is necessary. I don't think that is worth the effort.

Comment (gafter) [inline src/ExpressionEvaluator/CSharp/Test/ResultProvider/ValueFormattingTests.cs]: I should also note that the compilers are, generally, not programmed to handle surrogate pairs. Some surrogate pairs are considered letters, but neither the C# nor the VB compiler recognize them as such in identifiers. There is, I believe, an open request to fix that. Making the compilers surrogate-aware is a much larger task than just perfecting how we escape them in literals.

**Comment by gafter** [comment]
@jaredpar Do you have any further comments?

@dotnet/roslyn-compiler May I please have a second review of this small change?

File: src/ExpressionEvaluator/CSharp/Test/ResultProvider/ValueFormattingTests.cs (hunk 1 above)
Comment (jaredpar) [inline src/ExpressionEvaluator/CSharp/Test/ResultProvider/ValueFormattingTests.cs]: > The justification is that the implementation is incorrect, and the test carefully tests only one case for which the incorrect implementation happens to work.

The implementation is incorrect but people may be depending on it. Should we be taking this through compat council?

Comment (gafter) [inline src/ExpressionEvaluator/CSharp/Test/ResultProvider/ValueFormattingTests.cs]: That would be a fine idea. I'll start a thread.

Comment (gafter) [inline src/ExpressionEvaluator/CSharp/Test/ResultProvider/ValueFormattingTests.cs]: @ufcpp While it is true that emoji are printable, they cannot be represented as characters without being encoded, either as a surrogate pair or as a sequence of ASCII characters representing a C# unicode escape sequence. This PR proposes them to be escaped using a C# unicode escape sequence.

Leaving them as a surrogate pair is problematic, as the resulting source cannot be encoded as UTF8. That's because surrogate characters cannot properly be encoded in UTF-8. See http://unicodebook.readthedocs.io/issues.html#strict-utf8-decoder

To enable the resulting source to be output to a file in any encoding (including UTF-8), we prefer the C# escape sequence.

Comment (tannergooding) [inline src/ExpressionEvaluator/CSharp/Test/ResultProvider/ValueFormattingTests.cs]: @gafter, I didn't think the language  required input to be UTF-8? Only that a conforming compiler had to support at-least UTF-8.

I would think, if the compiler supports UTF-16 and the user decides to use UTF-16 characters, then the compiler should just work (and should not care if the sequence can be represented in UTF-8 or not).

The spec currently (and as far back as I can check) defines the various characters as:
```
letter-character:
  A Unicode character of classes Lu, Ll, Lt, Lm, Lo, or Nl 
  A unicode-escape-sequence representing a character of classes Lu, Ll, Lt, Lm, Lo, or Nl
combining-character:
  A Unicode character of classes Mn or Mc 
  A unicode-escape-sequence representing a character of classes Mn or Mc
decimal-digit-character:
  A Unicode character of the class Nd 
  A unicode-escape-sequence representing a character of the class Nd
connecting-character:  
  A Unicode character of the class Pc
  A unicode-escape-sequence representing a character of the class Pc
formatting-character:  
  A Unicode character of the class Cf
  A unicode-escape-sequence representing a character of the class Cf
```

**Comment by gafter** [comment]
OK, I’ve modified the PR to use a “long Unicode” escape sequence when a nicely-paired set of surrogate characters appears in the input.

File: src/ExpressionEvaluator/CSharp/Test/ResultProvider/ValueFormattingTests.cs (hunk 1 above)
Comment (gafter) [inline src/ExpressionEvaluator/CSharp/Test/ResultProvider/ValueFormattingTests.cs]: @tannergooding There would be two problems leaving surrogate pairs in source:
- The direct translation of Unicode surrogates to UTF-8 fails, which is an obstacle to writing source into a UTF-8 encoded file. See http://unicodebook.readthedocs.io/issues.html#strict-utf8-decoder
- Some categories of Unicode code points are not valid in a string literal (e.g. control characters, formatting characters, etc) and must be escaped. But we do not have platform APIs that help us determine the Unicode category of Unicode code points that are represented by surrogate pairs. So we have no way of knowing whether escaping is required. But escaping is always correct.

Comment (tannergooding) [inline src/ExpressionEvaluator/CSharp/Test/ResultProvider/ValueFormattingTests.cs]: > But we do not have platform APIs that help us determine the Unicode category of Unicode code points that are represented by surrogate pairs.

@gafter, I'm not sure what you mean by this statement, `char.GetUnicodeCategory(string, int)` is designed specifically for this purpose.

For example, the sumerian character `𒅴´ is a surrogate pair. Because it is comprised of two separate Unicode characters, it cannot be represented as a character literal (`char c = '𒅴'` is invalid). Because of this, you cannot use `char.GetUnicodeCategory('𒅴')`. However, it is valid in a string (string s = "𒅴") and can therefore be passed to the other overload: `char.GetUnicodeCategory("𒅴", 0)` returns `OtherLetter` (`char.GetUnicodeCategory("𒅴", 1)` returns `Surrogate`).

Comment (tannergooding) [inline src/ExpressionEvaluator/CSharp/Test/ResultProvider/ValueFormattingTests.cs]: > The direct translation of Unicode surrogates to UTF-8 fails, which is an obstacle to writing source into a UTF-8 encoded file

Also, I understand this limitation, but not why it is of a concern to the language or the compiler. It becomes a limitation only to the user in that they have to save the file as UTF-16 or UTF-32. Saving it as UTF-8 is invalid and would be an error in the IDE. If the IDE did save it and the C# compiler retrieved such a source file, we would likely error during parsing.

Comment (gafter) [inline src/ExpressionEvaluator/CSharp/Test/ResultProvider/ValueFormattingTests.cs]: @tannergooding The code in question here is not strictly part of the compiler or language implementation. It is part of a set of APIs design to assist in *producing* source code. As such it must be concerned with whether the source code it produces can be saved in the most common encodings.

Thanks for calling `char.GetUnicodeCategory(string, int)` to my attention. That may be helpful here.

**Comment by gafter** [comment]
@tannergooding suggested using `char.GetUnicodeCategory(string, int)` to determine if a surrogate pair represents a printable Unicode code-point (which could therefore be placed directly into the resulting string). I'll revise the PR to try that.

File: src/ExpressionEvaluator/CSharp/Test/ResultProvider/ValueFormattingTests.cs (hunk 1 above)
Comment (gafter) [inline src/ExpressionEvaluator/CSharp/Test/ResultProvider/ValueFormattingTests.cs]: I should point out that the documentation for `char.GetUnicodeCategory(string, int)` does not describe its treatment of surrogate pairs representing Unicode code-points. It only describes its behavior for characters. These are different because a surrogate pair is a pair of characters representing a single Unicode code-point.

Comment (tannergooding) [inline src/ExpressionEvaluator/CSharp/Test/ResultProvider/ValueFormattingTests.cs]: Yes, the documentation is somewhat lacking. The implementation, however, is here: https://source.dot.net/#System.Private.CoreLib/shared/System/Char.cs,517b834a1717ca04.

It ends up converting the character at `index` to `Utf32` (https://source.dot.net/#System.Private.CoreLib/src/System/Globalization/CharUnicodeInfo.cs,553115e31e8da9c0) and then passes the resulting `int` to the internal lookup table.

The regular `char.GetUnicodeCategory(char)` function does effectively the same but cannot handle surrogate characters due to the limitations of `char` (which can only represent a single utf-16 codepoint).

Comment (tannergooding) [inline src/ExpressionEvaluator/CSharp/Test/ResultProvider/ValueFormattingTests.cs]: > It is part of a set of APIs design to assist in producing source code.

It suddenly makes a lot more sense 😄

**Comment by gafter** [comment]
OK, printable surrogate pairs are preserved as such in the resulting string.

**Comment by khyperia** [comment]
> OK, I’ve modified the PR to use a “long Unicode” escape sequence when a nicely-paired set of surrogate characters appears in the input.

This seems like it has subtle behavior implications that I want to bring up and make sure it's the intended decision - I think it gets complicated because .net is always(?) utf16. Please ask for clarification if my example is unclear (both here and offline work). The two behaviors before/after this change are:

Before:

1) The user passes in a string containing a high unicode codepoint, requiring surrogates in utf16.
1) Surrogate pairs are not merged.
1) They are emitted as `\u[high]\u[low]`.
1) The compiler later parses this. Nothing changes (still represented as surrogate pair).
1) The resulting assembly has a surrogate pair.

After:

1) The user passes in a string containing a high unicode codepoint, requiring surrogates in utf16.
1) Surrogate pairs **are** merged.
1) It is emitted as `\U[codepoint]`.
1) The compiler later parses this. The high-codepoint is converted to a surrogate pair, to be represented in .net as a utf16 string.
1) The resulting assembly has a surrogate pair.

The final behavior is identical, but intermediate steps differ. Imagining a hypothetical C# compiler/runtime that used, say, utf8 instead of utf16 (is such a thing even possible by spec?), the output binary would differ, as the utf8 compiler would not split the codepoint into surrogate pairs, but rather into utf8 encoding. I think this is the desired behavior (as it's the sane behavior, as the alternative (without surrogate-merging) is the utf8 compiler encodes the surrogate pairs in utf8, which is illegal), but I wanted to call it out and make sure I/we understand the change.

(Offtopic: is there a more precise term for "high unicode codepoint", meaning "a codepoint that requires surrogate characters when represented in utf16"? Also, please correct vague/incorrect terminology if you notice it in the above text, I'm still trying to learn the complexities of text encodings)

File: src/Compilers/CSharp/Portable/SymbolDisplay/ObjectDisplay.cs [hunk 2]
```diff
@@ -223,10 +235,30 @@ public static string FormatLiteral(string value, ObjectDisplayOptions options)
...
+                {
+                    var category = CharUnicodeInfo.GetUnicodeCategory(value, i);
+                    if (category == UnicodeCategory.Surrogate)
+                    {
+                        // an unpaired surrogate
+                        builder.Append("\\u" + ((int)c).ToString("x4"));
+                    }
+                    else if (NeedsEscaping(category))
+                    {
+                        var unicode = CombineSurrogates(c, value[++i]);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/SymbolDisplay/ObjectDisplay.cs]: Could use `char.ConvertToUtf32(value, i)` or `char.ConvertToUtf32(value[i], value[i + 1])`.

File: src/Compilers/VisualBasic/Portable/SymbolDisplay/ObjectDisplay.vb [hunk 3]
```diff
@@ -462,6 +469,12 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.ObjectDisplay
                         Yield Quotes()
                     Else
                         Yield Character(c)
+                        If copyPair Then
+                            ' copy the second character of a unciode surrogate pair
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/SymbolDisplay/ObjectDisplay.vb]: Typo: `Unicode`

File: src/Compilers/VisualBasic/Test/Symbol/SymbolDisplay/ObjectDisplayTests.vb [hunk 4]
```diff
@@ -179,6 +179,14 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.UnitTests
         End Sub
 
         <Fact>
+        Public Sub TextForEscapedStringLiterals()
+            Dim literal = SyntaxFactory.Literal(ChrW(&H2028) & "x") ' U+2028 is a line separator
+            Assert.Equal("ChrW(8232) & ""x""", literal.Text)
+            literal = SyntaxFactory.Literal(ChrW(&HDBFF)) ' U+DBFF is a unicode surrogate
+            Assert.Equal("ChrW(56319)", literal.Text)
+        End Sub
```
Comment (cston) [inline src/Compilers/VisualBasic/Test/Symbol/SymbolDisplay/ObjectDisplayTests.vb]: Consider testing `ObjectDisplay.FormatLiteral` directly. Perhaps:
```
Assert.Equal("...",
    ObjectDisplay.FormatLiteral(
        ChrW(&HD83C) & ChrW(&HDFC8),
        ObjectDisplayOptions.UseQuotes Or ObjectDisplayOptions.EscapeNonPrintableCharacters))
```
And a similar test for C# `ObjectDisplayTests`:
```
Assert.Equal("...",
    ObjectDisplay.FormatLiteral("\ud83c", ObjectDisplayOptions.EscapeNonPrintableCharacters));
Assert.Equal("...",
    ObjectDisplay.FormatLiteral("\ud83c\udfc8", ObjectDisplayOptions.EscapeNonPrintableCharacters));
```

**Comment by gafter** [comment]
@khyperia You are not correctly stating the "before" behavior. We previously did not escape (or even detect the presence of) surrogates in any way. We just copied them into the resulting string, not even checking if they are properly paired. That was the bug being fixed here.

**Comment by gafter** [comment]
I should also mention that, conceptually, there is no such thing as a utf8 representation of a surrogate character. Surrogates are part of a utf16 representation of "wide" characters, and utf8 has its own representation for wide characters. But a utf8 sequence representing that utf16 sequence is problematic. See http://unicodebook.readthedocs.io/issues.html#strict-utf8-decoder for details.

**Comment by khyperia** [comment]
> You are not correctly stating the "before" behavior.

Right, yes, my bad - I was a bit vague, I meant "before this specific commit in particular", or perhaps rather "this entire PR but with the surrogate joining left out".

---

I think my comment boils down to: what happens when you round-trip source-to-source? (parse, pass to this API, emit to source again - at least I am assuming that is a valid operation for this API, I'm not exactly sure what it's doing)

Imagine we have two strings:

    var x = "\ud83c\udfc8";

and

    var x = "\U0001F3C8";

(both should be the same football emoji, so just imagine if they're not 🙂)

When converted to binary forms (instead of ascii escape), the two strings are indistinguishable. So later, when round-tripping back to source, how do we know which form to emit in this API? This PR's answer is "always choose the merged version".

---

I think the more I think about it, the more I realize that emitting the paired version is never the right thing to do. I'll leave the above thoughts, because it takes a bit to get to that conclusion, and I want to leave a trail for anyone else to follow along. (I've still not 100% convinced myself, but I think that's just me being stubborn)

That conclusion leaves some interesting questions surrounding other places, though - e.g. do we do unicode analysis on string literals? What do we do if we encounter invalid unicode in a string literal?
What do we do when we encounter a valid utf16 surrogate pair encoded in utf8 source (which seems very interesting if we do not error on invalid utf8 source)? (These are questions that are irrelevant to this PR, I'm just genuinely curious and wondering out loud)

**Comment by gafter** [comment]
> I think my comment boils down to: what happens when you round-trip source-to-source?

When the literal comes from source, we do not *compute* what source should be used for it. We use whatever was written in the actual source, unchanged, because we save it as part of the token. This code only comes into play when you hand-build tokens without providing source, letting the compiler APIs select a source representation for you.

When we are reading a utf8 source file, we must decode it into our internal utf16 representation. A "utf8 representation of a Unicode surrogate" isn't legal utf8, so I would expect the utf8 decoder to choke on the source. utf8 has its own representation for wide Unicode codepoints, which gets converted to a surrogate pair when decoded into utf16.

File: src/Compilers/CSharp/Portable/SymbolDisplay/ObjectDisplay.cs (hunk 2 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/SymbolDisplay/ObjectDisplay.cs]: Didn't know about that API; thanks!

File: src/Compilers/VisualBasic/Test/Symbol/SymbolDisplay/ObjectDisplayTests.vb (hunk 4 above)
Comment (gafter) [inline src/Compilers/VisualBasic/Test/Symbol/SymbolDisplay/ObjectDisplayTests.vb]: `ObjectDisplay` is not a public API. But it is used in `SymbolDisplay.FormatPrimitive`, which I can test.

Comment (cston) [inline src/Compilers/VisualBasic/Test/Symbol/SymbolDisplay/ObjectDisplayTests.vb]: The methods in this class are directly testing `ObjectDisplay`.

**Comment by cston** [comment]
LGTM

**Comment by gafter** [comment]
test windows_debug_vs-integration_prtest please

**Comment by gafter** [comment]
@khyperia Do you approve of this PR in its current form?

**Comment by khyperia** [comment]
LGTM.

> I would expect the utf8 decoder to choke on the source.

Some quick testing seems like there's a couple bugs around this. For example, we have the docs `If the source code files were created with the same codepage that is in effect on your computer or if the source code files were created with UNICODE or UTF-8, you need not use /codepage.`, but I've found an example where not specifying codepage and specifying `/codepage:65001` ([UTF-8](https://msdn.microsoft.com/en-us/library/windows/desktop/dd317756(v=vs.85).aspx)) produces different behavior. (I think the eventual logic boils down to crazy stuff happening deep inside the Encoding class in the stdlib). That's completely irrelevant to this PR, though, I just thought it was interesting.
