### PR TITLE
Include local functions in 'Use expression body' refactoring

### LINKED ISSUE #31477: UseBlockBody refactoring doesn't work on local function
In the following code snippet, I would expect a refactoring to be offered at the `$$` position to convert the local function to a block body.

```C#
void M()
{
    void local() $$=> throw new NotImplementedException();
}
```

### PR DESCRIPTION
**Pull request by rik-smeets**
Resolves #31477.

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/UseExpressionBody/Refactoring/UseExpressionBodyForLocalFunctionsRefactoringTests.cs [hunk 1]
```diff
@@ -0,0 +1,156 @@
...
+using Microsoft.CodeAnalysis.CSharp.UseExpressionBody;
+using Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.CodeRefactorings;
+using Microsoft.CodeAnalysis.Options;
+using Microsoft.CodeAnalysis.Test.Utilities;
+using Roslyn.Test.Utilities;
+using Xunit;
+
+namespace Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.UseExpressionBody
+{
+    [WorkItem(31477, "https://github.com/dotnet/roslyn/issues/31477")]
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/UseExpressionBody/Refactoring/UseExpressionBodyForLocalFunctionsRefactoringTests.cs]: enh.....................

File: src/Features/CSharp/Portable/UseExpressionBody/Helpers/UseExpressionBodyForLocalFunctionHelper.cs [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+            => statement.WithBody(body);
+
+        protected override bool CreateReturnStatementForExpression(
+            SemanticModel semanticModel, LocalFunctionStatementSyntax statement)
+        {
+            if (statement.Modifiers.Any(SyntaxKind.AsyncKeyword))
+            {
+                // if it's 'async TaskLike' (where TaskLike is non-generic) we do *not* want to
+                // create a return statement.  This is just the 'async' version of a 'void' local function.
+                return  statement.ReturnType is GenericNameSyntax genericNameSyntax && genericNameSyntax.Arity != 0;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/UseExpressionBody/Helpers/UseExpressionBodyForLocalFunctionHelper.cs]: 1. two spaces after 'return'.
2. checking the type syntactically means this won't work if this was an alias for example.  can we not just check the actual symbolic type?

File: src/Features/Core/Portable/Diagnostics/Analyzers/IDEDiagnosticIds.cs [hunk 3]
```diff
@@ -99,6 +99,8 @@ internal static class IDEDiagnosticIds
         public const string ValueAssignedIsUnusedDiagnosticId = "IDE0059";
         public const string UnusedParameterDiagnosticId = "IDE0060";
 
+        public const string UseExpressionBodyForLocalFunctionsDiagnosticId = "IDE0061";
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Diagnostics/Analyzers/IDEDiagnosticIds.cs]: probably worth a comment saying this conceptually belongs with the rest, but is here because it was added later.

File: src/EditorFeatures/CSharpTest/UseExpressionBody/Analyzer/UseExpressionBodyForLocalFunctionsAnalyzerTests.cs [hunk 4]
```diff
@@ -0,0 +1,593 @@
...
+using Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Diagnostics;
+using Microsoft.CodeAnalysis.Options;
+using Microsoft.CodeAnalysis.Test.Utilities;
+using Roslyn.Test.Utilities;
+using Xunit;
+
+namespace Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.UseExpressionBody
+{
+    [WorkItem(31477, "https://github.com/dotnet/roslyn/issues/31477")]
+    public class UseExpressionBodyForLocalFunctionsAnalyzerTests : AbstractCSharpDiagnosticProviderBasedUserDiagnosticTest
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/UseExpressionBody/Analyzer/UseExpressionBodyForLocalFunctionsAnalyzerTests.cs]: 1. were these tests effectively copied from the other method tests?
2. do you have tests for 'when multiline'?

File: src/Features/CSharp/Portable/UseExpressionBody/Helpers/UseExpressionBodyForLocalFunctionHelper.cs [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+            => statement.Body;
+
+        protected override ArrowExpressionClauseSyntax GetExpressionBody(LocalFunctionStatementSyntax statement)
+            => statement.ExpressionBody;
+
+        protected override SyntaxToken GetSemicolonToken(LocalFunctionStatementSyntax statement)
+            => statement.SemicolonToken;
+
+        protected override LocalFunctionStatementSyntax WithSemicolonToken(LocalFunctionStatementSyntax statement, SyntaxToken token)
+            => statement.WithSemicolonToken(token);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/UseExpressionBody/Helpers/UseExpressionBodyForLocalFunctionHelper.cs]: interesting.  I learned something new today about LocalFunctions (namely that they have optional semicolons).  Is this tested in the PR?

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/UseExpressionBody/Helpers/UseExpressionBodyForLocalFunctionHelper.cs]: Yeah, that one goes back a ways :)  Presumably to feel more comfortable to C/C++ users where this was required for ambiguity reasons :)

File: src/EditorFeatures/CSharpTest/UseExpressionBody/Refactoring/UseExpressionBodyForLocalFunctionsRefactoringTests.cs (hunk 1 above)
Comment (rik-smeets) [reply src/EditorFeatures/CSharpTest/UseExpressionBody/Refactoring/UseExpressionBodyForLocalFunctionsRefactoringTests.cs]: Maybe I'm missing something obvious (especially since I'm pretty tired today), but what exactly do you mean here?

Comment (rik-smeets) [reply src/EditorFeatures/CSharpTest/UseExpressionBody/Refactoring/UseExpressionBodyForLocalFunctionsRefactoringTests.cs]: Maybe I'm missing something obvious (especially since I'm pretty tired today), but what exactly do you mean here?

File: src/Features/CSharp/Portable/UseExpressionBody/Helpers/UseExpressionBodyForLocalFunctionHelper.cs (hunk 5 above)
Comment (jcouv) [reply src/Features/CSharp/Portable/UseExpressionBody/Helpers/UseExpressionBodyForLocalFunctionHelper.cs]: It looks like `void local() { };` is parsed as a local function followed by an empty statement.

File: src/Features/CSharp/Portable/UseExpressionBody/Helpers/UseExpressionBodyForLocalFunctionHelper.cs (hunk 2 above)
Comment (jcouv) [reply src/Features/CSharp/Portable/UseExpressionBody/Helpers/UseExpressionBodyForLocalFunctionHelper.cs]: For comparison, `UseExpressionBodyForMethodHelper` indeed uses a symbolic type for this check:
```C#
        protected override bool CreateReturnStatementForExpression(
            SemanticModel semanticModel, MethodDeclarationSyntax declaration)
        {
            if (declaration.Modifiers.Any(SyntaxKind.AsyncKeyword))
            {
                // if it's 'async TaskLike' (where TaskLike is non-generic) we do *not* want to
                // create a return statement.  This is just the 'async' version of a 'void' method.
                var method = semanticModel.GetDeclaredSymbol(declaration);
                return method.ReturnType is INamedTypeSymbol namedType && namedType.Arity != 0;
            }
            
            return !declaration.ReturnType.IsVoid();
        }
```

File: src/Features/CSharp/Portable/CodeCleanup/CSharpCodeCleanupService.cs [hunk 6]
```diff
@@ -84,7 +84,8 @@ internal class CSharpCodeCleanupService : ICodeCleanupService
                                        IDEDiagnosticIds.UseExpressionBodyForOperatorsDiagnosticId,
                                        IDEDiagnosticIds.UseExpressionBodyForPropertiesDiagnosticId,
                                        IDEDiagnosticIds.UseExpressionBodyForIndexersDiagnosticId,
-                                       IDEDiagnosticIds.UseExpressionBodyForAccessorsDiagnosticId)),
+                                       IDEDiagnosticIds.UseExpressionBodyForAccessorsDiagnosticId,
+                                       IDEDiagnosticIds.UseExpressionBodyForLocalFunctionsDiagnosticId)),
```
Comment (jcouv) [inline src/Features/CSharp/Portable/CodeCleanup/CSharpCodeCleanupService.cs]: >UseExpressionBodyForLocalFunctionsDiagnosticId [](start = 56, length = 46)

If you don't mind, could you share a screenshot to show what the options look like?

File: src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs [hunk 7]
```diff
@@ -1006,6 +1006,45 @@ void Method()
...
+//[
+class Customer
+{
+    private int Age;
+
+    public int GetAge() 
+    {
+        return GetAgeLocal();
+        
+        int GetAgeLocal() => this.Age;
```
Comment (jcouv) [inline src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs]: >int GetAgeLocal() => this.Age; [](start = 8, length = 30)

nit: we recommend camelCasing for local functions and locals.

File: src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs [hunk 8]
```diff
@@ -1006,6 +1006,45 @@ void Method()
...
+using System;
+
+//[
+class Customer
+{
+    private int Age;
+
+    public int GetAge()
+    {
+        return int GetAgeLocal();
```
Comment (jcouv) [inline src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs]: >int [](start = 15, length = 3)

Typo: this `int` doesn't belong

File: src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs [hunk 9]
```diff
@@ -1006,6 +1006,45 @@ void Method()
 //]
     }
 }
+";
+
+        private const string s_preferExpressionBodyForLocalFunctions = @"
+using System;
+
+//[
```
Comment (jcouv) [inline src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs]: I believe the `//[` and `//]` markers could be scoped more narrowly, to be consistent with other examples in this file. They could just be around the local function.
That said, I don't exactly know what that affects. @CyrusNajmabadi do you know?

File: src/EditorFeatures/CSharpTest/UseExpressionBody/Analyzer/UseExpressionBodyForLocalFunctionsAnalyzerTests.cs [hunk 10]
```diff
@@ -0,0 +1,593 @@
...
+        {
+            return Bar();
+        }
+    }
+
+    Task Bar() { }
+}", options: UseBlockBody);
+        }
+    }
+}
```
Comment (jcouv) [inline src/EditorFeatures/CSharpTest/UseExpressionBody/Analyzer/UseExpressionBodyForLocalFunctionsAnalyzerTests.cs]: would be interesting to also test a nested local function

File: src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs (hunk 7 above)
Comment (genlu) [reply src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs]: Are we using camel case for local function in roslyn?

Comment (jcouv) [reply src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs]: I just heard that IDE uses Pascal for local functions. Compiler users camel.

File: src/EditorFeatures/CSharpTest/UseExpressionBody/Analyzer/UseExpressionBodyForLocalFunctionsAnalyzerTests.cs [hunk 11]
```diff
@@ -0,0 +1,593 @@
...
+    public class UseExpressionBodyForLocalFunctionsAnalyzerTests : AbstractCSharpDiagnosticProviderBasedUserDiagnosticTest
+    {
+        internal override (DiagnosticAnalyzer, CodeFixProvider) CreateDiagnosticProviderAndFixer(Workspace workspace)
+            => (new UseExpressionBodyDiagnosticAnalyzer(), new UseExpressionBodyCodeFixProvider());
+
+        private IDictionary<OptionKey, object> UseExpressionBody =>
+            this.Option(CSharpCodeStyleOptions.PreferExpressionBodiedLocalFunctions, CSharpCodeStyleOptions.WhenPossibleWithSilentEnforcement);
+
+        private IDictionary<OptionKey, object> UseBlockBody =>
+            this.Option(CSharpCodeStyleOptions.PreferExpressionBodiedLocalFunctions, CSharpCodeStyleOptions.NeverWithSilentEnforcement);
```
Comment (genlu) [inline src/EditorFeatures/CSharpTest/UseExpressionBody/Analyzer/UseExpressionBodyForLocalFunctionsAnalyzerTests.cs]: Can you please also add some tests with `CSharpCodeStyleOptions.WhenOnSingleLineWithSilentEnforcement`?

**Comment by jcouv** [comment]
@rik-smeets Just FYI, our deadline for VS 2019 for new features (such as this one) is January 7th. Past that, this would slip to update 1.

File: src/Features/CSharp/Portable/CodeCleanup/CSharpCodeCleanupService.cs (hunk 6 above)
Comment (rik-smeets) [reply src/Features/CSharp/Portable/CodeCleanup/CSharpCodeCleanupService.cs]: Sure:
image

File: src/EditorFeatures/CSharpTest/UseExpressionBody/Analyzer/UseExpressionBodyForLocalFunctionsAnalyzerTests.cs (hunk 4 above)
Comment (rik-smeets) [reply src/EditorFeatures/CSharpTest/UseExpressionBody/Analyzer/UseExpressionBodyForLocalFunctionsAnalyzerTests.cs]: 1. Most of them effectively were. Since they were very complete already, I thought it'd be a good idea to use them as the basis for these tests.
2. I'll commit them in a moment.

File: src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs (hunk 9 above)
Comment (rik-smeets) [reply src/VisualStudio/CSharp/Impl/Options/Formatting/StyleViewModel.cs]: Only the part shown between these markers in shown in the code style preview window. If I make this change, it would become like this:
image

Since you can't see it's a local function anymore, I think we shouldn't make this change.

**Comment by rik-smeets** [comment]
@jcouv @genlu @CyrusNajmabadi Thank you all for reviewing my PR. I think I processed all your review comments, feel free to look at it again.

**Comment by jcouv** [comment]
@jinujoseph Please approve for preview2 and merge. Thanks

**Comment by Neme12** [comment]
Why are so many integration tests failing? Is that expected?

File: src/EditorFeatures/CSharpTest/UseExpressionBody/Refactoring/UseExpressionBodyForLocalFunctionsRefactoringTests.cs (hunk 1 above)
Comment (alrz) [reply src/EditorFeatures/CSharpTest/UseExpressionBody/Refactoring/UseExpressionBodyForLocalFunctionsRefactoringTests.cs]: You apply WorkItem on test methods, not classes. Hard guess.

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/UseExpressionBody/Refactoring/UseExpressionBodyForLocalFunctionsRefactoringTests.cs]: I don't particularly like it because what you're doing now is marking this attribute on all *future* additions to this class.  It makes the attribute overly broad, instead of targetting specific tests.

Furthermore, we don't generally use workitem for *new* feature work.  It's generally for real 'bugs'.

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/UseExpressionBody/Refactoring/UseExpressionBodyForLocalFunctionsRefactoringTests.cs]: regardless, roslyn doesn't follow this pattern elsewhere, so i would prefer we not do things differently just because it's 'legal'.  Please follow the "when in rome" approach for IDE changes.  thanks!

Comment (rik-smeets) [reply src/EditorFeatures/CSharpTest/UseExpressionBody/Refactoring/UseExpressionBodyForLocalFunctionsRefactoringTests.cs]: Well, #31477 is labelled as a _bug_, even though I would personally also call it a feature request. I see your point, I'll just remove the attributes from both classes.

**Comment by JoeRobich** [comment]
Thanks @rik-smeets! =)
