### PR TITLE
Make value sets resilient in error recovery scenarios.

### LINKED ISSUE #44518: IDE crashes when using relational pattern on bool constant
**Version Used**: 16.7P1, master (69b3bf5)

**Steps to Reproduce**:

```c#
class C
{
    void M()
    {
        _ = is < true;
    }
}
```

**Expected Behavior**: Compiler errors.

**Actual Behavior**: The IDE crashes.

```
System.ArgumentException: relation
   at Microsoft.CodeAnalysis.CSharp.ValueSetFactory.BoolValueSetFactory.Related(BinaryOperatorKind relation, Boolean value)
   at Microsoft.CodeAnalysis.CSharp.ValueSetFactory.BoolValueSetFactory.Microsoft.CodeAnalysis.CSharp.IValueSetFactory.Related(BinaryOperatorKind relation, ConstantValue value)
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.<SplitValues>g__resultForRelation|34_0(BinaryOperatorKind relation, ConstantValue value, <>c__DisplayClass34_0& )
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.SplitValues(ImmutableDictionary`2 values, BoundDagTest test)
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.SplitCases(ImmutableArray`1 statesForCases, ImmutableDictionary`2 values, BoundDagTest test, ImmutableArray`1& whenTrue, ImmutableArray`1& whenFalse, ImmutableDictionary`2& whenTrueValues, ImmutableDictionary`2& whenFalseValues, Boolean& foundExplicitNullTest)
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.MakeDecisionDag(ImmutableArray`1 casesForRootNode)
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.MakeBoundDecisionDag(SyntaxNode syntax, ImmutableArray`1 cases)
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.CreateDecisionDagForIsPattern(SyntaxNode syntax, BoundExpression inputExpression, BoundPattern pattern, LabelSymbol whenTrueLabel)
   at Microsoft.CodeAnalysis.CSharp.Binder.MakeIsPatternExpression(SyntaxNode node, BoundExpression expression, BoundPattern pattern, TypeSymbol boolType, Boolean hasErrors, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindIsPatternExpression(IsPatternExpressionSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindAssignment(AssignmentExpressionSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(CSharpSyntaxNode node, ExpressionSyntax syntax, Boolean allowsAnyExpression, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode declaration, BlockSyntax blockBody, ArrowExpressionClauseSyntax expressionBody, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode syntax, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, DiagnosticBag diagnostics, ImportChain& importChain, Boolean& originalBodyNested, InitialState& forSemanticModel)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.VisitNamedType(NamedTypeSymbol symbol, TypeCompilationState arg)
   at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.Accept[TArgument,TResult](CSharpSymbolVisitor`2 visitor, TArgument argument)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamespace(NamespaceSymbol symbol)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean emittingPdb, Boolean emitTestCoverageData, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForMethodBodiesInTree(SyntaxTree tree, Nullable`1 span, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForSyntaxTree(CompilationStage stage, SyntaxTree syntaxTree, Nullable`1 filterSpanWithinTree, Boolean includeEarlierStages, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetDiagnostics(Nullable`1 span, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.GenerateCompilationEvents(AnalysisScope analysisScope, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<ComputeAnalyzerDiagnosticsAsync>d__55.MoveNext()

```

### LINKED ISSUE #44540: Roslyn crashes when use native int with incompleted switch expression.
**Version Used**: 
VS2019 16.7.0 Preview 1.0

**Steps to Reproduce**:
Looks like #44398, but for nint and nuint instead.

https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEBMBGAsAKBQZgAJ1CBhQgb10JuKJQBZCBZACgDsBLdmQgDwCUlAPTCA9gkLsArtxjVaiuYQBehALz9CUAO6cYAYwAWVHIvMXCGdQD5RGADQLLltLbROzlgL4BuZ+YoGACcrCoC/l4WogCC7GIwRoiECHAADghiACbSBnABiqIA+hpanFCENpoYhBDsWZGK3rjeQA=
```cs
using System;
public class C {
    public void M(nint x) {//or nuint
        int z = x switch{
                1=>//1,
                2=>2,
        };
        Console.WriteLine(z);
        //Another reproduce
        //_ = x is >= 1 and;
    }
}
```

**Expected Behavior**:
Compile error, but not `FailFast`.

**Actual Behavior**:
Environment.FailFast in VS.

StackTrace copy from sharplab.
```cs
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.CodeAnalysis.ConstantValue.get_SByteValue() in /_/src/Compilers/Core/Portable/ConstantValue.cs:line 48
   at Microsoft.CodeAnalysis.ConstantValue.get_Int16Value() in /_/src/Compilers/Core/Portable/ConstantValue.cs:line 61
   at Microsoft.CodeAnalysis.ConstantValue.get_Int32Value() in /_/src/Compilers/Core/Portable/ConstantValue.cs:line 64
   at Microsoft.CodeAnalysis.CSharp.ValueSetFactory.NintValueSet.Microsoft.CodeAnalysis.CSharp.IValueSet.Any(BinaryOperatorKind relation, ConstantValue value) in /_/src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.NintValueSet.cs:line 67
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.<CheckConsistentDecision>g__handleRelationWithValue|36_0(BinaryOperatorKind relation, ConstantValue value, Boolean& trueTestPermitsTrueOther, Boolean& falseTestPermitsTrueOther, Boolean& trueTestImpliesTrueOther, Boolean& falseTestImpliesTrueOther, <>c__DisplayClass36_0& ) in /_/src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs:line 1178
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.CheckConsistentDecision(BoundDagTest test, BoundDagTest other, IValueSet whenTrueValues, IValueSet whenFalseValues, SyntaxNode syntax, Boolean& trueTestPermitsTrueOther, Boolean& falseTestPermitsTrueOther, Boolean& trueTestImpliesTrueOther, Boolean& falseTestImpliesTrueOther, Boolean& foundExplicitNullTest) in /_/src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs:line 1206
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.Tests.One.Filter(DecisionDagBuilder builder, BoundDagTest test, IValueSet whenTrueValues, IValueSet whenFalseValues, Tests& whenTrue, Tests& whenFalse, Boolean& foundExplicitNullTest) in /_/src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs:line 1707
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.SplitCase(StateForCase stateForCase, BoundDagTest test, IValueSet whenTrueValues, IValueSet whenFalseValues, StateForCase& whenTrue, StateForCase& whenFalse, Boolean& foundExplicitNullTest) in /_/src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs:line 902
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.SplitCases(ImmutableArray`1 statesForCases, ImmutableDictionary`2 values, BoundDagTest test, ImmutableArray`1& whenTrue, ImmutableArray`1& whenFalse, ImmutableDictionary`2& whenTrueValues, ImmutableDictionary`2& whenFalseValues, Boolean& foundExplicitNullTest) in /_/src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs:line 935
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.MakeDecisionDag(ImmutableArray`1 casesForRootNode) in /_/src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs:line 781
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.MakeBoundDecisionDag(SyntaxNode syntax, ImmutableArray`1 cases) in /_/src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs:line 656
   at Microsoft.CodeAnalysis.CSharp.DecisionDagBuilder.CreateDecisionDagForSwitchExpression(SyntaxNode syntax, BoundExpression switchExpressionInput, ImmutableArray`1 switchArms) in /_/src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs:line 161
   at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.CheckSwitchExpressionExhaustive(SwitchExpressionSyntax node, BoundExpression boundInputExpression, ImmutableArray`1 switchArms, BoundDecisionDag& decisionDag, LabelSymbol& defaultLabel, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/SwitchExpressionBinder.cs:line 68
   at Microsoft.CodeAnalysis.CSharp.SwitchExpressionBinder.BindSwitchExpressionCore(SwitchExpressionSyntax node, Binder originalBinder, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/SwitchExpressionBinder.cs:line 46
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:line 714
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:line 460
   at Microsoft.CodeAnalysis.CSharp.Binder.BindPossibleArrayInitializer(ExpressionSyntax node, TypeSymbol destinationType, BindValueKind valueKind, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 1686
   at Microsoft.CodeAnalysis.CSharp.Binder.BindVariableDeclaration(SourceLocalSymbol localSymbol, LocalDeclarationKind kind, Boolean isVar, VariableDeclaratorSyntax declarator, TypeSyntax typeSyntax, TypeWithAnnotations declTypeOpt, AliasSymbol aliasOpt, DiagnosticBag diagnostics, Boolean includeBoundType, CSharpSyntaxNode associatedSyntaxNode) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 962
   at Microsoft.CodeAnalysis.CSharp.Binder.BindDeclarationStatementParts(LocalDeclarationStatementSyntax node, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 692
   at Microsoft.CodeAnalysis.CSharp.Binder.BindLocalDeclarationStatement(LocalDeclarationStatementSyntax node, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 679
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 160
   at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 1731
   at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 1718
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 160
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode declaration, BlockSyntax blockBody, ArrowExpressionClauseSyntax expressionBody, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 3288
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode syntax, DiagnosticBag diagnostics) in /_/src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:line 3245
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, DiagnosticBag diagnostics, ImportChain& importChain, Boolean& originalBodyNested, InitialState& forSemanticModel) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 1767
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 895
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 511
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass22_0.<CompileNamedTypeAsync>b__0() in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 407
   at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in /_/src/Compilers/Core/Portable/InternalUtilities/UICultureUtilities.cs:line 143
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.WaitForWorkers() in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 316
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean emittingPdb, Boolean emitTestCoverageData, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs:line 203
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForAllMethodBodies(DiagnosticBag diagnostics, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:line 2460
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, DiagnosticBag diagnostics, CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:line 2417
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CancellationToken cancellationToken) in /_/src/Compilers/CSharp/Portable/Compilation/CSharpCompilation.cs:line 2319
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.GetAllDiagnosticsWithoutStateTrackingAsync(ImmutableArray`1 analyzers, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs:line 448
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.GetAllDiagnosticsAsync(CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs:line 313
```

### LINKED ISSUE #44657: System.NullReferenceException in DecisionDagRewriter
Replace VerifyDiagnostics with VerifyEmitDiagnostics in Microsoft.CodeAnalysis.CSharp.UnitTests.PatternMatchingTests3.Relational_SignedEnumExhaustive unit-test and run it.

```
Microsoft.CodeAnalysis.CSharp.UnitTests.PatternMatchingTests3.Relational_SignedEnumExhaustive [FAIL]
  System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter.DecisionDagRewriter.cs(634,0): at Microsoft.CodeAnalysis.CSharp.LocalRewriter.DecisionDagRewriter.<PushEqualityTestsIntoTree>g__splitCases|15_0(ImmutableArray`1 cases, BinaryOperatorKind op, ConstantValue value, <>c__DisplayClass15_0& )
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter.DecisionDagRewriter.cs(616,0): at Microsoft.CodeAnalysis.CSharp.LocalRewriter.DecisionDagRewriter.PushEqualityTestsIntoTree(SyntaxNode syntax, ValueDispatchNode otherwise, ImmutableArray`1 cases, IValueSetFactory fac)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter.DecisionDagRewriter.cs(587,0): at Microsoft.CodeAnalysis.CSharp.LocalRewriter.DecisionDagRewriter.GatherValueDispatchNodes(BoundDecisionDagNode node, HashSet`1 loweredNodes, BoundDagTemp input, IValueSetFactory fac)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter.DecisionDagRewriter.cs(565,0): at Microsoft.CodeAnalysis.CSharp.LocalRewriter.DecisionDagRewriter.GatherValueDispatchNodes(BoundDecisionDagNode node, HashSet`1 loweredNodes, BoundDagTemp input, IValueSetFactory fac)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter.DecisionDagRewriter.cs(538,0): at Microsoft.CodeAnalysis.CSharp.LocalRewriter.DecisionDagRewriter.GatherValueDispatchNodes(BoundDecisionDagNode node, HashSet`1 loweredNodes, BoundDagTemp input)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter.DecisionDagRewriter.cs(495,0): at Microsoft.CodeAnalysis.CSharp.LocalRewriter.DecisionDagRewriter.GenerateSwitchDispatch(BoundDecisionDagNode node, HashSet`1 loweredNodes)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter.DecisionDagRewriter.cs(396,0): at Microsoft.CodeAnalysis.CSharp.LocalRewriter.DecisionDagRewriter.LowerDecisionDagCore(BoundDecisionDag decisionDag)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_BasePatternSwitchLocalRewriter.cs(72,0): at Microsoft.CodeAnalysis.CSharp.LocalRewriter.BaseSwitchLocalRewriter.LowerDecisionDag(BoundDecisionDag decisionDag)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_SwitchExpression.cs(62,0): at Microsoft.CodeAnalysis.CSharp.LocalRewriter.SwitchExpressionLocalRewriter.LowerSwitchExpression(BoundConvertedSwitchExpression node)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_SwitchExpression.cs(40,0): at Microsoft.CodeAnalysis.CSharp.LocalRewriter.SwitchExpressionLocalRewriter.Rewrite(LocalRewriter localRewriter, BoundConvertedSwitchExpression node)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_SwitchExpression.cs(26,0): at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitConvertedSwitchExpression(BoundConvertedSwitchExpression node)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(4398,0): at Microsoft.CodeAnalysis.CSharp.BoundConvertedSwitchExpression.Accept(BoundTreeVisitor visitor)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs(149,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeRewriter.cs(98,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs(235,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(BoundExpression node)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeVisitors.cs(214,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\BoundTree\BoundTreeRewriter.cs(93,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithStackGuard(BoundExpression node)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter.cs(209,0): at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitExpressionImpl(BoundExpression node)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter.cs(168,0): at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Visit(BoundNode node)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(9841,0): at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitReturnStatement(BoundReturnStatement node)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_ReturnStatement.cs(17,0): at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitReturnStatement(BoundReturnStatement node)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(2962,0): at Microsoft.CodeAnalysis.CSharp.BoundReturnStatement.Accept(BoundTreeVisitor visitor)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter.cs(194,0): at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitStatement(BoundStatement node)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_Block.cs(103,0): at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitPossibleUsingDeclaration(BoundStatement node, ImmutableArray`1 statements, Int32 statementIndex, Boolean& replacedLocalDeclarations)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_Block.cs(61,0): at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitStatementSubList(ArrayBuilder`1 builder, ImmutableArray`1 statements, Int32 startIndex)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter_Block.cs(22,0): at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitBlock(BoundBlock node)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Generated\BoundNodes.xml.Generated.cs(2694,0): at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter.cs(194,0): at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitStatement(BoundStatement node)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter.cs(109,0): at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Rewrite(CSharpCompilation compilation, MethodSymbol method, Int32 methodOrdinal, NamedTypeSymbol containingType, BoundStatement statement, TypeCompilationState compilationState, SynthesizedSubmissionFields previousSubmissionFields, Boolean allowOmissionOfConditionalCalls, Boolean instrumentForDynamicAnalysis, ImmutableArray`1& dynamicAnalysisSpans, DebugDocumentProvider debugDocumentProvider, BindingDiagnosticBag diagnostics, Boolean& sawLambdas, Boolean& sawLocalFunctions, Boolean& sawAwaitInExceptionHandler)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs(1324,0): at Microsoft.CodeAnalysis.CSharp.MethodCompiler.LowerBodyOrInitializer(MethodSymbol method, Int32 methodOrdinal, BoundStatement body, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState, Boolean instrumentForDynamicAnalysis, DebugDocumentProvider debugDocumentProvider, ImmutableArray`1& dynamicAnalysisSpans, BindingDiagnosticBag diagnostics, VariableSlotAllocator& lazyVariableSlotAllocator, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, StateMachineTypeSymbol& stateMachineTypeOpt)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs(1152,0): at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs(522,0): at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs(412,0): at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass23_0.<CompileNamedTypeAsync>b__0()
    F:\GitHub\roslyn\src\Compilers\Core\Portable\InternalUtilities\UICultureUtilities.cs(141,0): at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0()
       at System.Threading.Tasks.Task.InnerInvoke()
       at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
       at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
    --- End of stack trace from previous location where exception was thrown ---
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs(327,0): at Microsoft.CodeAnalysis.CSharp.MethodCompiler.WaitForWorkers()
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs(162,0): at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean emittingPdb, Boolean emitTestCoverageData, Boolean hasDeclarationErrors, Boolean emitMethodBodies, BindingDiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
    F:\GitHub\roslyn\src\Compilers\CSharp\Portable\Compilation\CSharpCompilation.cs(2962,0): at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CompileMethods(CommonPEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean emitMetadataOnly, Boolean emitTestCoverageData, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
    F:\GitHub\roslyn\src\Compilers\Core\Portable\Compilation\Compilation.cs(2516,0): at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream metadataPEStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CompilationTestData testData, CancellationToken cancellationToken)
    F:\GitHub\roslyn\src\Compilers\Core\Portable\Compilation\Compilation.cs(2460,0): at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, Stream metadataPEStream, CancellationToken cancellationToken)
    F:\GitHub\roslyn\src\Test\Utilities\Portable\Diagnostics\DiagnosticExtensions.cs(343,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.GetEmitDiagnostics[TCompilation](TCompilation c, EmitOptions options, IEnumerable`1 manifestResources)
    F:\GitHub\roslyn\src\Test\Utilities\Portable\Diagnostics\DiagnosticExtensions.cs(332,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyEmitDiagnostics[TCompilation](TCompilation c, EmitOptions options, DiagnosticDescription[] expected)
    F:\GitHub\roslyn\src\Test\Utilities\Portable\Diagnostics\DiagnosticExtensions.cs(349,0): at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyEmitDiagnostics[TCompilation](TCompilation c, DiagnosticDescription[] expected)
    F:\GitHub\roslyn\src\Compilers\CSharp\Test\Semantic\Semantics\PatternMatchingTests3.cs(2968,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.PatternMatchingTests3.Relational_SignedEnumExhaustive()
```

### PR DESCRIPTION
**Pull request by gafter**
Many of these checks are redundant (because they are checked in the caller) but added
to strengthen the codebase against future changes.
Fixes #44518
Fixes #44540
Fixes #44657

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a couple of reviews of this fix to a crash in pattern-matching scenarios?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs [hunk 1]
```diff
@@ -5501,5 +5501,107 @@ static void Main()
                 );
             var compVerifier = CompileAndVerify(compilation, expectedOutput: expectedOutput);
         }
+
+        [Fact, WorkItem(44518, "https://github.com/dotnet/roslyn/issues/44518")]
+        public void Crash_01()
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs:5506]: >Crash_01 [](start = 20, length = 8)

Minor: Consider naming these something like "InvalidConstant_01", etc. instead since presumably the tests shouldn't crash.

**Comment by cston** [comment]
> Many of these checks are redundant (because they are checked in the caller) but added
to strengthen the codebase against future changes.

Can we test the redundant checks directly, by testing the type class implementations directly for instance?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs [hunk 2]
```diff
@@ -5501,5 +5501,107 @@ static void Main()
...
+    {
+        _ = is < true;
+    }
+}
+";
+            var compilation = CreateCompilation(source, parseOptions: TestOptions.RegularWithPatternCombinators);
+            compilation.VerifyDiagnostics(
+                // (5,13): error CS1525: Invalid expression term 'is'
+                //         _ = is < true;
+                Diagnostic(ErrorCode.ERR_InvalidExprTerm, "is").WithArguments("is").WithLocation(5, 13)
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs:5521]: >ERR_InvalidExprTerm [](start = 37, length = 19)

These errors look like parse errors. Do we hit the binding code with this test? Same comment for tests below.

Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests3.cs:5521]: This test did crash without the fix. See https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATAAgGEBYAKAG8z9r9sAWfAWQAoBKKmy0mn/AfXwBefAEso+ADz4YCAK5wA3B2oBfMiqA

**Comment by gafter** [comment]
@cston I think I've responded to all of your comments. Do you have any others?

@dotnet/roslyn-compiler May I please have a second review of these crash fixes?

**Comment by gafter** [comment]
@cston @dotnet/roslyn-compiler These are compiler/IDE crash bugs, so I'd like to get the fix merged ASAP. Can you please have a look?

File: src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.NintValueSet.cs [hunk 3]
```diff
@@ -53,7 +53,7 @@ public bool All(BinaryOperatorKind relation, int value)
                 return _values.All(relation, value);
             }
 
-            bool IValueSet.All(BinaryOperatorKind relation, ConstantValue value) => All(relation, value.Int32Value);
+            bool IValueSet.All(BinaryOperatorKind relation, ConstantValue value) => value.IsBad ? true : All(relation, value.Int32Value);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Utilities/ValueSetFactory.NintValueSet.cs:56]: Minor: `value.IsBad || All(...)`. Similar comment for other `nint` and `nuint` cases.
