### PR TITLE
A method declared with __arglist is not a candidate with a keyword argument list

### LINKED ISSUE #2631: Crash with IndexOutOfRangeException in OverloadResolution.IsApplicable during SimplifyTypeNamesDiagnosticAnalyzer analysis
Paste C# code:

```C#
class C
{
    void M()
    {
        System.Console.WriteLine("", arg0: 0, arg1: 0, arg2: 0, );
    }
}
```

There's an assert and a crashing exception, both pasted below. First, the assert:
```
System.Exception: ASSERT FAILED 
5/10/2015 4:31:38 PM
Source:    at Roslyn.Editor.TestApp.OutputWindowTraceListener.Fail(String message, String detailMessage) in C:\Roslyn\Main\Closed\Hosting\EditorTestApp\UI\ToolWindows\Output\OutputWindowTraceListener.cs:line 50
   at System.Diagnostics.TraceListener.Fail(String message)
   at System.Diagnostics.TraceInternal.Fail(String message)
   at System.Diagnostics.Debug.Assert(Boolean condition)
   at Microsoft.CodeAnalysis.CSharp.OverloadResolution.IsApplicable(Symbol candidate, EffectiveParameters parameters, AnalyzedArguments arguments, ImmutableArray`1 argsToParameters, Boolean isVararg, Boolean hasAnyRefOmittedArgument, Boolean ignoreOpenTypes, HashSet`1& useSiteDiagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 2582
   at Microsoft.CodeAnalysis.CSharp.OverloadResolution.IsApplicable[TMember](TMember member, TMember leastOverriddenMember, ArrayBuilder`1 typeArgumentsBuilder, AnalyzedArguments arguments, EffectiveParameters originalEffectiveParameters, EffectiveParameters constructedEffectiveParameters, ImmutableArray`1 argsToParamsMap, Boolean hasAnyRefOmittedArgument, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 2504
   at Microsoft.CodeAnalysis.CSharp.OverloadResolution.IsMemberApplicableInNormalForm[TMember](TMember member, TMember leastOverriddenMember, ArrayBuilder`1 typeArguments, AnalyzedArguments arguments, Boolean isMethodGroupConversion, Boolean allowRefOmittedArguments, Boolean inferWithDynamic, HashSet`1& useSiteDiagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 2325
   at Microsoft.CodeAnalysis.CSharp.OverloadResolution.AddMemberToCandidateSet[TMember](TMember member, ArrayBuilder`1 results, ArrayBuilder`1 members, ArrayBuilder`1 typeArguments, AnalyzedArguments arguments, Boolean completeResults, Boolean isMethodGroupConversion, Boolean allowRefOmittedArguments, Dictionary`2 containingTypeMapOpt, Boolean inferWithDynamic, HashSet`1& useSiteDiagnostics, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 495
   at Microsoft.CodeAnalysis.CSharp.OverloadResolution.PerformMemberOverloadResolution[TMember](ArrayBuilder`1 results, ArrayBuilder`1 members, ArrayBuilder`1 typeArguments, AnalyzedArguments arguments, Boolean completeResults, Boolean isMethodGroupConversion, Boolean allowRefOmittedArguments, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 233
   at Microsoft.CodeAnalysis.CSharp.OverloadResolution.MethodOrPropertyOverloadResolution[TMember](ArrayBuilder`1 members, ArrayBuilder`1 typeArguments, AnalyzedArguments arguments, OverloadResolutionResult`1 result, Boolean isMethodGroupConversion, Boolean allowRefOmittedArguments, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 136
   at Microsoft.CodeAnalysis.CSharp.OverloadResolution.MethodInvocationOverloadResolution(ArrayBuilder`1 methods, ArrayBuilder`1 typeArguments, AnalyzedArguments arguments, OverloadResolutionResult`1 result, HashSet`1& useSiteDiagnostics, Boolean isMethodGroupConversion, Boolean allowRefOmittedArguments, Boolean inferWithDynamic, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 101
   at Microsoft.CodeAnalysis.CSharp.Binder.ResolveDefaultMethodGroup(BoundMethodGroup node, AnalyzedArguments analyzedArguments, Boolean isMethodGroupConversion, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 6254
   at Microsoft.CodeAnalysis.CSharp.Binder.ResolveMethodGroupInternal(BoundMethodGroup methodGroup, CSharpSyntaxNode expression, String methodName, AnalyzedArguments analyzedArguments, Boolean isMethodGroupConversion, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 6147
   at Microsoft.CodeAnalysis.CSharp.Binder.ResolveMethodGroup(BoundMethodGroup node, CSharpSyntaxNode expression, String methodName, AnalyzedArguments analyzedArguments, Boolean isMethodGroupConversion, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 6122
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodGroupInvocation(CSharpSyntaxNode syntax, CSharpSyntaxNode expression, String methodName, BoundMethodGroup methodGroup, AnalyzedArguments analyzedArguments, DiagnosticBag diagnostics, CSharpSyntaxNode queryClause, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Invocation.cs:line 452
   at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(CSharpSyntaxNode node, CSharpSyntaxNode expression, String methodName, BoundExpression boundExpression, AnalyzedArguments analyzedArguments, DiagnosticBag diagnostics, CSharpSyntaxNode queryClause, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Invocation.cs:line 222
   at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(InvocationExpressionSyntax node, DiagnosticBag diagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Invocation.cs:line 165
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 408
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 353
   at Microsoft.CodeAnalysis.CSharp.Binder.BindValue(ExpressionSyntax node, DiagnosticBag diagnostics, BindValueKind valueKind) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 288
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(CSharpSyntaxNode node, ExpressionSyntax syntax, Boolean allowsAnyExpression, DiagnosticBag diagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 418
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(ExpressionStatementSyntax node, DiagnosticBag diagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 411
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 49
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.IncrementalBinder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1639
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.Bind(Binder binder, CSharpSyntaxNode node, DiagnosticBag diagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 1996
   at Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.Bind(Binder binder, CSharpSyntaxNode node, DiagnosticBag diagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MethodBodySemanticModel.cs:line 48
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1397
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode(CSharpSyntaxNode node) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 369
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node, CSharpSyntaxNode& bindableNode, BoundNode& lowestBoundNode, BoundNode& highestBoundNode, BoundNode& boundParent) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 896
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 775
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\SyntaxTreeSemanticModel.cs:line 173
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 504
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSymbolInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\CSharpExtensions.cs:line 443
   at Microsoft.CodeAnalysis.CSharp.Extensions.ExpressionSyntaxExtensions.TryReplaceWithAlias(ExpressionSyntax node, SemanticModel semanticModel, Boolean preferAliasToQualifiedName, CancellationToken cancellationToken, IAliasSymbol& aliasReplacement) in C:\Roslyn\Main\Open\src\Workspaces\CSharp\Portable\Extensions\ExpressionSyntaxExtensions.cs:line 868
   at Microsoft.CodeAnalysis.CSharp.Extensions.ExpressionSyntaxExtensions.TryReduce(MemberAccessExpressionSyntax memberAccess, SemanticModel semanticModel, TypeSyntax& replacementNode, TextSpan& issueSpan, OptionSet optionSet, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Workspaces\CSharp\Portable\Extensions\ExpressionSyntaxExtensions.cs:line 722
   at Microsoft.CodeAnalysis.CSharp.Extensions.ExpressionSyntaxExtensions.TryReduceExplicitName(ExpressionSyntax expression, SemanticModel semanticModel, TypeSyntax& replacementNode, TextSpan& issueSpan, OptionSet optionSet, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Workspaces\CSharp\Portable\Extensions\ExpressionSyntaxExtensions.cs:line 665
   at Microsoft.CodeAnalysis.CSharp.Extensions.ExpressionSyntaxExtensions.TryReduceOrSimplifyExplicitName(ExpressionSyntax expression, SemanticModel semanticModel, ExpressionSyntax& replacementNode, TextSpan& issueSpan, OptionSet optionSet, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Workspaces\CSharp\Portable\Extensions\ExpressionSyntaxExtensions.cs:line 637
   at Microsoft.CodeAnalysis.CSharp.Diagnostics.SimplifyTypeNames.CSharpSimplifyTypeNamesDiagnosticAnalyzer.CanSimplifyTypeNameExpression(SemanticModel model, SyntaxNode node, OptionSet optionSet, TextSpan& issueSpan, String& diagnosticId, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Features\CSharp\Diagnostics\Analyzers\CSharpSimplifyTypeNamesDiagnosticAnalyzer.cs:line 132
   at Microsoft.CodeAnalysis.CSharp.Diagnostics.SimplifyTypeNames.CSharpSimplifyTypeNamesDiagnosticAnalyzer.CanSimplifyTypeNameExpressionCore(SemanticModel model, SyntaxNode node, OptionSet optionSet, TextSpan& issueSpan, String& diagnosticId, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Features\CSharp\Diagnostics\Analyzers\CSharpSimplifyTypeNamesDiagnosticAnalyzer.cs:line 93
   at Microsoft.CodeAnalysis.Diagnostics.SimplifyTypeNames.SimplifyTypeNamesDiagnosticAnalyzerBase`1.TrySimplifyTypeNameExpression(SemanticModel model, SyntaxNode node, AnalyzerOptions analyzerOptions, Diagnostic& diagnostic, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Features\Core\Diagnostics\Analyzers\SimplifyTypeNamesDiagnosticAnalyzerBase.cs:line 83
   at Microsoft.CodeAnalysis.CSharp.Diagnostics.SimplifyTypeNames.CSharpSimplifyTypeNamesDiagnosticAnalyzer.<>c__DisplayClass2_0.<AnalyzeNode>b__1(SyntaxNode n) in C:\Roslyn\Main\Open\src\Features\CSharp\Diagnostics\Analyzers\CSharpSimplifyTypeNamesDiagnosticAnalyzer.cs:line 47
   at Microsoft.CodeAnalysis.SyntaxNode.ChildSyntaxListEnumeratorStack..ctor(SyntaxNode startingNode, Func`2 descendIntoChildren) in C:\Roslyn\Main\Open\src\Compilers\Core\Portable\Syntax\SyntaxNode.Iterators.cs:line 50
   at Microsoft.CodeAnalysis.SyntaxNode.<DescendantNodesOnly>d__157.MoveNext() in C:\Roslyn\Main\Open\src\Compilers\Core\Portable\Syntax\SyntaxNode.Iterators.cs:line 378
   at Microsoft.CodeAnalysis.CSharp.Diagnostics.SimplifyTypeNames.CSharpSimplifyTypeNamesDiagnosticAnalyzer.AnalyzeNode(SyntaxNodeAnalysisContext context) in C:\Roslyn\Main\Open\src\Features\CSharp\Diagnostics\Analyzers\CSharpSimplifyTypeNamesDiagnosticAnalyzer.cs:line 58
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass32_0`1.<ExecuteSyntaxNodeAction>b__1() in C:\Roslyn\Main\Open\src\Compilers\Core\AnalyzerDriver\AnalyzerExecutor.cs:line 298
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows(DiagnosticAnalyzer analyzer, Action analyze, Action`3 onAnalyzerException, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Compilers\Core\AnalyzerDriver\AnalyzerExecutor.cs:line 501
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows(DiagnosticAnalyzer analyzer, Action analyze) in C:\Roslyn\Main\Open\src\Compilers\Core\AnalyzerDriver\AnalyzerExecutor.cs:line 489
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteSyntaxNodeAction[TLanguageKindEnum](SyntaxNodeAnalyzerAction`1 syntaxNodeAction, SyntaxNode node, SemanticModel semanticModel) in C:\Roslyn\Main\Open\src\Compilers\Core\AnalyzerDriver\AnalyzerExecutor.cs:line 298
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteSyntaxNodeActions[TLanguageKindEnum](AnalyzerActions actions, IEnumerable`1 nodes, SemanticModel semanticModel, Func`2 getKind) in C:\Roslyn\Main\Open\src\Compilers\Core\AnalyzerDriver\AnalyzerExecutor.cs:line 284
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.AbstractSyntaxNodeAnalyzerService`1.ExecuteSyntaxNodeActions(AnalyzerActions actions, IEnumerable`1 descendantNodes, SemanticModel semanticModel, AnalyzerExecutor analyzerExecutor) in C:\Roslyn\Main\Open\src\Features\Core\Diagnostics\EngineV1\AbstractSyntaxNodeAnalyzerService.cs:line 25
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticAnalyzerDriver.<GetSemanticDiagnosticsAsync>d__40.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Diagnostics\EngineV1\DiagnosticAnalyzerDriver.cs:line 378
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticAnalyzerDriver.GetSemanticDiagnosticsAsync(DiagnosticAnalyzer analyzer)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.<GetSemanticDiagnosticsAsync>d__81.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer.cs:line 828
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.GetSemanticDiagnosticsAsync(DiagnosticAnalyzerDriver userDiagnosticDriver, DiagnosticAnalyzer analyzer)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.AnalyzerExecutor.<GetDocumentAnalysisDataAsync>d__3.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer.AnalyzerExecutor.cs:line 70
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.AnalyzerExecutor.GetDocumentAnalysisDataAsync(DiagnosticAnalyzerDriver analyzerDriver, StateSet stateSet, VersionArgument versions)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.<AnalyzeDocumentAsync>d__52.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer.cs:line 278
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.AnalyzeDocumentAsync(Document document, VersionArgument versions, ImmutableHashSet`1 diagnosticIds, Boolean skipClosedFileChecks, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.<AnalyzeDocumentAsync>d__50.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer.cs:line 194
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.AnalyzeDocumentAsync(Document document, SyntaxNode bodyOpt, ImmutableHashSet`1 diagnosticIds, Boolean skipClosedFileChecks, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.<AnalyzeDocumentAsync>d__49.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer.cs:line 175
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.AnalyzeDocumentAsync(Document document, SyntaxNode bodyOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.IncrementalAnalyzerDelegatee.AnalyzeDocumentAsync(Document document, SyntaxNode bodyOpt, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Features\Core\Diagnostics\DiagnosticAnalyzerService_IncrementalAnalyzer.cs:line 86
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<>c.<ProcessDocumentAnalyzersAsync>b__26_1(IIncrementalAnalyzer a, Document d, CancellationToken c) in C:\Roslyn\Main\Open\src\Features\Core\SolutionCrawler\WorkCoordinator.IncrementalAnalyzerProcessor.cs:line 175
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<>c__DisplayClass27_1`1.<<RunAnalyzersAsync>b__0>d.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\SolutionCrawler\WorkCoordinator.IncrementalAnalyzerProcessor.cs:line 197
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<>c__DisplayClass27_1`1.<RunAnalyzersAsync>b__0(T v, CancellationToken c)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<GetOrDefaultAsync>d__29`2.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\SolutionCrawler\WorkCoordinator.IncrementalAnalyzerProcessor.cs:line 240
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.GetOrDefaultAsync[TData,TResult](TData value, Func`3 funcAsync, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<RunAnalyzersAsync>d__27`1.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\SolutionCrawler\WorkCoordinator.IncrementalAnalyzerProcessor.cs:line 195
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.RunAnalyzersAsync[T](ImmutableArray`1 analyzers, T value, Func`4 runnerAsync, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<ProcessDocumentAnalyzersAsync>d__26.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\SolutionCrawler\WorkCoordinator.IncrementalAnalyzerProcessor.cs:line 175
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<RunAnalyzersAsync>d__27`1.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\SolutionCrawler\WorkCoordinator.IncrementalAnalyzerProcessor.cs:line 201
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<GetOrDefaultAsync>d__29`2.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\SolutionCrawler\WorkCoordinator.IncrementalAnalyzerProcessor.cs:line 255
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<>c__DisplayClass27_1`1.<<RunAnalyzersAsync>b__0>d.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\SolutionCrawler\WorkCoordinator.IncrementalAnalyzerProcessor.cs:line 199
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.<AnalyzeSyntaxAsync>d__47.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer.cs:line 122
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.<AnalyzeSyntaxAsync>d__48.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer.cs:line 171
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.<ShouldRunAnalyzerForStateTypeAsync>d__62.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer.cs:line 486
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.<ShouldRunAnalyzerForStateTypeAsync>d__63.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer.cs:line 512
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Microsoft.CodeAnalysis.Shared.Extensions.DiagnosticAnalyzerExtensions.<SupportsSyntaxDiagnosticAnalysisAsync>d__2.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Shared\Extensions\DiagnosticAnalyzerExtensions.cs:line 84
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Microsoft.CodeAnalysis.Shared.Extensions.DiagnosticAnalyzerExtensions.<GetDiagnosticAnalyzerCategoryAsync>d__0.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Shared\Extensions\DiagnosticAnalyzerExtensions.cs:line 69
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticAnalyzerDriver.<GetAnalyzerActionsAsync>d__37.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Diagnostics\EngineV1\DiagnosticAnalyzerDriver.cs:line 302
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticAnalyzerDriver.<GetAnalyzerActionsAsync>d__39.MoveNext() in C:\Roslyn\Main\Open\src\Features\Core\Diagnostics\EngineV1\DiagnosticAnalyzerDriver.cs:line 321
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.<GetAnalyzerActionsAsync>d__8.MoveNext() in C:\Roslyn\Main\Open\src\Compilers\Core\AnalyzerDriver\AnalyzerManager.cs:line 149
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.<GetCompilationAnalysisScopeAsync>d__5.MoveNext() in C:\Roslyn\Main\Open\src\Compilers\Core\AnalyzerDriver\AnalyzerManager.cs:line 95
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

StackTrace: 
```

And then the crashing exception:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Immutable.ImmutableArray`1.Builder.get_Item(Int32 index)
   at Microsoft.CodeAnalysis.ArrayBuilder`1.get_Item(Int32 index) in C:\Roslyn\Main\Open\src\Compilers\Core\SharedCollections\ArrayBuilder.cs:line 83
   at Microsoft.CodeAnalysis.CSharp.AnalyzedArguments.Argument(Int32 i) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\AnalyzedArguments.cs:line 37
   at Microsoft.CodeAnalysis.CSharp.OverloadResolution.IsApplicable(Symbol candidate, EffectiveParameters parameters, AnalyzedArguments arguments, ImmutableArray`1 argsToParameters, Boolean isVararg, Boolean hasAnyRefOmittedArgument, Boolean ignoreOpenTypes, HashSet`1& useSiteDiagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 2594
   at Microsoft.CodeAnalysis.CSharp.OverloadResolution.IsApplicable[TMember](TMember member, TMember leastOverriddenMember, ArrayBuilder`1 typeArgumentsBuilder, AnalyzedArguments arguments, EffectiveParameters originalEffectiveParameters, EffectiveParameters constructedEffectiveParameters, ImmutableArray`1 argsToParamsMap, Boolean hasAnyRefOmittedArgument, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 2504
   at Microsoft.CodeAnalysis.CSharp.OverloadResolution.IsMemberApplicableInNormalForm[TMember](TMember member, TMember leastOverriddenMember, ArrayBuilder`1 typeArguments, AnalyzedArguments arguments, Boolean isMethodGroupConversion, Boolean allowRefOmittedArguments, Boolean inferWithDynamic, HashSet`1& useSiteDiagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 2325
   at Microsoft.CodeAnalysis.CSharp.OverloadResolution.AddMemberToCandidateSet[TMember](TMember member, ArrayBuilder`1 results, ArrayBuilder`1 members, ArrayBuilder`1 typeArguments, AnalyzedArguments arguments, Boolean completeResults, Boolean isMethodGroupConversion, Boolean allowRefOmittedArguments, Dictionary`2 containingTypeMapOpt, Boolean inferWithDynamic, HashSet`1& useSiteDiagnostics, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 495
   at Microsoft.CodeAnalysis.CSharp.OverloadResolution.PerformMemberOverloadResolution[TMember](ArrayBuilder`1 results, ArrayBuilder`1 members, ArrayBuilder`1 typeArguments, AnalyzedArguments arguments, Boolean completeResults, Boolean isMethodGroupConversion, Boolean allowRefOmittedArguments, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 233
   at Microsoft.CodeAnalysis.CSharp.OverloadResolution.MethodOrPropertyOverloadResolution[TMember](ArrayBuilder`1 members, ArrayBuilder`1 typeArguments, AnalyzedArguments arguments, OverloadResolutionResult`1 result, Boolean isMethodGroupConversion, Boolean allowRefOmittedArguments, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 136
   at Microsoft.CodeAnalysis.CSharp.OverloadResolution.MethodInvocationOverloadResolution(ArrayBuilder`1 methods, ArrayBuilder`1 typeArguments, AnalyzedArguments arguments, OverloadResolutionResult`1 result, HashSet`1& useSiteDiagnostics, Boolean isMethodGroupConversion, Boolean allowRefOmittedArguments, Boolean inferWithDynamic, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 101
   at Microsoft.CodeAnalysis.CSharp.Binder.ResolveDefaultMethodGroup(BoundMethodGroup node, AnalyzedArguments analyzedArguments, Boolean isMethodGroupConversion, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 6254
   at Microsoft.CodeAnalysis.CSharp.Binder.ResolveMethodGroupInternal(BoundMethodGroup methodGroup, CSharpSyntaxNode expression, String methodName, AnalyzedArguments analyzedArguments, Boolean isMethodGroupConversion, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 6147
   at Microsoft.CodeAnalysis.CSharp.Binder.ResolveMethodGroup(BoundMethodGroup node, CSharpSyntaxNode expression, String methodName, AnalyzedArguments analyzedArguments, Boolean isMethodGroupConversion, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 6122
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodGroupInvocation(CSharpSyntaxNode syntax, CSharpSyntaxNode expression, String methodName, BoundMethodGroup methodGroup, AnalyzedArguments analyzedArguments, DiagnosticBag diagnostics, CSharpSyntaxNode queryClause, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Invocation.cs:line 452
   at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(CSharpSyntaxNode node, CSharpSyntaxNode expression, String methodName, BoundExpression boundExpression, AnalyzedArguments analyzedArguments, DiagnosticBag diagnostics, CSharpSyntaxNode queryClause, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Invocation.cs:line 222
   at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(InvocationExpressionSyntax node, DiagnosticBag diagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Invocation.cs:line 165
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 408
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 353
   at Microsoft.CodeAnalysis.CSharp.Binder.BindValue(ExpressionSyntax node, DiagnosticBag diagnostics, BindValueKind valueKind) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 288
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(CSharpSyntaxNode node, ExpressionSyntax syntax, Boolean allowsAnyExpression, DiagnosticBag diagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 418
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(ExpressionStatementSyntax node, DiagnosticBag diagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 411
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 49
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.IncrementalBinder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1639
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.Bind(Binder binder, CSharpSyntaxNode node, DiagnosticBag diagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 1996
   at Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.Bind(Binder binder, CSharpSyntaxNode node, DiagnosticBag diagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MethodBodySemanticModel.cs:line 48
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1397
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode(CSharpSyntaxNode node) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 369
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node, CSharpSyntaxNode& bindableNode, BoundNode& lowestBoundNode, BoundNode& highestBoundNode, BoundNode& boundParent) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 896
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 775
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\SyntaxTreeSemanticModel.cs:line 173
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 504
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSymbolInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\CSharpExtensions.cs:line 443
   at Microsoft.CodeAnalysis.CSharp.Extensions.ExpressionSyntaxExtensions.TryReplaceWithAlias(ExpressionSyntax node, SemanticModel semanticModel, Boolean preferAliasToQualifiedName, CancellationToken cancellationToken, IAliasSymbol& aliasReplacement) in C:\Roslyn\Main\Open\src\Workspaces\CSharp\Portable\Extensions\ExpressionSyntaxExtensions.cs:line 868
   at Microsoft.CodeAnalysis.CSharp.Extensions.ExpressionSyntaxExtensions.TryReduce(MemberAccessExpressionSyntax memberAccess, SemanticModel semanticModel, TypeSyntax& replacementNode, TextSpan& issueSpan, OptionSet optionSet, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Workspaces\CSharp\Portable\Extensions\ExpressionSyntaxExtensions.cs:line 722
   at Microsoft.CodeAnalysis.CSharp.Extensions.ExpressionSyntaxExtensions.TryReduceExplicitName(ExpressionSyntax expression, SemanticModel semanticModel, TypeSyntax& replacementNode, TextSpan& issueSpan, OptionSet optionSet, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Workspaces\CSharp\Portable\Extensions\ExpressionSyntaxExtensions.cs:line 665
   at Microsoft.CodeAnalysis.CSharp.Extensions.ExpressionSyntaxExtensions.TryReduceOrSimplifyExplicitName(ExpressionSyntax expression, SemanticModel semanticModel, ExpressionSyntax& replacementNode, TextSpan& issueSpan, OptionSet optionSet, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Workspaces\CSharp\Portable\Extensions\ExpressionSyntaxExtensions.cs:line 637
   at Microsoft.CodeAnalysis.CSharp.Diagnostics.SimplifyTypeNames.CSharpSimplifyTypeNamesDiagnosticAnalyzer.CanSimplifyTypeNameExpression(SemanticModel model, SyntaxNode node, OptionSet optionSet, TextSpan& issueSpan, String& diagnosticId, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Features\CSharp\Diagnostics\Analyzers\CSharpSimplifyTypeNamesDiagnosticAnalyzer.cs:line 132
   at Microsoft.CodeAnalysis.CSharp.Diagnostics.SimplifyTypeNames.CSharpSimplifyTypeNamesDiagnosticAnalyzer.CanSimplifyTypeNameExpressionCore(SemanticModel model, SyntaxNode node, OptionSet optionSet, TextSpan& issueSpan, String& diagnosticId, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Features\CSharp\Diagnostics\Analyzers\CSharpSimplifyTypeNamesDiagnosticAnalyzer.cs:line 93
   at Microsoft.CodeAnalysis.Diagnostics.SimplifyTypeNames.SimplifyTypeNamesDiagnosticAnalyzerBase`1.TrySimplifyTypeNameExpression(SemanticModel model, SyntaxNode node, AnalyzerOptions analyzerOptions, Diagnostic& diagnostic, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Features\Core\Diagnostics\Analyzers\SimplifyTypeNamesDiagnosticAnalyzerBase.cs:line 83
   at Microsoft.CodeAnalysis.CSharp.Diagnostics.SimplifyTypeNames.CSharpSimplifyTypeNamesDiagnosticAnalyzer.<>c__DisplayClass2_0.<AnalyzeNode>b__1(SyntaxNode n) in C:\Roslyn\Main\Open\src\Features\CSharp\Diagnostics\Analyzers\CSharpSimplifyTypeNamesDiagnosticAnalyzer.cs:line 47
   at Microsoft.CodeAnalysis.SyntaxNode.ChildSyntaxListEnumeratorStack..ctor(SyntaxNode startingNode, Func`2 descendIntoChildren) in C:\Roslyn\Main\Open\src\Compilers\Core\Portable\Syntax\SyntaxNode.Iterators.cs:line 50
   at Microsoft.CodeAnalysis.SyntaxNode.<DescendantNodesOnly>d__157.MoveNext() in C:\Roslyn\Main\Open\src\Compilers\Core\Portable\Syntax\SyntaxNode.Iterators.cs:line 378
   at Microsoft.CodeAnalysis.CSharp.Diagnostics.SimplifyTypeNames.CSharpSimplifyTypeNamesDiagnosticAnalyzer.AnalyzeNode(SyntaxNodeAnalysisContext context) in C:\Roslyn\Main\Open\src\Features\CSharp\Diagnostics\Analyzers\CSharpSimplifyTypeNamesDiagnosticAnalyzer.cs:line 58
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass32_0`1.<ExecuteSyntaxNodeAction>b__1() in C:\Roslyn\Main\Open\src\Compilers\Core\AnalyzerDriver\AnalyzerExecutor.cs:line 298
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows(DiagnosticAnalyzer analyzer, Action analyze, Action`3 onAnalyzerException, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Compilers\Core\AnalyzerDriver\AnalyzerExecutor.cs:line 501
5/10/2015 4:31:38 PM
Source: First chance exception: System.Collections.Immutable
StackTrace:    at System.Collections.Immutable.ImmutableArray`1.Builder.get_Item(Int32 index)
   at Microsoft.CodeAnalysis.ArrayBuilder`1.get_Item(Int32 index) in C:\Roslyn\Main\Open\src\Compilers\Core\SharedCollections\ArrayBuilder.cs:line 83
   at Microsoft.CodeAnalysis.CSharp.AnalyzedArguments.Argument(Int32 i) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\AnalyzedArguments.cs:line 37
   at Microsoft.CodeAnalysis.CSharp.OverloadResolution.IsApplicable(Symbol candidate, EffectiveParameters parameters, AnalyzedArguments arguments, ImmutableArray`1 argsToParameters, Boolean isVararg, Boolean hasAnyRefOmittedArgument, Boolean ignoreOpenTypes, HashSet`1& useSiteDiagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 2594
   at Microsoft.CodeAnalysis.CSharp.OverloadResolution.IsApplicable[TMember](TMember member, TMember leastOverriddenMember, ArrayBuilder`1 typeArgumentsBuilder, AnalyzedArguments arguments, EffectiveParameters originalEffectiveParameters, EffectiveParameters constructedEffectiveParameters, ImmutableArray`1 argsToParamsMap, Boolean hasAnyRefOmittedArgument, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 2504
   at Microsoft.CodeAnalysis.CSharp.OverloadResolution.IsMemberApplicableInNormalForm[TMember](TMember member, TMember leastOverriddenMember, ArrayBuilder`1 typeArguments, AnalyzedArguments arguments, Boolean isMethodGroupConversion, Boolean allowRefOmittedArguments, Boolean inferWithDynamic, HashSet`1& useSiteDiagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 2325
   at Microsoft.CodeAnalysis.CSharp.OverloadResolution.AddMemberToCandidateSet[TMember](TMember member, ArrayBuilder`1 results, ArrayBuilder`1 members, ArrayBuilder`1 typeArguments, AnalyzedArguments arguments, Boolean completeResults, Boolean isMethodGroupConversion, Boolean allowRefOmittedArguments, Dictionary`2 containingTypeMapOpt, Boolean inferWithDynamic, HashSet`1& useSiteDiagnostics, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 495
   at Microsoft.CodeAnalysis.CSharp.OverloadResolution.PerformMemberOverloadResolution[TMember](ArrayBuilder`1 results, ArrayBuilder`1 members, ArrayBuilder`1 typeArguments, AnalyzedArguments arguments, Boolean completeResults, Boolean isMethodGroupConversion, Boolean allowRefOmittedArguments, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 233
   at Microsoft.CodeAnalysis.CSharp.OverloadResolution.MethodOrPropertyOverloadResolution[TMember](ArrayBuilder`1 members, ArrayBuilder`1 typeArguments, AnalyzedArguments arguments, OverloadResolutionResult`1 result, Boolean isMethodGroupConversion, Boolean allowRefOmittedArguments, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 136
   at Microsoft.CodeAnalysis.CSharp.OverloadResolution.MethodInvocationOverloadResolution(ArrayBuilder`1 methods, ArrayBuilder`1 typeArguments, AnalyzedArguments arguments, OverloadResolutionResult`1 result, HashSet`1& useSiteDiagnostics, Boolean isMethodGroupConversion, Boolean allowRefOmittedArguments, Boolean inferWithDynamic, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Semantics\OverloadResolution\OverloadResolution.cs:line 101
   at Microsoft.CodeAnalysis.CSharp.Binder.ResolveDefaultMethodGroup(BoundMethodGroup node, AnalyzedArguments analyzedArguments, Boolean isMethodGroupConversion, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 6254
   at Microsoft.CodeAnalysis.CSharp.Binder.ResolveMethodGroupInternal(BoundMethodGroup methodGroup, CSharpSyntaxNode expression, String methodName, AnalyzedArguments analyzedArguments, Boolean isMethodGroupConversion, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 6147
   at Microsoft.CodeAnalysis.CSharp.Binder.ResolveMethodGroup(BoundMethodGroup node, CSharpSyntaxNode expression, String methodName, AnalyzedArguments analyzedArguments, Boolean isMethodGroupConversion, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 6122
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodGroupInvocation(CSharpSyntaxNode syntax, CSharpSyntaxNode expression, String methodName, BoundMethodGroup methodGroup, AnalyzedArguments analyzedArguments, DiagnosticBag diagnostics, CSharpSyntaxNode queryClause, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Invocation.cs:line 452
   at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(CSharpSyntaxNode node, CSharpSyntaxNode expression, String methodName, BoundExpression boundExpression, AnalyzedArguments analyzedArguments, DiagnosticBag diagnostics, CSharpSyntaxNode queryClause, Boolean allowUnexpandedForm) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Invocation.cs:line 222
   at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(InvocationExpressionSyntax node, DiagnosticBag diagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Invocation.cs:line 165
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 408
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 353
   at Microsoft.CodeAnalysis.CSharp.Binder.BindValue(ExpressionSyntax node, DiagnosticBag diagnostics, BindValueKind valueKind) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Expressions.cs:line 288
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(CSharpSyntaxNode node, ExpressionSyntax syntax, Boolean allowsAnyExpression, DiagnosticBag diagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 418
   at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(ExpressionStatementSyntax node, DiagnosticBag diagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 411
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 49
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.IncrementalBinder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1639
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.Bind(Binder binder, CSharpSyntaxNode node, DiagnosticBag diagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 1996
   at Microsoft.CodeAnalysis.CSharp.MethodBodySemanticModel.Bind(Binder binder, CSharpSyntaxNode node, DiagnosticBag diagnostics) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MethodBodySemanticModel.cs:line 48
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1397
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLowerBoundNode(CSharpSyntaxNode node) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 369
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetBoundNodes(CSharpSyntaxNode node, CSharpSyntaxNode& bindableNode, BoundNode& lowestBoundNode, BoundNode& highestBoundNode, BoundNode& boundParent) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 896
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 775
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetSymbolInfoWorker(CSharpSyntaxNode node, SymbolInfoOptions options, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\SyntaxTreeSemanticModel.cs:line 173
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetSymbolInfo(ExpressionSyntax expression, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 504
   at Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetSymbolInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\CSharpExtensions.cs:line 443
   at Microsoft.CodeAnalysis.CSharp.Extensions.ExpressionSyntaxExtensions.TryReplaceWithAlias(ExpressionSyntax node, SemanticModel semanticModel, Boolean preferAliasToQualifiedName, CancellationToken cancellationToken, IAliasSymbol& aliasReplacement) in C:\Roslyn\Main\Open\src\Workspaces\CSharp\Portable\Extensions\ExpressionSyntaxExtensions.cs:line 868
   at Microsoft.CodeAnalysis.CSharp.Extensions.ExpressionSyntaxExtensions.TryReduce(MemberAccessExpressionSyntax memberAccess, SemanticModel semanticModel, TypeSyntax& replacementNode, TextSpan& issueSpan, OptionSet optionSet, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Workspaces\CSharp\Portable\Extensions\ExpressionSyntaxExtensions.cs:line 722
   at Microsoft.CodeAnalysis.CSharp.Extensions.ExpressionSyntaxExtensions.TryReduceExplicitName(ExpressionSyntax expression, SemanticModel semanticModel, TypeSyntax& replacementNode, TextSpan& issueSpan, OptionSet optionSet, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Workspaces\CSharp\Portable\Extensions\ExpressionSyntaxExtensions.cs:line 665
   at Microsoft.CodeAnalysis.CSharp.Extensions.ExpressionSyntaxExtensions.TryReduceOrSimplifyExplicitName(ExpressionSyntax expression, SemanticModel semanticModel, ExpressionSyntax& replacementNode, TextSpan& issueSpan, OptionSet optionSet, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Workspaces\CSharp\Portable\Extensions\ExpressionSyntaxExtensions.cs:line 637
   at Microsoft.CodeAnalysis.CSharp.Diagnostics.SimplifyTypeNames.CSharpSimplifyTypeNamesDiagnosticAnalyzer.CanSimplifyTypeNameExpression(SemanticModel model, SyntaxNode node, OptionSet optionSet, TextSpan& issueSpan, String& diagnosticId, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Features\CSharp\Diagnostics\Analyzers\CSharpSimplifyTypeNamesDiagnosticAnalyzer.cs:line 132
   at Microsoft.CodeAnalysis.CSharp.Diagnostics.SimplifyTypeNames.CSharpSimplifyTypeNamesDiagnosticAnalyzer.CanSimplifyTypeNameExpressionCore(SemanticModel model, SyntaxNode node, OptionSet optionSet, TextSpan& issueSpan, String& diagnosticId, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Features\CSharp\Diagnostics\Analyzers\CSharpSimplifyTypeNamesDiagnosticAnalyzer.cs:line 93
   at Microsoft.CodeAnalysis.Diagnostics.SimplifyTypeNames.SimplifyTypeNamesDiagnosticAnalyzerBase`1.TrySimplifyTypeNameExpression(SemanticModel model, SyntaxNode node, AnalyzerOptions analyzerOptions, Diagnostic& diagnostic, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Features\Core\Diagnostics\Analyzers\SimplifyTypeNamesDiagnosticAnalyzerBase.cs:line 83
   at Microsoft.CodeAnalysis.CSharp.Diagnostics.SimplifyTypeNames.CSharpSimplifyTypeNamesDiagnosticAnalyzer.<>c__DisplayClass2_0.<AnalyzeNode>b__1(SyntaxNode n) in C:\Roslyn\Main\Open\src\Features\CSharp\Diagnostics\Analyzers\CSharpSimplifyTypeNamesDiagnosticAnalyzer.cs:line 47
   at Microsoft.CodeAnalysis.SyntaxNode.ChildSyntaxListEnumeratorStack..ctor(SyntaxNode startingNode, Func`2 descendIntoChildren) in C:\Roslyn\Main\Open\src\Compilers\Core\Portable\Syntax\SyntaxNode.Iterators.cs:line 50
   at Microsoft.CodeAnalysis.SyntaxNode.<DescendantNodesOnly>d__157.MoveNext() in C:\Roslyn\Main\Open\src\Compilers\Core\Portable\Syntax\SyntaxNode.Iterators.cs:line 378
   at Microsoft.CodeAnalysis.CSharp.Diagnostics.SimplifyTypeNames.CSharpSimplifyTypeNamesDiagnosticAnalyzer.AnalyzeNode(SyntaxNodeAnalysisContext context) in C:\Roslyn\Main\Open\src\Features\CSharp\Diagnostics\Analyzers\CSharpSimplifyTypeNamesDiagnosticAnalyzer.cs:line 58
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass32_0`1.<ExecuteSyntaxNodeAction>b__1() in C:\Roslyn\Main\Open\src\Compilers\Core\AnalyzerDriver\AnalyzerExecutor.cs:line 298
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows(DiagnosticAnalyzer analyzer, Action analyze, Action`3 onAnalyzerException, CancellationToken cancellationToken) in C:\Roslyn\Main\Open\src\Compilers\Core\AnalyzerDriver\AnalyzerExecutor.cs:line 501
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #2631

This repairs the compiler crash reported in #2631. The problem was we were not preventing an __arglist method from being considered a candidate when the argument list uses keyword notation. That ain't never gonna work because there would be no way to specify the __arglist parameter (it has no name).

@VSadov @AlekseyTs @agocke Please review.

### CODE REVIEW

**Comment by VSadov** [comment]
LGTM

File: src/Compilers/CSharp/Test/Semantic/Semantics/OverloadResolutionTests.cs [hunk 1]
```diff
@@ -8078,5 +8078,26 @@ static void Main()
...
+    static void M(object x, params object[] args) { }
+    static void Main(string[] args)
+    {
+        M(x: 1, y: 2, z: 3);
+    }
+}";
+            var compilation = CreateCompilationWithMscorlib(source);
+            compilation.VerifyDiagnostics();
+        }
+
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/OverloadResolutionTests.cs]: Do we have any tests verifying the behavior when we are forced to bind to an overload that has an `__arglist` parameter?  Say if only the `__arglist` overload was present in this case?

Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/OverloadResolutionTests.cs]: Yes, we have plenty of end-to-end tests for `__arglist`, including interactions with async, NoPia, and other features.

**Comment by jaredpar** [comment]
LGTM
