### PR TITLE
fix EmitDefaultValue to not attempt to emit decimal constants.

### LINKED ISSUE #15956: Null-coalescing operator followed by throw causes compilation to fail when used with decimal.
**Version Used**:
```
Microsoft Visual Studio Professional 2017 RC
Version 15.0.26014.0 D15REL
Microsoft .NET Framework
Version 4.6.02006
```

**Steps to Reproduce**:

1. Create a new C# Blank App (Universal Windows)
2. Paste the following App.xaml.cs above the App class.
```
public class ITest
{
    public decimal Test()
        => 1m;
}

public class TestClass
{
    public void Test(ITest test)
    {
        var result = test?.Test() ?? throw new Exception();
    }
}
```
3. Compile.

**Expected Behavior**:
The project compiles.

**Actual Behavior**:
The build fails during XamlPreCompile with:
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.CSharp.CurrentVersion.targets(246,9): error MSB6006: "csc.exe" exited with code -2146232797.`

**Notes**:
Changing `decimal` to, say, `int` fixes the problem, as does replacing the `throw` expression with a constant, e.g., `2.3m`.

### PR DESCRIPTION
**Pull request by TyOverby**
closes #15956

### CODE REVIEW

**Comment by TyOverby** [comment]
@dotnet/roslyn-compiler 
Please review!

**Comment by TyOverby** [comment]
@jaredpar Which branch should I be merging this into?

**Comment by jaredpar** [comment]
master

File: src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs [hunk 1]
```diff
@@ -2624,7 +2624,7 @@ private void EmitDefaultValue(TypeSymbol type, bool used, SyntaxNode syntaxNode)
             if (used)
             {
                 // default type parameter values must be emitted as 'initobj' regardless of constraints
-                if (!type.IsTypeParameter())
+                if (!type.IsTypeParameter() && type.SpecialType != SpecialType.System_Decimal)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs]: I didn't understand what is uniquely special about `Decimal`. Doesn't it have a default value? If yes, is it the only special type without a default value?

**Comment by AlekseyTs** [comment]
@TyOverby In order to merge to master, an ask mode template must be filled out and a sign-off from @srivatsn (as the final step) must be obtained.

File: src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs]: >if (!type.IsTypeParameter() && type.SpecialType != SpecialType.System_Decimal) [](start = 16, length = 78)

Please verify that VB doesn't have similar logic in its codegen.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 2]
```diff
@@ -3526,6 +3526,28 @@ public static void Main()
...
+public class TestClass
+{
+    public void Test(ITest test)
+    {
+        var result = test?.Test() ?? throw new Exception();
+    }
+}";
+            var compilation = CreateCompilationWithMscorlib(source, options: TestOptions.DebugDll);
+            compilation.VerifyDiagnostics();
+            compilation.VerifyEmitDiagnostics();
```
Comment (VSadov) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: IL validation for "public void Test" would be useful here

Comment (VSadov) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Also test "Release" as well. 
Since this is an Emit bug, need to make sure optimized code is ok.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: >compilation.VerifyEmitDiagnostics(); [](start = 12, length = 36)

Please adjust the test scenario so that it can be executed and call ```public void Test(ITest test)``` with null and not null input, observe expected behavior of the program.

File: src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs (hunk 1 above)
Comment (VSadov) [inline src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs]: The Decimal is a constant, but not an IL constant. From IL prospective it is just a struct, so must be emitted via initobj.
Normally this codepath would not see Decimal, because they would be rewritten into bound literal/constants and codegen knows how to deal with decimal there.

New code that emits Throw expressions emit, however, appears to call EmitDefaultValue directly to put an unreachable emit of a default value as a cute way to balance stack.

By itself that is ok, but it calls this method with any kind of type - IL constants or not, thus causing this issue.

Comment (jcouv) [inline src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs]: Thanks. Is Decimal the only type in this situation (a C# constant, but not an IL constant)?

Comment (VSadov) [inline src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs]: Another type like Decimal is "DateTime". Please add a similar test for that. 
C# does not allow DateTime constants so GetDefaultValue will not produce a constant for it (in VB it would), and that saves us here.
However - just in case if anything changes we need a similar test with DateTime.

Comment (TyOverby) [inline src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs]: I could be mistaken, but I don't think we can load decimal constants the same way that we load any other constants.

For example, the IL for `decimal x = 4.1m;` is 

```
        IL_0003: ldc.i4.s 41          // Push num onto the stack as int32, short form
        IL_0005: ldc.i4.0             // Push 0 onto the stack as int32
        IL_0006: ldc.i4.0             // Push 0 onto the stack as int32
        IL_0007: ldc.i4.0             // Push 0 onto the stack as int32
        IL_0008: ldc.i4.1             // Push 1 onto the stack as int32
        IL_0009: call instance void [mscorlib]System.Decimal::.ctor(int32, int32, int32, bool, uint8) // Call method indicated on the stack with arguments

```

Comment (TyOverby) [inline src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs]: It appears that VB does weird things with regards to emitting Decimal and DateTime constants.

http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/CodeGen/EmitExpression.vb,39

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs (hunk 2 above)
Comment (TyOverby) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Done and Done

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 3]
```diff
@@ -3526,6 +3526,65 @@ public static void Main()
...
+
+            // RELEASE
+            compilation = CreateCompilationWithMscorlib(source, options: TestOptions.ReleaseDll);
+            compilation.VerifyDiagnostics();
+            compilation.VerifyEmitDiagnostics();
+
+            verifier = CompileAndVerify(compilation);
+            verifier.VerifyIL("TestClass.Test", @"{
+    // Code size       17 (0x11)
+    .maxstack  1
```
Comment (VSadov) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: nice! unreachable temps are optimized away in Release. I wanted to confirm that.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 4]
```diff
@@ -3526,6 +3526,65 @@ public static void Main()
...
+    IL_0000:  ldarg.1
+    IL_0001:  brtrue.s   IL_0009
+    IL_0003:  newobj     ""System.Exception..ctor()""
+    IL_0008:  throw
+    IL_0009:  ldarg.1
+    IL_000a:  call       ""decimal ITest.Test()""
+    IL_000f:  pop
+    IL_0010:  ret
+}");
+        }
```
Comment (VSadov) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Can you add a similar test for DateTime?

Comment (VSadov) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: I.E. - roughly same code, but DateTime instead of Decimal.

Comment (TyOverby) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: ^ Done

**Comment by VSadov** [comment]
LGTM

**Comment by AlekseyTs** [comment]
> It appears that VB does weird things with regards to emitting Decimal and DateTime constants.

I am not sure how to interpret this. Does that mean that VB possibly has similar issue? Or did you confirm that it doesn't? Could you elaborate please?

**Comment by AlekseyTs** [comment]
>                 EmitInitObj(type, true, syntaxNode);

It doesn't look like it can be observed in IL that this line of code is reachable for decimal type. Would it be possible to come up with a scenario, for which it will be observable in IL? 

---
Refers to: src/Compilers/CSharp/Portable/CodeGen/EmitExpression.cs:2637 in a31df04. [](commit_id = a31df047dbfcd4bcf2a635fe66188535bcf80d4e, deletion_comment = False)

**Comment by TyOverby** [comment]
@AlekseyTs VB handles DateTime and Decimal specially.


> Would it be possible to come up with a scenario, for which it will be observable in IL?


I'm unsure how to do this.

**Comment by AlekseyTs** [comment]
@TyOverby Let's go ahead with completing the sign-off process (https://github.com/dotnet/roslyn/pull/16140#issuecomment-269683840) and merging the fix. Let's followup on the additional testing and VB separately.

**Comment by TyOverby** [comment]
# Ask Mode Template

## Customer scenario

The programmer uses a throw expression on the RHS of a `??` operator where the LHS value is a `decimal`.

## Bugs this fixes:

#15956

## Workarounds, if any

None known.

## Risk

Low.  This PR mainly adds extra handling for an edge-case.

## Performance impact

Low.  (No extra allocations in a scenario that didn't previously crash the compiler).  No extra codepaths taken.

## Is this a regression from a previous update?

No, this likely could have been hit prior to 

## Root cause analysis:

When implemented, the throw-expression emitter spits out a default value for whatever it is supposed to be replacing.
While we've guarded against Decimal in other locations, it was left out here.  This fix adds knowledge of Decimal to emit-default-value in order to hopefully catch this error for this throw-expression and other cases that use emit-default-value.

## How was the bug found?

Customer reported it on github.

**Comment by TyOverby** [comment]
@srivatsn 

Ask mode approval?

**Comment by AlekseyTs** [comment]
@TyOverby Please don't forget to squash commits before merging.
