### PR TITLE
Fix IInlineRenameInfo.GetFinalSymbolName not being respected

### LINKED ISSUE #16460: IInlineRenameInfo.GetFinalSymbolName does not work
VS 2017 RC2

Having this implementation:

```fsharp
interface IInlineRenameInfo with
    member __.CanRename = true
    member __.LocalizedErrorMessage = null
    member __.TriggerSpan = triggerSpan
    member __.HasOverloads = false
    member __.ForceRenameOverloads = true
    member __.DisplayName = symbolUse.Symbol.DisplayName
    member __.FullDisplayName = try symbolUse.Symbol.FullName with _ -> symbolUse.Symbol.DisplayName
    member __.Glyph = Glyph.MethodPublic
        
    member __.GetFinalSymbolName replacementText = 
        let res = replacementText + "_FOOOOO"
        res
```

I expect that if user types new name `Bar` than renaming should finishes with replacing all symbol occurrences with `Bar_FOOOOO`, but it's not the case. If I don't check "Preview changes", then `GetFinalSymbolName` is not called at all. If I check it, then it's called and the proper new name is shown, but only in the title:

image

### PR DESCRIPTION
**Pull request by saul**
**Customer scenario**

IInlineRenameInfo.GetFinalSymbolName is not respected - the result of it is only used in a dialog window for previewing renaming. The result of the function is currently not used for determining what the final symbol name should be. This PR fixes this issue.

Example of the current buggy behaviour:
image

**Bugs this fixes:** 

Fixes #16460 

**Workarounds, if any**

No workaround

**Risk**

No risk. All references to Roslyn GetFinalSymbolName simply return the same string they are passed in.

**Performance impact**

No performance impact.

**Is this a regression from a previous update?**

**Root cause analysis:**

No automated tests covering inline renaming (from what I could gather).

**How was the bug found?**

F# contributor testing (@vasily-kirichenko)

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @dotnet/roslyn-ide for review.

File: src/EditorFeatures/Core/Implementation/InlineRename/InlineRenameSession.cs [hunk 1]
```diff
@@ -587,7 +587,7 @@ private void CommitCore(IWaitContext waitContext, bool previewChanges)
                     newSolution = previewService.PreviewChanges(
                         string.Format(EditorFeaturesResources.Preview_Changes_0, EditorFeaturesResources.Rename),
                         "vs.csharp.refactoring.rename",
-                        string.Format(EditorFeaturesResources.Rename_0_to_1_colon, this.OriginalSymbolName, _renameInfo.GetFinalSymbolName(this.ReplacementText)),
+                        string.Format(EditorFeaturesResources.Rename_0_to_1_colon, this.OriginalSymbolName, this.ReplacementText),
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/InlineRename/InlineRenameSession.cs]: Wasn't `this.ReplacementText` already ran through the filter? Will this get filtered twice?

**Comment by saul** [comment]
@jasonmalinowski, I'm not sure what filter you're referring to. Do you mean GetFinalSymbolName? If so, then no it's only called once.

**Comment by jasonmalinowski** [comment]
Oh you moved the call and not added a second one. Wow I failed at reading that code.

**Comment by Pilchie** [comment]
Thanks @saul!
