### PR TITLE
Revise compound assignment for nullable

### LINKED ISSUE #29962: Incorrect nullability analysis in compound assignment
```C#

        public override BoundNode VisitCompoundAssignmentOperator(BoundCompoundAssignmentOperator node)
        {
            VisitLvalue(node.Left); // PROTOTYPE(NullableReferenceTypes): Method should be called VisitValue rather than VisitLvalue.
            TypeSymbolWithAnnotations leftType = _resultType;

            TypeSymbolWithAnnotations resultType;
            Debug.Assert(!IsConditionalState);

            //if (this.State.Reachable) // Consider reachability: see https://github.com/dotnet/roslyn/issues/28798
            {
                TypeSymbolWithAnnotations leftOnRightType = GetAdjustedResult(leftType, MakeSlot(node.Left));

                // PROTOTYPE(NullableReferenceTypes): Update operator based on inferred argument types.
                if ((object)node.Operator.LeftType != null)
                {
                    // PROTOTYPE(NullableReferenceTypes): Ignoring top-level nullability of operator left parameter.
                    leftOnRightType = ApplyConversion(
                        node.Left,
                        node.Left,
                        node.LeftConversion,
                        TypeSymbolWithAnnotations.Create(node.Operator.LeftType),
                        leftOnRightType,
                        checkConversion: true,
                        fromExplicitCast: false,
                        useLegacyWarnings: false,
                        AssignmentKind.Assignment,
                        reportTopLevelWarnings: false,
                        reportNestedWarnings: false);
                }
                else
                {
                    leftOnRightType = default;
                }

                VisitRvalue(node.Right);
                TypeSymbolWithAnnotations rightType = _resultType;

                if ((object)node.Operator.ReturnType != null)
                {
                    if (node.Operator.Kind.IsUserDefined() && (object)node.Operator.Method != null && node.Operator.Method.ParameterCount == 2)
                    {
                        ReportArgumentWarnings(node.Left, leftOnRightType, node.Operator.Method.Parameters[0]);
                        ReportArgumentWarnings(node.Right, rightType, node.Operator.Method.Parameters[1]);
                    }

                    resultType = InferResultNullability(node.Operator.Kind, node.Operator.Method, node.Operator.ReturnType, leftOnRightType, rightType);
                    resultType = ApplyConversion(
                        node,
                        node,
                        node.FinalConversion,
                        leftType,
                        resultType,
                        checkConversion: true,
                        fromExplicitCast: false,
                        useLegacyWarnings: false,
                        AssignmentKind.Assignment);
                }
                else
                {
                    resultType = TypeSymbolWithAnnotations.Create(node.Type);
                }

                TrackNullableStateForAssignment(node, leftType, MakeSlot(node.Left), resultType);
                _resultType = resultType;
            }
            //else
            //{
            //    VisitRvalue(node.Right);
            //    AfterRightHasBeenVisited(node);
            //    resultType = null;
            //}

            return null;
        }
```

### LINKED ISSUE #65546: Compilator can't find the matching overload for operator+ when implementing nullability to project
### Describe the bug
I have an overload of operator+, which takes two arguments: (CustomObject x, Guid[]?), but the compilator doesn't call the overload when used. And throws this error message: "Error	CS8620	Argument of type 'Guid[]' cannot be used for parameter 'y' of type 'Guid' in 'CustomObject CustomObject.operator +(CustomObject x, Guid[]? y)' due to differences in the nullability of reference types." even though all types should be matching.

### Further technical details
- Include the output of `dotnet --info`
- VS 2022

### LINKED ISSUE #70646: Incorrect nullable analysis of compound assignment due to double visit of operands
**Version Used**: https://github.com/dotnet/roslyn/commit/74619838680598cd5b357d9d10b5a407b730508c

**Steps to Reproduce**:

[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAUPgMwAERNAwjQN4U3t237EBsjNAewAOAU2QQEA5DWwAKJgGM4NWAhUBKGgF4AfDQUBuNh2PsihUy0sdGAfhoRtNGKgA2r5cCcv3yhd5EAd1l1I3IbG39sLRoAWWJZRxjgTycFUOsOCAA6ABUBAGUEZFgAcxCDGgB6KpoRAA9RBQQRDBpAiGQYMs9UNRgBGBF2iABnGmQRISkWjEsAX0tLajpeOgAWOOgYBPVLVnCI9gZ7JOc3DxovGJ9L/xugisz2KJj4xKcUq7SMw6PXuIJM5fa76X5Hdg5fJFEowcqhaq1AAWYmGAxgAFpbjQAG4QVyoYYAM1cAkC40kNAA5BAqcpRgJnIyOl0yipxg0mrNsgsln9VnxVID5KdlCcrppdDQAAxheZAA)

```cs
using System;
public class C {
    public static C operator +(C c, int i) => c;
    
    public static void Main()
    {
        C? a = null, b = null, c = new();
        c += M1(a = b, b = c);
        a.ToString(); // expected warning, but none was reported
    }
    
    public static void Main1()
    {
        C? a = null, b = null, c = new();
        c += M1(a = b, b = c);
        c += M1(a = b, b = c);
        a.ToString(); // here non-null value flows to 'a', so no warning is expected.
    }
    
    static int M1(C? a, C? b) => 0;
}
```

**Expected Behavior**: a nullable warning is reported on `a.ToString()` in Main

**Actual Behavior**: no nullable warning is reported and a NullReferenceException occurs at runtime

**Remarks**: The following call to VisitArguments is problematic because the arguments we are passing in were already visited separately. This causes unexpected changes in flow state.

https://github.com/dotnet/roslyn/blob/bafa495e3af419c164b9b95dce37029de99c1069/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs#L9942-L9943

I hope to resolve this along with #29962 and #65546

### PR DESCRIPTION
**Pull request by RikkiGibson**
- Closes #70646.
- Closes #65546.
- Closes #29962.

Addresses several nullable issues, mainly related to compound assignment. I made an effort to share code for visiting a normal binary operator with the code for visiting a compound assignment.

`VisitCompoundAssignmentOperator` has been pretty much rewritten only using the original code as a reference. I would recommend that you review the old and new versions of the methods separately as the diff may be a little noisy.

Other minor adjustments in the PR include:
- simplifies disabling nullable warnings on default arguments. Eliminates a rather crufty condition in `ReportNullableAssignmentIfNecessary` and instead ensures that we pass along the default arguments BitVector so that we set `_disableDiagnostics` in the right places.
- changed the nullable state of an assignment expression to a property with `[AllowNull]`. Now, any "sanitizing" of the value going into the property will not apply until the property is actually read again. This more precisely reflects the semantics of this scenario.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 1]
```diff
@@ -9899,79 +9899,116 @@ private ImmutableArray<BoundExpression> GetDeconstructionRightParts(BoundExpress
...
+                leftLvalueType,
+                resultTypeWithState,
+                checkConversion: true,
+                fromExplicitCast: false,
+                useLegacyWarnings: false,
+                assignmentKind: AssignmentKind.Assignment);
+
+            // visit 'x = (TResult)((TLeft)x op (TRight)y)'
+            // Handle `[DisallowNull]` on LHS operand (final assignment target).
+            if (CheckDisallowedNullAssignment(resultTypeWithState, GetLValueAnnotations(node.Left), node.Right.Syntax))
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:9990]: reuse leftArgumentAnnotations here.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 2]
```diff
@@ -9368,6 +9379,9 @@ private void VisitThisOrBaseReference(BoundExpression node)
                 {
                     SetResult(node, TypeWithState.Create(leftLValueType.Type, rightState.State), leftLValueType);
                 }
+
+                AdjustSetValue(left, ref rightState);
+                TrackNullableStateForAssignment(right, leftLValueType, MakeSlot(left), rightState, MakeSlot(right));
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:9384]: What is the effect of moving these lines?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 3]
```diff
@@ -9899,78 +9913,63 @@ private ImmutableArray<BoundExpression> GetDeconstructionRightParts(BoundExpress
...
-            TypeWithAnnotations declaredType = LvalueResultType;
-            TypeWithAnnotations leftLValueType = declaredType;
-            TypeWithState leftResultType = ResultType;
-
-            Debug.Assert(!IsConditionalState);
-
-            TypeWithState leftOnRightType = GetAdjustedResult(leftResultType, MakeSlot(node.Left));
+            // for an operator like: 'TResult operator op(TLeftParam left, TRightParam right);'
+            // and usage like: 'x op= y;'
+            // expansion is (roughly): 'x = (TLeftArg)((TLeftParam)x op (TRightParam)y);'
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:9918]: >TLeftArg [](http://example.com/codeflow?start=45&length=8)

`TLeftParam`?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 4]
```diff
@@ -9899,78 +9913,63 @@ private ImmutableArray<BoundExpression> GetDeconstructionRightParts(BoundExpress
...
 
-                FlowAnalysisAnnotations leftAnnotations = GetLValueAnnotations(node.Left);
-                leftLValueType = ApplyLValueAnnotations(leftLValueType, leftAnnotations);
+            // visit '(TLeftParam)x op (TRightParam)y'
+            var resultTypeWithState = ReinferAndVisitBinaryOperator(
+                node,
+                node.Operator.Kind,
+                node.Operator.Method,
+                node.Operator.ReturnType ?? node.Type,
+                node.LeftConversion as BoundConversion ?? node.Left,
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:9939]: > as BoundConversion [](http://example.com/codeflow?start=35&length=19)

Is `as BoundConversion` necessary? What else might this be other than a `BoundConversion` or `null`?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:9384]: When we adjust the set value after setting the result, it reflects the fact that the property needs to be read again before a "sanitized" value can be observed. See test `Assignment_AllowNullProperty_Value`.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 5]
```diff
@@ -9899,78 +9913,63 @@ private ImmutableArray<BoundExpression> GetDeconstructionRightParts(BoundExpress
...
-            else
-            {
-                resultType = TypeWithState.Create(node.Type, NullableFlowState.NotNull);
-            }
+            SetResultType(node, resultTypeWithState);
 
-            AdjustSetValue(left, ref resultType);
-            TrackNullableStateForAssignment(node, leftLValueType, MakeSlot(node.Left), resultType);
+            AdjustSetValue(node.Left, ref resultTypeWithState);
+            Debug.Assert(MakeSlot(node) == -1);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:9970]: >Debug.Assert(MakeSlot(node) == -1); [](http://example.com/codeflow?start=12&length=35)

Just curious: Why assert this?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:9970]: I wanted to indicate that the value stored in the LHS of the compound-assignment effectively drops any "sub-slot" information in either operand of the compound-assignment, i.e. the nullable state of fields of the operands. Showing that the entire compound-assignment never has a slot felt useful. See test `CompoundAssignment_SubSlots`.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:9939]: https://github.com/dotnet/roslyn/blob/003a34f525da234ee59228133631cc285ac5f49a/src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml#L546-L547

The other possibility is that it is a `BoundPlaceholder`, which to me didn't make sense to visit as if the operand is really being operated on by that placeholder. However, I don't think I tested to see what happens when we remove the `as BoundConversion`.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 6]
```diff
@@ -71716,42 +71774,230 @@ class C
...
+                        tc += guidArray;
+                    }
+                }
+                """;
+
+            var comp = CreateCompilation(source);
+            comp.VerifyEmitDiagnostics();
+        }
+
+        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/65546")]
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:71835]: >https://github.com/dotnet/roslyn/issues/65546 [](http://example.com/codeflow?start=25&length=45)

70646?

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 7]
```diff
@@ -71716,42 +71774,230 @@ class C
...
+                // (17,9): warning CS8602: Dereference of a possibly null reference.
+                //         c1.f1.ToString(); // 1
+                Diagnostic(ErrorCode.WRN_NullReferenceReceiver, "c1.f1").WithLocation(17, 9),
+                // (18,9): warning CS8602: Dereference of a possibly null reference.
+                //         c1.f2.ToString(); // 2
+                Diagnostic(ErrorCode.WRN_NullReferenceReceiver, "c1.f2").WithLocation(18, 9),
+                // (19,9): warning CS8602: Dereference of a possibly null reference.
+                //         c1.f3.ToString(); // 3
+                Diagnostic(ErrorCode.WRN_NullReferenceReceiver, "c1.f3").WithLocation(19, 9));
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:71909]: >} [](http://example.com/codeflow?start=8&length=1)

Should we test the following as well?
```csharp
class C
{
    public string f1, f2, f3;
}
C c1 = new() { f1 = null, f2 = null }; // 1, 2
C c2 = new() { f1 = null, f3 = null }; // 3, 4
c1 += c2;
c1.f1.ToString();
c1.f2.ToString();
c1.f3.ToString();
```

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 5 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:9970]: A regular assignment can have a slot.

It's possible a compound assignment should have a slot for the same reason but I feel comfortable punting on it.

https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLoN7LpGYZQAs6AsgBRRwAMA/OgB4A0mDzAnh3U+gBeASnyFiEgJYAzdNWot0AXnTdRAQhUA7AK4AbPaJYA6ACoB7AMoAXAE6StAc2rCA3OIlETFm/acv3JAkAX2RgoA===

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.DebugVerifier.cs [hunk 8]
```diff
@@ -186,6 +186,18 @@ private void VerifyExpression(BoundExpression expression, bool overrideSkippedEx
                 return base.VisitAssignmentOperator(node);
             }
 
+            public override BoundNode? VisitCompoundAssignmentOperator(BoundCompoundAssignmentOperator node)
+            {
+                if (node.LeftConversion is BoundConversion leftConversion)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.DebugVerifier.cs:191]: `BoundCompoundAssignmentOperator` also has a `FinalConversion` (for converting result of binary operator back to left type). Should that be verified here too?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.DebugVerifier.cs:191]: The fact that we are verifying this here is somewhat an accident of how the shared `ReinferAndVisitBinaryOperator` works. We didn't end up needing to do that for the final conversion. The way we happen to visit the final conversion doesn't end up including it in the visited nodes map.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 9]
```diff
@@ -69446,24 +69501,32 @@ public void BinaryOperator_15_WithDisallowNull()
...
     public static S? operator+(S? a, [DisallowNull] S? b) => throw null!;
-    static void F(S? x, S? y)
+    static void F1(S? x, S? y)
     {
         if (x == null) throw null!;
         S? s;
         s = x + x;
         s = x + y; // 1
         s = y + x;
+        s = y + y; // no warning
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:69511]: If I understood properly, the key here is that we have a side-effect from line above that produced warning number 1. Although I think it's good to test that scenario (since it was affected by change), I think the intent of the test was to check each binary operation in isolation. 

Feels like we should split the binary operations to independent methods to ensure isolation.
If the purpose is to validate the nullable state of a variable as a side-effect of a binary operation, then doing `y.Value.ToString()` seems more direct.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.DebugVerifier.cs (hunk 8 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.DebugVerifier.cs:191]: > [...] doesn't end up including [the final conversion] in the visited nodes map.

That seems strange. I would have expected the visited nodes map to include all bound nodes, with enumerated exceptions (in `s_skippedExpressions`).

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 4 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:9939]: nit: No test is affected by the removal of `as BoundConversion`. It'd be good to hunt one down.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 3)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:9939]: Opened #70751 to try and find a scenario which could be used as a starting point. I probably will not block the PR on it, though.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.DebugVerifier.cs (hunk 8 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.DebugVerifier.cs:191]: Some nodes, including the Conversion/Placeholder nodes, are marked "skipInVisitor" and won't be visited unless we go out of our way to do so.

**Review by jcouv — APPROVED** [review]
