### PR TITLE
Don't offer to remove variable in situations where we would crash

### LINKED ISSUE #49827: ArgumentNullException on CSharpRemoveUnusedVariableCodeFixProvider.
**Version Used**: 
master: 1afc0cf904ed74841b108a2c1395cd73a61e9cbe
**Steps to Reproduce**:

```csharp
namespace TestRepro
{
	class Another_crash
	{
		void Test2(bool test)
		{
			if(test and test) { // List codefixes here will throw the exception.

			}
		}
	}
}
```

**Expected Behavior**:

The codefix provider should not crash.

**Actual Behavior**:

<details><summary>Exception stacktrace </summary>
<p>
System.ArgumentNullException : Value cannot be null.
Parameter name: statement
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitIfStatement(IfStatementSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.IfStatementSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxNodeRemover.SyntaxRemover.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitBlock(BlockSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxNodeRemover.SyntaxRemover.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitMethodDeclaration(MethodDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxNodeRemover.SyntaxRemover.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitClassDeclaration(ClassDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxNodeRemover.SyntaxRemover.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitNamespaceDeclaration(NamespaceDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.NamespaceDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxNodeRemover.SyntaxRemover.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitCompilationUnit(CompilationUnitSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxNodeRemover.SyntaxRemover.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxNodeRemover.RemoveNodes[TRoot](TRoot root,IEnumerable`1 nodes,SyntaxRemoveOptions options)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.RemoveNodesCore(IEnumerable`1 nodes,SyntaxRemoveOptions options)
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.RemoveNode[TRoot](TRoot root,SyntaxNode node,SyntaxRemoveOptions options)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.RemoveNodeInternal(SyntaxNode root,SyntaxNode declaration,SyntaxRemoveOptions options)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.<>c__DisplayClass198_0.<RemoveNode>b__0(SyntaxNode r)
   at Microsoft.CodeAnalysis.Editing.SyntaxGenerator.PreserveTrivia[TNode](TNode node,Func`2 nodeChanger)
   at Microsoft.CodeAnalysis.CSharp.CodeGeneration.CSharpSyntaxGenerator.RemoveNode(SyntaxNode root,SyntaxNode node,SyntaxRemoveOptions options)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.RemoveChange.Apply(SyntaxNode root,SyntaxGenerator generator)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
</p>
</details>

### PR DESCRIPTION
**Pull request by davidwengier**
Fixes #49827

Take two! Lets see if I can follow instructions 😄

### CODE REVIEW

File: src/Features/CSharp/Portable/RemoveUnusedVariable/CSharpRemoveUnusedVariableCodeFixProvider.cs [hunk 1]
```diff
@@ -69,5 +69,19 @@ protected override void RemoveOrReplaceNode(SyntaxEditor editor, SyntaxNode node
 
         protected override SeparatedSyntaxList<SyntaxNode> GetVariables(LocalDeclarationStatementSyntax localDeclarationStatement)
             => localDeclarationStatement.Declaration.Variables;
+
+        protected override bool ShouldOfferFix(ISyntaxFactsService syntaxFacts, SyntaxNode node)
+        {
+            // Local declarations must be parented by an executable block (or global statement) otherwise
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/RemoveUnusedVariable/CSharpRemoveUnusedVariableCodeFixProvider.cs:75]: interesting.  i'm surprised we can remove it from a GlobalStatement (as i assume taht would leave the global statement without an actual statement, which i would think woudl break too).  Or is that because when we remove the node we actually walk up and remove the global statement?

File: src/Features/CSharp/Portable/RemoveUnusedVariable/CSharpRemoveUnusedVariableCodeFixProvider.cs [hunk 2]
```diff
@@ -69,5 +69,19 @@ protected override void RemoveOrReplaceNode(SyntaxEditor editor, SyntaxNode node
...
+            // removing them would be invalid (and more than likely crash the fixer)
+            if (node.Parent.Parent is LocalDeclarationStatementSyntax { Parent: var localDeclParent } &&
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/RemoveUnusedVariable/CSharpRemoveUnusedVariableCodeFixProvider.cs:77]: insead of PArent.Parent, i would find the ancestor that is a TLocalDeclarationStatement.  That's what the fixer actually does.  in general, we want the logic to be the same so we know that whatever the fix logic is deciding to remove the checking logic has checked the same thing.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/RemoveUnusedVariable/CSharpRemoveUnusedVariableCodeFixProvider.cs:77]: the relevant line is: https://github.com/dotnet/roslyn/pull/56902/files#diff-1a572f8959b2a2b068b03239a019de5818b4a1a57868cb49c62d84baf37ac17fL114

Consider extracting this out to a common helper to keep them in sync.  Once you find the LocalDecl, then you check that it's either in a GlobalStatement or an ExecutableBlock.

**Review by CyrusNajmabadi — APPROVED** [review]
overall logic i approve of.  just would like some slight sharing to keep things in sync.

File: src/Features/CSharp/Portable/RemoveUnusedVariable/CSharpRemoveUnusedVariableCodeFixProvider.cs (hunk 1 above)
Comment (davidwengier) [reply src/Features/CSharp/Portable/RemoveUnusedVariable/CSharpRemoveUnusedVariableCodeFixProvider.cs:75]: Like 65 of this file handles that, but removing the whole global statement instead of just the statement. Can't do that here, because removing the if statement would be odd.

File: src/Features/CSharp/Portable/RemoveUnusedVariable/CSharpRemoveUnusedVariableCodeFixProvider.cs [hunk 3]
```diff
@@ -69,5 +69,18 @@ protected override void RemoveOrReplaceNode(SyntaxEditor editor, SyntaxNode node
...
+        {
+            // Local declarations must be parented by an executable block, or global statement, otherwise
+            // removing them would be invalid (and more than likely crash the fixer)
+            if (localDeclaration.Parent is not GlobalStatementSyntax &&
+                !syntaxFacts.IsExecutableBlock(localDeclaration.Parent))
+            {
+                return false;
+            }
+
+            return true;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/RemoveUnusedVariable/CSharpRemoveUnusedVariableCodeFixProvider.cs:83]: nit, consider:

```suggestion
            return localDeclaration.Parent is GlobalStatementSyntax ||
                syntaxFacts.IsExecutableBlock(localDeclaration.Parent))
```

This is simpler or me as there's a lot less negations.  in the original there are two negations in the condition itself.  and then the truthy condition is negated for a falsy result.  Personally, i find that more confusing than just returning this simpler truthy expression.  Up to you though.

File: src/Features/Core/Portable/RemoveUnusedVariable/AbstractRemoveUnusedVariableCodeFixProvider.cs [hunk 4]
```diff
@@ -34,13 +34,25 @@ internal abstract class AbstractRemoveUnusedVariableCodeFixProvider<TLocalDeclar
...
-            return Task.CompletedTask;
+
+            var document = context.Document;
+            var root = await document.GetSyntaxRootAsync(context.CancellationToken).ConfigureAwait(false);
+            var node = root.FindNode(diagnostic.Location.SourceSpan);
+
+            var syntaxFacts = document.GetRequiredLanguageService<ISyntaxFactsService>();
+            var localDeclaration = FindLocalDeclaration(node);
+
+            if (localDeclaration is null || ShouldOfferFixForLocalDeclaration(syntaxFacts, localDeclaration))
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/RemoveUnusedVariable/AbstractRemoveUnusedVariableCodeFixProvider.cs:52]: out of curiosity, when are we removing when there is no local variable decl?

Comment (davidwengier) [reply src/Features/Core/Portable/RemoveUnusedVariable/AbstractRemoveUnusedVariableCodeFixProvider.cs:52]: A declaration in a for loop, or catch clause for example

File: src/Features/CSharp/Portable/RemoveUnusedVariable/CSharpRemoveUnusedVariableCodeFixProvider.cs [hunk 5]
```diff
@@ -69,5 +69,13 @@ protected override void RemoveOrReplaceNode(SyntaxEditor editor, SyntaxNode node
 
         protected override SeparatedSyntaxList<SyntaxNode> GetVariables(LocalDeclarationStatementSyntax localDeclarationStatement)
             => localDeclarationStatement.Declaration.Variables;
+
+        protected override bool ShouldOfferFixForLocalDeclaration(ISyntaxFactsService syntaxFacts, LocalDeclarationStatementSyntax localDeclaration)
+        {
+            // Local declarations must be parented by an executable block, or global statement, otherwise
+            // removing them would be invalid (and more than likely crash the fixer)
+            return localDeclaration.Parent is GlobalStatementSyntax ||
+                syntaxFacts.IsExecutableBlock(localDeclaration.Parent))
```
Comment (davidwengier) [inline src/Features/CSharp/Portable/RemoveUnusedVariable/CSharpRemoveUnusedVariableCodeFixProvider.cs:78]:
```suggestion
                syntaxFacts.IsExecutableBlock(localDeclaration.Parent);
```

File: src/Features/Core/Portable/RemoveUnusedVariable/AbstractRemoveUnusedVariableCodeFixProvider.cs (hunk 4 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/RemoveUnusedVariable/AbstractRemoveUnusedVariableCodeFixProvider.cs:52]: Ah. The get ancestor call is wrong then. You could have a catch variable in a llama inside a local decl initializer.

Comment (davidwengier) [reply src/Features/Core/Portable/RemoveUnusedVariable/AbstractRemoveUnusedVariableCodeFixProvider.cs:52]: Lost to the auto-merge, logged https://github.com/dotnet/roslyn/issues/56924 and will follow up.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/RemoveUnusedVariable/AbstractRemoveUnusedVariableCodeFixProvider.cs:52]: That's fine
