### PR TITLE
Validate generic arguments in `using static` directives

### LINKED ISSUE #30726: Using static Type<T> with constraints produces incorrect program instead of build error.
**Version Used**: 15.8.7

**Steps to Reproduce**:

```c#
using static Test<System.String>;

public static class Test<T> where T : struct
{
    public static void Run( T item ) { }
}

class Program
{
    static void Main( string[] args )
    {
        Run( "This should not compile." );
    }
}
```

**Expected Behavior**:

The compiler should issue an error:
**CS0453**: The type 'string' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'Test<T>'

**Actual Behavior**:
The program compiles. When you run the program we get:
**System.TypeLoadException:** 'GenericArguments[0], 'System.String', on 'Test`1[T]' violates the constraint of type parameter 'T'.'

The compiled IL code is:

```IL
IL_0000: ldstr "This should not compile."
IL_0005: call void class Test`1<string>::Run(!0)
```

### PR DESCRIPTION
**Pull request by RikkiGibson**
Resolves #30726

Looks like there is a separate Validate() phase in Imports which takes place after binding, probably because attempting certain validations during binding can result in a stack overflow.

This PR adds to the Imports.Validate method to validate constraints on `using static`. It was already validating constraints on using aliases which explains what we were seeing before @AlekseyTs.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/BindingTests.cs [hunk 1]
```diff
@@ -3364,6 +3364,26 @@ public static int MathMax3(this int a, int b)
             Assert.False(symbols.Where(s => s.Name == "MathMax3").Any());
         }
 
+        [Fact, WorkItem(30726, "https://github.com/dotnet/roslyn/issues/30726")]
+        public void UsingStaticGenericConstraint()
+        {
+            var code = @"
+using static Test<System.String>;
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/BindingTests.cs]: Note that the diagnostic we produce will squiggle all of `Test<System.String>` instead of just `System.String`. This is maybe not perfect (why not squiggle the particular type argument that's wrong?) but shouldn't impact usability much.

File: src/Compilers/CSharp/Portable/Binder/Imports.cs [hunk 2]
```diff
@@ -576,6 +576,18 @@ private void Validate()
...
 
+            foreach (var @using in Usings)
+            {
+                // Check if `using static` directives meet constraints.
+                if (@using.NamespaceOrType.IsType)
+                {
+                    var typeSymbol = (TypeSymbol)@using.NamespaceOrType;
+                    var corLibrary = typeSymbol.ContainingAssembly.CorLibrary;
+                    var conversions = new TypeConversions(corLibrary);
+                    typeSymbol.CheckAllConstraints(conversions, @using.UsingDirective.Name.Location, semanticDiagnostics);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Imports.cs]: Looks like there's an NRE in here.

File: src/Compilers/CSharp/Portable/Binder/Imports.cs [hunk 3]
```diff
@@ -576,6 +576,18 @@ private void Validate()
                 alias.Alias.CheckConstraints(semanticDiagnostics);
             }
 
+            foreach (var @using in Usings)
+            {
+                // Check if `using static` directives meet constraints.
+                if (@using.NamespaceOrType.IsType)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/Imports.cs]: Is it worth explicitly checking if this is a static using? Today yes when `NamespaceOrType.IsType` is true then it's a `using static`. That's possibly something that is not going to be true in the future though. Think it might benefit from a more explicit check. Possibly add a property to `NamespaceOrTypeUsingDirective` called `IsStatic` that does this under the hood.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Imports.cs]: > Is it worth explicitly checking if this is a static using? 

It feels like it shouldn't matter whether the using is static or not, the constraints should be satisfied anyways.

---
In reply to: [227993769](https://github.com/dotnet/roslyn/pull/30737#discussion_r227993769) [](ancestors = 227993769)

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Imports.cs]: Not certain, but I'm leaning toward no because it seems like any conceivable feature that involves referencing a type in a using directive should still have the compiler check constraints on that type.

File: src/Compilers/CSharp/Portable/Binder/Imports.cs [hunk 4]
```diff
@@ -576,6 +576,18 @@ private void Validate()
...
+                {
+                    var typeSymbol = (TypeSymbol)@using.NamespaceOrType;
+                    var corLibrary = typeSymbol.ContainingAssembly.CorLibrary;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Imports.cs]: >var corLibrary = typeSymbol.ContainingAssembly.CorLibrary; [](start = 20, length = 58)

I think it is more appropriate to request CorLibrary from ```_compilation.SourceAssembly``` rather than from the assembly that defines the type. The type name in the using was resolved in context of the ```_compilation```. We will also be able to share a single ```TypeConversions``` instance to check all types.

File: src/Compilers/CSharp/Portable/Binder/Imports.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Imports.cs]: It looks like UsingDirective can be null in scripting scenarios? Do I need to supply an alternate location in such cases?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Imports.cs]: > It looks like UsingDirective can be null in scripting scenarios? Do I need to supply an alternate location in such cases?

We usually use ```NoLocation.Singleton``` in situations when there is no specific syntax to refer to.

---
In reply to: [227996503](https://github.com/dotnet/roslyn/pull/30737#discussion_r227996503) [](ancestors = 227996503)

File: src/Compilers/CSharp/Portable/Binder/Imports.cs (hunk 3 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Imports.cs]: Sounds good.

File: src/Compilers/CSharp/Portable/Binder/Imports.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Imports.cs]: Addressed in 2fb9e18

File: src/Compilers/CSharp/Test/Semantic/Semantics/BindingTests.cs [hunk 5]
```diff
@@ -3364,6 +3364,26 @@ public static int MathMax3(this int a, int b)
...
+}
+";
+            CreateCompilationWithMscorlib45(code).VerifyDiagnostics(
+                // (2,1): hidden CS8019: Unnecessary using directive.
+                // using static Test<System.String>;
+                Diagnostic(ErrorCode.HDN_UnusedUsingDirective, "using static Test<System.String>;").WithLocation(2, 1),
+                // (2,14): error CS0453: The type 'string' must be a non-nullable value type in order to use it as parameter 'T' in the generic type or method 'Test<T>'
+                // using static Test<System.String>;
+                Diagnostic(ErrorCode.ERR_ValConstraintNotSatisfied, "Test<System.String>").WithArguments("Test<T>", "T", "string").WithLocation(2, 14));
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/BindingTests.cs]: >} [](start = 8, length = 1)

Consider testing constraint errors in containing types and nested types as well.
```c#
using static A<A<int>[]>.B;

class A<T> where T : class
{
    internal static class B { }
}
```

File: src/Compilers/CSharp/Portable/Binder/Imports.cs [hunk 6]
```diff
@@ -576,6 +576,19 @@ private void Validate()
...
             }
 
+            foreach (var @using in Usings)
+            {
+                // Check if `using static` directives meet constraints.
+                if (@using.NamespaceOrType.IsType)
+                {
+                    var typeSymbol = (TypeSymbol)@using.NamespaceOrType;
+                    var corLibrary = _compilation.SourceAssembly.CorLibrary;
+                    var conversions = new TypeConversions(corLibrary);
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/Imports.cs]: Do we need to recreate `conversions` for every type or can it be re-used here? Believe it can be re-used as it's the same for every iteration.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Imports.cs]: You're right. There's no reason to believe it will change per-using.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Imports.cs]: Note that basically the same conversions object is created in order to check constraints on using aliases. Any benefit in trying to lazy-load it on the compilation or something and reuse it?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Imports.cs]: > Note that basically the same conversions object is created in order to check constraints on using aliases. Any benefit in trying to lazy-load it on the compilation or something and reuse it?

It is probably safe to use Conversions cached on a compilation in all these places

---
In reply to: [228274243](https://github.com/dotnet/roslyn/pull/30737#discussion_r228274243) [](ancestors = 228274243)

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/BaseClassTests.cs [hunk 7]
```diff
@@ -2070,8 +2070,11 @@ AbstractClass Test()
 }";
             var comp = CreateCompilation(text);
             comp.VerifyDiagnostics(
+    // (2,14): error CS0311: The type 'object' cannot be used as type parameter 'T' in the generic type or method 'Crash<T>'. There is no implicit reference conversion from 'object' to 'CrashTest.Crash<object>.AbstractClass'.
+    // using static CrashTest.Crash<object>;
+    Diagnostic(ErrorCode.ERR_GenericConstraintNotSatisfiedRefType, "CrashTest.Crash<object>").WithArguments("CrashTest.Crash<T>", "CrashTest.Crash<object>.AbstractClass", "T", "object").WithLocation(2, 14),
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/BaseClassTests.cs]: This test contains a using static which violates a generic constraint. Before, we emitted a diagnostic on the usage of a class contained within the type imported via `using static`, but it seems correct to add a diagnostic to the `using static` directive itself here too.

**Comment by RikkiGibson** [comment]
Determinism test is broken. Weird.
```
2018-10-25T18:25:05.8119000Z ##[warning]Unable to run "git clean -ffdx" and "git reset --hard HEAD" successfully, delete source folder instead.
2018-10-25T18:25:12.8272801Z ##[error]System.AggregateException: One or more errors occurred. (One or more errors occurred. (Access to the path 'F:\vsagent\9\s\Binaries\Temp\VBCSCompiler\AnalyzerAssemblyLoader\eefc8a0313a344e783a6e8f6c55f7725\9\Microsoft.NetCore.VisualBasic.Analyzers.dll' is denied.)) (Access to the path 'F:\vsagent\9\s\Binaries\Temp\VBCSCompiler\AnalyzerAssemblyLoader\eefc8a0313a344e783a6e8f6c55f7725\9\Microsoft.NetCore.VisualBasic.Analyzers.dll' is denied.) ---> System.UnauthorizedAccessException: Access to the path 'F:\vsagent\9\s\Binaries\Temp\VBCSCompiler\AnalyzerAssemblyLoader\eefc8a0313a344e783a6e8f6c55f7725\9\Microsoft.NetCore.VisualBasic.Analyzers.dll' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.FileInfo.Delete()
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.<>c__DisplayClass9_1.<DeleteDirectory>b__0(FileSystemInfo item)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolForAll[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, TaskScheduler taskScheduler)
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.DeleteDirectory(String path, Boolean contentsOnly, Boolean continueOnContentDeleteError, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.DeleteDirectory(String path, CancellationToken cancellationToken)
   at Agent.Plugins.Repository.GitSourceProvider.GetSourceAsync(AgentTaskPluginExecutionContext executionContext, RepositoryResource repository, CancellationToken cancellationToken)
   at Agent.Plugins.Repository.CheckoutTask.RunAsync(AgentTaskPluginExecutionContext executionContext, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'F:\vsagent\9\s\Binaries\Temp\VBCSCompiler\AnalyzerAssemblyLoader\eefc8a0313a344e783a6e8f6c55f7725\9\Microsoft.NetCore.VisualBasic.Analyzers.dll' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.FileInfo.Delete()
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.<>c__DisplayClass9_1.<DeleteDirectory>b__0(FileSystemInfo item)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)<---
```

**Comment by RikkiGibson** [comment]
CI is all good. Please review @AlekseyTs
