### PR TITLE
Fix couple of cast simplification bugs in unsafe and unchecked context

### LINKED ISSUE #2691: Invalid simplifications
The IDE incorrectly considers casts (float*) and (uint) to be unnecessary in the following cases:

```C#
        public float ReadSingle(byte* ptr)
        {
            return *(float*)ptr;
        }
```

```C#
        private readonly byte* _endPointer;
        private byte* _currentPointer;

        private void CheckBounds(int byteCount)
        {
            if (unchecked((uint)byteCount) > (_endPointer - _currentPointer))
            {
                ThrowOutOfBounds();
            }
        }
```

### PR DESCRIPTION
**Pull request by mavasani**
Fix cast simplification to not offer cast removals for following cases:

1) Explicit numeric casts in unchecked context
2) Non-identity pointer-to-pointer conversions.

Fixes #2691

Description: Fix is to bail out early for these cases. As we are now more conservative, we cannot regress in offering any additional incorrect cast removals.

Testing Done: Existing cast simplification tests.

/cc @ManishJayaswal @Srivatsn: Please let me know if the PR will correctly go into the stabilization branch.

### CODE REVIEW

**Comment by mavasani** [comment]
@tmeschter @jmarolf @shyamnamboodiripad @tmat @amcasey please review.

File: src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs [hunk 1]
```diff
@@ -355,6 +360,16 @@ public static bool IsUnnecessaryCast(this CastExpressionSyntax cast, SemanticMod
...
             }
+            else if (expressionToCastType.IsExplicit && expressionToCastType.IsNumeric && IsInUncheckedContext(cast))
+            {
+                // Don't remove any explicit numeric casts in unchecked context.
+                return false;
+            }
+            else if (expressionToCastType.IsPointer)
+            {
+                // Don't remove any non-identity pointer conversions.
+                return expressionType != null && expressionType.Equals(outerType);
```
Comment (amcasey) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: It might still be reasonable to remove certain casts to void*.  Definitely not essential.

File: src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs [hunk 2]
```diff
@@ -540,5 +555,22 @@ private static bool IsRequiredImplicitNumericConversion(ITypeSymbol sourceType,
...
+
+            do
+            {
+                if (currentNode.Kind() == SyntaxKind.UncheckedExpression || currentNode.Kind() == SyntaxKind.UncheckedStatement)
+                {
+                    return true;
+                }
+
+                currentNode = currentNode.Parent;
+            } while (currentNode is ExpressionSyntax || currentNode is StatementSyntax);
```
Comment (amcasey) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: This will stop if it hits a lambda, correct?

**Comment by amcasey** [comment]
LGTM.

File: src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs (hunk 1 above)
Comment (mavasani) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: Hmm, I have taken the most conservative approach here :) Let me open a new issue to properly deal with cast simplification involving pointer conversions. Probably you and/or other unsafe code experts can guide/review the implementation.

File: src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs (hunk 2 above)
Comment (tmat) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: It will not for expression-bodied lambdas.

Comment (tmat) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: The context can also be set by a compilation wide option.

Comment (tmat) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: Re lambdas: it actually should not stop at lambda body. 

In this case I believe the cast is unchecked:
```
unchecked { () => (uint)x } 
```

Comment (mavasani) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: Yes, Tomas is write. I'll add a test for this scenario.

I'll also fix the simplifier to check for compilation wide option and add a test for the same.

Comment (amcasey) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: I agree for unchecked statements, but what if the lambda is in an unchecked expression?  Also, should you stop if you encounter a checked statement/expression?

Comment (mavasani) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: Lambda in unchecked expression: Is that an important scenario? I'd prefer to still err on the conservative side.

Checked expression/statement: Indeed we should bail out and return false, I'll fix that and also add a test.

**Comment by mavasani** [comment]
@tmat Compiler exposes APIs to classify conversions, and the cast simplifier is responsible for determining if they are equivalent or not. The idea here is that if someone has explicit numeric casts within an unchecked context, they probably know what they are doing. Maybe we can be smarter to detect more redundant casts in this scenario, but implementing that feature would be for post RTM. Goal here is to do a minimum risk fix to ensure no incorrect cast removals are suggested.

**Comment by tmat** [comment]
@mavasani I agree we should be conservative for now. But don't agree on assuming that if someone uses unchecked/checked context explicitly they know exactly what casts are needed. There are various weird sign-extension rules that are hard to understand. I found myself wondering why the compiler asks me to put cast in on many occasions.

**Comment by mavasani** [comment]
@tmat Sure, let me open a new issue for post 1.0 to do smarter cast simplification in unchecked and pointer conversion contexts.

File: src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs (hunk 2 above)
Comment (mavasani) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: @tmat Regarding this: _The context can also be set by a compilation wide option._

The default compilation option is unchecked for non-constant expressions. I don't think want to disable all explicit numeric cast simplifications at project level. Probably this is better addressed post 1.0, I'll add this to the work item I create.
