### PR TITLE
Address cases where brace matching wasn't working for string quotes.

### LINKED ISSUE #62571: Auto-quotes and "$" operator problem
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Auto-quotes-and--operator-problem/10092299)._

---
[severity:It bothers me. A fix would be nice]
I have some sort of problem. When I want to use **'$'** operator in C#, for instance in `Console.Writeline($"Hello world")`, auto-quotes for some reason doesn't work, but it perfectly works when I use **'@'** operator before a string like here: `Console.Writeline(@"Hello world")`

---
#### Feedback Bot on 7/11/2022, 06:23 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes #62571

### CODE REVIEW

File: src/Features/CSharp/Portable/BraceCompletion/InterpolatedStringBraceCompletionService.cs [hunk 1]
```diff
@@ -5,87 +5,83 @@
...
-
-            if (text[start] != '$')
-                return false;
-
-            // Verify that we are actually in an location allowed for an interpolated string.
-            var token = document.Root.FindToken(start);
-            if (token.Kind() is not SyntaxKind.InterpolatedStringStartToken and
-                                not SyntaxKind.InterpolatedVerbatimStringStartToken and
-                                not SyntaxKind.StringLiteralToken and
-                                not SyntaxKind.IdentifierToken)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/BraceCompletion/InterpolatedStringBraceCompletionService.cs:80]: prior logic was too much syntax tree based.  this made it fall over when the tree wasn't well formed (like just having a naked `$` in an expression).

The fix is to smartly moved before those characters.  We then know we must have a string  (since we have a `$` and we know the user is typing `"`).   We then use the existing helpers to then ask "is this a legal place for such a string".  

Importantly, we're only looking at the tree *prior* to the current token we're writing.  we're not trying to examine the in-progress token itself directly.

File: src/EditorFeatures/CSharpTest/AutomaticCompletion/AutomaticLiteralCompletionTests.cs [hunk 2]
```diff
@@ -13,7 +11,7 @@
 namespace Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.AutomaticCompletion
 {
     [Trait(Traits.Feature, Traits.Features.AutomaticCompletion)]
-    public class AutomaticLiteralCompletionTests : AbstractAutomaticBraceCompletionTests
+    public sealed class AutomaticLiteralCompletionTests : AbstractAutomaticBraceCompletionTests
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/EditorFeatures/CSharpTest/AutomaticCompletion/AutomaticLiteralCompletionTests.cs:14]: This is currently not needing to view with whitespace off (a very good thing)

File: src/Features/CSharp/Portable/BraceCompletion/InterpolatedStringBraceCompletionService.cs [hunk 3]
```diff
@@ -5,87 +5,83 @@
...
-        public static bool IsPositionInInterpolatedStringContext(ParsedDocument document, int position, CancellationToken cancellationToken)
+        // Check if the user is typing an interpolated or interpolated verbatim string.
+        // If the preceding character(s) are not '$' or '$@' then we can't be starting an interpolated string.
+        if (text[start] == '@')
         {
-            var text = document.Text;
-
-            var start = position - 1;
-            if (start < 0)
+            // must have $@.  otherwise this is some other @ construct.
```
Comment (sharwell) [inline src/Features/CSharp/Portable/BraceCompletion/InterpolatedStringBraceCompletionService.cs:65]:
```suggestion
            // must have $@ for an interpolated string.  otherwise this is some other @ construct.
```

**Review by sharwell — APPROVED** [review]
Suggest manually verifying that this does not interfere with typing an interpolated raw string in the editor.

**Comment by CyrusNajmabadi** [comment]
> Suggest manually verifying that this does not interfere with typing an interpolated raw string in the editor.

Has done so.
