### PR TITLE
Invert the binding order of InitializerExpressions and CreationExpressions

### LINKED ISSUE #30357: Crach VS2017 craches when insert code with twice use one name out variable
<pre>crashtestconsoleapp.zip

class Program
    {
        static void Main(string[] args)
        {
            var int_string = &quot;123&quot;;
            // Replace &quot;0&quot; to &quot;int.TryParse(int_string, out var i) ? i : default(int)&quot;
            new TestData(int_string, 0) { Number = int.TryParse(int_string, out var i) ? i : default(int) };
        }

        struct TestData
        {
            public int Number { get; set; }
            public string Str { get; }

            public TestData(string str, int number)
            {
                Str = str;
                Number = number;
            }
        }
    }
</pre>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/328269/crach-vs2017-craches-when-insert-code-with-twice-u.html
VSTS ticketId: 677539_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

### PR DESCRIPTION
**Pull request by chsienki**
- Push intializer binding into the respective creation expression bindings so that initializer binding takes place *after* the creation, ensuring any referenced out vars have already been inferred,  thereby preventing infinite loops
- Add test to show behavior

Fixes #30357

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs [hunk 1]
```diff
@@ -34493,6 +34493,32 @@ public class C
...
+    }
+
+    public static void Main()
+    {
+        C c = new C(out var i) { Number = i };
+        System.Console.WriteLine(c.Number);
+    }
+}
+";
+            var compilation = CreateCompilationWithMscorlib45(source, options: TestOptions.DebugExe, parseOptions: TestOptions.Regular);
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs]: Use the `CreateCompilation` helper. It's the standard helper we should be using whenever possible.

File: src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs [hunk 2]
```diff
@@ -34493,6 +34493,32 @@ public class C
...
         }
+
+        [Fact]
+        public void OutVarInConstructorUsedInInitializer()
+        {
+            var source =
+@"
+public class C
+{
+    public int Number{ get; set; }
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs]: Nit: space before brace

File: src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs [hunk 3]
```diff
@@ -34493,6 +34493,32 @@ public class C
 ");
             Assert.Null(model.GetOperation(node3).Parent);
         }
+
+        [Fact]
+        public void OutVarInConstructorUsedInInitializer()
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs]: Do we have a similar test for collection initializers?

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 4]
```diff
@@ -3944,29 +3936,33 @@ private BoundExpression BindClassCreationExpression(ObjectCreationExpressionSynt
...
+                return BindClassCreationExpression(node, typeName, node.Type, type, analyzedArguments, diagnostics, node.Initializer, initializerType);
             }
             finally
             {
                 analyzedArguments.Free();
             }
         }
 
-        private BoundExpression MakeBadExpressionForObjectCreation(ObjectCreationExpressionSyntax node, TypeSymbol type, BoundExpression boundInitializerOpt, AnalyzedArguments analyzedArguments)
+        private BoundExpression MakeBadExpressionForObjectCreation(ObjectCreationExpressionSyntax node, TypeSymbol type, AnalyzedArguments analyzedArguments, DiagnosticBag diagnostics)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: In the case `node.Initializer is null` the `diagnostics` parameter won't be used. Should we assert that it's empty in that case?

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 5]
```diff
@@ -4864,15 +4864,27 @@ private bool IsConstructorAccessible(MethodSymbol constructor, ref HashSet<Diagn
...
             {
-                childNodes.Add(boundInitializerOpt);
+                childNodes.Add(boundInitializerOpt ?? makeBoundInitializerOpt());
             }
 
             return new BoundBadExpression(node, resultKind, symbols.ToImmutableAndFree(), childNodes.ToImmutableAndFree(), type);
+
+            BoundObjectInitializerExpressionBase makeBoundInitializerOpt()
+            {
+                if (initializerSyntaxOpt != null )
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: Nit: space before close paren

**Comment by jaredpar** [comment]
Close / re-open to trigger CI

File: src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs (hunk 3 above)
Comment (chsienki) [reply src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs]: Added OutVarInConstructorUsedInCollectionInitializer

File: src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs (hunk 1 above)
Comment (chsienki) [reply src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs]: Fixed.

File: src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs (hunk 2 above)
Comment (chsienki) [reply src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs]: Fixed.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 4 above)
Comment (chsienki) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: I don't know that it will definitely be empty... It gets passed in from much higher up the stack. All we know is that we wouldn't add anything to it, but the code is simple enough that it seems trivially obvious we haven't changed it in the non-initializer case?

File: src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs [hunk 6]
```diff
@@ -34493,6 +34493,55 @@ public class C
...
+
+    public static void Main()
+    {
+        C c = new C(out var i) { Number = i };
+        System.Console.WriteLine(c.Number);
+    }
+}
+";
+            var compilation = CreateCompilation(source, options: TestOptions.DebugExe, parseOptions: TestOptions.Regular);
+            CompileAndVerify(compilation, expectedOutput: @"1");
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs]: Nit: you could just use `CompileAndVerify`. Not blocking.

Comment (chsienki) [reply src/Compilers/CSharp/Test/Semantic/Semantics/OutVarTests.cs]: Thanks, this was just copy/paste from the other tests. Cleaned up.
