### PR TITLE
Postpone AnalyzerChanged operations when analyzer is changed on file system

### LINKED ISSUE #11019: VisualStudioAnalyzer deadlocks IDE
**Version Used**: master 1.3.0.60502

**Steps to Reproduce**:

1.  Restore project from commandline that has nuget analyzers
2.  Also be working in Visual Studio simultaneously

**Expected Behavior**:

Visual Studio keeps working

**Actual Behavior**:

Visual Studio deadlocks

**Notes:**

filewatcher service calls us and waits:
```
>	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.Services.FileChangeService.AdviseFileChange(string filename, Microsoft.VisualStudio.Shell.Interop._VSFILECHANGEFLAGS filter, Microsoft.VisualStudio.Shell.Interop.IVsFileChangeEvents sink) Line 429	C#
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.Services.FileChangeService.Microsoft.VisualStudio.Shell.Interop.IVsFileChangeEx.AdviseFileChange(string file, uint filter, Microsoft.VisualStudio.Shell.Interop.IVsFileChangeEvents sink, out uint cookie) Line 267	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.FileChangeTracker.StartFileChangeListeningAsync.AnonymousMethod__15_0() Line 74	C#
 	mscorlib.dll!System.Lazy<uint>.CreateValue() Line 437	C#
 	mscorlib.dll!System.Lazy<uint>.LazyInitValue() Line 388	C#
 	mscorlib.dll!System.Lazy<uint>.Value.get() Line 339	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.FileChangeTracker.StartFileChangeListeningAsync.AnonymousMethod__15_1() Line 80	C#
 	mscorlib.dll!System.Threading.Tasks.Task<uint>.InnerInvoke() Line 680	C#
 	mscorlib.dll!System.Threading.Tasks.Task.Execute() Line 2498	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj) Line 2861	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot) Line 2827	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution) Line 2767	C#
 	mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() Line 2704	C#
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 820	C#
 	mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() Line 1161	C#
```

VisualStudioAnalyzer then makes a call to register while the FileChangeTracker is already waiting
```
 	WindowsBase.dll!System.Windows.Threading.DispatcherSynchronizationContext.Wait(System.IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout) Line 108	C#
 	mscorlib.dll!System.Threading.SynchronizationContext.InvokeWaitMethodHelper(System.Threading.SynchronizationContext syncContext, System.IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout) Line 349	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	mscorlib.dll!System.Lazy<uint>.LazyInitValue() Line 386	C#
 	mscorlib.dll!System.Lazy<uint>.Value.get() Line 339	C#
>	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioAnalyzer.VisualStudioAnalyzer(string fullPath, Microsoft.VisualStudio.Shell.Interop.IVsFileChangeEx fileChangeService, Microsoft.VisualStudio.LanguageServices.Implementation.TaskList.HostDiagnosticUpdateSource hostDiagnosticUpdateSource, Microsoft.CodeAnalysis.ProjectId projectId, Microsoft.CodeAnalysis.Workspace workspace, Microsoft.CodeAnalysis.IAnalyzerAssemblyLoader loader, string language) Line 35	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.AddAnalyzerAssembly(string analyzerAssemblyFullPath) Line 31	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject.OnAnalyzerChanged(object sender, System.EventArgs e) Line 580	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioAnalyzer.OnUpdatedOnDisk(object sender, System.EventArgs e) Line 110	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.FileChangeTracker.Microsoft.VisualStudio.Shell.Interop.IVsFileChangeEvents.FilesChanged(uint changeCount, string[] files, uint[] changes) Line 118	C#
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.Services.FileChangeSubscription.Notify.AnonymousMethod__0() Line 219	C#
 	Microsoft.VisualStudio.Shell.14.0.dll!Microsoft.VisualStudio.ErrorHandler.CallWithCOMConvention(System.Func<int> method, bool reportError, bool setShellErrorInfo) Line 165	C#
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.Services.FileChangeSubscription.Notify(Microsoft.VisualStudio.Shell.Interop._VSFILECHANGEFLAGS changes) Line 221	C#
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.Services.FileChangeSubscription.Notify(System.IO.WatcherChangeTypes changeTypes, Microsoft.VisualStudio.Services.FileProperties props) Line 198	C#
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.Services.FileWatcher.Notify(Microsoft.VisualStudio.Services.ChangeStreamDigest digest) Line 353	C#
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.Services.DirectoryWatcher.ProcessFileChanges(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, Microsoft.VisualStudio.Services.ChangeStreamDigest>> digests, int depth) Line 2081	C#
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.Services.DirectoryWatcher.ProcessChanges(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, Microsoft.VisualStudio.Services.ChangeStreamDigest>> digests, int depth) Line 1855	C#
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.Services.DirectoryWatcher.ProcessChanges(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, Microsoft.VisualStudio.Services.ChangeStreamDigest>> digests, int depth) Line 1909	C#
 	Microsoft.VisualStudio.Shell.UI.Internal.dll!Microsoft.VisualStudio.Services.DirectoryWatcher.OnChangedAsync() Line 1566	C#
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs) Line 83	C#
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler) Line 37	C#
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeImpl() Line 583	C#
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state) Line 528	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 891	C#
 	WindowsBase.dll!MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 197	C#
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.Invoke() Line 441	C#
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.ProcessQueue() Line 2232	C#
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.WndProcHook(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled) Line 2485	C#
 	WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled) Line 341	C#
 	WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o) Line 494	C#
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs) Line 104	C#
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler) Line 37	C#
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs) Line 1445	C#
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam) Line 392	C#
```

VS deadlocks

dump available at: \\mlangfs1\public\jmarolf\Dumps\devenv_hang.dmp

### PR DESCRIPTION
**Pull request by natidea**
Fixes #11019 deadlock. See #11019 for more root cause analysis on the deadlock.

This fix postpones the operations in `AnalyzerChanged` handler in `AbstractProject`, to give the main thread time to release the `FileChangeService` lock.

### CODE REVIEW

**Comment by natidea** [comment]
retest vsi please

**Comment by natidea** [comment]
Tag @dotnet/roslyn-analysis for review

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/AbstractProject.cs [hunk 1]
```diff
@@ -581,10 +581,17 @@ private void OnImportChanged(object sender, EventArgs e)
...
-            VisualStudioAnalyzer analyzer = (VisualStudioAnalyzer)sender;
-
-            RemoveAnalyzerAssembly(analyzer.FullPath);
-            AddAnalyzerAssembly(analyzer.FullPath);
+            // Postpone handler's actions to prevent deadlock. This AnalyzeChanged event can
+            // be invoked while the FileChangeService lock is held, and VisualStudioAnalyzer's 
+            // efforts to listen to file changes can lead to a deadlock situation.
+            // Postponing the VisualStudioAnalyzer operations gives this thread the opportunity
+            // to release the lock.
+            Dispatcher.CurrentDispatcher.BeginInvoke(new Action(() => {
```
Comment (heejaechang) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/AbstractProject.cs]: is this operation must happen on UI thread? is the event raised from UI thread?

Comment (natidea) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/AbstractProject.cs]: Yes, this was raised on the UI thread in the stack in #11019. I suppose it may be invoked in a different thread in other scenarios. But doesn't `Dispatcher.CurrentDispatcher` invoke the operation in the current thread? 

I did not want to change the semantics of this method such that its operations could be performed in a different thread.

**Comment by natidea** [comment]
Also tagging @tmeschter

**Comment by heejaechang** [comment]
I guess too hard to add for this code? otherwise, seems fine.

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/AbstractProject.cs (hunk 1 above)
Comment (mavasani) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/AbstractProject.cs]: Change looks good, but I'd like @tmeschter to take a look as well.

**Comment by natidea** [comment]
@tmeschter any comments? I'll check into master and decide whether to integrate into any of the forthcoming releases.

**Comment by tmeschter** [comment]
LGTM.

**Comment by natidea** [comment]
@dotnet-bot retest windows_debug_unit32_prtest please
@dotnet-bot retest windows_debug_unit64_prtest please
@dotnet-bot retest windows_eta_open_prtest please
Failing due to yesterday's network problems. They passed earlier.

**Comment by natidea** [comment]
@dotnet-bot retest vsi please
These last ran 2 weeks ago. Testing again just to be sure.

**Comment by natidea** [comment]
@dotnet-bot retest windows_vsi_p2_open_prtest please
Previous Failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/80/
Filed #11846

**Comment by natidea** [comment]
@dotnet-bot retest windows_vsi_p2_open_prtest please
Previous Failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/84/
