### PR TITLE
Fix Call Hierarchy cross-thread exception when displaying field initializers

### LINKED ISSUE #82125: Call hierarchy does not work with error
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Call-hierarchy-does-not-work-with-error/11028753)._

---
[severity:It's more difficult to complete my work] [regression]

---
#### Feedback Bot on 1/16/2026, 09:15 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

### PR DESCRIPTION
**Pull request by deepakrathore33**
Fixes: https://github.com/dotnet/roslyn/issues/82125

### CODE REVIEW

File: src/VisualStudio/Core/Def/CallHierarchy/CallHierarchyProvider.cs [hunk 1]
```diff
@@ -92,7 +92,7 @@ public FieldInitializerItem CreateInitializerItem(IEnumerable<CallHierarchyDetai
     {
         return new FieldInitializerItem(EditorFeaturesResources.Initializers,
                                         "__" + EditorFeaturesResources.Initializers,
-                                        Glyph.FieldPublic.GetImageSource(GlyphService),
+                                        () => Glyph.FieldPublic.GetImageSource(GlyphService),
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Def/CallHierarchy/CallHierarchyProvider.cs:87]: my preference would be to do what we did with a few other cases in roslyn like this. namely, we just pass GlyphService to FieldInitializerItem.  It then implements DisplayGlyph by calling `Glyph.FieldPublic.GetImageSource(this.GlyphService)`

**Review by CyrusNajmabadi — APPROVED** [review]
Signing off given suggested change is made.  tnx.

File: src/VisualStudio/Core/Def/CallHierarchy/CallHierarchyProvider.cs (hunk 1 above)
Comment (deepakrathore33) [reply src/VisualStudio/Core/Def/CallHierarchy/CallHierarchyProvider.cs:87]: Thanks! Updated to pass GlyphService directly.

File: src/VisualStudio/CSharp/Test/CallHierarchy/CSharpCallHierarchyTests.cs [hunk 2]
```diff
@@ -238,6 +238,27 @@ class C
         testState.VerifyResultName(root, string.Format(EditorFeaturesResources.Calls_To_0, "Goo"), [EditorFeaturesResources.Initializers]);
     }
 
+    [WpfFact, WorkItem("https://github.com/dotnet/roslyn/issues/82125")]
```
Comment (jasonmalinowski) [inline src/VisualStudio/CSharp/Test/CallHierarchy/CSharpCallHierarchyTests.cs]: Did this test correctly catch the failure before? Or since it's involving threading in some way, would only reproduce in an integration test?

File: src/VisualStudio/TestUtilities2/CallHierarchy/CallHierarchyTestState.vb [hunk 3]
```diff
@@ -194,6 +194,22 @@ Namespace Microsoft.CodeAnalysis.Editor.UnitTests.CallHierarchy
             Next
         End Sub
 
+        Friend Sub VerifyResultNameWithGlyph(root As CallHierarchyItem, searchCategory As String, expectedCallers As String(), Optional scope As CallHierarchySearchScope = CallHierarchySearchScope.EntireSolution, Optional documents As IImmutableSet(Of Document) = Nothing)
```
Comment (jasonmalinowski) [inline src/VisualStudio/TestUtilities2/CallHierarchy/CallHierarchyTestState.vb]:
```suggestion
        Friend Sub VerifyResultNameHasGlyph(root As CallHierarchyItem, searchCategory As String, expectedCallers As String(), Optional scope As CallHierarchySearchScope = CallHierarchySearchScope.EntireSolution, Optional documents As IImmutableSet(Of Document) = Nothing)
```

For some reason I expected the "with" to mean we'd actually assert the specific glyph type, but we're not really. Is that just impossible?

**Review by jasonmalinowski — APPROVED** [review]
Approved, but wondering if we need more tests here or not.

**Comment by deepakrathore33** [comment]
You're right removed the test. The threading issue would only show up in real VS, not in unit tests.

**Comment by deadman2000** [comment]
Any progress? I'm still waiting for a fix.

File: src/VisualStudio/Core/Def/CallHierarchy/FieldInitializerItem.cs [hunk 4]
```diff
@@ -4,23 +4,28 @@
...
 {
-    public FieldInitializerItem(string name, string sortText, ImageSource displayGlyph, IEnumerable<CallHierarchyDetail> details)
+    private readonly IGlyphService _glyphService;
+
+    public FieldInitializerItem(string name, string sortText, IGlyphService glyphService, IEnumerable<CallHierarchyDetail> details)
     {
         Name = name;
         SortText = sortText;
-        DisplayGlyph = displayGlyph;
+        _glyphService = glyphService;
```
Comment (JoeRobich) [inline src/VisualStudio/Core/Def/CallHierarchy/FieldInitializerItem.cs]: Could we pass in a `glyphCreator` `Func` instead so that it matches how CallHierarchyItem handles this?

**Review by JoeRobich — APPROVED** [review]
