### PR TITLE
Collection expressions: nullable analysis of spread element expression

### LINKED ISSUE #74667: Missing nullability warning for spreads of maybe-null collections
**Version Used**: 17.11 preview 6

There should be a warning "CS8602 Dereference of a possibly null reference" in the following example, but there is not:

```cs
List<int>? maybeNull = null;
List<int> clone = [.. maybeNull];
```

When this code runs, it throws NullReferenceException.

In both <https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-12.0/collection-expressions#known-length-translation> and <https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-12.0/collection-expressions#unknown-length-translation>, the translation uses `foreach` over the expression being spread, which would equivalently throw:

```cs
foreach (var _ in maybeNull) // Both warns and throws
```

### PR DESCRIPTION
**Pull request by cston**
From https://github.com/dotnet/roslyn/issues/68786:
> - [ ] Spread analysis

Fixes #74667

### CODE REVIEW

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 1]
```diff
@@ -3739,6 +3749,34 @@ static NullableFlowState getResultState(BoundCollectionExpression node, Collecti
...
+            {
+                Debug.Assert(node.ExpressionPlaceholder is { });
+                AddPlaceholderReplacement(node.ExpressionPlaceholder, node.Expression, result);
+                VisitForEachExpression(
+                    node,
+                    node.Conversion,
+                    conversion,
+                    node.ExpressionPlaceholder,
+                    node.EnumeratorInfoOpt,
+                    awaitOpt: null);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3767]: It seems like we aren't looking at the `node.IteratorBody`? Perhaps there isn't a need to do that if things look right in the `VisitForEachExpression` itself?

Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3767]: Good catch, we should be visiting `node.IteratorBody`. Added to the caller.

**Comment by cston** [comment]
@dotnet/roslyn-compiler, please review.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.DebugVerifier.cs [hunk 2]
```diff
@@ -119,7 +119,30 @@ private void VerifyExpression(BoundExpression expression, bool overrideSkippedEx
                     return null;
                 }
 
-                return base.VisitCollectionExpression(node);
+                // See NullableWalker.VisitCollectionExpression.getCollectionDetails() which
+                // does not have an element type for the ImplementsIEnumerable case.
+                var hasElementType = node.CollectionTypeKind is not (CollectionExpressionTypeKind.None or CollectionExpressionTypeKind.ImplementsIEnumerable);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.DebugVerifier.cs:124]: That would be the non-generic IEnumerable case, right? So that's like converting an `object~` element type to the target element type, there's no nullability check that needs to be done there?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.DebugVerifier.cs [hunk 3]
```diff
@@ -119,7 +119,30 @@ private void VerifyExpression(BoundExpression expression, bool overrideSkippedEx
...
+                    {
+                        Visit(spread.Expression);
+                        Visit(spread.Conversion);
+                        if (spread.EnumeratorInfoOpt != null)
+                        {
+                            VisitForEachEnumeratorInfo(spread.EnumeratorInfoOpt);
+                        }
+                        if (hasElementType)
+                        {
+                            Visit(((BoundExpressionStatement?)spread.IteratorBody)?.Expression);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.DebugVerifier.cs:137]: Do we actually need to dig into the expression here, instead of just visiting the statement, for the verifier to pick it up?

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 4]
```diff
@@ -3636,17 +3638,19 @@ protected override void VisitStatement(BoundStatement statement)
...
-                                var completion = VisitOptionalImplicitConversion(spread.ExpressionPlaceholder, elementType,
-                                    useLegacyWarnings: false, trackMembers: false, AssignmentKind.Assignment, delayCompletionForTargetType: true,
-                                    operand => itemState).completion;
-                                Debug.Assert(completion is not null);
-                                elementConversionCompletions.Add(completion);
-                            }
+                            var itemResult = spread.EnumeratorInfoOpt == null ? default : _visitResult;
+                            var iteratorBody = ((BoundExpressionStatement)spread.IteratorBody).Expression;
+                            AddPlaceholderReplacement(spread.ElementPlaceholder, expression: null, itemResult);
+                            var completion = VisitOptionalImplicitConversion(iteratorBody, elementType,
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3649]: It looks like we are assuming the `iteratorBody` is something that would be convertible to the `elementType`? But I thought it could represent a call to a void-returning `Add` method, for example.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 5]
```diff
@@ -3636,17 +3638,19 @@ protected override void VisitStatement(BoundStatement statement)
...
-                                var itemState = spread.EnumeratorInfoOpt == null ? default : ResultType;
-                                var completion = VisitOptionalImplicitConversion(spread.ExpressionPlaceholder, elementType,
-                                    useLegacyWarnings: false, trackMembers: false, AssignmentKind.Assignment, delayCompletionForTargetType: true,
-                                    operand => itemState).completion;
-                                Debug.Assert(completion is not null);
-                                elementConversionCompletions.Add(completion);
-                            }
+                            var itemResult = spread.EnumeratorInfoOpt == null ? default : _visitResult;
+                            var iteratorBody = ((BoundExpressionStatement)spread.IteratorBody).Expression;
+                            AddPlaceholderReplacement(spread.ElementPlaceholder, expression: null, itemResult);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3648]: What's the significance of using a `null` replacement expression here, versus, say, using the same placeholder node as the replacement, which seems to be done in some other places.

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs [hunk 6]
```diff
@@ -3340,9 +3348,17 @@ static void Main()
                     }
                 }
                 """;
-            // https://github.com/dotnet/roslyn/issues/68786: Infer nullability from collection expressions in type inference.
             var comp = CreateCompilation(source);
-            comp.VerifyEmitDiagnostics();
+            comp.VerifyEmitDiagnostics(
+                // (10,44): warning CS8619: Nullability of reference types in value of type 'IEnumerable<string?>' doesn't match target type 'IEnumerable<object>'.
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs:3353]: What is being analyzed to yield this warning? Are we actually converting the `b` to `IEnumerable<object>` before enumerating in the bound tree and warning on that?

**Review by RikkiGibson — COMMENTED** [review]
Done review pass. I was struggling a bit to understand some of the NullableWalker changes.

File: src/Features/CSharp/Portable/Snippets/AbstractCSharpAutoPropertySnippetProvider.cs [hunk 7]
```diff
@@ -64,7 +65,7 @@ protected override async Task<PropertyDeclarationSyntax> GenerateSnippetSyntaxAs
             type: compilation.GetSpecialType(SpecialType.System_Int32).GenerateTypeSyntax(allowVar: false),
             explicitInterfaceSpecifier: null,
             identifier: identifierName.ToIdentifierToken(),
-            accessorList: SyntaxFactory.AccessorList([.. accessors.Where(a => a is not null)!]));
+            accessorList: SyntaxFactory.AccessorList([.. (IEnumerable<AccessorDeclarationSyntax>)accessors.Where(a => a is not null)]));
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Snippets/AbstractCSharpAutoPropertySnippetProvider.cs:68]: why was this needed?

Comment (cston) [reply src/Features/CSharp/Portable/Snippets/AbstractCSharpAutoPropertySnippetProvider.cs:72]: Without the explicit cast, `accessors.Where(a => a is not null)` is considered `IEnumerable<AccessorDeclarationSyntax?>`, and `!` does not suppress the warning from `..`.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.DebugVerifier.cs (hunk 3 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.DebugVerifier.cs:141]: `NullableWalker` only visits the expression within the `BoundExpressionStatement` of `spread.IteratorBody`. (The containing `BoundExpressionStatement` is only there to allow sharing code in binding between `foreach` and `..` since the `foreach` infrastructure expects the body to be a statement.)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 4 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3677]: The `Add()` cases are not handled in this PR. For those cases, `elementType.HasType == false` so we shouldn't reach this code path.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 5 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3676]: Thanks, I didn't realize we used the placeholder as the replacement in other locations. Updated.

File: src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs (hunk 6 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Emit2/Semantics/CollectionExpressionTests.cs]: It looks like the comment refers to `ab = [..a, ..b]` in `TypeInference_Spread_08`.

In that test, `b` has type `IEnumerable<string?>[]` and the target collection has type `IEnumerable<object!>[]`.

`NullableWalker.VisitCollectionExpression` is reporting the warning from the implicit conversion of the *element* of the spread element expression, with type `IEnumerable<string?>`, to the *element type* `IEnumerable<object!>` of the target collection.

File: src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionTests.cs [hunk 8]
```diff
@@ -33373,8 +33389,10 @@ public void SpreadNullability()
                 string[] y2 = [.. x2];
                 """;
 
-            // https://github.com/dotnet/roslyn/issues/68786: We should check the spreads
-            CreateCompilation(src).VerifyEmitDiagnostics();
+            CreateCompilation(src).VerifyEmitDiagnostics(
+                // (5,19): warning CS8602: Dereference of a possibly null reference.
+                // string[] y1 = [.. x1];
+                Diagnostic(ErrorCode.WRN_NullReferenceReceiver, "x1").WithLocation(5, 19));
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionTests.cs:33395]: Parking comment here, but it relates to a test below. I think we can remove the comment in `SpreadNullability_SplitExpression`.

File: src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionTests.cs [hunk 9]
```diff
@@ -42432,6 +42450,258 @@ static void Test(MyCollection a)
...
+        {
+            var source = """
+                #nullable enable
+                using System.Collections.Generic;
+                class Program
+                {
+                    static void Main()
+                    {
+                        IEnumerable<string?> x = [null];
+                        IEnumerable<object> y = [..x];
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionTests.cs:42652]: Consider adding the converse scenario, where the elements are not-null and the target collection allows for null elements:
```
                        IEnumerable<string> x = [""];
                        IEnumerable<object?> y = [..x]; // no warning
```

File: src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionTests.cs [hunk 10]
```diff
@@ -42432,6 +42450,258 @@ static void Test(MyCollection a)
...
+                    }
+                    static void Main()
+                    {
+                        F<int>([1, 2, 3]);
+                    }
+                }
+                """;
+            var comp = CreateCompilation(source);
+            comp.VerifyEmitDiagnostics();
+        }
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionTests.cs:42703]: Do we have a test where the spread operand is more than a simple local? For instance `M(x)`, which could produce nullability warnings of its own.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 8)

File: src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionTests.cs (hunk 10 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionTests.cs:42703]: It looks like the operand in test `Spread_Nullable_09` is not producing warnings of its own. It sounded like Julien was asking for an `F()` which warns about a possible null argument, for example.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.DebugVerifier.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.DebugVerifier.cs:141]: OK, sounds like if we visited the statement here, then we would fail verification because NullableWalker did not also visit that statement.

File: src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionTests.cs (hunk 10 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Emit3/Semantics/CollectionExpressionTests.cs:42703]: Added case.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 11]
```diff
@@ -3767,6 +3779,34 @@ static NullableFlowState getResultState(BoundCollectionExpression node, Collecti
             }
         }
 
+        public override BoundNode? VisitCollectionExpressionSpreadElement(BoundCollectionExpressionSpreadElement node)
+        {
+            VisitRvalue(node.Expression);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3784]: It looks like a case like `var x = [..(int[]?)null]` is handled by the `VisitForEachExpression` itself? Since we would be visiting a loop like `foreach (var elem in (int[]?)null) { ... }`?

File: src/Features/CSharp/Portable/Snippets/AbstractCSharpAutoPropertySnippetProvider.cs (hunk 7 above)
Comment (RikkiGibson) [reply src/Features/CSharp/Portable/Snippets/AbstractCSharpAutoPropertySnippetProvider.cs:72]: It feels like `!` placed on the expression where the warning is reported should suppress that warning. If it is not doing that, we should file a follow-up issue.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 10)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 11 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:3784]: Yes, the top-level nullability of the expression being spread is handled in `VisitForEachExpression()`. For an example test, see `CollectionExpressionTests.SpreadNullability`.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 4 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Thanks. I've renamed `elementType` to `targetElementType`. We can consider adding methods to `BoundCollectionExpressionSpreadElement` as needed in separate PRs.

File: src/Features/CSharp/Portable/Snippets/AbstractCSharpAutoPropertySnippetProvider.cs (hunk 7 above)
Comment (cston) [reply src/Features/CSharp/Portable/Snippets/AbstractCSharpAutoPropertySnippetProvider.cs:72]: https://github.com/dotnet/roslyn/issues/75560
