### PR TITLE
Make change signature more async and remove UI dialogs from the service

### LINKED ISSUE #41121: InvalidOperationException in AbstractChangeSignatureService
Mentioned in https://github.com/dotnet/roslyn/issues/30315#issuecomment-428454397
Things seem to be a little funky here, we probably need to reevaluate how threading should work.

```
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult[T](Task`1 task, CancellationToken cancellationToken) in C:\repos\roslyn\src\Workspaces\Core\Portable\Utilities\TaskExtensions.cs:line 75
   at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.TryCreateUpdatedSolution(ChangeSignatureAnalyzedContext context, ChangeSignatureOptionsResult options, CancellationToken cancellationToken, Solution& updatedSolution) in C:\repos\roslyn\src\Features\Core\Portable\ChangeSignature\AbstractChangeSignatureService.cs:line 209
   at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.ChangeSignatureWithContext(ChangeSignatureAnalyzedContext context, ChangeSignatureOptionsResult options, CancellationToken cancellationToken) in C:\repos\roslyn\src\Features\Core\Portable\ChangeSignature\AbstractChangeSignatureService.cs:line 160
   at Microsoft.CodeAnalysis.ChangeSignature.ChangeSignatureCodeAction.ComputeOperationsAsync(Object options, CancellationToken cancellationToken) in C:\repos\roslyn\src\Features\Core\Portable\ChangeSignature\ChangeSignatureCodeAction.cs:line 33
   at Microsoft.CodeAnalysis.CodeActions.CodeActionWithOptions.<GetOperationsAsync>d__1.MoveNext() in C:\repos\roslyn\src\Workspaces\Core\Portable\CodeActions\CodeActionWithOptions.cs:line 37
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task, CancellationToken cancellationToken) in C:\repos\roslyn\src\Workspaces\Core\Portable\Utilities\TaskExtensions.cs:line 87
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult[T](Task`1 task, CancellationToken cancellationToken) in C:\repos\roslyn\src\Workspaces\Core\Portable\Utilities\TaskExtensions.cs:line 74
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument, IProgressTracker progressTracker, CancellationToken cancellationToken) in C:\repos\roslyn\src\EditorFeatures\Core.Wpf\Suggestions\SuggestedActions\SuggestedAction.cs:line 153
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass18_0.<InvokeCore>b__0() in C:\repos\roslyn\src\EditorFeatures\Core.Wpf\Suggestions\SuggestedActions\SuggestedAction.cs:line 138
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager, Object extension, Action action) in C:\repos\roslyn\src\Workspaces\Core\Portable\ExtensionManager\IExtensionManagerExtensions.cs:line 23
```

### LINKED ISSUE #41783: Add Parameter - more async, less waitandgetresult

### LINKED ISSUE #44198: 'ChangeSignatureCodeRefactoringProvider' encountered an error and has been disabled
```
System.InvalidOperationException : WaitAndGetResult cannot be called from a thread pool thread.
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.TryCreateUpdatedSolution(ChangeSignatureAnalysisSucceededContext context,ChangeSignatureOptionsResult options,CancellationToken cancellationToken,Solution& updatedSolution)
   at Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.ChangeSignatureWithContext(ChangeSignatureAnalysisSucceededContext context,ChangeSignatureOptionsResult options,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ChangeSignature.ChangeSignatureCodeAction.ComputeOperationsAsync(Object options,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CodeActions.CodeActionWithOptions.GetOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass20_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

### PR DESCRIPTION
**Pull request by dibarbet**
When debugging roslyn master, I noticed that change signature was throwing in [TryCreateUpdatedSolution](http://sourceroslyn.io/#Microsoft.CodeAnalysis.Features/ChangeSignature/AbstractChangeSignatureService.cs,269) as it expected to be called on the UI thread.  However, this code path is triggered by [GetOperationsAsync ](http://sourceroslyn.io/#Microsoft.CodeAnalysis.EditorFeatures.Wpf/Suggestions/SuggestedActions/SuggestedAction.cs,83)which is explicitly not running on the UI thread.  The AbstractChangeSignatureService currently uses the UI thread as it pops up error messages and dialog boxes in certain cases.

There are two parts to the change:
1.  Make TryCreateUpdatedSolution (and bits above it) in AbstractChangeSignatureService async.  This is mostly done in 
3c9b43c542b261ecdf9b0cefb86374428152d992, but not quite all (I should have started with 2 first but oh well).
2.  Move the error message /dialog box handling outside of the AbstractChangeSignatureService.  This is done in 
5144713811db716aee3ae3939647b1791accedb1

Note that most of the file changes are replacing WpfFact with Fact, the meat of the changes are in the following files
AbstractChangeSignatureService.cs
ChangeSignatureCodeAction.cs
ChangeSignatureCodeActionOperation.cs
AbstractChangeSignatureCommandHandler.cs

Resolves #44198
Resolves #41121
Resolves #41783

### CODE REVIEW

File: src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs [hunk 1]
```diff
@@ -97,7 +97,7 @@ internal ChangeSignatureResult ChangeSignature(Document document, int position,
             switch (context)
             {
                 case ChangeSignatureAnalysisSucceededContext changeSignatureAnalyzedSucceedContext:
-                    return ChangeSignatureWithContext(changeSignatureAnalyzedSucceedContext, cancellationToken);
+                    return ChangeSignatureWithContextAsync(changeSignatureAnalyzedSucceedContext, cancellationToken).WaitAndGetResult_CanCallOnBackground(cancellationToken);
```
Comment (dibarbet) [inline src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs]: In the next commit, I make this async as well and move the wait up to the command handler

File: src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs [hunk 2]
```diff
@@ -387,7 +385,7 @@ internal ChangeSignatureResult ChangeSignatureWithContext(ChangeSignatureAnalysi
                 var notificationService = context.Solution.Workspace.Services.GetRequiredService<INotificationService>();
                 if (!notificationService.ConfirmMessageBox(FeaturesResources.This_symbol_has_related_definitions_or_references_in_metadata_Changing_its_signature_may_result_in_build_errors_Do_you_want_to_continue, severity: NotificationSeverity.Warning))
```
Comment (dibarbet) [inline src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs]: this is removed in the next commit

**Review by davidwengier — APPROVED** [review]

File: src/EditorFeatures/Core/Implementation/ChangeSignature/AbstractChangeSignatureCommandHandler.cs [hunk 3]
```diff
@@ -68,25 +72,27 @@ private bool ExecuteCommand(ITextView textView, ITextBuffer subjectBuffer, Comma
...
-                        // wait context. That means the command system won't attempt to show its own wait dialog 
-                        // and also will take it into consideration when measuring command handling duration.
-                        context.OperationContext.TakeOwnership();
-                        workspace.Services.GetService<INotificationService>().SendNotification(errorMessage, severity: severity);
-                    },
-                context.OperationContext.UserCancellationToken);
+                    context.OperationContext.UserCancellationToken).WaitAndGetResult(context.OperationContext.UserCancellationToken);
 
+                var notificationService = workspace.Services.GetRequiredService<INotificationService>();
                 if (result == null || !result.Succeeded)
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/ChangeSignature/AbstractChangeSignatureCommandHandler.cs:82]: is result null when we cancel? if so, doc that.

File: src/EditorFeatures/Core/Implementation/ChangeSignature/AbstractChangeSignatureCommandHandler.cs [hunk 4]
```diff
@@ -68,25 +72,27 @@ private bool ExecuteCommand(ITextView textView, ITextBuffer subjectBuffer, Comma
...
                 {
+                    ShowError(result?.CannotChangeSignatureReason, context.OperationContext, notificationService);
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/ChangeSignature/AbstractChangeSignatureCommandHandler.cs:84]: explain what happens if we pass null here.

File: src/EditorFeatures/Core/Implementation/ChangeSignature/AbstractChangeSignatureCommandHandler.cs [hunk 5]
```diff
@@ -68,25 +72,27 @@ private bool ExecuteCommand(ITextView textView, ITextBuffer subjectBuffer, Comma
...
-                    (errorMessage, severity) =>
-                    {
-                        // We are about to show a modal UI dialog so we should take over the command execution
-                        // wait context. That means the command system won't attempt to show its own wait dialog 
-                        // and also will take it into consideration when measuring command handling duration.
-                        context.OperationContext.TakeOwnership();
-                        workspace.Services.GetService<INotificationService>().SendNotification(errorMessage, severity: severity);
-                    },
-                context.OperationContext.UserCancellationToken);
+                    context.OperationContext.UserCancellationToken).WaitAndGetResult(context.OperationContext.UserCancellationToken);
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/ChangeSignature/AbstractChangeSignatureCommandHandler.cs:79]: can you extract all the code below this into a void helper that does the same work.  then after that call, unilaterally return 'true'.  it's just a minfield that every early return below here has to know to return 'true'.

File: src/EditorFeatures/Core/Implementation/ChangeSignature/AbstractChangeSignatureCommandHandler.cs [hunk 6]
```diff
@@ -68,25 +72,27 @@ private bool ExecuteCommand(ITextView textView, ITextBuffer subjectBuffer, Comma
...
+                var notificationService = workspace.Services.GetRequiredService<INotificationService>();
                 if (result == null || !result.Succeeded)
                 {
+                    ShowError(result?.CannotChangeSignatureReason, context.OperationContext, notificationService);
                     return true;
                 }
 
+                if (result.ConfirmationMessage != null)
+                {
+                    if (!notificationService.ConfirmMessageBox(result.ConfirmationMessage, severity: NotificationSeverity.Warning))
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/ChangeSignature/AbstractChangeSignatureCommandHandler.cs:90]:
```suggestion
                if (result.ConfirmationMessage != null &&
                    !notificationService.ConfirmMessageBox(result.ConfirmationMessage, severity: NotificationSeverity.Warning))
```

File: src/EditorFeatures/Core/Implementation/ChangeSignature/AbstractChangeSignatureCommandHandler.cs [hunk 7]
```diff
@@ -126,5 +132,24 @@ private bool ExecuteCommand(ITextView textView, ITextBuffer subjectBuffer, Comma
...
+        {
+            switch (reason)
+            {
+                case CannotChangeSignatureReason.DefinedInMetadata:
+                    ShowMessage(FeaturesResources.The_member_is_defined_in_metadata, NotificationSeverity.Error, operationContext, notificationService);
+                    break;
+                case CannotChangeSignatureReason.IncorrectKind:
+                    ShowMessage(FeaturesResources.You_can_only_change_the_signature_of_a_constructor_indexer_method_or_delegate, NotificationSeverity.Error, operationContext, notificationService);
+                    break;
+            }
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/ChangeSignature/AbstractChangeSignatureCommandHandler.cs:146]: so you don't show an error if tehre is no reason?  i don't like this method :)  plz make the reason non-optional and have the caller decide to call it or not as appropriate.

File: src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs [hunk 8]
```diff
@@ -90,29 +90,16 @@ public async Task<ImmutableArray<ChangeSignatureCodeAction>> GetChangeSignatureC
...
-                            errorHandler(FeaturesResources.You_can_only_change_the_signature_of_a_constructor_indexer_method_or_delegate, NotificationSeverity.Error);
-                            break;
-                    }
-
-                    break;
-            }
-
-            return new ChangeSignatureResult(succeeded: false);
+                ChangeSignatureAnalysisSucceededContext changeSignatureAnalyzedSucceedContext => await ChangeSignatureWithContextAsync(changeSignatureAnalyzedSucceedContext, cancellationToken).ConfigureAwait(false),
+                CannotChangeSignatureAnalyzedContext cannotChangeSignatureAnalyzedContext => new ChangeSignatureResult(succeeded: false, cannotChangeSignatureReason: cannotChangeSignatureAnalyzedContext.CannotChangeSignatureReason),
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs:100]: this result coudl be a static-readonly.  it might be nicer that way as 'new' implies you're creating something fresh with data that is specific to this scenario.  but this really is a standard result you return that doesn't change in any circumstances.

File: src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs [hunk 9]
```diff
@@ -200,21 +187,21 @@ internal ChangeSignatureResult ChangeSignature(Document document, int position,
...
+            return ChangeSignatureWithContextAsync(context, options, cancellationToken);
         }
 
-        internal ChangeSignatureResult ChangeSignatureWithContext(ChangeSignatureAnalysisSucceededContext context, ChangeSignatureOptionsResult options, CancellationToken cancellationToken)
+        internal async Task<ChangeSignatureResult> ChangeSignatureWithContextAsync(ChangeSignatureAnalysisSucceededContext context, ChangeSignatureOptionsResult options, CancellationToken cancellationToken)
         {
-            var succeeded = TryCreateUpdatedSolution(context, options, cancellationToken, out var updatedSolution);
-            return new ChangeSignatureResult(succeeded, updatedSolution, context.Symbol.ToDisplayString(), context.Symbol.GetGlyph(), options.PreviewChanges);
+            var (updatedSolution, confirmationMessage) = await CreateUpdatedSolutionAsync(context, options, cancellationToken).ConfigureAwait(false);
+            return new ChangeSignatureResult(updatedSolution != null, updatedSolution, context.Symbol.ToDisplayString(), context.Symbol.GetGlyph(), options.PreviewChanges, confirmationMessage: confirmationMessage);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs:204]: instead of `updatedSolution != null` here, can teh constructor of ChangeSignatureResult just do that itself?

File: src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs [hunk 10]
```diff
@@ -382,22 +367,13 @@ internal ChangeSignatureResult ChangeSignatureWithContext(ChangeSignatureAnalysi
...
             }
 
-            if (hasLocationsInMetadata)
-            {
-                var notificationService = context.Solution.Workspace.Services.GetRequiredService<INotificationService>();
-                if (!notificationService.ConfirmMessageBox(FeaturesResources.This_symbol_has_related_definitions_or_references_in_metadata_Changing_its_signature_may_result_in_build_errors_Do_you_want_to_continue, severity: NotificationSeverity.Warning))
-                {
-                    return false;
-                }
-            }
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs:392]: sooooooooooooooooo much nicer.

File: src/Features/Core/Portable/ChangeSignature/ChangeSignatureCodeActionOperation.cs [hunk 11]
```diff
@@ -0,0 +1,55 @@
...
+        /// </summary>
+        internal override bool TryApply(
+            Workspace workspace, IProgressTracker progressTracker, CancellationToken cancellationToken)
+        {
+            if (ConfirmationMessage != null)
+            {
+                var notificationService = workspace.Services.GetRequiredService<INotificationService>();
+                if (!notificationService.ConfirmMessageBox(ConfirmationMessage, severity: NotificationSeverity.Warning))
+                {
+                    return false;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ChangeSignature/ChangeSignatureCodeActionOperation.cs:48]: what does returning false do here higher up the chain?

File: src/Features/Core/Portable/ChangeSignature/ChangeSignatureResult.cs [hunk 12]
```diff
@@ -12,19 +12,30 @@ internal sealed class ChangeSignatureResult
...
         public string? Name { get; }
 
-        public ChangeSignatureResult(bool succeeded, Solution? updatedSolution = null, string? name = null, Glyph? glyph = null, bool previewChanges = false)
+        public ChangeSignatureResult(
+            bool succeeded,
+            Solution? updatedSolution = null,
+            string? name = null,
+            Glyph? glyph = null,
+            bool previewChanges = false,
+            CannotChangeSignatureReason? cannotChangeSignatureReason = null,
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ChangeSignature/ChangeSignatureResult.cs:29]: fwiw i think ChangeSignatureFailureReason or ChangeSignatureFailureKind or ChangeSignatureFailureREsult are better names for `Cannot...Reason`.

**Review by CyrusNajmabadi — COMMENTED** [review]
Overall LGTM.  But def a few things i'd like tweaked before i sign off.  but this is sooo much better :)

File: src/EditorFeatures/Core/Implementation/ChangeSignature/AbstractChangeSignatureCommandHandler.cs (hunk 3 above)
Comment (dibarbet) [reply src/EditorFeatures/Core/Implementation/ChangeSignature/AbstractChangeSignatureCommandHandler.cs]: it's nullable annotated to not return null - removed the check

File: src/EditorFeatures/Core/Implementation/ChangeSignature/AbstractChangeSignatureCommandHandler.cs (hunk 4 above)
Comment (dibarbet) [reply src/EditorFeatures/Core/Implementation/ChangeSignature/AbstractChangeSignatureCommandHandler.cs]: made it non-nullable

File: src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs (hunk 9 above)
Comment (dibarbet) [reply src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs:206]: I could potentially, but there are many cases where we explicitly create a failure result and don't pass in any solution (we just pass succeeded: false).  I could modify it to just pass a null solution, but I'm not sure if that's much better

File: src/Features/Core/Portable/ChangeSignature/ChangeSignatureCodeActionOperation.cs (hunk 11 above)
Comment (dibarbet) [reply src/Features/Core/Portable/ChangeSignature/ChangeSignatureCodeActionOperation.cs:48]: So I dug around a bit, and not much.  As best I can tell it's used only in integration tests to confirm if the code action application succeeded or not - http://sourceroslyn.io/#Microsoft.VisualStudio.IntegrationTest.Utilities/InProcess/TextViewWindow_InProc.cs,423

This behavior seems to match the other operations (e.g. InstallPackageAndAddImportOperation, InstallPackageDirectlyCodeActionOoperation)

File: src/EditorFeatures/Core/Implementation/ChangeSignature/AbstractChangeSignatureCommandHandler.cs [hunk 13]
```diff
@@ -70,62 +71,86 @@ private bool ExecuteCommand(ITextView textView, ITextBuffer subjectBuffer, Comma
...
+            if (finalSolution == null)
+            {
+                // User clicked cancel.
+                return;
+            }
+
+            if (workspace.TryApplyChanges(finalSolution))
+            {
+                using var workspaceUndoTransaction = workspace.OpenGlobalUndoTransaction(FeaturesResources.Change_signature);
+                workspaceUndoTransaction.Commit();
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/ChangeSignature/AbstractChangeSignatureCommandHandler.cs:132]: i literally don't know waht this is doing.  If i'm reading it right, it's saying:

try to update the solution.  If that succeeds, open a transaction and then immediately commit the empty transaction.

I have no idea what the purpose of the transaction is.  @jasonmalinowski how is that supposed to work?

File: src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs [hunk 14]
```diff
@@ -88,29 +90,16 @@ public async Task<ImmutableArray<ChangeSignatureCodeAction>> GetChangeSignatureC
...
-                            break;
-                    }
-
-                    break;
-            }
-
-            return new ChangeSignatureResult(succeeded: false);
+                ChangeSignatureAnalysisSucceededContext changeSignatureAnalyzedSucceedContext => await ChangeSignatureWithContextAsync(changeSignatureAnalyzedSucceedContext, cancellationToken).ConfigureAwait(false),
+                CannotChangeSignatureAnalyzedContext cannotChangeSignatureAnalyzedContext => new ChangeSignatureResult(succeeded: false, changeSignatureFailureKind: cannotChangeSignatureAnalyzedContext.CannotChangeSignatureReason),
+                _ => s_ChangeSignatureResultFailure,
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs:101]: is this branch reachable?

File: src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs (hunk 9 above)
Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs:204]: ok.  i don't love this.  but it's not a big deal :)

File: src/Features/Core/Portable/ChangeSignature/ChangeSignatureCodeActionOperation.cs [hunk 15]
```diff
@@ -0,0 +1,55 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+// See the LICENSE file in the project root for more information.
+
+#nullable enable
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ChangeSignature/ChangeSignatureCodeActionOperation.cs:5]:
```suggestion
```

File: src/Features/Core/Portable/ChangeSignature/ChangeSignatureCodeActionOperation.cs [hunk 16]
```diff
@@ -0,0 +1,55 @@
...
+        /// <summary>
+        /// Show the confirmation message, if available, before attempting to apply the changes.
+        /// </summary>
+        internal override bool TryApply(
+            Workspace workspace, IProgressTracker progressTracker, CancellationToken cancellationToken)
+        {
+            if (ConfirmationMessage != null)
+            {
+                var notificationService = workspace.Services.GetRequiredService<INotificationService>();
+                if (!notificationService.ConfirmMessageBox(ConfirmationMessage, severity: NotificationSeverity.Warning))
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ChangeSignature/ChangeSignatureCodeActionOperation.cs:46]: this is a bit weird.  how does thi work during preview?  won't this pop up and cause all sorts of issues?

**Review by CyrusNajmabadi — COMMENTED** [review]
still some questions.

File: src/EditorFeatures/Core/Implementation/ChangeSignature/AbstractChangeSignatureCommandHandler.cs (hunk 13 above)
Comment (dibarbet) [reply src/EditorFeatures/Core/Implementation/ChangeSignature/AbstractChangeSignatureCommandHandler.cs:132]: woops I think that's a bad merge.. will fix

File: src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs (hunk 14 above)
Comment (dibarbet) [reply src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs:101]: Yeah, I get a warning without it, but I'm not exactly sure how it could be reached

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs:101]: `_ => throw ExceptionUtilities.Unreachable(...);`

File: src/Features/Core/Portable/ChangeSignature/ChangeSignatureCodeActionOperation.cs (hunk 16 above)
Comment (dibarbet) [reply src/Features/Core/Portable/ChangeSignature/ChangeSignatureCodeActionOperation.cs:44]: @CyrusNajmabadi interesting answer-

So from testing, in normal VS without these changes I cannot get preview to show up at all for change signature invoked via a code action.  I think that's probably a bug, unless it was disabled for code actions for some other reason.  If it should be showing preview, I can make a separate preview handling method here to not show the notification, but I'll have to dig tomorrow to figure out why preview isn't working in roslyn master first.

If I invoke via the command handling (cntrl R, cntrl V) then what happens is the same as before this change - the confirmation box pops up before the preview box (and hitting no cancels)

Comment (davidwengier) [reply src/Features/Core/Portable/ChangeSignature/ChangeSignatureCodeActionOperation.cs:44]: > I think that's probably a bug

https://github.com/dotnet/roslyn/issues/4608

Comment (dibarbet) [reply src/Features/Core/Portable/ChangeSignature/ChangeSignatureCodeActionOperation.cs:44]: I investigated this a bit today.  So it looks like the code action was never written with handling preview in mind.

I attempted to implement preview via the [IPreviewDialogService](http://sourceroslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Host/IPreviewDialogService.cs,9668af67b8157caa), but it lives in the editor features layer while the code refactoring provider (+ service and operations) live in Features.  So that definition needs to move down or I need something to move the code action impl up to editor features (via some service as I don't want to entirely move change signature service up).  

I think that is a bit tangential to this PR so I'd like to move forward with the current behavior here (dialog shows when applying the code action as before).

File: src/Features/Core/Portable/ChangeSignature/CannotChangeSignatureReason.cs [hunk 17]
```diff
@@ -6,7 +6,7 @@
 
 namespace Microsoft.CodeAnalysis.ChangeSignature
 {
-    internal enum CannotChangeSignatureReason
+    internal enum ChangeSignatureFailureKind
```
Comment (jasonmalinowski) [inline src/Features/Core/Portable/ChangeSignature/CannotChangeSignatureReason.cs:9]: Don't forget to update the file name.

**Comment by jasonmalinowski** [comment]
@dibarbet: I think this will close these bugs, right?

https://github.com/dotnet/roslyn/issues/44198
https://github.com/dotnet/roslyn/issues/41121

It looks like we may have changed the offending WaitAndGetResult to a _CanCallOnBackground but you've cleaned it up properly now.

File: src/EditorFeatures/Core/Implementation/ChangeSignature/AbstractChangeSignatureCommandHandler.cs [hunk 18]
```diff
@@ -70,62 +71,86 @@ private bool ExecuteCommand(ITextView textView, ITextBuffer subjectBuffer, Comma
...
-                        context.OperationContext.TakeOwnership();
-                        workspace.Services.GetService<INotificationService>().SendNotification(errorMessage, severity: severity);
-                    },
-                context.OperationContext.UserCancellationToken);
-
-                if (result == null || !result.Succeeded)
-                {
-                    return true;
-                }
+                    context.OperationContext.UserCancellationToken).WaitAndGetResult(context.OperationContext.UserCancellationToken);
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/Implementation/ChangeSignature/AbstractChangeSignatureCommandHandler.cs:78]: So where in this process does the options dialog get displayed? Because now that this is async, how are we getting back to the UI thread to display the dialog? Does this need a JTF-friendly wait here as opposed to WaitAndGetResult?

Comment (dibarbet) [reply src/EditorFeatures/Core/Implementation/ChangeSignature/AbstractChangeSignatureCommandHandler.cs:78]: @jasonmalinowski see the HandleResult method that runs after this WaitAndGetResult
https://github.com/dotnet/roslyn/pull/47768/files#diff-becc7ba48505ea7db15e854f845d4702e0d44964ec9a05d20b65c26572049596R86
The service just returns the failure kind and doesn't do any UI thread operations, so WaitAndGetResult is fine.  Then since we're already on the UI thread, HandleResult can just display the notification without any switching.

Comment (dibarbet) [reply src/EditorFeatures/Core/Implementation/ChangeSignature/AbstractChangeSignatureCommandHandler.cs:78]: And to add to that - the preview window is also part of HandleResult.  If the result has preview changes then it will use the preview service to display them from the UI thread.

**Comment by dibarbet** [comment]
> 
> 
> @dibarbet: I think this will close these bugs, right?
> 
> #44198
> #41121
> 
> It looks like we may have changed the offending WaitAndGetResult to a _CanCallOnBackground but you've cleaned it up properly now.

Yes it will!  Updated the PR description.

**Comment by allisonchou** [comment]
@dibarbet I think this may also resolve #41783

File: src/Features/Core/Portable/ChangeSignature/ChangeSignatureCodeAction.cs [hunk 19]
```diff
@@ -26,19 +29,19 @@ public ChangeSignatureCodeAction(AbstractChangeSignatureService changeSignatureS
...
         {
             if (options is ChangeSignatureOptionsResult changeSignatureOptions && changeSignatureOptions != null)
             {
-                var changeSignatureResult = _changeSignatureService.ChangeSignatureWithContext(_context, changeSignatureOptions, cancellationToken);
+                var changeSignatureResult = await _changeSignatureService.ChangeSignatureWithContextAsync(_context, changeSignatureOptions, cancellationToken).ConfigureAwait(false);
 
                 if (changeSignatureResult.Succeeded)
                 {
-                    return Task.FromResult(SpecializedCollections.SingletonEnumerable<CodeActionOperation>(new ApplyChangesOperation(changeSignatureResult.UpdatedSolution!)));
+                    return SpecializedCollections.SingletonEnumerable<CodeActionOperation>(new ChangeSignatureCodeActionOperation(changeSignatureResult.UpdatedSolution!, changeSignatureResult.ConfirmationMessage));
```
Comment (jasonmalinowski) [inline src/Features/Core/Portable/ChangeSignature/ChangeSignatureCodeAction.cs:40]:
```suggestion
                    return SpecializedCollections.SingletonEnumerable<CodeActionOperation>(new ChangeSignatureCodeActionOperation(changeSignatureResult.UpdatedSolution, changeSignatureResult.ConfirmationMessage));
```

You should be enable to annotate this now with the member not null stuff.

File: src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs [hunk 20]
```diff
@@ -198,30 +171,39 @@ internal ChangeSignatureResult ChangeSignature(Document document, int position,
...
 
         /// <returns>Returns <c>null</c> if the operation is cancelled.</returns>
-        internal static ChangeSignatureOptionsResult? GetChangeSignatureOptions(ChangeSignatureAnalysisSucceededContext context)
+        internal static ChangeSignatureOptionsResult? GetChangeSignatureOptions(ChangeSignatureAnalyzedContext context)
         {
-            var changeSignatureOptionsService = context.Solution.Workspace.Services.GetRequiredService<IChangeSignatureOptionsService>();
+            if (context is not ChangeSignatureAnalysisSucceededContext succeededContext)
+            {
+                return null;
+            }
```
Comment (jasonmalinowski) [inline src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs:201]: It feels a bit strange that the callers don't just check for the failure and immediately abort.

File: src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs [hunk 21]
```diff
@@ -81,39 +79,14 @@ internal abstract class AbstractChangeSignatureService : ILanguageService
 
         public async Task<ImmutableArray<ChangeSignatureCodeAction>> GetChangeSignatureCodeActionAsync(Document document, TextSpan span, CancellationToken cancellationToken)
```
Comment (jasonmalinowski) [inline src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs:80]: I admit I'm surprised this function is here versus just being inlined into the actual code fix provider. Not urgent to fix though.

File: src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs [hunk 22]
```diff
@@ -248,23 +230,21 @@ internal ChangeSignatureResult ChangeSignatureWithContext(ChangeSignatureAnalysi
 
 #nullable enable
```
Comment (jasonmalinowski) [inline src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs:231]: Is there anything left in this file that isn't #nullable enabled or isn't easily updated?

File: src/Features/Core/Portable/ChangeSignature/ChangeSignatureCodeAction.cs [hunk 23]
```diff
@@ -26,19 +29,19 @@ public ChangeSignatureCodeAction(AbstractChangeSignatureService changeSignatureS
         public override object? GetOptions(CancellationToken cancellationToken)
             => AbstractChangeSignatureService.GetChangeSignatureOptions(_context);
 
-        protected override Task<IEnumerable<CodeActionOperation>> ComputeOperationsAsync(object options, CancellationToken cancellationToken)
+        protected override async Task<IEnumerable<CodeActionOperation>> ComputeOperationsAsync(object options, CancellationToken cancellationToken)
         {
             if (options is ChangeSignatureOptionsResult changeSignatureOptions && changeSignatureOptions != null)
```
Comment (jasonmalinowski) [inline src/Features/Core/Portable/ChangeSignature/ChangeSignatureCodeAction.cs:34]:
```suggestion
            if (options is ChangeSignatureOptionsResult changeSignatureOptions)
```

If the first test is true, it can't be null.

**Review by jasonmalinowski — APPROVED** [review]
Looks good, or at least much better than what was there. I can't say I care for the pattern where the GetOptions() call runs even if the analysis fails and returns null, and then the actual refactoring operation runs even if options are null and then returns a different failure object. It seems like we're having to propogate failures when instead we could have stopped earlier and not had to have code dealing with failure modes. I'm happy for that to be addressed in a follow-up PR though (or not, if it makes a mess of something else) since this is a vast improvement for what's there.

**Comment by dibarbet** [comment]
merging, will address small feedback in followup
