### PR TITLE
Ensure we don't free metadata from under skeleton assemblies

### LINKED ISSUE #13243: [Test Failure] AV in Roslyn.Services.Editor.UnitTests2.dll
test failure
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/2694/

there seems an issue with metadata reader

 Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
15:26:22      at System.Reflection.Metadata.Ecma335.TypeDefTableReader.GetExtends(TypeDefinitionHandle handle)
15:26:22      at Microsoft.CodeAnalysis.PEModule.GetBaseTypeOfTypeOrThrow(TypeDefinitionHandle typeDef) in q:\roslyn\src\Compilers\Core\Portable\MetadataReader\PEModule.cs:line 860
15:26:22      at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.MakeDeclaredBaseType() in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\Metadata\PE\PENamedTypeSymbol.cs:line 429
15:26:22      at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.GetDeclaredBaseType(ConsList`1 basesBeingResolved) in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\Metadata\PE\PENamedTypeSymbol.cs:line 406
15:26:22      at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamedTypeSymbol.get_TypeKind() in q:\roslyn\src\Compilers\CSharp\Portable\Symbols\Metadata\PE\PENamedTypeSymbol.cs:line 1603

### PR DESCRIPTION
**Pull request by jasonmalinowski**
When we create skeleton assembly references, we back them by temporary memory out of our ITemporaryStorage service. We used a ConditionalWeakTable to ensure that if the reference was held alive that the underlying memory wouldn't disappear. This was subtly incorrect. If you had a PE symbol from such a compilation, the compilation is not held alive, and the metadata reference could be freed but the metadata (which is held by the symbol) could still be held. This meant we'd free the memory too early and crash.

The fix is simple: root the memory by the metadata object, not the metadata reference.

Fixes #13243.

*Review*: @dotnet/roslyn-ide, @heejaechang, @jaredpar, @tmat

### CODE REVIEW

File: src/Workspaces/Core/Portable/Workspace/Solution/MetadataOnlyImage.cs [hunk 1]
```diff
@@ -8,6 +8,7 @@
 using Microsoft.CodeAnalysis.Host;
 using Microsoft.CodeAnalysis.Internal.Log;
 using Roslyn.Utilities;
+using System;
```
Comment (heejaechang) [inline src/Workspaces/Core/Portable/Workspace/Solution/MetadataOnlyImage.cs]: using?

Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Workspace/Solution/MetadataOnlyImage.cs]: Sort

File: src/Workspaces/Core/Portable/Workspace/Solution/MetadataOnlyImage.cs [hunk 2]
```diff
@@ -78,7 +79,11 @@ public static MetadataOnlyImage Create(Workspace workspace, ITemporaryStorageSer
             return Empty;
         }
 
-        private static readonly ConditionalWeakTable<MetadataReference, Stream> s_lifetime = new ConditionalWeakTable<MetadataReference, Stream>();
+        /// <summary>
+        /// A map to ensure that the streams from the temporary storage service that back the metadata we create stay alive as long
+        /// as the metadata is alive.
+        /// </summary>
+        private static readonly ConditionalWeakTable<AssemblyMetadata, ISupportDirectMemoryAccess> s_lifetime = new ConditionalWeakTable<AssemblyMetadata, ISupportDirectMemoryAccess>();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Workspace/Solution/MetadataOnlyImage.cs]: wrap long lines (both the comment and initializer plz).

**Comment by heejaechang** [comment]
👍

File: src/Workspaces/Core/Portable/Workspace/Solution/MetadataOnlyImage.cs [hunk 3]
```diff
@@ -97,18 +102,15 @@ public MetadataReference CreateReference(ImmutableArray<string> aliases, bool em
                 // give them pointer to the native memory. also we need to handle lifetime ourselves.
                 var metadata = AssemblyMetadata.Create(ModuleMetadata.CreateFromImage(supportNativeMemory.GetPointer(), (int)stream.Length));
 
-                var referenceWithNativeMemory = metadata.GetReference(
+                // Tie lifetime of stream to metadata we created. It is important to tie this to the Metadata and not the
+                // metadata reference, as PE symbols hold onto just the Metadata.
+                s_lifetime.Add(metadata, supportNativeMemory);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Workspace/Solution/MetadataOnlyImage.cs]: is there a race condition concern here?  .Add will throw if two people try to do this.  And isn't this code all free threaded?  shouild we be locking anywhere here?

Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Workspace/Solution/MetadataOnlyImage.cs]: Note that below we called GEtValue, allowing one thread to 'win'.  I have no idea the semantics we want here.  But i'm feeling like a lock is in order to make ownership/lifetime very clear.

Comment (heejaechang) [inline src/Workspaces/Core/Portable/Workspace/Solution/MetadataOnlyImage.cs]: metadata is new object created above. there can't be 2 same metadata

File: src/Workspaces/Core/Portable/Workspace/Solution/MetadataOnlyImage.cs (hunk 2 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Workspace/Solution/MetadataOnlyImage.cs]: I have the chrome extension :)  This still goes wider than my screen :)

File: src/Workspaces/Core/Portable/Workspace/Solution/MetadataOnlyImage.cs (hunk 3 above)
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Workspace/Solution/MetadataOnlyImage.cs]: Indeed, we created a new object a few lines above, so there can't be a race here. I'm switching it to an Add to save the cost of the closure.

**Comment by CyrusNajmabadi** [comment]
👍

**Comment by tmat** [comment]
👍

File: src/Workspaces/Core/Portable/Workspace/Solution/MetadataOnlyImage.cs [hunk 4]
```diff
@@ -97,18 +103,16 @@ public MetadataReference CreateReference(ImmutableArray<string> aliases, bool em
                 // give them pointer to the native memory. also we need to handle lifetime ourselves.
                 var metadata = AssemblyMetadata.Create(ModuleMetadata.CreateFromImage(supportNativeMemory.GetPointer(), (int)stream.Length));
 
-                var referenceWithNativeMemory = metadata.GetReference(
+                // Tie lifetime of stream to metadata we created. It is important to tie this to the Metadata and not the
+                // metadata reference, as PE symbols hold onto just the Metadata. We can use Add here since we created
+                // a brand new object in AssemblyMetadata.Create above.
+                s_lifetime.Add(metadata, supportNativeMemory);
+
+                return metadata.GetReference(
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Workspace/Solution/MetadataOnlyImage.cs]: Good call. Updated.

**Comment by CyrusNajmabadi** [comment]
I'm going to start coding on a tablet.  Then all code must be no longer than 40 characters wide!

**Comment by tmat** [comment]
Why tablet? If you wanna suffer code on Watch ;)
