### PR TITLE
Dont Case Correct Identifier to Symbols that the identifier cannot bind

### LINKED ISSUE #1949: Pretty lister changes case of unresolvable types
Consider the following code snippet:

``` vb
Dim outputKind as OutputKind = OutputKind.ConsoleApplication
```

In the case where `OutputKind` is unresolvable (has a squiggle) any pretty listing of that line will change the output to:

``` vb
Dim outputKind as outputKind = outputKind.ConsoleApplication
```

This makes editing code not feasible with the build is in a broken state.

### PR DESCRIPTION
**Pull request by basoundr**
Fix #1949 : Identifiers in the TypeOrNamespace context should not be
case corrected by binding the identifier to any random symbol like
locals, parameters, properties and others.

### CODE REVIEW

**Comment by basoundr** [comment]
Reviewers: @Pilchie @jasonmalinowski @dpoeschl @rchande @balajikris @brettfo

File: src/EditorFeatures/VisualBasicTest/CaseCorrecting/CaseCorrectionServiceTests.vb [hunk 1]
```diff
@@ -841,6 +841,24 @@ End Class
             Test(input, expected)
         End Sub
 
+        <WorkItem(1949, "https://github.com/dotnet/roslyn/issues/1949")>
+        <Fact, Trait(Traits.Feature, Traits.Features.CaseCorrection)>
+        Public Sub TestUnResolvedTypeDoesNotBindToAnyAccessibileSymbol()
```
Comment (balajikris) [inline src/EditorFeatures/VisualBasicTest/CaseCorrecting/CaseCorrectionServiceTests.vb]: Nit: typo 'Accessible'

File: src/Workspaces/VisualBasic/Portable/CaseCorrection/VisualBasicCaseCorrectionService.Rewriter.vb [hunk 2]
```diff
@@ -150,6 +155,12 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.CaseCorrection
                 Return CaseCorrectIdentifierIfNamesDiffer(token, newToken, symbol)
             End Function
 
+            Private Shared Function IsNamespaceOrTypeRelatedSymbol(symbol As ISymbol) As Boolean
+                Return TypeOf symbol Is INamespaceOrTypeSymbol OrElse
+                    (TypeOf symbol Is IAliasSymbol AndAlso TypeOf DirectCast(symbol, IAliasSymbol).Target Is INamespaceOrTypeSymbol) OrElse
+                    (symbol.IsKind(SymbolKind.Method) AndAlso DirectCast(symbol, IMethodSymbol).MethodKind = MethodKind.Constructor)
```
Comment (jasonmalinowski) [inline src/Workspaces/VisualBasic/Portable/CaseCorrection/VisualBasicCaseCorrectionService.Rewriter.vb]: Why the constructor check since constructors in VB are not named by class name?

File: src/EditorFeatures/VisualBasicTest/CaseCorrecting/CaseCorrectionServiceTests.vb [hunk 3]
```diff
@@ -841,6 +841,24 @@ End Class
             Test(input, expected)
         End Sub
 
+        <WorkItem(1949, "https://github.com/dotnet/roslyn/issues/1949")>
+        <Fact, Trait(Traits.Feature, Traits.Features.CaseCorrection)>
```
Comment (jasonmalinowski) [inline src/EditorFeatures/VisualBasicTest/CaseCorrecting/CaseCorrectionServiceTests.vb]: Additional tests for the alias branches included in the code?

Comment (basoundr) [inline src/EditorFeatures/VisualBasicTest/CaseCorrecting/CaseCorrectionServiceTests.vb]: Alias tests are already included in the code

File: src/Workspaces/VisualBasic/Portable/CaseCorrection/VisualBasicCaseCorrectionService.Rewriter.vb (hunk 2 above)
Comment (basoundr) [inline src/Workspaces/VisualBasic/Portable/CaseCorrection/VisualBasicCaseCorrectionService.Rewriter.vb]: That and for Attributes.

Eg: Attributes,
```VB
Class SampleAttribute
    inherits Attribute
End Class

<sample>
Class D
End Class
```

```VB
Class SampleAttribute
    inherits Attribute
End Class

<Sample>
Class D
End Class
```

We have tests for these cases as well in the code.

**Comment by basoundr** [comment]
Reviewers: @Pilchie @jasonmalinowski @dpoeschl @rchande @balajikris @brettfo

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by Pilchie** [comment]
:+1:
