### PR TITLE
Handle different extensions specified as output name to vbc

### LINKED ISSUE #13681: VB Compiler outputs to a different binary than the one passed through outputpath in certain cases.
**Version Used**: 

**Steps to Reproduce**:
1. Invoke vbc with `vbc foo.vb /t:exe /o:foo.dll`

**Expected Behavior**: Since the output path is specified as foo.dll, the expectation is that there's a foo.dll on disk.

**Actual Behavior**: It outputs a foo.dll.exe because the target is a exe. 

.NET Core executables are output as dlls by default because they are run by a different host. Supporting that will require a post-process step which is brittle.

### PR DESCRIPTION
**Pull request by OmarTawfik**
Fixes #13681

### CODE REVIEW

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-compiler

File: docs/compilers/Visual Basic/Compiler Breaking Changes.md [hunk 1]
```diff
@@ -0,0 +1,8 @@
+**This document lists known breaking changes in Roslyn (VS2015+) from the native VB compiler (VS2013 and previous).**
+
+*Breaks are formatted with a monotonically increasing numbered list to allow them to referenced via shorthand (i.e., "known break #1").
+Each entry should include a short description of the break, followed by either a link to the issue describing the full details of the break or the full details of the break inline.*
+
+1. When specifying the output extension as one of the known output types (example /out:foo.dll), but specifying a different target type
+   (example /t:exe) the compiler will now keep the specified extension and won't add the target extension (example foo.dll.exe). See
```
Comment (jaredpar) [inline docs/compilers/Visual Basic/Compiler Breaking Changes.md]: CC @AnthonyDGreen for a quick look at this.

File: src/Compilers/VisualBasic/Test/CommandLine/CommandLineTests.vb [hunk 2]
```diff
@@ -7944,6 +7944,39 @@ End Class
             Next
         End Sub
 
+        <WorkItem(13681, "https://github.com/dotnet/roslyn/issues/13681")>
+        <Theory()>
+        <InlineData("/t:exe", "/out:foo.dll", "foo.dll", "foo.dll.exe")>    'Output with known but different extension
+        <InlineData("/t:exe", "/out:foo.txt", "foo.txt.exe", "foo.exe")>    'Output with unknown extension
+        <InlineData("/t:exe", "/out:foo", "foo.exe", "foo")>                'Output without extension
+        <InlineData("/t:exe", "/out:foo.exe", "foo.exe", "foo.exe.exe")>    'Output with correct extension
```
Comment (jaredpar) [inline src/Compilers/VisualBasic/Test/CommandLine/CommandLineTests.vb]: Please add `InlineData` entries for other targets that just EXE.

File: src/Compilers/VisualBasic/Test/CommandLine/CommandLineTests.vb [hunk 3]
```diff
@@ -7944,6 +7944,39 @@ End Class
             Next
         End Sub
 
+        <WorkItem(13681, "https://github.com/dotnet/roslyn/issues/13681")>
+        <Theory()>
+        <InlineData("/t:exe", "/out:foo.dll", "foo.dll", "foo.dll.exe")>    'Output with known but different extension
```
Comment (jaredpar) [inline src/Compilers/VisualBasic/Test/CommandLine/CommandLineTests.vb]: What happens in the case where the file is just an extension?  For example:

```
/t:dll /out:.exe 
```

File: src/Compilers/VisualBasic/Portable/CommandLine/VisualBasicCommandLineParser.vb [hunk 4]
```diff
@@ -2216,10 +2216,12 @@ lVbRuntimePlus:
                         outputFileName = outputFileName & ".netmodule"
                     End If
                 Else
-                    Dim defaultExtension As String = kind.GetDefaultExtension()
-                    If Not String.Equals(ext, defaultExtension, StringComparison.OrdinalIgnoreCase) Then
+                    If Not ext.EndsWith(".exe", StringComparison.OrdinalIgnoreCase) And
+                        Not ext.EndsWith(".dll", StringComparison.OrdinalIgnoreCase) And
+                        Not ext.EndsWith(".netmodule", StringComparison.OrdinalIgnoreCase) And
+                        Not ext.EndsWith(".winmdobj", StringComparison.OrdinalIgnoreCase) Then
```
Comment (cston) [inline src/Compilers/VisualBasic/Portable/CommandLine/VisualBasicCommandLineParser.vb]: Why `EndsWith` rather than `Equals`?

File: src/Compilers/VisualBasic/Test/CommandLine/CommandLineTests.vb [hunk 5]
```diff
@@ -7944,6 +7944,50 @@ End Class
...
+        <InlineData("/t:library", "/out:foo", "foo.dll", "foo")>                                        'Output without extension
+        <InlineData("/t:module", "/out:foo", "foo.netmodule", "foo")>                                   'Output without extension
+        <InlineData("/t:winmdobj", "/out:foo", "foo.winmdobj", "foo")>                                  'Output without extension
+        <InlineData("/t:exe", "/out:foo.exe", "foo.exe", "foo.exe.exe")>                                'Output with correct extension (.exe)
+        <InlineData("/t:library", "/out:foo.dll", "foo.dll", "foo.dll.dll")>                            'Output with correct extension (.dll)
+        <InlineData("/t:module", "/out:foo.netmodule", "foo.netmodule", "foo.netmodule.netmodule")>     'Output with correct extension (.netmodule)
+        <InlineData("/t:winmdobj", "/out:foo.winmdobj", "foo.winmdobj", "foo.winmdobj.winmdobj")>       'Output with correct extension (.winmdobj)
+        Public Sub OutputingFilesWithDifferentExtensions(targetArg As String, outArg As String, expectedFile As String, unexpectedFile As String)
```
Comment (cston) [inline src/Compilers/VisualBasic/Test/CommandLine/CommandLineTests.vb]: Please test `OrdinalIgnoreCase`.

**Comment by OmarTawfik** [comment]
@cston @jaredpar do I've sign offs?

**Comment by cston** [comment]
LGTM
