### PR TITLE
Fix stack overflow in requesting syntax directives

### LINKED ISSUE #36346: C# Parser can stack overflow when GetDirectives is called on a SyntaxNodeOrToken
See https://developercommunity.visualstudio.com/content/problem/565382/compiling-causes-a-stack-overflow-error.html

While the compiler as a whole may not handle extremely deep trees, it seems reasonable to harden the public surface area of the parser.

### PR DESCRIPTION
**Pull request by agocke**
Fixes #36346

### CODE REVIEW

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNodeTests.cs [hunk 1]
```diff
@@ -14,6 +14,49 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+    {
+        const string KeyColumn=""KeyColumn"";
+        const string Label=""Label"";
+        const string PredictedLabelIndex=""PredictedLabelIndex"";
+        
+        
+        
+        EstimatorChain <ColumnCopyingTransformer> GenerateDataPipeline(MLContext mlContext, LightGbmMulticlassTrainer.Options options)
+        {
+           return  mlContext.Transforms.Conversion.MapValueToKey(outputColumnName: KeyColumn, inputColumnName: Label)");
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNodeTests.cs]: >; [](start = 119, length = 1)

Did you intend this semicolon to be after the whole fluent call chain?  If this is really a test case for the bug, it might be worth doing another test with valid syntax (i.e. move the semicolon from the middle of the fluent call to the end).

Comment (gafter) [inline src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNodeTests.cs]: >" [](start = 117, length = 1)

You probably need a newline so the `#region` starts on a line.

File: src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNodeTests.cs [hunk 2]
```diff
@@ -14,6 +14,49 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+
+            // Append a bunch of fluent method calls in a region
+            srcBuilder.AppendLine("#region Normalization");
+            for (int i = 0; i < 10000; i++)
+            {
+                srcBuilder.AppendLine(@".Append(mlContext.Transforms.NormalizeLogMeanVariance(inputColumnName: ""F40714"", outputColumnName:""NF40714""))");
+            }
+            srcBuilder.AppendLine("#endregion");
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Syntax/Syntax/SyntaxNodeTests.cs]: >srcBuilder [](start = 12, length = 10)

Need a semicolon at the end of the fluent call chain.

**Comment by agocke** [comment]
@dotnet/roslyn-compiler For a short review
