### PR TITLE
Reduce overhead from memory mapped files

### LINKED ISSUE #19493: MemoryMappedInfo cleanup delays Visual Studio shutdown
**tl;dr:** We create instances of `MemoryMappedInfo` (and its nested types). These types are disposable and have finalizers, but in some cases we do not explicitly dispose of instances. The large number of instances created for some user scenarios combined with non-deterministic cleanup resulted in a measurable (~50ms) increase in the time it takes to close Visual Studio for some scenarios.

What follows is a long and detailed breakdown of an investigation that started early Friday morning (5/12) in response to a performance regression detected the day before.

:bulb: When we refer to "meeting internal performance goals" in places like the contributor guide for Roslyn, but don't explain how external contributors are supposed to actually accomplish that, part of what we're talking about is covered by the system explained in detail below. If you were ever interested in what exactly we meant by that, I hope you enjoy the following read. :smile:

### How it started (5/11)

As part of my current role ("grasshopper") on the @dotnet/roslyn-infrastructure team, one of my responsibilities is scheduling and monitoring the incorporation of Roslyn code into Visual Studio itself. The whole process is very new to me, but a reasonably accurate way for a non-Microsoft to view this system is a build farm dedicated to running end-to-end tests prior to taking changes from one large team and applying them to another team. The system as a whole serves as both an early warning system for potential problems and helps identify the team responsible for various types of failures.

One of the toughest types of problems to detect reliably is performance regressions, and anyone who's tried to implement such tests in the past knows what I'm talking about. And the bigger the system under test, the harder it is to produce meaningful results. Small sections of code might be easy to benchmark, but in this case we're talking about ~15+ minute end-to-end user scenario tests of Visual Studio. To keep things flowing smoothly, performance tests in the system allow for some amount of "noise" in the test results. Deviations outside the allowed noise signify major problems where we cannot proceed until they are resolved (I haven't had to deal with one of these so there could be exceptions/special cases that I just don't know about). Deviations "under the degrade bar" do not cause a red flag in the system, still show up on performance reports based on a scoring system. Test scenarios that ran slower than the baseline are given a score based on how close to the bar they are: (actual-baseline)/(bar-baseline), and the highest values show up on the top of the report for manual investigation.

I mentioned "tests" and "scenarios". The two concepts are vital to understanding how we review long and complicated test sequence to identify specific possible regressions. The "test" refers to a complete end-to-end test, which might include opening VS, creating one or more projects, writing some code, building, running, and finally closing the solution and closing Visual Studio itself. Each test is divided into several named scenarios corresponding to specific actions, and target metrics may be defined either for the test as a whole or for specific scenarios.

:bulb: For anyone wanting to set up a system like this someday, I recommend you implement the ability to automatically assign metrics based on what you measure in a shipping release. This "baselining" ability allows you to establish target goals relatively easily that help ensure future releases of your product perform *at least as well* as the previous release, which is a great place to start when discussing development strategies to gradually improve the experience your customers have on a daily basis.

Thursday's test run included one test which did not exceed the bar but seemed "worse than normal", thus starting a manual review. The specific scenario was "Close VS", which in this test occurs after the solution is already closed. The degrade bar is set at 100ms slower than the previous release, and the build was showing a value of 52ms slower. The investigation started with a review of the history of this test using a tool that shows the builds on our team and the builds for the "mainline" that all the teams interact with. This overlay of the two branches is important because it can show with relatively high confidence whether a problem originated on our team (shows up on ours before mainline), or another team (shows up in mainline before ours). Here's the graph going back several builds. The orange branch is our team, and the purple branch is one of the main Visual Studio branches.

image

This investigation centered around the apparent new trend where we are sitting roughly 40-50ms slower than our goal line, and which started on our team builds prior to showing up in the main branch.

### Tracking down the problem (5/12)

Tracking down the problem is not always easy, but the two things you can do to be successful on this front are preparation and practice.

#### Preparation

Our end-to-end tests which we use for performance monitoring have PerfView running in the background. I don't have details regarding the exact configuration, but the key items would be:

1. Configure your sampling rate such that you have a "manageable" output data file size over the duration of your test. Since our tests are 15+ minutes, this means a slower sampling rate than the default.
2. Make sure you are enabling items that relate to your user experience. The meaning of this will vary by industry/application, but for me the two items I found valuable were having Thread Time enabled and also having marks inserted into the trace by the end-to-end test driver identifying exactly when a scenario (e.g. Close VS) started and ended.
3. Store the outputs of the PerfView traces for a sufficient amount of time that they can be used for comparative analysis in the future.

#### Practice

I had an advantage in investigating this by knowing three things:

1. The scenario which failed was Close VS, so I could filter the PerfView reports to start and end at the markers placed at the start and end of this scenario. As you can see from the graph, this is a ~300ms window out of the ~15 minute report.
2. Since I was investigating an elapsed time performance failure, the view of most immediate interest was the Thread Time view. I needed to account for the additional 50ms of time, regardless of whether that time was BLOCKED TIME or CPU TIME.
3. Even though this was my first experience ever with this test or scenario, I knew I could most easily track down the time by opening two reports side by side: one from a recent "slow" run, and the other from a recent "fast" run.

### Findings

I started with the Call Tree view examining the main thread. By comparing with the previous run, I pretty quickly narrowed down the additional time on the main thread to the following trace. The highlighted value accounts for all of the new time:

image

As you can see, the main thread was blocked during this time, so to find the root cause we have to find out what it was waiting on. In this case, the answer was pretty easy to infer by looking at the thread activity histograms and asking "what would the CLR be waiting for during `clr!??EEShutdown`.

image

Focusing on the finalizer thread showed two items of particular interest:

image

The in the conveniently available CoreCLR sources, we can see that these are the two methods called to [finalize a single object](https://github.com/dotnet/coreclr/blob/76cbc581382ebbcf745dd2b79ac02c419970808c/src/vm/finalizerthread.cpp#L98-L99).

* **clr!WKS::CallFinalizer**: This is slow when you have many finalizers, or when finalizers themselves are slow
* **clr!WKS::LogFinalization**: This has no measurable overhead normally, but a small amount of overhead when ETW events are being recorded. While the call within it, **clr!??ETW::GCLog::SendFinalizeObjectEvent**, probably should have been pruned by our analysis as measurement overhead imposed by PerfView recording, it nevertheless provided valuable insight for me. *Time here means a large number of objects are getting finalized.*

A closer look at **clr!WKS::CallFinalizer** revealed the problem with `MemoryMappedInfo`:

image

In the next step of my investigation, I wanted to determine how many `MemoryMappedInfo` objects were getting finalized when the CLR was trying to shut down. This part was rather difficult, but hopefully in the future it can be improved (filed Microsoft/perfview#200 and Microsoft/perfview#201). I filtered the events view to the start/end time for the scenario, set MaxRet to 110000 (so all events would show), and set the process filter to **devenv**. I then opened the **Microsoft-Windows-DotNETRuntime/GC/FinalizeObject** events, showed the **TypeID** column, and exported the resulting view as a CSV file. After opening the CSV file in Excel, I used a pivot table on the TypeID column to get a histogram which I sorted by the number of times an object of that type ID was finalized. Working from the top, I then examined all available events in PerfView of type **Microsoft-Windows-DotNETRuntime/GC/AllocationTick** to associate type IDs with type names. I only made it through the first 5 items before the sampling rate of AllocationTick stopped showing results.

image

### Follow-up

The solution appears to be two-fold:

1. Reduce the number of memory-mapped file handles that need to be cleaned up. For example, rather than create a memory mapped file for every temporary storage request, we could set a minimum size on the file at 1 MiB, and use smaller views within the file for temporary storage. When a request is too large to fit in the available space at the end of the current file, stop creating storage in that file and move to a new one.
2. Reduce the "weight" of finalization by reducing the size of the object graph referenced by finalizable objects. In particular, avoid making `MemoryMappedInfo` and `SharedReadableStream` themselves finalizable, and instead create a minimal type (or types) derived from `CriticalHandle` which is responsible for releasing the unmanaged resources.

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #19493

## Ask Mode

**Customer scenario**

Customer closes Visual Studio after working in a C# or Visual Basic project.

**Bugs this fixes:**

#19493 
DevDiv 435299 (external users: this internal bug tracks the internal performance regression and just points to the previous public bug where I placed all the actual info)

**Workarounds, if any**

Wait longer.

**Risk**

Low. Of several ways known ways to improve performance in this scenario, I chose the least risky one. Follow-up issues will be filed as opportunistic areas for further improvement in the future.

**Performance impact**

The time it takes to close Visual Studio is reduced by roughly 0.25-1ms for each file in the solution. This is a multiple second improvement for projects like Roslyn.sln.

**Is this a regression from a previous update?**

No. The bug appears to have been introduced with Visual Studio 2015.

**Root cause analysis:**

Failure of internal Regression Prevention System (RPS) tests to exercise code paths related to this bug, and failure to go through PerfView traces in detail for scenarios targeting very large solutions. Discussions are taking place regarding improvements to PerfView which should help reveal these kinds of problems for both us and developers of other applications before they cause problems.

**How was the bug found?**

RPS tests

### CODE REVIEW

**Comment by sharwell** [comment]
@dotnet/roslyn-ide for review

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs [hunk 1]
```diff
@@ -115,85 +106,91 @@ public Stream CreateWritableStream()
...
                 {
-                    _streamCount--;
-                    if (_streamCount == 0 && _accessor != null)
+                    lock (_memoryMappedFile)
                     {
-                        _accessor.Dispose();
-                        _accessor = null;
+                        if (_accessor != null)
+                        {
+                            // dispose accessor it owns.
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: "it"?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs [hunk 2]
```diff
@@ -115,85 +106,91 @@ public Stream CreateWritableStream()
...
 
-            ~MemoryMappedInfo()
+            public static string CreateUniqueName(long size)
             {
-                Dispose(false);
+                return "Roslyn Temp Storage " + size.ToString() + " " + Guid.NewGuid().ToString("N");
             }
 
-            public void Dispose()
+            private unsafe sealed class CopiedMemoryMappedViewHandle : CriticalHandleZeroOrMinusOneIsInvalid
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: having hte class here seems to have made the diff very unhappy.  Can we have in a separate file?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs [hunk 3]
```diff
@@ -115,85 +106,91 @@ public Stream CreateWritableStream()
...
 
-            private void Dispose(bool disposing)
-            {
-                lock (_memoryMappedFile)
+                public CopiedMemoryMappedViewHandle(SafeMemoryMappedViewHandle viewHandle)
                 {
-                    if (_accessor != null)
+                    _viewHandle = viewHandle;
+
+                    RuntimeHelpers.PrepareConstrainedRegions();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: please document.

**Comment by CyrusNajmabadi** [comment]
Can you give an explanation of what this actually does and why it addresses the problem?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 3 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: 1. I will document
2. I made a mistake. The call to `PrepareConstrainedRegions` must *immediately* precede the `try` statement, but I have a variable initialization between the two.

Comment (tmat) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: >RuntimeHelpers.PrepareConstrainedRegions(); [](start = 20, length = 43)

Let's not use CERs. We are not going to run this in environments where it matters.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 2 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: ➡️ Done!

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 1 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: 💭 Not sure, I didn't change this part of the code.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 3 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: CERs are the correct way to acquire the pointer from a `SafeBuffer`. Unless it causes a demonstrated performance problem it needs to stay.

**Comment by sharwell** [comment]
@CyrusNajmabadi This change addresses the bug specifically in commit 723144bafbcd550e2953b17ab2833fbcdb61209e. Normally I wouldn't rebase in the middle of a review, but due to the complexity of the underlying bug I wanted the documentation to be correctly associated with the relevant changes so it's clear that while the first commits are preparation, only the last one actually resolves the performance problems we observed.

**Comment by sharwell** [comment]
:memo: This change remains a suboptimal use of this resource, but it does make a substantial difference in the area of closing Visual Studio. If accepted in the current form, I will file follow-up issues covering areas where this could be further improved in the future.

**Comment by sharwell** [comment]
@MattGertz for ask mode

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 3 above)
Comment (tmat) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: If thread abort occurs before the try block is entered we don't acquire the pointer but ReleaseHandle will still call ReleasePointer.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 2 above)
Comment (tmat) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: >CopiedMemoryMappedViewHandle [](start = 40, length = 28)

This seems to be similar to [https://source.dot.net/#System.Reflection.Metadata/System/Reflection/Internal/MemoryBlocks/MemoryMappedFileBlock.cs](https://source.dot.net/#System.Reflection.Metadata/System/Reflection/Internal/MemoryBlocks/MemoryMappedFileBlock.cs).

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 3 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: ReleaseHandle is not called if the handle is invalid, which it would be in this case.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 2 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: It does. Given the perf sensitivity here I'll have to review that closely for applicability tomorrow.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 3 above)
Comment (tmat) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: Why would it be invalid?

---
In reply to: [116652491](https://github.com/dotnet/roslyn/pull/19522#discussion_r116652491) [](ancestors = 116652491)

**Comment by MattGertz** [comment]
Pending CR signoffs.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 2 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: I looked again. This class wouldn't be applicable to our use case without modification because it doesn't accommodate having multiple handles for the same instance, and doesn't include the required special case for `Environment.HasShutdownStarted`.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+
+            public byte* RawValue => (byte*)handle;
+
+            protected override bool ReleaseHandle()
+            {
+                // The operating system will release these handles when the process terminates, so do not spend time
+                // releasing them manually in that case. Doing so causes unnecessary delays during application shutdown.
+                if (!Environment.HasShutdownStarted)
+                {
+                    _viewHandle.ReleasePointer();
```
Comment (jaredpar) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs]: Why are we ignoring the return value of `ReleasePointer` here?

Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs]: ➡️ Method returns `void`

Comment (jaredpar) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs]: Doh.  Was looking at ReleaseHandle.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 1 above)
Comment (heejaechang) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: with what you changed, stream given out will always work regardless accessor, memory map file being already disposed right? so this comment seems no longer needed.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs [hunk 5]
```diff
@@ -346,19 +319,6 @@ public IntPtr GetPointer()
                 {
                     return (IntPtr)_start;
                 }
-
-                /// <summary>
-                /// Acquire the fixed pointer to the start of the memory mapped view.
-                /// The pointer will be released during <see cref="Dispose(bool)"/>
-                /// </summary>
-                /// <returns>The pointer to the start of the memory mapped view. The pointer is valid, and remains fixed for the lifetime of this object.</returns>
-                private static byte* AcquirePointer(MemoryMappedViewAccessor accessor)
```
Comment (heejaechang) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: I guess we no longer need to do this to get right pointer position?

Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: We do, but it's now part of the `CopiedMemoryMappedViewHandle` constructor.

**Comment by heejaechang** [comment]
👍 nice improvement.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs [hunk 6]
```diff
@@ -1,11 +1,11 @@
 ﻿// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
 
+using Roslyn.Utilities;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: Sorting.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 5 above)
Comment (heejaechang) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: I dont see this.

 ptr += accessor.PointerOffset;

before, it was needed to make pointer to point to right location.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs [hunk 7]
```diff
@@ -0,0 +1,63 @@
...
+                // 1. The pointer is not acquired, and the current handle is invalid (thus will not be released)
+                // 2. The pointer is acquired, and the current handle is fully initialized for later cleanup
+                RuntimeHelpers.PrepareConstrainedRegions();
+                try
+                {
+                    viewHandle.AcquirePointer(ref pointer);
+                }
+                finally
+                {
+                    handle = (IntPtr)pointer;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs]: for me, could you either write this as "this.handle =" or "base.handle ="?  Right now it looks like this is being assigned to a random local/parameter that i can't see :)

Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs]: base.handle would make it very clear where the storage for this name lives.

Comment (heejaechang) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs]: agree. I had to look it up to find out where the handle came from.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs [hunk 8]
```diff
@@ -0,0 +1,63 @@
...
+        /// This critical handle increments the reference count of a <see cref="SafeMemoryMappedViewHandle"/>. The view
+        /// will be released when it is disposed <em>and</em> all pointers acquired through
+        /// <see cref="SafeBuffer.AcquirePointer"/> (which this class uses) are released.
+        /// </summary>
+        /// <remarks>
+        /// <para><see cref="CriticalHandle"/> types are not reference counted, and are thus somewhat limited in their
+        /// usefulness. However, this handle class has tightly restricted accessibility and is only used by managed
+        /// code which does not rely on it counting references.</para>
+        /// </remarks>
+        private unsafe sealed class CopiedMemoryMappedViewHandle : CriticalHandleZeroOrMinusOneIsInvalid
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs]: Maybe a better name would be RefCountedMemoryMappedViewHandle?   'Copied' doesn't really convey to me the purpose here.  Whereas RefCount helps me understand that the purpose of this is to add the Acquire/Release semantics that make things work.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 1 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: @heejaechang Comments have been updated for accuracy.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs [hunk 9]
```diff
@@ -0,0 +1,63 @@
...
+        {
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs]: Consider adding '#ifdef debug' code that makes this type finalizable, and which throws if it is finalized without ReleaseHandle being called (if we're not shutting down).

Basically, a way to catch if something bad is happening, without the release overhead of using finalizers.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs (hunk 7 above)
Comment (tmat) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs]: Or even better use ```SetHandle((IntPtr)pointer)```

**Comment by heejaechang** [comment]
just FYI. memory map file is some time shared with OOP to reduce size of data it needs to send over. so if you create some kind of mmf manager to share one memory map file or view between multiple consumers, we need to change OOP synchronization side as well to accommodate the changes.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs [hunk 10]
```diff
@@ -326,17 +304,12 @@ protected override void Dispose(bool disposing)
                 {
                     base.Dispose(disposing);
 
-                    if (_start != null)
+                    if (disposing)
                     {
-                        _accessor.SafeMemoryMappedViewHandle.ReleasePointer();
-                        _start = null;
+                        _handle.Dispose();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: Why do we only do this if we're disposing?  Can you comment why that's ok?

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs (hunk 8 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs]: This is explicitly not a reference-counted handle by design, to avoid unnecessary overhead. See the remarks above.

**Comment by CyrusNajmabadi** [comment]
Overall LGTM.  Had some nits, and some general thoughts about comments for future readers.  This is non-obvious stuff, so the more stuff to make it clearer, the better.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs (hunk 9 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs]: We rely heavily on this finalizer in the current implementation. This change would totally break debug builds.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs [hunk 11]
```diff
@@ -0,0 +1,63 @@
...
+            private readonly SafeMemoryMappedViewHandle _viewHandle;
+
+            public CopiedMemoryMappedViewHandle(SafeMemoryMappedViewHandle viewHandle)
+            {
+                _viewHandle = viewHandle;
```
Comment (tmat) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs]: My comment from previous iteration still holds. If a thread abort happens right after this assignment the finalizer will try to release pointer of a handle for which we haven't acquired it.

Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs]: :memo: I replied to your earlier comment.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs (hunk 8 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs]: "This critical handle increments the reference count of a <see cref="SafeMemoryMappedViewHandle"/>. The view
 +        /// will be released when it is disposed <em>and</em> all pointers acquired through
 +        /// <see cref="SafeBuffer.AcquirePointer"/> (which this class uses) are released."

I'm not saying that there need to be a ref count in here.  I'm asking that hte name of hte type indicate that it's purpose is to properly ensure refcounting for something.  Given that it seems to exist to Acquire/Release, it def seems like a ref-count-like system.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs (hunk 7 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs]: I can use `base.handle`. Using `this.handle` breaks code style for the project.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs (hunk 9 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs]: What finalizer?  I don't see one in the current code.  

> This change would totally break debug builds.

If that's the case, can you comment as such that that's the intended way for this type to be used.   i.e. that the client of it is not required to release it since a finalizer will take care of it for them.

Again, this is non-obvious stuff.  We need documentation to explain the intent here and how its expected to be used properly.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 6 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: Got hit by #17658.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 5 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: Interesting. It's always 0 in the current code but I'll account for it since we're planning for it to make a difference in the future.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs (hunk 9 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs]: > What finalizer?

The type extends `CriticalFinalizerObject`.

> If that's the case, can you comment as such that that's the intended way for this type to be used.

It is not the intended way for this type to be used. The intended behavior for this type is the standard behavior implied by the fact that the type(s) implement `IDisposable`. When unmanaged resources are involved, finalizers are provided to ensure that failure to follow normal `IDisposable` practices will not result in leaks.

Documenting detailed behavior would suggest that this type does not follow the expected practices for `IDisposable`, but I can't think of any special cases or concerns that apply here.

**Comment by sharwell** [comment]
> just FYI. memory map file is some time shared with OOP to reduce size of data it needs to send over. so if you create some kind of mmf manager to share one memory map file or view between multiple consumers, we need to change OOP synchronization side as well to accommodate the changes.

Yes, I will cover this in the follow-up issue. Thanks!

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs (hunk 8 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs]: Unless there are strong objections, I prefer to keep the current name. To me, the behavior seems closer to [`DuplicateHandle`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724251.aspx) than [`SafeHandle`](https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.safehandle.aspx), but I don't want it confused with either.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs (hunk 7 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs]: ➡️ Now updated to use `SetHandle`.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 6 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: ➡️ Fixed.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 5 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: :arrow_right: Fixed.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 10 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: :arrow_right: `_handle` is a managed object. Interactions with managed objects during `Dispose` are always¹ conditional on `disposing` being true.

¹ There are limited exceptions, but none apply to anything related to this code so there's nothing to get confused about.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs (hunk 9 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs]: > but I can't think of any special cases or concerns that apply here.

Think about it this way.  This code will live for years or decades.  Different people with different levels of understanding will come across this code in the future and may end up not realizing these things and may end up breaking things in subtle ways.  

Defensively commenting our code to make it clear what is/isn't ok just helps ensure that people in the future don't mess things up.  Again, this is subtle stuff.  And these patterns and types you're using are *not* common the Roslyn codebase.  That means people don't have a natural built-in understanding of all these details.  For example, i was unaware that this code was finalizer-safe.  Making the documentation for this clear this up hurts no one and can only help the long term sustainability of this code.

Heck, it can be as simple as:  Clients of this code should take care to Dispose this type so that the memory mapped file can be released by teh OS as soon as it is no longer necessary.  However, if a client does not Dispose things, the GC will still take care of this by eventually finalizing this type.  All that means is that the memory mapped file will be kept alive longer than absolutely necessary.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs (hunk 10 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: Can you comment why that's ok in the code.

Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: For example, so that the next person who comes doesn't have to ask and go figure out "hunh... if this type is finalized... is it ok that we don't dispose this handle?"   

Comments are great in the code for answering the questions that people may have when they come across the code.  It prevents the problem where someone goes "hunh... is this intentional and appropriate?  or is this an oversight and a potential bug?".   When a comment can make it clear that the developer considered and appropriately thought through this, it's massively helpful for long term maintenance (especially around complex and subtle code).

Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.MemoryMappedInfo.cs]: ➡️ Added a description to `MemoryMappedInfo` which describes these types as standard (totally non-special) implementations of `IDisposable` from the perspective of outside code, and linked to an article which covers many guidelines for implementing these types, including the reason why `_handle` is only disposed if `disposing` is true.

File: src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs (hunk 9 above)
Comment (sharwell) [inline src/Workspaces/Core/Desktop/Workspace/Host/TemporaryStorage/TemporaryStorageServiceFactory.CopiedMemoryMappedViewHandle.cs]: ➡️ Added a comment (with reference link) describing this as a non-special implementation of `IDisposable`, which includes several characteristics related to behavior for external code:

1. Calling `Dispose` is recommended
2. A finalizer is provided to ensure unmanaged resources are non-deterministically released if `Dispose` is not called
3. Multiple calls to `Dispose` after the first are a NOP

**Comment by sharwell** [comment]
@heejaechang I filed #19570 with the enhancement request for the future.
