### PR TITLE
Log paths to HTML test results when present

### LINKED ISSUE #49045: Test runner doesn't output HTML when run locally
**Version Used**: d06c9e6cd72a7248450985088c846b383cc23ac1

**Steps to Reproduce**:

1. Break something in the tests
2. Run the following command
```pwsh
.\Build.cmd -test
```

Output looks like:
```
# a bunch of build output...
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:54.97
Proc dump location:
Running 46 test assemblies in 82 partitions
  36 running, 46 queued,  0 completed
  36 running, 45 queued,  1 completed
  36 running, 43 queued,  3 completed
  36 running, 23 queued, 23 completed
  36 running, 22 queued, 24 completed
  36 running, 21 queued, 25 completed
  36 running, 20 queued, 26 completed
  36 running, 19 queued, 27 completed
  36 running, 18 queued, 28 completed
  36 running, 17 queued, 29 completed
  36 running, 16 queued, 30 completed
  36 running, 15 queued, 31 completed
  36 running, 14 queued, 32 completed
  36 running, 13 queued, 33 completed
  36 running, 12 queued, 34 completed
  36 running, 11 queued, 35 completed
  36 running, 10 queued, 36 completed
Test failure log: C:\Users\rikki\src\roslyn\artifacts\TestResults\Debug\Microsoft.CodeAnalysis.CSharp.Emit.UnitTests.dll.1_net472_x86.xml
```

**Expected Behavior**: Failure log links to an HTML file.

**Actual Behavior**: Failure log links to an XML file.

/cc @jaredpar

### PR DESCRIPTION
**Pull request by RikkiGibson**
Fixes #49045

### CODE REVIEW

**Review by genlu — APPROVED** [review]

File: src/Tools/Source/RunTests/ProcessTestExecutor.cs [hunk 1]
```diff
@@ -108,7 +108,7 @@ private async Task<TestResult> RunTestAsyncInternal(AssemblyInfo assemblyInfo, b
             try
             {
                 var commandLineArguments = GetCommandLineArguments(assemblyInfo);
-                var resultsFilePath = GetResultsFilePath(assemblyInfo);
+                var resultsFilePath = GetResultsFilePath(assemblyInfo, Options.IncludeHtml ? "html" : "xml");
```
Comment (jaredpar) [inline src/Tools/Source/RunTests/ProcessTestExecutor.cs:111]: The `resultsFilePath` here should always be the XML path. Otherwise it breaks the logic below for looking up failed tests based on the XML contens of the results.

Comment (jaredpar) [reply src/Tools/Source/RunTests/ProcessTestExecutor.cs:111]: Why do u think this change is necessary? The code on line 81 should include the HTML when the option is specified in build.ps1

Comment (RikkiGibson) [reply src/Tools/Source/RunTests/ProcessTestExecutor.cs:111]: Without this change, we do pass the html flag to 'dotnet test' correctly, but we don't log the paths to the HTML logs from RunTests, and when tests complete with failures locally we open the XML logs instead of the HTML logs. #49091

Comment (RikkiGibson) [reply src/Tools/Source/RunTests/ProcessTestExecutor.cs:111]: Perhaps resultsFilePath could be without an extension? Or in specific usages where we know Options.IncludeHtml is set we can try using ChangeExtension or something.

Comment (jaredpar) [reply src/Tools/Source/RunTests/ProcessTestExecutor.cs:111]: Think the solution to that though is changing `TestResult.ResultsFilePath` more directly though. Yes this change accomplishes that but it does so but breaking the retry logic. Need to change that without breaking retry. 

Or possible just change `TestResult` to return both paths.

Comment (RikkiGibson) [reply src/Tools/Source/RunTests/ProcessTestExecutor.cs:111]: I'll change this code since it definitely seems bad to just "sometimes try to parse HTML as XML", but I would also note that retry is disallowed when HTML output is enabled.

Comment (jaredpar) [reply src/Tools/Source/RunTests/ProcessTestExecutor.cs:111]: Agreed HTML + retry is disallowed as a combo. It seems like a bad idea to make the rest of our code here aware of that though.

**Review by jaredpar — APPROVED** [review]
