### PR TITLE
Fixes #7470 NRE in build task

### LINKED ISSUE #7470: Build task is crashing on ETA and VSI runs
C:\Users\dotnet-bot\.nuget\packages\Microsoft.Net.Compilers\1.2.0-beta-20151211-01\tools\Microsoft.CSharp.Core.targets(67,5): error MSB3883: Unexpected exception:  [d:\j\workspace\roslyn-internal_prtest_win_dbg_unit32\Open\src\Features\Core\Portable\Features.csproj]
10:53:14 C:\Users\dotnet-bot\.nuget\packages\Microsoft.Net.Compilers\1.2.0-beta-20151211-01\tools\Microsoft.CSharp.Core.targets(67,5): error : System.NullReferenceException: Object reference not set to an instance of an object. [d:\j\workspace\roslyn-internal_prtest_win_dbg_unit32\Open\src\Features\Core\Portable\Features.csproj]

http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_unit32/404/consoleFull#56248540979494335-f7bd-47d0-8771-8661e00c2db2

### PR DESCRIPTION
**Pull request by agocke**

### CODE REVIEW

File: src/Compilers/Core/CommandLine/BuildClient.cs [hunk 1]
```diff
@@ -93,13 +93,14 @@ internal int RunCompilation(IEnumerable<string> originalArguments, BuildPaths bu
                         return HandleResponse(buildResponse, parsedArgs, buildPaths);
                     }
                 }
-                catch
+                catch (OperationCanceledException)
```
Comment (amcasey) [inline src/Compilers/Core/CommandLine/BuildClient.cs]: Other exceptions will still be caught further down the stack, right?

**Comment by amcasey** [comment]
:+1:

File: src/Compilers/Core/CommandLine/BuildClient.cs (hunk 1 above)
Comment (agocke) [inline src/Compilers/Core/CommandLine/BuildClient.cs]: Yes, all server exceptions should be caught by RunServerCompilation. By the time we get here we shouldn't be swallowing exceptions.

File: src/Compilers/Shared/DesktopBuildClient.cs [hunk 2]
```diff
@@ -157,12 +157,12 @@ protected override int RunLocalCompilation(List<string> arguments, string client
                 }
             }
 
-            return null;
+            return Task.FromResult<BuildResponse>(null);
```
Comment (brettfo) [inline src/Compilers/Shared/DesktopBuildClient.cs]: Why does this method have to return `Task<BuildResponse>` instead of just `BuildResponse`?  There are no `await`'s here.  Or is it to make the signature equivalent to another function that does use `await`?

Comment (brettfo) [inline src/Compilers/Shared/DesktopBuildClient.cs]: I spoke with @agocke offline and he explained what was going on.

File: src/Compilers/Server/VBCSCompilerTests/DesktopBuildClientTests.cs [hunk 3]
```diff
@@ -13,6 +13,7 @@
 using System.Threading.Tasks;
 using Microsoft.CodeAnalysis.Test.Utilities;
 using Roslyn.Test.Utilities;
+using System.Threading;
```
Comment (jaredpar) [inline src/Compilers/Server/VBCSCompilerTests/DesktopBuildClientTests.cs]: Sort usings

File: src/Compilers/Core/CommandLine/BuildClient.cs [hunk 4]
```diff
@@ -93,13 +93,14 @@ internal int RunCompilation(IEnumerable<string> originalArguments, BuildPaths bu
...
                 {
-                    // It's okay, and expected, for the server compilation to fail.  In that case just fall 
-                    // back to normal compilation. 
+                    return CommonCompiler.Succeeded;
```
Comment (jaredpar) [inline src/Compilers/Core/CommandLine/BuildClient.cs]: Why would we return `Succeeded` when we catch `OperationCanceledException`?

Comment (jaredpar) [inline src/Compilers/Core/CommandLine/BuildClient.cs]: Looking this line feels wrong.  If the server build is cancelled and this exception is caught we will return succeeded but never run the compilation.

File: src/Compilers/Shared/DesktopBuildClient.cs (hunk 2 above)
Comment (jaredpar) [inline src/Compilers/Shared/DesktopBuildClient.cs]: I swear we should write a rule that flags returning `null` from a `Task` based method :frowning:

File: src/Compilers/Core/CommandLine/BuildClient.cs (hunk 4 above)
Comment (AlekseyTs) [inline src/Compilers/Core/CommandLine/BuildClient.cs]: Also, it would be good to add a comment explaining the scenario when this exception could be expected to be thrown by the code in the try and why does it need special handling.

Comment (jaredpar) [inline src/Compilers/Core/CommandLine/BuildClient.cs]: In fixing this we should also add a unit test to verify this behavior is appropriately covered.

Comment (agocke) [inline src/Compilers/Core/CommandLine/BuildClient.cs]: On second thought -- we're passing `CancellationToken.None` above -- should we be catching this exception at all? It should be impossible.

Comment (jaredpar) [inline src/Compilers/Core/CommandLine/BuildClient.cs]: It's a virtual method, it can throw anything. This is why I had the catch all originally. 

Do we have a bug tracking the fix for the retune value here?

Comment (agocke) [inline src/Compilers/Core/CommandLine/BuildClient.cs]: Filed here: https://github.com/dotnet/roslyn/issues/7866

The reason I got rid of the catch is that it was swallowing the NRE from RunServerCompilation.

I understand swallowing all exceptions in the process of trying to run a server compilation, but I think once we have a result we should not expect exceptions.
