### PR TITLE
When building a decision dag, recognize special CLR behavior of arrays.

### LINKED ISSUE #35487: CS7038: 'Failed to emit module' declaring and then assigning `ReadOnlySpan<char>`
**Version Used**: 
3.100.19.20907 (01f3eb10)

**Steps to Reproduce**:

Compile this.
```C#
void FailToEmitDll(ReadOnlySpan<char> span) {
    ReadOnlySpan<char> temp;
    temp = 1 switch
    {
        _ => span
    };
}
```
**Expected Behavior**:
It compiles.

**Actual Behavior**:
`1>CSC : error CS7038: Failed to emit module 'Tests'.`

**Workaround**
Change the declaration-and-assignment of `temp` to read:
```
var temp = 1 switch (…)
```
Similar to #33275.

### LINKED ISSUE #35661: Switch case doesn't match anymore in VS2019
**Version Used**: 
Visual Studio 2019
**Example code**
```
public Type GetIntArrayType(object obj)
{
    switch (obj)
    {
        case int[] _ when obj.GetType() != typeof(uint[]):
            return typeof(int[]);
        case uint[] _:
            return typeof(uint[]);
        default:
            throw new Exception("Not an int array");
    }
}

Console.WriteLine(GetIntArrayType(new uint[0]));
```
**Expected Behavior**:
`System.UInt32[]`
**Actual Behavior**:
`System.Exception : Not an int array`

This code worked in VS2017, but no longer in VS2019. I suspect some optimization was done to skip cases that "can't match", but in this rather special case it is mistaken.

It will match `int[]`(!) but fail the condition and instead of testing the next case it jumps to default.

The fact that an uint array can be unboxed as an int array is strange as well, but the reason behind that is explained here: https://blogs.msdn.microsoft.com/ericlippert/2009/09/24/why-is-covariance-of-value-typed-arrays-inconsistent/

I understand that this is an edge case that you might not deem important enough to do anything about, but I wanted to let you know about this change in behavior from VS2017.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #35661

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet/roslyn-compiler This is the change we discussed today.  May I please have a couple of reviews?

**Comment by jcouv** [comment]
Was #35487 resolved prematurely?

**Comment by gafter** [comment]
@jcouv See https://github.com/dotnet/roslyn/issues/35487#issuecomment-492381942.  That issue has nothing to do with this one.

File: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs [hunk 1]
```diff
@@ -1007,6 +1006,91 @@ RemainingTestsForCase makeNext(ArrayBuilder<BoundDagTest> remainingTests)
             }
         }
 
+        /// <summary>
+        /// Determine what we can learn from one successful runtime type test about another planned
+        /// runtime type test for the purpose of building the decision tree.
+        /// We accomodate a special behavior of the runtime here, which does not match the language rules.
+        /// A value of type `int[]` is an "instanceof" (i.e. result of the `isinst` instruction) the type
+        /// `uing[]` and vice versa.  It is similarly so for every pair of same-sized numeric types, and
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs]: `uint[]`?

Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs]: Yes; I'll fix before committing.

File: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs [hunk 2]
```diff
@@ -1007,6 +1006,91 @@ RemainingTestsForCase makeNext(ArrayBuilder<BoundDagTest> remainingTests)
...
+        /// arrays of enums are considered to be their underlying type.  We need the dag construction to
+        /// recognize this runtime behavior, so we pretend that matching one of them gives no information
+        /// on whether the other will be matched.  That isn't quite correct (nothing reasonable we do
+        /// could be), but it comes closest to preserving the existing C#7 behavior without undersireable
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs]: nit: "undesirable"

Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs]: Will fix.

File: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs [hunk 3]
```diff
@@ -1007,6 +1006,91 @@ RemainingTestsForCase makeNext(ArrayBuilder<BoundDagTest> remainingTests)
...
+
+                    if (e2 is NamedTypeSymbol { TypeKind: TypeKind.Enum, EnumUnderlyingType: var t2 })
+                        e2 = t2;
+
+                    switch (e1.SpecialType, e2.SpecialType)
+                    {
+                        // The following support CLR behavior that is required by
+                        // the CLI specification but violates the C# language behavior.
+                        // See ECMA-335's definition of *array-element-compatible-with*.
+                        case var (s1, s2) when s1 == s2:
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs]: What scenarios does this case catch?

File: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs [hunk 4]
```diff
@@ -1007,6 +1006,91 @@ RemainingTestsForCase makeNext(ArrayBuilder<BoundDagTest> remainingTests)
...
+        bool? ExpressionOfTypeMatchesPatternTypeForLearningFromSuccessfulTypeTest(TypeSymbol expressionType, TypeSymbol patternType, ref HashSet<DiagnosticInfo> useSiteDiagnostics)
+        {
+            bool? result = Binder.ExpressionOfTypeMatchesPatternType(_conversions, expressionType, patternType, ref useSiteDiagnostics, out Conversion conversion);
+            return (!conversion.Exists && isRuntimeSimilar(expressionType, patternType))
+                ? null // runtime and compile-time test behavior differ. Pretend we don't know what happens.
+                : result;
+
+            static bool isRuntimeSimilar(TypeSymbol expressionType, TypeSymbol patternType)
+            {
+                while (expressionType is ArrayTypeSymbol { ElementType: var e1, IsSZArray: var sz1, Rank: var r1 } &&
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs]: any need to test cases where the expression array type has a different rank than the pattern array type? I'd expect that a conversion wouldn't exist, so we wouldn't get here, but I don't know the spec deeply enough to say.

**Comment by gafter** [comment]
Fixed the issue mentioned in the OP

File: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs (hunk 3 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs]:
``` c#
    case int[] a1: ...
    case Eint[] a2: ...
```

File: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs (hunk 4 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs]: We would get here, but we would conclude they are not runtime similar.  But even if we did, since the runtime doesn't treat them as similar the code would work correctly either way.  Are you suggesting some test like
``` c#
    case int[] a1: ...
    case Eint[,] a2: ...
```
?

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I have a second review please?

File: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs [hunk 5]
```diff
@@ -1007,6 +1006,91 @@ RemainingTestsForCase makeNext(ArrayBuilder<BoundDagTest> remainingTests)
...
+        /// <summary>
+        /// Determine what we can learn from one successful runtime type test about another planned
+        /// runtime type test for the purpose of building the decision tree.
+        /// We accomodate a special behavior of the runtime here, which does not match the language rules.
+        /// A value of type `int[]` is an "instanceof" (i.e. result of the `isinst` instruction) the type
+        /// `uint[]` and vice versa.  It is similarly so for every pair of same-sized numeric types, and
+        /// arrays of enums are considered to be their underlying type.  We need the dag construction to
+        /// recognize this runtime behavior, so we pretend that matching one of them gives no information
+        /// on whether the other will be matched.  That isn't quite correct (nothing reasonable we do
+        /// could be), but it comes closest to preserving the existing C#7 behavior without undersirable
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs]: >undersirable [](start = 92, length = 12)

Typo

File: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs [hunk 6]
```diff
@@ -1007,6 +1006,91 @@ RemainingTestsForCase makeNext(ArrayBuilder<BoundDagTest> remainingTests)
...
+        /// side-effects, and permits the code-gen strategy to preserve the dynamic semantic equivalence
+        /// of a switch (on the one hand) and a series of if-then-else statements (on the other).
+        /// See, for example, https://github.com/dotnet/roslyn/issues/35661
+        /// </summary>
+        bool? ExpressionOfTypeMatchesPatternTypeForLearningFromSuccessfulTypeTest(TypeSymbol expressionType, TypeSymbol patternType, ref HashSet<DiagnosticInfo> useSiteDiagnostics)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs]: >b [](start = 8, length = 1)

`private`

File: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs [hunk 7]
```diff
@@ -1007,6 +1006,91 @@ RemainingTestsForCase makeNext(ArrayBuilder<BoundDagTest> remainingTests)
...
+            {
+                while (expressionType is ArrayTypeSymbol { ElementType: var e1, IsSZArray: var sz1, Rank: var r1 } &&
+                       patternType is ArrayTypeSymbol { ElementType: var e2, IsSZArray: var sz2, Rank: var r2 } &&
+                       sz1 == sz2 && r1 == r2)
+                {
+                    if (e1 is NamedTypeSymbol { TypeKind: TypeKind.Enum, EnumUnderlyingType: var t1 })
+                        e1 = t1;
+
+                    if (e2 is NamedTypeSymbol { TypeKind: TypeKind.Enum, EnumUnderlyingType: var t2 })
+                        e2 = t2;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs]: There is a `TypeSymbolExtensions.EnumUnderlyingType(this TypeSymbol type)` helper method.

File: src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs [hunk 8]
```diff
@@ -2596,5 +2596,201 @@ .maxstack  1
...
+
+        [Fact]
+        public void CompileTimeRuntimeInstanceofMismatch_02()
+        {
+            var source =
+@"class Program
+{
+    static void Main()
+    {
+        object o = null;
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs]: >object o = null; [](start = 8, length = 16)

Perhaps change the code to test both `byte[]` and `sbyte[]` and report which branch was hit.

**Comment by gafter** [comment]
@cston I think I've addressed your comments.  Do you have any more?
