### PR TITLE
Account for both parts of partial methods while computing dependent s…

### LINKED ISSUE #32702: VS 2019 Preview 1 is reporting members as unused when they are
**Version Used**:  VS2019 Preview 1

**Steps to Reproduce**:

Note that this is hit or miss. It randomly seems fine with some methods but not others.

```csharp
static partial class ContainerConfig
{
   static partial void Configure( ContainerBuilder builder, Assembly assembly )
    {
     builder.ConfigureMvcBindings()
                .ConfigureCoreBindings();
     builder.ConfigureLogging();
   }  

   //CodeLens says ref count = 1, method is marked as unused
   private static ContainerBuilder ConfigureCoreBindings( this ContainerBuilder builder )
   {
       return builder;
   }

   //CodeLens says ref count = 1, method is seen as used
   public static ContainerBuilder ConfigureMvcBindings( this ContainerBuilder builder )
   {
      return builder;
   }

   //CodeLens says ref count = 1, method is seen as unused
   private static ContainerBuilder ConfigureLogging( this ContainerBuilder builder )
   {
      return builder;
   }
}
```

This seems to be working correctly in VS 2018 15.9.4. Closing and reopening VS doesn't change anything.

**Expected Behavior**:

Members that are being used are not marked as unused.

**Actual Behavior**:

Some members that are clearly being used in the same source file are still being marked as unused. The CodeLens reference count is correct but Roslyn doesn't seem to detect the reference.

unusedmembers

### PR DESCRIPTION
**Pull request by mavasani**
…ymbols for symbol end action

We invoke symbol end actions for named type symbols after symbol callbacks have been made for all its member symbols. However, we did not account for both parts of partial methods, which means we would end up with a symbol end callback for a named type prior to the partial implementation part being analyzed. This caused the remove unused member analyzer in IDE to incorrectly flag private members referenced in partial methods.

Fixes #32702

### CODE REVIEW

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs [hunk 1]
```diff
@@ -173,6 +173,16 @@ void processMembers(IEnumerable<ISymbol> members)
...
                                 memberSet.Add(member);
+
+                                // Ensure that we include symbols for both parts of partial methods.
+                                if (member is IMethodSymbol method)
+                                {
+                                    var otherPartOfPartialOpt = method.PartialDefinitionPart ?? method.PartialImplementationPart;
+                                    if (otherPartOfPartialOpt != null)
+                                    {
+                                        memberSet.Add(otherPartOfPartialOpt);
+                                    }
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs]: 1. ick.  too bad this just isn't in the members list.  but i can see the problems that would cause as well.  
2. do we not have an AddIfNotNull extension here?  that might clean things up.

Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs]: > do we not have an AddIfNotNull extension here

I did not find any such existing extension method on HashSet.

File: src/EditorFeatures/CSharpTest/RemoveUnusedMembers/RemoveUnusedMembersTests.cs [hunk 2]
```diff
@@ -2237,6 +2237,35 @@ partial class MyClass
...
+        public async Task UsedExtensionMethod_ReferencedFromPartialMethod()
+        {
+            await TestDiagnosticMissingAsync(
+@"
+<Workspace>
+    <Project Language=""C#"" AssemblyName=""Assembly1"" CommonReferences=""true"">
+        <Document>
+static partial class B
+{
+    static partial void PartialMethod(A a);
```
Comment (genlu) [inline src/EditorFeatures/CSharpTest/RemoveUnusedMembers/RemoveUnusedMembersTests.cs]: Isn't this supposed to be the declaration for the implementation below? Signature doesn't match.

File: src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs [hunk 3]
```diff
@@ -2913,5 +2913,69 @@ public void TestSymbolStartAnalyzer_NestedOperationAction_Inside_AllSymbolKinds(
                 Diagnostic("SymbolStartRuleId").WithArguments("e1", "Analyzer5").WithLocation(1, 1),
                 Diagnostic("SymbolStartRuleId").WithArguments("f1", "Analyzer6").WithLocation(1, 1));
         }
+
+        [Fact, WorkItem(32702, "https://github.com/dotnet/roslyn/issues/32702")]
+        public void TestInvocationInPartialMethod()
```
Comment (genlu) [inline src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs]: What are these two tests doing?

**Comment by mavasani** [comment]
Ping @dotnet/roslyn-compiler for reviews.

**Comment by mavasani** [comment]
Ping @dotnet/roslyn-compiler for reviews.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs [hunk 4]
```diff
@@ -173,6 +173,16 @@ void processMembers(IEnumerable<ISymbol> members)
                             {
                                 memberSet = memberSet ?? new HashSet<ISymbol>();
                                 memberSet.Add(member);
+
+                                // Ensure that we include symbols for both parts of partial methods.
+                                if (member is IMethodSymbol method)
```
Comment (jcouv) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs]: are methods the only symbol that can be partial?

Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs]: I believe they are the only ones where they have a different symbol for other part of partial, unless I am unaware of another such symbol kind.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs [hunk 5]
```diff
@@ -173,6 +173,16 @@ void processMembers(IEnumerable<ISymbol> members)
...
+                                {
+                                    var otherPartOfPartialOpt = method.PartialDefinitionPart ?? method.PartialImplementationPart;
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs]: >method.PartialDefinitionPart ?? method.PartialImplementationPart [](start = 64, length = 64)

Why are we trying both? Don't we know which symbol is going to be in the members list when both declarations are present? I assume that would be the definition part.

Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs]: Personally, I wasn't sure what part is returned by `GetMembers()` invocation and was just playing safe. If you are certain that `GetMembers()` always returns the definition part (and that cannot change in future), then I can change the above code to just add `PartialImplementationPart`, if non-null.

Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs]: I see we do remove the implementation part [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Symbols/Source/SourceMemberContainerSymbol.cs,2529), safe to assume that will always be guaranteed?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs [hunk 6]
```diff
@@ -173,6 +173,16 @@ void processMembers(IEnumerable<ISymbol> members)
...
+                                    if (otherPartOfPartialOpt != null)
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerManager.AnalyzerExecutionContext.cs]: >otherPartOfPartialOpt != null [](start = 40, length = 29)

Consider casting to object for the null check, or use ```is null``` check instead.

File: src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs (hunk 3 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs]: >TestInvocationInPartialMethod [](start = 20, length = 29)

Does it make sense to add direct tests for the component that we are fixing? Imagine that the fix is undone by mistake, would these tests appear flaky because they will be passing one time and fail another?

Comment (mavasani) [reply src/Compilers/CSharp/Test/Semantic/Diagnostics/DiagnosticAnalyzerTests.cs]: I did run the added tests bunch of times prior to the fix and they failed consistently. However, I agree with you that we probably need a better deterministic testing strategy for symbol start/end action based analyzers - I'd like to delay that work until we do see flakiness in current tests though.

**Comment by mavasani** [comment]
@jinujoseph @vatsalyaagrawal for approval
