### PR TITLE
Fix InvalidOperationException in AbstractRemoveUnusedParametersAndVal…

### LINKED ISSUE #37326: InvalidOperationException from CSharpRemoveUnusedParametersAndValuesDiagnosticAnalyzer
I'm seeing this message a lot in the Error List:

&gt;Analyzer 'Microsoft.CodeAnalysis.CSharp.RemoveUnusedParametersAndValues.CSharpRemoveUnusedParametersAndValuesDiagnosticAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'This program location is thought to be unreachable.'.

There's no file/llne reference for this message pointing to something that might need fixing.
 
The longer I run VS, the more instances of this message I see (i'm up to 10 now) and the only way I've found to get rid of them is to restart VS.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/649894/invalidoperationexception-from-csharpremoveunusedp.html
VSTS ticketId: 948443_
_These are the original issue comments:_

Visual Studio Feedback System on 7/18/2019, 01:40 AM (6 hours ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
Visual Studio Feedback System on 7/18/2019, 06:32 AM (73 min ago): <markdown><p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

### PR DESCRIPTION
**Pull request by mavasani**
…uesDiagnosticAnalyzer.ShouldReportUnusedParameters

We recently changed the enum values for `UnusedParametersPreference` (see https://github.com/dotnet/roslyn/commit/ee61cc53ff02b55df8c9d756235c0e1085dafa4b), which seems to lead to this exception if customers had explicitly changed this option in the Tools Option page prior to that fix. I have changed the code to be much more defensive.

Fixes #37326

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/RemoveUnusedParametersAndValues/RemoveUnusedParametersTests.cs [hunk 1]
```diff
@@ -1290,6 +1290,35 @@ public async Task RegressionTest_ShouldReportUnusedParameter()
 
 public interface IFoo { event Action Fooed; }
 
+public sealed class C : IDisposable
+{
+    private readonly Task<IFoo> foo;
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/RemoveUnusedParametersAndValues/RemoveUnusedParametersTests.cs]: can't use 'foo'.

File: src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs [hunk 2]
```diff
@@ -280,15 +280,12 @@ public bool IsComputingUnusedParams(ISymbol symbol)
                 return false;
             }
 
-            switch (unusedParametersPreference)
+            if (unusedParametersPreference == UnusedParametersPreference.NonPublicMethods)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/RemoveUnusedParametersAndValues/AbstractRemoveUnusedParametersAndValuesDiagnosticAnalyzer.cs]: should we have some part of our stack look for the value '2' and attempt to change it to '1'?  i.e. in the code that reads/writes this from the VS option system.

File: src/EditorFeatures/CSharpTest/RemoveUnusedParametersAndValues/RemoveUnusedParametersTests.cs (hunk 1 above)
Comment (mavasani) [reply src/EditorFeatures/CSharpTest/RemoveUnusedParametersAndValues/RemoveUnusedParametersTests.cs]: Ah, I copied an existing test. Let me change both the tests.
