### PR TITLE
Fixed Intellisense suggestion non-viable constructor call in delegating constructor

### LINKED ISSUE #2579: Intellisense suggests non-viable constructor call in delegating constructor
Using VS2015 RC.

When autocompleting calls to `: this()` for delegating constructors, intellisense is suggesting that the constructor call itself:

Intellisense Suggestion

Intellisense should suggest only other constructors here.

### PR DESCRIPTION
**Pull request by zaytsev-victor**
Fixes #2579

**Customer scenario**

When autocompleting calls to ```: this()``` for delegating constructors, IntelliSense is suggesting that the constructor call itself

**Bugs this fixes:**

#2579

**Workarounds, if any**

**Risk**

Low

**Performance impact**

**Is this a regression from a previous update?**
No

**Root cause analysis:**

IntelliSense doesn't exclude current constructor from suggestion list. Existing tests verifies incorrect behavior.

**How was the bug found?**

customer reported

### CODE REVIEW

File: src/Features/CSharp/Portable/SignatureHelp/ConstructorInitializerSignatureHelpProvider.cs [hunk 1]
```diff
@@ -82,8 +82,11 @@ private static bool IsArgumentListToken(ConstructorInitializerSyntax expression,
                 return null;
             }
 
+            var currentCunstructor = semanticModel.GetDeclaredSymbol(( constructorInitializer.Parent as ConstructorDeclarationSyntax ));
```
Comment (sharwell) [inline src/Features/CSharp/Portable/SignatureHelp/ConstructorInitializerSignatureHelpProvider.cs]: :bulb: currentC**o**nstructor

File: src/Features/CSharp/Portable/SignatureHelp/ConstructorInitializerSignatureHelpProvider.cs [hunk 2]
```diff
@@ -82,8 +82,11 @@ private static bool IsArgumentListToken(ConstructorInitializerSyntax expression,
...
+
             var symbolDisplayService = document.Project.LanguageServices.GetService<ISymbolDisplayService>();
             var accessibleConstructors = type.InstanceConstructors
+                                             .WhereAsArray(c => c != currentCunstructor)
```
Comment (sharwell) [inline src/Features/CSharp/Portable/SignatureHelp/ConstructorInitializerSignatureHelpProvider.cs]: :bulb: I would prefer this condition be merged with the next in order to avoid creating this array unnecessarily

Comment (zaytsev-victor) [inline src/Features/CSharp/Portable/SignatureHelp/ConstructorInitializerSignatureHelpProvider.cs]: Good point, thanks!

File: src/Features/CSharp/Portable/SignatureHelp/ConstructorInitializerSignatureHelpProvider.cs (hunk 1 above)
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/SignatureHelp/ConstructorInitializerSignatureHelpProvider.cs]: No parens needed.
No surrounding spaces needed.
Should just be a straight case as all ConstructorInitializers must be parented by a ConstructorDeclaration.

Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/SignatureHelp/ConstructorInitializerSignatureHelpProvider.cs]: "Constructor" not "Custructor" :)

File: src/Features/CSharp/Portable/SignatureHelp/ConstructorInitializerSignatureHelpProvider.cs [hunk 3]
```diff
@@ -82,9 +82,11 @@ private static bool IsArgumentListToken(ConstructorInitializerSyntax expression,
                 return null;
             }
 
+            var currentConstructor = semanticModel.GetDeclaredSymbol(constructorInitializer.Parent);
+
             var symbolDisplayService = document.Project.LanguageServices.GetService<ISymbolDisplayService>();
             var accessibleConstructors = type.InstanceConstructors
-                                             .WhereAsArray(c => c.IsAccessibleWithin(within))
+                                             .WhereAsArray(c => c.IsAccessibleWithin(within) && c != currentConstructor)
```
Comment (Pilchie) [inline src/Features/CSharp/Portable/SignatureHelp/ConstructorInitializerSignatureHelpProvider.cs]: Nit: You should always use `.Equals` for ISymbol. They aren't guaranteed to have reference equality.

**Comment by Pilchie** [comment]
@dpoeschl do you know what is up with this failure?

**Comment by sharwell** [comment]
@dotnet-bot retest this please

**Comment by zaytsev-victor** [comment]
Any update on this?

**Comment by dpoeschl** [comment]
Hi @zaytsev-victor, sorry about the delay. We're looking at it again now and will update you soon.

**Comment by rchande** [comment]
Built and tested this locally and LGTM. Merging now. Thanks for your contribution, @zaytsev-victor!
