### PR TITLE
Produce errors on emitting attributes using default constructor of structs

### LINKED ISSUE #19394: Compiler crashes when a user defined struct is used as a well known attribute synthesized by the compiler
Example test:

```csharp
            var code = @"
namespace System.Runtime.CompilerServices
{
    public struct DynamicAttribute
    {
        public DynamicAttribute(bool[] transformFlags)
        {
        }
}
}
class T
{
    void M(dynamic x) {}
}
";

            CreateCompilationWithMscorlib(code).VerifyEmitDiagnostics(/* there should be an error */);
```

However, the compiler crashes with the following:

```
	System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
	at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
	at Microsoft.Cci.FullMetadataWriter.DefinitionIndex`1.get_Item(T item)
	at Microsoft.Cci.FullMetadataWriter.GetMethodDefinitionHandle(IMethodDefinition def)
	at Microsoft.Cci.MetadataWriter.GetCustomAttributeTypeCodedIndex(IMethodReference methodReference)
	at Microsoft.Cci.MetadataWriter.AddCustomAttributeToTable(EntityHandle parentHandle, ICustomAttribute customAttribute)
	at Microsoft.Cci.MetadataWriter.AddCustomAttributesToTable[T](IEnumerable`1 parentList, Func`2 getDefinitionHandle)
	at Microsoft.Cci.MetadataWriter.PopulateCustomAttributeTableRows(ImmutableArray`1 sortedGenericParameters)
	at Microsoft.Cci.MetadataWriter.PopulateTypeSystemTables(Int32[] methodBodyOffsets, BlobBuilder mappedFieldDataWriter, BlobBuilder resourceWriter, BlobBuilder dynamicAnalysisDataOpt, Blob& mvidFixup)
	at Microsoft.Cci.MetadataWriter.BuildMetadataAndIL(PdbWriter nativePdbWriterOpt, BlobBuilder ilBuilder, BlobBuilder mappedFieldDataBuilder, BlobBuilder managedResourceDataBuilder, Blob& mvidFixup, Blob& mvidStringFixup)
	at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean allowMissingMethodBodies, Boolean isDeterministic, CancellationToken cancellationToken)
	at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, Func`1 testSymWriterFactory, DiagnosticBag diagnostics, Boolean metadataOnly, CancellationToken cancellationToken)
	at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CompilationTestData testData, CancellationToken cancellationToken)
	at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CancellationToken cancellationToken)
	at Microsoft.CodeAnalysis.DiagnosticExtensions.GetEmitDiagnostics[TCompilation](TCompilation c, EmitOptions options, IEnumerable`1 manifestResources)
	at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyEmitDiagnostics[TCompilation](TCompilation c, EmitOptions options, DiagnosticDescription[] expected)
	at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyEmitDiagnostics[TCompilation](TCompilation c, DiagnosticDescription[] expected)
	Attributes\AttributeTests_RefReadOnly.cs(1666,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.AttributeTests_RefReadOnly.RefReadOnlyDefinitionsInsideUserDefinedIxxxsReadOnlyAttribute_Struct()
```

### PR DESCRIPTION
**Pull request by OmarTawfik**
Fixes #19394

Note: This is such a corner case that I chose to produce that error on all attributes (regardless of being optional or not) instead of crashing. This can be relaxed in the future if needed.
I also believe that getting an error about a user-defined system struct not being a class is better than having the type in your compilation, and compiling successfully without emitting the attribute.

### CODE REVIEW

File: src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs [hunk 1]
```diff
@@ -2142,10 +2142,27 @@ private void AddCustomAttributesToTable(IEnumerable<TypeReferenceWithAttributes>
 
         private void AddCustomAttributeToTable(EntityHandle parentHandle, ICustomAttribute customAttribute)
         {
-            metadata.AddCustomAttribute(
-                parent: parentHandle,
-                constructor: GetCustomAttributeTypeCodedIndex(customAttribute.Constructor(Context)),
-                value: GetCustomAttributeSignatureIndex(customAttribute));
+            IMethodReference constructor = customAttribute.Constructor(Context);
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs]: >customAttribute.Constructor(Context) [](start = 43, length = 36)

This PR make way more changes than I would expect. I thought when we discussed this issue offline, the suggestion was to perform the check in the ```customAttribute.Constructor(Context)``` call. Since the synthesized default struct constructor is not a real method, it should not be possible to get IMethodReference for it.

Comment (OmarTawfik) [reply src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs]: @AlekseyTS there are a few places in the codebase that don't expect null to be returned from `Constructor()`. I'm investigating further.

---
In reply to: [188084807](https://github.com/dotnet/roslyn/pull/26815#discussion_r188084807) [](ancestors = 188084807)

**Comment by OmarTawfik** [comment]
@AlekseyTs @dotnet/roslyn-compiler this is ready for review.

File: src/Compilers/Core/Portable/PEWriter/MetadataVisitor.cs [hunk 2]
```diff
@@ -49,7 +49,13 @@ public void Visit(IEnumerable<ICustomAttribute> customAttributes)
         public virtual void Visit(ICustomAttribute customAttribute)
         {
             this.Visit(customAttribute.GetArguments(Context));
-            this.Visit(customAttribute.Constructor(Context));
+
+            IMethodReference constructor = customAttribute.Constructor(Context, reportDiagnostics: false);
+            if (constructor != null)
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/PEWriter/MetadataVisitor.cs]: >if (constructor != null) [](start = 12, length = 24)

Consider doing this check on entry and returning without doing anything if ```constructor``` is null.

File: src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs [hunk 3]
```diff
@@ -3351,9 +3356,9 @@ private void SerializeMethodSpecificationSignature(BlobBuilder builder, IGeneric
             }
         }
 
-        private void SerializeCustomAttributeSignature(ICustomAttribute customAttribute, BlobBuilder builder)
+        private void SerializeCustomAttributeSignature(ICustomAttribute customAttribute, IMethodReference constructor, BlobBuilder builder)
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs]: >private void SerializeCustomAttributeSignature(ICustomAttribute customAttribute, IMethodReference constructor, BlobBuilder builder) [](start = 8, length = 131)

It looks like changes to this function are not necessary, consider reverting

File: src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs [hunk 4]
```diff
@@ -717,7 +717,7 @@ internal ModuleReferenceHandle GetModuleReferenceHandle(string moduleName)
             return this.GetOrAddModuleReferenceHandle(moduleName);
         }
 
-        private BlobHandle GetCustomAttributeSignatureIndex(ICustomAttribute customAttribute)
+        private BlobHandle GetCustomAttributeSignatureIndex(ICustomAttribute customAttribute, IMethodReference constructor)
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs]: >private BlobHandle GetCustomAttributeSignatureIndex(ICustomAttribute customAttribute, IMethodReference constructor) [](start = 8, length = 115)

It looks like changes to this function are not necessary, consider reverting

File: src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs (hunk 3 above)
Comment (AlekseyTs) [reply src/Compilers/Core/Portable/PEWriter/MetadataWriter.cs]: We can simply call ```Constructor``` method without requesting diagnostics

---
In reply to: [188719435](https://github.com/dotnet/roslyn/pull/26815#discussion_r188719435) [](ancestors = 188719435)

File: src/Compilers/CSharp/Portable/Emitter/Model/AttributeDataAdapter.cs [hunk 5]
```diff
@@ -28,8 +28,22 @@ ImmutableArray<Cci.IMetadataExpression> Cci.ICustomAttribute.GetArguments(EmitCo
...
         {
+            if (this.AttributeConstructor.IsDefaultValueTypeConstructor())
+            {
+                // Parameter constructors for structs exist in symbol table, but are not emitted.
+                // Produce an error since we cannot use it (instead of crashing):
+                // Details: https://github.com/dotnet/roslyn/issues/19394
+
+                if (reportDiagnostics)
+                {
+                    context.Diagnostics.Add(ErrorCode.ERR_NotAnAttributeClass, NoLocation.Singleton, this.AttributeClass);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Emitter/Model/AttributeDataAdapter.cs]: >NoLocation.Singleton [](start = 79, length = 20)

Consider using location from context.SyntaxNodeOpt when one is available

File: src/Compilers/CSharp/Portable/Emitter/Model/AttributeDataAdapter.cs [hunk 6]
```diff
@@ -28,8 +28,22 @@ ImmutableArray<Cci.IMetadataExpression> Cci.ICustomAttribute.GetArguments(EmitCo
...
+                }
+
+                return null;
+            }
+
             PEModuleBuilder moduleBeingBuilt = (PEModuleBuilder)context.Module;
             return (Cci.IMethodReference)moduleBeingBuilt.Translate(this.AttributeConstructor, (CSharpSyntaxNode)context.SyntaxNodeOpt, context.Diagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Emitter/Model/AttributeDataAdapter.cs]: >Translate [](start = 58, length = 9)

Please add an assert into this method that it is not called with DefaultValueTypeConstructor

File: src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs [hunk 7]
```diff
@@ -8878,5 +8878,50 @@ public static void Main()
...
+    public struct DynamicAttribute
+    {
+        public DynamicAttribute(bool[] transformFlags)
+        {
+        }
+    }
+}
+class T
+{
+    void M(dynamic x) {}
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs]: >dynamic [](start = 11, length = 7)

What is the behavior for ```dynamic[]``` type? Should we disallow structures in ICustomAttribute altogether regardless of what constructor is used?

File: src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.vb [hunk 8]
```diff
@@ -5639,6 +5639,25 @@ Imports TestAssembly.BothObsoleteParent.BothObsoleteChild
...
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+]]></expected>)
+        End Sub
+
+        <Fact>
+        <WorkItem(19394, "https://github.com/dotnet/roslyn/issues/19394")>
+        Public Sub WellKnownTypeAsStruct_DefaultConstructor_ParamArrayAttribute()
+            Dim code = <compilation><file name="a.vb"><![CDATA[
+Namespace System
+	public Structure ParamArrayAttribute
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.vb]: >ParamArrayAttribute [](start = 18, length = 19)

It would be good to have test targeting usage on non-default struct constructor. Perhaps with tuples?

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1)

File: src/Compilers/CSharp/Portable/Emitter/Model/AttributeDataAdapter.cs [hunk 9]
```diff
@@ -28,8 +28,22 @@ ImmutableArray<Cci.IMetadataExpression> Cci.ICustomAttribute.GetArguments(EmitCo
...
+                // Parameter constructors for structs exist in symbol table, but are not emitted.
+                // Produce an error since we cannot use it (instead of crashing):
+                // Details: https://github.com/dotnet/roslyn/issues/19394
+
+                if (reportDiagnostics)
+                {
+                    context.Diagnostics.Add(ErrorCode.ERR_NotAnAttributeClass, NoLocation.Singleton, this.AttributeClass);
+                }
+
+                return null;
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Emitter/Model/AttributeDataAdapter.cs]: Was null a possible return before this change?

File: src/Compilers/VisualBasic/Portable/Emit/AttributeDataAdapter.vb [hunk 10]
```diff
@@ -14,7 +14,19 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols
...
+            If Me.AttributeConstructor.IsDefaultValueTypeConstructor() Then
+                ' Parameter constructors for structs exist in symbol table, but are not emitted.
+                ' Produce an error since we cannot use it (instead of crashing):
+                ' Details: https://github.com/dotnet/roslyn/issues/19394
+
+                If reportDiagnostics Then
+                    context.Diagnostics.Add(ERRID.ERR_AttributeMustBeClassNotStruct1, NoLocation.Singleton, Me.AttributeClass)
+                End If
+
+                Return Nothing
```
[the remark this answers is not in the document]
Comment (OmarTawfik) [reply src/Compilers/VisualBasic/Portable/Emit/AttributeDataAdapter.vb]: No it was not. Now we check at callsites for nullability.

---
In reply to: [188724441](https://github.com/dotnet/roslyn/pull/26815#discussion_r188724441) [](ancestors = 188724441)

File: src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs (hunk 7 above)
Comment (OmarTawfik) [reply src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs]: The crash only happens with default constructors. For structs and non default constructors, we emit successfully. Changing that would be a breaking change that we need to take to LDM.

---
In reply to: [188722425](https://github.com/dotnet/roslyn/pull/26815#discussion_r188722425) [](ancestors = 188722425)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit/Attributes/AttributeTests_WellKnownAttributes.cs]: > The crash only happens with default constructors. For structs and non default constructors, we emit successfully. Changing that would be a breaking change that we need to take to LDM.

Could you please open an issue to follow-up or start a conversation with Compatibility Council? This is not blocking, but it would be good to make a decision on this sooner rather than later. 

---
In reply to: [189076550](https://github.com/dotnet/roslyn/pull/26815#discussion_r189076550) [](ancestors = 189076550,188722425)

**Comment by OmarTawfik** [comment]
@jaredpar for code review and possible ask mode approval :)

**Comment by jaredpar** [comment]
approved
