### PR TITLE
Avoid premature full binding of a receiver as a value in the process of binding possible type-or-value receiver (so-called “Color Color” scenario)

### LINKED ISSUE #45739: code fix of IDE0002 produces invalid code when a constant has same name as its type
**Version Used**: 
Visual Studio 2019 16.6.2

**Steps to Reproduce**:

```C#
using System;

namespace N
{
    public class C
    {
        public const DateTimeKind DateTimeKind = System.DateTimeKind.Utc;
    }
}
```

**Expected Behavior**:
no suggestion is provided

**Actual Behavior**:
code fix suggested, which simplifies code to
```C#
using System;

namespace N
{
    public class C
    {
        public const DateTimeKind DateTimeKind = DateTimeKind.Utc;
    }
}
```
which causes error
```
CS0110 The evaluation of the constant value for 'C.DateTimeKind' involves a circular definition
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #45739.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/ColorColorTests.cs [hunk 1]
```diff
@@ -2368,6 +2368,140 @@ instance void .ctor () cil managed
...
+}
+";
+
+            CompileAndVerify(source, expectedOutput: "TrueTrue")
+                .VerifyDiagnostics();
+        }
+
+        [WorkItem("https://github.com/dotnet/roslyn/issues/45739")]
+        [Fact]
+        public void ConstFieldEnum_02()
```
Comment (Rekkonnect) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ColorColorTests.cs:2414]: We should also test that
```cs
public const Color Color = Color.Red | Color.Red;
```
is not considered circular #Resolved

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review  #Closed

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review  #Closed

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review  #Closed

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review  #Closed

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review  #Closed

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review  #Closed

**Comment by RikkiGibson** [comment]
Taking a look shortly. #Closed

File: src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Binders/PlaceholderLocalBinder.cs [hunk 2]
```diff
@@ -73,14 +73,7 @@ internal sealed override void LookupSymbolsInSingleBinder(
...
             {
-                var valueText = name.Substring(2);
-                ulong address;
-                if (!ulong.TryParse(valueText, NumberStyles.AllowHexSpecifier, CultureInfo.InvariantCulture, out address))
-                {
-                    // Invalid value should have been caught by Lexer.
-                    throw ExceptionUtilities.UnexpectedValue(valueText);
-                }
-                var local = new ObjectAddressLocalSymbol(_containingMethod, name, this.Compilation.GetSpecialType(SpecialType.System_Object), address);
+                var local = new ObjectAddressLocalSymbol(_containingMethod, name, this.Compilation.GetSpecialType(SpecialType.System_Object));
```
Comment (RikkiGibson) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Binders/PlaceholderLocalBinder.cs:76]: I didn't follow why this change is being made, could you please explain? #Resolved

Comment (AlekseyTs) [reply src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/Binders/PlaceholderLocalBinder.cs:76]: > I didn't follow why this change is being made, could you please explain?

Added asserts exposed a bug in comparison of ```ObjectAddressLocalSymbol```s. We are not reusing them and were never considered them equal, i.e. representing the same entity. I went ahead and implemented equality for ```ObjectAddressLocalSymbol```. In the process, I incorporated the code above into constructor, that makes it clear what do we need to compare.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review  #Closed

**Review by RikkiGibson — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review #Closed

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review #Closed

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review #Closed

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review #Closed

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review on a PR opened for review on Nov 1st. #Closed

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review on a PR opened for review on Nov 1st. #Closed

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review on a PR opened for review on Nov 1st. #Closed

File: src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs [hunk 3]
```diff
@@ -403,10 +403,9 @@ internal partial class BoundBinaryOperator
     {
         public override ConstantValue? ConstantValueOpt => Data?.ConstantValue;
 
-        public override Symbol? ExpressionSymbol => this.BinaryOperatorMethod;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs:406]: Regarding comment on `BoundTypeOrValueData` type (line 669 to 672)

`ValueExpression` and `TypeExpression` were removed so the comment above should not reference those members.

Also, the justification provided for this type was to hide some bound nodes from the regular HasErrors bound node handling. Is this still the case?
Could this information be inlined into `BoundTypeOrValueExpression`? Or should the comment be updated? #Closed

File: src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs [hunk 4]
```diff
@@ -1680,7 +1680,7 @@ private ImmutableArray<ISymbol> LookupSymbolsInternal(
                         }
                         else
                         {
-                            Debug.Assert(symbol.IsExtensionBlockMember());
+                            Debug.Assert(symbol.GetIsNewExtensionMember());
                             if (SourceNamedTypeSymbol.ReduceExtensionMember(binder.Compilation, symbol, receiverType, wasExtensionFullyInferred: out _) is { } compatibleSubstitutedMember)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs:1684]: Regarding comment on `case BoundKind.TypeOrValueExpression:` in `GetSemanticSymbols` (line 3424)

Comment above seems out-of-date (remove?) #Closed

File: src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs [hunk 5]
```diff
@@ -672,34 +672,24 @@ public override bool SuppressVirtualCalls
     //       A BoundTypeOrValueExpression should never have errors if it is present in the tree.
     internal readonly struct BoundTypeOrValueData : System.IEquatable<BoundTypeOrValueData>
     {
+        public Binder Binder { get; }
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs]: Testing comment location. 
Comment was left using VSCode review support (GitHub PullRequest extension). Location is BoundTypeOrValueData.Binder (line 675) #Closed

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs [hunk 6]
```diff
@@ -1955,28 +1953,28 @@ private BoundExpression ReplaceTypeOrValueReceiver(BoundExpression receiver, boo
...
-                        return typeOrValue.Data.TypeExpression;
+                        return typeOrValue.Data.Binder.BindNamespaceOrType(identifier, diagnostics);
                     }
                     else
                     {
-                        diagnostics.AddRange(typeOrValue.Data.ValueDiagnostics);
-                        return CheckValue(typeOrValue.Data.ValueExpression, BindValueKind.RValue, diagnostics);
+                        var boundValue = typeOrValue.Data.Binder.BindIdentifier(identifier, invoked: false, indexed: false, diagnostics: diagnostics);
+
+                        Debug.Assert(typeOrValue.Type.Equals(boundValue.Type, TypeCompareKind.ConsiderEverything));
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs:1973]: `Debug.Assert(typeOrValue.Type.Equals(boundValue.Type, TypeCompareKind.ConsiderEverything));` (line 1973)
Could the nullability of the value differ? For example `Color? Color = ...;` the `Color` value would have type `Color?` #Closed

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs [hunk 7]
```diff
@@ -2385,6 +2383,17 @@ private BoundExpression BindNameofOperatorInternal(InvocationExpressionSyntax no
                         EnsureNameofExpressionSymbols(methodGroup, diagnostics);
                     }
                 }
+
+                boundArgument = methodGroup.Update(
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs:2387]: `boundArgument = methodGroup.Update(` (line 2387)
Can we use `FixMethodGroupWithTypeOrValue`?
There is a slight difference in behavior: here we're calling `ReplaceTypeOrValueReceiver` and therefore `BindToNaturalType` unconditionally. Is that difference intentional? #Closed

Comment (jcouv) [reply src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs:2387]: Never mind. `FixMethodGroupWithTypeOrValue` needs a conversion

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 8]
```diff
@@ -180,7 +192,7 @@ private BoundBadExpression BadExpression(SyntaxNode syntax, LookupResultKind res
             return new BoundBadExpression(syntax,
                 resultKind,
                 symbols,
-                childNodes.SelectAsArray((e, self) => self.BindToTypeForErrorRecovery(e), this),
+                childNodes.SelectAsArray((e, self) => self.AdjustBadExpressionChild(self.BindToTypeForErrorRecovery(e)), this),
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:195]: `self.AdjustBadExpressionChild(self.BindToTypeForErrorRecovery(e))` (line 195)
nit: Would it be simpler for `BindToTypeForErrorRecovery` to handle calling `AdjustBadExpressionChild`, even if it involves a tiny bit of extra work in scenarios were a type-or-value couldn't not be encountered? #Resolved

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 9]
```diff
@@ -2211,6 +2145,7 @@ private BoundExpression BindNonMethod(SimpleNameSyntax node, Symbol symbol, Bind
                             }
                         }
 
+                        // The type calculation here should be kept in sync with logic in BindLeftIdentifierOfPotentialColorColorMemberAccess.
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: `// The type calculation here should be kept in sync with logic in BindLeftIdentifierOfPotentialColorColorMemberAccess.` (line 2148)
It's not obvious what type calculation this comment is referring to
 #Closed

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 10]
```diff
@@ -2254,11 +2189,108 @@ private BoundExpression BindNonMethod(SimpleNameSyntax node, Symbol symbol, Bind
                     }
 
                 case SymbolKind.RangeVariable:
+                    // The type calculation here should be kept in sync with logic in BindLeftIdentifierOfPotentialColorColorMemberAccess.
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:2205]: Comment refers to `case SymbolKind.Field:` a few lines above (line 2171)
~~Should a similar comment be left in the field case?~~
~~`BindLeftIdentifierOfPotentialColorColorMemberAccess` has a case for fields when computing type~~

Never mind. I see it's in `BindFieldAccess` #Closed

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 11]
```diff
@@ -7523,63 +7555,87 @@ private BoundExpression BindLeftIdentifierOfPotentialColorColorMemberAccess(Iden
...
-                // BindFieldAccess may insert a conversion if binding occurs
-                // within an enum member initializer.
-                leftSymbol = ((BoundConversion)boundValue).Operand.ExpressionSymbol;
+                return bindAsValue(left, diagnostics);
             }
-            else
+
+            var lookupResult = LookupResult.GetInstance();
+            var useSiteInfo = CompoundUseSiteInfo<AssemblySymbol>.Discarded;
+            this.LookupIdentifier(lookupResult, left, invoked: false, ref useSiteInfo);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:7584]: Not directly related to this PR: Does `BindLeftIdentifierOfPotentialColorColorMemberAccess` need to worry about `nint` and `_` like `BindIdentifier` does?
`nint nint = 0;` and `_ _ = null; class _ { }` appear legal. #Closed

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs (hunk 6 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs:1973]: > Could the nullability of the value differ? 

Bound tree doesn't preserve top level nullability of types and we are binding simple identifiers. Perhaps nested nullability can somehow sneak in. Since this is an assert, I am not worried about this and I am comfortable going with a possibly too strong condition. We can relax it once the assert starts causing problems.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 11 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:7584]: > Does `BindLeftIdentifierOfPotentialColorColorMemberAccess` need to worry about `nint` and `_` like `BindIdentifier` does?

Could you please elaborate? What code in `BindIdentifier` do you refer to?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:7584]: It looks like this is legal
```
_ _ = null;

_.ReferenceEquals(null, null);

class _ { } 
```

This seems correct because `-` in this case is identifier and the name of the type.

The following is illegal because the name of the type is not "nint", it is "IntPtr"
```
nint nint = 0;

nint.ReferenceEquals(null, null);
```

However, this works:
```
using System;

nint IntPtr = 0;
IntPtr.ReferenceEquals(null, null);
```

Does this answer the question?

File: src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs (hunk 3 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/BoundTree/BoundExpression.cs:406]: Removed the `BoundTypeOrValueData` type

File: src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs (hunk 4 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs:1684]: > Comment above seems out-of-date (remove?)

Adjusted

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 9 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: > It's not obvious what type calculation this comment is referring to

Clarified

File: src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs (hunk 4 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs:1684]: nit: There's still a problem with the comment. It says:
```
// If we're seeing a node of this kind, then we failed to resolve the member access
                        // as either a type or a property/field/event/local/parameter.  In such cases,
                        // the second interpretation applies.
```
But then we assert: `Debug.Assert(boundNode is not BoundTypeOrValueExpression);`

I'd just remove the comment.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs (hunk 8 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:195]: What was the resolution?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:195]: > What was the resolution?

Since this was a "nit" I didn't spend much time thinking about that and didn't feel like this comment needs a specific response. I took it under advisement. I am comfortable with the current approach.
I felt that suggested simplification won't be appropriate because the node has type, and therefore, should not be changed by a helper the sole purpose of which is to figure out the type, even when that operation is requested as part of an error recovery.

File: src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs (hunk 4 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Compilation/CSharpSemanticModel.cs:1684]: The comment is correct. The assert is there to help us to make sure that we do not leave `BoundTypeOrValueExpression` in the tree. If it is there, we can recover, but we prefer not getting in a situation like that.
