### PR TITLE
Change implementation of a SynthesizedRecordConstructor to act more like a constructor declared in source.

### LINKED ISSUE #44781: User defined constructors in a record are not required to call primary constructor
This is an existing test. Observe IL for user-defined "C..ctor(C)". It delegates to object constructor and no error is reported.

```
        [Fact]
        public void RecordClone2()
        {
            var comp = CreateCompilation(@"
data class C(int x, int y)
{
    public C(C other) { }
}");
            comp.VerifyDiagnostics();

            var c = comp.GlobalNamespace.GetTypeMember("C");
            var clone = c.GetMethod(WellKnownMemberNames.CloneMethodName);
            Assert.Equal(0, clone.Arity);
            Assert.Equal(0, clone.ParameterCount);
            Assert.Equal(c, clone.ReturnType);

            var ctor = (MethodSymbol)c.GetMembers(".ctor")[0];
            Assert.Equal(1, ctor.ParameterCount);
            Assert.True(ctor.Parameters[0].Type.Equals(c, TypeCompareKind.ConsiderEverything));

            var verifier = CompileAndVerify(comp, verify: Verification.Fails);
            verifier.VerifyIL("C." + WellKnownMemberNames.CloneMethodName, @"
{
  // Code size        7 (0x7)
  .maxstack  1
  IL_0000:  ldarg.0
  IL_0001:  newobj     ""C..ctor(C)""
  IL_0006:  ret
}
");
            verifier.VerifyIL("C..ctor(C)", @"
{
  // Code size        7 (0x7)
  .maxstack  1
  IL_0000:  ldarg.0
  IL_0001:  call       ""object..ctor()""
  IL_0006:  ret
}");
        }
```

### LINKED ISSUE #44782: Generated copy constructor executes regular field initializers before invoking base constructor
```
data class C(int x)
{
    public int y = WhyCopyConstructorCallsMe();
    
    private static int WhyCopyConstructorCallsMe() => 0;
}
```

IL:
```
    .method public hidebysig specialname rtspecialname 
        instance void .ctor (
            class C ''
        ) cil managed 
    {
        // Method begins at RVA 0x20b0
        // Code size 43 (0x2b)
        .maxstack 8

        IL_0000: ldarg.0
        IL_0001: call int32 C::WhyCopyConstructorCallsMe()
        IL_0006: stfld int32 C::y
        IL_000b: ldarg.0
        IL_000c: call instance void [System.Private.CoreLib]System.Object::.ctor()
        IL_0011: nop
        IL_0012: ldarg.0
        IL_0013: ldarg.1
        IL_0014: ldfld int32 C::'<x>k__BackingField'
        IL_0019: stfld int32 C::'<x>k__BackingField'
        IL_001e: ldarg.0
        IL_001f: ldarg.1
        IL_0020: ldfld int32 C::y
        IL_0025: stfld int32 C::y
        IL_002a: ret
    } // end of method C::.ctor
```

https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRIMYHsEBNkA0MIAlgDYG4gDUAPrrFAAQACATEwMIAUJAdjCYAPAJQBYAFABvSUzmsAzE36CAnkwC8TAOoALVZywAHA1j7IYCOBhg5OUMmWQBZCNxEBuWfO9yjCEgA3WAhWAEYANmUBHX1DE0NzS2tbBHtHFzcRTQA+JgAGLwkAX0lJPigAWxQjKAxQljCAOgAlOAESaqbDSqNyCAQAZQHAknrkSRkJeUUmZGgyCFxWDgBJZABRIRgBirJVvhIYXyYpmdKSySA===

This isn't going to work. Primary constructor parameters are in scope in initializers, but copy constructor doesn't have them.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #44781.
Fixes #44782.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@agocke, @RikkiGibson, @cston, @jcouv, @dotnet/roslyn-compiler Please review.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs [hunk 1]
```diff
@@ -2316,22 +2316,72 @@ private static void AddNestedTypesToDictionary(Dictionary<string, ImmutableArray
...
-            public readonly ArrayBuilder<ImmutableArray<FieldOrPropertyInitializer>> StaticInitializers = ArrayBuilder<ImmutableArray<FieldOrPropertyInitializer>>.GetInstance();
-            public readonly ArrayBuilder<ImmutableArray<FieldOrPropertyInitializer>> InstanceInitializers = ArrayBuilder<ImmutableArray<FieldOrPropertyInitializer>>.GetInstance();
+            public readonly ArrayBuilder<ArrayBuilder<FieldOrPropertyInitializer.Builder>> StaticInitializers = ArrayBuilder<ArrayBuilder<FieldOrPropertyInitializer.Builder>>.GetInstance();
+            public readonly ArrayBuilder<ArrayBuilder<FieldOrPropertyInitializer.Builder>> InstanceInitializers = ArrayBuilder<ArrayBuilder<FieldOrPropertyInitializer.Builder>>.GetInstance();
             public readonly ArrayBuilder<SyntaxReference> IndexerDeclarations = ArrayBuilder<SyntaxReference>.GetInstance();
+            public ParameterListSyntax? RecordConstructorParamList;
+            public TypeDeclarationSyntax? RecordDeclarationWithParameters;
+            public ArrayBuilder<FieldOrPropertyInitializer.Builder>? InstanceInitializersForRecordDeclarationWithParameters;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:2324]: >InstanceInitializersForRecordDeclarationWithParameters [](start = 69, length = 54)

It seems `InstanceInitializersForRecordDeclarationWithParameters` is only ever read in debug-only code. Can we remove it or make it debug-only?

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs [hunk 2]
```diff
@@ -2750,40 +2821,29 @@ private void AddEnumMembers(MembersAndInitializersBuilder result, EnumDeclaratio
             }
         }
 
-        private static void AddInitializer(ref ArrayBuilder<FieldOrPropertyInitializer>? initializers, ref int aggregateSyntaxLength, FieldSymbol? fieldOpt, CSharpSyntaxNode node)
+        private static void AddInitializer(ref ArrayBuilder<FieldOrPropertyInitializer.Builder>? initializers, FieldSymbol? fieldOpt, CSharpSyntaxNode node)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:2824]: >ArrayBuilder [](start = 47, length = 12)

Consider `ImmutableArray<FieldOrPropertyInitializer.Builder>.Builder?` to make it clear that we're not using pooled instances, so we won't have to worry about freeing. That would also propagate to `AddNonTypeMembers`, `AddInitializers` and `MembersAndInitializersBuilder.InstanceInitializersForRecordDeclarationWithParameters`

Or, if we can remove `InstanceInitializersForRecordDeclarationWithParameters`, then can we use pooled instances (freeing in `AddInitializers`)?

nit: consider making this a local function in `AddNonTypeMembers`.

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordConstructor.cs [hunk 3]
```diff
@@ -5,59 +5,80 @@
...
-                allowRefOrOut: true,
-                allowThis: false,
-                addRefReadOnlyModifier: false);
-        }
-
-        internal override LexicalSortKey GetLexicalSortKey()
-        {
-            // We need a separate sort key because struct records will have two synthesized
-            // constructors: the record constructor, and the parameterless constructor
-            return LexicalSortKey.SynthesizedRecordCtor;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordConstructor.cs:39]: >LexicalSortKey.SynthesizedRecordCtor; [](start = 19, length = 37)

Can we remove the sort key then (if no other reference)?

File: src/Compilers/CSharp/Portable/Lowering/Instrumentation/DebugInfoInjector.cs [hunk 4]
```diff
@@ -85,6 +85,12 @@ public override BoundStatement InstrumentFieldOrPropertyInitializer(BoundStateme
 
         private static BoundStatement InstrumentFieldOrPropertyInitializer(BoundStatement rewritten, SyntaxNode syntax)
         {
+            if (syntax.IsKind(SyntaxKind.Parameter))
+            {
+                // This is an initialization of a generated property based on record parameter.
+                return AddSequencePoint(rewritten);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/Instrumentation/DebugInfoInjector.cs:91]: Do we have a test to show the sequence point?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs [hunk 5]
```diff
@@ -701,6 +701,13 @@ public override BoundNode VisitArrayAccess(BoundArrayAccess node)
         internal static bool IsFieldOrPropertyInitializer(BoundStatement initializer)
         {
             var syntax = initializer.Syntax;
+
+            if (syntax.IsKind(SyntaxKind.Parameter))
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter.cs:705]: nit: by the looks of this and previous code, it seems we are missing information in bound nodes (we have to go back to syntax). Consider filing an issue.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs [hunk 6]
```diff
@@ -109,16 +109,35 @@ public void RecordProperties_01()
 using System;
 data class C(int X, int Y)
 {
+    int Z = 123;
     public static void Main()
     {
         var c = new C(1, 2);
         Console.WriteLine(c.X);
         Console.WriteLine(c.Y);
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:117]: >Console.WriteLine(c.Y); [](start = 8, length = 23)

nit: Consider printing `c.Z` as well.

File: src/Compilers/CSharp/Portable/CSharpResources.resx [hunk 7]
```diff
@@ -6163,4 +6163,7 @@ To remove the warning, you can use /reference instead (set the Embed Interop Typ
   <data name="ERR_UnexpectedArgumentList" xml:space="preserve">
     <value>Unexpected argument list.</value>
   </data>
+  <data name="ERR_UnexpectedOrMissingConstructorInitializerInRecord" xml:space="preserve">
+    <value>A constructor declared in a record with parameters must have 'this' constructor initializer.</value>
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/CSharpResources.resx:6167]: >a record with parameters [](start = 37, length = 24)

nit: we'll want to align on terminology. Andy has been using "positional records" for such records. I lean towards "record with positional members".

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:2324]: > It seems InstanceInitializersForRecordDeclarationWithParameters is only ever read in debug-only code. Can we remove it or make it debug-only? 

Of course it is read, otherwise record properties and other fields with initializers wouldn't be initialized. This instance is in the InstanceInitializers builder.

---
In reply to: [434398822](https://github.com/dotnet/roslyn/pull/44803#discussion_r434398822) [](ancestors = 434398822)

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:2824]: I don't think it is worth making changes that you suggest. Besides none of that is added in this PR. 

---
In reply to: [434399118](https://github.com/dotnet/roslyn/pull/44803#discussion_r434399118) [](ancestors = 434399118)

File: src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordConstructor.cs (hunk 3 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Synthesized/Records/SynthesizedRecordConstructor.cs:39]: > Can we remove the sort key then (if no other reference)?

Sure. I will do this in a following PR, unless a change is needed for this one.

---
In reply to: [434399175](https://github.com/dotnet/roslyn/pull/44803#discussion_r434399175) [](ancestors = 434399175)

File: src/Compilers/CSharp/Portable/Lowering/Instrumentation/DebugInfoInjector.cs (hunk 4 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/Instrumentation/DebugInfoInjector.cs:91]: We don't at the moment. We will have to test debugging support at some point, I think that should happen at that time. I can make an explicit note in Test Plan.

---
In reply to: [434399243](https://github.com/dotnet/roslyn/pull/44803#discussion_r434399243) [](ancestors = 434399243)

File: src/Compilers/CSharp/Portable/CSharpResources.resx (hunk 7 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/CSharpResources.resx:6167]: > nit: we'll want to align on terminology. Andy has been using "positional records" for such records. I lean towards "record with positional members".

Agree, at some point we should do that.

---
In reply to: [434399626](https://github.com/dotnet/roslyn/pull/44803#discussion_r434399626) [](ancestors = 434399626)

File: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs (hunk 6 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:117]: > nit: Consider printing c.Z as well.

I will add this in the next PR. For now, it is clear in IL that this field is also initialized.

---
In reply to: [434399596](https://github.com/dotnet/roslyn/pull/44803#discussion_r434399596) [](ancestors = 434399596)

**Comment by AlekseyTs** [comment]
@jcouv I think I responded to all your comments

File: src/Compilers/CSharp/Portable/Lowering/Instrumentation/DebugInfoInjector.cs (hunk 4 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/Instrumentation/DebugInfoInjector.cs:91]: BTW, this code path is getting hit by the existing tests. I just didn't add the test to verify presence of the sequence point.

---
In reply to: [434690200](https://github.com/dotnet/roslyn/pull/44803#discussion_r434690200) [](ancestors = 434690200,434399243)

Comment (jcouv) [reply src/Compilers/CSharp/Portable/Lowering/Instrumentation/DebugInfoInjector.cs:91]: Yup, I understand. Added a note to test plan already (" verify sequence points"). Thanks

File: src/Compilers/CSharp/Portable/CSharpResources.resx (hunk 7 above)
Comment (jcouv) [reply src/Compilers/CSharp/Portable/CSharpResources.resx:6167]: Filed [https://github.com/dotnet/roslyn/issues/44826](https://github.com/dotnet/roslyn/issues/44826)

---
In reply to: [434694065](https://github.com/dotnet/roslyn/pull/44803#discussion_r434694065) [](ancestors = 434694065,434399626)

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 8]
```diff
@@ -3227,6 +3227,9 @@ public virtual BoundNode BindMethodBody(CSharpSyntaxNode syntax, DiagnosticBag d
         {
             switch (syntax)
             {
+                case TypeDeclarationSyntax recordDecl:
+                    return BindRecordConstructorBody(recordDecl);
```
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:3231]: > This seems strange. The constructor body isn't the only method body associated with the record type declaration, there's also all the corresponding accessors and Equals/GetHashCode.
What's the benefit of having this syntax primarily associate with the record constructor?

The other methods you mentioned do not come through here and do not have any user code in them. This method contains user code - the base arguments and possibly the explicit body in the future. For SemanticModel we need a syntax node that includes all of them. I think the TypeDeclarationSyntax is the best candidate.

---
In reply to: [434700327](https://github.com/dotnet/roslyn/pull/44803#discussion_r434700327) [](ancestors = 434700327)

[the remark this answers is not in the document]
Comment (jcouv) [reply src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:3231]: Thanks for the clarification

---
In reply to: [434709888](https://github.com/dotnet/roslyn/pull/44803#discussion_r434709888) [](ancestors = 434709888,434700327)

**Comment by AlekseyTs** [comment]
@agocke, @RikkiGibson, @cston, @dotnet/roslyn-compiler Please review, need a second sign-off.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs [hunk 9]
```diff
@@ -2426,31 +2476,52 @@ private void AddDeclaredNontypeMembers(MembersAndInitializersBuilder builder, Di
...
+                if (builder.RecordConstructorParamList is null)
+                {
+                    builder.RecordConstructorParamList = parameterList;
+                    builder.RecordDeclarationWithParameters = syntax;
+                    builder.InstanceInitializersForRecordDeclarationWithParameters = new ArrayBuilder<FieldOrPropertyInitializer.Builder>();
+                    return builder.InstanceInitializersForRecordDeclarationWithParameters;
+                }
+                else
+                {
+                    // PROTOTYPE: Add error for multiple parameter lists
```
[the remark this answers is not in the document]
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs:2521]: > nit: it would be nice to reference the tracking issue for this instead of using PROTOTYPE. [https://github.com/dotnet/roslyn/issues/44676](https://github.com/dotnet/roslyn/issues/44676)

The code was moved from other place in the same file. I didn't add the comment.

---
In reply to: [434735063](https://github.com/dotnet/roslyn/pull/44803#discussion_r434735063) [](ancestors = 434735063)

**Comment by RikkiGibson** [comment]
It looks like CI did not re-run between when #44705 was merged and when this was merged. Thus some tests in features/records branch have broken.
