### PR TITLE
Disable 'Use 'throw' exception' refactoring for generic type parameter without constraint

### LINKED ISSUE #22926: IDE0016 provides invalid codefix on generic type without constraint
**Version Used**: 
Visual Studio 15.4.1

**Steps to Reproduce**:
```csharp
class A<T>
{
    T x;
    public A(T t)
    {
        if (t == null) throw new ArgumentNullException();
        x = t;
    }
}
```

**Expected Behavior**:
T is not constrained, so `??` cannot be applied on it.

**Actual Behavior**:
Code fix to
```csharp
x = t ?? throw new ArgumentNullException();
```

How about allowing `??` on unconstrained generic type? For value type, just ignore it, as it implies `== null`.

### PR DESCRIPTION
**Pull request by zaytsev-victor**
**Customer scenario**

IDE0016 provides invalid codefix on generic type without constraint

**Bugs this fixes:**

Fixes #22926

**Risk**

Low

**Performance impact**

Low

**Is this a regression from a previous update?**

**Root cause analysis:**

Missed check for parameter type.

**How was the bug found?**

customer reported

### CODE REVIEW

File: src/Features/Core/Portable/UseThrowExpression/AbstractUseThrowExpressionDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -281,6 +287,22 @@ private static bool ValueIsAccessed(SemanticModel semanticModel, IConditionalOpe
...
+            {
+                type = local.Type; 
+            }
+
+            if (symbol is IParameterSymbol parameter)
+            {
+                type = parameter.Type;
+            }
+
+            return type != null && (type.IsReferenceType || type.IsNullable());
```
Comment (sharwell) [inline src/Features/Core/Portable/UseThrowExpression/AbstractUseThrowExpressionDiagnosticAnalyzer.cs]: :bulb: `type.CanAddNullCheck()`

https://github.com/dotnet/roslyn/blob/289aebf09380e809ed9481229e98de324d70c835/src/Workspaces/Core/Portable/Shared/Extensions/ITypeSymbolExtensions.cs#L22-L23

File: src/Features/Core/Portable/UseThrowExpression/AbstractUseThrowExpressionDiagnosticAnalyzer.cs [hunk 2]
```diff
@@ -281,6 +287,22 @@ private static bool ValueIsAccessed(SemanticModel semanticModel, IConditionalOpe
             return false;
         }
 
+        private bool IsReferenceOrNullableType(ISymbol symbol)
+        {
+            ITypeSymbol type = null;
```
Comment (sharwell) [inline src/Features/Core/Portable/UseThrowExpression/AbstractUseThrowExpressionDiagnosticAnalyzer.cs]: :bulb: `var type = symbol.GetSymbolType();`

https://github.com/dotnet/roslyn/blob/289aebf09380e809ed9481229e98de324d70c835/src/Workspaces/Core/Portable/Shared/Extensions/ISymbolExtensions.cs#L879-L884

**Comment by zaytsev-victor** [comment]
@sharwell thanks for suggestion (:
Is that expected that this refactoring is not shown in this case (object initialize):
```csharp
class A<T> where T: class
{
    public A(T t)
    {
        if (t == null) throw new ArgumentNullException();
        var x = t;
    }
}
```

Or I should file a bug?

**Comment by sharwell** [comment]
@zaytsev-victor File a bug 👍

**Comment by sharwell** [comment]
@mavasani just waiting on your requested review :smile:

File: src/EditorFeatures/CSharpTest/UseThrowExpression/UseThrowExpressionTests.cs [hunk 3]
```diff
@@ -454,5 +454,74 @@ public B(A a)
...
+        public async Task TestNotWhenUnconstrainedTypeParameter()
+        {
+            await TestMissingInRegularAndScriptAsync(
+@"using System;
+class A<T>
+{
+    T x;
+    public A(T t)
+    {
+        if (t == null) [|throw|] new ArgumentNullException();
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/UseThrowExpression/UseThrowExpressionTests.cs]: It seems so wacky that you can write this, but not ```t ?? throw ...```.  It feels like a csharplang bug/suggestion should be filed on this.

Comment (zaytsev-victor) [reply src/EditorFeatures/CSharpTest/UseThrowExpression/UseThrowExpressionTests.cs]: @CyrusNajmabadi I agree with you. Proposal to fix it https://github.com/dotnet/csharplang/issues/263
