### PR TITLE
[AskMode] Avoid DataTip crash in .cshtml...

### LINKED ISSUE #6430: Crash (InvalidOperationException) when hovering/clicking in .cshtml files...
capture

- Create an ASP Web App.
- Modify an existing .cshtml file to include the code above.
- Hover/click in the indicated location.

### PR DESCRIPTION
**Pull request by KevinH-MS**
There are cases were a DataBuffer span may map to two zero-length spans in the _subjectBuffer.  In these cases, rather than throwing an Exception, we can simply try returning a DataTip from each one.

Fixes #6430

### CODE REVIEW

**Comment by KevinH-MS** [comment]
FYI @dotnet/roslyn-ide @dotnet/interactive

**Comment by Pilchie** [comment]
:+1:

**Comment by KevinH-MS** [comment]
Any other reviewers?

File: src/VisualStudio/Core/Def/Implementation/Venus/VenusCommandFilter.cs [hunk 1]
```diff
@@ -61,49 +61,52 @@ public override int GetDataTipText(TextSpan[] pSpan, out string pbstrText)
...
+                // First, we'll only consider spans whose length matches our input span. 
+                if (candidateSpan.Length != expectedSpanLength)
+                {
+                    continue;
+                }
 
-            pSpan[0] = subjectSpan.ToVsTextSpan();
+                // Next, we'll check to see if there is actually a DataTip for this candidate.
+                // If there is, we'll map this span back to the DataBuffer and return it.
+                pSpan[0] = candidateSpan.ToVsTextSpan();
```
Comment (cston) [inline src/VisualStudio/Core/Def/Implementation/Venus/VenusCommandFilter.cs]: Why assign to ```pSpan[0]``` here rather than a local? Do we ever want to return this subject buffer span?

File: src/VisualStudio/Core/Def/Implementation/Venus/VenusCommandFilter.cs [hunk 2]
```diff
@@ -61,49 +61,52 @@ public override int GetDataTipText(TextSpan[] pSpan, out string pbstrText)
...
+            var expectedSpanLength = span.Length;
+            foreach (var candidateSpan in subjectSpans)
             {
-                pbstrText = null;
-                return VSConstants.E_FAIL;
-            }
+                // First, we'll only consider spans whose length matches our input span. 
+                if (candidateSpan.Length != expectedSpanLength)
+                {
+                    continue;
```
Comment (cston) [inline src/VisualStudio/Core/Def/Implementation/Venus/VenusCommandFilter.cs]: When do we hit this case?

File: src/VisualStudio/Core/Def/Implementation/Venus/VenusCommandFilter.cs (hunk 1 above)
Comment (KevinH-MS) [inline src/VisualStudio/Core/Def/Implementation/Venus/VenusCommandFilter.cs]: It's subtle and perhaps deserves a comment, but ```base.GetDataTipText``` may modify the value (it's in/out), and we should return that modified value to our caller (at least that's what the code was doing before).

File: src/VisualStudio/Core/Def/Implementation/Venus/VenusCommandFilter.cs (hunk 2 above)
Comment (KevinH-MS) [inline src/VisualStudio/Core/Def/Implementation/Venus/VenusCommandFilter.cs]: If ```MapDownToBuffer``` maps to two spans in the subject buffer and one is zero-length (and the other is not).

File: src/VisualStudio/Core/Def/Implementation/Venus/VenusCommandFilter.cs (hunk 1 above)
Comment (cston) [inline src/VisualStudio/Core/Def/Implementation/Venus/VenusCommandFilter.cs]: It looks like we're modifying the value even in the case where this method returns ```E_FAIL``` though. If that was the previous behavior, ok.

**Comment by cston** [comment]
LGTM

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by KevinH-MS** [comment]
optimistically merging (will revert if not actually approved, but per offline, I believe it will be)

**Comment by MattGertz** [comment]
Approved pending successful testing.
