### PR TITLE
Fix regression for switching on a constant value

### LINKED ISSUE #35011: switch case without default no longer compiles in visual studio 2019 [c#]
VSF_TYPE_MARKDOWNThe following code compiles fine in Visual Studio 2017, but not in Visual Studio 2019. Is there a default compiler option that has changed which can resolve this?

    using System;
    
    namespace NoDefaultCase
    {
        public static class Program
        {
            public const string Database = &quot;MongoDB&quot;;
    
            public static string GetDb()
            {
                switch (Database)
                {
                    case &quot;MongoDB&quot;:
                        return Database;
                }
            }
    
            public static void Main(string[] args)
            {
                Console.WriteLine($&quot;The value returned is \&quot;{GetDb()}\&quot;.&quot;);
                Console.WriteLine(&quot;Press a key to exit&quot;);
                Console.ReadKey();
            }
        }
    }

There is also a Stack Overflow ticket for this item:
https://stackoverflow.com/questions/55541269/why-does-a-switch-case-statement-on-a-string-constant-require-a-default-in-visua

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/520522/switch-case-without-default-no-longer-compiles-in.html
VSTS ticketId: 841662_
_These are the original issue comments:_

Martin Eyles on 4/6/2019, 05:37 AM (10 days ago): <p>In Visual Studio 2017, the output of the build is:<br><br>    1&gt;------ Rebuild All started: Project: NoDefaultCase, Configuration: Debug Any CPU ------<br>    1&gt;  NoDefaultCase -&gt; C:\Users\MartinEyles\source\repos\NoDefaultCase\NoDefaultCase\bin\Debug\NoDefaultCase.exe<br>    ========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========<br><br>In Visual Studio 2019, the output of the build is:<br><br>    1&gt;------ Rebuild All started: Project: NoDefaultCase, Configuration: Debug Any CPU ------<br>    1&gt;C:\Users\MartinEyles\source\repos\NoDefaultCase\NoDefaultCase\Program.cs(9,30,9,35): error CS0161: 'Program.GetDb()': not all code paths return a value<br>    ========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========</p>

Visual Studio Feedback System on 4/8/2019, 02:55 AM (8 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Martin Eyles on 4/8/2019, 03:07 AM (8 days ago): <p>A github repository containing the example solution can be found at <a target='_blank' href="https://github.com/martineyles/NoDefaultCase">https://github.com/martineyles/NoDefaultCase</a> This includes an archive of the example solution in the state before it was added to github (NoDefaultCase - Before Github.zip).</p>

Martin Eyles on 4/8/2019, 05:59 AM (8 days ago): <p>I experience this issue in </p><p>Microsoft Visual Studio Enterprise 2019 <br>Version 16.0.0<br>VisualStudio.16.Release/16.0.0+28729.10<br>Microsoft .NET Framework Version 4.7.03056'</p><p>It has been suggested by others in the Stack Overflow community that a preview version of Visual Studio 2019 behaves the same way as Visual Studio 2017</p>

Martin Eyles on 4/12/2019, 05:24 AM (4 days ago): <p>The issue is still present in:<br><br>Microsoft Visual Studio Enterprise 2019<br>Version 16.0.1<br>VisualStudio.16.Release/16.0.1+28803.156<br>Microsoft .NET Framework Version 4.7.03056</p>

Martin Eyles on 4/12/2019, 05:26 AM (4 days ago): <p>Stack overflow users has suggested that this does not meet the C#  specification, and is likely to be either a bug or a change in the  specification that hasn't yet been documented.</p>

Martin Eyles on 4/12/2019, 05:29 AM (4 days ago): <p>To quote a user with very good reputation on stack overflow:</p><p>The <a target='_blank' href="https://www.ecma-international.org/publications/standards/Ecma-334.htm">ECMA C# 5 standard</a> section 13.8.3 describes the reachability of the end of a switch statement:</p><p>  
</p><blockquote>   
<p>The end point of a switch statement is reachable if at least one of the following is true:</p><p>      
</p><ul><li>The switch statement contains a reachable break statement that exits the switch statement.</li><li>The switch statement is reachable, the switch expression is a non-constant value, and no default label is present.</li><li>The switch statement is reachable, the switch expression is a  constant value that doesn’t match any case label, and no default label  is present.</li></ul></blockquote><p>  
</p><p>None of these seem to be the case in your example:</p><p>  
</p><ul><li>There are no break statements</li><li>The switch expression is a constant value</li><li>The constant value <em>does</em> match a case label</li></ul><p>  
</p><p>So with C# 5 rules, the end point of this switch statement is <em>not</em> reachable, and it should compile with no problems. The <a target='_blank' href="https://github.com/dotnet/csharplang/blob/master/spec/statements.md">draft specification in GitHub</a> has the same text, so it doesn't look like it's changed there yet...</p>

_These are the original issue solutions:_
(no solutions)

### PR DESCRIPTION
**Pull request by agocke**
We made a change in #32818 to restore compatibility with C# 7.x
in rejecting certain switch statements even when we could prove
completeness with the new switch analysis. It looks like that
change just went a little too far, as we could do the analysis
if the argument to the switch expression was a constant. This
change removes the compat clause for switches with constant
values

Fixes #35011

### CODE REVIEW

**Comment by agocke** [comment]
@dotnet/roslyn-compiler @gafter For review.

The test failure is because of some out-of-date infrastructure in the dev16.0 branch. I'm working on getting it fixed in https://github.com/dotnet/roslyn/pull/35061

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass_Switch.cs [hunk 1]
```diff
@@ -63,7 +63,8 @@ private void VisitSwitchBlock(BoundSwitchStatement node)
                 Join(ref afterSwitchState, ref this.State);
             }
 
-            if (reachableLabels.Contains(node.BreakLabel) || node.DefaultLabel == null && IsTraditionalSwitch(node))
+            if (node.DecisionDag.ReachableLabels.Contains(node.BreakLabel) ||
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass_Switch.cs]: >node.DecisionDag.ReachableLabels [](start = 16, length = 32)

Why can't we use the local here?

Comment (agocke) [reply src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass_Switch.cs]: We can, that was a mistake made when back porting this code from master, where that local is not defined.

File: src/Compilers/CSharp/Test/Semantic/FlowAnalysis/FlowTests.cs [hunk 2]
```diff
@@ -89,6 +89,90 @@ public class C {
...
+                return S;
+        }
+        // error
+    }
+}";
+
+            var comp = CreateCompilation(src);
+            comp.VerifyDiagnostics(
+                // (40,17): warning CS0162: Unreachable code detected
+                //                 return S;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/FlowAnalysis/FlowTests.cs]: >return S; [](start = 35, length = 9)

It is hard to tell which line this corresponds to. Consider marking the lines with a comment, or use distinct expressions (here and below).
