### PR TITLE
Convert to struct has errors on uninitiated members

### LINKED ISSUE #33407: Convert to struct has errors on uninitiated members
**Version Used**: Visual studio 2019

**Steps to Reproduce**:

1. Have code

```csharp
public class Class
{
    void MyMethod()
    {
        var tuple = (3, "string");
    }

```
2. Place cursor before open parenthesis and type (Ctrl+.) to open codefixes
image

3. Select Convert to struct

**Expected Behavior**:
Generated struct gives no errors.

**Actual Behavior**:
Generated struct gives errors on uninitialized members Item1 and Item2.
image

Adding these declarations fixes warnings:
```
internal struct NewStruct
{
    public int Item1 { get; }
    public string Item2 { get; }
...
```

@CyrusNajmabadi Julien mentioned you might want to take a look. :)

### PR DESCRIPTION
**Pull request by ivanbasov**
### Customer scenario
1. Have code

```cs
public class Class
{
    void MyMethod()
    {
        var tuple = (3, "string");
    }
```

2. Place cursor before open parenthesis and type (Ctrl+.) to open codefixes
3. Choose "convert to struct" and run the refactoring.

**Expected**
The code generated is valid.

**Actual**
The code generated is invalid: it misses definitions for fields corresponding to non-named in the tuple such as Item1, Item2 and so on.

### Bugs this fixes
#33407

### Workarounds, if any
Manually add code for those fields.

### Risk
Low

### Performance impact
None

### Is this a regression from a previous update?
This is a new feature just added. It was added with this defect.

### Root cause analysis
Test cases actually covered the situation but code provided in those tests cases contained errors. We may need to consider adding a validation of code generated in test scenarios.

### How was the bug found?
Internal customers

### CODE REVIEW

File: src/Workspaces/Core/Portable/CodeGeneration/AbstractCodeGenerationService.cs [hunk 1]
```diff
@@ -228,8 +228,8 @@ public async Task<Document> AddImportsAsync(Document document, CodeGenerationOpt
             }
 
             // Filter out the members that are implicitly declared.  They're implicit, hence we do
-            // not want an explicit declaration.
-            var filteredMembers = membersList.Where(m => !m.IsImplicitlyDeclared);
+            // not want an explicit declaration. The only exception are fields generated from implicit tuple fields.
+            var filteredMembers = membersList.Where(m => !m.IsImplicitlyDeclared || m.IsTupleField());
```
Comment (ivanbasov) [inline src/Workspaces/Core/Portable/CodeGeneration/AbstractCodeGenerationService.cs]: >|| m.IsTupleField() [](start = 81, length = 19)

I'm not sure this is the best fix. I would prefer to re-create fields from tuple fields during the refactoring and change IsImplicitlyDeclared to true in fields. However, I could not find an infrastructure for doing this. Please point me if you see a better solution.

**Comment by mavasani** [comment]
@ivanbasov We should possibly mark the underlying issue as Needs Design Review?

**Comment by jinujoseph** [comment]
@ivanbasov make sure to retarget to 16.0 before merge

**Comment by MohammadHamdyGhanem** [comment]
@ivanbasov @CyrusNajmabadi
There is still and issue; If you convert this tuple:
`var tuple = (Id: 3, Type: "string");`
To a structure, it becomes:
`var tuple = new NewStruct(Id: 3, Type: "string");`
Which contains two bugs, because the casing of the named arguments should be lowerd.
The easy solution is to remove the named arguments, since it is not needed after converting to a struct.

**Comment by MohammadHamdyGhanem** [comment]
By the way: I didn't know b4 about `Ctrl+.`, so I never fiund the command to convert to struct before today!
I think it will be helpful if you add a `code fixes` sub menu to the context menu, or add a suggestion link to the tooltip of the item even when there is no bug, but possible enhancements.

**Comment by CyrusNajmabadi** [comment]
>By the way: I didn't know b4 about `Ctrl+.`, so I never fiund the command to convert to struct before today!

If you've never used lightbulbs, the the menu shows up autoamtically for users to alert them to its presence.  That lightbulb also shows that you can hit `ctrl-.` to invoke it.

If you hover over hte lightbulb, it will also show:

image

> I think it will be helpful if you add a `code fixes` sub menu to the context menu,

We don't do this because hte context menu is already massively overloaded and a ton of time has been taken to remove extraneous entries that can be reached from other places.

**Comment by CyrusNajmabadi** [comment]
@MohammadHamdyGhanem 

>There is still and issue; If you convert this tuple:
`var tuple = (Id: 3, Type: "string");`
To a structure, it becomes:
`var tuple = new NewStruct(Id: 3, Type: "string");`
Which contains two bugs, because the casing of the named arguments should be lowerd.
The easy solution is to remove the named arguments, since it is not needed after converting to a struct.

Would you be interested in contributing a fix here?

**Comment by MohammadHamdyGhanem** [comment]
>ton of time has been taken to remove extraneous entries that can be reached from other places

About that: you can combine the commands: `Go to Definition`, `Peak to definition` and `Go to Implementation` as sub-Items of one menu called `Definition` or any other suitable name. 

>Would you be interested in contributing a fix here?
Sorry, not there yet!

**Comment by CyrusNajmabadi** [comment]
>About that: you can combine the commands: `Go to Definition`, `Peak to definition` and `Go to Implementation` as sub-Items of one menu called `Definition` or any other suitable name.

@MohammadHamdyGhanem If you have suggestions, please file new issues.  It's spammy to just add random thoughts like this to unrelated (and closed) PRs.
