### PR TITLE
Change Signature - Add Parameter - Optional parameters & Fixes

### LINKED ISSUE #41043: Add Parameter Unit Testing - View Model interactions

### LINKED ISSUE #41045: Add Parameter - Implement Optional Parameters
Very early thinking/prototyping is something like this:

image

### LINKED ISSUE #41047: Add Parameter - Polish Completion experiences or make binding indicator
- [ ] Invoking completion in an empty textbox shows only keywords
- [x] Filling out Parameter Name before Type Name causes types to appear there

### LINKED ISSUE #41782: Add Parameter - Better indicator that the type didn't bind.

### LINKED ISSUE #42736: Cross-language add parameter tests
https://github.com/dotnet/roslyn/pull/38748#pullrequestreview-369939314

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #41045
Fixes #41047 
Fixes #42736
Fixes #41782
Fixes #41043

Adds support for optional parameters and addresses many review comments from previous PRs. It does **not** include the completion list in the Type/Name textboxes (that is covered by #42903)

**Updated Add Parameter Dialog**:

AddParameterBindingIndicator3

**Updated Change Signature Dialog**:

image

### CODE REVIEW

**Comment by dpoeschl** [comment]
Tagging for review: @CyrusNajmabadi @jasonmalinowski @dotnet/roslyn-ide

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs [hunk 1]
```diff
@@ -338,88 +334,100 @@ private SyntaxNode GetNodeContainingTargetNode(SyntaxNode matchingNode)
...
             {
-                var newArguments = PermuteAttributeArgumentList(declarationSymbol, attribute.ArgumentList.Arguments, signaturePermutation);
+                var semanticModel = await document.GetSemanticModelAsync(cancellationToken).ConfigureAwait(false);
+                var symbolInfo = semanticModel.GetSymbolInfo((AttributeSyntax)originalNode, cancellationToken);
+
+                var isParamsArrayExpanded = IsParamsArrayExpanded(semanticModel, attribute, symbolInfo, cancellationToken);
+
+                var newArguments = PermuteAttributeArgumentList(declarationSymbol, attribute.ArgumentList.Arguments, signaturePermutation.WithoutAddedParameters());
+                newArguments = AddNewArgumentsToList(declarationSymbol, newArguments, attribute.ArgumentList.Arguments, signaturePermutation, isReducedExtensionMethod: false, isParamsArrayExpanded, generateAttributeArguments: true);
                 return attribute.WithArgumentList(attribute.ArgumentList.WithArguments(newArguments).WithAdditionalAnnotations(changeSignatureFormattingAnnotation));
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:431]: the amount of duplication here bums me out enormously :)

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs [hunk 2]
```diff
@@ -442,31 +450,100 @@ private SyntaxNode GetNodeContainingTargetNode(SyntaxNode matchingNode)
...
+
+            int argumentCount;
+            bool lastArgumentHasNameColon;
+            ExpressionSyntax lastArgumentExpression;
+
+            if (node is AttributeSyntax attribute)
+            {
+                argumentCount = attribute.ArgumentList.Arguments.Count;
+                lastArgumentHasNameColon = attribute.ArgumentList.Arguments.LastOrDefault()?.NameColon != null ||
+                    attribute.ArgumentList.Arguments.LastOrDefault()?.NameEquals != null;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:468]: variable name doesn't seem to match initialization logic.  i.e. it says "lastArgHasNameColon" but you check for name-colon and name-equals.  needs comment.

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs [hunk 3]
```diff
@@ -442,31 +450,100 @@ private SyntaxNode GetNodeContainingTargetNode(SyntaxNode matchingNode)
...
+                lastArgumentExpression = attribute.ArgumentList.Arguments.LastOrDefault()?.Expression;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:469]: would be good to NRT these files.

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs [hunk 4]
```diff
@@ -442,31 +450,100 @@ private SyntaxNode GetNodeContainingTargetNode(SyntaxNode matchingNode)
...
+            }
+            else
+            {
+                BaseArgumentListSyntax argumentList = node switch
+                {
+                    InvocationExpressionSyntax invocation => invocation.ArgumentList,
+                    ObjectCreationExpressionSyntax objectCreation => objectCreation.ArgumentList,
+                    ConstructorInitializerSyntax constructorInitializer => constructorInitializer.ArgumentList,
+                    ElementAccessExpressionSyntax elementAccess => elementAccess.ArgumentList,
+                    _ => throw new ArgumentException("Unexpected SyntaxNode", nameof(node))
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:479]: `throw ExcetionUtilities.UnexpectedValue(node.Kind())`

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs [hunk 5]
```diff
@@ -442,31 +450,100 @@ private SyntaxNode GetNodeContainingTargetNode(SyntaxNode matchingNode)
...
+                };
+
+                argumentCount = argumentList.Arguments.Count;
+                lastArgumentHasNameColon = argumentList.Arguments.LastOrDefault()?.NameColon != null;
+                lastArgumentExpression = argumentList.Arguments.LastOrDefault()?.Expression;
+            }
+
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:486]:
```suggestion
```

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs [hunk 6]
```diff
@@ -442,31 +450,100 @@ private SyntaxNode GetNodeContainingTargetNode(SyntaxNode matchingNode)
...
+
+            if (symbolInfo.Symbol is IMethodSymbol methodSymbol && methodSymbol.Parameters.LastOrDefault()?.IsParams == true)
+            {
+                if (argumentCount > ((IMethodSymbol)symbolInfo.Symbol).Parameters.Length)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:490]:
```suggestion
                if (argumentCount > methodSymbol.Parameters.Length)
```

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs [hunk 7]
```diff
@@ -442,31 +450,100 @@ private SyntaxNode GetNodeContainingTargetNode(SyntaxNode matchingNode)
...
+                {
+                    return true;
+                }
+                else if (argumentCount == ((IMethodSymbol)symbolInfo.Symbol).Parameters.Length)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:494]:
```suggestion

                if (argumentCount == methodSymbol.Parameters.Length)
```

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs [hunk 8]
```diff
@@ -442,31 +450,100 @@ private SyntaxNode GetNodeContainingTargetNode(SyntaxNode matchingNode)
...
+                {
+                    if (lastArgumentHasNameColon)
+                    {
+                        return true;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:498]: can you comment (or give example) to explain why this is true?  i'm not really getting it.

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs [hunk 9]
```diff
@@ -442,31 +450,100 @@ private SyntaxNode GetNodeContainingTargetNode(SyntaxNode matchingNode)
...
+                    }
+                    else
+                    {
+                        var fromType = semanticModel.GetTypeInfo(lastArgumentExpression, cancellationToken);
+                        var toType = ((IMethodSymbol)symbolInfo.Symbol).Parameters.Last().Type;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:503]:
```suggestion
                        var toType = methodSymbol.Parameters.Last().Type;
```

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs [hunk 10]
```diff
@@ -442,31 +450,100 @@ private SyntaxNode GetNodeContainingTargetNode(SyntaxNode matchingNode)
...
+                        return !semanticModel.Compilation.HasImplicitConversion(fromType.Type, toType);
+                    }
+                }
+                else
+                {
+                    return false;
+                }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:510]:
```suggestion
```

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs [hunk 11]
```diff
@@ -442,31 +450,100 @@ private SyntaxNode GetNodeContainingTargetNode(SyntaxNode matchingNode)
...
+                attributeLists: default,
+                modifiers: default,
                 type: skipParameterType
                     ? null
-                    : addedParameter.Type.GenerateTypeSyntax(allowVar: false)
-                        .WithTrailingTrivia(SyntaxFactory.ElasticSpace),
-                SyntaxFactory.Identifier(addedParameter.ParameterName),
-                @default: null);
+                    : addedParameter.Type.GenerateTypeSyntax()
+                        .WithTrailingTrivia(ElasticSpace),
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:531]: adding the trailing space seems like it should be unnecessary.

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs [hunk 12]
```diff
@@ -510,47 +605,41 @@ protected override T TransferLeadingWhitespaceTrivia<T>(T newArgument, SyntaxNod
...
+            return result.ToImmutable();
         }
 
-        private List<SyntaxTrivia> UpdateParamTagsInLeadingTrivia(Document document, CSharpSyntaxNode node, ISymbol declarationSymbol, SignatureChange updatedSignature)
+        private ImmutableArray<SyntaxTrivia> UpdateParamTagsInLeadingTrivia(Document document, CSharpSyntaxNode node, ISymbol declarationSymbol, SignatureChange updatedSignature)
         {
             if (!node.HasLeadingTrivia)
             {
-                return null;
+                return default;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:642]: why default here, but ImmutableArray.Empty below?

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs [hunk 13]
```diff
@@ -665,6 +755,27 @@ private List<SyntaxNode> VerifyAndPermuteParamNodes(IEnumerable<XmlElementSyntax
         }
 
         protected override IEnumerable<AbstractFormattingRule> GetFormattingRules(Document document)
-            => SpecializedCollections.SingletonEnumerable(new ChangeSignatureFormattingRule()).Concat(Formatter.GetDefaultFormattingRules(document));
+            => Formatter.GetDefaultFormattingRules(document).Concat(new ChangeSignatureFormattingRule());
+
+        protected override SyntaxNode AddNameToArgument(SyntaxNode newArgument, string name)
+        {
+            return (newArgument as ArgumentSyntax).WithNameColon(NameColon(name));
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:762]:
```suggestion
            return ((ArgumentSyntax)newArgument).WithNameColon(NameColon(name));
```

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:762]: it woudl also be desirable to use generics here to make this strongly typed so we don't even need this.

Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:762]: how does this work with attribute arguments?  won't this crash with an null-ref exception?

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs [hunk 14]
```diff
@@ -665,6 +755,27 @@ private List<SyntaxNode> VerifyAndPermuteParamNodes(IEnumerable<XmlElementSyntax
...
+        }
+
+        protected override SyntaxNode CreateExplicitParamsArrayFromIndividualArguments(SeparatedSyntaxList<SyntaxNode> newArguments, int indexInExistingList, IParameterSymbol parameterSymbol)
+        {
+            var listOfArguments = SeparatedList(newArguments.Skip(indexInExistingList).Select(a => ((ArgumentSyntax)a).Expression), newArguments.GetSeparators().Skip(indexInExistingList));
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:767]: 1. by stripping off the Expression of an argument, aren't we droping things like `ref/out`?
2. it would be nice to be strongly typed here.

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs [hunk 15]
```diff
@@ -665,6 +755,27 @@ private List<SyntaxNode> VerifyAndPermuteParamNodes(IEnumerable<XmlElementSyntax
...
+            var initializerExpression = InitializerExpression(SyntaxKind.ArrayInitializerExpression, listOfArguments);
+            var objectCreation = ArrayCreationExpression((ArrayTypeSyntax)parameterSymbol.Type.GenerateTypeSyntax(), initializerExpression);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:769]: i don't know if this ArrayTypeSyntax cast is safe in error scenarios.  it may crash.

File: src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs [hunk 16]
```diff
@@ -147,35 +171,32 @@ internal ChangeSignatureResult ChangeSignature(Document document, int position,
...
-                return new CannotChangeSignatureAnalyzedContext(CannotChangeSignatureReason.DeclarationMethodPositionNotFound);
+                insertPosition = declarationChangeSignatureService.GetPositionBeforeParameterListClosingBrace(reference.GetSyntax());
             }
-
-            if (!symbol.MatchesKind(SymbolKind.Method, SymbolKind.Property, SymbolKind.NamedType))
+            else
             {
-                return new CannotChangeSignatureAnalyzedContext(CannotChangeSignatureReason.IncorrectKind);
+                // We may have some indirection, like an event declaration backed by an invisible delegate invoke method.
+                // In the worst case, still continue on.
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs:187]: not sure what is meant by 'some indirection'.

File: src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs [hunk 17]
```diff
@@ -537,53 +549,52 @@ private bool TryGetNodeWithEditableSignatureOrAttributes(Location location, Solu
...
             {
                 var originalConfigurationParameters = updatedSignature.OriginalConfiguration.ToListOfParameters();
                 var updatedConfigurationParameters = updatedSignature.UpdatedConfiguration.ToListOfParameters();
 
                 var realParameters = declarationSymbol.GetParameters();
+                var bonusParameters = realParameters.Skip(originalConfigurationParameters.Length);
 
-                var bonusParameters = realParameters.Skip(originalConfigurationParameters.Count);
+                var compensatedOriginalConfigurationParameters = originalConfigurationParameters.AddRange(bonusParameters.Select(p => new ExistingParameter(p)));
+                var compensatedUpdatedConfigurationParameters = updatedConfigurationParameters.AddRange(bonusParameters.Select(p => new ExistingParameter(p)));
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs:581]: what does 'compensated' mean?

File: src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs [hunk 18]
```diff
@@ -665,151 +676,227 @@ protected static int GetParameterIndex<TNode>(SeparatedSyntaxList<TNode> paramet
...
+                    ? arguments.GetSeparator(i)
+                    : CommaTokenWithElasticSpace());
             }
 
-            return separators;
+            return separators.ToImmutable();
         }
 
         protected abstract SyntaxGenerator Generator { get; }
+        protected abstract ISyntaxFacts SyntaxFacts { get; }
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs:750]: nit: place abstracts above concrete members.

File: src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs [hunk 19]
```diff
@@ -665,151 +676,227 @@ protected static int GetParameterIndex<TNode>(SeparatedSyntaxList<TNode> paramet
...
-          SeparatedSyntaxList<SyntaxNode> newArguments,
-          SignatureChange signaturePermutation,
-          bool isReducedExtensionMethod)
+        protected virtual SeparatedSyntaxList<SyntaxNode> AddNewArgumentsToList(
+            ISymbol declarationSymbol,
+            SeparatedSyntaxList<SyntaxNode> newArguments,
+            SignatureChange signaturePermutation,
+            bool isReducedExtensionMethod,
+            bool isParamsArrayExpanded,
+            bool generateAttributeArguments = false)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs:758]: nit: make this non-optional.  i want callers to ahve to think about what to pass here.

File: src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs [hunk 20]
```diff
@@ -665,151 +676,227 @@ protected static int GetParameterIndex<TNode>(SeparatedSyntaxList<TNode> paramet
...
+                            var newArgument = newArguments[indexInListOfPreexistingArguments];
+
+                            if (seenNamedArguments && !SyntaxFacts.IsNamedParameter(newArgument))
+                            {
+                                newArgument = AddNameToArgument(newArgument, parameters[indexInListOfPreexistingArguments].Name);
+                            }
+
+                            fullList.Add(newArgument);
+                            indexInListOfPreexistingArguments++;
                         }
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs:860]: i skipped most of this.  it's complex and confusing :(

File: src/Features/Core/Portable/ChangeSignature/Parameter.cs [hunk 21]
```diff
@@ -21,28 +25,63 @@ public ExistingParameter(IParameterSymbol param)
...
+        public string TypeName { get; }
+        public bool TypeBinds { get; }
+        public string CallSiteValue { get; }
 
-        public string TypeNameDisplayWithErrorIndicator { get; set; }
+        public bool IsRequired { get; }
+        public string DefaultValue { get; }
+        public bool UseNamedArguments { get; }
+        public bool IsCallsiteOmitted { get; }
+        public bool IsCallsiteError { get; }
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ChangeSignature/Parameter.cs:84]: doc these.

File: src/Features/Core/Portable/ChangeSignature/ParameterConfiguration.cs [hunk 22]
```diff
@@ -32,49 +32,48 @@ internal sealed class ParameterConfiguration
             SelectedIndex = selectedIndex;
         }
 
-        public static ParameterConfiguration Create(IEnumerable<Parameter?> parameters, bool isExtensionMethod, int selectedIndex)
+        public static ParameterConfiguration Create(ImmutableArray<Parameter> parameters, bool isExtensionMethod, int selectedIndex)
         {
-            var parametersList = parameters.ToList();
+            var parametersList = parameters.ToList()!;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ChangeSignature/ParameterConfiguration.cs:37]: `!`?

File: src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb [hunk 23]
```diff
@@ -353,7 +360,13 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.ChangeSignature
...
             If vbnode.IsKind(SyntaxKind.Attribute) Then
                 Dim attribute = DirectCast(vbnode, AttributeSyntax)
-                Dim newArguments = PermuteArgumentList(attribute.ArgumentList.Arguments, updatedSignature, declarationSymbol)
+
+                Dim semanticModel = Await document.GetSemanticModelAsync(cancellationToken).ConfigureAwait(False)
+                Dim symbolInfo = semanticModel.GetSymbolInfo(DirectCast(originalNode, AttributeSyntax))
+                Dim methodSymbol = TryCast(symbolInfo.Symbol, IMethodSymbol)
+
+                Dim newArguments = PermuteArgumentList(attribute.ArgumentList.Arguments, updatedSignature.WithoutAddedParameters(), declarationSymbol)
+                newArguments = AddNewArgumentsToList(methodSymbol, newArguments, updatedSignature, isReducedExtensionMethod:=False, isParamsArrayExpanded:=False, generateAttributeArguments:=True)
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb:369]: i feel like i say this same logic repeated multiple times here and in C#.

File: src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb [hunk 24]
```diff
@@ -429,124 +444,169 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.ChangeSignature
...
+            If invocation IsNot Nothing Then
+                argumentCount = invocation.ArgumentList.Arguments.Count
+                Dim isNamed = invocation.ArgumentList.Arguments.LastOrDefault()?.IsNamed
+                lastArgumentIsNamed = isNamed.HasValue AndAlso isNamed.Value
+                lastArgumentExpression = invocation.ArgumentList.Arguments.LastOrDefault()?.GetExpression()
+            ElseIf objectCreation IsNot Nothing Then
+                argumentCount = objectCreation.ArgumentList.Arguments.Count
+                Dim isNamed = objectCreation.ArgumentList.Arguments.LastOrDefault()?.IsNamed
+                lastArgumentIsNamed = isNamed.HasValue AndAlso isNamed.Value
+                lastArgumentExpression = objectCreation.ArgumentList.Arguments.LastOrDefault()?.GetExpression()
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb:467]: this logic looks identical to the logic above.

File: src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb [hunk 25]
```diff
@@ -429,124 +444,169 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.ChangeSignature
...
+            Else
+                Throw New ArgumentException("Unexpected SyntaxNode", NameOf(node))
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb:469]: ExceptionUtilities.UnexpectedValue

File: src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb [hunk 26]
```diff
@@ -429,124 +444,169 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.ChangeSignature
...
+            End If
+
+            Dim methodSymbol = TryCast(symbolInfo.Symbol, IMethodSymbol)
+            If methodSymbol IsNot Nothing AndAlso methodSymbol.Parameters.LastOrDefault()?.IsParams Then
+                If argumentCount > DirectCast(symbolInfo.Symbol, IMethodSymbol).Parameters.Length Then
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb:474]:
```suggestion
                If argumentCount > methodSymbol .Parameters.Length Then
```

File: src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb [hunk 27]
```diff
@@ -429,124 +444,169 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.ChangeSignature
...
+                    Return True
+                ElseIf argumentCount = DirectCast(symbolInfo.Symbol, IMethodSymbol).Parameters.Length Then
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb:476]:
```suggestion
                ElseIf argumentCount = methodSymbol.Parameters.Length Then
```

File: src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb [hunk 28]
```diff
@@ -429,124 +444,169 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.ChangeSignature
...
+                    If lastArgumentIsNamed Then
+                        Return True
+                    Else
+                        Dim fromType = semanticModel.GetTypeInfo(lastArgumentExpression, cancellationToken)
+                        Dim toType = DirectCast(symbolInfo.Symbol, IMethodSymbol).Parameters.Last().Type
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb:481]:
```suggestion
                        Dim toType = methodSymbol.Parameters.Last().Type
```

File: src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb [hunk 29]
```diff
@@ -429,124 +444,169 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.ChangeSignature
...
+                        Return Not semanticModel.Compilation.HasImplicitConversion(fromType.Type, toType)
+                    End If
+                Else
+                    Return False
+                End If
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb:486]:
```suggestion
```

File: src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb [hunk 30]
```diff
@@ -429,124 +444,169 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.ChangeSignature
...
+            End If
+
+            Return False
+        End Function
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb:490]: is this the same as the C# version?  it seems familiar.

File: src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb [hunk 31]
```diff
@@ -618,12 +678,28 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.ChangeSignature
...
         End Property
 
+        Protected Overrides Function CreateExplicitParamsArrayFromIndividualArguments(newArguments As SeparatedSyntaxList(Of SyntaxNode), indexInExistingList As Integer, parameterSymbol As IParameterSymbol) As SyntaxNode
+            ' A params array cannot be introduced due to the addition of an omitted 
+            ' argument in VB because you cannot have a named argument to a params array.
+            Throw New InvalidOperationException()
+        End Function
+
+        Protected Overrides Function AddNameToArgument(newArgument As SyntaxNode, name As String) As SyntaxNode
+            Return DirectCast(newArgument, SimpleArgumentSyntax).WithNameColonEquals(NameColonEquals(IdentifierName(name)))
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb:694]: what if it's not a SimpleArgSyntax?

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs [hunk 32]
```diff
@@ -66,7 +66,7 @@ internal override SyntaxTrivia Trivia(SyntaxNode node)
                 return SyntaxFactory.Trivia(structuredTriviaSyntax);
             }
 
-            return default;
+            throw new ArgumentException("Expected 'node' to be a StructuredTriviaSyntax", nameof(node));
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs:69]: ExceptionUtliities.Unexpected

File: src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs [hunk 33]
```diff
@@ -2168,22 +2168,10 @@ internal SyntaxNode AddParentheses(SyntaxNode expression, bool includeElasticTri
...
-        internal abstract bool IsNamedArgument(SyntaxNode syntaxNode);
-
-        internal abstract bool IsWhitespaceTrivia(SyntaxTrivia trivia);
-
-        internal abstract bool IsDocumentationCommentTriviaSyntax(SyntaxNode node);
-
-        internal abstract bool IsParameterNameXmlElementSyntax(SyntaxNode node);
-
-        internal abstract SyntaxNode[] GetContentFromDocumentationCommentTriviaSyntax(SyntaxTrivia trivia);
-
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Editing/SyntaxGenerator.cs:2186]: 👍

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs [hunk 34]
```diff
@@ -150,7 +150,7 @@ public bool IsAnonymousFunction(SyntaxNode node)
         }
 
         public bool IsNamedParameter(SyntaxNode node)
-            => node.CheckParent<NameColonSyntax>(p => p.Name == node);
+            => node.CheckParent<NameColonSyntax>(p => p.Name == node) || (node is ArgumentSyntax arg && arg.NameColon != null);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs:153]: something is wonky here.  the old logic was just busted.  we should just remove that.  And if something breaks it should then call a new method called `IsNameOfNamedArgument`

we absolutely should not have both types of logic running together.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs [hunk 35]
```diff
@@ -1701,6 +1701,20 @@ public void GetPartsOfCastExpression(SyntaxNode node, out SyntaxNode type, out S
...
+            ((XmlElementSyntax)node).StartTag.Name.ToString() == DocumentationCommentXmlNames.ParameterElementName;
+
+        public override SyntaxNode[] GetContentFromDocumentationCommentTriviaSyntax(SyntaxTrivia trivia)
+        {
+            if (trivia.GetStructure() is DocumentationCommentTriviaSyntax documentationCommentTrivia)
+            {
+                return documentationCommentTrivia.Content.ToArray();
+            }
+
+            throw new ArgumentException("Expected 'trivia' to be of type DocumentationCommentTriviaSyntax", nameof(trivia));
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs:1715]: ExceptionUtilities.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/AbstractSyntaxFacts.cs [hunk 36]
```diff
@@ -508,6 +508,22 @@ protected int GetStartOfNodeExcludingAttributes(SyntaxNode root, SyntaxNode node
...
+            => token.RawKind == SyntaxKinds.AwaitKeyword;
+
+        public bool IsIdentifier(SyntaxToken token)
+            => token.RawKind == SyntaxKinds.IdentifierToken;
+
+        public bool IsGlobalNamespaceKeyword(SyntaxToken token)
+            => token.RawKind == SyntaxKinds.GlobalKeyword;
+
+        public bool IsHashToken(SyntaxToken token)
+            => token.RawKind == SyntaxKinds.HashToken;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/AbstractSyntaxFacts.cs:525]: this should move to ISyntaxKinds

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs [hunk 37]
```diff
@@ -1701,6 +1701,20 @@ public void GetPartsOfCastExpression(SyntaxNode node, out SyntaxNode type, out S
...
 
+        public override bool IsParameterNameXmlElementSyntax(SyntaxNode node)
+            => node.IsKind(SyntaxKind.XmlElement) &&
+            ((XmlElementSyntax)node).StartTag.Name.ToString() == DocumentationCommentXmlNames.ParameterElementName;
+
+        public override SyntaxNode[] GetContentFromDocumentationCommentTriviaSyntax(SyntaxTrivia trivia)
+        {
+            if (trivia.GetStructure() is DocumentationCommentTriviaSyntax documentationCommentTrivia)
+            {
+                return documentationCommentTrivia.Content.ToArray();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs:1712]: can we remve teh .ToArray?

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb [hunk 38]
```diff
@@ -170,7 +170,16 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.LanguageServices
...
         Public Function IsNamedParameter(node As SyntaxNode) As Boolean Implements ISyntaxFacts.IsNamedParameter
-            Return node.CheckParent(Of SimpleArgumentSyntax)(Function(p) p.IsNamed AndAlso p.NameColonEquals.Name Is node)
+            If node.CheckParent(Of SimpleArgumentSyntax)(Function(p) p.IsNamed AndAlso p.NameColonEquals.Name Is node) Then
+                Return True
+            End If
+
+            Dim arg = TryCast(node, SimpleArgumentSyntax)
+            If arg IsNot Nothing AndAlso arg.NameColonEquals IsNot Nothing Then
+                Return True
+            End If
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb:180]: same comment as c#.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb [hunk 39]
```diff
@@ -1896,6 +1905,25 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.LanguageServices
             Return False
         End Function
 
+        Public Overrides Function IsParameterNameXmlElementSyntax(node As SyntaxNode) As Boolean Implements ISyntaxFacts.IsParameterNameXmlElementSyntax
+
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb:1909]:
```suggestion
```

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb [hunk 40]
```diff
@@ -1896,6 +1905,25 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.LanguageServices
...
+            Dim xmlElement = TryCast(node, XmlElementSyntax)
+            If xmlElement IsNot Nothing Then
+                Return xmlElement.StartTag.Name.ToString() = DocumentationCommentXmlNames.ParameterElementName
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb:1912]: should not need TOstring() here (same for c# if you do this there).

File: src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb [hunk 41]
```diff
@@ -58,7 +58,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.CodeGeneration
                 Return SyntaxFactory.Trivia(structuredTrivia)
             End If
 
-            Return Nothing
+            Throw New ArgumentException("Expected 'node' to be a StructuredTriviaSyntax", NameOf(node))
```
Comment (CyrusNajmabadi) [inline src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb:61]: ExceptionUtilities.

**Comment by CyrusNajmabadi** [comment]
done with pass. i didn't look at the UI/xaml side at all.

general feedback is that things seem ok, but i really wish we could move away from these massive complex methods doing all this manipulation.  My recommendation would be in the future to potentially pull that out into helper tyeps very responsible for some isolated (but complex) piece of logic.  

i.e. all the stuff with params just seems insanly complex for what doesn't seem like it should be that problematic :)

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs (hunk 8 above)
Comment (dpoeschl) [reply src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs]: You're not getting it because it was wrong. Switched to false and added a test. 😬

File: src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs (hunk 18 above)
Comment (dpoeschl) [reply src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs]: Done

File: src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs (hunk 19 above)
Comment (dpoeschl) [reply src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs]: Done.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb (hunk 40 above)
Comment (dpoeschl) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb:1911]: How? `Name` is an XmlNodeSyntax.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs (hunk 34 above)
Comment (dpoeschl) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs]: I've split it as you suggested. :)

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs (hunk 11 above)
Comment (dpoeschl) [reply src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs]: It was.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb (hunk 40 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb:1907]: well.. check that its' the right type, decompose it, eventually get to a token, and check .ValueText on that :)

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs (hunk 2 above)
Comment (dpoeschl) [reply src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:468]: Changed to `lastArgumentIsNamed`

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs (hunk 1 above)
Comment (dpoeschl) [reply src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs]: I've deduplicated within each language, but not across languages.

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs (hunk 14 above)
Comment (dpoeschl) [reply src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:820]: These are individual elements of a params array, which I don't think can have modifiers?

File: src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb (hunk 23 above)
Comment (dpoeschl) [reply src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb]: The Permute/Add logic has been deduped within each language, but not across languages.

File: src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb (hunk 24 above)
Comment (dpoeschl) [reply src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb:504]: It is. Deduped.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs (hunk 37 above)
Comment (dpoeschl) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs:1715]: How?

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb (hunk 40 above)
Comment (dpoeschl) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb]: Fixed, thanks. For some reason C# didn't require the extra type check.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/AbstractSyntaxFacts.cs (hunk 36 above)
Comment (dpoeschl) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/AbstractSyntaxFacts.cs]: I don't know why these 4 things were here. They were unused. Deleted now.

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs (hunk 14 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:820]: gotcha.  can you add a comment here that this is ok?

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs (hunk 37 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs:1715]: that can be casted to `SyntaxList<SyntaxNode>`

Comment (dpoeschl) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Services/SyntaxFacts/CSharpSyntaxFacts.cs]: Yip. Fixed. Thanks.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb (hunk 38 above)
Comment (dpoeschl) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb]: Fixed here as well.

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs (hunk 13 above)
Comment (dpoeschl) [reply src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs]: Fixed the attribute arguments part.

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs (hunk 14 above)
Comment (dpoeschl) [reply src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:825]: Yep! Done.

File: src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs (hunk 16 above)
Comment (dpoeschl) [reply src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs]: Updated the comment. Not sure if it's any more satisfactory of an answer.

File: src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs (hunk 17 above)
Comment (dpoeschl) [reply src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs:584]: Changed the symbol names here and added a doc comment. It's basically when you're reordering a delegate parameter list with 2 parameters, but you have to worry about BeginInvoke calls with 4 arguments. This adds those extra 2 on.

File: src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb (hunk 30 above)
Comment (dpoeschl) [reply src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb:504]: Deduped most of this logic (everything except the initial data gathering).

File: src/Features/Core/Portable/ChangeSignature/ParameterConfiguration.cs (hunk 22 above)
Comment (dpoeschl) [reply src/Features/Core/Portable/ChangeSignature/ParameterConfiguration.cs]: Wasn't necessary. Deleted.

File: src/EditorFeatures/CSharpTest/ChangeSignature/AddParameterTests.OptionalParameter.SymbolKinds.cs [hunk 42]
```diff
@@ -0,0 +1,115 @@
...
+{
+    public MyAttribute($$int a) { }
+}";
+            var updatedSignature = new[] {
+                new AddedParameterOrExistingIndex(0),
+                AddedParameterOrExistingIndex.CreateAdded("System.Int32", "x", isRequired: false, defaultValue: "10", callSiteValue: "100"),
+                AddedParameterOrExistingIndex.CreateAdded("System.Int32", "y", isRequired: false, defaultValue: "11", isCallsiteOmitted: true),
+                AddedParameterOrExistingIndex.CreateAdded("System.Int32", "z", isRequired: false, defaultValue: "12", callSiteValue: "102")};
+
+            // TODO: The = in the attribute is a bug. You cannot specify that the attribute should use : instead in the SyntaxGenerator
```
Comment (ryzngard) [inline src/EditorFeatures/CSharpTest/ChangeSignature/AddParameterTests.OptionalParameter.SymbolKinds.cs:104]: issue?

File: src/Features/Core/Portable/ChangeSignature/Parameter.cs (hunk 21 above)
Comment (dpoeschl) [reply src/Features/Core/Portable/ChangeSignature/Parameter.cs:84]: Renamed to IsCallsiteTodo and also doc'd.

File: src/EditorFeatures/CSharpTest/ChangeSignature/AddParameterTests.cs [hunk 43]
```diff
@@ -377,6 +377,34 @@ public MyAttribute(int y, byte b, string x)
             await TestChangeSignatureViaCommandAsync(LanguageNames.CSharp, markup, updatedSignature: permutation, expectedUpdatedInvocationDocumentCode: updatedCode);
         }
 
+        [WpfFact, Trait(Traits.Feature, Traits.Features.ChangeSignature)]
+        public async Task AddOptionalParameterWithOmittedCallsiteToAttributeConstructor()
```
Comment (ryzngard) [inline src/EditorFeatures/CSharpTest/ChangeSignature/AddParameterTests.cs:381]: nit: why is this not in the Omitted file?

File: src/EditorFeatures/CSharpTest/ChangeSignature/RemoveParametersTests.cs [hunk 44]
```diff
@@ -184,6 +184,91 @@ void B()
...
+}}
+</Document>";
+            }
+
+            workspaceXml += @"
+    </Project>
+</Workspace>";
+
+            // Ext(this F f, int i, string s) --> Ext(this F f, string s)
+            // If a reference does not bind correctly, it will believe Ext is not an extension
```
Comment (ryzngard) [inline src/EditorFeatures/CSharpTest/ChangeSignature/RemoveParametersTests.cs:245]: this comment seems more like a sticky note you put on your monitor. What's the context? When do we not correctly bind?

File: src/Features/Core/Portable/FeaturesResources.resx [hunk 45]
```diff
@@ -1454,6 +1454,13 @@ This version used in: {2}</value>
   <data name="Make_member_static" xml:space="preserve">
     <value>Make static</value>
   </data>
+  <data name="ChangeSignature_NewParameterIntroduceTODOVariable" xml:space="preserve">
+    <value>TODO</value>
+    <comment>"TODO" is an indication that there is work still to be done.</comment>
+  </data>
+  <data name="ChangeSignature_NewParameterOmitValue" xml:space="preserve">
+    <value>&lt;omit&gt;</value>
```
Comment (ryzngard) [inline src/Features/Core/Portable/FeaturesResources.resx:1462]: Is there value in adding `<` `>` around "omit"? 

Also, should it be capitalized? `Omit`

File: src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialog.xaml [hunk 46]
```diff
@@ -32,13 +34,96 @@
                 <RowDefinition Height="Auto"/>
                 <RowDefinition Height="Auto"/>
                 <RowDefinition Height="Auto"/>
+                <RowDefinition Height="Auto"/>
```
Comment (ryzngard) [inline src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialog.xaml:37]: nit: I believe if they're all Auto you could just use a StackPanel.

Comment (ryzngard) [reply src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialog.xaml:37]: No need to change now though.

Comment (dpoeschl) [reply src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialog.xaml:37]: Good catch -- the type field is supposed to expand to fill the space when the dialog is resized. Oops.

File: src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialogViewModel.cs [hunk 47]
```diff
@@ -26,61 +28,124 @@ internal class AddParameterDialogViewModel : AbstractNotifyPropertyChanged
...
             CallSiteValue = string.Empty;
+            DefaultValue = string.Empty;
         }
 
         public string ParameterName { get; set; }
 
         public string CallSiteValue { get; set; }
 
-        private string TypeNameWithoutErrorIndicator
+        private SymbolDisplayFormat _symbolDisplayFormat = new SymbolDisplayFormat(
```
Comment (ryzngard) [inline src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialogViewModel.cs:54]:
```suggestion
        private static readonly SymbolDisplayFormat _symbolDisplayFormat = new SymbolDisplayFormat(
```

File: src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialogViewModel.cs [hunk 48]
```diff
@@ -26,61 +28,124 @@ internal class AddParameterDialogViewModel : AbstractNotifyPropertyChanged
...
+        public bool TypeBinds => !TypeSymbol!.IsErrorType();
 
-        public ITypeSymbol? TypeSymbol { get; set; }
+        private bool _isRequired;
+        public bool IsRequired
+        {
+            get
+            {
+                return _isRequired;
+            }
```
Comment (ryzngard) [inline src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialogViewModel.cs:76]:
```suggestion
            get => _isRequired;
```

File: src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialogViewModel.cs [hunk 49]
```diff
@@ -26,61 +28,124 @@ internal class AddParameterDialogViewModel : AbstractNotifyPropertyChanged
...
+            set
+            {
+                if (_isRequired != value)
```
Comment (ryzngard) [inline src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialogViewModel.cs:79]:
```suggestion
                if (SetProperty(ref _isRequired, value, nameof(IsRequired))
```

Comment (dpoeschl) [reply src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialogViewModel.cs:79]: Don't even need the nameof! Or the following empty NPC() call! Fixed, thanks.

File: src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialog.xaml (hunk 46 above)
Comment (dpoeschl) [reply src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialog.xaml:37]: Fixed.

File: src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialogViewModel.cs (hunk 47 above)
Comment (dpoeschl) [reply src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialogViewModel.cs]: Thanks! Fixed.

File: src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialogViewModel.cs (hunk 48 above)
Comment (dpoeschl) [reply src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialogViewModel.cs]: There were a couple of these. Fixed them up.

File: src/EditorFeatures/CSharpTest/ChangeSignature/AddParameterTests.cs (hunk 43 above)
Comment (dpoeschl) [reply src/EditorFeatures/CSharpTest/ChangeSignature/AddParameterTests.cs]: Good nit. Fixed.

File: src/Features/Core/Portable/FeaturesResources.resx (hunk 45 above)
Comment (dpoeschl) [reply src/Features/Core/Portable/FeaturesResources.resx:1462]: I like it as is personally. The `<` `>` are there to indicate that it's _special_, it's not going to put in the word "omit".... you've chosen a special option and I'm trying to show you that. Any better ideas on how to do that would be great too.

File: src/EditorFeatures/CSharpTest/ChangeSignature/RemoveParametersTests.cs (hunk 44 above)
Comment (dpoeschl) [reply src/EditorFeatures/CSharpTest/ChangeSignature/RemoveParametersTests.cs]: Removed these comments. They don't make sense anymore.

File: src/EditorFeatures/CSharpTest/ChangeSignature/AddParameterTests.OptionalParameter.SymbolKinds.cs (hunk 42 above)
Comment (dpoeschl) [reply src/EditorFeatures/CSharpTest/ChangeSignature/AddParameterTests.OptionalParameter.SymbolKinds.cs:104]: Linked to https://github.com/dotnet/roslyn/issues/43354 in the code.

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs (hunk 15 above)
Comment (dpoeschl) [reply src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:805]: IsParamsArrayExpanded is false in error scenarios, so it should never get in here. I've added an assert that the parameter symbol we have here is IsParams.

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs (hunk 3 above)
Comment (dpoeschl) [reply src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs]: I NRT'd this file. The Abstract one already was.

File: src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb (hunk 31 above)
Comment (CyrusNajmabadi) [reply src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb:720]: > OmittedArgumentSyntax 

Quite possibly . Though i'm fine with ChangeSig simply bailing out and not crashing on these.  but we need to test.

**Comment by dpoeschl** [comment]
@CyrusNajmabadi @ryzngard I believe I've either fixed or responded to all of your feedback (with the exception of handling `OmittedArgumentSyntax`, which I'll do today). Please take another look and let me know what you think.

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs [hunk 50]
```diff
@@ -476,38 +476,33 @@ private bool IsParamsArrayExpanded(SemanticModel semanticModel, SyntaxNode node,
...
                 {
                     return true;
                 }
-                else if (argumentCount == ((IMethodSymbol)symbolInfo.Symbol).Parameters.Length)
+                else if (argumentCount == methodSymbol.Parameters.Length)
                 {
                     if (lastArgumentHasNameColon)
                     {
-                        return true;
+                        return false;
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs]: =-o   intentional change?

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs (hunk 15 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:848]: 👍

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs [hunk 51]
```diff
@@ -196,7 +196,8 @@ internal partial interface ISyntaxFacts
 
         bool IsPointerMemberAccessExpression(SyntaxNode node);
 
-        bool IsNamedParameter(SyntaxNode node);
+        bool IsNamedArgument(SyntaxNode node);
+        bool IsNameOfNamedArgument(SyntaxNode node);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Services/SyntaxFacts/ISyntaxFacts.cs:200]: 👍

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb [hunk 52]
```diff
@@ -169,17 +169,13 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.LanguageServices
...
-            If node.CheckParent(Of SimpleArgumentSyntax)(Function(p) p.IsNamed AndAlso p.NameColonEquals.Name Is node) Then
-                Return True
-            End If
-
+        Public Function IsNamedArgument(node As SyntaxNode) As Boolean Implements ISyntaxFacts.IsNamedArgument
             Dim arg = TryCast(node, SimpleArgumentSyntax)
-            If arg IsNot Nothing AndAlso arg.NameColonEquals IsNot Nothing Then
-                Return True
-            End If
+            Return arg IsNot Nothing AndAlso arg.NameColonEquals IsNot Nothing
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb:174]:
```suggestion
            Return arg?.NameColonEquals IsNot Nothing
```

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs [hunk 53]
```diff
@@ -450,6 +454,59 @@ private SyntaxNode GetNodeContainingTargetNode(SyntaxNode matchingNode)
...
+            newArguments = AddNewArgumentsToList(
+                declarationSymbol,
+                newArguments,
+                argumentList.Arguments,
+                signaturePermutation,
+                isReducedExtensionMethod,
+                isParamsArrayExpanded,
+                generateAttributeArguments: false);
+
+            return (T)argumentList
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:496]: might be good to just have an example in comments of what the two steps above this do.

File: src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb [hunk 54]
```diff
@@ -444,6 +454,33 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.ChangeSignature
             Return vbnode
         End Function
 
+        Private Function UpdateArgumentList(
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb:457]: i shed a tear that we can't share this with C# :)

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs (hunk 50 above)
Comment (dpoeschl) [reply src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs]: Yes. You pointed out that it didn't make sense, and you were right. I fixed it and added a test. 😬😬😬

File: src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb [hunk 55]
```diff
@@ -524,6 +518,18 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.ChangeSignature
...
 
+        Private Sub GetArgumentListDetails(
+            argumentList As ArgumentListSyntax,
+            ByRef argumentCount As Integer,
+            ByRef lastArgumentIsNamed As Boolean,
+            ByRef lastArgumentExpression As ExpressionSyntax)
+
+            argumentCount = argumentList.Arguments.Count
+            Dim isNamed = argumentList.Arguments.LastOrDefault()?.IsNamed
+            lastArgumentIsNamed = isNamed.HasValue AndAlso isNamed.Value
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb:514]: `isNamed.GetValueOrDefault()`

File: src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb [hunk 56]
```diff
@@ -524,6 +518,18 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.ChangeSignature
             Return False
         End Function
 
+        Private Sub GetArgumentListDetails(
+            argumentList As ArgumentListSyntax,
+            ByRef argumentCount As Integer,
+            ByRef lastArgumentIsNamed As Boolean,
+            ByRef lastArgumentExpression As ExpressionSyntax)
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb:510]: maybe doc this.   for example, why do you need the last last argexpr?

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb [hunk 57]
```diff
@@ -1904,7 +1904,10 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.LanguageServices
         Public Overrides Function IsParameterNameXmlElementSyntax(node As SyntaxNode) As Boolean Implements ISyntaxFacts.IsParameterNameXmlElementSyntax
             Dim xmlElement = TryCast(node, XmlElementSyntax)
             If xmlElement IsNot Nothing Then
-                Return xmlElement.StartTag.Name.ToString() = DocumentationCommentXmlNames.ParameterElementName
+                Dim name = TryCast(xmlElement.StartTag.Name, XmlNameSyntax)
+                If name IsNot Nothing Then
+                    Return name.LocalName.ValueText = DocumentationCommentXmlNames.ParameterElementName
+                End If
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb:1910]:
```suggestion
                Return name?.LocalName.ValueText = DocumentationCommentXmlNames.ParameterElementName
```

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs [hunk 58]
```diff
@@ -811,7 +811,12 @@ protected override IEnumerable<AbstractFormattingRule> GetFormattingRules(Docume
 
         protected override SyntaxNode AddNameToArgument(SyntaxNode newArgument, string name)
         {
-            return ((ArgumentSyntax)newArgument).WithNameColon(NameColon(name));
+            return newArgument switch
+            {
+                ArgumentSyntax a => a.WithNameColon(NameColon(name)),
+                AttributeArgumentSyntax a => a.WithNameColon(NameColon(name)),
+                _ => throw ExceptionUtilities.UnexpectedValue(newArgument.Kind())
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:837]: so did we just crash before =-o  ??

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs [hunk 59]
```diff
@@ -541,29 +541,7 @@ private bool IsParamsArrayExpanded(SemanticModel semanticModel, SyntaxNode node,
...
-                    {
-                        var fromType = semanticModel.GetTypeInfo(lastArgumentExpression, cancellationToken);
-                        var toType = methodSymbol.Parameters.Last().Type;
-                        return !semanticModel.Compilation.HasImplicitConversion(fromType.Type, toType);
-                    }
-                }
-            }
-
-            return false;
+            return IsParamsArrayExpandedHelper(symbolInfo.Symbol, argumentCount, lastArgumentIsNamed, semanticModel, lastArgumentExpression, cancellationToken);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:585]: 👍

File: src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs [hunk 60]
```diff
@@ -970,5 +970,32 @@ protected ImmutableArray<SyntaxTrivia> GetPermutedDocCommentTrivia(Document docu
...
+                if (argumentCount > methodSymbol.Parameters.Length)
+                {
+                    return true;
+                }
+
+                if (argumentCount == methodSymbol.Parameters.Length)
+                {
+                    if (lastArgumentIsNamed)
+                    {
+                        return false;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ChangeSignature/AbstractChangeSignatureService.cs:988]: doc.

File: src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb (hunk 31 above)
Comment (dpoeschl) [reply src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb:720]: Addressed. Thanks.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb (hunk 52 above)
Comment (dpoeschl) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb:174]: Fixed.

File: src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb (hunk 55 above)
Comment (dpoeschl) [reply src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb:514]: Fixed.

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs (hunk 53 above)
Comment (dpoeschl) [reply src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:496]: Done

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb (hunk 57 above)
Comment (dpoeschl) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb:1910]: Fixed, thanks.

File: src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs (hunk 58 above)
Comment (dpoeschl) [reply src/Features/CSharp/Portable/ChangeSignature/CSharpChangeSignatureService.cs:837]: Yes. /ducks.

File: src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb (hunk 56 above)
Comment (dpoeschl) [reply src/Features/VisualBasic/Portable/ChangeSignature/VisualBasicChangeSignatureService.vb:510]: Updated method name for clarity

File: src/VisualStudio/Core/Def/ServicesVSResources.resx [hunk 61]
```diff
@@ -1437,4 +1453,26 @@ I agree to all of the foregoing:</value>
   <data name="Razor_CSharp_Language_Server_Client" xml:space="preserve">
     <value>Razor C# Language Server Client</value>
   </data>
+  <data name="Type_name_does_not_parse_correctly" xml:space="preserve">
+    <value>Type name does not parse correctly</value>
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/ServicesVSResources.resx:1457]:
```suggestion
    <value>Type name has a syntax error</value>
```

Since I think "syntax error" might be a more common term?

File: src/VisualStudio/Core/Def/ServicesVSResources.resx [hunk 62]
```diff
@@ -1437,4 +1453,26 @@ I agree to all of the foregoing:</value>
...
+    <comment>"Type" is the programming language concept</comment>
+  </data>
+  <data name="Type_name_parses_correctly_and_is_recognized" xml:space="preserve">
+    <value>Type name parses correctly and is recognized</value>
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/ServicesVSResources.resx:1461]:
```suggestion
    <value>Type name is valid</value>
```

File: src/VisualStudio/Core/Def/ServicesVSResources.resx [hunk 63]
```diff
@@ -1437,4 +1453,26 @@ I agree to all of the foregoing:</value>
...
+    <comment>"Type" is the programming language concept</comment>
+  </data>
+  <data name="Type_name_parses_correctly_but_is_not_recognized" xml:space="preserve">
+    <value>Type name parses correctly but is not recognized</value>
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/ServicesVSResources.resx:1465]:
```suggestion
    <value>Type name is not recognized</value>
```

Comment (dpoeschl) [reply src/VisualStudio/Core/Def/ServicesVSResources.resx]: Took this one. Thanks.

File: src/VisualStudio/Core/Def/ServicesVSResources.resx (hunk 61 above)
Comment (dpoeschl) [reply src/VisualStudio/Core/Def/ServicesVSResources.resx]: Took this one, thanks.

File: src/VisualStudio/Core/Def/ServicesVSResources.resx (hunk 62 above)
Comment (dpoeschl) [reply src/VisualStudio/Core/Def/ServicesVSResources.resx]: Combined these into "Type name is recognized"

File: src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialogViewModel.ParameterViewModels.cs [hunk 64]
```diff
@@ -0,0 +1,246 @@
...
+                    if (!string.IsNullOrWhiteSpace(Default))
+                    {
+                        text += $" = {Default}";
+                    }
+
+                    return text;
+                }
+            }
+
+            public bool NeedsBottomBorder
```
Comment (ryzngard) [inline src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialogViewModel.ParameterViewModels.cs:61]: hmm... this design seems a little odd. Could the be abstract as well and handled in the implementing classes?

File: src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialogViewModel.ParameterViewModels.cs [hunk 65]
```diff
@@ -0,0 +1,246 @@
...
+            private readonly AddedParameter _addedParameter;
+
+            public AddedParameterViewModel(ChangeSignatureDialogViewModel changeSignatureDialogViewModel, AddedParameter addedParameter)
+                : base(changeSignatureDialogViewModel)
+            {
+                _addedParameter = addedParameter;
+            }
+
+            /// <summary>
+            /// Display text for the type in the UI, including a marker if it doesn't bind.
```
Comment (ryzngard) [inline src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialogViewModel.ParameterViewModels.cs:101]: this would be good for `/// <inherit-doc /> `

File: src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialogViewModel.ParameterViewModels.cs [hunk 66]
```diff
@@ -0,0 +1,246 @@
...
+            /// </summary>
+            public override string Type => _addedParameter.TypeName;
+
+            public override Visibility TypeWarningVisibility => _addedParameter.TypeBinds ? Visibility.Collapsed : Visibility.Visible;
+
+            public override string ParameterName => _addedParameter.Name;
+
+            public override bool IsRemoved { get => false; set => throw new InvalidOperationException(); }
```
Comment (ryzngard) [inline src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialogViewModel.ParameterViewModels.cs:109]:
```suggestion
            public override bool IsRemoved 
            { 
                get => false; 
                set => throw new InvalidOperationException(); 
            }
```

File: src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialogViewModel.ParameterViewModels.cs [hunk 67]
```diff
@@ -0,0 +1,246 @@
...
+            }
+
+            public override string CallSiteValue => _addedParameter.CallSiteValue;
+
+            public override string InitialIndex => "+";
+
+            // Newly added parameters cannot have modifiers yet
+            public override string Modifier => string.Empty;
+
+            // Only required parameters are supported currently
```
Comment (ryzngard) [inline src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialogViewModel.ParameterViewModels.cs:139]: not sure I understand this comment. Wouldn't that mean that the `IsRequired` below should always return true?

File: src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialogViewModel.cs [hunk 68]
```diff
@@ -94,15 +161,87 @@ private void SendFailureNotification(string message)
...
+                        ? ServicesVSResources.Type_name_is_recognized
+                        : ServicesVSResources.Type_name_is_not_recognized;
+                }
+            }
+
+            NotifyPropertyChanged(nameof(TypeBindsDynamicStatus));
+            NotifyPropertyChanged(nameof(TypeBindsImage));
+            NotifyPropertyChanged(nameof(TypeDoesNotBindImage));
+            NotifyPropertyChanged(nameof(TypeDoesNotParseImage));
+            NotifyPropertyChanged(nameof(TypeIsEmptyImage));
```
Comment (ryzngard) [inline src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialogViewModel.cs:210]: This looks tedious, why do the properties not NotifyPropertyChanged themselves?

File: src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialogViewModel.ParameterViewModels.cs (hunk 64 above)
Comment (dpoeschl) [reply src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialogViewModel.ParameterViewModels.cs:61]: Why would the implementing classes handle this? The logic is the same for Existing/Added?

File: src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialogViewModel.ParameterViewModels.cs (hunk 65 above)
Comment (dpoeschl) [reply src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialogViewModel.ParameterViewModels.cs:101]: Actually don't need it at all anymore. It was only there for clarification about the "doesn't bind" "marker" which is no more.

File: src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialogViewModel.ParameterViewModels.cs (hunk 66 above)
Comment (dpoeschl) [reply src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialogViewModel.ParameterViewModels.cs:109]: Fixed.

File: src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialogViewModel.ParameterViewModels.cs (hunk 67 above)
Comment (dpoeschl) [reply src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialogViewModel.ParameterViewModels.cs:139]: Stale comment deleted.

File: src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialogViewModel.cs (hunk 68 above)
Comment (dpoeschl) [reply src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialogViewModel.cs:210]: They don't change, only their Visibility changes. How would they NPC themselves?

Comment (ryzngard) [reply src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialogViewModel.cs:210]: aren't these values visibility values that get bound? Maybe I'm just confusing some of the names.

File: src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialogViewModel.ParameterViewModels.cs (hunk 64 above)
Comment (ryzngard) [reply src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialogViewModel.ParameterViewModels.cs:61]: The `this ==` is basically checking implementation details of subclasses right?

File: src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialogViewModel.cs (hunk 68 above)
Comment (dpoeschl) [reply src/VisualStudio/Core/Def/Implementation/ChangeSignature/AddParameterDialogViewModel.cs:210]: Talked offline and we could do this either way. Leaving as-is for now.

File: src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialogViewModel.ParameterViewModels.cs (hunk 64 above)
Comment (dpoeschl) [reply src/VisualStudio/Core/Def/Implementation/ChangeSignature/ChangeSignatureDialogViewModel.ParameterViewModels.cs:61]: Talked offline. Going to leave this as-is.

**Comment by dpoeschl** [comment]
Updated the dialog layout with @ryzngard:

image

**Comment by dpoeschl** [comment]
@jinujoseph We're looking good here. Is `master` the right target branch (can never be too sure after last time...)? Is there anything else needed?

**Comment by jinujoseph** [comment]
@dpoeschl master branch is right , lets Ship it !!
