### PR TITLE
Fully qualify unimported type name when in import directive

### LINKED ISSUE #37038: Completion for "Show items from unimported namespaces" within a using alias results in unbuildable code
Using aliases need to full specify types used as generic arguments. "Show items from unimported namespaces" is unaware of that and attempts to add a using directive, which still results in a build error.

**Steps to Reproduce**:

``` C#
using System;

using CollectionOfStringBuilders = System.Collections.Generic.List<StringBui>
```

**Expected Behavior**:
``` C#
using System;

using CollectionOfStringBuilders = System.Collections.Generic.List<System.Text.StringBuilder>
```

**Actual Behavior**:
``` C#
using System;
using System.Text;
using CollectionOfStringBuilders = System.Collections.Generic.List<StringBuilder>
```

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'StringBuilder' could not be found (are you missing a using directive or an assembly reference?)	ConsoleApp5	C:\Users\davkean\source\repos\ConsoleApp5\ConsoleApp5\Program.cs	3	Active
```

tag @genlu

### LINKED ISSUE #37523: Intellisense for using static adds an import rather than a full qualification
**Version Used**: VS 16.3 preview 1

**Steps to Reproduce**:

usingStatic

Make sure "Show Items From Unimported Namespaces" is switched on in `Tools->options->Text Editor->C#->Intellisense`

at the top of a file start typing `using static <SomeType>`
When intellisense shows up for `<SomeType>` press enter.

**Expected Behavior**:

The file now shows 
```csharp
using static <SomeNamespace>.<SomeType>
```

**Actual Behavior**:

The file now shows 
```csharp
using <SomeNamespace>;
using <SomeType>;
```

### PR DESCRIPTION
**Pull request by genlu**
Fix #37038
Fix #37523

### CODE REVIEW

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs [hunk 1]
```diff
@@ -261,31 +268,75 @@ internal override async Task<CompletionChange> GetChangeAsync(Document document,
...
+                var fullyQualifiedNode = fullyQualifiedRoot.FindNode(fullyQualifiedSpan);
+                var fullyQualifiedNodeWithAnnotation = fullyQualifiedNode.WithAdditionalAnnotations(Simplifier.Annotation);
+
+                var annotatedRoot = fullyQualifiedRoot.ReplaceNode(fullyQualifiedNode, fullyQualifiedNodeWithAnnotation);
+                var annotatedDocument = document.WithSyntaxRoot(annotatedRoot);
+
+                var simplifiedDocument = await Simplifier.ReduceAsync(annotatedDocument, cancellationToken: cancellationToken).ConfigureAwait(false);
+
+                var changes = await simplifiedDocument.GetTextChangesAsync(document, cancellationToken).ConfigureAwait(false);
+                return Utilities.Collapse(originalText, changes.ToImmutableArray());
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs]: this is a surprisingly large amount of work to have to do.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs [hunk 2]
```diff
@@ -261,31 +268,75 @@ internal override async Task<CompletionChange> GetChangeAsync(Document document,
...
+                //      using System.Text;
+                //
+                //      namespace Foo
+                //      {
+                //          using CollectionOfStringBuilders = List<StringBuilder>;
+                //      }
+                //
+                // Here we will always choose to qualify the unimported type, just to be consistent and keeps things simple.
+                var syntaxContext = await CreateContextAsync(document, completionListSpan.Start, cancellationToken).ConfigureAwait(false);
+                return (syntaxContext.IsInImportsDirective, true);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs]: this si not actually desirable.  users have indicated that they would prefer fully qualified names in imports so that they know what symbol this is actually resolving to.

Plus, you end up needing a massive amount of code to simplify this (which is also surpirsing) which i would prefer just be gone :)

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs]: or, alternatively, why not just check:

1. if you're on the RHS of an alias, and you are *nested*, only then should you use the minimal name, and add the import.
2. otherwise, if you're on the RHS of an alias, just spit out hte fully qualified name.

Then there's no need to do any sort of post-simplification pass for this very minor case.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs (hunk 1 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs]: Yea, I'm wondering if there's a better way to archive this.

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs (hunk 2 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs]: OK, I prefer "always fully qualify", makes everything simpler. Will fix

**Comment by genlu** [comment]
Could I get a review on this? @dotnet/roslyn-ide

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs (hunk 2 above)
Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs]: Done

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs [hunk 3]
```diff
@@ -285,7 +286,29 @@ static bool ShouldCompleteWithFullyQualifyTypeName(Document document)
...
+                //      using System.Text;
+                //
+                //      namespace Foo
+                //      {
+                //          using CollectionOfStringBuilders = List<StringBuilder>;
+                //      }
+                //
+                // Here we will always choose to qualify the unimported type, just to be consistent and keeps things simple.
+                var syntaxContext = await CreateContextAsync(document, completionListSpan.Start, cancellationToken).ConfigureAwait(false);
+                return syntaxContext.IsInImportsDirective;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs]: fwiw:

1. i'm really surprised we don't have one of these already.  consider looking up higher in the callstack to see if someone created a context we can pass along.
2. contexts aren't cheap (but they're not uber expensive either).  Consider just inlining whatever that call does to determine IsInImportsDirective so we don't have to do all the rest of its computation.

Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs]: Will do. Thx!

**Comment by genlu** [comment]
@dpoeschl Could you please review this? Thanks!

File: src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs [hunk 4]
```diff
@@ -35,9 +35,11 @@ internal abstract partial class AbstractTypeImportCompletionProvider : CommonCom
             SemanticModel semanticModel,
             CancellationToken cancellationToken);
 
+        protected abstract Task<bool> IsInImportsDirectiveAsync(Document document, int position, CancellationToken cancellationToken);
+
         // Telemetry shows that the average processing time with cache warmed up for 99th percentile is ~700ms.
         // Therefore we set the timeout to 1s to ensure it only applies to the case that cache is cold.
-        internal int TimeoutInMilliseconds => 1000;
+        internal static int TimeoutInMilliseconds { get; set; } = 1000;
```
Comment (ivanbasov) [inline src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs]: >static [](start = 17, length = 6)

What is the benefit of making it static?
Can we execute tests in parallel and break it?

Comment (ivanbasov) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs]: Other than that the PR looks good. But this one concerns me.

---
In reply to: [308491939](https://github.com/dotnet/roslyn/pull/37290#discussion_r308491939) [](ancestors = 308491939)

Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs]: That's a good point. The reason it's static is to make it easier to disable the timebox during tests (since it's not easy to get the provider object itself during tests, and I don't want to add an additional option just for test purpose)

There are 3 kinds of tests that might be affected by this.
1. completion provider tests that are specifically written for import completion. For those, this value is always set to -1 to avoid flakiness, so being static shouldn't be an issue.
2. completion command handler tests. Those are WfpFact/WpfTheory, which I believe can't be executed in parallel.
3. Integration tests. I don't think these can be executed in parallel either.

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs]: You can do this through instance state that is passed in through a mef import.  i.e. something that is queried to get the delay.  In tests you pass in an instance that says 'infinite delay'.

Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs]: So something like this?
http://source.roslyn.io/#Roslyn.Services.Test.Utilities/TestExperimentationService.cs,13

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs]: Statics are really really unpleasant.  It would be easy for this to lead to some *very* hard to debug flakeyness in tests.  I would really try to avoid it if possible.  Using an 'option' is fine with me as well.

Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs]: I totally agree, and will definitely fix this one way or another. I just want to avoid potential conflict this would cause with the expander PR. As I said above, I believe this doesn't affect tests for now. Once this is merged, I will update the expander PR and fix this there immediately (which will be merged as soon as our integration test machine is updated to 16.3 preview 1)

Comment (genlu) [reply src/Features/Core/Portable/Completion/Providers/ImportCompletionProvider/AbstractTypeImportCompletionProvider.cs]: Fixed.
