### PR TITLE
Out as return only

### LINKED ISSUE #62094: References within `out` parameter should not be considered as potentially escaping
The following should compile without errors.

References within `y` should not be considered as potentially escaping the method invocation `F0(ref x, out y)` because `y` is an output only.
```csharp
ref struct R
{
    public R(ref int i) { }
}

class Program
{
    static void F0(ref R a, out R b)
    {
        b = a;
    }

    static void F1(ref R x)
    {
        int i = 1;
        R y = new R(ref i);
        F0(ref x, out y);
    }
}
```
Result:
```
(17,23): error CS8352: Cannot use variable 'y' in this context because it may
    expose referenced variables outside of their declaration scope
(17,9): error CS8350: This combination of arguments to 'Program.F0(ref R, out R)' is disallowed
    because it may expose variables referenced by parameter 'b' outside of their declaration scope
```

Relates to test plan https://github.com/dotnet/roslyn/issues/59194

### LINKED ISSUE #64155: Change value escape of 'out' parameters to ReturnOnly
```cs
ref struct ByteContainer
{
    public byte B;
}

ref struct RefByteContainer
{
    public ref byte RB;

    public RefByteContainer(ref ByteContainer bc)
    {
        RB = ref bc.B; // CS9079: Cannot ref-assign 'bc.B' to 'RB' because 'bc.B' can only escape the current method through a return statement.
    }

    public RefByteContainer Create(ref ByteContainer bc)
    {
        return new RefByteContainer { RB = ref bc.B }; // ok
    }

    public void Create(ref ByteContainer bc, out RefByteContainer rbc)
    {
        rbc.RB = ref bc.B; // CS9079: Cannot ref-assign 'bc.B' to 'RB' because 'bc.B' can only escape the current method through a return statement.
    }
}
```

This shows that constructors end up being less "capable" than factory methods. We might want to adjust the rules for 'out' parameters (including 'this' in constructors). We will have to think through whether it would hurt other scenarios to do so. cc @jaredpar @cston

### LINKED ISSUE #64365: Breaking change for methods with multiple refs
Consider the following code:

```csharp
ref struct RS
{
  void M()
  {
    int i = default;
    G(ref this, ref i); 
  }
}

static void G(ref RS rs, in int i)
{
  ...
}
```

This code compiled in C# 7.2 but fails in C# 11. The reason for the change is C# 11 introduced `ref` fields and now the method `G` has the potential of capturing `i` as a field of `rs`. This was an intentional breaking change that came with doing the `ref` field work and approved by LDM. It was a necessary evil of doing `ref` fields because return and assignment to `ref` parameters were inseparable concepts. 

The concept of *return only* scope changed that and now `capture` and assign to `ref` parameter are separable concepts. As such we're going to remove this breaking change by marking all `ref` parameters as *return only*.

### PR DESCRIPTION
**Pull request by jaredpar**
Implementation side of https://github.com/dotnet/csharplang/pull/6483

This unifies `out` parameters with return values with respect to ref safety. A value that can be returned through one can be returned through the other. 

closes #62094
closes #64155
closes #64365

**Note** this does not implement having `[UnscopedRef] ref` on a parameter widen the *ref-safe-to-escape*. That will be handled as a follow up change. That is strictly non-breaking, hence lower risk and can be considered in ask mode or post RTM.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 1]
```diff
@@ -3017,6 +3151,21 @@ internal uint GetBroadestValEscape(BoundTupleExpression expr, uint scopeOfTheCon
             return broadest;
         }
 
+#nullable enable 
+
+        internal uint GetValEscape(BoundExpression expr, Symbol? symbol, uint scopeOfTheContainingExpression)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:3156]: This feels wrong but couldn't think of a better way to do it. The other way I considered was looking at the current method under the binder, if it's a constructor and we're looking at `BoundThisReference` then it's the equivalent check. That would avoid making a new method. Wasn't sure if that would catch all cases though.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 2]
```diff
@@ -786,6 +893,11 @@ private uint GetParameterValEscape(ParameterSymbol parameter)
         {
             if (UseUpdatedEscapeRules)
             {
+                if (parameter.RefKind == RefKind.Out && parameter.EffectiveScope != DeclarationScope.Unscoped)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:896]: Specification says

> A `out` parameter for a `ref struct` will have *safe-to-escape* of *return only*.

i.e. we need to check if parameter's type is ref struct here. Also, it seems like this STE is used on `out` parameters regardless of presence of `scoped` or `[UnscopedRef]` modifiers. So it seems like the check of `parameter.EffectiveScope` here can be deleted.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 3]
```diff
@@ -19,6 +20,121 @@ namespace Microsoft.CodeAnalysis.CSharp
 {
     internal partial class Binder
     {
+#nullable enable
+        /// <summary>
+        /// This is an argument that needs to be considered for MAMM rules. It's at least an 
+        /// output argument of the function and very often also an input. Essentially this 
+        /// represents all the in, ref and out arguments.
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:27]: change `in, ref and out` to `ref and out`

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 4]
```diff
@@ -1759,11 +1880,18 @@ bool isRefEscape
             ImmutableArray<RefKind> argRefKindsOpt,
             ImmutableArray<int> argsToParamsOpt,
             bool ignoreArglistRefKinds,
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:1882]: We should rely on the `this` parameter to provide the RefKind to decide whether references can escape into the receiver

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 5]
```diff
@@ -19,6 +20,121 @@ namespace Microsoft.CodeAnalysis.CSharp
 {
     internal partial class Binder
     {
+#nullable enable
+        /// <summary>
+        /// This is an argument that needs to be considered for MAMM rules. It's at least an 
+        /// output argument of the function and very often also an input. Essentially this 
+        /// represents all the in, ref and out arguments.
+        /// </summary>
+        internal readonly struct MixableArgument
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:29]: Let's consider whether we can name this in a way that makes it clear we are talking about a "destination" of a mixing scenario.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 6]
```diff
@@ -19,6 +20,121 @@ namespace Microsoft.CodeAnalysis.CSharp
...
+
+            internal bool IsArgList { get; }
+
+            internal EscapeArgument(ParameterSymbol? parameter, BoundExpression argument, RefKind refKind, bool isArgList = false)
+            {
+                Debug.Assert(!isArgList || parameter is null);
+                Argument = argument;
+                Parameter = parameter;
+                RefKind = refKind;
+                IsArgList = isArgList;
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:77]: It looks like this property is never read

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 5 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:29]: How about `MixableDestination`?

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 6 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:77]: Correct. Will remove.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 7]
```diff
@@ -3838,50 +3838,14 @@ class Program
...
-                //     static void F50(scoped ref R x, scoped ref R y) { F0(__arglist(ref x, ref y)); } // 5
-                Diagnostic(ErrorCode.ERR_RefReturnScopedParameter, "x").WithArguments("x").WithLocation(11, 72),
-                // (12,55): error CS8350: This combination of arguments to 'Program.F1(ref R, __arglist)' is disallowed because it may expose variables referenced by parameter '__arglist' outside of their declaration scope
-                //     static void F51(scoped ref R x, scoped ref R y) { F1(ref x, __arglist(ref y)); } // 6
-                Diagnostic(ErrorCode.ERR_CallArgMixing, "F1(ref x, __arglist(ref y))").WithArguments("Program.F1(ref R, __arglist)", "__arglist").WithLocation(12, 55),
-                // (12,79): error CS9075: Cannot return a parameter by reference 'y' because it is scoped to the current method
-                //     static void F51(scoped ref R x, scoped ref R y) { F1(ref x, __arglist(ref y)); } // 6
-                Diagnostic(ErrorCode.ERR_RefReturnScopedParameter, "y").WithArguments("y").WithLocation(12, 79));
+            comp.VerifyEmitDiagnostics();
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:3841]: We should have errors here, at least when we call `F1` and the argument for parameter `ref R a` is `scoped ref`. This is because we could assign `__refvalue(...) = M(ref a)` in the implementation of `F1` and `ref a` will escape.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 8]
```diff
@@ -1855,17 +2033,89 @@ bool isRefEscape
...
+
+            bool includeRefScopes = shouldIncludeRefScopes();
+            int index = 0;
+            while (index < escapeValues.Count)
+            {
+                var tuple = escapeValues[index];
+                if (!includeRefScopes && tuple.IsRefEscape)
+                {
+                    escapeValues.RemoveAt(index);
+                }
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2058]: Consider moving `includeRefScopes` and this check into `GetFilteredArguments()` to avoid adding to the list, then removing after.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 9]
```diff
@@ -19,6 +21,153 @@ namespace Microsoft.CodeAnalysis.CSharp
...
+        {
+            /// <summary>
+            /// This will be null in cases like arglist or a function pointer receiver.
+            /// </summary>
+            internal ParameterSymbol? Parameter { get; }
+
+            internal BoundExpression Argument { get; }
+
+            /// <summary>
+            /// This differentiates whethere the value can only escape to <see cref="EscapeLevel.CallingMethod"/>
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:133]: >whethere [](http://example.com/codeflow?start=36&length=8)

Typo.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 10]
```diff
@@ -19,6 +21,153 @@ namespace Microsoft.CodeAnalysis.CSharp
...
+
+            internal EscapeValue(ParameterSymbol parameter, BoundExpression argument, EscapeLevel escapeLevel, bool isRefEscape)
+            {
+                Argument = argument;
+                Parameter = parameter;
+                EscapeLevel = escapeLevel;
+                IsRefEscape = isRefEscape;
+            }
+
+            internal EscapeValue(BoundExpression argument, EscapeLevel escapeLevel, bool isRefEscape)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:148]: >EscapeValue [](http://example.com/codeflow?start=21&length=11)

Consider removing this constructor and passing `parameter: null` explicitly at the call sites. Or if we really need multiple constructors, have this constructor call the constructor above.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 11]
```diff
@@ -4232,6 +4118,46 @@ static void F2(ref R x2, ref R y2)
                 Diagnostic(ErrorCode.ERR_EscapeVariable, "y1").WithArguments("y1").WithLocation(13, 16));
         }
 
+        /// <summary>
+        /// Ensure that readonly members / types is properly accounted for
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:4122]: >is [](http://example.com/codeflow?start=49&length=2)

"are"

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 12]
```diff
@@ -21442,7 +21370,7 @@ public void ReturnOnlyScope_02()
                 static void M3(out S p1, ref S p2) {
                     p1 = default;
                     p2.refField = ref p1.field; // 3
-                    p2.refField = ref p1.refField; // Okay
+                    p2.refField = ref p1.refField; // 9
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:21373]: >9 [](http://example.com/codeflow?start=54&length=1)

`// 4`, etc.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 13]
```diff
@@ -21458,7 +21386,7 @@ public void ReturnOnlyScope_02()
                 }
 
                 static void M6(ref S p1, out S2 p2) {
-                    p2 = Inner1(ref p1); // 6
+                    p2 = Inner1(ref p1); // Okay (was 6)
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:21389]: > (was 6) [](http://example.com/codeflow?start=48&length=8)

Consider dropping.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 14]
```diff
@@ -21806,10 +21724,90 @@ public RefByteContainer Create(ref ByteContainer bc)
                 """;
 
             var comp = CreateCompilation(source, runtimeFeature: RuntimeFlag.ByRefFields);
+            comp.VerifyDiagnostics();
+        }
+
+        [Fact]
+        public void OutReturnOnly_Ctor1()
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:21731]: >OutReturnOnly_Ctor1 [](http://example.com/codeflow?start=20&length=19)

What scenario are we testing here?

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 15]
```diff
@@ -21806,10 +21724,90 @@ public RefByteContainer Create(ref ByteContainer bc)
...
+                {
+                    int field;
+                    ref int refField;
+                    public RS(ref int i)
+                    {
+                        refField = ref i;
+                    }
+
+                    static void M1(ref RS i, ref RS rs) => rs = new RS(ref i.field); // 1
+                    static void M2(ref RS i, out RS rs) => rs = new RS(ref i.field);
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:21800]: >out [](http://example.com/codeflow?start=45&length=3)

Consider testing with `[UnscopedRef] out RS rs` as well.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 16]
```diff
@@ -1824,19 +1996,25 @@ bool isRefEscape
...
+                ArrayBuilder<EscapeArgument> escapeArguments)
             {
                 for (int argIndex = 0; argIndex < argsOpt.Length; argIndex++)
                 {
                     var argument = argsOpt[argIndex];
                     var refKind = argRefKindsOpt.IsDefault ? RefKind.None : argRefKindsOpt[argIndex];
-                    argsAndParams.Add((null, argument, refKind));
+                    escapeArguments.Add(new EscapeArgument(parameter: null, argument, refKind, isArgList: true));
+
+                    if (refKind == RefKind.Ref && mixableArguments is not null)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2014]: >refKind [](http://example.com/codeflow?start=24&length=7)

Do we need to check if `argument` is a `ref struct`?

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 17]
```diff
@@ -1855,17 +2033,89 @@ bool isRefEscape
...
+                {
+                    escapeValues.RemoveAt(index);
+                }
+                else
+                {
+                    index++;
+                }
+            }
+
+            bool shouldIncludeRefScopes()
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2065]: >bool [](http://example.com/codeflow?start=12&length=4)

Consider declaring this a `static` local function and passing `symbol` and `isRefEscape` explicitly as parameters, so it's clear what state the return value depends on.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 18]
```diff
@@ -1855,17 +2033,89 @@ bool isRefEscape
...
+            }
+        }
+
+        /// <summary>
+        /// Returns the set of arguments to an invocation that impact ref analysis. This will 
+        /// filter out everything that could never meaningfully contribute to ref analysis. For
+        /// example it will remove anything which corresponds to scope parameters. For ref
+        /// parameters it will place in two values representing both the RSTS and STS
+        /// </summary>
+        private void GetFilteredArguments(
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2101]: >GetFilteredArguments [](http://example.com/codeflow?start=21&length=20)

Consider using a more specific name so it's clear this is used for escape analysis (and with updated escape rules).

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 19]
```diff
@@ -1855,17 +2033,89 @@ bool isRefEscape
...
+                    default:
+                        return false;
+                }
+            }
+        }
+
+        /// <summary>
+        /// Returns the set of arguments to an invocation that impact ref analysis. This will 
+        /// filter out everything that could never meaningfully contribute to ref analysis. For
+        /// example it will remove anything which corresponds to scope parameters. For ref
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2098]: >scope [](http://example.com/codeflow?start=65&length=5)

Perhaps "scoped".

Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2098]: It looks like `scoped out` parameters are still included.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 20]
```diff
@@ -8,6 +8,8 @@
 using System.Collections.Generic;
 using System.Collections.Immutable;
 using System.Diagnostics;
+using System.Diagnostics.CodeAnalysis;
+using System.Dynamic;
```
[the remark this answers is not in the document]
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:12]: > using System.Diagnostics.CodeAnalysis;

This is being used for `[NotNullWhen]` but no idea why `System.Dynamic` is there.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 21]
```diff
@@ -19,6 +21,153 @@ namespace Microsoft.CodeAnalysis.CSharp
 {
     internal partial class Binder
     {
+#nullable enable
+
+        internal enum EscapeLevel : uint
```
[the remark this answers is not in the document]
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:26]: It's not just used for parameters though, it's also used for values. The property on `MixableDestination` yes uses these specifically for parameters (and arglist). But this is the general value of 

> There are two different levels to which a return can happen, let's name them. 

Do you think a comment would help here? Happy to write moer

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 22]
```diff
@@ -2086,103 +2311,59 @@ private bool UseUpdatedEscapeRulesForInvocation(Symbol symbol)
...
-            //     - Ignore the *ref-safe-to-escape* of arguments to `in / ref / out` parameters of `ref struct` types. The corresponding parameters *ref-safe-to-escape* are at most *return only* and hence cannot be returned via `ref` or `out` parameters.
-            //     - Assume the method has a `ref struct` return type.
-            // 2. All `ref` or `out` arguments of `ref struct` types must be assignable by a value with that *safe-to-escape*.
-            //    This applies even when the `ref` argument matches a `scoped ref` parameter.
-
-            if (!symbol.RequiresInstanceReceiver())
-            {
-                // ignore receiver when symbol is static
-                receiverOpt = null;
-            }
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2102]: Is this check not needed?

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 23]
```diff
@@ -19,6 +21,153 @@ namespace Microsoft.CodeAnalysis.CSharp
...
+                ? p.ToString()
+                : Argument.ToString();
+        }
+
+        /// <summary>
+        /// Represents a value being analyzed for escape analysis purposes. This represents the value 
+        /// as it contributes to escape analysis which means arguments can show up multiple times. For
+        /// example `ref x` will be represented as both a val and ref escape
+        /// </summary>
+        internal readonly struct EscapeValue
```
[the remark this answers is not in the document]
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:123]: This type is not just used in MAMM decisions. It's also used for all invocation calculation now.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 24]
```diff
@@ -19,6 +21,153 @@ namespace Microsoft.CodeAnalysis.CSharp
...
+            /// can never be written to by an argument that has a level of <see cref="EscapeLevel.ReturnOnly"/>
+            /// </summary>
+            internal EscapeLevel EscapeLevel { get; }
+
+            internal MixableDestination(ParameterSymbol parameter, BoundExpression argument)
+            {
+                Debug.Assert(parameter.RefKind.IsWritableReference());
+                Argument = argument;
+                Parameter = parameter;
+                EscapeLevel = parameter.RefKind == RefKind.Out ? EscapeLevel.ReturnOnly : EscapeLevel.CallingMethod;
```
[the remark this answers is not in the document]
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:60]: I'm somewhat reluctant to firmly tie those values together. Essentially silently converting the `uint` to `EscapeLevel`. I mostly used them as initializers for convenience. I gave a lot of thought to not doing taht.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 25]
```diff
@@ -1874,73 +2124,47 @@ bool isRefEscape
...
-            // 2. ...
-            foreach (var (parameter, argument, _) in argsAndParams)
-            {
-                // For a given argument `a` that is passed to parameter `p`:
-                // 1. ...
-                // 2. If `p` is `scoped` then `a` does not contribute *safe-to-escape* when considering arguments. 
-                if (parameter?.EffectiveScope == DeclarationScope.ValueScoped)
+            foreach (var (parameter, argument, refKind) in escapeArguments)
+            {
+                // This means it's part of an __arglist or function pointer receiver.
```
[the remark this answers is not in the document]
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2132]: I was attempting to maintain the original code here. I'm also unsure why a function pointer could come into play here. Not sure you can really do those on a ref struct. I will try removing and see what happens.

**Comment by cston** [comment]
>                 case BoundKind.ThisReference:

Does this case need to updated similar to the change in `GetValEscape()`?

---
Refers to: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:3650 in d9608af. [](commit_id = d9608afcddc4dcb7e5282006fcf432fe5588571c, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 26]
```diff
@@ -3046,9 +3227,14 @@ internal uint GetValEscape(BoundExpression expr, uint scopeOfTheContainingExpres
             // otherwise default to ExternalScope (ordinary values)
             switch (expr.Kind)
             {
+                case BoundKind.ThisReference:
+                    if (this.ContainingMember() is MethodSymbol { MethodKind: MethodKind.Constructor })
+                    {
+                        return Binder.ReturnOnlyScope;
+                    }
+                    return Binder.CallingMethodScope;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:3235]: Consider using `ThisParameter` similar to the corresponding code in `GetRefEscape()`:
```csharp
var thisParam = ((MethodSymbol)this.ContainingMember()).ThisParameter;
Debug.Assert(thisParam.Type.Equals(((BoundThisReference)expr).Type, TypeCompareKind.ConsiderEverything));
return GetParameterValEscape(thisParam);
```

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceLocalSymbol.cs [hunk 27]
```diff
@@ -144,6 +144,7 @@ internal sealed override uint ValEscapeScope
                 {
                     return _valEscapeScope;
                 }
+
```
[the remark this answers is not in the document]
Comment (cston) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceLocalSymbol.cs:147]: Consider reverting this change.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 28]
```diff
@@ -1874,73 +2124,47 @@ bool isRefEscape
...
-            if (isRefEscape || checkingMethodArgumentsMustMatch || hasRefStructType(symbol))
-            {
-                foreach (var (parameter, argument, effectiveRefKind) in argsAndParams)
+                if (parameter.RefKind != RefKind.None)
                 {
-                    if (effectiveRefKind == RefKind.None)
+                    if (parameter.EffectiveScope == DeclarationScope.Unscoped)
                     {
-                        continue;
+                        var kind = parameter.Type.IsRefLikeType ? EscapeLevel.ReturnOnly : EscapeLevel.CallingMethod;
```
[the remark this answers is not in the document]
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2152]: Okay not as bad as I thought.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs (hunk 14 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:21731]: Added a comment

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 24 above)
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:60]: I think it would make sense to assert that the value lies in the expected range and convert it. Would be happy to chat more about this to make sure I understand.

**Comment by Sergio0694** [comment]
Me following this PR:

PatrickSpongebobGIF

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 16 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2014]: For better or worse this layer returns all arguments no matter if they are `ref struct` or not. Higher layers filter out the values that aren't going to contribute to escape analysis. I was loath to make a change this deep just now given our time constraints.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 21 above)
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:26]: I guess what I want to know when I see this is: which code elements does it apply to? is it the escape level of a parameter in both regular invocation analysis and MAMM? can it be used anywhere else and if so what's the meaning of it in that context?

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 19 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2098]: Cleaned up the comment here a bit, hope it's clearer now.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 22 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2102]: Every single caller did this check so I just moved it to the implementation.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 29]
```diff
@@ -2086,103 +2311,59 @@ private bool UseUpdatedEscapeRulesForInvocation(Symbol symbol)
...
+                    if (mixableArg.Parameter is not null && object.ReferenceEquals(mixableArg.Parameter, fromParameter))
+                    {
+                        continue;
+                    }
 
-                uint escapeTo = GetValEscape(argument, scopeOfTheContainingExpression);
-                var (parameterToEscape, argToEscape, isRefEscape) = argAndParamToEscape.GetValueOrDefault();
+                    // This checks to see if the value could even be assigned to this argument. For example
+                    // a `ref` to a `ref` can't ever be assigned to the value of any `ref` parameter. The
+                    // rules of the method signature prevent it. Ignore these entirely.
```
[the remark this answers is not in the document]
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2340]: updated that comment a bit.

**Comment by jaredpar** [comment]
@cston, @RikkiGibson addressed most feedback, had some clarification requests on others.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 30]
```diff
@@ -19,6 +20,144 @@ namespace Microsoft.CodeAnalysis.CSharp
...
+
+        private enum EscapeLevel : uint
+        {
+            CallingMethod = Binder.CallingMethodScope,
+            ReturnOnly = Binder.ReturnOnlyScope,
+        }
+
+        /// <summary>
+        /// The destination in a method arguments must match (MAMM) check. This is 
+        /// created primarily for a ref and out arguments of a ref struct. It also applies
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:33]: >for a ref and out [](http://example.com/codeflow?start=30&length=17)

"for ref and out"

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 31]
```diff
@@ -19,6 +20,144 @@ namespace Microsoft.CodeAnalysis.CSharp
...
+            /// <summary>
+            /// In the case this is the argument for a ref / out parameter this will refer
+            /// to the corresponding parameter. This will be null in cases like arguments 
+            /// passed to an arglist
+            /// </summary>
+            internal ParameterSymbol? Parameter { get; }
+
+            /// <summary>
+            /// This destination can only be written to by arguments that have an equal or
+            /// wider this escape level. An destination that is <see cref="EscapeLevel.CallingMethod"/>
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:49]: >wider this escape [](http://example.com/codeflow?start=16&length=17)

"wider escape"?

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 32]
```diff
@@ -796,7 +950,10 @@ private uint GetParameterValEscape(ParameterSymbol parameter)
             }
         }
 
-        private uint GetParameterRefEscape(ParameterSymbol parameter)
+        private static EscapeLevel? GetParameterValEscapeLevel(ParameterSymbol parameter, bool useUpdatedEscapeRules) =>
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:953]: >GetParameterValEscapeLevel [](http://example.com/codeflow?start=36&length=26)

`GetParameterValEscapeLevel()` and `GetParameterRefEscapeLevel()` are unusual (compared other escape analysis methods) because they return a subset of values, and return that as an `EscapeLevel?` rather than a `uint`. Given that, and the fact that these are only used in one call-site each, consider inlining the calls.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 33]
```diff
@@ -1855,17 +2039,82 @@ bool isRefEscape
...
+        /// <summary>
+        /// Returns the set of <see cref="EscapeValue"/> to an invocation that impact ref analysis. 
+        /// This will filter out everything that could never meaningfully contribute to ref analysis. For
+        /// example 
+        ///   - For ref arguments it will return an <see cref="EscapeValue"/> for both ref and 
+        ///     value escape (if appropriate based on scoped-ness of associated parameters)
+        ///   - It will remove value escape for args which correspond to scoped parameters. 
+        ///   - It will remove value escape for non-ref struct.
+        ///   - It will remove ref escape for args which correspond to scoped refs.
+        /// Optionall this will also return all of the <see cref="MixableDestination" /> that
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2096]: >Optionall [](http://example.com/codeflow?start=12&length=9)

Typo.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs (hunk 14 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:21743]: There's no difference in behavior with this test in this PR, correct?

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 32 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:953]: @RikkiGibson suggested I not inline
@cston suggested I inline

:)

Fine with either but at the moment would prefer to keep as is. Happy to change.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 34]
```diff
@@ -2086,103 +2302,60 @@ private bool UseUpdatedEscapeRulesForInvocation(Symbol symbol)
...
+                    if (mixableArg.Parameter is not null && object.ReferenceEquals(mixableArg.Parameter, fromParameter))
+                    {
+                        continue;
+                    }
 
-                uint escapeTo = GetValEscape(argument, scopeOfTheContainingExpression);
-                var (parameterToEscape, argToEscape, isRefEscape) = argAndParamToEscape.GetValueOrDefault();
+                    // This checks to see if the EscapeValue could ever be assigned to this argument based 
+                    // on comparing the EscapeLevel of both. If this could never be assigned due to 
+                    // this then we don't need to consider it for MAMM analysis
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2332]: >analysis [](http://example.com/codeflow?start=71&length=8)

Consider ending multi-sentence comments with ".", for consistency, and to avoid cases where it looks like the last sentence was cut off.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 24 above)
[the remark this answers is not in the document]
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:59]: Just re-used `GetParameterValEscapeLevel` here.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 35]
```diff
@@ -8883,12 +8806,12 @@ static void Main()
             else
             {
                 comp.VerifyEmitDiagnostics(
-                    // (6,9): error CS8350: This combination of arguments to 'A.MayCaptureRef(__arglist)' is disallowed because it may expose variables referenced by parameter '__arglist' outside of their declaration scope
-                    //         MayCaptureRef(__arglist(ref r)); // error: may expose variables outside of their declaration scope
-                    Diagnostic(ErrorCode.ERR_CallArgMixing, "MayCaptureRef(__arglist(ref r))").WithArguments("A.MayCaptureRef(__arglist)", "__arglist").WithLocation(6, 9),
-                    // (6,37): error CS8168: Cannot return local 'r' by reference because it is not a ref local
-                    //         MayCaptureRef(__arglist(ref r)); // error: may expose variables outside of their declaration scope
-                    Diagnostic(ErrorCode.ERR_RefReturnLocal, "r").WithArguments("r").WithLocation(6, 37));
+                    // (7,9): error CS8350: This combination of arguments to 'A.F2(ref R, ref R)' is disallowed because it may expose variables referenced by parameter 'x2' outside of their declaration scope
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:8809]: >(7,9): error CS8350: This combination of arguments to 'A.F2(ref R, ref R)' [](http://example.com/codeflow?start=23&length=74)

This does not appear to be error from this test. Consider unskipping the test or restoring the previous errors.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 36]
```diff
@@ -8849,7 +8772,7 @@ unsafe static R Create()
 
         // Breaking change in C#11: A ref to ref struct argument is considered
         // an unscoped reference when passed to an __arglist.
-        [Theory]
+        [Theory(Skip = "https://github.com/dotnet/roslyn/issues/64308")]
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:8775]: >Skip = "https://github.com/dotnet/roslyn/issues/64308" [](http://example.com/codeflow?start=16&length=54)

Consider unskipping the test and including the actual errors reported below, along with a link to the bug.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs (hunk 7 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:3841]: This change updates `ref` passed to `arglist` as not being being treated like any other `ref` parameter. So they can escape to caller but not in a cyclic fashion.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs (hunk 36 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:8775]: Is there still a breaking change here with `__arglist`? If not, please remove [https://github.com/dotnet/roslyn/blob/main/docs/compilers/CSharp/Compiler%20Breaking%20Changes%20-%20DotNet%207.md#ref-to-ref-struct-argument-considered-unscoped-in-__arglist](https://github.com/dotnet/roslyn/blob/main/docs/compilers/CSharp/Compiler%20Breaking%20Changes%20-%20DotNet%207.md#ref-to-ref-struct-argument-considered-unscoped-in-__arglist).

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 37]
```diff
@@ -19,6 +20,145 @@ namespace Microsoft.CodeAnalysis.CSharp
...
+            /// <summary>
+            /// This destination can only be written to by arguments that have an equal or
+            /// wider escape level. An destination that is <see cref="EscapeLevel.CallingMethod"/>
+            /// can never be written to by an argument that has a level of <see cref="EscapeLevel.ReturnOnly"/>.
+            /// </summary>
+            internal EscapeLevel EscapeLevel { get; }
+
+            internal MixableDestination(ParameterSymbol parameter, BoundExpression argument)
+            {
+                Debug.Assert(parameter.RefKind.IsWritableReference() && parameter.Type.IsRefLikeType);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:56]: > && parameter.Type.IsRefLikeType [](http://example.com/codeflow?start=68&length=32)

It looks like this was dropped in commit 17. Was that intentional?

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 38]
```diff
@@ -19,6 +20,145 @@ namespace Microsoft.CodeAnalysis.CSharp
...
+                Debug.Assert(GetParameterValEscapeLevel(parameter, useUpdatedEscapeRules: true).HasValue);
+                Argument = argument;
+                Parameter = parameter;
+                EscapeLevel = GetParameterValEscapeLevel(parameter, useUpdatedEscapeRules: true)!.Value; ;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:60]: > ; [](http://example.com/codeflow?start=104&length=2)

Trailing `;`.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 39]
```diff
@@ -1855,17 +2040,82 @@ bool isRefEscape
...
+        /// <summary>
+        /// Returns the set of <see cref="EscapeValue"/> to an invocation that impact ref analysis. 
+        /// This will filter out everything that could never meaningfully contribute to ref analysis. For
+        /// example: 
+        ///   - For ref arguments it will return an <see cref="EscapeValue"/> for both ref and 
+        ///     value escape (if appropriate based on scoped-ness of associated parameters).
+        ///   - It will remove value escape for args which correspond to scoped parameters. 
+        ///   - It will remove value escape for non-ref struct.
+        ///   - It will remove ref escape for args which correspond to scoped refs.
+        /// Optional this will also return all of the <see cref="MixableDestination" /> that
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2097]: >Optional [](http://example.com/codeflow?start=12&length=8)

"Optionally"?

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 37 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:56]: Don't know what you mean, that check is in the code right now.

**Comment by cston** [comment]
>         [InlineData(LanguageVersion.CSharp11)]

Consider replacing with `[Fact]` since we have separate code paths for the two language versions with in the test.

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/RefEscapingTests.cs:2940 in e11141d. [](commit_id = e11141dc8685c5f14eebcef0b51f1ebbf098cdbb, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 37 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:56]: Never mind, I misread the diff.

**Comment by cston** [comment]
>         public void BreakingChange_RefToRefStructInArglist(

"BreakingChange_" prefix can be removed, as well as the comment above the test.

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:8777 in e11141d. [](commit_id = e11141dc8685c5f14eebcef0b51f1ebbf098cdbb, deletion_comment = False)

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 40]
```diff
@@ -9495,7 +9405,7 @@ static void Main()
         R a = new R();
         R b = new R();
         R c = new R();
-        R d;
+        scoped R d;
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:9408]: >scoped [](http://example.com/codeflow?start=8&length=6)

We should also test the case where the `out` local is not marked `scoped`.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 41]
```diff
@@ -1855,17 +2040,82 @@ bool isRefEscape
...
+                symbol,
+                receiver,
+                parameters,
+                argsOpt,
+                argRefKindsOpt,
+                argsToParamsOpt,
+                includeRefEscape: shouldIncludeRefScopes(symbol, isRefEscape),
+                ignoreArglistRefKinds,
+                mixableArguments: null,
+                escapeValues); ;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:2056]: > ; [](http://example.com/codeflow?start=30&length=2)

Trailing `;`.

**Review by RikkiGibson — APPROVED** [review]

**Comment by RikkiGibson** [comment]
The diagnostic message for ERR_RefAssignReturnOnly should mention that you can return through a return statement or an out parameter.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs (hunk 40 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:9317]: Added `OutReturnOnly_5` which enumerates the different cases here.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 42]
```diff
@@ -931,11 +921,21 @@ private bool CheckParameterValueKind(SyntaxNode node, BoundParameter parameter,
...
-            if (UseUpdatedEscapeRules)
+            Binder.ReturnOnlyScope => EscapeLevel.ReturnOnly,
+            Binder.CallingMethodScope => EscapeLevel.CallingMethod,
+            _ => null,
+        };
+
+        private uint GetParameterValEscape(ParameterSymbol parameter) =>
+            GetParameterValEscape(parameter, UseUpdatedEscapeRules);
+
+        private static uint GetParameterValEscape(ParameterSymbol parameter, bool useUpdatedEcapeRules)
```
[the remark this answers is not in the document]
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs:935]: I was attempting to do that with my change. Was having the call sites force through the `useUpdatedEscapeRules` based on earlier decisions in the code. Think your and my version should align on behavior but yours is more robust.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 43]
```diff
@@ -6005,30 +5931,33 @@ public void AssignRefTo_RefField()
...
+    static void AssignOutToIn<T>(in S<T> sIn, out T tOut) { tOut = default; sIn.F = ref tOut; } // 14
+    static void AssignInToIn<T>(in S<T> sIn, in T tIn)    { sIn.F = ref tIn; } // 15
 }";
             var comp = CreateCompilation(source, runtimeFeature: RuntimeFlag.ByRefFields);
             comp.VerifyEmitDiagnostics(
                 // (9,59): error CS8374: Cannot ref-assign 'tValue' to 'F' because 'tValue' has a narrower escape scope than 'F'.
                 //     static void AssignValueToValue<T>(S<T> s, T tValue) { s.F = ref tValue; } // 1
                 Diagnostic(ErrorCode.ERR_RefAssignNarrower, "s.F = ref tValue").WithArguments("F", "tValue").WithLocation(9, 59),
+                // (10,59): error CS9079: Cannot ref-assign 'tRef' to 'F' because 'tRef' can only escape the current method through a return statement.
+                //     static void AssignRefToValue<T>(S<T> s, ref T tRef) { s.F = ref tRef; } // 14
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:5959]: >// 14 [](http://example.com/codeflow?start=95&length=5)

Is this correct?

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 44]
```diff
@@ -6038,6 +5967,9 @@ class Program
                 // (14,64): error CS8374: Cannot ref-assign 'tValue' to 'F' because 'tValue' has a narrower escape scope than 'F'.
                 //     static void AssignValueToRef<T>(ref S<T> sRef, T tValue) { sRef.F = ref tValue; } // 4
                 Diagnostic(ErrorCode.ERR_RefAssignNarrower, "sRef.F = ref tValue").WithArguments("F", "tValue").WithLocation(14, 64),
+                // (15,64): error CS9079: Cannot ref-assign 'tRef' to 'F' because 'tRef' can only escape the current method through a return statement.
+                //     static void AssignRefToRef<T>(ref S<T> sRef, ref T tRef) { sRef.F = ref tRef; } // 15
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:5971]: >// 15 [](http://example.com/codeflow?start=103&length=5)

Is this correct?

**Comment by cston** [comment]
>     static void AssignRefToValue<T>(S<T> s, ref T tRef) { s.F = ref tRef; }

Consider adding `// 2`, etc.

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:6057 in dd92bf2. [](commit_id = dd92bf25b44443d865bab276c1010e963bd69844, deletion_comment = False)

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 45]
```diff
@@ -8615,9 +8459,10 @@ public void BreakingChange_ReturnOutByRef()
         }
 
         // Breaking change in C#11: Instance method on ref struct instance may capture unscoped ref or in arguments.
+        // No longer a breaking change
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:8462]: Consider deleting comments, to avoid confusion.

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs (hunk 45 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:8462]:
```
// increment this counter when editing the comment: 3
```

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs (hunk 44 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:5971]: Sigh no ... I forgot the tests don't fail when you update comments. Let me fix.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs (hunk 43 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs]: STE of `S<T> s` is *calling method* and RSTE of `tRef` is *return only*. so it makes sense that you can't escape `tRef` into `s.F`.

fwiw, I don't think there's any reason to do this assignment in real world code.

**Review by RikkiGibson — APPROVED** [review]

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 46]
```diff
@@ -1854,93 +2026,135 @@ bool isRefEscape
...
-            bool isRefEscape,
-            bool checkingMethodArgumentsMustMatch,
+            bool isInvokedWithRef,
             bool ignoreArglistRefKinds,
-            ArrayBuilder<(ParameterSymbol? Parameter, BoundExpression Argument, bool IsRefEscape)> result)
+            ArrayBuilder<EscapeValue> escapeValues)
         {
-            if (!symbol.RequiresInstanceReceiver())
+            // This code is attempting to implement the following portion of the spec. Essentially if we're not 
+            // either invoking a method by ref or have a ref struct return then all of the ref arguments.
```
[the remark this answers is not in the document]
Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: yep, fixed.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RawInterpolationTests_Handler.cs [hunk 47]
```diff
@@ -11312,7 +11315,10 @@ static void Main()
 }";
 
         var comp = CreateCompilation(new[] { code, InterpolatedStringHandlerAttribute, InterpolatedStringHandlerArgumentAttribute }, targetFramework: TargetFramework.NetCoreApp);
-        comp.VerifyDiagnostics();
+        comp.VerifyDiagnostics(
+            // (5,104): error CS8352: Cannot use variable 'out CustomHandler' in this context because it may expose referenced variables outside of their declaration scope
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RawInterpolationTests_Handler.cs:11319]: would this scenario work if `[UnscopedRef]` were applied to the method?

File: src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs [hunk 48]
```diff
@@ -13829,6 +13832,7 @@ public static void M(ref S1 s1)
                 // (15,23): error CS8352: Cannot use variable 's2' in this context because it may expose referenced variables outside of their declaration scope
                 //         M2(ref s1, $"{s2}");
                 Diagnostic(ErrorCode.ERR_EscapeVariable, "s2").WithArguments("s2").WithLocation(15, 23)
+
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs:13835]: nit: unnecessary blank line

File: src/Compilers/CSharp/Test/Semantic/Semantics/RawInterpolationTests_Handler.cs (hunk 47 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RawInterpolationTests_Handler.cs:11319]: No. The `[UnscopedRef]` would only apply to the `ref` portion of `this`. That doesn't come into play here though as the violation is the following: 

```csharp
s.Handler = this;
```

In this case `s` has a STE of _containing method_ and `this` has STE of `return only` as we model `this` as an `out`. 

Also note that we specifically disallow `[UnscopedRef]` on a `struct` constructor because it would create some really awkward interactions. At that point the STE and RSTE would be equivalent and the ctor could capture refs to itself. So cyclic self assignment in a ctor. I think we could now model that correctly but have it disallowed because it creates really awkward scenarios and I can't see a scenario in which it would be justified. If one was provided I'd be interested in allowing but it won't help this particular issue.

File: src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs (hunk 48 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Test/Semantic/Semantics/InterpolationTests.cs]: And the correctness test decided to escalate your nit to a blocking error 😦

File: src/Compilers/CSharp/Test/Semantic/Semantics/RawInterpolationTests_Handler.cs (hunk 47 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RawInterpolationTests_Handler.cs:11319]: Ah, of course. STE of this is not customizable and neither is STE of a `scoped ref` parameter. Thanks!

Though I guess if it were possible to say `ref scoped S`, you *would* be able to value-assign `this` to it. I wonder if that fact is related to why `ref scoped` was cut? I wasn't following as closely when that happened.

Comment (jaredpar) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RawInterpolationTests_Handler.cs:11319]: > I wonder if that fact is related to why ref scoped was cut? I wasn't following as closely when that happened.

The initial design only had essentially two scopes: _calling method_ and _containing method_. A parameter which was `ref scoped` had it's STS set to _containing method_. That decision though was wrong and it allowed for easy exploitation as follows: 

```csharp
void M(ref scoped Span<int> parameter)
{
  Span<int> local = stackalloc int[42];
  parameter = local; // uh oh 
}
```

This works because the STS of both values was _containing method_ so the assignment just falls out. At the time we realized the mistake here we still were also looking at other unintended design issues we'd created and cut this on a focus of 

> Get back to the original intent of just allowing `ref` fields in current use with minimal additions to language 

Now that we've gotten comfortable representing multiple scopes in the design it is possible to model `ref scoped`. For example it could be done effectively as: 

```csharp
Span<int> M(Span<int> p1, ref scoped Span<int> p2, scoped Span<int> p3)
// Becomes
'a Span<int> M('a Span<inT>, 'b ref 'c Span<int> p2, 'd Span<int> p3) 
  lifetime 'a >= 'b
  lifetime 'c >= 'd
```

The relationship between `'d` and `'c` means that you can assign these values to `scoped` locals but not the other way around. There is very deliberately no relationship because that requires thinking through a bit more. 

This also introduces the other problem that we have to deal with: variance. Essentially we have to make sure that in the above design `'b ref 'c Span<int>` cannot be assigned to `'b ref 'd Span<int>` even though `'c Span<int>` can be assigned to `'d Span<int>` as that just recreates the original problem.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RawInterpolationTests_Handler.cs:11319]: right..with a 2-scope solution, it's sort of unsafe by construction. The caller is essentially saying to the callee, "somehow, I am passing you references to your own local variables".

**Comment by jaredpar** [comment]
Unix failure is known Helix issue with Unix queue. Merging
