### PR TITLE
recursive-patterns(17) Improvements when switching on a tuple

### LINKED ISSUE #20641: Pattern matching IL much larger than non-pattern matching equivalent
**Version Used**:
2.3.0.61814 (b7f611db)

**Steps to Reproduce**:
Compile the following program:
```C#
using System.Collections;
using System.Collections.Generic;

class Program
{
    static void Main() { }

    internal static bool TryGetCount1<T>(IEnumerable<T> source, out int count)
    {
        ICollection nonGeneric = source as ICollection;
        if (nonGeneric != null)
        {
            count = nonGeneric.Count;
            return true;
        }

        ICollection<T> generic = source as ICollection<T>;
        if (generic != null)
        {
            count = generic.Count;
            return true;
        }

        count = -1;
        return false;
    }

    internal static bool TryGetCount2<T>(IEnumerable<T> source, out int count)
    {
        switch (source)
        {
            case ICollection nonGeneric:
                count = nonGeneric.Count;
                return true;

            case ICollection<T> generic:
                count = generic.Count;
                return true;

            default:
                count = -1;
                return false;
        }
    }
}
```

**Expected Behavior**:
The IL for TryGetCount1 and TryGetCount2 would be close to identical.

**Actual Behavior**:
The IL for TryGetCount2 is ~28% larger than that for TryGetCount1.
```
.method assembly hidebysig static bool  TryGetCount1<T>(class [mscorlib]System.Collections.Generic.IEnumerable`1<!!T> source,
                                                        [out] int32& count) cil managed
{
  // Code size       45 (0x2d)
  .maxstack  2
  .locals init ([0] class [mscorlib]System.Collections.ICollection nonGeneric,
           [1] class [mscorlib]System.Collections.Generic.ICollection`1<!!T> generic)
  IL_0000:  ldarg.0
  IL_0001:  isinst     [mscorlib]System.Collections.ICollection
  IL_0006:  stloc.0
  IL_0007:  ldloc.0
  IL_0008:  brfalse.s  IL_0014
  IL_000a:  ldarg.1
  IL_000b:  ldloc.0
  IL_000c:  callvirt   instance int32 [mscorlib]System.Collections.ICollection::get_Count()
  IL_0011:  stind.i4
  IL_0012:  ldc.i4.1
  IL_0013:  ret
  IL_0014:  ldarg.0
  IL_0015:  isinst     class [mscorlib]System.Collections.Generic.ICollection`1<!!T>
  IL_001a:  stloc.1
  IL_001b:  ldloc.1
  IL_001c:  brfalse.s  IL_0028
  IL_001e:  ldarg.1
  IL_001f:  ldloc.1
  IL_0020:  callvirt   instance int32 class [mscorlib]System.Collections.Generic.ICollection`1<!!T>::get_Count()
  IL_0025:  stind.i4
  IL_0026:  ldc.i4.1
  IL_0027:  ret
  IL_0028:  ldarg.1
  IL_0029:  ldc.i4.m1
  IL_002a:  stind.i4
  IL_002b:  ldc.i4.0
  IL_002c:  ret
} // end of method Program::TryGetCount1
```
and
```
.method assembly hidebysig static bool  TryGetCount2<T>(class [mscorlib]System.Collections.Generic.IEnumerable`1<!!T> source,
                                                        [out] int32& count) cil managed
{
  // Code size       58 (0x3a)
  .maxstack  2
  .locals init ([0] class [mscorlib]System.Collections.Generic.IEnumerable`1<!!T> V_0,
           [1] class [mscorlib]System.Collections.ICollection V_1,
           [2] class [mscorlib]System.Collections.Generic.ICollection`1<!!T> V_2,
           [3] class [mscorlib]System.Collections.ICollection nonGeneric,
           [4] class [mscorlib]System.Collections.Generic.ICollection`1<!!T> generic)
  IL_0000:  ldarg.0
  IL_0001:  stloc.0
  IL_0002:  ldloc.0
  IL_0003:  brfalse.s  IL_0035
  IL_0005:  ldloc.0
  IL_0006:  isinst     [mscorlib]System.Collections.ICollection
  IL_000b:  dup
  IL_000c:  stloc.1
  IL_000d:  brtrue.s   IL_001b
  IL_000f:  ldloc.0
  IL_0010:  isinst     class [mscorlib]System.Collections.Generic.ICollection`1<!!T>
  IL_0015:  dup
  IL_0016:  stloc.2
  IL_0017:  brfalse.s  IL_0035
  IL_0019:  br.s       IL_0027
  IL_001b:  ldloc.1
  IL_001c:  stloc.3
  IL_001d:  ldarg.1
  IL_001e:  ldloc.3
  IL_001f:  callvirt   instance int32 [mscorlib]System.Collections.ICollection::get_Count()
  IL_0024:  stind.i4
  IL_0025:  ldc.i4.1
  IL_0026:  ret
  IL_0027:  ldloc.2
  IL_0028:  stloc.s    generic
  IL_002a:  ldarg.1
  IL_002b:  ldloc.s    generic
  IL_002d:  callvirt   instance int32 class [mscorlib]System.Collections.Generic.ICollection`1<!!T>::get_Count()
  IL_0032:  stind.i4
  IL_0033:  ldc.i4.1
  IL_0034:  ret
  IL_0035:  ldarg.1
  IL_0036:  ldc.i4.m1
  IL_0037:  stind.i4
  IL_0038:  ldc.i4.0
  IL_0039:  ret
} // end of method Program::TryGetCount2
```

### LINKED ISSUE #25934: Compiler ignores tuple element names in positional patterns.
The following code compiles without error. It should be an error, because c and d are not defined as elements of the input tuple:

``` c#
        switch ((a: 1, b: 2))
        {
            case (c: 2, d: 3):
                break;
        }
```

### PR DESCRIPTION
**Pull request by gafter**
This PR is a set of changes intended to improve things for pattern-matching operations on tuples:

- https://github.com/dotnet/roslyn/commit/2f117a4defc3328fa040f194a257c646bbcf8250 Adds a code quality test for switching on a tuple literal. The test exposed some parsing precedence issues for the switch expression which are fixed here. The `=>` following the when clause was being consumed as part of the when expression (as a lambda). Changed the precedence of the when expression to a coalescing expression to forbid a lambda there.
- https://github.com/dotnet/roslyn/commit/ab7a2446cc81bec755fe347d998536690fb8c29f Fixes a bug in the semantic model for switch expressions.
- https://github.com/dotnet/roslyn/commit/cec28aa3bb430ea71cca348fb13129d5faf3ab54 Refactoring some code in preparation for subsequent changes.
- https://github.com/dotnet/roslyn/commit/c15d849a43794a36da5f8af1b4e20bccb05e6896 Introduce BoundPatternBinding rather than using a tuple. Also move the implementation of the is-pattern operator to its own source file.
- https://github.com/dotnet/roslyn/commit/c0953a4ea0387dcc12a7d035fc124858ff919dc9 Refactor the decision dag rewriter so we can reuse it for handling tuples in a subsequent iteration.
- https://github.com/dotnet/roslyn/commit/4fbf77ebb2dabf1e686d9384fd68c21af3c0fa1b Add instrumentation for the switch statement's when clause. This was dropped in a previous PR when we dropped the old lowering code.
- https://github.com/dotnet/roslyn/commit/662deba9748ff71469cb2d960a4a9c4a7a4ed04e Fix the diagnostic argument for "wrong number of subpatterns". This fixes a crash during LDM demo.
- https://github.com/dotnet/roslyn/commit/8b8bc93abc3759cdea5cbe051341701a0e6fe895 Optimizes switch on a tuple literal by saving the elements of the tuple literal and not constructing a tuple object. Fixes #20641
- https://github.com/dotnet/roslyn/commit/170b511b6a147efa1da16dcd4dbfdbb993149914 Permit switching on a tuple literal without redundant parentheses. Fixes dotnet/csharplang#1395 . The syntax change is currently under compat council review.
- https://github.com/dotnet/roslyn/commit/95a9bd8dabdd9580f84ce83eaecde915c3321208 Bind and check the optional "named argument" style names in positional (tuple) patterns. Fixes #25934

@agocke @cston Please review these pattern-matching changes. You might find it easier to do iteration by iteration. I will be happy to do a co-review by Skype or over-the-shoulder if it is easier for you.
@dotnet/roslyn-compiler Additional review most welcome
@dotnet/roslyn-ide Can you suggest additional IDE tests for the changes in https://github.com/dotnet/roslyn/commit/170b511b6a147efa1da16dcd4dbfdbb993149914 ?

Question for reviewers: would you have preferred that I submit a separate PR for each of these changes?

### CODE REVIEW

**Comment by gafter** [comment]
test windows_debug_unit32_prtest please

**Comment by gafter** [comment]
(Failure link https://ci.dot.net/job/dotnet_roslyn/job/features_recursive-patterns/job/ubuntu_16_mono_debug_prtest/82/ )

File: src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs [hunk 1]
```diff
@@ -1125,6 +1125,198 @@ .maxstack  2
...
+    {
+        var door = new Door();
+        door.Act(Door.Action.Close);
+        door.Act(Door.Action.Lock);
+        door.Act(Door.Action.Lock, true);
+        door.Act(Door.Action.Open);
+        door.Act(Door.Action.Unlock);
+        door.Act(Door.Action.Unlock, true);
+        door.Act(Door.Action.Open);
+    }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs]: >} [](start = 4, length = 1)

Consider executing with `ChangeState1` as well.

File: src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs [hunk 2]
```diff
@@ -250,6 +250,10 @@ private static Binder GetEnclosingBinderInternalWithinRoot(SyntaxNode node, int
                 {
                     binder = rootBinder.GetBinder(current);
                 }
+                else if (kind == SyntaxKind.SwitchExpression)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs]: >else if (kind == SyntaxKind.SwitchExpression) [](start = 16, length = 45)

Is there an associated test?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs [hunk 3]
```diff
@@ -103,13 +89,22 @@ void notePredecessor(BoundDecisionDagNode successor)
...
+                    {
+                        GetDagNodeLabel(successor);
+                    }
+                }
             }
 
             protected new void Free()
             {
+                _dagNodeLabels.Free();
+                _switchArms.Free();
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs]: >_switchArms.Free() [](start = 16, length = 18)

Are we freeing the `ArrayBuilder<>` in `_switchArms.Values`?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs [hunk 4]
```diff
@@ -122,11 +117,115 @@ protected virtual LabelSymbol GetDagNodeLabel(BoundDecisionDagNode dag)
...
+                BoundExpression loweredSwitchGoverningExpression,
+                ArrayBuilder<BoundStatement> result)
+            {
+                // Note that a when-clause can contain an assignment to a
+                // pattern variable declared in a different when-clause (e.g. in the same section, or
+                // in a different section via the use of a local function), so we need to analyze all
+                // of the when clauses to see if they are all simple enough to conclude that they do
+                // not mutate pattern variables.
+                var mightAssignWalker = new WhenClauseMightAssignWalker(isSwitchStatement: this._isSwitchStatement);
+                bool canShareTemps =
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs]: >bool canShareTemps [](start = 16, length = 18)

Consider merging `OfType` and `Any` to avoid `IEnumerable` allocations:
```
!decisionDag.TopologicallySortedNodes
.Any(n => n as BoundWhenDecisionDagNode w &&
    mightAssignWalker.MightAssignSomething(w.WhenExpression));
```

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs [hunk 5]
```diff
@@ -18,35 +19,34 @@ internal sealed partial class LocalRewriter
...
-                this._inputTemp = new BoundDagTemp(loweredInput.Syntax, loweredInput.Type, source: null, index: 0);
+                this._tempAllocator = new DagTempAllocator(_factory, node);
             }
 
             public void Free()
             {
                 _tempAllocator.Free();
             }
 
+            protected BoundDagTemp InputTemp(BoundExpression expr) => new BoundDagTemp(expr.Syntax, expr.Type, null, 0);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: >protected [](start = 12, length = 9)

`static`

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs [hunk 6]
```diff
@@ -301,6 +302,65 @@ protected void ShareTemps(ImmutableArray<BoundDecisionDagNode> sortedNodes)
...
+                }
+
+                return decisionDag;
+
+                bool usesOriginalInput(BoundDecisionDagNode node)
+                {
+                    switch (node)
+                    {
+                        case BoundWhenDecisionDagNode n:
+                            return (n.Bindings.Any(b => b.dagTemp.IsOriginalInput));
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: >( [](start = 35, length = 1)

Minor point: unnecessary parentheses.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs [hunk 7]
```diff
@@ -301,6 +302,65 @@ protected void ShareTemps(ImmutableArray<BoundDecisionDagNode> sortedNodes)
...
+                        case BoundTestDecisionDagNode t:
+                            return t.Test.Input.IsOriginalInput;
+                        case BoundEvaluationDecisionDagNode e:
+                            switch (e.Evaluation)
+                            {
+                                case BoundDagFieldEvaluation f:
+                                    // Uses only a tuple element, not the whole input
+                                    return f.Input.IsOriginalInput && !f.Field.IsTupleElement();
+                                default:
+                                    return e.Evaluation.Input.IsOriginalInput;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: >e.Evaluation.Input.IsOriginalInput [](start = 43, length = 34)

Minor point: Consider checking this common expression outside of the `switch (e.Evaluation) { ... }`.

File: src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/CodeGen/PatternTests.cs]: Done already in a later iteration.

---
In reply to: [179658250](https://github.com/dotnet/roslyn/pull/25963#discussion_r179658250) [](ancestors = 179658250)

File: src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs (hunk 2 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs]: No, there is an open issue for SemanticModel implementation and tests. This is present to unblock an exception in the IDE when hand-testing.

---
In reply to: [179658390](https://github.com/dotnet/roslyn/pull/25963#discussion_r179658390) [](ancestors = 179658390)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs (hunk 7 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: The value being switched on does not have an `Input` field, and `e` is not in scope before the switch.

---
In reply to: [179661343](https://github.com/dotnet/roslyn/pull/25963#discussion_r179661343) [](ancestors = 179661343)

Comment (cston) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: I simply meant check `e.Evaluation.Input.IsOriginalInput` before the nested `switch`, but it was a minor point.

Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: I understand now. I think this is more clear and concise (I would have to add a new if statement to return false when)

---
In reply to: [179859796](https://github.com/dotnet/roslyn/pull/25963#discussion_r179859796) [](ancestors = 179859796)

**Comment by gafter** [comment]
Added a new iteration to address comments so far.

File: src/Compilers/CSharp/Portable/CSharpResources.resx [hunk 8]
```diff
@@ -5375,4 +5375,13 @@ To remove the warning, you can use /reference instead (set the Embed Interop Typ
   <data name="IDS_FeatureIndexingMovableFixedBuffers" xml:space="preserve">
     <value>indexing movable fixed buffers</value>
   </data>
+  <data name="ERR_SwitchGoverningExpressionRequiresParens" xml:space="preserve">
+    <value>Parentheses are required around the switch governing expression.</value>
+  </data>
+  <data name="ERR_TupleElementNameMismatch" xml:space="preserve">
+    <value>The name '{0}' does not identify tuple element {1}.</value>
+  </data>
+  <data name="ERR_DeconstructParameterNameMistmatch" xml:space="preserve">
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/CSharpResources.resx]: >ERR_DeconstructParameterNameMistmatch [](start = 14, length = 37)

Typo: mismatch

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 9]
```diff
@@ -516,6 +534,29 @@ private BoundPattern BindDeconstructionPattern(DeconstructionPatternSyntax node,
                 deconstruction: patterns.ToImmutableAndFree(), propertiesOpt: propertiesOpt, variable: variableSymbol, variableAccess: variableAccess, hasErrors: hasErrors);
         }
 
+        /// <summary>
+        /// Check that the given name designates a tuple element at the given index, and return that element.
+        /// </summary>
+        private FieldSymbol CheckIsTupleElement(SyntaxNode node, NamedTypeSymbol tupleType, string name, int tupleIndex, DiagnosticBag diagnostics)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: Are you sure you need to return the `FieldSymbol`?
If not, you could simply check that `tupleType.TupleElementNames[tupleIndex]` matches `name`.

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 10]
```diff
@@ -469,35 +469,53 @@ private BoundPattern BindDeconstructionPattern(DeconstructionPatternSyntax node,
...
+                    }
+                    BoundPattern boundSubpattern = BindPattern(subPattern.Pattern, elementType, isError, diagnostics);
                     patterns.Add(boundSubpattern);
                 }
             }
             else
             {
                 // It is not a tuple type. Seek an appropriate Deconstruct method.
                 var inputPlaceholder = new BoundImplicitReceiver(node, declType); // A fake receiver expression to permit us to reuse binding logic
+                // PROTOTYPE(patterns2): include element names node.SubPatterns[i].NameColon?.Name in the AnalyzedArguments
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: In regular deconstructions (assignment/declaration/foreach), the names on the LHS do not contribute to selecting a `Deconstruct` overload. It would be rather strange that names would matter in one deconstruction context, but not others. Probably needs some LDM discussion.

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 11]
```diff
@@ -469,35 +469,53 @@ private BoundPattern BindDeconstructionPattern(DeconstructionPatternSyntax node,
...
-                    // PROTOTYPE(patterns2): Check that node.SubPatterns[i].NameColon?.Name corresponds to parameter i of the method. Or,
-                    // better yet, include those names in the AnalyzedArguments used in MakeDeconstructInvocationExpression so they are
-                    // used to disambiguate.
-                    BoundPattern boundSubpattern = BindPattern(node.SubPatterns[i].Pattern, elementType, isError, diagnostics);
+                    if (subPattern.NameColon != null && !isError)
+                    {
+                        // Check that the given name is the same as the corresponding parameter of the method.
+                        string name = subPattern.NameColon.Name.Identifier.ValueText;
+                        int parameterIndex = i + skippedExtensionParameters;
+                        string parameterName = deconstructMethod.Parameters[parameterIndex].Name;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: Can we reach here with a `null` `deconstructMethod`?

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 12]
```diff
@@ -469,35 +469,53 @@ private BoundPattern BindDeconstructionPattern(DeconstructionPatternSyntax node,
...
                 BoundExpression deconstruct = MakeDeconstructInvocationExpression(
                     node.SubPatterns.Count, inputPlaceholder, node, diagnostics, outPlaceholders: out ImmutableArray<BoundDeconstructValuePlaceholder> outPlaceholders);
                 deconstructMethod = deconstruct.ExpressionSymbol as MethodSymbol;
-                // PROTOTYPE(patterns2): Set and check the deconstructMethod
-
+                int skippedExtensionParameters = deconstructMethod?.IsExtensionMethod == true ? 1 : 0;
                 for (int i = 0; i < node.SubPatterns.Count; i++)
                 {
+                    var subPattern = node.SubPatterns[i];
                     bool isError = outPlaceholders.IsDefaultOrEmpty || i >= outPlaceholders.Length;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: I think `MakeDeconstructInvocationExpression` will either return `default` for `outPlaceholders` or exactly the requested number.
In deconstruction binding, we check `HasAnyErrors` on the result from `MakeDeconstructInvocationExpression` instead.

File: src/Compilers/CSharp/Portable/Syntax/Syntax.xml [hunk 13]
```diff
@@ -2380,11 +2380,11 @@
         </summary>
       </PropertyComment>
     </Field>
-    <Field Name="OpenParenToken" Type="SyntaxToken">
+    <Field Name="OpenParenToken" Type="SyntaxToken" Optional="true">
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Syntax/Syntax.xml]: Do we want to document this as a breaking change?

File: src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs [hunk 14]
```diff
@@ -607,5 +607,62 @@ private bool IsPossibleSubpatternElement()
                 p => p.CurrentToken.Kind == closeKind || p.CurrentToken.Kind == SyntaxKind.SemicolonToken || p.IsTerminator(),
                 expected);
         }
+
+        private ExpressionSyntax ParseSwitchExpression(ExpressionSyntax leftOperand)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs]: Were those two methods just moved, or also modified?

File: src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs [hunk 15]
```diff
@@ -483,9 +483,9 @@ bool looksLikeCast()
             return null;
         }
 
-        private PatternSyntax ParsePattern(Precedence precedence)
+        private PatternSyntax ParsePattern(Precedence precedence, bool whenIsKeyword = false)
         {
-            var node = ParseExpressionOrPattern(forCase: false, precedence: precedence);
+            var node = ParseExpressionOrPattern(whenIsKeyword: whenIsKeyword, precedence: precedence);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs]: Probably don't need the named arguments, since names are clear and types are distincts.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 16]
```diff
@@ -7992,15 +8017,15 @@ private SwitchSectionSyntax ParseSwitchSection()
                         }
                         else
                         {
-                            var node = CheckRecursivePatternFeature(ParseExpressionOrPattern(forCase: true, precedence: Precedence.Ternary));
+                            var node = CheckRecursivePatternFeature(ParseExpressionOrPattern(whenIsKeyword: true, precedence: Precedence.Ternary));
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: Nit: could remove `precedence:` named argument

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs [hunk 17]
```diff
@@ -7936,9 +7936,34 @@ private SwitchStatementSyntax ParseSwitchStatement()
...
+                // PROTOTYPE(patterns2): Do we need to preserve any diagnostics that were attached directly to parenExpression?
+                Debug.Assert(parenExpression.GetDiagnostics().Length == 0);
+            }
+            else if (expression.Kind == SyntaxKind.TupleExpression)
+            {
+                // As a special case, when a tuple literal is the governing expression of
+                // a switch statement we permit the switch statement's own parentheses to be omitted.
+                // LDM 2018-04-04.
+                openParen = closeParen = default;
+            }
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: Can you add an example of the newly supported syntax to the "all syntax" test? I don't remember the exact name for that resource, but I can dig it up if needed.

File: src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs (hunk 14 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser_Patterns.cs]: Just moved.

File: src/Compilers/CSharp/Portable/Syntax/Syntax.xml (hunk 13 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Syntax/Syntax.xml]: Yes

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs (hunk 10 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: It certainly does need discussion before it is changed.

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs (hunk 9 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: Cannot check the name, as you are allowed to use any name for that position's element (e.g. `Item2` instead of `LastName`)

File: src/Compilers/CSharp/Portable/Lowering/Instrumentation/DebugInfoInjector.cs [hunk 18]
```diff
@@ -352,7 +352,7 @@ public override BoundStatement InstrumentPatternSwitchStatement(BoundPatternSwit
             SwitchStatementSyntax switchSyntax = (SwitchStatementSyntax)original.Syntax;
             TextSpan switchSequencePointSpan = TextSpan.FromBounds(
                 switchSyntax.SwitchKeyword.SpanStart,
-                switchSyntax.CloseParenToken.Span.End);
+                (switchSyntax.CloseParenToken != default) ? switchSyntax.CloseParenToken.Span.End : switchSyntax.Expression.Span.End);
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Lowering/Instrumentation/DebugInfoInjector.cs]: >switchSyntax.CloseParenToken != default [](start = 17, length = 39)

`.IsMissing`?

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs (hunk 12 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: `HasAnyErrors` is too blunt a tool, as it then suppresses processing for *any* kind of nested error. I prefer this.

---
In reply to: [179892024](https://github.com/dotnet/roslyn/pull/25963#discussion_r179892024) [](ancestors = 179892024)

File: src/Compilers/CSharp/Portable/Parser/LanguageParser.cs (hunk 17 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Parser/LanguageParser.cs]: Since the new syntax forms are not tied to any language version yet, not yet.

---
In reply to: [179894724](https://github.com/dotnet/roslyn/pull/25963#discussion_r179894724) [](ancestors = 179894724)

File: src/Compilers/CSharp/Portable/Lowering/Instrumentation/DebugInfoInjector.cs (hunk 18 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/Instrumentation/DebugInfoInjector.cs]: That would return the wrong (`false`) result. A "missing" token is one that was inserted by the parser. There is no token here at all.

---
In reply to: [179895304](https://github.com/dotnet/roslyn/pull/25963#discussion_r179895304) [](ancestors = 179895304)

**Comment by gafter** [comment]
I have added a new delta adding a breaking change note and fixing a typo in an error code name.

File: src/Compilers/CSharp/Portable/BoundTree/BoundDecisionDag.cs [hunk 19]
```diff
@@ -98,88 +93,104 @@ public ImmutableArray<BoundDecisionDagNode> TopologicallySortedNodes
...
             return this.Update(newRoot);
+        }
+
+        /// <summary>
+        /// A trivial node replacement function for use with <see cref="Rewrite(Func{BoundDecisionDagNode, Func{BoundDecisionDagNode, BoundDecisionDagNode}, BoundDecisionDagNode})"/>.
+        /// </summary>
+        /// <param name="dag"></param>
+        /// <param name="replacement"></param>
+        /// <returns></returns>
+        public BoundDecisionDagNode TrivialReplacement(BoundDecisionDagNode dag, Func<BoundDecisionDagNode, BoundDecisionDagNode> replacement)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/BoundTree/BoundDecisionDag.cs]: >public [](start = 8, length = 6)

`static`?

File: src/Compilers/CSharp/Portable/BoundTree/BoundDecisionDag.cs [hunk 20]
```diff
@@ -98,88 +93,104 @@ public ImmutableArray<BoundDecisionDagNode> TopologicallySortedNodes
...
             replacement.Free();
             return this.Update(newRoot);
+        }
+
+        /// <summary>
+        /// A trivial node replacement function for use with <see cref="Rewrite(Func{BoundDecisionDagNode, Func{BoundDecisionDagNode, BoundDecisionDagNode}, BoundDecisionDagNode})"/>.
+        /// </summary>
+        /// <param name="dag"></param>
+        /// <param name="replacement"></param>
+        /// <returns></returns>
```
Comment (cston) [inline src/Compilers/CSharp/Portable/BoundTree/BoundDecisionDag.cs]: Consider removing if not documented.

**Comment by cston** [comment]
>                 if (x.Input != y.Input || x.Kind != y.Kind)

Consider comparing `Kind` before `Input` since the `Kind` comparison seems less expensive.

---
Refers to: src/Compilers/CSharp/Portable/Binder/DecisionDagBuilder.cs:1204 in 8b8bc93. [](commit_id = 8b8bc93abc3759cdea5cbe051341701a0e6fe895, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs [hunk 21]
```diff
@@ -122,11 +117,158 @@ protected virtual LabelSymbol GetDagNodeLabel(BoundDecisionDagNode dag)
...
+                    {
+                        return false;
+                    }
+
+                    this._mightAssignSomething = false;
+                    this.Visit(expr);
+                    return this._mightAssignSomething;
+                }
+
+                public override BoundNode VisitReturnStatement(BoundReturnStatement node)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs]: >VisitReturnStatement [](start = 42, length = 20)

Are there tests for the additional visit methods in this iteration?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs [hunk 22]
```diff
@@ -55,12 +55,30 @@ public void Free()
                     _map.Free();
                 }
 
+#if DEBUG
+                public string Dump()
+                {
+                    var poolElemenet = PooledStringBuilder.GetInstance();
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: >Elemenet [](start = 28, length = 8)

Typo

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs [hunk 23]
```diff
@@ -268,327 +343,172 @@ protected BoundExpression LowerTest(BoundDagTest test)
...
-                            foreach ((BoundExpression left, BoundDagTemp dagTemp) in whenNode.Bindings)
+                    switch (node)
+                    {
+                        case BoundEvaluationDecisionDagNode evalNode:
+                            if (evalNode.Evaluation is BoundDagFieldEvaluation eval &&
+                                eval.Input.IsOriginalInput &&
+                                eval.Field is var field &&
+                                field.IsTupleField &&
+                                field.CorrespondingTupleField != null &&
+                                field.TupleElementIndex is int i)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: Can this be simplified, by removing `field.IsTupleField` or `field.CorrespondingTupleField != null`?

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 24]
```diff
@@ -114,24 +114,24 @@ private BoundPattern BindDiscardPattern(DiscardPatternSyntax node, TypeSymbol in
                 hasErrors = true;
             }
 
-            return BindConstantPattern(node, innerExpression, inputType, node.Expression, hasErrors, diagnostics, out _);
+            return BindConstantPattern(node, innerExpression, operandType, node.Expression, hasErrors, diagnostics, out _);
         }
 
         internal BoundConstantPattern BindConstantPattern(
             CSharpSyntaxNode node,
-            TypeSymbol inputType,
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: >private [](start = 8, length = 7)

`static`?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests2.cs [hunk 25]
```diff
@@ -1220,38 +1220,286 @@ void Test5()
...
-    public static void Main()
+    static void Main()
+    {
+        switch (a: 1, b: 2)
+        {
+            case (c: 2, d: 3): // error: c and d not defined
+                break;
+        }
+    }
+}
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests2.cs]: >element 0 [](start = 78, length = 9)

Are we referring to tuple fields as 0-based elements elsewhere? If not, should we refer to `tuple Item1` here instead?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests2.cs [hunk 26]
```diff
@@ -1220,38 +1220,286 @@ void Test5()
...
     {
-        switch ((o, 0))
+        switch (a: 1, b: 2)
         {
-            case (Fox fox, _):
-                System.Console.Write(""Fox "");
+            case (a: 2, Item2: 3):
+                System.Console.WriteLine(666);
                 break;
-            case (Cat cat, _):
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests2.cs]: >} [](start = 8, length = 1)

Consider testing: `case (Item2: 1, 2):`

**Comment by cston** [comment]
>     <Field Name="IterationErrorExpressionOpt" Type="BoundExpression" Null="allow"/>

Is this field used?

---
Refers to: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml:1006 in 76b4fcb. [](commit_id = 76b4fcb9061a4add2927f8a3fc25555317cf53de, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs [hunk 27]
```diff
@@ -145,6 +145,18 @@ public bool MightAssignSomething(BoundExpression expr)
                     return this._mightAssignSomething;
                 }
 
+                public override BoundNode VisitReturnStatement(BoundReturnStatement node)
+                {
+                    if (node.RefKind != RefKind.None)
+                    {
+                        // might be taking a ref to a variable in a lambda that the caller assigns.
+                        this._mightAssignSomething = true;
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs]: I don't see how this can be hit without either an error about ref returning a variable outside its lifetime, or an error on the call to such a method with a ref parameter and one of the variables we are tracking.

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 28]
```diff
@@ -516,6 +534,29 @@ private BoundPattern BindDeconstructionPattern(DeconstructionPatternSyntax node,
...
+            foreach (var symbol in tupleType.GetMembers(name))
+            {
+                if (symbol is FieldSymbol field && field.IsTupleElement())
+                {
+                    foundElement = field;
+                    break;
+                }
+            }
+
+            if (foundElement == null || foundElement.TupleElementIndex != tupleIndex)
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: `foundElement is null`

File: src/Compilers/CSharp/Portable/BoundTree/BoundDecisionDag.cs (hunk 19 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/BoundTree/BoundDecisionDag.cs]: It is intended to be used as a fallback by outside callers of `Rewrite` as a fallback. There is one caller in this iteration, but an outside caller in a later iteration where we rewrite for tuple literal inputs to a switch.

---
In reply to: [180570098](https://github.com/dotnet/roslyn/pull/25963#discussion_r180570098) [](ancestors = 180570098)

File: src/Compilers/CSharp/Portable/BoundTree/BoundDecisionDag.cs [hunk 29]
```diff
@@ -98,88 +93,104 @@ public ImmutableArray<BoundDecisionDagNode> TopologicallySortedNodes
...
+                    }
 
-            // Is the decision's result known because the input is a constant?
-            bool? knownResult(BoundDagTest choice)
-            {
-                if (choice.Input.Source != null)
-                {
-                    // This is a test of something other than the main input; result unknown
-                    return null;
+                    return TrivialReplacement(dag, replacement);
```
[the remark this answers is not in the document]
Comment (gafter) [reply src/Compilers/CSharp/Portable/BoundTree/BoundDecisionDag.cs]: Yes, in the simplification call to Rewrite when we change the decision dag to avoid creating a tuple when switching on a tuple literal in a later iteration of this PR.

---
In reply to: [180571876](https://github.com/dotnet/roslyn/pull/25963#discussion_r180571876) [](ancestors = 180571876)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs (hunk 21 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs]: Not each one individually, no. I will add a test comparing when a when clause might assign something vs not.

---
In reply to: [180574667](https://github.com/dotnet/roslyn/pull/25963#discussion_r180574667) [](ancestors = 180574667)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs (hunk 27 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs]: Agreed; will remove the return statement visitor.

---
In reply to: [180583839](https://github.com/dotnet/roslyn/pull/25963#discussion_r180583839) [](ancestors = 180583839)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs [hunk 30]
```diff
@@ -122,11 +117,115 @@ protected virtual LabelSymbol GetDagNodeLabel(BoundDecisionDagNode dag)
...
+                    // assign the input expression to its temp.
+                    BoundExpression inputTemp = _tempAllocator.GetTemp(InputTemp(loweredSwitchGoverningExpression));
+                    Debug.Assert(inputTemp != loweredSwitchGoverningExpression);
+                    result.Add(_factory.Assignment(inputTemp, loweredSwitchGoverningExpression));
+                    return decisionDag;
+                }
+            }
+
             /// <summary>
             /// Lower the given nodes into _loweredDecisionDag.
```
[the remark this answers is not in the document]
Comment (gafter) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_BasePatternSwitchLocalRewriter.cs]: Adding the comment "Should only be called once per instance of this.". The caller cannot see `_switchArms` so the comment would not mean anything in the caller.

---
In reply to: [180577191](https://github.com/dotnet/roslyn/pull/25963#discussion_r180577191) [](ancestors = 180577191)

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs (hunk 24 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: I cannot tell what this comment refers to, but there are no methods near here that could be static.

---
In reply to: [180579394](https://github.com/dotnet/roslyn/pull/25963#discussion_r180579394) [](ancestors = 180579394)

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests2.cs (hunk 25 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests2.cs]: Yes!

---
In reply to: [180581813](https://github.com/dotnet/roslyn/pull/25963#discussion_r180581813) [](ancestors = 180581813)

**Comment by gafter** [comment]
>     <Field Name="IterationErrorExpressionOpt" Type="BoundExpression" Null="allow"/>

Yes, by the semantic model in error recovery.

---
In reply to: [380264456](https://github.com/dotnet/roslyn/pull/25963#issuecomment-380264456) [](ancestors = 380264456)

---
Refers to: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml:1006 in 76b4fcb. [](commit_id = 76b4fcb9061a4add2927f8a3fc25555317cf53de, deletion_comment = False)

**Comment by gafter** [comment]
@agocke @cston I have added a new iteration that responds to all of your comments. Please let me know if you see anything else you'd like changed.

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs (hunk 24 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: The comment referred to `CheckIsTupleElement`.

---
In reply to: [180602793](https://github.com/dotnet/roslyn/pull/25963#discussion_r180602793) [](ancestors = 180602793,180579394)
