### PR TITLE
If given a partially constructed type, call Construct() on its Constr…

### LINKED ISSUE #5126: InvalidOperationException from CSharpTypeInferenceService
Crash dump:

%internal_share%\public\tomat\Bugs\5126

Repro:

1. Open src\Scripting\Core\ScriptMetadataReferenceResolver.cs in Roslyn.sln solution in Repro.zip in the folder above.
2. Edit line 60 like so:

```C#
return PackageResolver.ResolveNuGetPackage(reference).SelectAsArray(p => 
```

```C#
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol.Construct(ImmutableArray`1 typeArguments)
   at Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol.Microsoft.CodeAnalysis.IMethodSymbol.Construct(ITypeSymbol[] arguments)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.Instantiate(IMethodSymbol method, IList`1 invocationTypes)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.<>c__DisplayClass20_0.<InferTypeInArgument>b__0(IMethodSymbol m)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeInArgument(Int32 index, IEnumerable`1 methods, ArgumentSyntax argumentOpt)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeInInvocationExpression(InvocationExpressionSyntax invocation, Int32 index, ArgumentSyntax argumentOpt)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeInArgument(ArgumentSyntax argument, Nullable`1 previousToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.<InferTypesWorker_DoNotCallDirectly>b__6_1(ArgumentSyntax argument)
   at Microsoft.CodeAnalysis.Shared.Extensions.ObjectExtensions.TypeSwitch[TBaseType,TDerivedType1,TDerivedType2,TDerivedType3,TDerivedType4,TDerivedType5,TDerivedType6,TDerivedType7,TDerivedType8,TDerivedType9,TDerivedType10,TDerivedType11,TDerivedType12,TDerivedType13,TDerivedType14,TDerivedType15,TDerivedType16,TDerivedType17,TDerivedType18,TDerivedType19,TDerivedType20,TDerivedType21,TDerivedType22,TDerivedType23,TDerivedType24,TDerivedType25,TDerivedType26,TDerivedType27,TDerivedType28,TDerivedType29,TDerivedType30,TDerivedType31,TDerivedType32,TDerivedType33,TDerivedType34,TDerivedType35,TDerivedType36,TDerivedType37,TDerivedType38,TResult](TBaseType obj, Func`2 matchFunc1, Func`2 matchFunc2, Func`2 matchFunc3, Func`2 matchFunc4, Func`2 matchFunc5, Func`2 matchFunc6, Func`2 matchFunc7, Func`2 matchFunc8, Func`2 matchFunc9, Func`2 matchFunc10, Func`2 matchFunc11, Func`2 matchFunc12, Func`2 matchFunc13, Func`2 matchFunc14, Func`2 matchFunc15, Func`2 matchFunc16, Func`2 matchFunc17, Func`2 matchFunc18, Func`2 matchFunc19, Func`2 matchFunc20, Func`2 matchFunc21, Func`2 matchFunc22, Func`2 matchFunc23, Func`2 matchFunc24, Func`2 matchFunc25, Func`2 matchFunc26, Func`2 matchFunc27, Func`2 matchFunc28, Func`2 matchFunc29, Func`2 matchFunc30, Func`2 matchFunc31, Func`2 matchFunc32, Func`2 matchFunc33, Func`2 matchFunc34, Func`2 matchFunc35, Func`2 matchFunc36, Func`2 matchFunc37, Func`2 matchFunc38, Func`2 defaultFunc)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypesWorker_DoNotCallDirectly(ExpressionSyntax expression)
   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService`1.AbstractTypeInferrer.InferTypes(TExpressionSyntax expression, Boolean filterUnusable)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeInLambdaExpression(ExpressionSyntax lambdaExpression)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeInSimpleLambdaExpression(SimpleLambdaExpressionSyntax lambdaExpression, Nullable`1 previousToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.<>c__DisplayClass8_0.<InferTypesWorker_DoNotCallDirectly>b__35(SimpleLambdaExpressionSyntax simpleLambdaExpression)
   at Microsoft.CodeAnalysis.Shared.Extensions.ObjectExtensions.TypeSwitch[TBaseType,TDerivedType1,TDerivedType2,TDerivedType3,TDerivedType4,TDerivedType5,TDerivedType6,TDerivedType7,TDerivedType8,TDerivedType9,TDerivedType10,TDerivedType11,TDerivedType12,TDerivedType13,TDerivedType14,TDerivedType15,TDerivedType16,TDerivedType17,TDerivedType18,TDerivedType19,TDerivedType20,TDerivedType21,TDerivedType22,TDerivedType23,TDerivedType24,TDerivedType25,TDerivedType26,TDerivedType27,TDerivedType28,TDerivedType29,TDerivedType30,TDerivedType31,TDerivedType32,TDerivedType33,TDerivedType34,TDerivedType35,TDerivedType36,TDerivedType37,TDerivedType38,TDerivedType39,TDerivedType40,TDerivedType41,TDerivedType42,TResult](TBaseType obj, Func`2 matchFunc1, Func`2 matchFunc2, Func`2 matchFunc3, Func`2 matchFunc4, Func`2 matchFunc5, Func`2 matchFunc6, Func`2 matchFunc7, Func`2 matchFunc8, Func`2 matchFunc9, Func`2 matchFunc10, Func`2 matchFunc11, Func`2 matchFunc12, Func`2 matchFunc13, Func`2 matchFunc14, Func`2 matchFunc15, Func`2 matchFunc16, Func`2 matchFunc17, Func`2 matchFunc18, Func`2 matchFunc19, Func`2 matchFunc20, Func`2 matchFunc21, Func`2 matchFunc22, Func`2 matchFunc23, Func`2 matchFunc24, Func`2 matchFunc25, Func`2 matchFunc26, Func`2 matchFunc27, Func`2 matchFunc28, Func`2 matchFunc29, Func`2 matchFunc30, Func`2 matchFunc31, Func`2 matchFunc32, Func`2 matchFunc33, Func`2 matchFunc34, Func`2 matchFunc35, Func`2 matchFunc36, Func`2 matchFunc37, Func`2 matchFunc38, Func`2 matchFunc39, Func`2 matchFunc40, Func`2 matchFunc41, Func`2 matchFunc42, Func`2 defaultFunc)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypesWorker_DoNotCallDirectly(Int32 position)
   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService`1.InferTypes(SemanticModel semanticModel, Int32 position, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Shared.Extensions.ITypeInferenceServiceExtensions.InferType(ITypeInferenceService typeInferenceService, SemanticModel semanticModel, Int32 position, Boolean objectAsDefault, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Completion.Providers.EnumAndCompletionListTagCompletionProvider.<GetItemsWorkerAsync>d__2.MoveNext()

```

### LINKED ISSUE #5255: VS crash when trying to bring up completion list in lambda
Consider a project with the following files.

>**File1.cs**
>```C#
using System.Collections.Generic;
using System.Linq;
namespace Microsoft.VisualStudio.InteractiveWindow.UnitTests
{
    public class HistoryTests 
    {
        private readonly History _history;
        public HistoryTests()
        {
            _history = new History();
        }
        private IEnumerable<string> HistoryEntries => _history.Items.Select(e =>
    }
}
```


>**File2.cs**
>```C#
using System.Collections.Generic;
namespace Microsoft.VisualStudio.InteractiveWindow.UnitTests
{
    internal class History
    {
        public IEnumerable<int> Items { get; set; }
    }
}
```

If we place our cursor at the end of `=>` at the end of File1.cs and press space, we will get the following error.
```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol.Construct(ImmutableArray`1 typeArguments) in C:\r\src\Compilers\CSharp\Portable\Symbols\MethodSymbol.cs:line 742
   at Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol.Microsoft.CodeAnalysis.IMethodSymbol.Construct(ITypeSymbol[] arguments) in C:\r\src\Compilers\CSharp\Portable\Symbols\MethodSymbol.cs:line 1149
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.Instantiate(IMethodSymbol method, IList`1 invocationTypes) in C:\r\src\Workspaces\CSharp\Portable\LanguageServices\CSharpTypeInferenceService.TypeInferrer.cs:line 576
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.<>c__DisplayClass20_0.<InferTypeInArgument>b__0(IMethodSymbol m) in C:\r\src\Workspaces\CSharp\Portable\LanguageServices\CSharpTypeInferenceService.TypeInferrer.cs:line 517
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeInArgument(Int32 index, IEnumerable`1 methods, ArgumentSyntax argumentOpt) in C:\r\src\Workspaces\CSharp\Portable\LanguageServices\CSharpTypeInferenceService.TypeInferrer.cs:line 517
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeInInvocationExpression(InvocationExpressionSyntax invocation, Int32 index, ArgumentSyntax argumentOpt) in C:\r\src\Workspaces\CSharp\Portable\LanguageServices\CSharpTypeInferenceService.TypeInferrer.cs:line 414
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeInArgument(ArgumentSyntax argument, Nullable`1 previousToken) in C:\r\src\Workspaces\CSharp\Portable\LanguageServices\CSharpTypeInferenceService.TypeInferrer.cs:line 257
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.<InferTypesWorker_DoNotCallDirectly>b__6_1(ArgumentSyntax argument) in C:\r\src\Workspaces\CSharp\Portable\LanguageServices\CSharpTypeInferenceService.TypeInferrer.cs:line 123
   at Microsoft.CodeAnalysis.Shared.Extensions.ObjectExtensions.TypeSwitch[TBaseType,TDerivedType1,TDerivedType2,TDerivedType3,TDerivedType4,TDerivedType5,TDerivedType6,TDerivedType7,TDerivedType8,TDerivedType9,TDerivedType10,TDerivedType11,TDerivedType12,TDerivedType13,TDerivedType14,TDerivedType15,TDerivedType16,TDerivedType17,TDerivedType18,TDerivedType19,TDerivedType20,TDerivedType21,TDerivedType22,TDerivedType23,TDerivedType24,TDerivedType25,TDerivedType26,TDerivedType27,TDerivedType28,TDerivedType29,TDerivedType30,TDerivedType31,TDerivedType32,TDerivedType33,TDerivedType34,TDerivedType35,TDerivedType36,TDerivedType37,TDerivedType38,TResult](TBaseType obj, Func`2 matchFunc1, Func`2 matchFunc2, Func`2 matchFunc3, Func`2 matchFunc4, Func`2 matchFunc5, Func`2 matchFunc6, Func`2 matchFunc7, Func`2 matchFunc8, Func`2 matchFunc9, Func`2 matchFunc10, Func`2 matchFunc11, Func`2 matchFunc12, Func`2 matchFunc13, Func`2 matchFunc14, Func`2 matchFunc15, Func`2 matchFunc16, Func`2 matchFunc17, Func`2 matchFunc18, Func`2 matchFunc19, Func`2 matchFunc20, Func`2 matchFunc21, Func`2 matchFunc22, Func`2 matchFunc23, Func`2 matchFunc24, Func`2 matchFunc25, Func`2 matchFunc26, Func`2 matchFunc27, Func`2 matchFunc28, Func`2 matchFunc29, Func`2 matchFunc30, Func`2 matchFunc31, Func`2 matchFunc32, Func`2 matchFunc33, Func`2 matchFunc34, Func`2 matchFunc35, Func`2 matchFunc36, Func`2 matchFunc37, Func`2 matchFunc38, Func`2 defaultFunc) in C:\r\src\Workspaces\Core\Portable\Shared\Extensions\ObjectExtensions.TypeSwitch.cs:line 7089
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypesWorker_DoNotCallDirectly(ExpressionSyntax expression) in C:\r\src\Workspaces\CSharp\Portable\LanguageServices\CSharpTypeInferenceService.TypeInferrer.cs:line 121
   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService`1.AbstractTypeInferrer.InferTypes(TExpressionSyntax expression, Boolean filterUnusable) in C:\r\src\Workspaces\Core\Portable\LanguageServices\TypeInferenceService\AbstractTypeInferenceService.cs:line 51
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeInLambdaExpression(ExpressionSyntax lambdaExpression) in C:\r\src\Workspaces\CSharp\Portable\LanguageServices\CSharpTypeInferenceService.TypeInferrer.cs:line 1350
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypeInSimpleLambdaExpression(SimpleLambdaExpressionSyntax lambdaExpression, Nullable`1 previousToken) in C:\r\src\Workspaces\CSharp\Portable\LanguageServices\CSharpTypeInferenceService.TypeInferrer.cs:line 1344
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.<>c__DisplayClass8_0.<InferTypesWorker_DoNotCallDirectly>b__35(SimpleLambdaExpressionSyntax simpleLambdaExpression) in C:\r\src\Workspaces\CSharp\Portable\LanguageServices\CSharpTypeInferenceService.TypeInferrer.cs:line 222
   at Microsoft.CodeAnalysis.Shared.Extensions.ObjectExtensions.TypeSwitch[TBaseType,TDerivedType1,TDerivedType2,TDerivedType3,TDerivedType4,TDerivedType5,TDerivedType6,TDerivedType7,TDerivedType8,TDerivedType9,TDerivedType10,TDerivedType11,TDerivedType12,TDerivedType13,TDerivedType14,TDerivedType15,TDerivedType16,TDerivedType17,TDerivedType18,TDerivedType19,TDerivedType20,TDerivedType21,TDerivedType22,TDerivedType23,TDerivedType24,TDerivedType25,TDerivedType26,TDerivedType27,TDerivedType28,TDerivedType29,TDerivedType30,TDerivedType31,TDerivedType32,TDerivedType33,TDerivedType34,TDerivedType35,TDerivedType36,TDerivedType37,TDerivedType38,TDerivedType39,TDerivedType40,TDerivedType41,TDerivedType42,TResult](TBaseType obj, Func`2 matchFunc1, Func`2 matchFunc2, Func`2 matchFunc3, Func`2 matchFunc4, Func`2 matchFunc5, Func`2 matchFunc6, Func`2 matchFunc7, Func`2 matchFunc8, Func`2 matchFunc9, Func`2 matchFunc10, Func`2 matchFunc11, Func`2 matchFunc12, Func`2 matchFunc13, Func`2 matchFunc14, Func`2 matchFunc15, Func`2 matchFunc16, Func`2 matchFunc17, Func`2 matchFunc18, Func`2 matchFunc19, Func`2 matchFunc20, Func`2 matchFunc21, Func`2 matchFunc22, Func`2 matchFunc23, Func`2 matchFunc24, Func`2 matchFunc25, Func`2 matchFunc26, Func`2 matchFunc27, Func`2 matchFunc28, Func`2 matchFunc29, Func`2 matchFunc30, Func`2 matchFunc31, Func`2 matchFunc32, Func`2 matchFunc33, Func`2 matchFunc34, Func`2 matchFunc35, Func`2 matchFunc36, Func`2 matchFunc37, Func`2 matchFunc38, Func`2 matchFunc39, Func`2 matchFunc40, Func`2 matchFunc41, Func`2 matchFunc42, Func`2 defaultFunc) in C:\r\src\Workspaces\Core\Portable\Shared\Extensions\ObjectExtensions.TypeSwitch.cs:line 8067
   at Microsoft.CodeAnalysis.CSharp.CSharpTypeInferenceService.TypeInferrer.InferTypesWorker_DoNotCallDirectly(Int32 position) in C:\r\src\Workspaces\CSharp\Portable\LanguageServices\CSharpTypeInferenceService.TypeInferrer.cs:line 186
   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService`1.AbstractTypeInferrer.InferTypes(Int32 position) in C:\r\src\Workspaces\Core\Portable\LanguageServices\TypeInferenceService\AbstractTypeInferenceService.cs:line 41
   at Microsoft.CodeAnalysis.LanguageServices.TypeInferenceService.AbstractTypeInferenceService`1.InferTypes(SemanticModel semanticModel, Int32 position, CancellationToken cancellationToken) in C:\r\src\Workspaces\Core\Portable\LanguageServices\TypeInferenceService\AbstractTypeInferenceService.cs:line 82
   at Microsoft.CodeAnalysis.Shared.Extensions.ITypeInferenceServiceExtensions.InferType(ITypeInferenceService typeInferenceService, SemanticModel semanticModel, Int32 position, Boolean objectAsDefault, CancellationToken cancellationToken) in C:\r\src\Workspaces\Core\Portable\Shared\Extensions\ITypeInferenceServiceExtensions.cs:line 46
   at Microsoft.CodeAnalysis.CSharp.Completion.Providers.EnumAndCompletionListTagCompletionProvider.<GetItemsWorkerAsync>d__2.MoveNext() in C:\r\src\Features\CSharp\Portable\Completion\CompletionProviders\EnumAndCompletionListTagCompletionProvider.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractCompletionProvider.<GetItemsAsync>d__3.MoveNext() in C:\r\src\Features\Core\Portable\Completion\Providers\AbstractCompletionProvider.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractCompletionProvider.<ProduceCompletionListAsync>d__1.MoveNext() in C:\r\src\Features\Core\Portable\Completion\Providers\AbstractCompletionProvider.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.AbstractCompletionService.<GetCompletionListAsync>d__16.MoveNext() in C:\r\src\Features\Core\Portable\Completion\AbstractCompletionService.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Completion.AbstractCompletionService.<GetCompletionListAsync>d__11.MoveNext() in C:\r\src\Features\Core\Portable\Completion\AbstractCompletionService.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<GetCompletionListAsync>d__14.MoveNext() in C:\r\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Controller.Session_ComputeModel.cs:line 127
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<DoInBackgroundAsync>d__13.MoveNext() in C:\r\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Controller.Session_ComputeModel.cs:line 102
```

While trying to bring up the completion list, the typeinferer throws an exception because it is attempting to construct a method whose `ConstructedFrom` property reference is not equal to itself (see [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Symbols/MethodSymbol.cs,740)).

### PR DESCRIPTION
**Pull request by jmarolf**
…uctedFrom type
Fixes #5126
Fixes #5255

### CODE REVIEW

**Comment by jmarolf** [comment]
Reviewers: @balajikris, @brettfo, @CyrusNajmabadi, @davkean, @dpoeschl, @jasonmalinowski, @DustinCampbell, @Pilchie, @rchande

**Comment by jmarolf** [comment]
@amcasey @tmat @TyOverby for context.

File: src/Workspaces/CSharp/Portable/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs [hunk 1]
```diff
@@ -573,6 +573,12 @@ private IMethodSymbol Instantiate(IMethodSymbol method, IList<ITypeSymbol> invoc
                 }
 
                 var typeArguments = method.ConstructedFrom.TypeParameters.Select(tp => bestMap.GetValueOrDefault(tp) ?? tp).ToArray();
+
+                if (!ReferenceEquals(method, method.ConstructedFrom))
+                {
+                    return method.ConstructedFrom.Construct(typeArguments);
```
Comment (amcasey) [inline src/Workspaces/CSharp/Portable/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs]: Just do this regardless?  If they're ReferenceEquals, it will be equivalent, right?

**Comment by amcasey** [comment]
Regression test?

**Comment by balajikris** [comment]
Here is a unit testable repro from 5126... Type infer at $$

```C#
using System.Collections.Generic;
using System.Linq;

class C
{
    void M(IEnumerable<string> args)
    {
        args = args.Select(a =>$$) // where '$$' is the cursor location, hit space
    }
}
```

**Comment by jmarolf** [comment]
Thanks @balajikris I'll add some tests

**Comment by brettfo** [comment]
Pending unit tests, :shipit: and thank you!

File: src/Workspaces/CSharp/Portable/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs (hunk 1 above)
Comment (CyrusNajmabadi) [inline src/Workspaces/CSharp/Portable/LanguageServices/CSharpTypeInferenceService.TypeInferrer.cs]: +1

**Comment by CyrusNajmabadi** [comment]
:+1:

File: src/EditorFeatures/CSharpTest/TypeInferrer/TypeInferrerTests.cs [hunk 2]
```diff
@@ -1683,5 +1683,23 @@ void M()
...
+        {
+            var text =
+    @"using System.Collections.Generic;
+using System.Linq;
+
+class C
+{
+    void M(IEnumerable<string> args)
+    {
+        args = args.Select(a =>[||])
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/TypeInferrer/TypeInferrerTests.cs]: could you also test with:  

```args = args.Select(a => [|b|])```

Comment (jmarolf) [inline src/EditorFeatures/CSharpTest/TypeInferrer/TypeInferrerTests.cs]: Done

File: src/EditorFeatures/CSharpTest/TypeInferrer/TypeInferrerTests.cs [hunk 3]
```diff
@@ -22,8 +22,8 @@ protected override void TestWorker(Document document, TextSpan textSpan, string
             var typeInference = document.GetLanguageService<ITypeInferenceService>();
 
             var inferredType = useNodeStartPosition
-                ? typeInference.InferType(document.GetSemanticModelForSpanAsync(new TextSpan(node.SpanStart, 0), CancellationToken.None).Result, node.SpanStart, objectAsDefault: true, cancellationToken: CancellationToken.None)
-                : typeInference.InferType(document.GetSemanticModelForSpanAsync(node.Span, CancellationToken.None).Result, node, objectAsDefault: true, cancellationToken: CancellationToken.None);
+                ? typeInference.InferType(document.GetSemanticModelForSpanAsync(new TextSpan(node?.SpanStart ?? textSpan.Start, 0), CancellationToken.None).Result, node?.SpanStart ?? textSpan.Start, objectAsDefault: true, cancellationToken: CancellationToken.None)
+                : typeInference.InferType(document.GetSemanticModelForSpanAsync(node?.Span ?? textSpan, CancellationToken.None).Result, node, objectAsDefault: true, cancellationToken: CancellationToken.None);
```
Comment (Pilchie) [inline src/EditorFeatures/CSharpTest/TypeInferrer/TypeInferrerTests.cs]: What are these changes about?  Also, would it maybe be clearer to just have:
```
textSpan = node?.Span ?? textSpan;
```

Before this, so that you can unconditionally use textSpan?
