### PR TITLE
Avoid GUID conflicts for Naming Styles Symbol Specifications (causes Naming Styles to not work and the Tools | Options page to not load)

### LINKED ISSUE #16431: Naming Styles can be completely broken by adding multiple specifications
To the point where the option page won't even load.

Rough repro steps:
1. Add two symbol specifications
2. Create two rules, that use the two symbol specifications
3. Save the options. Try to reopen the option page. It'll fail to load.

It doesn't repro if you do the analogous thing with Styles instead of Specifications.

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #16431

Escrow Template
================

**Customer scenario**: The user adds two Naming Styles Symbol Specifications in the same VS session, and the Naming Styles analyzer stops working altogether, and the Naming Styles Tools | Options page will no longer load if one of these symbol specifications are actually used in a rule.

**Bugs this fixes:** #16431

**Workarounds, if any**: The user can only add one Symbol Specification per VS session. Once two have been added, fixing it requires manual edits to your CurrentSettings.vssettings file.

**Risk**: Very low. This code is in the Naming Styles option pages code, and nothing sits on top of that layer. It's essentially the same code as before, we just create a new guid for each new Symbol Specification instead of accidentally caching the guid.

**Performance impact**: We make a new SymbolSpecification object each time the user adds a symbol specification, but that is extremely minor and is done extremely infrequently.

**Is this a regression from a previous update?** Yes, this is a regression from RC.2

**Root cause analysis:** I believe a refactoring was done as part of a larger effort which introduced the caching of the new Symbol Specification guid.

**How was the bug found?**: Ad-hoc testing

### CODE REVIEW

**Comment by dpoeschl** [comment]
This change will eventually be included in a larger PR, but it can be reviewed independently. Tagging @dotnet/roslyn-ide @jmarolf for review.

File: src/Workspaces/Core/Portable/NamingStyles/Serialization/SymbolSpecification.cs [hunk 1]
```diff
@@ -60,6 +33,36 @@ internal class SymbolSpecification
             ApplicableSymbolKindList = symbolKindList;
         }
 
+        public static SymbolSpecification CreateDefaultSymbolSpecification()
+        {
+            return new SymbolSpecification(
+                id: Guid.NewGuid(),
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/NamingStyles/Serialization/SymbolSpecification.cs]: doc that this gives a fresh guid each time, which is what we want. (i assume that's true)

Comment (dpoeschl) [inline src/Workspaces/Core/Portable/NamingStyles/Serialization/SymbolSpecification.cs]: Yes, that's true.

**Comment by dpoeschl** [comment]
@CyrusNajmabadi comment added.

File: src/Workspaces/Core/Portable/NamingStyles/Serialization/SymbolSpecification.cs [hunk 2]
```diff
@@ -60,6 +33,38 @@ internal class SymbolSpecification
             ApplicableSymbolKindList = symbolKindList;
         }
 
+        public static SymbolSpecification CreateDefaultSymbolSpecification()
+        {
+            // Always use a new, distinct guid
```
Comment (Pilchie) [inline src/Workspaces/Core/Portable/NamingStyles/Serialization/SymbolSpecification.cs]: Why?

Comment (dpoeschl) [inline src/Workspaces/Core/Portable/NamingStyles/Serialization/SymbolSpecification.cs]: Yep, bad comment was bad.

Comment (Pilchie) [inline src/Workspaces/Core/Portable/NamingStyles/Serialization/SymbolSpecification.cs]: Much better - thanks!

**Comment by dpoeschl** [comment]
Tagging @MattGertz for Escrow consideration.

**Comment by dpoeschl** [comment]
@natidea I've filed https://devdiv.visualstudio.com/DevDiv/_workitems?id=370236&fullScreen=false&_a=edit for tracking. Can you verify that it looks okay and will show up in the shiproom query?

**Comment by natidea** [comment]
Approved to merge via [370236](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/370236)
