### PR TITLE
Unify implementation of 'go to defintion' and 'go to definition on hover'

### LINKED ISSUE #63693: CTRL+Click does not navigate in Decompiled document
**Version Used**: 

**Steps to Reproduce**:

1. Navigate to a decompiled type
2. CTRL+Click on a type within decompiled type that does not live within that file

**Expected Behavior**:
Navigates to that type in the same way that right-click Go To Definition does

**Actual Behavior**:
Nothing

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/63694
Fixes #63693

No clue why we had separate services for this.  Now we always defer to the single service for both use cases.

### CODE REVIEW

File: src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptGoToSymbolService.cs [hunk 1]
```diff
@@ -8,11 +8,15 @@
...
+using Microsoft.CodeAnalysis.Navigation;
+using Microsoft.CodeAnalysis.Text;
+using System.Threading;
 
 namespace Microsoft.CodeAnalysis.ExternalAccess.VSTypeScript
 {
-    [ExportLanguageService(typeof(IGoToSymbolService), InternalLanguageNames.TypeScript), Shared]
-    internal sealed class VSTypeScriptGoToSymbolService : IGoToSymbolService
+    [ExportLanguageService(typeof(IAsyncGoToDefinitionService), InternalLanguageNames.TypeScript), Shared]
+    internal sealed class VSTypeScriptGoToSymbolService : IAsyncGoToDefinitionService
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptGoToSymbolService.cs:19]: TS internal side change of our EA layer.  the external side of course stays unchanged.

File: src/EditorFeatures/Core/GoToDefinition/AbstractGoToDefinitionService.cs [hunk 2]
```diff
@@ -42,40 +43,47 @@ internal abstract class AbstractAsyncGoToDefinitionService : AbstractFindDefinit
                 workspace, document.Id, position, virtualSpace: 0, cancellationToken);
         }
 
-        public async Task<INavigableLocation?> FindDefinitionLocationAsync(Document document, int position, CancellationToken cancellationToken)
+        public async Task<(INavigableLocation? location, TextSpan symbolSpan)> FindDefinitionLocationAsync(
+            Document document,
+            int position,
+            CancellationToken cancellationToken)
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/GoToDefinition/AbstractGoToDefinitionService.cs:49]: main change here is to allow our internal API to return not just hte location, but also the span of hte reference.  NOrmal go-to doesn't need this, but go-to-on-hover uses this to determine waht span to underline.

File: src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/VSTypeScriptWellKnownSymbolTypes.cs [hunk 3]
```diff
@@ -2,12 +2,10 @@
...
 // See the LICENSE file in the project root for more information.
 
-using Microsoft.CodeAnalysis.GoToDefinition;
-
 namespace Microsoft.CodeAnalysis.ExternalAccess.VSTypeScript.Api
 {
     internal static class VSTypeScriptWellKnownSymbolTypes
     {
-        public const string Definition = WellKnownSymbolTypes.Definition;
+        public const string Definition = nameof(Definition);
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/ExternalAccess/VSTypeScript/Api/VSTypeScriptWellKnownSymbolTypes.cs:9]: note: Thsi is kept around for binary compat (TS does reference this).  But in the past, and in the present, the value is never actually used for any purposes.  I think maybe someone wanted this to be a flexible system with more types of symbols types.  but that has never been a thing as of yet.

File: src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptGoToSymbolService.cs (hunk 1 above)
Comment (dibarbet) [reply src/EditorFeatures/Core/ExternalAccess/VSTypeScript/VSTypeScriptGoToSymbolService.cs:18]: 🎉 hurray for external access

File: src/EditorFeatures/Core/GoToDefinition/AbstractGoToDefinitionService.cs (hunk 2 above)
Comment (dibarbet) [reply src/EditorFeatures/Core/GoToDefinition/AbstractGoToDefinitionService.cs:49]: if we don't have an `INavigableLocation` can we do anything with the text span?  Or should this be `(INavigableLocation location, TextSpan symbolSpan)?` where the whole tuple is nullable?

File: src/EditorFeatures/Core.Wpf/NavigableSymbols/NavigableSymbolService.NavigableSymbol.cs [hunk 4]
```diff
@@ -58,25 +46,21 @@ private class NavigableSymbol : INavigableSymbol
...
                 // Fire and forget.
-                var token = _listener.BeginAsyncOperation(nameof(NavigateAsync));
+                var token = _service._listener.BeginAsyncOperation(nameof(NavigateAsync));
                 _ = NavigateAsync().ReportNonFatalErrorAsync().CompletesAsyncOperation(token);
             }
 
             private async Task NavigateAsync()
             {
-                using var context = _uiThreadOperationExecutor.BeginExecute(
+                using var context = _service._uiThreadOperationExecutor.BeginExecute(
```
Comment (dibarbet) [inline src/EditorFeatures/Core.Wpf/NavigableSymbols/NavigableSymbolService.NavigableSymbol.cs:55]: talked offline - could use the background wait indicator here since we already use it for gotodef

Comment (CyrusNajmabadi) [reply src/EditorFeatures/Core.Wpf/NavigableSymbols/NavigableSymbolService.NavigableSymbol.cs]: done.

File: src/EditorFeatures/Core.Wpf/NavigableSymbols/NavigableSymbolService.cs [hunk 5]
```diff
@@ -20,32 +18,27 @@ namespace Microsoft.CodeAnalysis.Editor.NavigableSymbols
     [Export(typeof(INavigableSymbolSourceProvider))]
     [Name(nameof(NavigableSymbolService))]
     [ContentType(ContentTypeNames.RoslynContentType)]
-    internal partial class NavigableSymbolService : INavigableSymbolSourceProvider
+    internal sealed partial class NavigableSymbolService : INavigableSymbolSourceProvider
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core.Wpf/NavigableSymbols/NavigableSymbolService.cs:21]: Oh this thing is in the WPF layer. Ah, that's why I couldn't find it. 😦

**Review by dibarbet — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
>if we don't have an INavigableLocation can we do anything with the text span? Or should this be (INavigableLocation location, TextSpan symbolSpan)? where the whole tuple is nullable?

Discussed offline.  This is more ergonomic wrt to deconstruction.  The complaint is valid though, and i think we should examine on a case by case basis where this is a positivevs a negative.
