### PR TITLE
Await in local function inside lock is now working as expected

### LINKED ISSUE #18644: Incorrect error for await in local function inside lock
See https://github.com/dotnet/csharplang/issues/392 for details.

The compiler improperly produces an error when `await` is used inside a local function whose declaration happens to be inside a `lock` statement.

### PR DESCRIPTION
**Pull request by t-camaia**
The InMethodBinder constructor was edited to pass the desired BinderFlags. Some flags were being passed by mistake to LocalScopeBinder while visiting local functions.

Also, a few tests were added to assure correct behavior.

Fixes #18644 
Fixes https://github.com/dotnet/roslyn/issues/24102

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 1]
```diff
@@ -30,6 +30,34 @@ internal void VerifyDiagnostics(string source, CSharpCompilationOptions options,
...
+            };
+
+            listOfTasks.Add(localFunc());
+        }
+    }
+}
+";
+
+            var comp = CreateCompilationWithMscorlib46(source);
+            comp.VerifyDiagnostics();
```
Comment (VSadov) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: But does it really run as expected?

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 2]
```diff
@@ -30,6 +30,34 @@ internal void VerifyDiagnostics(string source, CSharpCompilationOptions options,
     [CompilerTrait(CompilerFeature.LocalFunctions)]
     public class LocalFunctionTests : LocalFunctionsTestBase
     {
+        [ConditionalFact(typeof(DesktopOnly))]
```
Comment (VSadov) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: Should it be DesktopOnly? The test code does not look as possibly platform specific.

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 3]
```diff
@@ -30,6 +30,34 @@ internal void VerifyDiagnostics(string source, CSharpCompilationOptions options,
...
+            listOfTasks.Add(localFunc());
+        }
+    }
+}
+";
+
+            var comp = CreateCompilationWithMscorlib46(source);
+            comp.VerifyDiagnostics();
+        }
+
```
Comment (VSadov) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: The change should make rethrowing exceptions illegal in a local function in a catch, which is correct. I think we need a test for that.

Perhaps it is worth checking all the scenarios affected by the `AllClearedAtExecutableCodeBoundary`.  There are 6 flags in there. Not sure if `InCatchFilter` can be tested, since local function cannot be in an expression. Others are certainly testable. (you can put more than one scenario in a test, so this won't be a lot of tests)

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 4]
```diff
@@ -30,6 +30,34 @@ internal void VerifyDiagnostics(string source, CSharpCompilationOptions options,
...
+            listOfTasks.Add(localFunc());
+        }
+    }
+}
+";
+
+            var comp = CreateCompilationWithMscorlib46(source);
+            comp.VerifyDiagnostics();
+        }
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: Please also test a lock containing a local function containing a lock containing an await (that should produce a diagnostic).
The fact that we're resetting flags at the local function boundary shouldn't prevent the old behavior to kick in within the local function.

Comment (jcouv) [reply src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: Also, just FYI, I was curious whether lambdas might have a similar issue. They [don't appear to](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAGAAhwEYBWAbgFgAoHAJgIGEaBvGgjogFgIFkAKAPbAAVnADGMAoICU7Tm2qdlBDIPEBrIXKUqOivXpIA6EgwgEAvEQAcBfjKsA+eYYWu3KnAE4iANmMATTQ4DAATBypdTwIAXyi3WI8k6ligA==).

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs (hunk 2 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: In theory no it shouldn't be desktop only. This particular test hit a problem in our CoreClr infrastructure code though. To unblock this PR I had @t-camaia mark it as desktop only. Andy and I are discussing the bigger problem this exposed and how best to work around it.

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs (hunk 1 above)
Comment (t-camaia) [reply src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: Yes! Am I missing something?

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs (hunk 3 above)
Comment (t-camaia) [reply src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: I just added some test scenarios. All flags but InCatchFilter are being tested.

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs (hunk 4 above)
Comment (t-camaia) [reply src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: Done! I put it in LocalFunctionDoesNotOverwriteInnerScopeFlags method.

Comment (t-camaia) [reply src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: That's interesting. Looking through the code it seems lambdas do behave similarly and inherit all the flags from their parent. I think it would be necessary to debug it to understand what's happening.

**Comment by jcouv** [comment]
FYI, updated the description to record that this PR also fixes https://github.com/dotnet/roslyn/issues/24102

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 5]
```diff
@@ -30,6 +30,162 @@ internal void VerifyDiagnostics(string source, CSharpCompilationOptions options,
...
+            localFunc();
+        }
+        catch (Exception)
+        {
+            IEnumerable<int> localFunc()
+            {
+                try{}
+                catch (Exception)
+                {
+                    yield return 1;
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: Small detail: please return different values in the different locations, so it's easier to match code and diagnostics.
Alternatively, you can do "yield return 1; // errror 2", as the comment will be included in the diagnostic.

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 6]
```diff
@@ -30,6 +30,162 @@ internal void VerifyDiagnostics(string source, CSharpCompilationOptions options,
...
+
+class C
+{
+    void M(List<Task> listOfTasks)
+    {
+        lock(listOfTasks)
+        {
+            async Task localFunc()
+            {
+                await Task.Yield();
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: >await Task.Yield(); [](start = 16, length = 19)

I think Vlad pointed this out earlier. You should split the test into the portion that works and the portion that produces a diagnostic. Then the portion that works should be checked for execution (`CompileAndVerify(..., expectedOutput: "")`).

File: src/Compilers/CSharp/Portable/Binder/InMethodBinder.cs [hunk 7]
```diff
@@ -36,7 +36,12 @@ public IteratorInfo(TypeSymbol elementType, ImmutableArray<Diagnostic> elementTy
         }
 
         public InMethodBinder(MethodSymbol owner, Binder enclosing)
-            : base(enclosing)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/InMethodBinder.cs]: >base(enclosing) [](start = 14, length = 15)

It feels like it would be better to keep one constructor, but adjust the initializer to clear unwanted flags.
```
base(enclosing, enclosing.Flags & ~BinderFlags.AllClearedAtExecutableCodeBoundary)
```

File: src/Compilers/CSharp/Portable/Binder/LocalBinderFactory.cs [hunk 8]
```diff
@@ -233,7 +233,7 @@ public override void VisitLocalFunctionStatement(LocalFunctionStatementSyntax no
 
                     binder = binder.WithUnsafeRegionIfNecessary(node.Modifiers);
 
-                    Visit(body, new InMethodBinder(match, binder));
+                    Visit(body, new InMethodBinder(match, binder, binder.Flags & ~BinderFlags.AllClearedAtExecutableCodeBoundary));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/LocalBinderFactory.cs]: >Visit(body, new InMethodBinder(match, binder, binder.Flags & ~BinderFlags.AllClearedAtExecutableCodeBoundary)); [](start = 20, length = 111)

It feels like InMethodBinder constructor should just take care of this.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/LocalBinderFactory.cs]: >AllClearedAtExecutableCodeBoundary [](start = 94, length = 34)

Please make sure to add tests covering each bit from BinderFlags.AllClearedAtExecutableCodeBoundary

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1)

File: src/Compilers/CSharp/Portable/Binder/LocalBinderFactory.cs (hunk 8 above)
Comment (t-camaia) [reply src/Compilers/CSharp/Portable/Binder/LocalBinderFactory.cs]: Like Vlad pointed out, InCatchFilter probably can't be tested, since we can't put a local function inside an expression. It wouldn't change much, but I could define a new group of flags without the InCatchFilter flag.

File: src/Compilers/CSharp/Portable/Binder/InMethodBinder.cs (hunk 7 above)
Comment (t-camaia) [reply src/Compilers/CSharp/Portable/Binder/InMethodBinder.cs]: It actually makes sense. I'll test it locally and push the changes once I'm finished with the tests.

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs (hunk 5 above)
Comment (t-camaia) [reply src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: Done.

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs (hunk 6 above)
Comment (t-camaia) [reply src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: Done.

File: src/Compilers/CSharp/Portable/Binder/InMethodBinder.cs (hunk 7 above)
Comment (t-camaia) [reply src/Compilers/CSharp/Portable/Binder/InMethodBinder.cs]: Done.

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 9]
```diff
@@ -30,6 +30,235 @@ internal void VerifyDiagnostics(string source, CSharpCompilationOptions options,
...
+            var source = @"
+using System;
+using System.Threading.Tasks;
+
+class C
+{
+    static void Main()
+    {
+        lock (new Object())
+        {
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: `await localFunc();` here and `System.Console.Write("localFunc");` after `await Task.Yield();` to have a visual confirmation that program ran as expected. Thanks

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 10]
```diff
@@ -30,6 +30,235 @@ internal void VerifyDiagnostics(string source, CSharpCompilationOptions options,
...
+            {
+                yield return 3;
+            }
+        }
+    }
+}
+";
+
+            var comp = CreateCompilationWithMscorlib46(source, options: TestOptions.ReleaseExe);
+            CompileAndVerify(comp, expectedOutput: "");
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: Same, let's get printf verification that the code ran as expected.

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs (hunk 9 above)
Comment (t-camaia) [reply src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: Done. All expected outputs are non-empty now.

**Comment by jaredpar** [comment]
retest windows_release_unit64_prtest please

**Comment by t-camaia** [comment]
@dotnet/roslyn-compiler

File: src/Compilers/CSharp/Portable/Binder/InMethodBinder.cs [hunk 11]
```diff
@@ -36,7 +36,7 @@ public IteratorInfo(TypeSymbol elementType, ImmutableArray<Diagnostic> elementTy
...
+            : base(enclosing, enclosing.Flags & ~BinderFlags.AllClearedAtInMethodBoundary)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/InMethodBinder.cs]: >AllClearedAtInMethodBoundary [](start = 61, length = 28)

I don't think it is necessary to introduce a new set of flags. Instead, I would assert in the body of the constructor that enclosing.Flags doesn't contain flags that we cannot create tests for.

**Comment by AlekseyTs** [comment]
Done with review pass.

**Comment by AlekseyTs** [comment]
@t-camaia In the future, please do not re-base PRs that are under review, simply push additional commits to it. GitHub supports squashing commits when PR is merged.

File: src/Compilers/CSharp/Portable/Binder/InMethodBinder.cs (hunk 11 above)
Comment (t-camaia) [reply src/Compilers/CSharp/Portable/Binder/InMethodBinder.cs]: Alright. Just added an assert.

File: src/Compilers/CSharp/Portable/Binder/LocalBinderFactory.cs (hunk 8 above)
Comment (agocke) [reply src/Compilers/CSharp/Portable/Binder/LocalBinderFactory.cs]: I don't think that's necessary, we can just skip InCatchFilter.

**Comment by t-camaia** [comment]
@dotnet/roslyn-compiler
