### PR TITLE
🔼 Remember decompiler EULA in the solution user options

### LINKED ISSUE #26415: Remember "Navigate to decompiled sources" user agreement
**Version Used**: 15.7

**Steps to Reproduce**:

1. Enable "Navigate to decompiled sources"
2. Press <kbd>F12</kbd> to navigate to a symbol in metadata
3. Accept the license agreement
4. Restart Visual Studio and repeat the steps above

**Expected Behavior**:

During step 4, the disclaimer should not be shown. In particular, a value of Accept should be remembered in the following conditions:

1. The disclaimer was accepted for the current solution
2. Step 1 was completed on the current machine

The value of accept could be stored in the .suo file to meet the above conditions. If stored in the VS profile somewhere, roaming for the option should be explicitly disabled.

📝  The above design has been approved by legal. Deviations from the above may require separate approval and could delay the work, so at this point the issue is considered a "task" more than a discussion.

**Actual Behavior**:

The disclaimer acceptance state is reset every time Visual Studio is launched.

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #26415

### CODE REVIEW

File: src/EditorFeatures/Core/DefaultDecompilerEulaService.cs [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+        [ImportingConstructor]
+        [Obsolete(MefConstruction.ImportingConstructorMessage, error: true)]
+        public DefaultDecompilerEulaService()
+        {
+            _isAccepted = false;
+        }
+
+        public Task<bool> IsAcceptedAsync(CancellationToken cancellationToken)
+        {
+            return _isAccepted ? SpecializedTasks.True : SpecializedTasks.False;
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Core/DefaultDecompilerEulaService.cs]: We don't just have FromResult that does this?

File: src/VisualStudio/Core/Def/RoslynPackage.cs [hunk 2]
```diff
@@ -40,12 +41,52 @@ namespace Microsoft.VisualStudio.LanguageServices.Setup
     [ProvideMenuResource("Menus.ctmenu", version: 16)]
     internal class RoslynPackage : AbstractPackage
     {
+        // note: must be <= 31 characters long
+        private const string DecompilerEulaOptionKey = "ILSpy-234190A6EE66";
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/RoslynPackage.cs]: What's with the magic number?

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs [hunk 3]
```diff
@@ -119,14 +119,15 @@ public bool TryNavigateToSymbol(ISymbol symbol, Project project, OptionSet optio
             // Check whether decompilation is supported for the project. We currently only support this for C# projects.
             if (project.LanguageServices.GetService<IDecompiledSourceService>() != null)
             {
+                var eulaService = project.Solution.Workspace.Services.GetRequiredService<IDecompilerEulaService>();
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs]: Is there any reason this a workspace service? Given the implementation is using JTF it means nobody can actually call it from any layer below the VS layer effectively, and I don't imagine different workspaces needing different implementations.

Comment (Therzok) [reply src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs]: The other IDE?

Comment (Therzok) [reply src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs]: Oh, well, technically, we would also be VS layer.

Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs]: @jasonmalinowski It uses `IVsPersistSolutionOpts`, which I assume is not available in other contexts

File: src/EditorFeatures/Core/DefaultDecompilerEulaService.cs (hunk 1 above)
Comment (sharwell) [reply src/EditorFeatures/Core/DefaultDecompilerEulaService.cs]: We do not

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs (hunk 3 above)
Comment (jasonmalinowski) [reply src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs]: Yeah, the method this is being called in is already using all sorts of other VS for Windows interfaces. :smile:

File: src/EditorFeatures/Core/DefaultDecompilerEulaService.cs (hunk 1 above)
Comment (jasonmalinowski) [reply src/EditorFeatures/Core/DefaultDecompilerEulaService.cs]: Sounds like a great opportunity to refactor!

Comment (sharwell) [reply src/EditorFeatures/Core/DefaultDecompilerEulaService.cs]: :arrow_right: dotnet/corefx#21880 seems sufficient in context, but another bug could be opened if you were looking for something more specific.

File: src/VisualStudio/Core/Def/RoslynPackage.cs (hunk 2 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/RoslynPackage.cs]: :arrow_right: I rebased this change to fix merge conflicts, and the only change of substance was the addition of this comment for the constant:

> The randomly-generated key name is used for serializing the ILSpy decompiler EULA preference to the .SUO file. It doesn't have any semantic meaning, but is intended to not conflict with any other extension that might be saving an "ILSpy" named stream to the same file.

File: src/VisualStudio/Core/Def/Implementation/VisualStudioDecompilerEulaService.cs [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+        public VisualStudioDecompilerEulaService(SVsServiceProvider serviceProvider, IThreadingContext threadingContext)
+        {
+            _serviceProvider = (IAsyncServiceProvider)serviceProvider;
+            _threadingContext = threadingContext;
+        }
+
+        public async Task<bool> IsAcceptedAsync(CancellationToken cancellationToken)
+        {
+            var roslynPackage = await TryGetRoslynPackageAsync(cancellationToken).ConfigureAwait(false);
+            return roslynPackage.IsDecompilerEulaAccepted;
```
Comment (dpoeschl) [inline src/VisualStudio/Core/Def/Implementation/VisualStudioDecompilerEulaService.cs]: Null reference if `TryGetRoslynPackageAsync` fails for some reason?

Or if we know it won't fail, then renaming & restructuring that method would help.

Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/VisualStudioDecompilerEulaService.cs]: Enabled nullable reference types and resolved

File: src/VisualStudio/Core/Def/Implementation/VisualStudioDecompilerEulaService.cs [hunk 5]
```diff
@@ -0,0 +1,72 @@
...
+        public async Task MarkAcceptedAsync(CancellationToken cancellationToken)
+        {
+            var roslynPackage = await TryGetRoslynPackageAsync(cancellationToken).ConfigureAwait(false);
+            if (roslynPackage is object)
+            {
+                roslynPackage.IsDecompilerEulaAccepted = true;
+            }
+        }
+
+        private async ValueTask<RoslynPackage?> TryGetRoslynPackageAsync(CancellationToken cancellationToken)
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Def/Implementation/VisualStudioDecompilerEulaService.cs]: trying to understand the scenario where we get into these codepaths but roslyn hasn't loaded. isn't the decompilatino option part of our property pages, which should only be available if our package is loaded?

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs [hunk 6]
```diff
@@ -121,16 +124,15 @@ public bool TryNavigateToSymbol(ISymbol symbol, Project project, OptionSet optio
...
+                    var notificationService = project.Solution.Workspace.Services.GetRequiredService<INotificationService>();
                     allowDecompilation = notificationService.ConfirmMessageBox(ServicesVSResources.Decompiler_Legal_Notice_Message, ServicesVSResources.Decompiler_Legal_Notice_Title, NotificationSeverity.Warning);
                     if (allowDecompilation)
                     {
-                        var workspace = project.Solution.Workspace;
-                        workspace.TryApplyChanges(workspace.CurrentSolution.WithOptions(workspace.Options
-                            .WithChangedOption(FeatureOnOffOptions.AcceptedDecompilerDisclaimer, true)));
+                        ThreadingContext.JoinableTaskFactory.Run(() => eulaService.MarkAcceptedAsync(cancellationToken));
                     }
                 }
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs]: if decompilatin is not allowed, what happens here

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs [hunk 7]
```diff
@@ -121,16 +124,15 @@ public bool TryNavigateToSymbol(ISymbol symbol, Project project, OptionSet optio
             // Check whether decompilation is supported for the project. We currently only support this for C# projects.
             if (project.LanguageServices.GetService<IDecompiledSourceService>() != null)
             {
+                var eulaService = project.Solution.Workspace.Services.GetRequiredService<IDecompilerEulaService>();
                 allowDecompilation = project.Solution.Workspace.Options.GetOption(FeatureOnOffOptions.NavigateToDecompiledSources) && !symbol.IsFromSource();
-                if (allowDecompilation && !project.Solution.Workspace.Options.GetOption(FeatureOnOffOptions.AcceptedDecompilerDisclaimer))
+                if (allowDecompilation && !ThreadingContext.JoinableTaskFactory.Run(() => eulaService.IsAcceptedAsync(cancellationToken)))
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs]: why is the eula checking here, instead of where the option is defined in the property pages?

File: src/VisualStudio/Core/Def/RoslynPackage.cs [hunk 8]
```diff
@@ -53,11 +57,54 @@ namespace Microsoft.VisualStudio.LanguageServices.Setup
         termValues: new[] { Guids.CSharpProjectExistsInWorkspaceUIContextString, Guids.VisualBasicProjectExistsInWorkspaceUIContextString })]
     internal class RoslynPackage : AbstractPackage
     {
-        private VisualStudioWorkspace _workspace;
-        private IComponentModel _componentModel;
-        private RuleSetEventHandler _ruleSetEventHandler;
-        private ColorSchemeApplier _colorSchemeApplier;
-        private IDisposable _solutionEventMonitor;
+        // The randomly-generated key name is used for serializing the ILSpy decompiler EULA preference to the .SUO
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Def/RoslynPackage.cs]: why save to SUO, instead of like the user profile?

seems unfortunate that if i flip to different projects (or make a new solution/prj) i would have to accept the prompt again, right?

File: src/VisualStudio/Core/Def/RoslynPackage.cs [hunk 9]
```diff
@@ -262,18 +309,20 @@ private void UnregisterRuleSetEventHandler()
...
+            RoslynDebug.AssertNotNull(_workspace);
+
             // we will pause whatever ambient work loads we have that are tied to IGlobalOperationNotificationService
             // such as solution crawler, pre-emptive remote host synchronization and etc. any background work users didn't
             // explicitly asked for.
             //
             // this should give all resources to BulkFileOperation. we do same for things like build, 
             // debugging, wait dialog and etc. BulkFileOperation is used for things like git branch switching and etc.
-            var globalNotificationService = _workspace.Services.GetService<IGlobalOperationNotificationService>();
+            IGlobalOperationNotificationService globalNotificationService = _workspace.Services.GetRequiredService<IGlobalOperationNotificationService>();
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Def/RoslynPackage.cs]: why?

File: src/VisualStudio/Core/Def/RoslynPackage.cs [hunk 10]
```diff
@@ -262,18 +309,20 @@ private void UnregisterRuleSetEventHandler()
...
 
             // BulkFileOperation can't have nested events. there will be ever only 1 events (Begin/End)
             // so we only need simple tracking.
-            var gate = new object();
-            GlobalOperationRegistration localRegistration = null;
+            object gate = new object();
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Def/RoslynPackage.cs]: why?

File: src/VisualStudio/Core/Def/Implementation/VisualStudioDecompilerEulaService.cs (hunk 5 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/VisualStudioDecompilerEulaService.cs]: It could be enabled through API usage of Roslyn.

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs (hunk 6 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs]: What do you mean by "not allowed" in this context?

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs (hunk 7 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs]: The EULA acceptance persists per solution instance.

File: src/VisualStudio/Core/Def/RoslynPackage.cs (hunk 8 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/RoslynPackage.cs]: This is the approval we got from legal for persisting the option.

File: src/VisualStudio/Core/Def/RoslynPackage.cs (hunk 9 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/RoslynPackage.cs]: The value is used in a local function.

File: src/VisualStudio/Core/Def/RoslynPackage.cs (hunk 10 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/RoslynPackage.cs]: The value is used in a local function.

File: src/VisualStudio/Core/Def/RoslynPackage.cs (hunk 9 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/RoslynPackage.cs]: ➡️ Bound by #41689 and/or #41705

File: src/VisualStudio/Core/Def/RoslynPackage.cs (hunk 10 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/RoslynPackage.cs]: ➡️ Covered by discussion in https://github.com/dotnet/roslyn/pull/33323#discussion_r398316375

File: src/VisualStudio/Core/Def/Implementation/VisualStudioDecompilerEulaService.cs (hunk 5 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/VisualStudioDecompilerEulaService.cs]: Also, this method can return null if called while the IDE is closing.

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs (hunk 6 above)
Comment (CyrusNajmabadi) [reply src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs]: confirmation box shows.  user clicks 'no'.  so we don't persist the eula acceptance.  won't they get into a prompt-loop teh next time they do anything?

Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs]: If decompilation is not allowed, meaning the user clicked 'No', then nothing happens. Put another way, this pull request does not change #42638. It only improves the experience when users hit 'Yes', which is presumably the case because the dialog only shows after a user manually enables this feature.

File: src/VisualStudio/Core/Def/RoslynPackage.cs (hunk 9 above)
Comment (CyrusNajmabadi) [reply src/VisualStudio/Core/Def/RoslynPackage.cs]: ah.  bleagh.

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs (hunk 6 above)
Comment (CyrusNajmabadi) [reply src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs]: > which is presumably the case because the dialog only shows after a user manually enables this feature.

but if a user manually enabled the feature... then they should have been prompted for the eula *then*.  and only if they accepted the eula should we even store the value that they want decompilation.  if they did not accept the eual then, then we shouldhave never set the 'true' bit for decompilation.  

I honestly don't get this.  it doesn't make sense to me (either in terms of user experience or in terms of the code).

Comment (CyrusNajmabadi) [reply src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs]: basically, i do not understand how the setting to decompile could ever be true, while the setting for the eula is ever false.  not at this location in the code.  We're in symbol-nav.  These settings should be in a consistent state long before we ever get here.

Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs]: The EULA is not presented when the option is checked in options, because that could have occurred while the user had a different solution open. The option is checked the first time navigation to a symbol in metadata occurs, where it can be checked in the context of persistence for the current solution.

Comment (CyrusNajmabadi) [reply src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs]: @mikadumont @jinujoseph  on this.  i'm just not getting it.  there' no reason i would expect or want to tie this option to a solution.  

> because that could have occurred while the user had a different solution open. 

If i go to option and turn on decompilaiton .i should get a prompt.  that prompt should be remembered forever.  Best case is that it's associated with my account and roamed.  Worst case it's remembered on the local machine.  But i can't understand any sort of design that ties this to somethinglike the solution or to navigation.  That makes no sense on any level, and does not give the user any sort of expected experience around decompilation that is sensible.

The fallout of that is the types of experiences i've been running into :-/

Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs]: @CyrusNajmabadi This is not our call to make on the public issue tracker. If you want to change the location where the message is presented, that request must go through an internal legal approval process.

Comment (CyrusNajmabadi) [reply src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioSymbolNavigationService.cs]: Talked to @mikadumont offline about this.  We're almost totally ok with where this PR brings us in terms of user expeirence.  One thing we want to change though is that if the user clicks 'no', we remember that choice of theirs and we disable "enable navigation to decompiled...".  That way they don't get pestered after informing us of their decision.

Then, if they want to enable this later, they can do so through tools|options.  

This is also a viable approach if we ever enable this option by default.  If we do, users will get the prompt on first-nav, but we will respect and persist their decision here on what they want their experience to be.

Tagging @jinujoseph as well.
