### PR TITLE
Fix "Tuple to Struct" named parameters being cased incorrectly

### LINKED ISSUE #45451: 'Convert to struct' refactoring bug, incorrect constructor call
**Version Used**: 
Visual Studio 2019 Preview - Version 16.7.0 Preview 3.0

**Steps to Reproduce**:
1. Create a console app with the following code. 
```
using System;

namespace ConsoleApp1 {
    class Program {
        static void Main(string[] args) {
            var point = (X: 3, Y: 4);

            Console.WriteLine(point.X);
            Console.WriteLine(point.Y);
        }
    }
}
```
2. Select the valuetuple (X:3, Y:4) and active the 'Convert to struct' refactoring
3. The constructor call will look like **var point = new NewStruct(X: 3, Y: 4);**  The named arguments are in uppercase and should be lowercase.

As you can see you get a compiler error (red squigly line) in the preview of the refactoring.
image

**Expected Behavior**:
I expected lower case argument names: **var point = new NewStruct(x: 3, y: 4);**.

The following code should have been generated

```
using System;

namespace ConsoleApp1 {
    class Program {
        static void Main(string[] args) {
            var point = new NewStruct(x: 3, y: 4);

            Console.WriteLine(point.X);
            Console.WriteLine(point.Y);
        }
    }

    internal struct NewStruct {
        public int X;
        public int Y;

        public NewStruct(int x, int y) {
            X = x;
            Y = y;
        }

        public override bool Equals(object obj) {
            return obj is NewStruct other &&
                   X == other.X &&
                   Y == other.Y;
        }

        public override int GetHashCode() {
            return HashCode.Combine(X, Y);
        }

        public void Deconstruct(out int x, out int y) {
            x = X;
            y = Y;
        }

        public static implicit operator (int X, int Y)(NewStruct value) {
            return (value.X, value.Y);
        }

        public static implicit operator NewStruct((int X, int Y) value) {
            return new NewStruct(value.X, value.Y);
        }
    }
}
```

**Actual Behavior**:
The following code is generated

```
using System;

namespace ConsoleApp1 {
    class Program {
        static void Main(string[] args) {
            var point = new NewStruct(X: 3, Y: 4); 

            Console.WriteLine(point.X);
            Console.WriteLine(point.Y);
        }
    }

    internal struct NewStruct {
        public int X;
        public int Y;

        public NewStruct(int x, int y) {
            X = x;
            Y = y;
        }

        public override bool Equals(object obj) {
            return obj is NewStruct other &&
                   X == other.X &&
                   Y == other.Y;
        }

        public override int GetHashCode() {
            return HashCode.Combine(X, Y);
        }

        public void Deconstruct(out int x, out int y) {
            x = X;
            y = Y;
        }

        public static implicit operator (int X, int Y)(NewStruct value) {
            return (value.X, value.Y);
        }

        public static implicit operator NewStruct((int X, int Y) value) {
            return new NewStruct(value.X, value.Y);
        }
    }
}
'''

### PR DESCRIPTION
**Pull request by davidwengier**
Fixes #45451 

When converting a tuple to a struct the casing was changed for the parameters of the generated constructor but the call sites weren't changed resulting in a compile error.

Reviewing commit-by-commit might be best, as there were a few analyzer warnings to clean up, but not enough that I thought it was worth a separate PR.

### CODE REVIEW

File: src/Features/CSharp/Portable/ConvertTupleToStruct/CSharpConvertTupleToStructCodeRefactoringProvider.cs [hunk 1]
```diff
@@ -32,5 +34,21 @@ internal class CSharpConvertTupleToStructCodeRefactoringProvider :
         public CSharpConvertTupleToStructCodeRefactoringProvider()
         {
         }
+
+        protected override ArgumentSyntax GetArgumentWithChangedName(ArgumentSyntax argument, string name)
+        {
+            return argument.WithNameColon(ChangeName(argument.NameColon, name));
+        }
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ConvertTupleToStruct/CSharpConvertTupleToStructCodeRefactoringProvider.cs:41]: nit

```suggestion
        protected override ArgumentSyntax GetArgumentWithChangedName(ArgumentSyntax argument, string name)
            =>  argument.WithNameColon(ChangeName(argument.NameColon, name));
```

File: src/Features/CSharp/Portable/ConvertTupleToStruct/CSharpConvertTupleToStructCodeRefactoringProvider.cs [hunk 2]
```diff
@@ -32,5 +34,21 @@ internal class CSharpConvertTupleToStructCodeRefactoringProvider :
...
+
+        private static NameColonSyntax? ChangeName(NameColonSyntax? nameColon, string name)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/ConvertTupleToStruct/CSharpConvertTupleToStructCodeRefactoringProvider.cs:43]: nit: i'd just call this `WithName`

File: src/Features/Core/Portable/ConvertTupleToStruct/AbstractConvertTupleToStructCodeRefactoringProvider.cs [hunk 3]
```diff
@@ -305,7 +305,7 @@ private static string GetTitle(Scope scope)
                     // We should only ever get a default array (meaning, update the root), or a
                     // non-empty array.  We should never be asked to update exactly '0' nodes.
                     Debug.Assert(documentToUpdate.NodesToUpdate.IsDefault ||
-                                 documentToUpdate.NodesToUpdate.Length >= 1);
+                                !documentToUpdate.NodesToUpdate.IsEmpty);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ConvertTupleToStruct/AbstractConvertTupleToStructCodeRefactoringProvider.cs:308]:
```suggestion
                                 !documentToUpdate.NodesToUpdate.IsEmpty);
```

File: src/Features/Core/Portable/ConvertTupleToStruct/AbstractConvertTupleToStructCodeRefactoringProvider.cs [hunk 4]
```diff
@@ -649,32 +649,38 @@ private static bool AreEquivalent(StringComparer comparer, INamedTypeSymbol tupl
...
+                var argumentName = generator.SyntaxFacts.GetNameForArgument(argument);
+                var newArgumentName = GetConstructorParameterName(argumentName);
+
+                return GetArgumentWithChangedName(argument, newArgumentName);
             }
 
             return (TArgumentSyntax)generator.Argument(expr).WithTriviaFrom(argument);
         }
 
+        protected abstract TArgumentSyntax GetArgumentWithChangedName(TArgumentSyntax argument, string name);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ConvertTupleToStruct/AbstractConvertTupleToStructCodeRefactoringProvider.cs:682]: nit: please place abstracts together.  ideally at the top, below the constructor.

File: src/Features/VisualBasic/Portable/ConvertTupleToStruct/VisualBasicConvertTupleToStructCodeRefactoringProvider.vb [hunk 5]
```diff
@@ -30,5 +30,26 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.ConvertTupleToStruct
...
+            If nameColonEquals Is Nothing Then
+                Return argument
+            End If
+
+            Return simpleArgument.WithNameColonEquals(ChangeName(nameColonEquals, name))
+        End Function
+
+        Private Shared Function ChangeName(nameColonEquals As NameColonEqualsSyntax, name As String) As NameColonEqualsSyntax
+            Dim newName = SyntaxFactory.IdentifierName(name).WithTriviaFrom(nameColonEquals.Name)
+            Return nameColonEquals.WithName(newName)
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/ConvertTupleToStruct/VisualBasicConvertTupleToStructCodeRefactoringProvider.vb:52]: can we keep the logic symettric with c#?  i.e. have ChangeName be null-resistent, and have GetArgumentWithChangedName just call it unilaterally?

File: src/Features/Core/Portable/ConvertTupleToStruct/AbstractConvertTupleToStructCodeRefactoringProvider.cs [hunk 6]
```diff
@@ -872,6 +878,9 @@ private static SyntaxNodeOrToken ConvertArgumentOrToken(SyntaxGenerator generato
             return constructor;
         }
 
+        private static string GetConstructorParameterName(string name)
+            => name.ToCamelCase(trimLeadingTypePrefix: false);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ConvertTupleToStruct/AbstractConvertTupleToStructCodeRefactoringProvider.cs:882]: note: technically this is not accurate.  while this is the norm (and def better than where we started from), this doesn't necessarily match the user's actual stated preference for their parameters.  i.e. a user could have a different naming style.  consider updating this to respect that style.

note: this is a not a blocker on the PR.  given that camel-case is likely correct for 95%+ of our users (and we were broken before anyways), it's totally fine to just get to this point and have us wait to see if anyone ever cares about the niche case of having a different parameter style *and* using this feature.

That said, it's likely worth a comment in the code that the above line is for expediency with teh common case, and not for correctness.

File: src/Features/Core/Portable/ConvertTupleToStruct/AbstractConvertTupleToStructCodeRefactoringProvider.cs (hunk 4 above)
Comment (davidwengier) [reply src/Features/Core/Portable/ConvertTupleToStruct/AbstractConvertTupleToStructCodeRefactoringProvider.cs:682]: There aren't any others to put this with, but below the constructor is good info, thanks :)

File: src/Features/CSharp/Portable/ConvertTupleToStruct/CSharpConvertTupleToStructCodeRefactoringProvider.cs (hunk 2 above)
Comment (davidwengier) [reply src/Features/CSharp/Portable/ConvertTupleToStruct/CSharpConvertTupleToStructCodeRefactoringProvider.cs:43]: I don't love `ChangeName`, but `WithName` looks odd not being an extension method, so going to leave this.

File: src/Features/Core/Portable/ConvertTupleToStruct/AbstractConvertTupleToStructCodeRefactoringProvider.cs (hunk 6 above)
Comment (davidwengier) [reply src/Features/Core/Portable/ConvertTupleToStruct/AbstractConvertTupleToStructCodeRefactoringProvider.cs:882]: I agree this isn't a blocker, which is why I left the existing behavior, but I definitely want to follow up on this, as its a pet peeve of mine when our code actions don't honour my settings. I just don't know how to do anything about it yet :)

**Comment by davidwengier** [comment]
Thanks for the review
