### PR TITLE
Fix issue with locating source method in optimized code...

### LINKED ISSUE #2406: Debug.Assert(false) fired at Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.CompilationContext.GetSubstitutedSourceMethod
This is on our current baseline drop with Roslyn signed build from April 23. Dump shared at: `\\manish-test\share_r\ExpressionEvaluator_Assert\expr_evaluator_assert.dmp`

Hit the below assert, causing all locals being un-evaluated: http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ExpressionCompiler/CompilationContext.cs,1440

`Debug.Assert(false, "Why didn't we find a substituted source method for " + candidateSubstitutedSourceMethod + "?");`

**Call stack:**
>	Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ExpressionCompiler.dll!Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.CompilationContext.GetSubstitutedSourceMethod(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol candidateSubstitutedSourceMethod, bool hasDisplayClassThis) Line 1440	C#
 	Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ExpressionCompiler.dll!Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.CompilationContext.ExtendBinderChain(Microsoft.CodeAnalysis.ExpressionEvaluator.InspectionContext inspectionContext, Microsoft.CodeAnalysis.CSharp.CSharpCompilation compilation, Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.MetadataDecoder metadataDecoder, Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode syntax, Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.EEMethodSymbol method, Microsoft.CodeAnalysis.CSharp.Binder binder, bool hasDisplayClassThis, bool methodNotType) Line 743	C#
 	Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ExpressionCompiler.dll!Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.CompilationContext.CompileExpression.AnonymousMethod__0(Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.EEMethodSymbol method, Microsoft.CodeAnalysis.DiagnosticBag diags) Line 134	C#
 	Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ExpressionCompiler.dll!Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.EEMethodSymbol.GenerateMethodBody(Microsoft.CodeAnalysis.CSharp.TypeCompilationState compilationState, Microsoft.CodeAnalysis.DiagnosticBag diagnostics) Line 395	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileSynthesizedMethods(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol> additionalTypes, Microsoft.CodeAnalysis.DiagnosticBag diagnostics) Line 569	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(Microsoft.CodeAnalysis.CSharp.CSharpCompilation compilation, Microsoft.CodeAnalysis.CSharp.Emit.PEModuleBuilder moduleBeingBuiltOpt, bool generateDebugInfo, bool hasDeclarationErrors, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, System.Predicate<Microsoft.CodeAnalysis.CSharp.Symbol> filterOpt, System.Threading.CancellationToken cancellationToken) Line 145	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CompileImpl(Microsoft.CodeAnalysis.Emit.CommonPEModuleBuilder moduleBuilder, System.IO.Stream win32Resources, System.IO.Stream xmlDocStream, bool generateDebugInfo, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, System.Predicate<Microsoft.CodeAnalysis.ISymbol> filterOpt, System.Threading.CancellationToken cancellationToken) Line 2371	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Compilation.Compile(Microsoft.CodeAnalysis.Emit.CommonPEModuleBuilder moduleBuilder, System.IO.Stream win32Resources, System.IO.Stream xmlDocStream, bool generateDebugInfo, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, System.Predicate<Microsoft.CodeAnalysis.ISymbol> filterOpt, System.Threading.CancellationToken cancellationToken) Line 1269	C#
 	Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ExpressionCompiler.dll!Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.CompilationContext.CompileExpression(Microsoft.CodeAnalysis.ExpressionEvaluator.InspectionContext inspectionContext, string typeName, string methodName, Microsoft.CodeAnalysis.CodeGen.CompilationTestData testData, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, out Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProperties resultProperties) Line 158	C#
 	Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.ExpressionCompiler.dll!Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.EvaluationContext.CompileExpression(Microsoft.CodeAnalysis.ExpressionEvaluator.InspectionContext inspectionContext, string expr, Microsoft.VisualStudio.Debugger.Evaluation.DkmEvaluationFlags compilationFlags, Microsoft.CodeAnalysis.DiagnosticBag diagnostics, out Microsoft.CodeAnalysis.ExpressionEvaluator.ResultProperties resultProperties, Microsoft.CodeAnalysis.CodeGen.CompilationTestData testData) Line 246	C#
 	Microsoft.CodeAnalysis.ExpressionEvaluator.ExpressionCompiler.dll!Microsoft.CodeAnalysis.ExpressionEvaluator.ExpressionCompiler.Microsoft.VisualStudio.Debugger.ComponentInterfaces.IDkmClrExpressionCompiler.CompileExpression.AnonymousMethod__1(Microsoft.CodeAnalysis.ExpressionEvaluator.EvaluationContextBase context, Microsoft.CodeAnalysis.DiagnosticBag diagnostics) Line 91	C#
 	Microsoft.CodeAnalysis.ExpressionEvaluator.ExpressionCompiler.dll!Microsoft.CodeAnalysis.ExpressionEvaluator.ExpressionCompiler.CompileWithRetry<Microsoft.CodeAnalysis.ExpressionEvaluator.ExpressionCompiler.CompileExpressionResult>(System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.ExpressionEvaluator.MetadataBlock> metadataBlocks, Microsoft.CodeAnalysis.DiagnosticFormatter formatter, Microsoft.CodeAnalysis.ExpressionEvaluator.ExpressionCompiler.CreateContextDelegate createContext, Microsoft.CodeAnalysis.ExpressionEvaluator.ExpressionCompiler.CompileDelegate<Microsoft.CodeAnalysis.ExpressionEvaluator.ExpressionCompiler.CompileExpressionResult> compile, Microsoft.CodeAnalysis.ExpressionEvaluator.DkmUtilities.GetMetadataBytesPtrFunction getMetaDataBytesPtr, out string errorMessage) Line 304	C#
 	Microsoft.CodeAnalysis.ExpressionEvaluator.ExpressionCompiler.dll!Microsoft.CodeAnalysis.ExpressionEvaluator.ExpressionCompiler.CompileWithRetry<Microsoft.CodeAnalysis.ExpressionEvaluator.ExpressionCompiler.CompileExpressionResult>(Microsoft.VisualStudio.Debugger.Clr.DkmClrModuleInstance moduleInstance, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.ExpressionEvaluator.MetadataBlock> metadataBlocks, Microsoft.CodeAnalysis.ExpressionEvaluator.ExpressionCompiler.CreateContextDelegate createContext, Microsoft.CodeAnalysis.ExpressionEvaluator.ExpressionCompiler.CompileDelegate<Microsoft.CodeAnalysis.ExpressionEvaluator.ExpressionCompiler.CompileExpressionResult> compile, out string errorMessage) Line 278	C#
 	Microsoft.CodeAnalysis.ExpressionEvaluator.ExpressionCompiler.dll!Microsoft.CodeAnalysis.ExpressionEvaluator.ExpressionCompiler.Microsoft.VisualStudio.Debugger.ComponentInterfaces.IDkmClrExpressionCompiler.CompileExpression(Microsoft.VisualStudio.Debugger.Evaluation.DkmLanguageExpression expression, Microsoft.VisualStudio.Debugger.Clr.DkmClrInstructionAddress instructionAddress, Microsoft.VisualStudio.Debugger.Evaluation.DkmInspectionContext inspectionContext, out string error, out Microsoft.VisualStudio.Debugger.Evaluation.ClrCompilation.DkmCompiledClrInspectionQuery result) Line 84	C#
 	Microsoft.VisualStudio.Debugger.Engine.dll!Microsoft.VisualStudio.Debugger.EntryPoint.IDkmClrExpressionCompiler_CompileExpression(System.IntPtr pvClassInfo, System.IntPtr Expression, System.IntPtr InstructionAddress, System.IntPtr InspectionContext, ref System.IntPtr Error, ref System.IntPtr Result)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.VisualStudio.Debugger.Engine.dll!Microsoft.VisualStudio.Debugger.Evaluation.DkmLanguageExpression.CompileExpression(Microsoft.VisualStudio.Debugger.Clr.DkmClrInstructionAddress InstructionAddress, Microsoft.VisualStudio.Debugger.Evaluation.DkmInspectionContext InspectionContext, out string Error, out Microsoft.VisualStudio.Debugger.Evaluation.ClrCompilation.DkmCompiledClrInspectionQuery Result)	Unknown
 	vsdebugeng.manimpl.dll!VSDebugEngine.ManagedEE.EntryPoint.Microsoft.VisualStudio.Debugger.ComponentInterfaces.IDkmLanguageExpressionEvaluator.EvaluateExpression(Microsoft.VisualStudio.Debugger.Evaluation.DkmInspectionContext inspectionContext, Microsoft.VisualStudio.Debugger.DkmWorkList workList, Microsoft.VisualStudio.Debugger.Evaluation.DkmLanguageExpression expression, Microsoft.VisualStudio.Debugger.CallStack.DkmStackWalkFrame stackFrame, Microsoft.VisualStudio.Debugger.DkmCompletionRoutine<Microsoft.VisualStudio.Debugger.Evaluation.DkmEvaluateExpressionAsyncResult> completionRoutine)	Unknown
 	Microsoft.VisualStudio.Debugger.Engine.dll!Microsoft.VisualStudio.Debugger.EntryPoint.IDkmLanguageExpressionEvaluator_EvaluateExpression(System.IntPtr pvClassInfo, System.IntPtr InspectionContext, System.IntPtr WorkList, System.IntPtr Expression, System.IntPtr StackFrame, System.IntPtr CompletionRoutine)	Unknown

### PR DESCRIPTION
**Pull request by KevinH-MS**
We were previously assuming that "this" was always hoisted in async/iterator state machines.  This is not true in optimized code.

(fixes #2406)

### CODE REVIEW

**Comment by KevinH-MS** [comment]
FYI @amcasey @cston @ManishJayaswal

**Comment by KevinH-MS** [comment]
Note:  The change in VB doesn't seem to be required (VB doesn't optimize away the display class field), but it seemed like it was better to be safe than sorry here (just in case we do ever decide to optimize).

File: src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs [hunk 1]
```diff
@@ -1484,14 +1484,10 @@ private static NamedTypeSymbol GetNonDisplayClassContainer(NamedTypeSymbol type)
...
-                // because then "this" is hoisted unconditionally.
-                var isDesiredMethodStatic = hasDisplayClassThis
-                    ? ThreeState.False
-                    : (GeneratedNames.GetKind(candidateSubstitutedSourceType.Name) == GeneratedNameKind.StateMachineType)
-                        ? ThreeState.True
-                        : ThreeState.Unknown;
+                // a Roslyn lambda that only captures "this" and a Dev12 lambda that captures nothing
+                // (neither introduces a display class).  Also, "this" may be optimized away in async
+                // or iterator state machines.
+                var isDesiredMethodStatic = hasDisplayClassThis ? ThreeState.False : ThreeState.Unknown;
```
Comment (amcasey) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs]: Technically, this no longer needs to be a ThreeState.  I'm not sure what that means for consistency.

File: src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/HoistedThisTests.cs [hunk 2]
```diff
@@ -950,11 +949,22 @@ static int P
...
-            var comp = CreateCompilationWithMscorlib45(source, options: TestOptions.DebugDll, assemblyName: ExpressionCompilerUtilities.GenerateUniqueName());
-            var runtime = CreateRuntimeInstance(comp);
+            var sourceCompilation = CreateCompilationWithMscorlib45(source, options: TestOptions.DebugDll, assemblyName: ExpressionCompilerUtilities.GenerateUniqueName());
+            var runtime = CreateRuntimeInstance(sourceCompilation);
             var context = CreateMethodContext(runtime, methodName);
 
             VerifyHasThis(context, expectedType, expectedIL);
+
+            // Now recompile and test CompileExpression with optimized code.
+            sourceCompilation = sourceCompilation.WithOptions(sourceCompilation.Options.WithOptimizationLevel(OptimizationLevel.Release));
```
Comment (amcasey) [inline src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/HoistedThisTests.cs]: I think it would be better to pass an additional flag indicating whether ```this``` is expected to be present in release builds.  If so, confirm that it is (with IL, if possible).  Otherwise, compile ```1``` as a sanity check.

**Comment by amcasey** [comment]
Personally, I would find it reassuring to see a test where we assert that ```this``` is optimized away.

**Comment by amcasey** [comment]
LGTM, with comments.

File: src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs (hunk 1 above)
Comment (KevinH-MS) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs]: Yeah, I considered whether to make it a bool, but decided that using "ThreeState.Unknown" expressed the intent more clearly.  I could certainly remove "need to" from the comment though.

File: src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/HoistedThisTests.cs (hunk 2 above)
Comment (KevinH-MS) [inline src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/HoistedThisTests.cs]: Makes sense.  I will add an additional check.

File: src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs (hunk 1 above)
Comment (cston) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs]: Could 'isDesiredMethodStatic' be renamed so bool makes sense? Perhaps something like 'mustBeInstanceMethod'.

Comment (amcasey) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs]: I was going to suggest the same.  You could make it a bool and rename it.

Comment (KevinH-MS) [inline src/ExpressionEvaluator/CSharp/Source/ExpressionCompiler/CompilationContext.cs]: Okay, you've persuaded me. :)  Will change.

File: src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/HoistedThisTests.cs (hunk 2 above)
Comment (KevinH-MS) [inline src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/HoistedThisTests.cs]: Note: In all of the cases that we currently test, "this" is optimized away, so I didn't add a flag.

File: src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/HoistedThisTests.cs [hunk 3]
```diff
@@ -950,11 +949,26 @@ static int P
...
+            runtime = CreateRuntimeInstance(sourceCompilation);
+            context = CreateMethodContext(runtime, methodName);
+            string error;
+            var testData = new CompilationTestData();
+            // In C#, "this" will be optimized away.
+            context.CompileExpression("this", out error, testData);
+            Assert.NotNull(error);
```
Comment (amcasey) [inline src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/HoistedThisTests.cs]: Would VerifyNoThis work?

Comment (KevinH-MS) [inline src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/HoistedThisTests.cs]: Yes, good point.  No need to duplicate.

File: src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/HoistedThisTests.cs (hunk 2 above)
Comment (KevinH-MS) [inline src/ExpressionEvaluator/CSharp/Test/ExpressionCompiler/HoistedThisTests.cs]: Hmmm...must be getting sloppy (I wasn't running the tests I thought I was).  After latest changes, I realized that I do need a flag (there are cases in the C# tests where "this" isn't optimized away).  Added...
