### PR TITLE
Check NotNullIfNotNull in implementation

### LINKED ISSUE #44539: Invalid NotNullIfNotNull contract is not reported
**Version Used**: https://github.com/dotnet/roslyn/commit/ab680e7d4afb50003b487c28aeb7fcb7c89fd7fe

**Steps to Reproduce**:

```cs
using System.Diagnostics.CodeAnalysis;
#nullable enable
public class C {
    public void Main()
    {
        M1(new()).ToString();
        M2(new()).ToString();
        
        M1(null).ToString();
        M2(null).ToString();
    }
    
    [return: NotNullIfNotNull("p")]
    public object? M1(object? p) {
        if (p is null) return null;
        return Nullable(); // no warnings (one expected)
    }
    
    [return: NotNullIfNotNull("p")]
    public object? M2(object? p) {
        if (p is null) return null;
        return M1(p); // no warnings (correct)
    }
    
    object? Nullable() {return null;}
}
```
([sharplab repro](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8A+AAgAwAEhAjAHQAimEA5gHYD2smAxlFQMIsAmcAIJMIAG1xRMUANwBYAFABiJgFcxYiMDFxScUdriLCAZnIAmUj1IBvRaQfkzhACykAshExMAFAEp7RzsFR1CPCh8mOAB3fz8qABUWAGUYBG8Gf3kQsId3c0iYuMSUtIyswNzKsPcItQ14pNT0pky/bNy8gvqxRtKWto7HAF9q6oBtQgB2EFIAORYYOfUxAElsBaWVnwAiAAcdvwBdatNSFmAAKzgOGAB+cJ8L69uHvb9batCcUh890mkpB6H2mQJWQ1yoOWGi0OiypAA9AigSxSNEIAgmBkoL8WFE9AAPPY3eD8AI5ByjCmkCbTWabaFrDaLRm7A7HU5mZ4kh75J5XHmkd6fanfbC/f6A4HkKZgjQQsKg2p/dqI5GsNEYrGtHE+DgsBAIEnk0JU0LVbmveYrWFwfy2UE9GRU4ZAA=))

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #44539

VS validation: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/274873

### CODE REVIEW

**Comment by jcouv** [comment]
The local rewriter warning should be fixed by annotating `VisitExpressionImpl` with `NotNullIfNotNull`.
The `CSharpSyntaxRewriter.cs` one needs a bit  more validation. Can we rewrite to null? If not, then an assertion would do the trick.

**Comment by RikkiGibson** [comment]
> The local rewriter warning should be fixed by annotating VisitExpressionImpl with NotNullIfNotNull.

I think this might not be right, because VisitExpressionImpl's parameter has a non-null type, and adding the attribute introduces a different warning:

`src\Compilers\CSharp\Portable\Lowering\LocalRewriter\LocalRewriter.cs(232,13): warning CS8825: Return value must be non-null because parameter 'node' is non-null.`

I think something about the Debug.Assert is giving the `visited` a maybe-null state afterwards. Perhaps the pure null check?

**Comment by RikkiGibson** [comment]
I have opened a tracking issue #47682 and have suppressed the new warnings, since "proper" fixes for the warnings seem non-trivial.

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler Please review

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler Please review

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler Please review

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 1]
```diff
@@ -33431,6 +33759,12 @@ void M4([NotNull]out int? x)
     {
         return null; // 3
     }
+
+    void M7([NotNull]out int? x)
+    {
+        x = null;
+        return; // 4
+    }
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:33767]: Please add a few cases for constructors where the only code in the method is a `:this` call to another constructor and verify that we validate not-null correctly in those cases.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 2]
```diff
@@ -883,6 +883,36 @@ int getSlotForFieldOrPropertyOrEvent(Symbol member)
...
+            if (inputParamNames.IsEmpty)
+            {
+                return;
+            }
+
+            foreach (var inputParam in this.MethodParameters)
+            {
+                if (inputParamNames.Contains(inputParam.Name)
+                    && outputState.MayBeNull()
+                    && GetOrCreateSlot(inputParam) is > 0 and int inputSlot
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:897]: Yeah I think that will end up doing the same thing.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 3]
```diff
@@ -780,11 +780,24 @@ void enforceNotNull(SyntaxNode? syntaxOpt, LocalState state)
...
                 foreach (var parameter in this.MethodParameters)
                 {
-                    if (parameterHasBadState(parameter, state))
+                    var slot = GetOrCreateSlot(parameter);
+                    if (slot <= 0)
+                    {
+                        continue;
+                    }
+
+                    var annotations = parameter.FlowAnalysisAnnotations;
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:789]: This code was moved from `parameterHasBadState` below. However `GetFlowAnalysisAnnotations(Symbol)` here would just dispatch out to `ParameterSymbol.FlowAnalysisAnnotations`.

It could make sense to change this to `GetParameterAnnotations` in order to avoid attribute binding cycles. Since I can't come up with a crashing scenario for this off the top of my head I would like to punt changes to it to #47635

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 4]
```diff
@@ -883,6 +883,36 @@ int getSlotForFieldOrPropertyOrEvent(Symbol member)
...
+        {
+            if (inputParamNames.IsEmpty)
+            {
+                return;
+            }
+
+            foreach (var inputParam in this.MethodParameters)
+            {
+                if (inputParamNames.Contains(inputParam.Name)
+                    && outputState.MayBeNull()
```
Comment (cston) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:896]: >outputState.MayBeNull() [](start = 23, length = 23)

Can we check this once, before the loop?

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 5]
```diff
@@ -27590,6 +27590,334 @@ static void M(C c, string? p1, string? p2)
...
+                Diagnostic(ErrorCode.WRN_ReturnNotNullIfNotNull, "return null;", isSuppressed: false).WithArguments("p").WithLocation(23, 13),
+                // (23,13): warning CS8824: Parameter 'pOut' must have a non-null value when exiting because parameter 'p' is non-null.
+                //             return null; // 3, 4
+                Diagnostic(ErrorCode.WRN_ParameterNotNullIfNotNull, "return null;", isSuppressed: false).WithArguments("pOut", "p").WithLocation(23, 13),
+                // (33,9): warning CS8825: Return value must be non-null because parameter 'p' is non-null.
+                //         return pOut; // 5, 6
+                Diagnostic(ErrorCode.WRN_ReturnNotNullIfNotNull, "return pOut;", isSuppressed: false).WithArguments("p").WithLocation(33, 9),
+                // (33,9): warning CS8824: Parameter 'pOut' must have a non-null value when exiting because parameter 'p' is non-null.
+                //         return pOut; // 5, 6
+                Diagnostic(ErrorCode.WRN_ParameterNotNullIfNotNull, "return pOut;", isSuppressed: false).WithArguments("pOut", "p").WithLocation(33, 9));
```
[the remark this answers is not in the document]
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:27918]: Thanks, this caught a bug.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 6]
```diff
@@ -27557,7 +27557,7 @@ void M(string? s)
         [Fact]
         public void NotNullIfNotNull_Return()
         {
-            // NotNullIfNotNull isn't enforced within method bodies
+            // NotNullIfNotNull isn't enforced in scenarios like the following
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:27560]: >// NotNullIfNotNull isn't enforced in scenarios like the following [](start = 12, length = 66)

nit: the comment probably should be removed. Since parameter `p` is maybe-null upon exit, the problem isn't that we didn't enforce NotNullIfNotNull.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:33767]: I wasn't sure exactly what this meant--do you want tests where constructor parameters have `[NotNull]` and `[NotNullIfNotNull]`?

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 6 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:27560]: I guess the comment is saying: if our analysis were more rigorous, we would warn here. But we can't distinguish scenarios like the following, so we don't warn in either place:

```cs
[return: NotNullIfNotNull("x")]
X? M1(X? x) => null; // ideally would warn here--what if 'x' actually contains not-null?

[return: NotNullIfNotNull("x")]
X? M2(X? x)
{
    if (x is null)
    {
        return null; // shouldn't warn here--'x' is always null.
    }

    return x;
}
```

Comment (jcouv) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:27560]: Thanks for the clarification. Makes sense

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 4 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Done

**Review by cston — APPROVED** [review]

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 7]
```diff
@@ -27918,6 +27918,233 @@ public class C
...
+        }
+
+        [Fact, WorkItem(44539, "https://github.com/dotnet/roslyn/issues/44539")]
+        public void NotNullIfNotNull_Constructor()
+        {
+            var source = @"
+using System.Diagnostics.CodeAnalysis;
+public class C
+{
+    public C(string? p, [NotNullIfNotNull(""p"")] string? pOut)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28112]: Note: was looking for cases where a ctor chains into another ctor via `:this`.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28112]: I added a few tests like this, but I'm not certain that it was what you were looking for. Let me know what you think.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 8]
```diff
@@ -28145,6 +28145,92 @@ public C(string? p, [NotNullIfNotNull(""p"")] string? pOut)
...
+
+    public C(string? p, [NotNullIfNotNull(""p"")] out string? pOut) { pOut = p; }
+}
+";
+            var comp = CreateNullableCompilation(new[] { source, NotNullIfNotNullAttributeDefinition });
+            comp.VerifyDiagnostics();
+        }
+
+        [Fact, WorkItem(44539, "https://github.com/dotnet/roslyn/issues/44539")]
+        public void NotNull_Constructor()
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs:28213]: This test uncovered a problem where the NotNull diagnostic would be given once in the "initializers" pass, and again in the "body" pass. Hence the implementation change.

**Review by jaredpar — APPROVED** [review]

**Comment by RikkiGibson** [comment]
Changing base so we can get this change into 16.8.
