### PR TITLE
Do not apply SuppressMessage suppressions to compiler diagnostics

### LINKED ISSUE #39094: SuppressMessage works in IDE but still produces warnings in build output
**Version Used**: 
VS 16.3.2
**Steps to Reproduce**:

1. Create new c# .net core Console Project with following code
   ```c#
    using System;
  
    namespace ConsoleApp2
    {
        class Program
        {
            private string test;
    
            static void Main(string[] args)
            {
                var p = new Program() { test = "bl" };
                Console.WriteLine("Hello World!" + p.test);
            }
        }
    }

   ```
2. Enable nullable in `.csproj` (field `test` will show green squigles with non initilized non-nullable warning)
3.  Add Gloabl suppression file with
  ```c#
  [assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "CS8618:Non-nullable field is uninitialized. Consider declaring as nullable.", Justification = "<Pending>", Scope = "member", Target = "~F:ConsoleApp2.Program.test")]
  ```
  (warning in source code will vanish)

**Expected Behavior**:

Bild shows no warnings

**Actual Behavior**:
Build shows warning  `Program.cs(7,24,7,28): warning CS8618: Non-nullable field 'test' is uninitialized. Consider declaring the field as nullable.`

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #39094
Verified that added unit test fails prior to the fix.

### CODE REVIEW

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/SuppressMessageAttributeState.cs [hunk 1]
```diff
@@ -197,6 +200,19 @@ bool hasNamespaceSuppression(INamespaceSymbol namespaceSymbol, bool inImmediatel
 
                 return false;
             }
+
+            static bool isCompilerDiagnostic(Diagnostic diagnostic)
+            {
+                foreach (var customTag in diagnostic.CustomTags)
```
Comment (CyrusNajmabadi) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/SuppressMessageAttributeState.cs]: how does IReadOnlyList not have a .Contains method...

Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/SuppressMessageAttributeState.cs]: Sure, will just inline.

**Comment by mavasani** [comment]
@dotnet/roslyn-compiler for reviews.

File: src/Compilers/CSharp/Test/Semantic/Diagnostics/GetDiagnosticsTests.cs [hunk 2]
```diff
@@ -420,5 +420,43 @@ public void GettingDeclarationDiagnosticsForATreeShouldNotFreezeCompilation()
...
+            effectiveDiagnostics.Verify(expected);
+            Assert.False(effectiveDiagnostics.Single().IsSuppressed);
+
+            // Verify CS0168 is not suppressed for compiler diagnostics computed
+            // using CompilerDiagnosticAnalyzer
+            var analyzers = new DiagnosticAnalyzer[] { new CSharpCompilerDiagnosticAnalyzer() };
+            var analyzerDiagnostics = compilation.GetAnalyzerDiagnostics(analyzers);
+            analyzerDiagnostics.Verify(expected);
+            Assert.False(analyzerDiagnostics.Single().IsSuppressed);
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Diagnostics/GetDiagnosticsTests.cs]: >} [](start = 8, length = 1)

When does `SuppressMessage()` suppress the diagnostic? Can we include that case here as well?

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/SuppressMessageAttributeState.cs (hunk 1 above)
Comment (cston) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/SuppressMessageAttributeState.cs]: Agreed, we should use `System.Linq.Enumerable.Contains()` or some equivalent.

Comment (sharwell) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/SuppressMessageAttributeState.cs]: I would prefer to use a `for` loop with indexing to avoid enumerator allocations.

Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/SuppressMessageAttributeState.cs]: Thanks, I added an extension method with the implementation using a for loop.

File: src/Compilers/CSharp/Test/Semantic/Diagnostics/GetDiagnosticsTests.cs (hunk 2 above)
Comment (mavasani) [reply src/Compilers/CSharp/Test/Semantic/Diagnostics/GetDiagnosticsTests.cs]: Yes, and we do have large number of SuppressMessageAttribute tests for analyzer diagnostics [here](http://sourceroslyn.io/#Roslyn.Test.Utilities/Diagnostics/SuppressMessageAttributeTests.cs,752ca1059dcd2143).

**Comment by mavasani** [comment]
@dotnet/roslyn-compiler for an additional review.

**Comment by mavasani** [comment]
@dotnet/roslyn-compiler for an additional review.

**Comment by mavasani** [comment]
Thanks @jcouv @cston
