### PR TITLE
Fix property parsing when it contains parantheses

### LINKED ISSUE #48587: Problem on VB.net compiler with property,when no "As" keyword specified (.NET 4.8)
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1186116/problem-on-vbnet-compiler-with-propertywhen-no-as.html)._

---
[severity:It bothers me. A fix would be nice]
With VB.net 4.8 (Haven't tried any other version)
When, Option Strict is set to OFF;

It turns out this compile, without any error nor warning;

```
Public ReadOnly Property NumberOfResult() String Integer JohnDoe WwwIIWww Wow
  Get
    Return Me.mList.Count()
  End Get
End Property
```

I typed too quickly "As" and it switch it for String instead. 
But the property is then returning "Object", not string, either Integer and even not JohnDoe (which was nothing in my code, not even a class. I just type something not existing. You can in fact type whatever you want here).

---
#### Feedback Bot on 9/16/2020, 00:07 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #48587

### CODE REVIEW

File: src/Compilers/VisualBasic/Portable/Parser/Parser.vb [hunk 1]
```diff
@@ -4186,7 +4186,11 @@ checkNullable:
                 ' TODO - GreenSepList knows its error count. Expose it instead of recomputing it.
                 If propertyParameters.Count = 0 Then
                     Dim unexpected = ResyncAt({SyntaxKind.AsKeyword, SyntaxKind.ImplementsKeyword, SyntaxKind.EqualsToken})
-                    closeParen = closeParen.AddTrailingSyntax(unexpected)
+                    If unexpected.Count > 0 Then
+                        closeParen = closeParen.AddTrailingSyntax(unexpected, ERRID.ERR_ExpectedEOS)
+                    Else
+                        closeParen = closeParen.AddTrailingSyntax(unexpected)
```
Comment (Youssef1313) [inline src/Compilers/VisualBasic/Portable/Parser/Parser.vb:4192]: This was *silently* adding unexpected tokens as skipped trivia.

File: src/Compilers/VisualBasic/Portable/Parser/Parser.vb [hunk 2]
```diff
@@ -4186,7 +4186,11 @@ checkNullable:
                 ' TODO - GreenSepList knows its error count. Expose it instead of recomputing it.
                 If propertyParameters.Count = 0 Then
                     Dim unexpected = ResyncAt({SyntaxKind.AsKeyword, SyntaxKind.ImplementsKeyword, SyntaxKind.EqualsToken})
-                    closeParen = closeParen.AddTrailingSyntax(unexpected)
+                    If unexpected.Count > 0 Then
+                        closeParen = closeParen.AddTrailingSyntax(unexpected, ERRID.ERR_ExpectedEOS)
```
Comment (333fred) [inline src/Compilers/VisualBasic/Portable/Parser/Parser.vb:4190]: Might be better as an error that indicates `As` was expected? @AlekseyTs, do you have thoughts?

Comment (Youssef1313) [reply src/Compilers/VisualBasic/Portable/Parser/Parser.vb:4190]: @333fred I kept the same behavior as the native compiler as it will/should be consistent with other similar cases.

Comment (333fred) [reply src/Compilers/VisualBasic/Portable/Parser/Parser.vb:4190]: Alright, that's enough reason for me.

File: src/Compilers/VisualBasic/Test/Syntax/Parser/ParserRegressionTests.vb [hunk 3]
```diff
@@ -934,4 +934,15 @@ End Enum
         Assert.Equal(Syntax.InternalSyntax.Scanner.BadTokenCountLimit, tree.GetDiagnostics().Where(Function(d) d.Code = ERRID.ERR_IllegalChar).Count())
     End Sub
 
+    <Fact, WorkItem(48587, "https://github.com/dotnet/roslyn/issues/48587")>
+    Public Sub ParseTrailingTextAfterPropertyWithParentheses()
+        ParseAndVerify(<![CDATA[
+Class C
+    Public ReadOnly Property NumberOfResult() String Integer JohnDoe WwwIIWww Wow
```
Comment (333fred) [inline src/Compilers/VisualBasic/Test/Syntax/Parser/ParserRegressionTests.vb:941]: Can you add some variants on this test where we have the possible resync points? Ie, some garbage before the `As`, `=`, or `Implements` keywords.

File: src/Compilers/VisualBasic/Portable/Parser/Parser.vb (hunk 1 above)
Comment (Youssef1313) [inline src/Compilers/VisualBasic/Portable/Parser/Parser.vb:4192]: After giving a second look, this `Else` feels redundant.

File: src/Compilers/VisualBasic/Test/Syntax/Parser/ParserRegressionTests.vb (hunk 3 above)
Comment (Youssef1313) [reply src/Compilers/VisualBasic/Test/Syntax/Parser/ParserRegressionTests.vb]: @333fred Thanks. I extended the test.

File: src/Compilers/VisualBasic/Portable/Parser/Parser.vb (hunk 1 above)
Comment (333fred) [reply src/Compilers/VisualBasic/Portable/Parser/Parser.vb:4192]: Yeah, it does doesn't it :)

**Review by 333fred — APPROVED** [review]
LGTM with the redundant else removed.

**Comment by 333fred** [comment]
@dotnet/roslyn-compiler for a second review.

File: src/Compilers/VisualBasic/Test/Syntax/Parser/ParserRegressionTests.vb [hunk 4]
```diff
@@ -934,4 +934,17 @@ End Enum
...
+    <Fact, WorkItem(48587, "https://github.com/dotnet/roslyn/issues/48587")>
+    Public Sub ParseTrailingTextAfterPropertyWithParentheses()
+        ParseAndVerify(<![CDATA[
+Class C
+    Public ReadOnly Property NumberOfResult1() String Integer JohnDoe WwwIIWww Wow
+    Public ReadOnly Property NumberOfResult2() Some unexpected tokens As Integer
+End Class
+]]>,
+<errors>
+    <error id="30205"/>
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Syntax/Parser/ParserRegressionTests.vb:946]: ><error id="30205"/> [](start = 4, length = 19)

Please switch to form of the test that can use AssertTheseDiagnostics helper (or the like), so that we could see the text of the error and its location

File: src/Compilers/VisualBasic/Test/Syntax/Parser/ParserRegressionTests.vb [hunk 5]
```diff
@@ -934,4 +934,17 @@ End Enum
         Assert.Equal(Syntax.InternalSyntax.Scanner.BadTokenCountLimit, tree.GetDiagnostics().Where(Function(d) d.Code = ERRID.ERR_IllegalChar).Count())
     End Sub
 
+    <Fact, WorkItem(48587, "https://github.com/dotnet/roslyn/issues/48587")>
+    Public Sub ParseTrailingTextAfterPropertyWithParentheses()
+        ParseAndVerify(<![CDATA[
+Class C
+    Public ReadOnly Property NumberOfResult1() String Integer JohnDoe WwwIIWww Wow
+    Public ReadOnly Property NumberOfResult2() Some unexpected tokens As Integer
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Syntax/Parser/ParserRegressionTests.vb:942]: >Some unexpected tokens As Integer [](start = 47, length = 33)

Please also test with a comment at the end of the line, line continuation and line continuation followed by a comment.

File: src/Compilers/VisualBasic/Portable/Parser/Parser.vb [hunk 6]
```diff
@@ -4186,7 +4186,9 @@ checkNullable:
...
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Portable/Parser/Parser.vb:4190]: >closeParen = closeParen.AddTrailingSyntax(unexpected, ERRID.ERR_ExpectedEOS) [](start = 24, length = 76)

I am not sure if the ResyncAt above is necessary and, as a consequence, whether this special error handling is necessary as well. First, I do not see us doing similar things in other places where ```ParseParameters``` is used. Second, at the very least the condition for the resync is questionable, zero parameters doesn't indicate any error situation on its own, therefore, we shouldn't be resyncing just because of that (resync is an attempt to recover from an error). Third, it looks like this declaration with parameters ```Public ReadOnly Property NumberOfResult3(x as Integer)  String Integer JohnDoe WwwIIWww Wow``` is parsed as expected and an appropriate error is reported. So, it feels like we are simply duplicating the work that is done elsewhere.

Comment (Youssef1313) [reply src/Compilers/VisualBasic/Portable/Parser/Parser.vb:4190]: @AlekseyTs That's very reasonable. But I can't continue debugging to get to the better solution. I can't open the compilers solution on my current machine due to very low specs. (I was working on an Azure VM, for which my subscription has ended :cry:)

Comment (Youssef1313) [reply src/Compilers/VisualBasic/Portable/Parser/Parser.vb]: I removed the resync in a draft PR and CI passed. So applying the change here and will see whether the new test will pass or not..

**Comment by Youssef1313** [comment]
@fred333 @AlekseyTs Can you give this another look?

**Comment by AlekseyTs** [comment]
@Youssef1313 It looks like `Microsoft.CodeAnalysis.VisualBasic.UnitTests.ParserRegressionTests.ParseTrailingTextAfterPropertyWithParentheses` test is failing

File: src/Compilers/VisualBasic/Test/Syntax/Parser/ParserRegressionTests.vb [hunk 7]
```diff
@@ -934,4 +934,29 @@ End Enum
...
+    <Fact, WorkItem(48587, "https://github.com/dotnet/roslyn/issues/48587")>
+    Public Sub ParseTrailingTextAfterPropertyWithParentheses()
+        Dim compilation = CompilationUtils.CreateCompilationWithMscorlib40(
+<compilation name="ParseTrailingTextAfterPropertyWithParentheses">
+    <file name="a.b">
+Class C
+    Public ReadOnly Property NumberOfResult1() String Integer JohnDoe WwwIIWww Wow
+    Public ReadOnly Property NumberOfResult2() Some unexpected tokens As Integer
+
+    Public ReadOnly Property NumberOfResult3() ' With comment - no errors.
```
Comment (333fred) [inline src/Compilers/VisualBasic/Test/Syntax/Parser/ParserRegressionTests.vb:946]: Can you please also add a version with bad text in between the parens and the comment/line continuation below?

**Review by 333fred — APPROVED** [review]

**Review by AlekseyTs — APPROVED** [review]
LGTM (iteration 11)

**Comment by AlekseyTs** [comment]
@Youssef1313 Thanks for the contribution!
