### PR TITLE
Test/fix scoping of pattern variables in expression-bodied functions and properties.

### LINKED ISSUE #8810: Scoping for pattern variables in an expression-bodied local function
We should (implement if necessary and) test the correctness of pattern variables defined at the top level of a local function

```cs
public static void Main(string[] args)
{
    bool Three(object o) => o is int i && i == 3;
}
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #8810.
Related to #8816.

@gafter, @jaredpar, @dotnet/roslyn-compiler Please review.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs [hunk 1]
```diff
@@ -215,11 +221,16 @@ private Binder GetEnclosingBinder(CSharpSyntaxNode node, int position)
                         binder = RootBinder.GetBinder(current);
                     }
                 }
+                else if (current.Kind() == SyntaxKind.ArrowExpressionClause && current.Parent?.Kind() == SyntaxKind.LocalFunctionStatement)
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs]: Nit: It looks like this block and the one above it could be combined.

File: src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs [hunk 2]
```diff
@@ -1549,7 +1549,7 @@ private static BoundBlock BindMethodBody(MethodSymbol method, TypeCompilationSta
                     binder = new ExecutableCodeBinder(arrowExpression, sourceMethod, binder);
                     importChain = binder.ImportChain;
                     // Add locals
-                    return binder.BindExpressionBodyAsBlock(arrowExpression, diagnostics);
+                    return binder.WithPatternVariablesIfAny(arrowExpression.Expression).BindExpressionBodyAsBlock(arrowExpression, diagnostics);
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs]: Do we ever bind an expression body without the pattern variables? I'm wondering if we could fold this logic directly into the `BindExpressionBodyAsBlock` helper.

**Comment by agocke** [comment]
:+1:

File: src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compilation/MemberSemanticModel.cs]: I don't think it will make code easier to understand. In fact, I believe it will make it much harder to understand.

File: src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs (hunk 2 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs]: If you look at the change made in src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs, you'll notice that I explicitly removed the behavior that you are suggesting. The reason is that the binder must be available to the SemanticModel in order for it (the model) to understand the scope tracked by the binder. Creating and dropping the binder on the fly doesn't work well in this case.

**Comment by AlekseyTs** [comment]
Test prtest/mac/dbg/unit32 please.

File: src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs (hunk 2 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Compiler/MethodCompiler.cs]: Ah yes, forgot about the semantic model. :+1:

**Comment by gafter** [comment]
LGTM
