### PR TITLE
Don't crash when invoking signature help on an inaccessible item.

### LINKED ISSUE #4144: Invoking signature help on an inaccessible item can cause a crash.
Bug reported by an external customer.

Place the cursor at '$$' and type a left paren '(':

``` C#
using System.Collections.Generic;

class A
{
    List<int> args = new List<int>();
}

class B : A
{
    void M()
    {
        args.Add$$
    }
}
```

Offending site: [InvocationExpressionSignatureHelpProvider.GetMethodGroupItems()](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.EditorFeatures/SignatureHelp/InvocationExpressionSignatureHelpProvider_MethodGroup.cs,819f5f9b3568db09)

### PR DESCRIPTION
**Pull request by brettfo**
Fixes #4144.

As reported by a customer, when attempting to show signature help on an inaccessible item can cause a crash.  The fix is: when checking if we're looking for instance members, also consider the containing type of the invocation expression, not just if it's name is visible.

**Question for reviewers:**
Consider the following code (taken from the unit test):

``` C#
class A
{
    List<int> args;
}

class B : A
{
    void M()
    {
        args.Add$$
    }
}
```

There is no crash in VB, but the `args` symbol also doesn't bind to begin with, like it does in C#.  Given this scenario it can either be argued that when the user typed `args` they knew exactly what they were doing and they intend to update the definition of `args` to be `public` or `protected`, *or*, they were unaware of the private field and they might be surprised by the completion/sig-help sessions that follow the dot.  Thoughts?

As it stands now, `Add(int item)` appears in the completion list after typing the dot in C#, but nothing appears in VB.

**Edit**
After digging in a bit, VB _does_ show the appropriate completion items, but I wasn't originally seeing that due to some unnoticed changes on my box.

### CODE REVIEW

**Comment by brettfo** [comment]
Tagging for review: @Pilchie @DustinCampbell @dpoeschl @davkean @jasonmalinowski @balajikris @basoundr @jmarolf @rchande

**Comment by DustinCampbell** [comment]
WRT your question, I think the right approach is to show the inaccessible signature. The user will get an error after using it anyway. Maybe we'll add a code fix someday to change the accessibility of the member. That would make this a smooth experience.

For VB, I think it's OK if the compiler has already removed the inaccessible members and doesn't consider them. However, if the IDE is removing the members, I think we should relax that. How do others feel? @Pilchie?

**Comment by jasonmalinowski** [comment]
I agree with @DustinCampbell -- let's show it.

File: src/EditorFeatures/CSharp/SignatureHelp/InvocationExpressionSignatureHelpProvider_MethodGroup.cs [hunk 1]
```diff
@@ -43,7 +43,8 @@ internal partial class InvocationExpressionSignatureHelpProvider
                 }
 
                 var includeInstance = !throughExpression.IsKind(SyntaxKind.IdentifierName) ||
-                    semanticModel.LookupSymbols(throughExpression.SpanStart, name: throughSymbol.Name).Any(s => !(s is INamedTypeSymbol));
+                    semanticModel.LookupSymbols(throughExpression.SpanStart, name: throughSymbol.Name).Any(s => !(s is INamedTypeSymbol)) ||
+                    semanticModel.LookupSymbols(throughExpression.SpanStart, container: throughSymbol.ContainingType).Any(s => !(s is INamedTypeSymbol));
```
Comment (DustinCampbell) [inline src/EditorFeatures/CSharp/SignatureHelp/InvocationExpressionSignatureHelpProvider_MethodGroup.cs]: So, what was the crash in the repro? It's not clear to me how this fixes a crash. Also, can throughSymbol.ContainingType be null? How does that impact this situation?

Comment (brettfo) [inline src/EditorFeatures/CSharp/SignatureHelp/InvocationExpressionSignatureHelpProvider_MethodGroup.cs]: The crash occurred on the next line, `Contract.ThrowIfFalse()` that was unhandled, and this makes the boolean true where it should be. As for ContainingType, the default to the method is null anyways and that simply means 'from this context', similar to the line above that doesn't specify the container, so it defaults to the class containing the method, `B` in this case.

Comment (DustinCampbell) [inline src/EditorFeatures/CSharp/SignatureHelp/InvocationExpressionSignatureHelpProvider_MethodGroup.cs]: Got it. I didn't realize any of the methods on Contract compiled in release. Good to know.

Comment (Pilchie) [inline src/EditorFeatures/CSharp/SignatureHelp/InvocationExpressionSignatureHelpProvider_MethodGroup.cs]: I'm still thinking about this - I understand that this fixes the issue, but doesn't feel quite right for some reason.

Comment (DustinCampbell) [inline src/EditorFeatures/CSharp/SignatureHelp/InvocationExpressionSignatureHelpProvider_MethodGroup.cs]: From my perspective, we really shouldn't be failing fast and crashing the user's machine within signature help providers. In my observation, signature help can get all sorts of mangled trees and the providers should be somewhat resilient and just return null when things bind in ways we don't expect. I'd prefer a debug-only assert over crashing VS and causing the user to lose their unsaved changes.

Just my 2 cents.

Comment (Pilchie) [inline src/EditorFeatures/CSharp/SignatureHelp/InvocationExpressionSignatureHelpProvider_MethodGroup.cs]: I agree with the not crashing bit.  One of my concerns is the existence of this IncludeStatic and IncludeInstance code - we have a bunch of it in Completion that @rchande was just touching due to late regressions in VB.  Should we share that code?

Comment (rchande) [inline src/EditorFeatures/CSharp/SignatureHelp/InvocationExpressionSignatureHelpProvider_MethodGroup.cs]: The code here is basically asking the same two questions: "could this name have bound to a type?" and "could this name have bound to a non-type?". I could see us adding the extension methods ISymbol.CouldHaveBoundAsType(position, name) and ISymbol.CouldHaveBoundAsSomethingOtherThanAType(position, name) and using them in at least the 3 places that do this check.

**Comment by brettfo** [comment]
retest this please

**Comment by brettfo** [comment]
Pinging for additional feedback/signoff given that we had a hallway discussion yesterday that this fix should just be targeted at fixing the crash and not about making signature help crash-proof.

File: src/EditorFeatures/CSharpTest/SignatureHelp/InvocationExpressionSignatureHelpProviderTests.cs [hunk 2]
```diff
@@ -1947,5 +1947,29 @@ void M()
 
             Test(markup, expectedOrderedItems);
         }
+
+        [WorkItem(4144, "https://github.com/dotnet/roslyn/issues/4144")]
+        [Fact, Trait(Traits.Feature, Traits.Features.SignatureHelp)]
+        public void TestInaccessibleItem()
```
Comment (jasonmalinowski) [inline src/EditorFeatures/CSharpTest/SignatureHelp/InvocationExpressionSignatureHelpProviderTests.cs]: Nitpick: name the test for what it's testing about inaccessible items, since without looking I could imagine this would either assert they are there or they aren't there.

Comment (brettfo) [inline src/EditorFeatures/CSharpTest/SignatureHelp/InvocationExpressionSignatureHelpProviderTests.cs]: Updated in 8a0e1f8.

File: src/EditorFeatures/VisualBasicTest/SignatureHelp/InvocationExpressionSignatureHelpProviderTests.vb [hunk 3]
```diff
@@ -1835,5 +1835,27 @@ End Class
 
             Test(markup, expectedOrderedItems)
         End Sub
+
+        <WorkItem(4144, "https://github.com/dotnet/roslyn/issues/4144")>
+        <Fact, Trait(Traits.Feature, Traits.Features.SignatureHelp)>
+        Public Sub TestInaccessibleItem()
```
Comment (Pilchie) [inline src/EditorFeatures/VisualBasicTest/SignatureHelp/InvocationExpressionSignatureHelpProviderTests.vb]: Apply the name change from C# here too.

File: src/EditorFeatures/CSharp/SignatureHelp/InvocationExpressionSignatureHelpProvider_MethodGroup.cs [hunk 4]
```diff
@@ -43,7 +43,8 @@ internal partial class InvocationExpressionSignatureHelpProvider
                 }
 
                 var includeInstance = !throughExpression.IsKind(SyntaxKind.IdentifierName) ||
-                    semanticModel.LookupSymbols(throughExpression.SpanStart, name: throughSymbol.Name).Any(s => !(s is INamedTypeSymbol));
+                    semanticModel.LookupSymbols(throughExpression.SpanStart, name: throughSymbol.Name).Any(s => !(s is INamedTypeSymbol)) ||
+                    (!(throughSymbol is INamespaceOrTypeSymbol) && semanticModel.LookupSymbols(throughExpression.SpanStart, container: throughSymbol.ContainingType).Any(s => !(s is INamedTypeSymbol)));
```
Comment (Pilchie) [inline src/EditorFeatures/CSharp/SignatureHelp/InvocationExpressionSignatureHelpProvider_MethodGroup.cs]: What if there are no symbols returned that aren't types.  Is that possible?  If so, we'll be back to the same crash.  I *think* we'll always get ToString/GetHashCode, but worth double checking.

**Comment by Pilchie** [comment]
:+1:

File: src/EditorFeatures/CSharp/SignatureHelp/InvocationExpressionSignatureHelpProvider_MethodGroup.cs (hunk 4 above)
Comment (brettfo) [inline src/EditorFeatures/CSharp/SignatureHelp/InvocationExpressionSignatureHelpProvider_MethodGroup.cs]: I've tried the same scenario with `List<SomeUndefinedType>` and it behaves as expected, and the closest I could get to your scenario was with the private field being `UndefinedType` but we don't get this far in that case because the field type doesn't bind, so I think we're correct in the assumption that we'll always get `ToString/GetHashCode/GetType` or not this far at all.
