### PR TITLE
Fix for 7845: add DynamicAttribute to event with dynamic type

### LINKED ISSUE #7845: DynamicAttribute is not emitted for types of events.
```
    class Program
    {
        event Action<dynamic> E1;
        Action<dynamic> P1 { get; set; }
    }
```

```
.event class [mscorlib]System.Action`1<object> E1
{
  .addon instance void ConsoleApplication7.Program::add_E1(class [mscorlib]System.Action`1<object>)
  .removeon instance void ConsoleApplication7.Program::remove_E1(class [mscorlib]System.Action`1<object>)
} // end of event Program::E1

.property instance class [mscorlib]System.Action`1<object>
        P1()
{
  .custom instance void [System.Core]System.Runtime.CompilerServices.DynamicAttribute::.ctor(bool[]) = ( 01 00 02 00 00 00 00 01 00 00 ) 
  .get instance class [mscorlib]System.Action`1<object> ConsoleApplication7.Program::get_P1()
  .set instance void ConsoleApplication7.Program::set_P1(class [mscorlib]System.Action`1<object>)
} // end of property Program::P1
```

It doesn't look like there is a difference by comparison to behavior of the native compiler.

### PR DESCRIPTION
**Pull request by jcouv**
This adds a DynamicAttribute on the emitted .event when the type calls for it.

The unittests cover the expected behaviors, but there are also compatibility issues which were manually validated. 
The scenarios were:
1) subscribing/unsubscribing to an event from an external assembly
2) subscribing/unsubscribing with a lambda
3) overriding an event from an external assembly
Those scenarios were tested with the combination of compilers (native, v1.1 and latest with fix) for the referenced and the consuming assemblies. This showed no regression. I can provide more details.

One more scenario was validated but did show a regression compared to v1.1: building without reference to System.Core. 
Because we're emitting a DynamicAttribute, the compiler requires this reference. Failing such compilation with error CS1980 is consistent with the native compiler behavior and the broad handling of DynamicAttribute in Roslyn. This will be reviewed with the compatibility council later on.

Fixes #7845
CC @dotnet/roslyn-compiler for review.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs [hunk 1]
```diff
@@ -325,6 +327,119 @@ class C
...
+            var libComp = CreateCompilationWithMscorlib(text: libText, references: new[] { MscorlibRef, SystemCoreRef });
+            Assert.False(libComp.GetDiagnostics().Any(d => d.Severity == DiagnosticSeverity.Error));
+
+            byte[] libImage;
+            using (var output = new MemoryStream())
+            {
+                libComp.Emit(output, options: new EmitOptions(metadataOnly: true));
+                libImage = output.ToArray();
+            }
+            var libAssemblyRef = MetadataReference.CreateFromImage(libImage.AsImmutableOrNull());
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: `using` block can be replaced with ```var libAssemblyRef = libComp.EmitToImageReference();```.

**Comment by cston** [comment]
LGTM

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs (hunk 1 above)
Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: Thanks. Will do.

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEEventSymbol.cs [hunk 2]
```diff
@@ -92,11 +92,16 @@ private enum Flags : byte
                 _eventType = metadataDecoder.GetTypeOfToken(eventType);
             }
 
+            TypeSymbol originalEventType = _eventType;
+            _eventType = DynamicTypeDecoder.TransformType(_eventType, 0, handle, moduleSymbol);
+            // Dynamify object type if necessary
+            _eventType = _eventType.AsDynamicIfNoPia(_containingType);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEEventSymbol.cs]: Did we do this before? It doesn't feel appropriate for an event.

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEEventSymbol.cs [hunk 3]
```diff
@@ -92,11 +92,16 @@ private enum Flags : byte
                 _eventType = metadataDecoder.GetTypeOfToken(eventType);
             }
 
+            TypeSymbol originalEventType = _eventType;
+            _eventType = DynamicTypeDecoder.TransformType(_eventType, 0, handle, moduleSymbol);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEEventSymbol.cs]: Consider adjusting the code so that only the final value was stored in the ```_eventType``` field.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs [hunk 4]
```diff
@@ -287,6 +287,17 @@ internal sealed override void DecodeWellKnownAttribute(ref DecodeWellKnownAttrib
...
         }
 
+        internal override void AddSynthesizedAttributes(ModuleCompilationState compilationState, ref ArrayBuilder<SynthesizedAttributeData> attributes)
+        {
+            base.AddSynthesizedAttributes(compilationState, ref attributes);
+
+            if (this.Type.ContainsDynamic())
+            {
+                var compilation = this.DeclaringCompilation;
+                AddSynthesizedAttribute(ref attributes, compilation.SynthesizeDynamicAttribute(this.Type, 0));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs]: Consider adding parameter name for the second argument in order to improve readability.

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs [hunk 5]
```diff
@@ -8,6 +8,8 @@
 using Microsoft.CodeAnalysis.Test.Utilities;
 using Roslyn.Test.Utilities;
 using Xunit;
+using System.IO;
+using Microsoft.CodeAnalysis.Emit;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: What do we need these two usings for?

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs [hunk 6]
```diff
@@ -325,6 +327,119 @@ class C
...
+            var source = @"
+class A
+{
+        public event System.Action<dynamic> E1;
+        public event System.Action<dynamic> E2 { add {} remove {} }
+        public System.Action<dynamic> P { get; set; }
+}";
+            Action<ModuleSymbol> validator = module =>
+            {
+                var type = module.GlobalNamespace.GetMember<NamedTypeSymbol>("A");
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: Consider casting module to PEModuleSymbol to make sure that we are checking metadata produced by the compiler.

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs [hunk 7]
```diff
@@ -325,6 +327,119 @@ class C
             Assert.True(fevent.RemoveMethod.IsImplicitlyDeclared, "FieldLikeEvent RemoveAccessor");
         }
 
+        [Fact]
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: Please add a WorkItem attribute with the issue number and its complete URL. Same for other new tests.

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs [hunk 8]
```diff
@@ -325,6 +327,119 @@ class C
...
+}";
+            // The compilation succeeds because 'f' gets properly treated as dynamic 
+            var comp = CreateCompilationWithMscorlib(text: source, references: new[] { MscorlibRef, SystemCoreRef, CSharpRef, libAssemblyRef });
+            Assert.False(comp.GetDiagnostics().Any(d => d.Severity == DiagnosticSeverity.Error));
+
+            Assert.Equal(1, comp.SyntaxTrees.Length);
+            var tree = comp.SyntaxTrees[0];
+            var model = comp.GetSemanticModel(tree);
+
+            var methodSyntax = tree.GetRoot().DescendantNodes().OfType<SimpleLambdaExpressionSyntax>().First();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: The name ```methodSyntax``` is confusing. Consider renaming to ```lambdaSyntax```. Also, assert string representation of the node so that a reader could make better sense of what the test is doing.

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs [hunk 9]
```diff
@@ -325,6 +327,119 @@ class C
...
+            var methodSymbol = model.GetTypeInfo(methodSyntax);
+            Assert.Equal("System.Action<dynamic>", methodSymbol.ConvertedType.ToTestDisplayString());
+
+            var parameterSyntax = methodSyntax.DescendantNodes().OfType<ParameterSyntax>().First();
+            var parameterSymbol = model.GetDeclaredSymbol(parameterSyntax);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: Assert string representation of the node here too.

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs [hunk 10]
```diff
@@ -325,6 +327,119 @@ class C
...
+            // The compilation succeeds because 'f' gets properly treated as dynamic 
+            var comp = CreateCompilationWithMscorlib(text: source, references: new[] { MscorlibRef, SystemCoreRef, CSharpRef, libAssemblyRef });
+            Assert.False(comp.GetDiagnostics().Any(d => d.Severity == DiagnosticSeverity.Error));
+
+            Assert.Equal(1, comp.SyntaxTrees.Length);
+            var tree = comp.SyntaxTrees[0];
+            var model = comp.GetSemanticModel(tree);
+
+            var methodSyntax = tree.GetRoot().DescendantNodes().OfType<SimpleLambdaExpressionSyntax>().First();
+            var methodSymbol = model.GetTypeInfo(methodSyntax);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: Is this really a method symbol?

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs [hunk 11]
```diff
@@ -325,6 +327,119 @@ class C
...
+                //     public event System.Action<dynamic> E1 { add {} remove {} }
+                Diagnostic(ErrorCode.ERR_DynamicAttributeMissing, "dynamic").WithArguments("System.Runtime.CompilerServices.DynamicAttribute").WithLocation(4, 32));
+        }
+
+        [Fact]
+        public void EventWithDynamicAttribute_IsLoadedAsDynamic()
+        {
+            var libText = @"
+public class C {
+    public event System.Action<dynamic> E1;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: There should be similar test for an event with explicit accessors.

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs [hunk 12]
```diff
@@ -325,6 +327,119 @@ class C
...
+class LambdaConsumer
+{
+    void M(C c)
+    {
+        c.E1 += f => f.Bogus();
+    }
+}";
+            // The compilation succeeds because 'f' gets properly treated as dynamic 
+            var comp = CreateCompilationWithMscorlib(text: source, references: new[] { MscorlibRef, SystemCoreRef, CSharpRef, libAssemblyRef });
+            Assert.False(comp.GetDiagnostics().Any(d => d.Severity == DiagnosticSeverity.Error));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: Success of compilation is verified by compiling the code, running it and observing result. Use CompileAndVerify helper instead. Adjust the code so that it prints something to the console if it operates as expected, CompileAndVerify is able to verify output against a baseline.

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs [hunk 13]
```diff
@@ -325,6 +327,119 @@ class C
...
+            var source = @"
+class LambdaConsumer
+{
+    void M(C c)
+    {
+        c.E1 += f => f.Bogus();
+    }
+}";
+            // The compilation succeeds because 'f' gets properly treated as dynamic 
+            var comp = CreateCompilationWithMscorlib(text: source, references: new[] { MscorlibRef, SystemCoreRef, CSharpRef, libAssemblyRef });
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: There should be a test when library is referenced as a compilation reference rather than an image reference.

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEEventSymbol.cs (hunk 2 above)
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEEventSymbol.cs]: Yes, see [PEPropertySymbol constructor](https://github.com/dotnet/roslyn/blob/a4e375b95953e471660e9686a46893c97db70b0e/src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEPropertySymbol.cs#L114-L115).

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEEventSymbol.cs (hunk 3 above)
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEEventSymbol.cs]: I agree.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs (hunk 4 above)
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs]: Will do.

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs (hunk 5 above)
Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: They are for line 412. But they will go away with Chuck's suggestion to use EmitToImageReference instead.

```
using (var output = new MemoryStream())
            {
                libComp.Emit(output, options: new EmitOptions(metadataOnly: true));
```

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs (hunk 7 above)
Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: Yes

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs (hunk 5 above)
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: Please sort usings

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs (hunk 6 above)
Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: Yes

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs (hunk 7 above)
Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: Yes

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs (hunk 8 above)
Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: Ok for naming. But I didn't understand the feedback on assert.

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs (hunk 10 above)
Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: Will change to lambdaTypeInfo.

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs (hunk 11 above)
Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: Yes

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEEventSymbol.cs (hunk 2 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEEventSymbol.cs]: This doesn't make it appropriate for an event. Do you have a test that demonstrates that this should be done?

Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEEventSymbol.cs]: Makes sense. The call to AsDynamicIfNoPia is not useful.

Comment (jcouv) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEEventSymbol.cs]: Aleksey, I noticed that DynamicTypeDecoder.TransformType assumes the presence of customModifiers (haveCustomModifierFlags: true on line 72). This doesn't seem harmful, as the decoder logic handles the case of zero custom modifiers properly, but it's a bit awkward. 
We should discuss.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEEventSymbol.cs]: That is correct, there could be custom modifiers inside the type. Amount of custom modifiers at the top level is passed through special parameter.

**Comment by AlekseyTs** [comment]
@jcouv I think we need more tests in this area:
- Overriding/implementing with matching dynamic and with object/dynamic mismatch
- The scenarios that you tested for backward compatibility (with unsupported event error)
- Other scenarios you tested manually?

If you can confirm that we have unit-tests for some of them, new unit-tests are not needed, otherwise I think we should add them.

**Comment by jcouv** [comment]
@AlekseyTs, sure, I'll stop by tomorrow to discuss some additional tests.

**Comment by jcouv** [comment]
Updated unittests for:
- compiling and running, instead of just compiling and checking
- override/implement with event and event field
- capturing error when loading legacy IL
- custom modifier

**Comment by jcouv** [comment]
@dotnet-bot retest prtest/lin/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/4639/
// Retest reason: I/O failure was most likely transient

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEEventSymbol.cs [hunk 14]
```diff
@@ -86,17 +86,21 @@ private enum Flags : byte
...
             }
 
+            TypeSymbol originalEventType = _eventType;
             if ((object)_eventType == null)
             {
                 var metadataDecoder = new MetadataDecoder(moduleSymbol, containingType);
-                _eventType = metadataDecoder.GetTypeOfToken(eventType);
+                originalEventType = metadataDecoder.GetTypeOfToken(eventType);
+
+                var targetSymbolCustomModifierCount = 0;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEEventSymbol.cs]: Use ```const``` instead?

File: src/Compilers/CSharp/Test/Symbol/Symbols/CustomModifiersTests.cs [hunk 15]
```diff
@@ -1806,7 +1806,7 @@ Set Overridden3
         }
 
         [Fact, WorkItem(7674, "https://github.com/dotnet/roslyn/issues/7674")]
-        public void EventWithDynamic()
+        public void EventFieldWithDynamic()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/CustomModifiersTests.cs]: I assume your intent is to use ```EventFieldWithDynamic``` as a name for the new test. Revert rename?

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs [hunk 16]
```diff
@@ -325,6 +325,397 @@ class C
...
+    public override event System.Action<object> E2 { add {} remove {} }
+
+    void M() {
+        E1 += (string s) => System.Console.WriteLine(s); // type won't fit
+        E2 += (string s) => System.Console.WriteLine(s); // type won't fit
+        E1(""Avoid warning"");
+    }
+}";
+            var comp = CreateCompilationWithMscorlib(text: source, references: new[] { libAssemblyRef }).VerifyDiagnostics(
+                // (8,9): error CS1661: Cannot convert lambda expression to delegate type 'Action<object>' because the parameter types do not match the delegate parameter types
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: I am not sure what is the goal here. Do we want to verify that CL2.E1 and CL2.E2 still have type ```System.Action<object>```? If that is correct, let's test that directly rather than use diagnostics for this - create compilation, lookup symbols for the events and check their types.

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs [hunk 17]
```diff
@@ -325,6 +325,397 @@ class C
...
+    public override event System.Action<object> E2 { add {} remove {} }
+
+    void M() {
+        E1 += (string s) => System.Console.WriteLine(s); // type won't fit
+        E2 += (string s) => System.Console.WriteLine(s); // type won't fit
+        E1(""Avoid warning"");
+    }
+}";
+            var comp = CreateCompilationWithMscorlib(text: source, references: new[] { libAssemblyRef }).VerifyDiagnostics(
+                                // (8,9): error CS1661: Cannot convert lambda expression to delegate type 'Action<object>' because the parameter types do not match the delegate parameter types
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: Same comment as above.

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs [hunk 18]
```diff
@@ -325,6 +325,397 @@ class C
...
+    {
+        C x = new C();
+        x.E += (f) => f.Bogus(); // Type of E is seen as Action<object>, not Action<dynamic>
+    }
+}
+";
+            var compilation = CreateCompilationWithCustomILSource(source, ilSource, new[] { CSharpRef, SystemCoreRef }).VerifyDiagnostics(
+                // (7,25): error CS1061: 'object' does not contain a definition for 'Bogus' and no extension method 'Bogus' accepting a first argument of type 'object' could be found (are you missing a using directive or an assembly reference?)
+                //         x.E += (f) => f.Bogus();
+                Diagnostic(ErrorCode.ERR_NoSuchMemberOrExtension, "Bogus").WithArguments("object", "Bogus").WithLocation(7, 25));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: I think we are actually interested in an error about the event rather than about the body of the lambda.

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs [hunk 19]
```diff
@@ -325,6 +325,397 @@ class C
...
+        c.RaiseEvent();
+    }
+}";
+            var expectedOutput = "Print method ran.";
+            var compilationVerifier = CompileAndVerify(source: source, additionalRefs: new[] { MscorlibRef, SystemCoreRef, CSharpRef, libCompRef },
+                                                    expectedOutput: expectedOutput);
+        }
+
+
+        [Fact, WorkItem(7845, "https://github.com/dotnet/roslyn/issues/7845")]
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: Minor - an extra empty line.

File: src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs (hunk 18 above)
Comment (jcouv) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: I don't know if I get a more specific error.
What if I changed this test to verify the loaded symbol for the event, similarly to your suggestion for the other tests?

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/Source/EventTests.cs]: I think this test is actually supposed to test diagnostics, we want to make sure we are reporting the same/similar error for this scenario as before. Try replacing the lambda with ```null```.

**Comment by jcouv** [comment]
@AlekseyTs, I added a commit to address the code review feedback. 

The size of the IL that I had to embed for the legacy scenario to execute bothers me a bit, but I don't see a solution to shrink it...

**Comment by jcouv** [comment]
@AlekseyTs, I pushed one more commit to address both those recommendations. Thanks.

**Comment by AlekseyTs** [comment]
LGTM

**Comment by jcouv** [comment]
@dotnet-bot retest prtest/win/dbg/eta please

**Comment by jcouv** [comment]
This change introduced a small backward compatibility break. 
Compiling such events without System.Core will result in an error, just like the 4.6 compiler, but unlike the 1.1 compiler.
`error CS1980: Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?`
