### PR TITLE
Adjust parsing to fix local function typing in IDE

### LINKED ISSUE #13480: Typing generic local function requires fighting with auto-completion
Place caret inside method M in following code snippet:
```cs
class C
{
    public void M()
    {

    }
}
```

and start typing this text: T M\<T\>(T t) => t;

you will end up with following code:
```cs
class C
{
    public void M()
    {
        ToString M<ToString>(T t) => t;
    }
}
```

because auto-completion offers you to complete ToString when you type return type and type parameter. It also auto-completes preselected item as you continue typing even if you don't interact with auto-completion popup at all.

If you want to end up with correct code you have to decline auto-completion by pressing 'esc' multiple times during typing a single line.

Also, completing 'ToString' in angle brackets looks bizarre and doesn't make any sense.

### PR DESCRIPTION
**Pull request by agocke**
Previously, when parsing a local function we held off on creating the
node until we actually saw a body because the local function could be
ambiguous with an await statement until then. However, we never verified
that the parsed return type was "await", meaning we were overly
conservative in classifying incomplete local functions. This created a
very bad typing experience where completion could not tell that you were
declaring a local function until the body, which created many incorrect
results in the completion list, including in the generic parameter list.

This change verifies that the return type we've parsed is actually the
literal text "await" before considering the parse ambiguous.

Fixes #13480.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Syntax/Parsing/LocalFunctionParsingTests.cs [hunk 1]
```diff
@@ -13,6 +13,92 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+            Assert.Equal("int L(", m5s1.ToFullString().Trim());
+
+            var m6 = file.DescendantNodes()
+                .OfType<MethodDeclarationSyntax>()
+                .Where(m => (string)m.Identifier.Value == "M6")
+                .Single();
+            var m6s1 = m6.Body.Statements.Single();
+            Assert.Equal(SyntaxKind.LocalFunctionStatement, m6s1.Kind());
+            Assert.Equal("int? L(", m6s1.ToFullString().Trim());
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Syntax/Parsing/LocalFunctionParsingTests.cs]: If this is verifying the shape of the syntax tree, consider using the helpers in `ParsingTests`. See `AsyncParsingTests` for example.

**Comment by cston** [comment]
LGTM

File: src/Compilers/CSharp/Test/Syntax/Parsing/LocalFunctionParsingTests.cs (hunk 1 above)
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Test/Syntax/Parsing/LocalFunctionParsingTests.cs]: agreed.

**Comment by CyrusNajmabadi** [comment]
👍  With a couple of requests on cleanup.

**Comment by AlekseyTs** [comment]
LGTM

**Comment by agocke** [comment]
test perf_correctness_prtest please
