### PR TITLE
Disable BackgroundCompiler on low VM

### LINKED ISSUE #6253: Disable BackgroundCompiler on low VM indication
We've had reports of people running into crashes with large solutions, particularly with Resharper 9.2 installed. From the dumps, I noticed that the most of the memory attributed to Roslyn was held onto by the BackgrdoundCompiler. It's doing exactly what it's supposed to do. However, in low VM situations, it seems reasonable to exchange performance for increased reliability.

Since BackgroundCompiler acts as a cache of compilations, there's no functionality hit to disabling it.

### PR DESCRIPTION
**Pull request by pharring**
Fixes #6253 

@jasonmalinowski @heejaechang @KevinH-MS @Pilchie 

This looks fairly straightforward, but can you check the uses of ```PartialSemanticsEnabled``` to determine that, when we've disabled the BackgroundCompiler, we at least make forward progress elsewhere?

### CODE REVIEW

File: src/Features/Core/Portable/Workspace/BackgroundCompiler.cs [hunk 1]
```diff
@@ -42,6 +43,25 @@ public BackgroundCompiler(Workspace workspace)
             }
         }
 
+        public void Dispose()
+        {
+            if (_workspace != null)
+            {
+                this.CancelBuild(releasePreviousCompilations: true);
+
+                var editorWorkspace = _workspace as Workspace;
```
Comment (jasonmalinowski) [inline src/Features/Core/Portable/Workspace/BackgroundCompiler.cs]: _workspace is already of type Workspace here...?

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs [hunk 2]
```diff
@@ -16,7 +17,7 @@ namespace Microsoft.VisualStudio.LanguageServices
     /// </summary>
     public abstract class VisualStudioWorkspace : Workspace
     {
-        private readonly BackgroundCompiler _backgroundCompiler;
+        private BackgroundCompiler _backgroundCompiler;
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs]: This is not a blocking comment/suggestion, but in general I prefer to leave things readonly even in the disposable case. To me the readonlyness is such a strong guarantee for what invariants the rest of the code can assume that losing it for just this case isn't worth it.

**Comment by heejaechang** [comment]
will it go into master as well?

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs [hunk 3]
```diff
@@ -34,6 +41,22 @@ internal VisualStudioWorkspace(HostServices hostServices, WorkspaceBackgroundWor
             }
         }
 
+        private void OnCacheFlushRequested(object sender, EventArgs e)
+        {
+            if (_backgroundCompiler != null)
+            {
+                _backgroundCompiler.Dispose();
+                _backgroundCompiler = null; // PartialSemanticsEnabled will now return false
```
Comment (Pilchie) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs]: It seems that the only place that still uses FrozenPartialSemantics is data tips.  This might mean that calculating datatips get significantly more expensive, as it will now block while metadata is read, files are parsed, skeleton assemblies generated, etc, instead of returning info based on whatever the background compiler has already completed.

**Comment by Pilchie** [comment]
@heejaechang All changes to `stabilization` are being merged back to `master`.

File: src/Features/Core/Portable/Workspace/BackgroundCompiler.cs (hunk 1 above)
Comment (pharring) [inline src/Features/Core/Portable/Workspace/BackgroundCompiler.cs]: Heh. Copied it from the constructor without noticing that. I will fix in both places.

**Comment by davkean** [comment]
Filed https://github.com/dotnet/roslyn/issues/6257 for the tests that are deadlocking.
Also fixed, the duplicate timeout messages in the Identified Problems section.

retest prtest/win/dbg/unit32 please

**Comment by davkean** [comment]
Added that test that failed to my list of flaky tests in #6167, unless you broke this Paul?

**Comment by pharring** [comment]
All tests pass on my local box.

**Comment by pharring** [comment]
retest prtest/win/dbg/unit32 please

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs (hunk 3 above)
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs]: We don't use it any more for completion?

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs (hunk 2 above)
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs]: A common counter-argument is that then we're holding onto the disposed object, but in theory the disposed object should have released it's resources...if it didn't then we don't understand our own code.

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs (hunk 3 above)
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs]: If data tips are the only thing using it, I think we did that because in practice it only requires your current syntax tree + metadata references to mscorlib. In that case, we don't need to turn off partial semantics in this PR, since the features we thought needed the background compiler don't.

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs (hunk 2 above)
Comment (pharring) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs]: In this case, nulling out the _backgroundCompiler is necessary because we want to change the meaning of PartialSemanticsEnabled. I could have introduced an extra bool field for that, but then we'd have the same discussion about whether that should be readonly. Seemed simpler to save the field and the discussion. (You said it was not  blocking.)

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs (hunk 3 above)
Comment (pharring) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs]: I think he missed this route:
http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/Document.cs,410
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures.Text/Extensions.cs,122
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/Intellisense/Completion/Controller.Session_ComputeModel.cs,98
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/Intellisense/Completion/Controller.Session_ComputeModel.cs,82
http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/Intellisense/Completion/Controller.Session_ComputeModel.cs,38

That looks like completion to me.

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs (hunk 2 above)
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs]: I think I'd prefer to leave the object read-only and have a new mutable bool. But that's me.

File: src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs (hunk 3 above)
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs]: I'm curious, @pharring, have you tested what the VS experience is like when we do turn off partial semantics and have no background compiler? I'd be curious to know what the "large solution" experience is in this case...

Comment (Pilchie) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs]: Yes, I did.  Thanks for pointing it out.

Comment (pharring) [inline src/VisualStudio/Core/Def/Implementation/ProjectSystem/VisualStudioWorkspace.cs]: Personally, I can't detect any difference (I wrote an extension which disables the background compiler), but that was just with a few minutes of playing with it.
