### PR TITLE
Fix typo in `#if` directive

### LINKED ISSUE #60553: Incorrect define constant use in BuildServerConnection.cs
I have accidentally found the following in `src\Compilers\Shared\BuildServerConnection.cs`, method `RunServerShutdownRequestAsync`:

```
#if NET50_OR_GREATER
                            await process.WaitForExitAsync(cancellationToken).ConfigureAwait(false);
#else
                            process.WaitForExit();
#endif
```

I think the define constant should be `NET5_0_OR_GREATER` (underscore).

### PR DESCRIPTION
**Pull request by Youssef1313**
Closes #60553

### CODE REVIEW

**Review by sharwell — APPROVED** [review]

File: src/Compilers/Shared/BuildServerConnection.cs [hunk 1]
```diff
@@ -96,7 +96,7 @@ internal sealed class BuildServerConnection
                         try
                         {
                             var process = Process.GetProcessById(shutdownBuildResponse.ServerProcessId);
-#if NET50_OR_GREATER
+#if NET5_0_OR_GREATER
```
Comment (333fred) [inline src/Compilers/Shared/BuildServerConnection.cs:99]: @jaredpar how broken was our code because of this?

**Review by 333fred — COMMENTED** [review]
Want to hear from Jared before approving this.

File: src/Compilers/Shared/BuildServerConnection.cs (hunk 1 above)
Comment (Youssef1313) [reply src/Compilers/Shared/BuildServerConnection.cs:99]: @333fred The intent is that both `WaitForExit` and `WaitForExitAsync` are semantically equivalent (https://github.com/dotnet/runtime/issues/34294#issuecomment-606833721).

However, I found https://github.com/dotnet/runtime/issues/42556, which makes me less confident that we want to call the async version in .NET 5.0. It's a bug where they're not semantically equivalent and it was fixed for .NET 6, but not ported to .NET 5.

Comment (jaredpar) [reply src/Compilers/Shared/BuildServerConnection.cs:99]: In this particular case the distinction should not matter because we aren't actually reading output in the shutdown path. It's more just "wait for this op to complete".

Comment (jaredpar) [reply src/Compilers/Shared/BuildServerConnection.cs:99]: In terms of "how broken" the answer is "not really that broken". It's mostly about using `Async` when possible to avoid blocking threads. This is just on the "jaredpar is embarrased" level than bad scenario.

**Review by jaredpar — APPROVED** [review]

**Comment by jaredpar** [comment]
@chsienki, @RikkiGibson, @cston  PTAL

**Review by chsienki — APPROVED** [review]

**Comment by jcouv** [comment]
@jaredpar @chsienki @333fred Seems this PR could be merged.

**Comment by 333fred** [comment]
Thanks Youssef!
