### PR TITLE
Do not put an equals and quotes when completing an xml attribute if present

### LINKED ISSUE #72259: Doc comment completions should not insert `=""` if there is already one
**Version Used**:
Latest `main`

**Steps to Reproduce**:
```cs
class C
{
    /// <summary>
    /// <see cref=""/>
    /// </summary>
    void M()
    {
    }
}
```
Try to replace `cref` with other valid attrribute, e.g. `langword`

**Expected Behavior**:
`cref` is replaced with `langword`

**Actual Behavior**:
An additional `=""` is added:
devenv_XIDJACNtsz

### PR DESCRIPTION
**Pull request by sdelarosbil**
Closes #72259

To address this issue, this pr will check to see if there's an Equals token already next to the completion. If there is, we don't place the ="" and only replace the word meant to be completed.

To note about the VB change: it seems the completion on VB works differently and didn't supported this scheme of completion (I tried a unit test and it wasn't even something in the list). So this effectively leaves VB as is.

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs [hunk 1]
```diff
@@ -760,6 +760,35 @@ static void Goo()
...
+                    /// <see langword=""/>
+                    /// </summary>
+                    static void Goo()
+                    {
+                    }
+                }
+                """;
+
+            await VerifyProviderCommitAsync(text, "langword", expected, null);
+        }
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs:790]: can you add a similar test in CompletionCommandHandlerTests?  Also, please test the case where the user has typed *nothing* but brings up completion and completes out one of these words.  like `<see $$=""/>`.  Note: all these tests i'm asking for should go into CompletionCommandHandlerTests, not the provider tests.  thanks.

File: src/Features/VisualBasic/Portable/Completion/CompletionProviders/XmlDocCommentCompletionProvider.vb [hunk 2]
```diff
@@ -332,7 +332,7 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Completion.Providers
 
         Private Function GetAttributes(tagName As String, attributes As SyntaxList(Of XmlNodeSyntax)) As IEnumerable(Of CompletionItem)
             Dim existingAttributeNames = attributes.Select(AddressOf GetAttributeName).WhereNotNull().ToSet()
-            Return GetAttributeItems(tagName, existingAttributeNames)
+            Return GetAttributeItems(tagName, existingAttributeNames, false)
```
Comment (CyrusNajmabadi) [inline src/Features/VisualBasic/Portable/Completion/CompletionProviders/XmlDocCommentCompletionProvider.vb:335]: named parameter for `false`

File: src/Features/CSharp/Portable/Completion/CompletionProviders/XmlDocCommentCompletionProvider.cs [hunk 3]
```diff
@@ -85,7 +85,7 @@ public override bool IsInsertionTrigger(SourceText text, int characterPosition,
 
             if (IsAttributeNameContext(token, position, out var elementName, out var existingAttributes))
             {
-                return GetAttributeItems(elementName, existingAttributes);
+                return GetAttributeItems(elementName, existingAttributes, !token.GetNextToken().IsKind(SyntaxKind.EqualsToken));
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/XmlDocCommentCompletionProvider.cs:88]: named parameter.

File: src/Features/Core/Portable/Completion/Providers/AbstractDocCommentCompletionProvider.cs [hunk 4]
```diff
@@ -113,10 +113,10 @@ private CompletionItem GetItem(string name)
         return CreateCompletionItem(name);
     }
 
-    protected IEnumerable<CompletionItem> GetAttributeItems(string tagName, ISet<string> existingAttributes)
+    protected IEnumerable<CompletionItem> GetAttributeItems(string tagName, ISet<string> existingAttributes, bool addEqualsAndQuotes)
     {
         return s_attributeMap.Where(x => x.elementName == tagName && !existingAttributes.Contains(x.attributeName))
-                             .Select(x => CreateCompletionItem(x.attributeName, beforeCaretText: x.text, afterCaretText: "\""));
+                             .Select(x => CreateCompletionItem(x.attributeName, beforeCaretText: addEqualsAndQuotes ? x.text : x.text[..^2], afterCaretText: addEqualsAndQuotes ? "\"" : ""));
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/AbstractDocCommentCompletionProvider.cs:119]: can you wrap this a bit in a more pleasing fashion?  something like:

```
        return s_attributeMap
            .Where(x => x.elementName == tagName && !existingAttributes.Contains(x.attributeName))
            .Select(x => CreateCompletionItem(
                x.attributeName,
                beforeCaretText: addEqualsAndQuotes ? x.text : x.text[..^2],
                afterCaretText: addEqualsAndQuotes ? "\"" : ""));
```

Thanks :)

File: src/Features/VisualBasic/Portable/Completion/CompletionProviders/XmlDocCommentCompletionProvider.vb (hunk 2 above)
Comment (CyrusNajmabadi) [reply src/Features/VisualBasic/Portable/Completion/CompletionProviders/XmlDocCommentCompletionProvider.vb:335]: can you add a test in CompletionCommandHandlerTests that shows the vb behavior?

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs [hunk 5]
```diff
@@ -760,6 +760,35 @@ static void Goo()
...
         }
 
+        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/72259")]
+        public async Task SeeAttributeNames2()
+        {
+            var text = """
+                class C
+                {
+                    /// <summary>
+                    /// <see l$$=""/>
```
Comment (DoctorKrolic) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs:770]: Please add test like `/// <see l$$     =""/>`. Since there is a gap between identifier and a `=` (even if there is at least one space, I made several just for clarity) I would expect completion to actually insert `=""`: `/// <see langword="$$"     =""/>`. This way user's path can be the following:
1. `/// <see l$$     =""/>`
2. `/// <see langword="$$"     =""/>`
3. `/// <see langword="not$$"     =""/>` - complete the keyword
4. `/// <see langword="not"     $$=""/>` - move cursor to the next "empty" attribute
5. `/// <see langword="not"     langword="$$"/>` - work on the next attribute

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs [hunk 6]
```diff
@@ -760,6 +760,35 @@ static void Goo()
...
+                    static void Goo()
+                    {
+                    }
+                }
+                """;
+            var expected = """
+                class C
+                {
+                    /// <summary>
+                    /// <see langword=""/>
```
Comment (DoctorKrolic) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs:781]: The test doesn't seem to show it, but I would expect the cursor to jump into quotes after completion in such scenario: `/// <see langword="$$"/>`. Please make sure the expected behavior here is fully tested

Comment (sdelarosbil) [reply src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs:781]: The new test now tests for this and I actually had to implement this

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs (hunk 5 above)
Comment (sdelarosbil) [reply src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs:770]: I added a test with a space that adds the equals/quotes, but the other parts seemed a little out of scope for this issue

File: src/Features/Core/Portable/Completion/Providers/AbstractDocCommentCompletionProvider.cs (hunk 4 above)
Comment (sdelarosbil) [reply src/Features/Core/Portable/Completion/Providers/AbstractDocCommentCompletionProvider.cs]: done

File: src/Features/CSharp/Portable/Completion/CompletionProviders/XmlDocCommentCompletionProvider.cs (hunk 3 above)
Comment (sdelarosbil) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/XmlDocCommentCompletionProvider.cs]: done.

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs (hunk 1 above)
Comment (sdelarosbil) [reply src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs:790]: @CyrusNajmabadi I moved the tests to CompletionCommandHandlerTests, but adding the test to type nothing seems like it won't help much.

If you type nothing and invoke the completion, it doesn't actually suggests you attributes name, it would rather suggests you tags (so it would actually suggest me a `see` tag here even though I just wrote one). This could be a separate issue, but for testing this behavior in particular, it didn't seem like it would have helped.

If a test should still be added, what are your expectations of it?

File: src/Features/VisualBasic/Portable/Completion/CompletionProviders/XmlDocCommentCompletionProvider.vb (hunk 2 above)
Comment (sdelarosbil) [reply src/Features/VisualBasic/Portable/Completion/CompletionProviders/XmlDocCommentCompletionProvider.vb]: Like I said in the pr, it doesn't work the same way. It more behaves like I described with my other comment, but even IF you typed "l" here.

So I could add a test, but I am not sure it would be useful.

Comment (CyrusNajmabadi) [reply src/Features/VisualBasic/Portable/Completion/CompletionProviders/XmlDocCommentCompletionProvider.vb]: the test still shows behavior, and let's us know if it changes :)

code changes fairly regularly.  and if we only have tests for what we think the code itself does, we can often miss stuff if a large refactoring happens later.

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs [hunk 7]
```diff
@@ -1015,23 +1044,6 @@ class C
...
-                    /// <summary>
-                    /// <see langword="$$
-                    /// </summary>
-                    static void Goo()
-                    {
-                    }
-                }
-                """;
-            await VerifyItemExistsAsync(text, "await", usePreviousCharAsTrigger: true);
-        }
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs:1033]: why was this test removed? generally, we never do that.  we just update the test to show the new behavior.

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests_XmlDoc.vb [hunk 8]
```diff
@@ -625,6 +625,54 @@ class c
             End Using
         End Function
 
+        <WpfTheory, CombinatorialData>
+        Public Async Function InvokeWithOpenAngleSeeCommitLangwordWithEqualsQuotes(showCompletionInArgumentLists As Boolean) As Task
+
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests_XmlDoc.vb:630]:
```suggestion
```

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs (hunk 7 above)
Comment (sdelarosbil) [reply src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs:1033]: Oh I thought you wanted me to move it instead of duplicating it, I'll add it back

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs (hunk 7 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs:1033]: nope!  please keep :)

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests_XmlDoc.vb [hunk 9]
```diff
@@ -625,6 +625,54 @@ class c
...
+    void goo() { }
+}
+            ]]></Document>, showCompletionInArgumentLists:=showCompletionInArgumentLists)
+
+                state.SendTypeChars("l")
+                state.SendInvokeCompletionList()
+                Await state.AssertSelectedCompletionItem(displayText:="langword")
+                state.SendReturn()
+
+                ' /// <see langword="$$"/>
```
Comment (DoctorKrolic) [inline src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests_XmlDoc.vb:647]:
```suggestion
                ' /// <see langword="$$"
```
I appreciate the effort to show the result in a more readable form, but it should precisely match the actual outcome

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests_XmlDoc.vb [hunk 10]
```diff
@@ -625,6 +625,54 @@ class c
...
```
Comment (DoctorKrolic) [inline src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests_XmlDoc.vb:671]:
```suggestion
                ' /// <see langword="$$" =""
```
Same as above

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs (hunk 5 above)
Comment (DoctorKrolic) [reply src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs:770]: I don't know what do you mean by "the other parts". I've written potential user path just to show that the behavior I expect here can actually be useful. And by looking at new tests I see that you fully fulfilled this request, so treat this comment as resolved, thanks for your work!

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs (hunk 1 above)
Comment (sdelarosbil) [reply src/EditorFeatures/CSharpTest/Completion/CompletionProviders/XmlDocumentationCommentCompletionProviderTests.cs:790]: Done.

File: src/Features/VisualBasic/Portable/Completion/CompletionProviders/XmlDocCommentCompletionProvider.vb (hunk 2 above)
Comment (sdelarosbil) [reply src/Features/VisualBasic/Portable/Completion/CompletionProviders/XmlDocCommentCompletionProvider.vb]: Turns out after retrying, I found out I didn't checked this well and it behaves the same.

So I ended up implementing the same logic, but still added the test to make sure.

**Comment by sdelarosbil** [comment]
@CyrusNajmabadi Should be ready for another round of review

**Review by DoctorKrolic — APPROVED** [review]

**Comment by sdelarosbil** [comment]
@CyrusNajmabadi This one was ready for another round, should be very close to merge, but the CI is failing for another reason.

File: src/Features/Core/Portable/Completion/Providers/AbstractDocCommentCompletionProvider.cs [hunk 11]
```diff
@@ -279,6 +283,13 @@ public override async Task<CompletionChange> GetChangeAsync(Document document, C
         var replacementText = beforeCaretText;
         var newPosition = replacementSpan.Start + beforeCaretText.Length;
 
+        if (text.Length > replacementSpan.End + 1
+            && text[replacementSpan.End] == '='
+            && text[replacementSpan.End + 1] == '"')
+        {
+            newPosition += 2;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Completion/Providers/AbstractDocCommentCompletionProvider.cs:290]: so this means that we shoudl put the caret between teh quotes, even if there were already quotes there, right?  In that case, can you add that validation in the tests as well, so we don't regress that?  Thanks!

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by sdelarosbil** [comment]
@CyrusNajmabadi Seems the CI test is being flaky here (tried to run one that failed locally and it passed)

**Comment by sdelarosbil** [comment]
@CyrusNajmabadi and CI failed again, I don't know why it behaves like this, I try to check the errors, but it doesn't help me much...

**Comment by CyrusNajmabadi** [comment]
it's not you.  it's us :)

**Comment by CyrusNajmabadi** [comment]
Thanks!
