### PR TITLE
Use task based approach for concurrent suppressor execution

### LINKED ISSUE #41713: Diagnostics: OperationCanceledException in ExecuteSuppressionAction
VSMac logs contain exceptions from Roslyn with this stack:

```
ERROR [2020-02-07 15:05:15Z]: Roslyn fatal exception
System.AggregateException: One or more errors occurred. (The operation was canceled.) ---> System.OperationCanceledException: The operation was canceled.
  at System.Threading.CancellationToken.ThrowOperationCanceledException () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/shared/System/Threading/CancellationToken.cs:338 
  at System.Threading.CancellationToken.ThrowIfCancellationRequested () [0x00008] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/shared/System/Threading/CancellationToken.cs:333 
  at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteSuppressionAction (Microsoft.CodeAnalysis.Diagnostics.DiagnosticSuppressor suppressor, System.Collections.Immutable.ImmutableArray`1[T] reportedDiagnostics) [0x0000a] in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerExecutor.cs:297 
  at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<>c__DisplayClass73_0.<ApplyProgrammaticSuppressionsCore>b__3 (Microsoft.CodeAnalysis.Diagnostics.DiagnosticSuppressor suppressor) [0x00000] in /_/src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs:697 
  at System.Threading.Tasks.Parallel+<>c__DisplayClass44_0`2[TSource,TLocal].<PartitionerForEachWorker>b__1 (System.Collections.IEnumerator& partitionState, System.Int32 timeout, System.Boolean& replicationDelegateYieldedBeforeCompletion) [0x00103] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corefx/src/System.Threading.Tasks.Parallel/src/System/Threading/Tasks/Parallel.cs:3220 
--- End of stack trace from previous location where exception was thrown ---
```

The fact that this is an OperationCanceledException tells me there should be a catch(OperationCanceledException) somewhere but I can't find it. How is this supposed to work? Is this benign?

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #41713

### CODE REVIEW

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs [hunk 1]
```diff
@@ -758,10 +758,23 @@ void executeSuppressionActions(IEnumerable<Diagnostic> reportedDiagnostics, bool
...
-                    });
+                        Parallel.ForEach(suppressors, suppressor =>
+                        {
+                            AnalyzerExecutor.ExecuteSuppressionAction(suppressor, getSuppressableDiagnostics(suppressor));
+                        });
+                    }
+                    catch (AggregateException ex)
+                    {
+                        // Unwrap and throw the inner OperationCanceledException.
+                        if (ex.InnerExceptions.Count == 1 && ex.InnerException is OperationCanceledException)
```
Comment (sharwell) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: You'll want to throw `OperationCanceledException` even if more than one was cancelled, as long as all are.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs [hunk 2]
```diff
@@ -758,10 +758,23 @@ void executeSuppressionActions(IEnumerable<Diagnostic> reportedDiagnostics, bool
...
+                        {
+                            throw ex.InnerException;
```
Comment (sharwell) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]:
```suggestion
                            ExceptionDispatchInfo.Capture(ex.InnerException).Throw();
```

**Comment by mavasani** [comment]
Ping for reviews.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs [hunk 3]
```diff
@@ -758,10 +759,17 @@ void executeSuppressionActions(IEnumerable<Diagnostic> reportedDiagnostics, bool
...
-                        AnalyzerExecutor.ExecuteSuppressionAction(suppressor, getSuppressableDiagnostics(suppressor));
-                    });
+                        Parallel.ForEach(suppressors, suppressor =>
+                        {
+                            AnalyzerExecutor.ExecuteSuppressionAction(suppressor, getSuppressableDiagnostics(suppressor));
+                        });
+                    }
+                    catch (AggregateException ex)
+                    {
+                        ExceptionDispatchInfo.Capture(ex.InnerException).Throw();
```
Comment (cston) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: >InnerException [](start = 57, length = 14)

What if there are exceptions from multiple threads?

Comment (cston) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: Should `OperationCanceledException` reach here in an `AggregateException`? If `Parallel.ForEach()` was passed a `ParallelOptions` with a `CancellationToken`, then we'd presumably have to handle non-nested `OperationCanceledException` here. But otherwise, should the `Action` handle the `OperationCanceledException` for each thread?

---
In reply to: [383568522](https://github.com/dotnet/roslyn/pull/41892#discussion_r383568522) [](ancestors = 383568522)

Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: Good points. @sharwell Do you know how `ExceptionDispatchInfo.Capture` handles these cases? I think it might be best to switch this code to just building up a tasks array and doing a WaitAll instead of using a `Parallel.ForEach`, just like other places in the driver. Another option is to remove the concurrent execution completely as we don't expect that many suppressors, and they would generally be much cheaper compared to analyzers.

Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: @cston @sharwell I have switched to a different approach.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs [hunk 4]
```diff
@@ -8,6 +8,7 @@
 using System.Collections.Immutable;
 using System.Diagnostics;
 using System.Linq;
+using System.Runtime.ExceptionServices;
```
Comment (cston) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: >using System.Runtime.ExceptionServices [](start = 0, length = 38)

Consider removing if no longer needed.

**Comment by mavasani** [comment]
Ping @sharwell @dotnet/roslyn-compiler for additional review.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs [hunk 5]
```diff
@@ -758,10 +758,23 @@ void executeSuppressionActions(IEnumerable<Diagnostic> reportedDiagnostics, bool
                 var suppressors = this.Analyzers.OfType<DiagnosticSuppressor>();
                 if (concurrent)
                 {
-                    Parallel.ForEach(suppressors, suppressor =>
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: >Parallel.ForEach(suppressors, suppressor => [](start = 20, length = 43)

The motivation for this change is not obvious. Could you please share some details?

Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: `OperationCanceledException` during the suppressor execution leads to it being wrapped in an `AggregateException` by `Parallel.ForEach`, which ends up being reported as an NFW by our exception handlers, see https://github.com/dotnet/roslyn/issues/41713#issuecomment-588505199.

This change switches to the task based approach used at other places in the driver, which also avoids this case. I can add a comment.

Comment (AlekseyTs) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: > This change switches to the task based approach used at other places in the driver, which also avoids this case. I can add a comment.

So, despite what the title of this PR says, this change prevents wrapping of an OperationCanceledException with AggregateException rather than does any kind of unwrapping. Please make sure this is reflected in the commit comment on merge.


---
In reply to: [384078808](https://github.com/dotnet/roslyn/pull/41892#discussion_r384078808) [](ancestors = 384078808)

Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: Ah yes, that was my previous attempt. Let me update the PR title. I'll also update the commit comment prior to merge.

File: src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs [hunk 6]
```diff
@@ -758,10 +758,26 @@ void executeSuppressionActions(IEnumerable<Diagnostic> reportedDiagnostics, bool
...
-                    });
+                        foreach (var suppressor in suppressors)
+                        {
+                            var task = Task.Run(
+                                () => AnalyzerExecutor.ExecuteSuppressionAction(suppressor, getSuppressableDiagnostics(suppressor)),
+                                AnalyzerExecutor.CancellationToken);
+                            tasks.Add(task);
+                        }
+
+                        Task.WaitAll(tasks.ToArray(), AnalyzerExecutor.CancellationToken);
```
Comment (sharwell) [inline src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: 📝 I believe `Task.WaitAll` has exactly the same exception behavior as `Parallel.ForEach`.

Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: I verified the added test fails prior to this change - the invoked code was throwing an `AggregateException`, but now throws `OperationCanceledException`.

Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: Tagging @stephentoub to confirm the semantics of `Task.WaitAll`. I see under the debugger that `OperationCanceledException` thrown from any of tasks is propagated as `OperationCanceledException` itself, not wrapped within an `AggregateException`. We'd still like to know if this is indeed a guarantee from the API, not just a specific instance where this behavior is seen on cancellation.

Comment (stephentoub) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: Yes, assuming the wait itself was canceled and the only tasks that didn't complete successfully were canceled:
https://github.com/dotnet/runtime/blob/4807684b13d473c19121fbe757296e7607f3cabf/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L4727-L4735

Comment (mavasani) [reply src/Compilers/Core/Portable/DiagnosticAnalyzer/AnalyzerDriver.cs]: Thanks @stephentoub.

@sharwell Are you fine to sign off on the changes?
