### PR TITLE
Fix temp creation with `in` parameters

### LINKED ISSUE #29371: `in` arguments crash the compiler when temp stores are required
When trying to build one of my solution's code libraries, csc.exe exits with errorlevel 0x‭80131623‬, and 'dotnet build shows these stack traces:

```
C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Roslyn\Microsoft.CSharp.Core.targets(52,5): error : FailFast: System.InvalidOperationException: Unexpected value '4' of type 'Microsoft.CodeAnalysis.RefKind' [E:\projects\testframework-wow\src\Blizzard.TestFramework.WoW\Blizzard.TestFramework.WoW.csproj]
C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.SyntheticBoundNodeFactory.StoreToTemp(BoundExpression argument, BoundAssignmentOperator&amp; store, RefKind refKind, SynthesizedLocalKind kind, SyntaxNode syntaxOpt) [E:\projects\testframework-wow\src\Blizzard.TestFramework.WoW\Blizzard.TestFramework.WoW.csproj]
C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.LocalRewriter.BuildStoresToTemps(Boolean expanded, ImmutableArray`1 argsToParamsOpt, ImmutableArray`1 parameters, ImmutableArray`1 argumentRefKinds, ImmutableArray`1 rewrittenArguments, Boolean forceLambdaSpilling, BoundExpression[] arguments, ArrayBuilder`1 refKinds, ArrayBuilder`1 storesToTemps) [E:\projects\testframework-wow\src\Blizzard.TestFramework.WoW\Blizzard.TestFramework.WoW.csproj]
C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.LocalRewriter.MakeArguments(SyntaxNode syntax, ImmutableArray`1 rewrittenArguments, Symbol methodOrIndexer, MethodSymbol optionalParametersMethod, Boolean expanded, ImmutableArray`1 argsToParamsOpt, ImmutableArray`1&amp; argumentRefKindsOpt, ImmutableArray`1&amp; temps, Boolean invokedAsExtensionMethod, ThreeState enableCallerInfo) [E:\projects\testframework-wow\src\Blizzard.TestFramework.WoW\Blizzard.TestFramework.WoW.csproj]
C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitObjectCreationExpression(BoundObjectCreationExpression node) [E:\projects\testframework-wow\src\Blizzard.TestFramework.WoW\Blizzard.TestFramework.WoW.csproj]
C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundObjectCreationExpression.Accept(BoundTreeVisitor visitor) [E:\projects\testframework-wow\src\Blizzard.TestFramework.WoW\Blizzard.TestFramework.WoW.csproj]
C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node) [E:\projects\testframework-wow\src\Blizzard.TestFramework.WoW\Blizzard.TestFramework.WoW.csproj]
C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32&amp; recursionDepth, BoundExpression node) [E:\projects\testframework-wow\src\Blizzard.TestFramework.WoW\Blizzard.TestFramework.WoW.csproj]
C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitExpressionImpl(BoundExpression node) [E:\projects\testframework-wow\src\Blizzard.TestFramework.WoW\Blizzard.TestFramework.WoW.csproj]
C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Visit(BoundNode node) [E:\projects\testframework-wow\src\Blizzard.TestFramework.WoW\Blizzard.TestFramework.WoW.csproj]
C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.DoVisitList[T](ImmutableArray`1 list) [E:\projects\testframework-wow\src\Blizzard.TestFramework.WoW\Blizzard.TestFramework.WoW.csproj]
C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitObjectCreationExpression(BoundObjectCreationExpression node) [E:\projects\testframework-wow\src\Blizzard.TestFramework.WoW\Blizzard.TestFramework.WoW.csproj]
C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundObjectCreationExpression.Accept(BoundTreeVisitor visitor) [E:\projects\testframework-wow\src\Blizzard.TestFramework.WoW\Blizzard.TestFramework.WoW.csproj]
C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node) [E:\projects\testframework-wow\src\Blizzard.TestFramework.WoW\Blizzard.TestFramework.WoW.csproj]
C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32&amp; recursionDepth, BoundExpression node) [E:\projects\testframework-wow\src\Blizzard.TestFramework.WoW\Blizzard.TestFramework.WoW.csproj]
C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitExpressionImpl(BoundExpression node) [E:\projects\testframework-wow\src\Blizzard.TestFramework.WoW\Blizzard.TestFramework.WoW.csproj]
C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.LocalRewriter.Visit(BoundNode node) [E:\projects\testframework-wow\src\Blizzard.TestFramework.WoW\Blizzard.TestFramework.WoW.csproj]
C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.DoVisitList[T](ImmutableArray`1 list) [E:\projects\testframework-wow\src\Blizzard.TestFramework.WoW\Blizzard.TestFramework.WoW.csproj]
C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.LocalRewriter.VisitCall(BoundCall node) [E:\projects\testframework-wow\src\Blizzard.TestFramework.WoW\Blizzard.TestFramework.WoW.csproj]
C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundCall.Accept(BoundTreeVisitor visitor) [E:\projects\testframework-wow\src\Blizzard.TestFramework.WoW\Blizzard.TestFramework.WoW.csproj]
C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node) [E:\projects\testframework-wow\src\Blizzard.TestFramework.WoW\Blizzard.TestFramework.WoW.csproj]
C:\Program Files\dotnet\sdk\2.1.400-preview-009171\Roslyn\Microsoft.CSharp.Core.targets(52,5): error :    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32&amp; recursionDepth, BoundExpression node) [E:\projects\testframework-wow\src\Blizzard.TestFramework.WoW\Blizzard.TestFramework.WoW.csproj]
...
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/306848/unexpected-value-4-of-type-microsoftcodeanalysisre.html
VSTS ticketId: 659932_
_These are the original issue comments:_

Daniel Hobbs on 8/15/2018, 08:47 AM (2 days ago): I had a similar problem. (Unexpected value '4' of type 'Microsoft.CodeAnalysis.RefKind') I think it may be due to lowering with 'in'. I'm on VS 15.8. Here is a repro.

```C#
public readonly struct S
{        
    private static readonly S s_Default = default;        
    public static ref readonly S Default => ref s_Default;
}    
public class C
{
    public C(in S s, int i = 0)\{ }    
}    
public static class Foo 
{        
    // Crashes CSC - "csc.exe" exited with code -2146232797        
    public static C Instance { get; } = new C(s: in S.Default); // use 'in' and omit optional arg    
}
```

_These are the original issue solutions:_
(no solutions)

### PR DESCRIPTION
**Pull request by agocke**
There's a variety of cases in the compiler where we need to store an
expression into a temporary variable, e.g. to sequence side effects
in the right order. This code was not adjusted to deal with `in`
parameters, so it exhibited various pathologies.

The first case is the simplest -- sometimes when using the "explicit in"
modifier on an argument, the temp creation routine would simply crash.

The other cases are more subtle and mostly have to do with whether or
not the temp is created as a ref local or regular local. This is
specific to the "implicit in", where the "in" keyword is not mentioned
on the argument. In this case, the semantics for the call should be that
the argument is passed by-ref without storing to a copy unless
absolutely necessary. Absolutely necessary in this case is defined as 1)
the argument is an rvalue or 2) the argument requires a conversion to
the parameter type.

A lot of this knowledge was already present in CodeGen, but not available
in lowering, so I've pulled out the HasHome helper to Binding, as I felt that
was the best place for the common code.

Fixes #29371

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs [hunk 1]
```diff
@@ -1280,12 +1280,17 @@ internal static BoundExpression NullOrDefault(TypeSymbol typeSymbol, SyntaxNode
                 case RefKind.Out:
                     refKind = RefKind.Ref;
                     break;
+
+                // "in" arguments are spilled by-value, while "strict-in" arguments are
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs]: Can we use the terms "implicit in" and "explicit in". I think it's a bit clearer.

File: src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs [hunk 2]
```diff
@@ -1280,12 +1280,17 @@ internal static BoundExpression NullOrDefault(TypeSymbol typeSymbol, SyntaxNode
...
+                // spilled by-ref. It's the responsibility of the caller to determine
+                // whether or not their argument can be spilled by-ref.
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs]: It's unclear if the second sentence refers to explicit or implicit in arguments.

File: src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs [hunk 3]
```diff
@@ -1280,12 +1280,17 @@ internal static BoundExpression NullOrDefault(TypeSymbol typeSymbol, SyntaxNode
...
                 case RefKind.In:
-                    if (argument.GetRefKind() == RefKind.None)
-                    {
-                        refKind = RefKind.None;
-                    }
+                    refKind = RefKind.None;
                     break;
+                case RefKindExtensions.StrictIn:
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs]: Oh hmm, guess we did call this strict in.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenInParametersTests.cs [hunk 4]
```diff
@@ -11,6 +11,493 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+  IL_0007:  ldarg.1
+  IL_0008:  ldlen
+  IL_0009:  conv.i4
+  IL_000a:  call       ""void System.Console.WriteLine(int)""
+  IL_000f:  ret
+}");
+        }
+
+        [Fact]
+        public void InParamReorder()
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenInParametersTests.cs]: Please add a test where there are three parameters that require a reorder while building for release. That will force us to spill at least two temporaries. Wanted to have a test that ensures the temporary optimizer doesn't incorrectly re-use a slot here.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenInParametersTests.cs [hunk 5]
```diff
@@ -11,6 +11,493 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+  IL_0005:  newobj     ""C..ctor(in int, int)""
+  IL_000a:  pop
+  IL_000b:  ret
+}");
+        }
+
+        [Fact]
+        public void InParamCollectionInitializerOptionalArg()
+        {
+            var comp = CompileAndVerify(@"
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenInParametersTests.cs]: Why didn't you verify the output on this test?

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenInParametersTests.cs [hunk 6]
```diff
@@ -11,6 +11,493 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+  IL_0007:  ldarg.1
+  IL_0008:  call       ""void System.Console.WriteLine(int)""
+  IL_000d:  ret
+}");
+        }
+
+        [Fact]
+        public void InParamCtorOptionalArg()
+        {
+            var comp = CompileAndVerify(@"
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenInParametersTests.cs]: Why didn't you verify the output here?

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenInParametersTests.cs [hunk 7]
```diff
@@ -11,6 +11,493 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+
+    static void M(in int x, in int y)
+    {
+        Console.WriteLine(x);
+        Console.WriteLine(y);
+    }
+}", expectedOutput: @"GetField 0
+GetField 1
+2
+2");
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenInParametersTests.cs]: This doesn't really tell us what order the side effects occured in though. Consider adding a parameter to `GetField` that can also be printed to ensure side effects happen in the correct order.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenInParametersTests.cs [hunk 8]
```diff
@@ -11,6 +11,493 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+
+    public C(in int x, in int y)
+    {
+        Console.WriteLine(x);
+        Console.WriteLine(y);
+    }
+}", expectedOutput: @"GetField 0
+GetField 1
+2
+2");
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenInParametersTests.cs]: Same feedback about the reordering not being pproperly vetted here.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs [hunk 9]
```diff
@@ -260,7 +262,8 @@ private BoundExpression VisitAssignmentOperator(BoundAssignmentOperator node, bo
             ImmutableArray<int> argsToParamsOpt,
             BoundExpression rewrittenRight,
             TypeSymbol type,
-            bool used)
+            bool used,
+            Binder argumentsBinderOpt)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs]: Rather than an opt-suffix why not make this an optional parameter?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs [hunk 10]
```diff
@@ -675,13 +687,16 @@ private static ImmutableArray<RefKind> GetRefKindsOrNull(ArrayBuilder<RefKind> r
...
             bool forceLambdaSpilling,
+            Binder argumentsBinderOpt,
             /* out */ BoundExpression[] arguments,
             /* out */ ArrayBuilder<RefKind> refKinds,
             /* out */ ArrayBuilder<BoundAssignmentOperator> storesToTemps)
         {
             Debug.Assert(refKinds.Count == arguments.Length);
             Debug.Assert(storesToTemps.Count == 0);
 
+            var discardedDiags = DiagnosticBag.GetInstance();
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: Given the multiple return paths in this method did you consider a try / finally to free this up?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs [hunk 11]
```diff
@@ -697,7 +712,8 @@ private static ImmutableArray<RefKind> GetRefKindsOrNull(ArrayBuilder<RefKind> r
                 // Except for async stack spilling which needs to know whether arguments were originally passed as "In" and must obey "no copying" rule.
                 if (paramRefKind == RefKind.In)
                 {
-                    argRefKind = argRefKind == RefKind.None ? paramRefKind : RefKindExtensions.StrictIn;
+                    Debug.Assert(argRefKind == RefKind.None || argRefKind == RefKind.In);
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: Should we also assert here that `argRefKind != RefKind.None || !(argumentsBinderOpt is null)`. Once there is any implicit `in` then we need to ensure that a binder was passed down.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs [hunk 12]
```diff
@@ -736,20 +753,44 @@ private static ImmutableArray<RefKind> GetRefKindsOrNull(ArrayBuilder<RefKind> r
...
 
+            discardedDiags.Free();
+
             return;
 
             bool isLambdaConversion(BoundExpression expr)
                 => expr is BoundConversion conv && conv.ConversionKind == ConversionKind.AnonymousFunction;
         }
 
+        private static bool InArgumentRequiresCopy(
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: Can this be a local function?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs [hunk 13]
```diff
@@ -287,6 +287,7 @@ private BoundIndexerAccess TransformIndexerAccess(BoundIndexerAccess indexerAcce
                 argumentRefKinds,
                 rewrittenArguments,
                 forceLambdaSpilling: true, // lambdas must produce exactly one delegate so they must be spilled into a temp
+                indexerAccess.BinderOpt,
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_CompoundAssignmentOperator.cs]: Should we add an assert that this is non-null.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs [hunk 14]
```diff
@@ -208,7 +209,8 @@ private BoundExpression VisitAssignmentOperator(BoundAssignmentOperator node, bo
                             indexerAccess.ArgsToParamsOpt,
                             rewrittenRight,
                             type,
-                            used);
+                            used,
+                            indexerAccess.BinderOpt);
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs]: Should we assert this is not null?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs [hunk 15]
```diff
@@ -260,7 +262,8 @@ private BoundExpression VisitAssignmentOperator(BoundAssignmentOperator node, bo
             ImmutableArray<int> argsToParamsOpt,
             BoundExpression rewrittenRight,
             TypeSymbol type,
-            bool used)
+            bool used,
+            Binder argumentsBinderOpt)
         {
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_AssignmentOperator.cs]: Should we add an assert that either this is not an index property or `argumentsBinderOpt` isn't `null`?

**Comment by jaredpar** [comment]
Done with review pass iteration 1

**Comment by AlekseyTs** [comment]
> Fortunately, the IOperation code caused us
to store Binders on the BoundNodes, so we can reconstitute the
information necessary (specifically, whether or not the argument is an
lvalue).

I think we should try to avoid relying on the Binder. Elsewhere in the lowering are we making a decision whether to allocate a temp local for an argument corresponding to an 'in' parameter? I mean for the case that doesn't require any special handling for side-effects. It feels like we should be able to reuse the same logic.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs [hunk 16]
```diff
@@ -736,20 +753,44 @@ private static ImmutableArray<RefKind> GetRefKindsOrNull(ArrayBuilder<RefKind> r
...
+            BoundExpression argumentExpr,
+            Binder argumentsBinder,
+            DiagnosticBag diagnostics)
+            => argumentExpr.Kind == BoundKind.Conversion || !argumentsBinder.CheckValueKind(
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: >=> argumentExpr.Kind == BoundKind.Conversion || !argumentsBinder.CheckValueKind( [](start = 12, length = 80)

Consider using regular body, the expression is not trivial and is quite long.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs [hunk 17]
```diff
@@ -736,20 +753,44 @@ private static ImmutableArray<RefKind> GetRefKindsOrNull(ArrayBuilder<RefKind> r
...
             return;
 
             bool isLambdaConversion(BoundExpression expr)
                 => expr is BoundConversion conv && conv.ConversionKind == ConversionKind.AnonymousFunction;
         }
 
+        private static bool InArgumentRequiresCopy(
+            BoundExpression argumentExpr,
+            Binder argumentsBinder,
+            DiagnosticBag diagnostics)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: >DiagnosticBag diagnostics [](start = 12, length = 25)

It looks like all consumers discard diagnostics. Consider removing this parameter and discarding diagnostics locally. This might simplify consumers.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenInParametersTests.cs [hunk 18]
```diff
@@ -11,6 +11,493 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+        M(in x);
+    }
+    static void M(in int x, int y = 0)
+    {
+        Console.WriteLine(x);
+        Console.WriteLine(y);
+    }
+}", expectedOutput: @"1
+0");
+            comp.VerifyIL("C.M", @"
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenInParametersTests.cs]: >C.M [](start = 27, length = 3)

Is IL of this method really interesting? It feels like we should be checking IL for "Main".

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenInParametersTests.cs [hunk 19]
```diff
@@ -11,6 +11,493 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+    public static ref S GetField()
+    {
+        Console.WriteLine(""GetField "" + _field.X++);
+        return ref _field;
+    }
+
+    public static void Main()
+    {
+        var c = new C();
+        _ = c[y: GetField().X, x: GetField().X + 1];
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenInParametersTests.cs]: >c[y: GetField().X, x: GetField().X + 1] [](start = 12, length = 39)

Consider also testing scenario ```c[y: GetField().X + 1, x: GetField().X]```

**Comment by AlekseyTs** [comment]
Consider adding tests around readonly fields when they are passed to ```in``` parameters inside and outside of constructor.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1)

File: src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs [hunk 20]
```diff
@@ -12,6 +12,7 @@
 using Microsoft.CodeAnalysis.PooledObjects;
 using Microsoft.CodeAnalysis.Text;
 using Roslyn.Utilities;
+using static Microsoft.CodeAnalysis.CSharp.Binder;
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs]: Why is this `using static` needed?

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 21]
```diff
@@ -2863,5 +2864,232 @@ private static bool CheckValEscape(ImmutableArray<BoundExpression> expressions,
...
+
+        /// <summary>
+        /// Special HasHome for fields. 
+        /// Fields have readable homes when they are not constants.
+        /// Fields have writeable homes unless they are readonly and used outside of the constructor.
+        /// </summary>
+        private static bool HasHome(
+            BoundFieldAccess fieldAccess,
+            AddressKind addressKind,
+            MethodSymbol methodOpt,
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: Where is `null` ever given for `methodOpt`?

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs [hunk 22]
```diff
@@ -2863,5 +2864,232 @@ private static bool CheckValEscape(ImmutableArray<BoundExpression> expressions,
...
+        internal static bool IsReadOnly(AddressKind addressKind) => addressKind >= AddressKind.ReadOnly;
+
+        /// <summary>
+        /// Checks if expression directly or indirectly represents a value with its own home. In
+        /// such cases it is possible to get a reference without loading into a temporary.
+        /// </summary>
+        internal static bool HasHome(
+            BoundExpression expression,
+            AddressKind addressKind,
+            MethodSymbol methodOpt,
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: Where is `null` ever given for `methodOpt`?

**Comment by jaredpar** [comment]
Done with review pass (iteration 3)

File: src/Compilers/CSharp/Portable/CodeGen/CodeGenerator.cs [hunk 23]
```diff
@@ -186,10 +183,10 @@ private LocalDefinition LazyReturnTemp
             }
         }
 
-        private bool IsStackLocal(LocalSymbol local)
-        {
-            return _stackLocals != null && _stackLocals.Contains(local);
-        }
+        internal static bool IsStackLocal(LocalSymbol local, HashSet<LocalSymbol> _stackLocalsOpt)
+            => _stackLocalsOpt?.Contains(local) ?? false;
```
[the remark this answers is not in the document]
Comment (agocke) [reply src/Compilers/CSharp/Portable/CodeGen/CodeGenerator.cs]: I'll change the parameter name, but _stackLocals can be null even in old code. It's set to null if there are no locals in the block.

File: src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs (hunk 20 above)
Comment (agocke) [reply src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs]: This code uses `AddressKind` a lot, which has been moved.

File: src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs (hunk 21 above)
Comment (agocke) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: There were a couple places, but it turned out the cause of all of them was the AwaitExpressionSpiller. That was easy to fix up, so I've done that and removed the `Opt`. Note that this helper was previously used for Emit, so a `null` method is pretty rare, but if someone ends up using this, say, before initializers are lowered, this is actually a really common case.

Comment (jaredpar) [reply src/Compilers/CSharp/Portable/Binder/Binder.ValueChecks.cs]: > Note that this helper was previously used for Emit, so a null method is pretty rare

Where can it be null for Emit?

---
In reply to: [215768535](https://github.com/dotnet/roslyn/pull/29591#discussion_r215768535) [](ancestors = 215768535)

**Comment by agocke** [comment]
@jaredpar Addressed comments

**Comment by VSadov** [comment]
Since the fix no longer depends on the binders to figure l-value flavors, the PR description might need updating.

**Comment by agocke** [comment]
@VSadov Good point. I've updated the description to note that I lifted HasHome into binding instead.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectOrCollectionInitializerExpression.cs [hunk 24]
```diff
@@ -372,11 +382,15 @@ private BoundExpression MakeCollectionInitializer(BoundExpression rewrittenRecei
 
         private ImmutableArray<BoundExpression> EvaluateSideEffectingArgumentsToTemps(
                                                  ImmutableArray<BoundExpression> args,
+                                                 ImmutableArray<RefKind> paramRefKindsOpt,
+                                                 Binder argumentsBinderOpt,
```
Comment (VSadov) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectOrCollectionInitializerExpression.cs]: >Binder argumentsBinderOpt [](start = 49, length = 25)

Unused?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectOrCollectionInitializerExpression.cs [hunk 25]
```diff
@@ -372,11 +382,15 @@ private BoundExpression MakeCollectionInitializer(BoundExpression rewrittenRecei
...
                                                  ArrayBuilder<BoundExpression> sideeffects,
                                                  ref ArrayBuilder<LocalSymbol> temps)
         {
             ArrayBuilder<BoundExpression> newArgs = null;
 
+            var discarded = DiagnosticBag.GetInstance();
+
```
Comment (VSadov) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_ObjectOrCollectionInitializerExpression.cs]: This looks no longer needed.

**Comment by agocke** [comment]
@jaredpar Is this approved for 15.9?

**Comment by jaredpar** [comment]
@agocke no. I'm waiting for @AlekseyTs before I submit.

File: src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs [hunk 26]
```diff
@@ -1275,25 +1275,35 @@ internal static BoundExpression NullOrDefault(TypeSymbol typeSymbol, SyntaxNode
 #endif
             )
         {
+            MethodSymbol containingMethod = this.CurrentFunction;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs]: >this.CurrentFunction [](start = 44, length = 20)

Is this set to constructor for constructor initializer and field initializers?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs [hunk 27]
```diff
@@ -105,7 +115,7 @@ private BoundExpression VisitIndexerAccess(BoundIndexerAccess node, bool isLeftO
                 // This node will be rewritten with MakePropertyAssignment when rewriting the enclosing BoundAssignmentOperator.
 
                 return oldNodeOpt != null ?
-                    oldNodeOpt.Update(rewrittenReceiver, indexer, rewrittenArguments, argumentNamesOpt, argumentRefKindsOpt, expanded, argsToParamsOpt, null, isLeftOfAssignment, type) :
+                    oldNodeOpt.Update(rewrittenReceiver, indexer, rewrittenArguments, argumentNamesOpt, argumentRefKindsOpt, expanded, argsToParamsOpt, oldNodeOpt.BinderOpt, isLeftOfAssignment, type) :
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs]: >oldNodeOpt.BinderOpt [](start = 152, length = 20)

Can we revert this change?

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenInParametersTests.cs [hunk 28]
```diff
@@ -11,6 +11,643 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
...
+{
+    private static readonly int _f = 0;
+    public C()
+    {
+        M(y: _f, x: _f + 1);
+    }
+
+    public static void Main()
+    {
+        M(y: _f, x: _f + 1);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenInParametersTests.cs]: >M(y: _f, x: _f + 1); [](start = 8, length = 20)

Would it be interesting to test this case with explicit ```in``` modifiers at the call site?

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs (hunk 27 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs]: > We can... but doesn't the old behavior look wrong to you?

I think the binder there is for IOperation factory, which is supposed to deal with nodes produced by initial binding. 

---
In reply to: [216492768](https://github.com/dotnet/roslyn/pull/29591#discussion_r216492768) [](ancestors = 216492768)

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 7)

File: src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs (hunk 26 above)
Comment (agocke) [reply src/Compilers/CSharp/Portable/Lowering/SyntheticBoundNodeFactory.cs]: I added a test for this, you should see if it matches what you were thinking. (I also verified that, yes, the value of `containingMethod` is the constructor here).

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs (hunk 27 above)
Comment (agocke) [reply src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_IndexerAccess.cs]: Ah, I see. I'll revert.
