### PR TITLE
Ensure script compilations properly inherit return type from first compilation

### LINKED ISSUE #17403: Script compilations created from a previous compilation have incorrect return type
We are now finally able to use the Roslyn 2.0 NuGet for Xamarin Workbooks, which means I can finally leverage my work for [supporting compilations against a target (not host) corlib](https://github.com/dotnet/roslyn/pull/8507).

Unfortunately the tests I wrote for that fix were not extensive enough to catch an issue where subsequent compilations result in an implicit reference to host corlib and not the target corlib.

This is due to the implementation of `ScriptCompilationInfo.ReturnType`, which was desired to never return `null`:

```csharp
public Type ReturnType => ReturnTypeOpt ?? typeof(object);
```

I did not catch all the places in Roslyn that were using `ReturnType` but should now be using `ReturnTypeOpt`:

* `CSharpScriptCompilationInfo.WithPreviousScriptCompilation`
* `CSharpCompilation.WithScriptCompilationInfo`
* `VisualBasicScriptCompilationInfo.WithPreviousScriptCompilation`
* `VisualBasicCompilation.WithScriptCompilationInfo`

This is how the bug ends up manifesting in Workbooks:

screen shot 2017-02-26 at 3 44 52 pm

### PR DESCRIPTION
**Pull request by abock**
This fixes #17403 which prevents Xamarin Workbooks from moving to the upstream Roslyn 2.0 NuGet. Related to, and expands upon, #8507 _(Compilation: use System.Object from target corlib)_.

### Before

screen shot 2017-02-26 at 3 44 52 pm

### After

screen shot 2017-02-26 at 3 51 05 pm

### CODE REVIEW

File: src/Compilers/CSharp/Test/Symbol/Compilation/CompilationAPITests.cs [hunk 1]
```diff
@@ -1592,21 +1593,42 @@ public void CrossCorlibSystemObjectReturnType_Script()
             //
             // In the original bug, Xamarin iOS, Android, and Mac Mobile profile corlibs were
             // realistic cross-compilation targets.
-            var compilation = CSharpCompilation.CreateScriptCompilation(
-                "submission-assembly",
-                references: new [] { MinAsyncCorlibRef },
+
+            Action<CSharpCompilation> AssertCompilationCorlib = compilation =>
```
Comment (tmat) [inline src/Compilers/CSharp/Test/Symbol/Compilation/CompilationAPITests.cs]: Use local function instead of lambda:

```C#
void AssertCompilationCorlib(CSharpCompilation compilation)
{
...
}
```

**Comment by tmat** [comment]
test windows_release_vs-integration_prtest please

**Comment by tmat** [comment]
👍

File: src/Compilers/CSharp/Test/Symbol/Compilation/CompilationAPITests.cs (hunk 1 above)
Comment (abock) [inline src/Compilers/CSharp/Test/Symbol/Compilation/CompilationAPITests.cs]: Nice. I wasn't sure if I could use C# 7 features yet 😄 .

Comment (abock) [inline src/Compilers/CSharp/Test/Symbol/Compilation/CompilationAPITests.cs]: Apparently not. If I convert this to a local function, VS2015 cannot compile it.

Comment (abock) [inline src/Compilers/CSharp/Test/Symbol/Compilation/CompilationAPITests.cs]: Fixed.

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-interactive
