### PR TITLE
Handle out parameters in cross-language scenarios

### LINKED ISSUE #599: Cross-language references to C# methods with out parameters are not found by FAR, GTD, etc.
Ported from TFS WorkItem: **829965**

------------------------------

**Repro Steps:**

**Affected Branch:** <BR>**Affected Build:** <BR>**Affected Product Language:** 

<BR>**Steps to reproduce:**<BR><BR>1. Copy/paste into C# class library:

&nbsp;
<PRE style="FONT-SIZE: 16px; FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink"><SPAN style="COLOR: blue">public</SPAN> <SPAN style="COLOR: blue">class</SPAN> <SPAN style="COLOR: #2b91af">C</SPAN>
<SPAN style="COLOR: black">{</SPAN>
    <SPAN style="COLOR: blue">public</SPAN> <SPAN style="COLOR: blue">void</SPAN> <SPAN style="COLOR: black">WithoutOut</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">int</SPAN> <SPAN style="COLOR: black">x</SPAN><SPAN style="COLOR: black">)</SPAN>
    <SPAN style="COLOR: black">{</SPAN>
    <SPAN style="COLOR: black">}</SPAN>
 
    <SPAN style="COLOR: blue">public</SPAN> <SPAN style="COLOR: blue">void</SPAN> <SPAN style="COLOR: black">WithOut</SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: blue">out</SPAN> <SPAN style="COLOR: blue">int</SPAN> <SPAN style="COLOR: black">x</SPAN><SPAN style="COLOR: black">)</SPAN>
    <SPAN style="COLOR: black">{</SPAN>
        <SPAN style="COLOR: black">x</SPAN> <SPAN style="COLOR: black">=</SPAN> <SPAN style="COLOR: black">1</SPAN><SPAN style="COLOR: black">;</SPAN>
    <SPAN style="COLOR: black">}</SPAN>
<SPAN style="COLOR: black">}</SPAN></PRE>

&nbsp;

2. Copy/paste into VB class library:

&nbsp;
<PRE style="FONT-SIZE: 16px; FONT-FAMILY: Consolas; BACKGROUND: white; COLOR: hotpink"><SPAN style="COLOR: blue">Class</SPAN> <SPAN style="COLOR: #2b91af">D</SPAN>
    <SPAN style="COLOR: blue">Sub</SPAN> <SPAN style="COLOR: black">T</SPAN><SPAN style="COLOR: black">()</SPAN>
        <SPAN style="COLOR: blue">Dim</SPAN> <SPAN style="COLOR: black">c</SPAN> <SPAN style="COLOR: black">=</SPAN> <SPAN style="COLOR: blue">New</SPAN> <SPAN style="COLOR: #2b91af">C</SPAN><SPAN style="COLOR: black">()</SPAN>
        <SPAN style="COLOR: black">c</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black"><FONT style="BACKGROUND-COLOR: #ff0000">WithOut</FONT></SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: black">1</SPAN><SPAN style="COLOR: black">)</SPAN>
        <SPAN style="COLOR: black">c</SPAN><SPAN style="COLOR: black">.</SPAN><SPAN style="COLOR: black"><FONT style="BACKGROUND-COLOR: #00ff00">WithoutOut</FONT></SPAN><SPAN style="COLOR: black">(</SPAN><SPAN style="COLOR: black">1</SPAN><SPAN style="COLOR: black">)</SPAN>
    <SPAN style="COLOR: blue">End</SPAN> <SPAN style="COLOR: blue">Sub</SPAN>
<SPAN style="COLOR: blue">End</SPAN> <SPAN style="COLOR: blue">Class</SPAN></PRE>

&nbsp;

3. Add a reference from the VB class library to the C# class library.

&nbsp;

4. Invoke GTD on the call to c.WithOut() in the VB file.

&nbsp;

Expected: GTD should take you to the source location in the C# file

Actual: Metadata As Source

------------------------------

**Revisions:**

1) Created By David Poeschl (11/21/2013 8:20:30 PM)

------------------------------

2) Edited By Andrew Casey (ROSLYN) (6/13/2014 4:03:24 PM)

I hit this while trying to port some code from C# to VB (in Roslyn).

------------------------------

3) Edited By Andrew Casey (ROSLYN) (11/12/2014 10:52:46 AM)

Still happening.&nbsp; Tried to GTD on 

<font color="#2b91af" face="Courier New" size=1><font color="#2b91af" face="Courier New" size=1><font color="#2b91af" face="Courier New" size=1>CustomDebugInfoReader</font></font></font><font face="Courier New" size=1><font face="Courier New" size=1>.TryParseVisualBasicImportString</font></font>
&nbsp;in VB.

------------------------------

4) Edited By Andrew Casey (ROSLYN) (2/11/2015 12:24:55 PM)

Guess the SymbolId for the method has RefKind &quot;Ref&quot; instead of &quot;Out&quot;.&nbsp; Presumably, the comparison needs to be more forgiving for VB symbols.

------------------------------

### PR DESCRIPTION
**Pull request by amcasey**
Ignore the difference between ```ref``` and ```out``` in ```SymbolKey``` and ```SymbolEquivalenceComparer``` since two overloads cannot differ by only RefKind.  This prevents VB FAR and GTD from being too discerning and missing matching references.

That is, without this fix, if you attempt to find all references to a C# method with an out parameter, no VB references will be reported.

Caveat: Switching between ```ref``` and ```out``` is still a rude edit, so EnC sets a switch to force consideration of the difference.

Fixes #599.

### CODE REVIEW

**Comment by amcasey** [comment]
Relevant leads: @ManishJayaswal @Pilchie 
Potential code reviewers: @jasonmalinowski @tmat @dpoeschl 
Buddy tester: TBD

File: src/Workspaces/Core/Portable/Shared/Utilities/SymbolEquivalenceComparer.ParameterSymbolEqualityComparer.cs [hunk 1]
```diff
@@ -78,5 +81,12 @@ public int GetHashCode(IParameterSymbol x)
                     _symbolEqualityComparer.SignatureTypeEquivalenceComparer.GetHashCode(x.Type));
             }
         }
+
+        public static bool AreEquivalent(RefKind rk1, RefKind rk2, bool distinguishRefFromOut)
+        {
+            return distinguishRefFromOut
+                ? rk1 == rk2
+                : (rk1 == RefKind.None) == (rk2 == RefKind.None);
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Shared/Utilities/SymbolEquivalenceComparer.ParameterSymbolEqualityComparer.cs]: There's already that .IsRefOrOut helper being used just a few lines prior. Please use for consistency's sake.

**Comment by brettfo** [comment]
Re: buddy test: :shipit:

Confirmed GTD, FAR, Progression, and inline rename all work as expected.

File: src/Workspaces/Core/Portable/SymbolId/SymbolKey.cs [hunk 2]
```diff
@@ -225,8 +226,10 @@ private static SymbolKeyResolution CreateSymbolInfo(ISymbol[] symbols)
 
             for (int i = 0; i < refKinds.Length; i++)
             {
+                // The ref-out distinction is not interesting for SymbolKey because you can't overload
+                // based on the difference.
                 var parameter = parameters[i];
-                if (refKinds[i] != parameters[i].RefKind)
+                if (!SymbolEquivalenceComparer.AreEquivalent(refKinds[i], parameter.RefKind, distinguishRefFromOut: false))
```
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/SymbolId/SymbolKey.cs]: Might be best to name your new method AreRefKindsEquivalent...I read this diff as you're invoking the entire symbol asking if two symbols are equivalent.

**Comment by jasonmalinowski** [comment]
Other than this pull request reminds me of the existence of SymbolKey and SymbolEquivalenceComparer, :+1:.

File: src/Workspaces/Core/Portable/Shared/Utilities/SymbolEquivalenceComparer.ParameterSymbolEqualityComparer.cs (hunk 1 above)
Comment (jasonmalinowski) [inline src/Workspaces/Core/Portable/Shared/Utilities/SymbolEquivalenceComparer.ParameterSymbolEqualityComparer.cs]: I can't read code, sorry.

**Comment by amcasey** [comment]
Thanks @brettfo!

File: src/Workspaces/Core/Portable/SymbolId/SymbolKey.cs (hunk 2 above)
Comment (amcasey) [inline src/Workspaces/Core/Portable/SymbolId/SymbolKey.cs]: Sure.

File: src/Workspaces/Core/Portable/Shared/Utilities/SymbolEquivalenceComparer.ParameterSymbolEqualityComparer.cs (hunk 1 above)
Comment (amcasey) [inline src/Workspaces/Core/Portable/Shared/Utilities/SymbolEquivalenceComparer.ParameterSymbolEqualityComparer.cs]: As we discussed offline, that helper is for parameters.

**Comment by dpoeschl** [comment]
:+1: Thanks for tackling this @amcasey!

**Comment by DustinCampbell** [comment]
Indeed. Thank you!

**Comment by MattGertz** [comment]
Approved 5/28 by ML Shiproom.

**Comment by Pilchie** [comment]
Thanks @amcasey.  :shipit:
