### PR TITLE
Track nullable state in try statements

### LINKED ISSUE #30561: Variable should be nullable outside try block if assigned nullable value inside try block
`s.Length` should result in a warning:
```c#
[System.Runtime.CompilerServices.NonNullTypes]
class C
{
    static void MayThrow()
    {
        throw null;
    }
    static int F()
    {
        string? s = "";
        try
        {
            s = null;
            MayThrow();
            s = "";
        }
        catch (System.Exception)
        {
        }
        return s.Length; // warning: possibly null
    }
}
```
Reported by @gafter.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #30561

### CODE REVIEW

**Comment by 333fred** [comment]
@gafter looks like there are some merge conflicts to resolve.

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs [hunk 1]
```diff
@@ -105,6 +119,80 @@ public override BoundNode VisitTryStatement(BoundTryStatement node)
             return null;
         }
 
+        protected Optional<TLocalState> _tryState;
+
+        private void VisitTryBlock0(BoundStatement tryBlock, BoundTryStatement node, ref TLocalState tryState)
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs]: >VisitTryBlock0 [](start = 21, length = 14)

Can we have a better name than 0? Really doesn't convey any information here.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 2]
```diff
@@ -51742,5 +51742,184 @@ static void Main()
...
+        {
+            var source =
+@"public static class Program
+{
+    public static int Main()
+    {
+        string? s = string.Empty;
+        try
+        {
+            s = null;
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Can you add a similar test where `s` is known not to be null before `MayThrow` so we can verify that behavior?

**Comment by 333fred** [comment]
Done review pass (commit 1)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 2 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Sure, adding `SetNullableStateInFinally_02b`, but in such a test the variable `s` would be `null` nowhere in the program.

**Comment by gafter** [comment]
@cston @333fred All comments have been addressed. Do you have any further comments?

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 2 above)
Comment (333fred) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Sorry, I might not have been clear. I mean something like this:

```c#
string? s = null;
try
{
    MayThrow();
    s = string.Empty;
    int i = s.Length; // No warning
}
// Catch and finally have warnings, and after try has warnings.
```

---
In reply to: [232778962](https://github.com/dotnet/roslyn/pull/31082#discussion_r232778962) [](ancestors = 232778962)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 3]
```diff
@@ -55966,5 +55966,227 @@ static void M(object x)
...
+        string? s = null;
+        try
+        {
+            MayThrow();
+            s = string.Empty;
+            _ = s.Length; // ok
+        }
+        catch (System.Exception)
+        {
+            _ = s.Length; // warning 1
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >_ = s.Length; // warning 1 [](start = 12, length = 26)

test idea: if we did `s = string.Empty;` here, I assume that warning 2 disappears.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 4]
```diff
@@ -55966,5 +55966,227 @@ static void M(object x)
...
+    public static int Main()
+    {
+        string? s = string.Empty;
+        try
+        {
+            s = null;
+            MayThrow();
+            s = string.Empty;
+        }
+        catch (System.Exception)
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >catch (System.Exception) [](start = 8, length = 24)

test ideas: 
Consider testing with `catch` that catches some other exception type? I think this will not affect the analysis, but when I saw the tests, I assumed that `System.Exception` was handled specially (as a catch all).

Also, consider some tests with multiple `catch` blocks.

File: src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs [hunk 5]
```diff
@@ -105,6 +119,80 @@ public override BoundNode VisitTryStatement(BoundTryStatement node)
...
+        protected Optional<TLocalState> _tryState;
+
+        private void VisitTryBlockWithUnassignments(BoundStatement tryBlock, BoundTryStatement node, ref TLocalState tryState)
+        {
+            if (trackUnassignments)
+            {
+                Optional<TLocalState> oldTryState = _tryState;
+                _tryState = AllBitsSet();
+                VisitTryBlock(tryBlock, node, ref tryState);
+                var tts = _tryState.Value;
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/FlowAnalysis/AbstractFlowPass.cs]: >tts [](start = 20, length = 3)

nit: even though this is moving existing code, consider giving `tts` and `ots` proper names.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 4 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: `System.Exception` is not handled specially.

Adding a test for multiple catch blocks.

Not adding nested scenarios because it is all compositional. There is no special handling of nesting for try blocks. Trying to test nesting of constructs would cause an explosion of the tests.

---
In reply to: [232864656](https://github.com/dotnet/roslyn/pull/31082#discussion_r232864656) [](ancestors = 232864656)

Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Actually, I will add some nested scenarios.  There is nesting-specific state handling code.

---
In reply to: [233151144](https://github.com/dotnet/roslyn/pull/31082#discussion_r233151144) [](ancestors = 233151144,232864656)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs (hunk 3 above)
Comment (jcouv) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Even `catch { }` will not catch everything?

---
In reply to: [232871216](https://github.com/dotnet/roslyn/pull/31082#discussion_r232871216) [](ancestors = 232871216,232855231)

Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Yes, `catch {}` will catch "everything" thrown.  However, it would be incorrect to treat that as a special case that suppresses the warning in the finally, as it is still possible for s to be null in the finally (because an exception could occur on entry to the catch clause).

---
In reply to: [233190864](https://github.com/dotnet/roslyn/pull/31082#discussion_r233190864) [](ancestors = 233190864,232871216,232855231)

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 6]
```diff
@@ -55966,5 +55966,669 @@ static void M(object x)
...
+            var comp = CreateCompilation(new[] { source }, options: WithNonNullTypesTrue());
+            comp.VerifyDiagnostics(
+                // (18,17): warning CS8602: Possible dereference of a null reference.
+                //             _ = s.Length; // warning
+                Diagnostic(ErrorCode.WRN_NullReferenceReceiver, "s").WithLocation(18, 17)
+                );
+        }
+
+        [Fact, WorkItem(30561, "https://github.com/dotnet/roslyn/issues/30561")]
+        public void SetNullableStateInNestedTry_01()
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >SetNullableStateInNestedTry_01 [](start = 20, length = 30)

@jcouv: this tests nested try statements as suggested.

Comment (jcouv) [reply src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: Got it. Thanks!

---
In reply to: [233200599](https://github.com/dotnet/roslyn/pull/31082#discussion_r233200599) [](ancestors = 233200599)

**Comment by gafter** [comment]
> Do we need to update the speclet for nullable to reflect this change, or is this already implied by the base spec?

The precise flow-analysis rules for nullable analysis are not specified, so there isn't anything to update.

**Comment by gafter** [comment]
@jaredpar For approval, please

**Comment by jaredpar** [comment]
approved
