### PR TITLE
Report erroneous implicit conversions in a switch expression

### LINKED ISSUE #40295: Roslyn silently fails to detect errors and can't emit module with invalid tuple conversions in switch expressions
**Version Used**: 

Microsoft Visual Studio Professional 2019 Preview
Version 16.5.0 Preview 1.0
VisualStudio.16.Preview/16.5.0-pre.1.0+29521.150
Microsoft .NET Framework
Version 4.8.03752

**Steps to Reproduce**:

Try to compile the following code:

```cs
class A
{
  public static extern implicit operator B(A a);
}

class B
{
  public static extern implicit operator B(A a);
}

class C
{
  static void M(string s)
  {
    (B, B) x = s switch { _ => (new A(), new A()), };
    x.Item1.ToString();
  }
}
```

**Expected Behavior**:
Roslyn shows some errors in this code as it's not clear which conversion it should use.

**Actual Behavior**:
No errors in the code. Compilation fails to emit the module.
```
      Error CS7038: Failed to emit module 'netcoreapp'.
```

**Notes**
I've tried to use this source in Roslyn's test sources and it seems that the following stack trace is to blame:
```
   at Microsoft.CodeAnalysis.CSharp.Binder.GenerateImplicitConversionError(DiagnosticBag diagnostics, SyntaxNode syntax, Conversion conversion, BoundExpression operand, TypeSymbol targetType) in C:\Work\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 2172
   at Microsoft.CodeAnalysis.CSharp.Binder.GenerateConversionForAssignment(TypeSymbol targetType, BoundExpression expression, DiagnosticBag diagnostics, Boolean isDefaultParameter, Boolean isRefAssignment) in C:\Work\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 1771
   at Microsoft.CodeAnalysis.CSharp.Binder.BindVariableDeclaration(SourceLocalSymbol localSymbol, LocalDeclarationKind kind, Boolean isVar, VariableDeclaratorSyntax declarator, TypeSyntax typeSyntax, TypeWithAnnotations declTypeOpt, AliasSymbol aliasOpt, DiagnosticBag diagnostics, Boolean includeBoundType, CSharpSyntaxNode associatedSyntaxNode) in C:\Work\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 1018
   at Microsoft.CodeAnalysis.CSharp.Binder.BindVariableDeclaration(LocalDeclarationKind kind, Boolean isVar, VariableDeclaratorSyntax declarator, TypeSyntax typeSyntax, TypeWithAnnotations declTypeOpt, AliasSymbol aliasOpt, DiagnosticBag diagnostics, Boolean includeBoundType, CSharpSyntaxNode associatedSyntaxNode) in C:\Work\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 918
   at Microsoft.CodeAnalysis.CSharp.Binder.BindDeclarationStatementParts(LocalDeclarationStatementSyntax node, DiagnosticBag diagnostics) in C:\Work\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 678
   at Microsoft.CodeAnalysis.CSharp.Binder.BindLocalDeclarationStatement(LocalDeclarationStatementSyntax node, DiagnosticBag diagnostics) in C:\Work\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 653
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in C:\Work\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 48
   at Microsoft.CodeAnalysis.CSharp.Binder.BindBlockParts(BlockSyntax node, DiagnosticBag diagnostics) in C:\Work\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 1696
   at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics) in C:\Work\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 1684
   at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics) in C:\Work\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 45
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode declaration, BlockSyntax blockBody, ArrowExpressionClauseSyntax expressionBody, DiagnosticBag diagnostics) in C:\Work\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 3238
   at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodBody(CSharpSyntaxNode syntax, DiagnosticBag diagnostics) in C:\Work\roslyn\src\Compilers\CSharp\Portable\Binder\Binder_Statements.cs:line 3186
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, DiagnosticBag diagnostics, ImportChain& importChain, Boolean& originalBodyNested, InitialState& forSemanticModel) in C:\Work\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 1674
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) in C:\Work\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 981
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) in C:\Work\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 507
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass22_0.<CompileNamedTypeAsTask>b__0() in C:\Work\roslyn\src\Compilers\CSharp\Portable\Compiler\MethodCompiler.cs:line 397
   at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0() in C:\Work\roslyn\src\Compilers\Core\Portable\InternalUtilities\UICultureUtilities.cs:line 139
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #40295

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 1]
```diff
@@ -2171,7 +2171,7 @@ internal BoundExpression GenerateConversionForAssignment(TypeSymbol targetType,
                         foreach (var arm in switchExpression.SwitchArms)
                         {
                             var armConversion = this.Conversions.ClassifyImplicitConversionFromExpression(arm.Value, targetType, ref useSiteDiagnostics);
-                            if (!armConversion.IsImplicit)
+                            if (!armConversion.IsImplicit || !armConversion.IsValid)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: >IsImplicit [](start = 47, length = 10)

Would it make sense to adjust behavior of ```IsImplicit``` to return ```false``` when conversion doesn't exist?

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1)

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: No.  From the language point of view, the conversion *does* exist, but produces an error.  Doing as you suggest would violate the language specification and it would be a (backward) breaking change in the language semantics.

Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs]: However, it is possible that the switch conversion itself should be considered to exist but not be valid when one of the element conversions exists but is not valid.  I'll make sure that is implemented and tested in a revision.

---
In reply to: [362603307](https://github.com/dotnet/roslyn/pull/40678#discussion_r362603307) [](ancestors = 362603307)

**Comment by gafter** [comment]
@AlekseyTs I think I've responded to your comments.  Do you have any other comments?
