### PR TITLE
Fixing parentheses simplification in the presence of a conditional member access.

### LINKED ISSUE #987: Inline Temporary Variable adds redundant parentheses for conditional access expression
Ported from TFS WorkItem: <b>1091928</b>

------------------------------

<p><b>Repro Steps:</b></p>
<P>1. Start with the following code:</P>
```csharp
class Program
{
    static void Main(string[] args)
    {
        var x = args.Length.ToString();
        var y = x?.ToString();
    }
}
```
<P>2. Apply Inline Temporary Variable on 'x'</P>
<P><STRONG>Expected Result:</STRONG></P>
```csharp
class Program
{
    static void Main(string[] args)
    {
        var y = args.Length.ToString()?.ToString();
    }
}
```
<P><STRONG>Actual Result:</STRONG></P>
```csharp
class Program
{
    static void Main(string[] args)
    {
        var y = (args.Length.ToString())?.ToString();
    }
}
```

### PR DESCRIPTION
**Pull request by srivatsn**
Fixes #987

Giving the ConditionalMemberAcces the same precedence as member access while determining associativity fixes the issue.

In VB, removing parentheses simplification works fine. There is a case where cast simplfication doesn't work and I've filed #1025 to track that.

### CODE REVIEW

**Comment by srivatsn** [comment]
@dotnet-bot test this please

**Comment by srivatsn** [comment]
@mavasani @DustinCampbell @shyamnamboodiripad can you please take a look?

**Comment by DustinCampbell** [comment]
:+1:

**Comment by mavasani** [comment]
:+1:

File: src/EditorFeatures/CSharpTest/CodeActions/InlineTemporary/InlineTemporaryTests.cs [hunk 1]
```diff
@@ -3502,7 +3500,53 @@ class A
...
+        public void TestConditionalAccessWithConditionalExpression()
+        {
+            Test(
+            @"
+class A
+{
+    void M(string[] args)
+    {
+        var [|x|] = args[0]?.Length ?? 10;
+        var y = x == 10 ? 10 : 4;
```
Comment (shyamnamboodiripad) [inline src/EditorFeatures/CSharpTest/CodeActions/InlineTemporary/InlineTemporaryTests.cs]: Add a corresponding test for VB too?

File: src/EditorFeatures/VisualBasicTest/CodeActions/InlineTemporary/InlineTemporaryTests.vb [hunk 2]
```diff
@@ -3831,5 +3831,53 @@ End Class
...
         End Sub
+
+        <Fact, Trait(Traits.Feature, Traits.Features.CodeActionsInlineTemporary)>
+        Public Sub TestSimpleConditionalAccess()
+            Dim code =
+<File>
+Class C
+    Sub M(args As String())
+        Dim [|x|] = args.Length.ToString()
+        Dim y = x?.ToString()
```
Comment (shyamnamboodiripad) [inline src/EditorFeatures/VisualBasicTest/CodeActions/InlineTemporary/InlineTemporaryTests.vb]: Is it possible to have other forms of expressions like the following and does the fix work in those cases?
x?!dictionarykey
x?.<xmlelement>
x?...<xmldescendant> or 
x?.@xmlattribute

**Comment by shyamnamboodiripad** [comment]
:+1:

**Comment by srivatsn** [comment]
Added some more tests per Shyam's suggestions.

**Comment by srivatsn** [comment]
@dotnet-bot test this please
