### PR TITLE
Regression test for 32503

### LINKED ISSUE #32503: inline declaration breaks nullable check
```c#
class A { }
class B : A { }

A Foo()
{
	var s = new A();
	if (s is B b) {}
	return s; // Possible null reference return.
}
```

the weird thing is that if you change the `if` line to `if (s is B) {}` then the warning goes away.

### PR DESCRIPTION
**Pull request by jaredpar**
This issue is fixed. Adding a regression test.

closes #32503

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 1]
```diff
@@ -74820,5 +74820,26 @@ void M1(C? c1)
                 //         c1 ??= M2(c1);
                 Diagnostic(ErrorCode.WRN_NullReferenceArgument, "c1").WithArguments("c1", "C C.M2(C c1)").WithLocation(6, 19));
         }
+
+        [WorkItem(32503, "https://github.com/dotnet/roslyn/issues/32503")]
+        [Fact]
+        public void PatternDeclarationBreaksNullabeAnalysis()
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >Nullabe [](start = 44, length = 7)

Typo

File: .gitignore [hunk 2]
```diff
@@ -24,6 +24,9 @@ x64/
 # Enable "build/" folder in the NuGet Packages folder since NuGet packages use it for MSBuild targets
 !packages/*/build/
 
+# Debug artifacts
+launchSettings.json
```
Comment (cston) [inline .gitignore]: Is this change intentional?

Comment (jaredpar) [reply .gitignore]: Yes. This stops Git from constantly including launchSettings.json whenever I setup Visual Studio for debugging.
