### PR TITLE
Issue 31304 Check variables in scope when getting name declaration suggestions

### LINKED ISSUE #31304: Varible name suggested same as foreach varible name
In 15.8.7
Using the following code makes Visual Studio suggest I use the name item for class Item, even though that name is already defined.

Note that var is NOT an Item class.

This is obviously incorrect as there will be two different varibles with the same item name.

```csharp
foreach (var item in returnedShipment.items)
{
  shipment.itemReferences.Add(item.item_reference);
  Item <name item is suggested here>
}
```

devenv_2018-10-18_11-01-46 2

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/361110/varible-name-suggested-same-as-foreach-varible-nam.html
VSTS ticketId: 708453_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

### PR DESCRIPTION
**Pull request by dibarbet**
Fixes #31304

This changes the behavior of the declaration name provider to check to see if the variable name is already defined in the current scope.  

Raising this to get some clarity on a couple issues.
1.  I'm not sure what the performance impact of calling `LookupSymbols` on the location is when providing the suggestions.  It should only be called once every time the suggestion list is generated.
2.  What symbols should be considered as conflicting?  Parameters and locals seem to be a definite, but I've also included ones like fields (which could be shadowed).

### CODE REVIEW

File: src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs [hunk 1]
```diff
@@ -248,6 +253,32 @@ private Glyph GetGlyph(SymbolKind kind, Accessibility? declaredAccessibility)
             return result.Select(kvp => (kvp.Key, kvp.Value)).ToImmutableArray();
         }
 
+        /// <summary>
+        /// Get symbol names that are visible and could hide or cause a conflict with potential names.
+        /// </summary>
+        /// <param name="context"></param>
+        /// <returns></returns>
+        private ImmutableHashSet<string> GetPossibleConflictingSymbolNames(CSharpSyntaxContext context)
```
Comment (mavasani) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs]: We have helpers for generating unique non-conflicting names based on location, see http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/LanguageServices/SemanticsFactsService/ISemanticFactsService.cs,110

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs [hunk 2]
```diff
@@ -1522,6 +1522,147 @@ void M()
             }
         }
 
+        [WorkItem(31304, "https://github.com/dotnet/roslyn/issues/31304")]
+        [Fact, Trait(Traits.Feature, Traits.Features.Completion)]
+        public async Task TestCompletionDoesNotUseForeachVariableName()
+        {
+            var markup = @"
+class ClassA
```
Comment (mavasani) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs]: What is the behavior in VB?

File: src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs (hunk 1 above)
Comment (dibarbet) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs]: Hmm - I already have names generated [from here](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/Completion/CompletionProviders/DeclarationNameCompletionProvider.NameGenerator.cs,1883522963f5d313).  These are then modified based on the styles [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs,238).

Should I replace any removed name with a generated name / change how the base name suggestions are found?

Comment (mavasani) [reply src/Features/CSharp/Portable/Completion/CompletionProviders/DeclarationNameCompletionProvider.cs]: Maybe you can extract a separate helper `ISemanticFactsService.IsUniqueName(name, ...)`? Another option is just check `GenerateUniqueName(baseName, ...) == baseName`.

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs (hunk 2 above)
Comment (dibarbet) [reply src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs]: I don't get any VB name suggestions at all in the editor and as far as I can tell there are no tests for name suggestions in VB either.  My guess is because the type declaration happens after the variable name is chosen e.g. ``Dim classB As ClassB``.  Similarly in C# there are not any name suggestions when using ``var``.  

The DeclarationNameCompletionProvider seems to be only be used by the CSharpCompletionService and is in a CSharp package.

**Comment by sharwell** [comment]
> This means we can suggest things like a name that is already in use, but allow a person to quickly commit it, then tweak as they want. 

This applies to the shadowing case (e.g. a local variable shadowing a field), but does not apply to the case of avoiding a duplicate name visible in the containing scope where shadowing is not allowed (e.g. a local variable attempting to shadow another local variable).

**Comment by sharwell** [comment]
Marked for design review to answer the question about conflicting symbols.

**Comment by Neme12** [comment]
I agree with @CyrusNajmabadi ... It might still be useful to complete a name that I would then tweak a little. That's what I often do with name completions.

**Comment by Neme12** [comment]
> This applies to the shadowing case (e.g. a local variable shadowing a field), but does not apply to the case of avoiding a duplicate name visible in the containing scope where shadowing is not allowed (e.g. a local variable attempting to shadow another local variable).

@sharwell  I don't understand. I think @CyrusNajmabadi's point is that we complete the name but change change it, for example by adding a suffix, thus avoiding any sort of shadowing. The completion is still useful for a part of the name.

**Comment by sharwell** [comment]
Design review outcome:

1. Avoid suggesting names that cause conflicts (compile errors) within the current method, presumably by adding a numerical suffix to the suggested name.
1. Do not avoid suggesting names that shadow names in the surrounding context, such as fields or properties.

File: src/Workspaces/Core/Portable/LanguageServices/SemanticsFactsService/ISemanticFactsService.cs [hunk 3]
```diff
@@ -111,6 +112,10 @@ internal interface ISemanticFactsService : ILanguageService
             SemanticModel semanticModel, SyntaxNode location,
             SyntaxNode containerOpt, string baseName, IEnumerable<string> usedNames, CancellationToken cancellationToken);
 
+        SyntaxToken GenerateUniqueName(
```
Comment (dibarbet) [inline src/Workspaces/Core/Portable/LanguageServices/SemanticsFactsService/ISemanticFactsService.cs]: GenerateUniqueLocalName actually also looks at fields and properties, so I had to add an interface method to allow me to pass in a custom filter.

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs (hunk 2 above)
Comment (mavasani) [reply src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs]: Thanks for checking!

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs [hunk 4]
```diff
@@ -1522,6 +1522,178 @@ void M()
...
+    class ClassB { }
+
+    void M()
+    {
+        ClassB classB = new ClassB();
+        ClassB classB1 = new ClassB();
+        ClassB $$
+    }
+}
+";
```
Comment (mavasani) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/DeclarationNameCompletionProviderTests.cs]: Consider adding another interesting scoping test:

```csharp
class ClassA
{
    class ClassB { }
    void M(bool flag)
    {
        ClassB $$
        if (flag)
        {
            ClassB classB = new ClassB();
        }
    }
}
```

**Comment by CyrusNajmabadi** [comment]
> Avoid suggesting names that cause conflicts (compile errors) within the current method, presumably by adding a numerical suffix to the suggested name.

This will actively regress typing for me as i take advantage of this behavior a *lot*.

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb [hunk 5]
```diff
@@ -4077,10 +4077,6 @@ class C
                 state.SendTypeChars("w")
                 Await state.AssertSelectedCompletionItem(displayText:="when", isHardSelected:=False)
 
-                state.SendBackspace()
-                state.SendTypeChars("i")
-                Await state.AssertSelectedCompletionItem(displayText:="identifier", isHardSelected:=False)
```
Comment (sharwell) [inline src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: ❓  Why did this change?

**Comment by sharwell** [comment]
> This will actively regress typing/completion for me as i take advantage of this behavior a lot.

How do you typically resolve the conflict?

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb (hunk 5 above)
Comment (dibarbet) [reply src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: Good catch - This change was from the previous revision which removed any suggestions from fields and properties as well.  Missed adding it back when we changed to locals as well.  Adding it back

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi How do you typically resolve the conflict in these situations?

I complete the name and then add appropriate  disambiguation text.

**Note**: a while back we had a bug (not sure where it is) that said something like this:

Suggestion mode should allow me to write code that then becomes a prefix of the name suggestions i'm being offered.  So, for example, if i write:

```
SyntaxToken //<-- hit space here
```

First, i should options of:

image

However, if i then write:

```
SyntaxToken open
```

The list should also have:

```
openSyntaxToken
openSyntax
openToken
```

That way a user can still get the speedup of the suggestion, along with a way to easily disambiguate.  Note: i want this feature *all the time*.  i.e. not just for cases of collisions.  I often want *most* of the suggestion.  But i still want to provide my own little prefix.

If we had such a thing, i'd feel like we had a much better solution for this sort of problem.

**Comment by sharwell** [comment]
> If we had such a thing, i'd feel like we had a much better solution for this sort of problem.

Agreed. It would also automatically address the conflict situation except for cases where users want to disambiguate with a suffix.

Considering inline rename behaves poorly in the face of name conflicts with locals, I think the current PR does offer an improvement for a _different_ common scenario. I don't think the concern is enough to block this PR outright, but it makes sense to move it to 16.1 Preview 1 so it gets more bake time.

**Comment by sharwell** [comment]
@CyrusNajmabadi the request is described in https://github.com/dotnet/roslyn/issues/22901#issuecomment-340671305

**Comment by CyrusNajmabadi** [comment]
@sharwell Yup!  That's the one :)

**Comment by sharwell** [comment]
@dibarbet I retargeted this to 16.1 Preview 1. Thanks! 😄
