### PR TITLE
Foreach ref assignment without identity conversion should give error

### LINKED ISSUE #61238: Compiler should warn on `foreach (ref T2 t2 in enumThatIsRefT1)`
`foreach (T value in enumerable)` is happy to insert an explicit cast to `T` from whatever type `enumerable` actually emits. IIRC this enabled things to work reasonably well back in the pre-generics age so you could `foreach (MyClass instance in arrayList)` because your `ArrayList`'s enumerator only gave out `object`s. Otherwise you'd have had to do `foreach (object instance in arrayList) { MyClass myClass = (MyClass)instance; ... }` _all over the place_. It was the least awful solution at the time, and also matched Java (iirc).

The thing is, looks like this still happens with `foreach (ref T2 value in enumerableOfRefT1s)` if `enumerableOfRefT1s` hands out an enumerator that does not implement `IEnumerable<T1>` but instead implements the duck-type pattern and has a `ref T1 Current` property.

I found this the hard way because a certain rendering path in Paint.NET was just not working; you'd draw with the Recolor Tool and it was not working; there was no effect on the canvas.

Turns out, it's because I had this code for the enumerator:

```cs
public unsafe readonly ref struct RegionRowPtr<T>
    where T : unmanaged
{
    private readonly T* ptr;
    private readonly int width;
    private readonly int y;
    ...
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public Enumerator GetEnumerator()
    {
        return new Enumerator(this.ptr, this.width);
    }
    ...
    public ref struct Enumerator
        //: IEnumerator<T>
    {
        private T* pCurrent;
        private int countLeft;
        ...
        public ref T Current
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => ref *this.pCurrent;
        }
        ...
    }
}
```    

And I was using it this way, elsewhere:

```cs
protected override unsafe void OnRenderContent(RegionPtr<ColorBgra> dstContent, Point2Int32 renderOffset)
{
    ColorBgra32 fillColor = this.Changes.FillColor;
    ColorBgra32 basisColor = this.basisColor;

    ThrowIfCancellationRequested();
    this.sampleSource.Render(dstContent, renderOffset);

    foreach (RegionRowPtr<ColorBgra> dstRow in dstContent.Rows)
    {
        ThrowIfCancellationRequested();

        // NOTE how dstRow's T is ColorBgra, but I'm foreach-ing with ColorBgra32
        foreach (ref ColorBgra32 dstColorRef in dstRow)
        {
            ColorBgra32 dstColor = dstColorRef;

            byte b = Int32Util.ClampToByte(dstColor.B + (fillColor.B - basisColor.B));
            byte g = Int32Util.ClampToByte(dstColor.G + (fillColor.G - basisColor.G));
            byte r = Int32Util.ClampToByte(dstColor.R + (fillColor.R - basisColor.R));
            byte a = Int32Util.ClampToByte(dstColor.A + (fillColor.A - basisColor.A));

            dstColorRef = ColorBgra32.FromBgra(b, g, r, a);
        }
    }
}
```

In my code, `PaintDotNet.ColorBgra` is the "old" color/pixel type, and `PaintDotNet.Imaging.ColorBgra32` is the new one, part of the newer more comprehensive imaging framework I've been working on. I'm still converting from the old to the new, little by little, over time. There's an implicit cast from `ColorBgra` to `ColorBgra32` (they are binary compatible). So instead of reading and writing to the refs that the enumerator was handing out, it was casting and then giving me `ref`s to the cast value (presumably on the stack). Reads were fine, writes went nowhere. Changing to `foreach (ref ColorBgra` fixed it.

I feel like this might be accidental? Surely the compiler should warn about this? I burned an hour on this, and thankfully it's the only location in my entire codebase where the text `foreach (ref ` exists, so it's not a widespread problem, but I could see it causing others a lot of pain and suffering.

### PR DESCRIPTION
**Pull request by ArcadeMode**
Fixes #61238

### CODE REVIEW

**Comment by ArcadeMode** [comment]
The implementation reuses the existing error code CS8173 - as i mentioned in #61238 I do feel like it *might* be more informative for the user if the message were to read something along the lines of `The enumerator must return type 'C' because it is being assigned by reference`. If preferred I could introduce a new errorcode for it.

File: src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs [hunk 1]
```diff
@@ -450,6 +450,12 @@ private BoundForEachStatement BindForEachPartsWorker(BindingDiagnosticBag diagno
 
             CompoundUseSiteInfo<AssemblySymbol> useSiteInfo = GetNewCompoundUseSiteInfo(diagnostics);
             Conversion elementConversionClassification = this.Conversions.ClassifyConversionFromType(inferredType.Type, iterationVariableType.Type, isChecked: CheckOverflowAtRuntime, ref useSiteInfo, forCast: true);
+            
+            if (elementConversionClassification.Kind != ConversionKind.Identity && IterationVariable.RefKind == RefKind.Ref && builder.CurrentPropertyGetter.RefKind == RefKind.Ref)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs:454]: This might not handle `foreach (ref readonly var x in ...)` properly. Where do we do the check to report bad conversions on `ref var x = ref ...`?

Comment (ArcadeMode) [reply src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs:454]: This is inspired by Binder_Statements.cs line 1965 if that is what you are asking?

Comment (ArcadeMode) [reply src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs:454]: I took a closer look it does indeed not show the error in this case, I will test for RefReadOnly too to resolve it

**Comment by jcouv** [comment]
@ArcadeMode The change looks good to me. Please ping when the suggested tests are added. I'll sign-off then. Thanks

**Comment by ArcadeMode** [comment]
@jcouv the mentioned test is already added, unless im overlooking something?

**Comment by jcouv** [comment]
@ArcadeMode Got it. Thanks

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 3)

**Comment by jcouv** [comment]
@RikkiGibson for second review

File: src/Compilers/CSharp/Test/Semantic/Semantics/ForEachTests.cs [hunk 2]
```diff
@@ -3689,5 +3689,39 @@ void Goo()
...
+                Diagnostic(ErrorCode.ERR_RefAssignmentMustHaveIdentityConversion, "items").WithArguments("C").WithLocation(4, 21)
+            );
+        }
+
+        [Fact]
+        public void ForEachIterator_RefReadonlyAssignmentWithoutIdentityConversion()
+        {
+            string source = @"
+using System;
+Span<C2> items = new Span<C2>(new C2[1]);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ForEachTests.cs:3715]: Sorry to belabor this. Please also add a test where we create a `ReadOnlySpan<C2> items` and `foreach` over it.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/ForEachTests.cs:3715]: If that test does not have the expected error, we might be able to resolve by simply deleting the check for `builder.CurrentPropertyGetter.RefKind == RefKind.Ref`.

I think we already require the ref kind of `Current { get; }` to be compatible with the ref kind of the iteration variable, so I think we only need to check the iteration variable to know if an identity conversion is required.

File: src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs [hunk 3]
```diff
@@ -451,6 +451,12 @@ private BoundForEachStatement BindForEachPartsWorker(BindingDiagnosticBag diagno
             CompoundUseSiteInfo<AssemblySymbol> useSiteInfo = GetNewCompoundUseSiteInfo(diagnostics);
             Conversion elementConversionClassification = this.Conversions.ClassifyConversionFromType(inferredType.Type, iterationVariableType.Type, isChecked: CheckOverflowAtRuntime, ref useSiteInfo, forCast: true);
 
+            if (elementConversionClassification.Kind != ConversionKind.Identity && (IterationVariable.RefKind == RefKind.Ref || IterationVariable.RefKind == RefKind.RefReadOnly) && builder.CurrentPropertyGetter.RefKind == RefKind.Ref)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs:454]: I think all we will need is

```suggestion
            if (elementConversionClassification.Kind != ConversionKind.Identity && IterationVariable.RefKind is RefKind.Ref or RefKind.RefReadOnly)
```

File: src/Compilers/CSharp/Test/Semantic/Semantics/ForEachTests.cs (hunk 2 above)
Comment (ArcadeMode) [reply src/Compilers/CSharp/Test/Semantic/Semantics/ForEachTests.cs:3717]: No need to apologize, I am having a lot of fun working on this stuff. It indeed did not have the expected error. I have removed the suggested statement which indeed fixed it. I added an extra test for that scenario as per your suggestion.

I could not find a test that demonstrated the compatibility check on ref kinds so I have added one extra test for that too. I felt like it adds a new case to the testsuite but if this is considered superfluous I can remove it.

File: src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs (hunk 3 above)
Comment (ArcadeMode) [reply src/Compilers/CSharp/Portable/Binder/ForEachLoopBinder.cs]: Verified through added test

File: src/Compilers/CSharp/Test/Semantic/Semantics/ForEachTests.cs (hunk 2 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/ForEachTests.cs:3717]: Sounds good. We don't worry too much about a test being redundant. Best tip I could give to discover the original would be to disable the code that reports the expected diagnostic and see which existing tests fail.

File: src/Compilers/CSharp/Test/Semantic/Semantics/ForEachTests.cs [hunk 4]
```diff
@@ -3689,5 +3689,76 @@ void Goo()
...
+            string source = @"
+using System;
+ReadOnlySpan<C2> items = new ReadOnlySpan<C2>(new C2[1]);
+foreach (ref readonly C t in items) {}
+class C {}
+class C2 : C {}
+";
+            CreateCompilationWithMscorlibAndSpan(source).VerifyDiagnostics(
+                // (4,21): error CS8173: The expression must be of type 'C' because it is being assigned by reference
+                // foreach (ref C t in items) {}
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/ForEachTests.cs:3742]: nit: diagnostic comment is out of date here. When a failing test result provides an expected value it's best to just copy/paste it in, including the preceding comments.

**Review by RikkiGibson — COMMENTED** [review]
Very nearly done, just had a nit to pick.

File: src/Compilers/CSharp/Test/Semantic/Semantics/ForEachTests.cs (hunk 4 above)
Comment (ArcadeMode) [reply src/Compilers/CSharp/Test/Semantic/Semantics/ForEachTests.cs]: Consider this nit picked 😉 Actually found another nit in the next test haha, fixed some indenting 😆

**Review by RikkiGibson — APPROVED** [review]

**Comment by RikkiGibson** [comment]
Spanish test is failing. I don't think it's related to this PR.
```
[xUnit.net 00:01:11.47]     Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests.TestNoBlockOnCompletionItems3(showCompletionInArgumentLists: False) [FAIL]
  Con error Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests.TestNoBlockOnCompletionItems3(showCompletionInArgumentLists: False) [1 s]
  Mensaje de error:
   System.ObjectDisposedException : No se puede obtener acceso al objeto desechado.
Nombre del objeto: 'CompletionList`1'.
  Seguimiento de la pila:
     en Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Data.CompletionList`1.CheckNotDisposed()
   en Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Data.CompletionList`1.get_IsEmpty()
   en Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Implementation.AsyncCompletionSession.GetSelectedItem(CompletionModel model)
   en Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Implementation.AsyncCompletionSession.ComputeCompletionItems(CompletionModel model)
   en Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Implementation.AsyncCompletionSession.Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.IAsyncCompletionSession.GetComputedItems(CancellationToken token)
   en Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.TestState.CalculateItemsIfSessionExists() en /_/src/EditorFeatures/TestUtilities2/Intellisense/TestState.vb:línea 499
   en System.Threading.Tasks.Task.Execute()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests.VB$StateMachine_209_TestNoBlockOnCompletionItems3.MoveNext() en /_/src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb:línea 5358
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() en C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:línea 264
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext() en C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:línea 48
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Xunit.Sdk.ExceptionAggregator.<RunAsync>d__9.MoveNext() en C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:línea 90
[xUnit.net 00:01:33.25]     Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests.TargetTypePreselectionConvertibility1 [SKIP]
Mensaje del recopilador de datos "Blame": Todas las pruebas han terminado de ejecutarse; no se generará el archivo Sequence..
  Omitidas Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests.TargetTypePreselectionConvertibility1 [1 ms]
Results File: C:\h\w\ACB50978\w\B1F009AB\e\WorkItem_83_x64_test_results.xml

Con error! - Con error:     1, Superado:   397, Omitido:     1, Total:   399, Duración: 1 m 9 s - Microsoft.CodeAnalysis.EditorFeatures2.UnitTests.dll (net472)
```

**Comment by RikkiGibson** [comment]
Thanks for the contribution @ArcadeMode!
