### PR TITLE
Fix inconsistencies in the way reachability is handled in pattern switch

### LINKED ISSUE #20210: Inconsistent error CS8120: The switch case has already been handled by a previous case.
**Version Used**: 
VisualStudio.15.Preview/15.3.0-Preview+26510.0

**Steps to Reproduce**:

Consider the following code:

```cs
class Program
{
  public static void Main()
  {
    switch (default(object)) // OK
    {
      case bool _:
      case true:
      case false:
        break;
    }

    switch (new object()) // errors
    {
      case bool _:
      case true:
      case false:
        break;
    }

    switch ((object)null) // OK
    {
      case bool _:
      case true:
      case false:
        break;
    }

    switch ((bool?)null) // OK
    {
      case bool _:
      case true:
      case false:
        break;
    }

    switch (default(bool?)) // errors
    {
      case bool _:
      case true:
      case false:
        break;
    }

    switch (default(bool)) // errors
    {
      case bool _:
      case true:
      case false:
        break;
    }
  }
}
```

**Expected Behavior**:
```
error CS8120: The switch case has already been handled by a previous case.
```
is reported either for each switch statement in the program or for neither of them.

**Actual Behavior**:
the error is reported only for some of switch statements in the program.
It is reported for switches over `new object()`, `default(bool?)` and `default(bool)` but not for switches over `default(object)`, `(object)null`, `(bool?)null`.

### PR DESCRIPTION
**Pull request by gafter**
**Customer scenario**

Fixes inconsistencies in the way reachability is handled in pattern switch. The concept of reachability, which takes the value of the switch expression into account and can produce warnings, is separate from the concept of subsumption which takes the full set of patterns into account and can produce errors.

The new rule is: If a single case could handle all inputs, e.g. has the same constant value, a wildcard pattern, etc, then the default label is considered unreachable. By contrast, subsumption ignores the *value* of the switch expression.

**Bugs this fixes:**

Fixes #20210

**Workarounds, if any**

None.

**Risk**

Fairly low. This only affects the computation of warning diagnostics.

**Performance impact**

Little additional code in the normal case, and no additional allocations.

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

This is an area of the specification that was poorly settled, and not well tested (mea culpa).

**How was the bug found?**

Customer reported.

**Test documentation updated?**

N/A

@agocke @AlekseyTs Please review this change to the handling of reachability for pattern switch.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/PatternSwitchBinder.cs [hunk 1]
```diff
@@ -138,15 +135,41 @@ internal override void BindPatternSwitchLabelForInference(CasePatternSwitchLabel
...
+                bool? patternMatches =
+                    labelSyntax.Kind() == SyntaxKind.DefaultSwitchLabel ? null :
+                    // wildcard pattern matches anything
+                    boundLabel.Pattern.Kind == BoundKind.WildcardPattern ? true :
+                    // `var x` matches anything
+                    // `Type x` matches anything of a subtype of `Type` except null
+                    boundLabel.Pattern is BoundDeclarationPattern d ? (d.IsVar ? true : inputMatchesType(d.DeclaredType.Type)) :
+                    // `case 2` matches the input `2`
+                    boundLabel.Pattern is BoundConstantPattern p ? SwitchGoverningExpression.ConstantValue?.Equals(p.ConstantValue) :
+                    null;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/PatternSwitchBinder.cs]: >null; [](start = 20, length = 5)

I think this code would be easier to read and maintain if it was written as a sequence of ```if-else if-else``` statements

File: src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs [hunk 2]
```diff
@@ -69,30 +68,15 @@ internal bool AddLabel(BoundPatternSwitchLabel label, DiagnosticBag diagnostics,
                 if (guardAlwaysSatisfied)
                 {
                     // Only unconditional switch labels contribute to subsumption
-                    if (AddToDecisionTree(_subsumptionTree, null, label) == null)
+                    if (AddToDecisionTree(_subsumptionTree, null, label) == null && !label.Pattern.HasErrors)
                     {
-                        return false;
+                        // Since the pattern was not subsumed, we should be able to add it to the decision tree
+                        throw ExceptionUtilities.Unreachable;
+                        //return false;
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Binder/SubsumptionDiagnosticBuilder.cs]: delete commented-out code.

File: src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass_Switch.cs [hunk 3]
```diff
@@ -171,10 +171,19 @@ private void VisitPatternSwitchBlock(BoundPatternSwitchStatement node)
                 }
             }
 
-            // we always consider the default label reachable for flow analysis purposes.
+            // we always consider the default label reachable for flow analysis purposes
+            // unless there was a single case that would match every input.
             if (node.DefaultLabel != null)
             {
-                SetState(initialState.Clone());
+                if (node.SomeLabelAlwaysMatches)
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass_Switch.cs]: Will this only produce warnings in cases that already have errors or warnings?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternSwitchTests.cs [hunk 4]
```diff
@@ -363,9 +363,12 @@ public static void Main()
...
             var compilation = CreateCompilationWithMscorlib45(source, options: TestOptions.DebugExe);
             compilation.VerifyDiagnostics(
-                // (8,18): error CS8121: An expression of type string cannot be handled by a pattern of type int.
+                // (8,18): error CS8121: An expression of type 'string' cannot be handled by a pattern of type 'int'.
                 //             case int i: // error: type mismatch.
-                Diagnostic(ErrorCode.ERR_PatternWrongType, "int").WithArguments("string", "int").WithLocation(8, 18)
+                Diagnostic(ErrorCode.ERR_PatternWrongType, "int").WithArguments("string", "int").WithLocation(8, 18),
+                // (9,17): warning CS0162: Unreachable code detected
+                //                 break;
+                Diagnostic(ErrorCode.WRN_UnreachableCode, "break").WithLocation(9, 17)
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternSwitchTests.cs]: Should we try to avoid cascade here?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternSwitchTests.cs [hunk 5]
```diff
@@ -3265,5 +3277,113 @@ void M()
...
+        public void SwitchOnNull_20210()
+        {
+            var source =
+@"class Sample
+{
+    void M()
+    {
+        switch (default(object))
+        {
+          case bool _:
```
Comment (jcouv) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternSwitchTests.cs]: Nit: the formatting in this code snippet is off (using 2 spaces in some places?)

**Comment by jcouv** [comment]
Along with the compat council discussion, please also add an entry to the doc for breaking changes.

**Comment by jcouv** [comment]
Approved for ask-mode.

File: src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass_Switch.cs (hunk 3 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass_Switch.cs]: See the thread on the compat council email. The short answer is that there are circumstances that newly get errors:
``` c#
    switch (default(object))
    {
      case bool _:
      case true: // error: subsumed
      case false: // error: subsumed
        break;
    }
```
and circumstances that newly get warnings:
``` c#
    switch (1)
    {
      case 1 when true:
        break;
      default:
        break; // warning: unreachable
    }
```

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternSwitchTests.cs (hunk 4 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/PatternSwitchTests.cs]: Yes, good idea...

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternSwitchTests.cs (hunk 5 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/PatternSwitchTests.cs]: That is a style supported by VS (I think), and used by the customer who submitted this test.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternSwitchTests.cs (hunk 4 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/PatternSwitchTests.cs]: Actually, that is hard to do. If we treat the code as reachable, then we would newly complain, e.g. about fallthrough to another case.

**Comment by gafter** [comment]
I've addressed all the (minor) comments on this review. Although its already been approved, you are welcome to take a second look in case you don't like how I've handled them.
