### PR TITLE
Fix SyntaxGenerator.WithModifiers to recognize ClassStatement, not only ClassBlock

### LINKED ISSUE #50003: Make class 'abstract' in VB.NET applies MustOverride incorrectly - should be MustInherit.
**Version Used**: 

Visual Studio 2019 v16.8.3

**Steps to Reproduce**:

1.

Create a class as follows:

   Class C
       Public MustOverride Sub M()
   End Class

Notice the error shown as:

Error	BC31411	'C' must be declared 'MustInherit' because it contains methods declared 'MustOverride'.

2.

Hover over the C on the Class line and choose "Show potential fixes" displaying the:

*Make class 'abstract'*

Choose this and to apply the "fix".

3. 

Instead of applying MustInherit, its applying MustOverride; even though the description of the "fix" clearly states the correctly desired result of MustInherit.

**Expected Behavior**:

Apply MustInherit (not MustOverride) on the Class.

**Actual Behavior**:

Applies MustOverride which is completely incorrect and produces a completely different set of error(s) that shouldn't have happened if the right thing would have taken place.

Additionally, would be nice if it could state "Make class 'MustInherit'"; though this may be beyond the scope of what code fixes are capable of doing.

Thanks.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes https://github.com/dotnet/roslyn/issues/53627
Fixes #50003

~~This has a breaking change for public API. If it is not desired, let me know~~ (Outdated now. Went another route per review)

### CODE REVIEW

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb [hunk 1]
```diff
@@ -2207,13 +2207,13 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.LanguageServices
...
+                Case SyntaxKind.ClassBlock, SyntaxKind.ClassStatement
                     Return DeclarationKind.Class
-                Case SyntaxKind.StructureBlock
+                Case SyntaxKind.StructureBlock, SyntaxKind.StructureStatement
                     Return DeclarationKind.Struct
-                Case SyntaxKind.InterfaceBlock
+                Case SyntaxKind.InterfaceBlock, SyntaxKind.InterfaceStatement
                     Return DeclarationKind.Interface
-                Case SyntaxKind.EnumBlock
+                Case SyntaxKind.EnumBlock, SyntaxKind.EnumStatement
```
Comment (Youssef1313) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb:2216]: Few lines below, there is:

```
                Case SyntaxKind.SubStatement
                    If Not IsChildOf(declaration, SyntaxKind.SubBlock) Then
                        Return DeclarationKind.Method
                    End If
```

This is very weird, why the "IsChildOf" check is negated? and how `SubStatement` won't be a child of a `SubBlock`?

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb [hunk 2]
```diff
@@ -2207,13 +2207,13 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.LanguageServices
                     Return DeclarationKind.Namespace
                 Case SyntaxKind.ImportsStatement
                     Return DeclarationKind.NamespaceImport
-                Case SyntaxKind.ClassBlock
+                Case SyntaxKind.ClassBlock, SyntaxKind.ClassStatement
```
Comment (Youssef1313) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb:2210]: Currently there is no special logic for things other than class, so only this change seems to have a noticeable and testable behavioral change. But I fixed all others.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb [hunk 3]
```diff
@@ -2207,13 +2207,13 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.LanguageServices
...
                     Return DeclarationKind.Class
```
Comment (Youssef1313) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb:2211]: @AlekseyTs Sorry for pinging on an IDE-side PR, but want to confirm the correctness from a language perspective. Can both "ClassBlockSyntax" and "ClassStatementSyntax" be considered a "declaration"?

**Comment by CyrusNajmabadi** [comment]
The original logic is intended here.

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/VisualBasic/Services/SyntaxFacts/VisualBasicSyntaxFacts.vb:2216]: This is intended. It's for cases like when you're on an interface and you only have the statement portion without a block

**Comment by Youssef1313** [comment]
Thanks @CyrusNajmabadi, will go to another route.

File: src/EditorFeatures/VisualBasicTest/MakeTypeAbstract/MakeTypeAbstractTests.vb [hunk 4]
```diff
@@ -22,7 +22,7 @@ Public Class [|Foo|]
     Public MustOverride Sub M()
 End Class",
 "
-Public MustOverride Class Foo
+Public MustInherit Class Foo
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/VisualBasicTest/MakeTypeAbstract/MakeTypeAbstractTests.vb:25]: given this example, i guess my surprise is that we are passing in hte class-statement, and not hte class-block for this feature.

Comment (Youssef1313) [reply src/EditorFeatures/VisualBasicTest/MakeTypeAbstract/MakeTypeAbstractTests.vb:25]: @CyrusNajmabadi, yep, it passes the class statement.

Comment (CyrusNajmabadi) [reply src/EditorFeatures/VisualBasicTest/MakeTypeAbstract/MakeTypeAbstractTests.vb:25]: i guess my fix would be at that level :) There is also an ISymbolDeclarationService that helps ensure that we work with the right node (if this is a feature that uses symbols).

Comment (Youssef1313) [reply src/EditorFeatures/VisualBasicTest/MakeTypeAbstract/MakeTypeAbstractTests.vb:25]: @CyrusNajmabadi The fix is mainly for the public `SyntaxGenerator.WithModifiers` API

Comment (CyrusNajmabadi) [reply src/EditorFeatures/VisualBasicTest/MakeTypeAbstract/MakeTypeAbstractTests.vb:25]: i guess my point is this: i think it's hte feature working improperly.  i would update the feature.  if we update the generator, we need to update it to support all statements for blocks, and it was intentional that we were not conflating these at that level.

Comment (Youssef1313) [reply src/EditorFeatures/VisualBasicTest/MakeTypeAbstract/MakeTypeAbstractTests.vb:25]: @CyrusNajmabadi For the purpose of `WithModifiers`, supporting other statements won't have effect. For `SyntaxGenerator` in general, I'm not sure what other parts are affected by but supporting blocks only and not statements?

Comment (CyrusNajmabadi) [reply src/EditorFeatures/VisualBasicTest/MakeTypeAbstract/MakeTypeAbstractTests.vb:25]: i'm not sure i get your question.  it feels very strange to just special case class statements here (what about structs/interfaces/modules)?

Comment (Youssef1313) [reply src/EditorFeatures/VisualBasicTest/MakeTypeAbstract/MakeTypeAbstractTests.vb:25]: @CyrusNajmabadi In this specific code path. They have no effect. The declaration kind is passed to `GetModifierList`:

https://github.com/dotnet/roslyn/blob/ad0674f544bfd0e5e6110f761ff8cae80a028544/src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb#L2490

File: src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb [hunk 5]
```diff
@@ -2366,8 +2366,15 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.CodeGeneration
             Dim isDefault As Boolean
             SyntaxFacts.GetAccessibilityAndModifiers(tokens, acc, currentMods, isDefault)
 
-            If (currentMods <> modifiers) Then
-                Dim newTokens = GetModifierList(acc, modifiers And GetAllowedModifiers(declaration.Kind), GetDeclarationKind(declaration), isDefault)
+            If currentMods <> modifiers Then
+                Dim declarationKind = GetDeclarationKind(declaration)
+                If declarationKind = DeclarationKind.None AndAlso declaration.IsKind(SyntaxKind.ClassStatement) Then
```
Comment (CyrusNajmabadi) [inline src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb:2371]: i don't get it.  this is directly making a change purely for classes.  i dont' see why we wouldn't need the same for structs/interfaces/modules here.  

And, like i said before, i thinik the bug is that hte caller is passing ina  class statement, it should pass in a classblock.

Comment (Youssef1313) [reply src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb:2371]: > i thinik the bug is that hte caller is passing ina class statement, it should pass in a classblock.

I believe API consumers won't expect this at all.

---

> i don't get it. this is directly making a change purely for classes. i dont' see why we wouldn't need the same for structs/interfaces/modules here.

Because it literally doesn't have any effect. If you look at the following method:

https://github.com/dotnet/roslyn/blob/ad0674f544bfd0e5e6110f761ff8cae80a028544/src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb#L2490

Any type declaration other than a class will be treated the same. I could handle all other statements, but it doesn't have any functional/behavioral change.

Comment (Youssef1313) [reply src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb:2371]: > i thinik the bug is that hte caller is passing ina class statement, it should pass in a classblock.

I believe API consumers won't expect this at all.

---

> i don't get it. this is directly making a change purely for classes. i dont' see why we wouldn't need the same for structs/interfaces/modules here.

Because it literally doesn't have any effect. If you look at the following method:

https://github.com/dotnet/roslyn/blob/ad0674f544bfd0e5e6110f761ff8cae80a028544/src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb#L2490

Any type declaration other than a class will be treated the same. I could handle all other statements, but it doesn't have any functional/behavioral change.

Comment (Youssef1313) [reply src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb:2371]: To put it another way, there is no way to write a unit test for interface/structure that can fail now and be fixed by handling statements in this code path. `WithModifiers` *already* works correctly for the other declarations.

Comment (CyrusNajmabadi) [reply src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb:2371]: i don't really get it.  

> I believe API consumers won't expect this at all.

I don't have an issue with htat.  It was an explicit decision that we do not try to blur the lines between the statements and blocks.  The block corresponds to the decl, and the api here intends to operate on the decls.

Comment (CyrusNajmabadi) [reply src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb:2371]: this is my approach: https://github.com/dotnet/roslyn/issues/50003

Comment (Youssef1313) [reply src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb:2371]: @CyrusNajmabadi Well, Part of the disconnect is whether `WithModifiers` should work with statements, or only blocks. It currently works with statements very well, except for the class case (more specifically sealing the class). Anything other than sealing a class works correctly using either a statement or a block. This is one of the reasons I think `WithModifiers` should get modified to work with class statement, even if the original design didn't intend that.

Otherwise, a clear doc comment should make this clear. (and in this case, you can close the PR and #53627)

Comment (CyrusNajmabadi) [reply src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb:2371]: i would then update GetModifierList to put the special logic there.

Comment (Youssef1313) [reply src/Workspaces/VisualBasic/Portable/CodeGeneration/VisualBasicSyntaxGenerator.vb]: @CyrusNajmabadi The suggested approach is a lot easier to follow and to reason about. Only problem I found is that most callers don't have a relevant SyntaxNode to pass. So I passed `Nothing` for these cases.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
thanks!
