### PR TITLE
Fix InvalidCastException in document highlights for constructor references

### LINKED ISSUE #83245: Feature "Document Highlights" unavailable due to an internal error
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Feature-Document-Highlights-unavailabl/11076921)._

---
[regression] [worked-in:18.2]
I typed:
```var z = new Comparison```

and got:

```
StreamJsonRpc.RemoteInvocationException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.NonErrorNamedTypeSymbol' to type 'Microsoft.CodeAnalysis.IMethodSymbol'.
   at StreamJsonRpc.JsonRpc.&lt;InvokeCoreAsync&gt;d__171`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.&lt;TryInvokeAsync&gt;d__20`1.MoveNext()
RPC server exception:
System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.NonErrorNamedTypeSymbol' to type 'Microsoft.CodeAnalysis.IMethodSymbol'.
      at Microsoft.CodeAnalysis.DocumentHighlighting.AbstractDocumentHighlightsService.&lt;&gt;c__DisplayClass6_0.&lt;FilterAndCreateSpansAsync&gt;b__0(ReferencedSymbol r)
      at Microsoft.CodeAnalysis.ImmutableArrayExtensions.WhereAsArrayImpl[T,TArg](ImmutableArray`1 array, Func`2 predicateWithoutArg, Func`3 predicateWithArg, TArg arg)
      at Microsoft.CodeAnalysis.DocumentHighlighting.AbstractDocumentHighlightsService.FilterAndCreateSpansAsync(ImmutableArray`1 references, Document startingDocument, IImmutableSet`1 documentsToSearch, ISymbol symbol, FindReferencesSearchOptions options, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.DocumentHighlighting.AbstractDocumentHighlightsService.GetTagsForReferencedSymbolAsync(ISymbol symbol, Document document, IImmutableSet`1 documentsToSearch, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.DocumentHighlighting.AbstractDocumentHighlightsService.GetDocumentHighlightsInCurrentProcessAsync(Document document, Int32 position, IImmutableSet`1 documentsToSearch, HighlightingOptions options, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.DocumentHighlighting.AbstractDocumentHighlightsService.GetDocumentHighlightsAsync(Document document, Int32 position, IImmutableSet`1 documentsToSearch, HighlightingOptions options, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteDocumentHighlightsService.&lt;&gt;c__DisplayClass2_0.&lt;&lt;GetDocumentHighlightsAsync&gt;b__0&gt;d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.&lt;&gt;c__DisplayClass7_0`1.&lt;&lt;RunWithSolutionAsync&gt;g__ProcessSolutionAsync|1&gt;d.MoveNext()
   --- End of stack trace from previous location ---
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.RunWithSolutionAsync[T](AssetProvider assetProvider, Checksum solutionChecksum, Boolean updatePrimaryBranch, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunWithSolutionAsync[T](Checksum solutionChecksum, Func`2 implementation, CancellationToken cancellationToken)
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunServiceImplAsync[T](Func`2 implementation, CancellationToken cancellationToken)
```

---
#### Feedback Bot on 4/20/2026, 06:38 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

### PR DESCRIPTION
**Pull request by deepakrathore33**
Fixes: https://github.com/dotnet/roslyn/issues/83245
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/roslyn/pull/83246)

### CODE REVIEW

File: src/Features/Core/Portable/DocumentHighlighting/AbstractDocumentHighlightsService.cs [hunk 1]
```diff
@@ -173,7 +173,12 @@ private async Task<ImmutableArray<DocumentHighlights>> FilterAndCreateSpansAsync
             var constructorParts1 = constructor.OriginalDefinition.GetAllMethodSymbolsOfPartialParts();
             references = references.WhereAsArray(r =>
             {
-                var constructorParts2 = ((IMethodSymbol)r.Definition).GetAllMethodSymbolsOfPartialParts();
+                // FindReferences on a constructor cascades to the containing type; keep those
+                // non-method definitions as-is since the partial-parts dedup is method-only.
+                if (r.Definition is not IMethodSymbol methodSymbol)
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/DocumentHighlighting/AbstractDocumentHighlightsService.cs:178]: > FindReferences on a constructor cascades to the containing type 

That seems... odd.  And the code is:

```
    protected override bool CanFind(IMethodSymbol symbol)
        => symbol.MethodKind is MethodKind.Constructor or MethodKind.StaticConstructor;

    protected override async ValueTask<ImmutableArray<ISymbol>> DetermineCascadedSymbolsAsync(IMethodSymbol symbol, Solution solution, FindReferencesSearchOptions options, CancellationToken cancellationToken)
    {
        if (symbol.MethodKind is MethodKind.Constructor)
            return GetOtherPartsOfPartial(symbol);

        return [];
    }

    private static ImmutableArray<ISymbol> GetOtherPartsOfPartial(IMethodSymbol symbol)
    {
        if (symbol.PartialDefinitionPart != null)
            return [symbol.PartialDefinitionPart];

        if (symbol.PartialImplementationPart != null)
            return [symbol.PartialImplementationPart];

        return [];
    }
```

i need more info on when thsi happen.s

Comment (deepakrathore33) [reply src/Features/Core/Portable/DocumentHighlighting/AbstractDocumentHighlightsService.cs:178]: Thanks for the review. Here is a small repro:
Paste:
`var z = new Comparison
`
Then click on Comparison

comp1

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/DocumentHighlighting/AbstractDocumentHighlightsService.cs:178]: i believe you're hitting it.  i'm just saying teh comment seems invalid (at least from looking at the code). can you debug in and see why you're getting named types here? it doesn't seem like it woudl be cascading from constructor related.

Comment (deepakrathore33) [reply src/Features/Core/Portable/DocumentHighlighting/AbstractDocumentHighlightsService.cs:178]: Yeah, comment is invalid update it.

**Review by CyrusNajmabadi — APPROVED** [review]

**Review by dibarbet — APPROVED** [review]
