### PR TITLE
Respect root editorconfig files when getting options for a file

### LINKED ISSUE #37282: Compiler EditorConfig support does not respect `root = true`
When determining AnalyzerOptions for a source file. We should not add options from an .editorconfig files above a rooted .editorconfig.

**Steps to Reproduce**:

1. Open Roslyn master in VS
2. Open AnalyzerConfigTests.cs
3. Add the following test
```csharp
        [Fact]
        public void NestedAnalyzerOptionsWithRoot()
        {
            var configs = ArrayBuilder<AnalyzerConfig>.GetInstance();
            configs.Add(Parse(@"
[*.cs]
dotnet_diagnostic.cs000.bad_key = bad_val", "/.editorconfig"));
            configs.Add(Parse(@"
root = true

[*.cs]
dotnet_diagnostic.cs000.some_key = some_val", "/src/.editorconfig"));

            var options = GetAnalyzerConfigOptions(
                new[] { "/src/test.cs", "/src/test.vb" },
                configs);
            configs.Free();

            VerifyAnalyzerOptions(
                new[] {
                    new[] { ("dotnet_diagnostic.cs000.some_key", "some_val") },
                    new (string, string) [] { }
                },
                options);
        }
```
4. Run the new test

**Expected Behavior**:
Test passes

**Actual Behavior**:
```
Message: 
    
    Expected:
    [dotnet_diagnostic.cs000.some_key, some_val]
    Actual:
    [dotnet_diagnostic.cs000.some_key, some_val]
    [dotnet_diagnostic.cs000.bad_key, bad_val]
    Differences:
        [dotnet_diagnostic.cs000.some_key, some_val]
    ++> [dotnet_diagnostic.cs000.bad_key, bad_val]
    
    Expected: True
    Actual:   False
```

### PR DESCRIPTION
**Pull request by JoeRobich**
Walk the AnalyzerConfigDocuments from most nested to least nested. Check each applicable editorconfig for whether it is the root or not before continuing.

Fixes #37282

### CODE REVIEW

**Comment by JoeRobich** [comment]
CC @agocke  @jasonmalinowski

File: src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs [hunk 1]
```diff
@@ -95,32 +95,51 @@ public AnalyzerConfigOptionsResult GetOptionsForSourcePath(string sourcePath)
...
-                    int dirLength = config.NormalizedDirectory.Length;
-                    // Leave '/' if the normalized directory ends with a '/'. This can happen if
-                    // we're in a root directory (e.g. '/' or 'Z:/'). The section matching
-                    // always expects that the relative path start with a '/'. 
-                    if (config.NormalizedDirectory[dirLength - 1] == '/')
+                    // When we process analyzer configs we will want to start with the outer most
+                    // editorconfig and walk down to the one closest to our source file.
+                    applicableAnalyzerConfigs.Insert(0, (analyzerConfigIndex, config));
+
+                    if (config.GlobalSection.Properties.ContainsKey("root") &&
```
Comment (jasonmalinowski) [inline src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs]: config.IsRoot?

File: src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs [hunk 2]
```diff
@@ -95,32 +95,51 @@ public AnalyzerConfigOptionsResult GetOptionsForSourcePath(string sourcePath)
...
                     {
-                        dirLength--;
+                        break;
                     }
-                    string relativePath = normalizedPath.Substring(dirLength);
+                }
+            }
+
+            // Reverse the list of applicable configs so that we walk from furthest to the
+            // the source file to closest allowing options to be overwritten as we go.
```
Comment (jasonmalinowski) [inline src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs]: Rather than overwriting, if we just update addOptions to not overwrite keys but preserve the "closest" value does that also work and then you can avoid having to reverse the order?

Comment (jasonmalinowski) [reply src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs]: (this work as it is, not sure it'll feel more natural or not)

**Comment by jasonmalinowski** [comment]
@agocke This is targeting master since this would block IDE throwing our feature flag to use the compiler support. Not sure what that means for your new bar now.

File: src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs (hunk 2 above)
Comment (JoeRobich) [reply src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs]: 👍 Good suggestion. Updated.

File: src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs [hunk 3]
```diff
@@ -141,6 +152,12 @@ public AnalyzerConfigOptionsResult GetOptionsForSourcePath(string sourcePath)
 
                 foreach (var (key, value) in section.Properties)
                 {
+                    // If this key were added by an earlier editorconfig then ignore it.
+                    if (analyzerBuilder.ContainsKey(key))
```
Comment (agocke) [inline src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs]: Won't this break if a later section in the current editorconfig overrides an earlier section? Also, what if the key was added to the SyntaxTree options and not the Analyzer options?

File: src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs [hunk 4]
```diff
@@ -95,8 +95,10 @@ public AnalyzerConfigOptionsResult GetOptionsForSourcePath(string sourcePath)
 
             var normalizedPath = PathUtilities.NormalizeWithForwardSlash(sourcePath);
 
-            // The editorconfig paths are sorted from shortest to longest, so matches
-            // are resolved from most nested to least nested, where last setting wins
+            // The editorconfig paths are sorted from longest to shortest, so matches
+            // are resolved from least nested to most nested. This allows us to walk
+            // up the chain of editorconfig files until we find a root editorconfig
+            // or have processed them all.
```
Comment (agocke) [inline src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs]: Instead of reversing the order, it feels like it might be a smaller change to clear the options when we hit a `root = true`.

File: src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs (hunk 3 above)
Comment (JoeRobich) [reply src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs]: I process the sections in reverse order so precedence should be preserved.

File: src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs (hunk 4 above)
Comment (JoeRobich) [reply src/Compilers/Core/Portable/CommandLine/AnalyzerConfigSet.cs]: I like it. At first I thought this way would save processing, but since the config files are already parsed it wouldn't save much and it would be a little harder to follow. I'll update.

File: src/Compilers/Core/CodeAnalysisTest/AnalyzerConfigTests.cs [hunk 5]
```diff
@@ -1151,6 +1151,59 @@ public void NestedAnalyzerOptionsWithRoot()
...
+                options);
+        }
+
+        [Fact]
+        public void NestedAnalyzerOptionsWithSectionOverrides()
+        {
+            var configs = ArrayBuilder<AnalyzerConfig>.GetInstance();
+            configs.Add(Parse(@"
+[*.cs]
+dotnet_diagnostic.cs000.some_key = a_val", "/.editorconfig"));
```
Comment (agocke) [inline src/Compilers/Core/CodeAnalysisTest/AnalyzerConfigTests.cs]: Could you also include an analyzer option override? I see we have some tests in this file for one or the other, but not both together.

**Comment by agocke** [comment]
@JoeRobich Are you going to have time to get to this today? I'd like to prep it for tactics approval.
