### PR TITLE
Use optimized hash creation methods on .NET 5+

### LINKED ISSUE #67995: Checksum's usage of a native hash algorithm resulting in thread starvation
**Version Used**: 
Investigating thread starvation in Speedometer's CopyRichNotAccurate, I see Checksum's usage of CAPI SHA256 hash algorithm is one of the cause of the starvations. It appears the following code path instantiates large number of finalizable objects (ie the underlying SafeHandle) on multiple threads at the same in a short burst. This hits a lock in the CLR's CFinalize::RegisterForFinalization causing contention and resulting in a lot of blocked time on the thread pool, 10% of the blocked time on these threads is this bug.

**Steps to Reproduce**:
1. Download trace from any run of Speedometer's CopyRichNotAccurate tests (ask me offline for how to do this)
2. Look at blocked time via Thread Time Stacks under CFinalize::RegisterForFinalization.
image

I had a look at SHA265Cng and it has a similar path so is likely not the path forward. Maybe the managed version of the algorithm? Or alternative, a customer wrapper around CNG that avoids creating a finalizable safe handle over and over again?

### PR DESCRIPTION
**Pull request by sharwell**
Implements the changes suggested in https://github.com/dotnet/roslyn/issues/67995#issuecomment-1525781878

Review commit-by-commit highly recommended.

Supersedes #67998
Fixes #67995

### CODE REVIEW

File: src/Workspaces/Core/Portable/Workspace/Solution/Checksum_Factory.cs [hunk 1]
```diff
@@ -23,47 +22,100 @@ internal partial class Checksum
...
 
         public static Checksum Create(IEnumerable<string> values)
         {
+#if NET5_0_OR_GREATER
+            using var pooledHash = s_incrementalHashPool.GetPooledObject();
+
+            foreach (var value in values)
+            {
+                pooledHash.Object.AppendData(MemoryMarshal.AsBytes(value.AsSpan()));
+                pooledHash.Object.AppendData(MemoryMarshal.AsBytes("\0".AsSpan()));
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Workspace/Solution/Checksum_Factory.cs:49]: unrelated to your change, but it's def weird we append these null bytes.

File: src/Workspaces/Core/Portable/Workspace/Solution/Checksum_Factory.cs [hunk 2]
```diff
@@ -23,47 +22,100 @@ internal partial class Checksum
...
+#else
             using var pooledHash = s_incrementalHashPool.GetPooledObject();
             using var pooledBuffer = SharedPools.ByteArray.GetPooledObject();
             var hash = pooledHash.Object;
+            hash.Initialize();
 
             AppendData(hash, pooledBuffer.Object, value);
 
-            return From(hash.GetHashAndReset());
+            return From(hash.TransformFinalBlock(Array.Empty<byte>(), 0, 0));
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Workspace/Solution/Checksum_Factory.cs:85]: what's the change about 'Initialize/TransformFinalBlock' about?

File: src/Workspaces/CoreTest/ChecksumTests.cs [hunk 3]
```diff
@@ -40,22 +32,18 @@ public void ValidateChecksumFromSpanSameAsChecksumFromBytes2()
...
             Assert.NotEqual(checksum3, checksum1);
 
             Assert.NotEqual(checksum1, checksumA);
-            Assert.NotEqual(checksum1, checksumB);
             Assert.NotEqual(checksum2, checksumA);
-            Assert.NotEqual(checksum2, checksumB);
             Assert.NotEqual(checksum3, checksumA);
-            Assert.NotEqual(checksum3, checksumB);
         }
-#endif
```
Comment (CyrusNajmabadi) [inline src/Workspaces/CoreTest/ChecksumTests.cs:59]: i'm not a fan of this change here.  validating that the byte-array/span versions aren't checked against each other.

Comment (sharwell) [reply src/Workspaces/CoreTest/ChecksumTests.cs:59]: Restoring this test to its original form would require additional conditional code that in practice defeats one of the key purposes of this test.

File: src/Workspaces/Core/Portable/Workspace/Solution/Checksum_Factory.cs (hunk 2 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Workspace/Solution/Checksum_Factory.cs:85]: ➡️ We change from `IncrementalHash` (which uses `SHA256CryptoServiceProvider` internally) to using `SHA256` directly (via `SHA256.Create()`). `Initialize` and `TransformFinalBlock` are what `IncrementalHash` uses internally.

File: src/Workspaces/Core/Portable/Workspace/Solution/Checksum_Factory.cs (hunk 1 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Workspace/Solution/Checksum_Factory.cs:49]: ➡️ Ensures the hash for `[ "Text1", "" ]` is different from the hash of `[ "Text", "1" ]`.

File: src/Workspaces/CoreTest/ChecksumTests.cs (hunk 3 above)
Comment (sharwell) [reply src/Workspaces/CoreTest/ChecksumTests.cs:59]: Specifically, we need to _avoid_ using the `IncrementalHash` type on .NET Framework (due to the finalizers), but we need to _keep_ using the `IncrementalHash` type for incremental hashing on .NET Core because it provides `AppendData(ReadOnlySpan<byte>)` which is not present on the `SHA256` type.

Comment (CyrusNajmabadi) [reply src/Workspaces/CoreTest/ChecksumTests.cs:59]: i see now.  thanks!

File: src/Workspaces/Core/Portable/Workspace/Solution/Checksum_Factory.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Workspace/Solution/Checksum_Factory.cs:49]: Fair. I originally felt that that wasn't necessary, but then remembered these checksums very much *are* expected to be unique keys to data, so this is actually very important.  Thanks!

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/Workspaces/Core/Portable/Workspace/Solution/Checksum_Factory.cs [hunk 4]
```diff
@@ -23,47 +22,102 @@ internal partial class Checksum
...
 
         public static Checksum Create(Stream stream)
         {
+#if NET7_0_OR_GREATER
+            Span<byte> hash = stackalloc byte[SHA256HashSizeBytes];
+            SHA256.HashData(stream, hash);
+            return From(hash);
+#elif NET5_0_OR_GREATER
+            using var pooledHash = s_incrementalHashPool.GetPooledObject();
+            Span<byte> buffer = stackalloc byte[SharedPools.ByteBufferSize];
```
Comment (stephentoub) [inline src/Workspaces/Core/Portable/Workspace/Solution/Checksum_Factory.cs:99]: 4K is a much larger buffer than we typically like to stackalloc.  It might be fine for your scenarios, just calling it out.  We have a rough guideline of not stackalloc'ing more than 1K.

Comment (stephentoub) [reply src/Workspaces/Core/Portable/Workspace/Solution/Checksum_Factory.cs:99]: (Also, keep in mind this whole buffer will be zero'd unless you're using SkipLocalsInit.)

**Comment by stephentoub** [comment]
> Implements the changes suggested in https://github.com/dotnet/roslyn/issues/67995#issuecomment-1525781878

Glad it was helpful.  Curious what the net impact looks like if there are any perf tests that surface it...
