### PR TITLE
ignore fixed-field check if inside nameof binder

### LINKED ISSUE #12696: nameof operator has some inconsistant behavior with fixed size buffers and static inner classes and can crash
**Version Used**: 
Visual studio 2015 Update 3
**Steps to Reproduce**:

Minimal code example to start with: 

``` C#
   public struct MyType
   {
      public static readonly string a = nameof(MyType.senderContext); // does not work strange behavior?
      public static readonly string b = nameof(senderContext); // works????
      public static class Inner
      {
         public static readonly string c = nameof(MyType.normalField);    //works as expected
         public static readonly string d = nameof(MyType.senderContext);  //has strange behavior/crashing
      }
      public int normalField;
      public unsafe fixed short senderContext[6];
   }
```

So that seems to be minimal (or close too ) for reproducing this issue. To cause the crash remove 'MyType' nameof operator in declaration d

**Expected Behavior**:
 I would expect all declarations a,b,c,d to be valid. And for declaration d to not crash when the definition is changed to remove the class name like declaration b.

**Actual Behavior**:
So hopefully the code sample is fairly self explanatory. but for more detail..... the fixed size buffer has some strange inconsistent behavior and some crashing. declaration strangely does not work as one would expect, but declaration b does. In the inner class c works fine as expected and d mirrors declaration a, but it becomes interesting if you try to remove declaration d's 'MyType
 from the nameof operator like declaration b. Then visual studio will crash the moment you remove the '.'

### PR DESCRIPTION
**Pull request by TyOverby**
closes #12696

### CODE REVIEW

**Comment by TyOverby** [comment]
@dotnet/roslyn-compiler Out for review.

I'm not really sure if this is the best way to handle things, so I'm up to suggestions.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs [hunk 1]
```diff
@@ -1258,5 +1258,41 @@ class Other {
...
+    {
+        Console.Write(MyType.a + "" "");
+        Console.Write(MyType.b + "" "");
+        Console.Write(MyType.c);
+    }
+}
+";
+            var compilation = CreateCompilationWithMscorlib45(source, null, new CSharpCompilationOptions(OutputKind.ConsoleApplication).WithAllowUnsafe(true));
+            CompileAndVerify(compilation, expectedOutput: "normalField fixedField fixedField").VerifyDiagnostics();
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs]: Does this test hit the issue in the bug? The bug repro involves a nested class.

Comment (TyOverby) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NameOfTests.cs]: The nested-class detail was a red-herring.  The bug is hit whenever `TupleName.fixedFieldName` is used.

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 2]
```diff
@@ -84,6 +84,8 @@ protected bool InCrefButNotParameterOrReturnType
             get { return InCref && !this.Flags.Includes(BinderFlags.CrefParameterOrReturnType); }
         }
 
+        protected virtual bool IsBindingNameOf => false;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: >protected virtual bool IsBindingNameOf => false; [](start = 8, length = 48)

Default implementation is usually placed in Binder.cs

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 3]
```diff
@@ -5664,7 +5666,7 @@ private static void CombineExtensionMethodArguments(BoundExpression receiver, An
                 hasError = this.CheckInstanceOrStatic(node, receiver, fieldSymbol, ref resultKind, diagnostics);
             }
 
-            if (!hasError && fieldSymbol.IsFixed)
+            if (!hasError && fieldSymbol.IsFixed && !IsBindingNameOf)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: >IsBindingNameOf [](start = 53, length = 15)

It doesn't look like we need an extra API, all other similar places simply check if EnclosingNameofArgument is not null.

Comment (TyOverby) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: Done

File: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs [hunk 4]
```diff
@@ -5664,7 +5664,8 @@ private static void CombineExtensionMethodArguments(BoundExpression receiver, An
                 hasError = this.CheckInstanceOrStatic(node, receiver, fieldSymbol, ref resultKind, diagnostics);
             }
 
-            if (!hasError && fieldSymbol.IsFixed)
+            var notInsideNameOf = EnclosingNameofArgument == null;
+            if (!hasError && fieldSymbol.IsFixed && notInsideNameOf)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs]: Consider inlining `notInsideNameOf` so the check is only made if the other two expressions are also true.

**Comment by cston** [comment]
LGTM

**Comment by AlekseyTs** [comment]
The bug report mentioned a crash, were you able to reproduce it? Does unit-test cover the crash?

**Comment by TyOverby** [comment]
@AlekseyTs The bug report had two related-but-different bugs.  I was going to break them up into multiple PRs to fix separately, but I just pushed a fix for the 2nd bug which was the crashing one.

**Comment by cston** [comment]
LGTM

File: src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs [hunk 5]
```diff
@@ -1693,6 +1693,13 @@ public override BoundNode VisitFieldAccess(BoundFieldAccess node)
 
         private void VisitFieldAccessInternal(BoundExpression receiverOpt, FieldSymbol fieldSymbol)
         {
+            // VisitLvalue and VisitRValue don't accept null arguments, and if receiverOpt is null
+            // then there's nothing left to visit anyway.
+            if (receiverOpt == null)
+            {
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs]: Comment goes inside the if block.

Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs]: You may also want to mention cases in which this is possible (like in a `nameof` expression)

Comment (TyOverby) [inline src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs]: Done

Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs]: @TyOverby I think you forgot to push :)

File: src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs [hunk 6]
```diff
@@ -1693,6 +1693,13 @@ public override BoundNode VisitFieldAccess(BoundFieldAccess node)
 
         private void VisitFieldAccessInternal(BoundExpression receiverOpt, FieldSymbol fieldSymbol)
         {
+            // VisitLvalue and VisitRValue don't accept null arguments, and if receiverOpt is null
+            // then there's nothing left to visit anyway.
+            if (receiverOpt == null)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs]: >if (receiverOpt == null) [](start = 12, length = 24)

I think we should simply strengthen VisitRValue and VisitLvalue implementation instead. Other use sites can benefit from this as well.

Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs]: @AlekseyTs Do you know of any other calls that pass null?

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs]: Also we need to think if we should visit ```nameof``` argument at all, it is not being evaluated. CC @gafter.

---
In reply to: [80124110](https://github.com/dotnet/roslyn/pull/13941#discussion_r80124110) [](ancestors = 80124110)

Comment (TyOverby) [inline src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs]: What does it mean to visit an RValue or LValue that doesn't exist?

CC @agocke

Comment (TyOverby) [inline src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs]: Looking at the sourcecode for VisitLValue, I'm not sure what a hardened implementation would look like.

File: src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs (hunk 5 above)
Comment (TyOverby) [inline src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs]: 😑

File: src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs [hunk 7]
```diff
@@ -1693,6 +1693,13 @@ public override BoundNode VisitFieldAccess(BoundFieldAccess node)
 
         private void VisitFieldAccessInternal(BoundExpression receiverOpt, FieldSymbol fieldSymbol)
         {
+            if (receiverOpt == null)
+            {
+                // VisitLvalue and VisitRValue don't accept null arguments, and if receiverOpt is null
+                // then there's nothing left to visit anyway.
```
Comment (jaredpar) [inline src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs]: In what cases would they be `null`?  Errors or normal code that would produce this?

Comment (TyOverby) [inline src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs]:
```
    TypeName.fieldName // receiverOpt is TypName
vs 
    fieldName // receiverOpt is null  
```

This has been working fine for us so far because non-fixed fields are treated as Rvalues, while fixed fields go through the lvalue path (while binding nameof)

File: src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs (hunk 6 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs]: > Do you know of any other calls that pass null?

We can certainly check other call sites. However, given that implementation of our visitors usually follow a pattern when it is Ok to visit "null". Look, for example, how ```Visit(BoundNode node)``` is implemented. Basically, visiting null is a no-op, not a crash. Given this, it is very easy to fall into a trap when, for some reason, a code is switched from calling regular Visit to calling VisitRValue/VisitLvalue.

>  I'm not sure what a hardened implementation would look like.

I would use VisitAlways(BoundNode node) as an example. If the input is null, give it back and get out.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs]: BTW, It looks like it is safe to call VisitRValue with null input.

Comment (TyOverby) [inline src/Compilers/CSharp/Portable/FlowAnalysis/PreciseAbstractFlowPass.cs]: @AlekseyTs: so you mean throw a `if (node == null) { return; }` in the body for VisitLValue?  

VisitRValue is safe to call with null, but it looks like it was almost by accident.

If I do change VisitLValue and VisitRValue to return immediately on null, should I change the argument name to nodeOpt?

**Comment by gafter** [comment]
:shipit:

**Comment by AlekseyTs** [comment]
LGTM

**Comment by jcouv** [comment]
Could there be an equivalent VB problem?

**Comment by TyOverby** [comment]
@jcouv I don't think so because VB doesn't allow fixed buffers

**Comment by AlekseyTs** [comment]
It might make sense to harden VisitLValue/VisitRvalue in VB nonetheless

**Comment by AlekseyTs** [comment]
LGTM, thank you for adjusting VB implementation as well.

**Comment by TyOverby** [comment]
@dotnet-bot 

test windows_release_unit32_prtest please
test windows_debug_unit64_prtest please

**Comment by TyOverby** [comment]
@dotnet-bot

test windows_release_unit32_prtest please
test windows_debug_unit64_prtest please

**Comment by TyOverby** [comment]
@dotnet-bot test windows_eta_open_prtest please

**Comment by TyOverby** [comment]
@dotnet-bot test windows_debug_unit64_prtest  please

**Comment by TyOverby** [comment]
@AlekseyTs Could you take a look at my changes with the failing unit test?

The test `ObjectInitializerNoStackOverflowFor150LevelsOfNesting` is now failing because previously there were no compilation errors, and now it fails with `An expression is too long or complex to compile\r\n Dim c As Cust = New Cust With...`

The only thing I could think of is that my change somehow introduced more levels of recursion, but my changes *shouldn't* have done that as they merely prevented crashes from dereferencing null.

**Comment by AlekseyTs** [comment]
Test windows_debug_unit64_prtest please.

Previous failure http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/4036/

**Comment by AlekseyTs** [comment]
Test windows_debug_unit64_prtest please.

**Comment by AlekseyTs** [comment]
@TyOverby It looks like you would need to repro the failure locally and debug. Alternatively, try separating VB only change into a separate PR to unblock the bug fix.
