### PR TITLE
Restrict extract class on workspaces that can't add files

### LINKED ISSUE #50868: Extract interface / class refactoring can be invoked in miscellaneous files workspace
**Version Used**: 3.9.0-3.21056.4+e5eb71d6714749bccf91d9268ece78cd5d4d43ea

**Steps to Reproduce**:

1. Create a new C# file by File > New > File, and create a C# class. Do _not_ create a project first, so this lands in Miscellaneous Files.
2. Go to the Class1 name, and Ctrl+.
3. Invoke extract class.
4. Try to extract into a new file.

**Actual Behavior**: Gold bar.

**Expected Behavior**: Not gold bar. A few options here:

1. Just block the refactoring entirely in misc files.
2. Correctly check Workspace.CanApplyChanges to see whether we can add documents before showing the dialog, and if not disable the "new file name" option.
3. Make Miscellaneous Files Workspace support creating new documents. (Note: this might be hard.)

### PR DESCRIPTION
**Pull request by ryzngard**
Fixes #50868

### CODE REVIEW

File: src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs [hunk 1]
```diff
@@ -53,6 +53,7 @@ public partial class TestWorkspace : Workspace
         private readonly IMetadataAsSourceFileService _metadataAsSourceFileService;
 
         private readonly Dictionary<string, ITextBuffer> _createdTextBuffers = new Dictionary<string, ITextBuffer>();
+        private readonly string? _workspaceKind;
 
         public TestWorkspace(ExportProvider? exportProvider = null, TestComposition? composition = null, string? workspaceKind = null, bool disablePartialSolutions = true, bool ignoreUnchangeableDocumentsWhenApplyingChanges = true)
```
Comment (ryzngard) [inline src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace.cs:58]:
```suggestion
        public TestWorkspace(ExportProvider? exportProvider = null, TestComposition? composition = null, string workspaceKind = WorkspaceKind.Host, bool disablePartialSolutions = true, bool ignoreUnchangeableDocumentsWhenApplyingChanges = true)
```

**Review by JoeRobich — APPROVED** [review]
LGTM

**Review by jasonmalinowski — APPROVED** [review]
