### PR TITLE
Fix detection of nested symbols in Document Outline

### LINKED ISSUE #66012: Enums don't nest in Document Outline depending on formatting
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Enums-dont-nest-in-Document-Outline-dep/10228858)._

---
If enums are written in this style the members will appear on the same level as the enum in the Document Outline window instead of being children of it:
```
enum Test
   {  a, b  }
```

image

If they are written in this style they work correctly:
```
enum Test {
   a,
   b
   }
```

image

---
#### Feedback Bot on 12/13/2022, 09:09 PM: 

(private comment, text removed)
#### Feedback Bot on 12/14/2022, 08:06 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### LINKED ISSUE #66473: Document Outline  VS2022 17.4 show "hard to watch" tree node  when member's class are inline
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Document-Outline--VS2022-174-show-hard/10193663)._

---
\[severity:Other\] \[regression\] \[worked-in:17.4\]  
I’m using VS 2022 17.4 and i see this problem is quite stranger (image attached bellow)  
Document Outline VS2022 17.4 show “hard to watch” tree node when member’s class are inline
B6b26d767a6224f7d9650b4072ae9f9b6638035624327453000_VS2022_17 4_DocumentOutline_ShowIncorrect

---
#### Feedback Bot on 11/9/2022, 01:37 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #66012
Fixes #66473

### CODE REVIEW

File: src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineViewModel_Utilities.cs [hunk 1]
```diff
@@ -156,7 +155,11 @@ DocumentSymbolData NestDescendantSymbols(ImmutableArray<RoslynDocumentSymbol> al
 
             // Returns whether the child symbol is in range of the parent symbol.
             static bool Contains(LspDocumentSymbol parent, LspDocumentSymbol child)
-                => child.Range.Start.Line > parent.Range.Start.Line && child.Range.End.Line < parent.Range.End.Line;
+            {
+                var parentRange = ProtocolConversions.RangeToLinePositionSpan(parent.Range);
+                var childRange = ProtocolConversions.RangeToLinePositionSpan(child.Range);
+                return childRange.Start > parentRange.Start && childRange.End <= parentRange.End;
```
Comment (sharwell) [inline src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineViewModel_Utilities.cs:161]: 📝 This is a move from comparing line number to comparing position number. Since the LSP `Position` type didn't support the comparison, we convert to a Roslyn `TextPosition` which provides the `>` and `<=` operators.

File: src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs [hunk 2]
```diff
@@ -194,9 +194,12 @@ public static LSP.VersionedTextDocumentIdentifier DocumentToVersionedTextDocumen
         public static LinePosition PositionToLinePosition(LSP.Position position)
             => new LinePosition(position.Line, position.Character);
 
+        public static LinePositionSpan RangeToLinePositionSpan(LSP.Range range)
+            => new(PositionToLinePosition(range.Start), PositionToLinePosition(range.End));
```
Comment (sharwell) [inline src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs:198]: 📝 This is a restoration of a helper method that was recently removed in #68081 due to lack of use

File: src/VisualStudio/CSharp/Test/DocumentOutline/DocumentOutlineTestsBase.cs [hunk 3]
```diff
@@ -107,7 +107,7 @@ protected async Task<DocumentOutlineTestMocks> CreateMocksAsync(string code)
             async Task<ManualInvocationResponse?> RequestAsync(ITextBuffer textBuffer, Func<JToken, bool> capabilitiesFilter, string languageServerName, string method, Func<ITextSnapshot, JToken> parameterFactory, CancellationToken cancellationToken)
             {
                 var request = parameterFactory(textBuffer.CurrentSnapshot).ToObject<RoslynDocumentSymbolParams>();
-                var response = await testLspServer.ExecuteRequestAsync<RoslynDocumentSymbolParams, DocumentSymbol[]>(method, request!, cancellationToken);
+                var response = await testLspServer.ExecuteRequestAsync<RoslynDocumentSymbolParams, object[]>(method, request!, cancellationToken);
```
Comment (sharwell) [inline src/VisualStudio/CSharp/Test/DocumentOutline/DocumentOutlineTestsBase.cs:110]: 📝 I lost two hours because this mock isn't the real call and didn't match the signature of the real call:
https://github.com/dotnet/roslyn/blob/1497e87d967c5b7797edb5f782131508607139e5/src/Features/LanguageServer/Protocol/Handler/Symbols/DocumentSymbolsHandler.cs#L41

File: src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineViewModel_Utilities.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/VisualStudio/Core/Def/DocumentOutline/DocumentOutlineViewModel_Utilities.cs:161]: oh jeez.  yeah.

**Review by CyrusNajmabadi — APPROVED** [review]
