### PR TITLE
Convert a return value to return type even if it has errors

### LINKED ISSUE #76499: Signature help session is not triggered after typing comma in target-typed new expression inside return statement
**Version Used**: VS 17.13 P2.1

**Steps to Reproduce**:

https://github.com/user-attachments/assets/4bc1add9-a4e4-446f-b2f3-38e08c79c4e4

```cs
static A Do()
{
    return new("ASD"$$);
}

public record class A(string Id, int Count);
```

**Expected Behavior**:
Signature help session starts.

**Actual Behavior**:
Signature help session doesn't start.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #76499

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs [hunk 1]
```diff
@@ -15163,6 +15166,34 @@ public IEnumerator GetEnumerator()
                 );
         }
 
+        [Fact]
+        public void CS1622ERR_ReturnInIterator_WrongType()
+        {
+            var text = @"
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs:15172]: nit: raw strings.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefLocalsAndReturnsTests.cs [hunk 2]
```diff
@@ -4284,7 +4284,10 @@ static ref int M(ref int i)
             CreateCompilationWithMscorlib46(text).VerifyDiagnostics(
                 // (6,9): error CS8150: By-value returns may only be used in methods that return by value
                 //         return;
-                Diagnostic(ErrorCode.ERR_MustHaveRefReturn, "return").WithLocation(6, 9)
+                Diagnostic(ErrorCode.ERR_MustHaveRefReturn, "return").WithLocation(6, 9),
+                // (6,9): error CS0126: An object of a type convertible to 'int' is required
+                //         return;
+                Diagnostic(ErrorCode.ERR_RetObjectRequired, "return").WithArguments("int").WithLocation(6, 9)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefLocalsAndReturnsTests.cs:4290]: It feels like most diagnostics that are added by this change are "fine", except, when the return statement's ref kind doesn't match the containing method signature, the extra diagnostic for conversion failure is not "ideal". But, I think that additional investment to avoid reporting this diagnostic isn't necessary.

It *is* necessary, IMO, to create the conversion anyway, so that IDE can get complete information. Even if the return statement has a wrong ref kind, we should still indicate the converted type through the public API.

File: src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs:15172]: If there's a need to make a functional change to the test I may go ahead and fix it up. But otherwise, as a copy/paste/modify job, I will leave as is.

File: src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs [hunk 3]
```diff
@@ -3041,11 +3041,6 @@ private BoundStatement BindReturn(ReturnStatementSyntax syntax, BindingDiagnosti
                 hasErrors |= arg.HasErrors || ((object)arg.Type != null && arg.Type.IsErrorType());
             }
 
-            if (hasErrors)
-            {
-                return new BoundReturnStatement(syntax, refKind, BindToTypeForErrorRecovery(arg), @checked: CheckOverflowAtRuntime, hasErrors: true);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Statements.cs:3046]: >return new BoundReturnStatement(syntax, refKind, BindToTypeForErrorRecovery(arg), @checked: CheckOverflowAtRuntime, hasErrors: true); [](http://example.com/codeflow?start=16&length=133)

Consider suppressing any additional diagnostics by setting ```diagnostics``` value to "suppressed" instead of getting rid of the `if` completely.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs [hunk 4]
```diff
@@ -1810,15 +1810,21 @@ async System.Collections.Generic.IAsyncEnumerable<int> M2()
...
             var comp = CreateCompilationWithAsyncIterator(source);
             comp.VerifyDiagnostics(
-                // (8,9): error CS1622: Cannot return a value from an iterator. Use the yield return statement to return a value, or yield break to end the iteration.
+                // source(8,9): error CS1622: Cannot return a value from an iterator. Use the yield return statement to return a value, or yield break to end the iteration.
                 //         return default;
                 Diagnostic(ErrorCode.ERR_ReturnInIterator, "return").WithLocation(8, 9),
-                // (10,60): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
+                // source(8,16): error CS8716: There is no target type for the default literal.
+                //         return default;
+                Diagnostic(ErrorCode.ERR_DefaultLiteralNoTargetType, "default").WithLocation(8, 16),
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncIteratorTests.cs:1818]: >Diagnostic(ErrorCode.ERR_DefaultLiteralNoTargetType, "default").WithLocation(8, 16), [](http://example.com/codeflow?start=16&length=84)

Any change in reported diagnostics feels unexpected.

**Comment by AlekseyTs** [comment]
Done with review pass (commit 3)

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 4)

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler for second review

**Review by 333fred — APPROVED** [review]
LGTM, but consider adding this test from my version:

```cs
        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/76799")]
        public void TestGetSemanticModelReturnsInPresenceOfPatternConflicts()
        {
            var code = """
                public class IssueClass
                {
                    public int ID;

                    public object ConvertFieldValueForStorage(object value)
                    {
                        return value is IssueClass issue ? (decimal)issue.ID : (object)-1m;
                    }
                }
                """;

            var comp = CreateCompilation(code);
            var tree = comp.SyntaxTrees.Single();
            var model = comp.GetSemanticModel(tree);

            var returnStatementCode = "return value is IssueClass issue ? (decimal)issue.ID : -1m;";
            var returnStatement = (ReturnStatementSyntax)SyntaxFactory.ParseStatement(returnStatementCode);

            var methodDeclLocation = tree.GetRoot().DescendantNodes().OfType<MethodDeclarationSyntax>().First().Body!.SpanStart;

            Assert.True(model.TryGetSpeculativeSemanticModel(methodDeclLocation, returnStatement, out var speculativeModel));

            var typeInfo = speculativeModel.GetTypeInfo(returnStatement.Expression!);
            Assert.Equal(SpecialType.System_Decimal, typeInfo.Type.SpecialType);
            Assert.Equal(SpecialType.System_Object, typeInfo.ConvertedType.SpecialType);
        }
```

**Comment by CyrusNajmabadi** [comment]
Thanks both of you.  I'll test this out to see if it fixes the issue i'm running into.

**Comment by CyrusNajmabadi** [comment]
Confirmed.  This fixes the issue :)

**Comment by CyrusNajmabadi** [comment]
@RikkiGibson ok to set this to merge?

**Comment by RikkiGibson** [comment]
Sure, do you need this not squashed?

**Comment by CyrusNajmabadi** [comment]
> Sure, do you need this not squashed?

Feel free to squash.
