### PR TITLE
Make dynamic nullable if its type was annotated to be nullable when generating its type syntax

### LINKED ISSUE #70623: Implement abstract class code fix does not consider nullability for dynamic
**Version Used**: VS 17.8 Preview 5

**Steps to Reproduce**:

1. Have the following code:

    ```c#
    abstract class C
    {
        public abstract dynamic? M(dynamic? arg);
    }

    class D : C
    {    
    }
    ```

2. Invoke "Implement abstract class" on `D`.

**Expected Behavior**:

The generated method matches the base class method in terms of nullability, i.e.:

```c#
class D : C
{
    public override dynamic? M(dynamic? arg)
    {
        throw new NotImplementedException();
    }
}
```

**Actual Behavior**:

The generated methods is missing nullability annotations:

```c#
class D : C
{
    public override dynamic M(dynamic arg)
    {
        throw new NotImplementedException();
    }
}
```

### PR DESCRIPTION
**Pull request by sdelarosbil**
Closes #70623

The issue turned out to be surprisingly deep, but there simply wasn't support for the TypeSyntaxGenerator to have a dynamic? generated when the annotation indicates nullability.

This pr makes it nullable using the same conditions than the NamedType one.

### CODE REVIEW

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ITypeSymbolExtensions.TypeSyntaxGeneratorVisitor.cs [hunk 1]
```diff
@@ -108,7 +108,13 @@ public override TypeSyntax VisitArrayType(IArrayTypeSymbol symbol)
             }
 
             public override TypeSyntax VisitDynamicType(IDynamicTypeSymbol symbol)
-                => AddInformationTo(SyntaxFactory.IdentifierName("dynamic"), symbol);
+            {
+                var typeSyntax = AddInformationTo(SyntaxFactory.IdentifierName("dynamic"), symbol);
+                if (symbol is { IsValueType: false, NullableAnnotation: NullableAnnotation.Annotated })
+                    return AddInformationTo(SyntaxFactory.NullableType(typeSyntax), symbol);
+
+                return typeSyntax;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ITypeSymbolExtensions.TypeSyntaxGeneratorVisitor.cs:116]:
```suggestion
                return symbol.NullableAnnotation is NullableAnnotation.Annotated
                    ? AddInformationTo(SyntaxFactory.NullableType(typeSyntax), symbol)
                    : typeSyntax;
```

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks!

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ITypeSymbolExtensions.TypeSyntaxGeneratorVisitor.cs (hunk 1 above)
Comment (sdelarosbil) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ITypeSymbolExtensions.TypeSyntaxGeneratorVisitor.cs]: @CyrusNajmabadi done

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ITypeSymbolExtensions.TypeSyntaxGeneratorVisitor.cs [hunk 2]
```diff
@@ -108,7 +108,12 @@ public override TypeSyntax VisitArrayType(IArrayTypeSymbol symbol)
             }
 
             public override TypeSyntax VisitDynamicType(IDynamicTypeSymbol symbol)
-                => AddInformationTo(SyntaxFactory.IdentifierName("dynamic"), symbol);
+            {
+                var typeSyntax = AddInformationTo(SyntaxFactory.IdentifierName("dynamic"), symbol);
+                return symbol.NullableAnnotation is NullableAnnotation.Annotated
+                    ? AddInformationTo(SyntaxFactory.NullableType(typeSyntax), symbol)
+                    : typeSyntax;
```
Comment (sharwell) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ITypeSymbolExtensions.TypeSyntaxGeneratorVisitor.cs:115]: ❓ Why does this use the current form instead of:

```suggestion
                var typeSyntax = SyntaxFactory.IdentifierName("dynamic");
                return symbol.NullableAnnotation is NullableAnnotation.Annotated
                    ? AddInformationTo(SyntaxFactory.NullableType(typeSyntax), symbol)
                    : AddInformationTo(typeSyntax, symbol);
```

Comment (sharwell) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ITypeSymbolExtensions.TypeSyntaxGeneratorVisitor.cs:115]: Or equivalently, this:

```suggestion
                var typeSyntax = AddInformationTo(SyntaxFactory.IdentifierName("dynamic"), symbol);
                if (symbol.NullableAnnotation is NullableAnnotation.Annotated)
                    typeSyntax = SyntaxFactory.NullableType(typeSyntax);

                return AddInformationTo(typeSyntax, symbol);
```

Comment (sdelarosbil) [reply src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ITypeSymbolExtensions.TypeSyntaxGeneratorVisitor.cs]: done, did the first one

**Review by sharwell — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks very much!
