### PR TITLE
Note unused field definitions in abstract classes

### LINKED ISSUE #13652: Warnings on unused fields not triggered when class is abstract
**Version Used**: VS 2015 Update 3

**Steps to Reproduce**:

When having an `abstract` class containing `private` fields that are never assigned to or never read, the native compiler (VS 2012) used to issue related warnings CS0414 / CS0649. The roslyn compiler in VS 2015 however does only trigger these warnings when the class is not being marked as `abstract`.

For details please see my related [StackOverflow question](http://stackoverflow.com/questions/39324517/visual-studio-2015-warnings-not-triggered).

For a better overview, I add the minimal example on how to reproduce this issue here as well:

```csharp
    // When the class is being marked as abstract, VS-2015 will not issue any warning.
    // When the class is not abstract the warnings are issued.
    public abstract class Demonstrator
    {
        // This should trigger warning CS0169 Warning Level 2
        private int _UnusedField;

        // This should trigger warning CS0414 Warning Level 4
        private int _AssignedButNotReadField;

        public Demonstrator()
        {
            _AssignedButNotReadField = 1;
        }
    }
```

The compiler should still trigger those warnings even though the class is abstract, as, due to the fact that those fields are private, their usage is still restricted to that single class.

### PR DESCRIPTION
**Pull request by OmarTawfik**
Fixes #13652 
@dotnet/roslyn-compiler

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs [hunk 1]
```diff
@@ -552,27 +552,27 @@ private void NoteFieldDefinitions()
...
-                                assembly.NoteFieldDefinition(field, isInternal: false, isUnread: true);
-                            }
-                            else if (containerEffectiveAccessibility == Accessibility.Private)
+                        Accessibility fieldDeclaredAccessibility = field.DeclaredAccessibility;
+                        if (fieldDeclaredAccessibility == Accessibility.Private)
+                        {
+                            // mark private fields as tentatively unassigned and unread unless we discover otherwise.
+                            assembly.NoteFieldDefinition(field, isInternal: false, isUnread: true);
+                        }
+                        else if (!this.IsAbstract)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs]: Shouldn't we report warnings for internal fields of abstract classes?

File: src/Compilers/CSharp/Test/Semantic/Semantics/AccessCheckTests.cs [hunk 2]
```diff
@@ -1153,5 +1153,46 @@ public class TestClass1 { }
...
+            var text = @"
+    public abstract class Class1
+    {
+        private int _UnusedField;
+
+        public Class1()
+        {
+        }
+    }
+";
```
Comment (OmarTawfik) [inline src/Compilers/CSharp/Test/Semantic/Semantics/AccessCheckTests.cs]: Fixed

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs (hunk 1 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs]: Turned out there is a different comptability issue here as well. We don't report WRN_UnassignedInternalField (649) on unassigned internal fields, and the native csc does. I'll add a fix/test that as well.

**Comment by OmarTawfik** [comment]
@cston @AlekseyTs added a third type of warnings into account (649).
@gafter modified the breaking changes markdown files to indicate the change.

**Comment by AlekseyTs** [comment]
Based on the build failures, it looks like this change exposed a bug in another area.

File: src/Compilers/CSharp/Test/Semantic/Semantics/AccessCheckTests.cs [hunk 3]
```diff
@@ -1153,5 +1153,57 @@ public class TestClass1 { }
...
+    }
+}";
+            CompileAndVerify(text).VerifyDiagnostics(
+                // (4,21): warning CS0414: The field 'Class1._AssignedButNotReadField' is assigned but its value is never used
+                //         private int _AssignedButNotReadField;
+                Diagnostic(ErrorCode.WRN_UnreferencedFieldAssg, "_AssignedButNotReadField").WithArguments("Class1._AssignedButNotReadField").WithLocation(4, 17));
+        }
+
+        [Fact, WorkItem(13652, "https://github.com/dotnet/roslyn/issues/13652")]
+        public void UsedButNotAssignedFieldInAbstractClassShouldTriggerWarning()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/AccessCheckTests.cs]: >UsedButNotAssignedFieldInAbstractClassShouldTriggerWarning [](start = 20, length = 58)

It feels like it would be good to have a test for a scenario when the class is public, or there is an InternalsVisisbleTo attribute.

File: src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs [hunk 4]
```diff
@@ -19951,11 +19951,6 @@ public void Func(object o, string p)
         table[p] = o;
     }
 }
-
-abstract class Foo
-{
-    public int x; // no diagnostic when in abstract class (for no apparent reason except that's the way Dev10 does it)
```
Comment (agocke) [inline src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs]: So Dev11 broke compat with Dev10, where it was restored in Dev11, broken again in Dev14, and will be reverted in Dev15?

**Comment by agocke** [comment]
Fix LGTM, but it looks like we have actual code in Roslyn that produces this warning.

How sure are we that we want to change this behavior?

File: src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs (hunk 4 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs]: ^ 😆

**Comment by OmarTawfik** [comment]
@AlekseyTs I'll fix the code base errors in another commit now.
@agocke the warnings were produced in case of non-abstract classes. This PR includes abstract classes as well.

File: src/Compilers/CSharp/Test/Semantic/Semantics/AccessCheckTests.cs (hunk 3 above)
Comment (OmarTawfik) [inline src/Compilers/CSharp/Test/Semantic/Semantics/AccessCheckTests.cs]: I'll add tests to cover the rest of the cases.

**Comment by VSadov** [comment]
We indeed have an unused field in an abstract class in Roslyn.

        private readonly RefKind _refKind;    in  SourceDelegateMethodSymbol is redundant and unused

        internal override RefKind RefKind => _refKind;    seems to be redundant too, since every class derived from SourceDelegateMethodSymbol overrides it.

I think these two members should be removed.

**Comment by OmarTawfik** [comment]
@VSadov Jenkins revealed many cases like this. I'm going over them now.

**Comment by OmarTawfik** [comment]
@VSadov Removed a bunch of other unused variables through the codebase.
@CyrusNajmabadi can you take a quick look at the other non-compiler fixes? these were probably clean ups from other dead code.

**Comment by CyrusNajmabadi** [comment]
👍 on all IDE changes.  Regardless of what happens with th compiler diagnostic, we'd still lke that cleanup.

**Comment by cston** [comment]
LGTM

**Comment by AlekseyTs** [comment]
LGTM
