### PR TITLE
Use proper "unsafe" context while binding type in explicit interface specifier

### LINKED ISSUE #80565: Unsafe context required on an explicit interface implementation with pointers in the interface type parameters despite being marked unsafe
**Version Used**: .NET 9 SDK

**Steps to Reproduce**:

```cs
interface ITest<T>
{
    void Method();
}

unsafe interface IPointerTest : ITest<void*[]>
{

}

class PointerImpl : IPointerTest
{
    // error CS0214: Pointers and fixed size buffers may only be used in an unsafe context
    unsafe void ITest<void*[]>.Method()
    {

    }
}
```

**Diagnostic Id**:

CS0214: Pointers and fixed size buffers may only be used in an unsafe context

**Expected Behavior**:

The use of `void*` should be okay because the member is marked `unsafe`.

**Actual Behavior**:

An error is reported and the `unsafe` modifier on the member appears to be ignored within the interface type reference. The code works only when the modifier is put on the whole class.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #80565.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/UnsafeTests.cs [hunk 1]
```diff
@@ -13942,5 +13942,168 @@ void M2()
...
+}
+
+unsafe interface IPointerTest : ITest<void*[]>
+{
+
+}
+
+class PointerImpl : IPointerTest
+{
+    unsafe void ITest<void*[]>.Method()
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Semantic/Semantics/UnsafeTests.cs:13962]: Are there any tests without `unsafe` here verifying we report an error?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/UnsafeTests.cs:13962]: > Are there any tests without `unsafe` here verifying we report an error?

Probably. It was easier for me to add new ones.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review

File: src/Compilers/CSharp/Test/Semantic/Semantics/UnsafeTests.cs [hunk 2]
```diff
@@ -13942,5 +13942,361 @@ void M2()
             comp = CreateCompilation(csharp, options: TestOptions.UnsafeDebugDll, parseOptions: TestOptions.RegularPreview);
             comp.VerifyDiagnostics();
         }
+
+        [Fact]
```
Comment (jjonescz) [inline src/Compilers/CSharp/Test/Semantic/Semantics/UnsafeTests.cs:13946]: Consider adding WorkItem attribute
