### PR TITLE
Empty C# statement has no side-effects

### LINKED ISSUE #4729: Empty statement ";" suppresses try-catch-finally optimization in some circumstances
In https://github.com/dotnet/roslyn/pull/4569/files#r37368440 @AlekseyTs noted that we incorrectly treat a "no-op" statement as having side-effects. In the context where the problem occurs, that has the effect of sometimes suppressing the optimization that allows us to elide empty finally blocks, or elide catch blocks when the try block is empty. See `case BoundKind.NoOpStatement` below, which should `return false`.

``` cs
        /// <summary>
        /// Is there any code to execute in the given statement that could have side-effects,
        /// such as throwing an exception? This implementation is conserviative, in the sense
        /// that it may return true when the statement actually may have no side effects.
        /// </summary>
        private static bool HasSideEffects(BoundStatement statement)
        {
            if (statement == null) return false;
            switch (statement.Kind)
            {
                case BoundKind.NoOpStatement:
                    return true;
                case BoundKind.Block:
                    {
                        var block = (BoundBlock)statement;
                        foreach (var stmt in block.Statements)
                        {
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #4729

@dotnet/roslyn-compiler May I please have a couple of reviews of this one-line bug fix?

### CODE REVIEW

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTryFinally.cs [hunk 1]
```diff
@@ -61,6 +59,109 @@ .maxstack  0
 }");
         }
 
+        [Fact]
```
Comment (sharwell) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTryFinally.cs]: :bulb: If you use a `[Theory]` here, you could actually write the test so the contents of each block is parameterized as a clean way to validate the code generated for `""` and `";"` is the same.

```csharp
[Theory]
[InlineData("")]
[InlineData(";")]
public void NopInTryCatchFinally(string nopText)
```

Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTryFinally.cs]: Hmmm, that's a great idea.
