### PR TITLE
Rename Engine: Handle type parameters of partial types (fixes crash)

### LINKED ISSUE #7440: Crash in rename with generic partial class "mix-in"
```C#
partial class C<T>
    where T : C<T>.D
{

}

partial class C<T>
{
    public class D { }
}
```

Move caret to T` and invoke Rename.

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #7440. We previously assumed that TypeParameters would only have one locations, which is not true in partial types. This fixes a crash that occurs whenever a conflict is introduced involving the TypeParameters.

### CODE REVIEW

**Comment by dpoeschl** [comment]
Tagging @dotnet/roslyn-ide

File: src/EditorFeatures/Test2/Rename/RenameEngineTests.VisualBasicConflicts.vb [hunk 1]
```diff
@@ -3059,6 +3059,50 @@ End Class
                     result.AssertLabeledSpansAre("conflict", renameTo, RelatedLocationType.UnresolvedConflict)
                 End Using
             End Sub
+
+            <Fact>
+            <Trait(Traits.Feature, Traits.Features.Rename)>
+            <WorkItem(7440, "https://github.com/dotnet/roslyn/issues/7440")>
+            Public Sub RenameTypeParameterInPartialClass()
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Test2/Rename/RenameEngineTests.VisualBasicConflicts.vb]: What about type parameters in partial methods? Do we already have coverage of that scenario?

**Comment by jasonmalinowski** [comment]
:+1:

File: src/EditorFeatures/Test2/Rename/RenameEngineTests.CSharpConflicts.vb [hunk 2]
```diff
@@ -3526,5 +3526,39 @@ class Program
...
+        Public Sub RenameMethodToConflictWithTypeParameter()
+            Using result = RenameEngineResult.Create(
+                    <Workspace>
+                        <Project Language="C#" CommonReferences="true">
+                            <Document>
+partial class C&lt;{|Conflict:T|}&gt; { void [|$$M|]() { } }
+partial class C&lt;{|Conflict:T|}&gt; {}
+                            </Document>
+                        </Project>
+                    </Workspace>, renameTo:="T2")
```
Comment (brettfo) [inline src/EditorFeatures/Test2/Rename/RenameEngineTests.CSharpConflicts.vb]: What's the actual conflict here?  Why can't `T` be renamed to `T2`?

File: src/EditorFeatures/Test2/Rename/RenameEngineTests.VisualBasicConflicts.vb [hunk 3]
```diff
@@ -3059,6 +3059,50 @@ End Class
...
+    Sub [|$$M|]()
+    End Sub
+End Class
+
+Partial Class C(Of {|Conflict:T|})
+End Class
+]]>
+                                </Document>
+                            </Project>
+                        </Workspace>, renameTo:="T")
```
Comment (brettfo) [inline src/EditorFeatures/Test2/Rename/RenameEngineTests.VisualBasicConflicts.vb]: Maybe related to my other question, but what's the use-case for renaming a symbol to itself?  `T` -> `T`

**Comment by brettfo** [comment]
:shipit: pending the test fix from `T2` to `T`.

**Comment by dpoeschl** [comment]
@brettfo - Yep, I had fixed that locally on my machine but apparently hadn't sent that fix to githubland. Thanks!

File: src/EditorFeatures/Test2/Rename/RenameEngineTests.VisualBasicConflicts.vb (hunk 1 above)
Comment (dpoeschl) [inline src/EditorFeatures/Test2/Rename/RenameEngineTests.VisualBasicConflicts.vb]: This kind of conflict doesn't exist for method type parameters, but those are covered in other ways in the test suite.

**Comment by dpoeschl** [comment]
@Pilchie @davkean Is this good to go for askmode?

**Comment by davkean** [comment]
@MattGertz Can we have an approval for Ask Mode?

**Comment by MattGertz** [comment]
Approved.
