### PR TITLE
Fix culture conditional fact attribute

### LINKED ISSUE #9892: ConditionalFact(typeof(IsEnglishLocal)) skips tests when current culture is “en-US”
It looks like there is a bug in our infrastructure
```
System.Globalization.CultureInfo.CurrentCulture != new System.Globalization.CultureInfo("en-US") 
```
is true, even though ```System.Globalization.CultureInfo.CurrentCulture.ToString()```
is “en-US”

It is possible we never run these tests.

### PR DESCRIPTION
**Pull request by TyOverby**
Apparently `!=` isn't implemented for `System.Globalization.CultureInfo`, so this change compares against the culture-code in string form.

Closes #9892

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@davkean for review.

File: src/Test/Utilities/Shared/Assert/ConditionalFactAttribute.cs [hunk 1]
```diff
@@ -44,8 +44,7 @@ public class HasShiftJisDefaultEncoding : ExecutionCondition
 
     public class IsEnglishLocal : ExecutionCondition
     {
-        public override bool ShouldSkip =>
-                System.Globalization.CultureInfo.CurrentCulture != new System.Globalization.CultureInfo("en-US");
+        public override bool ShouldSkip => System.Globalization.CultureInfo.CurrentCulture.ToString() != "en-US";
```
Comment (AlekseyTs) [inline src/Test/Utilities/Shared/Assert/ConditionalFactAttribute.cs]: ```!System.Globalization.CultureInfo.CurrentCulture.Name.StartsWith("en", StringComparison.OrdinalIgnoreCase)```

To be consistent with code in src\Test\Utilities\Shared\FX\EnsureEnglishUICulture.cs

Comment (davkean) [inline src/Test/Utilities/Shared/Assert/ConditionalFactAttribute.cs]: What's the check looking for? It is this for resources or formatting? Because right now your checking the culture for formatting, but not for resources.

Comment (AlekseyTs) [inline src/Test/Utilities/Shared/Assert/ConditionalFactAttribute.cs]: We should probably check InstalledUICulture, basically we want to skip some tests on non-English OS.

**Comment by TyOverby** [comment]
As per my discussion with @davkean, I've changed this to compare against `CurrentUICulture`

**Comment by jaredpar** [comment]
:+1: 

Confirmed tests with this attribute ran in Jenkins:

http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/5409/testReport/Microsoft.CodeAnalysis.UnitTests/StringTextDecodingTests/Decode_NonUtf8/

**Comment by TyOverby** [comment]
@dotnet-bot test prtest/lin/dbg/unit32 please

**Comment by TyOverby** [comment]
@dotnet-bot test prtest/lin/dbg/unit32  please

**Comment by TyOverby** [comment]
@AlekseyTs Could I get another review?

File: src/Test/Utilities/Shared/Assert/ConditionalFactAttribute.cs [hunk 2]
```diff
@@ -44,8 +44,7 @@ public class HasShiftJisDefaultEncoding : ExecutionCondition
 
     public class IsEnglishLocal : ExecutionCondition
     {
-        public override bool ShouldSkip =>
-                System.Globalization.CultureInfo.CurrentCulture != new System.Globalization.CultureInfo("en-US");
+        public override bool ShouldSkip => System.Globalization.CultureInfo.CurrentUICulture.ToString() != "en-US";
```
Comment (AlekseyTs) [inline src/Test/Utilities/Shared/Assert/ConditionalFactAttribute.cs]: ```!System.Globalization.CultureInfo.CurrentUICulture.Name.StartsWith("en", StringComparison.OrdinalIgnoreCase)```?

To be consistent with code in src\Test\Utilities\Shared\FX\EnsureEnglishUICulture.cs

**Comment by jaredpar** [comment]
:+1:

File: src/Test/Utilities/Shared/Assert/ConditionalFactAttribute.cs (hunk 2 above)
Comment (TyOverby) [inline src/Test/Utilities/Shared/Assert/ConditionalFactAttribute.cs]: Done.

**Comment by AlekseyTs** [comment]
LGTM

**Comment by TyOverby** [comment]
@dotnet-bot test this please
