### PR TITLE
Fix Quick Info nullability display for backing fields

### LINKED ISSUE #77219: Nullable Quick Info for `field` uses unspeakable name
It looks like we only half-handled this for Quick Info.

Quick Info tooltip saying "'<Prop>k__BackingField' is not null here."

@jasonmalinowski do you know which API is being used to display the symbol here? Maybe just `Name`? I am wondering if some SymbolDisplay needs to be used instead, or if IDE needs to special case it, or if compiler needs to expose something new for the layers to work appropriately.. 

 _Originally posted by @RikkiGibson in [#75529](https://github.com/dotnet/roslyn/issues/75529#issuecomment-2657979025)_

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #77219

### CODE REVIEW

File: src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs [hunk 1]
```diff
@@ -2164,6 +2164,123 @@ class C {
...
         }
 
+        [Fact]
+        public void TestPropertyBackingField_Minimal_01()
+        {
+            var text = @"
+#nullable enable
+class C {
+    string P { get; set; } }
+";
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs:2174]: raw string plz

File: src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs [hunk 2]
```diff
@@ -2164,6 +2164,123 @@ class C {
                 SymbolDisplayPartKind.Keyword);
         }
 
+        [Fact]
```
Comment (CyrusNajmabadi) [inline src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs:2167]:
```suggestion
        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/77219")]
```

File: src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs (hunk 1 above)
Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs:2174]: oh. this is a compiler test.  up to you.

File: src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs [hunk 3]
```diff
@@ -7998,6 +7998,44 @@ void N()
             NullabilityAnalysis(string.Format(FeaturesResources._0_is_not_null_here, "s")));
     }
 
+    [Fact]
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs:8001]:
```suggestion
    [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/77219")]
```

**Review by CyrusNajmabadi — APPROVED** [review]
IDE side lgtm.

File: src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs [hunk 4]
```diff
@@ -2164,6 +2164,123 @@ class C {
...
+                text,
+                findSymbol,
+                format,
+                "P.field",
+                SymbolDisplayPartKind.PropertyName,
+                SymbolDisplayPartKind.Punctuation,
+                SymbolDisplayPartKind.Keyword);
+        }
+
+        [Fact]
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs:2194]:
```suggestion
        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/77219")]
```

File: src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs [hunk 5]
```diff
@@ -2164,6 +2164,123 @@ class C {
...
+                format,
+                "I.P.field",
+                SymbolDisplayPartKind.InterfaceName,
+                SymbolDisplayPartKind.Punctuation,
+                SymbolDisplayPartKind.PropertyName,
+                SymbolDisplayPartKind.Punctuation,
+                SymbolDisplayPartKind.Keyword);
+        }
+
+        [Fact]
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs:2228]:
```suggestion
        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/77219")]
```

File: src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs [hunk 6]
```diff
@@ -2164,6 +2164,123 @@ class C {
...
+                format,
+                "P.field",
+                SymbolDisplayPartKind.InterfaceName,
+                SymbolDisplayPartKind.Punctuation,
+                SymbolDisplayPartKind.PropertyName,
+                SymbolDisplayPartKind.Punctuation,
+                SymbolDisplayPartKind.Keyword);
+        }
+
+        [Fact]
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs:2260]:
```suggestion
        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/77219")]
```

File: src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs [hunk 7]
```diff
@@ -7998,6 +7998,44 @@ void N()
...
+                {
+                    get => $$field;
+                }
+            }
+            """,
+            MainDescription($"({FeaturesResources.field}) string? X.P.field"),
+            NullabilityAnalysis(string.Format(FeaturesResources._0_may_be_null_here, "P.field")));
+    }
+
+    [Fact]
```
Comment (RikkiGibson) [inline src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs:8020]:
```suggestion
        [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/77219")]
```

File: src/Features/Core/Portable/QuickInfo/QuickInfoUtilities.cs [hunk 8]
```diff
@@ -18,6 +18,11 @@ namespace Microsoft.CodeAnalysis.QuickInfo;
 
 internal static class QuickInfoUtilities
 {
+    /// <summary>
+    /// Display variable name only.
+    /// </summary>.
```
Comment (RikkiGibson) [inline src/Features/Core/Portable/QuickInfo/QuickInfoUtilities.cs:23]:
```suggestion
    /// </summary>
```

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler Small test-only change on the compiler side.

File: src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs [hunk 9]
```diff
@@ -2164,6 +2164,123 @@ class C {
...
+            TestSymbolDescription(
+                text,
+                findSymbol,
+                format,
+                "P.field",
+                SymbolDisplayPartKind.InterfaceName,
+                SymbolDisplayPartKind.Punctuation,
+                SymbolDisplayPartKind.PropertyName,
+                SymbolDisplayPartKind.Punctuation,
+                SymbolDisplayPartKind.Keyword);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs:2257]:
```suggestion
                SymbolDisplayPartKind.PropertyName,
                SymbolDisplayPartKind.Punctuation,
                SymbolDisplayPartKind.Keyword);
```

**Comment by RikkiGibson** [comment]
@cston for review of a test-only change

File: src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs [hunk 10]
```diff
@@ -2164,6 +2164,121 @@ class C {
...
+        {
+            var text = @"
+#nullable enable
+class C {
+    string P { get; set; } }
+";
+
+            Func<NamespaceSymbol, Symbol> findSymbol = global =>
+                global.GetTypeMembers("C", 0).Single().
+                GetMembers("<P>k__BackingField").Single();
```
Comment (jasonmalinowski) [inline src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs:2178]: There's no better way to do this?

**Review by jasonmalinowski — APPROVED** [review]

File: src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs (hunk 10 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs:2178]: There isn't an API on the IPropertySymbol that gives us the backing field, for example, so I don't think there are particularly better ways to do this in general.

Comment (CyrusNajmabadi) [reply src/Compilers/CSharp/Test/Symbol/SymbolDisplay/SymbolDisplayTests.cs:2178]: I believe there's an issue asking for this. The ide has wanted such an associated symbol API since forever :-)

Note, what you can do instead is get all the fields and they get the single one associated with the property of interest.

**Review by cston — APPROVED** [review]
Compiler tests LGTM.
