### PR TITLE
Display documentation from associated property/event when showing QuickInfo for get/set and add/remove

### LINKED ISSUE #29703: Quick Info shows incorrect documentation on get/set accessors
**Version Used**: 
Visual Studio 2017 28105.1.d15.9

**Steps to Reproduce**:

1. Create a C# Console project (.NET Core)
2. Add some comments to the Program class

```C#
namespace Demo
{
    /// <summary>
    /// Main application entrypoint.
    /// </summary>
    internal class Program
    {
        /// <summary>
        /// Gets or sets the value.
        /// </summary>
        /// <value>
        /// The value.
        /// </value>
        public string Value { get; set; }

        /// <summary>
        /// Main entry point.
        /// </summary>
        /// <param name="args">The arguments.</param>
        public static void Main(string[] args)
        {
        }
    }
}
```

3. Hover over to the `get` or `set` accessor of the `Value` property

**Expected Behavior**:
The quick info should show the XML comments for  `Value` property

**Actual Behavior**:
The quick info shows XML comments from the `Program` class

image

### PR DESCRIPTION
**Pull request by Scott-Caldwell**
Prior to this PR, the QuickInfo for property get/set accessors and event add/remove methods would display the documentation for the containing type rather than the property or event. This PR rectifies that so that the property/event documentation is displayed in the QuickInfo instead.

image

Fixes #29703.

### CODE REVIEW

File: src/Features/Core/Portable/Shared/Extensions/ISymbolExtensions_2.cs [hunk 1]
```diff
@@ -246,7 +246,7 @@ private static string GetMethodDocumentation(IMethodSymbol method)
                 case MethodKind.EventRemove:
                 case MethodKind.PropertyGet:
                 case MethodKind.PropertySet:
-                    return method.ContainingSymbol.GetDocumentationComment().SummaryText;
+                    return method.AssociatedSymbol.GetDocumentationComment().SummaryText;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/Shared/Extensions/ISymbolExtensions_2.cs]: i'm a little nervous about this somehow being null in some error case... @gafter Is it an invariant that if you're a .PropertyGet/Set that you always have a non-null AssociatedSymbol?  Thanks!

Comment (jasonmalinowski) [reply src/Features/Core/Portable/Shared/Extensions/ISymbolExtensions_2.cs]: (I've forwarded this question to the team internally.)

**Comment by jasonmalinowski** [comment]
Once the AssociatedSymbol question is resolved, I'm happy to merge this unless @CyrusNajmabadi you have any other thoughts.

**Comment by CyrusNajmabadi** [comment]
No other concerns on my part!

File: src/Features/Core/Portable/Shared/Extensions/ISymbolExtensions_2.cs (hunk 1 above)
Comment (gafter) [reply src/Features/Core/Portable/Shared/Extensions/ISymbolExtensions_2.cs]: I believe so.  Having said that, extra null checks couldn't hurt.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please.

**Comment by jasonmalinowski** [comment]
Thanks @Scott-Caldwell for the fix!
