### PR TITLE
Covariant returns part 4

### LINKED ISSUE #44067: Eliminate Warning CS1957 (runtime ambiguous override) by generating correct code
The compiler sometimes reports CS1957:

```csharp
class Base<TInt>
{
    //these signatures differ only in ref/out
    public virtual void Method(int @in, ref int @ref) { }
    public virtual void Method(TInt @in, out TInt @out) { @out = @in; }
}

class Derived : Base<int>
{
    public override void Method(int @in, ref int @ref) { } // HERE
}
```

`warning CS1957: Member 'Derived.Method(int, ref int)' overrides 'Base<int>.Method(int, ref int)'. There are multiple override candidates at run-time. It is implementation dependent which method will be called.`

The compiler is capable of emitting a methodimpl record which will disambiguate the situation for the runtime.  If we do that, there will never be any need to produce this warning.  Perhaps more importantly, the compile-time behavior and the runtime behavior will agree.

### LINKED ISSUE #44068: Consider cacheing `ExplicitlyOverriddenClassMethod` in `PEMethodSymbol`
A new property `ExplicitlyOverriddenClassMethod` is added in `PEMethodSymbol` to assist in the implementation of covariant return types.  It is possible that cacheing it may increase the cost of compilation overall (due to the space for the cache), but it is possible it may decrease compilation time overall. Or it may have no impact. This issue tracks considering whether or not something should be changed.

### LINKED ISSUE #45337: Compiler generated IL overrides wrong method
The following program prints "1" instead of "2" as required. That is because the override in `Derived` is viewed by the runtime as overriding the wrong method (the C# compiler fails to produce the required methodimpl/`.override` data in the generated assembly).

A similar program with `Base.M` being `abstract` generates a type load exception at runtime.

```csharp
using System;
class Base
{
    public virtual void M(out int x) { x = 1; }
}
abstract class Base2 : Base
{
    public virtual void M(ref int x) { }
}
class Derived : Base2
{
    public override void M(out int x) { x = 3; }
}
class Program
{
    static void Main()
    {
        var b = new Derived();
        b.M(out int x);
        Console.WriteLine(x);
    }
}
```

### PR DESCRIPTION
**Pull request by gafter**
- Respond to review comments from part 3 (https://github.com/dotnet/roslyn/pull/43797)
- Implement and test retargeting symbols for covariant returns.
- A PE symbol with multiple methodimpl entries is ignored as an explicit override for language covariant returns.
- Test binary compatibility scenarios with overrides inserted into the hierarchy.
- A methodimpl may be required anytime the runtime and language disagree about the overridden method.
- Emit a call to the least derived override in the hierarchy with the correct return type.
- Test covariant returns in expression trees.
- Test capturing a covariant method in a delegate creation.
- Test consumption and override of covariantly overridden methods, properties, and indexers from VB.
- Require that the target runtime supports covariant returns when the feature is used.
- Test compile-time behavior of nullable variance in covariant returns.
- Produce `RequireMethodImplToRemainInEffectAttribute` on covariant overrides.
- Eliminate CS1957 by generating correct code via methodimpl records.
   Fixes #44067
- Cache `PEMethodSymbol.ExplicitlyOverriddenClassMethod`
   Closes #44068
- Move some PROTOTYPE comments to issues.
   Relates to #44206, #44207, #44208, #44209
- Incidentally fixes #45337
- Condition WRN_MultipleRuntimeOverrideMatches on whether runtime has buggy methodimpl
   Relates to https://github.com/dotnet/runtime/issues/38119
   Fixes https://github.com/dotnet/roslyn/issues/45453

### CODE REVIEW

**Comment by gafter** [comment]
May I please have a couple of reviews of this next round of changes for covariant returns from the compiler team? It is mostly tests.

**Comment by gafter** [comment]
@AlekseyTs @dotnet/roslyn-compiler May I please have a couple of reviews of this next round of changes for covariant returns? It is mostly tests.

**Comment by gafter** [comment]
@AlekseyTs @dotnet/roslyn-compiler May I please have a couple of reviews of this next round of changes for covariant returns?

File: src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs [hunk 1]
```diff
@@ -387,7 +387,8 @@ public virtual ImmutableArray<CSharpAttributeData> GetReturnTypeAttributes()
         /// ignoring any other overriding methods in base classes.
         /// </summary>
         /// <param name="accessingTypeOpt">The search must respect accessibility from this type.</param>
-        internal MethodSymbol GetLeastOverriddenMethod(NamedTypeSymbol accessingTypeOpt)
+        /// <param name="withSameReturnType">The returned method must have the same return type.</param>
+        internal MethodSymbol GetLeastOverriddenMethod(NamedTypeSymbol accessingTypeOpt, bool withSameReturnType = false)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs:391]: > = false [](start = 112, length = 8)

Please make this a required parameter so that every consumer has to make an explicit decision what to pass, and, while reviewing this PR, we could be certain that all existing call sites are properly adjusted.

File: src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs [hunk 2]
```diff
@@ -433,9 +436,10 @@ internal MethodSymbol GetLeastOverriddenMethod(NamedTypeSymbol accessingTypeOpt)
         /// Also, if the given method symbol is generic then the resulting virtual or abstract method is constructed with the
         /// same type arguments as the given method.
         /// </summary>
-        internal MethodSymbol GetConstructedLeastOverriddenMethod(NamedTypeSymbol accessingTypeOpt)
+        /// <param name="withSameReturnType">The returned method must have the same return type.</param>
+        internal MethodSymbol GetConstructedLeastOverriddenMethod(NamedTypeSymbol accessingTypeOpt, bool withSameReturnType = false)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs:440]: >= false [](start = 124, length = 7)

Same comment about parameter.

File: src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs [hunk 3]
```diff
@@ -465,6 +469,11 @@ public MethodSymbol OverriddenMethod
             }
         }
 
+        /// <summary>
+        /// If we know a specific overridden class method, that method.
+        /// </summary>
+        internal virtual MethodSymbol ExplicitlyOverriddenClassMethod => null;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs:475]: >internal virtual MethodSymbol ExplicitlyOverriddenClassMethod => null; [](start = 8, length = 70)

We have learned over the years that introducing new virtual methods at the top of the symbol hierarchy is error prone. It is very easy to fail to provide a required override for some derived type when the method is introduced. And it is even easier to do that when some derived type is added later. Our current approach is to add abstract methods and provide implementation in all leaf classes. This way we can review that the method is properly implemented for all flavors and can test all relevant scenarios by using code coverage.

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs [hunk 4]
```diff
@@ -262,8 +262,8 @@ bool isAccessorOverride(MethodSymbol accessor, MethodSymbol overriddenAccessor)
                     return MemberSignatureComparer.CSharpAccessorOverrideComparer.Equals(accessor, overriddenAccessor); //NB: custom comparer
                 }
 
-                if (accessor is PEMethodSymbol { ExplicitlyOverriddenClassMethod: MethodSymbol peOverriddenAccessor } &&
-                    overriddenAccessor.Equals(peOverriddenAccessor, TypeCompareKind.AllIgnoreOptions))
+                if (accessor is MethodSymbol { ExplicitlyOverriddenClassMethod: MethodSymbol explicitlyOverriddenAccessor } &&
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:265]: >accessor is MethodSymbol [](start = 20, length = 24)

It looks like ```accessor``` is already a method symbol and the type check is redundant.

File: src/Compilers/CSharp/Portable/Symbols/PropertySymbol.cs [hunk 5]
```diff
@@ -231,6 +231,11 @@ public PropertySymbol OverriddenProperty
             }
         }
 
+        /// <summary>
+        /// If we know a specific overridden class property, that property.
+        /// </summary>
+        internal virtual PropertySymbol ExplicitlyOverriddenClassProperty => null;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/PropertySymbol.cs:237]: >internal virtual PropertySymbol ExplicitlyOverriddenClassProperty => null; [](start = 8, length = 74)

Same comment as for the new virtual API in MethodSymbol

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs [hunk 6]
```diff
@@ -1226,21 +1226,26 @@ private ImmutableArray<MethodSymbol> ExplicitlyOverriddenMethods()
...
+                    MethodSymbol result = null;
                     foreach (MethodSymbol method in ExplicitlyOverriddenMethods())
                     {
                         if (method.ContainingType.IsClassType())
                         {
-                            return method;
+                            if (result is { })
+                                return null;
+
+                            result = method;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs:1244]: >result = method [](start = 28, length = 15)

Do we care if the name matches?

**Comment by AlekseyTs** [comment]
>                     return overriddenProperty;

Do we care if the name matches?

---
Refers to: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEPropertySymbol.cs:546 in 6a2b697. [](commit_id = 6a2b697e18b45f71ca4d60f4de98f0ee9eaa2641, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingMethodSymbol.cs [hunk 7]
```diff
@@ -280,6 +280,16 @@ private ImmutableArray<MethodSymbol> RetargetExplicitInterfaceImplementations()
             return builder.ToImmutableAndFree();
         }
 
+        internal override MethodSymbol ExplicitlyOverriddenClassMethod
+        {
+            get
+            {
+                return _underlyingMethod.OverriddenMethod is MethodSymbol overridden
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingMethodSymbol.cs:287]: >OverriddenMethod [](start = 41, length = 16)

This looks like a bug. Should this be ```ExplicitlyOverriddenClassMethod```? It looks like there is a test gap as well.

File: src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingPropertySymbol.cs [hunk 8]
```diff
@@ -187,6 +187,16 @@ private ImmutableArray<PropertySymbol> RetargetExplicitInterfaceImplementations(
             return builder.ToImmutableAndFree();
         }
 
+        internal override PropertySymbol ExplicitlyOverriddenClassProperty
+        {
+            get
+            {
+                return _underlyingProperty.OverriddenProperty is PropertySymbol overridden
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingPropertySymbol.cs:194]: >OverriddenProperty [](start = 43, length = 18)

This looks like a bug. Should this be ```ExplicitlyOverriddenClassProperty```? It looks like there is a test gap as well.

**Comment by AlekseyTs** [comment]
It feels like at the very least the new APIs should have non-trivial implementation for substituted symbols.

**Comment by AlekseyTs** [comment]
>     }

I think it is also interesting to check what method is going to be called when we virtually call ```Base2<int, int>.Method(out List<int> x)``` on instance in ```b```

---
Refers to: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs:1150 in 6a2b697. [](commit_id = 6a2b697e18b45f71ca4d60f4de98f0ee9eaa2641, deletion_comment = False)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs [hunk 9]
```diff
@@ -627,6 +627,14 @@ .maxstack  1
         [Fact, WorkItem(540019, "http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/540019")]
         public void TestBug6156()
         {
+            // Note: this test originally required a mismatch between the compile-time view of what the
+            // program should do and the runtime view.  The runtime considers `ref` and `out` to be the
+            // same, so it had a different view of what one method was overriding than C# did.  However,
+            // in the context of implementing the covariant return types feature, we added code in the compiler to
+            // cause the compiler to emit methodimpl records whenever there is a mismatch.  As a consequence
+            // of that, this we updated test to now require that the runtime behavior and the compile-time behavior
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs:635]: >this [](start = 24, length = 4)

Typo?

File: src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Source/OverridesTests.vb [hunk 10]
```diff
@@ -7213,5 +7213,63 @@ End Class
 void ValidatorBase<T>.DoValidate(T objectToValidate)")
         End Sub
 
+        <Fact>
+        Public Sub OverrideOfCSharpCovariantReturn()
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Source/OverridesTests.vb:7217]: >OverrideOfCSharpCovariantReturn [](start = 19, length = 31)

I think we should also add a test for a success scenario where VB overrides  with return type String and calling through Base and Derived calls the overrides.

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs [hunk 11]
```diff
@@ -125,6 +156,27 @@ private static CSharpCompilation MetadataView(CSharpCompilation comp, params Met
...
+            references = references.Append(comp.ToMetadataReference());
+            var result = CreateCompilation("", references: references, targetFramework: TargetFramework.NetStandardLatest);
+            result.VerifyDiagnostics();
+            var originalCorLib = comp.Assembly.CorLibrary;
+            var newCorLib = result.Assembly.CorLibrary;
+            Assert.NotEqual(originalCorLib, newCorLib);
+
+            if (someType is { })
+            {
+                // confirm that it is retargeted
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:171]: >confirm that it is retargeted [](start = 19, length = 29)

Only types declared in ```comp.SourceModule``` are going to be retargeting. Consider adjusting the way we locate the type to make more precise and to ensure we are not going to pick up a type from a referenced assembly.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:171]: >retargeted [](start = 38, length = 10)

retargeting vs. retargeted

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs [hunk 12]
```diff
@@ -125,6 +156,27 @@ private static CSharpCompilation MetadataView(CSharpCompilation comp, params Met
...
+                var someRetargetedType = result.GlobalNamespace.GetMembers(someType.Name).OfType<NamedTypeSymbol>().FirstOrDefault();
+                var someRetargetedMember = someRetargetedType.GetMembers().OfType<MethodSymbol>().FirstOrDefault();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:173]: >var someRetargetedMember = someRetargetedType.GetMembers().OfType<MethodSymbol>().FirstOrDefault(); [](start = 16, length = 99)

Is it necessary to assert the member? Would it be sufficient to assert that the type is retargeting?

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs [hunk 13]
```diff
@@ -125,6 +156,27 @@ private static CSharpCompilation MetadataView(CSharpCompilation comp, params Met
...
+            var result = CreateCompilation("", references: references, targetFramework: TargetFramework.NetStandardLatest);
+            result.VerifyDiagnostics();
+            var originalCorLib = comp.Assembly.CorLibrary;
+            var newCorLib = result.Assembly.CorLibrary;
+            Assert.NotEqual(originalCorLib, newCorLib);
+
+            if (someType is { })
+            {
+                // confirm that it is retargeted
+                var someRetargetedType = result.GlobalNamespace.GetMembers(someType.Name).OfType<NamedTypeSymbol>().FirstOrDefault();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:172]: >result.GlobalNamespace [](start = 41, length = 22)

Instead of looking across the world, we could look in AssemblySymbol corresponding to the metadata reference for ```comp```. The type must be in that assembly.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:172]: >FirstOrDefault [](start = 116, length = 14)

Why would we ever fail to locate the type?

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs (hunk 11 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:171]: The same issue with variable names.

---
In reply to: [424738892](https://github.com/dotnet/roslyn/pull/44025#discussion_r424738892) [](ancestors = 424738892)

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs [hunk 14]
```diff
@@ -192,16 +263,34 @@ void M(Base b, Derived d)
                 Diagnostic(ErrorCode.ERR_FeatureInPreview, "M").WithArguments("covariant returns").WithLocation(8, 28)
                 );
             verify(comp);
+            VerifyAssignments(comp, 2);
             comp = CreateCompilationWithCovariantReturns(source).VerifyDiagnostics(
                 );
             verify(comp);
+            VerifyAssignments(comp, 2);
             verify(CompilationReferenceView(comp));
             verify(MetadataView(comp));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:272]: >verify(MetadataView(comp)); [](start = 12, length = 27)

I think we should strengthen the tests and create metadata and retargeted view with ```Program``` class as well (rather than with an empty source) and verify assignments and IL for them too. This applies to other similar tests too.

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs [hunk 15]
```diff
@@ -1659,11 +2115,793 @@ End Class
...
+            verify1(comp);
+
+            comp = CreateCompilationWithCovariantReturns(s2, references: new[] { ref0, ref1a }).VerifyDiagnostics(
+                );
+            verify1(comp);
+            verify1(CompilationReferenceView(comp, ref0, ref1a));
+            verify1(MetadataView(comp, ref0, ref1a));
+            verify1(RetargetedView(comp, ref0, ref1a));
+
+            verify2(CompilationReferenceView(comp, ref0, ref1b));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:2337]: >CompilationReferenceView [](start = 20, length = 24)

Isn't this going to create a retargeting assembly?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:2337]: Perhaps the helper should assert that we are indeed reuse SourceAssemblySymbol

---
In reply to: [424776007](https://github.com/dotnet/roslyn/pull/44025#discussion_r424776007) [](ancestors = 424776007)

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs [hunk 16]
```diff
@@ -1659,11 +2115,793 @@ End Class
...
+public class Mid : Base
+{
+}
+";
+            var ref1a = CreateCompilationWithoutCovariantReturns(s1a, references: new[] { ref0 }, assemblyName: "ref1").EmitToImageReference();
+
+            var s1b = @"
+public class Mid : Base
+{
+    public override string M() => null;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:2312]: >public override string M() => null; [](start = 4, length = 35)

I think we should also test scenario when this is:
- ```new virtual method```, I assume it will be newSlot
- ```new``` but not virtual, I assume it will be newSlot
- all of the above including original but when there is no hidebysig flag in metadata. 

Also when the method overrides explicitly, but not the Base.M, but rather a method higher in the type hierarchy.

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs [hunk 17]
```diff
@@ -1659,11 +2115,793 @@ End Class
...
+
+            static void verify2(CSharpCompilation comp)
+            {
+                VerifyOverride(comp, "Derived.M", "System.String Derived.M()", "System.String Mid.M()", binaryCompat: true);
+                VerifyOverride(comp, "Mid.M", "System.String Mid.M()", "System.Object Base.M()");
+            }
+        }
+
+        [Fact]
+        public void BinaryCompatibility_02()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:2354]: >BinaryCompatibility_02 [](start = 20, length = 22)

I assume this is a "clone" of the previous test. Same comments apply.

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs [hunk 18]
```diff
@@ -1659,11 +2115,793 @@ End Class
...
+            verify1(comp);
+
+            comp = CreateCompilationWithCovariantReturns(s2, references: new[] { ref0, ref1a }).VerifyDiagnostics(
+                );
+            verify1(comp);
+            verify1(CompilationReferenceView(comp, ref0, ref1a));
+            verify1(MetadataView(comp, ref0, ref1a));
+            verify1(RetargetedView(comp, ref0, ref1a));
+
+            verify2(CompilationReferenceView(comp, ref0, ref1b));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:2464]: >CompilationReferenceView [](start = 20, length = 24)

Same comment

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs [hunk 19]
```diff
@@ -1659,11 +2115,793 @@ End Class
...
+            {
+                VerifyOverride(comp, "Derived.M", "System.String Derived.M()", "System.Object Base.M()");
+            }
+
+            static void verify2(CSharpCompilation comp)
+            {
+                // When viewed from metadata, we do not see a relationship between Derived.M and Mid.M because
+                // there is nothing in the metadata to indicate there is relationship. The compiler
+                // does no simulate the covariant language rules on metadata nor does the compiler simulate the
+                // virtual slot unification that the runtime does.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:2478]: >// virtual slot unification that the runtime does. [](start = 16, length = 50)

Please add a PROTOTYPE comment to verify this assumption once we have a runtime to test against.

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs [hunk 20]
```diff
@@ -1659,11 +2115,793 @@ End Class
...
+public class Mid : Base
+{
+}
+";
+            var ref1a = CreateCompilationWithoutCovariantReturns(s1a, references: new[] { ref0 }, assemblyName: "ref1").EmitToImageReference();
+
+            var s1b = @"
+public class Mid : Base
+{
+    public override object M() => null;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:2439]: >public override object M() => null; [](start = 4, length = 35)

I think we should also test scenario when this is:
- new virtual method, I assume it will be newSlot
- new but not virtual, I assume it will be newSlot
- all of the above including original but when there is no hidebysig flag in metadata.

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs [hunk 21]
```diff
@@ -1659,11 +2115,793 @@ End Class
...
+}
+
+public class B : A
+{
+    public virtual object P => null;
+}
+
+public class C : B
+{
+    public override string get_P() => null;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:2500]: >string [](start = 20, length = 6)

I think it would be interesting to test what happens when both overrides use object as return types, including checking what runtime "thinks" it should do.

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs [hunk 22]
```diff
@@ -1659,11 +2115,793 @@ End Class
...
+public class Derived : Base
+{
+    public override string M() => null;
+    public override string P => null;
+}
+public class Program : Derived
+{
+    Expression<Func<Derived, string>> M1()
+    {
+        return d => d.M();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:2631]: >d [](start = 20, length = 1)

Consider also testing with ```base``` as receiver.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 13)

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs [hunk 23]
```diff
@@ -1659,11 +2115,793 @@ End Class
...
+  // Code size       13 (0xd)
+  .maxstack  2
+  // sequence point: new Func<string>(base.M)
+  IL_0000:  ldarg.0
+  IL_0001:  ldftn      ""string Derived.M()""
+  IL_0007:  newobj     ""System.Func<string>..ctor(object, System.IntPtr)""
+  IL_000c:  ret
+}
+");
         }
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:2905]: >} [](start = 8, length = 1)

It feels like we should test how overriding related APIs behave in constructed types.

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs [hunk 24]
```diff
@@ -1659,11 +2115,793 @@ End Class
...
+            verify1(MetadataView(comp, ref0, ref1a));
+            verify1(RetargetedView(comp, ref0, ref1a));
+
+            verify2(CompilationReferenceView(comp, ref0, ref1b));
+            verify2(MetadataView(comp, ref0, ref1b));
+            verify2(RetargetedView(comp, ref0, ref1b));
+
+            static void verify1(CSharpCompilation comp)
+            {
+                VerifyOverride(comp, "Derived.M", "System.String Derived.M()", "System.Object Base.M()");
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:2343]: >VerifyOverride [](start = 16, length = 14)

In addition to this check it would be good to observe what are we going to call for an invocation of ```d.M()``` for a given set of references, where d is an instance of Derived.

File: src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs (hunk 3 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs:475]: >ExplicitlyOverriddenClassMethod [](start = 38, length = 31)

I would expect to see some targeted tests for this API.

File: src/Compilers/CSharp/Portable/Symbols/PropertySymbol.cs (hunk 5 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/PropertySymbol.cs:237]: >ExplicitlyOverriddenClassProperty [](start = 40, length = 33)

I would expect to see some targeted tests for this API.

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs [hunk 25]
```diff
@@ -1226,21 +1226,26 @@ private ImmutableArray<MethodSymbol> ExplicitlyOverriddenMethods()
...
                 {
+                    // If there is a *single* methodimpl entry, we return that.
+                    MethodSymbol result = null;
                     foreach (MethodSymbol method in ExplicitlyOverriddenMethods())
                     {
                         if (method.ContainingType.IsClassType())
                         {
-                            return method;
+                            if (result is { })
+                                return null;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs:1242]: > return null; [](start = 31, length = 13)

Is this code path covered by a test?

**Comment by gafter** [comment]
They aren't used for substituted symbols.  I've removed the API on `MethodSymbol` and `PropertySymbol` and instead provided non-virtual helpers (with tests) for for use in `OverriddenOrHiddenMembersHelpers`, as this is an implementation detail of the latter.

---
In reply to: [628192335](https://github.com/dotnet/roslyn/pull/44025#issuecomment-628192335) [](ancestors = 628192335)

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs (hunk 6 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs]: No.

---
In reply to: [424661333](https://github.com/dotnet/roslyn/pull/44025#discussion_r424661333) [](ancestors = 424661333)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs]: >> Do we care if the name matches?

> No.

It feels like there are interesting scenarios around that. Do we test any?

---
In reply to: [425494566](https://github.com/dotnet/roslyn/pull/44025#discussion_r425494566) [](ancestors = 425494566,424661333)

Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs]: Yes. See, for example, `ExplicitOverrideWithoutCSharpOverride` in `CodeGenOverridingAndHiding.cs`.

---
In reply to: [425496726](https://github.com/dotnet/roslyn/pull/44025#discussion_r425496726) [](ancestors = 425496726,425494566,424661333)

File: src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingMethodSymbol.cs (hunk 7 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingMethodSymbol.cs:287]: No, this is intended and necessary for correctness. Most of the tests would break if changed as suggested. Having said that, this method is removed later in this PR.

---
In reply to: [424665540](https://github.com/dotnet/roslyn/pull/44025#discussion_r424665540) [](ancestors = 424665540)

File: src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingPropertySymbol.cs (hunk 8 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingPropertySymbol.cs:194]: No, this is intended and necessary for correctness. Most of the tests would break if changed as suggested. Having said that, this method is removed later in this PR.

---
In reply to: [424665880](https://github.com/dotnet/roslyn/pull/44025#discussion_r424665880) [](ancestors = 424665880)

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs (hunk 11 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:186]: I am using it as an adjective, not as a type name. We have an inconsistency in the compiler today with what verb tense we use (SubstitutedSymbol, etc, vs RetargetingSymbol). We should be consistent, and I will file an issue to rename these to use the same past tense that we use everywhere.

---
In reply to: [424742356](https://github.com/dotnet/roslyn/pull/44025#discussion_r424742356) [](ancestors = 424742356,424738892)

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs (hunk 22 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:2776]: That is a semantic error.

---
In reply to: [424787359](https://github.com/dotnet/roslyn/pull/44025#discussion_r424787359) [](ancestors = 424787359)

**Comment by gafter** [comment]
>                     return overriddenProperty;

No.

---
In reply to: [628181507](https://github.com/dotnet/roslyn/pull/44025#issuecomment-628181507) [](ancestors = 628181507)

---
Refers to: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEPropertySymbol.cs:546 in 6a2b697. [](commit_id = 6a2b697e18b45f71ca4d60f4de98f0ee9eaa2641, deletion_comment = False)

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs (hunk 11 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:186]: > I am using it as an adjective, not as a type name. I will change "is" to "has been" for clarity. We have an inconsistency in the compiler today with what verb tense we use (SubstitutedSymbol, etc, vs RetargetingSymbol). We should be consistent, and I will file an issue to rename these to use the same past tense that we use everywhere.

The names reflecting what the symbols are doing, they are performing retargeting, they are not retargeted. References are retargeted, definitions are not, definitions perform retargeting. 

---
In reply to: [425950644](https://github.com/dotnet/roslyn/pull/44025#discussion_r425950644) [](ancestors = 425950644,424742356,424738892)

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs (hunk 4 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs]: No additional code is produced. This is written for clarity.

---
In reply to: [424656304](https://github.com/dotnet/roslyn/pull/44025#discussion_r424656304) [](ancestors = 424656304)

File: src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs (hunk 3 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs]: This method is removed later in this PR.

---
In reply to: [424636776](https://github.com/dotnet/roslyn/pull/44025#discussion_r424636776) [](ancestors = 424636776)

File: src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs (hunk 1 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs]: Parameter is removed later in this PR.

---
In reply to: [424627754](https://github.com/dotnet/roslyn/pull/44025#discussion_r424627754) [](ancestors = 424627754)

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs (hunk 21 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:2668]: I will add a runtime expected output to the existing test `MethodAccessorMethodOverridingRoundTrip` in `CodeGenOverridingAndHiding`.

---
In reply to: [424784704](https://github.com/dotnet/roslyn/pull/44025#discussion_r424784704) [](ancestors = 424784704)

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs (hunk 25 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs]: Yes; see `PEMethodSymbol_ExplicitlyOverriddenClassMethod_WhenAmbiguous` in a later iteration.

---
In reply to: [424901858](https://github.com/dotnet/roslyn/pull/44025#discussion_r424901858) [](ancestors = 424901858)

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs (hunk 16 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:2480]: The "Also when the method overrides explicitly, but not the Base.M, but rather a method higher in the type hierarchy." is what is tested on `Derived.M` in `verify2` below.

I have added the other suggestions to the test plan.

---
In reply to: [424780749](https://github.com/dotnet/roslyn/pull/44025#discussion_r424780749) [](ancestors = 424780749)

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs (hunk 24 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:2511]: This PR is for compile-time behavior only. We already have tests that demonstrate what IL is produced by the compiler for source with particular base classes.

---
In reply to: [424885197](https://github.com/dotnet/roslyn/pull/44025#discussion_r424885197) [](ancestors = 424885197)

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs (hunk 19 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:2646]: There is nothing prototypish about this code.  I will add this suggestion to the test plan.

---
In reply to: [424782561](https://github.com/dotnet/roslyn/pull/44025#discussion_r424782561) [](ancestors = 424782561)

File: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs (hunk 20 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:2607]: These suggestions are recorded in the test plan.

---
In reply to: [424783253](https://github.com/dotnet/roslyn/pull/44025#discussion_r424783253) [](ancestors = 424783253)

File: src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Source/OverridesTests.vb (hunk 10 above)
Comment (gafter) [reply src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Source/OverridesTests.vb:7217]: I will add the compile-time success test. Runtime tests will have to wait. I will show the IL at the call site.

---
In reply to: [424732466](https://github.com/dotnet/roslyn/pull/44025#discussion_r424732466) [](ancestors = 424732466)

**Comment by gafter** [comment]
@AlekseyTs I believe I've responded to all of your comments. Do you have any others?

@dotnet/roslyn-compiler May I please have a second review?

**Comment by gafter** [comment]
@AlekseyTs I believe I've responded to all of your comments. Do you have any others?

@dotnet/roslyn-compiler May I please have a second review?

**Comment by gafter** [comment]
@AlekseyTs I believe I've responded to all of your comments. Do you have any others?

@dotnet/roslyn-compiler May I please have a second review?

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs [hunk 26]
```diff
@@ -233,6 +233,7 @@ private sealed class UncommonFields
             public ImmutableArray<string> _lazyNotNullMembers;
             public ImmutableArray<string> _lazyNotNullMembersWhenTrue;
             public ImmutableArray<string> _lazyNotNullMembersWhenFalse;
+            public MethodSymbol _lazyExplicitClassOverride;
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs:236]: If this is allowed to contain null consider enabling nullable for this piece so that you can annotate it.

File: src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs [hunk 27]
```diff
@@ -416,7 +427,9 @@ internal MethodSymbol GetLeastOverriddenMethod(NamedTypeSymbol accessingTypeOpt)
                 // See InternalsVisibleToAndStrongNameTests: IvtVirtualCall1, IvtVirtualCall2, IvtVirtual_ParamsAndDynamic.
                 MethodSymbol overridden = m.OverriddenMethod;
                 HashSet<DiagnosticInfo> useSiteDiagnostics = null;
-                if ((object)overridden == null || !AccessCheck.IsSymbolAccessible(overridden, accessingType, ref useSiteDiagnostics))
+                if ((object)overridden == null ||
+                    !AccessCheck.IsSymbolAccessible(overridden, accessingType, ref useSiteDiagnostics) ||
+                    (requireSameReturnType && !this.ReturnType.Equals(overridden.ReturnType, TypeCompareKind.AllIgnoreOptions)))
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs:432]: Does AllIgnoreOptions also ignore custom modifiers? We probably want to keep that, don't we?

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs [hunk 28]
```diff
@@ -1099,15 +1098,14 @@ static bool isOrContainsErrorType(TypeSymbol typeSymbol)
         /// </summary>
         private bool IsValidOverrideReturnType(Symbol overridingSymbol, TypeWithAnnotations overridingReturnType, TypeWithAnnotations overriddenReturnType, DiagnosticBag diagnostics)
         {
-            if (DeclaringCompilation.LanguageVersion >= MessageID.IDS_FeatureCovariantReturnsForOverrides.RequiredVersion())
+            if (overridingSymbol.ContainingAssembly.RuntimeSupportsCovariantReturnsOfClasses &&
+                DeclaringCompilation.LanguageVersion >= MessageID.IDS_FeatureCovariantReturnsForOverrides.RequiredVersion())
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs:1102]: Can we use the `CheckFeatureAvailability` helper instead? Allowing indirection here as helped us produce better diagnostics in the past.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs [hunk 29]
```diff
@@ -627,6 +627,14 @@ .maxstack  1
...
         public void TestBug6156()
         {
+            // Note: this test originally required a mismatch between the compile-time view of what the
+            // program should do and the runtime view.  The runtime considers `ref` and `out` to be the
+            // same, so it had a different view of what one method was overriding than C# did.  However,
+            // in the context of implementing the covariant return types feature, we added code in the compiler to
+            // cause the compiler to emit methodimpl records whenever there is a mismatch.  As a consequence
+            // of that, we updated this test to now require that the runtime behavior and the compile-time behavior
+            // of this program match, so that at runtime it obeys the behavior specified by the C#
+            // language specification.
```
Comment (agocke) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs:637]: Interesting... we should note this breaking change somewhere

Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs:637]: Looks more like a bug fix than a breaking change. We generated code to call the wrong (unrelated!) method before. Now the code causes the right method to be called.

---
In reply to: [437698623](https://github.com/dotnet/roslyn/pull/44025#discussion_r437698623) [](ancestors = 437698623)

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs (hunk 28 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol_ImplementationChecks.cs:1124]: No, because the purpose of this code is not to report a language version diagnostic.

---
In reply to: [437696307](https://github.com/dotnet/roslyn/pull/44025#discussion_r437696307) [](ancestors = 437696307)

File: src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs (hunk 27 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/MethodSymbol.cs:437]: I don't think so. The language's overriding rules ignore custom modifiers. Their presence may cause the compiler to add them to the override.

---
In reply to: [437693763](https://github.com/dotnet/roslyn/pull/44025#discussion_r437693763) [](ancestors = 437693763)

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs (hunk 26 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs:247]: All of these fields that are of ref type can be null. The thing to annotate would be `internal MethodSymbol ExplicitlyOverriddenClassMethod`. But I don't want to take on annotating this in the context of this PR.

---
In reply to: [437685349](https://github.com/dotnet/roslyn/pull/44025#discussion_r437685349) [](ancestors = 437685349)

**Comment by gafter** [comment]
@agocke I think I've responded to all of your comments. Do you have any others?

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs (hunk 29 above)
Comment (agocke) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenTests.cs:637]: Depends on how old this behavior was. It's certainly a change and it could be breaking.

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a second review?

File: src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingMethodSymbol.cs [hunk 30]
```diff
@@ -280,6 +280,19 @@ private ImmutableArray<MethodSymbol> RetargetExplicitInterfaceImplementations()
...
 
+        /// <summary>
+        /// Retarget the underlying method's overridden method.
+        /// </summary>
+        internal MethodSymbol RetargetOverriddenMethod
+        {
+            get
+            {
+                return _underlyingMethod.OverriddenMethod is MethodSymbol overridden
+                    ? this.RetargetingTranslator.Retarget(overridden, MemberSignatureComparer.RetargetedExplicitImplementationComparer)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingMethodSymbol.cs:291]: >this.RetargetingTranslator.Retarget(overridden, MemberSignatureComparer.RetargetedExplicitImplementationComparer) [](start = 22, length = 113)

Retargeting the overridden method calculated in a different "universe" feels like a wrong thing to do. I think we should re-resolve overriding instead, otherwise we will not match result with metadata when an override is added/removed, etc. in the new compilation.

Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingMethodSymbol.cs:291]: This method is the overriding method. I presume you mean re-resolve the overridden method? That is indeed what is done in `OverriddenOrHiddenMembersHelpers`. However, the value returned by this property is used in the face of covariant returns, just as it is will be used by the runtime in the face of covariant returns unless the retargeted method is recompiled with the revised reference. In other words, the intent of this property is to assist `OverriddenOrHiddenMembersHelpers` in modeling what the runtime does rather than modeling what would happen if the retargeted method were recompiled.

If you still think this is incorrect, can you please be more explicit about the scenario that you believe might behave incorrectly?

---
In reply to: [441831407](https://github.com/dotnet/roslyn/pull/44025#discussion_r441831407) [](ancestors = 441831407)

**Comment by gafter** [comment]
@AlekseyTs I believe I've responded to all of your comments. Do you have any others?

File: src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingMethodSymbol.cs (hunk 30 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingMethodSymbol.cs:291]: > However, the value returned by this property is used in the face of covariant returns

I see no indication in this method (neither in its name, or in its implementation) that we are dealing with an override that will have an explicit MethodImpl emitted in metadata. Only under these conditions the current implementation would be correct, I think. If that is the only scenario when this method is supposed to be used, I suggest a rename to indicate this restriction and an assert inside to verify the MethodImpl requirement.

---
In reply to: [441896761](https://github.com/dotnet/roslyn/pull/44025#discussion_r441896761) [](ancestors = 441896761,441831407)

File: src/Compilers/CSharp/Portable/CSharpResources.resx [hunk 31]
```diff
@@ -3371,12 +3371,6 @@ Although C# distinguishes between out and ref, the CLR sees them as the same. Wh
 
 Give the compiler some way to differentiate the methods. For example, you can give them different names or provide an additional parameter on one of them.</value>
   </data>
-  <data name="WRN_MultipleRuntimeOverrideMatches" xml:space="preserve">
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/CSharpResources.resx:3374]: >WRN_MultipleRuntimeOverrideMatches [](start = 14, length = 34)

I think this warning is still applicable in some scenarios, even with explicit MethodImpl.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/CSharpResources.resx:3374]: Specifically when two methods collide due to, for example, generic substitution in the base type. Consider adding a test like that and make sure that changing the order of declaration for methods in the base doesn't affect what method is getting overridden. Same for the scenario in  #44067. 

---
In reply to: [441902428](https://github.com/dotnet/roslyn/pull/44025#discussion_r441902428) [](ancestors = 441902428)

File: src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingMethodSymbol.cs (hunk 30 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingMethodSymbol.cs:291]: That is the scenario affected by this property, but it is not necessary (or intended) to restrict its use to that or any particular scenario in the implementation for it to have the correct impact on the compiler behavior. I believe the implementation is correct as it currently exists.

---
In reply to: [441898873](https://github.com/dotnet/roslyn/pull/44025#discussion_r441898873) [](ancestors = 441898873,441896761,441831407)

File: src/Compilers/CSharp/Portable/CSharpResources.resx (hunk 31 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/CSharpResources.resx:3374]: This warning was not used for that scenario. A different error (`CS0462` `ERR_AmbigOverride`) is produced at the point of the override in that case. We have plenty of tests for that error, and in any case it isn't affected by this PR.

---
In reply to: [441903992](https://github.com/dotnet/roslyn/pull/44025#discussion_r441903992) [](ancestors = 441903992,441902428)

File: src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingMethodSymbol.cs (hunk 30 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingMethodSymbol.cs:291]: > I believe the implementation is correct as it currently exists.

I would agree if that method were to always produce the same result as the ```OverriddenMethod``` API for scenarios when explicit MethodImpl is not involved. However, I do not believe this is the case. For example, I suspect that would not be the case when another override is injected above this method in a new compilation. Please add a direct test for this API for a scenario like that. This is not a private method, its name is very unspecific and its general use is error prone. In order for developers to not misuse this method in the future. I am asking you:
- to rename it so that it reflects the intended usage of the method
- to add an assert to verify that ```overridden``` is indeed going to have an explicit MethodImpl. 

I believe that under other conditions the result returned by this method is meaningless and shouldn't be used.  

---
In reply to: [441921131](https://github.com/dotnet/roslyn/pull/44025#discussion_r441921131) [](ancestors = 441921131,441898873,441896761,441831407)

File: src/Compilers/CSharp/Portable/CSharpResources.resx (hunk 31 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/CSharpResources.resx:3374]: > This warning was not used for that scenario. A different error (CS0462 ERR_AmbigOverride) is produced at the point of the override in that case.

What about the scenario in #44067? The removal of this warning is justified by that issue in ErrorCode.cs.

---
In reply to: [441923177](https://github.com/dotnet/roslyn/pull/44025#discussion_r441923177) [](ancestors = 441923177,441903992,441902428)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/CSharpResources.resx:3374]: Please add a test for that scenario with a different order of methods in base.

---
In reply to: [441960774](https://github.com/dotnet/roslyn/pull/44025#discussion_r441960774) [](ancestors = 441960774,441923177,441903992,441902428)

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs [hunk 32]
```diff
@@ -1220,41 +1226,48 @@ public override ImmutableArray<MethodSymbol> ExplicitInterfaceImplementations
...
+                        hasUniqueClassOverride = true;
+                        Interlocked.CompareExchange(ref AccessUncommonFields()._lazyExplicitClassOverride, uniqueClassOverride, null);
+                    }
                 }
 
+                // CONSIDER: what we'd really like to do is set this bit only in cases where the explicitly
+                // overridden method matches the method that will be returned by MethodSymbol.OverriddenMethod.
+                // Unfortunately, this MethodSymbol will not be sufficiently constructed (need IsOverride and MethodKind,
+                // which depend on this property) to determine which method OverriddenMethod will return.
+                _packedFlags.InitializeIsExplicitOverride(isExplicitFinalizerOverride: sawObjectFinalize, isExplicitClassOverride: hasUniqueClassOverride);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs:1257]: >hasUniqueClassOverride [](start = 131, length = 22)

It looks like there  is a behavior change here, which is going to affect the value returned by IsExplicitClassOverride property. Could you please elaborate why is this necessary with respect to existing usage of this property and point me to the tests that observe and justify the behavior change around existing usage of the property.

File: src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingPropertySymbol.cs (hunk 8 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingPropertySymbol.cs:197]: > No, this is intended and necessary for correctness. Most of the tests would break if changed as suggested. Having said that, this method is removed later in this PR.

The method is still present in the last iteration (iteration 30)


---
In reply to: [425945737](https://github.com/dotnet/roslyn/pull/44025#discussion_r425945737) [](ancestors = 425945737,424665880)

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberMethodSymbol.cs [hunk 33]
```diff
@@ -874,6 +874,14 @@ internal override void AddSynthesizedAttributes(PEModuleBuilder moduleBuilder, r
                 AddSynthesizedAttribute(ref attributes, moduleBuilder.SynthesizeNullableContextAttribute(this, nullableContextValue));
             }
 
+            bool isCovariantOverride = this.IsOverride && !this.OverriddenMethod.ReturnType.Equals(this.ReturnType, TypeCompareKind.AllIgnoreOptions);
+            if (isCovariantOverride)
+            {
+                // If present, we add PreserveBaseOverridesAttribute to covariant overrides.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberMethodSymbol.cs:880]: >If present, [](start = 19, length = 11)

Why if present? Isn't this attribute required to enforce proper behavior at runtime?

File: src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingMethodSymbol.cs (hunk 30 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingMethodSymbol.cs:291]: After reviewing more code I think we should call this method ExplicitlyOverriddenClassMethod (as in PEMethodSymbol) and implement it accordingly.

---
In reply to: [441959797](https://github.com/dotnet/roslyn/pull/44025#discussion_r441959797) [](ancestors = 441959797,441921131,441898873,441896761,441831407)

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs [hunk 34]
```diff
@@ -131,11 +132,13 @@ private static OverriddenOrHiddenMembersResult MakeOverriddenOrHiddenMembersWork
...
-            Symbol explicitOverride = member switch
+            // A specific override exact match candidate, if one is known. This supports covariant returns, for which signature
+            // matching is not sufficient. This member is treated as being as good as an exact match.
+            Symbol knownOverriddenMember = member switch
             {
-                PEMethodSymbol method => method.ExplicitlyOverriddenClassMethod,
-                PEPropertySymbol property => property.ExplicitlyOverriddenClassProperty,
+                MethodSymbol method => KnownOverriddenClassMethod(method),
+                PEPropertySymbol { GetMethod: PEMethodSymbol { ExplicitlyOverriddenClassMethod: { AssociatedSymbol: PropertySymbol overriddenProperty } } } => overriddenProperty,
+                RetargetingPropertySymbol property => property.RetargetOverriddenProperty,
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:141]: >property.RetargetOverriddenProperty [](start = 54, length = 35)

It feels like the logic here should be the same as for PEPropertySymbol above, I.e. infer from the getter

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberMethodSymbol.cs (hunk 33 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberMethodSymbol.cs:880]: Yes, indeed it is. How to deal with this is tracked by [https://github.com/dotnet/roslyn/issues/44208](https://github.com/dotnet/roslyn/issues/44208)

---
In reply to: [441984151](https://github.com/dotnet/roslyn/pull/44025#discussion_r441984151) [](ancestors = 441984151)

File: src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs (hunk 32 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs:1257]: If by "existing usages" you mean prior to the addition of the covariant returns feature, the only usage is in `PEMethodSymbol.IsOverride`. This scenario only arises from metadata that doesn't have a mapping to C#. In such cases of metadata that doesn't map to the language we have the freedom to decide how to map it to the language APIs. We previously ignored the overrides in PE when deciding what (if any) to report as the overridden method. As a consequence there could have been a mismatch between `IsOverride` and `OverriddenMember` (true and null). Now we do not treat it as an override of any particular at all (except by the usual rules in the absence of the .override) if there is no unique override, these two properties align, and we do pay attention to the override in metadata if it is unique. The behavior is tested in `PEMethodSymbol_ExplicitlyOverriddenClassMethod_WhenAmbiguous` among other places.

If and when we decide to support methods that have more than one language override, we will have to change a number of things, including changing "overridden symbol" to "overridden symbolS" (i.e. make it plural). There is no reason to do that today as such scenarios do not map to the language.

---
In reply to: [441975630](https://github.com/dotnet/roslyn/pull/44025#discussion_r441975630) [](ancestors = 441975630)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs:1257]: I think this behavior change should be reverted. I believe it is not related to the feature and unnecessary. I will not sign off like that. If you want to make a change like that, follow the standard route: open an issue, describe what the problem is, get support of the team, etc.

---
In reply to: [442308377](https://github.com/dotnet/roslyn/pull/44025#discussion_r442308377) [](ancestors = 442308377,441975630)

Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/Metadata/PE/PEMethodSymbol.cs:1257]: I will revert the behavior change to the method `IsOverride` and leave the API's inconsistent results to be dealt with at some future time.

---
In reply to: [442323736](https://github.com/dotnet/roslyn/pull/44025#discussion_r442323736) [](ancestors = 442323736,442308377,441975630)

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs (hunk 34 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:141]: If you have a valid retargeting scenario in mind for which this intermediate value results in incorrect compiler behavior, please identify that scenario. Otherwise I prefer it this way.

---
In reply to: [441992380](https://github.com/dotnet/roslyn/pull/44025#discussion_r441992380) [](ancestors = 441992380)

File: src/Compilers/Core/Portable/WellKnownTypes.cs [hunk 35]
```diff
@@ -619,6 +620,7 @@ internal static class WellKnownTypes
             "System.Runtime.CompilerServices.NativeIntegerAttribute",
             "System.Runtime.CompilerServices.IsExternalInit",
             "System.Runtime.InteropServices.OutAttribute",
+            "System.Runtime.CompilerServices.PreserveBaseOverridesAttribute",
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/WellKnownTypes.cs:623]: >"System.Runtime.CompilerServices.PreserveBaseOverridesAttribute" [](start = 12, length = 64)

I think we should limit lookup of this attribute to the core library, therefore, should move it to the set of SpecialTypes.

File: src/Compilers/Core/Portable/WellKnownMember.cs [hunk 36]
```diff
@@ -508,6 +508,8 @@ internal enum WellKnownMember
         System_Runtime_CompilerServices_NativeIntegerAttribute__ctor,
         System_Runtime_CompilerServices_NativeIntegerAttribute__ctorTransformFlags,
 
+        System_Runtime_CompilerServices_PreserveBaseOverridesAttribute__ctor,
```
Comment (AlekseyTs) [inline src/Compilers/Core/Portable/WellKnownMember.cs:511]: >System_Runtime_CompilerServices_PreserveBaseOverridesAttribute__ctor [](start = 8, length = 68)

Similarly to the type, I think this should be a special member.

Comment (gafter) [reply src/Compilers/Core/Portable/WellKnownMember.cs:511]: Recorded in [https://github.com/dotnet/roslyn/issues/44208](https://github.com/dotnet/roslyn/issues/44208)

---
In reply to: [442335918](https://github.com/dotnet/roslyn/pull/44025#discussion_r442335918) [](ancestors = 442335918)

File: src/Compilers/Core/Portable/WellKnownTypes.cs (hunk 35 above)
Comment (gafter) [reply src/Compilers/Core/Portable/WellKnownTypes.cs:623]: Recorded in [https://github.com/dotnet/roslyn/issues/44208](https://github.com/dotnet/roslyn/issues/44208).

---
In reply to: [442335393](https://github.com/dotnet/roslyn/pull/44025#discussion_r442335393) [](ancestors = 442335393)

File: src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingPropertySymbol.cs (hunk 8 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/Retargeting/RetargetingPropertySymbol.cs:197]: The virtual method that was present in iteration 13 no longer exists as a virtual method. This method replaces the override. The implementation is as intended.

---
In reply to: [441976888](https://github.com/dotnet/roslyn/pull/44025#discussion_r441976888) [](ancestors = 441976888,425945737,424665880)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs [hunk 37]
```diff
@@ -1155,11 +1160,17 @@ public static void Main()
...
+            // override that forces the runtime to agree with the compile-time override behavior.  It is therefore no
+            // longer ambiguous from the runtime's perspective.  The output of this test is therefore correct from a
+            // language perspective and there is no ambiguity.
             var comp = CompileAndVerify(source, expectedOutput: @"
+Base.Method(out, ref)
 Derived.Method(ref, out)
-Base.Method(ref, out)
-Base.Method(ref)");
+Derived.Method(ref)
+Base2.Method(out)");
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs:1171]: >"); [](start = 17, length = 3)

Minor suggestion: consider putting ```");``` on the next line. This way changes in the base-line will be easier to review in the future.

**Comment by AlekseyTs** [comment]
>     public virtual void Method(out List<U> y, ref List<T> x) { Console.WriteLine(""Base.Method(out, ref)""); y = null; }

Please add a test that flips the order of declaration for the first two methods.

---
Refers to: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs:1129 in db2f370. [](commit_id = db2f370cda5b72479024672f9801510a7d620a4a, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>     public virtual void Method(ref List<U> x) { Console.WriteLine(""Base.Method(ref)""); }

Please add a test where this is ```out``` and the parameter in Base2.Method is ```ref```. Could be combined with the test requested above.

---
Refers to: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs:1130 in db2f370. [](commit_id = db2f370cda5b72479024672f9801510a7d620a4a, deletion_comment = False)

File: src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs [hunk 38]
```diff
@@ -139,10 +139,7 @@ public class Derived2 : Derived<int>
             comp.VerifyDiagnostics(
                 // (4,26): error CS0462: The inherited members 'Derived<TInt>.Method(long, TInt)' and 'Derived<TInt>.Method(long, int)' have the same signature in type 'Derived2', so they cannot be overridden
                 //     public override void Method(long l, int i) { }  //CS0462 and CS1957
-                Diagnostic(ErrorCode.ERR_AmbigOverride, "Method").WithArguments("Derived<TInt>.Method(long, TInt)", "Derived<TInt>.Method(long, int)", "Derived2").WithLocation(4, 26),
-                // (4,26): warning CS1957: Member 'Derived2.Method(long, int)' overrides 'Derived<int>.Method(long, int)'. There are multiple override candidates at run-time. It is implementation dependent which method will be called.
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs:143]: >// (4,26): warning CS1957: Member 'Derived2.Method(long, int)' overrides 'Derived<int>.Method(long, int)'. There are multiple override candidates at run-time. It is implementation dependent which method will be called. [](start = 16, length = 218)

In order to confirm that there is indeed no problem now, we should test runtime behavior. Including scenario when the order of virtual methods declared in the ```Base``` is different.

File: src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs [hunk 39]
```diff
@@ -188,15 +185,9 @@ public override void Method(int a, long b)
                 // (12,26): error CS0462: The inherited members 'Base<T, U>.Method(T)' and 'Base<T, U>.Method(int)' have the same signature in type 'Derived', so they cannot be overridden
                 //     public override void Method(int a)
                 Diagnostic(ErrorCode.ERR_AmbigOverride, "Method").WithArguments("Base<T, U>.Method(T)", "Base<T, U>.Method(int)", "Derived"),
-                // (4,25): warning CS1957: Member 'Derived.Method(int)' overrides 'Base<int, int>.Method(int)'. There are multiple override candidates at run-time. It is implementation dependent which method will be called.
-                //     public virtual void Method(T x) { }
-                Diagnostic(ErrorCode.WRN_MultipleRuntimeOverrideMatches, "Method").WithArguments("Base<int, int>.Method(int)", "Derived.Method(int)"),
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs:193]: >Diagnostic(ErrorCode.WRN_MultipleRuntimeOverrideMatches, "Method").WithArguments("Base<int, int>.Method(int)", "Derived.Method(int)"), [](start = 16, length = 134)

Same comment as for other tests affected by the removal of WRN_MultipleRuntimeOverrideMatches

File: src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs [hunk 40]
```diff
@@ -227,13 +219,12 @@ class Base2<A, B> : Base<A, B>
...
 {
-    public override void Method(ref List<int> a, out List<int> b) { b = null; } // Reports warning about runtime ambiguity
+    public override void Method(ref List<int> a, out List<int> b) { b = null; } // No warning - the compiler produces a methodimpl record to disambiguate
     public override void Method(ref List<int> a) { } // No warning when ambiguous signatures are spread across multiple base types
 }";
 
             CreateCompilation(source).VerifyDiagnostics(
-                // (5,25): warning CS1957: Member 'Derived.Method(ref System.Collections.Generic.List<int>, out System.Collections.Generic.List<int>)' overrides 'Base<int, int>.Method(ref System.Collections.Generic.List<int>, out System.Collections.Generic.List<int>)'. There are multiple override candidates at run-time. It is implementation dependent which method will be called.
-                Diagnostic(ErrorCode.WRN_MultipleRuntimeOverrideMatches, "Method").WithArguments("Base<int, int>.Method(ref System.Collections.Generic.List<int>, out System.Collections.Generic.List<int>)", "Derived.Method(ref System.Collections.Generic.List<int>, out System.Collections.Generic.List<int>)"));
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs:236]: >WRN_MultipleRuntimeOverrideMatches [](start = 37, length = 34)

Same comment as for the other tests affected by the removal of WRN_MultipleRuntimeOverrideMatches

File: src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs [hunk 41]
```diff
@@ -4967,9 +4966,9 @@ class Derived : Base<int>
     public override void Method(int @in, ref int @ref) { }
 }
 ";
-            CompileAndVerifyDiagnostics(text, new ErrorDescription[] {
-                new ErrorDescription { Code = (int)ErrorCode.WRN_MultipleRuntimeOverrideMatches, Line = 5, Column = 25, IsWarning = true }, //C# can distinguish, but runtime can't
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs:4971]: >WRN_MultipleRuntimeOverrideMatches [](start = 61, length = 34)

Same comment as for the other tests affected by the removal of WRN_MultipleRuntimeOverrideMatches

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs [hunk 42]
```diff
@@ -18274,8 +18274,8 @@ class Derived : Base<string>
     public override void Test(string s, ref int x) { }
 }
 ";
-            var comp = DiagnosticsUtils.VerifyErrorsAndGetCompilationWithMscorlib(text,
-                new ErrorDescription { Code = (int)ErrorCode.WRN_MultipleRuntimeOverrideMatches, Line = 8, Column = 25, IsWarning = true });
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs:18278]: >WRN_MultipleRuntimeOverrideMatches [](start = 61, length = 34)

Same comment as for the other tests affected by the removal of WRN_MultipleRuntimeOverrideMatches

File: src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Source/OverridesTests.vb [hunk 43]
```diff
@@ -7214,5 +7214,173 @@ End Class
...
+            ' https://github.com/dotnet/roslyn/issues/44206: For testing purposes, we support a compiler "feature" flag that permits us to skip
+            ' the requirement for a runtime feature indicator. We should remove it once we have a runtime that
+            ' we can test against that actually supports the feature.
+            Dim cSharpParseOptions = CSharp.CSharpParseOptions.Default.WithLanguageVersion(CSharp.LanguageVersion.Preview).WithFeatures({New KeyValuePair(Of String, String)("DoNotRequireRuntimeCovariantReturnsSupport", "true")})
+            Dim cSharpCompilation = CreateCSharpCompilation(csSource, cSharpParseOptions)
+            Dim reference As MetadataReference = cSharpCompilation.EmitToImageReference
+            Dim references = cSharpCompilation.References.Append(reference)
+
+            Dim compilation = CreateEmptyCompilationWithReferences(vbSource, references, TestOptions.ReleaseDll)
+            compilation.AssertTheseDiagnostics(<expected>
```
Comment (AlekseyTs) [inline src/Compilers/VisualBasic/Test/Symbol/SymbolsTests/Source/OverridesTests.vb:7339]: >AssertTheseDiagnostics [](start = 24, length = 22)

Consider using ```AssertNoDiagnostics``` helper.

File: src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs [hunk 44]
```diff
@@ -212,28 +203,92 @@ public void TestAmbiguousOverridesRefOut()
...
+Base2<A, B>.Method(out List<A> x)
+
+Derived.Method(ref List<int> a, out List<int> b)
+Base<T, U>.Method(out List<U> y, ref List<T> x)
+Derived.Method(ref List<int> a)";
+            for (int i = 0; i < 2; i++)
+            {
+                if (i == 1)
+                {
+                    // This case is not working due to https://github.com/dotnet/runtime/issues/38119
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs:281]: >// This case is not working due to https://github.com/dotnet/runtime/issues/38119 [](start = 20, length = 81)

Based on that please revert removal of the ambiguity warning. We can revisit its removal once, if runtime behavior is fixed. Which likely never for desktop.

**Comment by gafter** [comment]
>     public virtual void Method(out List<U> y, ref List<T> x) { Console.WriteLine(""Base.Method(out, ref)""); y = null; }

Such a test is in `AmbiguousOverrideTests.cs` and called `TestAmbiguousOverridesRefOut`. I will delete it there and move it to replace this test. However, there is a runtime bug causing it to fail, so part of it is skipped; see [https://github.com/dotnet/runtime/issues/38119](https://github.com/dotnet/runtime/issues/38119)

---
In reply to: [646294931](https://github.com/dotnet/roslyn/pull/44025#issuecomment-646294931) [](ancestors = 646294931)

---
Refers to: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs:1129 in db2f370. [](commit_id = db2f370cda5b72479024672f9801510a7d620a4a, deletion_comment = False)

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 31)

File: src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs (hunk 44 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs:281]: The semantics of compilation is targeting core clr. The runtime will have to be fixed for the covariant return feature to work properly.

---
In reply to: [442540260](https://github.com/dotnet/roslyn/pull/44025#discussion_r442540260) [](ancestors = 442540260)

File: src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs (hunk 38 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs:143]: That is tested in `TestAmbiguousOverridesRefOut` in `CodeGenOverridingAndHiding`.

---
In reply to: [442518510](https://github.com/dotnet/roslyn/pull/44025#discussion_r442518510) [](ancestors = 442518510)

File: src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs (hunk 39 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs:193]: There is no runtime behavior for a program that does not compile.

---
In reply to: [442519006](https://github.com/dotnet/roslyn/pull/44025#discussion_r442519006) [](ancestors = 442519006)

File: src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs (hunk 40 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs:236]: That is tested in `CodeGenOverridingAndHiding`.

---
In reply to: [442519288](https://github.com/dotnet/roslyn/pull/44025#discussion_r442519288) [](ancestors = 442519288)

File: src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs (hunk 42 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Symbol/Symbols/SymbolErrorTests.cs:18278]: That is tested in `CodeGenOverridingAndHiding`.

---
In reply to: [442522720](https://github.com/dotnet/roslyn/pull/44025#discussion_r442522720) [](ancestors = 442522720)

File: src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs (hunk 41 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs:4971]: That is tested in `CodeGenOverridingAndHiding`.

---
In reply to: [442521581](https://github.com/dotnet/roslyn/pull/44025#discussion_r442521581) [](ancestors = 442521581)

**Comment by gafter** [comment]
@AlekseyTs I believe I have responded to all of your comments. If you still think we should warn for the runtime bug [https://github.com/dotnet/runtime/issues/38119](https://github.com/dotnet/runtime/issues/38119), I will reword the warning to clearly indicate the runtime bug and suggest upgrading to .net core 5 (in which it will need to be fixed for covariant returns).

**Comment by AlekseyTs** [comment]
> If you still think we should warn for the runtime bug dotnet/runtime#38119, I will reword the warning to clearly indicate the runtime bug and suggest upgrading to .net core 5 (in which it will need to be fixed for covariant returns).

I still think the change should be reverted without any promises about .net core 5 and we shouldn't be referencing any specific releases in the messages. I am not at all optimistic about this issue being fixed in this time frame and I do not believe that the covariant return feature makes behavior significantly worse than it has been for years. 

I consider this issue a blocker for this PR. If and when the runtime is fixed, we will follow up as appropriate. There is an issue tracking that.

File: docs/compilers/CSharp/Compiler Breaking Changes - DotNet 5.md [hunk 45]
```diff
@@ -58,3 +58,11 @@
             o is sbyte or short or int or long;
     ```
     Because the `and` and `or` combinators can follow a type pattern, the compiler interprets them as part of the pattern combinator rather than an identifier for the declaration pattern. Consequently, it is an error to use `or` or `and` as pattern variable identifiers starting with C# 9.0.
+
+4. The fix for https://github.com/dotnet/roslyn/issues/44067 generates correct (different) code.
+   In certain cases the compiler used to generate code whose behavior was ambiguous according
+   to the CLR's specification. The compiler used to produce the warning CS1957 in those cases.
+   The compiler now generates correct unambiguous code rather than reporting CS1957. Because
+   it is possible that the runtime behavior of a program will change due to the change in our code
+   generation strategy, this could be a breaking change. If your program did not elicit the warning
```
Comment (AlekseyTs) [inline docs/compilers/CSharp/Compiler Breaking Changes - DotNet 5.md:67]: >this could be a breaking change [](start = 24, length = 31)

I guess, given the current CLR behavior, the code could switch from overriding the right method to overriding the wrong method at runtime.

File: docs/compilers/CSharp/Compiler Breaking Changes - DotNet 5.md [hunk 46]
```diff
@@ -58,3 +58,11 @@
             o is sbyte or short or int or long;
     ```
     Because the `and` and `or` combinators can follow a type pattern, the compiler interprets them as part of the pattern combinator rather than an identifier for the declaration pattern. Consequently, it is an error to use `or` or `and` as pattern variable identifiers starting with C# 9.0.
+
+4. The fix for https://github.com/dotnet/roslyn/issues/44067 generates correct (different) code.
+   In certain cases the compiler used to generate code whose behavior was ambiguous according
+   to the CLR's specification. The compiler used to produce the warning CS1957 in those cases.
```
Comment (AlekseyTs) [inline docs/compilers/CSharp/Compiler Breaking Changes - DotNet 5.md:64]: >The compiler used to produce the warning CS1957 in those cases. [](start = 31, length = 63)

This statement probably should be adjusted once the change around warming reporting is reverted.

File: docs/compilers/CSharp/Compiler Breaking Changes - DotNet 5.md [hunk 47]
```diff
@@ -58,3 +58,11 @@
             o is sbyte or short or int or long;
     ```
     Because the `and` and `or` combinators can follow a type pattern, the compiler interprets them as part of the pattern combinator rather than an identifier for the declaration pattern. Consequently, it is an error to use `or` or `and` as pattern variable identifiers starting with C# 9.0.
+
+4. The fix for https://github.com/dotnet/roslyn/issues/44067 generates correct (different) code.
```
Comment (AlekseyTs) [inline docs/compilers/CSharp/Compiler Breaking Changes - DotNet 5.md:62]: >generates correct (different) code. [](start = 61, length = 35)

Did we get compatibility council approval for this behavior change in the compiler? If not, I don't think it is blocking this PR, but we should follow up.

File: docs/compilers/CSharp/Compiler Breaking Changes - DotNet 5.md (hunk 45 above)
Comment (gafter) [reply docs/compilers/CSharp/Compiler Breaking Changes - DotNet 5.md:67]: > I guess, given the current CLR behavior, the code could switch from overriding the right method to overriding the wrong method at runtime.

I don't think we've characterized the bug sufficiently well to conclude that can happen.

Comment (AlekseyTs) [reply docs/compilers/CSharp/Compiler Breaking Changes - DotNet 5.md:67]: > I don't think we've characterized the bug sufficiently well to conclude that can happen.

I think we can conclude that from the tests that you added/modified. Or at least try to do that. If behavior was order dependent without an explicit override and explicit override changes it and also order dependent, then it is possible that things just might become worse, until proven otherwise. If we cannot prove otherwise, we should assume worse for the purpose of determining impact of the behavior change.

---
In reply to: [442936553](https://github.com/dotnet/roslyn/pull/44025#discussion_r442936553) [](ancestors = 442936553)

File: docs/compilers/CSharp/Compiler Breaking Changes - DotNet 5.md (hunk 47 above)
Comment (gafter) [reply docs/compilers/CSharp/Compiler Breaking Changes - DotNet 5.md:62]: The compat council has the issue on their plate.

Comment (AlekseyTs) [reply docs/compilers/CSharp/Compiler Breaking Changes - DotNet 5.md:62]: > The compat council has the issue on their plate.

Please send me an invite for the discussion. 

---
In reply to: [442950442](https://github.com/dotnet/roslyn/pull/44025#discussion_r442950442) [](ancestors = 442950442)

Comment (gafter) [reply docs/compilers/CSharp/Compiler Breaking Changes - DotNet 5.md:62]: This is being tracked by [https://github.com/dotnet/roslyn/issues/45453](https://github.com/dotnet/roslyn/issues/45453)

---
In reply to: [443144872](https://github.com/dotnet/roslyn/pull/44025#discussion_r443144872) [](ancestors = 443144872,442950442)

File: src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs (hunk 44 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs]: This is being tracked by [https://github.com/dotnet/roslyn/issues/45453](https://github.com/dotnet/roslyn/issues/45453)

---
In reply to: [442546841](https://github.com/dotnet/roslyn/pull/44025#discussion_r442546841) [](ancestors = 442546841,442540260)

**Comment by gafter** [comment]
This is being tracked by [https://github.com/dotnet/roslyn/issues/45453](https://github.com/dotnet/roslyn/issues/45453) to unblock the PR.

---
In reply to: [646373139](https://github.com/dotnet/roslyn/pull/44025#issuecomment-646373139) [](ancestors = 646373139)

**Comment by gafter** [comment]
@AlekseyTs Your remaining issue is tracked by https://github.com/dotnet/roslyn/issues/45453. Do you have any other comments?

**Comment by AlekseyTs** [comment]
> Do you have any other comments?

Yes, the warning should be put back. All changes around it should be postponed until/if we have a runtime to test against.

**Comment by gafter** [comment]
We have a separate issue tracking what should be done about that. This is not targeting master, it is targeting a feature branch that will not be integrated until we have runtime support.

Do you have any other issues?

---
In reply to: [649681504](https://github.com/dotnet/roslyn/pull/44025#issuecomment-649681504) [](ancestors = 649681504)

**Comment by AlekseyTs** [comment]
The current change in behavior around the warning is not warranted and is not supported by runtime behavior. The issue tracks the future work around the warning and is predicated on the runtime work. That work might or might not happen.

**Comment by AlekseyTs** [comment]
I prefer to review that there is no code and behavior changes around that right now, then to deal with possible restoration and making sure it is done properly in the future.

**Comment by AlekseyTs** [comment]
Especially that, apparently, we just decided to keep the warning, at least in some scenarios. So, removing it right now doesn't make any sense, in my opinion.

**Comment by jaredpar** [comment]
I don't think we should block this on the warning. There is an issue tracking and if the decision is to restore then @gafter is essentially on the hook for adding it back in. 

> The issue tracks the future work around the warning and is predicated on the runtime work. That work might or might not happen.

The runtime team has indicated, at least to my reading, that they will implement this behavior if we request it.

**Comment by gafter** [comment]
@davidwrighton has been working on fixing the runtime bug this week

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs [hunk 48]
```diff
@@ -165,6 +168,18 @@ private static OverriddenOrHiddenMembersResult MakeOverriddenOrHiddenMembersWork
             return OverriddenOrHiddenMembersResult.Create(overriddenMembers, hiddenMembers, runtimeOverriddenMembers);
         }
 
+        /// <summary>
+        /// Compute a candidate overridden method when a method knows what method it is intended to
+        /// override. This makes a particular difference when covariant returns are used, in which
+        /// case the signature matching rules would not compute the correct overridden method.
+        /// </summary>
+        private static MethodSymbol KnownOverriddenClassMethod(MethodSymbol method) => method switch
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:176]: Nit: I'd prefer this to be on the next line and indented.

Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:176]: Are you suggesting a newline after the arrow?

---
In reply to: [445847240](https://github.com/dotnet/roslyn/pull/44025#discussion_r445847240) [](ancestors = 445847240)

Comment (333fred) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:176]: I find it looks best with the arrow on the next line entirely, but after the arrow would also work. The way it's formatted right now, though, the switch cases braces look like a method body to a quick scan.

---
In reply to: [445849322](https://github.com/dotnet/roslyn/pull/44025#discussion_r445849322) [](ancestors = 445849322,445847240)

**Comment by gafter** [comment]
I think the most recent commit addresses all comments. Would you please have another look?

**Comment by AlekseyTs** [comment]
> I think the most recent commit addresses all comments. Would you please have another look?

Will take a look tomorrow morning

**Comment by AlekseyTs** [comment]
>             // overrides, which typically arise through combinations of ref/out and generics.)  In incorrect code,

Might want to preserve this part to allow readers to get an idea about the scenario without having to go to some web site.

---
Refers to: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:122 in 8f4771f. [](commit_id = 8f4771f15c66846cd2c92c2a365b10ea54601d43, deletion_comment = True)

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs [hunk 49]
```diff
@@ -930,33 +945,38 @@ internal static bool RequiresExplicitOverride(this MethodSymbol method)
...
-                // TODO: do we want to add more sophisticated handling for the case where there are multiple runtime-overridden methods?
-                MethodSymbol runtimeOverriddenMethod = method.GetFirstRuntimeOverriddenMethodIgnoringNewSlot(ignoreInterfaceImplementationChanges: true);
-                return runtimeOverriddenMethod is null ||
-                    csharpOverriddenMethod != runtimeOverriddenMethod &&
-                    method.IsAccessor() != runtimeOverriddenMethod.IsAccessor();
+                MethodSymbol runtimeOverriddenMethod = method.GetFirstRuntimeOverriddenMethodIgnoringNewSlot(out bool wasAmbiguous);
+                return wasAmbiguous
+                    // See https://github.com/dotnet/roslyn/issues/45453
+                    ? method.ContainingAssembly.RuntimeSupportsCovariantReturnsOfClasses
+                    : csharpOverriddenMethod != runtimeOverriddenMethod;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:954]: >csharpOverriddenMethod != runtimeOverriddenMethod [](start = 22, length = 49)

Should we always return true if this condition is met and look at ambiguity otherwise?

**Comment by davidwrighton** [comment]
The runtime bug (dotnet/runtime#38119) fix was checked in a few minutes ago. (dotnet/runtime#38310)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs [hunk 50]
```diff
@@ -1112,54 +1112,156 @@ public static void Main()
...
+                    string subst(string s) => j switch
+                    {
+                        0 => s.Replace("BASEREF", "ref").Replace("BASE2REF", "out"),
+                        _ => s.Replace("BASEREF", "out").Replace("BASE2REF", "ref"),
+                    };
+
+                    var substitutedSource = subst(substitutedSource0);
+                    var compilation = CreateCompilation(substitutedSource, options: TestOptions.ReleaseExe);
+                    string expectedOutput;
+                    if (compilation.Assembly.RuntimeSupportsCovariantReturnsOfClasses)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs:1193]: >if (compilation.Assembly.RuntimeSupportsCovariantReturnsOfClasses) [](start = 20, length = 66)

Once we have a fixed runtime available, I think it would be good to add an unconditional test against that runtime to verify expected behavior. Consider capturing this in the issue.

File: src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs [hunk 51]
```diff
@@ -136,13 +137,25 @@ public class Derived2 : Derived<int>
...
+                    );
+            }
+            else
+            {
+                comp.VerifyDiagnostics(
+                    // (4,26): error CS0462: The inherited members 'Derived<TInt>.Method(long, TInt)' and 'Derived<TInt>.Method(long, int)' have the same signature in type 'Derived2', so they cannot be overridden
+                    //     public override void Method(long l, int i) { }  //CS0462 and CS1957
+                    Diagnostic(ErrorCode.ERR_AmbigOverride, "Method").WithArguments("Derived<TInt>.Method(long, TInt)", "Derived<TInt>.Method(long, int)", "Derived2").WithLocation(4, 26),
+                    // (4,26): warning CS1957: Member 'Derived2.Method(long, int)' overrides 'Derived<int>.Method(long, int)'. There are multiple override candidates at run-time. It is implementation dependent which method will be called. Please use a newer runtime.
+                    //     public override void Method(long l, TInt i) { }
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs:155]: >//     public override void Method(long l, TInt i) { } [](start = 20, length = 54)

It looks like a warning from a different compilation made its way into diagnostics. Any idea how did this happen?

File: src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs [hunk 52]
```diff
@@ -5,6 +5,7 @@
 using System;
 using System.Collections.Generic;
 using System.Linq;
+using ICSharpCode.Decompiler.IL;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs:8]: Why do we need this?

File: src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs [hunk 53]
```diff
@@ -4771,11 +4771,20 @@ public class Derived : Base<int>, Interface<int, int>
...
 ";
-            CompileAndVerifyDiagnostics(text, new ErrorDescription[] {
-                new ErrorDescription { Code = (int)ErrorCode.WRN_MultipleRuntimeImplementationMatches, Line = 15, Column = 35, IsWarning = true }, //Both Base methods implement Interface.Method(int)
-                new ErrorDescription { Code = (int)ErrorCode.WRN_MultipleRuntimeImplementationMatches, Line = 15, Column = 35, IsWarning = true }, //Both Base methods implement Interface.Method(T)
-                new ErrorDescription { Code = (int)ErrorCode.WRN_MultipleRuntimeImplementationMatches, Line = 15, Column = 35, IsWarning = true }, //Both Base methods implement Interface.Method(U)
-            });
+            //Both Base methods implement Interface.Method(int)
+            //Both Base methods implement Interface.Method(T)
+            //Both Base methods implement Interface.Method(U)
+            CreateCompilation(text).VerifyDiagnostics(
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs:4777]: >VerifyDiagnostics [](start = 36, length = 17)

Is this test going to break once we start testing against new core CLR? Consider adding a comment with a hint to split the test to explicitly target Core CLR and other frameworks once that happens.

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs (hunk 49 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:954]: If the suggestion would lead to an incorrect behavior, it would be good to back the fact with a test demonstrating the fact.

---
In reply to: [446321935](https://github.com/dotnet/roslyn/pull/44025#discussion_r446321935) [](ancestors = 446321935)

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 33)

**Comment by gafter** [comment]
>             // overrides, which typically arise through combinations of ref/out and generics.)  In incorrect code,

Given that the latest version of the language won't have this problem, documenting it in detail inline seems counterproductive. I think the link is sufficient.

---
In reply to: [650306747](https://github.com/dotnet/roslyn/pull/44025#issuecomment-650306747) [](ancestors = 650306747)

---
Refers to: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:122 in 8f4771f. [](commit_id = 8f4771f15c66846cd2c92c2a365b10ea54601d43, deletion_comment = True)

File: src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs (hunk 53 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs:4777]: No, the changes in this PR have no effect on this test at compile-time or runtime. I just used newer APIs in the test to make it easier to understand.

---
In reply to: [446344222](https://github.com/dotnet/roslyn/pull/44025#discussion_r446344222) [](ancestors = 446344222)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs:4777]: > No, the changes in this PR have no effect on this test at compile-time or runtime. I just used newer APIs in the test to make it easier to understand.

Are you saying that we will keep reporting the warnings even when the target runtime supports covariant returns?

---
In reply to: [446406777](https://github.com/dotnet/roslyn/pull/44025#discussion_r446406777) [](ancestors = 446406777,446344222)

File: src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs (hunk 51 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs:155]: This is correct. It is precisely the same diagnostic from before this PR.

---
In reply to: [446335378](https://github.com/dotnet/roslyn/pull/44025#discussion_r446335378) [](ancestors = 446335378)

File: src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs (hunk 53 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/InheritanceBindingTests.cs:4777]: Yes, these diagnostics have nothing much to do with the changes in this PR. These are ambiguities in implicit interface implementations, which we are not touching.

---
In reply to: [446407986](https://github.com/dotnet/roslyn/pull/44025#discussion_r446407986) [](ancestors = 446407986,446406777,446344222)

File: src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs (hunk 51 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs:155]: > This is correct. It is precisely the same diagnostic from before this PR.

Any idea how did this happen? 

---
In reply to: [446408459](https://github.com/dotnet/roslyn/pull/44025#discussion_r446408459) [](ancestors = 446408459,446335378)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs (hunk 50 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs:1193]: Recorded in [https://github.com/dotnet/roslyn/issues/43188](https://github.com/dotnet/roslyn/issues/43188) for you.

---
In reply to: [446331200](https://github.com/dotnet/roslyn/pull/44025#discussion_r446331200) [](ancestors = 446331200)

File: src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs (hunk 51 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs:155]: I'm not sure what you mean. You're wondering why we report the same diagnostics that we always did?

---
In reply to: [446411091](https://github.com/dotnet/roslyn/pull/44025#discussion_r446411091) [](ancestors = 446411091,446408459,446335378)

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs (hunk 49 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:954]: The test demonstrating that your suggestion would be incorrect is shown in [https://github.com/dotnet/runtime/issues/38119](https://github.com/dotnet/runtime/issues/38119) and, now that the runtime is fixed, is tested by the runtime team's unit tests.

I don't think it makes sense to add tests for a hypothetical buggy version of the compiler.

---
In reply to: [446358005](https://github.com/dotnet/roslyn/pull/44025#discussion_r446358005) [](ancestors = 446358005,446321935)

File: src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs (hunk 51 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs:155]: > I'm not sure what you mean. You're wondering why we report the same diagnostics that we always did?

Yes, I am wondering if you understand why was this happening. This is not a trick question.


---
In reply to: [446412205](https://github.com/dotnet/roslyn/pull/44025#discussion_r446412205) [](ancestors = 446412205,446411091,446408459,446335378)

Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs:154]: Yes, because we don't (and never did) suppress the warning in the face of this particular error.

---
In reply to: [446414161](https://github.com/dotnet/roslyn/pull/44025#discussion_r446414161) [](ancestors = 446414161,446412205,446411091,446408459,446335378)

**Comment by gafter** [comment]
@AlekseyTs I believe I've responded to all of your comments. Do you have any others?

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs (hunk 49 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:954]: > The test demonstrating that your suggestion would be incorrect is shown in [https://github.com/dotnet/runtime/issues/38119](https://github.com/dotnet/runtime/issues/38119) and, now that the runtime is fixed, is tested by the runtime team's unit tests.

Could you please elaborate what exactly would be wrong and how? 

> I don't think it makes sense to add tests for a hypothetical buggy version of the compiler.

It is always good to have test that prevents a regression in the future. Is there an existing test that would fail if the behavior of the function were to change as suggested? What would be the nature of the failure? 




---
In reply to: [446413877](https://github.com/dotnet/roslyn/pull/44025#discussion_r446413877) [](ancestors = 446413877,446358005,446321935)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs (hunk 50 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs:1193]: > Recorded in [https://github.com/dotnet/roslyn/issues/43188](https://github.com/dotnet/roslyn/issues/43188) for you.

I believe this test has nothing to do with covariant return scenario, and I am not asking to test that.

---
In reply to: [446411375](https://github.com/dotnet/roslyn/pull/44025#discussion_r446411375) [](ancestors = 446411375,446331200)

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs (hunk 49 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:954]: See `TestAmbiguousOverridesRefOut` in `CodeGenOverridingAndHiding` as changed in iteration 33. Depending on the order of the declarations, the override would change from being correct to incorrect or vice versa (both tested).

---
In reply to: [446416546](https://github.com/dotnet/roslyn/pull/44025#discussion_r446416546) [](ancestors = 446416546,446413877,446358005,446321935)

File: src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs (hunk 51 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs:154]: > Yes, because we don't (and never did) suppress the warning in the face of this particular error.

Let me rephrase the question. I am wondering if you understand why a warning about code in a different compilation and pointing at location in a different compilation is reported for this compilation.

---
In reply to: [446414685](https://github.com/dotnet/roslyn/pull/44025#discussion_r446414685) [](ancestors = 446414685,446414161,446412205,446411091,446408459,446335378)

Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/Semantics/AmbiguousOverrideTests.cs:154]: Because that is the way the diagnostic is produced in the compiler. I presume the intent was to produce the diagnostic where the user was most likely to be able to fix it (by renaming, for example). None of that has anything to do with any compiler changes in the present PR.

---
In reply to: [446419715](https://github.com/dotnet/roslyn/pull/44025#discussion_r446419715) [](ancestors = 446419715,446414685,446414161,446412205,446411091,446408459,446335378)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs (hunk 50 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs:1193]: The expected behavior for this scenario depends on a having the covariant-return supporting runtime where the necessary fix appears, which we do not yet have. For testing on existing runtimes, see line 1213.

---
In reply to: [446418074](https://github.com/dotnet/roslyn/pull/44025#discussion_r446418074) [](ancestors = 446418074,446411375,446331200)

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs (hunk 49 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:954]: > Adding the methodimpl entries changes what overridden method the runtime binds the override to. Since we want to remain compatible with previous behavior (right or wrong) for buggy runtimes, we do not want to change what we produce.

> See TestAmbiguousOverridesRefOut in CodeGenOverridingAndHiding as changed in iteration 33. Depending on the order of the declarations, the override would change from being correct to incorrect or vice versa (both tested).

I am just trying to understand why the code is written this way here. Could you, please, help me out with that?

At first, the logic feels wrong because we might not emit a MethodImpl for true covariant return case with ambiguous runtime override. However, one might argue that in the case when the runtime doesn't support covariant returns, we would report an error elsewhere and wouldn't even try to emit. Does this match the line of thinking you use? If so, consider capturing this in a comment.

On the other hand, could this negatively affect retargeting scenario when covariant returns involved? It looks like we would fail to communicate the presence of the covariant return override to the KnownOverriddenClassMethod above, potentially negatively affecting resolution of what the method overrides in that new universe. Is this possible? It might be worth adding some tests around this scenario. We might want to use a slightly different logic in this helper specifically for the purpose of RetargetingMethodSymbol.ExplicitlyOverriddenClassMethod.


---
In reply to: [446418702](https://github.com/dotnet/roslyn/pull/44025#discussion_r446418702) [](ancestors = 446418702,446416546,446413877,446358005,446321935)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs (hunk 50 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs:1193]: > The expected behavior for this scenario depends on a having the covariant-return supporting runtime where the necessary fix appears, which we do not yet have. For testing on existing runtimes, see line 1213.

That line tests conditionally. I am suggesting to add an unconditional test against core clr once the fix is going to be available to us.

---
In reply to: [446423506](https://github.com/dotnet/roslyn/pull/44025#discussion_r446423506) [](ancestors = 446423506,446418074,446411375,446331200)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs [hunk 54]
```diff
@@ -1112,54 +1112,156 @@ public static void Main()
...
+Base2<A, B>.Method(BASE2REF List<A> x)
+
+{m1}
+{m2}
+Derived.Method(BASEREF List<int> a)";
+                    }
+                    else
+                    {
+                        // unknown runtime behavior
+                        continue;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs:1256]: >continue; [](start = 24, length = 9)

Can't we test Mono behavior today?

Comment (jaredpar) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs:1256]: Not in our unit tests. There are some issues getting their runtime working in our repo. I will keep that in mind as I'm working to get dotnet5 inserted into our repo. Mono working again will be next on my list after that.

Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs:1256]: > Not in our unit tests. There are some issues getting their runtime working in our repo. I will keep that in mind as I'm working to get dotnet5 inserted into our repo. Mono working again will be next on my list after that. 

Perhaps it would make sense to make a note to come back to this place once that happens?

---
In reply to: [446446062](https://github.com/dotnet/roslyn/pull/44025#discussion_r446446062) [](ancestors = 446446062)

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs (hunk 49 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:954]: It looks like this helper also affects behavior of IsMetadataNewSlot API for source and retargeting scenario. Given all that, I would be more comfortable if the logic here was adjusted to accurately detect if we are dealing with covariant return situation and always return true for that case, regardless of  runtime capability, returning anything else feels incorrect for this scenario. For remaining cases, use logic based on the runtime capability. The current logic seems short and clever, but I am not comfortable with its possible inaccuracy in some scenarios. 

---
In reply to: [446444174](https://github.com/dotnet/roslyn/pull/44025#discussion_r446444174) [](ancestors = 446444174,446418702,446416546,446413877,446358005,446321935)

Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:954]: > I am just trying to understand why the code is written this way here. Could you, please, help me out with that?

The compat council's decision means that we do not emit methodimpl in the ambiguous scenarios unless supported by the runtime. That is the *true* branch of the conditional. The false branch of the conditional simply checks if the runtime's unambiguous override candidate is the same as the language one. Methodimpl works on all runtimes for that scenario as far as I know.

> At first, the logic feels wrong because we might not emit a MethodImpl for true covariant return case with ambiguous runtime override. 

We only support covariant returns when targeting a platform that supports covariant returns. I don't think that needs additional documentation.

> On the other hand, could this negatively affect retargeting scenario when covariant returns involved?

This code is only when emitting the source method, and for the metadata properties of a source method. I don't think it can affect the properties of a retargeting method (which mirror the same metadata properties that would arise on the underlying method if emitted).
I don't think we intend to support retargeting a method that uses covariant returns to a runtime that does not support them. I don't think any small adjustment here could make that work.


---
In reply to: [446444174](https://github.com/dotnet/roslyn/pull/44025#discussion_r446444174) [](ancestors = 446444174,446418702,446416546,446413877,446358005,446321935)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs (hunk 54 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs:1256]: In `ConditionalFactAttribute` we have
```csharp
        public static bool IsDesktop => RuntimeUtilities.IsDesktopRuntime;
        public static bool IsCoreClr => !IsDesktop;
```
So `mono` will be tested as a core clr runtime.

---
In reply to: [446445205](https://github.com/dotnet/roslyn/pull/44025#discussion_r446445205) [](ancestors = 446445205)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs (hunk 50 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs:1193]: An unconditional test would fail on desktop. It would also fail on coreclr3. In any case, the request is recorded in [https://github.com/dotnet/roslyn/issues/43188](https://github.com/dotnet/roslyn/issues/43188).

---
In reply to: [446445016](https://github.com/dotnet/roslyn/pull/44025#discussion_r446445016) [](ancestors = 446445016,446423506,446418074,446411375,446331200)

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs (hunk 49 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:954]: > The compat council's decision means that we do not emit methodimpl in the ambiguous scenarios unless supported by the runtime. That is the true branch of the conditional. The false branch of the conditional simply checks if the runtime's unambiguous override candidate is the same as the language one. Methodimpl works on all runtimes for that scenario as far as I know. 

That shouldn't affect the covariant return case because there is no prior behavior that we need to maintain and covariant returns always supposed to use MethodImpl. That is the design of the feature. Whether the runtime would understand it or not is orthogonal, in my opinion.

> This code is only used when emitting the source method

That is not the case, I just gave two examples. I would prefer us to implement the letter of the spec about covariant returns rather than hoping that this shortcut isn't going to have an adverse effect somewhere in the compiler today or in the future. 

> I don't think it can affect the properties of a retargeting method (which mirror the same metadata properties that would arise on the underlying method if emitted).

That would have to be proven by tests that observe that there is no behavior difference between source and retargeting references. Alternatively, we could align behavior of this method with Covariant Returns feature specification. I.e. This method should always return true for covariant return scenario, regardless of runtime capability. 

> I don't think any small adjustment here could make that work.

I am sorry, but I would have to disagree with that.

I can be convinced if you can come up with a test scenario that would demonstrate an incorrect behavior if the suggested changes were implemented.


---
In reply to: [446450749](https://github.com/dotnet/roslyn/pull/44025#discussion_r446450749) [](ancestors = 446450749,446444174,446418702,446416546,446413877,446358005,446321935)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs (hunk 50 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs:1193]: > An unconditional test would fail on desktop. It would also fail on coreclr3.

We are not testing against different flavors of Core CLR and I specifically asked for a test with runtime that includes the fix. We have capability to create targeted tests like that

---
In reply to: [446451821](https://github.com/dotnet/roslyn/pull/44025#discussion_r446451821) [](ancestors = 446451821,446445016,446423506,446418074,446411375,446331200)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs (hunk 54 above)
Comment (jaredpar) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs:1256]: Mono qualifies as a desktop runtime.

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs (hunk 49 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:954]: This code is not used for retargeting symbols. Retargeting symbols mirror the behavior of the PE symbols that would be generated for the underlying source symbols. Neither scenario "works" on platforms that do not support covariant returns.

> > This code is only used when emitting the source method

> That is not the case, I just gave two examples.

I don't know what examples you gave that suggests this code is used for anything other than a source symbol.

> > I don't think it can affect the properties of a retargeting method (which mirror the same metadata properties that would arise on the underlying method if emitted).

> That would have to be proven by tests that observe that there is no behavior difference between source and retargeting references. 

Retargeting symbols do not have any runtime behavior as they are compile-time artifacts.  Perhaps this code from `RetargetingMethodSymbol`'s base class should help:

```csharp
        internal override bool IsMetadataVirtual(bool ignoreInterfaceImplementationChanges = false)
        {
            return UnderlyingMethod.IsMetadataVirtual(ignoreInterfaceImplementationChanges);
        }

        internal override bool IsMetadataNewSlot(bool ignoreInterfaceImplementationChanges = false)
        {
            return UnderlyingMethod.IsMetadataNewSlot(ignoreInterfaceImplementationChanges);
        }
```

> I can be convinced if you can come up with a test scenario that would demonstrate an incorrect behavior if the suggested changes were implemented.

I have already done so. See TestAmbiguousOverridesRefOut in CodeGenOverridingAndHiding as changed in iteration 33. Depending on the order of the declarations, the override would change from being correct to incorrect or vice versa (both tested).

In any case, the compat council explicitly decided that we should not produce methodimpl entries for the ambiguous scenario on runtimes that are not known to have the fix to [https://github.com/dotnet/runtime/issues/38119](https://github.com/dotnet/runtime/issues/38119). The compat council's decision is documented in [https://github.com/dotnet/roslyn/issues/45453](https://github.com/dotnet/roslyn/issues/45453). I know you disagree with it, but it is simply not possible for me to implement your preferred approach and the compat council's decision at the same time, since they differ.


---
In reply to: [446453378](https://github.com/dotnet/roslyn/pull/44025#discussion_r446453378) [](ancestors = 446453378,446450749,446444174,446418702,446416546,446413877,446358005,446321935)

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs (hunk 54 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenOverridingAndHiding.cs:1256]: In any case, mono would be tested in the `(ExecutionConditionUtil.IsCoreClr || ExecutionConditionUtil.IsDesktop)` scenario of line 1213

---
In reply to: [446455428](https://github.com/dotnet/roslyn/pull/44025#discussion_r446455428) [](ancestors = 446455428)

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs (hunk 49 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:954]: > I can be convinced if you can come up with a test scenario that would demonstrate an incorrect behavior if the suggested changes were implemented.

If you mean to produce a methodimpl for covariant return scenarios when targeting runtimes that do not support covariant returns... that is simply invalid IL that doesn't obey the IL specification implemented by the runtime. Producing invalid IL is incorrect behavior.

---
In reply to: [446458615](https://github.com/dotnet/roslyn/pull/44025#discussion_r446458615) [](ancestors = 446458615,446453378,446450749,446444174,446418702,446416546,446413877,446358005,446321935)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:954]: > If you mean to produce a methodimpl for covariant return scenarios when targeting runtimes that do not support covariant returns... that is simply invalid IL that doesn't obey the IL specification implemented by the runtime. Producing invalid IL is incorrect behavior.


I mean, please, give me something concrete. A test that fails with suggested changes, for example. So far you gave me just claims and guesses, nothing of substance. Please, be very specific, what is the scenario, what is the nature of failure, why do you think it is a failure, etc.
The change I suggest to make - before the return add a logic to check if we are dealing with covariant return case (i.e. there is a mismatch in return type, etc.), return true if that is the case.


---
In reply to: [446461000](https://github.com/dotnet/roslyn/pull/44025#discussion_r446461000) [](ancestors = 446461000,446458615,446453378,446450749,446444174,446418702,446416546,446413877,446358005,446321935)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:954]: > See TestAmbiguousOverridesRefOut in CodeGenOverridingAndHiding as changed in iteration 33. Depending on the order of the declarations, the override would change from being correct to incorrect or vice versa (both tested).

Correct me if I am wrong, but I believe the test is not using covariant returns and, therefore, cannot be affected by suggested changes.

---
In reply to: [446463069](https://github.com/dotnet/roslyn/pull/44025#discussion_r446463069) [](ancestors = 446463069,446461000,446458615,446453378,446450749,446444174,446418702,446416546,446413877,446358005,446321935)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:954]: > The compat council explicitly decided that we should not produce methodimpl entries for the ambiguous scenario on runtimes that are not known to have the fix to [https://github.com/dotnet/runtime/issues/38119](https://github.com/dotnet/runtime/issues/38119). The compat council's decision is documented in [https://github.com/dotnet/roslyn/issues/45453](https://github.com/dotnet/roslyn/issues/45453).

This decision doesn't apply to covariant return case because there is no backward compatibility scenario that involves covariant returns feature, compat council makes decisions about compatibility scenarios. Covariant Returns is a new feature, we never emitted anything like that before, with or without an override. And, I am pretty sure that with suggested changes, we wouldn't emit a MethodImpl for covariant return case in case of the ambiguity if runtime doesn't have the fix. If you disagree, all you have to do to prove me wrong is to provide a concrete test case failing with suggested changes.  

---
In reply to: [446471373](https://github.com/dotnet/roslyn/pull/44025#discussion_r446471373) [](ancestors = 446471373,446463069,446461000,446458615,446453378,446450749,446444174,446418702,446416546,446413877,446358005,446321935)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:954]: > Perhaps this code from RetargetingMethodSymbol's base class should help:

Please take a look at this implementation of the API in SourceMemberMethodSymbol (note the use of this,  RequiresExplicitOverride, function):
```
        internal override bool IsMetadataNewSlot(bool ignoreInterfaceImplementationChanges = false)
        {
            if (IsExplicitInterfaceImplementation && _containingType.IsInterface)
            {
                // All implementations of methods from base interfaces should omit the newslot bit to ensure no new vtable slot is allocated.
                return false;
            }

            // If C# and the runtime don't agree on the overridden method,
            // then we will mark the method as newslot and specify the
            // override explicitly (see GetExplicitImplementationOverrides
            // in NamedTypeSymbolAdapter.cs).
            return this.IsOverride ?
                this.RequiresExplicitOverride() :
                this.IsMetadataVirtual(ignoreInterfaceImplementationChanges);
        }
```

For a method that overrides using covariant returns, this method is supposed to return true. When the overriding method is represented by a RetargetingMethodSymbol, IsMetadataNewSlot should also return true. Please add a targeted test to assert both expectations.

Here is another place (RetargetingMethodSymbol) where RequiresExplicitOverride makes a difference:
```
         internal MethodSymbol ExplicitlyOverriddenClassMethod
        {
            get
            {
                return
                    _underlyingMethod.RequiresExplicitOverride()
                        ? this.RetargetingTranslator.Retarget(_underlyingMethod.OverriddenMethod, MemberSignatureComparer.RetargetedExplicitImplementationComparer)
                        : null;
            }
        }
```

I strongly believe that the behavior of this function shouldn't depend on the fact whether the underlying compilation targets runtime with a fix or not. The behavior should be consistent across scenarios when there is an ambiguity at runtime and when there isn't an ambiguity at runtime. The reason is - there is no ambiguity at runtime for covariant return case, or the code simply would be illegal for that runtime. One might say that the mechanism we are using to detects the ambiguity has a flaw, it shouldn't be detecting any for a covariant return case. The proposed change basically mitigates that flaw. 


---
In reply to: [446472369](https://github.com/dotnet/roslyn/pull/44025#discussion_r446472369) [](ancestors = 446472369,446471373,446463069,446461000,446458615,446453378,446450749,446444174,446418702,446416546,446413877,446358005,446321935)

**Comment by AlekseyTs** [comment]
It appears that commit 33 lacks adequate testing for Covariant Return scenarios. It looks like there are no tests added that would test scenarios around run-time ambiguity linked to WRN_MultipleRuntimeOverrideMatches and Covariant Returns. Zero. None.

I took the liberty to try out this branch and did some testing around the changes in RequiresExplicitOverride function about which I raised concerns earlier. It didn't take much time to find issues with the current behavior. Here is a couple of unit-tests. They reflect the current behavior, Behaviors unexpected from my point of view are marked with ```// ISSUE:``` comment.

```

        [Fact]
        public void Test_01()
        {
            var source1 = @"
public class Base<T>
{
    public virtual object M(out int x) => throw null;
    public virtual object M(ref T x) => throw null;
}
";
            var source2 = @"
public class Derived : Base<int>
{
    public override string M(out int x) => throw null;
}
";
            var comp = CreateCompilationWithCovariantReturns(source1 + source2, pretendRuntimeSupportsCovariantReturnsFeature: true).VerifyDiagnostics(
                );

            var m = comp.SourceAssembly.GlobalNamespace.GetMember<MethodSymbol>("Derived.M");
            Assert.True(m.IsMetadataNewSlot());
            Assert.True(m.RequiresExplicitOverride());
            m.GetFirstRuntimeOverriddenMethodIgnoringNewSlot(out bool wasAmbiguous);
            Assert.False(wasAmbiguous);

            var metadataReference = comp.EmitToImageReference();

            comp = CreateCompilationWithCovariantReturns(source2, pretendRuntimeSupportsCovariantReturnsFeature: true, references: new[] { metadataReference }).VerifyDiagnostics(
                );

            m = comp.SourceAssembly.GlobalNamespace.GetMember<MethodSymbol>("Derived.M");
            Assert.True(m.IsMetadataNewSlot());
            Assert.True(m.RequiresExplicitOverride());
            m.GetFirstRuntimeOverriddenMethodIgnoringNewSlot(out wasAmbiguous);
            Assert.False(wasAmbiguous);

            // ISSUE: The WRN_MultipleRuntimeOverrideMatches warning is just a noise, we would never try to emit metadata for runtime that doesn't include the fix for the ambiguity at run-time. 
            comp = CreateCompilationWithCovariantReturns(source1 + source2, pretendRuntimeSupportsCovariantReturnsFeature: false).VerifyDiagnostics(
                // (4,27): warning CS1957: Member 'Derived.M(out int)' overrides 'Base<int>.M(out int)'. There are multiple override candidates at run-time. It is implementation dependent which method will be called. Please use a newer runtime.
                //     public virtual object M(out int x) => throw null;
                Diagnostic(ErrorCode.WRN_MultipleRuntimeOverrideMatches, "M").WithArguments("Base<int>.M(out int)", "Derived.M(out int)").WithLocation(4, 27),
                // (10,28): error CS8778: 'Derived.M(out int)': Target runtime doesn't support covariant return types in overrides. Return type must be 'object' to match overridden member 'Base<int>.M(out int)'
                //     public override string M(out int x) => throw null;
                Diagnostic(ErrorCode.ERR_RuntimeDoesNotSupportCovariantReturnsOfClasses, "M").WithArguments("Derived.M(out int)", "Base<int>.M(out int)", "object").WithLocation(10, 28)
                );

            m = comp.SourceAssembly.GlobalNamespace.GetMember<MethodSymbol>("Derived.M");
            Assert.True(m.IsMetadataNewSlot());
            Assert.True(m.RequiresExplicitOverride());
            m.GetFirstRuntimeOverriddenMethodIgnoringNewSlot(out wasAmbiguous);

            // Apparently, it isn't ambiguous, as I was expecting.
            Assert.False(wasAmbiguous);

            // ISSUE: The WRN_MultipleRuntimeOverrideMatches warning is just a noise, we would never try to emit metadata for runtime that doesn't include the fix for the ambiguity at run-time. 
            comp = CreateCompilationWithCovariantReturns(source2, pretendRuntimeSupportsCovariantReturnsFeature: false, references: new[] { metadataReference }).VerifyDiagnostics(
                // warning CS1957: Member 'Derived.M(out int)' overrides 'Base<int>.M(out int)'. There are multiple override candidates at run-time. It is implementation dependent which method will be called. Please use a newer runtime.
                Diagnostic(ErrorCode.WRN_MultipleRuntimeOverrideMatches).WithArguments("Base<int>.M(out int)", "Derived.M(out int)").WithLocation(1, 1),
                // (4,28): error CS8778: 'Derived.M(out int)': Target runtime doesn't support covariant return types in overrides. Return type must be 'object' to match overridden member 'Base<int>.M(out int)'
                //     public override string M(out int x) => throw null;
                Diagnostic(ErrorCode.ERR_RuntimeDoesNotSupportCovariantReturnsOfClasses, "M").WithArguments("Derived.M(out int)", "Base<int>.M(out int)", "object").WithLocation(4, 28)
                );

            m = comp.SourceAssembly.GlobalNamespace.GetMember<MethodSymbol>("Derived.M");
            Assert.True(m.IsMetadataNewSlot());
            Assert.True(m.RequiresExplicitOverride());
            m.GetFirstRuntimeOverriddenMethodIgnoringNewSlot(out wasAmbiguous);

            // Apparently, it isn't ambiguous, as I was expecting.
            Assert.False(wasAmbiguous);
        }

        [Fact]
        public void Test_02()
        {
            var source1 = @"
public class Base1<T>
{
    public virtual string M(out int x) => throw null;
    public virtual string M(ref T x) => throw null;
}

public class Base2 : Base1<int>
{
    public new virtual object M(out int x) => throw null;
}
";
            var source2 = @"
public class Derived : Base2
{
    public override string M(out int x) => throw null;
}
";
            var comp = CreateCompilationWithCovariantReturns(source1 + source2, pretendRuntimeSupportsCovariantReturnsFeature: true).VerifyDiagnostics(
                );

            var m = comp.SourceAssembly.GlobalNamespace.GetMember<MethodSymbol>("Derived.M");
            Assert.True(m.IsMetadataNewSlot());
            Assert.True(m.RequiresExplicitOverride());
            m.GetFirstRuntimeOverriddenMethodIgnoringNewSlot(out bool wasAmbiguous);

            // ISSUE: Really ambiguous?
            Assert.True(wasAmbiguous);

            var metadataReference = comp.EmitToImageReference();

            comp = CreateCompilationWithCovariantReturns(source2, pretendRuntimeSupportsCovariantReturnsFeature: true, references: new[] { metadataReference }).VerifyDiagnostics(
                );

            Assert.True(m.IsMetadataNewSlot());
            Assert.True(m.RequiresExplicitOverride());
            m.GetFirstRuntimeOverriddenMethodIgnoringNewSlot(out wasAmbiguous);

            // ISSUE: Really ambiguous?
            Assert.True(wasAmbiguous);

            comp = CreateCompilationWithCovariantReturns(source1 + source2, pretendRuntimeSupportsCovariantReturnsFeature: false).VerifyDiagnostics(
                // (15,28): error CS8778: 'Derived.M(out int)': Target runtime doesn't support covariant return types in overrides. Return type must be 'object' to match overridden member 'Base2.M(out int)'
                //     public override string M(out int x) => throw null;
                Diagnostic(ErrorCode.ERR_RuntimeDoesNotSupportCovariantReturnsOfClasses, "M").WithArguments("Derived.M(out int)", "Base2.M(out int)", "object").WithLocation(15, 28)
                );

            m = comp.SourceAssembly.GlobalNamespace.GetMember<MethodSymbol>("Derived.M");
            Assert.False(m.IsMetadataNewSlot()); // ISSUE: Why is this different now? This is a spec violation.
            Assert.False(m.RequiresExplicitOverride()); // ISSUE: Why is this different now?
            m.GetFirstRuntimeOverriddenMethodIgnoringNewSlot(out wasAmbiguous);

            // ISSUE: Really ambiguous?
            Assert.True(wasAmbiguous);

            comp = CreateCompilationWithCovariantReturns(source2, pretendRuntimeSupportsCovariantReturnsFeature: false, references: new[] { metadataReference }).VerifyDiagnostics(
                // (4,28): error CS8778: 'Derived.M(out int)': Target runtime doesn't support covariant return types in overrides. Return type must be 'object' to match overridden member 'Base2.M(out int)'
                //     public override string M(out int x) => throw null;
                Diagnostic(ErrorCode.ERR_RuntimeDoesNotSupportCovariantReturnsOfClasses, "M").WithArguments("Derived.M(out int)", "Base2.M(out int)", "object").WithLocation(4, 28)
                );

            m = comp.SourceAssembly.GlobalNamespace.GetMember<MethodSymbol>("Derived.M");
            Assert.False(m.IsMetadataNewSlot()); // ISSUE: Why is this different now? This is a spec violation.
            Assert.False(m.RequiresExplicitOverride()); // ISSUE: Why is this different now?
            m.GetFirstRuntimeOverriddenMethodIgnoringNewSlot(out wasAmbiguous);

            // ISSUE: Really ambiguous?
            Assert.True(wasAmbiguous);
        }
```  

I think we have a couple of options to address these issues:
1) We simply suppress reporting WRN_MultipleRuntimeOverrideMatches for covariant return case in CheckOverrideMember and always return true for covariant return case in RequiresExplicitOverride as I suggested on a separate thread. This is the cheapest option, I think. 
2) We adjust calculation of RuntimeOverriddenMembers set and GetFirstRuntimeOverriddenMethodIgnoringNewSlot to properly account for MethodImpl in metadata for a covariant return case and avoid false ambiguity reports about them.

I didn't try either approach, but I have relatively high degree of confidence, that either approach will eliminate issues around covariant return scenarios and will not break any existing tests. They also will not cause any observable violations of Covariant Returns specification and the compat council decision around preserving backwards compatibility in relation to WRN_MultipleRuntimeOverrideMatches.

**Comment by gafter** [comment]
Regarding your comments about unexpected `wasAmbiguous` produced by a call to `RuntimeOverriddenMembers`: these are actually all as expected. In each case the overridden method that would be found by the runtime (i.e. including the return type in the signature) is indeed ambiguous. That is what that is reporting to the caller. That is one piece of data used to determine if a methodimpl is required.

Regarding your comments about cascaded `WRN_MultipleRuntimeOverrideMatches` warnings in the presence of certain other errors: I agree that it would be good to avoid this. It isn't high priority, but I will address it in the next iteration.

I am working on a revision of the algorithm to compute whether a methodimpl is required. There are two different ambiguities that affect whether a methodimpl is required: the first represented by the flag you commented about, and a possible ambiguity in the type containing the language (not runtime) overridden method (if it is a different type). That revision will include deeper combinatorial tests of all of the factors that go into the decision whether to emit a warning and whether to emit a methodimpl.

**Comment by AlekseyTs** [comment]
> Regarding your comments about unexpected wasAmbiguous produced by a call to RuntimeOverriddenMembers: these are actually all as expected. In each case the overridden method that would be found by the runtime (i.e. including the return type in the signature) is indeed ambiguous. That is what that is reporting to the caller. That is one piece of data used to determine if a methodimpl is required.

That comment is actually about a value returned by ```GetFirstRuntimeOverriddenMethodIgnoringNewSlot``` method, not by the ```RuntimeOverriddenMembers``` property. Either that method, the ```GetFirstRuntimeOverriddenMethodIgnoringNewSlot```, shouldn't be involved into figuring out anything about covariant return case, or its behavior is not expected, because there is no ambiguity in a covariant return case. We emit special MethodImpl for a covariant return case and the MethodImpl is unambiguous in runtime that supports covariant returns. In a runtime that doesn't support covariant returns, the MethodImpl is always illegal, regardless of what it tries to points to. As it stands right now, ```GetFirstRuntimeOverriddenMethodIgnoringNewSlot``` affects behavior around covariant returns.

**Comment by AlekseyTs** [comment]
> As it stands right now, GetFirstRuntimeOverriddenMethodIgnoringNewSlot affects behavior around covariant returns.

To clarify, that effect is not unexpected ambiguity warnings being reported, the effect causes other symbol APIs behave in a way that violates specification for Covariant Returns feature. That is just what is obvious from reviewing the code changes. It is quite likely that other less obvious negative outcomes can come from it today or in the future.

**Comment by gafter** [comment]
> the effect causes other symbol APIs behave in a way that violates specification for Covariant Returns feature

The language specification for the feature is at https://github.com/dotnet/csharplang/blob/master/proposals/covariant-returns.md. As far as I know any language questions on the compiler APIs are answered by the compiler in agreement with the requirements of the language specification *except in those cases where the language is not representable in the targeted runtime version and the questions are asked about the runtime representation*.

If you find this is incorrect, please identify the specification requirement that is violated.

**Comment by AlekseyTs** [comment]
> If you find this is incorrect, please identify the specification requirement that is violated.

Overrides utilizing Covariant Returns must be metadata newslot and must have an explicit MethodImpl. This is part of the feature specification, whether you consider that a language part or not.

**Comment by gafter** [comment]
> Overrides utilizing Covariant Returns must be metadata newslot and must have an explicit MethodImpl.

That is the specification for the mapping of the language to the dotnet 5 platform. When emitting metadata for that platform we always obey that mapping.

In any case I have modified the way the APIs respond when the target framework does not support the language features used.

**Comment by AlekseyTs** [comment]
> In any case I have modified the way the APIs respond when the target framework does not support the language features used.

Thank you. Could you please add the unit-tests from https://github.com/dotnet/roslyn/pull/44025#issuecomment-650577122? It would be interesting to see the effect of the changes on those scenarios.

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs [hunk 55]
```diff
@@ -920,43 +905,85 @@ private static int CustomModifierCount(Symbol member)
...
+            // appear to the runtime to be ambiguous in some cases.
+            bool methodimplWouldBeAmbiguous = csharpOverriddenMethod.MethodHasRuntimeCollisionInSubstututedForm();
+            if (!methodimplWouldBeAmbiguous)
+                return true;
+
+            // We produce the warning when a methodimpl would be required but would be ambiguous to the runtime
+            warnAmbiguous = true;
+
+            bool overridenMethodContainedInSameTypeAsRuntimeOverriddenMethod =
+                csharpOverriddenMethod.ContainingType.Equals(runtimeOverriddenMethod.ContainingType, TypeCompareKind.CLRSignatureCompareOptions);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:945]: >CLRSignatureCompareOptions [](start = 117, length = 26)

Do we expect custom modifiers and array sizes make a difference for this scenario?

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:945]: >csharpOverriddenMethod.ContainingType.Equals(runtimeOverriddenMethod.ContainingType, TypeCompareKind.CLRSignatureCompareOptions); [](start = 16, length = 129)

Would it make sense to perform this check before ```MethodHasRuntimeCollisionInSubstututedForm``` check? In other words, is it possible to have a RuntimeCollisionInSubstututedForm when ```!overridenMethodContainedInSameTypeAsRuntimeOverriddenMethod```?

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:945]: > Would it make sense to perform this check before MethodHasRuntimeCollisionInSubstututedForm check? In other words, is it possible to have a RuntimeCollisionInSubstututedForm when !overridenMethodContainedInSameTypeAsRuntimeOverriddenMethod?

After reviewing implementation of MethodHasRuntimeCollisionInSubstututedForm, I see that these checks are orthogonal. However, the order could be significant in order to preserve legacy compiler behavior, especially for scenarios when we did produce a MethodImpl, but now wouldn't produce it due to ```methodimplWouldBeAmbiguous``` check. It might be worth following up on that separately.  

---
In reply to: [448079933](https://github.com/dotnet/roslyn/pull/44025#discussion_r448079933) [](ancestors = 448079933)

Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:945]: Since the same class can only occur once in the inheritance chain, I don't think there can be any differences as a practical matter.

---
In reply to: [448079095](https://github.com/dotnet/roslyn/pull/44025#discussion_r448079095) [](ancestors = 448079095)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:945]: To clarify, I am referring to the logic we used to have here before the Covariant Returns feature work. I.e.
```
                MethodSymbol runtimeOverriddenMethod = method.GetFirstRuntimeOverriddenMethodIgnoringNewSlot(ignoreInterfaceImplementationChanges: true);
                return csharpOverriddenMethod != runtimeOverriddenMethod &&
                    method.IsAccessor() != runtimeOverriddenMethod.IsAccessor();
```

I think we should consider simply duplicating/preserving the logic and returning true when it would produce true. 

---
In reply to: [448082197](https://github.com/dotnet/roslyn/pull/44025#discussion_r448082197) [](ancestors = 448082197,448079933)

**Comment by AlekseyTs** [comment]
> using Newtonsoft.Json;

Is this really used?

---
Refers to: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:14 in cd0752f. [](commit_id = cd0752f469203f7811fe7406d84b0e97e545df73, deletion_comment = False)

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 37)

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs (hunk 55 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:945]: The order of operations here simplifies the computation of when to produce a warning (`warnAmbiguous`).

> scenarios when we did produce a MethodImpl, but now wouldn't produce it due to methodimplWouldBeAmbiguous check

The previous compilers (e.g. Roslyn master) only produced a methodimpl if the first runtime match is an accessor (e.g. `Prop.get`) and the overridden method (e.g. `get_Prop()`) is not, or vice versa. There are three ways that can happen
1. if they are contained in different types. This code handles that with the final test and produces a methodimpl.
2. if they have the same return type after generic substitution and appear in the same type. That is a compile-time error CS0082.
3. similar to case (2) but with conflicting members declared in metadata, possibly using indexed properties. 

Only case (3) could make a difference in generated code, and I believe it is not a realistic scenario. If you think it is important, however, I could preserve the test from the old code for compat purposes.

---
In reply to: [448082197](https://github.com/dotnet/roslyn/pull/44025#discussion_r448082197) [](ancestors = 448082197,448079933)

**Comment by gafter** [comment]
Done.

---
In reply to: [652136417](https://github.com/dotnet/roslyn/pull/44025#issuecomment-652136417) [](ancestors = 652136417)

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs (hunk 55 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:945]: > Only case (3) could make a difference in generated code, and I believe it is not a realistic scenario. If you think it is important, however, I could preserve the test from the old code for compat purposes.

I would be more comfortable if we preserve the original logic for compat purposes. The area is very complicated and, I think it is better be safe than sorry, in case we forgot to think about some scenario. 

---
In reply to: [448473120](https://github.com/dotnet/roslyn/pull/44025#discussion_r448473120) [](ancestors = 448473120,448082197,448079933)

Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:945]: I have added the old condition and tests that demonstrate that it is used. As explained, all of those test scenarios are compile-time errors.

---
In reply to: [448493699](https://github.com/dotnet/roslyn/pull/44025#discussion_r448493699) [](ancestors = 448493699,448473120,448082197,448079933)

**Comment by gafter** [comment]
@AlekseyTs I believe I have responded to all of your comments. Do you have any others?

@333fred Could you please review the changes since your last approval?

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 39). It looks like there are legitimate test failures.

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs [hunk 56]
```diff
@@ -920,43 +905,89 @@ private static int CustomModifierCount(Symbol member)
...
+
+            // Due to https://github.com/dotnet/runtime/issues/38119 the methodimpl would
+            // appear to the runtime to be ambiguous in some cases.
+            bool methodimplWouldBeAmbiguous = csharpOverriddenMethod.MethodHasRuntimeCollisionInSubstututedForm();
+            if (!methodimplWouldBeAmbiguous)
+                return true;
+
+            // We produce the warning when a methodimpl would be required but would be ambiguous to the runtime.
+            // This ambiguity only arises due to collision after generic substitution.
+            warnAmbiguous = csharpOverriddenMethod.ContainingType.IsGenericType;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:943]: >csharpOverriddenMethod.ContainingType.IsGenericType [](start = 28, length = 51)

I am not sure if this check is accurate enough. If my understand is correct, this check is added to suppress confusing cascading warning for unit-test ```RecordTests.Overrides_01```. The type there is indeed not generic, but I think if we make it generic, we also don't want to report that warning. Also, I believe, ```IsGenericType``` is true when the type itself is not generic, but is contained in a generic type, I think we wouldn't want to report the warning for a non-generic type like that. I think several targeted tests are warranted around this issue. It looks like the usage of `records` feature isn't really required, it should be enough to declare the same virtual method twice in the same class and then attempt to override it. Also, consider if we could simply check whether both definitions of conflicting methods are completely equivalent and they are declared in source (i.e. in some compilation), which would constitute the error situation that compiler complains about elsewhere, and drop that check about generic types altogether. Please include a test for an attempt to override against retargeting methods, as apposed to an attempt to override against source methods directly.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 41)

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs (hunk 56 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:943]: This is intended to be a simple check for one form of invalid program to suppress the cascaded warning. It isn't intended to suppress the warning in all possible scenarios where it could be considered cascaded. Given how rare this situation is likely to be in the first place, improvements to reduce the cascaded warnings would not be worth the effort.

---
In reply to: [449128610](https://github.com/dotnet/roslyn/pull/44025#discussion_r449128610) [](ancestors = 449128610)

**Comment by gafter** [comment]
@AlekseyTs I have responded to your most recent comment. Do you have any others?

**Comment by gafter** [comment]
@Fred Silberberg Could you please review the changes since your last approval?

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs (hunk 56 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:943]: > This is intended to be a simple check for one form of invalid program to suppress the cascaded warning. It isn't intended to suppress the warning in all possible scenarios where it could be considered cascaded. Given how rare this situation is likely to be in the first place, improvements to reduce the cascaded warnings would not be worth the effort.

Could you please clarify what scenario you are trying to address? Since the commit adding this check didn't include any new tests, there is no certainty that my guess is accurate.

> The use of IsGenericType was intentional, as the return type may be defined using type parameters from an enclosing type.

Could you please elaborate. I am not sure why would this make any difference, Again, it is quite possible I misunderstand your intent here. 

> As you know, there is a bug in retargeted methods that would likely prevent a test of the form you suggest adding.

I didn't think the scenario is specific to Covariant Return scenarios. In that case, I am not aware of any bug that would prevent suggested testing. 

---
In reply to: [449160771](https://github.com/dotnet/roslyn/pull/44025#discussion_r449160771) [](ancestors = 449160771,449128610)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:943]: Note, that my initial suggestion was about adjusting behavior of ```GetFirstRuntimeOverriddenMethodIgnoringNewSlot``` to not report an ambiguity in that particular error scenario and to undo the adjustment here. Only that method has access to both candidates. Sorry if that was not clearly expressed in the initial comment. 

---
In reply to: [449175779](https://github.com/dotnet/roslyn/pull/44025#discussion_r449175779) [](ancestors = 449175779,449160771,449128610)

Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:943]: > Could you please clarify what scenario you are trying to address? Since the commit adding this check didn't include any new tests, there is no certainty that my guess is accurate.

I am trying to address the scenario that conflicting methods were declared in a non-generic type. There is an existing test that hits that scenario (inherited from master), which is why no additional test had to be added.

> Could you please elaborate? I am not sure why would this make any difference, Again, it is quite possible I misunderstand your intent here. 

A type that has no type parameters of its own but is nested inside a generic type can have a conflict in substituted form that would not have been a conflict where declared, due to the use of type parameters.

I don't consider it important which scenarios the warning is suppressed in, since in all applicable scenarios there is also an error reported. This change was mainly to simplify the merge with master.

---
In reply to: [449179890](https://github.com/dotnet/roslyn/pull/44025#discussion_r449179890) [](ancestors = 449179890,449175779,449160771,449128610)

Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:943]: > Note, that my initial suggestion was about adjusting behavior of GetFirstRuntimeOverriddenMethodIgnoringNewSlot to not report an ambiguity in that particular error scenario and to undo the adjustment here. Only that method has access to both candidates. Sorry if that was not clearly expressed in the initial comment. 

The purpose of `GetFirstRuntimeOverriddenMethodIgnoringNewSlot` is to compute what the runtime overridden method would be, ignoring `newslot` and ignoring what the actual overridden method *should* be. As such, it has no business paying any attention to the proper (non-runtime) overridden member. It is used to compute whether or not we need to produce a `methodimpl`, which is what this method does, so it cannot use the `methodimpl` as part of that computation.

---
In reply to: [449185254](https://github.com/dotnet/roslyn/pull/44025#discussion_r449185254) [](ancestors = 449185254,449179890,449175779,449160771,449128610)

**Comment by 333fred** [comment]
>             var propertyDeclaration = "public virtual Pbject Prop => default(Pbject);";

Is this supposed to be `Pbject`?

---
Refers to: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:4088 in ee5b72f. [](commit_id = ee5b72fcb4d36d6586a59e71ba7ac9b32496000f, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs (hunk 56 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:943]: > I am trying to address the scenario that conflicting methods were declared in a non-generic type. There is an existing test that hits that scenario (inherited from master), which is why no additional test had to be added.

Could you please point me to the exact unit-test?

> This change was mainly to simplify the merge with master.

I cannot say that I am comfortable with this approach. The merge from master indicated a possible flaw in the changes made in this PR. It is clear to me that more thorough testing is needed around this change, clearly demonstrating scenarios which you think is worth affecting and which you think is not worth affecting. Reviewers should have a clear understanding how this is going to affect different scenarios and should be able to form their own opinion about what is important and what is not important.  


---
In reply to: [449185254](https://github.com/dotnet/roslyn/pull/44025#discussion_r449185254) [](ancestors = 449185254,449179890,449175779,449160771,449128610)

**Comment by 333fred** [comment]
>             var propertyDeclaration = "public virtual Pbject Prop => default(Pbject);";

If it is, consider either commenting or making the name more obviously bad

---
In reply to: [653151076](https://github.com/dotnet/roslyn/pull/44025#issuecomment-653151076) [](ancestors = 653151076)

---
Refers to: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:4088 in fafc14d. [](commit_id = fafc14d2c142105434917fb95af0f02918c73643, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs (hunk 56 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:943]: You can see the difference in the behavior of the test `RecordTests.Overrides_01`. We do not report the warning in that case.

If there is a specific flaw in the behavior of the compiler as implemented here, please identify it. All of the possible code paths are exercised by tests. There are certainly many other "scenarios" in which the warning may or may not be suppressed, but I don't believe it is important that any of them (or all of them) are suppressed.

---
In reply to: [449190145](https://github.com/dotnet/roslyn/pull/44025#discussion_r449190145) [](ancestors = 449190145,449185254,449179890,449175779,449160771,449128610)

**Comment by gafter** [comment]
>             var propertyDeclaration = "public virtual Pbject Prop => default(Pbject);";

Yes, it is a type parameter that will be substituted with `object`.

---
In reply to: [653151076](https://github.com/dotnet/roslyn/pull/44025#issuecomment-653151076) [](ancestors = 653151076)

---
Refers to: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:4088 in ee5b72f. [](commit_id = ee5b72fcb4d36d6586a59e71ba7ac9b32496000f, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs (hunk 56 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:943]: > An ambiguity there (in the runtime override) is irrelevant to whether or not the methodimpl would be ambiguous, as the methodimpl may well point to some other type altogether.

> The purpose of GetFirstRuntimeOverriddenMethodIgnoringNewSlot is to compute what the runtime overridden method would be, ignoring newslot and ignoring what the actual overridden method should be. As such, it has no business paying any attention to the proper (non-runtime) overridden member. It is used to compute whether or not we need to produce a methodimpl, which is what this method does, so it cannot use the methodimpl as part of that computation.

I am merely making a suggestion how to address an issue that in my opinion exists with the current code. If you think there is a better way to to improve things, that is great. There is really no point in arguing what should do what and what should pay attention to what. The resulting behavior is more important. We are in complete control and can redefine all these things. For example, you did that in this PR. It used to be that ```GetFirstRuntimeOverriddenMethodIgnoringNewSlot``` was not involved into deciding whether to report WRN_MultipleRuntimeOverrideMatches, but now it is involved and, I believe, that is one of the reasons why we started reporting WRN_MultipleRuntimeOverrideMatches in cases when we didn't before.    

---
In reply to: [449190145](https://github.com/dotnet/roslyn/pull/44025#discussion_r449190145) [](ancestors = 449190145,449185254,449179890,449175779,449160771,449128610)

Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:943]: > You can see the difference in the behavior of the test RecordTests.Overrides_01. We do not report the warning in that case.

> If there is a specific flaw in the behavior of the compiler as implemented here, please identify it. All of the possible code paths are exercised by tests. There are certainly many other "scenarios" in which the warning may or may not be suppressed, but I don't believe it is important that any of them (or all of them) are suppressed.

Ok, let me do my own testing then.

---
In reply to: [449195217](https://github.com/dotnet/roslyn/pull/44025#discussion_r449195217) [](ancestors = 449195217,449190145,449185254,449179890,449175779,449160771,449128610)

**Comment by gafter** [comment]
>             var propertyDeclaration = "public virtual Pbject Prop => default(Pbject);";

This is done throughout these tests, including e.g. `Ptring` for `string`. I'd rather not add a revision for renaming identifiers in tests.

---
In reply to: [653154733](https://github.com/dotnet/roslyn/pull/44025#issuecomment-653154733) [](ancestors = 653154733,653151076)

---
Refers to: src/Compilers/CSharp/Test/Symbol/Symbols/CovariantReturnTests.cs:4088 in ee5b72f. [](commit_id = ee5b72fcb4d36d6586a59e71ba7ac9b32496000f, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs (hunk 56 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:943]: > Ok, let me do my own testing then.

With the latest state of the branch (commit 41) I simply tested scenarios that were outlined at the beginning of this thread. I.e. conflicting methods declared in a generic type and conflicted methods declared in a non-generic type, which is nested into a generic type. These were compared against the scenario when conflicted methods were declared in a non-generic top-level type. I also paid attention to behavior inconsistencies between targeting runtime that supports Covariant Returns feature and runtime that doesn't support it.

My expectations were:
- There should be no difference in behavior across different flavors of type genericity, because it really makes no difference since methods conflict at their original definition point
- There should be no difference in behavior across different flavors of targeted runtimes, because the scenario doesn't involve the Covariant Returns feature, nor could it benefit from any fix that a runtime supporting the feature might have.
- There should be no WRN_MultipleRuntimeOverrideMatches warnings reported for scenarios for which this warning is not reported in master branch right now.

The full code of the unit-tests is below, they reflect behavior of the branch at commit 41.
Here is the summary:
1) Test03 - a non-generic top-level type
-  WRN_MultipleRuntimeOverrideMatches warning is not reported, it is not reported for this scenario in master.
-  Values of IsMetadataNewSlot and RequiresExplicitOverride on the override flip-flop depending on whether runtime supports Covariant Returns feature.
2) Test04 - a generic top-level type
-  Presence of the WRN_MultipleRuntimeOverrideMatches warning flip-flops depending on whether runtime supports Covariant Returns feature.
-  Values of IsMetadataNewSlot and RequiresExplicitOverride on the override flip-flop depending on whether runtime supports Covariant Returns feature.
3) Test05 - a non-generic type nested into generic type
-  Presence of the WRN_MultipleRuntimeOverrideMatches warning flip-flops depending on whether runtime supports Covariant Returns feature. It is not reported for this scenario in master.
-  Values of IsMetadataNewSlot and RequiresExplicitOverride on the override flip-flop depending on whether runtime supports Covariant Returns feature.

I don't believe there is a benefit in this "erratic" behavior across scenarios.

I also believe that the change
```
            // We produce the warning when a methodimpl would be required but would be ambiguous to the runtime.
            // This ambiguity only arises due to collision after generic substitution.
            warnAmbiguous = csharpOverriddenMethod.ContainingType.IsGenericType;
```
is confusing to the reader of the code in the sense that it doesn't go to the core of the issue we want to handle, which was indicated by the failing tests that came from master. Yes, the change in commit 41 suppresses the warning for some specific scenario, but it is not general enough to cover all family of them. Besides that, we still have the issue with flip-flopping IsMetadataNewSlot and RequiresExplicitOverride API across all scenarios.

I would like to propose a simple fix to address all these problems together. Instead of making changes in ```RequiresExplicitOverride```, I suggest to make a small change in ```GetFirstRuntimeOverriddenMethodIgnoringNewSlot``` function. Right before we record the fact of ambiguity, we could add a check that explicitly targets duplicate method declarations:
```
                                if (MemberSignatureComparer.RuntimeSignatureComparer.Equals(candidate.OriginalDefinition, overridden.OriginalDefinition))
                                {
                                    // Identical definitions in the original type definitions. This is not supported by any runtime and it is probably 
                                    // better to not treat this as an ambiguity, since an error is likely has been reported elsewhere.
                                    continue;
                                }

                                // found more than one possible override in this type
                                wasAmbiguous = true;
                                return candidate;
```

After this change all three tests start behaving as I would expect them to behave. I even ran all Roslyn tests, all of them passed.
Given the simplicity of the proposed change, focus on specific condition that causes the trouble, and the consistency benefits that it gives, I believe it is a better option by comparison to the current approach.  

The tests:
```
        [Theory]
        [CombinatorialData]
        public void Test_03(bool withCovariantCapableRuntime)
        {
            var src = @"
class Base
{
    public virtual void M1() => throw null; // 1

    public virtual void M1() => throw null; // 2
}

class Derived : Base
{
    public override void M1() => throw null; // 3
}
";

            var comp = CreateCompilationWithCovariantReturns(src, pretendRuntimeSupportsCovariantReturnsFeature: withCovariantCapableRuntime);
            var symbol = comp.GetMember<MethodSymbol>("Derived.M1");
            Assert.Equal("void Derived.M1()", symbol.ToTestDisplayString());

            comp.VerifyDiagnostics(
                // (6,25): error CS0111: Type 'Base' already defines a member called 'M1' with the same parameter types
                //     public virtual void M1() => throw null; // 2
                Diagnostic(ErrorCode.ERR_MemberAlreadyExists, "M1").WithArguments("M1", "Base").WithLocation(6, 25)
                );

            Assert.Equal(withCovariantCapableRuntime, symbol.IsMetadataNewSlot()); // Expected False regardless of runtime
            Assert.Equal(withCovariantCapableRuntime, symbol.RequiresExplicitOverride(out _)); // Expected False regardless of runtime
        }

        [Theory]
        [CombinatorialData]
        public void Test_04(bool withCovariantCapableRuntime)
        {
            var src = @"
class Base<T>
{
    public virtual void M1() => throw null; // 1

    public virtual void M1() => throw null; // 2
}

class Derived : Base<int>
{
    public override void M1() => throw null; // 3
}
";

            var comp = CreateCompilationWithCovariantReturns(src, pretendRuntimeSupportsCovariantReturnsFeature: withCovariantCapableRuntime);

            var symbol = comp.GetMember<MethodSymbol>("Derived.M1");
            Assert.Equal("void Derived.M1()", symbol.ToTestDisplayString());

            // (6,25): error CS0111: Type 'Base<T>' already defines a member called 'M1' with the same parameter types
            //     public virtual void M1() => throw null; // 2
            var common1 = Diagnostic(ErrorCode.ERR_MemberAlreadyExists, "M1").WithArguments("M1", "Base<T>").WithLocation(6, 25);
            // (11,26): error CS0462: The inherited members 'Base<T>.M1()' and 'Base<T>.M1()' have the same signature in type 'Derived', so they cannot be overridden
            //     public override void M1() => throw null; // 3
            var common2 = Diagnostic(ErrorCode.ERR_AmbigOverride, "M1").WithArguments("Base<T>.M1()", "Base<T>.M1()", "Derived").WithLocation(11, 26);

            if (withCovariantCapableRuntime)
            {
                comp.VerifyDiagnostics(common1, common2);
            }
            else
            {
                comp.VerifyDiagnostics(
                    // (4,25): warning CS1957: Member 'Derived.M1()' overrides 'Base<int>.M1()'. There are multiple override candidates at run-time. It is implementation dependent which method will be called.
                    //     public virtual void M1() => throw null; // 1
                    Diagnostic(ErrorCode.WRN_MultipleRuntimeOverrideMatches, "M1").WithArguments("Base<int>.M1()", "Derived.M1()").WithLocation(4, 25),
                    common1, common2
                    );
            }

            Assert.Equal(withCovariantCapableRuntime, symbol.IsMetadataNewSlot()); // Expected False regardless of runtime
            Assert.Equal(withCovariantCapableRuntime, symbol.RequiresExplicitOverride(out _)); // Expected False regardless of runtime
        }

        [Theory]
        [CombinatorialData]
        public void Test_05(bool withCovariantCapableRuntime)
        {
            var src = @"
class Container<T>
{
    class Base
    {
        public virtual void M1() => throw null; // 1

        public virtual void M1() => throw null; // 2
    }

    class Derived : Base
    {
        public override void M1() => throw null; // 3
    }
}
";

            var comp = CreateCompilationWithCovariantReturns(src, pretendRuntimeSupportsCovariantReturnsFeature: withCovariantCapableRuntime);

            var symbol = comp.GetMember<MethodSymbol>("Container.Derived.M1");
            Assert.Equal("void Container<T>.Derived.M1()", symbol.ToTestDisplayString());

            // (8,29): error CS0111: Type 'Container<T>.Base' already defines a member called 'M1' with the same parameter types
            //         public virtual void M1() => throw null; // 2
            var common = Diagnostic(ErrorCode.ERR_MemberAlreadyExists, "M1").WithArguments("M1", "Container<T>.Base").WithLocation(8, 29);

            if (withCovariantCapableRuntime)
            {
                comp.VerifyDiagnostics(common);
            }
            else
            {
                comp.VerifyDiagnostics(
                    // (6,29): warning CS1957: Member 'Container<T>.Derived.M1()' overrides 'Container<T>.Base.M1()'. There are multiple override candidates at run-time. It is implementation dependent which method will be called. Please use a newer runtime.
                    //         public virtual void M1() => throw null; // 1
                    Diagnostic(ErrorCode.WRN_MultipleRuntimeOverrideMatches, "M1").WithArguments("Container<T>.Base.M1()", "Container<T>.Derived.M1()").WithLocation(6, 29),
                    common
                    );
            }

            Assert.Equal(withCovariantCapableRuntime, symbol.IsMetadataNewSlot()); // Expected False regardless of runtime
            Assert.Equal(withCovariantCapableRuntime, symbol.RequiresExplicitOverride(out _)); // Expected False regardless of runtime
        }
```


   

---
In reply to: [449196034](https://github.com/dotnet/roslyn/pull/44025#discussion_r449196034) [](ancestors = 449196034,449195217,449190145,449185254,449179890,449175779,449160771,449128610)

**Comment by AlekseyTs** [comment]
Please add unit-tests from https://github.com/dotnet/roslyn/pull/44025#discussion_r449346129. And also please add this unit-test:
```
        [Theory]
        [CombinatorialData]
        public void Test_06(bool withCovariantCapableRuntime)
        {
            var src1 = @"
public class Container<T>
{
    public class Base
    {
        public virtual void M1() => throw null; // 1

        public virtual void M1() => throw null; // 2
    }
}
";

            var src2 = @"
class Derived : Container<int>.Base
{
    public override void M1() => throw null; // 3
}
";

            var comp1 = CreateCompilationWithCovariantReturns(src1, pretendRuntimeSupportsCovariantReturnsFeature: withCovariantCapableRuntime, targetFramework: TargetFramework.Mscorlib40);
            comp1.VerifyDiagnostics(
                // (8,29): error CS0111: Type 'Container<T>.Base' already defines a member called 'M1' with the same parameter types
                //         public virtual void M1() => throw null; // 2
                Diagnostic(ErrorCode.ERR_MemberAlreadyExists, "M1").WithArguments("M1", "Container<T>.Base").WithLocation(8, 29)
                );

            var comp2 = CreateCompilationWithCovariantReturns(src2, pretendRuntimeSupportsCovariantReturnsFeature: withCovariantCapableRuntime, references: new[] { comp1.ToMetadataReference() }, targetFramework: TargetFramework.Mscorlib40);
            comp2.VerifyDiagnostics(
                // (4,26): error CS0462: The inherited members 'Container<T>.Base.M1()' and 'Container<T>.Base.M1()' have the same signature in type 'Derived', so they cannot be overridden
                //     public override void M1() => throw null; // 3
                Diagnostic(ErrorCode.ERR_AmbigOverride, "M1").WithArguments("Container<T>.Base.M1()", "Container<T>.Base.M1()", "Derived").WithLocation(4, 26)
                );

            var comp3 = CreateCompilationWithCovariantReturns(src2, pretendRuntimeSupportsCovariantReturnsFeature: withCovariantCapableRuntime, references: new[] { comp1.ToMetadataReference() }, targetFramework: TargetFramework.Mscorlib46);
            comp3.VerifyDiagnostics(
                // (4,26): error CS0462: The inherited members 'Container<T>.Base.M1()' and 'Container<T>.Base.M1()' have the same signature in type 'Derived', so they cannot be overridden
                //     public override void M1() => throw null; // 3
                Diagnostic(ErrorCode.ERR_AmbigOverride, "M1").WithArguments("Container<T>.Base.M1()", "Container<T>.Base.M1()", "Derived").WithLocation(4, 26)
                );
        }
```

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs (hunk 56 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:943]: I have recorded [https://github.com/dotnet/roslyn/issues/45678](https://github.com/dotnet/roslyn/issues/45678) for the suggestion to reduce cascaded diagnostics.

The behavior of the compiler internal methods `IsMetadataNewSlot()` and `RequiresExplicitOverride()` is intended. The values of these internal methods are expected to "flip-flop" depending on whether or not the target runtime contains a fix for [https://github.com/dotnet/runtime/issues/38119](https://github.com/dotnet/runtime/issues/38119), as these methods are used to implement the compat council's decision documented in [https://github.com/dotnet/roslyn/issues/45453](https://github.com/dotnet/roslyn/issues/45453). There are many tests in `CovariantReturnTests` that illustrate this behavior. Being internal methods, this behavior is not directly observable by consumers of the compiler.

---
In reply to: [449346129](https://github.com/dotnet/roslyn/pull/44025#discussion_r449346129) [](ancestors = 449346129,449196034,449195217,449190145,449185254,449179890,449175779,449160771,449128610)

**Comment by gafter** [comment]
These tests do not reflect the behavior of the compiler. I have recorded [https://github.com/dotnet/roslyn/issues/45678](https://github.com/dotnet/roslyn/issues/45678) for the suggestion to reduce cascaded diagnostics and add tests including these to confirm the suggested revised behavior.

---
In reply to: [653303890](https://github.com/dotnet/roslyn/pull/44025#issuecomment-653303890) [](ancestors = 653303890)

**Comment by gafter** [comment]
@AlekseyTs I have responded to your comments. Do you have any others?

File: src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs (hunk 56 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Symbols/OverriddenOrHiddenMembersHelpers.cs:943]: > The behavior of the compiler internal methods IsMetadataNewSlot() and RequiresExplicitOverride() is intended. The values of these internal methods are expected to "flip-flop" depending on whether or not the target runtime contains a fix for [https://github.com/dotnet/runtime/issues/38119](https://github.com/dotnet/runtime/issues/38119), as these methods are used to implement the compat council's decision documented in [https://github.com/dotnet/roslyn/issues/45453](https://github.com/dotnet/roslyn/issues/45453).

I do not agree with your interpretation of compat council decision. I believe it only applies to scenarios that are really affected by the runtime fix, and is focused only on preserving backward compatibility when compiler emits code against runtimes that do not have the fix. None of the scenarios discussed on this thread are applicable on either point: they are not affected by the runtime fix, there is no codegen to preserve  because no code is generated. Finally, I do not believe there is any benefit from the warning or APIs flip flopping for these scenarios. In my opinion, the logic for detecting ambiguity was moved to ```GetFirstRuntimeOverriddenMethodIgnoringNewSlot ``` with the intent to implement compat council's decision, but that was done in a way that doesn't accurately match the original logic, thus causing the warning to be reported for scenarios for which it wasn't reported before. I think, compat council never expressed a desire to change compiler's behavior in this way. 
Nevertheless, I am fine with following up on this separately, under umbrella of the opened issue.  

---
In reply to: [450310947](https://github.com/dotnet/roslyn/pull/44025#discussion_r450310947) [](ancestors = 450310947,449346129,449196034,449195217,449190145,449185254,449179890,449175779,449160771,449128610)

**Comment by AlekseyTs** [comment]
> These tests do not reflect the behavior of the compiler. I have recorded [https://github.com/dotnet/roslyn/issues/45678](https://github.com/dotnet/roslyn/issues/45678) for the suggestion to reduce cascaded diagnostics and add tests including these to confirm the suggested revised behavior.


Only the test above reflected behavior after proposed fix. The other three tests from the referenced thread reflect behavior of the compiler in this PR. However, I am fine with following up on this separately, under umbrella of the opened issue.  


---
In reply to: [654315472](https://github.com/dotnet/roslyn/pull/44025#issuecomment-654315472) [](ancestors = 654315472,653303890)
