### PR TITLE
catch watson failures closer to serialization

### LINKED ISSUE #14504: Catch exceptions closer to tree serialization
When SyntaxTree serialization fails the watsons often capture call stacks too far removed from the actual error due to async.   We should capture these failures closer to the actual error.

### PR DESCRIPTION
**Pull request by mattwar**
Fixes #14504 

Adds watson checks when SyntaxTrees are serialized and deserialized. This should help find problems in serialization, so the dumps have better information for tracking down the problems.

This is the same as #14506 except fixed and in RC branch.

@dotnet/roslyn-ide @jaredpar @VSadov  please review

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Syntax/CSharpSyntaxNode.cs [hunk 1]
```diff
@@ -201,13 +201,20 @@ public static SyntaxNode DeserializeFrom(Stream stream, CancellationToken cancel
...
             {
-                var root = (Syntax.InternalSyntax.CSharpSyntaxNode)reader.ReadValue();
-                return root.CreateRed();
+                using (var reader = new ObjectReader(stream, defaultData: GetDefaultObjectReaderData(), binder: s_defaultBinder))
+                {
+                    var root = (Syntax.InternalSyntax.CSharpSyntaxNode)reader.ReadValue();
+                    return root.CreateRed();
+                }
+            }
+            catch (Exception e) when (FatalError.ReportUnlessCanceled(e))
```
Comment (jasonmalinowski) [inline src/Compilers/CSharp/Portable/Syntax/CSharpSyntaxNode.cs]: This means we'll crash any consumers of the API that aren't VS, even if it's the consumer's mistake? I feel like we had some flag on this in the past to differentiate the two cases?

Comment (mattwar) [inline src/Compilers/CSharp/Portable/Syntax/CSharpSyntaxNode.cs]: No.  This is a no-op, unless we set the error handler, which we only do in our products.

**Comment by mattwar** [comment]
@dotnet-bot retest please
