### PR TITLE
Another round of compatibility fixes in Overload Resolution.

### LINKED ISSUE #2533: Breaking change in C# overload resolution with params parameter
Reported at https://twitter.com/eamodio/status/594144835130503168

The following program compiled on previous versions of Visual Studio, but fails when compiled with Roslyn-powered VS2015.

```cs
namespace VS2015_compile
{
    public class Foo
    {
        // Kind of stranger still if you comments out object o2 = null below then it will fail in both 2013 and 2015
        protected void Bar(object o, object o1, string s, object o2 = null) { }
        protected void Bar(string s, object o1, object o2) { }

        public void Baz()
        {
            // Fails in 2015 - ambiguous
            Bar("foo", null, null);
        }
    }
}
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #2533.

@VSadov, @gafter, @jaredpar Please review.

### CODE REVIEW

**Comment by VSadov** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs [hunk 1]
```diff
@@ -1186,9 +1187,9 @@ private static TypeSymbol GetParameterType(int argIndex, MemberAnalysisResult re
                     continue;
                 }
 
-                if (okToDowngradeToNeither)
+                if (!considerRefKinds || Conversions.ClassifyImplicitConversion(type1, type2, ref useSiteDiagnostics).Kind != ConversionKind.Identity)
                 {
-                    Debug.Assert(Conversions.ClassifyImplicitConversion(type1, type2, ref useSiteDiagnostics).Kind != ConversionKind.Identity);
+                    Debug.Assert(considerRefKinds || Conversions.ClassifyImplicitConversion(type1, type2, ref useSiteDiagnostics).Kind != ConversionKind.Identity);
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs]: This assert is precisely the same condition that was tested just above it. Please remove.

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs [hunk 2]
```diff
@@ -1267,6 +1269,36 @@ private static TypeSymbol GetParameterType(int argIndex, MemberAnalysisResult re
             GetParameterCounts(m1, arguments, out m1ParameterCount, out m1ParametersUsedIncludingExpansionAndOptional);
             GetParameterCounts(m2, arguments, out m2ParameterCount, out m2ParametersUsedIncludingExpansionAndOptional);
 
+            // We might have got out of the loop above early and allSame isn't completely calculated.
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs]: I can't tell what this comment is trying to tell me. Which `if` statement do we need to not skip over?

I feel like this method has gotten too long to be understood on its own. Can it be refactored into a set of helper methods?

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs [hunk 3]
```diff
@@ -1267,6 +1269,36 @@ private static TypeSymbol GetParameterType(int argIndex, MemberAnalysisResult re
...
+            // We need to ensure that we are not going to skip over the next 'if' because of that.
+            if (allSame && m1ParametersUsedIncludingExpansionAndOptional == m2ParametersUsedIncludingExpansionAndOptional)
+            {
+                // Complete comparison for the remaining parameter types
+                for (i = i + 1; i < arguments.Count; ++i)
+                {
+                    var argumentKind = arguments[i].Kind;
+
+                    // If these are both applicable varargs methods and we're looking at the __arglist argument
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs]: This code is copied-and-pasted from above, and then optimized for the parts that are used vs not used. That's dangerous, as bug fixes or changes in one now won't affect the other. Can this somehow be refactored to avoid the code duplication?

**Comment by gafter** [comment]
I would say this is OK for VS2015, but please create a work item to refactor the affected method for clarity and to eliminate duplication (which would be too risky this late in the VS2015 development schedule).

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs]: I don't believe the condition is the same. If considerRefKinds is false, conversion between parameter types isn't classified by the if condition. This assert is here to verify the assumption that the conversion is never an identity in that case and we can skip classification as an optimization.

Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs]: Can you please make that assumption explicit (e.g. cut and paste your response above after the first sentence).

**Comment by AlekseyTs** [comment]
@dotnet-bot test this please

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs]: I'll do this in a separate commit. Want to get this behavior change in ASAP. Opened an issue to track this work - #2641.
