### PR TITLE
Classify pattern-matching temp as long-lived

### LINKED ISSUE #18257: Pattern switch in async method causes compiler crash
The following code (thanks to @TyOverby) causes a compiler assertion

``` c#
// csc /t:library /optimize+ repro.cs
using System;
 
public class Foo {}
 
public class C {
    public async void M() {
        switch (new object())
        {
            case Foo _:
            default:
                throw new InvalidOperationException();
        }
    }
}
```

The lowering temp produced by pattern-matching is not classified as long-lived, and probably should be.

### PR DESCRIPTION
**Pull request by gafter**
**Customer scenario**

Use a switch in an async method, where the switch uses any new features introduced in C# 7.0.

**Bugs this fixes:**

Fixes #18257

**Workarounds, if any**

None known.

**Risk**

Small, as there is no change to code generation, but rather the classification of variables affecting the PDB.

**Performance impact**

Tiny, if any. Thee is only a slight change to which (existing) compiler code path is taken for these scenarios.

**Is this a regression from a previous update?**

No, the pattern-matching switch was new in C# 7.0.

**Root cause analysis:**

We did not test the interaction of pattern-matching with async.

**How was the bug found?**

Customer reported.

### CODE REVIEW

**Comment by gafter** [comment]
@agocke @AlekseyTs May I please have a review?

**Comment by gafter** [comment]
[Looking at the test failures now]

**Comment by jaredpar** [comment]
Approved pending sign offs.

File: src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs [hunk 1]
```diff
@@ -5860,12 +5863,12 @@ static void M(object o)
         <entry offset=""0x7a"" startLine=""18"" startColumn=""17"" endLine=""18"" endColumn=""23"" />
         <entry offset=""0x7c"" startLine=""20"" startColumn=""9"" endLine=""20"" endColumn=""19"" />
         <entry offset=""0x81"" hidden=""true"" />
-        <entry offset=""0xb5"" startLine=""23"" startColumn=""17"" endLine=""23"" endColumn=""23"" />
-        <entry offset=""0xb7"" startLine=""25"" startColumn=""17"" endLine=""25"" endColumn=""23"" />
-        <entry offset=""0xb9"" startLine=""27"" startColumn=""9"" endLine=""27"" endColumn=""19"" />
-        <entry offset=""0xbe"" hidden=""true"" />
-        <entry offset=""0xc8"" startLine=""30"" startColumn=""17"" endLine=""30"" endColumn=""23"" />
-        <entry offset=""0xca"" startLine=""32"" startColumn=""5"" endLine=""32"" endColumn=""6"" />
+        <entry offset=""0xba"" startLine=""23"" startColumn=""17"" endLine=""23"" endColumn=""23"" />
```
Comment (tmat) [inline src/Compilers/CSharp/Test/Emit/PDB/PDBTests.cs]: The changes in sequence points suggest there are changes in IL. Seems like no other test covers the difference in IL. It would be good to have one.

File: src/Compilers/Core/Portable/SynthesizedLocalKind.cs [hunk 2]
```diff
@@ -207,6 +204,11 @@ internal enum SynthesizedLocalKind
         InstrumentationPayload = 34,
 
         /// <summary>
+        /// Temp created for pattern matching by type.
+        /// </summary>
+        PatternMatchingTemp = 35,
```
Comment (tmat) [inline src/Compilers/Core/Portable/SynthesizedLocalKind.cs]: I'd remove "Temp" from the name. "Temp" suggests it's temporary, not long lived.
It would also be useful to mention in the comment what value is specifically stored in this variable. Is it the type object we are switching on?

**Comment by gafter** [comment]
@tmat Thanks for the suggestions. I've modified the PR to address both.
