### PR TITLE
Fixing race condition between setting and reading _lazyEmitExtensionAttribute

### LINKED ISSUE #5516: Race condition in AnonymousTypeSymbol
```
MESSAGE:
Debug.Assert() Failure
+++++++++++++++++++
STACK TRACE:
MESSAGE:
Debug.Assert() Failure
+++++++++++++++++++
STACK TRACE:
at System.Diagnostics.TraceListener.Fail(String message)
 at System.Diagnostics.TraceInternal.Fail(String message)
 at System.Diagnostics.Debug.Assert(Boolean condition)
 at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceAssemblySymbol.AddSynthesizedAttributes(ModuleCompilationState compilationState, ArrayBuilder`1& attributes) in d:\j\workspace\dotnet_roslyn_prtest_win_dbg_32\src\Compilers\VisualBasic\Portable\Symbols\Source\SourceAssemblySymbol.vb:line 1396
 at Microsoft.CodeAnalysis.VisualBasic.Symbol.GetCustomAttributesToEmit(ModuleCompilationState compilationState, Boolean emittingAssemblyAttributesInNetModule) in d:\j\workspace\dotnet_roslyn_prtest_win_dbg_32\src\Compilers\VisualBasic\Portable\Emit\SymbolAdapter.vb:line 44
 at Microsoft.CodeAnalysis.VisualBasic.Emit.PEModuleBuilder.GetSourceAssemblyAttributes() in d:\j\workspace\dotnet_roslyn_prtest_win_dbg_32\src\Compilers\VisualBasic\Portable\Emit\PEModuleBuilder.vb:line 185
 at Microsoft.CodeAnalysis.Emit.PEModuleBuilder`9.Microsoft.Cci.IModule.get_AssemblyAttributes() in d:\j\workspace\dotnet_roslyn_prtest_win_dbg_32\src\Compilers\Core\Portable\Emit\CommonPEModuleBuilder.cs:line 732
 at Microsoft.Cci.ReferenceIndexer.Visit(IModule module) in d:\j\workspace\dotnet_roslyn_prtest_win_dbg_32\src\Compilers\Core\Portable\PEWriter\ReferenceIndexer.cs:line 35
 at Microsoft.Cci.ReferenceIndexer.Visit(IAssembly assembly) in d:\j\workspace\dotnet_roslyn_prtest_win_dbg_32\src\Compilers\Core\Portable\PEWriter\ReferenceIndexer.cs:line 24
 at Microsoft.CodeAnalysis.VisualBasic.Emit.PEAssemblyBuilderBase.Dispatch(MetadataVisitor visitor) in d:\j\workspace\dotnet_roslyn_prtest_win_dbg_32\src\Compilers\VisualBasic\Portable\Emit\PEAssemblyBuilder.vb:line 50
 at Microsoft.Cci.MetadataWriter.CreateIndices() in d:\j\workspace\dotnet_roslyn_prtest_win_dbg_32\src\Compilers\Core\Portable\PEWriter\MetadataWriter.cs:line 545
 at Microsoft.Cci.MetadataWriter.SerializeMetadataAndIL(BlobBuilder metadataWriter, BlobBuilder debugMetadataWriterOpt, PdbWriter nativePdbWriterOpt, BlobBuilder ilWriter, BlobBuilder mappedFieldDataWriter, BlobBuilder managedResourceDataWriter, Int32 methodBodyStreamRva, Func`2 calculateMappedFieldDataStreamRva, Int32& moduleVersionIdOffsetInMetadataStream, Int32& entryPointToken, MetadataSizes& metadataSizes) in d:\j\workspace\dotnet_roslyn_prtest_win_dbg_32\src\Compilers\Core\Portable\PEWriter\MetadataWriter.cs:line 2104
 at Microsoft.Cci.PeWriter.WritePeToStream(MetadataWriter mdWriter, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt) in d:\j\workspace\dotnet_roslyn_prtest_win_dbg_32\src\Compilers\Core\Portable\PEWriter\PeWriter.cs:line 126
 at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean allowMissingMethodBodies, Boolean deterministic, CancellationToken cancellationToken) in d:\j\workspace\dotnet_roslyn_prtest_win_dbg_32\src\Compilers\Core\Portable\PEWriter\PeWriter.cs:line 94
 at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, Func`1 testSymWriterFactory, DiagnosticBag diagnostics, Boolean metadataOnly, CancellationToken cancellationToken) in d:\j\workspace\dotnet_roslyn_prtest_win_dbg_32\src\Compilers\Core\Portable\Compilation\Compilation.cs:line 1928
 at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken) in d:\j\workspace\dotnet_roslyn_prtest_win_dbg_32\src\Compilers\Core\Portable\Compilation\Compilation.cs:line 1784
 at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken) in d:\j\workspace\dotnet_roslyn_prtest_win_dbg_32\src\Compilers\Core\Portable\Compilation\Compilation.cs:line 1593
 at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CancellationToken cancellationToken) in d:\j\workspace\dotnet_roslyn_prtest_win_dbg_32\src\Compilers\Core\Portable\Compilation\Compilation.cs:line 1539
 at Microsoft.CodeAnalysis.VisualBasic.UnitTests.AnonymousTypesCodeGenTests._Closure$__2-1._Lambda$__0() in d:\j\workspace\dotnet_roslyn_prtest_win_dbg_32\src\Compilers\VisualBasic\Test\Emit\CodeGen\AnonymousTypesCodeGenTests.vb:line 167
 at System.Threading.Tasks.Task.InnerInvoke()
 at System.Threading.Tasks.Task.Execute()
```

### PR DESCRIPTION
**Pull request by VSadov**
Fixing race condition between setting and reading _lazyEmitExtensionAttribute

Fixes #5516

### CODE REVIEW

**Comment by VSadov** [comment]
@AlekseyTs @jaredpar @TyOverby - please review

File: src/Compilers/VisualBasic/Portable/Symbols/Source/SourceAssemblySymbol.vb [hunk 1]
```diff
@@ -1162,9 +1162,13 @@ Namespace Microsoft.CodeAnalysis.VisualBasic.Symbols
                             emitExtensionAttribute = ThreeState.True
                         End If
                     End If
-
                 End If
 
+                Debug.Assert(_lazyEmitExtensionAttribute = ThreeState.Unknown OrElse
+                             _lazyEmitExtensionAttribute = emitExtensionAttribute)
```
Comment (jaredpar) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceAssemblySymbol.vb]: Isn't this a racy assert?  It reads the value twice from memory.

**Comment by AlekseyTs** [comment]
LGTM

File: src/Compilers/VisualBasic/Portable/Symbols/Source/SourceAssemblySymbol.vb (hunk 1 above)
Comment (VSadov) [inline src/Compilers/VisualBasic/Portable/Symbols/Source/SourceAssemblySymbol.vb]: order is unimportant ( I could use Or here) and assert would be racy even if we read once since a bad value could be installed right after we checked.

I think this is as good as we can have. "Assert we have no races here" is typically at best a best effort. 
The old assert was also racy and eventually caught something.

**Comment by VSadov** [comment]
test win please

**Comment by VSadov** [comment]
test win

**Comment by VSadov** [comment]
@dotnet-bot Test win 64 please

**Comment by VSadov** [comment]
test win 64 please

**Comment by VSadov** [comment]
test win please

**Comment by VSadov** [comment]
how do I tell it to run tests again nowdays?..

**Comment by VSadov** [comment]
@dotnet-bot test this please
