### PR TITLE
Don't offer to remove necessary native integer casts

### LINKED ISSUE #47800: Conversion from `IntPtr` to `nint` to `nuint` incorrectly reported as redundant.
The following code incorrectly reports a cast from `IntPtr` -> `nint` -> `nuint` as redundant:
```csharp
using System;

public class C {
    public nuint M(nint x) => (nuint)x;

    public nint M(nuint x) => (nint)x;

    public nuint N(IntPtr x) => (nuint)(nint)x; // IDE0004: Cast is redundant

    public nint N(UIntPtr x) => (nint)(nuint)x; // IDE0004: Cast is redundant

    public nuint O(IntPtr x) => (nuint)x; // CS0030: Cannot convert type 'System.IntPtr' to 'nuint'

    public nint O(UIntPtr x) => (nint)x;  // CS0030: Cannot convert type 'System.UIntPtr' to 'nint'
}
```

However, it is required as casting directly from `IntPtr` to `nuint` is disallowed (only a conversion from `nint` to `nuint` is allowed)

Sharplab for master from Sep 15th:
https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAmARgFgAoUnAZgAJ8qBhKgb1KtZuoDsBXNDmKgLIAKDr34APAJRUAvAD4qInn0niA3KRZtKVUX0FKxVKbIUixqjWRJt2u5fwByQgJJ8ACjATHp8xdwtzFXUqAHpQqhcAEQBRAAYEgBYQemh+NCgqBDgAEy4OHIg+TRttTiNnAFU3GE9vEz8gmElDYLUwiOj4pJS6NKoMrNz8wuLrWx0A/QB5Vw8vH1N/B0sO+gBlBIo43qKOAHt+AGN9jgA3RH4YAE8ABzgqAHIcAgA6GrrHqhh9p6mYR4lCblGZCarzeq+Mx6ZohNZ0TZxba7DgHY6nC4IK53B7PN7g2peL4/P5iQEkAC+QA===

### PR DESCRIPTION
**Pull request by davidwengier**
Fixes #47800

### CODE REVIEW

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Simplification/Simplifiers/CastSimplifier.cs [hunk 1]
```diff
@@ -455,6 +455,50 @@ private static bool IsObjectCastInInterpolation(ExpressionSyntax castNode, IType
...
+                // Given (nuint)(nint)myIntPtr we would normally suggest removing the (nint) cast as being identity
+                // but it is required as a means to get from IntPtr to nuint, and vice versa from UIntPtr to nint,
+                // so we check for an identity cast from [U]IntPtr to n[u]int, and a parent cast to the opposite.
+                if (castedExpressionType.SpecialType == castType.SpecialType &&
+                    !castedExpressionType.IsNativeIntegerType &&
+                    castType.IsNativeIntegerType &&
+                    parentCastType.IsNativeIntegerType &&
+                    parentCastType.SpecialType == (castType.SpecialType == SpecialType.System_IntPtr
+                        ? SpecialType.System_UIntPtr
+                        : SpecialType.System_IntPtr))
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Simplification/Simplifiers/CastSimplifier.cs:496]: extract the RHS to a local.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by jasonmalinowski** [comment]
@davidwengier Thanks for fixing this one!
