### PR TITLE
Fix "Hide base member" code fix for constants

### LINKED ISSUE #18391: CS0108 Incorrectly shown with fix that breaks code
**Version Used**: 
Visual Studio 2017

**Steps to Reproduce**:
Put this code into C#:

````
    public class BaseClass {
        public const int PRIORITY = 100;   
    }

    public class DerivedClass : BaseClass {
        public const int PRIORITY = BaseClass.PRIORITY + 100;
    }
````

You get the following warning:
Warning	CS0108	'DerivedClass.PRIORITY' hides inherited member 'BaseClass.PRIORITY'. Use the new keyword if hiding was intended.

If you right-click on the squiggilies and select Quick Actions and Refactorings > Hide base member, it changes the code to look like this:

````
    public class DerivedClass : BaseClass {
        public const new int PRIORITY = BaseClass.PRIORITY + 100;
    }
````

The problem is, that code doesn't compile and now generates 4 errors instead of one warning.

### PR DESCRIPTION
**Pull request by MaximRouiller**
Imported the SyntaxGenerator to ensure that when adding `new` keyword to fields with existing modifiers, it would add them in the proper order without overriding any of them.

Fixes #18391

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs [hunk 1]
```diff
@@ -93,5 +93,29 @@ class App : Application
     public new int Test;
 }");
         }
+
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsAddNew)]
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs]: Hi!  Thanks for the contribution!  Please add a [WorkItem()] attribute here that links to the ithub bug.  thanks!

Comment (MaximRouiller) [inline src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs]: How do I append to this PR? First timer here.

**Comment by MaximRouiller** [comment]
@sharwell Will append to changes at the same time.

File: src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs (hunk 1 above)
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs]: You can add a new commit to your branch, and when you push your updated branch to your fork it will automatically update this pull request.

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.AddNewKeywordAction.cs [hunk 2]
```diff
@@ -51,7 +53,8 @@ private SyntaxNode GetNewNode(Document document, SyntaxNode node, CancellationTo
                 var fieldDeclaration = node as FieldDeclarationSyntax;
                 if (fieldDeclaration != null)
                 {
-                    newNode = fieldDeclaration.AddModifiers(SyntaxFactory.Token(SyntaxKind.NewKeyword));
+                    var generator = _document.GetLanguageService<SyntaxGenerator>();
+                    newNode = generator.WithModifiers(fieldDeclaration, generator.GetModifiers(fieldDeclaration).WithIsNew(true));
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.AddNewKeywordAction.cs]: I thnk this can be even simpler.  This entire method can just be:

```return generator.WithModifiers(fieldDeclaration, generator.GetModifiers(fieldDeclaration).WithIsNew(true));```

We don't need any of the rest of the code in this method.

File: src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.AddNewKeywordAction.cs [hunk 3]
```diff
@@ -51,7 +53,8 @@ private SyntaxNode GetNewNode(Document document, SyntaxNode node, CancellationTo
                 var fieldDeclaration = node as FieldDeclarationSyntax;
                 if (fieldDeclaration != null)
                 {
-                    newNode = fieldDeclaration.AddModifiers(SyntaxFactory.Token(SyntaxKind.NewKeyword));
+                    var generator = _document.GetLanguageService<SyntaxGenerator>();
```
Comment (sharwell) [inline src/Features/CSharp/Portable/CodeFixes/HideBase/HideBaseCodeFixProvider.AddNewKeywordAction.cs]: :bulb: I would suggest using `SyntaxGenerator.GetGenerator(_document)`, since that's part of the public API and makes for a better example of what other code fix authors can do. With that said, the form you used here is commonly seen in Roslyn's current code fixes. :smile:

**Comment by MaximRouiller** [comment]
Updated with relevant feedback.

File: src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs [hunk 4]
```diff
@@ -93,5 +93,30 @@ class App : Application
     public new int Test;
 }");
         }
+
+        [WorkItem(18391, "Issue where 'new' keyword would be in the wrong order on 'const' fields.")]
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs]: The string arg will just be the url of the github issue.  Thanks!

Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs]: (and yes, the int and the string are redundant :D)

Comment (sharwell) [inline src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs]: :bulb: The "description" should actually be a link to the issue:

```
[WorkItem(18391, "https://github.com/dotnet/roslyn/issues/18391")]
```

With that said, what you did here makes complete sense. I'll update `WorkItemAttribute` as a separate pull request so this is clear to future contributors. 👍

Comment (MaximRouiller) [inline src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs]: Done.

Comment (MaximRouiller) [inline src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs]: Done. 😄

**Comment by sharwell** [comment]
@MaximRouiller Are you interested in adding a second unit test showing that you've also fixed #14455? I'm specifically interested in seeing that the formatting issue is fixed, since with know `WithIsNew` would have fixed the ordering issue.

**Comment by MaximRouiller** [comment]
Yeah totally! There's nothing like fixing 2 bugs with one stone!

**Comment by MaximRouiller** [comment]
Separate pull request?

**Comment by sharwell** [comment]
> Separate pull request?

No, same one would make sense, since this is where the issue is fixed.

**Comment by MaximRouiller** [comment]
Tested it in Visual Studio and it does solves #14455.

Adding tests now.

**Comment by sharwell** [comment]
@MaximRouiller As promised, here's my update to `WorkItemAttribute`: #18403 :smile:

**Comment by MaximRouiller** [comment]
Pure curiosity. How long until it's merged? 😄

**Comment by CyrusNajmabadi** [comment]
We'll merge immediately once it is signed off on.  I would still like https://github.com/dotnet/roslyn/pull/18399#discussion_r109493689 addressed.  Thanks!

**Comment by MaximRouiller** [comment]
@CyrusNajmabadi Oh... you want me to refactor the WHOLE thing? Not just for `FieldDeclaration`? 😨

**Comment by CyrusNajmabadi** [comment]
Correct.  The rest of the code in that method should be unnecessary.

**Comment by MaximRouiller** [comment]
On it.

What other bugs will this solve? Anything related to it?

**Comment by sharwell** [comment]
@MaximRouiller great expression 😆

> What other bugs will this solve? Anything related to it?

It just makes the code simpler. The code contains separate branches for different types of syntax, but the new code you wrote using `SyntaxGenerator` works for all of them. Rather than special casing each construct, you can simplify the method to just get the generator and use it directly on the input syntax `node`.

**Comment by CyrusNajmabadi** [comment]
> What other bugs will this solve? Anything related to it?

It may not solve any other bugs (afaik).  But it's still the right way to write the code :)

**Comment by MaximRouiller** [comment]
It works but it changes the order of the keywords for the other tests.

I'll also be updating the tests.

**Comment by CyrusNajmabadi** [comment]
> It works but it changes the order of the keywords for the other tests.

Which cases does it change.  It's may be necessary to fixup SyntaxGenerator to better generate modifier lists here.

**Comment by sharwell** [comment]
@MaximRouiller 

:bulb: Note that if you ever get to a point where you aren't comfortable, or even just ran out of time, let us know and we can finish items that were mentioned, such as the current refactoring. It's just that if you're working on something already we prefer that you get the credit in the Git history for the full improvements. 👍 

> It works but it changes the order of the keywords for the other tests.

Do you have an example? When this kind of situation arises where the results aren't what was originally expected, sometimes the right answer is to go with the original approach and possibly file a bug to address the changes later.

**Comment by MaximRouiller** [comment]
@CyrusNajmabadi see latest commit.

The code doesn't become invalid. Far from it. But it's not *exactly* the original behavior.

File: src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs [hunk 5]
```diff
@@ -34,7 +34,7 @@ class App : Application
 
 class App : Application
 {
-    public static new App Current { get; set; }
+    public new static App Current { get; set; }
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs]: Interesting.  I'm ok with this change in behavior for now.  But this does indicate an area where SyntaxGenerator does need to be better.  But it's so minor we don't need to fix in this PR.

Comment (MaximRouiller) [inline src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs]: Thank god.

Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Diagnostics/HideBase/HideBaseTests.cs]: :D

**Comment by MaximRouiller** [comment]
Question... would a blog post on this whole process would interest the community?

**Comment by CyrusNajmabadi** [comment]
Absolutely!

**Comment by MaximRouiller** [comment]
Very late but for posterity:

https://blog.decayingcode.com/post/contributing-to-open-source-my-first-roslyn-pull-request-fixing-the-bug/
