### PR TITLE
Don't trigger completion on space next to words

### LINKED ISSUE #1594: Completion List incorrectly invoked on Space between 'new' and Type in ObjectCreationExpression
Paste the below code
```
class Program
{
    static void Main(string[] args)
    {
        var s = new A[] {
           new A  (   new $$B()),
                };
    }
}

public class A
{
    public A(B b)
    {

    }
}

public class B
{
}
```

Now keep pressing spaces at `$$`, the completion list shows up and B gets inserted inspite of B being present already. The resultant looks something like this
```
class Program
{
    static void Main(string[] args)
    {
        var s = new A[] {
           new A  (   new   B        B()),
                };
    }
}

public class A
{
    public A(B b)
    {

    }
}

public class B
{
}
```

 This is a regression from Dev12.

### PR DESCRIPTION
**Pull request by rchande**
Don't trigger preselection when the user types space if the caret is
next to a word.

Fixes #1594 

Reviewers: @balajikris @basoundr @brettfo @dpoeschl @jasonmalinowski @Pilchie 

Note that this isn't for preview.

### CODE REVIEW

File: src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb [hunk 1]
```diff
@@ -1453,5 +1453,37 @@ class C
                 state.AssertNoCompletionSession()
             End Using
         End Sub
+
+        <WorkItem(1594, "https://github.com/dotnet/roslyn/issues/1594")>
+        <Fact, Trait(Traits.Feature, Traits.Features.Completion)>
+        Public Sub NoPreselectionOnSpaceWhenAbuttingWord()
```
Comment (jasonmalinowski) [inline src/EditorFeatures/Test2/IntelliSense/CSharpCompletionCommandHandlerTests.vb]: Should the test be called NoSessionOnSpace... since that's what it's actually asserting?

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by basoundr** [comment]
:+1:

File: src/Features/CSharp/Completion/CompletionProviders/CompletionUtilities.cs [hunk 2]
```diff
@@ -81,7 +81,13 @@ internal static bool IsTriggerAfterSpaceOrStartOfWordCharacter(SourceText text,
...
             // Bring up on space or at the start of a word.
             var ch = text[characterPosition];
-            return ch == ' ' || (CompletionUtilities.IsStartingNewWord(text, characterPosition) && options.GetOption(CompletionOptions.TriggerOnTypingLetters, LanguageNames.CSharp));
+            return SpaceTypedNotAdjacentToWord(ch, text, characterPosition) ||
+                (CompletionUtilities.IsStartingNewWord(text, characterPosition) && options.GetOption(CompletionOptions.TriggerOnTypingLetters, LanguageNames.CSharp));
+        }
+
+        private static bool SpaceTypedNotAdjacentToWord(char ch, SourceText text, int characterPosition)
+        {
+            return ch == ' ' && (characterPosition == text.Length - 1 || !IsWordStartCharacter(text[characterPosition + 1]));
```
Comment (dpoeschl) [inline src/Features/CSharp/Completion/CompletionProviders/CompletionUtilities.cs]: Should this space "adjacent to a word" as well: "word<space>"? Or should "AdjacentTo" just be "Before"?

Comment (rchande) [inline src/Features/CSharp/Completion/CompletionProviders/CompletionUtilities.cs]: "Before". Will update.
