### PR TITLE
Relax compiler server spinwait test

### LINKED ISSUE #11819: [Test failure] Assert.True() failure in DesktopBuildClientTests.ServerTests.ConnectToPipeWithSpinWait
Roslyn-Stabilization-Signed-Release_20160607.1 failed
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
src\Compilers\Server\VBCSCompilerTests\DesktopBuildClientTests.cs(168,0): at
Microsoft.CodeAnalysis.CompilerServer.UnitTests.DesktopBuildClientTests.ServerTests.<ConnectToPipeWithSpinWait>d__11.MoveNext()

### PR DESCRIPTION
**Pull request by agocke**
The test fired cancellation then waited 100ms for cancellation to be acknowledged.
There's no guarantee on a heavily loaded machine that cancellation will be
acknowledged in that time frame. This test should be reliable, so 1s should
provide a very high probability that the test is reflective of the spirit behind it
(that the spin wait is cancellable). Fixes #11819 

/cc @cston @dotnet/roslyn-infrastructure @dotnet/roslyn-compiler 

Note: This is a test-only change.

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
Can this test be written in some way to not have a timeout?

**Comment by agocke** [comment]
@jasonmalinowski I thought about that. The test is basically that, cancellation is possible. The timeout isn't strictly necessary -- we could just wait until it's cancelled and the test will hang if it never does -- but that seemed like a very bad experience, since that has the effect of hanging the test infrastructure.

This seemed like a better alternative.

**Comment by jasonmalinowski** [comment]
We have in the pipe general support for dumping hung unit tests before it's killed. We've traditionally pushed back against these types of changes since it just makes the flakiness less flaky.

I guess my question of "can we not have a timeout" wasn't a question of "must we wait forever" but "can we achieve the same value of test coverage without needing to wait at all?"

**Comment by agocke** [comment]
I'm not sure mocking out this method call any further will be very useful. Plus, that would be a code change, which I hoped to avoid in ask mode if possible.

I'll simply remove the time out, it's not necessary to detect if the call is canceleable.

**Comment by agocke** [comment]
+ @MattGertz for ask mode -- this is a test only change

**Comment by agocke** [comment]
@dotnet/roslyn-infrastructure @dotnet/roslyn-compiler Ping for review

File: src/Compilers/Server/VBCSCompilerTests/DesktopBuildClientTests.cs [hunk 1]
```diff
@@ -150,8 +150,9 @@ public void ConnectToServerFails()
             {
                 // No server should be started with the current pipe name
                 var client = CreateClient();
-                var oneSecondInMs = (int)TimeSpan.FromSeconds(1).TotalMilliseconds;
-                Assert.False(client.TryConnectToNamedPipeWithSpinWait(oneSecondInMs,
+                var oneSec = TimeSpan.FromSeconds(1);
+
+                Assert.False(client.TryConnectToNamedPipeWithSpinWait((int)oneSec.TotalMilliseconds,
                                                                       default(CancellationToken)));
```
Comment (cston) [inline src/Compilers/Server/VBCSCompilerTests/DesktopBuildClientTests.cs]: Is the change from `oneSecondInMs` to `oneSec` needed?

File: src/Compilers/Server/VBCSCompilerTests/DesktopBuildClientTests.cs [hunk 2]
```diff
@@ -160,24 +161,17 @@ public void ConnectToServerFails()
...
                 Assert.False(connection.IsCompleted);
-                // Spin for a little bit
-                await Task.Delay(TimeSpan.FromMilliseconds(100));
                 cts.Cancel();
-                await Task.WhenAny(connection, Task.Delay(TimeSpan.FromMilliseconds(100)))
-                    .ConfigureAwait(false);
-                Assert.True(connection.IsCompleted);
-                Assert.True(connection.IsCanceled);
+                await Assert.ThrowsAnyAsync<OperationCanceledException>(
+                    async () => await connection.ConfigureAwait(false)).ConfigureAwait(false);
```
Comment (cston) [inline src/Compilers/Server/VBCSCompilerTests/DesktopBuildClientTests.cs]: If `connection` is already a `Task`, is ```await Assert.ThrowsAnyAsync<OperationCanceledException>(connection).ConfigureAwait(false);``` sufficient?

**Comment by cston** [comment]
LGTM

**Comment by TyOverby** [comment]
LGTM

File: src/Compilers/Server/VBCSCompilerTests/DesktopBuildClientTests.cs (hunk 2 above)
Comment (agocke) [inline src/Compilers/Server/VBCSCompilerTests/DesktopBuildClientTests.cs]: I tried that, but it appeared that the exception was swallowed in the task object, so it was never witnessed by the call.

File: src/Compilers/Server/VBCSCompilerTests/DesktopBuildClientTests.cs (hunk 1 above)
Comment (agocke) [inline src/Compilers/Server/VBCSCompilerTests/DesktopBuildClientTests.cs]: No, but it seems safe to leave in, to me.
