### PR TITLE
Apply Spacing rules around methodcall inside Attributes

### LINKED ISSUE #776: Formatter: SpaceAfterMethodCallName is ignored in Attribute
I'm talking about space between "[Obsolete" and "("Test")]" in example below.

Notice this is regression in VS2015 compared to VS2013. Assuming this setting equals to VS "Insert space between method name and its opening parenthesis" setting.

```csharp
[Obsolete ("Test")]
class Program
{
    static void Main (string[] args)
    {
    }
}
```

### PR DESCRIPTION
**Pull request by basoundr**
Fix #776 : Apply spacing rules around method call inside attributes as
well

### CODE REVIEW

**Comment by basoundr** [comment]
Potential Reviewers @Pilchie @jasonmalinowski @heejaechang @dpoeschl @rchande @balajikris @brettfo

**Comment by jasonmalinowski** [comment]
:+1:

File: src/Workspaces/CSharp/Portable/Formatting/FormattingHelpers.cs [hunk 1]
```diff
@@ -73,12 +73,14 @@ public static bool IsCloseParenInParameterList(this SyntaxToken token)
 
         public static bool IsOpenParenInArgumentList(this SyntaxToken token)
         {
-            return token.Kind() == SyntaxKind.OpenParenToken && token.Parent.Kind() == SyntaxKind.ArgumentList;
+            return token.Kind() == SyntaxKind.OpenParenToken &&
+                (token.Parent.IsKind(SyntaxKind.ArgumentList) || token.Parent.IsKind(SyntaxKind.AttributeArgumentList));
         }
```
Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Formatting/FormattingHelpers.cs]: You just made a change to deal Parent being null.  Should you use `IsParentKind()` to handle that case?

**Comment by Pilchie** [comment]
Isn't this already handled by PR #1126?

File: src/Workspaces/CSharp/Portable/Formatting/FormattingHelpers.cs (hunk 1 above)
Comment (basoundr) [inline src/Workspaces/CSharp/Portable/Formatting/FormattingHelpers.cs]: @Pilchie The change I made was for `node.Parent` and that has a potential for Parent being a null. This is `token.Parent` which will always be parented. So dont need to perform that check.

I prefer [`IsKind(...)`](http://index/#Microsoft.CodeAnalysis.CSharp/CSharpExtensions.cs,27) since there is just one check rather than [`IsParentKind(...)`](http://index/#Microsoft.CodeAnalysis.CSharp.Workspaces/Extensions/SyntaxNodeExtensions.cs,19) which does a null check and the same check as `IsKind()`

Comment (Pilchie) [inline src/Workspaces/CSharp/Portable/Formatting/FormattingHelpers.cs]: Got it, I think I was confused between this and classification, where we have to be careful before checking parents of tokens, since sometimes we just classify a list of tokens without a tree.

**Comment by basoundr** [comment]
I oversaw this PR. This PR has the same code change but it fails to mention that it also fixed the other 2 spacing options `CSharpFormattingOptions.SpaceAfterMethodCallName`
and `CSharpFormattingOptions.SpaceBetweenEmptyMethodCallParentheses` apart from `CSharpFormattingOptions.SpaceWithinMethodCallParentheses`
