### PR TITLE
Remove UI thread affinitization from snippet info service constructor

### LINKED ISSUE #45723: CSharpSnippetInfoService not initialized
**Version Used**: VS Master (Local, Experimental Host)

**Steps to Reproduce**: No strong repro yet. Occurs when opening a C# file. 

**Stack Trace:**
Microsoft.VisualStudio.Composition.CompositionFailedException: An exception was thrown while initializing part "Microsoft.VisualStudio.LanguageServices.CSharp.Snippets.CSharpSnippetInfoService". ---> System.InvalidOperationException: Unexpected false   at Roslyn.Utilities.Contract.Fail(String message)   at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition)   at Microsoft.CodeAnalysis.Editor.Shared.Utilities.ForegroundThreadAffinitizedObject.AssertIsForeground()   at Microsoft.VisualStudio.LanguageServices.Implementation.Snippets.AbstractSnippetInfoService..ctor(IThreadingContext threadingContext, SVsServiceProvider serviceProvider, Guid languageGuidForSnippets, IAsynchronousOperationListenerProvider listenerProvider)   at Microsoft.VisualStudio.LanguageServices.CSharp.Snippets.CSharpSnippetInfoService..ctor(IThreadingContext threadingContext, SVsServiceProvider serviceProvider, IAsynchronousOperationListenerProvider listenerProvider) --- End of stack trace from previous location where exception was thrown ---   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)   --- End of inner exception stack trace ---   at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.CreateValue()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.Create()   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass55_0.<CreateExport>b__0()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass71_1`2.<GetExports>b__1()   at System.Lazy`1.CreateValue() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at System.Lazy`1.get_Value()   at Microsoft.CodeAnalysis.Host.Mef.MefLanguageServices.GetService[TLanguageService]()   at Microsoft.CodeAnalysis.Completion.CommonCompletionProvider.<TryAddSnippetInvocationPartAsync>d__3.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.CodeAnalysis.Completion.CommonCompletionProvider.<GetDescriptionAsync>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)   at Microsoft.CodeAnalysis.LanguageServer.Handler.CompletionResolveHandler.<HandleRequestAsync>d__1.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass55_0.<CreateExport>b__0()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.<>c__DisplayClass10_0.<UnwrapExport>b__1()   at System.ComponentModel.Composition.Primitives.Export.GetExportedValueCore()   at System.ComponentModel.Composition.Primitives.Export.get_Value()   at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)   at System.ComponentModel.Composition.ExportServices.<>c__DisplayClass11_0`2.<CreateStronglyTypedLazyOfTM>b__1()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService.HACK_AbstractCreateServicesOnUiThread.CreateServicesOnUIThread(IComponentModel componentModel, String languageName)   at Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService.AbstractPackage`2.<LoadComponentsAsync>d__9.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService.AbstractPackage.<LoadComponentsInUIContextOnceSolutionFullyLoadedAsync>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)   at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()   at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass55_0.<CreateExport>b__0()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.VisualStudio.Composition.NetFxAdapters.MefV1ExportProvider.<>c__DisplayClass10_0.<UnwrapExport>b__1()   at System.ComponentModel.Composition.Primitives.Export.GetExportedValueCore()   at System.ComponentModel.Composition.Primitives.Export.get_Value()   at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)   at System.ComponentModel.Composition.ExportServices.<>c__DisplayClass11_0`2.<CreateStronglyTypedLazyOfTM>b__1()   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService.HACK_AbstractCreateServicesOnUiThread.CreateServicesOnUIThread(IComponentModel componentModel, String languageName)   at Microsoft.VisualStudio.LanguageServices.Implementation.LanguageService.HACK_AbstractCreateServicesOnUiThread.Microsoft.VisualStudio.Text.Editor.IWpfTextViewConnectionListener.SubjectBuffersConnected(IWpfTextView textView, ConnectionReason reason, Collection`1 subjectBuffers)   at Microsoft.VisualStudio.Text.Editor.Implementation.ConnectionManager.WpfListener.SubjectBuffersConnected(IWpfTextView textView, ConnectionReason reason, Collection`1 subjectBuffers)   at Microsoft.VisualStudio.Text.Editor.Implementation.ConnectionManager.<>c__DisplayClass7_1.<.ctor>b__1()   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)

CC: @dibarbet

### PR DESCRIPTION
**Pull request by dibarbet**
Removes the UI thread affinitization from snippet info service constructor by using a fire and forget task.  The server was already firing and forgetting the cache population, this just additionally moves the initialization of the VS services to the task instead of the constructor.

Let me know if this approach is correct

Also removed the text buffer initialization hack as this appeared to be the only service being initialized via that method.
Resolves #45723

### CODE REVIEW

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs [hunk 1]
```diff
@@ -109,11 +119,10 @@ public bool SnippetShortcutExists_NonBlocking(string shortcut)
         public virtual bool ShouldFormatSnippet(SnippetInfo snippetInfo)
             => false;
 
-        private void PopulateSnippetCaches()
+        private void PopulateSnippetCaches(IAsyncToken token)
```
Comment (sharwell) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:122]: 💭 It looks like this can be simplified further by making this method asynchronous. It's behaving asynchronously already, but hiding that fact behind a synchronous API.

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs [hunk 2]
```diff
@@ -51,18 +52,26 @@ internal abstract class AbstractSnippetInfoService : ForegroundThreadAffinitized
...
-                {
-                    ComEventSink.Advise<IVsExpansionEvents>(_expansionManager, this);
-                    _waiter = listenerProvider.GetListener(FeatureAttribute.Snippets);
-                    _languageGuidForSnippets = languageGuidForSnippets;
-                    PopulateSnippetCaches();
-                }
+                _waiter = listenerProvider.GetListener(FeatureAttribute.Snippets);
+                _languageGuidForSnippets = languageGuidForSnippets;
+
+                InitializeAndPopulateSnippetsCacheAsync(threadingContext, serviceProvider).Forget();
```
Comment (sharwell) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:60]: 💭 We could really use a `FileAndForget` method (related to #29273)

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs [hunk 3]
```diff
@@ -51,18 +52,26 @@ internal abstract class AbstractSnippetInfoService : ForegroundThreadAffinitized
...
-
             if (serviceProvider != null)
             {
-                var textManager = (IVsTextManager2)serviceProvider.GetService(typeof(SVsTextManager));
-                if (textManager.GetExpansionManager(out _expansionManager) == VSConstants.S_OK)
-                {
-                    ComEventSink.Advise<IVsExpansionEvents>(_expansionManager, this);
-                    _waiter = listenerProvider.GetListener(FeatureAttribute.Snippets);
-                    _languageGuidForSnippets = languageGuidForSnippets;
-                    PopulateSnippetCaches();
```
Comment (sharwell) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:64]: 📝 I was more concerned about this change before I eventually realized that the _implementation_ of `PopulateSnippetCaches` was already operating in a fire-and-forget asynchronous manner. The new code doesn't change this fact, but rather brings it to the surface.

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs (hunk 2 above)
Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:60]: There is one I can import from the VS shell - https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.vstasklibraryhelper.fileandforget?view=visualstudiosdk-2019

Should I use this instead?

Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:60]: Ours should tie into the Roslyn telemetry/NFW infrastructure so we know things are operating in a consistent manner.

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs [hunk 4]
```diff
@@ -51,18 +52,26 @@ internal abstract class AbstractSnippetInfoService : ForegroundThreadAffinitized
...
+                _waiter = listenerProvider.GetListener(FeatureAttribute.Snippets);
+                _languageGuidForSnippets = languageGuidForSnippets;
+
+                InitializeAndPopulateSnippetsCacheAsync(threadingContext, serviceProvider).Forget();
+            }
+        }
+
+        private async Task InitializeAndPopulateSnippetsCacheAsync(IThreadingContext threadingContext, Shell.SVsServiceProvider serviceProvider)
+        {
+            var token = _waiter.BeginAsyncOperation(GetType().Name + ".Start");
```
Comment (sharwell) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:66]:
```suggestion
            using var token = _waiter.BeginAsyncOperation(GetType().Name + ".Start");
```

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs [hunk 5]
```diff
@@ -51,18 +52,26 @@ internal abstract class AbstractSnippetInfoService : ForegroundThreadAffinitized
...
+
+            await threadingContext.JoinableTaskFactory.SwitchToMainThreadAsync();
+
+            var textManager = (IVsTextManager2)serviceProvider.GetService(typeof(SVsTextManager));
```
Comment (sharwell) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:70]:
```suggestion
            var textManager = (IVsTextManager2)await serviceProvider.GetServiceAsync(typeof(SVsTextManager));
            Assumes.Present(textManager);
```

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs [hunk 6]
```diff
@@ -51,18 +52,26 @@ internal abstract class AbstractSnippetInfoService : ForegroundThreadAffinitized
...
+            if (textManager.GetExpansionManager(out _expansionManager) == VSConstants.S_OK)
+            {
+                ComEventSink.Advise<IVsExpansionEvents>(_expansionManager, this);
+                PopulateSnippetCachesAsync().CompletesAsyncOperation(token).Forget();
```
Comment (sharwell) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:74]:
```suggestion
                await PopulateSnippetCachesAsync();
```

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs [hunk 7]
```diff
@@ -109,20 +119,18 @@ public bool SnippetShortcutExists_NonBlocking(string shortcut)
         public virtual bool ShouldFormatSnippet(SnippetInfo snippetInfo)
             => false;
 
-        private void PopulateSnippetCaches()
+        private async Task PopulateSnippetCachesAsync()
         {
             Debug.Assert(_expansionManager != null);
-
-            var token = _waiter.BeginAsyncOperation(GetType().Name + ".Start");
+            AssertIsForeground();
```
Comment (sharwell) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:125]:
```suggestion
            await threadingContext.JoinableTaskFactory.SwitchToMainThreadAsync();
```

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs [hunk 8]
```diff
@@ -109,20 +119,18 @@ public bool SnippetShortcutExists_NonBlocking(string shortcut)
...
             // In Dev14 Update2+ the platform always provides an IExpansion Manager
             var asyncExpansionManager = (IExpansionManager)_expansionManager;
             // Call the asynchronous IExpansionManager API from a background thread
-            Task.Factory.StartNew(() => PopulateSnippetCacheAsync(asyncExpansionManager),
+            await Task.Factory.StartNew(() => PopulateSnippetCacheAsync(asyncExpansionManager),
                             CancellationToken.None,
                             TaskCreationOptions.None,
-                            TaskScheduler.Default).CompletesAsyncOperation(token);
-
+                            TaskScheduler.Default).ConfigureAwait(false);
```
Comment (sharwell) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:133]:
```suggestion
            await TaskScheduler.Default;
            await PopulateSnippetCacheAsync(asyncExpansionManager);
```

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs (hunk 5 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:70]: 📝 You'll need to change the parameter type to `Shell.IAsyncServiceProvider` for this one.

Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:70]: IVsTextManager is not free threaded and casting requires the UI thread - is it still advisable to use GetServiceAsync in this scenario?  Will GetServiceAsync run on the UI thread?

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs (hunk 8 above)
Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:133]: Ah, I tried awaiting the PopulateSnippetCacheAsync regularly, but it didn't go to the background thread - is that what await TaskScheduler.Default is for?

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs (hunk 5 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:70]: We will still switch to the UI thread, but `GetServiceAsync` ensures we will not be blamed if the initialization for the package that provides `SVsTextManager` is slow.

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs (hunk 8 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:133]: Yes, it switches back to a background thread, and then awaits there. 😄

File: src/VisualStudio/Core/Def/Implementation/Options/RoamingVisualStudioProfileOptionPersister.cs [hunk 9]
```diff
@@ -44,7 +44,9 @@ private class SVsSettingsPersistenceManager { };
         private readonly Dictionary<string, List<OptionKey>> _optionsToMonitorForChanges = new Dictionary<string, List<OptionKey>>();
         private readonly object _optionsToMonitorForChangesGate = new object();
 
-        /// <remarks>We make sure this code is from the UI by asking for all serializers on the UI thread in <see cref="HACK_AbstractCreateServicesOnUiThread"/>.</remarks>
+        /// <remarks>
+        /// We make sure this code is from the UI by asking for all <see cref="IOptionPersister"/> in <see cref="RoslynPackage.InitializeAsync"/>
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/Options/RoamingVisualStudioProfileOptionPersister.cs:48]: Thanks for fixing these comments -- I see that code hasn't actually done that for years. :-/

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs (hunk 2 above)
Comment (jasonmalinowski) [reply src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:60]: So what may be better than the true fire-and-forget is to instead add the task into a JointableTaskCollection and wait for that when this MEF component is Disposed; that way this isn't going to risk running unsynchronized during VS shutdown.

Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:60]: Did you mean to Task.Run() this? Otherwise the first bit of InitializeAndPopulateSnippetsCacheAsync may still be running on your UI thread. (It's not really problematic here, but...)

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs [hunk 10]
```diff
@@ -72,7 +81,8 @@ public int OnAfterSnippetsUpdate()
 
             if (_expansionManager != null)
             {
-                PopulateSnippetCaches();
+                var token = _waiter.BeginAsyncOperation(GetType().Name + ".Start");
+                PopulateSnippetCachesAsync().CompletesAsyncOperation(token).Forget();
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:85]: Ditto: consider adding these to a JoinableTaskCollection or the like to avoid random running later.

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs (hunk 7 above)
Comment (jasonmalinowski) [reply src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:125]: Does this actually just need to get deleted? It looks like we're going to the foreground to do a cast but then immediately jumps to the background thread to use it? My hunch is this is a managed object so the UI thread jump isn't necessary at all.

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs [hunk 11]
```diff
@@ -109,20 +119,18 @@ public bool SnippetShortcutExists_NonBlocking(string shortcut)
         public virtual bool ShouldFormatSnippet(SnippetInfo snippetInfo)
             => false;
 
-        private void PopulateSnippetCaches()
+        private async Task PopulateSnippetCachesAsync()
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:122]: What would this look like if we renamed this to QueuePopulateSnippetCaches, it _didn't_ return Task, and then also did the async listener stuff inside of this? Right now every one of the callers has do the same BeginAsyncOperation/CompletesAsyncOperation/Forget dance, and seems we can put that into one single place.

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs (hunk 2 above)
Comment (jasonmalinowski) [reply src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:60]: We do this in other places too for stuff written since we tried to be good citizens on this.

**Comment by jasonmalinowski** [comment]
@dibarbet And so perhaps one last question: what is causing this to all get kicked off anymore? The first invocation of completion is going to import the MEF services and start this whole process, but does that mean the first use of completion won't get snippets because this didn't run yet?

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs (hunk 2 above)
Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:60]: > 
> 
> So what may be better than the true fire-and-forget is to instead add the task into a JointableTaskCollection and wait for that when this MEF component is Disposed; that way this isn't going to risk running unsynchronized during VS shutdown.

I'm not sure I quite understand this comment - do you mean similar to https://github.com/dotnet/roslyn/blob/9625a14e7405d7a3ea1dc77957d5293850b69cc8/src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioActiveDocumentTracker.cs#L42 ?

It seems a little tricky as I'll need to deal with multiple tasks in that collection since it is not just called once from the ctor.

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs (hunk 11 above)
Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:122]: I thought about that, my only concern was that it would then not include the bits switching to the main thread and retrieving the services during initialization.  So then we could have the object be constructed, but the async operation thinks nothing is in progress (if for example we paused on switching to the main thread on line 68)

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs (hunk 7 above)
Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:125]: Yup, per DavidP this should be a machine translated version - so casting should be callable from any thread, but any more complex stuff may not be.

Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:125]: @jasonmalinowski If it's not _documented_ as a managed object, then it's not safe to assume it is.

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs (hunk 2 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:60]: `InitializeAndPopulateSnippetsCacheAsync` immediately yields, so there is no need to do so here.

**Comment by dibarbet** [comment]
> @dibarbet And so perhaps one last question: what is causing this to all get kicked off anymore? The first invocation of completion is going to import the MEF services and start this whole process, but does that mean the first use of completion won't get snippets because this didn't run yet?

Yes, it seems fairly consistently missing snippet results on first completion list opening

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs [hunk 12]
```diff
@@ -81,8 +89,10 @@ public int OnAfterSnippetsUpdate()
 
             if (_expansionManager != null)
             {
-                var token = _waiter.BeginAsyncOperation(GetType().Name + ".Start");
-                PopulateSnippetCachesAsync().CompletesAsyncOperation(token).Forget();
+                _asyncTasks.Add(ThreadingContext.JoinableTaskFactory.RunAsync(async () =>
+                {
+                    await PopulateSnippetCacheAsync().ConfigureAwait(false);
```
Comment (sharwell) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:94]:
```suggestion
                _asyncTasks.Add(ThreadingContext.JoinableTaskFactory.RunAsync(() =>
                {
                    return PopulateSnippetCacheAsync();
```

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs [hunk 13]
```diff
@@ -54,24 +60,26 @@ internal abstract class AbstractSnippetInfoService : ForegroundThreadAffinitized
...
             if (serviceProvider != null)
             {
+                _asyncTasks = new JoinableTaskCollection(threadingContext.JoinableTaskContext);
                 _waiter = listenerProvider.GetListener(FeatureAttribute.Snippets);
                 _languageGuidForSnippets = languageGuidForSnippets;
 
-                InitializeAndPopulateSnippetsCacheAsync(threadingContext, serviceProvider).Forget();
+                _asyncTasks.Add(threadingContext.JoinableTaskFactory.RunAsync(async () =>
+                {
+                    await InitializeAndPopulateSnippetsCacheAsync(threadingContext, (Shell.IAsyncServiceProvider)serviceProvider).ConfigureAwait(false);
```
Comment (sharwell) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:69]: ❗ This cast needs to occur on the main thread.

Comment (sharwell) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs]:
```suggestion
                _asyncTasks.Add(threadingContext.JoinableTaskFactory.RunAsync(() =>
                {
                    return InitializeAndPopulateSnippetsCacheAsync(threadingContext, (Shell.IAsyncServiceProvider)serviceProvider);
```

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs [hunk 14]
```diff
@@ -44,25 +45,42 @@ internal abstract class AbstractSnippetInfoService : ForegroundThreadAffinitized
...
             Guid languageGuidForSnippets,
             IAsynchronousOperationListenerProvider listenerProvider)
             : base(threadingContext)
         {
-            AssertIsForeground();
+            _asyncTasks = new JoinableTaskCollection(threadingContext.JoinableTaskContext);
+            _waiter = listenerProvider.GetListener(FeatureAttribute.Snippets);
+            _languageGuidForSnippets = languageGuidForSnippets;
 
             if (serviceProvider != null)
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:65]: How is this possible for this to be null? Should we #nullable enable the file?

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs [hunk 15]
```diff
@@ -44,25 +45,42 @@ internal abstract class AbstractSnippetInfoService : ForegroundThreadAffinitized
...
-                }
+                    return InitializeAndPopulateSnippetsCacheAsync(threadingContext, serviceProvider);
+                }));
+            }
+        }
+
+        private async Task InitializeAndPopulateSnippetsCacheAsync(IThreadingContext threadingContext, Shell.SVsServiceProvider serviceProvider)
+        {
+            await threadingContext.JoinableTaskFactory.SwitchToMainThreadAsync();
+            var asyncProvider = (Shell.IAsyncServiceProvider)serviceProvider;
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:77]: Consider updating this type to accept the serviceProvider as an IAsyncServiceProvider directly rather than having the cast down here. You may still have to do the cast but at least the requirements of this class are stated at the boundary.

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs [hunk 16]
```diff
@@ -250,6 +260,8 @@ private static void ConvertToStringAndFree(ref IntPtr ptr, ref string str)
             }
         }
 
+        public void Dispose() => _asyncTasks.Join();
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:263]: So looking at the docs, is this correct? My worry being this remark in Join:

> Calling this method when the caller is not executing within a JoinableTask safely no-ops.

I'd be curious which branch this takes:

https://github.com/microsoft/vs-threading/blob/8f1ef716997c51e2eb690e3fe9165da55662e32d/src/Microsoft.VisualStudio.Threading/JoinableTaskCollection.cs#L124-L134

Mind you, if this _doesn't_ work then I have other code to fix as well. :smile:

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs [hunk 17]
```diff
@@ -44,25 +45,42 @@ internal abstract class AbstractSnippetInfoService : ForegroundThreadAffinitized
...
+        private async Task InitializeAndPopulateSnippetsCacheAsync(IThreadingContext threadingContext, Shell.SVsServiceProvider serviceProvider)
+        {
+            await threadingContext.JoinableTaskFactory.SwitchToMainThreadAsync();
+            var asyncProvider = (Shell.IAsyncServiceProvider)serviceProvider;
+
+            var textManager = (IVsTextManager2)await asyncProvider.GetServiceAsync(typeof(SVsTextManager)).ConfigureAwait(true);
+            if (textManager.GetExpansionManager(out _expansionManager) == VSConstants.S_OK)
+            {
+                ComEventSink.Advise<IVsExpansionEvents>(_expansionManager, this);
+                await PopulateSnippetCacheAsync().ConfigureAwait(false);
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:83]: Is there any concern that more than one PopulateSnippetCacheAsync() could be running at the same time?

Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:83]: It was always the case that multiple could be running at the same time (before this change as well) since it just fired off a task.  Since we haven't heard of any issues, and it's running on the UI thread to update the cache we should be safe (there's also locks to update the cache).

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs (hunk 16 above)
Comment (jasonmalinowski) [reply src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:263]: Yep, looks like this pattern is broken. :-/

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs (hunk 15 above)
Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:76]: I'd rather leave it down here - I have to switch to the main thread to cast it.  If I move it up I have to switch before calling this method, but I'd rather leave all the messiness inside it.

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs [hunk 18]
```diff
@@ -136,7 +135,7 @@ private async Task PopulateSnippetCacheAsync()
             Debug.Assert(_expansionManager != null);
 
             // In Dev14 Update2+ the platform always provides an IExpansion Manager
-            var expansionManager = (IExpansionManager)_expansionManager;
+            var expansionManager = (IExpansionManager)_expansionManager!;
```
Comment (sharwell) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:138]: 💡 Use `RoslynDebug.Assert` on the previous line rather than a suppression.

**Comment by sharwell** [comment]
Temporarily marking this blocked on #45850

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs (hunk 15 above)
Comment (jasonmalinowski) [reply src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:76]: Casting things off the UI thread that came from a service provider is a no-no, I'm not aware of any rule about casting the serviceProvider _itself_. Or at least, we're doing this in one place:

https://github.com/dotnet/roslyn/blob/ffb3ca784e92b633f54dcc50f5306aaf945af3d0/src/VisualStudio/Core/Def/Implementation/ProjectSystem/FileChangeWatcherProvider.cs#L25

So if that's a no-no, uh, it's not new. :smile:

File: src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractCreateServicesOnTextViewConnection.cs [hunk 19]
```diff
@@ -15,20 +14,18 @@
...
     {
         private readonly IComponentModel _componentModel;
         private readonly string _languageName;
         private bool _initialized = false;
 
-        public HACK_AbstractCreateServicesOnUiThread(IThreadingContext threadingContext, IServiceProvider serviceProvider, string languageName)
-            : base(threadingContext)
+        public AbstractCreateServicesOnTextViewConnection(IServiceProvider serviceProvider, string languageName)
         {
             _componentModel = (IComponentModel)serviceProvider.GetService(typeof(SComponentModel));
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractCreateServicesOnTextViewConnection.cs:30]: Wait, so this thing gets the IServiceProvider only to go back and get the component model from it? Can we write this with just MEF directly?

File: src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractPackage`2.cs [hunk 20]
```diff
@@ -97,7 +97,7 @@ protected override async Task LoadComponentsAsync(CancellationToken cancellation
             _packageInstallerService?.Connect(this.RoslynLanguageName);
             _symbolSearchService?.Connect(this.RoslynLanguageName);
 
-            HACK_AbstractCreateServicesOnUiThread.CreateServicesOnUIThread(ComponentModel, RoslynLanguageName);
+            AbstractCreateServicesOnTextViewConnection.CreateServices(ComponentModel, RoslynLanguageName);
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractPackage`2.cs:100]: Can we get rid of this at least? Is a view opened on the server for a file?

File: src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractCreateServicesOnTextViewConnection.cs (hunk 19 above)
Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/LanguageService/AbstractCreateServicesOnTextViewConnection.cs:28]: I attempted this - I could not import IComponentModel (composition failed) and did not find anything directly importing it from mef anywhere else.  If you have another way let me know!

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs (hunk 15 above)
Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs]: I can't use [Import(typeof(SVsServiceProvider))] the snippetinfo is using System.Composition for ExportLanguageService - so I just cast it before passing in.

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs [hunk 21]
```diff
@@ -109,26 +113,15 @@ public bool SnippetShortcutExists_NonBlocking(string shortcut)
...
         {
-            Debug.Assert(_expansionManager != null);
-
-            var token = _waiter.BeginAsyncOperation(GetType().Name + ".Start");
+            using var token = _waiter.BeginAsyncOperation(GetType().Name + ".Start");
+            RoslynDebug.Assert(_expansionManager != null);
 
             // In Dev14 Update2+ the platform always provides an IExpansion Manager
-            var asyncExpansionManager = (IExpansionManager)_expansionManager;
+            var expansionManager = (IExpansionManager)_expansionManager;
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:122]: Should this assert we're on the UI thread prior to the cast?

File: src/VisualStudio/CSharp/Impl/Snippets/CSharpSnippetInfoService.cs [hunk 22]
```diff
@@ -31,7 +31,7 @@ internal class CSharpSnippetInfoService : AbstractSnippetInfoService
             IThreadingContext threadingContext,
             SVsServiceProvider serviceProvider,
             IAsynchronousOperationListenerProvider listenerProvider)
-            : base(threadingContext, serviceProvider, Guids.CSharpLanguageServiceId, listenerProvider)
+            : base(threadingContext, (IAsyncServiceProvider)serviceProvider, Guids.CSharpLanguageServiceId, listenerProvider)
```
[the remark this answers is not in the document]
Comment (dibarbet) [reply src/VisualStudio/CSharp/Impl/Snippets/CSharpSnippetInfoService.cs:34]: this appears to be used in other places, e.g. http://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/VisualStudioDecompilerEulaService.cs,31

So unless I hear otherwise I'll keep this

File: src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs (hunk 21 above)
Comment (dibarbet) [reply src/VisualStudio/Core/Def/Implementation/Snippets/AbstractSnippetInfoService.cs:122]: Nope, per DavidP this is machine translated and can be cast on any thread.
