### PR TITLE
Fix for #18978 Cast is redundant on call to params method

### LINKED ISSUE #18978: IDE0004 "Cast is redundant" when casting `object[]` to `object` calling a method that takes `params object[]` changes behavior
**Version Used**: VS2017 15.1 (26403.7)

**Steps to Reproduce**:
```
public static void Main(string[] args)
{
    var takesArgs = new[] { "Hello", "World" };
    TakesParams(takesArgs);
    TakesParams((object)takesArgs);
}

private static void TakesParams(params object[] foo)
{
    Console.WriteLine(foo.Length);
}
```

This correctly prints:
>2
>1

Following the "Cast is redundant" refactoring:
```
public static void Main(string[] args)
{
    var takesArgs = new[] { "Hello", "World" };
    TakesParams(takesArgs);
    TakesParams(takesArgs);
}

private static void TakesParams(params object[] foo)
{
    Console.WriteLine(foo.Length);
}
```

Produces:
>2
>2

### PR DESCRIPTION
**Pull request by MaStr11**
Fixes #18978

### CODE REVIEW

**Comment by Pilchie** [comment]
Thanks for the submission.  Tagging @dotnet/roslyn-ide  for code review.

**Comment by Pilchie** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

File: src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs [hunk 1]
```diff
@@ -161,43 +161,40 @@ private static bool UserDefinedConversionIsAllowed(ExpressionSyntax expression,
             //
             // Foo((object)null);
 
-            if (cast.Expression.WalkDownParentheses().IsKind(SyntaxKind.NullLiteralExpression))
```
Comment (sharwell) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: :memo: The diff does a poor job here. The only actual change is the removal of this `if` condition.

File: src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs [hunk 2]
```diff
@@ -144,7 +144,7 @@ private static bool UserDefinedConversionIsAllowed(ExpressionSyntax expression,
             SemanticModel semanticModel,
             CancellationToken cancellationToken)
         {
-            // Special case: When a null literal is cast and passed as the single argument to a params parameter,
+            // When a casted parameter is passed as the single argument to a params parameter,
             // we can only remove the cast if it is implicitly convertible to the parameter's type,
             // but not the parameter's element type. Otherwise, we could end up changing the invocation
             // to pass a null array rather than an array with a null single element.
```
Comment (sharwell) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: :bulb:

> to pass ~~a null~~ **an** array rather than an array with a ~~null~~ single element.

File: src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs [hunk 3]
```diff
@@ -144,7 +144,7 @@ private static bool UserDefinedConversionIsAllowed(ExpressionSyntax expression,
             SemanticModel semanticModel,
             CancellationToken cancellationToken)
         {
-            // Special case: When a null literal is cast and passed as the single argument to a params parameter,
+            // When a casted parameter is passed as the single argument to a params parameter,
```
Comment (sharwell) [inline src/Workspaces/CSharp/Portable/Extensions/CastExpressionSyntaxExtensions.cs]: 💭 I actually don't know if this should be **cast** or **casted**. But either way, value seems to be more appropriate than parameter so I would suggest the following:

> casted ~~parameter~~ **value**

**Comment by sharwell** [comment]
@MattGertz for ask mode. This is a community member fix for a refactoring operation that can change code behavior where we don't want it to.

## Ask Mode

**Customer scenario**

Customer applies the "Remove redundant cast" refactoring, and code changes behavior unexpectedly.

**Bugs this fixes:**

#18978

**Workarounds, if any**

Disable the diagnostic, or avoid applying a fix all operation without a detailed code review.

**Risk**

Low. Theoretically this change has the capability of introducing a false negative in the diagnostic, but that is preferential to the current false positive being observed.

**Performance impact**

Low. Additional call sites are evaluated within a specific analyzer but the evaluation is efficient. The place where measurable overhead could occur is a Fix All operation for removing unnecessary casts; however, this is the place where it's also most important the results are correct.

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

Failed to consider a language edge case in testing.

**How was the bug found?**

Customer reported.

**Comment by sharwell** [comment]
Congratulations on your first time contribution @MaStr11! 🏅
