### PR TITLE
Verify files are saved after a save operation

### LINKED ISSUE #62109: Integration tests should clearly indicate "failure to save"
Sometimes tests fail to save all documents in response to a Save or Save All command. Execution of these commands should be followed by an automatic verification that the active (or all) documents are saved, and if not fail the test with an easily identifiable error message. This message will help triage test flakiness due to this common problem.

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #62109

### CODE REVIEW

File: src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerVerifierInProcess.cs [hunk 1]
```diff
@@ -2,16 +2,78 @@
...
+            }
+
+            throw new InvalidOperationException("Failed to locate running document table cookie for the active document");
+        }
+
+        public async Task AllDocumentsAreSavedAsync(CancellationToken cancellationToken)
+        {
+            await JoinableTaskFactory.SwitchToMainThreadAsync(cancellationToken);
+            var runningDocumentTable = await GetRequiredGlobalServiceAsync<SVsRunningDocumentTable, IVsRunningDocumentTable>(cancellationToken);
+            var runningDocumentTable3 = await GetRequiredGlobalServiceAsync<SVsRunningDocumentTable, IVsRunningDocumentTable3>(cancellationToken);
```
Comment (dibarbet) [inline src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerVerifierInProcess.cs:58]: Is this better than casting the runningDocumentTable to IVsRunningDocumentTable3?

**Review by dibarbet — APPROVED** [review]

File: src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerVerifierInProcess.cs (hunk 1 above)
Comment (sharwell) [reply src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerVerifierInProcess.cs]: ➡️ Simplified to only need `IVsRunningDocumentTable4`

**Comment by jasonmalinowski** [comment]
@sharwell The platform team is working on async save; have you validated that the approach here is going to be compatible with that?

**Comment by sharwell** [comment]
I have not, but the validation will do a better job of revealing failures caused by any change there than the current code does.

**Comment by sharwell** [comment]
I'm seeing a gold bar for Inheritance Margin:

```
Feature 'Inheritance margin' is currently unavailable due to an internal error.
StreamJsonRpc.RemoteInvocationException: The solution does not contain the specified document.
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__16`1.MoveNext() in /_/src/Workspaces/Remote/Core/BrokeredServiceConnection.cs:line 184
RPC server exception:
System.InvalidOperationException: The solution does not contain the specified document.
      at Microsoft.CodeAnalysis.Shared.Extensions.ISolutionExtensions.GetRequiredDocument(Solution solution, DocumentId documentId) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Workspace/Core/Extensions/ISolutionExtensions.cs:line 48
      at Microsoft.CodeAnalysis.Remote.RemoteInheritanceMarginService.<>c__DisplayClass2_0.<GetInheritanceMarginItemsAsync>b__0(Solution solution) in /_/src/Workspaces/Remote/ServiceHub/Services/InheritanceMargin/RemoteInheritanceMarginService.cs:line 38
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<>c__DisplayClass10_0`1.<<RunWithSolutionAsync>g__TryFastGetSolutionAndRunAsync|0>d.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs:line 161
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<RunWithSolutionAsync>d__10`1.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs:line 133
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Threading.Tasks.ValueTask`1.get_Result()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunWithSolutionAsync>d__11`1.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs:line 92
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__14`1.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs:line 118
```

File: eng/build.ps1 [hunk 2]
```diff
@@ -573,6 +573,9 @@ function Deploy-VsixViaTool() {
   # Disable background download UI to avoid toasts
   &$vsRegEdit set "$vsDir" $hive HKCU "FeatureFlags\Setup\BackgroundDownload" Value dword 0
 
+  # Disable async save
+  &$vsRegEdit set "$vsDir" $hive HKCU "FeatureFlags\VS\RDT\AsyncSave" Value dword 0
```
Comment (jasonmalinowski) [inline eng/build.ps1:577]: Do we need a bug to track this being enabled at some point? Although this is a good stop-gap, we at some point want to actually test our product in the way we ship, right?

File: src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerVerifierInProcess.cs [hunk 3]
```diff
@@ -2,16 +2,73 @@
...
+            foreach (var cookie in runningDocumentTable.GetRunningDocuments())
+            {
+                runningDocumentTable.UpdateDirtyState(cookie);
+                if (runningDocumentTable.IsDocumentDirty(cookie))
+                {
+                    unsavedFiles.Add(runningDocumentTable.GetDocumentMoniker(cookie));
+                }
+            }
+
+            AssertEx.EqualOrDiff("", string.Join(Environment.NewLine, unsavedFiles), "Unexpected dirty documents after failed Save All");
```
Comment (jasonmalinowski) [inline src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerVerifierInProcess.cs:69]: (Not urgent for this PR) We should really have an AssertEx.Empty() since we do this pattern in a few places.

File: src/VisualStudio/Core/Def/ProjectSystem/RunningDocumentTableEventTracker.cs [hunk 4]
```diff
@@ -183,23 +183,11 @@ public IEnumerable<(string moniker, ITextBuffer textBuffer, IVsHierarchy hierarc
 
         private IEnumerable<uint> GetInitializedRunningDocumentTableCookies()
         {
```
Comment (jasonmalinowski) [inline src/VisualStudio/Core/Def/ProjectSystem/RunningDocumentTableEventTracker.cs:185]: Consider moving this too IVsRunningDocumentTableExtensions? You could then reuse it in the SolutionExplorerVerifierInProcess where you do the same checks again.

**Review by jasonmalinowski — DISMISSED** [review]

File: src/VisualStudio/Core/Def/ProjectSystem/Extensions/IVsRunningDocumentTableExtensions.cs [hunk 5]
```diff
@@ -17,5 +15,23 @@ public static bool IsDocumentInitialized(this IVsRunningDocumentTable4 runningDo
 
             return (flags & (uint)_VSRDTFLAGS4.RDT_PendingInitialization) == 0;
         }
+
+        public static IEnumerable<uint> GetRunningDocuments(this IVsRunningDocumentTable3 runningDocumentTable)
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/VisualStudio/Core/Def/ProjectSystem/Extensions/IVsRunningDocumentTableExtensions.cs:19]: ➡️ This name is intentionally chosen to match `GetRunningDocumentsEnum`, since it acts as a managed wrapper around the COM API.

File: src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerInProcess.cs [hunk 6]
```diff
@@ -229,6 +230,10 @@ public async Task RestoreNuGetPackagesAsync(string projectName, CancellationToke
         public async Task SaveAllAsync(CancellationToken cancellationToken)
         {
             await TestServices.Shell.ExecuteCommandAsync(VSConstants.VSStd97CmdID.SaveSolution, cancellationToken);
+            await TestServices.Workspace.WaitForAllAsyncOperationsAsync(new[] { FeatureAttribute.Workspace }, cancellationToken);
```
Comment (jasonmalinowski) [inline src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerInProcess.cs:233]: A comment here would be appreciated: it's odd to see this attached to the workspace since it's not actually the workspace being the origin of any asynchrony here. I'm not sure creating a new feature attribute is any _better_, but we have so many unnecessary waits on the Workspace sprinkled around that this might be culled at some point.

File: src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicLineCommit.cs [hunk 7]
```diff
@@ -99,6 +100,8 @@ End Module
 
             Assert.False(await TestServices.Editor.IsSavedAsync(HangMitigatingCancellationToken));
             await TestServices.Input.SendAsync((VirtualKeyCode.VK_S, VirtualKeyCode.CONTROL));
+            await TestServices.Workspace.WaitForAllAsyncOperationsAsync(new[] { FeatureAttribute.Workspace }, HangMitigatingCancellationToken);
```
Comment (jasonmalinowski) [inline src/VisualStudio/IntegrationTest/New.IntegrationTests/VisualBasic/BasicLineCommit.cs:103]: Ditto to earlier comment request.

File: src/VisualStudio/IntegrationTest/TestSetup/IntegrationTestServiceCommands.cs [hunk 8]
```diff
@@ -127,6 +137,14 @@ private void StartServiceCallback(object sender, EventArgs e)
 
                     var asyncCompletionTracker = componentModel.GetService<AsyncCompletionTracker>();
                     asyncCompletionTracker.StartListening();
+
+#pragma warning disable RS0030 // Do not used banned APIs
+                    await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync();
+#pragma warning restore RS0030 // Do not used banned APIs
```
Comment (jasonmalinowski) [inline src/VisualStudio/IntegrationTest/TestSetup/IntegrationTestServiceCommands.cs:143]: Not really harmful here, but RDT advising for events is explicitly free-threaded.

**Review by jasonmalinowski — APPROVED** [review]
New changes look good; I do request some comments to be added explain that the waits are waiting for asynchronous save since otherwise it looks like we're waiting for other workspace asynchrony that doesn't exist. Given we often have entirely unnecessary waits on the Workspace that get deleted from time to time, a comment here has a pretty good chance of preventing a future problem.

File: src/VisualStudio/IntegrationTest/TestSetup/IntegrationTestServiceCommands.cs (hunk 8 above)
Comment (sharwell) [reply src/VisualStudio/IntegrationTest/TestSetup/IntegrationTestServiceCommands.cs:143]: ➡️ This file is throwaway code (only used by legacy test project which is in the process of migration)

File: eng/build.ps1 (hunk 2 above)
Comment (sharwell) [reply eng/build.ps1]: ➡️ This is already removed

File: src/VisualStudio/Core/Def/ProjectSystem/RunningDocumentTableEventTracker.cs (hunk 4 above)
Comment (sharwell) [reply src/VisualStudio/Core/Def/ProjectSystem/RunningDocumentTableEventTracker.cs:185]: Will leave like this for now, since I only really created the extension method as an `IEnumerable<uint>` adapter for a COM API.

File: src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerInProcess.cs (hunk 6 above)
Comment (sharwell) [reply src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerInProcess.cs:233]: ➡️ Added comment

File: src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerVerifierInProcess.cs (hunk 3 above)
Comment (sharwell) [reply src/VisualStudio/IntegrationTest/New.IntegrationTests/InProcess/SolutionExplorerVerifierInProcess.cs:69]: Make sense, I also did a quick look just to make sure it didn't already exist
