### PR TITLE
Handle bad input expressions for the is-pattern expression.

### LINKED ISSUE #13316: Compiler crashes when using patterns with type name: Unexpected value 'TypeExpression' of type 'BoundKind'
**Version Used**: Visual Studio "15" Previews 3 & 4

**Steps to Reproduce**:

I uncovered this during a typo. Attempt to compile this code:

```cs
using System;

namespace CS7
{
    class T1 { int a; }
    class Program
    {
        static void Main(string[] args)
        {
            if (T1 is object i)
            {
                Console.WriteLine($"Writing O {i}.");
            }
            else { Console.WriteLine($"Writing Not O."); }
        }

    }
}
```

**Expected Behavior**: Compiles successfully.

**Actual Behavior**: Exception thrown:

```
"csc.exe" exited with code -2146232797

Unhandled Exception: System.InvalidOperationException: Unexpected value 'TypeExpression' of type 'Microsoft.CodeAnalysis.CSharp.BoundKind'
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpressionCore(BoundExpression expression, Boolean used)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpression expression, Boolean used)
   at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitAsExpression(BoundAsOperator asOp, Boolean used)
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #13316 

@AlekseyTs @agocke Please review
@dotnet/roslyn-compiler FYI

### CODE REVIEW

**Comment by gafter** [comment]
I've also modified the binding of switches to improve the diagnostics and semantic model.

File: src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs [hunk 1]
```diff
@@ -2556,6 +2556,7 @@ private static bool IsOperandErrors(CSharpSyntaxNode node, BoundExpression opera
                     if (!operand.HasAnyErrors)
                     {
                         Error(diagnostics, ErrorCode.ERR_LambdaInIsAs, node);
+                        operand = new BoundBadExpression(node, LookupResultKind.Empty, ImmutableArray<Symbol>.Empty, ImmutableArray.Create<BoundNode>(operand), CreateErrorType());
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs]: There's a helper method: `operand = BadExpression(node, operand);`

File: src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs [hunk 2]
```diff
@@ -2594,36 +2595,36 @@ private BoundExpression BindIsOperator(BinaryExpressionSyntax node, DiagnosticBa
         {
             var resultType = (TypeSymbol)GetSpecialType(SpecialType.System_Boolean, diagnostics, node);
             var operand = BindValue(node.Left, diagnostics, BindValueKind.RValue);
+            var expressionHasErrors = IsOperandErrors(node, ref operand, diagnostics);
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Operators.cs]: Perhaps `operandHasErrors` to avoid confusing with entire `is` expression.

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 3]
```diff
@@ -13,8 +13,8 @@ partial class Binder
     {
         private BoundExpression BindIsPatternExpression(IsPatternExpressionSyntax node, DiagnosticBag diagnostics)
         {
-            var expression = BindExpression(node.Expression, diagnostics);
-            var hasErrors = node.HasErrors || IsOperandErrors(node, expression, diagnostics);
+            var expression = BindValue(node.Expression, diagnostics, BindValueKind.RValue);
+            var hasErrors = node.HasErrors || IsOperandErrors(node, ref expression, diagnostics) || expression.HasErrors;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: Is `|| expression.HasErrors` necessary? `IsOperandErrors()` returns `expression.HasAnyErrors`.

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 4]
```diff
@@ -160,6 +160,10 @@ internal BoundExpression ConvertPatternExpression(TypeSymbol inputType, CSharpSy
                     // input value among many constant tests.
                     convertedExpression = operand;
                 }
+                else if (conversion.ConversionKind == ConversionKind.NoConversion && convertedExpression.Type?.IsErrorType() == true)
+                {
+                    convertedExpression = operand;
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: When do we hit this case? And by dropping the original `convertedExpression` node, is it possible there are no nodes with `HasErrors` as a result? (Is that an issue?)

Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: Because the converted expression's type is an error type, we've already reported an error. We hit this case when the switch expression (to which the switch case or goto case is converted) is an error, or when the left-hand-side of an is-pattern expression is an error. In those cases we have already reported an error, but it is useful to have the underlying expression of the pattern in the caller so we can, for example, report duplicate case labels, value not constant, etc.

---
In reply to: [76448902](https://github.com/dotnet/roslyn/pull/13382#discussion_r76448902) [](ancestors = 76448902)

**Comment by cston** [comment]
LGTM

**Comment by gafter** [comment]
@dotnet/roslyn-compiler Could I have one more review, please?

**Comment by gafter** [comment]
@AlekseyTs @agocke May I please have a second review of this?

**Comment by agocke** [comment]
LGTM

**Comment by VSadov** [comment]
LGTM
