### PR TITLE
Relax conversion requirements for pattern-matching involving type parameters.

### LINKED ISSUE #16195: Generic expression of a derived type cannot be handled by a pattern
**Version Used**: 
Microsoft Visual Studio Professional 2017 RC
Version 15.0.26014.0 D15REL
Microsoft .NET Framework
Version 4.6.01586
Visual C# Compiler version 2.0.0.61213

**Steps to Reproduce**:

    public class Packet
    {
    }

    public class KeepalivePacket : Packet
    {
    }

    public void Send<T>(T packet)
        where T : Packet
    {
        if (packet is KeepalivePacket keepalive)
        {
            // Do stuff with keepalive
        }

        switch (packet)
        {
            case KeepalivePacket keepalivePacket:
                // Do stuff with keepalivePacket
                break;
        }
    }

I get a compilation error for both the if statement and case statement. 

> CS8121: An expression of type T cannot be handled by a pattern of type KeepalivePacket

The code compiles successfully if the type is _not_ a derived type of `Packet` (ie. `packet is Packet keepalive` or `packet is object keepalive` works fine).

The code compiles without error if I first cast the parameter to `object`.

    if ((object)packet is KeepalivePacket keepalive)
    {
        // This works
    }

I couldn't find any mention of unsupported pattern matching with generic parameters/variables in the design notes/blog posts. 

Is this expected to fail? Does this compilation error need a more informative message?

Roslyn is recommending pattern matching for the following code with **IDE0019**. Applying the code fix to the following code results in the compilation error above.

    var keepalive = packet as KeepalivePacket;
    if (keepalive != null)
    {
        // Do stuff with keepalive
    }

Does **IDE0019** need to be updated to not apply when the variable/parameter is generic?

### PR DESCRIPTION
**Pull request by gafter**
**Customer scenario**

This is a tiny language change for 7.1. See https://github.com/dotnet/csharplang/issues/154.

See #16195 for customer scenario. In short, pattern-matching can give a compile-time error unexpectedly when type parameters are involved. The compiler is correct to give these errors according to the spec, but we wish to relax the language to make it legal.

**Bugs this fixes:**

Fixes #16195

**Workarounds, if any**

Cast the expression being matched to `object`.

**Risk**

Low. This has little impact on existing code.

**Performance impact**

None expected.

**Is this a regression from a previous update?**

No.

### CODE REVIEW

**Comment by gafter** [comment]
@jaredpar Please look at this and determine if it is suitable for 15.3. A number of customers have complained, and the fix is small.

**Comment by CyrusNajmabadi** [comment]
@gafter Is https://github.com/dotnet/roslyn/issues/16993 another manifestation of this issue?

**Comment by gafter** [comment]
This PR is pending a compiler team feature review.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs [hunk 1]
```diff
@@ -175,8 +171,13 @@ BoundExpression MakeIsDeclarationPattern(SyntaxNode syntax, BoundExpression lowe
...
             {
+                // The type here is not a Nullable<T> instance type, as that would have led to the semantic error:
+                // ERR_PatternNullableType: It is not legal to use nullable type '{0}' in a pattern; use the underlying type '{1}' instead.
+                Debug.Assert(!type.IsNullableType());
+
                 // It is possible that the input value is already of the correct type, in which case the pattern
-                // is irrefutable, and we can just do the assignment and return true.
+                // is irrefutable (there is no way for a non-nullable value type to be null), and we can just do
+                // the assignment and return true.
                 if (loweredInput.Type == type)
```
Comment (VSadov) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: This type comparison should ignore dynamic/tuple/modopt differences

Comment (VSadov) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: Essentially if there is an identity conversion, then match is irrefutable.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs [hunk 2]
```diff
@@ -207,18 +208,26 @@ BoundExpression MakeIsDeclarationPattern(SyntaxNode syntax, BoundExpression lowe
...
+                // Because a cast involving a type parameter is not necessarily a valid conversion (or, if it is, it might not
+                // be of a kind appropriate for pattern-matching), we use `object` as an intermediate type for the input expression.
+                var tmpType = _factory.SpecialType(SpecialType.System_Object);
+                var s = _factory.SynthesizedLocal(_factory.SpecialType(SpecialType.System_Boolean), syntax);
+                var i = _factory.SynthesizedLocal(tmpType, syntax); // we copy the input to avoid double evaluation
+                return _factory.Sequence(
+                    ImmutableArray.Create(s, i),
+                    ImmutableArray.Create<BoundExpression>(
+                        _factory.AssignmentExpression(_factory.Local(i), _factory.Convert(tmpType, loweredInput)),
+                        _factory.AssignmentExpression(_factory.Local(s), _factory.Is(_factory.Local(i), type)),
```
Comment (VSadov) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: we should have some tests that validate IL, just to be sure how this is emitted.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: That may be true (the suggested change would be a code improvement), but it is not relevant to the change in the PR.

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a second review? @VSadov I believe the tests you suggested have been added.

@jaredpar May I have permission to merge when reviews are complete?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 3]
```diff
@@ -5674,5 +5674,91 @@ public static void Main(string[] args)
...
+                //         Console.Write(x is T b0);
+                Diagnostic(ErrorCode.ERR_PatternWrongGenericTypeInVersion, "T").WithArguments("Base", "T", "7", "7.1").WithLocation(13, 28),
+                // (16,18): error CS9003: An expression of type 'Base' cannot be handled by a pattern of type 'T' in C# 7. Please use language version 7.1 or greater.
+                //             case T b1:
+                Diagnostic(ErrorCode.ERR_PatternWrongGenericTypeInVersion, "T").WithArguments("Base", "T", "7", "7.1")
+                );
+            compilation = CreateCompilationWithMscorlib45(source, references: new MetadataReference[] { CSharpRef, SystemCoreRef }, options: TestOptions.ReleaseExe, parseOptions: TestOptions.Regular7_1);
+            compilation.VerifyDiagnostics();
+            CompileAndVerify(compilation, expectedOutput: "True1False0");
+        }
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Consider testing types that are not type parameters but where `.ContainsTypeParameter()` is `true`: `T[]`, `A<T>.B`, etc.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs [hunk 4]
```diff
@@ -207,18 +208,26 @@ BoundExpression MakeIsDeclarationPattern(SyntaxNode syntax, BoundExpression lowe
...
+                        _factory.AssignmentExpression(loweredTarget, _factory.Conditional(_factory.Local(s), _factory.Convert(type, _factory.Local(i)), _factory.Default(type), type))
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: >_factory.Local(s) [](start = 90, length = 17)

Can we inline the assignment to ```s``` here?

File: src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs [hunk 5]
```diff
@@ -7612,5 +7612,477 @@ .maxstack  1
...
+}
+class A
+{
+}
+class B : A
+{
+}
+class X : B { }
+";
+            CreateStandardCompilation(source).VerifyDiagnostics(
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs]: >CreateStandardCompilation(source).VerifyDiagnostics( [](start = 12, length = 52)

Consider explicitly using C# 7 version, otherwise this test will break once we bump the default version.

File: src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs [hunk 6]
```diff
@@ -7612,5 +7612,477 @@ .maxstack  1
...
+        {
+            case T t:
+                return t;
+            default:
+                return default(T);
+        }
+    }
+}
+";
+            CreateStandardCompilation(source).VerifyDiagnostics(
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs]: >CreateStandardCompilation(source).VerifyDiagnostics( [](start = 12, length = 52)

Consider explicitly using C# 7 version, otherwise this test will break once we bump the default version.

File: src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs [hunk 7]
```diff
@@ -7612,5 +7612,477 @@ .maxstack  1
...
+        switch (o)
+        {
+            case int t:
+                return t;
+            default:
+                return default(int);
+        }
+    }
+}";
+            CreateStandardCompilation(source).VerifyDiagnostics(
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/SwitchTests.cs]: >CreateStandardCompilation(source).VerifyDiagnostics( [](start = 12, length = 52)

Consider explicitly using C# 7 version, otherwise this test will break once we bump the default version.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 8]
```diff
@@ -5674,5 +5674,91 @@ public static void Main(string[] args)
...
+                Console.Write(1);
+                break;
+            default:
+                Console.Write(0);
+                break;
+        }
+    }
+}
+";
+            var compilation = CreateCompilationWithMscorlib45(source, references: new MetadataReference[] { CSharpRef, SystemCoreRef }, options: TestOptions.ReleaseExe, parseOptions: TestOptions.Regular);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: >var compilation = CreateCompilationWithMscorlib45(source, references: new MetadataReference[] { CSharpRef, SystemCoreRef }, options: TestOptions.ReleaseExe, parseOptions: TestOptions.Regular); [](start = 12, length = 192)

Consider explicitly using C# 7 version, otherwise this test will break once we bump the default version.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 9]
```diff
@@ -5674,5 +5674,91 @@ public static void Main(string[] args)
...
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: >var compilation = CreateCompilationWithMscorlib45(source, references: new MetadataReference[] { CSharpRef, SystemCoreRef }, options: TestOptions.ReleaseExe, parseOptions: TestOptions.Regular); [](start = 12, length = 192)

Consider explicitly using C# 7 version, otherwise this test will break once we bump the default version.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs (hunk 3 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: > Consider testing types that are not type parameters but where .ContainsTypeParameter() is true: T[], A<T>.B, etc.

Yes, please add several tests for scenarios like that.

**Comment by AlekseyTs** [comment]
Done with review pass.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs [hunk 10]
```diff
@@ -260,21 +260,30 @@ private DecisionTree AddByType(DecisionTree decision, TypeSymbol type, DecisionM
                 case DecisionTree.DecisionKind.ByValue:
                     {
                         var byValue = (DecisionTree.ByValue)decision;
+                        DecisionTree result;
                         if (byValue.Default == null)
                         {
-                            byValue.Default = makeDecision(byValue.Expression, byValue.Type);
-                            if (byValue.Default.MatchIsComplete)
+                            if (byValue.Type.Equals(type, TypeCompareKind.IgnoreDynamicAndTupleNames))
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: This is a bug fix to insert a needed conversion.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs [hunk 11]
```diff
@@ -260,21 +260,30 @@ private DecisionTree AddByType(DecisionTree decision, TypeSymbol type, DecisionM
...
                             {
-                                byValue.MatchIsComplete = true;
+                                result = byValue.Default = makeDecision(byValue.Expression, byValue.Type);
+                            }
+                            else
+                            {
+                                byValue.Default = new DecisionTree.ByType(byValue.Expression, byValue.Type, null);
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: This is a bug fix to insert a needed conversion.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs [hunk 12]
```diff
@@ -260,21 +260,30 @@ private DecisionTree AddByType(DecisionTree decision, TypeSymbol type, DecisionM
...
+                                result = AddByType(byValue.Default, type, makeDecision);
                             }
-
-                            return byValue.Default;
                         }
                         else
                         {
-                            Debug.Assert(byValue.Default.Type == type);
-                            return Add(byValue.Default, makeDecision);
+                            result = AddByType(byValue.Default, type, makeDecision);
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: This is a bug fix to insert a needed conversion.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs [hunk 13]
```diff
@@ -93,10 +94,10 @@ private BoundExpression MakeIsDeclarationPattern(BoundDeclarationPattern lowered
 
                 return _factory.Sequence(ImmutableArray.Create(temp),
                          sideEffects: ImmutableArray<BoundExpression>.Empty,
-                         result: MakeIsDeclarationPattern(loweredPattern.Syntax, loweredInput, discard, requiresNullTest: true));
+                         result: MakeIsDeclarationPattern(loweredPattern.Syntax, loweredInput, discard, requiresNullTest: loweredInput.Type.CanContainNull()));
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: This is a bug fix to remove an unneeded null check.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs [hunk 14]
```diff
@@ -93,10 +94,10 @@ private BoundExpression MakeIsDeclarationPattern(BoundDeclarationPattern lowered
...
             }
 
-            return MakeIsDeclarationPattern(loweredPattern.Syntax, loweredInput, loweredPattern.VariableAccess, requiresNullTest: true);
+            return MakeIsDeclarationPattern(loweredPattern.Syntax, loweredInput, loweredPattern.VariableAccess, requiresNullTest: loweredInput.Type.CanContainNull());
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: This is a bug fix to remove an unneeded null check.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs [hunk 15]
```diff
@@ -141,13 +142,36 @@ private BoundExpression CompareWithConstant(BoundExpression input, BoundExpressi
...
         {
             var type = loweredTarget.Type;
+            requiresNullTest = requiresNullTest && !loweredInput.Type.CanContainNull();
 
-            // The type here is not a Nullable<T> instance type, as that would have led to the semantic error:
-            // ERR_PatternNullableType: It is not legal to use nullable type '{0}' in a pattern; use the underlying type '{1}' instead.
-            Debug.Assert(!type.IsNullableType());
+            // It is possible that the input value is already of the correct type, in which case the pattern
+            // is irrefutable, and we can just do the assignment and return true (or perform the null test).
+            if (MatchIsIrrefutable(loweredInput.Type, loweredTarget.Type, requiresNullTest))
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: This is a bug fix to remove an unneeded type test.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs (hunk 4 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Patterns.cs]: Done. But it made no difference in any generated code.

File: src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs [hunk 16]
```diff
@@ -221,7 +221,7 @@ private DecisionTree AddByValue(DecisionTree.ByType byType, BoundConstantPattern
                 var kvp = byType.TypeAndDecision[i];
                 var matchedType = kvp.Key;
                 var decision = kvp.Value;
-                if (matchedType.TupleUnderlyingTypeOrSelf() == value.Value.Type.TupleUnderlyingTypeOrSelf())
+                if (matchedType.Equals(value.Value.Type, TypeCompareKind.IgnoreDynamicAndTupleNames))
```
Comment (cston) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: Please add tests that ignore `dynamic`.

Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: I can't think of a way to make that happen. The is no constant pattern whose type is generic. This could probably be simplified to `(matchedType == value.Value.Type)`.

Comment (gafter) [inline src/Compilers/CSharp/Portable/BoundTree/DecisionTreeBuilder.cs]: Oh, I know a way to make it happen. An enum type nested in a generic class.

**Comment by cston** [comment]
LGTM

**Comment by gafter** [comment]
@agocke or @AlekseyTs Please re-review for my second review. There have been changes since @agocke looked at this.

**Comment by gafter** [comment]
@MeiChin-Tsai @jaredpar for ask-mode approval (once reviews are complete).

**Comment by MeiChin-Tsai** [comment]
Approved once you get code review and tests done. Thanks.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 17]
```diff
@@ -5674,5 +5674,226 @@ public static void Main(string[] args)
...
+    {
+        M<Base>(new Container<Base>.Derived[1]);
+        M<Base>(new Base[1]);
+    }
+    public static void M<T>(T[] x) where T: Base
+    {
+        Console.Write(x is Container<T>.Derived[] b0);
+        switch (x)
+        {
+            case Container<T>.Derived[] b1:
```
Comment (agocke) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Is it legal to use an unbound type here? i.e., `case Container<>.Derived d:`?

Even if not, consider adding a test case for it.

Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Unbound types are an error in type binding everywhere except in a `typeof()`. I don't think we have tests for each place a type can occur.
