### PR TITLE
IDE0028: Added simplifying collection initializer in tuple

### LINKED ISSUE #72169: Missing opportunity for a collection expression in a value tuple
**Version Used**: 
17.10.0 Preview 1.0

**Steps to Reproduce**:
```cs
public (int, List<int>) M() {
  return (42, new List<int>());
}
```

**Diagnostic Id**: none

**Expected Behavior**:
I don't see a reason why the `new List<int>()` expression couldn't be replaced by `[]`, so I expect code analysis to suggest that.
Doing it manually works:
```cs
public (int, List<int>) M() {
  return (42, []);
}
```

**Actual Behavior**:
Nothing is suggested.

### PR DESCRIPTION
**Pull request by victor-pogor**
fixes #72169

https://github.com/dotnet/roslyn/assets/24962085/ed1ab154-1a4b-404a-826a-dfb6fd7c9a55

### CODE REVIEW

File: src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Utilities/SpeculationAnalyzer.cs [hunk 1]
```diff
@@ -773,6 +773,15 @@ bool IsSupportedConstructWithNullType()
                 return true;
             }
 
+            // Similar to above, it's fine for a tuple expression to have a 'null' direct type (as long as a
+            // target-typed tuple-expression conversion happened).  Note: unlike above, we don't have to check
+            // a language version since tuple expressions always supported tuple-expression-conversions.
+            if (newExpression.IsKind(SyntaxKind.TupleExpression) &&
+                this.SpeculativeSemanticModel.GetConversion(newExpression).IsTupleLiteralConversion)
+            {
+                return true;
```
Comment (victor-pogor) [inline src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Utilities/SpeculationAnalyzer.cs:782]: Is there any extra condition needed here? Like:

```c#
SymbolsAreCompatible(originalTypeInfo.Type, newTypeInfo.ConvertedType)
```

I see the tests are working too if having this extra condition

Comment (CyrusNajmabadi) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Utilities/SpeculationAnalyzer.cs:782]: Yes. The types should be validated as well.

Comment (victor-pogor) [reply src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/Utilities/SpeculationAnalyzer.cs:783]: Added

**Comment by victor-pogor** [comment]
Hi @CyrusNajmabadi, could you review this PR please 🌝

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks!
