### PR TITLE
Fixed issue with converting auto properties in partial classes

### LINKED ISSUE #22146: Convert auto property to full property fails for partial types across multiple files
**Version Used**: Latest master as of this posting

**Steps to Reproduce**:

1. Two C# files:

Program.cs:
```C#
partial class Program
{
    int P { get; set; }
}
```

Program2.cs:
```C#
partial class Program
{
    int Q { get; set; }
}
```

2. Try `Convert to full property` on both of the properties.

**Expected Behavior**: Both work

**Actual Behavior**: One works, one throws an exception in the InfoBar:

```
System.ArgumentException : The node is not part of the tree.
Parameter name: node
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.CheckNodeInTree(SyntaxNode node)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.ReplaceNode(SyntaxNode node,Func`3 computeReplacement)
   at async Microsoft.CodeAnalysis.ConvertAutoPropertyToFullProperty.AbstractConvertAutoPropertyToFullPropertyCodeRefactoringProvider.ExpandToFullPropertyAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

### PR DESCRIPTION
**Pull request by chborl**
Fixes #22146

**Customer scenario**
If customer creates a partial class and does the auto property to full property refactoring while in the class that is 2nd in the list, it will throw an error in the info bar

**Bugs this fixes:**
https://github.com/dotnet/roslyn/issues/22146

**Workarounds, if any**
none

**Risk**
Low

**Performance impact**
Low

**Is this a regression from a previous update?**
No

**Root cause analysis:**
Did not consider partial classes.  Will add partial class tests to new features to avoid this error in the future.

**How was the bug found?**
Found by IDE team member

**Test documentation updated?**
n/a

### CODE REVIEW

**Comment by chborl** [comment]
@dotnet/roslyn-ide

File: src/Features/Core/Portable/ConvertAutoPropertyToFullProperty/AbstractConvertAutoPropertyToFullPropertyCodeRefactoringProvider.cs [hunk 1]
```diff
@@ -96,8 +96,12 @@ internal bool IsValidAutoProperty(SyntaxNode property, IPropertySymbol propertyS
                 DeclarationModifiers.From(propertySymbol),
                 propertySymbol.Type, fieldName,
                 initializer: GetInitializerValue(property));
-            var containingType = GetTypeBlock(
-                propertySymbol.ContainingType.DeclaringSyntaxReferences.FirstOrDefault().GetSyntax(cancellationToken));
+
+            //var containingType = GetTypeBlock(
```
Comment (rchande) [inline src/Features/Core/Portable/ConvertAutoPropertyToFullProperty/AbstractConvertAutoPropertyToFullPropertyCodeRefactoringProvider.cs]: oops

File: src/Features/Core/Portable/ConvertAutoPropertyToFullProperty/AbstractConvertAutoPropertyToFullPropertyCodeRefactoringProvider.cs [hunk 2]
```diff
@@ -96,8 +96,12 @@ internal bool IsValidAutoProperty(SyntaxNode property, IPropertySymbol propertyS
...
+            //    propertySymbol.ContainingType.DeclaringSyntaxReferences.FirstOrDefault().GetSyntax(cancellationToken));
+            var containingType = propertySymbol.ContainingType.DeclaringSyntaxReferences
```
Comment (rchande) [inline src/Features/Core/Portable/ConvertAutoPropertyToFullProperty/AbstractConvertAutoPropertyToFullPropertyCodeRefactoringProvider.cs]: SuperNit (tm) containing type makes me think of SemanticModel.EnclosingNamedType, so maybe call this "typeDeclaration" or something?

File: src/Features/Core/Portable/ConvertAutoPropertyToFullProperty/AbstractConvertAutoPropertyToFullPropertyCodeRefactoringProvider.cs [hunk 3]
```diff
@@ -96,8 +96,12 @@ internal bool IsValidAutoProperty(SyntaxNode property, IPropertySymbol propertyS
...
+                    .Select(r => GetTypeBlock(r.GetSyntax(cancellationToken)))
```
Comment (rchande) [inline src/Features/Core/Portable/ConvertAutoPropertyToFullProperty/AbstractConvertAutoPropertyToFullPropertyCodeRefactoringProvider.cs]: Should we be using GetSyntaxAsync as as not to block a thread?

File: src/Features/Core/Portable/ConvertAutoPropertyToFullProperty/AbstractConvertAutoPropertyToFullPropertyCodeRefactoringProvider.cs (hunk 2 above)
Comment (dpoeschl) [reply src/Features/Core/Portable/ConvertAutoPropertyToFullProperty/AbstractConvertAutoPropertyToFullPropertyCodeRefactoringProvider.cs]: :+1:

File: src/Features/Core/Portable/ConvertAutoPropertyToFullProperty/AbstractConvertAutoPropertyToFullPropertyCodeRefactoringProvider.cs [hunk 4]
```diff
@@ -96,8 +96,12 @@ internal bool IsValidAutoProperty(SyntaxNode property, IPropertySymbol propertyS
...
+                    .Single(d => property.Ancestors().Contains(d));
```
Comment (dpoeschl) [inline src/Features/Core/Portable/ConvertAutoPropertyToFullProperty/AbstractConvertAutoPropertyToFullPropertyCodeRefactoringProvider.cs]: Nit: Indented too far.

**Comment by chborl** [comment]
@dotnet/roslyn-ide

**Comment by chborl** [comment]
@Pilchie  for ask mode approval.  Thanks.

**Comment by Pilchie** [comment]
Approved for 15.5 Preview 2.

**Comment by natidea** [comment]
Approved to merge via [507709](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/507709)
