### PR TITLE
Handle recursive patterns in IOperation based GetValueUsageInfo method

### LINKED ISSUE #32271: "Unhandled declaration pattern context" when using switch expressions
Affected Branch: master
Affected Build:  16.0.0 Preview 1.1+ 
Affected Product Language: C#  
Solution: \\\\mlangfs1\public\andrha\ConsoleApp1.zip 
Dump: \\\\mlangfs1\public\andrha\unhandled_decl_dump.dmp

Steps to reproduce:

1. Open zipped solution, specifically Program.cs. 
2. Run VS under debugger with debug Roslyn (I used f5 from Roslyn repo)

### PR DESCRIPTION
**Pull request by mavasani**
Added unit tests for remove unused values analyzer/fix, which invokes this method, and was asserting with the repro in the issue.
Fixes #32271

### CODE REVIEW

File: src/Workspaces/Core/Portable/Extensions/OperationExtensions.cs [hunk 1]
```diff
@@ -57,6 +57,17 @@ public static ValueUsageInfo GetValueUsageInfo(this IOperation operation)
...
+                    case IRecursivePatternOperation _:
+                        // A declaration pattern within a recursive pattern is a
+                        // write for the declared local.
+                        // For example, 'x' is defined and assigned the value from 'obj' below:
+                        //      (obj) switch
+                        //      {
+                        //          (X x) => ...
+                        //      };
+                        //
+                        return ValueUsageInfo.Write;
```
Comment (mavasani) [inline src/Workspaces/Core/Portable/Extensions/OperationExtensions.cs]: This is the only product code change.

**Comment by mavasani** [comment]
@vatsalyaagrawal @jinujoseph for approval

**Comment by mavasani** [comment]
Integration test failures are due to https://github.com/dotnet/roslyn/issues/31739, @sharwell has a PR to fix it.
