### PR TITLE
Do not consider DirectCast(Nothing, <ValueType>) to be equivalent to a default value.

### LINKED ISSUE #2094: DirectCast(Nothing, StructType) should always throw NullReferenceException
```
Structure S
    Function GetS() As S
        Return DirectCast(Nothing, S)
    End Function
End Structure
```
vbc /t:library /optimize- test.vb

**RESULTS:**
```
  .locals init (valuetype S V_0)
  IL_0000:  nop
  IL_0001:  ldloca.s   V_0
  IL_0003:  initobj    S
  IL_0009:  br.s       IL_000b
  IL_000b:  ldloc.0
  IL_000c:  ret
```

**EXPECTED RESULTS:**
```
  .locals init (valuetype S V_0)
  IL_0000:  ldnull
  IL_0001:  unbox.any  S
  IL_0006:  stloc.0
  IL_000b:  br.s       IL_000e
  IL_000d:  ldloc.0
  IL_000e:  ret
```
(or something similar that uses ldnull/unbox.any instead of initobj)

I was quite surprised when I wrote the code above, tested it (with Debug), and later found that it threw a NullReferenceException when compiled for Release.  It should always throw (to avoid these kinds of surprises).

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #2094.

@VSadov, @gafter, @jaredpar, @agocke Please review.

### CODE REVIEW

**Comment by VSadov** [comment]
LGTM

File: src/Compilers/VisualBasic/Portable/BoundTree/BoundExpressionExtensions.vb [hunk 1]
```diff
@@ -39,8 +39,12 @@ Namespace Microsoft.CodeAnalysis.VisualBasic
                     Return constValue IsNot Nothing AndAlso constValue.IsNothing
 
                 Case BoundKind.DirectCast
-                    constValue = DirectCast(node, BoundDirectCast).Operand.ConstantValueOpt
-                    Return constValue IsNot Nothing AndAlso constValue.IsNothing
+                    ' DirectCast(Nothing, <ValueType>) is emitted as an unbox on a null reference.
+                    ' It is not equivalent to a default value
+                    If node.Type.IsTypeParameter() OrElse Not node.Type.IsValueType Then
+                        constValue = DirectCast(node, BoundDirectCast).Operand.ConstantValueOpt
+                        Return constValue IsNot Nothing AndAlso constValue.IsNothing
```
Comment (gafter) [inline src/Compilers/VisualBasic/Portable/BoundTree/BoundExpressionExtensions.vb]: This is my favorite line in all of Roslyn.

**Comment by gafter** [comment]
LGTM
