### PR TITLE
Fix crash in LocalRewriter.GetDefaultParameterValue

### LINKED ISSUE #39868: LocalRewriter crashes on bad default values converted to System.Nullable
When analyzed in IOperation or with `#nullable enable` the following program will crash.

```cs
public struct MyStruct
{
    static void M1(MyStruct? s = default(MyStruct)) { } // error, bad default argument
    static void M2() { M1(); } // crash when analyzing the default argument to M1
}
```

Related to https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1023149/

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #39868

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs [hunk 1]
```diff
@@ -1403,6 +1403,10 @@ private BoundExpression GetDefaultParameterValue(SyntaxNode syntax, ParameterSym
                 // so replace the argument with default(int?).
                 defaultValue = new BoundDefaultExpression(syntax, parameterType) { WasCompilerGenerated = true };
             }
+            else if (defaultConstantValue.IsNull || defaultConstantValue.IsBad)
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: In the `void M(MyStruct? s = default(MyStruct))` scenario, the `defaultConstantValue.IsBad` value is true. This change prevents us from entering the `parameterType.IsNullableType()` branch.

The original code was probably already preventing other kinds of bad default arguments from crashing the compiler--it just hadn't accounted for bad arguments to System.Nullable parameters.

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs [hunk 2]
```diff
@@ -1403,6 +1403,10 @@ private BoundExpression GetDefaultParameterValue(SyntaxNode syntax, ParameterSym
...
+            {
+                defaultValue = MakeLiteral(syntax, defaultConstantValue, parameterType, localRewriter);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: >defaultValue = MakeLiteral(syntax, defaultConstantValue, parameterType, localRewriter); [](start = 16, length = 87)

I think we would want to return BadExpression instead of null literal for ```defaultConstantValue.IsBad```. We wouldn't want to report any nullable warnings for that value, for example.

File: src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IArgument.cs [hunk 3]
```diff
@@ -3678,6 +3678,41 @@ P M1()
...
+
+            string expectedOperationTree = @"
+IExpressionStatementOperation (OperationKind.ExpressionStatement, Type: null) (Syntax: 'M1();')
+    Expression:
+    IInvocationOperation (void MyStruct.M1([MyStruct? s = null])) (OperationKind.Invocation, Type: System.Void) (Syntax: 'M1()')
+        Instance Receiver:
+        null
+        Arguments(1):
+            IArgumentOperation (ArgumentKind.DefaultValue, Matching Parameter: s) (OperationKind.Argument, Type: null, IsImplicit) (Syntax: 'M1()')
+            ILiteralOperation (OperationKind.Literal, Type: MyStruct?, IsImplicit) (Syntax: 'M1()')
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_IArgument.cs]: >ILiteralOperation (OperationKind.Literal, Type: MyStruct?, IsImplicit) (Syntax: 'M1()') [](start = 12, length = 87)

C# doesn't support literals of type ```MyStruct?```.

File: src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs [hunk 4]
```diff
@@ -25953,6 +25953,25 @@ void M6(C? c)
...
         }
 
+        [Fact]
+        [WorkItem(39868, "https://github.com/dotnet/roslyn/issues/39868")]
+        public void BadNullableDefaultArgument()
+        {
+            string source = @"
+public struct MyStruct
+{
+    static void M1(MyStruct? s = default(MyStruct)) { } // 1
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Semantic/Semantics/NullableReferenceTypesTests.cs]: >MyStruct? [](start = 19, length = 9)

Please add a test for scenario when this is a not nullable reference type and the default value is bad.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1)

File: src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs [hunk 5]
```diff
@@ -1403,6 +1403,14 @@ private BoundExpression GetDefaultParameterValue(SyntaxNode syntax, ParameterSym
                 // so replace the argument with default(int?).
                 defaultValue = new BoundDefaultExpression(syntax, parameterType) { WasCompilerGenerated = true };
             }
+            else if (defaultConstantValue.IsNull)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_Call.cs]: >else if (defaultConstantValue.IsNull) [](start = 12, length = 37)

Consider combining this ```if``` with the previous one for clarity:
```
            else if (defaultConstantValue.IsNull)
            {
                if (parameterType.IsValueType || (parameterType.IsNullableType() && parameterType.IsErrorType())))
                {
                    // We have something like M(int? x = null) or M(S x = default(S)),
                    // so replace the argument with default(int?).
                    defaultValue = new BoundDefaultExpression(syntax, parameterType) { WasCompilerGenerated = true };
                }
                else
                {
                    defaultValue = MakeLiteral(syntax, defaultConstantValue, parameterType, localRewriter);
                }
            }
```
