### PR TITLE
Make local function default parameter value binding lazy

### LINKED ISSUE #16451: Compiler crash with recursive local function parameter default value
Typing the following code into a C# project causes VS to crash (stack overflow in the compiler).

```cs
class C
{
    public static void Main(int arg)
    {
        int Local(int x = Local()) => 2;
    }
}
```

### PR DESCRIPTION
**Pull request by agocke**
Current strict binding can cause circularity problems when local
functions are referenced. This change causes local functions to use lazy
default parameter binding, similar to methods, and then forces their
construction when diagnostics are requested for the local function.

This also requires a mechanism for recording declaration diagnostics
outside of adding to the compilation's DeclarationDiagnostics. A new
type, DeclarationDiagnosticStore is introduced as an abstraction to
store declaration diagnostics on either the compilation or in a local
DiagnosticBag, depending on the needs of the symbol storing diagnostics.

Fixes #16451

### CODE REVIEW

**Comment by agocke** [comment]
/cc @dotnet/roslyn-compiler 

The first commit is just a refactoring, so I would advise reviewing commit-by-commit.

File: src/Compilers/CSharp/Portable/Utilities/DeclarationDiagnosticBag.cs [hunk 1]
```diff
@@ -0,0 +1,46 @@
+﻿using System;
+using System.Diagnostics;
+
+namespace Microsoft.CodeAnalysis.CSharp
+{
+    /// <summary>
+    /// Takes declaration diagnostics and either stores them directly or acts as a proxy to the compilation's
+    /// <see cref="CSharpCompilation.DeclarationDiagnostics"/>, depending on construction.
+    /// </summary>
+    internal struct DeclarationDiagnosticStore
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Utilities/DeclarationDiagnosticBag.cs]: This seems like a lazy `DiagnosticBag`. Perhaps rename to something more general such as `DiagnosticBagProvider`. Or better yet, does this even need to be lazy? Could the callers simply pass in `Compilation.DeclarationDiagnostics` in the cases where that `DiagnosticBag` should be used?

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs [hunk 2]
```diff
@@ -109,49 +81,47 @@ internal ReturnTypeAndDiagnostics(TypeSymbol returnType, ImmutableArray<Diagnost
         /// </summary>
         internal Binder ScopeBinder { get; }
 
+        public Binder ParameterBinder => _binder;
+
         internal void GetDeclarationDiagnostics(DiagnosticBag addTo)
         {
-            // Force attribute binding for diagnostics
-            foreach (var typeParam in _typeParameters)
+            lock (_lazyLock)
```
Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: Is there a risk of deadlock now?

File: src/Compilers/CSharp/Portable/Utilities/DeclarationDiagnosticBag.cs [hunk 3]
```diff
@@ -0,0 +1,46 @@
...
+
+        public void Add(ErrorCode err, Location location) => Bag.Add(err, location);
+
+        public void AddRange(DiagnosticBag diagnostics) => Bag.AddRange(diagnostics);
+
+        public DiagnosticBag Bag
+        {
+            get
+            {
+                var bag = _compilationOpt?.DeclarationDiagnostics ?? _backingBagOpt;
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Utilities/DeclarationDiagnosticBag.cs]: >_compilationOpt?.DeclarationDiagnostics ?? _backingBagOpt [](start = 26, length = 57)

I don't understand why this entire class can't be replaced by the caller storing the appropriate diagnostic bag.

File: src/Compilers/CSharp/Portable/Utilities/DeclarationDiagnosticBag.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Utilities/DeclarationDiagnosticBag.cs]: >DeclarationDiagnosticStore [](start = 20, length = 26)

File name and class name disagree.

File: src/Compilers/CSharp/Portable/Utilities/DeclarationDiagnosticBag.cs (hunk 3 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Utilities/DeclarationDiagnosticBag.cs]: Fair enough, I'll refactor.

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs (hunk 2 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: Between which threads?

Comment (cston) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: Does the public API allow binding the same method body from multiple threads? If so, could binding two mutually dependent local functions lead to a deadlock? 

More generally, is the change to use `lock` necessary? Does it handle a case that the `Interlocked.CompareExchange` approach was not handling?

File: src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs [hunk 4]
```diff
@@ -353,14 +353,7 @@ internal virtual void PostDecodeWellKnownAttributes(ImmutableArray<CSharpAttribu
...
                 this.RecordPresenceOfBadAttributes(boundAttributes);
-                if (addToDiagnostics == null)
-                {
-                    this.AddDeclarationDiagnostics(diagnostics);
-                }
-                else
-                {
-                    addToDiagnostics.AddRange(diagnostics);
-                }
+                declarationDiagnostics.AddRange(diagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs]: >declarationDiagnostics.AddRange(diagnostics); [](start = 16, length = 45)

Can we get rid of ```declarationDiagnostics``` parameter and simply ```call this.AddDeclarationDiagnostics(diagnostics)```?

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs (hunk 2 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: Yes -- without the lock there's no synchronization on adding the diagnostics to the bag. You could end up with two threads calling GetDeclarationDiagnostics and them each adding duplicate declaration diagnostics to the bag.

File: src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs (hunk 4 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs]: If we are loading attributes on a local function parameter then that would add the diagnostics to the declaration diagnostics, which this PR is trying to avoid.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs]: Why don't we override AddDeclarationDiagnostics for the parameter? What is the purpose of making it virtual?

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs [hunk 5]
```diff
@@ -13,55 +13,26 @@ namespace Microsoft.CodeAnalysis.CSharp.Symbols
...
+        private TypeSymbol _lazyReturnType;
         private TypeSymbol _iteratorElementType;
-        private ImmutableArray<Diagnostic> _diagnostics;
+
+        private readonly DiagnosticBag _declarationDiagnostics;
+
+        // Lock for initializing lazy fields and registering their diagnostics
+        // Acquire this lock when initializing lazy objects to guarantee their declaration
+        // diagnostics get added to the store exactly once
+        private readonly object _lazyLock = new object();
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: >private readonly object _lazyLock = new object(); [](start = 8, length = 49)

It feels wasteful to use extra field and a an extra allocation for this, can we simply lock the _declarationDiagnostics?

File: src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs (hunk 4 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs]: AddDeclarationDiagnostics is currently on Symbol. I could push down the property I introduced (DeclarationDiagnostics) to Symbol, if you prefer. Then AddDeclarationDiagnostics could use that property.

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs (hunk 5 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: I was worried that `DiagnosticBag` would lock `this`. I didn't check if it did, though.

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs [hunk 6]
```diff
@@ -109,49 +80,47 @@ internal ReturnTypeAndDiagnostics(TypeSymbol returnType, ImmutableArray<Diagnost
...
-            // Force attribute binding for diagnostics
-            foreach (var typeParam in _typeParameters)
+            lock (_lazyLock)
             {
-                typeParam.GetAttributesBag(addTo);
-            }
+                // Force attribute binding for diagnostics
+                foreach (var typeParam in _typeParameters)
+                {
+                    typeParam.GetAttributesBag(_declarationDiagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: >typeParam.GetAttributesBag(_declarationDiagnostics) [](start = 20, length = 51)

It feels like we should simply call force complete on each type parameter and that should take care of adding diagnostics to the right bag ensuring that there would be no duplicates. The lock is not need then.

File: src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs (hunk 4 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Symbol_Attributes.cs]: This code is inside Symbol. I am assuming it is called of off symbol, which is the target of the attribute.

**Comment by agocke** [comment]
@AlekseyTs I've refactored the PR with your suggestions

**Comment by AlekseyTs** [comment]
@agocke Could you, please, do a proper re-base so that the PR wouldn't include 250+ commits?

**Comment by agocke** [comment]
@AlekseyTs Done

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs [hunk 7]
```diff
@@ -108,49 +77,39 @@ internal ReturnTypeAndDiagnostics(TypeSymbol returnType, ImmutableArray<Diagnost
...
-                {
-                    addTo.AddRange(_lazyTypeParameterConstraintsAndDiagnostics.Diagnostics);
-                }
-                addTo.AddRange(_lazyReturnTypeAndDiagnostics.Diagnostics);
-            }
+            addTo.AddRange(_declarationDiagnostics);
         }
 
+        internal override void AddDeclarationDiagnostics(DiagnosticBag diagnostics)
+            => _declarationDiagnostics.AddRange(diagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: >_declarationDiagnostics.AddRange(diagnostics) [](start = 15, length = 45)

Would there be an advantage of checking diagnostics.IsEmptyWithoutResolution before calling AddRange?

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs [hunk 8]
```diff
@@ -159,48 +118,43 @@ public override ImmutableArray<ParameterSymbol> Parameters
...
         }
 
         private void ComputeParameters()
         {
-            if (_lazyParametersAndDiagnostics != null)
+            lock (_declarationDiagnostics)
             {
-                return;
-            }
+                if (_lazyParameters != null)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: >if (_lazyParameters != null) [](start = 16, length = 28)

This check can be moved out of the ```lock```.

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs [hunk 9]
```diff
@@ -159,48 +118,43 @@ public override ImmutableArray<ParameterSymbol> Parameters
...
                 ComputeParameters();
-                return _lazyParametersAndDiagnostics.Parameters;
+                return _lazyParameters;
             }
         }
 
         private void ComputeParameters()
         {
-            if (_lazyParametersAndDiagnostics != null)
+            lock (_declarationDiagnostics)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: >lock (_declarationDiagnostics) [](start = 12, length = 30)

To avoid possibility of getting into a dead-lock situations it is probably better to calculate everything into locals, including collecting diagnostics into a local bag, and then only store the result while the lock is taken.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs [hunk 10]
```diff
@@ -8,7 +8,6 @@
 using System.Linq;
 using System.Reflection;
 using System.Threading;
-using Microsoft.CodeAnalysis.CSharp.Emit;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceAssemblySymbol.cs]: This is the only change in the file. Please revert to keep the number of affected files smaller.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs [hunk 11]
```diff
@@ -27,11 +27,14 @@ private enum ParameterSyntaxKind : byte
...
         private readonly ParameterSyntaxKind _parameterSyntaxKind;
+        // Used for publishing lazy values and their diagnostics simultaneously
+        private readonly object _lazyLock = new object();
 
         private CustomAttributesBag<CSharpAttributeData> _lazyCustomAttributesBag;
         private ThreeState _lazyHasOptionalAttribute;
         protected ConstantValue _lazyDefaultSyntaxValue;
 
+
         internal SourceComplexParameterSymbol(
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs]: An unnecessary empty line.

**Comment by AlekseyTs** [comment]
>                 var parameterType = binder.BindType(parameterSyntax.Type, diagnostics);

Could eagerly binding the type cause similar problem?

---
Refers to: src/Compilers/CSharp/Portable/Symbols/Source/ParameterHelpers.cs:60 in 2b5fb44. [](commit_id = 2b5fb4496087e74b70c16b6a3fa2796177c23191, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs [hunk 12]
```diff
@@ -201,9 +137,15 @@ private ConstantValue DefaultSyntaxValue
                 if (_lazyDefaultSyntaxValue == ConstantValue.Unset)
                 {
                     var diagnostics = DiagnosticBag.GetInstance();
-                    if (Interlocked.CompareExchange(ref _lazyDefaultSyntaxValue, MakeDefaultExpression(diagnostics, ParameterBinder), ConstantValue.Unset) == ConstantValue.Unset)
+                    var defaultSyntaxValue = MakeDefaultExpression(diagnostics, ParameterBinderOpt);
+
+                    lock (_lazyLock)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs]: >lock (_lazyLock) [](start = 20, length = 16)

It is not clear why original synchronization is in sufficient for local functions. Could you elaborate please?

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs [hunk 13]
```diff
@@ -447,24 +377,38 @@ internal sealed override CustomAttributesBag<CSharpAttributeData> GetAttributesB
...
+                    }
+
                     state.NotePartComplete(CompletionPart.Attributes);
                 }
             }
 
             return _lazyCustomAttributesBag;
         }
 
+        private void ReportLocalFuncAttributeErrors(LocalFunctionSymbol localFunc)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceComplexParameterSymbol.cs]: >private void ReportLocalFuncAttributeErrors(LocalFunctionSymbol localFunc) [](start = 8, length = 74)

It doesn't look like this function is used.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceConstructorSymbol.cs [hunk 14]
```diff
@@ -76,7 +76,11 @@ protected override void MethodChecks(DiagnosticBag diagnostics)
             var bodyBinder = binderFactory.GetBinder(parameterList, syntax, this).WithContainingMemberOrLambda(this);
 
             SyntaxToken arglistToken;
-            _lazyParameters = ParameterHelpers.MakeParameters(bodyBinder, this, parameterList, true, out arglistToken, diagnostics, false);
+            _lazyParameters = ParameterHelpers.MakeParameters(
+                bodyBinder, this, parameterList, out arglistToken,
+                allowRefOrOut: true, allowThis: false,
+                diagnostics: DeclaringCompilation.DeclarationDiagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceConstructorSymbol.cs]: >DeclaringCompilation.DeclarationDiagnostics [](start = 29, length = 43)

It feels like we should continue using ```diagnostics``` here.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceDelegateMethodSymbol.cs [hunk 15]
```diff
@@ -245,7 +245,11 @@ private sealed class InvokeMethod : SourceDelegateMethodSymbol
                 this.refKind = refKind;
 
                 SyntaxToken arglistToken;
-                var parameters = ParameterHelpers.MakeParameters(binder, this, syntax.ParameterList, true, out arglistToken, diagnostics, false);
+                var parameters = ParameterHelpers.MakeParameters(
+                    binder, this, syntax.ParameterList, out arglistToken,
+                    allowRefOrOut: true, allowThis: false,
+                    diagnostics: DeclaringCompilation.DeclarationDiagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceDelegateMethodSymbol.cs]: >DeclaringCompilation.DeclarationDiagnostics [](start = 33, length = 43)

Should keep using ```diagnostics```.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs [hunk 16]
```diff
@@ -4,12 +4,9 @@
 using System.Diagnostics;
 using System.Globalization;
 using System.Threading;
-using Microsoft.CodeAnalysis.CSharp.Symbols;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceEventSymbol.cs]: Please remove this file from PR, the changes are unrelated.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceFieldSymbol.cs [hunk 17]
```diff
@@ -202,6 +200,7 @@ private CustomAttributesBag<CSharpAttributeData> GetAttributesBag()
                 return bag;
             }
 
+            var declarationDiagnostics = DeclaringCompilation.DeclarationDiagnostics;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceFieldSymbol.cs]: >var declarationDiagnostics = DeclaringCompilation.DeclarationDiagnostics; [](start = 12, length = 73)

It doesn't look like this change is needed and there are no other changes in this file that are related to the purpose of this PR. Please revert/remove from the PR.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberMethodSymbol.cs [hunk 18]
```diff
@@ -135,7 +135,11 @@ private void MethodChecks(MethodDeclarationSyntax syntax, Binder withTypeParamsB
             // instance). Constraints are checked in AfterAddingTypeMembersChecks.
             var signatureBinder = withTypeParamsBinder.WithAdditionalFlagsAndContainingMemberOrLambda(BinderFlags.SuppressConstraintChecks, this);
 
-            _lazyParameters = ParameterHelpers.MakeParameters(signatureBinder, this, syntax.ParameterList, true, out arglistToken, diagnostics, false);
+            _lazyParameters = ParameterHelpers.MakeParameters(
+                signatureBinder, this, syntax.ParameterList, out arglistToken,
+                allowRefOrOut: true, allowThis: true,
+                diagnostics: DeclaringCompilation.DeclarationDiagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberMethodSymbol.cs]: >DeclaringCompilation.DeclarationDiagnostics [](start = 29, length = 43)

Should keep using ```diagnostics```.

File: src/Compilers/CSharp/Portable/Symbols/Source/ParameterHelpers.cs [hunk 19]
```diff
@@ -16,10 +16,10 @@ internal static class ParameterHelpers
             Binder binder,
             Symbol owner,
             BaseParameterListSyntax syntax,
-            bool allowRefOrOut,
             out SyntaxToken arglistToken,
-            DiagnosticBag diagnostics,
-            bool beStrict)
+            bool allowRefOrOut,
+            bool allowThis,
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/ParameterHelpers.cs]: >bool allowThis, [](start = 12, length = 15)

It looks like this parameter is not used, please remove.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs [hunk 20]
```diff
@@ -89,6 +89,7 @@ internal sealed class SourcePropertySymbol : PropertySymbol, IAttributeTargetSym
                 // always use the real attribute bag of this symbol and modify LoadAndValidateAttributes to
                 // handle partially filled bags.
                 CustomAttributesBag<CSharpAttributeData> temp = null;
+                var declarationDiagnostics = DeclaringCompilation.DeclarationDiagnostics;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs]: >var declarationDiagnostics = DeclaringCompilation.DeclarationDiagnostics; [](start = 16, length = 73)

This change doesn't look meaningful.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs [hunk 21]
```diff
@@ -751,7 +752,10 @@ private static ImmutableArray<ParameterSymbol> MakeParameters(Binder binder, Sou
             }
 
             SyntaxToken arglistToken;
-            var parameters = ParameterHelpers.MakeParameters(binder, owner, parameterSyntaxOpt, false, out arglistToken, diagnostics, false);
+            var parameters = ParameterHelpers.MakeParameters(
+                binder, owner, parameterSyntaxOpt, out arglistToken,
+                allowRefOrOut: false, allowThis: false,
+                diagnostics: owner.DeclaringCompilation.DeclarationDiagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs]: >owner.DeclaringCompilation.DeclarationDiagnostics [](start = 29, length = 49)

Should keep using ```diagnostics```.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs [hunk 22]
```diff
@@ -179,19 +177,24 @@ internal virtual CustomAttributesBag<CSharpAttributeData> GetAttributesBag(Diagn
...
+                    CustomAttributesBag<CSharpAttributeData> attributesBag = typeParameter.GetAttributesBag();
 
                     lazyAttributesStored = Interlocked.CompareExchange(ref _lazyCustomAttributesBag, attributesBag, null) == null;
                 }
 
                 if (lazyAttributesStored)
                 {
+                    if (ContainingSymbol is LocalFunctionSymbol localFunc)
+                    {
+                        var attributes = ((TypeParameterSyntax)_syntaxRefs[0].GetSyntax()).AttributeLists;
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs]: >[0] [](start = 74, length = 3)

Use ```Single()``` instead because you are making an assumption that there is only one syntax reference.

**Comment by AlekseyTs** [comment]
>     internal sealed class LocalFunctionTypeParameterSymbol : SourceTypeParameterSymbolBase

It feels like this class duplicates a lot of code. We should be able to reuse SourceMethodTypeParameterSymbol. Please open an issue to track this work.

---
Refers to: src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs:454 in 2b5fb44. [](commit_id = 2b5fb4496087e74b70c16b6a3fa2796177c23191, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedOperatorSymbolBase.cs [hunk 23]
```diff
@@ -128,10 +128,10 @@ protected override void MethodChecks(DiagnosticBag diagnostics)
                 signatureBinder,
                 this,
                 ParameterListSyntax,
-                true,
                 out arglistToken,
-                diagnostics,
-                false);
+                allowRefOrOut: true,
+                allowThis: false,
+                diagnostics: DeclaringCompilation.DeclarationDiagnostics);
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceUserDefinedOperatorSymbolBase.cs]: >DeclaringCompilation.DeclarationDiagnostics [](start = 29, length = 43)

Should keep using ```diagnostics```.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs [hunk 24]
```diff
@@ -2242,7 +2242,7 @@ static int B(int val)
     }
     static object D(object val)
     {
-        T Local<T>(T valu) where T : object
+        T Local<T>(T valu) where T : class
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs]: >class [](start = 37, length = 5)

What is the reason behind this change?

**Comment by AlekseyTs** [comment]
Done with review pass.

File: src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs (hunk 7 above)
Comment (agocke) [inline src/Compilers/CSharp/Portable/Symbols/Source/LocalFunctionSymbol.cs]: `AddRange` checks this.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs (hunk 24 above)
Comment (agocke) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs]: The former is illegal C# code. The diagnostics started showing up after my change. :)

**Comment by agocke** [comment]
@AlekseyTs I don't think binding the type when constructing the parameters can create the same problem -- I don't think type binding can cause method body binding, so it shouldn't depend on binding local functions either.

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs (hunk 24 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenLocalFunctionTests.cs]: Dis you add a test for the error scenario elsewhere? Please do.

**Comment by AlekseyTs** [comment]
@agocke If you re-target this PR to master, you might want to address #17293 in this PR.

**Comment by cston** [comment]
LGTM

**Comment by gafter** [comment]
>             state.NotePartComplete(part);

There appears to be a race condition here. The part should only be completed here if the bag was completed on this thread. Otherwise we should wait for the part to be completed.

---
Refers to: src/Compilers/CSharp/Portable/Symbols/Source/SourceMethodSymbol.cs:939 in 1e97cc0. [](commit_id = 1e97cc09cd5b660bc3f230b310716a6c7808c383, deletion_comment = False)

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs [hunk 25]
```diff
@@ -179,19 +178,24 @@ internal virtual CustomAttributesBag<CSharpAttributeData> GetAttributesBag(Diagn
...
                     var typeParameter = (SourceTypeParameterSymbolBase)sourceMethod.SourcePartialDefinition.TypeParameters[_ordinal];
-                    CustomAttributesBag<CSharpAttributeData> attributesBag = typeParameter.GetAttributesBag(diagnosticsOpt);
+                    CustomAttributesBag<CSharpAttributeData> attributesBag = typeParameter.GetAttributesBag();
 
                     lazyAttributesStored = Interlocked.CompareExchange(ref _lazyCustomAttributesBag, attributesBag, null) == null;
                 }
 
                 if (lazyAttributesStored)
                 {
+                    if (ContainingSymbol is LocalFunctionSymbol localFunc)
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs]: >if [](start = 20, length = 2)

It is uncomfortable seeing the implementation of local functions leak down to this shared helper. Since this could be done as a purely syntactic check, would it make sense moving it closer to its symbol type and reporting the error eagerly?

Comment (gafter) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs]: >if [](start = 20, length = 2)

It feels uncomfortable to see the implementation of local functions leaking down to this shared helper. Since this could be a purely syntactic check, would it make sense to do it eagerly closer to local function's implementation type?

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests_Global.cs [hunk 26]
```diff
@@ -6108,5 +6108,1861 @@ class H
             Assert.Null(model.GetAliasInfo(x1.Type));
         }
 
+        [Fact]
```
Comment (gafter) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests_Global.cs]: >Fact [](start = 9, length = 4)

I suspect I am seeing these changes due to branches changing.

File: src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs (hunk 25 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Symbols/Source/SourceTypeParameterSymbol.cs]: Sorry for the duplicate comment. CodeFlow isn't cooperating.
