### PR TITLE
Fix for LSP diagnostic bugs

### LINKED ISSUE #41029: [LSP] Diagnostic squiggles don't appear for client until edits are made
Repro - Have a file with diagnostic errors / warning / info in a sln.  Open the file as a liveshare guest.  Notice that squiggles are missing until an edit is made.

This is likely because joining a liveshare session and opening the document on the client will not trigger the server to recompute diagnostics - http://sourceroslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/LanguageClient/InProcLanguageServer.cs,151 

Likely need some way to force publish when the client opens the document.

### PR DESCRIPTION
**Pull request by allisonchou**
Fixes bug where IDE info diagnostics are reported as warnings with purple squiggles (https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1062989).

Also partially fixes #41029, pending a bug fix from LSP side (https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1067885).

### CODE REVIEW

File: src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs [hunk 1]
```diff
@@ -167,7 +167,7 @@ public static LSP.DiagnosticSeverity DiagnosticSeverityToLspDiagnositcSeverity(D
                 case DiagnosticSeverity.Hidden:
                     return LSP.DiagnosticSeverity.Hint;
                 case DiagnosticSeverity.Info:
-                    return LSP.DiagnosticSeverity.Information;
+                    return LSP.DiagnosticSeverity.Hint;
```
Comment (JoeRobich) [inline src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs]: Maybe add a comment as to why we are returning `Hint` here and link to an issue tracking this being reverted.

File: src/Features/LanguageServer/Protocol/Handler/Initialize/InitializeHandler.cs [hunk 2]
```diff
@@ -27,6 +27,7 @@ internal class InitializeHandler : IRequestHandler<InitializeParams, InitializeR
                 DocumentRangeFormattingProvider = true,
                 DocumentOnTypeFormattingProvider = new DocumentOnTypeFormattingOptions { FirstTriggerCharacter = "}", MoreTriggerCharacter = new[] { ";", "\n" } },
                 DocumentHighlightProvider = true,
+                TextDocumentSync = new TextDocumentSyncOptions { OpenClose = true }
```
Comment (dibarbet) [inline src/Features/LanguageServer/Protocol/Handler/Initialize/InitializeHandler.cs]: Do we need this since the notifications aren't propagated through live share yet?

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs [hunk 3]
```diff
@@ -166,34 +181,39 @@ public async Task<SymbolInformation[]> GetWorkspaceSymbolsAsync(JToken input, Ca
...
+                }
+
+                // LSP does not currently support publishing diagnostics incrememntally, so we re-publish all diagnostics.
+                PublishDiagnosticsAsync(e.Solution, document);
+            }
+        }
+
 #pragma warning disable VSTHRD100 // Avoid async void methods
-        private async void DiagnosticService_DiagnosticsUpdated(object sender, DiagnosticsUpdatedArgs e)
+        private async void PublishDiagnosticsAsync(Solution solution, Document document)
```
Comment (dibarbet) [inline src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs]: This should just return Task, then you can remove the suppression.

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs [hunk 4]
```diff
@@ -79,7 +80,21 @@ public Task<InitializeResult> Initialize(JToken input, CancellationToken cancell
...
+        public Task Initialized()
+        {
+            // Publish diagnostics for all open documents immediately following initialization.
+            var openDocuments = _workspace.GetOpenDocumentIds();
+            foreach (var documentId in openDocuments)
+            {
+                var document = _workspace.CurrentSolution.GetDocument(documentId);
+                if (document != null)
+                {
+                    PublishDiagnosticsAsync(_workspace.CurrentSolution, document);
```
Comment (dibarbet) [inline src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs]: PublishDiagnosticsAsync should return a task, then can return the result of PublishDiagnosticsAsync here.  Right now it will trigger PublishDiagnosticsAsync and will return a CompletedTask before PublishDiagnosticsAsync completes.

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs [hunk 5]
```diff
@@ -166,34 +181,39 @@ public async Task<SymbolInformation[]> GetWorkspaceSymbolsAsync(JToken input, Ca
             return await _protocol.GetWorkspaceSymbolsAsync(_workspace.CurrentSolution, workspaceSymbolParams, _clientCapabilities, cancellationToken).ConfigureAwait(false);
         }
 
+        private void DiagnosticService_DiagnosticsUpdated(object sender, DiagnosticsUpdatedArgs e)
```
Comment (dibarbet) [inline src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs]: Since this is still the one triggered by the event handler, this should still be async void and wrapped in the try catch instead of in PublishDiagnosticsAsync.

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs [hunk 6]
```diff
@@ -166,34 +181,39 @@ public async Task<SymbolInformation[]> GetWorkspaceSymbolsAsync(JToken input, Ca
...
+        }
+
 #pragma warning disable VSTHRD100 // Avoid async void methods
-        private async void DiagnosticService_DiagnosticsUpdated(object sender, DiagnosticsUpdatedArgs e)
+        private async void PublishDiagnosticsAsync(Solution solution, Document document)
 #pragma warning restore VSTHRD100 // Avoid async void methods
         {
             // Since this is an async void method, exceptions here will crash the host VS. We catch exceptions here to make sure that we don't crash the host since
             // the worst outcome here is that guests may not see all diagnostics.
             try
```
Comment (dibarbet) [inline src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs]: This try catch should be in the event handler method.

File: src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs (hunk 1 above)
Comment (dibarbet) [reply src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs]: I don't think we will necessarily be reverting it.  This is just how the LSP client handles squiggles - info is purple and Hint is two dots.

Comment (dibarbet) [reply src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs]: Hidden should also not be hint, but it will be until we have support for hidden diagnostics - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1063158

Comment (JoeRobich) [reply src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs]: Interesting choice.

File: src/Features/LanguageServer/Protocol/Handler/Initialize/InitializeHandler.cs [hunk 7]
```diff
@@ -26,7 +26,7 @@ internal class InitializeHandler : IRequestHandler<InitializeParams, InitializeR
                 DocumentFormattingProvider = true,
                 DocumentRangeFormattingProvider = true,
                 DocumentOnTypeFormattingProvider = new DocumentOnTypeFormattingOptions { FirstTriggerCharacter = "}", MoreTriggerCharacter = new[] { ";", "\n" } },
-                DocumentHighlightProvider = true,
+                DocumentHighlightProvider = true
```
Comment (CyrusNajmabadi) [inline src/Features/LanguageServer/Protocol/Handler/Initialize/InitializeHandler.cs]:
```suggestion
                DocumentHighlightProvider = true,
```

File: src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs [hunk 8]
```diff
@@ -79,7 +80,19 @@ public Task<InitializeResult> Initialize(JToken input, CancellationToken cancell
...
+        public async Task Initialized()
+        {
+            // Publish diagnostics for all open documents immediately following initialization.
+            var openDocuments = _workspace.GetOpenDocumentIds();
+            foreach (var documentId in openDocuments)
+            {
+                var document = _workspace.CurrentSolution.GetDocument(documentId);
+                if (document != null)
+                {
+                    await PublishDiagnosticsAsync(_workspace.CurrentSolution, document).ConfigureAwait(false);
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/Core/Def/Implementation/LanguageClient/InProcLanguageServer.cs]: continually referencing _workspace.CurrentSolution is very scary.  it could change over time.  Instead, pull this out above hte foreach look and always reference the same instance.  Passing that instance into `PublishDiagnosticsAsync` shouldn't be necessary either.  it's redundant given that `document` is passed in.
