### PR TITLE
Fix region tracking for regions with local functions

### LINKED ISSUE #37427: Region analysis gives incorrect results in the presence of local functions
Region analysis gives incorrect results in the presence of local functions.  The implementation does not properly track the start and end of the region, resulting in incorrect results.

See also https://github.com/dotnet/roslyn/issues/37421 https://github.com/dotnet/roslyn/issues/19497

/cc @CyrusNajmabadi @agocke 

``` c#
        [Fact, WorkItem(37427, "https://github.com/dotnet/roslyn/issues/37427")]
        public void RegionWithLocalFunctions()
        {
            var analysisResults = CompileAndAnalyzeDataFlowStatements(@"
class A
{
    static void M(int p)
    {
        int i, j;
        i = 1;
        /*<bind>*/
        int L1() => 1;
        int k;
        j = i;
        int L2() => 2;
        /*</bind>*/
        k = j;
    }
}
");
            var dataFlowAnalysisResults = analysisResults;
            Assert.True(dataFlowAnalysisResults.Succeeded);
            Assert.Equal("k", GetSymbolNamesJoined(dataFlowAnalysisResults.VariablesDeclared));
            // should be "j"
            Assert.Equal(null, GetSymbolNamesJoined(dataFlowAnalysisResults.AlwaysAssigned));
            Assert.Equal(null, GetSymbolNamesJoined(dataFlowAnalysisResults.Captured));
            Assert.Equal(null, GetSymbolNamesJoined(dataFlowAnalysisResults.CapturedInside));
            Assert.Equal(null, GetSymbolNamesJoined(dataFlowAnalysisResults.CapturedOutside));
            // should be "i"
            Assert.Equal(null, GetSymbolNamesJoined(dataFlowAnalysisResults.DataFlowsIn));
            // should be "j"
            Assert.Equal(null, GetSymbolNamesJoined(dataFlowAnalysisResults.DataFlowsOut));
            // should be "i"
            Assert.Equal(null, GetSymbolNamesJoined(dataFlowAnalysisResults.ReadInside));
            // should be "j"
            Assert.Equal("i, j", GetSymbolNamesJoined(dataFlowAnalysisResults.ReadOutside));
            // should be "j"
            Assert.Equal(null, GetSymbolNamesJoined(dataFlowAnalysisResults.WrittenInside));
            // should be "p, i, k"
            Assert.Equal("p, i, j, k", GetSymbolNamesJoined(dataFlowAnalysisResults.WrittenOutside));
        }
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #37427

/cc @agocke
@CyrusNajmabadi I suspect this will address the anomaly you are seeing in your PR.

### CODE REVIEW

**Comment by gafter** [comment]
I might move this to the compilerNext branch once I have feedback about which branch is appropriate for this work.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowsOutWalker.cs [hunk 1]
```diff
@@ -58,6 +58,12 @@ private HashSet<Symbol> Analyze(ref bool badRegion)
             return _dataFlowsOut;
         }
 
+        protected override ImmutableArray<PendingBranch> Scan(ref bool badRegion)
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowsOutWalker.cs]: The analysis was wrong before in the presence of multipass.  But since multipass was rare, we didn't notice.  However, with the way we handle local functions in this PR, we are more likely to have multiple passes and get the wrong answer.  The need for this wqas caught by an existing test.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs [hunk 2]
```diff
@@ -1519,36 +1519,43 @@ public override BoundNode VisitBlock(BoundBlock node)
...
+                    if (stmt.Kind != BoundKind.LocalFunctionStatement)
+                    {
+                        VisitStatement(stmt);
+                    }
+                }
+            }
+            else
             {
-                if (stmt.Kind != BoundKind.LocalFunctionStatement)
+                foreach (var stmt in block.Statements)
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs]: If we are tracking regions then we take the block statements in the order in which they appear.

File: src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs [hunk 3]
```diff
@@ -1519,36 +1519,43 @@ public override BoundNode VisitBlock(BoundBlock node)
...
+            {
+                // Visit the statements in two phases:
+                //   1. Local function declarations
+                //   2. Everything else
+                //
+                // The idea behind visiting local functions first is
+                // that we may be able to gather the captured variables
+                // they read and write ahead of time in a single pass, so
+                // when they are used by other statements in the block we
+                // won't have to recompute the set by doing multiple passes.
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs]: >won't have to recompute the set by doing multiple passes [](start = 19, length = 56)

This is a compiler performance optimization, so we can skip it when it compromises correctness.

**Comment by CyrusNajmabadi** [comment]
Cool!  Thanks much!

File: src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs [hunk 4]
```diff
@@ -1519,36 +1519,43 @@ public override BoundNode VisitBlock(BoundBlock node)
...
-            }
 
-            // Second phase
-            foreach (var stmt in block.Statements)
+                // Second phase
+                foreach (var stmt in block.Statements)
+                {
+                    if (stmt.Kind != BoundKind.LocalFunctionStatement)
+                    {
+                        VisitStatement(stmt);
```
Comment (agocke) [inline src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs]: My read of this will be that we still won't visit local functions as part of the region if the the declaration doesn't actually live in the region.

Can that affect the results?

File: src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs [hunk 5]
```diff
@@ -6360,6 +6363,41 @@ void Method(out object test)
...
+        {
+            var analysisResults = CompileAndAnalyzeDataFlowStatements(@"
+class A
+{
+    static void M(int p)
+    {
+        int i, j;
+        i = 1;
+        /*<bind>*/
+        int L1() => 1;
```
Comment (agocke) [inline src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs]: We should have a test that confirms that this code behaves identically if the local function declarations are moved out of the region (I think? That's my understanding of the contract of these region analyses).

File: src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs (hunk 4 above)
Comment (gafter) [reply src/Compilers/CSharp/Portable/FlowAnalysis/DefiniteAssignment.cs]: In this code, we visit every statement (even a local function declaration) whether it is in the region or not.  If there is a region we visit the statements in order.  If there is no region then we visit the local functions before the other statements.

File: src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs (hunk 5 above)
Comment (gafter) [reply src/Compilers/CSharp/Test/Semantic/FlowAnalysis/RegionAnalysisTests.cs]: That will be true for this test since the local functions are trivial.  I will add that to this test.

**Comment by gafter** [comment]
@agocke I added the requested test.  Do you have any other comments?

@dotnet/roslyn-compiler May I please have a second review of this small change?
