### PR TITLE
Report nullable safety warnings (vs. "W"-warnings) for assignments to captured primary constructor parameters.

### LINKED ISSUE #67099: Primary constructor parameter assignment in initializers uses wrong nullable warning
**Version Used**:  features/PrimaryConstructors

**Steps to Reproduce**:

https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQAUEEsC2UECeAwgPYB2yMCcAxjCQsgDQAmIA1AD4ACATAIwBYAFABiMnAA2kqMEkQABBDKz5I7gGYFfBUQAU3fgAYFyAJQKA3iIW3tWw0YD8CgGJYIklvwUBeBXrIfgoS0mYA3AoA9FG6AMoAHABsRiaoIeSoyFCQMAQKAOqoAO74ZFhkAOY2dpraxm4eXrzhNbZt9rp6FiAKMAAWWMh6AEQjZh3WwnYzjZ4svMGhkpEx8cm8AKwK6dm5+QBy5IUlZRXV03YAviJXQA=

We report a non-safety W-warning for the assignment to the primary ctor parameter. This warning code is intended for assignments that are considered "stylistic", and it's expected that some users will decide to suppress them globally to avoid updating the types of locals. A separate error code should be used for nullable assignments can be seen outside the current method body (such as CS8625), as these are actual safety issues and not just stylistic choices.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #67099.

### CODE REVIEW

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 1)

File: src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs [hunk 1]
```diff
@@ -16476,6 +16476,68 @@ void verify1(string source1, string source2, string source3)
             }
         }
 
+        [Fact]
+        [WorkItem("https://github.com/dotnet/roslyn/issues/67099")]
+        public void NullableWarningsForAssignment_01_NotCaptured()
+        {
+            var source = @"
+#nullable enable
+class C1(string p1, string p2)
```
Comment (jjonescz) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs:16485]: Is this fixed for records, too, as mentioned in the issue? Should we add a test?

**Review by jjonescz — APPROVED** [review]

File: src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/PrimaryConstructorTests.cs:16485]: > Is this fixed for records, too, as mentioned in the issue? Should we add a test?

Records do not capture parameters the same way and it was not my intent to change existing behavior for records in this PR. I will make sure the issue is not closed and is properly triaged for the record scenario. Thanks for brining this up.
