### PR TITLE
Fix namespace incremental parsing bug

### LINKED ISSUE #37665: Incremental parsing of using with errant [ throws asserts, crashes
**Version Used**: 16.2.0 (debug build will assert so you can easily see the problem)

**Steps to Reproduce**:

1. Create a new console application.
2. Before a semicolon in one of the using directives at the top of the file, type a `[`.

**Expected Behavior**: no asserts

**Actual Behavior**: the compiler asserts during incremental parse. IDE will crash from there.

This is one bug found by digging through a bug bucket of 16.2 crashes.

Assert:

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------

   at Microsoft.CodeAnalysis.SyntaxTreeExtensions.VerifySource(SyntaxTree tree, IEnumerable`1 changes)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChanges(SourceText newText, IReadOnlyList`1 changes)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.WithChangedText(SourceText newText)
   at Microsoft.CodeAnalysis.DocumentState.IncrementallyParse(TextAndVersion newTextAndVersion, TreeAndVersion oldTreeAndVersion, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DocumentState.<IncrementallyParseTreeAsync>d__15.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.DocumentState.IncrementallyParseTreeAsync(ValueSource`1 oldTreeSource, ValueSource`1 newTextSource, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DocumentState.<>c__DisplayClass14_0.<CreateLazyIncrementallyParsedTree>b__0(CancellationToken c)
   at Roslyn.Utilities.AsyncLazy`1.StartAsynchronousComputation(AsynchronousComputationToStart computationToStart, Request requestToCompleteSynchronously, CancellationToken callerCancellationToken)
   at Roslyn.Utilities.AsyncLazy`1.GetValueAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DocumentState.<GetSyntaxTreeAsync>d__42.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.DocumentState.GetSyntaxTreeAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Document.GetSyntaxTreeAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Host.BackgroundParser.<>c__DisplayClass20_0.<ParseDocumentAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

### PR DESCRIPTION
**Pull request by agocke**
There was a previous parsing change (#32999) which modified namespace
parsing to allow modifiers and attributes on namespaces, to improve
error recovery.

This PR contained a bug because it didn't move the incremental parsing
check to before parsing attributes and modifiers, which should now
be included in incremental parsing to prevent changes from being dropped

Fixes #37665, #37664, #37663

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
:(

Sorry about that.

**Comment by CyrusNajmabadi** [comment]
So previous to this, was it the case that we basically wouldn't reuse the namespace decl because it had errors on it.  But because there were no longer errors, we thought we could use it now?  Definitely a subtle thing i hadn't considered.

File: src/Compilers/CSharp/Test/Syntax/IncrementalParsing/IncrementalParsingTests.cs [hunk 1]
```diff
@@ -3,6 +3,7 @@
 using System;
 using System.Collections.Immutable;
 using System.Linq;
+using System.Security.Policy;
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Syntax/IncrementalParsing/IncrementalParsingTests.cs]: doesn't look like this is used

**Comment by RikkiGibson** [comment]
@jasonmalinowski indicated that this should be taken in 16.2 servicing

File: src/Compilers/CSharp/Test/Syntax/IncrementalParsing/IncrementalParsingTests.cs (hunk 1 above)
Comment (agocke) [reply src/Compilers/CSharp/Test/Syntax/IncrementalParsing/IncrementalParsingTests.cs]: I have no idea how that got added...

**Comment by agocke** [comment]
@CyrusNajmabadi No worries, now I got to fix my first incremental parsing bug 😄 I think you're right, this was probably working before because the modifiers and attributes were errors.

**Comment by agocke** [comment]
Actually, the modifiers and attributes were previously stored as skipped syntax, so they weren't part of the node at all. So the namespace node reuse was fine.

**Comment by agocke** [comment]
Ah, but that still would have dropped tokens. No, it's probably the errors.

**Comment by RikkiGibson** [comment]
@agocke I noticed the issues marked as "will be fixed by this PR" are still open. Do you know what's going on there?

**Comment by agocke** [comment]
Probably just hasn't made it to master. I think that's when bugs get autoclosed.
