### PR TITLE
Convert operand of `true`/`false` operator invoked as part of `&&`/`||`operator evaluation

### LINKED ISSUE #78609: Invalid code is emitted for a user-defined conditional logical operator
```
public class Program
{
    static void Main()
    {
        _ = (Get1() && Get2());
    }

    static S1 Get1() => new S1();
    static S1 Get2() => new S1();
}

struct S1
{
    public static S1 operator &(S1 x, S1 y) => x;

    public static bool operator true(S1? x) => true;
    public static bool operator false(S1? x) => false;
}
```

PEVerify fails: [ : Program::Main][mdToken=0x6000003][offset 0x00000008][found value 'S1'][expected value 'System.Nullable`1[S1]'] Unexpected type on the stack.

IL:
```
    .method private hidebysig static 
        void Main () cil managed 
    {
        // Method begins at RVA 0x2050
        // Code size 30 (0x1e)
        .maxstack 2
        .locals init (
            [0] valuetype S1
        )

        IL_0000: nop
        IL_0001: call valuetype S1 Program::Get1()
        IL_0006: stloc.0
        IL_0007: ldloc.0
        IL_0008: call bool S1::op_False(valuetype [System.Runtime]System.Nullable`1<valuetype S1>)
        IL_000d: brtrue.s IL_001d

        IL_000f: ldloc.0
        IL_0010: call valuetype S1 Program::Get2()
        IL_0015: call valuetype S1 S1::op_BitwiseAnd(valuetype S1, valuetype S1)
        IL_001a: pop
        IL_001b: br.s IL_001d

        IL_001d: ret
    } // end of method Program::Main
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #78609.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs [hunk 1]
```diff
@@ -8969,6 +8969,646 @@ static void M(C x, C y)
...
+        catch (System.ArgumentException) // https://github.com/dotnet/runtime/issues/115674 The user-defined operator method 'op_BitwiseOr' for operator 'OrElse' must have associated boolean True and False operators.
+        {
+            System.Console.Write("exception");
+            return;
+        }
+
+        ex.Compile()();
+    }
+
+    static void Test3(S1 s1)
```
Comment (chsienki) [inline src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs:9025]: Nit: looks like Test3 is unused

File: src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs [hunk 2]
```diff
@@ -8969,6 +8969,646 @@ static void M(C x, C y)
...
+        catch (System.ArgumentException) // https://github.com/dotnet/runtime/issues/115674 The user-defined operator method 'op_BitwiseOr' for operator 'OrElse' must have associated boolean True and False operators.
+        {
+            System.Console.Write("exception");
+            return;
+        }
+
+        ex.Compile()();
+    }
+
+    static void Test3(S1? s1)
```
Comment (chsienki) [inline src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs:9113]: Unused?

**Review by chsienki — APPROVED** [review]

File: src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Semantic/Semantics/OperatorTests.cs:9025]: > Nit: looks like Test3 is unused

This is intentional. Demonstrates that we can successfully compile the `if`. A consistency check.

**Comment by AlekseyTs** [comment]
@jcouv, @dotnet/roslyn-compiler For the second review.

File: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml [hunk 3]
```diff
@@ -501,6 +501,15 @@
     <Field Name="LogicalOperator" Type="MethodSymbol"/>
     <Field Name="TrueOperator" Type="MethodSymbol"/>
     <Field Name="FalseOperator" Type="MethodSymbol"/>
+
+    <!-- Used as an operand to bind TrueFalseOperandConversion -->
+    <Field Name="TrueFalseOperandPlaceholder" Type="BoundValuePlaceholder?" SkipInVisitor="true" Null="allow"/>
+    <!--
+    Could be a BoundConversion or, in some cases of an identity conversion, the OperandPlaceholder, or null for no conversion case
+    If the node survives lowering, this property in it must be null.
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml:509]: Consider asserting that in `LocalRewritingValidator`

**Review by jcouv — APPROVED** [review]
LGTM Thanks (commit 1)

File: src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml (hunk 3 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/BoundTree/BoundNodes.xml:509]: > Consider asserting that in LocalRewritingValidator

This is an FYI, not a contract or a correctness requirement
