### PR TITLE
Adjust indent block operations used for VB smart indent in argument lists

### LINKED ISSUE #25323: VB: Smart indent issue with argument lists
**Version Used**: 15.7.0 Preview 1.0 [27506.1.d15.7]

The here is that VB smart indent for argument lists is *always* based on the position of the first argument, regardless of where other arguments are positioned.

**Steps to Reproduce**:

1. Create Visual Basic Console App project
2. Add the following line of code to `Main()`:

``` VB
Console.WriteLine("{0} + {1} = {2}", 19, 23, 19 + 23)
```

3. Place the editor caret before the second argument (`19`) and press ENTER. Then, unindent until the remaining arguments start one tab to the left of `Console`:

``` VB
Console.WriteLine("{0} + {1} = {2}",
    19, 23, 19 + 23)
```

4. Place the editor caret before the third argument (`23`) and press ENTER.

**Expected Behavior**:

The indentation should be aligned with the second argument.

``` VB
Console.WriteLine("{0} + {1} = {2}",
    19,
    23, 19 + 23)
```

**Actual Behavior**:

The indentation is always aligned with the first argument, regardless of where subsequent arguments are positioned.

``` VB
Console.WriteLine("{0} + {1} = {2}",
    19, 
                  23, 19 + 23)
```

Note that this happens for every single argument after the first one. If the user wants a different indentation level, the IDE fights them by trying to force every argument to align with the first argument.

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes #25323

### Customer scenario

Visual Basic argument lists (and other parenthesized lists, like parameter lists and type parameter lists),
have specialized smart indent behavior. Essentially, arguments after the first argument in a list are
indented to the same position as the first argument. Consider the following code.

``` VB
Sub M()
    Console.WriteLine("{0} + {1} = {2}", 19, 23, 19 + 23)
End Sub
```

If the user presses ENTER before the second argument (19), the indentation looks like so.

``` VB
Sub M()
    Console.WriteLine("{0} + {1} = {2}",
                      19, 23, 19 + 23)
End Sub
```

However, this can cause indentation issues if the user wants to ident all subsequent arguments differently. Consider the following scenario.

``` VB
Sub M()
    Console.WriteLine("{0} + {1} = {2}",
        19, 23,
        19 + 23)
End Sub
```

Now, if the user presses ENTER before the third argument (23), the indentation of the first argument will be used, even though the user had indented the second argument differently:

``` VB
Sub M()
    Console.WriteLine("{0} + {1} = {2}",
        19,
                      23,
        19 + 23)
End Sub
```

This problem occurs because a single indent block operation is created for the whole argument list using the indentation of the first argument. This change fixes the issue by creating multiple indent block operations using the indentation of the first argument, and the indentation of any argument that appears on a different line.

### Bugs this fixes

Fixes #25323

### Workarounds, if any

If the user wishes to format their argument lists in the manner described above, there really isn't a good way to workaround the issue. It's an annoyance and the editor will fight against the user's indentation.

### Risk

Low. This change is localized to indentation in argument lists.

### Performance impact

Low performance impact. Any new allocations do not happen in hot paths -- only when the user presses enter in an argument list.

### Is this a regression from a previous update?

No.

### Root cause analysis

I'm surprised we have not heard about this. This problem shows up in very simple cases where a method call has a large number of arguments. However, it is somewhat less common because many users will move the first argument to the next line and indent *all* arguments together at once.

### How was the bug found?

I was reformatting the VB classification unit tests and found this issue to be particularly frustrating.

### CODE REVIEW

File: src/EditorFeatures/VisualBasic/Formatting/Indentation/SpecialFormattingOperation.vb [hunk 1]
```diff
@@ -106,6 +106,62 @@ Namespace Microsoft.CodeAnalysis.Editor.VisualBasic.Formatting.Indentation
...
+            Dim sourceText = node.SyntaxTree.GetText()
+
+            ' First, create a list of all arguments that start lines.
+            Dim arguments = New List(Of ArgumentSyntax)
+
+            Dim previousLineNumber = -1
+            For Each argument In argumentList.Arguments
+                Dim lineNumber = sourceText.Lines.GetLineFromPosition(argument.SpanStart).LineNumber
+                If lineNumber > previousLineNumber Then
+                    arguments.Add(argument)
```
Comment (sharwell) [inline src/EditorFeatures/VisualBasic/Formatting/Indentation/SpecialFormattingOperation.vb]: ❓ What happens if the argument is split across lines?

```vb
Method(a +
  b, c +
  d) ' <-- What happens if you add , and hit enter here?
```

Comment (heejaechang) [reply src/EditorFeatures/VisualBasic/Formatting/Indentation/SpecialFormattingOperation.vb]: I am fine to be better on smart indent on expression. but just as FYI.

both C# and VB never tries to be too smart on multi line expressions. every one has different liking on those on every different cases even for same construct.

we do have some special cases like argument or parameter lists, but even for those, we did very simple thing.

most of time, if expression is more than 2 lines a part, we just give up and act like simple block indent (either align with previous line or 4 space added  after previous line)

Comment (heejaechang) [reply src/EditorFeatures/VisualBasic/Formatting/Indentation/SpecialFormattingOperation.vb]: one thing I hope we don't do is, we forcing people to follow our liking and make them to depend options for it.

Comment (DustinCampbell) [reply src/EditorFeatures/VisualBasic/Formatting/Indentation/SpecialFormattingOperation.vb]: Thanks! Good question. I'll add a test or two to cover this scenario.

Comment (DustinCampbell) [reply src/EditorFeatures/VisualBasic/Formatting/Indentation/SpecialFormattingOperation.vb]: @heejaechang: We aren't forcing people to follow our liking with this change and no options would ever be required. Instead, we're treating the special case of argument lists (which is different between C# and VB) to be a bit more natural.

File: src/EditorFeatures/VisualBasicTest/Formatting/Indentation/SmartIndenterTests.vb [hunk 2]
```diff
@@ -2835,6 +2835,44 @@ End Class"
...
         End Sub
 
+        <WorkItem(3293, "https://github.com/dotnet/roslyn/issues/3293")>
+        <WpfFact, Trait(Traits.Feature, Traits.Features.SmartIndent)>
+        Public Sub TestSmartIndentInArgumentLists3()
+            Dim code = "
+Class C
+    Sub M()
+        Console.WriteLine(""{0} + {1}"",
+            19, 23 +
```
Comment (sharwell) [inline src/EditorFeatures/VisualBasicTest/Formatting/Indentation/SmartIndenterTests.vb]: :memo: This test doesn't cover the case I was describing because `19` is an argument that starts a line. `23 +` gets excluded because it is on the same line as 19. I'm looking for a test case where an argument meets *both* of the following conditions:

1. The argument is the first argument that starts on the line
2. The first token of the argument is not the first token on the line

Comment (DustinCampbell) [reply src/EditorFeatures/VisualBasicTest/Formatting/Indentation/SmartIndenterTests.vb]: Sorry, I missed the first `+` in your original example. Will update.

Comment (DustinCampbell) [reply src/EditorFeatures/VisualBasicTest/Formatting/Indentation/SmartIndenterTests.vb]: And FWIW, it will certainly use the indentation of the first argument in that case. However, I think I'm comfortable with that.

Comment (sharwell) [reply src/EditorFeatures/VisualBasicTest/Formatting/Indentation/SmartIndenterTests.vb]: No problem, the additional ones you did add were good tests too

Comment (DustinCampbell) [reply src/EditorFeatures/VisualBasicTest/Formatting/Indentation/SmartIndenterTests.vb]: And FWIW, I would expect that it would indent to the second argument in this case. I don't think that's necessarily correct, but it's a pretty fishy scenario.

File: src/EditorFeatures/VisualBasicTest/Formatting/Indentation/SmartIndenterTests.vb [hunk 3]
```diff
@@ -2841,36 +2841,17 @@ End Class"
...
+          d,
 
     End Sub
 End Class"
 
             AssertSmartIndent(
                 code,
                 indentationLine:=6,
-                expectedIndentation:=16)
+                expectedIndentation:=13)
```
Comment (sharwell) [inline src/EditorFeatures/VisualBasicTest/Formatting/Indentation/SmartIndenterTests.vb]: :bulb: This is super weird IMO. It would be better to filter arguments to cases where they start on a line. If not in this pull request, then it would be good to file a bug to clean this up "eventually". 😄

Comment (DustinCampbell) [reply src/EditorFeatures/VisualBasicTest/Formatting/Indentation/SmartIndenterTests.vb]: If I understand the system correctly, filtering to just arguments that start a line would be even less predictable. This would leave gaps in the argument list where there isn't an indent block operation. In those cases, the indenter would move up the tree to the next indent block operation, which would likely be some node above the argument list. Here's what I *think* would happen:

``` VB
Sub M()
    Method(a +
      b, c +
      d,

End Sub
```

If there isn't an indent block operation created for `c + d`, the indentation would be 4 because the indent block operation from `Sub M() .. End Sub` would be used.

@heejaechang, please correct me if I'm not understanding the code correctly.

Comment (DustinCampbell) [reply src/EditorFeatures/VisualBasicTest/Formatting/Indentation/SmartIndenterTests.vb]: @sharwell: I think the right experience is to cause the first line break in an argument list after the first argument to use the same indent as the first argument. Then, subsequent line breaks would just use the previous line's indentation. However, I couldn't find a way to achieve that in this system. 😞

Comment (sharwell) [reply src/EditorFeatures/VisualBasicTest/Formatting/Indentation/SmartIndenterTests.vb]: Skipping arguments because they don't start a line would be equivalent to skipping trailing arguments on the same line. The indentation block from the previous (or first) argument would be used. For the case above, pressing <kbd>Enter</kbd> after `d` would indent to match `a`.

Comment (DustinCampbell) [reply src/EditorFeatures/VisualBasicTest/Formatting/Indentation/SmartIndenterTests.vb]: Ah yes, you're correct. :smile: I think that'd still be a weird experience though.

``` VB
Sub M()
    Method(a +
      b, c +
      d,
           |
End Sub
```

**Comment by jinujoseph** [comment]
@Pilchie for 15.7.P2 ask mode approval

File: src/EditorFeatures/VisualBasicTest/Formatting/Indentation/SmartIndenterTests.vb (hunk 3 above)
Comment (heejaechang) [reply src/EditorFeatures/VisualBasicTest/Formatting/Indentation/SmartIndenterTests.vb]: smart indentation, first use formatting rule to find indentation, after that it uses simple indentation logic to find out where to put caret.
(http://index/?leftProject=Microsoft.CodeAnalysis.EditorFeatures&leftSymbol=poqp1cwzffsy&rightProject=Microsoft.CodeAnalysis.CSharp.EditorFeatures&file=Formatting%5CIndentation%5CCSharpIndentationService.Indenter.cs&line=136)

the simple indentation logic does either following previous line or add 4 more spaces.

the special formatting rule for argument, parameter was added for VB since vb had this behavior where caret aligned to first argument/parameter in the list rather than following previous line indentation or 4 spaces.

ex) void method(A b, 
                           | <= here

if one wants this kind of behavior
void method(A b,
    | <= here

one can just remove formatting rule, and let default smart indentation logic to take over.

if one wants to use formatting rule for it, you can use this
http://index/?query=FormattingRu&rightProject=Microsoft.CodeAnalysis.Workspaces&file=Formatting%5CRules%5COperations%5CIndentBlockOption.cs&line=16 and set something like "," as base token, but formatter was not designed to format expressions. it is designed to leave expression exactly as they were as much as possible, so I dont think there is enough options or knobs around expressions.

I think if behavior desired is just letting caret to be either aligned with previous line or 4 more spaces after previous line, it would be better just to let default smart indent behavior to take care of it.

**Comment by Pilchie** [comment]
Approved - thanks!

File: src/EditorFeatures/VisualBasicTest/Formatting/Indentation/SmartIndenterTests.vb (hunk 3 above)
Comment (DustinCampbell) [reply src/EditorFeatures/VisualBasicTest/Formatting/Indentation/SmartIndenterTests.vb]: Thanks @heejaechang. I think the right behavior for VB probably is:

1. Align with the first argument on the second line of an argument list.
2. Align with the previous line for subsequent lines in an argument list.

If I'm understanding you, removing the current VB formatting rule wouldn't provide that experience, correct?

**Comment by DustinCampbell** [comment]
Thanks @Pilchie! @heejaechang / @sharwell, I've filed #25371 to track further improvement in this area.

File: src/EditorFeatures/VisualBasicTest/Formatting/Indentation/SmartIndenterTests.vb (hunk 3 above)
Comment (heejaechang) [reply src/EditorFeatures/VisualBasicTest/Formatting/Indentation/SmartIndenterTests.vb]: yep. I think your change is general improvement around this area. I was just saying if we want to make it even better, we can tweak it a bit more.
