### PR TITLE
Add code fix for non-ref structs with members of the specific types

### LINKED ISSUE #31831: Code fix for CS8345 to make struct a ref struct
```c#
using System;

struct S
{
    Span<int> span; // CS8345: Field or auto-implemented property cannot be of type 'Span<int>' unless it is an instance member of a ref struct.
}
```

It would be nice to have a code fix to make `S` a ref struct.

### PR DESCRIPTION
**Pull request by vepanimas**
Fixes #31831.

A code fix for the compiler error "CS8345: Field or auto-implemented property cannot be of type '<specific type>' unless it is an instance member of a ref struct."

It fixes a case when we have such kind of code:
```
struct S
{
    Span<int> span;
}
```

Instance fields of a `Span<T>` type require a containing struct to be allocated on the stack, this is implemented using a `ref` keyword. So it's good to have an auto-fix converting the previous code to
```
ref struct S
{
    Span<int> span;
}
```

**Questions:**

- [ ] We probably also need a separate code fix changing a static `Span<T>` prop/field to the instance one.
- [x] Fix assembly references for unit tests.

### CODE REVIEW

File: src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+using Microsoft.CodeAnalysis.CodeActions;
+using Microsoft.CodeAnalysis.CodeFixes;
+using Microsoft.CodeAnalysis.CSharp.Syntax;
+using Microsoft.CodeAnalysis.Editing;
+using Microsoft.CodeAnalysis.Text;
+
+namespace Microsoft.CodeAnalysis.CSharp.MakeRefStruct
+{
+    [ExportCodeFixProvider(LanguageNames.CSharp), Shared]
+    public class CSharpMakeRefStructCodeFixProvider : CodeFixProvider
```
Comment (Neme12) [inline src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs]: This has to be internal, not public

File: src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+            var span = context.Span;
+
+            var root = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
+            var structDeclaration = FindContainingStruct(root, span);
+
+            if (!structDeclaration.Modifiers.Any(m => m.IsKind(SyntaxKind.RefKeyword)))
+            {
+                var gen = SyntaxGenerator.GetGenerator(document);
+                var refStructDeclaration = gen.WithModifiers(structDeclaration,
+                    gen.GetModifiers(structDeclaration).WithIsRef(true));
```
Comment (Neme12) [inline src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs]: :bulb: Could you do this later in FixCodeAsync?

File: src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+            => ImmutableArray.Create(CS8345);
+
+        public override async Task RegisterCodeFixesAsync(CodeFixContext context)
+        {
+            var document = context.Document;
+            var cancellationToken = context.CancellationToken;
+            var span = context.Span;
+
+            var root = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
+            var structDeclaration = FindContainingStruct(root, span);
```
Comment (Neme12) [inline src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs]: Does the compiler error only occur inside a struct? What if we're inside a class? Even if it never occurs inside classes, it might be a good idea to verify that struct is not null.

**Comment by CyrusNajmabadi** [comment]
Can you change the title of this and add more of a description to explain what's going on?  Also, when you'd lke this to be reviewed, please say so.  Thanks!

**Comment by vepanimas** [comment]
@Neme12, @CyrusNajmabadi , thx for review! I fixed all previous stuff and commited a new bunch of code :smiley:.

Though I have a problem here with the `Span<T>` type. These tests couldn't pass, because a diagnostic error is not emitted, so they fail with "No action was offered when one was expected.". The code flow doesn't hit neither [this](https://github.com/dotnet/roslyn/blob/0610c79807fa59d0815f2b89e5283cf6d630b71e/src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberFieldSymbol.cs#L60) nor [this](https://github.com/dotnet/roslyn/blob/0610c79807fa59d0815f2b89e5283cf6d630b71e/src/Compilers/CSharp/Portable/Symbols/Source/SourcePropertySymbol.cs#L1420), because in a TypeSymbol instead of a Property we get an `ErrorType` with "error CS0246: The type or namespace name 'Span<>' could not be found (are you missing a using directive or an assembly reference?)" message. 

It seems that all neccessary libs are [included](https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/TestUtilities/Workspaces/TestWorkspace_XmlConsumption.cs#L857), so I don't really understand what's going on here. That's my first attempt to contribute and I don't feel very confident with the codebase, so I've been stucked with that for a whole day :cold_sweat:. Do you have any ideas where can I look into? Or may be some similar issues are already known?

File: src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs [hunk 4]
```diff
@@ -153,6 +153,11 @@ public DeclarationModifiers WithIsWriteOnly(bool isWriteOnly)
             return new DeclarationModifiers(SetFlag(_modifiers, Modifiers.WriteOnly, isWriteOnly));
         }
 
+        public DeclarationModifiers WithIsRef(bool isRef)
+        {
+            return new DeclarationModifiers(SetFlag(_modifiers, Modifiers.Ref, isRef));
```
Comment (Neme12) [inline src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs]: Should we add a new constructor with a corresponding parameter as well?

**Comment by Neme12** [comment]
> The type or namespace name 'Span<>' could not be found

@vepanimas Is it possible you're just missing a `using` directive?

**Comment by vepanimas** [comment]
@Neme12, it seems that I found a solution [here](https://github.com/dotnet/roslyn/blob/defeca5d0e44915fc978cfd93d3de2e4a6d0dbf4/src/EditorFeatures/CSharpTest/Diagnostics/UseImplicitOrExplicitType/UseImplicitTypeTests.cs#L2089). It looks a bit weird, but it works for me as well.

File: src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs (hunk 4 above)
Comment (vepanimas) [reply src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs]: Added a new param to the existing constuctor. Is that enough? Do we really need a new constructor for this modifier?

Comment (Neme12) [reply src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs]: Because of compatibility concerns you might have to follow https://github.com/dotnet/roslyn/blob/master/docs/Adding%20Optional%20Parameters%20in%20Public%20API.md but maybe it's better to wait and ask someone from Roslyn

**Comment by vepanimas** [comment]
@CyrusNajmabadi, could you review this, pls?

File: src/Features/CSharp/Portable/CSharpFeaturesResources.resx [hunk 5]
```diff
@@ -586,4 +586,7 @@
     <value>Introduce 'using' statement</value>
     <comment>{Locked="using"} "using" is a C# keyword and should not be localized.</comment>
   </data>
+  <data name="Make_ref_struct" xml:space="preserve">
+    <value>Make ref struct</value>
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/CSharpFeaturesResources.resx]: needs a comment that both `ref` and `struct` are locked. (see above).  also, consider making this `Make 'ref struct'`

File: src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs [hunk 6]
```diff
@@ -0,0 +1,85 @@
...
+
+            // CS8345 could be triggered when struct is already marked with `ref` but a property is static
+            if (structDeclaration != null && !structDeclaration.Modifiers.Any(m => m.IsKind(SyntaxKind.RefKeyword)))
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs]: `!structDeclaration.Modifiers.Any(SyntaxKind.RefKeyword)`

File: src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs [hunk 7]
```diff
@@ -0,0 +1,85 @@
...
+            {
+                context.RegisterCodeFix(
+                    new MyCodeAction(
+                        CSharpFeaturesResources.Make_ref_struct,
+                        c => FixCodeAsync(context.Document, context.Span, c)),
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs]: you already have locals for context.Document and context.Span

File: src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs [hunk 8]
```diff
@@ -0,0 +1,85 @@
...
+        public override FixAllProvider GetFixAllProvider()
+        {
+            return WellKnownFixAllProviders.BatchFixer;
+        }
+
+        private async Task<Document> FixCodeAsync(Document document, TextSpan span, CancellationToken c)
+        {
+            var root = await document.GetSyntaxRootAsync(c).ConfigureAwait(false);
+
+            var structDeclaration = FindContainingStruct(root, span);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs]: maybe a comment saying that this will always succeed because you're using the same span that worked in RegisterCodeFixesAsync

File: src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs [hunk 9]
```diff
@@ -0,0 +1,85 @@
...
+                    context.Diagnostics);
+            }
+        }
+
+        public override FixAllProvider GetFixAllProvider()
+        {
+            return WellKnownFixAllProviders.BatchFixer;
+        }
+
+        private async Task<Document> FixCodeAsync(Document document, TextSpan span, CancellationToken c)
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs]: don't abbreviate to 'c' here.  (it's fine in the calling lambda).

File: src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs [hunk 10]
```diff
@@ -0,0 +1,85 @@
...
+            var member = root.FindNode(span);
+            // Could be declared in a class or even in a nested class inside a struct,
+            // so find only the first parent declaration
+            return member.GetAncestor<TypeDeclarationSyntax>() as StructDeclarationSyntax;
+        }
+
+        private SyntaxNode UpdateStructDeclaration(Document document, StructDeclarationSyntax decl)
+        {
+            var gen = SyntaxGenerator.GetGenerator(document);
+            return gen.WithModifiers(decl, gen.GetModifiers(decl).WithIsRef(true));
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs]: i would just inline this entire function.

File: src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs [hunk 11]
```diff
@@ -0,0 +1,85 @@
...
+
+            var root = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
+            var structDeclaration = FindContainingStruct(root, span);
+
+            // CS8345 could be triggered when struct is already marked with `ref` but a property is static
+            if (structDeclaration != null && !structDeclaration.Modifiers.Any(m => m.IsKind(SyntaxKind.RefKeyword)))
+            {
+                context.RegisterCodeFix(
+                    new MyCodeAction(
+                        CSharpFeaturesResources.Make_ref_struct,
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs]: title can't change. s o remove this and just have this specified in the `: base(...)` call below.

File: src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs (hunk 4 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs]: Since this is an internal constructor, i think this shoudl be fine.

**Comment by CyrusNajmabadi** [comment]
LGTM (with some cleanup/resource tweaks i mentioned).  @sharwell @jasonmalinowski this falls into that "simple code fix bucket" that i think we now want to consider taking and allowing the community to help us flesh out.  What do you guys think?

File: src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs [hunk 12]
```diff
@@ -0,0 +1,85 @@
...
+using Microsoft.CodeAnalysis.CodeFixes;
+using Microsoft.CodeAnalysis.CSharp.Syntax;
+using Microsoft.CodeAnalysis.Editing;
+using Microsoft.CodeAnalysis.Shared.Extensions;
+using Microsoft.CodeAnalysis.Text;
+
+namespace Microsoft.CodeAnalysis.CSharp.MakeRefStruct
+{
+    [ExportCodeFixProvider(LanguageNames.CSharp), Shared]
+    internal class CSharpMakeRefStructCodeFixProvider : CodeFixProvider
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs]: nit: in general the `CSharp` or `VisualBasic` prefix is for when there are multiple versions of this provided for both languages.  That said, we probably don't consistently follow that rule for other C#-only features, so i'm ok with leaving this as is.

File: src/EditorFeatures/CSharpTest/MakeRefStruct/MakeRefStructTests.cs [hunk 13]
```diff
@@ -0,0 +1,269 @@
...
+    }
+}
+
+ref struct S
+{
+    static Span<int> M { get; }
+}
+";
+            await TestInRegularAndScriptAsync(text, expected, parseOptions: s_parseOptions);
+        }
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/MakeRefStruct/MakeRefStructTests.cs]: do you have a fix-all test?  You returned the batch-fixer, so we should have a test for that.  Note: as @Neme12 has pointed out, the chance of needing fix-all in these cases is super low.  So we could even make this *not* batch-fixable and that would be 100% ok with me.

File: src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs (hunk 8 above)
Comment (vepanimas) [reply src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs]: Do we really need it? I haven't found neither additional null checks in the "fixing" code, nor special comments in similar cases (for example [this](https://github.com/dotnet/roslyn/blob/3bb73cf7f31cda72f057ae50ab6ce4b147efb115/src/Features/Core/Portable/MakeMethodAsynchronous/AbstractMakeMethodAsynchronousCodeFixProvider.cs#L89) code).

File: src/EditorFeatures/CSharpTest/MakeRefStruct/MakeRefStructTests.cs (hunk 13 above)
Comment (vepanimas) [reply src/EditorFeatures/CSharpTest/MakeRefStruct/MakeRefStructTests.cs]: Yep, I'll simply remove the batch-fixer. At first I decided not to add it, but found somewhere in the docs, that it is a bad practice for a new code-fixes.

File: src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs (hunk 12 above)
Comment (vepanimas) [reply src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs]: OK, thx, will consider this in the next PR's 😄

**Comment by vepanimas** [comment]
@CyrusNajmabadi, I think it's done, could u check it again pls?

File: src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs (hunk 6 above)
Comment (vepanimas) [reply src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs]: Thx, I didn't think about that case. I reworked this considering partial structs.

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs [hunk 14]
```diff
@@ -1815,14 +1815,14 @@ private static SyntaxTokenList AsModifierList(Accessibility accessibility, Decla
...
 
             // partial and ref must be last
-            if (modifiers.IsPartial)
+            if (modifiers.IsRef)
             {
-                list = list.Add(SyntaxFactory.Token(SyntaxKind.PartialKeyword));
+                list = list.Add(SyntaxFactory.Token(SyntaxKind.RefKeyword));
             }
 
-            if (modifiers.IsRef)
```
Comment (vepanimas) [inline src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs]: A `ref` keyword should be before `partial`, because `ref partial` is only allowed for now. It shouldn't be a breaking change, but anyway pls take a look at this.

**Comment by Neme12** [comment]
@vepanimas I see you removed [WIP] but the PR is still marked as "PR For Personal Review Only". I think we should ask @jinujoseph or someone to remove that label.

**Comment by jinujoseph** [comment]
thanks @Neme12 , fixed

File: src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs (hunk 8 above)
Comment (CyrusNajmabadi) [reply src/Features/CSharp/Portable/MakeRefStruct/CSharpMakeRefStructCodeFixProvider.cs]: I would add the comment

**Comment by CyrusNajmabadi** [comment]
I don't have a working computer. So the earliest I can review this again would be this coming Tuesday. Can you please ping me Wednesday if I haven't reviewed?

**Comment by vepanimas** [comment]
@CyrusNajmabadi ping

**Comment by CyrusNajmabadi** [comment]
@genlu @jcouv can either of you PTAL.

File: src/EditorFeatures/CSharpTest/MakeRefStruct/MakeRefStructTests.cs [hunk 15]
```diff
@@ -0,0 +1,340 @@
...
+
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsMakeRefStruct)]
+        [WorkItem(31831, "https://github.com/dotnet/roslyn/issues/31831")]
+        public async Task FieldInNotRefStruct()
+        {
+            var text = @"
+using System;
+namespace System
+{
+    public readonly ref struct Span<T>
```
Comment (jcouv) [inline src/EditorFeatures/CSharpTest/MakeRefStruct/MakeRefStructTests.cs]: Consider extracting the `Span<T>` help code out

File: src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs [hunk 16]
```diff
@@ -153,6 +155,11 @@ public DeclarationModifiers WithIsWriteOnly(bool isWriteOnly)
             return new DeclarationModifiers(SetFlag(_modifiers, Modifiers.WriteOnly, isWriteOnly));
         }
 
+        public DeclarationModifiers WithIsRef(bool isRef)
```
Comment (jcouv) [inline src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs]: nit: `WithRef`?

File: src/EditorFeatures/CSharpTest/MakeRefStruct/MakeRefStructTests.cs [hunk 17]
```diff
@@ -0,0 +1,340 @@
...
+{
+    public readonly ref struct Span<T> 
+    {
+        unsafe public Span(void* pointer, int length) { }
+    }
+}
+
+struct S
+{
+    Span<int>[||] M { get; }
```
Comment (jcouv) [inline src/EditorFeatures/CSharpTest/MakeRefStruct/MakeRefStructTests.cs]: note: this is an error scenario (code before&after won't compile). Maybe add a comment?

File: src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs (hunk 16 above)
Comment (genlu) [reply src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs]: I think it's the other way around, `WithAsync` and `WithPartial` should be `WithIsAsync` and `WithIsPartial`, they are public unfortunately...

---
In reply to: [251166882](https://github.com/dotnet/roslyn/pull/32037#discussion_r251166882) [](ancestors = 251166882)

File: src/Features/CSharp/Portable/MakeRefStruct/MakeRefStructCodeFixProvider.cs [hunk 18]
```diff
@@ -0,0 +1,91 @@
...
+            return null;
+        }
+
+        private static async Task<Document> FixCodeAsync(
+            Document document, 
+            StructDeclarationSyntax structDeclaration, 
+            CancellationToken cancellationToken)
+        {
+            var root = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
+            var gen = SyntaxGenerator.GetGenerator(document);
```
Comment (genlu) [inline src/Features/CSharp/Portable/MakeRefStruct/MakeRefStructCodeFixProvider.cs]: nit: please spell out syntaxGenerator or just generator.

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs (hunk 14 above)
Comment (genlu) [reply src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs]: Look like there was a test gap, thank you for fixing/adding test for this. Could you please also add a test for `readonly ref partial struct` (since the order matters)?

---
In reply to: [249267149](https://github.com/dotnet/roslyn/pull/32037#discussion_r249267149) [](ancestors = 249267149)

File: src/EditorFeatures/CSharpTest/MakeRefStruct/MakeRefStructTests.cs [hunk 19]
```diff
@@ -0,0 +1,340 @@
...
+    public class MakeRefStructTests : AbstractCSharpDiagnosticProviderBasedUserDiagnosticTest
+    {
+        private static readonly CSharpParseOptions s_parseOptions =
+            CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.CSharp7_3);
+
+        internal override (DiagnosticAnalyzer, CodeFixProvider) CreateDiagnosticProviderAndFixer(Workspace workspace)
+            => (null, new MakeRefStructCodeFixProvider());
+
+        [Fact, Trait(Traits.Feature, Traits.Features.CodeActionsMakeRefStruct)]
+        [WorkItem(31831, "https://github.com/dotnet/roslyn/issues/31831")]
```
Comment (genlu) [inline src/EditorFeatures/CSharpTest/MakeRefStruct/MakeRefStructTests.cs]: @dotnet/roslyn-ide Do we use `WorkItemAttribute` for new features? I thought it only applies to tests for bug fixes.

**Comment by genlu** [comment]
@jinujoseph This is marked as 16.1 P1 but targeting master right now. Where do we want this merged into?

**Comment by jinujoseph** [comment]
pls retarget dev16.1-preview1 before merging

**Comment by jcouv** [comment]
I've retargeted the PR to dev16.1-preview1 and fixed a trivial conflict

File: src/EditorFeatures/CSharpTest/MakeRefStruct/MakeRefStructTests.cs (hunk 17 above)
Comment (vepanimas) [reply src/EditorFeatures/CSharpTest/MakeRefStruct/MakeRefStructTests.cs]: I don't really understand what kind of comment should I write :confused:. It's obvious that if a codefix for a compiler error exists then the code is not compiled successfully.

File: src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs (hunk 16 above)
Comment (vepanimas) [reply src/Workspaces/Core/Portable/Editing/DeclarationModifiers.cs]: `withIsRef` looks weird but consistent with the majority of the similar builder methods from this class, so I left it as is.

File: src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs (hunk 14 above)
Comment (vepanimas) [reply src/Workspaces/CSharp/Portable/CodeGeneration/CSharpSyntaxGenerator.cs]: Done!

File: src/Features/CSharp/Portable/MakeRefStruct/MakeRefStructCodeFixProvider.cs (hunk 18 above)
Comment (vepanimas) [reply src/Features/CSharp/Portable/MakeRefStruct/MakeRefStructCodeFixProvider.cs]: Fixed

File: src/EditorFeatures/CSharpTest/MakeRefStruct/MakeRefStructTests.cs (hunk 15 above)
Comment (vepanimas) [reply src/EditorFeatures/CSharpTest/MakeRefStruct/MakeRefStructTests.cs]: Refactored

Comment (jcouv) [reply src/EditorFeatures/CSharpTest/MakeRefStruct/MakeRefStructTests.cs]: Thanks

File: src/EditorFeatures/CSharpTest/MakeRefStruct/MakeRefStructTests.cs (hunk 17 above)
Comment (vepanimas) [reply src/EditorFeatures/CSharpTest/MakeRefStruct/MakeRefStructTests.cs]: Aaah, you've talked about comments only for those cases where the code still can't be compiled after the fix applied, right?

Comment (vepanimas) [reply src/EditorFeatures/CSharpTest/MakeRefStruct/MakeRefStructTests.cs]: fixed

**Comment by vepanimas** [comment]
I resolved all issues, it looks ready to merge.

**Comment by jcouv** [comment]
Merged to dev16.1-preview1. Thanks @vepanimas!
