### PR TITLE
Fix invalid cast when removing unreachable code in top-level programs

### LINKED ISSUE #61810: CSharpRemoveUnreachableCodeCodeFixProvider encountered an error and has been disabled
**Version Used**: The one with Visual Studio v17.2.3?

**Steps to Reproduce**:

1. Create a console app project with the following code in Program.cs:
``` C#
// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");

do
{

} while (true);

Console.WriteLine("Hello, World!");
```
2. Press <kbd>Alt</kbd>-<kbd>Enter</kbd> on the second `Console.WriteLine("Hello, World!");` line.

**Expected Behavior**: No crash. 😄

**Actual Behavior**:
image

**Stack trace**:
```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.GlobalStatementSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.StatementSyntax'.
   at Microsoft.CodeAnalysis.CSharp.RemoveUnreachableCode.CSharpRemoveUnreachableCodeCodeFixProvider.FixAllAsync(Document document,ImmutableArray`1 diagnostics,SyntaxEditor editor,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.<>c__DisplayClass4_0.<FixAllAsync>b__0(SyntaxEditor editor)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

### LINKED ISSUE #61837: Unreachable code CodeFixProvider crashes when FixAll is applied
Reproduced on 17.2.0 Preview 1

```csharp
public class C
{
    public void M()
    {
        throw new Exception();
        Console.WriteLine();
        Console.WriteLine();
    }
}
```

Invoke fix all:

```csharp
System.InvalidOperationException : GetCurrentNode returned null with the following node: Console.WriteLine(); - line 281
   at Roslyn.Utilities.Contract.Fail(String message,Int32 lineNumber)
   at Microsoft.CodeAnalysis.Editing.SyntaxEditor.GetChangedRoot()
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.<GetFixAllProvider>b__2_0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeFixes.DocumentBasedFixAllProvider.<>c__DisplayClass8_1.<GetFixedDocumentsAsync>b__2(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeFixes.DocumentBasedFixAllProvider.GetFixedDocumentsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeFixes.DocumentBasedFixAllProvider.FixSingleContextAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeFixes.DocumentBasedFixAllProvider.FixAllContextsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeFixes.DefaultFixAllProviderHelpers.GetFixAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllCodeActionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorkerAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

This is reproducible in unit tests as well, but for a strange reason I can reproduce under two conditions:

1. Test must be run from CodeStyle, not EditorFeatures
    - This is weird. I thought CodeStyle is for supplying code fixes from NuGet and VS don't use that?
2. Test must be written in the new testing framework.

@mavasani @sharwell @CyrusNajmabadi

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #61810
Fixes #61837

- First commit moves tests to new testing framework.
- Second commit uses indexer instead of LINQ and makes the class `sealed` (just minor cleanup)
- Third commit is actual bug fix.

### CODE REVIEW

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by Youssef1313** [comment]
@CyrusNajmabadi The tests are passing locally, but failing in CI. Interestingly, the failing tests on CI are those tests that have multiple diagnostics reported.

I suspect there is an existing FixAll issue that was revealed with the new testing framework. However, I don't understand why tests pass locally.

**Comment by Youssef1313** [comment]
There is also a bug when multiple unused statements exist in top-level. I'll add another test and fix that. But I'm still unsure about the CI failure.

**Comment by Youssef1313** [comment]
> The tests are passing locally, but failing in CI. 

I could get them to fail locally. They pass when run from `EditorFeatures`, but fail when run from `CodeStyle`. I'll see if I can debug through this.

File: src/Analyzers/Core/Analyzers/Helpers/DiagnosticHelper.cs [hunk 1]
```diff
@@ -139,7 +139,7 @@ internal static class DiagnosticHelper
         {
             if (additionalUnnecessaryLocations.IsEmpty)
             {
-                return Create(descriptor, location, effectiveSeverity, additionalLocations, ImmutableDictionary<string, string?>.Empty, messageArgs);
+                return Create(descriptor, location, effectiveSeverity, additionalLocations, properties, messageArgs);
```
Comment (Youssef1313) [inline src/Analyzers/Core/Analyzers/Helpers/DiagnosticHelper.cs:142]: The codefix relies on properties to know whether to include a diagnostic in FixAll operation or not. Not passing properties in this code path caused all diagnostics to be included in fix all.

File: src/Analyzers/CSharp/Analyzers/RemoveUnreachableCode/RemoveUnreachableCodeHelpers.cs [hunk 2]
```diff
@@ -12,15 +14,35 @@ internal static class RemoveUnreachableCodeHelpers
     {
         public static ImmutableArray<ImmutableArray<StatementSyntax>> GetSubsequentUnreachableSections(StatementSyntax firstUnreachableStatement)
         {
-            SyntaxList<StatementSyntax> siblingStatements;
+            StatementSyntax[] siblingStatements;
```
Comment (Youssef1313) [inline src/Analyzers/CSharp/Analyzers/RemoveUnreachableCode/RemoveUnreachableCodeHelpers.cs:17]: I couldn't rely on `SyntaxList<TNode>` for global statements due to https://github.com/dotnet/roslyn/issues/61836.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Can you take another look? Thanks!

File: src/Analyzers/CSharp/Analyzers/RemoveUnreachableCode/RemoveUnreachableCodeHelpers.cs [hunk 3]
```diff
@@ -12,15 +14,35 @@ internal static class RemoveUnreachableCodeHelpers
...
+                        return ImmutableArray<ImmutableArray<StatementSyntax>>.Empty;
+                    }
+
+                    var builder = ArrayBuilder<StatementSyntax>.GetInstance();
+                    foreach (var member in compilationUnit.Members)
+                    {
+                        if (member is not GlobalStatementSyntax currentGlobalStatement)
+                        {
+                            continue;
+                        }
```
Comment (Youssef1313) [inline src/Analyzers/CSharp/Analyzers/RemoveUnreachableCode/RemoveUnreachableCodeHelpers.cs:40]: Note to self: I think it would be good to have a test capturing the difference between `continue;` and `break;`. That's an error scenario where there are global statements, followed by a class declaration, followed by global statements.

Another test case (error scenario too) is having a class declaration as the first member, followed by global statements.

File: src/Analyzers/CSharp/Analyzers/RemoveUnreachableCode/RemoveUnreachableCodeHelpers.cs (hunk 2 above)
Comment (CyrusNajmabadi) [reply src/Analyzers/CSharp/Analyzers/RemoveUnreachableCode/RemoveUnreachableCodeHelpers.cs:17]: this would be worth putting a comment.  also, if you don't intend on mutating this, make into an immutablearray.

File: src/Analyzers/CSharp/Analyzers/RemoveUnreachableCode/RemoveUnreachableCodeHelpers.cs [hunk 4]
```diff
@@ -12,15 +14,35 @@ internal static class RemoveUnreachableCodeHelpers
...
+                    siblingStatements = switchSection.Statements.ToArray();
+                    break;
+
+                case GlobalStatementSyntax globalStatement:
+                    if (globalStatement.Parent is not CompilationUnitSyntax compilationUnit)
+                    {
+                        return ImmutableArray<ImmutableArray<StatementSyntax>>.Empty;
+                    }
+
+                    var builder = ArrayBuilder<StatementSyntax>.GetInstance();
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/RemoveUnreachableCode/RemoveUnreachableCodeHelpers.cs:34]:
```suggestion
                    using var _ = ArrayBuilder<StatementSyntax>.GetInstance(out var builder);
```

you'll likely need to surround with a block as well.

File: src/Analyzers/CSharp/Analyzers/RemoveUnreachableCode/RemoveUnreachableCodeHelpers.cs [hunk 5]
```diff
@@ -12,15 +14,35 @@ internal static class RemoveUnreachableCodeHelpers
...
+                    {
+                        if (member is not GlobalStatementSyntax currentGlobalStatement)
+                        {
+                            continue;
+                        }
+
+                        builder.Add(currentGlobalStatement.Statement);
+                    }
+
+                    siblingStatements = builder.ToArrayAndFree();
```
Comment (CyrusNajmabadi) [inline src/Analyzers/CSharp/Analyzers/RemoveUnreachableCode/RemoveUnreachableCodeHelpers.cs:45]:
```suggestion
                    siblingStatements = builder.ToImmutable();
```

**Review by CyrusNajmabadi — APPROVED** [review]
