### PR TITLE
Do not emit empty language property in SARIF log

### LINKED ISSUE #68745: The `language` property of the SARIF file should be output correctly
**Version Used**: .NET 8.0.100-preview.5

**Steps to Reproduce**:

1. Fork [this repository](https://github.com/aetos382/roslyn-sarif-language-bug).
2. Run actions.

**Diagnostic Id**: N/A

**Expected Behavior**: All steps of the workflow are successful.

**Actual Behavior**: The `github/codeql-action/upload-sarif` action fails.

> Unable to upload "csharp-compiler.sarif" as it is not valid SARIF:
> - instance.runs[0].tool.driver.language does not match pattern "^[a-zA-Z]{2}(-[a-zA-Z]{2})?$"

**Causes**: 
The `tool.driver.language` property of the sarif file output by the C# compiler is an empty string (`""`).
Should be either output "en-US" or omit the property (if the locale of the execution environment is English).
See the sarif file attached to the workflow artifact.

**Workaround**: Specifies the `PreferredUILang` property

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #68745

SARIF spec requires non-empty language name property, which contains the culture name of the diagnostic messages in the SARIF log. Culture name can be empty for InvariantCulture, hence we must handle the empty culture name value in the SARIF error loggers.

### CODE REVIEW

File: src/Compilers/Core/Portable/CommandLine/SarifV1ErrorLogger.cs [hunk 1]
```diff
@@ -44,7 +44,11 @@ public SarifV1ErrorLogger(Stream stream, string toolName, string toolFileVersion
             _writer.Write("version", toolAssemblyVersion.ToString());
             _writer.Write("fileVersion", toolFileVersion);
             _writer.Write("semanticVersion", toolAssemblyVersion.ToString(fieldCount: 3));
-            _writer.Write("language", culture.Name);
+
+            // Emit the 'language' property only if it is a non-empty string to match the SARIF spec.
+            if (culture.Name.Length > 0)
```
Comment (333fred) [inline src/Compilers/Core/Portable/CommandLine/SarifV1ErrorLogger.cs:49]: What about language properties that are all whitespace?

**Review by 333fred — COMMENTED** [review]
Done review pass (commit 1)

File: src/Compilers/Core/Portable/CommandLine/SarifV1ErrorLogger.cs (hunk 1 above)
Comment (mavasani) [reply src/Compilers/Core/Portable/CommandLine/SarifV1ErrorLogger.cs:49]: I wasn't sure if that is a valid culture name. The docs at https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.name?view=net-7.0#property-value indicate it will be an empty string or in the expected format.

Comment (mavasani) [reply src/Compilers/Core/Portable/CommandLine/SarifV1ErrorLogger.cs:49]: All the CultureInfo constructors should throw `CultureNotFoundException` for invalid culture identifiers: https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.-ctor?view=net-7.0

**Review by 333fred — APPROVED** [review]
