### PR TITLE
Fix check for extension params parameter in nullable analysis

### LINKED ISSUE #80024: `CS8620` reported on non-null argument passed to extension method with non-nullable params collection parameter
**Full issue information + repro project**:  
https://github.com/just-ero/roslyn-issues-repros/tree/main/5.0.0/009_NullabilityWarning_ParamsExtension

### Version

> [!NOTE]  
> **Roslyn**: 5.0.0-2.25412.5 (b0b21b61)  
> **.NET SDK**: 10.0.100-preview.7.25380.108  
>  
> **Visual Studio Code**: 1.103.2  
> **C# Extension**: 2.89.19  
> **C# Dev Kit Extension**: 1.50.20  

### Steps to Reproduce

1. Add the following code wherever syntactically applicable:
    ```cs
    class C;

    static class E
    {
        extension(C)
        {
            static void Extension(params C[] values) { }
        }

        static void M()
        {
            C.Extension(new C());
        }
    }
    ```
2. Observe `Argument of type 'C' cannot be used for parameter 'values' of type 'C[]' in 'void extension(C).Extension(params C[] values)' due to differences in the nullability of reference types.`

### Expected Behavior

The warning is not reported. The parameter expects non-nullable values and `new C()` is not nullable.

### Actual Behavior

It is.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #80024

For a static extension call, the receiver type is included as an "argument" so that it can contribute to type (re)inference. The `parameters` used to analyze the call is adjusted accordingly to include the extension parameter. See [`getParameters()` helper on line 6752](https://github.com/dotnet/roslyn/blame/b4f64f4bbedbc6c4168cc1577aac507389d8b48b/src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs#L6752). I think a similar adjustment is also made in overload resolution and possibly elsewhere.

The `Ordinal`s of the parameter symbols are not adjusted based on this, so using them to decide if a parameter is the "last parameter in the list" is buggy. Instead, helper `Binder.GetCorrespondingParameter` already gave us the right symbol, so, we can just do a more direct check for whether the parameter we got, was the "last parameter in the list".

Relates to test plan https://github.com/dotnet/roslyn/issues/76130

### CODE REVIEW

File: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests2.cs [hunk 1]
```diff
@@ -34072,5 +34072,94 @@ .method public hidebysig specialname rtspecialname instance void .ctor ( string
         AssertEx.Equal("""[System.String caller = ""]""", parameter.ToTestDisplayString());
         Assert.Equal(1, parameter.CallerArgumentExpressionParameterIndex);
     }
+
+    [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/78189")]
+    public void Repro_78189()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests2.cs]: >Repro_78189 [](http://example.com/codeflow?start=16&length=11)

Do we have a test observing nullable warnings for `params` for similar declarations?  #Closed

**Comment by AlekseyTs** [comment]
Done with review pass (commit 1) #Closed

File: src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests2.cs (hunk 1 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Emit3/Semantics/ExtensionTests2.cs]: I didn't see any so I added one.

**Review by jjonescz — APPROVED** [review]

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 2)

**Comment by dodexahedron** [comment]
Thanks for this one.

It was becoming more and more annoying as we continue to adopt the new extension style.

**Comment by Kinematics** [comment]
This was supposedly fixed and applied to 11103, however as of today's (Oct 24) update to build 11121 the error is still occurring. Has the fix actually been applied to a build that has been released, or is it still pending?

**Comment by RikkiGibson** [comment]
Could you please let us know the output for `#error version` in a source file. Thanks

**Comment by Kinematics** [comment]
@RikkiGibson  — I am not sure what you mean by "the output for `#error version`". I'm not aware of any such command, or how to run it.

If you mean the version of Visual Studio being used, it is: `Version: Insiders [11121.172]`

If you mean source code that causes the error, the sample in #80024 still causes the error.

**Comment by CyrusNajmabadi** [comment]
> I am not sure what you mean by "the output for #error version". I'm not aware of any such command, or how to run it.

Place the literal string `#error version` in one of your .cs files and attempt to build it.

**Comment by Kinematics** [comment]
Compiler version: '5.0.0-2.25513.8 (7463b65f)'. Language version: preview.

**Comment by RikkiGibson** [comment]
Based on output of the following commands:

```sh
> git merge-base --is-ancestor 41f7a773e3bcce133e3fee6aa11feb742d8bae62 upstream/release/dev18.0; echo $?
1
> git merge-base --is-ancestor 41f7a773e3bcce133e3fee6aa11feb742d8bae62 upstream/main; echo $?
0
```

(see also [stackoverflow answer](https://stackoverflow.com/questions/18345157/how-can-i-tell-if-one-commit-is-an-ancestor-of-another-commit-or-vice-versa#18345268))

it looks like this PR made it into main but not into `release/dev18.0`.

@phil-allen-msft Is there some appropriate branch we can backport this PR to, which would allow this to most expediently make it to Insiders users. Maybe we would also need to fill out the ask mode template to do that?

**Comment by dodexahedron** [comment]
> This was supposedly fixed and applied to 11103, however as of today's (Oct 24) update to build 11121 the error is still occurring. Has the fix actually been applied to a build that has been released, or is it still pending?

+1

In fact, I am pretty sure I'm getting more of them than I was on RC1 (in VS 2022), because I had to suppress some today that were now being thrown for lines that had not changed and for which the methods being called had also not changed.

**Comment by jjonescz** [comment]
@RikkiGibson yes, for this to flow to VS Insiders, I believe it would need to be backported to release/dev18.0 branch (see https://github.com/dotnet/roslyn/blob/release/dev18.0/eng/config/PublishData.json#L125) but that would also need QB approval

**Comment by Kinematics** [comment]
So this bug still exists in the release version of VS2026, along with the latest Insider's.

Insider version: 11206.111, Compiler version: '5.3.0-1.25555.5 (02d301627ed5016a4c18acd1a35e5bbc20ff03f0)'.
Release: 18.0.0, Compiler version: '5.0.0-2.25529.7 (68a9207c)'.

**Comment by colejohnson66** [comment]
Still present in 10.0.102.

**Comment by aradalvand** [comment]
I can confirm the warning still shows up even in .NET SDK 10.0.102:

image

@RikkiGibson Could you re-evaluate this?

**Comment by AlekseyTs** [comment]
@aradalvand

> Could you re-evaluate this?

Consider opening a new issue with clear repro steps. Doing that (rather than commenting on a merged PR) will have much better chances that the problem will be noticed and looked at.

**Comment by aradalvand** [comment]
The repro and the issue description would be the same as before. This just hasn't made it into the recent SDK release, it seems.

**Comment by jjonescz** [comment]
The PR has the 18.3 milestone, so it will be in VS 18.3. I think that corresponds to SDK 10.0.200.

A bugfix would need to be backported (if it meets the servicing bar) to be in a release like 10.0.1xx.

**Comment by Frulfump** [comment]
> The PR has the 18.3 milestone, so it will be in VS 18.3. I think that corresponds to SDK 10.0.200.
> 
> A bugfix would need to be backported (if it meets the servicing bar) to be in a release like 10.0.1xx.

VS 18.3 came out on the 10th of February but the SDK installed with that and 18.3.1 is still the 1xx feature band. Any updates? The insiders version of VS 2026 comes with 10.0.200-preview SDK.

**Comment by jjonescz** [comment]
> VS 18.3 came out on the 10th of February but the SDK installed with that and 18.3.1 is still the 1xx feature band.

Yes, sorry, the release of 10.0.200 got unexpectedly delayed, it seems. (FWIW, 10.0.200-preview should be pretty stable at this point given the original expectation was that it would be released already.)

**Comment by Frulfump** [comment]
> > VS 18.3 came out on the 10th of February but the SDK installed with that and 18.3.1 is still the 1xx feature band.
> 
> Yes, sorry, the release of 10.0.200 got unexpectedly delayed, it seems. (FWIW, 10.0.200-preview should be pretty stable at this point given the original expectation was that it would be released already.)

Ah I see, is there a publicly shareable reason for the unexpected delay?

**Comment by jjonescz** [comment]
Turns out I wrongly assumed the [usual release cycle](https://learn.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs#lifecycle) but there were some changes to the release cycle and so apparently the sdk is not following the same schedule as in the past.

**Comment by Kinematics** [comment]
Visual Studio 18.4 came with 10.0.200, and the issue appears to be fixed.

**Comment by luryus** [comment]
> A bugfix would need to be backported (if it meets the servicing bar) to be in a release like 10.0.1xx.

@jjonescz Is this going to get backported? Ubuntu repos only ship the 1xx band of the SDK and updating to newer ones is difficult with MS no longer publishing Ubuntu packages.

Is there a reason why this would _not_ be backport-worthy? It's a clear bug in Roslyn, right?
