### PR TITLE
Handle checking for language version in speculative semantic model

### LINKED ISSUE #37454: Renaming a variable when range syntax is in use results in crash
I'm not positive that this is an issue with Roslyn rather than Visual Studio, but I'm reporting it here just in case.  I initially reported it on the [Feedback Hub](https://developercommunity.visualstudio.com/content/problem/645303/multiple-c-8-issues-intellisense-breaks-gathering.html), but it was marked as low priority ("Under Consideration").

* Visual Studio 2019.3.0 Preview 1.0 (prior preview versions also exhibit the issue)
* .NET Core 3.0.0-preview7 (prior preview versions also exhibit the issue)
* C# 8.0 preview

If I attempt to rename `bar` to `foobar` in the following code by putting my cursor within it, pressing F2, and typing `foobar`, Visual Studio will immediately crash without showing an error dialog as soon as I've typed `foo`. Any unsaved changes will be lost. Normally, Visual Studio would report that there's a conflict when I reach `foo`, then allow me to continue typing the rest of the variable name; however, in this context, it crashes. If I change `data[..2]` to `data.Slice(0, 2)`, Visual Studio doesn't crash, and the rename is successful.

``` csharp
using System;

namespace BugReport
{
    public static class Example
    {
        public static void Test(ReadOnlySpan<byte> data)
        {
            if (true)
            {
                var bar = 1;
                var foo = data[..2];
                DoSomething(foo);
            }
        }

        private static void DoSomething(ReadOnlySpan<byte> _) { }
    }
}
```

### PR DESCRIPTION
**Pull request by agocke**
Asking for Location.SourceTree may not produce a syntax tree, even if there
is a backing syntax tree, because a speculative tree node may produce NoLocation
when asked for one, even if there is a backing tree. This change stops us from
trying to do the SyntaxTree->Location->SyntaxTree roundtrip because it's not guaranteed
to succeed.

Fixes #37454

### CODE REVIEW

**Comment by agocke** [comment]
@jcouv I think we should take this for tell/ask mode, since it crashes VS

File: src/Compilers/CSharp/Portable/Errors/MessageID.cs [hunk 1]
```diff
@@ -230,12 +230,30 @@ internal static string RequiredFeature(this MessageID feature)
...
-        internal static bool CheckFeatureAvailability(this MessageID feature, DiagnosticBag diagnostics, Location errorLocation)
+        internal static bool CheckFeatureAvailability(
+            this MessageID feature,
+            DiagnosticBag diagnostics,
+            SyntaxNode syntax,
+            Location location = null)
         {
-            var diag = GetFeatureAvailabilityDiagnosticInfoOpt(feature, (CSharpParseOptions)errorLocation.SourceTree.Options);
+            var diag = GetFeatureAvailabilityDiagnosticInfoOpt(feature, (CSharpParseOptions)syntax.SyntaxTree.Options);
             if (!(diag is null))
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Errors/MessageID.cs]: >!(diag is null) [](start = 16, length = 15)

Nit: while you're here, consider simplifying to `diag is object`

Comment (333fred) [reply src/Compilers/CSharp/Portable/Errors/MessageID.cs]: The variable declaration could also be inlined entirely.

---
In reply to: [308427113](https://github.com/dotnet/roslyn/pull/37513#discussion_r308427113) [](ancestors = 308427113)

Comment (agocke) [reply src/Compilers/CSharp/Portable/Errors/MessageID.cs]: True, but it's not bad as-is.

**Comment by agocke** [comment]
@jcouv @cston @jaredpar Could one of you take a look when you get a chance?

File: src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs [hunk 2]
```diff
@@ -16,6 +16,45 @@ namespace Microsoft.CodeAnalysis.CSharp.UnitTests
 {
     public class SemanticTests : CSharpTestBase
     {
+        [Fact]
```
Comment (cston) [inline src/Compilers/CSharp/Test/Symbol/Compilation/SemanticModelAPITests.cs]: >Fact [](start = 9, length = 4)

Consider adding `[WorkItem]`.

**Comment by leecow** [comment]
tactics approved for preview 8

**Comment by agocke** [comment]
Oops, I forgot to change the branch to 16.3-preview2. I'm going to cherry-pick this change over.
