### PR TITLE
Report warning (always false) when testing null using pattern-is

### LINKED ISSUE #20103: The given expression is never of the provided type when pattern matching is used
**Version Used**: 2.3.0.61719 (5fbdd5c5)

**Steps to Reproduce**:

```csharp
class C
{
	static object Test ()
	{
		const object o = null;
		return o is object res; // Removing unused res shows the warning
	}

	static void Main ()
	{
	}
}
```

**Expected Behavior**:

`warning CS0184: The given expression is never of the provided ('object') type` is issued or even CS8121 error to be consistent with other pattern matching checks.

**Actual Behavior**:

No warning CS0184

### PR DESCRIPTION
**Pull request by gafter**
**Customer scenario**

If you have an expression `e is T`, where the expression `e` ends up being a constant null, the compiler reports that the expression is always false. But if you add an identifier after the type, the warning unexpectedly vanishes.

**Bugs this fixes:**

Fixes #20103

**Workarounds, if any**

N/A

**Risk**

Very low. We just add the missing diagnostic.

**Performance impact**

Only a trivial change to the execution path. Unlikely to be any measurable perf impact.

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

We did not attempt to duplicate the warnings from one construct when implementing the other.

**How was the bug found?**

Customer reported.

**Test documentation updated?**

N/A

**Compatibility**

This would technically be a breaking change, as it adds a warning where there was none before. The compatibility council has been consulted and has approved this change.

@dotnet/roslyn-compiler Please review.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs [hunk 1]
```diff
@@ -28,6 +28,11 @@ private BoundExpression BindIsPatternExpression(IsPatternExpressionSyntax node,
             }
 
             var pattern = BindPattern(node.Pattern, expressionType, hasErrors, diagnostics);
+            if (!hasErrors && pattern is BoundDeclarationPattern p && !p.IsVar && expression.ConstantValue == ConstantValue.Null)
```
Comment (jcouv) [inline src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: Why exclude `var` case?

Comment (gafter) [reply src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: No, that would be a semantically breaking change. People currently do `if (expr is var tmp && ...` to introduce a temporary variable, and all that kind of code would break.

Comment (sharwell) [reply src/Compilers/CSharp/Portable/Binder/Binder_Patterns.cs]: I actually proposed making this change in dotnet/csharplang#792. The specific case which most concerns me is the following pattern:

```
switch (x)
{
case var _ when expression:
  break;
}
```

**Comment by gafter** [comment]
@dotnet/roslyn-compiler May I please have a second review?
@jaredpar For 15.5 approval.

File: src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs [hunk 2]
```diff
@@ -6345,5 +6353,33 @@ static void Main()
                 Diagnostic(ErrorCode.ERR_SwitchExpressionValueExpected, @"Console.WriteLine(""Hello"")").WithArguments("void").WithLocation(6, 17)
                 );
         }
+
+        [Fact, WorkItem(20103, "https://github.com/dotnet/roslyn/issues/20103")]
+        public void TestNullInInPattern()
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/PatternMatchingTests.cs]: Should the name be `...InIsPattern`?

**Comment by gafter** [comment]
@jaredpar May I please have approval for 15.5?
/cc @jcouv

**Comment by jaredpar** [comment]
Approved to merge

**Comment by gafter** [comment]
github is terminally confused with this PR. Moving to a fresh PR.
