### PR TITLE
SpillSequenceSpiller.Spill - ensure sequences under ref assignments are spilled.

### LINKED ISSUE #58569: Compiler crash when array access with from-end expression used in deconstruction assignment lowers to use a ref local and the right-hand side contains an await expression
**Version Used**: 

.NET SDK 6.0.101

**Steps to Reproduce**:

```
var ts = new (int x, int y)[0];
(ts[^1].x, ts[0].y) = (0, await Task.FromResult(0));
```

**Expected Behavior**:

No crash.

**Actual Behavior**:

```
System.InvalidOperationException: Unexpected value 'Sequence' of type 'Microsoft.CodeAnalysis.CSharp.BoundKind' [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodToStateMachineRewriter.HoistExpression(BoundExpression expr, SyntaxNode awaitSyntaxOpt, Int32 syntaxOffset, RefKind refKind, ArrayBuilder`1 sideEffects, ArrayBuilder`1 hoistedFields, Boolean& needsSacrificialEvaluation) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodToStateMachineRewriter.HoistExpression(BoundExpression expr, SyntaxNode awaitSyntaxOpt, Int32 syntaxOffset, RefKind refKind, ArrayBuilder`1 sideEffects, ArrayBuilder`1 hoistedFields, Boolean& needsSacrificialEvaluation) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodToStateMachineRewriter.HoistRefInitialization(SynthesizedLocal local, BoundAssignmentOperator node) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodToStateMachineRewriter.VisitAssignmentOperator(BoundAssignmentOperator node) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.BoundAssignmentOperator.Accept(BoundTreeVisitor visitor) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.VisitExpressionWithoutStackGuard(BoundExpression node) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(BoundExpression node) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.VisitExpressionWithStackGuard(Int32& recursionDepth, BoundExpression node) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(BoundNode node) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodToStateMachineRewriter.Visit(BoundNode node) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.AsyncMethodToStateMachineRewriter.VisitExpressionStatement(BoundExpressionStatement node) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.BoundExpressionStatement.Accept(BoundTreeVisitor visitor) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(BoundNode node) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodToStateMachineRewriter.Visit(BoundNode node) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.DoVisitList[T](ImmutableArray`1 list) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.Symbols.MethodToClassRewriter.VisitBlock(BoundBlock node) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodToStateMachineRewriter.<>c__DisplayClass41_0.<VisitBlock>b__0() [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodToStateMachineRewriter.PossibleIteratorScope(ImmutableArray`1 locals, Func`1 wrapped) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodToStateMachineRewriter.VisitBlock(BoundBlock node) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(BoundNode node) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodToStateMachineRewriter.Visit(BoundNode node) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitSequencePoint(BoundSequencePoint node) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.BoundSequencePoint.Accept(BoundTreeVisitor visitor) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(BoundNode node) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodToStateMachineRewriter.Visit(BoundNode node) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.DoVisitList[T](ImmutableArray`1 list) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.Symbols.MethodToClassRewriter.VisitBlock(BoundBlock node) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodToStateMachineRewriter.<>c__DisplayClass41_0.<VisitBlock>b__0() [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodToStateMachineRewriter.PossibleIteratorScope(ImmutableArray`1 locals, Func`1 wrapped) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodToStateMachineRewriter.VisitBlock(BoundBlock node) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriterWithStackGuard.Visit(BoundNode node) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodToStateMachineRewriter.Visit(BoundNode node) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.AsyncMethodToStateMachineRewriter.VisitBody(BoundStatement body) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.AsyncMethodToStateMachineRewriter.GenerateMoveNext(BoundStatement body, MethodSymbol moveNextMethod) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.AsyncRewriter.GenerateMoveNext(SynthesizedImplementationMethod moveNextMethod) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.AsyncRewriter.GenerateMethodImplementations() [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.StateMachineRewriter.Rewrite() [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.AsyncRewriter.Rewrite(BoundStatement bodyWithAwaitLifted, MethodSymbol method, Int32 methodOrdinal, VariableSlotAllocator slotAllocatorOpt, TypeCompilationState compilationState, BindingDiagnosticBag diagnostics, AsyncStateMachine& stateMachineType) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.LowerBodyOrInitializer(MethodSymbol method, Int32 methodOrdinal, BoundStatement body, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState, Boolean instrumentForDynamicAnalysis, DebugDocumentProvider debugDocumentProvider, ImmutableArray`1& dynamicAnalysisSpans, BindingDiagnosticBag diagnostics, VariableSlotAllocator& lazyVariableSlotAllocator, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, StateMachineTypeSymbol& stateMachineTypeOpt) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType) [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass25_0.<CompileNamedTypeAsync>b__0() [C:\temp\repro_deconstruction_await_ref_local\repro_deconstruction_await_ref_local.csproj]
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #58569.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs [hunk 1]
```diff
@@ -311,11 +311,26 @@ private BoundStatement UpdateStatement(BoundSpillSequenceBuilder builder, BoundS
...
+                            expression = sequence.Value;
+                            continue;
+                        }
+
+                        goto default;
+
+                    case BoundKind.AssignmentOperator:
+                        var assignment = (BoundAssignmentOperator)expression;
+                        if (assignment.IsRef &&
+                            assignment is not { Left.Kind: BoundKind.Local, Right.Kind: BoundKind.ArrayAccess }) // Optimize for some known to be safe scenarios.
```
Comment (333fred) [inline src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs:329]: What drives the need to optimize? Do we think this is especially common?

File: src/Compilers/CSharp/Test/Emit/CodeGen/IndexAndRangeTests.cs [hunk 2]
```diff
@@ -3582,5 +3582,188 @@ class C
...
+        await M1(arr);
+        System.Console.WriteLine(arr[0][0]);
+    }
+}
+";
+            CompileAndVerifyWithIndexAndRange(src, expectedOutput:
+@"
+125
+").VerifyDiagnostics();
+        }
```
Comment (333fred) [inline src/Compilers/CSharp/Test/Emit/CodeGen/IndexAndRangeTests.cs:3767]: It might be worth testing with some slicing as well: Something like `arr[1..][^1]` to ensure that the slice rewriting bits are working as well.

**Comment by 333fred** [comment]
Done review pass (commit 1)

File: src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs (hunk 1 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Portable/Lowering/SpillSequenceSpiller.cs:329]: > What drives the need to optimize? Do we think this is especially common?

- Laziness. Don't want to update IL baselines for tests.
- The IL is actually becomes bigger, less optimal.

File: src/Compilers/CSharp/Test/Emit/CodeGen/IndexAndRangeTests.cs (hunk 2 above)
Comment (AlekseyTs) [reply src/Compilers/CSharp/Test/Emit/CodeGen/IndexAndRangeTests.cs:3767]: > It might be worth testing with some slicing as well: Something like ```arr[1..][^1]``` to ensure that the slice rewriting bits are working as well.

I'll add a test. However, a scenario like that isn't interesting for the specific problem I am trying to address in this PR. It doesn't matter how array came to the existence. It is a reference type and it is going to be captured by value. It is the array element (the actual target of the assignment) captured by reference. That is what needs the right spilling.

**Comment by AlekseyTs** [comment]
@333fred, @dotnet/roslyn-compiler Please review.

**Review by 333fred — APPROVED** [review]
LGTM (commit 2)

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

**Review by cston — APPROVED** [review]
