### PR TITLE
Fixed Make Method Asynchronous refactoring.

### LINKED ISSUE #18396: Make Method Asynchronous does not preserve leading trivia properly
**Version Used**: Master branch with #18307 merged.

**Steps to Reproduce**:

:bulb: A unit test is implemented for this case as part of #18307, but is skipped. Un-skip these tests to enable them when the underlying issue is fixed.

Use "Make method async (keep void)" on the following method:

```csharp
class C
{
    // Leading trivia
    /*1*/ void /*2*/ M2/*3*/() /*4*/
    {
        await M3Async();
    }

    async Task<int> M3Async()
    {
        return 1;
    }
}
```

**Expected Behavior**:

```csharp
class C
{
    // Leading trivia
    /*1*/ async void /*2*/ M2Async/*3*/() /*4*/
    {
        await M3Async();
    }

    async Task<int> M3Async()
    {
        return 1;
    }
}
```

**Actual Behavior**:

```csharp
class C
{
    // Leading trivia
    /*1*/
    async void /*2*/ M2Async/*3*/() /*4*/
    {
        await M3Async();
    }

    async Task<int> M3Async()
    {
        return 1;
    }
}
```

### PR DESCRIPTION
**Pull request by zaytsev-victor**
**Customer scenario**
Make Method Asynchronous does not preserve leading trivia properly

**Bugs this fixes:**
Fixes #18396

**Workarounds, if any**

**Risk**
Low

**Performance impact**
Low

**Is this a regression from a previous update?**
No

**Root cause analysis:**
Missed Formatter annotation for kept void return type.

**How was the bug found?**
ad hoc testing

### CODE REVIEW

File: src/Features/CSharp/Portable/MakeMethodAsynchronous/CSharpMakeMethodAsynchronousCodeFixProvider.cs [hunk 1]
```diff
@@ -81,6 +81,10 @@ protected override bool IsAsyncSupportingFunctionSyntax(SyntaxNode node)
                 {
                     newReturnType = taskType.GenerateTypeSyntax();
                 }
+                else
```
Comment (sharwell) [inline src/Features/CSharp/Portable/MakeMethodAsynchronous/CSharpMakeMethodAsynchronousCodeFixProvider.cs]: 💭 There is a similar case a few lines below, which applies to methods that return `Task` before they are make asynchronous. I'm guessing you could create a new unit test which fails unless an `else` case is added there too.

File: src/EditorFeatures/CSharpTest/Diagnostics/MakeMethodAsynchronous/MakeMethodAsynchronousTests.cs [hunk 2]
```diff
@@ -685,7 +685,7 @@ public void M1()
 
         [Theory]
         [InlineData(0, "Task")]
-        [InlineData(1, "void", Skip = "https://github.com/dotnet/roslyn/issues/18396")]
+        [InlineData(1, "void")]
         [Trait(Traits.Feature, Traits.Features.CodeActionsMakeMethodAsynchronous)]
         [WorkItem(18307, "https://github.com/dotnet/roslyn/issues/18307")]
         public async Task AddAsyncInLocalFunctionKeepsTrivia(int codeFixIndex, string expectedReturn)
```
Comment (sharwell) [inline src/EditorFeatures/CSharpTest/Diagnostics/MakeMethodAsynchronous/MakeMethodAsynchronousTests.cs]: :memo: If you add a `string initialReturn` parameter before `string expectedReturn`, you could reuse this test for all four cases:

```
[InlineData(0, "void", "Task")]
[InlineData(1, "void", "void")]
[InlineData(1, "int", "Task<int>")] // This case is new but I'm guessing it already works
[InlineData(1, "Task", "Task")] // This case is new and I'm guessing it fails
```

File: src/Features/CSharp/Portable/MakeMethodAsynchronous/CSharpMakeMethodAsynchronousCodeFixProvider.cs [hunk 3]
```diff
@@ -90,6 +94,10 @@ protected override bool IsAsyncSupportingFunctionSyntax(SyntaxNode node)
                     // in Task<>.
                     newReturnType = taskOfTType.Construct(methodSymbol.ReturnType).GenerateTypeSyntax();
                 }
+                else
+                {
+                    newReturnType = newReturnType.WithAdditionalAnnotations(Formatter.Annotation);
```
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/MakeMethodAsynchronous/CSharpMakeMethodAsynchronousCodeFixProvider.cs]: I feel like we could add this universally at the bottom of this method.

Comment (sharwell) [inline src/Features/CSharp/Portable/MakeMethodAsynchronous/CSharpMakeMethodAsynchronousCodeFixProvider.cs]: @zaytsev-victor Can you take a look and see if this would produce a cleaner result? Let me know what you decide.

Comment (zaytsev-victor) [inline src/Features/CSharp/Portable/MakeMethodAsynchronous/CSharpMakeMethodAsynchronousCodeFixProvider.cs]: @sharwell I like this solution, but in most cases it is useless operation, but if you ok with that I will update PR

Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/MakeMethodAsynchronous/CSharpMakeMethodAsynchronousCodeFixProvider.cs]: Yes, please do :)
