### PR TITLE
Make TryNavigateToMetadataSymbol asynchronous

### LINKED ISSUE #58612: InvalidOperationException: WaitAndGetResult cannot be called from a thread pool thread
```
System.InvalidOperationException: WaitAndGetResult cannot be called from a thread pool thread.\r
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult[T](Task`1 task, CancellationToken cancellationToken) in D:\R1\src\Workspaces\SharedUtilitiesAndExtensions\Compiler\Core\Utilities\TaskExtensions.cs:line 43\r
   at Microsoft.CodeAnalysis.FindUsages.DefinitionItem.DefaultDefinitionItem.TryResolveSymbolInCurrentSolution(Workspace workspace, String symbolKey) in D:\R1\src\Features\Core\Portable\FindUsages\DefinitionItem.DefaultDefinitionItem.cs:line 120\r
   at Microsoft.CodeAnalysis.FindUsages.DefinitionItem.DefaultDefinitionItem.TryNavigateToMetadataSymbol(Workspace workspace, String symbolKey, Func`4 action) in D:\R1\src\Features\Core\Portable\FindUsages\DefinitionItem.DefaultDefinitionItem.cs:line 90\r
   at Microsoft.CodeAnalysis.FindUsages.DefinitionItem.DefaultDefinitionItem.CanNavigateToMetadataSymbol(Workspace workspace, String symbolKey) in D:\R1\src\Features\Core\Portable\FindUsages\DefinitionItem.DefaultDefinitionItem.cs:line 74\r
   at Microsoft.CodeAnalysis.FindUsages.DefinitionItem.DefaultDefinitionItem.&lt;CanNavigateToAsync&gt;d__5.MoveNext() in D:\R1\src\Features\Core\Portable\FindUsages\DefinitionItem.DefaultDefinitionItem.cs:line 54\r
--- End of stack trace from previous location where exception was thrown ---\r
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r
   at Microsoft.CodeAnalysis.Editor.GoToDefinition.AbstractGoToSymbolService.&lt;GetSymbolsAsync&gt;d__1.MoveNext() in D:\R1\src\EditorFeatures\Core\GoToDefinition\AbstractGoToSymbolService.cs:line 42\r
--- End of stack trace from previous location where exception was thrown ---\r
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()\r
   at Microsoft.CodeAnalysis.Editor.NavigableSymbols.NavigableSymbolService.NavigableSymbolSource.&lt;GetNavigableSymbolAsync&gt;d__7.MoveNext() in D:\R1\src\EditorFeatures\Core.Wpf\NavigableSymbols\NavigableSymbolService.NavigableSymbolSource.cs:line 66\r
--- End of stack trace from previous location where exception was thrown ---\r
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.GoToDefMouseHandler.&lt;QueryNavigableSymbolAsync&gt;d__34.MoveNext()\r
--- End of stack trace from previous location where exception was thrown ---\r
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.GoToDefMouseHandler.&lt;SetMouseCursorAndNavigableSpanHelperAsync&gt;d__32.MoveNext()\r
--- End of stack trace from previous location where exception was thrown ---\r
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.GoToDefMouseHandler.&lt;SetMouseCursorAndNavigableSpanHelperAsync&gt;d__32.MoveNext()\r
--- End of stack trace from previous location where exception was thrown ---\r
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.GoToDefMouseHandler.&lt;&gt;c__DisplayClass31_0.&lt;&lt;SetMouseCursorAndNavigableSpanAsync&gt;b__0&gt;d.MoveNext()\r
--- End of stack trace from previous location where exception was thrown ---\r
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r
   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__76.MoveNext()\r
--- End of stack trace from previous location where exception was thrown ---\r
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r
   at Microsoft.VisualStudio.Threading.JoinableTask`1.&lt;&lt;JoinAsync&gt;g__JoinSlowAsync|3_0&gt;d.MoveNext()\r
--- End of stack trace from previous location where exception was thrown ---\r
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.GoToDefMouseHandler.&lt;SetMouseCursorAndNavigableSpanAsync&gt;d__31.MoveNext()\r
--- End of stack trace from previous location where exception was thrown ---\r
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.&lt;CallExtensionPointAsync&gt;d__37.MoveNext()\r
--- End of stack trace from previous location where exception was thrown ---\r
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #58612

### CODE REVIEW

**Review by davidwengier — APPROVED** [review]

File: src/Features/Core/Portable/FindUsages/DefinitionItem.DefaultDefinitionItem.cs [hunk 1]
```diff
@@ -84,19 +84,11 @@ private bool TryNavigateToMetadataSymbol(Workspace workspace, string symbolKey)
...
-                var project = projectAndSymbol.project;
-                var symbol = projectAndSymbol.symbol;
-                if (symbol == null || project == null)
-                {
-                    return false;
-                }
-
-                if (symbol.Kind == SymbolKind.Namespace)
+                var projectAndSymbol = await TryResolveSymbolInCurrentSolutionAsync(workspace, symbolKey).ConfigureAwait(false);
+                if (projectAndSymbol is not (var project, { Kind: not SymbolKind.Namespace } symbol))
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/FindUsages/DefinitionItem.DefaultDefinitionItem.cs:91]: Double negative make Cyrus brain hurt :-)

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/Features/Core/Portable/FindUsages/DefinitionItem.DefaultDefinitionItem.cs (hunk 1 above)
Comment (sharwell) [reply src/Features/Core/Portable/FindUsages/DefinitionItem.DefaultDefinitionItem.cs:91]: Yeah, me too
