### PR TITLE
Move static members to another type - qualifies static member references in the moved members

### LINKED ISSUE #79806: Move static members to another type... doesn't modify references to static members it doesn't move
**Version Used**: 
VS 2022 17.14.11

**Steps to Reproduce**:

1. put this code into a .cs file
```cs
internal class ClassWithStaticMembers
{

    public static int StaticInt { get; set; }
    public static string StaticString { get; set; }
    public static void StaticMethod()
    {
        Console.WriteLine(StaticString + StaticInt);
    }
}
```
2. execute  `Move static members to another type...` from the context menu of StaticMethod()
3. do not select other members, and hit OK
4. observe that the method in the created file looks like this
```cs
    public static void StaticMethod()
    {
        Console.WriteLine(StaticString + StaticInt);
    }
```
instead of this
```cs
    public static void StaticMethod()
    {
        Console.WriteLine(ClassWithStaticMembers.StaticString + ClassWithStaticMembers.StaticInt);
    }
```

**Expected Behavior**:
references to static members in the source class that are not moved should now be qualified with the identifier of the source class
**Actual Behavior**:
references to static members are not qualified, yielding uncompiling code.

### PR DESCRIPTION
**Pull request by akhera99**
Fixes #79806

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/CodeActions/MoveStaticMembers/CSharpMoveStaticMembersTests.cs [hunk 1]
```diff
@@ -792,6 +792,53 @@ public static int TestMethod()
             """, "Class1Helpers.cs", selectedMembers, "Class1Helpers").ConfigureAwait(false);
     }
 
+    [Fact]
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/CodeActions/MoveStaticMembers/CSharpMoveStaticMembersTests.cs]: workitem.

File: src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersWithDialogCodeAction.cs [hunk 2]
```diff
@@ -371,4 +388,67 @@ private static async Task<SyntaxNode> FixReferencesSingleDocumentAsync(
...
+            {
+                var symbolInfo = semanticModel.GetSymbolInfo(identifierNode, cancellationToken);
+                var symbol = symbolInfo.Symbol;
+
+                var selectedMemberNames = selectedMembers.Select(m => m.Name).ToImmutableHashSet();
+
+                // Check if it's a static member from the original class that isn't being moved
+                if (symbol != null &&
+                    symbol.IsStatic &&
+                    symbol.ContainingType != null &&
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersWithDialogCodeAction.cs]:
```suggestion
                if (symbol is { IsStatic: true, ContainingType: { } containingType } &&
```

File: src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersWithDialogCodeAction.cs [hunk 3]
```diff
@@ -371,4 +388,67 @@ private static async Task<SyntaxNode> FixReferencesSingleDocumentAsync(
...
+                    nodesToUpdate.Add((identifierNode, qualified));
+                }
+            }
+        }
+
+        if (nodesToUpdate.Count > 0)
+        {
+            root = root.ReplaceNodes(
+                nodesToUpdate.Select(t => t.original),
+                (original, _) => nodesToUpdate.First(t => t.original == original).replacement);
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersWithDialogCodeAction.cs]: this should be a dictionary, so we don't have the linear passes here.

Comment (akhera99) [reply src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersWithDialogCodeAction.cs]: true, fixed.

File: src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersWithDialogCodeAction.cs [hunk 4]
```diff
@@ -371,4 +388,64 @@ private static async Task<SyntaxNode> FixReferencesSingleDocumentAsync(
...
+        var generator = SyntaxGenerator.GetGenerator(sourceDoc);
+
+        var members = memberNodes
+            .Select(node => root.GetCurrentNode(node))
+            .WhereNotNull();
+        var nodesToUpdate = new Dictionary<SyntaxNode, SyntaxNode>();
+
+        foreach (var memberNode in members)
+        {
+            foreach (var identifierNode in memberNode.DescendantNodes().Where(
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersWithDialogCodeAction.cs:419]: it's intentional that you're only walking into the member nodes to update things?  (i'm not saying this is incorrect, i'm genuinely just asking if thjat's intentional).  If so, please doc why.

File: src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersWithDialogCodeAction.cs [hunk 5]
```diff
@@ -371,4 +388,64 @@ private static async Task<SyntaxNode> FixReferencesSingleDocumentAsync(
...
+                var symbolInfo = semanticModel.GetSymbolInfo(identifierNode, cancellationToken);
+                var symbol = symbolInfo.Symbol;
+
+                var selectedMemberNames = selectedMembers.Select(m => m.Name).ToImmutableHashSet();
+
+                // Check if it's a static member from the original class that isn't being moved
+                if (symbol is { IsStatic: true, ContainingType: { } containingType } &&
+                    symbol.ContainingType.Name == originalType.Name &&
+                    !selectedMembers.Contains(symbol) &&
+                    !selectedMemberNames.Contains(symbol.Name))
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersWithDialogCodeAction.cs]: i don't undersatnd the 'name' check.  what is it for?

Comment (akhera99) [reply src/Features/Core/Portable/MoveStaticMembers/MoveStaticMembersWithDialogCodeAction.cs]: Something I forgot to remove after adding the Contains check above.

**Review by JoeRobich — APPROVED** [review]
