### PR TITLE
Prevent Format String analyzer from crashing on a local function named Format

### LINKED ISSUE #29398: CSharpValidateFormatStringDiagnosticAnalyzer crashes for local function named Format
Visual Studio 15.8.1

```c#
public class C
{
    public void M()
    {
        Format();
        void Format() { }
    }
}
```

Gives:

> AD0001 Analyzer 'Microsoft.CodeAnalysis.CSharp.ValidateFormatString.CSharpValidateFormatStringDiagnosticAnalyzer' threw the following exception:

```
Exception occurred with following context:
Compilation: RoslynRepro
SyntaxTree: C:\Users\jmusser\Source\Repos\RoslynRepro\RoslynRepro\Class1.cs
SyntaxNode: Format() [InvocationExpressionSyntax]@[55..63) (4,8)-(4,16)

System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Symbols.SourceOrdinaryMethodSymbol' to type 'Microsoft.CodeAnalysis.INamedTypeSymbol'.
   at Microsoft.CodeAnalysis.ValidateFormatString.AbstractValidateFormatStringDiagnosticAnalyzer`1.TryGetValidFormatMethodSymbol(SyntaxNodeAnalysisContext context, SymbolInfo symbolInfo)
   at Microsoft.CodeAnalysis.ValidateFormatString.AbstractValidateFormatStringDiagnosticAnalyzer`1.AnalyzeNode(SyntaxNodeAnalysisContext context, INamedTypeSymbol formatProviderType)
   at Microsoft.CodeAnalysis.ValidateFormatString.AbstractValidateFormatStringDiagnosticAnalyzer`1.<>c__DisplayClass15_0.<Initialize>b__1(SyntaxNodeAnalysisContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__44`1.<ExecuteSyntaxNodeAction>b__44_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

[(repros on master on sharplab, too)](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAN0QSwGYE8A+AAgMwAEhATKQMICwAUAN4OmvlmEAspAsgBQBKFm2b0240gDEA9gkgxBAbmETy3GXIgKBpRqQC+Kgw0P0gA===)

### PR DESCRIPTION
**Pull request by chborl**
Fixes #29398 

Added a check to see if the Format method is a local function in CSharp.

### CODE REVIEW

File: src/Features/Core/Portable/ValidateFormatString/AbstractValidateFormatStringDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -298,6 +298,11 @@ private IParameterSymbol GetParameterWithMatchingName(ImmutableArray<IParameterS
                 return null;
             }
 
+            if (((IMethodSymbol)symbolInfo.Symbol).MethodKind == MethodKind.LocalFunction)
+            {
+                return null;
+            }
+
             var containingType = (INamedTypeSymbol)symbolInfo.Symbol.ContainingSymbol;
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ValidateFormatString/AbstractValidateFormatStringDiagnosticAnalyzer.cs]: i would also change this to .ContainingType.  Or at least validate that .ContainingSymbol is actually a NamedType.  Otehrwise, you'll probably just crash here in the future with some other new language construct.
