### PR TITLE
Do not capture pinned locals into state machine

### LINKED ISSUE #9775: Compiler captures fixed/pinned locals into async state machine in Debug
Reported by customer using Update1, 
but reproducable in current master

**Steps to Reproduce**:

``` C#
        private static async Task<int> Test(byte[] arr)
        {
            unsafe
            {
                fixed(byte * ptr = &arr[3])
                {
                    ptr->ToString();
                }
            }

            await Task.Yield();

            return 42;
        }
```

**Expected Behavior**:

There pinned local introduced by the fixed statement should stay a pinned local, otherwise ptr may be pointing to random movable memory and cause AVs

MoveNext ()

/o+

```
    .locals init (
        [0] int32,
        [1] int32,
        [2] uint8& pinned ptr,      <---------
        [3] valuetype [mscorlib]System.Runtime.CompilerServices.YieldAwaitable/YieldAwaiter,
        [4] valuetype [mscorlib]System.Runtime.CompilerServices.YieldAwaitable,
        [5] class [mscorlib]System.Exception
```

**Actual Behavior**:
/o-

```
        [0] int32,
        [1] int32,
        [2] valuetype [mscorlib]System.Runtime.CompilerServices.YieldAwaitable/YieldAwaiter,
        [3] valuetype [mscorlib]System.Runtime.CompilerServices.YieldAwaitable,
        [4] class ConsoleApplication2.Program/'<Test>d__1',
        [5] class [mscorlib]System.Exception
```

### PR DESCRIPTION
**Pull request by cston**
Fixes #9775.

### CODE REVIEW

**Comment by cston** [comment]
@dotnet/roslyn-compiler, @tmat please review.

**Comment by cston** [comment]
@dotnet/roslyn-compiler, @tmat, please review.

**Comment by tmat** [comment]
:shipit:

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncLocalsTests.cs [hunk 1]
```diff
@@ -1273,5 +1273,263 @@ public class C
                 }, module.GetFieldNames("C.<F>d__0"));
             });
         }
+
+        [WorkItem(9775, "https://github.com/dotnet/roslyn/issues/9775")]
+        [Fact]
+        public void Fixed_Debug()
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncLocalsTests.cs]: >public void Fixed_Debug() [](start = 8, length = 25)

Is it possible to get in a situation when a pinned local has to be spilled? Do we have any tests for scenarios like this?

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncLocalsTests.cs [hunk 2]
```diff
@@ -1273,5 +1273,263 @@ public class C
...
+        await Task.Yield();
+        return i;
+    }
+    static void Main()
+    {
+        var i = F(new byte[] { 1, 2, 3 }).Result;
+        Console.Write(i);
+    }
+}";
+            var verifier = CompileAndVerify(text, options: TestOptions.UnsafeReleaseExe, expectedOutput: @"1");
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncLocalsTests.cs]: >TestOptions.UnsafeReleaseExe [](start = 59, length = 28)

It looks like this test option uses OptimizationLevel.Release and the modified code is not used for this option. Consider also testing with OptimizationLevel that would cause compiler to take the modified code path.

Comment (cston) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncLocalsTests.cs]: Debug is used at line 1412.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncLocalsTests.cs]: > Debug is used at line 1412.

Thanks!

File: src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncLocalsTests.cs (hunk 1 above)
Comment (cston) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncLocalsTests.cs]: `unsafe { ... await expr ... }` results in `error CS4004: Cannot await in an unsafe context`. We have several tests for that error.

Comment (AlekseyTs) [inline src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncLocalsTests.cs]: Thanks.
