### PR TITLE
Validate help links

### LINKED ISSUE #50203: IDE0079 should not warn when suppressing CA1716
```cs
#pragma warning disable CA1716 // Identifiers should not match keywords
namespace Select
#pragma warning restore CA1716 // Identifiers should not match keywords
{
}
```

Animation

### LINKED ISSUE #50302: Some rules doesn't have correct help link
**Version Used**: 

https://github.com/dotnet/roslyn/pull/50278/commits/29f7328867c68615c42dade4d2eecb193902fea1

**Steps to Reproduce**:

In https://github.com/dotnet/roslyn/pull/50278/commits/29f7328867c68615c42dade4d2eecb193902fea1, run `dotnet test --filter "FullyQualifiedName~CSharp_VerifyIDECodeStyleOptionsAreConfigurable"` in `src\EditorFeatures\Test`

The result is:

```
  Error Message:
   Invalid help link for IDE0001
```

The issue is simply in:

https://github.com/dotnet/roslyn/blob/afd10305a37c0ffb2cfb2c2d8446154c68cfa87a/src/Features/Core/Portable/SimplifyTypeNames/SimplifyTypeNamesDiagnosticAnalyzerBase.cs#L48-L54

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #50302

### CODE REVIEW

File: src/Features/Core/Portable/SimplifyTypeNames/SimplifyTypeNamesDiagnosticAnalyzerBase.cs [hunk 1]
```diff
@@ -51,15 +53,17 @@ internal abstract class SimplifyTypeNamesDiagnosticAnalyzerBase<TLanguageKindEnu
...
 
         private static readonly DiagnosticDescriptor s_descriptorPreferBuiltinOrFrameworkType = new(IDEDiagnosticIds.PreferBuiltInOrFrameworkTypeDiagnosticId,
             s_localizableTitleSimplifyNames,
             s_localizableMessage,
             DiagnosticCategory.Style,
             DiagnosticSeverity.Hidden,
             isEnabledByDefault: true,
-            customTags: DiagnosticCustomTags.Unnecessary);
+            helpLinkUri: DiagnosticHelper.GetHelpLinkForDiagnosticId(IDEDiagnosticIds.PreferBuiltInOrFrameworkTypeDiagnosticId),
+            customTags: DiagnosticCustomTags.Unnecessary.Concat(EnforceOnBuildValues.PreferBuiltInOrFrameworkType.ToCustomTag()).ToArray());
```
Comment (Youssef1313) [inline src/Features/Core/Portable/SimplifyTypeNames/SimplifyTypeNamesDiagnosticAnalyzerBase.cs:66]: Why is this needed here? there is already a separate analyzer for this:

https://github.com/dotnet/roslyn/blob/d57cddbaa7536c8741db191be76d2a773fd0b86f/src/Features/Core/Portable/PreferFrameworkType/PreferFrameworkTypeDiagnosticAnalyzerBase.cs#L12

Both are even using the same ID.

Comment (mavasani) [reply src/Features/Core/Portable/SimplifyTypeNames/SimplifyTypeNamesDiagnosticAnalyzerBase.cs:66]: I am not sure to be honest. @CyrusNajmabadi would probably know.

**Review by mavasani — APPROVED** [review]
