### PR TITLE
Fixed completion list for explicit interface implementation

### LINKED ISSUE #15988: Explicit Interface Implementation Completions show Object methods
**Version Used**: 2017 RC Refresh

```C#
class C : IComparable {
	int IComparable.
}
```

Pressing Ctrl+Space after the `.` will show the four methods from `object`, even though they cannot be implemented with this syntax.

### LINKED ISSUE #19947: Completion list for explicit interface implementations includes invalid members
image

Only implementable members declared immediately in the named interface should be in the list, members from derived interfaces will cause an error.

### PR DESCRIPTION
**Pull request by zaytsev-victor**
Fixes #15988
Fixes #19947

**Customer scenario**
Completion list for explicit interface implementations includes invalid members.

**Bugs this fixes:**
#19947, #15988

**Workarounds, if any**
None

**Risk**
Low, affected only ```ExplicitInterfaceMemberCompletionProvider``` class.

**Performance impact**

**Is this a regression from a previous update?**

**Root cause analysis:**
Completion members aren't filtered by interface type. Tests doesn't check that invalid members are not presented in code completion.

**How was the bug found?**

customer reported

### CODE REVIEW

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs [hunk 1]
```diff
@@ -82,7 +82,7 @@ internal override bool IsInsertionTrigger(SourceText text, int characterPosition
             var members = semanticModel.LookupSymbols(
                 position: name.SpanStart,
                 container: symbol)
-                    .WhereAsArray(s => !s.IsStatic)
+                    .WhereAsArray(s => !s.IsStatic && s.ContainingType.Equals(symbol))
```
Comment (sharwell) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs]: ❓ Do we know why `LookupSymbols` is including these symbols in the first place? Is there a reason we don't want to implement this correction at that level instead?

Comment (rchande) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs]: Doesn't LookupSymbols generally include base members?

**Comment by rchande** [comment]
test windows_debug_vs-integration_prtest

**Comment by rchande** [comment]
test windows_release_vs-integration_prtest

File: src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs (hunk 1 above)
Comment (CyrusNajmabadi) [inline src/Features/CSharp/Portable/Completion/CompletionProviders/ExplicitInterfaceMemberCompletionProvider.cs]: I'm not certain why we're even using LookupSymbols...  We already have the interface type.  So it's unclear to me why we don't just get the members we need directly off that type.

**Comment by CyrusNajmabadi** [comment]
Hrmm..> Would still have liked my comment addressed :)   but that's ok.  The current code is fine with me.
