### PR TITLE
Have VisualStudioDocumentNavigationService perform bounds checks

### LINKED ISSUE #7660: VS2015.1: ArgumentOutOfRangeException while inline renaming in razor
With `Index.cshtml` looking like

``` cshtml
@using ArgumentOutOfRangeTest.Controllers
@model Some
@Html.GetTest().TestMethod(x =>
{
    x.SomeMethod(new { Controller = "Test", Action = nameof(TestController.Other) });
}).GetHtml()
```

I set the cursor to `Other`, pressed `F2` and got an error MessageBox telling me about a ArgumentOutOfRangeException for parametername position.
Pressing `F2` again, it did the same error again.
Attaching Visual Studio got me this stacktrace:

```
ArgumentOutOfRangeException: param: position
   at Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetLineNumberFromPosition(Int32 position)
   at Microsoft.VisualStudio.Text.Implementation.TextSnapshot.GetLineNumberFromPosition(Int32 position)
   at Microsoft.CodeAnalysis.Text.Extensions.SnapshotSourceText.LineInfo.IndexOf(Int32 position)
   at Microsoft.CodeAnalysis.Text.Extensions.SnapshotSourceText.LineInfo.GetLineFromPosition(Int32 position)
   at Microsoft.CodeAnalysis.Shared.Extensions.SourceTextExtensions.GetLineAndOffset(SourceText text, Int32 position, Int32& lineNumber, Int32& offset)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Extensions.SourceTextExtensions.GetVsTextSpanForSpan(SourceText text, TextSpan textSpan)
   at Microsoft.VisualStudio.LanguageServices.Implementation.VisualStudioDocumentNavigationService.CanNavigateToSpan(Workspace workspace, DocumentId documentId, TextSpan textSpan)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.AbstractEditorInlineRenameService.GetRenameInfo(IEnumerable`1 refactorNotifyServices, Document document, SyntaxToken triggerToken, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.AbstractEditorInlineRenameService.GetRenameInfo(Document document, Int32 position, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.AbstractEditorInlineRenameService.GetRenameInfoAsync(Document document, Int32 position, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameService.StartInlineSession(Document document, TextSpan textSpan, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.RenameCommandHandler.ExecuteRenameWorker(RenameCommandArgs args, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.RenameCommandHandler.<>c__DisplayClass37_0.<ExecuteCommand>b__0(IWaitContext waitContext)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Utilities.VisualStudioWaitIndicator.Wait(String title, String message, Boolean allowCancel, Action`1 action)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.RenameCommandHandler.ExecuteCommand(RenameCommandArgs args, Action nextHandler)
   at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.ExecuteHandlers[T](IList`1 commandHandlers, T args, Action lastHandler)
   at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.Microsoft.CodeAnalysis.Editor.ICommandHandlerService.Execute[T](IContentType contentType, T args, Action lastHandler)
   at Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.ExecuteRename(ITextBuffer subjectBuffer, IContentType contentType, Action executeNextCommandTarget)
   at Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.ExecuteVisualStudio2000(Guid& pguidCmdGroup, UInt32 commandId, UInt32 executeInformation, IntPtr pvaIn, IntPtr pvaOut, ITextBuffer subjectBuffer, IContentType contentType)
   at Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.Exec(Guid& pguidCmdGroup, UInt32 commandId, UInt32 executeInformation, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Html.Interop.OleToCommandTargetShim.Invoke(Guid group, Int32 id, Object inputArg, Object& outputArg)
   at Microsoft.Html.Editor.Commands.HtmlMainController.Invoke(Guid group, Int32 id, Object inputArg, Object& outputArg)
   at Microsoft.VisualStudio.Html.Interop.CommandTargetToOleShim.Exec(Guid& guidCommandGroup, UInt32 commandID, UInt32 commandExecOpt, IntPtr variantIn, IntPtr variantOut)
   at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Editor.Implementation.CompoundTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
```

While trying to create a minimal reproduction (see `Index.cshtml` above), VS bugged me all the time with an messagebox, telling me `You cannot rename this element` (translated from german).
After restarting Visual Studio it was able to rename it without problems.

Unfortunately i couldn't reproduce it and also the renaming in the originally affected solution worked after restarting Visual Studio, so i'm opening this issue in the hope that someone will figure it out eventually.

EDIT: but i just run into it again so it seems to happen after some time.

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #7660
Fixes internal bugs 112211, 136895, 224318, 235409

We have a number of bugs (listed above) that show features trying to
navigate to positions that are not within the bounds of the documents in
which they are navigating. I have not been able to figure out the common
root cause of this problem, but they all flow through the
VisualStudioDocumentNavigationService, so adding bounds checks there
should alleviate the symptoms (reported as crashes, hangs, and error
dialogs).

Ask Mode
============

**Customer scenario**: The customer tries to navigate using the Navigation Bar or initiate a rename in a Razor file, and they are sometimes met with a crash, a hang, or an error dialog. **The total hit count from the Watson is currently 6686**. It is unclear why this only happens occasionally, and we have not been able to reproduce the failure locally.

**Bugs this fixes:** 

#7660
https://devdiv.visualstudio.com/DevDiv/_workitems?id=112211
https://devdiv.visualstudio.com/DevDiv/_workitems?id=136895
https://devdiv.visualstudio.com/DevDiv/_workitems?id=224318
https://devdiv.visualstudio.com/DevDiv/_workitems?id=235409

**Workarounds, if any**: None. The product crashes, hangs, or shows an error dialog.

**Risk**: Fairly low. We now return false instead of true for CanNavigateTo* for ContainedDocuments if their navigation target is outside the bounds of the document, which will cause rename to give a "You cannot rename this element" dialog instead of an "ArgumentOutOfRange" dialog. For the actual TryNavigateTo* methods, we are just adjusting the requested bounds to be within the bounds of the Document's length. In the worst case that I can imagine, we will navigate to the end of the document instead of some non-existent (and crashing) location that was requested of us.

**Performance impact**: Low perf impact, it's just a few math operations and one allocation, and it's only done on infrequent user-initiated actions.

**Is this a regression from a previous update?** No

**Root cause analysis:** We do not understand the root cause at this time. However, this change should address the symptoms being reported by customers (and Watson).

**How was the bug found?** Watson and customer reports

### CODE REVIEW

**Comment by dpoeschl** [comment]
Tagging for review @dotnet/roslyn-ide @jasonmalinowski (discussed offline) @heejaechang (made a similar change for the TodoCommentIncrementalAnalyzer)

**Comment by dpoeschl** [comment]
Note: There is still some underlying problem here that is unresolved. Figuring that out will now be tracked by https://github.com/dotnet/roslyn/issues/16365

**Comment by rchande** [comment]
How is anyone going to diagnose #16365 once this fix goes in? As mentioned earlier it can't be reproduced locally and now there won't be any crash dumps coming in.

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs [hunk 1]
```diff
@@ -48,6 +48,13 @@ public bool CanNavigateToSpan(Workspace workspace, DocumentId documentId, TextSp
 
             var document = workspace.CurrentSolution.GetDocument(documentId);
```
Comment (heejaechang) [inline src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs]: how one can guarantee TextSpan given is belong to CurrentSolution snapshot? either API needs to change to accept Document and span that belong to the Document snapshot, and regardless this crash, this implementation should always make sure given span is valid.

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs [hunk 2]
```diff
@@ -82,6 +89,13 @@ public bool CanNavigateToPosition(Workspace workspace, DocumentId documentId, in
...
             var text = document.GetTextAsync(CancellationToken.None).WaitAndGetResult(CancellationToken.None);
+
```
Comment (heejaechang) [inline src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs]: same as previous comment.

**Comment by heejaechang** [comment]
👍

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs (hunk 1 above)
Comment (heejaechang) [inline src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs]: we might introduce SnapshotSpan like editor to handle 2 together?

**Comment by dpoeschl** [comment]
@rchande We have a bunch of dumps still that can be investigated, but for a limited time... I'll do a non-fatal Watson if the positions/spans are out of bounds.

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs [hunk 3]
```diff
@@ -176,6 +193,40 @@ public bool TryNavigateToPosition(Workspace workspace, DocumentId documentId, in
...
+        /// is either no navigation or navigation to the end of the document.
+        /// See https://github.com/dotnet/roslyn/issues/7660 for more details.
+        /// </summary>
+        private static TextSpan GetSpanWithinDocumentBounds(TextSpan span, int documentLength)
+        {
+            int newStart = Math.Max(span.Start, 0);
+            int newEnd = Math.Min(span.Start + span.Length, documentLength);
+            int newLength = newEnd - newStart;
+
+            return new TextSpan(newStart, newLength);
```
Comment (Pilchie) [inline src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs]: Could consider: 
```C#
return TextSpan.FromBounds(GetPositionWithinDocumentBounds(span.Start, documentLength), GetPositionWithinDocumentBounds(span.End, documentLength)); 
```
instead to only have math in one place.

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs (hunk 1 above)
Comment (dpoeschl) [inline src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs]: @heejaechang I have filed this work as https://github.com/dotnet/roslyn/issues/16367, since it's a larger change than this tactical crash-preventing fix. It's a good idea, though. :smile: Do you feel like *this* change should be gated on this additional work?

**Comment by dpoeschl** [comment]
@Pilchie @rchande I've added the non-fatal Watsons.

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs [hunk 4]
```diff
@@ -27,6 +30,7 @@ internal sealed class VisualStudioDocumentNavigationService : ForegroundThreadAf
     {
         private readonly IServiceProvider _serviceProvider;
         private readonly IVsEditorAdaptersFactoryService _editorAdaptersFactoryService;
+        private readonly IEnumerable<Lazy<IErrorLoggerService>> _errorLoggers;
```
Comment (rchande) [inline src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs]: Unused?

**Comment by dpoeschl** [comment]
@rchande Fixed. Thanks.

File: src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs (hunk 1 above)
Comment (heejaechang) [inline src/VisualStudio/Core/Def/Implementation/Workspace/VisualStudioDocumentNavigationService.cs]: @dpoeschl nope. I already gave +1

**Comment by dpoeschl** [comment]
Tagging @MattGertz for RC.3 Escrow consideration.

**Comment by natidea** [comment]
@dpoeschl  Please review/complete the Ask Mode information on [112211](https://devdiv.visualstudio.com/DevDiv/_workitems?id=112211)

**Comment by dpoeschl** [comment]
@natidea Done.

**Comment by natidea** [comment]
Approved to merge
