### PR TITLE
Fix quick info for pp symbols

### LINKED ISSUE #78171: Preprocessing directives not handled correctly in CommonSemanticQuickInfoProvider.BindToken(
```
Unexpected value 'Preprocessing' of type 'Microsoft.CodeAnalysis.SymbolKind'
   at Microsoft.CodeAnalysis.Shared.Extensions.ISymbolExtensions.IsSymbolAccessibleCore(ISymbol symbol, ISymbol within, ITypeSymbol throughType, Boolean& failedThroughTypeCheck)
   at Microsoft.CodeAnalysis.QuickInfo.CommonSemanticQuickInfoProvider.<>c__DisplayClass12_0.<BindToken>b__0(ISymbol s)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.CodeAnalysis.QuickInfo.CommonSemanticQuickInfoProvider.BindToken(SolutionServices services, SemanticModel semanticModel, SyntaxToken token, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.QuickInfo.CommonSemanticQuickInfoProvider.<ComputeFromLinkedDocumentsAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.QuickInfo.CommonSemanticQuickInfoProvider.<ComputeQuickInfoDataAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.QuickInfo.CommonSemanticQuickInfoProvider.<BuildQuickInfoAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.QuickInfo.CommonQuickInfoProvider.<GetQuickInfoAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.CodeAnalysis.QuickInfo.CommonQuickInfoProvider.<GetQuickInfoAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.<PerformFunctionAsync>d__3`1.MoveNext()
```

While editing code

```C#
    /// <summary>
    /// Removes entries from a dictionary based on a specified condition. The condition is defined by a function that
    /// evaluates each key-value pair.
    /// </summary>
    public static void Remove<TKey, TValue, TArg>(this IDictionary<TKey, TValue> dictionary, Func<TKey, TValue, TArg, bool> predicate, TArg arg)
        where TKey : notnull
    {
#if NET
        // .NET supports removing while enumerating:
        foreach (var entry in dictionary)
        {
            if (predicate(entry.Key, entry.Value, arg))
            {
                dictionary.Remove(entry.Key);
            }
        }
#else
        if (dictionary.IsEmpty())
        {
            return;
        }

        using var _ = ArrayBuilder<TKey>.GetInstance(out var keysToRemove);
        foreach (var entry in dictionary)
        {
            if (predicate(entry.Key, entry.Value, arg))
            {
                keysToRemove.Add(entry.Key);
            }
        }

        foreach (var key in keysToRemove)
        {
            dictionary.Remove(key);
        }
#endif
    }
```

### PR DESCRIPTION
**Pull request by Rekkonnect**
Fixes #78171

CC @CyrusNajmabadi

### CODE REVIEW

File: src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs [hunk 1]
```diff
@@ -5544,6 +5544,32 @@ static void Main(string[] args)
             """);
     }
 
+    [Fact, WorkItem("https://github.com/dotnet/roslyn/issues/78171")]
+    public async Task TestPreprocessingSymbol()
+    {
+        var markup = """
+
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/QuickInfo/SemanticQuickInfoSourceTests.cs:5551]:
```suggestion
```

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks!
