### PR TITLE
Fix F1 keyword for interpolated and verbatim strings

### LINKED ISSUE #46986: F1 Help service doesn't detect interpolated or verbatim string tokens
Clicking f1 on a `$` sign or `@` sign doesn't use the correct f1 keywords.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #46986

`$_CSharpKeyword`: [This](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/tokens/interpolated.md) article is what have this f1 keyword.

`@_CSharpKeyword`: [This](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/tokens/verbatim.md) article is what have this f1 keyword.

I removed the following part:

```
            if (token.IsKind(SyntaxKind.PlusEqualsToken))
            {
                text = "+=_CSharpKeyword";
                return true;
            }

            if (token.IsKind(SyntaxKind.MinusEqualsToken))
            {
                text = "-=_CSharpKeyword";
                return true;
            }
```

These if conditions are impossible to be met because of the check `SyntaxFacts.IsAssignmentExpressionOperatorToken` before them. `SyntaxFacts.IsAssignmentExpressionOperatorToken` will already return true for MinusEqualsToken and PlusEqualsTokene.

~~It even seem that `SyntaxFacts.IsAssignmentExpressionOperatorToken` is also redundant, this check is already done in `IsOperator`.~~ (This was incorrect, I'll revert it)

### CODE REVIEW

File: src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs [hunk 1]
```diff
@@ -186,6 +186,20 @@ private static bool TryGetTextForOperator(SyntaxToken token, Document document,
...
+            {
+                text = "$_CSharpKeyword";
+                return true;
+            }
+
+            if (token.IsKind(SyntaxKind.StringLiteralToken) && token.ValueText[0] == '@')
+            {
+                text = "@_CSharpKeyword";
+                return true;
+            }
```
Comment (Youssef1313) [inline src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:201]: Currently, the dotnet/docs doesn't have any `@$_CSharpKeyword` F1 keyword. I opened a PR to add this in docs. Are you okay with this new F1 keyword and adding the following here?

```csharp
        if (token.IsKind(SyntaxKind.InterpolatedVerbatimStringStartToken))
        {
            text = "@$_CSharpKeyword";
            return true;
        }
```

**Comment by Youssef1313** [comment]
```
        [WorkItem(867572, "http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/867572")]
        [Fact, Trait(Traits.Feature, Traits.Features.F1Help)]
        public async Task TestSubscription()
        {
            await TestAsync(
@"class CCC
{
    event System.Action e;
    void M()
    {
        e +[||]= () => {
        };
    }
}", "CCC.e.add");
        }
```

This test failed unintentionally with my changes. But actually the new behavior is what makes sense. The result should be `+=_CSharpKeyword` instead of `CCC.e.add`.

File: src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs [hunk 2]
```diff
@@ -186,39 +186,41 @@ private static bool TryGetTextForOperator(SyntaxToken token, Document document,
                 return true;
             }
 
-            if (token.IsKind(SyntaxKind.ColonColonToken))
+            if (token.IsKind(SyntaxKind.InterpolatedStringStartToken) ||
+                token.IsKind(SyntaxKind.InterpolatedStringEndToken) ||
+                token.IsKind(SyntaxKind.InterpolatedStringTextToken))
             {
-                text = "::_CSharpKeyword";
+                text = "$_CSharpKeyword";
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:193]: can you provide the links these now go to.

File: src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs [hunk 3]
```diff
@@ -186,39 +186,41 @@ private static bool TryGetTextForOperator(SyntaxToken token, Document document,
...
-            if (token.IsKind(SyntaxKind.EqualsGreaterThanToken))
+            if (token.Kind() == SyntaxKind.ColonToken && token.Parent is NameColonSyntax)
             {
-                text = "=>_CSharpKeyword";
+                text = "cs_namedParameter";
                 return true;
             }
 
-            if (token.IsKind(SyntaxKind.PlusEqualsToken))
+            if (token.IsKind(SyntaxKind.QuestionToken) && token.Parent is ConditionalExpressionSyntax)
```
Comment (CyrusNajmabadi) [inline src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:215]: should we do this for `:` as well.

File: src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs (hunk 2 above)
Comment (Youssef1313) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:193]: The `$_CSharpKeyword` should go to this:

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated

Comment (CyrusNajmabadi) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:193]: and is that where `$_CSharpKeyword` does redirect to?  Can you give me the links these produce directly, so i can validate they end up landing on an appropriate page?  Thanks!

File: src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs (hunk 3 above)
Comment (Youssef1313) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:215]: Pressing F1 on `:` in the following snippet:

```
    public class Test
    {
    }

    public class Class1 :/*F1 here*/ Test
    {
    }
```

Redirects to https://docs.microsoft.com/en-us/dotnet/api/system.nullable-1 on Visual Studio 16.6.4 on my machine. Surely the link in very weird.

@CyrusNajmabadi Do you want me to try fix everything I can in the F1 area in this PR? or keep it only for the newly added ones for string interpolation and verbatim string?

File: src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs (hunk 2 above)
Comment (Youssef1313) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:193]: https://msdn.microsoft.com/query/dev16.query?appId=Dev16IDEF1&l=EN-US&k=k($_CSharpKeyword);k(DevLang-csharp)&rd=true

Comment (CyrusNajmabadi) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:193]: That link takes me to https://docs.microsoft.com/en-us/.

Comment (Youssef1313) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:193]: It was redirecting correctly at the time I commented with it. For me, it now redirects nowhere. Just keeps loading without doing anything. Probably it's temporary issue with that service? Actually, **ALL** the F1 thing uses that link.

Comment (Youssef1313) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:193]: I can confirm that at the time of writing this, the whole service isn't working correctly. Pressing F1 on **anything**, for example await keyword, either take much loading time without redirecting anywhere, or redirects to the home docs page as you stated @CyrusNajmabadi.

Let's wait a little bit and check if the service will back to normal. Otherwise, I don't know what we should do.

But anyways, the PR just sets the f1 keyword for string interpolation and it matches the f1_keywords metadata in dotnet/docs. So, it should work whenever the service back to normal.

Comment (Youssef1313) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:193]: Also, adding @davidwengier as he touched this area before (https://github.com/dotnet/docs/pull/19700#issuecomment-664838915)

Comment (Youssef1313) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:193]: It actually redirects to "/Areas/Epx/Content/500.aspx?aspxerrorpath=/query/dev16.query" first, which in turn redirected to the home docs.
So, it's an internal server error.

File: src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs [hunk 4]
```diff
@@ -186,39 +186,41 @@ private static bool TryGetTextForOperator(SyntaxToken token, Document document,
...
-                text = "+=_CSharpKeyword";
+                text = "?_CSharpKeyword";
                 return true;
             }
 
-            if (token.IsKind(SyntaxKind.MinusEqualsToken))
+            if (token.IsKind(SyntaxKind.EqualsGreaterThanToken))
             {
-                text = "-=_CSharpKeyword";
+                text = "=>_CSharpKeyword";
```
Comment (davidwengier) [inline src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:223]: This currently matches the comparison operators page and the lambda operators page. This needs a PR into docs to clean up, and a follow up here. I'd suggest removing `=>_CSharpKeyword` from the lambda page, and just using `lambda_CSharpKeyword`.

Tests for both variants would be good too, to ensure we don't regress it in future.

File: src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs (hunk 2 above)
Comment (davidwengier) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:193]: The query service seems to be pretty flaky at the moment, not sure what the deal is with that. The link above (msdn.microsoft.com/query/dev16.query?appId=Dev16IDEF1&l=EN-US&k=k($_CSharpKeyword);k(DevLang-csharp)&rd=true) worked for me, and looks how I suspect.

File: src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs [hunk 5]
```diff
@@ -186,39 +186,41 @@ private static bool TryGetTextForOperator(SyntaxToken token, Document document,
...
-                text = "?_CSharpKeyword";
+                text = "::_CSharpKeyword";
                 return true;
             }
 
-            if (token.IsKind(SyntaxKind.EqualsGreaterThanToken))
+            if (token.Kind() == SyntaxKind.ColonToken && token.Parent is NameColonSyntax)
             {
-                text = "=>_CSharpKeyword";
+                text = "cs_namedParameter";
```
Comment (davidwengier) [inline src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:211]: Probably could make this `namedParameter_CSharpKeyword` for consistency. It's already mapped in the docs.

File: src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs [hunk 6]
```diff
@@ -118,8 +118,8 @@ private string TryGetText(SyntaxToken token, SemanticModel semanticModel, Docume
                 TryGetTextForCombinationKeyword(token, syntaxFacts, out text) ||
                 TryGetTextForKeyword(token, syntaxFacts, out text) ||
                 TryGetTextForPreProcessor(token, syntaxFacts, out text) ||
-                TryGetTextForSymbol(token, semanticModel, document, cancellationToken, out text) ||
-                TryGetTextForOperator(token, document, out text))
+                TryGetTextForOperator(token, document, out text) ||
```
Comment (davidwengier) [inline src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:121]: Nit: The interpolated and verbatim string characters are not really operators are they? They are in the "Special characters" section of the docs, or the "Tokens" folder of the docs repo, so _maybe_ we should mirror that here?

I don't have strong feelings about this (though would have made this diff easier to read 😛)

**Review by davidwengier — APPROVED** [review]
Signing off as far as the help links go, I don't see any issues introduced here. The `=>` issue I mentioned looks like it is pre-existing so no reason to block this PR, but it would be nice to fix if you're in the mood :)

File: src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs (hunk 6 above)
Comment (Youssef1313) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs:122]: @davidwengier I've mode them to a new method.

File: src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs (hunk 4 above)
Comment (Youssef1313) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs]: @davidwengier The comparison operator page has the following f1 keywords:

```
  - "<_CSharpKeyword"
  - ">_CSharpKeyword"
  - "<=_CSharpKeyword"
  - ">=_CSharpKeyword"
```

none of them is `=>_CSharpKeyword`

Comment (davidwengier) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs]: Oops, you're right! My bad.

File: src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs (hunk 1 above)
Comment (Youssef1313) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs]: @davidwengier Should I add the combination?

Comment (davidwengier) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs]: Looks like that would regress the experience from a help page (albeit for string, which isn't great) to a generic 404 page, so I'd say leave it until after the doc page is created.

Comment (Youssef1313) [reply src/VisualStudio/CSharp/Impl/LanguageService/CSharpHelpContextService.cs]: @davidwengier I've a PR there
https://github.com/dotnet/docs/pull/20197

**Comment by Youssef1313** [comment]
Pinging @davidwengier 
Could you approve the docs PR?
Then, this should be ready to go.

**Comment by davidwengier** [comment]
I think its really up to the docs team to approve that PR, if they're happy with where that keyword goes, or if they think it should go to one of the specific operator pages, or indeed a new page.

**Comment by CyrusNajmabadi** [comment]
The link still isn't working for me :-/

**Comment by Youssef1313** [comment]
@CyrusNajmabadi What if you press F1 anything inside Visual Studio? (await keyword for example) Does it work?

**Comment by Youssef1313** [comment]
@davidwengier The PR that adds `@$_CSharpKeyword` is now merged.

**Review by davidwengier — APPROVED** [review]
LGTM

**Comment by Youssef1313** [comment]
@davidwengier Anything left to merge this?

**Comment by davidwengier** [comment]
@CyrusNajmabadi are you okay with this?

**Comment by CyrusNajmabadi** [comment]
Yup.  Thanks!
