### PR TITLE
Serialize document states without loading text

### LINKED ISSUE #43802: Serialize document states without loading text
**Version Used**: 16.6 Preview 3

Currently `DocumentStateChecksums` loads the text of documents here:

https://github.com/dotnet/roslyn/blob/1b17eae2aaa77c8c5f057dc657fc2a9d93fadb59/src/Workspaces/Core/Portable/Workspace/Solution/StateChecksums.cs#L239

This operation can load a large number of documents into a dictionary which are not all in use at the same time. This operation should instead place a _recoverable_ text in the dictionary, which can be loaded on demand at a point where it is needed.

🔗 This is the root cause of https://developercommunity.visualstudio.com/content/problem/1008598/vs-2019-constantly-crashing-because-of-addition-of.html

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #43802

### CODE REVIEW

File: src/Workspaces/Core/Portable/Workspace/Solution/StateChecksums.cs [hunk 1]
```diff
@@ -236,7 +236,7 @@ public DocumentStateChecksums(params object[] children) : base(WellKnownSynchron
 
             if (searchingChecksumsLeft.Remove(Text))
             {
-                result[Text] = await state.GetTextAsync(cancellationToken).ConfigureAwait(false);
+                result[Text] = await SerializableSourceText.FromTextDocumentStateAsync(state, cancellationToken).ConfigureAwait(false);
```
Comment (sharwell) [inline src/Workspaces/Core/Portable/Workspace/Solution/StateChecksums.cs:239]: 📝 This pull request's _sole purpose_ is to avoid the use of `GetTextAsync` here, and store recoverable text in `SolutionAsset` instead of `SourceText`.

File: src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+        }
+
+        public ImmutableArray<byte> GetChecksum()
+        {
+            if (Storage is not null)
+                return Storage.GetChecksum();
+            else if (Text is not null)
+                return Text.GetChecksum();
+            else
+                return ImmutableArray<byte>.Empty;
```
Comment (davidwengier) [inline src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs:47]: throw Unreachable?

File: src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+        }
+
+        public async ValueTask<SourceText> GetTextAsync(CancellationToken cancellationToken)
+        {
+            if (Text is not null)
+                return Text;
+
+            if (Storage is not { } textStorage)
```
Comment (davidwengier) [inline src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs:55]: What does this achieve over just null checking Storage and using Storage directly below?

Or even just using `Storage!` given its an invariant of the class constructor.

Comment (sharwell) [reply src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs:55]: This was a type check in a previous revision. I'll simplify it.

File: src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs (hunk 2 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs]: ➡️ Done

File: src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs (hunk 3 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs]: ➡️ Done

File: src/Workspaces/Core/Portable/Serialization/SerializerService_Asset.cs [hunk 4]
```diff
@@ -61,12 +63,24 @@ private SourceText DeserializeSourceText(ObjectReader reader, CancellationToken
...
             Contract.ThrowIfFalse(kind == SerializationKinds.Bits);
-            return SourceTextExtensions.ReadFrom(_textService, reader, encoding, cancellationToken);
+            return new SerializableSourceText(SourceTextExtensions.ReadFrom(_textService, reader, encoding, cancellationToken));
+        }
+
+        private SourceText DeserializeSourceText(ObjectReader reader, CancellationToken cancellationToken)
+        {
+            var serializableSourceText = DeserializeSerializableSourceText(reader, cancellationToken);
+            return serializableSourceText.Text ?? serializableSourceText.Storage!.ReadText(cancellationToken);
         }
```
Comment (tmat) [inline src/Workspaces/Core/Portable/Serialization/SerializerService_Asset.cs:84]: Perhaps move this logic to SerializableSourceText.

File: src/Workspaces/Remote/Core/AbstractAssetProvider.cs [hunk 5]
```diff
@@ -101,7 +101,7 @@ public async Task<DocumentInfo> CreateDocumentInfoAsync(Checksum documentChecksu
 
             var textLoader = TextLoader.From(
                 TextAndVersion.Create(
-                    await GetAssetAsync<SourceText>(documentSnapshot.Text, cancellationToken).ConfigureAwait(false),
+                    await (await GetAssetAsync<SerializableSourceText>(documentSnapshot.Text, cancellationToken).ConfigureAwait(false)).GetTextAsync(cancellationToken).ConfigureAwait(false),
```
Comment (tmat) [inline src/Workspaces/Remote/Core/AbstractAssetProvider.cs:104]: > (await GetAssetAsync<SerializableSourceText>(documentSnapshot.Text, cancellationToken).ConfigureAwait(false)) [](start = 25, length = 110)

extract to local

File: src/Workspaces/Core/Portable/Workspace/Host/TextFactory/ITextFactoryService.cs [hunk 6]
```diff
@@ -16,6 +16,8 @@ namespace Microsoft.CodeAnalysis.Host
     /// </summary>
     internal interface ITextFactoryService : IWorkspaceService
     {
+        SourceHashAlgorithm ChecksumAlgorithm { get; }
```
Comment (tmat) [inline src/Workspaces/Core/Portable/Workspace/Host/TextFactory/ITextFactoryService.cs:19]: > SourceHashAlgorithm ChecksumAlgorithm { get; } [](start = 7, length = 47)

Not sure what is this good for? All implementations return SHA1.

Comment (sharwell) [reply src/Workspaces/Core/Portable/Workspace/Host/TextFactory/ITextFactoryService.cs:19]: It ensures that the use of this property will not be missed if the implementation changes in the future.

File: src/EditorFeatures/Core/Implementation/Workspaces/EditorTextFactoryService.cs [hunk 7]
```diff
@@ -40,6 +40,11 @@ internal class EditorTextFactoryService : ITextFactoryService
 
         private static readonly Encoding s_throwingUtf8Encoding = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false, throwOnInvalidBytes: true);
 
+        /// <summary>
+        /// The default algorithm used by <see cref="SourceText"/> is <see cref="SourceHashAlgorithm.Sha1"/>.
+        /// </summary>
+        public SourceHashAlgorithm ChecksumAlgorithm => SourceHashAlgorithm.Sha1;
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/Core/Implementation/Workspaces/EditorTextFactoryService.cs:46]: i forget, but are we allowed to use sha1?  i thought that was deprecated/banned for new code.

File: src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs [hunk 8]
```diff
@@ -0,0 +1,76 @@
...
+using System.Diagnostics;
+using System.Threading;
+using System.Threading.Tasks;
+using Microsoft.CodeAnalysis.Host;
+using Microsoft.CodeAnalysis.Text;
+using Roslyn.Utilities;
+
+namespace Microsoft.CodeAnalysis.Serialization
+{
+    internal sealed class SerializableSourceText
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs:17]: doc.

File: src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs [hunk 9]
```diff
@@ -0,0 +1,76 @@
...
+    {
+        public ITemporaryTextStorageWithName? Storage { get; }
+        public SourceText? Text { get; }
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs:20]: doc that this is one or the other.

File: src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs [hunk 10]
```diff
@@ -0,0 +1,76 @@
...
+        }
+
+        public SerializableSourceText(SourceText text)
+            : this(storage: null, text)
+        {
+        }
+
+        private SerializableSourceText(ITemporaryTextStorageWithName? storage, SourceText? text)
+        {
+            Debug.Assert(storage is not null || text is not null);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs:34]:
```suggestion
            Debug.Assert(storage is not null || text is not null);
            Debug.Assert(storage is null || text is null);
```

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs:34]: or
```suggestion
            Debug.Assert(storage is null != text is null);
```

File: src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs [hunk 11]
```diff
@@ -0,0 +1,76 @@
...
+
+            Storage = storage;
+            Text = text;
+        }
+
+        public bool IsDefault => Storage is null && Text is null;
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs:40]: feels like this coudl never be true.  there are only two public entrypoints.  one requires Storage, one requires Text.  If that's not so, then something is super unclear to me and docs might help.

File: src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs [hunk 12]
```diff
@@ -0,0 +1,76 @@
...
+
+        public ImmutableArray<byte> GetChecksum()
+        {
+            Contract.ThrowIfTrue(IsDefault);
+            if (Storage is not null)
+                return Storage.GetChecksum();
+            else if (Text is not null)
+                return Text.GetChecksum();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs:48]:
```suggestion
            Storage?.GetChecksum() ?? Text.GetChecksum();
```

File: src/Workspaces/Core/Portable/Serialization/SerializerService_Asset.cs [hunk 13]
```diff
@@ -21,29 +21,31 @@ namespace Microsoft.CodeAnalysis.Serialization
...
+            else
+            {
+                RoslynDebug.AssertNotNull(text.Text);
 
-            writer.WriteInt32((int)SerializationKinds.Bits);
-            text.WriteTo(writer, cancellationToken);
+                writer.WriteInt32((int)text.Text.ChecksumAlgorithm);
+                writer.WriteEncoding(text.Text.Encoding);
+                writer.WriteInt32((int)SerializationKinds.Bits);
+                text.Text.WriteTo(writer, cancellationToken);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Serialization/SerializerService_Asset.cs:44]: on the fence if i would prefer this reading/writing in SerializableSourceText or here.  Do you prefer it here?

File: src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs (hunk 10 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs:34]: It's allowed to have both, as long as they reference the same source.

File: src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs (hunk 11 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs:40]: I was thinking this was a value type for some reason.

File: src/Workspaces/Core/Portable/TemporaryStorage/TemporaryStorageServiceFactory.cs [hunk 14]
```diff
@@ -199,6 +203,18 @@ public TemporaryTextStorage(TemporaryStorageService service, string storageName,
...
                 public long Offset => _memoryMappedInfo!.Offset;
                 public long Size => _memoryMappedInfo!.Size;
+                public SourceHashAlgorithm ChecksumAlgorithm => _checksumAlgorithm;
+                public Encoding? Encoding => _encoding;
+
+                public ImmutableArray<byte> GetChecksum()
+                {
+                    if (_checksum.IsDefault)
+                    {
+                        _checksum = ReadText(CancellationToken.None).GetChecksum();
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/TemporaryStorage/TemporaryStorageServiceFactory.cs:213]: should we do an interlocked swap here?  that way we always return the exact same array out? it feels a bit strange that i could call and normally get the same result come out, but occasionally get a different array (And that would be obersvable).

File: src/Workspaces/Core/Portable/Workspace/Host/TemporaryStorage/ITemporaryTextStorageWithName.cs [hunk 15]
```diff
@@ -0,0 +1,21 @@
...
+
+#nullable enable
+
+using System.Collections.Immutable;
+using System.Text;
+using Microsoft.CodeAnalysis.Text;
+
+namespace Microsoft.CodeAnalysis.Host
+{
+    internal interface ITemporaryTextStorageWithName : ITemporaryTextStorage, ITemporaryStorageWithName
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Workspace/Host/TemporaryStorage/ITemporaryTextStorageWithName.cs:13]: doc

File: src/Workspaces/Remote/Core/SolutionAsset.cs [hunk 16]
```diff
@@ -34,6 +33,8 @@ internal sealed class SolutionAsset
 
         public SolutionAsset(object? value, Checksum checksum, WellKnownSynchronizationKind kind)
         {
+            Contract.ThrowIfTrue(kind is WellKnownSynchronizationKind.SourceText);
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Remote/Core/SolutionAsset.cs:36]: doc/message

File: src/Workspaces/Core/Portable/Serialization/SerializerService_Asset.cs (hunk 4 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Serialization/SerializerService_Asset.cs:84]: I'm OK with it in the current location for now (same place it's always lived).

File: src/EditorFeatures/Core/Implementation/Workspaces/EditorTextFactoryService.cs (hunk 7 above)
Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/Workspaces/EditorTextFactoryService.cs:46]: ➡️ This is the only valid implementation of this property without making a behavior change outside the scope of this pull request.

File: src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs (hunk 10 above)
Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs:34]: how can you construct such a thing?  all i see are two public constructors, each which only take one value, but pass null for the other.  It seems like in all cases, it's one or the other.

File: src/Workspaces/Core/Portable/TemporaryStorage/TemporaryStorageServiceFactory.cs (hunk 14 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/TemporaryStorage/TemporaryStorageServiceFactory.cs:213]: Don't think it makes a difference but will switch it.

File: src/Workspaces/Core/Portable/Serialization/SerializerService_Asset.cs (hunk 13 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Serialization/SerializerService_Asset.cs:44]: I don't see a strong reason to move it right now. It's in the same location it was and doing essentially the same thing, plus related methods `DeserializeSerializableSourceText` and `DeserializeSourceText` appear together.

Comment (CyrusNajmabadi) [reply src/Workspaces/Core/Portable/Serialization/SerializerService_Asset.cs:44]: sgtm.

File: src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs (hunk 8 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs:21]: ➡️ Done

File: src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs (hunk 9 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs:38]: ➡️ Documented that both are allowed as long as they are the same

File: src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs (hunk 10 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs:52]: ➡️ Now documented

File: src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs (hunk 11 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs]: ➡️ Fixed by removing this property

File: src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs (hunk 12 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs]: ➡️ I made it the other way around, but fixed either way

File: src/Workspaces/Core/Portable/TemporaryStorage/TemporaryStorageServiceFactory.cs (hunk 14 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/TemporaryStorage/TemporaryStorageServiceFactory.cs]: ➡️ Done

File: src/Workspaces/Core/Portable/Workspace/Host/TemporaryStorage/ITemporaryTextStorageWithName.cs (hunk 15 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Workspace/Host/TemporaryStorage/ITemporaryTextStorageWithName.cs:16]: ➡️ Done

File: src/Workspaces/Remote/Core/SolutionAsset.cs (hunk 16 above)
Comment (sharwell) [reply src/Workspaces/Remote/Core/SolutionAsset.cs:40]: ➡️ Done

File: src/EditorFeatures/Core/Implementation/Workspaces/EditorTextFactoryService.cs (hunk 7 above)
Comment (CyrusNajmabadi) [reply src/EditorFeatures/Core/Implementation/Workspaces/EditorTextFactoryService.cs:46]: sgtm.

File: src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs [hunk 17]
```diff
@@ -0,0 +1,83 @@
...
+    /// both processes.
+    /// </summary>
+    internal sealed class SerializableSourceText
+    {
+        /// <summary>
+        /// The storage location for <see cref="SourceText"/>.
+        /// </summary>
+        /// <remarks>
+        /// At least one of <see cref="Storage"/> or <see cref="Text"/> will be non-<see langword="null"/>. If both are
+        /// provided, they must reference the same source text.
```
Comment (CyrusNajmabadi) [inline src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs:28]:
```suggestion
        /// At least one of <see cref="Storage"/> or <see cref="Text"/> will be non-<see langword="null"/>. If both are
        /// provided, they must reference the same source text.
```

i don't see who ever ends up providing both.  so the doc comment right now doesn't make sense to me. it seems to describe something that can't happen, and i'd rather it describe only the things that can.

note: you could have this comment if your private constructor ever became public.  Or you could have a comment that says "if `private SerializableSourceText(ITemporaryTextStorageWithName? storage, SourceText? text)` were to become public, then it would be ok to provide both of these as long as blah blah was true"

**Review by CyrusNajmabadi — APPROVED** [review]
LGTM.  i do request a doc change.  but it's not blocking.

**Comment by CyrusNajmabadi** [comment]
Since this hits asset serialization, i do want to make sure @tmat is ok with the overall idea here.  if there aren't concerns @tmat i'm a-ok with htis :)

File: src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs (hunk 17 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs:28]: In what scenario would this restriction change the decisions made by a consumer of this type, using the current API provided by the type?

File: src/Workspaces/Core/Portable/Workspace/Host/TextFactory/ITextFactoryService.cs (hunk 6 above)
Comment (tmat) [reply src/Workspaces/Core/Portable/Workspace/Host/TextFactory/ITextFactoryService.cs:19]: ITextFactoryService doesn't seem like the right place for this. The service is for creating buffers.

Comment (sharwell) [reply src/Workspaces/Core/Portable/Workspace/Host/TextFactory/ITextFactoryService.cs:19]: This property returns the `ChecksumAlgorithm` used for `SourceText` instances created by this service. Since this service creates the `SourceText` instances, it is the only one that can know what checksum algorithm will be used.

Comment (tmat) [reply src/Workspaces/Core/Portable/Workspace/Host/TextFactory/ITextFactoryService.cs:19]: It would be imo better to pass the alg as an argument to the methods of this interface.

Comment (sharwell) [reply src/Workspaces/Core/Portable/Workspace/Host/TextFactory/ITextFactoryService.cs]: ➡️ Property removed by using the value from serialization.

File: src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs (hunk 17 above)
Comment (sharwell) [reply src/Workspaces/Core/Portable/Serialization/SerializableSourceText.cs]: ➡️ Contract strengthened

**Review by tmat — APPROVED** [review]
:shipit:

File: src/EditorFeatures/Core/Implementation/Workspaces/EditorTextFactoryService.cs [hunk 18]
```diff
@@ -40,6 +40,11 @@ internal class EditorTextFactoryService : ITextFactoryService
...
+
```
Comment (tmat) [inline src/EditorFeatures/Core/Implementation/Workspaces/EditorTextFactoryService.cs:47]: Still needed?

Comment (sharwell) [reply src/EditorFeatures/Core/Implementation/Workspaces/EditorTextFactoryService.cs]: I dunno what you are talking about 🤣

**Comment by JayCroghan** [comment]
I see this listed as milestone 16.8.P3 but the developer community issue isn't linked as being fixed by that preview release, should I assume the defect link is missing and give it a try anyway?

**Comment by sharwell** [comment]
@jinujoseph This change is not in 16.8 Preview 3 (tagged commit b446afd). The tags are missing for 16.8 Preview 4 and newer so I'm not sure what to put here.

**Comment by jinujoseph** [comment]
@JayCroghan This will be in 16.9.p1
