### PR TITLE
C#: Improve error reporting for an Overload Resolution failure due to an ambiguity.

### LINKED ISSUE #2985: C# Error message incorrectly lists conflicting overloads
[A customer reports in DevDiv 1171723]

Given the following code

```cs
using FluentAssertions;
using Extensions;
using System;
using System.Collections.Generic;
using System.Collections;

namespace FluentAssertions
{
    public static class AssertionExtensions
    {
        public static dynamic Should(this object actualValue) { throw null; }
        public static dynamic Should(this IEnumerable actualValue) { throw null; }
        public static dynamic Should<T>(this IEnumerable<T> actualValue) { throw null; }
        public static dynamic Should<TKey, TValue>(this IDictionary<TKey, TValue> actualValue) { throw null; }
    }
}

namespace Extensions
{
    public static class TestExtensions
    {
        public static dynamic Should<TKey, TValue>(this IReadOnlyDictionary<TKey, TValue> actualValue) { throw null; }
    }
}

namespace ClassLibraryOverloadResolution
{    
    public class Class1
    {
        void foo()
        {
            Dictionary<String, String> dict = null;
            dict.Should().ContainKey("");
        }
    }
}
```

EXPECTED (copied from VS 2013):
```none
1>E:\temp\ClassLibraryOverloadResolution\ClassLibraryOverloadResolution\Class1.cs(19,13,19,26): error CS0121: The call is ambiguous between the following methods or properties: 'Extensions.TestExtensions.Should<string,string>(System.Collections.Generic.IReadOnlyDictionary<string,string>)' and 'FluentAssertions.AssertionExtensions.Should<string,string>(System.Collections.Generic.IDictionary<string,string>)'
```
ACTUAL:
```none 
1>e:\temp\ClassLibraryOverloadResolution\ClassLibraryOverloadResolution\Class1.cs(19,18,19,24): error CS0121: The call is ambiguous between the following methods or properties: 'AssertionExtensions.Should(object)' and 'AssertionExtensions.Should(IEnumerable)'
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #2985.

@VSadov, @gafter, @agocke, @jaredpar, @khyperia Please review.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MemberResolutionKind.cs [hunk 1]
```diff
@@ -103,5 +103,10 @@ internal enum MemberResolutionKind : byte
         /// 7.5.3.2 of the language specification).
         /// </summary>
         Worse,
+
+        /// <summary>
+        /// Same as <see cref="Worse"/>, but shouldn't be mentionaed in an ambiguity diagnostics.
+        /// </summary>
```
Comment (VSadov) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MemberResolutionKind.cs]: mentionEd

**Comment by VSadov** [comment]
LGTM

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MemberResolutionKind.cs (hunk 1 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MemberResolutionKind.cs]: Thanks!

Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MemberResolutionKind.cs]: OK... but then when *should* it be used?

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs [hunk 2]
```diff
@@ -1044,15 +1045,81 @@ private void RemoveWorseMembers<TMember>(ArrayBuilder<MemberResolutionResult<TMe
...
+                }
+            }
+            else if (countOfNotBestCandidates == 1)
+            {
+                for (int i = 0; i < worse.Count; ++i)
+                {
+                    Debug.Assert(!results[i].Result.IsValid || worse[i] != unknown);
+                    if (worse[i] == worseThanSomething)
+                    {
+                        if (BetterFunctionMember(results[notBestIdx], results[i], arguments.Arguments, ref useSiteDiagnostics) == BetterResult.Left)
```
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs]: Since the then and else branches are almost identical, I think this would be more clearly expressed using a ?: operator to compute the last argument (possibly into a temp).

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MemberResolutionKind.cs (hunk 1 above)
Comment (gafter) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MemberResolutionKind.cs]: I suggest

"Same as <see cref="Worse"/>, but the candidate shouldn't be mentioned in an ambiguity diagnostics."

(also corrects misspelling of mentioned)

Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/MemberResolutionKind.cs]: I will update the comment using suggested wording.

File: src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs (hunk 2 above)
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Semantics/OverloadResolution/OverloadResolution.cs]: I will make the suggested change.

**Comment by gafter** [comment]
LGTM modulo two comments.
