### PR TITLE
Fixing NullReferenceException inside ConvertToInterpolatedString

### LINKED ISSUE #20943: CSharpConvertConcatenationToInterpolatedStringRefactoringProvider encountered an error and has been disabled.
From: https://developercommunity.visualstudio.com/content/problem/78891/csharpconvertconcatenationtointerpolatedstringrefa.html

Was writing c# code for console application when all of a sudden this popup appeared right below the menu bar. "Show Stack Trace" link gives below information

```
System.NullReferenceException : Object reference not set to an instance of an object.
at Microsoft.CodeAnalysis.ConvertToInterpolatedString.AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.IsStringConcat(ISyntaxFactsService syntaxFacts,SyntaxNode expression,SemanticModel semanticModel,CancellationToken cancellationToken)
at async Microsoft.CodeAnalysis.ConvertToInterpolatedString.AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

### PR DESCRIPTION
**Pull request by Neme12**
fixes #20943

### CODE REVIEW

**Comment by Neme12** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please

**Comment by Neme12** [comment]
Note: it's disabled because dynamic could have a custom + operator.

**Comment by Neme12** [comment]
> this is probably not worth investing in

A good approach might actually be to offer the refactoring but show a warning. This is only a refactoring, not an analyzer so false positives wouldn't be an issue.

File: src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.cs [hunk 1]
```diff
@@ -190,9 +190,9 @@ private static SyntaxNode ConcatinateTextToTextNode(SyntaxGenerator generator, S
                 return false;
             }
 
-            var method = semanticModel.GetSymbolInfo(expression, cancellationToken).Symbol as IMethodSymbol;
-            return method?.MethodKind == MethodKind.BuiltinOperator &&
-                   method.ContainingType.SpecialType == SpecialType.System_String &&
+            return semanticModel.GetSymbolInfo(expression, cancellationToken).Symbol is IMethodSymbol method &&
+                   method.MethodKind == MethodKind.BuiltinOperator &&
+                   method.ContainingType?.SpecialType == SpecialType.System_String &&
```
Comment (CyrusNajmabadi) [inline src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.cs]: @sharwell @jasonmalinowski This is rather interesting.  We have a MethodSymbol without a null ContainingType.  I'm pretty certain there will be a lot of codepaths in the IDE that will not be resilient to this sort of thing.  The presumption was that fields/props/events/methods would all be contained in types (possibly the implicit script class for scripts).

Comment (jasonmalinowski) [reply src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.cs]: Ouch, that's interesting indeed. 😦 @jaredpar or maybe @jcouv do we know more when this can happen?

Comment (jcouv) [reply src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.cs]: I'll take a look, that does seem wrong.
What's the expression used in `semanticModel.GetSymbolInfo` in this example?

Filed https://github.com/dotnet/roslyn/issues/25377

Comment (Neme12) [reply src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.cs]: it's a binary + expression involving dynamic

Comment (CyrusNajmabadi) [reply src/Features/Core/Portable/ConvertToInterpolatedString/AbstractConvertConcatenationToInterpolatedStringRefactoringProvider.cs]: Perhaps the compiler synthesizes methods for dynamic invocations?  But then doesn't have an INamedTypeSymbol to place them on (because IDynamicTypeSymbol isn't an INamedTypeSymbol). (Just spitballing).

However, for this case, it would be nice if we could synthesize a type.  Similar to how top level members in script code belong to an implicit named type representing the script class.

**Comment by Neme12** [comment]
retest windows_debug_vs-integration_prtest please
