### PR TITLE
Report error creating delegate from partial generic method without implementation

### LINKED ISSUE #72431: KeyNotFoundException thrown when compiling optional generic partial methods (no modifier)
**Version Used**:  Microsoft (R) Visual C# Compiler version 4.9.0-3.24121.1 (a98c90d5)

**Steps to Reproduce**:

Unfortunately I cannot reproduce it in a new project so I do not know what causes it. I hope you can find out from the stack trace. Originally reported at dotnet/sdk#39033:

I have a class with this declaration:

```
partial void AddPlatformDailyRewards<T>(MauiAppBuilder builder) where T : DailyRewardItem;
```

According to [the documentation](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/partial-method), I should not need to implement this mehtod. However, if I do not implement it for each platform, I would encounter this issue when **building** (the exception is from CSC.exe):

```
16:18:31:714	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error : Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at System.ThrowHelper.ThrowKeyNotFoundException()
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.FullMetadataWriter.GetMethodDefinitionHandle(IMethodDefinition def)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataWriter.GetMethodDefinitionOrReferenceHandle(IMethodReference methodReference)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MethodSpecComparer.GetHashCode(IGenericMethodInstanceReference methodInstanceReference)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataWriter.InstanceAndStructuralReferenceIndex`1.TryGetValue(T item, Int32& index)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.FullMetadataWriter.GetOrAddMethodSpecificationHandle(IGenericMethodInstanceReference reference)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataWriter.GetMethodHandle(IMethodReference methodReference)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataWriter.GetHandle(Object reference)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataWriter.ResolveEntityHandleFromPseudoToken(Int32 pseudoSymbolToken)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataWriter.WriteInstructions(Blob finalIL, ImmutableArray`1 generatedIL, UserStringHandle& mvidStringHandle, Blob& mvidStringFixup)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataWriter.SerializeMethodBody(MethodBodyStreamEncoder encoder, IMethodBody methodBody, StandaloneSignatureHandle localSignatureHandleOpt, UserStringHandle& mvidStringHandle, Blob& mvidStringFixup)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataWriter.SerializeMethodBodies(BlobBuilder ilBuilder, PdbWriter nativePdbWriterOpt, Blob& mvidStringFixup)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.MetadataWriter.BuildMetadataAndIL(PdbWriter nativePdbWriterOpt, BlobBuilder ilBuilder, BlobBuilder mappedFieldDataBuilder, BlobBuilder managedResourceDataBuilder, Blob& mvidFixup, Blob& mvidStringFixup)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean metadataOnly, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.Compilation.SerializePeToStream(CommonPEModuleBuilder moduleBeingBuilt, DiagnosticBag metadataDiagnostics, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getMetadataPeStreamOpt, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, RebuildData rebuildData, Boolean metadataOnly, Boolean includePrivateMembers, Boolean isDeterministic, Boolean emitTestCoverageData, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider metadataPEStreamProvider, EmitStreamProvider pdbStreamProvider, RebuildData rebuildData, Func`2 testSymWriterFactory, DiagnosticBag diagnostics, EmitOptions emitOptions, Nullable`1 privateKeyOpt, CancellationToken cancellationToken)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 generators, ImmutableArray`1 additionalTextFiles, AnalyzerConfigSet analyzerConfigSet, ImmutableArray`1 sourceFileAnalyzerConfigOptions, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, ErrorLogger errorLogger, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, AnalyzerDriver& analyzerDriver, Nullable`1& generatorTimingInfo)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[T](Func`2 func)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter, String pipeName)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc, CompileOnServerFunc compileOnServerFunc, ICompilerServerLogger logger)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.MainCore(String[] args)
16:18:31:767	2>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
16:18:34:793	2>Done building project "MyProjectName.csproj" -- FAILED.
```

VS Error List also goes crazy and list each exception line as an error:

image

If I run `dotnet build` from the CLI instead of VS, at least I get the detailed info of which causes the problem:

```
C:\Program Files\dotnet\sdk\8.0.200\Roslyn\Microsoft.CSharp.Core.targets(84,5): error : Unhandled exception. System.Col
lections.Generic.KeyNotFoundException: The given key '<ProjectName>.SetupOptions.AddPlatformDailyRewards<T>(Microsoft.Maui.Hosting.MauiAppBuilder)' was not present in the dictionary.
```

By adding an empty implementation to all files (iOS/Windows etc), the error disappears.

**Diagnostic Id**: N/A

**Expected Behavior**: The build should be successful as the method is optional. At least it should tell me where the problem is.

**Actual Behavior**: Exception is thrown by CSC.

### PR DESCRIPTION
**Pull request by cston**
Fixes #72431.

### CODE REVIEW

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs [hunk 1]
```diff
@@ -2788,7 +2788,7 @@ static ErrorCode getRefMismatchErrorCode(TypeKind type)
                 return true;
             }
 
-            var sourceMethod = selectedMethod as SourceOrdinaryMethodSymbol;
+            var sourceMethod = selectedMethod.OriginalDefinition as SourceOrdinaryMethodSymbol;
             if (sourceMethod is object && sourceMethod.IsPartialWithoutImplementation)
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:2792]: >IsPartialWithoutImplementation [](http://example.com/codeflow?start=55&length=30)

Consider checking other use sites of this API

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 1)

**Comment by AlekseyTs** [comment]
Consider adding similar tests for VB

File: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs (hunk 1 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:2792]: There was only one other use of `IsPartialWithoutImplementation`, in `CallsAreOmitted()`.

**Comment by cston** [comment]
> Consider adding similar tests for VB

Thanks, the same issue existed in VB.

---
In reply to: [2061785068](https://github.com/dotnet/roslyn/pull/73060#issuecomment-2061785068) [](http://example.com/codeflow?ancestors=2061785068)

File: src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs [hunk 2]
```diff
@@ -12012,6 +12012,52 @@ public static int Main()
...
+        [Fact]
+        public void CS0762ERR_PartialMethodToDelegate_02()
+        {
+            var source = """
+                delegate void D();
+                partial class Program
+                {
+                    static void Main()
+                    {
+                        M1(M2<int>);
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Test/Semantic/Semantics/SemanticErrorTests.cs:12025]: Is there also a bug when using a method group like `GenericType<int>.PartialMethod`?

**Review by RikkiGibson — APPROVED** [review]

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 3)
