### PR TITLE
Remove duplication in AbstractSymbolCompletionProvider.CreateItems

### LINKED ISSUE #36080: "Sequence contains no elements" in AbstractSymbolCompletionProvider for shared files
**Version Used**: 
3.1.0-beta4-19261-04+33cfe1a0905264d80633c5154de57de6c0bb94a0

**Steps to Reproduce**:

1. Create Shared Project and 2 Console projects
2. Reference Shared Project from other 2 projects and add SomeClass.cs
3. Type something in SomeClass.cs that would invoke code completion

**Expected Behavior**:
No exception is thrown/logged
**Actual Behavior**:
Our log is being spammed by:
```
ERROR [2019-05-30 12:11:17Z]: Roslyn non-fatal exception
System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00011] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/external/corefx/src/System.Linq/src/System/Linq/First.cs:19 
  at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.CreateItems (System.Collections.Generic.Dictionary`2[TKey,TValue] originatingContextMap, System.Collections.Generic.Dictionary`2[TKey,TValue] invalidProjectMap, System.Collections.Generic.List`1[T] totalProjects, System.Boolean preselect, System.Collections.Immutable.ImmutableArray`1[T] inferredTypes) [0x0002a] in /_/src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs:162 
  at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.GetItemsWorkerAsync (Microsoft.CodeAnalysis.Document document, System.Int32 position, Microsoft.CodeAnalysis.Options.OptionSet options, System.Boolean preselect, System.Threading.CancellationToken cancellationToken) [0x002b8] in /_/src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs:352 
  at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.ProvideCompletionsAsync (Microsoft.CodeAnalysis.Completion.CompletionContext context) [0x001f2] in /_/src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs:320 
```
I was able to reproduce this also on Windows(debugging VS) but apparently it's sent to Watson instead of logging into a file...

### PR DESCRIPTION
**Pull request by jasonmalinowski**
We had two overloads of AbstractSymbolCompletionProvider.CreateItems, once which handles the case of a single file and one that handles linked files. The code is almost identical, but the linked file one incorrectly handled the case of not having any symbols. Rather than fixing the bug in just that branch, I'm refactoring it to simply remove the second copy so both the single file and linked file cases
go through the same helper. The intent here is to avoid hiding simple bugs that had nothing to do with linked files in the linked-file-only path.

Fixes #36080 by virtue of deleting the offending code entirely. No new tests are added since I've confirmed that the existing tests (once the refactoring was complete) would have been sufficient for discovering this problem.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Yaaay, dedupe. 

It's also worth noting that hte entire internal architecture of completion is pretty awful.  There's a lot of independent calls to compute information, lots of which have to recompute intermediary state computed by prvious passes.  There's a lot of opportunity for cleanup and dedupe here, that will likely also improve perf a lot.

File: src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs [hunk 1]
```diff
@@ -153,67 +102,44 @@ private bool ShouldIncludeInTargetTypedCompletionList(ISymbol symbol, ImmutableA
...
 
-        private CompletionItem AddTargetTypeMatchTagIfAppropriate(
-            CompletionItem item,
-            Dictionary<ISymbol, SyntaxContext> originatingContextMap,
-            ImmutableArray<ITypeSymbol> inferredTypes,
-            IGrouping<(string displayText, string suffix, string insertionText), ISymbol> symbolGroup)
-        {
-            foreach (var symbol in symbolGroup)
-            {
-                foreach (var syntaxContext in originatingContextMap.Values)
```
Comment (jasonmalinowski) [inline src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs]: Deleting this code is also fixing a potentially big perf problem: to determine if a target type matched, we were accidentally binding each symbol up to _n_ times, where _n_ is the number of _total_ symbols in the list. This should have been only finding the syntaxContexts for the symbol by looking it up in the dictionary, but instead by matching all was binding far more than it needed to.

Comment (dpoeschl) [inline src/Features/Core/Portable/Completion/Providers/AbstractSymbolCompletionProvider.cs]: 🤦‍♂️👏

**Comment by jasonmalinowski** [comment]
Tagging @jinujoseph for delegated M2 approval.

**Comment by dpoeschl** [comment]
I'm testing this out locally as well.
