### PR TITLE
Do not restrict to type argument list context when a name could resolve to a generic and a non-generic symbol

### LINKED ISSUE #25572: Variable name missing from completion after <
**Version Used**: 
Roslyn 2.7.0 that shipped in VS 15.6

**Steps to Reproduce**:

1. Create new C# console app
2. Replace the Program.cs text with this
```
using System.Collections.Generic;
using System.Linq;

class C
{
    void M()
    {
        int foo;
        List<int> list;
        if (list.Count < $$)
        {
        }
    }
}
```
3. Retype $$

**Expected Behavior**:
The identifier `foo` should be in completion

**Actual Behavior**:
It is not in completion

### PR DESCRIPTION
**Pull request by Rekkonnect**
Fixes #25572

The new solution requires that all the symbols the name may resolve to are named types or methods and there exists at least one generic symbol of the aforementioned kinds in order to restrict the context into a generic type argument list. Otherwise, the context is not enforced as a generic type argument list.

### CODE REVIEW

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs [hunk 1]
```diff
@@ -1017,7 +1017,7 @@ public static bool IsGenericConstraintContext(this SyntaxTree syntaxTree, Syntax
             }
 
             var symbols = semanticModelOpt.LookupName(nameToken, cancellationToken);
-            return symbols.Any(static s =>
+            return symbols.All(static s =>
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs:1020]: needs docs.

**Comment by Rekkonnect** [comment]
When run locally, the failing test case (`Nested_AllKinds`) passes with both arguments, could it be an issue not caused by this PR?

File: src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs [hunk 2]
```diff
@@ -12391,6 +12391,57 @@ void M(string s)
...
+
+                    void A() { }
+                    void A<T>() { }
+                }
+                
+                """;
+
+            await VerifyItemExistsAsync(source, "other");
+            await VerifyItemExistsAsync(source, "System");
+            await VerifyItemExistsAsync(source, "C");
```
Comment (CyrusNajmabadi) [inline src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs:12442]: i don't get thsi case.  here, this could only be a case where we want type arguments, so why is 'other' showing up?

Comment (Rekkonnect) [reply src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs:12442]: As I explained in the description, this PR makes it so that it handles the case the user wants to type `other.A < other.B`, even if both are method groups, and comparison with `<` would be invalid. If we do not want that behavior, we will go with requiring that the context is in a type argument list if the conflicting symbols are only either types or methods, and at least one of them is generic.

Comment (CyrusNajmabadi) [reply src/EditorFeatures/CSharpTest/Completion/CompletionProviders/SymbolCompletionProviderTests.cs:12442]: > this PR makes it so that it handles the case the user wants to type other.A < other.B, even if both are method groups, and comparison with < would be invalid.

 I don't see that as good thing.  

Let's go with something that makes sense here :)

**Review by CyrusNajmabadi — APPROVED** [review]

File: src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs [hunk 3]
```diff
@@ -1032,6 +1036,10 @@ public static bool IsGenericConstraintContext(this SyntaxTree syntaxTree, Syntax
                     _ => false,
                 };
             });
+            if (!anyGeneric)
```
Comment (CyrusNajmabadi) [inline src/Workspaces/SharedUtilitiesAndExtensions/Workspace/CSharp/Extensions/ContextQuery/SyntaxTreeExtensions.cs:1039]:
```suggestion

            if (!anyGeneric)
```

**Comment by CyrusNajmabadi** [comment]
Thanks!
