### PR TITLE
Catch deconstruction ref escape errors in invocation escape analysis

### LINKED ISSUE #64000: Code that compiles on dotnet 6 gives compile errors on dotnet 7 preview
It seems dotnet 7 preview may have broken language specification? 

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Markup/Avalonia.Markup/Markup/Parsers/BindingExpressionGrammar.cs#L302

This line compiles fine targetting net6.0, but targetting net7.0 it gives the following compile error...

```
C:\Users\danwa\source\repos\Avalonia\src\Markup\Avalonia.Markup\Markup\Parsers\BindingExpressionGrammar.cs(302,79): err
or CS8168: Cannot return local 'reader' by reference because it is not a ref local 
```

### LINKED ISSUE #64448: Unnecessary ref safety error reported for deconstruction
Compile:
```csharp
ref struct R
{
    public R(ref int i) { }
    public void Deconstruct(out int x, out int y) => throw null;
}

class Program
{
    static void Main()
    {
        int i = 0;
        var r = new R(ref i);

        int x, y;
        (x, y) = r;                  // error CS8352: 'r' ... may expose referenced variables
        r.Deconstruct(out x, out y); // ok
    }
}
```
Expected: No errors

Actual:
```
(15, 18): error CS8352: Cannot use variable 'r' in this context because it may expose
    referenced variables outside of their declaration scope
```

### PR DESCRIPTION
**Pull request by cston**
Fixes #64000

The first commit contains tests only, no compiler changes.

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 1]
```diff
@@ -8026,6 +8026,793 @@ .maxstack  4
...
+                Diagnostic(ErrorCode.ERR_BadTypeArgument, "y").WithArguments("System.Span<int>").WithLocation(8, 19),
+                // (8,22): error CS0306: The type 'Span<int>' may not be used as a type argument
+                //         (x, y) = (y, x);
+                Diagnostic(ErrorCode.ERR_BadTypeArgument, "x").WithArguments("System.Span<int>").WithLocation(8, 22));
+        }
+
+        [Theory]
+        [InlineData(LanguageVersion.CSharp10)]
+        [InlineData(LanguageVersion.CSharp11)]
+        public void Deconstruct_11(LanguageVersion languageVersion)
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:8630]: `Deconstruct_11`, `_12`, `_13` test `var` deconstruction declarations which should be addressed by https://github.com/dotnet/roslyn/pull/64414.

**Comment by cston** [comment]
@dotnet/roslyn-compiler, please review, thanks.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 2]
```diff
@@ -8026,6 +8026,793 @@ .maxstack  4
...
+        [WorkItem(64448, "https://github.com/dotnet/roslyn/issues/64448")]
+        [Theory]
+        [InlineData(LanguageVersion.CSharp10)]
+        [InlineData(LanguageVersion.CSharp11)]
+        public void Deconstruct_02A(LanguageVersion languageVersion)
+        {
+            var source =
+@"ref struct R1
+{
+    public R1(ref int i) { }
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:8078]: Consider having the constructor look like this 

```csharp
public R1(Span<int> span) { }
```

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 3]
```diff
@@ -8026,6 +8026,793 @@ .maxstack  4
...
+ref struct R2
+{
+    public R2(ref int i) { }
+}
+class Program
+{
+    static void F1()
+    {
+        int i = 1;
+        var r = new R1(ref i);
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:8090]: Then here do the following:

```csharp
var r = new R1(stackalloc int[42]);
```

Together those two changes will make the errors uniform through the language versions.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 4]
```diff
@@ -8026,6 +8026,793 @@ .maxstack  4
...
+                    //         r.Deconstruct(out x1, out y1); // 2
+                    Diagnostic(ErrorCode.ERR_CallArgMixing, "r.Deconstruct(out x1, out y1)").WithArguments("R1.Deconstruct(out int, out R2)", "this").WithLocation(19, 9));
+            }
+        }
+
+        [WorkItem(64448, "https://github.com/dotnet/roslyn/issues/64448")]
+        [Theory]
+        [InlineData(LanguageVersion.CSharp10)]
+        [InlineData(LanguageVersion.CSharp11)]
+        public void Deconstruct_02B(LanguageVersion languageVersion)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:8133]: Same feedback here.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 5]
```diff
@@ -8026,6 +8026,793 @@ .maxstack  4
...
+                    //         s.Deconstruct(out x1, out y1); // 2
+                    Diagnostic(ErrorCode.ERR_CallArgMixing, "s.Deconstruct(out x1, out y1)").WithArguments("Program.Deconstruct(System.ReadOnlySpan<int>, out int, out R)", "s").WithLocation(14, 9));
+            }
+        }
+
+        [WorkItem(64448, "https://github.com/dotnet/roslyn/issues/64448")]
+        [Theory]
+        [InlineData(LanguageVersion.CSharp10)]
+        [InlineData(LanguageVersion.CSharp11)]
+        public void Deconstruct_05(LanguageVersion languageVersion)
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:8399]: Same feedback here.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 6]
```diff
@@ -8026,6 +8026,793 @@ .maxstack  4
...
+        {
+            var source =
+@"using System;
+ref struct R1
+{
+    public void Deconstruct(out R2 x, out R2 y) => throw null;
+}
+ref struct R2
+{
+    public R2(ref int i) { }
```
Comment (jaredpar) [inline src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:8477]: Same feedback here.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs (hunk 3 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:8090]: The new tests include a number of `Span<int>` / `stackalloc` tests to test that the errors are uniform across language versions. For these tests, I was interested in the differences between language versions as well.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs (hunk 4 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:8133]: Removed 2A and 2B (the equivalent Span<T> cases were 4A and 4B).

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs (hunk 3 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:8090]: Removed 2A and 2B (the equivalent Span<T> cases were 4A and 4B).

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs (hunk 2 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:8078]: Removed test. The `Span<int>` case is covered in 4A.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs (hunk 5 above)
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:8399]: Removed 5 (the equivalent Span<T> case was 6).

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 7]
```diff
@@ -8026,6 +8026,591 @@ .maxstack  4
...
+        R2 y = new R2(stackalloc byte[1]);
+        R2 z1 = new R2(stackalloc byte[1]);
+        (x, (y, z1)) = s;
+        R2 z2 = default;
+        (x, (y, z2)) = s; // 1
+    }
+    static void Deconstruct(this Span<int> s, out R2 x, out R1 y) => throw null;
+}";
+            var comp = CreateCompilationWithSpanAndMemoryExtensions(source, parseOptions: TestOptions.Regular.WithLanguageVersion(languageVersion));
+            if (languageVersion == LanguageVersion.CSharp10)
```
[the remark this answers is not in the document]
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:8305]: The parameter in the `ERR_CallArgMixing` diagnostic is different: 'x' vs. 'this'.

File: src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs [hunk 8]
```diff
@@ -8026,6 +8026,591 @@ .maxstack  4
...
+}";
+            var comp = CreateCompilationWithSpanAndMemoryExtensions(source, parseOptions: TestOptions.Regular.WithLanguageVersion(languageVersion));
+            comp.VerifyEmitDiagnostics();
+        }
+
+        [WorkItem(64448, "https://github.com/dotnet/roslyn/issues/64448")]
+        [Theory]
+        [InlineData(LanguageVersion.CSharp10)]
+        [InlineData(LanguageVersion.CSharp11)]
+        public void Deconstruct_02B(LanguageVersion languageVersion)
```
[the remark this answers is not in the document]
Comment (cston) [reply src/Compilers/CSharp/Test/Semantic/Semantics/RefFieldTests.cs:8096]: I'd considered combining with the previous test - either with a `Span<int>` parameter to the test method, or having two methods in the test, one for `Span<int>` and one for `ReadOnlySpan<int>` - but two separate test methods seemed easy to read.

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs [hunk 9]
```diff
@@ -1128,7 +1128,7 @@ private void CheckRestrictedTypeReceiver(BoundExpression expression, CSharpCompi
 
             if (!gotError)
             {
-                gotError = !CheckInvocationArgMixing(
+                CheckInvocationArgMixing(
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs:1131]: It wasn't clear to me why we no longer update 'gotError' here.

File: src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs [hunk 10]
```diff
@@ -304,7 +305,7 @@ private BoundExpression FixTupleLiteral(ArrayBuilder<DeconstructionVariable> che
                 {
                     var elementSyntax = syntax.Kind() == SyntaxKind.TupleExpression ? ((TupleExpressionSyntax)syntax).Arguments[i] : syntax;
 
-                    hasErrors |= !MakeDeconstructionConversion(tupleOrDeconstructedTypes[i], elementSyntax, rightSyntax, diagnostics,
+                    hasErrors |= !MakeDeconstructionConversion(tupleOrDeconstructedTypes[i], elementSyntax, rightSyntax, LocalScopeDepth, diagnostics,
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs:308]: It looks like the valEscape we pass here doesn't affect things in practice, but it would be more strictly correct/robust to pass 'rightEscape' here.

Consider a scenario like the following

```cs
    public RS M2(RS a, RS b, RS c, RS d) {
        (a, scoped var bc) = d;
        b = bc;
        return b;
    }
```

The variable we're converting here is essentially 'var bc', and we're declaring it as implicitly 'scoped' by passing 'LocalScopeDepth' as the val escape. But then the way we use it is to immediately assign it out to the variables it's ultimately bound for.

File: src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs [hunk 11]
```diff
@@ -138,10 +138,13 @@ internal BoundExpression BindDeconstruction(AssignmentExpressionSyntax node, Bin
             }
 
             Conversion conversion;
+            // Among other things, MakeDeconstructionConversion() will handle
+            // value escape analysis for the Deconstruct() method group.
```
Comment (RikkiGibson) [inline src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs:142]: note that this escape analysis eventually occurs through the already existing call to `BindMethodGroupInvocation` on the synthesized `Deconstruct` call.

File: src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs (hunk 9 above)
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/Binder_Invocation.cs:1131]: If the `BoundCall` returned from binding the `Deconstruct()` method has errors, the caller, `MakeDeconstructionConversion()` will avoid setting inferred types for deconstructed variables and will result in type inference errors. But `CheckInvocationArgMixing()` should only affect which ref safety diagnostics are reported for the method call, it should not affect whether the `BoundCall` has errors, or the resulting type inference.

File: src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs [hunk 12]
```diff
@@ -245,6 +245,7 @@ private BoundExpression FixTupleLiteral(ArrayBuilder<DeconstructionVariable> che
                         TypeSymbol type,
                         SyntaxNode syntax,
                         SyntaxNode rightSyntax,
+                        uint rightEscape,
```
[the remark this answers is not in the document]
Comment (cston) [reply src/Compilers/CSharp/Portable/Binder/Binder_Deconstruct.cs:248]: Renamed to `rightValEscape`, keeping the prefix to match `rightSyntax`.

**Review by RikkiGibson — APPROVED** [review]

**Review by jaredpar — APPROVED** [review]
