### PR TITLE
Fix crash for local function with MaybeNullWhenAttribute

### LINKED ISSUE #41479: Local function with [MaybeNullWhen(false)] crashes in nullable analysis
This is a bug in the local-function-attributes feature branch.

Sample:
```cs
#nullable enable

using System.Diagnostics.CodeAnalysis;

class C
{
    void M()
    {
        _ = tryGetValue(out string? s);
        bool tryGetValue<T>([MaybeNullWhen(false)] out T t)
        {
            t = default;
            return false;
        }
    }
}
```

This code throws a NullReferenceException about 'other' being null here:
```
NullableWalker.Join(ref NullableWalker.LocalState self, ref NullableWalker.LocalState other) Line 8247
NullableWalker.VisitLocalFunctionUse(LocalFunctionSymbol symbol, NullableWalker.LocalFunctionState localFunctionState, SyntaxNode syntax, bool isCall) Line 1804
AbstractFlowPass<NullableWalker.LocalState, NullableWalker.LocalFunctionState>.VisitLocalFunctionUse(LocalFunctionSymbol symbol, SyntaxNode syntax, bool isCall) Line 1176
NullableWalker.VisitCall(BoundCall node) Line 3465
```

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #41479

### CODE REVIEW

File: src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs [hunk 1]
```diff
@@ -5545,6 +5614,97 @@ void M<T>([AllowNull] T t1, T t2)
...
+using System.Diagnostics.CodeAnalysis;
+
+class C
+{
+    void M<TOuter>()
+    {
+        getDefault<string>().ToString(); // 1
+        getDefault<string?>().ToString(); // 2
+        getDefault<int>().ToString();
+        getDefault<int?>().ToString();
```
Comment (cston) [inline src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: Should this be `_ = getDefault<int?>.Value; // 3`

Comment (RikkiGibson) [reply src/Compilers/CSharp/Test/Semantic/Semantics/LocalFunctionTests.cs]: Yeah it seems like that would be a more meaningful test.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 2]
```diff
@@ -1801,7 +1801,21 @@ private void VisitStatementsWithLocalFunctions(BoundBlock block)
...
+            {
+                state = StateWhenTrue.Clone();
+                state.Join(in StateWhenFalse);
+            }
+            else
+            {
+                state = State;
+            }
+
+            if (Join(ref localFunctionState.StartingState, ref state) &&
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >if (Join(ref localFunctionState.StartingState, ref state) && [](start = 12, length = 60)

Perhaps I am just confused by the terminology used here, but it feels like the ```state``` is a state after the call,  whereas StartingState implies it is a state on entry into the function, i.e. before the call. Why would we want to "Join" them?

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: /cc @agocke in case you want to weigh in here.

It seems like the state we want to join into the local function's StartingState is one where all arguments have been visited, but postconditions from the call have not yet been applied.

The current implementation can cause diagnostics which seem undesirable:
```cs
void M()
{
    var s = ""hello"";

    local1(out s);

    bool local1([MaybeNullWhen(false)] out string s1)
    {
        s.ToString(); // currently warns, but probably shouldn't
        s1 = ""world"";
        return true;
    }
}
```

Comment (jcouv) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: > It seems like the state we want to join into the local function's StartingState is one where all arguments have been visited, but postconditions from the call have not yet been applied.

Good point. Maybe we should call `VisitLocalFunctionUse` at the start of `VisitCall` rather than as we currently do (at the end of `VisitCall`.

That said, I'm not sure if that's Aleksey's question. 
The way I understand it: the reason why we `Join` is that we want to get the worst case state at the start of all local function invocations, then we'll analyze the local function with that state.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: It also seems like a similar bug is permitting us to use variables which have not been definitely assigned. I will try to fix both issues in this PR.

```cs
void M()
{
    string s0;
    local1(out s0);

    void local1(out string s1)
    {
        s0.ToString(); // should produce an error, but doesn't
        s1 = ""hello"";
    }
}
```

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: It seems like a little refactoring is needed to fix the definite assignment issue. Will file a separate issue and fix in a different PR.

Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: Filed #41631

**Comment by RikkiGibson** [comment]
Please let me know if you have any further comments/concerns @AlekseyTs.

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs [hunk 3]
```diff
@@ -1801,7 +1801,21 @@ private void VisitStatementsWithLocalFunctions(BoundBlock block)
             SyntaxNode syntax,
             bool isCall)
         {
-            if (Join(ref localFunctionState.StartingState, ref State) &&
+            // When we are in a conditional state after analyzing a call to a local function,
```
Comment (AlekseyTs) [inline src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: >When we are in a conditional state after analyzing a call to a local function, [](start = 15, length = 78)

Consider adjusting the comment to reflect what state we are dealing with.

**Comment by AlekseyTs** [comment]
>         protected override void VisitLocalFunctionUse(

Do we ever expect this method called by a base class? How do we ensure it is called at the right time for the purpose of nullable analysis? Consider if we can throw from the override and use a different name for a method that we call in the NullableWalker.

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:1798 in 406d19d. [](commit_id = 406d19d577f8d689909ae0131dda264e2686a07a, deletion_comment = False)

File: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs (hunk 3 above)
Comment (RikkiGibson) [reply src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs]: It actually feels like we should be able to replace my change which temporarily merges the conditional states, with a `Debug.Assert(!IsConditionalState)` here. Since I do not expect to be in a conditional state after analyzing the call arguments, but before analyzing the call postconditions. Will verify.

**Comment by RikkiGibson** [comment]
>         protected override void VisitLocalFunctionUse(

I think we can make this override throw an exception and define a non-virtual method in this class instead.

I'm actually a little surprised that some of these parameters are unused, such as isCall. It makes it seem like we analyze the local function usage as if it's being called whenever we convert the local function to a delegate. The base method only joins the state if it is a call, and otherwise it just marks the local function as visited.

---
In reply to: [585468456](https://github.com/dotnet/roslyn/pull/41597#issuecomment-585468456) [](ancestors = 585468456)

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/NullableWalker.cs:1798 in 406d19d. [](commit_id = 406d19d577f8d689909ae0131dda264e2686a07a, deletion_comment = False)

**Comment by RikkiGibson** [comment]
The lingering issues such as "why do we analyze a delegate conversion as if it is a call" I think I will need to push off to another PR.

**Comment by RikkiGibson** [comment]
@AlekseyTs please let me know if I have adequately addressed your comments.
