### PR TITLE
Prevent spurious warnings about missing dependencies

### LINKED ISSUE #3020: AnalyzerDependencyChecker creates spurious warnings in the Error List
Analyzer assemblies with code fixes end up with a reference to System.Composition.AttributedModel. The `AnalyzerDependencyChecker` verifies that all of an analyzer assembly's references are either satisfied by other analyzer assemblies, or are already loaded in the process. System.Composition.AttributedModel ships with VS but may not be loaded when this check is performed, leading us to create an unhelpful warning in the error list:

> Analyzer assembly 'D:\Roslyn\Main\Open\Binaries\Debug\Microsoft.CodeAnalysis.FxCopAnalyzers.dll' depends on 'System.Composition.AttributedModel, Version=1.0.27.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' but it was not found. Analyzers may not run correctly.

Within VS we should just white-list all assemblies that start with "System"; that is, assume that even if we don't know where they are and they aren't already loaded, they will be found by VS when and if needed.

This would also bring us in line with the behavior of VBCSCompiler.exe.

### Repro Steps ###

1. Create a new C# Console Application project.
2. Add Microsoft.CodeAnalysis.FxCopAnalyzers.dll and Microsoft.CodeAnalysis.CSharp.FxCopAnalyzers.dll as analyzer references.
3. Save the project.
4. Restart VS.
5. Open the console application project again.

#### Expected Behavior ####
No warnings in the error list.

#### Actual Behavior ####
The above warning appears for each of the analyzer references.

### PR DESCRIPTION
**Pull request by tmeschter**
**Bug:** Fixes #3020.

**Customer Scenario**
1. User adds any analyzer assembly that includes a code fix to their project (e.g.,  Microsoft.CodeAnalysis.FxCopAnalyzers.dll or Microsoft.CodeAnalysis.CSharp.FxCopAnalyzers.dll).
2. Users saves their project and restarts VS.
3. User reopens the same project.
4. User gets spurious warnings about 'System.Composition.AttributedModel' not being found and analyzers possibly not working. Closing and reopening the project sometimes helps, but more often than not the warnings show up.

**Fix Description**
The fix updates the `AnalyzerDependencyChecker` to allow whitelisting arbitrary sets of assemblies, not just those already loaded. This is used to then whitelist all assemblies with a name starting with "System" on the assumption that even if they are not already loaded they will in fact be found if needed. If an analyzer reference appears on any whitelist we won't report it as missing, even if we don't know where it is.

**Testing**
I tested the customer scenario listed above, and also tested that missing assemblies that *don't* start with 'System' as still reported.

@ManishJayaswal This is ready for ship room.
@srivatsn @mavasani @shyamnamboodiripad @jmarolf @heejaechang Could you take a look, please?

### CODE REVIEW

**Comment by mavasani** [comment]
:+1:

**Comment by jmarolf** [comment]
:+1:

**Comment by ManishJayaswal** [comment]
Approved 5/26 by ML Shiproom.

**Comment by pharring** [comment]
:+1:

File: src/VisualStudio/Core/Def/Implementation/AnalyzerDependencyCheckingService.cs [hunk 1]
```diff
@@ -20,6 +20,7 @@ namespace Microsoft.VisualStudio.LanguageServices.Implementation
     internal sealed class AnalyzerDependencyCheckingService
     {
         private static readonly object s_dependencyConflictErrorId = new object();
+        private static readonly IAssemblyWhiteList s_systemPrefixWhiteList = new AssemblyNamePrefixWhiteList("System");
```
Comment (sharwell) [inline src/VisualStudio/Core/Def/Implementation/AnalyzerDependencyCheckingService.cs]: :question: Should this include **mscorlib** as well? See DotNetAnalyzers/StyleCopAnalyzers#1345 for reference.
